### ISSUE TITLE
Allow for user specified keyfiles to be used on borg init

### ISSUE THREAD

**Issue by dfloyd888** [borgbackup/borg#1009]
What would be useful would be a feature to allow existing keyfiles (either an existing keyfile in the config, or a hash from an existing file) to be used on creation of a new repository.  Used wisely, this would minimize the amount of data that has to be kept secure, but yet accessible.  It also means that one can ensure that a backup from today would have a keyfile for future repositories.

**Comment by enkore** [comment]
#1001? (#964, #962)

**Comment by dfloyd888** [comment]
Thank you.  That definitely addresses what I was looking for.
