### ISSUE TITLE
What is borg serve --remote-path?

### ISSUE THREAD

**Issue by ProgVal** [borgbackup/borg#1014]
The doc says `set remote path to executable (default: "borg")`, but I am not really sure what that mean.

Does `borg serve` call itself a command, which could be either `borg` (the default), `ssh foo@bar borg`, …?

**Comment by ThomasWaldmann** [comment]
it is for cases when `borg` is not in the path. or the executable name is not just `borg`, but e.g. `borg-1.0.2`.

when the client invokes `borg serve`, it first establishes a ssh connection to the server and then executes `borg serve ...` there (or `/whatever/borg-1.0.2 serve ...`).

**Comment by ProgVal** [comment]
What is the point for a client to invoke `borg serve` locally?

**Comment by enkore** [comment]
It invokes it on the server, through SSH.

**Comment by ProgVal** [comment]
Nevermind, it's explained in the doc

**Comment by ProgVal** [comment]
Thanks for your help!
