### ISSUE TITLE
borg mount wrong uid

### ISSUE THREAD

**Issue by datafux** [borgbackup/borg#1017]
when i borg mount an archive, the owner of the mounted archive has the same uid as the owner who created the archive. usually this is not a problem. but when i borg mount it on a machine where my user has a different uid i cannot access files and directories with permission flags 0700.
not sure if this is a borg or a FUSE issue.
I'm on osx 10.11.4 with borg 1.0.2 and osxfuse 3.2.0

**Comment by ThomasWaldmann** [comment]
```
borg mount -o MOUNTOPTIONS ...
```
maybe check the fuse mount options (see fuse docs) whether they are helpful in your case.

**Comment by datafux** [comment]
Thanks for the hint. "borg mount -o defer_permissions ..." did the job

**Comment by Timmmm** [comment]
Did you mean `-o default_permissions`? That doesn't work for me, and anyway the docs say

> for security reasons the "default_permissions" mount option is internally enforced by borg. "ignore_permissions" can be given to not enforce "default_permissions".

Yet I still get:

```
me@sw01:~/backup_mount/main-2020-04-09_1416/Users/me$ ls -ld *
drwxr-xr-x 1 me me    0 Apr  9 15:34 bin
drwx--x--x 1  501 dialout 0 Apr  9 10:04 workspace
```

These were the permissions of the original directories (on a Mac):

```
$ ls -ld bin workspace
drwx------ - me  9 Apr 10:07 bin
drwx--x--x - me  9 Apr 10:04 workspace
```

What's going on here? I'm using `borg` 1.1.11 on a Mac, backing up to a Linux machine.

**Comment by Timmmm** [comment]
If I try to access it using root I can't even get into the mount directory. `ls` gives this insanity:

```
d????????? ? ?    ?           ?            ? backup_mount
```

**Comment by Timmmm** [comment]
Btw this used to work with Borg 1.0.11.

**Comment by ThomasWaldmann** [comment]
Please do not add to stone-age closed tickets, but rather open a new one and give all the details.

And first please read the fuse docs (`man fuse` etc.) because fuse does some stuff in a rather unusual way.

**Comment by Timmmm** [comment]
In fact, I just tried mounting a backup that was created with Borg 1.1.11, using Borg 1.0.11. This time I get:

```
$ ls -ld *
drwxr-xr-x 1 me me    0 Apr  9 17:58 bin
drwx--x--x 1  501 dialout 0 Apr  9 10:04 workspace
```

Which is clearly still wrong. The even weird thing though is that if I `cd workspace` and then `ls`, it works! With Borg 1.1.11 I get a permission denied error.

Anyway this is clearly a bug; I will open a new issue.
