### ISSUE TITLE
improve automating backups example

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1020]
http://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups

should be:
```
export BORG_REPO=...
export BORG_PASSPHRASE=...   (as we now default to encryption enabled)
```

People tend to forget the "export" and then wonder why it does not work.

**Comment by pepa65** [comment]
That is right. It is very unintuitive for a (ba)sh scripter to export variables that are needed for commands that are used in the script. Is that because /usr/bin/borg isn't in an executable format but a shell script that specifies an interpreter (python)?

**Comment by ThomasWaldmann** [comment]
"export" means that the variable is put into the environment. Without that, you can only use it in the script, but a process won't see it as env var.
