### ISSUE TITLE
chunker performance

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1021]
the chunker seems to perform at 400-500MB/s on a in-memory file (BytesIO or on ramdisk), including reading, chunk buffer management and the chunking itself.
 
just reading (fd.read()) the file performs at ~6000MB/s.

can we make the chunker significantly faster without making the code more complex?

**Comment by enkore** [comment]
Force-inlining buzhash and buzhash_update seemed to make a difference when I tried it. If you have a good, deterministic benchmark it's worth a shot.

**Comment by ThomasWaldmann** [comment]
Hmm, i changed `static` to `static inline` for buzhash/buzhash_update, but did not see a difference in speed.

**Comment by enkore** [comment]
iirc `__attribute__((always_inline))`

**Comment by ThomasWaldmann** [comment]
gcc does inline small functions with -O2 (as it is run by default by cythonize call).

**Comment by ThomasWaldmann** [comment]
note: replacing .read() by .readinto() (and thus avoiding the memcpy) in the python-file part of the chunker doesn't give a noticeable speedup.

**Comment by ThomasWaldmann** [comment]
btw, i had a look into the assembler code and gcc -O2 seems clever enough to translate that "BARREL_SHIFT" code into a single "rol" x86 instruction. \o/

**Comment by rakajack** [comment]
Replacing lenmod in a buzhash_update with a constant (because window is always 4095) gives 30 mb/s increase in chunker speed.

**Comment by ThomasWaldmann** [comment]
@ah, good find! it could be also computed outside the loop and passed in instead the length.

**Comment by rakajack** [comment]
A chunk have a minimum size (min_size). Are we skipping (min_size - window_size) bytes after finding a boundary?

**Comment by ThomasWaldmann** [comment]
No. Also, we are not yet skipping files that are too small.

**Comment by ThomasWaldmann** [comment]
See PR #1077.

**Comment by ThomasWaldmann** [comment]
new chunker
-----------------
```
    length   count      dt throughput chunks_count
1000000000       1   2.271 440.392    120
 100000000      10   2.310 432.956     12
  10000000     100   2.200 454.530      2
   1000000    1000   1.100 908.739      1
    100000   10000   0.104 9609.142     1
     10000  100000   0.225 4434.996     1
      1000 1000000   1.750 571.296      1
       100 1000000   1.732 57.728       1
        10 1000000   1.719 5.816        1
         1 1000000   1.821 0.549        1
```

master chunker
--------------------
```
coming...
```

**Comment by ThomasWaldmann** [comment]
did one more test: created files with random content of different sizes, checked if old and new chunker code produces the same chunks. yes, it does!

[donot.txt](https://github.com/borgbackup/borg/files/276379/donot.txt)
[master.txt](https://github.com/borgbackup/borg/files/276378/master.txt)
[chunker_identical.py.txt](https://github.com/borgbackup/borg/files/276380/chunker_identical.py.txt)
