### ISSUE TITLE
check vs extract --dry-run

### ISSUE THREAD

**Issue by edgewood** [borgbackup/borg#1022]
Does extract --dry-run test an archive any more than check does?  The drive that my repositories are on is reporting unreadable sectors, so I'm replacing it under warranty.  I'm waiting for the replacement drive, and I'd like to verify the repositories both before and after I transfer them to the new drive.

I already run check over each of the repositories at the end of every set of backups (ie, I create A archives spread among R repositories every night, then run borg check for each R).

I know that there used to be a borg verify command, now replaced with extract --dry-run.  Does running that on each archive give me any extra assurance of uncorrupted data over just running check?  Should I run check on each archive instead, or additionally?

I looked at the doc for the commands, and the FAQ.  I think the doc for check says that I don't need to run check on each archive, that a repo level check will do that if I don't use --repository-only.  Beyond that I'm not sure.

**Comment by ThomasWaldmann** [comment]
`borg extract --dry-run repo::arch` will extract all items (verify, decrypt, decompress) like it does without `--dry-run`, it will just not write the resulting data to disk files.

`borg check` does not (yet) extract all data chunks, but there is ongoing work to add that.

**Comment by edgewood** [comment]
So extract --dry-run will do some validation that is not currently done by check?

**Comment by ThomasWaldmann** [comment]
Yes, it will check the (hmac-)sha256 of the file data chunks and it will actually decrypt / decompress them.
