### ISSUE TITLE
typo in kernel version?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1024]
_chunker.c refers to "Linux kernels prior to 4.7 ...".

considering that the latest current kernel is 4.6rc6, this seems wrong.

**Comment by enkore** [comment]
From #914, pinging @verygreen

**Comment by ThomasWaldmann** [comment]
@enkore Ah, thought it was from you and didn't use git blame. ;)

**Comment by verygreen** [comment]
Well, current is 4.6 - that means 4.6 is affected. I was hoping the fix might get accepted into 4.7, but even that seems to be unlikely now as I did not get any comments on it. probably time to try and resend it.

**Comment by ThomasWaldmann** [comment]
OK, so in case it doesn't get in, maybe we could just say "all kernel versions" until we know definitively.

**Comment by verygreen** [comment]
Possible too, I guess.

**Comment by enkore** [comment]
Seems to be in linux 4.7-rc7

**Comment by ThomasWaldmann** [comment]
I just confirmed that the fix is in kernel 4.7 release.
