### ISSUE TITLE
prune: does not accept format tags (like "create")

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1027]
Works:
```
borg create repo::{hostname}-{now}
```

Does not:
```
borg prune repo --prefix {hostname}- ...
```

**Comment by ThomasWaldmann** [comment]
note: could be used in the quickstart example script.

**Comment by ThomasWaldmann** [comment]
When doing this, it must be made sure that P of `--prefix P` does not get empty - see how the current tags formatting code deals with exceptions.

**Comment by pepa65** [comment]
This works: `borg prune -P prefix ...`
(with BORG_REPO set)
But your "does not" example should work according to the documentation, right?

**Comment by ThomasWaldmann** [comment]
What I meant is that with `borg prune --prefix {something}` the string that expands from `{something}` never ever gets empty because every archive name in the repo has the empty string as a prefix and thus prune would operate like without the `--prefix` option and would remove archives that the user likely did not want to remove.
