### ISSUE TITLE
Open file/dirs once and use fildes-based APIs instead of path-based APIs

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1038]
In line with #906, #908 and related issues we should try to use file descriptor / handle based operations in favour of path-based operations to avoid various race conditions and inconsistencies when files are replaced during a backup run.

These changes should go into master.

Windows can then use the _get_osfhandle API to retrieve the object backing a file descriptor of the CRTs POSIX-like API (open etc). And that can be used with the usual object-oriented Windows functions (e.g. GetUserObjectSecurity instead of GetFileSecurity).

**Comment by ThomasWaldmann** [comment]
note: we use `os.scandir(path)` and it requires python >= 3.7 to support giving a directory FD instead of a path on UNIX.

see also: https://github.com/benhoyt/scandir/issues/108

**Comment by ThomasWaldmann** [comment]
fixed by #4043.
