### ISSUE TITLE
AES Counter/IV handling on rollbacks

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1039]
Suppose the following series of events:

1. IV starts at *x0*
2. Some data blocks *n-1* are written
3. Manifest is written
4. IV of manifest is now x0+n = x1
5. Repository.commit; attacker raises false abort/exception
6. Attacker still has the blocks encrypted with IVs x0 ... x0+n
7. Another session, unclean commit state is detected, rollback is made (as usual)
8. The old manifest is in place with IV x0
9. This is not detected since the commit aborted before the cache was comitted
10. Some data is encrypted, with _reused_ IVs x0 and following

In the case of AES_CTR_HMAC_SHA256 reusing IVs can "just" leak plaintext, but for AES_GCM this is way more devastating, because authenticity can be forged. Now, luckily, we have the chunk ID HMAC in place as well, which prevents forgery of data chunks, but not the manifest.

**Comment by ThomasWaldmann** [comment]
Yes, looks like a problem.

It always happens on a rollback, right (no matter at what specific step it was interrupted)?

**Comment by enkore** [comment]
Yes, I think this is a problem for any kind of rollback.

**Comment by enkore** [comment]
(No haste though, I don't think this is too critical)

**Comment by enkore** [comment]
Duplicate of #22
