### ISSUE TITLE
Supporting subdirectories inside Borg repository to organize users while maintaining de-dupe?

### ISSUE THREAD

**Issue by sb56637** [borgbackup/borg#104]
Hi everyone,

Would it be possible to create backups in subdirectories of a Borg repository? I'm not sure if these would technically be sub-repos or just simply subdirectories in the same repo. But the point is that it would be useful to have the option of organizing backups according to arbitrary criterion, such as usernames or maybe different company department names, while at the same time retaining a common de-duplication index.

I know that it wouldn't be possible for more than 1 to access the repo at any given moment, but that could be scheduled and worked around.

Thanks a lot for creating Borg!

**Comment by level323** [comment]
If I understand you correctly, something along the lines of what you wish to achieve via subdirs can be achieved already by structuring the name you give to an archive. 

I have followed this approach and it works reasonably well. e.g. an archive name of `Usammy--Fdaily--Suserdata--D20150719` is the name of an archive of `/home/sammy` of user `sammy` taken `daily` on `2015-07-19`.

That said, I think some kind of organisation system for archives would be useful. Tags might even be preferable to subdirs.

**Comment by sb56637** [comment]
What gave me this idea is Obnam, which has a username folder inside the defined repository directory. This is nice to keep different users separated while still maintaining de-dupe between them all.

**Comment by oderwat** [comment]
The problem with @level323 approach (which I kinda use too) is that access rights are not defined. It would indeed be cool to have a "global" repository space for multiple users which then get their own sub-repository. This would enable a whole range of new usecases for borg.

**Comment by ThomasWaldmann** [comment]
how are "access rights" managed with the directory approach? i can see you could limit access to different archives to different parties somehow, but if the chunks shall be shared, this is no real protection as all parties could access all chunks directly somehow - so this is an unsolvable problem.

**Comment by oderwat** [comment]
One could suid root borg I guess? Of course if the chunks are available to everyone this will be a potential problem. I did not dig into borg. But if the metadata is missing the chunks are probably not that easy to make sense of and with user elevation one could also have a key which is not available to the normal users.

**Comment by ThomasWaldmann** [comment]
Well, yes and no. Short files will end up being represented as 1 chunk (and short might well mean 64kiB or 1MiB). So it's getting a bit into the "security by obscurity" department here.

**Comment by sb56637** [comment]
I'm not terribly concerned with the security aspect, because in most cases there is a level of trust between the different users that would be sharing the repository. Or in a corporate or hosted setting, if the administrator wanted to he could probably just write some kind of a wrapper that authenticates users and then acts as an intermediary between the user and Borg.

**Comment by oderwat** [comment]
Yeah, thats not acceptable for security in a real multi user environment. Still it would allow multi-user separation while having a shared repository. Something like a first step.

**Comment by sb56637** [comment]
@oderwat Our comments crossed paths by a few seconds. :) But yes, I agree that it would be a good first step. I don't think that Borg should be responsible for security, which is probably best left to the another 3rd party layer. Just organizational features would be greatly appreciated.

**Comment by oderwat** [comment]
Well I think that creating security should be part of borg in that respect. While user separation could already be implemented with some shell scripts. You can prune on a "-p PREFIX" and use the users as prefix of the backup name easily. So if there is no user elevation in borg one could more or less made a simple wrapper in an extra script (or as a minor feature in borg) and setup the repository itself with group access. I think that deduplictation will still work if the users and paths aka metadata of the files are different.

**Comment by ThomasWaldmann** [comment]
I am closing this as "nothing to do".

There are 2 cases:

1. either all repo users trust each other ultimately - then you can just coordinate to use different archive names (including hostname, username, etc.), give the same symmetric crypto key to each of them, etc. - this is already possible.

2. not all repo users trust each other ultimately - then you must not share the data chunks nor the crypto key (i.o.w.: must not share access to the same repository). borg does not make any difference between file content chunks, directory chunks, archive chunks, repository manifest. it's all just a big pile of chunks and you can request any of them if you have access to the repo.
