### ISSUE TITLE
Passphrase unicode normalization?

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1048]
Borg gets the passphrase as text and encodes it in UTF-8 for further handling.

I'm not sure, so this has to be checked, but I think ".encode('utf-8')" doesn't do normalization itself, so depending on how exactly the string was constructed it may not be normalized. -> `unicodedata.normalize('NFC', str)` should eliminate possible problems here.

**Comment by ThomasWaldmann** [comment]
Could this explain that a passphrase created on OS X does later not work on Linux?

**Comment by ThomasWaldmann** [comment]
Hmm, do I see it right that if we change that, some existing passphrases/repos would stop working?

**Comment by RonnyPfannschmidt** [comment]
this should be a new repo format, and a format upgrade would normalize the passphrase

**Comment by ThomasWaldmann** [comment]
rather "key format".

**Comment by edgewood** [comment]
Yes.

You could implement the code such that newly created and changed passphrases are always normalized.  Then when a passphrase is submitted for use, you'd try using the normalized string first, but if that failed try the raw string.  If the raw string works where the normalized didn't, either invoke the change-passphrase code to change to the normalized string, or emit a warning suggesting that the user do so.

**Comment by ThomasWaldmann** [comment]
some experiments regarding this could be done to see whether / when normalization gives different output.

Requirements:
- basic python3 skills
- can enter non-ascii stuff on keyboard (e.g. russian, maybe other non-english langs)
- need to run (native, not in VM) OS X
- need to run (native, not in VM) Linux

**Comment by enkore** [comment]
Hmm. There are multiple kinds of normalization and the possibility of un-normalized strings. If this:

> Could this explain that a non-ascii passphrase created on OS X does later not work on Linux?

has indeed this root cause, then what Borg should do is

- Try to unlock with standard normalization (i.e. what we decided on)
- Try to unlock with `.encode(utf-8)`
- Try to unlock with *any* normalization applied <-- which may or may not catch things like "init on OSX, access on IRIX/Windows/vxWorks". _Testing needed!_
- When successful with non-standard normalization, normalize with standard normalization and re-encrypt the key file with that

**Comment by ThomasWaldmann** [comment]
Code to try this (try to find different byte sequences for same input when using Mac OS X, Linux, Cygwin):
```
$ python3
>>> input("Type strange chars here: ").encode('utf-8')
Type strange chars here: äöü
b'\xc3\xa4\xc3\xb6\xc3\xbc'
```
Not sure if it happens with german umlauts, maybe rather âàá?

**Comment by ThomasWaldmann** [comment]
Yesterday, i compared the utf-8 byte sequences (see previous post for the code) on Mac OS X and Linux.

I tried: german umlauts, french accented chars, russian/cyrillic chars.  I didn't find differences in the resulting byte sequences.

**Comment by ThomasWaldmann** [comment]
Help wanted: we can only fix this, if we can reproduce the (potential) problem.

That is: create different utf-8 bytes from same passphrase entered on different systems / in different ways.

If somebody can show this and we can reproduce, we can fix it.

**Comment by enkore** [comment]
Linux and OS X seem to be ruled out so far.

Can someone test this on Windows? There are a few different shells around, maybe that can make a difference, too, there.

**Comment by ThomasWaldmann** [comment]
I'll try it with cygwin on win10.

**Comment by ThomasWaldmann** [comment]
Close?

**Comment by ThomasWaldmann** [comment]
Closing this as not a problem / not reproducible.
