### ISSUE TITLE
cjk screen output formatting trouble

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1051]
chinese, japanese, korean "monospace" terminal fonts use 2 cells per glyph, so using len(text) gives an incorrect value if text has cjk unicode code points.

this leads to wrong output in the `--progress` "single line output" - the amount of spaces to "fill" the line and erase previous output is computed wrongly.

there is https://pypi.python.org/pypi/wcwidth to compute the correct width.

3 ideas:
- just require it via setup.py
- bundle it in borg.support
- use a try / except ImportError and use a len(text) dummy if it can't be imported.

Screenshot: ![borg_jap](https://cloud.githubusercontent.com/assets/356103/15339816/7b97a3dc-1c86-11e6-8be9-a31e366b7370.png)

**Comment by enkore** [comment]
- pull the wcwidth(3) of the libc via ctypes/cython?

**Comment by ThomasWaldmann** [comment]
urwid also seems to have cjk support.
