### ISSUE TITLE
crash related to (non-borg) binary files in keys directory

### ISSUE THREAD

**Issue by christian-comsolit** [borgbackup/borg#1056]
If i try to list/mount a remote repository i get this error:

`Local Exception.`
`Traceback (most recent call last):`
`  File "borg/archiver.py", line 1498, in main`
`  File "borg/archiver.py", line 1452, in run`
`  File "borg/archiver.py", line 74, in wrapper`
`  File "borg/helpers.py", line 95, in load`
`  File "borg/key.py", line 53, in key_factory`
`  File "borg/key.py", line 289, in detect`
`  File "borg/key.py", line 402, in find_key`
`  File "/home/vagrant/.pyenv/versions/3.5.1/lib/python3.5/codecs.py", line 321, in decode`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 12: invalid start byte`

`Platform: Linux xxx 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 `
`Linux: debian 8.4 `
`Borg: 1.0.2  Python: CPython 3.5.1`

I'm using the standalone binary version 1.0.2 on debian 8.4.0 (server and client) with locales configured as en_US.UTF-8.
The generated key file seems to be correctly encoded:
`file -i` outputs "us-ascii" which according to http://stackoverflow.com/a/11303410 is correct.

Has anybody a clue what could be the issue here?

**Comment by enkore** [comment]
In a Python 3 shell...

```
>>> open("/path/to/your/keyfile").read()
```

Does that fail as well?

**Comment by ThomasWaldmann** [comment]
is there some file in the keys directory that does not belong there?

the directory is usually ~/.config/borg/keys

**Comment by ThomasWaldmann** [comment]
Note: we should open the file in binary mode first and do the magic check before trying to decode it.

**Comment by christian-comsolit** [comment]
Yes i had a zip-file lying arround there...  if that's deleted it works.
Thank you so much!

**Comment by enkore** [comment]
Fix in #1058

**Comment by ThomasWaldmann** [comment]
Sounds like you backuped your keys, which is good. :)

**Comment by enkore** [comment]
Fixed by #1058
