### ISSUE TITLE
SIGTERM handler

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1059]
In the sigterm handler, we should reset the sigterm handler to the standard handler.

So just in case the exception raising does not terminate the process, a second term signal "gets through".

**Comment by enkore** [comment]
I don't think this is necessary. I see two reasons how the exception can fail: it gets stuck outside the VM, or someone in the VM is catching BaseException silently. In the first case Python's signal handler doesn't help, in the second case it's a serious bug. Getting stuck outside the VM is a serious bug as well. In those cases SIGKILL can / should be used and would be used automatically by a service manager.
