### ISSUE TITLE
Use atomic file writing and updating for configuration and key files

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1060]
Proposed sequence

- write to temporary
- fsync(temp)
- rename(temp, real)
- fsync(containing_dir) <-- important for the repository config when we implement DEKs

***

:moneybag: [there is a bounty for this](https://github.com/borgbackup/borg/issues/1060)

**Comment by ThomasWaldmann** [comment]
Note: the temporary file needs to be in same directory as the target file (just maybe some prefix/postfix, like ~*.tmp).

**Comment by ThomasWaldmann** [comment]
Note: I've put a bounty on this and have unassigned @enkore (who was assigned on this for rather long).

Anybody (including @enkore) feel free to work on this, please tell on bountysource when you start.

**Comment by enkore** [comment]
Had forgot about it, but here's a draft I had laying around from a month ago or so. Feel free to recycle :)

```py
class SaveFile:
    """
    Update file contents atomically.

    Must be used as a context manager.

    On a journaling file system the file contents are always updated
    atomically and won't become corrupted, even on pure failures or
    crashes (for caveats see SyncFile).
    """

    SUFFIX = '.tmp'

    def __init__(self, path):
        self.path = path
        self.tmppath = os.path.join(self.path, self.SUFFIX)

    def __enter__(self):
        # XXX use platform-specific SyncFile
        self.fd = open(self.tmppath, 'xb')
        return self.fd

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.fd.close()
        if exc_type is not None:
            os.unlink(self.tmppath)
            return
        os.rename(self.tmppath, self.path)
        # XXX use platform-specific sync_dir
        sync_dir(os.path.dirname(self.path))

    def write(self, data):
        self.fd.write(data)
```

**Comment by PlasmaPower** [comment]
> fsync(containing_dir)

`fsync` for python at least only applies to specific file descriptors. Any ideas on how to do this? I think on *nix you might be able to open a file descriptor for a directory, but I think that's not true for Windows.

**Comment by enkore** [comment]
Got an abstraction for that

```
        # XXX use platform-specific sync_dir
        sync_dir(os.path.dirname(self.path))
```

It's possible on Windows but that stuff needs more investigating how one can reliably cause a transaction flush there.

**Comment by enkore** [comment]
While doing "corruption testing" with various file systems (NTFS-3g, ext4, XFS) [2] I noticed that given just the right sequence of operations [1] one can manage to put some data in a freshly created repository on XFS and then lose the repo config rendering the repo unusable until an advanced power-user re-creates the config file.

I don't think this is a critical/big problem in normal usage patterns since the first create after an init will almost certainly take longer than the dirty-writeout timeout (a couple minutes).

[1] borg init, borg create small archive (<1 MB in my case), borg create big archive, pull drive during create.
[2] First tests made for #1211, with rather ugly results:

> Rather curious: ntfs-3g journaling doesn't seem to be very reliable. After a few pulls with no repository corruption I get an EIO on open(2) on a data file and a rather ugly ntfs-3g message:
>
>>    Jun 27 20:59:35 tiger ntfs-3g[27314]: Trying to read non-allocated mft records (83 > 82): Nicht erlaubter Seek (seek not permissible)
>>    Jun 27 20:59:35 tiger ntfs-3g[27314]: Trying to read non-allocated mft records (83 > 82): Nicht erlaubter Seek
>
> Even root can't touch that inode anymore, not even rm the dirent. I'll see whether Windows chkdsk can fix that, or whether I have to reformat my thumb drive?!

**Comment by enkore** [comment]
Stapling https://github.com/jborg/attic/issues/177

> safe to say it's an "issue" outside attic. i.e. crash before the file was committed to disk and stuff like that. #1060 goes in the direction.

**Comment by PlasmaPower** [comment]
> ntfs-3g isn't reliable at all on this system

Could you test this on a loop device? I'm not experiencing any corruption issues there:

```sh
truncate -s 1G part.raw
mkfs.ntfs -F part.raw
mkdir /mnt/loop
ntfs-3g part.raw /mnt/loop
```

**Comment by enkore** [comment]
How can I remove a loop device in a similarly unexpected fashion as physically pulling a hot drive?

**Comment by PlasmaPower** [comment]
@enkore Good question, I think `pkill -9 ntfs-3g` will do that.

**Comment by enkore** [comment]
No, doesn't seem to cause the same issue (it would surprise me if they didn't test NTFS-3G to that standard). It smells like a hardware problem e.g. someone in the USB may be reordering writes or dropping sync-like commands.

**Comment by PlasmaPower** [comment]
Do you think it might be a race condition visible with the increased latency? I don't know of a good way to simulate increased latency on a disk, maybe sshfs with `tc qdisc netem`?

**Comment by enkore** [comment]
I really don't know. That live? metadata refers to non-existing MFT entries suggests (in my mind) that some basic precondition of the journaling must've been broken. I ATM don't have any real drives I'd be willing to use for testing this, but when I get some I'll test more hardware wrt. this bug.

**Comment by ThomasWaldmann** [comment]
@enkore claim the bounty ;)
