### ISSUE TITLE
freebsd llfuse troubles

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1068]
llfuse does not build on freebsd for releases > 0.41.1 and <= 1.0.0:

https://bitbucket.org/nikratio/python-llfuse/issues/87/type-mismatch-causes-build-failure-on
https://bitbucket.org/nikratio/python-llfuse/issues/91/freebsd-src-llfusec-error-implicit

As the issues were closed, we can hope for a fixed > 1.0.0 release.

After that release, our setup.py needs the freebsd special casing to get removed (where it requires ==0.41.1).

**Comment by jungle-boogie** [comment]
I downloaded and installed llfuse1.1 from:
https://bitbucket.org/nikratio/python-llfuse/downloads

Then checked to see if this was in my python3 path:

```
>>> import sys
>>> print(sys.path)
 '/usr/local/lib/python3.4/site-packages/llfuse-1.1-py3.4-freebsd-10.3-RELEASE-p3-amd64.egg'
```

and also:

```
>>> import llfuse
>>> llfuse.__file__
'/home/sean/.python-eggs/llfuse-1.1-py3.4-freebsd-10.3-RELEASE-p3-amd64.egg-tmp/llfuse.so'
```

I then proceeded to attempt mount a borg backup:
`% sudo borg mount droplet drive`

No error and it mounts:
drwxr-xr-x  1 root  wheel  0 May 24 16:22 2015-11-30-20:16


All performed with:
`borg 1.0.3`
`Python 3.4.4`

**Comment by lfam** [comment]
It works for me on with borg 1.0.3 on Linux 4.4.11 and Python 3.4.3. Also tested with FUSE 2.9.6, which is the latest version.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/1131 fixes this.
