### ISSUE TITLE
fix capabilities extraction on linux

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1069]
when extracting files that have "capabilities" in the extended attributes (xattrs), the xattrs were extracted first and then a chown call was used to set the owner.

chown has the side effects of killing the capabilities again, so the result was not as expected.

changing the order to first do chown and then set xattrs fixes this.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/39a40cd7b7bfe55b45b176c129c22ca62ba50ebe fixes this.

**Comment by enkore** [comment]
(also see #921 for detailed reproduction of the bug)
