### ISSUE TITLE
temp file size poorly documented

### ISSUE THREAD

**Issue by rsplaul** [borgbackup/borg#108]
When playing around with borg and a several hundred of GB of data, I noticed that borg requires a fair amount of capacity for temporary files. Since this came as a little surprise to me I would appreciate a section in the documentation explaining how the amount of data being backed up and the expectable temp file usage correlate.

**Comment by ThomasWaldmann** [comment]
this might be related to:
https://github.com/borgbackup/borg/commit/bd354d7bb43fe07c650064f070d18ae3064eefc8

so, for now, I'ld suggest we advise in the docs about using export TEMP=/somewhere/withlotsofspace.
similar thing is true for the .cache/borg/ directory, it also can get rather big.

**Comment by rsplaul** [comment]
Actually `~/.cache/borg/`is the main problem. If you do a backup as root, this happens to reside in `/root`. On most systems (with multiple partitions) I've seen or installed so far, `/root` would end up on a rather small root partition with only a few GB of free space.

**Comment by PerfMonk** [comment]
(Nice to have ???)
Wouldn't it be usefull if the .cache/borg would be moved in a database (mariadb, postgreSql, ...) so that it would be simpler to manage if you want to backup from more than one machine or move it to some "very big empty space" you have on some other device ??? Possibility to use temporary space on the database would be simpler either.

**Comment by ThomasWaldmann** [comment]
the cache/index files in .cache/borg are hash tables that are loaded into RAM (more or less "as is") and the real usage of them happens in RAM (and after that, they are written back to disk).

using something directly on disk or even via the network is likely much slower.

**Comment by PerfMonk** [comment]
I agree it would be slower on disk.  But if you have a really big repository and that you want to take backups from more than one computer you will have to wait until borg have recreated all those zillions of hashes.  Is there a way to avoid this ?  

If I understand well, it's the location where the cache/index is saved that cause problems (fill the root or your home and recalculation delay when accessed from another computer where the cache/index  is not there.  Couldn't the index/cache be saved with the backup at the end and restored from the archive when we need to access the archive ?  It must be loaded from the ~/.cache/borg directory anyway.

**Comment by ThomasWaldmann** [comment]
@PerfMonk about "creating a zillion of hashes": they are at the very core of what borg does, the whole working (deduplication) principle is based on the chunk's content-hash, so they get computed anyway.

The question about location (and mechanism / algorithm) more or less boils down to (connection) latency and speed. These indexes (hash tables) are used a lot, so this needs to be low-latency and fast. Attic used to have mmapped index files and there were performance issues with that and this is why jonas changed it to be "read from disk, do lots of operations in memory, write back to disk".

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/1e097bfd6b9904954be2f739cbb67ac478df4ce5 fixed the docs

**Comment by PerfMonk** [comment]
Thanks for the docs!
