### ISSUE TITLE
Using record size to determine optimal chunker parameters

### ISSUE THREAD

**Issue by storcium** [borgbackup/borg#1085]
Hello, I am working with backup files that have a fixed (but configurable) record size.  Using default or even a "fine granularity" chunker parameters yields almost no deduplication at all, but working lower start producting results.  Examples below.  With a record size of 32K the chunker params of 8,16,10,4095 yield a good result at expense of time and RAM.  So is the goal to put the record size in the middle as the most likely chunk size?

Alternatively, is there a possibility of a tool that would determine optimal chunker parameters by analyzing two files, e.g. yesterday's and today's backup?

Here are my three stats with different chunker settings:

```
iss@issapl2:~$ /usr/local/bin/borg create -v --stats --progress /vault/repo1::cgm1 /data/volume1/cgm-backupfile-1    ------------------------------------------------------------------------------
Archive name: cgm1
Archive fingerprint: f91d586b3a97c8a06c422fe05aa565101e6f42b5392de6334fb47ad4c495ef78
Time (start): Sun, 2016-05-22 16:21:40
Time (end):   Sun, 2016-05-22 16:44:07
Duration: 22 minutes 27.51 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              124.41 GB            124.41 GB            123.96 GB
All archives:              124.41 GB            124.41 GB            123.96 GB

                       Unique chunks         Total chunks
Chunk index:                   46836                46943
------------------------------------------------------------------------------
iss@issapl2:~$ /usr/local/bin/borg create -v --stats --progress /vault/repo1::cgm2 /data/volume1/cgm-backupfile-2
------------------------------------------------------------------------------
Archive name: cgm2
Archive fingerprint: be1fded145da8216c95a0eeb8586de86357f1f17710db92a2cf136a1a3ccb029
Time (start): Sun, 2016-05-22 16:51:23
Time (end):   Sun, 2016-05-22 17:13:59
Duration: 22 minutes 36.08 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              124.42 GB            124.42 GB            123.97 GB
All archives:              248.83 GB            248.83 GB            247.93 GB

                       Unique chunks         Total chunks
Chunk index:                   93738                93951
------------------------------------------------------------------------------
```

```
iss@issapl2:~$ /usr/local/bin/borg create -v --stats --progress --chunker-params "9,16,12,4095" /vault/repo1::cgm1 /data/volume1/cgm-backupfile-1
------------------------------------------------------------------------------
Archive name: cgm1
Archive fingerprint: 2cd1b48f0eb5635fa57eb4033a1ac0cab0025d71edcb30b4512c32a2ebd5cd8c
Time (start): Sun, 2016-05-22 20:00:07
Time (end):   Sun, 2016-05-22 20:42:01
Duration: 41 minutes 54.59 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              125.50 GB            125.58 GB            124.55 GB
All archives:              125.50 GB            125.58 GB            124.55 GB

                       Unique chunks         Total chunks
Chunk index:                25768665             25941248
------------------------------------------------------------------------------
iss@issapl2:~$ /usr/local/bin/borg create -v --stats --progress --chunker-params "9,16,12,4095" /vault/repo1::cgm2 /data/volume1/cgm-backupfile-2
------------------------------------------------------------------------------
Archive name: cgm2
Archive fingerprint: 860fe0ce4cd435597b14894513215da8d9d4ab371856ae7e2e60368099e3f8ce
Time (start): Sun, 2016-05-22 21:32:24
Time (end):   Sun, 2016-05-22 22:03:38
Duration: 31 minutes 13.73 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              125.50 GB            125.58 GB             50.57 GB
All archives:              251.00 GB            251.16 GB            175.12 GB

                       Unique chunks         Total chunks
Chunk index:                32917211             51879777
------------------------------------------------------------------------------
```

```
iss@issapl2:~$ /usr/local/bin/borg create -v --stats --progress --chunker-params "8,16,10,4095" /vault/repo1::cgm1 /data/volume1/cgm-backupfile-1
------------------------------------------------------------------------------
Archive name: cgm1
Archive fingerprint: 0d0c5767c7b52f4b01c1079a74cb77e63cb281335fbc9f6f8deb065fd71bb283
Time (start): Sun, 2016-05-22 22:26:28
Time (end):   Mon, 2016-05-23 02:37:28
Duration: 4 hours 11 minutes 0.12 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              128.35 GB            128.63 GB            127.42 GB
All archives:              128.35 GB            128.63 GB            127.42 GB

                       Unique chunks         Total chunks
Chunk index:                92939143             93784123
------------------------------------------------------------------------------
iss@issapl2:~$ /usr/local/bin/borg create -v --stats --progress --chunker-params "8,16,10,4095" /vault/repo1::cgm2 /data/volume1/cgm-backupfile-2
------------------------------------------------------------------------------
Archive name: cgm2
Archive fingerprint: 8e9faf2b57459e5470faba74222b3c1a1c6fe2f700b1934cdcd2c31af46921bc
Time (start): Mon, 2016-05-23 03:20:44
Time (end):   Mon, 2016-05-23 06:00:24
Duration: 2 hours 39 minutes 39.75 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              128.35 GB            128.63 GB             29.60 GB
All archives:              256.70 GB            257.26 GB            157.02 GB

                       Unique chunks         Total chunks
Chunk index:               108944974            187564821
------------------------------------------------------------------------------
```

**Comment by ThomasWaldmann** [comment]
I am not sure I fully understand your post, so some questions (please edit first post to clarify).

> "... that have a custom record size."

Does that mean some specific, fixed record size? or is each record of a different size?

> Using default or even a "fine granularity" chunker parameters yields almost no deduplication at all,

The default chunker is configured to produce rather big chunks to avoid resource usage problems.
If the changes in your input files happen in a way so that there are no stable big chunks, it won't result in deduplicatable chunks.

> but working lower start producting results. Examples below. With a record size of 32K the chunker params of 8,16,10,4095 yield a good result at expense of time and RAM.

That means that statistically it will result in 2^10 == 1024 byte chunks (but never below 2^8 and never above 2^16). Where it cuts depends on the hash of the rolling window content, so it could result in sizes 604, 990, 1540, 1111, ...

Btw, with such small target chunk size, using a smaller window size seems required, so try something else as the last value 4095 -> 255 or 31 (I never experimented with modifying window size, so be careful. IIRC it must not be an even value.).

> So is the goal to put the record size in the middle as the most likely chunk size?

The chunker is not really made to deal with fixed size records. But yes, it'll work better if the typical chunk size is not far above your record size, but close or below.

> Alternatively, is there a possibility of a tool that would determine optimal chunker parameters by analyzing two files, e.g. yesterday's and today's backup?

No, there is no such tool yet.

**Comment by ThomasWaldmann** [comment]
BTW, for a fixed-record layout (like records sized X and optional header fixed size Y) we could have a chunker that cuts that into (single or multiple) records on record boundaries:

```
R0 X bytes | R1 X bytes | ...
```
or
```
Header Y bytes | R0 X bytes | R1 X bytes | ...
```

**Comment by storcium** [comment]
Thomas, Thank you for the fast answer.

Updated with the specifics of a record size.  Tar archives, database backups and such would often allow or require the setting of block size for the backup, so this should re fairly common?  The fixed record chunker would be a great option.

This answers my question - I will work with smaller chunks and window and post the results.

**Comment by ThomasWaldmann** [comment]
Fixed record size chunker topic -> #1086.

**Comment by storcium** [comment]
Would it ever make sense to have the median record equal to MIN or MAX?  For example, the records are 8K, patterns may be up to 32K, but most likely at 8K, so chunker parameters = 13,15,13,4095

**Comment by storcium** [comment]
And...chasing down this thought, is there a way to get a distribution of dedup chunks after the fact, i.e. how many 8K chunks, how many 32K chunks etc.?  So we can learn more about the deduplication structure of data and adjust/narrow chunker parameters to be more precise (i.e. not waste CPU looking for chunk sizes that we already know do not repeat much)?

**Comment by enkore** [comment]
Something like c89c9fe ?

**Comment by storcium** [comment]
oh perfect!  a histogram of chunk frequency based on a wider chunker selection, then narrow it down to the most used sizes.

**Comment by verygreen** [comment]
for my testing I found that you just follow the developer guide with tox and stuff, then that produces a working borg "binary" in .tox somewhere (use find) and you can use it in-place instead of the normal borg installed system-wide.
This might not be the most optimal way for it, but works for me ;)

**Comment by ThomasWaldmann** [comment]
I don't think we automatically create a binary while running the tox/py.test tests, but IF there is a borg.exe in the PATH, the unit tests will test it. How to make such a borg binary is described in our docs, development section (and one can also see it in the Vagrantfile).

**Comment by verygreen** [comment]
I put binary in quotes because it's not really a binary, but you can use full path to the created script and it works to execute the experimental built version even outside of the tox/virtualenv chroot if you call it directly.

**Comment by ThomasWaldmann** [comment]
Ah, yes, that is generally true for stuff installed in a virtualenv.

**Comment by storcium** [comment]
I went ahead and installed in a normal environment, and am able to run borg with the option provided by enkore - thank you for the functionality and directions.  Right now waiting for a large backup to run with fine chunker granularity, then I will check what size chunks are being popular in the repo, and try to narrow into that size.

Does it make any sense to make the median size (third parameter) equal to MIN or MAX size?  If, for example, the chunk sizes are crowded around a particular value?

**Comment by ThomasWaldmann** [comment]
@storcium please note that the chunk sizes do not mean more than that the hash function's result value's last bits (in the window it considered) were zero. There is not other meaning than that. Deduplication happens to work good with that because cutting points shift with content shifts.

**Comment by storcium** [comment]
Thank you, Thomas.  I am going to dive deeper into the workings of the rolling hash.  For the time being, I am running a very fine grained parameter set on a powerful machine against a 500 GB data set.  Will produce a histogram as per @enkore and try again with the min/max/med based on that result.  Data is Intersystems Cache data mostly.  Oddly, on AIX it deduplicated to 92% reduction, while on OpenVMS it's much worse (all data is in Linux on NFS).  Thank you.

**Comment by enkore** [comment]
>  Oddly, on AIX it deduplicated to 92% reduction, while on OpenVMS it's much worse (all data is in Linux on NFS). 

Indeed, that doesn't sound right. If your repos are encrypted then there is typically a small variation due to the random seed supplied to the chunker (to make fingerprinting attacks harder), but it shouldn't be very large (except for a few lucky cases from 2**32 for specific data sets).

Try running the test suite ([instructions](http://borgbackup.readthedocs.io/en/stable/installation.html#using-git)) to see if there may be other issues.

If you're running `master` anyway you can use something like `borg list --format '{path} {sha1}{LF}' /path/to/repo::archive` to check whether the file contents are reproduced correctly.

**Comment by storcium** [comment]
Yes, it seems we are not deduplicating anything.  I was able to set up a test with two backups of the same volume different by one day.  Each is about 25GB.  Repo is init using no encryption (-e none).  The files have the same database in them, so there should be at least some similarity.  Here is the result of two borg backups (borg 1.0.4.dev235+ng4302ffb.d20160525):

iss@issapl1:/data/volume1$ borg create -v --stats --progress --chunker-params 9,16,12,4095 /vault/repo1::t1 /data/volume1/s_data35-may302016-2239.bck
------------------------------------------------------------------------------
Archive name: t1
Archive fingerprint: 65863ede077cda7f5b4f934686ee2c6fa2c235172ad6bb5a6a488037258933b6
Time (start): Wed, 2016-06-01 09:30:16
Time (end):   Wed, 2016-06-01 09:39:31
Duration: 9 minutes 15.03 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               26.15 GB             26.16 GB             26.15 GB
All archives:               26.15 GB             26.16 GB             26.15 GB

                       Unique chunks         Total chunks
Chunk index:                 5267384              5281540
------------------------------------------------------------------------------


iss@issapl1:/data/volume1$ borg create -v --stats --progress --chunker-params 9,16,12,4095 /vault/repo1::t2 /data/volume1/s_data35-may312016-2243.bck
------------------------------------------------------------------------------
Archive name: t2
Archive fingerprint: dde49c916661458681d0f94ba9f71403cd3ae4c2b1845c56e6bc80d6ca11b5e2
Time (start): Wed, 2016-06-01 09:40:36
Time (end):   Wed, 2016-06-01 09:49:58
Duration: 9 minutes 22.07 seconds
Number of files: 1
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               26.20 GB             26.21 GB             26.04 GB
All archives:               52.34 GB             52.38 GB             52.20 GB

                       Unique chunks         Total chunks
Chunk index:                10389921             10571808
------------------------------------------------------------------------------

**Comment by ThomasWaldmann** [comment]
If changes are spread into most chunks, this will spoil the deduplication. Your target chunksize is already rather low (2^12 = 4096 Bytes). So can it be that almost all ~4096B pieces in your input files have some change in them?

Is maybe your input data already compressed or encrypted using a stream compression or cipher?

**Comment by storcium** [comment]
I checked and the data is definitely not compressed or encrypted, or rearranged.  This was the last few days I made sure to verify that.  In fact, I can read the data with the strings command.

I tried the same with chunk settings of 17,22,19

**Comment by ThomasWaldmann** [comment]
Hmm, I recently did changes (improvements) to the chunker. Is the dedup problem also there with 1.0.3?

**Comment by storcium** [comment]
Yes, I tested 1.0.2, 1.0.3 and 1.0.4

**Comment by storcium** [comment]
So it seems OpenVMS BACKUP tool rearranges data a lot by inserting CRC tags and other info into its records.  Unlike tar/gtar and databases and VM images, which are true to the underlying data.  I tried deduplicating part of the database itself with borg 1.0.4 and reduced 12 GB to 26 KB!  So with the chunk settings I guess it's trial and error, and best guess as to optimal parameters.  I wonder if a tool is possible that would look at two versions of a file (say Monday backup vs. Tuesday backup) and advise of approximate values for chunker.  Is that possible?

**Comment by ThomasWaldmann** [comment]
@storcium sounds like a generic chunker can not chunk such data (as from OpenVMS Backup archive) in a good way if it inserts varying data between records - that "spoils" any medium to large chunksize. Using a very small chunksize is not advisable due to resource usage.

I used that "spoiling by varying data" technique in my tool to generate large amounts of non-deduplicatable data: https://github.com/borgbackup/backupdata#mkdatapy

So 2 potential solutions:

- can you make OpenVMS backup create output that has bigger chunks of data that do not change if the underlying data did not change (== not spoiling the byte sequence by inserting varying data itself)? Something like a blocksize setting? Or another backup tool?

- is the backup archive format documented and easy enough so it can be checked whether a custom chunker makes sense?

**Comment by storcium** [comment]
@ThomasWaldmann thank you for the reference.  I have requested format info from HP, which owns OpenVMS support.  Will test a larger block size for backup.  Interestingly, inline compression, e.g. Gzip, bbcp yields 80% reduction in data size.
