### ISSUE TITLE
fixed record size chunker?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1086]
Maybe it is useful to add a fixed record size chunker additionally to the content-defined chunker to get better deduplication for that kind of data.

E.g. if a database file has fixed record size RS and an optional header with size HS, we could chunk like this:

```
HS | RS | RS | RS | ...
```

Of course one needs to be careful to not generate too many chunks or resource usage to manage them will go through the roof (so instead of chunking every RS, a multiple of RS might save some resources).

**Comment by verygreen** [comment]
This probably ties nicely into a per-file chunk params/chunkers too? This being just yet another option to choose from.

**Comment by ThomasWaldmann** [comment]
Related:

https://github.com/QubesOS/qubes-issues/issues/858

https://github.com/tasket/sparsebak

**Comment by ThomasWaldmann** [comment]
See #4238 for the fixed-blocksize chunker implementation.

Would be nice if this would get some practical testing by users having fixed-blocksize data (like disk / LVM images, simple databases, etc.). Due to the incompatibility, please use a separate test repo for testing this.

Like with the default "buzhash" chunker, one usually wants to avoid a huge amount of chunks. Thus, even if your disk sector size is 512b or 4096b, rather use a multiple of that a block_size for the chunker, e.g. 4MiB block size and 0 header size:
```
borg create --chunker-params=fixed,4194304,0 repo::archive diskimage.raw
```

**Comment by srd424** [comment]
This is looking very interesting - might be nice for partclone images too, which I think use a fixed record size.

**Comment by ThomasWaldmann** [comment]
Played with source data (pure random) and borg repo (unencrypted) on a ramdisk:

normal chunker (buzhash):
```
	Command being timed: "borg create -C none /tmp/ramdisk/borg-buzhash::arch /tmp/ramdisk/random.img"
	User time (seconds): 143.06
	System time (seconds): 12.74
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 2:35.83
```

**Comment by ThomasWaldmann** [comment]
@srd424 it's in master branch now.

**Comment by swatgoss** [comment]
Hi,

Im a "fairly" new user of borg, (only started using it a bit over 1year ago), and now i feed it all my backups (few TB of multiple "archives" of misc files, many TB of disk images consisting of qcow, raw, iso).

I currently have some server time to spare and i'm quite interested in "benchmarking" the different algorithms/parameters combinations !
(I/O shouldn't be a real limitation, since the server can easily handle around 100GB of data in /dev/shm + there is a few ~300GB of SSD storage left empty in the hypervisor, there is also a NAS for very large datasets tests. The hypervisor ships 2 Xeon E5649 if someone wonders)

What would be some useful test protocol to begin with ?
More precisely, what range of parameters do you think to be pertinent or do you want to see tested ?

I thought of some kind of script using GNU parallel script (or simple semaphore) to test parameters combinations (like 6~10 at a time) against an interesting ROMs set :
![borg info output](https://user-images.githubusercontent.com/3351720/58935943-e5056880-876e-11e9-9aa7-215b92c81376.png)
After some testing, i already lowered the chunkers params quite a bit to increase deduplication ratio without slowing down operations too much.

Never tinkered with rolling hash window size but before discovering this "fixed size chunking" option, it was my next idea of investigation ;)

**Comment by ThomasWaldmann** [comment]
you could practically test the `fixed` chunker with your raw disk images. find out if they have some header or just start from sector 0.

try it with a quite big (4MiB) and a small (64kiB) chunk size. watch how it affects dedup. check speed.

**Comment by verygreen** [comment]
When testing filesystem images - find out the underlying filesystem blocksize (if fixed, typically 4K, but much bigger on e.g. isofs) and also try that as one of the fixed chunk sizes.

**Comment by swatgoss** [comment]
Switched to a raw image of 40GiB, its a small Windows7 installation.

bmap says the following :

    
    <ImageSize> 42949672960 </ImageSize>

    
    <BlockSize> 4096 </BlockSize>

    
    <BlocksCount> 10485760 </BlocksCount>

    
    <MappedBlocksCount> 5872186  </MappedBlocksCount>

I launched 6 instances of borg 1.2.0a2 to test 512B 4096B 16384B 65536B 1048576B 4194304B blocksizes without compression or encryption, like the example of 8 Jan.

I'm planning on putting some awk to create a sort of CSV-like that will try to track the size of all repos seen by "du" every 10s or so ... but the slowest instance will generate a column of data far longer than the other

--------
blocksize =  65536
254.86user 38.86system 9:55.65elapsed 49%CPU (0avgtext+0avgdata 456412maxresident)k
64inputs+45709240outputs (0major+372181minor)pagefaults 0swaps
                       Original size      Compressed size    Deduplicated size
All archives:               42.98 GB             42.98 GB             23.32 GB

                       Unique chunks         Total chunks
Chunk index:                  355562               655492

**Comment by swatgoss** [comment]
I also checked sha256sum as suggested by piping `borg extract --stdout` on the 64KiB repo and it gave :
`a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e`

while bmap checksum is :
`c6f7f58d35636baff7a4528d6298968a107cfd7dfdb6225515bcb2df2194eca7`

To verify i relaunched a batch of 5 instances (excluding the 55mins 512B parameter) to see if images are different of each other ...

**Comment by ThomasWaldmann** [comment]
Please use the `sha256sum filename.raw` command to compute the whole-file hash.

**Comment by swatgoss** [comment]
After rerunning a batch (swapping 512B test for 8KiB) and this time i wrote the data on the NAS, so the 3 first runs can be a little bit slower the 3 last tests.

The sha256sum is the last line appearing on each "log", and is really identical between all of them

```
blocksize =  4096
521.34user 49.76system 11:51.84elapsed 80%CPU (0avgtext+0avgdata 5570500maxresident)k
72inputs+35245216outputs (0major+2395456minor)pagefaults 0swaps
                       Original size      Compressed size    Deduplicated size
All archives:               43.39 GB             43.42 GB             17.37 GB

                       Unique chunks         Total chunks
Chunk index:                 4173593             10487716
a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e  -
```
```
blocksize =  8192
381.58user 41.11system 9:47.17elapsed 71%CPU (0avgtext+0avgdata 3085496maxresident)k
72inputs+39500368outputs (0major+1374688minor)pagefaults 0swaps
                       Original size      Compressed size    Deduplicated size
All archives:               43.17 GB             43.19 GB             19.76 GB

                       Unique chunks         Total chunks
Chunk index:                 2394309              5243858
a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e  -
```
```
blocksize =  16384
308.76user 36.15system 8:36.13elapsed 66%CPU (0avgtext+0avgdata 1485380maxresident)k
72inputs+42165280outputs (0major+678108minor)pagefaults 0swaps
                       Original size      Compressed size    Deduplicated size
All archives:               43.06 GB             43.07 GB             21.35 GB

                       Unique chunks         Total chunks
Chunk index:                 1298594              2621924
a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e  -
```
```
blocksize =  65536
251.67user 32.31system 5:51.67elapsed 80%CPU (0avgtext+0avgdata 457868maxresident)k
72inputs+45709240outputs (0major+209987minor)pagefaults 0swaps
                       Original size      Compressed size    Deduplicated size
All archives:               42.98 GB             42.98 GB             23.32 GB

                       Unique chunks         Total chunks
Chunk index:                  355562               655492
a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e  -
```
```
blocksize =  1048576
232.24user 34.82system 5:49.73elapsed 76%CPU (0avgtext+0avgdata 74876maxresident)k
72inputs+48079192outputs (0major+40030minor)pagefaults 0swaps
                       Original size      Compressed size    Deduplicated size
All archives:               42.95 GB             42.95 GB             24.61 GB

                       Unique chunks         Total chunks
Chunk index:                   23479                40969
a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e  -
```
```
blocksize =  4194304
235.64user 36.61system 5:39.56elapsed 80%CPU (0avgtext+0avgdata 74752maxresident)k
72inputs+48271608outputs (0major+39520minor)pagefaults 0swaps
                       Original size      Compressed size    Deduplicated size
All archives:               42.95 GB             42.95 GB             24.71 GB

                       Unique chunks         Total chunks
Chunk index:                    5896                10244
a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e  -
```

**Comment by ThomasWaldmann** [comment]
does the sha256 hash of the extracted data now match the hash computed for the original file when using the `sha256sum` tool?

**Comment by swatgoss** [comment]
Yep, when using `sha256sum` on the raw image i get the same hash.
That leaves a mystery about the hash given by bmap in its file ...

```
pv /dev/shm/windows7-clone.raw | sha256sum -
40.0GiB 0:05:08 [ 132MiB/s] [==============================>] 100%
a20947f3285d9d61ae4fb14a9b8d3521eb76534498a0d8a4f1e6b69db8db399e  -
```

Now i have 2 questions,
- You seemed to imply that images after extraction could be different when using the fixed size chunker, do you have any precisions about this idea ? where would the differences in extracted image come from ?

- Does the fixed size chunker means that a multithreaded borg is to be expected in a near future ?
Since you know the size of next chunks, it should be possible to process them in parallel and compare them to the central "unique chunks database" to see if you need to write them in repo or "just" make a reference to a known data chunk ...

many years ago i saw https://github.com/imcleod/VMDK-stream-converter that compressed vmdk and always thought that reading multiple chunks at a time to compress/store them, without reordering, could provide a significant improvement in practical throughput. (that was before brotli or zstd btw)

**Comment by swatgoss** [comment]
Another interesting fact, the repos seem pretty compressible by ZFS lz4 on my NAS.
Compressed and apparent data given by `du -shmc` with and without `--apparent-size` option :

```
| blocksize | compressed | apparent | gain  | relative | 
|-----------|------------|----------|-------|----------| 
| 4096      | 9287       | 16957    | 7670  | 54,76    | 
| 8192      | 10283      | 19107    | 8824  | 53,82    | 
| 16384     | 10948      | 20496    | 9548  | 53,41    | 
| 65536     | 11798      | 22287    | 10489 | 52,94    | 
| 1048576   | 12604      | 23475    | 10871 | 53,69    | 
| 4194304   | 12610      | 23570    | 10960 | 53,50    | 
```

**Comment by ThomasWaldmann** [comment]
Well, the purpose of testing an alpha is finding bugs that the unit tests did not find.
So successfully comparing the hashes just made sure there is no bug.

The fixed size chunker has nothing to do with the multithreading work and no, that is not expected in the near future. Also, I guess one would likely keep strict sequential reading within the input file for performance reasons for the generic use case (which needs to cover HDDs and SSDs).

**Comment by ThomasWaldmann** [comment]
About compression: not really on-topic in this ticket.

If you compress or encrypt with borg, I find it unlikely that zfs will be able to compress.

If you don't compress and don't encrypt with borg, zfs compression working is expected and depends on your backed up data.

**Comment by swatgoss** [comment]
The point i was trying to make was that the compressibility of the borg deduped repo data seems to increases the compressibility of the remaining data, the more its deduplicated the more it compresses.

On the multithreading point, do you mean that taking a "pool of next chunks" (like readahead) and then dispatching to multiple worker threads  (for hashing and compression maybe) before gathering the results and then plugging them in the normal pipeline of operation would not be technically possible in the implementation of the borg algorithm/pipeline ?

By any chance do you have a tool/debug/functionnality that would allow to display/track how much time or cycles is spent in each "step" (chunking, compressing, comparing, writing to repo ... and many more) of the actual (monothreaded) pipeline of operations ?

**Comment by ThomasWaldmann** [comment]
guess readahead should work as long as it is just linear read. reading from same file at the same time at different positions would likely degrade hdd read performance. but that will be decided later and likely start rather simple when multithreading is implemented.

there is no timing info yet, but a ticket to add such.

**Comment by verygreen** [comment]
parallel processing of chunks does not imply you need to read from multiple positions and disrupt readahead.

You can just read sequentially and then pass the chunks (that presumably you can read faster than you can process) into separate processing threads to compress in parallel.

**Comment by swatgoss** [comment]
Thats quite my thought too, and since reading, chunking and hashing can be done without knowledge of underlying data, maybe the parallelisation of those tasks in a "fixed size chunking" context could bring some huge speedups.

I take my inspiration of piping mbuffer and pigz (not really anymore) in pipes to compress large quantities of data and getting a near optimal throughput between disk I/O and CPU usage.
+ it also works for transmitting data over "uneven bandwidth over time" network and allowing to get the last drop of a single connection (eg. tcp session)

**Comment by swatgoss** [comment]
Hi again, im back to add another "souvenir", the example given in PLZIP seems to be quite similar to the case of borg processing fixed size chunks, maybe some of their design (https://www.nongnu.org/lzip/manual/plzip_manual.html#Program-design) can be transposed and allow some increase in borg speed of operation !

Hope this could be of any use, or just a small discovery for those that didnt already know about LZIP !

**Comment by ThomasWaldmann** [comment]
Multithreading is planner for a later borg release, there's also a ticket about it.
