### ISSUE TITLE
Binary files impossible to start

### ISSUE THREAD

**Issue by iGormilhit** [borgbackup/borg#1087]
I'm sorry to bother you with this, but I'm trying to install the standalone binary on a debian wheezy server, following the instructions of the [documentation](https://borgbackup.readthedocs.io/en/stable/installation.html#standalone-binary).

So, I have a borg file, which is the binary, under ``/usr/local/bin/``, which is executable. But when I test it with ``borg -V``, I get the following message, in french : ``-su: /usr/local/bin/borg : fichier binaire impossible à lancer`` which I could translate into : ``binary file impossible to start (or lauch)``.

I tried also to ``cd`` into the directory and do a ``./borg -V`` with the same results. I think that I must miss some dependencies, or something, but I can't find what.

**Comment by devrando** [comment]
Is your /tmp mounted with the option `noexec`? 
Please try again after remounting /tmp with exec
`mount -o remount,rw /tmp`

**Comment by ThomasWaldmann** [comment]
In case @devrando's hint does not work, I need the output of that:
```
sha256sum borg
uname -a
dpkg -l | grep libc
```

**Comment by devrando** [comment]
Just checked again, the error if /tmp is mounted with `noexec`is different:
```
root@seafile:~# mount -o remount,noexec /tmp
root@seafile:~# borg
borg: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
root@seafile:~# mount -o remount,exec /tmp
root@seafile:~# borg
usage: borg [-h] [-V] <command> ...


```

**Comment by iGormilhit** [comment]
I'm trying to document myself about this /tmp and how to mount it. The fact is that I don't have any separate partition for /tmp, and can't find anything related to it in /etc/fstab.

I can see that : 
```
cat /proc/mounts | grep tmp
udev /dev devtmpfs rw,relatime,size=10240k,nr_inodes=493025,mode=755 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=395636k,mode=755 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /run/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=2353680k 0 0
```

So maybe I should try ``mount -o remount,exec /tmp``, but I'm not so much confident about it. Will I have to do it again if I restart my server ? How does that impact the security of my server ?

**Comment by iGormilhit** [comment]
But I can't remount /tmp : 

```
# mount -o remount,exec /tmp
mount : impossible de trouver /tmp dans /etc/fstab ou /etc/mtab
```

There's no /tmp in fstab or mtab.

**Comment by iGormilhit** [comment]
I'm dumb ! I didn't get the right binary ! Darwin != Linux.

Sorry... Now it works.

Thank you for your answers...

**Comment by ThomasWaldmann** [comment]
Yes, darwin is for mac os x.
