### ISSUE TITLE
Repository: compact should delete 'lone commits'

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1088]
compact should delete superfluous segments containing only a commit tag to avoid cluttering the repository with small commit segments.

Old commit tags were routinely deleted by compaction in earlier versions because they where together with data in a segment. Since these commit segments usually contained the manifest the where compacted when a new manifest was written.

For details see #1075

**Comment by enkore** [comment]
I've been thinking about this.

The <=1.0.x-way of things is to always compact which incidentally also leaves only two commits in the repository (one before compaction started, one after it finished; or some more if save_space=True), while the current master code would generally preserve commits (however, due to compaction, the transactions contents are not preserved as-is). Since these are quite small (on a unixy-FS with no data inlining: 1 block + 1 inode) I'm thinking we should just leave these be, since they still more-or-less represent points that can be rolled back to when newer commits are corrupted (i.e. limiting rollback damage) somewhat.

**Comment by ThomasWaldmann** [comment]
Hmm, I don't understand how these "lone commits" are still valuable as roll-back point - aren't they superceded as soon as the preceding segments are compacted (and thus, removed)?
