### ISSUE TITLE
configurable path prefix

### ISSUE THREAD

**Issue by rsplaul** [borgbackup/borg#109]
Especially when dealing with snapshots as a backup source it is a little bit annoying that the path prefix which is stored in the backup can't be configured. For example, if I have two separate filesystems mounted as `/media/music` and `/media/movies` respectively, and I'm mounting their snapshots (one after the other of course) to `/mnt/snapshot` to do a backup, the resulting path stored in the backup would have a superfluous `/mnt/snapshot` prefix – while not indicating the original mount point at all. 
A solution could be an option that allows for stripping off the whole path (or maybe a certain amount of directory levels, just like the `-p` option of the `patch` utility) and optionally preceding the filename with a configurable path when storing the files in the backup storage.

**Comment by ThomasWaldmann** [comment]
at extract time, there is borg extract --strip-components already.

for backup, one has to consider that borg maintains a "files" cache / index that maps hash(file_path) -> (mtime, inode, size). it is used to quickly determine whether a file has been modified. so, we have to make sure that matching/skipping still works reliably.

**Comment by ThomasWaldmann** [comment]
see also: https://github.com/jborg/attic/issues/262

**Comment by rsplaul** [comment]
Alright, I didn't have the --strip-components option in mind. Doesn't really help when mounting the backup with fuse, but that's probably not a big problem.

How does the idea of stripping away or prefixing the path in the backup interfere with the files cache? Obviously the cache won't be of any use when you keep changing the path, but that probably isn't what one is going to do anyways...

**Comment by ThomasWaldmann** [comment]
Guess the cache will need to continue having the full path.

**Comment by rsplaul** [comment]
But the full path is known, because that's where the files are copied from, is it? ;-) And the relation full path <–> stored path would be known from the command line option. Anyways, if that's too much work, I suggest improving other parts of borg instead. And if not, I'd vote for a --strip-components option for borg create.

**Comment by FabioPedretti** [comment]
As a workaround you can change dir into the base path and create for relative paths:
`cd /mnt/snapshot`
`borg create .... music movies`

**Comment by ThomasWaldmann** [comment]
closing this, see what @FabioPedretti suggested.
