### ISSUE TITLE
recreate command should allow to keep a backup

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#1098]
im about to start to experiment with it, and i'd really like it better if by default it would backup and the same name case would only override the archive (the reason simply enabling to verify the result *before* loosing the source)

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/34667358-recreate-command-should-allow-to-keep-a-backup)

**Comment by pepa65** [comment]
You mean like:
```
borg create ::nameAGAIN
borg prune -y 1 -P name
borg rename ::nameAGAIN name
```
Except the above would not go well if there are other names starting with name...  I might use `borg recreate` for some things..!

**Comment by enkore** [comment]
> Possibly add a --target option to not replace the source archive -- with the target possibly in another Repo (better than "cp" due to full integrity checking, and deduplication at the target)
