### ISSUE TITLE
Add create-and-prune command or repl mode

### ISSUE THREAD

**Issue by wienczny** [borgbackup/borg#1099]
I'm currently using a small script to create my backups that has two statements.

borg create ...
borg prune ...

Both commands require the password to be entered. I'm currently entering those passwords manually. It would be great if only one password was required. I could use an environment variable but I don't like the idea of storing my password in the shell environment while doing the 'create' part.
I suggest adding a single command that does create and prune.
Alternatively you could add a repl mode where you run borg commands line by line (create, prune). Then one could even pipe the commands to borg.

**Comment by ThomasWaldmann** [comment]
If you do not enter it manually, but have it in the BORG_PASSPHRASE env var, it won't ask.

**Comment by wienczny** [comment]
Yes I could use the BORG_PASSPHRASE environment variable, but I don't like that idea because of `cat /proc/<pid>/environ`. Try that on any process below the shell that exports BORG_PASSPHRASE (like borg). You can read the password. Using /proc/<pid>/mem is not that easy.
As the password is required to decode the repo key and derive some key material for block map etc. It can be discarded after these values are present.

**Comment by enkore** [comment]
> because of cat /proc/<pid>/environ

For exactly this reason the environ file has 0400 access rights.

**Comment by wienczny** [comment]
This does not prevent `root` or any user with CAP_DAC_OVERRIDE from reading it. The environment may not be as secure on other UNIX like OS.
The environment is passed down to any spawned process that does not know about the secrets. This may leak the keys.

**Comment by enkore** [comment]
> This does not prevent root or any user with CAP_DAC_OVERRIDE from reading it. The environment may not be as secure on other UNIX like OS.

Ok, but someone with root/DAC_OVERRIDE can per definition read anything anyway. He could even attach a (python) debugger to your processes and just print the variables. Or just read the script/file where the password is stored.

In this scenario there is hardly a way to do this safely. Even passing it over an open and inherited file descriptor (like gpg(1) supports it) wouldn't be safe.

>  The environment is passed down to any spawned process that does not know about the secrets. This may leak the keys.

Fair point.

**Comment by ThomasWaldmann** [comment]
I think this ticket should be closed and every single point found valuable should be taken to its own ticket:

- create-and-prune in 1 command: nope
- repl / "borg shell": maybe, create own ticket and make clear what you mean
- not passing BORG_PASSPHRASE or other secrets to subprocesses not needing them: own ticket

**Comment by enkore** [comment]
#1103 #1104
