### ISSUE TITLE
Noob Question 1 : How to start borg once installed from git ?

### ISSUE THREAD

**Issue by PerfMonk** [borgbackup/borg#110]
Sorry for the noise!

I'm new to borg and have no notion of python.  Once installed as well well described at https://borgbackup.github.io/borgbackup/installation.html, how to I start borg from another new shell ???

The borg command doesn't seem to be in path and if I do command from the installed shell terminal, everything is working OK.  But once I exit the shell, how do I start borg ?  I haven't found any documentation about it.

Regards,
               BT

**Comment by ReimarBauer** [comment]
One way to do so is just to call it from the bin directory of your virtualeng. e.g.
assuming that you created the env directory in your $HOME dir.

~/borg-env/bin/borg -h

**Comment by ThomasWaldmann** [comment]
Yes, what reimar said. :) That is the easiest way.

Alternatively, you can also activate the virtualenv once and after that, borg will be in the PATH, so you can just invoke "borg":
source ~/borg-env/bin/activate
borg
borg
borg

**Comment by ThomasWaldmann** [comment]
TODO(?): add docs for this

**Comment by PerfMonk** [comment]
Thanks a lot!    I agree that it could be documented for noob like me who are going to as why can't I start borg anymore!

**Comment by ThomasWaldmann** [comment]
updated docs: https://github.com/borgbackup/borg/commit/fb998cbd66c78a88b51e58bac2042454c99280cf
