### ISSUE TITLE
recreate should detect+skip already compressed chunks

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1100]
> Detect and skip (unless --always-recompress) already recompressed chunks -- delayed until current PRs on borg.key APIs are decided #810 #789

(from #812)

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/34680260-recreate-should-detect-skip-already-compressed-chunks)

**Comment by ThomasWaldmann** [comment]
fixed by #1420.
