### ISSUE TITLE
Protect indices and other auxiliary files with checksums

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1101]
> Add a 'N.check' file or something similar with a checksum of the index and hints files. Corruption in these can be a) silent b) throw away data c) do other bad things. Devise a mechanism how the presence of a .check file can be inferred for existing repos.

(from #858)

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/34680322-protect-indices-and-other-auxiliary-files-with-checksums)

**Comment by ThomasWaldmann** [comment]
Just append / prepend a hash / hmac?

**Comment by enkore** [comment]
That doesn't cut it because the length of the index files is checked when reading them. It would have to be compatible both ways.

My line of thought

- Repository setting default=false.
- If the repo is opened and that is false then no checking is done/expected
- Otherwise absence/incorrectness of the check file means full recovery
- If a commit is made and the setting is false, it's flipped to true and saved, the commit is made and a check file created

API wise:
- hashindex_read takes (optional) hash to verify read data against (no double read = no room for inconsistencies, no real performance penalty)
- hashindex_write calculates hash at the same time

**Comment by ThomasWaldmann** [comment]
Why add a setting if the only(?) purpose is to support old index files?

**Comment by PlasmaPower** [comment]
I'm assuming a CRC32 is good? Also, is this specific to `hashindex`?

**Comment by enkore** [comment]
Both the indices and the hints file should be protected.

The checksum should be algorithm-agile (possible to change later), e.g. `sha512:abcdef...`.

**Comment by enkore** [comment]
Fixed by #1688 #2496 #2502 #2568 #2580

**Comment by ThomasWaldmann** [comment]
\o/ - claim bounty.
