### ISSUE TITLE
Extract without full path

### ISSUE THREAD

**Issue by Ovski4** [borgbackup/borg#1102]
Hi,

I would like to know if there is a way to extract an archive without getting the full path. I didn't find this answer in the "borg extract options".

If I am in **/home/user**, and want to extract the directory **/home/toto/important_files** from my backup, I will get the following path:  **/home/user/home/toto/important_files**.

I find this dangerous, because a user might want to delete the home directory recursively : **rm -rf ~/home/**
If by mistake, It runs **rm -rf /home**, it's bad. It's even worse for other directories etc/, and so on.

Thank you!

**Comment by ThomasWaldmann** [comment]
from `borg extract` help
```
  --strip-components NUMBER
                        Remove the specified number of leading path elements.
                        Pathnames with fewer elements will be silently
                        skipped.
```

**Comment by ThomasWaldmann** [comment]
In general: causing a desaster by badly mistyping `rm` or other commands is not in scope of this issue tracker. The general rule here is to better type such stuff slowly and read / think again for a few seconds before hitting enter. In case you nevertheless cause a desaster, that is why you have (full) backups.

**Comment by Ovski4** [comment]
Thank you for your answer, I read to quickly and didn't get the purpose of this option. I agree with what you said anyway, I always try to be as careful as possible.

**Comment by jcrben** [comment]
The commands and options here are rather unfriendly to the user...

**Comment by ThomasWaldmann** [comment]
@jcrben so, what is your suggestion to improve?

**Comment by jcrben** [comment]
Sorry to be critical without more details!

Why would an option for removing leading path elements be called `--strip-components`? Naming is hard, it's easier to criticize than create, but keep in mind that even if the users are mostly programmers we are still humans...

I think also this sort of problem is better solved by specifying the path directly rather than trying to strip out elements. It's like the difference between an array and a hash map: see https://www.reddit.com/r/programming/comments/lirke/simple_made_easy_by_rich_hickey_video/

**Comment by ThomasWaldmann** [comment]
So, what you suggest is --strip-path=/path/prefix/to/strip ?

**Comment by jcrben** [comment]
Maybe, but I guess I was thinking I'd just specify the full intended pathname explicitly as an override. I haven't run into this use case yet.

I guess I'd also rather just use code to do something like this... I'm mostly using borg-backup in an automated fashion with scripts so I would probably just split the path and slice it as necessary if needed.

**Comment by ThomasWaldmann** [comment]
@jcrben not sure i understand. assume you have these pathes in the archive:

mnt/server/home/username/document.txt
mnt/server/etc/passwd

So, one likely will want `borg extract --strip-path=mnt/server/ archive::repo` (as an easier replacement for --strip-components=2).

So, what would you do?

**Comment by Tuxie** [comment]
IMHO, it would be most intuitive to be able to append the extraction root path to the repo definition, and use ending slashes like rsync:

borg extract archive::repo/mnt/server/ home/username/document.txt etc/passwd

Extraction would work like this:
borg backup archive::home-2016-11-12 /home

cd ~/code/
borg extract archive::home-2016-11-12/home/tuxie/code/ my_project

or

mkdir ~/code/my_project_restored
cd ~/code/my_project_restored
borg extract archive::home-2016-11-12/home/tuxie/code/ my_project/

**Comment by ThomasWaldmann** [comment]
I don't think we want to make the repo::archive parsing even more complex than it already is (in contrary: there is a ticket to make it simpler by splitting it up).

**Comment by jcrben** [comment]
I think what I want is basically just a destination path for extract: https://github.com/jborg/attic/issues/195

Generally when I'm extracting it is to examine the backup first rather than just clobbering my existing files...
