### ISSUE TITLE
borg extract --verbose --progress

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#1107]
i always expect borg to be super fast. and it is!

yet `borg extract` is not really satisfactory: it can take a while to tell you it can't find a file in the archive. this is a bit frustrating, especially on a clear VM cache:

```
root@marcos:~# echo 3 > /proc/sys/vm/drop_caches
root@marcos:~# time borg extract -v  /media/sdc2/borg/::marcos-2016-05-30 var/spool/cron/crontabs
real    1m16.672s
user    0m22.588s
sys     0m2.416s
```

things are obviously better with a primed cache:

```
root@marcos:~# time borg extract -v  /media/sdc2/borg/::marcos-2016-05-30 var/spool/cron/crontabs

real    0m23.155s
user    0m21.436s
sys     0m1.628s
```

... but that's not very useful because `extract` is often run here and there to extract only this one file that was mistakenly destroyed (for example).

I was expecting `-v` to tell me stuff like:

```
opening repository
finding archive
looking for file
extracting content...
foo
bar
baz
all done!
```

`--progress` would obviously be also useful here to add progress bars above.

more info about the setup:

```
root@marcos:~# lsb_release -d
Description:    Debian GNU/Linux 8.4 (jessie)
root@marcos:~# uname -a
Linux marcos 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux
root@marcos:~# borg --version
borg 1.0.2
root@marcos:~# borg  list /media/sdc2/borg | wc -l 
500
root@marcos:~# time borg info /media/sdc2/borg/::marcos-2016-05-30
Name: marcos-2016-05-30
Fingerprint: dd79e1d17c0d1a3f57f3f7663dae37b0193104a321d37da07f2f5f474f1d2924
Hostname: marcos
Username: root
Time (start): Mon, 2016-05-30 07:38:54
Time (end):   Mon, 2016-05-30 07:52:55
Command line: /usr/bin/borg create --one-file-system --verbose --stats /media/sdc2/borg::marcos-2016-05-30 / /boot /usr /var /home --exclude-caches --exclude /home/*/.cache --exclude */.Trash-* --exclude */[Cc]ache/* --exclude */.bitcoin/blocks/* --exclude *.vmdk --exclude /tmp/* --exclude */build-area/* --exclude /proc/* --exclude /dev/* --exclude /sys/* --exclude /var/cache/* --exclude /var/tmp/* --exclude /var/log/*
Number of files: 1698760

                       Original size      Compressed size    Deduplicated size
This archive:              212.73 GB            187.30 GB            590.28 MB
All archives:              142.37 TB            125.27 TB            671.69 GB

                       Unique chunks         Total chunks
Chunk index:                14719975           2897409051

real    0m57.973s
user    0m20.528s
sys     0m9.272s
```

... it would be nice to have a single command to dump all that for bug reports. ;) debug-environment?

**Comment by ThomasWaldmann** [comment]
Yes, we maybe could add some more progress indication. We maybe could show stuff which we did *not* extract, just to give an impression about the progress?

borg processes all the files in the archive in a sequential way and extracts whatever matches the stuff you gave on the commandline. there is no index or fast-forward, so this is like tar speed-wise.

**Comment by enkore** [comment]
extract --progress (#1449) adds some more output here, besides progress also some status output while fetching metadata

**Comment by confidentidiot** [comment]
What is the correct syntax to get borg to display any verbose output or progress information during an `extract` operation?  I am currently test driving borg version 1.0.11 on Ubuntu Mate 16.04.1 and backing up to a remote repository running FreeBSD 11.1 via SSH.  The following commands do not produce any output or status information:

```
borg extract --list /path/to/repo::archiveName
borg extract --verbose /path/to/repo::archiveName
```
The option `--progress` is not a recognized argument.

**Comment by enkore** [comment]
I think for 1.0 you would need both --list and --verbose. --progress does not exist there.

**Comment by confidentidiot** [comment]
That seems to have solved it.  Thanks, @enkore !

**Comment by ThomasWaldmann** [comment]
we have --progress since quite a while.
