### ISSUE TITLE
borg hangs on full target disk

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#1114]
last night i started a backup of data that i originally did back up with the small chunker params
this morning i found out the disk was full and borg was hanging

**Comment by ThomasWaldmann** [comment]
borg needs space to work - even to delete stuff (or start a transaction) - this is why the docs say to avoid full repo disk conditions.

you can try deleting the segment files of the last incomplete backup and then run `borg check --repair`. After that, use borg delete or prune with the `--safe-space` flag.

See also: #327 #364 #239

**Comment by RonnyPfannschmidt** [comment]
the issue i want to see addressed here is borg not exiting with a failure (and maybe a checkpint) on a full disk

**Comment by ThomasWaldmann** [comment]
Hmm, maybe related to #1138 (so fix that first and then try to reproduce with / without that fix).

**Comment by RonnyPfannschmidt** [comment]
i believe with #1263 my issue is reasonably well solved as well, do you agree @ThomasWaldmann @enkore

**Comment by ThomasWaldmann** [comment]
Likely yes. Just try to reproduce?

**Comment by RonnyPfannschmidt** [comment]
ok, will try with a vm in a bit

**Comment by enkore** [comment]
> This should be solved with #1263 and #1272 / #1336. If there are still corner cases that are currently not handled a new report should be created.

(or just post it here)
