### ISSUE TITLE
no progress bar at the segment cleanup step for delete/prune

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#1115]
when running a delete on a no-append-only repository,
after the decrement references step, there is a cleanup step, which does not show a progress bar

so on a large repo one is left wondering

**Comment by ThomasWaldmann** [comment]
Guess you mean the `compact()` call, where it compacts the segment files.

**Comment by RonnyPfannschmidt** [comment]
exactly

**Comment by enkore** [comment]
With the progress handling changes implementing this should be pretty simple.
