### ISSUE TITLE
OSXFUSE Runtime Version Mismatch

### ISSUE THREAD

**Issue by tristan-k** [borgbackup/borg#1118]
I'm running Mac OS El Capitan with `osxfuse 3.3.2` and `borgbackup 1.0.3` from `brew cask`. When trying to mount a borgbackup I will get an error saying `OSXFUSE Runtime Version Mismatch`.

```
$ brew cask info borgbackup
borgbackup: 1.0.3
BorgBackup
https://borgbackup.readthedocs.org/en/stable/
/opt/homebrew-cask/Caskroom/borgbackup/1.0.3 (5,6M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/borgbackup.rb
==> Contents
  borg-darwin64 (binary)
```

```
$ borg mount /path/to/borgbackup ~/Desktop/BorgBackup
this OSXFUSE library version is incompatible with the OSXFUSE kernel extension
```

```
OSXFUSE Runtime Version Mismatch

The OSXFUSE library version this program is using is incompatible with the loaded OSXFUSE kernel extension.
```

```
brew cask info osxfuse-beta
osxfuse-beta: 3.3.2
OSXFUSE
https://osxfuse.github.io/
/opt/homebrew-cask/Caskroom/osxfuse-beta/3.3.2 (25 files, 6,8M)
https://github.com/caskroom/homebrew-versions/blob/master/Casks/osxfuse-beta.rb
==> Contents
  Extras/FUSE for OS X 3.3.2.pkg (pkg)
==> Caveats
You must reboot for the installation of osxfuse-beta to take effect.
````

So which version of osxfuse is compatible with borgbackup? Seems related to https://github.com/borgbackup/borg/issues/429

**Comment by enkore** [comment]
I don't know what brew does ... does it compile stuff from source? Or is it binary packages?

In the first case you may need to rebuild borg after updating osxfuse (this is really a osxfuse not a borg thing). In the second case someone else has forgotten to rebuild borg after updating osxfuse.

**Comment by tristan-k** [comment]
`brew cask` installs binaries. I found a [line](https://github.com/borgbackup/borg/blob/master/Vagrantfile#L57) in the vagrant file which is using osxfuse 3.2.0, which is outdated.

So I will have to build borgbackup manually?

**Comment by enkore** [comment]
From the URL mentioned in your console output above ( https://github.com/caskroom/homebrew-cask/blob/master/Casks/borgbackup.rb ) it suggests that they re-package the static binaries from the borg release page. These are built with the Vagrantfile, yes.

**Comment by tristan-k** [comment]
I tried `osxufse 3.2.0` which is working fine. So for the time being I will stick to this outdated version, but I would love to see borgbackup pick up the recent osxfuse version.

**Comment by ThomasWaldmann** [comment]
The 3.3.x series is just 11 days old. I usually try to use the latest osxfuse at the time of a borg release (at least when I have time to adapt the Vagrantfile and actually test whether everything still works).

I case you build you try a self-installed / self-built borgbackup with 3.3.latest, keep us updated whether everything works.

I am assigning the ticket to next release as a reminder to update osxfuse.

**Comment by tristan-k** [comment]
I noticed something else. Maybe it is related to the outdated osxfuse version. Mounting the volume works fine but the actual files stored inside are not accessable. In the finder (file browser) they all have a size of 0 Bytes. Trying to copy one file outside the fuse volume results in an error.

**Comment by enkore** [comment]
Try mounting with `--foreground` to if something goes wrong on borg's part.

**Comment by ThomasWaldmann** [comment]
@tristan-k if you have a different / additional borg/osxfuse issue, please open another ticket about it.

**Comment by tristan-k** [comment]
I have built borg from source and it mounts the repo just fine with the latest osxfuse version. I will close the issue, because with the next stable release from borg this should be resolved.

@ThomasWaldmann Opened another ticket at https://github.com/borgbackup/borg/issues/1126.
