### ISSUE TITLE
multithreaded lzma compression?

### ISSUE THREAD

**Issue by jxy** [borgbackup/borg#1124]
Is it possible to use multiple threads for lzma compression?  The xz util does a good job in doing so.  I guess making the whole backup program to be multithreaded may be nontrivial, multithreaded compression would make lzma more useful.

**Comment by ThomasWaldmann** [comment]
not yet.

it is planned to introduce some multithreading in 1.2 (conservatively, so we do not run into lots of issues with race conditions and crypto security). that might or might not include compression, let's see.

https://github.com/borgbackup/borg/milestones/1.2%20sequential%20threading
