### ISSUE TITLE
borg check: false negative for item metadata qualifier

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1135]
While analyzing #1130, I found a bug in borg check's internal "resync" code.

If an item metadata chunk is missing somehow, resync mode is triggered.
While it is active, it skips byte-wise over input data as long as the metadata dict qualifier returns a negative result.

The qualifier works by looking directly at the bytes in the input data (which is msgpacked serialized data) and looks for the bytes that introduce a mapping (dict) and a bytestring (key name inside the dict).

The problem was that it only checked for fixmap and that is only used for metadata dicts up to 15 items. If an item had more metadata, map16 is used and the qualifier did not check for that and thus returned a false negative, skipping over the (valid) data.

Another (theoretical) problem is that it only checked for fixstr and that is only used for bytestrings up to 31 bytes. If a metadata dict key were longer than that, str16 (or str8 or str32) would be used and the qualifier would not check for that and thus return a false negative, skipping over the (valid) data. This is not a real problem for borg, as (currently and in the past) all dict keys are shorter than 32 bytes.

**Comment by enkore** [comment]
len(borg.constants.ITEM_KEYS) = 19, but not all of them can occur on one item. acl_default/acl_access and acl_extended and acl_nfs4 are mutually exclusive. Making the count 17/18. bsdflags is in 1.1 for Linux, making it 17 there as well. hardlink_master and source are mutually exclusive, making it 16. rdev usually doesn't occur, making it 15.

So it's an issue, but it'll be very, very rare.

**Comment by ThomasWaldmann** [comment]
Are you implying this change should not be applied to 1.0-maint?

**Comment by enkore** [comment]
I'd say it's not a bugfix in 1.0-maint ("check may break things"), but more like a, err, "compatibility-with-future-versions enhancement".

**Comment by ThomasWaldmann** [comment]
Hmm, if an archive is made with 1.1+ (assuming repo format is still compatible), running borg-1.0 check on it might trigger this "bug". With --repair, I guess it could remove valid data then.

**Comment by enkore** [comment]
Yes and that's about what the changelog should say. Note that accessing a 1.1+ repo from 1.0.x already requires some manual intervention (deleting hints+index)

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/1148 fixes this.
