### ISSUE TITLE
confused I/O Error reporting / handling

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1138]
I am moving this comment by @nesneros which was originally in #1130 to a separate ticket:

Error message seen in log output:
```
/home/jan/projects/spark/core/target/scala-2.11/test-classes/org/apache/spark/rdd/AsyncRDDActionsSuite$$anonfun$1.class: [Errno 5] Input/output error
```

I was thinking more about these I/O errors and disconnection to the target drive. I would think one could experience I/O errors on the target if it suddenly is disconnected. Could the I/O errors be a "reporting bug" in borg? That the I/O error is  related to a file on the target, but is reported for the file being processed on the source? 

I archiver.py around line 328 there is code like:
```
                try:
                    status = archive.process_file(path, st, cache, self.ignore_inode)
                except OSError as e:
                    status = 'E'
                    self.print_warning('%s: %s', path, e)
```
If the process_file function is writing to target I think this could explain the behaviour. My Python skills are basically non-existing so I might be completely off track.

***
As seen in #1130 just ignoring the OSError when writing to the repo and continuing with next file leads to a corrupt, but completed transaction committed to the repo.

If the error would be handled as a fatal error, the transaction would be incomplete and (I guess) easily rolled back.

The bounty is for fixing the wrong log output and the wrong exception handling leading to corruption.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/34878887-confused-i-o-error-reporting-handling)

**Comment by ThomasWaldmann** [comment]
Reply by @encore:

Yes, the reporting isn't very good there. If you get an EIO when writing to the repository it may seem like the EIO came from reading a backup file.

I'm not sure but it could be possible that the file system you use, smbnetfs, gives EIO if there are connection problems.

**Comment by ThomasWaldmann** [comment]
Note: until fixed, such a log entry has to be interpreted as:

"while processing the file at the left, the error shown at the right occurred." and "processing" does not just include reading that file, but also a lot of other operations, like writing the resulting chunks to the repo.

**Comment by enkore** [comment]
So...

- Wrap try/except OSError around operations on (and only on) the backup source set, remove try/except OSError for process_file etc.
- Or use InternalOSError everywhere else? Like in 1cc644

**Comment by ThomasWaldmann** [comment]
A conservative fix for 1.0-maint would be good.

**Comment by enkore** [comment]
> InternalOSError

Thinking about this I concluded that this is a bad solution. The inverse should be used instead (e.g. BackupOSError / InputOSError / ...), since that's fail-safe, while InternalOSError is not.

**Comment by ThomasWaldmann** [comment]
@enkore see bountysource link.

**Comment by enkore** [comment]
Ah I didn't see that. Ok.

**Comment by andela-kerinoso** [comment]
I see this issue has categorized under  **milestone:"1.0.4 fixes for 1.0-maint"**; do I have to raise a PR against **1.0-maint** branch or straight to **master**?

**Comment by andela-kerinoso** [comment]
Also this fix does not take care of the lock on the repository. Due to inaccessibility of the backup repository for this scenario, the code has no means of breaking the lock. So before any other commands could be run, users would have to manually run `borg break-lock <path-to-repo>` when the repository is accessible again.

**Comment by enkore** [comment]
A fix will need to go into 1.0-maint; master may / may not need additional fixes over that for the features that are in master but not in 1.0-maint.

**Comment by andela-kerinoso** [comment]
PR #1180 seems to fix this issue.

**Comment by ThomasWaldmann** [comment]
@enkore please try fixing it. see also bountysource.

**Comment by enkore** [comment]
#1211
