### ISSUE TITLE
"borg delete" should allow to delete broken archives as well

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1139]
--force for borg delete, so that you can delete broken archives. I.e. it tries to delete normally, but doesn't fail if the metadata is corrupted, and the manifest entry is always removed at least [and the archive superblock deleted from the repo].

**Comment by ThomasWaldmann** [comment]
hmm, guess we could need that for dealing with #1138.

**Comment by ThomasWaldmann** [comment]
fixed by #1239 in 1.0-maint.
