### ISSUE TITLE
Feature request: local repo/archive made from remote directory

### ISSUE THREAD

**Issue by bjmuld** [borgbackup/borg#1141]
What I want is to automate scripts on my machine which stores the repository, and have it PULL directories for archiving from remote machines (encryption done on the remote machine.  borg on both).

Good feature, I think, unless it violates some security "principle" I'm overlooking. It would be useful to me.

Thanks for the hard work!

**Comment by ThomasWaldmann** [comment]
Hi @bjmuld - this is already discussed in #900.
