### ISSUE TITLE
--list option for prune needs -v

### ISSUE THREAD

**Issue by nesneros** [borgbackup/borg#1142]
Consider the follow prune command

```
$ borg prune --list -v -H 2 /media/jan/OS/borgbackup
Keeping archive: xps15-jan-2016-06-06T12:05:47        Mon, 2016-06-06 14:05:47
Keeping archive: xps15-jan-2016-06-06T11:54:40        Mon, 2016-06-06 13:54:40
```

If I remove -v I get no output. I assume that --list is intended to print the list regardless of -v is present or not?

```
$ borg -V
borg 1.0.3
```

**Comment by ThomasWaldmann** [comment]
For 1.0.x, this is expected behaviour, due to how "logging" works, see the docs.

We recently changed this, so in some future version, you likely won't need to give -v and more if some other option implies you want to see output.
