### ISSUE TITLE
Dealing with locked files to be backed up under Cygwin

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#116]
When attempting to backup the entire /cygdrive/C/Users/someuser/ directory for a currently logged in user, "borg create" will exit with an error if a particular file is exclusively locked.  

Instead, "borg create" should probably just warn and then skip any locked files which cannot be read, so that the majority of the files can be backed up on that run.  Perhaps with a command-line switch to restore the old behavior "--exit-on-lockedfile=true|false".

**Comment by ThomasWaldmann** [comment]
yes, of course it should not exit.

will have to check this for other error conditions also (my impression was that it never exits, but obviously it happens).

**Comment by ThomasWaldmann** [comment]
@tgharold what's the easiest way to reproduce this?

I have cygwin and borg running and when trying to backup the current user's profile dir, i get a lot of errno 16 device or resource busy warnings - but it still backs up everything else (before and after these warnings).

**Comment by tgharold** [comment]
$ cat python3.4m.exe.stackdump
Exception: STATUS_ACCESS_VIOLATION at rip=00400DD1884
rax=0000000073FC18F6 rbx=0000000017ABD088 rcx=000006FFF0BD100F
rdx=0000000600322120 rsi=000000060030C580 rdi=FFFFFFFFF3BD100D
r8 =00000000000219BB r9 =00000000CFF063D9 r10=0000000000000FFF
r11=000006FFFCFDE645 r12=000000000000001F r13=000000000000FFFF
r14=0000000000000FFF r15=000006FFF0BD0010
rbp=000000000C42EFF1 rsp=000000000022B070
program=C:\cygwin64\bin\python3.4m.exe, pid 16860, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B

**Comment by tgharold** [comment]
And on my other system:

$ borg create --progress --stats ssh://backups.tgharold.com/backup/thomast61p/borgs/borgmatic.borg::snapshot-$(date +'%Y%m%d-%H%M') /cygdrive/c/Users/tgh/
borg: /cygdrive/c/Users/tgh/AppData/Local/ElevatedDiagnostics: [Errno 13] Permission denied: '/cygdrive/c/Users/tgh/AppData/Local/ElevatedDiagnostics'
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session'
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs'
Segmentation fault (core dumped)B D cygdrive/c/Users/tgh...ion State/000531.log

$ cat python3.4m.exe.stackdump
Exception: STATUS_ACCESS_VIOLATION at eip=6388195E
eax=FC810008 ebx=80202B20 ecx=FC811007 edx=73FC18F6 esi=800E2158 edi=FD5D1005
ebp=02A2EFF9 esp=0028BDB0 program=C:\cygwin\bin\python3.4m.exe, pid 6768, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args

**Comment by tgharold** [comment]
Re-running the second backup with --verbose to see if it segfaults in the Chrome directory.  That would narrow it down to trying to backup:

/cygdrive/c/Users/USERNAME/AppData/Local/Google/Chrome/

While Chrome is running.

**Comment by tgharold** [comment]
Yeah, seems to have trouble with the Google Chrome directory:

A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Cookies-journal
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session'
? /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs'
? /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Custom Dictionary.txt
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Custom Dictionary.txt.backup
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Cookies
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Cookies-journal
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/000003.log
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/CURRENT
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/LOCK
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/LOG
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/LOG.old
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/MANIFEST-000001
d /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000008.sst
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000528.ldb
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000530.ldb
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000531.log
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000532.ldb
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/CURRENT
Segmentation fault (core dumped)

**Comment by ThomasWaldmann** [comment]
can you retry with a local backup repo (not ssh:), with/without encryption, with/without compression?
also, give the precise borg version number and the full commandline.

**Comment by tgharold** [comment]
Command that I'm using to test in borg 0.23.0

borg create --verbose --progress --stats ssh://backups.tgharold.com/backup/thomast61p/borgs/borgmatic.borg::snapshot-$(date +'%Y%m%d-%H%M') /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/

Will try to a local backup in a bit.

```
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Cache/f_00fc53
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Cache/index
d /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Cache
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/ChromeDWriteFontCache
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Cookieses
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Cookies-journal
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session'
? /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs'
? /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Custom Dictionary.txt
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Custom Dictionary.txt.backup
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Cookies
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Cookies-journal
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/000003.log
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/CURRENT
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/LOCK
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/LOG
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/LOG.old
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules/MANIFEST-000001
d /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension Rules
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000008.sst
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000528.ldb
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000530.ldb
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000531.log
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/000532.ldb
A /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Extension State/CURRENT
Segmentation fault (core dumped)
```

And the command that caused that segfault -- this was writing to a brand new borg repo, freshly created with "borg init".

tgh@thomast61p ~
$ borg create --verbose --progress --stats file:///home/tgh/borg-test/test.borg::snapshot-$(date +'%Y%m%d-%H%M') /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/

**Comment by tgharold** [comment]
Trying again without --verbose / --stats / --progress

```
$ rm -rf borg-test && mkdir borg-test && borg init file:///home/tgh/borg-test/test.borg
Initializing repository at "file:///home/tgh/borg-test/test.borg"
Encryption NOT enabled.
Use the "--encryption=passphrase|keyfile" to enable encryption.
Synchronizing chunks cache...
Rebuilding archive collection. Known: 0 Repo: 0 Unknown: 0
Merging collection into master chunks cache...
Done.

tgh@thomast61p ~
$ borg create file:///home/tgh/borg-test/test.borg::snapshot-$(date +'%Y%m%d-%H%M') /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/

borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session'
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs'
Segmentation fault (core dumped)

tgh@thomast61p ~
$ cat python3.4m.exe.stackdump
Exception: STATUS_ACCESS_VIOLATION at eip=6388195E
eax=FDE30008 ebx=80237518 ecx=FDE31007 edx=73FC18F6 esi=801A0A70 edi=FDE5E005
ebp=021A1FF9 esp=0028C0C0 program=C:\cygwin\bin\python3.4m.exe, pid 7824, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args

**Comment by tgharold** [comment]
Fails under the latest version from /master branch

```
tgh@thomast61p ~
$ pip3 install git+https://github.com/borgbackup/borg.git@master
Collecting git+https://github.com/borgbackup/borg.git@master
  Cloning https://github.com/borgbackup/borg.git (to master) to /tmp/pip-dqtglmg2-build
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.6 in /usr/lib/python3.4/site-packages (from borgbackup==0.23.0+85.g9d21e4a)
Installing collected packages: borgbackup
  Found existing installation: borgbackup 0.23.0
    Uninstalling borgbackup-0.23.0:
      Successfully uninstalled borgbackup-0.23.0
  Running setup.py install for borgbackup
Successfully installed borgbackup-0.23.0+85.g9d21e4a

tgh@thomast61p ~
$ rm -rf borg-test && mkdir borg-test && borg init file:///home/tgh/borg-test/test.borg                                             Initializing repository at "file:///home/tgh/borg-test/test.borg"
Encryption NOT enabled.
Use the "--encryption=repokey|keyfile|passphrase" to enable encryption.
Synchronizing chunks cache...
Rebuilding archive collection. Known: 0 Repo: 0 Unknown: 0
Merging collection into master chunks cache...
Done.

tgh@thomast61p ~
$ borg create file:///home/tgh/borg-test/test.borg::snapshot-$(date +'%Y%m%d-%H%M') /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Session'
borg: /cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs: [Errno 16] Device or resource busy: '/cygdrive/c/Users/tgh/AppData/Local/Google/Chrome/User Data/Default/Current Tabs'
Segmentation fault (core dumped)

tgh@thomast61p ~
$ cat python3.4m.exe.stackdump
Exception: STATUS_ACCESS_VIOLATION at eip=6D98195E
eax=FEA80008 ebx=8019E5A0 ecx=FEA81007 edx=73FC18F6 esi=801EECD0 edi=FEE61005
ebp=0119EFF9 esp=0028C0C0 program=C:\cygwin\bin\python3.4m.exe, pid 7616, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args

tgh@thomast61p ~
$ ls -l python3.4m.exe.stackdump
-rwxr-xr-x 1 tgh None 307 Jul 30 06:19 python3.4m.exe.stackdump

**Comment by ThomasWaldmann** [comment]
Quickest way to reproduce (latest borg from git master branch, cygwin64, win10):

borg init repo
borg create repo::archive /cygdrive/c/Users/NAME/AppData/Local/Google/Chrome/User Data/Default/Extension State/LOCK

This directly triggers the segfault.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/3be55bedd3a44206c5398931cdebdc7cda4b94f5 fixes the segfault, please check.

**Comment by tgharold** [comment]
3be55be definitely fixed the segfault
