### ISSUE TITLE
Standalone Binary: Segmentation fault on IPFire

### ISSUE THREAD

**Issue by davidak** [borgbackup/borg#1162]
I tried the Standalone Binary since we don't have Python 3.x on IPFire but it crashes.

Is that because of **libc 2.12**?

tested borg 1.0.2 on newest IPFire:

IPFire 2.19 (i586) - Core Update 102
Linux ipfire 3.14.65-ipfire-pae #1 SMP Thu May 12 01:17:19 GMT 2016 i686 GNU/Linux

borg-linux32 sha256: a83f75f09f23e6867807ba5983229a7220d4fe132b1cced9b7c44563408ce617

[ipfire-strace-borg-linux32.txt](https://github.com/borgbackup/borg/files/311689/ipfire-strace-borg-linux32.txt)

**Comment by ThomasWaldmann** [comment]
There's not enough information in the strace output.
Please do a full strace, edit your top post and attach it as strace.txt.

I shortly tried the binary on centos6 (which also has glibc 2.12) and it worked there.

**Comment by davidak** [comment]
What do you mean with 'full strace'? How should the command look like?

**Comment by hansmi** [comment]
> What do you mean with 'full strace'?

Without `-eopen`, i.e. with all syscalls.

**Comment by textshell** [comment]
does it output anything before crashing?
can you attach the log from strace -fy -o borgcrash.log ./borg-linux32
even better would be a stack trace with gdb, but i’m not sure there is a reasonable way to get gdb installed. another option would be to enabled coredumps and look at the coredump on your PC (again using gdb).

**Comment by davidak** [comment]
>does it output anything before crashing?

no


[borgcrash.txt](https://github.com/borgbackup/borg/files/315356/borgcrash.txt)

```
[pid  5855] open("/tmp/_MEIkKdAGb/_ctypes.cpython-35m-i386-linux-gnu.so", O_RDONLY) = 3
[pid  5855] read(3</tmp/_MEIkKdAGb/_ctypes.cpython-35m-i386-linux-gnu.so>, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0\3\0\1\0\0\0\300O\0\0004\0\0\0"..., 512) = 512
[pid  5855] fstat64(3</tmp/_MEIkKdAGb/_ctypes.cpython-35m-i386-linux-gnu.so>, {st_mode=S_IFREG|0700, st_size=438093, ...}) = 0
[pid  5855] mmap2(NULL, 124480, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3</tmp/_MEIkKdAGb/_ctypes.cpython-35m-i386-linux-gnu.so>, 0) = 0xac6ec000
[pid  5855] mmap2(0xac708000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3</tmp/_MEIkKdAGb/_ctypes.cpython-35m-i386-linux-gnu.so>, 0x1c) = 0xac708000
[pid  5855] mprotect(0xacd24000, 3824, PROT_READ|PROT_WRITE) = -1 EACCES (Permission denied)
[pid  5855] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0xacd24eec} ---
[pid  5855] +++ killed by SIGSEGV (core dumped) +++
<... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV && WCOREDUMP(s)}], 0, NULL) = 5855
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=5855, si_status=SIGSEGV, si_utime=9, si_stime=1} ---
rt_sigaction(SIGINT, {SIG_DFL, [INT], SA_RESTART}, {0x804bc70, [INT], SA_RESTART}, 8) = 0
rt_sigaction(SIGKILL, {SIG_DFL, [KILL], SA_RESTART}, {0x804bc70, [INT], SA_RESTART}, 8) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGTERM, {SIG_DFL, [TERM], SA_RESTART}, {0x804bc70, [TERM], SA_RESTART}, 8) = 0
tgkill(5854, 5854, SIGSEGV)             = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_TKILL, si_pid=5854, si_uid=0} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault
```

i have this core dump, but no gdb: [core.zip](https://github.com/borgbackup/borg/files/315360/core.zip)

**Comment by verygreen** [comment]
Do you mount /tmp as noexec by any chance?

[root@somebox ~]# mount none /tmp/ -t tmpfs -o noexec
[root@somebox ~]# /usr/local/bin/borg 
/usr/local/bin/borg: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted

**Comment by verygreen** [comment]
Also,
```
[pid  5855] mprotect(0xacd24000, 4096, PROT_READ) = 0
...
[pid  5855] mprotect(0xacd24000, 3824, PROT_READ|PROT_WRITE) = -1 EACCES (Permission denied)
```
This looks strange. 3284 is less than a page size and I think mprotect needs a page-ligned addresses/sizes.
Also I don't see anywhere this address being actually mmapped

Or perhaps there's something that precludes the region to get more permissive access once it was reduced to just read (related to some security model or whatever), this is certainly not unheard of.

**Comment by davidak** [comment]
>Do you mount /tmp as noexec by any chance?

No, i also tested in /root/

IPFire is a hardened Linux-Distribution. Maybe that causes some errors.

**Comment by verygreen** [comment]
It does not matter where the binary is, if you check the strace, it unpacks the internal content into /tmp/ and then runs from there.

**Comment by davidak** [comment]
>It does not matter where the binary is

yes, i tested with the following command that i found in some other issue:

`TEMP=/root strace ./borg-linux32`

**Comment by verygreen** [comment]
Ok, just making sure since in the strace we can see:
`[pid  5855] mmap2(0xac708000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3</tmp/_MEIkKdAGb/_ctypes.cpython-35m-i386-linux-gnu.so>, 0x1c) = 0xac708000`
(note the /tmp/ path).

**Comment by ThomasWaldmann** [comment]
@davidak any news? see last comment of @verygreen.

Also, if the single-file bootloader's unpacking to /tmp makes an issue:

You can do that once (on a system where it works) - just run `borg init somerepopath` and do not enter a password. While borg is waiting for the password, see the new `/tmp/_ME*` directory and just copy it to somewhere else. In future, you can just run borg from the copied directory.

**Comment by davidak** [comment]
@ThomasWaldmann thanks. how do i start from the copied /tmp/_ME*?

**Comment by ThomasWaldmann** [comment]
ehrm. I though I had seen some borg executable in there at some time. But it seems this has changed, maybe with some pyinstaller version. One can create "directory" instead of "single-file" output with pyinstaller though (but I did not, because I thought the unpacked dir is the same ...).

**Comment by davidak** [comment]
```
ls tmp/_MEIPPYPn5/
array.cpython-35m-i386-linux-gnu.so                _heapq.cpython-35m-i386-linux-gnu.so  _md5.cpython-35m-i386-linux-gnu.so
base_library.zip                                   include                               msgpack._packer.cpython-35m-i386-linux-gnu.so
binascii.cpython-35m-i386-linux-gnu.so             _json.cpython-35m-i386-linux-gnu.so   msgpack._unpacker.cpython-35m-i386-linux-gnu.so
_bisect.cpython-35m-i386-linux-gnu.so              lib                                   _multibytecodec.cpython-35m-i386-linux-gnu.so
borg.chunker.cpython-35m-i386-linux-gnu.so         libacl.so.1                           _opcode.cpython-35m-i386-linux-gnu.so
borg.compress.cpython-35m-i386-linux-gnu.so        libattr.so.1                          _pickle.cpython-35m-i386-linux-gnu.so
borg.crypto.cpython-35m-i386-linux-gnu.so          libbz2.so.1.0                         _posixsubprocess.cpython-35m-i386-linux-gnu.so
borg.hashindex.cpython-35m-i386-linux-gnu.so       libcrypto.so.1.0.0                    pyexpat.cpython-35m-i386-linux-gnu.so
borg.platform_linux.cpython-35m-i386-linux-gnu.so  libfuse.so.2                          _random.cpython-35m-i386-linux-gnu.so
_bz2.cpython-35m-i386-linux-gnu.so                 libgcc_s.so.1                         readline.cpython-35m-i386-linux-gnu.so
_codecs_cn.cpython-35m-i386-linux-gnu.so           liblz4.so.1                           resource.cpython-35m-i386-linux-gnu.so
_codecs_hk.cpython-35m-i386-linux-gnu.so           liblzma.so.5                          select.cpython-35m-i386-linux-gnu.so
_codecs_iso2022.cpython-35m-i386-linux-gnu.so      libpython3.5m.so.1.0                  _sha1.cpython-35m-i386-linux-gnu.so
_codecs_jp.cpython-35m-i386-linux-gnu.so           libreadline.so.6                      _sha256.cpython-35m-i386-linux-gnu.so
_codecs_kr.cpython-35m-i386-linux-gnu.so           libssl.so.1.0.0                       _sha512.cpython-35m-i386-linux-gnu.so
_codecs_tw.cpython-35m-i386-linux-gnu.so           libstdc++.so.6                        _socket.cpython-35m-i386-linux-gnu.so
_ctypes.cpython-35m-i386-linux-gnu.so              libtinfo.so.5                         _ssl.cpython-35m-i386-linux-gnu.so
_datetime.cpython-35m-i386-linux-gnu.so            libz.so.1                             _struct.cpython-35m-i386-linux-gnu.so
fcntl.cpython-35m-i386-linux-gnu.so                llfuse.cpython-35m-i386-linux-gnu.so  termios.cpython-35m-i386-linux-gnu.so
grp.cpython-35m-i386-linux-gnu.so                  _lzma.cpython-35m-i386-linux-gnu.so   unicodedata.cpython-35m-i386-linux-gnu.so
_hashlib.cpython-35m-i386-linux-gnu.so             math.cpython-35m-i386-linux-gnu.so    zlib.cpython-35m-i386-linux-gnu.so
```

at this time it is not important to me anymore to get this running. i have done a simple backup with rsync. if you have any idea what i could try next, i can help debug it. maybe it's helpful for someone else.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/1162#issuecomment-226084290 that would be something to debug further. maybe create a /root/tmp dir (with same mode as you see on /tmp) and use that for TEMP=/root/tmp.

**Comment by davidak** [comment]
@ThomasWaldmann he only noticed that i used /tmp instead of /root there. i don't see something i can do.

i extracted the copy from the system where it worked to /root/tmp/_MEIPPYPn5 but when i run `TEMP=/root/tmp/ strace ./borg-linux32` it get's extracted to a different directory:

```
[root@ipfire ~]# ll tmp/
total 12
drwx------ 4 root root 4096 Jul  9 02:01 _MEIPPYPn5
drwx------ 4 root root 4096 Jul  9 19:14 _MEIvjIdHY
drwx------ 4 root root 4096 Jul  9 19:15 _MEIw1EtfA
```

**Comment by ThomasWaldmann** [comment]
@davidak the single-file binary always extracts itself and the loads stuff from the temporary directory.

The strange thing is that you set TEMP to somewhere else, but it still used /tmp!?

**Comment by davidak** [comment]
>but it still used /tmp!?

no, i tried both. the problem is the segfault.

```
TEMP=/root/tmp/ strace ./borg-linux32
[...]
mkdir("/root/tmp/_MEIaGMqqr", 0700)     = 0
```
full log: https://davidak.basecom.de/paste/?0a312e7d7c357927#lrIgK3ET9yhwhAnmlTxonwMy01geU81F04f5CuH+shg=

**Comment by ThomasWaldmann** [comment]
Maybe it would be worthwhile to re-check this with current ipfire and current borg (there will be soon a 1.0.9rc1 release).

**Comment by davidak** [comment]
I downloaded the new Release 1.0.0rc1 but on an old IPFire.

Still Segmentation fault.

I will test it on a current IPFire...

**Comment by ThomasWaldmann** [comment]
@davidak please use 1.0.9rc1 (not the topmost item).

**Comment by davidak** [comment]
The newer versions of IPFire have a x86_64 Kernel by default, but still libc 2.12.

At home i have the newest IPFire 2.19 (x86_64) - Core Update 107.

```
[root@ipfire ~]# ./borg-linux64 debug-info
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
Platform: Linux ipfire 3.14.79-ipfire #1 SMP Fri Nov 4 21:16:26 GMT 2016 x86_64 
Linux:   
Borg: 1.0.9rc1  Python: CPython 3.5.2
PID: 2797  CWD: /root
sys.argv: ['./borg-linux64', 'debug-info']
SSH_ORIGINAL_COMMAND: None
```

that looks good for now, only a `undefined symbol: rl_signal_event_hook` error.

```
[root@ipfire ~]# ./borg-linux64
usage: borg-linux64 [-h] [-V] <command> ...

Borg - Deduplicated Backups

[...]
```

I havn't tested a backup yet.

**Comment by ThomasWaldmann** [comment]
rl_signal_event_hook seems related to readline (which is used by python interpreter).

**Comment by ThomasWaldmann** [comment]
Maybe it is worth re-testing this after 1.0.10rc1 gets released (soon).
The binary will have a fixed bootloader and a more recent python 3.5.3.
Not sure if it helps...

**Comment by ThomasWaldmann** [comment]
@davidak can you try the "pyi321" binary of latest release, whether it behaves differently?

**Comment by davidak** [comment]
@ThomasWaldmann yes. i used `borg-linux64-pyi321-debug` of Release 1.0.10:

```
[root@ipfire ~]# ./borg-linux64-pyi321-debug debug-info
PyInstaller Bootloader 3.x
LOADER: executable is /root/borg-linux64-pyi321-debug
LOADER: homepath is /root
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /root/borg-linux64-pyi321-debug
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /tmp/_MEIeGsHLl
LOADER: LD_LIBRARY_PATH=/tmp/_MEIeGsHLl
PyInstaller Bootloader 3.x
LOADER: executable is /root/borg-linux64-pyi321-debug
LOADER: homepath is /root
LOADER: _MEIPASS2 is /tmp/_MEIeGsHLl
LOADER: archivename is /root/borg-linux64-pyi321-debug
LOADER: Already in the child - running user's code.
LOADER: Python library: /tmp/_MEIeGsHLl/libpython3.5m.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is /tmp/_MEIeGsHLl/base_library.zip:/tmp/_MEIeGsHLl
LOADER: sys.prefix is /tmp/_MEIeGsHLl
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /tmp/_MEIeGsHLl/base_library.zip:/tmp/_MEIeGsHLl
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running __main__.py
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
Platform: Linux ipfire 3.14.79-ipfire #1 SMP Fri Nov 4 21:16:26 GMT 2016 x86_64
Linux:
Borg: 1.0.10  Python: CPython 3.5.3
PID: 18479  CWD: /root
sys.argv: ['./borg-linux64-pyi321-debug', 'debug-info']
SSH_ORIGINAL_COMMAND: None

LOADER: Back to parent (RC: 0)
LOADER: Doing cleanup
LOADER: Freeing archive status for /root/borg-linux64-pyi321-debug
```

still same error.

**Comment by ThomasWaldmann** [comment]
Pity. Well, maybe the ipfire guys should upgrade their stuff from stoneage. :-)

**Comment by ThomasWaldmann** [comment]
I'm closing this, it doesn't look like we can fix this from our side.
Maybe file a ticket in the ipfire issue tracker.

**Comment by davidak** [comment]
thanks for investigating.

bugreport here for everyone interested in the progress: https://bugzilla.ipfire.org/show_bug.cgi?id=11313
