### ISSUE TITLE
Trailing and leading whitespace and control characters are allowed as archive names

### ISSUE THREAD

**Issue by Abogical** [borgbackup/borg#1166]
It is possible for borg archive names to have trailing and leading whitespace and control characters.

```bash
$ borg create "/path/to/repo::archive       " /files/to/backup
$ borg create "/path/to/repo::   archive" /files/to/backup
$ borg create "/path/to/repo::new
> line" /files/to/backup
$ borg create /path/to/repo::$'\1' /files/to/backup
$ borg list /path/to/repo
archive                              Tue, 2016-06-14 02:10:48
   archive                           Tue, 2016-06-14 02:11:20
new
line                             Tue, 2016-06-14 02:11:23
                                    Tue, 2016-06-14 02:12:30
```

Obviously, this creates several issues, escpecially trailing whitespaces.

Trailing whitespace
--
Due to `borg list`'s format **It is impossible to know whether an archive name has trailing spaces, let alone how many spaces it has**.

For example let's create an archive with a normal name.
```bash
$ borg create /path/to/repo::archive /files/to/backup
```
Then create an archive with 1 space after the name, and another with 3 spaces after the name.
```bash
$ borg create "/path/to/repo::archive " /files/to/backup
$ borg create "/path/to/repo::archive   " /files/to/backup
```
Listing the repository gives an awkward result.
```bash
$ borg list /path/to/repo
archive                              Tue, 2016-06-14 03:20:01
archive                              Tue, 2016-06-14 03:24:06
archive                              Tue, 2016-06-14 03:28:13
```
The following problems occur:
- All archives appeares to have the same name, which is impossible.
- It is impossible to know that there are trailing whitespace characters.
- It is impossible to know how many trailing spaces there are.

Control characters and leading whitespaces
--
Control characters and leading whitespaces may make `borg list` harder to read and harder to be parsed by scripts.

Possible solutions
--
- Reject control characters and leading and trailing whitespaces when creating a new archive.
- Truncate leading and trailing whitespace when creating a new archive.
- Change format of `borg list`, or allow to change it via `--list-format`.

*Note: times in the shell's output are not actual times.*

**Comment by enkore** [comment]
> - It is impossible to know that there are trailing whitespace characters.
> - It is impossible to know how many trailing spaces there are.

borg-info gives the verbatim name with no added formatting, so you'd be able to get it from there.

**Comment by Abogical** [comment]
@enkore `borg info` is for a specific archive, The problem comes when listing all archive names in a repository, which is done via `borg list`

**Comment by Abogical** [comment]
@enkore Trial and error may work though, still it's silly for borg to allow such a thing, users and scripts would not expect that this would be possible.

**Comment by Abogical** [comment]
@enkore `--short` may also reveal the trailing whitespaces but does not handle new lines well.

**Comment by ThomasWaldmann** [comment]
This is a bit of a crap-in crap-out problem.

Maybe just do not feed crap (strange archive names) into borg?

**Comment by Abogical** [comment]
Alright then, if you do not consider this as a bug, then you can close this issue. Otherwise you can review my pull request (#1174)

**Comment by ThomasWaldmann** [comment]
Well, it is somehow a solution for a problem I usually do not have.

Why are you having crap characters in archive names? Can you tell more about the use case?

**Comment by Abogical** [comment]
I agree that this is indeed a trivial problem.

In my case, I'm attempting to make a GUI for borg that would open existing repositories and parse `borg list`, It would list other people's repositories. The problem is I can't guarantee it would work 100% of the time, as there could be some crazy guy out there who might have a repository which uses this crap.

In the end it's a design choice that it's up to you:
- Do you want to have the linux filesystem wild west, where you can allow all characters except NULL and slash, and see that this makes no problem for you in the future of this project, then that is fine. Decline the pull request and I'll work on the third solution provided, where I apply `--list-format` when listing repositories. Just be careful when dealing with these archive names as they may break repositories.
- Do you want to remove the headache and just it ban it all together, so you can guarantee correct formatting when printing archive names and that archive names won't break repositories in some awkward way, then that is fine. I'll still work on the third solution though as it would make parsing `borg list` way easier.

**Comment by Abogical** [comment]
I've applied the third solution (#1179). Explanation of how this will fix the issue is in the PR. If this PR is merged, you can close the issue.
