### ISSUE TITLE
Please consider adding a --mode option to borg init.

### ISSUE THREAD

**Issue by Zugschlus** [borgbackup/borg#117]
Hi,

borgbackup uses the normal system umask to create a repository, which might result in a world-readable repository.

Please consider giving borg init a --mode option where one can control with which mode a new repository is created, with the mode being recorded in repository metadata and honored for future runs automatically.

Greetings
Marc

**Comment by ThomasWaldmann** [comment]
Sounds like this could be easily done in the backup script, at least if borg is used locally.
Have to check remote repos, though, where it might not be that easy.

**Comment by Zugschlus** [comment]
yes, my main use is remote.

**Comment by ThomasWaldmann** [comment]
can you test whether a umask command in .profile or .bashrc of the repo's ssh user works?

**Comment by Zugschlus** [comment]
I can and will, but that would be a system-wide setting while it might be desireable to have this set per repository. Additionally, having a remote job rely on local shell init files is _mucho_ ugly. I have never seen this in a serious tool.

**Comment by ThomasWaldmann** [comment]
can you explain the usecase for per repository umask setting (and not just per user)?

shell init files might not work btw. because ssh might directly execute the borg binary, not the shell (at least another user mentioned this in another ticket).

**Comment by Zugschlus** [comment]
this is far fetched, but imagine one repository being a regular backup, and another being a master image used to install new systems. the latter does not require privacy and might be used by many people to install.

**Comment by ThomasWaldmann** [comment]
hint: implement this with a default (secure) umask of 077. if someone wants to create files with a less secure mode, he will need to change the default.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/9f1d92c993a5c2219f8b9e6b9b2b8474cb0b630b fixed.
