### ISSUE TITLE
please consider adding the possibility to back up an entire block device

### ISSUE THREAD

**Issue by Zugschlus** [borgbackup/borg#118]
Hi,

I have a number of Windows machines running as virtual machines on my Linux host. The virtual hard disks are in LVM LVs where the raw device is directly connected to the virtual machine. There is no Linux file system and no image files that can be backed up.

I would be nice if borg create ssh://remotehost/path/to/repository /dev/mapper/vg-lv would actually back up the block device's contents instead of just the device node. Combined with the deduplication feature, it would be a grossly space saving method to back up VMs.

Greetings
Marc

**Comment by oderwat** [comment]
This may help: https://github.com/vasi/diskfile

**Comment by ThomasWaldmann** [comment]
@Zugschlus you can just use: dd if=/dev/whatever | borg create repo::mydisk -

**Comment by Zugschlus** [comment]
That's cute. I was not aware that borg would also happily back up standard input. Will deduplication work with that?

**Comment by Zugschlus** [comment]
It will. How nice. Please document this use.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/729cc4d82d9597fdf56a81fc8a5bcd6228850fce documented

also, this is also somehow duplicate to #79 thus closing this one.

**Comment by steabert** [comment]
I couldn't find anywhere in the documentation how to extract an archive that was created by using:
`dd if=/dev/xxx | borg create repo::mydisk -`
The extract command mentions that something is always extracted to the current directory.
This seemed the appropriate place to ask, but maybe this should be a new issue?
