### ISSUE TITLE
borgbackup build failure when using OpenSSL 1.1.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1187]
https://groups.google.com/d/msg/linux.debian.devel/53fq9S-Qpp4/V_0pPtdzBQAJ

**Comment by ThomasWaldmann** [comment]
Note: as some developer on the linked mailing list thread has noticed, just making an application work with OpenSSL 1.1.0 is often not sufficient if one still wants it to work with 1.0.1 and 1.0.2 also.

**Comment by enkore** [comment]
Guess we'll need to detect OpenSSL version in setup.py and generate a little header file aliasing changed names -- Cython has no "ifdef" like construct, at least not that I'm aware...

**Comment by ThomasWaldmann** [comment]
https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/borgbackup_1.0.3-1_amd64-20160529-1408

**Comment by enkore** [comment]
Probably one of the (many) structures that are now opaque in 1.1 and require accessors.

**Comment by ThomasWaldmann** [comment]
See this PR which is schedule for borg 1.2:
https://github.com/borgbackup/borg/pull/1034/files#diff-85ee6ebe1cdcfd4a4699c3913d519b27L104

When this is merged, we do not access into the OpenSSL ctx any more (to read the current value of ctx.iv), but just compute the next iv from the previous iv and, if needed, the amount of data.

This could be done in a similar way in borg 1.0 and 1.1 also.

**Comment by ThomasWaldmann** [comment]
Related: what is the best / easiest way to build / test borg with OpenSSL 1.1 without disturbing any other openssl using software on the system?

**Comment by LocutusOfBorg** [comment]
>Related: what is the best / easiest way to build / test borg with OpenSSL 1.1 without disturbing any other openssl using software on the system?

```
pbuilder-dist experimental create
pbuilder-dist experimental login
do your checks here :)
```

**Comment by ThomasWaldmann** [comment]
Note: once openssl 1.1 is the test environment, attic of course does not build/install any more and test environment setup fails hard.

**Comment by ThomasWaldmann** [comment]
I put this into 1.0.4 milestone, so existing debian/ubuntu packages will successfully build and run on openssl 1.0.x and 1.1.x.

**Comment by LocutusOfBorg** [comment]
+1

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg there is a slight remaining issue:

attic won't get fixed for openssl 1.1 and we have tests that want attic (but are automatically skipped if no attic is installed). I'ld like to keep the attic migration tests as long as openssl 1.0.x is the usual thing and as long as people migrate from attic to borg.

Removing attic from the tests (in a openssl 1.1 environment) currently requires something like:
```
echo "# nope" > requirements.d/attic.txt
```
Is that ok like that? Better ideas?

**Comment by LocutusOfBorg** [comment]
we don't install attic during run of testsuite
https://buildd.debian.org/status/fetch.php?pkg=borgbackup&arch=amd64&ver=1.0.3-1&stamp=1464002095
so, we fallback in the "no attic installed" case.

It is ok to have a broken attic, it isn't part of the next Debian stable release FWIW
and it is ok evenutally to have that patch

but a question: we have some disabled test with this keyword
export PYBUILD_TEST_ARGS=\
        -k 'not benchmark and not fuse_mount' \
        --pyargs borg.testsuite

so, in case can't we just adapt a little bit that variable?

**Comment by ThomasWaldmann** [comment]
the tests are not the problem. but in tox.ini, we usually install attic and if that breaks...

**Comment by LocutusOfBorg** [comment]
but the tox.ini is not used in Debian builds... is it?

BTW if you provide me a patch, I can fix attic too.
(or ask ftpmasters to remove it)

let me know, I want it fixed, or out, but I don't know which one is better

**Comment by ThomasWaldmann** [comment]
The patch for attic would be similar as the changeset for borg. But considering all the other fixes that are missing in attic and that its development has halted, it is somehow questionable whether we should keep it alive.

In future, we could still run our unit tests (that want attic) via tox / pip (as long as it is available from there) on some system that still has openssl 1.0.x - considering support length of ubuntu lts and centos for a rather long time.

**Comment by ThomasWaldmann** [comment]
Just in case attic gets removed from a future Debian: is there some good way to point its previous users to borgbackup on upgrade?

**Comment by LocutusOfBorg** [comment]
I could break+replace attic to force them torwards borgbackup, but this might be a little bit unfair for the other maintainer.
An alternative might be to remove attic, and add a "Provides: attic" on borgbackup control file

**Comment by ThomasWaldmann** [comment]
The problem might be to get people aware about the change and the needed manual intervention (running "borg migrate", fixing scripts).

**Comment by LocutusOfBorg** [comment]
so, I'm not sure how we can notify them :(

**Comment by LocutusOfBorg** [comment]
BTW people seem to already know how to migrate, according to popcon
https://qa.debian.org/popcon.php?package=borgbackup
https://qa.debian.org/popcon.php?package=attic

it already has the same number of users

**Comment by mansoorcheema** [comment]
how to access openssl 1.1 opaque structures (public in openssl 1.0)?

**Comment by enkore** [comment]
using accessor functions. some of them were already there, some were not.

So instead of `cipher_ctx->iv_len` you'd use `EVP_CIPHER_iv_length(cipher_ctx)`. https://www.openssl.org/docs/manmaster/man3/EVP_CIPHER_CTX_new.html

To be both 1.0 and 1.1 compatible you'll usually need extra code. Example: https://github.com/borgbackup/borg/pull/1034/files#diff-1ae52fe303138861ca3a43717a17b81aR1

**Comment by ThomasWaldmann** [comment]
@mansoorcheema why are you asking? is it related to borg?
