### ISSUE TITLE
borg create --exclude does not handle directories with spaces in the name correctly

### ISSUE THREAD

**Issue by jrmiller82** [borgbackup/borg#1189]
`borg create --exclude '~/Foo\ Bar' backup::01 ~/`

Does not exclude directory 'Foo Bar' but if I do: 

`mv ./Foo\ Bar Foo-Bar`

and then 

`borg create --exclude '~/Foo-Bar' backup::01 ~/`

It excludes the directory. 

Yes, I know it's bad practice to have spaces in names in directories; but, some of the users I'm trying to develop a borg backup solution for use OSX and they put alot of spaces in file names and directories.

**Comment by enkore** [comment]
Pretty sure that's escaped wrong.

`--exclude '~/Foo Bar'`

**Comment by jrmiller82** [comment]
I used the escaping from zsh... ahhh... maybe the `'   '` means I don't have to escape with `\ `

**Comment by ThomasWaldmann** [comment]
Did it work?

**Comment by jrmiller82** [comment]
Sorry. Haven't had enough free time to make a test case.

**Comment by ThomasWaldmann** [comment]
I assume this is a escaping issue and closing this now.

Please reopen if the above suggestions did not fix your issue.
