### ISSUE TITLE
Please document that deduplication works even inside a file

### ISSUE THREAD

**Issue by Zugschlus** [borgbackup/borg#119]
Hi,

from expeiments with big files with random contents[1], I have learned that deduplication even works within a file, even when file contents is shifted inside the file. This is a good thing!

Please document this, as this is a strong point for using borgbackup even for big blobs of data that are only changing in small places, such as VM images.

Greetings
Marc

[1] create 4 GB of random ASCII file, back it up, change a single character, back it up again, look at repository size

**Comment by ThomasWaldmann** [comment]
yes, good point, that's not clearly said yet.

you can also move lots of files around (rename them, move to other directories) and it will still recognize the duplication between the files at new location and old location.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/300c7351e70e487775967c464751111320f8225c fixed
