### ISSUE TITLE
Permission issue on OS X - brew cask installation

### ISSUE THREAD

**Issue by ctourner** [borgbackup/borg#1190]
When installing borg from `brew cask`, the borg binary is installed with permissions 0744. As a result, other users on the system can't use borg.

OS X: 10.11.5, borg: 1.0.3

**Comment by enkore** [comment]
Sounds more like a packaging problem? If so, please report to cask: https://github.com/caskroom/homebrew-cask

https://github.com/caskroom/homebrew-cask/blob/master/Casks/borgbackup.rb

**Comment by ctourner** [comment]
I reported this issue to homebrew-cask.
Closing for now.
