### ISSUE TITLE
where is "borg diff" in latest 1.0.3 ?

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#1192]
@anarcat  @ThomasWaldmann 
In #740 we got some good code that was later merged and gave the borg diff functionality.
1. Is it possible to do inter-archive diff right now? If yes how ?
2. will we ever have a "borg diff" cmd?
PS. I can see some git commits mention "diff" and their git diffs concern a python func named "compare_items", so what borg command uses that?

Thanks in advance.  Background story: Last day I needed a diff and after getting mad at 'borg mount' which is painfully slow, I went for 2 hour restore + bash's diff into a file so I inspected the diff and was finally happy... But this is/was such a time and hdd space waste...

**Comment by enkore** [comment]
This is a feature which was merged into master and will be released with Borg 1.1.

Borg 1.0 is released and therefore only receives bug fixes via the 1.0-maint branch and no new features.
