### ISSUE TITLE
Detection and solving of stuck locks

### ISSUE THREAD

**Issue by verygreen** [borgbackup/borg#1196]
It is desirable to automatically detect and solve stuck locks for a process that's no longer running in order to keep backups as hassle-free and maintenance free as possible.

lock file already holds a PID of the process that's holding it which should help us here.
Hostname of the holding node also is part of the lock filename.

So if a lock file is detected, the hostname part matches ours and the pid does not really exist in the system anymore, it should be pretty easy do declare such a lock as stale and kill it.

I guess a special care needs to be taken to exclude generic names like localhost and localhost.localnet too.

**Comment by ThomasWaldmann** [comment]
"server", "pc", ...

**Comment by enkore** [comment]
I think this was discussed a few times now across a few tickets with the bottom-line always being that identical host names happen more often than we'd like and that also some people access their repos over network file systems where this approach doesn't work (doesn't fail-safe) at all. I think last time I suggested that it may be implemented, but only as a clearly labelled opt-in.

**Comment by enkore** [comment]
Closing as dupicate of #562
