### ISSUE TITLE
doing checkpoints while a file is being processed

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1198]
borg currently only does checkpoints between files (after one file is finished, before next one is started).

this is a problem if your backup contains a huge file and your remote repository connection breaks down frequently (and in less time than needed to complete that file).

of course, extracting such huge files over a unreliable connection might be a similar problem.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/35419244-doing-checkpoints-while-a-file-is-being-processed)

**Comment by ThomasWaldmann** [comment]
Status Quo
---------------

Currently, a checkpoint archive is a valid (but partial) archive. Meaning that all files in it are complete, but it does not have all files yet. The function of such a checkpoint archive is to keep references to the already stored chunks and also to do finish a repository transaction ("commit" these changes).

Later, when another try of that backup job is performed, this will be a normal, full backup - it will just be faster because some chunks (data and metadata) are already there and don't need to get retransmitted again.

Future?
----------

We could modify the checkpoint archive properties slightly so that some of its files might be incomplete (usually the last file). The metadata would then tell the (original) file is of size S, but the chunks would not sum up to that size. The beginning of the file up to some offset s (s < S) would be valid.

Implementation notes
-----------------------------

As there is technically no "resume" happening, this might be quite easy to implement.

**Comment by dragetd** [comment]
What would be the semantics of extracting/listing such incomplete files? Or mounting this checkpoit-repository?
The user should not be able to access incomplete (i.e. corrupted) data through any regular way.

**Comment by ThomasWaldmann** [comment]
If you are extracting a ".checkpoint" archive, you then would know beforehands that the last file(s) might be truncated. One would only extract a ".checkpoint" archive in a situation when there is no normal archive, which means that you didn't have a "good" backup anyways. The data extracted would be valid up to the point of truncation.

**Comment by dragetd** [comment]
But how would he know what the last file was?
Imagine I am backing up 50 VM disk images of various bigger sizes. Close to the end of the backup the PC goes up in flames.
The .checkpoint-archive on the remote shows me it has 49 disk images. Currently I could be certain: I have 9 valid disk images and one is lost.
In the future I would have 50 disk images, but one is corrupted. Which one? I'd need to test one by one.

I know, this example is a bit far fetched and I see the advantage 'I will have the incomplete 50th disk images and still can extract xx% of the data from it'. Just thought I'd bring that example up.

Thinking about it, the advantage might outweigh the downside of my fictional scenario, rrue…

**Comment by enkore** [comment]
When writing the checkpoint the incomplete file could get an extra suffix added that says so. Of course, that has the usual issues of any in-band signalling, but I don't think they're important here.

**Comment by ThomasWaldmann** [comment]
Good idea. ".part" comes to mind.
