### ISSUE TITLE
please consider using asymmetric cryptography

### ISSUE THREAD

**Issue by Zugschlus** [borgbackup/borg#120]
Hi,

it would probably be nice to have the machine to be backed up encrypt the backups without it being able to decrypt. That would be possible if the cryptography would be done with an asymmetric cryptosystem.

Greetings
Marc

P.S.: Please consider this a wishlist request, please feel free to say "we wont do this"

**Comment by ThomasWaldmann** [comment]
the repo is basically a key/value store. but while a lot of stuff only gets written/appended while doing a backup, some stuff is also read from the repo (e.g. the repo manifest). thus, we need a more detailled plan first.

**Comment by ThomasWaldmann** [comment]
btw, this is way too vague and I'll close this soon due to that.
