### ISSUE TITLE
Cannot list repo contents when disk is full

### ISSUE THREAD

**Issue by walkertraylor** [borgbackup/borg#1203]
I am unable to list repo contents after reaching the hard quota limit on my account.   Presumably a user would want to delete an archive to free up space, but is unable to determine which archives are suitable for deletion without the ability to execute the list command.

Traceback:

```
 user@hostname$ borg list $BORG_REPO
Remote: Borg 0.29.0: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/locking.py", line 134, in acquire
Remote: OSError: [Errno 69] Disc quota exceeded: '####OBFUSCATED#####/lock.exclusive'
Remote:
Remote: During handling of the above exception, another exception occurred:
Remote:
Remote: Traceback (most recent call last):
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/remote.py", line 96, in serve
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/remote.py", line 121, in open
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/repository.py", line 63, in __init__
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/repository.py", line 141, in open
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/locking.py", line 267, in acquire
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/locking.py", line 118, in __enter__
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/locking.py", line 142, in acquire
Remote: borg.locking.LockFailed: ('####OBFUSCATED#####/lock.exclusive', "[Errno 69] Disc quota exceeded: '####OBFUSCATED#####/lock.exclusive'")
Remote: Platform: FreeBSD ####OBFUSCATED##### 10.2-RELEASE FreeBSD 10.2-RELEASE #0: Fri Oct 30 07:01:38 MDT 2015     root@####OBFUSCATED#####:/usr/src/sys/amd64/compile/kernel.10_1amd64.conf amd64
Remote: Python: CPython 3.4.3
Remote:
Remote Exception (see remote log for the traceback)
Platform: Darwin love 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64 i386
Borg: 1.0.3  Python: CPython 3.5.1
PID: 26613  CWD: /Users/wtraylor
sys.argv: ['borg', 'list', '####OBFUSCATED#####backup/macbookpro']
SSH_ORIGINAL_COMMAND: None
```

(edited by enkore: code tags)

**Comment by enkore** [comment]
This is [documented](http://borgbackup.readthedocs.io/en/stable/quickstart.html#important-note-about-free-space) but obviously undesirable behaviour.

Related/Duplicate-y are e.g. #1035 and others, since the technical reason we ATM can't do it is the same.

**Comment by ThomasWaldmann** [comment]
can you solve your current problem by getting a higher quota or do you need a workaround?

**Comment by walkertraylor** [comment]
I have requested a higher quotes, but I prefer a workaround because the request will take many hours, and I foresee this happening again as I don't know exactly how large my total backup will be or how much working space is required.

**Comment by ThomasWaldmann** [comment]
The docs have some workarounds you can take so you always have some free space. So e.g. if you have 500GB, creating a 5GB dummy file as a emergency reserve is a good idea. Or having some monitoring, like putting the current usage and quota in the backup log file.

On #borgbackup we discuss some workaround... hold on...

**Comment by ThomasWaldmann** [comment]
Is the repo "append-only"? See repo/config.

**Comment by walkertraylor** [comment]
no

**Comment by ThomasWaldmann** [comment]
@walkertraylor do you have logs of the last borg operation that filled up the disk?

**Comment by walkertraylor** [comment]
No, but I can give some more background information.  

I am using borgmatic backup script, with high verbosity output. 
This is the first large backup I am doing, after various successful test backups.
After the test backups, I cleared everything out and created a fresh key, passphrase, and initialized a fresh repo using the borg command as recommended by borgmatic.
I began the borgmatic backup using high verbosity on the command line, which is a direct output of the borg high verbosity switch.  
(Thanks for Dan Helfman for fixing borgmatic to support this: 
https://tree.taiga.io/project/witten-borgmatic/issue/21)
 

Since starting the backup a week ago, the backup fails whenever my internet connection drops (nightly.)
When this happens I have to use "borg break-lock" to be able to resume the backup.
The backup seems to resume just fine, and quickly compares existing files.

I haven't seen anything standout unusual in the output. I see the lists of files being compared, updated or added, with the occassional traceback when the connection drops, and a traceback about the lockfile when I attempt to resume. (Which I clear with break-lock then resume.) 

The files being backed up are changing as they are local files which I am using them during the backup process.

I have followed the instructions to the letter with no special configuration other than using a key with optional passphrase.

Since I have not yet completed one full backup, I don't know how much space is being occupied by working space.  I suspect I must be near 

I may be legitimately using the entire space available.  I am trying to back up 50GB of data.  My hard quota is 55GB.  (I have put in the order to raise it.)   I imaging that some of my large files may have changed since I started the upload and those blocks could be taking up the extra space.  Also I changed my "excludes" list in borgmatic configuration mid-backup. I don't know how borgmatic deals with that - if it deletes the old files already backedup or if it waits until the entire backup is complete then excludes on the next run.  

I have run borgmatic 5-10 times due to interruptions to continue this backup.  

I accept I may have to delete everything and start over, but a way to see what is going on currently would be very helpful for troubleshooting now and in the future. Even better would be a way to delete some of the files from the current backup (such as the ones I intend to exclude, if in fact they are in the repo.)

**Comment by ThomasWaldmann** [comment]
Well, if you do not have this in real production mode yet (== nothing valuable to preserve), you could just kill the repo and start over from scratch?

Did you use compression? You likely should - lz4 for very fast repos, zlib or < lzma,6 if the bandwidth to the repo is low. The default is **no compression** so that users will do an informed decision (see our docs) about the best compression for them.

In any case, I'ld use that "borg1" command (which is 1.0.x) if you are on rsync.net ("borg" maps to 0.29). Maybe this also helps a bit about the stale locks.

**Comment by ThomasWaldmann** [comment]
If the repo contents is not important, you could do an experiment first:

**Comment by walkertraylor** [comment]
Yes, I can start over.  This is personal usage as testing for commercial production usage.  My connection is slow and unstable so was looking for options before I resorted to that, but can and will proceed that way.

Thanks for the reminder about compression!  I was using lzip,6 on my tests but did not enable when switching over to borgmatic for management of borg and should enable it.

And good tip about borg1 on rsync.net, interesting.

I am open to experimentation, what's the idea?

**Comment by ThomasWaldmann** [comment]
The idea of that experiment is to remove the latest, uncommitted segments - so some space gets free.
The remainder would be either some checkpoint or some older archive(s).
If that works out, we'll know for the future.

For your repo, it is better to start over with compression, otherwise you waste space there.

**Comment by walkertraylor** [comment]
Will manually delete and reupload with compression and proper excludes file.  Thanks for support workaround ideas for future reference.
