### ISSUE TITLE
backup to local *and* remote repositories

### ISSUE THREAD

**Issue by jots** [borgbackup/borg#121]
I would like to backup to both a local repository (on another disk) and to a remote repository.
What is the best way to do that?  
create a backup twice each night?  Is there a more efficient way?

**Comment by ThomasWaldmann** [comment]
yes, just do 2 backups. the first ones will (as usual) take a bit longer, but subsequent ones will be quite fast.

**Comment by RonnyPfannschmidt** [comment]
i think this one also relates to syncing backups
