### ISSUE TITLE
read-special mode behaves inconsistent

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1215]
Moved from #1003:

@gpoudrel said:

I have a case where I backup a special device 
/dev/vg/lv-server-snap which is a symlink to /dev/dm-10

I use borg to backup /dev/vg/lv-server it follows the symlink and backup the special device.
```
# borg create --read-special /repo::today lvdisplay.txt /dev/vg/lv-server-snap
```
I mount the archive, it is odd.
```
# borg mount /repo::today /mnt
# ls /mnt/dev/
dev tmp
# ls -l /mnt/dev/vg
ls: cannot read symbolic link /mnt/dev/vg/lv-server-snap: Input/output error
ls: reading directory /mnt/dev/vg/: Software caused connection abort
total 20971520
lrwxrwxrwx 1 root root 21474836480 Jun 28 05:05 lv-server-snap
```

When I use a device which is not a symlink it works.

**Comment by ThomasWaldmann** [comment]
It is likely because we `stat()` the symlink, but in `--read-special` mode, we `open()` a regular file (using the symlink as path).

`open()` then follows the symlink and reads the file (or in this case: device) it points to.

But: the `stat()` call we do, does not follow the symlink, but stats the symlink itself, which is inconsistent in this case.

So, in `--read-special` mode, we should follow the symlink for `stat()` also.

**Comment by milkey-mouse** [comment]
This issue should probably be reopened considering the fix had to be reverted...

**Comment by ThomasWaldmann** [comment]
I'ld prefer if the issue (if any) is reproduced and a new ticket with up-to-date information is filed.
