### ISSUE TITLE
Prune --one

### ISSUE THREAD

**Issue by fulldecent** [borgbackup/borg#1219]
I would like to prune and keep only the latest of each archive.

Is this possible? Or do I need to manually look through each archive and find the correct -H -d -w -m command so that I only get one?

**Comment by jmiserez** [comment]
If you use `-H 1` it will keep only 1 archive in total. Same if you use just one of `-m 1` or `-w 1` or `-d 1`. Use `--dry-run` to see what would be deleted before you go ahead and actually do it.

**Comment by ThomasWaldmann** [comment]
Is it a good idea to keep only the latest one? Considering historical deduplication, it is cheap to keep (many) more than 1. And you'ld be glad that you did in case something went wrong with the last one.

**Comment by ThomasWaldmann** [comment]
borg 1.1 will have `--keep-last N` (which is the same as the also new `--keep-secondly N`).  Until then `--keep-hourly N` is a good approximation.

But you have to think about whether you really want that - the last 7 backups could be all taken in the last 5 minutes or on the last day. So in some cases, you might miss a older, but better backup archive.

**Comment by jmiserez** [comment]
@ThomasWaldmann I'm confused. In which case does `--keep-hourly 1` not keep only the latest one (assuming no other options)? I'm not arguing that `--keep-last 1` would not be useful, but in this specific case `--keep-hourly 1` is *exactly* the same under all circumstances, right?

**Comment by ThomasWaldmann** [comment]
Yes, for N == 1 it is the same, for N > 1, it is not.

**Comment by fulldecent** [comment]
Thank you for clarifying. It was not clear to me that one archive would be kept with -H1 even if that one archive is more than one hour old. I read the documentation to mean that EVERYTHING would be deleted and I would be left with nothing.

My backup needs to be unattended and reliable. Borg's crippling "you need to keep space available" issue is a show stopper. So I thought a 'prune --latest' would allow me to reliably control space.

I have another idea for controlling space, will create a separate issue.
