### ISSUE TITLE
deadlocks with multiple borg create

### ISSUE THREAD

**Issue by erikhydro** [borgbackup/borg#1220]
the attached script shows a problem with locking. the script simulates what happens if you have multiple servers where on each of them a cronjob does a backup to the same borg repository on a central server at the same time. because of locking an option --lock-wait 86400 is added to have a maximum waiting time of 24 hours. longer is not good, because then the next cronjob backup is started. so after 24 hours continuous blocking i want to get error output which cron will send me by mail. so far so good. every server should automatically do its backup. one after another because of locking. but it does not work.

the script shows why. you need two computers. on the server you create a borg repo with borg init. on the client you run the script.

it will run 10 backups in parallel.

you will get lots of messages like these:

Remote: Borg 1.0.2: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 96, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 455, in put
Remote:     self.prepare_txn(self.get_transaction_id())
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 199, in prepare_txn
Remote:     self.lock.upgrade()
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 299, in upgrade
Remote:     self.acquire(exclusive=True, remove=SHARED)
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 258, in acquire
Remote:     self._wait_for_readers_finishing(remove, sleep)
Remote:   File "/usr/lib/python3/dist-packages/borg/locking.py", line 287, in _wait_for_readers_finishing
Remote:     raise LockTimeout(self.path)
Remote: borg.locking.LockTimeout: /root/foorepo/lock
Remote: Platform: Linux nagios 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) i686
Remote: Linux: debian 8.5 
Remote: Borg: 1.0.2  Python: CPython 3.4.2
Remote: PID: 5658  CWD: /root
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None

the script won't terminate. there will not be 10 finished backups. if you then kill the script, you will have zero backups.

[borglockchecker.zip](https://github.com/borgbackup/borg/files/338675/borglockchecker.zip)

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/35589335-deadlocks-with-multiple-borg-create)

**Comment by ThomasWaldmann** [comment]
Can you add info about timing?
When did above backup start, when do you get the LockTimeout exception?

**Comment by ThomasWaldmann** [comment]
Hmm, looks like a deadlock that is only terminated by the timeout.

My guess is that all processes first acquire a shared read lock (multiple readers are ok) before they start the transaction (some of them might also need to resync the chunks cache, which might introduce a race condition).

When they are finished with reading, they try to upgrade the shared read lock to an exclusive write lock (only 1 writer, no readers). That deadlocks because all processes want to do that (so the read locks do not all go away, so no upgrade to a write lock will succeed). After the timeout, they all give up.

A solution could be to immediately acquire a write lock.

**Comment by erikhydro** [comment]
You can not always upgrade a read lock to a write lock, also not if waiting forever. Why? Two processes A and B are both having a read lock. Now A wants to upgrade to a write lock, so it waits until B releases its read lock. Now B wants to upgrade to a write lock too, so it waits until A releases its read lock. So A and B are deadlocked.

So if you implement a function for upgrading a read lock into a write lock, then one of the possible results of this function must be, that it does not work and the read lock has to be released first.

Since you must deal with this possible situation, it is easier to always release the read lock and then acquire the write lock. so this means every process EITHER has a read OR a write lock, but never both.

Of course things can happen between releasing the read lock and acquiring the write lock afterwards. so once you acquired the write lock you must recheck the data because someone else can have changed it in between.

Maybe an easy and robust design is to decide on which lock to take right at the beginning and then keeping the lock until the very end. example:

borg create -> write lock
borg list -> read lock
borg check -> write lock
borg delete -> write lock
and so on.

**Comment by ThomasWaldmann** [comment]
moved this to 1.0.5. while this does not work as desired, at least no harm (like corruption) is caused.

if we have time left before 1.0.4 release and can fix and test it, we can move it back to 1.0.4.

**Comment by enkore** [comment]
In the mean time a possible workaround could be to use an external distributed lock/synchronization manager to manage execution of the parallel jobs. In that case the borg internal locking would then only act as a fail-safe.

**Comment by ThomasWaldmann** [comment]
Seems like the simplest and also most robust design for now is to remove lock upgrade functionality and thus always take the required lock just from the beginning.

Long-term, a lockless design would be nice.

**Comment by ThomasWaldmann** [comment]
another workaround is to manually spread the multiple "borg create" in time, so that the their "read phases" (resyncing the chunks cache, if one uses a shared repo) does not overlap - then the deadlock does not happen.

**Comment by skunk73** [comment]
hmmm... still experiencing the deadlock even after starting the borg create processes with a 10 seconds lag from the previous...

**Comment by ThomasWaldmann** [comment]
chunks cache resync can take much longer. maybe enable INFO logging (--info) to see it.

**Comment by ThomasWaldmann** [comment]
@erikhydro I just executed your script on new locking code: works. \o/

**Comment by ThomasWaldmann** [comment]
Fixed by #1371.
