### ISSUE TITLE
Backup remote server to the local machine

### ISSUE THREAD

**Issue by AndrewBurdyug** [borgbackup/borg#1221]
Hi! 

Can I use borg for backup remote server to the local machine? 
Should I use sshfs or something like this should work:
```
borg create -s -p backup::home ssh://user@server:port:/home
```

In docs I saw only vise versa examples: backup local machine to the remote server(remote repo).

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/quickstart.html#remote-repositories

**Comment by AndrewBurdyug** [comment]
This is no what I asked.
I do not want use 'remote repositories', I want use 'local repositories' and do the backup of remote server. 

Scheme of transferring data: 

content of remote server  -> local machine (local repositories)

**Comment by RonnyPfannschmidt** [comment]
search for pull workflow, there are some basic docs for it, but its not supported in general yet

**Comment by AndrewBurdyug** [comment]
Ok, I done this by using sshfs, but I got mount point in names of backup files:
```
$ sudo sshfs -d -p 5333 root@server:/ /mnt
$ sudo borg create -s -p backup::home /mnt/home
$ sudo borg list backup::home
Enter passphrase for key /home/buran/backup: 
drwxr-xr-x root   root          0 Wed, 2016-06-29 14:20:15 mnt/home
-rw-r--r-- root   root          5 Wed, 2016-06-29 14:20:15 mnt/home/test
```
Is there a way to specify something like a `basename` and get 'bare-metal' paths in backups:
'/home' instead of 'mnt/home'?

Or some option for extracting like '--prune /mnt' ?

**Comment by RonnyPfannschmidt** [comment]
borg extract supports the `--strip-components NUMBER` option

**Comment by AndrewBurdyug** [comment]
Thanks!

**Comment by fwolfst** [comment]
I am in the same situation, the issue itself is resolved, but being able to backup remote locations to local repositories (via ssh) would be a great feature, imho. Can/should I create a new issue for that? I will not be able to contribute much.

**Comment by ThomasWaldmann** [comment]
See #900 and potentially other tickets. sshfs might be an option also.

**Comment by jeremyfritzen** [comment]
Why SSHFS and not a NFS mount point?

**Comment by ThomasWaldmann** [comment]
@jeremyfritzen sshfs might be more secure and a lot of servers have sshd running anyway. If you have nfs running anyway and there are no security concerns, you can also use that.

**Comment by jeremyfritzen** [comment]
Thanks!
Indeed, I think sshfs is better than NFS since sshd is installed by default on most of debian distributions.
Thanks!
