### ISSUE TITLE
add advice about issue #1138

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1223]
#1138 could lead to corruption, because not only input file, but also output-related OSErrors were ignored for "borg create".

we should add some advice for users how to deal with this:
- making sure they know which repos / archives are in good / bad state
- how to deal with bad state

**Comment by ThomasWaldmann** [comment]
Guess first step is doing a check, including -v:
```
borg check -v REPO
```

Potential outcomes:
- good -> nothing else to do
- errors found -> run `borg check -v --repair`
- crash (?)

**Comment by enkore** [comment]
#1202
