### ISSUE TITLE
Architecture documentation

### ISSUE THREAD

**Issue by fulldecent** [borgbackup/borg#1224]
Could the architecture of Borg please be documented in a simple beginners' guide for contributors? You can assume the reader has read all the user documentation and wants to understand the code... without having to read all of it.

Perhaps this can go into a CONTRIBUTING.md file.

Here is a project that quickly documents what is going on https://github.com/fulldecent/cameralife/blob/master/CONTRIBUTING.md#how-does-this-code-work

This will help me better understand the "note about free space" and other technical decisions the project has made.

**Comment by enkore** [comment]
http://borgbackup.readthedocs.io/en/stable/internals.html ?

**Comment by fulldecent** [comment]
This is great reading. I am still confused on the free space issue, do I need to read between the lines somewhere?

**Comment by enkore** [comment]
For operation without save_space the compaction algorithm uses most space. It's not documented but pretty much a standard off-the-shelf data logging compaction/vacuum algorithm. It copies live (not-deleted) data from old segments (log files) to new ones. After everything's done a commit is made. Segments which are now redundant are then deleted.

save_space does exactly the same thing, but commits and deletes the old segment after every segment, therefore using less space.

See also https://github.com/borgbackup/borg/blob/master/src/borg/repository.py#L40

**Comment by ThomasWaldmann** [comment]
So, in the worst case (1 chunk in every segment deleted), this could need almost 1 repo size *additional* free space compared to the space saving method (for borg 1.0).

**Comment by enkore** [comment]
Unclear whether any issue remains. Closing. Feel free to reopen if this assessment is not accurate.
