### ISSUE TITLE
Misleading error reporting in borg-extract

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1231]
Hello darkness my old friend

```
            try:
                if dry_run:
                    archive.extract_item(item, dry_run=True)
                else:
                    if stat.S_ISDIR(item.mode):
                        dirs.append(item)
                        archive.extract_item(item, restore_attrs=False)
                    else:
                        archive.extract_item(item, stdout=stdout, sparse=sparse, hardlink_masters=hardlink_masters,
                                             original_path=orig_path)
            except OSError as e:
                self.print_warning('%s: %s', remove_surrogates(orig_path), e)
```

Guess we'll just rename input_io => something_else_io (say backup_io or ... or io_io!) and apply the same fix.

Note that this isn't nearly as critical as the other error handling bug, since nothing is written. So it's "merely" misleading error reporting.

**Comment by ThomasWaldmann** [comment]
X-|

**Comment by enkore** [comment]
> I think these bugs are a really nice example of structured exception handling
> and how easy it is to write code that *looks* completely reasonable and good *unless* you inspect the entire call tree

**Comment by enkore** [comment]
#1234  in 1.0-maint
