### ISSUE TITLE
1.0.x should be able to read v2 hints files

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1235]
Pretty simple.

The difference between v1 and v2 is that 'compact' is a mapping of `segment -> count of deleted bytes in segment [free space]` in v2, while in v1 it's just a list of segments. So for 1.0-maint just need to check for version==2 and then take only the keys into `self.compact`.

This makes changing versions back-and-forth, if so desired, easier.

**Comment by ThomasWaldmann** [comment]
move to 1.0.5?

**Comment by enkore** [comment]
#1255 in 1.0-maint
