### ISSUE TITLE
borg create --progress should pay attention to terminal width?

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#124]
Right now, it looks like the --progress output is limited to 80 columns.  I typically run at 120/132/160 column window.  Because the output of --progress is limited to 80 columns, the shortening of the file path isn't very useful.

```
 11.55 GB O  10.51 GB C 362.17 kB D cygdrive/c/Program F...Boss_Various_WAV.upk
```
As can be seen, the /cygdrive/c/ prefix uses up a lot of the useful space in the filename output.  If --progress would pay attention to terminal width, I could enlarge the window (on the fly) to see more information about which file is being backed up.

**Comment by ThomasWaldmann** [comment]
sure, but for that we need to determine terminal width for all platforms borg runs on.

**Comment by RonnyPfannschmidt** [comment]
Click has a relatively reliable helper function for that

**Comment by ThomasWaldmann** [comment]
shutil on py 3.3+ has get_terminal_size, so we just delay this until we drop 3.2 support.

**Comment by ThomasWaldmann** [comment]
Note: click seems to not support py 3.2 (at least does not run tests on py32), also it does not have clear pypi classifiers about python3.x compatibility.

**Comment by ThomasWaldmann** [comment]
looks like this already works, thanks to @anarcat's work.
