### ISSUE TITLE
Documentation unclear: What is the default exclude style?

### ISSUE THREAD

**Issue by nomeata** [borgbackup/borg#1247]
The section http://borgbackup.readthedocs.io/en/stable/usage.html#borg-help-patterns tells me about the various exclusion formats, and says “Explicit style selection is necessary when a non-default style is desired”. But nowhere in the docs I could find what the default style is, and if I can globally change the default style.

Also, currently on that site at least, the examples are not typeset properly, i.e. not as literate code.

**Comment by nomeata** [comment]
(The typesetting is fixed via #1248)

**Comment by nomeata** [comment]
Ok, reading the code it seems that `FnmatchPattern` is the default. I will update the docs and amend #1248.

**Comment by ThomasWaldmann** [comment]
Cool, thanks. See my comments in the PR.

BTW, be careful what applies to 1.0.x and what is new in master branch (will be 1.1 at some time).

**Comment by enkore** [comment]
Fixed in #1251
