### ISSUE TITLE
Update docs to reflect new checkpoint behavior

### ISSUE THREAD

**Issue by dragetd** [borgbackup/borg#1249]
New checkpoints are saved every 30 minutes and not 5. But they also work in-between files now. Update docs (create / FAQ) accordingly.

I will write something up right away.

**Comment by ThomasWaldmann** [comment]
IIRC, the docs never said that the time is 5 minutes / 300s.

And the in-between files stuff still lives in a PR, it is not in master yet.

**Comment by dragetd** [comment]
http://borgbackup.readthedocs.io/en/latest/usage.html?highlight=checkpoint#borg-create says 300 seconds and
http://borgbackup.readthedocs.io/en/latest/faq.html?highlight=checkpoint#if-a-backup-stops-mid-way-does-the-already-backed-up-data-stay-there says 5 minutes.

Oh, and you are right, thought the last commit was about the in-file checkpoints, but it is not. Well, might be not a bad idea to update the FAQ about checkpoints along. So, I should not open a PR (yet)?

**Comment by ThomasWaldmann** [comment]
You could add the general stuff already, but do not talk about stuff that is not merged yet.

**Comment by dragetd** [comment]
I guess I will wait until the in-file checkpoint handling has been worked out and then update things.
