### ISSUE TITLE
cygwin test failure: IsADirectoryError when renaming

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1256]
current master branch under cygwin 2.5.2 on windows 10 (ntfs):
```
    # in test_unreadable_index:

    def write_index(self):
        hints = {b'version': 2,
                 b'segments': self.segments,
                 b'compact': self.compact}
        transaction_id = self.io.get_segments_transaction_id()
        hints_file = os.path.join(self.path, 'hints.%d' % transaction_id)
        with open(hints_file + '.tmp', 'wb') as fd:
            msgpack.pack(hints, fd)
            fd.flush()
            os.fsync(fd.fileno())
        os.rename(hints_file + '.tmp', hints_file)
        self.index.write(os.path.join(self.path, 'index.tmp'))
        os.rename(os.path.join(self.path, 'index.tmp'),
>                 os.path.join(self.path, 'index.%d' % transaction_id))
E       IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpmhpbju03/repository/index.tmp' -> '/tmp/tmpmhpbju03/repository/index.1'

src/borg/repository.py:330: IsADirectoryError
```

**Comment by PlasmaPower** [comment]
I have a feeling cygwin's unix-like FS emulation is going to give us a lot of trouble. Are you sure we want to invest the effort in ensuring tests run?

**Comment by ThomasWaldmann** [comment]
well, borg worked in the past with cygwin, so it would be good to keep it working.

any idea about what is happening here? where/why is a directory involved here?

**Comment by ThomasWaldmann** [comment]
Added it to 1.0.4 milestone, so we can try to fix that before release.

**Comment by enkore** [comment]
Does it happen with 1.0-maint, if it doesn't... maybe test state leakage from RepositoryAuxiliaryCorruptionTestCase?

**Comment by ThomasWaldmann** [comment]
It only happens with master branch, not 1.0-maint.

**Comment by ThomasWaldmann** [comment]
related to exception handling and "InternalOSError". check again later.

**Comment by ThomasWaldmann** [comment]
does not happen any more now.
