### ISSUE TITLE
add missing env var for --remote-path

### ISSUE THREAD

**Issue by nomeata** [borgbackup/borg#1258]
`borg` supports configuring everything related to “how do I access the repository” using environment variables, in particular `BORG_REPO`, `BORG_PASSPHRASE`, `BORG_KEY_FILE` and `BORG_RSH`. The only one missing is `BORG_REMOTE_PATH`.

If that were added, it would be possible to set up an environment (either in `.profile`, or via a wrapper) where no repository-access-specific parameters need to be passed as arguments.

(#1163 is somewhat related)

**Comment by ThomasWaldmann** [comment]
Good idea.

Seems like this was somehow forgotten and caused the annoyance of always having to give `--remote-path X` if the executable on the remote is not "borg" (and in PATH).

rsync.net and their "borg1" come to mind...

**Comment by ThomasWaldmann** [comment]
fixed by #1259 in 1.0-maint.
