### ISSUE TITLE
RemoteArchiverTestCase failures on cygwin (1.0-maint)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1268]
Quite some of these tests either hang or fail:

```
py.test -v -k Remote
```

The corresponding local tests work:

```
py.test -v -k "not Remote"    # ... and not bench
```

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/35765312-remotearchivertestcase-failures-on-cygwin-1-0-maint)

**Comment by ThomasWaldmann** [comment]
It seems like borg.remote receives crap via the inter-process pipes.
The msgpack unpacker does not unpack the expected data formats.

It does not seem to be related to "binary mode", I did some experiments in a cygwin python interpreter and was able to send b'\n\001\002\000' to a subprocess and it was echoed back unchanged.

So, what can it be? Can a pipe lose data?

**Comment by skabanov** [comment]
Hello. I was unlucky enough to have my backup server running windows . So i was hit by this bug using cygwin package.I could create archive without problem, but cannot get info or mount it on my linux server. I debugged it down to  pipe buffer starvation on cygwin.I was able to resolve it by patching cygwin dll by increasing pipe default buffer.

diff --git a/winsup/cygwin/fhandler.h b/winsup/cygwin/fhandler.h
index c7db8f8..e9c4fa1 100644
--- a/winsup/cygwin/fhandler.h
+++ b/winsup/cygwin/fhandler.h
@@ -31,7 +31,7 @@ details. */
 /* It also appears that this may be the only acceptable block size for
    atomic writes to a pipe.  It is a shame that we have to make this
    so small.  http://cygwin.com/ml/cygwin/2011-03/msg00541.html  */
-#define DEFAULT_PIPEBUFSIZE PREFERRED_IO_BLKSIZE
+#define DEFAULT_PIPEBUFSIZE 31*1024*1024 /*PREFERRED_IO_BLKSIZE*/
 
 /* Used for fhandler_pipe::create.  Use an available flag which will
    never be used in Cygwin for this function. */

**Comment by enkore** [comment]
This sounds a lot like a (bad) bug in cygwin. Did you / can you raise this issue with the cygwin project?

**Comment by skabanov** [comment]
Locally on windows everything is working.Remotely list, checks, create are ok.For info and mount
i got either:
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 83, in wrapper
  File "borg/archiver.py", line 95, in wrapper
  File "borg/archiver.py", line 591, in do_info
  File "borg/archive.py", line 345, in calc_stats
  File "borg/remote.py", line 404, in get_many
  File "borg/remote.py", line 329, in call_many
Exception: Unexpected RPC data format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 1684, in main
  File "borg/archiver.py", line 1621, in run
  File "borg/archiver.py", line 85, in wrapper
  File "borg/remote.py", line 226, in __exit__
  File "borg/remote.py", line 388, in rollback
  File "borg/remote.py", line 271, in call
  File "borg/remote.py", line 329, in call_many
Exception: Unexpected RPC data format.

or just hunging pipe.

**Comment by skabanov** [comment]
Looks like they reverted big pipe sizes in 2011 because of this:
http://cygwin.com/ml/cygwin/2011-03/msg00541.html

**Comment by enkore** [comment]
Ah right, my bad. This is about RPC issues, not about writing to disk.

**Comment by ThomasWaldmann** [comment]
@skabanov can you discuss this with the cygwin developers?

https://cygwin.com/problems.html

I recently ran the tests in the new windows10 vagrant machine and the RemoteArchiver / RemoteRepository issues seems the be the last big problem, the other tests work fine.

**Comment by ThomasWaldmann** [comment]
ping

**Comment by ThomasWaldmann** [comment]
http://hastebin.com/wirabaropo.sql seen by ChainFire in practice - same cause?

**Comment by ThomasWaldmann** [comment]
I've tagged it with corruption, as it seems that borg data gets corrupted between borg client and repo - not our fault likely, but still interesting for potential users of borg on cygwin.

**Comment by ThomasWaldmann** [comment]
Considering above issue and if running under windows 10, #1961 might be interesting.

**Comment by ThomasWaldmann** [comment]
Note: I send a notice to the `cygwin` mailing list: https://cygwin.com/ml/cygwin/2017-01/msg00087.html

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.0.9/borg/remote.py#L188 this is the place where the ssh subprocess is forked and the pipes are set up.

**Comment by ThomasWaldmann** [comment]
Just noticed that above is only the borg client pipe setup. The borg serve setup is here:

https://github.com/borgbackup/borg/blob/1.0.9/borg/remote.py#L73

And here is maybe the culprit: the stdin/stdout/stderr likely defaults to text mode and really needs to be explicitly set to binary on windows for serve().

**Comment by enkore** [comment]
If this theory is correct it would mean that the FDs are in text mode, so \r\n things get mangled. _setmode() would fix that.

Python [has that](https://docs.python.org/3/library/msvcrt.html#msvcrt.setmode) but I'm not sure whether that module is available in cygwin, since it's called msvcrt.

**Comment by ThomasWaldmann** [comment]
Hmm, we use 2 kinds of I/O there:
- logging (to stderr, should not matter for this corruption issue)
- os.read(), os.write() to the FDs (no text mode issue with that!)

**Comment by Astara** [comment]
@skabanov - the issue about pipes you cited was on WinXP where total user member was limited to 2G (or 3G in some special cases).  WinXP is no longer supported and certainly most users will have more than a 2G address space.

@ThomasWaldmann - I don't think text mode is your problem -- it doesn't make sense to use text mode for a pipe, not to mention, it would violate the posix compatiblity.

For a test, can you set the values of the writer->reader to be "synchronous".

Things I'd try:  why use pipes for the network case? -- its prone to being less stable/having more problems than if you just use ssh for transfer.  I.e. spawn a process on client to run ssh and
connect client stdout to ssh-in, and pipe it directly through ssh.

Would simplify the logical design and if it works, you can focus on getting pipes fixed -- if you still
want to -- or just use ssh-direct.

Um... did I hear you say python?  Erk... might try perl or even c++!  (pullin' your leg)... :-)

FWIW, rsync can be set to use ssh via the RSYNC_RSH envvar and it works pretty reliably (though 
considerably slower than passing it in cleartext -- not something to worry about right now, though,
as first priority is getting it working, then focus on perf issues if needed.  

Hope this helps!

**Comment by ThomasWaldmann** [comment]
@Astara with "pipe" i meant the inter-process pipe between borg and its subprocess ssh (on the client side) and sshd and its subprocess "borg serve" (on the server side). Sounds like you mean the same.

Not sure what you mean with "writer->reader to be synchronous" or how it would help here.
Nor what you mean with "ssh-direct".

If we have access to destination filesystem, we don't need to do client/server, we could also just directly write to the repo.

**Comment by enkore** [comment]
> Things I'd try: why use pipes for the network case?

These are the pipes from and to the respective SSH processes.

**Comment by Astara** [comment]
@enkore - Just did a test of passing a 5.6G tar between two machines here, using ssh and rsh.
Rsh got about 3x the throughput, with ssh barely topping 100MB/s.  Yeah, various hardware systems __can__ do faster in specific instructions, but in real programs -- are they able to use those instructions and feed them quickly enough?

rsh had speeds between 300-400MB/s (10Gb link).

In practice, anything doing calculations in software on every byte is going to slow things down.  As soon as those algorithms are backported to windows 7, I'll test again.... ;-)

**Comment by ThomasWaldmann** [comment]
seems like cygwin's pipe behaviour is being fixed:

https://sourceware.org/ml/cygwin/2017-01/msg00167.html

**Comment by ThomasWaldmann** [comment]
continued in #2075.
