### ISSUE TITLE
Document Attic->Borg incompatibilities, provide documentation to build Attic<->Borg archive converter

### ISSUE THREAD

**Issue by sergiocallegari** [borgbackup/borg#127]
Hi,

I think that the subject says all, still let me be more specific.

The borg documentation says that it is incompatible with attic... but how?

- Are the archives incompatible or just the command line invocation?
- If the archives are incompatible in what sense they are?

Since the attic archive format is stable, in case the borg format deviates from it wouldn't it be nice to document how this happens?

**Comment by ThomasWaldmann** [comment]
It's the archives, see #21 for more details.

Also, as time goes by, the command line might also become incompatible.

**Comment by ThomasWaldmann** [comment]
As we already have #21 I am closing this as duplicate.

**Comment by sergiocallegari** [comment]
Well, my idea was to have a text file inside the Borg sources kept up to date as long as incompatible changes /both in the interface and in the archive format/ accumulate. If this is also the idea in #21, then good to close this one. Sorry for the noise.

**Comment by ThomasWaldmann** [comment]
As long as there is no converter (see #21), borg has just to be seen as different software, so what's the point of having such docs?
