### ISSUE TITLE
Check free space on repository transaction commit

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#1272]
To avoid leaving the filesystem the repository resides on without sufficient free space, borg should check the free space just before commiting a transaction. If the free space is to low an transaction abort will leave the repository in a safe state while preserving a needed free space margin on the file system.

The needed amount of storage for the commit (not counting space freed by compaction) should be fairly easy to calculate.

Thomas suggested to additionally keep 4x index size of free space. Also compaction will need space. I *think* up to the maximum segment size.

**Comment by ThomasWaldmann** [comment]
Implementation note: the check could just raise OSError ENOSPC artifically & a bit early.

**Comment by enkore** [comment]
There are multiple parts to this as I mentioned in other tickets I'm too lazy to search for right now ;)

1. The index write-out requires the necessary free space. This is easy to calculate and check beforehand
2. The space requirements of compaction.

  So this is the more interesting part. I think a solution is pretty much straightforward, do --save-space with none of the drawbacks (speed, disk scratching, mainly). When a segment is full, just write a commit tag. Then any old segments may be deleted. (This is the complete_xfer part). Don't write the index, which is the slow and disk-scratchy part.

  If it crashes during this, the old index is still around, and replay_segments only need to replay segments created during compaction. After overall compaction is done, a normal commit w/ index write-out is done, as usual.

  This limits free additional free space requirements of the compaction to approx one segment size. Again, can be checked beforehand.
