### ISSUE TITLE
Having direct access to the latest backup (of an optional prefix)

### ISSUE THREAD

**Issue by oderwat** [borgbackup/borg#128]
I would love to have the possibility to directly refer to the latest backup like in "bup" where you can access the latest one by specifying "latest" as location.

Currently I use something list this:

```
borg list vps-borg:mt02-df-dbs.borg::$(borg list vps-borg:mt02-df-dbs.borg | tail -1 | awk '{ print $1 }')
```

With that change this would be:

```
borg list vps-borg:mt02-df-dbs.borg::latest
```

Of course `latest` could than not be an archive name anymore. 

I would like if this also would support --prefix definitions and use the latest backup of an archive with that prefix.

P.S.: I know that all of this could be done with scripting. But that would be harder to handle all kinds of possible errors.

**Comment by ThomasWaldmann** [comment]
how about repo::prefix[idx] and using python index semantics on a sorted list of archives with the given prefix:
0 <= idx < n: the archive at position idx
-n <= idx <= -1: the archive at the -idx-last position
 
"lastest" would be repo::prefix[-1].

or we reverse sort order, then "latest" is repo::prefix[0].

**Comment by ThomasWaldmann** [comment]
see also: https://github.com/jborg/attic/issues/148

**Comment by ThomasWaldmann** [comment]
If we would like to use `[n]` index syntax, we would have to disallow `[]` as archive name characters.

Problem: may conflict with (currently) valid archive names.

**Comment by Ape** [comment]
We could use these without reserving new characters:

```
repo::prefix:0 => the latest with prefix 'prefix'
repo::prefix:1 => the next one
repo:::0       => the latest in the whole repo
```

**Comment by RonnyPfannschmidt** [comment]
how about a more explicit addressing mode

if repository, name to match and indexing are separate arguments then the whole thing is trivial and non-ambigious

**Comment by ThomasWaldmann** [comment]
@Ape good idea, : is maybe reserved already.

@RonnyPfannschmidt I also thought about splitting up (repo and archive), but that is a major change, so has to wait until 2.0 if we do that.

prune takes repo and a --prefix argument separately. no ...::archive allowed for prune, but we already have allowed this for misc. commands that would need the new index mechanism.

**Comment by enkore** [comment]
> good idea, ":" is maybe reserved already.

Nope. Even :: is okay in archive names, `some_archive:asd::def:::foo::::bar` is a valid archive name.

**Comment by pepa65** [comment]
I think the syntax should be more like:
`borg list repo:: -P prefix --index -1`

**Comment by ThomasWaldmann** [comment]
Recently, --first / --last / --sort / --prefix was made available to some commands.

**Comment by kewlfft** [comment]
Therefore, I understand the way to proceed is the following and there is no other functionality being developed:
```
borg list myrepo::$(borg list --last 1 myrepo)
```

**Comment by samuelharmer** [comment]
> Therefore, I understand the way to proceed is the following and there is no other functionality being developed:
> 
> ```
> borg list myrepo::$(borg list --last 1 myrepo)
> ```

`borg list --last 1 myrepo` includes a timestamp and hash by default which causes the `list` command to fail. Actual syntax follows.

```
borg list myrepo::$(borg list --format '{archive}{NL}' --last 1 myrepo)
```

**Comment by ThomasWaldmann** [comment]
Can you try `--short` instead of `--format ...`?

No, I'ld rather not add a very special meaning into using `repo::` without an archive name.

**Comment by ThomasWaldmann** [comment]
Some updates about borg2:

- will have repo and archive name separated (not glued together by `::`)
- will not have `--prefix` any more. users can use the more powerful `-a` / `--glob-archives` for the same purpose.

Thus, solutions for this:
- borg 1.x: `borg list --prefix MYPREFIX --last 1 --short MYREPO`
- borg 2: likely something like `borg --repo MYREPO rlist --last 1 -a 'MYPREFIX*'`
