### ISSUE TITLE
more FUSE tests

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1284]
We need more FUSE tests to avoid stuff like #1282.

We already have:
- mount (repo and archive)
- list/compare directory

Still needed:
- stat file
- read file
- list xattrs
- read xattrs

Avoid duplicating the fuse mounting/unmounting code, it is already there twice.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/35838902-more-fuse-tests)

**Comment by enkore** [comment]
Fixed in #1292
