### ISSUE TITLE
add --append-only to 'borg init'

### ISSUE THREAD

**Issue by rdeker** [borgbackup/borg#1291]
It's a small nit, but I'm automating some borg repo creations and it would be great if append-only mode could be specified at init time instead of having to automate editing the config file.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/35866629-add-append-only-to-borg-init)

**Comment by ThomasWaldmann** [comment]
did you see that you can use `borg serve --append-only ...` now in 1.0.5?

see the updated append-only docs:
http://borgbackup.readthedocs.io/en/stable/usage.html?highlight=append-only#append-only-mode

So, I guess you'ld rather want to do that, right?

**Comment by rdeker** [comment]
I did, but how does one do that in a case where repos are accessed via network attached disk (NFS in my case) rather than via ssh?

**Comment by ThomasWaldmann** [comment]
Ah, true, doesn't help for that.

**Comment by ThomasWaldmann** [comment]
fixed in 1.0-maint by #1386, soon to be merged into master also.

**Comment by ThomasWaldmann** [comment]
@PlasmaPower claim it :)

**Comment by PlasmaPower** [comment]
@ThomasWaldmann I think you've forgotten to accept the claim.
