### ISSUE TITLE
borg-mount misses files that can be extracted through borg-extract

### ISSUE THREAD

**Issue by Voltara** [borgbackup/borg#1295]
See jborg/attic#382

Reproduced this one with borg 1.0.5.  The order of the paths in `borg create` matters.  Notice the discrepancy between `borg mount` and `borg list` for archive `repo::2` in this example.

    (borg-env) askalski@meki:~$ borg -V
    borg 1.0.5
    (borg-env) askalski@meki:~$ mkdir /tmp/issue382
    (borg-env) askalski@meki:~$ cd /tmp/issue382
    (borg-env) askalski@meki:/tmp/issue382$ mkdir -p fs/mnt mnt fakemount repo
    (borg-env) askalski@meki:/tmp/issue382$ echo hello > fakemount/README
    (borg-env) askalski@meki:/tmp/issue382$ sshfs localhost:/tmp/issue382/fakemount fs/mnt
    
    (borg-env) askalski@meki:/tmp/issue382$ borg init -e none repo
    (borg-env) askalski@meki:/tmp/issue382$ borg create --one-file-system repo::1 fs fs/mnt
    (borg-env) askalski@meki:/tmp/issue382$ borg create --one-file-system repo::2 fs/mnt fs
    (borg-env) askalski@meki:/tmp/issue382$ borg mount repo mnt
    
    (borg-env) askalski@meki:/tmp/issue382$ find mnt -ls
            1      0 drwxr-xr-x   1 askalski askalski        0 Jul  8 19:31 mnt
            2      0 drwxr-xr-x   1 askalski askalski        0 Jul  8 19:31 mnt/1
      1000000      0 drwxrwxr-x   1 askalski askalski        0 Jul  8 19:30 mnt/1/fs
      1000097      0 drwxrwxr-x   1 askalski askalski        0 Jul  8 19:30 mnt/1/fs/mnt
      1000194      0 -rw-rw-r--   1 askalski askalski        6 Jul  8 19:30 mnt/1/fs/mnt/README
            3      0 drwxr-xr-x   1 askalski askalski        0 Jul  8 19:31 mnt/2
      1000577      0 drwxrwxr-x   1 askalski askalski        0 Jul  8 19:30 mnt/2/fs
    
    (borg-env) askalski@meki:/tmp/issue382$ borg list repo::1
    drwxrwxr-x askalski askalski        0 Fri, 2016-07-08 19:30:01 fs
    drwxrwxr-x askalski askalski        0 Fri, 2016-07-08 19:30:10 fs/mnt
    -rw-rw-r-- askalski askalski        6 Fri, 2016-07-08 19:30:10 fs/mnt/README
    
    (borg-env) askalski@meki:/tmp/issue382$ borg list repo::2
    drwxrwxr-x askalski askalski        0 Fri, 2016-07-08 19:30:10 fs/mnt
    -rw-rw-r-- askalski askalski        6 Fri, 2016-07-08 19:30:10 fs/mnt/README
    drwxrwxr-x askalski askalski        0 Fri, 2016-07-08 19:30:01 fs
    
    (borg-env) askalski@meki:/tmp/issue382$ fusermount -u fs/mnt 
    (borg-env) askalski@meki:/tmp/issue382$ fusermount -u mnt

**Comment by enkore** [comment]
Hiding somewhere in here https://github.com/borgbackup/borg/blob/1.0-maint/borg/fuse.py#L71

From a quick look I would say that this is the part where it goes wrong: https://github.com/borgbackup/borg/blob/1.0-maint/borg/fuse.py#L103 creating a inode for "fs" due to "fs/mnt" being processed "fs" / "mnt".  That inode is then replaced later by the explicit "fs" item IMHO.

**Comment by enkore** [comment]
I guess it should try _find_inode first before allocating a new one.

**Comment by ThomasWaldmann** [comment]
Yes, before line 97, first try _find_inode. If we have one already, the content of it is made-up and we need to replace all referers to that inode by references to the freshly added inode with the correct directory item.

**Comment by enkore** [comment]
Fixed in #1296
