### ISSUE TITLE
somehow warn when extracting a damaged file

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1299]
borg check --repair replaces file chunks that are missing in the repo by all-zero chunks of same length.

but there currently is no indication when extracting such a file, it looks normally, no warning.

so, emit a warning? rename the file in the metadata, e.g. ".damaged"?

when a file is healed later, it should extract normally again.

**Comment by textshell** [comment]
also maybe the archive as a whole could maybe gain a flag "contains damaged files". This could then be displayed in list.

**Comment by enkore** [comment]
Fixed in #1301
