### ISSUE TITLE
new compression code and liblz4 availability

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#130]
PR #129 introduces a liblz4 requirement - just noticed that this is not available by default on ubuntu 12.04.
```
# install liblz4-dev (and liblz4) via ppa on ubuntu 12.04
add-apt-repository ppa: gezakovacs/lz4
apt-get update
apt-get install liblz4-dev
```

Can other people have a look how it is for other linux distributions?

**Comment by RonnyPfannschmidt** [comment]
fedora 22 supplies lz4-devel as well as python-lz4

```
$ dnf search lz4
Last metadata expiration check performed 0:26:16 ago on Sun Aug  2 22:15:22 2015.
=================================================== N/S Matched: lz4 ===================================================
lz4.x86_64 : Extremely fast compression algorithm
lz4.i686 : Extremely fast compression algorithm
lz4-static.i686 : Static library for lz4
lz4-static.x86_64 : Static library for lz4
python-lz4.x86_64 : LZ4 Bindings for Python
python3-lz4.x86_64 : LZ4 Bindings for Python3
lz4-devel.i686 : Development library for lz4
lz4-devel.x86_64 : Development library for lz4
php-horde-horde-lz4.x86_64 : Horde LZ4 Compression Extension
perl-Compress-LZ4.x86_64 : Perl interface to the LZ4 compression library
```

**Comment by ThomasWaldmann** [comment]
the compression branch could be in 0.25, but requires additionally lz4 - any problem with that?

**Comment by ThomasWaldmann** [comment]
closing as I am going to merge this now.

If people have an issue with lz4 availability, I suggest they either upgrade to a more recent linux distribution, lobby for backport creation (if not already available) for whatever they currently use or just continue using 0.24 (last version that does not require lz4) until lz4 availability improves.
