### ISSUE TITLE
package Borg for OpenWRT

### ISSUE THREAD

**Issue by miguipda1** [borgbackup/borg#1311]
Dear TW,

Borg is the main perfect backup system I found till now.
But there is a real need that could still spread it widely.

I want to talk about a use at home and also in small companies.
They usually use some router on which a harddrive is installed (or connected). It means that harddrive need to get some secure backups that Borg could perform (to cloud when encrypted).

For this reason the main widespread operating system use for this kind of routers (that allows to transform them in file server) is OpenWRT.

Then all the OpenWRT users (and they are a lot accross the world) still need Borg as a package that could run on OpenWRT.

For this reason could you please take in consideration to create a package for this OS ?
You may test it by using [OpenWRT on VirtualBox](https://wiki.openwrt.org/doc/howto/virtualbox).
To help you take note you may found the existing available package dependencies [here](https://downloads.openwrt.org/chaos_calmer/15.05.1/ar7/generic/packages/packages/).

Sincerely thanks and have a nice day.

With pleasure to be able to use it soon on our routers (servers).

Miguipda ;-)

**Comment by RonnyPfannschmidt** [comment]
i own one of those myself, at least mine has a severe lack of ram

borg does need a good amount of ram for the use of the store, both client and server

it may be possible to use a openwrt as a store after the implementation of a dumb ssh protocol
but i don't see a path for supporting a full borg process on such a stripped system

**Comment by miguipda1** [comment]
Dear TW,

this is why after having wait one year I finally bought a more powerfull router with 1Gb of RAM and a (onboard) SATA HDD (of 1To) : its name is [Banana Pi R1](http://www.banana-pi.org/r1.html) (sometimes also named Lamobo R1).

It is also why I proposed you may test your package on a Virtualbox then it will be used by people who have a "good" router (I means whith enough memory).

Have a nice day.

**Comment by ThomasWaldmann** [comment]
Most routers nowadays desperately lack RAM and some also flash (space to install stuff).
The usual MIPS cpu in most routers is also rather slow and many of these small platforms can only connect a mass storage device via USB2 (for some this might be not obvious if they use a SATA/USB2 converter internally, but you'll notice the not-that-great speed).

You are kind of lucky if yours has enough resources, but most don't. So I don't think there are enough users who could use that to rectify the developer resources needed to constantly support this.

That said, noone is holding you back from installing borg on your powerful router, just do the install from source, as documented (see linux instructions). If you want to offer such packages, you could link to them via the community repo.

**Comment by enkore** [comment]
Hi miguipda1, this project just develops the software, shipping/packaging isn't done by here. We provide static binaries as a convenience for some systems, but that's pretty much it. I would recommend contacting OpenWRT people (e.g. IRC channel or maybe they have a mailing list or forum for package requests) about packaging this project for their OS.

Progress for distribution packages is tracked in #105, therefore closing as a duplicate.

**Comment by callegar** [comment]
I think that what is being asked here is not to have the whole of borg on the openwrt machine, rather to have some code to be run on the openwrt machine such that borg running on a host can connect to.

In fact, something like this exists already (sort of). Openwrt has ssh packages and on the host you can mount an sshfs where borg can put its repos.

Yet, I believe that much can be improved over this situation. Paying the overhead of the sshfs is not nice, and setting it up requires working "outside" of the borg command.

Ideally, one could imagine a dumbish-but-not-completely-dumb borg protocol to store data. The "not completely dumb part" should be a compromise on keeping the server light (so that it can be coded in C rather than python and run on systems with extremely limited ram) and keeping the network  round trips to a minimum (to help on high latency connections).

**Comment by enkore** [comment]
There is nothing really keeping anyone from doing that, the network protocol is lightweight and language agnostic, as are the on-disk data structures.

However, the logic behind the repository is quite non-trivial and there aren't enough resources in this project to sustain another implementation of it.

To really save a lot of memory (eg repository index) a simple reimplementation in C wouldn't suffice, it would need relatively complex changes (eg. memory mapping the index) which would tend to diminish speed in favour of memory: While the Python runtime with Borg loaded may be around 30-40 MB, a repository index can easily grow beyond that. For example in one of my repos the index is about 170 MB for a 400 GB repository.
