### ISSUE TITLE
implement lz4-compression level parameter

### ISSUE THREAD

**Issue by bmhm** [borgbackup/borg#1321]
Hello, a minor issue/suggestion.

The docs don't tell anything about lz4 and compression parameters (lz4,1 through lz4,6).
Anyway, I'm using lz4,6 for some files and borg doesn't complain.

Source: http://borgbackup.readthedocs.io/en/stable/usage.html#borg-create

lz4 command line utility can take those parameters. So, does borg react to this compression parameter?

To be tagged as minor && docs.

**Comment by bmhm** [comment]
When dealing with the docs anyway, why not give some examples like corresponding command line tools. Would be helpful.

**Comment by bmhm** [comment]
thanks @enkore . But given that the lz4 binary DOES take a parameter, we could also say borg can be enhanced.

**Comment by enkore** [comment]
(Hmm, seems this was lost in the 18:00 github outage, anyway Lazarus has it)

> We'll leave this as-is for now. Having `lz4` optionally accept+ignore the level parameter allows to easily add lz4 level support later, with no need to adjust scripts between borg versions.

**Comment by bmhm** [comment]
By the way, the man page and compression option is confusing anyway.

- lz4 is an algorithm
- zlib is a library or a specific implementation (using the DEFLATE algorithm, extendable for other algorithms)
- lzma is an algorithm

So, the -C argument should have taken lz4, deflate, lzma instead imho. Perhaps deflate could be added as an alias for zlib. As soon as zlib implements more algorithms, things might get confusing, don't you think?

Also, what is the current default (only) level of lz4? Why no INFO/Warning, that the level is ignored?

**Comment by enkore** [comment]
LZ4 only has two levels AFAIK, standard and best. Default is standard.

> zlib vs deflate

Technically, yes, however zlib is kinda synonymous to deflate. It's also rather unlikely zlib will ever implement anything new.

**Comment by bmhm** [comment]
A proposal:
Even if there _WERE_ only two levels, still implement levels 0-9. Then map 0-4 to low and 0-9 to high compression. This way no scripts are being broken and GUIs are easier to implement.

> It's also rather unlikely zlib will ever implement anything new.
Agreed. Still at first, it was confusing to me. I was looking for something like "gzip" oder "DEFLATE" (although gzip is a file format using a header and DEFLATE). Some tools, like clonezilla, use the term gzip when they mean DEFLATE, bz2 when they mean BWT and 7z when they mean lzma. Technically it's less correct, but still easier to recognize -- you did hear of gzip, bzip2 and 7z before, didn't you?

perhaps `borg help compression` could yield such information.

**Comment by ThomasWaldmann** [comment]
lz4hc seems a bit pointless: it is slow for compression (slower than zlib) and only fast for extraction - considering we need 99% compression and 1% extraction maybe,

**Comment by dragetd** [comment]
Also see https://cyan4973.github.io/lz4/ there are also stats for 'Compression + Transfer + Decompression'

LZ4HC is optimized for webapplications where resources are compressed once, but decompressed many times. Backups usually often have compression and (hopefully) rarely decompression.

Funny enough, lz4 help only documents -1 vs -9 for fast and high compression. But the lz4 binary does indeed take -2…8 as an argument. Even more strange: 2 and 3 seem to make a difference while anything above 4 seems to be identical.
see https://gist.github.com/dragetd/305509b8f77ff98fa10f388ecd388331

Nevertheless, lz4hc is not really practical for a backup programm.

**Comment by bmhm** [comment]
> lz4hc seems a bit pointless

> LZ4HC is optimized for webapplications 

I never intended to pose an RFC for LZ4 hc... 

> Even more strange: 2 and 3 seem to make a difference in speed while anything above 4 seems to be equally slow.

This is most interesting! I will rewrite my local scripts to sth below 4 then. Probably 4 to 9 ist just the same?

**Comment by ThomasWaldmann** [comment]
closing this, nothing to do.
