### ISSUE TITLE
borg break-lock doesn't use BORG_REPO env variable

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#1324]
Most other commands do.
Using 1.0.6.

**Comment by enkore** [comment]
workaround (from the docs)

> BORG_REPO
>    When set, use the value to give the default repository location. If a command needs an archive parameter, you can abbreviate as ::archive. If a command needs a repository parameter, you can either leave it away _or abbreviate as ::, if a positional parameter is required._

Works, though unintuitive here:

```
$ BORG_REPO=testrepo borg break-lock ::
$
```

**Comment by FabioPedretti** [comment]
Thanks, I noticed however that "borg list" works also without the :: , so this doesn't look consistently with every command?

**Comment by enkore** [comment]
Yes, it's a small bug/annoyance in the `break-lock` command; with a workaround (for now).

**Comment by enkore** [comment]
#1327 merged, fix scheduled for 1.0.7, 1.1
