### ISSUE TITLE
ZSH Autocompletion File

### ISSUE THREAD

**Issue by mrkmg** [borgbackup/borg#1328]
Hello,

I have created a zsh completion function for Borg.

Is this something you would like to integrate with the repository? If so, feel free to take it. Otherwise, feel free to just use it. It does need a little more work, which I would be happy to make a PR for once I have thoroughly tested it.

https://gist.github.com/mrkmg/dbabe71b379adb282ca6ef4568d40f5a

**Comment by ThomasWaldmann** [comment]
How about putting it into a repo of yours and link to it via our community repo?

**Comment by enkore** [comment]
Yes I think that would be a good solution for now. Distros can also package it from there, if they want to.

**Comment by mrkmg** [comment]
Will do! I am working on making it a little better in regards to performance and making sure each autocomplete is valid (I know as it stands a couple options are showing up improperly)

**Comment by ThomasWaldmann** [comment]
@mrkmg maybe document the borg version for which you make it and update it when you adapt to newer borg releases.

**Comment by mrkmg** [comment]
I will use tags for that. Correlate the tags with the version of Borg.

btw, borg is awesome!

**Comment by enkore** [comment]
borgbackup/community#3 merged, thanks
