### ISSUE TITLE
Filesystem boundary detection

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1339]
http://blog.schmorp.de/2016-03-03-detecting-a-mount-point.html

> Unfortunately, this fails badly on Linux, for two reasons. The first is a bug - **st_dev values are not stable (most notably with NFS), that is, you might stat a path, get a st_dev value, and later stat the same path again to get a different st_dev value, even though nothing has changed.** This can cause your tree walker to detect a filesystem crossing when there really isn't one.

> The other reason is bind mounts - you can create a loop by bind mounting some directory into a subdirectory of itself:

The suggested alternative is to do an illegal rename(2) across the suspected FS boundary and check for EXDEV.

Is this approach portable to the general unix?

> simplicity is a mirage

**Comment by verygreen** [comment]
Are you sure rename would protect you from bind mount in the same fs?

I am surprised that st_dev value would be unstable without reboot in between, that should not really happen because the value is derived from internal kernel device value hat does stay stable as long as the fs is mounted.

As for bind mount - the example given is certainly incorrect - there is no inheritance of subdirectory mount into the mount itself for exactly the reason stated - to avoid recursive loops:
```
[root@fedora1 tmp]# mount . subdir --bind
[root@fedora1 tmp]# ls subdir
d52a.sanity       f400a.sanity        lustre-log.1468570823.194805  subdir
debug             gEjLhz              lustre-log.1468570825.225640  test_logs
f127b.sanity.tmp  lnet_stats.out      sanity.log
f128.sanity.log   lnet_stats.sys_tmp  sanityN-test_234.parameters
[root@fedora1 tmp]# ls subdir/subdir/
[root@fedora1 tmp]# ls subdir/subdir/
```

**Comment by verygreen** [comment]
Also, rename does not help you as I suspected because it IS the same fs:
```
[root@fedora1 tmp]# mv sanity.log subdir/
mv: 'sanity.log' and 'subdir/sanity.log' are the same file
[root@fedora1 tmp]# mv sanity.log subdir/aaa
[root@fedora1 tmp]# 
```

**Comment by verygreen** [comment]
if I were protecting against recursive bind mounts, I'd probably do a lookup based on st_dev + inode number for every directory (no recursive mounted files) traversed.
If we have already archived this directory before somewhere above in the path - then we are in a recursive mount situation -- print a warning and bail out.

**Comment by verygreen** [comment]
I was wrong, btw about the rename, it does protect you. I just forgot that gnu mv resorts to copy if rename(2) fails:
```
rename("subdir/aaa", "sanity.log")      = -1 EXDEV (Invalid cross-device link)
```

**Comment by enkore** [comment]
Testing:

```
├─/tmp                         tmpfs       tmpfs       rw
│ └─/tmp/asdftmp               tmpfs       tmpfs       rw

/> ll tmp | wc -l    
82
/> ll tmp/asdftmp | wc -l
82
```

```
$ borg create -svp tmp/repo::archive tmp
------------------------------------------------------------------------------                                                               
Archive name: archive
Archive fingerprint: 555c5cdce14373c4a31b61baab0f9e8c4598ba59689e744213619da42372de4c
Time (start): Fri, 2016-07-15 17:33:56
Time (end):   Fri, 2016-07-15 17:33:57
Duration: 0.56 seconds
Number of files: 953
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               71.78 MB             71.78 MB             33.85 MB
All archives:               71.78 MB             71.78 MB             33.85 MB

                       Unique chunks         Total chunks
Chunk index:                     178                  897
------------------------------------------------------------------------------
```

Terminates, no loop.

```
$ borg create -svpx tmp/repo::archive2 tmp
------------------------------------------------------------------------------                                                               
Archive name: archive2
Archive fingerprint: d26fadb144c65afc7cadd73ea55e68a27a67abfed3c05b620c2506be6a51e652
Time (start): Fri, 2016-07-15 17:35:05
Time (end):   Fri, 2016-07-15 17:35:05
Duration: 0.13 seconds
Number of files: 953
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               71.78 MB             71.78 MB            320.54 kB
All archives:              143.55 MB            143.56 MB             34.17 MB

                       Unique chunks         Total chunks
Chunk index:                     191                 1792
------------------------------------------------------------------------------
```

**Comment by enkore** [comment]
Aha. It seems that bind mounts do, in fact, *not* loop. The "looping" directory contains the contents of the mountpoint *before* it was mounted.

**Comment by verygreen** [comment]
I guess the loop checking with a lookup might still be useful even if bind mount are safe if we want to protect against an attacker that creates a seemingly endless loop with renames as borg operates.

I.e.:
I have a big / hierarchy with say a b c, all deep inside.
as borg entered a/z, attacker performs rename("a/z", "b/z"); rename("a", "b/z/a"); and so on multiple times to keep the borg in a loop.

**Comment by enkore** [comment]
Hm, generic just-in-time loop creation could only be defeated by a lookup table, so storing at least the (dev, ino[, gen]) tuple.

**Comment by verygreen** [comment]
I think this is already stored for file caching purposes anyway?

**Comment by enkore** [comment]
The files cache is optional for memory usage reasons, but could be used if wanted.

I'm thinking -- just guard the stack and limit recursion depth safely. That way Borg always terminates sooner or later.

**Comment by enkore** [comment]
Relating to "NFS st_dev" only [this](https://bugzilla.redhat.com/show_bug.cgi?id=533569) turned up.

**Comment by enkore** [comment]
Recursion limit is -> #380 

Close this, resolved / not a problem?
