### ISSUE TITLE
windows: backup and extract ADS

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1342]
Alternate Data Streams (ADS) are the Windows equivalent of resource forks (and/or extended attributes, depending on platform and the moon-phase when you're asking the question ;)

Support for these shall be added to the borg.xattr module.

**Comment by ThomasWaldmann** [comment]
isn't there the big difference that a ADS can contain lots of data? size like the regular file contents?

**Comment by enkore** [comment]
How large xattrs can be depends completely on the system and FS. Linux has a limit of 64K here, I think some file systems on Linux have further restrictions. On the other Hand, OSX resource forks (which are read through the xattr API as well #51) have no length limit, while Solaris has no limits at all (#1337).

Typical examples of ADS aren't very large.

**Comment by Anakonda** [comment]
In theory ADS can store any data that file can - if you open a file it opens ADS without name. eg `filename` is `filename::$DATA`.
I would try storing them as seperate files. Note that when trying to extract `file:stream` created in non-windows `file` would have to be created too/first.

**Comment by enkore** [comment]
Hm, maybe just introduce an Item attribute like "subitems" with a list of items that are encapsulated by the parent item. Then an ADS would just be a regular item in that list, with chunked contents (so no problems with large ADS). This approach would also allow storing what Solaris does.

**Comment by ThomasWaldmann** [comment]
Doesn't that mean that the LIST ("directory") of streams can't be more than 64K, but the stream itself is unbounded?

**Comment by enkore** [comment]
Hm, didn't read it like this, but seems more likely.

> SMB 3.0 supports list **(**of streams**)** less than or equal to 64K.

**Comment by enkore** [comment]
More research

- When using ntfs(-3g) xattr's are mapped to ADS, specifically the `user.` namespace is (everything else is empty)
  - ADS larger than 64K are not accessible on Linux (*Argument list too long*)
  - I.e. the ADS "asdf" becomes the xattr "user.asdf" on Linux
  - An ADS larger than 64K can be listed, but not retrieved.
- NTFS EA are not accessible on Linux (and are only used by Windows 8 and up for some system files apparently)

**Comment by tk7r** [comment]
@enkore : MacOSX xattr is NOT limited to 4K. Quite contrary.
I have tested it on MacOSX 10.7 and could set more than 100 KByte as an attribute. (limited by the command line size limit)
In my tests on MacOSX 10.11 i have found a file "in the wild" with more  than 300KByte as an attribute.
And i have written a little c program to get the xattr limit from MacOSX itself. It's limited to 2^31 Byte per file on MacOSX 10.11.

**Comment by enkore** [comment]
Hm, interesting. Seems that there is no reliance on sources there. According to the man page it should be....

>      The maximum supported size of extended attribute can be found out using pathconf(2) with
>     _PC_XATTR_SIZE_BITS option.

**Comment by tk7r** [comment]
I'll attach my test program. rename the file to have a ".c" extension; compile with
$ gcc -o test_resource_fork_size test_resource_fork_size.c
and run it
[test_resource_fork_size.txt](https://github.com/borgbackup/borg/files/379208/test_resource_fork_size.txt)

**Comment by tk7r** [comment]
I ran  test_resource_fork_size on MacOSX 10.7 : Limit is 2^18 Byte there. = 256KByte

**Comment by enkore** [comment]
Interesting. Did this evolve over time? I can't find the original article mentioning the 4K limit on OSX, but [this one](http://blog.fosketts.net/2009/09/11/bizarre-hfs-tricks-in-mac-os-x-10-6-snow-leopard/) for 10.6 turned up mentioning 128 bytes per xattr.

**Comment by tk7r** [comment]
i have found the 4k limit article too... but reading the apple documents for Mac OS X 10.6 has a limit of 128 KByte (not byte). - i will try to take some time to install some ancient Mac OS X releases and test the limits/xattr interface there - is there something else that i can/should test?

**Comment by tk7r** [comment]
i have found an ancient system with MacOSX 10.6 : xattrs seem to be limited to 4KByte there. (pathconf is there but doesn't know the _PC_XATTR_SIZE_BITS flag).
my conclusion: extended attributes on MacOSX are fully supported in borgbackup since MacOSX 10.6 - restoring files on at least the same MacOSX version should keep you safe.

**Comment by Anakonda** [comment]
So did we "decide" something? ATM I have them as normal files. That also have the benefit of being able to extract only certain streams of file.

**Comment by enkore** [comment]
Works for me

**Comment by enkore** [comment]
Fixed by #1411
