### ISSUE TITLE
Show compression stats after create

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#1349]
It would be nice if borg info and other commands that prints a summary could also be able to show which compression algorithms are used and the compression ratio for the data they manage.
This way one can see what are their differences and choose the right one for his needs.

**Comment by enkore** [comment]
That would require reading all data, so it's not really practical.

**Comment by FabioPedretti** [comment]
Maybe just after a create? Or as an option with info.

**Comment by gaitjan** [comment]
So I assume that the stats printed at the end of 'borg create ... --stats ...' can only be printed as a result of the create?
Those stats aren't saved as metadata in the repository/archive?

**Comment by enkore** [comment]
Obsolete since the compr patterns were removed. `--compression auto,zlib/lzma/*` stats would probably be #2209
