### ISSUE TITLE
network error - borg behaviour

### ISSUE THREAD

**Issue by rootbert** [borgbackup/borg#1350]
while testing the behaviour of borg during network problems I encountered the following problem:
during a "borg create --compression lz4 -v --stats --exclude /var/lib/lxcfs/cgroup --exclude /var/lib/lxc --exclude /var/lib/lxd backupuser@192.168.200.1:/backups/var /var" I did a "iptables -I OUTPUT --dest 192.168.200.1 --dport 22 -j REJECT" to simulate some errors in the network (-j DROP would be my next test). The borg backup command now hangs and does not die after some timeout (1 hour at the moment). 

Did I miss some timeout options in the docs? Is this expected behaviour? IMHO the client initiated command should die after some time.

**Comment by enkore** [comment]
If the SSH tunnel doesn't break Borg won't break. I.e. if you get the same behaviour on a plain SSH session then it's not a Borg issue.

Also see #636

**Comment by rootbert** [comment]
ah, ok, thanks for the input. For reference: ssh options ServerAliveInterval and ServerAliveCountMax on client side and TCPKeepAlive, ClientAliveInterval and ClientAliveCountMax on the server side are the relevant configuration options.
