### ISSUE TITLE
Add debug-obj-refcount debug command.

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#1352]
Talking about quick recovery of corrupted repositories i learned that there is debug-delete-obj. It seems in some situations it would be nice to be able to check the refcount of an object before deleting it.

**Comment by enkore** [comment]
A basic version could use the regular cache.

One could also imagine a more elaborate version searching per-archive chunks if the main cache doesn't exist because e.g. resync fails.

**Comment by ThomasWaldmann** [comment]
fixed by #1732.
