### ISSUE TITLE
test_non_ascii_acl failing

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#1361]
`E       AssertionError: b'user:\xc3\xbcbel:rw-:666' not found in b'user::rw-\nuser:666:rw-:666\ngroup::r--\ngroup:666:rw-:666\nmask::rw-\nother::---'` from [src/borg/testsuite/platform.py:90](https://github.com/borgbackup/borg/blob/504af0206d3abb0dba1a20e9519d23eb0ed15957/src/borg/testsuite/platform.py#L90)

I'm running this without fakeroot BTW (for #1359 testing). It is consistent across filesystems (edit: or maybe not, but it occurs on a lot of them including ext4).

**Comment by ThomasWaldmann** [comment]
maybe this test requires a system user "übel".

**Comment by enkore** [comment]
This test only passes in the vagrant boxes iirc.

Add a check that the user dübel exist and pytest.skip otherwise?

**Comment by PlasmaPower** [comment]
Oh, makes sense. I missed that comment. I'll add a PR to check if the user exists first.
