### ISSUE TITLE
Compression excludes file types

### ISSUE THREAD

**Issue by artelse** [borgbackup/borg#1372]
Would be nice to have the option to exclude certain file types from compression: e.g. .zip, .rar, .7v, .jpg, mp3,4, etc. This might speed up initial backups substantially.
Great tool btw, have started playing to backup to a remote raspberry pi and so far works!

**Comment by ThomasWaldmann** [comment]
borg 1.1 (after release or current master branch) has configurable compression (by extension + also by autodetect).

**Comment by enkore** [comment]
#810 #1007
