### ISSUE TITLE
try out FUSE for macOS (osxfuse) 3.4.x

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1378]
If you are a Mac OS X based borg user, you could just try if the latest release (3.4.1) works as expected.
Try it manually and also run our unit tests to see if everything works as expected.

On the vagrant machines I use for testing and also for building the borg-macosx64 binary,  I currently still have osxfuse 3.3.x. It would be good to know if it is safe to upgrade them to FUSE for macOS 3.4.x.

**Comment by devrando** [comment]
I can confirm that current master works with osxfuse 3.4.1 (tested on el capitan).
Tested manually.

**Comment by ThomasWaldmann** [comment]
Maybe try running it without fakeroot (or as real root). IIRC some tests are not compatible with fakeroot.

**Comment by ThomasWaldmann** [comment]
I'll try it in the vagrant VM...
