### ISSUE TITLE
codecov.io stopped working

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1381]
we used to have:
- patch coverage
- overall coverage
- travis

but currently we only have travis, why?

**Comment by PlasmaPower** [comment]
Codecov seems to be setup and working. Is it replacing coveralls, and is this issue still relevant?

**Comment by enkore** [comment]
My bad, I can't tell all these `*cov*` services apart :)

Usually we'd have the three check lines and the comments from the bot with more details, but all of them are absent, e.g. https://github.com/borgbackup/borg/pull/1383

**Comment by PlasmaPower** [comment]
It seems to be working again, e.g. #1387.
