### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#1382]
`grep -I -l -- $'[ \t]$' $(git ls-files .)` gives a list of files with trailing whitespace:

```
CHANGES.rst
README.rst
docs/changes.rst
docs/deployment.rst
docs/installation.rst
docs/internals.rst
docs/misc/internals-picture.txt
docs/misc/prune-example.txt
src/borg/platform/posix.pyx
tox.ini
```

I'd sort them into four different categories:

- Code
- Configuration
- Documentation
- Documentation diagrams

I'd say we should remove all but the diagrams. Opinions? (I'll make a PR once we decide which to remove)

**Comment by ThomasWaldmann** [comment]
Maybe it is easier to say if one just removes all trailing WS, makes a PR (first against 1.0-maint, then merge that into master, then redo the process on master for the remainder). In the PR it is easier to see if all changes are OK.

**Comment by ThomasWaldmann** [comment]
merge is done.
