### ISSUE TITLE
Vagrant box issues

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#1384]
I'm having a hard time getting a lot of boxes working for #1359.

`trusty64`:

Works perfectly.

`centos7_64`:

This warning is repeated until it reaches the maximum tries:

```
centos7_64: Warning: Authentication failure. Retrying...
```

In my system log (`journalctl -e`) I get this spammed:

```
ssh-agent[456]: error: Unknown message 1
```

If I kill ssh-agent, I still get the error but without the system log messages. Anyone else experienced this problem?

`centos6_{64,32}`:

```
==> centos6_64: Box 'centos6-64' could not be found. Attempting to find and install...
    centos6_64: Box Provider: virtualbox
    centos6_64: Box Version: >= 0
==> centos6_64: Box file was not detected as metadata. Adding it directly...
==> centos6_64: Adding box 'centos6-64' (v0) for provider: virtualbox
    centos6_64: Downloading: centos6-64
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/lee/python-projects/borg/centos6-64
```

`darwin64`:

Works with virtualbox extensions (not open source, free for personal use). However, it runs out of resources a lot making testing a pain.

The boxes listed here are the only ones I've tried, I'll update as I try more. Has anybody actually tested that all the boxes work?

**Comment by ThomasWaldmann** [comment]
the centos6 boxes are not online, I just installed them locally. IIRC i did not find something good back then when I made them, but maybe the situation has changed meanwhile.

the centos7 box works for me. do you maybe have some special ssh configuration for localhost?

**Comment by PlasmaPower** [comment]
@ThomasWaldmann No configuration applies to anything but special hosts. Besides, I think Vagrant passes in it's own SSH config (`vagrant ssh-config [up-host]`).

**Comment by PlasmaPower** [comment]
Well this doesn't look like a Vagrantfile issue, so I'm going to open this over at the vagrant github.

**Comment by PlasmaPower** [comment]
For future reference, this is a problem with vagrant 1.8.5 which has been fixed by 1.8.6 (not yet released).

**Comment by walkertraylor** [comment]
I updated the Vagrantfile to use community centos6 images (to enable them to automatically download with a vagrant up,) pending for request.

**Comment by walkertraylor** [comment]
Vagrantfile has been updated to use community centos6 images to enable them to automatically download with a "vagrant up."
