### ISSUE TITLE
not enough space for a 2nd backup

### ISSUE THREAD

**Issue by sixpointzero** [borgbackup/borg#1385]
I have a single 1TB external hard disk and my first backup was approximately 850GB. I read the docs and I realized that borg creates a 2nd backup by using the older backup which, although might be faster, consumes the same amount of space (assuming the data hasn't changed much). I tried to overwrite the original backup but that didn't work.
How can I create subsequent backups on the same external hard disk without running out of disk space?

**Comment by ThomasWaldmann** [comment]
That sounds unusual. Usually a 2nd backup only consumer however much has changed in your data.

Can you please add borgbackup version, OS details, the precise command lines you used, etc.?

Between the 1st and 2nd backup of this data set on this machine, did you do more than 8 backup of other data sets on this machine with borg?

**Comment by enkore** [comment]
>  read the docs and I realized that borg creates a 2nd backup by using the older backup which, although might be faster, consumes the same amount of space (assuming the data hasn't changed much) 

This sounds like a misunderstanding. Borg uses all data in the repository to deduplicate any new data that should be stored, and that makes it use much less space than more traditional programs (full or incremental).

> Between the 1st and 2nd backup of this data set on this machine, did you do more than 8 backup of other data sets on this machine with borg?

A cold cache would make it slow, but not make it use more space.

**Comment by ThomasWaldmann** [comment]
If the data is compressible and one uses compression (and lz4 can always be used, it is very fast), even more will fit.

**Comment by sixpointzero** [comment]
After completing the backup, I think it was indeed a misunderstanding like @enkore  said. Still, because @ThomasWaldmann asked, I'm using `borg 1.0.6` and `Linux 4.4.15-1-lts x86_64 GNU/Linux` on Arch Linux. However, I'm still a bit confused about how borg works. Here's what happened:

    ~ → borg list /run/media/carbon/backup/
    user                                 Tue, 2016-07-26 16:53:23
    data.checkpoint                      Tue, 2016-07-26 21:48:44
    data.checkpoint.1                    Tue, 2016-07-26 22:18:58
    data                                 Wed, 2016-07-27 15:35:18
    etc                                  Wed, 2016-07-27 17:36:55
    user1                                Wed, 2016-07-27 17:40:08


    ~ → borg info /run/media/carbon/backup/::user
    Name: user
    Fingerprint: 8a7ecb300e937fc7b855c9a1702f1d991b75852e48e720629f403277b9fe0804
    Hostname: europa
    Username: carbon
    Time (start): Tue, 2016-07-26 16:53:23
    Time (end):   Tue, 2016-07-26 17:26:36
    Command line: /usr/bin/borg create -vsp -C lz4 /run/media/carbon/backup::user /home/carbon/
    Number of files: 9863
    
                           Original size      Compressed size    Deduplicated size
    This archive:               34.86 GB             15.92 GB            162.64 MB
    All archives:                1.69 TB              1.63 TB            885.76 GB
    
                           Unique chunks         Total chunks
    Chunk index:                  402111               743476


    ~ → borg info /run/media/carbon/backup/::user1
    Name: user1
    Fingerprint: d63eb8ae571651c9f2f2fdb15de4a48131d51c584fe00e60f4572b158d0a7f57
    Hostname: europa
    Username: carbon
    Time (start): Wed, 2016-07-27 17:40:08
    Time (end):   Wed, 2016-07-27 17:41:26
    Command line: /usr/bin/borg create -vsp -C lz4 /run/media/carbon/backup::user1 /home/carbon/
    Number of files: 8033
    
                           Original size      Compressed size    Deduplicated size
    This archive:               34.82 GB             15.90 GB            142.35 MB
    All archives:                1.69 TB              1.63 TB            885.76 GB
    
                           Unique chunks         Total chunks
    Chunk index:                  402111               743476


    ~ → borg info /run/media/carbon/backup/::data
    Name: data
    Fingerprint: 8a77be8ff8e0307892ff37417687ee63dc08730bb9c501d29474142765f40e90
    Hostname: europa
    Username: carbon
    Time (start): Wed, 2016-07-27 15:35:18
    Time (end):   Wed, 2016-07-27 17:16:50
    Command line: /usr/bin/borg create -vsp -C lz4 /run/media/carbon/backup::data /data
    Number of files: 50158
    
                           Original size      Compressed size    Deduplicated size
    This archive:              887.36 GB            873.03 GB            164.63 GB
    All archives:                1.69 TB              1.63 TB            885.76 GB
    
                           Unique chunks         Total chunks
    Chunk index:                  402111               743476


    ~ → borg info /run/media/carbon/backup/::data.checkpoint
    Name: data.checkpoint
    Fingerprint: 6c24a85944f372dd3d12402ed3475c2add80b290f8a6ba253fb4f7e56ad39472
    Hostname: europa
    Username: carbon
    Time (start): Tue, 2016-07-26 21:48:44
    Time (end):   Tue, 2016-07-26 22:12:14
    Command line: /usr/bin/borg create -vsp -C lz4 /run/media/carbon/backup::data /data
    Number of files: 39
    
                           Original size      Compressed size    Deduplicated size
    This archive:               19.82 GB             19.87 GB            122.36 kB
    All archives:                1.69 TB              1.63 TB            885.76 GB
    
                           Unique chunks         Total chunks
    Chunk index:                  402111               743476


    ~ → borg info /run/media/carbon/backup/::data.checkpoint.1
    Name: data.checkpoint.1
    Fingerprint: eaf08f9d04626181703e6e03c14cfc785e5eb93de2c247588c8bdee892422111
    Hostname: europa
    Username: carbon
    Time (start): Tue, 2016-07-26 22:18:58
    Time (end):   Wed, 2016-07-27 15:19:03
    Command line: /usr/bin/borg create -vsp -C lz4 /run/media/carbon/backup::data /data
    Number of files: 28361
    
                           Original size      Compressed size    Deduplicated size
    This archive:              716.99 GB            707.98 GB              5.06 MB
    All archives:                1.69 TB              1.63 TB            885.76 GB
    
                           Unique chunks         Total chunks
    Chunk index:                  402111               743476


    ~ → borg info /run/media/carbon/backup/::etc
    Name: etc
    Fingerprint: c6e60b87745a97131764c3d99717eb34817ce2cb7d8dabbd419afc25bbcd08e1
    Hostname: europa
    Username: carbon
    Time (start): Wed, 2016-07-27 17:36:55
    Time (end):   Wed, 2016-07-27 17:36:56
    Command line: /usr/bin/borg create -vsp -C lz4 /run/media/carbon/backup::etc /etc
    Number of files: 567
    
                           Original size      Compressed size    Deduplicated size
    This archive:               11.66 MB              5.17 MB              5.16 MB
    All archives:                1.69 TB              1.63 TB            885.76 GB
    
                           Unique chunks         Total chunks
    Chunk index:                  402111               743476
    ~ → 
I created three backups for `~/`, `/data`, and `/etc` with the archive names `user`, `data`, and `etc` respectively. I also created a 2nd backup for `~/` with the name `user1`. 

- What are `data.checkpoint` and `data.checkpoint.1`? The original size of `/data` was `887.36 GB` at the time and that is displayed correctly but what about the `19.82 GB` and `716.99 GB` on the checkpoints?
- What does `user1` contain? Does it contain only that part of `~/` that was different from the time when `user` was created? If yes, then why does it say that the archive size of `user1` is `34.82 GB`? Does it reflect the new size of `~/`? Can I see the actual size of `user1` assuming that it only stores the diffs?
- About the actual size of `user1`, how many subsequent backups would I be able to create before running out of disk space? What happens when I do? What should I delete?
- What do the deduplicated sizes of individual archives signify (such as `162.64 MB` for `user`)?

Sorry for bothering you with so many questions.

**Comment by ThomasWaldmann** [comment]
The user/user1/etc backup deduped quite ok.

Also, the data + checkpoints deduped against each other, which is expected as the checkpoint has a partial copy of the whole backup. You can remove the checkpoint archives now, just `borg delete` them.

Checkpoints are interrrupted, partial backups - kept there so the next try with same data does not need to retransmit all the data again (see also FAQ).

Also, I'ld advise you to add the date or datetime to your archive names,  giving them numbers is tedious (see docs for examples).

As you already used lz4 all the time, your storage medium is a bit tight spacewise. If you have almost 1TB of almost incompressible data, you can't expect to get many backups on a 1 TB disk (1TB HDD == ~931 GiB space).

If lz4 compresses that badly, using a higher compression algo like zlib is likely a futile attempt also - likely your input data is already compressed.

So, either reduce backup data set size (input) or get a bigger target disk.

**Comment by ThomasWaldmann** [comment]
The deduplicated size shown for an archive is the volume of unique chunks - chunks that are ONLY in that one archive.

Archives always contains all the files you saved into them, but they will reuse / share identical chunks with other archives.

**Comment by enkore** [comment]
> The deduplicated size shown for an archive is the volume of unique chunks - chunks that are ONLY in that one archive.

In other words, the "deduplicated size" column shows *actual* space usage of the archive or all archives. The leftmost, "original size" column shows the size of the archive or all archives when they would be extracted.

**Comment by sixpointzero** [comment]
> Checkpoints are interrrupted, partial backups - kept there so the next try with same data does not need to retransmit all the data again (see also FAQ).

I see. The backup was indeed interrupted two times. I deleted the checkpoints and now the deduplicated size of `data` makes sense but that of `user` and `user1` still doesn't. If deduplicated size (the actual size you say?) of `user` and `user1` is only `162 MB` and `142 MB`, where is the rest of the `~15GB` that was compressed and is supposedly saved?

> All archives contain all data. However, due to deduplication, that does not mean that all data is stored again and again. Every bit of data is only stored once, and all data is deduplicated, regardless of whether the same file appears twice in an archive or the same file appears many times in different archives.

So that means that I can delete `user` but `user1` would still have all the data that I saved from `~/`?

**Comment by enkore** [comment]
> So that means that I can delete user but user1 would still have all the data that I saved from ~/?

Yes, if you delete `user` that doesn't change anything with `user1`.

> If deduplicated size (the actual size you say?) of user and user1 is only 162 MB and 142 MB, where is the rest of the ~15GB that was compressed and is supposedly saved?

Because most of the data is deduplicated between the two archives it doesn't show up there (it's *only* the data that is used by *this archive* [and this archive alone]).

**Comment by sixpointzero** [comment]
I think I got it. Thanks for answering my questions and for creating such an awesome software.
