### ISSUE TITLE
minor doc tweaks on master

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#1390]
A couple suggestions for master (with reference to: http://borgbackup.readthedocs.io/en/latest/usage.html):
- [ ] borg list has an example (the last one) for showing diff. This should be removed since there is a dedicated borg diff command now;
- [ ] elaborate a bit more on _auto,C[,L]_ heuristic: based on file extension, file type or it tries to compress and use none if the compressed is just X% smaller?

Thanks

**Comment by ThomasWaldmann** [comment]
borg list: true, it is not needed any more.

auto,C,L heuristics:
- if you just give that as a param to `borg create`, it will not look at the filename, but just try to compress with lz4 to decide about compressibility. if it compresses ok, it will then compress with the given C,L compression algo/level. if it does not compress, it will save the content uncompressed.
lz4 is very fast, so we don't waste many cycles by using it that way.
- if you use it in a compression config, the above mechanism will be used after matching filename/extension.
