### ISSUE TITLE
duplicated paths

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#1404]
No idea if this is a real issue, but if I specify the same path twice:
- it get processed twice (time to do the backup, size and number or files reported in the summary);
- borg list archive shows it twice;
- borg mount shows it only once.

This may also happen if a path is under another one (e.g.: /var /var/log ), but I didn't try this.

Maybe it could show a warning when a duplicate path get detected (adding duplicate paths is most likely a user error) and process it only once?

**Comment by ThomasWaldmann** [comment]
well, the simplest cases could be easily catched.
but there could be more complex pathes pointing to same stuff, bind mounts etc.
and, as you noted: containment.

if different pathes point to same resource, we would also need to decide which one to skip.

so I'ld say: just don't do that. usually you have a relatively small amount of pathes you give to borg, so it shouldn't be too hard to avoid unwanted duplicates.

btw, in a script, you easily can format like this:
```
borg create ... \
    first/path \
    second/path \
    third/path 
```

**Comment by PlasmaPower** [comment]
Also, if you have an array of files you'd like to send to borg without duplicates, try `borg [command] -- $(readlink -f "${files[@]}" | sort -u)`

(if it's not an array replace `"${files[@]}"` with just `$files`)

**Comment by enkore** [comment]
Even good ol' `tar(1)` behaves like this.

Close?
