### ISSUE TITLE
Consider using os.path.expandpath or equivalent

### ISSUE THREAD

**Issue by jody-frankowski** [borgbackup/borg#1405]
It is currently hard to use the borg command with variables that contain the `~` sign because it is not trivial to expand the variable and borg doesn't expand its arguments.
Example:

```
# This variable could be sourced from another file in order to reuse the script
to_backup="~/a \
~/b \
"

borg create -v --stats --progress --list -C lz4 borg::`date` $to_backup
```

**Comment by enkore** [comment]
This really is a shell-related issue. You probably want to do something along the lines of

```
to_backup=(
        ~/a
        ~/b
)

python  borg ... ${to_backup[*]}
```

Expanding `~` has also the issue that `~` is valid file name.

Technically you can also expand it yourself, e.g. http://stackoverflow.com/a/27485157/675646

**Comment by jody-frankowski** [comment]
Thank you for your answer.
How would you handle this for exclusion? --exclude doesn't accept a list of arguments, and --exclude-from will need a file with expanded paths.

**Comment by PlasmaPower** [comment]
@jody-frankowski Try `${!variable}` to have Bash or ZSH expand a variable for you.

**Comment by enkore** [comment]
> How would you handle this for exclusion?

You can always write something like

```
to_backup = (
--exclude something/to/exclude
something/to/backup
--exclude something/to/backup/but/not/this/folder
)
```

**Comment by jody-frankowski** [comment]
Thank you for your answers guys.
