### ISSUE TITLE
borg extract fails to parse paths with spaces in filename

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#141]
Looks like borg extract does not know how to deal properly with spaces (or parenthesis?) in path arguments.  Or possibly that it doesn't deal properly with the path options at all.  All of the following result in no output:

```
borg extract --verbose ssh://backups.example.com/backup/borgmatic.borg::archive-name /cygdrive/c/Program\ Files\ \(x86\)/Steam/

borg extract --verbose ssh://backups.example.com/backup/borgmatic.borg::archive-name "/cygdrive/c/Program Files (x86)/Steam/"

borg extract --verbose ssh://backups.example.com/backup/borgmatic.borg::archive-name /cygdrive/c/
```

However, if I don't pass in any path at all, extract works.

**Comment by ThomasWaldmann** [comment]
Can you please additionally try 'single quotes'?

**Comment by tgharold** [comment]
No luck with using single-quotes either.  I think borg is just not parsing / matching the PATH at all.  If any PATH value is present, nothing gets extracted.

(I vaguely remember attic having this issue and it never being fixed, but I could be wrong.)

**Comment by ThomasWaldmann** [comment]
@tgharold I'll try if I can fix it before next release (soon).

**Comment by ThomasWaldmann** [comment]
Note: works on linux. outer single quotes work, backslashes before spaces or parens work also.

**Comment by ThomasWaldmann** [comment]
I compared how sys.argv looks on linux and cygwin, looked same. So it is rather unclear to me how this can happen.

**Comment by tgharold** [comment]
Yes, I'm running the borg command in the cygwin (64bit) mintty terminal.  

`C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -`

**Comment by ThomasWaldmann** [comment]
Hmm, is this maybe similar to #143 ?

**Comment by ThomasWaldmann** [comment]
@tgharold can you check the end of #338 - maybe same cause for you?

**Comment by ThomasWaldmann** [comment]
no response, closing.

**Comment by knutov** [comment]
I can confirm - all variants of quoting spaces are not working on Mac.

**Comment by knutov** [comment]
I can confirm - all variants of quoting spaces are not working on Mac.

```
borg extract ...  "Users/user/Library/Application\ Support/Sublime\ Text"

Include pattern 'Users/user/Library/Application\' never matched.
Include pattern 'Support/Sublime\' never matched.
Include pattern 'Text' never matched.
```

Same with single quotes and without backslashes.

**Comment by ThomasWaldmann** [comment]
@knutov interesting. i'll try this now on my M1 macbook air, let's see...

**Comment by ThomasWaldmann** [comment]
Can't reproduce:
```
tw@mba2020 /tmp % borg init -e none repo                                                   
tw@mba2020 /tmp % borg create repo::arch /Users/tw/Library/Application*Support/Numi   
tw@mba2020 /tmp % borg list repo::arch                                            
drwxr-xr-x tw     staff         0 Sat, 2021-09-04 22:52:39 Users/tw/Library/Application Support/Numi
-rw-r--r-- tw     staff       873 Thu, 2021-09-02 10:21:36 Users/tw/Library/Application Support/Numi/525619.spadl
-rw-r--r-- tw     staff      1431 Sat, 2021-09-04 22:52:36 Users/tw/Library/Application Support/Numi/com.dmitrynikolaev.numi.ipak
-rw-r--r-- tw     staff      1545 Sat, 2021-09-04 22:52:39 Users/tw/Library/Application Support/Numi/525619.padl
tw@mba2020 /tmp % borg extract --list repo::arch 'Users/tw/Library/Application Support/Numi'
Users/tw/Library/Application Support/Numi
Users/tw/Library/Application Support/Numi/525619.spadl
Users/tw/Library/Application Support/Numi/com.dmitrynikolaev.numi.ipak
Users/tw/Library/Application Support/Numi/525619.padl
tw@mba2020 /tmp % ls -lR Users 
total 0
drwx------  3 tw  wheel  96 Sep 12 14:30 tw

Users/tw:
total 0
drwx------  3 tw  wheel  96 Sep 12 14:30 Library

Users/tw/Library:
total 0
drwx------  3 tw  wheel  96 Sep 12 14:30 Application Support

Users/tw/Library/Application Support:
total 0
drwxr-xr-x  5 tw  staff  160 Sep  4 22:52 Numi

Users/tw/Library/Application Support/Numi:
total 24
-rw-r--r--  1 tw  staff  1545 Sep  4 22:52 525619.padl
-rw-r--r--  1 tw  staff   873 Sep  2 10:21 525619.spadl
-rw-r--r--  1 tw  staff  1431 Sep  4 22:52 com.dmitrynikolaev.numi.ipak
```

**Comment by ThomasWaldmann** [comment]
Ah, I found the issue: of course you must not use quotes **and** backslash at the same time.

**Comment by ThomasWaldmann** [comment]
@knutov can you check our docs and maybe do a PR if they are not clear enough about this?

Not specifically a borg issue (but rather shell / quoting), but widespread enough to still mention it.

**Comment by knutov** [comment]
Thanks, I will check it
