### ISSUE TITLE
borg binary tests failing on wheezy32

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#1416]
I originally found this while testing my multiple filesystem code of course, but I destroyed the box and replicated it on master. I haven't seen these errors on any other distro. Here's the log: https://gist.github.com/c38dd79e6a271bc05ac68b2739626d12
. For ease of reading, here's just the failures section of Python 3.4: https://gist.github.com/832ae39ab55c8d9085ed4986f90030f3. It should be noted that other errors might be occurring on different versions.

**Comment by ThomasWaldmann** [comment]
Are you sure your borg.exe binary was up-to-date (corresponding to your source)?
If it is a totally fresh machine, this should be always the case, but otherwise might be an issue.

**Comment by PlasmaPower** [comment]
I destroyed the box immediately before checking out master (and pulling), where I did `vagrant up wheezy32` and the errors still occurred. In general, I always destroy a box before pulling it up again to run tests.

**Comment by PlasmaPower** [comment]
You're right that the errors do look like a version mismatch though.

**Comment by PlasmaPower** [comment]
Can you replicate this with `vagrant destroy wheezy32 -f && vagrant up wheezy32`?

**Comment by PlasmaPower** [comment]
I've just replicated this in a fresh arch chroot! I've saved my session with `script`, once the tests are finished I'll upload the log.

**Comment by ThomasWaldmann** [comment]
```
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded: ignored.
```
likely this in the command output is spoiling a lot of tests.

**Comment by PlasmaPower** [comment]
I didn't catch that, good eye. That would make sense. Do you have any idea why that error occurs? It seems odd given that fakeroot is supplied by an official debian package.

**Comment by PlasmaPower** [comment]
Wait a minute, my tests on the `vagrant-multiple-fs` branch have the same problem and don't use fakeroot. I'll see if I can get a log of that.

**Comment by PlasmaPower** [comment]
In case anyone wants logs from it in a fresh chroot or replication instructions: https://gist.github.com/PlasmaPower/4b0fef40059685e81b8d3fcea816832f (contains terminal escape codes, use `curl -L https://gist.githubusercontent.com/PlasmaPower/4b0fef40059685e81b8d3fcea816832f/raw/ca3fa110090b2941532e2b31944deea4e2727401/wheezy32-test.log` to view properly).

**Comment by ThomasWaldmann** [comment]
I can reproduce on wheezy32.
One just needs to start `fakeroot -u ./borg.exe --version` to reproduce. Freshly built exe.

**Comment by ThomasWaldmann** [comment]
```
(borg-env) vagrant@vagrant:/vagrant/borg$ fakeroot -u ./borg.exe --version
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded: ignored.
borg.exe 1.1.dev333+ngd5edaa5

(borg-env) vagrant@vagrant:/vagrant/borg$ fakeroot -u -l /usr/lib/i386-linux-gnu/libfakeroot/libfakeroot-sysv.so ./borg.exe --version
borg.exe 1.1.dev333+ngd5edaa5
```
Doesn't fakeroot find its own stuff?

**Comment by PlasmaPower** [comment]
@ThomasWaldmann yeah that was what I thought too. However, `cannot be preloaded` is a lot more general than not found so I think it might be another problem.

**Comment by ThomasWaldmann** [comment]
But why does it work if one just gives the right file explicitly?

**Comment by enkore** [comment]
Take a peek at the process environment (/proc/[pid]/environ). LD_PRELOAD must be an absolute path AFAIK.

**Comment by ThomasWaldmann** [comment]
What I am also wondering: that was not a problem for 1.0-maint, so what is different in master that influences this?

**Comment by ThomasWaldmann** [comment]
```
root@vagrant:~# ps aux|grep borg
vagrant  12310  0.0  0.2   4388  1320 pts/0    S+   23:16   0:00 /bin/bash /usr/bin/fakeroot -u borg.exe init repo2
vagrant  12325  0.1  0.2   2640  1172 pts/0    S+   23:16   0:00 borg.exe init repo2
vagrant  12326  0.3  2.8  22860 14864 pts/0    S+   23:16   0:00 borg.exe init repo2

root@vagrant:~# cat /proc/12310/environ |strings|grep LD_
LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu/libfakeroot

root@vagrant:~# cat /proc/12325/environ |strings|grep LD_
LD_PRELOAD=libfakeroot-sysv.so
LD_LIBRARY_PATH=/usr/lib/i386-linux-gnu/libfakeroot:/usr/lib64/libfakeroot:/usr/lib32/libfakeroot:/usr/lib/i386-linux-gnu/libfakeroot

root@vagrant:~# cat /proc/12325/environ |strings|grep FAKE
FAKEROOTKEY=1137788455
FAKED_MODE=unknown-is-real

root@vagrant:~# cat /proc/12326/environ |strings|grep LD_
LD_PRELOAD=libfakeroot-sysv.so
LD_LIBRARY_PATH=/tmp/_MEIMCnUPr

root@vagrant:~# cat /proc/12326/environ |strings|grep FAKE
FAKEROOTKEY=1137788455
FAKED_MODE=unknown-is-real
```

Looks like pyinstaller destroying the LD_LIBRARY_PATH?

**Comment by ThomasWaldmann** [comment]
But I use same pyinstaller v3.1.1 git tag in master and in 1.0-maint...

**Comment by enkore** [comment]
Are the machines identical?

**Comment by ThomasWaldmann** [comment]
Same wheezy32 vagrant VM.

**Comment by ThomasWaldmann** [comment]
https://github.com/pyinstaller/pyinstaller/issues/1759

**Comment by ThomasWaldmann** [comment]
Hmm, I tried the 1.0.7rc2 release binaries and the built master binary: both emit the error messages on stderr when called with fakeroot -u. So maybe the difference is the test environment, whether it stumbles over the stderr output or not.

**Comment by ThomasWaldmann** [comment]
1.0-maint:
- borg list emits str output via print() - on sys.stdout.

master:
- borg list has some hack to write bytes to sys.stdout.buffer or decoded to sys.stdout if it is not a file, but e.g. StringIO, see https://github.com/borgbackup/borg/blob/master/src/borg/archiver.py#L782

**Comment by ThomasWaldmann** [comment]
I still could not find out why the tests somehow work on 1.0-maint although there is the same fakeroot issue as on master. But I made https://github.com/pyinstaller/pyinstaller/pull/2148 to hopefully fix the root cause of the fakeroot issue. It also enables us to fork ssh with a "as we got it" LDLP (not just with empty LDLP as we do it now).
