### ISSUE TITLE
look at new xattr stuff in python 3.3

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#142]
it's now included in python, maybe we can rid of some own code?

**Comment by oderwat** [comment]
I run python 3.2 and don't want to change that...

**Comment by RonnyPfannschmidt** [comment]
not that python 3.2 is broken for many practical concerns

**Comment by oderwat** [comment]
We have some servers on debian wheezy and I don't feel like compiling python 3.4 just for borg. Same goes for upgrading the distro to jessie.

**Comment by RonnyPfannschmidt** [comment]
ah, "damn" always the enterprise distros

**Comment by ThomasWaldmann** [comment]
killing 3.2 is currently scheduled for 1.0 milestone.

**Comment by ThomasWaldmann** [comment]
merged into #113, closing this one.

**Comment by anarcat** [comment]
removed milestone here, added it to #113.
