### ISSUE TITLE
Use repository as source for backups

### ISSUE THREAD

**Issue by njor** [borgbackup/borg#1421]
Hi, I would like to propose a feature: the ability to use existing archives in a repository as the _source_ for backups made to another repository, instead of the filesystem. Instead of the following command line:
`borg create /dest/repo::dest-archive /source/path`
... one could use:
`borg create /dest/repo::dest-archive /source/repo::source-archive`
... and that would just replicate the source archive into the destination repository.

The point is to optimize the use of two (or more) different backups of the same data. It is already possible to have redundant backups by creating two different archives in different repositories from the filesystem, but there are advantages of using an existing repository as source:

- Performance: no need to walk the whole file tree to look for file changes again, nor to do the de-duplication or even to compress the data again, as all of this work has already been done in the source repository, and that data can be used to speedup subsequent backups of the same data. This would be especially useful when the duplication is important, or if using slow compression like glib or lzma.
- Better resilience for multiple snapshots: when doing some backups on a support that is not always available (like a network with an unpredictable connexion, or an external drive that can be unplugged at times), this allows to keep snapshots of the data even at periods when the destination repository is not available. Let’s say I have some data that is backed up every n hours on both a local and a network repository, if at backup time the network is not available, I can still backup on the local repository anyways, and whenever the network becomes available again, I can just "push" all the intermediate snapshots to the remote repository. That way all intermediate snapshots are still saved on all the repositories.

**Comment by enkore** [comment]
Hi njor, this has been brought up before in #895 and #1098

**Comment by njor** [comment]
Hi @enkore.
I don’t know if it is exactly the same thing. As I understand it, the merge feature proposed would be especially useful in cases where files can be hardlinked (that is, when two repositories are on the same disk), and the recreate feature allows to rewrite existing archives in a repository to recompress / rechunkify them.

My proposal takes place at the time when new archives are created, and can be used even if the target and source repositories have not been "linked" together in any way.
It also seems simpler to implement (well, maybe ^^), as only the "read files on disk and chunk / compress them" part of archive creation has to be modified. The burden of managing archives names and stuff rests on the user.

If that proposal is accepted, I could try to work on it (but I’d need some help).

**Comment by enkore** [comment]
#895 is a special case / optimization (and thus should be, if implemented, be transparent to the user) of this:

> Possibly add a --target option to not replace the source archive -- with the target possibly in another Repo (better than "cp" due to full integrity checking, and deduplication at the target)

---

> If that proposal is accepted, I could try to work on it (but I’d need some help).

Sure. There's usually a few people around in the IRC channel.

**Comment by njor** [comment]
Ok, I cannot start working on it right now, but I’ll come and ask as soon as I can. :-)
