### ISSUE TITLE
Different return code when network issue encountered?

### ISSUE THREAD

**Issue by BonkaBonka** [borgbackup/borg#1424]
Hi!

It'd be really awesome if the return code could differentiate between a network failure and a more serious issue.

More specifically, my internet provider (TWC) is made almost completely of awful and often causes my connection to drop.  My VPN recovers pretty quickly after the cablemodem reboots but I'd like to be able to distinguish between a "permanent" error (XFS throwing a wobbly over a busted inode) and a transient (network) one that is probably safe to retry.

**Comment by PlasmaPower** [comment]
What type is the exception? I'd think it's a `socket.error`.

**Comment by PlasmaPower** [comment]
Nevermind, that's now an alias of `OSError`. Is it an instance of a `ConnectionError`?

**Comment by BonkaBonka** [comment]
Not sure.  When I ran with `--debug` I didn't see any particular Exception being thrown:

~~~~
$ borg create --compression=lz4 --one-file-system --lock-wait=3600 --debug --show-rc --progress --stats --list borgbox:/vol/testing/repo::initial /vol/filepile/
using builtin fallback logging configuration
bonka@borgbox's password: 
Remote: using builtin fallback logging configuration
Reading files cache ...
Processing files ...

[random progress while I wander over and unplug the cablemodem]

Remote: Write failed: Broken pipe
Connection closed by remote host
terminating with error status, rc 2
$
~~~~

That said, it took a good number of minutes for borg to realize the connection had gone away and if I plugged the modem back in prior to it noticing, it resumed.  I am impressed that OpenVPN and SSH recover so well.

I'm comfortable with y'all closing the ticket or tagging it as an "eventually" thing - in the face of real numbers, I feel like I'm borrowing trouble trying to over-engineer the failure handling.  :smile:

**Comment by enkore** [comment]
Look through the other SSH-related tickets, there are some tweakable settings in the SSH config so that the remote end hangs up on a broken connection sooner.

**Comment by PlasmaPower** [comment]
> Remote: Write failed: Broken pipe

Looks like it's a RPCError with a remote error of type BrokenPipeError (a subclass of ConnectionError, but we only get a string). This is doable if @enkore's suggestion doesn't work out for you..

**Comment by ThomasWaldmann** [comment]
see #6756
