### ISSUE TITLE
BORG_RELOCATED_REPO_ACCESS_IS_OK doesn't seem to work

### ISSUE THREAD

**Issue by micah** [borgbackup/borg#1426]
I relocated my repository and so I added BORG_RELOCATED_REPO_ACCESS_IS_OK=true to the beginning of my borg invocation so I wouldn't be asked about it being relocated, but it still asks me:

```
/etc/backup.d# BORG_RELOCATED_REPO_ACCESS_IS_OK=true /usr/bin/borg create --stats /srv/backup::`date +%Y-%m-%d` / --exclude '/proc' --exclude '/dev' --exclude '/run' --exclude '/srv' --exclude '/mnt' --exclude '/sys' --exclude '/tmp' --exclude '/home/*/.local/share/Trash' --exclude '/home/*/.Trash' --exclude '/home/*/.thumbnails' --exclude '/home/*/.beagle' --exclude '/home/*/.aMule' --exclude '/home/*/gtk-gnutella-downloads' 
Warning: The repository at location /srv/backup was previously located at /mnt/backup
Do you want to continue? [yN] 
```

**Comment by PlasmaPower** [comment]
Try `BORG_RELOCATED_REPO_ACCESS_IS_OK=yes`, does that work? I think it needs to be in the list [here](https://github.com/borgbackup/borg/blob/e09a059ce8f4dd81e6fb735ab8786ee3848ff9a0/src/borg/helpers.py#L944).

**Comment by micah** [comment]
Sorry, I had 'true' before, but when I read the man page it said to use 'yes', but I got the same result.

**Comment by ThomasWaldmann** [comment]
@micah please specific borg version, OS and what shell you use.

**Comment by enkore** [comment]
When you do `BORG_RELOCATED_REPO_ACCESS_IS_OK=yes python -c 'import os; print(os.environ)'` then the BORG_..._IS_OK should be in the output.

**Comment by micah** [comment]
@ThomasWaldmann I'm using borg 1.0.6 on Debian unstable with bash.

@enkore yes, when I do that I see in the list:

```
...
'BORG_RELOCATED_REPO_ACCESS_IS_OK': 'yes',
...
```

**Comment by ThomasWaldmann** [comment]
Works for me:
```
(borg-env)tw@tux:~/w/borg$ mv repo reponew

(borg-env)tw@tux:~/w/borg$ BORG_RELOCATED_REPO_ACCESS_IS_OK=no borg create reponew::archive borg
Enter passphrase for key /home/tw/w/borg/reponew: 
Warning: The repository at location /home/tw/w/borg/reponew was previously located at /home/tw/w/borg/repo
Do you want to continue? [yN] Aborting.
Repository access aborted

(borg-env)tw@tux:~/w/borg$ BORG_RELOCATED_REPO_ACCESS_IS_OK=yes borg create reponew::archive borg
Enter passphrase for key /home/tw/w/borg/reponew: 
Warning: The repository at location /home/tw/w/borg/reponew was previously located at /home/tw/w/borg/repo
Do you want to continue? [yN] (borg-env)tw@tux:~/w/borg$ 
```

There is a slight cosmetic issue: there is no newline output when the "Do you want to continue?" question is automatically answered via env var. But you see it does not abort when the env var is yes.

**Comment by micah** [comment]
Hmm, ok but then it seems like it is not answering it automatically?

**Comment by ThomasWaldmann** [comment]
It worked for me. See how it aborted with "no" and how it did not abort with "yes".

**Comment by enkore** [comment]
Maybe it hangs for other reason(s) after displaying the question, unrelated to the env var? Maybe network issues, or it just has to something. Try --debug to get a better idea.

**Comment by qknight** [comment]
i'm calling borg like this:
```
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes
export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
mkdir -p .borg-cache
export BORG_CACHE_DIR=.borg-cache
```

later i call like this:
```
borg create -v --stats backup-borg::$name backup-rsync
```

still i see
```
Warning: The repository at location /backup/nixcloud-backup/backup-borg was previously located at /backup/restart/backup-borg
Do you want to continue? [yN] 
```

why does this fail?

**Comment by ThomasWaldmann** [comment]
@qknight do you use sudo somewhere in the script? or something else that kills env vars?
is the shell bash? some shells need separate VAR=VALUE and export VAR.

**Comment by qknight** [comment]
this is my script:

https://github.com/nixcloud/nixcloud-backup/blob/master/nixcloud_backup.sh

it uses sudo, but sets the variables inside the innermost shell so it should apply for the `borg` command.

**Comment by enkore** [comment]
Does it actually wait for you to answer, or continue (htop, iotop)?

It's very confusing that it prints the question, but not that it was answered from the env var.

Patch suggestion: set the default of `env_msg` of `helpers.yes` to something like `{} (from {})`.

**Comment by qknight** [comment]
it spawns an interactive shell and i can press `y` and it will continue. it will then finish the backup.
i could patch it but i don't have a development environment at hand so you have to guide me here.

**Comment by enkore** [comment]
Hm, so it doesn't continue.

**Comment by ThomasWaldmann** [comment]
Improved by #1467.
