### ISSUE TITLE
Binary tests failing on freebsd64

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#1434]
Logs: https://gist.github.com/e6a86feda0abd606b596e56f73c97c24

This is a different set of errors than #1416.

The first log was from a run in `/var/tmp`, and the second was from a run in `/tmp`. They both produce the same errors.

**Comment by ThomasWaldmann** [comment]
Note: master branch (or at least not 1.0-maint)

**Comment by ThomasWaldmann** [comment]
both fixed meanwhile.
