### ISSUE TITLE
Enhancement request: no check for lock for RO operation

### ISSUE THREAD

**Issue by ptitvert** [borgbackup/borg#1439]
Hello,
I've played a little bit with Borg to implement it in our environment. And one aspect which is really not nice on Borg is its inability to allow 2 operations at the same time on the same repository.
For example, a backup is running, why is it not possible to do a "borg list" ?? Or "borg mount"? Or "borg info"? Or doing a restore? Or doing several restore at the same time? Or any operation that is read only?

That's my request, please allow the possibility to have a lockless borg for RO operations.

**Comment by ThomasWaldmann** [comment]
The locking scheme we use is shared-read exclusive-write locking.

shared-read means there may be multiple readers at the same time, but no writer.
exclusive-write means that a writer will only be allowed when no other writer or reader is active.

This is trying to play safe and is not very fine-grained (scope is always the repository), but it avoids repo corruption (multiple writers, obviously) and also getting wrong or inconsistent information (reading while a writer is active).

There are already some other tickets about improving the locking, so I guess this is duplicate.

**Comment by ptitvert** [comment]
I've seen the other tickets, but they were quite specific, and I wanted to have a more global view. Like a locking concept which is consistent, and not solved for one particular aspect.

**Comment by ptitvert** [comment]
For example, if a backup is currently in progress, then a read on the current backup does make sense. But a read on another backup makes totally sense.
I would prefer a locking on the backup part, instead in the whole repository. You won't get inconsistent information. So as long as a backup is "locked" you can do whatever you want for other backups (read only if you want).

Or what would be nice, but could be more difficult to implement with the deduplication...  to be able to run 2 backups at the same time in the same repository... but I don't dream on that... the other aspect is more critical for my eyes.

**Comment by ThomasWaldmann** [comment]
we can't just lock "the backup" (the archive). e.g. the repo manifest is repository global and read by most, read-modify-written by some operations.

we are still working on optimizing the current, relatively simple scheme, btw. (e.g. trying to detect stale locks) - so that should be finished first before we try to make it more complex.
