### ISSUE TITLE
Untracked segment

### ISSUE THREAD

**Issue by PostalBlab** [borgbackup/borg#1442]
If borg enters Repository.compact_segments() with an untracked segment it is possible the segment never gets deleted and stays in REPO/data
Copy paste from my explanation in #borgbackup:
> my repo has 3626 segments and one archive. by deleting the archive, in Archiver.do_delete() with archive.delete(), 2 more segments (3627 and 3628) are created because of all the write_delete() calls. both getting added to Repository.compact. after archive.delete() got called repository.commit() is called. because of the self.io.write_commit() call, segment 3629 gets created and then repository.compact_segments() is called. segment 1-3626 are getting thrown into "unnused" but 3627 and 3628 have all these TAG_DELETE entries which triggers new write_delete() calls and more TAG_DELETE entries. 3629 gets stuffed with TAG_DELETED entries and reaches max_segment_size. 3630 is created and 3629 gets completly untracked.

This happens with 1.0.6

The bug still exist in 1.1.dev and is getting worse.
In Repository.compact_segments(), write_put() and write_delete() are called with raise_full=True. When max_segment_size is reached write_*() throws an LoggedIO.SegmentFull exception, complete_xfer() is called, which leads to closing the current segment and opening a new one and closing it because of the write_commit() call. This leads to more untracked segment files with only 17 byte.

**Comment by ThomasWaldmann** [comment]
Fixed by #1448.
