### ISSUE TITLE
backing up /var /usr/local - permission denied

### ISSUE THREAD

**Issue by panditarevolution** [borgbackup/borg#1445]
Hi,

This may not be a borg issue as such, however I'm getting permission denied when trying to backup /var and /usr/local. /etc on the other hand seems to backup fine.

I tried running the commands from my user account, with `sudo`, as well as after `sudo su`.

Any ideas what could be the reason for this?

**Comment by ThomasWaldmann** [comment]
Maybe there is a special permissions system in force on that system.

Usually, root is permitted to read everything, but there are ways to change that.

What borg version, what OS / distribution is that? Are you the system administrator?

**Comment by panditarevolution** [comment]
I'm using borg 1.0.0rc1 on Debian. In my opinion I'm also the system administrator, though my computer disagrees sometime :)

I looked at the folders and they are owned by the root uid and gui, so I find this a bit strange....

**Comment by ThomasWaldmann** [comment]
If it is really 1.0.0rc1, please upgrade to 1.0.6 or 1.0.7rc1.

AFAIK, Debian has no special permissions in force by default. Is your filesystem OK? Maybe run a fsck.

**Comment by ThomasWaldmann** [comment]
anything new? it currently looks like a local problem on your system, so if we do not get more information, we likely can't do anything about it.

**Comment by panditarevolution** [comment]
Hi sorry this took a while. I suspect it was a problem with the system. Also for other reasons, I decided to wipe my system and install Fedora instead. I also updated borg to 1.0.6 ...so unfortunately it's not a like for like situation however everything works now as expected. 

Thanks a lot for following up on this and for maintaining and developing a great piece of software!

**Comment by ThomasWaldmann** [comment]
You're welcome, thanks for the feedback. Closing this now.
