### ISSUE TITLE
Show the number of sent and received bytes in --stats

### ISSUE THREAD

**Issue by a3nm** [borgbackup/borg#1463]
Just a suggestion: In the summary displayed by `--stats`, it would be nice to know how many bytes were sent and received, just like `rsync -v` does. This is interesting data, e.g., to compare borg to rsync.

If you think that this is better accomplished using a wrapper script (like bandwidth limiting), I would then think it would be useful to add an FAQ entry about it.

Thanks!

**Comment by PlasmaPower** [comment]
This would be just logging the amount of information transferred *through* SSH, not the total bandwidth used by SSH right? I'm not sure how we would get information on the latter.

Should this also apply to local repositories? They could be network mounts.

**Comment by a3nm** [comment]
I would say that giving the amount of data sent through ssh would be a sufficient approximation (not sure what rsync does there). For local transfers, I would say it also makes sense (and rsync does it too).

-- 
Antoine Amarilli

**Comment by enkore** [comment]
When creating archives the deduplicated size is a proxy for this, there is some overhead, but as soon as we're talking about gigabytes dedup size it won't really matter.

**Comment by enkore** [comment]
Done. It's not in --stats but rather --debug. See #2209 for other instrumentation.

**Comment by a3nm** [comment]
Thanks! I'll try this when it lands in Debian.

**Comment by ziesemer** [comment]
> => Separate borg.output. logger + cmdline option for these?

What happened to this part of the ticket from #2209?

> It's not in --stats but rather --debug. 

Any reason this can't be included with the current "`--stats`" output?  (I'm more concerned about bandwidth used, than current repository size.)
 
Overall, is there anyway I can show or get at these metrics, without enabling full `--debug` ?
