### ISSUE TITLE
Race in xattr querying leading to entire file not being backed up

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1469]
A related race is found in xattr.get_all: https://github.com/borgbackup/borg/blob/1.0-maint/borg/xattr.py#L28

When a single xattr vanishes between listxattr and getxattr of the respective xattr, OSError(errno=ENOATTR|ENODATA) will be raised and processing of the file will be aborted/skipped.

However only the attribute should be skipped.

(From #906)

Fixed by #1464

**Comment by ThomasWaldmann** [comment]
#1464 is merged.
