### ISSUE TITLE
binary wheels for latest release

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#147]
A binary wheel is a package that can be easily installed with `pip install package.whl`. It contains python code plus already compiled C code (so you do not need a compiler, nor development headers on your system).

As PyPi does not let me upload all the wheels, I'll just link them from here:

https://paste.thinkmo.de/dPXrFRMU#borgbackup-0.25.0.list

Release: 0.25.0, all files signed by my GPG key (please check the signature).
source code
linux x86_64 - made on ubuntu 14.04 64bit
linux armv7el - made on raspbian wheezy on a raspberry pi2
mac os x 10.10 - made on a Mac (still missing)
cygwin 64bit - made on windows 10

**Comment by ThomasWaldmann** [comment]
See also #214 for single-file standalone binaries for some platforms.

**Comment by ThomasWaldmann** [comment]
I am thinking about dropping support for wheels again, due to following reasons:
- they need to get built on each platform we support
- they are usable only on that specific platform (depends on python version, OS release, ...)
- they still need working python, pip
- pyinstaller binary builds are easier to install (just copy 1 file, everything included)

Any comments?

**Comment by anarcat** [comment]
let's drop this and use the standalone binaries in #214.

**Comment by ThomasWaldmann** [comment]
I am reopening this as a reminder to remove wheel-related documentation and also the links to this issue before next release.

**Comment by ThomasWaldmann** [comment]
Done:

https://github.com/borgbackup/borg/commit/ee66c4c4354e7fb055485d49563be10bcd411cd8
https://github.com/borgbackup/borg/commit/28a85bf0aa0359bd3ac0f1bd9d898b8e09487533
