### ISSUE TITLE
per archive total item count limit

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1473]
See #1452 for the basics.

While we have a short time fix for this, raising the limits, we also might need a long term fix, solving the limit problem completely.

**Comment by enkore** [comment]
Ideas so far:

- Mark chunk lists on each level with the depth remaining (breaks backwards compat)
- Somehow be able to differentiate a pointed-to chunk from a "real" (wanted) data chunk and a another level of chunk list. This could be done w/o breaking backwards compat and still allowing arbitrary sized archive items.

**Comment by ThomasWaldmann** [comment]
## Current state:
```
Archive.items = [id, id, id, ...] # ids pointing to the chunks of the metadata stream (containing fs items' metadata)
````
The current problem is that, due to the growth of that `.items` list, the serialised `Archive` object might become bigger than the max chunk size the repo supports (about 8MB).

## TODO (near future):
```
Archive.items = [id, id, id, ...]  # ids pointing to something
Archive.items_indirect = 0  # NEW: level of indirection, 0 = ids point directly to metadata stream
```
borg would just create all archives with items_indirect = 0.

## TODO (has time)
Actually support items_indirect > 0.
Specifically, I think it is enough to support items_indirect = 1 for all practical purposes.

For 1, the `Archive.items` ids would point to intermediate chunks containing the (final) ids pointing to the metadata stream.

**Comment by ThomasWaldmann** [comment]
An alternative idea, would be to **always** uses items_indirect = 1 mode of operation (we don't actually need the attribute then).

This creates less "rare special cases" (guess the amount of users needing items_indirect = 1 would be rather low and stuff would be hard to test if we dynamically switch from 0 to 1 only if really needed).

If we always operate with indirection, the usual `Archive.items` list (for most users with little to medium archive sizes) would have just one entry pointing to a chunk with the final chunk ids of the metadata stream. For users with bigger archives, the code pathes would be exactly the same, just the `Archive.items` list would have more than 1 element.

**Comment by ThomasWaldmann** [comment]
Note: borg2 will need transferring of all archives using `borg transfer` so guess that could be a good time for such a change. We only need to support old archives as the input for `borg transfer` and from then on, we only have new stuff in the new repo.
