### ISSUE TITLE
Unable to run under CentOS 6 due to  error while loading shared libraries: libz.so.1

### ISSUE THREAD

**Issue by sinasalek** [borgbackup/borg#1479]
I installed borg via binary packages, however it does not work at all
I installed it on another CentOS 6 VPS and it worked just fine. So it seems that there is some sort of a conflict
with some of the settings.
On this particular server i cannot turn of selinux due to security. is borg compatible with SELinux ? is this caused by SeLinux? is there any workaround? 
I found similar issue but under docker

**Error Details**
Virtualization: ESXI
Borg Version : borg 1.0.7rc2
OS : CentOS 6 (2.6.32-642.3.1.el6.x86_64)
SetLinux: Permissive
Control Panel: CPanel
Full error : 
` error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted`

**Comment by ThomasWaldmann** [comment]
I tested the binaries a while back on a centos6 vagrant VM, they worked.

The liblz4.so.1 is bundled within the binary.
When such a pyinstaller-made binary is starting, it first unpacks itself into TMPDIR (usually /tmp/), using a temporary subdir _MExxxx. In there, there is everything needed: python 3.5.2, shared libs, compiled C and cython stuff.

Maybe your system is configured not to load / execute stuff from /tmp ?
Is that working:

```
TMPDIR=/home/username/tmp borg --version
```

**Comment by ThomasWaldmann** [comment]
And you did set the binary to +rx?
```
chmod +rx borg-linux64
```

**Comment by enkore** [comment]
> Maybe your system is configured not to load / execute stuff from /tmp ?

Looks like it to me as well. /tmp probably has `-o noexec` or a similar policy. Set TMPDIR env var to somewhere where that bit is not set and it probably works.

**Comment by sinasalek** [comment]
I did that but apparently documentation is not fully correct. It's mentioned that the variable name is TEMP. but when i tried your suggestion it worked :)
Thanks alot
Here is the full code for record. and in my case i always have to include TMPDIR or it doesn't work

`
mkdir -p /root/tmp
wget https://github.com/borgbackup/borg/releases/download/1.0.7rc2/borg-linux64
cp borg-linux64 /usr/bin/borg
rm -f borg-linux64
chown root:root /usr/bin/borg
chmod +rx /usr/bin/borg
TMPDIR=/root/tmp borg --version
`

**Comment by ThomasWaldmann** [comment]
from python tempfile docs:
"""
the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables
"""

**Comment by enkore** [comment]
I'm not sure whether the PyInstaller shim that does the unpacking adheres to that. Since TMPDIR works and TEMP apparently doesn't...

docs/installation.rst around line 110

> Note that the binary uses /tmp to unpack |project_name| with all dependencies.
It will fail if /tmp has not enough free space or is mounted with the ``noexec`` option.
You can change the temporary directory by setting the ``TEMP`` environment variable before running |project_name|.

...should then be ``TMPDIR``

**Comment by ThomasWaldmann** [comment]
@sinasalek did you maybe forget to "export " like in

```
export TEMP=...
```

**Comment by sinasalek** [comment]
Correction: You were right, it was caused by nonexec, and i tried again with TEMP and it worked. The reason that it didn't work was because i forgot to use export.

**Comment by ThomasWaldmann** [comment]
shall we explicitly give an example there in the docs?

**Comment by ThomasWaldmann** [comment]
otoh, iirc we point out the export-thing at some other place in the docs.

**Comment by sinasalek** [comment]
Suggestion: It think displaying a proper error when it cannot extract dependencies prevents confusion in the future. also at least for know mentioning the current zlib error in documentation helps alot

Here is my installation code that worked :

    mkdir -p /root/tmp
    export TMPDIR=/root/tmp
    wget https://github.com/borgbackup/borg/releases/download/1.0.7rc2/borg-linux64
    cp borg-linux64 /usr/bin/borg
    rm -f borg-linux64
    chown root:root /usr/bin/borg
    chmod +rx /usr/bin/borg
    borg --version

Thanks

**Comment by enkore** [comment]
TMPDIR, TEMP, TMP, just like `tempfile`: https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_utils.c#L249

**Comment by enkore** [comment]
>  It think displaying a proper error when it cannot extract dependencies prevents confusion in the future

This is out of our reach; since this is done by PyInstaller.

**Comment by sinasalek** [comment]
I see. mentioning the error in doc is also fine. people can find it via simple google search. not a big deal

**Comment by David-Else** [comment]
I am running on a shared server with no root privileges using cloud linux 6, and trying to install Borg into my home directory `~/bin` had the error:
```
borg-linux64 --version
borg-linux64: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
```
Which I fixed by using the example in this thread, but now I have a new error:
```
TMPDIR=/home/user/tmp borg-linux64 --version
borg-linux64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/user/tmp/_MEIr1RMp4/libz.so.1)
```
I asked the hosting to upgrade but they refused :(
```
ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
```
Is there anything I can do to use `borg 1.1.16` on my server? Thanks.

**Comment by ThomasWaldmann** [comment]
Please note that centos6 is after "end of life" meanwhile.

About borg:
- newer borg "fat binary" releases tend to have higher glibc requirements than older ones, this is documented in the README.txt available with these binary releases. this is just because of the same problem: linux dists we use to build the binaries run out of support and we need to switch to newer ones (which have newer glibc).
- borg 1.1.11 maybe is a good version (new enough to have the most critical bug fixes, old enough so it still runs on old linux).

**Comment by David-Else** [comment]
@ThomasWaldmann Thanks! That version works. I assume I am safe to use `1.1.x` on my home machine and `1.1.11` on the server?

The only way it runs is with `TMPDIR=/home/user/tmp borg`. As I have no root access, what do you recommend so that the server can run borg when I sync from my home machine? Maybe on the server alias `borg` to `TMPDIR=/home/user/tmp borg` and source it? I am not that experienced, thanks!

**Comment by David-Else** [comment]
I am nearly there, but the final hurdle is to run `borg` on the server without:
```
Remote: borg: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
Connection closed by remote host. Is borg working on the server?
```
I can't get the environmental variable `TMPDIR` in scope when running `borg` on the server.

I have tried:
1. `alias borg="TMPDIR=/home/user/tmp borg"` on the server using `.bashrc` and source it,  borg runs on server when I am in the server, but when SSH access it then it does not, it must be in a different scope/context.
2. Try to init a repo from my home computer on the server with `TMPDIR=/home/user/tmp borg init --verbose --encryption=repokey servernameinsshconfig:borg-documents-backup`

Any ideas? Thanks!

**Comment by ThomasWaldmann** [comment]
No matter whether client or server, one should use at least 1.1.11 (except when using a patched version, where patches for the most severe issues have been applied to an older release, like e.g. 1.1.9 from debian).

And yes, using 1.1.11 (or patched 1.1.9 from debian) on the server and a newer 1.1.x on the client is no problem.

**Comment by ThomasWaldmann** [comment]
This is the interesting part of the code about env_vars:
https://github.com/borgbackup/borg/blob/1.1.16/src/borg/remote.py#L686

So, try whether that works: `borg --remote-path='TMPDIR=/home/user/tmp borg' ...`

It might also depend on whether the server side uses a ssh forced command e.g. via `authorized_keys` file

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/4545/files - tried that?

**Comment by David-Else** [comment]
@ThomasWaldmann THANKS! `borg --remote-path='TMPDIR=/home/user/tmp borg' ...` was the missing ingredient to get everything working.

It has been a long journey, I had nearly given up and was experimenting with setting up my own private virtual server from scratch with another company... but now all is well and I can relax in the knowledge that when the ancient decrepit Cloud Linux 6 is hacked at least my documents will be safely encrypted :)

This hosting company really has me by the balls. Once all my overpriced services are nearly expired I will be moving to somewhere with Rocky Linux and live happily ever after.
