### ISSUE TITLE
reference the ccc talk

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#149]
not sure where to put this, but it seems relevant (even if only german):

https://www.youtube.com/watch?v=Nb5nXEKSN-k

(coming from https://github.com/jborg/attic/issues/217)

**Comment by ThomasWaldmann** [comment]
I also put a comment below the video and linked the slides from there.

**Comment by rpodgorny** [comment]
any chance there's going to be an english version?

**Comment by ThomasWaldmann** [comment]
as soon as I make an english talk.
wanted to give some lightning talk at europython, but the slots were always full.
32c3 would be one of the next intl confs I visit, not sure if a talk about a backup program is on-topic there.
otoh it has (AFAIK) good crypto, so maybe?

**Comment by anarcat** [comment]
@rpodgorny i guess some german volunteer would need to translate the subs somehow.

**Comment by ThomasWaldmann** [comment]
I tried, but I didn't find a way. Guess that only the uploader / "owner" can do that.

**Comment by ThomasWaldmann** [comment]
maybe we could have a page in the docs that lists all talks / slides / reviews / ... about borgbackup.

**Comment by anarcat** [comment]
it would be great to start that, because it's actually hard and annoying
to do that retrospectively. :)

**Comment by KwadroNaut** [comment]
You might want to prefer to use https://media.ccc.de/browse/conferences/gpn/gpn15/gpn15-6942-attic_borg_backup.html#video instead of youtube.

**Comment by anarcat** [comment]
see also #266 for common material...
