### ISSUE TITLE
Simple command to mount the last archive of repo

### ISSUE THREAD

**Issue by DoTheEvo** [borgbackup/borg#1493]
if I want to mount latest backup I go in to my borg repo and:

`borg list .`

> 2016-05-30                           Mon, 2016-05-30 10:55:45
> 2016-06-16                           Thu, 2016-06-16 20:33:46
> 2016-07-17                           Sun, 2016-07-17 12:15:59
> 2016-08-03                           Wed, 2016-08-03 09:34:58
> 2016-08-17                           Wed, 2016-08-17 11:39:28

to get the name of my last archive, then...

`borg mount .::2016-08-17 ~/temp`

so I think ideal would be to have a way to skip the list part, and just tell borg to mount the latest archive from the repo. So something like this

`borg mount .::--last`

assuming that --last would be from now considered a keyword and would not allow to make repo with such name. Maybe --last is breaking some naming practice but you got the point...

--------

also side note, maybe there might be no need for the dot character in the future if I am in a repo?
Similar to how git works? I just write `git status` and `git push`
So ultimately it could be, assuming I am inside a repo just
`borg mount --last ~/temp`
Probably its some work when many commands expect <repo>::<archive> to target it, but it would feel cleaner and seamless

**Comment by ThomasWaldmann** [comment]
latest: duplicate of #128.

not having to type the repo path: just `export BORG_REPO=.`  (or, if it is always same repo, maybe rather full path).

**Comment by ThomasWaldmann** [comment]
close?

**Comment by DoTheEvo** [comment]
>latest: duplicate of #128.

cool

>not having to type the repo path: just export BORG_REPO=. (or, if it is always same repo, maybe rather full path).

oh, that I would forget about and would fuck up later on after reinstall or use on another machine
