### ISSUE TITLE
Improper logging of remote exceptions/errors

### ISSUE THREAD

**Issue by lutoma** [borgbackup/borg#1494]
I've been using borg to back up various servers for a few weeks and I've been very happy with it so far. However for some reason, all of our backups failed this night on all our servers with an error message like this:

```bash
Aug 17 14:10:57 bnc borg[15672]: Remote Exception (see remote log for the traceback)
Aug 17 14:10:57 bnc borg[15672]: Platform: Linux bnc 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64
Aug 17 14:10:57 bnc borg[15672]: Linux: debian 8.4
Aug 17 14:10:57 bnc borg[15672]: Borg: 1.0.6  Python: CPython 3.4.2
Aug 17 14:10:57 bnc borg[15672]: PID: 15672  CWD: /
Aug 17 14:10:57 bnc borg[15672]: sys.argv: ['/usr/bin/borg', 'create', 'foo@example.net:backups/foo.foo.net::{now:%Y-%m-%d}', '/', '--exclude-from', '/var/local/backup-excludes.txt', '--exclude-caches', '-vs', '-C', 'lz4']
Aug 17 14:10:57 bnc borg[15672]: SSH_ORIGINAL_COMMAND: None
```

IMHO that's a very unhelpful error message for a number of reasons:

* It doesn't actually say what is broken, but just refers to the "remote log".
* There is no mention of a "remote log" anywhere in the documentation (at least I couldn't find any).
* Remote errors don't seem to get logged to any file by default, but just to stdout/-err (where the client will just discard them), and the configuration samples in the documentation don't contain any stderr redirection to logs either. This is problematic because you don't tend to notice that until after you've had some kind of remote error, at which point it's obviously too late to add logging, and one may not be able to reproduce the error anymore.

Apologies if those are known issues or there is some kind of error/misunderstanding on my side.

**Comment by ThomasWaldmann** [comment]
Usually one sees some "REMOTE: ..." lines right above the part you posted. That is the remote log and there you see what's broken.

The client won't discard stderr of the ssh process, but log it using such "REMOTE: ..." lines (maybe it should rather say "ssh stderr:" because not everything coming out of ssh on stderr necessarily comes from remote).

**Comment by lutoma** [comment]
Oooh I see, I just now realized that actually part of the log was cut off, but because it started right with that line it looked like it was complete. Looks like the mistake was on my side indeed. Sorry for the noise, and thanks for the great backup tool :).
