### ISSUE TITLE
Shared home issues

### ISSUE THREAD

**Issue by frispete** [borgbackup/borg#1500]
When using borg on different systems with a shared home, the current ~/.cache/borg scheme results in **failed backup attempts**, unless an environment var ``BORG_RELOCATED_REPO_ACCESS_IS_OK=yes`
is provided everywhere. 

Even, if it is provided, borgs operational output is cluttered with:

```
borg create -v /backup/path::repo-$date /var/lib/virtualbox
Warning: The repository at location /backup/path was previously located at ssh://user@host/backup/path
Do you want to continue? [yN] Next log line appears here
```

Since one of the biggest strengths of borg is deduplication, which can be archived only if the backup path is shared and backups are separated with prefix, I propose a new .cache naming scheme:

```
~/.cache/borg/$hostname/...
```

**Comment by enkore** [comment]
You don't need to share the borg cache directory for deduplication to work. The broken (missing new line) output für B_R_R_A_I_O=yes will be fixed in the next point release.

Generally speaking it may be a good idea to keep ~/.cache host-specific.

**Comment by frispete** [comment]
> You don't need to share the borg cache directory for deduplication to work.
Yes, sure, but how can I avoid that? Can I specify the location manually?

**Comment by enkore** [comment]
Yes, there's [BORG_CACHE_DIR](http://borgbackup.readthedocs.io/en/stable/usage.html#environment-variables).

**Comment by frispete** [comment]
Okay, thanks enkore, and sorry for bothering again, but how is that supposed to be used?

I've tried:
export BORG_CACHE_DIR="~/.cache/borg/$HOSTNAME"
This resulted in creation of a ~ folder in my home, and borg created another borg dir below ~/~/.cache/borg/$HOSTNAME, containing a CACHEDIR.TAG file, but otherwise, these folders remained empty.

Obviously, borg anchors BORG_CACHE_DIR in home, which is not, what the documentation implies. I've relocated these folders to ~/.cache/borg, removed everything else there, and been using:

export BORG_CACHE_DIR=".cache/borg/$HOSTNAME"

Nevertheless, it looks like those cache locations aren't being used at all (they're missing the typical sha dirs in there at least).

Also, all backup runs show the typical Fetching and Merging index messages.

Still 1.0.7 here...

**Comment by enkore** [comment]
> Obviously, borg anchors BORG_CACHE_DIR in home

More likely: relative paths are relative to the current working directory. (Which could also explain why these are seemingly unused if the cwd was changed)

Try `export BORG_CACHE_DIR=~/.cache/borg/$(hostname)`. Note absence of quotes to allow shell expansion.

Now you get:

```
$ echo $BORG_CACHE_DIR 
/home/mabe/.cache/borg/tiger
```

Which works as expected for me.

**Comment by frispete** [comment]
Thanks again, enkore.
One can learn something every day.
Environment vars are expanded inside double quotes in bash (unlike within single quotes), but ~ is expanded only, if not quoted.. 

Since documentation says, BORG_CACHE_DIR defaults to ‘~/.cache/borg’, I expected it to be treated with os.path.expanduser() by borg, which is not the case, obviously.

Let's keep this open in order to anchor a related pull request (that I hope to be able to prepare soon)

**Comment by frispete** [comment]
Sorry for bothering again, but this still doesn't work as expected.

My setup is as follows:
NFS shared $HOME
backing up many local VMs, both virtualbox and vmware style to a shared repo in order to maximize deduplication, using prefixes to separate them logically. Unfortunately, every time, the backing up host (data source) changes, it is recreating the index. Hence, the advantage of separating the cache dirs per host is lost...

This boils down to: the best result, I get is still with B_R_R_A_I_O=yes, and I should ignore the ugly warning. I dislike this situation, since it easily results in erroneously ignoring important warnings as well...

**Comment by ThomasWaldmann** [comment]
@frispete The index rebuild is expected. borg clients need a current chunks index, so they have knowledge about all chunks in the repo. If they notice that their index is outdated, they rebuild it.

**Comment by enkore** [comment]
Unclear whether any issue remains. Closing. Feel free to reopen if this assessment is not accurate.
