### ISSUE TITLE
Easy method to list all archives in repository missing

### ISSUE THREAD

**Issue by frispete** [borgbackup/borg#1502]
Due to a broken borg backup, I want to check all backups with borg extract --dry-run, but with borg 1.0.6, it looks like `--list-format` as in `borg list repository --list-format` with just a repository isn't processed at all:
```
borg list /backup/path --list-format="{formatkeys}{NEWLINE}"
prefix                  $date
...
```

Consequently, listing archives need a construct such as this, if I'm not mistaken:
```
for a in $(borg list /backup/path | cut -d' ' -f1); do echo $a; done
```

While still not exactly handy, I wish, that this command would do the same: 
```
borg list /backup/path --list-format="{archive}{NEWLINE}"
```

**Comment by enkore** [comment]
Yes, customizing the list format of the archive list itself (not the file list of an archive) is not supported in 1.0.x.

**Comment by ThomasWaldmann** [comment]
borg list --short repo
