### ISSUE TITLE
Tests are very sleepy

### ISSUE THREAD

**Issue by sourcejedi** [borgbackup/borg#151]
Tests are great!  I wonder if they can be sped up.  I didn't figure why, but the tests spend most of their time doing nothing.  It doesn't seem to show as IO-wait (`wa`) in `top`, I just get something like 80% idle time on the cpu core.

    $ time fakeroot -u py.test --pyargs borg.testsuite
    ... 141 passed, 8 skipped in 289.71 seconds ...

    real	4m50.700s
    user	0m55.163s
    sys	0m16.085s

**Comment by ThomasWaldmann** [comment]
maybe try if just some tests cause the slowness (e.g. measure test module by test module).

**Comment by sourcejedi** [comment]
right!  iirc, archiver is pretty slow

**Comment by sourcejedi** [comment]
It might be fakeroot.  Either that, or the sleepy tests are the 10 tests that need fakeroot to pass.  On attic:

Ran 117 tests in 133.361s

OK (skipped=9)

real	2m13.758s
user	0m32.372s
sys	0m5.502s

v.s. no fakeroot:

Ran 117 tests in 16.464s

FAILED (errors=10, skipped=6)

real	0m16.654s
user	0m14.794s
sys	0m1.543s

**Comment by ThomasWaldmann** [comment]
I guess that rather missing fakeroot makes them fail in test setup, so that the real test does not get executed at all. That is of course quicker than doing the test. ;)

**Comment by sourcejedi** [comment]
If that's all, it means those 10 tests (out of the 117 in attic) take an average of 16 seconds.  The total difference is 15s cpu and 1min 45s sleeping.  And there are no sleepy tests that work without fakeroot.  I suspect it's more complex than that.

**Comment by sourcejedi** [comment]
*correction: an average of 12 seconds (60*2 / 10)

**Comment by ThomasWaldmann** [comment]
The archiver tests are very high-level. Many of them invoke multiple borg commands and then check what happened. Some are doing rather expensive checks like aes counter uniqueness and sparse file checks with relatively big files.

So, unless you have some specific idea about how to improve the tests, I guess we can't do much about it and this issue could be closed.

**Comment by sourcejedi** [comment]
The tests could be improved by sleeping less, in principle.  As I showed by the cpu+io-wait utilization (or on the flip side, the cpu idle %).

Measuring io-wait more methodically, with 4 logical cpus I still get about 7% cpu+io-wait, instead of 25%:

<pre>
borg$ ($TEST; killall -SIGINT iostat) & (iostat  -c -y -t 50 > iostat.log; cat iostat.log)
... 141 passed, 8 skipped in 281.95 seconds ...

real 4:42.82
user 52.58
sys 12.52

Linux 4.1.3-201.fc22.x86_64 (volcano.localdomain) 	15/08/15 	_x86_64_	(4 CPU)

15/08/15 12:26:30
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.06    0.00    0.73    0.22    0.00   95.99

15/08/15 12:27:30
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           4.14    0.00    0.86    0.23    0.00   94.77

15/08/15 12:28:30
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           6.71    0.00    2.52    0.21    0.00   90.56

15/08/15 12:29:30
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           7.18    0.00    2.59    0.18    0.00   90.04
</pre>

I also tried `strace -c`; I can't remember if that has a bug when tracing multiple processes (`-f`).  It shows a plausible time blocked.  Unfortunately the strace results don't confirm my theory on their own.  (I don't see _any_ sleep-specific calls, but we know there are _some_ sleeps from reading the tests.  Presumably everyone is using the hack of calling down to `sys_select()` or `sys_poll()` with a timeout.  `sys_wait*` is just waiting for a child process, it's not a timed sleep as you might guess from the name.).

<pre>borg$ time strace -f -c -w fakeroot -u py.test</code>

... 141 passed, 8 skipped in 317.38 seconds ...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 42.58  436.526940        2105    207333         1 select
 31.74  325.376387      558107       583        12 wait4
 23.02  235.973456         491    480225           read
  1.50   15.354392          37    416089           write
  0.32    3.276285          16    202388     91900 stat
  0.12    1.209623          22     53959      9689 open
  0.09    0.942983          13     74114         1 fstat

...
real	5m18.808s
user	1m6.039s
sys	0m46.143s
</pre>

**Comment by ThomasWaldmann** [comment]
I've looked a bit at the code, some suspicions (in case you want to investigate further):

wait4 - is this maybe CAUSED by using strace (the man page tells about returning stats about resource usage)?

long times (even more than the "real" runtime) in select, a lot in wait4: does this have to do with teardown of the remote archiver? usually borg commands are commandline and the process dies after it has finished its work (== 1 borg command). but in the tests, a lot of borg commands are executed without that the main process terminates. `RemoteRepository.__del__` calls `.close()` - but when is `__del__` called?

**Comment by sourcejedi** [comment]
I'm not saying this is a priority btw.  I filed the bug because the amount of cpu idling time suggested it might be possible to make a big improvement.

`strace` won't show it's own `wait()` call.  But I was _also_ `time` on top of `fakeroot` to run the test command.  `time` definitely uses `wait()`.  So the total time spent in `wait()` across all the processes I measured should be at _least_ the full test run time.  Equally the `fakeroot` command is equally going to spend most of its time blocked waiting for the test command to finish.  Though looking at the times maybe it doesn't use `wait()`.

I can switch the order of commands, i.e. run  `fakeroot time strace` instead:

<pre>
borg$ TEST="fakeroot -u time strace -c -w -f py.test"
borg$ ($TEST; killall -SIGINT iostat) & (iostat 60 > iostat.log; cat iostat.log)
...141 passed, 8 skipped in 313.95 seconds...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 58.34  223.405124         800    279162           read
 34.15  130.767681       23737      5509           select
  2.49    9.531870          43    223239           write
  1.72    6.574422       11782       558         1 wait4
  0.89    3.392696          17    202327     91881 stat
  0.32    1.239916          23     54099      9684 open
  0.29    1.128433          15     74431         1 fstat
  0.23    0.866469          14     60497           close
...
real 5:15.06
user 67.73
sys 41.98  -- Note I think the sys here _is_ due to strace, because it's higher than the original result I posted.
</pre>

<h2>__del__()</h2>

I doubt it helps the test time, but [using `__del__` is only for if you're a real wizard](https://docs.python.org/3/reference/datamodel.html#basic-customization).  IMO tearing down a remote archiver should definitely be an explicit close().

**Comment by ThomasWaldmann** [comment]
ehrm, yes, i meant "time", not "strace".

I agree about the explicit close(). Still has to be seen whether this can be integrated easily.

**Comment by sourcejedi** [comment]
It's fakeroot.  Although something's going funny with `skipped`, it's only changing 2 this time, so they'd have to be two _really_ sleepy tests to make up the numbers.  And I've not noticed that in the progress indications; it looks slow across many tests (with the normal fakeroot).  (Maybe a fuse thing? fuse is weird about root).

<pre><code>$ sudo python3 -m attic.testsuite.run
...
Ran 118 tests in 33.539s
OK (skipped=7)
31.72user 2.20system 0:33.75elapsed 100%CPU (0avgtext+0avgdata 78452maxresident)k
0inputs+0outputs (0major+540286minor)pagefaults 0swaps

$ fakeroot -u time python3 -m attic.testsuite.run
...
Ran 118 tests in 137.040s
OK (skipped=9)
35.96user 5.93system 2:17.44elapsed 30%CPU (0avgtext+0avgdata 78668maxresident)k
0inputs+0outputs (0major+545971minor)pagefaults 0swaps

**Comment by ThomasWaldmann** [comment]
you could repeat the tests with current borg master, it now does really (almost) the same tests with and without fakeroot.

**Comment by sourcejedi** [comment]
Looks good!  Thanks for working on that.  (I understand it was mainly to get tests working at all on Cygwin).

<pre>$ time py.test-3.4
...151 passed, 6 skipped, 2 xfailed in 56.07 seconds...
real	0m56.452s
user	0m49.410s
sys	0m5.338s</pre>

Allegedly `fakeroot-sysv` is faster, but it won't work for multi-threaded programs.  (I guess that's something to look out for, because Debian defaults to `fakeroot-sysv`).
