### ISSUE TITLE
Remove unqualified numeric compression specifiers when compression flexibility lands (PR #129)

### ISSUE THREAD

**Issue by sourcejedi** [borgbackup/borg#152]
Proposed commit 8997766202 would prominently advertise the following insane usage information:

    + 'select compression algorithm and level, by giving a number: '
    +                                    '0 == no compression [default], '
    +                                    '1..9 == zlib level 1..9, '
    +                                    '10 == lz4.
    +                                    'Alternatively, you can also give a name and optionally additional args: '
    +                                    'null == no compression, '
    +                                    'zlib == zlib (default level 6), '
    +                                    'zlib,0 .. zlib,9 == zlib (with level 0..9), '
    +                                    'lz4 == lz4.'

Proposals:

All documents naming "10" as an alias for "lz4" should be burnt, because it implies better compression than "9" but will actually be worse.

1..9 as shortcuts for zlib,1..9 should not be mentioned in the short usage information.  It may be documented elsewhere as a backwards compatibility option, to avoid unnecessary panic.  The same applies to "0".

**Comment by ThomasWaldmann** [comment]
sounds good, I'll update it that way.

**Comment by ThomasWaldmann** [comment]
PR updated.
