### ISSUE TITLE
Cache’s previous_location is only updated on cache commit

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#1524]
When the "Warning: The repository at location {} was previously located at" prompt is answered the location should be be updated immediately instead of only on the next commit.

Rational: Automated backup scripts often have no way to answer such prompts. A natural first try is to do a quick operation from the shell to fix that problem like a borg list or borg info. But these commands don’t commit a cache transaction so previous_location is never updated.

**Comment by enkore** [comment]
enhancement -> bug because it's so annoying

**Comment by enkore** [comment]
✓#1708
