### ISSUE TITLE
chunker params error

### ISSUE THREAD

**Issue by storcium** [borgbackup/borg#154]
Hello, trying to run a test from https://borgbackup.github.io/borgbackup/usage.html:

# Backup huge files with little chunk management overhead
$ borg create --chunker-params 19,23,21,4095 /mnt/backup::VMs /srv/VMs

That is failing:

root@lab2-b1:/usr/local/ISS/borg# borg create --chunker-params 19,23,21,4095  /vault/repo1::tst1 /data/volume1
usage: borg create [-h] [-v] [--no-files-cache] [--umask M]
                   [--remote-path PATH] [-s] [-p] [-e PATTERN]
                   [--exclude-from EXCLUDEFILE] [--exclude-caches]
                   [-c SECONDS] [--do-not-cross-mountpoints] [--numeric-owner]
                   [--timestamp yyyy-mm-ddThh:mm:ss]
                   [--chunker-params CHUNK_MIN_EXP,CHUNK_MAX_EXP,HASH_MASK_BITS,HASH_WINDOW_SIZE]
                   [-C COMPRESSION]
                   ARCHIVE PATH [PATH ...]
borg create: error: argument --chunker-params: invalid ChunkerParams value: '19,23,21,4095'

Thank you,
Alex

**Comment by storcium** [comment]
Platform is Ubuntu 14.04.2 and I built borg from git - thanks

**Comment by ThomasWaldmann** [comment]
Oops. Thanks for the hint and for your contribution. I'm fixing it asap.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/93a89d97faed2f5091ad7d229f15049c63c3ee46 fixes this.

sorry for the inconvenience, this likely got confused due to some incomplete refactoring of the parameter order.

**Comment by ThomasWaldmann** [comment]
reopening this so people can find it easier (while it is fixed in git, people using release code might still stumble over it until next release).

I'll make a new release soon, so it will be also fixed in release code.

**Comment by storcium** [comment]
Much appreciated!  And hail from LinuxCon NA.

Alex

**Comment by ThomasWaldmann** [comment]
ah, nice. scalability tests is something I can hardly do.

**Comment by ThomasWaldmann** [comment]
fixed in 0.25, closing.
