### ISSUE TITLE
more tests for recreate

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1541]
While there are tests that verify general behaviour quite some edge cases don't have real tests. More tests also makes further development easier.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/37335315-more-tests-for-recreate)

**Comment by enkore** [comment]
Most of that stuff with edge cases went out the window. I think most of the stuff should now be covered relatively well, but some things still look rather complex and likely undertested, like matcher_add_tagged_dirs.

**Comment by ThomasWaldmann** [comment]
@enkore iirc you killed that interrupt/resume stuff in the end, so maybe update your comment above.

**Comment by ThomasWaldmann** [comment]
@enkore shall we close this and use the bounty money for some other task?

**Comment by enkore** [comment]
Yeah.

**Comment by enkore** [comment]
I don't think it's possible to remove a bounty, so I am going to claim the bounty and add the funds ($60) back to the borgbackup org.

**Comment by enkore** [comment]
Done.

**Comment by ThomasWaldmann** [comment]
Yeah, would've done same. Thanks. :)
