### ISSUE TITLE
borg serve option to restrict prune

### ISSUE THREAD

**Issue by danielparks** [borgbackup/borg#1545]
It would be great to be able to set an SSH forced command to restrict prune to a certain configuration.

For example, I would like to be able to do something like `borg serve --restrict-prune-keep-daily=7`. Then if I run `borg prune . . . --keep-monthly=3` it will behave as before, but if I run `borg prune . . . --keep-daily=1` it will fail.

It would be especially rad if I could "or" this with `--append-only` so that I can either back up or prune with the same key. That would solve a typical use case of wanting to back up and then prune from a cron job.

Related:
 * [#1168 borg serve --append-only](https://github.com/borgbackup/borg/issues/1164)
 * [#1164: More borg serve restrictions for key control](https://github.com/borgbackup/borg/issues/1164)
 * [#36: the "hacked server" issue](https://github.com/borgbackup/borg/issues/36)

---

[💰 Bounty!](https://www.bountysource.com/issues/37345176-borg-serve-option-to-restrict-prune)

**Comment by ThomasWaldmann** [comment]
The "borg serve" RPC server does not "see" prune calls, it just gets lower-level get/put/delete calls done by the client. If you do not trust the client, the restriction has to be done server-side, but that's not possible if the server has no detailled knowledge about what high-level ops the client is doing.

**Comment by danielparks** [comment]
Sure, that's not surprising. I suppose the request is then to add a higher level op to the server.

**Comment by enkore** [comment]
To do a prune operation you need the keys (if it's encrypted); so the forced command would be "borg prune --prefix ...".

**Comment by ThomasWaldmann** [comment]
@enkore so, what do you want to say? that the server can't prune, because we can't give it the key?

**Comment by danielparks** [comment]
@enkore, do you mean that the prune operation requires calculations to be done on encrypted information, and thus requires access to the keys?

**Comment by enkore** [comment]
Correct.

**Comment by danielparks** [comment]
Makes total sense. Sigh. It's like my dreams of faster-than-light travel. Can't break the laws of physics or logic.
