### ISSUE TITLE
can I change max_segments_size in the config file?

### ISSUE THREAD

**Issue by qlandman** [borgbackup/borg#1548]
I have a question regarding the max_segments_size variable in the config file of a Borg repo. The default config size makes that created files in de data directory are approx. 5MB each. This is fine for backups stored on a local drive, but when I want to transfer the repo to a Webdav mount it is very slow due to the ramp up time for the file transfer.

Can I safely alter the max_segments_size variable without affecting the reliability of the Borg Backup process? What would be a sane size for each segment created. I was thinking of something between 20-50 MB for repos I want to store offsite.

**Comment by ThomasWaldmann** [comment]
borg 1.1 will use bigger segments, ~512MB.

**Comment by enkore** [comment]
1.0 has a tendency to read (download in your case) one segment for pretty much any operation that modifies archive(s). 1.1 usually doesn't do that.

Besides that there is no problem in changing it, even in existing repos.
