### ISSUE TITLE
Building and using OpenSSL 1.1.x

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1549]
The good news is that borg is ready for OpenSSL 1.1 and works with both 1.0.x and 1.1.0.

One can even have OpenSSL 1.1 on a system that usually uses 1.0.x, without risking any impact on the system (as long as LD_LIBRARY_PATH does not include the OpenSSL 1.1 lib directory):

```
# build openssl, from the openssl 1.1.x toplevel src directory:
./config --prefix=/opt/openssl11 --openssldir=/opt/openssl11/ssl
make
make test
sudo make install 
```

```
# build borg, from the borg toplevel src directory:
export BORG_OPENSSL_PREFIX=/opt/openssl11
rm borg/crypto*.so src/borg/crypto*.so
pip install -e .
```

```
# use borg, make it find openssl 1.1:
export LD_LIBRARY_PATH=/opt/openssl11/lib:$LD_LIBRARY_PATH
borg
```

**Comment by textshell** [comment]
maybe using rpath for local testing is also an idea. but i have no idea about how to get cython to pass -Wl,-rpath,/opt/openssl11/lib to the linker. More info about the concept for example here: https://www.eyrie.org/~eagle/notes/rpath.html

**Comment by ThomasWaldmann** [comment]
See also: #1550

**Comment by enkore** [comment]
Should this actually go into the docs? With OpenSSL 1.1 being more and more available, the relevance seems fading.

**Comment by ThomasWaldmann** [comment]
If we drop openssl 1.0 support in borg 1.2 / master branch, guess we should have this in the docs, e.g. for people using ubuntu thas no openssl 1.1 yet.

**Comment by ThomasWaldmann** [comment]
This piece of information could also live in the Vagrantfile, if we support testing on dists / systems that have no openssl readily available.

**Comment by FabioPedretti** [comment]
Ubuntu 18.04, to be released in a month, will have OpenSSL 1.1: https://packages.ubuntu.com/source/bionic/openssl
Still with OpenSSL 1.0: Ubuntu 17.10 (will be EOL in july 2018) and previous LTS releases (14.04 and 16.04): https://wiki.ubuntu.com/Releases

**Comment by Gu1nness** [comment]
I will update the docs for this one as well

**Comment by ThomasWaldmann** [comment]
@Gu1nness aren't all openssl 1.0.x out of support meanwhile and everybody who cares has already 1.1?

**Comment by Gu1nness** [comment]
Indeed.
Then we might close this issue then?

**Comment by ThomasWaldmann** [comment]
Yeah, let's close this.
