### ISSUE TITLE
put docs on readthedocs.org

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#155]
non-trivial as we need to install borg to generate the docs.
but install fails due to some requirements missing.

so, we need to mock the missing stuff.

rtd would be superior to what we have right now as it supports versioning and builds automatically.

**Comment by rumpelsepp** [comment]
IIRC it has virtuelenv support, so it should be doable.

**Comment by RonnyPfannschmidt** [comment]
@rumpelsepp i think the problem is requirements for compiling the c stuff, not the python side

**Comment by rumpelsepp** [comment]
ahh. true.

**Comment by anarcat** [comment]
i believe we only need the help command to work for docs to be generated, am i correct?

in this case, maybe we could focus on making that bit work through clever exception handling all over the place, no?

maybe click could help? see #251 and #208.

**Comment by ThomasWaldmann** [comment]
@anarcat yes, it is using borg help to generate these usage include files. Don't see how this is related to click.

**Comment by anarcat** [comment]
actually, thinking more aloud here: click is likely to be more a burden than helping here, because the decorators and all that stuff are likely to be outside of archiver.py, which will make it actually harder to generate the help docs.

**Comment by anarcat** [comment]
there is now #262 that should fix this, provided that repository hooks are correctly configured here (something i cannot do myself, it seems).

we will also need to update the homepage everywhere (where?) once we're happy with the switch.

**Comment by anarcat** [comment]
also note that if we have a borg domain name, we can host it on rtfd as well: https://docs.readthedocs.org/en/latest/alternate_domains.html

**Comment by anarcat** [comment]
oh and another todo here: add a neat little badge like this in the readme:

<a href="http://borgbackup.readthedocs.org/en/latest/?badge=latest" style="text-decoration: none;" onclick="$('#badge_markup').toggle(); return false;">
        <img src="https://readthedocs.org/projects/borgbackup/badge/?version=latest">
      </a>

... or wherever we have the travis badges and al.
