### ISSUE TITLE
OpenSSL: Python uses 1.0 -> no 1.1 for borg?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1550]
We can't have 2 different OpenSSL versions dynamically linked from same process, right?

So if we run with the system's Python interpreter (which will be linked against OpenSSL 1.0.x for many dists for quite a while from now), we can't use OpenSSL 1.1.x from our crypto code. :-(

A workaround might be there for the binary build: we could build a Python with OpenSSL 1.1.x and that will be bundled into the binary (together with OpenSSL 1.1 libs).

**Comment by enkore** [comment]
I'd expect that very few or no distributions ship two versions of OpenSSL (but we have to see how that plays out).

In that case either the system runs with 1.0.x and Python is linked against that, or it runs 1.1.x and Python is linked against that as well.

So this question becomes interesting if a distro ships multiple OpenSSL versions and decides to pick not-1.1 for compiling Python. In that case I would expect that this version would be the standard version available in the prefixes we search in setupy.py

**Comment by PlasmaPower** [comment]
Can we `dlopen` a different version of a library than the executable is linked against? It'd make our code rather messy though.

Given that even Arch Linux is still on OpenSSL 1.0, I'd doubt that many distros ship OpenSSL 1.1.

**Comment by ThomasWaldmann** [comment]
Just discussed with green on IRC: quite some linux dists had OpenSSL 0.9x and 1.0.x in parallel in the same dist release for some time.

So the problem left is what Python (stdlib) will link against.

Maybe it would be clever if dists packaged 2 python3 versions linked against different OpenSSL, e.g. py35+ossl10 and py36+ossl11.

Then you can choose whether you (your python dependencies) want new or old openssl.

**Comment by ThomasWaldmann** [comment]
this is how the crypto-aead branch borg with custom openssl 1.1 and system python looks like:
```
$ cat /proc/3514/maps |grep libcrypto
7f6af05f7000-7f6af0858000 r-xp 00000000 fb:01 10491                      /opt/openssl11/lib/libcrypto.so.1.1
7f6af0858000-7f6af0a58000 ---p 00261000 fb:01 10491                      /opt/openssl11/lib/libcrypto.so.1.1
7f6af0a58000-7f6af0a75000 r--p 00261000 fb:01 10491                      /opt/openssl11/lib/libcrypto.so.1.1
7f6af0a75000-7f6af0a7f000 rw-p 0027e000 fb:01 10491                      /opt/openssl11/lib/libcrypto.so.1.1
7f6af1a91000-7f6af1cc0000 r-xp 00000000 fb:01 550246                     /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f6af1cc0000-7f6af1ebf000 ---p 0022f000 fb:01 550246                     /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f6af1ebf000-7f6af1edb000 r--p 0022e000 fb:01 550246                     /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f6af1edb000-7f6af1ee8000 rw-p 0024a000 fb:01 550246                     /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

It didn't blow up. So, can this work?

**Comment by ThomasWaldmann** [comment]
I also experimented a bit about when the libcrypto is loaded: with a bare python interpreter, it is not loaded. But load is triggered by import hmac, hashlib, ssl.

So if there is an issue with having both libs loaded, we could everything via cython wrappers (and not import from hmac, hashlib, ssl). Not sure if that lib list is complete, though, or if some other lib also will import them.

**Comment by enkore** [comment]
> Because different versions of libcrypto.so and libssl.so provide the
same symbols, loading multiple versions into one process may cause a
mixture of the versions to be used, which may lead to crashes and other
nastiness.

**Comment by rugk** [comment]
Debian Stretch will have OpenSSL 1.1.x by default, so also Python should be linked against it and you should be able to use it: :tada:

**Comment by ThomasWaldmann** [comment]
@rugk ah, great to hear.

**Comment by ArchangeGabriel** [comment]
ArchLinux is also on OpenSSL 1.1 by default (but 1.0 is still available and used by some packages: https://www.archlinux.org/packages/?q=openssl-1.0), and python links against the new version.

**Comment by ThomasWaldmann** [comment]
Guess we will do it that way:

- borg 1.0/1.1 will work with both openssl 1.0 or 1.1 (whatever the system defaults to, the python was built with)

- borg 1.2 will introduce multithreading (openssl 1.1 is thread-safe by default, 1.0 is not) and also use new ciphers aes-ocb and chacha20-poly1305 (only offered by openssl 1.1), so we will require openssl >= 1.1 - maybe not initially as currently a lot of distributions (used by developers) still have 1.0 only, but a bit later.

**Comment by ThomasWaldmann** [comment]
just realized that travis-ci runs on ubuntu trusty, so if we want openssl 1.1 there, we have to install it...

**Comment by ThomasWaldmann** [comment]
Guess as everybody is switching to openssl 1.1 now or soon, this is not an issue any more.
