### ISSUE TITLE
Borg crashes after canceling of deletion

### ISSUE THREAD

**Issue by BlackLotus** [borgbackup/borg#1551]
After a delete got cancelled by accident borg now throws an exception like this https://gist.github.com/BlackLotus/5b435559c95d7ff819eec1b5fe66ecca

I'm using borg from git revision e4e678790610a67ef866d569143157d80c7f6c26 (note: master branch, changeset not in 1.0-maint).

**Comment by BlackLotus** [comment]
Ok I looked at the problem a bit and the problem was that borg tried to read a header after reaching the end of the file. For testing I added a check if the file was closed before reading the header and if so setting the header to None. After adding it borg worked again. I wanted to add a few debugging outputs after doing a borg info and a borg list, but for some reason the archive was now fixed. I removed my 3 lines of code and now the problem is gone.

**Comment by ThomasWaldmann** [comment]
@enkore can you have a look?

**Comment by enkore** [comment]
First glance: some state-tracking bug with the read FDs maybe.

**Comment by ThomasWaldmann** [comment]
move to b3?

**Comment by ThomasWaldmann** [comment]
I had a look and find it strange:
- reading at the end of a file should not give "read of closed file"
- as "fd" is used before that line in the same function and there is no close() happening there, it seems strange that it is suddenly closed

**Comment by ThomasWaldmann** [comment]
The root issue is also in 1.0-maint.

Not sure it would trigger there, but we better fix the root cause in any case.

**Comment by enkore** [comment]
Good catch! Fixed in 1.0-maint via #1643
