### ISSUE TITLE
push restore howto

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1552]
borgbackup push restore with correct uid:gid restore for file and folder ownership

Assume you have a pull backup system set up with borg, where a backup server pulls the data from the target via sshfs.

In case of a restore there is no direct way for borg to know the correct uid:gid of files, because it uses the /etc/passwd and /etc/group of the backup server. Using the archived uids/gids (no name mapping) might lead to wrong results, because after a reinstall the name-to-id mapping might have changed.

The workaround is chrooting into an sshfs mounted directory:

At the backup server do as root:

```
> mkdir /tmp/sshfs
> sshfs root@TARGETIP:/ /tmp/sshfs
> mkdir /tmp/sshfs/borgrepo
> mount --bind PATHTOREPO /tmp/sshfs/borgrepo
> cp /usr/local/bin/borg /tmp/sshfs/usr/local/bin/borg
> cd /tmp/sshfs
> for i in dev proc sys; do mount --bind /$i $i; done
> chroot /tmp/sshfs
```

Now we are on the backup system but inside a chroot with the target's rootfs.

```
> borg extract /borgrepo::ARCHIVENAME 
> exit
```

Now we left the chroot again, umount all the stuff:

```
> cd /tmp/sshfs
> for i in dev proc sys borgrepo; do umount ./$i; done
> cd /root
> fusermount -uz /tmp/sshfs
```

Thanks to secuser on IRC for this howto.

**Comment by enkore** [comment]
Or simply `borg export-tar | ssh 'tar xf -'`, if the loss of detail is acceptable.

**Comment by fantasya-pbem** [comment]
@enkore A simple ``borg export-tar`` seems not a good short alternative for a full restore. I'd not mention it is a push restore howto solution. Maybe only to make the results clear when uid/guid changes have happened.

**Comment by fantasya-pbem** [comment]
- Created a new PR.
- A "-" was missing in export-tar (FILE parameter).
- Changed -e to --exclude for better readability.
- Tested everything, works as expected.
