### ISSUE TITLE
Creating a copy of a repository to have two backup sites

### ISSUE THREAD

**Issue by kalumkalac** [borgbackup/borg#1559]
I have a huge FS of 1.5 TB backuped on one Borg repository. My goal is to have two backup sites, but I don't want to just copy the files of the first repo, but that the two repo could live on their own, as described in the [FAQ - Can I copy or synchronize my repo to another location?](http://borgbackup.readthedocs.io/en/stable/faq.html#can-i-backup-from-multiple-servers-into-a-single-repository).

My goal :
- client machine —borg create—> repo1
- client machine —borg create—> repo2

But I do not want to create a whole backup from the client machine given the size of the repository, the slow CPU and slow network connection. So what I did is rsync the first repo to the repo2, and tried to `borg create` on the repo2.

But I received this message : `The repository at location blahblablah was previously located at blahblahblah. Cache is newer than repository, refusing to continue`. It's true that I created another archive after the rsync.

But this message is telling me that borg considers that repo1 and repo2, although at different locations, are the same ones. And the cache is also somewhat "shared" between the two repos.

How do I tell borg that the repos are not the same ?

Thanks

**Comment by enkore** [comment]
> How do I tell borg that the repos are not the same ?

By changing the repository ID in the `config` file in the repo.

Note: If these are encrypted, then it's unsafe to update both "branches" of the original repository independently. This is due to the use of counting nonces, which means that nonces would be used by both "branches", but possibly for different plaintexts. This can potentially leak the plaintext to an attacker having access to both "branches".

**Comment by kalumkalac** [comment]
Thank you. That do the trick.

**Comment by rafis** [comment]
```sh
rm -rf ~/.cache/borg
```

**Comment by pmorch** [comment]
> `rm -rf ~/.cache/borg`

= Sledgehammer. I like it. :-)

**Comment by ThomasWaldmann** [comment]
Recent borg versions have `borg delete --cache-only REPO`.
