### ISSUE TITLE
Refer to proper PGP key in documentation

### ISSUE THREAD

**Issue by JensRantil** [borgbackup/borg#1560]
Somewhat related to https://github.com/borgbackup/borg/issues/734. I was looking in documentation to see which PGP key is being used for signing.

Proposal: Document it in documentation.

**Comment by ThomasWaldmann** [comment]
Idea: document it as release-signing and security contact key in README.rst, so it becomes part of the docs as well as showing up directly on github project's front page.

**Comment by ThomasWaldmann** [comment]
fixed by #1566
