### ISSUE TITLE
BORG_FILES_CACHE_TTL env var missing unit

### ISSUE THREAD

**Issue by JensRantil** [borgbackup/borg#1561]
https://borgbackup.readthedocs.io/en/stable/usage.html#environment-variables `BORG_FILES_CACHE_TTL` doesn't specify which unit the value is in. Seconds? Hours? Days?

**Comment by ThomasWaldmann** [comment]
Neither. It is "generations" kind of.

**Comment by JensRantil** [comment]
Ah. Maybe `BORG_FILES_CACHE_TTL` documentation should point to that FAQ?

**Comment by ThomasWaldmann** [comment]
Or: move that part of the FAQ to the env var description, point to there from faq.

**Comment by ThomasWaldmann** [comment]
fixed by #1566
