### ISSUE TITLE
Support to extract to path prefix

### ISSUE THREAD

**Issue by JensRantil** [borgbackup/borg#1563]
I'd like to be able to `borg extract` a specific file, but I don't want to put it in its original location. It would be useful to be able to extract a file to a custom path to inspect it etc.

**Comment by JensRantil** [comment]
I guess workaround is to FUSE mount the snapshot. Unfortunately, FUSE is not supported on all systems.

**Comment by enkore** [comment]
--strip-components also allows to remove a prefix.

**Comment by ThomasWaldmann** [comment]
... and it always extracts to current directory, in case that was unclear.

**Comment by enkore** [comment]
I believe there's an RFE to change that, but I didn't find it three hours ago, and also can't find it now... pointers? :D

**Comment by ThomasWaldmann** [comment]
Can't find it either. But OTOH, doing a "cd ..." first or using borg mount and a file manager solves this easily.

**Comment by ThomasWaldmann** [comment]
I am closing this as duplicate, we have it via the attic todo list.
