### ISSUE TITLE
Support for relaxed locking scheme

### ISSUE THREAD

**Issue by keras** [borgbackup/borg#1565]
I have a FTP server for backup storage. Closest way using it with borg would be mounting it locally via ftpfs or similar. The problem here is that locking isn't supported.

It would be great if I could define alternative repository lock path on some local fs. The feature might have it's dangers, but I think some kind of warning would suffice?

**Comment by ThomasWaldmann** [comment]
If you have a good-enough filesystem, locking should work, it is just mkdir (creating a directory).

If that doesn't work, the emulation of a filesystem is just not good enough.

**Comment by ThomasWaldmann** [comment]
Also, if not even such a simple operation works, I doubt you could use it for reliable backups anyway.

**Comment by ThomasWaldmann** [comment]
What you maybe can do to use that space is to create a backup with borg on some working / local filesystem and then use some other tool to sync it to your ftp space, so you have a remote copy in case you lose your local repo.

**Comment by ThomasWaldmann** [comment]
Closing this, not actionable.

**Comment by enkore** [comment]
> The problem here is that locking isn't supported.

How? Do you get an error?

**Comment by keras** [comment]
Oh nevermind updated and it's working now.
