### ISSUE TITLE
implement a break-lock command

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#157]
locks might be left over by crashing borg processes and they have no timeout (backups can take long, so timeout is problematic).

but there should be a nice way to force breaking a lock without having to manually find the cache directory and the repo directory and removing the "lock" directory there (presence of that directory means "locked").

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/25944194-implement-a-break-lock-command)

**Comment by neutrinus** [comment]
If we would have a pidfile then Borg could check if the process still exists..  

Obviously it won't work with fuse mounted repository :)

**Comment by ThomasWaldmann** [comment]
Note: not only the lock.exclusive needs to be broken, also kill the lock.roster (if there is a shared lock in there, an exclusive lock acquire will wait for it to go away, which might never happen if the respective process is dead).

**Comment by rumpelsepp** [comment]
Just thinking: What about `--force` for the interface?

**Comment by ThomasWaldmann** [comment]
the command is meant as a separate command, not as a --force option for other commands.
it's not a good idea to force override locking if one did not make first sure that not other process is running.
