### ISSUE TITLE
`Edit on GitHub` link on borgbackup.readthedocs.io does not work.

### ISSUE THREAD

**Issue by weakish** [borgbackup/borg#1570]
It points to `https://github.com/borgbackup/borg/blob/HASH/docs/*.rst` and gets `404`.

I think the url should be `https://github.com/borgbackup/borg/edit/master/docs/*.rst`.

**Comment by ThomasWaldmann** [comment]
See also: #766, #689, #451 and #413.

**Comment by ThomasWaldmann** [comment]
This is covered there https://github.com/rtfd/readthedocs.org/issues/1820 thus I am closing it here.
