### ISSUE TITLE
more informative IntegrityError

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#1571]
IntegrityError should whenever possible include the chunk id where the problem was encountered.

Currently the error message just says that a specific problem happened on some chunk without nameing the chunk id. That does make debugging and fixing hard. With the chunk id there is at least some chance to drill down and come up with some fix.

**Comment by ThomasWaldmann** [comment]
Note:
- the IntegrityErrors raised from borg.repository are quite nice already (include segment/offset - but not object id yet). 
- the ones raised from borg.key are rather bare, no info at all yet.
- we should not call it *chunkid* (not every object in the repo is a chunk), so, just *id* or *object id*?

**Comment by ThomasWaldmann** [comment]
See PR #1034: "borg.key: include chunk id in exception msgs" - stay close to that to avoid merge conflicts?

**Comment by ThomasWaldmann** [comment]
key.py: backported the stuff from PR #1034.

repository.py: kept as is, addressing on repo level is segment/offset, the chunk id is not generally available, thus I did not add it.

wording: I kept "Chunk", it is used all over the place. If we want to change it, this needs a separate cleanup PR.

**Comment by enkore** [comment]
✓#1690
