### ISSUE TITLE
add placeholder to IntegrityError docstring

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#1572]
It seems all callers pass details to IntegrityError, but they are only output via the traceback not via the main exception message, because the doc string is missing a placeholder.

**Comment by ThomasWaldmann** [comment]
Note: also check other Error subclasses. This is problematic esp. for the Errors that do not output a traceback.

**Comment by enkore** [comment]
#1692

**Comment by ThomasWaldmann** [comment]
@enkore no, that's all. I had a look at other Error subclasses' docstrings, but they looked ok.
