### ISSUE TITLE
borg check --verify-data always decompresses

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1573]
encrypted repo:
- gets object
- verifies MAC, decrypts (if successful, we know data is ok)
- decompresses (not strictly needed)
- asserts H(data) == id (not strictly needed)

not encrypted repo:
- gets object
- decompresses (here it is needed, for next step)
- asserts H(data) == id

As decompression might be relatively expensive, we could maybe optimize this so it is not used on encrypted repos.

**Comment by ThomasWaldmann** [comment]
Hmm, the H(data) == id check makes sure even a evil repo could not give us correctly-signed-by-us-different-data.

**Comment by enkore** [comment]
^ Perhaps add the AEAD part to the crypto ticket.

Apart from that there doesn't seem do be anything to do here.

**Comment by ThomasWaldmann** [comment]
No, as layed out in the top post, decompression is not necessary to verify integrity of authenticated data (== for encrypted repos).

**Comment by enkore** [comment]
> Hmm, the H(data) == id check makes sure even a evil repo could not give us correctly-signed-by-us-different-data. Using a AEAD cipher, this could be optimized by putting the id into the AD part.

**Comment by ThomasWaldmann** [comment]
Ah, right. I missed the different-data aspect. But still, we can optimize this later, so keep it open.

**Comment by enkore** [comment]
There is still the argument for doing it: Authenticating the chunk ID only shows what the writing client *thought* it wrote, not what is actually in the repository. Write-time corruption of the chunk or it's ID or the compressed form or a compressor bug would not be noticed this way.

**Comment by elho** [comment]
> There is still the argument for doing it: [...]
> 
> I think --verify-data being a very thorough check really ought to cover these cases. It already does; no reason to weaken it.

Indeed.  Also, in many cases that involve remote repositories, network bandwidth wll be main bottleneck anyway. Especially as decompression tends to be a good deal faster than compression, even for the slow algorithms in borg.

How about leaving `--verify-data` untouched, but adding a extra option like `--verify-crypto` (or some better name :wink:) that performs the weaker optimized variant.

**Comment by ThomasWaldmann** [comment]
OK, we keep --verify-data as is, no change here.

About extending AEAD cipher protection:

We could just feed in `chunk_id` (guess `chunk_length` is not useful / not needed) as AAD so it gets included in the auth tag computation.

But we would **not** put them into the data layout we give to `repo.put(id, data)`, because there is code on the repo side that adds crc32, `chunk_length`, PUT and `chunk_id` in front of the data we give.

This would be nice as currently only the weak crc32 spans over all this.

When reading, we would also feed the `chunk_id` we wanted (and the `chunk_length` we got?) as AAD.

If it does not blow up when verifying the tag, we know that we have written the data we got for the chunkid we wanted now.

What do you think?

**Comment by ThomasWaldmann** [comment]
Just noticed that the diagram already shows feeding the chunkid in as AAD. Just need to implement it...

**Comment by ThomasWaldmann** [comment]
closing this, nothing to do here.
