### ISSUE TITLE
segfault with borg 1.1.0b1 binary

### ISSUE THREAD

**Issue by nizedk** [borgbackup/borg#1578]
Segmentation fault on Ubuntu 16.04.1, borg-linux64 1.1.0b1

Hi,

I have a problem with the binary build of borg-linux64 1.1.0b1; it segfaults on all of the machines I've tried it on (3 different boxes).

[  139.479365] borg-linux64[1459]: segfault at 0 ip 00007f26a1908d16 sp 00007ffece574c58 error 4 in libc-2.23.so[7f26a187e000+1c0000]

I download it with wget, I chmod +rx it, and that have worked everywhere until now.

I've tried removing my borg folder from .cache without any result.

I have attached a strace file for reference; [strace.txt](https://github.com/borgbackup/borg/files/456654/strace.txt) - if a core dump would be of use, I can provide that as well.

**Comment by ThomasWaldmann** [comment]
Can you add the OS of these 3 different boxes? I am sure it worked on SOME machine here. :)

As a side note: the borg beta is currently using a master branch version of pyinstaller as we needed some changes that are not released yet. I hope there will be a release until we want to release borg 1.1.

**Comment by nizedk** [comment]
"uname -a" and "cat /etc/issue" from 3 boxes

```
Linux very 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04.1 LTS \n \l
```


```
Linux icebox 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04.1 LTS \n \l
```

```
Linux mje-psql-test01 4.2.0-36-generic #41~14.04.1-Ubuntu SMP Tue Apr 19 17:03:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 16.04.1 LTS \n \l
```

... so there is a pattern, I didn't notice immediately. It works on a 12.04.5 I found.

So.. something related to 16.04 LTS?

**Comment by ThomasWaldmann** [comment]
I could reproduce here, some stuff from gdb:
```
Starting program: /home/tw/borg-1.1.0b1/borg-linux64 
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) backtrace
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff7629ba9 in __add_to_environ (
    name=0x405da8 "LD_LIBRARY_PATH_ORIG", value=0x0, combined=0x0, replace=1)
    at setenv.c:131
#2  0x0000000000404688 in ?? ()
#3  0x0000000000402db3 in ?? ()
#4  0x00007ffff7610830 in __libc_start_main (main=0x401950, argc=1, 
    argv=0x7fffffffdaf8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdae8)
    at ../csu/libc-start.c:291
#5  0x000000000040197e in ?? ()
```

**Comment by nizedk** [comment]
Awesome!('ish)

I was worried it was something I did wrong, or that I've somehow tainted my boxes. :-)

**Comment by ThomasWaldmann** [comment]
Oops, my fault. :-(
Try setting LD_LIBRARY_PATH=/foobar.

**Comment by nizedk** [comment]
Great success! :-)

**Comment by nizedk** [comment]
Thank you for the help, I can now continue testing the new awesome features. :-)

**Comment by ThomasWaldmann** [comment]
@enkore 1.0.7 is not affected, other version of pyinstaller there.

**Comment by enkore** [comment]
Yes, I noticed that as well :D

**Comment by ThomasWaldmann** [comment]
I am reopening this. While we have a workaround, it needs a new pyinstaller bootloader and a new borg binary release to fix it.

**Comment by ThomasWaldmann** [comment]
Affects: 1.1.0b1, linux and freebsd binaries. macosx should be fine.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/322d2176770bbf06d0854cf6053dfb5ac59cf02e will fix this in the next binary build.T
