### ISSUE TITLE
debug-put and debug-delete do not update chunks index

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1587]
These commands are quite low-level and simplistic - maybe a bit too simple?

If they do not update the cache, it will be out-of-sync with the repo.

And: borg won't notice that it is out of sync.

**Comment by textshell** [comment]
It might be a concern, but i think these are used for patching problems. So they are supposed to be minimal building blocks without much smarts. i.e. one use for delete is forcing borg repair to do other repair steps. Maybe we need some kind of high-level commands, but the cache is supposed to be a reflection of the archive metadata so there is not really much these commands could do anyway, is there?

**Comment by ThomasWaldmann** [comment]
put: if a new object ID is put, it is not referred to by any archive metadata. and we can do nothing about that (so writing some refcount 1 into index is futile). if an existing ID is put (supported?), we do not want to change refcount.

delete: if we delete a previously existing ID from the repo, all potential references to it (e.g. from archives) will be invalid. but we can't (and likely do not want to) fix archives within the debug cmd, so changing refcount in index also seem inappropriate as it would not reflect the state of the archives.

so, guess the debug cmds should not be changed functionally.
maybe it should be documented that they have these effects at least.

**Comment by ThomasWaldmann** [comment]
solved by PR #1666.
