### ISSUE TITLE
Allow user to change SSH timeout

### ISSUE THREAD

**Issue by Airaiche** [borgbackup/borg#1589]
Hi,

I use a wrapper script for borg, and one of the backup destinations is a local IP address I connect to via SSH. Being a local address, it isn't accessible when I'm not home, which makes borg hang for a too long time.

I know I can change SSH's ConnectTimeout option, I did it, but I would like to keep the default timeout for normal connections, and set it to a short time (2 seconds) just for borg.

A command line option like --ssh-timeout=2s would be perfect for that. Could it be implemented ?

Thanks !

**Comment by enkore** [comment]
The [`BORG_RSH`](http://borgbackup.readthedocs.io/en/stable/usage.html#environment-variables) environment variable allows this.

E.g.

`BORG_RSH="ssh -o ConnectTimeout=1234" borg create ...`

```
export BORG_RSH="ssh ..."
borg create ...
```
