### ISSUE TITLE
aes-gcm weak key detector neccessary / nice to have?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#160]
http://www.iacr.org/archive/fse2012/75490220/75490220.pdf

if somebody fully understands this paper, a comment about the following would be very welcome:

should we implement a aes-gcm weak key detector to sleep better at night?
(the detector would get a key as input and would have to qualify its strength)

we currently use AES256-CTR + HMAC-SHA256, but in experimental branch there is some more efficient, hardware accelerated AES256-GCM AEAD code we could use.

Update:

I put a bounty on this, it is for writing python code (+ unit tests) that detects if a given key has the problem described in the paper.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/26013514-aes-gcm-weak-key-detector-neccessary-nice-to-have)

**Comment by KarstenHohmeier** [comment]
Hello,
The paper states that hitting a problematic AES key will reduce the cycle length of GHASH. The worst case is apparently a cycle length of 1, where all created cyphertext blocks would have an identical GHASH value. In this worst case the content of any two data blocks could be swapped by an attacker. In "milder" cases of reduced cycle length a hash collision simply becomes more likely.
I am not familiar with the borg-internal key->value storage parts. If the hashes are also they keys, an archive created with a problematic AES key might also have serious issues with deduplication not working as intended. Would hash collisions in the ENCRYPT/MAC parts be problematic for the data storage of borg?

**Comment by ThomasWaldmann** [comment]
currently, master branch code uses sha256 as id_hash function (to compute the keys for key/value store). in experimental branch, I did experiments with using ghash as id_hash.

The encryption/authentication is separate from that and aes-ctr/sha256 in master. In experimental branch, I have some code that uses aes-gcm for AEAD.

**Comment by KarstenHohmeier** [comment]
If AES-GCM were to be used for encryption/authentication and the GHASH value was reused as id_hash, then borg could hit one of those cases where a problematic AES key leeds to undetectable repository corruption due to more likely hash collisions.
Since the check for a weak key has to be only done once - on repo creation - I would sleep much better if a check was done.
By the way: Even SHA256 has a (very small) probability for a random hash collision. Would a colliding block of data be always deduplicated away in the current codebase? Or is there a second line of defense against that?

**Comment by ThomasWaldmann** [comment]
Agreed that such a check would be nice. Now we just need some mathematically inclined python developer writing the code. :)

About sha256 collisions, see #170 .

**Comment by KarstenHohmeier** [comment]
I looked at experimental/borg/borg/crypto.pyx. Is there a way to get the root authentication key after setting up the EVP_CIPHER_CTX cipher context? I tried to read evp.h, but it scared me :)

**Comment by ThomasWaldmann** [comment]
Well, in the python code we fetch the AES key from the keyfile (see key.py).

**Comment by KarstenHohmeier** [comment]
That is not what I meant. The root authentication key H, is the start value for the hash. The paper said this should be H = EK(0). Since AES-GCM is single pass, that value should be somewhere in the encryption context. If you get it out after setting up the context, you could do the exponentiation test against it to look for weak keys.

**Comment by ThomasWaldmann** [comment]
Ah. No idea then, sorry.

**Comment by lichtkegel** [comment]
I made a gist that should implement the test you want. I also handed this in on bountysource, because, why not.

https://gist.github.com/lichtkegel/7a8baae97993ca20430f

**Comment by ThomasWaldmann** [comment]
Current code: https://github.com/lichtkegel/aestools

**Comment by ThomasWaldmann** [comment]
@KarstenHohmeier can you review that code? ^^^

**Comment by KarstenHohmeier** [comment]
Sure thing. But give me a couple of days.

**Comment by ThomasWaldmann** [comment]
@lichtkegel don't forget to claim the bounty.

**Comment by ThomasWaldmann** [comment]
This issue can be closed, the weak key detector code has been implemented by @lichtkegel in the aestools pypi package. More review is welcome.

**Comment by KarstenHohmeier** [comment]
I looked at the code published here: [https://pypi.python.org/packages/source/a/aestools/aestools-0.1.0.tar.gz#md5=469092df8eb9121095f6ebed0cc434cc]

My First question was: Do we really get *H* from encrypteing *0* with the key *K*?
**Fig.1.** from the paper suggest this. So this seems correct.

Then I looked at the test of *H*:

take all the factors
`factors = (3, 5, 17, 257, 641, 65537, 274177, 6700417, 67280421310721)`
set order to 1
`order = 1`
for every factor
`for factor in factors:`
calc the exponent ((2^128-1)/p) as in the paper
`    n = ((1 << 128) - 1) // factor`
if the exponentiation of *H* does not equal 1
`    if gf_2_128_exp(x, n) != 1:`
then the factor is also a factor of the order of *H*
(*"If and only if p divides ord(H) ..."*)
`        order *= factor`
`return order`

This is exactly what the paper suggests for testing.

I withhold judgement on the other two helper functions *def gf_2_128_mul(x, y)* and *def gf_2_128_exp(x, n)*. At the time present I cannot wrap my head around this bit for bit. *gf_2_128_exp* is recursive, which does not make things easier.

If we assume, that they correctly do, what the names suggest, exponentiation and multiplication for the 2^128 Galois field, then this is a proper implementation of the AES-GCM weak key test as suggested in [https://eprint.iacr.org/2011/202.pdf].

Is there anybody here who is fit in crypto arithmetics and can verify the *gf_2_128_mul(x, y)* and *def gf_2_128_exp(x, n)* functions?

**Comment by ThomasWaldmann** [comment]
Reopened so discussion does not happen on a closed ticket.
Maybe this could be also moved to the aestools issue tracker?
Do the gf_2_128_mul/exp functions have unit tests?

**Comment by KarstenHohmeier** [comment]
For the functions themselves, no. But there are some global tests against known weak (from the paper) and known strong keys.

**Comment by lichtkegel** [comment]
@KarstenHohmeier and others: If it helps, the `gf_2_128_exp` function is [basic exponentiation by squaring](https://en.wikipedia.org/wiki/Exponentiation_by_squaring#Basic_method) and relies on the correctness of the `gf_2_128_mul` implementation.

**Comment by lichtkegel** [comment]
Turns out there actually *was* a mistake in the finite field implementation. The way the polynomial is stored, the element `1` actually corresponds to the value `1<<127`. That was even noted explicitly in the paper, but I somehow screwed that up. Interestingly, it did not affect any of our tests. We need more tests.

**Comment by ThomasWaldmann** [comment]
@lichtkegel good catch!

I'm closing this again. Please move all still relevant stuff from above and file all new issues relating to aestools (and not borg / borg using aestools) to the aestools tracker.
