### ISSUE TITLE
borg check --verify-data should be faster

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1600]
I am running borg check --verify-data on my local repo (via WiFi), it is running since ~12h and at ~20% now, so it'll take ~2.5d total, which is a bit much considering I have a fast, low latency connection and the repo is not very big (~400GB).

Also, the CPU load on the client is between 3 and 13 percent for borg, so it seems it is waiting most of the time. When I was near the server, I was hearing lots of random-access disk noises.

Some unchecked ideas:
- use get_many?
- do a linear scan over the segments instead of iterating over chunks index?

**Comment by enkore** [comment]
Yes to both.

Originally we needed to query the cache because we only wanted to check chunks covered by the archive selection, but since that was removed this is an unnecessary performance reduction.

**Comment by ThomasWaldmann** [comment]
linear scan doesn't work, no api for that. but I am implementing get_many().

**Comment by enkore** [comment]
Ah right, I somehow thought that the items lits was sorted by segment.

**Comment by ThomasWaldmann** [comment]
This ticket is about get_many and other minor optimisations, i moved the more complicated part to #1610.

**Comment by ThomasWaldmann** [comment]
Fixed in master branch by #1607.
