### ISSUE TITLE
Allow multiple paths for restrict-to-path

### ISSUE THREAD

**Issue by icefoxen** [borgbackup/borg#1602]
Specifically, I want a client to be able to back up two file systems to a borg server: / and /home .  These are on separate disks and should be handled separately anyway, and `borg create -x` is used by the client to restrict backups to one filesystem at a time.

Now it used to be the case that I could put "borg serve --restrict-to-path /srv/bak/borg/foo" in the command section of the server's .authorized_keys file, and it would allow the system to make backups in both the `/srv/bak/borg/foo` and `/srv/bak/borg/foo-home` directory.  I lately upgraded to borg 1.0.7 and it no longer allows that to be the case, saying "Repository path not allowed".  I certainly agree that this is probably the right thing, but it would be nice if I could give multiple arguments to `--restrict-to-path` instead of forcing it to use different SSH keys.

Thanks.

**Comment by icefoxen** [comment]
...Okay, I feel a bit dumb, 'cause it appears I can just do `borg serve --restrict-to-path /srv/bak/borg/foo` and make directories `/srv/bak/borg/foo/root/` and `/srv/bak/borg/foo/home`.  Works great!

HOWEVER!  It might still be useful for people to be able to restrict to multiple paths?  Or at least for the above pattern to be mentioned in the docs, and the `--restrict-to-path` help to mention it allows subdirectories but not names starting with the same path prefix.

**Comment by ThomasWaldmann** [comment]
Try borg serve --restrict-to-path p1 --restrict-to-path p2.

**Comment by icefoxen** [comment]
Tried that and it didn't *seem* to work.  Gave me the same error message.

**Comment by ThomasWaldmann** [comment]
Fixed by #1677.
