### ISSUE TITLE
Consider changing {utcnow} and {now} to a format without embedded space.

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#1606]
Maybe the separator could be '_' instead.

Why? Handling archives names with embedded spaces is annoying on the commandline. It just irks me every time i need to move back to add quotes.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/37921249-consider-changing-utcnow-and-now-to-a-format-without-embedded-space)

**Comment by enkore** [comment]
Agreed. There's a standardized format for it w/o the space (the ISO format, 2016-12-13T14:15:16). 

![8601](https://imgs.xkcd.com/comics/iso_8601.png)

:)

**Comment by textshell** [comment]
I think the easy label only if we can agree on a format. Disregarding the suggestions from xkcd(which also doesn’t tell us what separator to use for time^^) we currently have "T", " " (no change) and "_" as proposed separators.

I personally prefer "_" because it is easy on tokenizers used in shells and on the eye. Downside is that is not the iso standard, but i don‘t think that using a different separator will pose a problem for interpretation (the intend to basically use the iso field order should still be clear) or for parsing (just replace "_" vefore using an iso compliant parser, maybe adding a "Z" which the borg UTC format also "lacks")

**Comment by ThomasWaldmann** [comment]
Well, I personally don't like that T too much, but it is the standard.

But the blank is also somehow bad, because it will cause separation on the shell and one needs to quote to avoid that, which is a pain.

So while I would find "_" prettier, I can live with "T".
