### ISSUE TITLE
More intuitive use of --stats, --list, etc.

### ISSUE THREAD

**Issue by mantlepro** [borgbackup/borg#1609]
--stats, --list, etc. do not output any info without -v or log level escalation. --list, --stats and others should imply (automatically enable) -v without explicit need for -v switch to be present as a command line arg.

**Comment by ThomasWaldmann** [comment]
this is already changed in borg master branch (and will be in borg 1.1).
it's not as easy as just enabling -v, because that would also enable other -v output...
