### ISSUE TITLE
don't have multiple debug subcommands by default

### ISSUE THREAD

**Issue by hpk42** [borgbackup/borg#1627]
the "borg help" is cluttered with debug subcommands.  Maybe hide them by default?  Or merge them into a single sub command?

**Comment by ThomasWaldmann** [comment]
@hpk42 yes, carefully introducing subcommands is currently being considered.

**Comment by enkore** [comment]
Mostly fixed in #1636

**Comment by enkore** [comment]
Todo left: remove debug-XXX from master - maybe just them showing up, but still accept them (for easier from-the-top-off-the-head debugging advice etc - don't have to distinguish versions and so on).

**Comment by ThomasWaldmann** [comment]
I'ld say either just remove them in 1.1 (they are not automatically used and not even frequently used) or deprecate them for removal in 1.2.

**Comment by enkore** [comment]
Another point in this direction would be that when debugging on this level you already know the version and it's unlikely to have "commercial off the shelf" instructions involving these anyway.

**Comment by ThomasWaldmann** [comment]
I'll remove the debug-xxx form. See above + archiver.py is too big anyway.
