### ISSUE TITLE
Source folder "grows" after checkpoint resume

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1630]
So i backupped a folder with some huge mail dirs and several sparse files. Nothing special. But the process was stopped two times. Once by  #1628 and once by me. 

The weird thing is borg thought the source directory / original archive size "grew"/doubled after resume. And i can assure you it did not. I made sure that there won't be any writing to the source dir it while borg is running. It also took quite some time. 24+h.

Also the dedup size does not add up. These 3 are all the archives in the repo. There is nothing else.

Last to first run:

	$ borg info /mnt/nas-03/borgbackup/::2016-09-22-vps_backup
	Name: 2016-09-22-vps_backup
	Fingerprint: 972856f7536bf72296d2c91cc3bb5a0bbc0fa74c1cac0b93a5b7e8be0584703e
	Hostname: host
	Username: root
	Time (start): Thu, 2016-09-22 23:41:12
	Time (end):   Fri, 2016-09-23 04:43:02
	Command line: borg create -vpsC lz4 /mnt/nas-03/borgbackup/::{now:%Y-%m-%d}-vps_backup /vps_backup --exclude=*[cC]ache*
	Number of files: 8395563

		               Original size      Compressed size    Deduplicated size
	This archive:              813.76 GB            131.51 GB              5.91 GB
	All archives:                1.45 TB            342.75 GB             86.04 GB

		               Unique chunks         Total chunks
	Chunk index:                  773217             17735878

	$ borg info /mnt/nas-03/borgbackup/::2016-09-22-vps_backup.checkpoint
	Name: 2016-09-22-vps_backup.checkpoint
	Fingerprint: b35e4f57fa7b6f7455c7fc7d50cecaf7e97e79e967e17140f2c88581cc7c77c1
	Hostname: host
	Username: root
	Time (start): Thu, 2016-09-22 11:06:29
	Time (end):   Thu, 2016-09-22 23:15:50
	Command line: borg create -vpsC lz4 /mnt/nas-03/borgbackup/::{now:%Y-%m-%d}-vps_backup /vps_backup --exclude=*[cC]ache*
	Number of files: 8393152

		               Original size      Compressed size    Deduplicated size
	This archive:              423.63 GB            113.70 GB             37.93 MB
	All archives:                1.45 TB            342.75 GB             86.04 GB

		               Unique chunks         Total chunks
	Chunk index:                  773217             17735878

	$ borg info /mnt/nas-03/borgbackup/::2016-09-22-vps_backup.checkpoint.1
	Name: 2016-09-22-vps_backup.checkpoint.1
	Fingerprint: 146d2db4f3d27bd916bcd3b18779b65c03b13f36c8351d401c27940a4809ead2
	Hostname: host
	Username: root
	Time (start): Thu, 2016-09-22 23:25:32
	Time (end):   Thu, 2016-09-22 23:32:16
	Command line: borg create -vpsC lz4 /mnt/nas-03/borgbackup/::{now:%Y-%m-%d}-vps_backup /vps_backup --exclude=*[cC]ache*
	Number of files: 567673

		               Original size      Compressed size    Deduplicated size
	This archive:              211.85 GB             97.55 GB             30.60 kB
	All archives:                1.45 TB            342.75 GB             86.04 GB

		               Unique chunks         Total chunks
	Chunk index:                  773217             17735878

**Comment by ThomasWaldmann** [comment]
Not sure what you mean. The early 2 archives are checkpoint archives, so they only have a part of your files. You can delete the checkpoint archives (AFTER you made a successful, complete backup of same dataset).

The "number of files" and "size" values refer to the archive contents, not to the whole source data set.

I'ld suspect the huge "orig size" and small "dedup size" in the 2 checkpoint archives comes from deduplication against some earlier backup archive (or checkpoint archive) you made.

Alternatively, it could be files with huge sparse areas, they are read as zeros and of course deduplicate well.

**Comment by lightonflux** [comment]
> I'ld suspect the huge "orig size" and small "dedup size" in the 2 checkpoint archives comes from deduplication against some earlier backup archive (or checkpoint archive) you made.

There was never another archive in the repository. 

What i don't understand is why the orig archive doubles in size.

**Comment by enkore** [comment]
Which version was this on?

**Comment by lightonflux** [comment]
1.0.7

**Comment by lightonflux** [comment]
BTW: Is there an issue about handling checkpoint transparently? Looks a bit ugly in the borg list repo listing.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/1630#issuecomment-249123456 updated that comment with a more correct explanation.

**Comment by lightonflux** [comment]
Thanks @ThomasWaldmann 

> checkpoints will be handled a bit differently in borg 1.1.

Looking forward to it!
