### ISSUE TITLE
Placeholder for `current_time.isoformat()`

### ISSUE THREAD

**Issue by blueyed** [borgbackup/borg#1638]
As a followup to https://github.com/borgbackup/borg/pull/692/files#diff-794f4bac1dcee9a81389fd1d2ae14221R699:

What do you think about having a `nowiso` placeholder for `current_time.replace(microsecond=0).isoformat()`?

Not sure if it should be added also as `utcnowiso`.

I think this is much better than the default that `{now}` provides, which will contain spaces and needs to be quoted on the shell therefore.

**Comment by enkore** [comment]
#1625?

**Comment by RonnyPfannschmidt** [comment]
i think so,  too

**Comment by blueyed** [comment]
Exactly, thanks!
