### ISSUE TITLE
error with borg create

### ISSUE THREAD

**Issue by jots** [borgbackup/borg#164]
using Borg 0.24.0.
after 70GB of chugging along, got this:
  File "/usr/local/lib/python3.4/dist-packages/borg/archive.py", line 433, in process_symlink
    source = os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/10/exe'

borg: Exiting with failure status due to previous errors

also it seems that borg does not follow symlinks.  Is there a way to tell it to follow symlinks?

**Comment by ThomasWaldmann** [comment]
well, it maybe does not look like, but this is just a warning - it did not find that file (which is nothing unusual in /proc and you should not backup /proc anyway).

borg emits that warning, but continues with the next file (please verify that by borg list repo::archive and close the issue if you  have all other files).

The message at the end is a bit misleading, it just means that there were some issues (some files not backed up), but all other files were backed up. There is already another ticket about improving the logging in misc. ways.

Usually one either exludes /dev /proc /sys or one reassembles all the useful filesystems (with the virtual ones) using "mount --bind" at a separate location that gets backed up.

About symlinks: borg backups a symlink as a symlink (and does not follow), so you get precisely what you had after a restore. if you want to backup the target items pointed to by the symlink, you must use the target name.

If you think it makes sense to follow symlinks (optionally), please open a separate ticket for that and explain the usecase where it makes sense / is preferable to what we do now.

**Comment by ThomasWaldmann** [comment]
@jots if my answer solves your issue, please close.

**Comment by ThomasWaldmann** [comment]
@jots any news?

**Comment by ThomasWaldmann** [comment]
no reply, assuming it is solved.

about the log output: there is a general ticket about improved logging.
