### ISSUE TITLE
borg binaries not working on VMware ESXi 6.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1642]
borg 1.0.7 linux 64bit binary

```
[root@esx102:/vmfs/volumes/xxx] ./borg -V
Fatal Python error: Py_Initialize:  Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0xffdb15e0 (most recent call first): Aborted
```

Workaround is to:

```
export TEMP=/somewhere
./borg ...
```

We checked:
- binary sha256 is valid
- /tmp has enough free space
- /tmp/_MExxxxx/base_library.zip is valid (it contains the encodings package)
- glibc is 2.12 (the binary requires 2.13 only for "resource" module)

**Comment by enkore** [comment]
Hm, maybe noexec on /tmp?

**Comment by ThomasWaldmann** [comment]
Tried to check that, but neither /proc/mounts nor "mount" gave info about root fs or /tmp fs mount.

**Comment by grogthegreat** [comment]
I'm not a programmer but I'm willing to help someone test. I have three ESXi 6.0 hosts that I'd love to use borg on.

**Comment by grogthegreat** [comment]
If anyone wants to take this on, here are the errors I'm seeing when I try to init a repo or create a backup.
[Borg1.0.9ESXi6.0Errors.txt](https://github.com/borgbackup/borg/files/679455/Borg1.0.9ESXi6.0Errors.txt)

**Comment by ThomasWaldmann** [comment]
Not sure if it helps, but maybe worth retrying this with borg 1.0.10rc1 binary when it is released (soon).

It will include a fixed pyinstaller bootloader and also a more recent python 3.5.3 (with quite some fixes).

**Comment by grogthegreat** [comment]
Tested the debug version of the 1.0.10rc1 binary.
SHA256: 4565E83E1C9B23C46D6C7782B77A189F24F4CB89D56140090257F02DED812305

I have to run export TEMP=/vmfs/path in order to get ./borg -V working.
I then get the following errors when I try to init or backup to a repo.
https://pastebin.mozilla.org/8970858
My best guess is that python is doing something that works in a linux OS but isn't supported in ESXi6.0.

**Comment by enkore** [comment]
The trace would suggest that Python is trying to use things like `fdopendir(2)` ... likely because these were built on Linux with a Python that has these configured in, while ESXi does not implement these syscalls.

**Comment by ThomasWaldmann** [comment]
Maybe people should just use Proxmox PVE, there is a real (debian) linux at the base of it. ;-)

Also: FOSS.

**Comment by enkore** [comment]
I suppose a way around this would be to either built it on ESXi directly or build it with a Python built on Linux that has been configured/tuned for ESXi compatibility.

**Comment by grogthegreat** [comment]
Thanks for all the replies. Please let me know if there are any other tests I can run. While ESXi isn't FOSS, it does have a very large user base with lots of people using their free version. It is the only option for me since I'm running hyperconvered with ScaleIO which is free for personal use.

**Comment by ThomasWaldmann** [comment]
Is this still an issue with more recent esxi and borg releases?
If so, can someone please file a new bug about it?

**Comment by horihel** [comment]
I just stumbled on this - 1.1.6 and ESX 6.7 don't cooperate.
```
[root@localhost:~] export TEMPFILE=/vmfs/volumes/datastore1/temp
[root@localhost:~] /vmfs/volumes/datastore1/borg-linux64-1.1.6
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x000000139b40f080 (most recent call first):
Aborted
[root@localhost:~]
```

**Comment by ThomasWaldmann** [comment]
Can you just use a normal, local posix filesystem (not a cluster vmware fs, no vfat) for your temp files?

Also, the permissions on your temp dir are incorrect. This is how it usually looks like on a linux system:
```
$ ls -ld /tmp
drwxrwxrwt 61 root root 36864 Aug  7 13:23 /tmp
```

**Comment by horihel** [comment]
I'm afraid the ESX console doesn't support any filesystems (there isn't even a traditional mount command).

I fixed permissions - no change.

to be honest, as the ESXi console is not actually running on linux (at least not normal linux) it might be ok to stop trying.

```
[root@localhost:~] uname -a
VMkernel localhost.head.de 6.7.0 #1 SMP Release build-9214924 Jul 18 2018 19:07:37 x86_64 x86_64 x86_64 ESXi
```

**Comment by ThomasWaldmann** [comment]
as it doesn't look like this can be fixed and is an issue outside of borg, i am closing this.
