### ISSUE TITLE
cryptic errors when accessing remote archives when llfuse and fusermount are missing

### ISSUE THREAD

**Issue by joshmyzie2** [borgbackup/borg#1647]
I had set up a remote borg repository on a Debian Jessie server using the jessie-backports package.  I was able init, create, and mount the archives with no problems, but after I tried using the mounted archive files on my local machine I got errors.  Using `cat` or `file` on the files gave me an input/output error and using `cp` on the files resulted in empty files being created.

I was able to find the problem by mounting the archives locally on the remote server, which then produced an error saying that it failed to import `llfuse`, so I installed `python3-llfuse`.  Then after trying to mount locally again, I got an error saying that it couldn't find `fusermount`, so I installed `fuse`.  I was then able to mount and access the archive files both locally and remotely.

Is there a way to make these errors visible when mounting remote repositories?
And should these two packages be added as dependencies for the Debian package?_

**Comment by ThomasWaldmann** [comment]
you don't need fuse / llfuse on the borg server if you want to use borg mount on the client.
because of that, the fuse stuff should not be added as requirement (but maybe as "suggested").

you only need them on the machine where you want to run borg mount.

it would be helpful if you could add following infos to your original post:
- borg versions
- exact sequence of commands that reproduces the problem you have seen
- make sure to make clear what commands are run where

**Comment by joshmyzie2** [comment]
That's strange then because I didn't change anything on the client machine, but after installing fuse and llfuse on the remote repository server, the fuse mounted files started working on the client.

I'm using 1.0.7 on both client and server.

On the client I had run
```
borg mount ssh://backup_user@remote_host:2222/home/backup_user/repo::local_host-20160926 /tmp/backup
cp /tmp/backup/file /tmp/
```
And the copied file was empty.  If I ran `cat /tmp/backup/file` on the client, I got and input/output error.

After running on the remote repository server:
```
apt-get install python3-llfuse
apt-get install fuse
```
the previous mount commands worked fine.

It's all working great now, so feel free to just close this if whatever problem I had isn't obvious to you.

**Comment by joshmyzie2** [comment]
Ok, actually ignore everything I said. :)

The problem is actually triggered when I run `borg mount` from emacs eshell.  If I mount it from there, then even accessing the files from a normal bash shell produces the input/output errors.  It has nothing to do with fuse/llfuse being installed.

I'll just close this as the underlying problem is probably an emacs/fuse bug.
