### ISSUE TITLE
Negative "all archives" size?  32-bit integer overflow?

### ISSUE THREAD

**Issue by sourcejedi** [borgbackup/borg#165]
![screenshot from 2015-08-28 16-20-47](https://cloud.githubusercontent.com/assets/14057/9550136/7cd23b90-4da1-11e5-96c5-efa1286a0256.png)

borg 0.24.0-57-g034e347

This is after two archives of 1gb and then 2gb (all zeros).  Then I ran the 2gb with --stat and this weirdess showed up.  Negative 1gb "all archives".

Between the 1gb and 2gb run, `borg info` shows the expected positive number.  After the 2gb run, it shows the silly negative number.

Change 2gb to 3gb and "all archives" falls to 24.27kB.

Change it to 700mb.  First run ok.  Add a second 700mb archive, and "all archives" falls to -1.75GB.

Integer overflow?! (32-bit signed) It happens on x86_64, although the original screenshot is from a 32-bit test VM.

<pre>
truncate -s 1G 1gb
truncate -s 2G 2gb
borg init borg
borg create -v --stat borg::1gb 1gb
borg create -v --stat borg::2gb 2gb

**Comment by sourcejedi** [comment]
> This fixes a infrequent problem when (refcount * chunksize) overflowed a int32_t. chunksize is always <= 8MiB and usually rather ~64KiB (with default chunker params). Thus, this happened only for high refcounts and/or unusually big chunks.

Nice.  So...

1. To overflow refcount in the chunk index, you need 2GiB * ~64KiB (of zeros or other consistent pattern, again assuming defaults).

2. Chunksize doesn't overflow.

3. Segment index limits the repo on-disk size to 2G * 5M = 10PB, fine.

4. In-memory indexes almost certainly limit you before then.  De-dupe is known to be memory-intensive, we have some discussion of this & mention in the docs.

I think the first point is a concern. There's not a big margin there, and we need to make sure we have an overflow check. You can include a 500G sparse VM image (mostly zero) in the backup.  If it never changes then "incremental" backups are plenty fast, but you overflow after 256 daily backups.

**Comment by ThomasWaldmann** [comment]
about 1.: good find.

I first thought this is no real problem, but your example of historical deduplication of files with lots of duplicate chunks shows some potential.

But in the specific and very common case of all-zero chunks, we are lucky that the chunks seem to be 8MB size, so a int32 overflow would mean 2G * 8MB = 16TB of zeros over all archives. In your example with the 500GB mostly-zero VM it would mean 32000 backups of it.

So, it is maybe not that bad. I'ld appreciate if you open a separate issue about this. Maybe if we break compatibility anyway at some time later, we could use int64 to get rid of this issue.
