### ISSUE TITLE
borg check output to file

### ISSUE THREAD

**Issue by IwishIcanFLighT** [borgbackup/borg#1651]
Hi there!

I have a backup routine shell script file that creates a daily backup of my server, prune the repo and check it afterward.
I want to be able to read the results of these jobs afterward. What I currently do is `./backupscript.sh &> logfile.txt` which work great with `borg create` and `borg list`.

Output of `borg create -v --stats --show-rc` in the log file:
```
------------------------------------------------------------------------------
Archive name: 2016-09-27-17-26-28
Archive fingerprint: c84c86a***
Time (start): Tue, 2016-09-27 17:26:29
Time (end):   Tue, 2016-09-27 17:26:42
Duration: 12.95 seconds
Number of files: 46281
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               23.99 GB             23.99 GB              1.86 MB
All archives:               95.96 GB             95.97 GB              7.66 GB

                       Unique chunks         Total chunks
Chunk index:                   31509               219617
------------------------------------------------------------------------------
terminating with success status, rc 0
```
Output of `borg prune -v --show-rc ` in the log file:
```
Keeping archive: 2016-09-27-17-26-28    Tue, 2016-09-27 17:26:29
Keeping archive: 2016-09-27-16-59-04    Tue, 2016-09-27 16:59:05
Keeping archive: 2016-09-27             Tue, 2016-09-27 15:07:37
Pruning archive: 2016-09-27-17-21-42    Tue, 2016-09-27 17:21:43
terminating with success status, rc 0

```

However, `borg check -v --show-rc` only outputs to the terminal, leaving the log file empty.

The ideal output to the log file would be something like this:

```
Starting repository check
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive 2016-09-27-17-26-28 (3/3)
Analyzing archive 2016-09-27-16-59-04 (2/3)
Analyzing archive 2016-09-27 (1/3)
Archive consistency check complete, no problems found.
terminating with success status, rc 0
```

I can't find anything in the doc that can help me with that... Am I missing something?
Thanks

**Comment by ThomasWaldmann** [comment]
If you redirect stdout as well as stderr, it should work.

**Comment by ThomasWaldmann** [comment]
So, does it work now?

**Comment by IwishIcanFLighT** [comment]
Sorry I was away for a while after submitting the issue. But I'm back!

It kinda worked. I was able to capture the check using `borg check --show-rc -v >> output.log 2>&1`
However, the output.log file was containing all the progress status on line 3:

```
Starting repository check
Starting archive consistency check...
Progress 0.1%,Progress 0.2%,Progress 0.3%,Progress 0.3%,Progress 0.4%,Progress 0.5%,Progress 0.6%,[...]
Analyzing archive 2016-09-29-17-18-26 (4/4)
Analyzing archive 2016-09-29-16-15-22 (3/4)
Analyzing archive 2016-09-28-18-31-40 (2/4)
Analyzing archive 2016-09-27-17-41-00 (1/4)
Archive consistency check complete, no problems found.
terminating with success status, rc 0
```
I was able to obtain what I want with sed, but this is not ideal.

I suggest an option to hide the progression of the check from the terminal, or even better an option to output the check result directly into a logfile (same goes for `borg create` and `borg prune`).

Anyway, my issue is resolved but I let it opened for the suggestions I made above.
Thanks ! 😄

**Comment by ThomasWaldmann** [comment]
the borg check output is improved in borg master branch (borg 1.1 later).
if you have rather special logging requirements, you can maybe do it using a logging.conf.
