### ISSUE TITLE
borg locking issues using systemd --user service

### ISSUE THREAD

**Issue by fkjogu** [borgbackup/borg#1656]
I'd like to run a backup script like this
```
#!/bin/bash

REPOSITORY=/path/to/repo

# Backup all of /home and /var/www except a few
# excluded directories
./borg create -v --debug --stats --compression lzma,9 \
    $REPOSITORY::`hostname`-`date +%Y-%m-%d` \
    ~/some \
    ~/folders \
```

through a `systemd --user` service. When executing it manually, it works just fine. But as soon as I start this service file

```
[Unit]
Description=Run borg backup on home directory

[Service]
Type=oneshot
ExecStart=/absolute/path/to/borg-backup-home.sh

[Install]
WantedBy=default.target
```
it fails with the only error message in journald

```
Can't aquire Failed to create/acquire the lock <path>/lock.exclusive (timeout).
```

Any idea, what can cause this?

Running borg 1.0.7 (pip) on a Debian Jessie with a nfs home (might be relevant?).

**Comment by infectormp** [comment]
[Service] include a line "User=<username to run as>"?

**Comment by fkjogu** [comment]
Since I run it with the user session instance of systemd, the user should already be set to mine. As a consequence, the user can't even be changed, since my account does not have the appropriate permissions.

**Comment by infectormp** [comment]
@fkjogu may be you can try set user?

**Comment by ThomasWaldmann** [comment]
Not sure it is related, but under some circumstances, systemd sends SIGHUP to process and until recently borg didn't process that well (did not clean up locks before exiting). It is fixed in repo code and will be in next release.

**Comment by enkore** [comment]
I think the [systemd-SIGHUP disaster](https://www.google.de/search?q=systemd-SIGHUP) only happened on log-out of the user. But maybe that's it. Or permissions?

**Comment by fkjogu** [comment]
I've tried to do a test backup on master, which seems to be working. As soon as the new stable version is available, I'll try my real backup.

**Comment by fkjogu** [comment]
On the other hand, I've tried also a fresh backup with this method on 1.0.7 which also works. Something is wrong with my existing backup.

**Comment by fkjogu** [comment]
After renamic the `.cache/borg/<id>` directory, it now also works with my existing backup.

diff of the old cache folder and the new created one
```
diff <id> <id>-old/
Only in <id>-old/: carl.27150-0.old
Binary files <id>/chunks and <id>-old/chunks differ
Common subdirectories: <id>/chunks.archive.d and <id>-old/chunks.archive.d
diff <id>/config <id>-old/config
4,5c4,5
< manifest = somehex
< timestamp = 2016-09-28T07:35:48.821680
---
> manifest = someotherhex
> timestamp = 2016-08-25T22:03:13.652254
Binary files <id>/files and <id>-old/files differ
Only in <id>-old/: lock.exclusive
Only in <id>-old/: txn.active
```

**Comment by enkore** [comment]
Looks like there was a stale lock in there actually and no permissions issue. (There are already tickets about better locking and it's being worked on for 1.1.0b3, therefore closing).
