### ISSUE TITLE
adapt borg check like in PR 1554

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1663]
See #1554.

Also look if other commands can be done / extended using the same mechanisms.

**Comment by ThomasWaldmann** [comment]
See also #1542.

**Comment by funkyfuture** [comment]
there's still this implementation: d61c778869b9f336cb301682b0e01cf5f9f61786

**Comment by ThomasWaldmann** [comment]
@funkyfuture ok, do you want to take this and make a new PR based on that and current master?
