### ISSUE TITLE
use appveyor.com for windows based testing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#167]
We maybe could use this service to automate testing on Windows.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/26292300-use-appveyor-com-for-windows-based-testing)

**Comment by ThomasWaldmann** [comment]
I would appreciate if a Windows based developer implements this, tests it with appveyor.com and does a PR.

**Comment by ThomasWaldmann** [comment]
https://bitbucket.org/ned/coveragepy/src < some appveyor configs/scripts (but for win32 python, not cygwin).

**Comment by fliiiix** [comment]
Maybe something like this: https://github.com/ogrisel/python-appveyor-demo ?

**Comment by ThomasWaldmann** [comment]
@fliiiix good example, but it is not based on cygwin. borg does not run under native windows, only under cygwin.

**Comment by RonnyPfannschmidt** [comment]
you can also use appveyor to upload windows wheels after the tests

**Comment by PlasmaPower** [comment]
Cygwin is installed to `C:\cygwin` and `C:\cygwin64` on appveyor by default: https://www.appveyor.com/docs/installed-software#mingw-msys-cygwin

**Comment by Anakonda** [comment]
See #1240

**Comment by ThomasWaldmann** [comment]
@Anakonda can you make it do some tests?

Doesn't need to be all of them, but so we can close this issue.

**Comment by Anakonda** [comment]
I actuall have that already. I'm trying to fix some more tests.
```======= 50 failed, 427 passed, 258 skipped, 3 xfailed in 443.28 seconds =======```

**Comment by Anakonda** [comment]
#1307 merged, Close this now?

**Comment by ThomasWaldmann** [comment]
@Anakonda don't forget to claim the bounty.
