### ISSUE TITLE
Prune: Chunk ID missing from chunks index, corrupted chunks index - aborting transaction.

### ISSUE THREAD

**Issue by imba3r** [borgbackup/borg#1675]
I am using borg create backups from my Arch Linux desktop to my NAS running Ubuntu 16.04. Both have borg 1.0.7 installed.

`borg create --compression none -v --stats --progress "borg@node:/tank/backups/borg/bastion::$(hostname)-$(date +%Y-%m-%d)" /home /etc (... excludes)`

After the backup I prune using the following command which now gives me an error:

```
$ borg prune -v borg@node:/tank/backups/borg/bastion  --prefix `hostname`- --keep-daily=7 --keep-weekly=4 --keep-monthly=6
Chunk ID 0d5f6acbf1ad96a7a619e080bb1752c815df10b8bec98b3594cb8598c4fc192b missing from chunks index, corrupted chunks index - aborting transaction.
```

I ran borg check to see if there are problems, this is the output.

```
$ borg check -v borg@node:/tank/backups/borg/bastion
Remote: Starting repository check
Remote: Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive bastion-2016-10-02 (15/15)
Analyzing archive bastion-2016-10-01 (14/15)
Analyzing archive bastion-2016-09-30 (13/15)
Analyzing archive bastion-2016-09-29 (12/15)
Analyzing archive bastion-2016-09-28 (11/15)
Analyzing archive bastion-2016-09-27 (10/15)
Analyzing archive bastion-2016-09-26 (9/15)
Analyzing archive bastion-2016-09-25 (8/15)
Analyzing archive bastion-2016-09-14 (7/15)
Analyzing archive bastion-2016-09-11 (6/15)
Analyzing archive bastion-2016-09-04 (5/15)
Analyzing archive bastion-2016-08-31 (4/15)
Analyzing archive bastion-2016-08-28 (3/15)
Analyzing archive bastion-2016-07-31 (2/15)
Analyzing archive bastion-2016-06-29 (1/15)
Archive consistency check complete, no problems found.
```

I had this error once before with version 1.0.7. Last time I deleted both my local and the remote borg cache dir. There has to be another way to recover from this?

**Comment by ThomasWaldmann** [comment]
Can it be that some content in that repo was made with borg < 1.0.4 and what you see now is corruption introduced back then?

**Comment by imba3r** [comment]
Since my oldest archive dates before the 1.04 release that may be possible. However I just tried to dry-extract both my latest and my oldest (the one done prior to 1.04) - both succeeded. Shouldn't either borg check or dry-extract detect the problem that prevents me from pruning?

**Comment by enkore** [comment]
If neither detects issues it means that there is no problem with the repository, only an issue in the local cache. (The local cache is currently not verified by check). This can be caused by a bug in Borg (naturally) or data corruption in the cache files.

Does the issue persist if you delete `~/.cache/borg/<repository ID>/chunks`? (The repository ID is obtainable through the `config` file of your repository - I know, a bit awkward, #1679)

**Comment by imba3r** [comment]
Deleting the cache on the client worked once again..

I have an samsung ssd 850 evo with ext4 on it. Both cache and home are on it. Smartctl shows no issues afaict: 

```
=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED


...


ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE

  5 Reallocated_Sector_Ct   PO--CK   100   100   010    -    0
  9 Power_On_Hours          -O--CK   099   099   000    -    1720
 12 Power_Cycle_Count       -O--CK   098   098   000    -    1589
177 Wear_Leveling_Count     PO--C-   098   098   000    -    25
179 Used_Rsvd_Blk_Cnt_Tot   PO--C-   100   100   010    -    0
181 Program_Fail_Cnt_Total  -O--CK   100   100   010    -    0
182 Erase_Fail_Count_Total  -O--CK   100   100   010    -    0
183 Runtime_Bad_Block       PO--C-   100   099   010    -    0
187 Uncorrectable_Error_Cnt -O--CK   100   100   000    -    0
190 Airflow_Temperature_Cel -O--CK   075   055   000    -    25
195 ECC_Error_Rate          -O-RC-   200   200   000    -    0
199 CRC_Error_Count         -OSRCK   100   100   000    -    0
235 POR_Recovery_Count      -O--C-   099   099   000    -    13
241 Total_LBAs_Written      -O--CK   099   099   000    -    14412280577
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning
```

I couldn't paste the whole report for some reason, the browser always froze..

**Comment by ThomasWaldmann** [comment]
@imba3r if it happens again, update the ticket, so we can try to find the root cause (having to delete the cache is no solution).

**Comment by enkore** [comment]
There are no known bugs in the cache logic (at this time). With these good-looking SMART values there is also no obvious hardware issue. So pretty much the only thing we can say here for now is to watch & observe if/when this happens again and try to gather as much data about the circumstance as possible (sequence of commands, hard reset / power failure during or after backup, stuff like that).

If #1101 is implemented it should allow in the future to easily distinguish between a borg-side problem and a hardware/corrupted data problem.

**Comment by fsironman** [comment]
I have exactly the same Problem with one of my repositories, which might be related to #1644.

`Okt 03 06:41:42 myserver bash[27204]: Archive name: filme-2016-10-03-05_40
Okt 03 06:41:42 myserver bash[27204]: Archive fingerprint: d80a45b834dc39f2c50521e26b7393252ce4b7b1c33c338b374151028c2fa433
Okt 03 06:41:42 myserver bash[27204]: Time (start): Mon, 2016-10-03 05:41:04
Okt 03 06:41:42 myserver bash[27204]: Time (end):   Mon, 2016-10-03 06:41:41
Okt 03 06:41:42 myserver bash[27204]: Duration: 1 hours 37.69 seconds
Okt 03 06:41:42 myserver bash[27204]: Number of files: 3278
Okt 03 06:41:42 myserver bash[27204]: ------------------------------------------------------------------------------
Okt 03 06:41:42 myserver bash[27204]:                        Original size      Compressed size    Deduplicated size
Okt 03 06:41:42 myserver bash[27204]: This archive:                3.68 TB              3.68 TB             41.19 GB
Okt 03 06:41:42 myserver bash[27204]: All archives:                2.53 EB             13.39 EB              9.28 TB
Okt 03 06:41:42 myserver bash[27204]:                        Unique chunks         Total chunks
Okt 03 06:41:42 myserver bash[27204]: Chunk index:                 1579669        5084042873478
Okt 03 06:41:42 myserver bash[27204]: ------------------------------------------------------------------------------
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-10-03-05_40               Mon, 2016-10-03 05:41:04
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-09-26-22_54               Mon, 2016-09-26 22:54:29
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-08-29-07_12               Mon, 2016-08-29 07:12:22
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-08-22-05_53               Mon, 2016-08-22 05:53:15
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-08-15-03_58               Mon, 2016-08-15 03:58:06
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-08-12-14_26               Fri, 2016-08-12 14:26:41
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-07-15-20_52               Fri, 2016-07-15 20:52:36
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-06-17-12_03               Fri, 2016-06-17 12:03:31
Okt 03 06:41:47 myserver bash[27204]: Keeping archive: filme-2016-05-20-17_18               Fri, 2016-05-20 17:18:41
Okt 03 06:41:47 myserver bash[27204]: Pruning archive: filme-2016-04-20                     Wed, 2016-04-20 11:25:09
Okt 03 06:42:02 myserver bash[27204]: Chunk ID 23dedda4adfdb9e762d41b93d5b7190fcac91e4b920df7b031d765f1f4a0a4a1 missing from chunks index, corrupted chunks index - aborting transaction.`




I did not delete the cache so i could provide it if needed.

**Comment by enkore** [comment]
Can you run this snippet on your repo and post the results?

```py

import heapq
import sys
from binascii import hexlify

from borg.archiver import Archiver, with_repository
from borg.helpers import location_validator


class XArchiver(Archiver):
    @with_repository(cache=True)
    def show_odd_cache_entries(_, args, repository, cache, manifest, key):
        contents = heapq.nlargest(20, cache.chunks.iteritems(), key=lambda k_r_s_c: k_r_s_c[1])
        fmt = '%-64s %-16s %-16s %-16s'
        print(fmt % ('Object ID', 'refcount', 'size', 'csize'))
        for key, (refcount, size, csize) in contents:
            print(fmt % (hexlify(key).decode(), refcount, size, csize))


class Args:
    location = location_validator(archive=False)(sys.argv[1])



if __name__ == '__main__':
    XArchiver().show_odd_cache_entries(Args)
```

It may take some time + memory.

**Comment by fsironman** [comment]
```

17:38:22 % python3 borg_test.py ironbackup:/media/d7e382f2-5492-465c-b8c8-f2f158b04486/Filme/borg 
Traceback (most recent call last):
  File "borg_test.py", line 25, in <module>
    XArchiver().show_odd_cache_entries(Args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 72, in wrapper
    lock_wait=self.lock_wait, lock=lock, append_only=append_only, args=args)
  File "/usr/local/lib/python3.5/dist-packages/borg/remote.py", line 162, in __init__
    borg_cmd = self.borg_cmd(args, testing)
  File "/usr/local/lib/python3.5/dist-packages/borg/remote.py", line 238, in borg_cmd
    opts.append('--umask=%03o' % args.umask)
AttributeError: type object 'Args' has no attribute 'umask'
17:38:48 % mkdir borg_filme
17:40:00 % sshfs backup:/media/d7e382f2-5492-465c-b8c8-f2f158b04486/Filme/borg borg_filme 
17:40:08 % python3 borg_test.py borg_filme 
Warning: The repository at location /home/dominik/borg_filme was previously located at ssh://backup/media/d7e382f2-5492-465c-b8c8-f2f158b04486/Filme/borg
Do you want to continue? [yN] y
Object ID                                                        refcount         size             csize           
229af9352652f2605ed03417e68a57ff4f7b0845d667fc688e5adef1f5c0e94a 4291735924       684016723        1850177050      
c1324475accb7cec1418b8206742bd98dc0bc8ea68dfe43572affe563c2e2b75 4291533551       3092209648       3933046736      
d7467da68db0a917e44f27a194f6b916a3d9652d16ce70073ed1e116fdea2177 4290853050       2375379773       2261698280      
48dd3e0e96e18696cc4764a5e6f176b7368fbd63cf7d7327d449c577c474fdc1 4289621540       3337277000       3231372542      
1a2f220073019184a3cba361efdca61ddaa4455aaf15d97dc26309608255711d 4287949718       2997228407       503391340       
67d436b3ff249c37bce80c56cbd65f80605ea9597e63d4c372e98b5cca8a7518 4285614870       292892452        157785308       
e99e1190e4723653cf30ec8f0d8f669324fd9b5940ba4565f20636dce3b96f95 4284389670       3590345154       2754223421      
71ecb49797707a354942a4f9eda8ebcc108ea42dd8612993d5513e2242d02b49 4281788511       1290306523       4248262091      
92ed532ac0ec2ede87ff908bdb464f05009da631e8ab22561fa932af3ca8c9ae 4279782803       402134993        1137419015      
4fad4faf12c64027805f8990b3b92be794e4b5f4997b8f828debe2ea1c12bff2 4278991827       2441889091       2324259658      
9a5a1698a99fe1c827f90a81fbe2c1d4777ec1c801467462afd4cebf3a22dcce 4278521034       3894680514       1746064323      
07d8c196fdc3ed50bc4f4eb8454e7561a8399938d8cb54a807619896f27ce9da 4277053899       250860032        3010495625      
a4d399142d1f04da3fd4500bd1b7f11a1093c8c733f7cded193fe2688beae470 4274825767       1047355452       2252492144      
b72100cf71b2856bcb69b18997f5333d5bc6c59c4df1894ef291310c88830305 4274367543       1015181585       3937616656      
46a94dc4bf7b02f7e7c428aa0b4edac66f008d7427bbc2f88ca16b2d8511abf9 4273718987       1991189387       3510459133      
736197471d851e989b39b751eaf05af0e449f91d8c11c9343c9cc89c4616090d 4268830041       3817492334       2688830884      
87ef8a890f0526e13e3f6c5fd4f3c1ae7e43b250a1e096327fae0cf3a597122c 4265440446       556795058        858675496       
37ded9c662da503b82df32c9420bd18e40fab1d4fbdb3c36c4583f5d7e919b6e 4265201856       1074037671       739057793       
ca687a252111c1f396049cbd58e5e08ead28f50e125d16b0fa044e176227ae7a 4258173716       2309406764       2085888578      
5f22e0e78dde4efe8b1fbfde69d6ee261023649eacc7e96887dd0063b3e435ae 4257625688       1915672842       595108792 
```

and 

```
sudo smartctl -a /dev/sdi
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.4.0-36-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Crucial/Micron RealSSD m4/C400
Device Model:     M4-CT256M4SSD2
Serial Number:    0000000012370915DE2F
LU WWN Device Id: 5 00a075 10915de2f
Firmware Version: 000F
User Capacity:    256.060.514.304 bytes [256 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 6
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Tue Oct  4 17:43:43 2016 CEST

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x002f   100   100   050    Pre-fail  Always       -       0
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
  9 Power_On_Hours          0x0032   100   100   001    Old_age   Always       -       16942
 12 Power_Cycle_Count       0x0032   100   100   001    Old_age   Always       -       1481
170 Grown_Failing_Block_Ct  0x0033   100   100   010    Pre-fail  Always       -       0
171 Program_Fail_Count      0x0032   100   100   001    Old_age   Always       -       0
172 Erase_Fail_Count        0x0032   100   100   001    Old_age   Always       -       0
173 Wear_Leveling_Count     0x0033   099   099   010    Pre-fail  Always       -       49
174 Unexpect_Power_Loss_Ct  0x0032   100   100   001    Old_age   Always       -       231
181 Non4k_Aligned_Access    0x0022   100   100   001    Old_age   Always       -       562 246 316
183 SATA_Iface_Downshift    0x0032   100   100   001    Old_age   Always       -       0
184 End-to-End_Error        0x0033   100   100   050    Pre-fail  Always       -       0
187 Reported_Uncorrect      0x0032   100   100   001    Old_age   Always       -       0
188 Command_Timeout         0x0032   100   100   001    Old_age   Always       -       0
189 Factory_Bad_Block_Ct    0x000e   100   100   001    Old_age   Always       -       84
194 Temperature_Celsius     0x0022   100   100   000    Old_age   Always       -       0
195 Hardware_ECC_Recovered  0x003a   100   100   001    Old_age   Always       -       750
196 Reallocated_Event_Count 0x0032   100   100   001    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   100   100   001    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   100   100   001    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   100   100   001    Old_age   Always       -       0
202 Perc_Rated_Life_Used    0x0018   099   099   001    Old_age   Offline      -       1
206 Write_Error_Rate        0x000e   100   100   001    Old_age   Always       -       0
```

**Comment by enkore** [comment]
Yeah, that cache is definitely corrupted for good.

From the list of object IDs, can you try to retrieve some of them by doing `borg debug-get-obj <repository> <object ID> <some file that will be created>` (the latter doesn't matter, we won't need it) and see whether that works or fails ("...fetched" vs "... not found")?

**Comment by fsironman** [comment]
```
17:55:24  % borg debug-get-obj borg_filme 229af9352652f2605ed03417e68a57ff4f7b0845d667fc688e5adef1f5c0e94a 123
object 229af9352652f2605ed03417e68a57ff4f7b0845d667fc688e5adef1f5c0e94a not found.
17:56:02  % borg debug-get-obj borg_filme c1324475accb7cec1418b8206742bd98dc0bc8ea68dfe43572affe563c2e2b75 123
object c1324475accb7cec1418b8206742bd98dc0bc8ea68dfe43572affe563c2e2b75 not found.
17:56:35  % borg debug-get-obj borg_filme d7467da68db0a917e44f27a194f6b916a3d9652d16ce70073ed1e116fdea2177 123
object d7467da68db0a917e44f27a194f6b916a3d9652d16ce70073ed1e116fdea2177 not found.
17:57:18  % borg debug-get-obj borg_filme 48dd3e0e96e18696cc4764a5e6f176b7368fbd63cf7d7327d449c577c474fdc1 123
object 48dd3e0e96e18696cc4764a5e6f176b7368fbd63cf7d7327d449c577c474fdc1 not found.
17:57:49  % borg debug-get-obj borg_filme 1a2f220073019184a3cba361efdca61ddaa4455aaf15d97dc26309608255711d 123
object 1a2f220073019184a3cba361efdca61ddaa4455aaf15d97dc26309608255711d not found.
17:58:06  % borg debug-get-obj borg_filme 67d436b3ff249c37bce80c56cbd65f80605ea9597e63d4c372e98b5cca8a7518 123
object 67d436b3ff249c37bce80c56cbd65f80605ea9597e63d4c372e98b5cca8a7518 not found.
17:58:21  % borg debug-get-obj borg_filme e99e1190e4723653cf30ec8f0d8f669324fd9b5940ba4565f20636dce3b96f95 123
object e99e1190e4723653cf30ec8f0d8f669324fd9b5940ba4565f20636dce3b96f95 not found.
17:58:34  % borg debug-get-obj borg_filme 71ecb49797707a354942a4f9eda8ebcc108ea42dd8612993d5513e2242d02b49 123
object 71ecb49797707a354942a4f9eda8ebcc108ea42dd8612993d5513e2242d02b49 not found.
17:58:46  % borg debug-get-obj borg_filme 92ed532ac0ec2ede87ff908bdb464f05009da631e8ab22561fa932af3ca8c9ae 123
object 92ed532ac0ec2ede87ff908bdb464f05009da631e8ab22561fa932af3ca8c9ae not found.
17:59:05  % borg debug-get-obj borg_filme 4fad4faf12c64027805f8990b3b92be794e4b5f4997b8f828debe2ea1c12bff2 123
object 4fad4faf12c64027805f8990b3b92be794e4b5f4997b8f828debe2ea1c12bff2 not found.
17:59:18  % export BORG_CACHE_DIR="/mnt/cache1/.borg_cache"
18:00:02  % borg debug-get-obj borg_filme 4fad4faf12c64027805f8990b3b92be794e4b5f4997b8f828debe2ea1c12bff2 123
object 4fad4faf12c64027805f8990b3b92be794e4b5f4997b8f828debe2ea1c12bff2 not found.
18:00:12  % borg debug-get-obj borg_filme 07d8c196fdc3ed50bc4f4eb8454e7561a8399938d8cb54a807619896f27ce9da 123
object 07d8c196fdc3ed50bc4f4eb8454e7561a8399938d8cb54a807619896f27ce9da not found.
18:00:32  % borg debug-get-obj borg_filme a4d399142d1f04da3fd4500bd1b7f11a1093c8c733f7cded193fe2688beae470 123
object a4d399142d1f04da3fd4500bd1b7f11a1093c8c733f7cded193fe2688beae470 not found.
18:00:46  % borg debug-get-obj borg_filme b72100cf71b2856bcb69b18997f5333d5bc6c59c4df1894ef291310c88830305 123
object b72100cf71b2856bcb69b18997f5333d5bc6c59c4df1894ef291310c88830305 not found.
18:01:04  % borg debug-get-obj borg_filme 46a94dc4bf7b02f7e7c428aa0b4edac66f008d7427bbc2f88ca16b2d8511abf9 123
object 46a94dc4bf7b02f7e7c428aa0b4edac66f008d7427bbc2f88ca16b2d8511abf9 not found.
18:01:23  % borg debug-get-obj borg_filme 736197471d851e989b39b751eaf05af0e449f91d8c11c9343c9cc89c4616090d 123
object 736197471d851e989b39b751eaf05af0e449f91d8c11c9343c9cc89c4616090d not found.
18:01:35  % borg debug-get-obj borg_filme 87ef8a890f0526e13e3f6c5fd4f3c1ae7e43b250a1e096327fae0cf3a597122c 123
object 87ef8a890f0526e13e3f6c5fd4f3c1ae7e43b250a1e096327fae0cf3a597122c not found.
18:01:50  % borg debug-get-obj borg_filme 37ded9c662da503b82df32c9420bd18e40fab1d4fbdb3c36c4583f5d7e919b6e 123
object 37ded9c662da503b82df32c9420bd18e40fab1d4fbdb3c36c4583f5d7e919b6e not found.
18:02:02  % borg debug-get-obj borg_filme ca687a252111c1f396049cbd58e5e08ead28f50e125d16b0fa044e176227ae7a 123
object ca687a252111c1f396049cbd58e5e08ead28f50e125d16b0fa044e176227ae7a not found.
18:02:13  % borg debug-get-obj borg_filme 5f22e0e78dde4efe8b1fbfde69d6ee261023649eacc7e96887dd0063b3e435ae 123
object 5f22e0e78dde4efe8b1fbfde69d6ee261023649eacc7e96887dd0063b3e435ae not found.
```

I'm using a custom cache dir: 17:59:18  % export BORG_CACHE_DIR="/mnt/cache1/.borg_cache"
Not sure if this has anything to do with all the not found.

**Comment by enkore** [comment]
No, this command is independent from any cache, it directly talks to the repository.

With this bit I'm fairly confident that parts of your cache has been overwritten/replaced with ~random data. I ran the integer columns [1] (refcount, size, csize) through a little Python script (below [2]) and the ratio of ones to zeroes is almost exactly 1 (0.98873) [3].

I think this could be indicative of the SSD with the cache on it failing or having erroneous writes (due to power failure / sudden power loss directly after a backup).


[1] the object ID column is not suitable for this kind of test, because it's always (pseudo-)random.

[2]
```py
import sys

count0, count1 = 0, 0

for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    value = int(line)
    b = bin(value)
    count0 += b.count('0')
    count1 += b.count('1')

print('0s: %10d' % count0)
print('1s: %10d' % count1)
print('ratio: %.5f' % (count0 / count1))
```

[3]
```
0s:        965
1s:        976
ratio: 0.98873
```

**Comment by fsironman** [comment]
Sadly I cant rule out any drive error.

Nevertheless how do I recover from this?
Preferably without losing the file cache as rechunking takes about 20h.

Delete the chunks + chunks.archive.d and just keep files in the cache?

**Comment by enkore** [comment]
Try this:

1. Copy `files` to a different dir
2. borg delete --cache-only repo
3. Create tiny archive (creates cache)
4. Copy `files` back into cache dir

**Comment by ThomasWaldmann** [comment]
If the chunks cache was corrupted, maybe it is not a good idea to keep the files cache either.

**Comment by fsironman** [comment]
Copying the `files` back in after recreating the cache dir with an empty backup worked.

> If the chunks cache was corrupted, maybe it is not a good idea to keep the files cache either.

As it did rechunk everything beforehand I belive borg did no use the corrupted cache file at all and just created a new one. And even if it not really important data.

**Comment by enkore** [comment]
The data pulled from the files cache is checked for plausibility against the chunks cache, meaning that all chunks listed for a file have to be in the chunks cache as well. Otherwise it will rechunk the file (the assumption is that some of these chunks where deleted, not that either one of these are corrupted - but it may work reasonably well against corruption).

**Comment by ThomasWaldmann** [comment]
Any new information here?

Tending to close this as an issue not caused by borg (but by hardware or other external influence).

**Comment by imba3r** [comment]
I have not encountered the issue since I reported it here. I replaced my sata cable just to be sure -- maybe that's what caused the problems, hard to tell.

**Comment by ThomasWaldmann** [comment]
ok, thanks for feedback.

**Comment by feldsam** [comment]
Hello, deleting cache works for me.

**Comment by W1zzardTPU** [comment]
Got this today on our backup server

Chunk ID 6168965f75dec00691f7e417f35b2e83e371a0a658c848eb14eca9c206831b11 missing from chunks index, corrupted chunks index - aborting transaction.

Command 'borg prune --prefix 2 --keep-hourly 4 --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-yearly 1 borg@server:/backup/borg/repo/mysql' returned non-zero exit status 2.

# borg check -v .
Starting repository check
Starting repository index check
Index object count match.
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive 2021-01-17T19:41:57 (1/16)
Analyzing archive 2021-01-24T19:42:37 (2/16)
Analyzing archive 2021-01-31T22:01:52 (3/16)
Analyzing archive 2021-02-07T21:48:17 (4/16)
Analyzing archive 2021-02-11T22:05:55 (5/16)
2021-02-11T22:05:55: mysql/gpuz/results_text_compressed2.sql.gz: New missing file chunk detected (Byte 1083166524-1086353891). Replacing with all-zero chunk             .
Analyzing archive 2021-02-12T22:03:05 (6/16)
2021-02-12T22:03:05: mysql/gpuz/results_text_compressed2.sql.gz: New missing file chunk detected (Byte 1083166635-1086354002). Replacing with all-zero chunk             .
Analyzing archive 2021-02-13T22:07:58 (7/16)
2021-02-13T22:07:58: mysql/gpuz/results_text_compressed2.sql.gz: New missing file chunk detected (Byte 1083166591-1086353958). Replacing with all-zero chunk             .
Analyzing archive 2021-02-14T22:01:35 (8/16)
Analyzing archive 2021-02-15T22:01:53 (9/16)
Analyzing archive 2021-02-16T22:15:51 (10/16)
Analyzing archive 2021-02-17T22:36:51 (11/16)
Analyzing archive 2021-02-18T22:33:29 (12/16)
Analyzing archive 2021-02-19T04:33:15 (13/16)
Analyzing archive 2021-02-19T10:30:48 (14/16)
Analyzing archive 2021-02-19T16:31:46 (15/16)
Analyzing archive 2021-02-19T22:56:01 (16/16)
Archive consistency check complete, problems found.

# borg -V
borg 1.1.14

Running on Linux RAID-1, but the drives have around 60,000 hours each, so could be a hardware issue. No other problems with the server though.

Haven't repaired the repo or touched the cache yet, let me know if you need more testing

**Comment by ThomasWaldmann** [comment]
@W1zzardTPU looks like some corruption. maybe run memtest86+ / smartctl -t long to make sure your RAM/disk is ok.

to repair, use `borg check --repair -v ...`.

if that is an old repo used with borg < 1.1.11, also see the advisory close to the top of the changelog.

**Comment by W1zzardTPU** [comment]
Isn't it surprising that a chunk in the same file is corrupted 3 times, on 3 different days?

**Comment by ThomasWaldmann** [comment]
No, that's rather expected due to deduplication, if the chunk happens to be identical.

**Comment by W1zzardTPU** [comment]
Oh so it refers to the same chunk in all those 3 error messages? Maybe this could be a future enhancement to the error message, to display the chunk id?

Memory and drives seem fine, tests completed fine just now.

If you don't need any testing I'll repair the repo, please confirm

**Comment by ThomasWaldmann** [comment]
@W1zzardTPU feel free to repair the repo, guess we can't find anything more from there. I opened #5704 for the logging issue.

Maybe keep the log from repairing and check if it finds some orphaned chunk. If it tells an id, compare it to the missing chunk id.

**Comment by W1zzardTPU** [comment]
Same server, same repo (out of a dozen or so), just 1 month later

Chunk ID 0b0e70ba79bda02c39f71c5fe91550cd670aecbec1c5130220fb4b3c61786ae9 missing from chunks index, corrupted chunks index - aborting transaction.
