### ISSUE TITLE
append_only and prune interaction

### ISSUE THREAD

**Issue by rakajack** [borgbackup/borg#1689]
Is it safe to automatically run prune (from the safe client) on append_only repository?

Is there a protection from the following situation:

1) Hacked client A with append_only access iterates over chunk id's from the cache and put() garbage to them.
2) Client B with full access runs a prune command.

**Comment by enkore** [comment]
No, there is no protection for that. If hacked client A just deleted important archives and client B would prune after that, with full access and not in append-only mode, then the data will be gone.

Therefore if this process is automated, then there should be some checks done that the expected archives are still in place. I guess we should say so in the docs if we don't do already.

**Comment by ThomasWaldmann** [comment]
Fixed by #1744.
