### ISSUE TITLE
borgversionN placeholder

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1694]
borgversion currently expands to e.g. `1.1.0b3.dev6+ng1030660.d20161007`.
that's correct, but for client / server multiple versions support, it is a bit much.

so, add some more placeholders, that expand like:

borgversion1 1
borgversion2 1.1
borgversion3 1.1.0

With this, I guess people would usually use borgversion2 on the client to select the borg version on the server via --remote-path borg-{borgversion2}. On the server, borg-1.1 would just symlink to the latest 1.1.x release.

**Comment by enkore** [comment]
Shouldn't it already be e.g. 1.0.7 with a tagged version?

{borgminor} = 1.1 would make sense; we follow semver (I think?) so we can call it by name.

**Comment by ThomasWaldmann** [comment]
Yes, borgversion is 1.0.7 if you use 1.0.7 release.

But that's not as useful as 1.0, because one usually does not want to request a specific bugfix version, but just some compatible version.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt Hmm, I suspect setuptools_scm assembles the version string from components, so it would be nice if it also offered a version tuple, so we do not need to do the split.

**Comment by RonnyPfannschmidt** [comment]
setuptools_scm does not work with components at all

**Comment by ThomasWaldmann** [comment]
fixed by #1752.
