### ISSUE TITLE
openbsd64 box - check fuse again

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1696]
From Vagrantfile:
```
    # pkg_add fuse  # does not install, sdl dependency missing
```

This is likely the "free unix spectrum emulator" that wanted SDL, not the `devel/fuse` package.

So, check again with correct fuse and fix the comment at least.

**Comment by bket** [comment]
OpenBSD has in kernel support for FUSE 2.6. There is no FUSE package.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/a0df60e1b86d8e4b7efdb721090c5245524e01aa fixed.
