### ISSUE TITLE
low-level borg transfer command

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1697]
This ticket is about a low-level command, let's call it `transfer` for now:
- just transfer all repo objects (except the manifest) "as is" to a different, already existing repo
- use new Repository.scan() method to read data in efficient linear on-disk order
- append source manifest items to existing (if any) manifest items in target repo
- initially: do not change encryption (currently: **must use same enc. key and hmac key**), compression, chunking - keep it simple.

Applications:
- clone a repo (source into empty destination)
- merge repos (source into non-empty destination)
- move a repo to a different physical location (including locations with no shell access)

Note: In master/1.1 we already have `recreate`, but it currently is limited to work within same repository and also it is working high-level (iterate over archives, iterate over items, re-chunk, decrypt/decompress/compress/encrypt).

**Comment by enkore** [comment]
Hm, requirements 1), 3) and 4) together basically mean to operate repositories in an unsafe way unless a lot of care is taken that only one repo is ever updated and all the other repos are only "transferred into", ie. master-slave repos. This should be noted rather clearly. Perhaps even a safety switch built-in (ie. "slave" flag in the manifest).

**Comment by ThomasWaldmann** [comment]
Well, the use cases I have in mind are single-use, not continuously mixing repos in a specific manner.

**Comment by RonnyPfannschmidt** [comment]
why not just enable recreate to target different repos?

personally i never needed to move a whole repo, but always had a need to move archives between repos

for example
* push recent backups from usb hd to offsite repo

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt not sure how they would compare performance-wise, esp. if you just want to transfer repo from location A to B (into empty repo, so it can transfer "as is"). If you always have shell access, you can ofc just use rsync for that, but if you use a backup service, you might not have that.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann i still see a much higher need for archive transfer than i see for whole repo transfer

in particular since whole repo transfer doesnt capture stuff happening over time well as far as i understood

**Comment by fti7** [comment]
+1 for transfer/copy of archives. That would make nice scenarios possible :-)

**Comment by enkore** [comment]
Duplicate of #895?

**Comment by ThomasWaldmann** [comment]
ok, let's close this due to security issues.
