### ISSUE TITLE
1.1 release schedule, get into debian stretch

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1707]
See: https://wiki.debian.org/DebianStretch

So, until when do we need to release 1.1.0rc1?

**Comment by anarcat** [comment]
i am not sure i understand your question, but if you are asking details about the Debian freeze timeline, they are detailed in the URL you shared. In short:

* Q3 2016: Please finish up things for Stretch
* 2016-11-05: Transition freeze (general freeze of transitions)
* 2017-01-05: "Soft" freeze (no new packages, no re-entry, normal migrations)
* 2017-02-05: Full freeze

Right now, Debian stretch and backports have [1.0.7-1](https://tracker.debian.org/pkg/borgbackup). To get this updated to a 1.1 release, a 1.1 package should be upoaded to Debian unstable before the "full freeze", that is february 2017.

That is, of course, if everything goes well: borg could be removed from testing if there are unfixed critical bugs. In this case, it needs to "re-enter" testing, and that cannot be done after the "soft" freeze in january 2017. Also note the "no new packages" restriction during the soft freeze: this could affect borg if 1.1 ships an additionnal binary package (e.g. a theoritical borgbackup-doc or borgbackup-web). For both reasons, I would recommend considering that as the hard deadline instead.

In general, as stated in the first step, Q3 2016 is when everyone should be pushing to put the latest and greatest in Debian. That is already passed, so we're already late to ship new software into the next Debian stable. I know that even I have scrambled only now to push my latest updates in, even though I am a Debian Developer and I should know better.

Another thing to consider is that the package version shipped in Stretch will be around for a loooong time. [Debian releases](https://wiki.debian.org/DebianReleases#Production_Releases) see about 3 years of full support, and an extra 2 years with LTS. Debian jessie will therefore be supported normally until 2018 and with LTS until 2020. To quote the release team: *As always, Debian 9 "Stretch" will be released "when it's ready"*. Some stats about a typical Debian release, it:

* endures a freeze cycle of 7 +/- 1 months before getting released.
* is released about 2 years after the previous one (the often cited example of Debian Sarge being quite an exceptional event in Debian history).
* leaves users about 1 year to upgrade to the next one once this latter itself gets released.
* has (from release to the end of security updates) a total lifetime of about 3 years.

So starting with a full freeze in february 2017, we could see a release in september 2017, which would mean support until september 2020 and LTS until 2022, a whooping 6 years from now.

So I would recommend shipping in Debian a release you're ready to be bugged about for a while. Obviously, it's not borg maintainer's direct responsibility to manage Debian packages, but it does mean users may be using an older version than what you want, unless you maintain a critical security issues branch separate from normal development.

@LocutusOfBorg is, I believe, the package maintainer in Debian and may have other thoughts to add.

**Comment by ThomasWaldmann** [comment]
I was asking because it was not clear what transitions and re-entry means (the latter is clear now).

Also "no new packages" can be interpreted differently (I understand it now as "no new package names", but a new version 1.1 of a package 1.0 would be acceptable).

If full-freeze is in february, what is the time until september used for? If nothing would change, it would be useless, wouldn't it?

**Comment by LocutusOfBorg** [comment]
changes after the freeze have to be acked by the release team, and only minimal changes are acked (depending on the month you ask the unblock, at the begin they accept almost everything, at the end only puntual fixes for RC bugs).
So, if you really want 1.1 in Stretch, we can upload an RC version and ask for a freeze exception if the release is stable enough and changes are not too many (assuming you can give us a final release before the end of the next month)

I didn't look too carefully, but in this case there is a chance that:
borg is out of Stretch (in case the new RC is buggy), borg is in Stretch with an RC version

**Comment by anarcat** [comment]
> Also "no new packages" can be interpreted differently (I understand it now as "no new package names", but a new version 1.1 of a package 1.0 would be acceptable).

That is correct. Also consider auto-removal...

> If full-freeze is in february, what is the time until september used for?

Fixing all the bugs. You can see how it works here:

https://bugs.debian.org/release-critical/graph.png

The green line is Debian testing. When it reaches 0, there's a release.

> If nothing would change, it would be useless, wouldn't it?

Right, things still change: uploads are allowed on a case-by-case basis to fix release-critical bugs only.

> I would try if we can get 1.1 into stretch (if we can get it stable soon enough).
> If we just put 1.0.8 or .9 in there, we will have to live with that for many years - and that would be a pity if we already have something better.

That would be great, but unfortunately, I'm not familiar enough with the state of the issue queue or the current software to comment on that.

> So, if you really want 1.1 in Stretch, we can upload an RC version and ask for a freeze exception if the release is stable enough and changes are not too many (assuming you can give us a final release before the end of the next month)

That's true. However, those exceptions are not very common, and it's better to not plan ahead to operate that way: everyone wants that piece of *that* cake... If there's an RC of borg in testing, the update should be featuring only release-critical bugs to get back into testing if it is released after the freeze.

> I didn't look too carefully, but in this case there is a chance that:
borg is out of Stretch (in case the new RC is buggy), borg is in Stretch with an RC version

Yes: autoremovals will kick in if 1.1-rc1 has a release-critical bug, and after a certain point (2017-01-05), it becomes impossible for the package to re-enter testing. Then if 1.1 (not RC) is released after the full freeze (2017-02-05), then it may be difficult to be accepted through the freeze, as I suspect it will feature more than just critical fixes.

I hope that makes everything clear! I'd be happy to answer further questions you may have.

**Comment by ThomasWaldmann** [comment]
Due to release timing issues, we'll stay with 1.0.x for stretch.

**Comment by enkore** [comment]
Or, more precisely, the distro release management [process] will do it
