### ISSUE TITLE
many files in ~/.config/borg/key-nonces dir

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1714]
I just deleted 14.500 files from there. I suspect they were generated from borg unit tests...

**Comment by enkore** [comment]
Confirmed. Looks very much like unit tests. Should bend BORG_NONCES_DIR in tests to the appropriate tempdir where the repo lives, too.

**Comment by textshell** [comment]
testsuite.key has a fixture to stop leaving files around. But that one was not copied to the noncemanager  test.

```
@pytest.fixture(autouse=True)
def nonce_dir(tmpdir_factory, monkeypatch):
    monkeypatch.setenv('XDG_CONFIG_HOME', tmpdir_factory.mktemp('xdg-config-home'))
```

But maybe we want to do this more global.
