### ISSUE TITLE
please upgrade to 1.1+

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1715]
```
Please upgrade to borg version 1.1+ on the server for safer AES-CTR nonce handling.
```

That's what 1.0.x-maint tip says about a 1.0.7 server.

Guess we forgot to change the message when backporting this to 1.0.x?

**Comment by enkore** [comment]
I don't think we backported this (yet).

**Comment by ThomasWaldmann** [comment]
crap, I accidentally ran 1.1 on this repo. :- |
