### ISSUE TITLE
Can't mount on ubuntu. Missing dependencies ?

### ISSUE THREAD

**Issue by jsalatiel** [borgbackup/borg#1726]
Trying to mount a backup archive on ubuntu 16.04 fails with:
`# borg mount ~/.backup/ /tmp/pqp/`
`Loading fuse support failed [ImportError: No module named 'llfuse']`

I have installed borgbackup from ubuntu repositories. Is there any missing dependencies on ubuntu packages ?

> 
> `# dpkg -l | grep -i fuse`
> ii  exfat-fuse                                  1.2.3-1                                    amd64        read and write exFAT driver for FUSE
> ii  fuse                                        2.9.4-1ubuntu3.1                           amd64        Filesystem in Userspace
> ii  gvfs-fuse                                   1.28.2-1ubuntu1~16.04.1                    amd64        userspace virtual filesystem - fuse server
> ii  ifuse                                       1.1.2-0.1build3                            amd64        FUSE module for iPhone and iPod Touch devices
> ii  libfuse2:amd64                              2.9.4-1ubuntu3.1                           amd64        Filesystem in Userspace (library)
> ii  ntfs-3g                                     1:2015.3.14AR.1-1build1                    amd64        read/write NTFS driver for FUSE

**Comment by ThomasWaldmann** [comment]
borg mount needs llfuse.

http://packages.ubuntu.com/xenial-updates/borgbackup

it recommends python3-llfuse, but does not require it.

apt-get install python3-llfuse

**Comment by jsalatiel** [comment]
Thanks ! It worked ! Before closing this, shouldn't this package be a dependency in ubuntu repositories ? I dont know who mantains the package, but it should be warned.

**Comment by jsalatiel** [comment]
IMHO, if one of borg features depends on this package, it should be a dependency, not a suggestion =)

**Comment by ThomasWaldmann** [comment]
Well, you can use borg without using borg mount, so it is somehow optional.
As long as llfuse is available, one of course wants to have it. But llfuse is a bit of a fragile thing concerning platform support.

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg ^^^

**Comment by LocutusOfBorg** [comment]
eh, I'm stick to what upstream suggests
```
# msgpack pure python data corruption was fixed in 0.4.6.
# Also, we might use some rather recent API features.
install_requires = ['msgpack-python>=0.4.6', ]

extras_require = {
    # llfuse 0.40 (tested, proven, ok), needs FUSE version >= 2.8.0
    # llfuse 0.41 (tested shortly, looks ok), needs FUSE version >= 2.8.0
    # llfuse 0.41.1 (tested shortly, looks ok), needs FUSE version >= 2.8.0
    # llfuse 0.42 (tested shortly, looks ok), needs FUSE version >= 2.8.0
    # llfuse 1.0 (tested shortly, looks ok), needs FUSE version >= 2.8.0
    # llfuse 2.0 will break API
    'fuse': ['llfuse<2.0', ],
}
```
If you want me to make it a real dependency just ask, if you think suggest is too weak

**Comment by ThomasWaldmann** [comment]
Well, the python-based setup has it optional, because building llfuse quite frequently has issues (e.g. on the BSDs). But if a distribution always has a well-built functioning llfuse package of suitable version, there is maybe nothing against making it a requirement, so people don't run into missing it.

**Comment by ThomasWaldmann** [comment]
Tagging this "documentation", so we can add a note for package maintainers with the result of this discussion.

**Comment by LocutusOfBorg** [comment]
Fixed in git https://anonscm.debian.org/cgit/collab-maint/borgbackup.git/commit/?id=b231fdc8ecf623852f2667bc2805609fd8172407

**Comment by ThomasWaldmann** [comment]
Thanks! Good that there is a way to exclude platforms for a requirement. ;)

**Comment by ThomasWaldmann** [comment]
OK, so I'll add a line in setup.py and requirements.d/fuse.txt that package maintainers shall add llfuse as requirement for borg on all platforms where llfuse is available and working.

**Comment by enkore** [comment]
Fixed by #1743

**Comment by jcrben** [comment]
for those who stumble across this on Google, if you install from pip you need:
`pip install borgbackup[fuse]`

(as noted in the install docs; sadly, available extras are not exposed in the pip UI yet https://github.com/pypa/pip/issues/4824)

**Comment by sevillaarvin** [comment]
> borg mount needs llfuse.
> 
> http://packages.ubuntu.com/xenial-updates/borgbackup
> 
> it recommends python3-llfuse, but does not require it.
> 
> apt-get install python3-llfuse

Confirming this works. I'm on:
* manjaro@20.2.1
* linux-kernel@5.9.16-1-MANJARO
* borg@1.1.14

The command I used is `sudo pacman -S python-llfuse`
