### ISSUE TITLE
Improve cache sync speed

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1729]
See #235 and #536 

Some findings in https://github.com/borgbackup/borg/issues/235#issuecomment-254010549

So I've started to analyze some of my logs and there are indeed a few observable oddities. For example, some merges will take much longer than others, even when the archive index that is merged is small.

One particularly extreme sample is that merging one archive took almost one minute, while archives with more than ten times as many chunks merged in less than two seconds. When forced to reproduce, it did not happen with the same archive. This might be #536 

We've already found that there's quite a performance regression in master branch here (see third link above), but that one is fixed easily. Some minor difference persists between 1.0.x and master, though; root cause unknown so far.

Further, the process feels quite slow given the data that is processed. I am suspecting that by using msgpack-python we give up a lot of performance, because it creates Python objects for everything in the items stream, most of which doesn't matter here. Quite possible that we could speed it up significantly by using a zero-copy-oriented approach and coding it in C or using msgpack-c in this spot and directly interfacing with the C API of the hash index. (This will likely add either msgpack-c as a dependency -- which shouldn't be an issue with us already requiring msgpack-python anyway -- or a _significant_ chunk of C).

**Comment by ThomasWaldmann** [comment]
guess it rather depends on how many *new* keys are in a index than the amount of all keys in that index. insert is more expensive than update and sometimes might also trigger table growth.

**Comment by enkore** [comment]
Fixed by #2572

**Comment by ThomasWaldmann** [comment]
"will be fixed by #2572" (it is not merged yet)
