### ISSUE TITLE
Wishlist: Tar file export / import

### ISSUE THREAD

**Issue by erikswanson** [borgbackup/borg#176]
It would be neat to be able to directly export an archive from borg to a tarball without needing to extract the tree of files to disk. The main use case for this would be offline and fully self-contained backups for security / archival purposes.

The UX for this would be mostly the same as `borg extract` except that instead of writing files to disk (or plainly to stdout), the stdlib `tarfile` module would be used to write to an archive file (or stdout).

The converse, a `borg import` that works like `borg create` but consumes a tar file (or stream) instead of reading files from disk might be simple enough to add as well, although I don't have a compelling use case for this.

**Comment by ThomasWaldmann** [comment]
See also: https://github.com/borgbackup/borg/issues/175#issuecomment-136703259

That stream of items that goes over the pipe mentioned in the last sentence there is a quite similar idea (except that we need tar here and maybe json+binary there).

**Comment by erikswanson** [comment]
Would the format for that case avoid undoing deduplication? (For instance, to support moving multiple archives at the same time.) If so, that'd be a good reason to support two streaming formats.

Otherwise, if you're going to expand deduplication for that case, may as well look into just using tar.

**Comment by sergiocallegari** [comment]
This seems interesting, particularly to transform backup archives made by other software into more efficient borg backup archives, as long as they can provide "tar" output (sometimes they can).

**Comment by ThomasWaldmann** [comment]
@erikswanson if archives are transferred in order, it could maybe work in a similar way as if reading from the file system, avoiding chunking and transferring stuff that's already is in the target archive.

**Comment by deadly11ama** [comment]
I have a use-case for this.  My Borg archives are a long way away, RTT wise (300ms), on a VPS that doesn't support FUSE.  Borg extract over the network is quite slow.  To restore at a decent speed I need to extract locally on the VPS with the archives, and I need to do this as root to retain user IDs/etc.

It would be greatly preferable to do something like
  ssh -C backup-vps borg extract --tar repository::archive | sudo tar xvf -
to restore, instead.

**Comment by enkore** [comment]
That's more of a problem with the netcode in Borg though. Borg does prefetching over the network, but it's a rather, uh, crude implementation. For example, instead of having an adaptive window, it just has a fixed buffer of at most 100 in-flight prefetches. This is probably what causes the poor bandwidth in your case; your bandwidth-delay combination is not a good match for that fixed parameter.

**Comment by enkore** [comment]
Note: tarfile ingestion is now #2233

**Comment by enkore** [comment]
https://borgbackup.readthedocs.io/en/latest/usage.html#borg-export-tar
