### ISSUE TITLE
BorgJS

### ISSUE THREAD

**Issue by vesparny** [borgbackup/borg#1761]
Hi,
I do not know if this is the right place, but I wanted to let you know that I've created a wrapper script for borg that takes care of creating, checking and pruning archives.
It has been released as a nodejs package.
It enables the user to receive push notifications (via pushbullet), emails and OS native notifications about the state of the backups.

Here is the module.
https://github.com/vesparny/borgjs

Hope someone will find it useful.

Thanks for the great project.

**Comment by ThomasWaldmann** [comment]
hi @vesparny! you could do a PR against borgbackup/community to add a link to your project.

**Comment by vesparny** [comment]
Sure.

PR landed. Closing
