### ISSUE TITLE
limit cache space needs to avoid out of space exceptions

### ISSUE THREAD

**Issue by martin21** [borgbackup/borg#1765]
Today a borgbackup ran into exception due to insufficient free space.

I´d like borgbackup to limit cache size so that there is enough free space on filesystem. Ideally with an option to determine the limit in percent and/or size. This is not about reducing cache size needs, but about making sure that it will not abort the backup in out of space conditions – even if by continuing without cache.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1684, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1621, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 82, in wrapper
    do_files=getattr(args, 'cache_files', False), lock_wait=self.lock_wait) as cache_:
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 86, in **init**
    self.sync()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 355, in sync
    self.begin_txn()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 187, in begin_txn
    shutil.copy(os.path.join(self.path, 'files'), txn_dir)
  File "/usr/lib/python3.5/shutil.py", line 235, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 116, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python3.5/shutil.py", line 76, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device

**Comment by ThomasWaldmann** [comment]
Well, this is problematic:

While borg can work without files cache, it would not be able to quickly determine whether a file is unchanged and whether all chunks of it are still in the repo. so, without files cache, it has to read and chunk and hash all your files and also talk to (remote?) repo to check whether it has these chunks - consuming a lot of time and traffic.

The main reason why we introduced the option to work without files cache was low memory (RAM) machines. While memory can't be upgraded in some machines, it usually should not be a problem to supply enough .cache space on disk (or adjust the files cache TTL).

**Comment by ThomasWaldmann** [comment]
Not directly related, but living in same space:

https://borgbackup.readthedocs.io/en/stable/faq.html#the-borg-cache-eats-way-too-much-disk-space-what-can-i-do

**Comment by ThomasWaldmann** [comment]
I am closing this one. We already have other tickets about reducing cache space needs (e.g. #235).

"Limiting" (to less what we need) is not possible (with the current algorithm).
