### ISSUE TITLE
Possibility of BORG_NEW_PASSPHRASE environment variable

### ISSUE THREAD

**Issue by rjkowalewski** [borgbackup/borg#1768]
I was hoping to be able to script the changing of the password on all of my repos every so often but I notice that there is currently only BORG_PASSPHRASE for the current passphrase and BORG_DISPLAY_PASSPHRASE to suppress the question of showing your new passphrase. Would it be possible to add a variable to hold the new passphrase, for example BORG_NEW_PASSPHRASE in order to be able to script the change-password function more easily.

**Comment by ThomasWaldmann** [comment]
sounds like a reasonable feature to add.

until we have, one can work around like this (untested):
```
borg change-passphrase repo <<<EOF
newpass
newpass
N
EOF
```
