### ISSUE TITLE
Repository deletion is grossly inefficient

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1776]
We use shutil.rmtree for the data directories. rmtree is built on the wrong listdir() API[1] instead of scandir(). Therefore deleting a repository takes far longer than need be, especially on hard drives.

While technically a defect in Python we can also easily fix it for us.

Upstream issue: http://bugs.python.org/issue28564 (Python 3.7)

[1] https://hg.python.org/cpython/file/3.5/Lib/shutil.py#l393

**Comment by ThomasWaldmann** [comment]
Well, low prio, normal user does not delete repos that often.

Even developers do not delete BIG repos (when it makes a real perf difference) that often.

**Comment by ThomasWaldmann** [comment]
From Python 3.7 "what's new":

"The shutil.rmtree() function has been sped up to 20–40%. This was done using the os.scandir() function."

So, time will solve this. Not now, but in the not-too-far future.

As I already pointed out above, this is not a big issue, repos are not deleted that often.

Considering both, I am closing this as "time will solve this".
