### ISSUE TITLE
New user feedback

### ISSUE THREAD

**Issue by gleb** [borgbackup/borg#1778]
* where I learned about it - [HN/Reddit](https://www.reddit.com/r/linux/comments/42feqz/i_asked_here_for_the_optimal_backup_solution_and/)
* really great documentation
* great UX
* in general onboarding is very good
* need docs on compression
  * that deduplication is done before compression
  * presumably that compression is done on each chunk
  * what happens when you rerun the same archive (without deleting)
    with different compression - will it recreate everything, or
    reuse chunks compressed with different compression algorithm
  * how much of a benefit to be gained by going with lzma,1 vs lz4 -
    given that we are compressing small chunks, past deduplication
  * --stats is misleading w.r.t. compression vs deduplication
* --stats and --list needing -v is weird and not documented in the
  right place
* that --exclude default patterns don't work like tar is confusing
  (most of them need to prefixed with '*/' to get the same result)
* document rsync.net offer and integration
* want throughput printed in --stats and in --progress, like apt
* want --directory (-C option)
* want bash command completion
* want an official ppa
* want profiling data as part of --stats-profile.  Something like
  compressing @ 10MB/s, transfering @ 1MB/s, this much time spent on
  random IO.  End goal is to be able to eyeball how much improvement
  could be gained by running compression faster (faster core, or on
  multiple cores), how much by getting a higher throughput uplink,
  how much in lower latency uplink, how much in lower latency backup
  storage

**Comment by ThomasWaldmann** [comment]
want: separate tickets for different things. :)

a ticket that contains 10 completely different things can not be reasonably worked on.

there is a ppa for debian/ubuntu. not sure what you mean by "official" (borg developers do not maintain dist packages).

**Comment by gleb** [comment]
Sorry, this was the wrong place to post this.   I took down some notes while onboarding and figured they might be of some use.   I'll pick out the few things that are proper issues from there and file them separately.

**Comment by ThomasWaldmann** [comment]
a lot of these are issues (bugs, todo, docs, ...), just needs to be broken down into smaller work units and clean topics.

**Comment by enkore** [comment]
Thanks for your feedback; the new-user perspective is always hard to assume (for me at least) when having worked on something for some time :)
