### ISSUE TITLE
--exclude patterns are not compatible with tar

### ISSUE THREAD

**Issue by gleb** [borgbackup/borg#1779]
In tar `--exclude .bundler/gems` will exclude `foo/.bundler/gems`
In borg it will not, and you need to use `--exclude '*/.bundler/gems'` to get the same effect.

I figured this out while porting a tarsnap script to borg.   Since otherwise the `--exclude` interface seems to be similar to tar's, this is confusing.

Maybe document this difference and how to change patterns from tar to borg ? Other than that the docs for patterns are very good. It's just that this difference is not obvious.

**Comment by ThomasWaldmann** [comment]
We can't just change the patterns, that would break everybody's scripts.

But we already have different pattern prefixes (see borg help patterns) to implement different semantics, please check them. Another prefix could be used to implement different semantics.

**Comment by gleb** [comment]
Agreed.   What I am suggesting is documenting the difference and the workaround.

**Comment by enkore** [comment]
Fixed by #1863
