### ISSUE TITLE
Bash command completion

### ISSUE THREAD

**Issue by gleb** [borgbackup/borg#1782]
Would be nice to have bash programmable completion

**Comment by enkore** [comment]
There is zsh completion: https://github.com/borgbackup/community

Not sure if that's easily converted to bash.

**Comment by RonnyPfannschmidt** [comment]
with arg-parse one can use arg-completer to provide auto completion to bash (pytest does that)

**Comment by ThomasWaldmann** [comment]
https://argcomplete.readthedocs.io/en/latest/

**Comment by RonnyPfannschmidt** [comment]
i believe it can be part of that borg package,

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt you mean inside the binary? don't think that can work. the code is not active, not even unpacked when you type in your command line on the shell. in general argcomplete looks like an external thing, not something that we need to require or bundle.

but, if it works ok, we could add it to the docs.

**Comment by enkore** [comment]
Maybe it can generate a completion file? Then we could generate that as part of the source distribution creation (just like cythonizing). Package maintainers can then just put it where it belongs on their system.

**Comment by Forceu** [comment]
I wrote a quick script for bash-completion, just create the file /etc/bash_completion.d/borg

It is not ideal however, at the moment it doesn't support anything apart from the regular arguments

```
_borg()
	{
	local cur prev opts
	COMPREPLY=()
	#get current word, not used at the moment
	cur="${COMP_WORDS[COMP_CWORD]}"
	#get previous word, not used at the moment
	prev="${COMP_WORDS[COMP_CWORD-1]}"

	opts="init create check change-passphrase migrate-to-repokey extract rename delete list mount info break-lock prune upgrade debug-info debug-dump-archive-items debug-dump-repo-objs debug-get-obj debug-put-obj debug-delete-obj"
	if [[ $COMP_CWORD == 1 ]] ; then
		COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
	else
		COMPREPLY=()
	fi
	return 0
}
```

**Comment by rugk** [comment]
Fixed by https://github.com/borgbackup/borg/pull/3268, is not it?
