### ISSUE TITLE
Signing backups with gpg

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#1786]
It would be nice if one could sign backups with GPG - as an additional layer of security.
Duplicity e.g. supports this.

**Comment by enkore** [comment]
You can just pull the archive ID and sign that.

**Comment by rugk** [comment]
But that's a manual step to do. It would be nice if it is integrated in Borg.

**Comment by ThomasWaldmann** [comment]
Having to add gpg as a dependency for everybody if it can be easily done externally (and only by those wanting it) seems wrong.

borg list will show all archive ids (not sure if in 1.0 or 1.1), so this could get signed.

**Comment by enkore** [comment]
Closing as duplicate in favour of #672
