### ISSUE TITLE
borg benchmark command

### ISSUE THREAD

**Issue by gleb** [borgbackup/borg#1788]
It would be nice to have a command to benchmark different subsystems.   Something like

```
borg benchmark repo /mnt/external_drive/backup
     100MB/s up   200MB/s down
borg benchmark repo offsetitebackup.com:foo
     1MB/s up   10MB/s down
borg benchmark compression lzma,1
      2MB/s compression  8MB/s decompression
borg benchmark chunker
   ... etc
```

My current use case is picking compression settings for on-site and off-site backups, as a new user.  Today answering a question "how much compression can I run and still be IO bound" is fairly involved, takes time and knowledge to setup and run tests.   With builtin benchmarking support it could be done by a simple script in a few minutes.

Another usecase would be trouble-shooting performance issues by users/sysadmins (it is network, hard drive, code regression?).  Also, it would be useful for development, to trend performance over time.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/38830536-borg-benchmark-command)

(not necessarily like described above, see also comments)

**Comment by dragetd** [comment]
The question without compression is if borg is hitting a file-processing boundary or the network-speed boundary. The goal is, that on a reasonable PC and 'normal' network, borg should not be the limiting factor. If that is the case, your question can be answered by benchmarking network throughput and IO-performance. :-)

Of course, compression is the interesting thing. But that speed depends almost only on the data that is being compressed. I did some benchmarks on different data corpus here: https://github.com/dragetd/borgbench

Under compression I tested different settings on an debian root filesystem which should have a mixed bag of compressible data. E.g. (https://github.com/dragetd/borgbench/blob/master/compression/img/results_rootfs_zlib.png) or https://github.com/dragetd/borgbench/blob/master/compression/img/results_rootfs_lzma.png

So in the end, the speed should be something over 90% of max(average io performance for traversing and reading all files / network speed / compression speed based on the actual data)

**Comment by anarcat** [comment]
see also #1618 and #1364

**Comment by ThomasWaldmann** [comment]
add some benchmark, so we can see perf independently of user data:
- write some known content / size files to src folder, like:

  - big, all zero
  - big, all random
  - lots of small files, all zero
  - lots of small files, all random
- create backups of these into dst repo
- don't use compression (we know that lz4 is fast and lzma is slow)
- test with / without encryption depending on how dst repo was initialized
