### ISSUE TITLE
Borg performance on Raspberry Pi 3

### ISSUE THREAD

**Issue by feluxe** [borgbackup/borg#1793]
I have a laptop and a Raspberry Pi3 connected over wlan. The Pi itself is connected via ethernet to a wireless access point. The Pi mounts the home dir of the laptop via NFS. If I execute `rsync -av` on the Pi to copy from the mounted home dir of the laptop to a USB disk which is connected to the Pi, I get about **12MB/s**. (both hard-drives, the one of the laptop and the one on the Pi are encrypted with LUKS).

In comparison, if I run borg instead of rsync on the Pi with the exact same setup like this:

    $ borg init --encryption=none /path/to/repo
    $ borg create -v --stats -p /path/to/repo::Monday /nfs-import/peter-laptop/peter/home/*

I get a processing speed of about **1-5MB/s**.

I love the way borg works and I really would like to use it with the Pi, but the performance I currently get may not be good enough to keep track of my home dir. Is there anything I could do to tweak the performance or have I hit the limit of what is possible?

#### Some more detail:

This is how the home dir of the laptop is currently mounted to the Pi (NFS):

    /etc/exports
		/home    192.168.178.10(ro,sync,crossmnt,no_subtree_check,root_squash)
		/home/peter    192.168.178.10(ro,sync,no_subtree_check,root_squash)

    /etc/auto.peter-laptop
		home    -fstype=nfs4,ro,retry=3,rsize=131072,wsize=131072,tcp 192.168.178.20:/home/peter

I also notices, that the speed drops the most when directories with a large amount of small files are being processed. It was struggling with some `node_modules` dirs a lot. These are directories in which nodejs dependency modules are stored. Sometimes they contain huge amounts of tiny script files, like 150K files totaling 300MB.

**Comment by enkore** [comment]
You probably want to push into the repository on the Pi, which should give better performance (more CPU on the laptop, and the files cache works (cf. --ignore-inode)).

Like so:

```
borg create -svp backup@raspi:/path/to/repo::Monday ~peter
```

**Comment by ThomasWaldmann** [comment]
What @enkore said.

Additionally, using the borg client on the laptop also gives it more RAM, enabling it to process much bigger backups / bigger repositories.

The borg server part on the raspi uses less RAM than the client (and also uses much less CPU).

**Comment by feluxe** [comment]
Thanks for your response!

> You probably want to push into the repository on the Pi, which should give better performance

> Additionally, using the borg client on the laptop also gives it more RAM, enabling it to process much bigger backups / bigger repositories.
>
> The borg server part on the raspi uses less RAM than the client (and also uses much less CPU).

Of cause all this makes a lot of sense, but my idea is to build up the Pi as a dedecated and independent backup module to exclude backup related things from the clients as much as possible. The Pi would become a backup unit running its cycle in the background each hour, year in year out, becoming more and more solid and tuned over time. Clients would hook onto that cycle by no more effort than being available. One thing less on the client machine to distract its user.

I don't really want to give up on that idea already. I have the feeling if I tweak out just a little more performance the thing would run just fine...

I'm still not sure about the actual performance and I need to continue testing. For example I just noticed that if I exclude the `node_modules` dirs from the backup I get a quite acceptable performance of about **10MB/s** on a fresh initial run, which is similar to what I get from rsync. IMHO this kind of speed would totally be enough. Yet, I also don't know how fast borg would be after all `node_modules` directories were synced. It looks like duplication among these dirs is *gigantic* (which makes sense because those nodejs packages very often have same or similar dependencies.)

> cf. --ignore-inode

I'll give it a try.

> If Borg is installed on the remote host, big performance gains can be achieved compared to using a network filesystem (sshfs, nfs, ...).

If I understand this right then I should install borg on both machines no matter if I push or pull a backup and I should use ssh instead of NFS or sshfs to gain batter performance? Right now borg is NOT installed on the laptop.. If I have borg installed on both ends in order to increase performance, how would I notice both borgs successfully hooked?

>We added some performance improvements for directories with many files in the 1.1 series. I'm not sure whether that has any advantage with a networked file system, though...

I'm exited to see the release of v1.1! :-)

**Comment by ThomasWaldmann** [comment]
Close? Or is there anything else?

**Comment by feluxe** [comment]
I think it can be closed. I could not get borg running on the Pi3 at reasoable speed. Demand on RAM/CPU is just too high... I'll give it another try when 1.1 is out.

**Comment by ThomasWaldmann** [comment]
Well, in general SBCs, esp. when designed like the rpi, are not high-performance machines. Almost all has to go via usb 2.0 multiple times: lan-usb-cpu-usb-disk + vice versa.

In case of the rpi3, the 4 cores don't currently help, as borg is single-threaded still.

Also, a lot of currently used Intel/AMD CPUs have AES hardware acceleration, but ARM CPUs like in the rpi3 don't have this. borg has on-by-default crypto.

So, using such a device as a borg server can work ok (basically just key/value storage + ssh, no crypto, no chunking, no hashing), but as a borg client it is a bit much (chunking, hashing, crypto + ssh).
