### ISSUE TITLE
Docker container added

### ISSUE THREAD

**Issue by maltefiala** [borgbackup/borg#1794]
After looking at existing borg containers, I decided it's time for a sleek simple one: https://hub.docker.com/r/produktion/borg/

Of course, a shoutout to [Olivier Mauras](https://pkgs.alpinelinux.org/package/edge/community/x86_64/borgbackup) who packaged borgbackup.

**Comment by ThomasWaldmann** [comment]
Maybe do a PR against the community repo (to add a link there) rather than an issue?

**Comment by maltefiala** [comment]
Done
