### ISSUE TITLE
Possible options on the market for offsite backup

### ISSUE THREAD

**Issue by vesparny** [borgbackup/borg#1795]
Hi everyone,
curious to know what the community uses for offsite backup.

I personally use [rsync.net](http://rsync.net/)
Technically it's possible to do a local backup and use any backend supported by [rclone](http://rclone.org/), but the fear of compromising data during the transfer put me off.

**Comment by enkore** [comment]
### Regular borg server

Any BSD/Linux/possibly Windows box where you have shell access would work.

### rsync.net

native borg support (`--remote-path borg1`). Borg plan: http://www.rsync.net/products/attic.html

### Amazon Cloud Drive

https://github.com/borgbackup/borg/issues/102#issuecomment-256990559

> With my PR on acdcli, you can use borg on amazon cloud drive right now. I've been using it for a month or so without issue.

### borg + git-annex

https://juliank.wordpress.com/2016/05/11/backing-up-with-borg-and-git-annex/
http://zyradyl.github.io/2016/10/02/Collegi-Backup-System/

**Comment by ThomasWaldmann** [comment]
@enkore shell access is not needed, just restricted ssh access - if the other system is already configured appropriately. See the borgbackup org repo about writing a spec.

**Comment by ThomasWaldmann** [comment]
closing this in favour of #2177.
