### ISSUE TITLE
Minimal mandatory feature support for manifest

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#1806]
Quite some features require changes in the repository that are not safe when using old client versions. We should have minimal support in place to mark a repository on first use of such an feature as incompatible with older versions. As features can also be "unused" this should be with feature granularity. Also different operations have different requirements. For the start i propose to have mandatory feature lists for "write", "delete" and "check". (E.g. a feature where archives are stored outside of the manifest would be mandatory for delete (and check, but this could be implied)

For this minimal version we should define how these are saved in the manifest in a way that all borg versions will preserve when rewriting the manifest.

Additionally borg should check that all relevant lists are empty before performing an operation.

We need to decide on a format of the features. I propose using short strings.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/38975114-minimal-mandatory-feature-support-for-manifest)

**Comment by ThomasWaldmann** [comment]
Do we really need that?

We could just increment Manifest version to avoid older clients working with the repository.

The RPC mechanism already has some versioning.

**Comment by textshell** [comment]
Yes, i think we need this ;).
Manifest version is a very blunt tool that needs either a lot of planing and predicting the future or doesn’t allow for a graceful upgrading period when combined with optional features.

This is much more fine grained. For example adding a new mandatory feature for check still allows older clients to use the repository. But we are free to add features that would be unsafe when running check on a version that doesn‘t understand new feature. Or maybe it is save for an old version to read the repository but it is not safe to do any changes (i.e. because new parts need to be refcounted).

This also allows to capture certain upgrade steps. I.e. a new archive feature A might start out as optional but we someday want to be able to remove support for archives that lack that feature. The code that adds this feature knows a "a-only" feature for write and if it sees that it unconditionally enables that feature.
So later we add an upgrade step where all archives not yet using this new feature are rewritten and adds the "a-only" mandatory feature to the manifest for write. Now version that don‘t support the feature refuse to create archives. Intermediate version just keep working and new version can drop the old support code.

I think this mechanism will allow smooth upgrading in more scenarios, but i‘m not very creative at the moment. Also this is the standard used in many systems. While we don‘t want to keep compatibility like certain file systems do, we can just more aggressively promote features to mandatory to keep compat code small, but still allow users graceful upgrade pathes with mixed versions.

**Comment by ThomasWaldmann** [comment]
fixed by #2648.

@textshell claim the bounty.
