### ISSUE TITLE
hashindex size limitations

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1809]
The size of it is limited to 2**31 entries, probably not important right now (since that would need at least ~180 GB of usable memory). [hash_sizes](https://github.com/borgbackup/borg/blob/master/src/borg/_hashindex.c#L49)

We use normal C I/O currently, which will be limited to 32 bit offsets depending on platform (I think Linux 32 bits and Windows?). This would limit the repository index to ~60 million entries and the chunks cache to ~49 million entries. This is already addressed by the patches in #1688, since Python I/O always uses large offsets if available as far as I'm aware.

**Comment by ThomasWaldmann** [comment]
Split this into 2 or 3 tickets?

**Comment by textshell** [comment]
I’m pretty sure both windows and linux allow for C i/o with full 64 bit offsets. On linux the default is controlled by a #define _FILE_OFFSET_BITS 64, but there is always the option to just use the 64 postfixed functions on 32bit systems. Might need O_LARGEFILE on opening the file.

**Comment by enkore** [comment]
Note: Offsets is not the only issue. E.g. the current hashindex code does not loop long read()s, which will, at least on Linux, never read more than 2 GB.

**Comment by ThomasWaldmann** [comment]
hashindex 2GB means roughly 48 million buckets a 44 bytes each. so borg has an additional (not yet documented?) limitation here.

47858071 is the prime hashtable size directly below that and it can be 75% full before it grows to next size. So that means roughly 35 million used buckets.

If one has a lot of little files, one does not need a huge data volume to go beyond that...

**Comment by ThomasWaldmann** [comment]
The default target chunk size is ~ 2MiB for bigger files, but small files (that do not reach that size) create smaller chunks (1 chunk per file).

**Comment by ThomasWaldmann** [comment]
Workarounds:
- split source data into subsets and back them up to multiple repos.
- use tar to bundle huge collections of small files and backup the tar file / stream with borg.
