### ISSUE TITLE
Question about required disk size  

### ISSUE THREAD

**Issue by lorddaedra** [borgbackup/borg#1810]
Let's assume, we have two servers: 

1. server with borg backup repository and client , we have full access to this server, we have 300Gb of free disk space there (less than 2x200Gb).
2. target storage server with media files (without ability to install anything like borg client), only read access via ftps/rsync, let's assume, we have 200Gb of media files there (max filesize of every single image is 5Mb).

My questions: 
1. is it possible to backup second media files to first server?.. 
2. How much disk space will be required if I will try to mount sshfs and use borgbackup from this remote directory?.. 
a.) 400Gb ( ~200Gb [repository size] plus ~200Gb [full size of last version of image folder on storage server])
 or
b.) ~200Gb [repository size] + some more than 5Mb?

If answer is a.), can we improve something in borg create function to get answer b.) ?..

**Comment by enkore** [comment]
If I understand correctly, you want to backup the files from server (2) on the disks in server (1), correct?

In that case you will need ~200 GB of storage on server (1), where the repository is. Mounting the files to backup from server (2) won't need extra disk space on server (1). (Answer 2b.)

sshfs on server (1), making the files from (2) available, would work. borg-create then runs on server (1) (perhaps with --ignore-inode).

**Comment by lorddaedra** [comment]
> If I understand correctly, you want to backup the files from server (2) on the disks in server (1), correct?

Yes, correct.

So it's cheaper to use borg create from sshfs directory, instead of first rsync to local directory and next add from local directory to borg repository.

Thank you for your answers.

**Comment by lorddaedra** [comment]
I tested borg backups via sshfs, it can't be solution for backuping production systems with media directories bigger several Gbs because of it will take days or weeks to end backup task... It's take extremely long time to process requests... Looks like rsync to local folder + borg backup from local folder is better solution for now even if it require twice more disk space.

**Comment by lorddaedra** [comment]
I added feature request, which can help to solve this issue. https://github.com/borgbackup/borg/issues/1811

**Comment by ThomasWaldmann** [comment]
Closing (as the size question, which was the topic of this issue, was answered).
