### ISSUE TITLE
Export statistics or graph them with borg

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1812]
Just a feature suggestion. 

Either a statistics command or a command that exports some statistics in an easily parseable format like json so graphing solutions like grafana can use it. Or a statistics command that draws stats like `vnstat` ([image](http://www.serverninjas.com/wp-content/uploads/2013/04/vnstat-hourly-report.jpg)). 

Statistic items that are (IMHO) worth to graph:

 * number of files
 * time of completion
 * dedup size
 * compressed size
 * orig size
 * chunks  (personally not interested in that)

Here some pseudo UI:

     borg export-stats --format json path-to/repo > wonderful.json

Why is it important to log these infos?

Imagine you backup a data you don't have control over. E.g. a webserver with some software that creates thousands of php session files. This would slow down borg MASSIVLY. Or if you use higher compression and suddenly several gigs of compressed data appear.

It would be nice to see all the stuff in easy to understand graphs. It would allow to improve your retention policy. 

Some of these problems would be addressed by other festures / bug reports e.g.:

 * be faster with many files (think 5 mio 44kb files)
 * limit repo by size  → max retention
 * compression by file type
 * good defaults for compression by file type

This is just a suggestion. And i would like to hear your input about how to make this more useful and if you see a need for this.

**Comment by ThomasWaldmann** [comment]
Nice idea.

I'ld rather object adding graphing stuff to borg and doing that within borg. The interface should be that borg exports such data in easily readable format for external graphing tools - like csv or json.

A first step in that direction could be that borg info archive gives some more info (see above).

**Comment by enkore** [comment]
http://borgbackup.readthedocs.io/en/latest/internals/frontends.html#standard-output
