### ISSUE TITLE
Improve Repo README

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1813]
It is really great that Borg has a repo README so you kind of know what the weird data in the directory is. 

But it is quite lacking if you have really no idea. Here some suggestions for improvement. Please add your own.

 * Mention that borg is a backup solution
 * Link to the project site
 * Explain in one or two sentences what borg does and what it provides.
 * Explain what a repo is. Or reformulate. (Imagine a non technical person reading this file.)
 * Add creation date of the repo
 * last time of backup

The last point would really help if you don't have borg available.

**Comment by ThomasWaldmann** [comment]
The README is not intended to be documentation or a feature list, so it should be minimal and make clear (in understandable language), what that directory contains. Using your favourite search engine to get more information is always possible.

I don't like putting any metadata about the repo in there (like creation / modification dates), the README is for humans, let's not mix machine processable data in there. You can look at timestamps of misc. other files/dirs to get hints about repo creation or updates.

**Comment by enkore** [comment]
I guess we can add a link to http://borgbackup.rtfd.io , but I don't think it needs any long explanations. Metadata, or anything mutable, should not go in there.

**Comment by bjornfor** [comment]
An idea: "This is a Borg repository" -> "This is a Borg Backup repository". I think the word "Backup" can be helpful to some people.
