### ISSUE TITLE
Best practise for journald?

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1817]
My setup looks like this:

 * systemd timer that invokes unit
 * systemd unit that invokes a bash script
 * bash script invokes borg several times

The script only outputs `borg -s` so when i look in the journald log i only see the stats. I don't see the command nor the target repo of the command. 

My work around is to name the archive with target repo and backup source. 

Is there a better solution to run borg? Or is there an option to include command and repo in the stat output when running interactively.

**Comment by enkore** [comment]
You can use `set -x` in your bash script to print all commands executed to stderr.

**Comment by edgewood** [comment]
I have this in my borg wrapper script:

borg() {
    echo borg "$@"
    /path/to/borg "$@"
}

-- 
Ed Blackman

**Comment by rumpelsepp** [comment]
You could also pipe to `logger`.

**Comment by lightonflux** [comment]
All these are valid solutions and i already worked around it. But it sounds like a simple problem to solve. Although i don't think it should be saved in the repository as you don't need the info there. 

It would also be helpful if borg prints the full repo path. So for example instead of `borg-server:.`, ssh://root@borg-server.mydomain.com:/backup/borg/repos/zeus`. 

Can borg even do that? Know about the ssh command which is used when you configure a name in **~/.ssh/config**?

**Comment by enkore** [comment]
Not without parsing the SSH configuration file.
