### ISSUE TITLE
create: {now} date/time format for nanoseconds

### ISSUE THREAD

**Issue by caigner** [borgbackup/borg#1822]
When using **{now}** The date/time is also including nanoseconds:
`2016-11-10 10:31:04.255053`

I don't like the whitespace between date and time (because I have to use quotes when using the archive name). So I tried it like this: **{now:%F_%T}**, which produces:
`2016-11-10_10:45:55`

Fine, but I am missing the nanoseconds. For this there is %N in date-format. But **{now:%F_%T.%N}** doesn't work in Borg Backup.

Please consider adding %N (and maybe even %3N, for microseconds) support to {now}.

Thanks!
Christian

**Comment by RonnyPfannschmidt** [comment]
the chars that python does support are listed on https://docs.python.org/3.5/library/datetime.html#strftime-strptime-behavior

according to that microseconds are supported using %f

as for nanoseconds, that tends to be an extension of the c library

python does call the underlying c library for formatting that - so you might need to check out that

**Comment by enkore** [comment]
`{now:%F_%T.%f}` gives nanosecond resolution.

TODO: Document this in borg-create help: http://borgbackup.readthedocs.io/en/latest/usage.html#borg-help-placeholders

**Comment by caigner** [comment]
Guys, you are great! Thanks!

**Comment by ThomasWaldmann** [comment]
BTW, the issue with the blank is solved in future borg 1.1, it uses "T" as separator as the iso standard says.

**Comment by enkore** [comment]
Fixed by #1863
