### ISSUE TITLE
Feature proposal: Add ability to check given archive against backed up source files (=PATH in borg create command)

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#1828]
I have to say that borg backup is very impressive product and already as such ready for most of my needs. However to make it even better I filed this proposal.

Feature proposal: Add ability to check given archive against backed up source files (=PATH in borg create command)

Now there are very good ways to check repo and archive internal consistency. This is very good but to have a total detection against bitrot and other media errors you should have a way to afterwards check archive contents against backup source files on disk (=PATH in borg create command).
Now this is only possible e.g. by doing borg extract to another dir and then diff -r between extracted dir and source dir. 
It would be nice if borg could do this "extract given archive and diff it with actual source files on disk" with a single command and report all mismatches in a human and machine readable way.
This command would be the last part of a chain to detect that backup is valid and it really contains files as they are on disk.
Another use for this command could be to easily check changes between an older archive and current state on disk. (E.g. diff style output: list files only in archive, list files only on disk, list modified files and their modifications)
This command could be an option in borg check.

This proposed functionality is like --compare option in tar command.

**Comment by enkore** [comment]
Hi, thanks for the proposal and the good description.

There is a very similar feature request in #963, so I'm closing this one as a duplicate. But it will be linked from #963, so it's not lost in any way :)
