### ISSUE TITLE
Borg Backup Hangs

### ISSUE THREAD

**Issue by kevdogg** [borgbackup/borg#1838]
Unfortunately I've seen a few posts regarding the issue about borg backup hanging, however none more recent than February 2016

Client Arch linux - Running borg backup 1.07 with python 3.5.2
Server - Ubuntu 16.04 Running borg backup 1.0.8

The backup will start however after a period of time the backup will freeze.  Here is the output with -v --debug flag:

Borg Backup started at: Sat Nov 12 14:00:39 CST 2016
using builtin fallback logging configuration
Remote: using builtin fallback logging configuration
Reading files cache ...ome/kevdog                                               
31.79 GB O 13.09 GB C 74.09 MB D 96205 N home/kevdog/work...history/segments.gen

It gets to this point and then the numbers and stats will freeze and I'll have to kill the process.  I've rebooted computers several times but it doesn't seem to make a difference.
Sometimes the process will freeze after 1-2 minutes and others it will take about 30 min.  I've only recently within the last week have begun to have this problem

Both computers are on a local network and I can complete a similar rsync backup of the same files/directories as the borg backup without a stall.

Previous post have mentioned a problem with python version.

**Comment by enkore** [comment]
How long have you waited after the freeze to kill it (approx)?

Does it exhibit any activity (CPU / iotop / nload)?

**Comment by ThomasWaldmann** [comment]
Is there anything in the kernel log (dmesg / syslog)? Like disk having troubles or some other low level stuff?

Usually this should lead to an error, but maybe something is retrying for long?

**Comment by kevdogg** [comment]
I think I discovered the problem --- disk space is full -- argh.  Hmm maybe borg should detect this?? Clearly my fault here.

**Comment by enkore** [comment]
We improved handling of that situation for 1.1.x, although it shouldn't hang with 1.0.x.

**Comment by enkore** [comment]
Unclear whether any issue remains. Closing. Feel free to reopen if this assessment is not accurate.
