### ISSUE TITLE
Index object count mismatch. 519348 != 519198, gone on "borg check --repair"

### ISSUE THREAD

**Issue by mgeisler** [borgbackup/borg#1852]
Hi all,

I've started using Borg a few days ago with rsync.net and have been impressed with the speed and functionality so far. Today I ran `borg check` and got:
```
$ borg check -v
Remote: Starting repository check
Remote: Index object count mismatch. 519348 != 519198
Remote: Completed repository check, errors found.
```
That didn't sound very good, so I tried again with the `--repair` flag:
```
$ borg check -v --repair
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Remote: Starting repository check
Remote: Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive hbox-2016-11-14.21 (10/10)
Analyzing archive hbox-2016-11-14.18 (9/10)
Analyzing archive hbox-2016-11-14.15 (8/10)
Analyzing archive hbox-2016-11-14.12 (7/10)
Analyzing archive hbox-2016-11-14.09 (6/10)
Analyzing archive hbox-2016-11-14.06 (5/10)
Analyzing archive hbox-2016-11-14.00 (4/10)
Analyzing archive hbox-2016-11-13.17 (3/10)
Analyzing archive hbox-2016-11-13.16 (2/10)
Analyzing archive hbox-2016-11-13.15 (1/10)
Archive consistency check complete, no problems found.
```
Now the errors are somehow gone? Or does `borg check` not print anything if it finds and repairs an error?

I've been creating and deleting many more archives than shown above, and I've also aborted many commands with Ctrl-C when they took longer than expected. Some times, I had to run `borg break-lock` to remove the lock files left behind when command is interrupted. I'm pretty certain, however, that no other Borg command was running in those cases since I was still testing things manually.

I'm using Borg 1.0.7 both locally (Debian Testing) and remotely (FreeBSD).

**Comment by infectormp** [comment]
duplicate? https://github.com/borgbackup/borg/issues/1598

**Comment by mgeisler** [comment]
Thanks @infectormp, it could very well be a duplicate of #1598. However, that issue talks a lot about the beta version 1.1.0 whereas I've only used 1.0.7.

**Comment by ThomasWaldmann** [comment]
Can you check whether your disk (see SMART) and filesystem is ok?

**Comment by mgeisler** [comment]
Hi @ThomasWaldmann. I have had problems with my drives – hence the sudden interest in an off-site backup! :-) I started experimenting with Borg shortly before my drives gave up completely, and there were indeed some read errors while backing up.

I guess the errors are not too surprising in that light – but I found it surprising to see the error disappear from one run of `borg check` to another. Maybe it has simply repaired itself if there was a backup run in between the two checks?

**Comment by enkore** [comment]
When --repair fixes (this specific) issue then no diagnostic is currently printed.

This could've happened if a remote serve process was still doing something (even with the client dead -- it seems that *somehow* that is possible) and another borg also did something. IIRC segment files are opened in exclusive mode since a while, so only inconsequential inconsistencies, like the one you saw here, should happen on the usual OS+FS combinations (exclusive open has to be supported by OS + FS).

**Comment by ThomasWaldmann** [comment]
@enkore how can that be? the repo is locked in the repo / by the server process.

**Comment by enkore** [comment]
> I had to run borg break-lock

**Comment by ThomasWaldmann** [comment]
OK, for borg break-lock one must make sure no borg is running any more, documented.

**Comment by mgeisler** [comment]
> OK, for borg break-lock one must make sure no borg is running any more, documented.

Yes, it's nicely documented and completely expected that one shouldn't break locks while there are still live processes around.

However, I believe there weren't any other processes around since I was running them by hand at that time. (I was surprised by the number of times a lock file was left behind, but that's another story.)

**Comment by mgeisler** [comment]
> When --repair fixes (this specific) issue then no diagnostic is currently printed.

Thanks, that's good to know! I think we can close this issue then.
