### ISSUE TITLE
Add option to disable backup of atime and ctime

### ISSUE THREAD

**Issue by cyril42e** [borgbackup/borg#1853]
Hi, I just noticed that borg now backups atime and ctime since version 0.28.0 (issue #317), and this is a problem for me :
- I use rsync daily to update a mirror of my data, and less often create borg archives. Rsync sets atime, so it means that the metadata of my archives can never be deduplicated (and they are close to 400MB for each archive). I have found a patch for rsync to prevent it to set atime, but it has been around there for years and has never been integrated.
- It does not make a lot of sense to me to duplicate metadata because I've done a batch grep on a directory, or an index tool has visited them, or I even just read some files.
- Sometimes I create the borg archive from one of my mirrors, so all the files have different ctime, and again this prevents the metadata from being deduplicated with the archives of another disk, even if the file tree is identical.

Does it make sense to at least add an option to "borg create" to disable backup of atime and ctime ? (in this case they could be set to the same value as mtime).

**Comment by ThomasWaldmann** [comment]
Sounds like reasonable use cases and adding `--noatime` and `--noctime` to `borg create` might be easy.

**Comment by jazcap53** [comment]
Hi folks,
I'd like to have a shot at this issue. It would be my first contribution to open-source.

I've been trying out borgbackup for a week, it's a very worthwhile project. I spent a few hours today looking at the relevant code and tests, and as @ThomasWaldmann says, it *might* be easy to implement #1853. 

Please don't let the gray beard fool you; I'm fairly new at Python, with some C++ and C and UNIX/Linux in my background.

**Comment by ThomasWaldmann** [comment]
@jazcap53 cool, go for it! ;) If you have something and want first feedback, just open a pull request.

**Comment by jazcap53** [comment]
@ThomasWaldmann Will do!

**Comment by ThomasWaldmann** [comment]
Making progress? We plan rc1 for next saturday or so.

**Comment by jazcap53** [comment]
Have read a lot of code over the last 2 days and it's going well. Getting ready to try out some changes.
I'll have some specific questions within the next hour or so.
I have nothing but free time between now and saturday :)

**Comment by ThomasWaldmann** [comment]
If you like, join us on #borgbackup on freenode IRC.

**Comment by jazcap53** [comment]
OK

**Comment by ThomasWaldmann** [comment]
@jazcap53 see #1883

**Comment by jazcap53** [comment]
Thank you!

**Comment by ThomasWaldmann** [comment]
fixed by #1883.
