### ISSUE TITLE
improve docs about upgrade of passphrase-encrypted attic repo with borg >=1.0

### ISSUE THREAD

**Issue by sebcworks** [borgbackup/borg#1854]
I have a remote Attic repository that was encrypted (so, with a passphase).

When I'm doing an upgrade (`borg upgrade <repo>`) localy, on the server, it won't ask for passphrase and thus, will do an upgrade that, at the end, won't be usable. Doing a "migrate-to-repokey" aferward won't restore the repository.
For now, my only solution (validated by @ThomasWaldmann on IRC) is to do a first upgrade with a version prior to 1.0 and finally, the upgrade with the 1.0

Suggestion:
It would be great to have a option in the upgrade command to tell that the repo is passphrase-encrypted and thus, ask for it to create a repokey protected by the same passphrase.

**Comment by enkore** [comment]
I'm labelling this corruption because I understand that the converted repository is not accessible and if --inplace were used it would be not usable anymore.

**Comment by sebcworks** [comment]
After trying to find the best way to upgrade an encrypted attic repo, I found that doing `borg migrate-to-repokey` after the `borg upgrade` **do actually work**. 

The fact is, at first, I wrongly do the upgrade process as root while the repo owner was a normal user. Thus, the "ugpraded" config file was owned by root, but I tried to do `migrate-to-repokey` as the real owner of the repo (as I noticed that converted files were now owned by root, I restore owner for all the data folder but seems to forgot the config file).

So the following should work:
```
attic init --e passphrase testing_to_borg.attic
attic create --stats testing_to_borg.attic::backups-2016-11-17 /path/to/data
attic list testing_to_borg.attic

borg upgrade -p --debug testing_to_borg.attic

borg list testing_to_borg.attic # Fail
attic list testing_to_borg.attic # Fail

borg migrate-to-repokey testing_to_borg.attic

borg list testing_to_borg.attic # Works
```

Also, I notice that after doing the migrate-to-repokey command, the config file of the copy is modified as well, is it normal?

**Comment by ThomasWaldmann** [comment]
OK, so you tested this procedure with current borg and you did not need to use borg < 1.0?

**Comment by sebcworks** [comment]
Yes. Was still with current (1.0.8)

**Comment by ThomasWaldmann** [comment]
OK, so I am changing this to a "improve docs" issue.

**Comment by enkore** [comment]
Fixed by #1863

**Comment by sebcworks** [comment]
I'm answering to this issue to warn about a problem: 
Even is the process of upgrading the attic repo is a success, a `borg check` will report an error "_Did not get expected metadata dict when unpacking item metadata ..._" for every chunk.

**Thus, a `borg check --repair` will simply delete all the data,** leaving a repository with the list of all archives, but it is impossible to restore any file of any archive!

I was able to mount any archive and to check the validity of the files, so it seems to be related to `borg check`

**Comment by enkore** [comment]
This might be #1837 if the repo was used with attic versions 0.13 and earlier.

**Comment by ThomasWaldmann** [comment]
I posted a warning on twitter and the borgbackup mailing list.

**Comment by sebcworks** [comment]
It is definitely related to #1837 as my repository was on attic 0.13

Thanks for the reactivity.
