### ISSUE TITLE
Bitrot mitigation

### ISSUE THREAD

**Issue by zatricky** [borgbackup/borg#1866]
I'm considering using borg (capitalisation?) for remote backup, hence this question.

Does borg have a built-in feature to mitigate bitrot?

It is one of the few features that I'm unable to verify. Admittedly, bup seems to be the only other backup tool that _specifically_ mentions the feature, though bup doesn't seem appropriate for my use-case anyway.

**Comment by enkore** [comment]
Borg has strong integrity checking, to detect bitrot.

check --repair can repair files with corrupted data (replace it with runs of zero), and heal them later should the data become available in the repo again.

Forward error correction (FEC) which would mean that bitrot can be corrected in place is not implemented at this time (#225)

**Comment by ThomasWaldmann** [comment]
We already have #225, so close this one?

**Comment by enkore** [comment]
I guess. ftr: duplicate / closed shouldn't stop anyone from asking follow up questions :)
