### ISSUE TITLE
Stats info is not refreshed when copying big files

### ISSUE THREAD

**Issue by 33hops** [borgbackup/borg#1873]
Thank you for this great software. 
I am testing Borg Backup to use it to copy big virtual disk files. It works well, but I miss that the statistics aren't refreshed more often. When copying a lot of small files the progress shows up well, but when you get to copy one single big file, you have to wait until the copy process has finished to know what's happened.

**Comment by enkore** [comment]
Can you post which commands you are using?

**Comment by 33hops** [comment]
borg create --stats --progress --compression lz4 /root/backups/vmsbackup1::1 my-virtual-disk.vmdk

**Comment by ThomasWaldmann** [comment]
IIRC this is fixed in 1.1 (came with the in-file checkpoint code).

**Comment by 33hops** [comment]
O.K., I'm new to it. Thanks for the info, I'll compile a newer version.

**Comment by enkore** [comment]
Hm, the progress display always updated itself when working on big files.

**Comment by 33hops** [comment]
I'm using 1.0.8
I didn't get Thomas well then. He pointed that there was a bug fixed in v. 1.1?

**Comment by enkore** [comment]
I'm not sure what he's referring to, I don't think anything besides in-file checkpoints was changed by adding them.

**Comment by 33hops** [comment]
Now it works after some seconds of initiating the backup. I'm using putty, not a direct console. This might be the cause. I'll investigate it further and let you know. Thank you.

**Comment by enkore** [comment]
Yes, while initializing the transaction it doesn't display anything. I think while loading the files cache it just display "0 .. 0 ..0 ... 0 N" or something like that.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/1217/files#diff-a7aee10470e434998489f84fe93dc2bcR740

I meant that part of the PR that implemented in-file checkpoints.

**Comment by enkore** [comment]
But that wasn't new ;) https://github.com/borgbackup/borg/pull/1217/files#diff-a7aee10470e434998489f84fe93dc2bcL775

**Comment by ThomasWaldmann** [comment]
new for stdin processing: https://github.com/borgbackup/borg/pull/1217/files#diff-a7aee10470e434998489f84fe93dc2bcL708

**Comment by enkore** [comment]
Ahh, ok.

Close/resolved?

**Comment by ThomasWaldmann** [comment]
I tested it again, yes, 1.1 updates the progress display regularly while processing a (big) file. Closing.

@33hops keep in mind that 1.1 is still beta, so testing is ok, but any important production use is not recommended yet.
