### ISSUE TITLE
no progress indication on segment replay

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#188]
happens when nuking all indexes for regen

**Comment by ThomasWaldmann** [comment]
So which indexes do you mean precisely?

**Comment by RonnyPfannschmidt** [comment]
i removed the `hint.$NUMBER` and `index.$NUMBER` files in the root of the archive

**Comment by ThomasWaldmann** [comment]
I suppose you mean with "borg check"? See also #195.

**Comment by ThomasWaldmann** [comment]
See #394.
