### ISSUE TITLE
please add "borg info $reponame::*" or "borg info $reponame::ALL"

### ISSUE THREAD

**Issue by devZer0** [borgbackup/borg#1880]
when doing every day incremental forewer backup with borg, after some days it`s difficult to get an overview on which archive got most of the change (i.e. most of new unique chunks being added), as you need to walk trough all the archives manually/by script to do a report.

for example, if i backup several systems every day with borg and the backup server gets out of space, i`d like to wipe out the largest archive first as it may contain a temporary large file which shoud not have been backed up at all - so i need to write a scripte which does "borg list" to get the list of archives and then step trough every single $archive with "borg info $reponame::$archive"

i wonder, why we can`t have this builtin, as i think this is pretty usefull. adding it would not break existing functionality

when trying out borg for the first time, i was intuitively trying "*" or "all" and found, that it does not exist.

i mean like this:

<pre># borg info /repos/repo1::*
Name: All Archives

                       Original size      Compressed size    Deduplicated size
1st-archive:                11.30 GB              4.26 GB              2.00 GB
2nd-archive:		     7.69 GB              3.90 GB              1.21 GB
3rd-archive:                 7.24 GB              4.44 GB            556.56 MB 
4th-archive:		     7.71 GB              3.91 GB             30.76 MB 
------------------------------------------------------------------------------
All archives:               34.94 GB             16.51 GB              7.30 GB

                       Unique chunks         Total chunks
Chunk index:                  133204               585514
</pre>

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/pull/1412?

**Comment by enkore** [comment]
That isn't yet implemented (neither borg-list nor borg-info can give you the O/C/D sizes of the archives), but sounds useful, although it won't be particularly fast (the data has to be calculated on each invocation), think n-times borg-info.

**Comment by ThomasWaldmann** [comment]
in 1.1 we already have --last / --first / ... - this looks like an extension of this.
if we would pack that into the archivename, it might cause troubles with archives already named like that (maybe not very likely), so not sure that is the right way. also, if "*" means all, people might expect there is archive name matching with wildcards.

**Comment by wolfpackmars2** [comment]
@ThomasWaldmann I came here to request "archive name matching with wildcards" but I think this issue fits the bill.

Is there a reason there *shouldn't* be wildcard matching on archive names?

I'm surprised there isn't.  For example, if I have archives in format: YYYYMMDD-{ClientName} and I have several clients using the same repo, I feel I should be able to get info using wild card matching.

Return all archives containing "ClientPCNumber" in the name. E.g. '20170425-ClientPCNumber01', '20170424-ClientPCNumber01', '20170424-ClientPCNumber02', etc.
```borg info MyRepo::*ClientPCNumber*```

Return all archives for "ClientPCNumber02" created in April 2017.
```borg info MyRepo::201704*ClientPCNumber02```

There are options --first, --last, and -P/--prefix, but those seem like incomplete implementations trying to solve this problem.  These options could all be replaced by handling wildcards in archive names, IMO.

**Comment by wolfpackmars2** [comment]
> so i need to write a scripte which does "borg list" to get the list of archives and then step trough every single $archive with "borg info $reponame::$archive"

@devZer0 Have you written any scripts as you describe?

**Comment by ThomasWaldmann** [comment]
Well, --first/--last is a bit different from pattern matching.

Pattern matching on archive names: re, fm or sh? (see pattern styles we have implemented for files).
Or multiple of them?

OTOH: the Location regex to match this repo::archive is already crazy and problematic enough. :-(

**Comment by wolfpackmars2** [comment]
Personally, I am not interested in the headache that would be likely involved with using regex to match archive names.  From an operations perspective, I would expect this to work just like most other basic file system commands (`rm *.exe`, `cp my*file0?.xls`, etc).  I guess this would be "SH" matching.

I'm sure that some day someone will create a ticket requesting RE matching (not sure what FM matching is), but in the short term I think adding SH matching is a reasonable goal. If someone wants additional pattern matching, they can create a new ticket for that in the future :).

**Comment by enkore** [comment]
> I'm sure that some day someone will create a ticket requesting RE matching.

Tickets can be closed with wontfix.

> I think adding SH matching is a reasonable goal.

Yes. But only exactly one such option that is mutually exclusive with `--prefix`, e.g. `--glob-archives` with sh: semantics (because fm: never was reasonable to begin with).

**Comment by enkore** [comment]
#2448

**Comment by enkore** [comment]
I like this a lot btw. because I think prefix-based structuring is unreasonable and I don't use it at all in production.
