### ISSUE TITLE
RPC versioning issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1887]
From https://travis-ci.org/borgbackup/borg/jobs/179186074 : 

```
self = <RemoteRepository ssh://__testsuite__/tmp/tmpluqbot0p/repository>
args = (), kwargs = {}, sig = <inspect.Signature object at 0x7f1272e94dd8>
bound_args = <inspect.BoundArguments object at 0x7f1272d74c50>
named = {'limit': None, 'marker': None}, name = 'marker'
param = <Parameter at 0x7f1271e16990 'marker'>

    @functools.wraps(f)
    def do_rpc(self, *args, **kwargs):
        sig = inspect.signature(f)
        bound_args = sig.bind(self, *args, **kwargs)
        named = {}
        for name, param in sig.parameters.items():
            if name == 'self':
                continue
            if name in bound_args.arguments:
                named[name] = bound_args.arguments[name]
            else:
                if param.default is not param.empty:
                    named[name] = param.default
    
        if self.server_version < since:
>           raise self.RPCServerOutdated(f.__name__, format_version(since))
E           borg.remote.RPCServerOutdated: ('scan', '1.1.0b3')

.tox/py34/lib/python3.4/site-packages/borg/remote.py:375: RPCServerOutdated
```

If installed locally the verson is 1.1.0b3.dev243+ng5917822.

**Comment by ThomasWaldmann** [comment]
This is a bit urgent as it currently breaks all travis builds.

**Comment by ThomasWaldmann** [comment]
Also, I think the exception msg should contain both the required and the found version - we currently can only guess what version it found there.

**Comment by enkore** [comment]
I don't get this locally.

**Comment by enkore** [comment]
> py34 inst: /home/travis/build/borgbackup/borg/.tox/dist/borgbackup-**1.0.9.**dev242+ng5917822.zip

**Comment by enkore** [comment]
Ah but of course. The 1.0.9 tag is newer than the 1.1.0b2 tag. @RonnyPfannschmidt shouldn't setuptools-scm use the lexicographically higher and tree-ish closer tag?

**Comment by enkore** [comment]
I created another 1.1.dev1 tag: https://github.com/borgbackup/borg/releases/tag/1.1.dev1

Let's see if that helps.

**Comment by enkore** [comment]
Fixed. Restarting builds.

**Comment by enkore** [comment]
Somehow the main build passes but the PR builds fail. "AssertionError: own dev numbers are unsupported".

**Comment by enkore** [comment]
Fixed for now / until the next release(?)
