### ISSUE TITLE
introduce a ui object to control progress bars and so on

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#189]
while adding some status output for the segment replay, i noticed, that important details are missing
to control whether to show progress bars, where to show them and at what detail to show them,

**Comment by ThomasWaldmann** [comment]
only `borg create` has `--progress` option right now (not a progress bar, though).

**Comment by ThomasWaldmann** [comment]
about introducing "UI": next goal is to get output and logging right (even that is somehow tricky to differentiate and get right, see other ticket), so if you'ld like to add more UI than that, please post a plan how it will behave in different situations, like interactive use, when backgrounded, when output is redirected to a log file.

**Comment by anarcat** [comment]
closing this in favor of #314 which has more details and a proposed implementation.
