### ISSUE TITLE
borg mount: TypeError in error handler vol2

### ISSUE THREAD

**Issue by nmiculinic** [borgbackup/borg#1903]
Similar issue as in #1894 

```
/t/borg » ~/.local/bin/borg mount /mnt/data/gdrive/backup-borg /mnt/data
Enter passphrase for key /mnt/data/gdrive/backup-borg: 
Local Exception.
Traceback (most recent call last):
  File "/tmp/borg/borg/archiver.py", line 1957, in main
    exit_code = archiver.run(args)
  File "/tmp/borg/borg/archiver.py", line 1902, in run
    return args.func(args)
  File "/tmp/borg/borg/archiver.py", line 82, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository)
  File "/tmp/borg/borg/helpers.py", line 119, in load
    data = key.decrypt(None, cdata)
  File "/tmp/borg/borg/key.py", line 150, in decrypt
    raise IntegrityError('Chunk %s: Encryption envelope checksum mismatch' % bin_to_hex(id))
  File "/tmp/borg/borg/helpers.py", line 768, in bin_to_hex
    return hexlify(binary).decode('ascii')
TypeError: a bytes-like object is required, not 'NoneType'

Platform: Linux protagonist 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 
Linux: arch  
Borg: 1.0.9rc2.dev11+ngb25de0a  Python: CPython 3.5.2
PID: 10175  CWD: /tmp/borg
sys.argv: ['/home/lpp/.local/bin/borg', 'mount', '/mnt/data/gdrive/backup-borg', '/mnt/data']
SSH_ORIGINAL_COMMAND: None
```

I've manually installed commit b25de0ab38e396854646c1e6e96b41402372308f which is One after Merge #1895  was merged into 1.0-maintenance

**Comment by ThomasWaldmann** [comment]
Oh, oops. Should've looked around for similar places... - will do now.

**Comment by enkore** [comment]
Does this happen with other borg commands on this repository as well (eg list)?

**Comment by ThomasWaldmann** [comment]
Fix for error handler is ETA 5 mins.

**Comment by nmiculinic** [comment]
I've tried your patch. 

```
/t/borg » ~/.local/bin/borg mount /mnt/data/gdrive/backup-borg /mnt/data
Enter passphrase for key /mnt/data/gdrive/backup-borg: 
Data integrity error: Chunk (unknown): Encryption envelope checksum mismatch
Traceback (most recent call last):
  File "/tmp/borg/borg/archiver.py", line 1957, in main
    exit_code = archiver.run(args)
  File "/tmp/borg/borg/archiver.py", line 1902, in run
    return args.func(args)
  File "/tmp/borg/borg/archiver.py", line 82, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository)
  File "/tmp/borg/borg/helpers.py", line 119, in load
    data = key.decrypt(None, cdata)
  File "/tmp/borg/borg/key.py", line 152, in decrypt
    raise IntegrityError('Chunk %s: Encryption envelope checksum mismatch' % id_str)
borg.helpers.IntegrityError: Chunk (unknown): Encryption envelope checksum mismatch

Platform: Linux protagonist 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 
Linux: arch  
Borg: 1.0.9rc2.dev12+ng989b228  Python: CPython 3.5.2
PID: 19914  CWD: /tmp/borg
sys.argv: ['/home/lpp/.local/bin/borg', 'mount', '/mnt/data/gdrive/backup-borg', '/mnt/data']
SSH_ORIGINAL_COMMAND: None
```

Does this mean I have data corruption or?

**Comment by ThomasWaldmann** [comment]
Yes, something is wrong with the manifest. The hmac does not match.

**Comment by ThomasWaldmann** [comment]
Did you manually modify the key? Does the keyfile look ok?

**Comment by nmiculinic** [comment]
Ok, thank you!

The key should be alright, since it asked me again when I mistype. There's no keyfile, just simple password.

I'm trying to figure out what's wrong with my setup. Currently am migrating from old to new pc.. Run borg check on old, it works all right. 
It automatically pushes to googleDrive using drive. On new pc I encountered said problems. Right now I'm verifying md5 checksums of files to see if there's any inconsistency here.

**Comment by ThomasWaldmann** [comment]
Check permissions also.

**Comment by enkore** [comment]
I think the errors would hint at byte/bit-level corruption somewhere - disk/RAM/network.

**Comment by nmiculinic** [comment]
Disk... For some reason I don't have luck with exFat. 

I moved data from exfat to ext4, repulled from google drive and it works. Pulling on exfat had its problems due to some permissions regarding change/modification time...I think I'll give up on exfat, or maybe I should use something else than exfat-fuse in fstab?

**Comment by ThomasWaldmann** [comment]
For borg repo, better use a stable filesystem implemented in the kernel. ext4 is very stable.

FUSE filesystems sometime tend to be a bit slow. I noticed that for ntfs, significantly slow than ext4.

**Comment by ThomasWaldmann** [comment]
Your bug report helped to find/fix some issues, thanks!
