### ISSUE TITLE
Backup fails: Failed to create/acquire the lock, Unknown MAGIC in header

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#1909]
Backup fails: Failed to create/acquire the lock, Unknown MAGIC in header

One of my several borg backups fails every time. 

Running backup:

	borg create --debug -p -v -s -C lz4 jk@server:/home/jk/borgdata/client/workspace::2016-11-30_09:55:23 /home/jk/workspace --exclude '*/target' --exclude '*.jar' --exclude '*.class' --exclude '*.sjsir' --exclude '*.metadata' --exclude '*.idea' --exclude '*/winsrc'
	Failed to create/acquire the lock /home/jk/.cache/borg/d3b5ebf73d9506275310b8a764d155cb0db3b16e9d77065ef36a391c89fa1b7d/lock.exclusive (timeout).

So it seems a locking problem. There are no other borgs running so I break the lock:

	jk@client:~$ borg break-lock --debug jk@server:/home/jk/borgdata/client/workspace
	using builtin fallback logging configuration
	Remote: using builtin fallback logging configuration

And try backup again:

	borg create --debug -p -v -s -C lz4 jk@server:/home/jk/borgdata/client/workspace::2016-11-30_09:59:57 /home/jk/workspace --exclude '*/target' --exclude '*.jar' --exclude '*.class' --exclude '*.sjsir' --exclude '*.metadata' --exclude '*.idea' --exclude '*/winsrc'
	hashindex: /home/jk/.cache/borg/d3b5ebf73d9506275310b8a764d155cb0db3b16e9d77065ef36a391c89fa1b7d/chunks: Unknown MAGIC in header
	Local Exception.
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1684, in main
		exit_code = archiver.run(args)
	  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1621, in run
		return args.func(args)
	  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 85, in wrapper
		return method(self, args, repository=repository, **kwargs)
	  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 244, in do_create
		with Cache(repository, key, manifest, do_files=args.cache_files, lock_wait=self.lock_wait) as cache:
	  File "/usr/lib/python3/dist-packages/borg/cache.py", line 69, in __init__
		self.open(lock_wait=lock_wait)
	  File "/usr/lib/python3/dist-packages/borg/cache.py", line 158, in open
		self.rollback()
	  File "/usr/lib/python3/dist-packages/borg/cache.py", line 237, in rollback
		self._do_open()
	  File "/usr/lib/python3/dist-packages/borg/cache.py", line 151, in _do_open
		self.chunks = ChunkIndex.read(os.path.join(self.path, 'chunks').encode('utf-8'))
	  File "borg/hashindex.pyx", line 75, in borg.hashindex.IndexBase.read (borg/hashindex.c:1268)
	  File "borg/hashindex.pyx", line 63, in borg.hashindex.IndexBase.__cinit__ (borg/hashindex.c:1068)
	Exception: hashindex_read failed

	Platform: Linux client 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64
	Linux: Ubuntu 16.04 xenial
	Borg: 1.0.7  Python: CPython 3.5.2
	PID: 9277  CWD: /home/jk
	sys.argv: ['/usr/bin/borg', 'create', '--debug', '-p', '-v', '-s', '-C', 'lz4', 'jk@server:/home/jk/borgdata/client/workspace::2016-11-30_09:59:57', '/home/jk/workspace', '--exclude', "'*/target'", '--exclude', "'*.jar'", '--exclude', "'*.class'", '--exclude', "'*.sjsir'", '--exclude', "'*.metadata'", '--exclude', "'*.idea'", '--exclude', "'*/winsrc'"]
	SSH_ORIGINAL_COMMAND: None

This leaves the lock behind and next backup fails again when trying to get the lock.

However, repository check with --debug option says:

	Archive consistency check complete, no problems found.

What's the reason for this error and how can I fix it?

I had a power failure on server and backup client earlier but most likely backup was NOT running at that time.

**Comment by enkore** [comment]
> /home/jk/.cache/borg/d3b5ebf73d9506275310b8a764d155cb0db3b16e9d77065ef36a391c89fa1b7d/chunks

What are the first couple bytes of this file?

`hexdump -C /home/jk/.cache/borg/d3b5ebf73d9506275310b8a764d155cb0db3b16e9d77065ef36a391c89fa1b7d/chunks | head -n 10`

**Comment by jk-1** [comment]
hexdump -C /home/jk/.cache/borg/d3b5ebf73d9506275310b8a764d155cb0db3b16e9d77065ef36a391c89fa1b7d/chunks | head -n 10
	00000000  2b 05 8b 11 11 00 e2 01  87 28 13 02 f9 00 cc 05  |+........(......|
	00000010  5f 0d 49 08 f7 04 5e 16  c2 05 5b 07 87 18 f6 02  |_.I...^...[.....|
	00000020  24 0f 28 12 96 0f 6a 00  72 0a ac 0a db 03 1a 01  |$.(...j.r.......|
	00000030  47 00 d3 00 de 08 b9 04  0c 00 86 10 e5 01 9b 02  |G...............|
	00000040  1e 05 18 04 65 02 ce 01  9c 03 89 0f 1a 07 ba 0f  |....e...........|
	00000050  1e 09 60 13 ac 08 73 0b  ff 13 f6 06 72 17 15 18  |..`...s.....r...|
	00000060  03 00 8d 01 0f 0a 5f 03  61 02 b8 11 ff 00 d0 01  |......_.a.......|
	00000070  58 08 b8 04 74 02 6a 07  63 00 cf 0a 84 02 94 0e  |X...t.j.c.......|
	00000080  da 08 b5 00 16 0b 46 01  88 03 ff 05 70 02 cd 04  |......F.....p...|
	00000090  3f 04 88 01 22 04 40 07  59 08 fd 03 18 03 9c 00  |?...".@.Y.......|

**Comment by enkore** [comment]
Yeah that file is corrupted. It should start with BORG_IDX, followed by two 32 bit ints. At offset 0x10 there should be 0x20 0x0c (=32 byte keys, 12 byte values).

I'd say a `borg delete --cache-only <repo>` will fix this for now, but keep an eye out for other corrupted files or errors in dmesg or `smartctl -x /dev/TheDrive`.

**Comment by jk-1** [comment]
It seems that you are right, deleting cache fixed the issue. At least taking backup succeeds now, I run some further checks later. Thanks!
