### ISSUE TITLE
move repo - manually edit .cache/<id>/config afterwards?

### ISSUE THREAD

**Issue by devZer0** [borgbackup/borg#1910]
hello, 

i have a lot of borg repos - whenever i move my borg repos to a different backup-store, i need to edit tons of cache files:

find . -name "config" |while read line;do sed -i 's/path-before-move/path-after-move/g' $line;done

this sucks.

isn`t there a more easy way to tell borg that it`s repository has been moved around ?

**Comment by enkore** [comment]
If you move a  repository you get a prompt like this:

```
Warning: The repository at location /foo was previously located at /bar
Do you want to continue? [yN] 
```

([env var overrides](http://borgbackup.readthedocs.io/en/stable/usage.html#environment-variables))

Up to and including release 1.0.7 this had to be answered when modifying the repository (eg. `borg create/delete/prune`). Since 1.0.8 the answer is always saved immediately.

**Comment by devZer0** [comment]
i`m asking for a non-interacive way to tell borg that the repos have moved. apparently, there is no "proactive" way to tell borg that the repos have moved, besides search/replace config files in borg-cache.

**Comment by enkore** [comment]
You use any of the [mentioned env vars](http://borgbackup.readthedocs.io/en/stable/usage.html#environment-variables) to update it. The only caveat is that you need to do an operation that actually uses the cache, eg. `echo '' | borg create repo::moved-repo-{now} -` or `borg info repo::some_archive_that_exists`.

**Comment by sourcejedi** [comment]
The latest version of `borg` has a `config` command.  So nowadays I think it should be possible to `borg config --cache /new/path/to/repo previous_location /new/path/to/repo`.  (`previous_location` is the name of the config key that stores the location).
