### ISSUE TITLE
borg info requires repo_or_archive param

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1914]
So, just setting BORG_REPO env var and doing a `borg info` (without the param) does not work.

See how `borg list` does it, it works there.

Found in master branch, check 1.0-maint also.

**Comment by PeaceOff** [comment]
hey i am entering the open-source community, can i take a look?

**Comment by ThomasWaldmann** [comment]
sure, see archiver.py.

**Comment by PeaceOff** [comment]
on it, Thanks!

**Comment by ThomasWaldmann** [comment]
@joaocsf if you end your commit comment fix ", fixes #1914", github will automatically close #1914.

Fixed by #1917. Closing manually...

**Comment by enkore** [comment]
GitHub help: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by joaocsf** [comment]
Sorry, I didn't knew about that. Thank you for the information! I'm learning alot with this project!
