### ISSUE TITLE
rechunk lost all file content

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1920]
Note: it looks like this is a bug in (unreleased) borg 1.1, borg 1.0.x is not affected.

borg 1.1 (master branch), while trying to reproduce #1658, all went apparently(!) well, all checks succeeded, no tracebacks, no error msgs.

but then I noticed that in an archive list, all file lengths are 0.
when extracting the file, a 0 bytes file was extracted.
other metadata looked ok (uid/gid/timestamp/path).

what i roughly did was:

- copied bigger production repo to usb3 disk
- borg check --repository-only
- borg recreate (changed compression) on some archives
- borg delete on bigger number of archives
- borg prune, reducing the whole repo to ~ 10 archives
- borg check (complete, archives too)
- borg recreate with --exclude on a bigger directory
- borg check (complete, archives too)
- borg check --verify-data

I'll try to reproduce with lesser actions.

**Comment by RonnyPfannschmidt** [comment]
i presume a reproducer for at least my condition needs a few steps

my first naive untested idea is to do the following ones:

* create a few big files
* borg create --chunker-params $(borg_0_29_params)
* borg recreate --chunker-params default
* borg check
* borg check --verify-data

i hope i can follow up with verifying if that first idea is any good on the weekend
