### ISSUE TITLE
add st_size to item metadata?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1923]
when dealing with #1920 i noticed that all checks were pretty happy even though all file content was lost.

archive items currently do not have a size entry, so there is no way to implement:
- a consistency check: do all chunk sizes really add up to the files' length?
- an archive listing that can determine file length quickly - it needs to sum up the chunk lengths

So, shall we:
- add a size entry to metadata IF item has a chunks list
- add fallback behaviour to sum-of-chunk-sizes for old archives
- optimize borg list archive to directly use metadata file size
- do a (very small) optimisation to FUSE code to directly use metadata file size (it still needs to iterate over chunks to determine st_blocks)
- add borg check code that checks metadata file size vs. sum of chunk sizes
?

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/39711336-add-st_size-to-item-metadata)

**Comment by ThomasWaldmann** [comment]
@enkore any comment?

**Comment by enkore** [comment]
Yeah, sure why not.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/2157 fixed this.
