### ISSUE TITLE
setup.py: use pkg-config?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1925]
From IRC:
```
ronny$ ThomasWaldmann: btw, is there a reason for not using pkg-config in setup.py for the libs?
ronny$ pkg-config is basically a tool that given a database of configfiles can tell you if a lib exists and what cflags/ldflags it needs
ronny$ it would help building borg on nix for example (where there is no FHS, but pkg-config is correct#
lfam$ ronny: Is the reason for that to avoid setting BORG_SSL_PREFIX and BORG_LZ4_PREFIX?
lfam$ We have to do that in Guix
textshell$ pkg-config is fairly easy to use. So if the libraries we need have upstream .pc files it should be easy to use it.
ronny$ lfam: it would simply make deployment and packaging easier if the paths work out using the .pc files
lfam$ Yes, I'd prefer not to have to set those variables
lfam$ Although, they are a very minor "wrinkle" in our Borg package
lfam$ http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/backup.scm#n403
ronny$ lfam: currently nix does use the variables as well, but its a pain tho propperly use it when combining with overrides say to use a checkout as install source for nix-shell
```

**Comment by ThomasWaldmann** [comment]
https://github.com/matze/pkgconfig/

**Comment by ThomasWaldmann** [comment]
Had a look at pkg-config and esp. its python wrapper and it seems to be easy to use and an improvement compared to how we currently do it - so it seems worth switching to it and having `pkgconfig` as additional dependency.

**Comment by ThomasWaldmann** [comment]
openssl ok
zstd, lz4, zlib, lzma ok
libb2 does not support it (yet?) https://github.com/BLAKE2/libb2/issues/22

**Comment by ThomasWaldmann** [comment]
can somebody who has experience with C library development and pkg-config please make a PR against libb2 to add pkg-config support? the developer is unfamiliar with it and so am I.

**Comment by ThomasWaldmann** [comment]
https://github.com/matze/pkgconfig/pull/39 fixes the openssl version parsing issue.

wait until that is merged and released to pypi.

**Comment by ThomasWaldmann** [comment]
see PR #4437 - did a major cleanup to setup*.py while adding pkg-config support.

one open question:

Currently pkgconfig should be installed **before** borg's setup.py is invoked ("should" meaning: it will not crash if it is not installed, but in that case, it will just not support pkg-config mechanism).

I tried to add it to `setup_requires`, but that doesn't help because it is needed before that is processed.

@RonnyPfannschmidt any idea? can you review the PR?

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann i believe adding it in the build system section of pyproject.toml is going to elevate the issue a bit for pip usage/building - for normal building i propose printing a warning if its missing

the "structurally correct" solution would be to resolve the elements lazy when setup is already called and beyond the step of installing setup_requires, but it would be unreasonable to implement at first glance

given that the pyproject.toml build-system section is gaining traction i believe targeting that and giving a warning for legacy users should be sufficient

**Comment by RonnyPfannschmidt** [comment]
wrt doing a review - i took a quick skim, and it looks like a fabulous sweep, but i wont have time for a deeper one until the weekend, and even then i cant make promises

**Comment by ThomasWaldmann** [comment]
i had a try at adding `pyproject.toml`, but stuff broke (didn't find .c files that should have been generated by Cython), so I'll rather not do that within this PR.

**Comment by RonnyPfannschmidt** [comment]
I wont get to take a look this weekend, i came down with a cold

**Comment by ThomasWaldmann** [comment]
Oh, then best wishes!

**Comment by RonnyPfannschmidt** [comment]
Thanks, im fortunate to be in good hands
