### ISSUE TITLE
please add "non unique added" or similar to borg info

### ISSUE THREAD

**Issue by devZer0** [borgbackup/borg#1926]
whenever a borg archive is created and new files are added to the backup, after finishing, --stats perfectly shows how much data is being added and how effectly deduplication jumped in.

for example, if a system being backed up grew 100GB in size because there was some binary and compressed database (i.e. non dedup`able data) dumped to disk before borg ran, for the current archive run, you perfectly see those 100gb in the stats/log under "deduplicated size" and you also see it in "borg info" if it's still the most recent archive.

now, let borg run another time without changing anything on the source, that information gets completely lost if you don't keep the historical logs, i.e. you will never again know, at which point in time borg grew by another 100GB of uniqe and non deduplicateable blocks because if two archives contain the same file, the blocks aren't unique anymore and so they get not counted individually.

you cannot even get back that information if you step with "borg info" through all the archives, because borg info only shows unique chunks for each archive.

i would find it extremely useful (and less confusing), if borg info would contain another column which shows "non unique data added|changed", so you get a much better overview what`s going on.

let`s take this as an example:
<pre>
[root@backupvm2]# ls -la dbserver1/archive-*/u01/backup/rman/*.full|grep 82
-rw-r-----. 1 502 500 82488434688 25. Nov 20:16 archive-28-11-2016_17-11/u01/backup/rman/backup_711737149_664_1_20161125_928868412.full

-rw-r-----. 1 502 500 82488434688 25. Nov 20:16 archive-29-11-2016_14-39/u01/backup/rman/backup_711737149_664_1_20161125_928868412.full

-rw-r-----  1 502 500 82488434688 25. Nov 20:16 archive-03-12-2016_06-00/u01/backup/rman/backup_711737149_664_1_20161125_928868412.full
-rw-r-----  1 502 500 82510512128  2. Dez 20:19 archive-03-12-2016_06-00/u01/backup/rman/backup_711737149_710_1_20161202_929559613.full

-rw-r-----  1 502 500 82488434688 25. Nov 20:16 archive-04-12-2016_06-00/u01/backup/rman/backup_711737149_664_1_20161125_928868412.full
-rw-r-----  1 502 500 82510512128  2. Dez 20:19 archive-04-12-2016_06-00/u01/backup/rman/backup_711737149_710_1_20161202_929559613.full

dbserver1
archive-name                           orig-size    compr-size    dedup-size
archive-28-11-2016_17-11               109.06 GB     103.53 GB      14.49 MB
archive-29-11-2016_14-39               110.68 GB     105.08 GB      14.63 MB
archive-03-12-2016_06-00               204.27 GB     197.58 GB      14.26 MB
archive-04-12-2016_06-00               204.28 GB     197.58 GB      15.52 MB
----------------------------------------------------------------------------
All archives:                          628.29 GB     603.77 GB     196.75 GB

</pre>

as you can see, dedup size sums up to 196.75GB, but you can`t see at which point in time dedupe`d archive size grew significantly because another full compressed database dump entered the archive. you could gues it was betwwen 29.11 and 3.12 - but when you removed a non-dedupable file and added another one of the same size, in this case even original and compressed size would have stayed the same value and you never knew at which point in time your archive grew 100% in size.

so, for me when doing incremental backups which daily/weekly/montly retention, colum "deduplicated size" does not really contain useful information at all, as what can be typically seen is just the metadata growth. but that`s negligible few megabytes each day. i would find "non unique gb added" much much more interesting information.

**Comment by ThomasWaldmann** [comment]
I don't think this is possible (not even theoretically).

The value "this archive grews the repo by X" depends on all other archives, so it can't be just recorded and still be correct later (after other archives have been deleted or added).

Just as a simple example:
- your very first backup b1 grows the repo by big amount, say 100GB
- your second backup b2 of almost same data grows the archive by 50MB
- your third backup b3 of almost same data grows the archive by 70MB

Now you delete the first archive b1. If we recorded the big growth within metadata of this archive, it would be lost now. Also, it does not free up a lot of data as most of it are still referenced by b2 and b3.

Now one could assume that if we somehow still knew that b1 started the big growth, that then b2 and b3 might still contain the same data (if "bN" as name means Nth generation of same data set b) and reference the same big amount of chunks.

But this is somehow worthless information as other archives a1 .. aN might also reference these chunks now (and they were not marked with big growth as most was already there), so even deletion of all bN would not free much space.

**Comment by enkore** [comment]
The intent is probably to have the historical information ("what create -s showed", essentially).

**Comment by ThomasWaldmann** [comment]
It maybe helps if you do not think of borg as incremental backup program, it always does full backups - it just does not store the same data chunks multiple times (deduplication). Due to everything being full backups with references, everything is very symetric. The first reference to a specific chunk is not different from the second reference to same chunk.

**Comment by ThomasWaldmann** [comment]
@enkore yes, I understood that, but explained that even that can be a futile attempt...

**Comment by ThomasWaldmann** [comment]
Maybe it is simplest to look at the development of the "total chunks" value for a series of archives of the same data set. Except for inner duplication inside the same archive of same dataset, this is a growth indication. And it is independent of other archives.

**Comment by enkore** [comment]
Question looks to be answered. Unclear whether any issue remains. Closing. Feel free to reopen if this assessment is not accurate.
