### ISSUE TITLE
Appending data to an existing archive

### ISSUE THREAD

**Issue by 33hops** [borgbackup/borg#1935]
Is there a way to append data to an existing archive within a repo?. I have checked the docs, but I have found no way of appending data. Must all data be writen in a single operation?

**Comment by enkore** [comment]
> Is there a way to append data to an existing archive within a repo?

No

> Must all data [of a single archive] be writen in a single operation?

Yes, all data contained in an archive must be visited by one create operation.

Also see http://borgbackup.readthedocs.io/en/stable/faq.html#if-a-backup-stops-mid-way-does-the-already-backed-up-data-stay-there
