### ISSUE TITLE
Incorrect duration if clock jumps backwards during borg-create

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#1936]
Two bugs actually:

1. The duration becomes negative.
2. Negative deltas aren't correctly calculated, either.

Eg.: Starting around 00:52:00 (on the 6th), then crossing over to 23:57:00 (on the 5th) displays something along the lines of "-1 days 5 minutes xy seconds".

(Borg isn't the only one getting it wrong, though. GNU time says: "243user 18system -55:-28.37elapsed" -- note how the absolute time span is still wrong by about 50 minutes!).

IIRC we already store the duration in seconds in the archive metadata, so we'd only have to use a different clock to calculate that (I'd leave the timestamps as-is, no way knowing which one would be correct!), ie. a monotonic one that's good for at least a couple days (large creates and all).

**Comment by enkore** [comment]
Also, the progress display stops updating, since it is based on time.time, which jumps around as well.

**Comment by enkore** [comment]
Also there's the issue with the manifest timestamp in the cache -- with just the usual one hour jumps it *shouldn't* be a problem often, but maybe we should replace that with a counter in the future?

**Comment by ThomasWaldmann** [comment]
start time + duration might be less confusing when crossing a dst switch time.

**Comment by enkore** [comment]
All fixed in #1941
