### ISSUE TITLE
Tox failures in archiver.py

### ISSUE THREAD

**Issue by edgewood** [borgbackup/borg#194]
On current git master I get 53 failures in borg/archiver.py.  Git bisection finds the problematic commit is b3f5231.

All output at http://pastebin.com/Ykn5C5pr

Travis CI shows green on GitHub, and I can get a mostly clean run in a Debian Jessie chroot (two errors with sparse files that might be chroot related).  There must be something wrong in my environment, but I'm unable to figure out what.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann I think the testsuite needs a global autouse fixture to remove that env var

**Comment by ThomasWaldmann** [comment]
@edgewood the failures only happen when you have BORG_REPO=... defined when invoking tox?

**Comment by ThomasWaldmann** [comment]
I tried setting BORG_REPO to misc crap before invoking "fakeroot -u tox", but I can't reproduce the failures, everything passes here.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann they work for all kinds of tests

**Comment by edgewood** [comment]
Nothing matching "BORG" in the environment, and the failures also occur 
in a fresh shell after confirming that my .bashrc and .bash_profile 
haven't been modified.

-- 
Ed Blackman

**Comment by ThomasWaldmann** [comment]
@edgewood please specify the OS version and platform you use.

I am seeing similar failures on Ubuntu 12.04 32bit.

**Comment by edgewood** [comment]
Indeed, I'm on Ubuntu 12.04.5 32-bit.
-- 
Ed Blackman
Sent from my OnePlus One. Please excuse my brevity.


-------- Original Message --------

**Comment by ThomasWaldmann** [comment]
it's an argparse issue. luckily, I am the pypi maintainer of that. :D

**Comment by ThomasWaldmann** [comment]
crap, now I have a fixed argparse in venv and it still imports the buggy one from stdlib.
any ideas?

**Comment by ThomasWaldmann** [comment]
PR #199 fixes this by adding borg.support.argparse with argparse taken from py 3.2.6.
python < 3.2.4 and python 3.3.0 are broken. as long as we have to support them, there is no other way to fix this.

**Comment by edgewood** [comment]
On Sat, Sep 12, 2015 at 04:20:33PM -0700, TW wrote:
>Closed #194.

Fix confirmed here, many thanks!

-- 
Ed Blackman
