### ISSUE TITLE
is borgbackup broken in jessie backport  repository?

### ISSUE THREAD

**Issue by jsalatiel** [borgbackup/borg#1942]
I am trying to install borgbackup on debian jessie ( stable ) and it wont work:
`# sudo apt-get install borgbackup`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 borgbackup : Depends: python3-msgpack (>= 0.4.6~) but 0.4.2-1 is to be installed
E: Unable to correct problems, you have held broken packages.

My sources.list is pratically default:

deb http://mirrors.kernel.org/debian/ stable main non-free
deb-src http://mirrors.kernel.org/debian/ stable main
deb http://security.debian.org/ stable/updates main
deb-src http://security.debian.org/ stable/updates main
deb http://mirrors.kernel.org/debian/ stable-updates main
deb-src http://mirrors.kernel.org/debian/ stable-updates main
deb http://http.debian.net/debian jessie-backports main

**Comment by enkore** [comment]
Not 100 % sure here but you probably need to do something like `apt install -t [jessie-]backports borgbackup`, perhaps with python3-msgpack itself.

**Comment by jsalatiel** [comment]
Thanks , it worked =)
