### ISSUE TITLE
Question: cron troubles

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1943]
I have an old machine without systemd and only cron. But i can't get it to run:

Here my /etc/cron.d/borg entry:

    SHELL=/bin/sh
    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    0 2 * * BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes /usr/local/bin/borg create -vsC lz4 /srv/borg/repos/maximus::{now:\%Y-\%m-\%d}-maximus /mnt/maximus  >> /var/log/borg.log 2>&1

(Runs perfectly in a script, with all three lines without the cron-time part)

**Comment by enkore** [comment]
Log?

**Comment by lightonflux** [comment]
cron[3214]: Error: bad username; while reading /etc/cron.d/borgbackup

The big problem was the escaping of the date variables (`\%Y`) because % is a line break in cron.

The second problem was a lacking username.

The line has to be:

     0 2 * * * root BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes /usr/local/bin/borg create -vsC lz4 /srv/borg/repos/maximus::{now:\%Y-\%m-\%d}-maximus /mnt/maximus  >> /var/log/borg.log 2>&1
