### ISSUE TITLE
borg unmount command?

### ISSUE THREAD

**Issue by lightonflux** [borgbackup/borg#1947]
Just noticed that you can mount a backup without having fusermount to unmount it. (I think it is not a dependency of the deb package).

So a `borg unmount` or `borg umount` command would be nice, just for consistency sake. 

Maybe make it more like traditional mount. 

   * `borg mount` without options lists mounted borg backups
   * `borg u(n)mount` unmounts

**Comment by jungle-boogie** [comment]
> Just noticed that you can mount a backup without having fusermount to unmount it

Can you point me to the documentation regarding that?

**Comment by ThomasWaldmann** [comment]
borg umount is already implemented, see changelog.

**Comment by lightonflux** [comment]
> Can you point me to the documentation regarding that?
https://borgbackup.readthedocs.io/en/1.0.8/usage.html#id29

@ThomasWaldmann I could not find it in the docs/changes.rst file.

**Comment by enkore** [comment]
It's in 1.0.9rc1 http://borgbackup.readthedocs.io/en/latest/changes.html#version-1-0-9rc1-2016-11-27
