### ISSUE TITLE
Borg doesn't substitute placeholder

### ISSUE THREAD

**Issue by iLLogical2007** [borgbackup/borg#1948]
I issued the following commands to create a backup of a folder that is containing Proxmox image files:

`borg create --stats --progress -C zlib,6 /backup/vnode01-proxmox::lxc-2000-{now:%Y-%m-%d_%H:%M:%S} /var/lib/vz/images/2000`
`borg create --stats --progress -C zlib,6 /backup/vnode01-proxmox::lxc-3000-{now:%Y-%m-%d_%H:%M:%S} /var/lib/vz/images/3000`

Now when I'm checking the repository I run into following problem:

`borg list /backup/vnode01-proxmox`

> lxc-2000-{now:%Y-%m-%d_%H:%M:%S}     Mon, 2016-12-12 22:15:31
> lxc-3000-{now:%Y-%m-%d_%H:%M:%S}     Mon, 2016-12-12 22:31:52

As you can see it seems that borg does not substitute the {now} placeholder (I also tried it w/o the formatting - just used {now}, but same result).

Borg version:
`borg --version`
> borg 1.0.0rc1

**Comment by enkore** [comment]
1.0.0rc1 is outdated - the GitHub releases page is kinda confused ATM. You'll find the current stable release (1.0.8) further down.
