### ISSUE TITLE
better progress indication for borg check

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#195]
after starting borg check, it first starts a repository check.

this can take rather long and there is no output at all until Repository.check() finishes.

afterwards it does archive checks, they output 1 line per archive.

**Comment by anarcat** [comment]
i wonder if this was fixed in the verbosity PR, see #303

**Comment by ThomasWaldmann** [comment]
can you link to the changeset rather than the PR?

**Comment by anarcat** [comment]
i'll dig.

**Comment by anarcat** [comment]
efa88ef6 comes to mind... it's actually in #233 ... and it was a sneaky side-effect that crept in.

**Comment by ThomasWaldmann** [comment]
See #394.
