### ISSUE TITLE
repo check speedup: add ability to restart an interrupted check, verify data in parallel

### ISSUE THREAD

**Issue by borkd** [borgbackup/borg#1952]
First, hats off and big thank you to entire borgbackup community!

Repository check takes a considerable amount of time on a multi TB-sized repo. Sometime life happens as this process works its magic. It would be nice if borg check picked up the pieces after last known check instead of starting from scratch. This would also allow folks to do scheduled rolling-style checks as time and resources permit.

1. Please consider adding an option to restart the check from a last unchecked segment.

2. Please consider allowing CRC and other checks to run in parallel. Even modest consumer 
configurations have multiple cores and enough disk bandwidth to handle that these days.

**Comment by enkore** [comment]
Re. 1: See #1657 

Re. 2: Multithreaded code is not allowed in the 1.0/1.1 series, but one of the two main goals of the 1.2 development cycle. Another (large) speedup for the CRC check is currently evaluated by me -- might get into 1.1.

**Comment by ThomasWaldmann** [comment]
What you can do right now is to run borg check --repository-only and --archives-only separately.

Still, if you repo is big, even the --repository-only check will take quite some time.

**Comment by borkd** [comment]
I did separate the checks like that, ran under screen and all, only to have network outage spoil the fun towards the end of day #3 at ~48%. Check runs on a server that consumes cloudy/distributed storage.

**Comment by ThomasWaldmann** [comment]
closing this, we have it already it other tickets.
