### ISSUE TITLE
Multiple [Errno 22] Invalid argument on lxcfs

### ISSUE THREAD

**Issue by viceldan** [borgbackup/borg#1956]
Server: Ubuntu 16.04, Freshly installed borgbackup  1.0.7-0ubuntu1.16.04.1
Client : Ubuntu 16.04, Freshly installed borgbackup  1.0.7-0ubuntu1.16.04.1

Copied public ssh key of root from Client to server into Server's /root/.ssh/authorized_keys => passwordless ssh as root works.
All commands on Server and Client were done as root.

On Server:
```
mkdir /srv/backup/borg/client
ls -ld /srv/backup/borg/client
drwx------ 3 root root 104 Dez 14 14:26 /srv/backup/borg/client/
```

On Client:
```
# borg init --encryption=none root@server:/srv/backup/borg/client
# borg create -v --stats root@server:/srv/backup/borg/client::today /var
```

**I get hundrets of lines like**:
```
...
/var/lib/lxcfs/cgroup/pids/system.slice/tmp.mount/tasks: [Errno 22] Invalid argument
/var/lib/lxcfs/cgroup/pids/system.slice/var.mount/cgroup.procs: [Errno 22] Invalid argument
/var/lib/lxcfs/cgroup/pids/system.slice/var.mount/tasks: [Errno 22] Invalid argument
/var/lib/lxcfs/cgroup/pids/user.slice/cgroup.procs: [Errno 22] Invalid argument
...
```

And at least the stats:
```
------------------------------------------------------------------------------
Archive name: today
Archive fingerprint: 199277b6a78b0cd1f8f550b1cf14cb72681c6ee80d6cd1b1bafee056b429afd4
Time (start): Wed, 2016-12-14 14:35:34
Time (end):   Wed, 2016-12-14 14:36:27
Duration: 53.53 seconds
Number of files: 22240
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.16 GB              1.16 GB              1.09 GB
All archives:                1.16 GB              1.16 GB              1.09 GB

                       Unique chunks         Total chunks
Chunk index:                   16251                22293
------------------------------------------------------------------------------
```

Now the questions:
Where do all these error lines come from?
Do they mean something or can they be safely skipped?
What does this mean to my backup?
Have I overlooked something?

Thanks for any help

**Comment by enkore** [comment]
Likely "lxcfs" doesn't support some metadata operation (perhaps xattrs or ACL).

I'm not 100 % sure what lxcfs is for, but a quick Google search suggests that it is like procfs for LXC, so there is probably no need to back it up.

**Comment by robaato** [comment]
To clarify quoting from lxcfs:
"it will provide an emulated /proc and /sys/fs/cgroup folder for the containers"
and it's usually mounted like: lxcfs on /var/lib/lxcfs type fuse.lxcfs  

Thus in my opinion it should not be backed up (i skip it in my scenarios).
