### ISSUE TITLE
--stats should imply -v

### ISSUE THREAD

**Issue by bj0** [borgbackup/borg#1958]
I was wondering why --stats didn't print anything in my backup log and I finally found the note in the docs that said
> While some options (like --stats or --list) will emit more informational messages, you have to use INFO (or lower) log level to make them show up in log output. Use -v or a logging configuration.

I think --stats should imply `-v (--info)` because if you're putting --stats you obviously want to see it.  This would also match behaviour of attic for those who are switching over.

**Comment by enkore** [comment]
Fixed in 1.1.x
