### ISSUE TITLE
borg terminates calling shell/process

### ISSUE THREAD

**Issue by devZer0** [borgbackup/borg#1960]
i have put some scripting around borg and come across some weirdness.

the script is like this:

while( hosts to be backed up )
 do stuff
  if repo desn`t exist 
    then 
      borg init ....
    else   
      borg create .....
 do other stuff
done

that worked good until i cleaned up cache dir a little bit too agressively, which resulted in:

[root@backupvm2 backup]# ./borg_backup_all.sh
<snipp>
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] Aborting.
Cache initialization aborted
<snipp>
[root@backupvm2 backup]#

bang - we`re back at the shell prompt at the first host to be backed up !?

apparently, not only borg exited but took the calling process with it.

that makes borg pretty unusable to be called from scripts

i`m using the self-contained borg-binary (which extracts into /tmp), version 1.0.8 

i don`t think this is normal behaviour of unix processes, something weird is going on here.

i`m using a similar loop/script with rsync for months and never came across such problem

for now, i worked around this problem with  BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes

**Comment by devZer0** [comment]
not sure if this is related, but it could...

http://unix.stackexchange.com/questions/310208/shell-script-exits-early-for-unclear-reasons/310210#310210

**Comment by devZer0** [comment]
oh, i`m getting a clue. apparently , as my while loop reads from stdin, this must be borg suddenly eating up my stdin on asking for user input.

i wonder if i should do </dev/null which every borg invocation to avoid such behaviour in general, or if borg could need som additional param "-n" like ssh has

see
http://stackoverflow.com/questions/8376166/execute-a-command-on-remote-hosts-via-ssh-from-inside-a-bash-script

**Comment by enkore** [comment]
You could read the file into a variable and then just close stdin (less typing), something like exec 0<&- should do it.

**Comment by devZer0** [comment]
ok, i turned my "ls -1 /dir|while read hostname;do..." into a "for $(ls -1 /dir);do"   loop, that completely resolves the issue as stdin is not used at all.

think we can close this.
