### ISSUE TITLE
borg create: read once, write to many repositories

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#1967]
Good practices suggest to do a backup on two (or more) different sites, one possibly a remote one. AFAIK currently one has to run two borg create, about doubling backup time (or alternate the backup, e.g. odd days on site1 and even days on site2). Either way the backup may also contains different data if the source files are modified between the create instances.
It would be nice if a single borg create could be able to update many different repositories.
Is this doable? Would it bring performance advantages, read (as well compression, etc) being done only once?

**Comment by ThomasWaldmann** [comment]
See the FAQ why duplicating backups is maybe not a good idea:

http://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

Also, borg is quite quick skipping unmodified files, so a backup does not need to encrypt/compress that much (exception: the first backup of a data set or if you have huge changes between backups).

**Comment by FabioPedretti** [comment]
Thanks for quick reply. I thought lot of time is spent in reading source files, but I also know this is improved in 1.1, reading them in inode order. Feel free to close if this idea is not so useful.
Thanks again.

**Comment by enkore** [comment]
#175 #895 #1697

**Comment by fti7** [comment]
#1697 duplicates this.
An Archive-Level Copy would be very useful.
I would like to create a similar Setup, but omiting that a Client needs to send it multiple times.

Idea:
-> A client does an "daily" Backup to a central Backup Repository.
-> Another Cronjob will "copy" a specific Archive (Like an weekly) to an Offsite Repository

The downsides are of course mentioned in the FAQ

**Comment by ThomasWaldmann** [comment]
Closing this for similar reasons as seen in #3867: we would have to do a lot of stuff per target repo, so there isn't much won by this.
