### ISSUE TITLE
add OS X install docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#197]
there is some stuff already in the travis CI files (as we do OS X testing on travis), but no pretty writeup in the docs yet. See travis.yml and .travis directory.

Some other automated installation for OS X is in the Vagrantfile.

**Comment by yagebu** [comment]
I can work on this. Are the pyinstaller binaries working well enough that we can recommend them as a first choice? I'll write up how to do a homebrew installation anyway but it might be nice to give undecided users a recommendation.

**Comment by ThomasWaldmann** [comment]
@yagebu i didn't get much feedback about the binaries for osx yet and did only a very short test myself, so use them carefully. I will soon start working on adapting the unit tests so they can alternatively run with the binary instead from source code.

Maybe tell in the docs that users shall test the binaries first, but carefully. They are much easier to install, so IF they work, users might be happier than struggling with the other way of installing it.

**Comment by yagebu** [comment]
Even when using the binary, an up-to-date OpenSSL version is required, is that correct?

**Comment by ThomasWaldmann** [comment]
No, the binary includes everything. Only a (g)libc and the kernel is used from the OS.

**Comment by yagebu** [comment]
Ah ok. Then I wouldn't be to happy to recommend them, since there is no clear update path. And we do bundle a security sensitive library...

**Comment by yagebu** [comment]
Oh I just tried to create a homebrew formula and it worked :)

Can you create the `borgbackup/homebrew-borgbackup` repository? Then I can file a PR against it with the homebrew formula and Mac OS X users can just run the following to install borg:

    brew tap borgbackup/borgbackup
    brew install borgbackup

**Comment by ThomasWaldmann** [comment]
The update path is to install the next release.

And it's relatively unlikely that there are critical bugs in the stuff be use from openssl (rather than in more complex code that we do not use), it is just basic AES and pbkdf2 code - that is hopefully covered by test vectors in their tests. But that's a rather fundamental thing that applies to all bundled / statically linked product.

**Comment by ThomasWaldmann** [comment]
Is creating such a (separate) repo the usual way it how homebrew support is implemented?
Is there some magic in place to search for that (as you do not refer to it in the 2 lines you posted)?

**Comment by yagebu** [comment]
The custom repo ist the usual way to support homebrew if it not an official formula.
No, there is no magic to place to search for it, unless we submit it to the homebrew project. Don't think we meet the criteria for that yet though: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md

But it's quite common to have these separate repositories with only a small number of very specific formulae (called 'taps' in homebrew language). For example https://github.com/neovim/homebrew-neovim

**Comment by yagebu** [comment]
So we would still have to tell the users these two lines, but then they would receive updates through their package manager and not have to manually update borg.

**Comment by ThomasWaldmann** [comment]
Is it also possible to put all the homebrew stuff into a directory, so that there could be one repo for all packaging stuff instead of one repo per packaging system / distribution?

**Comment by yagebu** [comment]
It is possible, but then you would have to give the full git url to the `brew tap` command...
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md

**Comment by ThomasWaldmann** [comment]
ok, so how about putting it into a borg-packages repo, /homebrew directory?

**Comment by yagebu** [comment]
Then the command would turn into:

    brew tap borgbackup/borgbackup https://github.com/borgbackup/borg-packages.git

And the directory would have to be named ``HomebrewFormula`` or just ``Formula``. Another disadvantage would be that it clones the whole repository, so if we had other packaging stuff in there, homebrew users would also pull that in.

Don't most other packaging systems have their own version control anyway? Isn't homebrew the odd one out in the sense that for homebrew it's common to just get your package (build file) from a github repo?

I would be willing to maintain a ``borgbackup/homebrew-borgbackup`` (or ``borgbackup/homebrew-borg``) repo, as it would make for a much nicer user experience IMHO.

**Comment by ThomasWaldmann** [comment]
fixed by PR #295 - thanks @yagebu!

maybe refer to the homebrew issue from a new ticket.
