### ISSUE TITLE
update sphinx on rtfd

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1972]
see #1485 discussion - we can just have a newer sphinx than the quite old one rtfd uses by default if we just install it via requirements.txt.

this might fix some issues of the older sphinx version and improve docs usability.

**Comment by enkore** [comment]
It seems you changed the RTD config to install from requirements/docs.txt in #2086, causing all docs builds since then to fail.

**Comment by ThomasWaldmann** [comment]
Yup, fixed.

**Comment by ThomasWaldmann** [comment]
keep in 1.0 even though to new policy because rtfd has global settings that need to work for all branches.

**Comment by enkore** [comment]
What's left to do here?

**Comment by ThomasWaldmann** [comment]
Well, the initial idea was that a new sphinx version fixes some issues we see (e.g. the bad search results).

But that did not work out, so yes, this can be closed (except if we would need any of the other bug fixes in sphinx).
