### ISSUE TITLE
Restrict matches by file type

### ISSUE THREAD

**Issue by RAOF** [borgbackup/borg#1974]
I've got a lot of (large) .o files in various build directories that I don't need backed up.
I'm also paranoid that excluding *.o will accidentally exclude something that I *want* backed up; people, including me, name files strange things.

This could be resolved by being able to restrict matches by file type (probably mime-type?). If a file matches *both* *.o and is of mime-type application/x-object that's definitely something I don't need to care about.

There seem to be plenty of tools available to sniff mimetype, and doing so *should* be cheap (the `mimetype` command seems to reliably take ~40ms to process a file, and borg could do better without the fork/exec/linker relocation necessary.

**Comment by ThomasWaldmann** [comment]
mimetype detection (by parsing file content like with libmagic) is unreliable and can be dangerous.

why not just exclude the build directories?

**Comment by RAOF** [comment]
I agree mimetype detection is unreliable (which is why I would want it 
as an *additional* filter; false negatives are cheap and safe). It 
*should* be safe enough; this does require some level of parsing 
untrusted input, but it's very limited.

Excluding the build directories is difficult for me: many of these 
build directories are for Debian packaging. They're created and 
destroyed frequently, I don't have direct control over their naming 
(it's determined by the Debian build tools), and their names change 
frequently.

**Comment by enkore** [comment]
These are probably under a common root? If so, you can do e.g. `--exclude /debian/build/root/*.o`

Issue seems resolvable with existing tools.
