### ISSUE TITLE
sFTP support like obnam ?

### ISSUE THREAD

**Issue by s-m-i-c-h-a** [borgbackup/borg#1976]
Hi,

just a question:
Are there some plans, that borg get "sftp" support as obnam have?

I will use a stupid NAS box as the borg repository. (SSH access is possible, but I can not install the borg software on that). I will than save the backups from clients via SSH to the NAS box. The only way at the moment is to use sshfs to mount the "repository" on the client and save the backup via borg in that sshfs.

In obnam, I can use instead the option to use "sftp" (like sftp://user@nsa:/backup) instead to do the sshfs mount staff.

Is some feature like this also planed in borg?

Many Thanks
Michael

**Comment by enkore** [comment]
It has been suggested before, but no one is working on it.

See #1070 or #1811 for details.
