### ISSUE TITLE
borg prune and daylight saving time

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#1980]
Hi, I am using borg prune with the --keep-* options.
I'd like every run removes all archives on a certain date.
However, likely to daylight saving time, some archives in the same day are pruned, while others are left.
Would be possible to consider this in prune?
A possibility would be to slightly alter daily (or longer) prune options, e.g. daily could consider n*24h + 4h, or something.
Or even better just calculate the timing explicitly considering daylight saving time changes, so that daily can be 23,24 or 25h based on the fact that the prune interval cross a daylight saving time date.
Not a serious issue, it just would make pruning behaviour a bit more consistent to what one should expect.
Thanks!

**Comment by enkore** [comment]
That's a really good point... even though the prune time calculation is made in local time, it *probably* doesn't work like you describe, and which I would see as the correct behaviour as well.

I'd say that if the behaviour shall change, it should be done in master, not in a point release (1.0-maint).

**Comment by ThomasWaldmann** [comment]
Nothing against computing correct time (in case it's wrong now), but we won't just consider n*24h + 4h or so - that would be even more problematic / confusing.

**Comment by FabioPedretti** [comment]
Hi, any plan to address this in 1.1?

**Comment by ThomasWaldmann** [comment]
@FabioPedretti we didn't work on it yet, but you could help by adding more details.

For example, the precise prune command you are using and the log output that shows the unexpected results.

**Comment by FabioPedretti** [comment]
Thanks for the reply.
I always run the prune at 0:00 and the creates just after that.

I run prune with:
`borg prune -v --stats --show-rc --list --keep-within=56d`

Here is a sample output of 1 december, in which older backups cross a daylight saving time (happened on 21 October):
```
Keeping archive: web-2016-11-30                       Wed, 2016-11-30 02:04:46
Keeping archive: STORAGE-2016-11-30                   Wed, 2016-11-30 01:38:35
Keeping archive: router-2016-11-30                    Wed, 2016-11-30 01:33:55
Keeping archive: proxy-2016-11-30                     Wed, 2016-11-30 01:31:24
Keeping archive: NAS-2016-11-30                       Wed, 2016-11-30 01:18:25
Keeping archive: LOTUS-2016-11-30                     Wed, 2016-11-30 00:40:55
Keeping archive: logger-2016-11-30                    Wed, 2016-11-30 00:38:32
Keeping archive: liste-2016-11-30                     Wed, 2016-11-30 00:36:03
Keeping archive: idp2-2016-11-30                      Wed, 2016-11-30 00:33:58
Keeping archive: idp1-2016-11-30                      Wed, 2016-11-30 00:31:57
---- 8X cut X8 ----
Keeping archive: db4-2016-10-07                       Fri, 2016-10-07 08:40:41
Keeping archive: web-2016-10-06                       Thu, 2016-10-06 01:57:13
Keeping archive: STORAGE-2016-10-06                   Thu, 2016-10-06 01:39:21
Keeping archive: router-2016-10-06                    Thu, 2016-10-06 01:34:50
Keeping archive: proxy-2016-10-06                     Thu, 2016-10-06 01:32:42
Keeping archive: NAS-VECCHIA-2016-10-06               Thu, 2016-10-06 01:07:54
Pruning archive: NAS-LOTUS-2016-10-06                 Thu, 2016-10-06 00:28:43
Pruning archive: logger-2016-10-06                    Thu, 2016-10-06 00:26:52
Pruning archive: liste-2016-10-06                     Thu, 2016-10-06 00:24:31
Pruning archive: gads-2016-10-06                      Thu, 2016-10-06 00:22:50
Pruning archive: dns2-2016-10-06                      Thu, 2016-10-06 00:21:11
Pruning archive: dns-2016-10-06                       Thu, 2016-10-06 00:19:32
Pruning archive: db5-2016-10-06                       Thu, 2016-10-06 00:16:05
Pruning archive: db4-2016-10-06                       Thu, 2016-10-06 00:12:16
Pruning archive: web-2016-10-05                       Wed, 2016-10-05 02:14:29
Pruning archive: STORAGE-2016-10-05                   Wed, 2016-10-05 01:26:47
Pruning archive: router-2016-10-05                    Wed, 2016-10-05 01:23:02
Pruning archive: proxy-2016-10-05                     Wed, 2016-10-05 01:21:08
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
```
As you can see I would have expected (given that I run prune before the create) that only and all backups on a certain date get pruned (e.g. ...-2016-10-06). However this is not the case, backups  on -2016-10-06 terminated after 1:00 are not pruned.
This doesn't happen when not crossing October daylight saving times.
Thanks for looking into this.

**Comment by ThomasWaldmann** [comment]
So, I assume your timezone is CEST (UTC+2) in the summer and CET (UTC+1) in the winter?
You start your prune run at 00:00 localtime?

BTW, I'ld guess an obvious workaround to that problem is to start prune/backup after 02:00 localtime.

**Comment by ThomasWaldmann** [comment]
Hmm, this might be rather a matter of definition of --prune-within than a bug or a timezone issue.

If you give `--prune-within=56d` what it does is compute 56 * 24 * 3600 and then keeps everything that is younger than that amount of seconds.

**Comment by ThomasWaldmann** [comment]
From the docs:
```
For example, “–keep-within 2d” means to keep all archives that were created within the past 48 hours.
```
Note that this does not say "from the last 2 calendar days", but "48h", so usually that spans 3 days.

**Comment by FabioPedretti** [comment]
> So, I assume your timezone is CEST (UTC+2) in the summer and CET (UTC+1) in the winter?

Correct, GMT+1, Italy.
> You start your prune run at 00:00 localtime?

Yes.
> BTW, I'ld guess an obvious workaround to that problem is to start prune/backup after 02:00 localtime or a while before 01:00 localtime so it is finished before 01:00 localtime.

0:00 is preferrable, since some backups last many hours and I want to avoid having them running in the morning working hours.

> Hmm, this might be rather a matter of definition of --prune-within than a bug or a timezone issue.
>
> If you give --prune-within=56d what it does is compute 56 * 24 * 3600 and then keeps everything that is younger than that amount of seconds.
>
> ...
> Note that this does not say "from the last 2 calendar days", but "48h", so usually that spans 3 days.

Yes, indeed, it would be nice if 56d implies 56 calendar days, this will avoid this issue. Is this feasible or implies other problem?

**Comment by ThomasWaldmann** [comment]
BTW, just as a hint from my practice:

I like to start backups so that their reference datetime is on same day as the work that they saved.

So if users have a usual workday, one can usually start backups between 21:00..23:00, so the backups start and finish on the same calendar day as the work they backup.

So, if later someone tells "I need file X as it was on day Y", you can just take Y and search the backup with the respectivey name (same reference date). No need to add 1 day as when you start your backups after 00:00.

**Comment by ThomasWaldmann** [comment]
Well, of course it would be possible to compute it in calendar days (hours, ...), but it would be way more complicated.

--keep-X computes with calendar units, maybe you can just use that?

**Comment by ThomasWaldmann** [comment]
Guess we rather keep it simple. Calendar calculations tend to get complicated or wrong...

**Comment by FabioPedretti** [comment]
> I like to start backups so that their reference datetime is on same day as the work that they saved.

It may perfectly sense. However if I will start them before 0:00 (say at 20:00), some of them (I did many every day) may begin after 0:00 and it will be confusing that the same sets have a different day.
(the day used on tag can be set to whatever I need, using the previous day even when running at 0:00 or keeping the same day even when starting the set at 20:00 even if some get past 0:00)

> Well, of course it would be possible to compute it in calendar days (hours, ...), but it would be way more complicated.
>
>--keep-X computes with calendar units, maybe you can just use that?

Do you mean --keep-last X (this is 1.1 only anyway)? This would work indeed.

I think however that it is logical to have 56d ago the same hour of now (no matter different DST) and would best to have this, other people may also get confused in the future.
But OK, if this is too much trouble and prone to other errors it is not a big issue.

Thanks for your time looking at this and working on this amazing tool!

**Comment by enkore** [comment]
If I understand correctly then solving this would mean that the calculation needs to take DST transitions during the considered time frame into account, correct?

This would mean adding a TZ database (e.g. pytz) and doing quite a bit of logic with the _transition_info tuples therein. Sounds... involved.

Q: This issue would be (I think) solved by performing the calculation in UTC space (which does not have DST transitions). Would doing the calculation in UTC space regress in other ways?

**Comment by FabioPedretti** [comment]
Another way to do this is to just count days. E.g. 56d is not 56 * 24 * 3600, but 56 previous calendar days at the same current time. May this work?

**Comment by enkore** [comment]
Isn't that what the code is already doing?

https://github.com/borgbackup/borg/blob/1.0.10/borg/helpers.py#L200
https://github.com/borgbackup/borg/blob/1.0.10/borg/archiver.py#L701

I.e. for --keep-daily N the last N archives are kept where stftime(%Y-%m-%d) differs.

**Comment by ThomasWaldmann** [comment]
the difference between --keep-daily N and --keep-within Nd (besides minor differences concerning what is considered a day) might be that the latter keeps ALL backups within the interval and the first one keeps the LAST backup of each day (which only makes sense if you used --prefix correctly and is a recipe for backup data loss if you don't).
