### ISSUE TITLE
add non-encrypted repo check for --tam repo upgrades (or at least better docs)

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#1981]
Hi, while reading the release notes for the new 1.0.9 version, I saw I need to run a command similar to --tam upgrade or sth like that. It upgrades the repo to make it more secure.

The problem is the docs don't say specifically that the repo needs to have some encryption. For non-encrypted repo-s the upgrade command fails with some python error that looks ugly.

Two simple things could remedy this situation:
1. Add one sentence to docs/release notes that specifies we need to upgrade ONLY repos with encryption.
2. Add a simple if-check for the --tam option that would print "this repo is not encrypted, you don't need to run this upgrade at all. Bye bye..."

Agree?

**Comment by DrupaListo-com** [comment]
the python error I saw on upgrade left me thinking I might have screwed my repo somehow, while I think I didn't ...

**Comment by enkore** [comment]
Yes, it errors out in an ugly way but no harm done to repo/key.

**Comment by enkore** [comment]
Fixed by #1994
