### ISSUE TITLE
borg delete too slow?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1982]
I backed up a machine that did not see backups for a while, so quite some new (and some unwanted new) data ended up in the backup. I later removed some of the unwanted data, backed up again and then deleted the first of these archives.

borg delete was sitting at 100% cpu for ~45 cpu minutes and ~270MB memory (as displayed by "top"), no repo activity most of the time. then memory jumped up a bit to ~400-600MB, repo activity started, cpu dropped to almost 0. finished a few minutes later, freed ~12GB (repo disk usage).

borg 1.0.9 core i5-4200u 8GB RAM.

**Comment by enkore** [comment]
cache sync?

**Comment by ThomasWaldmann** [comment]
No, cache was in sync, that happened when I created the first backup that day. The above mentioned times are for deleting that archive.

**Comment by ThomasWaldmann** [comment]
maybe it was a degraded hashtable, filled up completely with a lot of tombstones. this issue was fixed recently via MAX_EFF_LOAD.

**Comment by ThomasWaldmann** [comment]
I'll close this for now, we can reopen / open a new ticket if it happens again.
