### ISSUE TITLE
write adaptor for google sparsehash

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#1984]
It would be nice to have a alternative "proven" hashtable implementation, maybe google sparsehash.

We could have a wrapper in C that implements the same api as hashindex and uses C++ internally.

So, anyone good with C, C++ and templates?

**Comment by julianbrost** [comment]
I'm wondering if you have any special requirements for that hashtable? If C++ is an option, why not go for `std::unordered_map` (C++11)?

**Comment by ThomasWaldmann** [comment]
Guess we also have covered this in #1985.
