### ISSUE TITLE
borg create ignore some folders and files

### ISSUE THREAD

**Issue by maboxx** [borgbackup/borg#1987]
Hello,
borg backup ignore some files and folders when I do borg create ..... 
I installed the latest version and do the following command:
`borg create --compression lz4  --one-file-system -v --stats --progress /run/media/mabo/USB3TB/borgbackups::'{hostname}-{now:%Y-%m-%d-%H%M%S}' /home /etc /usr/local /var /root`

I checked the backup now with borg list ... and also with borg extract ....
In a first view in /var/ I missing some folders and files. For example the path /vart/lib/libvirt/. In this path I missed the folder "images" with some .iso and .qcow2 Files.
Also directly under /var/ I missing some files and folders.

What am I doing wrong here?

EDIT:
Ok, Maybe I found the problem. I use opensuse with btrfs and there are some subvolumes in /var. It seems that all subvolumes are missing in the backup? Could this be the problem? What can I do that subvolumes also included in the backup?

Sorry but I am a newbie.....

**Comment by enkore** [comment]
Subvolumes in btrfs show up as a separate mount, so --one-file-system excludes them. You can add these paths explicitly to have them included.

**Comment by maboxx** [comment]
Thank you for the information!
