### ISSUE TITLE
please print exact original archive size

### ISSUE THREAD

**Issue by tpo** [borgbackup/borg#1990]
### Feature request
Please let `borg info` print the **exact size** of the original.

### Rationale
We do backup and restore VM images. They are accessible via a third party API over HTTPS. When restoring an image we upload it via a HTTP POST to the API.

Optimally we want to do `borg extract ... | curl -X POST --upload-file - ...`, which will:
* save us storing a an intermediary copy of the VM image
* save us maintaing a huge partition for saving intermediary copies of images

The API implementation **requires** to transmit the size of the file in the HTTP headers (i.e. `Content-Length: 1234567890`). That means, in order to do `borg extract | curl -X POST --header 'Content-Length: 1234567890'`, we need to know the exact size of the data to come via `borg extract` which currently `borg` does not provide.

### Proposed patch and discussion

A trivial patch would be to add at the end of the `do_info` function the following line:

        print('Original size: %d' % stats.osize)

That is a bit ugly UI-wise however I can't really think a better way usage/UI wise.

Also this patch is lightly related to #1812.
?

Thanks,
*t

**Comment by enkore** [comment]
`borg list --list-format '{size}' repo::archive some/file`

**Comment by tpo** [comment]
Ah, you are my hero @enkore ! Thank you!
