### ISSUE TITLE
borg check does not exit with failure status when archive is absent

### ISSUE THREAD

**Issue by dluijkx** [borgbackup/borg#1997]
when running a command such as:
borg check -v repo::archive1           (archive1 is not actually part of the repo)
...if archive1 does not exist in the repo, the command should report an error ( that archive "archive1" does not exist ), then exit with a non-zero status.
Instead, it says the archive consistency check is complete(see below), and exits with a 0 status.

Starting repository check
Completed repository check, no problems found.
Starting archive consistency check...
Orphaned objects check skipped (needs all archives checked).
Archive consistency check complete, no problems found.
[root@chlxfs1 trc]# echo $?
0

**Comment by enkore** [comment]
Fixed by #2000
