### ISSUE TITLE
exclude-if-present could check with .exists() instead of .isfile()

### ISSUE THREAD

**Issue by costela** [borgbackup/borg#1999]
Hi,

Is there a reason why `--exclude-if-present` explicitly checks if its argument is a file? I couldn't find any rationale looking into #395, but maybe I'm missing something.
If there isn't one, then maybe `.exists(...)` would be a more generic check? It would allow doing things like `--exclude-if-present .git`.

Cheers

**Comment by ThomasWaldmann** [comment]
Sounds like basically a good idea, but would have these consequences:
- it would need more general processing, currently it backups the "tag" as a file if "keep tags" mode is active
- for "keep tags" mode it would be somehow strange to keep all the `.git/*` but not the workdir (ok if checkout clean, but not if unclean). it would be also strange to only keep an empty `.git`.

**Comment by costela** [comment]
I'm not sure I understand what you mean.
- if `keep_tag_files` is set, borg currently calls `_process` recursively on the tags, which then get treated appropriately as a file or directory (see [here](https://github.com/borgbackup/borg/blob/902c4230868ebbafc675e1cc3e4e891c45c0aead/src/borg/archiver.py#L415)). Or did I misunderstand your objection?
- as for the "strangeness": I don't think it would be that weird, especially in the case of git, since the .git folder get's backed-up recursively as a folder (as explained above) and not left empty. I.e.: doing a backup with `--keep-tag-files` and `--exclude-if-present .git` would be basically the same as having a backup of the bare git repo, which might make sense, since it might mean a significant size reduction, depending on the repository (in my tests with a small 48MB repo I got a 32MB backup with the options above and 46MB without).

**Comment by ThomasWaldmann** [comment]
Oh, right, it is _process already for the tags, not process_dir - so that's not a problem.

But still it feels like a problematic hack. For .git workdirs this would exclude all **uncommitted/unadded** changes (which are not likely to exist anywhere else - this is different than for added/committed/pushed changes which might also exist on github or whereever).

OTOH, UNIX tools policy is not like standing in the way and making things impossible that the admin wants (and that might make sense in some scenarios), so we could implement that and the admin can feel free to use that for good or shoot himself/his users in the foot.

**Comment by ThomasWaldmann** [comment]
Like this for implementing any filesystem object (files, dirs, ...) as "tag file".

**Comment by ThomasWaldmann** [comment]
Like this for keeping as is: only files can be tag files.

**Comment by costela** [comment]
Good point about the uncommitted changes, but IMHO your "unix philosophy" counter-point seems slightly more important in this case! ;)

**Comment by costela** [comment]
For completeness' sake, we could also add a `--exclude-if-file` to keep the current behavior accessible (or analogously add a `--exclude-if-dir-present` to go the opposite direction), but this feels like over-engineering for relatively little gain.

**Comment by dragetd** [comment]
I would not increase the number of command line options for such a trivial function. Personally I have the same reasoning as Thomas: I think it is an odd feature I would never use, but I also see no reason why it should not be possible.
