### ISSUE TITLE
Vagrantfile requires plugin vagrant-reload

### ISSUE THREAD

**Issue by htgoebel** [borgbackup/borg#2003]
Please state in the documentation, that running `vagrant up windows10` requires the plugin `vagrant-reload`. Otherwise you'll get errors like this:
```
$ vagrant up windows10
Bringing machine 'windows10' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.
```

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/1787 we have to check what of the comments there need to be added to docs. It is also remarkable that first "vagrant up" won't work, but it needs addtl. steps.

**Comment by enkore** [comment]
524e0b532

Though not terribly useful since the box is broken even with the plugin installed.
