### ISSUE TITLE
Know what changed for one archive

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2007]
Sorry if this has been asked before, but I've been looking on google and I've not seen anything about this. 

I'd like to know whether it is possible to know what files changed (or are exclusive) for a particular archieve. That is, when "borg info" says that this archive has a deduplicated size of 30.16MB, I'd love to know which files are associated to that size. The reason is that I've performed two consecutive backups over the same set of folders (20GB in total) and that's the info I get for the second one (and very similar for the first one).

Knowing which files make the difference would be useful for me.

**Comment by enkore** [comment]
1.1.x branch:

- borg diff archive1 archive2 gives list of changed files
- borg list archive --format '{path} {num_unique}\n' gives list of files with how many unique chunks they have (perhaps we want to add unique size also?)

**Comment by ThomasWaldmann** [comment]
Just as an additional note: the "deduplicated size" of the archive also includes the (also deduplicated) metadata stream of all archived filesystem objects.

**Comment by ThomasWaldmann** [comment]
Duplicate to #177 (and also solved in 1.1beta / master branch).

**Comment by alejandro-perez** [comment]
Oh, thanks! I'm using 1.0.9 (Arch Linux) and didn't read anything about borg diff on the documentation. That's a great feature. Looking forward to reach Arch Linux.
