### ISSUE TITLE
Repository completely deleted, can't re-init

### ISSUE THREAD

**Issue by yb66** [borgbackup/borg#2009]
Hi,

A repository was accidentally rm'd, so the directory it was in is completely clean. I don't need the old backups, what I do need is to continue backing up asap. Tried:

```
$ borg init path/to/dir
Repository path/to/dir already exists.
```

```
$ borg delete path/to/dir
path/to/dir is not a valid repository. Check repo config.
```

I've read the docs but don't see anything that tells me where the information that borg is referencing now is being kept. Does anyone know how I clear it / find it / edit it?

Regards,
iain

**Comment by enkore** [comment]
If the directory `path/to/dir` exists and is not completely empty (including hidden files) then Borg will refuse to init a new repository there. Make sure that `path/to/dir` is empty or delete `dir` itself.

**Comment by yb66** [comment]
Thanks, I was able to init a new repo but have run into other errors which may require another ticket, we'll see. Still, I'd like to know where Borg stores its information? It's obviously not all in the repo as the repo was completely deleted.

I'm on OSX 10.9, if that's of help.

Regards,
iain

**Comment by enkore** [comment]
The two messages you saw only depend on the files in/at the repository path.

Borg also does store some extra data in ~/.cache/borg and ~/.config/borg/{keys,security}

**Comment by yb66** [comment]
I see. I'll do some digging/testing before opening a new ticket. Thanks for your time.

iain
