### ISSUE TITLE
read backup data from stdin

### ISSUE THREAD

**Issue by avimar** [borgbackup/borg#2013]
Hi. Borg seems awesome. I was using rdiff-backup and rdiff-snapshot (fortunately not needed backups often) and seems so much more intuitive to recover.

I'm wondering if I can backup myslq _directly_ into borg without hitting the disk twice.

Percona has a stream option -- but it's in tar format (for the directory of files) and also I couldn't figure out why it still wants a file path.... 
https://www.percona.com/doc/percona-xtrabackup/2.4/innobackupex/streaming_backups_innobackupex.html

Alternatively, is there a "delete-on-backup" option? (I didn't notice one) -- like rsync's `--remove-source-files`

I would use that to "suck backups" into borg's backup.

Thanks!

**Comment by enkore** [comment]
Something along the lines of `rdbms_dump_tool | borg create repo::archive -`

**Comment by ThomasWaldmann** [comment]
The archive file name created is `stdin` iirc.

**Comment by enkore** [comment]
TODO: Document "-" for "PATHS" and the file name in the archive ("stdin")

**Comment by pka** [comment]
We're successfully using borg for cloud image backups via stdin:
`curl --silent --location --user $APIUSER:$APIPASS https://provider.com/api/xxxxxxx/download/ | borg create --compression zlib,6 -v --stats ssh://borg@example.org/backup::my-snapshot-1234 -`

**Comment by gerroon** [comment]
I have been trying to find an answer to this. Is it possible to backup folders using stdin "without" making a huge tar file then piping to Borg?

**Comment by ThomasWaldmann** [comment]
@gerroon stdin is just a single, unstructured stream of bytes, so how should it work backing up more than a single file via it without using something like tar (or another thing creating some data structure that can later be extracted again to multiple files/dirs)?

**Comment by gerroon** [comment]
Well, I was thinking of sending files individually? But I am not sure how I can structure it.

**Comment by davidbartonau** [comment]
@gerroon did you end up solving this problem?  I am facing the same problem, and it seems like any stream based backup tool will have the same issue.

One possibility would be a command that takes a list of commands and runs them sequentially and writes them to a tar file.
```
commandsToTar '{ "db1": [ "pg_dump", "db1" ], "db2": [ "pg_dump", "db1" ] }' | borg
```
The result would be a tar file with 2 members.

**Comment by ThomasWaldmann** [comment]
From `borg create` docs:
```
--stdin-name NAME | use NAME in archive for stdin data (default: “stdin”)
```

That way, you can do:
```
sql_dumper db1 | borg create --stdin-name db1 -
sql_dumper db2 | borg create --stdin-name db2 -
```

**Comment by davidbartonau** [comment]
Thanks @ThomasWaldmann .  Doesn't that create two separate archives?  Is there much of a file overhead per backup?  Am I overthinking this ;-)

**Comment by ThomasWaldmann** [comment]
It does, but so what? :)

You have 2 databases, so why not have 2 archives?

Of course, for practical purposes, you'ld likely add a timestamp to the archive name.
