### ISSUE TITLE
use vagrant for cygwin testing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#202]
if somebody wants to help with that, that would be very much appreciated!

A Vagrantfile that supports all sorts of (unixoid) OSes is in the toplevel directory of the project.

modernIE offers Windows 10 vagrant VMs.

The goal of the bounty is to have an automated provisioning of a standard windows VM with cygwin, python 3.4 and virtualenv working (same as for the other vagrant machines). So that one can ssh to the machine and run tox.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/26658967-use-vagrant-for-windows-cygwin-testing)

**Comment by ThomasWaldmann** [comment]
Idea: once we have this, it could be also used for automated builds on windows. This is not part of the bounty.

**Comment by billyc** [comment]
I think I've got this mostly working locally with a virtualbox VM. Is modernIE your preference for the final cloud-based solution?

**Comment by ThomasWaldmann** [comment]
I didn't compare VM options out there. The good thing about modern.ie VMs is that they are legal and provided for free by microsoft. Not sure about what the other options are.

**Comment by billyc** [comment]
Cool, free and legal seem like a good combination =)

I'm on it.

**Comment by PlasmaPower** [comment]
Have you considered using Appveyor instead? I've seen it used for similar projects.

**Comment by PlasmaPower** [comment]
Looks like there's an issue for that: #167.

**Comment by PlasmaPower** [comment]
Is this issue still relevant now that we have AppVeyor setup?

**Comment by PlasmaPower** [comment]
Also, does this issue include box creation and setup? Does it need to be automated, is a document explaining it okay, or should it just be left up to the end "user".

**Comment by enkore** [comment]
> Is this issue still relevant now that we have AppVeyor setup?

I would say it is much less relevant than before, but it would still make it easier to test on cygwin in the meantime 'till we have Windows releases.

**Comment by ThomasWaldmann** [comment]
Fixed by #1787. Thanks! Claim the bounty.
