### ISSUE TITLE
API versions number-space overlap issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2023]
Up to now, we just used 1..N in 1.0-maint and master (soon 1.1) branch and incremented the version when we did changes needing a recompile of the .pyx stuff / added new functionality.

Always at 1.0 -> master merge time, I noticed that both branches are overlapping and therefore that the increment is not really reliable when switching from one branch to the other.

Thus, I suggest doing it like this:

1.0-maint: use versions starting from 01_00_00
master (1.1): use versions starting from 01_01_00

**Comment by enkore** [comment]
Since `_` syntax is new in 3.6 we could also just make it a string, since we do an exact comparison anyway.

**Comment by ThomasWaldmann** [comment]
I did not really intend to use _ in the source, just used them in the ticket to be more clear.
But good idea, I'll use strings to make it more clear in the source alo.
