### ISSUE TITLE
Structured JSON logging

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2024]
Emit log messages and progress outputs as JSON lines.

This is pretty straightforward in a basic form, but can be enhanced in some ways (eg. provide formatting data as well [1]). We should spec a basic format that we'll adhere to, but leave exact details (eg. messages) open.

A basic implementation can be seen there: https://github.com/enkore/borg/tree/f/logjson

[1]

- Provide formatting data (`log.error("Fu: %s", blar)` -> formatting data = `(blar,) {}`)
- When handling `Error`s, provide the class name (eg. `LockTimeout`, `PathNotAllowed`)
- Provide fixed message-IDs in addition to the more frequently changed log messages themselves (eg. `io-error` when skipping a file due to BackupOSError)

**Comment by ThomasWaldmann** [comment]
there is also structlog, but that would be an addtl. dependency.

**Comment by RonnyPfannschmidt** [comment]
structlog is a much different beast, the json stuff in @enkore 's branch looks nice at first glance
