### ISSUE TITLE
crc32 issues on openbsd

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2043]
```
==> openbsd64:     cc -pthread -fno-strict-aliasing -DNDEBUG -O2 -pipe -fPIC -O2 -pipe -fPIC -I/usr/local/include/python3.4m -c src/borg/crc32.c -o build/temp.openbsd-6.0-amd64-3.4/src/borg/crc32.o
==> openbsd64:     In file included from src/borg/_crc32/crc32.c:66,
==> openbsd64:                      from src/borg/crc32.c:433:
==> openbsd64:     src/borg/_crc32/clmul.c:36:23: error: smmintrin.h: No such file or directory
==> openbsd64:     src/borg/_crc32/clmul.c:37:23: error: wmmintrin.h: No such file or directory
==> openbsd64:     In file included from src/borg/_crc32/crc32.c:66,
==> openbsd64:                      from src/borg/crc32.c:433:
==> openbsd64:     src/borg/_crc32/clmul.c:87: error: expected ')' before '*' token
==> openbsd64:     src/borg/_crc32/clmul.c:113: error: expected ')' before '*' token
==> openbsd64:     src/borg/_crc32/clmul.c:147: error: expected ')' before '*' token
==> openbsd64:     src/borg/_crc32/clmul.c:187: error: expected ')' before '*' token
==> openbsd64:     src/borg/_crc32/clmul.c:254: error: expected declaration specifiers or '...' before '__m128i'
==> openbsd64:     src/borg/_crc32/clmul.c:254: error: expected declaration specifiers or '...' before '__m128i'
...
```

**Comment by enkore** [comment]
Some Googling around shows that for some reason openbsd does not ship intrinsics.

GCC supposedly has a `__OpenBSD__` macro.

**Comment by enkore** [comment]
> Platform: **NetBSD netbsd7-1**.enkore.de 7.0.1 NetBSD 7.0.1 (GENERIC.201605221355Z) amd64 x86_64
> Borg: 1.1.0.dev234+ngabfcf99.d20170114  Python: CPython 3.5.1
> PID: 433  CWD: /home/jenkins/jenkins/workspace/borg-netbsd
> sys.argv: ['/home/jenkins/jenkins/workspace/borg-netbsd/_venv/bin/borg', 'debug', 'info']
> SSH_ORIGINAL_COMMAND: None
> 
> CRC implementation: crc32_clmul
> Process ID: ('netbsd7-1.enkore.de@8796757166562', 433, 0)

(GCC)

> Platform: **SunOS solaris11-1**.enkore.de 5.11 11.3 i86pc i386
> Borg: 1.1.0.dev234+ngabfcf99.d20170114  Python: CPython 3.5.1
> PID: 18417  CWD: /export/home/jenkins/workspace/borg-solaris
> sys.argv: ['/export/home/jenkins/workspace/borg-solaris/_venv/bin/borg', 'debug', 'info']
> SSH_ORIGINAL_COMMAND: None
> 
> CRC implementation: crc32_slice_by_8
> Process ID: ('solaris11-1.enkore.de@192663443185259', 18417, 0)

(SunCC/Solaris Studio isn't GCC)

> Platform: **FreeBSD freebsd10-1**.enkore.de 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC amd64 amd64
> Borg: 1.1.0.dev234+ngabfcf99.d20170114  Python: CPython 3.5.1
> PID: 29749  CWD: /usr/home/jenkins/jenkins/workspace/borg-freebsd
> sys.argv: ['/usr/home/jenkins/jenkins/workspace/borg-freebsd/_venv/bin/borg', 'debug', 'info']
> SSH_ORIGINAL_COMMAND: None
> 
> CRC implementation: crc32_slice_by_8
> Process ID: ('freebsd10-1.enkore.de@8796747908966', 29749, 0)

(cc = clang)

> Platform: **OpenBSD openbsd5-1**.enkore.de 5.9 GENERIC.MP#1888 amd64 amd64
> Borg: 1.1.0.dev234+ngabfcf99.d20170114  Python: CPython 3.5.1
> PID: 4323  CWD: /home/jenkins/jenkins/workspace/borg-openbsd
> sys.argv: ['/home/jenkins/jenkins/workspace/borg-openbsd/_venv/bin/borg', 'debug', 'info']
> SSH_ORIGINAL_COMMAND: None
> 
> CRC implementation: crc32_slice_by_8
> Process ID: ('openbsd5-1.enkore.de@8796759211687', 4323, 0)

(cc = GCC, but with no Intel intrinsics - perhaps that's part of the libc/system headers, not GCC itself necessarily)


> Platform: **SunOS openindiana**-1.enkore.de 5.11 illumos-f83b46b i86pc i386
> Borg: 1.1.0.dev234+ngabfcf99.d20170114  Python: CPython 3.4.3
> PID: 11870  CWD: /home/jenkins/jenkins/workspace/borg-openindiana
> sys.argv: ['/home/jenkins/jenkins/workspace/borg-openindiana/_venv/bin/borg', 'debug', 'info']
> SSH_ORIGINAL_COMMAND: None
> 
> CRC implementation: crc32_slice_by_8
> Process ID: ('openindiana-1.enkore.de@149534124556718', 11870, 0)

Apparently same cc as OpenBSD:

> $ cc -v 
> Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd5.9/4.2.1/specs
> Target: amd64-unknown-openbsd5.9
> Configured with: OpenBSD/amd64 system compiler
> Thread model: posix
> gcc version 4.2.1 20070719

**Comment by enkore** [comment]
Solaris, SunCC: On Solaris binaries are tagged with their ISA extensions, so if you have a binary that has some SSE4 instructions in it, then SunCC will add that to the binary header. If the current CPU does not support SSE4, then you can't execute the program. (I think this is a reliability feature to avoid issues with runtime detection and so on).

So you need to enable it (`-xarch=aes`) and patch it some (obviously this won't be committed to master):

```
From a3df7fb5899c88423d3eaa3d55bb6fdd2cc198fb Mon Sep 17 00:00:00 2001
From: jenkins <jenkins@solaris11-1.enkore.de>
Date: Sat, 14 Jan 2017 17:38:42 +0100
Subject: [PATCH] Add Solaris Studio support (broken)

In Solaris binaries are tagged with their ISA extensions,
so having runtime detection of code paths is generally not possible,
with SunCC.
---
 src/borg/_crc32/clmul.c |   11 +++++++++--
 src/borg/_crc32/crc32.c |    4 ++--
 2 files changed, 11 insertions(+), 4 deletions(-)

diff --git a/src/borg/_crc32/clmul.c b/src/borg/_crc32/clmul.c
index 4b84b03..5cc509c 100644
--- a/src/borg/_crc32/clmul.c
+++ b/src/borg/_crc32/clmul.c
@@ -39,12 +39,19 @@
 #ifdef _MSC_VER
 #include <intrin.h>
 #else
-/*
+#ifdef __sun    
+#define __cpuid(level, a, b, c, d)                      \
+  __asm__ ("cpuid\n\t"                                  \
+           : "=a" (a), "=b" (b), "=c" (c), "=d" (d)     \
+           : "0" (level))
+#else
+/* 
  * Newer versions of GCC and clang come with cpuid.h
  * (ftr GCC 4.7 in Debian Wheezy has this)
  */
 #include <cpuid.h>
 #endif
+#endif
 
 static void
 cpuid(int info, unsigned* eax, unsigned* ebx, unsigned* ecx, unsigned* edx)
@@ -57,7 +64,7 @@ cpuid(int info, unsigned* eax, unsigned* ebx, unsigned* ecx, unsigned* edx)
     *ecx = registers[2];
     *edx = registers[3];
 #else
-    /* GCC, clang */
+    /* GCC, clang, Solaris Studio */
     unsigned int _eax;
     unsigned int _ebx;
     unsigned int _ecx;
diff --git a/src/borg/_crc32/crc32.c b/src/borg/_crc32/crc32.c
index 2395925..664aaf5 100644
--- a/src/borg/_crc32/crc32.c
+++ b/src/borg/_crc32/crc32.c
@@ -2,7 +2,7 @@
 /* always compile slice by 8 as a runtime fallback */
 #include "slice_by_8.c"
 
-#ifdef __GNUC__
+#if defined(__GNUC__) || defined(__sun)
 /*
  * clang also has or had GCC bug #56298 explained below, but doesn't support
  * target attributes or the options stack. So we disable this faster code path for clang.
@@ -13,7 +13,7 @@
  * on OpenBSD.
  */
 #ifndef __OpenBSD__
-#if __x86_64__
+#if __x86_64__ ||  __amd64
 /*
  * Because we don't want a configure script we need compiler-dependent pre-defined macros for detecting this,
  * also some compiler-dependent stuff to invoke SSE modes and align things.
-- 
1.7.9.2
```
