### ISSUE TITLE
vagrant machines run out of memory

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2053]
likely since python-xdist (x8). at least the xenial64 machine regularly kills python workers.

lower to x4 and slightly increase memory, like ~ +200MiB?

**Comment by enkore** [comment]
Why not something like

```
commands = py.test -n {env:XDISTN:auto} ...
```

That way the default would be "auto" (2 on Travis / probably one in the VMs), but can be changed by the env-var XDISTN to a higher value if one wants to.

**Comment by ThomasWaldmann** [comment]
OK.
