### ISSUE TITLE
binaries in pypi package

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2066]
Just noticed that when there are binaries (*.so) below src/borg, they will end up in the pypi package when running `python setup.py sdist`.

Is that new? Are we expected to exclude them in MANIFEST.in?

**Comment by enkore** [comment]
(from #2052)

https://docs.python.org/3/distutils/commandref.html

> graft dir 	include all files under dir

So I guess we'd have to explicitly exclude these again, eg.

```
recursive-exclude src *.so
recursive-exclude src *.dll
```

**Comment by ThomasWaldmann** [comment]
Note: did a quick, minimal fix for 1.1.0b3, more should be done in 1.0-maint and merged into master from there.

**Comment by ThomasWaldmann** [comment]
fixed by #2089.
