### ISSUE TITLE
unnecessary read of unmodified files

### ISSUE THREAD

**Issue by kcwu** [borgbackup/borg#2071]
How to reproduce
```
mkdir data
dd if=/dev/zero of=data/datafile bs=1024k count=5000

borg init -e none repo
time borg create repo::test1 data
time borg create repo::test2 data
```
The second `borg create` is expected fast because no files are changed. But it actually took about 1 minute.

`iostat` also confirmed `borg` did read the whole file
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          45.92    0.00    6.12   47.96    0.00    0.00

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda             634.69     80991.84         0.00      79372          0
```

Could be reproduced with borg 1.0.7 on Ubuntu, 1.0.9 on FreeBSD, and github master on Ubuntu.

**Comment by enkore** [comment]
http://borgbackup.readthedocs.io/en/stable/faq.html#i-am-seeing-a-added-status-for-a-unchanged-file

**Comment by kcwu** [comment]
Oh, I see. Confirmed. Thanks.
