### ISSUE TITLE
Add ability to mount backed up RAW devices

### ISSUE THREAD

**Issue by e-alfred** [borgbackup/borg#2074]
Hello,

I backed up a RAW device using Borg Backup, but now I would like mount the backup to access files on the filesystem level. The RAW files are LVM logical volumes with a partition on them that is used inside a KVM virtual machine. The system is running Debian 8 Jessie with the latest Borg binary version 1.0.9.

I tried the following to access the RAW file:

1. Mount the Borg Backup repository using `borg mount /backupdir /mnt`. The images are shown as directories with a "stdin" file inside.
2. Mount the image as a loop using `losetup /dev/loop0 stdin`
3. Find the partitions inside the loop-mounted image using `kpartx -av /dev/loop0`
4. Mount the partitions found and mapped under `/dev/mapper/loop1p0` using mount.

At this point borg backup takes all CPU and kpartx crashes with a segfault.

The procedure above works with a RAW file directly obtained using dd outside Borg Backup. Is it possible to do this with a Borg Backup as well without extracting the whole image which is terabytes in size?

**Comment by ThomasWaldmann** [comment]
@e-alfred can you try what happens with a smaller image (not terabytes, but few gigabytes)?

**Comment by enkore** [comment]
Afaik some people already did similar things (mounting snapshotted file system through loop device through borg mount). Maybe try it without kpartx; parted or fdisk can also print the partition table.

**Comment by e-alfred** [comment]
I tried it with the offset using mount, but the only thing I get is 

> EXT4-fs (loop0): INFO: recovery required on readonly filesystem
> EXT4-fs (loop0): write access unavailable, cannot proceed

Could the high CPU load come from the compression level used? I used `zlib,7` for borg. Would lz4 be a better choice?

**Comment by enkore** [comment]
You'll need to use mount options like ro,noload to mount unclean snapshots a journaling FS.

**Comment by e-alfred** [comment]
Thanks, I used `mount -t ext4 -o ro,noload,loop,offset=32256 stdin /media/test` and it works now. But borg still uses a lot of CPU and moving in the directories of the mounted backup lags quite a bit.  Even a simple `ls -lah` takes some time to complete and the borg mounting process takes 100% CPU.

**Comment by enkore** [comment]
Borg tends to be CPU heavy due to the cryptographic verification that it does and CRCing in the segments (though that's much better in 1.1 now). In this case there is also a lot of indirection, which will already degrade performance:

```
ext4 -> jbd2 -> blockdev -> loopdev -> vfs -> fuse | userspace | -> borg -> | kernel | -> vfs -> ext4/whatever the repo is on
  ^                                                                                                         |
  +---< jbd2 <- blockdev <- loopdev <- vfs <- fuse | userspace | <- borg <- | kernel | <- vfs <-------------+
```

For casual access and direct access (no indirection through loop + ro-mounted FS inside loop) borg mount performance is usually satisfactory (60-70 MB/s) -- for full restores better use extract.

**Comment by devrando** [comment]
I had success doing this with qemu-nbd(over WAN link 50/10mbit):


```
#load kernel module
modprobe nbd max_part=8
#connect in snapshot mode
qemu-nbd --snapshot --connect=/dev/nbd0 /path/to/my/fuse/borg/disk.raw #vmdk vdi ....
#Access raw,vdi vmdk partitions by 
ls -lah /dev/nbd0p*
#Disconnect when ready
qemu-nbd -d /dev/nbd0 
```

**Comment by ThomasWaldmann** [comment]
@enkore remove bug label? doesn't look like a borg bug, rather a performance issue.

**Comment by enkore** [comment]
This issue doesn't seem to contain something actionable. The kind-of question has been answered. Unclear whether any issue remains. Closing. Feel free to reopen if this assessment is not accurate.
