### ISSUE TITLE
Is it safe to upload config file?

### ISSUE THREAD

**Issue by StefanMallia** [borgbackup/borg#2079]
I am currently creating encrypted backups on my local machine and incrementally uploading newly created files (by Borg) to an online storage. Is it safe to also upload the config file? What could an attacker do if they got access to the config file but not the passphrase?

**Comment by enkore** [comment]
If you're using repokey, then anyone with access to the config can start brute-forcing the contained key file. It's PBKDF2-HMAC-SHA256 @ 100k iterations or so.

**Comment by StefanMallia** [comment]
Then that means storing the config file with the repository is unsafe even with a strong (30 char and random) passphrase?

**Comment by enkore** [comment]
30 random letters and numbers are about 6e+53 possibilities, even at 1 billion combinations per second (1 GHz = 3e+16/year) that's still like 2e+37 years (20 billion billion billion billion years).

**Comment by StefanMallia** [comment]
Great so short answer is that keeping config file secret is not important if one has a strong passphrase. Thank you!
