### ISSUE TITLE
make a better / real man page

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#208]
README.Debian from the debian package tells about quite some difficulties about creating a man page.

I think this should be solved upstream (== by us), also to make it easier for other linux distributions.

Debian packaging is discussed here:

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1355849.html

The solution for creating the manpage should be automated.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/26801934-make-a-real-man-page)

**Comment by anarcat** [comment]
more accurate URL for the packaging work is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792096

i was able to generate man pages by formatting argparse usage using some shims in monkeysign, initially inspired by:

https://andialbrecht.wordpress.com/2009/03/17/creating-a-man-page-with-distutils-and-optparse/

original source: https://crunchyfrog.googlecode.com/hg/utils/command/build_manpage.py

current implementation: https://sources.debian.net/src/monkeysign/2.0.2/monkeysign/documentation.py/#L13

this would need to be ported to argparse (easy) and eventually to click (harder, see https://github.com/mitsuhiko/click/issues/434)

**Comment by anarcat** [comment]
i gave that my best shot, and argparse is just a nightmare to handle, particularly with our sub-parsers and everything. i would suggest we wait for the click port in #251 before spending any more time on this.

my current work is in my [man-builder branch](https://github.com/anarcat/borg/commits/man-builder) if anyone is masochistic enough to continue this nonsense.

**Comment by LocutusOfBorg** [comment]
what about using rst2man?

**Comment by rumpelsepp** [comment]
In syncthing we do it like this:

* http://docs.syncthing.net/users/syncthing.html
* https://github.com/syncthing/docs/blob/master/conf.py#L251-L291

**Comment by anarcat** [comment]
@LocutusOfBorg would be certainly easier than the curent approach. however we'd need to split the manpages better: right now the `usage.rst.inc` files is all in one file, so we can't use rst2man to generate multiple manpages.

but i think it makes perfect sense, especially considering how messy #384 has become. we could revert all the mock and `have_cython` stuff and simply generate the `rst` files statically. then we'd have a much better control over the content of those files and could generate manpages, which would be readable directly online here (in github) as well.

@ThomasWaldmann would that satisfy the bounty you posted?

**Comment by anarcat** [comment]
i did the above suggestion in #408. the next step here will be to split the usage file into multiple parts so that rst2man can kick in.

**Comment by anarcat** [comment]
@rumpelsepp thanks for the suggestion, looks like the way to go now...

**Comment by anarcat** [comment]
@rumpelsepp how do you keep those rst files in sync with the code? by hand?

**Comment by anarcat** [comment]
i built #409 to fix this.

remaining todos after the PR:

* hook manpages into `setup.py`
* turn `usage.rst` into a `borg.1` manpage so the docs there can also be read online

**Comment by rumpelsepp** [comment]
@anarcat: Yeah, by hand. Since you "only" have to document the command line interface (which might not be changed that often), it is not that big deal to keep that in sync. One should keep in mind to always update documentation in a PR as well when the CLI changes.

**Comment by rumpelsepp** [comment]
And also, I suggest to structure the manpages like git does: `borg-create(1)`, `borg-prune(1)`, ... All possible subcommands in one manpage is a bit of a pain to read.

**Comment by anarcat** [comment]
@rumpelsepp then you may find it interesting to look at the `build_usage` in `setup.py` in #409 - it generates the `rst` sources for each manpage automatically. it lacks per-option markup, but it's otherwise quite useful.

and i agree about `borg-create(1)`, just need to convince @ThomasWaldmann now. :p

**Comment by ThomasWaldmann** [comment]
I guess we can have borg-*, but there also should be a borg manpage with the basics and to refer to the others.

**Comment by anarcat** [comment]
yeah, that's what i was hoping to do with the `usage.rst` file, but since it has that table of contents on top, it actually includes all the other manpages in the rendering... so some more work required.

also note that, in debian, doing "man borg create" will find the "borg-create(1)" manpage.

**Comment by oz123** [comment]
Hi, 
If you are using argparse, you might consider using this:
https://github.com/oz123/man-utils

I am the author of this, and I would like to get some feed back.  I basically adds a method to your setup.py which you can use to create the man page. 
All it does is parse your argparse...

**Comment by anarcat** [comment]
well, i guess the first feedback i will give you is that i have no idea how to use this in our project. the only documentation i could find says to `import man-utils`, but where should i do that? near main? in setup.py? you mention a method in setup.py, but that's not documented either...

**Comment by anarcat** [comment]
it looks like the goods are in https://github.com/oz123/man-utils/blob/master/manutils/manutils.py

@ThomasWaldmann that code looks pretty useful, but it would require sucking it all into setup.py (as is done in the author's original project, [pwman3](https://github.com/pwman3/pwman3/blob/develop/setup.py)) - or moving it to an import, say in borg/support/manutils.py. you were hesitant in doing that for other parts of the setup.py, so what do you think? i feel it would be messy to include it all in setup.py...

**Comment by anarcat** [comment]
license is acceptable: https://raw.githubusercontent.com/oz123/man-utils/master/LICENSE

**Comment by oz123** [comment]
@anarcat the project was a response to a bug report in python.org. It was made, and never really used unfortunately. I used it in pwman3 like you already saw. The usage is really straight forward. If you would like I can help directly via IRC or mail.

**Comment by ThomasWaldmann** [comment]
importing in setup.py is dangerous as stuff is not installed yet when it runs.

**Comment by anarcat** [comment]
@ThomasWaldmann i know about that specific concern, but i was able to workaround that fairly reliably in monkeysign in the past... are there other concerns?

**Comment by ThomasWaldmann** [comment]
I'ld prefer the man page being generated by a developer and commited to the repo than doing complex stuff triggered by setup.py (we just had a lot of troubles and pain with exactly that).

**Comment by anarcat** [comment]
sure, but that command needs to be implemented somewhere. @oz123 proposed a solution that is standalone but that can also be integrated in `setup.py` (without necessarily being triggered in the default build, same as our current build_usage).

**Comment by ThomasWaldmann** [comment]
if it is not triggered at install/build time and does not import stuff except when actually using it, I guess we could use it.

**Comment by ThomasWaldmann** [comment]
note: debian has added a manpage by just using "make man" with the sphinx Makefile. It contains the same as our html docs, just in man page format.

**Comment by anarcat** [comment]
@TW this is what #409 was trying to do as well.

**Comment by ThomasWaldmann** [comment]
As (IIRC) more than 1 linux dist is now generating their "own" man page by just using "make man", I think we should do that upstream, so they don't have to.

**Comment by bpereto** [comment]
Building borgbackup for CentOS (#105) is at the moment not possible, cause the needed packages and dependencies for spinx are not available in epel. python3-spinx and python3-spinx_rtd_theme have a lot of deps.

**Comment by ThomasWaldmann** [comment]
@bpereto how about building a package without (html or manpage) docs? borg has builtin help and the html docs are on our web site.

**Comment by bpereto** [comment]
@ThomasWaldmann 
found python2-sphinx exists in epel, so I can stick with that. and after fixing the unicode string literal, it worked.

**Comment by ThomasWaldmann** [comment]
@enkore claim the bounty.
