### ISSUE TITLE
borg list: make it possible to list archive comments as well

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#2081]
Add optional backup log text into borg create command.

Example

`usage: borg create [-h] [--critical] [--error] [--warning] [--info] [--debug]
                   [--lock-wait N] [--show-rc] [--no-files-cache] [--umask M]
                   [--remote-path PATH] [-s] [-p] [--list]
                   [--filter STATUSCHARS] [-e PATTERN]
                   [--exclude-from EXCLUDEFILE] [--exclude-caches]
                   [--exclude-if-present FILENAME] [--keep-tag-files]
                   [-c SECONDS] [-x] [--numeric-owner] [--noatime] [--noctime]
                   [--timestamp yyyy-mm-ddThh:mm:ss]
                   [--chunker-params CHUNK_MIN_EXP,CHUNK_MAX_EXP,HASH_MASK_BITS,HASH_WINDOW_SIZE]
                   [--ignore-inode] [-C COMPRESSION] [--read-special] [-n]
                   [--log Log text ending with characters --]
                   ARCHIVE PATH [PATH ...]

--- or ---

usage: borg create [-h] [--critical] [--error] [--warning] [--info] [--debug]
                   [--lock-wait N] [--show-rc] [--no-files-cache] [--umask M]
                   [--remote-path PATH] [-s] [-p] [--list]
                   [--filter STATUSCHARS] [-e PATTERN]
                   [--exclude-from EXCLUDEFILE] [--exclude-caches]
                   [--exclude-if-present FILENAME] [--keep-tag-files]
                   [-c SECONDS] [-x] [--numeric-owner] [--noatime] [--noctime]
                   [--timestamp yyyy-mm-ddThh:mm:ss]
                   [--chunker-params CHUNK_MIN_EXP,CHUNK_MAX_EXP,HASH_MASK_BITS,HASH_WINDOW_SIZE]
                   [--ignore-inode] [-C COMPRESSION] [--read-special] [-n]
                   [--log "Log text between quotation marks"]
                   ARCHIVE PATH [PATH ...]
`

Log text is a free text describing the content of the backup. It is shown as last column when running borg list command like this:

borg list /home/foo/bbckpdata/MyBackup
documents--2016-12-21_17:55:50        Wed, 2016-12-21 17:55:54  Initial backup
documents--2016-12-21_18:26:07        Wed, 2016-12-21 18:26:11  Before huge change xxx.
documents--2016-12-21_18:35:08        Wed, 2016-12-21 18:35:08  After adding new content from yyy.
presentations--2016-12-21_19:07:56    Wed, 2016-12-21 19:07:56  Before major change zzz.
presentations--2016-12-21_19:30:07    Wed, 2016-12-21 19:30:07  Daily backup.

Purpose of this log text is to more easily find the correct archive when restore is needed or give some idea what archives can be pruned away.

**Comment by enkore** [comment]
1.1 has [archive comments](http://borgbackup.readthedocs.io/en/1.1.0b3/usage.html#borg-create) but I believe that they can't be listed in the archive listing. One could add that, though.

**Comment by jk-1** [comment]
Sounds what I'm looking for if it is available on borg list output.
If borg list backward compatibility is an issue you could add comments on borg list output only when using option borg list  --comment

usage: borg list [-h] [--critical] [--error] [--warning] [--info] [--debug]
                 [--lock-wait N] [--show-rc] [--no-files-cache] [--umask M]
                 [--remote-path PATH] [--short] [--list-format LISTFORMAT]
                 [-P PREFIX]
                 [--comment]
                 [REPOSITORY_OR_ARCHIVE]

**Comment by ThomasWaldmann** [comment]
could be also added via --list-format and a placeholder (if not already possible).
