### ISSUE TITLE
borg mount -f should umount when SIGINT (ctrl-c)

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2082]
Currently, the mount remains beyond the command execution.
This behaviour is inconvenient for those who use it as a means of assuring you don't forget to umount it (and thus remove the lock).

Thanks!

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.0.9/borg/fuse.py#L93 see there.

**Comment by alejandro-perez** [comment]
Umm, I do agree that if there is a crash, we should not umount. 
But IMHO receiving a SIGINT signal is something you do on purpose, and you know what you are doing, and in that particular signal at least you should umount.

**Comment by enkore** [comment]
SIGINT should be umount, at the very least when running the --foreground.

**Comment by alejandro-perez** [comment]
Great thanks! I'm looking forward to see borg 1.1.0 out!

**Comment by ThomasWaldmann** [comment]
fixed by #2102.
