### ISSUE TITLE
doc page "Resources" vs. borg-community

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2088]
Resources has:

- "This is a collection of additional resources that are somehow related to borgbackup."
- Videos, Talks, Presentations
- Software

community has:

- " random stuff from borg community"
- Software + a bunch of scripts

---

IMHO it would be better to just have *one* of these and merge them.

I think the Resources page in the docs is better, but there should only be one (latest) version of it. So maintenance branches would just link to the latest version of it (one can do that in the toctree).

**Comment by ThomasWaldmann** [comment]
how about:
- docs: **our** stuff + major, popular 3rd party stuff (slow changing, ok as it is now)
- community repo: any related stuff, quickly changing

**Comment by enkore** [comment]
Neither is changing much, so...

**Comment by enkore** [comment]
How bout throwing the docs page out, moving everything to the community repo, and replacing the "Resources" TOC item with a direct link to the community repo.

**Comment by ThomasWaldmann** [comment]
I'ld rather have a link from a content page than mess with the TOC.

**Comment by enkore** [comment]
Just an idea: Make a "The Borg Collective" (or "Join the [Borg] Collective") page on borgbackup.org which has all of this. I'd wager that would give the many excellent projects in borgbackup/community much more exposure than they get now.

**Comment by ThomasWaldmann** [comment]
"The Borg Collective" is used in the docs to refer to borgbackup contributors, so we shouldn't use same term for the wider group of borg users or developers of related projects.

So how about "BorgBackup related resources"?

**Comment by rugk** [comment]
That is a great idea. I also see that the community repo is a bit off/far away and hard to find. So what will be the way to go?

**Comment by ThomasWaldmann** [comment]
please review PR #5140.

**Comment by fantasya-pbem** [comment]
Anything to do here?

**Comment by ThomasWaldmann** [comment]
@fantasya-pbem no, i guess you fixed this by your recent PRs. thanks!

btw, guess these 3 PRs would for sure qualify for a "update docs" bounty, if you like.
