### ISSUE TITLE
`borg extract --stdout` with leading slashes fails silently

### ISSUE THREAD

**Issue by chrysn** [borgbackup/borg#209]
i recently had to restore my .zsh_history file. as many runnign processes might overwrite it, i went for extraction to --stdout (to redirect it to ~/.zsh_history-extracted; i might instead as well have used direct extraction in another directory had i read the changelog of 0.24 before).

while

    borg extract prometheus:hephaistos.borg::chrysn-full-2015-09-17-10:20 home/chrysn/.zsh_history --stdout >! .zsh_history-borg-stdoutrestored

worked fine,

    borg extract prometheus:hephaistos.borg::chrysn-full-2015-09-17-10:20 /home/chrysn/.zsh_history --stdout >! .zsh_history-borg-stdoutrestored-leadingslash

created an empty file without indicating any error. at least, it should give an error message when it doesn't find the file at all, but practically, it should either accept the leading slash or immediately err out. the issue is especially present in user directories, where one would be tempted to do `borg extract ... ~/.zsh_history`, which is expanded by the shell to the leading-slash form.

the borg version used that showed that behavior was 0.23.0, apologies if it's already fixed in later versions.

**Comment by ThomasWaldmann** [comment]
the issue title and description is a bit misleading.

your main issue seems to be that extracting a file that does not exist in the repository fails silently.
that does not depend on --stdout, it also happens in the same way without that.

about the other issue: I guess we can't fix the leading slash issue as creating an archive from a relative path works also and is also stored without a leading "/", so we can't know later if the "/" was there or not and whether we could just strip it or not.

**Comment by ThomasWaldmann** [comment]
Looking at it more generally: it is allowed to give multiple path arguments. So, to implement this, we would need to remember whether we have matched each of them once at least.

**Comment by ThomasWaldmann** [comment]
Even more generally, there might be also exclude patterns that do not match (but I think we should not complain about them not matching).
