### ISSUE TITLE
posix_fadvise fails in docker container

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2095]
https://bugs.alpinelinux.org/issues/6592

**Comment by enkore** [comment]
Also found 1-2 Python bugs here: http://bugs.python.org/issue29342

**Comment by ThomasWaldmann** [comment]
Guess we should add an exception handler and ignore any errors (which we can do here as fadvise failures are only changing caching behaviour).

While we could call logger.warning on such exceptions, doing so might be an annoyance as with bugs like found above, the warning would get emitted frequently (per file).

Maybe we could use the "warnings" module rather than logging with a warning filter with action="once".

**Comment by enkore** [comment]
posix_fadvise does normally never fail -- we're not even talking to the FS here, actually, so poor FUSE FSes and such have nada influence here.

My guess here is that there perhaps is a race condition in the handling of `__del__`; perhaps the segment FD is already gone -> fileno() = -1 -> posix_fadvise fails. The fix would be to correct the behaviour (... why is the repository closed in `__del__` anyway, for example), not ignore the error.

**Comment by ThomasWaldmann** [comment]
As he told this only happens with docker, I thought it might be caused by running under docker.

**Comment by enkore** [comment]
Hm, giving some thought to that: His traces would indicate that it's a general problem (note how there is a second trace (starting in the middle of the `__del__` trace) which is the actual main control flow, so not racy). It only happens on ARM && docker. fadvise64, the syscall underpinning posix_fadvise, was incorrectly devised when introduced, so ARM (presumably PPC as well) have a different syscall, fadvise64_64. Perhaps there is some issue there with the libc or docker on ARM.

**Comment by ThomasWaldmann** [comment]
@enkore guess it can't be the fd.fileno() as 2 lines above the fadvise we do fsync on same fd.fileno(). if it were invalid, it would blow up there also.

but I noticed there might be re-entrance happening. some cases harmless, but could also cause problems, see my PR.

**Comment by ThomasWaldmann** [comment]
https://github.com/docker/docker/issues/30516 I filed it also there, maybe the docker devs can help.

**Comment by ThomasWaldmann** [comment]
As a side note: besides the posix_fadvise call in repository.py, we have another one in _chunker.c - but we do not check the return value there.

**Comment by ThomasWaldmann** [comment]
worked around by #2104 (which just ignores the OSError, so borg does not blow up - the root cause outside of borg still needs fixing)

**Comment by enkore** [comment]
Fix by: https://github.com/docker/docker/issues/30516#issuecomment-275921962

**Comment by enkore** [comment]
Given that the Docker installation can be fixed by admin, no update per se needed, do we still need the workarounds?

**Comment by ThomasWaldmann** [comment]
Well, not really necessary, but would improve the UX on docker / ARM. Like "just works" vs. "blows up, admin needs to research, patch system stuff (once? after every sec. upd.?)".

IF we remove the workaround in the python code, we would also need to add an error check in the C code to be consistent about it. 

Separate PR.
