### ISSUE TITLE
use gitlab?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2097]
Had some discussion on email about github and whether contributing to the project is possible without using github.

Currently (with borg collective only using github) I think this is not really something that scales to more than minor contributions (e.g. sending in an easy patch via email or mailing list). Bigger contributions are hard to handle that way.

While discussing / researching, gitlab came up as potential alternative - it even allows authenticating via github (or bitbucket or ...) for people who want to do so (so there is no "you have to create an account first" barrier) - while not requiring it for those who don't.

Just opening this ticket to collect opinions / options.

**Comment by ThomasWaldmann** [comment]
Note: this should not be regarded as a representative poll (as obviously people not wanting to use github can't comment here).

**Comment by dadadel** [comment]
As an other open source alternative, there is also [Gogs](https://gogs.io/) that looks like Github.

**Comment by RonnyPfannschmidt** [comment]
@dadadel i dont think self-hosting is considered a viable alternative due to racking up quite some maintenance cost in terms of owned/rented systems and time to set up/update/keep running

**Comment by enkore** [comment]
Self-hosting the SCM and issue tracker creates an unnecessary single-point-of-failure in the project.

**Comment by ThomasWaldmann** [comment]
The main issue why non-github project hosting was brought up were privacy issues related to github usage.

**Comment by bebehei** [comment]
> privacy issues related to github usage.

@ThomasWaldmann Could you please elaborate on this? I don't see why gitlab.com should be better in relation to privacy.

**Comment by enkore** [comment]
Either one is a mostly venture-capital funded US-based incorporation, I don't really see any difference (except for GitHub being more popular overall).

**Comment by ThomasWaldmann** [comment]
@bebehei the reasons told were mostly about only one real-name being allowed per person (see TOS) and you have to use that for all your contributions (public as well as private repos, your private stuff as well as the work you do for companies using paid github repos). It is pretty easy to build a profile of somebody with this.

The difference with gitlab (hosted) vs github (hosted) is mostly a thing of preference and trust.
OTOH, gitlab can also be self-hosted, then you only trust yourself (or *that* hoster, if it is not you).

**Comment by enkore** [comment]
Like I said above, self-hosting just creates a big (issue tracker, canonical URLs, incoming links from other sites) single point of failure for imho little value added back to the project, apart from issues like "who's paying for it". Using smaller hosters -- either they are free, then that's problematic because these went under some times already, or they're paid, same question as with self hosting, just a different kind of SPOF.

**Comment by ThomasWaldmann** [comment]
Well, maybe the realname requirement came from one of the projects / employers.
If you only can have one account (due to github) and at any time someone requires realnames, the end result is same.

**Comment by bebehei** [comment]
I found the first reasonable(at least for me) argument: https://mikegerwitz.com/about/githubbub

But I'm not sure, if his point is valid: AFAIK gitlab.com runs GitLab EE and I doubt that GitLab EE's javascript source code is free for non-paying members.

**Comment by enkore** [comment]
> That is—GitHub forces you to run proprietary software in order to use much of their website. This is unethical.

^- That's actually not how ethics work.

**Comment by enkore** [comment]
Closing, see discussion above.

An additional data point: I had to use Gitlab in the last couple weeks, and I don't want to use it again, like **ever**, until they improve.
