### ISSUE TITLE
Potential issues with v1.1.0-b3

### ISSUE THREAD

**Issue by magma1447** [borgbackup/borg#2098]
I have been running borgbackup-1.1.0-b2 since the start of October, this far without issues. I am adding around 500 GB (before deduplication and compression) of new data to my backup-repos every day, from 10 different hosts.

Last week I upgraded to 1.1.0-b3, within 30 hours from that upgrade I received my first issue with my borg-repos.
`
var/lib/redis/dump-session.rdb: New missing file chunk detected (Byte 1039118850-1040776088). Replacing with all-zero chunk.
Archive consistency check complete, problems found.
`
This was my only output for stderr.

14 hours later I received the same error again (different byte values though).
In between I had run a borgbackup check manually, no issues found.

Yet another 4 hours later I got this error:
`
zlib.error: Error -3 while decompressing data: incorrect header check
`
This error was from another host, and another destination repo.

My backup setup works like this:
Each host has three repos to backup to, rotated based on weekday (Mon+Thu, Tue+Sat, Wed+Fri+Sun). The different hosts does not share repo with each other.
Backups are run every hour for some of the hosts, daily for others. Those using the most data are run every hour.
The backup process uses these commands: create, prune, check.
`
${BORGBIN} create --lock-wait ${BORG_LOCKWAIT} --compression auto,lz4,1 ${BORG_ARCHIVE}::{now} ${BACKUPFILES}
${BORGBIN} prune --lock-wait ${BORG_LOCKWAIT} --keep-within 5d ${BORG_ARCHIVE}
${BORGBIN} check --lock-wait ${BORG_LOCKWAIT} --last ${BORG_CHECKLAST} --no-files-cache ${BORG_ARCHIVE}
`

After my third error I downgraded to 1.1.0-b2 again. 24-30 hours has passed since then and I have not seen any errors.

If it's not clear, I am raising the question if there could be an issue with 1.1.0-b3. It could of course be a hardware issue on my side as well.

**Comment by magma1447** [comment]
Adding some notes/discussion from IRC.

> 11:49 < ganja\> ThomasWaldmann: I am a bit suspecious of the b3 version. ~30 hours after I upgraded from b2 to b3 I got my first error from a check, ever.
11:49 < ganja\> var/lib/redis/dump-session.rdb: New missing file chunk detected (Byte 1039118850-1040776088). Replacing with all-zero chunk.
11:49 < ganja\> Archive consistency check complete, problems found.
11:49 < ganja\> Borgbackup check failed
11:51 < ganja\> This raises two questions for me. 1) Is it a coincidence that it happened when I upgraded to b3? 2) It replaced with all-zero chunk, I did not pass --repair to the check, should it really change things when I do not? I assume --repair is not default.
11:52 < ganja\> I have rerun check and I do not get any errors anymore.
12:20 < ganja\> $ borgbackup check --last 20 --no-files-cache pgc-nosql-01.borg
12:20 < ganja\> Enter passphrase for key /data/borg-WedFriSun/pgc-nosql-01.borg: 
12:20 < ganja\> $ echo $?
12:20 < ganja\> 0
14:50 < ThomasWaldmann> ganja\: hmm, that is strange
14:51 < ThomasWaldmann> can you file a bug report with all the details?
14:52 < ThomasWaldmann> like which commands were run against the repo until you found the missing chunk
14:53 < ThomasWaldmann> also do a fsck on the fs and a smartctl -a on the disk
14:55 < ThomasWaldmann> also, in the check output, i'ld guess there was another warning before the one you posted?
16:16 < ganja\> ThomasWaldmann: I can try to file an issue with details of what process has been run. I'll do it later today or tomorrow. It's a raid6 filesystem to which I write hundreds of gigabyte ever day, it's not likely the FS is broken. There was no other stderr output. stdout is in my /dev/null.
16:25 < ganja\> ThomasWaldmann: Interesting enouhg, I just got another error. From the same host (of 10), same error. Same destination repo. The first error was at 2 am, the second at 4 pm. There is a backup every hour. So about 14 hours/backups between them.
16:58 < ThomasWaldmann> ganja\: were there other ops than borg create in between?
16:59 < ganja\> create, purge, check
16:59 < ganja\> More exact:
17:00 < ganja\> ${BORGBIN} create --lock-wait ${BORG_LOCKWAIT} --compression auto,lz4,1 ${BORG_A
17:00 < ganja\> RCHIVE}::{now} ${BACKUPFILES}
17:00 < ganja\> ${BORGBIN} prune --lock-wait ${BORG_LOCKWAIT} --keep-within 5d ${BORG_ARCHIVE}
17:00 < ganja\> ${BORGBIN} check --lock-wait ${BORG_LOCKWAIT} --last ${BORG_CHECKLAST} --no-files-cache ${BORG_ARCHIVE}
17:01 < ThomasWaldmann> --no-files-cache?
17:02 < ThomasWaldmann> btw, there is no ,1 for lz4
17:03 < ganja\> I wanted a check without file-cache, didn't take the time to read up if it mattered.
17:03 < ganja\> ok, no lz4,1. Doesn't really matter. :)
17:04 < ThomasWaldmann> I'ld suspect that --no-files-cache does not change how borg check work.
17:05 < ThomasWaldmann> so, did you look into SMART data?
17:06 < ganja\> smartd will email me if there is anything of interest. There are no known issues of the disks.
17:07 < ganja\> /sys/devices/virtual/block/md2/md/mismatch_cnt is 0 (it's stored at md2)
17:07 < ThomasWaldmann> can you just put all smartctl -a output into a pastebin?
17:07 < ganja\> ok, wait a min, many disks
17:08 < ThomasWaldmann> (would be not the first time that borg is first to notice some hw issue)
17:09 < ganja\> The fact that I don't believe it is that I backup 10 hosts to the same md, using borg. This is one of the smaller ones failing.
17:09 < ThomasWaldmann> other than that and fs issues, borg prune and borg check are next suspects
17:10 < ganja\> http://pastebin.com/hRAExAJa
17:16 < ThomasWaldmann> line 263 might be your problem
17:17 < ThomasWaldmann> check / exchange sata cable
17:18 < ganja\> That's my sdx, it's a spare. Sorry, forgot to exclude those.
17:18 < ganja\> That disk has been "fixed".
17:18 < ganja\> and even if it's not fixed, it's not used right now.
17:19 < ganja\> serial WD-WCC4E1095675 and WD-WCC4E5PL8KC1 are also spares.
17:21 < ThomasWaldmann> line 921 same thing
17:23 < ThomasWaldmann> 1298 a few
17:25 < ThomasWaldmann> you have a lot of disks :)
17:25 < ThomasWaldmann> some disks also have quite many load cycles.
17:26 < ganja\> That's just half of the disks.
17:27 < ganja\> The problem is that I do not believe the fact that it happened ~24h after an upgrade to b3. Especially not when I am writing 500 GB per day to that filesystem, and have done so for a year.
17:27 < ganja\> That coincidence seems a bit too much impossible to me.
17:27 < ThomasWaldmann> well, could be coincidence, but likely isn't. we can't know.
17:28 < ganja\> I have downgraded my binary again. If borg isn't guilty, I should not get the same errors again I assume.
17:28 < ThomasWaldmann> writing lots of data to the disks only shows that the sectors occupied by that data are ok.
17:28 < ganja\> Though there is a risk that particular repo is "destroyed" now I guess.
17:28 < ThomasWaldmann> other sectors could be not ok.
17:29 < ganja\> But since it's a raid6 it shouldn't matter if a few sectors are bad.
17:29 < ThomasWaldmann> also, 2 disks have (had?) faulty cables or sata ports.
17:29 < ThomasWaldmann> and a 3rd one had a slight issue with that, maybe ignorable.
17:30 < ganja\> I believe those errors are old, but I can't be sure. I bought them for another computer. But that hw raid card threw them out one after one.
17:30 < ganja\> I ended up buying other disks for that server after that, and used these on this one instead.
17:30 < ThomasWaldmann> noticable is that most disks have never seen a smart long test
17:31 < ganja\> But since I haven't written down their smart output before that move, I can't say for sure.
17:31 < ThomasWaldmann> I'ld do that on all disks in some low-usage hours.
17:31 < ThomasWaldmann> maybe not on all at the same time to lower the risk of multiple disk failures at once.
17:35 < ThomasWaldmann> in any case, file a bug and re-use the irc log from above ^^^^ to supply all the details into that bug report
17:36 < ganja\> I will do that later today or tomorrow when I have the time. A bit split between two tasks right now.
17:36 < ganja\> I don't know how used the b3 is. I have 4.6 TB borg-data. Adding about 500 GB every day (before dedup/compress).
17:37 < ThomasWaldmann> another interesting check would be to run memtest86+ on the machine(s)
17:37 < ganja\> That won't happen, it's not that easy for me to take it offline for hours/days.
17:37 < ThomasWaldmann> b3 is likely not much tested yet as it is rather fresh
17:38 < ThomasWaldmann> not much *practically* tested, of course the unit tests were ok
17:38 < ganja\> Yes, I understand that there are unit tests. But it's not always the same thing.
17:39 < ThomasWaldmann> there are also application level memory testers, but the only test the memory they get
17:39 < ganja\> It's a very busy system, that's not practical.
17:39 < ganja\> I got another error from another host now actually.
17:40  * ThomasWaldmann gtg now, bbl. thanks for the report, but please make it permanent in the issue tracker so we have it all in one place.
17:40 < ganja\> and another borg-repo
17:40 < ganja\> This error would sound like a memory issue though "zlib.error: Error -3 while decompressing data: incorrect header check"
17:40 < ganja\> or disk, I notice it's the check that fails again.

**Comment by magma1447** [comment]
Adding to the IRC-log I can say that I have not run a fsck on the filesystem, neither have I run a memtest. It's a server that I rather don't bring down for the amount of time that takes. Though if there actually is an issue, that is definitely a mistake from my part since it could have severe consequences.

**Comment by magma1447** [comment]
Last note for now. Neither of the disks which had smart-errors logged has increased their values since initially checked. smart-log available here: http://pastebin.com/hRAExAJa

**Comment by enkore** [comment]
> 17:40 < ganja> This error would sound like a memory issue though "zlib.error: Error -3 while decompressing data: incorrect header check"

Most likely a memory or CPU issue, since the SHA-256 did not notice it - not corrupted on disk.

**Comment by magma1447** [comment]
@enkore 

> Is that repository encrypted?

Yes, it's encrypted.

> Did you see that error with b2 on the same repo as well?

Not a single time.

> What's the compression usually used there?

I have run a recreate earlier to change all old/current data to lzma,6. All new data is zlib,3.

> The other issues I cannot say. It raises eyebrows for sure.

The most important thing for me is actually that my issues are known. If you start getting other similar reports regarding 1.1.0-b3, it's interesting to know that the next one isn't alone.

> Regarding the check message about replacing stuff

Great to know, thank you for the explanation!

PS! I am currently working on running fsck on the filesystem. I have 3 raid6 arrays, two of them has been checked, without errors. All three have borg-repos on them, but it's the third that is relevant for this issue. The problem is that something is using it, and I can not figure out what, yet. Worst case it's a reboot incoming soon.

**Comment by enkore** [comment]
When it's encrypted then my original comment would be correct - the bytes zlib is complaining about as corrupted where verified by SHA-256 immediately before decryption. This one is likely a hardware issue then, but that may/may not be related to the other errors you saw. Since it passed SHA-256 it would be correct on disk.

Assuming this is a hardware problem eg. memory then it might be that b3 trips over it because it has slightly different memory layout/usage from b2.

---

Regarding check messages again: We should probably add the cause of why the chunk is invalid (the IntegrityError, CRC vs MAC vs ID error).

**Comment by magma1447** [comment]
I had to reboot the server to get single access to my last md. There were a few errors, so there is a potential that my issues aren't related to 1.1.0-b3. It's a hell of coincidence though.
`
/dev/md2: Clearing orphaned inode 1095762 (uid=0, gid=34, mode=042755, size=4096)
/dev/md2: Clearing orphaned inode 1095555 (uid=0, gid=34, mode=042700, size=4096)
/dev/md2: Clearing orphaned inode 102401 (uid=0, gid=1000, mode=040770, size=4096)
`

And about 100 of these, which as I understand isn't an error:
`
Inode 3524870 extent tree (at level 1) could be narrower.
`

I will run a few days with 1.1.0-b2 again. If it seems to work, I will try 1.1.0-b3 ones again to see if I start getting errors after an upgrade again.

**Comment by ThomasWaldmann** [comment]
Thanks for the update. The orphaned inodes are strange, did the server crash/reboot somehow?

**Comment by magma1447** [comment]
@ThomasWaldmann 
Not that I can remember. The uptime was 255 days, since 12th May. MD2 was created in the end of April 2016. That leaves only a ~two week window unspoken for. And since the raid was new, I am sure I would have been careful enough to fsck my new content on it the first weeks if it crashed.

**Comment by ThomasWaldmann** [comment]
I added it to b4 milestone as it was seen with b3.

so, in case this turns out being a bug, we'll want to fix it in b4.

**Comment by ThomasWaldmann** [comment]
Any news?

**Comment by magma1447** [comment]
Running a fsck on the same md right now. I have a handful of new errors, which is quite scary.

Hopefully this means that it's unlikely that it was Borgbackup's fault.

I will go through a fsck on all 3 md's today, twice to be sure there are no errors after the first run. After that  I will check all 3*10 borg repos, and then finally upgrade to b3 again.

**Comment by ThomasWaldmann** [comment]
@magma1447 can you say something about your (raid) hardware?

**Comment by magma1447** [comment]
Time is running out for today. Got a dinner meeting to attend at 16:30. I didn't get as far as I wanted, but I will write down what I have done this far, the output of it, and the plan.

But first I'll answer your last question. I am using Linux Software raid. Disks are randomly connected to 2 different sata controllers on the motherboard and 2 dual port LSI sas controllers, having a non-raid firmware on them, and also a DAS cabinet connected via SAS to one of the ports on one of the sas controllers.

So what I did first today was a borg check on 8/30 borg-repos. No errors reported.

I then ran a fsck -f -n, on mounted devices while in use. That told me I had errors on 2/3 MDs. Unexpected and worrying, but ok.

I then stopped all related services and unmounted everything and started to run fsck for real. Exact command was 'fsck -f -p -C - /dev/md0', and md1 and m2.
All three were clean except from the fact that 'the extent tree could be narrower'. Interesting, clean, it just said I had errors. *confused*
I then ran fsck -f -p -D -E bmap2extent -C - /dev/md0 (and md1, md2). Zero errors again.
I then ran yet another of the first variant to make sure it was clean after the tree optimization. Zero errors again.

I have then been running borgbackup check on all 10 borg-repos I have on md2. Zero errors. I will start checking all borg-repos on md1 now. I won't be able to finish those checks on my last 20 borg-repos today, it takes too long time.

Tomorrow I will finish those borgbackup check's. I expect them to come out clean. After that I will upgrade to b3 again.

The system is a Debian Stretch.

**Comment by ThomasWaldmann** [comment]
Hmm, if a device is mounted (r/w) and active, can fsck give correct results? I always thought it needs to be unmounted (or at least r/o).

**Comment by enkore** [comment]
Hmm, sometimes getting errors, sometimes not, b2 no errors, b3 errors, [this trace](https://github.com/borgbackup/borg/issues/2098#issuecomment-274547004), could really all be memory errors (especially the last one).

You mentioned that taking the machine down for many hours for a memtest is of course not a good option, but since these clues point toward userspace getting bad memory, maybe try a userspace memory tester, like [memtester](https://packages.debian.org/jessie/utils/memtester).

**Comment by magma1447** [comment]
From some googling about it. Fsck -n on an online mount isn't reliable. This makes me wonder why it's accepted without a warning. But that's another discussion, for another forum.

But since that is unreliable I would say that I have been going through all valid tests with 0 errors then. In other words, I see no real reason for a memory test. There are no indications of any system/data error from the last 4 weeks.

**Comment by magma1447** [comment]
I don't know if anything has changed with the check command. But I just got the idea that I could run a check with the b3 version as well before actually creating any backups with it. Maybe it's detecting something b2 isn't?

**Comment by magma1447** [comment]
I have now finished checking all 3*10 repositories, with both b2 and b3. No issues found. I will push out the b3 binary again.

**Comment by magma1447** [comment]
Got this 12 minutes ago.
`
var/lib/redis/dump-session.rdb: New missing file chunk detected (Byte 1079921118-1081887582). Replacing with all-zero chunk.

Archive consistency check complete, problems found.

Borgbackup check failed
`
About 24 hours after I upgraded to b3.

**Comment by ThomasWaldmann** [comment]
ok, can you tell us the sequence of commands issued since the change to b3?

also, are we confident that hardware issues can be ruled out?

**Comment by magma1447** [comment]
These are the commands used, before and now. I have just pushed newer binaries.
> ${BORGBIN} create --lock-wait ${BORG_LOCKWAIT} --compression auto,lz4,1 ${BORG_ARCHIVE}::{now} ${BACKUPFILES}
> ${BORGBIN} prune --lock-wait ${BORG_LOCKWAIT} --keep-within 5d ${BORG_ARCHIVE}
> ${BORGBIN} check --lock-wait ${BORG_LOCKWAIT} --last ${BORG_CHECKLAST} --no-files-cache ${BORG_ARCHIVE}

I am quite confident that there is no hardware issue. At first I was running b2 for quite some time without a single error. Then I upgraded to b3 and got several errors within 24 hours. My filesystem did have a handful of errors back then though.

After correcting those filesystem errors I then downgraded to b2 again, and was running that for 4 weeks. Not a single error. Checked the filesystems, no errors. I then upgraded to b3 and found errors after about 24 hours.

If it was an unlikely coincidence before, it's even more unlikely this time.

Just ran a manual check on the repo.
> borgbackup check pgc-nosql-01.borg/
> var/lib/redis/dump-session.rdb: New missing file chunk detected (Byte 53980987-56496247). Replacing with all-zero chunk.
> var/lib/redis/dump-session.rdb: New missing file chunk detected (Byte 450335289-455748381). Replacing with all-zero chunk.
> var/lib/redis/dump-session.rdb: New missing file chunk detected (Byte 1079921118-1081887582). Replacing with all-zero chunk.
> Archive consistency check complete, problems found.

A very interesting fact though. It's the same host (out of 10) that gives me errors this time. It's the host with the 3rd largest backup size which makes it fairly likely, but not very likely.

**Comment by ThomasWaldmann** [comment]
@rciorba could it be that we have a problem with _hashindex.c here?

You're more familiar with the code / code changes there, could you please look at:

- git diff 1.1.0b2 1.1.0b3 _hashindex.c  # changes between b2 and b3 (was a bug introduced?)
- git diff 1.1.0b3 master _hashindex.c  # changes after b3 (is that bug already fixed?)

The question is whether a `chunkid in chunks_hashtable` check could erroneously return False although the chunkid is in fact contained in the hashtable (just not found, due to a bug).

Thanks!

**Comment by enkore** [comment]
That would explain the missing chunk messages, yes. There was the skip hint change 766a43a, but that would not affect lookup.

It wouldn't explain the zlib failure after the HMAC was just verified. That one was likely really a memory/bus/CPU error, perhaps a one-off, not defective hardware per se, I think in the latter case we should've seen more problems by now.

**Comment by rciorba** [comment]
I can't see an obvious flaw. I also added an extra test for the hashindex https://github.com/borgbackup/borg/pull/2188 since I've been able to break it without the current test failing on the RH branch. I've ran the test both pre and post a85cf75465bbd15e016a2c73afbab98ee272e98a and it passes.

As far as loading/saving to disk, the load simply uses the iterator, which simply loops over all keys and skips deleted+empty ones, so I can't see any obvious issue there.

**Comment by enkore** [comment]
A theory:

Point 1:

> The repository index forgets to mention these. Unlikely, because check compares the rebuilt and the read-from-disk indices with each other

The comparison between built index (self.index) and on-disk index (current_index) looks like this:

```py

                for key, value in self.index.iteritems():
                    if current_index.get(key, (-1, -1)) != value:
report_error('Index mismatch for key {}. {} != {}'.format(key, value, current_index.get(key, (-1, -1))))
```

So there is no lookup used in the rebuilt index.

Point 2:

> The chunks index rebuilt from scratch by ArchiveChecker forgets to mention these.

This one is always rebuilt.

Point 3:

> Somesomething list/scan?

Unchanged.

---

Can the wrong probe length hint lead to an insert occurring *after* a tombstone behind the actual slot of the key? My understanding was that this would not make things disappear, since tombstones don't abort probing.

**Comment by rciorba** [comment]
> Can the wrong probe length hint lead to an insert occurring after a tombstone behind the actual slot of the key?

Yes! That's what https://github.com/borgbackup/borg/pull/2116 fixes.
 
> I think so, but my understanding was that this would not make things disappear, since tombstones don't abort probing.

Correct, it only has an impact on performance, not make things disappear.

**Comment by magma1447** [comment]
Is mentioned I got another error just after I upgraded to beta 3 again, but since then I have not seen any issues. It's almost two weeks ago now. Maybe there isn't a case after all.

**Comment by ThomasWaldmann** [comment]
@magma1447 if an issue happens with low probability / frequency, it is always a bit hard to debug it or even to say if it is an issue at all or just some failure somewhere else. Sometimes race conditions can happen an cause such rare errors.

**Comment by magma1447** [comment]
I shouldn't have said anything. Received this 5 hours ago:

backup/full_mysqldump.sql.borg_part_1: New missing file chunk detected (Byte 11276552296-11278017984). Replacing with all-zero chunk.

backup/full_mysqldump.sql.borg_part_1: New missing file chunk detected (Byte 32219356515-32220847801). Replacing with all-zero chunk.

backup/full_mysqldump.sql.borg_part_2: New missing file chunk detected (Byte 16940213992-16941953018). Replacing with all-zero chunk.

backup/full_mysqldump.sql.borg_part_2: New missing file chunk detected (Byte 19742669145-19743916878). Replacing with all-zero chunk.

backup/full_mysqldump.sql: New missing file chunk detected (Byte 11276552296-11278017984). Replacing with all-zero chunk.

backup/full_mysqldump.sql: New missing file chunk detected (Byte 32219356515-32220847801). Replacing with all-zero chunk.

backup/full_mysqldump.sql: New missing file chunk detected (Byte 54002303243-54004042269). Replacing with all-zero chunk.

backup/full_mysqldump.sql: New missing file chunk detected (Byte 56804758396-56806006129). Replacing with all-zero chunk.

backup/full_mysqldump.sql.borg_part_2: New missing file chunk detected (Byte 7523117277-7523932831). Replacing with all-zero chunk.

backup/full_mysqldump.sql: New missing file chunk detected (Byte 52247316299-52248131853). Replacing with all-zero chunk.

Archive consistency check complete, problems found.

**Comment by ThomasWaldmann** [comment]
Uhoh. :( Was that the latest archive being checked or an older one? Has that archive been checked before?

**Comment by magma1447** [comment]
27/30 repositories are checked after every backup. This particular one is checked the day after it has received backups, due to the backups taking quite some time, and it also receives backups almost hourly. Archives prefixed with full_, like this one, are checked the last 5 (--last 5).

The output doesn't tell me for which archive the errors are. As a side-note, wouldn't it be an improvement for the output to tell that as well?

I ran a manual check with --last 1, it triggers the errors as well.

The repository in this case is my slow repository (#2245), I do not know if it's relevant though. It has passed checks 3 times per week lately.

**Comment by magma1447** [comment]
Yet another today:
----
backup/full_mysqldump.sql: New missing file chunk detected (Byte 21719314622-21720306523). Replacing with all-zero chunk.

Archive consistency check complete, problems found.

**Comment by ThomasWaldmann** [comment]
Something is broken here. I hope we can soon have a b4, just to check if it is related to the remote module somehow.

**Comment by ThomasWaldmann** [comment]
I am shifting this to b5. We'll just check if it still happens after all the other b4 fixes are in place.

**Comment by magma1447** [comment]
A short update. I updated to beta4 on the 28th. Since then I haven't received any errors, yet.
I partly wrote this so it would be easier for myself to keep track of the date when I updated the binary. After 2-3 weeks without errors I would assume it has been solved together with something else.

**Comment by ThomasWaldmann** [comment]
@magma1447 did any errors happen with b4 meanwhile?

**Comment by magma1447** [comment]
@ThomasWaldmann Nothing new. I assume that it's solved by b4 and can be closed.

**Comment by ThomasWaldmann** [comment]
Great.

Not great that we do not know precisely what it was, but if it is gone, guess it is good enough.
