### ISSUE TITLE
Add a --max-lock-wait argument

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#210]
There are times when borg's behavior of waiting infinitely for a lock is not desired.

I might be on the road, at a hotspot, and I want a backup to happen right now, or fail immediately instead of keeping me waiting.  By being able to tell borg not to wait more then 5/10/30/60 seconds for a lock, I can find out quickly whether the backup is going to run, or whether I should consider an alternate backup method for the moment.

Another example is when setting up a new server where multiple cron files from different packages all have their own "borg create" scripts.  They might be scheduled to all run at different times, with an eye towards avoiding schedule conflicts.  Maybe I don't want them to wait for more then 5 or 15 minutes.

Some of this is due to borg over SSH, where the local borg process was killed, but left a stale lock behind.  After which, future borgs start stacking up in a waiting pattern because they can't get the lock.  But in the case of a limited backup window scenario, if there's a long-running borg process going, I may not want to wait more then 15 seconds for mine to start.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/26802395-add-a-max-lock-wait-argument)

**Comment by ThomasWaldmann** [comment]
Maybe we can collect some feedback from all borgbackup users reading this:

what do you think is a good default value for --max-lock-wait?
should it be infinite wait or rather short, like 1s or so?

**Comment by level323** [comment]
I think the default value should either be infinite or very short (e.g. 1 second) or no delay at all. The former is essentially "blocking" and the latter is effectively "non-blocking". Whereas there are clear use cases for either of these defaults, defaulting to some number between these extremes will be very circumstance-specific and likely to be applicable to even fewer people that defaulting to pure blocking or non-blocking operation.

**Comment by tgharold** [comment]
My feeling is that the default should be infinite. It's easier to specify "--max-lock-wait 0" (or some other arbitrarily small number of seconds) then "--max-lock-wait infinity"?

**Comment by ThomasWaldmann** [comment]
True, but otoh the more nice behaviour for interactive use would be to only have a short wait time by default, so one has to type less. For a script, when one wants a looong wait time, one can just give a very large number.

**Comment by tgharold** [comment]
Sure, and allow an "infinite" keyword instead of specifying a very large number?

**Comment by anarcat** [comment]
infinite could be -N...

**Comment by mhubig** [comment]
In my case I came here looking for a known bug after seeing a stalled borg create cronjob waiting forever because of a lockfile. IMHO it's a bit uncommon to have a program waiting forever instead of failing if it can't get hold of a resource ...

So I would also appreciate a `--max-lock-wait` or even better a `--fail-if-lock` flag!

Or maybe it would be even better to change the default behavior to immediately fail if there is a lock present and having a flag to `--wait-for-lock` defaulting to infinit which also can be used with a max wait time like `--wait-for-lock 60s` or `--wait-for-lock "2015-10-11 13:15:01"` ...

**Comment by anarcat** [comment]
agreed: `--fail-if-lock` sounds like a good default, even.

**Comment by ThomasWaldmann** [comment]
@mhubig good suggestion. I'ld also like it that way:

change the default behavior to immediately fail if there is a lock present and having a flag to --wait-for-lock defaulting to infinity which also can be used with a max wait time like --wait-for-lock 60s or --wait-for-lock "2015-10-11 13:15:01" ...

Hopefully that's possible with argparse. ;)

**Comment by anarcat** [comment]
we could have `default=None` on the argument for the "infinity" setting. then for parsing dates and times, that's outside the scope of argparse, IMHO... stackoverflow mentions a time parsing library, using regex or strptime as main options:

http://stackoverflow.com/questions/4628122/how-to-construct-a-timedelta-object-from-a-simple-string

we do have some delta parsing algorithm in `helpers.prune_within()` it seems, which we could factor out...

i would advise against absolute datetime limits, too complicated for nothing - no one will use this.

**Comment by ThomasWaldmann** [comment]
default=None and option to give a timeout in seconds (only), no need for time parsing.

**Comment by anarcat** [comment]
agreed.

**Comment by mhubig** [comment]
:+1:

**Comment by ThomasWaldmann** [comment]
See PR #438. \o/
```
borg create repo::test  data  # will terminate after 1s lock wait time if it can't get the lock
borg create --lock-wait 3600 repo::test data  # will wait for max. 1h
```

The infinite wait version didn't make it, due to arg parsing conflicts:
```
borg create --lock-wait repo::test data  # would try to evaluate "repo::test" for lock wait integer
```

But infinite does only make limited sense anyway. Nobody really wants to wait infinitely, so he can also just give that big integer value he really wants to wait.
