### ISSUE TITLE
Automatically break locks?

### ISSUE THREAD

**Issue by jbms** [borgbackup/borg#2101]
If borg terminates unexpectedly, the lock is left in place, which will prevent future automatic backups from working until the lock is removed.  Automatically issuing the break-lock command would be quite dangerous, but it seems that in the common case that the old lock was made by the same machine, it should be possible to directly check if the process that made it is still alive, and if not, the lock can safely be deleted.  This would likely eliminate the need for break-lock in almost all cases.

**Comment by ThomasWaldmann** [comment]
@jbms we have lock cleanup code at quite some places meanwhile (in borg 1.0), so leftover locks should be less frequently as in older borg versions.

borg 1.1 will have an automated stale lock cleanup IF you assert as admin that your hostnames are unique (and then doing what you also thought about: check if it is same machine, check if process is alive, if not: kill lock).

So, i think this is already implemented, in master branch and 1.1.0beta currently.
