### ISSUE TITLE
Deprecated LZ4 function

### ISSUE THREAD

**Issue by bket** [borgbackup/borg#2103]
While compiling borg 1.0.9 the following warning is given:

`LZ4_compress_limitedOutput’ is deprecated: use LZ4_compress_default() instead
`

The new function LZ4_compress_default() appeared in lz4 r129 (1.7.0).

**Comment by ThomasWaldmann** [comment]
TODO: switch to new function if we do not need to support systems any more that have < 1.7.0.

A version list for the usual linux dists, freebsd, netbsd, openbsd, OS X would help here.

**Comment by ThomasWaldmann** [comment]
Debian 8 "Jessie" has r122. Debian 9 "Stretch" will have r131.

Ubuntu 14.04 "Trusty" has r114. Ubuntu 16.04 "Xenial" has r131.

So, do it in borg >= 1.2?

**Comment by ThomasWaldmann** [comment]
Considering we will require python 3.5 for borg 1.2 (and also likely openssl 1.1), which requires a relatively recent system, we can do above now also.

**Comment by ThomasWaldmann** [comment]
lz4 is too old on travis (ubuntu trusty), we can't do that now.

**Comment by ThomasWaldmann** [comment]
fixed by #3443 and #3456.
