### ISSUE TITLE
It is not clear from the docs when or how often to run borg check

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2105]
I'm starting to use borgbackup and from the docs I couln't figure out when is borg check intended to be executed. Is it something you run when you found a problem? Or periodically? Or after each backup?

**Comment by infectormp** [comment]
That your decision when you want execute check. You can run it when you found a problem, periodically or after each backup.

**Comment by alejandro-perez** [comment]
Isn't there any recommendation at all?

**Comment by enkore** [comment]
No real recommendation. When there is a data problem it's usually the first/easiest diagnostic tool to use (as well as checking system logs, smart etc.). Small repos can be checked more quickly, larger repos and extremely large repos can take a lot of time to fully check (>1 day), so running it more often than once a week or once every couple weeks isn't really practical.

--

Personally: I do backups to some always-on-line disks, these are checked once per week, but I also do backups to off-line disks, which are checked less often (every 10th insertion of a disk, which works out to something like a month or two).

**Comment by alejandro-perez** [comment]
Thanks for the detailed explanation. My repositories are small enough to be checked in less than 1h, so I think I will stick to the weekly idea.
