### ISSUE TITLE
add some tricks for Vagrant

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2108]
https://github.com/pyinstaller/pyinstaller/pull/2415

- some modifyvm commands to get the box booting everywhere (CPU, OS, Virt. Type)
- switching off usb for the OSX machine, so no ext. pack is required
- no itunes updates in the OSX machine (take rather long)

**Comment by enkore** [comment]
> no itunes updates in the OSX machine (take rather long)

Haha this is great :D

**Comment by ThomasWaldmann** [comment]
fixed by #2109.
