### ISSUE TITLE
[Bug?/Question] Compressed vs Original Size

### ISSUE THREAD

**Issue by Stunkymonkey** [borgbackup/borg#2113]
I think borg is the best backup programm for me right now
Thanks for this awesome tool

But I am wondering about one thing, when i make a backup with borgmattic. The Output is like this:
```
------------------------------------------------------------------------------
Archive name: test-2017-01-29T20:59:34.657728
Archive fingerprint: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Time (start): Sun, 2017-01-29 20:59:46
Time (end):   Sun, 2017-01-29 21:02:01
Duration: 2 minutes 14.27 seconds
Number of files: 256837
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              194.98 GB            195.03 GB            130.00 MB
All archives:                1.96 TB              1.96 TB            269.88 GB

                       Unique chunks         Total chunks
Chunk index:                 1669424             12222147
------------------------------------------------------------------------------
```
Is it right, that the compressed size is bigger, then the original one?
Does this make sense?
I am using `borgmattic` with `borg 1.0.9` on `Arch Linux`

**Comment by enkore** [comment]
There are two bytes overhead per chunk minimum (unencrypted repo, no compression); when compression is used this is about ~44 bytes or so. You have ~50 MB overhead which is about the right ballpark with your 256k files.
