### ISSUE TITLE
borg info (or maybe inquire) to get specific pieces of information in a less verbose way  

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2117]
This would be an enhancement or feature request, not a bug.

I would find very useful to be able to get some of the information borg info shows in a less verbose and more direct way. E.g.
* Size of an archive
* Compressed size of a archive
* De-duplicated size of a archive
* Compressed de-duplicated size of an archive
* The same kind of data, but for repositories
* Start time of an archive
* Duration time of an archive
* etc.

Why do I want this? E.g. send me an email when the deduplicated size of an archive just created exceeds 500MB. Or when the total size of the repository exceeds 20GB. 
So far, you can get (part of) this information from the output of the borg info command, but you have to rely on bash and helper programs (e.g. cut, awk) to get the information.

I think that having the possibility of formatting the output of "borg info" as it is done with "borg list" using place holders (e.g. {{size}}, {{csize}}..) would be beneficial for some use cases.

**Comment by enkore** [comment]
#1812?

**Comment by alejandro-perez** [comment]
Yes, seems pretty similar to what I want. I'll wait, there is no vital to me.

Thanks!
