### ISSUE TITLE
docs: use "restrict" option for authorized_keys

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2121]
it is preferable over specifying single restrictions as it will also include all future restrictions.

but: it requires openssh >=7.1, so we have to wait with that docs change until we can expect most people have that.

**Comment by ThomasWaldmann** [comment]
[restrict.diff.txt](https://github.com/borgbackup/borg/files/751735/restrict.diff.txt)

**Comment by enkore** [comment]
removing later labe, @rugk's suggestion is good (use restrict, adding a note about it)
