### ISSUE TITLE
docs: borg list: guaranteed hashes

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2123]
`hashlib.algorithms_guaranteed` was expanded with Python 3.6, so we should keep in mind to build the docs with 3.4, since that is our baseline.

```diff
@@ -84,14 +84,22 @@ The following keys are available for --format:
  - isomtime
  - isoctime
  - isoatime
 
+ - blake2b
+ - blake2s
  - md5
  - sha1
  - sha224
  - sha256
  - sha384
+ - sha3_224
+ - sha3_256
+ - sha3_384
+ - sha3_512
  - sha512
+ - shake_128
+ - shake_256
 
  - archiveid
  - archivename
  - extra: prepends {source} with " -> " for soft links and " link to " for hard links
```

**Comment by ThomasWaldmann** [comment]
... or document that these are only available on 3.6+.

**Comment by enkore** [comment]
"build the docs" ~ run build_usage... not actually building them. That one doesn't matter.

I think it would be sufficient to just not have them in the official docs. The local --help will tell what's exactly available on the local system.

**Comment by ThomasWaldmann** [comment]
ok, so the real change needed is in the development docs "how to make a release".
