### ISSUE TITLE
disaster recovery with rear

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2126]
somehow outside of borg scope, but maybe still worth documenting:

- point to rear for disaster recovery
- run rear before creating backups with borg and just include the (iso?) image created by rear in the backup
- in disaster case, extract iso from backup, create rescue media, restore your stuff

**Comment by zuzzas** [comment]
Not being offensive, but it's spelt "disaster" in English.

**Comment by enkore** [comment]
Corrected

**Comment by ThomasWaldmann** [comment]
Btw, I personally do not use R.E.A.R (yet?), so some feedback of somebody who actually does and actually has tried disaster recovery would be interesting. Or even a PR for docs.

**Comment by kasimon** [comment]
We may be implementing this in the near future, I will see if I can come up with a PR afterwards.

**Comment by ThomasWaldmann** [comment]
@kasimon that would be great. Guess we do not need much docs about it, considering REAR has its own docs and we do not want to duplicate them. So, just some hints and pointers (see ideas in previous comment) should be enough.

**Comment by bpereto** [comment]
We use REAR to restore physical servers in a disaster case (in combination with a tape library).

to use rear to restore stuff from borg it must be implemented by rear, which somebody had done:
https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/borg-example.conf

rear with borg requires to include the passphrase in the ISO, therefore its required to store the iso securely (in borg or elswhere).

**Comment by milkey-mouse** [comment]
Looks like they already have a pretty detailed [guide](https://github.com/rear/rear/blob/fa77c9248b5f11008d6951fa0b2da3e7f43639cd/doc/user-guide/04-scenarios.adoc#bootable-iso-with-borg) in the REAR docs. Should we just point to it in our docs, or maybe reference it in [borgbackup/community](https://github.com/borgbackup/community)?

**Comment by ThomasWaldmann** [comment]
Link from community repo sounds good.
