### ISSUE TITLE
use pyinstaller to create standalone executables

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#213]
pyinstaller has a 3.0.dev2 pre-release now on PyPi (for some platforms git repo code is needed).

```
 . env/bin/activate
cd borg
pip install -e .
pip install 'pyinstaller==3.0.dev2'
pyinstaller -F -n borg-PLATFORM --hidden-import=logging.config borg/__main__.py
```
See issue #214 for latest binaries.

**Comment by ThomasWaldmann** [comment]
linux: worked for 32 and 64bit
mac os x: currently broken build, no python dynlib there
freebsd: currently broken build, bootloader does not compile, python dynlib is not found
netbsd/openbsd: no support in pyinstaller yet

**Comment by level323** [comment]
@ThomasWaldmann Creating a standalone binary (or, more generally, redistributable application files) has great value to me (and, I suspect, to others). 

I had actually just begun hacking the Vagrantfile from the borg code (#196) with a plan of using Vagrant to build a redistributable. My initial plan was to automate a process I had already documented to build python from source in a borg-specific directory under /usr/local/, build borg in that dedicated python environment, ensure it passes the tests, and deliver a tarball of the /usr/local/ borg install.

There is obvious overlap with what you're trying with pyinstaller. pyinstaller will produce nice tidy single-file executables which are also much smaller (~6MB for pyinstaller vs ~60MB for my method). However, pyinstaller seems quite bleeding edge (at least in terms of python 3 support) and, according to your comments, is only working on linux presently.

If there is anyone interested in my approach I'm happy to keep you posted.

Naturally, I'm also very interested in the pyinstaller approach in the longer term. @ThomasWaldmann do you have a script or any special setup for building the borg executable with pyinstaller or is it just straightforward?

**Comment by ThomasWaldmann** [comment]
> @ThomasWaldmann <https://github.com/ThomasWaldmann> Creating a
> standalone binary (or, more generally, redistributable application
> files) has great value to me (and, I suspect, to others).

Ah, good that it is useful.

I thought so, that not everybody likes the sometimes painful way to
install python stuff.

> I had actually just begun hacking the Vagrantfile from the borg code
> (#196 <https://github.com/borgbackup/borg/issues/196>) with a plan of
> using Vagrant to build a redistributable. My initial plan was to
> automate a process I had already documented to build python from source
> in a borg-specific directory under /usr/local/, build borg in that
> dedicated python environment, ensure it passes the tests, and deliver a
> tarball of the /usr/local/ borg install.

Ah, interesting approach. You need to install quite a lot there to make
it complete (openssl, liblz4, python, ...).

> There is obvious overlap with what you're trying with pyinstaller.
> pyinstaller will produce nice tidy single-file executables which are
> also much smaller (~6MB for pyinstaller vs ~60MB for my method).
> However, pyinstaller seems quite bleeding edge (at least in terms of
> python 3 support) and, according to your comments, is only working on
> linux presently.

Yes and no. They are working on that python3 branch since quite a while,
so although it is still in pre-release state it is not that new.

Linux seems to work ok.

But the non-linux platforms seem to be not yet fully working, sometimes
due to pyinstaller3, sometimes due to the python on that platform not
bringing a dynamic libpython with it.

> If there is anyone interested in my approach I'm happy to keep you posted.

In case we run into issues, yours sounds like a "do it all yourself"
alternative. Quite a lot of work though.

> Naturally, I'm also very interested in the pyinstaller approach in the
> longer term. @ThomasWaldmann <https://github.com/ThomasWaldmann> do you
> have a script or any special setup for building the borg executable with
> pyinstaller or is it just straightforward?

(if it works at all) it is quite easy:

. env/bin/activate
pip install -e .
pip install 'pyinstaller==3.0.dev2'
pyinstaller -F -n borg-PLATFORM borg/__main__.py


-- 
Waldmann EDV Systeme/Service GbR
Gerhard Waldmann, Thomas Waldmann
Pleidelsheimer Str. 25
74321 Bietigheim-Bissingen

Weitere Infos siehe: http://waldmann-edv.de/

GPG Fingerprint: 6D5B EF9A DD20 7580 5747  B70F 9F88 FB52 FAF7 B393
Encrypted E-Mail is preferred / Verschluesselte E-Mail wird bevorzugt.

**Comment by JuergenBS** [comment]
Standalone binaries would be very helpful. I am planning to use borg on a debian wheezy system and with an official standalone binary I can throw away my half-ready automatic python/borg install stuff.

**Comment by ThomasWaldmann** [comment]
@JuergenBS see #214, should work on wheezy.

**Comment by JuergenBS** [comment]
@ThomasWaldmann tried the binaries a few seconds ago:
I'm using a Debian Wheezy amd64 system and unfortunately 
1) the precise variant is 32bit-only:
root@host:~# ldd ./borg-precise32
        linux-gate.so.1 =>  (0xf7757000)
        libdl.so.2 => /lib32/libdl.so.2 (0xf7746000)
        libz.so.1 => not found
        libc.so.6 => /lib32/libc.so.6 (0xf75e0000)
        /lib/ld-linux.so.2 (0xf775a000)
2) the trusty variant requires glibc 2.14 but the system only provides 2.13:
root@host:~# ldd ./borg-trusty64
        linux-vdso.so.1 =>  (0x00007fff5e798000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe32e73d000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe32e525000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe32e198000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe32e94e000)
root@host:~# ./borg-trusty64
./borg-trusty64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIIzBbOL/libz.so.1)

I would assume that the precise version requires only glibc 2.13. Any reason why not all single-binaries are built for precise/wheezy? They should also run on trusty/jessie/..., shouldn't they?

**Comment by level323** [comment]
FYI I'm hacking the borg `Vagrantfile` (using the `wheezy32` provisioner as a basis) to build environments for producing PyInstaller-derived standalone binaries for 32 bit wheezy.

All that's required is to manually build/install python 3.4.x in that environment.

Once that's working it should be a snap to do the same for 64 bit wheezy.

Getting close. Will post once working.

**Comment by ThomasWaldmann** [comment]
@level323 didn't the binary built on trusty32 work on wheezy32? It is supposed to work on all 32bit linux dists.

**Comment by level323** [comment]
@TW and @JuergenBS I can confirm that the precise32 borg binary in #214 doesn't work on 32 bit wheezy. Error thrown is:
```
Error loading Python lib '/tmp/_MEIdutbnc/libpython3.4m.so.1.0': /lib/i386-linux-gnu/i686/cmov/libc.so.6: version `GLIBC_2.15' not found (required by /tmp/_MEIdutbnc/libpython3.4m.so.1.0)
```
Seems to be the glibc issue you flagged in your earlier comment, @TW.

Because I need a borg 32 bit binary for wheezy 32bit to scratch my own itch, I'll persist with hacking the Vagrantfile to achieve this, and report the outcome here, in due course.

Also just FWIW for my own needs I will prefer to build the standalone with the `-D` flag rather than `-F` because the single-file executable has some side effects due to the fact that it actually expands itself to `/tmp` on each invocation.

I'm dreaming of a grand plan to modify the Vagrantfile to automate building of the standalones/conduct tests/etc, but that requires I bone up on Ruby and Vagrant more deeply, so it may take a little while ;-)

**Comment by ThomasWaldmann** [comment]
@level323 ok, so it seems we need to build the binaries on a linux with rather old glibc, but not too old python (I'ld really want 3.4+ for that - I even tried 3.5 for the faster os.walk, but pyinstaller did not support 3.5 at that time).

Please open a PR with your Vagrantfile changes so it can be reviewed. I prefer incremental small changes.

What "side effects" for the single-file do you mean? I'ld rather prefer a single-file distribution as it is easier to sign / checksum and to make sure people have exactly what they are supposed to have (no files missing).

**Comment by ThomasWaldmann** [comment]
@level323 maybe using pyenv not only on OS X, but also on the other platforms could help?

**Comment by level323** [comment]
@ThomasWaldmann I have the Vagrantfile working to produce Wheezy 32 bit pyinstaller standalones under Python 3.4.3. I need to tidy up my hacks to the Vagrantfile now, then will create a PR.

Re your comments on PYTHON_CONFIGURE_OPTS="--enable-shared": `TW_coding_fu > level323_coding_fu` :-) I did encounter this issue but after digging around, I solved it via `./configure --enable-shared` when compiling Python 3.4.3. I assume this is equivalent to your suggestion.

The "side effects" of the single standalone are described here: https://pythonhosted.org/PyInstaller/#how-the-one-file-program-works

Specifically (amphasis mine):

1. After creating the temporary folder, the bootloader proceeds exactly as for the one-folder bundle, in the context of the temporary folder. When the bundled code terminates, it deletes the temporary folder. (Note that in Linux and related systems, **it is possible to mount the /tmp folder with a "no-execution" option. That option is not compatible with a PyInstaller one-file bundle.** It needs to execute code out of /tmp.)

2. **The _MEIxxxxxx folder is not removed if the program crashes or is killed** (kill -9 on Unix, killed by the Task Manager on Windows, "Force Quit" on Mac OS). Thus if your app crashes frequently, your users will lose disk space to multiple _MEIxxxxxx temporary folders.

Point 2 is more critical to me, as I envisage using borg on a backup server running continuously and point 2 might cause me issues in the longer term (*might*).

I don't mind at all if you only want to publish the single-file standalone. It's very easy for me to generate the directory standalone via the Vagrantfile if ever I need to.

I got a little over-excited working on the Vagrantfile yesterday, at the expense of my employer. Can't spend so much time on it today but hope to squeeze some time here and there to clean up the Vagrantfile and raise the PR.

**Comment by ThomasWaldmann** [comment]
@level323 I'ld like to release 0.26.1 this weekend - can you publish what you have right now so we avoid doing double work?

**Comment by ThomasWaldmann** [comment]
Here are some binaries that should work on centos 6+, debian 7+, ubuntu 12.04+ (and other linuxes that have at least glibc 2.12):

https://paste.thinkmo.de/3Yw2nVTq#borgbackup-0.26.1-pre1.lst

Please test and give feedback.

The issue with the "queue" ImportError when using borg mount should be fixed also.

**Comment by lfam** [comment]
Are there any signatures for these new binaries?

**Comment by ThomasWaldmann** [comment]
No, i didn't sign yet. But the sha256 it shows on the pastebin page is computed at upload time.

**Comment by lfam** [comment]
Ah, I see that you own the domain and are an author of bepasty. I guess that will do.

**Comment by JuergenBS** [comment]
@ThomasWaldmann: I just tested the binary borg-linux64 in a VM (Univention Corporate Server 4.0 that is based on Debian Wheezy with glibc 2.13): init, create (lz4, lzma, zlib), extract (verified via diff), prune, delete. Works like a charm. GREAT! Thanks a lot. This simplifies the usage of borg on different systems A LOT!
Btw: I would also prefer if you always add a GPG signature for all files. Even for prereleases.

**Comment by level323** [comment]
@TW sorry I am away this weekend and didn't bring my computer. Will post my
Vagrantfile when I get back

**Comment by ThomasWaldmann** [comment]
@level323 btw, about single-file vs. directory: as I said, I'ld like to go the single-file way. But I guess everybody who wants the directory way could just copy the temp. directory while borg is running?

**Comment by ThomasWaldmann** [comment]
Looks like we have a working binary build process based on pyinstaller (for supported platforms, which are less than we support for source-code based installs, but that needs to be fixed in pyinstaller). Closing.
