### ISSUE TITLE
Please add option --include and --include-from

### ISSUE THREAD

**Issue by jgscha** [borgbackup/borg#2131]
Please add for command "create" options --include and --include-from analogous --exclude and --exclude-from. 
File matching for includes should be considered first (or priority is configurable or priority in order of call arguments).
This would allow defining easier file selection rules, for example
  --include "keep.xyz" --exclude "*.xyz"

**Comment by enkore** [comment]
#1406 -> #1971

**Comment by wolfpackmars2** [comment]
Regarding this, since 'pattern' options were added, perhaps 'exclude' options should be eventually deprecated. `exclude` implies an inverse `include` option.

If not deprecated, adding `include` options maybe not be as difficult if they can piggy-back on some of the code implemented to handle the pattern matching operations.  Include/exclude could be implemented as aliases to functionality provided by `pattern*`.

I haven't looked into the details of implementing this - wanted to get some additional feedback first.

@ThomasWaldmann

**Comment by ThomasWaldmann** [comment]
I also had the idea a while ago to add ``include`` as a complement to ``exclude``, but it was somehow considered as superfluous in the end.

Not sure if discussion was in a ticket here or on IRC.

**Comment by wolfpackmars2** [comment]
I think it would be easiest to begin deprecating the exclude options.  However, I will review the code and see how hard it will be to refactor `include/exclude` to essentially be aliases of functionality provided by the pattern options. By combining the functionality of these three options would make the code more maintainable, reduce confusion, and give users more options WRT handling these situations.

`--include` and `--include-from`
Uses the same code provided by the `pattern*` options, except any lines not preceded by an explicit *+* or *-* would implicitly be handled as though they were preceded by *-*.

`--exclude` and `--exclude-from`
Same as above, but ambiguous lines would be handled as though they were preceded by *+*.

When the include/exclude options are used, data will be passed through a function to add the proper operator to any ambiguous lines, and then passed along to the "pattern*" functions.  This would also *not* break backwards compatibility.

**Comment by jgscha** [comment]
I think deprecating the exclude options is not a good idea. Too dangerous forgetting to extend include pattern when later adding new files in tree and using only includes. Mixing include amd exclude is the best for flexibilty.
I want show a simple example:

_include /boot/grub/*.cfg                                                                                 
exclude /boot/grub/*                                                                                     
include /boot/ubuntu*/*                                                                                  
exclude /boot/lost+found/                                                                                
exclude /boot/\*/\*.c32                                                                                   
exclude /boot/\*/\*.iso
...
include /boot/\*/*_

I think such a sequence gives maximal flexibility and security not to forget important files and exclude recoverable files.

The algorithm for selection is easy:

`for  each file_or_directory`
`.  for each ordered pattern_rule`
`..  if  Matched(file, rule)`
`....      if include DoBackup(file)`
`....     next file_or_directory`
`. DoDefault(file)`

**Comment by wolfpackmars2** [comment]
I think it would be ideal to keep exclude and add the include option. Alternatively, your example can use the pattern or patterns-from options.

Patterns-from.lst
```+ /boot/grub/*.cfg
- /boot/grub/*
+ /boot/ubuntu*/*
- /boot/lost+found/
- /boot/*/*.c32
- /boot/*/*.iso
...
+ /boot/*/*
```

or command line:
```borg --pattern +/boot/grub/*.cfg --pattern -/boot/grub/*```
Etc.
