### ISSUE TITLE
xxRepo "is not a valid repository. Check repo config"

### ISSUE THREAD

**Issue by andrewufrank** [borgbackup/borg#2132]
when i remounted a disk with a repository i get this error message. i cannot find any hint in the documentation what this message indicates and what actions can be taken. the same error message is returned for `borg list xxRepo` or `borg check xxRepo` with or without `--repair`. 
when i looked at the data directory of the repository, i found that it has directories from 1 to 13, but 9 was missing. could i have inadvertently deleted a directory? 

thank you for the help!
andrew

**Comment by ThomasWaldmann** [comment]
is that a borg repo (or an old repo made by attic)?
read / search permissions?
is there a "config" file? what's in it?

**Comment by enkore** [comment]
What files are there in the repository directory? There should be a `config` file and a `README` file at least.

If there is no config file and you use repokey/migrate-to-repokey (from attic), and no backup of the key/config (`borg key export`) then you have a problem (this file contains the key).

If there is no config file and you don't use encryption or use keyfile mode, then it can be recreated:

1. If keyfile mode, go to ~/.config/borg/keys/ and find the key file (named with the repository directory name). The first line is `BORG_KEY <some hex>`.

2. Create `config` file with contents:

   ```
   [repository]
   version = 1
   segments_per_dir = 10000 
   max_segment_size = 5242880
   append_only = 0
   id = <some hex copied from key file>
   ```

   If you don't use encryption, you can just make an `id` up.

3. Create `README` file with contents `This is a Borg repository`

**Comment by andrewufrank** [comment]
thank you - this sounds promising. i will try first with a small example repository to gain some insight in the details of your recommendation.
(additional information: it is a new repository with no encryption - only local network).

**Comment by andrewufrank** [comment]
i experimented on a different repository following your suggestions and it worked. thank you!

now on this (big) one, i get pat the error message above when i do list, but then in get 
`repository has no manifest`
what is the meaning of this? 

i run check now...

**Comment by ThomasWaldmann** [comment]
@andrewufrank the manifest the topmost data structure in the repo and contains e.g. the directory of archives. it should be there. if it is not, borg check --repair can usually fix this (assuming that only the manifest is missing and most other stuff is still there).

**Comment by ThomasWaldmann** [comment]
@andrewufrank btw, it is unusual to lose manifest, config, etc. - is your disk hardware or filesystem maybe defective? check smartctl -a /dev/sdX and maybe do a fsck on the filesystem.

**Comment by andrewufrank** [comment]
i assume that i know how i created the problem (rm -r * ...(:-)). human error is a very common cause of trouble!
i am new to borg and it is an interesting excersize to see how resiliant the repositories are. the check (without --repair) is still running - it was ok till 80%. i will report about the result.

**Comment by ThomasWaldmann** [comment]
@andrewufrank if the manifest is not found, it will read through the whole repo and hunt for archives, to reconstruct the manifest.

due to deduplication, there is not much redundancy in a borg repo, but some stuff can be rebuilt.

the manifest is the last thing written to the repo before a commit, so it is in the last real segment file.
most values in the config are just configuration parameters, except if you use repokey encryption, then there is also the key (and you must have a backup of that to not lose it).

**Comment by andrewufrank** [comment]
i can report that the repair worked - the repository can be read and mounted. it is hard to see which files are affected. the repair reported all affected files, but they ware so many that i lost part of the list - perhaps an automatic log should be enforced, the output is not expected and in my case was VERY long.  (and i it may be a good idea to warn users that `--repair` takes for large repositories a very long time  - 20 hours in my case).

most important: what is left can be used! great work!

if i add new files to the repositories, they will be stored normally? 
is it correct that the missing data is replaced by one single zero block, not duplicated? 

regarding the manifest: do yo write this each time after a commit at the end or is there only one single updated manifest stored? it is clear that there is very little redundancy in the stored data but it seems there is some redundancy in the metadata, such that files can be reconstructed (at least in my case). 

to make it more difficult to loose the config file: could it be made non-writable, to produce an extra warning before it can be deleted? 

all told: i am very impressed with borg backup!
andrew

**Comment by enkore** [comment]
> stay in same file system, do not cross mount points

yes

> is it correct that the missing data is replaced by one single zero block, not duplicated?

yup, same deduplication as always

> regarding the manifest: do you write this each time after a commit at the end or is there only one single updated manifest stored? it is clear that there is very little redundancy in the stored data but it seems there is some redundancy in the metadata, such that files can be reconstructed (at least in my case).

The data in the repository is a transaction log that doesn't do random writes - the manifest is moved to a different file in every operation. (Data is deleted by moving used data from files to new files, then deleting the old files - we call 'em segments)
