### ISSUE TITLE
borg mount only a selected PATH (as in extract)

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2138]
Given the fairly amount of CPU power needed for the "versions" option (which I found utterly useful), I'd like to ask for restrict the mount to just a specific PATH. IMO, the use of the versions option typically means you are looking for the versions of a (some) specific (set of) file(s).

E.g. OMG! Someone, at some time, modified "Documents/Important/analysis.odt". I need to recover the previous version (whenever it was). I don't want to mount all the (potentially huge) directory tree with all the versions. Just that file/directory.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/41830614-borg-mount-only-a-selected-path-as-in-extract)

**Comment by ThomasWaldmann** [comment]
@alejandro-perez sounds useful.

Not sure if it would help much with the processing time needed because to find all files below some specific path, borg still has to read through the whole archives. But at least it would save some memory, as all non-matching fs object would not have to get created in memory.

Another idea (not sure if already implemented or still todo) is to only process a subset of all archives (like last 10, all with some specific prefix, ...) and not all of them.

**Comment by alejandro-perez** [comment]
It is always faster to do not create objects, etc (maybe not breathtaking improvement, but I guess it should be at least noticeable). 
Regarding the subset of archives, I've seen that beta version does allow to select a specific prefix with -P (1.0.9 does not).

**Comment by alejandro-perez** [comment]
Note when I mentioned performance imporvements I meant with the "-o versions" option, which is more CPU intensive that just mounting the archives as they are.

**Comment by enkore** [comment]
If it doesn't already, borg-mount should do the standard set of --last/--first/--prefix options that a bunch of other commands also have implemented in common.

**Comment by ThomasWaldmann** [comment]
since borg 1.1, borg mount already supports --first, --last, --prefix and --glob-archives.

**Comment by ThomasWaldmann** [comment]
Notes:
- hardlink_masters potentially not being present in the selected items complicates things, as usual. code for this exists for e.g. do_extract.
- to check: does borg mount currently hide part files?

**Comment by alejandro-perez** [comment]
> since borg 1.1, borg mount already supports --first, --last, --prefix and --glob-archives to only work on a subset of all archives.

This allows you to select a number of archives, but I was thinking of a set of files rather than archives.
Use case: I want to see all the versions of just one file in home/alex/a_file_that_changes_a_lot.odt, I'd rather not process the whole repository.

**Comment by alejandro-perez** [comment]
@ThomasWaldmann Thanks!

**Comment by alejandro-perez** [comment]
I've made a contribution of $20. I wanted to make a bounty for this issue, but the issue did not show up in the list of issues at BountySource. It is not much, I know, but I hope that helps.

**Comment by ThomasWaldmann** [comment]
@alejandro-perez thanks!

Bountysource is sometimes a bit weird. But finding issues mostly works if one puts the github issue url into the bountysource search box (I already did that for this issue).
