### ISSUE TITLE
limit msgpack.Unpacker

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2139]
The Unpacker in the rpc code (borg serve, RemoteRepository, see remote.py) currently operates without limits. Thus a evil client or evil server could send packs that unpack to huge amounts of data and thus cause a DoS via excessive memory consumption.

The danger by this is not very high though:

- attacking a server: borg operates via a ssh and a client usually needs a authorized ssh key or username/password to connect to a server. thus the server knows which credentials are used and could just revoke access for the evil client's account / the key.

- attacking a client: same thing: you know the server who is attacking you because you connected to it. also, if a server were hacked and wants that you can't use borg (to access backups, to create backups), there are easier ways to do that than rpc with evil data.

To fix this, we can set limits on the Unpacker (requires msgpack >= 0.4.6, but we already require that since quite a while anyway).

https://github.com/msgpack/msgpack-python/blob/0.4.6/msgpack/fallback.py#L143

But: currently we have a problem with the archive objects (pointed to via the archiveid): in the past, these could grow bigger than MAX_CHUNK_SIZE and old archive objects could exist without any specific limit in size - thus we can't define a limit for that kind of data. see #1473.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/41861104-limit-msgpack-unpacker)

**Comment by enkore** [comment]
There are multiple different limits we can define:

- max_buffer_size (int) – Limits size of data waiting unpacked. 0 means system’s INT_MAX (default). Raises BufferFull exception when it is insufficient. You should set this parameter when unpacking data from untrusted source.
- max_str_len (int) – Limits max length of str. (default: 2**31-1)
- max_bin_len (int) – Limits max length of bin. (default: 2**31-1)
- max_array_len (int) – Limits max length of array. (default: 2**31-1)
- max_map_len (int) – Limits max length of map. (default: 2**31-1)

For example, we can already restrict max_array_len and max_map_len to fairly low values safely.

**Comment by ThomasWaldmann** [comment]
Yes, we can start doing that, but until we can give an (always working under normal conditions) upper limit for the binary data length, there is still an attack vector. See my previous comment.

**Comment by enkore** [comment]
Don't we still validate MAX_OBJECT_SIZE (20 MiB)?

**Comment by ThomasWaldmann** [comment]
IIRC only when writing?

**Comment by enkore** [comment]
We should also use a limited unpacker for the outer key packing (KeyfileKeyBase.decrypt_key_file).

**Comment by ThomasWaldmann** [comment]
@enkore yes, I'll look at that. separate ticket, this one is about rpc.
