### ISSUE TITLE
single-file binaries (made with PyInstaller)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#214]
Here are some single-file binaries made using pyinstaller:

https://github.com/borgbackup/borg/releases

Please read the README.txt there.

**Comment by pguth** [comment]
**To check the GPG signature** download both the binary and the `*.asc` file and then on the shell type e.g.: `gpg --verify borg-trusty64.asc borg-trusty64`

**Comment by ThomasWaldmann** [comment]
Note:
- the linux binaries require that your (g)libc is same or newer than the one used for building the binaries, see #213 .
- maybe similar restrictions apply to the *BSD / Mac OS X binaries
- borg mount might not work for some binaries, see #218

**Comment by anarcat** [comment]
adding this as a target for 0.27, i think this is an essential aspect for the project, and we should ship it along with the rest!

can the binaries be shipped on pypi? where else if not?

**Comment by ThomasWaldmann** [comment]
Yes, I'll make new pyinstaller/debian7-based binaries for 0.27.
Actually that is the main reason I want to do a early 0.27 release and shifted some stuff to 0.28.

No, PyPi is not possible, I'll just publish a link to them here in this ticket.

**Comment by anarcat** [comment]
it would be nice to have a "trusted" location to publish those binaries, or at least they should be signed... having them on some pastebin site doesn't seem really reliable... how about [github releases](https://help.github.com/articles/about-releases/) ([tutorial](https://help.github.com/articles/creating-releases/))?

**Comment by ThomasWaldmann** [comment]
good idea, I did that for 0.26.1 to test it, 0.27 will come soon.

**Comment by ThomasWaldmann** [comment]
TODO: point all links directly to github releases (not to this issue).

**Comment by anarcat** [comment]
the README.txt in the github release has the following header after redirection to Amazon:

```
Content-Type:application/octet-stream
```

Which makes the file unreadable in the browser. Maybe it would be better to put its content directly in the release page?

**Comment by anarcat** [comment]
moving this to #260...

**Comment by ThomasWaldmann** [comment]
move all you need from here to other tickets, I am closing this one now as my "TODO" is done.

**Comment by ThomasWaldmann** [comment]
TODO done here:
https://github.com/borgbackup/borg/commit/04ac82d3e2e768f9d354013614000f7e7feb43f4
