### ISSUE TITLE
Add file to existing archive?

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2143]
Hi,

I was wondering if there is a way to add a file to an existing archive. The rationale is as follows:
* I create an archive using borg create REPOSITORY::ARCHIVE PATHS. Log output is captured into a LOG_FILE.
* I want to include LOG_FILE into REPOSITORY::ARCHIVE (to keep a backup of backup log files).

I know that I can do this by just creating an intermediate ARCHIVE_TMP first, then repeat the borg create (which this time has the complete log file) to ARCHIVE. And finally deleting ARCHIVE_TMP. But I was wondering if I can do this with borg recreate (it seems that you cannot include files not already included into the file list).

Thanks for this awesome tool!

**Comment by ThomasWaldmann** [comment]
You can't do that with borg (yet?).

How about just creating an additional REPOSITORY::ARCHIVE_log?

**Comment by alejandro-perez** [comment]
> You can't do that with borg (yet?).
>
> How about just creating an additional REPOSITORY::ARCHIVE_log?
>

Yep, probably that's the best approach. Don't know if it makes sense 
keeping all the logs  (i.e. having a multiple .borg_logs/ARCHIVE.log 
files) or just the one associated to the current backup (i.e. .borg_log 
file).

**Comment by ThomasWaldmann** [comment]
closing this: there is an easy workaround.
