### ISSUE TITLE
Select between GiB and GB

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2144]
Hi,

I've seen that borg generates output using KB/MB/GB (international units). However, some of us prefer using GiB (binary units), as we are more used to it. Is is possible to adjust this via a ENV variable or something?

Thanks

**Comment by ThomasWaldmann** [comment]
not possible yet. in general a good idea, but might be problematic for a few places when there is little space in the layout and every addtl. character might be problematic. E.g. in the progress display.

**Comment by alejandro-perez** [comment]
> not possible yet. in general a good idea, but might be problematic for 
> a few places when there is little space in the layout and every addtl. 
> character might be problematic. E.g. in the progress display.
>

I think I might have an idea for that. You could copy "df" behaviour. 
When used with "-h" it gives summaries in binary units, and when used 
with "-H" in international units. Now, it uses G for Gbytes, M for 
Mbytes, K for Kbytes, regardless they are Gigabytes or Gigibytes. And 
you save one character in all the cases :).

**Comment by greenpasta** [comment]
> I think I might have an idea for that. You could copy "df" behaviour.
When used with "-h" it gives summaries in binary units, and when used
with "-H" in international units. Now, it uses G for Gbytes, M for
Mbytes, K for Kbytes, regardless they are Gigabytes or Gigibytes. And
you save one character in all the cases :).

+1

**Comment by ThomasWaldmann** [comment]
Mixing stuff up is the worst. Also, this is standardized and we just follow the standards:

https://en.wikipedia.org/wiki/Binary_prefix

**Comment by alejandro-perez** [comment]
I agree. For the time being I've changed my mind. I prefer robust SW that makes one thing and makes it right rather than thousands of options that make the code difficult to maintain.

Also the JSON output in bytes already provides me with the raw information so I can get it in MiB, MB, or even stones.

Thanks!

**Comment by ThomasWaldmann** [comment]
Note: somebody added `--iec` option a while ago.
