### ISSUE TITLE
borg diff not visible in docs navigation

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2147]
http://borgbackup.readthedocs.io/en/latest/usage.html

**Comment by enkore** [comment]
The changelog only has 1.0.x releases - looks like a docs build of 1.0-maint. Perhaps it can be tweaked so that latest==only master?

**Comment by ThomasWaldmann** [comment]
oh, right. that looks better: http://borgbackup.readthedocs.io/en/1.1.0b3/usage.html

branch was still set to "upgrade-sphinx", not master, another thing I forgot to revert after my experiment with upgrading sphinx.
