### ISSUE TITLE
Problem backup changed files without new timestamp

### ISSUE THREAD

**Issue by jgscha** [borgbackup/borg#2151]
After an initial backup changed files are not updated again by incremental backup if file timestamp is not changed (for example crypted file containers or files used as image for loop device). I assume this is done for performance reasons.
Please add an option ("--rehash", "--ignore-time" or other) for possibilty to force reading and hashing such files again.

**Comment by enkore** [comment]
--no-files-cache

**Comment by jgscha** [comment]
Thank you, with --no-files-cache it works. 
I didn't associate the meaning of this option with my problem. Perhaps you can append in the doc such a example, with comment why using the option.
