### ISSUE TITLE
Argument list too long error probably due to xattrs

### ISSUE THREAD

**Issue by cluelesscoder** [borgbackup/borg#2161]
Reported and discussed this in IRC. Data which was originally on Windows was transferred to OSX, and from there sent to a Linux Ubuntu 14.04 machine with ext4 filesystem where the errors happened upon typing borg extract backup::<repo_name>

See log on pastebin: http://rn0.me/show/QOGX3zmqQDB2f8AMb3dD/

Seems like it has something to do with the icon files; checked the xattrs there. Note this doesn't happen when running it on OSX.

xattrs:
```
ls -l -@ google_drive/Archive/Something/Something_Finance/Monthly\ financials/Icon?
-rw-r--r--@ 1 cluelesscoder  staff  0 Feb 14 12:48 google_drive/Archive/Something/Something_Finance/Monthly financials/Icon?
	com.apple.FinderInfo	32
	com.apple.ResourceFork	340647
```

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/42034922-argument-list-too-long-error-probably-due-to-xattrs)

**Comment by enkore** [comment]
Proposed solution: When setting an xattr upon extraction results in E2BIG, just print a warning.

**Comment by ThomasWaldmann** [comment]
Print a warning, continue with other xattrs of same file, and the remaining files in the restore data set.
Also, exit with warning rc.

**Comment by Abogical** [comment]
I'm working on this, However I'd like to have a repo with big xattrs for testing.

**Comment by Abogical** [comment]
@enkore I'm sorry, but were you working on this?

**Comment by ThomasWaldmann** [comment]
@Abogical maybe easiest way to generate a repo with files with too big xattrs is to not read them from the filesystem, but synthetically create such an archive item.

**Comment by enkore** [comment]
There is a regression test about the Attic 0.13 ACL bug that you can borrow code from that does this.
