### ISSUE TITLE
Add new key "dsize" for "borg list --format"

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2164]
Hi, in the keys for the --format argument you have "size, csize, num_chunks and unique_chunks". Would it be difficult to have a "dsize" that indicates the amount of deduplicated size (and perhaps a cdsize, the compressed deduplicated size). That way, I know EXACTLY, where the 1,41GB of deduplicated (compressed) size of my archive are.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/42062772-add-new-key-dsize-for-borg-list-format)

**Comment by ThomasWaldmann** [comment]
Good idea. Let's choose a name first:
- dsize (like deduplicated size) or unique_size (sum of all chunk sizes of unique chunks, chunks that are only used by this file)
- cdsize / dcsize (deduplicated compressed size) or unique_csize (sum of all chunk csizes of unique chunks...)

**Comment by alejandro-perez** [comment]
To be consistent with the other *size keys, I'd go with the shorter versions. Besides, long format strings would be less long :)

**Comment by enkore** [comment]
- dsize / usize  (the latter is used somewhere in the stats code already iirc)
- psize

  proportional size, of course! csize / refcount.

**Comment by alejandro-perez** [comment]
This is just beautiful, thanks:
```
List of the 20 most relevant files in the archive:
borg list REPO::ARVHIVE --format "{size:>10} {csize:>10} {dcsize:>10} {path}{NL}" | sort -hk3 | tail -n 20
```
This is exactly what I wanted to execute after my daily backups, because sometimes you don't know where those 674MB came from :)

**Comment by ThomasWaldmann** [comment]
@Abogical now claim the bounty. :)
