### ISSUE TITLE
borg init repo -> unencrypted repo

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2165]
Only applies to master branch (borg 1.1beta).

When blake2b was introduced, we removed the default of aes256-hmac-sha256.

Then intention was that the user does an informed decision between hmac-sha256 and blake2b MACs.

But: if a user does not specify --encryption, we now fall back to no encryption at all (and this was not intended).

**Comment by jdchristensen** [comment]
For what it's worth, I feel that if the user does not specify -e, then that means they don't want encryption.

**Comment by ThomasWaldmann** [comment]
@jdchristensen Like web browsing nowadays should default to https to protect your privacy and the authenticity/integrity of data, I think backups should also default to be encrypted and authenticated - that is why this was changed at 1.0.

For borg, if you have reasons against doing encryption/authentication, you can still switch it off with `-e none`.
