### ISSUE TITLE
Borg Backup as a Backend to XSIBACKUP

### ISSUE THREAD

**Issue by 33hops** [borgbackup/borg#2168]
Hi, I'm Daniel from 33HOPS. We have recently included an option to use Borg Backup as a backend in our software. We have noticed that your main URL: https://borgbackup.readthedocs.io/en/stable/ explicitly rejects links from our site 33hops.com, with an HTTP status "405 Not Allowed". Are you unhappy about something?, if so, please, just just let us know what the reason for this is and we'll try to please you. We thought that you'd be happy to gain more users.

**Comment by enkore** [comment]
I'm not aware that someone from our end blacklisted you (I don't think we can, actually ;)

**Comment by ThomasWaldmann** [comment]
@33hops use https:// for your links to readthedocs.

**Comment by enkore** [comment]
However, I noticed that if I am on this page: https://33hops.com/xsibackup-vmware-esxi-backup.html

And click on the " XSIBackup MANPAGE with all arguments explained and examples " link, then I get a browser warning about unsecure blablabla, not important, important is that this link does a POST request. Perhaps the same happened accidentally with the link you tried to make to the borg docs?

**Comment by 33hops** [comment]
Uff, I'm a bit embarrased. I think that I shot my feet with that code (I had forgotten about) that was meant for the menus only. I forgot to add an extra selector to avoid the hijacking effect. Not to say the "kind of" paranoic thought about you rejecting the link. The thing is that readthedocs.io are rejecting POST requests while the other sites we link to, just accept them.

My excuses, keep up the good work, and if you want some licenses of our software just let us know through our contact form, it will be a pleasure to share our work with you.

Sincerely Daniel
