### ISSUE TITLE
Interactive repository swap

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2169]
From #2160 

Note that when using BORG_PASSPHRASE the attacker cannot swap the *entire*
repository against a new repository with e.g. repokey mode and no passphrase,
because Borg will abort access when BORG_PASSPRHASE is incorrect.

However, interactively a user might not notice this kind of attack
immediately, if she assumes that the reason for the absent passphrase
prompt is a set BORG_PASSPHRASE.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/42112412-interactive-repository-swap)

note: bounty is for checking /fixing all mentioned "repo swap" issues.

**Comment by ThomasWaldmann** [comment]
How about this scenario:
- local keyfile mode, empty passphrase
- attacker swaps repo, using a fresh repokey repo with empty passphrase

**Comment by enkore** [comment]
Yeah that'd work just fine.

This isn't a bug/vuln in Borg itself, rather, just good ol' tricking the user.

**Comment by ThomasWaldmann** [comment]
Hmm, ofc. it is a bit stupid / unsafe-per-se to use a local keyfile without passphrase, but users would still think it is safe, because an attacker with only repo access does not have the key.

So, if the attacker could just swap the repo against a repokey without passphrase repo and that would go unnoticed, exposing all the data, that would be at least unexpected / embarassing.

**Comment by enkore** [comment]
1.1 == consider repokey w/ empty passphrase as plaintext for security-theatre-purposes?

**Comment by ThomasWaldmann** [comment]
@enkore I thought about that possibility, too. Makes sense for repokey and as layed out above, I'ld say this is more than just security theater.

**Comment by ThomasWaldmann** [comment]
I practically tried if it fixes https://github.com/borgbackup/borg/issues/2169#issuecomment-280430895.
```
# "legitimate user"
(borg-prod-env)tw@tux:~/w/borg$ borg init -e keyfile tw@localhost:/home/tw/w/borg/repo
(enter empty passphrase)
(borg-prod-env)tw@tux:~/w/borg$ borg create tw@localhost:/home/tw/w/borg/repo::1 src

(borg-prod-env)tw@tux:~/w/borg$ mv repo repo-kf
(borg-prod-env)tw@tux:~/w/borg$ borg init -e repokey tw@localhost:/home/tw/w/borg/repo
(borg-prod-env)tw@tux:~/w/borg$ borg create tw@localhost:/home/tw/w/borg/repo::1 src
(borg-prod-env)tw@tux:~/w/borg$ grep id repo/config 
id = 4a2f7aab0e05c0efa233b9c25c9eb001598c92b4da12444635385ae4fe2cd2c3
(borg-prod-env)tw@tux:~/w/borg$ rm -rf ~/.cache/borg/4a2f7aab0e05c0efa233b9c25c9eb001598c92b4da12444635385ae4fe2cd2c3
(borg-prod-env)tw@tux:~/w/borg$ borg create tw@localhost:/home/tw/w/borg/repo::1 src
```

**Comment by ThomasWaldmann** [comment]
Reopening it for now until is cleared.

**Comment by enkore** [comment]
Didn't you forget to delete the ~/.config/borg/security/... directory?

**Comment by ThomasWaldmann** [comment]
Fixed manual test:
```
# preparing repo of "attacker" with access to repo server
borg init -e repokey tw@localhost:/home/tw/w/borg/repo
# enter empty passphrase
echo "attacker:" ; grep id repo/config

# move out of the way for now
mv repo repo-repokey

# repo of "legitimate user"
borg init -e keyfile tw@localhost:/home/tw/w/borg/repo
# enter empty passphrase
echo "legit:" ; grep id repo/config

# "legitimate user", cron job
borg create tw@localhost:/home/tw/w/borg/repo::1 src

echo "attack now"
read R
# attack (in other terminal):
# - remove everything relating to attacker repo id from cache/config
# - keep everything relating to legit repo
# - remove repo
# - move repo-repokey to repo

# "legitimate user", cron job does next backup
borg create tw@localhost:/home/tw/w/borg/repo::2 src
# now got the expected warning
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] 
```

**Comment by ThomasWaldmann** [comment]
@enkore claim bounty.
