### ISSUE TITLE
borg init -e vs borg create -e

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#217]
Both borg init and borg create have a "-e" parameter.  The one on borg init should probably be changed to something that doesn't conflict.

It's not clear at the moment in "borg help create" how to backup to a keyfile protected repository.

**Comment by ThomasWaldmann** [comment]
I am not sure I understand the issue, the options are separate for each sub command and should not conflict.

Encryption is only setup once (init) and then everything going to that repo will be encrypted, you do not need to repeat to specify that for the create command.

That's different from how compression is handled: compression is specified for each create you do (that has practical applications when some machines have a very slow repo connection while others have a fast one - you can use different compression then inside same repo).

**Comment by tgharold** [comment]
Ahhh, so the encryption is automatic.

So the question is then: Do you want to strive to keep single-letter options unique across the entire application to avoid confusion where "-e" means one thing for "borg init" and a different thing for "borg create"?

**Comment by ThomasWaldmann** [comment]
Well, it might help users if we try.

Otoh, long term it might be futile - there are only 26 letters (x2 for different case).

Also, changing something afterwards breaks existing scripts...

**Comment by tgharold** [comment]
Aye, breakage is a valid concern.  OTOH, I wonder how often people script "borg init" without using the long-options?

**Comment by ThomasWaldmann** [comment]
well, we can't know.

close this ticket?
