### ISSUE TITLE
Limited unpacker for manifest

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2175]
The same goes for the unpacker used in `unpack_and_verify_manifest`. (Which would mean that we also need to settle on a maximum number of archives per repo for now -- this is already implicitly limited to IIRC something like 400k by the 20 MB object size limit, but we should really just declare one. N.B. since archive names are kinda arbitrary this might be more difficult).

Split from #2139

**Comment by ThomasWaldmann** [comment]
master branch, archive name = hex(i), id = sha(hex(i)), ts = datetime.utcfromtimestamp(i)

then max chunk size check is triggered at ~ 475.000 archives.

so, declaring the limit at 400.000 archives (or max chunk size, whatever is reached first) seems to be ok for the purpose of limiting the unpacker here.
