### ISSUE TITLE
document snapshot usage

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2178]
some systems create snapshots at varying pathes.

concerning borg's filecache, this is unfortunate as there will be always a cache miss when going from one snapshot's files backup to the next.

so, we should point out that the snapshot mount point should be always the same (if not otherwise possible, mount --bind could be used).

**Comment by ThomasWaldmann** [comment]
or rather point out that the **absolute** path of src files (and inode number and mtime and size) must not change for speedy files-cache-enabled backups.

**Comment by enkore** [comment]
Fixed by #2218

**Comment by ThomasWaldmann** [comment]
@kmq thanks for the docs update.

btw, did you see the docs bounties?

**Comment by kmq** [comment]
@ThomasWaldmann  just in passing until you mentioned them, [but it seems I might be up for $30](https://github.com/borgbackup/borg/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Akmq%20)

**Comment by ThomasWaldmann** [comment]
@kmq just refer to your PRs in one of the bounty tickets.
