### ISSUE TITLE
remove compression mode default?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2179]
following the same reasoning why we do not have a encryption mode default any more in borg 1.1, we should remove the compression mode default and thus require the user to give `--compression X` for `borg create`.

Having `--compression none` as default (as now) is similarly bad as having `--encryption none` as default (as in early borg/attic).

**Comment by ThomasWaldmann** [comment]
let's discuss here whether we want to remove the default (see top post) or switch the default to lz4.

Pro remove:
- makes people read the docs and be able to do an informed decision about what the best compression for their usecase is

Contra remove:
- is a bit of a pain, `--compression X` needs to be always specified (interactive use, unit tests, ...)

Pro lz4:
- lz4 is super fast, often it saves more time (because needing to transfer/store less) than it needs time for compressing.
- lz4 also deals ok with already compressed data.

Contra lz4:
- if we do the decision by defining it as default, people won't necessarily decide about the best compression for their use case but just use the default (which is not the best for every use case).

**Comment by ThomasWaldmann** [comment]
Thumbs up here for "removing the default".

**Comment by ThomasWaldmann** [comment]
Thumbs up here for "lz4 as default".

**Comment by lfam** [comment]
> Contra remove:
>
>   is a bit of a pain, --compression X needs to be always specified (interactive use, unit tests, ...)

I think that initializing new repositories is not done often, so it's a very minor annoyance, as is having to choose a value for --encryption.

**Comment by jdchristensen** [comment]
I think having some default compression level (lz4 or zlib) is the right choice.  Having to specify it every time a backup is done is annoying, and for most regular users, one of those two will be fine.  Just like we don't force people to read up on chunker parameters and set them, we can allow those who care to read the docs and adjust as needed.

(As a separate issue, I think it might be good to allow a per-repo default to be specified at repo creation time.)

**Comment by demure** [comment]
Since I use a cron job -> wrapper script for my backups (and I kind of feel borg is ment to be scripted) I see the removal of a default as a non issue to everyday use, with some positives (which you already listed).

**Comment by mrhut10** [comment]
I vote having a compression as default however removing the default is still better than how it is currently.

**Comment by ThomasWaldmann** [comment]
ok, looks like lz4 as default compression is much more welcome (than having no default), so we'll take that.
