### ISSUE TITLE
Borg (cygwin) 1.0.10 don't like smb paths

### ISSUE THREAD

**Issue by theChaosCoder** [borgbackup/borg#2186]
I know that cygwin is not really supported, but it worked with smb paths with no problems until version 1.0.10. 
I also tested the cygwin version from billyc [https://github.com/borgbackup/borg/issues/440](https://github.com/borgbackup/borg/issues/440)
Same result.

/cygdrive/x/abc still works

> borg list //synology/Backups/My-PC/Borg
> 
> usage: borg list [-h] [--critical] [--error] [--warning] [--info] [--debug]
> [--lock-wait N] [--show-rc] [--no-files-cache] [--umask M]
> [--remote-path PATH] [--short] [--list-format LISTFORMAT]
> [-P PREFIX]
> [REPOSITORY_OR_ARCHIVE]
> 
> borg list: error: argument REPOSITORY_OR_ARCHIVE: Invalid location format: "//synology/Backups/My-PC/Borg"

**Comment by ThomasWaldmann** [comment]
It's likely caused by the more strict regex used for location url parsing in 1.0.10.

I didn't think about UNC pathes and also there is no test for them.

**Comment by nj** [comment]
`//` is technically not valid UNC, whereas `\\` is - unless used in the sense of POSIX (hence smb://server/path)

**Comment by ThomasWaldmann** [comment]
please note that the way to get such a path accepted is:

file:////servername/share/path
