### ISSUE TITLE
dedup tar.gz backups into a borg repo

### ISSUE THREAD

**Issue by jsheperd** [borgbackup/borg#2189]
I am looking for the most disk efficient way to dedup server snapshots created by rear and placed into separate /backup/os_snapshots/hostname.tar.gz files on a backup server. 
The servers are very similar, they should be different in /etc, logs, ..., but they have similar /usr, /bin, ..., so deduplication relevant.

I imagine three options to do that
1. tar -xzvf backup.tar.gz -C /tmp/backup; borg create myrepo::hostname_weekly; rm -rf /temp/backup
2. mount the tar.gz with fuse and borg create from there
3. zcat backup.tar.gz | borg create myrepo::hostname_weekly -

Is the 3rd option working on someway ?
The idea to make the backup with simple tar.gz archives, that is easy to manage for the operation center and making the backup version management and rotation with borg from the tar.gz archives.

**Comment by ThomasWaldmann** [comment]
4. adapt https://github.com/borgbackup/borg-import

ad 1.: would work, similar to what 4. would do.
ad 2.: if the fuse fs for tar works well, this should work also.
ad 3.: might dedup some big files' chunks, but not small files.

REAR support borg directly also.

**Comment by jsheperd** [comment]
1. OK
2. I have tested archivemount for mounting the tar.gz, but it is unusable slow.
3. i dropped it 
4. I would take a trial. Can you help me with some hints, how to start ?

Just for to be sure, Isn't any built-in for doing this ?

**Comment by enkore** [comment]
This would be #63.

You can just feed the .tar.gz into borg create directly (via pipe or just as a file), but the results will be a lot worse compared to creating the backups with borg directly. That's just how it is.

Regarding borg-import, I think that would make sense if there is some predefined scheme, but other than that it would in the end not do much different from 1 or 2 (maybe 3, but not that useful). Just to clarify: borg-import does not support this, with "adapt" Thomas meant "extend/develop".

**Comment by jsheperd** [comment]
Rear 2.0 works perfectly with BORG 1.0.10. on CentOS 6.8.
I had problems earlier because I tried BORG with the rear of CentOS 6.8 final's epel-release repo. 
It has rear 1.17.2.

**Comment by enkore** [comment]
Also see #2233
