### ISSUE TITLE
separate compaction

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2195]
Some (all?) repo-writing borg commands call compact() after their original work is done, to optimize the repository (remove non-compact segments).

I am thinking about having a separate `borg compact` command (or having it as part of a `borg optimize` command) because:
- not compacting after borg delete will likely accelerate delete a lot, good for interactive usage
- doing compact only once after multiple repo-writing commands (e.g. multiple delete) is faster (considering total time needed)
- some commands might be less prone to crash (e.g. borg delete --force (--force)). while trying to write tests for these, I had often borg crash in compact() when it touched corrupted repo parts. this had the slightly strange effect that the archive I wanted to delete was gone although borg crashed, raising questions about transactional behaviour.
- like borg prune (delete), it could be run by a different user for append-only repos

**Comment by level323** [comment]
FWIW I think it's a good idea.

**Comment by enkore** [comment]
`borg debug compact-repository`

**Comment by ThomasWaldmann** [comment]
@enkore the idea was rather to remove the compact_segments() from most/all commands and have a separate command just for that (which would be a normal command then, not a debug command).

**Comment by rugk** [comment]
Could not one already trigger this behavior (for now) by adding some random (fake, not existent) `borg debug put-obj` and `borg debug del-obj` or would that be a bit dangerous (when done in production archives?)?

**Comment by ThomasWaldmann** [comment]
The writing borg commands would still call compact_segments() to not change behaviour there.

We could add a `--no-compact` option to skip that, so delete and prune would work much faster, delaying some of the work until compact is called.
