### ISSUE TITLE
Provide support for ssh -oBatchMode=yes

### ISSUE THREAD

**Issue by kasimon** [borgbackup/borg#2202]
If there is a problem with the ssh key, ssh will fall back to prompting for a password. As this can often be unwanted in scripted backup settings, it would be helpful if borg had an option to call ssh with `-oBatchMode=yes` to disable this fallback. This also could be achieved by putting 
```
Host <backupHost>
  BatchMode yes
```
into `~/.ssh/config`, but having a command line switch for this would be nicer in my opinion.

**Comment by enkore** [comment]
You can do it via the [BORG_RSH](http://borgbackup.readthedocs.io/en/stable/usage.html#environment-variables) env var

**Comment by kasimon** [comment]
Awesome, thank you!
