### ISSUE TITLE
question: What is borg 1.1.x and how is it different than 1.0.x?

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#2205]
Hi, as a in-frequent user of borg I am left wondering:
1. Why ins't  1.1.x available in the borg ppa I use: costamagnagianfranco/borgbackup ?
2. Is 1.1.x safe to use?
3. Is 1.1.x a new borg branch? Is it 1.1 = experimental and 1.0 = master or?

Most of all - where can I find this info in the docs and release notes? For now no such info found, although I tried..

**Comment by ThomasWaldmann** [comment]
borg 1.1 (== master branch currently) is still **beta**, so use it for testing, but not as only backup for your important data.For production usage, use borg 1.0.x.

There is a 1.1.0b3 release on pypi and also binary releases on github.
In a few weeks, there will be a b4 release with some fixes and some new stuff.
After that, maybe 1 more beta, then hopefully release candidates.

The changelog is there (not complete, it is usually updated at [beta] release time):
http://borgbackup.readthedocs.io/en/latest/changes.html#changelog

Usually, distributions do not package beta software.

**Comment by ThomasWaldmann** [comment]
guess there's nothing to do here left.

**Comment by DrupaListo-com** [comment]
yup, fellow googlers might find that clarification helpful...
