### ISSUE TITLE
pass file extension list for borg to exclude from compression

### ISSUE THREAD

**Issue by bedros** [borgbackup/borg#2208]
I always use borg backup with compression, because it's proven that it saves space, however, I have a directory wit music and video files, and it becomes extremely slow to backup when compression is turned on.

is there a way to pass parameter to borg such as

`borg create --exclude-compression-list filename-lists-extensions-one-per-line --compress`

when borg creates the archive, it checks if the file's extension is in the list, then it saves without compression.

**Comment by ThomasWaldmann** [comment]
borg 1.1 will enable you to determine compression by a path/filename/ext match. still beta, be careful.

**Comment by ThomasWaldmann** [comment]
with borg 1.0, you could of course create separate archives. like one w/o compression for the music and video and another with compression for the rest.

also, you could use lz4 compression, which should not show any such slow down.

**Comment by enkore** [comment]
http://borgbackup.readthedocs.io/en/latest/usage.html#borg-help-compression

**Comment by bedros** [comment]
thank you for your quick response, I'm switching to lz4 for now, until 1.1 is released.
