### ISSUE TITLE
Add instrumentation to borg create?

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#2209]
Just a thought from an irc discussion about finding backup performance problems. If we had some option that outputs more detailed statistics about potentially performance relevant details it might be a lot easier to diagnose performance problems.

Ideas:
* number of files cache hits
* number of files cache indicated changed files
* number of files not in files cache at all
* time spent in chunking
* time spent in id hashing
* time spent in crypto (encryption + integrity hash)
* bytes sent to remote
* bytes read from remote
* can we do an reasonable approximation of how long borg was blocked by remote communications?

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/42441165-add-a-profiling-summary-option-for-borg-create)

**Comment by enkore** [comment]
> bytes send to remote
bytes read from remote

I actually wrote that a few days ago. #2210

=> Separate borg.output. logger + cmdline option for these?

**Comment by textshell** [comment]
Magic ;)

I was thinking like this would be an new option similar to --summary but with performance focused information. Still more like a report than just some logging lines. Just using a logger might be easier though. I expect some of the data collection to potentially have a performance impact though. (or maybe not? e.g. querying the current time on linux is just a memory read)

**Comment by enkore** [comment]
Direct tracing (via `sys.setprofile`) is really quite expensive, adding ~two extra function calls to encrypt+decrypt+id_hash has maybe not such a big impact, but perhaps it would better to implement it directly (not via @decorator magic or extra methods).

**Comment by textshell** [comment]
I didn‘t consider `sys.setprofile` a valid path for lightweight stats. I agree that such performance code should be kept lean and not too magic. But using an extra method would ease implementation:
Something like this would be fairly maintainable and easy to check for correct usage.
```
    performance_stats.set_section("chunking")
    ...
    performance_stats.set_section("id_hash")
```

**Comment by ThomasWaldmann** [comment]
another idea might be to add some benchmark, so we can see perf independently of user data:
- write some known content / size files to src folder, like:

  - big, all zero
  - big, all random
  - lots of small files, all zero
  - lots of small files, all random
- create backups of these into dst repo
- don't use compression (we know that lz4 is fast and lzma is slow)
- test with / without encryption depending on how dst repo was initialized

**Comment by textshell** [comment]
More synthetic tests are covered by #1788 i think.

**Comment by enkore** [comment]
```
Resource Usage (relative): 5% CPU, 0% input, 94% network
Resource Usage (absolute): 0.18 CPU, 0.0 input, 3.2 network, 3.5 wall clock
```

**Comment by textshell** [comment]
@ThomasWaldmann 
What happend to this issue. It seems you either misplaced an edit or an edit and a bounty on the top of this issue. (As this issue is not about docs)

**Comment by enkore** [comment]
```
Resource Usage (relative): 33% CPU, 68% input, 9% repository, 0% cache sync
Resource Usage (absolute): 20.87s CPU, 42.24s input, 5.92s repository, 62.37s wall clock, 0.00s cache sync
Resource Usage: bottleneck: input
```

(Actual "borg create")

**Comment by textshell** [comment]
Rename "Resource Usage" to "Time used in" or something like that? Currently i think this sounds like some kind of magic.

**Comment by enkore** [comment]
Yeah, it's just the class name for now ([diff](https://github.com/borgbackup/borg/compare/master...enkore:f/trackwait)). Naming is hard :)

**Comment by ThomasWaldmann** [comment]
closing due to #5230.

**Comment by ThomasWaldmann** [comment]
reopening, see #5230.

**Comment by fadedreamz** [comment]
@ThomasWaldmann I would like to give it a shot, can you kindly assign it to me?

**Comment by ThomasWaldmann** [comment]
There might be some more insights distributed over the issues here and on the mailing list, but the docs, esp. internals docs are maybe the best read.

If you search for a starting point: they are in `src/borg/archiver.py`, e.g. `do_create` implements `borg create`.

**Comment by fadedreamz** [comment]
@ThomasWaldmann would like to confirm my findings with you.

The [`process_file`](https://github.com/borgbackup/borg/blob/master/src/borg/archive.py#L1302) function has all the status for a file that is being processed.
- number of files cache hits
Can be determined by the number of files with status = `U` (unchanged)
- number of files cache indicated changed files
Can be determined by the number of files with status = `M` (modified), not sure if we need to include also the `C`
- number of files not in files cache at all
Can be determined by the number of files with status = 'A' (added)

The [`chunk_processor`](https://github.com/borgbackup/borg/blob/master/src/borg/archive.py#L1161-L1167) function can be instrumented for the following -

- time spend chunking
The `chunk_iter` is the iterator that reads the file and thus we can add instrumentation here to gather statistics.
- time spend in id hashing
The `id_hash` function calculates the hash of a chunk, so we can add instrumentation before and after to gather statistics.

For the following, I still haven't explored them (But maybe they are in RemoteRepository)
- time spend in crypto (encryption + integrity hash)
- bytes send to remote
- bytes read from remote

No comment yet on 
- can we do a reasonable approximation of how long borg was blocked by remote communications?

I haven't looked into `process_dir/pipe/dev/dir_with_fd/fifo/symlink` in `FilesystemObjectProcessors`. Should they be also considered for statistics?

Let me know your thoughts/comments on the findings. TIA

**Comment by ThomasWaldmann** [comment]
1 yes, but maybe increase the respective counter at the same place where these status chars are set rather than deriving that from the status char.

2 sounds right

3/4 remote stuff is in RemoteRepository, yes. crypto and compression is in one nested call, iirc (and not in remote.py).

In general it would be good to add as little code as possible for this (some code parts are already rather complex and we should try to make readability not even worse). We already have `stats` - can we add some attributes in there?

**Comment by ThomasWaldmann** [comment]
For a start, maybe just do the stuff that uses simple counters.

**Comment by francoo98** [comment]
Hello. I've been thinking about how to implement number of files cache hits, number of files cache indicated changed files and number of files not in files cache at all.
I forked the repository and pushed a short commit. What I did was add a dictionary to `fso.stats` and added a line to the `FileSystemObjectProcessor.process_file()` to update the dictionary once a file has been processed.
This dictionary has keys corresponding to the files status A, U and M; and it's values are counters.

**Comment by ThomasWaldmann** [comment]
@francoo98 sounds good, but code review is easier if you just open a pull request against master branch.

**Comment by francoo98** [comment]
> @francoo98 sounds good, but code review is easier if you just open a pull request against master branch.

Ok, I opened a PR. Can I get this assigned?

**Comment by ThomasWaldmann** [comment]
Fixed by #6991. Thanks to @francoo98!

**Comment by ThomasWaldmann** [comment]
@francoo98 looks like bountysource has technical troubles (again). :-(

I clicked on "accept", but the site does not register my acceptance.

But there is a timed mechanism also, so if noone rejects, it will also pay out the bounty to you. Alternatively, we could contact bountysource support if you do not want to wait for that.

**Comment by francoo98** [comment]
I'd like to contact support, it will take 2 weeks for the website to pay me otherwise

**Comment by ThomasWaldmann** [comment]
@francoo98 the chunking_time test sometimes fails on github CI.

**Comment by ThomasWaldmann** [comment]
@hexagonrecursion can you try if you can accept this bounty?

**Comment by francoo98** [comment]
I can't find the failing workflow. Can you link it?

**Comment by ThomasWaldmann** [comment]
It was the `chunking_time > 0.0` test.

**Comment by francoo98** [comment]
I understand, but I don't see it failing anywhere. I checked github actions and everything seems fine, and my pull request also says everything is fine.

**Comment by ThomasWaldmann** [comment]
Well, I've seen it, so please fix.

**Comment by ThomasWaldmann** [comment]
@francoo98 bounty "paid out", thanks to @bountysource support! \o/
