### ISSUE TITLE
update docs bounty

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2212]
there are quite some docs issues: https://github.com/borgbackup/borg/labels/documentation

grab some doc update issues, create a PR against master (and, after discussion, also to 1.0-maint, if applicable, see [here](http://borgbackup.readthedocs.io/en/latest/development.html#branching-model), also linked from PR submission template)

the bounty is for fixing 2 small issues or 1 bigger issue.
docs issues that already have a bounty on them do not qualify.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/42442553-update-docs-bounty)

**Comment by kmq** [comment]
Please see https://github.com/borgbackup/borg/pull/2223

**Comment by ThomasWaldmann** [comment]
Fixed by #2223, which is a backport of #2218 and #2222.
