### ISSUE TITLE
update docs bounty 2

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2213]
there are quite some docs issues: https://github.com/borgbackup/borg/labels/documentation

grab some doc update issues, create a PR against master (and, after discussion, also to 1.0-maint, if applicable, see [here](http://borgbackup.readthedocs.io/en/latest/development.html#branching-model), also linked from PR submission template)

the bounty is for fixing 2 small issues or 1 bigger issue.
docs issues that already have a bounty on them do not qualify.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/42443042-update-docs-bounty-2)

**Comment by milkey-mouse** [comment]
Can you close this one? My PRs #2270 and #2271 for small docs issues were merged.

**Comment by ThomasWaldmann** [comment]
OK :)
