### ISSUE TITLE
update backup example script in docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2214]
first have a look at latest docs, see if it can be improved (but keep it simple overall) then backport to 1.0-maint.

http://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups
http://borgbackup.readthedocs.io/en/latest/quickstart.html#automating-backups

**Comment by kmq** [comment]
I made a first pass over the "Automated backup" section:  7bbac29c615a08591fc1192c4959ba796c645422 is that what you had in mind ?

**Comment by kmq** [comment]
I took your feedback into account and made some improvements. How does this look ?0e5c64438c521f88968cd95cffd1ae9e07a7deca

**Comment by enkore** [comment]
You could just create a pull request at this point ;)
