### ISSUE TITLE
Resumable partial checking of repositories

### ISSUE THREAD

**Issue by julian-klode** [borgbackup/borg#2216]
git-annex has a way to check its repository for a defined time per day, allowing it to eventually check all of the repository up to some time. It might make sense to have something like that. Just needs a file to record what stuff has been checked (and probably also when). Or multiple named session files. Or you could just always select a random sample of things to check.

**Comment by enkore** [comment]
#1657?

**Comment by julian-klode** [comment]
@enkore Ehm, yeah. Closing this one, then.
