### ISSUE TITLE
add high level description about changes in borgbackup compared to attic

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#224]
- in general: lots of tickets from attic issue tracker fixed (bugs, features), see #5 for a list
- less chunk management overhead (less memory and disk usage) via adjustable chunker params
- faster remote cache resync (useful when backing up multiple machines into same repo)
- compression: lz4 and lzma compression, adjustable compression levels
- better error messages / exception handling
- repokey replaces problematic passphrase mode (you can't change the passphrase nor the pbkdf2 iteration count in "passphrase" mode)
- simple sparse file support
- can read special files (e.g. block devices) or stdin directly
- mkdir-based locking is more compatible than attic's posix locking
- tested on misc. linux systems, 32 and 64bit, freebsd, openbsd, netbsd, mac os x
- use fadvise to not spoil / blow up the cache
- better output for verbose mode, progress indication

**Comment by anarcat** [comment]
any more details on:

> repokey replaces problematic passphrase mode

didn't see this one pass by... 

where should this be documented? FAQ?

**Comment by ThomasWaldmann** [comment]
Maybe a section in the README.rst.

**Comment by anarcat** [comment]
hmm... i don't know, there's already a lot of stuff in there... there's already a section about Attic in the FAQ, i think that would be a better place.
