### ISSUE TITLE
--progress for serve/RPC doesn't work

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2241]
I think this was broken with the implied logging stuff?

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/42549881-progress-for-serve-rpc-doesn-t-work)

**Comment by ThomasWaldmann** [comment]
last thing to start for b4.

**Comment by enkore** [comment]
Suggested fix: 

- Always spew logging on remote end (or pass that via env var, extra cmdline arg would break 1.0 servers), we already filter locally
- Change transfer of "new-style" log messages from text to the JSON format also used in the API

**Comment by enkore** [comment]
Moved to 1.1.0b5 because fix is more complex than anticipated.

**Comment by ThomasWaldmann** [comment]
@enkore claim bounty.
