### ISSUE TITLE
borg backup to remote filesystem failed, repository defect?

### ISSUE THREAD

**Issue by maboxx** [borgbackup/borg#2243]
Hello,
since yesterday my borg backup to my remote filesystem (NAS) failing.
Please see the log:
```
Synchronizing chunks cache...
Archives: 74, w/ cached Idx: 70, w/ outdated Idx: 0, w/o cached Idx: 4.
Reading cached archive chunk index for DATA-2017-01-20-010003 ...
Merging into master chunks index ...
Reading cached archive chunk index for DATA-2017-01-24-010003.checkpoint ...
Merging into master chunks index ...
Fetching and building archive index for DATA-2017-03-01-174322 ...
/bin/sh: /tmp/_MEIzVfGS1/libreadline.so.6: no version information available (required by /bin/sh)
/bin/sh: relocation error: /bin/sh: symbol rl_filename_stat_hook, version READLINE_6.3 not defined in file libreadline.so.6 with link time reference
Object with key b'r \xb3\x13o\x98M4\x1bBSw\xd6$\x8eMI\x9d\x870\xe9\xb0\xf3\x97\x80\xfeT^ga>\xd1' not found in repository /backup/borgbackups.
Traceback (most recent call last):
  File "borg/archiver.py", line 2052, in main
  File "borg/archiver.py", line 1997, in run
  File "borg/archiver.py", line 90, in wrapper
  File "borg/archiver.py", line 299, in do_create
  File "borg/cache.py", line 97, in __init__
  File "borg/cache.py", line 391, in sync
  File "borg/cache.py", line 358, in create_master_idx
  File "borg/cache.py", line 311, in fetch_and_build_idx
  File "borg/remote.py", line 472, in get_many
  File "borg/repository.py", line 524, in get_many
  File "borg/repository.py", line 520, in get
borg.repository.Repository.ObjectNotFound: (b'r \xb3\x13o\x98M4\x1bBSw\xd6$\x8eMI\x9d\x870\xe9\xb0\xf3\x97\x80\xfeT^ga>\xd1', '/backup/borgbackups')

Platform: Linux linux 4.4.49-16-default #1 SMP Sun Feb 19 17:40:35 UTC 2017 (70e9954) x86_64 
Linux: openSUSE  42.2 x86_64
Borg: 1.0.9  Python: CPython 3.5.2
PID: 1183  CWD: /root/bin
sys.argv: ['borg', 'create', '--compression', 'lz4', '--exclude-caches', '--one-file-system', '-v', '--stats', '--progress', '/backup/borgbackups::DATA-{now:%Y-%m-%d-%H%M%S}', '/data/files/document', '/data/files/homes', '/data/files/photo', '/data/files/video/privat', '/archive/mediathek/music/favorites', '/archive/mediathek/report/important']
SSH_ORIGINAL_COMMAND: None


Synchronizing chunks cache...
Archives: 74, w/ cached Idx: 70, w/ outdated Idx: 0, w/o cached Idx: 4.
Reading cached archive chunk index for DATA-2017-02-11-010002 ...
Merging into master chunks index ...
Reading cached archive chunk index for DATA-2017-02-01-175157.checkpoint ...
Merging into master chunks index ...
Reading cached archive chunk index for DATA-2017-01-10-010002 ...
Merging into master chunks index ...
Reading cached archive chunk index for DATA-2017-01-04-012913 ...
Merging into master chunks index ...
Reading cached archive chunk index for DATA-2017-01-04-010003 ...
Merging into master chunks index ...
Fetching and building archive index for DATA-2017-03-01-174322 ...
/bin/sh: /tmp/_MEIH2u7Dj/libreadline.so.6: no version information available (required by /bin/sh)
/bin/sh: relocation error: /bin/sh: symbol rl_filename_stat_hook, version READLINE_6.3 not defined in file libreadline.so.6 with link time reference
Object with key b'r \xb3\x13o\x98M4\x1bBSw\xd6$\x8eMI\x9d\x870\xe9\xb0\xf3\x97\x80\xfeT^ga>\xd1' not found in repository /backup/borgbackups.
Traceback (most recent call last):
  File "borg/archiver.py", line 2052, in main
  File "borg/archiver.py", line 1997, in run
  File "borg/archiver.py", line 90, in wrapper
  File "borg/archiver.py", line 703, in do_prune
  File "borg/cache.py", line 97, in __init__
  File "borg/cache.py", line 391, in sync
  File "borg/cache.py", line 358, in create_master_idx
  File "borg/cache.py", line 311, in fetch_and_build_idx
  File "borg/remote.py", line 472, in get_many
  File "borg/repository.py", line 524, in get_many
  File "borg/repository.py", line 520, in get
borg.repository.Repository.ObjectNotFound: (b'r \xb3\x13o\x98M4\x1bBSw\xd6$\x8eMI\x9d\x870\xe9\xb0\xf3\x97\x80\xfeT^ga>\xd1', '/backup/borgbackups')

Platform: Linux linux 4.4.49-16-default #1 SMP Sun Feb 19 17:40:35 UTC 2017 (70e9954) x86_64 
Linux: openSUSE  42.2 x86_64
Borg: 1.0.9  Python: CPython 3.5.2
PID: 1866  CWD: /root/bin
sys.argv: ['borg', 'prune', '-v', '--list', '/backup/borgbackups', '--prefix', '{hostname}-', '--keep-within=1d', '--keep-daily=7', '--keep-weekly=4', '--keep-monthly=12']
SSH_ORIGINAL_COMMAND: None
```

When I try to mount my repository with borg mount I recieving this error:

```
$ borg mount borgbackups::DATA-2017-03-01-174322 borgmount/
Object with key b'r \xb3\x13o\x98M4\x1bBSw\xd6$\x8eMI\x9d\x870\xe9\xb0\xf3\x97\x80\xfeT^ga>\xd1' not found in repository /volume1/backup/borgbackups.
Traceback (most recent call last):
  File "borg/archiver.py", line 2052, in main
  File "borg/archiver.py", line 1997, in run
  File "borg/archiver.py", line 90, in wrapper
  File "borg/archiver.py", line 553, in do_mount
  File "borg/fuse.py", line 71, in __init__
  File "borg/fuse.py", line 117, in process_archive
  File "borg/remote.py", line 472, in get_many
  File "borg/repository.py", line 524, in get_many
  File "borg/repository.py", line 520, in get
borg.repository.Repository.ObjectNotFound: (b'r \xb3\x13o\x98M4\x1bBSw\xd6$\x8eMI\x9d\x870\xe9\xb0\xf3\x97\x80\xfeT^ga>\xd1', '/volume1/backup/borgbackups')

Platform: Linux DS1 3.10.102 #15047 SMP Tue Feb 14 02:40:00 CST 2017 x86_64 
Linux:   
Borg: 1.0.9  Python: CPython 3.5.2
PID: 17959  CWD: /volume1/backup
sys.argv: ['borg', 'mount', 'borgbackups::DATA-2017-03-01-174322', 'borgmount/']
SSH_ORIGINAL_COMMAND: None
```

Can anyone help me what is the problem here? A local backup to my local filesystem works fine.
I use the version 1.0.9 because I don't not know exactly how I can update borg. With "borg upgrade?"

I am grateful for any help!

**Comment by enkore** [comment]
Try `borg check` and see what it reports. When it seems ok, run `borg check --repair` to apply the repairs that were proposed in the previous run of check.

**Comment by ThomasWaldmann** [comment]
Also, if possible, please check SMART values of the repo disk (if nothing special is in there also consider a SMART long test). If you don't find bad sectors there, check RAM with memtest86+.

**Comment by maboxx** [comment]
Hello together,
Thank you for your help. It works now again.

I did the command borg check and recieve this log (I post the last lines):

`
...
...
...
Index mismatch for key b'\xccG\x11\xa4\xc7V\xce+\x15IJ\xbc\xe6\x81p\xeb7?r"uo\\"\xbe\xa9q\xe3\xb9V\xc8\x03'. (119308, 8) != (-1, -1)
Index mismatch for key b'\xea\x9d\xae\x92\x9a\xbe\xc3`\xf4\x02r\xdcP\xd9\xfd\x91\xd4\x07B\x99\x90\x9eu\x94\rJ\x1a\xd2$\x17y\xfb'. (111091, 8) != (-1, -1)
Index mismatch for key b'\xd9k\x91\xbf\x03&QV\\\xab,\xfc\xbc\x19\xcb\x01$\xb4\xb5\x07\x03S>\xda\xfb\x87Ew<M\x02Z'. (30753, 8) != (-1, -1)
Index mismatch for key b'\xa4eC\x8d\x91\x1a\xaf+\xcf\xeer\x04\xcc\x16s\x00\x9cN\xe1\xb0\xb2\xc4i&m\xf9)\xe5\xc3\x00:\xb5'. (27695, 1687872) != (-1, -1)
Index mismatch for key b'\xb7!m{O\xeb\xb3\x9e{j\xef!\x1a\x1b\r\x8f\x82\xb8\xc7\xcfNy\xb8c\xfa\xd1\xb1!\x10\x82\xcb\xec'. (84176, 4536437) != (-1, -1)
Index mismatch for key b'\xf2\x00\x8cMJ\x9b\xe2\x98\x13\xee\xa2\xfbeZ\x92\xdd\xf6\x8d/\x19\xf5LZ?\xe2"\x834\x89\xa6K~'. (28374, 8) != (-1, -1)
Index mismatch for key b'\xd6\xc3\x9e\xfc\x88\xcb\xeb\xf0\x9e9\x11\\\xbe\xf4\x98\xdd_-)*\x0e\xacXGv\x07O\xee\x16\xb7\x1c\xde'. (62424, 2555514) != (-1, -1)
Index mismatch for key b'\xbed\x9a`A\x02\xe9\x01\xc3\x16g.\xb2\xb8\x8bI\xc2\xfa\xf3\x89\xb8\x80Ib\xe0\x1bJ\xb1\x8a\xa5\x92\x9d'. (125769, 4316658) != (-1, -1)
Index mismatch for key b'\xc8\xa5\xfd\x17@i\xc4\xae\x11k\xb9!\xdc\xb5\xfc\n-\xe9\x10\xbf\x9cM\x83\xc1\xad"\xed\xe8I\x87\xf5\xd4'. (35903, 8) != (-1, -1)
Index mismatch for key b"\xd4\xb0j\xdd'\x10\x07\xec2ck\x05\x8cb\x8cS\xa9\x17\xfck\x08Z\x16\x17|j\xa7\xf0<\x95\xcbT". (32235, 713021) != (-1, -1)
Index mismatch for key b'*\x8aI\x1b\x00y\x95\x1b\x93\x8c\xb2_\x15\xaf\x11\x831Q\xa4Cb\xe4\xc4\x98\x18f\x16\xf0\xc7\x91\xda\xa5'. (7028, 8) != (-1, -1)
Index mismatch for key b'X[\xcb5\xf2\xd1\x87p\x15x\xc1\x93\xed\xf0d<\x01\x17>`.\x89"\xc8/K&\xebwe\x14\\'. (37634, 8) != (-1, -1)
Index mismatch for key b'\xac\xbb\x86\x9c\xc9D\t[o9\x89\x0f\x1d$EGG\x1c\x96\xa0\x01\xbb\xd4A\x8d\xd6Ug\xbe\x96\x9c\xe2'. (12108, 8) != (-1, -1)
Index mismatch for key b'\xdc\xc9}3\xb9[\xd3\xd7\xc4\xd8^*Lz\xc7\x85\xd3\xe1"\xcd\x8d\x80-\x17a\xf5\xa90\xca\x07\x12='. (126263, 450344) != (-1, -1)
Completed repository check, errors found.
`

After this I did the next command borg check -v --repair:

`
...
...
...
Analyzing archive DATA-2017-01-03-203002 (9/74)
Analyzing archive DATA-2017-01-03-201557 (8/74)
Analyzing archive DATA-2017-01-03-010020 (7/74)
Analyzing archive DATA-2017-01-02-210221 (6/74)
Analyzing archive DATA-2017-01-02-020103 (5/74)
Analyzing archive DATA-2017-01-02-014714 (4/74)
Analyzing archive DATA-2017-01-02-014528 (3/74)
Analyzing archive DATA-2017-01-01-174102 (2/74)
Analyzing archive DATA-2017-01-01-115539.checkpoint (1/74)
Archive consistency check complete, no problems found.
`

Now the borgbackup works again!

Thank you for your help!

Maybe anyone can give me a help how I can update my version 1.0.9 to the latest?

Greetings
maboxx

**Comment by ThomasWaldmann** [comment]
@maboxx just install the latest version as you did install 1.0.9.

Read the changelog, so you'll know what's new.

**Comment by maboxx** [comment]
OK thanks and after this I have nothing do do else? No repository update?

**Comment by enkore** [comment]
No, if that is needed it will be announced as the very first item in the changelog

**Comment by maboxx** [comment]
Thank you very much!!! Till then.
maboxx
