### ISSUE TITLE
minor fix for borg 1.0 hashtable

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2246]
Considering https://github.com/borgbackup/borg/issues/2245#issuecomment-283856546 I think we should do:

```
MAX_LOAD = 0.75  # we already have that
MAX_EFF_LOAD = 0.85  # new
```

```
eff_load = (buckets_used + tombstones) / capacity  # new
if eff_load > MAX_EFF_LOAD:
    resize(current_size)  # get rid of tombstones, keep size(*)
```

Equivalent: maintain a free bucket counter, compute min_free value according to MAX_EFF_LOAD and use that.

(*) there could be an addtl. check if the load is already far from what we target and in that case do a real resize to a different size.

**Comment by ThomasWaldmann** [comment]
For 1.1 we can either do same or use robin hood and get rid of tombstones by that.

**Comment by ThomasWaldmann** [comment]
Related: http://stackoverflow.com/questions/29881941/load-factor-of-hash-tables-with-tombstones

**Comment by enkore** [comment]
^- i.e. track tombstones.
