### ISSUE TITLE
Please enable IPv6 addresses for remote repositories

### ISSUE THREAD

**Issue by wararjey** [borgbackup/borg#2256]
Hello,

I was trying to specify a remote borg repo as something like that
ssh://user@[ipv6_address_string]:/path/to/repo
(and tried with leaving out the ssh:// in front, as well)

borg then somehow tried to read the ipv6 address as a hostname, and the hostname lookup naturally failed.

ssh supports ipv6 address string, by putting the address into a square bracket.

I have a use case where I want to backup to a remote repository via ssh onto a machine by ipv6. However, I do not want to expose machines IPv6 address to DNS, that's why I would like to use an address literal instead of a dns domain name in the remote repo url.

Regards,
wararjey

**Comment by ThomasWaldmann** [comment]
I'ld suggest you make a hosts file entry with a hostname for the host's ipv6 address.

Then you don't need to type complicated/long v6 addresses all the time when you work with borg (or ssh) and you do not need to put it into dns either. "Not exposing to DNS" sounds a bit like security by obscurity btw.

Borg's location URL parsing is already quite complex and ipv6 having ":" and "::" as valid address parts likely would complicate it significantly.

**Comment by wararjey** [comment]
Thanks for the hint with the hosts file, I hadn't thought of that.

I wonder if borg could not let ssh do the hostname/ipaddress parsing for the host part of the url, then you'd get that 'feature' for free...

Regards,
wararjey

**Comment by ari-s** [comment]
I'd like to have this solved: I have a case were adding the entry to /etc/hosts (or ~/.ssh/config) causes significant hassle: 

ansible-generated backup scripts for several remote backup clients that connect to remote servers where the borg repo resides. security model dictates that the borg repos are init'd from the admins machines, so all admins have to change their config. for other reasons, we'd like the backup_servers not in DNS.

**Comment by ThomasWaldmann** [comment]
@ari-s watch progress of #2264 and help testing it when it is ready.

**Comment by jeanrjc** [comment]
Hello, sorry to comment on this issue, but maybe I did not understand something.

The following does not work with borg 1.1.9:

```bash
$ borg check --archives-only backupNC@[2a02:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:/media/pi/myCloudDrive/borgBKP --debug
using builtin fallback logging configuration
35 self tests completed in 1.18 seconds
SSH command line: ['ssh', 'backupNC@2a02', 'borg', 'serve', '--umask=077', '--debug']
Remote: ssh: Could not resolve hostname 2a02: Name or service not known
Connection closed by remote host. Is borg working on the server?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 134, in wrapper
    make_parent_dirs=make_parent_dirs, args=args)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 577, in __init__
    raise ConnectionClosedWithHint('Is borg working on the server?') from None
borg.remote.ConnectionClosedWithHint: Connection closed by remote host. Is borg working on the server?

Platform: Linux nextcloudpi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l
Linux: debian 10.12 
Borg: 1.1.9  Python: CPython 3.7.3
PID: 4155  CWD: /home/pi
sys.argv: ['/usr/bin/borg', 'check', '--archives-only', 'backupNC@[2a02:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:/media/pi/myCloudDrive/borgBKP', '--debug']
SSH_ORIGINAL_COMMAND: None
```

The "SSH command line" is obviously wrong, what did I miss ? 

Thanks

**Comment by ThomasWaldmann** [comment]
Hmm, that looks strange, somehow like it did not build the ssh commandline correctly.

**Comment by ThomasWaldmann** [comment]
As a workaround, you could try a hostname instead of the v6 ip.

**Comment by ThomasWaldmann** [comment]
You could also try the `ssh://user@[...]/repopath` syntax.

The `user@[...]:/repopath` syntax parsing seems to have a bug for ipv6 addrs.

**Comment by ThomasWaldmann** [comment]
moved this to new issue #6526.
