### ISSUE TITLE
borg rename with remote repo is not working

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2260]
rename is not working with remote repo

```bash 
# echo $REPOSITORY
bak@server:/path/borg.test

# borg list $REPOSITORY
2017-03-06                     Mon, 2017-03-06 04:39:47
2017-03-06-044557              Mon, 2017-03-06 04:45:58

# borg rename $REPOSITORY::2017-03-06 2017-03-06-043947

Remote: Borg 1.0.10: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "borg/remote.py", line 145, in serve
Remote:   File "borg/remote.py", line 185, in open
Remote:   File "borg/repository.py", line 83, in __enter__
Remote:   File "borg/repository.py", line 172, in open
Remote:   File "borg/locking.py", line 265, in acquire
Remote:   File "borg/locking.py", line 294, in _wait_for_readers_finishing
Remote: borg.locking.LockTimeout: Failed to create/acquire the lock /..../borg.test/lock (timeout).
Remote: Platform: Linux .... 2.6.32-042stab120.5 #1 SMP Tue Oct 25 22:31:12 MSK 2016 x86_64 x86_64
Remote: Linux: CentOS 6.8 Final
Remote: Borg: 1.0.10  Python: CPython 3.5.3
Remote: PID: 771781  CWD: /.....
Remote: sys.argv: ['borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote:
('Remote Exception (see remote log for the traceback)', 'LockTimeout')
Platform: Linux ..... 2.6.32-042stab120.16 #1 SMP Tue Dec 13 20:58:28 MSK 2016 x86_64 x86_64
Linux: debian jessie/sid
Borg: 1.0.10  Python: CPython 3.5.3
PID: 18315  CWD: /home/.....
sys.argv: ['borg', 'rename', 'bak@.....:/...../borg.test::2017-03-06', '2017-03-06-043947']
SSH_ORIGINAL_COMMAND: None

# borg --version # both local and remote server
borg 1.0.10
```

**Comment by ThomasWaldmann** [comment]
@knutov your repo seems locked, that might mean that currently another borg process is active in it, so you can rename archives in parallel.

In some cases, it can also be a left behind lock from some crash or bug or power failure. If you can make **very sure** that there is no borg process working in the repo, you manually break the lock using `borg break-lock` command.

**Comment by knutov** [comment]
@ThomasWaldmann  Thanks, indeed, repo was mounted and rename worked fine after `borg umount`. 

So, is it possible to add detection of reason not to be able to do something and print it instead of bunch of debug lines?

**Comment by ThomasWaldmann** [comment]
We have a general default policy to rather give too much than too little information in case of exceptions (attic tried the opposite at some places and guess what, it was quite bad for debugging).

For some specific exceptions we can declare that we only want a short error msg and no traceback, if the exception is rather expected and reasons are known. The whole locking code is new to borg and still getting changes, so that might still take a bit until we do that.

We currently only know hostname, pid and threadid for the locks (not the operation). Yes, sounds like a good idea to display some more information.

**Comment by ThomasWaldmann** [comment]
Nothing left here. Closing.

**Comment by knutov** [comment]
one more question, why create is not possible when repo is mounted? mount is read-only, so why not?

**Comment by ThomasWaldmann** [comment]
Locking is very much playing safe right now and rather too restrictive than too loose.

But even read-only borg mount is not as unproblematic as you think.

If you allow other borg to write to the repo, they could rename or delete the archive(s) that you have mounted (while you maybe even work with the mounted "files"). They could also delete whole repo.

Also they could create new archives that would not show up in your repo mount until you remount.

**Comment by knutov** [comment]
Yes, I understand this. 

But, is really **create** can lead to deletion of something?

I'm new to borg (btw, it's excellent, I've tested a lot of backup scripts today and now I'm moving from self-written tar-based backup to borg) and almost first case I had problem with is when backup is mounted for some user (assuming user is restoring something) and periodic cron trying to make a new snapshot at the same time.

**Comment by knutov** [comment]
Well, I see, `create` may lead to delete at least after `BORG_FILES_CACHE_TTL`. So, should it be another feature request issue to be able to create while mounted? Or are any known best practices on how to deal with such situation ?

**Comment by ThomasWaldmann** [comment]
borg create does not delete anything, but borg delete and prune does.

but we only have a exclusive write lock and non-exclusive read locks for the repo.
there are no different types of locks for create / delete / ...

**Comment by enkore** [comment]
( #768 )
