### ISSUE TITLE
Improve documentation for --keep-exclude-tags

### ISSUE THREAD

**Issue by edgimar** [borgbackup/borg#2268]
The current documentation for the `--keep-exclude-tags` option consists of this one "sentence" in the Usage section of the documentation:

> keep tag objects (i.e.: arguments to –exclude-if-present) in otherwise excluded caches/directories
 
This leaves a lot to be understood (I had to read through the source to figure out what it _actually_ does).  Perhaps a bit more detail on this option should be included in the documentation (along with `--exclude-if-present`) in the [Description](http://borgbackup.readthedocs.io/en/latest/usage.html#id48) section.

**Comment by ThomasWaldmann** [comment]
@edgimar you could make a PR with a better description.
