### ISSUE TITLE
JSON API: Missing bits and pieces

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2274]
From #2249 

> Although some minor / not overly important bits and pieces are still missing, I'd have to make a survey to find them all. Thinking recreate might not do the stats or file list right (or does it?), perhaps adding a few more tests, and working a more general intro / summary into the docs and more [comprehensive] reference material.
>
> Also, feedback if someone wants to make a test drive would be valuable, before we freeze this interface and define compatibility policies etc.

**Comment by Abogical** [comment]
Excuse me if it's a dumb question, but why not msgpack?

**Comment by ThomasWaldmann** [comment]
@Abogical json is easier for this and we do not have the high efficiency / throughput requirements here.

**Comment by enkore** [comment]
- Pro JSON: way more tooling (e.g. jq), more widely known, easier to introspect (since it's printable text)
- Contra JSON: has issues with binary contents ("Since JSON can only encode text, any string representing a file system path may miss non-text parts." -- for now, might add workaround, e.g. base64 for elements that could contain binary stuff)
- Pro msgpack: no problems with binary contents
- Contra msgpack: less tooling, harder to introspect / handle (e.g. difficult to put in a mailing list or Github issue)

**Comment by ThomasWaldmann** [comment]
Guess concerning msgpack vs json, the decision was made long ago.

About binary items: we have a more specific ticket about this.

Considering all else, this ticket is too unspecific.
