### ISSUE TITLE
Allow rsync-like wildcards that differ in how deep they match

### ISSUE THREAD

**Issue by edgimar** [borgbackup/borg#2275]
In issue #1406 (PR #1971) a new include/exclude grammar was defined.  While this is good, I believe it would be more expressive if one could have two different wildcards, like is possible with rdiff-backup.  When using a single `*` character, it means to match something without traversing into subdirectories, and `**` matches anything and allows traversing into subdirectories.  For example, `/home/foo/*` would match `/home/foo/bar.txt`, but not match `/home/foo/baz/bar.txt`.  On the other hand, `/home/foo/**` can match, for example, `/home/foo/a/b/c/d/e/f/g/bar.txt`.  This wildcard convention is also used by rsync.

**Comment by enkore** [comment]
http://borgbackup.readthedocs.io/en/stable/usage.html#borg-help-patterns

**Comment by edgimar** [comment]
Ah, ok -- I hadn't noticed that there were different options for the patterns.  I would have preferred for the default pattern to be sh, though!

**Comment by enkore** [comment]
You're not wrong, but that'd break a lot of scripts, so we don't change the default ;)

**Comment by edgimar** [comment]
What about making it possible to specify a default syntax/style within a `--patterns-from` file?  This would be similar to how in a mercurial .hgignore file you can specify the format you wish to use at the beginning of the file using something like `syntax: regexp`.

**Comment by ThomasWaldmann** [comment]
@edgimar sounds like a good idea and maybe even easily implementable (did not look into the code yet). Maybe open a separate ticket about it?

**Comment by edgimar** [comment]
Funny, I was opening a separate ticket as you wrote your last comment:  Issue #2279
