### ISSUE TITLE
Allow specifying default pattern style inside --patterns-from file

### ISSUE THREAD

**Issue by edgimar** [borgbackup/borg#2279]
Currently the default pattern style used for options like `--patterns-from` is fnmatch (as indicated [here](http://borgbackup.readthedocs.io/en/stable/usage.html#borg-help-patterns)).  Sometimes a different default would be desirable.  It would therefore be nice if it were possible to specify a default to be used within the scope of a particular `--patterns-from` file, similar to how in a mercurial `.hgignore` file you can specify the format you wish to use at the beginning of the file using something like `syntax: regexp`.

**Comment by ThomasWaldmann** [comment]
As we have patterns change in 1.0 also, I added this to next 1.0 milestone, so that we decide about this.

**Comment by enkore** [comment]
#2288.
