### ISSUE TITLE
Prune help text: --keep-last parameter doesn't exist

### ISSUE THREAD

**Issue by theChaosCoder** [borgbackup/borg#2282]
Borg doesn't know any keep-last parameter. Tested with 1.0.9/10

> borg  prune -n --list /volumeUSB1/backup
> 
> At least one of the "keep-within", **"keep-last"**, "keep-hourly", "keep-daily", "keep-weekly", "keep-monthly" or "keep-yearly" settings must be specified.

> borg  prune -n --list --keep-last 1 /volumeUSB1/backup
> borg: error: unrecognized arguments: --keep-last

**Comment by enkore** [comment]
Indeed it doesn't.

d52b5cf5

**Comment by enkore** [comment]
#2286
