### ISSUE TITLE
Option to skip inaccessible files/directories

### ISSUE THREAD

**Issue by woky** [borgbackup/borg#2291]
I'm using a tool to mount my Android devices as fuse filesystem. Sometimes it fails, sometimes I unplug the device and forget to unmount it. In some case, it results into directory inaccessible to root. I run brog from cron and the situation can be seen from many emails about `borg create` failure I get from cron:

```/home/woky/devices/tablet: [Errno 13] Permission denied: '/home/woky/devices/tablet'```

The problem is that borg fails on EACCES. It doesn't continue and it even deletes the current backup (or it's just not shown in `list`). It would be nice if one could rely on borg to continually do backups from cron jobs in presence of inaccessible files/directories (borg should just warn about them).

Option to stay on a single filesystem may be useful, but that **may** fix this issue only as a side effect. Borg should be resilient to I/O errors in source paths (perhaps even `EIO` if source drive or filesystem is failing).

**Comment by enkore** [comment]
> It doesn't continue and it even deletes the current backup (or it's just not shown in list).

Are you sure about that? `borg create` warns about these, but does not abort. The exit code should be 1 (warning).

**Comment by woky** [comment]
Actually, you may be right. I think the target archive was just pruned. Sorry about the fuss.
