### ISSUE TITLE
borg mount and speed of copying files

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2292]
The case: backup server - 1Gbit link - client server. Borg is installed on both servers.
Repo size is 5 GB only, 200000 files inside.

After `borg mount` - `time rsync av` from mount point tooks
```
real	48m24.688s
user	0m43.856s
```

1 GBit link between servers, 5 GB repo size, 48 cpu cores, fast SSD disks, low to zero load on both servers, and such low speed. Why? Network, cpu thread, disks - **non** of them was utilized at 100%, how to find where the problem is?

For example - `tar xzf` takes 1-2 minutes in this case.

**Comment by ThomasWaldmann** [comment]
200000 files in 5GB are quite a lot. guess it is due to latency / roundtrips.

and please note that borg mount + rsync -av is not the way you extract an archive - borg extract is way more efficient for that.

**Comment by knutov** [comment]
Yes, you are right,

```
root@server:~/mnt# time borg extract -v --list  $REPOSITORY::testdate
...
real	3m10.602s
user	1m58.003s
sys	0m42.250s
```

Unfortunately, in my case, the user who is recovering files has mount (made by root) and do not has access to the repo and can not do `borg extract`.

Is there any way to speed up the copying files from `borg mount` using rsync or anything else ?

**Comment by enkore** [comment]
Which version do you use for mounting?

**Comment by knutov** [comment]
```
# borg -V
borg 1.0.10
```

**Comment by enkore** [comment]
Ok. Can you try this (does not work with the static binaries):

```
python(3) -m cProfile -o /tmp/borg-profile $(which borg) mount <repo> <mountpoint>
<do the rsync/reads>
fusermount -u <mountpoint> / borg umount <mountpoint>
```

Then send the /tmp/borg-profile file to Thomas or me (see AUTHORS for email addresses), it doesn't contain passwords / data. This should give us a good idea what the issue is.

**Comment by knutov** [comment]
Yes, I can. 

What exactly do you mean under "do the rsync/reads"? rsync of the whole repo, or a few minutes will be enough ?

**Comment by enkore** [comment]
Ideally what is slow compared to the direct way / borg extract, a couple minutes should be enough.

**Comment by knutov** [comment]
```
python -m cProfile -o /tmp/borg-profile $(which borg) mount $REPOSITORY::$SNAPSHOT $MNT -o allow_other
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/cProfile.py", line 199, in <module>
    main()
  File "/usr/lib/python2.7/cProfile.py", line 186, in main
    code = compile(fp.read(), progname, 'exec')
TypeError: compile() expected string without null bytes
```

How to fix it?

**Comment by ThomasWaldmann** [comment]
Try with python3.

**Comment by knutov** [comment]
```
# python3 -m cProfile -o /tmp/borg-profile $(which borg) mount $REPOSITORY::$SNAPSHOT $MNT -o allow_other
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.4/cProfile.py", line 160, in <module>
    main()
  File "/usr/lib/python3.4/cProfile.py", line 146, in main
    code = compile(fp.read(), progname, 'exec')
TypeError: source code string cannot contain null bytes

# python3 --version
Python 3.4.3
```

**Comment by ThomasWaldmann** [comment]
```
ls -l `which borg`
```

**Comment by knutov** [comment]
```
# ls -l `which borg`
-rwxr-xr-x 1 root root 11485480 Feb 13 14:10 /usr/local/bin/borg
```

**Comment by ThomasWaldmann** [comment]
That is the binary, see https://github.com/borgbackup/borg/issues/2292#issuecomment-290813092.

**Comment by enkore** [comment]
In other words, you'd need to install Borg [any way](http://borgbackup.readthedocs.io/en/stable/installation.html) but not as a static/standalone binary.

**Comment by knutov** [comment]
Thanks, I've got it.

I sent email with link to profile to @ThomasWaldmann from knutov-at-gmail-com

Please check is it enough

**Comment by enkore** [comment]
@ThomasWaldmann  ^^^

**Comment by ThomasWaldmann** [comment]
cumulative sorted:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    108/1    0.008    0.000  138.487  138.487 {built-in method exec}
        1    0.000    0.000  138.487  138.487 borg-env/bin/borg:3(<module>)
        1    0.000    0.000  138.349  138.349 /root/borg-env/lib/python3.4/site-packages/borg/archiver.py:2057(main)
        1    0.000    0.000  138.309  138.309 /root/borg-env/lib/python3.4/site-packages/borg/archiver.py:2016(run)
        1    0.000    0.000  138.308  138.308 /root/borg-env/lib/python3.4/site-packages/borg/archiver.py:70(wrapper)
        1    0.000    0.000  137.091  137.091 /root/borg-env/lib/python3.4/site-packages/borg/archiver.py:545(do_mount)
        1    0.000    0.000  136.407  136.407 /root/borg-env/lib/python3.4/site-packages/borg/fuse.py:80(mount)
        1    0.000    0.000  136.400  136.400 /root/borg-env/lib/python3.4/site-packages/borg/fuse.py:26(fuse_main)
        1   56.442   56.442  136.400  136.400 {llfuse.main}
     5611    0.159    0.000   76.045    0.014 /root/borg-env/lib/python3.4/site-packages/borg/fuse.py:286(read)
     1970    0.478    0.000   73.835    0.037 /root/borg-env/lib/python3.4/site-packages/borg/remote.py:324(call_many)
    42539   72.735    0.002   72.735    0.002 {built-in method select}
     1980    0.009    0.000   72.708    0.037 /root/borg-env/lib/python3.4/site-packages/borg/remote.py:454(get_many)
     1972    0.018    0.000   72.097    0.037 /root/borg-env/lib/python3.4/site-packages/borg/remote.py:528(get_many)
    34252    0.190    0.000   71.769    0.002 {built-in method next}
      934    0.007    0.000   71.595    0.077 /root/borg-env/lib/python3.4/site-packages/borg/remote.py:501(get)
     1048    0.511    0.000    4.225    0.004 /root/borg-env/lib/python3.4/site-packages/borg/key.py:219(decrypt)
     1049    3.653    0.003    3.653    0.003 {built-in method openssl_sha256}
    27701    0.017    0.000    3.131    0.000 /root/borg-env/lib/python3.4/site-packages/borg/fuse.py:252(_load_pending_archive)
      654    0.001    0.000    3.109    0.005 /root/borg-env/lib/python3.4/site-packages/borg/fuse.py:282(opendir)
```

**Comment by ThomasWaldmann** [comment]
@knutov you said it is 1 gbit/s, but how is latency?

It seems to be quite often / long in os.select(), waiting for the network.

**Comment by enkore** [comment]
```
     5611    0.159    0.000   76.045    0.014 fuse.py:286(read)
```

Would seem to imply that it's the random read latency. This can only be avoided by implementing read-ahead.

**Comment by knutov** [comment]
@ThomasWaldmann `ping` to backup server says `time=48.2 ms`.

@enkore thanks, I plan to test 1.0.11 this week, but unsure, does it already work with some parallel actions or it's still have locks? Locks lead to problems in my case (trying to restore during backup, or backup during restoring, or getting info during restoring/backup are pain with 1.0.10 and requires a lot of additional code to handle this cases in my automatization)

**Comment by ThomasWaldmann** [comment]
@knutov any news?

borg will keep using locks for quite a while (likely all 1.0 and 1.1). better play safe.

**Comment by knutov** [comment]
Sorry for not answering for a long time 

At the end of all I should admit the root problem is clearly round trips to backup server which is server in different datacenter in different country to make backup truly be safe from original source place. 

`export`tar` works pretty fast but we decided to separate data per user. Less deduplication but now our users can have direct access to repos and can do `borg extract` so initial problem do not exists any more for us.

With newer version `borg mount` with such remote server is still pretty uncomfortable in terms of speed and latency of manual operations like `cd` or `diff` for files but it's rarely used like in case of manual looking at files mostly for `borg mount versions` so I do not think it's a problem now.

I don't think it's easy to make it faster in case if ping is about 40-50 ms so I'm closing ticket.

**Comment by ThomasWaldmann** [comment]
cd speed: should be usually fast with one exception: if you cd into an archive toplevel dir (if you mounted the whole repo). in that case the archive will be on-demand loaded at that moment and cause some delay. this is intended behaviour to avoid having to load all archives at mount time (which would take even much longer).

diff speed: read operations on files need to access the repo again to fetch that content. like for borg extract, there is maybe optimization potential.
