### ISSUE TITLE
One cause of orphaned chunks

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2295]
When a file is processed and a file-critical error occurs, e.g. EIO somewhere in the file, then all chunks that were already add_chunk()d will become orphans.

This seems like an O.K. trade-off to me, since while fixing it in the current codebase is doable ("just" tricky), it'd be a significant complexity increase in any multi-threaded structure I can come up with.

If one wants to fix it, then a possible solution could be to delay the incref when processing files to the point where add_item() is called, and iterating over the chunks cache, deleting chunks with refcount==0.

**Comment by fantasya-pbem** [comment]
I have thought about documenting this, but I'm not sure yet where to place that. FAQ? Is it a "common issue" or rather a "limitation"? Could be like "Borg check finds orphaned objects, why?", but that should explain more than just one cause.

Or we could add a note to ``borg create`` usage (if file read error, then orphan), but that again is just one of several things that could go wrong.

**Comment by ThomasWaldmann** [comment]
Guess it could be in the `borg check` docs.

**Comment by fantasya-pbem** [comment]
At least we have this documented now.

**Comment by ThomasWaldmann** [comment]
Guess documenting it is good enough, closing.
