### ISSUE TITLE
way-off fs timestamps crash msgpack

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2304]
https://github.com/msgpack/msgpack-python/issues/221

**Comment by enkore** [comment]
NTFS is probably the only FS that can cause this:

- Old FS: 32 bit second timestamps starting some where in the 70s: Only goes to 2040 or so
- Modern nixish FS: 64 bit nanosecond timestamps, just like us: Only goes to 2263 or so
- NTFS: 64 bit 100-nanosecond timestamps, goes to the year 60 000.

**Comment by ThomasWaldmann** [comment]
Idea: make a filter function that clamps everything in stat_result into 64bits range.

Use it for the result of the os.lstat(path) call in _process().

**Comment by enkore** [comment]
master: revert 8b2e7ec68099fc85ac7298d462db14b5f0ee7486 ?

1.0-maint: backport summary of the changes? I believe bigint was new in master.

**Comment by ThomasWaldmann** [comment]
i wouldn't revert that cs, but rather clamp the ts in master also.
these are fs defects, not real timestamps, so no need to save them "as is".
