### ISSUE TITLE
Failed to create/acquire the lock ...8ee53ed8/lock.exclusive 

### ISSUE THREAD

**Issue by qknight** [borgbackup/borg#2306]
i have a system which often reboots/crashes (due to power loss) and 3 of 5 backups weren't working yesterday, and the logs show:

> Failed to create/acquire the lock /backup/nixcloud-backup/.borg-cache/e4f72857fd062fadead393dd604d052d018ba6e3f115fb23f3bf7dcd8ee53ed8/lock.exclusive (timeout).
> borg error, exiting

can removal of these files be automated? one could write the PID into the lockfile somewhere and check if the process is still around.

**Comment by Abogical** [comment]
I believe you need [borg break-lock](http://borgbackup.readthedocs.io/en/stable/usage.html#borg-break-lock)

**Comment by enkore** [comment]
> can removal of these files be automated? one could write the PID into the lockfile somewhere and check if the process is still around.

that feature is in beta

**Comment by rpodgorny** [comment]
@enkore: any pointers? i need that, too...

**Comment by ThomasWaldmann** [comment]
@rpodgorny maybe wait until 1.1.0b4 gets released. only for testing yet, don't use it for important data.

**Comment by FabioPedretti** [comment]
In 1.1.0b3:
> automatically remove stale locks - set BORG_HOSTNAME_IS_UNIQUE env var to enable stale lock killing. If set, stale locks in both cache and repository are deleted. #562 #1253

**Comment by rugk** [comment]
> one could write the PID into the lockfile somewhere and check if the process is still around.

Actually I wrote a script to do something like that locally. I think this is a nice and reliable workaround. See https://github.com/rugk/borg-cron-helper
