### ISSUE TITLE
Question about using borg on/with lustre filesystem data.

### ISSUE THREAD

**Issue by pol** [borgbackup/borg#2310]
Lustre is a parallel filesystem often used in high performance computing.  Due to the way it is built, it *hates* lots of small files and prefers fewer larger files.  There are a bunch of reasons for this, but the main one is that file metadata is stored separately from file data, so any metadata operation poses a potential bottleneck.  Also (for the same reason) lustre prefers you to have a deep (as opposed to wide) file hierarchy to avoid thrashing the metadata server when you look at directories.

As a result, Borg is not a good fit.  It creates lots of small-ish chunks with thousands of chunk-files per data subdirectory.  But I think that it still could be a good fit.

One possible solution would be to deal with this by keeping the chunks in a tar file.  Since they are "write-once" (sort of), a tar file is a good fit (if they were modified a lot, it would not be, pruning would be an issue).  The "store the chunks in a big tar file" avoids the metadata load by writing the chunk metadata into the tar file, so the lustre metadata servers don't have to.  If splitting were required for filesystem limitations (say a 15GB max file size limit), then multiple tar files could be used.  

One way I tried to deal with it was to use very large chunk sizes, but that isn't allowed.  It doesn't allow a CHUNK_MAX_EXP > 23,  and the largest values that I was able to get a successful run out of were: `--chunker-params 21,23,22,4095`.  Which actually resulted in data chunk file sizes ranging from 237K to 14M.   I am not really sure what the relationship is between chunks and the files they are stored in.  I only have ~10k files in the data directory, but borg info says I have 490k unique chunks. I assume that the data files each contain several chunks?

My question is: do you have any advice about using Borg in this situation? Is there a patch that I can write/apply that might resolve these issues?

Thanks in advance.

**Comment by enkore** [comment]
After initialising the repository, edit the `config` file and raise `max_segment_size` to a suitable value (1.0 uses 5 MiB here, 1.1 uses 500 MiB). `segments_per_dir` dictates how many files per directory are stored (1.0 uses 10000, 1.1 uses 500).

**Comment by pol** [comment]
I will try this, thanks.

**Comment by pol** [comment]
The max_segment_size set by default in my repo is:

max_segment_size = 5242880

That seems to be 5MiB, is that right?

**Comment by enkore** [comment]
Yes

**Comment by pol** [comment]
What is the maximum size for a segment?  

I first tried making 640MiB segments (just doubling the base value a few times, so that was mostly picked out of the air), and that worked well. Many fewer (~100), and much larger segments. Plus the whole thing was a bit faster (~8%, not sure if this is significant).  

Then I went for segments that I would consider ideal (~13GiB), and put in 13958643712 for the segment size.  It started pretty quick then crashed with as error (significant bit bolded): 

```
# time borg create -s -p -C lz4 ./lustre-work-borg-test.config.big::big-segment /mnt/lustrefs/work/borg-test
Local Exception.GB C 4.29 GB D 1 N mnt/lustrefs/work/borg-test/143/vm-143-disk-1.qcow2
Traceback (most recent call last):
  File "borg/archiver.py", line 2089, in main
  File "borg/archiver.py", line 2025, in run
  File "borg/archiver.py", line 91, in wrapper
  File "borg/archiver.py", line 315, in do_create
  File "borg/archiver.py", line 288, in create_inner
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 343, in _process
  File "borg/archive.py", line 694, in process_file
  File "borg/cache.py", line 401, in add_chunk
  File "borg/repository.py", line 542, in put
  File "borg/hashindex.pyx", line 140, in borg.hashindex.NSIndex.__setitem__ (borg/hashindex.c:2840)
OverflowError: value too large to convert to uint32_t

Platform: Linux dtn2 2.6.32-642.3.1.el6.x86_64 #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64 x86_64
Linux: CentOS 6.8 Final
Borg: 1.0.10  Python: CPython 3.5.3
PID: 2202  CWD: /mnt/lustrefs/backup/borg
sys.argv: ['borg', 'create', '-s', '-p', '-C', 'lz4', './lustre-work-borg-test.config.big::big-segment', '/mnt/lustrefs/work/borg-test']
SSH_ORIGINAL_COMMAND: None
```
Aside from doing some sanity checking on config values, which might be warranted, what is the maximum size for a segment? My hunch would be 4294967295, but maybe you aren't storing just segment bytes in that uint32_t.

**Comment by enkore** [comment]
4 GiB is correct; the offsets into segment files are stored as a uin32_t.

Note that the 1.0.x compaction (vacuum / GC) algorithm was not designed with big segments in mind, so deleting stuff, esp. stuff that is "sprinkled" across a large number of segments, will do a lot of IO.

**Comment by ThomasWaldmann** [comment]
Hmm, anything left to do here?

**Comment by pol** [comment]
No, though it might be nice (if it doesn't exist already) to have documentation of the segments, segment-files per directory, and their maximum size. 

But I have no other issues on this topic.

**Comment by enkore** [comment]
I guess these should be added to the internals docs [about here](http://borgbackup.readthedocs.io/en/latest/internals/data-structures.html#segments).
