### ISSUE TITLE
borg create without syncing cache

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2313]
code exists, needs testing, integration, but not a priority now

**Comment by ThomasWaldmann** [comment]
code url?

**Comment by enkore** [comment]
https://github.com/borgbackup/borg/compare/master...enkore:f/avoid-cache-sync

**Comment by ThomasWaldmann** [comment]
@enkore that adhoc chunks cache is a cool idea, I like it. \o/

I think this need to be broken down into multiple steps:

1. a refactoring PR that creates the class structure as you have in your branch, but does no functional changes (or additions). So it would only implement the local chunks cache as we have it now. as that new structure seems cleaner / easier, I guess we could do that in any case. and it should be pretty easy to review and get merged.

2. we need to agree about csize (discussing it in detail, all the places where it occurs, all the usages it has, and what to do with it)

3. implement the csize change, if any

4. implement your adhoc chunks cache

**Comment by ThomasWaldmann** [comment]
btw, i guess it would be useful if you do a DONTMERGE PR with your current branch, just to be able to get detailled feedback.

**Comment by enkore** [comment]
The main problem with csize is not so much that the technical issues, but a logical issue:

- If I create an archive with some new chunks, they will have csize set
- If I create another archive, but without the cache, so with csize=0 (which is unambiguous) for these chunks
- If I delete the first archive
- And then sync a cache
- The cache cannot know the csize of these chunks
- So we need to ask the repository, which means that has to do per-chunk I/O, because the csize isn't in the repo index, either (which makes a lot of sense)

But that might be ok, since it's a contrived example. A worst case in the very literal sense. Adding a repository API that allows to only get the length of a chunk (and falling back to len(GET()) in the client if that API is not available) would avoid network cost, and mostly leave the I/O.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/2313#issuecomment-289770897 I'ld put a bounty on 1. immediately and after discussion of 2. maybe another one on 3. - but needs separate tickets first.

**Comment by ThomasWaldmann** [comment]
Talked with @textshell and we both though that this maybe should be shifted to after 1.1.x due to unclear compatibility / effort / scope.

It's a bit of a pity, it is a super interesting feature, but otoh, we should not delay 1.1 too much.

@enkore what do you think?

**Comment by enkore** [comment]
It doesn't matter, because planning on a per-issue level doesn't work with the dynamics of an open source project. If it works out, good, otherwise, good.

---

Re. comment No. 3

(1) It's clear now that splitting the cache up into chunks and files is not a meaningful change. Implementing #2487 makes a lot more sense and will give way to have two different Cache implementations, which *is* meaningful.
(2) The solution space is pretty much completely defined by the problem, most importantly compatibility. See the other ticket.
(3) Implementing things is easy.

**Comment by enkore** [comment]
I'll prepare a patch this evening.
