### ISSUE TITLE
Create backup fails with "AssertionError" after interrupted backup

### ISSUE THREAD

**Issue by egalitarian** [borgbackup/borg#2318]
I was creating a backup with v1.0.9 after another interrupted backup to a remote storage mounted using nfs when I got this exception (full log attached). Now I can't create another backup anymore. The repo is quite big (around 3TB) and i'ts on a remote location so it would take forever to run a check. What could be the reason for this and what steps should I take now?

Synchronizing chunks cache...
Archives: 23, w/ cached Idx: 22, w/ outdated Idx: 0, w/o cached Idx: 1.
Reading cached archive chunk index for server-2017-02-19T16:20:07 ...
Merging into master chunks index ...
... lots of those ...
Reading cached archive chunk index for server-2017-02-15T17:34:02.checkpoint ...
Merging into master chunks index ...
Done.
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 2089, in main
  File "borg/archiver.py", line 2025, in run
  File "borg/archiver.py", line 91, in wrapper
  File "borg/archiver.py", line 315, in do_create
  File "borg/archiver.py", line 288, in create_inner
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 369, in _process
  File "borg/archiver.py", line 343, in _process
  File "borg/archive.py", line 709, in process_file
  File "borg/archive.py", line 294, in add_item
  File "borg/archive.py", line 298, in write_checkpoint
  File "borg/archive.py", line 333, in save
  File "borg/repository.py", line 201, in commit
  File "borg/repository.py", line 354, in compact_segments
AssertionError

[borg-log.txt](https://github.com/borgbackup/borg/files/852336/borg-log.txt)

**Comment by enkore** [comment]
This assertion guards an internal reference count, which is stored on-disk in the repository. If this reference count is corrupted, it may fail. In that case a check / check --repair (--repository-only) is advisable and will restore the correct reference counts.

**Comment by egalitarian** [comment]
Thanks, I'll try that. Maybe a description string for that assertion would be nice.

**Comment by egalitarian** [comment]
The check failed with I/O error at about 8% after two days. It would take more than 10 days to fully check and only if I'm lucky to have uninterrupted connection at both ends for that time. The remote machine is too low on resources to actually be able to do a check itself so I'm forced to do it remotely. Is there anything else I could do beside actually fetching the remote drive for a local check?

Probably borg should be more resilient to interrupted backup because if it requires a check and repair after each interruption it would make it impractical for large offsite backups.

**Comment by ThomasWaldmann** [comment]
@egalitarian the repo check is always executed on the repo server, even if you invoked it from the remote borg client. the archives check runs on the client though, as it needs decryption.

**Comment by egalitarian** [comment]
I understand that but I'm not using borg server on the remote system as it is too low on resources to run it. I'm backing up to a remote mounted drive from the local system.

**Comment by ThomasWaldmann** [comment]
Ah, right, didn't fully re-read the top post. OK, if you run via NFS, you save cpu/ram resources on the repo machine, but you buy that via needing more time needed for more data transfer. It might be also harder to see whether an I/O error is a connection issue or has it's cause on the repo disk.

**Comment by egalitarian** [comment]
Its probably a connection issue cause the SMART log is clean.

**Comment by enkore** [comment]
Technically truncated|corrupted|shadowed writes shouldn't happen with NFS even if there are connection problems

**Comment by egalitarian** [comment]
So maybe sshfs is a better idea?

**Comment by egalitarian** [comment]
That's exactly what I did and everything's working fine ever since.
