### ISSUE TITLE
crash when reading corrupt lock.roster file

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#232]
maybe it's just my fiddling around in #231, but when i interrupt `borg convert`, it leaves a `lock.roster` file lying around. then when i try to run it again, i get an exception. i can't reproduce now, unfortunately, but there was an empty `lock.roster` file lying around. doing `rm lock.roster` solve the problem.

maybe some weird race condition?

**Comment by ThomasWaldmann** [comment]
oh, empty lock roster shouldn't happen, it should have json content.

**Comment by anarcat** [comment]
yeah, somehow i can't reproduce... odd.

**Comment by ThomasWaldmann** [comment]
Guess the code dealing with lock.roster needs checking / fixing so it can deal with that without crashing.

**Comment by ThomasWaldmann** [comment]
Just to clarify: presence of a lock.roster file is not a bug. other than the exclusive lock directory, the roster file is not removed. but it shouldn't crash of course if the roster file's content is corrupt.
