### ISSUE TITLE
get rid of bigint stuff

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2323]
When we do incompatible archive and "files" cache changes anyway (and archives need to be converted, cache to be rebuilt), it will be a good time to also remove these functions:
- int_to_bigint
- bigint_to_int

They exist to (de)serialize integers bigger than 63 bits (although "bigger than 64bits" would have been better, msgpack can serialize unsigned 64bit ints, but not more, thus bigint uses a bytestring for longer ints).

We have msgpacked timestamps on disk in the archives and also in the "files" cache.

Likely, the reason for the existance of the bigint functions are broken timestamps on NTFS that can result in bigger-than-64bit mtime_ns values.

We needed clamping for other reasons also, so a bit later safe_s / safe_ns functions were introduced that just clamp seconds / nanoseconds into the unproblematic range (64bit uint). These must stay.

**Comment by enkore** [comment]
I re-read everything pertaining to this and conclude:

- The code in 1.0.x was correct and works correctly with any timestamp
- Me removing the bigint conversions in 1.1.x betas was incorrect / based on wrong assumptions about struct timespec.
- There are parts that need clamping
- Therefore, revert the bigint removal (=#2321) and everything is back to being correct
- However, when converting timestamps to a human representation, clamping may be needed (to dates before the year 9999). So #2309 needs to be partially reverted but other spots reviewed as well (`borg list`).

**Comment by ThomasWaldmann** [comment]
I don't think this should be closed. While we won't do it right now (that is why it is kept for "breaking" times), we should get rid of that unnecessary bigint hack. It is only needed for broken timestamps far in the future, we can as well just clamp such timestamps into the 64bit uint range without losing anything of value.

**Comment by enkore** [comment]
Fair enough. By the time that comes, msgpack might just have 128 bit integers already, solving it another way.

**Comment by ThomasWaldmann** [comment]
Also, I don't think #2309 should be "partially reverted".

**Comment by enkore** [comment]
Hm, we can keep the 1.0.x behaviour, which just transparently stores timestamps (of whatever vintage ;), or we can try to avoid bigint coding via e.g. these changes from #2309:

```diff
-            mtime=st.st_mtime_ns,
+            mtime=safe_ns(st.st_mtime_ns),
         )
         # borg can work with archives only having mtime (older attic archives do not have
         # atime/ctime). it can be useful to omit atime/ctime, if they change without the
         # file content changing - e.g. to get better metadata deduplication.
         if not self.noatime:
-            attrs['atime'] = st.st_atime_ns
+            attrs['atime'] = safe_ns(st.st_atime_ns)
         if not self.noctime:
-            attrs['ctime'] = st.st_ctime_ns
+            attrs['ctime'] = safe_ns(st.st_ctime_ns)
```

If we have to do further work here anyway, then I don't see a good reason (yet), why the behaviour should be changed here, compared to 1.0.x?

**Comment by ThomasWaldmann** [comment]
I think #2309 should stay fully applied. If we don't let crappy timestamps into the archives, we won't have troubles with them. safe_ns solves the > 64bit problem as well as the > y9999 problem.

if we only had new archives, that would be enough. as we also have old crappy ones, it will need some more safe_ns (safe_s) at some places, but I think I got them all in #2309.

**Comment by enkore** [comment]
> safe_ns solves the > 64bit problem as well as the > y9999 problem.

Works for me

**Comment by ThomasWaldmann** [comment]
In `msgpack`, there is `Timestamp` with `.from_unix_nano()` plus `.to_unix_nano()`:

https://github.com/msgpack/msgpack-python/blob/main/test/test_timestamp.py#L76

Looks like exactly what we need for the future.

pack: give a `Timestamp` object to msgpack
unpack: get a `Timestamp` object from msgpack (optionally, Unpacker can be configured to give nanoseconds int)

**Comment by ThomasWaldmann** [comment]
I replaced the bigint stuff by msgpack.Timestamp, the only place left with bigint is the upgrader code for `borg transfer`.
