### ISSUE TITLE
device/FIFO hardlinks

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2324]
While borg has great support for hardlinked regular files, it does not yet do anything special for hardlinked other filesystem items:

```
# create some devices and a symlink
tw@tux:~/aaa$ sudo mknod b00 b 0 0
tw@tux:~/aaa$ sudo mknod c00 c 0 0
tw@tux:~/aaa$ ln -s /vmlinuz symlink

# create hardlinks to them
tw@tux:~/aaa$ sudo ln b00 b00h
tw@tux:~/aaa$ sudo ln c00 c00h
tw@tux:~/aaa$ sudo ln symlink symlinkh

# at the left there is the inode number:
tw@tux:~/aaa$ ls -li
total 0
4187051 brw-r--r-- 2 root root 0, 0 Mar 21 04:44 b00
4187051 brw-r--r-- 2 root root 0, 0 Mar 21 04:44 b00h
4187052 crw-r--r-- 2 root root 0, 0 Mar 21 04:44 c00
4187052 crw-r--r-- 2 root root 0, 0 Mar 21 04:44 c00h
4187053 lrwxrwxrwx 2 tw   tw      8 Mar 21 04:45 symlink -> /vmlinuz
4187053 lrwxrwxrwx 2 tw   tw      8 Mar 21 04:45 symlinkh -> /vmlinuz

tw@tux:~/aaa$ borg init repo
tw@tux:~/aaa$ borg create repo::arch .

tw@tux:~/aaa$ mkdir extr ; cd extr
tw@tux:~/aaa/extr$ sudo borg extract ../repo::arch

tw@tux:~/aaa/extr$ ls -li
total 0
4187086 brw-r--r-- 1 root root 0, 0 Mar 21 04:44 b00
4187087 brw-r--r-- 1 root root 0, 0 Mar 21 04:44 b00h
4187100 crw-r--r-- 1 root root 0, 0 Mar 21 04:44 c00
4187101 crw-r--r-- 1 root root 0, 0 Mar 21 04:44 c00h
4187080 lrwxrwxrwx 1 tw   tw      8 Mar 21 04:45 symlink -> /vmlinuz
4187083 lrwxrwxrwx 1 tw   tw      8 Mar 21 04:45 symlinkh -> /vmlinuz
```
So, the hardlinked devices/symlink were not restored in a hardlinked way.

borg 1.0.10.

**Comment by ThomasWaldmann** [comment]
```
# create some devices and a symlink
tw@tux:~/aaa$ sudo mknod b00 b 0 0
tw@tux:~/aaa$ sudo mknod c00 c 0 0
tw@tux:~/aaa$ ln -s /vmlinuz symlink

# create hardlinks to them
tw@tux:~/aaa$ sudo ln b00 b00h
tw@tux:~/aaa$ sudo ln c00 c00h
tw@tux:~/aaa$ sudo ln symlink symlinkh

# at the left there is the inode number:
tw@tux:~/aaa$ ls -li
total 0
4187051 brw-r--r-- 2 root root 0, 0 Mar 21 04:44 b00
4187051 brw-r--r-- 2 root root 0, 0 Mar 21 04:44 b00h
4187052 crw-r--r-- 2 root root 0, 0 Mar 21 04:44 c00
4187052 crw-r--r-- 2 root root 0, 0 Mar 21 04:44 c00h
4187053 lrwxrwxrwx 2 tw   tw      8 Mar 21 04:45 symlink -> /vmlinuz
4187053 lrwxrwxrwx 2 tw   tw      8 Mar 21 04:45 symlinkh -> /vmlinuz

tw@tux:~/aaa$ borg init repo
tw@tux:~/aaa$ borg create repo::arch .

tw@tux:~/aaa$ mkdir extr ; cd extr
tw@tux:~/aaa/extr$ sudo borg extract ../repo::arch

tw@tux:~/aaa/extr$ ls -li
total 0
4187086 brw-r--r-- 1 root root 0, 0 Mar 21 04:44 b00
4187087 brw-r--r-- 1 root root 0, 0 Mar 21 04:44 b00h
4187100 crw-r--r-- 1 root root 0, 0 Mar 21 04:44 c00
4187101 crw-r--r-- 1 root root 0, 0 Mar 21 04:44 c00h
4187080 lrwxrwxrwx 1 tw   tw      8 Mar 21 04:45 symlink -> /vmlinuz
4187083 lrwxrwxrwx 1 tw   tw      8 Mar 21 04:45 symlinkh -> /vmlinuz
```
So, the hardlinked devices/symlink was not restored in a hardlinked way. borg 1.0.10.

**Comment by ThomasWaldmann** [comment]
From WP:

To prevent loops in the filesystem, and to keep the interpretation of .. (parent directory) consistent, many modern operating systems do not allow hard links to directories. [...] Mac OS X v10.5 (Leopard) and newer use hard links on directories for the Time Machine backup mechanism only.

**Comment by ThomasWaldmann** [comment]
Crap.
- a regular file's Item.source attribute is used to refer to the hardlink master by its name.
- a symlink's Item.source attribute is used to store the symlink's link target.

So we can't use "source" for the hardlink master reference for symlinks.

**Comment by ThomasWaldmann** [comment]
Also (cosmetic problem):

We used 'h' as status char for 'hardlinked regular file'.

So, would we then use 'h' for any hardlinked fs object?

Or drop using 'h' (and not informing about hardlink discovery) and rather output the fs object's type?

**Comment by ThomasWaldmann** [comment]
SOCK? FIFO?

**Comment by textshell** [comment]
I think having a status for detected hardlinked files is nice.
A general question: Do hardlinks on symlinks, block and char devices matter? It seems like there is little gain in hardlinking those. But i might just not know the use cases. Afaiu a symlink’s content is immutable so changing one means creating a new one anyway and symlink owner/group and permissions are never used if a remember correctly. For devices at least the owner/group and permissions would "propagate" so there could be situations where that is semantically important.
For fifos (pipes) (and sockets but they are not included in backups) the hardlink is actually semantically important (allows communication across the hardlink).

So it seems excluding symlinks (and directories) might be a way to keep this simple still maybe get all real life usecases covered.

**Comment by ThomasWaldmann** [comment]
ok, so i could remove the hardlinked-symlink support again, we can just emit a warning if we encounter one. would simplify the code a little bit.

@enkore what do you think?

**Comment by enkore** [comment]
Do hardlinked device files actually make sense? I don't think it's possibly to modify their "contents" (i.e. st_rdev) after mknod, so whether nlink>1 or not has no impact. The same reasoning applies to symlinks (I don't know about a way of modifying a symlink, either).

**Comment by ThomasWaldmann** [comment]
well, the usual effect of a hardlink is just to have same fs object under 2 different names (see usage for binaries in /bin /usr/bin). restoring without a hardlink would produce same names, just not hardlinked. so, while not precisely the same, at least nothing would break.

ok, so I guess i remove the hardlinked-symlink support again and keep the rest.

**Comment by ThomasWaldmann** [comment]
See #2342 which fixes behaviour for hardlinked devices and FIFOs.

Considering this is a rather big change and the bug is rather harmless and only occurs for exotic use cases of hardlinks, I guess we better not apply it to 1.0.

Opinions?

**Comment by ThomasWaldmann** [comment]
Hardlinked symlinks are removed from the scope of this ticket and covered in #2379.

**Comment by enkore** [comment]
No backport.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/2342 fixed this.
