### ISSUE TITLE
Remove Python API docs

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2335]
These were never part of the toctree nor linked to. Since we decided to not expose a Python API, these are not useful and only slow the docs build down.

- Remove api.rst
- Remove build_api from setup.py

**Comment by ThomasWaldmann** [comment]
Well, not declaring the python api stable for outside use does not necessarily mean we do not want to have docs about it (e.g. for our own use).

OTOH, I personally do not use html docs, I rather look into src anyway.

**Comment by enkore** [comment]
Plus they were completely incomplete (he) on RTFD anyway (http://borgbackup.readthedocs.io/en/stable/api.html).

**Comment by ThomasWaldmann** [comment]
Yes, seen that. No easy way to fix?

**Comment by enkore** [comment]
I tried that for the borgcube docs, which have Python API docs for code that imports Borg, which normally fails on RTFD, but never got it to work. So instead I mocked the extension modules out. Which would still leave these docs rather incomplete (no extension docs).

**Comment by enkore** [comment]
Fixed by #2336
