### ISSUE TITLE
"borg extract ARCHIVE PATH" not preserving ownership nor perms

### ISSUE THREAD

**Issue by bjornfor** [borgbackup/borg#2337]
However, if I drop the "PATH" pattern and simply extract everything, then ownership / perms are correct.

I'm running borg 1.0.10.

Below are steps you can take to reproduce the issue:

Setup:
```
$ mkdir /tmp/borg-test
$ cd /tmp/borg-test
$ borg init -e none backup.borg
$ mkdir myfiles
$ echo hello > myfiles/file
$ borg create backup.borg::1 myfiles
```

Check ownership / perms:
```
$ find myfiles/ -ls
  4301282      4 drwxr-xr-x   2  bfo      users        4096 mars 25 16:20 myfiles/
  4259188      4 -rw-r--r--   1  bfo      users           6 mars 25 16:20 myfiles/file

$ borg list backup.borg::1
drwxr-xr-x bfo    users         0 Sat, 2017-03-25 16:20:59 myfiles
-rw-r--r-- bfo    users         6 Sat, 2017-03-25 16:20:59 myfiles/file
```

Everything looks correct so far. Now to the problem:

```
$ mkdir restore
$ cd restore
$ borg extract ../backup.borg::1 "sh:**/file"
$ find . -ls
  4301283      4 drwxr-xr-x   3  bfo      users        4096 mars 25 16:34 .
  4301285      4 drwx------   2  bfo      users        4096 mars 25 16:34 ./myfiles
  4259190      4 -rw-r--r--   1  bfo      users           6 mars 25 16:20 ./myfiles/file
```

Look at that, "myfiles" now has 700 perms instead of 755.

These steps only show the permission issue, but if I run borg with sudo then I get files owned by root and not the correct user (also tried with --numeric-owner).

Side issue: It seems "borg extract" only sets ownership / perms on files that it updates the _contents_ of. Already existing files (with correct content) in the restore location are not fixed up wrt. ownership and permissions.

**Comment by ThomasWaldmann** [comment]
Your main issue is a duplicate, we already have a ticket about that.

About the side issue: "updating" an existing tree is not supported yet, there is also an issue about that.
