### ISSUE TITLE
safe_s() not safe enough for 32bit platforms

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2347]
Seen within 1.1.0b4 platform testing:
```
==> wheezy32: [gw3] linux -- Python 3.6.0 /vagrant/borg/borg/.tox/py36/bin/python3.6
==> wheezy32: def test_safe_timestamps():
==> wheezy32:         # ns fit into uint64
==> wheezy32:         assert safe_ns(2 ** 64) < 2 ** 64
==> wheezy32:         assert safe_ns(-1) == 0
==> wheezy32:         # s are so that their ns conversion fits into uint64
==> wheezy32:         assert safe_s(2 ** 64) * 1000000000 < 2 ** 64
==> wheezy32:         assert safe_s(-1) == 0
==> wheezy32:         # datetime won't fall over its y10k problem
==> wheezy32:         beyond_y10k = 2 ** 100
==> wheezy32:         with pytest.raises(OverflowError):
==> wheezy32:             datetime.utcfromtimestamp(beyond_y10k)
==> wheezy32: >       assert datetime.utcfromtimestamp(safe_s(beyond_y10k)) > datetime(2500, 12, 31)
==> wheezy32: E       OverflowError: timestamp out of range for platform time_t
==> wheezy32: 
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/testsuite/helpers.py:1307: OverflowError
```

**Comment by ThomasWaldmann** [comment]
```
>>> asctime(gmtime(2**32 - 1))  # max uint32
'Sun Feb  7 06:28:15 2106'

>>> asctime(gmtime(2**31 - 1))  # max int32
'Tue Jan 19 03:14:07 2038'
```

**Comment by ThomasWaldmann** [comment]
as we are dealing with filesystem timestamps, valid ones only represent timestamps in the past (up to present). only invalid timestamps (due to bugs / crashes) refer to the far future.

so if we would introduce a uint32 or int32 clamping (and thus intentionally introduce a y2106 or y2038 issue), this would not affect us in the next 20 or 89 years. and by then we (or future borg devs) can relax the clamping to 64bits.

**Comment by ThomasWaldmann** [comment]
On Debian wheezy, 32bit, Python 3.4.0:
```
>>> datetime.utcfromtimestamp(2**31)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: timestamp out of range for platform time_t
>>> datetime.utcfromtimestamp(2**31-1)
datetime.datetime(2038, 1, 19, 3, 14, 7)
```

So, looks like we need to clamp to max. int32 and y2038.

**Comment by enkore** [comment]
Since this is only a display issue - for regular handling, extracting, mounting etc. we don't convert to datetime - let's see whether we can fix this non-invasively via #2376/2368

**Comment by ThomasWaldmann** [comment]
I don't see an easy and safe way to avoid all potential issues without clamping.

Even if we discovered and fixed all problematic places somehow (which would need some additional code at all these places) and we would continue writing > y2038 timestamps into archives, older borg versions on 32bit platforms would still crash on that data.

Also, there is always some risk we do not discover all problematic places or introduce new ones in future, so something might still blow up on 32bit platforms.

So, as there is no problem within the next 20 years, I propose to just merge the 32bit int clamping PR.

**Comment by enkore** [comment]
Yeah I don't see a better way either right now. Fixing all occurrences is actually quite a bit of work and using the [pure Python datetime module](https://github.com/python/cpython/blob/master/Lib/datetime.py) would not help because it still uses date/time routines from `time` which presumably would have the same Y2038 issues / be the actual cause of them.

**Comment by ThomasWaldmann** [comment]
fixed by #2404.

**Comment by joeyh** [comment]
"as we are dealing with filesystem timestamps, valid ones only represent timestamps in the past (up to present)"

This is not actually true. One easy example of it not being true is clock skew.

**Comment by ThomasWaldmann** [comment]
@joeyh By "present" I didn't mean "this moment" (or "this nanosecond"), but rather a longer period of time (like "these days") that would include the usual time differences.
