### ISSUE TITLE
Repository ... does not exist.

### ISSUE THREAD

**Issue by davidak** [borgbackup/borg#2354]
I get this error message when i try to create a backup.

```
davidak@unibook:~$ borg create --compression zlib,8 --stats "/run/user/1000/gvfs/smb-share\:server\=10.101.65.7\,share\=root/Technik/dkl/backup::$(hostname)-$(date +%Y-%m-%d)" ~
Repository /run/user/1000/gvfs/smb-share\:server\=10.101.65.7\,share\=root/Technik/dkl/backup does not exist.
```

That is strange because the repo does exits and is mounted.

```
davidak@unibook:~$ borg list /run/user/1000/gvfs/smb-share\:server\=10.101.65.7\,share\=root/Technik/dkl/backup
Enter passphrase for key /run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup: 
unibook-2.local-2016-08-25           Thu, 2016-08-25 13:00:13
```

---

Platform: Linux unibook 4.8.0-44-generic 47~16.04.1-Ubuntu SMP Wed Mar 22 18:51:56 UTC 2017 x86_64 x86_64
Linux: "elementary" 0.4 loki
Borg: 1.0.10  Python: CPython 3.5.2
PID: 1892  CWD: /home/davidak
sys.argv: ['/usr/local/bin/borg', 'debug-info']
SSH_ORIGINAL_COMMAND: None

Repository on Windows Server via GVFS.

```
gvfs-mount smb://10.101.65.7/root < /home/davidak/.smbcreds
```

**Comment by enkore** [comment]
> Repository /run/user/1000/gvfs/smb-share\:server\=10.101.65.7\,share\=root/Technik/dkl/backup does not exist.

vs.

> Enter passphrase for key /run/user/1000/gvfs/smb-share:server=10.101.65.7,share=root/Technik/dkl/backup: 

I.e. you don't need to escape : and = in a quoted shell string.
