### ISSUE TITLE
do not show unchanged files

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#236]
`U foo` is really confusing to me. coming from the SVN/rsync/git world (i think?), i thought it meant the file was updated until i read the source.

why do we mention unchanged files at all?

**Comment by ThomasWaldmann** [comment]
I wanted to show all files, so one sees what is being considered for backup. One could easily pipe through grep and just filter what one really wants to see. If it were not there, you can't bring it back that easily.

**Comment by level323** [comment]
I agree with @ThomasWaldmann. This is a feature. In any subsequent manual or automated review/reporting/forensics if is valuable to know that borg was aware of a file but believed it to be unchanged.

**Comment by anarcat** [comment]
i would like to be able to disable that feature, basically. personnally, i would have it turned off by default.

with large datasets, just the write() calls to the terminal have a performance impact that is non-negligible - piping through grep will alleviate that partly, but not completely.

i'd be happy to work on a --changed-only flag or something.

**Comment by ThomasWaldmann** [comment]
maybe let's first finish the logging and verbosity level/features stuff.

**Comment by anarcat** [comment]
meh, okay.

**Comment by anarcat** [comment]
this depends on #302 and maybe #314.

**Comment by ThomasWaldmann** [comment]
Fixed first by https://github.com/borgbackup/borg/commit/1785ca54ba82ba851905478446d9bf00a3f9f597, then altered to https://github.com/borgbackup/borg/commit/21bd01ef1677ad52e73b1b4d98ba1364d4c64506.

`borg create -v --filter=AME ...` is what one might want to use to resolve this issue.
