### ISSUE TITLE
Second run of upgrade --tam doesn't modify keys

### ISSUE THREAD

**Issue by edgewood** [borgbackup/borg#2363]
I upgraded from borg 1.0.7 to 1.0.10, and saw the release notes about running borg upgrade --tam on all clients.  I did so, and saw that the upgrade for each repo modified the associated repo key, but only on the first client that I ran the upgrade on.

I was making some related changes, and ran ansible to update my borg clients.  Unfortunately, I forgot that I have ansible set up to install the keys, so the modified keys were overwritten by the originals.

Rerunning upgrade --tam doesn't modify the keys, even with --force.

Do I need the key modifications?  If so, how do I get borg to make them again?

**Comment by enkore** [comment]
Could be a bug; the additional protection given by storing the flag in the keys (which is the modification you observed) does not apply to repokey.

**Comment by edgewood** [comment]
Sorry, I should have been more explicit.  I'm using keyfile mode, not 
repokey.  The modifications I saw was to the content of each keyfile.

Subsequent backups have not had any problems, so I'm guessing the flag 
isn't required.

I have a snapshot of the repo prior to the upgrade.  I tried making a 
copy of the snapshot and rerunning the upgrade against the copy.  The 
upgrade succeeded, but it didn't modify the keys.

-- 
Ed Blackman

**Comment by ThomasWaldmann** [comment]
@edgewood how about using `borg upgrade --disable-tam <repo>` and then `borg upgrade --tam <repo>`, shouldn't that give the desired result?

**Comment by edgewood** [comment]
I will try it and report back.
-- 
Ed Blackman
Sent from my OnePlus One. Please excuse my brevity.


-------- Original Message --------

**Comment by edgewood** [comment]
That worked, thank you.
