### ISSUE TITLE
borg info from different server

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2366]
In our case we want to collect sometimes info about all repos from the backup server side or from some control server. It is not server where backups was made.

So, we get
```
borg info $REPOSITORY::$SNAPSHOT
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN]
```
each time and I think this is not how it should be.

I can do 
```
yes 'y' | borg info $REPOSITORY::$SNAPSHOT
```

but may be it will be better to have some key for it like `-f | --force` or just do not ask if action is `info`, like it is for `list` ?

**Comment by ThomasWaldmann** [comment]
If you answer y once, it should remember that for that repo.
For automation, there is also an automated answerer via environment variable.

but be careful, this is security related, so don't automate away if it could be security critical.

**Comment by ThomasWaldmann** [comment]
Expected behaviour, automation exists, closing.

**Comment by enkore** [comment]
http://borgbackup.readthedocs.io/en/stable/usage.html#environment-variables
