### ISSUE TITLE
borg selfupgrade (just an idea)

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2367]
Installation as a [standalone binary](https://borgbackup.readthedocs.io/en/stable/installation.html#pyinstaller-binary) looks like the better way for now.

But there is no auto upgrade option in this case.

For example, certbot-auto from Let's Encrypt can do selfupgrade to the latest stable each run and it's amazing! For borg to have option to do check and upgrade daily from the cron will be good enough, I think, and the stable 1.1 is coming soon as I see changelogs..

May be it's better to add `borg selfupgrade`?

**Comment by enkore** [comment]
On 31.03.2017 20:12, Nick S. Knutov wrote:
> Installation as a standalone binary
> <https://borgbackup.readthedocs.io/en/stable/installation.html#pyinstaller-binary>
> looks like the better way for now.
> 
> But there is no auto upgrade option in this case.
> 
> For example, certbot-auto from Let's Encrypt can do selfupgrade to the
> latest stable each run and it's amazing! For borg to have option to do
> check and upgrade daily from the cron will be good enough, I think, and
> the stable 1.1 is coming soon as I see changelogs..
> 
> May be it's better to add |borg selfupgrade|?
> 

Networking code is a huge can of worms (more so when deployed in a
static binary) that we want to circuit around as far as possible.

Cheers, Marian

**Comment by knutov** [comment]
technically it is easy, we need to have somewhere text file with the link to the latest stable and small script that will check this link and update binary if the url was changed (I can write script in bash of course, but the link must be maintained and it's better to port this inside borg).

I will do it for myself anyway as soon as the next stable release will out (and publish on github), the idea was about having this all inside borg.

**Comment by ThomasWaldmann** [comment]
you either use the package of your linux distribution, then an unattended-upgrades process will take care of all your security updates. OR you take care yourself and manage it manually.

I don't think it is a good idea if tools have their builtin upgrader, that's what distributions and package manager are for.

In case you decide to hack your own stuff, at least make sure your verify the gpg signature before you execute stuff as root.

**Comment by knutov** [comment]
Ok, thanks, I understand your point.

Anyway, "package for my linux distribution" is usually not exists or is not the last stable, so I have to use manual binary install and the case looks similar to Let's Encrypt, which has self-upgrade, that's why I wrote this issue.

**Comment by ThomasWaldmann** [comment]
For ubuntu, there is a ppa from the borgbackup package maintainer, that always has the latest.
For other dists, similar mechanisms may exist.
