### ISSUE TITLE
borg list one file

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2369]
The case: FreeBSD without FUSE, without technical possibility to get FUSE. 
The task is to check if desired file is present in the repo.

It is possible to do 
`borg list $REPOSITORY::$SNAPSHOT `
but some repos have millions of files and it's very bad to do `borg list | grep` in such cases (especially over slow network/disks) .

Is there any better options? 

I checked,

`borg list $REPOSITORY::$SNAPSHOT/some/path` is not working

**Comment by enkore** [comment]
Thanks, this is implemented in the next feature release. See http://borgbackup.readthedocs.io/en/latest/usage.html#borg-list
