### ISSUE TITLE
JSON: Use a more standard, timezone-aware format date time format

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2376]
Cf. #2368

Can be implemented similar to the output-type dependent file-size formatting.

**Comment by enkore** [comment]
This is a fairly simple change, but I think it should really be made for 1.1.

**Comment by ThomasWaldmann** [comment]
@enkore borg currently does a lot using localtime, but has no real timezone support (likely would require pytz). So I am not totally sure that even now all timestamps shown are totally correct (esp. regarding tzoffset and dst).

So how's your idea about this change being "fairly simple"?

**Comment by enkore** [comment]
This issue would just be about using a ISO8601 format (and output in UTC), not true TZ support, which would probably be bigger.

**Comment by ThomasWaldmann** [comment]
Ah, OK, so I'll try that...

**Comment by ThomasWaldmann** [comment]
A first step could be to use the yyyy-mm-ddThh:mm:ss format without tz (so, no weekday and the T separator would be the difference to the human-readable iso-like format we use).

**Comment by ThomasWaldmann** [comment]
partially addressed by #2925 (no tz yet), nothing to do left for 1.1 milestone.

**Comment by sophie-h** [comment]
Would it maybe be an option for 1.2 to begin with storing an additional datetime with timezone for archive `start` and `end` times? And maybe also output them in a (possibly unstable/transient `x-start-tz`) json keys, if a datetime with timezone is available as well?

**Comment by sophie-h** [comment]
@ThomasWaldmann Maybe 2.0 is a good chance for doing everything properly with timezones?

**Comment by ThomasWaldmann** [comment]
Yeah, would be good timing. But already a ton of other todo, do you want to work on it?

**Comment by ThomasWaldmann** [comment]
I started working on it...

**Comment by ThomasWaldmann** [comment]
Python (C?) wart: seems like strftime and strptime disagree on tz being with/without ":" between HH and MM.
