### ISSUE TITLE
borg rename using template doesn't eval

### ISSUE THREAD

**Issue by Artiavis** [borgbackup/borg#2386]
I realized I created an archive using ENVIRONMENT_VARIABLE_NAME instead of $ENVIRONMENT_VARIABLE_NAME, so I tried running
     borg rename ::ENVIRONMENT_VARIABLE_NAME '{hostname}-{utcnow:%Y-%m-%d}'

But somehow the command changed the archive name to the literal string  '{hostname}-{utcnow:%Y-%m-%d}'! I'm trying to rename it again but it seems like the eval only works on the existing archive name, not the targeted name. And now that my archive has that name, I don't know how to rename it. This seems like a bug, and also maybe something that should be covere in the docs. Can you please help me out? Using borg 1.0.10 on macOS via homebrew.

**Comment by enkore** [comment]
Labelling "corruption" since the resulting archive is not accessible using `list`, `extract`... (should be accessible through `mount`).

**Comment by enkore** [comment]
Try this

```
borg rename ::'{{hostname}}-{{utcnow:%Y-%m-%d}}' target-name
```

**Comment by Artiavis** [comment]
It works! Thanks for that debugging tip. In hindsight it's obvious but it wasn't intuitive as a user without pouring over source code.

Is this still a bug that the rename target doesn't seem to apply the interpolation?

**Comment by enkore** [comment]
I'd say there are two things to do here:

- Rename target is not interpolated, which it should be (for consistency)
- Documentation should explain how to escape interpolation
