### ISSUE TITLE
Document hardlink handling, HardLinkManager / hlid

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2388]

**Comment by fantasya-pbem** [comment]
We have "hardlinks for regular files, devices, FIFOs" documented in https://borgbackup.readthedocs.io/en/stable/usage/general.html#support-for-file-metadata. What else has to be documented?

**Comment by ThomasWaldmann** [comment]
Guess he meant the added complexity in the code needed to handle hardlinks.
Before this is considered for .rst docs, I'ld rather start with having better commented code for that.

**Comment by ThomasWaldmann** [comment]
This changes in #6663, after that it is not `hardlink_master`, but `hlid`.

**Comment by ThomasWaldmann** [comment]
fixed in borg2 branch.
