### ISSUE TITLE
consider adding an alternative purge procedure (for "disk nearly full" scenario)

### ISSUE THREAD

**Issue by storcium** [borgbackup/borg#239]
Backup fills the repo to 99%, prune actually increased used space to 100%

Now there does not appear to be any way to clear any part of it.  Is there any option to at least start clearing files or the only option is to add space or delete the whole repo?
```
iss@issapl1:~$ borg list /vault/repo1
borg: Error: Failed to acquire shared lock [('/vault/repo1/lock.exclusive', "[Errno 28] No space left on device: '/vault/repo1/lock.exclusive'")]
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/locking.py", line 118, in acquire
OSError: [Errno 28] No space left on device: '/vault/repo1/lock.exclusive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/locking.py", line 248, in acquire
  File "/vagrant/borg/borg/borg/locking.py", line 102, in __enter__
  File "/vagrant/borg/borg/borg/locking.py", line 126, in acquire
borg.locking.LockFailed: ('/vault/repo1/lock.exclusive', "[Errno 28] No space left on device: '/vault/repo1/lock.exclusive'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 959, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 915, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 363, in do_list
  File "/vagrant/borg/borg/borg/archiver.py", line 42, in open_repository
  File "/vagrant/borg/borg/borg/repository.py", line 60, in __init__
  File "/vagrant/borg/borg/borg/repository.py", line 134, in open
  File "/vagrant/borg/borg/borg/locking.py", line 259, in acquire
borg.locking.SharedLockFailed: ('/vault/repo1/lock.exclusive', "[Errno 28] No space left on device: '/vault/repo1/lock.exclusive'")

borg: Exiting with failure status due to previous errors
```
Borg 0.26.0
Ubuntu 14.04.3
kernel 3.19.0-25-generic

The bounty is for implementing an alternative purge mode that needs significantly less space.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/27118903-consider-adding-an-alternative-purge-procedure-for-disk-nearly-full-scenario)

**Comment by ThomasWaldmann** [comment]
Hmm, maybe this is related to that segment files never get changed. They get created. If chunks are deleted from a segment, a new segment file is created with all still existing chunks and the repo index is updated, then the old segment is removed. A segment is about 5MB.

So if you have less space there than 5MB + some working space for the repo index and transaction temp storage, it might be not possible to do much...

In the repo, is there anything else than: config, hints.* index.* lock.roster README and data/* ?

**Comment by storcium** [comment]
Hi Thomas,

The repo only has the config, hints.* index.* lock.roster README and data/* , nothing else.  When I started the prune, the space was at about 17GB but it shrunk to 0 during prune.  Here is the output of prune:

iss@issapl1:~$ borg list /vault/repo1
borg: Error: Failed to acquire shared lock [('/vault/repo1/lock.exclusive', "[Errno 28] No space left on device: '/vault/repo1/lock.exclusive'")]
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/locking.py", line 118, in acquire
OSError: [Errno 28] No space left on device: '/vault/repo1/lock.exclusive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/locking.py", line 248, in acquire
  File "/vagrant/borg/borg/borg/locking.py", line 102, in __enter__
  File "/vagrant/borg/borg/borg/locking.py", line 126, in acquire
borg.locking.LockFailed: ('/vault/repo1/lock.exclusive', "[Errno 28] No space left on device: '/vault/repo1/lock.exclusive'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 959, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 915, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 363, in do_list
  File "/vagrant/borg/borg/borg/archiver.py", line 42, in open_repository
  File "/vagrant/borg/borg/borg/repository.py", line 60, in __init__
  File "/vagrant/borg/borg/borg/repository.py", line 134, in open
  File "/vagrant/borg/borg/borg/locking.py", line 259, in acquire
borg.locking.SharedLockFailed: ('/vault/repo1/lock.exclusive', "[Errno 28] No space left on device: '/vault/repo1/lock.exclusive'")

borg: Exiting with failure status due to previous errors
i

**Comment by ThomasWaldmann** [comment]
17GB is strange. How big is your repo index?

**Comment by storcium** [comment]
Looks like 1.3 GB
-rw-------   1 iss iss 1342177298 Sep 30 23:15 index.2340851

**Comment by ThomasWaldmann** [comment]
When it starts a transaction, it copies the "chunks" and "files" index into txn.tmp.
Per chunk it deletes, it writes a DELETE tag into the repo (and remembers the segment for later compaction). When it does a commit (it does that AFTER pruning all archives!), it calls compact_segments, which writes the remaining chunks into new segments.
At the very very end, it deletes the segments it does not need any more.

So, if I analyzed that code correctly, it seems that doing a small purge (a single archive delete) is better in that situation than purging a lot of archives, because purging more also needs more space temporarily.

**Comment by ThomasWaldmann** [comment]
BTW, is your backup repo on a LVM logical volume that you could just extend temporarily?

**Comment by storcium** [comment]
On Sat, Oct 3, 2015 at 8:22 AM, TW <notifications@github.com> wrote:

> BTW, is your backup repo on a LVM logical volume that you could just
> extend temporarily?
>

It is not on LVM, but on a ZFS volume, so I should be able to add some
space, just need to figure out how

**Comment by storcium** [comment]
On Fri, Oct 2, 2015 at 4:37 PM, TW <notifications@github.com> wrote:

> When it starts a transaction, it copies the "chunks" and "files" index
> into txn.tmp.
> Per chunk it deletes, it writes a DELETE tag into the repo (and remembers
> the segment for later compaction). When it does a commit (it does that
> AFTER pruning all archives!), it calls compact_segments, which writes the
> remaining chunks into new segments.
> At the very very end, it deletes the segments it does not need any more.
>
> So, if I analyzed that code correctly, it seems that doing a small purge
> (a single archive delete) is better in that situation than purging a lot of
> archives, because purging more also needs more space temporarily.
>

Thank you - that would be great regarding a small purge, just so high space
situations are resolved gracefully.

Best regards,
Alex

**Comment by ThomasWaldmann** [comment]
Maybe purge operation could be modified to support deleting one purge candidate archive after the other (saving space) OR all purge candidate archives in one go (saving time?).

**Comment by ThomasWaldmann** [comment]
@storcium btw, could you resolve that problem for your repo?

**Comment by storcium** [comment]
On Fri, Oct 9, 2015 at 6:07 AM, TW <notifications@github.com> wrote:

> @storcium <https://github.com/storcium> btw, could you resolve that
> problem for your repo?
>
Since we are still in test mode, I deleted the repo files and did two
things to prevent future issues.  One - set ZFS quota on repo to allow
emergency addition of a little space to clean up.  Two - modify backup
script to look for 30% of expected data size and abort if that amount of
space is not available on repo.  These two measure should keep us trouble
free.

Thanks you,
Alex

**Comment by ThomasWaldmann** [comment]
Note: I added a "always have free space" warning to the docs.

**Comment by anarcat** [comment]
> Note: I added a "always have free space" warning to the docs.

i wonder if that section should link here. maybe it should also include the "reserved space" the filesystem always keeps, although that doesn't work for root unfortunately...

**Comment by ThomasWaldmann** [comment]
merged PR #428 closes this. there was also an alternate PR #423 which was not merged.

**Comment by ThomasWaldmann** [comment]
@ticpu yes, but maybe avoid adding it N times to the docs (as that option is offered by multiple commands).

Can you do a PR?

**Comment by ticpu** [comment]
@ThomasWaldmann I was looking to make a pull request but looking at the code and then at commit 389503db60a7af234eb0387cadcd8ef97c66b220, it seems save-space is enabled by default and not used anymore, would you prefer a PR to remove the option altogether? Today I experienced a low disk space situation, first time I tried deleting I had a No space left exception, then freed up a bit and got a message saying I'd need 1.17 GB more space. However, I don't know if --save-space would have helped me.

**Comment by ThomasWaldmann** [comment]
@ticpu looks like. Maybe the master and 1.1-maint docs / changelog should be checked concerning that (and if it's really a NOP since 1.1.something, we should remove it from docs and also from the code in 1.2).
