### ISSUE TITLE
The deduplication assumptions are not documented (hashing)

### ISSUE THREAD

**Issue by kjpgit** [borgbackup/borg#2390]
Considering the cornerstone and trade-off of this tool is hash-based deduplication, the lack of documented details on https://borgbackup.readthedocs.io/en/stable/ is frightening.  A link to "buzhash" on wikipedia - which isn't a defined algorithm, just a family of algorithms - is all I see.  There is no information on if this is just a hint, as the rolling hash is in rsync, or an authoritative hash.    It should also call out if file size is used as an additional check (e.g. is the same checksum allowed for different size chunks or would that cause a detected/undetected collision).  The only mention of sha256 is in the encryption section which is optional and I don't plan on using encryption.

**Comment by kjpgit** [comment]
I also think this should be documented as a trade-off which all software has and may not be appropriate for all use cases.   I have to wonder if hashing is even legal for some record keeping use cases.  Saying it's a "holy grail" does not inspire confidence (http://slides.com/thomaswaldmann/borg-6-7-8#/ .

**Comment by enkore** [comment]
Some of the things you mentioned are considered implementation details, and thus are (more or less well) documented in the "Internals" section of the docs (and the code):

http://borgbackup.readthedocs.io/en/stable/internals.html
http://borgbackup.readthedocs.io/en/latest/internals/data-structures.html
http://borgbackup.readthedocs.io/en/latest/internals/security.html

Chunk size is checked when de-duplicating with (HMAC-)SHA-256. ("holy grail" is btw. a reference to a blog post, which is in the video, but not the slides).

**Comment by ThomasWaldmann** [comment]
@kjpgit (hmac-)sha256 is the deduplication hash (id_hash), not buzhash.

**Comment by ThomasWaldmann** [comment]
Hmm, I guess we should say more clearly that a chunk is considered duplicate if we already have the same id_hash in the repository (and that id_hash is a cryptographic hash, like (hmac-)sha256).

Some places in our docs sound a bit like dedup is based on the buhash value, but we only use that for cutting the pieces, not for detecting duplicates.
