### ISSUE TITLE
Do we have a Deleted (D) --filter status?

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#2395]
We already got --filter statuses for A(added), M(modified), E(error), but where is D(Deleted)?
See docs: https://borgbackup.readthedocs.io/en/stable/usage.html#item-flags

I am logging stderr/stdout to bzipped files and for easy inspection I need to have deleted status. Is it impossible to track that ?

**Comment by enkore** [comment]
> Is it impossible to track that ?

Yes.

**Comment by DrupaListo-com** [comment]
@enkore 
1. Borg gives statuses A and M, based on the borg cache right?
2. I can't understand why it's impossible to tell if a file is (D)eleted, while it's possbile to tell if a file is (A)dded or (M)odified.. isn't the info in the cache enough for all 3 statuses?

I guess the problem in adding the D status is some borg design principle I am missing ...
In any case if you point me to the borg .py file to inspect, I will be very thankful.
Sorry to be such a nag for you.

**Comment by enkore** [comment]
File names in the cache are hashed, so if a file is not seen during a run (what you want to know for your Deleted status), then we could only tell that there were file hashes not seen during a run -- not helpful.

**Comment by DrupaListo-com** [comment]
I begin to get it: 
to do what I want (detect deletions) we need to compare the current backup src and a past borg archive. 
And at borg backup time we DON'T read any past archive cause it's not strictly needed for simply backing up and thus wastes time for little "gains".

Furthermore, at backup time we don't iterate through the whole cache, we rather iterate through the backup source set of files and folders. And since a deleted file is not in the backup source set, it is never iterated over and the cache is never searched for a deleted file as a consequence...

Finally, the fact that filenames are hashed in the cache, makes it impossible to tell only from cache+backup src set what the name of the deleted file was, even if we wanted to find missing hashes...

It's not that it's impossible to determine deletions, it's just that borg chose not to care about them at backup time.

So after/before each borg backup I could do a borg diff (if I used the 1.1 branch) or just diff current borg status logs (after each new backup) with prior status logs and parse the diff for deleted files and store that as either a separate deleted-files.log OR  just append fake "D" lines to the latest logs...
The status line diffing approach seems quite faster because it uses data we already have (at least we could easily keep "borg create" status logs) and does not iterate through the whole FS one more time... this approach also does not unpack the last archive which is slow.

Issue closed. Googlers enjoy.

**Comment by RonnyPfannschmidt** [comment]
@DrupaListo-com your assessment is not entirely correct, borg by design always does full backups, so its not trying to make a delta, it just good at reusing existing data

since it always does a full backup, determining "deletions" at backup time is simply not something that is conceptually sound or doable without "lying", full backups never have "deletions"

**Comment by DrupaListo-com** [comment]
@RonnyPfannschmidt the definition of "a deletion" / "deleted file" is very important here: as in "we deleted what from where". In this thread I mean the general notion of a deleted file between two states, not the narrower definition of deletion in the context of incremental backups - of course in borg that context is irrelevant.

By deletion above I understand this:
"Given two borg backup archives, a file is considered DELETED if it was in archive1 but not in the chronologically later archive2."
Both archive1 and archive2 are full backups and yet some files from 1 have been deleted in the meantime and are no longer in 2.

Of course I know borg does not care about the arrow of time in general. But since the majority of users use it to store consecutive archives, we should not discard/forbid that usage, right.

All this github issue boils down to is:
Q: Could we use the borg cache as a reliable and exact files history source? (so we can compare current FS state with the history and see what was modified,added,deleted and log that to a log file with A,M,D status letters)
A: For A and M we can use the cache. For D, we could in theory find some items in the cache that don't match with anything in the current FS we are backing up (and thus represent candidates for "deletions") but: a) these are hashes of fullpaths and can't be reversed, b) we are not even bothering looking for them because see a). So for D we should do the trick before/after each backup by comparing the current  archive with the prior archive  (or their status logs, where we need to store unchanged files and dirs too, along modified and added files/dirs.)

Same post as my prev one but with different words. Correct me if I got sth wrong again. Or we are just "lost in semantics" and we all are on the same page, but can't express the meaning well enough so others get it as we want it ;)

**Comment by RonnyPfannschmidt** [comment]
from what i gather we are both, not on the same page and lost in semantics,

can you please describe the actual use case you want to solve, in a way that doesn't deeply link it to loaded concepts such as history or your ideas on how to solve it

**Comment by DrupaListo-com** [comment]
Use case:
1a. I want to save backup status logs after each borg backup - example:
A /var/log/upstart/cups.log.1.gz
M /var/log/upstart/cups.log.2.gz

1b. these logs are from "borg create --verbose --list --filter AME ..."

1c. the status logs are based on the backup src state at backup time and the cache state

1d. I was wondering if I could also have the (D)eleted files statuses logged next to the A,M ...

**Comment by yorik** [comment]
I also miss `D` in my backups.

Thank you for the idea with post-backup diff, but I think the following diff line would be better:
```
borg diff ::$archive_list --json | jq -r 'select(.changes[].type == "removed") | "D " + .path'
```
