### ISSUE TITLE
borg uses the attic libraries

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#24]
here's a funky one. because the `attic` directory hasn't been renamed, the `egg` file created by `setup.py` has the same module name as the `borg` file.

this means that when `borg` starts, it actually loads the `attic` code:

```
$ sudo ./setup.py install
$ borg
usage: borg [-h]
            {serve,init,check,change-passphrase,create,extract,delete,list,mount,info,prune,help}
            ...

Attic 0.13_23_ge9c27e8-py3.4-linux-x86_64.egg - Deduplicated Backups
```

there's still a lot of attic left in there, which makes it impossible to install borg and attic next to each other without messing around with virtualenv.

**Comment by ThomasWaldmann** [comment]
yes, use a virtualenv. :)

I didn't rename the package dir yet before trying how good git can cope with that (I've a lot of unmerged code).

**Comment by ThomasWaldmann** [comment]
I tried and git coped well. So the package dir is named "borg" now.

**Comment by anarcat** [comment]
neat, thanks.
