### ISSUE TITLE
return code mismatch

### ISSUE THREAD

**Issue by mredig** [borgbackup/borg#2410]
I'm not 100% sure if this is an actual bug or something else I'm misunderstanding... But I have a script that runs borg and grabs the return code after the command executes. There is also a return code provided in the STDOUT of borg (might only be when verbose, but I always have that on). Typically, they are both zero, but today my backup returned `256`. I couldn't find any documentation as to what that meant, just [this](http://borgbackup.readthedocs.io/en/stable/usage.html#return-codes) or [this](https://github.com/borgbackup/borg/issues/61).

I then noticed the STDOUT reported a return code of `1` and I found a permission error in the log. I assume that both codes are reporting the same thing? Could this be somehow something mixing up big and little endians?

**Comment by ThomasWaldmann** [comment]
strange, can you show the script (remove passwords, if any) and the log?

what platform do you run borg on? cpu? OS?

for this to be a big vs. little endian issue, the value would need to be 16bit (not 32 or 64), so, unlikely?

**Comment by mredig** [comment]
The script is actually hosted here on [my github](https://github.com/mredig/Notes-to-Self/blob/master/assistant_scripts/borgScript/borgScript) account and I believe the lines you'll be interested in are around 119.

This is running on Debian connecting via cifs-utils to a windows IIS server in a HyperV environment.

I can share a redacted conf file for the script if you think it's necessary.

For what it's worth, it doesn't seem to be affecting me negatively apart from confusing me every time it happens (this setup has been running for about 10 month ish) cuz I forget the information on the return codes every time it happens.

Here is the error line from the log:
`E /media/webserversmb/$Recycle.Bin/S-1-5-21-124024298-4112193937-613952796-5686`
and the final part of the log
```
Number of files: 351012
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               25.92 GB             21.32 GB              5.80 MB
All archives:                4.53 TB              3.71 TB             36.05 GB

                       Unique chunks         Total chunks
Chunk index:                  782709             61822970
------------------------------------------------------------------------------
terminating with warning status, rc 1

```

and then the log from my script:

### 20170410-0836: Starting webserver-Hosting-Backup backup...

* `borg create --show-rc -v --stats -p --list -C zlib,9 --exclude-from /media/BackupDrive/Scripts/hosting.exclude /media/BackupDrive/serverborgRepoHosting::20170410-0836-hosting '/media/webserversmb' > '/media/BackupDrive/Scripts/logs/webserver-Hosting-Backup_STDOUT.log' 2>&1`


#### webserver-Hosting-Backup backup borg script ran successful: *256*

##### pruning: yes

* `borg prune -v /media/BackupDrive/serverborgRepoHosting --list --keep-daily=90 --keep-weekly=-1 --keep-monthly=-1 > '/media/BackupDrive/Scripts/logs/webserver-Hosting-Backup_pruneSTDOUT.log' 2>&1`


#### webserver-Hosting-Backup prune borg script ran successful: *0*
#### 20170410-0844: webserver-Hosting-Backup backup finished!

and again in markdown:

```
### 20170410-0836: Starting webserver-Hosting-Backup backup...

* `borg create --show-rc -v --stats -p --list -C zlib,9 --exclude-from /media/BackupDrive/Scripts/hosting.exclude /media/BackupDrive/serverborgRepoHosting::20170410-0836-hosting '/media/webserversmb' > '/media/BackupDrive/Scripts/logs/webserver-Hosting-Backup_STDOUT.log' 2>&1`


#### webserver-Hosting-Backup backup borg script ran successful: *256*

##### pruning: yes

* `borg prune -v /media/BackupDrive/serverborgRepoHosting --list --keep-daily=90 --keep-weekly=-1 --keep-monthly=-1 > '/media/BackupDrive/Scripts/logs/webserver-Hosting-Backup_pruneSTDOUT.log' 2>&1`


#### webserver-Hosting-Backup prune borg script ran successful: *0*
#### 20170410-0844: webserver-Hosting-Backup backup finished!

```

I'm sure all I have to do is empty the recycle bin to clear the warning, but if the mismatch is due to a bug in borg I want to make sure it's fixed for others as well.

**Comment by mredig** [comment]
As for endianness (I'm very rough on the subject so I may be way off?) doesn't it group into bits of 8 within whatever type the value is? Still doesn't totally make sense to me as I believe that would result in 128, right?

**Comment by enkore** [comment]
https://perldoc.perl.org/functions/system.html

> The return value is the exit status of the program as returned by the wait call. To get the actual exit value, shift right by eight (see below). See also exec. This is not what you want to use to capture the output from a command; for that you should use merely backticks or qx//, as described in `STRING` in perlop. Return value of -1 indicates a failure to start the program or an error of the wait(2) system call (inspect $! for the reason).

**Comment by mredig** [comment]
Well that would explain it! Thank you so much for finding that for me!

I've updated my script to account for that. Of course, anyone is free to use it if they find it helpful. :)
