### ISSUE TITLE
Silence logger messages

### ISSUE THREAD

**Issue by vjon** [borgbackup/borg#2415]
This is a generalization of jborg/attic#386

I'm curious as to whether anybody here would find an additional `log_level` to silence all logging particularly useful? In the example use case presented in the original attic issue, the `Repository {} already exists` error message could be silenced using `--critical`. Of course, this would also work to silence the majority of error messages for usage in automated backup scripts/etc.

So then the question becomes whether the `--critical` flag is sufficient, or whether a `--quiet` flag would provide enough added benefit to justify inclusion?

**Comment by ThomasWaldmann** [comment]
I don't think serious log messages should be silenced.

For the specific case of borg init on an existing repo:

just don't run borg init if the repo exists, problem solved.

**Comment by enkore** [comment]
#271
