### ISSUE TITLE
Add support for remote directories

### ISSUE THREAD

**Issue by jesusaurus** [borgbackup/borg#2416]
I would prefer to run borg local to the repository, rather than local to the directories. I would like to be able to create my backups with a command similar to:

```shell
borg create /path/to/repo::monday user@host.example.com:/var/log
```

I'm currently using sshfs to mount the remote directory locally, but it would be awesome if borg supported remote directories.

**Comment by theChaosCoder** [comment]
You mean like this: https://borgbackup.readthedocs.io/en/stable/usage.html#repository-urls

**Comment by ThomasWaldmann** [comment]
@jesusaurus search for "pull mode" in the issues, there is a workaround.

borg's builtin mode is "push" only, though.

**Comment by ThomasWaldmann** [comment]
@jesusaurus search for "pull mode" in the issues, there is a workaround.

borg's builtin mode is "push" only, though.
