### ISSUE TITLE
Offer pre-built ARM binaries

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2418]
It would be nice if you could also offer pre-built ARM binaries, so users  can easily use their Raspberry PI or so as a backup storage…

**Comment by enkore** [comment]
In-official binaries exist: https://borg.bauerj.eu/

**Comment by noplanman** [comment]
Just to let everybody here know, that I've managed to set up a docker solution for building binaries for all types of architectures.

Take a look here: https://git.feneas.org/noplanman/borg-binary-builder

I'm also looking into a solution for providing signed binaries directly, without requiring to do the whole docker operation for every new version.
