### ISSUE TITLE
File list from stdin

### ISSUE THREAD

**Issue by foosinn** [borgbackup/borg#2424]
Hey

i would love to see a feature like tars `-T` or `--files-from=FILE`. That way i could use `find` to exactly specify what files i want to backup. Find supports much more filters (filesize, rights, empty options and more) that would need a lot of work to support in borg.

An additional parameter for specifying delimiters like `null` or `newline` should be handy.

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/841
