### ISSUE TITLE
ENOENT for older versions of shared libraries

### ISSUE THREAD

**Issue by bjbeare** [borgbackup/borg#2426]
Seen on ubuntu 16.04.2

$ ps -ealf | grep borg | head -1
4 R root      64273  64262 97  80   0 - 296614 -     Apr17 ?        09:28:46 /usr/bin/python3 /usr/bin/borg create --stats --info -C lzma,9 --one-file-system /backup/home2/borg::home2-{now:%Y-%m-%d} /home2 --exclude */out/*

$ strace -p 64273 2>&1 | grep ENOENT | head -5
open("/usr/lib/liblzma.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/liblzma.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/liblzma.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/liblzma.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

I can "fix" this with the following:
cd /lib/x86*
ln -s liblzma.so.5.0.0 liblzma.so.2

**Comment by ThomasWaldmann** [comment]
Hmm, can you add more information?

Like:
- what borg version are you using?
- where did you get it from?
- what is the actual problem you are experiencing? (if you don't put the symlink)

BTW, using lzma,9 is pointless, see docs / FAQ.

**Comment by bjbeare** [comment]
$ borg --version
borg 1.0.10

## Installed from:
sources.list.d/costamagnagianfranco-ubuntu-borgbackup-yakkety.list:deb http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu yakkety main

If I don't put in the symlink... I don't notice an actual problem. I found this while doing some tracing for an unrelated reason.

**Comment by enkore** [comment]
This is an issue with the package.

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg ^

**Comment by LocutusOfBorg** [comment]
I fail to see the issue there. Borgbackup is built against lzma5 since a long time, if any hard dependency is spotted, the runtime dependency is calculated automatically. Maybe the lzma python binding has some fallback code?
https://launchpad.net/ubuntu/+source/python-lzma

I would suspect that import lzma would cause such enoents in the same way, regardless of borgbackup being used or not.

**Comment by ThomasWaldmann** [comment]
Hmm, guess there is no issue, if some library is found in the end (this should be visible if one looks at the full strace, directly after these ENOENT entries).
