### ISSUE TITLE
get rid of RawConfigParser?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#243]
The python docs say about RawConfigParser:
"""
Legacy variant of the ConfigParser with interpolation disabled by default and unsafe add_section and set methods.

Note:
Consider using ConfigParser instead which checks types of the values to be stored internally. If you don’t want interpolation, you can use ConfigParser(interpolation=None).
"""

**Comment by anarcat** [comment]
+1

**Comment by ThomasWaldmann** [comment]
closed by merging PR #344.
