### ISSUE TITLE
get rid of "resource" module's glibc 2.13 dependency

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2430]
We currently do in master (1.1) borg/platform/linux.pyx:
```
resource.getpagesize()
````

We could do:
```
>>> os.sysconf_names['SC_PAGESIZE']
30
>>> os.sysconf(30)
4096
```

The later is recommended by `getpagesize(2)`.

**Comment by ThomasWaldmann** [comment]
I just tested the sysconf method, works with py34 on centos6.

**Comment by enkore** [comment]
It's native code, no need to use kludges / hard-code kernel constants (30 / _SC_PAGESIZE).

**Comment by ThomasWaldmann** [comment]
@enkore hm? the point is to not import the `resource` module (which triggers the glibc 2.13 dependency), but to use something that works with older glibc also.
