### ISSUE TITLE
borg create --compression-from compression.conf causes No archive specified

### ISSUE THREAD

**Issue by artelse** [borgbackup/borg#2437]
Title says it. When I create an archive with:
`borg create --compression-from compression.conf repo::archive`
I get this error:
`borg create: error: argument ARCHIVE: "compression.conf": No archive specified`
If I omit the --compression-from option, create runs normally.

**Comment by enkore** [comment]
This feature will be removed in the next beta release. Use --compression auto,... instead.

**Comment by artelse** [comment]
With `--compression auto` I get:
`borg create: error: argument -C/--compression: invalid CompressionSpec value: 'auto'`
Running version 1.0.10

**Comment by enkore** [comment]
Both are / were 1.1 beta features and aren't included in 1.0.x.

**Comment by artelse** [comment]
Ah, my fault, just starting with borg and reading the wrong docs version :(
