### ISSUE TITLE
lock.roster not found, mac version

### ISSUE THREAD

**Issue by boolewinkle** [borgbackup/borg#244]
Hello,

> borg-macosx64 init /tmp/duckpond/Duckology1/Bkp 

gives an error
> Exception ignored in: <bound method Repository.__del__ of <Repository /tmp/duckpond/Duckology1/Bkp>>
> Traceback (most recent call last):
>  File "/vagrant/borg/borg/borg/repository.py", line 63, in __del__
>  File "/vagrant/borg/borg/borg/repository.py", line 149, in close
>  File "/vagrant/borg/borg/borg/locking.py", line 274, in release
>  File "/vagrant/borg/borg/borg/locking.py", line 202, in modify
>  File "/vagrant/borg/borg/borg/locking.py", line 175, in save
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/duckpond/Duckology1/Bkp/lock.roster'

This is on osx 10.10.5.  I get similar error about lock.roster when running a 0.26.1 compiled from source using python3.4.  

The mentioned file /tmp/duckpond/Duckology1/Bkp/lock.roster under a directory /tmp/duckpond
that is mounted via sshfs from a Synology box.  I can see this file from the mac terminal:

> ls /tmp/duckpond/Duckology1/Bkp/
> README		config		data		hints.0		index.0		lock.exclusive	lock.roster

A create command (following the init with the error)
> borg-macosx64 create --progress  --stats /tmp/duckpond/Duckology1/Bkp::2015-10-04:14:48 /Users/myhome/tmp

seems to hang, and ^C showing it is in

>   File "/vagrant/borg/borg/borg/locking.py", line 123, in acquire

Once when I removed lock.roster and lock.exclusive the create seemed to run, though I have not experimented much.

By the way, the install instructions say "osxfuse>3.0", however 2.8 is the newest version it seems?
I cannot find a 3.0 version.

**Comment by ThomasWaldmann** [comment]
Can you try if "init" works without sshfs?
And then just do a small backup ("create") and check ("list", "extract") if the basic functionality works?

**Comment by ThomasWaldmann** [comment]
as a side note: I recently tried a rsync/hardlinks based backup to a mounted sshfs and it failed because sshfs doesn't support hardlinks.

borg does not use hardlinks (or anything else too-special), but it seems one has to be a bit careful with expectations about fs behaviour when using sshfs.

**Comment by boolewinkle** [comment]
Yes, it appears to work fine if the repo is on a local drive rather than mounted over sshfs.

(Earlier I had tried attic very briefly, and it appeared to work over ssh, however I hope to switch to borg
due to what I read about attic's memory requirement)

**Comment by ThomasWaldmann** [comment]
borg has less requirements for the repo storage than attic has (borg does mkdir-based locking, which is a basic filesystem feature while attic requires posix-locking to be available).

The roster file is nothing special at all. So if that doesn't work, there seems to be something broken, maybe in sshfs itself?
