### ISSUE TITLE
pattern and patterns-from options: additional documentation

### ISSUE THREAD

**Issue by wolfpackmars2** [borgbackup/borg#2446]
I notice 'pattern' options are new but not well documented. 

They are listed as options for `borg create` and `borg extract`, but no further details are given.

Some documentation which could be helpful would include examples of pattern files and detail the different patterns that can be used.  If there already exists a section in the documentation describing generally how pattern matching is handled in borg, a reference to this section would be helpful when describing the new `--pattern*` options.

#1406

**Comment by ThomasWaldmann** [comment]
borg help pattern(s) or so.

**Comment by wolfpackmars2** [comment]
Forgot about that.

Do you want to keep it on the command line or add this information to the docs as well? If added to the docs, it would add additional maintenance when pattern behavior is changed.

Maybe there is a way to maintain this information in the source code but have it added to the docs?  I think Salt-Stack may do this, but I'm not 100% proficient with how this works.

If there's no need or desire to update the docs, this issue can be closed. I'm impartial either way.

**Comment by ThomasWaldmann** [comment]
IIRC we have these special help commands' output in a separate section in the docs.

**Comment by wolfpackmars2** [comment]
Ok I found it here: http://borgbackup.readthedocs.io/en/latest/usage.html#miscellaneous-help

I will close this. I will note, however, that I used the search function provided by RTD and none of my search terms directed me to this section.  Not sure what the problem is.

Search terms used: "pattern", "patterns", "patterns-from"

Also, searching "borg help patterns" on RTD does not lead to the correct section of the docs. This is surprising, considering "borg help patterns" is the section title. PEBCAK, probably.

**Comment by enkore** [comment]
Docs need to be usable — otherwise they're worthless.

> none of my search terms directed me to this section.
> Had to learn how to interpret RTD search results.

Thus might be a worthwhile addition to the docs explaining how to actually find stuff using the search function; I believe there is or was another ticket about issues with the search function.

**Comment by ThomasWaldmann** [comment]
See #1485.

**Comment by steveschow** [comment]
what format does the PATTERNFILE need to look like?  I can't find anything in the docs about it
