### ISSUE TITLE
missing instruction on recovering

### ISSUE THREAD

**Issue by piotrturski** [borgbackup/borg#2449]
i created an encrypted repo according to current instruction: http://borgbackup.readthedocs.io/en/stable/usage.html#borg-init
i used repokey mode and `export BORG_PASSPHRASE=...` in my backup script

now want to restore my data on another machine. i do 

```
export BORG_PASSPHRASE=...
borg list xxx
```
and i get:
`No key file for repository xxx found in /home/xxxx/.config/borg/keys.`

so
1. how?
2. is there any instruction in the docs?

**Comment by ThomasWaldmann** [comment]
That's strange.

Could you create a new user profile and then post the complete sequence of commands that reproduces the problem?

**Comment by enkore** [comment]
Probably not repokey mode then.
