### ISSUE TITLE
Fix the flaky builds on Travis

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2455]
srsly. I don't want to get any more of these "The build has been broken" mails just to find that yet again some random test failed with some random error. This is also annoying for PRs. And while these race conditions usually appear on Travis, they're still annoying from time to time for all contributors.

Some random tracebacks were posted to #2048 and some other tickets.

---

:moneybag: [There is a bounty on this](https://www.bountysource.com/issues/44643135-fix-the-flaky-builds-on-travis)

**Comment by PlasmaPower** [comment]
Might be fixed with #2478

**Comment by enkore** [comment]
Fixed by #2478

**Comment by ThomasWaldmann** [comment]
I'ld suggest to claim the bounty in a week or so.

**Comment by PlasmaPower** [comment]
Oops - already done. I'll just keep it in my bounty source account, and if the issue pops up again in the next week I'll re-donate it.

**Comment by enkore** [comment]
It's well-earned with the investigation alone.

**Comment by ThomasWaldmann** [comment]
The investigation is in #2048 in case somebody is wondering. Anything additional to that?

**Comment by PlasmaPower** [comment]
Not really, I just put faked in debug mode to troubleshoot it and suddenly everything worked.

**Comment by ThomasWaldmann** [comment]
Guess we'll see after a while on travis and also after I do next release testing on all sorts of vagrant VMs how well it goes.

As the error did not happen all the time and not on all systems, there still some chance it was just luck, I'ld guess? Also, we do not really have an explanation about what when wrong how...

Did any of you discuss this with any of the fakeroot devs? Or find out where their issue tracker is?

**Comment by PlasmaPower** [comment]
Hmm, I might try the fakeroot devs, good idea.

I guess there is a chance it was just luck, but after never having the test suite pass in my VM before after the patch it passed three times in a row, so I think it at least helped the problem. I guess it didn't totally fix it though.

**Comment by PlasmaPower** [comment]
> there still some chance it was just luck

but was it good luck or bad luck? :P
