### ISSUE TITLE
remove patterns stuff again from 1.0-maint?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2463]
Discuss whether we want to keep the `--patterns(-from)` feature in 1.0-maint (the pending 1.0.11rc1 would be the first release having it) or not.

**Comment by ThomasWaldmann** [comment]
@leo-b Considering that we'll need more time to test and fix all the include/exclude stuff in 1.1, I guess we were too optimistic adding this to 1.0 and we're likely better off having this only in 1.1 and remove it again from 1.0.

**Comment by enkore** [comment]
Fixed by #2512
