### ISSUE TITLE
! /dir/** doesn't exclude anything

### ISSUE THREAD

**Issue by Wonderer0** [borgbackup/borg#2470]
I have a folder `~/borg-test` containing a file `f0` and directories `d1` and `d2` containing files `f1` and `f2` respectively.  When I created an archive of it using the following patterns file:
```
R /home/me
+ /borg-test
+ /borg-test/d1
! /borg-test/**
```
it included both the directories and all three files.

If `!` in Borg works like `-` in `rsync` then it should have included `d1` but no other directories or files.  Using `-` instead of `!` gives the same results.  N.B. `borg help patterns` doesn't mention the `!` prefix yet, or which is the pruning one.

This is using the standalone binary borg-linux64 of version 1.1.0b5

P.S.  The above test was part of an experiment to try to work out how to include all directories in `/var/log` but no files, as raised in issue [#2399,](https://github.com/borgbackup/borg/issues/2399) to which nobody has responded :-( .  It would be much appreciated if someone could tell me how this can be done using Borg filters.

**Comment by ThomasWaldmann** [comment]
Hmm, there is no /home/me/ prefix in the 3 include/exclude lines. Guess it can't work that way.

**Comment by W0nderer** [comment]
I assumed that `R /home/me` made that the root of the patterns that follow.  What does it actually do?

Tried again with `R /` and the three patterns beginning with `/home/me` - same result.

**Comment by enkore** [comment]
R = root path which is the same as the PATH argument on the command line.

**Comment by W0nderer** [comment]
> R = root path which is the same as the PATH argument on the command line.

If it always has to be the same as the PATH argument why does it have to be given again in the patterns file?  I assumed could be different.  Can it be omitted?

Tried again creating an archive of `~/borg-test` with patterns:
```
R /home/me/borg-test 
+ /home/me/borg-test
+ /home/me/borg-test/d1
- /home/me/borg-test/** 
```
It also includes everything.

**Comment by W0nderer** [comment]
Tried again, commenting out the `+ /home/me/borg-test` as it shouldn't be needed now.  
That excluded the top level file `f0` and directory `d2`, but still included `f1` in `d1`.

It seems that including a directory automatically includes its contents. `+ /home/me/borg-test` also included `f0` and `d2`.  `+ /home/me/borg-test/d1` also includes f1.  This is similar to the problem I raised in issue #2399, how to include a directory but not its contents.

**Comment by W0nderer** [comment]
Tried again, using `!` instead of `-` to exclude everything below `/home/me/borg-test` apart from the `d` directory:
```
R /home/me/borg-test
+ /home/me/borg-test
+ /home/me/borg-test/d1
! /home/me/borg-test/**
```
All files and directories were still included, as when `-` was used.

However when `+ /home/me/borg-test` was commented out nothing was included, not even the `d` directory which was still explicitly specified.   Why does `+ /home/me/borg-test` include that directory and everything below it, but `+ /home/me/borg-test/d1` not even include the directory itself?

**Comment by ThomasWaldmann** [comment]
@edgimar seen that ^^^?

**Comment by edgimar** [comment]
The behavior looks normal to me:  borg will traverse a directory tree, encountering a directory before it encounters the directory's children.  The pattern `+ /home/me/borg-test` matches `borg-test` and everything beneath it, I believe.  So if that pattern is present, everything matches because that pattern is encountered before the others, and if it is absent, then when borg encounters `borg-test`, it is excluded without recursing due to the `!`, so `d1` is never even considered.

**Comment by W0nderer** [comment]
```
R /home/me/borg-test
+ /home/me/borg-test/d1
- /home/me/borg-test/**
```
worked OK thanks in that it included `d1` and all its contents.

`borg help patterns` says that if a pattern ends with a "/" a "*" is appended, which would cause it to also match all the contents of the directory.  So I had assumed that without a trailing "/" `/home/me/borg-test` would match only the directory itself.  Is there any way to match directories but not their contents, as also raised in issue #2399?

Replacing `- /home/me/borg-test/**` with `! /home/me/borg-test/**` excludes everything, even though the `+ /home/me/borg-test/d1` comes first.

**Comment by enkore** [comment]
! means to not recurse, so there would be no chance to apply the + pattern.

**Comment by W0nderer** [comment]
Making it experimental would be OK with me, I realise there are many other issues to be resolved.  All I am using now are very large files of `+ pf:` rules to specify everything to be included.  The list is generated using a script I have written that uses rsync like rules to filter all the pathnames in the tree(s) to be backed up.  A `! sh:**` is prepended to exclude everything else.

The pathname filtering script works in the same way as rsync (top-down, depth first, matching each full pathname) and the `+` and `-` rules have the same semantics as it, including patterns ending with a `/` matching only directories.  It also supports `%` rules, which work like `+` but also match the pathnames of all the parent directories in the pattern, as proposed in #2314.  You are welcome to the code if you want an rsync like solution.  It's in Ruby, but should be easily translatable into Python.

**Comment by ThomasWaldmann** [comment]
I am closing this as it is too unfocussed and unclear whether there is an issue at all.

If there is an issue, re-file it into a more focussed ticket, please.
