### ISSUE TITLE
borg on omnios (lz4 missing)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2474]
I was interested whether one could quickly get borg running on omnios, so I did some experiment.

I started from the vagrant machine, then installed some stuff:

```
sudo pkg update 
sudo pkg install gcc51
sudo pkg install system/header
sudo pkg install versioning/git
sudo pkg install python-34
sudo pkg install python-34/virtualenv
sudo vim /etc/profile # add /opt/python3.4/bin to PATH
sudo reboot 

cd /vagrant/borg
pyvenv borg-env
. borg-env/bin/activate
cd borg
pip install -r requirements.d/development.txt
pip install -e .
```
That's how far I got, now it complains about missing lz4.h and there seems no lz4 package.

**Comment by enkore** [comment]
Might be able to use the package from oi: http://pkg.openindiana.org/hipster/en/search.shtml?token=lz4&action=Search

**Comment by milkey-mouse** [comment]
I got lz4 built:

    pkg install versioning/git gcc51 gnu-make system/header object-file gnu-coreutils
    git clone https://github.com/lz4/lz4.git --branch master && cd lz4
    CC=gcc gmake
    INSTALL=/usr/gnu/bin/install gmake install

I will try to get borg fully working.

**Comment by milkey-mouse** [comment]
After getting lz4 working I found it wasn't too hard to get Borg running:

	pkg install gcc51 gnu-make gnu-coreutils object-file linker system/header python-34 python-34/virtualenv
	echo 'export PATH="/opt/python34/bin:$PATH"' >> /etc/profile && source /etc/profile

	curl -L https://github.com/lz4/lz4/tarball/master | tar -zx && cd lz4-lz4-*
	CC=gcc CFLAGS=-m64 gmake
	INSTALL=/usr/gnu/bin/install gmake install

	CFLAGS="-Wl,-rpath=/usr/local/lib:/opt/python34/lib" pip3 install borgbackup

Should I document this in the Installation section?

**Comment by ThomasWaldmann** [comment]
Not sure if anyone uses this. I only played with it once, like "let's see if borg can run on every OS". :-)

**Comment by milkey-mouse** [comment]
Yeah, when I Google "omnios" the first autocompletion is "omnios dead." Maybe the issue is enough; if so, I guess this issue can be closed.

**Comment by ThomasWaldmann** [comment]
https://github.com/omniosorg looks alive.
but still, I guess it is not popular enough to rectify inclusion into the docs, so it can live here.

**Comment by milkey-mouse** [comment]
In that case, this issue can probably be closed.

**Comment by ThomasWaldmann** [comment]
Yup. Too exotic to go into docs.
