### ISSUE TITLE
--json outputting like --stats

### ISSUE THREAD

**Issue by hyperknot** [borgbackup/borg#2479]
I'm using borg 1.1.0b5. When I run a create operation with --json instead of --stats, the output does not change to json, but stays the same realtime-updating printed line.

```
1.53 GB O 1.45 GB C 1.43 GB D 146767 N imagetiles/7tGehxVL63anDnXK/TileGroup93/8-113-118.jpg
```

Also, I found no place in the documentation which would explain what do the values of this line mean.

**Comment by enkore** [comment]
--stats means the final statistics, not the progress display. This is
also what --json refers to. (See --help / docs).

The meaning of the --progress output is described there as well.

http://borgbackup.readthedocs.io/en/latest/usage.html#borg-create

For retrieving progress output and other log output, I'll refer you to
the --log-json option. See long-form docs there:

http://borgbackup.readthedocs.io/en/latest/internals/frontends.html#logging

Cheers, Marian
