### ISSUE TITLE
Fix random EISDIR errors

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#2482]
Redo of #2455 - we thought it was fixed, but my solution (#2478) only reduced the frequency (if anything).

A stack trace and a lot of debugging info is present in #2048 

Often happens on Travis and almost always on the Vagrant FreeBSD VM.

----

bounty for reliably fixing the EISDIR issue (while not introducing similar, new issues):
https://www.bountysource.com/issues/44848943-fix-random-eisdir-errors

**Comment by PlasmaPower** [comment]
Would I be correct to say we only need fakeroot (instead of root) for a couple xattr tests? It seems to me we're applying fakeroot to a much wider area than it needs. Would a simple `fakexattr` program work?

I guess it's nice for devs to not run the tests as root, but we can still support fakeroot, just not use it for travis.

**Comment by PlasmaPower** [comment]
Oh, and we already have root only tests behind flags, we can just keep those.

**Comment by enkore** [comment]
A custom tool would also be interesting for error-injection. Borg in general has little if any test coverage of error handling, which is bad.

**Comment by PlasmaPower** [comment]
I'm working on this now. We'll need some sort of central DB to synchronize processes though. Would you prefer:

1. an in-filesystem DB (wouldn't require a daemon process, but might be harder if we add multithreading to Borg)
2. a Python daemon
3. a native daemon written in whatever we write the LD_PRELOAD library in

Also, how should we signal to throw errors? I'm thinking maybe an ENV variable, it might be easier to control than other options as ENV variables are applied to both the current process and children.

As for the LD_PRELOAD library itself, I'm thinking Rust, is that OK? I think it's mainly between C, C++, and Rust because we need a lot of low level stuff like `dlsym`. I'd prefer Rust for its macro system and builtin types like Mutex and thread_local, but if we write in in C more people could contribute to it.

**Comment by enkore** [comment]
I believe fakeroot provides user-wide synchronization (so, between process hierarchies), while we don't need that for the tests, since the Remote and Binary tests just fork/exec children. This probably makes it a lot simpler, e.g. a daemon is not required. OTOH a daemon might actually be simpler than using shared memory.

I can think of two broad categories of error injection: (1) For hand-written tests, so we need a way to tell what exactly shall fail (and perhaps how often). This probably implies talking to the daemon/library on an API-level (2) More like a fuzzer, e.g. randomly failing syscalls on the input data set of a `borg create`, because that should never be able to crash it.

It's probably a good idea to keep anything with heavy runtimes (like Python) out of this project.
I've meant to learn Rust for some time now.

**Comment by PlasmaPower** [comment]
Yeah shared memory would probably be more trouble than it's worth as it'd be a pain to make sure everything shared gets allocated in it. At that point we'd probably have to write our own table structure, which would probably be a mess. I think Unix sockets might be a good way to go.

I didn't think about using this as a fuzzer, but that sounds like a good idea too.

I agree that Python isn't a good fit for the daemon, if we end up going with one.

**Comment by PlasmaPower** [comment]
Interesting, it looks like I can have the Rust project create both the lib and the daemon, so I can share a lot of the code for message passing.

**Comment by ThomasWaldmann** [comment]
I noticed some maybe-related bugs where closed while it was believed #2455 is fixed (and that it fixes them also).

But it is not, so can they please get re-opened?

**Comment by PlasmaPower** [comment]
Project status: the daemon is finished (although some parts are untested), and the library has all forms of setxattr fully implemented. The xattr code should work for Linux and OSX. Everything else should work for any Unix platform.

Should the name include borg? Also, should it be under the borgbackup GitHub orginization? I guess the project could be generalized but the xattr overriding is very much Borg specific. I could put that behind a feature flag of course.

**Comment by PlasmaPower** [comment]
I just realized we could also keep it in tree (or as a subrepo, but then people get confused when they git clone without `--recursive`). Instead of having the users install it, we could just build it as part of the tests (maybe have `tox.ini` call a shell script that'll build and run it on Unix platforms). That would solve problems like how the executable finds the library path, as when it's built but not installed they'll be next to each other. Having the test wrapper version strongly linked to the borg version would also be helpful IMHO.

**Comment by enkore** [comment]
I agree, just keeping it in-tree, at least for now, is likely the easiest way.

**Comment by PlasmaPower** [comment]
Finished! Currently integrating it into Borg, and making sure everything works (at least the basics do though).

Should I propagate underlying FS xattrs if they exist? I think that's a good idea, but I haven't implemented it yet.

**Comment by PlasmaPower** [comment]
It would appear Borg is getting its symbols directly from libc (hardcoded). I think that's overriding my program. I don't know how fakeroot worked with that. It might be best to make that code load symbols from my library instead if it sees it in LD_PRELOAD.

**Comment by enkore** [comment]
That's this blob of code: https://github.com/borgbackup/borg/blob/master/src/borg/xattr.py#L71

**Comment by PlasmaPower** [comment]
@enkore Oops, I even added my lib there but I only set XATTR_FAKEROOT not libc_name.

> I don't believe we rely on those anywhere, but I do remember that there is a hack somewhere in place that skips some tests if SELinux is enabled, because SELinux adds some virtual xattrs or something that interfere.

There's one fuse test that gets skipped under fakeroot because of the lack of xattr propogation. Now that I think about it, I could disable the xattr overrides for that test with however we end up doing message passing to the daemon. For that, I'm currently thinking an ENV variable as it would easily propagate to children processes but not to parents or sibling.

**Comment by ThomasWaldmann** [comment]
I am closing #2497 now (without merging) as it is not making progress / needs help, see my recent comment there.

**Comment by ThomasWaldmann** [comment]
Worked around this by #4171 and #4177.

Not a real fix, but if we run as `root` on travis (which we already did for macosx due to no fakeroot there), we do not need fakeroot and thus these issues go away.

Would be cool to have a better solution / a replacement for fakeroot, some work on that is there:

https://github.com/PlasmaPower/borg-test-wrapper

**Comment by ThomasWaldmann** [comment]
As there is no progress here and the problem is not located in borg, but rather fakeroot, I'm closing this now, will fetch the bounty and will re-donate it to general borg funds, so it can be used for other borg stuff.
