### ISSUE TITLE
borg extract: print "No corruption found" on success when running --verbose

### ISSUE THREAD

**Issue by sten0** [borgbackup/borg#2483]
When running extract with --verbose, I believe the expectation is that success is verbose rather than silent.  As far as I can tell this is an easy enhancement that does not depend on issue #840 .  This should be as simple as adding a line to print something like "No corruption found" right before returning the exit state, no?

**Comment by enkore** [comment]
No errors reported, exit code = 0 => no issues.

**Comment by sten0** [comment]
Just to clarify, the request is that "borg extract --verbose" honours the request to be verbose on success.  Would a trivial patch to implement be rejected?

**Comment by enkore** [comment]
Yes. For one because success, warning and failure are already clear by the message (not) output and the exit code, which can also be shown with --show-rc. And because having such a message **only** on extract is inconsistent with all the other borg commands.

**Comment by sten0** [comment]
Thank you for taking the time to explain this, I appreciate it.  I guess
I'll just use a wrapper script for now, since it sounds like even if I
wrote a patch for --verbose/--info for all borg commands, that patch would
still be rejected.

Will the future --verify-data command support the --progress option?
