### ISSUE TITLE
ImportError: dynamic module does not define init function

### ISSUE THREAD

**Issue by rain0r** [borgbackup/borg#2491]
I'm using upstream master (currently commit d8b7aef15c440364d01f6bfc11440ac3b3e5957b). Don't know since when this is an issue (for me). Host system is gentoo with python 3.4.

```
$ borg --version
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/borg", line 11, in <module>
    load_entry_point('borgbackup==1.1.0b6.dev15+gd8b7aef1', 'console_scripts', 'borg')()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 34, in <module>
    from . import helpers
  File "/usr/lib64/python3.4/site-packages/borg/helpers.py", line 38, in <module>
    import borg.crypto.low_level
ImportError: dynamic module does not define init function (PyInit_low_level)
```

**Comment by enkore** [comment]
Do a clean rebuild (e.g. `rm src ; git checkout src`), setup.py has quite a lot of edge cases it doesn't handle correctly.

**Comment by rain0r** [comment]
That didn't work unfortunately.
I even checked out the git repository in a separate dir and installed it (as a user) in a virtualenv. Got the same error.

**Comment by enkore** [comment]
Can you post what commands you're using exactly?

**Comment by rain0r** [comment]
```
$ git clone https://github.com/borgbackup/borg/
$ mkvirtualenv -ppython3.6 borg
$ cd borg/
$ python setup.py install
$ pip install Cython
$ python setup.py install
$ borg --info
```

**Comment by enkore** [comment]
```
git clone https://github.com/borgbackup/borg/
virtualenv -ppython3.6 borg_env
. borg_env/bin/activate
cd borg
pip install Cython
python setup.py install
borg --version
borg 1.1.0b6.dev20+g85df969c
```

**Comment by rain0r** [comment]
That worked for me! Very strange.

**Comment by enkore** [comment]
Just an idea; I don't use virtualenvwrap, but perhaps if you already have some venv named "borg" and then run `mkvirtualenv -ppython3.6 borg`, does that then create another venv? If not then that could cause the issue. FWIW I installed virtualenvwrapper and it works, too.

Using `pip install .` instead of `python setup.py install` might also avoid some issues, since setup.py install sometimes just writes into existing directories of older versions causing all sorts of problems.

**Comment by rain0r** [comment]
I didn't have an existing virtualenv named `borg` but it works with `virtualenvwrapper` and your suggestion `pip install .`. Thanks very much.

**Comment by LucasBartosch** [comment]
Had exactly the same problem. As far as i know i followed the enkores instructions (being the same as the docs). creating a new  ` virtualenv ` and installing therein fixed it though.

**Comment by enkore** [comment]
What might also do the trick is to `pip uninstall borgbackup` first, which probably only works if it was installed using `pip` in the first place, or manually deleting `borgbackup*` in the site-packages.
