### ISSUE TITLE
export to archive

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2492]
Is there simple way to do extract to archive?

For example to tar and possibility to do it via pipe and then compress via pipe with something like pigz?

The case is to provide downloadable backups in archive from remote server.

I see one solution - local mount, nginx, mod_zip and making archive on the fly, but it is not good solution as repo will be locked for a long time and mount is slow compared to export.

**Comment by enkore** [comment]
No. #176 is an older feature request for this.

Either mount + make archive or extract + make archive + remove temporary dir for now.

**Comment by enkore** [comment]
https://borgbackup.readthedocs.io/en/latest/usage.html#borg-export-tar

**Comment by knutov** [comment]
> https://borgbackup.readthedocs.io/en/latest/usage.html#borg-export-tar

@enkore is it save to use 1.1 beta in production?

**Comment by ThomasWaldmann** [comment]
@knutov betas shouldn't be used in production. their main purpose is to find bugs.

of course, if it is not your only backup, nobody holds you back of additionally doing a backup test with borg. this can in fact be useful because some issues only get found in production like scenarios.

**Comment by knutov** [comment]
Thanks, I understand what beta means. Sometimes beta is in fact stable enough and good for production (Sublime can be good example), my question was more about it. But I looked milestones and it looks like format and data can be be broken so I will probably wait the real stable release.

Feature request - It will be good to have an example of this command to run it thru cgi. The case is to make request over some http server, do auth checks in cgi app, add some headers and then send stream from `borg export-tar` to upstream (probably nginx) without storing file locally.

**Comment by enkore** [comment]
If it's really actually CGI, then you roughly want to

1. Send Content-Disposition header to indicate that the response is a download (w/ file name and such)
2. Send Content-Type header (application/gzip)
3. Use Popen to invoke Borg. This depends on your Popen or it's equivalent.

```py
import subprocess

#  run is new in Python 3.5
# see https://docs.python.org/3/library/subprocess.html?#subprocess.run
result = subprocess.run(["borg", "export-tar",  "::" + archive,  "--tar-filter=gzip", "-"], env={
'BORG_PASSPHRASE': '1234',
'BORG_REPO': '/foo/bar',
}, stdin=subprocess.DEVNULL)
# borg inherits our stdout. Since this is CGI, stdout = what is sent to the client. Therefore, .tar.gz ends up at the client

if result.returncode != 0:  # some error happened
  # I dunno; result.stderr should have some error message from Borg.
```

**Comment by knutov** [comment]
Thanks!
