### ISSUE TITLE
[Feature] Add filters to skip compression for pre-compressed files

### ISSUE THREAD

**Issue by randombk** [borgbackup/borg#2493]
A large number of files on a system are already compressed, and will gain little from further compression by borg. Add a series of configurable filters to enable selective disabling of the compression feature for certain files. This should lighten the CPU load and improve performance, while having a minimal effect on the archive size.

**Comment by ThomasWaldmann** [comment]
We had that feature in master branch a while ago, but decided to remove it again as just using the "auto" compression feature (also in master branch and 1.1beta) is simpler and does not require a long configuration file.

borg will then just qualify compressability with lz4 (which is pretty fast) and only if compressable with that, it will apply the desired compression (e.g. zlib or lzma).
