### ISSUE TITLE
Integrate borg.xattr into platform modules

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2495]
Native code (Cythonized or C) avoids the whole "let's go find a libc" mess (including the "let's go and parse LD_PRELOAD and then parse the output of some command")

**Comment by enkore** [comment]
I wrote this a few days ago (<2 hours), and while it provides a comfortable boost to borg create, it will not be integrated into 1.1 (change too large, untested on fbsd, macos).

**Comment by ThomasWaldmann** [comment]
ok, do a PR with milestone 1.2?

**Comment by ThomasWaldmann** [comment]
@enkore do you still have the code somewhere? URL?
