### ISSUE TITLE
hashindex file size limited to 2GiB: backport to 1.0.x

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2498]
See issue #1809 for more details about the issue and PR #2496 for a fix (master branch).

This is fixed in master, do a backport in a while if no issues with the new code pop up.

**Comment by ThomasWaldmann** [comment]
I was under the wrong impression that the index file size limit affects all systems, but it does only affect 32bit systems.

They usually only have max. ~3GiB of usable memory for a process, so there is no huge improvement from 2GiB index size limit now to ~3GiB limit with the fix (or even less, depends on how much other stuff is running and total memory amount / addressing mode).

So we do not need to backport these rather big changes.

**Comment by enkore** [comment]
There would also be the possibility of using _FILE_OFFSET_BITS=64, but I think that one isn't just GCC specific but also ABI specific, so probably not much point trying without having a real build system that can do these things.
