### ISSUE TITLE
Operation not permitted / borg check

### ISSUE THREAD

**Issue by core77** [borgbackup/borg#2499]
Got this error when executing 

> borg check--repair mnt/hidrive/backup

How can i solve this?

***

PermissionError:

 [Errno 1] Operation not permitted: '/home/chris/mnt/hidrive/backup/hints.15449.tmp' -> '/home/chris/mnt/hidrive/backup/hints.15449'

Platform: Linux manjaro 4.9.24-1-MANJARO #1 SMP PREEMPT Fri Apr 21 08:32:28 UTC 2017 x86_64 
Linux:   
Borg: 1.0.10  Python: CPython 3.6.0
PID: 1337  CWD: /home/chris
sys.argv: ['/usr/bin/borg', 'check', '--repair', 'mnt/hidrive/backup']
SSH_ORIGINAL_COMMAND: None

**Comment by ThomasWaldmann** [comment]
Looks like a standard permissions issue in your filesystem.

Do you always use the same user when accessing your repo files?

Mixing root and unprivileged users when accessing a repo can lead to permission issues, so better **always** use the same (unprivileged) user account for repo file access.

You may need to use `chown -R borg.borg repo` (or so) once to fix the mess.
