### ISSUE TITLE
Tests fail to build attic with Openssl >= 1.1.0

### ISSUE THREAD

**Issue by PlasmaPower** [borgbackup/borg#2505]
We should either conditionally disable those tests or patch attic.

**Comment by ThomasWaldmann** [comment]
Another option would be to create an attic repo once and put a tar archive of it into our repo.
IIRC, the only thing we need attic for is `borg upgrade` test (converter from attic).

**Comment by enkore** [comment]
Just freeze an attic repo and put that into the test data, removing the attic dependency entirely?

**Comment by ThomasWaldmann** [comment]
@enkore that was the idea.

I did not check the code yet / did not do experiments whether that would be sufficient though.

**Comment by enkore** [comment]
Didn't see the first line in your post.

**Comment by enkore** [comment]
There are two fixtures, `attic_key_file` and `attic_repo` which would need this treatment. Apart from the fixture creation there is no further dependency on attic.

I'ld just do that now, doesn't look like a lot of work, but my OS is already on OpenSSL 1.1 :D

**Comment by ThomasWaldmann** [comment]
Hmm, looks like we need to solve that before 1.1rc - or we have a problem on all OSes with OpenSSL 1.1.
