### ISSUE TITLE
! pf:/some/dir Does not exclude directory

### ISSUE THREAD

**Issue by W0nderer** [borgbackup/borg#2509]
I have a folder `~/borg-test` containing a file `f0` and directories `d1` and `d2` containing files `f1` and `f2` respectively. When I created an archive of it using the following patterns file:
```
R /home/me/borg-test
! pf:/home/me/borg-test/d1
```
it included all files and directories, and did not exclude `d1`.
Using `-` instead of `!` didn't exclude it either.

This is using the standalone binary borg-linux64 of version 1.1.0b5

**Comment by enkore** [comment]
Sounds like the same issue as #2470?

**Comment by W0nderer** [comment]
In some ways it's the mirror image of #2470.  In that either the `+ /home/me/borg-test/d1` wasn't including `d1` when it should or the `! /home/me/borg-test/**` was excluding it when it shouldn't.  When the patterns file contains both `+` and `-` it's not always clear which isn't working as expected.  In this case `! pf:/home/me/borg-test/d1` isn't excluding `d1` when it should.
