### ISSUE TITLE
convert to click for command line parsing and dispatching

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#251]
it was informally discussed (on IRC) the idea of converting the current tangled mess of argparse calls into the much cleaner [click](http://click.pocoo.org/5/) dispatcher.

this could get rid of a lot of code in `archiver.py` and make borg easier to extend.

it seems that click works in both 2.7 and 3.3 or higher, so it could be a problem until we drop support for 3.2 (#65).

**Comment by anarcat** [comment]
i tested click quickly in https://github.com/borgbackup/backupdata/pull/1

it is kind of cool, but it's very idiomatic... for example, you can't have `help=` on "arguments". they somewhat assume they are sub-commands, which is fine for some times like `serve`, `create` and so on, but will be more annoying for the arguments to those commands, which will need to be described in the dispatcher's doc string.

i was also able to have a backwards compatibility layer to avoid depending on click, which may be nice...

**Comment by anarcat** [comment]
some parts of click are not so elegant:

http://click.pocoo.org/5/options/#boolean-flags

`@click.option('--shout/--no-shout', default=False)`

> Boolean flags are options that can be enabled or disabled. This can be accomplished by defining two flags in one go separated by a slash (/) for enabling or disabling the option. (If a slash is in an option string, Click automatically knows that it’s a boolean flag and will pass is_flag=True implicitly.)

i would have expected this to be magic, ie. that you would not have to specify `--no-whatever` at all...

**Comment by anarcat** [comment]
i don't know... i haven't used it much. i would say it's pretty likely to stumble upon at least *some* issues with the current arg parsing: if there's some weird stuff we do right now that is not supported in click, it will be hell to workaround. i think actual bugs are less likely, especially since we have unit tests for a lot of the archiver interface (don't we?). bugs in click are not very likely either: there have been regular and recurrent releases of click, so bugs are probably fixed quickly when/if found. the pulse looks good:

https://github.com/mitsuhiko/click/pulse/monthly

my concern is mostly over the work required in rearchitecturing the current code to fit click's idioms. it's a huge gain to have that stuff going, but it's also a little more obscure for people not familiar with it, and creeps into dispatching and I/O a lot more than i expected (for example: click does progress bars!)...

**Comment by ThomasWaldmann** [comment]
this rather sounds like after 1.0.

**Comment by ThomasWaldmann** [comment]
see #6551.
