### ISSUE TITLE
Optional space limit

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2517]
Server admins using borg should be able to specify a space limit in `borg serve` to prevent users from uploading too much data and thus abusing the service (and e.g. making it unavailable for other users), potentially also somehow DOSing it.

Maybe e.g. `borg server --limit-space 1TB`.

**Comment by ThomasWaldmann** [comment]
note: borg 1.1 will have a "keep a minimum of free space" feature, but not a limit on repo size.

maybe the latter could be enforced by disk quota, but interaction of these 2 should be tested then.
