### ISSUE TITLE
borg id REPO[::archive] command

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2522]
that just outputs the repository / archive id in hex.

**Comment by enkore** [comment]
I'd rather have a `info --without-cache` or something like that.

**Comment by ThomasWaldmann** [comment]
i wanted something easy for scripting, so one can just get that string into a variable, e.g. to kill some files / dirs.

**Comment by enkore** [comment]
You can also

```
$ borg list ... --json | jq  --raw-output .repository.id
8af7b721153c0923b910dc10b2264abdec737f552ff208cc111cf3447c980f9b
$ borg info ...::... --json | jq --raw-output '.archives[0].id'
b9ab8a03a9fe0c8591b24e8e14a32e6bd7aaa8d1d460bb1ec3411c9a045f81db
```

**Comment by ThomasWaldmann** [comment]
Yeah, you can always couple some commands to get what you want, but the emphasis in this idea was a **simple**, direct way without sed/awk/jq/...

**Comment by ThomasWaldmann** [comment]
we already have `borg config REPO id` to output the repo id.
not sure we need the archive id.
