### ISSUE TITLE
Harden key handling

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2525]
- Erase passphrase at the earliest possible moment (cf. `_passphrase`), note that we cannot delete it from /proc/.../environ
- Do not keep cryptographic keys around in Python objects
- Use secure memory for cryptographic keys

  This is offered by e.g. sodium_malloc. It works by aligning the data to the end of a page and mprotect()ing the *following* page with PROT_NONE. The remainder of the first page is filled with canary data. Finally another guard page is placed before the page containing the data. All three pages are mlock()d as well, to avoid swapping. Inclusion in core dumps is prohibited as well (MADV_DONTDUMP).

  Freeing memory checks the canaries and securely erases the contained data.
- It might be possible to erase /proc/PID/environ using the PR_SET_MM_ENV_START prctl; if it works, it requires capabilities/root and a kernel option.
- (Hippie idea: Fork a process that does crypto and only crypto and communicates via stdin/out/err with the parent)

Split up into separate tickets, possibly with bounties, as needed.

**Comment by ThomasWaldmann** [comment]
superseded by smaller tickets, see links.
