### ISSUE TITLE
Don't perform full Travis build on docs-only changes

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2531]
The build takes forever and a day and it's not really nice to have to manually abort it.

facebook/react#1768 and facebook/react#2000 show how to do this properly.

**Comment by narendravardi** [comment]
@enkore, can i work on this?

**Comment by enkore** [comment]
sure!

**Comment by narendravardi** [comment]
Now we have to make changes in such a way that for changes in docs folder, travis will not perform any build. Am I Correct or do i miss any files?

Please let me know if I miss any files.

**Comment by enkore** [comment]
docs/ is correct

**Comment by ThomasWaldmann** [comment]
There is also README.rst and AUTHORS in toplevel dir which can be considered doc files, but they change less frequently.

**Comment by narendravardi** [comment]
@ThomasWaldmann Even though they change less frequently, i think it's better to include these as well. I will raise a PR to stop build when the modified files does not include anyother files other than docs, README.rst and AUTHORS.
Please let me know if any changes are required.

**Comment by enkore** [comment]
Fixed by #2707
