### ISSUE TITLE
Investigate brew errors on Travis

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2532]
Sometimes OSX builds fail in the install phase with this error:

```
$ ./.travis/install.sh
++uname -s
+[[ Darwin == \D\a\r\w\i\n ]]
+brew update
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
+brew update
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.

The command "./.travis/install.sh" failed and exited with 1 during .

Your build has been stopped.
```

It might be related to the caches, but usually goes away by just restarting the build in question.

**Comment by enkore** [comment]
They're a bit frequent today. 

Recently the question was raised whether this is actually necessary, since Travis already runs this before the install script.

**Comment by ThomasWaldmann** [comment]
Still seeing this, but fix is unclear.

As the error we see is "Another active Homebrew update process is already in progress.", there seems to be something running in parallel to our install.sh.

So it's not clear how we can work with brew at all if brew is already active in the background somehow.
Or how we can be sure that brew update is finished when our testing starts.
