### ISSUE TITLE
Very confusing error message when _version.py contains misdetected version

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#2538]
When installing borg from a git repository without tags or when setuptools_scm can not get the correct version for some other reason, borg fails with very confusing error messages.

```
borg list: error: argument REPOSITORY_OR_ARCHIVE: invalid validator value: '/tmp/borg-repo'
```

*How to reproduce:*
easiest way without messing up the repository is to replace _version.py with
```
version = '0.1.dev1+aaaa'
```
But installing from a git repository without tags should reproduce this too.

*Cause:*
While parsing arguments `replace_placeholders` tries to use the version, but throws an exception which is somehow replaced by a confusing message in the argument parser exception handling.
```
>>> borg.helpers.Location('/tmp/borg-repo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/sw-dev/borg/src/borg/helpers.py", line 979, in __init__
    if not self.parse(self.orig):
  File "/home/martin/sw-dev/borg/src/borg/helpers.py", line 983, in parse
    text = replace_placeholders(text)
  File "/home/martin/sw-dev/borg/src/borg/helpers.py", line 696, in replace_placeholders
    'borgpatch': '%d.%d.%d' % borg_version_tuple[:3],
TypeError: %d format: a number is required, not str
```

*Possible solution:*
Do some sanity checking in `borg/__init__.py` and abort early with a clear error message?

**Comment by RonnyPfannschmidt** [comment]
i'll take a look at this one

**Comment by RonnyPfannschmidt** [comment]
the problem arrises from a custom repo having bad tags - a good solution needs a bit more discussion
