### ISSUE TITLE
Archive name placeholder {now} does weird things

### ISSUE THREAD

**Issue by OlliC** [borgbackup/borg#2543]
Hi, 

when using archive name placeholders i get some strange results. This is borg version 1.0.10 on Arch Linux. 

This is the archive name i use (exactly like provided in 'borg help placeholders' ): 
`'{hostname}-{now:%Y-%m-%d_%H:%M:%S}'`

This is the result: 
`Archive name: viki-2017-b454999f3eae497886e6183d96d436a5-21_viki:22:32`

{hostname} is ok.
%Y is ok. 
%m should be the month of the year, right? Why its "b454999f3eae497886e6183d96d436a5" ?
%d is ok.
%H should be Hour, but is the hostname again?
%M is ok. 
%S is ok.

**Comment by enkore** [comment]
Works for me. Can you share the command line you are using (and which shell)?

**Comment by OlliC** [comment]
I just wanted to share my systemd service file then it dawned on me. systemd has its own placeholders. 
%m is the machine ID and %H is the hostname there.

**Comment by OlliC** [comment]
Ok. After some searching around i found the answer. I just had to "escape" the parameterization by doubling up the percent signs. systemd's parameter expansion turns %% into %. Maybe you could put a hint in the documenation about that.

`'{hostname}-{now:%%Y-%%m-%%d_%%H:%%M:%%S}'`

**Comment by enkore** [comment]
systemd/systemd#624

**Comment by ThomasWaldmann** [comment]
Just a a side note:

One can also just use `{now}` without giving a format when one is happy with the default format.
