### ISSUE TITLE
borg stable crashes after ooming hard on borg create

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#2548]
this happens with the borg on fedora (1.10)

the backed up folder is a archive mounted by master (which fixes llfuse #2534 )

i am now re-testing with master doing the backup as well

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/45434280-borg-stable-crashes-after-ooming-hard-on-borg-create)

The bounty is for finding the specific root cause for the excessive memory consumption in borg's code.

**Comment by enkore** [comment]
Can you post the trace back (if any)?

**Comment by RonnyPfannschmidt** [comment]
@enkore there is no stack trace,

last night i did let it run for a complete night, and in the morning i got the message borg was killed,
then i reran it again and after half an hour of no longer being able to use the system i rebooted by power-cycling

**Comment by enkore** [comment]
Ok. If I understand correctly, then the first run ran out of memory. Then, you started another run, but the system wasn't stable any more?

I'm not sure if there is anything to fix here; the system instability was probably caused by the memory pressure (it would be typical behaviour). You could try to reduce the memory footprint by using --no-files-cache if you didn't disabled it already.

**Comment by RonnyPfannschmidt** [comment]
@enkore no - the problem is that before running out of memory the system is grinding to a pause for a few hours, i didnt have the time to wait for linux to go from swap of death to true oom

i now restarted the command with a ulimit of 12 gb memory on borg master doing the backup

**Comment by enkore** [comment]
I see. You might be interested in early_oom, which somewhat alleviates Linux' tendency to throw a tantrum under memory pressure.

**Comment by RonnyPfannschmidt** [comment]
the issue does not seem to happen on master anymore

**Comment by RonnyPfannschmidt** [comment]
would it be sensible to auto-impose memory limits for borg processes to avoid such issues in general?

**Comment by ThomasWaldmann** [comment]
Maybe most interesting here is what exactly is eating all (12GB?) of the memory and whether that is expected for what you are doing or not. Depends a lot on the amount of data being processed.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann i havent figured that one - i can try to rerun later, but its bascially all about running a "import" on a repository thats about 5 TB of backup data condensed down to about 266 gb due to duplication individual backups being between 50gb and 600 gb

the oom happens on the last release on fedora, it doesnt happen on master

i do have 16 gb of ram and 8 gb of swap, and borg was happily eating almost all of it (so think borg using about 20 gb there)

**Comment by enkore** [comment]
Is memory usage significantly different between 1.0.x and master, or is it just a small difference (enough to not eat everything?).

Either way -- 12+ GB is a huge amount of memory for Borg.

**Comment by RonnyPfannschmidt** [comment]
when i checked/watched (which is not perfect coverage) master was sitting at around 2gb, i suspect/fear it would have happily used more on 1.0.x if i had more memory/swap

**Comment by ThomasWaldmann** [comment]
is it clear which one of the 2 borgs ate all the memory?
borg mount? borg create? both?

**Comment by RonnyPfannschmidt** [comment]
borg create ate the memory

* borg mount was on master
* borg create on 1.0.10 ate the memory
* borg create on master worked fine

this whole issue happened while importing the archives of a semi-legacy borg repo (some attic sized chunks, some new gen sized chunks) into a fresh borg repo

**Comment by ThomasWaldmann** [comment]
Would be cool to find out the root cause and whether it can be fixed in 1.0-maint before we release 1.0.11(rc).

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann the task i used to cause it takes a few days to run - for personal reasons its rather uncertain to be promisable/soonish

**Comment by ThomasWaldmann** [comment]
Maybe it can be found more quickly, by comparing 1.0-maint to master, reading master changelog, monitoring memory usage (does it creep upwards permanently?), ...

**Comment by RonnyPfannschmidt** [comment]
for the most part memory usage was stable around 2-3 gb - it shot up at one particular archive and i believe at a very particular time-frame, so i wildly guess that its running into a small logic bug causing some kind of endless loop

**Comment by ThomasWaldmann** [comment]
Note: a temporary peak in memory usage happens when the chunks hashindex gets enlarged (temporarily has current AND enlarged hashtable in memory).

**Comment by enkore** [comment]
Some thoughts:

- Can't be a recursion issue (say, accidental directory loop due to hardlinked dirs), because we recurse on the Python = C stack, which explodes looong before we're talking about 10 GB.
- There aren't many unbounded structures (indices and cache would be noticeable due to storage use). Mainly the hard_links and ignore_inodes. The latter is always small. The former grows linearly with the number of hardlinks. Then there is the files cache, which can get really big. It's also kept in memory all the time while `borg create` does not generally need that.

I don't know how cumbersome this is to reproduce for you; perhaps take another shot using `--list`. I suppose doing something like `borg create ... --list | awk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0; fflush(); }'` parallel to a similar pipeline with pgrep or so (to get the memory usage of borg processes) could simplify it a bit.

**Comment by RonnyPfannschmidt** [comment]
@enkore it takes a borg run of about 2 days to hit the situation, i#ll try to engage once i find some more time to start it and let it run, (unfortunately this will likely be next month)

**Comment by ThomasWaldmann** [comment]
any news?

**Comment by ThomasWaldmann** [comment]
As there seems no progress at all, I am removing this from next-rc milestone again.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt any news?

do you have a skylake/kabylake cpu with hyperthreading?

**Comment by milkey-mouse** [comment]
Does the problem still manifest with a memory limit (e.g. run in a shell with `ulimit -Hv 131072` to limit to only 128M of memory)?

**Comment by ThomasWaldmann** [comment]
@milkey-mouse it's not a good idea to run borg with very low memory limits, it will run out of memory just by normal operations. If one want to limit memory to get MemoryError for some memory leak faster, one needs to consider repo index size, chunks index size, files cache size. Whatever is used need to fit into memory + some free space to maybe resize it to next level and also some other memory needs.

**Comment by ThomasWaldmann** [comment]
Gonna close this in a week if there is no progress / no more information.

**Comment by RonnyPfannschmidt** [comment]
sorry, due to earlier arrival of the kid i probably wont be able to provide more details in near future

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt no problem. if it is still a problem, someone else will reopen this or open a new bug.

**Comment by ThomasWaldmann** [comment]
I'll claim the bounty now to my personal account to immediately donate it to the borgbackup account again.
