### ISSUE TITLE
$ support the project? gratipay or flattr for borg?

### ISSUE THREAD

**Issue by mmagnus** [borgbackup/borg#2550]
You guys, have you consider to start https://gratipay.com, or https://flattr.com or anything else to support the developers? I would love to support the project with some cash regularly. What do you think?

**Comment by ThomasWaldmann** [comment]
Well, we have this:

https://borgbackup.readthedocs.io/en/stable/support.html#bounties-and-fundraisers

**Comment by mmagnus** [comment]
aaaaa OK, so since I didn't find it (but I was not searching deeply I guess), this information could be included in readme :-) If you wish.

Thanks. I guess we're done.

**Comment by enkore** [comment]
With Bountysource you can give the borgbackup org money (which we will then assign to issues/things) or you can put bounties on specific issues / things you specifically want yourself.

**Comment by mmagnus** [comment]
Yes, yes, no I see it. Super cool platform. I'll use it! Thanks!

**Comment by ThomasWaldmann** [comment]
Shall we link to that from README to give it better visibility?

**Comment by enkore** [comment]
There is a link there: https://github.com/borgbackup/borg#links

But perhaps giving it a bit more visibility wouldn't hurt.

**Comment by ThomasWaldmann** [comment]
TODO: Add more visible link to that section (with a bit of text) to the README.

**Comment by mmagnus** [comment]
I was looking for a badge to support, e.g. http://blog.bountysource.com/post/87257081709/bountysource-badges but it might be only my personal bias to look for badges to support ;-)

**Comment by ThomasWaldmann** [comment]
@mmagnus see #2558.
