### ISSUE TITLE
Make safe roll-back work on ZFS/Btrfs

### ISSUE THREAD

**Issue by suuchan** [borgbackup/borg#2557]
In _repository.py_ the code to roll back a transaction because there is no space left on the file system looks like this:

>     def cleanup(self, transaction_id):
>         """Delete segment files left by aborted transactions
>         """
>         self.segment = transaction_id + 1
>         for segment, filename in self.segment_iterator(reverse=True):
>             if segment > transaction_id:
>                 os.unlink(filename)
>             else:
>                 break

Unfortunately this does not work well on 'modern' CoW file systems such as ZFS or Btrfs. If these file systems are full, even a delete as root is not possible any more because of how CoW works. This is a well known problem:

- http://www.surlyjake.com/blog/2010/01/19/zfs-cant-rm-no-space-left-on-device/
- https://serverfault.com/questions/478733/rm-can-not-remove-xxx-no-space-left-on-device-on-btrfs

The trick is to free up space by 'emptying' a file. The above function should therefore do a

>    f = open(filename, "rw")
>    f.truncate();

before the os.unlink(). I find a total of 20 os.unlink() calls in the whole source. To better support the two above file systems I suggest to re-visit each of them, to check if a no space situation is possible and add the truncate code.

https://www.bountysource.com/issues/45481976-make-safe-roll-back-work-on-zfs-btrfs

**Comment by ThomasWaldmann** [comment]
Ah, interesting. Do you want to make a PR (against master branch) for that?

In borg 1.1 (master), you can configure a minimum amount of space to keep free, so you can avoid the filesystem completely filling up. Considering the above, maybe we should check the default value of this.

**Comment by enkore** [comment]
That's a pre-commit check to avoid dangling commits (i.e. commit in segments, index not written, need segment replay to recover). See https://github.com/borgbackup/borg/blob/master/src/borg/repository.py#L431

It is not checked while writing client data (PUT).

**Comment by suuchan** [comment]
The fix is trivial but I'd rather let you guys do this right for 1.1. Can you enable this issue on bountysource to put a bounty on it?

**Comment by ThomasWaldmann** [comment]
@suuchan you can just copy & paste the issue url into the bountysource search box to start a bounty.

**Comment by ThomasWaldmann** [comment]
claim :)
