### ISSUE TITLE
check backup then alert if something wrong

### ISSUE THREAD

**Issue by x86fantini** [borgbackup/borg#2561]
Hello, i've been using Borg from a while and i'm pretty happy. I would like to use the "check" function in conjunction with alerting if backup is non consistent.

i'm reading http://borgbackup.readthedocs.io/en/stable/usage.html#borg-check

has anyone implement a succesfull alert policy? i have monit installed, maybe this can help

thank you

**Comment by ThomasWaldmann** [comment]
hmm, seems like noone wanted to give the obvious answer here.

a borg process always returns a return code (rc) to the caller (e.g. to the shell).

0 == success, 1 == warning, 2 == error.

There is also the `--show-rc` option to log that rc.

How to interface that to monit is out of scope of the borg project.
