### ISSUE TITLE
Allow disabling chunks.archive.d before first cache sync is done.

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#2571]
We currently recommend creating `chunks.archive.d` in the cache directory as file to disable the chunks archive.
At work we want to do this before the repository is accessed the first time from a given system.
So my first attempt was to create the cache directory and place create a file `chunks.archive.d` there. But borg assumes that when the directory exists that it must contain a cache with a valid configuration file. This of course was not the case.
Design space:
* Change the detection for a existing cache to use e.g. the existence of the config file as indicator (this would solve the problem for expert user who can actually created the needed directory from the repository id, but this doesn't sound to nice)
* Add a (global) command line option to disable the chunks archive (that maybe persists this setting?)
* Add a more hidden way to enable this (environment variable, etc)

**Comment by enkore** [comment]
Hack: Run borg info and kill it after a few seconds, then replace c.a.d with a file.

**Comment by textshell** [comment]
@enkore i wouldn't dare to try to get that hack through review^^

Way easier would be to implement one of the ideas above. I just fear an global option is unwanted clutter and the others are strange or to hard for normal users to use.

I just had another idea:
* Add a "borg tune" command that given a repository path can be used for things like this. This would have a rather wide open scope for all kinds of misc settings when and es they are wanted.

**Comment by ThomasWaldmann** [comment]
+1 for some nice way to deal with this.

**Comment by enkore** [comment]
Sure, just a suggestion until a release gets out with that functionality.

**Comment by knutov** [comment]
if something like `test -e` inside code is used why just not to check some environment variable for the same for example? Should be trivial I think.
