### ISSUE TITLE
Testsuite requires writable /var/tmp

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2582]
test_get_cache_dir, test_get_keys_dir and test_get_security_dir do `monkeypatch.setenv('XDG_CONFIG_HOME', '/var/tmp/.config')` and expect implicitly that get_XYZ_dir() can create some directories there.

Change them to use tmpdir (the py.test fixture) instead.

**Comment by ThomasWaldmann** [comment]
why should /var/tmp be not writable?

**Comment by enkore** [comment]
My bad. Some leftover files from a CI user; /var/tmp should be world-writable.
