### ISSUE TITLE
Cannot use relative paths

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2583]
I tried to switch my absolute paths to relative ones following https://borgbackup.readthedocs.io/en/stable/deployment.html. (I use `--restrict-to-path` on the server)
This worked for two clients, but for one it did not work. I always got "Repository path not allowed" (= that's literally the only output, BTW) Using the full path did always work .
I used a very similar configuration for one of the other clients, so this is really a mystery for me.
Could it be related to the version of borg?

client: borg 1.0.10
server: borg 1.0.9

**Comment by enkore** [comment]
Interpretation of relative paths probably depends on the $HOME of the SSH user.

**Comment by rugk** [comment]
Uhh, but it's the same linux account on the backup server and the path is not relative to `~`. It just cd's to the right dir and then uses `./dir` as the path…

**Comment by ThomasWaldmann** [comment]
@rugk does this still happen and if so, can you add the precise/full borg commands you use and the precise/full error msgs you get?
