### ISSUE TITLE
Feature request: Checkpoints in the middle of a file

### ISSUE THREAD

**Issue by Clete2** [borgbackup/borg#2603]
Is there a reason why checkpoints in the middle of a large file are infeasible?

Per [the documentation](http://borgbackup.readthedocs.io/en/stable/faq.html?highlight=checkpoint#if-a-backup-stops-mid-way-does-the-already-backed-up-data-stay-there):

> Checkpoints only happen between files (so they don’t help for interruptions happening while a very large file is being processed).

I'm copying a 52GB file over a slow and unreliable connection which also happens to have a data cap, and I've used over 100GB of transfer to get this file over there. I've considered using `rsync` to get the file over there and then use `borg` to put that file in locally and then resume my remote backup. Is there a reason why checkpoints happen in between files?

**Comment by enkore** [comment]
Yes, its simpler. This is implemented in 1.1 beta, see #1198

http://borgbackup.readthedocs.io/en/latest/faq.html#how-can-i-backup-huge-file-s-over-a-unstable-connection
http://borgbackup.readthedocs.io/en/stable/faq.html#how-can-i-backup-huge-file-s-over-a-unstable-connection

**Comment by Clete2** [comment]
Thank you. I'm sorry, I didn't search well enough. :) I did not find #1198.

**Comment by enkore** [comment]
No need to be sorry :)
