### ISSUE TITLE
Progress line with huge files

### ISSUE THREAD

**Issue by sergiocallegari** [borgbackup/borg#264]
Hi,

looks like borg only updates the progress line when it moves to a new file. This means that when one has really big files the information is never updated and the progress option has very limited use.

Do you think it could be possible to have the information updated ever n chunks where n is a suitable number?

Thanks for the attention!

**Comment by ThomasWaldmann** [comment]
yeah, that would be nice.

currently, the code is just at a place that is not visited while it works on 1 file, just when it switches to next file.

**Comment by anarcat** [comment]
#314 could help with this.

**Comment by ThomasWaldmann** [comment]
related: #500

**Comment by ThomasWaldmann** [comment]
this was already fixed in master branch a while ago (the new progress indication updates multiple times per seconds - not only in between files).
