### ISSUE TITLE
borg extract --stdout also writes to disk when dir is restored

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2645]
From the doc I would have expected that `borg extract --stdout` *only* writes to the STDOUT. However, it actually writes to stdout and – as usual without the parameter – to the file path.

IMHO this is unexpected, or is this even a bug? (borg 1.0.10)

Actually I am also not sure what would happen if you restore a RAW device like in your doc example:
```shell
$ borg extract --stdout /path/to/repo::my-sdx | dd of=/dev/sdx bs=10M
```

Maybe the file is dumped somewhere too, or in this case it works as I expected? I only tested it with a usual text file.

**Comment by ThomasWaldmann** [comment]
Please give the complete sequence of commands you used and a directory listing with the unexpected files.

**Comment by rugk** [comment]
Ahh, I think I got the issue, I accidentially extracted a directory instead of a single file.

```shell
export BORG_REPO
[…]
borg extract ::ARCHIVE_NAME home/…/dir --stdout > file.txt
` `

**Comment by rugk** [comment]
Still a strange behaviour. Maybe you rather want to show an error message?

**Comment by ThomasWaldmann** [comment]
well, trying to write directories (or other non-file-like items) to stdout is kind of unexpected. :)

**Comment by rugk** [comment]
It is, and it makes it even stranger when this actually (somehow) "works"…

**Comment by enkore** [comment]
--stdout must not write to disk.
