### ISSUE TITLE
refactor load factor margin computation into hashindex init

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2646]
from @enkore in PR discussion:

it would probably be nicer if the capacity given would actually be the usable capacity, i.e. if `hashindex_init` or `HashIndex.__init__` already added the necessary load factor margin.

**Comment by Xavier-J-Ortiz** [comment]
Hello! I'd like to take a stab at this if it's still open.

Full disclosure, you guys deem it OK, this would be my first time attempting to contribute to an open source project.

I would appreciate any help, might need some help getting started with this. I love using borg, it's shaved time off of my backups, especially VM images. Would love to give back. :smile:

**Comment by ThomasWaldmann** [comment]
IIRC it is still todo, go for it! ;-)

If you have something, open a pull request to get feedback for it.

http://borgbackup.readthedocs.io/en/stable/development.html

**Comment by Xavier-J-Ortiz** [comment]
Actually, I think I'm going to relinquish this.
I think some of the files that I need to understand are in cython (I've worked with python, not cython), and it's a bit over my head to be honest.

Sorry about that.

**Comment by ThomasWaldmann** [comment]
OK, no problem.

**Comment by ThomasWaldmann** [comment]
`hashindex_init` (C code) should stay as it is as it is called by hashtable resize C code with specific sizes to up- or downsize (following specific pre-computed sizes, not just double/half or similar trivial policy).

`IndexBase` (Cython) looks like a better place for this.
