### ISSUE TITLE
pytest-xdist 1.17.0 breaks all testing

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2647]
https://travis-ci.org/borgbackup/borg/jobs/241229446 (master)
https://travis-ci.org/borgbackup/borg/jobs/241460695 (PR)

Reproduces locally, 1.15.0 works, though.

**Comment by enkore** [comment]
This is https://github.com/pytest-dev/pytest-xdist/issues/157

**Comment by textshell** [comment]
can/should we pin this somehow to a working version until this is fixed?

**Comment by ThomasWaldmann** [comment]
https://github.com/pytest-dev/pytest-xdist/pull/158 this is already approved. guess we'll see a fix release soon.

we can pin to a working version until it is released.

**Comment by enkore** [comment]
Pinning doesn't buy much, since it does not help topic branches (PRs), unless they're rebased. Looks like it's going to be resolved real soon now anyway.

**Comment by nicoddemus** [comment]
Yep, I'm preparing the release right now. 👍

**Comment by enkore** [comment]
Thank you!

**Comment by nicoddemus** [comment]
`1.17.1` is now out, sorry guys for the inconvenience.
