### ISSUE TITLE
Dry Run Statistics

### ISSUE THREAD

**Issue by storcium** [borgbackup/borg#265]
Would it be possible to display statistics (such as in borg info) for dry run?  This would be to tune expected backup time, compression and chunker parameters.  Perhaps also display statistics at the end of backup?

**Comment by ThomasWaldmann** [comment]
I assume we are talking about `borg create`. 
With dry_run it only does the directory traversal, it does not process the files.
So there can't be chunk / compression / time stats.

**Comment by storcium** [comment]
Got it, thanks.  In that case maybe on create.  I was actually wondering how one would go about tuning chunk sizes using some unknown data.

**Comment by ThomasWaldmann** [comment]
I personally tend to rather big chunks.

One may lose a bit of deduplication, but one saves a lot on resource usage (on disk, in memory, in time needed to deal with it).

**Comment by storcium** [comment]
Would that be such as 19,23,21,4095 we have discussed before?

**Comment by ThomasWaldmann** [comment]
Yes, that creates ~2MiB chunks in the statistical medium.

**Comment by storcium** [comment]
Thank you.  Makes sense.  I suppose we could just run borg info after a
session to see what we got in terms of deduplication ratio.

--
Alex Gorbachev
Storcium

**Comment by ThomasWaldmann** [comment]
btw, if you change chunk size in a existing repo, you of course will get no deduplication to older backups as the chunk size changes. so, IF a file changed since the last backup the whole file will be put in the repo (using the new chunk size). it will not put all files into the repo because of the files cache - if a file did not change since last backup, it will just be skipped and not chunked.

**Comment by storcium** [comment]
On Thursday, October 8, 2015, TW <notifications@github.com> wrote:

> btw, if you change chunk size in a existing repo, you of course will get
> no deduplication to older backups as the chunk size changes. so, IF a file
> changed since the last backup the whole file will be put in the repo (using
> the new chunk size). it will not put all files into the repo because of the
> files cache - if a file did not change since last backup, it will just be
> skipped and not chunked.
>
Thanks, this is important to know.  I found that in the 1-2 TB space we
work in dedup with 2 MB chunks reduced roughly in half, whereas the
business change is described as 10% per day.  I do realize there is a lot
of metadata in databases, and this is on OpenVMS platforms.  On UNIX
platforms we have achieved a 96% reduction in a 1TB test.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borgbackup/borg/issues/265#issuecomment-146668083>.
>


-- 
--
Alex Gorbachev
Storcium
