### ISSUE TITLE
make swidth better available

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2667]
`borg.platform.swidth` is currently only made available on linux, freebsd, os x.

but it also works on:
- cygwin
- openindiana

**Comment by enkore** [comment]
A bit confusing: swidth and umount are imported from posix in freebsd/darwin and the imported in init from there. Perhaps change this to just import directly from the posix module; avoids unused superficially unused imports and makes it more clear where these functions come from. It's all platform dependent anyway.
