### ISSUE TITLE
condensed 1.0 to 1.1 changelog

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2683]
Prepared here:

https://github.com/borgbackup/borg/wiki/Borg-1.1#draft-release-announcement--change-summary

**Comment by ThomasWaldmann** [comment]
@enkore how did you make that?

a) did you go through all beta changelog, picking all interesting pieces?
b) or did you just write down what came into your mind?

**Comment by enkore** [comment]
b) for major new stuff (I included a bunch of smaller things which were frequent annoyances in 1.0, like check's progress stuff), a) for compatibility.

**Comment by ThomasWaldmann** [comment]
OK, maybe there should be some final entry like:

"These are just the major changes, for lots of smaller changes please see the beta/rc changelogs."

**Comment by ThomasWaldmann** [comment]
@enkore so, the intention is to link to the Borg-1.1 wiki page in the 1.1.0 release announcements?

There is a "Contributors" section on the wiki page. We used to not credit contributors from the handmade "changelogs" (just in CONTRIBUTORS file and git history). Do you think we should change that? That has pros (fame!!1, motivation, ...) and cons (more stuff to read for the normal user).

**Comment by ThomasWaldmann** [comment]
Or is the intention to copy the wiki page to changes.rst at 1.1.0 time?

**Comment by enkore** [comment]
[something like that](https://pstore.enkore.de/borg-1.1.html)

**Comment by ThomasWaldmann** [comment]
Hmm, you included developers in the "donated funds" list?

**Comment by ThomasWaldmann** [comment]
OK, that's easier to read than having individual changes with their contributors.

So the plan is to have higher-level changelogs for 0.x, 1.0, 1.1 initial releases as single page per version in sphinx docs?

And have changes.rst for the more detailled stuff that includes all beta/rc/patch releases?

**Comment by enkore** [comment]
> Hmm, you included developers in the "donated funds" list?

those who donated ... this list is from BS

> as single page per version in sphinx docs?

release series go to borgackup.org ... should be indepedent from the strictly versioned docs (=*only* things that are versioned with a release should be in its docs, everything else causes trouble — see development.rst changes for a good example, /stable/ is half a year out of date).

> And have changes.rst for the more detailled stuff that includes all beta/rc/patch releases?

yes

**Comment by ThomasWaldmann** [comment]
Guess we are finished with that.

**Comment by ThomasWaldmann** [comment]
Hmm, except putting it on the homepage.

**Comment by ThomasWaldmann** [comment]
is there a caching issue on borgbackup.org? i still see old content there.

**Comment by enkore** [comment]
Couple hours edge and browser caches.
