### ISSUE TITLE
`pathconf(..., _PC_NAME_MAX) == 0` in borg mount

### ISSUE THREAD

**Issue by mpartel** [borgbackup/borg#2684]
When I use `pathconf(..., _PC_NAME_MAX)` to allocate space for `struct dirent` as described in [`man 3 readdir`](https://linux.die.net/man/3/readdir), I get back 0. [`man 3 pathconf`](https://linux.die.net/man/3/pathconf) says it should return -1 on error.

Original bindfs bug: https://github.com/mpartel/bindfs/issues/54 by @mengelmann

**Comment by enkore** [comment]
I don't think there is an API for us to change this; see http://pythonhosted.org/llfuse/operations.html

**Comment by ThomasWaldmann** [comment]
Updated, currently working links:
- https://www.rath.org/llfuse-docs/data.html#llfuse.StatvfsData
- could not find the issue 107 anywhere (archive.org, google cache)

**Comment by ThomasWaldmann** [comment]
https://github.com/python-llfuse/python-llfuse/blob/master/Changes.rst#release-13-2017-09-15

So, we have `f_namemax` since llfuse 1.3.0 (which is also the current minimum requirement for master branch borg).

**Comment by ThomasWaldmann** [comment]
So, what should f_namemax be?

filename lengths in borg archives are not really limited and it might depend on the OS and filesystem where an archive was created.
```
getconf NAME_MAX /
```
Values:
- Linux / ext4: 255
