### ISSUE TITLE
Index needs to be manually deleted & recreated after conversion from attic repo

### ISSUE THREAD

**Issue by jscinoz** [borgbackup/borg#269]
Migrating this over from a comment on jborg/attic#354.

After converting an existing attic repository to a borg repository, while the process completed without errors, any subsequent attempts to use the repository encountered an error when reading the index (unfortunately, I do not have a copy of the stack trace, and had to delete the original attic repository to recover space).

Deleting the index.XXXXX file in the repository and running ```borg check``` to rebuild it results in a functioning repository once more.

**Comment by ThomasWaldmann** [comment]
@anarcat ^^

**Comment by anarcat** [comment]
i'll try to reproduce this and give feedback.

**Comment by petrcech** [comment]
Hi,
i think it hat to do with the change 5409cbaa678eda55c7846726f1146be90ea9b648 as it removes caches conversion and with it the conversion of index.nnn file.

**Comment by anarcat** [comment]
i have a fix for this waiting in my pile of code here..

**Comment by anarcat** [comment]
hi @jscinoz! if you could test #281 and confirm if it fixes the problem for you, it would be really appreciated!

**Comment by anarcat** [comment]
i have done my own tests here and while i had this issue before, i don't see it anymore. i think therefore this is fixed, reopen with a way to reproduce if that's still a problem for you.
