### ISSUE TITLE
improve the logo and favicon on the website

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#272]
since we switched to the default RTD theme (#268), we have lost the logo on the main website. There is now a way to add that logo (implemented in PR https://github.com/snide/sphinx_rtd_theme/pull/69), so we should be able to configure that easily.

**Comment by anarcat** [comment]
so i added back the logo so we have some sort of custom display, but it's a little ugly: the terminal green and the RTD blue really don't mix so well, so i'm keeping this issue opened for someone with some graphics skills to come in and fix this. it's also possible to override the builtin CSS as well by throwing stuff in `_static` now, although i do not know if we can *add* to the CSS instead of just replacing it...

**Comment by ThomasWaldmann** [comment]
wasn't that "logo" just BORG in a special font?

**Comment by anarcat** [comment]
yes, pretty much, except it is in a `.ico` image file of some sort. i have no idea how that was built, source missing?

**Comment by ThomasWaldmann** [comment]
.ico rather sounds like the favicon.

**Comment by anarcat** [comment]
that's what i am refering to.

**Comment by anarcat** [comment]
actually, it is the favicon. but it's reused in the left column, in the `html_logo` field of the sphinx config. i have sent a commit in pr #313 to have it re-enabled too:

https://github.com/anarcat/borg/commit/c7c02ef725b6a5f19c22afdadad47559076e2810

**Comment by anarcat** [comment]
the logo was created in 8cf0ead by @pguth, apparently.

**Comment by ThomasWaldmann** [comment]
See PR #434.
