### ISSUE TITLE
Preview and confirm list of files to be backed up

### ISSUE THREAD

**Issue by blueyed** [borgbackup/borg#2729]
I've tried to use `borg create --exclude-caches --exclude-from … --one-file-system --progress --stats -v '/var/backup/borg::system-{now}' --dry-run --list --filter AM /` to not actually create an archive, but only list added or modified files, but the `--dry-run` causes the status to be `-` unconditionally.

In the end, it would be nice if there was some `--confirm` flag, which would display the new/modified files and ask for confirmation to continue interactely.

**Comment by ThomasWaldmann** [comment]
Well, the borg create code shortcuts when run with `--dry-run`. This mode is primarily inteded to optimize your exclude list, not to search for new or modified files.

**Comment by rugk** [comment]
> which would display the new/modified files and ask for confirmation to continue interactely.

Do you want5 to have this question for **each** file added/changed or just a list of all changed/added files and a confirmation afterwards?

**Comment by blueyed** [comment]
Just a list of all changed/added files and a confirmation afterwards.

**Comment by jcrben** [comment]
> This mode is primarily intended to optimize your exclude list, not to search for new or modified files

I'm not sure how to use it for that purpose either... https://github.com/borgbackup/borg/issues/1648 related for that exclude case

**Comment by blueyed** [comment]
Yes, #1648 would work for me.
Closing this issue for now.
