### ISSUE TITLE
Document valid status chars for --filter

### ISSUE THREAD

**Issue by blueyed** [borgbackup/borg#2730]
The supported status chars should be listed with the help for `borg create --filter` (`--filter STATUSCHARS`).
This could just list the available choices (and validate them), and then link to some more specifc documentation/list, where each of them is explained / listed with a short desc, similar to `borg help pattern`?!

**Comment by ThomasWaldmann** [comment]
Good idea.

**Comment by enkore** [comment]
http://borgbackup.readthedocs.io/en/stable/usage.html#item-flags
http://borgbackup.readthedocs.io/en/latest/usage/create.html#item-flags

Todo: Add short list (AME...) to --filter help text.
