### ISSUE TITLE
Link prune example

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2735]
[In the prune doc](https://borgbackup.readthedocs.io/en/latest/usage/prune.html) you state:
> There is also a visualized prune example in docs/misc/prune-example.txt.

Now, average Joe or the man on the Clapham omnibus, thinks: "That's nice, but where can I find this file?"

That's why I suggest to add a link to the file on GitHub. Or do something different to make it easier to find this file. You cannot expect a user to download the source code/clone the repo first. And even for that, they have to know the path relates to the source code and the file is meant to be found there.

**Comment by enkore** [comment]
```
.. include:: misc/prune...
    :literal:
```

(http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment)

In the examples section, or in a separate section following it.

**Comment by rugk** [comment]
So you want to include the file directly? Sure, also possible.
