### ISSUE TITLE
Deduplicated size larger than attic

### ISSUE THREAD

**Issue by dand321** [borgbackup/borg#275]
Wonder if I'm doing something wrong. I'm seeing a much better deduplication ratio with attic than with borg using the same dataset. The attic repo has 7 days worth of daily data from about 10 servers, mostly persona, mysql and mongo backups. The borg repo has only 2 days worth of the same exact data and is already nearly double the size of the attic repo. Both repos are using encryption, borg repo was created yesterday with 0.27.0 pre-compiled binary on Centos 6.5.

### Borg 0.27.0
```
Archive name: nfs2-web1-20151012
Archive fingerprint: 2d6706e9ce9acb7be3f4d9c5a4de101cd98bcc1276e4899c1221e81839473017
Start time: Tue Oct 13 04:24:36 2015
End time: Tue Oct 13 04:24:37 2015
Duration: 1.16 seconds
Number of files: 2

                       Original size      Compressed size    Deduplicated size
This archive:               15.33 MB             15.34 MB            588.39 kB
All archives:              197.95 GB            198.07 GB            111.81 GB

                       Unique chunks         Total chunks
Chunk index:                 1406967              2659644
```

### Attic 0.16
```
Archive name: nfs2-web1-20151012
Archive fingerprint: 36877cf8c6c79997d6b3435998f42f3c13771e14b256f44bdefab32a2c75d0c6
Start time: Tue Oct 13 00:14:56 2015
End time: Tue Oct 13 00:15:00 2015
Duration: 3.51 seconds
Number of files: 2

                       Original size      Compressed size    Deduplicated size
This archive:               15.32 MB             15.33 MB            616.77 kB
All archives:              683.57 GB            319.04 GB             66.40 GB
```

**Comment by ThomasWaldmann** [comment]
attic is compressing by default (zlib level 6, which is rather slow, but good compression) and there is no way to switch that off or choose compression algorithms or levels in attic.

borgbackup is not compressing by default - you have to think about and choose the compression algorithm and level that bests fits your use case. See borg create --help.

**Comment by dand321** [comment]
Thomas, thanks for pointing out the obvious. Turns out that zlib,6 provides the best overall results for us.

**Comment by dand321** [comment]
@ThomasWaldmann Just wanted to point out that although the help page is clear, your main doc page hints that compression is enabled by default:

http://borgbackup.readthedocs.org/en/latest/index.html

```
Now doing another backup, just to show off the great deduplication:

$ borg create --stats /mnt/backup::Tuesday ~/Documents

Archive name: Tuesday
Archive fingerprint: 387a5e3f9b0e792e91c...
Start time: Tue Mar 25 12:00:10 2014
End time:   Tue Mar 25 12:00:10 2014
Duration: 0.08 seconds
Number of files: 358
                  Original size    Compressed size    Deduplicated size
This archive:          57.16 MB           46.78 MB            151.67 kB  <--- !
All archives:         114.02 MB           93.46 MB             44.81 MB
```

**Comment by ThomasWaldmann** [comment]
oh, oops. that's just an old excample that didn't get updated. thanks for the hint.

I'll mark this as docs bug.

**Comment by ThomasWaldmann** [comment]
Reopening as a reminder to fix the docs.

**Comment by ThomasWaldmann** [comment]
@dand321 you also tried lz4? zlib,6 is quite high in cpu usage and might slow down the backup if your storage is fast.

**Comment by dand321** [comment]
I did test lz4, not enough compression. The slower speed with zlib,6 is more than acceptable in our case as it will allow us a longer retention time with the same amount of storage. Also, this is for 2nd tier backups. This will be taking the current days backups and archiving them nightly to local storage, then doing the same to offsite storage. Borg is replacing an rsync script that was not finishing in 24 hours and borg is completing in about an hour and a half, so despite borg with zlib,6 being slower than lz4 (or no compression), it is monumentally faster than our previous setup and we are thrilled!

**Comment by ThomasWaldmann** [comment]
@dand321 nice to hear. :) I fixed the docs.
