### ISSUE TITLE
1.0.11rc1 feedback ticket

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2754]
if you tested 1.0.11rc1 and you found some bug or issue, please file a separate issue from this.

if you tested it and everything worked, please write a comment below, stating:
- what you tested
- scale of your tests
- fresh repository or existing repository

**Comment by lfam** [comment]
I tested a few full backups and a small, partial restore on x86_64 Linux.

I used an existing repository, althought I made a Btrfs COW copy of it first, to protect against accidental corruption.

**Comment by realityexists** [comment]
I confirmed that #2674 is fixed by mounting my repo (created under Cygwin with borg 1.0.10) using borg 1.0.11rc1 on Linux.

**Comment by ThomasWaldmann** [comment]
thanks for the feedback, i'll start the 1.0.11 release process now...
