### ISSUE TITLE
borg delete requires free disk space

### ISSUE THREAD

**Issue by hferreiro** [borgbackup/borg#2756]
I was running low on disk space but couldn't use borg delete to free some because of the very same reason:

```
$ borg delete .local/share/borg.backup::backup
Local Exception.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 2089, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 2025, in run
    return func(args)
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 91, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 511, in do_delete
    archive.delete(stats, progress=args.progress, forced=args.forced)
  File "/usr/lib64/python3.5/site-packages/borg/archive.py", line 549, in delete
    chunk_decref(items_id, stats)
  File "/usr/lib64/python3.5/site-packages/borg/archive.py", line 530, in chunk_decref
    self.cache.chunk_decref(id, stats)
  File "/usr/lib64/python3.5/site-packages/borg/cache.py", line 424, in chunk_decref
    self.begin_txn()
  File "/usr/lib64/python3.5/site-packages/borg/cache.py", line 213, in begin_txn
    shutil.copy(os.path.join(self.path, 'chunks'), txn_dir)
  File "/usr/lib64/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.5/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib64/python3.5/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device
```

**Comment by RonnyPfannschmidt** [comment]
for some low space situations the `--save-space` option is enough to redeem

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/quickstart.html#important-note-about-free-space

**Comment by ThomasWaldmann** [comment]
```
$ borg delete .local/share/borg.backup::backup
```

@hferreiro is your backup on the same disk as your home directory?

**Comment by hferreiro** [comment]
@ThomasWaldmann I periodically rsync to a server.

@RonnyPfannschmidt  @infectormp so, I guess the what I am asking if for borg to catch the OSError about no space left and retry with --save-space, would that make sense?

**Comment by RonnyPfannschmidt** [comment]
that would make sense ^^

**Comment by ThomasWaldmann** [comment]
I don't think an automatic retry makes sense.
It complicates the code and it would only lead to you noticing a (near) out-of-space condition later.
Maybe when it is really to late and the fs has filled up to a degree when even --save-space will fail.

@hferreiro if that means "yes" as an answer to my question: ~backupuser/.cache/borg/chunks.archives.d can use a big amount of space. See the FAQ how to avoid that if you are low on space.

**Comment by ThomasWaldmann** [comment]
I am closing this as "known and documented".

**Comment by enkore** [comment]
1.1 also keeps a minimum operational space free by itself and has generally better behaviour and self-recovery.

**Comment by AnnoyingTechnology** [comment]
Encountered the same issue, got a 2.7Tb drive full.
`--space-space` doesn't seem like a valid option (`borg1.0.9@Debian8.10`).
Only workaround I've found so far is to copy the whole backup directory to a larger drive to allow for some pruning before copying it back to the original saturated drive. Luckily, one larger drive had enough free space available on that machine.

**Comment by ThomasWaldmann** [comment]
borg check/delete/prune --save-space ... should be there since borg 0.29.0.
