### ISSUE TITLE
likly encoding problem 

### ISSUE THREAD

**Issue by ReimarBauer** [borgbackup/borg#276]
Traceback (most recent call last):
  File
"/home/borgbackup/borg-env/lib/python3.4/site-packages/borg/cache.py",
line 71, in __del__
    self.close()
  File
"/home/borgbackup/borg-env/lib/python3.4/site-packages/borg/cache.py",
line 139, in close
    self.lock.release()
  File
"/home/borgbackup/borg-env/lib/python3.4/site-packages/borg/locking.py",
line 277, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File
"/home/borgbackup/borg-env/lib/python3.4/site-packages/borg/locking.py",
line 205, in modify
    self.save(roster)
  File
"/home/borgbackup/borg-env/lib/python3.4/site-packages/borg/locking.py",
line 178, in save
    with open(self.path, "w") as f:
  File "/home/borgbackup/borg-env/lib/python3.4/_bootlocale.py", line
23, in getpreferredencoding
    def getpreferredencoding(do_setlocale=True):
KeyboardInterrupt
borg: Exiting with failure status due to previous errors

**Comment by ThomasWaldmann** [comment]
This is because the script was interrupted with Ctrl-C, I don't see an encoding problem here.
