### ISSUE TITLE
Let borg key import use stdin

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2760]
If `borg key import` does not get a filename it should read the key input from stdin. 

Currently it shows "input file to import key from expected".

**Comment by enkore** [comment]
--paper?

**Comment by ThomasWaldmann** [comment]
top post: you meant `borg key import` (typo)

**Comment by rugk** [comment]
Not the paper backup. I want to input the `BORG_KEY […]` "file" as usual. Just not as a scanned file, but via stdin.
