### ISSUE TITLE
borg info should display stats on most recent archive

### ISSUE THREAD

**Issue by caigner** [borgbackup/borg#2765]
When the following command is issued:

`borg info /path/to/repository`

the following reply is displayed:

`borg info: error: argument ARCHIVE: "/path/to/repository": No archive specified`

Instead I think it would be convenient to have borg reply with stats on the most recent archive.

So 

`borg info /path/to/repository::most-recent-archive`

should be the same as 

`borg info /path/to/repository`

**Comment by RonnyPfannschmidt** [comment]
it should at least print a warning that it is usingthe most rcent archive since no archive was passed

**Comment by enkore** [comment]
1.1 displays repository stats here. Since you also have archive filters there, you can do `borg info --last 1 /path/to/repo`. ([Docs](http://borgbackup.readthedocs.io/en/latest/usage/info.html))
