### ISSUE TITLE
interrupted borg prune - no space has been freed

### ISSUE THREAD

**Issue by devZer0** [borgbackup/borg#2772]
i needed to interrupt borg prune during run (ctrl-c) and now at the second try, it immediatly returns without pruning anything - but the partition is still full (that`s the reason why id did prune it manually)

apparently, i guess there are unreferenced blocks/files now on disk, i.e. the pruning did something to the repos/data and de-referenced some pointer but freeing space didnt happen

what can be done here ?

(prune command run at daily basis was -keep-daily 31 --keep-weekly 8 --keep-monthly 6 - that was the reason why the partition got full...)

```
[root@backupvm2 backup]# /backup/bin/borg prune --verbose --stats --list \
    --keep-daily 14 --keep-weekly 8 --keep-monthly 3 \
    /iscsi/lun2/borg-repos/dbserver2


Keeping archive: archive-2017-06-30_0832              Fri, 2017-06-30 10:43:47
Keeping archive: archive-2017-06-29_0357              Thu, 2017-06-29 05:07:09
Keeping archive: archive-2017-06-28_0417              Wed, 2017-06-28 05:14:34
Keeping archive: archive-2017-06-27_0438              Tue, 2017-06-27 05:36:20
Keeping archive: archive-2017-06-26_0211              Mon, 2017-06-26 02:54:49
Keeping archive: archive-2017-06-25_0230              Sun, 2017-06-25 03:20:24
Keeping archive: archive-2017-06-24_0437              Sat, 2017-06-24 05:34:58
Keeping archive: archive-2017-06-23_0449              Fri, 2017-06-23 05:49:13
Keeping archive: archive-2017-06-22_0240              Thu, 2017-06-22 03:34:54
Keeping archive: archive-2017-06-21_0408              Wed, 2017-06-21 05:10:20
Keeping archive: archive-2017-06-20_0215              Tue, 2017-06-20 03:01:26
Keeping archive: archive-2017-06-19_0205              Mon, 2017-06-19 02:49:43
Keeping archive: archive-2017-06-18_0152              Sun, 2017-06-18 02:35:39
Keeping archive: archive-2017-06-17_0325              Sat, 2017-06-17 04:07:39
Keeping archive: archive-2017-06-11_0200              Sun, 2017-06-11 02:42:57
Keeping archive: archive-2017-06-04_0204              Sun, 2017-06-04 02:43:53
Keeping archive: archive-2017-05-31_0318              Wed, 2017-05-31 04:25:12
Keeping archive: archive-2017-05-28_0152              Sun, 2017-05-28 02:30:16
Keeping archive: archive-2017-05-21_0206              Sun, 2017-05-21 02:53:20
Keeping archive: archive-2017-05-14_0157              Sun, 2017-05-14 02:42:12
Keeping archive: archive-2017-05-07_0141              Sun, 2017-05-07 02:23:47
Keeping archive: archive-2017-04-30_0156              Sun, 2017-04-30 02:41:03
Keeping archive: archive-2017-04-23_0146              Sun, 2017-04-23 02:28:03
Keeping archive: archive-2017-03-31_0146              Fri, 2017-03-31 02:29:31
Keeping archive: archive-2017-02-26_0444              Sun, 2017-02-26 05:23:04
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:                4.34 TB              4.14 TB              1.62 TB

                       Unique chunks         Total chunks
Chunk index:                  766496              4205155
------------------------------------------------------------------------------

[root@backupvm2 backup]# df -h|grep lun2
/dev/sdc1                2,0T    1,9T  4,7G  100% /iscsi/lun2
```

**Comment by devZer0** [comment]
sorry for bad formatting, i don`t get the point to copy/past correct here

**Comment by ThomasWaldmann** [comment]
please add your borg version and system info.

**Comment by ThomasWaldmann** [comment]
I suspect your interrupted the prune after the prune-commit, but before the compact-segments-commit.

Guess any write operation to the repo should clean up by doing a rollbackup and a compact-segments.

**Comment by devZer0** [comment]
borg 1.0.10 on centos

will check if  write will fix things...

**Comment by ThomasWaldmann** [comment]
@devZer0 so, did it fix things?

**Comment by ThomasWaldmann** [comment]
no response, closing.

**Comment by bjornfor** [comment]
[For the archive.]

I had a seemingly similar situation (solved):

1. `borg create [...]` failed due to full disk (leaving behind a "checkpoint" archive).
2. I ran `borg delete [...]` on the incomplete checkpoint archive, but it probably also got interrupted (due to bad WiFi / empty laptop battery).
3. The checkpoint archive was now gone, but `borg info [...]` showed disk usage ~500 GiB but `du [...]` showed real usage to be 2+TiB. IOW, there must have been some unreferenced objects taking up lots of space in the repo.
4. On the next night the backup script ran again (`borg create [...] && borg prune [...]`) and the unreferenced objects were pruned -- `borg info` and `du` now roughly agree on the repo size.

This was with borg 1.1.17 on NixOS 21.11.
