### ISSUE TITLE
Kernel panic with borg backup

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#2773]
Hi guys,

I've been suffering this since a long time ago (months). I'm using 1.0.10 stable. This only happens on my office's computer. At first I thought of a problem with the computer itself (memory, mother board...) but I recently switched to a brand new computer, and the problems still persist.

My usage patter is the following. I have two repositories on that computer 1 for my home and 1 for a bunch of LXC containers. Every night at 1am a borg create + borg prune is executed, first for /home and then for /home/lxc. 
Current chunk statistics are:
/home                 UNIQUE: 408045     TOTAL: 15885397
/home/lxc            UNIQUE: 514328     TOTAL: 41876148

The office computer rarely goes powered down (I have some servers there) so after a few days/weeks (rarely more than 2 weeks) I got this kernel error (or some similar one). They are always related to the FS and it is my impression it is related to a high pressure of reads/writes, but I couldn't be sure. What's sure is that it happens always during borg operations.

```
jul 02 01:01:38 diffie kernel: BUG: unable to handle kernel NULL pointer dereference at           (null)
jul 02 01:01:38 diffie kernel: IP: [<ffffffff81215ac5>] lookup_fast+0x225/0x2d0
jul 02 01:01:38 diffie kernel: PGD 13b347067 
jul 02 01:01:38 diffie kernel: PUD 10c42b067 
jul 02 01:01:38 diffie kernel: PMD 0 
jul 02 01:01:38 diffie kernel: 
jul 02 01:01:38 diffie kernel: Oops: 0000 [#1] SMP
jul 02 01:01:38 diffie kernel: Modules linked in: xt_nat xt_comment xt_multiport xt_addrtype veth fuse xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 n
jul 02 01:01:38 diffie kernel:  thermal fan hci_uart btbcm btqca btintel bluetooth acpi_als kfifo_buf battery industrialio rfkill wmi intel_lpss_acpi intel_lpss i2c_hid evdev fjes tpm_tis tpm_tis_core tpm mac_hid acpi_pad sch_
jul 02 01:01:38 diffie kernel: CPU: 0 PID: 10501 Comm: borg Tainted: G        W  O    4.9.34-1-lts #1
jul 02 01:01:38 diffie kernel: Hardware name: System manufacturer System Product Name/H110M-K, BIOS 2003 09/19/2016
jul 02 01:01:38 diffie kernel: task: ffff88011b0b9d80 task.stack: ffffc90008e7c000
jul 02 01:01:38 diffie kernel: RIP: 0010:[<ffffffff81215ac5>]  [<ffffffff81215ac5>] lookup_fast+0x225/0x2d0
jul 02 01:01:38 diffie kernel: RSP: 0018:ffffc90008e7fc68  EFLAGS: 00010202
jul 02 01:01:38 diffie kernel: RAX: 0000000000000000 RBX: ffffc90008e7fd40 RCX: 0000000000000001
jul 02 01:01:38 diffie kernel: RDX: 00000000000ae8e4 RSI: 0000000000000040 RDI: ffff880200000000
jul 02 01:01:38 diffie kernel: RBP: ffffc90008e7fcb0 R08: ffff880200000000 R09: ffffc90008e7fd50
jul 02 01:01:38 diffie kernel: R10: 000000000000000b R11: 0000006f006f732e R12: ffff880200000000
jul 02 01:01:38 diffie kernel: R13: ffffc90008e7fcc8 R14: ffff88022ceb9b20 R15: ffffc90008e7fcd0
jul 02 01:01:38 diffie kernel: FS:  00007fa9774974c0(0000) GS:ffff880236c00000(0000) knlGS:0000000000000000
jul 02 01:01:38 diffie kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
jul 02 01:01:38 diffie kernel: CR2: 0000000000000000 CR3: 000000011b1a1000 CR4: 00000000003426f0
jul 02 01:01:38 diffie kernel: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
jul 02 01:01:38 diffie kernel: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
jul 02 01:01:38 diffie kernel: Stack:
jul 02 01:01:38 diffie kernel:  ffff8802000ae8e4 ffffc90008e7fcc4 0000000281213b2f 754eebf3f6b9af18
jul 02 01:01:38 diffie kernel:  ffffc90008e7fd40 0000000000000000 0000000000000000 ffffc90008e7fe80
jul 02 01:01:38 diffie kernel:  ffffc90008e7fed0 ffffc90008e7fd08 ffffffff81215e47 0000000208e7fd40
jul 02 01:01:38 diffie kernel: Call Trace:
jul 02 01:01:38 diffie kernel:  [<ffffffff81215e47>] walk_component+0x47/0x2c0
jul 02 01:01:38 diffie kernel:  [<ffffffff8121675a>] path_lookupat+0x7a/0x100
jul 02 01:01:38 diffie kernel:  [<ffffffff81218a6f>] filename_lookup+0xaf/0x140
jul 02 01:01:38 diffie kernel:  [<ffffffff8122ec84>] ? getxattr+0x124/0x1e0
jul 02 01:01:38 diffie kernel:  [<ffffffff812052bc>] ? __check_object_size+0x4c/0x1eb
jul 02 01:01:38 diffie kernel:  [<ffffffff8132b50d>] ? strncpy_from_user+0x4d/0x170
jul 02 01:01:38 diffie kernel:  [<ffffffff81218bd6>] user_path_at_empty+0x36/0x40
jul 02 01:01:38 diffie kernel:  [<ffffffff8120df26>] vfs_fstatat+0x66/0xc0
jul 02 01:01:38 diffie kernel:  [<ffffffff812209ef>] ? dput.part.6+0x2f/0x210
jul 02 01:01:38 diffie kernel:  [<ffffffff8120e446>] SyS_newlstat+0x36/0x70
jul 02 01:01:38 diffie kernel:  [<ffffffff8122edb8>] ? path_getxattr+0x78/0xb0
jul 02 01:01:38 diffie kernel:  [<ffffffff815fc537>] entry_SYSCALL_64_fastpath+0x1a/0xa9
jul 02 01:01:38 diffie kernel: Code: c1 74 a3 b9 f6 ff ff ff eb 9c 31 c9 eb 98 4c 89 e7 e8 20 b1 00 00 b9 fe ff ff ff eb 89 49 8b 44 24 60 89 55 b8 4c 89 e7 8b 73 38 <ff> 10 85 c0 89 c1 8b 55 b8 0f 8f 72 fe ff ff 8b 55 cc 4c 8
jul 02 01:01:38 diffie kernel: RIP  [<ffffffff81215ac5>] lookup_fast+0x225/0x2d0
jul 02 01:01:38 diffie kernel:  RSP <ffffc90008e7fc68>
jul 02 01:01:38 diffie kernel: CR2: 0000000000000000
jul 02 01:01:38 diffie kernel: ---[ end trace 0908827489326559 ]---
```

**Comment by alejandro-perez** [comment]
Sorry, fat fingers :) Let me finish the explanation.

My usage patter is the following. I have two repositories on that computer 1 for my home and 1 for a bunch of LXC containers. Every night at 1am a borg create + borg prune is executed, first for /home and then for /home/lxc. 
Current chunk statistics are:
/home                 UNIQUE: 408045     TOTAL: 15885397
/home/lxc            UNIQUE: 514328     TOTAL: 41876148

The office computer rarely goes powered down (I have some servers there) so after a few days/weeks (rarely more than 2 weeks) I got this kernel error (or some similar one). They are always related to the FS and it is my impression it is related to a high pressure of reads/writes, but I couldn't be sure. What's sure is that it happens always during borg operations.

```

**Comment by enkore** [comment]
- What's the file system?
- Has the disk remained the same?
- What does fdisk say?

**Comment by alejandro-perez** [comment]
First of all, this should not be a problem of borg, since it executes in the user-space and the issues I'm seeing is at kernel space. I acknowledge that, so thank you very much for helping me.

> What's the file system?

The filesystem is EXT4. I tried months ago with BTRFS but then that was horrible.

> Has the disk remained the same?

No. It uses to be a 500GB plate disk as a source, and 250GB plate disk as repository. Now it is a 500GB SSD disk as the source and 1TB plate disk as repository.

> What does fsck say?

```
LANG=en sudo fsck.ext4 /dev/sdb1 -f
e2fsck 1.43.4 (31-Jan-2017)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Backup: 53566/61054976 files (11.7% non-contiguous), 92117341/244190385 blocks
```
> Are the traces similar or different?

That's a good question. I will collect and paste some of them here as they come. For me they are similar, always FS-related.

**Comment by alejandro-perez** [comment]
> Edit: This is in the VFS layer before the FS gets to chime in. Hmm.

Umm. I recall having seen btrfs- and ext4-specific traces. I will collect a few of them more.

**Comment by ThomasWaldmann** [comment]
If you have a kabylake or skylake generation cpu, make sure you either apply the microcode updates that fix the hyperthreading bug or switch off hyperthreading immediately until you can apply the fix.

https://lists.debian.org/debian-devel/2017/06/msg00308.html

After doing that, keep us updated whether the crash is still happening.

**Comment by ThomasWaldmann** [comment]
Also, even if it is a "new" computer, please make sure that ssd / hdd and RAM work ok:
- memory test: memtest86+
- disk/ssd: smartctl -t long /dev/sdX and later smartctl -a /dev/sdX

**Comment by alejandro-perez** [comment]
> If you have a kabylake or skylake generation cpu that has hyperthreading, make sure you either apply the microcode updates that fix the hyperthreading bug or switch off hyperthreading immediately until you can apply the fix.
https://lists.debian.org/debian-devel/2017/06/msg00308.html
After doing that, keep us updated whether the crash is still happening.

Ok I read about this, and actually enabled ucode updates in Arch so I thought it should be fixed, but it seems that Kabylake are not fixed by this method and instead I need a vendor specific BIOS upgrade.

I will do as you say and disable HT and see what happens.

Thanks for the tip!

**Comment by alejandro-perez** [comment]
Hi again!

Thank you for the tip. It was indeed very helpful and completely related. I upgraded BIOS FW and now it seems to work properly, with HT enabled. So far so good, which is way more time working than ever was before upgrading.

I will close the issue since it is not related to borg and the solution was found anyway.

**Comment by enkore** [comment]
I really hope that this was some bad interaction between firmware (BIOS) and kernel, and not the SKL bug — if the SKL bug affected the VFS and file systems in the kernel, it would be really unsettling the bug was not noticed for so long.

**Comment by alejandro-perez** [comment]
Right. Maybe it was not the SKL bug. It might have been another BIOS bug fixed in any of the 5 versions between the shipped FW and the latests one I installed. Anyway it seems to be fixed now (longer term testing is requirer though). Thanks again!
