### ISSUE TITLE
Sync "build the docs" in installation.rst with updated data from development.rst

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2795]
"to build the docs" mentions no theme dependency at all. Note: It may make sense to just fork the current theme into borgbackup/ [0] to make customization etc. easier.

[0]
Using separate PyPI: Dependence on upstream, have to override individual files.
Using separate fork: is still a dependency (like before with sphinx_rtd_theme).
Using in-tree copy: no dependency, but litters the file list.

**Comment by takluyver** [comment]
I noticed that there's a file `requirements.d/docs.txt`, so I updated the source installation instructions to use that in #2822.

This doesn't answer the question about where the theme should live, but it makes it work with where it currently lives, whereas the current instructions are insufficient for building the docs.
