### ISSUE TITLE
slow stuff for borg list repo --json

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2796]
I noticed that there is only the basic/quick stuff in there and likely this is good for now.

But maybe we want to support `--format` not just for screen output, but also for json, it could look like:

```
borg list repo --json --format key1,key2,...
```

That way one could request also slow stuff like `comment` or `end` to be in the json output.

**Comment by enkore** [comment]
> --json Only valid for listing repository contents. Format output as JSON. The form of --format is ignored, but keys used in it are added to the JSON output. Some keys are always present. Note: JSON can only represent text. A “barchive” key is therefore not available.

**Comment by ThomasWaldmann** [comment]
Oh, I didn't notice that mechanism already being there... good. :)
