### ISSUE TITLE
use py.test for testing, refactor tests

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#28]
pytest is way superior (and also more comfortable) compared to unittest.

less work to write tests, prettier / easier readable tests, more useful output (esp. on failure).

the existing tests can be taken "as is" as a starting point, pytest is able to run them.

later, more pytest specific features can be used to further improve.

**be careful!**

`borg.selftest` is special because it must not depend on pytest. it runs every time `borg` is invoked by a user.

see there: https://github.com/borgbackup/borg/pull/6157#issuecomment-1024996349

These must **not** be converted to `unittest`:
```
from .testsuite.hashindex import HashIndexDataTestCase, HashIndexRefcountingTestCase, HashIndexTestCase
from .testsuite.crypto import CryptoTestCase
from .testsuite.chunker import ChunkerTestCase

SELFTEST_CASES = [
    HashIndexDataTestCase,
    HashIndexRefcountingTestCase,
    HashIndexTestCase,
    CryptoTestCase,
    ChunkerTestCase,
]
```

**Comment by ThomasWaldmann** [comment]
I made the necessary changes so py.test is used via tox (local testing) and travis ci.

Keeping this issue open as a reminder to actually migrate the tests to "py.test style" - but that should be done a bit later as currently too much unmerged code is still waiting to get merged and global changes would be a pain for that...

**Comment by hexagonrecursion** [comment]
You currently have a hierarchy of test classes with unittest.TestCase as the root. Several very nice features of pytest are unavailable in those tests. Once that stings especially badly is pytest.mark.parametrize.

https://docs.pytest.org/en/6.2.x/unittest.html?highlight=unittest#pytest-features-in-unittest-testcase-subclasses

I am going to start slowly purging the traces of unittest from your codebase.

**Comment by ThomasWaldmann** [comment]
There's progress: all archiver tests were recently migrated to pytest! Thanks to @bigtedde!

**Comment by ThomasWaldmann** [comment]
The helpers tests also use pytest now, so this is finished.
