### ISSUE TITLE
Exception: chunk has same id, but different size

### ISSUE THREAD

**Issue by nusse** [borgbackup/borg#2806]
I get the following Exception when trying to backup:
Exception: chunk has same id [b'\xc10Bi\xfa\xca] \x18\x81\xf2\x19\xff\xf6\xc7\xa2(\xfd\xfa\x1a2q\xe3=\x1bK\r5\x01\xb8\xa1$'], but different size (stored: 1763 new: 5859)!

I have been running borg for a year on my machine. Recently my computer crashed a few times and likely borg backups were interrupted. Since then I'm trying to get borg running again, but now I'm stuck.

borg check -v --repair reports no errors

Attached in borg.txt is the log from borg and the version information on Ubuntu package.
[borg.txt](https://github.com/borgbackup/borg/files/1135655/borg.txt)

**Comment by enkore** [comment]
Try `borg extract --dry-run repo::archive` for the archives you have, it will probably report an error.

**Comment by ThomasWaldmann** [comment]
```
>>> hex(1763)
'0x6e3'
>>> hex(5859)
'0x16e3'
```

Looks like a bit flip.

I suggest you run memtest86+ for a while to make sure your RAM is working ok and also smartctl -a to check your disk's SMART log (and maybe also a -t long for a surface test). Could be also other components, though.

**Comment by ThomasWaldmann** [comment]
I am closing this, currently looks pretty much like a hardware issue.

BTW, borg 1.1 will compute a checksum for some important files, e.g. index files - so in case a corruption occurs on-disk or when loading from disk, that will be detected.
