### ISSUE TITLE
Question: limit segments_per_dir to 2800 possible?

### ISSUE THREAD

**Issue by Micha-Btz** [borgbackup/borg#2808]
Hi there,

At first thanks for the great tool and keep on the work you did.

I have 115GB cloud storage by my ISP and i want to upload the backups there. But they limit the files per dir to 3000 pieces. Mostly I split my backup in more little repos to get it better uploaded. But my picture collection are about 20GB and I want only one repo for it. Borg creates ca 3500 files from the 20GB . 

repo config:

> [repository]
> version = 1
> segments_per_dir = 10000
> max_segment_size = 5242880
> append_only = 0
> id = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
My question is can I limit the segments_per_dir so that it will create

> data/0 = 2800 files
> data/1 = 700 files -> 2800 files
> data/2 = ......
> 

so that I can keep the repo in future? I have played with chunker-params but I think it makes not really sense to increase the size because the dedup suffers.

Can I just simply edit the repo config?

Thanks Micha

**Comment by ThomasWaldmann** [comment]
@Micha-Btz yes, just edit the repo config after initializing a repo (or at least before it has gone past filling the first directory according to the new limits).

**Comment by Micha-Btz** [comment]
works thanks alot.
