### ISSUE TITLE
bad naming of borg upgrade backup directory

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2811]
from irc:
```
12:24  marin[m]$ but the question is, if i upgraded it, which one is the upgraded copy,
                 the one with .upgrade... in the name, or the one without?

12:42  ThomasWaldmann$ marin[m]: seems a bit bad naming there, the stuff called
                                 *.upgrade-<timestamp> is referred to as "backup" in the
                                 source, so it is the backup of the previous state.
                                 the upgrade result is in the original place.
```

Guess the directory name should somehow state that it is the old state, the backup - just "upgrade" hints in the wrong direction.

**Comment by takluyver** [comment]
Would calling it `preupgrade` or `before-upgrade` instead of `upgrade` work?

**Comment by ThomasWaldmann** [comment]
before-upgrade seems to be clearer than what we have.

**Comment by takluyver** [comment]
I had a go at this in #2824, calling it `before-upgrade` - I think clarity is preferable to the brevity of `preupgrade`, which I'm not even sure is a real word.
