### ISSUE TITLE
document commercial support providers

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2812]
at europython i was asked whether commercial support exists for borgbackup.

guess it does (and i could offer it myself), but it is sort of undocumented.

so, just add a list of commercial support providers to the docs?

or have a list on the community repo?

**Comment by enkore** [comment]
support.rst is one of those pages that have no reason to linger around in released and distrib'd docs; I believe this was already brought up before. Move that to .org (so it can easily be updated), then we can add commercial support options there.

**Comment by milkey-mouse** [comment]
how cool would it be to have the domain `b.org`...

**Comment by ThomasWaldmann** [comment]
@milkey-mouse yeah, seems someone else also found that before you. :)

**Comment by MichaelRupertDev** [comment]
Gonna pick this up as one of two tasks for https://github.com/borgbackup/borg/issues/3332

**Comment by ThomasWaldmann** [comment]
commercial supporter list entry for myself:
```
company: Waldmann EDV Service GbR
contact: Thomas Waldmann <tw@waldmann-edv.de>
scope: borgbackup consulting, support, development
```

**Comment by ThomasWaldmann** [comment]
commercial service list entry for rsync.net:
```
company: rsync.net
service: http://rsync.net/products/attic.html
scope: cloud storage platform with borg support
```

**Comment by ThomasWaldmann** [comment]
@MichaelRupertDev can we finish this today, before 1.1.3 release? :)

**Comment by MichaelRupertDev** [comment]
I'll work on it now

**Comment by MichaelRupertDev** [comment]
Do you want me too add the rsync.net to the .org site and then add that in to the backport PR when it gets merged?

**Comment by ThomasWaldmann** [comment]
Would be nice, yes. (and this is overall big enough to get the bounty, no second issue needed)

**Comment by MichaelRupertDev** [comment]
Sweet, I'll get that added now.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borgbackup.github.io/blob/source/support/commercial.rst

pull requests for more are welcome, please do them in THAT repo, against THAT branch.
