### ISSUE TITLE
Best chunks parameters for deduplication of sql dumps

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2813]
The case: separate repo with sql dumps only, made daily. Some dumps are from internet shops and can be big (1-10 Gb).

What are the best chunks parameters (for `borg create --chunker-params`) for a such repo for the best deduplication ratio in such case?

**Comment by ThomasWaldmann** [comment]
Good question, but hard to answer as it depends on your data and the way / order it gets dumped into the dump file.

What you have to try to reach is having lots of stable (== unchanged) sections of the file that are longer than borg's target chunk size and trying to have the changes in as few chunks as possible.

Worst are a lot of small changes spread out over the whole file, hitting every chunk of it.

BTW, you should not compress the dump files before giving them to borg (and in case you can not avoid, use "rsyncable" compression, not full-stream compression).

**Comment by ThomasWaldmann** [comment]
What you also have to consider: smaller target chunk size usually leads to a bit better deduplication as it is more fine-grained and thus finds more stable / duplicate changes.

BUT: creating a lot of small chunks has its price, every chunk needs to be managed and cpu / memory and disk resources are needed for that. So, e.g. if you are creating 32x more chunks that with default chunker params, you might end up needing 32x the RAM and the disk space for the hash tables also.

**Comment by knutov** [comment]
> having lots of stable (== unchanged) sections of the file

that does not seem to be possible. Every table of mysql db can have new lines each day. But I can sure that order of tables and order of table lines in dump are always the same (==alphabetical).

So the data is not adjusted and every piece of data is located with different shift from start of file/stream almost every time. 

Dumps are not compressed initially, of course (in fact, I'm using `mysqldump ... | borg create ... -`)

Can you advise some specific chunker size? Or is it better to use better compression instead of trying to make better deduplication?

**Comment by ThomasWaldmann** [comment]
Can it be ordered by timestamp of last change?

Shifts do not matter, having longer stable sections matters.

Try smaller chunks, but not too small.
Use compression additionally.

**Comment by knutov** [comment]
It can not be ordered or modified in any way, it's `mysqldump` output. But in real life I suppose yes, it's always ordered in some way.

Just for infromation, changing from default to `--chunker-params 4,12,8,4095` leads to 5x speed drop and 2-3 times large repo after second+ `borg create` on my test data. 

This is not what I expect - most sql dumps are smaller than 128kb, I thought it's can be good idea to make minimal chunk size smaller, but I do not really understand what does chunk size really mean.

**Comment by ThomasWaldmann** [comment]
@knutov did you find a better-than-default solution for this?

**Comment by knutov** [comment]
@knutov No, the default setting was always better for my dumps compared to anything I've tested. So I just gave up after a series of guesses.

**Comment by knutov** [comment]
@ThomasWaldmann No, the default setting was always better for my dumps compared to anything I've tested. So I just gave up after a series of guesses.
