### ISSUE TITLE
evaluate lgtm.com

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2814]
https://lgtm.com/projects/g/borgbackup/borg/alerts/

**Comment by ThomasWaldmann** [comment]
there's one issue with getxattr that might be caused by a unsupported platform there.

what do they run? openbsd / netbsd maybe?

**Comment by enkore** [comment]
I don't think they run anything.

**Comment by ThomasWaldmann** [comment]
first few fixes in #2852.

**Comment by rugk** [comment]
This belongs to https://github.com/borgbackup/borg/issues/2423, does not it?

**Comment by ThomasWaldmann** [comment]
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
