### ISSUE TITLE
Only one – hyphen in doc in title with parameter?

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2815]
Is it intended that you only use one hyphen (`–`) when a parameter is [mentioned in the title](https://borgbackup.readthedocs.io/en/latest/usage/notes.html#additional-notes) of the doc? E.g.
> ## –umask
> If you use `--umask`, […]

**Comment by ThomasWaldmann** [comment]
Might be a feature gone wrong. Would be easier to understand if the two dashes are visible here.

**Comment by takluyver** [comment]
I have had a go at fixing this in #2818
