### ISSUE TITLE
hashindex optimization: use backshift deletion

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2825]
we could just move to backshift deletion in the hashtable to get totally rid of tombstones.

good:
- less code in hashindex_lookup (which is used frequently)
- shorter chains

bad:
- more effort when actually deleting hashtable entries (for chunks this happens when reference count goes to 0)

**Comment by enkore** [comment]
Note: this is already part of the robin hood patches.

**Comment by ThomasWaldmann** [comment]
It is, but it also makes sense w/o robin hood.

**Comment by aeveris** [comment]
Is this something that's still desired? If so, I'd like to work on this.

**Comment by ThomasWaldmann** [comment]
@aeveris yes, but please:

- be careful :-) correctness of the HT code is super important for correct operations of borg.
- make sure it (overall) gets faster (maybe port the benchmark code from #2230 ?)
  - we do a lot of HT lookups (for ALL chunks used) in a typical (non-first) backup
  - we do some deletes (for chunks going to refcount 0) when deleting archives (running `prune`)

**Comment by ThomasWaldmann** [comment]
Note: we have kind of "micro backshift deletion" in master branch code `hashindex_get`:
- it remembers the index of the first deleted (tombstone) bucket (if any) while searching for a used bucket with the desired key (see `didx`)
- in case it finds the bucket with the desired key at some `idx` and it has actually remembered some `didx`, it does not just `return idx`, but first swaps the buckets (`bucket[didx] <-> buckets[idx]`) and then does `return didx` (now having the desired key bucket there).

**Comment by ThomasWaldmann** [comment]
I just noticed we have this micro-opt code (see previous comment) in all borg versions.

Thus the hashindex will converge against a optimised state (considering performance of lookups) and I guess we do not need to make a bigger change like suggested in this issue for now. For sure not for borg < 2.0.

**Comment by ThomasWaldmann** [comment]
Nothing to do here.
