### ISSUE TITLE
possible hashindex_lookup performance improvement

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2826]
the lookup code currently has to check whether it did a full table scan and is finished because of this.

if we know that there are always free buckets in the table (and not everything is filled up with tombstones OR we do not have any tombstones at all), we can conclude that full table scans won't ever happen due to that (it finds a free bucket first).

so that check can be just removed if the precondition is always met.

**Comment by enkore** [comment]
Note: this issue is talking about the `if (idx==start) break` check; since indices use modular arithmetic a FTS has been performed in precisely this case.

**Comment by ThomasWaldmann** [comment]
Agreed, likely not big enough difference in speed to consider removing this.
