### ISSUE TITLE
prime hashtable size not really needed

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2830]
we could get rid of the prime hashtable sizing (not need when having a perfect hash function like taking a part of a cryptographic hash) and just go with any other hashtable sizing and growth pattern.

but we maybe do not want to use powers of 2 for growing (at least due to the big increases (e.g. 4GB -> 8GB).

also the modulo (integer division rest) operation could be maybe replaced by some "if" check (like: if index >= size: index -= size). needs some benchmarking to see how it affects performance.

**Comment by enkore** [comment]
There are an awful lot of micro-optimization tickets about the hashindex, yet to everyday use its performance is largely irrelevant (the only exception I can think of right now are borg info and the cache sync, where it actually has a tangible impact). If the practical performance of Borg should be improved, then there are things were time is far better spent.

**Comment by ThomasWaldmann** [comment]
Also, borg create's fast path (files cache says "unmodified") does a lot of hashtable lookups in quick order, esp. for large files, when it checks whether the chunk IDs in the chunks list are still in the hashindex.

Also, while it might not give a huge boost, some of that stuff also does not require a lot of code changes, so kind of low-hanging fruit (besides needing some measurements to be really sure).

**Comment by ThomasWaldmann** [comment]
Guess this ticket can be solved by adding a comment (see topic) to the source code.

As we already have the sizes table, no other change is needed for now.
