### ISSUE TITLE
Borg considers syntax error a hostname

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2833]
```shell
$ borg create --stats --progress --compression lz4 ::{user}-{now} Wallpaper
[…]
$ borg delete rugk-2017-07-16T18:13:49
Remote: ssh: Could not resolve hostname rugk-2017-07-16t18: Name or service not known
Connection closed by remote host. Is borg working on the server?
``` 

v1.1.0b6
`BORG_REPO` is a local path.

I know there is a syntax error as I am missing the `::` (`borg delete ::rugk-2017-07-16T18:13:49` works), but the error message is confusing. Why does borg think this is a hostname and tries to resolve it, should not it rather say "syntax error" and stop?

**Comment by ThomasWaldmann** [comment]
the problem might be that some commands take `repo` or `repo::archive`, `delete` is one of them.

guess one of the colons made it think it is `host:path`.

**Comment by enkore** [comment]
Might be the IPv6 code

**Comment by rugk** [comment]
> // Folks, let this be lesson for you all on how to design interfaces. repo::archive looks cool but is a total shit show to implement. Be reasonable. Use URIs.

Haha, you may change that in the future. (v1.2 or even later, maybe) I was also confused by this syntax when I tried it first. :smiley: But I'll use the syntax you have.

**Comment by rugk** [comment]
> Might be the IPv6 code

But why would it need to resolve an IPv6 address?

BTW indeed the colon is causing the issue:
```
$ borg delete dsads-dsad:s
Remote: ssh: Could not resolve hostname dsads-dsad: Name or service not known
Connection closed by remote host. Is borg working on the server?
```

**Comment by milkey-mouse** [comment]
I don't think it can be changed until at least v2.0. After all, it would definitely break compatibility to completely remove the most common way of specifying a repo.

**Comment by milkey-mouse** [comment]
Also, it's `ssh` that's trying to resolve it. The `Could not resolve hostname` error is from SSH, that's why it's prefixed by `Remote:`

**Comment by ThomasWaldmann** [comment]
Guess we just close this. We already have another ticket to separate the repo url from the archive name to have easier parsing, scheduled for 2.0.
