### ISSUE TITLE
rpc options

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2840]
borg has its on rpc implementation in remote.py. some parts are sync, some async and it is not quite the easiest code to work with.

we could consider outsourcing that code long term if we find sth. else that works for us:
- chopsticks (just pure python stuff?) https://chopsticks.readthedocs.io/en/stable/
- pyro4 https://pythonhosted.org/Pyro4/
- zeromq (via ssh?) http://pyzmq.readthedocs.io/en/latest/ssh.html
- zeromq with own crypto (curvemq) http://curvezmq.org/

**Comment by enkore** [comment]
I don't see any advantage (at all) in switching protocols (but many disadvantages). The issue isn't the protocol, but the quasi-async client implementation, which is not solved by using a different protocol.

**Comment by ThomasWaldmann** [comment]
well, at least we have it in a more permanent place now. IRC is more transient.

**Comment by enkore** [comment]
Agreed. I added this to the ["doing things differently"](https://github.com/borgbackup/borg/projects/3) collection of issues.
