### ISSUE TITLE
lock.exclusive directory can be left behind in certain scenarios

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#285]
it seems that our lock cleanup procedure can sometimes fail to remove locks during shutdown.

i have seen at least one case of this happening, here's a transcript of my console:

    (borg)root@angela:/home/anarcat/bin# borg create -v --exclude-caches -e /home/anarcat/mp3/ -e /home/pbuilder/ -e /home/anarcat/video/ -e /home/anarcat/iso/ -e  /home/anarcat/books -e /home/anarcat/books-incoming -e .cache --stats --do-not-cross-mountpoints /media/anarcat/calyx/borg-angela-conv::2015-10-15-test / 2>&1 | grep -v ^U
    ^C
    (borg)root@angela:/home/anarcat/bin# borg create --progress --exclude-caches -e /home/anarcat/mp3/ -e /home/pbuilder/ -e /home/anarcat/video/ -e /home/anarcat/iso/ -e  /home/anarcat/books -e /home/anarcat/books-incoming -e .cache --stats --do-not-cross-mountpoints /media/anarcat/calyx/borg-angela-conv::2015-10-15-test /
    ^Cborg: Error: Keyboard interrupt.
    Traceback (most recent call last):
      File "/home/anarcat/src/borg/borg/locking.py", line 118, in acquire
        os.mkdir(self.path)
    FileExistsError: [Errno 17] File exists: '/media/anarcat/calyx/borg-angela-conv/lock.exclusive'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/anarcat/src/borg/borg/archiver.py", line 1033, in main
        exit_code = archiver.run(sys.argv[1:])
      File "/home/anarcat/src/borg/borg/archiver.py", line 989, in run
        return args.func(args)
      File "/home/anarcat/src/borg/borg/archiver.py", line 111, in do_create
        repository = self.open_repository(args.archive, exclusive=True)
      File "/home/anarcat/src/borg/borg/archiver.py", line 46, in open_repository
        repository = Repository(location.path, create=create, exclusive=exclusive)
      File "/home/anarcat/src/borg/borg/repository.py", line 64, in __init__
        self.open(self.path, exclusive)
      File "/home/anarcat/src/borg/borg/repository.py", line 138, in open
        self.lock = UpgradableLock(os.path.join(path, 'lock'), exclusive).acquire()
      File "/home/anarcat/src/borg/borg/locking.py", line 248, in acquire
        self._wait_for_readers_finishing(remove, sleep)
      File "/home/anarcat/src/borg/borg/locking.py", line 266, in _wait_for_readers_finishing
        self._lock.acquire()
      File "/home/anarcat/src/borg/borg/locking.py", line 123, in acquire
        if timer.timed_out_or_sleep():
      File "/home/anarcat/src/borg/borg/locking.py", line 70, in timed_out_or_sleep
        self.sleep()
      File "/home/anarcat/src/borg/borg/locking.py", line 61, in sleep
        time.sleep(self.sleep_interval)
    KeyboardInterrupt

    borg: Exiting with failure status due to previous errors
    (borg)root@angela:/home/anarcat/bin# borg create --progress -v --exclude-caches -e /home/anarcat/mp3/ -e /home/pbuilder/ -e /home/anarcat/video/ -e /home/anarcat/iso/ -e  /home/anarcat/books -e /home/anarcat/books-incoming -e .cache --stats --do-not-cross-mountpoints /media/anarcat/calyx/borg-angela-conv::2015-10-15-test /
    ^Cborg: Error: Keyboard interrupt.
    Traceback (most recent call last):
      File "/home/anarcat/src/borg/borg/locking.py", line 118, in acquire
        os.mkdir(self.path)
    FileExistsError: [Errno 17] File exists: '/media/anarcat/calyx/borg-angela-conv/lock.exclusive'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/anarcat/src/borg/borg/archiver.py", line 1033, in main
        exit_code = archiver.run(sys.argv[1:])
      File "/home/anarcat/src/borg/borg/archiver.py", line 989, in run
        return args.func(args)
      File "/home/anarcat/src/borg/borg/archiver.py", line 111, in do_create
        repository = self.open_repository(args.archive, exclusive=True)
      File "/home/anarcat/src/borg/borg/archiver.py", line 46, in open_repository
        repository = Repository(location.path, create=create, exclusive=exclusive)
      File "/home/anarcat/src/borg/borg/repository.py", line 64, in __init__
        self.open(self.path, exclusive)
      File "/home/anarcat/src/borg/borg/repository.py", line 138, in open
        self.lock = UpgradableLock(os.path.join(path, 'lock'), exclusive).acquire()
      File "/home/anarcat/src/borg/borg/locking.py", line 248, in acquire
        self._wait_for_readers_finishing(remove, sleep)
      File "/home/anarcat/src/borg/borg/locking.py", line 266, in _wait_for_readers_finishing
        self._lock.acquire()
      File "/home/anarcat/src/borg/borg/locking.py", line 123, in acquire
        if timer.timed_out_or_sleep():
      File "/home/anarcat/src/borg/borg/locking.py", line 70, in timed_out_or_sleep
        self.sleep()
      File "/home/anarcat/src/borg/borg/locking.py", line 61, in sleep
        time.sleep(self.sleep_interval)
    KeyboardInterrupt

    borg: Exiting with failure status due to previous errors
    (borg)root@angela:/home/anarcat/bin# jobs
    (borg)root@angela:/home/anarcat/bin# ps axfu | grep borg
    root     12308  0.0  0.0  13960  2228 pts/4    S+   20:40   0:00          |                   \_ grep borg
    (borg)root@angela:/home/anarcat/bin# ls /media/anarcat/calyx/borg-angela-conv/lock.exclusive
    angela.12158-d5c59700
    (borg)root@angela:/home/anarcat/bin# ps 12158
      PID TTY      STAT   TIME COMMAND
    (borg)root@angela:/home/anarcat/bin# file 12158
    12158: cannot open `12158' (No such file or directory)
    (borg)root@angela:/home/anarcat/bin# file /media/anarcat/calyx/borg-angela-conv/lock.exclusive
    /media/anarcat/calyx/borg-angela-conv/lock.exclusive: directory
    (borg)root@angela:/home/anarcat/bin# ls -al /media/anarcat/calyx/borg-angela-conv/lock.exclusive
    total 8
    drwx------ 2 root    root    4096 oct 15 20:29 .
    drwxr-xr-x 4 anarcat anarcat 4096 oct 15 20:29 ..
    -rw------- 1 root    root       0 oct 15 20:29 angela.12158-d5c59700

Presumably interrupted during listing.. Would need a test case to
reproduce reliably, but it's not easy because we need to send an
interrupt at just the right moment...

**Comment by ThomasWaldmann** [comment]
I thought about putting a bounty on this, as it is important. But how can we decide that it is solved?

**Comment by anarcat** [comment]
i think we need to build a unit test for this and then beat it. maybe the bounty should be on the test? :)

clearly, the locking code is not thoroughly tested otherwise this couldn't happen... in bup-cron, i wrote a Pidfile class that was some sort of locking system, and then i discovered [lockfile](https://pypi.python.org/pypi/lockfile) - maybe we should look at that implementation instead of rolling our own locking code?

**Comment by ThomasWaldmann** [comment]
I looked at misc. lock file implementations (including lockfile), but didn't find anything that looked good enough. So I rather took some ideas from them and created an improved version (maybe not improved enough yet, though).

**Comment by ThomasWaldmann** [comment]
I looked at the tracebacks, just to clarify:
They do show that there already is a lock (that's why mkdir says "file exists") and that you interrupted the lock waiting with Ctrl-C.

They do NOT show that hitting ctrl-c creates such a orphan lock.

But, while looking at the code, I likely found places where this is the case... :)

**Comment by ThomasWaldmann** [comment]
Guess long term we should try (not sure if easy/possible) to have context managers for Cache and Repository.

**Comment by ibennetch** [comment]
I have another scenario where the program exiting can leave the repository in a locked state, which seems to be related to this report. I happen to have discovered it on 0.30.0 and haven't had a chance to test with 1.0.0rc yet.

Normally I access my repository with an absolute URL, like `borg info /mnt/borg/rain::2016-02-02` but if I slip up and use the relative path `borg info rain::2016-02-02` I get a prompt about how the repository was previously located in a different location, do I want to continue? If I say no, borg exits as expected, but the next run fails due to the lock. I expect that in this case borg will properly release the lock before closing.

Should I open a new issue about it or is this a good place to report this?

**Comment by ThomasWaldmann** [comment]
likely fixed by this: https://github.com/borgbackup/borg/pull/777

**Comment by stiefel40k** [comment]
Hi, 
I just wanted to say, that I encountered this error again, with the 1.0.10 version of borg. The scenario was the following:
I have a systemd-service which starts the backup script and a systemd-timer which starts the service after 15min after the boot. (The repository is on a remote server.) I used vpn during the time borg has been started, but I didn't realize, that it already been started as I terminated the VPN connection and got back to normal internet traffic. So no surprise my backup got interrupted, and after restarting the service I got this message. After manually deleting the lock the problem got resolved.

**Comment by ThomasWaldmann** [comment]
@stiefel40k it would be interesting if the borg serve process on the repo server keeps running after your vpn connection is interrupted. If it does, that would explain the lock being hold. Maybe it just takes a while until the connection breakdown is noticed, that depends on your ssh config (server/client keepalive).

**Comment by qknight** [comment]
i'm also suffering from this. many of my backups are now not working anymore.

- Failed to create/acquire the lock /backup/apu-nixi-backup/.borg-cache/a9939f1fbe8bf8f48fb73945c5dbff5301089186bca0cb6509aa388cf8c3a0cb/lock.exclusive (timeout).
borg error, exiting

also using 1.0.10! how much do you need to fix this? this is important stuff for me as 5/7 backups now fail.

**Comment by ThomasWaldmann** [comment]
I suggest opening a new ticket about this (also answering my question from above), not appending to a closed borg 0.xx ticket.

**Comment by tuxick** [comment]
I found [https://github.com/borgbackup/borg/issues/3191](issue 3191), seems it has been fixed in 1.1
