### ISSUE TITLE
Allow alternative behaviour for borg prune

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2856]
Since https://github.com/borgbackup/borg/issues/998 / https://github.com/borgbackup/borg/pull/1008 (v1.1.0) when pruning always *all* checkpoints except the latest one. Previously it, AFAIK, did not remove these checkpoints at all.

However, one may be a fan of `--consider-part-files` and thus also consider broken/invalid backups/archives to be nice archives as you can still recover *something*. However when doing "borg prune" always all old checkpoints are deleted, so the desperate wanting to use `--consider-part-files` cannot use it anymore, because the prune run. (And you also run prune, after a backup has failed. If this happens many times in a row and always fails, one may rather want to have these checkpoint archives than nothing or a very old archive…)

So IMHO you should also add `--consider-part-files` to "borg prune" and thus honour it in this command too. AFAIK this is not done yet, or am I wrong?

/cc @jdchristensen

**Comment by ThomasWaldmann** [comment]
Well, I'ld say if your backup procedure is that unreliable that you end up with checkpoints mostly and too rarely with completed backups, you should search for better ways, like:

- doing backups more frequently (if each checkpoint makes significant progress, it should be also possible to complete backups frequently enough and if not, it is hopeless anyway)

- using a different connection to your repo (e.g. not a unreliable/slow internet connection, but local media, usb or LAN)

**Comment by rugk** [comment]
Yeah, okay, that's an idea, but maybe people want to be assured anyway that checkpoints stay there for some time at least even if currently no errors happen. Besides paranoid users :wink: (or ones in situations where data loss even for fresh backups is so critical) it could be useful for people, whose connection to the repo varies. (laptop/travelling/etc.)
For automated backups there they cannot do backups too frequently (as it is unnecessary when in a good LAN), but sometimes also are some days with a bad connection (travelling outside of WLANs) and thus would still have their "partial backups" to be saved. As some would say: **just in case** – better save it.
I mean even with the alternative approach it would get pruned regularly and exactly in the same way as "usual complete backups", so they do not waste space, but they may just not agree that "checkpoints" are so useless that you have to prune them right away.
Let the user decide and offer options… (Where did I read that recently… ahh it was [here](https://borgbackup.readthedocs.io/en/stable/faq.html#why-was-borg-forked-from-attic) :smiley: )

**Comment by enkore** [comment]
> offer options

I don't care about this, but options are a means to an end,  not an end in itself.

http://www.sandraandwoo.com/comics/2012-11-19-0430-software-engineering-now-with-cats.png

**Comment by ThomasWaldmann** [comment]
Also note that as checkpoints are not complete backups, you never know what's in them (before listing them). So you can't really rely on them. You might be lucky or not.

So I don't think we want to deal with them except as a temporary thing until the latest backup is completed.

You still can keep them for a bit longer time by not running prune too frequently (like only every few weeks).
