### ISSUE TITLE
How to delete a dir/file in an archive?

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2858]
How can one delete a part of one (or multiple) archive(s) such as a dir or file?
Obviously you cannot use `borg delete` for that.

However, also `borg mount` does not work as – at least in my tests – it seems to mount the repo in read-only mode, i.e. I cannot create files in there e.g.

So how can this be accomplished? (With borg itself, without third-party tools… at least, preferably)

**Comment by enkore** [comment]
https://borgbackup.readthedocs.io/en/latest/usage/recreate.html

**Comment by rugk** [comment]
Ah, thanks so this example basically shows it:
``` 
borg recreate /mnt/backup --exclude home/icke/Pictures/drunk_photos
```

However this is only available in v1.1.0, so there is no way with borg <1.1.0?
And secondly, does this redownload the archives? When I do not use rechunking or compression?

**Comment by rugk** [comment]
> And secondly, does this redownload the archives? When I do not use rechunking or compression?

?

**Comment by enkore** [comment]
> When I do not use rechunking or compression, does this redownload the archives?

In this case only metadata is processed, the actual data of the archive is not processed.
