### ISSUE TITLE
rewrite process name to `borg`

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#286]
right now, borg is kind of ugly in the process list: we have the `python` binary in there, so we can't do stuff like `killall borg` and display is needlessly noisy.

It would be nice if borg would show up as "borg" instead of "python borg" or whatever. bup does this through [unpythonize_argv()](https://github.com/bup/bup/blob/b283da69ee1a65502f9ddbb7e4603af34e7bde6b/lib/bup/_helpers.c#L198) which does some pretty heavy memset() stuff to clear it up. there has to be a better way (tm).

**Comment by ThomasWaldmann** [comment]
This somehow looks like a rather dirty hack and might be even platform depedant, so I'ld rather not have that.

It's no problem finding the pid with ps and grep.
Also, we should try to get borg into a state where it doesn't have to be killed that often.

**Comment by anarcat** [comment]
i started working on something that would use the `setproctitle` module, which is a fairly clean and platform-independent implementation. then i blew up the head branch. :) anyways, the code is in #298...

**Comment by ThomasWaldmann** [comment]
As this adds new dependencies and is a rather cosmetic fix, I labelled it as "later". We are still working on the last dependencies we added (like lz4 not available everywhere and setuptools_scm related issues).

**Comment by ThomasWaldmann** [comment]
Note: Debian and Ubuntu has packages for this.

**Comment by anarcat** [comment]
no problem, fix is trivial enough that it can be integrated later... i'll close the PR to avoid duplication.

**Comment by anarcat** [comment]
for the record, in `top(1)` in debian jessie, this looks fine (debian backport):

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1902 root      20   0  533864 446908   4824 R  53,3 12,3   1:55.28 borg
```

`ps x` is a little less pretty, but i am not sure that is a problem:

```
$ ps a| grep borg
 1899 pts/7    S+     0:00 sh backup-borg-angela
 1902 pts/7    D+     2:06 /usr/bin/python3 /usr/bin/borg create -v --exclude-caches -e /home/anarcat/mp3/ -e /home/pbuilder/ -e /home/anarcat/video/ -e /home/anarcat/iso/ -e /home/anarcat/books -e /home/anarcat/books-incoming -e .cache --stats --do-not-cross-mountpoints /media/anarcat/calyx/borg-angela-conv::angela-2016-02-02 /
```

especially since killall does the expected thing:

```
$ LANG=C killall borg
borg(1902): Operation not permitted
```

ie. it finds the process! (but doesn't kill it, because it's not running as root and i don't want to actually interrupt the backup)

**Comment by ThomasWaldmann** [comment]
@anarcat you talk about the debian backport, so it is code that does not have special setproctitle calls.

so are you saying we don't need that, because tools are working good even without us doing setproctitle?

**Comment by anarcat** [comment]
On 2016-02-04 09:35:03, TW wrote:
> @anarcat you talk about the debian backport, so it is code that does not have special setproctitle calls.

correct.

> so are you saying we don't need that, because tools are working good even without us doing setproctitle?

i was not drawing any conclusions, just saying that things were not as
bad as I reported originally. it may be because of changes in Debian
jessie (e.g. killall), i don't know.

-- 
We all pay for life with death, so everything in between should be
free.
                         - Bill Hicks

**Comment by rumpelsepp** [comment]
What is the advantage of this over `pgrep`? If I want to kill borg I can just file `kill $(pgrep borg)`; there is imo no need for such a hack.

**Comment by ThomasWaldmann** [comment]
As we found multiple ways to solve that / not need that, shall we close this issue?

The fewer dependencies we have, the easier packagers have it to adopt and maintain borg.
