### ISSUE TITLE
Can mount, but not umount

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2863]
v1.0.9

STR (working as a non-root user by default):
1. mkdir mnt
2. setting repo/passphrase
3. ```shell
    $ borg mount :: ./mnt
    fuse: failed to exec fusermount: No such file or directory
    ``` 
4. Retried with `sudo borg mount :: ./mnt` works. (`borg mount :: ./mnt  4,81s user 0,75s system 27% cpu 19,883 total`) on a btrfs filesystem BTW. (Also set repo etc. again, so it works.)
5. browse in it
(interestingly for non-root users no username/password were shown and they could not access it)
6. Unmounting fails:
```shell 
borg umount ./mnt
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2052, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1997, in run
    return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 564, in do_umount
    return umount(args.mountpoint)
  File "borg/platform_linux.pyx", line 148, in borg.platform_linux.umount (borg/platform_linux.c:4217)
  File "/usr/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'fusermount'

Platform: XXXXXXX #2 SMP Sat May 6 19:26:50 UTC 2017 armv7l 
Linux: debian 9.0 
Borg: 1.0.9  Python: CPython 3.5.3
PID: 9277  CWD XXXXX
sys.argv: ['/usr/bin/borg', 'umount', './mnt']
SSH_ORIGINAL_COMMAND: None
```

With `umount ./mnt` I could finally unmount the repo anyway…

**Comment by ThomasWaldmann** [comment]
Why don't you have fusermount?

fusermount -u is the usual way to unmount a FUSE mount as a user on linux.

according to your error messages, it seems to be also used by mount somehow (although borg does not directly call it for that).

**Comment by rugk** [comment]
It's not there, but somehow borg managed to mount the archive anyway…

```
$ which fusermount
fusermount not found
$ ls -la /usr/bin/*mount* 
-rwxr-xr-x 1 root root 1275 Jun 10  2016 /usr/bin/cgroupfs-mount
-rwxr-xr-x 1 root root  620 Jun 10  2016 /usr/bin/cgroupfs-umount
$ ls -la /bin/*mount* 
-rwsr-xr-x 1 root root 30832 Mär 22 10:43 /bin/mount
-rwxr-xr-x 1 root root  9952 Mär 22 10:43 /bin/mountpoint
-rwsr-xr-x 1 root root 22492 Mär 22 10:43 /bin/umount
```

> fusermount -u is the usual way to unmount a FUSE mount as a user on linux.

Upps, but "umount" worked anyway… :laughing: 

Debian 9 here, Bananian here. fusermount does not seem to be included in Bananian. :smile: 
And the borg Debian package also does not seem to have it set as a dependency. :smile:

**Comment by ThomasWaldmann** [comment]
In Ubuntu, it is in the `fuse` package and gets installed to `/bin/fusermount`.

**Comment by rugk** [comment]
Maybe, but as I said, it's not there, here. I think my commands above prove this.

**Comment by ThomasWaldmann** [comment]
OK, file a bug to bananian or whatever, this is out of scope of borg.

**Comment by rugk** [comment]
But it **is** inside the scope of borg, why it could actually **mount** an archive without fusermount…
That's a kinda strange bug, as – if there would not be any other tool for unmounting – the user would have been trapped here.

**Comment by ThomasWaldmann** [comment]
being able to do mount as root is no surprise, the point of fusermount is not needing root.

but if you don't have fusermount installed (for whatever reason outside of borg project that is), it won't work as user.

**Comment by ThomasWaldmann** [comment]
hmm, the only thing that might be todo for `borg umount` is to check whether it runs as root and whether calling `fusermount -u` failed and then just try `umount`.

**Comment by rugk** [comment]
Ah, yeah, now I understand. :+1:
