### ISSUE TITLE
Allow writing in borg mount

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2864]
Why not have an option (`--allow-write`), which mounts the borg repo in r/w mode, so that I can delete files/archives. This would solve https://github.com/borgbackup/borg/issues/2858 easily and in a convenient way for the user.

Or is this solution not possible/too difficult?

**Comment by ThomasWaldmann** [comment]
too difficult and also not worth it. borg is a backup tool. archives are basically read-only.

borg recreate offers a way to re-create a new archive based on an old one (but even that is not modifying the original one).

**Comment by cpitclaudel** [comment]
Related discussion: https://github.com/NixOS/nixpkgs/issues/89380

**Comment by ThomasWaldmann** [comment]
@cpitclaudel i see that a deduplicating fs is useful for some purposes (if one is willing to take the resource consumption overhead, like RAM and CPU), but the borg fuse fs is not the right base for that, see my comment above.

**Comment by cpitclaudel** [comment]
Completely fair :) I added the link to also reroute future visitors.
