### ISSUE TITLE
When merging/pulling chunk index --progress-like output is used despite not passed

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2866]
When you need to merge the chunk index as you deleted the local chunk index/cache, then you always get this log output: (when piping/directing it to a log file as you usually do in automated systems):
```
Merging chunk index... (0.00%)
Merging chunk index... (1.22%)
Merging chunk index... (3.32%)
[…]
Merging chunk index... (100.00%)
```
(no original log file, just how I remember it)

However the command I executed there (borg create), did not have the `--progress` parameter passed, but just some usual ones (`-v` and `--stats`), whcih do have such a progress bar/indicator. Thus, IMHO, the behaviour of borg is wrong here. The output without `--progress` should be something like `Merging chunk index...` without any percentage.

v1.0.10

**Comment by ThomasWaldmann** [comment]
I can't find these messages in 1.0.10. There are some other messages, but no percentage progress display. It announces the archives as they get fetched / merged to build the chunks index.

IIRC this was implemented because people complained that it was taking a longer time, but nothing was visible, so they were unsure what's happening / if something was happening. Note that -v means verbose, so you have to expect some informative output.

If you still think this is a bug, reopen it and give more / more precise information.

**Comment by rugk** [comment]
> I can't find these messages in 1.0.10. There are some other messages, but no percentage progress display.

Wait… what?
You claim the `Merging chunk index... (0.00%)` is not there and it is just `Merging chunk index...` or what?
I mean later you confirm you implemented it, so I don't really know what you want to say here.

> Note that -v means verbose, so you have to expect some informative output.

But not `-progress`. But `borg create` with `-v` also shows no progress information about the actual backup (and takes a long time, too), so well…

What is annoying about these messages is just that each 0.0x % is shown and this spams your whole log file, when you pipe the output into your log.

**Comment by ThomasWaldmann** [comment]
It is implemented in 1.1.x. The problematic stuff is all what runs server side.

**Comment by enkore** [comment]
> The problematic stuff is all what runs server side.

This is about the cache sync.

**Comment by ThomasWaldmann** [comment]
Corrected. But still, there is no such progress in 1.0.10.

**Comment by rugk** [comment]
So v1.1.0 of borg do not display the progress anymore? If so, then this is fixed.

BTW on the sever side I may indeed used a lower/older version that 1.0.10.

**Comment by enkore** [comment]
> Corrected. But still, there is no such progress in 1.0.10.

1.0 does have this, and shows it as soon as you pass -v.

**Comment by ThomasWaldmann** [comment]
```
tw@tux:~/w/borg$ git checkout 1.0.10
Note: checking out '1.0.10'.
...
HEAD is now at e5f7121... paperkey.html - decode as utf-8, fixes #2150
tw@tux:~/w/borg$ grep -r Merging.chunk.index borg
tw@tux:~/w/borg$ grep -r Merging.chunk.index borg
(nothing)
```

**Comment by enkore** [comment]
https://github.com/borgbackup/borg/blob/1.0.11/borg/cache.py#L352

**Comment by ThomasWaldmann** [comment]
That is:
- another message
- it is only one time
- not counting percents.

**Comment by ThomasWaldmann** [comment]
Maybe related: #3195
