### ISSUE TITLE
1.1.0b6: Meaning of "max. archive size" unclear

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2868]
`borg info` has a new entry:
```
Utilization of max. archive size: 0%
```

So what does this mean?
I assume this is https://github.com/borgbackup/borg/pull/2565, so it is a storage quota, but does not it apply to the whole repo, not only to one archive?
So does not it have to say this?
```
Utilization of max. repo size: 0%
```

Or do you mean?
```
How much size this archive utilises in the whole repo: 0%
```

~~Then I would suggest something like this (it's in a more readable shorter way):~~
~~Part of max. repo size: 0%~~

Well… no, it basically means the same as "Utilization of max. repo size". I think that wording is okay.

**Comment by rugk** [comment]
Just noticed in case of no storage quota (as it's the default), "How much size this archive utilises in the whole repo" cannot be 0%, as it would also apply without storage quotas, but this does not seem to be the case, so actually I think it only applies to storage quotas.

**Comment by ThomasWaldmann** [comment]
it is referring to the max. size of the metadata stream.

**Comment by enkore** [comment]
(the maximum archive size borg can process)

**Comment by rugk** [comment]
Ohh, okay. :open_mouth:  Is this documented anywhere?

If it is such a strange thing, which may be only useful for debugging, why show it at all there.
As said, my tries to explain the thing, were wrong, but they could still make sense it would be quite useful to check that you do not exceed your quota e.g., but why on hell should a normal borg user (so no dev/no debugging) need this information?
I mean this limit is likely/hopefully a very big number (some terrabyte or so)… @enkore [once said](https://github.com/borgbackup/borg/issues/37#issuecomment-309247108) borg works with >40TB… so the limit must certainly be higher than 40 TB…
And if it is so high, 90% of the borg user may not even get 5% in the information screen and as such the information is largely useless for an average user, who does not create incredible huge archives.

BTW what is the max archive size "borg can process"? Is that be a hard limit?

**Comment by enkore** [comment]
You can hit that limit within a few dozen GB; it's essentially unrelated to the size of the files.

The meaning of this should be documented in the borg info help page, yes.

**Comment by rugk** [comment]
> You can hit that limit within a few dozen GB; it's essentially unrelated to the size of the files.

That's interesting. But it is archive-specific?

And do you still think this is an information, which should be visible to the end-user? I mean likely you could also show a user the number of chunks used in an archive, but usually the user does not care/it does not matter, …

**Comment by enkore** [comment]
> Is this documented anywhere?

https://borgbackup.readthedocs.io/en/latest/faq.html#are-there-other-known-limitations
https://borgbackup.readthedocs.io/en/latest/internals/data-structures.html#archive-limitation

> But it is archive-specific?

Yes.

> And do you still think this is an information, which should be visible to the end-user?

This is not a hypothetical limit. For jobs operating near it, the limit must be monitored, otherwise backups may start to fail. It is used to split large jobs as well.

**Comment by rugk** [comment]
Ah, thanks. Anyway maybe you can improve the wording of "Utilization of max. archive size". As you see at least I was quite confused by it.
