### ISSUE TITLE
borg extract --delete

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#2872]
Is it possible / how to do `borg extract` with deleting missing files like `rsync --delete` does ?

The case is to do restore from older snapshot where most files are exists and not changed but some files were changed and some files were created. So I need just to switch the state to older. Also, do not download existing files will be good.

**Comment by enkore** [comment]
Special case of #1986?

**Comment by knutov** [comment]
@enkore kind of, more sound like my description is shorter but feature is the same. And it's really very important functionality that will make restore process much better.

Is it possible to invent this for borg 1.1 ?

**Comment by ThomasWaldmann** [comment]
1.1 is in release candidate phase now, so currently no new features.

also, the features added in 1.1.x should be limited to rather urgent stuff (like stuff that was forgotten or came up as desperately missing in practical use) or small / uncritical stuff.

**Comment by knutov** [comment]
@ThomasWaldmann To me this is really the stuff that was forgotten, but I got your point. Can this be added to 1.2 milestone then?

**Comment by ThomasWaldmann** [comment]
we'll rather focus on multithreading (and required crypto changes) in 1.2. the more scope creep we have, the longer you won't see releases.

**Comment by ipha** [comment]
As a workaround you could mount the repo somewhere with `borg mount` then rsync out of that.

**Comment by knutov** [comment]
@ipha In our case borg's backup server is always located in different datacenter in different country.  Getting files over borg mount is extremely slow in such case.

@ThomasWaldmann Can this feature be planned for 1.1.1?

**Comment by ThomasWaldmann** [comment]
@knutov that's likely not a small feature, so it maybe has to wait until after 1.2.

I'm closing this in favour of #1986, we don't need to discuss this in 2 different places.

@knutov if you want to clarify, feel free to extend there.
