### ISSUE TITLE
GitHub: sign original source archives

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2874]
Currently you always attach another new signed archive to the GitHub releases for the source code. However, GitHub already bundles the source code archive automatically.

And as these files are reproducible, there is a nice way to sign them and only upload the signature.
See https://github.com/rugk/gittools/blob/master/signrelease.sh for a small script.

**Comment by ThomasWaldmann** [comment]
What I upload additionally to github releases is the sdist + sig as pushed to pypi.
I like to publish that there, just in case...
