### ISSUE TITLE
Document how to run borg on a Synology NAS

### ISSUE THREAD

**Issue by milkey-mouse** [borgbackup/borg#2879]
Synology's DSM doesn't support `ssh`ing directly in as far as I can tell. However there are many ["packages"](https://www.synology.com/en-us/dsm/packages) that can be installed to run a Git server, http server, etc. There is a [developer guide](https://global.download.synology.com/download/Document/DeveloperGuide/DSM_Developer_Guide.pdf) for creating third-party packages, but there is already a [Docker package](https://blog.pavelsklenar.com/how-to-install-and-use-docker-on-synology/). With a small distro (e.g. Alpine Linux) and borg installed this could be a good solution.

**Comment by HerleX** [comment]
> Synology's DSM doesn't support sshing directly in as far as I can tell

You can ssh into the Synology system by activating the SSH service in your Control Panel. [More Information here...](https://www.synology.com/en-us/knowledgebase/DSM/help/DSM/AdminCenter/system_terminal)

I am currently using a standalone binary which i have copied to `/usr/local/bin` on my DiskStation.
After adding the path to your Environment variables you can use the borg-command like on any system.

**Comment by milkey-mouse** [comment]
Hmm, I guess this issue is kind of moot then; once you get SSH set up it's the same as any other borg server.
