### ISSUE TITLE
how can I see in which files were the last archive's changed blocks

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#2884]
Each time I do a backup I need to see WHERE did most changes occur.
It seems impossible with current borg. OR?

I can imagine we could extend borg info to show that too.

The nearest I got so far is by logging borg create's output and then run the list of changed/added files through "du" and sort by file size. But that just shows the biggest files in the archive sorted NOT how much blocks changed in each file ...

Ideas ?

PS. This feature could help preventing the back up of large dirs/files one did not want to backup. So after each backup you can inspect the logs and re-do the backup after excluding some dir u forgot the 1st time.

Or you can run the report once a month and if needed run borg recreate (coming in borg 1.1) to delete retroactively those dirs/files u don't need backed up.

**Comment by ThomasWaldmann** [comment]
Not perfect, but helping:

`borg create -v --list --stats` you see how much it grew in total and have a list of file to make educated guesses.

**Comment by DrupaListo-com** [comment]
@ThomasWaldmann indeed create -v --list --stats (possibly with --filter AME) allows for some educated guesses...
Another approach is to diff borg list outputs using custom placeholders for size/filename...
But the best option imho is the recent 1.1.x borg diff that actually solves it all! Agree?

**Comment by ThomasWaldmann** [comment]
I personally didn't use borg diff for that yet, so just try and if it works, update the ticket with the solution and close.

**Comment by devZer0** [comment]
i always wondered why i nevere see "M" with --list and --filter AME, why are the files being shown as ADDED instead of MODIFIED?

some other person reported this today:  https://mail.python.org/pipermail/borgbackup/2018q1/001003.html

**Comment by ThomasWaldmann** [comment]
@devZer0 that is a different issue, please file a separate bug for it.

**Comment by facorazza** [comment]
I think this issue can be closed. `borg diff` does indeed show the differences between archives.
