### ISSUE TITLE
FreeBSD SSH server with a particular TCP port

### ISSUE THREAD

**Issue by Nikoos** [borgbackup/borg#2885]
Hello,

I am trying to set up a remote repo in a FreeNas jail (inside a freebsd jail precisely) using a reverse SSH tunnel.

My goal is to use my FreeNas in my house in order to initiate a reverse SSH tunnel (TCP NAT 26000) to my remote server (TCP 22, with an iptable rule to allow only a certain IP) then borg will this reverse ssh tunnel to access the remote storage, (note : I was able to setup my reverse SSH tunnel using SSHFS and use sshfs to access my remote repo, however I saw in the documentation that I can use directly ssh).

From my jail, I used the following command to initiate my reverse SSH tunnel (aaa.bbb.ccc.ddd is my remote device) : 

`ssh -N -R 26000:127.0.0.1:22 borg-user@aaa.bbb.ccc.ddd`

Using this command from my jail, my reverse SSH tunnel is up.

From my remote device, if I try the following command : 

`ssh sshtunnel@localhost -p 26000`

After dealing with my password (I test in a lab) : I have my FreeBSD Jail shell

If I try via the borg command : 

`/usr/bin/borg create --verbose --stats --progress --compression lz4 ssh://sshtunnel@localhost:26000/mnt/remote::'{hostname}-{now:%Y-%m-%d}' / --exclude /dev --exclude /proc --exclude /mnt --exclude /sys --exclude /run --exclude /tmp`

Once I typed the sshtunnel password, I have the following message : 

`Password for sshtunnel@borg_jail_01:
Remote: bash: borg: command not found
Connection closed by remote host. Is borg working on the server?`

I think, borg is trying to run the borg command on the remote ssh server...

Best regards,

Nikos

**Comment by enkore** [comment]
> I think, borg is trying to run the borg command on the remote ssh server...

Borg must be installed on the remote end for remote repository access.

See https://borgbackup.readthedocs.io/en/stable/quickstart.html#remote-repositories

**Comment by Nikoos** [comment]
My bad, I did not read enough the documentation. 

Sorry for this non-issue.

Thanks for your help
