### ISSUE TITLE
prune display: show rule that kept the backup

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2886]
people are often wondering how prune works / whether it does what they told.

instead of just showing a list with backup names and timestamps, we could also display the rule that triggered keeping the backup right besides it.

**Comment by enkore** [comment]
https://github.com/enkore/borgcube/blob/master/src/borgcube/job/prune.py#L73 (EUPL)

**Comment by NiklasMM** [comment]
I would like to give this issue a try, can I be assigned please?

**Comment by ThomasWaldmann** [comment]
fixed by #3235, thanks @NiklasMM!
