### ISSUE TITLE
clarify units used everywhere

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#289]
right now, we use strings like `kB` arbitrarily, without clearly stating anywhere whether we use powers of `10` ("kilo") or `2` ("kibi"). At the sizes that Borg deals with, this can become [significant](https://en.wikipedia.org/wiki/Binary_prefix#Deviation_between_powers_of_1024_and_powers_of_1000) (10% error on "terabyte" vs "tebibyte"!).

i believe this could be solved by either:

1. documenting clearly which units we are using in the documentat (but where?)
2. explicitely use IEC prefixes

In any case, `format_file_size()` could be simplified greatly. For example, here's an implementation from [this stackoverflow response](http://stackoverflow.com/a/1094933/1174784)

```python
def sizeof_fmt(num, suffix='B'):
    for unit in ['','Ki','Mi','Gi','Ti','Pi','Ei','Zi']:
        if abs(num) < 1024.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1024.0
    return "%.1f%s%s" % (num, 'Yi', suffix)
```

obviously, this is for IEC prefixes, for decimal, it would be:

```python
def sizeof_fmt(num, suffix='B'):
    for unit in ['','K','M','G','T','P','E','Z']:
        if abs(num) < 1000.0:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= 1000.0
    return "%.1f%s%s" % (num, 'Yi', suffix)
```

Fun times:

```python
def sizeof_fmt(num, suffix='B', units=None, power=None):
    for unit in units[:-1]:
        if abs(num) < power:
            return "%3.1f%s%s" % (num, unit, suffix)
        num /= float(power)
    return "%.1f%s%s" % (num, units[-1], suffix)

def sizeof_fmt_iec(num, suffix='B'):
   return sizeof_fmt(num, suffix=suffix, units=['','Ki','Mi','Gi','Ti','Pi','Ei','Zi', 'Yi'], power=1024)

def sizeof_fmt_decimal(num, suffix='B'):
   return sizeof_fmt(num, suffix=suffix, units=['','K','M','G','T','P','E','Z', 'Y'], power=1000)
```

then you can select which one you want dynamically...

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/27480669-clarify-units-used-everywhere)

**Comment by ThomasWaldmann** [comment]
We'll just use prefixes as they are meant to be, k = 1000, ki = 1024, etc.

For formatting decimal output, 1000-based would be easier.

**Comment by anarcat** [comment]
yet i believe the flexible output could be useful. for example, if we ever report ram usage, that is commonly shown in IEC prefixes (powers of two)...

so maybe the decimal output should be documented better...

**Comment by anarcat** [comment]
oh, and my code has a small error: it should be `k` (lowercase) in the SI system.

**Comment by anarcat** [comment]
#316 should cleanup the code, only documentation needed here.

**Comment by ThomasWaldmann** [comment]
related: #5743 - will add a --iec option.
