### ISSUE TITLE
netbsd: create vagrant VM for borg 1.2 testing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2894]
The current master branch Vagrantfile misses such a VM, see 1.1-maint branch for such a VM:

https://github.com/borgbackup/borg/blob/1.1-maint/Vagrantfile

The VM needs to be updated to work with:
- OpenSSL 1.1
- Python 3.6

Some VMs are used to build a borg binary with pyinstaller: Linux, FreeBSD, OS X.

In the past we used a rather old system to get a old (g)libc, but for borg 1.2 the system should be a recent one that still gets security updates for quite some time. Also: 64bit only. People needing old stuff can just use borg 1.0/1.1 binaries.

**Comment by ThomasWaldmann** [comment]
looks like netbsd 8.0 (currently available as release candidate) is still based on openssl 1.0.2.

**Comment by ThomasWaldmann** [comment]
Can some netbsd user update me about the OpenSSL versions situation?

**Comment by ThomasWaldmann** [comment]
Anyone?

**Comment by ThomasWaldmann** [comment]
from @needydev on twitter: "netbsd-current (and netbsd-9 will) have openssl 1.1.1" \o/

**Comment by ThomasWaldmann** [comment]
netbsd 9 was released feb 2020!

**Comment by ThomasWaldmann** [comment]
looks like we'll drop netbsd testing if they can't provide a current vagrant box.

**Comment by ThomasWaldmann** [comment]
There is a netbsd 9.1 box now.

**Comment by ThomasWaldmann** [comment]
Issues found:

- PATH incomplete, e.g. chown is not found
- / and /tmp have too little space
- spills a ton of warnings like that although I pointed to the 9.1 packages url:
```
    netbsd64: pkg_add: Warning: package `libidn-1.36nb1' was built for a platform:
    netbsd64: pkg_add: NetBSD/x86_64 9.0 (pkg) vs. NetBSD/x86_64 9.1 (this host)
```
- strange warnings also:
```
    netbsd64: sort: /dev/stdin: 
    netbsd64: Device not configured
```

**Comment by ThomasWaldmann** [comment]
https://mail-index.netbsd.org/current-users/2020/04/13/msg038329.html same issue, no solution.

**Comment by ThomasWaldmann** [comment]
@bsiegert thanks for making the new vagrant box! can you have a look at the issues, please?

**Comment by ThomasWaldmann** [comment]
If the box is updated for netbsd 9.2, maybe the above issues could be fixed. ^^^

**Comment by ThomasWaldmann** [comment]
@bsiegert do you have time to create a 9.2 vagrant box and fix the above issues?

**Comment by ThomasWaldmann** [comment]
fixed by #5854.

still seeing segfaults now and then though - although i use a different netbsd 9.2 base box.

**Comment by bsiegert** [comment]
>  do you have time to create a 9.2 vagrant box and fix the above issues?

Unfortunately, I don't. I am also not the one who made the Vagrant box. I merely asked on the mailing list who maintains these, and someone (not even sure who) stepped in.

`/sbin` and `/usr/sbin` missing from PATH is WAI, they are only in the default PATH for root. The segfaults shouldn't happen (TM), and I have never seen these in my usage of NetBSD.

If you are using VirtualBox as the underlying virtualization layer, there have been mysterious segfaults with NetBSD and OpenBSD before. Maybe try something qemu-based (KVM?) if that's a possibility.

**Comment by ThomasWaldmann** [comment]
@bsiegert ah, thanks for clarifying.

Yes, I use virtualbox. IIRC no issues for openbsd, just python on netbsd9 crashes rather often.
