### ISSUE TITLE
Comparing modified items incorrectly assumes comparable chunk ids

### ISSUE THREAD

**Issue by imsodin** [borgbackup/borg#2899]
This came up in #2842 (see during https://github.com/borgbackup/borg/pull/2842/files#diff-0c1790c20ac3974e84f97b2ded80507bR449) but the problem was there before https://github.com/borgbackup/borg/blob/master/src/borg/archiver.py#L1028.
The current solution of comparing just chunk ids is fine as long as the two archives were created with the same chunker params, but doesn't work otherwise.
I am not sure what would be the cheapest way to get matching contents from two chunk iterators. Maybe creating new chunks from the chunks with the same params?

**Comment by ThomasWaldmann** [comment]
iirc i have seen some code that actually reads the file contents then and compares them, which is expensive.
but borg diff warns about being expensive in that case.

**Comment by imsodin** [comment]
Yes [this is the warning](https://github.com/borgbackup/borg/blob/master/src/borg/archiver.py#L1162) and [this the expensive function](https://github.com/borgbackup/borg/blob/master/src/borg/archiver.py#L199), but that only determines whether they are equal. Thus as soon as there is a difference it can return. Finding matching content to return how many bytes were removed and added is more complex as shifted content needs to be accounted for.

**Comment by ThomasWaldmann** [comment]
I guess we rather won't compute it for that case. Changing chunker params is a rare event, so not knowing how much changed exactly when crossing that boundary is no big issue.

**Comment by imsodin** [comment]
Fine, then probably just put in a generic statement ("modified file"). I think this was introduced in 1.0. Should a PR fixing this be against 1.0-maint or will that get picked from master?

**Comment by enkore** [comment]
> Should a PR fixing this be against 1.0-maint or will that get picked from master?

The latter ([long version](http://borgbackup.readthedocs.io/en/latest/development.html#branching-model)). None of this is in 1.0, though.
