### ISSUE TITLE
factor out progress out of upgrade and create

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#291]
upgrade and create both use the hackish `\r` to display progress. that may be fine, but maybe we want to refactor `report_progress()` so it can be used by `upgrade`?

similarly, there should be a `--progress` argument to `upgrade`...

**Comment by ThomasWaldmann** [comment]
I am closing this as upgrade now got a progress indicator (but not using the same code as create).
It uses one of some progress indicator classes implemented in helpers.

As upgrade basically counts segment files while create is giving detailled statistics with original, compressed, deduplicated amounts, they are rather different anyway.

**Comment by anarcat** [comment]
there were two things this was supposed to do:

1. add a --progress flag to `upgrade` (not done)
2. factor out the `\r` stuff out of `upgrade` and `create` so that we have one set of tests and one codebase to handle that kind of "one-line display" (not done)

**Comment by ThomasWaldmann** [comment]
Do you think it makes sense to check the --progress switch there (or asked differently: that it is silent by default)?

I thought this is a place where one unconditionally wants to see a progress indication, that is why I didn't check for the --progress option.

**Comment by anarcat** [comment]
yeah, i guess it may not make sense to run upgrade in batch - but you never know! maybe some provider will be running a large number of borg repositories and upgrade them all at once, and won'T want that garbage in their logs! so yes, that's anothe reason for refactoring this so it's at least consistent.

**Comment by ThomasWaldmann** [comment]
note: adding --progress flags is easy, but for repository operations that run on the server, flag needs to be transmitted to remote side also.

**Comment by ThomasWaldmann** [comment]
as borg upgrade does not support remote repos currently, see #465, the passing of the progress flag via rpc is not an issue yet.
