### ISSUE TITLE
sizes and times hard to graph

### ISSUE THREAD

**Issue by franz82** [borgbackup/borg#2911]
Looking an output of command like `borg create -v --stats --show-rc ...`,
this is perfect for a first look after the execution but it's a nightmare if I want to graph this data.
Especially sizes and times are in human readable format, while I may decide to use a standard unit for a graph used for all data.
Who analyze or graph post backup data? In which way do you do that?
Regards,
-f

**Comment by enkore** [comment]
1.1 ([see here](https://www.borgbackup.org/releases/)) can output JSON. It's not 100 % stable yet.

https://borgbackup.readthedocs.io/en/1.1-maint/internals/frontends.html#standard-output
