### ISSUE TITLE
Icinga/Nagios monitoring script

### ISSUE THREAD

**Issue by kosli** [borgbackup/borg#2912]
I was just wondering if somebody has created a icinga/nagios script for monitoring the status of its borg backups? Couldn't find anything on the net...

**Comment by bebehei** [comment]
Well, that was my approach: https://github.com/bebehei/nagios-plugin-check_borg

It only checks for the latest execution, but PRs are welcomed!

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/community/ add it there? PR?

**Comment by bebehei** [comment]
Thank you @ThomasWaldmann. I will also add backup-with-borg (my self-written bash wrapper).

**Comment by kosli** [comment]
@bebehei  thanks for the script. as i have the issue with the backups being stored on read-only media, i don't want to remount rw/ro for every backup check (e.g. every X minutes) , especially as it would get in the way with a backup running and locking the repo. one idea was to use a overlayFS for the backup check, but still not the perfect solution. 
i think i will go another way: i will use the "--stats" output during the backup execution and store it in a file, that file will then be checked by a simple script to see the status of the last backup, and if it was in the last X hours. simliar like the script that i am using currently for my rdiff-backup jobs: https://exchange.nagios.org/directory/Plugins/Backup-and-Recovery/check_rdiff/details

**Comment by bebehei** [comment]
I pull the "Pull Requests Welcome". As my repos are not deletable via `rm`, I don't have to remount ro/rw before/after backup. Additionally IMHO it makes no sense mounting borg ro, as it does can't do anythinf then.

Also, why don't you change the check time to something more useful like 1h? Or only check a single time, when the backup has presumably finished.

**Comment by kosli** [comment]
Pull requets, sure, as soon as i get time to implement something
how are your repos not deletable via rm?  first step when running my borg scripts is remount rw, and remount ro when it finishes.
Even if the check time would be bigger, i would run into the same issue (e.g. worst case a backup blocks it for many hours etc.).   and despite that, i would need to reconfigure many checks at different locations to have a different check interval (and timeouts), and i don't want to take that effort.
