### ISSUE TITLE
lots of random accesses for chunks cache rebuild

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2919]
just noticed lots of random I/O noises from server hosting a borg repo.

client runs a chunks cache sync with borg 1.1.0rc1 and is working ("Fetching and building archive index") since longer on 1 archive made on 2017-07-25, causing these noises. this archive was made with borg 1.1.0beta also, using `--no-cache-sync`.

**Comment by ThomasWaldmann** [comment]
maybe it is fetch_missing_csize().

**Comment by ThomasWaldmann** [comment]
hmm, add "add csize to repo index" to the breaking 2.0 / doing things differently stuff?

**Comment by enkore** [comment]
> maybe it is fetch_missing_csize().

That's only possible if --no-cache-sync was used.

**Comment by ThomasWaldmann** [comment]
Yes, it was used, see top post.

**Comment by ThomasWaldmann** [comment]
i removed csize everywhere in borg2 branch, check how this behaves now.

**Comment by ThomasWaldmann** [comment]
does not happen any more in borg2 branch.
