### ISSUE TITLE
lock.roster left behind after umount in 1.1.0 rc1

### ISSUE THREAD

**Issue by cwygerde** [borgbackup/borg#2923]
I have been testing v1.1.0 rc1 and found the following issue:
Before doing a backup I check if a backup is neccessary by mounting the repo and comparing the latest archive with the source.
Then the repo is unmounted.
At the beginning of the next backup I get a message that lock.roster files are removed for PID ...
A workaround is doing a borg break-lock after each borg umount.

**Comment by ThomasWaldmann** [comment]
```
$ borg -V
borg 1.1.0rc1
$ borg mount repo mnt
$ ls mnt
1  2  new  testing
$ borg umount mnt
$ ls -l repo
total 668
-rw------- 1 tw tw    209 Jul 21 22:57 config
drwx------ 3 tw tw   4096 Jul 21 22:57 data
-rw------- 1 tw tw     64 Aug  6 02:09 hints.17
-rw------- 1 tw tw 656458 Aug  6 02:09 index.17
-rw------- 1 tw tw    190 Aug  6 02:09 integrity.17
-rw------- 1 tw tw     46 Aug  6 23:59 lock.roster
-rw------- 1 tw tw     73 Jul 21 22:57 README
$ borg create repo::checkingthelock .
Removed stale shared roster lock for pid 7081.
Removed stale shared roster lock for pid 7081.
```

**Comment by ThomasWaldmann** [comment]
does not happen when `borg mount -f` is used.

**Comment by ThomasWaldmann** [comment]
Hmm, the stale detection is malfunctioning if borg mount forks into the background:
```
$ borg mount repo mnt
$ borg create repo::checkingthelock7 .
Removed stale shared roster lock for pid 8289.
Removed stale shared roster lock for pid 8289.
```
Here it is killing the lock although the borg mount is still alive (just not having pid 8289 any more, but the forked process' pid).

**Comment by ThomasWaldmann** [comment]
from platform/posix.py:
```
def get_process_id():
    """
    Return identification tuple (hostname, pid, thread_id) for 'us'. If this is a FUSE process, then the PID will be
    that of the parent, not the forked FUSE child.
```
Well, that can't work with the stale detection...

**Comment by ThomasWaldmann** [comment]
@cwygerde thanks for finding this.

this was undiscovered for long as it only affected borg mount (no other command forks into the background).
also, it only happens when the stale lock killer is active (which is the default since a while in 1.1).

a fix is in PR #2924.

**Comment by enkore** [comment]
I think you are fixing another (more critical) bug in #2924.

This ticket initially describes 1.1 leaving lock.roster behind after umount, 1.0 does not do this.

**Comment by ThomasWaldmann** [comment]
It has both the same root cause, that the PID in the lock was not the alive process, but the dead grandparent's PID. The code worked ok even with that, except when stale lock detection was active.

**Comment by ThomasWaldmann** [comment]
running the code from #2924:

```
$ borg -V
borg 1.2.0.dev35+gfe7c101
$ borg mount repo mnt
$ ls mnt
1  checkingthelock    checkingthelock11  checkingthelock13  checkingthelock3  checkingthelock5  checkingthelock7  new
2  checkingthelock10  checkingthelock12  checkingthelock2   checkingthelock4  checkingthelock6  checkingthelock8  testing
$ borg umount mnt
$ ls -l repo
total 664
-rw------- 1 tw tw    209 Jul 21 22:57 config
drwx------ 3 tw tw   4096 Jul 21 22:57 data
-rw------- 1 tw tw     66 Aug  7 05:01 hints.65
-rw------- 1 tw tw 656458 Aug  7 05:01 index.65
-rw------- 1 tw tw    190 Aug  7 05:01 integrity.65
-rw------- 1 tw tw     73 Jul 21 22:57 README
$ borg create repo::checkingthelock15 scripts/
```

```
$ borg mount repo mnt
$ borg create repo::checkingthelock16 scripts/
Failed to create/acquire the lock /home/tw/w/borg/repo/lock (timeout).
```
