### ISSUE TITLE
Provide a way to completely delete data from the repository

### ISSUE THREAD

**Issue by realityexists** [borgbackup/borg#2929]
Sometimes data needs to be securely deleted. If it was backed up with borg there needs to be a way to also delete it from any backups. This data may be an entire file (e.g. a private key file) or a small part of a large file (e.g. a password inadvertently included in source code and later edited out).

Currently, the user can run "borg delete" or "borg delete" to delete any archives containing the deleted data. The data is then logically deleted (it would not be restored by any borg restore commands), but it is unclear whether it still exists in any borg segment files. (Apparently borg 1.1 introduces an optimisation where small changes don't cause segments to be rewritten, for example.)

Please provide and document a way to ensure that deleted data is truly gone from the repository. This may be a new "garbage collection" command that forces all segments containing deleted data to be rewritten or some combination of existing commands/options.

**Comment by ThomasWaldmann** [comment]
See also: #2195 

Having some params for the compaction command is easier for ad-hoc usage than e.g. editing of parameters in the repo config and then having to artificially trigger some write op just to have it call compact_segments() also.

**Comment by enkore** [comment]
Secure deletion often doesn't really work [1]. This is aggravated by Borg's deduplicating nature, since you have to delete all archives that reference the data in question before it is deleted. This may be non-trivial in itself (and Borg has no real reverse mapping to help you with this) [2]. Only when the data is logically deleted, secure physical deletion becomes relevant.

[1] Encrypting data and throwing the key away to dispose of it is much simpler and more secure.
[2] A Borg Expert's way to do this is to hack `borg debug dump-archive` to dump chunk IDs (reasonable to merge into master) and then delete those chunks manually, running `check --repair` afterwards to mask the errors.

**Comment by realityexists** [comment]
Absolutely, these are important points that should be documented, but I don't think they're reasons to not implement this.

Of course, the data should only be deleted when there are no archives left containing this data. That should be fairly obvious to the user (though still worth documenting). It's not always hard to know which archives contain it - maybe I know I just added it yesterday, so only the last daily archive needs to be deleted? Worst case scenario: assume it's in all archives until now, create one new archive without the data and delete all previous archives. This is still much easier and faster than deleting and re-creating the whole repository.

Secure deletion is a much harder problem. Maybe borg _could_ make an attempt to shred files, but that would be a separate feature. This issue leaves that problem up to the user - it's up to them to fill free space on an HDD, enable TRIM on an SSD, move the repository to a different drive and wipe the old one or whatever. This may be non-trivial to do, but not impractical.  (You also have to store your borg repo on the right type of filesystem, but that's a one-off thing.) This issue is about borg not retaining copies of deleted data, because having to re-create the whole repo every time you want some data completely deleted _is_ impractical.

**Comment by enkore** [comment]
We actually agree, I think. Thomas and I are just saying that there really isn't much to implement besides #2195 and docs (=this ticket).

**Comment by realityexists** [comment]
Yes, I guess this is just #2195 + docs + ensure there are no other ways borg retains data the user deleted, either now or in feature implemented later.

**Comment by ThomasWaldmann** [comment]
Just as a side note: if encryption is used, you can't see the data in the repo by looking at the repo files. you can't get a deleted chunk via borg commands either. so the only way would be to have the key and use borg code to access even deleted chunks by iterating over the segments and decrypt the data received.

**Comment by OliverEvans96** [comment]
Seeing as #2195 is closed, I suppose the docs are the only thing keeping this issue open?

**Comment by ThomasWaldmann** [comment]
@OliverEvans96 master branch has a separate `borg compact` command, but is has no parameters to enforce a "compact everything no matter how small the hole" behaviour yet.

**Comment by fantasya-pbem** [comment]
I made some changes to FAQ documenting two ways for wiping files off a repo.

**Comment by realityexists** [comment]
Ah, so `borg_compact --threshold 0` is the key to getting data definitely deleted from the repo?

**Comment by fantasya-pbem** [comment]
Yes. Very roughly spoken it detects "unused" data chunks and removes them from the repository.
