### ISSUE TITLE
"patterns" missing from documentation

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#293]
the `patterns` help topic is missing from the online documentation... it's not generated by `setup.py` either, so a little trickier than #279.

**Comment by anarcat** [comment]
i wonder how much work we should put in that issue considering we are likely to rewire the whole dispatching and argument parsing system with click in #251...

**Comment by anarcat** [comment]
or maybe the other way around? should the help system display the RST files instead of having the source in the code, maybe in a plain file?

it's easier to extract stuff from the rst file than deep into python docstrings or arbitrary argparse recursive data structures...

**Comment by ThomasWaldmann** [comment]
it's already fixed, see my PR #297.
