### ISSUE TITLE
Provide a way to access the "latest" snapshot

### ISSUE THREAD

**Issue by essembeh** [borgbackup/borg#2933]
I couldn't find an elegant way to easily access the latest snapshot in my repository, I have to pipe commands like borg list | tail -1 ... 
Maybe a variable {latest} could be useful for *list*, *extract*,  for this use case, like {now} is useful to create snapshots?
Is there a better solution?

Thanks

**Comment by ThomasWaldmann** [comment]
borg 1.1 will have `borg list --last 1`.

**Comment by essembeh** [comment]
Ok, it will be easier to get the last snapshot name with `--last 1` but *{latest}* would be more versatile?
For example:
`borg mount /path/to/borg::{latest} /mnt`
`borg extract /path/to/borg::{latest} /tmp`
`borg list /path/to/borg::{latest} | grep "MOTIF"`

Maybe *--last 1* will be available for extract/mount commands also? 

Thanks

**Comment by ThomasWaldmann** [comment]
If you backup multiple machines or user and system data separately into same repo, there is not a single latest archive.

That's why we have chosen, --first n, --last n, --sort s and --prefix p -- to address more use cases.

**Comment by essembeh** [comment]
In case of multiple machines & system, *{latest}* makes less sense, but there is always a latest based on the create date? I don't think 2 snapshots can have the same creation date due to lock mechanism. 

Will "--last 1" be available for mount for example?
`borg mount /path/to/borg --last 1 /mnt`
IMO it make less sense than {latest} for mount/extract but it could do the job (retrieve easily the last snapshot).

**Comment by ThomasWaldmann** [comment]
```
$ borg -V
borg 1.1.0rc2.dev33+g2e48110
$ borg init -e none repo
$ borg create repo::1 scripts/
$ borg mount --last 1 repo mnt
$ ls mnt
1
$ borg umount mnt
$ borg create repo::2 scripts/
$ borg mount --last 1 repo mnt
$ ls mnt
2
```

**Comment by enkore** [comment]
> Will "--last 1" be available for mount for example?

The 1.1 series docs are available at https://borgbackup.readthedocs.io/en/1.1-maint/usage/general.html (see https://www.borgbackup.org/releases/ for an overview).

**Comment by essembeh** [comment]
Thanks for the details 👍 
I just discovered I can mount a whole repository and all tags are available in subfolders of the mountpoint, this will do the job for my backup scripts ;)
