### ISSUE TITLE
Specifying a global config file

### ISSUE THREAD

**Issue by rbrito** [borgbackup/borg#2935]
Hi.

This is more a question that anything else (but if it is not implemented yet, perhaps this is a feature request).

Given the current stat of `obnam`, which is what I used to use, I'm strongly considering using `borg`, but from some quick tests and RTFM, I see no way to specify a global configuration file, say, a `~/borg.conf` or `~/.config/borg.conf` file (or the XDG standard location of files).

For instance, I would always like to specify the options to give me progress, being verbose, doing just a single-filesysem backup, choosing an appropriate compression etc. etc. to know the progress of my backups, so that making backups is so easy that I can install borg on my each of my parent's computers and tell them to just type: `borg create /` (to create a full system backup, especially with the repository being already implied).

Is this already implemented? It would rock a lot to have this. Of course, I can create scripts, but it would be nicer to have the software be as intelligent as possible.

BTW, I'm using Debian's packaged version 1.0.3 of borgbackup and I expect to migrate to borgbackup as soon as possible.

Thanks for all the efforts with this nice piece of software,

Rogério.

**Comment by ThomasWaldmann** [comment]
I think we already have a ticket about adding a config file, thus closing this as duplicate.

Backups are often automated, so one needs a script anyway and can just put options there as needed.
Also, if you frequently use it interactively, shell aliases are another option.

1.1 will have lz4 compression as new default, btw.

1.0.3 is a bit old btw, you should use a newer version.

https://packages.debian.org/search?keywords=borg&searchon=names&suite=all&section=all
