### ISSUE TITLE
integrate new screencasts into docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2936]
we have 3 new asciinema screencasts, but they need to get integrated into docs.

previously, the docs linked to just 1 screencast with installation and basic usage.

now we have 3 screencasts for install, basics, advanced.

maybe show the "basic" one and link to the other 2 below that?

**Comment by enkore** [comment]
I'd put all three on the [demo page](https://www.borgbackup.org/demo.html) and just one in the README.

**Comment by ThomasWaldmann** [comment]
@enkore yup!

**Comment by ThomasWaldmann** [comment]
https://asciinema.org/~borgbackup there it is!

**Comment by ThomasWaldmann** [comment]
BTW, uploading with ubuntu's asciinema 1.2.0 did not work (bad request), I used this:
```
curl -v -X POST -u borgbackup:secret-token https://asciinema.org/api/asciicasts -F asciicast=@install.json
```

**Comment by enkore** [comment]
If we want to keep the JSON files in this repo (see https://github.com/borgbackup/borgbackup.github.io/pull/15#issuecomment-322451943), then an exclude rule should probably be added to the MANIFEST to avoid including them in the source distribution.

**Comment by ThomasWaldmann** [comment]
Yes, I'ld like to keem them in git. Maybe not extremely useful right now, but at least we have a backup.

In next iteration, they hopefully get more editable again, so e.g. typos or other minor issues can be fixed via a PR.

**Comment by enkore** [comment]
I meant that keeping them in _one_ repo is sufficient.

**Comment by ThomasWaldmann** [comment]
Ah, yeah, we can keep them in the borgbackup.github.io repo.

But currently there is only 1 asciinema json file there.

**Comment by rugk** [comment]
I'd also say put the basic video in front (Readme or so) and only add links to the other ones, as they are mostly "tutorials".

Seeing https://asciinema.org/%7Eborgbackup I thought you do not want to host them on asciinema.org? But if you do, consider using the description texts I suggested. Better SEO, at least, you know… :smiley:
