### ISSUE TITLE
Backup script hangs without prompt

### ISSUE THREAD

**Issue by wimstefan** [borgbackup/borg#2947]
Version: borg 1.0.11 on Gentoo ~amd64

A backup script is running via cron and redirecting all output to a logfile. After switching harddisk, re-installing the OS and moving all relevant configuration files & user directories back on their place the backup script hangs on the first run after the switch after showing "Warning: Attempting to access a previously unknown unencrypted repository!".

The message  "Do you want to continue? [yN]" is not visible and I had to blindly type "y" on the command line from where I started the script. Only **after** that  the message showed up in the log and all continued normally.

 The backup directory is a separate disk which was not modified. The directory '~/.config/borg' was also copied to the new disk.

The content of the backup script:
```sh
#!/bin/sh
REPOSITORY=/backups/borg-mybackup/

borg create -v --stats                            \
  --exclude-caches                                \
  --compression lz4                               \
  $REPOSITORY::'{now:%Y-%m-%d}'                   \
  /home/                                   \
  /root                                           \
  /etc                                            \
  /var/git                                        \
  /var/www/localhost/htdocs/wordpress/wp-content  \
  /usr/local                                      \
  --exclude '/*/.cache'                           \
  --exclude '**/*/cache'                          \
  --exclude '*.pid'                               \
  --exclude '/*/.config/chromium'                 \
  --exclude '/*/.config/google-chrome*'           \
  --exclude '/*/.macromedia'                      \
  --exclude '/*/.mozilla'                         \
  --exclude '/*/.thunderbird'                     \
  --exclude '/*/.thumbnails'                      \
  --exclude '/*/xerrors.log'                      \
  --exclude '*.pyc'                               \
  >> /var/log/borg.log 2>&1

borg prune -v --list $REPOSITORY --keep-daily=7 --keep-weekly=4 --keep-monthly=6
```

**Comment by enkore** [comment]
Maybe there was line buffering enabled somewhere between Borg's output and you viewing the log, e.g. journalctl does this.

**Comment by ThomasWaldmann** [comment]
# about buffering

In borg 1.0.11, the prompt is output via `print(msg, file=sys.stderr, end='', flush=True)`.

stderr uses line buffering when connected to a tty and block buffering when connected to something else.

but that shouldn't matter, flush should bring it into the entity borg is connected to. if that entity is not a tty, but another piece of software, the effect could be explained by output buffering of that software maybe.

# redirection

in the script, stdout and stderr are both redirected to the same log file.
so, no message would ever show up in the terminal directly, but likely some other tool was used to view the log file and maybe the problem lies there if that tool does not output "incomplete" lines that do not end with a linefeed.

@wimstefan do you remember how you did it precisely?

**Comment by ThomasWaldmann** [comment]
No response, closing.

**Comment by wimstefan** [comment]
@ThomasWaldmann My apologies for the late reaction but real-life kept me quite busy the last days ...

As far as I remember I've run the script from a terminal prompt to test it. It might be very possible that I tried to monitor the logfile with multitail which might have caused the different buffering but I can't tell you for sure if that was the case. Not very helpful I know but at least a response to your efforts. Thanks a lot for that!

**Comment by ThomasWaldmann** [comment]
OK, thanks. We'll see if the issue pops up again...

**Comment by wimstefan** [comment]
And it's back again despite having "BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes" in the backup script. It happened running as a cronjob but also when I invoke the script from the terminal. In that case the script just hangs and even when I blindly enter "y" in the terminal there is no reaction. After interrupting the script with Ctrl-C the message `Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] Keyboard interrupt` appears in the logfile. 

The borg version is 1.1.0 btw.

**Comment by ThomasWaldmann** [comment]
you used this to have it in the environment?:

```
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes
```

**Comment by wimstefan** [comment]
Nope - I included it in the script as stated above ...

**Comment by ThomasWaldmann** [comment]
you must use export or it is not put into the environment and borg won't be able to see it.

**Comment by wimstefan** [comment]
Mamma mia! What was I thinking?!?! I'm so sorry to bother you with such a stupidity 😒 
```
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)
```
