### ISSUE TITLE
Social media?

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2948]
Ẁhat about creating, Twitter, GNUSocial/Mastodon or similar accounts?

(You can tag this with "community".)

**Comment by enkore** [comment]
https://twitter.com/@borgbackup

**Comment by rugk** [comment]
Ui, did not noticed it. Then maybe advertise that link on your website or (if that is possible) [GitHub organisation](https://github.com/borgbackup) or so. And as a FLOSS product, the idea to also be on GNUSocial/Mastodon is still there.

**Comment by ThomasWaldmann** [comment]
Well, personally I won't join social networks just to promote borg there.

But if I am using something anyway, it may happen that I operate a separate account for borg-news there.

I am not yet using GNUSocial/Mastodon and thay may or may not happen in the future.

I am fine with other regular contributors operating "borgbackup" accounts on other social networks. They just need to be prepared to get support or other questions (and also they likely should redistribute important announcements).

So, TODO for this ticket is imho to document our twitter account.

**Comment by ThomasWaldmann** [comment]
Note: the "how to release" docs in the development section mention my personal twitter account, that should be removed and replaced by @borgbackup at a better visible place.
