### ISSUE TITLE
Same files keep getting added during repeated "create" although they are unchanged

### ISSUE THREAD

**Issue by fuxoft** [borgbackup/borg#2956]
I am using Borg on Xubuntu Linux, the official repository version (1.0.7). When I run this command repeatedly:

`borg create -v --list --filter=AME /media/sklad/backup/frantisek_borg/dot_vst::{now} /home/fuxoft/.vst`

I always get a list of all files in one of the subdirectories (just ONE) of /home/fuxoft/.vst. The list looks like this (abbreviated):

```
A /home/fuxoft/.vst/LinuxStudio/comp_delay_mono.ttl
A /home/fuxoft/.vst/LinuxStudio/comp_delay_stereo.ttl
A /home/fuxoft/.vst/LinuxStudio/comp_delay_x2_stereo.ttl
A /home/fuxoft/.vst/LinuxStudio/compressor_lr.ttl
A /home/fuxoft/.vst/LinuxStudio/compressor_mono.ttl
```

However, these files definitely didn't change and are standard files with the same permissions as all other files in .vst/ directory. When listing the contents of any of the Borg archives, these files are listed as present.

Why are these files being always listed as added when they are already present in the archive?

**Comment by ThomasWaldmann** [comment]
borg always does full backups, they just (should) feel like incremental backups. So, of course you are seeing them in your archive if they are in the backup source file set.

There is a FAQ entry about files getting added unexpectedly, check if it applies to your case.

Also check file metadata like xattrs, ACLs, mtime.
What is your filesystem? Check inode numbers of these files, did they also not change?

**Comment by fuxoft** [comment]
The filesystem is ext4. These files definitely don't change in any way, it's an archive of audio plugins and I was doing the backup when there was no audio app running.

But you are right. I am experiencing exactly what's described in the FAQ. I solved it as described in the FAQ, by adding script that touches an empty file in this directory right before running borg.

**Comment by ThomasWaldmann** [comment]
In fact, you could touch the empty file whereever you want as long as it is in the input data set backed up by borg.
