### ISSUE TITLE
--timestamp time (vs list time)

### ISSUE THREAD

**Issue by taam** [borgbackup/borg#2957]
The time set with `--timestamp` is the end time, whereas `list` shows the start time, e.g.:

```
$ borg create --timestamp 2017-01-01T00:00:00 ::foo bar
$ borg list
foo                                  Sat, 2016-12-31 23:59:59
$ borg info ::foo
[...]
Time (start): Sat, 2016-12-31 23:59:59
Time (end):   Sun, 2017-01-01 00:00:00
Command line: borg create --timestamp 2017-01-01T00:00:00 ::foo bar
[...]
```

Having a start and end time is weird with only a single timestamp given. But if current design should not be changed and the start time is considered the important one, that's what `--timestamp` should set.

**Comment by ThomasWaldmann** [comment]
I'll have a look. Sounds like a bug, but I have to look at docs and past behaviour.

**Comment by ThomasWaldmann** [comment]
stable and also latest docs:
```
  --timestamp yyyy-mm-ddThh:mm:ss
                        manually specify the archive creation date/time (UTC).
                        alternatively, give a reference file/directory.
```
So, it is not specified there.

But somehow the end time does not make sense, also `borg list` gives the start time (and that's also what we have in the manifest), so guess it is a bug.
