### ISSUE TITLE
Support passing multiple archive names at once to delete

### ISSUE THREAD

**Issue by Oxreim** [borgbackup/borg#2958]
Being able to run a single command to specify a bunch of archives to clean up all at once. I know something similar can be done with the prune command however i feel that there is still value to be had if you could simply specify more then just the one archive for delete.

**Comment by ThomasWaldmann** [comment]
This can be easily done with shell scripting.

If we tried to extend borg's CLI for this, it would get a bit more ugly/complicated:
- usually we have either repo or repo::archive
- then we would need repo::archive1 archive2 ... (ugly: first arg needs also repo, but second does not)
- maybe even trouble with positional argument mapping (`archive other` is easy, `archive1 archive2 ... other1 other2 ...` is not)

**Comment by enkore** [comment]
> then we would need repo::archive1 archive2 ... (ugly: first arg needs also repo, but second does not)

This already exists (rename, diff). Note that delete also processes --first/--last/--glob-archives.

**Comment by RonnyPfannschmidt** [comment]
for multi argument while not use `borg delere repos archive1 archive 1...`

**Comment by ThomasWaldmann** [comment]
@enkore yes, I know, it is already a bit ugly there also.

@RonnyPfannschmidt we have a ticket about splitting complex repo::archive parsing into separate repo and archive, but if we remove the old way, that breaks cli compatibility.
