### ISSUE TITLE
Borg on Solaris 11 (sparc) ?

### ISSUE THREAD

**Issue by s200999900** [borgbackup/borg#2970]
Hi!

I plan to backup my prod solaris machines with borg.
Does borg can run on solaris 11 OS on sparc?
Thanks !

**Comment by enkore** [comment]
It works on Solaris 11 on x86,  but it's kinda annoying to compile due to Python bugs. It also generally works on Big Endian, so the combination might work out of the box.

The build steps are there: https://golem.enkore.de/job/borg-solaris/

The build script mentioned there but not visible to anons is this:

``` bash
export PATH=/opt/solarisstudio12.4/bin:$PATH

# work around https://bugs.python.org/issue1222585 by building wheels with CC instead of cc

# for python 3.4: this puts a correctly compiled wheel into the wheel cache
virtualenv -p python3.4 _venv34
. _venv34/bin/activate
pip3.4 install cython
export CC=$(which CC)
pip3.4 install msgpack-python
unset CC
rm -r _venv34

# create virtualenv
if [ ! -d _venv ]; then
virtualenv -p python3.5 _venv
fi
. _venv/bin/activate

pip install -U setuptools pip wheel cython

# for python3.5: cache correct wheel
export CC=$(which CC)
pip install -U msgpack-python
unset CC

# install deps
pip install -r requirements.d/development.txt detox
pip install -e .

# run tests
fakeroot -u detox -e py34,py35

borg debug info || true
```

YMMV.

**Comment by s200999900** [comment]
Thank you!

**Comment by ThomasWaldmann** [comment]
In 1.1-maint, there is also a openindiana VM (x64) entry in the Vagrantfile.

**Comment by ThomasWaldmann** [comment]
Closing this for now, reopen if you find issues.
