### ISSUE TITLE
netbsd: no readline

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2976]
Python build missing readline, likely:
```
    def import_paperkey(self, args):
        # imported here because it has global side effects
>       import readline
E       ImportError: No module named 'readline'

.tox/py34/lib/python3.4/site-packages/borg/crypto/keymanager.py:146: ImportError
```

**Comment by enkore** [comment]
If this can't be easily installed as an extra package (=> should be documented), then paperkey should be able to do without readline. I think it only uses the input()-side effect of RL, so no big deal.
