### ISSUE TITLE
with-lock crashes with 1.1.0-rc2

### ISSUE THREAD

**Issue by magma1447** [borgbackup/borg#2982]
I just upgraded from borgbackup-1.1.0-b3 to rc2, found an issue within minutes.

A simple example, borgbackup is version 1.1.0-rc2
> $ borgbackup --version
borgbackup 1.1.0rc2
> $ borgbackup with-lock mail-01.borg ls
[Files are listed here]
> Data integrity error: Segment entry data short read [segment 391, offset 1590]: expected 1890652, got 2497 bytes
> Traceback (most recent call last):
>   File "borg/archiver.py", line 3968, in main
>   File "borg/archiver.py", line 3896, in run
>   File "borg/archiver.py", line 148, in wrapper
>   File "borg/archiver.py", line 1677, in do_with_lock
>   File "borg/repository.py", line 411, in commit
>   File "borg/repository.py", line 685, in compact_segments
>   File "borg/repository.py", line 1292, in iter_objects
>   File "borg/repository.py", line 1373, in _read
> borg.helpers.IntegrityError: Data integrity error: Segment entry data short read [segment 391, offset 1590]: expected 1890652, got 2497 bytes
> 
> Platform: Linux thor 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 
> Linux: debian stretch/sid 
> Borg: 1.1.0rc2  Python: CPython 3.5.3
> PID: 31905  CWD: /data/borg-WedFriSun
> sys.argv: ['borgbackup', 'with-lock', 'mail-01.borg', 'ls']
> SSH_ORIGINAL_COMMAND: None
> 

With 1.1.0-b3 it works fine.

No errors when running check
> $ borgbackup check mail-01.borg
> Enter passphrase for key /data/borg-WedFriSun/mail-01.borg: 
>

**Comment by ThomasWaldmann** [comment]
hmm, does not always happen, with-lock worked fine for me here:
```
$ borg -V
borg 1.1.0rc2
$ borg with-lock repo ls -l repo
total 672
-rw------- 1 tw tw    209 Aug 14 17:34 config
drwx------ 3 tw tw   4096 Aug 14 17:34 data
-rw------- 1 tw tw     64 Aug 31 00:37 hints.43
-rw------- 1 tw tw 656458 Aug 31 00:37 index.43
-rw------- 1 tw tw    190 Aug 31 00:37 integrity.43
drwx------ 2 tw tw   4096 Aug 31 00:39 lock.exclusive
-rw------- 1 tw tw     50 Aug 31 00:39 lock.roster
-rw------- 1 tw tw     73 Aug 14 17:34 README
$ borg create repo::foo1 .
$ borg with-lock repo ls -l repo
total 672
-rw------- 1 tw tw    209 Aug 14 17:34 config
drwx------ 3 tw tw   4096 Aug 14 17:34 data
-rw------- 1 tw tw     66 Aug 31 00:40 hints.51
-rw------- 1 tw tw 656458 Aug 31 00:40 index.51
-rw------- 1 tw tw    190 Aug 31 00:40 integrity.51
drwx------ 2 tw tw   4096 Aug 31 00:40 lock.exclusive
-rw------- 1 tw tw     50 Aug 31 00:40 lock.roster
-rw------- 1 tw tw     73 Aug 14 17:34 README
```

**Comment by ThomasWaldmann** [comment]
btw, this is (again) a case where having a separate header (without data) crc would have been nice.

as we only have a crc for header+data, we need to rely on correctness of the length information from the header, then try to read that length and only when successfull, we can check the crc.

we already have a ticket for that.

**Comment by ThomasWaldmann** [comment]
I can't reproduce. @magma1447 does it still happen on your system?

**Comment by ThomasWaldmann** [comment]
If it still happens: reproduce the problem and give the current traceback.

Also give `ls repo_dir/index.*` (quick) or `borg check --debug --repository-only repo` (depends on repo size).

**Comment by magma1447** [comment]
@ThomasWaldmann I will leave tomorrow morning for Czech Republic, so if I am not responsive before next week, you know why.

I had issues with mail-01.borg yesterday, that seems to work fine now. I then tried all with a for loop over them. The first one failed.

Not sure if you wanted the ls with or without lock
`$ ls db-xbmc-01.borg/index.* -l
-rw------- 1 borg root 82138 Aug 31 10:33 db-xbmc-01.borg/index.633
`

`$ /usr/local/bin/borgbackup-1.1.0-rc2 with-lock db-xbmc-01.borg ls db-xbmc-01.borg/index.*
ls: cannot access 'db-xbmc-01.borg/index.631': No such file or directory
Data integrity error: Segment entry data short read [segment 634, offset 8]: expected 966583, got 4079 bytes
Traceback (most recent call last):
  File "borg/archiver.py", line 3968, in main
  File "borg/archiver.py", line 3896, in run
  File "borg/archiver.py", line 148, in wrapper
  File "borg/archiver.py", line 1677, in do_with_lock
  File "borg/repository.py", line 411, in commit
  File "borg/repository.py", line 685, in compact_segments
  File "borg/repository.py", line 1292, in iter_objects
  File "borg/repository.py", line 1373, in _read
borg.helpers.IntegrityError: Data integrity error: Segment entry data short read [segment 634, offset 8]: expected 966583, got 4079 bytes

Platform: Linux thor 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 
Linux: debian stretch/sid 
Borg: 1.1.0rc2  Python: CPython 3.5.3
PID: 5617  CWD: /data/borg-TueSat
sys.argv: ['/usr/local/bin/borgbackup-1.1.0-rc2', 'with-lock', 'db-xbmc-01.borg', 'ls', 'db-xbmc-01.borg/index.631']
SSH_ORIGINAL_COMMAND: None
`
Also ran the check, without with-lock
`$ /usr/local/bin/borgbackup-1.1.0-rc2 check --debug --repository-only db-xbmc-01.borg
using builtin fallback logging configuration
35 self tests completed in 0.09 seconds
Starting repository check
Verified integrity of /data/borg-TueSat/db-xbmc-01.borg/index.633
Verified integrity of /data/borg-TueSat/db-xbmc-01.borg/hints.633
Verified integrity of /data/borg-TueSat/db-xbmc-01.borg/index.635
Read committed index of transaction 635
Segment transaction is    635
Determined transaction is 635
Found 326 segments
Starting repository index check
Completed repository check, no problems found.
`

**Comment by ThomasWaldmann** [comment]
Interesting: check verifies integrity of `index.633` and `index.635`. bug? feature?

Guess that segment 635 will be a small commit-only segment, so segment 634 is the last "real" segment (with data). And it blew up in 634.

**Comment by ThomasWaldmann** [comment]
BTW, issue does not happen in b3 because there we still have `rollback()` at the end of `do_with_lock` - but we needed to change that to `commit()` for other reasons.

**Comment by ThomasWaldmann** [comment]
@magma1447 just to avoid chasing bugs already fixed, see #1867:

Does the repo in question get rsynced (or similar) using `borg with-lock` of borg < 1.1.0rc2?

If so, please upgrade borg everywhere and at least once use rsync in a way that makes sure files have at least same size in the end (so, *not* `--ignore-existing` in case you used that). Then try to reproduce the issue.

**Comment by magma1447** [comment]
@ThomasWaldmann It does get a regular borg with-lock rsync ... with the repo as a **source**. This is the original repo. So rsync in itself ain't writing to it, only borg with-lock. That lock has been with version < 1.1.0-rc2.

Is that what you asked for? And since it's my source, I assume your second paragraph isn't relevant? Or did I misunderstand?

**Comment by ThomasWaldmann** [comment]
oops, seems i got the bug number wrong in 9a362ae.

**Comment by ThomasWaldmann** [comment]
@magma1447 using this repo as a src (only) for rsync sounds unproblematic (IF the borg version is 1.1.0rc2).

Can you try the following?:
- create a new backup in the repo (using rc2)
- retry `borg with-lock ...` (using rc2)
(and stop using old borg with `with-lock`)

**Comment by magma1447** [comment]
@ThomasWaldmann My first initial test shows that it works. That's only 1 of 3*17 repositories tested though. I will upgrade to -rc2 again and test them all. It will take a a few days for all repositories to get new backups added to them.

**Comment by magma1447** [comment]
So yesterday I upgraded all servers to use borgbackup 1.1.0-rc2. 16/17 repositories for my Tue/Sat setup worked. The 17th of them had a similar problem to the above with-lock -issue. Spoke a bit about it with @ThomasWaldmann on IRC as well.

Today my servers started to write to my Wed/Fri/Sun repositories instead. 5/17 seems to have worked, the other 12 are getting similar errors. A seamless upgrade doesn't seem possible at the moment.

What does seem to help is to remove the index.* and then run a check --repair on the repositories.

**Comment by ThomasWaldmann** [comment]
@magma1447 i guess i have found a possible root cause of these issues, see #3002, but let's wait what @enkore says in his review.

this bug has maybe slept hidden for quite a while, but we recently added this "fail nicely with attic repos" harmless-looking change, which looks at the last uncommitted segment file (see also #2999) and by that created a cached FD to this file, which was short afterwards deleted in the repo cleanup process.

But the cached FD was still there and was used by the code, so it kind of shadowed whatever new file was created on disk.
