### ISSUE TITLE
compacting for little win

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2985]
while working on #2982, found this:
```
$ borg --debug-topic compact_segments with-lock repo ls repo
config  data  hints.36  index.36  integrity.36  lock.exclusive  lock.roster  README
compaction started.
not compacting segment 2 (only 564 bytes are sparse)
compacting segment 35 with usage count 4 and 634 freeable bytes
compacting segment 37 with usage count 1 and 41 freeable bytes
complete_xfer: wrote commit at segment 40
complete_xfer: deleting unused segment 35
complete_xfer: deleting unused segment 37
compaction completed.
```

Seem a bit too keen on compacting if the segment size is small.

The condition to skip compaction currently is:
```
segment_size > 0.2 * self.max_segment_size and freeable_space < 0.15 * segment_size
```
So, obviously, stuff in small segments always gets compacted, no matter how much we save by doing it.

Not sure, maybe this is ok, as we usually have big segments and only the final one is small (and commit-only segments).

**Comment by vphantom** [comment]
This is related to a request I found in https://mail.python.org/pipermail/borgbackup/2016q4/000501.html which mentions that line:

https://github.com/borgbackup/borg/blob/52be21c690e39cfa7c13596ae8542f6c45b212e1/src/borg/repository.py#L698

Allowing the user to set a threshold much higher than 15% could be very beneficial in some uses (i.e. to minimize S3 transactions when rcloning a Borg repo).

**Comment by ThomasWaldmann** [comment]
Note: i did substantial changes to compaction in master branch, compaction is now a separate command and does not automatically run with each repo-writing command.

Have to check again, whether it helps enough with this issue or more changes are needed.
