### ISSUE TITLE
1.1: recover_segments uses 500MB memory for new repos

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#2987]
Just noticed we still have this in repository.py in recover_segments:
```
# XXX: Rather use mmap, this loads the entire segment (up to 500 MB by default) into memory. 
```

As this is only used in an emergency, it would be unfortunate to run out of memory there and kill the recovery process of the segment file.

Some people run their repo server on a machine with not that much memory ("raspi") and in 1.0 this was only using ~5MB, so the trouble might come unexpected and at unfortunate time.

**Comment by enkore** [comment]
Fixed by #2988
