### ISSUE TITLE
Discussion General Code improvements

### ISSUE THREAD

**Issue by maltefiala** [borgbackup/borg#3]
I took the liberty to load attic and borg into codeclimate and suggest to start code improvement from there if we wished to: 

* https://codeclimate.com/github/jborg/attic/code
* https://codeclimate.com/github/borgbackup/borg

**Comment by ThomasWaldmann** [comment]
the following files should be excluded (if possible) - they are 3rd party code and/or generated code:
- versioneer.py
- attic/_version.py
- docs/conf.py

**Comment by ThomasWaldmann** [comment]
as a related thought:
while I am very much in favour of cleaning up code (see my first attic PRs), I currently have quite a lot of code (see "merge-all" branch) that is not yet merged into borg/master (or borg/anybranch).

if we do global cleanups now, this would create a hell lot of merge conflicts.

**Comment by maltefiala** [comment]
Fine by me, let's do them when you are ready

**Comment by maltefiala** [comment]
@ThomasWaldmann Please look at http://docs.codeclimate.com/article/166-excluding-files-folders for how to exclude files.

**Comment by ThomasWaldmann** [comment]
This is related to #4.

**Comment by anarcat** [comment]
should we simply close this in favor of #4 ?

**Comment by ThomasWaldmann** [comment]
yes, maybe move the codeclimate stuff there as a reminder to look closer at it.

**Comment by anarcat** [comment]
ack.
