### ISSUE TITLE
Support copying archives.

### ISSUE THREAD

**Issue by dseomn** [borgbackup/borg#3003]
Would it be possible to get a feature to copy an archive to another name in the same repository? That way I could regularly prune all archives with one prefix, but copy some archives to a different prefix if I don't want those specific archives to be pruned. (The `rename` command makes this possible too, but it has unwanted side effects in terms of which other archives are pruned.)

**Comment by ThomasWaldmann** [comment]
Guess we already have that in borg 1.1:

```
borg recreate repo::archive --target newarchive
```
