### ISSUE TITLE
No discussion of network connection behavior on internals page

### ISSUE THREAD

**Issue by rsyncnet** [borgbackup/borg#3015]
Thank you for all of the work you do on borg.

The question which I tried to research myself was:

"How many network (SSH) connections does borg create to do a routine, nightly backup".

Is it just a single connection that gets re-used for every single operation that borg does to perform a routine, nightly (incremental, I suppose) backup ?

Or does borg establish and tear down many SSH connections depending on how much data has to be transferred to complete the backup ?

I'm not asking about network *traffic*, which is briefly discussed on the usage.html page under the heading "Network (only for client/server operation)" ... rather, I am asking about network *connections* which I think would make sense to discuss on the "internals" page.

Thanks.

**Comment by ThomasWaldmann** [comment]
It establishes one ssh connection per borg command that operates on a ssh: repository.
So, your backup command (`borg create`) will establish one connection (and closes it when finishing).
If you have more commands, like `borg prune` or `borg check`, the will also establish 1 conn per cmd.

**Comment by rsyncnet** [comment]
OK, that is very helpful - thank you.

So no matter how big the repo is or how many files/segments, etc., it's just a single SSH connection.

Thanks.
