### ISSUE TITLE
I need help understanding max_segment_size ...

### ISSUE THREAD

**Issue by rsyncnet** [borgbackup/borg#3016]
I read #2310 with interest ... we are not using a lustre filesystem however our ZFS environment still benefits greatly by reducing the total number of files.

What confuses me is that there is a setting for max file size (segments) but no corresponding setting for minimum file size.

My own anecdotal findings (and what I read here) is that the segments tend to be about the size of the max_segment_size - which is great - but I don't expect that to be any kind of guarantee and I have no visibility as to how small they might end up being ...

Given a particular max_segment_size, how much smaller can segments be ?

Given a system tuning goal of minimizing the total number of files created, is there something more effective than simply cranking up max_segment_size to be 4294967295 ?

Finally, I was happy to read (again, in #2310) that max_segment_size can be changed in the config file "on the fly", which I assume means simply changing the setting in config ... I assume this means that all newly created segments will be larger[1] but how will existing segments grow over time ?

[1] But again, since it is named "max" (and not "average" or "default"), perhaps they wouldn't - that's confusing ...

**Comment by ThomasWaldmann** [comment]
it's the (rough) maximum size of the files in repo/data/<number>/*.

**Comment by enkore** [comment]
There is no minimum size for segments.

> Given a system tuning goal of minimizing the total number of files created, is there something more effective than simply cranking up max_segment_size to be 4294967295 ?

No... bit for portability it may be a good idea to use ~2 GiB (32 bit file / operating system).

> Finally, I was happy to read (again, in #2310) that max_segment_size can be changed in the config file "on the fly", which I assume means simply changing the setting in config ...

Yes

> I assume this means that all newly created segments will be larger[1] but how will existing segments grow over time ?

Existing segments are never modified, only deleted if their contents are "outdated" ([cf](http://borgbackup.readthedocs.io/en/latest/internals/data-structures.html#compaction))

**Comment by ThomasWaldmann** [comment]
@rsyncnet be a bit careful when tuning this, going to the extremes (big as well as small) can have a negative performance impact.

E.g. when borg decides to compact a segment, it will read the whole original, non-compact segment and write it to a new compact segment.

**Comment by rsyncnet** [comment]
Thank you - this is helpful.

What I continue to struggle with is, how closely does borg stay to the max_segment_size ?

Just because I set it to 10 or 20 or 100 MB doesn't mean it will actually follow that, does it ?

This is why the "max" signifier is confusing - "max" implies to me that the actual size could be anything, and simply will not exceed max_segment_size ... as if I were trying to keep segments small.

But in reality, tuning almost always involves trying to keep segments larger.

How confident can I be about getting segments that are close in size to max_segment_size ?

**Comment by ThomasWaldmann** [comment]
In borg 1.1, the maximum you will actually see is max_segment_size + MAX_OBJECT_SIZE.

MAX_OBJECT_SIZE is 20MiB.

This is because as long as the max_segment_size is not reached, borg will append a new object to the segment file. And that object can be MAX_OBJECT_SIZE big in the worst case (it often will be less than that as the default chunker params yield ~2MiB typically, but not everything is chunker output).

But you made me curious now: why do you need to know that precisely? The precise value usually should not matter much, rather the rough value (so e.g. if you use 5MiB like borg 1.0, or 500MiB like borg 1.1 - or some custom value in between).

**Comment by rsyncnet** [comment]
We don't need to know precisely at all - what we're trying to do is gauge how many tiny little files that borg can potentially make.

In practice, it appears that borg behaves quite well and does not create lots of <1MB files but I have no idea how reliable that is or if we can count on that.

If we're trying to optimize for fewer total files we would not look for a "max" setting - we would be looking for a "min" setting.  In practice, it appears that the "max" setting functions more like an "average" setting - segments all seem to be "about the size of the max".

In practice that is great and we will probably ask our customers to modestly increase max_segment_size ... perhaps to 20 MB ... but since the value is a *max* I have no assurance that someones workload will just create 10M 500 KB files one day ... which is what we want to avoid.

Millions of inodes gets to be expensive for us in terms of performance and management.  We want to continue to offer (deeply discounted) borg service, as we have been, but we want to lighten the load of all the little files ...

**Comment by ThomasWaldmann** [comment]
borg 1.1 will create some very small files when it does a commit (~17Bytes). This is intended and it is only about 2 of them per repo-writing operation, while the data will be in large segment files.

Smaller segment files will only appear if there is not enough data to let them grow to the max_segment_size, usually in the last data-carrying segment file a write operation creates.

So compared to just running rsync on all your data to do a backup, this is basically nothing concerning amount of files / inodes needed in the backup storage.

**Comment by rsyncnet** [comment]
"Smaller segment files will only appear if there is not enough data to let them grow to the max_segment_size, usually in the last data-carrying segment file a write operation creates."

That makes sense - and is what I would expect.

I think I have a good sense now - thank you.  The max_segment_size just happens to also be the typical segment size - not an outlier ...
