### ISSUE TITLE
Progress output generates extra lines with some filenames

### ISSUE THREAD

**Issue by dseomn** [borgbackup/borg#3027]
I'm running `borg create --no-files-cache --progress --numeric-owner` in an interactive terminal, and with most filenames, the command shows only one line of progress with some counters and the current filename. However, with some filenames, it seems to go on to the next line instead of overwriting the current line. Basically, in the screenshot below, I expect to see only the last line, not all the previous lines.

![image](https://user-images.githubusercontent.com/15314936/30412513-063b9a3e-98e6-11e7-85ff-efd61a011259.png)

**Comment by dseomn** [comment]
In case it helps, the filenames are utf-8, the non-ascii characters are `女子十二乐坊`, and here's some more information about my environment:

```
dseomn@solaria:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
dseomn@solaria:~$ echo $TERM
screen.xterm-256color
```

**Comment by ThomasWaldmann** [comment]
We have some code in borg that should deal with that.

So, what borg version, python version, operating system and version do you use?

**Comment by dseomn** [comment]
Here you go. Sorry I forgot to check if the bug is still present in the latest version.

```
dseomn@solaria:~$ /usr/bin/borg --version
borg 1.0.7
dseomn@solaria:~$ head -n 1 /usr/bin/borg
#!/usr/bin/python3
dseomn@solaria:~$ python3 --version
Python 3.5.2
dseomn@solaria:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by ThomasWaldmann** [comment]
1.0.7 is not quite the latest stuff, try the 1.0.11 and 1.1.0rc3 borg-linux64 binaries from there:

https://github.com/borgbackup/borg/releases

**Comment by dseomn** [comment]
I just tried with borg 1.0.11, python 3.5.3, FreeBSD 10.3, LC_ALL=en_US.UTF-8, and TERM=xterm-256color, and the issue was still there. For what it's worth, many other non-ascii characters seem to work fine. As far as I can tell, it's only CJK characters that are causing trouble.

**Comment by dseomn** [comment]
I think I found the cause. https://github.com/borgbackup/borg/blob/master/src/borg/helpers/progress.py uses `str.ljust`, which doesn't seem to take character width into account: https://www.recurse.com/blog/74-a-string-of-unexpected-lengths (scroll down to "The Unicode jungle"). I don't think I'm going to use `--progress` often enough for it to matter much to me, so feel free to close this bug if you don't think it's worth the effort to fix.

**Comment by enkore** [comment]
This is fixed in 1.1 with no backport.

**Comment by dseomn** [comment]
Thanks for the correction. That code looks like it uses `swidth` in https://github.com/borgbackup/borg/blob/master/src/borg/platform/base.py#L178, which doesn't seem to implement what the docstring says, and the docstring is also slightly wrong I think. (Some code points have 0 width.)

**Comment by enkore** [comment]
The posix platform modules delegates swidth to wcswidth(3).

**Comment by ThomasWaldmann** [comment]
I tried to reproduce:
- with cjk filenames and borg create --progress: worked for me
- ProgressIndicatorPercent did some incorrect space calculation
