### ISSUE TITLE
zero pad segment file names?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3028]
just came up on irc: why we don't zero-pad segment file names?

current:
```
1
10
11
2
3
...
```

could be:
```
00001
00002
00003
...
00010
00011
...
```
One issue with that is that the amount of padding somehow depends on segments_per_dir.

**Comment by ThomasWaldmann** [comment]
Another small issue is that if we start at 1 (not zero), we need 1 zero more for padding, if we use 10^n segments_per_dir.

**Comment by Artefact2** [comment]
> One issue with that is that the amount of padding somehow depends on segments_per_dir.

Yes, esp. considering the user can change it afterwards. Using a safe pad length (8?) could work, are people running repos with millions of segments per dir?

**Comment by enkore** [comment]
> why we don't zero-pad segment file names?

Because that breaks compatibility for no good reason.

Why weren't the padded initially? Arbitrary design decision and str(n) vs. str(n).rjust(X, '0')
