### ISSUE TITLE
Backup Remote Host -> Local Repo, Quicker and More Efficiently?

### ISSUE THREAD

**Issue by buckwangs** [borgbackup/borg#3029]
Hello,

Thank you for this ambitious backup solution. Currently, outgrowing rsync, Borg seems like a good idea but it's missed in the docs how to backup a remote server to a local repo, quickly and efficiently. An obvious solution would be to 
```
$ sshfs -p 22 root@server:/ /mntpoint
$ borg break-lock ".../borgrepo"
$ borg create --progress --stats ".../borgrepo::archiveName" "/mntpoint" --exclude "/mntpoint/dev/*" ...
```
But the resulting backup is exorbitantly slow. I must be doing something wrong and I do blame myself because only an hour in, Borg backed up just under 10GB. I love the idea of Borg but this feels like a kick in the nuts. Please advise if there is a quicker solution to this problem?

How can I backup a remote host to a local repo quicker than this?

**Comment by ThomasWaldmann** [comment]
borg directly only supports "push" mode, meaning that the borg client reads local files and pushes deduplicated, compressed, encrypted data to a repository (which can be a local directory, e.g. a mounted filesystem, or a borg repository server).

there is no direct support for "pull" mode yet, but we have a ticket about documenting workarounds already.

**Comment by ThomasWaldmann** [comment]
As a side note:

Doing a sshfs mount is not really pull mode. It is just backing up a locally mounted network filesystem.

Network filesystems usually do not have stable inode numbers, thus borg's file cache won't work with default parameters. To make it work by just ignoring inode numbers for file change detection you can use `borg create --ignore-inode ...`.

https://borgbackup.readthedocs.io/en/stable/usage.html?highlight=ignore%20inode#borg-create

**Comment by buckwangs** [comment]
Thank you @ThomasWaldmann 

The ```--ignore-inodes``` tip didn't improve much but thank you for mentioning it. I'll look over the ticket you've linked, thank you again for your time and Borg. It's all very appreciated :+1:

**Comment by ThomasWaldmann** [comment]
You won't see an effect of --ignore-inodes for your first backup, but for following backups.

**Comment by drebs** [comment]
Just for reference, `--ignore-inode` has been deprecated and `--files-cache` without `inode` should be used instead.
