### ISSUE TITLE
borg create doc: need example update

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#3034]
1. The example section of borg create in 1.1+ ( https://borgbackup.readthedocs.io/en/1.1.0rc3/usage/create.html ) shows:
```
# No compression (default)
$ borg create /path/to/repo::arch ~

# Super fast, low compression
$ borg create --compression lz4 /path/to/repo::arch ~
```
However elsewhere it says lz4 is now the default.

2. That same page should also reports about the auto compression specifier, which is documented here: https://borgbackup.readthedocs.io/en/1.1.0rc3/usage/help.html
3. It would be nice to explain when using a compression algorithm if the compressed size is the same or higher than the original, what is saved in the repo? The original or the compressed version? It would make sense to save the original, so to have a faster decompression when accessing the archive (also having a similar result to auto but with a better chance to compress, since lz4 currently used for the compression estimate may not be able to detect some partially compressed chunks, that may be compressed with a better algo, at the expense of some higher CPU load during create).

**Comment by ThomasWaldmann** [comment]
@FabioPedretti Thanks for finding this! Can you do a PR with a fix against master branch?

**Comment by ThomasWaldmann** [comment]
@FabioPedretti I fixed this with #3038.

**Comment by FabioPedretti** [comment]
Thanks for looking into it! But what about my point 2. and 3. (the latter being mainly a question)?

**Comment by ThomasWaldmann** [comment]
2. -> added example
3. -> --compression docs already point to `borg help compression` and it is explained there.

**Comment by FabioPedretti** [comment]
Thanks!
What I meant about 3. was:
1. I specify to use, e.g., zlib
2. a chunk compressed with zlib is the same size or bigger that the original chunk (likely because original chunk is already compressed or incompressible)
3. what is saved to the repo?
- the smaller (or same size), faster to access, original chunk
- or the bigger (or same size), slower to access (need to decompress it), zlib compressed chunk

**Comment by ThomasWaldmann** [comment]
@FabioPedretti for "auto" mode, the docs say it applies "none" compression method if the prediction says it is uncompressible. "none" compression means "store as is".

When not using "auto" mode or prediction says it is compressible, we compress with the specified compression.

IIRC we do not check again whether the result of that (more expensive) compression is actually smaller than the input. I can't estimate whether such a check would be worth it nor do I have data about that, this might be an interesting idea for a separate ticket, so we can close this one for the docs update.
