### ISSUE TITLE
borg serve: restrict to prefix

### ISSUE THREAD

**Issue by thewilli** [borgbackup/borg#3035]
I have several servers backing up to a single repository, in order to benefit from deduplication and an easier backup process. All archives are prefixed with the corresponding server name, so e.g. *serverA* names its archives like *serverA-mysql-{now}* or *serverA-someotherservice-{now}*.

Could you consider adding a `--restrict-to-prefix` option (similar to the existing`--restrict-to-path`) to `borg serve`, that limits all archive operations to those with a given prefix, so *serverA* would not be allowed to create, prune or mount archives from *serverB*?

**Comment by ThomasWaldmann** [comment]
I don't think that is possible. To enforce that, the server (borg serve) would have to do that.

But the server is only seeing encrypted data, so it does not know anything about archive names.

Also, there would be only 1 encryption/decryption key, so your misc. clients would have to trust each other also for that.
