### ISSUE TITLE
apply transactions within time range

### ISSUE THREAD

**Issue by thewilli** [borgbackup/borg#3036]
I'm using `borg serve` with the `--append-only` option set to have a server backup itself to a remote repository [without being able to tamper with the backup data](https://borgbackup.readthedocs.io/en/stable/faq.html#how-can-i-protect-against-a-hacked-backup-client).

That's fine, but prune operations with the append-only mode activated of course doesn't free space. That's why I'm struggling how to handle this properly. I could run a local borg command which applies all transactions, but I would then have to trust there are no bad transactions already in the repository.

One may be aware of an attack after some time has already passed. **That's why would like to have a borg command to "apply" all transactions within a certain period of time**, e.g. older than 30 days, where I am (quite) sure the backup client hasn't been corrupted in this time.

**Comment by ThomasWaldmann** [comment]
That's an interesting idea.

Maybe we could look into the transaction log to get the segment transaction id for some specific timestamp >= minimum time.

There's no code to do that (yet), though.
