### ISSUE TITLE
travis is stuck?

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#304]
it looks like travis has exploded since the cataclysmic merge i did last night... i may be unrelated, as *some* builds are working fine. indeed, it seems that linux builds are fine while osx builds are stuck, example:

https://travis-ci.org/borgbackup/borg/builds/85980086

this is to notify that the problem exists and discuss possible solutions.

**Comment by ThomasWaldmann** [comment]
```
14:49    #  Irssi: Join to #travis was synced in 1 secs
14:49  ThomasWaldmann$ moin! is there some issue on the osx workers?
14:49  ThomasWaldmann$ https://travis-ci.org/borgbackup/borg/builds/85970258
```

**Comment by anarcat** [comment]
definitely looks like a problem with OSX on travis' side:

    fatal: unable to access 'https://github.com/borgbackup/borg.git/': Could not resolve host: github.com

https://travis-ci.org/borgbackup/borg/jobs/85980090

not sure what we can do here... maybe talk with travis support?

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/borgbackup/borg/builds/86025422 seems to work again.
