### ISSUE TITLE
Backup / with exclude /var/cache/nginx with 10 millions files

### ISSUE THREAD

**Issue by covermind** [borgbackup/borg#3040]
Helllo I use Borg 1.0.11, try already with --no-cache-files, but borg is stalled without any error on 1-7 days in processes, I no wait more time.

For example, I have a server with 10 millions files in nginx cache, but i want exclude this cache.

I run: 

borg create --no-files-cache --debug --stats --list --exclude-if-present CACHEDIR.TAG --exclude-from /etc/borg/excludes.conf sbackup@$BSRV:/data/sbackup/system/$NSRV.techserver.pw::$NDATE /

or run:

borg create --debug --stats --list --exclude-if-present CACHEDIR.TAG --exclude-from /etc/borg/excludes.conf sbackup@$BSRV:/data/sbackup/system/$NSRV.techserver.pw::$NDATE /

Yes I use / and excludes.conf:

```
/boot
/dev
/mnt
/proc
/run
/sys
/tmp
/etc/fstab
/etc/mtab
/etc/mdadm
/etc/mdadm.conf
/etc/sysconfig
/etc/network
/etc/udev
/var/tmp/*
/var/log/*.log*
/var/log/*/*.log*
/var/log/*/*/*.log*
/var/log/*_log*
/var/log/*/*_log*
/var/log/*/*/*_log*
/var/lib/mysql/*
/var/lib/postgresql/*
/var/cache/nginx/*
```

Github replacing several * in paths. This is not mistake.

root@rel-eu:~# /root/borg/borg.sh
using builtin fallback logging configuration
SSH command line: ['ssh', '-i', '/root/borg/borg.remote', '-o', 'StrictHostKeyChecking=no', 'sbackup@back.server.lan', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration

And stalled on 1-7 days, i not wait more :). If I remove all million files in /var/cache/nginx/* backup task work properly.

I think borg look in this directory, even if have exclude /var/cache/nginx.
Can you test and fix this issue or add option not look before exclude?

Thank You.

**Comment by enkore** [comment]
Check with --list how far Borg looks into your directory trees.

**Comment by covermind** [comment]
borg create --no-files-cache --debug --stats --list --exclude-if-present CACHEDIR.TAG --exclude-from /etc/borg/excludes.conf sbackup@$BSRV:/data/sbackup/system/$NSRV.techserver.pw::$NDATE /

--list option have. Stalled on this:

SSH command line: ['ssh', '-i', '/root/borg/borg.remote', '-o', 'StrictHostKeyChecking=no', 'sbackup@back.server.lan', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration

And its all.

**Comment by covermind** [comment]
Strange... I re-create one more time repository and now working is ok.

**Comment by ThomasWaldmann** [comment]
@covermind do you always use same user when working with the repo? If you don't, there might be strange effects due to fs permission issues.

about using a fresh repository "fixing" your issue:
- so you did a first backup to that fresh repo and it worked normally.
- can you also please check if the 2nd backup also works normally?
if so, I think we can close this issue as it is not (as suspected) related to that excluded huge directory.

**Comment by covermind** [comment]
Hmm. Now what happened after I recreated repo:

d /var/www/html
d /var/www/pgadm
d /var/www
d /var
s /vmlinuz
s /vmlinuz.old
d /
------------------------------------------------------------------------------
Archive name: 2017-09-21-1506003426
Archive fingerprint: 90af07e9308cc0554d3ddec1e8bbccd048aecce7af292072fffe0923bf3c95fc
Time (start): Thu, 2017-09-21 17:17:08
Time (end):   Thu, 2017-09-21 17:45:51
Duration: 28 minutes 43.17 seconds
Number of files: 48969
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               29.53 GB             29.53 GB             29.18 GB
All archives:               29.53 GB             29.53 GB             29.18 GB

                       Unique chunks         Total chunks
Chunk index:                   53008                59562
------------------------------------------------------------------------------

And this is stalled now :((( . I make backup to new empty repo.

root@rel-eu:~# ps aux | grep borg

root       828  0.0  0.0  11184  2948 pts/0    S+   17:17   0:00 /bin/bash /root/borg/borg.sh
root       831  0.0  0.0  12460  5268 pts/0    S+   17:17   0:00 borg create --debug --stats --list --exclude-if-present CACHEDIR.TAG --exclude-from /etc/borg/excludes.conf sbackup@back.techserver.lan:/data/sbackup/system/rel-eu.techserver.lan::2017-09-21-1506003426 /
root       837 25.5  0.0 139212 30732 pts/0    S+   17:17  25:16 borg create --debug --stats --list --exclude-if-present CACHEDIR.TAG --exclude-from /etc/borg/excludes.conf sbackup@back.techserver.lan:/data/sbackup/system/rel-eu.techserver.lan::2017-09-21-1506003426 /
root       842  5.2  0.0  51128  8284 pts/0    S+   17:17   5:09 ssh -i /root/borg/borg.remote -o StrictHostKeyChecking=no sbackup@back.techserver.lan borg serve --umask=077 --debug
root      4580  0.0  0.0  12784   980 pts/1    S+   18:56   0:00 grep borg

root@rel-eu:~# strace -p 837
strace: Process 837 attached
wait4(842, ^Cstrace: Process 837 detached
 <detached ...>
root@rel-eu:~# strace -p 831
strace: Process 831 attached
wait4(-1, ^Cstrace: Process 831 detached
 <detached ...>
root@rel-eu:~#

**Comment by ThomasWaldmann** [comment]
can you at least add the borg command you ran?

also, the stats are at the end, so you say it is not terminating at the end?

**Comment by covermind** [comment]
Yes its not termintaing at end.

**Comment by ThomasWaldmann** [comment]
Any cpu, disk, memory activity?

**Comment by ThomasWaldmann** [comment]
It is there, after returning from create_inner:

https://github.com/borgbackup/borg/blob/1.0.11/borg/archiver.py#L331

So, all left to do is leaving the Cache context manager (which just releases the cache lock) and exiting.

**Comment by ThomasWaldmann** [comment]
hmm, why do we see 2 borg client processes in the ps output?

**Comment by covermind** [comment]
Every time when I run "borg create" in ps output have two processess + ssh.
Disk/Cpu idle when its stalled. But why can not release lock? On backup server no have anything processes working parallel with destination repo.

**Comment by ThomasWaldmann** [comment]
The cache lock is on the client side, usually in ~/.cache/borg/<repoid>/...

**Comment by covermind** [comment]
I delete cache files, same problem, stalled.

**Comment by covermind** [comment]
with --no-files-cache ,  same issue - stalled.

**Comment by enkore** [comment]
If it always stalls on the wait4(2) for the SSH client, then it might be a network/connection issue keeping the SSH client from exiting when Borg expects it to. What happens if you kill the SSH client process in this case?

**Comment by covermind** [comment]
Ok I move openssh server on backup server to 23 tcp port - same issue not working. Stalled.
Next I Install dropbear ssh server and bind it to 23 tcp port - Working!!!
How?

But I do not understand WTF. Only one server with borg backup have this trouble. Other servers backups work OK.

Backup tasks working over internet not inside LAN network.

**Comment by ThomasWaldmann** [comment]
This somehow sounds like a network issue (see previous post), so I am closing this for now.

Feel free to reopen if there is specific information pointing into borg direction.
