### ISSUE TITLE
compression: store original chunk when the compressed one would have same or bigger size

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#3046]
As discussed in #3034 it would be nice to consider storing in the repo the original (uncompressed) chunk when the compressed one would have same or bigger size than the original. This may happen if the input is already compressed.
The main benefit is faster access (no need to decompress).
(Another possible improvement could consider storing the original when the compressed one is smaller less than X% with X eventually configurable)

This is orthogonal to the "auto" compression specifier.

**Comment by ThomasWaldmann** [comment]
Note: I am working on a slightly different issue:

The non-auto modes always worked unconditionally, so if you say lzma, you always get that.
Maybe we just want to keep it that way.

But for the auto-mode, there was one check missing: that the expensively compressed data is actually smaller than the lz4_data we already have computed.

**Comment by ThomasWaldmann** [comment]
See #3085.

**Comment by ThomasWaldmann** [comment]
Fixed.

**Comment by FabioPedretti** [comment]
May I ask what could be the issues with the original proposal? I can see it may be confusing if some chunks ends up uncompressed even if a compressor was specified. But from what I can see there is no way to query how chunks are compressed in a repo. And documenting this will make things clear anyway.

That would speed up accessing the files, given the default now is lz4 and many already compressed files likely will end up with a bigger size.

Not a huge deal anyway.

**Comment by ThomasWaldmann** [comment]
@FabioPedretti there is no technical problem, it is just about simplicity, like:

- do no magic if something specific was requested
- do magic, if magic was requested ("auto" mode)

**Comment by ThomasWaldmann** [comment]
I'll check lz4 how bad the "problem" is.

**Comment by ThomasWaldmann** [comment]
Put some compressed data into compr/ (jpegs, mp3s, tar.gz), ran borg with lz4 and without compression, looks quite ok:
```
$ borg init -e none lz4repo 
$ borg create -C lz4 --stats --progress lz4repo::test compr/
------------------------------------------------------------------------------                                                           
Archive name: test
Archive fingerprint: 8aed5e70779bba657dfd3910bdaa69d7bd82056ff9ba1b19a11502079f3a1e97
Time (start): Sat, 2017-10-07 18:09:42
Time (end):   Sat, 2017-10-07 18:10:03
Duration: 21.05 seconds
Number of files: 105
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              949.20 MB            926.52 MB            926.52 MB
All archives:              949.20 MB            926.52 MB            926.52 MB

                       Unique chunks         Total chunks
Chunk index:                     441                  441
------------------------------------------------------------------------------

$ borg init -e none nonerepo 
$ borg create -C none --stats --progress nonerepo::test compr/
------------------------------------------------------------------------------                                                           
Archive name: test
Archive fingerprint: 62848b9219ffb072c4baa6791b41533f51649f89de2165772060162fdf204e63
Time (start): Sat, 2017-10-07 18:10:55
Time (end):   Sat, 2017-10-07 18:11:17
Duration: 21.16 seconds
Number of files: 105
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              949.20 MB            949.20 MB            949.20 MB
All archives:              949.20 MB            949.20 MB            949.20 MB

                       Unique chunks         Total chunks
Chunk index:                     441                  441
------------------------------------------------------------------------------

$ du -sh lz4repo nonerepo
884M    lz4repo
906M    nonerepo
```

**Comment by FabioPedretti** [comment]
It mostly depends on the type of data. Jpeg and MP3 are not very well compressed (the lossless part) to be very fast to decode. I tried with a single random file:
dd if=/dev/urandom of=random bs=1M count=1000

and I get this:
#  du -hs *repo
1005M   lz4repo
1001M   nonerepo

Also tried with some gz and xz files (this is my use case, big log files already compressed) and with lz4 they uses a bit more space. And it get likely worse in my use case when I need to access xz log files with borg mount, created with zlib, it is very slow to access.

P.S.: for some reason only when I run the create with none compression (in the same test you did) I get this message:
Warning: Attempting to access a previously unknown unencryp
ed repository!
No message for the create with lz4.

**Comment by generalmanager** [comment]
@ThomasWaldmann I understand that you prefer not to do something different than expected. But several other implementations do automatically skip files if the first X bytes are incompressible, like zfs for example. So I personally expected it to behave that way.

Would you agree to add something like "--autoskip-compression"? This would be very useful for whole system archives which include an encrypted /home or lots of incompressible media files. Otherwise you should probably update the docs and examples to use two seperate borg calls for compressible + incompressible files.
