### ISSUE TITLE
borg always doing full backup even nothing changes.

### ISSUE THREAD

**Issue by azzamsa** [borgbackup/borg#3048]
borgbackup still doing a full backup and double the repo size even nothing changes in source directory.

I have source directory "a" which contains:
```
$ du -ah a
1.2M    a/test-A-20
420K    a/test-A-1
244K    a/test-A-7
544K    a/test-A-8
216K    a/test-A-12
208K    a/test-A-5
256K    a/test-A-17
264K    a/test-A-18
228K    a/test-A-11
284K    a/test-A-10
264K    a/test-A-3
208K    a/test-A-13
204K    a/test-A-19
256K    a/test-A-16
564K    a/test-A-2
248K    a/test-A-6
204K    a/test-A-9
280K    a/test-A-15
288K    a/test-A-4
228K    a/test-A-14
6.5M    a
```

so I do the **first** backup
`$ borg create -v --stats --progress --compression lzma,9  repotext::backup1 a/`

and the result is:

```
$ borg info repotext::backup1
Name: backup1
Fingerprint: 58a706313a7ac390cb1488285ce886bd67d9013ac6eae0b224a762aa7a0ef003
Hostname: <myhostname>
Username: <myusername>
Time (start): Sat, 2017-09-23 15:08:41
Time (end):   Sat, 2017-09-23 15:08:43
Command line: /usr/bin/borg create --stats --progress --compression lzma,9 repotext::backup1 a/
Number of files: 20

                       Original size      Compressed size    Deduplicated size
This archive:                6.75 MB            669.54 kB            669.54 kB
All archives:                6.75 MB            669.54 kB            669.54 kB

                       Unique chunks         Total chunks
Chunk index:                      22                   22

```

I was very happy, becuse it has good compression

```
$ du -sh a
6.5M    a

$ du -sh repotext/
724K    repotext/
```
**but**, after two minutes, I try to see what happened if I do more backup for *unchanged and unmodified* files
and the result is:

```
$ borg info repotext::backup2
Name: backup2
Fingerprint: bddbdb3d5bf94d1830bebc5ab03bda313b6b9bccf1234365336cb344e939197d
Hostname: <myhostname>
Username: <myusername>
Time (start): Sat, 2017-09-23 15:27:02
Time (end):   Sat, 2017-09-23 15:27:02
Command line: /usr/bin/borg create --stats --progress --compression lzma,9 repotext::backup2 a/
Number of files: 20

                       Original size      Compressed size    Deduplicated size
This archive:                6.75 MB            669.54 kB                455 B
All archives:               13.51 MB              1.34 MB            670.00 kB

                       Unique chunks         Total chunks
Chunk index:                      23                   44
```

why the size of all archive become doubled, even nothing changes in source directory

```
This archive:                6.75 MB            669.54 kB                455 B
All archives:               13.51 MB              1.34 MB            670.00 kB
````

I do the *third* backup to see what happened, and it is same, the size of the repo become more than 20 mb.

---

why does borgbackup still doing full backup even there is nothing changes ?
if it is natural way of borg, so we have to do `prune` every time we don't need old backup ?

because it stated in [quickstart](https://borgbackup.readthedocs.io/en/stable/quickstart.html) 
>This backup will be a lot quicker and a lot smaller since only new never before seen data is stored.

is this about [It always chunks all my files, even unchanged ones!](https://borgbackup.readthedocs.io/en/stable/faq.html#it-always-chunks-all-my-files-even-unchanged-ones). But I don't do any other backup, I just do my second backup and third backup experiment just a coupe of minutes after the first backup.

```
$ borg --version
borg 1.0.9

Debian GNU/Linux 9.1 (stretch) x86_64
```
---

thank you so much for you contribution to community.
thank you.

**Comment by ThomasWaldmann** [comment]
you need to look at the deduplicated size column.

also, why do you think it always chunks all your files? the 2nd backup did not even take 1s.

**Comment by azzamsa** [comment]
@ThomasWaldmann Thank you so much for you advice. now I am have some understanding how borgbackup works. Because I really need an backup tool for my machine.

I create much experiment with borg to make me understand, what is data deduplication means, and How borg works.

this my [fist experiment with borg](https://gist.github.com/azzamsa/edfc7099ac8992ce50f208cb277b7052)

is it true if i say "that the deduplicated size is the "real" size that saved in backup directory."

and this is my [additional experiment](https://gist.github.com/azzamsa/402af1c21a4d06bf704787a5c4a72c5e).

I am sorry, it is OOT, but do you have any suggestion for doing backup with images and videos ?
[experiment with images](https://gist.github.com/azzamsa/402af1c21a4d06bf704787a5c4a72c5e#experiment-with-images). 

I can't compress the images and videos as like the text files.

---

thank you so much, thank you.

**Comment by ThomasWaldmann** [comment]
Yes, that is true (at least for that time when borg create outputs the stats).

You can't compress some media files as they are already compressed.

For local backups (fast connection to repo, lots of space available) use lz4 compression.

**Comment by azzamsa** [comment]
@ThomasWaldmann , sorry I want to ask again.
I just want to make sure that I am doing the right way to backup and using borg efficiently.

I do an experiment  [comparison of different compression when working with text](https://gist.github.com/azzamsa/402af1c21a4d06bf704787a5c4a72c5e#comparison-of-different-compression-when-working-with-text), and the best compressed size is when using lzma,6

I do a backup on local machine, but I want high compression, I want to save hdd space on my backup destination, is this good for using lzma,6 ?

why do you suggest using lz4? 

Thank you so much.

**Comment by ThomasWaldmann** [comment]
lzma uses quite a lot of cpu and (for local, fast repos) likely will reduce your backup speed (if your backup contains a significant amount of changes, not for no-change / little-change backups).

lz4 has very light cpu usage and won't reduce your backup speed.

If you are desperate with repo storage space and your data is compressible, use zlib or lzma.

Always keep some free space on your repo filesystem, see the docs.

**Comment by azzamsa** [comment]
Thank you so much Sir. 
you are very kind.

thank you so much. thank you for your contribution to community.
thanks a lot.

have a great day, Sir ThomasWaldmann.
