### ISSUE TITLE
Zenity does not work with BORG_PASSCOMMAND

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#3050]
### STR
1. Make sure `zenity --password` works, when you enter it into the CLI.
2. `export BORG_PASSCOMMAND='zenity --password'`
3. Run `borg create`

### What happens
``` 
zenity: /tmp/_MEIomrn2c/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib64/libpng16.so.16)
passcommand supplied in BORG_PASSCOMMAND failed: Command '['zenity', '--password']' returned non-zero exit status 1
```

### What should happen
The same as when I run the command manually.

I assume the tempdir `/tmp/_MEIomrn2c/` is created by borg.

### Workaround

```
export BORG_PASSPHRASE="$( zenity --password )"
```

### More info

using same user (no sudo, nothing else)
borg 1.1.0rc3
Fedora 26

**Comment by ThomasWaldmann** [comment]
That's an issue specific to the pyinstaller-made borg single-file binary.

We already had that when executing the ssh binary and it can be fixed in the same way (see ssh related code).
