### ISSUE TITLE
Slow incremental backups with no changes

### ISSUE THREAD

**Issue by martinjo** [borgbackup/borg#3067]
I'm backing up my photos to a remote repo. The total size is about 750GB, which deduped ended up being just under 500GB 👍. The initial backup completed in about 17h which seems fast to me.

My incremental backups when no files (or very few) have changed takes 6 hours. This seems slow to me. Is that speed normal? 

When running with verbosity set, I see that Borg spits out an 'A' in front of all of my files. I guess 
that means Added? 

Example:
A /mnt/user/Photos2/2010/2010-02-21 YongSheng (Neverland)/RAW/IMG_8907.CR2
A /mnt/user/Photos2/2010/2010-02-21 YongSheng (Neverland)/RAW/IMG_8908.CR2
A /mnt/user/Photos2/2010/2010-02-21 YongSheng (Neverland)/RAW/IMG_8909.CR2

In the end the actual data transferred to my repo is almost negligible, so somewhere along the way the files must be marked as unchanged. But is it really supposed to take so long time?

My backup is run from an unRAID server running on a 4 core Celeron CPU. CPU load averages about 30% and memory usage around 20%.

Any suggestions on how to speed things up?

**Comment by ThomasWaldmann** [comment]
> I'm backing up my photos to a remote repo. The total size is about
> 750GB, which deduped ended up being just under 500GB 👍. The initial
> backup completed in about 17h which seems fast to me.
> 
> My incremental backups when no files (or very few) have changed takes 6
> hours. This seems slow to me. Is that speed normal?
No.

> When running with verbosity set, I see that Borg spits out an 'A' in
> front of all of my files. I guess
> that means Added?
> 
> Example:
> A /mnt/user/Photos2/2010/2010-02-21 YongSheng (Neverland)/RAW/IMG_8907.CR2
> A /mnt/user/Photos2/2010/2010-02-21 YongSheng (Neverland)/RAW/IMG_8908.CR2
> A /mnt/user/Photos2/2010/2010-02-21 YongSheng (Neverland)/RAW/IMG_8909.CR2


Yes, "A" means that borg thinks it is a added or changed file. borg will read, chunk, deduplicate then, which is not super fast.

Usually it should show "U" (unchanged) for most of your files and it would be super fast then.

Check whether mtime, size, inode number are stable for your files - that is essential for the "files cache" being able to work.

If inode is not, consider --ignore-inode option, see docs / FAQ.

**Comment by enkore** [comment]
This can be caused by those files sharing the same time stamp and having the newest time stamp in the data set.

http://borgbackup.readthedocs.io/en/stable/faq.html#i-am-seeing-a-added-status-for-a-unchanged-file

**Comment by martinjo** [comment]
When I add the --ignore-inode option the whole process completes in a couple of minutes instead of hours. 

What complications could the --ignore-inode argument have? Should I just add it and be happy?

**Comment by ThomasWaldmann** [comment]
If a file has changed, but mtime is still as before the change, the size is the same and it can't detect the change via inode number change, it might think the file is not changed and will not back up the changes.

https://github.com/borgbackup/borg/pull/3024 this is about improving this, or at least making it more flexible.

**Comment by ThomasWaldmann** [comment]
@martinjo so, the "problematic" files where on what kind of filesystem?

**Comment by martinjo** [comment]
@ThomasWaldmann the files are in a "share", stored on several drives. I dont't know the specifics of how this would impact inodes. But it seems they are not "stable" since the backup works as intended with the --ignore-inode option. I'll ask in the unRAID forum... Thanks for all suggestions!

I'll close this issue now.
