### ISSUE TITLE
patterns-from maybe not skipping scan?

### ISSUE THREAD

**Issue by steveschow** [borgbackup/borg#3068]
I am using version 1.1rc3 (linux binary).  

I setup a --patterns-from file, which looks like this:

```
R /
- /bin/
- /boot/
- /dev/
- /lib/
- /lib64/
- /media/
- /mnt/
- /proc/
- /run/
- /selinux/
- /srv/
- /sys/
- /tmp/
- /data/hackman/
- /data/var/
- /data/sabnzbd/
- /home/*/.cache/
- /data/home/
- /data/.apps/
```

I get the following error while running borg create:

> /data/hackman/extra/.DocumentRevisions-V100: scandir: [Errno 13] Permission denied: '/data/hackman/extra/.DocumentRevisions-V100'

It sorta looks to me like borg is scanning through a dir which I specifically excluded using the above patterns file.  I would have thought that if a dir is excluded, then it should not be scanned at all.  Is this a bug or am I mis-interpreting the error message or perhaps not configuring the patterns file correctly?

**Comment by ThomasWaldmann** [comment]
IIRC there were 2 different excludes:
- exclude but scan for potential includes below
- exclude and do not scan below

**Comment by steveschow** [comment]
Ok, roger that, I found the "!" directive to avoid recursion.  But if there are no further include lines in the patterns-from file, then why would anything else need to be scanned recursively?

**Comment by steveschow** [comment]
FWIW, I think it doesn't need that directive, if you have an excluded dir, then it should not scan lower UNLESS there is an include directive below it, then that include gets scanned below (unless it of course has some more excludes and includes, etc).

For example:

```
R /
- /data
+ /data/include_this_dir
- /data/include_this_dir/but_not_this
```

The above would back up everything under "/", except it would ignore the /data dir, EXCEPT it would include the /data/include_this_dir folder, but not the /data/include_this_dir/but_not_this dir.

**Comment by ThomasWaldmann** [comment]
patterns (regex, glob) and fs structure (mounts, bind mounts, ...) can be complex, so borg does not try to compute what's "under" what.

it's the task of the admin to choose the appropriate patterns and exclude directives.

**Comment by steveschow** [comment]
Ok, but can I do this:

```
R /
! /data
+ /data/include_this_dir
```

You see the logical problem there?  You're saying that if I use "-" then its going to scan anyway, even though it doesn't appear to include anything...  but then if I use "!", its not going to be recursive...but what if I have a subsequent "+" that does need to be included?

I don't think the above that I suggested using "-" can be done properly without ending up with erratic scanning taking place in some cases..  and then if I use "!" I'm not sure it can be done at all since it sounds like recursion would be turned off.

I agree with you it can be complicated, and it is up to us to provide the patterns to do and not do..hence I don't see the point of having a scan that recurses when it doesn't need to...or do I see the benefit of using "!" to block recursion as long as there are no more "+" lines below that, then its redundant to need that feature...and it specifically would preclude me from being able to do the example I just gave.

**Comment by ThomasWaldmann** [comment]
Then you have configured it in a unsupported way. The "+" will never match because it is not even scanning this part of the filesystems, so matching filenames will never occur.

The problem with all this is that there can be e.g. regex include patterns of arbitrary complexity, so you can't decide by just looking at all the patterns whether the potentially matching files would be "under" some excluded directory (which could also be matched by a complex pattern).

Also, nobody stops you from mounting stuff a bit weirdly, e.g. same stuff at multiple places - we do not try to detect that / be "clever" about that either.

**Comment by steveschow** [comment]
I don't think you're understanding my simple request, but I give up.  If there is a proper way, please document it.  What I have suggested is now rsync and other stuff works.  Hope you will reconsider.  peace

**Comment by ThomasWaldmann** [comment]
It doesn't help us to solve one specific case (like all patterns simple, no includes at all).

It needs to be able to work for the general case (complex patterns, any amount of includes/excludes that conform to the documented behaviour).

**Comment by steveschow** [comment]
if your system can't handle this case then its a worthy discussion.  

This is an EXTREMELY common case.  Honestly, this is a deal breaker for me if I can't specify my backupset reasonably, and based upon what you're saying now I don't see a reasonable way to do it other then using some complicated external find command to build an explicit backup list for a situation that is simple and common.  Please reconsider or please explain how to use the existing framework to accomplish.  

Would this do it?
```
R /
! /data

R /data/include_this
! /data/include_this/but_not_this
```
