### ISSUE TITLE
non-intuitive exception chain on connection failure

### ISSUE THREAD

**Issue by rpodgorny** [borgbackup/borg#307]
this does not look very nice (exception within exception. and a full traceback instead of just nice message). a candidate for cleanup:

```
ssh: connect to host milhouse.podgorny.cz port 22: No route to host
borg: Error: Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/remote.py", line 147, in __init__
    version = self.call('negotiate', 1)
  File "/usr/lib/python3.5/site-packages/borg/remote.py", line 176, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.5/site-packages/borg/remote.py", line 226, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1030, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 986, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 111, in do_create
    repository = self.open_repository(args.archive, exclusive=True)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 41, in open_repository
    repository = RemoteRepository(location, create=create)
  File "/usr/lib/python3.5/site-packages/borg/remote.py", line 149, in __init__
    raise Exception('Server immediately closed connection - is Borg installed and working on the server?')
Exception: Server immediately closed connection - is Borg installed and working on the server?

borg: Exiting with failure status due to previous errors
```

**Comment by ThomasWaldmann** [comment]
I agree it doesn't look nice, but we must be careful to not lose information while making it look prettier.
Analyzing some attic issues has been a real pain just because it did not emit enough information.

**Comment by rpodgorny** [comment]
yep, sure thing. but i was just surprised as the server is currently down and the message says something about borg not being installed on the remote end. so i wanted to let you know it's a bit misleading...

**Comment by ThomasWaldmann** [comment]
well, the phrasing is "installed and working". If the server is down, it obviously not "working".

but I agree we could omit the "installed" part. borg is not working if it is not installed. borg is not working if the server is down. and you will notice the server is down when you check whether borg is working there.

i thought about replacing "working" with "running", but as this is not a permanent server process, we can't say "running".

**Comment by ThomasWaldmann** [comment]
btw, this is somehow part of the more general issue #57.
