### ISSUE TITLE
add BORG_CONFIG_DIR

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3083]
from the mailing list:

> I've read them BORG_CACHE_DIR is OK but I see no way to relocate the ".config/borg" directory in its *entirety*!
>
> If I read the docs correctly, I can only relocate *parts* of ".config" with BORG_KEYS_DIR and BORG_SECURITY_DIR but there are other files besides these on the ".config/borg" directory.
>
> I'd really like a BORG_CONFIG_DIR variable to relocate the *whole* config dir. I want everything in ONE predictable place, especially stuff related to backups which is a really critical process in my PoV.

**Comment by ThomasWaldmann** [comment]
Hmm, I see `.config/borg/key-nonces` on my machine, but all from 2016.

Didn't find `key-nonces` in the borg source (master branch).

**Comment by ThomasWaldmann** [comment]
Was it moved to `.config/borg/security/<repoid>/nonce`?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/1888/files

**Comment by narendravardi** [comment]
@ThomasWaldmann Can I pick this up?

**Comment by ThomasWaldmann** [comment]
sure, thanks! Make a PR against master.

The stuff is in helpers/fs.py and you can have a look at how the other BORG_*_DIR variables work, just do it in a similar way.

**Comment by ThomasWaldmann** [comment]
@narendravardi did you work on this issue yet or do you have questions?

**Comment by narendravardi** [comment]
@ThomasWaldmann This is what the changes I have made.

Included a function which would create 'BORG_CONFIG_DIR' and map this to '.config/borg' path in helpers/fs.py
I am looking at other files where BORG_*_DIR are used in the repo for making changes.

Is this what is expected? Please correct me if I am wrong.

**Comment by ThomasWaldmann** [comment]
Just have a look at the other similar env vars and do it in same way.
To discuss / code review, make a PR, so you can get feedback based on your code.

**Comment by narendravardi** [comment]
@ThomasWaldmann I have made changes and added to the following [commit](https://github.com/narendravardi/borg/commit/1fa23d162a562e147c348870a889a76decc0463e). The issue is that the travis-ci build is failing with some other errors. 

Travis-ci: https://travis-ci.org/narendravardi/borg/jobs/290760506

Do you suggest me to raise PR for this so that I can get some feedback on code?

**Comment by ThomasWaldmann** [comment]
Yes, see above.

**Comment by narendravardi** [comment]
Raised PR: #3206
