### ISSUE TITLE
Progress flag doesn't handle unicode gracefully.

### ISSUE THREAD

**Issue by alraban** [borgbackup/borg#309]
The progress flag sometimes produces corrupted output when ellipsizing with certain unicode characters, presumably because they can have non-standard width, so the next printed progress report doesn't fully erase them.  So for example, a file with kanji in the name will be backed up, and then the following file will look like this:

`3.60 TB O   3.58 TB C   3.58 TB D home/$USERNAME/data3/A...gren's Syndrome.flacd 漢 字 漢 字 .flac`

The extra characters stick around until another kanji file is written, or until the backup is completed.

**Comment by anarcat** [comment]
does this still happen on the master branch, after merge of #303? i reshuffled that code to clean that stuff up...

**Comment by alraban** [comment]
This was with release build 0.27.  I noticed it incidentally while running a large backup for testing #216

**Comment by ThomasWaldmann** [comment]
@alraban so could you test it again with git master branch?

**Comment by alraban** [comment]
Testing with the latest git master branch it's better but still not performing entirely as expected.  Instead of the previous behavior, whenever it hits a file with Kanji in the name, the progress report moves to a new line for the next file instead of staying on the same line like it does for regular files.  So when it works through an album with lots of kanji it looks like this:

```
613.15 MB O 613.18 MB C 613.00 MB D 28 N mnt/data3/Audio/MALICE MIZER/Merveilles/02 Syunikiss～二度目の哀悼～.flac                                                       
653.79 MB O 653.82 MB C 653.46 MB D 29 N mnt/data3/Audio/MALICE MIZER/Merveilles/03 ヴェル・エール～空白の瞬間の中で～.flac                                              
765.77 MB O 765.81 MB C 764.91 MB D 32 N mnt/data3/Audio/MALICE MIZER/Merveilles/06 エーゲ （過ぎ去りし風と共に）.flac                                                   
930.89 MB O 930.94 MB C 929.16 MB D 37 N mnt/data3/Audio/MALICE MIZER/Merveilles/11 月下の夜想曲.flac                                                                    
943.25 MB O 943.29 MB C 941.16 MB D 43 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂                                                                                         
946.41 MB O 946.45 MB C 944.31 MB D 44 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/01 薔薇に彩られた悪意と悲劇の幕開け.flac                                                
999.95 MB O 999.99 MB C 997.85 MB D 45 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/02 聖なる刻　永遠の祈り.flac                                                            
1.04 GB O 1.04 GB C 1.04 GB D 46 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/03 虚無の中での遊戯.flac                                                                      
1.07 GB O 1.07 GB C 1.07 GB D 47 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/04 鏡の舞踏　幻惑の夜.flac                                                                    
1.11 GB O 1.11 GB C 1.11 GB D 48 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/05 真夜中に交わした約束.flac                                                                  
1.14 GB O 1.14 GB C 1.14 GB D 49 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/06 血塗られた果実.flac                                                                        
1.18 GB O 1.18 GB C 1.17 GB D 50 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/07 地下水脈の迷路.flac                                                                        
1.20 GB O 1.20 GB C 1.20 GB D 51 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/08 破誡の果て.flac                                                                            
1.24 GB O 1.24 GB C 1.24 GB D 52 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/09 白い肌に狂う愛と哀しみの輪舞.flac                                                          
1.28 GB O 1.28 GB C 1.28 GB D 53 N mnt/data3/Audio/MALICE MIZER/薔薇の聖堂/10 再会の血と薔薇.flac     
```

**Comment by anarcat** [comment]
so it looks like the `len()` calls don't count characters properly... 

i'm unfortunately not very familiar with the Kanji charsets... are they fixed width? we currently assume that filenames of `N` characters have a width of `N` on the screen. if the font is not fixed width, this will inevitably create problems and i am not sure how we can work around that...

**Comment by ThomasWaldmann** [comment]
@alraban is that a monospace font? including the kanji chars? otherwise it can't really work I guess.

**Comment by alraban** [comment]
The font (terminus) is monospace, but I'm fairly sure that Terminus doesn't have kanji charsets. The kanji characters definitely take up more than one column, which was probably why they would force the ellipsized line to go wider than 80 character-width limit with the old progress report behavior. 
 
Unfortunately, I don't speak or type in any of the languages that use kanji, so I have limited familiarity with them.  I just come across them in Japanese film/music so I'm not sure how coders who use these charsets natively handle these types of issues.

**Comment by anarcat** [comment]
"oh well", i would say... if we don't have a monospace font, all assumptions are thrown out the window: we could add a few safety spaces to work around that behavior, but if the whole path is wider characters, we're screwed anyways...

so i would close this as fixed, sorry.

#314 could eventually fix this if we switch to ncurses or a GUI, however... but i feel this should be in a separate issue.

**Comment by alraban** [comment]
It's fine by me to close it.  The current behavior is legible and much superior to the old behavior (in .27) so that makes sense.

**Comment by anarcat** [comment]
cool, feel free to reopen if other issues come up or if you feel this should be fixed in the long term.
