### ISSUE TITLE
Add option to exclude files by size

### ISSUE THREAD

**Issue by n-st** [borgbackup/borg#3097]
`rsync` has the options `--min-size=SIZE` and `--max-size=SIZE` to ignore files that are smaller/bigger than a certain size.  
Can we add that to `borg` as well?

These options are particularly useful when backing up systems where users might choose to store large files (tarballs, disk images, media files, etc) in unforeseen places: you might have excluded `/home/*/Downloads`, but then someone decided to create `/home/johndoe/MyMovieCollection` and your backup size blows up.  
Excluding files by extension instead is likely to lead to false positives (you might want to keep that `.tar.gz` you created yourself and the `.mp4` you just finished editing) and false negatives (you *will* forget one of the dozens of different media/archive file extensions).

**Comment by ThomasWaldmann** [comment]
#902

**Comment by n-st** [comment]
Hmm, that one didn't come up when I searched for "exclude by size"…

Let's continue the discussion there.
