### ISSUE TITLE
Exception: Path should be relative and local

### ISSUE THREAD

**Issue by Mathiasdm** [borgbackup/borg#3108]
I am backing up buildroot builds (~5 GB), to be used by other users on other machines eventually. Unfortunately, when restoring a buildroot build, I get the following error (late in the restore process)::

  ```Local Exception
  Traceback (most recent call last):
    File "borg/archiver.py", line 4024, in main
    File "borg/archiver.py", line 3952, in run
    File "borg/archiver.py", line 148, in wrapper
    File "borg/archiver.py", line 159, in wrapper
    File "borg/archiver.py", line 724, in do_extract
    File "borg/archive.py", line 561, in extract_item
  Exception: Path should be relative and local
  ```

The error doesn't contain more details about the file or path causing the problem, unfortunately. I'm trying to get the borg build working locally to add this info (CentOS 7), but I haven't had too much success so far.

**Comment by enkore** [comment]
Try the --list option to narrow it down a bit.

**Comment by Mathiasdm** [comment]
Thanks!

The problem is a file called '..config.tmp'. Since the check for relative and local files is as follows, it fails: `if item.path.startswith(('/', '..')):`

I propose changing the check to the following (if that is safe): `if item.path.startswith(('/', '../')):`

**Comment by enkore** [comment]
Introduced in af059fbdfc, affects all versions.
