### ISSUE TITLE
1.1.0 triggers "Failed to add inotify watch descriptor for control group"

### ISSUE THREAD

**Issue by DamienCassou** [borgbackup/borg#3110]
I've just updated to 1.1.0 and I'm now seeing this in my logs:

```log
oct. 09 12:00:06 luz4 systemd[2263]: borg.service: Failed to add inotify watch descriptor for control group /user.slice/user-1000.slice/user@1000.service/borg.service: No space left on device
oct. 09 12:00:06 luz4 systemd[2263]: Starting Run borgbackup...
```

The message seems to be [generated by systemd](https://github.com/systemd/systemd/blob/v233/src/core/cgroup.c#L1288) but as it only started appearing after upgrade to 1.1.0, I thought I would report it here. Any idea?

**Comment by ThomasWaldmann** [comment]
That seems to be a problem outside of borg.
Maybe have a look into what the borg.service (not from us) is doing with inotify.

**Comment by DamienCassou** [comment]
My service file is

```systemd
[Unit]
Description=Run borgbackup

[Service]
Type=oneshot
Environment=BORG_REPO=%h/.local/share/borg/repository/
ExecStart=/usr/bin/borg create --verbose --stats --exclude-from %h/.config/borg/excludes ::'{hostname}-{now}' %h
ExecStart=/usr/bin/borg prune --verbose --list --prefix '{hostname}-' --keep-hourly=10 --keep-daily=7 --keep-weekly=4 --keep-monthly=6
```

and the timer is

```systemd
[Unit]
Description=Run borgbackup

[Install]
WantedBy=timers.target

[Timer]
OnCalendar=hourly
```

**Comment by ThomasWaldmann** [comment]
No inotify stuff there, so maybe within systemd.

**Comment by Zerophase** [comment]
Somewhat related. when backing up at multiple intervals I don't need multiple timers (hourly,daily,etc) for each interval?

**Comment by ThomasWaldmann** [comment]
Ehrm, it says "no space left on device" in the error msg (see top post).

Is just some of your filesystems full?

**Comment by DamienCassou** [comment]
> Is just some of your filesystems full?

sorry, I should have said that I checked that :-). To fix the problem, I increased the inotify limit with

```session
echo "fs.inotify.max_user_watches=204800" | sudo tee -a /etc/sysctl.d/90-override.conf
```

The bug can be closed IMO.
