### ISSUE TITLE
improve borg list --format doc (alias attributes)

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#3111]
https://borgbackup.readthedocs.io/en/stable/usage/list.html name and archive have the same description.

if they are the same you may want to refer one of them as an alias of the other?

**Comment by ThomasWaldmann** [comment]
```
  --format FORMAT, --list-format FORMAT
                        specify format for file listing (default: "{mode}
                        {user:6} {group:6} {size:8d} {mtime}
                        {path}{extra}{NL}")
```
So, maybe `--format '{name}{NL}'` is what you wanted.

**Comment by ThomasWaldmann** [comment]
About telling that one is the alias of the other: yes, we could do that. Also applies to some other value descriptions there.

**Comment by FabioPedretti** [comment]
You are right, they both works, thanks!

**Comment by FabioPedretti** [comment]
BTW, it would be nice to be able to use --format and --short also on prune.

**Comment by ThomasWaldmann** [comment]
@FabioPedretti separate ticket for that, describe the use case there.
