### ISSUE TITLE
How to test the project correctly?

### ISSUE THREAD

**Issue by bpereto** [borgbackup/borg#3123]
Since the release of borg 1.1.0 the packaging in fedora is broken. (142 failed tests)
It seems to use the borg binary for Tests, is this new?

Which is the correct way to test the project for only one interpreter, given by the buildenvironment?
Until now it was tested with pytest directly (see https://src.fedoraproject.org/rpms/borgbackup/blob/master/f/borgbackup.spec)   

```py.test-3 --pyargs borg.testsuite -vk "not test_non_ascii_acl and not test_fuse and not benchmark"```
fakeroot is not used, because it makes no sense to test all python versions when the package build is run for one fedora version which contains a defined python version.

The test command offered by setup.py runs 0 tests:
```
# python3 setup.py test
running test
running egg_info
writing src/borgbackup.egg-info/PKG-INFO
writing dependency_links to src/borgbackup.egg-info/dependency_links.txt
writing entry points to src/borgbackup.egg-info/entry_points.txt
writing requirements to src/borgbackup.egg-info/requires.txt
writing top-level names to src/borgbackup.egg-info/top_level.txt
reading manifest file 'src/borgbackup.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.coafile'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.gitattributes'
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'Vagrantfile'
no previously-included directories found matching '.travis'
no previously-included directories found matching '.github'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no previously-included files matching '*.orig' found anywhere in distribution
warning: no previously-included files matching '*.dll' found anywhere in distribution
writing manifest file 'src/borgbackup.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by ThomasWaldmann** [comment]
It will additionally test a borg.exe binary, if it can be found in the PATH (so, not for you, no problem).

I suspect that your issue is due to you trying to test stuff without installing borg.
borg 1.0 had the package at ./borg, so that was automatically used for imports (even if not wanted).
borg 1.1 moved the package to ./src/borg, so that does not unintentionally happen and really the installed code gets tested. this is python best practice.

so, how about just invoking tox -e py35 or so?

**Comment by bpereto** [comment]
fedora uses mock to build, so its a fakeroot in fakeroot, not so nice.

got the error:
```
___________________________________________________ test_return_codes[python] ____________________________________________________

cmd = <function cmd.<locals>.exec_fn at 0x7faf441782f0>
tmpdir = local('/tmp/pytest-of-beni/pytest-21/test_return_codes_python_0')

    def test_return_codes(cmd, tmpdir):
        print(cmd)
        repo = tmpdir.mkdir('repo')
        input = tmpdir.mkdir('input')
        output = tmpdir.mkdir('output')
        input.join('test_file').write('content')
        rc, out = cmd('init', '--encryption=none', '%s' % str(repo))
        print(out)
        assert rc == EXIT_SUCCESS
        rc, out = cmd('create', '%s::archive' % repo, str(input))
        assert rc == EXIT_SUCCESS
        with changedir(str(output)):
            rc, out = cmd('extract', '%s::archive' % repo)
            print(out)
>           assert rc == EXIT_SUCCESS
E           assert 1 == 0

build/lib.linux-x86_64-3.6/borg/testsuite/archiver.py:158: AssertionError
```

PYTHONPATH is not correctly set and is wrong, when it uses `with changedir(str(output))` to change int o `/tmp`, there is no module borg. At the time borg ist also not installed in the system root (or system root of the fake environment).
