### ISSUE TITLE
1.1.0 - nodump flag excluding stuff on unraid

### ISSUE THREAD

**Issue by airbillion** [borgbackup/borg#3127]
I have been using borg for well over a year now...I have updated between versions everytime without any issues except for the latest release...1.1.0.

When I run my backups it seems as though borg is not seeing all the files in my directories...I have tried all the different options using the --files-cache without any success...when I mount an archive after running a backup only a few directories are shown..if i downgrade back to 1.0.11 and run the backup again my whole directory is backed  up correctly...

The report after running shows:

```
borg 1.1.0:
------------------------------------------------------------------------------                                                                                      
Archive name: Tower-DOWNLOADS-2017-10-10
Archive fingerprint: 9866d6dd574c6488f2bbfdbf8003695556da0acb690b71a5eedf756b0e224442
Time (start): Tue, 2017-10-10 13:54:28
Time (end):   Tue, 2017-10-10 13:54:28
Duration: 0.14 seconds
Number of files: 0
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  631 B                585 B                585 B
All archives:                1.00 TB            879.78 GB            106.85 GB

                       Unique chunks         Total chunks
Chunk index:                   76804               621866
------------------------------------------------------------------------------
Keeping archive: Tower-DOWNLOADS-2017-10-10           Tue, 2017-10-10 13:54:28 [9866d6dd574c6488f2bbfdbf8003695556da0acb690b71a5eedf756b0e224442]
Keeping archive: Tower-DOWNLOADS-2017-10-09           Mon, 2017-10-09 00:15:55 [463b52fffc51b982037df5464310d70c4288c58e99d657ede6de248fa2aeb9e8]
Keeping archive: Tower-DOWNLOADS-2017-10-08           Sun, 2017-10-08 00:15:38 [e027fb3f1bf2653e8744107382e7ae09933ac04fb7df7ee2b9a570ab0b58f3cb]
Keeping archive: Tower-DOWNLOADS-2017-10-07           Sat, 2017-10-07 00:15:43 [43663b684f99127e7e2e991cc0f04478746c36a1eb23693fa1872bf4f8d40ea3]
Keeping archive: Tower-DOWNLOADS-2017-10-06           Fri, 2017-10-06 00:15:59 [15124fb778a0aac88e0077dc5f3720c351d18223f59b72b52fff53a012ca6966]
Keeping archive: Tower-DOWNLOADS-2017-10-05           Thu, 2017-10-05 00:15:36 [aab098fcb86d6f290fd45c1a48020e28f4f4785a9e7e44887fc197955f7c63a5]
Keeping archive: Tower-DOWNLOADS-2017-10-04           Wed, 2017-10-04 00:15:59 [77471d3464a2029788f0a2e66c420769dd08ff22ea5dbb303baf5db96a2727b1]
Keeping archive: Tower-DOWNLOADS-2017-10-03           Tue, 2017-10-03 00:16:12 [c1b20304b7a39fef4b556db4c2ffeefff52b7bad12d43c105f84a8bee50754cd]
------------------------------------------------------------------------------


borg 1.0.11
------------------------------------------------------------------------------                                                                                      
Archive name: Tower-DOWNLOADS-2017-10-10
Archive fingerprint: f08500be0803025d671f11a224215179635ff2bf83a6e42fa4d6302b768ecba3
Time (start): Tue, 2017-10-10 14:31:20
Time (end):   Tue, 2017-10-10 14:32:05
Duration: 44.78 seconds
Number of files: 40352
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              148.08 GB            130.39 GB            480.64 kB
All archives:                1.15 TB              1.01 TB            106.86 GB

                       Unique chunks         Total chunks
Chunk index:                   76809               712568
------------------------------------------------------------------------------
Keeping archive: Tower-DOWNLOADS-2017-10-10           Tue, 2017-10-10 14:31:20
Keeping archive: Tower-DOWNLOADS-2017-10-09           Mon, 2017-10-09 00:15:55
Keeping archive: Tower-DOWNLOADS-2017-10-08           Sun, 2017-10-08 00:15:38
Keeping archive: Tower-DOWNLOADS-2017-10-07           Sat, 2017-10-07 00:15:43
Keeping archive: Tower-DOWNLOADS-2017-10-06           Fri, 2017-10-06 00:15:59
Keeping archive: Tower-DOWNLOADS-2017-10-05           Thu, 2017-10-05 00:15:36
Keeping archive: Tower-DOWNLOADS-2017-10-04           Wed, 2017-10-04 00:15:59
Keeping archive: Tower-DOWNLOADS-2017-10-03           Tue, 2017-10-03 00:16:12
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:                1.15 TB              1.01 TB            106.86 GB

                       Unique chunks         Total chunks
Chunk index:                   76809               712568
------------------------------------------------------------------------------
```

Is there anything I am missing that I should do befor I upgrade to 1.1.0?

Any help would be appreciated!!

Thanks

**Comment by ThomasWaldmann** [comment]
Can you add the full borg command you use? Also, if we talk about borg create, remove the borg prune output please.

**Comment by airbillion** [comment]
Sure...sorry....

command:

'borg create -v -s -p --list --filter=AME --files-cache=ctime,size --compression lz4' "root@192.168.1.135:/mnt/user/borg_backup_repos/downloads/"::"$(hostname)-DOWNLOADS-$now" "/mnt/user/downloads/"

**Comment by ThomasWaldmann** [comment]
can you try without the -p --filter? can you catch all the output, stdout and stderr?
also, remove the trailing slashes from repo and source path?

**Comment by airbillion** [comment]
Hi,

Sure... everything is in quotes because I pulled it all from my backup script which uses variables...

I use a script that has been running nightly for over a year now...I also created a test repo with a small test folder to backup and have the same issues...

Using a script helps with my export values for the location of my backup repo and locations for the cache...

I'll post my results here later...thank you for the help!!

I hope I can get this figured out...

**Comment by ThomasWaldmann** [comment]
Do it step by step please, so we definitively find what's causing this. Thanks!

**Comment by enkore** [comment]
Check if there is a NODUMP flag on the files or directories.

**Comment by airbillion** [comment]
Test repo creation with -P & --filter removed...trailing slashes removed from repo and backup directory...quotes also removed:

root@Tower:/boot/scripts/borg_scripts/repo_scripts# ./borg_test.sh 

Borg TEST Backup script started....Tue Oct 10 22:27:32 EDT 2017
x /mnt/user/downloads/Books/walking_dead
------------------------------------------------------------------------------
Archive name: Tower-TEST-2017-10-10-1507688852
Archive fingerprint: b2edbd38c7a2db804260497979c34bc15c911b31e1e476f014972343baed77b0
Time (start): Tue, 2017-10-10 22:27:35
Time (end):   Tue, 2017-10-10 22:27:35
Duration: 0.00 seconds
Number of files: 0
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  537 B                532 B                532 B
All archives:              686.57 MB            649.65 MB            575.44 MB

                       Unique chunks         Total chunks
Chunk index:                     824                  897
------------------------------------------------------------------------------

Looks like it is excluding the whole directory for some reason...I have no exclude in the create command...

**Comment by ThomasWaldmann** [comment]
Is this backing up a mounted smb share exported by macOS?

**Comment by airbillion** [comment]
no....a local share...
Very odd because when I revert to  version 1.0.11...the whole share backs up normally..

**Comment by airbillion** [comment]
Here is the command:

borg create -v -s --list --compression lz4 root@192.168.1.135:/mnt/user/borg_backup_repos/test::$(hostname)-TEST-$now /mnt/user/downloads/Books/walking_dead

**Comment by airbillion** [comment]
lsattr output:

root@Tower:/boot/scripts/borg_scripts/repo_scripts# cd /mnt/user/downloads/Books/walking_dead/
root@Tower:/mnt/user/downloads/Books/walking_dead# lsattr
------dA----tTe--N- ./The Walking Dead 144 (2015) (Digital) (Minutemen-Acan).cbr
-----a---Ej-------P ./The.Chilling.Archives.of.Horror.Comics!.005.-.Haunted.Horror.2013.digital-Empire
---D------jIt--h-N- ./The.Walking.Dead.Compendium.V01.2011.Digital-EMPIRE
---------E-It--h--P ./The.Walking.Dead.Compendium.V01.2011.Digital-EMPIRE.1
---Dia---EjI------- ./The.Walking.Dead.Graphic.Novels
-----a-A---I------- ./The.Walking.Dead.Compendium.V01.2011.Digital-EMPIRE.2
-----a---Ej-------P ./The Walking Dead 149 (2015) (Digital) (Zone-Empire)
---D------jIt--h-N- ./The Walking Dead 150 (2016) (Digital) (Zone-Empire)
------dA----tTe--N- ./The Walking Dead 151 (2016) (Digital) (Zone-Empire)
---Di-d------T---N- ./The Walking Dead 152 (2016) (Digital) (Zone-Empire)
-----a-A---I------- ./The Walking Dead 153 (2016) (Digital) (Zone-Empire)
-----a---Ej-------P ./The Walking Dead 154 (2016) (Digital) (Zone-Empire)
-----ad---jI-T----P ./The Walking Dead 155 (2016) (Digital) (Zone-Empire)
------d--EjI------- ./The Walking Dead 156 (2016) (Digital) (Zone-Empire)
---Di-d------T---N- ./The Walking Dead 157 (2016) (Digital) (Zone-Empire)
---D---A-E--t--h-N- ./The Walking Dead 158 (2016) (Digital) (Zone-Empire)
---------E-It--h--P ./The Walking Dead 159 (2016) (Digital) (Zone-Empire)
-----ad---jI-T----P ./The.Walking.Dead.160.2016.Digital.Zone-Empire

**Comment by ThomasWaldmann** [comment]
don't do the lsattr in that dir, but one level higher.
you see at the x that borg is not even entering that directory.

**Comment by airbillion** [comment]
Output:

root@Tower:/mnt/user/downloads/Books# lsattr 
-----ad--E--tT-h--P ./!GMA SCAN
---D-adA----t-e--N- ./walking_dead
----i-dA-E--t--h--- ./ebooks

**Comment by airbillion** [comment]
Was something changed between 1.1.0 and 1.0.11 that would cause difference?

**Comment by airbillion** [comment]
Sorry...i didn't catch that...must be part of the issue

Unraid is a NAS OS based on linux slackware:  https://lime-technology.com/what-is-unraid/

Filesysem is xfs...my drives are pooled into a large storage array using fuse

**Comment by airbillion** [comment]
Is there a way I can disable the bsdflags support (including NODUMP flag) to test and see if that is the issue?

**Comment by ThomasWaldmann** [comment]
No, but we know it is that. There is a "d" flag in your walking_dead directory, saying NODUMP.

I'ld consider that a bug in the filesystem you use. So, just to be clear, is that?:
- some "unraid" filesystem on top of xfs
- xfs on top of a unraid block device

Output of `mount` command for /mnt/user/downloads?

**Comment by ThomasWaldmann** [comment]
General note: guess we need a way to switch of NODUMP support (or bsdflags completely). We already had that issue for the macOS share and now also for unraid, so it seems that we can't rely on bsdflags.

**Comment by ThomasWaldmann** [comment]
@airbillion guess you have to continue using 1.0.x to backup that stuff, until this is addressed by us (or fixed in unraid).

**Comment by airbillion** [comment]
Output:

root@Tower:/mnt/user/downloads# mount
proc on /proc type proc (rw)
sysfs on /sys type sysfs (rw)
tmpfs on /dev/shm type tmpfs (rw)
tmpfs on /var/log type tmpfs (rw,size=128m,mode=0755,size=384m)
/dev/sda1 on /boot type vfat (rw,noatime,nodiratime,umask=0,shortname=mixed)
/boot/bzmodules on /lib/modules type squashfs (ro)
/boot/bzfirmware on /lib/firmware type squashfs (ro)
/mnt on /mnt type none (rw,bind)
/dev/md1 on /mnt/disk1 type xfs (rw,noatime,nodiratime)
/dev/md2 on /mnt/disk2 type xfs (rw,noatime,nodiratime)
/dev/md3 on /mnt/disk3 type xfs (rw,noatime,nodiratime)
/dev/md4 on /mnt/disk4 type xfs (rw,noatime,nodiratime)
/dev/md5 on /mnt/disk5 type xfs (rw,noatime,nodiratime)
/dev/md6 on /mnt/disk6 type xfs (rw,noatime,nodiratime)
/dev/md7 on /mnt/disk7 type xfs (rw,noatime,nodiratime)
/dev/sde1 on /mnt/cache type xfs (rw,noatime,nodiratime)
shfs on /mnt/user0 type fuse.shfs (rw,nosuid,nodev,noatime,allow_other)
shfs on /mnt/user type fuse.shfs (rw,nosuid,nodev,noatime,allow_other)
/dev/sdd1 on /mnt/disks/Samsung_SSD_850_EVO_500GB_S2RANXAH314418B type xfs (rw,noatime,nodiratime)
/mnt/cache/system/docker/docker.img on /var/lib/docker type btrfs (rw)
/mnt/cache/system/libvirt/libvirt.img on /etc/libvirt type btrfs (rw)

Unraid does not use any special file system that I am aware of all my drives are formatted as xfs and can pe pulled and read by any linux OS...maybe it is their pooling system, but I am not sure if it is proprietary or not...

Ok...at least the issue is narrowed down now...I think having a switch/flag  to turn off the bsdflags would be the way to fix the issue...I keep on using v 1.0.11 in the mean time and check back when ther is a fix or work around...

I appreciate all your time and help in trying to get to the bottom of this!!  Hope it can be fixed...I think borg is the best backup software available!!

Thanks again!

**Comment by ThomasWaldmann** [comment]
https://www.reddit.com/r/unRAID/comments/75mjja/unraid_random_bsdflags_problem/

**Comment by ThomasWaldmann** [comment]
So the problematic fs here is `fuse.shfs` (unRAID?), not xfs.

**Comment by airbillion** [comment]
I'm not sure, but í posted this to their defect reports forum to see what they say...

https://forums.lime-technology.com/index.php?/topic/60701-Borgbackup-1.1.0-issue

**Comment by enkore** [comment]
Did you try `chattr -R -d your_files`?

**Comment by airbillion** [comment]
Tried...but no luck....the attriutes could not be changed...
chattr -R -d /mnt/user/downloads/Books/walking_dead/
root@Tower:/mnt/user/downloads/Books/walking_dead# lsattr
---D--d--E-ItTe--N- ./The Walking Dead 144 (2015) (Digital) (Minutemen-Acan).cbr
----ia-----It----N- ./The.Chilling.Archives.of.Horror.Comics!.005.-.Haunted.Horror.2013.digital-Empire
-----adA-EjI-Te---- ./The.Walking.Dead.Compendium.V01.2011.Digital-EMPIRE
----i-dA-E--t-e--N- ./The.Walking.Dead.Compendium.V01.2011.Digital-EMPIRE.1
---Di-----jI-T----P ./The.Walking.Dead.Graphic.Novels
-----ad--EjItTe--N- ./The.Walking.Dead.Compendium.V01.2011.Digital-EMPIRE.2
---DiadA--j-tTe---- ./The Walking Dead 149 (2015) (Digital) (Zone-Empire)
-----adA-EjI-Te---- ./The Walking Dead 150 (2016) (Digital) (Zone-Empire)
----iad--EjIt-eh--P ./The Walking Dead 151 (2016) (Digital) (Zone-Empire)
---Di-----jI-T----P ./The Walking Dead 152 (2016) (Digital) (Zone-Empire)
---D--d--E-ItTe--N- ./The Walking Dead 153 (2016) (Digital) (Zone-Empire)
----ia-----It----N- ./The Walking Dead 154 (2016) (Digital) (Zone-Empire)
-----a------tT----- ./The Walking Dead 155 (2016) (Digital) (Zone-Empire)
----i-dA-E--t-e--N- ./The Walking Dead 156 (2016) (Digital) (Zone-Empire)
----iadA-E-I------P ./The Walking Dead 157 (2016) (Digital) (Zone-Empire)
-----ad--EjItTe--N- ./The Walking Dead 158 (2016) (Digital) (Zone-Empire)
---DiadA--j-tTe---- ./The Walking Dead 159 (2016) (Digital) (Zone-Empire)
-----adA-EjI-Te---- ./The.Walking.Dead.160.2016.Digital.Zone-Empire

**Comment by enkore** [comment]
Maybe there is just a zeroing missing in shfs_getattr for stat->attributes before generic_fillattr.

**Comment by enkore** [comment]
Why do you even need shfs? Shouldn't sshfs work just as well?

**Comment by airbillion** [comment]
shfs is the pooling solution that unraid uses to create 1 big storage location for all the drives...

**Comment by enkore** [comment]
I see. shfs of unRAID is a completely different thing from the  open-source shfs (shell filesystem).

Perhaps report this as a security problem, since it seems to leak uninitialized memory to low/un-privileged users. Who knows what data is in there...

**Comment by ThomasWaldmann** [comment]
closing this as this is not a borg bug (but in unraid).

opened #3160 for the workaround.
