### ISSUE TITLE
use chunks.archive.d for borg info repo::archive?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3128]
check if we can speed up using the single-archive hashindex cached there.

note: for my own ~500GB repo and a ~130GB archive, `borg info repo::archive` took ~6 minutes.

**Comment by enkore** [comment]
This was actually already implemented once in #2764

**Comment by ThomasWaldmann** [comment]
Ah, right, we wanted to cherry-pick that part from there... - can you do it?

**Comment by enkore** [comment]
It heavily depended on the whole patch.

**Comment by ThomasWaldmann** [comment]
part of this was re-implemented in #4391.

the remaining slow path is for computing the unique_csize (and fetching / building an archive index from remote for this).

**Comment by ThomasWaldmann** [comment]
in borg2 branch, i removed all the csize stuff. iirc, the unique size is still expensive, check this again...
