### ISSUE TITLE
factor out UI elements to enable GUIs, filtering

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#314]
taking that out of #302, as requested:

here's another idea i had to resolve this just now. we could integrate the idea of a `UI` class somewhere. this would expand the `logger` module functionality to also cover stuff like user input, `--progress`, `--stats`, whether we show file output and so on. instead of calling basic methods like:

``` Python
print("Archive size: 50 GB")
logging.log("processing files")
print("\rprogress: 50%")
input("are you sure? [Y/n]")
```

...we could instead use:

``` Python
ui.display('Archive size: 50 GB')
ui.status('processing files')
ui.progress("progress: %d%%", percent)
ui.prompt('are you sure?', ['yes', 'no'], default='Yes')
```

This would allow us to control the interaction with the user topically, without having to propagate the `args` object all over the place. We'd initialize a UI object when we start with the commandline args, and then filtering can happen more naturally.

Even better: this can enable all sorts of UIs as well... A GUI could easily be built on top of this: `ui.display` could send information in a popup or a widget, `ui.status` could go in a status bar or notification area, `ui.progress` could update a status bar, `ui.prompt` would be a popup with buttons, etc...

i have implemented something like this for Monkeysign: there, i have a [ui module](https://sources.debian.net/src/monkeysign/2.0.2/monkeysign/ui.py/) that handles commandline parsing for both the GTK and commandline interfaces. it also configures a set of basic abstract functions like the above, that are then implemented in the [cli](https://sources.debian.net/src/monkeysign/2.0.2/monkeysign/cli.py/) and [gtk](https://sources.debian.net/src/monkeysign/2.0.2/monkeysign/gtkui.py/) modules.

**Comment by ThomasWaldmann** [comment]
Labelled it as later as we have to stabilize stuff now for next releases.

**Comment by ThomasWaldmann** [comment]
as there are some GUIs now, guess this was solved by the json output/log mode.
