### ISSUE TITLE
--show-version in the docs, but --version in borg

### ISSUE THREAD

**Issue by SanskritFritz** [borgbackup/borg#3142]
I think --show-version doesn't exist:
```
frank@HomeC ~/Downloads> ./borg-linux64 --version
borg-linux64 1.1.0
frank@HomeC ~/Downloads> ./borg-linux64 --show-version
Traceback (most recent call last):
  File "borg/__main__.py", line 2, in <module>
  File "borg/archiver.py", line 4013, in main
  File "borg/archiver.py", line 3849, in get_args
  File "borg/archiver.py", line 3873, in parse_args
AttributeError: 'Namespace' object has no attribute 'fallback_func'
Failed to execute script __main__
```

**Comment by ThomasWaldmann** [comment]
So? Where's the issue?

**Comment by SanskritFritz** [comment]
The issue is that the documentation says --show-version, but borg gives an error on that. But it does understand the --version switch.

**Comment by ThomasWaldmann** [comment]
Works for me (borg 1.1):
```
(borg-env) tw@tux:~/w/borg$ borg --version
borg 1.1.1.dev3+gf407de0

(borg-env) tw@tux:~/w/borg$ borg create --show-version --show-rc --list -v repo::arch inp/
borgbackup version 1.1.1.dev3+gf407de0
b inp/fd0
d inp
terminating with success status, rc 0
```

**Comment by ThomasWaldmann** [comment]
So, guess the docs should say how to use these 2 options (== together with another borg command).

The intention is to have the borg version / the borg rc in the log when e.g. running borg create.

**Comment by ThomasWaldmann** [comment]
http://borgbackup.readthedocs.io/en/stable/usage/general.html?highlight=show-version#common-options

**Comment by SanskritFritz** [comment]
Oh, I see, thanks. Well then, --version is undocumented?

**Comment by enkore** [comment]
+bug since it shouldn't crash

**Comment by SanskritFritz** [comment]
Ok, but I still think --version is undocumented. Or am I wrong?

**Comment by ThomasWaldmann** [comment]
Looks like, separate issue.
