### ISSUE TITLE
Is it safe to push multiple backups to different remote repos one the same host?

### ISSUE THREAD

**Issue by Nosxxx** [borgbackup/borg#3143]
I have 1 borgbackup remote host for multiple server.

Is it save to push a backup from server1 (repo1) and server2 (repo2) to the remote-host at the same time?

Hopefully you understand my question.

Thanks

**Comment by mlbarrow** [comment]
If the backups are going to their own repos, there should not be an issue. I have a single server that houses repos in different directories (`borg init ./server1; borg init ./server2`). Then I have individual SSH keys for each of those servers with an ssh forced command that directs them at their respective repos.

You should *NOT* have two servers going to the same repo at the same time, per the FAQ: http://borgbackup.readthedocs.io/en/stable/faq.html#can-i-backup-from-multiple-servers-into-a-single-repository

Refer to this page for detailed instructions on setting up a multiple client setup: http://borgbackup.readthedocs.io/en/stable/deployment/hosting-repositories.html

**Comment by Nosxxx** [comment]
Thanks for your answer!

**Comment by ThomasWaldmann** [comment]
Guess we're done here.
