### ISSUE TITLE
borg: error: unrecognized arguments: --files-cache=disabled

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#3146]
$ borg -V
borg 1.1.0

```
borg prune ... -v -s --list --no-files-cache ...
...
Warning: "--no-files-cache" has been deprecated. Use "--files-cache=disabled" instead.
```
and

```bash
borg prune ... -v -s --list --files-cache=disabled ...
...
borg: error: unrecognized arguments: --files-cache=disabled
```

**Comment by ThomasWaldmann** [comment]
Interesting. borg prune does not use the files cache anyway.

But looks like you discovered some discrepancy in how these 2 options are handled.

**Comment by enkore** [comment]
Why exactly is --no-files-cache a common option anyway? It is only used by `borg create`.

**Comment by knutov** [comment]
As far as I remember - if I'm not using this option with `borg prune` - the local cache are downloaded.

**Comment by ThomasWaldmann** [comment]
@enkore I reviewed the code and it seems that for prune, it can just be do_files=False.

So yes, it is only borg create left as a user of --files-cache and --no-files-cache.

**Comment by knutov** [comment]
After 

```
borg prune ./${path} -v -s --list --keep-daily=3 --keep-weekly=2 --keep-monthly=2  --keep-within 9d
```
files-cache is created. Should it be so? Is there way not to use it with prune?

I do `borg prune` from storage server side (it's separate remote server) with slow HDDs, so there is no cache in the beginning from this side.

**Comment by ThomasWaldmann** [comment]
@knutov please open a new issue if the issue is different.

**Comment by knutov** [comment]
ok, #3248

but it seems to be the same my issue - I wanted not to have files-cache with borg 1.1...
