### ISSUE TITLE
borg mount -o versions, for some archives

### ISSUE THREAD

**Issue by bobblkabb** [borgbackup/borg#3149]
My archive is propably too overkill for this feature. Was getting a 'killed' message.

**All archives**  
Original size  47.92 TB
Compressed size 36.37 TB
Deduplicated size 244.78 GB
**Chunk index**   
Unique chunks 494165
Total chunks 75598540

Running borgbackup 1.1 on Ubuntu 16.04.3 (vmware) with only 1 CPU and 2 GB RAM.
Any advice? What can I do?

**Comment by fsironman** [comment]
Download more RAM!

Jokes aside the memory usage for just doing backups with borg is probably enough for the 2 GB RAM. 
The FUSE mount might need way more memory I could not find a number in http://borgbackup.readthedocs.io/en/stable/internals/data-structures.html#indexes-caches-memory-usage though.

I would check with free / top and/or your syslog if it really was an OutOfMemory kill.

**Comment by enkore** [comment]
The versions view needs an extreme amount of memory.

**Comment by bobblkabb** [comment]
I see.
Trippled RAM up to 6GB (+2GB swap). Now it's working or at least I didn't get the killed message. Unfortunately I reconnected my ssh session and somehow the mount got disconnected ('socket's not connected').
Took an hour to mount btw.

Is there a way to mount a range of the repository instead of the complete repo? I got daily backups for nearly half a year.

**Comment by ThomasWaldmann** [comment]
The TODO here is to support the versions view for only some (not: all) archives using the usual --last, ... set of options.

**Comment by ThomasWaldmann** [comment]
For now you also can do the (non-"versions") repo mount and only access the archive subdirs you really need to look at. Less comfortable, but also less memory needs.

**Comment by bobblkabb** [comment]
@ThomasWaldmann 
The --last option is a good hint. Working fine.

**Comment by ThomasWaldmann** [comment]
Oh, we already have that? Good. :)
