### ISSUE TITLE
borg init does not respect BORG_PASSPHRASE

### ISSUE THREAD

**Issue by bebehei** [borgbackup/borg#3151]
With borg 1.1, `borg init` does requires now an `--encryption` parameter albeit `BORG_PASSPHRASE` has been already set. This was not the case with borg 1.0.

Is this wanted behavior? 

A small piece of shell output for better description:

```
[bebe:~/borgexp] % borg1.1 --version
borg 1.1.0
[bebe:~/borgexp] % borg1.0 --version
borg 1.0.11
[bebe:~/borgexp] % export BORG_PASSPHRASE=''                                             
[bebe:~/borgexp] % export BORG_REPO=./repo
[bebe:~/borgexp] % ls
[bebe:~/borgexp] % borg1.1 init
[...]
borg init: error: the following arguments are required: -e/--encryption
[bebe:~/borgexp] 2 % ls
[bebe:~/borgexp] % borg1.0 init
[ warning about tam, but it works]
[bebe:~/borgexp] % ls
repo
[bebe:~/borgexp] %
```

**Comment by ThomasWaldmann** [comment]
borg 1.0 has none, repokey, keyfile as options for -e, defaulting to repokey.

borg 1.1 adds repokey-blake2 / keyfile-blake2 (using blake2b as a faster alternative to hmac-sha256) and also authenticated / authenticated-blake2 as authenticated, but not encrypted modes.

while blake2b modes are faster and authenticated is better than none, these modes do not exist in borg 1.0, so one can't use them if backwards compatibility is an issue. but one likely wants to use them, if it isn't.

So, there is no clear default, the user needs to make an informed decision after reading the docs.

This all is unrelated to BORG_PASSPHRASE, which just sets the passphrase.
