### ISSUE TITLE
Usability: "borg check" should prompt for password immediately and verify it immediately

### ISSUE THREAD

**Issue by realityexists** [borgbackup/borg#3153]
borg 1.1.0. When I run `borg check -v --verify-data REPOSITORY_PATH` it runs for about an hour, then prompts me for the password, then runs for another hour. This means the user has to check back once in a while until the first part is done, enter the password, then wait again.

It would be better if borg immediately prompted for the password. The user could then just leave it running and come back much later to find it's all finished. Borg should also verify the password immediately, otherwise the user is back to the original problem if they enter the password wrong - or, worse, the check fails after having run for a long time.

Setting BORG_PASSPHRASE would probably work around this, but the user has to remember to do that every time.

**Comment by ThomasWaldmann** [comment]
see #1931.
