### ISSUE TITLE
borg 1.1.0 does not work - Repository encryption method changed

### ISSUE THREAD

**Issue by devZer0** [borgbackup/borg#3158]
i`m trying to upgrade to borg 1.1.0 and while testing i`m getting this one:

old version - working good for months:
```
[root@backupvm2 borg-repos]# /backup/bin/borg-1.0.11 list --debug  /iscsi/lun1/borg-repos/adminstation
using builtin fallback logging configuration
TAM-verified manifest
archive-2017-02-28_1052              Tue, 2017-02-28 12:41:22
...
archive-2017-10-13_1524              Fri, 2017-10-13 15:23:40
```

1.10 not even listing repo contents:
```
[root@backupvm2 borg-repos]# /backup/bin/borg-1.1.0 list --debug  /iscsi/lun1/borg-repos/adminstation
using builtin fallback logging configuration
35 self tests completed in 0.14 seconds
TAM-verified manifest
Cache integrity: No integrity data found (files, chunks). Cache is from old version.
security: read previous location ''
security: using previous_location of cache: '/iscsi/lun1/borg-repos/adminstation'
Repository encryption method changed since last access, refusing to continue
Traceback (most recent call last):
  File "borg/archiver.py", line 4024, in main
  File "borg/archiver.py", line 3952, in run
  File "borg/archiver.py", line 141, in wrapper
  File "borg/cache.py", line 199, in assert_secure
  File "borg/cache.py", line 165, in assert_secure
  File "borg/cache.py", line 172, in _assert_secure
  File "borg/cache.py", line 153, in assert_key_type
borg.cache.Cache.EncryptionMethodMismatch: Repository encryption method changed since last access, refusing to continue

Platform: Linux backupvm2 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64
Linux: CentOS Linux 7.3.1611 Core
Borg: 1.1.0  Python: CPython 3.5.4
PID: 29559  CWD: /iscsi/lun1/borg-repos
sys.argv: ['/backup/bin/borg-1.1.0', 'list', '--debug', '/iscsi/lun1/borg-repos/adminstation']
SSH_ORIGINAL_COMMAND: None
```

Same problem with "borg info"

Environment:
```
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes
export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
export BORG_CACHE_DIR=/backup/borg-cache
```

**Comment by devZer0** [comment]
getting closer:

[root@backupvm2 security]# mv /root/.config/borg/security/402db26002abd9df0fa4def5e94e61645106dff354eeac48434934b84616866c /root/.config/borg/security/402db26002abd9df0fa4def5e94e61645106dff354eeac48434934b84616866c.old

[root@backupvm2 security]# ls -la /root/.config/borg/security/402db26002abd9df0fa4def5e94e61645106dff354eeac48434934b84616866c.old
insgesamt 16
drwx------   2 root root    61 13. Okt 15:01 .
drwx------ 109 root root 12288 13. Okt 16:22 ..
-rw-------   1 root root     0 13. Okt 15:01 key-type
-rw-------   1 root root     0 13. Okt 15:01 location
-rw-------   1 root root     0 13. Okt 15:01 manifest-timestamp


[root@backupvm2 security]# /backup/bin/borg-1.1.0 list /iscsi/lun1/borg-repos/adminstation.cybercon.de
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] y
archive-2017-02-28_1052              Tue, 2017-02-28 12:41:22 [7b858664cb8020f09cbe4166dad7bdf044158964d965b0be236f32d6ed4b31f4]
archive-2017-03-31_0146              Fri, 2017-03-31 03:19:34 [e4722ee4783cf5bff244703579f2572cd681ba897f21af053c7f0b17dc5c7478]
archive-2017-05-31_0318              Wed, 2017-05-31 05:52:42 [12970e6ce57662916c39c88be3ea598c22ff72d31a901b8ad178af939037dd15]
archive-2017-06-30_0832              Fri, 2017-06-30 15:25:53 [adbb5085c34501f3fb555051ba01da41e838dfc97b2291cf5c1206f24703d676]
archive-2017-07-23_0213              Sun, 2017-07-23 04:19:43 [9ed8f6bd946af07550902117955ee9af758ce23292625bd274d33937f3feffda]
archive-2017-07-30_0230              Sun, 2017-07-30 04:47:11 [84256d7c6ec2f64b49eed666fbc05b46fea0a4b86fc3c3a32a5c9654fe1b2525]
archive-2017-07-31_0230              Mon, 2017-07-31 04:39:44 [0b75100584bad6914de8173fec00a81e1db8ea2e67dafb6947d1a169ba5e6c58]
archive-2017-08-06_0245              Sun, 2017-08-06 05:06:32 [925891240e0df2fa013ec14e45297c6aefc1426d7077059adaea2ad188ab0a0b]
archive-2017-08-13_0251              Sun, 2017-08-13 05:20:40 [9290cb3f24b5172c41214e911adab462ba45ddcd3ab624a623f861186cbeb316]
archive-2017-08-20_0307              Sun, 2017-08-20 05:43:07 [509c4077de52fb62ad65d8f30197f4246dd2fc9157c2ee20df5ee74438e5f32d]
archive-2017-08-27_0314              Sun, 2017-08-27 06:29:34 [c0ec19130bb2905e931a2a552008c6897af2e0e83d630d4429289f9912e1dcda]
archive-2017-08-31_0458              Thu, 2017-08-31 08:09:37 [0991b19bb9063be0433e5e8babc8b1ed383a6a20fd762aba0b1bf03bd76c718e]
archive-2017-09-03_0321              Sun, 2017-09-03 06:34:45 [af029f48e11000649b1d6d920c45b14e135ac7787a23614f6e9529112d6ddb58]
archive-2017-09-10_0309              Sun, 2017-09-10 06:13:18 [6484723207d646bb43d786d4cd969dd109e90bcddc35837bbee55dd4b638b269]
archive-2017-09-13_0448              Wed, 2017-09-13 08:44:19 [a1f505bacf7911b13fb25a3d45089c89bc2078b9d414fd3fb326953a246325be]
archive-2017-09-14_0601              Thu, 2017-09-14 09:19:54 [9a1824a5e3d304848d5523f77511db0b613c4f3d4125a8c7df403f931d6868d7]
archive-2017-09-15_0537              Fri, 2017-09-15 09:36:00 [124c5c53975de0e24126a0d0e93929c7cbd5c2b6da19487b5e2c915c10225fe9]
archive-2017-09-16_0532              Sat, 2017-09-16 09:37:26 [eeea41fe7f68cd38fff7351881e1eeb27e5b93815d3a264a0170ab2913d8b650]
archive-2017-09-17_0328              Sun, 2017-09-17 06:40:46 [ad6309cb6e8c62fb6b533692cc6736467edac1bef665de676f45ef83e9a432ae]
archive-2017-09-18_0318              Mon, 2017-09-18 06:01:17 [1392d276526d034f4df70c025bd13479086ec697a31e7e26f9ce0eba4a6b9321]
archive-2017-09-19_0555              Tue, 2017-09-19 09:47:32 [fa023c9c1105ad59d0b9dedc5d11863bd5f2b49a60d3003acf15a3ef1c1b254a]
archive-2017-09-20_0522              Wed, 2017-09-20 09:28:37 [1fa392affd4c26cd1170fbcc5a4d382be7cf631028794e95df2cc3cac8497f87]
archive-2017-09-21_0527              Thu, 2017-09-21 08:46:53 [0d5bb5bbf890352406d076e2bfd4ac2be0af9dcb7d8d651a22dbb712b5d6fdc8]
archive-2017-09-22_0532              Fri, 2017-09-22 09:12:06 [4142912734b4d7dad1c40d969b13082bd07eb88d22cf41a26b701b5791146f86]
archive-2017-09-23_0626              Sat, 2017-09-23 11:09:46 [8dad8a62a2eb2d5351f0278df4b6912e0ba8eafc823ab713c9c8a1bd6ed673a3]
archive-2017-09-24_0312              Sun, 2017-09-24 06:23:39 [e0b4c3aaae37203de0c16e280e5b09e75af61c72a107d08aa9d3cfa0318ddb69]
archive-2017-09-25_0321              Mon, 2017-09-25 06:01:57 [76917002b7cd62bedcf383c9f06e8bc8afe72d8e02d440386be9b7b46279f070]
archive-2017-09-26_1338              Tue, 2017-09-26 17:12:50 [5ce26a5ff0e14244bbd07459a2c4fa59ce00717286709d52692aa9db25c67f5e]
archive-2017-09-27_0808              Wed, 2017-09-27 11:53:46 [f199f44d24ca2b615797f65dc5eff35f7de0d570828c96e420460ffc5f953c19]
archive-2017-09-28_0427              Thu, 2017-09-28 07:33:58 [0fa63c82a6067e0e1a425dbc9afbfd471bcb9e2a143f4f98fe8a71b4e756e748]
archive-2017-09-29_0501              Fri, 2017-09-29 08:21:15 [f1c25257b8fd6160fed495550b8a5ad1a362465a792769385d53d7e049175227]
archive-2017-09-30_0527              Sat, 2017-09-30 09:38:47 [79c1d1576e78f27676604cc7a027bbc73c64e9433b74290454bd02b321d38145]
archive-2017-10-01_0307              Sun, 2017-10-01 06:51:10 [b4e99819a0826e3238a7c1ece1c8dad8c54e93d3aa1908c204b694aa4c6e95de]
archive-2017-10-02_0316              Mon, 2017-10-02 05:57:44 [b31995e8b96cfe82e8192597962cd8e655b53b9380dd5f7b5e83fd2e811a6c2c]
archive-2017-10-03_0502              Tue, 2017-10-03 08:45:34 [af29580f26d24ef3c3efe1cb5621119e8fff7ba13921e603e89065e7ab5b4c5e]
archive-2017-10-04_0435              Wed, 2017-10-04 08:18:03 [dad3ecf260b587e386b58025247418b63c5cf60fee3dfbcb78d7b5267a596c9e]
archive-2017-10-05_0448              Thu, 2017-10-05 08:21:21 [da97a44cc4e1f3be9fd5ff543a12e1504267390ff85c7c06dfd603619d5b8b55]
archive-2017-10-06_0406              Fri, 2017-10-06 07:37:07 [d2eec56e3ac26eaa38b85f24a12023a314b97d9f55b9384775bdbd6d98f4c382]
archive-2017-10-07_0553              Sat, 2017-10-07 10:22:05 [ea3a681101bf6e26cb6131d8c96a6d8ff2de0cec5f52a522c5d1e991d2277cd4]
archive-2017-10-08_0309              Sun, 2017-10-08 06:30:28 [bae98dec7eeb14b386d92a74836b04afef3a56b07c857457c6e2037e90d20f84]
archive-2017-10-09_0316              Mon, 2017-10-09 05:58:55 [f8610825bc1f3a209262d7f914c937c9e099345fbe113c2620c2d784f1056a3f]
archive-2017-10-10_0526              Tue, 2017-10-10 08:59:23 [5690015379799a6d6bf11f32905a3bc28da73910ada31242ed1fb50b1d3d36a2]
archive-2017-10-11_0427              Wed, 2017-10-11 08:14:47 [add7212329770f096df83523bb22d5fc2c1931508f60144675958ca9eb6dfd50]
archive-2017-10-12_0601              Thu, 2017-10-12 09:33:23 [1cdb40327f6a5d0253a6724d7368de79c0fb282c5c68f8ff79add8db557c8222]
archive-2017-10-13_1513              Fri, 2017-10-13 15:13:51 [aaf54ca4430fc752b0ac224f395ebb061e5a46bac8c6a93d795824d026acdc78]
archive-2017-10-13_1522              Fri, 2017-10-13 15:21:31 [ae0780bca863f92b399b4f6b7487a804a64be79bfcaa1d7d7f8474699f67f862]
archive-2017-10-13_1523              Fri, 2017-10-13 15:22:33 [dfa25ce100b44716a7beb2b8d8dd73996d8d57246869c47dc55be0b671dd7c8a]
archive-2017-10-13_1524              Fri, 2017-10-13 15:23:40 [9537573ee39bf652d41cb17028399e8e704b4551496e9bb013974a4cbd808f87]

**Comment by ThomasWaldmann** [comment]
note: shortened the archive list in above posts, not important for the issue.

@devZer0 can you reproduce the issue with a fresh repo and post the commands / borg versions needed for that?

**Comment by ThomasWaldmann** [comment]
The line marked with XXX raised the exception:
```
    def assert_key_type(self, key, cache_config=None):
        # Make sure an encrypted repository has not been swapped for an unencrypted repository
        if cache_config and cache_config.key_type is not None and cache_config.key_type != str(key.TYPE):
            raise Cache.EncryptionMethodMismatch()
        if self.known() and not self.key_matches(key):
            raise Cache.EncryptionMethodMismatch()   # XXX
```

**Comment by ThomasWaldmann** [comment]
Just seen that you already posted that. The culprit is the key-type file with 0 length.

Would be interesting if you could reproduce that.

**Comment by ThomasWaldmann** [comment]
As all of these files are 0 bytes: did you run out of disk space?

**Comment by ThomasWaldmann** [comment]
Guess we should use platform.SafeFile for these files.

**Comment by SR-G** [comment]
System upgraded yesterday (archlinux) to borg 1.1.0 and i can say i have the same problem. My backups are on an external HDD which works fine (always connected, no "disk space full", no errors, no system crashes). At first glance reverting to borg 1.0.4 seems OK (backups probably not corrupted).

`
borg list $REPO
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] y
2017-04-30                           Sun, 2017-04-30 02:00:03 [c8ba11c30faaa2a6a0cbbf4d0600fbf940e333a2ed8b68e375afb563f47ee88a]
2017-05-31                           Wed, 2017-05-31 02:00:12 [479b9457111cf134fffeaf16a904df5f1f42b4260a16bb23c5cdbd31d3900eb6]
`

**Comment by enkore** [comment]
When reading, ignore zero-length files.

**Comment by enkore** [comment]
What @SR-G says looks more like an actual logic bug, though.

**Comment by alphazo** [comment]
Similar to @SR-G, when upgrading to 1.1.0 on ArchLinux I got prompted with the "unknown unencrypted repository". For information my backups are not encrypted since they are stored on a FDE NAS that I have under tight control. The issue appeared with two repositories, one that is backing up an external hard drive to an internal mergerfs array that has plenty of space and the other one from a remote laptop to the same NAS. When I got the question the first time with the external drive it then took 2 days to perform the backup even if no data have changed. Sounds like all the files have been at least 100% hashed. I don't know if I want to do the same on the laptop since it will take many hours to perform something similar to a first run backup.

**Comment by ThomasWaldmann** [comment]
About slow first 1.1.0 backup: there is another ticket, read it and discuss there, please.

**Comment by ThomasWaldmann** [comment]
@alphazo about the "unknown unencrypted repo" message: 1.0 does not have the security dir (yet?), so you have to answer that message once (either manually or via env var).

borg 1.1 will remember your answer and initialize the files in the security dir and won't ask again then.

if you operate unencrypted repos, this is a rather harmless question, but not if you operate encrypted repos: if they are suddenly unencrypted, someone might be attacking you.

**Comment by alphazo** [comment]
@ThomasWaldmann Thanks for the great explanation on both the uncrypted repo and performance issue related to the way new files are detected. Everything seems to be fine on my side now.
