### ISSUE TITLE
switch off nodump behaviour or bsdflags

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3160]
we already had some issues with that:
- unraid showing uninitialized/random bsdflags #3127
- macOS shares showing nodump in general #2949
- the linux bsdflags support needs to open the fs item.
  - slowdown due to the extra open/ioctl?
  - also there was a bug with opening non-present device files. #3130

so, add a `--ignore-nodump`? (double negation, not nice, rather `--honor-nodump` for the opposite?

or even a `--no-bsdflags` to skip reading / archiving bsdflags in general?

both?

**Comment by ThomasWaldmann** [comment]
about `--honor-nodump`:
- borg < 1.1.0: did not care about nodump, this just backed up everything
- borg 1.1.0: honored nodump, so did not back up stuff with nodump set (no matter whether this was intentional or just a bug, see top post)
- borg 1.1.1: we could go back to the < 1.1.0 behaviour by adding a `--honor-nodump` flag and not honoring nodump by default.

**Comment by enkore** [comment]
> borg < 1.1.0: did not care about nodump, this just backed up everything

Only on Linux, since BSD flags have been supported since forever with the BSD API.
