### ISSUE TITLE
back up atime and ctime

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#317]
after reviewing [this documentation](https://borgbackup.readthedocs.org/en/latest/faq.html#can-i-backup-from-multiple-servers-into-a-single-repository) i noticed that only modification times were backed up in borg/attic ([source](https://github.com/borgbackup/borg/blob/master/borg/archive.py#L431)). 

is that on purpose? if so, why?

it seems it would be worthwhile to also index the access time, at the very least - and ctime can be valuable during forensics as well...

**Comment by ThomasWaldmann** [comment]
iirc, you can't restore them anyway.

**Comment by anarcat** [comment]
On 2015-10-20 13:26:08, TW wrote:
> iirc, you can't restore them anyway.

atime can certainly be restored:

```
[994]anarcat@marcos:test$ stat foo
  Fichier : « foo »
   Taille : 0           Blocs : 0          Blocs d'E/S : 4096   fichier vide
Périphérique : fe04h/65028d     Inœud : 3707433     Liens : 1
Accès : (0644/-rw-r--r--)  UID : ( 1000/ anarcat)   GID : ( 1000/ anarcat)
 Accès : 2015-10-20 13:28:00.342574329 -0400
Modif. : 2015-10-20 13:28:00.342574329 -0400
Changt : 2015-10-20 13:28:00.342574329 -0400
  Créé : -
[995]anarcat@marcos:test$ touch -r / foo
[996]anarcat@marcos:test$ stat foo
  Fichier : « foo »
   Taille : 0           Blocs : 0          Blocs d'E/S : 4096   fichier vide
Périphérique : fe04h/65028d     Inœud : 3707433     Liens : 1
Accès : (0644/-rw-r--r--)  UID : ( 1000/ anarcat)   GID : ( 1000/ anarcat)
 Accès : 2014-05-14 19:03:45.973953996 -0400
Modif. : 2015-09-28 21:35:32.555686445 -0400
Changt : 2015-10-20 13:28:07.362656450 -0400
  Créé : -
```

As for ctime, it's *possible* to "restore" it through various hacks, but
none that seem to make sense to me. What I have read ranges from:

* changing the clock
* patching the kernel
* changing the filesystem directly

All seem a little nuts, and leaving the ctime as-is actually makes sense
on restore, as we do change the file...

However, i think it could still be useful to *store* it, as we could
inspect it through the FUSE mountpoint, for example... Then it can be
used to check for inconsistencies or issues...

**Comment by anarcat** [comment]
(wtf github, why isn't markdown supported by email?)

source of the ways to change the ctime: http://stackoverflow.com/questions/4537291/setting-creation-or-change-timestamps

**Comment by ThomasWaldmann** [comment]
no, we won't change the clock or patch the kernel or change fs directly.

about saving atime and ctime: yes, that seems reasonable. we just need to be careful to not change it before "reading" it.

**Comment by anarcat** [comment]
> no, we won't change the clock or patch the kernel or change fs directly.

of course, i wasn't suggesting that. :)

> about saving atime and ctime: yes, that seems reasonable. we just need to be careful to not change it before "reading" it.

i believe that was fixed in attic a while back, see https://github.com/jborg/attic/pull/113

i guess the next step here is to add atime and ctime to the archive creation, and atime to extraction.

**Comment by ThomasWaldmann** [comment]
yup. os.utime().
