### ISSUE TITLE
Performance degradation even for `borg -V` after upgrading to 1.1

### ISSUE THREAD

**Issue by wzyboy** [borgbackup/borg#3171]
Hi,

I encountered a strange bug after upgrading all my Borg installations from 1.0.11 to 1.1.0: one of the installation became extremely slow even for simple calls like `borg -V`:

```
# Before upgrading:
$ yaourt -U /var/cache/pacman/pkg/borg-1.0.11-1-x86_64.pkg.tar.xz
[...]
$ time borg -V
borg 1.0.11

real	0m0.200s
user	0m0.190s
sys	0m0.011s


# After upgrading:
$ yaourt -U /var/cache/pacman/pkg/borg-1.1.0-1-x86_64.pkg.tar.xz
[...]
$ time borg -V
borg 1.1.0

real	0m2.295s
user	0m0.226s
sys	0m0.020s

```

I installed Borg from official Arch Linux repository. **However, out of my three Arch Linux installations, only one of them encountered this performance degradation.**

Here is the output of `python -m cProfile /usr/bin/borg -V`: https://pastebin.com/raw/mztsxgVS

Is there something suspicious in the cProfile output?

**Comment by enkore** [comment]
Try `strace -r` or -T to see which syscall causes the slowdown. I'll place a bet on [platform.posix](https://github.com/borgbackup/borg/blob/master/src/borg/platform/posix.pyx#L21).

**Comment by wzyboy** [comment]
@enkore 

Exactly! It's `socket.getfqdn()` that makes startup time 2s+ long. The Arch Linux node in question does not have an entry pointing to its own hostname in `/etc/hosts` while the other two nodes have. After adding an entry pointing to its own hostname into `/etc/hosts`, the `socket.getfqdn()` call does not block for 2 seconds any more and `time borg -V` now gives expected results.
