### ISSUE TITLE
repo compaction progress suddenly shown

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3173]
from irc user adhawkins:

I've been using borgbackup for a few weeks now, backing up 3 servers to two different accounts at rsync.net.

Recently, one of the servers (the only one that's using one of the accounts at rsync.net) has been adding lines like this to the output:

```
borg.output.progress Remote: Compacting segments   6%
(the percentage counts up to 100% in the log).
```

Is there any way to prevent this?
I'm seeing the same entries in both borg create and borg prune output.

**Comment by adhawkins** [comment]
Full borg command:

> borg create --remote-path borg1 -v --stats --exclude-caches user@host.rsync.net:{hostname}::{now:%Y-%m-%d-%H-%M-%S} --exclude-from /root/.borgbackup/excludes /etc /root /srv /home /usr/local /var/mail /var/lib/dpkg /var/spool/cron /var/backups/mysql /var/backups/postgresql

Local version is 1.0.9. Remote version is 1.1.0.

On the servers that *aren't* generating that logging, the remote end is on 1.1.1, local is also 1.0.9

**Comment by adhawkins** [comment]
Updating local version to 1.1.0 removes the message. 1.0.11 locally with 1.1.0 remotely also generated the messages.

**Comment by ThomasWaldmann** [comment]
- 1.0 does not have progress-showing code for the compaction

**Comment by ThomasWaldmann** [comment]
AFAICS, this works as expected.

**Comment by ThomasWaldmann** [comment]
Same "problem" is also there for `borg check` progress messages with borg 1.0.

**Comment by ostcar** [comment]
Could you explain once more, how I can remove remove "Compacting segments" output on a 1.0 client but still get the `--stats` output?

On my backup machine I have archlinux (borg=1.1.4) and I want to backup an ubuntu 16.04 server (borg=1.0.11). I would like to install borg from the package-manager so it is not possible to change the borg version to 1.1 on the ubuntu server.

Also, I would like to have the log output like this:

```
Archive name: client-full-2018-02-27_02:33 
Archive fingerprint: 9caaa972d8f8af9823a31113c70c76a8270d555f3bb51a8cecd33
Time (start): Tue, 2018-02-27 03:33:47
Time (end):   Tue, 2018-02-27 04:20:08
Duration: 46 minutes 21.45 seconds
Number of files: 290773
```
When I use the `-v` argument, I also get hundred lines of `borg.output.progress Remote: Compacting segments ...` in my log. If I don't add the `-v` argument, `--stats` argument does not work anymore.

Wouldn't it be possible to write the compacting segments message only at DEBUG level or show the `--stats` output, even when the log level is below INFO?

**Comment by ThomasWaldmann** [comment]
@ostcar iirc, you can get 1.1.4 for xenial from locutusofborg's ppa.
