### ISSUE TITLE
error on borg create after update to 1.1.0

### ISSUE THREAD

**Issue by corppneq** [borgbackup/borg#3183]
The remote (server) is a Debian machine where only 1.0.9 is available. My expectation is that no exception gets raised.

```
Remote: Borg 1.0.9: exception in RPC call:aPathYeahHereWasAPath                                                                       
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 108, in serve
Remote:     raise InvalidRPCMethod(method)
Remote: borg.remote.InvalidRPCMethod: get_free_nonce
Remote: Platform: Linux theNameOfTheServer 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64
Remote: Linux: debian 9.2 
Remote: Borg: 1.0.9  Python: CPython 3.5.3
Remote: PID: 1285  CWD: /home/theUsername
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--info']
Remote: SSH_ORIGINAL_COMMAND: None
Remote: 
Please upgrade to borg version 1.1+ on the server for safer AES-CTR nonce handling.
```

**Comment by corppneq** [comment]
manually updating borg to 1.1.0 fixes the issue

**Comment by enkore** [comment]
That's not an error, but rather a very poorly conveyed warning.

**Comment by trou** [comment]
Hitting the same "problem", it is quite annoying as the message pollutes logs and crons.

is it be possible to hide the warning ?

**Comment by ThomasWaldmann** [comment]
No, sorry. It will go away when you upgrade the server side borg.

**Comment by trou** [comment]
Yes but I can't...

**Comment by ThomasWaldmann** [comment]
@trou the binaries from gh releases page should work on almost any linux/freebsd/osx.

**Comment by enkore** [comment]
If it were straightforward to hide the ugly message inside Borg we'd just have done that, but doing that would be a pretty big mess (more than now, anyhow) in the code.

**Comment by trou** [comment]
OK, thanks for the explanation :)

**Comment by enkore** [comment]
But maybe the message could be expressed more clearly, especially that you can totally ignore these "Remote:" lines in this instance.
