### ISSUE TITLE
borg serve should detect stale locks and remove them.

### ISSUE THREAD

**Issue by darkskiez** [borgbackup/borg#3187]
When a lock is created it contains the host/pid that created it. When a borg serve instance is started on that host it should be able to check if the locks are stale (eg. pid is gone) and remove them if so. If the locks are from another host they should be left.

(Also, If I incorrectly borg break-lock, the running borg instance could probably periodically check it still has the lock before it does any damage... how much damage is possible? does it ever check it still has the lock?)

(Ideally the repository locks shouldn't be held for the whole backup and only during some critical metadata operations, but that's a different issue as I don't yet know enough about the repository format / architecture)

**Comment by ThomasWaldmann** [comment]
borg 1.1 has stale lock detection and removal (as far as safely possible).

I don't think periodical checks are very useful, because damage could be done at any time.

We already have a ticket about more fine grainer locking, so I'm closing this one.
