### ISSUE TITLE
Parsing of URL with port and ~user fails

### ISSUE THREAD

**Issue by fredleb** [borgbackup/borg#3188]
`borg init -e=none backup@daffy:9200/~backup/repos/pandarch/home`

leads to 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/users/backup/9200/~backup/repos/pandarch/home'`

Also tried:
`borg init -e=none backup@daffy:9200/~/repos/pandarch/home`
`borg init -e=none backup@daffy:9200/repos/pandarch/home`

Why is the port number landing into the repo path ?
Why is ~backup resolved but then still in the repo path ?
Or is my repo URL wrong ?

borg 1.1.0 on armvh7, arch linux

**Comment by ThomasWaldmann** [comment]
Giving a port is not supported by the user@host syntax, use ssh://... syntax.

**Comment by fredleb** [comment]
Oh yeah... completely missed that in the doc...

Thanks !
