### ISSUE TITLE
Exclusions from --exclude-if-present should appear in --list

### ISSUE THREAD

**Issue by HadrienG2** [borgbackup/borg#3189]
Currently, when `--exclude-if-present` is used, the excluded folders do not appear in the exclusion log produced by `--list --filter x`. This is inconsistent with the behaviour of `--exclude`, and makes it harder to debug exclusion patterns based on this technique.

**Comment by ThomasWaldmann** [comment]
Yeah, sounds reasonable. We'll have a look at that.

**Comment by ThomasWaldmann** [comment]
Note: also applies to --exclude-caches (CACHEDIR.TAG special case).

**Comment by HadrienG2** [comment]
That looks pretty good!
