### ISSUE TITLE
log output 1.0.x client -> 1.1.0 server

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3195]
```
$ borg-1.0.6 create -v tw@localhost:repo::test input
borg.output.progress Remote: Compacting segments   0%
borg.output.progress Remote: Compacting segments  50%
borg.output.progress Remote:
```

Same for 1.0.11 client.

The unusual `borg.output.progress` at the left is the logname included by the server and unexpected to show up there for a 1.0 client.

**Comment by ThomasWaldmann** [comment]
1.0 client supports these server log line formats:
```
$LOG <level> Remote: <msg>    # output via logging at level: "Remote: <msg>", line ending stripped
msg                                            # output via stderr with "Remote: " prepended, line ending preserved
```

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.1.0/src/borg/logger.py#L92 there it includes the logname.

**Comment by enkore** [comment]
Should work

**Comment by ThomasWaldmann** [comment]
another issue: this is progress log output, so it should not be output at all (except with --progress).

**Comment by ThomasWaldmann** [comment]
removing from milestone, this problem solves automatically as people upgrade to 1.1.x.
