### ISSUE TITLE
No documentation for "--stats"

### ISSUE THREAD

**Issue by kbabioch** [borgbackup/borg#3210]
In general the documentation of borg is very good and extensive. However I couldn't find any definitive information about the `--stats` parameter. I've seen it used all over the place and I see what it does, however the man page does not mention it.

**Comment by kbabioch** [comment]
I've just realized that it is documented [here](https://github.com/borgbackup/borg/blob/master/docs/man/borg-create.1#L90). However my distribution does not contain any man page (besides borg itself). What is a distribution supposed to install? Or is this getting included somehow?

**Comment by ThomasWaldmann** [comment]
well, distributions can choose to install whatever the packager deems fit.

but that said, maybe the packager did not notice yet that we have a bunch of man pages he could just use (these were not there in older borg versions).

**Comment by ThomasWaldmann** [comment]
also, the cli usage information in the man pages and in the html online docs should be equivalent because they are both created automatically from ArgParser (python code).

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/create.html#borg-create < also mentioned there.
