### ISSUE TITLE
borgbackup opening devices while backing up.

### ISSUE THREAD

**Issue by darkskiez** [borgbackup/borg#3213]
This _may_ be a linux kernel bug instead / aswell, but I needed to start somewhere

borgbackup reliably causes modules to get loaded whilst its backing up my system..

I have a dev tree outside of /dev from some old docker installations that seemingly trigger this when they are walked over by borg.

[  251.621693] brd: module loaded
[  281.337353] st: Version 20160209, fixed bufsize 32768, s/g segs 256
[  281.362408] usbcore: registered new interface driver cdc_acm
[  281.362409] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters

I'm not sure what operation is causing these to get loaded yet... but it managed to oops my kernel, more than once with a similar trace (that makes no sense) that looks like btrfs xattr operations may lead to a device open, however, trying this by itself with xattr -l <device> doesn't seem to reproduce this..

Segmentation faultC 3.96 GB D 7511970 N home/docker/aufs-dead/diff/72e10143e54ab6d...67327e94d134908cea1b5aaa846c92c12a1e/dev/ttyb2

Linux version 4.13.0-1-amd64 (debian-kernel@lists.debian.org) (gcc version 6.4.0 20170920 (Debian 6.4.0-7)) #1 SMP Debian 4.13.4-1 (2017-10-01)
Trace: https://pastebin.com/uB7tvPMf

**Comment by FabioPedretti** [comment]
Which borg version are you using? If 1.1.0 try with 1.1.1.

**Comment by ThomasWaldmann** [comment]
The bsdflags support code in 1.1.0 opened all fs items (including device files) to do a syscall on them (not: read them).

This is fixed in 1.1.1, block and char device files are excluded there.
