### ISSUE TITLE
How to use pattern to include or exclude folders?

### ISSUE THREAD

**Issue by de1m** [borgbackup/borg#3223]
Hi,
I've download the latest version of borg and I use ubuntu16.04.
Example
```bash
ubuntu@ubuntu-xenial:/nodejs$ ll
total 40
drwxrwxrwx  1 root root 4096 Oct 26 11:28 ./
drwxr-xr-x 27 root root 4096 Oct 26 07:27 ../
drwxrwxrwx  1 root root 4096 Sep  7 13:37 checkport/
drwxrwxrwx  1 root root 4096 Oct 19 11:58 dockerGetInfo/
drwxrwxrwx  1 root root 4096 Aug 17 09:53 kubeApiTest/
drwxrwxrwx  1 root root 4096 Oct 25 13:34 kubeCLweb/
drwxrwxrwx  1 root root 4096 May 10  2016 liste/
drwxrwxrwx  1 root root 4096 Oct 24 12:14 nodebackup/
drwxrwxrwx  1 root root 4096 Jun 22  2016 vmwareInvent/
drwxrwxrwx  1 root root 4096 May 23  2016 vpnVMListe/
```
This is my folder. I'll create backup only of nodebackup and liste, how can I do this?

**Comment by infectormp** [comment]
did you read https://borgbackup.readthedocs.io/en/stable/usage/create.html?

**Comment by de1m** [comment]
@infectormp yes, I've, but I don't undestood how I can use this to include two folders and exclude all another?

**Comment by infectormp** [comment]
@de1m 
here is two examples:
`borg create /path/to/repo::my-files /nodejs/nodebackup /nodejs/liste`
or
create CACHEDIR.TAG in all folder expect nodebackup and liste then
`borg create --exclude-caches /path/to/repo::my-files /nodejs/nodebackup /nodejs/liste`

or you can play with other borg options to get backup schema that will satisfy you

**Comment by de1m** [comment]
I need this with the patterns, because I'll create this command automatically (with a node script)

**Comment by de1m** [comment]
Okay, I've found
```bash
borg create -p --json --pattern "+ /nodejs/liste" --pattern "+ /nodejs/nodebackup" --pattern "- /nodejs/**" /dup/nodejs::mon1 /nodejs
```
