### ISSUE TITLE
wrong original size in borg create

### ISSUE THREAD

**Issue by GiuseppeArvati** [borgbackup/borg#3224]
Hello,
[borg 1.1.1  python 3.4.5 CentOs 6]
I tried 2 times with same command but different files ( oracle dump ) and both times I had
an original size reported twice bigger than the real one.
The file is 109 GB.
I tried even with smaller files but the problem did not appear.

```
# borg create -p --stats /opt/mnt/test.borg::test2 ads_orcl_daily_dmp_5
------------------------------------------------------------------------------
Archive name: test2
Archive fingerprint: ba34d3cb846d521388a14ea5cf1b9a8addb114de386a042738b99fac01e48a42
Time (start): Thu, 2017-10-26 12:33:18
Time (end):   Thu, 2017-10-26 13:33:38
Duration: 1 hours 20.12 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              232.90 GB            205.06 GB            102.53 GB
All archives:              232.90 GB            205.06 GB            102.53 GB

                       Unique chunks         Total chunks
Chunk index:                   44512                89022
------------------------------------------------------------------------------
```
giuseppe

**Comment by milkey-mouse** [comment]
I have the same issue. I thought it was the [bind mounts](https://github.com/milkey-mouse/backup-vm/blob/fe2174d75e7d86f3845a71cec6d152f7a2f36ed6/backup-vm.py#L518) in my archived folders that were causing it, but from this report it doesn't look like it.

**Comment by ThomasWaldmann** [comment]
Archiving a directory with a single 100MiB file (containing zeros) creates these stats:
```
                       Original size      Compressed size    Deduplicated size
This archive:                1.22 kB                671 B                671 B
All archives:              104.86 MB            412.05 kB             50.04 kB
```

**Comment by ThomasWaldmann** [comment]
I'll try with a bigger file later...

**Comment by ThomasWaldmann** [comment]
The "original size" doubles when a checkpoint is happening in the respective file.
Cosmetical bug, the chunks are referenced by the parts AND by the full file and both is going into the statistics.
