### ISSUE TITLE
--keep-tag-files for borg list?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3226]
From SanskritFritz (IRC):
```
in the docs there is --keep-tag-files for borg list.
A result of copy-paste or is there a point?

same with borg diff.
```

Note: maybe a global option? check whether it is better to make it a local option. check which branches are affected.

**Comment by SanskritFritz** [comment]
How about borg diff? Is the option used there?

**Comment by ThomasWaldmann** [comment]
ah, forgot that. fixing...

**Comment by SanskritFritz** [comment]
How is the documentation fixed then? Is it generated or do you have to fix it manually? (I can make a PR if it involves only manual text editing).

**Comment by ThomasWaldmann** [comment]
the docs and man pages are created from the code, no manual work needed.

**Comment by SanskritFritz** [comment]
OK, thanks. Also I have my doubts about --exclude-if-present as well. What do you think?

**Comment by ThomasWaldmann** [comment]
the changes remove these from diff and list:

```
$ borg list --help
...
  --exclude-caches      exclude directories that contain a CACHEDIR.TAG file
                        (http://www.brynosaurus.com/cachedir/spec.html)
  --exclude-if-present NAME
                        exclude directories that are tagged by containing a
                        filesystem object with the given NAME
  --keep-exclude-tags, --keep-tag-files
                        if tag objects are specified with ``--exclude-if-
                        present``, don't omit the tag objects themselves from
                        the backup archive
```

**Comment by SanskritFritz** [comment]
Ah sorry for the noise. I'll update the shell completions accordingly.
