### ISSUE TITLE
Can't find a way to list or export latest backup

### ISSUE THREAD

**Issue by EthraZa** [borgbackup/borg#3237]
Can't find a way to tell borg to "use" the latest backup without explicit knowing its name:

`borg list --last 1 repo::?`
`borg export-tar --last 1 repo::? bkp.tgz`

Is it possible? 
If so, it's missing an example, if not, it's a wish.

**Comment by ThomasWaldmann** [comment]
```
A=`borg list --short --last 1 repo`
borg list repo::$A
```

**Comment by EthraZa** [comment]
I was hoping that --last/first 1 would generate some variable like {hostname}/{now}, maybe just {1}. 
But, since I'm creating my server backup script, a shell way will do.

Thank you.
