### ISSUE TITLE
add version and some system data to log / tracebacks

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#324]
when we get bug reports, one often has to explicitly ask for the version, OS, arch, etc.

this could be logged into log file when borg starts and also be shown at the top or bottom of tracebacks.

**Comment by anarcat** [comment]
i think this something that logbook does, which i mentionned in https://github.com/borgbackup/borg/issues/302#issuecomment-149343414...

it's the "fingers crossed" mechanism:

https://pythonhosted.org/Logbook/features.html#core-features

> There is also a special “fingers crossed” handler that, in combination with the handler stack, has the ability to accumulate all logging messages and will deliver those in case a severity level was exceeded. For example, it can withhold all logging messages for a specific request to a web application until an error record appears, in which case it will also send all withheld records to the handler it wraps. This way, you can always log lots of debugging records, but only get see them when they can actually tell you something of interest.
