### ISSUE TITLE
store num_files (...) in archive

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3241]
https://github.com/borgbackup/borg/pull/2764#issuecomment-312749568

**Comment by enkore** [comment]
If you want to do `borg info` mostly on the client, using the cached archive index, then this has to be stored in the archive meta data. #3128.

**Comment by ThomasWaldmann** [comment]
Note: to support `borg info [--consider-part-files]`, we need `num_files_totals` and also `num_files_parts`.

https://github.com/borgbackup/borg/pull/4286
