### ISSUE TITLE
Use archive timestamp for pruning instead of name

### ISSUE THREAD

**Issue by NiklasMM** [borgbackup/borg#3243]
This seems so obvious, that there's probably a good reason that prevents it, but why is the archive name used for the pruning instead of the actual timestamp?

Now, if a user wants to use pruning, they have to include the `{now}` placeholder in their archive names (granted, it's a good practice, but still...).

Why not use the timestamp from the archive metadata? It just feels cleaner.

Instead of using a prefix to identify a subset of archives, users could provide a regex, which is a bit more powerful.

**Comment by alejandro-perez** [comment]
AFAIK borg behaves the way you mention. You don't need to provide the name. You could create:
* /tmp/repository::test1
* /tmp/repository::test2
* /tmp/repository::test3

And borg prune will work based on their actual timestamps, regardless you put the name on it or not.

**Comment by NiklasMM** [comment]
Whoops. You're totally right. [It does](https://github.com/borgbackup/borg/blob/master/src/borg/helpers/misc.py#L52)

I feel a bit stupid now and will close the issue in shame.
