### ISSUE TITLE
1.1.1 gives a BrokenPipeError when sending output to | less

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#3245]
With 1.1.1 when I run `borg list | less` I get this exception. It works fine on 1.0.11.

> Local Exception
> Traceback (most recent call last):
>   File "borg/archiver.py", line 4049, in main
>   File "borg/archiver.py", line 3977, in run
>   File "borg/archiver.py", line 148, in wrapper
>   File "borg/archiver.py", line 1356, in do_list
>   File "borg/archiver.py", line 1399, in _list_repository
> BrokenPipeError: [Errno 32] Broken pipe
> 
> Platform: Linux borg 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64
> Linux: debian 9.2
> Borg: 1.1.1  Python: CPython 3.5.4
> PID: 1956  CWD: /root/borg-script/1.1
> sys.argv: ['./borg-1.1.1', 'list']
> SSH_ORIGINAL_COMMAND: None
> 
> Exception ignored in: <_io.TextIOWrapper name='<stdout>' encoding='UTF-8'>
> BrokenPipeError: [Errno 32] Broken pipe

**Comment by ThomasWaldmann** [comment]
check: #790 #1151 #1379

**Comment by ThomasWaldmann** [comment]
in archiver.main, we have these:
```
    sys.stdout = ErrorIgnoringTextIOWrapper(sys.stdout.buffer, sys.stdout.encoding, 'replace', line_buffering=True)
    sys.stderr = ErrorIgnoringTextIOWrapper(sys.stderr.buffer, sys.stderr.encoding, 'replace', line_buffering=True)
```
