### ISSUE TITLE
borg prune and files-cache

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#3248]
After 

```
borg prune ./${path} -v -s --list --keep-daily=3 --keep-weekly=2 --keep-monthly=2  --keep-within 9d
```
files-cache is created. Should it be so? Is there way not to use it with prune?

I do `borg prune` from storage server side (it's separate remote server) with slow HDDs, so there is no cache in the beginning from this side.

borg 1.1.1

**Comment by ThomasWaldmann** [comment]
prune is like delete: it needs the chunks cache, but does not use the files cache.

so, what do you mean? it creates an "empty" files cache?

**Comment by knutov** [comment]
Oh, not sure, are files cache and chunk cache different things? 

Is it really not possible to delete/prune without writing any caches to disk?

**Comment by ThomasWaldmann** [comment]
The chunks cache is where borg keeps the reference-count information for all the chunks - it is essential so it can know which chunks it can delete (when refcount == 0).

**Comment by knutov** [comment]
ok then , after `borg prune` I have those files:

```bash
$ cd ~/.cache/borg/33d71ce4c1d350a946d424a14871507d68cdb2bd9be78e9eeba1da9f03951a98
$ ls -1
README
chunks
chunks.archive.d
config
files

$ du -hs chunks.archive.d
17M	chunks.archive.d
```

and there are a lot of files named `01c7e03ae623c9e180156066e40e670f25ffe89e74eb4f27ec588f28d7cb183b.compact` with size 1.9M inside

folder `chunks.archive.d` can be big and I have a lot of repos - so all this caches uses gigabytes on disk.

~/.cache/borg/ was cleared before `borg prune`.

Is everething ok there?

**Comment by knutov** [comment]
I mean, if it's only refcounters, why it takes so much size?
And caches from different repos are to much different, they can be from kylobytes to megabytes.

**Comment by knutov** [comment]
After `borg prune` I have 10 Gb of chunks cache for 665 repos which are 1.6 Tb on disk.

Writing chunks cache makes prune process much slower as far as I see it in shell. Usually I do not have chunk cache already written on the server where I'm doing `prune`

**Comment by ThomasWaldmann** [comment]
Sorry, but I don't get what your problem is.

**Comment by knutov** [comment]
Yes, the problem is about space and IO during writing chunks.archives.d. 

A read FAQ (solution was manually create file instead of folder as far as I remember) and it's ok solution for client side. 
I do prune/delete from server side and it's not conveninet in that case. 

So, if the best bractice is __that__ solution - may be it's better/possible to add command line paramater to not use chunks.archives.d ?

Any way, why the size is so big if it is only refcounters?

**Comment by ThomasWaldmann** [comment]
The chunks cache has (id_256bit, refcount_32bit, size_32bit, csize_32bit) per chunk, so it is 44 Bytes * chunk count.

For chunks.archives.d this is done separately per archive, multiplying this by a factor of N_archives.

Plus some overhead for the hash table, minus some stuff saved due to compression (1.1).

About adding a param to not create chunks.archives.d: open a separate issue for this.

Guess we are done here.
