### ISSUE TITLE
Add version information to "borg info"

### ISSUE THREAD

**Issue by alejandro-perez** [borgbackup/borg#3251]
This need has come from another issue I have #3250. 
The "borg info" does not show which version of borg was used to create an archive. Is this stored in metadata?

**Comment by ThomasWaldmann** [comment]
Some on-disk data structures are versioned, but we do not store the borg version (like seen in `borg --version`). Not sure it is super useful or rather would bring people to jump to wrong conclusions (like they need *that* version to restore best or something).

**Comment by alejandro-perez** [comment]
Fair enough. I see the point. Closing then.

**Comment by dimejo** [comment]
Borg v1.0 showed the command line used for the backup. Is that still the case with v1.1?

You could rename the binary to reflect the version used for the backup.

**Comment by alejandro-perez** [comment]
it is the case. But unless I can back to the past, it is too late ;)

**Comment by dimejo** [comment]
> it is the case. But unless I can back to the past, it is too late ;)

I know :)
It was merely ment as a solution for the near future.
