### ISSUE TITLE
prune command shows wrong stats

### ISSUE THREAD

**Issue by GiuseppeArvati** [borgbackup/borg#3260]
Hello,

borg 1.1.1
CentOs 6
2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Jan 11 20:56:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python 3.4.5 (default, Jun  1 2017, 13:52:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux

I checked the archive and it's ok but prune command shows wrong stats 

this is the output of a prune command

```
------------------------------------------------------------------------------
                       Original size      Compressed size Deduplicated size
Deleted data:               -4.00 TB             -2.95 TB -399.54 MB
All archives:                2.35 TB              1.74 TB 69.83 GB

                       Unique chunks         Total chunks
Chunk index:                  235474              7046007
------------------------------------------------------------------------------

```
```
------------------------------------------------------------------------------
                       Original size      Compressed size Deduplicated size
Deleted data:               -7.92 TB             -7.92 TB -678.57 MB
All archives:                3.79 TB              3.79 TB 159.05 GB

                       Unique chunks         Total chunks
Chunk index:                  390283              9992006
------------------------------------------------------------------------------
```

deleted data size, for original and compressed column, is bigger ( absolute value ) than all archives size

Is this ok ? or should be "deleted" switched with "all archive" ?

thank you
giuseppe

**Comment by ThomasWaldmann** [comment]
Hmm, that stuff can be misunderstood easily I guess (todo: check docs).

"Deleted data" refers to the change done by the pruning op.
"All archives" refers to the state **after** the pruning op.

So, if you delete more data in backups than you have left afterwards, it will look like top post.
