### ISSUE TITLE
When extracting a macOS locked file, some metadata is lost with "Operation not permitted"

### ISSUE THREAD

**Issue by smammy** [borgbackup/borg#3263]
## Description

When restoring a file that is locked using the macOS HFS "Locked" Finder flag, the file should be locked _last_ to avoid causing other metadata operations to fail.

## Environment

* macOS 10.12.6
* Borg 1.1.1

## Steps to replicate

1. Prepare a locked file that also has an extended attribute:
```
mkdir test; cd test
mkdir src; cd src
echo "file contents" > locked-file
xattr -w extra.data "this is an xattr" locked-file
SetFile -a L locked-file
cd ..
```

2. Back up the file:
```
sudo borg init -e repokey sam@keep:/storage/backupdisk/borg/lock-test
sudo borg create sam@keep:/storage/backupdisk/borg/lock-test::test1 src
```

3. Restore the file:
```
mkdir dst; cd dst
sudo borg extract --strip-components=1 sam@keep:/storage/backupdisk/borg/lock-test::test1 src
cd -
```

## Expected result

* `borg extract` has no output.
* Resulting file has an extended attribute named `extra.data` with contents `this is an xattr`.
    * Verify this with `xattr -pl extra.data dst/locked-file`.

## Actual result

* `borg extract` says: `attrs: [Errno 1] Operation not permitted: '<FD 7>'`
* Resulting file has no extended attribute named `extra.data`.

## Notes

* No other Finder flags are restored properly. Except `Invisible` for some reason.

**Comment by ThomasWaldmann** [comment]
@smammy so, "locked" is a bsdflag, right?

Borg first sets bsdflags, then xattrs. So, can we just reverse order or do we run into other issues then?

**Comment by ThomasWaldmann** [comment]
@smammy can you try changing the order and whether it works as expected then. also concerning the "other" (which?) finder flags?

The code is in borg/archive.py, method restore_attrs. Just move the if-block dealing with bsdflags to the end of the method (after the xattrs block).

**Comment by smammy** [comment]
Verified. Things work fine if bsdflags get set last.

**Comment by Peitemoukiemena** [comment]
I am getting the same error when trying to extract `borg extract /path/to/repo::my-files home/USERNAME/src`
 ```
attrs: [Errno 1] Operation not permitted: '<FD 7>'
``` 
I run `borg create` on a centos machine and backup to remote repository, synology NAS. Even though I see the error when extracting, I check the file afterwards and it has been extracted and the size is normal. Then why do I see this error?

**Comment by ThomasWaldmann** [comment]
@Peitemoukiemena please open a new bug with much more details instead of appending to old and closed issues.
