### ISSUE TITLE
/tmp issues

### ISSUE THREAD

**Issue by rsyncnet** [borgbackup/borg#3264]
Hello,

I'm seeing an error after upgrading from borg 1.0.11 to 1.1.0, even a simple list command results in:
```
pyimod03_importers Remote: self test test_identical_creation
(borg.testsuite.hashindex.HashIndexDataTestCase) FAILED:
Remote:
Traceback (most recent call last):
Remote: � File "borg/testsuite/hashindex.py", line 324, in test_identical_creation
Remote: � File "borg/testsuite/hashindex.py", line 303, in _serialize_hashindex
Remote: � File "tempfile.py", line 808, in __exit__
Remote: � File "tempfile.py", line 812, in cleanup
Remote: � File "shutil.py", line 474, in rmtree
Remote: � File "shutil.py", line 396, in _rmtree_safe_fd
Remote: � File "shutil.py", line 393, in _rmtree_safe_fd
Remote: OSError: [Errno 22] Invalid argument: '/tmp/tmphcstiz13'
Remote:
pyimod03_importers Remote: self test test_read_known_good
(borg.testsuite.hashindex.HashIndexDataTestCase) FAILED:
Remote: Traceback (most recent call last):
Remote: � File "borg/testsuite/hashindex.py", line 327, in test_read_known_good
Remote: � File "borg/testsuite/hashindex.py", line 310, in _deserialize_hashindex
Remote: � File "tempfile.py", line 808, in __exit__
Remote: � File "tempfile.py", line 812, in cleanup
Remote: � File "shutil.py", line 474, in rmtree
Remote: � File "shutil.py", line 396, in _rmtree_safe_fd
Remote: � File "shutil.py", line 393, in _rmtree_safe_fd
Remote: OSError: [Errno 22] Invalid argument: '/tmp/tmp1tc1qq9v'
Remote:
pyimod03_importers Remote: self test failed
```

Python version is 3.5

I felt assured from the docs that 1.1 would be backwards compatible with 1.0.1 ?

Is this error an issue on our end (related to install, etc) or is there some underlying issue with borg in need of a fix?

**Comment by ThomasWaldmann** [comment]
Looks like something is wrong with your `/tmp`.
Make sure you have some space there to extract the binary and run the selftests.

Also, 1.1.1 is out since a while.

1.1 is mostly compatible with 1.0, but there are some cosmetical issues with logging.

So maybe offer 1.0.latest and also 1.1.latest.

**Comment by ThomasWaldmann** [comment]
Any news? 1.1.2 out now.

**Comment by rsyncnet** [comment]
Thanks for your feedback. However we would like to point out- the underlying system has not changed during the upgrade from 1.0 to 1.1 (i.e. the same /tmp system that was in place and working for 1.0 is also present for 1.1). So, what is it about 1.1 that has changed with regard to /tmp usage or handling?

**Comment by ThomasWaldmann** [comment]
- pyinstaller: 3.3 (borg 1.1 binary) vs. 3.2.1 (borg 1.0 binary)
- the code / tmp space needed might be a bit bigger in 1.1, so don't make space too tight

no other changes that I am aware of right now.

**Comment by ThomasWaldmann** [comment]
The traceback seen in the top post seems to indicate there is a problem when cleaning up the temporary directory. shutil is a python standard library module and it tries to recursively delete the not anymore needed temp directory it created shortly before, including all contents. And then your OS says:
```
OSError: [Errno 22] Invalid argument: '/tmp/tmphcstiz13'
```
No idea what's invalid about that though.

**Comment by ThomasWaldmann** [comment]
https://stackoverflow.com/questions/40355611/python-3-4-installation-error-1-oserror-errno-22-invalid-argument

^ same problem there, no solution though.

BTW, I am doing quite extensive testing (see Vagrantfile) and have never seen that problem on any platform. The binary is built / tested on Debian Wheezy, FreeBSD 10.3 and OSX 10.10.

**Comment by ThomasWaldmann** [comment]
It would be usedul to try what happens...
- using borg 1.1.2 binary on the repo server
- directly / locally executing the binary on the repo server (e.g. `borg --version`, `borg init repo`), so we can avoid any traceback information loss from client/server mode
- if you get a traceback with that, post it here

**Comment by enkore** [comment]
What's the mount(8) line of /tmp?

**Comment by ThomasWaldmann** [comment]
Any news?

**Comment by ThomasWaldmann** [comment]
closing this due to lack of feedback.

if there is any additional info that could help us to fix the issue (if it is in borg), feel free to update the issue and reopen it.
