### ISSUE TITLE
stale file handle when checkpointing

### ISSUE THREAD

**Issue by richardilles** [borgbackup/borg#3265]
Since upgrading this error keeps happening when I hit large zip files. tried all types of compression, no difference. this was working fine with 1.0.1
```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4024, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 3952, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 148, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 528, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 492, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 593, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 593, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 593, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 593, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 571, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode, self.files_cache_mode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 991, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 923, in chunk_file
    from_chunk, part_number = self.write_part_file(item, from_chunk, part_number)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 905, in write_part_file
    self.write_checkpoint()
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 438, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 476, in save
    self.manifest.write()
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 410, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1048, in put
    size = self.io.read(segment, offset, id, read_data=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1356, in read
    header = fd.read(self.put_header_fmt.size)
OSError: [Errno 116] Stale file handle

Platform: Linux Alexis-Machine 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64
Linux: LinuxMint 18.2 sonya
Borg: 1.1.0  Python: CPython 3.5.2
PID: 22212  CWD: /etc/cron.monthly
sys.argv: ['/usr/bin/borg', 'create', '--debug', '--exclude-caches', '--list', '--one-file-system', '/mnt/backup/borg-data-repo::data-{now:%Y-%m-%d}', '/media/ironStorage/mail', '/media/ironStorage/Users', '/media/ironStorage/media/_Books', '/media/ironStorage/media/_NewMusic', '/media/ironStorage/Files', '/media/ironStorage/sys-backups', '/media/ironStorage/media/mp3', '/media/ironStorage/Temp', '/media/redStorage/Public', '/media/redStorage/HockeyVideos']
SSH_ORIGINAL_COMMAND: None
```
Archive data-2017-11-04 does not exist

**Comment by ThomasWaldmann** [comment]
this is new in 1.1: it creates checkpoints even in the middle of files.

btw, rather use 1.1.latest (currently 1.1.1). there were some bug fixes (but maybe not this bug).

**Comment by ThomasWaldmann** [comment]
Is /mnt/backup/borg-data-repo on NFS?

**Comment by richardilles** [comment]
I will get 1.1.1 when my ppa roles the update out (LocutusOfBorg PPA)

Yes, the repo is located on a NFS mount on a NAS server on the LAN.

**Comment by richardilles** [comment]
from your deployment page, I used "--checkpoint-interval 86400" (24 hour chk pt).
This has fixed the issue for me, may be worth mentioning in the wiki as its new.

**Comment by richardilles** [comment]
I changed the --checkpoint-interval to be 24 hours. This solved the fail during borg create, but it seems it is doomed to fail as when the operation completes it borks again. 

Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4024, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 3952, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 148, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 528, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 494, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 476, in save
    self.manifest.write()
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 410, in write
    self.repository.put(self.MANIFEST_ID, self.key.encrypt(data))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1048, in put
    size = self.io.read(segment, offset, id, read_data=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1356, in read
    header = fd.read(self.put_header_fmt.size)
OSError: [Errno 116] Stale file handle

**Comment by ThomasWaldmann** [comment]
Can you confirm your previous borg version number and that this worked with the same repo and NFS configuration?

**Comment by richardilles** [comment]
I am not sure of the exact previous version, but from the ppa history it should have been 1.0.11-2.
Looking into the stale handle issue from my NAS server, it did have a default timeout of 5 minutes - I changed this to be 24 hours and went back to default borg checkpoints intervals. This seems to have corrected the issue as I've passed by several check point intervals now without a stale handle error.
Otherwise the previous version had no issues with the exact same settings - I run a monthly backup using a script.

**Comment by ThomasWaldmann** [comment]
Can you add the NFS settings you have changed to fix this to this ticket?

**Comment by richardilles** [comment]
I stand corrected, it just failed for a stale file handle at a check point write. 

I use unraid NAS and the NFS parameter is called "Tunable (fuse_remember):"

**Comment by ThomasWaldmann** [comment]
https://forums.lime-technology.com/topic/47534-stale-file-handle/

**Comment by ThomasWaldmann** [comment]
Hmm, I am a bit unsure if that is something that borg should / must address or whether borg could expect the fs layer to be more well-behaved.

Opinions? @enkore

**Comment by richardilles** [comment]
https://forums.lime-technology.com/topic/25097-stale-nfs-file-handles/?do=findComment&comment=231586

more detail. perhaps an issue with the NAS - but 1.0.11 did not exhibit this issue - so it appears something changed with 1.1.1 to be sensitive to it. Doing another run with the client mount disabling caching (noac).

**Comment by richardilles** [comment]
Ok, did some testing and managed to get it to work consistently.
unraid has a default handle timeout of 5 1/2 minutes, bumped that to 2 hours
ubuntu nfs mount also has a timeout, to get around that I used "--checkpoint-interval 900" and it appears that 15 minutes is enough to keep handles fresh, the default 30 minutes is too much.
I didn't fiddle to see what the upper boundary was before it times out.

**Comment by ThomasWaldmann** [comment]
Ideas for "fixing" this on the borg side:
- adding a time component to the repo FD cache and not using FDs that were not requested in the last 5 minutes
- adding a wrapper around the file object that catches ESTALE and closes/reopens the file transparently (guess it would also need to track seek position)

**Comment by ThomasWaldmann** [comment]
@richardilles I worked on this in #3901 - can you practically and carefully test that code?

Maybe first use code from master and reproduce the ESTALE issue in a fresh repo (NOT your production repo).

Then switch to the code from the PR, create another fresh repo, do the same operations again and check if the ESTALE issue is fixed (it should not touch FDs older than 4 minutes with that code).

**Comment by ThomasWaldmann** [comment]
@richardilles i've merged it now into master.

a practical test (see above) would still be welcome.

**Comment by richardilles** [comment]
sorry for the year long delay. I can confirm the issue with nfs stale file handles is no longer an issue for me per version 1.1.10 using the tests mentioned above.
