### ISSUE TITLE
check behaviour with "disk full" conditions

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#327]
see there: https://github.com/jborg/attic/issues/356

It is unclear and should be checked whether this affects current versions of borgbackup or was just an issue with attic 0.13 or msgpack 0.4.2 (or some other reason).

To do that: write python code (e.g. a unit test) that produces a severely corrupted repo by a "disk full" condition (either with current version of borgbackup or with attic 0.13).
Try whether "check" and "check --repair" and other repo operations work as expected. Make them fail.

The bounty is for code that creates a corrupted repository.

Notes:
- Just having some unused segments or other minor issues that can be easily fixed by "check --repair", by manually removing lock files or that do not block other operations do not count as corruption.
- Try to create the corruption with a small repository, if possible. The code might go into our unit tests, so it should not take lots of time or space.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/27587182-check-behaviour-with-disk-full-conditions)

**Comment by ThomasWaldmann** [comment]
another full disk issue: https://github.com/jborg/attic/issues/166#issuecomment-68614341

**Comment by ThomasWaldmann** [comment]
The "check behaviour" is done, thus I closed this issue.

I was able to produce some corrupted repos, see:
https://paste.thinkmo.de/bqyrsTv6#borg-corrupt-repos.tgz

I will open separate issues for every find...

**Comment by anarcat** [comment]
is #239 the only issue that was created here? or are there others?

**Comment by ThomasWaldmann** [comment]
#239 was not created due to my testing, it was found by @storcium in practice.

But I found an issue that for check --repair the hashindex was not initialized to empty which caused an AssertionError and I fixed that. I didn't find other malfunctions.

I had a "space reserve" that I freed after it ran into the disk full condition, so `borg repair` (etc.) could operate normally.
