### ISSUE TITLE
macOS creation dates are not preserved

### ISSUE THREAD

**Issue by smammy** [borgbackup/borg#3272]
## Description

macOS creation dates are not preserved.

## Environment

* macOS 10.12.6
* Borg git @ d1d55904

## Steps to replicate

1. Prepare a file that has a known creation date and last modified date
```
mkdir test; cd test
mkdir src; cd src
touch dated-file
SetFile -d 12/31/1999 dated-file
SetFile -m 10/10/2000 dated-file
cd ..
```

2. Back up the file:
```
sudo borg init -e repokey sam@keep:/storage/backupdisk/borg/date-test
sudo borg create sam@keep:/storage/backupdisk/borg/date-test::test1 src
```

3. Restore the file:
```
mkdir dst; cd dst
sudo borg extract --strip-components=1 sam@keep:/storage/backupdisk/borg/date-test::test1 src
cd -
```

## Expected result

* Resulting file has a creation date of 12/31/1999.
    * Verify this with `GetFileInfo -d dst/dated-file`.

## Actual result

* Resulting file has a creation date of 10/10/2000.

## Notes

* It looks like borg either doesn't set the creation date at all or sets it to the modification date.
* If this was resolved, borg would pass all my tests for preserving macOS metadata (a feat so far only achieved by CrashPlan).

**Comment by ThomasWaldmann** [comment]
This is about stat_result.st_birthtime which is specific for macOS (and some BSDs?) and not yet supported by borg.

**Comment by smammy** [comment]
Hm, I don't see `st_birthtime` in my `os.stat` result.

```
> sudo python3 -c 'import os; print(os.stat("src/dated-file"))'
os.stat_result(st_mode=33188, st_ino=13787270, st_dev=16777220, st_nlink=1, st_uid=1000, st_gid=20, st_size=0, st_atime=1509814669, st_mtime=971187000, st_ctime=1509814669)
```

I'm going to dig into this a bit and let you know what I find.

**Comment by smammy** [comment]
I'm going to fool around with maybe adding this, unless you think it's a waste of my time.
