### ISSUE TITLE
logging configuration

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#328]
we use stdlb logging now, but it is not configurable yet - it could be via a ini-style configuration file.

**Comment by ThomasWaldmann** [comment]
we need that for borgweb, so it displays INFO, WARNING, ERROR for borgweb to analyze and do coloured output.

**Comment by anarcat** [comment]
couldn't borgweb setup a custom handler that would talk over a socket?

https://docs.python.org/2/howto/logging-cookbook.html#sending-and-receiving-logging-events-across-a-network

**Comment by ThomasWaldmann** [comment]
it's not required to send log events over a socket as borgweb needs log file access anyway.

**Comment by ThomasWaldmann** [comment]
see PR #422.
