### ISSUE TITLE
restructure project layout

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#329]
See there:

http://blog.ionelmc.ro/2014/05/25/python-packaging/

https://hynek.me/articles/testing-packaging/

**Comment by ThomasWaldmann** [comment]
Implement this for 1.0?

**Comment by ThomasWaldmann** [comment]
See also #337 - should be done at same time.

**Comment by rumpelsepp** [comment]
see also: https://packaging.python.org/en/latest/distributing/

**Comment by ThomasWaldmann** [comment]
@rumpelsepp they don't seem to advocate using a "src/" directory to put the main package into.

**Comment by ThomasWaldmann** [comment]
ionel suggests this structure:
```
src/borg
tests/
```
But: we invoke a subset of the testsuite from production code, so I guess we rather keep it like:
```
src/borg
src/borg/testsuite/
```

**Comment by enkore** [comment]
"src" is so boring, how about "code"? :D

**Comment by ThomasWaldmann** [comment]
Use the src, Luke! :-P

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/1016 fixed by merging this.
