### ISSUE TITLE
Available resources threshold option

### ISSUE THREAD

**Issue by EthraZa** [borgbackup/borg#3302]
Thinking about the problem I'm facing to get Borg up and running here ( #3299 ) I was thinking how I was handling the same problem before.
Within the rsync backups, I was using the param --bwlimit so it would limit the amount of data it puts over the LAN, and so it does not hammer the CPU or DISK as well.

I was imagining how awesome would be if Borg has a --limit option where it could get limited on things like CPU usage, MEMORY usage, DISK I/O usage, or even a TIME FRAME.
The option would not limit the amount Borg can use, but the minimun amount of available resources so it can run.
If the server hits the imposed threshold, Borg would stop its activity for a minimun amount of time and just sit there, wainting the server to calm down so it can come back to full activity.

In my case I would like to limit Borg to carry on the backup only if there is at least 15% of RAM available, otherwise the server would start to swap stuff and no proccess would be able to finish what they are trying to do in a rasonable time.

Does this seem like a reasonable and possible improvement request?

**Comment by ThomasWaldmann** [comment]
bwlimit: see faq for a solution

limiting / throttling cpu, memory, I/O: there are OS tools for this (not everything makes sense though)

About the other stuff: that would be a rather unusual and likely hard to impossible to implement featureset for an application. Usually only the OS has the kind of oversight that would be needed for this. Also, conditions can change rather quickly when applications or OS allocate/free memory. OSes usually try to use most of the memory available, so there is not really "free" memory after the system is running for a while. Whether a system performs well is primarily depending on the working set of memory pages fitting into physical RAM (idle pages may as well be swapped to disk without causing performance problems).

Beside that you need enough memory to run borg, impact for 2nd+ backups should be rather low, assuming that many files did not change and it will be finished rather quickly.

**Comment by EthraZa** [comment]
I see. Thank you.
