### ISSUE TITLE
'borg config' command

### ISSUE THREAD

**Issue by milkey-mouse** [borgbackup/borg#3304]
Similar to [`git config`](https://git-scm.com/docs/git-config), it would be nice to have a convenience `borg config` command that just opens the repo config and changes an option accordingly.

**Comment by milkey-mouse** [comment]
Another thing I'm not sure of is whether this should go under `borg debug` or not...

**Comment by ThomasWaldmann** [comment]
I am somehow a bit undecided what to think about this.

OTOH, it's nice to have a frontend here, so one does not need an editor. Using an editor isn't that complicated, though (locating the configs for the first time is non-trivial, though).

OTOH, you still need an editor due to security for remote repos (or run borg config on the server?).

**Comment by milkey-mouse** [comment]
I was thinking to run e.g. `ssh user@host borg config /path/to/repo key value` to reconfigure on the server because [some clients may only be allowed to use borg serve](https://borgbackup.readthedocs.io/en/stable/usage/notes.html?highlight=ssh#append-only-mode). If the user is allowed to run other commands, they could just run ssh directly like above. The repo config is not encrypted even with an encrypted repo, so it would still work.

**Comment by ThomasWaldmann** [comment]
Hmm, when using `ssh user@host borg config /path/to/repo key value` there is some risk that this causes permission issues, if user is not the usual borgbackup user.

**Comment by ThomasWaldmann** [comment]
btw, i am working on adding validation for the keys/values used with borg config.

when looking at the keys one might want to set with new values, I failed to find anything that a user could want to set for the cache configuration. @milkey-mouse do you see any use case?

See #3581.

If we fail to find any use case for modifying the cache config, there are 2 ways to deal with this:
- raise for any key now (if we think there could be use cases in future)
- remove the `borg config --cache` option / related code and only keep the repo related stuff

**Comment by milkey-mouse** [comment]
I remember at the time I had a good reason for it - I think a need to edit the cache was what spurred me to make the command. I will see later what I was doing and try to add examples to the docs (unless `--cache` really is just a symptom of featuritis...)

**Comment by milkey-mouse** [comment]
Ah, I found it: the main thing I used `--cache` for was changing the `previous_location` variable after intentionally moving a repository so I didn't have to run a dummy `BORG_RELOCATED_REPO_ACCESS_IS_OK=yes borg list` just to stop prompts from aborting my automatic backups.

I have also used it to change the manifest ID/integrity value during ill-advised repository surgery, but that's not something that should be encouraged/mentioned in the docs...

**Comment by ThomasWaldmann** [comment]
Reopening to update the validation PR accordingly.

**Comment by ThomasWaldmann** [comment]
See PR #3674.

BTW, I noticed `borg config --cache repo previous_location <new_value>` is not working at all, it does not set a new value, the old one is still present. This is unrelated to my validation changes.

@milkey-mouse can you have a look?

**Comment by milkey-mouse** [comment]
I just tested it (although the system I'm on has borg 1.1.3) and it worked fine.

**Comment by milkey-mouse** [comment]
Ok, wow, this is a really stupid issue. :man_facepalming:

`borg config --cache previous_location <new-location>` would never have worked in the first place! If you look at `cache.py` one can see it resets `previous_location` to the "new" canonical location again right before saving the file:

https://github.com/borgbackup/borg/blob/1473ea708cf9bdaaae54f42a06dc699e6ee926e1/src/borg/cache.py#L294-L309

So if you were resetting `previous_location` to the "correct" value after moving a repo, it would appear to work because `BORG_RELOCATED_REPO_ACCESS_IS_OK` would just so happen to change it to the same thing. But if you were trying to set it to a nonsense/inaccurate value to test it, it would never have worked!

I think the easiest course of action might just be to move `self._config.set('cache', 'previous_location', self.repository._location.canonical_path())` to the end of the load() function instead.

**Comment by milkey-mouse** [comment]
Ok, I've done that and it works now. Since the fix is moot until `previous_location` is whitelisted, it would probably be best to just cherry-pick 65ad328d onto #3674.

**Comment by ThomasWaldmann** [comment]
Doesn't that basically disable "moved repository" check because it will never see the real previous_location value?

**Comment by milkey-mouse** [comment]
No, because the variable set in `self._config` is different than the `self.previous_location` variable set and checked everywhere else. `self._config` is only read on load and written on save AFAIK.

Either way, I just double-checked and the relocated repo check still triggers.

**Comment by ThomasWaldmann** [comment]
i merged #3674.

**Comment by milkey-mouse** [comment]
ok, #3682 handles the other change.
