### ISSUE TITLE
Confusing meaning of relative patterns

### ISSUE THREAD

**Issue by Code7R** [borgbackup/borg#3306]
Hi,

I see a usability issue in borg-patterns(1) manpage. The explanation talks in lengths about how the behavior is when user specified a selector prefix. What does not tell you is what happens if no selector is specified (which is apparently a valid thing, reading the second paragraph).

And what does happen in this case?
Are relative names ok? (relative to source folder)
Are directory names ok? (skipping whole directory contents, of course)

That is not clear. I had to find it out by trial-and-error and this is something I don't like to rely on.

And the result came a bit surprising. Imagine a sample usecase - making backups of a portable harddisk which gets different mount points here and there. Now I stored an "exclude-patterns.txt" on that disk which contains three folder names (just the names). And I run borg like:
```
src=/media/mountpoint; borg create --exclude-from $src/exclude-patterns.txt borgfolder::$(date +%F) $src
```

Result: the pattern didn't match anything.

Maybe it was matching those relative to $CWD? Who knows, but it does not look right.

**Comment by ThomasWaldmann** [comment]
Let's check https://borgbackup.readthedocs.io/en/1.2.4/usage/help.html : 

- pattern style prefix default: `fm:` and `sh:` say what options use them by default.
- docs now also tells how the paths going into the matcher look like and that patterns need to match these paths.

Thus, I'm closing this.
