### ISSUE TITLE
Segmentation fault on 1.1.2 

### ISSUE THREAD

**Issue by chrisddwrt** [borgbackup/borg#3307]
Hi,

we try to run a borgbackup on a very large tree with small files on a suse system (openSUSE Leap 42.3). 

I tried the release (1.1.2/borg-linux64) first, then used a version from git using a build-env and python3.4.6. 
I used:

```
git clone https://github.com/borgbackup/borg.git
cd borg
git checkout -b1.1.2 1.1.2 
```
to make sure i run a stable release.

After 2-3 hours we get this. Also when we try to restart the backup, we run into the same issue.

the memory usage before the crash is arround 16gb. We use the following switches to run the backup:

```
borg create --verbose --filter AME --stats --show-rc --compression lz4 ...         
```
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 128159
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1850
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Here is the Segmentation fault we get:
```
Fatal Python error: Segmentation fault

Current thread 0x00007f7adfaf4700 (most recent call first):
  File "/mnt/zfs/borg/build/borg/src/borg/cache.py", line 548 in commit
  File "/mnt/zfs/borg/build/borg/src/borg/archive.py", line 479 in save
  File "/mnt/zfs/borg/build/borg/src/borg/archive.py", line 439 in write_checkpoint
  File "/mnt/zfs/borg/build/borg/src/borg/archive.py", line 910 in write_part_file
  File "/mnt/zfs/borg/build/borg/src/borg/archive.py", line 932 in chunk_file
  File "/mnt/zfs/borg/build/borg/src/borg/archive.py", line 1001 in process_file
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 594 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 617 in _process
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 506 in create_inner
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 543 in do_create
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 148 in wrapper
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 4001 in run
  File "/mnt/zfs/borg/build/borg/src/borg/archiver.py", line 4073 in main
  File "/usr/local/bin/borg", line 9 in <module>
: Zeile 13: 30413 Speicherzugriffsfehler  (Speicherabzug geschrieben) borg create --verbose --filter AME --stats --show-rc --compression lz4 /mnt/backjob::'job-{now}' /mnt/backup
```
If we can change i.e. parameters to prevent this, we are open to this. 

Borg is quite cool, i would like to use it for this server too.

Great Work!

Regards Christian

**Comment by ThomasWaldmann** [comment]
Sometimes segfaults point to hardware issues (like memory with bit errors, CPU overheating, ...), can you check that? See the FAQ with some hints for checking.

**Comment by ThomasWaldmann** [comment]
Another idea: how much "free" memory does this machine have?

The files cache is a python dict (a hashtable) and it will grow when getting too full. Same applies for borg's self-made hashindex (used for the chunks cache and repo index), so memory need might go up suddenly.

Should rather cause a MemoryError or something, though, not Segfault.

**Comment by ThomasWaldmann** [comment]
BTW, can you say how many files, how many GiBs we are talking about here?

**Comment by enkore** [comment]
Try disabling the files cache, since it has to fit into memory.

**Comment by chrisddwrt** [comment]
HI,

free:
             total       used       free     shared    buffers     cached
Mem:      32818736   13198860   19619876     132552    3252376    9496204
-/+ buffers/cache:     450280   32368456
Swap:            0          0          0

Size of the files we want to backup is 1.9TB Number of Files is: 78.487.783 

@enkore how to do that?

Thanks in advance

**Comment by ThomasWaldmann** [comment]
http://borgbackup.readthedocs.io/en/stable/internals/data-structures.html#indexes-caches-memory-usage

Assuming that 1 file = 1 chunk and that the repository is local on same machine, I already get almost 32GiB for mem_usage.

The peak could even reach about 86GiB. So, if you don't have swap, you might be out of memory. This is mostly caused by the files count (and chunks count) you try to process (manage) at once, not by your data volume.

Please note that this just a rough estimate, a precise calculation would need a lot of more input data we do not know.

Stuff you can do to lower memory needs:
- switch off files cache: `--files-cache=disabled`
  - lowers memory needs to about 1/5
  - speed impact: borg always needs to read/chunk/hash all input files
- use smaller repos (chunk count) / smaller input data sets (files and chunks count)
  - lowers memory needs proportionally
  - if you lower them enough, you could maybe afford running borg with files cache

**Comment by chrisddwrt** [comment]
Hi,

disabling the file cache helped to finish the backup, we got our first backup. So here we get some more informations on how many files, etc: 

------------------------------------------------------------------------------
Archive name: backup-2017-11-12T18:30:21
Archive fingerprint: 
Time (start): Sun, 2017-11-12 18:30:24
Time (end):   Mon, 2017-11-13 14:25:00
Duration: 19 hours 54 minutes 35.26 seconds
Number of files: 71669069
Utilization of max. archive size: 22%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.80 TB            997.53 GB             63.80 GB
All archives:                3.92 TB              2.16 TB            396.79 GB

                       Unique chunks         Total chunks
Chunk index:                 5983078            160852543
------------------------------------------------------------------------------
terminating with success status, rc 0

**Comment by ThomasWaldmann** [comment]
BTW, guess we can not do much about the segfault without a more precise location.

We know it was somehow in the cache commit, but not precisely what it was. Python code usually does not segfault, so it likely was either in the C code or in the Python interpreter.

Determining the precise location could be done with gdb, if it can be reproduced.

**Comment by ThomasWaldmann** [comment]
Just as a vague idea: malloc failing -> returns NULL pointer -> missing check for NULL? -> segfault.

**Comment by ThomasWaldmann** [comment]
@chrisddwrt did you find out anything else that could help debugging this?

**Comment by ThomasWaldmann** [comment]
closing due to lack of feedback. feel free to reopen it with more information.
