### ISSUE TITLE
sshfs: nonce.tmp os.replace PermissionError

### ISSUE THREAD

**Issue by ralhei** [borgbackup/borg#3315]
I just got a 500GB space rented from hidrive.com to get my borg backups located remotely on their disks.
The drive gets mounted easily via sshfs, and I can initialize a new repo, but then 'borg create' fails at this point:
```
[...]
  File "/home/heinkel/bin/borg/lib/python3.5/site-packages/borg/crypto/nonces.py", line 85, in ensure_reservation
    self.commit_repo_nonce_reservation(reservation_end, repo_free_nonce)
  File "/home/heinkel/bin/borg/lib/python3.5/site-packages/borg/crypto/nonces.py", line 48, in commit_repo_nonce_reservation
    self.repository.commit_nonce_reservation(next_unreserved, start_nonce)
  File "/home/heinkel/bin/borg/lib/python3.5/site-packages/borg/repository.py", line 309, in commit_nonce_reservation
    fd.write(bin_to_hex(next_unreserved.to_bytes(8, byteorder='big')))
  File "/home/heinkel/bin/borg/lib/python3.5/site-packages/borg/platform/base.py", line 174, in __exit__
    os.replace(self.tmppath, self.path)
PermissionError: [Errno 1] Operation not permitted: '/mnt/borg-repo/ralap/backup/nonce.tmp' -> '/mnt/borg-repo/ralap/backup/nonce'

Platform: Linux ralap.site.home 3.16.7-48-desktop #1 SMP PREEMPT Wed Oct 26 18:09:22 UTC 2016 (8c027f6) x86_64 x86_64
Linux: openSUSE  13.2 x86_64
Borg: 1.1.1  Python: CPython 3.5.1
PID: 5236  CWD: /home/heinkel
sys.argv: ['/usr/local/bin/borg', 'create', '--compression', 'lz4', '/mnt/borg-repo/ralap/backup::home-{now:%Y-%m-%d}', 'heinkel/tmp']
SSH_ORIGINAL_COMMAND: None
```
So it fails when it tries to rename `nonce.tmp` into `nonce` (via `os.replace`). The problem here is that the file `nonce` already exists, and for some reason  hidrive will not allow a 'mv' (rename) command to overwrite an existing file, also not on the command line.

Could borg possibly remove this `nonce`-file prior to renaming `nonce.tmp` to it?
Is there a short-term solution to it? Some option to borg which circumvents this problem?

Any help is very appreciated!

**Comment by ThomasWaldmann** [comment]
```
os.replace(src, dst, *, src_dir_fd=None, dst_dir_fd=None)

    Rename the file or directory src to dst. If dst is a directory, OSError will be raised. If dst exists and is a file, it will be replaced silently if the user has permission. The operation may fail if src and dst are on different filesystems. If successful, the renaming will be an atomic operation (this is a POSIX requirement).
...
```
Seems like sshfs does not behave like a posix filesystem here. File a bug there / check if this problem is known?

The point of `platform.SaveFile` is to atomically update a file. Either it works, then the file contents is updated or it doesn't, then it still has old contents.

If we would add a workaround for above problem (like delete+rename), it would not be atomic any more, so if something happens in between the delete and the rename, no file would exist at the target filename.

**Comment by ThomasWaldmann** [comment]
Hmm, can you also check if there is maybe a permissions issue that triggers the above problem?
Check the files and also the containing directory for rwx permissions.

**Comment by ThomasWaldmann** [comment]
https://unix.stackexchange.com/questions/123231/what-does-sshfs-oworkaround-rename-do

**Comment by ralhei** [comment]
Hi Thomas, so the permissions were not the problem, it was sshfs itself - and the problem got indeed solved by applying the 'workaround' option as described in the article referenced above. I.e. the file system must be mounted like
```
sshfs -o workaround=rename user@sftp.domain.com/dir /mnt
```
Thanks a lot for your help!

**Comment by ThomasWaldmann** [comment]
Guess we need to add that to FAQ, using sshfs is quite widespread and that default options are not posix-conform is a bit unexpected.
