### ISSUE TITLE
1.0: no `--progress` flag in `borg extract`

### ISSUE THREAD

**Issue by bsiegert** [borgbackup/borg#3316]
I had this on borg 1.0.9, but I believe the current version has the same issue.

The documentation (http://borgbackup.readthedocs.io/en/stable/usage/extract.html) says:

> --progress can be slower than no progress display, since it makes one additional pass over the archive metadata.

However, the create command does not have a `--progress` option! Which is a pity, since I would love to see the progress of my restore while it is happening.

**Comment by infectormp** [comment]
create command  have `--list` http://borgbackup.readthedocs.io/en/stable/usage/create.html#item-flags

**Comment by ThomasWaldmann** [comment]
Hi Benny, please clarify: are you talking about extract or create? Please edit your post.

**Comment by ThomasWaldmann** [comment]
1.0.9 borg create:
```
(borg-env) tw@tux:~/w/borg$ borg --version
borg 1.0.9
(borg-env) tw@tux:~/w/borg$ borg init myrepo
...
(borg-env) tw@tux:~/w/borg$ borg create -v --progress myrepo::test docs/
(displays progress output)
```

borg 1.0.9 extract:
```
(borg-env) tw@tux:~/w/borg$ borg extract -v --progress myrepo::test                                                 
usage: borg [-h] [-V] <command> ...
borg: error: unrecognized arguments: --progress
```
http://borgbackup.readthedocs.io/en/1.0.9/usage.html#borg-extract (no progress there)

**Comment by ThomasWaldmann** [comment]
borg 1.0.11: same thing, no progress for extract.

borg 1.1.x: simply progress display for extract.

**Comment by bsiegert** [comment]
I meant both extract, sorry. This was while restoring data.
TW <notifications@github.com> schrieb am Sa. 11. Nov. 2017 um 20:25:

**Comment by ThomasWaldmann** [comment]
OK, just use 1.1.x?

**Comment by ThomasWaldmann** [comment]
OK, so the docs issue is cleared I guess, so what's left is a feature request for `borg extract --progress` in borg 1.0.x?

**Comment by ThomasWaldmann** [comment]
guess this is not needed any more. 1.1.x is stable since long and has it.
