### ISSUE TITLE
crc32_slice_by_8 alignment issue on armhf

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3317]
seen in ubuntu bionic testing by @LocutusOfBorg, reproduced by Elladan (IRC):

```
Nov 11 19:17:36 pumpkin kernel: [25372.479551] Alignment trap: python3.6 (9704)
                 PC=0x75427c78 Instr=0xe955b402 Address=0x76f65039 FSR 0x001
```
Alignment trap confirmed :-)

Bus error raised by:
```
#4  crc32_slice_by_8
    (data=0x76fa2039, length=<optimized out>, previousCrc32=<optimized out>)
    at src/borg/algorithms/crc32_slice_by_8.c:358
#5  0x76462e4e in __pyx_pf_4borg_10algorithms_9checksums_crc32_slice_by_8
    (__pyx_self=<optimized out>, __pyx_v_value=<optimized out>, __pyx_v_data=<optimized out>)
    at src/borg/algorithms/checksums.c:1341
```
Bug was no repro with armhf xenial w/Python 3.5, reprod with bionic w/Python 3.6.

Legible stack trace here: http://rn0.me/show/8jem6kLzNkvHWldCYfzq/

**Comment by ThomasWaldmann** [comment]
See the data=<uneven address> in #4. ARM does not like it when memory accesses are unaligned.

Depending on the CPU configuration (`/proc/cpu/alignment`) and ARM generation, it might crash, fixup the issue in software, or just compute with wrong values.

**Comment by ThomasWaldmann** [comment]
The problem is that the crc-slice-by-8 code starts fetching 32 bit integers right from the buffer start address. It has some code for tail management, processing single bytes remaining at the end of the buffer.
Some head management code needs to get added there to process singles bytes at the start of the buffer until some divisible-by-4 address is reached.

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg and Elladan: can you test the PR?

**Comment by ThomasWaldmann** [comment]
Note: always giving the crc32 code aligned memory was no option as we can't easily (and pretty) control that from python. But doing some head managment (and not only tail managment) in byte-mode is the best solution anyway, I guess.

**Comment by LocutusOfBorg** [comment]
seems to work thanks! uploaded in debian and ubuntu

**Comment by LocutusOfBorg** [comment]
I uploaded this patch: https://github.com/ThomasWaldmann/borg/commit/81aad75b78c14f9a2cb82e2e116be4faa3ddb483
