### ISSUE TITLE
[Win10] Borg exits without finishing script

### ISSUE THREAD

**Issue by GodsVictory** [borgbackup/borg#3323]
The script below exits without pausing. I had create and prune on separate lines, but noticed prune wasn't getting ran, hence the 1 liner.

```
@echo off

set BORG_REPO=/b/POWER
set BORG_PASSPHRASE=[redacted]

For /f "tokens=2-4 delims=/ " %%a in ("%DATE%") do (set mydate=%%c-%%a-%%b)

REM Replace leading space with zero
For /f "tokens=1-2 delims=/:" %%a in ("%TIME%") do (set mytime=%%a%%b)

if "%mytime:~0,1%" ==" " set mytime=0%mytime:~1,3%
set timestamp=%mydate%_%mytime%
set TAG=POWER_%timestamp%
echo %TAG%

borg create --progress --compression none ::%TAG% /d/home && borg prune --list --prefix 'POWER_' --keep-daily 7 --keep-weekly 4 --keep-monthly 6
pause
```

**Comment by dimejo** [comment]
> set BORG_REPO=/b/POWER

Not having any experience with batch files on Windows, but this doesn't look like a correct path to me.

Did you try running with debug?

**Comment by GodsVictory** [comment]
You have to use paths like that. The backup is working fine, it just exits the script instead of continuing.

debug shows no errors, it simply exits the script

**Comment by ThomasWaldmann** [comment]
What borg version is that which directly runs under windows / where did you get it / how did you install it?

**Comment by GodsVictory** [comment]
https://github.com/billyc/borg-releases

1.0.11

**Comment by ThomasWaldmann** [comment]
Sounds like a windows scripting issue rather than a borg one.

Does windows cmd have a feature to terminate a script if one command terminates with a rc != 0?

**Comment by GodsVictory** [comment]
You have to explicitly check for it. Also, rc == 0 in this case. Borg is working fine, it's just exiting the script. I think I can work around it. This isn't really a borg issue since Windows isn't supported officially.
