### ISSUE TITLE
borg mount repo: add 'latest' symlink

### ISSUE THREAD

**Issue by nemoinis** [borgbackup/borg#3324]
obnam (now defunct) had this handy habit of adding a 'latest' symlink pointing to the most recent archive when fuse-mounting a repo. Made for less typing (and easier scripting) for the common case of getting a file from the most recent backup.
Thanks for considering it.

**Comment by ThomasWaldmann** [comment]
If you are just interested in the latest archive, you can just mount *that* archive, like `borg mount repo::archive` - then you only have its contents below the mountpoint.

You still need to find out the latest archive's name though, something like `borg list --short --last 1 repo`?

**Comment by nemoinis** [comment]
The point of the request is that is provides a QUICK painless way to access the latest archive. Without having to know its timestamp, run another command, or whatever. Just a simple, small symlink.

**Comment by marcpope** [comment]
Here's a way to mount it in one command:
REPO="$(borg list --short --last 1 reponame)"; borg mount reponame::$REPO /tmp/location

**Comment by nemoinis** [comment]
Yes, that, or more simply:
borg mount --last 1 reponame /tmp/location

It's not quite the same as a symlink to latest in the whole repo mount (for example to diff between latest and an older version) but it works for my common case. Thanks!
