### ISSUE TITLE
Remote snapshot creation

### ISSUE THREAD

**Issue by essembeh** [borgbackup/borg#3326]
Hi

Here is my use case:
- I have a **remote** server with datas I want to periodically backup
- I have my **storage** server which I trust more
- I don't trust **remote** so I don't want to grant access to **storage**

The common way is be to create a snapshot from **remote** to **storage** like
```borg create ssh://storage/mnt/backup.borg::{now} /etc```
But it gives **remote** full access to the borg repo, and it could potentially delete it.

I  would like to backup **remote**'s data from **storage** shell like 
```borg create /mnt/backup.borg::{now} ssh://remote/etc```
Which is to me more secure because **remote** has no access to **storage** and cannot access to the borg repo.

Another idea would be to create a special user on **remote** with a special **borg shell** (like git) which would allow only create operations (configurable to allow list, extract too?)

Maybe I'm missing something, but is there an alternative here to use borg to backup remotes without giving them full access to the repo?

Thanks

**Comment by infectormp** [comment]
maybe you need use https://borgbackup.readthedocs.io/en/stable/usage/notes.html#append-only-mode?

**Comment by essembeh** [comment]
Thanks, I haven't used serve yet, looks like the second solution I imagined (like a borg restricted shell).

But allowing remote snapshot creation would be a really nice feature.
Like rsync, you can rsync from local to distant and from distant to local.
I imagine it would require to have borg installed on both sides, but is would be very useful. 
Could it be a future feature?

**Comment by ThomasWaldmann** [comment]
There is no "pull mode" yet, but there is a ticket about it already, including with a workaround.

So, closing this as a duplicate.
