### ISSUE TITLE
Simultaneous Restore while a Backup Going On

### ISSUE THREAD

**Issue by marcpope** [borgbackup/borg#3339]
When attempting to recover data while a backup is taking place, e.g. borg list reponname, the repo is locked and can't be accomplished. (Tested with 1.1.1)

Consider a scenario of automated backup script every hour, taking 10+ minutes and having to time a restore in between the backups. In this case, you'd have to either cancel the backup script, or turn it off manually.

If possible, please investigate the possibility of mount, list, restore options when a backup is taking place. (does not need to look at the current, on-going backup).

**Comment by ThomasWaldmann** [comment]
The locking issue is known and there are some tickets about it already, thus I'll close this one.

If you do an hourly backup and it typically takes 10 mins, you still have 50 mins left to start a restore.

You do not need to cancel or turn off the backup script, the restore will also lock the repo and will finish normally if it could get the lock.

Depending on your `--lock-wait` value, the borg operations will either wait rather shortly for a lock (default) or longer (if you specify a longer value to let stuff queue up).

**Comment by marcpope** [comment]
If you mount an image, will the lock stay in place until unmounted?

**Comment by ThomasWaldmann** [comment]
Yes.
