### ISSUE TITLE
Performance issue due to frequent fsync/fdatasync

### ISSUE THREAD

**Issue by bjornfor** [borgbackup/borg#3352]
I have an USB3 backup harddisk (Seagate Expansion Portable 4TB) that is capable of sustained ~90 MiB/s writes (tested by dd'ing 100 GiB) but struggles to maintain ~15 MiB/s writes with borg due to its frequent calls to fsync/fdatasync. (fsync seems very slow on this drive.)

From strace log, I see borg writing a few MiBs, then calling fsync (with borg 1.0.x or fdatasync with 1.1.x), which on this drive can block for 0.2 - 2 seconds.

What can be done, short or long term, to have borg write more data between calls to fsync/fdatasync?

**Comment by ThomasWaldmann** [comment]
did you include the final sync in your dd perf test? otherwise you've just measured how long it took to write the stuff into memory write buffers, not on disk.

**Comment by ThomasWaldmann** [comment]
what's the segment file size of your borg 1.1 test repo? if you used an old repo (created with < 1.1), the segment files will be ~5MiB, with a borg 1.1 created repo it will be ~500MiB (and maybe more efficient, try it).

**Comment by bjornfor** [comment]
Creating new repo with borg 1.1.x vastly improved performance. I'm now looking at 60 MiB/s instead of 15 MiB/s. Thanks!

(I obviously reused the old borg 1.0.x repo when I initially tested borg 1.1.x.)

Is there a way to configure the segment size? I looked in "man borg" but didn't find anything. Just curious if I can get any closer to 90 MiB/s.

> did you include the final sync in your dd perf test?

Yes. I used "dd ... conv=fsync". Also, to be really sure of no caching, I wrote 100 GiB.

**Comment by ThomasWaldmann** [comment]
you can configure the segment size in a fresh repo: repodir/config

but I'ld not expect significant further improvements. of course there is a huge difference between syncing every 5MB to 500MB, but it will be way less if you go higher.

also, you maybe don't want extremely big segment files as compacting them will get increasingly expensive.

**Comment by bjornfor** [comment]
FYI, I tested increasing the segment size to the max, which I learned is 4 GiB. I didn't notice any speed-up compared to 500 MiB segment size. Still very happy to go from 15 to 60 MiB/s :-)
