### ISSUE TITLE
Order of options and paths can cause errors when going from 1.0 to 1.1

### ISSUE THREAD

**Issue by suuchan** [borgbackup/borg#3356]
After upgrading from 1.0.x to 1.1.0 our backup scripts fail with an error. The issue seems to be the order of options and paths to backup. This does not work:

`borg create '::{now:%Y-%m-%d}' -v --stats --compression lz4 --one-file-system --exclude /boot --exclude '/home/*/.cache' --exclude /root/.cache --exclude 're:^/usr/(?!local($|/))' --exclude 're:^/usr/local/(?!etc($|/))' --exclude /tmp --exclude /var/cache --exclude /var/tmp /home 
`

but moving the paths before all options does:

`borg create '::{now:%Y-%m-%d}' /home -v --stats --compression lz4 --one-file-system --exclude /boot --exclude '/home/*/.cache' --exclude /root/.cache --exclude 're:^/usr/(?!local($|/))' --exclude 're:^/usr/local/(?!etc($|/))' --exclude /tmp --exclude /var/cache --exclude /var/tmp`

The command line parsing should probably be fixed that the old order (which is also what `borg -h` shows) works again.

**Comment by ThomasWaldmann** [comment]
Which borg packages are you using? Is it the same python version?

**Comment by suuchan** [comment]
RHEL/CentOS 7 python, borgbackup package from EPEL:

python-2.7.5-58.el7.x86_64
borgbackup-1.1.0-1.el7.x86_64

We see it on three systems, after the upgrade from the previous 1.0.x EPEL package the command stops working.

**Comment by ThomasWaldmann** [comment]
@suuchan maybe don't use 1.1.0, it had some bugs and is superceded by 1.1.1 and 1.1.2 since a while.

**Comment by ThomasWaldmann** [comment]
https://centos.pkgs.org/7/epel-testing-x86_64/borgbackup-1.1.2-1.el7.x86_64.rpm.html

**Comment by ThomasWaldmann** [comment]
You don't use python 2.7 for borg, it needs 3.4+.

So the question is whether you changed your python 3.x version while doing the upgrade from borg 1.0 to 1.1.

**Comment by suuchan** [comment]
Sorry, my bad: 2.7 is the system python, borg uses python34:

```
# head -1 /usr/bin/borg
#!/usr/bin/python3.4
```

python34-3.4.5-4.el7.x86_64

We also tried 1.1.2 on Ubuntu 17.10 using the package from 18.04. And Fedora 27 with 1.1.2. Both have the same problem too.

**Comment by ThomasWaldmann** [comment]
A while ago, a similar (or same) problem has been seen already.

Back then we thought it is a bug in argparse that's present in some python versions.

**Comment by ThomasWaldmann** [comment]
Simplifying it a bit:
```
$ borg create repo::test -v --stats scripts/
usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug]
            [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS]
            [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
            [--remote-ratelimit RATE] [--consider-part-files]
            [--debug-profile FILE]
            <command> ...
borg: error: unrecognized arguments: scripts/
```

```
$ borg create -v --stats repo::test scripts/
(works)
```

So, it does not like options (like `-v --stats`) being put in between the positional args (like `repo::test` and `scripts/`). Seen it failing on Python 3.5.2 with latest 1.1-maint branch.

Please note that the docs tell you to use it in the working way:
```
usage: borg create [-h] [--critical] [--error] [--warning] [--info] [--debug]
                   [--debug-topic TOPIC] [-p] [--log-json]
                   ...
                   [--chunker-params PARAMS] [-C COMPRESSION]
                   ARCHIVE [PATH [PATH ...]]
```
You see there is nothing in between ARCHIVE and PATH.

Guess we have to check/fix the docs whether we show some other (not always working order) anywhere.

**Comment by ThomasWaldmann** [comment]
Another way to resolve it would be to try to find out whether there is some change in our argparse usage in 1.1 that triggers this and that can be solved otherwise.

**Comment by ThomasWaldmann** [comment]
https://stackoverflow.com/questions/33404227/python-argparse-optional-argument-only-works-when-its-entered-in-the-right-posi

http://bugs.python.org/issue15112

**Comment by ThomasWaldmann** [comment]
1.0: borg create uses `nargs='+'` for paths (but borg extract uses `nargs='*'`).

1.1: borg create uses `nargs='*'` for paths.
this is likely because `--pattern / --patterns-from` can also be used to give root paths, so the paths positional argument(s) became optional.

So, guess we have to live with it.

As the python bug is open since 2012, there's also no quick solution to be expected from there (and it would not help anyway if people use old pythons).

So, TODO: check the docs if we every mention the bad order.
