### ISSUE TITLE
borg mount on more than 1 repo at a time

### ISSUE THREAD

**Issue by marcpope** [borgbackup/borg#3358]
_Version: borg 1.1.1:_

Not sure if this is a bug or a feature?

As I mentioned in the IRC, you can mount a repo more than once using different mount points. This didn't seem like expected behavior as when mounting creates a lock. So there is effectively multiple locks on the same repo. Was wondering if this could cause issues somewhere.

**In my process list, you can see two mounts for the same repo:**
```
16848 ?        Sl     0:00 borg mount /home/borg229/test /mnt/test
16863 ?        Sl     0:00 borg mount /home/borg229/test /mnt/test2
```

**Under  /home/borg229/test/lock.roster shows the two locks:**
`{"shared": [["private.borgbackupserver.com@207379871126", 16863, 0], ["private.borgbackupserver.com@207379871126", 16848, 0]]}`

**I did test for mounting during a backup, and it gives the correct lock message:** 
`Failed to create/acquire the lock /home/borg229/test/lock.exclusive (timeout).`

**Comment by marcpope** [comment]
From further testing, don't see anything wrong with this.

**Comment by ThomasWaldmann** [comment]
Writing operations acquire an exclusive write lock (and they won't get it while there is a shared read lock).

Reading operations acquire a shared read lock (and they won't get it while there is an exclusive write lock).

So yes, as long as everything is just reading with shared locks, we are fine.
