### ISSUE TITLE
borg-freebsd64 binary: Cannot open self

### ISSUE THREAD

**Issue by breyer** [borgbackup/borg#336]
Hi,

i switched from the pip installation to the borg-freebsd64 binary.
After installation i receive following error:

>root@muenchen:/home/mono # borg
>Cannot open self /usr/home/mono/borg or archive /usr/home/mono/borg.pkg

it does't occurs if i start borg like that:

>root@muenchen:/home/mono # /usr/local/bin/borg
>usage: borg [-h]
>            {serve,init,check,change->passphrase,create,extract,rename,delete,list,mount,info,prune,upgrade,help}
>           ...
>Borg 0.27.0 - Deduplicated Backups
>
>optional arguments:
> -h, --help            show this help message and exit
>
>Available commands:
>  {serve,init,check,change->passphrase,create,extract,rename,delete,list,mount,info,prune,upgrade,help}

Not sure what the problem is, but found a similar issue with docker-compose here:
https://github.com/docker/compose/issues/1135
May this helps to solve this issue.

FreeBSD version:
>root@muenchen:/home/mono # uname -a
>FreeBSD muenchen 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

Thanks
Mark

**Comment by ThomasWaldmann** [comment]
please add this information:
```
echo $PATH
ls -ld /home /home/mono
which borg
cd /usr/local/bin
ls -l borg
gpg --verify borg.asc  # put the signature right besides the binary first
```

**Comment by breyer** [comment]
Importing your public key:
```
gpg --recv-keys FAF7B393
```

here the result:
```
root@muenchen:/usr/local/bin # echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
root@muenchen:/usr/local/bin # ls -ld /home /home/mono
lrwxr-xr-x  1 root  wheel     8 Oct 22 15:40 /home -> usr/home
drwxr-xr-x  3 mono  mono   1024 Oct 23 14:20 /home/mono
root@muenchen:/usr/local/bin # which borg
/usr/local/bin/borg
root@muenchen:/usr/local/bin # cd /usr/local/bin
root@muenchen:/usr/local/bin # ls -l borg
-rwxr-xr-x  1 root  wheel  9642975 Oct  7 14:42 borg
root@muenchen:/usr/local/bin # gpg --verify borg.asc
gpg: assuming signed data in 'borg'
gpg: Signature made Wed Oct  7 14:41:54 2015 CEST using RSA key ID 51F78E01
gpg: Good signature from "Thomas Waldmann <tw@waldmann-edv.de>" [unknown]
gpg:                 aka "Thomas Waldmann <tw-public@gmx.de>" [unknown]
gpg:                 aka "Thomas Waldmann <twaldmann@thinkmo.de>" [unknown]
gpg:                 aka "Thomas Waldmann <thomas.j.waldmann@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6D5B EF9A DD20 7580 5747  B70F 9F88 FB52 FAF7 B393
     Subkey fingerprint: 2F81 AFFB AB04 E11F E8EE  65D4 243A CFA9 51F7 8E01
```

**Comment by ThomasWaldmann** [comment]
ok, seems pretty ok. just wondering about this:
```
lrwxr-xr-x  1 root  wheel     8 Oct 22 15:40 /home -> usr/home
```
Could this cause issues? Should it be rather /home -> /usr/home?

**Comment by breyer** [comment]
hmm, don't think so. ```borg``` install via ```pip``` just works and other FreeBSD servers show me the similar listings:

```
root@paris:/home/mono # ls -ld /home /home/mono
lrwxr-xr-x  1 root  wheel   8 Jan 20  2015 /home -> usr/home
drwxr-xr-x  3 mono  mono   17 Oct 23 15:39 /home/mono
```
But i may be wrong?

**Comment by ThomasWaldmann** [comment]
Hmm, maybe it's unrelated to that home symlink (how it looks like depends on what you gave to ln -s).

Also, this has nothing to do with pip / running from source.

I suspect that the pyinstaller binary's "bootloader" has trouble to find the path to the binary file (to uncompress it to a temp location).

what does `cat /proc/curproc/file` output for you?

**Comment by breyer** [comment]
nothing:
```
root@muenchen:/ # ls -l /proc/curproc/file
ls: /proc/curproc/file: No such file or directory
```

**Comment by breyer** [comment]
after mounting:
```
root@muenchen:/ # mount -t procfs proc /proc
root@muenchen:/ # ls -l /proc/curproc/file
lr--r--r--  1 root  wheel  0 Oct 26 16:43 /proc/curproc/file -> /bin/ls
```

**Comment by ThomasWaldmann** [comment]
ah, progress. not fixed yet, but almost.

I added some comments there:
https://github.com/pyinstaller/pyinstaller/commit/d2e749f0d1fede80828c29837940a9269f596ebb

**Comment by htgoebel** [comment]
> Looks like we have to wait until pyinstaller is fixed

This can happen quick. Now that you already found all these issues, please submit a pull-request :-)

**Comment by ThomasWaldmann** [comment]
Seems like I become a freebsd user just to fix pyinstaller. :-)

**Comment by breyer** [comment]
You will not regret it ;)

**Comment by htgoebel** [comment]
> Seems like I become a freebsd user just to fix pyinstaller. :-)

Why not. Maybe I'll become a borgbackup user ...

**Comment by ThomasWaldmann** [comment]
Opened some pyinstaller issues:
https://github.com/pyinstaller/pyinstaller/issues/1634
https://github.com/pyinstaller/pyinstaller/issues/1635

**Comment by ThomasWaldmann** [comment]
To fix the freebsd exe build for borg, we either need the stuff fixed in master branch in the pyinstaller repo (== when they release 3.1) or switch to the develop branch in our vagrantfile: https://github.com/borgbackup/borg/blob/master/Vagrantfile#L221 in case we want to release before they have a new release in master.

**Comment by breyer** [comment]
IMHO take your time. It seems i'm the only one using FreeBSD. Will try to build a binary on my own this weekend. Thanks for your support!

Seems like i become a developer just to fix my issue ;)

**Comment by ThomasWaldmann** [comment]
Both issues should be fixed in pyinstaller develop branch now.

**Comment by ThomasWaldmann** [comment]
Crap, it's still broken.

**Comment by ThomasWaldmann** [comment]
https://github.com/pyinstaller/pyinstaller/pull/1661
