### ISSUE TITLE
Extracting a path with spaces fails

### ISSUE THREAD

**Issue by Cyuonut** [borgbackup/borg#338]
Borg (0.27.0) fails if you try to extract a path that has spaces. I verified this with multiple paths, and all with spaces failed. I tried it with quotes, apostrophes, backslashes in front of the spaces, and even double quoting and double backslashes, but no luck.

    $ borg extract -v repository::archive 'home/username/Desktop/This Has Spaces'
    
    borg: Warning: Include pattern 'home/username/Desktop/This' never matched.
    borg: Warning: Include pattern 'Has' never matched.
    borg: Warning: Include pattern 'Spaces' never matched.
    borg: Exiting with failure status due to previous errors

It clearly breaks the argument into pieces because of the spaces, whereas it should honour the quoting (of bash shell, in my case).

I'd provide you with a patch, but I'm not that familiar with the source.

**Comment by ThomasWaldmann** [comment]
Thanks for reporting this. Maybe duplicate to #141?

There is a FAQ item how to deal with non-ascii chars, guess it applies also to spaces - it's not a fix, but can be used until this is fixed:
http://borgbackup.readthedocs.org/en/latest/faq.html#i-can-t-extract-non-ascii-filenames-by-giving-them-on-the-commandline

**Comment by Cyuonut** [comment]
Thanks! Might be a duplicate of #141, sorry for not spotting it in the issues. I tried to search with "never matched", and found nothing.

Extracting the parent worked as expected, but isn't naturally the optimal choice, especially if consists of half a terabyte of data :)

BTW, you state in #141 that it works on Linux, but I'm using Ubuntu 15.04 with Linux kernel 3.13.0.

Please let me know if you want me to help with sorting this out.

**Comment by ThomasWaldmann** [comment]
Well, I don't remember precisely how I tested, maybe it was just writing / expanding that unit test "test_unsual_filenames" with a filename with blanks. But it is good to know that it happens on Linux also, so I don't need to search on cygwin.

**Comment by ThomasWaldmann** [comment]
Hmm, I can't reproduce with current master branch.

**Comment by ThomasWaldmann** [comment]
@Cyuonut what shell do you use? borg binary or from source?

**Comment by Cyuonut** [comment]
I've used pip3. The latest command line I found in history:
    $ pip3 install --upgrade borgbackup

Should I check the versions of the dependencies, too?

**Comment by Cyuonut** [comment]
I did it anyway:

    Name: msgpack-python
    Version: 0.4.6
    Location: /usr/local/lib/python3.4/dist-packages

    # pip3 install --upgrade msgpack-python
    Requirement already up-to-date: msgpack-python in /usr/local/lib/python3.4/dist-packages

**Comment by ThomasWaldmann** [comment]
python -V

**Comment by Cyuonut** [comment]
Python 2.7.9

**Comment by ThomasWaldmann** [comment]
ehrm, I mean the python you use with borgbackup (it doesn't work with python 2.x).

**Comment by Cyuonut** [comment]
$ python3 -V
    Python 3.4.3

**Comment by ThomasWaldmann** [comment]
Hmm, I tested also with 3.4.3. Your shell?

**Comment by Cyuonut** [comment]
$ bash --version
    GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

**Comment by ThomasWaldmann** [comment]
I have: GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

I'll quickly try to write some test code so we can see whether it is the shell...

**Comment by Cyuonut** [comment]
Thanks!

**Comment by ThomasWaldmann** [comment]
See my previous comment.

**Comment by Cyuonut** [comment]
$ python3 test_cmdline.py foo bar 'boo baz'
    ['test_cmdline.py', 'foo', 'bar', 'boo baz']

Seems to work correctly.

**Comment by ThomasWaldmann** [comment]
Hmm, now it's getting weird. Is somehow a Mac (OS X) machine involved in this at your side? Or asked differently: could it be that your blanks are not the same character in the archive and what you type in?

**Comment by Cyuonut** [comment]
No, not Mac, but hey, I should have mentioned this: The repository is on a Samba share (mounted with mount.cifs + mapchars) on a LaCie Network Space drive. It has worked normally with other software, but this might be the reason. I'll do a couple of tests now and will get back to this.

**Comment by ThomasWaldmann** [comment]
another code to test:
```
$ cat test_cmdline.py 
import sys, argparse

parser = argparse.ArgumentParser()
parser.add_argument('arg1')
parser.add_argument('arg2')
args = parser.parse_args()
print(args)

$ python test_cmdline.py 'foo bar' baz
Namespace(arg1='foo bar', arg2='baz')
```

**Comment by Cyuonut** [comment]
$ python test_cmdline.py 'foo bar' baz
    ['test_cmdline.py', 'foo bar', 'baz']
    Namespace(arg1='foo bar', arg2='baz')

**Comment by ThomasWaldmann** [comment]
The repo location on samba should not matter, any metadata (like filenames) is *inside* rather harmless segment files in the repo. Where did the file with blanks in the name originate from (OS, filesystem)?

**Comment by ThomasWaldmann** [comment]
Hmm, maybe I am running in wrong direction. Your first post has rather clearly shown that borg considers the 1 filename as multiple ones. And we don't know why yet.

**Comment by ThomasWaldmann** [comment]
Ah, one comment: if I do "python", it is always python3. But you need to invoke python3 explicitely.

**Comment by ThomasWaldmann** [comment]
btw, if you have IRC: #borgbackup :)

**Comment by Cyuonut** [comment]
About python3: Tested with explicit python3, and the results were the same.

About Samba+metadata: Yes, that's what I thought, but wanted to tell it. The files originate from the same computer as the one I'm trying to restore to.

I did a more local test, and here are the results:

    $borg init --encryption=repokey testborg
    Key in "<Repository /home/boman/testborg>" created.
    Keep this key safe. Your data will be inaccessible without it.
    Synchronizing chunks cache...
    Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
    Done.

    $borg create -s -v -p -C lz4 testborg::`date +'%Y-%m-%d_%H-%M-%S'` Desktop/This\ Has\ Spaces/
    borg: Desktop/This: [Errno 2] No such file or directory: 'Desktop/This'
    borg: Has: [Errno 2] No such file or directory: 'Has'
    borg: Spaces: [Errno 2] No such file or directory: 'Spaces'

So, the creation renders the same error.

I will have to get some sleep soon, but I'll be back with testing tomorrow! Thanks for the help! I'll try to make it wortwhile.

**Comment by ThomasWaldmann** [comment]
ok, thanks so far! good night!

**Comment by ThomasWaldmann** [comment]
Note: we need to try again with `from borg.support import argparse` (I needed to bundle a argparse.py from 3.2.6 to fix a breakage on early 3.2.x pythons). That argparse version might have different bugs than the one that comes with 3.4.3.

**Comment by Cyuonut** [comment]
```
$ cat >> test_cmdline.py 
import sys
from borg.support import argparse

parser = argparse.ArgumentParser()
parser.add_argument('arg1')
parser.add_argument('arg2')
args = parser.parse_args()
print(args)

$ python3 test_cmdline.py 'foo bar' baz
['test_cmdline.py', 'foo bar', 'baz']
Namespace(arg1='foo bar', arg2='baz')
```

**Comment by Cyuonut** [comment]
```
$ python3 test_cmdline.py testborg::`date +'%Y-%m-%d_%H-%M-%S'` Desktop/This\ Has\ Spaces/
['test_cmdline.py', 'testborg::2015-10-27_10-06-20', 'Desktop/This Has Spaces/']
Namespace(arg1='testborg::2015-10-27_10-06-20', arg2='Desktop/This Has Spaces/')
```

**Comment by ThomasWaldmann** [comment]
@Cyuonut thanks for testing again. guess the next step is to remove (your) bash from the equation. can you try with some other shell?

**Comment by Cyuonut** [comment]
Worked. And then I found out the problem, too. I had an old attic (and then borg) wrapper script that didn't handle the quoting correctly, and I had forgotten about it. I'm very sorry for the trouble! I'll make it up to you by filing proper bug reports in the future :)

**Comment by ThomasWaldmann** [comment]
was this an own script or something "public"?

**Comment by Cyuonut** [comment]
Home-brewed, so no need to file reports elsewhere.
