### ISSUE TITLE
Binary for ARM platform

### ISSUE THREAD

**Issue by Spheerys** [borgbackup/borg#3386]
Hi,

Could be possible to have a binary for the ARM architecture ?
A lot of low cost servers (such provided by Scaleway) are using ARM processors and for all actual Ubuntu/Debian versions, we can't have secure Borg version > 1.0.9 easily
Ubuntu extra Borg repository don't provide either ARM package !!

Thanks !

**Comment by ThomasWaldmann** [comment]
Search the issue tracker and you'll find some ARM offers.

Personally, I won't build arm binaries except if I could do it on a x86/x64 host (preferably via vagrant).

I recently tried via qemu, but it is way too slow.

**Comment by ThomasWaldmann** [comment]
BTW, for older ARM cpus, you'll need 1.1.3 (available tomorrow).

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/community/ (search for ARM)

**Comment by ThomasWaldmann** [comment]
as it is linked from community repo, I am closing this.

**Comment by noplanman** [comment]
Just to let everybody here know, that I've managed to set up a docker solution for building binaries for all types of architectures.

Take a look here: https://git.feneas.org/noplanman/borg-binary-builder

I'm also looking into a solution for providing signed binaries directly, without requiring to do the whole docker operation for every new version.
