### ISSUE TITLE
Reading files cache.... forever

### ISSUE THREAD

**Issue by tobecwb** [borgbackup/borg#3394]
So, I was trying to use BorgBackup to do a backup of 15TB of data.

This backup is huge, and has several millions of small files (more than 8 millions of files in total).

I tried to create the first backup of all files...
Create a shell script to do the backup of some directories on same repository... with default compression
like:

`borg create --stats --progress /mnt/repo/borg::FTP-{now:%Y-%m-%dT%H:%M:%S} /mnt/files/FTP`
`borg create --stats --progress /mnt/repo/borg::TEMPLATES-{now:%Y-%m-%dT%H:%M:%S} /mnt/files/TEMPLATES`
`borg create --stats --progress /mnt/repo/borg::PUBLIC-{now:%Y-%m-%dT%H:%M:%S} /mnt/files/PUBLIC`
....

Until now, taking 4 days to backup (files on a raid 6 - 80tb -, on same machine, cache on a SSD drive on same machine too, repository on same raid - yes, I know this is wrong) and not finished yet.
Then, I have to cancel the backup, and later tried to resume the backup...

when I start the borg, I receive the following message:
`Reading files cache ....` and this is taking forever...
until now, this message was on screen for more than 8 hours.

I already tried to use the `--debug` to discover if something is wrong, but everything seens to be ok, only taking forever to read the cache...

This is a normal behaviour? 
I known that to do backup of several small files can be problematic and slow, and that it's better to do a image backup, but there's a way to know if something is wrong?

Why I don't to a image backup: The server was configured by another person in this way (all 80tb is on the same partition, and all files on a single partition). I have only 30tb on a NAS, and already has some backups of this data on NAS.
If I wanna to do a image backup, I must delete all the backup on NAS to free space and to a image backup.

**Comment by ThomasWaldmann** [comment]
Check memory usage of borg. Is it using more than you have as physical memory?

If you have a gazillion of files, the files cache might use big amounts of memory. You can run borg without files cache, but it will be slower then for backups of unmodified data.

1.0: --no-files-cache
1.1: --files-cache=disabled

**Comment by tobecwb** [comment]
No, it's using almost nothing of memory...
something like 500mb only (the server has 16gb)

what's I don't get its taking like forever for a directory with few files!
I already backup eight directories in same repository.... some are big, some are small... (in size and number of files)...
now I'm trying to backup a directory with only 127 files, but with 1.5tb of data... this is taking more time than others

**Comment by ThomasWaldmann** [comment]
Well, when it first backs up large files, it has to read them completely.
Same thing happens if the files cache doesn't work or is disabled.

**Comment by ThomasWaldmann** [comment]
Without more information, ticket is not actionable.
It's not even clear whether there is a problem or whether just the first file takes a lot of time due to its size.

Reopen if you have more information.

**Comment by tobecwb** [comment]
Sorry for very long delay to reply this...
I had given up to use borg, but some days ago, I tried again with latest version...
still the same problem!

to best describe this, my file server has the following dirs, with size and number of files (approximated values):

- PROJECTS -> 7698893 files / 12Tb
- PgSQL -> 8 files / 901GB
- SqlServer -> 999 files / 307GB
- PUBLIC -> 865965 files / 766GB
- Test -> 120 files / 2GB (create just to test Borg with some random files)
- Templates -> 40443 files / 15GB
- ServerImages -> 116 files / 2TB
- Info -> 175074 files / 528GB

after 3 weeks doing a initial backup (each directory as a different backup, but all in same repository), the initial backup of all dirs finished.

Now, I want to do a new backup of 'Test' dir (the smallest dir)... when I execute:
`borg create --list --progress --stats --files-cache=mtime,size /BACKUP_REPO::Test-{now:%Y-%m-%d} /Test/`, the backup start and got freeze with all zero stats:

`0 B O 0 B C 0 B D 0 N Test`

until now, I was waiting for more than 3 hours to start this new backup


The filesystem is NTFS, and the server is a Windows Server with cygwin and borg (I know borg officially don't support Windows).

Currently, the memory usage is something about 1.5GB

**Comment by tobecwb** [comment]
some debug information

`borg create --debug --list --progress --files-cache=mtime,size /BACKUP_REPO::Test-{now:%Y-%m-%d} /Test/`

```
using builtin fallback logging configuration
35 self tests completed in 0.25 seconds
Verified integrity of /BACKUP_REPO/index.15134
TAM-verified manifest
security: read previous location '/BACKUP_REPO'
security: read manifest timestamp '2018-03-07T10:21:13.415497'
security: determined newest manifest timestamp as 2018-03-07T10:21:13.415497
security: repository checks ok, allowing access
Verified integrity of /c/Users/Administrador/.cache/borg/4d652aea67c6454cc46fb20242ad09d56ff2a5526f206794c39a1c150786cff9/chunks
security: read previous location '/BACKUP_REPO'
security: read manifest timestamp '2018-03-07T10:21:13.415497'
security: determined newest manifest timestamp as 2018-03-07T10:21:13.415497
security: repository checks ok, allowing access
Reading files cache .../Test
'''

after this, no new messages for several hours until now.

**Comment by ThomasWaldmann** [comment]
@tobecwb borg version you used for latest test?

**Comment by tobecwb** [comment]
Borg 1.1.4
The initial backup was created using the same version

**Comment by ThomasWaldmann** [comment]
borg 1.1.4 would say "Verified integrity of [files cache location]" after reading the files cache.
So, if it did not emit that msg yet, it is still reading the files cache...

Did you recently see a warning about slow msgpack? What msgpack version do you have installed?

**Comment by tobecwb** [comment]
Until now still in `Reading files cache`.
No message about "Verified integrity of [files cache location]"

the msgpack that was installed is version 0.5.5

**Comment by ThomasWaldmann** [comment]
I also need the Python version you use for borg.

Some recent msgpack versions that came out after borg 1.1.4 made some troubles because they were either broken or at least caused unexpected compatibility issues. Also they dropped testing on Python 3.4 after msgpack 0.5 while borg 1.1 still allows py34. Also the pypi package was renamed from msgpack-python to msgpack.

Borg 1.1.5 will therefore have a more restrictive msgpack-python >= 0.4.6, < 0.5.0 requirement to avoid any msgpack issues causes by these recent changes in msgpack.

Note that I am not saying that msgpack 0.5.5 is broken, but rather that it is untested.

So could you try:
```
# get rid of installed msgpack(-python)
pip uninstall msgpack
pip uninstall msgpack-python
# install a known-good msgpack-python version
pip install -v 'msgpack-python<0.5.0'
```
Please carefully read the log output of the last command whether there are any compiler issues or so.

Then try again to make that small backup.

**Comment by ThomasWaldmann** [comment]
https://github.com/msgpack/msgpack-python/blob/master/ChangeLog.rst

**Comment by tobecwb** [comment]
Python is version 3.6.4.

removed the msgpack and msgpack-python and installed msgpack-python<0.5.0

trying right now the small backup!
started now, and still in 'Reading files cache'...
wait a couple more minutes (or hours)

**Comment by ThomasWaldmann** [comment]
As you have > 8 million files and they are all read from files cache and put into an in-memory python dictionary, it is expected that this takes quite a while and eats quite some RAM. Maybe about 8M * 240B, that is roughly 2GB memory only for the files cache dict in the end (memory needs for this dict should grow from 0 to the final value while it is reading the files cache and there might be peaks when python is resizing the dictionary).

The chunks cache and other stuff will also need some memory.

It is important that you don't use the pure python msgpack implementation (borg would warn about slow msgpack if that is the case).

**Comment by tobecwb** [comment]
So, in this case, if a has several small dirs, but the sum of all dirs has millions of files, the recommendation is create several repositories?

Take my case..
I have a huge dir with more than 7 millions of files, and several small dirs with less than 100 files...
each time I wanna to backup a small dir, I will have to wait several minutes / hours just for each dir, even if this dir has only 10 files and 1GB.

suppose that I wanna to backup `PgSql`, `SqlServer`, and `Test`, and borg take 2 hours to read the cache...
at minimium, I will have to wait at least 6 hours just to borg read cache files (2 hours at each dir)

**Comment by tobecwb** [comment]
after almost 2 hours (01:42 to be exactly), borg finished read the cache files...
got 3 new/modified files, saved everything in less than 10 seconds
and now, saving cache files for more than 30 minutes

for me, I think this is a performance problem... i really don't know
the backup take more time saving and reading cache than doing the backup of files

**Comment by ThomasWaldmann** [comment]
Borg can work without the files cache, but performance-wise that likely won't help, rather harm.

Did you check whether the RAM usage exceeds the physical RAM at any time?

The highlevel code reading the files cache is python, the lower levels (in msgpack, in python dict) is C.

**Comment by tobecwb** [comment]
The peak memory usage was 2.5GB

until now saving cache files...
almost 4 hours to backup only 3 .txt files that sum less than 100kb

the big problem here was the time to read the cache files and save cache files...
I was checking the size of cache files when saving, and I see that borg, for some reason, appears that save the cache file two times..

when borg show "saving files cache", the file "files" on cache got 0kb, and was increasing with time...
when got 700mb or more, I don't know what happens, but the file got 0kb again, and now is increasing again..

if I disable cache, borg will not backup everything again?
so, if I wanna backup all again, it will take another 3 weeks or more

What I really don't get is why the entire files cache must be loaded on memory...
I was thinking something like redis, or some type of database that don't need to be loaded entirely on memory...
but this is out of scope of this issue

**Comment by ThomasWaldmann** [comment]
Guess the best you could do right now is to splitt off the huge files collection in projects to a separate repo.

**Comment by ThomasWaldmann** [comment]
The effect you observed at 700MB is interesting, have to check that.

**Comment by ThomasWaldmann** [comment]
Maybe you could reduce the files cache size a bit by reducing the number of "generations", see borg env vars docs. But don't go too low of stuff will get kicked from cache before it is needed again.

**Comment by ThomasWaldmann** [comment]
Hah, I guess I've found something.

The timer that controls the checkpointing is initialized when creating the Archive instance (very early).
The files cache is loaded later, on demand, when the first file gets processed.
So, if loading the files cache takes considerable time as in your case, borg will make the first checkpoint save too early (in the worst case right at the beginning when it starts actually archiving files).

If it does not have to back up much (only few files to check for changes, only few/small files changed) and the files cache loading takes > 30 mins, you will get the observed double-save effect.

**Comment by tobecwb** [comment]
tks for all the help @ThomasWaldmann 
until the cache process take more time than the backup itself, I will split my backup data in two or more repositories.

**Comment by ThomasWaldmann** [comment]
The timer issue was fixed in 1.1-maint by #3672.

**Comment by ThomasWaldmann** [comment]
I am going to close this now, as the only obvious bug was fixed.

Summarizing the speed tuning tips if somebody observes slow files cache loading:
- check memory needs and available memory, borg must not run out of physical RAM
- have huge file count data sets in separate repos because the files cache will be huge also and loading that takes time.
- use borg 1.1.5+ after it is released.

**Comment by ThomasWaldmann** [comment]
Another note about slowness in this case:

The default `--checkpoint-interval` is 1800s == 30mins.

So if saving the files cache would take 100mins(?), the whole backup becomes rather inefficient because it would need 3times more time for checkpointing than for actually backing up files.
