### ISSUE TITLE
remaining build_man issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3398]
```
(borg-env) tw@tux:~/w/borg$ python setup.py build_man
running build_man
...
building man page borg-prune(1)
docs/virtmanpage.rst:145: (ERROR/3) Unknown directive type "highlight".
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.. highlight:: none
```

The problem is that this will put some ugly error text into the resulting man page also.

The fix likely is not just removing the highlight directive as we likely need it for the html docs.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/52118992-remaining-build_man-issue)

**Comment by milkey-mouse** [comment]
See #3364 for more info
