### ISSUE TITLE
Archive does not exists (borg 1.0.11)

### ISSUE THREAD

**Issue by cipress** [borgbackup/borg#3401]
First i created a borg repo with init
then `sudo borg create ... /path/to/repo::'{hostname}-{now}'`
the result of command: `borg list /path/to/repo` is:
askme-2017-11-30 10:27:49.631768     Thu, 2017-11-30 10:27:53

when I try to: `borg list /path/to/repo::askme-2017-11-30`
shell returns: Archive askme-2017-11-30 does not exist

**Comment by Siassei** [comment]
@cipress The output is correct. The repository `borg list /path/to/repo::askme-2017-11-30` **does not** exsit! You forgot the time!

e.g. is correct
`borg list "/path/to/repo::askme-2017-11-30 16:43:16,2345"`

borg docs

> **{now}**
> The current local date and time, by default in ISO\-8601 format.
> You can also supply your own \fI\%format string\fP, e.g. {now:%Y\-%m\-%d_%H:%M:%S}

**Comment by cipress** [comment]
Thanks and sorry for opening, next time I must read carefully the docs :D

**Comment by Siassei** [comment]
nope, there are **only** stupid answer. no stupid questions! ;)
