### ISSUE TITLE
borg borgfs?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3404]
http://borgbackup.readthedocs.io/en/stable/usage/borgfs.html

- strange headline
- strangeusage

```
borg borgfs

borg [common options] borgfs [options] REPOSITORY_OR_ARCHIVE MOUNTPOINT [PATH...]
```

**Comment by milkey-mouse** [comment]
Hmm, I thought I explicitly prevented that in my borgfs PR. I'll take another look...

**Comment by milkey-mouse** [comment]
The page is not listed in the TOC, but does show up in a search, which I didn't account for. I thought borgfs didn't need its own docs page when `borg mount` is the same thing, but I didn't actually prevent the page from being generated.
