### ISSUE TITLE
LZ4 micro opt: memoryview -> bytes transform

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3412]
https://github.com/borgbackup/borg/blob/1.1.3/src/borg/compress.pyx#L135

there it transforms to bytes rather early, before invoking `super().decompress(data)` (which would happily work with memoryviews also). the bytes requirement is only for the lz4 decompressor.

we could save creation/destruction of one (potentially large) bytes object by doing the bytes transform after the super call.

**Comment by enkore** [comment]
```        # strip ID bytes
return data[2:]``` will copy for bytes.

**Comment by ThomasWaldmann** [comment]
The point was that data before that operation can be a memoryview, so it does not need to be transformed to a bytes object before that.

**Comment by ThomasWaldmann** [comment]
The same issue also applies to the ZSTD code, same situation there.
