### ISSUE TITLE
Laptop backup 

### ISSUE THREAD

**Issue by freeseacher** [borgbackup/borg#3419]
Is borgbackup capable to backup laptop to nfs share ? 

I have an linux mint laptop with encrypted home option. I want to backup to nfs or cifs share with some tool. 
I have a policy to backup it every day at about 22:00. I want block backup(xfs/lvm snap) of root and usr partitions and file backup with encryption of home folder. 
i want get back to about a week for a home folder and have usb drive to restore laptop in case of root corruption. 

But there are few things to mention. 
* Sometimes nfs share is not available because it is located at home. 
* during backup i can close the laptop and it will go to sleep mode
* after awake environment will probably changed. 

can borgbackup help me ?

**Comment by ThomasWaldmann** [comment]
You can do that, but you have to add some scripting around the borg core (maybe have a look into the community repo for someone else' scripts).

Some hints:

- doing snapshots is outside of borg's scope, do it yourself
- same for checking whether your mounts are there
- --read-special can read your block device (but it will be less efficient than a normal file backup)
- if you put the machine to sleep while it is backing up, it might just continue running the current backup after resume. if the mount does not work any more, I guess it will just crash with some exception, but that's shouldn't do any harm.

**Comment by freeseacher** [comment]
looks legit but i am looking for utility that will do it out of the box.

that issue can be closed. tnx

**Comment by ThomasWaldmann** [comment]
good luck with that.
