### ISSUE TITLE
borg delete <repo> doesn’t delete BORG_SECURITY_DIR/<repodir>

### ISSUE THREAD

**Issue by leuler** [borgbackup/borg#3427]
I just started using borgbackup and tested a few things with throwaway repositories. I noticed that deleting a repository (using `borg delete`) does not delete its subdirectory below BORG_SECURITY_DIR. Is that intentional?

**Comment by ThomasWaldmann** [comment]
No, guess that was forgotten when adding the security dir.

@enkore ^

**Comment by ThomasWaldmann** [comment]
Note: in the current fix (see above), the security dir is only deleted when the repo is deleted.

I am asking myself whether it should be also done when `borg delete --cache-only` is used or whether we need something like `--security-only` additionally.
