### ISSUE TITLE
does borg plan to support openwrt/LEDE platform?

### ISSUE THREAD

**Issue by moralrebuild** [borgbackup/borg#3430]
I'm using a Netgear R7800 w/ LEDE 17.01.4 which I think is modern and powerful enough to serve as backup server. But I couldn't find any information about how to setup the borg server on home router.

root@LEDE:/# uname -a
Linux LEDE 4.9.58 #0 SMP Thu Nov 16 11:54:17 2017 armv7l GNU/Linux
root@LEDE:/# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 12.50
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32
CPU implementer : 0x51
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x04d
CPU revision    : 0

processor       : 1
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 12.50
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32
CPU implementer : 0x51
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x04d
CPU revision    : 0

Hardware        : Generic DT based system
Revision        : 0000
Serial          : 0000000000000000

**Comment by RonnyPfannschmidt** [comment]
for the server side, ram is more of a must than cpu, how much memory does the router have?
and does it support ssh?

**Comment by moralrebuild** [comment]
@RonnyPfannschmidt OpenWrt/LEDE definitely supports ssh. This router model has 512MB RAM. One of my VPS with the same amount of RAM hosts a doze of services including borg and it works perfectly.

root@LEDE:/# free -m
              total        used        free      shared  buff/cache   available
Mem:            468         163          91           1         213         254
Swap:             0           0           0

**Comment by ThomasWaldmann** [comment]
I can't recommend running borg on such platforms (except if you know for sure your backup repo will stay rather small).

Even `borg serve` needs memory proportional to the amount of chunks in the repo (see formula in docs), so if your repos grows over time, you may run out of memory at some time (even if it initially worked).

If that happens and you have no means to upgrade memory, it's game over on that machine.

This can even be a problem on stuff like raspberry pi (where you have up to 1GB memory), but same basic problem: no upgrade possible.

Swap space might seem like a means to (slowly) work around the problem, but hashtable access patterns can be quite random, so swapping might perform even worse than usual.

Besides that, there are also some other frequent issues on SBC like all I/O going over USB2 (rpi).

Even some older / low power NAS devices with little (non-upgradeable) memory can be problematic.

**Comment by moralrebuild** [comment]
@ThomasWaldmann  For this router, it provides two USB 3.0 ports and one eSATA port. So far, one 4TB West Digital HDD connected to the router. In theory, 12TB or more NAS backup storage can be provided. If borg is designed as you explained, I doubt if it deserves the reputation it earned. Demanding very large RAM to achieve acceptable speed looks not so reasonable. I know deduplication probably has a cost. But does the increased cost make sense?

**Comment by ThomasWaldmann** [comment]
@moralrebuild It makes a lot of sense to many users.

And it's not our fault if people run stuff on underpowered machines (or build unbalanced machines, like little RAM, but many TB of disk) - the resource usage is documented.

I am closing this ticket now, as it was answered.

**Comment by ArchangeGabriel** [comment]
A [Turris Omnia](https://omnia.turris.cz/en/) is likely a better option if you want to have a nice OpenWRT/LEDE router with NAS functionality (they even have an optional NAS case, and you can have SATA on-board) and a “lot” of RAM (1 GB or 2 GB available).

**Comment by ThomasWaldmann** [comment]
One last comment: if the machine that has the repo files is low on RAM, one can of course expose the repo via NFS (or SMB or ...) and mount it on the machine that does get backed up with borg, so it can directly access the borg repo.

In that case, you only need memory for the NFS/SMB server process, there is no `borg serve`.

That method comes with the disadvantage that some operations take longer and cause more network traffic because there is no borg agent on the server side. The repository index will be loaded by the "client" then and will require more memory there than when running borg-client/borg-server.

**Comment by moralrebuild** [comment]
@ArchangeGabriel Thanks for sharing the information of a nice box, but it looks only be available on a number of countries, not globally. Besides it depends a customized OpenWrt, not surrendering their codes to the trunk.

**Comment by moralrebuild** [comment]
@ThomasWaldmann Thanks for your clear explanation and good suggestions. Now I'm going with sshfs for Windows, hope it will work. Thanks for your great contributions on this wonderful project.
