### ISSUE TITLE
create --progress --stats is defect in master branch

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3431]
```
0 B O 0 B C 0 B D 0 N home/tw/Downloads/gluon-ffs-1.0+2017-04-10-g.84dd03a-s.5cab37c-tp-link-tl-wr841n-nd-v9-sysupgrade.bin            
```

(that was NOT the first file, it's always 0 0 0 0)

**Comment by Maiestas28** [comment]
Hey, Im new to Python and this is my first time on Git. Can you guide me through what exactly is required here ? If this is too advanced you can let me know, I'l look for something else.

**Comment by ThomasWaldmann** [comment]
@Maiestas28 maybe first get more familiar with git and python (and python debugging), there are tutorials for both out there (and github also has good help IIRC).

**Comment by Maiestas28** [comment]
Got it. Thank you.

**Comment by Gu1nness** [comment]
Hi,
Can I pick this one ?

**Comment by ThomasWaldmann** [comment]
sure.
