### ISSUE TITLE
Add a possibility to silence borg not to ask any user confirmations

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#3438]
Certain borg commands require user intervention. At least in these situations borg (v1.1.3) asks user acceptance to continue:

1)  borg delete <repo> -command
```
borg delete <repo>
You requested to completely DELETE the repository *including* all archives it contains:
[info]                                                              		b01                                  Tue, 2017-12-12 12:56:07 [00385866a02382d78db5996befcbbc6f000cd9254579b0d238ac5b77b322390e]
[info]                                                              		b02                                  Tue, 2017-12-12 12:56:07 [01e7fdbdba4266f68d06e4fc36cbc12bfd833d8f454b34a5964529ff200b3c5a]
[info]                                                              		b-mod-bckp-01                        Tue, 2017-12-12 12:56:11 [cb06fdc054337bc48836fdaabdb1210c063898d252749acc1aa49a91e20dfd53]
[info]                                                              		b-mod-bckp-02                        Tue, 2017-12-12 12:56:12 [3a3bd2d7cc32356f629acbe4e7a697fbbd3960cacfbeaf7f82f4dbdc2742f37a]
[info]                                                              		b-mod-bckp-03                        Tue, 2017-12-12 12:56:13 [a4a1770290c86618810abda5b248ae4b416fed372aeead9c5378008c1fd63214]
[info]                                                              		Type 'YES' if you understand this and want to continue: Aborting.
```

2) After manual cache deletion or after repo id modification in borg config file every borg command require confirmation
```
borg list <repo>
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] 
```
Both these actions are needed e.g. when a borg repo is restored from backup media after HW/SW failure.

There may also be other borg commands that ask user acceptance.

These askings are valuable for interacticve user sessions but are problematic when borg is running from scripts or programs.

For scripting purposes there should be a possibility to silence all confirmation askings because scripts/programs are typically well tested and operations are done in purpose, not accidentally.

This "possibility" could be a new command line option or environment variable to read. 

This "possibility" could have values YES and NO. When YES is given and borg needs to ask acceptance, borg continues operation. When NO is given and borg needs to ask acceptance, borg exits with error code.

**Comment by ThomasWaldmann** [comment]
check the environment variables from the borg docs.

**Comment by jk-1** [comment]
It seems that this enhancement is already implemented! Thanks.

**Comment by ThomasWaldmann** [comment]
yup, closing.
