### ISSUE TITLE
Announcement channel

### ISSUE THREAD

**Issue by ovalseven8** [borgbackup/borg#3440]
Hello,

I just wanted to know if there is an announce-only channel for BorgBackup. I had a quick look on the website, but could not find anything.

What I mean is an announce-only mailing list or an RSS feed with information about new releases or important bugfixes like security vulnerabilities.

**Comment by dimejo** [comment]
https://github.com/borgbackup/borg/releases.atom

**Comment by ovalseven8** [comment]
Thanks!
