### ISSUE TITLE
have --batch option to avoid hanging cron jobs

### ISSUE THREAD

**Issue by jfburdet** [borgbackup/borg#345]
Hi,

I'm running borg from cron, and moved the repository and realized that now all my jobs where stuck since a few day to this :

"Warning: The repository at location /x/y/z  was previously located at /x/y Do you want to continue y/N ? "

Having a --no-confirm option and having borg accepting to run with this new location would be nice ... may be having some non-zero exit value.

That should apply to all command that could display this message (list, prune, etc ?)

**Comment by ThomasWaldmann** [comment]
That plus another confirmation question about unknown unencrypted repos are security critical questions, you do not really want to automate that.

But in general having a `--yes` option that answers non-critical questions is a good idea, do you want to change your issue text in that way?

The "fix" to your original problem btw is to monitor the logs and deal with any issues coming up (there could be also lock or connection problems), not to hide / make it shut up about / proceed over any issues.

**Comment by jfburdet** [comment]
I see what you mean. My problem is that borg is waiting for user input, making the cron job to become stalled.

So may be another option is to have an option like --batch wich would make borg avoiding to ask "Yes or No" but quitting with an error level <> 0.

**Comment by ThomasWaldmann** [comment]
Ah, yes, `--batch` makes sense.

**Comment by ThomasWaldmann** [comment]
I just refactored the confirmation code into helpers.yes function.

There are 2 mechanisms related to unattended operations:
- env_var_override (say "yes" by some env var - used heavily by unit tests, but you maybe rather don't want to answer "yes" automatically to security critical questions. one can NOT use that mechanism currently to answer "no" automatically, see #355)
- default_notty value (new. if that value is given AND there is no tty, it will just return that value and not try to ask the user / read something from stdin)

**Comment by ThomasWaldmann** [comment]
No new --batch option, but hopefully your initial problem is fixed nevertheless (see commit comment).
