### ISSUE TITLE
Same repo used by two workstations, feasible?

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#3453]
Hi there!

First of all, thanks for `borg`! I've been using it for a while (with S3 as well) and I'm loving it, I think I finally found my to-go cross-platform backup solution, after using and trying a lot of stuff out there. 

I'd like to know if it's feasible to backup from two different workstations in the same repo. The reason is that I have two - a Linux and a macOS machine. On both of them I have a dir like:

* Linux: /home/me/code
* macOS: /Users/me/code

These dirs mostly contain the same code, sometimes macOS might have a new projects or files or Linux might. What's I'd like to do is to have the same borg repo synchronized or in a network drive, and then create daily backups for both workstations in the same repo. Why? Well, to reduce the space used and dedup, since ultimately I push (sync) the repo to S3.

Each daily backup would be run in a cron on those machines and have a different prefix - `linux-<timestamp>` for Linux and macOS-<timestamp>` for macOS.

Is it something that's recommended? Any pitfalls of doing that? I'd love to hear your insights.

Cheers!

**Comment by FelixSchwarz** [comment]
The most obvious disadvantage to me is that you can't do concurrent backups to the same repo.

**Comment by ThomasWaldmann** [comment]
Also, there will by a cache resync frequently (iirc this is also in faq).

I'ld advise to not name the archives linux and macos, but to use the hostname rather.
It could happen that you have more linux and macos machines at some time.

**Comment by fullofcaffeine** [comment]
Thank you for the insights, I'll try it out!
