### ISSUE TITLE
Exclude doesn't seem to work for paths with a space

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#3457]
Hi,

I'm trying to exclude the `VirtualBox VMs` dir from a backup, the dir is at `/home/fullofcaffeine/VirtualBox VMs`. My exclude file has a line with `/home/fullofcaffeine/VirtualBox\ VMs`. However, when I `create` a new backup, borg is adding the files in this dir:

![screenshot from 2017-12-17 20-50-03](https://user-images.githubusercontent.com/81248/34087942-e65fb45e-e36b-11e7-90e3-08a76643f21e.png)

Any hints? Maybe I'm using the wrong syntax to escape the space char?

Also, where can I find the reference for what each letter prefix means (like the `d` and `A` that appears before each file in the list)?

Thanks in advance!

**Comment by ThomasWaldmann** [comment]
Try no \.

On December 18, 2017 3:50:59 AM GMT+01:00, Marcelo de Moraes Serpa <notifications@github.com> wrote:
>Hi,
>
>I'm trying to exclude the `VirtualBox VMs` dir from a backup, the dir
>is at `/home/me/VirtualBox VMs`. My exclude file has a line with
>`/home/me/VirtualBox\ VMs`. However, when I `create` a new backup, borg
>is adding the files in this dir:
>
>![screenshot from 2017-12-17
>20-50-03](https://user-images.githubusercontent.com/81248/34087942-e65fb45e-e36b-11e7-90e3-08a76643f21e.png)
>
>Any hints? Maybe I'm using the wrong syntax to escape the space char?
>
>Also, where can I find the refernece for what each letter prefix means
>(like the `d` and `A` that appears before each file in the list)?
>
>Thanks in advance!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/3457

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dimejo** [comment]
> Also, where can I find the refernece for what each letter prefix means (like the d and A that appears before each file in the list)?

http://borgbackup.readthedocs.io/en/stable/usage/create.html#item-flags

**Comment by ThomasWaldmann** [comment]
So, did it work?

**Comment by fullofcaffeine** [comment]
Sorry, I haven't had the time to test it again. I'll do so at some point this week and report back. Thanks a lot for the quick reply.

**Comment by ThomasWaldmann** [comment]
i am closing this for now due to lack of feedback.
it's likely solvable as proposed.
if it doesn't work when you try it, just re-open the issue and give more information.

**Comment by fullofcaffeine** [comment]
@ThomasWaldmann Had time to test again, removing the `\` fixes the issue. Thanks.

**Comment by amarendra** [comment]
I am still facing this issue. Neither `….../My Documents`, nor `….../My\ Documents` works (same behaviour with `~` or without). (Mac; borg 1.1.10).

**Comment by ThomasWaldmann** [comment]
@amarendra this issue is about entries in an exclude FILE. Do you use a separate exclude file?

If not, you likely just have an issue with your shell (passing parameters correctly from shell to borg).
Correct quoting / escaping should solve that. If not, open a new issue and give all details.
