### ISSUE TITLE
Confusing error message from borg init

### ISSUE THREAD

**Issue by DarthGandalf** [borgbackup/borg#3465]
If user doesn't have access to write to `/path`, this happens:
```
$ borg init -e keyfile /path
A repository already exists at /path.
```
borg 1.1.3

**Comment by ThomasWaldmann** [comment]
```
(borg-env) tw@tux:~/w/borg$ borg -V
borg 1.1.3
(borg-env) tw@tux:~/w/borg$ sudo mkdir inaccessible
(borg-env) tw@tux:~/w/borg$ sudo chmod 700 inaccessible
(borg-env) tw@tux:~/w/borg$ borg init -e none inaccessible/repo
Local Exception
Traceback (most recent call last):
  File "/home/tw/w/borg/src/borg/archiver.py", line 4157, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 4089, in run
    return set_ec(func(args))
  File "/home/tw/w/borg/src/borg/archiver.py", line 136, in wrapper
    with repository:
  File "/home/tw/w/borg/src/borg/repository.py", line 176, in __enter__
    self.create(self.path)
  File "/home/tw/w/borg/src/borg/repository.py", line 239, in create
    os.mkdir(path)
PermissionError: [Errno 13] Permission denied: '/home/tw/w/borg/inaccessible/repo'

Platform: Linux tux 4.14.4-tux3 #4 SMP Sun Dec 10 00:14:27 CET 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.3  Python: CPython 3.5.2
PID: 6981  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'init', '-e', 'none', 'inaccessible/repo']
SSH_ORIGINAL_COMMAND: None

(borg-env) tw@tux:~/w/borg$ borg init -e keyfile inaccessible/repo-kf
Local Exception
Traceback (most recent call last):
  File "/home/tw/w/borg/src/borg/archiver.py", line 4157, in main
    exit_code = archiver.run(args)
  File "/home/tw/w/borg/src/borg/archiver.py", line 4089, in run
    return set_ec(func(args))
  File "/home/tw/w/borg/src/borg/archiver.py", line 136, in wrapper
    with repository:
  File "/home/tw/w/borg/src/borg/repository.py", line 176, in __enter__
    self.create(self.path)
  File "/home/tw/w/borg/src/borg/repository.py", line 239, in create
    os.mkdir(path)
PermissionError: [Errno 13] Permission denied: '/home/tw/w/borg/inaccessible/repo-kf'

Platform: Linux tux 4.14.4-tux3 #4 SMP Sun Dec 10 00:14:27 CET 2017 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.3  Python: CPython 3.5.2
PID: 7025  CWD: /home/tw/w/borg
sys.argv: ['/home/tw/w/borg-env/bin/borg', 'init', '-e', 'keyfile', 'inaccessible/repo-kf']
SSH_ORIGINAL_COMMAND: None
```

Can't reproduce.

**Comment by DarthGandalf** [comment]
Ah, I found that error too now, when trying to reproduce this. Here are more complete steps:
```
$ cd /tmp
$ sudo mkdir inaccessible
$ ls -ld inaccessible
drwxr-xr-x 2 root root 4096 Dec 20 13:47 inaccessible
$ borg init --encryption=keyfile /tmp/inaccessible
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 4157, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 4089, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.5/site-packages/borg/archiver.py", line 136, in wrapper
    with repository:
  File "/usr/lib64/python3.5/site-packages/borg/repository.py", line 176, in __enter__
    self.create(self.path)
  File "/usr/lib64/python3.5/site-packages/borg/repository.py", line 240, in create
    with open(os.path.join(path, 'README'), 'w') as fd:
PermissionError: [Errno 13] Permission denied: '/tmp/inaccessible/README'

Platform: Linux komputer 4.12.12-gentoo #1 SMP Sat Oct 14 18:42:35 IST 2017 x86_64 AMD FX(tm)-8350 Eight-Core Processor
Linux: Gentoo Base System 2.4.1
Borg: 1.1.3  Python: CPython 3.5.4
PID: 25508  CWD: /var/tmp
sys.argv: ['/usr/lib/python-exec/python3.5/borg', 'init', '--encryption=keyfile', '/tmp/inaccessible']
SSH_ORIGINAL_COMMAND: None
$ sudo touch inaccessible/foo
$ borg init --encryption=keyfile /tmp/inaccessible
A repository already exists at /tmp/inaccessible.
```

**Comment by DarthGandalf** [comment]
So, accessibility doesn't matter, sorry. At first I got this message when there was something in the directory (I thought it's empty), and it was inaccessible.
It still not "repository" though.

**Comment by ThomasWaldmann** [comment]
that is not a bug. if you tell borg to initialize a repository somewhere, it will reject to do so if there is already something at that place.

Maybe the error message could be clearer by saying "Something already exists at /thatpath.".

**Comment by andreioss** [comment]
Yep, half an hour wasted with such misleading error text.
Please guys, change it to something more meaningful!

**Comment by anowlcalledjosh** [comment]
Currently the checks for creating a repository, from [`check_can_create_repository`], are:

1. if the target directory exists,
    1. is it a directory? if not, raise an error
    2. does it contain anything? if so, raise an error
2. are any of the parent directories Borg repositories? (detected via contents of `README` file)

The error raised says "A repository already exists at &lt;path&gt;", which is correct for check 2, but not for check 1.

Borg needs to handle the cases where:

- the target directory doesn't exist (already done, by creating it)
- the target directory exists, but isn't a directory (done, but the error message is wrong)
- the target directory exists, but already contains files (done, but the error message is wrong)
- a parent directory is a repository (done, raises the correct error)

so it would seem like there need to be two new errors: "&lt;path&gt; is not a directory", and "&lt;path&gt; already contains files".

I'm happy to implement this, with one question: if there are already files in the directory, should Borg check if it is already a repository and report a more accurate error if so, or just say "there are already files there"?

[`check_can_create_repository`]: https://github.com/borgbackup/borg/blob/79b2f2f6537aaa8ab4f8a71f13b0e294cd2b5c38/src/borg/repository.py#L198

**Comment by ThomasWaldmann** [comment]
@anowlcalledjosh good analysis. if it is easy to check for being a repo, it could be done for the target dir also (like in a loop over thatdir, parent(thatdir)).
