### ISSUE TITLE
`borg init --storage-quota` not working properly?

### ISSUE THREAD

**Issue by anowlcalledjosh** [borgbackup/borg#3470]
I ran `borg init --encryption keyfile --storage-quota 300G --progress --show-version --show-rc /repo`, but the `/repo/config` file has `storage_quota = 0`. Is this expected? If not, what format should the number in the config file be in? (looks like bytes from reading the source, but I'd like to check)

**Comment by ThomasWaldmann** [comment]
borg version?

**Comment by anowlcalledjosh** [comment]
1.1.3, installed from PyPI

**Comment by anowlcalledjosh** [comment]
Also getting `storage_quota = 0` on 1.1.0 and even 1.1.0b6 (first release with quota support).

With some print() debugging, it appears that the quota is not getting passed to `Repository` – I don't really understand how the flow of the program works, but it looks like the `with_repository` decorator in `archiver.py` doesn't pass any quota when it creates a `Repository`. Could that be (part of) the issue?

I believe this fixes it: add `storage_quota=args.storage_quota` to the call to `Repository()` at around line 133 in `archiver.py` (but I don't know if the remote repository handling needs anything like that). Happy to make a PR if this is the right fix.

**Comment by ThomasWaldmann** [comment]
@anowlcalledjosh yes, your analysis seems correct. I already started working on it before reading your latest comment, but I'ld appreciate if you review my PR (soon).

**Comment by ThomasWaldmann** [comment]
@anowlcalledjosh see PR #3475
