### ISSUE TITLE
keep-daily deleting last archive

### ISSUE THREAD

**Issue by andreioss** [borgbackup/borg#3487]
Hello,
I'm doing two backups of two directories:
```bash
# borg create /backups::customer_$(date +%d%m%Y) /var/www/html/
# borg create /backups::customer_uploads_$(date +%d%m%Y) /data/uploads/
# borg list /backups/
customer_uploads_21122017    Thu, 2017-12-21 18:59:03 [595c34d2b6116e7148d61f9456049f6d347bc6d19030af49c294afed144af7c7]
customer_22122017            Fri, 2017-12-22 06:26:12 [7945068f991bef87e8e6eab5354cad16e47c517c1551526f1877813b129f0ec5]
customer_25122017            Mon, 2017-12-25 07:57:06 [9014cc3bcab43974567167b8ef8189a76ab694856104836d60d25c3c518ce705]
customer_uploads_25122017    Mon, 2017-12-25 07:57:31 [fdb8466a748678aec2c637299385b4fbbbeda12af1430592606986063b8e1223]
```

Then I'm doing such prune:

```bash
# borg prune --stats --list --keep-daily=14 /backups/
Keeping archive: customer_uploads_25122017    Mon, 2017-12-25 07:57:31 [fdb8466a748678aec2c637299385b4fbbbeda12af1430592606986063b8e1223]
Pruning archive: customer_25122017            Mon, 2017-12-25 07:57:06 [9014cc3bcab43974567167b8ef8189a76ab694856104836d60d25c3c518ce705] (1/1)
Keeping archive: customer_22122017            Fri, 2017-12-22 06:26:12 [7945068f991bef87e8e6eab5354cad16e47c517c1551526f1877813b129f0ec5]
Keeping archive: customer_uploads_21122017    Thu, 2017-12-21 18:59:03 [595c34d2b6116e7148d61f9456049f6d347bc6d19030af49c294afed144af7c7
]
```

Why it's deleting last archive?!
And I should note - it deletes randomly, once customer_uploads_25122017, the next time - customer_25122017. But every time - exactly one of last archives (today).

**Comment by ThomasWaldmann** [comment]
Did you read `borg delete --help` or the online docs about borg delete?

**Comment by andreioss** [comment]
Thomas, of course, and how it could help me in my situation? Sorry, it seems I'm missing something. But why prune, that should delete archives older 14 days only, deleting todays backup, and every time another.

**Comment by sainaen** [comment]
> should delete archives older 14 days only

Yeah, it took me some time to adjust to this system, but `--keep-daily 14` doesn't work the way you think. In short, it keeps a single most recent backup on each day for the last 14 days (so they are _daily_ backups).
It sounds like what you want is `--keep-within 14d`.

Here's a quote, from `borg prune --help`:

> As an example, --keep-daily 7 means to keep the latest backup on each day, up to 7 most recent days with backups (days without backups do not count). The rules are applied from secondly to yearly, and backups selected by previous rules do not count towards those of later rules. The time that each backup starts is used for pruning purposes.

Also, I found [examples](https://borgbackup.readthedocs.io/en/stable/usage/prune.html#examples) really helpful, maybe check them out.

**Comment by ThomasWaldmann** [comment]
yup, what @sainaen says.

additionally, have a look at --prefix, in case you want to apply prune rules not to all archives, but only to one (or each) set of archives.

**Comment by andreioss** [comment]
Ohhh, now I understand...
Ivan, thanks a lot, usually I read docs carefully, but it seems not for this time :(
Thanks guys.
`--keep-within` works like a charm!
