### ISSUE TITLE
I/O Error on large backups

### ISSUE THREAD

**Issue by aruhri** [borgbackup/borg#3488]
When backing up I always receive an error, showing troubles with a hints-file. I back up to a NAS-Repo mounted via sshfs.
The error-message is attached.

[error.txt](https://github.com/borgbackup/borg/files/1586012/error.txt)

As a consequence I get the same error on extracting and pruning.

Part of the backup are two kvm server-images of 15GB respective 120GB.
Backing up without these there are no errors.

**Comment by ThomasWaldmann** [comment]
Reminded me a bit of #3265, but in any case: I/O errors from the filesystem are not borg problems, but a malfunction of the filesystem (bug, defective media, breakdown of network connection, ...).

**Comment by aruhri** [comment]
Yes, thats what I found out. For some reason, the sshfs connection broke always nearly at the same time, messing up the locking of borg.
I made the connection with nfs and it works now fine!
