### ISSUE TITLE
How to backup a VPS

### ISSUE THREAD

**Issue by knzudgt** [borgbackup/borg#3489]
My hosting provider does not offer backups solutions for my VPS, while its storage plans are not cheap. So I wonder: is it possible to use borg to backup an entire VPS and store its backups on a local or remote storage (a hard drive connected to my computer or in the cloud)? 
If possible, I would appreciate if you could provide me documentation or examples.

**Comment by infectormp** [comment]
Did you already read docs? https://borgbackup.readthedocs.io

**Comment by knzudgt** [comment]
Thanks, yes, I did.
I found documentation and examples on how to [backup in local](https://borgbackup.readthedocs.io/en/stable/quickstart.html#a-step-by-step-example), and how to perform [remote operations](https://borgbackup.readthedocs.io/en/stable/quickstart.html#remote-repositories) via ssh. However, since VPS have usually little storage space, I would like to save backups elsewhere, possibly in local (my pc), to avoid disk space issues.

**Comment by knzudgt** [comment]
I beg your forgiveness, I am new to `borg` and not an experienced administrator.
This is what I understand: 
1. Install `borg` on my VPS
2. get the public IP address (say `ipaddress`) of my local computer.
3. Run from remote the following command to initialize a repository on my hd drive:
`$ borg init knzudgt@ipaddress:/media/knzudgt/backups`
4. Run from remote the following command to backup the root directory:
`$ borg create knzudgt@ipaddress:/media/knzudgt/backups::Monday /`

Might this be correct?

**Comment by milkey-mouse** [comment]
If your local machine you want to backup to is behind a NAT or otherwise not directly exposed to the Internet (it probably isn't), you can use "pull mode." Issue #900 contains several techniques, but the easiest one is probably to have a cron job on your local computer (the one to back up *to*) that mounts the VPS filesystem using sshfs and backs that up with borg "locally."
