### ISSUE TITLE
Compile Warning: local variable 'olen' referenced before assignment

### ISSUE THREAD

**Issue by bpereto** [borgbackup/borg#3490]
At build-time from master (f83e5b7f80e631f69667195cbff50db284d7cf67)

$ gcc -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -g -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic build/temp.linux-x86_64-3.6/src/borg/platform/linux.o -L/usr/lib64 -lacl -lpython3.6m -o build/lib.linux-x86_64-3.6/borg/platform/linux.cpython-36m-x86_64-linux-gnu.so

warning: src/borg/crypto/low_level.pyx:742:22: local variable 'olen' referenced before assignment
warning: src/borg/crypto/low_level.pyx:745:22: local variable 'olen' referenced before assignment
warning: src/borg/crypto/low_level.pyx:767:22: local variable 'olen' referenced before assignment
warning: src/borg/crypto/low_level.pyx:773:22: local variable 'olen' referenced before assignment

**Comment by ThomasWaldmann** [comment]
False positive.

https://github.com/borgbackup/borg/blob/f83e5b7f80e631f69667195cbff50db284d7cf67/src/borg/crypto/low_level.pyx#L742

The problem is that in 740 (and 743, 765, 768) a pointer to olen is passed to a C function and set by it.
But that is not known to the compiler.

Is there a way to get rid of that? Just init olen to 0 at the beginning?

**Comment by ThomasWaldmann** [comment]
Note: master-only problem, in 1.1-maint issue is avoided by "outl = 0".
