### ISSUE TITLE
Question: LTS version of Borg?

### ISSUE THREAD

**Issue by aravindhsampath** [borgbackup/borg#3491]
I have been using Borg for my personal use, and am thinking about using it for backing up some research data at work. However, as a backup program - the ability to restore from OLD backups after several years is crucial. Another sysadmin at work scoffed at the idea of using a backup program that doesn't store the files as they are because of the scare of being unable to read archives later. 

What if Borg continues to develop and at some point(a couple of years or more) it can't read the backups we make today?

What would be a good answer to this question? 

- Are there plans for a LTS kind of release that will be assured of reading all archives before? 
or 
- Should I make a Golden Master binary of Borg from the latest release and just never look back at this project again? 

The project's README says the following: 

>  THIS IS SOFTWARE IN DEVELOPMENT, DECIDE YOURSELF WHETHER IT FITS YOUR NEEDS.

Am I taking this project too seriously than it was intended for?

Really appreciate all the work that goes into this project! Thanks!

**Comment by ThomasWaldmann** [comment]
Well, usually you continue using a repo for quite a while, so the borg you use will obviously be able to work with that repo. If we ever do a version step indicating major incompatible changes (like 1.x -> 2.0), there likely will be a migration procedure in case you want to convert a repo. Alternatively, you could just archive borg source, binaries, packages with your data. The binaries bundle everything needed, except (g)libc.

**Comment by mlbarrow** [comment]
@aravindhsampath It is a common practice for a backup application to store data in a non-native format. Typically, as is the case with `borg`, this is done to achieve some significant benefit. For example, decrease long-term storage costs, or provide copy data management.

If you have a business requirement to maintain data for archival purposes, I would recommend putting together a specific archival process at your organization which would entail extracting the relevant data sets from `borg` and purposefully storing those files in a native format along with any supporting metadata in order for someone to be able to properly reference the data at a future point.

**Comment by enkore** [comment]
Like @mlbarrow says, choosing the (initial) data storage method is just a small part of data archival. I'd say long term survival (even in the short period you quoted) mostly depends on organizational measures and less on technical measures.

> If you have a business requirement to maintain data for archival purposes, I would recommend putting together a specific archival process at your organization which would entail extracting the relevant data sets from borg and purposefully storing those files in a native format along with any supporting metadata in order for someone to be able to properly reference the data at a future point.

**Comment by aravindhsampath** [comment]
@ThomasWaldmann @mlbarrow @enkore  Thanks for the responses. 
I understand that I can continue to use borg 1.x and expect it to be able to read archives made with borg 1.x-n. I'm going to put together a long term backup strategy for our org which would involve borg 1.x to make the initial incremental backups with good dedupe and compression benefits. Every x years(or if a borg major version gets released), we'd do a full backup as kind of a checkpoint to cover ourselves. And of course we keep a local golden copy of borg binaries just in case.
