### ISSUE TITLE
Add status flag into archive

### ISSUE THREAD

**Issue by henfri** [borgbackup/borg#3493]
Hello,

I summarize a discussion from IRC a few minutes ago:
-Currently, it is not possible to find out if an Archive is complete, if the logs and/or return code has not been recorded on the machine pushing the backup ('client')
-So, in a situation where a restore is needed, this information may be missing -but it is crucial
-Consequently, a flag in the Archive 'completed' would be very useful.
-As the reason for a failure could be an interrupted network connection, we cannot ensure that we can write the status into the archive. Thus, the flag should be set to 'false' on Archive creation and to true if the job was completed successfully.

In addition, it would be useful to have a full log (same verbosity as the run of borg) as part of the archive. Again, this cannot be ensured, if the network connection dies.

Two option exist:
A) incomplete log -better than no log in my view (esp. in Desaster situation)
B) store the log on the client until the next borg job and add it to the archive then

B) is certainly very 'new' as today, a borg run does not touch a past archive.

Greetings,
Hendrik

**Comment by d7415** [comment]
As I understand it, the "interrupted network connection" case is already handled by borg - If a `borg create` doesn't finish then it won't appear in `borg list`, except possibly as a checkpoint.

I don't know about other scenarios.

**Comment by ThomasWaldmann** [comment]
There is the rc code of the borg create command and it can be logged with --show-rc.
But yes, if you do not keep the log / handle rc code, that doesn't help.

You could just add a "flag file" as just file to borg commandline:

```
touch /tmp/finished_flag
borg create repo::arch /home /tmp/finished_flag
```

**Comment by ThomasWaldmann** [comment]
@d7415 ah, right, so one even can just look at the created archive name.

**Comment by ThomasWaldmann** [comment]
closing this one, seems there is no action needed.

**Comment by henfri** [comment]
Sorry, I am not happy with the current status.
I do not know how to check if a backup shown by borg list is complete. 
Are you saying that any backup that does not contain '.checkpoint' is complete? I think I can show that this is not the case. I will re-check though.

I do not consider the option to log the return code sufficient. In a situation in which I need my backup, I may have lost this log. Also it seems to me something that should be in the core and not in everyones scripts around borg.

The suggestion to add a flag-file is an option, but again: I think this is a workaround. Why don't you think that this information should be part of the backup?

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
IIRC, any completed run of borg (like reaching the end of the recursion) will result in a non-checkpoint archive. And a not completed run will either result in no archive or a checkpoint archive.
