### ISSUE TITLE
Improve Readme.txt on Release Page

### ISSUE THREAD

**Issue by intdel** [borgbackup/borg#3497]
Hello,

A small step is missing in the Readme.txt on the Releases page. I am not sure if you have that checked in somewhere in git. If yes, I can correct it and make a pull request.

Anyways:
This step needs to be done before verifying:
'gpg --keyserver keys.gnupg.net --recv-keys .....'

Otherwise following error will appear:
gpg: Signature made Mon 27 Nov 2017 05:42:25 AM STD using RSA key ID ......
gpg: Can't check signature: public key not found

I guess for people familiar with gpg this step is obvious, but for some people it might not be. A lot of people will probably skip verification if it doesn't work. I guess adding this step should not be trivial.

Thanks

**Comment by ThomasWaldmann** [comment]
The correct key fingerprint is in the docs, security contact section.

**Comment by ThomasWaldmann** [comment]
Note: I added the missing line to 1.1.4 README.txt (not released yet).
