### ISSUE TITLE
aes ctr: random xor counter

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3499]
now:
```
ctr = last_ctr() + 1  # plus some ctr reservation code making sure it never overlaps
loop:
    ctr++
```
new?:
```
r = good_random_bits()
i = 0
loop:
    ctr = r xor i++
```

**Comment by enkore** [comment]
The 64 bit counter you get from the format is simply insufficient to do this securely; for multiple clients and an adversarial server the encryption in Borg as-is is simply and obviously broken with no compatible way of fixing it.

**Comment by ThomasWaldmann** [comment]
Right, forgot that we only store 64bits for the counter.
