### ISSUE TITLE
Backup freezes if Excel file is open

### ISSUE THREAD

**Issue by Cronktz** [borgbackup/borg#3511]
I try to backup a large working folder. I use a script which mounts the "to be backuped" file system and starts the _borg create_ command.
Whenever a MSOffice-file which I want to backup is open the backup procedure freezes and does not proceed.
I only encounter it with files from MS Office products (tested Excel and Word). 
If I try it with an open .txt-file the _borg create_ command finishes without any problems.
I already tried `--exclude '*~$*'` to prevent the backup of the temporary Office files but it gets also stuck at the main file which is open.
Copying the file with cp is working.

Version: borg 1.1.4

**Comment by ThomasWaldmann** [comment]
Need more info about the environment. Which OS is this? Filesystem where the office files reside on? Local / Network? Which borg package / executable?

Open files troubles -> sounds a bit like windows.

**Comment by Cronktz** [comment]
System on which Borg is running:
- System: Raspberry Pi 3 
- OS: Raspbian jessie
- Borg Version: 1.1.4
- Borg installed using pip and virtualenv

System with office files:
- OS: Ubuntu 12.04 LTS
- Filesystem: ext4

To backup I mount the folders through _cifs_ and issue the borg create command:
_borg create --stats --progress /path_to_repo::repo /backup_folder_

As soon as it reaches the opened file the progress option is showing that the _original_ data and the _compressed_ data is continuing to count up while the _deduplicated_ data stays at the same value.

First: 150.99 MB O 597.69 kB C 38.22 kB D 0 N data/openexcelfile.xlsx
Later: 335.54 MB O 1.32 MB C 38.22 kB 0 N data/openexcelfile.xlsx

In order to get a successful backup I need to close the file and restart the backup.

**Comment by ThomasWaldmann** [comment]
I'm quite sure the root cause for this strange behaviour is within the samba server / its configuration (or cifs), so maybe check if it does something special with that kind of files.

That said, it would be interesting to check what is actually happening if borg gets stuck there, but the stats are continuing to go up, that seems strange, too.

About your configuration:

You could run borg (client) on the Ubuntu machine and push the backups to your raspi (borg serve) by using a ssh://... repo url. Likely this would be way faster and also spread the memory allocation to both machines (with the bigger part on the ubuntu machine).

Maybe it would even solve the issue with the excel files, not sure.

**Comment by ThomasWaldmann** [comment]
Did you find out something?

**Comment by Cronktz** [comment]
Sorry for the late response but I configured the backup at my parents and had no access until today. 

No I did not find a solution for the issue. 

However as the backup process "stops" at the open file and killing the process does not seem to make any harm I call the `borg create` command with `timeout` in front of it.
As I run the backup once a day I can make sure that no `borg create` is running while I try to start the next days backup.
I hope that this avoids the former problem of locked repositories.
Also for me it seems better to make sure no forgotten borg process is running than breaking the lock on the startup of my backup procedure.
I know that I will possibly lose some backups, but like that my script should run more stable.
At this moment I prefer potentially losing some backups over no backup at all until I have time to look at the repository.
So far this configuration seems to work.

**Comment by ThomasWaldmann** [comment]
you should configure your samba (smbclient) in a way that it does not block/hang on files.

**Comment by ThomasWaldmann** [comment]
Any news on the samba/cifs "file locked and blocking" part?

**Comment by ThomasWaldmann** [comment]
No response, closing.
