### ISSUE TITLE
borg as encfs (and/or lessfs) alternative

### ISSUE THREAD

**Issue by panzerballett** [borgbackup/borg#3519]
this is not what `borg` is meant for, i know. but it seems `borg` could be very close to providing the same functionality as

- [encfs](http://www.arg0.net/encfs)
- [lessfs](https://sourceforge.net/projects/lessfs/) (which is discontinued)

 (or even both of them combined).

`borg` could be used to mount (using fuse) a data directory where the deduplicated (and encrypted) data is. `borg mount` does that (read-only) for the backups already. it would be very nice to have a read-write version of that - not to be used on a backup but to have an encrypted/deduplicated version of a directory tree on the physical disk (just as `encfs` and `lessfs` do).

are there any plans for something like that?

**Comment by ThomasWaldmann** [comment]
No plans.
