### ISSUE TITLE
Borg script isnt working

### ISSUE THREAD

**Issue by domacikolaci** [borgbackup/borg#3523]
Hi!

Trying to use the borg script on your wiki, and keep getting this message

> Repository ::{hostname}-{now} does not exist.

Please find below my code in borgbackup.sh
https://pastebin.com/8cvDR2MA 

Thanks!

**Comment by ThomasWaldmann** [comment]
Please try the script with a local repo first (just a path).

**Comment by domacikolaci** [comment]
Yep, mounted it and it worked, strange.... First backup run going to go all night since its over 2.4TB worth of data yay. Will report back if any problems!
