### ISSUE TITLE
stdin and filename

### ISSUE THREAD

**Issue by michalkolar** [borgbackup/borg#3533]
Hi,

i have problem with specific filename in stdin backup.

example:

mysqldump ... | borg create -v --stats ssh://backup_host:/....::{now:%Y-%m-%d} -

i expected param --stdin-filename (for example in rectis mysqldump | restic backup --stdin --stdin-filename production.sql)

Can i change filename from stdin to custom name?

Thanks,
Kolar

**Comment by ThomasWaldmann** [comment]
There is no such option yet, the name 'stdin' is currently hardcoded.

As there is usually only one such file in such an archive and you can name the archive as you like, isn't that sufficient?

**Comment by michalkolar** [comment]
Many people have the problem of rename the ending to, for example, .sql ... because windows 10 hiding extension of files...

**Comment by ThomasWaldmann** [comment]
Not sure I understand the problem.

**Comment by michalkolar** [comment]
Most people are stupid if they find a set of stdin in the archive, so they will not know what to do. For example, webhost customers. It would be great to change the stdin file name.

**Comment by michalkolar** [comment]
Hi ThomasWaldmann,

any news? Can i help you?


Thanks,
Kolar Michal

**Comment by ThomasWaldmann** [comment]
@michalkolar if you like, implement the feature and do a PR.
