### ISSUE TITLE
Return value for "completed with errors"

### ISSUE THREAD

**Issue by tuxick** [borgbackup/borg#3534]
Trying to do more checking/monitoring i found that borg create would return not 0 if it completed but for example skipped some files. Maybe it could return a special value for this, or maybe even the (first?) errno encountered? Might save the hassle of parsing the output.

**Comment by ThomasWaldmann** [comment]
iirc we have documentation about the currently used return codes and what they mean.

there also already was some discussion about using somehow more different return codes, please search on the issue tracker. back then, there was no clear conclusion about how that should work or whether it would be a good idea anyway, so the simple scheme you see now was implemented/kept.

so, as long as there is no very detailled and specific idea how this can be improved (including use cases) and wide agreement that this should be done (might cause compatibility issues, scripts might need changed), this is unlikely to be changed.
