### ISSUE TITLE
Corrupted cache '.cache/####/files' unable to recreate.

### ISSUE THREAD

**Issue by nealpalmer** [borgbackup/borg#3537]
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /home/pi/.cache/53f95bf25bdb1d96526e6de3ac66acb9b1e01a3d3bf30b184a4dab2f1057135b/files

I have tried removing the file to see if borg will automatically re-create it, but no such luck.  How do I replace the file so that my backups have a working files cache?

Borg 1.1.3

**Comment by ThomasWaldmann** [comment]
unrelated, but still important: you should be using 1.1.4, read its changelog.

the files cache will be recreated at next `borg create` run.

please reopen with more details if there are any issues with that.

**Comment by nealpalmer** [comment]
Problem happened again.  I upgraded to 1.1.4, and it doesn't automatically re-create the "files" cache when I run "create".

How do I force Borg to recreate the files cache?

> File failed integrity check: /home/pi/.cache/53f95bf25bdb1d96526e6de3ac66acb9b1e01a3d3bf30b184a4dab2f1057135b/files
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 545, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 508, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 619, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 596, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode, self.files_cache_mode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 988, in process_file
    ids = cache.file_known_and_unchanged(path_hash, st, ignore_inode, files_cache_mode)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 917, in file_known_and_unchanged
    self._read_files()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 523, in _read_files
    return
  File "/usr/lib/python3/dist-packages/borg/crypto/file_integrity.py", line 193, in __exit__
    self.hash_part('final', is_final=True)
  File "/usr/lib/python3/dist-packages/borg/crypto/file_integrity.py", line 188, in hash_part
    raise FileIntegrityError(self.path)
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /home/pi/.cache/53f95bf25bdb1d96526e6de3ac66acb9b1e01a3d3bf30b184a4dab2f1057135b/files

**Comment by ThomasWaldmann** [comment]
maybe manually remove the corrupt file and try again.

if this happens repeatedly (and rather frequently) on this machine, you should check the hardware.

if the integrity check fails for that file, it means that the contents that were written to disk (and checksummed) were different from what was read from disk now (and checkum-checked).

on good working hardware, this should be an extremely rare (like ~ never happens) event.
if you see it more frequently, there might be a problem in your hardware.

**Comment by nealpalmer** [comment]
I'm still fiddling with things, and making them run the way that I want.  Which includes incremental backups hourly.  And includes running stuff that I cancel (ctrl-c) in the middle of a create.

The problems have shown up IMMEDIATELY after hitting ctrl-c.  So it isn't unreliable hardware, it is unreliable human intervention.

I don't care that the cache file got corrupted, I'm certainly to blame for it (not flaky hardware)...

I have already tried:
1) letting borg do it's standard stuff -> borg crashes (fail)
2) removing the "files" file -> borg won't re-create it (fail)
3) truncating the "files" file -> borg won't re-create it (fail)
4) deleting the entire ".cache/####" directory, and starting a create, then cancelling it, then copying over the old chunks.archive.d directory, and starting another create.  YEAH, it finally built a new cache!

So to repeat my question:  How am I supposed to have borg regenerate the cache?  I'd love it if one of the first 3 options above would work - i.e. a simple automate-able one.
