### ISSUE TITLE
Borg repository does not exist?

### ISSUE THREAD

**Issue by carlbeech** [borgbackup/borg#3539]
Hi Apologies if I'm doing something wrong here, but I came to do a backup today and I got an error message that my repository does not exist...

carl@carl-ebook:~$ borg list $REPOSITORY
Repository /home/carl/carl@plex:/SPARE/BACKUPS/CARL_PC2 does not exist.

carl@carl-ebook:~$ echo $REPOSITORY
carl@plex://SPARE/BACKUPS/CARL_PC2

I keep my backup command in a shell script, and this has been working fine for months - 

I've manually checked that the address works ok, and that auto-login works fine, also that the directory is correct..:

carl@carl-ebook:~$ ssh carl@plex
Welcome to Linux Mint 18.3 Sylvia (GNU/Linux 4.10.0-42-generic x86_64)
...
carl@PLEX2 ~ $ ls -l /SPARE/BACKUPS/CARL_PC2
total 2584
-rw------- 1 carl carl     635 Aug 14 18:42 config
drwx------ 1 carl carl       2 Aug 14 18:42 data
-rw------- 1 carl carl   11501 Dec  4 22:29 hints.3481
-rw------- 1 carl carl 2621498 Dec  4 22:29 index.3481
-rw------- 1 carl carl      26 Aug 14 18:42 README

I noticed that the error message says: "/home/carl/carl@plex..."  - and was wondering if this was incorrect - shouldn't it say 'carl@plex...' - if its got the address incorrect and thinks its '/home/carl/carl@plex...' then this may explain why it doesn't find the repository...

Hope that all makes sense..

Cheers

Carl.

**Comment by ThomasWaldmann** [comment]
```
carl@carl-ebook:~$ echo $REPOSITORY
carl@plex://SPARE/BACKUPS/CARL_PC2
```
What exactly is //SPARE? Or is it /SPARE?

```
carl@carl-ebook:~$ ssh carl@plex
carl@PLEX2 ~ $ ls -l /SPARE/BACKUPS/CARL_PC2
```

**Comment by carlbeech** [comment]
Hi
Weird - I changed the //SPARE to /SPARE in my batch script and its now working...   thing is that I've had //SPARE for the last six months...

Anyway, main thing is that it's working again - much appreciated!

Cheers

Carl.
