### ISSUE TITLE
borg shows 'Failed to write all bytes for _bisect.so' when there is no free space in /tmp

### ISSUE THREAD

**Issue by lwiechec** [borgbackup/borg#3540]
I have noticed that when tried to contact borg process on the server side (running as `borg serve...`). Note that there was plenty of place on other mounts.

I couldn't find in the documentation to override temporary directory setting. I would propose that the error message were a bit more readable...

**Comment by ThomasWaldmann** [comment]
You need to provide enough free space in TEMP (TMPDIR) when using the standalone binary made with pyinstaller. One of the first things pyinstaller does is to extract the binary into TEMP and then run from there.

If there is not enough space, no permission (esp. to run stuff there), it will fail.

This is before borg code runs, so an issue about this (if any) should be filed against pyinstaller.

**Comment by lwiechec** [comment]
ha, ok - thanks for explanation; I have very little idea how pyinstaller works :)
