### ISSUE TITLE
FutureWarning use_bin_type

### ISSUE THREAD

**Issue by quite** [borgbackup/borg#3541]
Getting a new warning from borg 1.1.4-1 as packaged by Arch Linux. Is this dist specific,
and ought to be resolved in Arch? Otherwise, I'd be happy to see this go away.
I don't want to filter this type of output, as this is my backup software running in cron...

```
/usr/lib/python3.6/site-packages/msgpack/__init__.py:47: FutureWarning:
use_bin_type option is not specified. Default value of the option will be
changed in future version.
/usr/lib/python3.6/site-packages/borg/archive.py:225: FutureWarning:
use_bin_type option is not specified. Default value of the option will be
changed in future version.
/usr/lib/python3.6/site-packages/msgpack/__init__.py:37: FutureWarning:
use_bin_type option is not specified. Default value of the option will be
changed in future version.
/usr/lib/python3.6/site-packages/msgpack/__init__.py:47: FutureWarning:
use_bin_type option is not specified. Default value of the option will be
changed in future version.
```

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/3517

**Comment by quite** [comment]
Sry

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/5e007ea7a6f2bbc1da03aac13f16053c2697283e

arch could adjust the requirements and packages that way. ^
will be like this in next borg release anyway.
