### ISSUE TITLE
Chunk ID missing when purging

### ISSUE THREAD

**Issue by magma1447** [borgbackup/borg#3542]
I have a repository I can't purge anymore, due to a missing chunk. It just happened. The backup runs hourly, there has been no power failure or similar since last backup.

Borg is version 1.1.3 on both hosts. I know 1.1.4 is the latest, if you believe it helps, please tell me and I will upgrade.

>root@pgc-nosql-01:~# /usr/local/bin/borg-backup.sh 
>Initial setup
>System check
>Deciding Borg-repo
>  borg@thor:/mnt/md2/borg-WedFriSun/pgc-nosql-01.borg
>Creating Borg-backup
>Purging old Borg-backups
>Chunk ID db5d73939007f1f886ac276acffb9fcf21c84a4b3b26951d26a501f719ad3bdd missing from chunks index, corrupted chunks index - aborting transaction.
>Borgbackup purge failed

The command that fails is:
>${BORGBIN} prune --lock-wait ${BORG_LOCKWAIT} --keep-within 5d ${BORG_ARCHIVE}

BORGBIN is obviously just the path to the binary, BORG_LOCKWAIT is just a number, BORG_ARCHIVE is what's echoed with a prefix of two spaces.

A check on the repository says nothing is wrong:
>borg@thor:/mnt/md2/borg-WedFriSun$ borgbackup check pgc-nosql-01.borg
>Enter passphrase for key /mnt/md2/borg-WedFriSun/pgc-nosql-01.borg: 
>borg@thor:/mnt/md2/borg-WedFriSun$ echo $?
>0

**Comment by ThomasWaldmann** [comment]
Yes, please upgrade to 1.1.4 and DO NOT run `check --repair` with any 1.1.x older than 1.1.4

**Comment by magma1447** [comment]
I get the exact same result with 1.1.4 though. I can't tell if I have been running a --repair on it with 1.1.3 before.

I would expect a check to find the issue if there is one. And I wouldn't expect purge to find an issue if there isn't one.

Are you interested in the issue or should I just delete the repository and start over? It's not an issue for me dropping the data since I have two more repositories, and no known issues with the live data.

**Comment by ThomasWaldmann** [comment]
Well, borg check primarily cares about checking the repo and the archives, so I am not sure yet it would find such an issue in the cache. IIRC, borg check --repair would rebuild the chunks cache anyway.

What would be interesting is to find out how that chunk got lost (only from the index? also from the repo?).

**Comment by ThomasWaldmann** [comment]
Does that fetch work for your repo?
```
borg debug get-obj repo db5d73939007f1f886ac276acffb9fcf21c84a4b3b26951d26a501f719ad3bdd obj.bin
```

**Comment by magma1447** [comment]
Seems to exist.

>borg@thor:/mnt/md2/borg-WedFriSun$ borgbackup debug get-obj pgc-nosql-01.borg db5d73939007f1f886ac276acffb9fcf21c84a4b3b26951d26a501f719ad3bdd obj.bin
>object db5d73939007f1f886ac276acffb9fcf21c84a4b3b26951d26a501f719ad3bdd fetched.
>borg@thor:/mnt/md2/borg-WedFriSun$ file obj.bin 
>obj.bin: data
>borg@thor:/mnt/md2/borg-WedFriSun$ ls -l obj.bin 
>-rw------- 1 borg nogroup 598104 Jan 12 14:32 obj.bin

**Comment by ThomasWaldmann** [comment]
Can you run some stuff with modified 1.1.4 code?

**Comment by magma1447** [comment]
Not a problem if I get a binary. :)

**Comment by magma1447** [comment]
I will be AFK for a few hours now though.

**Comment by ThomasWaldmann** [comment]
Hmm, this somehow went off my radar.

@magma1447 guess you solved it meanwhile? anything to add here? close?

**Comment by magma1447** [comment]
I honestly don't really remember. Maybe we found a solution after communicating on IRC. Let's close it.
