### ISSUE TITLE
stat() errors in scandir_generic() cause the whole directory to be skipped

### ISSUE THREAD

**Issue by leo-b** [borgbackup/borg#3545]
When backing up a directory, ``scandir_inorder()`` is used to read the directory entries ordered by inode number:
https://github.com/borgbackup/borg/blob/1.1.4/src/borg/archiver.py#L613-L614
https://github.com/borgbackup/borg/blob/1.1.4/src/borg/helpers.py#L2104-L2105

 If the ``scandir_generic()`` implementation is used (python3.4 without the scandir package installed), the implicit `stat()` that is done on ``dirent.inode()`` will raise `Permission denied` e.g. on fuse mountpoints without `allow_other`. As a result, the whole directory will be skipped just because of one failing stat.
https://github.com/borgbackup/borg/blob/1.1.4/src/borg/helpers.py#L2046-L2090

1.) A failing ``stat()`` should only skip the corresponding directory entry.
2.) If the ``stat()`` fails on a directory entry that is going to be skipped anyway, the error message should be suppressed.

**Comment by ThomasWaldmann** [comment]
Good analysis. Would you like to do a PR to fix that issue?

**Comment by ThomasWaldmann** [comment]
@leo-b sounds good, just do a PR.

**Comment by ThomasWaldmann** [comment]
fixed by #3558.
