### ISSUE TITLE
Worst-case scenario entry-point plan

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#3547]
This is not entirely related to borg, but more to the backup system behind it. I hope it's okay to discuss this as I'd love you insights. If not, let me know and I'll close this right away.

I already have all my important files backup'ed with borg locally and to the cloud. That gives me peace of mind because: 1) I know my files are secure even in the cloud, 2) There's history of changes for each backup I make (via cron) 3) Borg makes sure integrity of files are good, 4) I know I'm using the least space possible because borg dedups and compresses out-of-the-box. I'm happy. Well, not quite...

Since my backup system is all encrypted and stored in the cloud and an external HD, there must be an entry point. In the worst-case scenario (where I don't have access to my phone's google authenticator nor to my external HD), the entry point is S3. For S3, I need my credentials and a OTP code from google authenticator. Now, I've found a way to generate OTPs code for google authenticator using a CLI tool called `oathtool` + the totp code (check here for the reference I used: https://gist.github.com/NapoleonWils0n/4005467).

My S3 credentials are in Lastpass, which also uses gooole authenticator 2FA.

What that means is, if I want to recover from scratch and I don't have access to my external HD nor my phone's google auth, I need to login to Lastpass and have access to both the S3 and Lastpass' OTP. Lastpass is the only service where I use a password that's not generated.

I was thinking to just store the totp code for S3 in Lastpass, and then encrypt the totp code for Laspass using a gnupg encrypted file or a borg repo, and then burn it to a DVD (but then this would be my single point of failure, if I lose this DVD and my phone, it's all gone). Backup'ing this to the cloud would be hard as I don't have a single cloud service without 2FA, and then we'd fall in the same chicken-and-egg situation on how to backup the totp code for that service. Maybe I should print this code somewhere? 

What do you think? What strategy to do you use for your "entry-point"?

**Comment by dfloyd888** [comment]
If you need an entry point, you could keep some type of tarfile with a Borg archive accessible by a URL, and have it encrypted using a keyfile.  Then, keep a paper copy of the QR code in several physically safe, yet secure locations, be it a safe deposit box, buried in a PVC pipe in the backyard, or wherever you think is best.  This way, an attacker that fetches the tarfile without knowing the keyfile can't really brute force it, and has to deal with the entire 256 bit keyspace.

As an aside, I'd recommend a utility that can export the Google Authenticator seeds in plain text, so you can print them, or at the minimum, copy them to another program.

**Comment by fullofcaffeine** [comment]
@dfloyd888 So a borg repo using asymmetric key and then store the private key in a physical media? That makes sense. Maybe printing QR codes would make it easier to retrieve the data?

**Comment by dfloyd888** [comment]
For my critical repos, I export the qr-html file, then print the QR code, and store that in my media safe.  That way, if something does happen, I can recover the keyfiles, pull the Borg repo from offsite storage, and be back in business.

**Comment by fullofcaffeine** [comment]
Thanks!
