### ISSUE TITLE
Placeholders {now} and {utcnow} are replaced with timestamps microseconds apart

### ISSUE THREAD

**Issue by BlessJah** [borgbackup/borg#3548]
Both `{now}` and `{utcnow}` should point to exact same moment, save for timezone adjustment. They are not, because current time is queried twice when replacing placeholders:

Borg version: 1.0.11, but master is also affected.

https://github.com/borgbackup/borg/blob/26f1cd148603e2c2762c5f27ef56bf5b9ca17d18/src/borg/helpers/parseformat.py#L189

```
$ borg create \
  --info \
  --stats \
  ':: utcnow: {utcnow:%H:%M:%S.%f}, now: {now:%H:%M:%S.%f}' \
  /dev/null
------------------------------------------------------------------------------
Archive name:  utcnow: 21:16:01.582465, now: 22:16:01.582458
Archive fingerprint: ...
Time (start): Mon, 2018-01-15 22:16:03
Time (end):   Mon, 2018-01-15 22:16:03
```

**Comment by ThomasWaldmann** [comment]
You meant "microseconds apart", did you?
