### ISSUE TITLE
Where's the default log file location?

### ISSUE THREAD

**Issue by Saltystew** [borgbackup/borg#3549]
When running a borg auto backup script I get rc 1 for backup and rc 0 for prune, docs say any warnings would be logged and mentions to check the log.  I can't find any log file or any docs giving the location.

So where is the log file?

**Comment by infectormp** [comment]
Logs output to console. If you want write log in file you need use something like
borg >> $LOG_PATH/$LOG_NAME 2>&1

**Comment by ThomasWaldmann** [comment]
Just checked the docs: this is not documented yet.
