### ISSUE TITLE
Document create --stats goes to stderr

### ISSUE THREAD

**Issue by tuxick** [borgbackup/borg#3552]
For some reason borg create --stats writes stats to stderr. Since nobody would expect that, please add a note to documentation.

**Comment by ThomasWaldmann** [comment]
borg writes a lot of stuff to stderr, so why do you say nobody would expect that?

**Comment by tuxick** [comment]
Well, stats is not an error :)

**Comment by ThomasWaldmann** [comment]
stderr is used for all log output, not just for errors.
and as backups are often automated and flexibility with logging is nice (as in "logging" python stdlib module), a lot of output goes over the logging module and thus is emitted on stderr.

afaik the only exception when stuff does not go to stderr might be rather interactive commands / features.

it's not always easy to decide though whether stderr or stdout is more appropriate.

**Comment by ThomasWaldmann** [comment]
another reason why stderr is somehow the preferred way: we use stdin/stdout sometimes to carry backup data, so of course log messages popping up in there is rather not desired.

**Comment by ThomasWaldmann** [comment]
see also #3549.
