### ISSUE TITLE
improve formatting of resource usage section

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3554]
https://borgbackup.readthedocs.io/en/1.1.4/usage/general.html#resource-usage

E.g. the text below "CPU client" appears as just 1 paragraph of floating text, but the intention was to rather have a list for "borg create", "chunks cache sync", etc.

**Comment by Gu1nness** [comment]
Hi,

The issue is the same on the man page.
I will patch both.

**Comment by ThomasWaldmann** [comment]
Fixed by #3589.
