### ISSUE TITLE
Performance consideration on a VM

### ISSUE THREAD

**Issue by jeremyfritzen** [borgbackup/borg#3564]
Hi,

I tested Borg Backup and it's really nice!
I am wondering if the performance I have are normal or not.

**My configuration**
I installed Borg 1.0.9-1 on 2 Debian Stretch VMs ("**_source"_** and "**_destination_**"). The backup is done with ssh (not ssffs).
The VMs are running on ESXi (Xeon E3 1220 v3) with each 1 core and 2 GB RAM.

**My test**
I made several backup archives with 2 files:
- 3 GB video file
- 1.5 MB picture file

The first backup took about 10 mn I guess.
Then, I had a second picture file (1.5 MB) => The backup took ~5 mn.
Then, I made a new backup (no changes) => The backup took ~5 mn.

It seems that the source VM takes a lot of CPU to chunk or hash the files and determine if there is change or not.
After that, the backup is pretty quick through LAN (both VMs are on the same ESXi).

**Is this performance normal, regarding the VM configurations?
What should I change to improve performance?**

Thank you all!

**Comment by ThomasWaldmann** [comment]
A no-change backup to a ssh: repo url should not take 5 mins, something seems to be wrong there.

Check the output of `borg create -v --list ...` whether you always see "A" status.
If so, read the FAQ about unexpected A status.

**Comment by jeremyfritzen** [comment]
OK, that's weird because I wasn't able to reproduce the issue...
