### ISSUE TITLE
Allow restoring latest version of a file

### ISSUE THREAD

**Issue by varac** [borgbackup/borg#3572]
Maybe I oversaw this, but I want to restore a file from my backups and don't know in which ARCHIVE it was stored in it's last version (i.e. I deleted it "some time ago", so it will not be present in the latest ARCHIVES).
How do I do that ? If there's no current way, then this will be a feature request for it.
Maybe a search command would be enough which shows which archive holds a file/glob in which version.

**Comment by EthraZa** [comment]
It got my attention... I'm curios to know if such a command exists/is possible.

But if not and you are in the need right now, I guess you can simple mount all backups and **ls** or **find** it.

If you know the path to the file, you can simple use ls (to find /home/Documents/MyFile123.txt):
```
borg mount repo somedir
ls -l somedir/*/home/Documents/MyFile*.txt
```

**Comment by ThomasWaldmann** [comment]
use the "versions" option of borg mount.

**Comment by varac** [comment]
@ThomasWaldmann Nice, I was not aware of this option! However, this gives me the different versions of a file, but not which repository they are located in.
In practice, this option will mostly solve the problem stated in the issue, however it would still be good to have a way of querying the repository names for each version of a file.

**Comment by ThomasWaldmann** [comment]
@varac if you have an idea how to actually do that, feel free to post a feature request with the details.

until then, you can use the timestamp as a hint maybe.

**Comment by varac** [comment]
ok, current options work for me. I'll see if I create a feature req!

Thx anyway!
