### ISSUE TITLE
Authenticated only mode asks for password

### ISSUE THREAD

**Issue by fancytenseletters** [borgbackup/borg#3576]
I wanted to setup non-encrypted and authenticated repository but invoking:
`borg init --encryption authenticated-blake2` or `borg init --encryption authenticated` asks me for password.

Do I misunderstand authenticated only mode or is there a bug in borg?

Borg version 1.1.4, Archlinux.

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/init.html?highlight=encryption#encryption-modes
`borg init --encryption none` ?

**Comment by infectormp** [comment]
Not encrypted no auth = none
Not encrypted, but authenticated = authenticated

**Comment by fancytenseletters** [comment]
Hm, I used `--encryption none` before and my goal was to switch to  `authenticated-blake2` for better performance as documentation advice. If password is needed for authenticated mode then it isn't directly comparable to none.

**Comment by ThomasWaldmann** [comment]
the password is needed to decrypt the "key".
a borg key contains the AES encryption key, the MAC key and the chunker seed.
any authenticated mode obviously needs the MAC key, even if no encryption is used.

**Comment by fancytenseletters** [comment]
Thx. It seems empty password works just fine.

**Comment by ThomasWaldmann** [comment]
If you combine empty password with repo-side key storage, you need to fully trust the repo location.

**Comment by fancytenseletters** [comment]
I'm using encryption at another level, that's why I don't want to duplicate it.

**Comment by ThomasWaldmann** [comment]
You need to differentiate between authentication and encryption.
If you use "authenticated" mode, there is no encryption.

But still you need to keep the key material secret (MAC key inside), because if an attacker can access the authentication key, he can modify and re-authenticate data in the repository. So, you basically degrade the MAC to a normal hash/checksum.

**Comment by BarbzYHOOL** [comment]
Hey, sorry to ask here but what does "authenticated" mean?? In practice (because saying "authenticated = not encrypted but authenticated" doesn't help me :P)

What is the use case for "authenticated" mode?

**Comment by ThomasWaldmann** [comment]
when writing data, authenticate means to add authentication information (it's similar to a checksum only you [who has the authentication key] can compute).

when reading data, authenticate means to check whether the data correspond to the authentication information (similar to checking whether a checksum is valid).

**Comment by ThomasWaldmann** [comment]
It can detect accidental corruption as well as malicious tampering.

An attacker would be able to recompute an md5sum, but he can not recompute an authentication tag because he does not have the key (we use hmac-sha256 or keyed blake2b).

**Comment by BarbzYHOOL** [comment]
so why encrypting??

**Comment by ThomasWaldmann** [comment]
If you need confidentiality, you want to encrypt your repo.
Encryption is rather fast on modern CPUs, so there is rarely a reason to switch it off.

**Comment by BarbzYHOOL** [comment]
I don't understand the difference between authenticated and encrypted but I'll stop there, thank you

**Comment by wgslr** [comment]
@BarbzYHOOL  Encryption ensures that someone (attacker) having access to the repository can not read what you put in there. Authentication means that the attacker can read the contents of archive, but can not change the repository contents and pretend it's the original information.

**Comment by BarbzYHOOL** [comment]
ok thank you very much @wgslr !!!

**Comment by kosli** [comment]
@ThomasWaldmann Is the `authenticated` mode with an **empty** (!) passphrase still better than just `none`? As I assume even with `none` checksums are being used to verify the integrity of the data?

**Comment by ThomasWaldmann** [comment]
`none` is just using a sha256 (hash).

`authenticated` is using hmac-sha256 or blake2b (MAC). a MAC involves a secret key which is encrypted and stored in the borg key (either in the repo config or in your home directory. the passphrase is used to decrypt the key material).

so an attacker could fake content in a `none` mode repo by recomputing a lot of sha256 values.

an attacker could only fake content in a `authenticated` repo, if they have access to the MAC secret key.
if you use empty passphrase, that is just a question of accessing your repo config or home dir to get the MAC secret key.
if you use a non-empty passphrase, the attacker would also need the passphrase.
