### ISSUE TITLE
borg create --stats goes to stderr

### ISSUE THREAD

**Issue by dluijkx** [borgbackup/borg#3577]
borg 1.1.4
...borg create --stats reports output to stderr when there is no error condition ( instead of stdout )
...borg create --json goes to stdout as expected

**Comment by ThomasWaldmann** [comment]
borg logging is configured to output to stderr (by default).

it is quite usual to use stderr for logging, esp. when the tool is also able to use stdout for data transfer (e.g. borg extract).

@enkore was there a special reason to use stdout for json mode?

**Comment by enkore** [comment]
separating logging and regular output

**Comment by ThomasWaldmann** [comment]
-v please.

**Comment by enkore** [comment]
If --json and --log-json would share the same channel, then the two formats would have to co-exist, which would make them less independent, but that was necessary from both implementation specifics (logging-based "text with some standard metadata" output vs. specific JSON format output) and constraints (couldn't/wouldn't add --json to everything; doesn't make sense for everything either).

There's also that thing with stdout being the more natural place for --stats output in the first place; --json essentially correcting that.

**Comment by jpsknr** [comment]
Hi,
I also consider that is not a best practise get in stderr the result if there is no error in execution...
Anyway, I want to configure a cron like:
0 4 * * * root sh /home/example/borg_backup.sh > /dev/null

The intention is to report with an email by crontab only when I have some error in my backup, but with this behaviour I recieve an email everyday.

How do you consider that it would be used?

Thanks in advance

**Comment by ThomasWaldmann** [comment]
@jpsknr using stderr for logging if stdout is (sometimes or always) used for data transport is not that far fetched, e.g. all cgi / wsgi web software works that way.

What you need is a script that redirects stderr (and stdout if you do not use it for data transport) to a file, checks the return code of borg and then sends notifications, if the rc is indicating an error.

**Comment by jpsknr** [comment]
Thanks @ThomasWaldmann
