### ISSUE TITLE
borg config --cache

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3584]
In #3581 I am adding validition for keys/values for borg config right now (use for set and delete, so people do not set invalid values that make borg and even "borg config" crash).

But somehow I can't come up with anything one would want to config in the "cache" config.

@milkey-mouse any idea?

**Comment by sourcejedi** [comment]
When I upgrade to borg 1.1 (:-), I want to use `borg config --cache` to set `previous_location`.  I create repositories at a temporary location, and then rename them in-place.  So I need to update `previous_location` to avoid prompting.  This is to avoid any issues if the process is interrupted half-way through creating the repo.  (Any alternative solution would also be of interest to me :-).

**Comment by milkey-mouse** [comment]
What @sourcejedi mentioned was my main use case for `borg config --cache` as well. I can't think of many others though.

**Comment by ThomasWaldmann** [comment]
already fixed a while ago by 810986f0f57589a708cb0e40da47dc21681b108e.
