### ISSUE TITLE
Hardlink failed, cannot securely erase old config file

### ISSUE THREAD

**Issue by smoneck** [borgbackup/borg#3591]
```
mount -t davfs https://owncloud.provider.com/remote.php/webdav/ ~/owncloud/
borg init -e repokey-blake2 ~/owncloud/backup
```
results in
```
Hardlink failed, cannot securely erase old config file
```

What does that mean and indicate?

Arch Linux 4.14.15, borg 1.1.4

**Comment by ThomasWaldmann** [comment]
```
    def save_config(self, path, config):
        config_path = os.path.join(path, 'config')
        old_config_path = os.path.join(path, 'config.old')

        if os.path.isfile(old_config_path):
            logger.warning("Old config file not securely erased on previous config update")
            secure_erase(old_config_path)

        if os.path.isfile(config_path):
            try:
                os.link(config_path, old_config_path)
            except OSError as e:
                if e.errno in (errno.EMLINK, errno.ENOSYS, errno.EPERM, errno.ENOTSUP):
                    logger.warning("Hardlink failed, cannot securely erase old config file")
                else:
                    raise

        with SaveFile(config_path) as fd:
            config.write(fd)

        if os.path.isfile(old_config_path):
            secure_erase(old_config_path)
```

This is what borg does to update the config in a safe and secure way.

If hardlinks are not supported by you fs, it will still work, but it won't be totally safe any more, e.g. if the system crashes in the moment when borg starts writing the config file, then it could be lost.

When hardlinks work, you would still have the config file's content hardlinked to `config.old` if that happens.

**Comment by ThomasWaldmann** [comment]
Hmm, I just had a look at `SaveFile` and that also does a good effort on not losing the config file in case updating it goes wrong:

```
class SaveFile:
    """
    Update file contents atomically.

    Must be used as a context manager (defining the scope of the transaction).

    On a journaling file system the file contents are always updated
    atomically and won't become corrupted, even on power failures or
    crashes (for caveats see SyncFile).
    """

    SUFFIX = '.tmp'

    def __init__(self, path, binary=False):
        self.binary = binary
        self.path = path
        self.tmppath = self.path + self.SUFFIX

    def __enter__(self):
        from .. import platform
        try:
            truncate_and_unlink(self.tmppath)
        except FileNotFoundError:
            pass
        self.fd = platform.SyncFile(self.tmppath, self.binary)
        return self.fd

    def __exit__(self, exc_type, exc_val, exc_tb):
        from .. import platform
        self.fd.close()
        if exc_type is not None:
            truncate_and_unlink(self.tmppath)
            return
        os.replace(self.tmppath, self.path)
        platform.sync_dir(os.path.dirname(self.path))
```

@enkore can you clarify why we need both mechanisms and what can go wrong if hardlinks don't work?

**Comment by ThomasWaldmann** [comment]
@smoneck the short answer is that you may ignore that warning. if nothing crashes and nobody is forensically analyzing your filesystem, nothing special will happen.

**Comment by ThomasWaldmann** [comment]
Ah, now I see it. As the warning message says, it can't securely erase the contents of the old config file. The old config file will be deleted, but the disc sectors its data had occupied are still there on disk (logically freed, but not overwritten by zeros).

**Comment by smoneck** [comment]
Thanks a lot for the clarification! Is it just a thing while initializing a repository? Or in other words: When do I have to be careful apart from the initialization. During normal `borg create` the config is not touched, right?

**Comment by ThomasWaldmann** [comment]
That code is always used when the config is written. Could be also when you change the passphrase of your encrypted key.

**Comment by enkore** [comment]
Seems to me like the error message should be more clear what this means.

Instead of

> Hardlink failed, cannot securely erase old config file

try something like

> Failed to securely erase old repository config file (\<not supported\>). Old repokey data, if any, may persist on physical storage.

**Comment by Sean-T-Moore** [comment]
I'm a new borg user using v 1.2.2 and it's a real head scratcher when this message gets displayed first thing during creation of a new repo on a filesystem that doesn't support hard links. The message reads: "Failed to securely erase old repository config file (hardlinks not supported). Old repokey data, if any, might persist on physical storage". Old config file? There isn't any old config file to be found. The warning makes no sense to somebody starting out, and it comes across as a critical failure that needs to be addressed. It continues to get displayed during other borg operations although there is nothing for the user to do. Perhaps a simple warning about hard links not supported during the init step would suffice and a link to some FAQ on filesystems on why they are preferred?

**Comment by ThomasWaldmann** [comment]
Yeah, it might be a disturbing message, but it just tells how it is.

If borg can not do a **secure erase** (overwrite with crap before deleting) of the old config, it will just simply (insecurely) erase it (delete it). But that means that the borg key (in case you use repokey) will still be present on some blockdevice block that is not used any more.

Usually this is maybe not interesting because the key is encrypted / protected with a passphrase. But just assume the passphrase was disclosed somehow and you change it to a new safe passphrase. In that case, the existance of the key which was encrypted with the old passphrase on a freed block of your block device might become a security problem.

That's why borg warns about it.

And as borg is usually used on the CLI, it outright tells the fact as you can't easily click on a "link to the FAQ" in a terminal.

**Comment by Sean-T-Moore** [comment]
Thanks for the clarification! Sounds like mode keyfile instead of repokey would be safer when using exfat repo drives. Too bad there isn't a cross-platform journalling filesystem that supports hard links.

**Comment by obitbef** [comment]
The unnecessary warning message when creating a **new**  repository is caused by saving the config first without the key and then again writing the config with the key.

**Comment by ThomasWaldmann** [comment]
@obitbef at that point, you're right, there can't be a key in the config.

BUT, see it as an early warning. If the repo storage does not support secure erase, it is a potential problem.
