### ISSUE TITLE
OverflowError in hashindex

### ISSUE THREAD

**Issue by JonasKvarnstrom** [borgbackup/borg#3592]
I just got the following error in Borg 1.1.4 (I replaced some information that should be irrelevant with "...").  Seems related to https://github.com/jborg/attic/issues/354 but I've never used attic.

```
Traceback (most recent call last):1 N z/devel/repo/everything/db/revs/18/18438                                                                                                                              

  File "/usr/local/lib/python3.5/dist-packages/borg/remote.py", line 248, in serve
    res = f(**args)

  File "/usr/local/lib/python3.5/dist-packages/borg/repository.py", line 1069, in put
    self.index[id] = segment, offset

  File "src/borg/hashindex.pyx", line 212, in borg.hashindex.NSIndex.__setitem__

OverflowError: value too large to convert to uint32_t

Borg server: Platform: Linux jonas-P5Q 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64
Borg server: Linux: Ubuntu 16.04 xenial
Borg server: Borg: 1.1.4  Python: CPython 3.5.2
Borg server: PID: 8236  CWD: /home/jonas
Borg server: sys.argv: ['/usr/local/bin/borg', 'serve', '--restrict-to-path', '/back/']
Borg server: SSH_ORIGINAL_COMMAND: 'borg serve --umask=077 --info'
Platform: Linux ... 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64
Linux: Ubuntu 17.10 artful
Borg: 1.1.4  Python: CPython 3.6.3
PID: 15915  CWD: /raid/...
sys.argv: ['/usr/local/bin/borg', 'create', '-v', '--progress', '--stats', '--filter=AME', '--compression=zlib', '--noatime', '--nobsdflags', '--checkpoint-interval', '600', '--exclude-from', '...', 'ssh://jonas@.../...::...', '.']
SSH_ORIGINAL_COMMAND: None
```

This is using Borg 1.1.4 on Ubuntu 17.10 to back up to Borg 1.1.4 on a remote server (Ubuntu 16.04, actually on the same LAN).  I was trying to create the first archive in a new repository.  The file in question (db/revs/18/18438) is about 1.5 GB in size.

At the moment this seems reproducible: I just ran my backup script again and got the same error for the same file.  A status line right before part of it was overwritten by an error message:

5.94 GB O 4.31 GB C 4.28 GB D 31541 N z/devel/repo/everything/db/revs/18/18438                                                                                                                                     

At this point it had processed about 1.5 GB of the file, so I assume something happened at the end of that file.

The same files have been backed up to two local destinations (local file system access instead of ssh://), though this has happened over a period of time, not everything at once.  The remote destination is new.

Is there anything specific that I can do to debug this?

**Comment by ThomasWaldmann** [comment]
Can I please see your repo/config?

You may change/shorten the id if you like and of course also *remove the key*, but please show the other values "as is".

**Comment by ThomasWaldmann** [comment]
It looks like the offset part of (segment, offset) pair overflows and this should not happen in default configuration, but could happen if one manually sets the max segment size to a value that is too close to 4GB.

**Comment by JonasKvarnstrom** [comment]
Thanks, the max segment size might be the clue I was missing!  It reminded me that I originally used Borg 1.0 and didn't want the default segment size, so I wrote a script that created a repo and changed some parameters such as increasing the default 5 MB segment size to 200 MB.  Possibly the regexp pattern was still applicable when I created the new repo using Borg 1.1, so that the script changed the new default of ~500 MB to ~20000 MB (with trailing digits still present)!

I don't have access from here but I'll get back to you as soon as I know if this was what happened.

**Comment by JonasKvarnstrom** [comment]
This was indeed the problem.  Previously the default max segment size was 5242880, so my script included:

`perl -pi -e "s/size = 5242880/size = 209715200/g" "$1/config"`

Now the default segment size is 500 GiB = 524288000, exactly 100 times as much, so the pattern still matched.

Sorry about the false alarm!  (On the other hand, it may be a good idea to refuse to use a max_segment_size that is definitely too large.)

**Comment by ThomasWaldmann** [comment]
Add validation of this value.

**Comment by ThomasWaldmann** [comment]
validator: max_segment_size <= MAX_UINT32 (== 2^32 - 1)

Note: segments can be slightly (MAX_OBJECT_SIZE) larger than max_segment_size, but we store the offset to the start of objects within the segment file into the hashindex (repo index), so this does not matter. Also, only the hashindex code has uint32 limits, the high-level python code works with python integers which can be larger than MAX_UINT32.
