### ISSUE TITLE
free space is not reclaimed after borg recreate --exclude

### ISSUE THREAD

**Issue by Catscrash** [borgbackup/borg#3593]
Hi,

I removed huge files from my repository using borg recreate and borg info ... shows, that the size of the repositories is quite small now:

```
                       Original size      Compressed size    Deduplicated size
All archives:              264.61 GB            239.40 GB             38.82 GB
```

But the folder still uses the old amount of space:

```
du -sh xxx
446G    xxx
```

what did I do wrong?

thanks!

**Comment by infectormp** [comment]
did you check repo size befor and after recreate?

**Comment by Catscrash** [comment]
yes, repo size using du before was 446G as well. And at that point borg info showed the same amount at deduplicated size

**Comment by dimejo** [comment]
Did you run `prune` after `recreate`? It is not explicitly mentioned in the docs but I think you still need to run it after removing files.

**Comment by Catscrash** [comment]
I just did, but that did not change anything.

**Comment by Catscrash** [comment]
Somehow the repo config was set to append_only 1, although I thought I only used the ssh append-only option. I removed it and re-ran prune, now it's shrinking down, I think it might run a while longer and will close this issue if that was the solution.

**Comment by ThomasWaldmann** [comment]
With `append-only = 1`, this behaviour is expected and intended.
