### ISSUE TITLE
Borg 1.0.11: exception in RPC call

### ISSUE THREAD

**Issue by corkerss** [borgbackup/borg#3595]
Hello, 

Currently receiving this error when back up Borg over SSH on OSX High Sierra to Ubuntu Server 16.04.
Backed up using script. No errors running script on server locally. Back up completes.

Remote: Borg 1.0.11: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 141, in serve
Remote:     raise InvalidRPCMethod(method)
Remote: borg.remote.InvalidRPCMethod: RPC method get_free_nonce is not valid
Remote: Platform: Linux ubuntu 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64
Remote: Linux: Ubuntu 16.04 xenial
Remote: Borg: 1.0.11  Python: CPython 3.5.2
Remote: PID: 31811  CWD: /home/martin
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--info']
Remote: SSH_ORIGINAL_COMMAND: None

Thanks

**Comment by infectormp** [comment]
can you update borg to actual version and reproduce error?

**Comment by corkerss** [comment]
I'd rather not, my server back ups are currently working and stable. 
The upgrade process is not super clear from version to version. Do I need to upgrade the repos using borg update or do I download the latest .deb and depackage and it will take care of the repos automatically?

**Comment by ThomasWaldmann** [comment]
These messages are normal when borg 1.1 client talks to borg 1.0 server, just ignore them.
To get rid of them, upgrade the server side to 1.1, too.

**Comment by corkerss** [comment]
many thanks
