### ISSUE TITLE
Documentation for "pf:" (path full-match) -- what is a "whole path"?

### ISSUE THREAD

**Issue by JonasKvarnstrom** [borgbackup/borg#3598]
My backup script creates archives using relative paths -- essentially:

`cd /home; borg create /path/to/repo::my-files jonas`

I needed the script to find some files matching certain criteria and exclude them from the backup.  The pf pattern seemed best suited for this, and the current documentation for pf: patterns says:

> This pattern style is useful to match whole paths. This is kind of a pseudo pattern as it can not have any variable or unspecified parts - the full, precise path must be given. pf:/data/foo.txt matches /data/foo.txt only. 

This emphasizes "whole paths" and "the full, precise path", and gives an example using an absolute path.  To me this initially seemed to indicate very clearly that I need to use absolute paths (/home/jonas/whatever), but then nothing was matched/excluded.  

In hindsight I suppose I should have realized that a "full path" refers to what would have been stored in the archive, which is a "full" but *relative* path.  Still, maybe the documentation can be clarified (assuming I'm correct)?

(I might do it myself but right now I don't have the time.)

**Comment by ThomasWaldmann** [comment]
Please give a full script that reproduces your issue.

**Comment by JonasKvarnstrom** [comment]
I'll take a look at writing a script that reproduces this, but first I'll try to clarify my description.

The examples at https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns are written to create backups starting at an absolute path such as "/".  For example:

```bash
# Exclude '/home/user/file.o' but not '/home/user/file.odt':
$ borg create -e '*.o' backup /
```

Here the backup starts at "/".  In my case I *could* have chosen to start the backup of my home directory at /home/jonas:  borg create ... /path/to/backup/repo /home/jonas.

Instead I started my backup by doing essentially:

```bash
cd /home
borg create ... /path/to/backup/repo jonas
```

That is, I'm backing up the directory "jonas" which is a relative path.  In this case all file paths are (as far as I can tell) internally represented as relative paths as well:

```
jonas/.bashrc
jonas/devel
jonas/MyDocument.txt
```

These are the paths that are given to the Borg pattern matcher.  So if I want to include or exclude something from my backup using a pf: pattern, I do have to include the *whole* path -- but that refers to the whole *relative* path:

```
# Works as expected
pf:jonas/devel
```

If I specify full absolute paths, it won't work because the pattern matcher never sees those absolute paths:

```
# Won't work
pf:/home/jonas/devel
```

That I tried to use absolute paths is in many ways my own fault.  The documentation doesn't explicitly refer to absolute paths, only to "full paths".  But this might still be clarified.
