### ISSUE TITLE
BORG_UNKNOWN_UNECRYPTED_REPO_ACCESS_IS_OK=yes not work

### ISSUE THREAD

**Issue by michalkolar** [borgbackup/borg#3599]
Hi, i have problem with borgbackup env variable.

Backup script:

#!/bin/sh
export BORG_RSH='/usr/local/bin/pv-wrapper ssh'
export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
export BORG_UNKNOWN_UNECRYPTED_REPO_ACCESS_IS_OK=yes
python -c 'import os; print(os.environ)'
cd /dev/lvm/
borg create --stats --progress --read-special root@backupserver:/aaabbbccc/$1::{now:%Y-%m-%d} ./$1

Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN]

root@vs1:~# borg -V
borg 1.1.3

Best regards,
Kolar

**Comment by ThomasWaldmann** [comment]
UNENCRYPTED

On February 6, 2018 7:55:58 PM GMT+01:00, "Michal Kolář" <notifications@github.com> wrote:
>Hi, i have problem with borgbackup env variable.
>
>Backup script:
>
>#!/bin/sh
>export BORG_RSH='/usr/local/bin/pv-wrapper ssh'
>export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
>export BORG_UNKNOWN_UNECRYPTED_REPO_ACCESS_IS_OK=yes
>python -c 'import os; print(os.environ)'
>cd /dev/lvm/
>borg create --stats --progress --read-special
>root@backupserver:/aaabbbccc/$1::{now:%Y-%m-%d} ./$1
>
>Warning: Attempting to access a previously unknown unencrypted
>repository!
>Do you want to continue? [yN]
>
>root@vs1:~# borg -V
>borg 1.1.3
>
>
>Best regards,
>Kolar
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/3599

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by michalkolar** [comment]
Sorry 👍  Problem solved :)
