### ISSUE TITLE
BORG_KEYS_DIR directory must not contain foreign stuff

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#360]
if key dir points to i.e. /cygdrive/d (a ntfs drive) it gets an error:

IsADirectoryError: [Errno 21] Is a directory: '/cygdrive/x/$RECYCLE.BIN'

**Comment by ThomasWaldmann** [comment]
Works for me:

```
(borg-env)tw@tux:~/w/borg$ export BORG_KEYS_DIR=/tmp/keytest
(borg-env)tw@tux:~/w/borg$ mkdir $BORG_KEYS_DIR
(borg-env)tw@tux:~/w/borg$ ls -ld $BORG_KEYS_DIR
drwxrwxr-x 2 tw tw 40 Nov  2 20:23 /tmp/keytest
(borg-env)tw@tux:~/w/borg$ ls -l $BORG_KEYS_DIR
total 0
(borg-env)tw@tux:~/w/borg$ borg init --encryption keyfile repo5
Initializing repository at "repo5"
Enter new passphrase: 
Enter same passphrase again: 
Remember your passphrase. Your data will be inaccessible without it.
Key in "/tmp/keytest/repo5" created.
Keep this key safe. Your data will be inaccessible without it.
initializing cache
synchronizing cache
Synchronizing chunks cache...
Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
Done.
(borg-env)tw@tux:~/w/borg$ ls -l $BORG_KEYS_DIR
total 4
-rw------- 1 tw tw 533 Nov  2 20:23 repo5
(borg-env)tw@tux:~/w/borg$ cat /tmp/keytest/repo5 
BORG_KEY bbefa36a404b2b...
```

**Comment by ClipperS87** [comment]
grrr-"export" was missing-plse.srry

**Comment by ClipperS87** [comment]
sorry, but if key dir points to i.e. /cygdrive/d (a ntfs drive) it gets a error 
IsADirectoryError: [Errno 21] Is a directory: '/cygdrive/x/$RECYCLE.BIN'

**Comment by ClipperS87** [comment]
...that also occurs if i simply generate a "$subdir" in the keys-dir

**Comment by ThomasWaldmann** [comment]
Well, it is unfortunate that on windows, a seemingly "empty" drive is not really empty, but that is not borg's fault. Due to that (and sometimes also due to other limitations, like limited entries in root directory), it is never a good idea to put stuff directly into the root.

You just have to point BORG_KEYS_DIR to an empty directory, not having or putting other stuff in there.

I'll have a look at the error it throws, but above will always apply.

**Comment by ClipperS87** [comment]
background info:
due to lack of multitreading you can run multiple instances against multiple repositories
also for different filetype (like backing up classical windows C drives, user Data or VMDK files) each having different repositories which different block geomerties makes sense (refering to other documentation here on this site)
you and up with multiple repositories.

to keep compatibility for the future (as putting the passwort in a environment variable is a discontinued feature) i decided to use a -e keyfile for the repository with empty password

all keyfiles tother hosted on a veracrypted directory - my kind of single-sign-on solution....

**Comment by ThomasWaldmann** [comment]
if you search for a "passphrase" mode replacement: you can use "repokey".
putting a (key) passphrase into env var is not discontinued, just the "passphrase" mode is.

also, if using veracrypt causes these issues (as you mount it as a drive and drives have trashbins, I suppose), you could just have a key directory inside your veracrypt dir (and not use it directly).

**Comment by ClipperS87** [comment]
mmh, but having my keyword in environment is a security thread, IMHO
anyway, even if you have a sub-directory for your keyfile this error occures:
if you simply make a subdir like "../keydir/test" ist works fine but ich you have "../keydir/$test" it runs into the abovementioned error state

**Comment by ThomasWaldmann** [comment]
does the shell maybe "expand" your $test (to nothing)?

**Comment by ClipperS87** [comment]
i tried with "#subdir" and get the same error message

**Comment by ThomasWaldmann** [comment]
maybe just stop using characters that have special meaning on the shell?

**Comment by ClipperS87** [comment]
ok
