### ISSUE TITLE
Failed to init repository in curlftpfs folder

### ISSUE THREAD

**Issue by iron-udjin** [borgbackup/borg#3601]
```
# curlftpfs ftp://myftp.com:/ /mnt
# mkdir /mnt/files
# env BORG_PASSPHRASE=test borg init -e repokey-blake2 /mnt/files/
Local Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 137, in wrapper
    with repository:
  File "/usr/local/lib/python3.6/site-packages/borg/repository.py", line 179, in __enter__
    self.create(self.path)
  File "/usr/local/lib/python3.6/site-packages/borg/repository.py", line 251, in create
    with open(os.path.join(path, 'README'), 'w') as fd:
OSError: [Errno 45] Operation not supported: '/mnt/files/README'

Platform: FreeBSD test 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64 amd64
Borg: 1.1.4  Python: CPython 3.6.4
PID: 1044  CWD: /root
sys.argv: ['/usr/local/bin/borg', 'init', '-e', 'repokey-blake2', '/mnt/files/']
SSH_ORIGINAL_COMMAND: None
```
For any other local folder borg works fine. Is there way to solve this problem?

Thank you!

**Comment by iron-udjin** [comment]
Oh... it seems problem with curlftpfs, not with borg.
Sorry, closing this issue.

**Comment by ThomasWaldmann** [comment]
Yet another (fuse?) filesystem just not being good enough as a filesystem.

**Comment by iron-udjin** [comment]
It's curlftpfs problem. It seems project is dead.
As far as I understood, borg doesn't support backup to FTP and there is no in plans to add support of it. My hoster provider doesn't support any other protocol like NFS, CIFS or sFTP. Unfortunatelly borg backup became unusable when only FTP available for backup.

P.S: to make repo locally and sync it to FTP is not an option for me.

**Comment by ThomasWaldmann** [comment]
if it is really ftp (and not ftps), it is unsecure anyway as your ftp credentials go over the wire without tls encryption. there are providers offering other protocols as well as direct borg support like hetzner and rsync.net, in case that is an option for you.

**Comment by iron-udjin** [comment]
There is no need to securing connection in local network or isolated network of hosting provider. Moreover, SSL add unneeded overhead.

My hoster provide 100Gb storage by FTP for free. To have possibility use other protocols and increase storage space I need to pay addition fee. That's why use other backup software which supports FTP the easiest and cheapest way for me.

**Comment by ThomasWaldmann** [comment]
Famous last words. ;-) If they charge additionally for more secure stuff, that's just evil.
