### ISSUE TITLE
borg induces lots of traffic on davfs2

### ISSUE THREAD

**Issue by smoneck** [borgbackup/borg#3603]
When I access a user-mounted `davfs2` backup (several GB), borg creates lots of traffic "overhead".

E.g. `borg list` causes the complete download of the backup before it lists the content. `borg delete` as well.

Why is it so? Is it a bug? Is it `davfs2`? The overhead as shown by `iftop` is ridiculous.

----
**EDIT** About 13 GB of download traffic for the deletion of a ~ 5 GB commit. :/

**Comment by smoneck** [comment]
[`borg` and `davfs2` are incompatible](https://github.com/borgbackup/borg/issues/3594)

**Comment by ThomasWaldmann** [comment]
If you want to qualify network filesystems, you could compare traffic on nfs or smbfs compared to davfs2.

OTOH, if davfs2 does not work stable enough (in general, borg does just normal fs calls), it's maybe useless for any heavy use.
