### ISSUE TITLE
borg mount doesn't work for remote storage

### ISSUE THREAD

**Issue by bugsyb** [borgbackup/borg#3611]
Hi All,

borg mount or borgfs do not accept remote repo (ssh based) whilst at the same time same repo is accepted to create backups and to list content.

Is this expected behaviour?

Thanks.

**Comment by ThomasWaldmann** [comment]
It should work. Check for repo URL syntax errors and order of options and arguments.

If you don't succeed, give the precise commands you used which did not work (mount) and which worked (create).

**Comment by bugsyb** [comment]
Many thanks for swift feedback. Problem does not exist on up to date system (Mint) with latest borgbackup.

Tests where performed using LiveISO Cinnamon 18.2 with manually added repo and installed what seemed to be the latest borgbackup.

After system has been restored using borg extract, same borg mount command (executed from saved earlier script) did work flawlessly now.

Thanks for help and quick confirmation that everything should work. I suspect it was case of some libraries which were not really up to date even if were fulfilling all min version requirements.
