### ISSUE TITLE
support request: borg info - type of compression questions

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#3614]
Hi, where/how is compression type (lz4, lzma, zstd) stored in borg metadata?
I saw only one occasion -> in the  ...
'Command line: /usr/bin/borg create --compression lz4 ...' part of a ...
$ borg info repo::archive
...call I made.

So is the "command line" string the only way we can tell what compression was used for a specific archive's creation?
Thanks in advnce.

**Comment by ThomasWaldmann** [comment]
There is the command line used and recorded in the metadata, you already have that.

But that is only for informative purposes, borg internally uses the compression type byte recorded in the chunk header. And that can be a mixup of compressions btw, e.g. if some chunks were already present in the repo and compressed with method A back then and you compressed the new chunks with method B.

**Comment by DrupaListo-com** [comment]
thanks, I got the full picture now.

**Comment by DrupaListo-com** [comment]
So as of now you can't easily get stats info for the chunks and their compressions right?

Like - from 1000 chunks in this archive 63% use lz4 and 22 % use zstd etc...

**Comment by ThomasWaldmann** [comment]
No.

**Comment by DrupaListo-com** [comment]
Are you open to adding such an option to borg info? If for example I work on it?
example: borg info repo::archive --compression-report # gives aggregated info about chunks' compression types used
or alternative options names: --chunks-report / --chunks-stats / --chunks-info

For me it's interesting to somehow automate the stats extraction, because this way it becomes easier to recreate(recompress) some repos/archives and others that are already processed - skip.

**Comment by ThomasWaldmann** [comment]
I don't see a big need for that.

**Comment by DrupaListo-com** [comment]
the whole reason for current thread is this:
https://github.com/borgbackup/borg/issues/3622

So if 3622 gets solved somehow, the option compression-report is not needed anymore.
