### ISSUE TITLE
"borg recreate --recompress" docs is hard to understand

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#3617]
Please someone translate this to sth more clear:
I quote from: https://borgbackup.readthedocs.io/en/stable/usage/recreate.html
"recompress data chunks according to --compression if if-different. When always, chunks that are already compressed that way are not skipped, but compressed again. Only the algorithm is considered for if-different, not the compression level (if any)."

1. what is 'if-different' ?
2. why is it underlined?
3. what is "always"?
4. And why 'Only the algorithm is considered for if-different, not the compression level (if any)' - does that mean that when we use " --recompress --compression zstd,14" 14 is gonna be ignored and the default level 3 used ? If not always when?

This section needs rewriting and examples what to expect when recompressing.

**Comment by DrupaListo-com** [comment]
follow up Q:
Do we always have to use  --recompress and --compression algo,L together? Does recreate w/o recompress but WITH --compression make sense?

**Comment by ThomasWaldmann** [comment]
The underlined stuff are option values. But it is not obvious that the option has values.

**Comment by ThomasWaldmann** [comment]
`--recompress=if-different` will not recompress e.g. `zstd,1` to `zstd,10`, because it is both zstd, so not considered different.

**Comment by DrupaListo-com** [comment]
... while always will recompress even those. I get it.
What happens if one uses --recompress without any value to it? Recompress is a)Silently ignored or b)always/if-different assumed?

**Comment by knutov** [comment]
> What happens if one uses --recompress without any value to it

You can just try it.

It will rise an error about wrong parameter

**Comment by DrupaListo-com** [comment]
thing is - it doesn't. I tried and now I wonder what happened during execution of a cmd like:
borg recreate repo::archive --recompress --compression zstd,10
... did it recompress always,some or none.
I have to do more tests now and will come back.

**Comment by ThomasWaldmann** [comment]
@DrupaListo-com see #3676.

**Comment by DrupaListo-com** [comment]
Thanks a ton!
I'm closing this one. We can polish things in #3676 as needed.
