### ISSUE TITLE
Debian install package for 1.1.4 causes too many conflicts

### ISSUE THREAD

**Issue by blackwhitekez** [borgbackup/borg#3618]
When I try ti install the debian package for 1.1.4 it tells me that 128 other packages on the system need updating. Due to conflicts it will force the uninstallation of Qgis software.

A backup client should have a small footprint on a compuyter, I do not understand why so many packages need to be updated.

Currently also logged as bug 890370 on Debian Bugs
[1.txt](https://github.com/borgbackup/borg/files/1723129/1.txt)

**Comment by kasimon** [comment]
AFAIK the borg project officially only releases its distro-independent binaries: https://github.com/borgbackup/borg/releases/

The debian package is created by the debian project, but let me add some remarks to your bug:

* Mixing packages from different debian releases is generally not recommended, unless you know exactly what you are doing. 
* Also, in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890370 you mention that you have to install the package from sid (unstable) to get 1.1.4. That is not correct, as you can see on https://packages.debian.org/borgbackup. 1.1.4 is in stretch-backports, buster and sid, so if you are running stable (stretch) and don't want to use the binary from the borg project, just install the backports version:

    sudo apt install -t stretch-backports borgbackup

and you should be good to go.

**Comment by blackwhitekez** [comment]
Thanks, I have just found the same solution
