### ISSUE TITLE
recreate : add --always-yes, --yes option to avoid typing YES when mass recreating

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#3619]
Am I missing sth or it's currently impossible to iterate through all archives and avoid having to say YES manually on each archive?
The only way to circumvent is to run the recreate on the repo and not on the repo::archive1,2,3.
But in the recreate-repo case, there is no prefix/filter for archives option. And you still have to type YES once.

**Comment by ThomasWaldmann** [comment]
Did you check the docs about environment variables? There are some "auto answerers".

**Comment by DrupaListo-com** [comment]
totally forgot about these, although at some point I've read those docs.
I think it's a good idea to ref these docs in the recreate docs, for other guys like me.

**Comment by ThomasWaldmann** [comment]
Well, that would mean to add a reference to basically all borg commands, making the docs (and builtin help and man pages) even larger and more time consuming to read. So I'ld rather not do that.

**Comment by DrupaListo-com** [comment]
OK. In future if same question comes over and over, maybe for 1-2 borg commands you can make an exception - but only when it becomes self evident that people need it.

**Comment by DrupaListo-com** [comment]
@ThomasWaldmann this is 50% support RQ and 50% feature RQ. Let's file it as a support request and close it until (IF at all) it resurfaces again.
PS. Do we really have a yes/no question/prompt on many of the subcommands? I guess everyday usage made me forget about these and so recently when I first used recreate I was annoyed I can't figure out how to auto-YES it.

**Comment by knutov** [comment]
`yes 'YES' | borg recreate ...` is working too wor this problem.

**Comment by ThomasWaldmann** [comment]
@knutov that is a bad idea as it will answer all questions with YES. there are some security related questions that usually should not be answered automatically.
