### ISSUE TITLE
add some conceptual intro to quickstart docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3620]
explain what a repository is, what an archive is.
otherwise it is hard to understand for people who never used git, tar, etc. before.

anything else?

**Comment by bhaveshpoddar94** [comment]
I can look into it.

**Comment by ThomasWaldmann** [comment]
@bhaveshpoddar94 sure, do it! :)

**Comment by bhaveshpoddar94** [comment]
https://github.com/borgbackup/borg/blob/master/README.rst#easy-to-use
I am assuming this is where the description needs to go. Correct me if I'm wrong.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/master/docs/quickstart.rst

I'ld put it there ^, the readme should stay a short as possible for an "elevator speech".

**Comment by bhaveshpoddar94** [comment]
So just a brief description of a repo and an archive at the beginning of the docs would suffice right?

**Comment by ThomasWaldmann** [comment]
Yes.

On March 4, 2018 9:32:02 AM GMT+01:00, Bhavesh Poddar <notifications@github.com> wrote:
>So just a brief description of a repo and an archive at the beginning
>of the docs would suffice right?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/3620#issuecomment-370211450

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bhaveshpoddar94** [comment]
Archive is to be explained in general, not with respect to git?

**Comment by ThomasWaldmann** [comment]
Yes. I think 1 or 2 sentences for repo and archive is enough.
