### ISSUE TITLE
recreate: avoid recompressing same chunk twice

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#3622]
Q1: when I run 
$ for archive in a1 a2 a3; do borg recreate repo::$archive --recompress always --compression abc,L ; done

... will this re-compress same chunk three times - if the chunk is shared by the 3 archives?

I now learned from another thread that --recompress accepts always and if-different - but I need if-different to be split into if-different-algo and if-different-algo-and-level - to cover all possible use cases.

Q2: Is that easy?

One way to avoid recompressing same chunk over and over again is via recompressing whole repo - IF some fail-safe to avoid multi-recompress-of-same-chunk is already in place - but whole-repo-recompress currently does not support filter by archive name.... which I need as I want to recompress/recreate only one sub-set of the archives.

The other way is to add --recompress if-different-algo-and-level.

**Comment by ThomasWaldmann** [comment]
A1: yes, always means always.

And we do not store the compression level, so there can be no decision based on the level.

Q2: it would need additional management and we do not currently have that (that could be e.g. an additional field in the chunks index, but we can not easily change that without causing compatibility issues esp. when downgrading).

So, considering recreate is a rare operation, I don't see enough reasons to change that.

**Comment by DrupaListo-com** [comment]
Sounds ok: to re-phrase:
- people that need to recompress from same compression ABC with level=3 to ABC level=10 will just use --recompress always and have to wait recompression to happen for 
a) XYZ.L -> ABC.10 - no room for improvement here
b) ABC.3 -> ABC.10 - again these need to be recompressed - no rrom for improvement
c) ABC.10 -> ABC.10 - for chunks already having same compression - with 'always' on they'll be re-compressed too but we need 'always' cause with 'if-different' b) and c) will be skipped.
So having to choose between
A) doing a) and skipping b and c (--recompress if-different)
and
B) doing a,b,c (--recompress always)

I'd just choose B) wait a bit extra time and be happy.
Cool.

**Comment by DrupaListo-com** [comment]
Final Q: When recompressing whole repo with 'always' - does it iterate archive by archive and recompresses shared chunks multiple times OR the iteration is over chunks from 1st to last?
Externally it could still say 'procesing archive 1' then 2, then archive 3, but what happens internally under the hood?

**Comment by DrupaListo-com** [comment]
...Cause to recompres a whole repo you have two options:
a) - loop through archives doing them one by one - might compress same chunks over and over again
b) - recompress whole repo directly - MIGHT be smart enough to avoid that

Is b) smart or "dumb" currently?

**Comment by ThomasWaldmann** [comment]
Looking at current code:

- the `ArchiveRecreator` maintains a `.seen_chunks` set, so it recompresses every chunk only once (this code is there since a while)
- new: I added code that can consider the level correctly, so one now can change the level using `--recompress=if-different` and same algorithm and different level will trigger recompressing. PR # ....
