### ISSUE TITLE
Permission denied in subfolder after 1 day

### ISSUE THREAD

**Issue by KodaCCH** [borgbackup/borg#3623]
Hi

I generate all day a backup with borg. The backups are all on a central system. This work. But after one day, when I check the backups wir borg -list i get a backup error in data direcotry:
```
tim@vm02:~/backups$ borg list vm01
Exception ignored in: <bound method Repository.__del__ of <Repository /home/tim/backups/vm01>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 171, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1259, in get_fd
    return self.fds[segment]
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 129

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 137, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 181, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 399, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1291, in get_segment_magic
    fd = self.get_fd(segment)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1261, in get_fd
    fd = open(self.segment_filename(segment), 'rb')
PermissionError: [Errno 13] Permission denied: '/home/tim/backups/vm01/data/0/129'

Platform: Linux vm02 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
Linux: debian 9.3
Borg: 1.1.4  Python: CPython 3.5.3
PID: 16805  CWD: /home/tim/backups
sys.argv: ['/usr/bin/borg', 'list', 'vm01']
SSH_ORIGINAL_COMMAND: None
```
The same with check or delete.

On backupserver I have a user tim where make borg init. On the vm01 I generate it as root and send with ssh/key
The first Backup work without problem.

**Comment by felixsteghofer** [comment]
Just have a look at the file permissions inside your repo folder. If you created the backup as root those should also only be accessible by root (usually 600 i.e. `-rw-------` when doing `ls -l ~/backups`).
Try to run as root, e.g. `sudo borg list vm01`.

Maybe you could access the first backup because you did not create the initial backup as root?

**Comment by KodaCCH** [comment]
Thank you. The first part I will check when Insee the error. 

The second: i have run borg init with tim (see first post), because I get a permission error when I run borg init as root
https://github.com/borgbackup/borg/issues/3616
What is the right way?

**Comment by felixsteghofer** [comment]
I both `borg init`ed the repo with privileged and unprivileged (most probably like you with user tim) users, but usually create actual backups as root to preserve file permissions. It should not make any difference how you initialised the repo if you backup as root, as far as i can tell.

**Comment by KodaCCH** [comment]
The problem is really with the rights. One part of files are chowned with tim, an other part with root.

The user on my Backup maschine is root and tim, the user on the vm01 is root
I have testet to borg init as root user. But then the vm01 say Repository path not allowed: /root/backups/vm01

**Comment by ThomasWaldmann** [comment]
@KodaCCH did your issues go away after fixing the permission mixup?

**Comment by KodaCCH** [comment]
Yes. When I run under root it works fine

**Comment by ThomasWaldmann** [comment]
Ok, closing as "the usual permission mixup".

**Comment by ThomasWaldmann** [comment]
#3587 for some hints about how to avoid the permission mixup.

**Comment by cwildfoerster** [comment]
Maybe just an heads up: Running `borg prune` as root on the may also cause permission mixups. In my case, i backup a couple of machines with a `backupuser` remotely and `borg prune` the backups locally on the server. At first at root, but after the first prune, all backups failed. Need to run `borg prune` also as `backupuser`
