### ISSUE TITLE
recreate resume possible?

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#3625]
Hi, I've searched the issue queue for similar topics, as always, but did not find anything for 'recreate resume' and 'recreate checkpoint'.

So after a failed recreate I have now a ARCHIVE-NAME-123.recreate.checkpoint arvhive along with normal ones.  ARCHIVE-NAME-123 was kept too ofc.

Question is besides deleting this recreate archive - can I do sth other useful with it?

**Comment by ThomasWaldmann** [comment]
I guess you should keep it until you've successfully completed the desired recreate operation.

**Comment by DrupaListo-com** [comment]
1. yeah, but what if the PC gets rebooted before a recreate completes OR borg is killed while recreating?
2. If I keep it, how will borg know / detect that it can resume? Based on a 2nd run with same params?
3. What if params are different next time?

**Comment by ThomasWaldmann** [comment]
borg never "resumes" from anything (neither from recreate nor create).

borg always does full backups (borg create) or a full recreate operation.

while doing that and having a checkpoint archive from an interrupted previous run, it just happens that borg notices it already has a lot of the chunks already in the repo, so it does not compress/encrypt/transfer/store them.

of course, it will only create the same chunks, if you do not change to other chunker params.
compression does not matter as the deduplication / detection of already present chunks works via the hash over the plaintext (not the compressed data, not the encrypted data).

so, keep the checkpoint from an interrupted run until you have a completed run of same operation and kill it afterwards.
