### ISSUE TITLE
how to safely delete borg cache

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#3626]
Hi, support Q:
1. I normally run borg having a shell var set/exported for BORG_CACHE_DIR=DIR-A.
But I've also recently run borg w/o this var set so borg used the default ~/.cache/borg/.
How should I proceed now:
a) to clear both dirs and start fresh? (it's ok if it's slow)
b) to clear DIR-A
c) to clear default  ~/.cache/borg/?

2. Is it safe to just delete both cache dirs and recreate them empty while borg is not running?

Thanks.

**Comment by ThomasWaldmann** [comment]
Easiest, but slowest, is to clear both and answer some question(s) the next time you run borg.

Alternatively, move the most recent cache you have to the place where you want it to be (and before that: clean whatever is at that place).

**Comment by DrupaListo-com** [comment]
Thanks! I'll go with 1st option as I really don't remember which one is the newest. I could probably compare file dir dates or contents but I am lazy. Thanks for confirming it's safe to empty those cache dirs.
PS. The reason this happened was bec. usually I rely on the bash env to set the cache dir var, but when u run borg via sudo and forget sudo -E which imports current bash env to sudo's env... the cache var is empty during that sudo run and ~/.cache/borg the default one is used...
Topic closed.
