### ISSUE TITLE
Is recreate replacing of dirs possible?

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#3627]
a bit weird question and one of the last ones I have for borg recreate:
- I know it's possible to exclude = retroactively delete dirs from old archives
- I know a backup's property is to store how files were at a point in time
- but what if one wants to delete a dir in a backup archive and then put a different version of it in its place ?
By the current recreate cmd's docs it's impossible to do via recreate.

The only way I can think of is to restore the archive in question to a tmp folder, do the replace and back up the modified restore again to a new archive. bonus: Since borg create allows to set a custom timestamp and archive name - one can make it look like an old archive... it's just a bit expensive to do hard-disk-cpu-wise.

Am I right above?

**Comment by ThomasWaldmann** [comment]
recreate reads an existing archive and creates a new one from that data.
you can add new data of course, this is not in the scope of recreate as this would need to additionally read stuff from disk.

so, yes, the method you pictured seems the best way to go for that.
