### ISSUE TITLE
Speed in Mb/s for progress

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#3630]
Is it possible to add speed in Mb/s (or Kb/s or smart) in progress line for actions like borg create, recreate, prune?

**Comment by ThomasWaldmann** [comment]
I don't like backup tools talking about Mbits/s.

The usual unit for storage is Bytes, not bits.

Also, having too much options just makes the usage of borg more complicated, the docs longer to read.

**Comment by ThomasWaldmann** [comment]
Besides units, I guess your main issue was to add *some* speed value to the output.

The progress output is already rather dense and we have to cope with 80 char long lines, so adding anything there is problematic (and we only have 1 line due to the way it is implemented).

**Comment by EthraZa** [comment]
But maybe we could customize the info that shows in this line, so we can choose to switch an useless info for a speed info?

**Comment by ThomasWaldmann** [comment]
So, which useless part would you remove/replace?

**Comment by EthraZa** [comment]
I don't even remember what info it gives, I'm just saying that if in a given moment, all I want to know is the speed, all the rest may be useless.

**Comment by EthraZa** [comment]
An idea could also be to interleave the information.

**Comment by jdchristensen** [comment]
It's really not clear what such a speed would mean.  For example, if an unchanged file is skipped, is it counted as processing that many bytes instantly?  What about a file that has one byte changed, so most chunks are unchanged?  Or should it mean the bytes/s written to the archive?  And would that be before or after compression?  Because of all of these variables, it's not clear to me that there's a useful "speed" to show to the user.

**Comment by ThomasWaldmann** [comment]
@jdchristensen yup, lots of issues there also.

**Comment by knutov** [comment]
From the other side, the really important thing I (and most people, I suppose) want is not the speed but estimated time. Although it seems to be not possible to calculate it now, so the speed is just something we can calculate and this can give some estimations.

**Comment by knutov** [comment]
@jdchristensen It's simple, I suppose. Borg already counting how much was read from disk, deduplicated, compressed. So it's simple to add some speed based on first parameter (read from disk).

**Comment by ThomasWaldmann** [comment]
@knutov  "predictions are hard, esp. if they are about the future."

We don't do predictions in borg, so no ETA.
