### ISSUE TITLE
Cut the backup into smaller pieces

### ISSUE THREAD

**Issue by meaz** [borgbackup/borg#3638]
Hi,
I just discovered borg which I like a lot. However, I have a question/problem that I can't fix. 
When borg creates a backup, in /data, there a lot of files. At least of those files is huge. I guess this is the first version of the backup.
Would it be possible to have instead smaller pieces of this huge file? I know duplicati can do that:  [https://www.duplicati.com/articles/Choosing-Sizes/](url) : by default, the backup files are no more that 50Mb, but you can increase or decrease that.
It would be very useful when I want to upload the backup folder, as my bandwidth is pretty low!

Thanks a lot

**Comment by ThomasWaldmann** [comment]
In attic and early borg, they used to be 5MB size, but for borg 1.1 we increased to 500MB for better efficiency (I guess primarily for local, high-bandwidth backups).

You can set the size in repo/config to lower values, if you like (that won't change the size of already existing files, though).

**Comment by meaz** [comment]
Cool: Thanks a lot @ThomasWaldmann ! Is there anyway to set it during initiation phase? Something like:
`borg init --max_segment_size = 5242880` (instead of 524288000)

or do I have to manually change the config file?

**Comment by ThomasWaldmann** [comment]
There is `borg config` since recently.
