### ISSUE TITLE
borg 1.1.4 doesn't build in ASCII universe anymore (requires UTF-8)

### ISSUE THREAD

**Issue by frispete** [borgbackup/borg#3639]
Hi,

the `lz4_system_prefix` test in setup_lz4.py results in this traceback under many conditions:
```
[   36s] + cd borgbackup-1.1.4
[   36s] + CFLAGS='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g'
[   36s] + python3 setup.py build
[   36s] Traceback (most recent call last):
[   36s]   File "setup.py", line 172, in <module>
[   36s]     liblz4_prefix = setup_lz4.lz4_system_prefix(possible_liblz4_prefixes)
[   36s]   File "/home/abuild/rpmbuild/BUILD/borgbackup-1.1.4/setup_lz4.py", line 28, in lz4_system_prefix
[   36s]     if 'LZ4_compress_default' in fd.read():  # requires lz4 >= 1.7.0 (r129)
[   36s]   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
[   36s]     return codecs.ascii_decode(input, self.errors)[0]
[   36s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 13333: ordinal not in range(128)
[   36s] error: Bad exit status from /var/tmp/rpm-tmp.EXSTbF (%build)
```

Here observed with openSUSE Tumbleweed (Factory) and python 3.6.4. Hence all build steps have to be processed under a `export LANG=en_US.UTF-8` clause. 

Don't know, if this is to be expected, but it deviates from earlier releases. (Yes, I know, that 3.7 will come with a mitigation in this area, but I would try to keep the build encoding agnostic.

**Comment by ThomasWaldmann** [comment]
This is already fixed in master, will be in 1.1.5.

Such code is used since long by us, but not all header file authors did put non-ascii stuff in there.
I refactored the code for 1.1.4, so that all library detection / processing is done in the same way.
