### ISSUE TITLE
statistics do not reflect processing order

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#365]
> showing Original, Compressed and Deduplicated sizes

the documentation states that compression is done after deduplication, so the column showing the compressed size should be last and (in case compression is used) showing the smallest values

currently (using compression) the column "deduplicted" shows the smalles value which seems wrong

**Comment by ThomasWaldmann** [comment]
Just to explain: the display is not reflecting the order in which it works, it is just doing global statistics about:
- sum of data size in all files considered (== you would need that much space if you just did a normal backup without compression)
- sum of compressed data size in all file considered (== you would need that much space if you just did a normal backup with compression)
- sum of unique compressed data size in all files considered (== additional repo space needed by borg)

This is same way as in "info" and "create --stats".

**Comment by ThomasWaldmann** [comment]
IIRC there is already some ticket about "info" with a similar request.

**Comment by ClipperS87** [comment]
this is the szenario:
i do backup first time with lzma,9 - because i have time and want to save space before i copy my backup to google storage ...
then I do daily lz4 backups from the same source 
So my repository in this moment has a mix like ("X" for lzma,9 compressed and "O" for lz4 compressed) XXXXXXXXXXO and after time XXXXXXXXXXOOOOOOOOOO
then i delete "unused old backups" (all before my last one) and (assuming that only 20% of my data have been changed since my first backup) end with XXXXXXXXOO and i store the new OO blocks to my google storage

having a mix of different compression methods used I am not sure how this is calculated:
"sum of compressed data size in all file considered"

**Comment by ThomasWaldmann** [comment]
borg stores original size and compressed size into the chunks list within the file metadata.
it also has a "chunks" index: chunkid -> refcount, size, csize for quick access.

**Comment by ClipperS87** [comment]
do you agree with that suggestion:
"backup"=range considered
sum of data size  (== size of data beeing backed up / checked for change)
_sum of unique data (== space needed for the (additional) chunks fo this backup)_
(this information is useful to optimize the chunker params!)
sum of compressed data size (== stand-alone space needed for this backup, each chunks may have different compression ratio)
sum of unique compressed data size (== additional repo space needed for this backup)

**Comment by ThomasWaldmann** [comment]
yes, sum of unique data seems useful.

**Comment by ClipperS87** [comment]
thank you - and also plse adapt the idea which is the idea behind the changed descriptions; in other words i would love to get this tools out of a "specialist" tool to a wider audience.
(plse put this to the place it belongs)

if we talk about backup we talk about recovery:
1. user, the primary us of this tool is nothing for backing up/restoring a accidentaly deleted file - use timeshift or any OS implemented versioning for that!
2. this tool is for recovery, preferred desaster recovery: so if your harddisk corrupted, your notebook taken by the authorities, your datacenter burned down - whatever; in this type of situation you need to get ready to work again 

- you need all of your data
-> full-backup PERIOD

- as fresh as possible
-> as only changed chunks are backed up and backup only uses one core you can backup every hour without impact on your ongoing work

- in a as-short-as-possible amount of time 
-> full restore at once instead of the restore in a "classical" backup process like one full restoe and then 3 differential and then 6 incremental backups

- from scratch
-> OS .iso from internet, no license files, passwords etc. needed
-> and your data from any glacier or google neartime storage

**Comment by ThomasWaldmann** [comment]
please, if you file tickets, stay focussed on the topic of the ticket and do not create tickets that deal with multiple topics.
