### ISSUE TITLE
documentation: what to use this program for

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#367]
if we talk about backup we talk about recovery:
1. user, the primary us of this tool is nothing for backing up/restoring a accidentaly deleted file - use timeshift or any OS implemented versioning for that!
2. this tool is for recovery, preferred desaster recovery: so if your harddisk corrupted, your notebook taken by the authorities, your datacenter burned down - whatever; in this type of situation you need to get ready to work again 

- you need all of your data
-> this tool does full-backup PERIOD

- as fresh as possible
-> as only changed chunks are backed up and backup only uses one core you can backup every hour without impact on your ongoing work

- in a as-short-as-possible amount of time 
-> full restore at once instead of the restore in a "classical" backup process like up to one full restore and then 3 differential and then 6 incremental backups

- from scratch
-> OS .iso from internet, no license files, passwords etc. needed
-> and your data from any glacier or google neartime storage

**Comment by ThomasWaldmann** [comment]
How do you use glacier or google neartime storage with borgbackup?

**Comment by ClipperS87** [comment]
currently i use google neartime storage and gsutil or my QNAP-NAS native "Cloud Backup Station"

**Comment by ThomasWaldmann** [comment]
So, you just use gsutil cp -R repo? how is that related to borgbackup documentation?

I mean you could make a copy of your repo in arbitrary many ways, but why should we document that?

**Comment by ClipperS87** [comment]
>and your data from any glacier or google neartime storage
>>and your data from any source local (like ext HD, BluRay, tape), centralized (like NAS) or Cloud (like amazon glacier or google neartime storage)

**Comment by RonnyPfannschmidt** [comment]
That could be a extra section in the dochs intended to be contribute by users of such tools

**Comment by ClipperS87** [comment]
@RonnyPfannschmidt anyone has a backup destination, or ;-)
..so -before opening a big discussion - I agree to simply delete this part
_and your data from any source local (like ext HD, BluRay, tape), centralized (like NAS) or in th cloud (like amazon glacier or google neartime storage)_

**Comment by ThomasWaldmann** [comment]
about 1. and 2.: you can use borgbackup for both.

about the rest: I don't see the point of adding this to the docs. While all is more or less true, this is either trivial or already seen in the basic feature list of borgbackup.
