### ISSUE TITLE
"borg config cat"

### ISSUE THREAD

**Issue by milkey-mouse** [borgbackup/borg#3671]
If borg config is called with no arguments, it would be useful for it to dump the entire repo or cache config file, as if `cat /path/to/repo/config` was called. Although I'm not sure if this conflicts with the idiotproofing mentioned in #3581 as there would be an even lower barrier to editing an important key...

For clarification, the command probably wouldn't actually be `borg config cat`, it would be like `borg config repo` with no key or value.

**Comment by Gu1nness** [comment]
@ThomasWaldmann Can I pick this one ?

**Comment by ThomasWaldmann** [comment]
@Gu1nness sure. See last line of top post. Also, please update your master branch first.

**Comment by Gu1nness** [comment]
Actually there is a bug in argparse which make it impossible to have all these behaviors possible without a patch : 
```shell
borg config <repo>
```
```shell
borg config <repo> --delete <key>
```
and
```shell
borg config <repo> <key> <value>
```

I have three possibilities : 
 * The first one, which is to add a patched class for the argument parser which supports interleaved optional positional arguments and optional arguments (I can create a Pypi repo for this and add it in the requirements of borg)
 * The second one, I use a ` borg config show <repo>` (or equivalently `borg config <repo> show` ) syntax, and this should be okay.
 * The last, kinda ugly one, I create only one argument for name and value ( [see here](https://github.com/borgbackup/borg/blob/master/src/borg/archiver.py#L3637) ) and then I check in the do_config function ( [see here](https://github.com/borgbackup/borg/blob/master/src/borg/archiver.py#L1524) ) that the list is at most 2 items long. Not sure I like this solution (especially in terms of help and usage which could be kind of broken).

@ThomasWaldmann which do you prefer ?

**Comment by milkey-mouse** [comment]
Why can't you make `repo` optional as well and just enforce `borg config --delete repo key value`?

**Comment by Gu1nness** [comment]
@milkey-mouse : From what I have read, the command to delete is `borg config repo --delete key` and not `borg config repo --delete key value`.
Also, I don't see the point in making repo optional ? The borg config command is dedicated to modifying the config of a repo, what would this command do ?

In my opinion, the best solution is to create a subcommand like borg config show <repo> when one wants to dump the repo configuration.

What do you think ?

**Comment by milkey-mouse** [comment]
When I said `borg config <repo>` above I didn't mean that `repo` was optional, I was just using angle brackets to indicate a placeholder (which is, in retrospect, confusing when talking about CLI syntax...)

**Comment by milkey-mouse** [comment]
I just realized this issue is kind of a duplicate of #3612. Oops.

**Comment by Gu1nness** [comment]
Indeed.
I'll go for borg config show <repo> then.
Concerning the other issue it is indeed a duplicate I guess. I think one of both should be closed in order to avoid redundancy.

**Comment by milkey-mouse** [comment]
I'm closing this issue as it's a duplicate, see #3612 for more information.
