### ISSUE TITLE
borg check --repair => AssertionError: maximum number of segments reached

### ISSUE THREAD

**Issue by wucke13** [borgbackup/borg#3686]
Today I wanted to add a snapshot to my local borg repo, however borg terminated with an error. I then started `borg repair --check`, which resulted in an interesting error:
```
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Data integrity error: Segment entry checksum mismatch [segment 52431, offset 4379711]
Data integrity error: Segment entry checksum mismatch [segment 52445, offset 824662]
Data integrity error: Segment entry checksum mismatch [segment 52576, offset 4167410]
Local Exception
Traceback (most recent call last):
  File "/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/lib/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/lib/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/lib/python3.6/site-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/lib/python3.6/site-packages/borg/archiver.py", line 304, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/lib/python3.6/site-packages/borg/repository.py", line 911, in check
    self._update_index(segment, objects, report_error)
  File "/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/lib/python3.6/site-packages/borg/repository.py", line 818, in _update_index
    s, offset = self.index.pop(key)
  File "src/borg/hashindex.pyx", line 144, in borg.hashindex.IndexBase.pop
  File "src/borg/hashindex.pyx", line 203, in borg.hashindex.NSIndex.__getitem__
AssertionError: maximum number of segments reached

Platform: Linux zorn 4.14.24 #1-NixOS SMP Sat Mar 3 09:24:39 UTC 2018 x86_64 
Linux:   
Borg: 1.1.4  Python: CPython 3.6.4
PID: 15048  CWD: /media/raid
sys.argv: ['/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/bin/borg', 'check', '--repair', '/media/raid/borg-repo']
SSH_ORIGINAL_COMMAND: None
```

More precisely `AssertionError: maximum number of segments reached` is what makes me curious: is there a maximum size for a borg repo, technical limited?

Here is some information about my system:
```
Platform: Linux zorn 4.14.24 #1-NixOS SMP Sat Mar 3 09:24:39 UTC 2018 x86_64 
Linux:   
Borg: 1.1.4  Python: CPython 3.6.4
PID: 15791  CWD: /media/raid
sys.argv: ['/nix/store/1p63bnppdnq60080dncbnigqhzq6h5vc-borgbackup-1.1.4/bin/borg', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('zorn@105852885032971', 15791, 0)
```
The regarding repo is about 280 Gb in size, contains ~25 Snapshots, of which the oldest may date back to mid 2017.

PS: I made the first snapshot with compression yesterday, using `zlib,9`, hopefully that is not likely to be the cause?

**Comment by ThomasWaldmann** [comment]
`Segment entry checksum mismatch` -> CRC32 error in the segment file entries.

Check disks, memory and other hardware.

**Comment by ThomasWaldmann** [comment]
#define _MAX_VALUE ( (uint32_t) 4294966271UL )

Quite a lot of segments, each about 5MB (borg 1.0) or 500MB (borg 1.1) by default.

**Comment by ThomasWaldmann** [comment]
borg check --repair should not blow up, but rather catch this exception.

**Comment by ThomasWaldmann** [comment]
@wucke13 did you run memtest86+ meanwhile, what was the result?

I had a look into the code and think that this error is only possible if your machine's RAM (or CPU) does not work correctly:
- the assertion fails while getting an entry from the repo index hashtable. it checks whether the segment number in the entry is within bounds.
- the entry has to somehow get into that index hashtable and the operation that does that has the same check, so it would trigger the same exception first
- check --repair starts from an empty repo index hashtable and rebuilds the index (in memory) from infos it gets from the segment files.

**Comment by ThomasWaldmann** [comment]
About "should not blow up": usually true, but in case of hw errors maybe the best option we have.

**Comment by wucke13** [comment]
The RAM was fine, passed one complete test. However, after rebooting the system, I was able to add a new snap to the repo just fine. I could imagine that this was the result of a long uptime (arround a week) on a non ECC-RAM system. Anyway, this most likely is nothing to blame borg for, so I'm closing.
