### ISSUE TITLE
getpass fails when invoking borg without a terminal

### ISSUE THREAD

**Issue by baldurmen** [borgbackup/borg#3689]
Hi!

I've written a [nagios/icinga2 check](https://gitlab.com/baldurmen/check_borg) to test the multiple borg archives I have, and when running it from a terminal, I have not problems whatsoever.

Sadly, when invoking it through icinga2 as an actual check, getpass fails since borg is not called from an actual terminal.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2052, in main exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1997, in run return func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 84, in wrapper kwargs['manifest'], kwargs['key'] = Manifest.load(repository)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 118, in load key = key_factory(repository, cdata)
  File "/usr/lib/python3/dist-packages/borg/key.py", line 87, in key_factory return RepoKey.detect(repository, manifest_data)
  File "/usr/lib/python3/dist-packages/borg/key.py", line 421, in detect passphrase = Passphrase.getpass(prompt)
  File "/usr/lib/python3/dist-packages/borg/key.py", line 311, in getpass return cls(getpass.getpass(prompt))
  File "/usr/lib/python3.5/getpass.py", line 92, in unix_getpass passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python3.5/getpass.py", line 127, in fallback_getpass return _raw_input(prompt, stream)
  File "/usr/lib/python3.5/getpass.py", line 149, in _raw_input raise EOFError
EOFError
```

This issue is referenced in the [getpass documentation](https://pymotw.com/2/getpass/#using-getpass-without-a-terminal).

I'm not sure I understand completely how borg deals with passwords, but if it helps, [my check exports BORG_PASSPHRASE](https://gitlab.com/baldurmen/check_borg/blob/master/check_borg#L90-93) as recommended by the documentation.

Do you think you could try to mitigate this by using `isatty` and `readline` as described in the getpass doc?

```
import getpass
import sys

if sys.stdin.isatty():
    p = getpass.getpass('Using getpass: ')
else:
    print 'Using readline'
    p = sys.stdin.readline().rstrip()

print 'Read: ', p
```

**Comment by ThomasWaldmann** [comment]
Please add the borg version, python version and OS you use.

**Comment by baldurmen** [comment]
Borg: `1.0.9-1`
OS: `Debian Stretch`
Python: `Python 3.5.3`

**Comment by ThomasWaldmann** [comment]
Not quite the latest stuff from us (1.0.11, 1.1.4), but I didn't see anything related in the 1.0 changelog, so I'll check the source code.

On your side, please make really really sure the BORG_PASSPHRASE env var is actually set/present in the environment where the affected borg command is run. This is the most frequent cause of error here.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.0.9/borg/key.py#L417

You can see there that only if does NOT find a BORG_PASSPHRASE (env_passphrase has returned None), it will query it from the user (assuming there is a terminal and a user).

So, I am quite sure that the env var was not set in borg's environment.

**Comment by ThomasWaldmann** [comment]
We could add code that deals with the situation more prettily instead of blowing up with EOFError.

**Comment by infectormp** [comment]
did you try export BORG_PASSPHRASE="xxx"?

**Comment by baldurmen** [comment]
@infectormp I'm not sure I understand what you are asking.

I've tried passing the environment variable two different ways:
* using `export BORG_PASSPHRASE` directly. As stated before, my [my check does this](https://gitlab.com/baldurmen/check_borg/blob/master/check_borg#L90-93)
* using the Icinga2 way, by using `env.BORG_PASSPHRASE` in the `CheckCommand` statement

Both end up passing the environment variable, as shown in the previous plugin output paste.

**Comment by ThomasWaldmann** [comment]
Are you echoing BORG_PASSPHRASE directly before a direct call to the borg binary?

I looked at the code again and my conclusion is still that the env var is not available in the borg process (you can look at the source code yourself, it is quite easy, see link above).

**Comment by ThomasWaldmann** [comment]
Do you use sudo in this case? Try without.

**Comment by baldurmen** [comment]
Ahhh, sudo was the culprit here... Sorry for the noise.

I've fixed that by running the nagios check with `sudo -E` instead of regular `sudo`.

As far as I'm concerned, this bug can be closed. Thanks for the help!

**Comment by ThomasWaldmann** [comment]
I'll improve the user experience for this in a PR soon...
