### ISSUE TITLE
prune question and try to get borg repository into Google Drive

### ISSUE THREAD

**Issue by daniel156161** [borgbackup/borg#3703]
i set async_upload to false into the config of google-drive-ocamlfuse

with that i can upload the repo backups without any problems on google Drive but the prune command don't work and put out a big error

now i try to sync with the -s into the mount skript (down below - Drive.txt)

sudo BORG_PASSPHRASE="$Key" borg prune	-v	\
   --list                           \
   --prefix $hostname'-root-'		\
   --keep-daily	'1'				    \
   --keep-weekly   '7'				\
   --keep-monthly  '1'				\
   --keep-yearly	'1'				\
    $repopfad						\

meant that it keeps one backup per day, seven daily backups into a week, one into the end of the month, one on the end of the year and how long would keep the yearly backups?

modify the Backup skript to get it working on Ubuntu Mate

[Backup.txt](https://github.com/borgbackup/borg/files/1827146/Backup.txt)
[Drive.txt](https://github.com/borgbackup/borg/files/1827147/Drive.txt)

**Comment by ThomasWaldmann** [comment]
if you have problems with ocamlfuse (which do not reproduce without ocamlfuse), file them there.

read the docs about `borg prune`, there is also a practical example there:
https://github.com/borgbackup/borg/blob/1.1-maint/docs/misc/prune-example.txt

**Comment by daniel156161** [comment]
ah okay thank you
