### ISSUE TITLE
Difference between "Deduplicated size" and real size of the repository

### ISSUE THREAD

**Issue by Thuffir** [borgbackup/borg#3709]
```
borg 1.1.4
Python 2.7.9
Linux xxx #1 SMP Debian 4.9.30-2A~4.2.0.201801290155 (2018-01-29) x86_64 GNU/Linux
```
`borg info` shows me:
```
                       Original size      Compressed size    Deduplicated size
All archives:                8.51 TB              5.36 TB            337.17 GB
```
but when I do a `df -hs` on the repository I get only `315G`.

Is my assumption that the Deduplicated size of the whole repo is the actual size wrong?

**Comment by stevesbrain** [comment]
Presuming you've done a data check, you'd be likely looking at possible filesystem/block size differences (at a guess)

**Comment by Thuffir** [comment]
Not sure what you mean, but ` du -hs --apparent-size` shows me also `315G`.

**Comment by stevesbrain** [comment]
In that case, not sure sorry :) I'm a user of borg, rather than someone who's delved into the code. I'll let someone more knowledgeable come up with a reasonable explanation!

**Comment by infectormp** [comment]
@Thuffir did you read https://borgbackup.readthedocs.io/en/stable/usage/info.html#description ?

**Comment by Thuffir** [comment]
Yes, and it says:
`All archives / deduplicated size = amount of data stored in the repo = all chunks in the repository.`
And that is why i though that it must be the "real" size of the repository.

**Comment by ThomasWaldmann** [comment]
```
>>> 337.17 * 1000**3 / 1024**3
314.0140324831009
```
borg's unit is GB (1000^3), linux tools use GiB (1024^3, advertised wrongly as GB).

**Comment by Thuffir** [comment]
Hehe. Thanks for clarification. Makes sense :)
