### ISSUE TITLE
Compression introduced by Encryption (documentation)

### ISSUE THREAD

**Issue by nobicycle** [borgbackup/borg#372]
I know that gpg significantly compresses a file when it encrypts. I just read the docs and was wondering if borgbackup encryption also introduces compression?  If so how does it compare with lz, zlib and lzma?

Thanks for the app.

**Comment by ThomasWaldmann** [comment]
encryption is unrelated to compression.

borgbackup uses AES encryption and that produces output exactly as long as the input.

but you can use `borg create --compression ...` to enable lz4, gzip or lzma compression.
from left to right, it compresses better, but also gets slower / more cpu intensive.

**Comment by nobicycle** [comment]
Thank you Thomas.
