### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory on Samba share

### ISSUE THREAD

**Issue by dhoeld** [borgbackup/borg#3728]
I'm not able to create a borg repo on my samba share:

**# borg init test -e none --debug**
```
using builtin fallback logging configuration
35 self tests completed in 0.11 seconds
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4175, in main
  File "borg/archiver.py", line 4107, in run
  File "borg/archiver.py", line 137, in wrapper
  File "borg/repository.py", line 179, in __enter__
  File "borg/repository.py", line 266, in create
  File "borg/repository.py", line 286, in save_config
  File "borg/platform/base.py", line 176, in __exit__
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/test/home/USERNAME/test/config.tmp' -> '/mnt/test/home/USERNAME/test/config'

Platform: Linux client 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64
Linux: debian stretch/sid 
Borg: 1.1.4  Python: CPython 3.5.4
PID: 7574  CWD: /mnt/test/home/USERNAME
sys.argv: ['borg', 'init', 'test', '-e', 'none', '--debug']
SSH_ORIGINAL_COMMAND: None
```

After issuing the borg init command the directory looks like this:

```
total 5
drwxrwxrwx 2 USERNAME USERNAME    0 Mar 26 09:42 ./
drwxr-xr-x 3 root   root   4096 Mar 23 14:06 ../
-rwxrwxrwx 1 USERNAME USERNAME  209 Mar 26 09:42 config.tmp*
drwxrwxrwx 2 USERNAME USERNAME    0 Mar 26 09:42 data/
-rwxrwxrwx 1 USERNAME USERNAME   73 Mar 26 09:42 README*
```

**# mount**
`//server/username/  on  /mnt/test/home/USERNAME            type  cifs             (rw,relatime,vers=default,cache=strict,username=USERNAME,domain=DOMAIN,uid=1000,forceuid,gid=1000,forcegid,addr=10.10.10.10,file_mode=0777,dir_mode=0777,nounix,serverino,mapposix,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)`

Any help/hint would be greatly appreciated!

**Comment by dhoeld** [comment]
Seems not to be an issue of borg backup --> close

**Comment by ThomasWaldmann** [comment]
so, what was it?

**Comment by dhoeld** [comment]
It seems there is something wrong with the mounted share. I'm able to create/modify/delete files and directories, but I'm not able to move files on the share.

I already asked my question here: [](https://askubuntu.com/questions/1019282/cant-move-files-on-cifs-mount-with-mv)

I
