### ISSUE TITLE
Files with modification date -1 not backed up

### ISSUE THREAD

**Issue by m1cm1c** [borgbackup/borg#3729]
I just noticed that some of the files I intended to back up do not occur in my backups. One thing I noticed is that I can't find any files whose modified date is `-1` (the timestamp in decimal notation is `-1`) in my backups, even though they exist in the locations I told borg to back up.

**Comment by ThomasWaldmann** [comment]
unix timestamps are unsigned ints, so how can it be "-1"?

please give the commands how to reproduce the problem and the borg version, python version, OS you use.

**Comment by m1cm1c** [comment]
To create such a file, simply issue this `touch` command:
```
$ touch --date="1970-01-01 00:59:59 +0100" someFile
```

You can get the modified date via `stat`:
```
$ stat someFile 
  File: 'someFile'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 805h/2053d	Inode: 394907      Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/christoph)   Gid: ( 1000/christoph)
Access: 1970-01-01 00:59:59.000000000 +0100
Modify: 1970-01-01 00:59:59.000000000 +0100
Change: 2018-03-27 00:26:35.480393771 +0200
 Birth: -
```

To get the timestamp, run it with `-c %Y`:
```
$ stat -c %Y someFile 
-1
```

I use borg version `1.0.11` with Python version `2.7.12` on Ubuntu 16.04 with kernel `4.4.0-116-generic`. I'm experiencing the problem with files in my home folder which is encrypted and uses ecryptfs. However, the output shown above was created outside my home folder directly on the underlying ext4 file system to make sure this isn't some peculiarity of ecryptfs.

**Comment by ThomasWaldmann** [comment]
Besides that such a datetime is before the beginning of UNIX time and thus invalid, I can't reproduce:
```
$ borg -V
borg 1.0.11
$ mkdir input
$ touch --date="1970-01-01 00:59:59 +0100" input/invalid_ts_file
$ borg create repo::arch input
$ borg list repo::arch
drwxr-xr-x tw     tw            0 Tue, 2018-03-27 00:57:40 input
-rw-r--r-- tw     tw            0 Thu, 1970-01-01 01:00:00 input/invalid_ts_file
```

**Comment by m1cm1c** [comment]
Unix timestamps are defined to be signed integers. This is how the year 2038 problem is a thing. It's defined to support dates from before the begin of the Unix epoch. I now checked the kernel wiki for whether the kernel hackers actually chose a signed integer for the modification date and they went with the definition:

> Four timestamps are recorded in the lower 128 bytes of the inode structure -- inode change time (ctime), access time (atime), data modification time (mtime), and deletion time (dtime). The four fields are 32-bit signed integers that represent seconds since the Unix epoch (1970-01-01 00:00:00 GMT), which means that the fields will overflow in January 2038.

Apart from the fact that the displayed data is wrong (which is explained by you apparently thinking that timestamps before the begin of the Unix epoch are invalid), the output looks fine. When I try to reproduce the problem like that, I get the same output. I'll close this issue for now and come back to it once I managed to write a script reproducing the bug.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.0.11/borg/helpers.py#L810

See the comments there. We had all sorts of issues with invalid timestamps blowing up something (e.g. python stdlib) before doing that. Also, for now, we want to be compatible to 32bit platforms.

**Comment by m1cm1c** [comment]
I'm leaving this comment for anyone experiencing the same problem.

After creating a new repository using the exact same command and using the exact same command for creating backups (got aliases for both), the phenomenon is just gone. The files show up in all revisions of the new repository I checked. Their modified timestamps are 0 instead of -1 as was to be expected given the code that was linked to above. Even `sha256sum * | sha256sum` in a directory with a whole bunch of these files prints the same value in the mounted backup and directly on my productive FS.

So if you experience the same problem, try deleting your repository and creating a new one.
