### ISSUE TITLE
Files not backed up if modified date left unchanged

### ISSUE THREAD

**Issue by m1cm1c** [borgbackup/borg#3730]
I wanted to revert a file to a previous version but the version I got was very old. The hashes of what borg claims was that file at different times are all the same. I suspect that this is because the modified date of that file wasn't changed.

**Comment by ThomasWaldmann** [comment]
borg (by default) looks at:
- borg 1.0.x: mtime, inode number, size
- borg 1.1.x: ctime, inode number, size

if you manage to change a file without changing at least one of these, borg will not detect that it needs to backup the file.

in 1.1 this should not be easily possible, as ctime can not be controlled from userspace.

in 1.0 this was possible by remembering the mtime, modifying the file (mtime moves forward) and then resetting the mtime to the remembered value. if you do (or some tool does) that, it is not borg's fault.

**Comment by ThomasWaldmann** [comment]
a workaround for borg 1.0.x is to disable the files cache using `--no-files-cache`.
the backup will be considerably slower then because borg will read/chunk/hash all the input files.

**Comment by m1cm1c** [comment]
It's definitely possible to detect such changes without reading all content because git manages to do it. This is a problem for people who use tools like TrueCrypt or its successors because it does not change the modified data of file containers by default. So there probably are a lot of people who might lose data this way, even though they thought it's backed up by borg.

**Comment by ThomasWaldmann** [comment]
Feel free to tell us how you think that should work (beyond what we already do, for a userspace non-daemon program), I'm curious. :)

If you use tools which cheat with mtime, you need either borg 1.1 or the workaround I told you.

And, as I said, that is not borg's problem. Guess what the "modification time" is intended to reflect.

If tools cheat with it, they (their authors) are responsible for the consequences (or at least for telling their users what consequences that might have and that their data needs special treatment).
