### ISSUE TITLE
mounted WebDAV folder doesn't work

### ISSUE THREAD

**Issue by bleda3** [borgbackup/borg#3746]
Hey there

I tried to make a backup routine with borg and WebDAV. So I connected and then mounted the WebDAV Folder into my system (one time through mount one time through owncloud) 
when I run` sudo borg init /home/user/ownCloud` 
it says 

> Repository /home/user/ownCloud already exists 

when I tried to make a work around through creating the backup folder locally and then moved it to the cloud it works the first time (with some error messages) but afterwards it says

> Failed to create/acquire the lock /mnt/dav/My Documents/Backup/lock.exclusive (timeout)

is it just not possible to make a backup routine on a server which only allows Port 80 because they most probably dont have borg installed or is there a solution?

Best regards

**Comment by ThomasWaldmann** [comment]
You only need borg init once for one specific repository.
You don't need to create a folder first, borg init will create the folder.

**Comment by ThomasWaldmann** [comment]
@bleda3 did you get it working?

If you can do the same thing locally, but not on webdav fs, it might be due to the webdav fs not working good enough.

**Comment by ThomasWaldmann** [comment]
no response.

**Comment by jonniewhite** [comment]
I got it working - but not with the root directory (where lost+found is), but by creating a subdirectory.

**Comment by ThomasWaldmann** [comment]
@jonniewhite interesting. so you had the same issue as @bleda3?

**Comment by jonniewhite** [comment]
That's correct. Initialising a repository in the root directory of a mounted webdav folder fails with `Repository ... already exists`. Note that there is a `lost+found` directory in the root directory. Initialising in a sub-directory works fine. I also get the problem that the 'lock.exclusive' is left in the repository directory even after a successful command, and therefore I have to do a `borg break-lock`. I'm using version 1.0.9 on Debian (WSL).
