### ISSUE TITLE
switch date/time format to iso style

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#375]
currently: american style
wanted: iso style, like 2015-12-31 23:59:59

e.g. in "info" command, maybe also at other places.

**Comment by level323** [comment]
I much prefer the ISO style, not least because the string sorts usefully

**Comment by ThomasWaldmann** [comment]
This is what's currently in the code:
```
def format_time(t):
    """Format datetime suitable for fixed length list output
    """
    if abs((datetime.now() - t).days) < 365:
        return t.strftime('%b %d %H:%M')    # AAA
    else:
        return t.strftime('%b %d  %Y')   # BBB
```
Output of these + iso format as CCC looks like:
```
drwxrwxr-x tw     tw            0 Oct 12 00:08 AAA
drwxrwxr-x tw     tw            0 Oct 12  2013 BBB
drwxrwxr-x tw     tw            0 2015-10-12 00:08 CCC
```
So, it needs 5 colums more space.
But is way easier to grep for as it is always formatted in the same easy way.
Shall we even add 3 more columns for the seconds?

**Comment by level323** [comment]
Yeah, add 3 columns for the seconds.

80 column terminals are soooo 1980's... ;-)

**Comment by FirefighterBlu3** [comment]
that makes the formatter simple, '%F %T'

**Comment by pszxzsd** [comment]
I don't think the seconds are useful information here and it's not worth breaking good old 80 column compatibility for that.

**Comment by ThomasWaldmann** [comment]
It's not like "iso-format-with-seconds" or "without" breaks 80 chars wide display, it would just leave less space for filenames as the current format (and that is true for both with-secs and without-secs).

**Comment by level323** [comment]
My original comment about 80 char wide display was my poor attempt at
humour - nothing more. Borg never did anything special to stay within 80
column wide output in the first place, AFAIK.

Sorry for any confusion.

**Comment by anarcat** [comment]
go with seconds, i would say.

**Comment by anarcat** [comment]
nanoseconds even, if available.
