### ISSUE TITLE
Borg mount encode error

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [borgbackup/borg#3750]
I'm running Borg 1.1.5 on my server. I have a windows clients which backs up on that server.
When I try to mount the repo with the windows backups, the mount command fails.

Here is its debug output:

`Mounting filesystem`
`handler raised <class 'UnicodeEncodeError'> exception ('ascii' codec can't encode character '\xe4' in position 11: ordinal not in range(128)), terminating main loop.`
`Local Exception`
`Traceback (most recent call last):`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/archiver.py", line 4253, in main`
`    exit_code = archiver.run(args)`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/archiver.py", line 4185, in run`
`    return set_ec(func(args))`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/archiver.py", line 1332, in do_mount`
`    return self._do_mount(args)`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/archiver.py", line 152, in wrapper`
`    return method(self, args, repository=repository, **kwargs)`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/archiver.py", line 1342, in _do_mount`
`    operations.mount(args.mountpoint, args.options, args.foreground)`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/fuse.py", line 309, in mount`
`    signal = fuse_main()`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/fuse.py", line 34, in fuse_main`
`    return llfuse.main(workers=1)`
`  File "src/fuse_api.pxi", line 348, in llfuse.main (src/llfuse.c:38990)`
`  File "src/handlers.pxi", line 436, in llfuse.fuse_opendir (src/llfuse.c:19138)`
`  File "src/handlers.pxi", line 437, in llfuse.fuse_opendir (src/llfuse.c:19060)`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/fuse.py", line 550, in opendir`
`    self._load_pending_archive(inode)`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/fuse.py", line 523, in _load_pending_archive`
`    self.process_archive(archive_name, [os.fsencode(archive_name)])`
`  File "/opt/borg-env/lib/python3.5/site-packages/borg/fuse.py", line 349, in process_archive`
`    path = os.fsencode(item.path)`
`  File "/opt/borg-env/lib/python3.5/os.py", line 860, in fsencode`
`    return filename.encode(encoding, errors)`
`UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 11: ordinal not in range(128)`

**Comment by ThomasWaldmann** [comment]
This is because borg thinks your filesystem encoding is pure ascii (and not e.g. `utf-8`). If your archive has filenames that are not pure ascii, you'll get an exception like seen above.

On Linux and other UNIX-like OSes, this is usually fixed by configuring the `locale` correctly, using e.g. `en_US.UTF-8` or so.

**Comment by ThomasWaldmann** [comment]
@Unkn0wn-MDCLXIV could you get it working now?

**Comment by ThomasWaldmann** [comment]
no response.
