### ISSUE TITLE
Extended attributes are not supported on this filesystem

### ISSUE THREAD

**Issue by mjbartholomew** [borgbackup/borg#3751]
I have a repository located on an ext4 filesystem (Raspbian), with the source data coming from an HFS+ volume (macOS Server). I am looking to move away from macOS from a server perspective and migrate my server shares to a computer running CentOS 7. The filesystem I intend to house my new shares on is XFS.

When I run `borg extract`, and tell it to extract the repository to my new XFS filesystem, I receive the following error messages for many of the files:

    Extended attributes are not supported on this filesystem

In some cases, the following error message also displays:

    Value or key of extended attribute com.apple.ResourceFork is too big for this filesystem

I know that XFS supports extended attributes, so what could be causing this issue?

**Comment by ThomasWaldmann** [comment]
what's the output of `mount` for the target filesystem?

**Comment by ThomasWaldmann** [comment]
@mjbartholomew ^

**Comment by ThomasWaldmann** [comment]
no response.
