### ISSUE TITLE
Backup to remote with different hostnames

### ISSUE THREAD

**Issue by reox** [borgbackup/borg#3762]
I backup to a remote server. I have a DNS entry for this server like remotelocation.example.com. If I'm at the remote location, it is not good to use this domain name, as the traffic is routed over the public router interface. Thus using the local DNS is prefered, like 192.168.0.42 or backupserver.local.
I adopted my backup script to check my location and adopt the server url accordingly.
But I get this warning:

```
Warning: The repository at location ssh://reox@192.168.0.42/srv/backup was previously located at ssh://reox@remotelocation.example.com/srv/backup
Do you want to continue? [yN]
```

I assume that nothing severe will happen, if I press yes. As far as I understand borg, the cache needs to be rebuild in this case, as the caches are created with the full path? At least the man page says something like
> This is because the file cache that is used to determine changed files quickly uses absolute filenames.

But I must admit, that I do not fully understand what the implications of this warning are.

I used `bup` before, and there a folder with the remote location was created locally. So I worked around the issue of multiple caches by softlinking one location to the other.
Can something like this be done for borg as well?

**Comment by ThomasWaldmann** [comment]
IIRC, the cache rebuild is not triggered by a changing repo location IF it is still the same repo.

You can auto-answer the security warning by an environment variable, see the docs. As long as you are sure you talk to the correct repo, it should not be a problem.

**Comment by reox** [comment]
okay thanks! For the record, the option here is `BORG_RELOCATED_REPO_ACCESS_IS_OK`.
