### ISSUE TITLE
Progress for other methods than 'create'

### ISSUE THREAD

**Issue by ho1ger** [borgbackup/borg#377]
I think a borg process is missing a generic way of showing that it is "alive and kicking" (and not "hanging" or waiting for an unreleased lock). When creating a new snapshot you have the --progress option, which is fine. I'd like to suggest to add something similar to other methods like "delete".

**Comment by ThomasWaldmann** [comment]
The locking issue will be addressed in 0.29, but yes, some other places could also use --progress.
Not sure about delete, that usually is rather fast.

**Comment by ho1ger** [comment]
I agree in general. But consider there are people (like me) that run borg on RaspberryPi-like machines and use a davfs as backup destination via ADSL. Then everything becomes pretty slow. So some kind of progress would be great. Even something like a spinning symbol (+ x + x ...) would be sufficient.

**Comment by ThomasWaldmann** [comment]
OK.

**Comment by ThomasWaldmann** [comment]
See #394.
