### ISSUE TITLE
multiple archives with same name?  What happens?

### ISSUE THREAD

**Issue by nealpalmer** [borgbackup/borg#3772]
The docs implied that you could create 2 archives with the same name (somewhere talking about intermediate checkpoints and restarting).

What happens to the first archive (assuming it completed), if you create another one with the same name?  Does it prune the old one?  Does it leave the old one, and now have 2 with the same name?  Does the old one stay and is inaccessible?

**Comment by jdchristensen** [comment]
You should just try it and see:

    $ borg init -e none testrepo
    $ echo hello > foo
    $ borg create testrepo::1 foo
    $ borg create testrepo::1 foo
    Archive 1 already exists

**Comment by ThomasWaldmann** [comment]
Can you give a link to WHERE the docs seem to imply that?

**Comment by ThomasWaldmann** [comment]
No reply, closing.
