### ISSUE TITLE
encrypt existing repository

### ISSUE THREAD

**Issue by Catscrash** [borgbackup/borg#3775]
Hi,

is there a way, to encrypt a repository after it existed for a while and was initiated with encryption=none?

Thanks!

**Comment by ThomasWaldmann** [comment]
No, sorry.

**Comment by bulletmark** [comment]
Can I ask why not?
```
pc:/backup borg key change-passphrase borg
This repository is not encrypted, cannot change the passphrase.
```

**Comment by bulletmark** [comment]
But the `change-passphrase` command has to re-encrypt everything anyhow doesn't it? So it would seem it is already an expensive operation. What's the difference between none->encrypted and encrypted->encrypted? The "untrusted server" is not relevant to the basic issue. E.g. I have not copied my repo backup to any other server yet but I want to add a pass-phrase now. So really, all I can do is blow the whole thing away?

**Comment by Catscrash** [comment]
Maybe it'd help if I show you my usecase:

I have non-encrypted repositories on a secure and trustworthy server. What I'm missing is a off-site backup for those repositories. I read about using rclone to backup the repository to backblaze.

I'm not willing to entrust my repository to backblaze unencrypted though.

So the threat model that you outlined above wouldn't apply here. 

Also there are already expensive operations like borg rewrite, where you can remove files, or change hashing (I think?). I'd be okay with it taking a few days.

**Comment by ThomasWaldmann** [comment]
@bulletmark change-passphrase ONLY changes the passphrase that protects the keys, but it does not change the encryption/authentication keys nor the random chunker seed (see also the docs). Because of that, it is a very quick operation, but it might not suit some use cases (see docs).

Changing the keys would require processing all data in the repository, quite expensive (and not implemented [yet]). Also it would need to be done in a safe way, so in case the conversion is interrupted, the repo and key material should be still in a usable state.

@Catscrash yes, your use case would be fine. You mean `borg recreate` and yes, that is rather expensive, too. It works on archive-level and therefore can't change encryption mode.

**Comment by sexybern** [comment]
> I have non-encrypted repositories on a secure and trustworthy server. What I'm missing is a off-site backup for those repositories. I read about using rclone to backup the repository to backblaze.

I use rclone to back up an unencrypted repository to wasabi using rclone's "crypt" method. You create a plain rclone target first, then create an "crypt" target on top if it. It encrypts the contents of the files and can optionally obscure or encrypt the file and directory names. It's not just useful for cloud backup services, you can use it on USB drives, file servers etc.

**Comment by OliverEvans96** [comment]
Is there a recommended manual approach for adding encryption right now? I would imagine it just looks like:
- Create a new archive with encryption
- Transfer archive from unencrypted repo to encrypted repo (Maybe option 1 from https://github.com/borgbackup/borg/issues/3867?)

**Comment by ThomasWaldmann** [comment]
You can only choose encryption mode when creating a new repo with `borg init`.

**Comment by rblenis** [comment]
How about this. Use fuse to iteratively mount each of the unencrypted backups, then back them up to a new repo with encryption.  This should be interrupt safe, as you can just restart the backup if interrupted and not worry about corrupting the original repo.  Then once it's all done, delete the original repo.
