### ISSUE TITLE
(re-)encrypt existing repo

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3781]
There are some valid usecases where users want to:

- encrypt a unencrypted repo (AND the unencrypted repo is assumed to be confidential / not exposed yet to prying eyes)
- re-encrypt / re-authenticate an existing encrypted repo with new key material

This needs a careful design to not leave the repo in a non-working state in case the operation gets interrupted while the repo is only partially processed. Also it would be nice to have some checkpointing, so an interruption does not mean having to start from the beginning.

Note: this is about re-encrypting an existing repo ("in place") and not about copying archives to another repo or something else.

**Comment by ss23** [comment]
There is also a use case for un-encrypting an encrypted repository, though I'd rate it lower priority.

**Comment by fcartegnie** [comment]
Since that won't be achieved without changing the whole repo, doesn't this feature belong to a more generic streamed export/import ? 
That would just be and internal stream format, and filters could be implemented to pass zfs send/receive, tar stdin/stdout, dumpe2fs/restorefs.

**Comment by ThomasWaldmann** [comment]
@Earnestly iirc we have a different issue about transferring archives to a new repo, see there.

**Comment by Earnestly** [comment]
That issue seems to be more a discussion of convenience with mind to "merging" rather than replication.  While this more convenience is often nice to have it doesn't seem necessary to solve this particular problem.

IMO being able to solve new problems with existing tooling is preferable to requiring the tools themselves handle each case explicitly.  Anything else is just optimisation (which is nice to have too).

**Comment by ThomasWaldmann** [comment]
@Earnestly move your comments elsewhere, please. Preferably, find a matching already existing ticket or open a new one.

THIS ticket is about re-encrypting an existing repo ("in place") and not about copying archives to another repo or something else.

**Comment by Earnestly** [comment]
Ah, sorry about the noise then.  Feel free to delete these comments.

**Comment by ThomasWaldmann** [comment]
This is a rather old ticket, but there are news in borg2 fundamentally changing the situation:

Previously (as in 2018-2021 and with borg 1.x), there was no really good way to transfer archives (there were some workarounds, but everything was rather inefficient, slow or lossy [esp. considering metadata]).

In borg2 (master branch, betas), we now have `borg transfer`, which can actually now do what @Earnestly suggested in a rather efficient (deduplicating) and all-preserving way.

So, @Earnestly was right, just ahead of what was possible back then. Closing this as "can be solved by borg transfer".
