### ISSUE TITLE
borg check gives no output

### ISSUE THREAD

**Issue by 0x72** [borgbackup/borg#3785]
```sh
$ borg info --show-version backups
borgbackup version 1.1.5
Repository ID: 11a0d...
Location: /run/media/0x72/backups
Encrypted: Yes (repokey BLAKE2b)
```

`borg check` gives no output, works quietly for a couple of minutes (repo size is 150GB) and exits with code 0:

```bash
$ borg check -v -p backups
$ echo $?
0
```

Since there is no output at all, even with the verbose or progress option set, I struggle to find the cause of this behaviour. I would expect some kind of output that tells me what borg is doing at the moment or at least give me a report after a completed check.

**Comment by ThomasWaldmann** [comment]
Strange, I get this:
```
heck complete, no problems found.
$ borg -V
borg 1.1.5

$ borg check -v -p repo
Starting repository check
Starting repository index check                                                 
Completed repository check, no problems found.
Starting archive consistency check...
Enter passphrase for key ......./repo: 
Analyzing archive arch (1/2)
Analyzing archive arch2 (2/2)
Archive consistency check complete, no problems found.
```

**Comment by ThomasWaldmann** [comment]
what does this output on your machine?
```
which borg
ls -l `which borg`
file `which borg`
```

**Comment by 0x72** [comment]
Yes, this is the output I expected! I am using borg on Arch Linux.

```
$ which borg
/usr/bin/borg
$ ls -l `which borg`
-rwxr-xr-x 1 root root 384 Apr  4 20:30 /usr/bin/borg
$ file `which borg`
/usr/bin/borg: Python script, ASCII text executable
```

**Comment by ThomasWaldmann** [comment]
Try to reproduce it again and if you can, check your environment variables, esp. the stuff starting with BORG_. Is there anything special?

**Comment by ThomasWaldmann** [comment]
No reply, can't reproduce, closing.

**Comment by openeggbert** [comment]
Hello, I had the same problem. "borg check {repo url}" gave me no output.
Adding --progress solved my issue. Borg check now returns output.
I don't know, if this would help user marcelmindemann.

**Comment by robertvokac** [comment]
Hello, I had the same problem. "borg check {repo url}" gave me no output.
Adding --progress solved my issue. Borg check now returns output.
I don't know, if this would help user marcelmindemann.

**Comment by ThomasWaldmann** [comment]
@robertvokac if you could reproduce the original issue, please add the borg version(s) and the full borg command to your post.

**Comment by StrategiosP** [comment]
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY
I AM ILLITERATE MORON WHO DOES NOT DESERVE TO LIVE
PLEASE KILL ME IN MOST PAINFULL WAY

**Comment by ThomasWaldmann** [comment]
@StrategiosP The top post is about not getting output although they were using `-v`.

When not using `-v`, borg would only output warnings and errors and otherwise stay silent (which is quite the usual way how tools on unix work).

rc = 0 means it was successful.

**Comment by StrategiosP** [comment]
Sorry to have wasted everyones time. I am an illiterate moron and will kill myself now.
