### ISSUE TITLE
Manifest rebuilding does not report progress (even with -p option on).

### ISSUE THREAD

**Issue by Progratron** [borgbackup/borg#3787]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

## Describe the problem you're observing.

I have quite a large backup (400GB) where the manifest is missing. I am waiting on:
```
$ borg -p -v check --repair backup
...
Rebuilding missing manifest, this might take some time...
```
for more than 100 hours now and no progress is being reported. Seems that borg does not report progress for manifest rebuilding even though the -p option has been turned on.

**Comment by ThomasWaldmann** [comment]
There is a bit of progress reporting: `logger.info('Found archive %s', name)`

But that only happens IF/WHEN it finds some archive and can be rare (if you only have few / large archives).
