### ISSUE TITLE
Prune archives with no data change in between

### ISSUE THREAD

**Issue by ShadowRylander** [borgbackup/borg#3800]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes; however, don't know the right terminology.

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### How much data is handled by borg? `--> A few tens of gigabytes.`

***

Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I was just wondering how to prune archives where there's no difference in data in between, i.e. several backups run back-to-back, but no files were changed. I'd like to delete all but the first of the archive copies, if possible; I'd gone through the `FAQ` and the `docs`, but didn't find anything similar to my situation, as they were all time-based, and I am unsure of the terminology I should use to find such a situation.
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the help!

**Comment by ThomasWaldmann** [comment]
If you use prune with the keep-daily rule, it will keep the last backup on each day.

Or in general: keep-INTERVAL will keep the last backup in INTERVAL.

**Comment by ShadowRylander** [comment]
True; however, can we not prune according to data contained within the archive? Such as, for example, `keep-daily, keep-same-data`?

**Comment by ThomasWaldmann** [comment]
borg as a normal non-daemon userspace program has no means to monitor your filesystem, so it can not know beforehands whether the data has changed or not.

And even if one would use other tools to make a list of changed files, it would not benefit borg as it always makes full backups and does not cache all metadata it needs to create the archive, so it would still have to look at a file's metadata (stat, xattr, acls) even if the file contents and the metadata did not change.

There is borg diff to compare archives, but there is no builtin mechanism to use that for pruning purposes.

**Comment by ThomasWaldmann** [comment]
BTW, if you keep all the logs from `borg create --list --filter=AME`, you can maybe make something based on their content.

**Comment by ShadowRylander** [comment]
Alright, then; thanks for everything! I'll close the thread, then.
