### ISSUE TITLE
Cannot configure a remote keyfile repository

### ISSUE THREAD

**Issue by vphantom** [borgbackup/borg#3802]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

More of an impossibility, not a bug per se.

## Describe the problem you're observing.

I created a remote repository with a local key:

```sh
borg init --remote-path=borg1 --encryption=keyfile userid@hostname:borg-repo-name
```

I cannot use `borg config` on that repository because it is remote:
```text
borg config --remote-path=borg1 userid@hostname:borg-repo-name additional_free_space 2G
[...usage...]
borg config: error: argument REPOSITORY: "userid@hostname:borg-repo-name": Repository must be local
```

I also cannot use `borg config` remotely either because Borg thinks it requires a key to do so (which it doesn't actually, as the config file is in clear text):
```text
$ ssh userid@hostname borg1 config borg-repo-name additional_free_space 2G
No key file for repository /data2/home/userid/borg-repo-name found in /data2/home/userid/.config/borg/keys.
```

My recourse will be to download the file, modify it manually and upload it back.  Ideally, one of the two methods above should be made to work.

**Comment by ThomasWaldmann** [comment]
Hmm, that is strange. The last command should be made working.
