### ISSUE TITLE
Don't require any of the --keep-* options for borg prune

### ISSUE THREAD

**Issue by realityexists** [borgbackup/borg#3811]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Enhancement request

## Describe the problem you're observing

I want to prune all archives with a particular prefix, but borg currently forces me to specify one of the --keep options.

#### Can you reproduce the problem? Yes:
```
borg prune --dry-run -P test PATH_TO_REPO
```

#### Include any warning/errors/backtraces from the system logs
```
At least one of the "keep-within", "keep-last", "keep-secondly", "keep-minutely", "keep-hourly", "keep-daily", "keep-weekly", "keep-monthly" or "keep-yearly" settings must be specified.
```

Additionally, this error is only displayed after entering the repository password, which is annoying.

**Comment by ThomasWaldmann** [comment]
Prune is made for implementing a time-based policy.

Guess what you want is rather `borg delete repo` with either `-P` or `-a` maybe?

**Comment by realityexists** [comment]
Possibly, but from the documentation it was not crystal clear to me what that would delete:

> This command deletes an archive from the repository or the complete repository.

So it sounds like if ARCHIVE is not specified then the entire repository might get deleted. Now, `-P` might affect that, but without a `--dry-run` option available, I sure as hell wasn't going to try it on my real repo when `prune` basically does what I want.

I've always found the distinction between `prune` and `delete` confusing, to be honest.

I even tried `--keep-last 0`, but that's not accepted. `--keep-within 1H` works (if the archive to delete was created over an hour ago).

**Comment by ThomasWaldmann** [comment]
OK, so guess we need:
- clarify docs
- update docs with some useful examples for multi-archive deletion
- add --dry-run for borg delete

**Comment by realityexists** [comment]
Yes, those would all be helpful, but why not allow prune without `--keep-*` as well? Or at least allow `--keep-last 0` if you want to make sure the user didn't forget an option.

And finally, such errors should be displayed before prompting for the repo password.

**Comment by jdchristensen** [comment]
I think it's a very rare situation in which someone wants to delete all archives with a certain prefix.  On the other hand, someone could easily accidentally call prune without an option, or with an option that causes all archives to be deleted, and I think we should make it hard for that mistake to happen.  People are constantly misunderstanding the prune options, so this will definitely happen.

I think `borg delete -P ...` already does what you want, and there it's less likely that someone will mistakenly delete archives they didn't intend to.

**Comment by realityexists** [comment]
Well, OK, if `delete -P` does what I want, I'm happy to use it... once it has `--dry-run`, so I can tell what it's about to delete.

**Comment by ThomasWaldmann** [comment]
I added #3821 and #3822, so this one can be closed.
