### ISSUE TITLE
borg mount -o versions

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#3815]
Something is wrong with mount with `versions` option:

```
borg -V
borg 1.1.5

borg mount remote@server:borg/repo /path/backup.mnt -o versions,allow_other
```
After that it stays silent for infinit.

`strace` shows "wait4(-1," at the end and nothing happens after.

If I do 
```
borg mount remote@server:borg/repo /path/backup.mnt -o versions -o allow_other
```
then mount is working but without any versions.

**Comment by ThomasWaldmann** [comment]
If you do a versions mount for the whole repo without restricting the processed archives, it will have to process all archives to mix them together into the versions view filesystem. If you have many and/or big archives, this may take a while.

OTOH, if you mount the whole repo using the normal view (not the versions view), it will only create the toplevel directories with the archive names and will lazy-load each archive when you dive into the respective toplevel directory. So the mount is much quicker in this case if you have many and/or big archives.

**Comment by ThomasWaldmann** [comment]
Not sure this is a bug. Can you try:
- locally, with same repo
- locally, with smaller repo
- remote, with smaller repo

**Comment by knutov** [comment]
ok, small repo over local network:

`mount bak@server:borg/test ./backup.mnt -o versions -o allow_other`

mounts fast, but without any versions.

`mount bak@server:borg/test ./backup.mnt -o versions,allow_other`

result is: "mount: unknown filesystem type 'nfs'"

`mount bak@server:borg/test ./backup.mnt -o allow_other -o versions`

same error,

even 

`mount bak@server:borg/test ./backup.mnt -o versions` resulting the same error.

What I'm doing wrong?

**Comment by ThomasWaldmann** [comment]
Try `borg mount -o versions repo mountpoint`.

**Comment by knutov** [comment]
oh, my mistake, last commands was run without borg, just `mount ...`.

so, `borg mount bak@server:borg/test ./backup.mnt -o versions,allow_other` is working, and `borg mount  -o versions,allow_other bak@server:borg/test ./backup.mnt` too.

And `... -o versions -o allow_other ...` never works as expected 

Big repo over local gigabit network mounts infinitely and bottleneck is local cpu (100% of one core), not network (from 300 Kbit/s to 2.5 Mbit/s) or disks.

**Comment by knutov** [comment]
upd: 

real	8m4.787s
user	7m48.156s

repo size is 28G deduplicated with zstd compression. 

I'll run more tests tomorrow.

**Comment by ThomasWaldmann** [comment]
Any news?

**Comment by knutov** [comment]
sorry, did not finished yet good testing .

Sometimes mounting takes minutes. It's bad, but acceptable.
Sometimes it takes infinit time, so it is not mounting at all after few hours. 

I want to write script for periodic testing but still did not find time for this.

**Comment by ThomasWaldmann** [comment]
closing this for now. reopen if there are any news.
