### ISSUE TITLE
Remove "Compacting Segments" from log

### ISSUE THREAD

**Issue by reox** [borgbackup/borg#3816]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

client
borg 1.0.9

remote server
borg 1.1.5

#### Operating system (distribution) and version.

debian stretch

#### Hardware / network configuration, and filesystems used.

Intel(R) Xeon(R) CPU E31245 @ 3.30GHz
ext4
backup to remote location

#### How much data is handled by borg?

~100GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
sudo borg create \
	--stats \
	--verbose \
	--show-rc \
	foo@example.com:/some/path/to/borg::'{hostname}-{now}' \
	/etc \
	/home 1>/dev/null
```

## Describe the problem you're observing.

I run borg backup in a cronjob. I like to receive the output of `borg create` and `borg prune` as a mail, so I do not throw away the output.
But In the mail I get a lot lines like
```
borg.output.progress Remote: Compacting segments  xx%
```
and I really do not care about them.
Probably it is the easiest to pipe the command through `grep -v 'Compacting segments'` but I wonder if there is a method to do this with borg already?
According to https://borgbackup.readthedocs.io/en/stable/usage/general.html#logging only log messages should be on stderr, so I wonder why the compacting segments is a log message?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

yes, every time.

**Comment by ThomasWaldmann** [comment]
IIRC this was fixed in 1.1 (if you use it on both sides, client and server).
