### ISSUE TITLE
__builtin_bswap32 referenced symbol not found

### ISSUE THREAD

**Issue by gco** [borgbackup/borg#3818]
The latest borg git repo refers to the __builtin_bswap32 symbol when built on Big Endian architectures without using gcc.  (Solaris 10, Sun's compiler).
```
% borg
Traceback (most recent call last):
  File "...python/borg-env/bin/borg", line 7, in <module>
    from borg.archiver import main
  File "...python/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 36, in <module>
    from . import helpers
  File ".../borg-env/lib/python3.6/site-packages/borg/helpers.py", line 44, in <module>
    from . import hashindex
ImportError: ld.so.1: python3.6: fatal: relocation error:
    file .../python/borg-env/lib/python3.6/site-packages/borg/hashindex.cpython-36m.so:
    symbol __builtin_bswap32: referenced symbol not found
```

The macros in src/borg/_endian.h are to blame.

**Comment by gco** [comment]
It's not Solaris- or SPARC-specific.  The same thing happens on any big-endian machines.  You're not testing on IBM z/Architecture? :-)

The usual code looks something like what the simple-minded implementation of `ntohl` looks like on little-endian machines:

`x = ((y>>24)&0xff) | ((y<<8)&0xff0000) | ((y>>8)&0xff00) | ((y<<24)&0xff000000);`

**Comment by ThomasWaldmann** [comment]
I am running a check on (big endian) powerpc debian linux right now (with gcc). But I expect it to work and you said yourself (see top post) that it happens without gcc when using Sun's compiler. So it isn't that far fetched that the code needs to be adapted for that compiler (which is only used on Solaris AFAIK).

**Comment by gco** [comment]
The issue isn't with Sun's compiler, it's the code that relies on a very _specific_ compiler.   Use portable byte-swapping code and it'll work with _any_ compiler.

**Comment by ThomasWaldmann** [comment]
OK, but fixing the issue still needs someone with a platform and compiler who can test the non-gcc code that has to be added.

**Comment by despair86** [comment]
hmm
SPARCWorks 12.6 implements some of those GCC intrinsic functions, I'd have to look at the docs again to verify whether or not it has `__builtin_bswap32()`.

On the other hand, `__builtin_c[tl]z()` do NOT exist there, and I have to patch those inline myself.

**Comment by despair86** [comment]
most of them are unimplemented even now, see https://docs.oracle.com/cd/E77782_01/html/E77792/gqexw.html#OSGCCgqexp and `/opt/SUNWspro/lib/compilers/include/CC/gnu/builtins*.h` (or, wherever you installed to...`/opt/*/lib/compilers/include/CC/gnu/builtins*.h`

if it has no inline definitions in those files (`builtins.h`, `builtins-def.h`) then it doesn't exist at all (yet, if ever)

**Comment by ThomasWaldmann** [comment]
@despair86 thanks for checking this.

can you add and test some working code to deal with that (see other comments)?

**Comment by despair86** [comment]
oh right
the only reason it works in openindiana is because their SFW-gate CBE (common build env) uses GCC 6.5

**Comment by ThomasWaldmann** [comment]
Is this still an issue with current borg code? 1.2-maint or master branch.

**Comment by ThomasWaldmann** [comment]
If somebody finds this is still a problem with current versions, please reopen.
