### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u011f' 

### ISSUE THREAD

**Issue by ovizii** [borgbackup/borg#382]
Hi there,

I am taking my first baby steps. I installed borg on 2 different debian machines, both running Jessie.
Made a backup from one to the other.
tried restoring the backup on the target machine.

    root@alfred:~/borg extract /root/stratobckp/::07.11.2015
    Warning: File system encoding is "ascii", extracting non-ascii filenames will not be supported.
    borg: Error: Local Exception.
    Traceback (most recent call last):
      File "/vagrant/borg/borg/borg/archiver.py", line 1030, in main
      File "/vagrant/borg/borg/borg/archiver.py", line 986, in run
      File "/vagrant/borg/borg/borg/archiver.py", line 283, in do_extract
      File "/vagrant/borg/borg/borg/archive.py", line 312, in extract_item
    UnicodeEncodeError: 'ascii' codec can't encode character '\u011f' in position 34: ordinal not in range(128)
    borg: Exiting with failure status due to previous errors

**File system encoding is "ascii", extracting non-ascii filenames will not be supported**
**Now what? **

any pointers please?

**Comment by ThomasWaldmann** [comment]
```
if sys.getfilesystemencoding() == 'ascii':
            logger.warning('Warning: File system encoding is "ascii", extracting non-ascii filenames will not be supported.')
```
This is the code. I haven't seen the warning yet on my machines / test setups.

**Comment by ovizii** [comment]
sorry, I'm not a coder. just wanted to report it. 
will do further tests, this was jsut a silly test, backing up from A => B then trying to restore on B

**Comment by ThomasWaldmann** [comment]
Guess the short version of that is "your locale setup is wrong".

**Comment by ThomasWaldmann** [comment]
Can you try if that helps?:
```
LANG=en_US.UTF-8
```

**Comment by ovizii** [comment]
ah, yes, that is fixed then. 
I had meanwhile realized my locales where misconfigured and fixed them. 
didn't realize these 2 issues were connected.

Thanks!

**Comment by ThomasWaldmann** [comment]
guess I'll either put that into faq or improve that not-that-much helping error msg.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/5595d56ecf26678e36dca4ec6e7c128c7ab7325d

Hah, you found a missing exception handler! :)

**Comment by ovizii** [comment]
:-) trust me to do that. I'm excellent at finding the most obscure constellations, its like Murphy is my middle name.
