### ISSUE TITLE
deduplicated archive bigger than source

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#383]
borg create  -s -p -v -C lzma,9 repo.borg::backupset source

Start time: Wed Nov  4 06:21:18 2015
End time: Sat Nov  7 20:56:20 2015
Duration: 3 days 14 hours 35 minutes 1.63 seconds
Number of files: 10

                       Original size      Compressed size    Deduplicated size
This archive:              225.65 GB            225.96 GB            225.96 GB
All archives:              225.65 GB            225.96 GB            225.96 GB

                       Unique chunks         Total chunks
Chunk index:                 3390929              3390929
-----------------------------------------------------------------------------
Filesystem shows for source (225.500.871.191 Bytes) and for repo.borg (226.355.757.056 Bytes)
, plus 854.885.865 Byte or 815,3 MB

Q1
I assume the the compression algorithm switch to "store only" as soon the result of the compression is not smaller then the source
Q2
The overhead of about 252 byte/chunk is ok and the total number of chunks can be reduced by setting different chunker-params ?

**Comment by ThomasWaldmann** [comment]
A1: no, it does not (at least not in the borg code, not sure about what lzma does internally).

A2: yes

What kind of data was that? video?

**Comment by ClipperS87** [comment]
3 VMWare .vmdk files in preallocated format

**Comment by ThomasWaldmann** [comment]
@ClipperS87 that's unexpected then, i would expect quite some compression.

can you try lz4, zlib and lzma with default level, just:
```
borg create --compression lz4
borg create --compression zlib
borg create --compression lzma
```
lzma,9 is quite resource-intensive stuff, maybe it had a problem with getting these resources and fell back to not compressing?

**Comment by ClipperS87** [comment]
other threads on the same machine did fine (as expected) so the file seem simply not to be compressed - i tried with latest .rar and maximum settings - similar results

**Comment by ThomasWaldmann** [comment]
OK, seems like .vmdk might be already compressed. So further compression is unexpected.
