### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gumida** [borgbackup/borg#3850]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Not sure

#### Your borg version (borg -V).
1.1.5

#### Operating system (distribution) and version.
Debian 9

#### Hardware / network configuration, and filesystems used.
Older hardware; local copyjob w/o network; ext4

#### How much data is handled by borg?
e.g. 3,5 TB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
Copied from Quick start:
`borg create                         \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
                                    \
    ::'{hostname}-{now}'            \
    /media                          \`

## Describe the problem you're observing.
Unknown borg output on console/log file when finishing backup. Couldn't find anything like this:

> [...]
> A /media/...
> A /media/tmp/files
> 	: [Errno 2] No such file or directory: '\t'
> 
> Archive name: server-2018-05-20T23:03:50

I thought, maybe a "bad" file name could be the reason for this. So I searched for file/folder names with backslashes in it and excluded them -> error message is still the same.
Is this relevant?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes

**Comment by ThomasWaldmann** [comment]
`\t` means a `TAB` char.

Check your command line: it looks like that final backslash is not really needed.

**Comment by ThomasWaldmann** [comment]
I could reproduce the issue:
```
$ . tabtest.sh 
	: [Errno 2] No such file or directory: '\t'

```
tabtest.sh contains a backslash followed by a tab char:
![screenshot from 2018-05-21 18-14-10](https://user-images.githubusercontent.com/356103/40317828-f23bee38-5d22-11e8-9ce8-c8b52930ad03.png)

**Comment by ThomasWaldmann** [comment]
Also, I was able to actually create a file that only has a tab char as name.

So, while that is a bit unusual, it seems possible. So, this is not a bug in borg.
