### ISSUE TITLE
Borg extract command is not working

### ISSUE THREAD

**Issue by Philippe34** [borgbackup/borg#3865]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
```
# borg -V
borg 1.1.5
```

I use the standalone binary borg-linux64 that I copied in /usr/local/bin/borg

#### Operating system (distribution) and version.
```
# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```
#### Hardware / network configuration, and filesystems used.
I use borg to backup directory in xfs filesystem

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
I use for the first time borg to test and I followed the quick start 
- borg init in local repository : borg init --encryption=repokey /backup/borg/
- borg create --stats /backup/borg::{hostname}_{now} /travail /var/www
- borg list /backup/borg
I can also mount an archive with borgfs

## Describe the problem you're observing.
borg extract command is doing nothing

```
#borg list /backup/borg::backup_2018-05-29T16:39:52 |grep borg
Enter passphrase for key /backup/borg:
drwxr-xr-x root   root          0 Tue, 2018-05-29 16:37:35 travail/borg
-rwxr-xr-x root   root         23 Tue, 2018-05-29 16:37:35 travail/borg/testfile.txt
-rw-r--r-- root   root        179 Mon, 2018-05-28 17:35:26 travail/borg/Makefile
```
You can see the backuped file testfile.txt. Now I delete the original file
```
# rm /travail/borg/testfile.txt
# ls /travail/borg/
Makefile
```
i want to restore this file 
```
# borg extract /backup/borg::backup_2018-05-29T16:39:52 travail/borg/testfile.txt
Enter passphrase for key /backup/borg:

# ls /travail/borg
Makefile
```
The file has not been extracted

To restore files, I have to mount the archive and copy the file.

Does borg extract command work in 1.1.15?

**Comment by Philippe34** [comment]
Hi,
I deleted the borg binary 1.1.5 to install borg-linux64 1.1.4.
````
# borg -V
borg 1.1.4
````
Now I retry a borg extract command 
````
#borg extract /backup/borg::joran.ies.univ-montp2.fr_2018-05-29T16:39:52 travail/borg/testfile.txt
````
It is working, but not the way I should expect
````
]# tree /travail/borg
/travail/borg
├── Makefile
└── travail
    └── borg
        └── testfile.txt

2 directories, 2 files
````
i would like : 
````
# tree borg.orig
borg.orig
├── Makefile
└── testfile.txt

0 directories, 2 files
````
Why the backup with 1.1.4 is not given me the right path ?
It seems to have a bug with 1.1.5

Best regards

**Comment by ThomasWaldmann** [comment]
This is not a bug, borg always extracts files into the current directory.

If you want extracted pathes to start from `/`, then `cd /` first.

**Comment by Philippe34** [comment]
Hi ThomasWaldmann ,

Thank you for your help for the importance of the path when we execue borg extract.
But please, consider that borg extract does not work at all with 1.1.5.

Regards

**Comment by ThomasWaldmann** [comment]
Please give me an example script that shows it does not work at all (and that considers that it always uses relative-to-current-dir extraction).

**Comment by Philippe34** [comment]
Sorry. borg extract works, but I did not see the result because of my wrong path.
Borg seems to be very great ! I have to test with remote repository now.

Thanks a lot

**Comment by ThomasWaldmann** [comment]
You're welcome!
