### ISSUE TITLE
borg check crashes with Input/Output error

### ISSUE THREAD

**Issue by fantasya-pbem** [borgbackup/borg#3874]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes. But this error is specific to the repo storage (WebDAV) I use.

## Is this a BUG / ISSUE report or a QUESTION?
ISSUE

#### Your borg version (borg -V).
borg 1.1.5

#### Operating system (distribution) and version.
Debian GNU/Linux 9

#### Hardware / network configuration, and filesystems used.

Intel(R) Xeon(R) CPU E5-2670 v3
KVM, 2 dedicated cores
MemTotal: 8179528 kB
1000 MBit network interface

Repo storage is "1&1 Online-Speicher" (https://www.1und1.de/sd2) mounted via davfs2, which has worked quite well over the last years. Borg repo is a subfolder in this storage and symlinked to /srv/borg.

#### How much data is handled by borg?
Utilization of max. archive size: 0%
Original size / Compressed size / Deduplicated size
All archives: 1.18 TB / 1.08 TB / 80.23 GB
Unique chunks / Total chunks
Chunk index: 166097 / 1500681

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg check -v /srv/borg

## Describe the problem you're observing.

Borg check crashes with Local Exception "KeyError: 30" followed by "During handling of the above exception, another exception occurred: OSError.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Just do "borg check /srv/ borg". I think davfs2 created some defect files some time ago when "borg create" was running. Now every "borg check" crashes with the same errors and has no chance to fix the broken files.

**Maybe it would be possible to catch these type of exception and delete the defect repo parts?**

#### Include any warning/errors/backtraces from the system logs

```
borg check --debug --repair /srv/borg
using builtin fallback logging configuration
35 self tests completed in 0.18 seconds
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
Verified integrity of /srv/borg/index.344
Read committed index of transaction 344
Cleaned up 0 uncommitted segment files (== everything after segment 344).
Segment transaction is    344
Determined transaction is 344
Found 282 segments
Local Exception
Traceback (most recent call last):
  File "borg/repository.py", line 1266, in get_fd
  File "borg/lrucache.py", line 21, in __getitem__
KeyError: 30

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 4253, in main
  File "borg/archiver.py", line 4185, in run
  File "borg/archiver.py", line 152, in wrapper
  File "borg/archiver.py", line 306, in do_check
  File "borg/repository.py", line 911, in check
  File "borg/repository.py", line 1311, in iter_objects
  File "borg/repository.py", line 1268, in get_fd
OSError: [Errno 5] Input/output error: '/srv/borg/data/0/30'

Platform: Linux v22018041585863736 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
Linux: debian 9.4 
Borg: 1.1.5  Python: CPython 3.5.5
PID: 25487  CWD: /media/1und1/borg/v22018041585863736
sys.argv: ['borg', 'check', '--debug', '--repair', '/srv/borg']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
That means borg tried to get the file handle for segment 30 from the LRU cache, but it was not there.
This is not an error yet, but normal behaviour of an LRU cache.

The handler of that exception then tries to reopen segment file 30 (to get a file handle for it) and your filesystem says I/O error instead of opening the file.

So, I'ld suspect that either the fs is buggy or there is no connection or ...

**Comment by ThomasWaldmann** [comment]
Can you find out more about segment file 30?
It should be in `repo_dir/data/0/30` - is it there?
Anything special about it you do not see for the other segment files?

**Comment by fantasya-pbem** [comment]
Segment file 30 is present. It looks like all other files (owner, size, ...), and I successfully made a copy:
```
cp /srv/borg/data/0/30 /tmp/
mv /srv/borg/data/0/30 /srv/borg/data/0/30.error
mv /tmp/30 /srv/borg/data/0/
```
But then, doing a "borg check" results in the same errors.

What's special about segment file 30: It is one of those from the very first backup. That backup ran successfully 14 days ago, no error output. It is a new repo made with same borg version.

**Comment by ThomasWaldmann** [comment]
Strange, because borg doesn't do anything else than trying to open that file here.

Do you always use same user / check permissions?

Does it maybe not cope with the load, if there are a lot of file ops per second?

**Comment by fantasya-pbem** [comment]
On that repo I never checked successfully. I use BorgBackup for some years now with this WebDAV storage, most of the time working smoothly. With the latest versions (>= 1.1) I feel that problems are getting more.

It may have a connection with too much load on the WebDAV side.

But: Could BorgBackup catch that error and skip the segment file / delete it, if it seems to be there (file exists) but has errors when trying to read? I wonder why BorgBackup has to crash on I/O error.
And: It's bad that borg create ran successfully and didn't notice the file error – I guess WebDAV didn't notice too... So it would be great if BorgBackup could take that bad segment file out.

**Comment by fantasya-pbem** [comment]
I have done more tests and think it depends on the amount of data per "borg create" if the repo gets corrupted or not. A fresh "borg init" followed by "borg create" with many Gigabytes of files results in nearly the same IOError in segment file 30 or 34.
But creating backups of smaller amounts of files works fine, "borg check" runs without errors then.

I did not get this error before simply because I did not do big backups over WebDAV. So I think we can close this issue.

**Comment by ThomasWaldmann** [comment]
Hmm, do you have a problem with the amount of open files?

**Comment by fantasya-pbem** [comment]
I don't think so. By "many GB of files" I mean several hundreds of big files. I consulted the BorgBackup docs and there is nothing written about amount of open files, so I assume no problem here.
I currently run some tests to find the bottleneck. Will report my findings, if any.

**Comment by ThomasWaldmann** [comment]
I meant the amount of open repository files.

**Comment by fantasya-pbem** [comment]
In the end it's plain simple: davfs uses /var/cache/davfs for caching files. My /var partition has 13 GB free space left. When "borg check" is running, it fills the cache with segment files and finally runs out of space if BorgBackup repository is bigger than cache space...

When "borg create" runs, there is only one segment file open at a time it seems, and the davfs cache is fine.
Question: Why does a "borg check" keep all segment files open? Is this normal behaviour? Can it be changed?

**Comment by fantasya-pbem** [comment]
So, if the LRU cache had a capacity of 10, my davfs cache would at most have 10 open segment files I guess. Do you think a LRU cache capacity parameter is a candidate for a repo config setting, a "borg check" option or a borg env variable?

**Comment by ThomasWaldmann** [comment]
Maybe an env var, because it doesn't depend on the machine the repo resides on or on the repo itself, but rather on how you access it and on the limitations of that.

OTOH, a fs that has troubles with opening 90 files (max.) maybe just isn't the right thing.

**Comment by ThomasWaldmann** [comment]
If you do a install from source, you could try lowering the lru cache parameter and retry.

Whether that helps or not could also depend on how davfs is doing the caching. If your fs fills up, it might be that not only open files are there, but also stuff that was opened recently (but is not open any more).

As this is not a borg issue, but rather davfs, I am closing this - if you find out more, add it below or reopen.

**Comment by ThomasWaldmann** [comment]
You shouldn't use borg 1.1.5 nowadays - if it was not patched, it has known, severe bugs.

See the maintainer ppa for a more recent borg for ubuntu.
