### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'items' in src/borg/item.pyx", line 60

### ISSUE THREAD

**Issue by barrio** [borgbackup/borg#3876]
I'm getting this exception when trying to restore a root backup from external hdd, no matter wether I use pip or github install. 
```
sudo borg extract -p /run/media/barrios/TOSHIBA\ EXT/vaio-manjaro-backup::root-2018-06-07
Calculating size
Local Exception
Traceback (most recent call last):
  File "/home/barrios/apps/borg/src/borg/archiver.py", line 4101, in main
    exit_code = archiver.run(args)
  File "/home/barrios/apps/borg/src/borg/archiver.py", line 4033, in run
    return set_ec(func(args))
  File "/home/barrios/apps/borg/src/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/barrios/apps/borg/src/borg/archiver.py", line 165, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/home/barrios/apps/borg/src/borg/archiver.py", line 708, in do_extract
    extracted_size = sum(item.get_size(hardlink_masters) for item in archive.iter_items(filter))
  File "/home/barrios/apps/borg/src/borg/archiver.py", line 708, in <genexpr>
    extracted_size = sum(item.get_size(hardlink_masters) for item in archive.iter_items(filter))
  File "/home/barrios/apps/borg/src/borg/archive.py", line 447, in iter_items
    filter=lambda item: self.item_filter(item, filter)):
  File "/home/barrios/apps/borg/src/borg/archive.py", line 220, in unpack_many
    items = [Item(internal_dict=item) for item in unpacker]
  File "/home/barrios/apps/borg/src/borg/archive.py", line 220, in <listcomp>
    items = [Item(internal_dict=item) for item in unpacker]
  File "src/borg/item.pyx", line 50, in borg.item.PropDict.__init__
  File "src/borg/item.pyx", line 60, in borg.item.PropDict.update_internal
AttributeError: 'bytes' object has no attribute 'items'

Platform: Linux manjaro 4.14.16-1-MANJARO #1 SMP PREEMPT Wed Jan 31 19:41:43 UTC 2018 x86_64
Linux: arch Manjaro Linux
Borg: 1.2.0.dev519+gc97006ec.d20180607  Python: CPython 3.6.5
PID: 14976  CWD: /
sys.argv: ['/home/barrios/apps/borg/borg-env/bin/borg', 'extract', '-p', '/run/media/barrios/TOSHIBA EXT/vaio-manjaro-backup::root-2018-06-07']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
The version number indicates that you are using master branch (unreleased borg development version).
This is not recommended for production usage, please use a 1.1.x release (or at least 1.1-maint branch) or oldstable 1.0.x release (or 1.0-maint branch).

Anyway, thanks for the bug report, we'll check what's up in master branch.

**Comment by barrio** [comment]
As I mentioned above, I tried pip install into virtualenv before, same thing.

**Comment by ThomasWaldmann** [comment]
Did you also try a 1.1.5 install into a **freshly made** virtualenv?

**Comment by barrio** [comment]
yes, but I used Python3 venv module instead of virtualenv
`python -m venv borg-env`
Could this be a problem?

**Comment by ThomasWaldmann** [comment]
Don't think so.

**Comment by ThomasWaldmann** [comment]
I had a look at the traceback and the respective code and it looks like the Unpacker has extracted a `bytes` object instead of the expected `dict` object, leading to the crash you see.

That means that the archive you tried to extract is defect and I recommend you first check your hardware (see borg docs about IntegrityErrors) and if hw is ok, then run borg check / borg check --repair on the repo (use 1.1.5 for that).

**Comment by ThomasWaldmann** [comment]
Also please give the msgpack version you use (see pip freeze).

**Comment by barrio** [comment]
msgpack 0.4.8

**Comment by ThomasWaldmann** [comment]
OK, msgpack(-python) 0.4.8 has no known severe problems (AFAIK), so that should be fine.

**Comment by barrio** [comment]
I ran borg create for / from within the running system on ext4 without snapshot, could this lead to a corrupted backup which in turn may have caused the exception? And then -silly enough- I tried to restore again from within the running system. As far as I recall this threw an exception when it came to restore the venv borg was running from... Maybe I try create & extract when the system is down from another install.

**Comment by ThomasWaldmann** [comment]
I don't think so.

OTOH, you should not try to back up /proc and /sys contents, this might trigger weird effects (this is not borg specific).

You also should not restore to a non-empty target directory, this might result in a strange mix up of files.
If you need a desaster recovery, start from a rescue system (usb stick, optical media, ...) and recover to empty file system.

**Comment by barrio** [comment]
As you recommended I did the following steps:
1. Install borg 1.1.5 via pip into fresh venv
2. run `borg create` with excludes for /sys & /proc, which ran without errors.
3. Target partition is ntfs, `chkdsk` ran for some hours showing no defect blocks.

Now on Ubuntu 16.04, again from a fresh venv:
4. run `borg extract -p archiv`, which threw the following exception:
`(borg-env) root@btrfsHDD:/media/barrios/Manjato Restore# borg extract -p ../TOSHIBA\ EXT/vaio-manjaro-backup::root-2018-06-07`
Data integrity error: Segment entry checksum mismatch [segment 2, offset 11555801]                                                                             
Traceback (most recent call last):
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 165, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py", line 752, in do_extract
    stripped_components=strip_components, original_path=orig_path, pi=pi)
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/archive.py", line 602, in extract_item
    for data in self.pipeline.fetch_many(ids, is_preloaded=True):
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/archive.py", line 222, in fetch_many
    for id_, data in zip(ids, self.repository.get_many(ids, is_preloaded=is_preloaded)):
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py", line 1050, in get_many
    yield self.get(id_)
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py", line 1044, in get
    return self.io.read(segment, offset, id)
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py", line 1375, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py", line 1411, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 2, offset 11555801]

Platform: Linux btrfsHDD 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64
Linux: Ubuntu 17.10 artful
Borg: 1.1.5  Python: CPython 3.6.3
PID: 12795  CWD: /media/barrios/Manjato Restore
sys.argv: ['/home/barrios/borg-env/bin/borg', 'extract', '-p', '../TOSHIBA EXT/vaio-manjaro-backup::root-2018-06-07']
SSH_ORIGINAL_COMMAND: None

Could it be that the source partition has defect blocks but` borg create `runs without exception?

**Comment by ThomasWaldmann** [comment]
Please do the checks as recommended by birg docs for IntegrityErrors.

On June 10, 2018 12:46:30 PM GMT+02:00, barrio <notifications@github.com> wrote:
>As you recommended I did the following steps:
>1. Install borg 1.1.5 via pip into fresh venv
>2. run `borg create` with excludes for /sys & /proc, which ran without
>errors.
>3. Target partition is ntfs, `chkdsk` ran for some hours showing no
>defect blocks.
>
>Now on Ubuntu 16.04, again from a fresh venv:
>4. run `borg extract -p archiv`, which threw the following exception:
>`(borg-env) root@btrfsHDD:/media/barrios/Manjato Restore# borg extract
>-p ../TOSHIBA\ EXT/vaio-manjaro-backup::root-2018-06-07`
>Data integrity error: Segment entry checksum mismatch [segment 2,
>offset 11555801]                                                       
>                     
>Traceback (most recent call last):
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py",
>line 4253, in main
>    exit_code = archiver.run(args)
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py",
>line 4185, in run
>    return set_ec(func(args))
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py",
>line 152, in wrapper
>    return method(self, args, repository=repository, **kwargs)
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py",
>line 165, in wrapper
>return method(self, args, repository=repository, manifest=manifest,
>key=key, archive=archive, **kwargs)
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/archiver.py",
>line 752, in do_extract
>  stripped_components=strip_components, original_path=orig_path, pi=pi)
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/archive.py",
>line 602, in extract_item
>    for data in self.pipeline.fetch_many(ids, is_preloaded=True):
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/archive.py",
>line 222, in fetch_many
>for id_, data in zip(ids, self.repository.get_many(ids,
>is_preloaded=is_preloaded)):
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py",
>line 1050, in get_many
>    yield self.get(id_)
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py",
>line 1044, in get
>    return self.io.read(segment, offset, id)
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py",
>line 1375, in read
>size, tag, key, data = self._read(fd, self.put_header_fmt, header,
>segment, offset, (TAG_PUT, ), read_data)
>File
>"/home/barrios/borg-env/lib/python3.6/site-packages/borg/repository.py",
>line 1411, in _read
>    segment, offset))
>borg.helpers.IntegrityError: Data integrity error: Segment entry
>checksum mismatch [segment 2, offset 11555801]
>
>Platform: Linux btrfsHDD 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8
>21:14:41 UTC 2018 x86_64
>Linux: Ubuntu 17.10 artful
>Borg: 1.1.5  Python: CPython 3.6.3
>PID: 12795  CWD: /media/barrios/Manjato Restore
>sys.argv: ['/home/barrios/borg-env/bin/borg', 'extract', '-p',
>'../TOSHIBA EXT/vaio-manjaro-backup::root-2018-06-07']
>SSH_ORIGINAL_COMMAND: None
>
>Could it be that the source partition has defect blocks but` borg
>create `runs without exception?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/3876#issuecomment-396038984

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ThomasWaldmann** [comment]
Any news?

**Comment by ThomasWaldmann** [comment]
no response, closing...
