### ISSUE TITLE
DistributionNotFound with msgpack-python 0.5.6-1 installed

### ISSUE THREAD

**Issue by raxod502** [borgbackup/borg#3889]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

Bug.

#### Your borg version (borg -V).

Version 1.1.6-1 installed via Pacman.

#### Operating system (distribution) and version.

Arch Linux.

```
$ uname -a
Linux taravangian 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
```

#### Hardware / network configuration, and filesystems used.

Not relevant.

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

I tried:

```
$ borg --version
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

We get:

```
$ borg --version
Traceback (most recent call last):
  File "/usr/bin/borg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python!=0.5.0,!=0.5.1,!=0.5.2,!=0.5.3,!=0.5.4,!=0.5.5,<=0.5.6,>=0.4.6' distribution was not found and is required by borgbackup
```

#### Include any warning/errors/backtraces from the system logs

I don't know of any.

**Comment by ThomasWaldmann** [comment]
Guess you need to talk to the dist package maintainer?

If it is because borg wants `msgpack-python` (old name) and the dist package provides `msgpack` (new name), the package maintainer needs to either patch borg (to want new name) or use the real `msgpack-python` (not the `msgpack`) package.

**Comment by raxod502** [comment]
I found out that the problem is solved by

```
$ pip install msgpack-python
```

I will follow up with the packager. Thanks!

**Comment by raxod502** [comment]
I see that this bug was reported already, earlier today: https://bugs.archlinux.org/task/58974

I'm sorry to duplicate the report here; I'm still getting used to the Linux packaging ecosystem.

**Comment by hroncok** [comment]
BTW we were hit by this in Fedora, because we recently switched from msgpack-python to msgpack in the system RPM package with msgpack. We cannot have both at the same time. I've hotfixed it by seding the setup.py, because going with just "msgpack" upstream doesn't work with all the versions specified that are < 0.5.

**Comment by UntouchedWagons** [comment]
@hroncok which file did you edit? I'm having the same issue on Fedora

**Comment by hroncok** [comment]
Oh. I edit it in the source of the Fedora package to fix your problem.

See https://bugzilla.redhat.com/show_bug.cgi?id=1630992

Fedora 29 update: https://bodhi.fedoraproject.org/updates/FEDORA-2018-390e4ad530
Fedora 28 update: https://bodhi.fedoraproject.org/updates/FEDORA-2018-e7aa6d923f
