### ISSUE TITLE
borg: Exiting with failure status due to previous errors

### ISSUE THREAD

**Issue by ovizii** [borgbackup/borg#389]
trying my hands at borgbackup using https://borgbackup.readthedocs.org/en/stable/quickstart.html#automating-backups as a template

What does it mean by "previous errors, all I saw was some permission problem.

```
borg create -s -p -v -C zlib,6 --dry-run        \
    $REPOSITORY::`hostname`-`date +%Y-%m-%d`    \
    /                                           \
    --exclude-from EXCLUDEFILE
- /var/lib/lxcfs/cgroup/blkio/blkio.leaf_weight
- /var/lib/lxcfs/cgroup/blkio/blkio.leaf_weight_device
borg: /var/lib/lxcfs/cgroup/blkio/blkio.reset_stats: [Errno 13] Permission denied: '/var/lib/lxcfs/cgroup/blkio/blkio.reset_stats'
- /var/lib/lxcfs/cgroup/blkio/blkio.sectors
.
.
.
- /var
- /vz
- /
borg: Exiting with failure status due to previous errors
Enter passphrase for key /root/.borg/keys/mnt_pve_SYS_bckp_borgbckp: borg: Error: Keyboard interrupt.
Traceback (most recent call last):
  File "/vagrant/borg/borg/borg/archiver.py", line 1030, in main
  File "/vagrant/borg/borg/borg/archiver.py", line 986, in run
  File "/vagrant/borg/borg/borg/archiver.py", line 426, in do_prune
  File "/vagrant/borg/borg/borg/helpers.py", line 66, in load
  File "/vagrant/borg/borg/borg/key.py", line 53, in key_factory
  File "/vagrant/borg/borg/borg/key.py", line 260, in detect
  File "/vagrant/borg/borg/borg/key.py", line 181, in getpass
  File "/home/vagrant/.pyenv/versions/3.5.0/lib/python3.5/getpass.py", line 78, in unix_getpass
  File "/home/vagrant/.pyenv/versions/3.5.0/lib/python3.5/getpass.py", line 147, in _raw_input
KeyboardInterrupt

borg: Exiting with failure status due to previous errors
root@james:~/.borg#
```

**Comment by ThomasWaldmann** [comment]
if borg does not have permission to read some of the files in the backup set, your backup will be incomplete. this is why it gives that warning. "previous errors" means the files it could not read.

borg >= 0.28 has return code 1 for that (which means that it reached the normal end of the backup procedure, but had issues with some files in between). this is to differentiate that from rc 0 (complete success) and rc 2 (total, abrupt, unexpected failure, not reaching the normal end).

**Comment by ThomasWaldmann** [comment]
To fix it, either exclude files it is expected to be unable to read.
Or run borg as root, so it can read all the files.

**Comment by ovizii** [comment]
THanks, as you noticed, I was running borg as root. 
I'm sure the problem is related to LXC (I'm pretty new to linux containers too) so I will do some more reading up on it.

Thanks for the nice explanations, it all makes more sense to me now. 
Will update this thread if I find out more.
