### ISSUE TITLE
switch from msgpack-python to msgpack

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3890]
I didn't switch from msgpack-python (which we used like forever) within borg 1.0.x or 1.1.x series to not break working package dependencies for distribution packages.

For the 1.2 release, bigger changes are expected anyway, so it is a good time to also switch to the new package name `msgpack`.

**Comment by eli-schwartz** [comment]
> to not break working package dependencies for distribution packages.

This is an illogical reason. Failing to switch is the thing which breaks package dependencies on Arch Linux. It's also the reason multiple distribution releases completely didn't work, when our attempts to patch borg to use msgpack failed without us noticing.

**Comment by ThomasWaldmann** [comment]
then you did not test your package although you made external breaking changes. not my fault.
