### ISSUE TITLE
enhancement request: forced scan for changes

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#390]
if a file keeps same size and timestamp but has changed some bytes, this changes are not noticed so the chunk-list of this file will be the "old" version
for this case i would appreciate to have a option like --fullscan to "force a scan for changes"

**Comment by ThomasWaldmann** [comment]
how do you change some bytes without changing the timestamp?

btw, there already is an option to not use the files cache (for other reasons).

**Comment by ClipperS87** [comment]
if there is an option not to use the file cache, then its fine

(("timestamp" is not "timestamp" i.a. in NTFS we have creation, modified, last access-timestamp etc. - and there are many ways to touch a file a data - i.e. outside a loaded FS like hex-editor etc. ;-) ))

**Comment by ThomasWaldmann** [comment]
If you are doing bloody hacks, like editing files with a disk sector editor, you can't expect tools noticing your changes. You still have the option to manually touch the file's timestamp afterwards (and I mean the mtime) to make your changes get noticed.

**Comment by ClipperS87** [comment]
also a hardware error can change the file - but also for this case I can use the option not to use the file cache - thank you

**Comment by ThomasWaldmann** [comment]
if a hardware error changes the source file you are lucky that it won't get backed up. :)
