### ISSUE TITLE
Borg prune deletes new archive

### ISSUE THREAD

**Issue by pcmanprogrammeur** [borgbackup/borg#3908]
I use BorgBackup for my backups. Here is what i have when i list my archives :

    borg list borg@[SERVER_IP]:/home/backups/$(hostname)
    jenkins_data_2018-06-16 Sat, 2018-06-16 09:28:08
    redmine_data_2018-06-16 Sat, 2018-06-16 09:31:38

Now, i would like to add the command "borg prune" and check what it could delete :

    borg prune -v --list --dry-run borg@[SERVER_IP]:/home/backups/$(hostname) --keep-daily=7 --keep-weekly=4 --keep-monthly=3
    Keeping archive: redmine_db_2018-06-16 Sat, 2018-06-16 09:31:38
    Would prune: jenkins_data_2018-06-16 Sat, 2018-06-16 09:28:08

So, Borg would prune an archive which has been created today.

Do you know why please ?

**Comment by adhawkins** [comment]
You haven't asked it to keep any hourly backups, so it will keep one per day for the last 7 days.

**Comment by adhawkins** [comment]
Not sure. It may delete the older one so you only have one per hour. Is there a keep option for minutes?

**Comment by pcmanprogrammeur** [comment]
Thank you very much.
To resolve the problem i created two subfolders :

**Comment by jdchristensen** [comment]
I recommend using ``-P`` to set a prefix, so you separately do the pruning for each host.  E.g. ``-P jenkins_`` and ``-P redmine_``.  (The trailing underscore is good practice, in case you have a host ``foo`` and another host ``foobar``.)

**Comment by ThomasWaldmann** [comment]
Guess this is solved with @jdchristensen's comment.

**Comment by pcmanprogrammeur** [comment]
Thank you @jdchristensen for this best practice !
