### ISSUE TITLE
feature request: borg-create final message

### ISSUE THREAD

**Issue by Kriechi** [borgbackup/borg#3915]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question / Feature Request

## Describe the problem you're observing.

I'm currently using borgbackup 1.1.5 an the latest macOS with 
`borg create --progress --one-file-system --checkpoint-interval=60 ::myhostname-$TIMESTAMP /Users/myusername`.
Once the backup is completed, I do not see any final concluding message. I would expect to see something like "Backup ::myhostname-$TIMESTAMP successfully created" or similar.

Sometimes it is hard for me to tell if it did finish or not, because one backup take 15-20min, and if I put my notebook to sleep, it might fail in between - without telling me.

I would like to see a short summary or conclusion being printed to stdout. Optionally it should be supressed with a `--quiet` option or similar. rsync provides a nice summary about total file size transferred, backup duration, etc.

**Comment by infectormp** [comment]
did you try?

> -s, --stats | print statistics for the created archive

**Comment by Kriechi** [comment]
yeah..., well..., no, I didn't.

Thanks!

**Comment by ThomasWaldmann** [comment]
also, there is `--show-rc` to output the exit status.
