### ISSUE TITLE
Chunker Parameters for Text Files

### ISSUE THREAD

**Issue by shadowrylander** [borgbackup/borg#3917]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### How much data is handled by borg?

1 - 2 GB

## Question

&nbsp;&nbsp;&nbsp;&nbsp; What would the recomended `--chunker-params` for mostly text files (i.e. thousands of them, a few hundred images, and a handful of binary files)? I am assuming:
&nbsp;&nbsp;&nbsp;&nbsp; `CHUNK_MIN_EXP:` 1
&nbsp;&nbsp;&nbsp;&nbsp; `CHUNK_MAX_EXP:` 23
But am confused as to what `HASH_MASK_BITS` and `HASH_WINDOW_SIZE` would be recomended.
&nbsp;&nbsp;&nbsp;&nbsp; Thanks!

&nbsp;&nbsp;&nbsp;&nbsp; `P.S. :` In addition, what is the general deduplication block size recomended for text files? Most programs have a default of a few megabytes, but the text files are only a few bytes or kilobytes.

**Comment by ThomasWaldmann** [comment]
You could just go with the default chunker settings. Small text files would be treated as 1 chunk then.

If your total data size is only a few GB it is maybe pointless to tweak a lot?

**Comment by ShadowRylander** [comment]
¯\_(ツ)_/¯
True; however, if just for testing purposes, what would the recomended settings be?

**Comment by ThomasWaldmann** [comment]
you could experiment with `--chunker-params 8,12,10,63`.

the min chunk will be 2^8 == 256 bytes, max chunk will be 2^12 == 4096 bytes.
the target ("usual") chunk size will be about 2^10 == 1024 bytes.
the window used to compute the rolling hash is 63 bytes long.

i never tried it, so be careful  and use a separate repo for such experiments.

be aware that these params will generate a huge amount of chunks and thus consume lots of RAM and disk space if you backup larger files / a large amount of data.

**Comment by ShadowRylander** [comment]
Thank you!
I've made another copy of my primary repository, so no worries there; in addition, would it be possible to explain what the `window` portion does?

**Comment by ThomasWaldmann** [comment]
a window of the given size (63) is moved over the whole input file, advancing position 1 byte at a time.

for each window position, the rolling hash (buzhash) value is computed.

then it masks MASK bits (10) from that hash value and if the result is 0, it cuts a chunk (if the minimum chunk size is already reached).

**Comment by ShadowRylander** [comment]
Hmm... Guess I'll have to read up on this more... Thanks!
