### ISSUE TITLE
support keyring for passphrase storage

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#392]
Consider using https://github.com/jaraco/keyring as it's maintained and supports GNOME, KDE, OS X, and others.

Supercedes #184 and #78.

**Comment by anarcat** [comment]
keyring is packaged in debian, FWIW, all the way down to Debian:

```
[995]anarcat@angela:~$ rmadison python3-keyring
debian:
 python3-keyring | 0.7.1-1+deb7u1 | wheezy           | all
 python3-keyring | 3.8-1~bpo70+1  | wheezy-backports | all
 python3-keyring | 4.0-1          | jessie-kfreebsd  | all
 python3-keyring | 4.0-1          | jessie           | all
 python3-keyring | 5.6-1          | stretch          | all
 python3-keyring | 5.6-1          | sid              | all
ubuntu:
 python3-keyring | 0.7.1-1fakesync1       | precise/universe          | all
 python3-keyring | 0.9.2-0ubuntu0.12.04.2 | precise-security/universe | all
 python3-keyring | 0.9.2-0ubuntu0.12.04.2 | precise-updates/universe  | all
 python3-keyring | 3.5-1                  | trusty/universe           | all
 python3-keyring | 4.0-1ubuntu1           | vivid                     | all
 python3-keyring | 4.0-1ubuntu1           | wily                      | all
 python3-keyring | 5.6-1ubuntu1           | xenial                    | all
```

**Comment by Airaiche** [comment]
Hi, is gnome-keyring going to be supported ? This seems to be the only reasonably secure way of automating encrypted backups...

**Comment by enkore** [comment]
If the headline were implemented then, yes.

As to reasonably secure... well... a keyring is a bit better than having it in plain-text in the script. For the backup to run, the keyring still has to be unlocked (with the password then available for attackers as well). Since we're talking automated, it likely is often unlocked.

Also note that you don't *have to* put the passphrase in the script. You could use e.g. secret-tool(1) to get it from the key ring with no specific support from borg. Someone on IRC recently made his scripts fetch the passphrase from a physical security token. There are many possibilities to do things like this right now...

**Comment by enkore** [comment]
Use BORG_PASSCOMMAND.

E.g., using Linux keyring stuff:

1. Store password, `secret-tool store borg-repository some-borg-repo  --label="Borg Password"`
2. `BORG_PASSCOMMAND="secret-tool lookup borg-repository some-borg-repo" borg list/create/...`

This should work with other keyrings as well, e.g. [OSX](https://www.netmeister.org/blog/keychain-passwords.html).

**Comment by enkore** [comment]
Documentation Task: Test and document using the different keyrings (Linux, OSX)

**Comment by Simounet** [comment]
Hi there,
I would love to use the secret-tool to handle my Borg password. I tried to add it to a cronjob, it asks me to unlock my keyring. Do you have any hint for me?

**Comment by RonnyPfannschmidt** [comment]
that bit belongs exclusively to secret-tool, borg cant help with it

**Comment by Simounet** [comment]
I agree but @enkore seems to used it so I thought it might be useful to Borg users.

**Comment by enkore** [comment]
Well the keyring needs to be unlocked to get passwords from it. If it isn't unlocked already, that should result in a prompt.

**Comment by Simounet** [comment]
Hmmm ok, I see. Thanks for the tip. I thought that an opened session could access to a password without being prompted.

**Comment by enkore** [comment]
It should be able to.

**Comment by Simounet** [comment]
In my case (a cronjob) it feels like it is not the same session. Too bad!

**Comment by enkore** [comment]
If it's running under the same user, `DISPLAY=:0` / `DISPLAY=:1` might be enough.

**Comment by Simounet** [comment]
It's working perfectly with `DISPLAY=:0`. Thanks!

**Comment by ThomasWaldmann** [comment]
^^^ sounds like a FAQ entry.

**Comment by piegamesde** [comment]
I don't quite understand -- is https://github.com/jaraco/keyring in use or not? The only thing I could find in the documentation regarding Gnome, KDE etc. seems to refer to their specific commands and not to that tool linked here which is quite confusing.

**Comment by hrehfeld** [comment]
```
  File "/usr/lib/python3.7/site-packages/keyring/core.py", line 55, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python3.7/site-packages/keyring/backends/chainer.py", line 44, in get_password
    password = keyring.get_password(service, username)
  File "/usr/lib/python3.7/site-packages/keyring/backends/kwallet.py", line 100, in get_password
    raise KeyringLocked("Failed to unlock the keyring!")
keyring.errors.KeyringLocked: Failed to unlock the keyring!
```

Seems like it is in use.
