### ISSUE TITLE
Borg is slow creating an archive when no files have changed

### ISSUE THREAD

**Issue by russelldavis** [borgbackup/borg#3927]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Issue

## System information. For client/server mode post info for both machines.
macOS 10.13.5

#### Your borg version (borg -V).
borg 1.1.5

#### Hardware / network configuration, and filesystems used.
Local filesystem (APFS) for both source and destination.

#### How much data is handled by borg?
80K files totalling 4GB in size

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create --stats ~/tmp/borg::full ~/

## Describe the problem you're observing.
When creating an incremental archive with ~no changed files, borg takes 24 seconds to scan everything. When doing the same thing with [duplicacy](https://github.com/gilbertchen/duplicacy), it only takes 5 seconds.

Similar results were documented at https://github.com/gilbertchen/benchmarking. I'm wondering if it's known why borg takes so much longer here and if there are any thoughts/plans on potentially addressing it.

In case it helps, here's my output from `borg benchmark crud`:

```
C-Z-BIG         212.83 MB/s (10 * 100.00 MB all-zero files: 4.70s)
R-Z-BIG         320.15 MB/s (10 * 100.00 MB all-zero files: 3.12s)
U-Z-BIG         566.04 MB/s (10 * 100.00 MB all-zero files: 1.77s)
D-Z-BIG        4277.36 MB/s (10 * 100.00 MB all-zero files: 0.23s)
C-R-BIG         107.68 MB/s (10 * 100.00 MB random files: 9.29s)
R-R-BIG         138.77 MB/s (10 * 100.00 MB random files: 7.21s)
U-R-BIG         576.90 MB/s (10 * 100.00 MB random files: 1.73s)
D-R-BIG         778.08 MB/s (10 * 100.00 MB random files: 1.29s)
C-Z-MEDIUM      243.46 MB/s (1000 * 1.00 MB all-zero files: 4.11s)
R-Z-MEDIUM      157.95 MB/s (1000 * 1.00 MB all-zero files: 6.33s)
U-Z-MEDIUM      677.86 MB/s (1000 * 1.00 MB all-zero files: 1.48s)
D-Z-MEDIUM     4201.69 MB/s (1000 * 1.00 MB all-zero files: 0.24s)
C-R-MEDIUM      127.15 MB/s (1000 * 1.00 MB random files: 7.86s)
R-R-MEDIUM      153.62 MB/s (1000 * 1.00 MB random files: 6.51s)
U-R-MEDIUM      670.86 MB/s (1000 * 1.00 MB random files: 1.49s)
D-R-MEDIUM      886.08 MB/s (1000 * 1.00 MB random files: 1.13s)
C-Z-SMALL        36.21 MB/s (10000 * 10.00 kB all-zero files: 2.76s)
R-Z-SMALL        92.80 MB/s (10000 * 10.00 kB all-zero files: 1.08s)
U-Z-SMALL        32.92 MB/s (10000 * 10.00 kB all-zero files: 3.04s)
D-Z-SMALL       287.14 MB/s (10000 * 10.00 kB all-zero files: 0.35s)
C-R-SMALL        27.81 MB/s (10000 * 10.00 kB random files: 3.60s)
R-R-SMALL        87.80 MB/s (10000 * 10.00 kB random files: 1.14s)
U-R-SMALL        35.81 MB/s (10000 * 10.00 kB random files: 2.79s)
D-R-SMALL       144.28 MB/s (10000 * 10.00 kB random files: 0.69s)
```

**Comment by ThomasWaldmann** [comment]
borg is not an incremental backup tool, it always creates full archives:
- it checks whether the file content could have changes (using the files cache). the outcome determines whether content has to get chunked again or the chunks list from the files cache is used. the check uses ctime which might be slower in some cases, but is safer to detect changes.
- when not chunking, it checks whether it still has all the chunks from the cached list in the repo.
- when chunking, it does not process content chunks again which it already has in the repo and processes only new chunks.
- it reads xattrs, acls, bsdflags from the fs.
- it creates an entry into the metadata stream with that data.

I don't know what duplicacy does in detail. Doing less than the above of course would be faster, but maybe not what one wants.

**Comment by ThomasWaldmann** [comment]
if you want to determine whether ctime vs. mtime plays a role, search the issue tracker for these keywords.

**Comment by russelldavis** [comment]
Thanks for the reply. I searched for ctime in the issues as you suggested and found https://github.com/borgbackup/borg/issues/3039. I tried the patch there (disabling the reading of extended attributes) and that brought the time down to 15s. I wonder if general python slowness accounts for the rest? ¯\\_(ツ)_/¯

Per your comment at https://github.com/borgbackup/borg/issues/3039#issuecomment-331192271, I like the idea of storing the attributes in the files cache (I think that's essentially what duplicacy does -- note that it always creates full archives as well). Perhaps that could eventually become an option? (ctime is the default now anyway, and I'd gladly accept a larger files cache as a tradeoff).

The last comment in that issue points to #3918. I tried that PR and it brought the time down from 25s to 20s which is 💯.

**Comment by ThomasWaldmann** [comment]
@russelldavis thanks for trying the code from the PR, happy that it improved speed also.

About storing xattrs / acls / bsdflags in the files cache: the files cache can already be huge and is loaded into memory. making it even bigger might just mean game over for systems with not that much RAM. not sure how big the difference usually would be, but guess that heavily depends on how (many) xattrs/acls are used.

**Comment by ThomasWaldmann** [comment]
@FabioPedretti if you like, you could do a speed test with the code from PR #3918.

**Comment by ThomasWaldmann** [comment]
I am closing this in favour of #3955.
