### ISSUE TITLE
[SOLVED] [MOUNTED CLOUDS] Repository has no attribute lock

### ISSUE THREAD

**Issue by lucas59356** [borgbackup/borg#3930]
#### Your borg version (borg -V).
borg 1.1.4

#### Operating system (distribution) and version.
Fedora 28 XFCE

#### Hardware / network configuration, and filesystems used.
i5 7200
6GB RAM
1TB HD

#### How much data is handled by borg?
~30GB

I make my backups in a local folder, after this I use rclone (by ncw) to upload my files to my google drive acc but sometimes we need to test our backups :p. Rclone haves a feature called mount that mounts the cloud remote as a fuse filesystem, the idea is mount that folder and check it. But that error in the end of this issue always happens. I tried to open python3, import os and getcwd(), same problem. After few moments searching and trying some workarounds I have found something that works:
I have CDed outside the mount and runned borg check with relative path to the folder that have the backup inside, now that error do not happens xD. Working perfectly <3.
![captura de tela_2018-06-26_09-01-36](https://user-images.githubusercontent.com/15693688/41910532-5274f718-7920-11e8-9c48-9cc62928d065.png)
![captura de tela_2018-06-26_09-01-21](https://user-images.githubusercontent.com/15693688/41910539-590e0e16-7920-11e8-9c2f-c0839f09173a.png)

#### The output with the problem
```
➜  backup borg check BORG --progress --verbose 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4175, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4107, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 136, in wrapper
    storage_quota=storage_quota)
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 147, in __init__
    self.path = os.path.abspath(path)
  File "/usr/lib64/python3.6/posixpath.py", line 376, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 11, in <module>
    load_entry_point('borgbackup==1.1.4', 'console_scripts', 'borg')()
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4197, in main
    tb = '%s\n%s' % (traceback.format_exc(), sysinfo())
  File "/usr/lib64/python3.6/site-packages/borg/helpers.py", line 1610, in sysinfo
    info.append('PID: %d  CWD: %s' % (os.getpid(), os.getcwd()))
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 169, in __del__
    if self.lock:
AttributeError: 'Repository' object has no attribute 'lock'
```

**Comment by ThomasWaldmann** [comment]
a lot of fuse filesystems aren't robust enough for heavy usage like borg does.

so, be careful.

**Comment by lucas59356** [comment]
I just use the fuse mount for checking the backup (only read). When doing a new backup I use an local folder, after this rclone (in its way) syncs to the google drive folder. It uses network heavily but works nice.
