### ISSUE TITLE
borg create --exclude-caches: Directories with CACHEDIR.TAG not being excluded

### ISSUE THREAD

**Issue by mkg20001** [borgbackup/borg#3938]
borg create is backing up folders with `CACHEDIR.TAG` in them even though `--exclude-caches` is specified

additionally the CACHEDIR.TAG itself is being backed-up up too

## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.6

#### Operating system (distribution) and version.

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

#### Hardware / network configuration, and filesystems used.

client: 256GB ssd, gigabit network
server: hetzner storagebox with borg support (no exact hardware details known)

#### How much data is handled by borg?

~100GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borgbackup create --verbose --filter AME --list --stats --show-rc --exclude-caches --exclude /home/*/.cache/* ::{hostname}-{now} /home
```

(note: this command is invoked by "sshpass -p xxx borgbackup..." and the BORG_REPO env variable is set)

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Another script that produces this problem:

```sh
cd /tmp
mkdir -p data/_OLD
touch data/_OLD/do_not_backup.file
touch data/_OLD/CACHEDIR.TAG
borg init -e none /tmp/testrepo
borg create --exclude-caches --verbose --stats --list /tmp/testrepo::backup /tmp/data
```

output of the above script

```log
A /tmp/data/_OLD/do_not_backup.file
A /tmp/data/_OLD/CACHEDIR.TAG
d /tmp/data/_OLD
d /tmp/data
------------------------------------------------------------------------------
Archive name: backup
Archive fingerprint: 287ff3512d9f4e78284f189e9482ca05f0774a9ef731b85157abbf765820ecbc
Time (start): Sat, 2018-06-30 13:40:47
Time (end):   Sat, 2018-06-30 13:40:47
Duration: 0.00 seconds
Number of files: 2
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.00 kB                709 B                709 B
All archives:                1.00 kB                709 B                709 B

                       Unique chunks         Total chunks
Chunk index:                       2                    2
------------------------------------------------------------------------------
```

#### Include any warning/errors/backtraces from the system logs

none

after I changed the contents of the CACHEDIR.TAG:
```
M /home/maciej/_OLD/CACHEDIR.TAG
```

**Comment by ThomasWaldmann** [comment]
that the CACHEDIR.TAG itself is being backed up is not a bug.

just imagine what would happen if we did not back it up and you needed a full restore of your data.
if the tag was not backed up / was not restored, your next backup would include all those directories because the tag is missing.

The CACHEDIR.TAG contents must start with this sequence:
```
Signature: 8a477f597d28d172789f06886806bc55
```
A simple touch does not produce a valid tag file.

http://www.brynosaurus.com/cachedir/spec.html

**Comment by mkg20001** [comment]
@ThomasWaldmann Thanks for the quick response! Makes sense, going to close this

About the missing signature: I think I should read the full docs instead of just doing `command --help | grep something`...

**Comment by ThomasWaldmann** [comment]
Well, we only have the spec URL in the docs for the cachedir standard...
