### ISSUE TITLE
Exit Codes of Borg backup on Network Error

### ISSUE THREAD

**Issue by engelant** [borgbackup/borg#3939]
Due to the remote nature of Borg Backup I would find it usefull, if we would get an Exit code back, that indicates the network connection broke down, since this is not really an error in Borg. Therefor inside the script one could just sleep a few seconds and then retry connectiong to the remote a few times before really giving up and throwing an error (or just continuing with the backup). This is especially affecting DialUP with DynDNS.

**Comment by ThomasWaldmann** [comment]
borg uses ssh to set up and deal with the connection. from ssh man page:

```
EXIT STATUS
     ssh exits with the exit status of the remote command
     or with 255 if an error occurred.
```

So, we (maybe) have that and also borg's `RemoteRepository` code notices that the pipes to the local ssh process stopped working.

Not much information (and not very precise information), but needs more research whether we can make something from that.

**Comment by engelant** [comment]
As far as I understood the SSH error code is not passed trough, just the error code of the command run on the remote end. Would there be any reson not to introduce an 2 < error code < 128, that represents a "transport error"?

**Comment by ThomasWaldmann** [comment]
That would be possible at a bigger release step I guess. Main problem is getting to know what happened and defining additional error codes (which reminds me that we likely have another ticket about this).

**Comment by ThomasWaldmann** [comment]
see #6756
