### ISSUE TITLE
Failure to extract. Once with 'include pattern not matched' error and once with no error.

### ISSUE THREAD

**Issue by seanspotatobusiness** [borgbackup/borg#3956]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG/ISSUE

## System information. For client/server mode post info for both machines.

Raspberry Pi 3 B+ runing Raspbian Stretch and accessing NFS fileshare on Synology NAS.

#### Your borg version (borg -V).

1.0.9

#### Operating system (distribution) and version.

Raspbian Stretch

#### Hardware / network configuration, and filesystems used.

Synology NAS uses ext4 but shares a folder with my Pi 3 B+ using NFS.

#### How much data is handled by borg?

~200 KB (not a typo)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

'''
pi@xerxes:~ $ borg list /home/pi/Wintermute/Dev/XerxesBackupRepo::FirstBackup | grep tmux
Enter passphrase for key /home/pi/Wintermute/Dev/XerxesBackupRepo: 
-rwxr-xr-x pi     pi         1901 Fri, 2018-06-29 10:11:57 home/pi/Mining/tmuxScript.sh

pi@xerxes:~ $ mv /home/pi/Mining/tmuxScript.sh /home/pi/Mining/tmuxScript.sh.orig

pi@xerxes:~ $ borg extract /home/pi/Wintermute/Dev/XerxesBackupRepo::FirstBackup /home/pi/Mining/tmuxScript.sh
Enter passphrase for key /home/pi/Wintermute/Dev/XerxesBackupRepo: 
Include pattern '/home/pi/Mining/tmuxScript.sh' never matched.
pi@xerxes:~ $ borg extract /home/pi/Wintermute/Dev/XerxesBackupRepo::FirstBackup home/pi/Mining/tmuxScript.sh
Enter passphrase for key /home/pi/Wintermute/Dev/XerxesBackupRepo: 
pi@xerxes:~ $ 
'''

## Describe the problem you're observing.

First extract attempt failed with error "Include pattern not matched". Not knowing how to resolve, I removed the / forward slash preceeding home to match the output from the grep search. This extract attempt failed silently. The file is not restored and no error is returned.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes.

#### Include any warning/errors/backtraces from the system logs

**Comment by ThomasWaldmann** [comment]
you have considered that extraction is always to the current working directory?

so, you did look into `./home/...` to check for extraction results, not into `/home/...`?

**Comment by seanspotatobusiness** [comment]
Extraction did indeed occur to /home/pi/home/pi/Mining. Thanks.
