### ISSUE TITLE
ioctl(fd, TCGETS, ...)  = -1 ENOTTY

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#3962]
just noticed while stracing:

```
ioctl(5, TCGETS, 0x7ffef1435b60)  = -1 ENOTTY (Inappropriate ioctl for device)
```

this happens for about any file `borg create` reads.

any idea how to get rid of this?

i thought it might be related to default `buffering=-1` of `os.fdopen()`, but setting it to 0 or 4096 didn't help.

python 3.6.5

**Comment by ThomasWaldmann** [comment]
```
    fh = os.open(path, flags_noatime)
    with os.fdopen(fh, 'rb') as fd:
        (read file)
```

**Comment by ThomasWaldmann** [comment]
Looks like we do not really need the fd there as we have the fh (and the chunker uses the fh, if valid).

**Comment by ThomasWaldmann** [comment]
https://github.com/python/cpython/blob/c0ee341b29bd7d978b49272a2c0e2dcfa77404d5/Modules/_io/_iomodule.c#L392

**Comment by ThomasWaldmann** [comment]
Code to reproduce:
```
with open('foo', 'rb', buffering=0) as f:
    f.read()
```

**Comment by Dav1dde** [comment]
Issue created in Python bug-tracker: https://bugs.python.org/issue34070
