### ISSUE TITLE
borg waiting lock timeout

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#3968]
Borg 1.1.6.

Sometimes borg cannot get lock when I do `borg create`. 
It's a cron job, so I have to look at servers manually time to time and kill borg and do manually `borg break- lock`.

Is it possible to setup some small timeout in this case?

upd: in case of ctrl+c instead of kill I see:

```
Traceback (most recent call last):
  File "borg/locking.py", line 129, in acquire
FileExistsError: [Errno 17] File exists: '/root/.cache/borg/080c2a228dd0cb7bd7c7baed8d0c68aaba193eef35a8b956704d7ffc6201ecfc/lock.exclusive'
```

**Comment by ThomasWaldmann** [comment]
Next time this happens, I need (before you kill / ctrl-c / break-lock):
```
ps aux | grep borg
hostname
ls -lR .cache/borg/CORRECT_REPO_ID
```

**Comment by knutov** [comment]
Now it happened again:

```
root@nancy:/# ps aux | grep borg
root     24501  0.0  0.0  13220  5344 pts/0    S+   00:02   0:00 borg create --compression auto,zstd,3 -svpx --show-rc --exclude-from=/usr/sandbox/exclude --exclude-caches --exclude-if-present .nobackup --noatime --nobsdflags --files-cache=ctime,size bak01@bak.some.server:borg/folder::folder-{now:%Y-%m-%d-%H%M%S} ./
root     24552  0.0  0.2 169240 27360 pts/0    S+   00:02   0:02 borg create --compression auto,zstd,3 -svpx --show-rc --exclude-from=/usr/sandbox/exclude --exclude-caches --exclude-if-present .nobackup --noatime --nobsdflags --files-cache=ctime,size bak01@bak.some.server:borg/folder::folder-{now:%Y-%m-%d-%H%M%S} ./
root     24729  0.0  0.0  46856  3728 pts/0    S+   00:02   0:00 ssh -oBatchMode=yes -oCiphers=aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,arcfour128,chacha20-poly1305@openssh.com -oStrictHostKeyChecking=no bak01@bak.some.server borg serve --umask=077 --info
root     27030  0.0  0.0  12920  1040 pts/3    S+   02:40   0:00 grep --color=auto borg
```

```
# hostname -f
nancy.dobrohost.ru
```

```
root@nancy:~# ls -lR ~/.cache/borg/642be8429e9ffa722ad8a413615f49f40ee17f252634caad4dd8b15de70a9c8a
/root/.cache/borg/642be8429e9ffa722ad8a413615f49f40ee17f252634caad4dd8b15de70a9c8a:
total 28140
-rw------- 1 root root 11534486 Jul  7 23:20 chunks
drwx------ 2 root root    12288 Mar  4 18:31 chunks.archive.d
-rw------- 1 root root      601 Jul  7 23:20 config
-rw------- 1 root root 17241502 Jul  7 23:20 files
drwx------ 2 root root     4096 Jul  9 00:51 lock.exclusive
-rw------- 1 root root       64 Jul  9 00:51 lock.roster
-rw------- 1 root root       68 Sep 12  2017 README
drwx------ 2 root root     4096 Jul  9 00:51 txn.active

/root/.cache/borg/642be8429e9ffa722ad8a413615f49f40ee17f252634caad4dd8b15de70a9c8a/chunks.archive.d:
total 52988
-rw------- 1 root root 4495630 Feb 24 11:28 2b3f11efb4c9946b8ad9f21f78f23b2f690efe264de8c34524443909441a5ad8.compact
-rw------- 1 root root      98 Feb 24 11:28 2b3f11efb4c9946b8ad9f21f78f23b2f690efe264de8c34524443909441a5ad8.compact.integrity
-rw------- 1 root root 4527838 Feb 24 11:28 3dec3edd96c563d37e3c8dffa7a73cf4174a5b96db2c7c12339521f6f050948c.compact
-rw------- 1 root root      98 Feb 24 11:28 3dec3edd96c563d37e3c8dffa7a73cf4174a5b96db2c7c12339521f6f050948c.compact.integrity
-rw------- 1 root root 4502494 Feb 24 11:28 52b690aca2d7513a606d673f9dffcbc0b34c67af5dbdf52cf23e0685caef6c3b.compact
-rw------- 1 root root      98 Feb 24 11:28 52b690aca2d7513a606d673f9dffcbc0b34c67af5dbdf52cf23e0685caef6c3b.compact.integrity
-rw------- 1 root root 4450706 Feb 24 11:28 5febdfaefca0c3e823696b9b16bf35f701e0085226e3bef0d6ab9519a9fbf713.compact
-rw------- 1 root root      98 Feb 24 11:28 5febdfaefca0c3e823696b9b16bf35f701e0085226e3bef0d6ab9519a9fbf713.compact.integrity
-rw------- 1 root root 4513846 Mar  4 18:31 6c9e4f7d3e0fdac634ef9283cc8d70be7457fd768ee58c673fedf62281c066b4.compact
-rw------- 1 root root      98 Mar  4 18:31 6c9e4f7d3e0fdac634ef9283cc8d70be7457fd768ee58c673fedf62281c066b4.compact.integrity
-rw------- 1 root root 4490086 Mar  4 18:31 9d46b9753f155d36ed679b46ab77bf09cf65f1a8f6a2c6a09ed7aba6b12a8eb3.compact
-rw------- 1 root root      98 Mar  4 18:31 9d46b9753f155d36ed679b46ab77bf09cf65f1a8f6a2c6a09ed7aba6b12a8eb3.compact.integrity
-rw------- 1 root root 4478382 Feb 24 11:28 b761cd3f812adb93e072db998938f8842a6d57ef6c7254c28f3179889f05454b.compact
-rw------- 1 root root      98 Feb 24 11:28 b761cd3f812adb93e072db998938f8842a6d57ef6c7254c28f3179889f05454b.compact.integrity
-rw------- 1 root root 4595950 Feb 24 11:28 b85517cbdf024613267e65ba19c3b4a27999ce987194588dd6230fa0026417c9.compact
-rw------- 1 root root      98 Feb 24 11:28 b85517cbdf024613267e65ba19c3b4a27999ce987194588dd6230fa0026417c9.compact.integrity
-rw------- 1 root root 4409654 Feb 24 11:28 ba621b912be52649374281052e494ef9386b52e128908c7c928a60a4aa27605d.compact
-rw------- 1 root root      98 Feb 24 11:28 ba621b912be52649374281052e494ef9386b52e128908c7c928a60a4aa27605d.compact.integrity
-rw------- 1 root root 4506366 Mar  4 18:31 c2f12f07fdf32794ba99b6f7a8dd2f343c10684cdf5b28447e38ecc45aaa4b64.compact
-rw------- 1 root root      98 Mar  4 18:31 c2f12f07fdf32794ba99b6f7a8dd2f343c10684cdf5b28447e38ecc45aaa4b64.compact.integrity
-rw------- 1 root root 4603386 Feb 24 11:28 c76affa070a69dced934226111727b61765718b99693d1d674be2baf48cf9a06.compact
-rw------- 1 root root      98 Feb 24 11:28 c76affa070a69dced934226111727b61765718b99693d1d674be2baf48cf9a06.compact.integrity
-rw------- 1 root root 4607478 Feb 24 11:28 e42b3b6472b3ef8ccc699fc2100e08d15c581ee3f9be857927441a64ef6feae2.compact
-rw------- 1 root root      98 Feb 24 11:28 e42b3b6472b3ef8ccc699fc2100e08d15c581ee3f9be857927441a64ef6feae2.compact.integrity

/root/.cache/borg/642be8429e9ffa722ad8a413615f49f40ee17f252634caad4dd8b15de70a9c8a/lock.exclusive:
total 0
-rw------- 1 root root 0 Jul  9 00:51 nancy.dobrohost.ru@228091181702898.8017-0

/root/.cache/borg/642be8429e9ffa722ad8a413615f49f40ee17f252634caad4dd8b15de70a9c8a/txn.active:
total 28112
-rw------- 1 root root 11534486 Jul  9 00:51 chunks
-rw------- 1 root root      601 Jul  9 00:51 config
-rw------- 1 root root 17241502 Jul  9 00:51 files
```

**repodir from backup server**
```
# ls -lR .
.:
total 11M
-rw------- 1 bak01 bak01  164 Mar 19  2017 config
drwx------ 3 bak01 bak01 4.0K Mar 19  2017 data
-rw------- 1 bak01 bak01  19K Jul  7 23:20 hints.5868
-rw------- 1 bak01 bak01  11M Jul  7 23:20 index.5868
-rw------- 1 bak01 bak01  190 Jul  7 23:20 integrity.5868
drwx------ 2 bak01 bak01 4.0K Jul 15 00:02 lock.exclusive
-rw------- 1 bak01 bak01   61 Jul 15 00:02 lock.roster
-rw------- 1 bak01 bak01   26 Mar 19  2017 README

./data:
total 72K
drwx------ 2 bak01 bak01 68K Jul  7 23:20 0

./data/0:
total 13G
-rw------- 1 bak01 bak01   17 Jul 26  2017 2004
...
-rw------- 1 bak01 bak01   17 Jul  7 23:20 5868

./lock.exclusive:
total 0
-rw------- 1 bak01 bak01 0 Jul 15 00:02 he1.knutov.net@22930456287622.648096-0
```

When I do `borg create` it waits for infinite time.
When I do `borg info`:
```
borg info bak01@bak.some.server:borg/folder
Failed to create/acquire the lock /some/path/borg/folder/lock.exclusive (timeout).
```

**Comment by ThomasWaldmann** [comment]
The borg repo on the server is locked by `he1.knutov.net`, pid 648096. Does a process for that pid exist on that machine?

The borg cache on `nancy.dobrohost.ru` is locked by pid 8017 on that machine, which seems stale as it is not in your `ps` output.

**Comment by knutov** [comment]
Yes,


```
bakup server# ps aux | grep 648096
bak01     648096  0.0  0.2 255704 37240 ?        S    00:02   0:00 borg serve --umask=077 --info
```

process with pid 8017 did not exists.

I didn't kill borg process, so I can check something more if you need.

Why this all happens? How to fix it?

**Comment by knutov** [comment]
```
# cat ~/.cache/borg/642be8429e9ffa722ad8a413615f49f40ee17f252634caad4dd8b15de70a9c8a/lock.roster
{"exclusive": [["nancy.dobrohost.ru@228091181702898", 8017, 0]]}
```

I use `borg-linux64` binary from https://github.com/borgbackup/borg/releases

```
borg --version
borg 1.1.6
```

**Comment by ThomasWaldmann** [comment]
BORG_HOSTNAME_IS_UNIQUE - what is the value of this env var on nancy? (in the env where borg runs)

**Comment by knutov** [comment]
> 24501 and 24552 on nancy is the borg create which is hanging forever?

It seems so.
It can happen to any other repo from any other server, it just happens sometimes.

```
# echo $BORG_HOSTNAME_IS_UNIQUE

```

so it's empty.

I only do 
```
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes
export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
export BORG_SHOW_SYSINFO=no
export BORG_RSH='ssh -oBatchMode=yes -oCiphers=aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,arcfour128,chacha20-poly1305@openssh.com -oStrictHostKeyChecking=no'
```

before `borg create`.

**Comment by knutov** [comment]
`env | grep BORG_HOSTNAME_IS_UNIQUE` is also empty

**Comment by ThomasWaldmann** [comment]
ok, I stared at the locking code for a while, couldn't find an issue yet.

but on your systems there seem to be 2:
- borg is dying and leaving a cache lock behind
- the stale lock removal does not remove the lock although it is on same host and you do not have BORG_HOSTNAME_IS_UNIQUE=no (default is yes).

**Comment by ThomasWaldmann** [comment]
fix for "never times out": #3981

**Comment by knutov** [comment]
Thanks,
Will it be released as 1.1.7? 
Or how to build stable version with this fix?

**Comment by ThomasWaldmann** [comment]
i first want to check if i can solve why the stale lock is not removed.

**Comment by ThomasWaldmann** [comment]
BTW, I reproduced the "wait forever to the cache lock" issue and that #3981 actually times out.
Merged into 1.1-maint and master.

Still unclear why it does not kill the stale locks.

Did you check that you do **not** have BORG_HOSTNAME_IS_UNIQUE=no on the client **and** on the server (in the environment)?

**Comment by knutov** [comment]
BORG_HOSTNAME_IS_UNIQUE is empty both in client and server side, I checked it.

**Comment by ThomasWaldmann** [comment]
What's also a bit strange is that the "wait forever for the cache lock" only happened when there is no repo lock, just a cache lock. So the repo was closed and unlocked in a somehow clean way, but not the clientside cache.

**Comment by ThomasWaldmann** [comment]
Host "nancy" runs a "normal" Linux?

**Comment by knutov** [comment]
Kind of. OpenVZ 6 which is Centos 6 with patches.

**Comment by ThomasWaldmann** [comment]
What does `kill -0 somenotexistingpid` result in in that environment?

**Comment by knutov** [comment]
```
root@nancy:~# ps aux | grep 123
root     26005  0.0  0.0  12916   952 pts/0    S+   01:50   0:00 grep --color=auto 123
root@nancy:~# kill -0 123
-bash: kill: (123) - No such process
```

**Comment by ThomasWaldmann** [comment]
ok, if it behaves the same from within borg (from cython), that should be ok.

what does this give for you there?:
```
# python (3 or 2)
>>> import sys
>>> sys.platform
```

**Comment by knutov** [comment]
```
root@nancy:~# python3
Python 3.4.3 (default, Nov 28 2017, 16:41:13)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'linux'
```

**Comment by ThomasWaldmann** [comment]
ok, good.

i tried the stale lock killer, it works for me. strange that it didn't work for you.

can you check if there were any messages in borg output relating to that (at the time when it had to kill the stale lock, but didn't)?

**Comment by ThomasWaldmann** [comment]
another python3 test (on host nancy in same env as borg):

```
import socket
socket.gethostname()
```

**Comment by knutov** [comment]
There are no messages untill I press ctrl+c as far as I remember.

stale lock killer works fine if it is repo lock, so the problem is about the cache locking I suppose.

**Comment by knutov** [comment]
```
root@nancy:~# python3
Python 3.4.3 (default, Nov 28 2017, 16:41:13)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostname()
'nancy'
```

There should not be any difference, I think. OpenVZ is something like lxc containers, and uses cgroups mostly the same way.

**Comment by ThomasWaldmann** [comment]
added some more code lines above, please try.

**Comment by knutov** [comment]
```
root@nancy:~# python3
Python 3.4.3 (default, Nov 28 2017, 16:41:13)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket, uuid
>>> name = socket.gethostname()
>>> uuid.getnode()
9898505997169
>>> socket.getaddrinfo(name, None, 0, socket.SOCK_DGRAM, 0, socket.AI_CANONNAME)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, 'nancy.dobrohost.ru', ('144.76.183.121', 0))]
```

**Comment by ThomasWaldmann** [comment]
looks as expected.

**Comment by knutov** [comment]
Numbers are different.

```
# reboot

root@nancy:~# uptime
 02:28:14 up 0 min,  1 user,  load average: 0.41, 0.10, 0.03
root@nancy:~# python3
Python 3.4.3 (default, Nov 28 2017, 16:41:13)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket, uuid
>>> name = socket.gethostname()
>>> uuid.getnode()
205614393461844
>>> socket.getaddrinfo(name, None, 0, socket.SOCK_DGRAM, 0, socket.AI_CANONNAME)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, 'nancy.dobrohost.ru', ('144.76.183.121', 0))]
```

**Comment by ThomasWaldmann** [comment]
OK, so that is the reason why the stale lock killer does not work for you. Or at least not crossing container restarts.

The nodeid is part of that (so it is not only fqdn, but also nodeid that must match to be considered "this host").

**Comment by ThomasWaldmann** [comment]
https://docs.python.org/3/library/uuid.html#uuid.getnode

so, is it your MAC address changing across a restart?

**Comment by knutov** [comment]
there were no reboots for containers for about 100+ days before.

There is no MAC address as far as I know, OpenVZ has special `venet` interface.

```
# ifconfig -a

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:16015 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18608 errors:0 dropped:12 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2623298 (2.6 MB)  TX bytes:19905213 (19.9 MB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:144.76.183.121  P-t-P:144.76.183.121  Bcast:144.76.183.121  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
```

**Comment by ThomasWaldmann** [comment]
hmm, no idea what uuid.getnode is doing then.

if you say it changes, it can't be always based on same all-zero "MAC".

**Comment by infectormp** [comment]
[uuid.getnode()](https://docs.python.org/2/library/uuid.html)
> If all attempts to obtain the hardware address fail, we choose a random 48-bit number with its eighth bit set to 1 as recommended in RFC 4122

Look like all-zero "MAC" interpreted by uuid.getnode() as fail to obtain ... and  uuid.getnode() generate a random 48-bit number every time with you call to uuid.getnode()

**Comment by ThomasWaldmann** [comment]
OK, so the main question before we go to dirty workarounds would be whether one can set some sort of unique mac address for that environment so that uuid.getnode returns a unique **and** stable node id.

What borg currently does is on the safe side: it thinks the lock is from another machine (due to the different nodeid part) and lets it alone. So, that is not a borg bug.

**Comment by knutov** [comment]
I checked and `uuid.getnode()` returns new value with any new python3 run.

mac address is possible to set with `veth` but not with `venet`. https://wiki.openvz.org/Differences_between_venet_and_veth

Also, with `kvm` and `lxc` there are different `venet` alternatives, without mac address too, as far as I remeber.

So, may be just use something else instead of `uuid.getnode()` ?

**Comment by ThomasWaldmann** [comment]
@knutov the problem is that we must be rather sure that the lock is really stale before automatically killing a lock. we can only be sure if we know that the lock is from localhost and we know that the process that created it is not alive any more. we can not do the "process is dead" check for remote hosts.

so the problem is to know that the lock is from local host. the lock has the fqdn. if that is unique, it is good enough. but if multiple hosts are named server.example.org it would be a problem, that is why we added the nodeid (derived from mac address, usually).

**Comment by ThomasWaldmann** [comment]
For borg 1.2 i could slightly change what behaviour BORG_HOSTNAME_IS_UNIQUE will trigger and add another BORG_MAC_IS_UNIQUE.

In < 1.2 setting BORG_HOSTNAME_IS_UNIQUE=no just disables stale lock killing.
In >= 1.2 it could mean that the fqdn won't get into the composite hostid (usually fqdn@nodeid).

In < 1.2 setting BORG_NODEID_IS_UNIQUE does not exist.
In >= 1.2 it could mean that the nodeid won't get into the composite hostid (usually fqdn@nodeid).

borg >= 1.2 would do stale lock killing as long as the composite hostid still has some information (so not both env vars are false).

**Comment by knutov** [comment]
btw, why change it only for borg 1.2? It could be safely changed for 1.1 for only openvz/lxc. (but it's ok if borg 1.2 will be released soon)

Also, in real world, I mean severs and pairs laptop-backup_server_over_ssh, hostname IS uniqe, so it should me default behavior, I think.

**Comment by ThomasWaldmann** [comment]
Yes, I know that the cache lock usually comes from localhost, but I'ld like to keep the locking code generic.

Also, borg does not have a config files yet (but uses commandline switches and env vars).

I try to avoid unexpected changes in a minor release (like 1.1.6 to 1.1.7), that's why change of behaviour has to wait for 1.2. Adding some stuff can be done, so e.g. we could add some BORG_MACHINE_ID env var that completely replaces building an id from hostname/nodeid and just uses whatever you have in there.

borg assumes that you have unique hostnames (that's why you need to set env var to "no" if it is otherwise), but the behaviour to add the nodeid and not rely just on the hostname is hardcoded in 1.1.

**Comment by knutov** [comment]
I understand your approach although this issue looks like a bug to me and changes are rather expected then not.

Anyway, adding BORG_MACHINE_ID to 1.1 line with keeping all as it is by default looks as a good solution for all without any side effects.

**Comment by ThomasWaldmann** [comment]
moved the TODO to #3985 and #3986.

bug here is fixed, the other stuff is not a bug in borg (but needs a workaround for problematic environments).

**Comment by knutov** [comment]
ok, thanks.

Still wonder, why do you rely on some uuids based on network settings, which are not constant in real life, instead of having pregenerated uuid (generated randomly or uuid from GPT table, if any, or something like that)?

**Comment by ThomasWaldmann** [comment]
Yeah, guess we could store an own uuid into .config/borg/uuid. But let's continue in the new ticket.

**Comment by ThomasWaldmann** [comment]
@knutov can you try #4006?

**Comment by ThomasWaldmann** [comment]
I am removing the "bug" label here, because the bug is rather that all-zero MAC address.

**Comment by ThomasWaldmann** [comment]
The change is in python code, so you don't need to compile.

**Comment by knutov** [comment]
I suppose it's working. Waiting for the 1.1.7 )

**Comment by knutov** [comment]
btw, do you have something like nightly builds from `master` ?

I tried to compile my own on ubuntu 16.04 (according to instructions from https://borgbackup.readthedocs.io/en/stable/installation.html#git-installation ) and it ended with
```
# cat /root/.pip/pip.log
Obtaining file:///root/borg
  Running setup.py (path:/root/borg/setup.py) egg_info for package from file:///root/borg
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in borgbackup setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

error in borgbackup setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```

**Comment by ThomasWaldmann** [comment]
sounds like your pip is too old to understand borg's setup.py.
