### ISSUE TITLE
chunk count differences

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#397]
Using borg 0.28.1, I built the following test scenario:

task 1
create a backup in a fresh repository
```
                       Unique chunks         Total chunks
Chunk index:                   69308                69813
```
task 2
create a backup of the same files in a fresh repository.
interrupted the backup process 4 times at different places using Ctrl-C and then started again
and finally i let the job finish
list shows me jobname.checkpoint, jobname.checkpoint.1 .. 3 and the jobname.
i deleted all .checkpoint* backups
i assumed that now the info will show me quite the same result as in task 1 or maybe a few chunks difference, but it has quite a big difference:
```
                       Unique chunks         Total chunks
Chunk index:                   69688                70139
```

what happened?

**Comment by ThomasWaldmann** [comment]
Quite big difference? 0.5%.

Your finding is interesting though, I can't easily explain the difference right now, so this would be something to investigate.

**Comment by ClipperS87** [comment]
As I understood only the last chunk maybe "unusable" after a interruption, and the next one then would be a plus 1 - so 4 times interrupting would result in 8 extra chunks. So 8 compared to 326 is quite a big difference in amount.
to investiogate further I run the same test with a smaller amount of data to be backupd up.
here are the results:

Command line: /usr/bin/borg create -vsp -c 5 -C lzma,9 test1::a test
Number of files: 12

                       Original size      Compressed size    Deduplicated size
This archive:              157.32 MB            156.20 MB            156.20 MB
All archives:              157.32 MB            156.20 MB            156.20 MB

                       Unique chunks         Total chunks
Chunk index:                    2289                 2289

with interupt/resume:
Command line: /usr/bin/borg create -vsp -c 5 -C lzma,9 test2::a test
Number of files: 12

                       Original size      Compressed size    Deduplicated size
This archive:              157.32 MB            156.21 MB            156.21 MB
All archives:              157.32 MB            156.21 MB            156.21 MB

                       Unique chunks         Total chunks
Chunk index:                    2301                 2301

with interrupt/resume and more checkpoints:
Command line: /usr/bin/borg create -v -c 2 -C lzma,9 test3::1 test
Number of files: 12

                       Original size      Compressed size    Deduplicated size
This archive:              157.32 MB            156.22 MB            156.22 MB
All archives:              157.32 MB            156.22 MB            156.22 MB

                       Unique chunks         Total chunks
Chunk index:                    2437                 2437


thats 6,5% more chunks!

**Comment by ThomasWaldmann** [comment]
Please always add the borgbackup version to your bug reports.

**Comment by ThomasWaldmann** [comment]
OK, i reproduced this - what I found is:
- when interrupting the backup, a checkpoint repository is left behind, interrupt it twice, 2 checkpoint archives.
- while the checkpoints and the final, completed backup archive share the data chunks, some metadata chunks might not deduplicate
- after deleting the checkpoint archives, the chunk count was only N+1 compared to the other repo.
- a `borg check --repair` fixed that chunk difference also, so both repos contained the same amount of chunks in the end.

So, it looks like everything behaves as expected.
