### ISSUE TITLE
Borg with cygwin

### ISSUE THREAD

**Issue by engelant** [borgbackup/borg#3975]
Are there currently any efforts of the borg collective to proviede ready to use packages of borg under windows with cygwin?

**Comment by ThomasWaldmann** [comment]
Not AFAIK. But feel free to do it, if you like!

**Comment by engelant** [comment]
Here you go, I need a wider set of testing
https://github.com/engelant/borg-cygwin

**Comment by ThomasWaldmann** [comment]
Cool, do a PR to link it from the community repo:

https://github.com/borgbackup/community

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/community/pull/25/files

ok, so as it is included there now, i think we can close the issue.
