### ISSUE TITLE
borg create -p does not show progress in 0.28.1

### ISSUE THREAD

**Issue by sergiocallegari** [borgbackup/borg#398]
With 0.27 one used to see progress information such as current file being backed up, current raw, compressed, unduplicated size, etc.

Now, on 0.28.1 I only see two messages:

```
reading files cache
processing files
```

and nothing else.

Thanks in advance for looking into it.

**Comment by ThomasWaldmann** [comment]
--progress is a toggle now and if you start borg from a terminal, it is on by default.

**Comment by sergiocallegari** [comment]
Clear now...

but please, rethink.  Having an option that acts as a toggle on something that is selected automatically based on whether your output is a terminal makes things unnecessarily complex for scripting.  For instance: how can a script assure that progress is always off, regardless of the output being a terminal or not? It needs to first determine itself if the output is a terminal and then decide whether to use --progress or not depending on that.

I think that having --progress and -p for "unconditionally switch on progress" and "--no-progress" for "unconditionally switch off progress" would be much easier.

**Comment by ThomasWaldmann** [comment]
@sergiocallegari usually I would agree, I also dislike magic behaviour. it is often causing troubles.

but for progress, isn't it doing now the right thing by default?
(except existing scripts where you want to remove --progress now)

**Comment by sergiocallegari** [comment]
Exactly... the new automatic default behavior is quite nice, but now it is difficult to reliably switch the progress display off in scripts. This is the reason for my suggestion for a --no-progress option to unconditionally switch off progress display. And if we get this, then --progress should probably be unconditional too "for simmetry".

**Comment by ThomasWaldmann** [comment]
@anarcat ^

**Comment by anarcat** [comment]
please test if #419 fixes the problem for you.
