### ISSUE TITLE
Broken Pipe (SSH): Break Lock

### ISSUE THREAD

**Issue by margau** [borgbackup/borg#3988]
Hello,
sometimes my SSH-Connection breaks, but the lock on the server is still active:
```
Remote: packet_write_wait: Connection to 84.x.x.x port 22: Broken pipe
Connection closed by remote host
```
If I try to restart, borg can't acquire the lock, I have to manually break it on the server.

My idea: When the Server (borg serve) notices the broken pipe, it automatically breaks the lock, because the client has obviously gone away.

Best regards 
margau

**Comment by ThomasWaldmann** [comment]
Before you break the lock, check if the borg serve process is still alive (and has the lock).

Also add your borg version to the top post.

**Comment by margau** [comment]
Borg Version is 1.1.6 - in my case, the SSH-Pipe breaks sometimes, but borg serve is still alive.
Something to automatically "heal" this case would be great.

**Comment by margau** [comment]
I have an hourly cronjob, it ran into problems until I manually ran break-lock. But since I updated to 1.1.6 (had the Debian version before) this didn't happen again.

**Comment by ThomasWaldmann** [comment]
@margau is the server-side ssh process also still running in such a case?

**Comment by margau** [comment]
Yes, that's what I meant with borg-serve. The client process exits in such a case with "broken pipe".

**Comment by ThomasWaldmann** [comment]
Well, borg serve's pipes (stdin/stdout/stderr) are connected to the sshd process on the server side. So if the sshd is still running, there is no broken pipe from borg's perspective.

**Comment by margau** [comment]
Would it be an Option to kill borg-serve if no data was received for 15 minutes?

**Comment by ThomasWaldmann** [comment]
Well, if the client is a bit on the slow side and needs a long time for some local computation without server communication, the server would kick it - not nice.

How about just using ssh's features for that kind of stuff?

**Comment by knutov** [comment]
It's not the solution when plug is off for some time, it's for the case when tcp connect was broken somehow but immediately new connect is possible to create.

Works perfect for sshfs for example.

**Comment by margau** [comment]
Hello, from Systemd I see the user session is gone:
`Jul 26 16:16:04 x systemd[1]: Stopping User Manager for UID 1003...
Jul 26 16:16:04 x systemd[64347]: Stopped target Default.
Jul 26 16:16:04 x systemd[64347]: Stopped target Basic System.
Jul 26 16:16:04 x systemd[64347]: Stopped target Sockets.
Jul 26 16:16:04 x systemd[64347]: Closed GnuPG cryptographic agent and passphrase cache.
Jul 26 16:16:04 x systemd[64347]: Closed GnuPG cryptographic agent (access for web browsers).
Jul 26 16:16:04 x systemd[64347]: Closed GnuPG network certificate management daemon.
Jul 26 16:16:04 x systemd[64347]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Jul 26 16:16:04 x systemd[64347]: Stopped target Paths.
Jul 26 16:16:04 x systemd[64347]: Stopped target Timers.
Jul 26 16:16:04 x systemd[64347]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Jul 26 16:16:04 x systemd[64347]: Reached target Shutdown.
Jul 26 16:16:04 x systemd[64347]: Starting Exit the Session...
Jul 26 16:16:04 x systemd[1]: Stopped User Manager for UID 1003.
`

But, under the same user, borg serve keeps running.
`SSH command line: ['ssh', '-p', '22', 'user@host', 'borg', 'serve', '--umask=077', '--debug']
` is the command which executes borg on the Remote Host.

I don't understand why borg serve didn't receive SIGINT when the user is gone. OS is Debian 9 default with SystemD.
Exception is `borg.remote.ConnectionClosed: Connection closed by remote host`

@knutov do you have documentation for `-o reconnect`? Can't find the option in man ssh or man ssh_config.

**Comment by ThomasWaldmann** [comment]
@knutov seems to be rather new option, ssh 7.6/7.7 does not know it.

**Comment by knutov** [comment]
oh, I'm sorry, it's my mistake, I googled and only sshfs has this option, not ssh itself.

**Comment by ThomasWaldmann** [comment]
@knutov yup, these are what I meant with "use ssh's features".

**Comment by ThomasWaldmann** [comment]
OK, so did someone try whether TCPKeepAlive, ServerAliveInterval, ServerAliveCountMax ssh options help?

I guess if the server process actively notices that the connection to the client is broken, the server will terminate, the pipe to borg serve will break and borg should terminate cleanly, unlocking the repo.

**Comment by mikenye** [comment]
I've had this issue. What appears to have solved it is to perform the following:

In the client's (the machine running `borg create`) `~/.ssh/config` file:
```
Host backupserver.fqdn
        User backupuser
        ServerAliveInterval 10
        ServerAliveCountMax 30
```

This will cause the client to send a keepalive to the server every 10 seconds. If 30 consecutive keepalives are sent without a response, the connection will be terminated.

In the server's (the machine running `borg serve`) `/etc/ssh/sshd_config` file:
```
ClientAliveInterval 10
ClientAliveCountMax 30
```

This will cause the server to send a keep alive to the client every 10 seconds. If 30 consecutive keepalives are sent without a response, the connection will be terminated.

If you then run your borg commands with `--lock-wait 600`, this gives sufficient time for the `borg serve` processes to exit after the SSH connection is torn down after the 300 second (5 minute) wait for the keepalives to fail.

So far (touch wood) this has solved the problem for me.

**Comment by mikenye** [comment]
The documentation has been updated, I think this issue can now be closed?

**Comment by ThomasWaldmann** [comment]
yup.
