### ISSUE TITLE
grotty errors displayed in built man pages

### ISSUE THREAD

**Issue by newtonne** [borgbackup/borg#3990]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.6

#### Operating system (distribution) and version.

MacOS 10.13.5 (High Sierra)

#### Hardware / network configuration, and filesystems used.

N/A

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

man borg

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

```
make man
cp _build/man/borg.1 <somewhere on manpath>
man borg
```

The above commands result in the following output at the bottom of the first man page:

```
:grotty:<standard input> (<standard input>):6996: character above first line discarded
grotty:<standard input> (<standard input>):7000: character above first line discarded
grotty:<standard input> (<standard input>):7004: character above first line discarded
grotty:<standard input> (<standard input>):7008: character above first line discarded
grotty:<standard input> (<standard input>):7012: character above first line discarded
```

Everything else looks OK, but if I scroll up I see the following output at the top which was initially hidden from view:

```
grotty:<standard input> (<standard input>):2254: character above first line discarded
grotty:<standard input> (<standard input>):2258: character above first line discarded
grotty:<standard input> (<standard input>):2262: character above first line discarded
```

I did a little investigation and it seems that 1ba0e85 introduced this bug, even though that change looks very innocuous. I don't know much about man pages or sphinx, but what I saw was that building the man pages prior to that change didn't result in these grotty errors.

#### Include any warning/errors/backtraces from the system logs

N/A

**Comment by ThomasWaldmann** [comment]
https://linux.die.net/man/1/grotty

**Comment by ThomasWaldmann** [comment]
Can this be reproduced on linux?

**Comment by newtonne** [comment]
I'll give it a go.

**Comment by newtonne** [comment]
I've done some more testing and believe it is actually the additional features table in `usage_general.rst.inc` that is messing things up.

Here's what that table looks like when it is read using `man`, which is what is shipped on the Mac:

<img width="447" alt="mac-screenshot" src="https://user-images.githubusercontent.com/14221622/43370017-90b08e7a-936f-11e8-9ade-729206bca7e3.png">

Here's what it looks like when read by `man-db`, which is what ships on most Linux distros:

<img width="446" alt="ubuntu-screenshot" src="https://user-images.githubusercontent.com/14221622/43370013-85fc0554-936f-11e8-89fe-39927c6e4d5b.png">

A few things to notice:

1. I don't see those `grotty` errors on Ubuntu, and I believe this to be because it uses `man-db`. After compiling `man-db` from source on macOS and using that to read the man page, I didn't see the issue there either.
2. The first table has a blank line above the OpenIndiana row. I couldn't figure out what is special about that row, but following the advice on this [StackOverflow answer](https://stackoverflow.com/questions/38253755/man-page-grotty-error-character-above-first-line-discarded#38273288) seems to fix this, and the issue I initially raised. Would you be willing to apply this fix?
3. The screenshots raise another issue, which is that since row and column spanning are not supported by `sphinx` (see warnings in output of `make man`), the information displayed in the above tables is incorrect when compared to the [online docs](https://borgbackup.readthedocs.io/en/stable/man_intro.html?highlight=xattr#support-for-file-metadata). I'll raise this as a separate issue.

**Comment by ThomasWaldmann** [comment]
Maybe this just needs re-checking after fixing #4000 - looks like it might be also fixed then.
