### ISSUE TITLE
borg reported "Time (start)", "Time (end)" and "Duration" are shorter than real

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#3993]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

(Minor) issue.

#### Your borg version (borg -V).
borg 1.1.6

#### Operating system (distribution) and version.
Debian 9. Using 64 bit release binary from borg.

#### Hardware / network configuration, and filesystems used.
The repo is on a remote, slow server, accessed with fuse.sshfs.

#### How much data is handled by borg?
0 byte in this backup (empty file for test). See the output below for the repo data.

## Describe the problem you're observing.

```
# time borg -V
borg 1.1.6

real    0m2,136s
user    0m1,812s
sys     0m0,316s
# touch /tmp/empty
# date -R ; time borg create -v --stats --show-rc --show-version --noatime --nobsdflags -C zstd,10 ::test /tmp/empty ; date -R
Fri, 27 Jul 2018 16:21:01 +0200
borgbackup version 1.1.6
------------------------------------------------------------------------------
Archive name: test
Archive fingerprint: 35dfbf1a8e451b9d5091d446d6512a606bd140316c70d08e475102212d0448b8
Time (start): Fri, 2018-07-27 16:21:43
Time (end):   Fri, 2018-07-27 16:23:05
Duration: 1 minutes 22.40 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  585 B                656 B                656 B
All archives:              274.70 TB            188.52 TB              1.76 TB

                       Unique chunks         Total chunks
Chunk index:                 3723435            524190694
------------------------------------------------------------------------------
terminating with success status, rc 0

real    4m35,563s
user    2m40,952s
sys     0m9,500s
Fri, 27 Jul 2018 16:25:37 +0200
```
As you can see I run: `date ; time borg create ... ; date`:
- Reported Time (start): is 42s later. It require 2s to extract the binary (as you can see in the time borg -V output I reported), so a bit of delay is expected. There are however 40s more than what expected.
- Reported Time (end): is 2m 32s before real end (compare with the second date).
- Reported Duration: is 3m 13s less than real duration (compare with time output or the difference between the two date).

**Comment by FabioPedretti** [comment]
Actually I only find now this was already documented:
- in the FAQ [here](https://borgbackup.readthedocs.io/en/stable/faq.html#why-is-the-time-elapsed-in-the-archive-stats-different-from-wall-clock-time);
- in issue #3301.

So I suppose it could actually be closed.

**Comment by FabioPedretti** [comment]
According to the above ticket OK for duration and end time (which should be better in 1.2 due to removing compaction), but it still is not clear why the start time is also 40s later.

**Comment by ThomasWaldmann** [comment]
I recent fixed another issue in time calculation caused by the lazy loading of the files cache.

So please check the git log / change log.

**Comment by FabioPedretti** [comment]
I found #3672, but it should already be in since 1.1.5, and I am on 1.1.6.
No big issue here anyway, if this issue is not useful for improving borg feel free to close.
Thanks.

**Comment by FabioPedretti** [comment]
As a workaround I run borg using /usr/bin/time:

`/usr/bin/time -f 'time: %e - cpu: %P - max mem: %MKB - I/O: %I/%O' borg ...`

(or use %E rather than %e for the time in hours:minutes:seconds format)

As a bonus it can record the time needed for every borg command (not just create), and also other interesting stats.

**Comment by ThomasWaldmann** [comment]
If this can still be reproduced on 1.2.x or master branch, please file a new ticket.
