### ISSUE TITLE
Incorrect information in man page additional features table

### ISSUE THREAD

**Issue by newtonne** [borgbackup/borg#4000]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.6

#### Operating system (distribution) and version.

MacOS 10.13.5 (High Sierra)

#### Hardware / network configuration, and filesystems used.

N/A

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`man borg`

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

`man borg`

During investigation of #3990, I discovered that `sphinx`'s lack of support for column and row spanning means that the information in the additional features table of the man page:

<img width="446" alt="ubuntu-screenshot" src="https://user-images.githubusercontent.com/14221622/43370204-dfb2df52-9372-11e8-8137-123c8d97d1a0.png">

does not match that in the online docs:

<img width="424" alt="online-docs-screenshot" src="https://user-images.githubusercontent.com/14221622/43370222-3282696e-9373-11e8-95ef-f3eae50fdac3.png">

#### Include any warning/errors/backtraces from the system logs

N/A

**Comment by ThomasWaldmann** [comment]
Guess the easiest way to fix is to have a single table row for "Solaris and derivates".

There does not need to be a version number for Solaris as we do not have them for other OSes either (and that does not mean we support all versions of the listed OSes).

@newtonne can you do a PR against master to fix this?

**Comment by newtonne** [comment]
Sure I can submit a PR, though I don't think your suggestion fixes the Flags column for the BSDs. 

Would you like me to remove all instances of column and row-spanning so that the content of each cell is explicitly defined? That would fix the issue, though it would remove the spanning from the online docs as I believe they are built from the same source.

**Comment by ThomasWaldmann** [comment]
yes, remove all the spanning and explicitly state the value for each row.

keep freebsd, openbsd, netbsd separate (as they have different properties / we have different code).

unify solaris and openindiana (same properties / we have same code).

**Comment by ThomasWaldmann** [comment]
Note: this is one of the last things to do for the upcoming 1.1.7 release - would be nice to have it fixed soon.

**Comment by newtonne** [comment]
No worries. I should have time to do this later today.
