### ISSUE TITLE
Mosh support?

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#4002]
Already mentioned in https://github.com/borgbackup/borg/issues/1171#issuecomment-226271124, but let's make a separate issue for that.

I have not tested it yet, but let's check whether [Mosh](https://mosh.org/) works with borg and, if so, if there are any disadvantages specific to borg or so.

**Comment by RonnyPfannschmidt** [comment]
@rugk mosh is about terminal sessions, which is very explicitly not what brog needs -so how would that make sense

**Comment by rugk** [comment]
The main goal would be to prevent accidential closes. In https://github.com/borgbackup/borg/issues/1171#issuecomment-226271124 @enkore said:
> mosh may even be compatible with borg.

So...

**Comment by ThomasWaldmann** [comment]
I had a look at mosh's documented features (website, presentation about it on yt) and it does not look like implementing streams like we need it, but rather a screen (or keyboard sequence) state synchronisation protocol.

So unless proven otherwise, I assume mosh can not be used for borg.
