### ISSUE TITLE
use fine-grained locks

### ISSUE THREAD

**Issue by pille** [borgbackup/borg#4004]
it would be nice to evaluate all locks and fine-tune them.
maybe different actions hold different locks resulting in actions being able to be done at the same time.
the most basic approach would be read/write which may allow for ```list``` or ```info``` actions during a running ```create```. this would also create the need to handle incomplete data. e.g. the running backup should be ignored. it would be a good idea to state that one is currently running, though.

maybe it's possible to make long-runnig tasks like a ```check``` non-blocking.

**Comment by ThomasWaldmann** [comment]
well, doing a (full) `check` while things are changing doesn't sound like doable / advisable (and especially not `check --repair`).

**Comment by pille** [comment]
i don't know the details, but old data-blocks should not change. at least not in append-only mode.
it's perfectly fine to skip new blocks. ```check --repair``` clearly is out of scope, as it's not read-only.
