### ISSUE TITLE
create -p -v shows unexpected result

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#401]
-p works as expected
-v works as expected

in combination it shows:
$ borg create -vp -C lzma,9 test3::a test
M test/140819224008000.jpg7.51 kB D test/140819224008000.jpg
M test/140819224141001.jpg1.01 MB D test/140819224141001.jpg

**Comment by ThomasWaldmann** [comment]
as -v outputs a long (scrolling) list and -p outputs stuff that is expected to stay at one place, this is expected and can't be fixed without introducing a far more elaborate UI.
So, just  don't use them together.

**Comment by ClipperS87** [comment]
>>So, just don't use them together
I'd appricate to find a note about this in the .docs
