### ISSUE TITLE
Cancel backup while it's running, could it corrupt the repo?

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#4015]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## Describe the problem you're observing.
Not a problem, just a question:

When you force-quite borg while it's in the middle of creating a backup, could the backup repository get corrupted or is the process somehow transactional (meaning cancelling won't affect the repo at all)?

**Comment by ThomasWaldmann** [comment]
It is transactional. If you cancel before stuff is committed, there will be uncommitted data after the last commit and borg will clean that up next time it uses the repo.

**Comment by fullofcaffeine** [comment]
Thanks!
