### ISSUE TITLE
create -v documentation

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#402]
I am unsure what the prefix mean:

M - modified
U - unchanged
d - directory
A -?

**Comment by ThomasWaldmann** [comment]
Yes, that is still missing from the docs. I just used ad-hoc letters. Maybe we could review the letters and use same as `ls -l` outputs?

See return / status values there:
https://github.com/borgbackup/borg/blob/master/borg/archive.py#L457

See comment there:
https://github.com/borgbackup/borg/blob/master/borg/archiver.py#L248

**Comment by ClipperS87** [comment]
mmh. 
i repeated to add the same unchanged/untouched directory like 
create ..repo::a then create... samerepo:b
but the last file always gets the "A"
...so there must be a bug...

**Comment by ThomasWaldmann** [comment]
Please create a separate issue for that (try to create a minimal, reproducable case for that and don't forget to give the borgbackup version).
