### ISSUE TITLE
Passphrase as switch flag? avoiding interactivity

### ISSUE THREAD

**Issue by BarbzYHOOL** [borgbackup/borg#4028]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

How can I avoid the interactive part of "borg init -e repokey" or anytime it asks for the passphrase? Can I pass it as a file?

Trying to automate installation on several virtual machines without having to do everything manually, else I'll be forced to NOT encrypt :(

**Comment by ThomasWaldmann** [comment]
Use:

export BORG_PASSPHRASE=yourpassphrase

**Comment by infectormp** [comment]
@BarbzYHOOL https://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups

**Comment by BarbzYHOOL** [comment]
ok thank you (but I don't like using environment variables)
