### ISSUE TITLE
borg extract and absolute pathes

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4029]
when using `borg create`, the leading slash of absolute pathes is automatically removed from items when they are written into an archive.

otoh, when using `borg extract repo::archive /some/path`, borg extract tries to match exactly what was given on the command line. And because the archive has no absolute paths in it, it fails with "nothing matched".

Check whether we should automatically remove leading slashes for `borg extract` (and some other commands that do path matching) also.

**Comment by ThomasWaldmann** [comment]
see also #2763

**Comment by milkey-mouse** [comment]
Crazy idea: `borg info` shows the original command line arguments that created the backup. We could try to re-parse those args at least well enough to get the original path and see if it started with a slash, then use that to inform `borg extract` & friends.
