### ISSUE TITLE
Can't use some characters in passphrase

### ISSUE THREAD

**Issue by BarbzYHOOL** [borgbackup/borg#4038]
## Have you checked borgbackup docs, FAQ, and open Github issues?

No

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.6

#### Operating system (distribution) and version.

deb9

## Describe the problem you're observing.

So I create the repository using Ansible and if I put a "é" in my passphrase, it doesn't work (well I won't pass the ansible error I guess). So I tried to create the repository manually with the same passphrase and it worked but displayed this

```Your passphrase (UTF-8 encoding in hex): 74657374c3a920c3a9
As you have a non-ASCII passphrase, it is recommended to keep the UTF-8 encoding in hex together with the passphrase at a safe place.
```

I don't really understand what it means and what should I do about that issue with Ansible (besides using a different character)

**Comment by ThomasWaldmann** [comment]
You can use any characters you like with borg passphrases, but if you shoot yourself in the foot by doing this, it's not borg's or borg developer's problem.

The non-ascii warning you get is just for your own safety. To access the repo, you must have the key and the passphrase (to be precise: the exact same bytes for the utf-8 encoding of the passphrase).

For some non-ascii chars, there might be different ways to produce them, e.g. by composing an accented char from accent+char (or having different sorts of spaces, or having similar-looking characters, or ...).

For successfully decrypting the key, it is important to be able to reproduce the exact same bytes and that is why it shows you these bytes.

solving ansible problems is not on-topic here.

you can just choose a pure ascii passphrase to avoid any issues.

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/init.html#description

> Be careful with special or non-ascii characters in your passphrase:
> 
> - Borg processes the passphrase as unicode (and encodes it as utf-8), so it does not have problems dealing with even the strangest characters.
> -  BUT: that does not necessarily apply to your OS / VM / keyboard configuration.

> So better use a long passphrase made from simple ascii chars than one that includes non-ascii stuff or characters that are hard/impossible to enter on a different keyboard layout.

**Comment by BarbzYHOOL** [comment]
Yes, I had read this and that's why I remembered it but I had no idea "é" was not a simple char. I still don't understand any of the explanation but fine, I removed this character...

**Comment by infectormp** [comment]
"e" is a simple char, "é" = unicode.
