### ISSUE TITLE
Dependency on attic?

### ISSUE THREAD

**Issue by Whissi** [borgbackup/borg#404]
Hi,

I am trying to bring *borg backup* to Gentoo Linux. I followed https://github.com/borgbackup/borg/blob/master/docs/development.rst to create the ebuild. But when I run the testsuite using *tox* the testsuite wants to pull in *attic*.

Does *borg* really depend on *attic*? Is the documentation still valid? Is *tox* still the recommended way to run the testsuite?

Thanks!

**Comment by ThomasWaldmann** [comment]
It's just for the "borg upgrade" tests, which can migrate a attic repo to borg.

**Comment by anarcat** [comment]
i confirm what @ThomasWaldmann says here. i think this can be closed.
