### ISSUE TITLE
building binaries on debian stretch, broken libb2

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4046]
Due to #4045, I just realized that stretch has the broken libb2 still.

Thus, if we build binaries on stretch (see master branch, upcoming 1.2 release) they would run into that issue, except if we switch to using the bundled blake2 reference implementation code.

That would somehow specialcase the build on debian stretch, requiring a different setup.py there as on the other build platforms (assuming they have a non-broken libb2).

**Comment by LocutusOfBorg** [comment]
stable-bpo    0.97+git20171226-2~bpo9+1 

what is the problem of using libb2 from stretch-backports?

**Comment by ThomasWaldmann** [comment]
yeah could pull that from bpo for the fat binary building.

doesn't solve it for people building from src on stretch and not being aware of the broken libb2, though.

**Comment by ThomasWaldmann** [comment]
the fixed package now also is in stretch-proposed-updates (and likely will be in next point-release of stretch).

**Comment by LocutusOfBorg** [comment]
I think it should have landed last week
https://www.debian.org/releases/stable/

**Comment by ThomasWaldmann** [comment]
https://packages.debian.org/stretch/libb2-1 still looks like the unfixed one.

**Comment by LocutusOfBorg** [comment]
I think it is ongoing right now...

**Comment by LocutusOfBorg** [comment]
wait for debian 9.8, it will contain it!

**Comment by ThomasWaldmann** [comment]
BTW, libb2 recently added pkg-config support (in 0.98.1) and soon that will be used by borg (master branch) to detect and locate libs/headers, see #4437.

**Comment by ThomasWaldmann** [comment]
And as there is no pkg-config support in libb2 < 0.98.1, borg will not automatically find libb2, even if installed.

It will then used the internal (non-broken) code. This closes this issues.

It still would be nice to have a fixed libb2 everywhere preferably a fresh one with pkg-config support.

**Comment by LocutusOfBorg** [comment]
@ThomasWaldmann just to clarify, I did upload libb2 0.98.1 in unstable, and asked for a freeze exception, and it went into testing some days ago (I should give a beer to somebody in Release Team!)

I'm backporting to stretch-backports right now, and Ubuntu already has it too.

So, stretch-backports is fine, buster is fine, ubuntu 19.04 is fine, and my ppa will be updated by the end of today!

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg Cool, thanks!
