### ISSUE TITLE
User-defined datetime format_spec

### ISSUE THREAD

**Issue by audeoudh** [borgbackup/borg#4055]
My use-case is to print from CLI the date of the archives, with the format "YYYY-MM-DD".  This format is (as far as I see) not supported currently.  However, I think it can be as simple as using a format specifier when printing the date : `borg  list --format '{time:%Y-%m-%d}{NL}'`. 

If I understand correctly the code, the format mechanism is in `src/borg/helpers/time.py`:

```python
class OutputTimestamp:
    def __init__(self, ts: datetime):
        if ts.tzinfo == timezone.utc:
            ts = to_localtime(ts)
        self.ts = ts


    def __format__(self, format_spec):
        return format_time(self.ts)


    def __str__(self):
        return '{}'.format(self)


    def isoformat(self):
        return isoformat_time(self.ts)


    to_json = isoformat
```

The method `__format__` receive the argument `format_spec`, which, in my use case, is `"%Y-%m-%d"`.  The formatting is done by the package `datetime` itself, and would support this `format_spec`:

```python
def format_time(ts: datetime):
    """
    Convert *ts* to a human-friendly format with textual weekday.
    """
    return ts.strftime('%a, %Y-%m-%d %H:%M:%S')
```

Does something makes impossible to forward the argument `format_spec` of the function `__format__` as first argument of the function `strftime`?  We can imagine to keep `"%a, %Y-%m-%d %H:%M:%S"` as default value.

**Comment by ThomasWaldmann** [comment]
Note sure what the problem is:
```
$ borg list repo
backupname     Wed, 2018-08-15 18:13:38 [4ecce...da06a6e]
#                   ^^^^^^^^^^ there it is.
```

**Comment by audeoudh** [comment]
Correct.  But to pipe it in another script which accept only the date (year + month + day) of the archives, `borg list repo | sed -n 's/.*\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\).*/\1-\2-\3/p'` is not that beautiful.

OK, it is even ugly.  One can indeed use a better approach, by pre-selecting the date in `borg list`:

```bash
$ borg list repo --format '{time}{NL}'
Wed, 2018-08-15 18:13:38
```

Hum…  A little more parsing:

```bash
$ borg list repo --format '{time}{NL}' | cut -f2 -d' '
2018-08-15
```

This one is correct, and not so ugly.  However, wouldn't `borg list repo --format '{time:%Y-%m-%d}{NL}'` be even nicer?

**Comment by ThomasWaldmann** [comment]
Sure, just thought whether it is worth the effort.

**Comment by enkore** [comment]
> `borg list --format '{time:%Y-%m-%d}{NL}'`

Actually that happens by-default if you feed a `datetime` object into new-style format (try `import datetime; '{:%Y-%m-%d}'.format(datetime.datetime.now())` in your python shell). Borg just prevents that behaviour from happening.

**Comment by audeoudh** [comment]
Hum…  Yep, sure…  That's exactly because Borg prevents that behaviour that I raised that issue.

**Comment by RonnyPfannschmidt** [comment]
i believe all thats needed is a small wrapper class that ensures borg uses the default datetime format for borg instead of the default for python, that way the "time" object could still be formatted

**Comment by audeoudh** [comment]
A wrapper class seems unnecessary for me.  A simple default argument should be sufficient.  What about audeoudh/borg@5957d71357?
