### ISSUE TITLE
Possible to prune archive without first rebuilding cache?

### ISSUE THREAD

**Issue by Zerophase** [borgbackup/borg#4057]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. I haven't seen anything relevant to this, other than the workaround for the cache. Want to make sure that is at least the best option, which doesn't threaten already stored data before attempting to resolve my issue.

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION.

#### Your borg version (borg -V).
borg 1.1.6

#### Operating system (distribution) and version.
Arch Linux x86_64

#### Hardware / network configuration, and filesystems used.
Kernel: 4.17.11-6-ck-ck
Shell: zsh 5.5.1
DE: Cinnamon 3.8.8
WM: Mutter (Muffin)
CPU: Intel i7-5960X (16) @ 4.5GHz
GPU: NVIDIA GeForce GTX 660 Ti
Memory: 3306MiB / 128753MiB

filesystems backed up: vfat, ext4 (on NVME)
backup to: ext4 (On HDD)
#### How much data is handled by borg?
391.1 GB used
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg prune -v --list "$REPO" --keep-hourly=24 --keep-daily=7 --keep-weekly=4 --keep-monthly=12

Also applies to any command relating to backing up.

## Describe the problem you're observing.
Starting today I noticed the cache used by borg ballooning to 6.5 gigs in size, quickly, taking up the last 22% of my root partition. For the past couple months I've had some errors in the backup process for one particular directory; but, this didn't seem to cause any issue with the backups being stored successfully. I now believe this might have caused my backup script to skip the pruning step. (can't be certain as I didn't notice unusually large disk usage till now)

Clearing borg's cache fixes my disk usage problem, but borg still balloons the cache to an unreasonable size when I try to prune manually. Is there anyway to prune without first rebuilding the cache that won't threaten the integrity of the data already stored by borg?

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#the-borg-cache-eats-way-too-much-disk-space-what-can-i-do
