### ISSUE TITLE
Extract all newest files from directory

### ISSUE THREAD

**Issue by Netmage-76** [borgbackup/borg#4058]
Hi,

I use borg 1.1.5 on Ubuntu 18.04 since a couple of month and I am happy with it, but I am not able to find any solution for my current problem. Maybe someone have a better way than I found. Unfortunately I didn't find any good solution in the internet or in the document.

Ususally I create a backup every couple of days. Today I unfortunatly deleted all files in one directory where I stored all my self-created shell scripts. The files are backuped in multiple archives like

> Archive 1 ---> file1-version1
> Achive 2 ---> file2-version1
> Achive 3 ---> file3-version1, file4-version1, file1-version2
> Achive 4 ---> file2-version2, file1-version3
> ...
> Achive 40 ---> file160-version1, file3-version2
> ...

Now I need to simply restore all files (found within all the archives) in the newest version to the directory. I already found the option "borg mount -o versions" where I can see all files (and file versions) in all archives, but manually copy the newest version back to the original directory costs me weeks of work.

I would love to see a borg command like: 
`borg extract --newest /path/to/repo::ANY home/username/extra/scripts/`

Does anyone have an idea to solve the problem in a simple way.

BR

**Comment by ThomasWaldmann** [comment]
Not sure whether I understand you correctly:

borg always does a **full backup** of the state of the backed up files at the time of the backup.

so, if you just want the latest state back, just use the latest backup.

**Comment by Netmage-76** [comment]
Hello ThomasWaldmann,

thank you for your fast reply. 

I also thought that borg does a full backup, but I tried to extract the files from a directory and the files were not available.

What I did was:

```
borg list /media/<borg data>
Enter passphrase for key /media/<borg data>:
201805022226_abc Wed, 2018-05-02 22:26:51 [xyz]
201805060027_abc Sun, 2018-05-06 00:28:20 [xzy]
201805060104_abc Sun, 2018-05-06 01:04:53 [yxz]
201805061243_abc Sun, 2018-05-06 12:43:42 [yzx]
...
```
```
borg extract /media/<borg data>::201805022226_abc /home/<user>/<path>/<path>/<path>/shell
Enter passphrase for key /media/<borg data>:
Include pattern '/home/<user>/<path>/<path>/<path>/shell' never matched.
```

When I mount the files with borg mount I am able to see that the files are available in a complete other archive (at the path I used before). This is the reason why I finally thought that borg does not do a full backup. Did I missinterpret something ?

BR

**Comment by ThomasWaldmann** [comment]
You must not give the leading slash when extracting files or dirs, see also output of `borg list`, it is not there either.

**Comment by Netmage-76** [comment]
Hello ThomasWaldmann,

you are right. I completely missinterpreted it. I even remember now that I had the leading slash problem in the past... thank you very very much for your help.

BR
