### ISSUE TITLE
check repository on smbfs / cifs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4059]
the question is whether #4056 was just a broken samba server (or smbfs/cifs client) or whether we have a problem in general with that.

So, try if that works:
```
# have a smbfs/cifs filesystem mounted on /mnt/smb, then:
borg init -e repokey /mnt/smb/repo
borg create /mnt/smb/repo::archive somefiles
```

If you tested it, post the outcome and also add OS/platform and smb client and server version info.

**Comment by matt-h** [comment]
I just did a test on a samba server and it worked just fine.

```
$ borg init -e repokey /mnt/smb/testing/testborg
nter new passphrase:
Enter same passphrase again:
Do you want your passphrase to be displayed for verification? [yN]: y
Your passphrase (between double-quotes): "test123"
Make sure the passphrase displayed above is exactly what you wanted.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /mnt/smb/testing/testborg

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.
```
```
$ borg create /mnt/smb/testing/testborg::testarchive git/testfiles
Enter passphrase for key /mnt/smb/testing/testborg:
```
```
$ borg list /mnt/smb/testing/testborg
Enter passphrase for key /mnt/smb/testing/testborg:
testarchive                          Mon, 2018-08-27 11:45:02 [c1f48620712130ddcd47e7c16a2c973599f2651125d62999f216210287b08c82]
```

### Client
```
$ uname -rv
4.18.3-arch1-1-ARCH #1 SMP PREEMPT Sat Aug 18 09:22:54 UTC 2018
```
```
$ borg --version
borg 1.1.6
```
Mounted using cifs

cifs-utils version 6.8

```
$ mount | grep smb
//servername/sambashare on /mnt/smb type cifs (rw,relatime,vers=default,cache=strict,username=matt,domain=,uid=1000,forceuid,gid=100,forcegid,addr=10.10.10.2,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
```

### Server
```
$ uname -rv
4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018
```

Samba version 4.8.3

**Comment by ThomasWaldmann** [comment]
Thanks for testing!

More testing results (failing or successful) using other samba / smbfs / cifs versions would be interesting.

**Comment by xunzi** [comment]
I am backing up a rootserver on a cifs-mounted Hetzner Storage Box, not sure what server software is powering these but probably not Windows due to licensing costs. Creating a repo, backing up and restoring data all work fine.
```
~% uname -rv
4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018
~% apt show cifs-utils
Package: cifs-utils
Version: 2:6.8-1 [...]
~% borg --version
borg 1.1.5
mount -v |grep cifs
//xxx.your-storagebox.de/backup on /xxx type cifs (rw,relatime,vers=default,cache=strict,username=xxx,domain=,uid=0,forceuid,gid=0,forcegid,addr=xxx,file_mode=0660,dir_mode=0770,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
```

**Comment by papanito** [comment]
I have connected a disk to my router (provider specific) which shares the disk via smb. I am facing #4839

**Comment by fantasya-pbem** [comment]
I successfully tested BorgBackup 1.1.11 on Linux Mint 19.3 Tricia using ``cifs-utils 2:6.8-1``, mounted with:
``//192.168.178.28/BORGTEST on /mnt/borgtest type cifs (rw,relatime,vers=2.1,cache=strict,uid=0,noforceuid,gid=0,noforcegid,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=1)``
Kernel: ``5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020``
SMB server is a local Windows 7 32bit VirtualBox VM.

**Comment by ThomasWaldmann** [comment]
done.
