### ISSUE TITLE
dependency on pkg_resources?

### ISSUE THREAD

**Issue by LocutusOfBorg** [borgbackup/borg#406]
Hi, I tried to install borg in a clean environment:

```
$ borgbackup 
Traceback (most recent call last):
  File "/usr/bin/borgbackup", line 5, in <module>
    from pkg_resources import load_entry_point
```

maybe pkg_resources is a needed runtime depencency?
```
cat /usr/bin/borgbackup 
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'borgbackup==0.28.1','console_scripts','borg'
__requires__ = 'borgbackup==0.28.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('borgbackup==0.28.1', 'console_scripts', 'borg')()
    )
```

**Comment by anarcat** [comment]
odd. how did you install it? this is stuff that setuptools would configure for you... but it does look like that is a runtime depends...

assuming this is the debian package here: in a similar Debian package (monkeysign), i had to explicitely add the pkg_resource dependency. so maybe that's a depends that is missing from the package.

if you install with pip, it will set that up for you.

**Comment by ThomasWaldmann** [comment]
The traceback is incomplete, please post a complete one.

**Comment by LocutusOfBorg** [comment]
@anarcat I'm the DD maintaining this package in debian :) and yes, I already added it as runtime dependency, but I'm wondering who does need it. if it is added because of setuptools I would expect python3:Depends to do the job, otherwise I would expect it on install_requires keyword.

@ThomasWaldmann this is what is printed when I try to run, I'm not sure what else I can provide.

Of course adding python3-pkg-resource to runtime dependencies fixed the issue
https://packages.qa.debian.org/b/borgbackup/news/20151113T130422Z.html

**Comment by RonnyPfannschmidt** [comment]
@LocutusOfBorg this is a artifact enforced by easy-install, one needs use recent pip for installation to avoid that legacy

**Comment by LocutusOfBorg** [comment]
thanks! but we don't use pip in Debian....

**Comment by LocutusOfBorg** [comment]
https://buildd.debian.org/status/package.php?p=borgbackup&suite=unstable

**Comment by RonnyPfannschmidt** [comment]
@LocutusOfBorg then make a tool to generate entry point scripts and use that instead of the hell made by setuptools ...

**Comment by anarcat** [comment]
@LocutusOfBorg nice - looks like all builds are passing! good job. :)

so just adding pkg-resource as a dependency was enough here - i'll close this issue then, because it does not affect pip-based production installs i believe just debian, and that is fixed in `debian/control`...

reopen if that's wrong.

**Comment by LocutusOfBorg** [comment]
well seems that I can't reopen because I don't have the button to click, but I don't need to. I have to blame some other python module for this problem :)
not a borg fault.

**Comment by anarcat** [comment]
thanks for the feedback!
