### ISSUE TITLE
borg create error: unrecognized arguments: --json

### ISSUE THREAD

**Issue by altzone** [borgbackup/borg#4061]
Hello,
I have a problem using borg create with the json option

the exit of borg is as follows:

```borg: error: unrecognized arguments: --json```

here is the complete command line:

`/usr/bin/borg create --stats --json --compression lz4 --exclude /proc --exclude /dev --exclude /sys --exclude /tmp --exclude /run --exclude /var/run --exclude /lost+found --exclude /var/cache/apt/archives --exclude /var/lib/mysql --exclude /var/lib/lxcfs  ssh://back@10.10.0.50/data0/backup/box1/backup::backup_2018-08-28_14:48:34 /`

I do not think I'm wrong, I read the doc again.

I use version 1.1.7 client and server side
Do you have an idea?

Thanks a lot

**Comment by altzone** [comment]
Hi Thomas,
I already try --log-json but same problem:
``` borg: error: unrecognized arguments: --log-json```

**Comment by ThomasWaldmann** [comment]
And `/usr/bin/borg -V` tells 1.1.7 on that machine?

**Comment by ThomasWaldmann** [comment]
I just tried `borg create --json repo::arch src` and it worked for me.

**Comment by ThomasWaldmann** [comment]
Also, `borg create --list --log-json repo::arch src` works for me.

**Comment by ThomasWaldmann** [comment]
Do you maybe have different borg versions on your machine? The json stuff is new in 1.1.x, 1.0.x did not have that yet.
