### ISSUE TITLE
STDIN overrides new unknown repository check -> Error

### ISSUE THREAD

**Issue by ethchest** [borgbackup/borg#4062]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue and Question

## System information. For client/server mode post info for both machines.

Client: Lenovo x230 with Ubuntu 16.04.5 and 16 GB RAM, on 1 TB SSD
Server: Hyper-V VM running Ubuntu 16.04.5 Server with 4 GB RAM allocated, but running on a Xeon X3430 with no cpu restrictions and ecc ram

#### Your borg version (borg -V).

1.1.7

#### Hardware / network configuration, and filesystems used.

Connected by 100 Mbit internal network, both ext4 file systems.

#### How much data is handled by borg?

In this new repository, none yet.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`dd if=/dev/sda1 count=$HEADER_SIZE | borg create user@hostip:/home/user/backupw::x230winimage -`

## Describe the problem you're observing.

After a successful backp of /home, I wanted to do a separate repo of windows stuff, and do a full disk image for that. As the script given in the documentation is too wonky imo to just run on its own (espcially as sfdisk doesn't know about gpt) I just wanted to run a small test with it, in this case on the EFI partition. (another question would be why the docs dd the header separately - shouldn't this be covered by `if=/dev/sdxN`?
Anyway, after the commandline above, I borg errored out with the following error:

```
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4434, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4366, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 143, in wrapper
    assert_secure(repository, kwargs['manifest'], self.lock_wait)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 206, in assert_secure
    sm.assert_secure(manifest, manifest.key, lock_wait=lock_wait)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 165, in assert_secure
    self.assert_access_unknown(warn_if_unencrypted, manifest, key)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 193, in assert_access_unknown
    retry=False, env_var_override='BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK')
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1367, in yes
    answer = input()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 0: invalid continuation byte

Platform: Linux hostname 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.1.7  Python: CPython 3.5.2
PID: 1668  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'create', 'remoteuser@hostip:/home/user/backupw::x230winimage', '-']
SSH_ORIGINAL_COMMAND: None

```

Obviously this seems to be because of the new repository check being denied by the STDIN. Is this to be expected/what would a way around that? Ideally, I think STDIN should either not mess with that prompt or there should be a better way to handle this, maybe an option for STDIN that give a warning but doesn't show the prompt? Interestingly, before that prompt, the ssh password/passphrase is prompted for - and that is not interfered with.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Can be reproduced by just running it again.

**Comment by ThomasWaldmann** [comment]
you need to make sure it does not have to ask questions as you can't answer them if stdin is used for data transfer.

in your case, you can see in the traceback that it wants to ask about `BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK`.

you can either do the first run without input redirection and manually answer or use that environment variable, see also the docs.

**Comment by ethchest** [comment]
Thanks. I didn't really know how to do a run without input redirection without using superfluous data, but I should have realized to use the environment variable.
Still, I would like to improve the docs for disk images. So do you know why there is this complicated script in the docs and it backs up the header separately? In my use of dd, just specifying the device always backed up the whole device, including the header.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/deployment/image-backup.html#using-ntfsclone-ntfs-i-e-windows-vms

guess you mean that with "complicated script".

it's like it is because it cares for backup of a disk with MBR partition table, potentially stuff after the mbr (could be some boot loader), and potentially multiple (ntfs or other) partitions.

all that stuff is backed up separately, so it could be restored separately also.
for ntfs partitions, it uses ntfsclone to efficiently create backup data.
for other partitions, it just does a sector-by-sector backup.

it you only have 1 partition (or no partition table at all) and you don't need to identify partitions for ntfsclone, you can use a simpler script, of course.

**Comment by ethchest** [comment]
I don't mind the script being there, but as the primary example about disk image backup, I think you could start with something simpler. (like you said and as I got from the script)  I would be happy to submit a PR.  Of course I exaggerated with 'complicated script' but for a simple case it is way too complicated, assumes that I am running as root and might not work with GPT. (as sfdisk says it doesn't support gpt)
Additionally, I would like to know if borg handles updates to disk images, or if it is somehow possible to protect a disk image from updates. By this I mean that from the docs it is not clear to me if a `borg create` from the same device would actually produce a new, usable image or if it would mess up the data and I would have to delete the archive and then redo it. I know that borg doesn't care much about files, but still I am not sure if/how this would work and it is not mentioned in the docs. By 'protecting' I mean a warning or a flag that could be set against accidentally writing file or additional stdin data to an existing disk image, as it would probably render the data unusable, as I understand it. (unless maybe extracting everything, and then manually truncating the additional file(s) from the disk data. I am happy to be wrong and then please correct me, but still maybe the docs could be clarified.

**Comment by ThomasWaldmann** [comment]
Maybe just move the zerofree example to above the ntfsclone example?

And add a even simpler "full disk, don't care" above that one.

Pull requests (against master) welcome.

You can do your image backups as often as you want and each backup will logically be a full, independent backup. Borg will read the whole device contents again, chunk and hash them again and process/store any new chunks (and won't process/store any already existing chunks if they already exists in the repo - in that case it will just refer to the existing chunk).

You can not write to an existing archive, try it, borg will just reject it.

**Comment by ethchest** [comment]
Sounds good. Thanks for the clarifications. Somehow I was under the impression that you could 'update' an archive, similarly to how you can resume it.

One thing I noticed - the stdin backup is finished now - is the difference between the reported (real) size during backup and the one reported by `borg info`. The reported size while running the backup was between around 500 GB, which is correct. But when doing `borg info` after, I got:

```

Time (start): Thu, 2018-08-30 08:02:25
Time (end): Thu, 2018-08-30 22:49:30
Duration: 14 hours 47 minutes 4.90 seconds
Number of files: 31
Command line: /usr/bin/borg create -pv user@hostip:/home/ruser/backupw::x230winimage-sda3 -
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.02 TB            834.50 GB            391.63 GB
All archives:                1.02 TB            834.50 GB            391.63 GB

                       Unique chunks         Total chunks
Chunk index:                  178816               384950

```

So, while my whole disk is 1 TB, why does borgbackup think that the whole diskimage was 1 TB? (during the run the number for the total and also the compressed size were correct.)

**Comment by ThomasWaldmann** [comment]
There is an open issue about size inconsistencies, it is like that (a cosmetic error).

**Comment by ethchest** [comment]
Ok thanks.
