### ISSUE TITLE
Borg: delete oldest incremental backups when capacity threshold is reached

### ISSUE THREAD

**Issue by nickpapadonis** [borgbackup/borg#4064]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.1.7

#### Operating system (distribution) and version.
Mac OSX

#### Hardware / network configuration, and filesystems used.
Local

#### How much data is handled by borg?
Testing

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
None yet

## Describe the problem you're observing.
This is a question.  Is it possible for borg backup to delete the oldest incremental backups when capacity threshold is reached.  I suspect this may be invocation of 'df .' or alternate script (for those use automation with Google Drive gdrive:

$ gdrive about
User: XXXX
Used: 7.5 GB
Free: 8.6 GB
Total: 16.1 GB
Max upload size: 5.2 TB

**Comment by ThomasWaldmann** [comment]
```
borg delete --first 1 --dry-run repo   # also consider --prefix or --glob-archives
```

**Comment by nickpapadonis** [comment]
I'm looking for this policy:
1. hourly backups for the past 24 hours
2. daily backups for the past month
3. weekly backups for all previous months.
4. oldest backups are deleted when the backup disk is full

The above command can be used with df.

I'm confused on allowing infinite weekly backups to be kept.  Does a specific argument allow this under "keep-weekly"?  I looked at archiver.py and see it only takes a numerical argument.

borg prune -v --list $REPOSITORY --prefix '{hostname}-'  --keep-hourly=24 --keep-daily=30 --keep-weekly=24 --keep-monthly=6

Any help appreciated.

**Comment by ThomasWaldmann** [comment]
There is no "delete something when disk is full" policy yet.

iirc 0 means forever, please check the docs.
