### ISSUE TITLE
borg: How to compress frequency of prior incremental backups

### ISSUE THREAD

**Issue by nickpapadonis** [borgbackup/borg#4065]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.1.7

#### Operating system (distribution) and version.
Mac OS

## Describe the problem you're observing.
This is a Question.

Is it possible to take backups from the past X days and compress that last day into a weekly backup.  I'm assuming this is a purge but not exactly sure how it should be specified.

I ask, because I'm trying to replicate Mac's Time Machine retention policy:
It makes hourly backups for the past 24 hours, daily backups for the past month, and weekly backups for all previous months. The oldest backups are deleted when the backup disk (capacity) is full.

Thanks!

**Comment by ThomasWaldmann** [comment]
It sounds like you are asking for some transformation of backups. borg does not do that in prune, it just deletes backups and keeps some according to the given policy.

But I don't think it is needed - if you make backups every day, a "keep N weeklies" policy would just keep every 7th of them and up to N in the end.

The difference why other tools might need to compress multiple into 1 is that they aren't doing full backups but incrementals/differentials, unlike borg, where each backup is logically a full backup.

**Comment by nickpapadonis** [comment]
Hi,

Comments follow

> On Aug 30, 2018, at 6:07 AM, TW <notifications@github.com> wrote:
> 
> It sounds like you are asking for some transformation of backups. borg does not do that in prune, it just deletes backups and keeps some according to the given policy.
> 
> But I don't think it is needed - if you make backups every day, a "keep N weeklies" policy would just keep every 7th of them and up to N in the end.
> 
> The difference why other tools might need to compress multiple into 1 is that they aren't doing full backups but incrementals/differentials, unlike borg, where each backup is logically a full backup.
> 
> 
It was my understanding borg performed data deduplication.  This would in effect be an incremental as only the files that changes should be backed up.  Does this agree with your findings?

Thanks

**Comment by ThomasWaldmann** [comment]
guess this one is answered.
