### ISSUE TITLE
borg: Does anyone have it working with gdrivefs and osxfuse?

### ISSUE THREAD

**Issue by nickpapadonis** [borgbackup/borg#4066]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes and many web pages

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.1.7

#### Operating system (distribution) and version.
OSX

## Describe the problem you're observing.
This is a question.  Does anyone have a working configuration using Mac OSX and osxfuse, such that borg's repo can be located on a Fuse mounted folder, specifically Google Drive?

I tried this configuration and it appears the repo is partially initialized after 'init', however then I run into an issue with a lock file left behind.  This causes later errors with 'create'.  I would be interested to find out if anyone has this configuration working as it seems to be a useful way of making a cloud backup.

The other solution is to keep the backup locally and rsync it to the cloud, which of course uses up extra intermediate disk capacity.

Thanks!

**Comment by ThomasWaldmann** [comment]
sounds like the filesystem you put your repo onto does not work good enough.

**Comment by ThomasWaldmann** [comment]
issue outside of borg, closing.
