### ISSUE TITLE
RAM For Receiving End of SSH Transfer?

### ISSUE THREAD

**Issue by ShadowRylander** [borgbackup/borg#4068]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

`borg 1.1.7`

#### Operating system (distribution) and version.

`Ubuntu 18.04 LTS Server VM`

#### Hardware / network configuration, and filesystems used.

`ext4`

#### How much data is handled by borg?

`50 MB - 15 GB`

## Question

Hello!
&nbsp;&nbsp;&nbsp;&nbsp; Approximately how much RAM would be needed for the receiving end of a borgbackup ssh transfer, given my data specifications? As I understand, and please correct me if I'm wrong, the source backs up the data and then transfers the chunks to the receiving end; therefore, I'm assuming the latter does not require as much RAM. I tried searching for this, but didn't know the proper terminology, and a google search didn't yield anything very helpful either.
&nbsp;&nbsp;&nbsp;&nbsp; Thanks you kindly for the help!

**Comment by ThomasWaldmann** [comment]
There's a formula in the docs. Or just try.

**Comment by ShadowRylander** [comment]
For the receiving end as well, regarding the formula? Sorry for being repetitive, though.

**Comment by ThomasWaldmann** [comment]
Receiving end (repo server): the main thing there is the size of the repository index.

The chunks and files index is on sender (client) side.

**Comment by ShadowRylander** [comment]
How would I go about checking the size of the index of a repository?

**Comment by ThomasWaldmann** [comment]
```
ls -l repo_dir/index*
```

**Comment by ShadowRylander** [comment]
Ah, right; thank you kindly! Closing the issue now, then.
