### ISSUE TITLE
Status after extract

### ISSUE THREAD

**Issue by xeor** [borgbackup/borg#4069]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.7

#### Operating system (distribution) and version.

macOS High Sierra

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg extract --progress ssh://borg@10.1.2.3/desktop::full_name-of-backup-2018-08-24_00:00:00

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

When working with extract, it is hard to see if it finished successful or not. I suggest there be a status at the end, just like when you do a backup.

Example, my restore took a little over a day, there was a couple of errors like `makedirs: [Errno 2] No such file or directory`.. The files tied to the error wasnt that important, so I didn't bother. But all the sudden, my prompt is back. No `extract complete` or anything from borg. Was everything else a success? Did borg crash? Was the errors fatal and it stopped?

A simple `backup finished, but with errors. See above`, would be good enough for me in this case. But I thought I would get a status like when I create the backups..

**Comment by ThomasWaldmann** [comment]
Did you try `--show-rc`?

**Comment by xeor** [comment]
Thanks for the tip, didn't have my old prompt (which shows returncodes), so I forgot about that 🤔 

It showed `terminating with warning status, rc 1`. Which based on the docs means I'm fine. The only errors are the ones that where outputed, and other than that, the restore was a success..?

**Comment by ThomasWaldmann** [comment]
Yes, only check the warning messages it showed.
