### ISSUE TITLE
rename is very slow (0.28.1)

### ISSUE THREAD

**Issue by chr-x** [borgbackup/borg#407]
Hi,
I am new to borgbackup. It looks very promising. Unfortunately I get stuck with 'rename'.

Starting: 
'# date ; time borg rename /media/sdi1/backup/borgbackup::aoxe-_1 aoxe ; date' 
three days ago , I am still waiting to finish. There is no ouput except the first 'date'.

The repository is 1 TB mostly mpg video data on an external USB-3.0 drive. The drive is connected via USB-2.0 hub. The CPU is an AMD A4-3300 dual core. The OS is Debian 8.2 amd64.

The 'create' run took about 40h at 10000kB/s read and write speed and a CPU usage of 30% idle and 55% wait, no compression, and no encryption.  The 'rename' run shows 22kB/s write every 2 sec (nmon) and a CPU usage of 98,2% idle and 1,2% wait all the time. 

What is going wrong here?

**Comment by ThomasWaldmann** [comment]
iirc, rename should be very fast. is you repo locked by something else? a lock leftever in cache or repo from a crashed/interrupted backup?

**Comment by chr-x** [comment]
Solved, lock.roster contained a stale lock from Ctrl-C. Rename is 2min 40sec Thank you!

**Comment by illwieckz** [comment]
I have the same issue here, but there is no `lock.roster` and I did a `break-lock` first to be sure. While I'm typing a lone `rename` is already lasting for more than 10 minutes and I'm still waiting for it to finish.

My borg repository contains 120k archive (2TB of deduplicated data for 700TB of non-deduplicated-uncompressed data). So, even if the rename would be lasting 2minute, it would mean the rename of all the archives will last 5 months. And I have to rename all of them.

How can I know I'm doing something wrong? What's the numeric translation of “_very fast_”?

**Comment by dimejo** [comment]
> What's the numeric translation of “very fast”?

On a repository with roughly 500 archives and about 600GB of real (deduplicated) data rename took 2 seconds for me. Note that this is a local repository on a 7.2k SATA drive.

**Comment by illwieckz** [comment]
Here it's a RAID1 (mdadm) of two 5400rpm drives, it's expected to be a bit slower than a plain 7200rpm drive but not that slower. For reference I interrupted the rename after being stalled for 33 minutes. Since I have more than 120 000 archives to rename, even if rename were working in 34 minutes per archive it's still not OK…

I would very appreciate any advice to find what's going wrong…

**Comment by ThomasWaldmann** [comment]
120.000 archives? O.O

Interesting. I'll have a look.

**Comment by ThomasWaldmann** [comment]
As a general note: if you want to rename them all, the best way is not to go via the commandline interface, but to write some custom code for that.
