### ISSUE TITLE
How to solve this locking problem?

### ISSUE THREAD

**Issue by ho1ger** [borgbackup/borg#4070]
... yes, I checked the documentation, and google, and also in the IRC.

I am running borg 1.1.5 on an Ubuntu 18.04.1 LTS machine. The backup target is a cloud storage that I mounted using davfs. The machine starts a cron job every 12 hours and pushes a backup to the cloud. This cron job is running as root.

I have a bit of an odd situation since a couple of days that I cannot understand or fix: a few days ago I logged into the machine and tried to `borg list` the contents of my repo. I did not get any result but only an error related to locking the repo. The same happened when I tried to manually create a backup, etc.

Interestingly, the cron job still seems to work (more or less), as it sent me this mail some days earlier:

    Removed stale shared roster lock for pid 28964.   <-- ??
    Removed stale shared roster lock for pid 28964.   <-- ??
    Initializing cache transaction: Reading config
    Initializing cache transaction: Reading chunks
    Initializing cache transaction: Reading files

     0% Syncing chunks cache. Processing archive 2018_05_27_18_20_02
     2% Syncing chunks cache. Processing archive 2018_05_31_18_20_01
    ...
    Compacting segments  94%
    Compacting segments  97%

    Saving files cache
    Saving chunks cache
    Saving cache config

    ------------------------------------------------------------------------------
    Archive name: 2018_09_02_12_20_01
    Archive fingerprint: dd199d7a69e0bc4bdcb2865fc07c62f2d08a6116bfd5a210862733974ca1ac60
    Time (start): Sun, 2018-09-02 12:20:11
    Time (end):   Sun, 2018-09-02 12:34:31
    Duration: 14 minutes 19.86 seconds
    Number of files: 11169
    Utilization of max. archive size: 0%
    ------------------------------------------------------------------------------
                          Original size      Compressed size    Deduplicated size
    This archive:               18.50 GB             17.90 GB             46.32 MB
    All archives:              889.64 GB            854.94 GB             20.48 GB

                          Unique chunks         Total chunks
    Chunk index:                   26141               908537
    ------------------------------------------------------------------------------

12 hours later, I got a similar mail but without the hint that it removed a lock for a stale backup session. So I actually thought my problem would have been solved by a miracle or so. When I now do `borg list`, I get the complete list of backups but at the end there is a problem:

    (list of backups)
    Local Exception
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
        exit_code = archiver.run(args)
      File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
        return set_ec(func(args))
      File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
        return method(self, args, repository=repository, **kwargs)
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 198, in __exit__
        self.close()
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
        self.lock.release()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 387, in release
        self._roster.remove()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 116, in __exit__
        self.release()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 149, in release
        os.rmdir(self.path)
    OSError: [Errno 22] Invalid argument: '/media/PATH_TO_MOUNT/backup/lock.exclusive'

    Platform: Linux cubi 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
    Linux: Ubuntu 18.04 bionic
    Borg: 1.1.5  Python: CPython 3.6.5
    PID: 4996  CWD: /root/scripts/backup
    sys.argv: ['/usr/bin/borg', 'list', '/media/PATH_TO_MOUNT/backup']
    SSH_ORIGINAL_COMMAND: None

    Exception ignored in: <bound method Repository.__del__ of <Repository /media/PATH_TO_MOUNT/backup>>
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 173, in __del__
        self.close()
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
        self.lock.release()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 384, in release
        with self._lock:
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 113, in __enter__
        return self.acquire()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 135, in acquire
        raise LockTimeout(self.path)
    borg.locking.LockTimeout: Failed to create/acquire the lock /media/PATH_TO_MOUNT/backup/lock.exclusive (timeout).

When running the same backup script as used by cron manually, the process fails immediately:

    Failed to create/acquire the lock /media/PATH_TO_MOUNT/backup/lock.exclusive (timeout).

Things are getting weirder: I tried to initialize a new borg repo on the webdav and I get the following error, again 

    By default repositories initialized with this version will produce security
    errors if written to with an older version (up to and including Borg 1.0.8).

    If you want to use these older versions, you can disable the check by running:
    borg upgrade --disable-tam /media/1und1/test

    See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.
    Exception ignored in: <bound method Repository.__del__ of <Repository /media/1und1/test>>
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 173, in __del__
        self.close()
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
        self.lock.release()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 379, in release
        self._roster.modify(EXCLUSIVE, REMOVE)
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 278, in modify
        elements.remove(self.id)
    KeyError: (('cubi@238368719996246', 5245, 0),)
    Local Exception
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
        exit_code = archiver.run(args)
      File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
        return set_ec(func(args))
      File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
        return method(self, args, repository=repository, **kwargs)
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 198, in __exit__
        self.close()
      File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
        self.lock.release()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 382, in release
        self._lock.release()
      File "/usr/lib/python3/dist-packages/borg/locking.py", line 149, in release
        os.rmdir(self.path)
    OSError: [Errno 22] Invalid argument: '/media/PATH_TO_MOUNT/test/lock.exclusive'

    Platform: Linux cubi 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
    Linux: Ubuntu 18.04 bionic
    Borg: 1.1.5  Python: CPython 3.6.5
    PID: 5245  CWD: /root/scripts/backup_test
    sys.argv: ['/usr/bin/borg', 'init', '--encryption=keyfile', '/media/1und1/test']
    SSH_ORIGINAL_COMMAND: None

However, it seems like the repo is created correctly, ...

    /media/PATH_TO_MOUNT/test/
    ├── config
    ├── data
    │   └── 0
    │       ├── 0
    │       └── 1
    ├── hints.1
    ├── index.1
    ├── integrity.1
    ├── lock.exclusive
    ├── nonce
    └── README

but an attempt to run a backup fails with the same problem as described earlier. I absolutely do not understand what is going on here, so any help would be appreciated.

**Comment by ThomasWaldmann** [comment]
Stale lock means that the lock is there, but the process that created it is not running (any more).

Usually borg cleans up locks when it terminates, but sudden death (like OS/hw crash, power failure) or a borg bug can leave locks behind.

The stuff seen above doesn't look like a well-behaved filesystem (or a stable connection), maybe that is the problem.

**Comment by ho1ger** [comment]
hmmmmm, ... It seems like that I could fix my problem... I still do not _really_ understand what was happening - but I want to write this down in case anybody has similar problems...

My cloud storage provider (German ISP 1und1) does not really delete stuff from the space they provide you but they move stuff into a "recycle bin" kind of thing. So far, this has never been a problem but for some reason this "recycling process" seems to have failed for some reason I do not understand. I emptied the bin and the locks can be created/acquired again...

**Comment by ThomasWaldmann** [comment]
sounds like an issue of the filesystem used for the repo, closing.

**Comment by mamrhein** [comment]
@ho1ger: I have the same issue with the 1und1 webdav server. Did you find a solution?
