### ISSUE TITLE
PlaceholderError not printed as json

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#4073]
borg 1.1.7

    $ borg create --progress --log-json dest::{x} src
    Invalid placeholder "x" in string: dest::{x}

    $ borg create --progress --log-json dest::x src
    {"type": "log_message", "name": "borg.archiver", "msgid": "Repository.DoesNotExist", …

**Comment by ThomasWaldmann** [comment]
The first one is a arg parsing issue.

arg parsing happens before logging (including the json logger) is set up, so in case of exceptions, it does a rather simple `print` to output stuff.

as the logging setup depends on arguments being parsed already (e.g. for logging options like `--debug`, `-v`, whether or not to setup the json logger), I guess we have a chicken and egg problem here.

**Comment by sophie-h** [comment]
I think this could be solved in principle (ENV + catching argparse exception), but that pretty hackish and the non-json error is just a minor inconvenience imo.

Maybe, it would still be worth to document it in the JSON section?

**Comment by ThomasWaldmann** [comment]
Yeah, could be mentioned - can you do a PR?

**Comment by fantasya-pbem** [comment]
I have added a short warning, see my PR.

**Comment by fantasya-pbem** [comment]
This issue can be close now.

**Comment by ThomasWaldmann** [comment]
Thanks for fixing!
