### ISSUE TITLE
JSON interface for finished 'progress_percent'

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#4074]
borg 1.1.7 output

```json
{"type": "progress_percent", "finished": false, "msgid": "repository.compact_segments",
 "operation": 1, "time": 1536057203.5422916,
 "info": null, "current": 3, "total": 3, "message": "Compacting segments  67%"}
{"type": "progress_percent", "finished": true, "msgid": "repository.compact_segments",
 "operation": 1, "time": 1536057203.5423532}
```

However, `current` and `total` are not documented to be optional.

Let me note that their absence also complicates strict parsing. Imho it would be better to just provide those values for `"finished": true`.

**Comment by ThomasWaldmann** [comment]
are you confusing `progress_message` with `progress_percent`?

https://github.com/borgbackup/borg/blob/master/docs/internals/frontends.rst#logging

**Comment by sophie-h** [comment]
> are you confusing progress_message with progress_percent?

Concerning the docs: yes. I have updated the issue with a correct example.

**Comment by ThomasWaldmann** [comment]
```
"info": null, "current": 3, "total": 3, "message": "Compacting segments  67%"
```
So, these 3 are not present when finished == true.

**Comment by ThomasWaldmann** [comment]
This is a quite old issue, but we fixed something similar recently.

**Comment by ThomasWaldmann** [comment]
#6683 only provides a minimal set of attribute in the final case, so guess we should do the same here.

So we just document some as optional, see https://github.com/borgbackup/borg/issues/4074#issuecomment-419184216 .
