### ISSUE TITLE
borg extract problems with ascii - warn user on archive creation?

### ISSUE THREAD

**Issue by Micha-Btz** [borgbackup/borg#4075]
Hi there,

I have problems with extract an archive due to ascii encoding.
locale is:

> sysiphus:~/media/restore$ locale
> LANG=de_DE.utf8
> LANGUAGE=
> LC_CTYPE="C"
> LC_NUMERIC="C"
> LC_TIME="C"
> LC_COLLATE="C"
> LC_MONETARY="C"
> LC_MESSAGES="C"
> LC_PAPER="C"
> LC_NAME="C"
> LC_ADDRESS="C"
> LC_TELEPHONE="C"
> LC_MEASUREMENT="C"
> LC_IDENTIFICATION="C"
> LC_ALL=C

> borg extract ../syncthing/backup/sysiphus/borg/::home-20180909
> Warning: File system encoding is "ascii", extracting non-ascii filenames will not be supported.
> Hint: You likely need to fix your locale setup. E.g. install locales and use: LANG=en_US.UTF-8
> Failed to encode filename "/home/mdomann/media/restore/home/mdomann/.config/menus/applications-merged/wine-Programs-GOG.com-Star Wars Jedi Knight - Jedi Academy-Deinstallieren STAR WARS? Jedi Knight? - Jedi Academy?.menu" into file system encoding "ascii". Consider configuring the LANG environment variable.

Explicit set the locales makes no difference.

the doc tells me to test with mount command:

> sysiphus:~/media$ borg mount syncthing/backup/sysiphus/borg/::home-20180909 restore 
> Local Exception
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4434, in main
>     exit_code = archiver.run(args)
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4366, in run
>     return set_ec(func(args))
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1352, in do_mount
>     return self._do_mount(args)
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
>     return method(self, args, repository=repository, **kwargs)
>   File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1362, in _do_mount
>     operations.mount(args.mountpoint, args.options, args.foreground)
>   File "/usr/lib/python3/dist-packages/borg/fuse.py", line 323, in mount
>     self._create_filesystem()
>   File "/usr/lib/python3/dist-packages/borg/fuse.py", line 252, in _create_filesystem
>     self.process_archive(self.args.location.archive)
>   File "/usr/lib/python3/dist-packages/borg/fuse.py", line 380, in process_archive
>     path = os.fsencode(item.path)
>   File "/usr/lib/python3.6/os.py", line 802, in fsencode
>     return filename.encode(encoding, errors)
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2122' in position 130: ordinal not in range(128)

> Platform: Linux sysiphus 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64
> Linux: debian buster/sid 
> Borg: 1.1.7  Python: CPython 3.6.6+
> PID: 23826  CWD: /home/mdomann/media
> sys.argv: ['/usr/bin/borg', 'mount', 'syncthing/backup/sysiphus/borg/::home-20180909', 'restore']
> SSH_ORIGINAL_COMMAND: None
> 

So at first I have backup on a second way so not a problem if it not works. So this issue is more to understand how it works.  How can I access my files if I really must? And should borg tell me on archive creating that this files will make trouble, so that I have a chance to react?

Thanks for the great tool.

Micha

**Comment by ThomasWaldmann** [comment]
It determines your fs encoding as ascii and because of that it fails to encode anything else than that.

borg will work as soon as python determines the fs encoding to be utf-8 (as it usually is nowadays, please check).

I have it like this:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by ThomasWaldmann** [comment]
Besides setting the env vars, also check if you actually installed/generated the locales you use.

**Comment by Micha-Btz** [comment]
Thanks for explanation. 
Setting 
: ${LANG:=de_DE.UTF-8}; export LANG
: ${LC_CTYPE:=de_DE.UTF-8}; export LC_CTYPE
in .bash_profile leads to
```
locale
LANG=de_DE.utf8
LANGUAGE=
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=
```
Now it works. Thanks.
