### ISSUE TITLE
borg create and stdin

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#4077]
borg 1.1.7.

`mysqldump ... | borg create ... --stdin-name 'name' - ` returns error
`mysqldump ... | borg create ... - --stdin-name 'name' ` runs ok

is it correct behavior?

How to make backup of multiple databases to the single snapshot with different `--stdin-name's` ?
Multiple `mysqldump $dbname | borg create $REPO::$DATE - --stdin-name $dbname` returns error `Archive $DATE already exists` after first mysqldump.

What I want to achieve is one snapshot named $DATE consist of multiple mysqldumps made to stdout.

**Comment by ThomasWaldmann** [comment]
You need to give `-` to make borg read stdin.
`--stdin-name` is only to give it a name, but is not sufficient to trigger reading from stdin.

And there is only one stdin stream, so if you want to put multiple things via stdin, borg can't help you with that. So I'ld suggest creating multiple archives and putting the name of the db into the archive name.

**Comment by ThomasWaldmann** [comment]
Oh, I misread that. See our section "order matters" in the docs?
