### ISSUE TITLE
How Does Borg Handle Changes While Performing a Backup?

### ISSUE THREAD

**Issue by Stunner** [borgbackup/borg#4081]
Like the title says, I just want some clarification on how borg handles the case where changes are made during a backup.

I back up over 2TB over my home network which usually takes about a day and a half or so, during which changes could very easily be made to the files being backed up. I am curious to know how borg works around this problem.

**Comment by Stunner** [comment]
Thanks for the fast response. Good to know.

I searched for this awhile back and had no luck finding anything about it. Searching Google and skimming through borg's documentation is what I tried to no avail. I also searched within this repo with no results... If it is in the docs perhaps it might not be under an obvious enough header? I didn't read all of borg's documentation but skimmed for it and might have missed it.

**Comment by ThomasWaldmann** [comment]
fixed by #4116 + backport.
