### ISSUE TITLE
experimental status

### ISSUE THREAD

**Issue by m-osmani** [borgbackup/borg#4085]
hello everybody,

i read here https://borgbackup.readthedocs.io/en/stable/usage/create.html that the option „--pattern“ , is experimental.

Is this information uptodate ?

Does „--exclude“ has limitation compared to „--pattern“ ?

regards

**Comment by m-osmani** [comment]
In general i found the answer here: https://github.com/borgbackup/borg/issues/1406

but why is the current state experimental ?

**Comment by ThomasWaldmann** [comment]
it mostly means that we did not get too much feedback about it yet and that it may change again.
