### ISSUE TITLE
Crash when creating new repository on CIFS mounted volume

### ISSUE THREAD

**Issue by fuxoft** [borgbackup/borg#4086]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. My bug is possibly related to bug #4056 but I am not sure.

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.5

#### Operating system (distribution) and version.

Xubuntu 18.04.1 LTS

#### Hardware / network configuration, and filesystems used.

CIFS mounted using the following fstab line:
//192.168.69.97/sklad /media/sklad cifs vers=1.0,guest,uid=1000 0 0

#### How much data is handled by borg?

none

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borgbackup init -v --encryption=repokey-blake2 /media/sklad/backup/frantisek_borg/fukafutokyu_orig

## Describe the problem you're observing.

I am trying to create new repository on CIFS mounted backup drive using the command above. After entering and confirming the passphrase, the following crash occurs:

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 266, in do_init
    key = key_creator(repository, args)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 111, in key_creator
    return key.create(repository, args)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 678, in create
    key.save(target, passphrase)
  File "/usr/lib/python3/dist-packages/borg/crypto/key.py", line 788, in save
    target.save_key(key_data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 299, in save_key
    self.save_config(self.path, self.config)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 281, in save_config
    os.link(config_path, old_config_path)
NotADirectoryError: [Errno 20] Not a directory: '/media/sklad/backup/frantisek_borg/fukafutokyu_orig/config' -> '/media/sklad/backup/frantisek_borg/fukafutokyu_orig/config.old'

Platform: Linux frantisek2 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.5
PID: 8538  CWD: /home/fuxoft
sys.argv: ['/usr/bin/borgbackup', 'init', '-v', '--encryption=repokey-blake2', '/media/sklad/backup/frantisek_borg/fukafutokyu_orig']
SSH_ORIGINAL_COMMAND: None
```

After the crash, the contents of repository directory is as follows:

```
drwxrwxrwx 3 fuxoft 501   0 Sep 24 03:17 ./
drwxrwxrwx 3 fuxoft 501   0 Sep 24 03:17 ../
-rwxrwxrwx 1 fuxoft 501 209 Sep 24 03:17 config*
drwxrwxrwx 2 fuxoft 501   0 Sep 24 03:17 data/
-rwxrwxrwx 1 fuxoft 501  73 Sep 24 03:17 README*
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, always. See above.

**Comment by fuxoft** [comment]
UPDATE: After adding "nounix" option to fstab, this error no longer appears and everything seems to work correctly. So I am not sure if this still qualifies as a Borg bug or not.

**Comment by ThomasWaldmann** [comment]
```
nounix
    Disable the CIFS Unix Extensions for this mount. This can be useful in order to turn off multiple settings at once. This includes POSIX acls, POSIX locks, POSIX paths, symlink support and retrieving uids/gids/mode from the server. This can also be useful to work around a bug in a server that supports Unix Extensions.

    See section INODE NUMBERS for more information. 
```

**Comment by fuxoft** [comment]
The error happened when Borg's python script tried to create a link on the mounted FS. Which was impossible because it was FAT32. The error was not caught (as it probably should be, according to the surrounding Python code). The "server" is quite old D-Link DNS 323 storage enclosure. Let's hope this info is useful if someone else has similar problem.

**Comment by ThomasWaldmann** [comment]
TODO: check if a reasonably modern linux generates the same problem (bad errno) when repo is on fat32.

**Comment by ThomasWaldmann** [comment]
note: we recently had a similar case (#4336) with a bad errno.

For me, it looks like this is a bug in the filesystem, it gives a wrong errno.

While we could consider any errno as "it did not work", this would somehow hide the real problem (and the bug in the fs) and might be even dangerous in case it is a hw error.

If there is any idea about how to deal better with this or any additional info (like being reproducable on recent cifs implementations and without using a crappy fat32 filesystem), please reopen.
