### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by rolfdobrig** [borgbackup/borg#4087]
Hi, since a few days my borg test installation stops to work. Currently one central borg server (Ubuntu 18.04, borg 1.1.5) and two clients (Ubuntu 16.04 and 14.04 with borg 1.0.2). Also one QNAP client wirh borg 1.1.0. Because lt stops to work my first thought was the central borg server and so I have done the update to borg 1.1.7. Nothing change. Second I tried the update also an the client side, nothing change.

All systems do not have an mounted filesystem. It is every time direct attached storage. So the oplock solution from samba doesn fit. One system has some nfs mounts.

Attached the debug output from one client with the update to borg 1.1.7. This is the client with the nfs mounts.
```
using builtin fallback logging configuration
35 self tests completed in 0.17 seconds
SSH command line: ['ssh', 'root@borg.nomics.de', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.10 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/backup/borgbackups/berlin1'
Remote: Resolved repository path to '/backup/borgbackups/berlin1'
Remote: Verified integrity of /backup/borgbackups/berlin1/index.259
TAM-verified manifest
Cache integrity: No integrity data found (files, chunks). Cache is from old version.
security: read previous location 'ssh://root@borg.nomics.de/backup/borgbackups/berlin1'
security: read manifest timestamp '2018-07-29T17:54:02.438098'
security: determined newest manifest timestamp as 2018-07-29T17:54:02.438098
security: repository checks ok, allowing access
Cache integrity: No integrity data found (files, chunks). Cache is from old version.
Cache integrity: No integrity data found (files, chunks). Cache is from old version.
Reading files cache ...
security: read previous location 'ssh://root@borg.nomics.de/backup/borgbackups/berlin1'
security: read manifest timestamp '2018-07-29T17:54:02.438098'
security: determined newest manifest timestamp as 2018-07-29T17:54:02.438098
security: repository checks ok, allowing access
Processing files ...
Remote: Cleaned up 1 uncommitted segment files (== everything after segment 259).
Remote: Verified integrity of /backup/borgbackups/berlin1/hints.259
Remote: Traceback (most recent call last):

  File "borg/remote.py", line 248, in serve

  File "borg/repository.py", line 1089, in put

  File "borg/repository.py", line 1459, in write_put

  File "src/borg/platform/linux.pyx", line 257, in borg.platform.linux.SyncFile.write

  File "src/borg/platform/linux.pyx", line 229, in borg.platform.linux._sync_file_range

OSError: [Errno 5] Input/output error

RemoteRepository: 118.04 MB bytes sent, 98.36 kB bytes received, 10484 messages sent
Traceback (most recent call last):

  File "borg/remote.py", line 248, in serve

  File "borg/repository.py", line 1089, in put

  File "borg/repository.py", line 1459, in write_put

  File "src/borg/platform/linux.pyx", line 257, in borg.platform.linux.SyncFile.write

  File "src/borg/platform/linux.pyx", line 229, in borg.platform.linux._sync_file_range

OSError: [Errno 5] Input/output error

Borg server: Platform: Linux borg 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64
Borg server: Linux: debian buster/sid 
Borg server: Borg: 1.1.7  Python: CPython 3.5.5
Borg server: PID: 4303  CWD: /root
Borg server: sys.argv: ['borg', 'serve', '--umask=077', '--debug']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux Rolf-X201 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64
Linux: debian stretch/sid 
Borg: 1.1.7  Python: CPython 3.5.5
PID: 18865  CWD: /usr/local/skripte
sys.argv: ['borg', 'create', '-C', 'lzma,4', '-v', '--debug', '--stats', 'root@borg.nomics.de:/backup/borgbackups/berlin1::{hostname}-{now:%Y-%m-%d}', '/', '--exclude', '/dev', '--exclude', '/proc', '--exclude', '/sys', '--exclude', '/var/run', '--exclude', '/home', '--exclude', '/run', '--exclude', '/lost+found', '--exclude', '/mnt', '--exclude', '/var/lib/lxcfs']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
> This exception is raised when a system function returns a system-related error, including I/O failures such as “file not found” or “disk full” (not for illegal argument types or other incidental errors).

So this is a file system error, not a Borg.

**Comment by infectormp** [comment]
try `borg check` and check you hardware

**Comment by rolfdobrig** [comment]
many thanks, so the problem must be on the central borg server. Because all clients have the same failure. I started the check on the first client and It seams that the check needs a lot of time. I come back with the results from the check.

**Comment by ThomasWaldmann** [comment]
Maybe first making sure the hw and fs is ok is a good idea.

If you do a lot of I/O on a broken system, it might get worse.

**Comment by rolfdobrig** [comment]
I think we have it. The disk has some access problems. 

many thanks to all. The hardware ist the failure not borg.

--- cut here ---
Sep 25 20:36:21 borg kernel: [3064665.956261] ata3.00: exception Emask 0x10 SAct 0x0 SErr 0x400100 action 0x
6
Sep 25 20:36:21 borg kernel: [3064665.956272] ata3.00: BMDMA stat 0x26
Sep 25 20:36:21 borg kernel: [3064665.956278] ata3: SError: { UnrecovData Handshk }
Sep 25 20:36:21 borg kernel: [3064665.956283] ata3.00: failed command: WRITE DMA EXT
Sep 25 20:36:21 borg kernel: [3064665.956294] ata3.00: cmd 35/00:08:68:3c:1a/00:00:46:02:00/e0 tag 0 dma 409
6 out
Sep 25 20:36:21 borg kernel: [3064665.956294]          res 53/84:08:68:3c:1a/84:00:46:02:00/40 Emask 0x30 (h
ost bus error)
Sep 25 20:36:21 borg kernel: [3064665.956304] ata3.00: status: { DRDY SENSE ERR }
Sep 25 20:36:21 borg kernel: [3064665.956308] ata3.00: error: { ICRC ABRT }
Sep 25 20:36:21 borg kernel: [3064665.956321] ata3: hard resetting link
Sep 25 20:36:21 borg kernel: [3064666.428078] ata3: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Sep 25 20:36:21 borg kernel: [3064666.454832] ata3.00: configured for UDMA/33
Sep 25 20:36:21 borg kernel: [3064666.454844] ata3: EH complete
--- cut here ---

**Comment by ThomasWaldmann** [comment]
It looks like sync_file_range on the borg server has an issue.

Unrelated, but as a security hint: you do not need to use root@borgserver, a normal account also works (when switching, you need to fix owner/group once to the new user/group).

**Comment by ThomasWaldmann** [comment]
Check cables (ICRC is interface crc error, thus one of the interfaces at the end of the cables or the cable itself is bad).

DRDY and UnrecovData sound rather like a disk issue though.

Check SMART output (`smartctl -a /dev/sdx`).

**Comment by rolfdobrig** [comment]
In which way I can check teh sync_file_range? Borg check --repository....?
yes, security was currently not my first topic. I tried to check out the stability and robustness 
Your point about the cable could be right. Yesterday evening I shutdown the central borg server and after 1 hour I started the server again. The failure with the disk was gone

Many thanks

**Comment by ThomasWaldmann** [comment]
@rolfdobrig sync_file_range is used for syncing repo segment files to disk, so just use `borg create` with some GBs.
