### ISSUE TITLE
Feature Request: remote files to backup to a local repository

### ISSUE THREAD

**Issue by geraldhmt** [borgbackup/borg#4089]
Hello,

I'm a newbie in borg.
Usually I backup files FROM remote server TO my local host. And my localhost could be behind firewall (read remote server could be join from my host by ssh,  but not the reverse way - ssh server is only on remote server).

With this case, I only find this way to bakup using borg :
 1) use rsync over ssh to get file from remote server to local space (the local sync space).
 2) use borg to backup local syn space.

Drawback are : 
 - files user/ group / could be altered because of difference between both server
 - wast space for local sync space.

Could be possible to use a local borg repository and select remote files (via ssh) ?

Thanks for your answer.
Gerald

**Comment by ThomasWaldmann** [comment]
See some older tickets here, maybe also discussion on the mailing list.

What borg does is `push mode`. What you want is referred to as `pull mode` (search for this).

borg does not implement pull mode, but there are workarounds.
You could maybe also mount the remote fs via sshfs onto a local directory.

(closing this as duplicate)
