### ISSUE TITLE
borg create fails with cache config having dual entry of integrity

### ISSUE THREAD

**Issue by mnikhil-git** [borgbackup/borg#4096]
Borg version 1.1.7

```
Removed stale exclusive roster lock for host ip-xx.xx.xx.xx.us-west-2.compute.internal@6808653270260 pid 25637 thread 0.
Removed stale exclusive roster lock for host ip-xx.xx.xx.xx.us-west-2.compute.internal@6808653270260 pid 25637 thread 0.
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4434, in main
  File "borg/archiver.py", line 4366, in run
  File "borg/archiver.py", line 143, in wrapper
  File "borg/cache.py", line 206, in assert_secure
  File "borg/cache.py", line 171, in assert_secure
  File "borg/cache.py", line 238, in __enter__
  File "borg/cache.py", line 262, in open
  File "borg/cache.py", line 266, in load
  File "configparser.py", line 696, in read
  File "configparser.py", line 1063, in _read
**configparser.DuplicateSectionError: While reading from '/mnt/s3-mount/efs-backup.borgbackup/.cache/borg/53f080be7807c6ed3435d6f7480aca251e8b73e4bc7a0b2d325a0a8fd89a41da/config' [line 14]: section 'integrity' already exists**

Platform: Linux ip-ip-xx.xx.xx.xx 4.4.0-1063-aws #72-Ubuntu SMP Fri Jul 13 07:23:34 UTC 2018 x86_64
Linux: debian stretch/sid
Borg: 1.1.7  Python: CPython 3.5.5
PID: 25716  CWD: /home/ubuntu
sys.argv: ['/opt/borgbackup/bin/borgbackup', 'create', '-v', '--stats', '--compression', 'zstd,8', '/mnt/s3-mount/efs-backup.borgbackup::2018-10-05-08-51', '/mnt/efs']
SSH_ORIGINAL_COMMAND: None
```
cache file has this
```
[cache]
version = 1
repository = 53f080be7807c6ed3435d6f7480aca251e8b73e4bc7a0b2d325a0a8fd89a41da
manifest =

[integrity]
manifest = e09178aa570f01705c4c4e872ffaaa4dce7f8
previous_location = /mnt/s3-mount/efs-backup.borgbackup
timestamp = 2018-10-05T08:46:03.498375
ignored_features =
mandatory_features =
key_type = 2

[integrity]
manifest = 351e48f913758912f1c5597a487e09178aa570f01705c4c4e872ffaaa4dce7f8
files = {"algorithm": "XXH64", "digests": {"final": "20bd0ecb07be023b"}}
chunks = {"algorithm": "XXH64", "digests": {"HashHeader": "a89eb3b225a32567", "final": "4251075456fbf9c1"}}
```

**Comment by mnikhil-git** [comment]
borg cache directory is on a s3fs mount, it does seems like the config in the borg cache is not generated properly in ini format.

**Comment by ThomasWaldmann** [comment]
the cache is not encrypted, so it is a bad idea anyway to put it at the same place as the repository. just keep it local, at the usual place.

maybe s3fs is not working good enough as a filesystem, never seen this ini problem before.

**Comment by mnikhil-git** [comment]
Hmm.. I can put it into a different directory on the same s3fs mount, but
same problem.

Its the s3fs that is not working good since when I tried the local
filesystem on ext4, it seems fine. The reason why I chose to put it on s3fs
mount is that the borg backup client is going to be changing all the time
(ec2 instance is ephemeral/transient that once the backup is done it gets
terminated and next backup is run by an entirely a new ec2 instance).

this could be an s3fs issue but I am wondering why is the change to a
simple text ini file could be having issues while the data backup itself
does not. Is there anything special going on how borgbackup writes this
config file (like parallel threads etc?)

**Comment by ThomasWaldmann** [comment]
No parallel threads yet. And the config file is read/written by configparser, which is a python stdlib module.

**Comment by ThomasWaldmann** [comment]
Did you try having the cache locally and just destroying it with the instance?
The next instance then will start with an empty cache and automatically rebuild what's needed.

**Comment by mnikhil-git** [comment]
>>Did you try having the cache locally and just destroying it with the instance?
yes

>>The next instance then will start with an empty cache and automatically rebuild what's needed.
yes, but given over a period of time that there will be multiple archives(with many files) in the backup repo, rebuilding will be a function of the number of them and it will increase the time for a simple single backup.

and that is also the reason that I thought that having borg base dir for config in the same s3 mount will not require the ec2 instance to rebuild the cache again in vain, because the ec2 instance is temporary and there will be new ec2 instance anyway.

**Comment by fullofcaffeine** [comment]
So, keeping the cache locally makes this a good/viable option to backup directly to a S3 compatible server?

**Comment by mnikhil-git** [comment]
So far the backup and restoral seems to have been working fine with s3fs-fuse mount of an s3 bucket, with cache being local on an ephemeral ec2 instance and the cost is regenerating the cache everytime there is a backup

**Comment by ThomasWaldmann** [comment]
issue outside of borg, closing.
