### ISSUE TITLE
specify options NOT to enforce/override via borg serve 

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4097]
== whitelist options determined client-side (and everything else is enforced server-side) - this avoids such security issues.

See there: https://github.com/borgbackup/borg/pull/4095#pullrequestreview-162266367

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/64379886-specify-options-not-to-enforce-override-via-borg-serve)

**Comment by step21** [comment]
Hi, probably this is simple, but I want to be sure that I understand it -
currently, for borg serve, all options are dropped, and then the listed options are assigned from force_result, right? Instead, all other options should be removed/unassigned explicitly so that only the listed options are left, right?

**Comment by ThomasWaldmann** [comment]
the point is just that using a whitelist will cause limited functionality if we forget to add something to it (the new stuff won't work).

forgetting to add something to a blacklist causes a security issue though (client being able to use something they should not be able to use).

**Comment by ThomasWaldmann** [comment]
@step21 are you still working on that?

**Comment by ThomasWaldmann** [comment]
@step ping :)

**Comment by ThomasWaldmann** [comment]
Looking at this right now...

**Comment by ThomasWaldmann** [comment]
Going to have a whitelist *and* a blacklist.

The latter will make sure known-critical stuff (which must be enforced server-side) is not accidentally whitelisted.

**Comment by ThomasWaldmann** [comment]
@step21 if you like to, you could review #4531.

**Comment by ThomasWaldmann** [comment]
example case where the old code was problematic in the past: #4093

**Comment by ThomasWaldmann** [comment]
fixed in master and 1.1-maint.
