### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by KodaCCH** [borgbackup/borg#4098]
I want install borgbackup from backport:
apt-get install borgbackup -t stretch-backports
But the installation givs an error because my python3 version:  3.6.6-1
Givs a change to install borg backup?

**Comment by KodaCCH** [comment]
Ok. I have installed from sid :)
Now it works

**Comment by ThomasWaldmann** [comment]
I think installing from backports should usually work.

Did you install other stuff from sid also and is that the reason why it runs into problems?

**Comment by KodaCCH** [comment]
Yes. I have installed postfix and postfix-mysql from sid. I don't find a package repository for this. So I used sid

**Comment by ThomasWaldmann** [comment]
so i guess this is not a borgbackup issue and maybe not even a packaging issue, just a dependency problem due to mix up of package source. reopen if you think otherwise.

@LocutusOfBorg ^
