### ISSUE TITLE
32c3 meetup?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#410]
I'll attend 32c3 (see https://events.ccc.de/congress/2015/wiki/Main_Page ) and will be at the Python assembly (when not attending talks or doing other stuff, see https://events.ccc.de/congress/2015/wiki/Assembly:Python ).

If you are a borgbackup user or developer (or just interested), we can meetup there, just add a note below so I see who's coming.

**Comment by anarcat** [comment]
i'd love to go, but being on the wrong side of the world makes this basically impossible during the holiday seasons for me. i'll be at the HOPE conference in NYC in july though. :)

**Comment by brodul** [comment]
@ThomasWaldmann I will definitely buy you some Club-mate or beer.

**Comment by ThomasWaldmann** [comment]
BTW, I'll travel tomorrow and if I can get in, I'll likely be on-site and preparing the python assembly a bit.

**Comment by brodul** [comment]
@ThomasWaldmann I am at the C3. Do you prefer beer or mate ?
I could not find the python assembly. Any hints where it is?

**Comment by ThomasWaldmann** [comment]
> I could not find the python assembly. Any hints where it is?

I'm at the python assembly now.

https://c3nav.de/?o=entry&d=python


-- 

Waldmann EDV Systeme/Service GbR
Gerhard Waldmann, Thomas Waldmann
Pleidelsheimer Str. 25
74321 Bietigheim-Bissingen

Weitere Infos siehe: http://waldmann-edv.de/

GPG ID: FAF7B393
GPG FP: 6D5B EF9A DD20 7580 5747 B70F 9F88 FB52 FAF7 B393
