### ISSUE TITLE
include only files from file list  (so that I can filter by combination of names mtime size etc) 

### ISSUE THREAD

**Issue by 517qf** [borgbackup/borg#4100]
Is there an option that only files that are listed in a file are included? This way I could use commands like find that offer all kinds of complicated filters so that only files I want to backup are selected.

Background: I want to include files based on their mtime and exclude based on their size and name: Getting such a list with find isn't too hard but I can imagine that it's very unlikely/hard to offer all of these functions in borg. I didn't find an option in the manual or in the issues.

I have seen the issue about filtering by size but this wouldn't suffice for me.

Thanks for this great software.

**Comment by ThomasWaldmann** [comment]
Try `--from-patterns` and `borg help patterns`.

Likely you'll need some intermediate processing, a bare file list won't contain all that is needed.

**Comment by 517qf** [comment]
Thanks for the quick reply and solving my problem. Before posting I only tried sh/fm selectors wich was really slow ... somehow I missed the pf function.

About the pf selector:  Is this file correct or is my solution slower then necessary? 

I use this command `borg create --patterns-from /path/to/my-patterns-file /path/to/repo`

My patterns file looks like this:

    R /home
    - /home/*
    + pf:/home/user/file1
    + pf:/home/user/subfolder/file2
    ...

----

My problem is: I have several terabyte of data so that I would have to pay a lot for a full online backup. I plan to use borg only for new/modified files since the last off-site backup. Why borg? Because I have many files that I only change slightly and I regularly rename/move files. I don't think that there is a more elegant solution?

**Comment by ThomasWaldmann** [comment]
Guess `- pp:/home/` would be even a bit faster, as it is just a prefix check, no wildcards.

The `pf:` stuff is fast as it uses a python dictionary (hashtable) internally, so O(1) lookups in all `pf`s.

About backing up huge amounts of data: the first backup will be big/slow, but afterwards, it will only add the changes / the new data. Not sure how you would get faster than that using that list approach.

**Comment by 517qf** [comment]
Thanks for this quick and useful reply.  The list with `- /home/*` already worked very well. I just asked because I intend to use this setup for years and small inefficiencies will add up over time. Now I will use `- pp:/home/`.
