### ISSUE TITLE
Log-file badly formatted

### ISSUE THREAD

**Issue by sm8ps** [borgbackup/borg#4104]
First time user here, trying out Borg-Backup with great enthusiasm. The primary results look very promising. Thanks for this great piece of software!
I followed the advice in the docs about logging and redirect all output to a file with redirection '2>>'. The log level is set to INFO via the option -v. 
The resulting log file contains many ^M-characters that I cannot get rid of via the standard recipes like ':%s/^M//' in sed (with ^M correctly inserted via CTRL+V,CTRL+M) or by using dos2unix. Below is an excerpt from a 'borg create' log taken from less output. I replaced sensitive names and so the character count has changed. (NB: I do not worry about the permission errors at the moment as they are completely reasonable.)
```
0 B O 0 B C 0 B D 0 N var/abc/folder/subfolder                                      ^MInitializing cache transaction: Reading config                                                     ^MInitializing cache transaction: Reading chunks                                                     ^MInitializing cache transaction: Reading files                                                      ^M                                                                                                   ^M1.32 MB O 72.06 kB C 72.06 kB D 3 N var/abc/folder/subfolder/fog.log.1        ^M10.50 MB O 554.00 kB C 554.00 kB D 3 N var/abc/folder/subfolder/fog.log.1     ^M/var/abc/folder/subfolder/lost+found: scandir: [Errno 13] Permission denied: '/var/abc/folder/subfolder/lost+found'
12.35 MB O 653.48 kB C 653.48 kB D 5 N var/abc/folder/subfolder/fog.log       ^M/var/abc/folder/subfolder/start: open: [Errno 13] Permission denied: '/var/abc/folder/subfolder/start'
/var/abc/folder/subfolder/finish: open: [Errno 13] Permission denied: '/var/abc/folder/subfolder/finish'
```
This happens with borg-linux64_v1-1-7 on Ubuntu 18.04.1.
Replacing each ^M by a line break (by copying less-output to gedit and replacing the string "^M") makes it look neat as expected albeit with a lot of unnecessary white space.
```
0 B O 0 B C 0 B D 0 N var/abc/folder/subfolder                                      
Initializing cache transaction: Reading config                                                     
Initializing cache transaction: Reading chunks                                                     
Initializing cache transaction: Reading files                                                      
                                                                                                   
1.32 MB O 72.06 kB C 72.06 kB D 3 N var/abc/folder/subfolder/fog.log.1        
10.50 MB O 554.00 kB C 554.00 kB D 3 N var/abc/folder/subfolder/fog.log.1     
/var/abc/folder/subfolder/lost+found: scandir: [Errno 13] Permission denied: '/var/abc/folder/subfolder/lost+found'
12.35 MB O 653.48 kB C 653.48 kB D 5 N var/abc/folder/subfolder/fog.log       
/var/abc/folder/subfolder/start: open: [Errno 13] Permission denied: '/var/abc/folder/subfolder/start'
/var/abc/folder/subfolder/finish: open: [Errno 13] Permission denied: '/var/abc/folder/subfolder/finish'
```

**Comment by sm8ps** [comment]
I think the output comes from the --progress option which was enabled. So this option is quite incompatible with capturing log files via '2>>'-redirection. Is there an easy way to improve on this situation? How about progress output on stdout instead of stderr?

**Comment by ThomasWaldmann** [comment]
Just do not use `--progress` if it is not going to the screen, but to a log file.

**Comment by sm8ps** [comment]
You are right. I thought it would be good to see from the log file what was going on in detail. Like the permission issues but I suppose they do get logged anyways.

**Comment by ThomasWaldmann** [comment]
If there are serious issues, you'll get warning/error level output.
