### ISSUE TITLE
virus scanner slows down 'borg create ...'

### ISSUE THREAD

**Issue by hbkoenig** [borgbackup/borg#4107]
I'm using borg-1.1.7 on Ubuntu 16.04 with Symantec AntiVirus (sav-ant 14.2.RU2.RBv1) installed/running too.

strace on 'borg create ...' shows 

lstat("/data/file1", {st_mode=S_IFREG|0664, st_size=174, ...}) = 0
llistxattr("/data/file1", "", 4096) = 0
open("/data/file1", O_RDONLY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC) = 3
ioctl(3, FS_IOC_GETFLAGS, 0x7fff86912dbc) = 0
close(3)                                = 0
getxattr("/data/file1", "system.posix_acl_access", NULL, 0) = -1 ENODATA (No data available)
getxattr("/data/file1", "system.posix_acl_default", NULL, 0) = -1 ENODATA (No data available)
lstat("/data/file2", {st_mode=S_IFREG|0664, st_size=249, ...}) = 0
...

and it looks like that open() triggers the "rtvscand" virus scanner, thus every open() takes ~2-5 msec for small, old unmodified files which are already in borg backup.

is it possible to tell borg not to use ioctl_iflags and thus avoid the open() and keep the av stuff sleeping == happy ?

or do I have to switch off av scanner while running backups ?
backup without av was ~2h 45m every night, now today with av it's ~11h 40m on a fast server with ~20M typically small/old source files on 15000 RPM spinning rust raid...

**Comment by ThomasWaldmann** [comment]
borg always does full backups, this is why it gets the file metadata from the fs and only reuses the content blocks it alreads has in the repo.

the call that needs a file handle (and thus calls `open()` first) is to get the `bsdflags` (or equivalent on linux), try `--nobsdflags` to not back up that kind of metadata.

**Comment by ThomasWaldmann** [comment]
Note: if open() is super slow due to the virus scanner, you might run into this performance issue again with borg 1.2.

To avoid race conditions and inconsistencies, we target working based on FDs in 1.2 (rather than with path/filenames as in 1.0/1.1), so it will open the file once to get the FD and then do as many as possible calls based on that FD - see the currently open PRs.

**Comment by hbkoenig** [comment]
> the call that needs a file handle (and thus calls `open()` first) is to get the `bsdflags` (or equivalent on linux), try `--nobsdflags` to not back up that kind of metadata.

ACK! 
a quick test with --nobsdflags shows that there are no open() calls for files anymore (only for directories, that's ok) and virus scanner is happily sleeping now;-)
will start another full (in terms of all data/disks) backup again...

> Note: if open() is super slow due to the virus scanner, you might run into this performance issue again with borg 1.2.

ah, good to know!  
I'm thinking of replacing rust by SSDs anyway, then I can do another benchmark without --nobsdflags if it's only the IOPs and seek times, or if just the next bottleneck will show up then;) 


thanks for your quick reply & help!!
