### ISSUE TITLE
Compressing already-compressed files, could they get corrupted?

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#4113]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## Question

I'm currently using the most expensive compression method (zstd,22). I'm wondering about already-compressed files, if they get aggressively compressed again, could they get corrupted somehow? Should I switch to the `auto` compression method?

**Comment by ThomasWaldmann** [comment]
as appropriate for a backup tool (which is not expected to modify contents), borg only has lossless compression algorithms. that always means `uncompress(compress(data)) == data`.

**Comment by fullofcaffeine** [comment]
Thanks for clarifying!
