### ISSUE TITLE
Can I cancel a prune operation?

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#4114]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## Question

If I cancel a prune while it's running, can I consider that archive to be intact or corrupt? 

Why I ask that: I accidentally started pruning an archive that should not have been pruned. The archive was very big, so I managed to Ctrl+C to cancel it in the middle of the operation. Now I'm not sure if I should create a new archive or if this archive is still pristine or somehow corrupted.

**Comment by ThomasWaldmann** [comment]
iirc, borg 1.1 prune does 2 transactions:
- pruning archives, commit.
- compacting the repo, commit.

thus, depending on when you killed it, the result will look differently. but in any case, uncommitted stuff will be rolled back the next time you use the repo and committed stuff should reflect a valid, consistent state.

**Comment by fullofcaffeine** [comment]
Hi Thomas, thanks for the helpful response!

1) What do you mean by "the result will look differently"?
2) So you'd say it's acceptable to kill a prune as a way to completely cancel it?

I tested extracting the archive, and it does *seem* to be alright. Good to know Borg has all these safety transactional measures in place.

**Comment by ThomasWaldmann** [comment]
if you cancel before the first commit, your repo will look unchanged.
if you cancel after it, it will have pruned some archives and committed the change.

**Comment by fullofcaffeine** [comment]
Thanks.

Can I use the output of `borg list` for that archive and compare with a list spit before the accidental prune to verify that it wasn't affected? I did that and the lists match, byte-by-byte.

**Comment by ThomasWaldmann** [comment]
The lists only contain some metadata, so if you compared them, you verified that that is still intact.
To verify an archive, you could extract or dry-run extract it and see if that works.
To verify the repo, you can use borg check.
