### ISSUE TITLE
Permission denied when setting extended attribute on macos

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#4115]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

#### Your borg version (borg -V).

borg 1.1.7

#### Operating system (distribution) and version.

macOS High Sierra 10.13.6

#### Hardware / network configuration, and filesystems used.

APFS (target), NTFS (source, where the borg repo is located)

#### How much data is handled by borg?

~600GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg extract /Volumes/Untitled\ 1/backups/icebox::static-external-hd-icebox

## Describe the problem you're observing.

I'm recovering from the archive mentrioned above, and while it seems to be working fine (it's still in progress at the tie of this writing), I'm getting a lot of errors related to extended attributes:

```
camelcasemotion/.git/objects/41/tmp_obj_yyoVGa: Permission denied when setting extended attribute com.apple.backupdelta.inodeForDeletionOriginal
camelcasemotion/.git/objects/41/tmp_obj_yyoVGa: Permission denied when setting extended attribute com.apple.backupdelta.deletionMarkerAndFile
camelcasemotion/.git/objects/4f/tmp_obj_6BJ1w9: Permission denied when setting extended attribute com.apple.backupdelta.inodeForDeletionOriginal
camelcasemotion/.git/objects/4f/tmp_obj_6BJ1w9: Permission denied when setting extended attribute com.apple.backupdelta.deletionMarkerAndFile
```

Do you know why this happens? Can I just ignore them?

**Comment by ThomasWaldmann** [comment]
I've no idea about these xattrs.

Guess it depends on whether you need them. If not, you can maybe just ignore the warnings.
