### ISSUE TITLE
[QUESTION]: Remote origin

### ISSUE THREAD

**Issue by NefixEstrada** [borgbackup/borg#4119]
Hello,

I'm trying to make a "backup server". This server has the borg repo, but it doesn't have the files. Is there any way to use a "remote origin" when creating the archive? Or should I use sshfs, nfs, smb or something else? When you are creating the archive you can set a remote repository, but I wasn't able to find an option for a remote origin.

Thanks in advance!

**Comment by ThomasWaldmann** [comment]
borg uses push mode (backup client pushes backups to repo server) and does not directly support pull mode. you can find some discussion about "pull mode" in this issue tracker (maybe also in docs/faq).

as a data source, you can use anything you like (for borg it just needs to be visible in a local directory), just make sure it works well enough for what you need.

borg is most efficient for local, posix filesystems that have stable inode numbers - in that case it can gain a lot of speed when processing unchanged files.

**Comment by NefixEstrada** [comment]
Thanks!
