### ISSUE TITLE
llfuse is obsolete, switch to pyfuse3

### ISSUE THREAD

**Issue by jvasile** [borgbackup/borg#4122]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

## Describe the problem you're observing.

`borg mount` requires llfuse, and [llfuse](https://github.com/python-llfuse/python-llfuse) was recently obsoleted:

>  **Warning - no longer maintained**
> 
> Python-LLFUSE is no longer actively maintained. Unless you are stuck with Python 2.x or libfuse 2.x, we recommended to use the pyfuse3 module instead.

Borg should probably develop a plan to evaluate, monitor, and eventually move to [pyfuse3](https://github.com/libfuse/pyfuse3).

**Comment by ThomasWaldmann** [comment]
Interesting, did not notice that yet.

Failing to build `llfuse` is usually due to a missing requirement.

**Comment by ThomasWaldmann** [comment]
https://github.com/libfuse/pyfuse3/commit/cf63be5a65354e20fa6d90fdfc81334382753b11#diff-2eeaed663bd0d25b7e608891384b7298

looks like pyfuse3 started as a fork of llfuse.

**Comment by ThomasWaldmann** [comment]
Requirements:
* Linux kernel 2.6.26 or newer.
* Version 3.3.0 or newer of the libfuse library.

TODO: check FreeBSD and macOS.

**Comment by Akito13** [comment]
I have this problem too, is there a temporary workaround for mounting backups?

**Comment by ThomasWaldmann** [comment]
@Akito13 this issue is to discuss about pyfuse3, not about llfuse installation issues.

if you can't get it working with a source based installation, use a package from your (linux?) distribution or our fat binary packages offered on the github releases page.

**Comment by ThomasWaldmann** [comment]
so, to summarize it for now:
- use latest llfuse version for borg, it works
- we'll check pyfuse3 later, when the requirements are more widespreadly available

**Comment by mist** [comment]
Debian Buster/testing has libfuse 3.4.1 as `libfuse3-3`, https://packages.debian.org/buster/libfuse3-3
Ubuntu Disco/19.04 has 3.2.6, https://packages.ubuntu.com/disco/libfuse3-3

**Comment by shawnl** [comment]
>     use latest llfuse version for borg, it works

llfuse doesn't install correct, unless you use 1.3.2 or earlier, causing the test suite to break:

```
Collecting llfuse<2.0 (from -r requirements.d/fuse.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/75/b4/5248459ec0e7e1608814915479cb13e5baf89034b572e3d74d5c9219dd31/llfuse-1.3.6.tar.bz2
ERROR: Files/directories not found in /tmp/pip-install-n7pndsvn/llfuse/pip-egg-info
```

**Comment by altendky** [comment]
`sudo apt-get install libfuse-dev` then installing llfuse got it to install for me (got the same error before this).

**Comment by shawnl** [comment]
Yeah I was just realizing this...

**Comment by flokli** [comment]
@thefloweringash stumbled over this. Can you check on the situation of pyfuse3 on MacOS?

**Comment by rvanlaar** [comment]
For other readers and google search:

`borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']`

Was fixed by: 
`sudo apt-get install libfuse-dev`
`pipsi uninstall borgbackup`
`pipsi install borgbackup[fuse]`

Beware: I used pipsi for installing borg, use the tool you used while install borg to uninstall and reinstall borg.

**Comment by ThomasWaldmann** [comment]
PSA: This is going off-topic and I'll delete all comments from here tomorrow that have nothing to do with the issue title.

**Comment by FelixSchwarz** [comment]
- Fedora 31+: `fuse3` 3.6.1
- RHEL 8: `fuse3` 3.2.1-12.el8 (`python3-llfuse` 1.3.6), kernel 4.18.0
- RHEL 7 (EPEL): `fuse3` 3.6.1-2.el7 (`python36-llfuse` 1.0), kernel 3.10.0

**Comment by ThomasWaldmann** [comment]
I locked this issue because people where discussing their llfuse installation troubles here, which is not the topic of this issue.

**Comment by ThomasWaldmann** [comment]
Removed "later". Guess we need to do this soon as we discovered in #5372 that llfuse is broken on python 3.9. :-(

**Comment by ThomasWaldmann** [comment]
Seems there are issues on freebsd and osxfuse (macOS) - see pyfuse3 issue tracker.

**Comment by ThomasWaldmann** [comment]
see #5407.
