### ISSUE TITLE
Can I safely change ownership of the files inside a borg repo?

### ISSUE THREAD

**Issue by tchaffee** [borgbackup/borg#4126]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.1.5
#### Operating system (distribution) and version.
Ubuntu 18.04.1
#### Hardware / network configuration, and filesystems used.
Dell XPS 15 Laptop
#### How much data is handled by borg?
Not sure. Around 35GB?
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`sudo borg create ...` 

## Describe the problem you're observing.
Since I am backing up the entire system including root (/) I am using `sudo`. So the backed up files are owned by root. But I want to copy the backup to Dropbox and Dropbox is running under my user, not root. Can I change the borg files to be owned by me?

**Comment by ThomasWaldmann** [comment]
see the workaround in #1869

**Comment by motwok** [comment]
my solution:

1. add setgid to the repository folder and all subfolders:
`find %REPOPATH% -type d -exec chmod g+s {} +`

2. change group for all files and folders
`chown :%GROUPNAME% -R %REPOPATH%`

3. add --umask 0027 (read rights for group) to the borg commandline.
`borg ... --umask 0027 ....`
see man umask for other posible values
using "umask 0027" before the borg command does not work.

Emmo

**Comment by ThomasWaldmann** [comment]
solved.
