### ISSUE TITLE
flake8 3.6.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4128]
https://travis-ci.org/borgbackup/borg/jobs/445865375

looks like it warns about addtl. stuff now.

we need to exclude all these (asap) and (later) re-enable them in the same changeset as the fix.

**Comment by motwok** [comment]
crap, murphey  caught me with this:
My first PR and i searched for hours to find "my"r error. 

Emmo

**Comment by ThomasWaldmann** [comment]
as this affects all PRs right now, I am fixing this, see PR #4135.

**Comment by ThomasWaldmann** [comment]
fixed by merging #4135 - please everybody rebase onto current master.
