### ISSUE TITLE
edit link broken on docs

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#413]
on the top right of: 

https://borgbackup.readthedocs.org/en/stable/installation.html

there is a link to:

https://github.com/borgbackup/borg/blob/c082b9c58ae97d23bca76dade218577339e871f7/docs/installation.rst

which is a 404.

/me blames rtd.

**Comment by ThomasWaldmann** [comment]
strange, that commit hash does not exist. well, let's see if it stays broken after the next doc updates.

**Comment by ThomasWaldmann** [comment]
it seems to be related to "stable" version there, "latest" and "0.28.1" work ok.

how is "stable" supposed to work anyway? do we need to add a tag for it maybe?

**Comment by ThomasWaldmann** [comment]
https://github.com/rtfd/readthedocs.org/issues/1820

As this is not a borgbackup issue, I am closing it here.
