### ISSUE TITLE
--exclude-from  ignored if creating backup of the full home directory

### ISSUE THREAD

**Issue by talbym** [borgbackup/borg#4132]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

## System and OS information:
Linux, amd64, Debian 9 ("stretch", stable)
borgbackup installed from the stretch-backports repository

#### Your borg version (borg -V).
1.1.7

#### Hardware / network configuration, and filesystems used.
The OS is completely installed to and thus runs from a USB3-pendrive (ext4)
backup should copy from USB3-pendrive (ext4) to local HDD (ext4)
4 GB RAM

#### How much data is handled by borg?
250000 files occupying 25 GB in the home directory located on the USB3-pendrive

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive ~`
`borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive /home/myusername`

in Detail:
```
BorgRepo="._BACKUP/BORG/MyRepo"
BorgArchive="MyArchive_`date +%Y%m%d_%H%M`"
BorgExcludes="._mystuff/BORG_EXCLUDES.txt"
BorgConfig="-psv --noatime --exclude-caches --keep-exclude-tags -C zstd,1"

borg init -v --encryption=none $BorgRepo
borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive ~

```
"._mystuff/BORG_EXCLUDES.txt":
sh:._BACKUP/
sh:.cache/
sh:.dbus/
HDD_on_PC/

As dirs "._BACKUP" and "HDD_on_PC" are softlinks to another partition, I observed that they are anyway excluded, so I would not have to mention them in this file. However, I do so to be sure that they stay excluded even when handling of softlinks would change. This does not appear to be a problem here, but I comment it for completeness. 

## Describe the problem you're observing.
The following works as expected and correctly handels the excluded dirs. I find the created archive to only contain the dir entries for .dbus and .cache, but no contents inside these dirs, while the TEMP/test dir is fully copied to the backup:
`borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive .dbus`
`borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive .cache`
`borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive .dbus .cache TEMP/test`

But if I want to make a backup of my full home directory containing 250000 files occupying 25 GB, then the excludes are NOT applied! The ".dbus" and ".cache" dirs with all their contents become copied to the backup! It does not depend on how I refer to the home dir, both versions show the bug:
`borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive ~`
`borg create $BorgConfig --exclude-from $BorgExcludes $BorgRepo::$BorgArchive /home/myusername`
The backup itself (and deduplication upon repeated backups) runs without error messages and I do not observe other issues. But my --excludes-from is ignored if backing up all "~".
  
#### Can you reproduce the problem? 
I deleted the repository, initialized a new one, did so several times.
I made a backup of small test dirs several times, and I did so with the big home directory several times.
The problem is reproducibly appearing if treating all the 250000 files containing 25 GB home dir "~", but reproducibly not appearing if only working with the ".dbus" or ".cache" or /TEMP/test dirs as small test directories.
The bug appears if working logged in as the user to KDE PLASMA and there working in a terminal emulator while all other apparent apps are closed, and it the same appears if logged in as the user on a by STRG+ALT+F1 reachable console not being logged in to a graphical X11 session.

**Comment by talbym** [comment]
You have been right. THANK YOU VERY MUCH!
Mixing the use of the absolute path in the "borg create " command with the use of relative paths in the Exclude file caused the problem! I verified that accordingly it also doesn't work if combining a relative path like in "borg create repo::archive ."  with absolute paths in the Exclude file "sh:/home/myusername/.cache/". 


I verified the following two combinations, not mixing the usage of relative and absolute paths in the borg command and Exclude file, to work:

_using relative paths only works:_
BorgExcludes="BORG_EXCLUDES.txt"
with "BORG_EXCLUDES.txt":
._BACKUP/
.cache/
.dbus/
`borg create --exclude-from $BorgExcludes repo::archive .`
_Watch out for the trailing "." (a relative path) used when calling the command from the home directory being the work directory!_

_using absolute paths only works:_
BorgExcludes="BORG_EXCLUDES.txt"
with "BORG_EXCLUDES.txt":
/home/myusername/._BACKUP/
/home/myusername/.cache/
/home/myusername/.dbus/
`borg create --exclude-from $BorgExcludes repo::archive /home/myusername`
_Watch out for actually using the leading "/" in the Exclude file, without the leading "/" it didn't work!_

**Comment by ilippert** [comment]
> This is probably because you specify the full path /home/myusername (equivalently ~) as the root of the backup, but relative paths in the exclude file. It's probably best to use full paths in both places, except that in the exclude file you should leave off the leading /.

Sorry, just to check whether I understand this correctly:
I cannot backup, say, `\home`, and then exclude-from a file that includes a line that specifies `*.tikz`?

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns

please check the docs.

**Comment by ilippert** [comment]
> https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns
> 
> please check the docs.

Thanks a lot, of course I did try to comprehend precisely that doc before. But, alas, after reading it (now about a third time), I still feel uncertainty. And instead of raising a new issue, I am asking that on a seemingly closely related issue.

**Comment by ThomasWaldmann** [comment]
Yeah, pointing at precisely the place in that part of the docs which you do not understand would be helpful, separate ticket.
