### ISSUE TITLE
can't browse html offline documentation

### ISSUE THREAD

**Issue by seguri** [borgbackup/borg#4133]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/borgbackup/downloads/

## Expected Result

Download HTMLZip documentation. Browse the documentation without an internet connection.

## Actual Result

I tested every html zip down to 1.1.3 and none of them loads successfully. `index.html` is stuck in a refresh loop. It still tries to contact external urls like app.travis-ci.org, assets.readthedocs.org, asciinema.org (the video displayed in the home page).

**Comment by ThomasWaldmann** [comment]
likely these badge icons of the README and the asciinema demo.

we want to show them on the online site. not sure whether we can have different content for the download for offline usage.
