### ISSUE TITLE
Exception ignored in: <bound method RemoteRepository.__del__ of <RemoteRepository

### ISSUE THREAD

**Issue by aiso-net** [borgbackup/borg#4139]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Bug

## System information. For client/server mode post info for both machines.
Both systems are Python 2.7.5

#### Your borg version (borg -V).
borg 1.1.7

#### Operating system (distribution) and version.
CentOS 7 (3.10.0-862.3.3.el7.x86_64) for borg repo server, CloudLinux 7 (3.10.0-714.10.2.lve1.5.19.7.el7.x86_64) for server being backed up.

#### Hardware / network configuration, and filesystems used.
Borg repo: Physical server with RAID card based FS mounted to /home and two network ports, 1 internet, 1 local network. /home is xfs
Server being backed up: VM on KVM with two network ports, 1 internet, 1 local. Backups being done over local network, backup of /var and /etc both of which are ext4

#### How much data is handled by borg?
```
[root@backup1 ~]# borg info /home/backups/webXXXX
Repository ID: 134
Location: /home/backups/webXXXX
Encrypted: No
Cache: /root/.cache/borg/1234
Security dir: /root/.config/borg/security/1234
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:               19.92 TB             16.29 TB            126.21 GB

                       Unique chunks         Total chunks
Chunk index:                 1346097            205748203
[root@backup1 ~]# borg check -v --repository-only /home/backups/webXXXX
Starting repository check
Starting repository index check
Completed repository check, no problems found.
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
[root@webXXXX ~]# sshpass -p 'mypass' borg check --repository-only root@IP-OF-REMOTE-SERVER:/home/backups/webXXXX
Exception ignored in: <bound method RemoteRepository.__del__ of <RemoteRepository ssh://root@IP-OF-REMOTE-SERVER:/home/backups/webXXXX>>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/remote.py", line 618, in __del__
    assert False, 'cleanup happened in Repository.__del__'
AssertionError: cleanup happened in Repository.__del__
Received SIGHUP.
[root@webXXXX ~]#
```

## Describe the problem you're observing.
After what appears to be a network crash, I run the repo check command on the server thats being backed up and it errors out. Same command on backup repo server does not have any issue.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes but running the above command. I have not tried rebooting the server being backed up, but I assume that would not help.

#### Include any warning/errors/backtraces from the system logs
No

**Comment by aiso-net** [comment]
Version are the same, per the issue post and I installed it using yum:
```
[root@webXXXX ~]# rpm -qa | grep borg
borgbackup-1.1.7-1.el7.x86_64
```

**Comment by aiso-net** [comment]
Any update (been without borg for a week) ?

**Comment by ThomasWaldmann** [comment]
Well, I don't have much information about the issue.
Usually, if borg crashes, it leaves a traceback where one can see what went wrong.
But what you posted above is something very generic and not from the real problem source, but just a side effect when python disposes objects.

Also not sure where `Received SIGHUP.` comes from?

You could try borg directly on the repo server machine (against same repo, using same borg command), maybe you can see the root cause then.

**Comment by ThomasWaldmann** [comment]
Maybe also check if there is something wrong with your ssh or network connection.

**Comment by aiso-net** [comment]
Thanks, and sorry for the bother...SSH issue, the root know_hosts file was empty on every server causing SSH to want to very authenticity again, must have had a solar flare.
