### ISSUE TITLE
positive feedback borg 0.28.1

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#414]
during the last days I ran several tests:

- created a "bigger" archive
- deleted .cache/borg and hints.* index.*
- borg check --repair to get a fresh hints/index and borg info to get a fresh cache
- then restored a part of the directory tree
- everthing worked as expected
```
Command line: /usr/bin/borg create -s -p -v -C lzma,9 /cygdrive/x/vm.borg::VM1 /cygdrive/v/VM1
Number of files: 4879

                       Original size      Compressed size    Deduplicated size
This archive:                2.43 TB              1.42 TB            653.53 GB
All archives:                2.43 TB              1.42 TB            653.53 GB

                       Unique chunks         Total chunks
Chunk index:                13443595             30348775
```

**Comment by ThomasWaldmann** [comment]
Thanks for the feedback. BTW, there is another (meanwhile closed) issue about scalability testing, maybe you can append it to #216.

What do you mean by "eth"? Typo?

Also, please look at the markup I added to make your issue look better.
