### ISSUE TITLE
_hashindex.c, hashindex.pyx some reworking/rethinking needed 

### ISSUE THREAD

**Issue by motwok** [borgbackup/borg#4145]
From the coding style the c and the cython every change is dangerous.
- pointer calculation on "void *" (replaced with "unsigned char*") is not comprehensible.
- in cython part also pointer calculations are used
- use types where it is possible (typesave)
- vital checks on key and value length are missing.
- memorymanagement, the complete index is in one allocatoion
....
(this is just from a short review, may i oversee some additional things, may i overrate)

**Comment by ThomasWaldmann** [comment]
the problem with non "just pointers to bytes" is that the code is written in a generic way.
so, as long as key size and total record size is given correctly, it can deal with anything.

allocation: not sure how to easily and efficiently do that better. we have really a lot of buckets, so allocating buckets individually is not efficient. writing some own memory management for more-than-a-bucket but less-than-everything might be overkill and introduce new bugs.

**Comment by motwok** [comment]
@ThomasWaldmann 
I meant this as a "Later" task, please set the tag.

> .. writing some own memory management ...
I meant was a better way to allocate this memory (and a better way to use it). 

The most important thing is the first line: "every change is dangerous."... this must change.
This is no easy and no quick task, it needs to understand the complete thing in detail bevor any change is done.

**Comment by ThomasWaldmann** [comment]
Likely, we'll just get rid of the borg 1.x `hashindex` C/Cython implementation by using `borghash` for borg2.

https://github.com/borgbackup/borghash

It is a pure Cython implementation, no C code anymore.

In borg, there will only be a small wrapper around borghash to fix api differences.
