### ISSUE TITLE
Borgbackup in Docker can't find /repo/data/0/1

### ISSUE THREAD

**Issue by ShadowRylander** [borgbackup/borg#4149]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug / Question

#### Your borg version (borg -V).

1.1.7

#### Operating system (distribution) and version.

WSL running Docker, with a container of [Minideb](https://github.com/bitnami/minideb)

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Any command trying to access the repo.

## Describe the problem you're observing.

Any command trying to access a mounted repository, whether mounting the repository itself in docker, or else mounting the folder containing the repo, via `-v /drive/host_repo:/path/container_repo`, is resulting in something similar to `FileNotFoundError: [Errno 2] No such file or directory: '/psntest/data/0/1'` every single time, whether in a newly created repo in the mounted folder, or a pre-established repo. However, repositories created in the container itself are accessed just fine, leading me to believe this is a problem with docker. This problem occurs on the `minideb` and `alpine` images, which I chose due to their small size.

The command I'm using is essentially this:
```
docker run -v /s/etc/repo:/repo -v /s/etc/source:/source --rm container
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Described in the previous statement.

#### Include any warning/errors/backtraces from the system logs

`FileNotFoundError: [Errno 2] No such file or directory: '/repo/data/0/1'`

**Comment by ShadowRylander** [comment]
I would also like to note that:
1. There are other borgbackup docker containers available, and
2. I tried installing `ntfs-3g` within the container, as the `/s/`, i.e. `S:\`, drive is `NTFS`, but apparently, that didn't work.

**Comment by ThomasWaldmann** [comment]
If you run into fundamental issues like files not behaving as they should and the issues are not present when using some proven filesystem (like ext4), the likelihood that it's just your filesystem being crappy is rather high.

I don't know much about how docker deals with that stuff, so I can't comment on that specifically.

**Comment by ShadowRylander** [comment]
Ah; ok. If that's the case, I'll ask this on the Docker [forum] as well. Thank you!

**Comment by ShadowRylander** [comment]
It's... fixed? Maybe after running a TRIM operation? Dunno. Thanks anyway!
