### ISSUE TITLE
Document how to monitor borg repo (e.g. Nagios)

### ISSUE THREAD

**Issue by problame** [borgbackup/borg#4155]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## Describe the problem you're observing.

I use a cron-job for making frequent backups to a remote server.
That connection is expected to be flaky (remote server down, firewall overloaded, etc).
Borg runs into a timeout, prints the timeout error on the command line and exits with non-zero exit status.
I get an email from cron informing me of that failed backup.
However, the backup 1h after works.
And I am OK with loosing that one failed backup, as long as there is one backup in the target repo that is less than 24h old.

I want to monitor the target repo _on the target machine_: is there a backup with prefix X in the last 24h.
I cannot use the `borg list` command because

1. the regular client and the monitoring job might interfere (flock?)
2. (more importantly) the repo is encrypted, so `borg list` will prompt me with a password.

I suppose there is some way to do this with `find` or similar, but the procedure is not documented.
Ideally, `borg` would provide such functionality itself.
Do you have any suggestions for this use case?

**Comment by ThomasWaldmann** [comment]
As the repo on the server is usually encrypted, you can't do that on the repo server.
