### ISSUE TITLE
Renewed files in the source are recognized as modified continuously

### ISSUE THREAD

**Issue by AIexBV** [borgbackup/borg#4159]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Potential bug

## System information. For client/server mode post info for both machines.
Synology Diskstation DJ-115j - DSM 6.2.1-23824 Update 1

#### Your borg version (borg -V).
V1.1.5

#### Operating system (distribution) and version.
Linux 3.2.40

#### Hardware / network configuration, and filesystems used.
HDD ext4

#### How much data is handled by borg?
Repo size 170 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create  --verbose  --filter AME   --list --stats --show-rc  --compression auto,zstd,3 
   /volume1/BackupRepos::'Backup-{now}'  /volume1/Backup/Pictures

## Describe the problem you're observing.
After removing and restoring a folder with pictures (jpg) from the backup-source, the backup-process recognizes these restored files as modified continuously for each future backup (create).
Deleting the cache (delete --cache-only) didn´t help. Removing the archives step by step and backup again in between, didn´t help. 

The user/group of the restored files is the same as before deletion. The file permissions may have changed.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you 
Didn´t try to reproduce, because the CPU is very slow and building the full repo blocks the CPU for a whole day. But it should be reproducible quite easy: Create a backup, delete a folder in the source and restore the folder in the source. Then repeat the backup several times. It should show the restored files as modified each time.
The backup-archiv is functional, but the backup process takes much longer as it took before. Finally I had to init a new repository to achieve the usual backup performance.

#### Include any warning/errors/backtraces from the system logs
rc result is 0 each time.

**Comment by infectormp** [comment]
@AIexBV can you update to 1.1.7 and try again?

**Comment by AIexBV** [comment]
I checked the issue in CygWin with borg version 1.1.7. After restoring a deleted folder, the next backup recognized the files as modified and then the next backup didn´t find any modified files. This seems to be the correct behaviour.

The build I use is provided by the SynoCommunity. So I have to wait, until they provide a new build. I am not able to set up a compile environment.
