### ISSUE TITLE
ssh borg mount fails with utf-8 encoding error

### ISSUE THREAD

**Issue by step-** [borgbackup/borg#4162]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, in docs and FAQ I didn't see anything that seemed to apply.
In GitHub issues I found
* #3202 which is in the area of `mount` + `utf-8`, but my issue looks different.
* #4112 which is practically the same error message of mine, but unlike mine it happens on the local machine

## Is this a BUG / ISSUE report or a QUESTION?

issue report

#### Your borg version (borg -V).
Borg: 1.1.7  Python: CPython 3.5.5
#### Operating system (distribution) and version.
Platform: Linux lcm 4.19.1 #1 SMP x86_64
Fatdog64 Linux 721
#### Hardware / network configuration, and filesystems used.
ext4
#### How much data is handled by borg?
1.5GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
It's an ssh command that runs on the server where borg in installed. Please note: the same command runs in a loop for three archives located in the same repo. It works just fine for the first two archives. Borg prints an error for the third archive.
```sh
ssh -i /root/.ssh/lcm_rsa root@lcm.local '
  export BORG_BASE_DIR=/mnt/S/repo
  ! mountpoint -q /mnt/COMMON &&
  mkdir -p /mnt/COMMON &&
  borg mount /mnt/S/repo/COMMON::COMMON-20181109_1541768992 /mnt/COMMON
  '
```

## Describe the problem you're observing.
For the third archive only Borg prints:
```
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4434, in main
  File "borg/archiver.py", line 4366, in run
  File "borg/archiver.py", line 1352, in do_mount
  File "borg/archiver.py", line 152, in wrapper
  File "borg/archiver.py", line 1362, in _do_mount
  File "borg/fuse.py", line 323, in mount
  File "borg/fuse.py", line 252, in _create_filesystem
  File "borg/fuse.py", line 380, in process_archive
  File "os.py", line 862, in fsencode
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 32: ordinal not in range(128)

Platform: Linux lcm 4.19.1 #1 SMP Wed Nov 7 18:52:51 EST 2018 x86_64
Linux:   
Borg: 1.1.7  Python: CPython 3.5.5
PID: 7667  CWD: /root
sys.argv: ['borg', 'mount', '/mnt/S/repo/COMMON::COMMON-20181109_1541768992', '/mnt/COMMON']
SSH_ORIGINAL_COMMAND: None
```
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, I can reproduce the problem.
Troubleshooting:`
* Executed the failing  command directly on the server through a terminal window (cut and pasted from this report) : it works - `COMMON-20181109_1541768992` is mounted to /mnt/COMMON
* Edited the command to change the dash character in the in archive name to, well, a dash character, and remounted : it works.  Rationale: since Unicode x2013 is an EN dash, I though maybe I mistyped a dash (but note again: the command comes from the third iteration in a loop, and the first two iterations work just fine).

Please note again: locally `borg mount` doesn't fail. It fails when `ssh` executes `borg mount`.

#### Include any warning/errors/backtraces from the system logs
See above.

**Comment by infectormp** [comment]
Maybe you have non UTF-8 locale in `ssh` env?

**Comment by step-** [comment]
You are correct. I didn't realize that the remote server runs dropbear daemon instead of OpenSSH. Therefore all my client-side ssh environment settings didn't export. I have updated my scripts. Thank you.
