### ISSUE TITLE
Standalone binaries seem to be x32/64 only

### ISSUE THREAD

**Issue by sm8ps** [borgbackup/borg#4165]
I have been using a Raspberry Pi to pull Borgbackup repositories via rsync over to a remote location in some untrusted environment. This should serve for disaster recovery and in normal use is not touched. In order to test this strategy, I wanted to install Borgbackup on the remote device so as to avoid copying the whole archive back to its original location.

I prefer using standalone binaries of the same version in all locations. So I installed the current borg-linux32 (1.1.7) to the Raspberry Pi (version 2B, armv7, 32 bit architecture). However, the binary segfaults. 
```
file borg-1.1.7 
borg-1.1.7: ELF 32-bit LSB executable, Intel 80386 (...)
```
I would suggest to specify the architecture on the installation page in the [docs](https://borgbackup.readthedocs.io/en/stable/installation.html) as well as on the [download page](https://github.com/borgbackup/borg/releases). 

Furthermore, I would be very grateful for a standalone binary for the armv7 architecture. I am sorry to say that I lack technical expertise to understand the process for doing so.

**Comment by ThomasWaldmann** [comment]
all binaries from borgbackup/borg releases are for x86/x64 (intel/amd).
just search this issue tracker to find arm binaries.

**Comment by infectormp** [comment]
@ThomasWaldmann maybe need add info about ARM builds to [docs](https://borgbackup.readthedocs.io/en/stable/installation.html#standalone-binary)?

**Comment by sm8ps** [comment]
Thanks for the explanations and the link to the ARM builds. I would also suggest adding this information to the docs.

**Comment by ThomasWaldmann** [comment]
fixed.
