### ISSUE TITLE
Init fails with invalid location format / environmat variables not getting picked up

### ISSUE THREAD

**Issue by alpipego** [borgbackup/borg#4178]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes
I've followed this manual: https://roll.urown.net/desktop/borg-backup.html https://roll.urown.net/NAS/borg-backup-server.html (left out the ssh forced command for now).

## Is this a BUG / ISSUE report or a QUESTION?

Question for now 

### Client

Platform: Linux precision 4.19.1-arch1-1-ARCH #1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018 x86_64
Linux: Antergos Linux 18.9 ISO-Rolling
Borg: 1.1.7  Python: CPython 3.7.1

### Server

Platform: Linux Nass 4.4.15+ #15284 SMP PREEMPT Mon Jul 9 23:05:28 CST 2018 x86_64
Linux:   
Borg: 1.1.5  Python: CPython 3.5.2

#### Hardware / network configuration, and filesystems used.

Synology Disk Station / Local Network / Ext4

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg init --encryption=keyfile-blake2`

## Describe the problem you're observing.

The `init` command fails with `borg init: error: argument REPOSITORY: Invalid location format: ""` although the env var `BORG_REPO` is set. If I explicitly pass it, i.e. `borg init $BORG_REPO` the error pretty much stays the same `borg init: error: argument REPOSITORY: Invalid location format: "ssh://borg-backup@192.168.1.131:/volume1/BorgBackup/precision"` with the correct path now. 

I suspect the environment variables are not picked up and thus `BORG_RSH` is not passed to the command as well?!

SSHing to remote machine works with `ssh borg-backup@192.168.1.131 -i PATHTOKEYFILE`

**Comment by ThomasWaldmann** [comment]
your repo url is invalid (remove the `:` after the ip), see also https://borgbackup.readthedocs.io/en/stable/usage/general.html#repository-urls .

obviously also the borg error message is less than great for the case when it reads the url from `$BORG_REPO`.

**Comment by ThomasWaldmann** [comment]
your main issue is a bug in the roll.urown.net docs, so you need to report that to them.

**Comment by alpipego** [comment]
Umpf. Thanks, I thought I had triple checked that. :+1:
