### ISSUE TITLE
How to define correct patterns to revert backup logic : exclude all by default, and add only desired folders.

### ISSUE THREAD

**Issue by reyman** [borgbackup/borg#4182]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes !

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
1.1.7

#### Operating system (distribution) and version.
Ubuntu 18.04

#### Hardware / network configuration, and filesystems used.

core I7, ethernet 100mb, ext4

#### How much data is handled by borg?

50go

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

REPOSITORY=/media/myname/datacenter/personnels/reycoseb/BACKUP/

borg create -v --dry-run --list --compression zlib,9   --patterns-from patterns.lst      $REPOSITORY::'{hostname}-{now:%Y-%m-%d}' 

`patterns.lst` contains 

```
R /home
- pp:/home/
+ /home/myname/Projets
+ /home/myname/Bureau
+ /home/myname/TRASH
+ /home/myname/Mail
+ /home/myname/Source
+ /home/myname/Backup
+ /home/myname/Data
+ /home/myname/.config
+ /home/myname/.dotfiles
+ /home/myname/.ssh
+ /home/myname/.zotero
```

## Describe the problem you're observing.

Into my  `/home/myname` folder i want to backup only the + folder, everything else is excluded.

I look to documentation of pattern, and also to other issue described here, but i cannot produce the desired behavior ... 

Thanks for your help

**Comment by reyman** [comment]
Yes, i try :/

**Comment by reyman** [comment]
Up the question, any idea anyone ?

**Comment by infectormp** [comment]
Look like answer was here https://github.com/borgbackup/borg/issues/4228#issuecomment-449650929
