### ISSUE TITLE
speed: borg vs rsync for cPanel account

### ISSUE THREAD

**Issue by enboig** [borgbackup/borg#4190]
* Adding version: borg 1.1.7

I have a script to backup my VPS webserver (web+mail+mysqldumps) accounts using rsync. I am exploring changing rsync to borg to have larger version history, but it is way slower:

small account (478.06 MB):
borg: 57.91 seconds
rsync: 0m3.762s

mid size (2.18 GB):
borg:  2 minutes 18.17 seconds
rsync: 0m5.974s

big size (15.87 GB):
borg: 14 minutes 59.75 seconds
rsync: 0m25.863s

huge (133.50 GB):
borg: 2 hours 7 minutes 38.05 seconds
rsync: 4m40.872s

I create my backups with 
```
borg create --stats --verbose --filter AME --list --show-rc --compression auto,zstd ::'{hostname}-account-{now}'  /home/account
```
Both backups go from server A to B and are written in the same RAID disk.

The backup involve lots of small text files, should I have set special parameters when creating the repository?

Are there SSH options to improve the speed? it a fibre connection, so there shouldn't be any problem.

**Comment by enboig** [comment]
I have just discovered https://github.com/borgbackup/borg/issues/3039 ; but I don't know if this is related to my case or how to check it.

**Comment by ThomasWaldmann** [comment]
rsync doesn't do much with the data, it just copies them from a to b.

borg chunks, hashes/deduplicates, compresses, encrypts, authenticates the data, so it is expected to need more resources (cpu, ram, time, ...) than rsync.

for a practical comparison, you should not only compare the first run (which is slowest), but also subsequent runs (which might be faster if there is duplicate data).

yes, it can also be that borg is slower because it cares more for file metadata than rsync, not sure about that.

**Comment by enboig** [comment]
I assumed as both only transmitted changed data, the would get similar speed. Usually bandwidth is the bottle neck and compression should help borg. I didn't thought about encryption. Deduplication should also help borg, and having a big repository. I could imagine borg being slower, but not that much.

And it was fifth daily run.

I will try and unencrypted and uncompressed backup in a week, and try to find bottle neck

**Comment by enboig** [comment]
Cheking the logs I notice unchanged files are upload again:
```
A /home/acount/public_html/......gif
A /home/acount/public_html/......jpg
```
It is a VPS and home is mounted, so maybe it is related to inodes... I will check different values for --files-cache

**Comment by enboig** [comment]
done: 1.1.7

**Comment by enboig** [comment]
Again "static" (php files, images, etc...) files are added again....
I run borg with:
```
/root/bin/borg create               \
    --stats                         \
    --files-cache ctime,size        \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --show-rc                       \
    --compression auto,zstd         \
    --exclude '/home/'$1'/tmp/*'           \
    ::'{hostname}-'$1'-{now}'       \
    /home/$1
```
The script is called in a loop for each server account

**Comment by enboig** [comment]
The filesystem in the VPS is:
```
/dev/mapper/vg_label-lv_home /home ext4 rw,usrjquota=quota.user,jqfmt=vfsv0 0 0
```

**Comment by infectormp** [comment]
To complete the experiment now you need try `--ignore-inode`

**Comment by knutov** [comment]
@enboig Is's slow becouse you are using ztsd to compress. Change it to LZ4 and it will be pretty fast.

**Comment by enboig** [comment]
I get a warning; and applied extra flags.
```
Warning: "--ignore-inode" has been deprecated. Use "--files-cache=ctime,size" or "...=mtime,size" instead.
```
@knutov I changed compression, it may help, but my problem is all files appear to be new every time

I think --nobsdflags did the trick. I don't know why, but in my last backup log, there wasn't a single file marked as "M", all were "A". Now I am running it manually and everything seems fine.

Thanks a lot, I will wait some days to inform back if everything is working as expected.

**Comment by infectormp** [comment]
@enboig can your problem be related to https://github.com/borgbackup/borg/issues/4192

**Comment by enboig** [comment]
It seems the same issue; I just rised the BORG_FILES_CACHE_TTL.
I will run twice the script and check times and cache size

**Comment by enboig** [comment]
I backup 45 sets in a row daily; I set BORG_FILES_CACHE_TTL=50; what may be an advisable value? I thouhgt "2X + _[some margin]_" would suffice, but after watching the first log it don't appear so.

**Comment by ThomasWaldmann** [comment]
X should be ok already.

**Comment by enboig** [comment]
I forgot to use ```EXPORT``` for BORG_FILES_CACHE_TTL ; making a new batch of tests

**Comment by enboig** [comment]
Now everything work as expected, being borg faster than rsync. It wasn't a problem with ```--files-cache``` neither ```--nobsdflags```

Thanks a lot for your help!

**Comment by ThomasWaldmann** [comment]
So, what was the problem?

**Comment by enboig** [comment]
I forgot to use ```EXPORT``` for BORG_FILES_CACHE_TTL ; so the variable didn't make it to borg process.
