### ISSUE TITLE
borg create extremely slow on every second run

### ISSUE THREAD

**Issue by sb-otrs** [borgbackup/borg#4192]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE or BUG

#### Your borg version (borg -V).
borg 1.1.7 (binary)

#### Operating system (distribution) and version.
Ubuntu 17.10

#### Hardware / network configuration, and filesystems used.
Local backup between two hard drives (8TB Seagate IronWolf), both with ext4 (mounted: rw,noatime,nodiratime,data=ordered).

#### How much data is handled by borg?
~4TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
/usr/bin/ionice -c 3 /usr/local/bin/borg create --stats --files-cache ctime,size,inode --numeric-owner /data/borgbackup::transfer-data_$(date +"%Y-%m-%d_%H-%M-%S") /transfer

## Describe the problem you're observing.
I'm doing a nightly backup of my data partition which usually has minimal changes. Usual backup duration is <2 minutes, but every second time it takes >11 hours. The slow backup time combined with the amount of data in play (~4TB) and the hard disk speed leads me to believe that it does in fact read all of the files instead of using the cache for efficacy.

Example (some lines redacted):
```
Archive name: transfer-data_2018-11-29_03-32-36
Archive fingerprint: XXX
Comment: 
Hostname: XXX
Username: root
Time (start): Thu, 2018-11-29 03:32:37
Time (end): Thu, 2018-11-29 03:34:18
Duration: 1 minutes 41.12 seconds
Number of files: 504522
Command line: /usr/local/bin/borg create --stats --files-cache ctime,size,inode --numeric-owner /data/borgbackup::transfer-data_2018-11-29_03-32-36 /transfer
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                4.08 TB              4.08 TB             42.13 kB
All archives:               50.41 TB             50.05 TB              4.59 TB

                       Unique chunks         Total chunks
Chunk index:                 3684311             31092934

Archive name: transfer-data_2018-11-30_03-34-00
Archive fingerprint: XXX
Comment: 
Hostname: XXX
Username: root
Time (start): Fri, 2018-11-30 03:34:01
Time (end): Fri, 2018-11-30 14:11:13
Duration: 10 hours 37 minutes 12.79 seconds
Number of files: 504562
Command line: /usr/local/bin/borg create --stats --files-cache ctime,size,inode --numeric-owner /data/borgbackup::transfer-data_2018-11-30_03-34-00 /transfer
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                4.16 TB              4.16 TB              4.48 MB
All archives:               50.41 TB             50.05 TB              4.59 TB

                       Unique chunks         Total chunks
Chunk index:                 3684311             31092934

Archive name: transfer-data_2018-12-01_03-32-35
Archive fingerprint: XXX
Comment: 
Hostname: XXX
Username: root
Time (start): Sat, 2018-12-01 03:32:36
Time (end): Sat, 2018-12-01 03:34:14
Duration: 1 minutes 38.10 seconds
Number of files: 504523
Command line: /usr/local/bin/borg create --stats --files-cache ctime,size,inode --numeric-owner /data/borgbackup::transfer-data_2018-12-01_03-32-35 /transfer
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                4.08 TB              4.08 TB            142.98 kB
All archives:               50.41 TB             50.05 TB              4.59 TB

                       Unique chunks         Total chunks
Chunk index:                 3684311             31092934
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I have not been able to work around this. The '--files-cache' option has been modified several times (currently I'm again using the default), also I have used '--noatime' for testing.

#### Include any warning/errors/backtraces from the system logs
n/a

#### Benchmark results
```
# /usr/local/bin/borg benchmark crud /data/borgbackup /dev/shm/borg
C-Z-BIG         107.50 MB/s (10 * 100.00 MB all-zero files: 9.30s)
R-Z-BIG         117.61 MB/s (10 * 100.00 MB all-zero files: 8.50s)
U-Z-BIG         236.54 MB/s (10 * 100.00 MB all-zero files: 4.23s)
D-Z-BIG         264.55 MB/s (10 * 100.00 MB all-zero files: 3.78s)
C-R-BIG          38.55 MB/s (10 * 100.00 MB random files: 25.94s)
R-R-BIG          78.37 MB/s (10 * 100.00 MB random files: 12.76s)
U-R-BIG         240.12 MB/s (10 * 100.00 MB random files: 4.16s)
D-R-BIG          87.12 MB/s (10 * 100.00 MB random files: 11.48s)
C-Z-MEDIUM      117.30 MB/s (1000 * 1.00 MB all-zero files: 8.53s)
R-Z-MEDIUM      122.69 MB/s (1000 * 1.00 MB all-zero files: 8.15s)
U-Z-MEDIUM      257.47 MB/s (1000 * 1.00 MB all-zero files: 3.88s)
D-Z-MEDIUM      276.66 MB/s (1000 * 1.00 MB all-zero files: 3.61s)
C-R-MEDIUM       36.76 MB/s (1000 * 1.00 MB random files: 27.20s)
R-R-MEDIUM       84.64 MB/s (1000 * 1.00 MB random files: 11.81s)
U-R-MEDIUM      263.80 MB/s (1000 * 1.00 MB random files: 3.79s)
D-R-MEDIUM       68.77 MB/s (1000 * 1.00 MB random files: 14.54s)
C-Z-SMALL        17.68 MB/s (10000 * 10.00 kB all-zero files: 5.65s)
R-Z-SMALL        68.81 MB/s (10000 * 10.00 kB all-zero files: 1.45s)
U-Z-SMALL        20.50 MB/s (10000 * 10.00 kB all-zero files: 4.88s)
D-Z-SMALL        25.98 MB/s (10000 * 10.00 kB all-zero files: 3.85s)
C-R-SMALL        12.55 MB/s (10000 * 10.00 kB random files: 7.97s)
R-R-SMALL        58.70 MB/s (10000 * 10.00 kB random files: 1.70s)
U-R-SMALL        19.76 MB/s (10000 * 10.00 kB random files: 5.06s)
D-R-SMALL        22.04 MB/s (10000 * 10.00 kB random files: 4.54s)
```

**Comment by ThomasWaldmann** [comment]
How many different sets of input files are processed by this user?

I mean e.g. if you back up home and everything else in 2 borg invocations, that would be 2 sets.

**Comment by sb-otrs** [comment]
I have 5 different sets in total within the repository. 4 of them run daily, 1 runs hourly.
The problem is only seen on the set mentioned above, the other 4 are much smaller though (1,4-2,5GB each).

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#it-always-chunks-all-my-files-even-unchanged-ones maybe it is that.

**Comment by ThomasWaldmann** [comment]
Another cause could be if the inode numbers are not stable or the absolute path of the backed up files is changing.

**Comment by sb-otrs** [comment]
Yes, I read that too but I can rule that out for my current setup. Everything runs locally on ext4 - I have remote backups but they are rsync'd to the local hard disk and the backup runs on the local files only.

**Comment by sb-otrs** [comment]
After 4 days (day 1 for rebuilding the file cache) I can safely assume the issue is resolved by raising BORG_FILES_CACHE_TTL (in my case to 50 which equals a little less than 2 days and leaves space for a few more sets).

Maybe it's worth extending documentation and/or FAQ to emphasize how the file cache works when using multiple sets in the same repository.

Thanks again Thomas!

**Comment by ThomasWaldmann** [comment]
@sb-otrs isn't the docs i linked good enough?
