### ISSUE TITLE
do borg extract without locking

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#420]
(due to lack of multi threading the extraction is a unneccassary bottleneck)
-> i would like to start multiple instances to extract severel subdirectories at the same time.

the extraction should be a "read-only" process. correct?

So there is no need for locking ...

**Comment by ClipperS87** [comment]
so why not lock it with timeout 1 second and then unlock it ...

**Comment by ThomasWaldmann** [comment]
@ClipperS87 not sure what you mean.

**Comment by ClipperS87** [comment]
as i understood you lock during extracting to avoid a inconsistent repository as source.
So my suggestion is to lock with timeout 1 second (if its not lockable then break) - if its lockable then immediately release the lock.
by doing this you can ensure that only one process writes to the repo and on the other hand if you extract you simply "dont care" what is happening with the repo as the index is cached (in memory).
and in the rare case that one "task" extracts a backup and another backup deletes this backup (and the chunks only connected with this backup) the extract runs into a "chunk file not found" which is totally ok...

**Comment by ThomasWaldmann** [comment]
ok, so you lock, get the lock, and release the lock again. then you extract the archive.
after 5 minutes, while you still extract the archive, someone else deletes the archive or the repo.

**Comment by ClipperS87** [comment]
for the "first shot" i prefer any solution which is better then today. 
I can live with the fact that no creating is possible during any extract process
I can live with the fact that if "someone" deletes _exactly_ the same archive which I am currently extracting I run into a "chunk not found" error (like today, if I miss a chunk file i.e. due to CRC error)

**Comment by anarcat** [comment]
On 2015-11-17 08:48:00, TW wrote:
> ok, so you lock, get the lock, and release the lock again. then you extract the archive.
> after 5 minutes, while you still extract the archive, someone else deletes the archive or the repo.

locking systems typically implement various semantics for this. for
example, sql database locks are "read" ("you can read, but not write,
because i'm reading") or "write" ("you can't read *or* write because i'm
writing").

seems like this is what would be needed here.

**Comment by ThomasWaldmann** [comment]
we already have read (shared) and write (exclusive) locks, just the granularity is currently "repo wide".

**Comment by anarcat** [comment]
then why can't extract use shared locks and run multiple extracts in parallel?

**Comment by ThomasWaldmann** [comment]
not sure, has to be investigated. while I rewrote the lower parts of the locking code (mkdir instead of posix locks), I didn't change how it is used from higher layers.

**Comment by ClipperS87** [comment]
simply avoid locking during extraction
there is no need for any locking during extraction - and the creation should only set a "write-lock"

**Comment by ThomasWaldmann** [comment]
@ClipperS87 I tried with 0.28.2 and running multiple extracts (and ONLY multiple extracts) from the same repo, on the same machine, at the same time works for me.

**Comment by ClipperS87** [comment]
i agree - in version 0.28.2  simultaneous extract works - even of several paths from the same backup.
great :-)
