### ISSUE TITLE
update bundled zstd code

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4210]
we have 1.3.4 bundled, current see there: https://github.com/facebook/zstd/releases

**Comment by ThomasWaldmann** [comment]
hmm, it doesn't seem like there are substantial improvements or fixes relevant to borg yet, so we can do that later.

**Comment by ThomasWaldmann** [comment]
@donnyward I've seen you are working on this, is it ready for a PR?

**Comment by donnyward** [comment]
@ThomasWaldmann It will be ready for a PR after I run the tests. I will do that after I get off work tonight.

**Comment by donnyward** [comment]
It's ready now, had to update setup_zstd.py because zstd's refactoring caused the test to fail. PR #4393
