### ISSUE TITLE
OSError: [Errno 5] Input/output error in "msgpack/_unpacker.pyx", line 159

### ISSUE THREAD

**Issue by finefoot** [borgbackup/borg#4211]
## Have you checked borgbackup docs, FAQ, and open Github issues?

I have read the docs, FAQ and GitHub issue search results but I haven't browsed through *every* GitHub issue. Sorry, if I should have missed something. Might be interesting in the light of https://github.com/borgbackup/borg/issues/4059

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

    $ borg -V
    borg 1.0.11

#### Operating system (distribution) and version.

Lubuntu 16.04

#### Hardware / network configuration, and filesystems used.

CIFS mounted with

    sudo mount -t cifs -o rw,user=[redacted] //192.168[redacted] /media/[redacted]/backup

#### How much data is handled by borg?

Sorry, what exactly do you want to know here? The line with the progress is partly overwritten with `Local Exception`:

    Local Exception.31 GB C 237.61 GB D 40173 N [redacted]

I'm trying to backup approximately 2 TB of data, approximately 230 GB had been written so far.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

    borg create --verbose --progress --stats /media/[redacted]/backup::Monday /media/[redacted]/archive

## Describe the problem you're observing.

I initiated the bord repo with

    borg init --encryption=repokey /media/[redacted]/backup

Then ran `borg create` as described above. After approximately 230 GB had been written, I got the error below.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I ran the exact `borg create` line afterwards again which resulted in the same error.

#### Include any warning/errors/backtraces from the system logs

Pasted below are two `stdout`/`stderr` output logs. First one from the initial attempt, which failed after approximately 230 GB had been written and took quite some time. Second one from the subsequent attempt with the same command. This failed almost immediately.

Initial attempt:

```
$ borg create --verbose --progress --stats /media/[redacted]/backup::Monday /media/[redacted]/archive

Enter passphrase for key /media/[redacted]/backup: 
Local Exception.31 GB C 237.61 GB D 40173 N [redacted]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2104, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 107, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 331, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 304, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 361, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 722, in process_file
    self.add_item(item)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 295, in add_item
    self.write_checkpoint()
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 301, in write_checkpoint
    self.cache.chunk_decref(self.id, self.stats)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 480, in chunk_decref
    self.repository.delete(id, wait=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 552, in delete
    self.prepare_txn(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 244, in prepare_txn
    hints = msgpack.unpack(fd)
  File "msgpack/_unpacker.pyx", line 159, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:159)
OSError: [Errno 5] Input/output error

Platform: Linux [redacted] 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.11  Python: CPython 3.5.2
PID: 8642  CWD: /home/[redacted]
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--progress', '--stats', '/media/[redacted]/backup::Monday', '/media/[redacted]/archive']
SSH_ORIGINAL_COMMAND: None
```

Subsequent attempt:

```
$ borg create --verbose --progress --stats /media/[redacted]/backup::Monday /media/[redacted]/archive

Enter passphrase for key /media/[redacted]/backup: 
Local Exception. GB C 0 B D 2367 N [redacted]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 2104, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 107, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 331, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 304, in create_inner
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 380, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 361, in _process
    status = archive.process_file(path, st, cache, self.ignore_inode)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 722, in process_file
    self.add_item(item)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 293, in add_item
    self.items_buffer.add(item)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 141, in add
    self.flush()
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 156, in flush
    self.chunks.append(self.write_chunk(chunk))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 172, in write_chunk
    id_, _, _ = self.cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 453, in add_chunk
    self.repository.put(id, data, wait=False)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 535, in put
    self.prepare_txn(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 244, in prepare_txn
    hints = msgpack.unpack(fd)
  File "msgpack/_unpacker.pyx", line 159, in msgpack._unpacker.unpack (msgpack/_unpacker.cpp:159)
OSError: [Errno 5] Input/output error

Platform: Linux [redacted] 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64
Linux: Ubuntu 16.04 xenial
Borg: 1.0.11  Python: CPython 3.5.2
PID: 11879  CWD: /home/[redacted]/Desktop
sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--progress', '--stats', '/media/[redacted]/backup::Monday', '/media/[redacted]/archive']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
As discussed before this is a file system error, not a Borg.
https://github.com/borgbackup/borg/issues/4087

**Comment by emmi474** [comment]
Thanks for getting back to me.

> As discussed before in #4087 this is a file system error, not a Borg.

What do you mean? Is this desired behaviour for borg to just show that exception? How do I investigate further?

**Comment by emmi474** [comment]
@ThomasWaldmann Thanks for getting back to me.

Did you see my update above? I think you posted your comment almost exactly at the same time I updated mine.

> Check the fs / disk where your repository is located.

It's been formatted immediately before I started the backup process. Scan disk shows no errors.

**Comment by ThomasWaldmann** [comment]
If the repo is accessed via smbfs, it could be also an issue with that or the network.

**Comment by ThomasWaldmann** [comment]
BTW, is there some special reason why you use 1.0.11? There is 1.1.8 out and even if you have reasons to use 1.0.x, there is 1.0.12.

**Comment by emmi474** [comment]
> BTW, is there some special reason why you use 1.0.11? There is 1.1.8 out and even if you have reasons to use 1.0.x, there is 1.0.12.

No reason other than it's the version from `apt-get install borgbackup`. Do you think it would be beneficial if I'd disregard the APT package and use the most recent standalone binary?

> If the repo is accessed via smbfs, it could be also an issue with that or the network.

Is there a reason why I should use `smbfs`? I'm using `cifs` to mount the volume at the moment. My mount command is

    sudo mount -t cifs -o rw,user=[redacted] //192.168[redacted] /media/[redacted]/backup

Are there any recommendations for further options to set up in order for borg to work with the volume? From reported user experiences or as a general requirement for borg? I couldn't find anything in the docs.

**Comment by ThomasWaldmann** [comment]
you can get a more recent version from LocutusOfBorg's ppa.

about smbfs/cifs mount options, maybe search this issue tracker.

in general, borg just needs a well-working filesystem.

**Comment by finefoot** [comment]
@ThomasWaldmann Sorry for taking so long to get back to you. You were right, changing the mount options resolved the issue. Instead of:

    sudo mount -t cifs -o rw,user=[redacted] //192.168[redacted] /media/[redacted]/backup

I'm now using:

    sudo mount -t cifs -o username=[redacted],uid=1000,forceuid,gid=1000,forcegid,file_mode=0666,dir_mode=0666,rw,cache=strict,soft,serverino,nounix,rsize=1048576,wsize=1048576,actimeo=1,vers=1.0 //192.168[redacted] /media/[redacted]/backup

There were quite some issues and questions about the same problem. That's where I got the used settings from, they seem to fix this problem for most people. So what do you think about adding a small paragraph about this to the docs? Something like:

> In general, borg just needs a well-working filesystem. So if you're getting `OSError: [Errno 5] Input/output error` with a cifs-mounted volume, make sure to check your mount settings. Most users were successful with the following options:
> 
>     sudo mount -t cifs -o username=[redacted],uid=1000,forceuid,gid=1000,forcegid,file_mode=0666,dir_mode=0666,rw,cache=strict,soft,serverino,nounix,rsize=1048576,wsize=1048576,actimeo=1,vers=1.0 //192.168[redacted] /media/[redacted]/backup

**Comment by ThomasWaldmann** [comment]
We can add it as a FAQ entry **if** someone invests the time to find out the options that make a difference for the `IOError` and gives the **minimum** list of options required to make it work.

**Comment by finefoot** [comment]
@ThomasWaldmann Sorry, I don't have time for that at the moment. I mean, the options aren't even the most important part about the suggested docs addition, I think. It's just that I didn't realize that `OSError` might implicate a problem with the cifs-mounted volume.

So how about a general hint without mentioning specific mount options:

> In general, borg just needs a well-working filesystem. So if you're getting `OSError: [Errno 5] Input/output error` make sure there's no issue with the filesystem on which you're storing the backup. This applies especially if you're writing to a cifs-mounted volume (see https://github.com/borgbackup/borg/issues/4056 or https://github.com/borgbackup/borg/issues/4059 or https://github.com/borgbackup/borg/issues/4086 or https://github.com/borgbackup/borg/issues/4211) where the error might randomly appear along the backup process, so make sure to check your mount settings. You can find some useful mount options in the resolved issue reports.
