### ISSUE TITLE
Borg create hangs and fails to create remote archive to rsync.net

### ISSUE THREAD

**Issue by jerrydeasley** [borgbackup/borg#4212]
I am having a recent problem creating remote archives from my local machine to my rsync.net account. 
I had daily cron job borg remote archives to rsync.net working perfectly from about April, 2018 through December 2, 2018.  Within a few days of Dec. 2, 2018, I noticed that no new archives had been created.  I I have manually run borg as follows:

```
borg create --stats --debug --list --remote-path=borg1 xxxx@usw-s009.rsync.net:repo1::archve /mnt/mydata
using builtin fallback logging configuration
35 self tests completed in 0.30 seconds
SSH command line: ['ssh', 'xxxx@usw-s009.rsync.net', 'borg1', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.74 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'repo1'
Remote: Resolved repository path to '/data1/home/xxxx/repo1'
TAM-verified manifest
security: read previous location 'ssh://xxxx@usw-s009.rsync.net/./repo1'
security: read manifest timestamp '2018-12-11T20:40:29.040172'
security: determined newest manifest timestamp as 2018-12-11T20:40:29.040172
security: repository checks ok, allowing access
Verified integrity of /home/xxxx/.cache/borg/8d03e211c13ba13257e40bedbdd54cc98a5ee21b70cd36866c8d7564a170ade0/chunks
Reading files cache ...
security: read previous location 'ssh://xxxx@usw-s009.rsync.net/./repo1'
security: read manifest timestamp '2018-12-11T20:40:29.040172'
security: determined newest manifest timestamp as 2018-12-11T20:40:29.040172
security: repository checks ok, allowing access
Processing files ...
```

after a few minutes, it fails as follows:

```
Remote: Fssh_packet_write_wait: Connection to 64.62.236.78 port 22: Broken pipe
RemoteRepository: 17.09 MB bytes sent, 3.84 kB bytes received, 33 messages sent
Connection closed by remote host
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 554, in do_create
    create_inner(archive, cache)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 518, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 631, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 631, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 631, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 605, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/local/lib/python3.6/site-packages/borg/archive.py", line 1028, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/local/lib/python3.6/site-packages/borg/archive.py", line 956, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/usr/local/lib/python3.6/site-packages/borg/archive.py", line 944, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/usr/local/lib/python3.6/site-packages/borg/cache.py", line 898, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/local/lib/python3.6/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/local/lib/python3.6/site-packages/borg/remote.py", line 707, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/local/lib/python3.6/site-packages/borg/remote.py", line 807, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 4434, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 4366, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.6/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/borg/remote.py", line 630, in __exit__
    self.rollback()
  File "/usr/local/lib/python3.6/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/local/lib/python3.6/site-packages/borg/remote.py", line 707, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/local/lib/python3.6/site-packages/borg/remote.py", line 807, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

Platform: FreeBSD Borg 11.2-STABLE FreeBSD 11.2-STABLE #0 r325575+fc3d65faae6(freenas/11.2-stable): Wed Dec  5 15:08:42 EST 2018     root@nemesis.tn.ixsystems.com:/freenas-11.2-releng/freenas/_BE/objs/freenas-11.2-releng/freenas/_BE/os/sys/FreeNAS.amd64 amd64
Borg: 1.1.7  Python: CPython 3.6.6
PID: 83981  CWD: /usr/home/xxxx
sys.argv: ['/usr/local/bin/borg', 'create', '--stats', '--debug', '--list', '--remote-path=borg1', 'xxxx@usw-s009.rsync.net:repo1::archive', '/mnt/mydata']
SSH_ORIGINAL_COMMAND: None
```

borg init, info, list all work as expected.  It's just create that causes this problem.  I have tried creating the remote archive to rsync.net on its default borg 0.29 server and its borg1 remote path (1.1.5) with similar failures.

I am running borg 1.1.7 from a freebsd (FreeNAS) 11.2 jail.  I have tried this from two different physical machines from my home location.  I have also tried from a Ubuntu install from my home location with similar results.  I have also setup a machine at my home location as a borg server target and tried to perform a remote archive from my work location to my home location with similar failure.  However, I am able to create a remote archive from work location from a 11.2 jail with borg 1.1.7 to rsync.net.  This makes me believe something related to my ISP (AT&T 100 Mbps fiber) is causing borg/ssh to fail.

I have tried editing ssh_config to add: 
```
Host *
ServerAliveInterval 120
```

all this seems to do is cause it to take longer before failing.  I have also tried connecting to rsync.net through its ip address rather than domain... same failure.

Any thoughts on how to resolve this?

**Comment by infectormp** [comment]
see https://github.com/borgbackup/borg/issues/3866

**Comment by ThomasWaldmann** [comment]
@jerrydeasley did you reboot your home switch / router / fiber adaptor before trying?

besides your ISP, these seem to be the common parts involved in your failing tries.

**Comment by jerrydeasley** [comment]
Thanks all for your help.
@ThomasWaldmann I have cold booted all involved equipment with no change.  My internet setup is AT&T fiber into the AT&T residential gateway ("RG").  I have the RG set in passthrough mode to my pfsense firewall.  I double checked this morning to see if AT&T had been monkeying around with the settings on the RG, but did not discern any.  To eliminate any firewall issues, I have tried my backups with firewall rules of pass all traffic to/from the rsync domain, but no change in results.  I also tried to upload a ~ 100 MB file to my rsync.net account using scp - I got the same "broken pipe" failure.  So, this seems to confirm that the problem is not within borg, but that something along the way is breaking ssh.  

If you have any other thoughts that might help, I would really appreciate hearing them.  This is the traceroutes from my home to usw-s009.rsync.net (Denver location), which hosts my account:
'''
traceroute to usw-s009.rsync.net (64.62.236.78), 64 hops max, 40 byte packets
 1  pfsense.localdomain (192.168.1.1)  0.106 ms  0.088 ms  0.107 ms
 2  104-190-24-1.lightspeed.hstntx.sbcglobal.net (104.190.24.1)  3.087 ms  8.998 ms  9.593 ms
 3  71.149.39.88 (71.149.39.88)  2.338 ms  2.174 ms  1.727 ms
 4  * * *
 5  12.83.86.169 (12.83.86.169)  4.693 ms
    12.83.86.165 (12.83.86.165)  3.981 ms
    12.83.86.169 (12.83.86.169)  1.857 ms
 6  gar25.dlstx.ip.att.net (12.122.85.233)  8.789 ms  9.630 ms  7.978 ms
 7  10ge6-6.core1.dal1.he.net (216.66.78.121)  7.725 ms  7.748 ms  8.977 ms
 8  10ge1-1.core1.rno1.he.net (184.105.222.106)  24.617 ms  25.086 ms  24.707 ms
 9  100ge6-2.core1.den1.he.net (184.105.81.213)  32.768 ms  33.078 ms  32.711 ms
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
'''

For comparison, here is the traceroute to rsync.net's San Diego location:
'''
traceroute to usw-s001.rsync.net (69.43.165.6), 64 hops max, 40 byte packets
 1  pfsense.localdomain (192.168.1.1)  0.120 ms  0.105 ms  0.122 ms
 2  104-190-24-1.lightspeed.hstntx.sbcglobal.net (104.190.24.1)  2.018 ms  12.42                                                                                                                               0 ms  10.199 ms
 3  71.149.39.88 (71.149.39.88)  5.357 ms  6.568 ms  2.543 ms
 4  71.144.129.126 (71.144.129.126)  2.455 ms  4.510 ms  1.865 ms
 5  12.83.86.169 (12.83.86.169)  3.197 ms  4.048 ms
    12.83.86.165 (12.83.86.165)  2.318 ms
 6  12.123.18.229 (12.123.18.229)  10.704 ms  8.165 ms  11.912 ms
 7  192.205.36.102 (192.205.36.102)  7.554 ms  7.836 ms  7.286 ms
 8  207.88.14.188.ptr.us.xo.net (207.88.14.188)  41.397 ms  41.169 ms  45.179 ms
 9  te0-11-4-0.rar3.sanjose-ca.us.xo.net (207.88.12.181)  40.977 ms  41.826 ms                                                                                                                                 41.002 ms
10  te0-12-1-0.rar3.chicago-il.us.xo.net (207.88.12.141)  41.820 ms  40.793 ms                                                                                                                                 41.177 ms
11  216.156.16.61.ptr.us.xo.net (216.156.16.61)  41.132 ms  42.108 ms  41.995 ms
12  ae1d0.mcr2.sandiego-ca.us.xo.net (216.156.1.62)  40.809 ms  87.180 ms  79.80                                                                                                                               3 ms
13  66.238.55.70.ptr.us.xo.net (66.238.55.70)  41.384 ms  41.225 ms  41.335 ms
14  te5-5-6509-a.castleaccess.com (69.43.169.112)  41.057 ms  41.103 ms  41.294                                                                                                                                ms
15  69.43.129.84 (69.43.129.84)  42.696 ms  41.137 ms  41.841 ms
16  * * *
17  * * *
18  * * *
'''

Is there anything about these traceroutes which appear to reveal my problem?

**Comment by ThomasWaldmann** [comment]
Don't see anything suspicious there.

Maybe report an issue to your ISP and hope for somebody with a clue looking at it.

**Comment by ThomasWaldmann** [comment]
Closing this, not a borg issue.

**Comment by ThomasWaldmann** [comment]
Hmm, just as an idea: for a test, bypass your pfsense box and directly try that scp?
Then you could at least rule out any issues with that hw / sw.
