### ISSUE TITLE
"Repository has no manifest." - very likely after NFS mount lost...

### ISSUE THREAD

**Issue by pmorch** [borgbackup/borg#4218]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.5

#### Operating system (distribution) and version.
Ubuntu 18.04

#### Hardware / network configuration, and filesystems used.
Pretty standard amd64 desktop machine with an NFS mounted ~/store (that, yes, has problems)

#### How much data is handled by borg?

```
> du -sh mozilla-borg
770M	mozilla-borg
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
> borg list mozilla-borg
Repository has no manifest.
```

## Describe the problem you're observing.

I have an NFS mounted ~/store folder. Sometimes I loose access to the NFS server for reasons unrelated to borg. When it occurs, it occurs suddenly after which the NFS server needs a hard restart to come back online.

I'm now seeing the `Repository has no manifest.` error. The NFS server is currently working fine, but it is possible the problem was introduced in the past when there were NFS problems.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

No

#### Include any warning/errors/backtraces from the system logs
I have a cron.d file:
```
> cat /etc/cron.d/backup-mozilla 
MAILTO=XXXXX@gmail.com

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 *    * * *   peter /etc/backupstore/cronic bash -c 'mountpoint /home/peter/store && borg create --stats /home/peter/store/backup/mozilla-borg::mozilla-{now} /home/peter/.mozilla >> /var/log/borg-mozilla.log 2>&1'
30 3    * * *   peter /etc/backupstore/cronic bash -c 'mountpoint /home/peter/store && borg prune -P mozilla- -p --keep-hourly 8 --keep-daily 3 --keep-weekly 3 --keep-monthly 3 --keep-yearly 3 /home/peter/store/backup/mozilla-borg 2>1'
```
That should create new backup every hour. (And has done so fine in the past).

And from this, the last lines of /var/log/borg-mozilla.log are:
```
Archive name: mozilla-2018-12-16T20:00:01
Archive fingerprint: d662d5a301d0d96cefaf76450507720cbd3b2e2dae0c4d94cb4b40279f3654af
Time (start): Sun, 2018-12-16 20:00:01
Time (end):   Sun, 2018-12-16 20:00:03
Duration: 2.09 seconds
Number of files: 4074
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              439.09 MB            255.00 MB              9.41 MB
All archives:               14.25 GB              8.23 GB              1.09 GB

                       Unique chunks         Total chunks
Chunk index:                    6047               132918
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Archive name: mozilla-2018-12-16T21:00:01
Archive fingerprint: b1315830d52f66c444b8dafce175a27c35086f183787e95984729a87cc07ae75
Time (start): Sun, 2018-12-16 21:00:01
Time (end):   Sun, 2018-12-16 21:00:03
Duration: 2.07 seconds
Number of files: 4074
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              439.09 MB            255.00 MB              9.49 MB
All archives:               14.69 GB              8.49 GB              1.10 GB

                       Unique chunks         Total chunks
Chunk index:                    6075               137085
------------------------------------------------------------------------------
Repository has no manifest.
Repository has no manifest.
Repository has no manifest.
<serveral more of such lines - one every hour I presume>
```

So the last one at 21:00 ended without problems emitted from borg and no more entries after that.  At no point did borg emit any error or warning messages, because then they'd be in the log output above.

[an old comment](https://github.com/borgbackup/borg/issues/2132#issuecomment-278759197) in #2132 suggests to run `borg check --repair`. When I do that (after keeping a copy of the original folder), I get:
```
> borg check --repair mozilla-borg
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Repository manifest not found!
(many, many lines like:)
home/peter/.mozilla/firefox/vxcggtho.dev-edition-default/xulstore.json: New missing file chunk detected (Byte 0-437). Replacing with all-zero chunk.
42 orphaned objects found!
Archive consistency check complete, problems found.
```

After which I see some of the backups but many are also missing. At least all the backups between 2018-12-11 23:00:03 and 2018-12-16 21:00:01 :-(

```
> borg list ~/store/backup/mozilla-borg/
mozilla-2018-11-25T23:00:01          Sun, 2018-11-25 23:00:02 [d8d6db0f2d79aa906fe15f435d65c3289cd92e2ccac353847164751607b5c2dd]
mozilla-2018-11-30T23:00:02          Fri, 2018-11-30 23:00:02 [c4b36d6b09fdecf3d51e7ea705fe0c79a76638f4c44619598ff2013cf288221e]
mozilla-2018-12-02T23:00:02          Sun, 2018-12-02 23:00:02 [c65756514ef98006edd820af713e7c77fe18ccedafbfd27e967cdfa1bc45f855]
mozilla-2018-12-08T17:00:01          Sat, 2018-12-08 17:00:01 [bb77c48d42778212f664373dd4d38ea04f2b153cf4cf7ccee5be3182afbacb9b]
mozilla-2018-12-11T23:00:02          Tue, 2018-12-11 23:00:03 [7d62cb404301a7c6fb7f614850a5a25e56e7f098c24261e7e56f81850c1f8255]
```

But uhm, I used to store things once an hour. They're all lost. And what about the  `New missing file chunk detected (Byte 0-437). Replacing with all-zero chunk.` errors.

Hmm. I don't like it. Something is pretty bad here.

**Comment by ThomasWaldmann** [comment]
Likely it's not related to the borg version (but the NFS instabilities you've experienced), but there is 1.1.8 now, so you maybe want to upgrade.

Borg tries hard to play safe. E.g. it calls sync (or similar OS calls) rather frequently and esp. after each segment file write is completed, before and after it commits changes to the repo. This should really make sure that stuff gets onto disk (in the right order), but of course borg can't help if the filesystem or lower layers have major problems.

That there was an issue and you don't see it in the logs might have 2 root causes:
- lower layers than borg silently malfunctioning (nfs, ...)
- the prune line in your crontab is incorrect, no log file there, the "2>1" has a typo also (so check if you have a file named "1")

**Comment by ThomasWaldmann** [comment]
About the "orphaned objects": this might be due to an IOError or similar at the source file when doing a backup. borg writes the chunks, but due to the error, does not write a metadata item referencing these chunks. We have an open issue about this. It's a cosmetic issue.

**Comment by ThomasWaldmann** [comment]
about the "lost archives" after `borg check --repair`:

borg tries hard to recover archives even with a lost manifest (== archive list) by scanning through the segment files and trying to discover archive metadata and finally regenerating the manifest with all it has discovered. but if there is really data loss in the repo due to fs problems, borg can't bring the data back.

that there are not a lot of backups might be also due to your prune settings, maybe you want to keep more archives (it doesn't cost a lot of storage due to dedup).

**Comment by pmorch** [comment]
Thats the thing. I don't think that there are massive fs problems apart from the NFS drive suddenly-disappearing-permanently-until-rebooted once in a while.

But hey, this isn't high-value stuff. It is the backup of my firefox profile in `$HOME/.mozilla`. And I currenty have a working firefox profile, so no biggie. I was using this as a test of borg... "How does it work with an unreliable destination" :-)

I'll start over with 1.1.8 and see how it goes.

I'll try to also have an hourly backup of my `/home/peter/store/backup/mozilla-borg` on media that I can rely on.

> that there are not a lot of backups might be also due to your prune settings, maybe you want to keep more archives (it doesn't cost a lot of storage due to dedup).

Are you sure about that? I've been very happy with the current prune line. Before the error, I believe there were between 8 and 8+24 hourly backups at all times. (At 03:30 it deletes all but the last 8 hourly backups, right?). At the very least, at there should be the `mozilla-2018-12-16T21:00:01` and `mozilla-2018-12-16T20:00:01` backups from the log file. They were **all** gone after the error.

However, as I said, lets not get carried away with trying to debug this error on an older version of borg. I'll close it, and if it occurs again, I'll reopen it (if that is possible) or I'll create a new bug report linking to this one. Containing more detailed information hopefully a before / after dataset so I/we can see what went wrong.

**Comment by pmorch** [comment]
And thank you for the swift reply! It is much appreciated on this end! Kudos!
