### ISSUE TITLE
Msgpack exception when trying to create archive in an old repository

### ISSUE THREAD

**Issue by yl3dy** [borgbackup/borg#4220]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

`borg 1.1.5`

#### Operating system (distribution) and version.

Ubuntu Bionic 18.04 amd64

#### Hardware / network configuration, and filesystems used.

Backup source (local HDD): XFS, external HDD with borg directory: ext4.

#### How much data is handled by borg?

Approximately 500 GB deduplicated and compressed (zlib) with 5 archives (full original size 2.96 TB) and 398125 unique + 2228374 total chunks.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`sys.argv: ['/usr/bin/borg', 'create', '--verbose', '--progress', '--stats', '--compression', 'zlib', '--exclude-from', 'attic.filter', '--one-file-system', '--list', '--filter', 'AMEh', '/media/yl3dy/backup/data.borg::2018-12-18__17-04', '/mnt/data']`
(sorry for filter name)

## Describe the problem you're observing.

Cannot create a new archive in a borg repository created and used previously with borg 1.0.9-1~bpo8+1 (created in some earlier version, 1.0.5 perhaps) in Debian 8 (oldstable) installed via backports. Previously had no issues with the drive and repository, regularly did `borg check`. The repository has no encryption. It is the first time this repository is used with borg 1.1.x. The current system has a clean borg cache. `list` and `info` run fine. `borg -vp check` doesn't show any problems. Running with `--dry-run` instead of `--stats` produces no output and no errors.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

On every `borg create` the following error arises. It fails on the same file every time (10th file in list).

#### Include any warning/errors/backtraces from the system logs

After few files:
```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 547, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 511, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 621, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 621, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 598, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1021, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 949, in chunk_file
    item.chunks.append(chunk_processor(data))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 937, in chunk_processor
    chunk_entry = cache.add_chunk(self.key.id_hash(data), data, stats, wait=False)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 898, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1059, in put
    self.prepare_txn(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 504, in prepare_txn
    hints = msgpack.unpack(fd)
  File "/home/yl3dy/.local/lib/python3.6/site-packages/msgpack/__init__.py", line 57, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 187, in msgpack._cmsgpack.unpackb
ValueError: 72459 exceeds max_map_len(32768)
```

**Comment by ThomasWaldmann** [comment]
borg 1.1.8 is the latest release, but i guess it will result in the same problem.

can you check with your previous borg version how many archives you have in that repo?

```
borg list repo | wc -l
```

**Comment by ThomasWaldmann** [comment]
Hmm, I see you said 5. Please verify.

**Comment by ThomasWaldmann** [comment]
It's msgpack in standard configuration trying to unpack your repo's hints file.

IIRC, the msgpack author recently changed near-to-infinite defaults to safer-against-DoS, lower defaults.

So, for a quick workaround, use an older msgpack-python.

**Comment by ThomasWaldmann** [comment]
Hmm, I see this change in defaults happened in msgpack 0.6.0, which is a version borg 1.1.5 never supported (see setup.py, it says `msgpack-python>=0.4.6,<0.5.0`).

Even the latest borg 1.1.8 does not support 0.6.0, so how did you get that installed?

**Comment by LocutusOfBorg** [comment]
python-msgpack | 0.5.6-1        | bionic | source, amd64, arm64, armhf, i386, ppc64el, s390x

not something that comes from repo.
https://launchpad.net/ubuntu/+source/python-msgpack
we use 0.5.6 since 18.04

**Comment by LocutusOfBorg** [comment]
```
  File "/home/yl3dy/.local/lib/python3.6/site-packages/msgpack/__init__.py", line 57, in unpack
```
this is not where we install official Ubuntu packages :)

**Comment by yl3dy** [comment]
Yeah, I haven't noticed that! Newer msgpack was installed via pip as a dependency of pynvim (sadly, this package, as well as a number of others, aren't in official Ubuntu repos, pip doesn't have any analog of apt pinning, and I can't put them into a virtualenv). Now an archive was created without errors.

**Comment by ThomasWaldmann** [comment]
reopening, see TODO in bold in https://github.com/borgbackup/borg/issues/4220#issuecomment-448302127 .

**Comment by ThomasWaldmann** [comment]
https://git.archlinux.org/svntogit/community.git/tree/trunk/0001-Fix-msgpack-version-constraints-using-proper-setupto.patch?h=packages/borg

this will break borg in archlinux due to the removal of the "< 0.6.0" requirement as soon as someone upgrades msgpack there. the breakage is non-obvious and won't be found in a quick test, but someone will find this issue in production then (see top post) ... @eli-schwartz

**Comment by ThomasWaldmann** [comment]
fixed in master branch (was easy due to the new msgpack wrapper in master).
not fixed in 1.1-maint (no wrapper there, msgpack >= 0.6.0 unsupported there).

**Comment by eli-schwartz** [comment]
Unclear what you expect us to do about this, since we cannot just hold up the entire world due to one package (and historically, the version constraints that borg has has been entirely illegitimate).

We could try backporting the patch even if you don't want to, but the patch does not apply due to the msgpack wrapper.

We could also drop borg from the distribution and tell users to exclusively compile and run it themselves in a virtualenv, but that doesn't seem like a very friendly option to users.

We could fork the software and distribute our own heavily modded version that actually works on a consistent basis on remotely recent distributions, but that is... unfeasible on so many levels.

Perhaps you could reconsider your unexplained refusal to support 0.6 -- if this is just about support for transitional packages under the "msgpack-python" name then the code for it has not disappeared from the msgpack sources, regardless of whether it is uploaded to PyPI for 0.6, so I see no reason to blockade users that have built it themselves.

**Comment by ThomasWaldmann** [comment]
@eli-schwartz a start would be not to remove the original requirements from setup.py (here: "< 0.6.0") and thus also not upgrading to incompatible versions of borgbackup's dependencies.

I'm sorry that this is some pain, but I am not responsible for msgpack and all the issues its development is causing.

**Comment by c---** [comment]
What a mess. On Arch Linux rolling back to the previous version is a temporary fix.

https://archive.archlinux.org/packages/p/python-msgpack/
https://archive.archlinux.org/packages/p/python-msgpack/python-msgpack-0.5.6-2-x86_64.pkg.tar.xz

**Comment by languitar** [comment]
Just for the reference, this is the related Archlinux ticket: https://bugs.archlinux.org/task/61346

**Comment by eigenbrot** [comment]
I was experiencing this exact bug on Archlinux with msgpack 0.6.0. On Jan 31st the Arch msgpack was upgraded to 0.6.1 and the problem appears to be solved. This was tested by running the exact same `borg create` command with both versions; msgpack 0.6.0 failed and msgpack 0.6.1 did not.

**Comment by ThomasWaldmann** [comment]
@eigenbrot one problem solved, other problems remain and it's totally unsupported.

**Comment by akaszynski** [comment]
Encountered the same issue on ``Ubuntu==18.04``, ``Python==3.7.2``, ``borg==1.1.9``, ``msgpack==0.6.1`` with a local python install of ``borgbackup``  Solved it with:
```
pip install msgpack==0.5.6
```

**Comment by rdxmb** [comment]
Having the exception below with Ubuntu 18.04 and

```
# borgbackup --version
borgbackup 1.1.5
# apt install python3-msgpack
Reading package lists... Done                                                                          
Building dependency tree                                                                               
Reading state information... Done                                                                      
python3-msgpack is already the newest version (0.5.6-1).                                               
python3-msgpack set to manually installed.                                                             
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
```
`borgpackup` was installed by `apt install borgbackup` from the Ubuntu repositorys.

```
borg init -e none mnt-nfs-backups-applications
root@bacula-app-0:/backup-pool/borgbackup# borg create -C lz4 -vsp mnt-nfs-backups-applications::$(date +%Y_%m_%d_%H_%M) /mnt/nfs/backups/applications
Exception ignored in: <bound method Repository.__del__ of <Repository /backup-pool/borgbackup/mnt-nfs-backups-applications>>/5d/80/a85eb1f9e20001a01775                                                           
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 173, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 379, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 278, in modify
    elements.remove(self.id)
KeyError: (('bacula-app-0.bacula-headless.bacula.svc.cluster.local@249435411410670', 1032, 0),)
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 547, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 511, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 621, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 621, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 621, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 6 more times]
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 598, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1021, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 953, in chunk_file
    from_chunk, part_number = self.write_part_file(item, from_chunk, part_number)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 931, in write_part_file
    self.write_checkpoint()
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 447, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 486, in save
    self.repository.commit()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 426, in commit
    self.check_free_space()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 632, in check_free_space
    compact_working_space = sum(self.io.segment_size(segment) - free for segment, free in self.compact.items())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 632, in <genexpr>
    compact_working_space = sum(self.io.segment_size(segment) - free for segment, free in self.compact.items())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1295, in segment_size
    return os.path.getsize(self.segment_filename(segment))
  File "/usr/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/backup-pool/borgbackup/mnt-nfs-backups-applications/data/0/0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 198, in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 415, in close
    self.lock.release()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 379, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 278, in modify
    elements.remove(self.id)
KeyError: ('bacula-app-0.bacula-headless.bacula.svc.cluster.local@249435411410670', 1032, 0)

Platform: Linux bacula-app-0 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.9
PID: 1032  CWD: /backup-pool/borgbackup
sys.argv: ['/usr/bin/borg', 'create', '-C', 'lz4', '-vsp', 'mnt-nfs-backups-applications::2020_02_13_19_07', '/mnt/nfs/backups/applications']
SSH_ORIGINAL_COMMAND: None
```
What is the solution for that?

**Comment by ThomasWaldmann** [comment]
It is the wrong issue (and it is closed).

Upgrade to borg 1.1.10 (available via ppa) and try to reproduce your issue.

**Comment by rdxmb** [comment]
@ThomasWaldmann thanks. I will try. (actually it seems there is another problem in my infrastructure causing this... )
