### ISSUE TITLE
borg mount fails silently on trailing spaces

### ISSUE THREAD

**Issue by nemoinis** [borgbackup/borg#4221]
#### Your borg version (borg -V).
borg 1.1.8
#### Operating system (distribution) and version.
Debian buster

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg mount  --prefix clientname  /path/to/repo  emptydir  ""

## Describe the problem you're observing.
borg mount silently fails when a command contains trailing spaces, as the one above. Of course I do not type such commands, but they occur as the result of bash scripts expansion of empty parameters, for example.

borg mount does mount the repo and the archives appear in 'emptydir', but they are all empty.

**Comment by ThomasWaldmann** [comment]
IIRC, any trailing arguments will be interpreted to match archive contents. So, if you give the empty string there, it won't match anything.

**Comment by ThomasWaldmann** [comment]
This issue is just one of multiple issues, other commands could also be strangely affected:
- create
- extract
- recreate
- diff
- export-tar

This is why I added `type=PathSpec` instead of `type=str`, it simply rejects empty strings.

**Comment by ThomasWaldmann** [comment]
borg 1.4 is fixed by #8005.
