### ISSUE TITLE
Can I safely change the compression level or algorithms?

### ISSUE THREAD

**Issue by fullofcaffeine** [borgbackup/borg#4222]
Hi there, this is a **question**.

I just read the following in the borg manual about the `lzma` compression alg:

```
... Giving levels above 6 is pointless and counterproductive because it does not compress better due to the buffer size used by borg - but it wastes lots of CPU cycles and RAM.
```

I have some questions regarding that:

1) I've been using 9 as the level. Now I'd like to reduce to 6 but keep using `lzma`. Can I safely do this without affecting my backup archives? Is the new archive going to take more time or take more space because of it? Are there any other consequences of doing this?

2) Also, what if I want a more radical change and decide to use another compression algorithm, what are the consequences in the repo (besides the final compression output varying) if any?

3) Can I also add the `auto` compression parameter later without further consequences?

Thanks in advance!

**Comment by RonnyPfannschmidt** [comment]
compression is transparent wrt content hashes, so my personal understanding is that its fine to change the setting without ill effect for prior backups and de-duplication

**Comment by lumbric** [comment]
For everyone stumbling on this one via google: [direct link to the answer in the FAQ](https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-safely-change-the-compression-level-or-algorithm)

(Added in the commit linked above.)
