### ISSUE TITLE
BorgBackup Meetup at 35c3

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4224]
"nerd christmas" is approaching quickly and I'll be there. \o/

On 2 days, you'll recognize me easily by my borgbackup bright-green-on-black polo shirts.

I've submitted a **'borgbackup update' lightning talk** - see the schedule:
https://c3lt.de/35c3/schedule/

If I'm not wandering around elsewhere or attending talks/session, you can find me at the **Python Assembly**. This can also be used as a meeting point to meet other borg users or developers.

For Python / Cython / C developers who want to get into the borgbackup development, I am offering a walk-through through the borg codebase and answer any questions you have - just ask!

**Comment by ThomasWaldmann** [comment]
I've also submitted a 90 minute self-organized session 2018-12-28 2200-2330 (just before the djb crypto talk):

https://events.ccc.de/congress/2018/wiki/index.php/Session:BorgBackup_Meetup

If it is accepted / the static pages are regenerated, it hopefully will also show up in the timetable at some time.

**Comment by ralphtheninja** [comment]
@ThomasWaldmann Will there be T-shirts for sale? :)

**Comment by ThomasWaldmann** [comment]
@ralphtheninja no, sorry. Guess we need a merchandise manager. :)

**Comment by mrhut10** [comment]
Will there in recordings of your talk? I would loved to hear it and the walk through the code base that your planning to do.
Love your work!!

**Comment by ThomasWaldmann** [comment]
@mrhut10 it's a "self-organized session", so i guess there is no recording.

**Comment by mrhut10** [comment]
I think I saw your slide notes you mentioned on Twitter I learnt something I didn't know about from it. Thank you

**Comment by ThomasWaldmann** [comment]
The slides were for the 5min lightning talk.

I'ld appreciate if everybody who learned something in the self-organized session to check whether it can also be found in the docs. If not, open a ticket so we can check whether it should be there (and where exactly) and then a pull request can be made to fix it.

**Comment by mrhut10** [comment]
I'll check the documentation but the online hosted backup service, i hadn't ever heard off. So that was interesting i want to look into this further.
How long has it been around for? 
is it worth trusting it wont go away or are we better just hosting our own backups, etc.

**Comment by ThomasWaldmann** [comment]
rsync.net is there since long, they used to support rsync, but started supported attic also at some time long ago. later they switch to borg 0.xx and now they also offer 1.x.x (as `borg1`).

hetzner came a bit later and the most recent service is borgbase.com.
