### ISSUE TITLE
Cannot create temporary directory on Windows

### ISSUE THREAD

**Issue by JonasOlson** [borgbackup/borg#4225]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

Borg 1.0.11 (which is the latest version in [Chocolatey](https://chocolatey.org/packages/borgbackup))

#### Operating system (distribution) and version.

Windows 10 Home

CYGWIN_NT-10.0 LAPTOP-FA89185Q 2.8.2(0.313/5/3) 2017-07-12 10:58 x86_64

#### Hardware / network configuration, and filesystems used.

Local system (to be backed up): Regular NTFS on Windows 10

Remote (where the Borg repository resides): Raspberry Pi, running Raspbian 9.6, with an NTFS filesystem on a USB disk

#### How much data is handled by borg?

The entire repository is 50GB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

    cmd.exe /c borg create --compression lz4 --info --stats --progress --show-rc ::{utcnow}Z ~

## Describe the problem you're observing.

The following error occurs in the function [`_get_default_tempdir`](https://github.com/python/cpython/blob/3e8f962e63c2f929604443531a9a3aced242f3e8/Lib/tempfile.py#L186-L229) in the file `tempfile.py`:

    FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/tmp', '/tmp', '/var/tmp', '/usr/tmp', '/c']

When I open a Python shell and manually run the same function, it searches through a longer list of directories, including more Windows-specific ones, and successfully finds a place to store temporary files. Only when run through Borg does this error occur.

The backup procedure worked for several months before this error appeared (with no change to the backup command or to the Borg installation). I'm guessing that it didn't initially need to create a temporary directory, but does so now.

(On a different Windows computer, this same error occurred already upon the initial `borg init` command. I could work around that by initialising the repository locally, which worked fine, and then move it to the remote server. After that, backups worked for a while, but eventually, the error started happening also on that computer.)

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Reproducibility is so-so. It currently happens every time on the two computers mentioned above, but the exact same command worked fine for a long time.

#### Include any warning/errors/backtraces from the system logs

```
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 2168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 2104, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 107, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 325, in do_create
    with Cache(repository, key, manifest, do_files=args.cache_files, lock_wait=self.lock_wait) as cache:
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 103, in __init__
    self.sync()
  File "/usr/lib/python3.6/site-packages/borg/cache.py", line 401, in sync
    with cache_if_remote(self.repository) as repository:
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 549, in cache_if_remote
    return RepositoryCache(repository)
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 520, in __init__
    tmppath = tempfile.mkdtemp(prefix='borg-tmp')
  File "/usr/lib/python3.6/tempfile.py", line 358, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/usr/lib/python3.6/tempfile.py", line 130, in _sanitize_params
    dir = gettempdir()
  File "/usr/lib/python3.6/tempfile.py", line 296, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python3.6/tempfile.py", line 231, in _get_default_tempdir
    dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/tmp', '/tmp', '/var/tmp', '/usr/tmp', '/c']

Platform: CYGWIN_NT-10.0 LAPTOP-FA89185Q 2.8.2(0.313/5/3) 2017-07-12 10:58 x86_64
Borg: 1.0.11  Python: CPython 3.6.1
PID: 5604  CWD: /c
sys.argv: ['/bin/borg', 'create', '--compression', 'lz4', '--info', '--stats', '--progress', '--show-rc', '::{utcnow}Z', '/c/Users/Åke Olson']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2 
```

**Comment by ThomasWaldmann** [comment]
what's this `cmd /c` for?

the python tempfile library determines the temp dir using some standard env vars, see there:

```
The default directory is chosen from a platform-dependent list,
but the user of the application can control the directory location
by setting the TMPDIR, TEMP or TMP environment variables. 
```

So, I'ld say this is not a borg bug, but either your environment is missing some entry or that platform-dependent list is kind of less than optimal for cygwin's python (which would be a Python bug).

**Comment by ThomasWaldmann** [comment]
you could fix that rather easily either in some shell startup script or in your borg backup script by:
```
export TEMP=/c/foobar/temp

borg ...
```

**Comment by ThomasWaldmann** [comment]
The easiest and guaranteed-to-work thing is to set it in your borg backup script.

Just make sure it gets into the environment (so `export ...` on UNIX) or it won't be inherited by the borg process.
