### ISSUE TITLE
unexpected norecurse behaviour for root path

### ISSUE THREAD

**Issue by heinrich-ulbricht** [borgbackup/borg#4228]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, I checked:
* `borg help patterns`
* generic googling
* searching for existing issues

## Is this a BUG / ISSUE report or a QUESTION?

Bug? At least unmet expectation.

#### Your borg version (borg -V).

1.1.8

#### Operating system (distribution) and version.

Debian GNU/Linux on Windows Subsystem for Linux (WSL)

#### Hardware / network configuration, and filesystems used.

Local folder to local folder backup.

#### How much data is handled by borg?

Not relevant, reproduction included below.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg create --list --stats --patterns-from /mnt/c/_Backups/borgbackupfiles.lst /mnt/c/_Backups/borg::Test`

## Describe the problem you're observing.

I expect the patterns in `patterns-from` file to be applied differently than observed. A minimal test case follows.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Directory structure for 100% reproduction:

* /mnt/c/Dev/Root
  * IgnoreMe _(folder to be ignored)_
  * IncludeMe _(folder to be included)_
    * includeme.txt

Pattern file:
```
R /mnt/c/Dev/Root/
+ /mnt/c/Dev/Root/IncludeMe
! /mnt/c/Dev/Root/**
```
**Expected result**: 
* I expect the folder `IncludeMe` to be backed up since the _exclude-norecurse_ rule "!" follows after the _include_ rule "+".

**Observed result**: 
* Nothing is being backed up. `/mnt/c/Dev/Root/` is being ignored.
* Console log: `x /mnt/c/Dev/Root`

Either my expectation about priority of the rules is wrong (that would mean that "!" always takes precedence over "+") OR this is a bug.

The exclude rule "-" behaves differently. I changed the pattern file to this (replacing "!" by "-"):

```
R /mnt/c/Dev/Root/
+ /mnt/c/Dev/Root/IncludeMe
- /mnt/c/Dev/Root/**
```

Now the `IncludeMe` folder is being backed up. The console shows:

```
x /mnt/c/Dev/Root
x /mnt/c/Dev/Root/IgnoreMe
A /mnt/c/Dev/Root/IncludeMe/includeme.txt
d /mnt/c/Dev/Root/IncludeMe
```
This is what I expected for "!" as well.

The documentation is not clear about "!" behaving differently than "-". Is this expected behavior?

**Comment by ThomasWaldmann** [comment]
iirc we specified a "first match" rule, so your expectation seems right.

**Comment by heinrich-ulbricht** [comment]
Thank you, that sounds indeed very logical and solves my problem. I  did not think about the root path being matched successfully with an empty string for **. This also explains why it seemed to work in other cases - where the root path was different.
Out of curiosity: it seems like the following patterns all solve my problem:
* `! /mnt/c/Dev/Root/?**`
* `! /mnt/c/Dev/Root/?*`
* `! /mnt/c/Dev/Root/**/`
Can you hint at which one is preferred from a performance standpoint?
Anyway, this ticket can be closed. Thanks again.
