### ISSUE TITLE
requirements of borg when installed via pip

### ISSUE THREAD

**Issue by henfri** [borgbackup/borg#4231]
Hello,

I just went through a bit of a hell installing borg  via pip on debian.
After installing
  537  apt-get install libssh-dev
  544  apt-get install build-essential
  546  apt-get install gcc
  548  apt-get install python3-dev
  551  apt-get install libssl-dev openssl
  553  apt-get install libacl1-dev

it works.
It would be nice, if these requirements were listed somewhere.

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
IIRC that is in the official install docs.

And I don't think we require libssh-dev.

**Comment by henfri** [comment]
Hello Thomas,

sorry, but I searched before creating this issue.
I looked at this place:
https://borgbackup.readthedocs.io/en/stable/installation.html#pip-installation
And there I do not find any requirements.

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
You're on the right page, just start reading at "from source".
The pip package is a source distribution.
