### ISSUE TITLE
Feature request: ETA indicator for long running processes

### ISSUE THREAD

**Issue by kakra** [borgbackup/borg#4232]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

borg 1.1.8

#### Operating system (distribution) and version.

Gentoo Linux, profile `default/linux/amd64/17.0/desktop/plasma/systemd`

#### Hardware / network configuration, and filesystems used.

local usage, btrfs source, xfs destination (repo)

#### How much data is handled by borg?

```
------------------------------------------------------------------------------
Archive name: system@20181226-0645
Archive fingerprint: 2ca305381f4cb7434b8ea151c6cd06c2d3b29ab71384731e30af89c448f8c11f
Time (start): Wed, 2018-12-26 06:45:42
Time (end):   Wed, 2018-12-26 17:12:02
Duration: 10 hours 26 minutes 20.39 seconds
Number of files: 4071578
Utilization of max. archive size: 2%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                2.43 TB              2.05 TB              1.63 GB
All archives:              135.94 TB            114.29 TB              2.76 TB

                       Unique chunks         Total chunks
Chunk index:                 6903780            264648769
------------------------------------------------------------------------------
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
BORG_REPO=/mnt/private/backup/jupiter.sol.local.borg borg check --repair -pv
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I need to check/repair my repository due to a previous system overload ending in a freeze. For better planning when the procedure needs my attention, I'd like to have an ETA indicator on the line showing the progress.

#### Include any warning/errors/backtraces from the system logs

This report is really not about the repository problem resulting from my system crash (I'm going to file a separate issue for that if I need support), it is actually about a feature request. I'm seeing a backtrace during normal operation but it doesn't belong here.

**Comment by ThomasWaldmann** [comment]
Giving an ETA is a problem with no really good solution.

https://xkcd.com/612/

Thus, we rather don't do it than causing lots of problems by giving wrong informations.

That much for the general issue, a special issue for borg is also that some operations are single-pass on an unknown amount of data (e.g. `borg create`), so there is no way to know how much data is coming. Adding another pass also adds additional runtime and it still might not lead to a good ETA because there are still enough unknown / fluctuating parameters to add enough uncertainty.

**Comment by kakra** [comment]
Yeah, the lovely windows file copy dialog... :-D

Well, I'm not interested in "borg create" ETA... I can guess that from previous runs looking at the logs.

I'd be interested in having ETAs for procedures that actually need my regular attention, like "borg check". And after all, ETA says "estimated". A bad estimation can be better than none at all. If it said "one hour left" I may decide to sit and wait, then start the next step, but if it said "10 hours left" I'd better decide to leave and return the next morning.

Without an ETA I don't know when to return. The only thing I can derive from previous runs is that one pass of "btrfs check" takes roughly 10-15 hours.

Maybe borg could add some switch like "--eta-I-know-it-is-inaccurate" to clearly communicate it is only an estimation? I know that giving an ETA during "borg check" with a set of very different archives will be fluctuating a lot. My archives are very similar (with a slight trend of becoming bigger over time), so it should be quite accurate. I also think there's not anything else except "borg check" that should show ETAs. If you create an archive, you run a test, then estimate your time window from the logs. If you extract an archive, you can probably expect about the same amount of time as the first creation of the archive (minus differences resulting from network/compression). So an ETA here would match your XKCD link.

Usually, when I automatically calculate ETAs in scripts, I extract the last 10-20 matching runs from logs, throw away the 10% best and worst times (given I have at least 10 runs), and then calculate an average from the remaining times. This works pretty well. If borg checks many archives (over 60 in my case), it could use a similar approach: Calculate a moving window average across the last 10 checks (removing best and worst times), then multiply the average with the remaining archives to check. We could even estimate an uncertainty from that and tell the user "+/- 1 hour" or something (by looking at the best and worst time of all runs even outside the moving window average).

Although I'm not familiar with python, I could try creating a patch for this if you're still interested.

BTW: My repository corruption probably results from the BLK-MQ data loss bug in kernel 4.19. Btrfs also complains about (correctable) csum errors now. So nothing to report here about that corruption.

**Comment by ThomasWaldmann** [comment]
We currently do not have infrastructure to store statistical data. Even if we had, there can be always huge differences in ssh or hdd throughput due to different load conditions.

So, I am not convinced yet that adding something like that would be an improvement or just add a lot of code for a questionable/unreliable feature. Guess we would just exchange open issues about missing eta for open issues about eta wrong.

Also, maybe there is not really a need to integrate this. If you can see in the logs that your last borg check took 5h, you'll know that it will take hours and you maybe don't want to wait.
