### ISSUE TITLE
Clarify the necessity to separately backup key in repokey mode

### ISSUE THREAD

**Issue by cornop** [borgbackup/borg#4234]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question / request to improve documentation

## Describe the problem you're observing.

`borg init --encryption=repokey-blake2` states:

```
IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).
```

while `borg init --help` says:

```
If you want "passphrase-only" security, use one of the repokey modes. The
key will be stored inside the repository (in its "config" file). In above
mentioned attack scenario, the attacker will have the key (but not the
passphrase).

[...]

Make a backup copy of the key file (keyfile mode) or repo config file
(repokey mode) and keep it at a safe place, so you still have the key in
case it gets corrupted or lost.
```

I find these contradicting. Do I need to export and separately store the key, or do I only need it in case the config gets corrupted?

**Comment by ThomasWaldmann** [comment]
What exactly do you find contradicting?

You want to backup the key, no matter whether you have it in the repo directory or in your home directory.

**Comment by cornop** [comment]
I know that I *want* to backup the key. The questions is whether I need the key to restore my backup (as opposed to needing the key only in case of corruption). `borg init` says I do, while the manual says I don't.

**Comment by ThomasWaldmann** [comment]
That you "need the key" for about every operation on an encrypted repo does not mean you explicitly have to give it to borg (like e.g. by specifying its path/filename).

It usually is discovered from either:
- the repository config file (`repokey` modes): the encrypted key is in `repository_dir/config` file
- a key file (`keyfile` modes): the encrypted key is (usually) in `~/.config/borg/keys/*` file

In both cases, the encrypted key is automatically read from there and gets decrypted using the passphrase (which is either queried from you interactively or read from environment or read from the output of some command or via a file descriptor).

**Comment by ThomasWaldmann** [comment]
So I'm not sure how to formulate the docs less confusing, maybe make a pull request to improve it.
