### ISSUE TITLE
Binary readme says Debian wheezy 7

### ISSUE THREAD

**Issue by BarbzYHOOL** [borgbackup/borg#4239]
This file says debian wheezy 7

Is it right or not updated? https://github.com/borgbackup/borg/releases/download/1.1.8/README.txt

**Comment by ThomasWaldmann** [comment]
The binaries are still built on wheezy. There is a ticket about moving to a newer dist.

**Comment by BarbzYHOOL** [comment]
Ok thank you, I'm on debian 9
