### ISSUE TITLE
info -v shows nothing new 0.28.1

### ISSUE THREAD

**Issue by ClipperS87** [borgbackup/borg#424]
usinge borg info with the -v verbose flag gives the same output as without....

**Comment by ThomasWaldmann** [comment]
-v is a flag that is globally provided by borg main command (not by subcommands).
some subcommands might use it, some not.

**Comment by anarcat** [comment]
this is related to #425: in the original logging refactoring pass, the default logging level was WARNING and `-v` was making INFO messages show up. now `-v` makes DEBUG messages show up, and we have very few of those. so in effect, `-v` is currently almost useless.

**Comment by ThomasWaldmann** [comment]
No, -v does not make DEBUG messages show up, it just generates more output on INFO level (like showing all files for `borg create`).

DEBUG messages are for developers or users debugging together with a developer. We currently do not have much DEBUG messages (if any).

**Comment by anarcat** [comment]
ah well, that explains #425 and the documentation inconsistencies. that's not the way i designed the logging refactoring...
