### ISSUE TITLE
Argparse for serve comment

### ISSUE THREAD

**Issue by step21** [borgbackup/borg#4240]
In `archiver.py` there is

```
def parse_args(self, args=None):
        # We can't use argparse for "serve" since we don't want it to show up in "Available commands"
```

but at least for me it does show up under commands. Is this intended or is the comment just old?

**Comment by ThomasWaldmann** [comment]
Hmm, right. In 1.1-maint branch, `borg --help` and `borg help` both show the `serve` command.
