### ISSUE TITLE
Cannot backup up folder with ACL-restricted parent folder (permission error)

### ISSUE THREAD

**Issue by heinrich-ulbricht** [borgbackup/borg#4250]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG?

#### Your borg version (borg -V).
1.1.7

#### Operating system (distribution) and version.
Fedora 28

#### Hardware / network configuration, and filesystems used.
Synology Disk Station (runs Linux) -> Folders on the Disk Station (secured with ACL) -> cifs-mounted in Fedora -> subfolder should be backed up via Borg on Fedora

Note that currently my assumption is that this is a problem related only to ACLs being used (see details below). But mounting it from the Disk Station might contribute to the problem.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg create --list --stats --filter=AME --patterns-from /home/user/borg-backup-patterns.lst --progress /home/user/BorgBackup::Test /home/user`

Patterns file contains among others:
`+ /home/user/Mount/RootFolder/SubFolder`

## Describe the problem you're observing.

I want to back up only folder _SubFolder_. The structure is as follows:
* _RootFolder_
  * _SubFolder_

Borg fails with error:
_/home/user/Mount/RootFolder: scandir: [Errno 13] Permission denied: '/home/user/Mount/RootFolder'_

But I expect Borg to successfully back up _SubFolder_ as specified in the include file since I can see and read its contents via console.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

_RootFolder_ is secured with the following ACL allowing only traversal and viewing permissions:
`user:svc-backup:allow:--x-------c--:---n (level: 0)`
(x=execute, c=read ACL, n=no propagate)

On _SubFolder_ read access is allowed:
`user:svc-backup:allow:r-x---a-R-c--:fd-- (level: 0)`
(r=read data, x=execute, a=read attribute, R=read xattr, c=read ACL, inherit)

Note that when doing `ls` for _RootFolder_ I see no files or folders and get the following error:
_ls: reading directory '.': Permission denied_
This is ok.

Nevertheless `cd SubFolder` works and I can read its contents. And I expect Borg to be able to do the same.

**Comment by heinrich-ulbricht** [comment]
Given the backup scenario I described shouldn't the following succeed (note: it does not)?

Command:
`borg create --list --stats --filter=AME --patterns-from /home/user/borg-backup-patterns.lst --progress /home/user/BorgBackup::Test /home/user`

Pattern file _borg-backup-patterns.lst_:
```
R /home/user/Mount/RootFolder/SubFolder

R /home/user/
- /home/user/*
```
I expect _/home/user/Mount/RootFolder/SubFolder_ to be backed up. But it's not. Sure I get this during backup: _/home/user/Mount/RootFolder: scandir: [Errno 13] Permission denied: '/home/user/Mount/RootFolder'_
But it should try to handle the second root pointing directly to the subfolder - or not?

**Comment by ThomasWaldmann** [comment]
It is as infectormp noted.

Also:
- it does not matter whether one gives a recursion root ("starting path") on the command line or in the patterns file - all of them will be used as roots.
- borg starts the recursion at these roots and then uses the include/exclude patterns to decide what to include or exclude.
- files below the recursion root are included by default, so the include patterns primary usage is for stuff below a previously excluded path.
