### ISSUE TITLE
Borg fails extracting backup with ValueError: 262971 exceeds max_array_len(131072)

### ISSUE THREAD

**Issue by jtek** [borgbackup/borg#4257]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

borg 1.1.8

#### Operating system (distribution) and version.

Arch Linux up to date as of 2019/01/17

#### Hardware / network configuration, and filesystems used.

- Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
- 16 GB RAM
- 1TB NVME
- internal Wifi
- BTRFS

#### How much data is handled by borg?

Daily backups of a database dump (~20GB).

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Here is the anonymised version : 

borg extract --debug -p -v --remote-path=borg1 <user>@<host>:<repo>::<backup>

## Describe the problem you're observing.

Backup fails after printing Calculating Size, which is overwritten by a stack trace (the e in Exceptione below is probably from "Calculating Size"

Local Exceptione                                                                                                                             
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 152, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 165, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 736, in do_extract
    extracted_size = sum(item.get_size(hardlink_masters) for item in archive.iter_items(filter))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 736, in <genexpr>
    extracted_size = sum(item.get_size(hardlink_masters) for item in archive.iter_items(filter))
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 438, in iter_items
    filter=lambda item: self.item_filter(item, filter)):
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 208, in unpack_many
    items = [Item(internal_dict=item) for item in unpacker]
  File "/usr/lib/python3.7/site-packages/borg/archive.py", line 208, in <listcomp>
    items = [Item(internal_dict=item) for item in unpacker]
  File "msgpack/_unpacker.pyx", line 533, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 464, in msgpack._cmsgpack.Unpacker._unpack
ValueError: 262971 exceeds max_array_len(131072)

Platform: Linux cheetah 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.2
PID: 6435  CWD: <cwd>
sys.argv: ['/usr/bin/borg', 'extract', '--debug', '-p', '-v', '--remote-path=borg1', '<user>@<host>:<repo>::<backup>']
SSH_ORIGINAL_COMMAND: None

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The problem is systematic.

#### Include any warning/errors/backtraces from the system logs

See output above.

There is a workaround : 

at line 208 of archive.py, changing

unpacker = msgpack.Unpacker(use_list=False)

to

unpacker = msgpack.Unpacker(use_list=False, max_array_len=4*128*1024)

solves the problem (the backup is currently restoring).
I didn't try other values for max_array_len but given the exception 2*128*1024 would at least have been too low.

python-msgpack is 0.6.0-1

**Comment by ThomasWaldmann** [comment]
see #4251.
