### ISSUE TITLE
How to deal with "Encryption envelope checksum mismatch"

### ISSUE THREAD

**Issue by dutchgecko** [borgbackup/borg#4258]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.8 (both machines)

##### Host

`Linux alchemist 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`

##### Client

Client was used to create backups, not being used for `borg recreate` or `borg check --verify-data`

`CYGWIN_NT-10.0 shendelzare 2.10.0(0.325/5/3) 2018-02-02 15:16 x86_64 Cygwin`

##### Host

`/dev/md0 /media/raid xfs rw,relatime,attr2,inode64,sunit=1024,swidth=2048,noquota 0 0`

```
md0 : active raid6 sdd[0] sde[4] sdc[1] sdb[5]
      5860270080 blocks super 1.2 level 6, 512k chunk, algorithm 2 [4/4] [UUUU]
      bitmap: 0/22 pages [0KB], 65536KB chunk
```

`Python 3.5.3`

##### Client

All mountpoints NTFS.

`BORG_RSH="ssh -i $SSHKEY -o PreferredAuthentications=publickey"`

`Python 3.6.4`

#### How much data is handled by borg?

```
All archives:                3.63 TB              3.06 TB            140.89 GB

                       Unique chunks         Total chunks
Chunk index:                  488477             11926697
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Run directly on host:

`borg recreate --verbose --stats --compression 'auto,zstd,4' --recompress if-different --progress --chunker-paramsdefault windowscygwin`

Confirmed with:

`borg check --info --verify-data --archives-only windowscygwin`

## Describe the problem you're observing.

Borg exits with error "Encryption envelope checksum mismatch" when running `recreate`:

``` pytb
Processing documents_20161227_1245
Data integrity error: Chunk 5daed89e93db0c6da41be8be6dcbf9f5c042fc3dfe2d4b1d48e0f25fdad13022: Encryption envelope checksum mismatch
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 150, in wrapper
    return method(self, args, repository=repository, cache=cache_, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/borg/archiver.py", line 1706, in do_recreate
    if not recreater.recreate(name, args.comment):
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 1660, in recreate
    self.process_items(archive, target)
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 1698, in process_items
    self.process_item(archive, target, item)
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 1704, in process_item
    self.process_chunks(archive, target, item)
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 1716, in process_chunks
    target.chunk_file(item, self.cache, target.stats, chunk_iterator, chunk_processor)
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 955, in chunk_file
    for data in chunk_iter:
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 1740, in iter_chunks
    yield from target.chunker.chunkify(file)
  File "src/borg/chunker.pyx", line 50, in borg.chunker.Chunker.__next__
  File "/usr/local/lib/python3.5/dist-packages/borg/helpers.py", line 2011, in read
    read_data = self._read(nbytes)
  File "/usr/local/lib/python3.5/dist-packages/borg/helpers.py", line 2003, in _read
    remaining = self._refill()
  File "/usr/local/lib/python3.5/dist-packages/borg/helpers.py", line 1991, in _refill
    chunk = next(self.chunk_iterator)
  File "/usr/local/lib/python3.5/dist-packages/borg/archive.py", line 223, in fetch_many
    yield self.key.decrypt(id_, data)
  File "/usr/local/lib/python3.5/dist-packages/borg/crypto/key.py", line 391, in decrypt
    raise IntegrityError('Chunk %s: Encryption envelope checksum mismatch' % id_str)
borg.helpers.IntegrityError: Data integrity error: Chunk 5daed89e93db0c6da41be8be6dcbf9f5c042fc3dfe2d4b1d48e0f25fdad13022: Encryption envelope checksum mismatch

Platform: Linux alchemist 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64
Linux: debian 9.6
Borg: 1.1.8  Python: CPython 3.5.3
PID: 5390  CWD: /media/raid/geckobackup/repos
sys.argv: ['/usr/local/bin/borg', 'recreate', '--verbose', '--stats', '--compression', 'auto,zstd,4', '--recompress', 'if-different', '--progress', '--chunker-params', 'default', 'windowscygwin']
SSH_ORIGINAL_COMMAND: None
```

After this error, the corrupt chunk can be verified with `borg check --verify-data`:

`chunk 5daed89e93db0c6da41be8be6dcbf9f5c042fc3dfe2d4b1d48e0f25fdad13022, integrity error: Data integrity error: Chunk 5daed89e93db0c6da41be8be6dcbf9f5c042fc3dfe2d4b1d48e0f25fdad13022: Encryption envelope checksum mismatch`

~~**I have not yet verified if the chunk was already bad before `recreate`**, I need to test this tomorrow.~~ Update: now verified that the chunk is incorrect in the original repo.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

This problem has occurred twice while running recreate, each time taking a fresh copy of the unaltered repository. Using `verify-data` seems to confirm that it is specifically this chunk which is causing a problem. Other repositories stored on this machine have been recreated without a problem.

The chunk in question is present in an archive from December 2016 (and presumably later iterations of that archive).

Mdadm reports no errors with the array (scrubbing occurs every three days). SMART status for component drives shows nothing unusual.

`borg check` without `--verify-data` reports no problems.

`borg check --verify-data` is currently still running as mdadm is running a scheduled scrub which has tanked filesystem performance. Finding other affected chunks could take a number of hours yet, I'll update if there are more.

Action not yet taken: 

* running `xfs_check` on the filesystem (fs must be offline or readonly first)
* ~~running `borg check --verify-data` on the unaltered (no `recreate`) repository~~

edit: `borg check --verify-data` has been run on the unaltered repository and found the same issue, so the problem is unrelated to `recreate`.

### My question

What do I do about this error? Do I need to do anything? Has archived data been lost?

If the stored data is still "technically correct", is there a way of removing the error so that `recreate` can continue?

I realise I might need to add more information, but I wanted to post this up before going to bed.

**Comment by ThomasWaldmann** [comment]
Consider some other hw issues also: bad RAM, bad other hw. client and server.

See borg docs about integrity issues about how to diagnose. You need to check hw first before doing more heavy operations on the repo.

**Comment by ThomasWaldmann** [comment]
That specific chunk has a bad cryptographic authentication tag, so either the tag or (more likely) the data is corrupted. Due to deduplication, you only have that chunk once in the repo, so every archive using it has the corrupt data.

There is some slight chance that you might still have the correct chunk at the source (on the machine you back up).

borg can heal a defect chunk:
- the bad one is removed by a `borg check --repair` (replaced with a dummy all-zero chunk)
- the correct one is added by a `borg create` (IF you still have the data that produces the chunk)
- the correct one is used for healing by another `borg check --repair` (healing all archives that reference the replacement chunk)

**Comment by dutchgecko** [comment]
Thanks for your help. The corrupted chunk was found by repair, and replaced by a fresh backup.

If I remember correctly (going back to 2016) my client machine was plagued by some gremlins ultimately caused by a faulty PSU at the time (it's the reason I started looking for a robust backup solution). This is probably enough to explain the cause of the corruption.

Regarding the use of `--verify-data`: I currently run a simple `borg check` after every backup, is it wise to include `--verify-data` to this daily run? I think fundamentally I don't understand when corruption would occur that is detected by a full check but not by the faster CRC.

**Comment by dutchgecko** [comment]
Very clear answers, thanks for your help!

**Comment by JingleheimerSE** [comment]
@ThomasWaldmann thanks for the very useful info on this as I've also hit `Encryption envelope checksum mismatch` on several of my repo chunks and its helped explain what is going on.

I am curious if you can answer a few of my questions about my options to resolve the issue though:
- You mentioned the option "_the correct one is added by a `borg create` (IF you still have the data that produces the chunk)_", is there a way to get the filename a chunk is associated with? I may still have the file but don't know which file I should be looking for.
  - Also, is it possible to determine which backups the chunk is used by? I was able to mount my oldest backup without hitting this issue but my second oldest is where things broke down and I'm wondering if all my subsequent backups rely on these chunks.
- If I run `--repair` and the data is zeroed, will that silently corrupt the data when mounting the backup? I'd rather just exclude or remove those files from the backup when mounting so maybe I should do a `recreate` and remove those paths instead?
- I'm not sure I understand the difference between `--repair` zeroing the data vs. healing it as you mention with "_the correct one is used for healing by another `borg check --repair` (healing all archives that reference the replacement chunk)_". How could the data be healed if deduplication means there is only one copy of the corrupted data?

Thanks again!

**Comment by ThomasWaldmann** [comment]
@JingleheimerSE I don't think we have code to get the filename. Guess the filename is known in `process_item`, but not at the place where the exception is raised. Maybe one can give `--list` option to find out the filename.

Neither do I think we have code to find which archives use a specific defect chunk.

It is really expected that you run `borg check --repair` to bring the repo in a consistent state. IIRC if you mount a repo or archive and try to read an all-zero replacement chunk, it will by default produce an IOError for that chunk (and there is an option NOT to do that), so there is no silent corruption.

The healing only works if a missing chunk reappears. Usually this requires:
- borg check --repair (will replace missing chunk with all-zero chunk, but still remember the correct original chunkid of the missing chunk)
- borg create reproducing the missing chunk in the repo (because the chunk is still in the input data)
- borg check --repair noticing that the chunk reappeared and fixing all references to use the correct chunk again and not the replacement chunk
