### ISSUE TITLE
HTTP API

### ISSUE THREAD

**Issue by turtle0x1** [borgbackup/borg#4259]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes
## Is this a BUG / ISSUE report or a QUESTION?
Not that I can see

## Describe the problem you're observing.
I have read [here in the documentation](https://borgbackup.readthedocs.io/en/stable/internals/frontends.html?highlight=api#) about creating front end "but does mean that there are no release-to-release guarantees on what you might find in that package"

Is there any future plans to include the ability to remote call this would allow for web based & other front ends?

**Comment by turtle0x1** [comment]
I have seen [borgweb](https://github.com/borgbackup/borgweb/tree/master/borgweb) but it seems quite limited in functionality?

**Comment by ThomasWaldmann** [comment]
borg is a cli tool, these usually have no http api.

borgweb isn't intended to be a full UI for borg, but covers just some specific usecases.

btw, vorta is a nice qt gui for borg, if that helps you.

**Comment by turtle0x1** [comment]
For example you have LXC / LXD, where LXD is a daemon that exposes the functionality of lxc to clients

**Comment by ThomasWaldmann** [comment]
you can now also build stuff on it, see vorta.

integrating daemon/service-like functionality might make networked clients possible, otoh, it also opens potential attack surface and might end up in security issues.

**Comment by turtle0x1** [comment]
I understand the concern with not wanting to opening an attack vector, it could be disabled by default.

With vorta they seem to run CLI commands which could be potentially available to command injection (vorta is a local program so its unlikely). 

If I was to run a web server with php and expose it I would have to perform `exec()` commands (just a vorta) which is fine but is also potentially a victim of command injection.

You also have the issue of command line flags changing over time which would make back version applications hard (although I suppose parameter changing in a rest api has the same problem)

Of course with daemon it can access the functions natively without needing to worry about escaping shell commands or worry about command flags changing.

**Comment by ThomasWaldmann** [comment]
api stability issues are always there, not matter whether the api is cli, python or some http interface.

currently, only the cli api (with json output for automation) is considered relatively stable.
there is no http or other kind of daemon, this there is no api and i currently consider this out of scope.
