### ISSUE TITLE
{hostname} isn't always the short hostname, but FQDN

### ISSUE THREAD

**Issue by pille** [borgbackup/borg#4262]
## Have you checked borgbackup docs, FAQ, and open Github issues?
yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

1.1.8

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create "::{hostname}_test" /tmp/
```
## Describe the problem you're observing.

```
borg list
```
some backup sets have short hostname and some FQDN. e.g.:
```
tmp1_test
tmp2.example.com_test
```

using shell variables/commands work as a workaround:
```
borg create "::${hostname --short}_test" /tmp/
```
```
tmp1_test
tmp2_test
```

**Comment by ThomasWaldmann** [comment]
What does the `hostname` shell command output on the hosts where the fqdn archive names are created?

**Comment by pille** [comment]
it wrongly reports the same, but that's not the point. according to documentation ```{hostname}``` should return the short hostname. ```hostname --short``` and ```hostname --fqdn``` behave correctly.

**Comment by infectormp** [comment]
@pille can you print out `/etc/hostname` here?

**Comment by pille** [comment]
for reasons it's:
```
tmp1
```
```
tmp2.example.com
```

**Comment by infectormp** [comment]
`/etc/hostname` must have only 1 record `tmp1` so i not see any problem at borg side.

**Comment by infectormp** [comment]
You can set FQDN name as the first column in /etc/hosts for the server's IP, followed by the short name.
```
/etc/hosts:

127.0.0.1   localhost 
::1         localhost 

10.2.17.15   tmp2.example.com tmp1
```

**Comment by pille** [comment]
@infectormp: as i said, this setup has it's reasons.
the whole point of this issue was to create awareness that documentation is not in sync with implementation. hostnames may contain multiple words seperated by dots.
either fix the code or the docs. i'll live with my workaround.

**Comment by ThomasWaldmann** [comment]
relevant borg 1.1.8 code: https://github.com/borgbackup/borg/blob/master/src/borg/platform/base.py#L250

https://docs.python.org/3/library/socket.html#socket.gethostname

**Comment by ThomasWaldmann** [comment]
Considering the last link, this might be rather a bad system configuration than a borg issue?

**Comment by infectormp** [comment]
https://docs.fedoraproject.org/en-US/Fedora/13/html/Installation_Guide/sn-networkconfig-fedora.html

> **Valid Hostnames**
You may give your system any name provided that the full hostname is unique. The hostname may include letters, numbers and hyphens.

**Comment by ThomasWaldmann** [comment]
@infectormp hah, that phrasing can easily mislead. Considering they don't mention dots, they mean the short name. But also speaking about the uniqueness of the full name here might mislead people to think that the full name is (completely) defined here.

**Comment by ThomasWaldmann** [comment]
I've looked up in the C source how `hostname --short` does it:

it will just truncate at the first dot, if there is any.

**Comment by ThomasWaldmann** [comment]
see #4276.
