### ISSUE TITLE
Borg should raise clear Exception on cache permission mismatch 

### ISSUE THREAD

**Issue by gthieleb** [borgbackup/borg#4263]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## Describe the problem you're observing.

I use `borg` for backup `/home` with my unprivileged user. 

I also use `borg` to backup systemrelevant files and VM disks using `sudo borg`. I do use `sudo` to catch files my unprivileged user does not have access to.

After every run of privileged `sudo borg` the ownership of `~/.config/borg` and `~/.config/cache` changes to `root:root` for the relevant backup hash path.

This makes it impossible to use any  `borg` related command as unprivileged user against the archive.
The workaround is to set back the ownership.

This is accepted behavior for me, so far.

It would be great if borgs exception handling would become more clear about the error it has.

Currently the exception is printed in raw format:

```
borg list /run/media/gt0015/b86a9ff9-6c1f-4f76-9a60-9849f92289da/backup
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4434, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4366, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 143, in wrapper
    assert_secure(repository, kwargs['manifest'], self.lock_wait)
  File "/usr/lib64/python3.6/site-packages/borg/cache.py", line 206, in assert_secure
    sm.assert_secure(manifest, manifest.key, lock_wait=lock_wait)
  File "/usr/lib64/python3.6/site-packages/borg/cache.py", line 171, in assert_secure
    with cache_config:
  File "/usr/lib64/python3.6/site-packages/borg/cache.py", line 238, in __enter__
    self.open()
  File "/usr/lib64/python3.6/site-packages/borg/cache.py", line 262, in open
    self.load()
  File "/usr/lib64/python3.6/site-packages/borg/cache.py", line 267, in load
    self._check_upgrade(self.config_path)
  File "/usr/lib64/python3.6/site-packages/borg/cache.py", line 326, in _check_upgrade
    raise Exception('%s does not look like a Borg cache.' % config_path) from None
Exception: /home/gt0015/.cache/borg/31eeac759ae30fc173c017dccc30b646868a6e46e4c7143d85f99a70647841c2/config does not look like a Borg cache.

Platform: Linux t470p 4.19.10-200.fc28.x86_64 #1 SMP Mon Dec 17 15:46:19 UTC 2018 x86_64
Linux: Fedora 28 Twenty Eight
Borg: 1.1.7  Python: CPython 3.6.7
PID: 32486  CWD: /home/gt0015
sys.argv: ['/usr/bin/borg', 'list', '/run/media/gt0015/b86a9ff9-6c1f-4f76-9a60-9849f92289da/backup']
SSH_ORIGINAL_COMMAND: None
```
It would be great that borg would catch this exception and print a human readable error message, pointing out the ownership mismatch.

**Comment by ThomasWaldmann** [comment]
Hmm, that almost looks a bit like a bad exception handler. We need to check this, a "PermissionDenied" exception should not be catched and lead to other exception like seen above.

**Comment by ThomasWaldmann** [comment]
This is from stdlib configparser code:
```
            try:
                with open(filename, encoding=encoding) as fp:
                    self._read(fp, filename)
            except OSError:
                continue
```
So looks like a **diaper pattern**, but not in the borg code, so not much we can do about it.

**Comment by ThomasWaldmann** [comment]
What you can do about your fundamental permissions issue:

Use `sudo -H`, so the borg running as root user will use root's home directory and not mess up the user's home dir. Of course you will need to put borg keys etc. there also.

**Comment by ThomasWaldmann** [comment]
we can open the file ourselves and use the configparser.read_file(fd) method.

**Comment by gthieleb** [comment]
@ThomasWaldmann thanks for the fix. I'll try asap. Regarding your suggestion using `sudo -H`. Sound that I need to maintain the key on two places. For remote (ssh) borg backup I have the idea, adapted from rsync, to use the `--remote-path="sudo borg"`. Do you think that will work, too?

**Comment by ThomasWaldmann** [comment]
you don't need sudo, you can also just use `borg@localhost:/repo` with ssh.
