### ISSUE TITLE
--filter 'R /some/dir' on CLI doesn't seem to have any effect

### ISSUE THREAD

**Issue by strugee** [borgbackup/borg#4265]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

A bug, I _think_? Docs are very scant so I may just be using it wrong

#### Your borg version (borg -V).

borg 1.1.8 installed from Debian backports

#### Operating system (distribution) and version.

Debian 9.6 stretch

#### Hardware / network configuration, and filesystems used.

Borg talks to a local Google Drive FUSE filesystem. Underlying fs for the rest of the system is ZFS.

#### How much data is handled by borg?

The entire system; several TB original and ~223GB after compression and deduplication

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create --stats --compression auto,lzma,6 --filter 'R /media/borg-stage/' --exclude /root/.gdfuse/defa
ult/cache --exclude /root/.cache [more excludes omitted] /media/gdrive/borg::steevie-$(date +%F-%H:%M-%a-%s) /etc/ /home /srv /
usr/local /root /var /opt /boot /bin/ /lost+found /lib /lib64 /sbin /vmlinuz* /initrd.img* /usr
```

Including `--exclude`s despite the directions not to because it seems like those might interact with `R` in some way.

## Describe the problem you're observing.

Borg does not seem to respect `--filter 'R /media/borg-stage/'` (a wrapper script arranges for this directory to be a temporary ZFS snapshot such that all my Borg backups look atomic after creation). I diagnosed this by inspecting `/proc/$pid/fd` and observing that Borg was opening files directly in `/` instead of the provided alternate root.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Haven't tried reproducing it cause Borg runs take a while for me, but  this seems pretty obviously reproducible.

#### Include any warning/errors/backtraces from the system logs

None that I can see.

**Comment by ThomasWaldmann** [comment]
The filter option is only intended to filter for the status (first char) output of `borg create --list`, like A for Added or E for Error.

**Comment by strugee** [comment]
Oh man, I feel really dumb - I meant to be using `--pattern`. I changed my script to use that and I observe the same behavior: the root directory isn't changed.

Here's the new commandline:

    borg create --progress --stats --compression auto,lzma,6 --pattern 'R /media/borg-stage/' --exclude /root/.gdfuse/default/cache --exclude /root/.cache [more excludes omitted] /media/gdrive/borg::steevie-$(date +%F-%H:%M-%a-%s) /etc/ /home /srv /usr/local /root /var /opt /boot /bin/ /lost+found /lib /lib64 /sbin /vmlinuz* /initrd.img* /usr

**Comment by ThomasWaldmann** [comment]
The `R` pattern is not like doing a chroot, so you will need that path prefix in your other patterns.

**Comment by ThomasWaldmann** [comment]
Also, you are mixing the older (--exclude) and the newer (--pattern) system, maybe rather decide for one of them.

**Comment by ThomasWaldmann** [comment]
@strugee interesting hack with the `3<<EOF`.

don't your `!` and `+` pathes all start with `/new/root/mountpoint/`?

**Comment by strugee** [comment]
> @strugee interesting hack with the `3<<EOF`.

Thanks :-)

> don't your `!` and `+` pathes all start with `/new/root/mountpoint/`?

No, they don't. Should they? Does `R` not affect those lines? Perhaps I misunderstood this:

> The `R` pattern is not like doing a chroot, so you will need that path prefix in your other patterns.

Since the behavior I want basically _is_ a chroot. (E.g. with the current script, all the files in the archive have `new/root/mountpoint/` prepended to them, which is not what I want.) Is `R` not the right tool for this? Is it even possible with current Borg releases?

Thinking out loud, I guess since it seems that Borg doesn't actually record the root `/` anyway, I could just `cd` into `/new/root/mountpoint` and get the same behavior that I want? Does that make sense to you?

**Comment by ThomasWaldmann** [comment]
R is a root, but not a chroot.
