### ISSUE TITLE
--verbose does very little

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#427]
splitting from #426 at the request of @ThomasWaldmann...

`--verbose` is currently only used in 6 calls in the whole program (or more precisely, it is used only in one place, in `print_info`, and that is called 6 times total):

```
archiver.py:68:        self.print_info("%1s %s", status, remove_surrogates(path))
archiver.py:290:            self.print_info(remove_surrogates(orig_path))
archiver.py:376:            self.print_info("Mounting filesystem")
archiver.py:479:            self.print_info('Keeping archive: %s' % format_archive(archive))
archiver.py:482:                self.print_info('Would prune:     %s' % format_archive(archive))
archiver.py:484:                self.print_info('Pruning archive: %s' % format_archive(archive))
```

The first one is the file listing on `create`. That should be a topical flag like `--changed` or `--unchanged` or `--list`. The second one is the file listing on extract, which could simply be logging.info(). I believe the other `print_info()` calls should simply be `logging.info()` calls.

i would of course be happy to implement such a change and cleanup the `print_*` calls that seem like unnecessary abstraction.

right now, i think the semantics of `--verbose` are confusing: some commands use it, some don't. By mapping it to `info`, we enforce some program-wide semantics that can be easily understood... 

if #426 goes through and we have a `--log-level` parameter, what is the meaning of `--verbose`, considering it is basically unused?

**Comment by ThomasWaldmann** [comment]
fixed by https://github.com/borgbackup/borg/commit/f2d41b1a6930b3c1a2ba45028401604aa4c7485c
