### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ftpbackup/repo/nonce.tmp' from 'borg prune' on ftpfs

### ISSUE THREAD

**Issue by SystemParadox** [borgbackup/borg#4283]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

borg 1.1.8

#### Operating system (distribution) and version.

Linux (Debian 9) kernel 4.9.0-8-amd64

#### How much data is handled by borg?

This archive: 12.08 GB (2.35 GB deduplicated)
All archives: 48.92 GB (6.46 GB deduplicated)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
BORG_REPO=/mnt/ftpbackup/repo
borg prune --list --show-rc --keep-within 2d --keep-daily 7 --keep-weekly 4 --keep-monthly 6
```

## Describe the problem you're observing.

When backing up to a filesystem mounted with curl-ftpfs, "borg create" works fine, but "borg prune" results in the following error:

```
Pruning archive: 2019-01-24-1517                      Thu, 2019-01-24 15:17:36 [cf9a4293e6e780044adfb6036fe059175ae2a36fcf286536336d49252ac421f5] (1/1)
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4436, in main
  File "borg/archiver.py", line 4368, in run
  File "borg/archiver.py", line 152, in wrapper
  File "borg/archiver.py", line 1596, in do_prune
  File "borg/helpers.py", line 411, in write
  File "borg/crypto/key.py", line 371, in encrypt
  File "borg/crypto/nonces.py", line 85, in ensure_reservation
  File "borg/crypto/nonces.py", line 48, in commit_repo_nonce_reservation
  File "borg/repository.py", line 323, in commit_nonce_reservation
  File "borg/platform/base.py", line 167, in __enter__
  File "src/borg/platform/linux.pyx", line 248, in borg.platform.linux.SyncFile.__init__
  File "borg/platform/base.py", line 106, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ftpbackup/repo/nonce.tmp'
```

The same script is also used to backup this machine over ssh and that works fine.

I expect this may well be an issue with ftpfs, so I'm mainly asking to see if there is a simple solution. However, I am confused that 'borg create' works but 'borg prune' does not.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, the problem occurs whenever prune tries to remove an archive.

**Comment by ThomasWaldmann** [comment]
the code uses open mode "x" to create a file and get exclusive access to it.

https://stackoverflow.com/questions/29295654/what-does-python3-open-x-mode-do

"no such file or directory":
- "no such file": doesn't make sense here as it is expected to create the file.
- "no such directory": hmm, maybe the path does not even exist?

in general, if that works locally (as it usually does), it means that the filesystem you are using is broken.

**Comment by SystemParadox** [comment]
Does 'borg create' use a nonce file, or is it just 'borg prune'?

**Comment by ThomasWaldmann** [comment]
all repo writing ops need it for encryption.

**Comment by SystemParadox** [comment]
Ok then I'm confused as to why it works with 'borg create', but not with 'borg prune'.

I thought it might be an issue with the mount not being in sync after doing the 'borg create', but I still have the same problem if I just run 'borg prune' on its own without creating first.

**Comment by SystemParadox** [comment]
Apparently curlftpfs 0.9.2 had the following in the release notes:

> Be aware that some applications might not be able to "save" files on curlftpfs from 0.9.2 on,
> because we don't support open(read+write) or open(write) and seek anymore

Possibly that is the issue? There's a compile flag `-DCURLFTPFS_O_RW_WORKAROUND`, but there's no runtime option so I'm leaving that  well alone.

I still don't understand why 'borg create' works though.

**Comment by SystemParadox** [comment]
I'm working around this by getting borg to backup to the local disk and then using rsync to copy that to the ftp mount. Even then I had to use `rsync --temp-dir` to make rsync use the local disk for temporary files, otherwise it throws the error: `rsync: mkstemp "[FILE]" failed: Operation not supported (95)`.

I'd love to know why borg is able to create and not prune, but I haven't been able to come up with anything. There are clearly some issues with curlftpfs so feel free to just close this if it's not something you're interested in supporting. Thanks!

**Comment by infectormp** [comment]
One more issue about curlftpfs https://github.com/borgbackup/borg/issues/3601

**Comment by ThomasWaldmann** [comment]
you could run an strace and see if it gives more clues about what works and what not.

but this is an issue with your filesystem, not with borg.
