### ISSUE TITLE
ArchiverTestCase.test_corrupted_repository fails in python3.7 / fedora rawhide

### ISSUE THREAD

**Issue by bpereto** [borgbackup/borg#4287]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug?

#### Your borg version (borg -V).
1.1.8

#### Operating system (distribution) and version.
* fedora rawhide
* Fedora Rawhide has python 3.7.2

## Describe the problem you're observing.

Fedora Rawhide Package build fails in testing:
```
=================================== FAILURES ===================================
__________________ ArchiverTestCase.test_corrupted_repository __________________
self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_corrupted_repository>
    def test_corrupted_repository(self):
        self.cmd('init', '--encryption=repokey', self.repository_location)
        self.create_src_archive('test')
        self.cmd('extract', '--dry-run', self.repository_location + '::test')
        output = self.cmd('check', '--show-version', self.repository_location)
        self.assert_in('borgbackup version', output)  # implied output even without --info given
>       self.assert_not_in('Starting repository check', output)  # --info not given for root logger
E       AssertionError: 'Starting repository check' unexpectedly found in 'borgbackup version 1.1.8\nStarting repository check\nStarting repository index check\nCompleted repository check, no problems found.\n'
build/lib.linux-x86_64-3.7/borg/testsuite/archiver.py:1494: AssertionError
 1 failed, 2233 passed, 310 skipped, 142 deselected, 4 xfailed in 909.07 seconds 
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.sHksSs (%check)
BUILDSTDERR:     Bad exit status from /var/tmp/rpm-tmp.sHksSs (%check)
```
https://bugzilla.redhat.com/show_bug.cgi?id=1669083

* Can it be related to https://github.com/borgbackup/borg/issues/3805 ?

Applied fix https://github.com/ThomasWaldmann/borg/commit/a9d523d6d80fc4fe4fa76b051ad16a286a7c1a43 mentions some issues with `logging.clear()`.
`setup_logging` in https://github.com/borgbackup/borg/blob/817c2b38a33071fbfeacf0fbfe17f01e88e11181/src/borg/logger.py#L107 has also a logger clear statement.

If I remove `setup_logging()` all the tests in `testsuite/archiver.py` are passing.

```
--- a/src/borg/testsuite/archiver.py	2018-12-09 03:18:19.000000000 +0100
+++ b/src/borg/testsuite/archiver.py.b	2019-01-30 21:18:48.973311799 +0100
@@ -279,7 +279,7 @@
         os.chdir(self._old_wd)
         # note: ignore_errors=True as workaround for issue #862
         shutil.rmtree(self.tmpdir, ignore_errors=True)
-        setup_logging()
+        #setup_logging()
 
     def cmd(self, *args, **kw):
         exit_code = kw.pop('exit_code', 0)
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes.

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/borgbackup/borg/builds/486040608 strange, 3.7 works on travis.

i also did not notice 3.7 breakage in local tests.

**Comment by ThomasWaldmann** [comment]
@bpereto ran you reproduce it locally also?

**Comment by ThomasWaldmann** [comment]
I did a local test with 3.7.0 and 3.7.2, no failures here.

**Comment by bpereto** [comment]
@ThomasWaldmann yes, if I run it locally in the fedora build environment I get the error also.

**Comment by tchellomello** [comment]
Hitting the same issue..

**Comment by ThomasWaldmann** [comment]
I need some way to reproduce this on debian or ubuntu, otherwise i can not do much about it.

**Comment by ThomasWaldmann** [comment]
Is this still happening?

**Comment by FelixSchwarz** [comment]
I did not see any unexpected test failures in Fedora for quite a while.

**Comment by ThomasWaldmann** [comment]
OK, I did not see that either, so I'll close it for now.
