### ISSUE TITLE
OSX: osxfuse pre-release 3.0.9

### ISSUE THREAD

**Issue by rmoriz** [borgbackup/borg#429]
Hi,

Using 0.28.2 single-binary (brew cask) I've problems using the latest osxfuse pre-release version 3.0.9
After some grepping in the borg repo found a reference to the pre-release osxfuse 3.0.5 in the Vagrantfile, this version seem to work.

Here are the steps (umount done in other window), I also tried with rebooting between installation, with no other outcome.

![steps](https://cloud.githubusercontent.com/assets/1527/11231491/44d61b2e-8da9-11e5-8b2d-b03b7ce1dbdd.png)

**Comment by ThomasWaldmann** [comment]
Hmm, looks like we can't do much about that. We use PyInstaller to create the binary and it usually bundles everything needed with it - but obviously not that osxfuse kernel extension.

I'll leave this ticket open as a reminder to update osxfuse on my build machine and to document which osxfuse version is needed.

**Comment by ThomasWaldmann** [comment]
done (added to release todo, upgraded osxfuse in vm).
