### ISSUE TITLE
extended globbing / wildcard behaviour

### ISSUE THREAD

**Issue by joolswills** [borgbackup/borg#43]
to continue from https://github.com/jborg/attic/issues/97

(To have * not match over directory boundaries, and add ** which does - which makes it far more logical)

Patch got into the glob2 library initially but was later reverted as other functions that used it expected the old behaviour.

https://github.com/miracle2k/python-glob2/pull/6

@ThomasWaldmann would you consider either of these options below - and if so which would you prefer?

A replacement function (note this is based on python library code so need to check licence compatibility) - this would be my preferred way.

```diff
diff --git a/attic/helpers.py b/attic/helpers.py
index 2ad2806..ad03e6d 100644
--- a/attic/helpers.py
+++ b/attic/helpers.py
@@ -9,7 +9,6 @@ import stat
 import sys
 import time
 from datetime import datetime, timezone, timedelta
-from fnmatch import translate
 from operator import attrgetter
 import fcntl

@@ -243,12 +242,12 @@ class ExcludePattern(IncludePattern):
     """
     def __init__(self, pattern):
         if pattern.endswith(os.path.sep):
-            self.pattern = pattern+'*'+os.path.sep
+            self.pattern = pattern+'**'+os.path.sep
         else:
-            self.pattern = pattern+os.path.sep+'*'
+            self.pattern = pattern+os.path.sep+'**'
         # fnmatch and re.match both cache compiled regular expressions.
         # Nevertheless, this is about 10 times faster.
-        self.regex = re.compile(translate(self.pattern))
+        self.regex = re.compile(self.translate())

     def match(self, path):
         return self.regex.match(path+os.path.sep) is not None
@@ -256,6 +255,43 @@ class ExcludePattern(IncludePattern):
     def __repr__(self):
         return '%s(%s)' % (type(self), self.pattern)

+    def translate(self):
+        pat=self.pattern
+        i, n = 0, len(pat)
+        res = ''
+        while i < n:
+            c = pat[i]
+            i = i+1
+            if c == '*':
+                if i < n and pat[i] == '*':
+                    res = res + '.*'
+                    i = i+1
+                else:
+                    res = res + '[^\\' + os.path.sep + ']*'
+            elif c == '?':
+                res = res + '.'
+            elif c == '[':
+                j = i
+                if j < n and pat[j] == '!':
+                    j = j+1
+                if j < n and pat[j] == ']':
+                    j = j+1
+                while j < n and pat[j] != ']':
+                    j = j+1
+                if j >= n:
+                    res = res + '\\['
+                else:
+                    stuff = pat[i:j].replace('\\','\\\\')
+                    i = j+1
+                    if stuff[0] == '!':
+                        stuff = '^' + stuff[1:]
+                    elif stuff[0] == '^':
+                        stuff = '\\' + stuff
+                    res = '%s[%s]' % (res, stuff)
+            else:
+                res = res + re.escape(c)
+        return res + '\Z(?ms)'
+

 def is_cachedir(path):
     """Determines whether the specified path is a cache directory (and
```

Modify the regular expression that comes out of fnmatch (Somewhat hacky)

```diff
diff --git a/attic/helpers.py b/attic/helpers.py
index 2ad2806..926a0b6 100644
--- a/attic/helpers.py
+++ b/attic/helpers.py
@@ -243,12 +243,19 @@ class ExcludePattern(IncludePattern):
     """
     def __init__(self, pattern):
         if pattern.endswith(os.path.sep):
-            self.pattern = pattern+'*'+os.path.sep
+            self.pattern = pattern+'**'+os.path.sep
         else:
-            self.pattern = pattern+os.path.sep+'*'
+            self.pattern = pattern+os.path.sep+'**'
         # fnmatch and re.match both cache compiled regular expressions.
         # Nevertheless, this is about 10 times faster.
-        self.regex = re.compile(translate(self.pattern))
+        pattern = translate(self.pattern)
+        # rework the regular expression so that it is the equivalent of doing
+        # ** -> .* and * -> [^\/]* so ** matches any sequence of characters,
+        # and * matches any except a path separator.
+        pattern = pattern.replace('.*.*','**')
+        pattern = pattern.replace('.*','[^\\'+os.path.sep+']*')
+        pattern = pattern.replace('**','.*')
+        self.regex = re.compile(pattern)

     def match(self, path):
         return self.regex.match(path+os.path.sep) is not None
```

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/19473255-extended-globbing-wildcard-behaviour)

**Comment by ThomasWaldmann** [comment]
As I said: I follow your reasons why you'ld want * and ** behave as you said. But if you'ld like to introduce own code for that instead of some (assumingly) well-tested library code, it needs to have pretty good test coverage and also documentation (if that already exists somewhere, a link might suffice).

So could you add tests (maybe starting from python glob's tests and just changing / extending them as needed)? BTW, I switched the testing framework of borg to py.test, so testing is less painful now. unittest-style tests still work, though.

**Comment by joolswills** [comment]
The first piece of code is well tested - I can make some test cases for it though if you need. It's a minor modification from the python 3 fnmatch code (See the patch I submitted for the other project - https://github.com/miracle2k/python-glob2/pull/6/files) -it's a very simple change - it was reverted due to other functions using this and expecting the old behaviour, but that wouldn't be a problem in the case of us just including the function
 
I'll get back to you regarding some tests.

Cheers.

**Comment by hansmi** [comment]
I'm trying to write an exclusion pattern for a couple of directories beneath all user's home directories, e.g. `~/.thumbnails` or `~/.cache`. The pattern must not match when a directory with the same name is located in a subdirectory, e.g. `~/img/.thumbnails`. Consider this directory structure:

```
home/
home/aaa
home/aaa/.thumbnails
home/user
home/user/img
home/user/img/.thumbnails
```

The pattern `home/*/.thumbnails` will also match `home/user/img/.thumbnails` which is not intended (caused by [fnmatch](https://docs.python.org/3/library/fnmatch.html) matching the slash with `*`). As of version 0.28.2 the only way I see is to use `find(1)` to build an exclusion list and to pass it to borg via `--exclude-from`.

Changing the pattern behaviour is not a good choice in my opinion as to not break compatibility. Other backup systems permit the user to specify exclusions using regular expressions. Considering that the matching is already done using regular expressions the core logic would not need significant changes. The above could be implemented as `--exclude-regex 'home/[^/]+/\.thumbnails'`.

**Comment by RonnyPfannschmidt** [comment]
I strongly recommend regex over having a own slightly modified fnmatch variant

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt why? regex is ok for coders, but normal users tend to struggle with getting regexes right.

**Comment by ThomasWaldmann** [comment]
btw, just as a side note:
i think the pattern matching needs to work consistently for include/exclude and also for create/extract.

**Comment by joolswills** [comment]
I still think the current matching should be changed so that * is non greedy (and introducing **). Having additional regexp matching as an option on top may be useful. I apologise for not submitting a pull request, I didn't get around to sorting out adding the testing side.

**Comment by hansmi** [comment]
@joolswills wrote:
> I still think the current matching should be changed so that * is non greedy (and introducing **).

Doing so would change the behaviour and break compatibility with existing backup scripts. Such a change would require either a new major version (e.g. 1.0) or at least a flag to control the behaviour. Considering that we're talking about backup software which people rely on to keep their data safe and complete the latter is preferrable (not everyone reads changelogs).

I agree with @ThomasWaldmann that regular expressions are harder to grasp than shell-style patterns.

@ThomasWaldmann wrote:
> i think the pattern matching needs to work consistently for include/exclude and also for create/extract.

With my current understanding of the code only exclusions can use patterns. Inclusions are always literal paths. This matches the behaviour of tar(1). Allowing them to be mixed easily leads to complications, i.e. whether order matters. rsync(1) supports very complex filtering setups and we could imitate it to some degree, but my question is, is that needed for a backup system which normally should backup everything unless it's explicitly excluded?

**Comment by joolswills** [comment]
it would change the behaviour yes, but I believe the current behaviour is not as people expect (different from how * is treated normally is a shell etc). So I am for the change. It would also bring it in line with how other software does it (eg rdiff-backup).

**Comment by ThomasWaldmann** [comment]
btw, 1.0 is not too far away, so we could break some stuff for the better.

**Comment by ThomasWaldmann** [comment]
see: https://github.com/borgbackup/borg/pull/584
