### ISSUE TITLE
migrate librelist mailing list archive to python.org

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#430]
the python.org postmaster offered that we could even give him archives of the librelist mailing list posts so they could be integrated into the new borgbackup@python.org mailing list archive.

librelist help documents that one can get them via rsync, but that does not work for me ("connection refused").

so we could either extract them via javascript or just let them be where they are.

**Comment by jungle-boogie** [comment]
I say just deprecate the old but but keep it accessible.

**Comment by anarcat** [comment]
could there be some context here as to why we are migrating off librelist?

**Comment by ThomasWaldmann** [comment]
because it didn't work. :(

there was a guy on the channel who could not subscribe. I tried with a fresh email address and could reproduce the issue. he even mailed help@librelist.com but did not get an answer.

as this was not the first time we had strange effects with it, I thought it was time to try something else.

**Comment by anarcat** [comment]
i agree. :) i just wanted that on record for future reference. it's crazy how we forget that kind of stuff.

i myself had trouble registering at first as well.  there were also problems with PGP/MIME mangling i reported to help@librelist.com, without response:

```
Antoine Beaupré <anarcat@debian.org> (August 18) (borgbackup lists replied sent)
Subject: mangled PGP/MIME messages?
To: help@librelist.com
Cc: borgbackup@librelist.com
Date: Tue, 18 Aug 2015 16:46:09 -0400

It looks like librelist mangles PGP/MIME messages so that PGP signatures
can't be checked on those messages.

Is that a known problem?

See: http://librelist.com/browser//borgbackup/2015/8/9/borgbackup-0-24-0-released/

A.

[ 4-line signature. Click/Enter to show. ]
 Antoine Beaupré <anarcat@debian.org> (August 19) (borgbackup lists sent)
 Subject: Re: mangled PGP/MIME messages?
 To: help@librelist.com
 Cc: borgbackup@librelist.com
 Date: Wed, 19 Aug 2015 09:27:56 -0400

 On 2015-08-18 16:46:09, Antoine Beaupré wrote:
 > It looks like librelist mangles PGP/MIME messages so that PGP signatures
 > can't be checked on those messages.
 >
 > Is that a known problem?
 >
 > See: http://librelist.com/browser//borgbackup/2015/8/9/borgbackup-0-24-0-released/

 For some reason, this email didn't get through. I did try to send a
 first email to the list to subscribe, got a reply and confirmed. Then i
 was told i was subscribed on the mailing list and *then* I sent the
 above email. It bounced back saying i wasn't subscribed!! I confirmed
 again, didn't get a reply, and then the second email I sent actually got
 through:

 http://librelist.com/browser//borgbackup/2015/8/18/registered-to-gmane/

 Really strange all this, makes me worried I am not really registered on
 the mailing list...

 Anyways, the original question above still stands: how does librelist
 deal with PGP/MIME (like this message)?

 A.
 [ 4-line signature. Click/Enter to show. ]
```

so yeah, things don't seem to be working very well on librelist... good thing we're now on more reliable software. it would be great to keep the archives though...

**Comment by anarcat** [comment]
i can also confirm the rsync daemon is down:

```
[991]anarcat@angela:test10$ rsync -azv librelist.com::borgbackup/2015/06/11/queue/ q
rsync: failed to connect to librelist.com (71.19.156.177): Connection refused (111)
rsync: failed to connect to librelist.com (2605:2700:0:5::4713:9cb1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
[992]anarcat@angela:test10$ rsync -azv librelist.com::borgbackup/2015/ .
rsync: failed to connect to librelist.com (71.19.156.177): Connection refused (111)
rsync: failed to connect to librelist.com (2605:2700:0:5::4713:9cb1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
```

however, it could be possible to extract the maildir archive from http://librelist.com/archives/borgbackup/

i could do that if i know what is the input format on the other side (mbox, iirc?).

**Comment by ThomasWaldmann** [comment]
I wrote 2 mails:
- to python.org postmaster about required format
- to help@librelist.com about rsync daemon being down (and the issues we encountered)

**Comment by ThomasWaldmann** [comment]
"mbox" is wanted format for the archive.

**Comment by anarcat** [comment]
i'm starting a mirror of the http version for now, just in case. i'll wait a while to see if librelist answers about rsync goes down and after timeout i'll try a conversion of some sort.

**Comment by ThomasWaldmann** [comment]
http://librelist.com/archives/borgbackup/2015/06/11/ <- there is json as well as direct queue access.

**Comment by anarcat** [comment]
yep, that's what i've sucking down.

```
$ wget --mirror -np http://librelist.com/archives/borgbackup/
[...]
$ du -sch librelist.com/
2,4M    librelist.com/
```

there are maildirs in there - next step is to extract those and convert them into mbox files.

@ThomasWaldmann it's one huge mbox we need, or one mbox per month or what?

**Comment by ThomasWaldmann** [comment]
A: "one huge mailbox"

**Comment by ThomasWaldmann** [comment]
current status: archive mirrored, converted to mbox format, submitted to python.org postmaster.

**Comment by ThomasWaldmann** [comment]
python 3 script used for conversion.

[md2mb.py.txt](https://github.com/borgbackup/borg/files/46613/md2mb.py.txt)

**Comment by ThomasWaldmann** [comment]
https://mail.python.org/pipermail/borgbackup/2015/thread.html

migration done! thanks to the kind help of python.org postmaster.

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Comment by jdchristensen** [comment]
1) I just checked the archives of the new list at
https://mail.python.org/pipermail/borgbackup/2015/thread.html
and it seems like there is only one message (a test) from after the conversion.  Is that correct?
2) The borg homepage still points people to the librelist mailing list.
3) Has gmane been updated to use the new mailing list?  I posted a couple of messages there and they haven't shown up yet.

**Comment by anarcat** [comment]
1. i see a bunch of messages there, including the test, but also the import from the older archive
2. the borg homepage will be updated alongside the next release. in the meantime, the "latest" docs should show the proper mailing list links
3. gmane should be updated! i'll ask around

**Comment by anarcat** [comment]
i asked lars from gmane, by email.

**Comment by jdchristensen** [comment]
Thanks!  About 1), I was just surprised that there was only one message from after the switch, since it has been more than two weeks.  Have there really been no messages sent to the new list besides the test message?

**Comment by anarcat** [comment]
that is my understanding so far yes.
