### ISSUE TITLE
When running check --verify-data ask for passphrase first

### ISSUE THREAD

**Issue by AshTex** [borgbackup/borg#4300]
I'm running `check --verify-data --save-space` on a ~100GB backup. I'd like to just run it and leave but I have to wait for the initial repository check to complete before I can put in my passphrase. It would be better if I could put in my passphrase at the beginning of the process and not have to wait an inordinate amount of time for the initial checks to complete.

**Comment by ThomasWaldmann** [comment]
yes, we already have a ticket for that.
