### ISSUE TITLE
Backup S3 bucket to local borg repository

### ISSUE THREAD

**Issue by pgtaboada** [borgbackup/borg#431]
Hi, 

I need to backup a S3 repo locally. What is the best approach?

**Comment by ThomasWaldmann** [comment]
borg supports 2 methods of accessing remote data:
- via ssh (requires ssh and borg installation on the remote host)
- via a locally mounted filesystem, including network fs and FUSE fs (does not require borg installation on the remote host).

So, check whether one of these methods can be used (I don't use S3, so I can't help you with that).

**Comment by RonnyPfannschmidt** [comment]
i think s3 would be fit as another key/value backend instead of the default one

**Comment by anarcat** [comment]
"from borg to S3" is #102, from what i understand, this is "from s3 to borg".

**Comment by ThomasWaldmann** [comment]
@anarcat thanks, confused that. @RonnyPfannschmidt please update or delete your answer.

**Comment by ThomasWaldmann** [comment]
This is some stuff a quick search gives:
- https://github.com/s3fs-fuse/s3fs-fuse
- https://github.com/danilop/yas3fs

Closing this as out of scope.

**Comment by xenithorb** [comment]
Sorry for resurrecting an old ticket, but I have a quick question:

Do you think `aws s3 sync` would suffice, to sync the resultant repo to S3? As far as I understand it works similarly to rsync (without the deltas I believe):

```
DESCRIPTION
       Syncs  directories  and S3 prefixes. Recursively copies new and updated
       files from the source directory to the destination. Only creates  fold-
       ers in the destination if they contain one or more files.
```

It also has a `--delete` option to effectively mirror

**Comment by enkore** [comment]
Should work
