### ISSUE TITLE
acl support for NetBSD

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#433]
borgbackup already has ACL support for Linux, FreeBSD and Mac OS X.

It seems like OpenBSD and FreeBSD have acl support, too:
https://github.com/grke/burp/blob/11cd1c9f03e4d19d221d00bcb39c831b23ce57ad/src/client/acl.c

So, is this a missing feature for borgbackup? Anybody using ACLs on OpenBSD or NetBSD?

This needs somebody familiar with these systems to help implementing and testing, so speak up if you want to help!

**Comment by anarcat** [comment]
i think this is basically filesystem-specific: we're going to have similar issues with NTFS, HFS (Mac) and so on. one would hope that the `acl` module we're using would handle all those use-cases, no?

**Comment by ThomasWaldmann** [comment]
yes, for windows/cygwin there is no acl support either yet.

**Comment by enkore** [comment]
Solaris and OpenIndiana are also absent. They seem to share the API (due to OpenIndiana's Solaris 10 heritage):

- http://docs.oracle.com/cd/E23824_01/html/821-1474/acl-5.html
- https://illumos.org/man/5/acl

Seems reasonably similar to the other ACL APIs.

**Comment by enkore** [comment]
OpenBSD has no ACL support.

**Comment by enkore** [comment]
NetBSD IMHO supports no ACLs at this time. It has the FreeBSD syscalls in the fbsd compat layer, but these are not implemented (ENOSYS).
