### ISSUE TITLE
1.1-maint: python3.4

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4343]
we support python 3.4 in borg 1.1.x.

but python 3.4 support is ending 2019-03 and also pip is dropping 3.4 support for pip > 19.1, pytest >= 5.0 is also dropping 3.4.

so, we'll likely have to add `pip <= 19.1, pytest < 5.0` to our requirements.
or check the vagrant VMs whether we can use python >= 3.5 on some where currently 3.4 is used.

**Comment by ThomasWaldmann** [comment]
VMs:
- netbsd64

**Comment by SystemOverlord** [comment]
Woldn't it be better for borg to also drop python 3.4 and putting the effort into more up to date versions?

**Comment by ThomasWaldmann** [comment]
master branch is currently on py35+ (it already was on py36+, but i reverted that to again to py35+ due to debian stable still having py35). most future development will happen there.

for 1.1-maint (and this ticket is only about 1.1-maint), it wouldn't be nice to remove 3.4 support as we have supported this for all 1.1.x releases yet. major changes in a patch release are a no-no.

so i guess i'll try pinning the test environment to tool versions that still work with 3.4.

**Comment by ThomasWaldmann** [comment]
fixed by #4472.
