### ISSUE TITLE
Invalid repo but changes are visible

### ISSUE THREAD

**Issue by gizmo15** [borgbackup/borg#4358]
Hi,

I use borg on Ubuntu 18.04. On the client and the server the version is 1.1.5.

My situation :
I have a client who make is backup on a remote server with ssh.

The CLI is use to make backup is :
```
borg create --compression auto,lzma,9 ${USER_BACKUP}@${TARGET_BACKUP}:${FOLDER_BACKUP}::{now} ${FINAL_BACKUP_NAME}`
```
The init was made 2 weeks ago with this command : 
```
borg init --encryption=keyfile-blake2 ${USER_BACKUP}@${TARGET_BACKUP}:${FOLDER_BACKUP}`
```
But this night, all my backups failed. The reason :
```
borg list ${USER_BACKUP}@${TARGET_BACKUP}:${FOLDER_BACKUP} --debug
using builtin fallback logging configuration
35 self tests completed in 0.25 seconds
SSH command line: ['ssh', '${USER_BACKUP}@${TARGET_BACKUP}', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.21 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/media/backup_storage/borg_backup/demo'
Remote: Resolved repository path to '/media/backup_storage/borg_backup/demo'
Remote: Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 248, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 374, in open
    self.repository.__enter__()  # clean exit handled by serve() method

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 184, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 388, in open
    raise self.InvalidRepository(path)

borg.repository.Repository.InvalidRepository: /media/backup_storage/borg_backup/demo is not a valid repository. Check repo config.

/media/backup_storage/borg_backup/demo is not a valid repository. Check repo config.
Borg server: Platform: Linux reverseproxy 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64
Borg server: Linux: Ubuntu 18.04 bionic
Borg server: Borg: 1.1.5  Python: CPython 3.6.7
Borg server: PID: 1370  CWD: /home/${USER_BACKUP}
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--debug']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux appEasylienceAlertDemo 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.7
PID: 3842  CWD: /home/${USER_BACKUP}
sys.argv: ['/usr/bin/borg', 'list', '${USER_BACKUP}@${TARGET_BACKUP}:/media/backup_storage/borg_backup/demo/', '--debug']
SSH_ORIGINAL_COMMAND: None
```

I don't understand why this night the config changed and are not correct...

When i executed borg list command, on the server i see an access is made because the date on the target folder change but the command failed.

If i delete the folder on the server and make an init, the backup works but i can't do that for a backup system.

Can you help me?

Thanks

**Comment by gizmo15** [comment]
If i try a check / repair : 
`borg check ${USER_BACKUP}@${TARGET_BACKUP}:/media/backup_storage/borg_backup/demo --debug --repository-only
using builtin fallback logging configuration
35 self tests completed in 0.40 seconds
SSH command line: ['ssh', '${USER_BACKUP}@${TARGET_BACKUP}', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.78 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/media/backup_storage/borg_backup/demo'
Remote: Resolved repository path to '/media/backup_storage/borg_backup/demo'
Remote: Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 248, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 374, in open
    self.repository.__enter__()  # clean exit handled by serve() method

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 184, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 388, in open
    raise self.InvalidRepository(path)

borg.repository.Repository.InvalidRepository: /media/backup_storage/borg_backup/demo is not a valid repository. Check repo config.

/media/backup_storage/borg_backup/demo is not a valid repository. Check repo config.
Borg server: Platform: Linux reverseproxy 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64
Borg server: Linux: Ubuntu 18.04 bionic
Borg server: Borg: 1.1.5  Python: CPython 3.6.7
Borg server: PID: 17947  CWD: /home/${USER_BACKUP}
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--debug']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux appEasylienceAlertDemo 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.7
PID: 22415  CWD: /home/${USER_BACKUP}
sys.argv: ['/usr/bin/borg', 'check', '${USER_BACKUP}@${TARGET_BACKUP}:/media/backup_storage/borg_backup/demo', '--debug', '--repository-only']
SSH_ORIGINAL_COMMAND: None`

or 

`borg check ${USER_BACKUP}@${TARGET_BACKUP}:/media/backup_storage/borg_backup/demo --debug --verify-data --repair
using builtin fallback logging configuration
35 self tests completed in 0.53 seconds
SSH command line: ['ssh', '${USER_BACKUP}@${TARGET_BACKUP}', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.41 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/media/backup_storage/borg_backup/demo'
Remote: Resolved repository path to '/media/backup_storage/borg_backup/demo'
Remote: Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 248, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 374, in open
    self.repository.__enter__()  # clean exit handled by serve() method

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 184, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 388, in open
    raise self.InvalidRepository(path)

borg.repository.Repository.InvalidRepository: /media/backup_storage/borg_backup/demo is not a valid repository. Check repo config.

/media/backup_storage/borg_backup/demo is not a valid repository. Check repo config.
Borg server: Platform: Linux reverseproxy 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64
Borg server: Linux: Ubuntu 18.04 bionic
Borg server: Borg: 1.1.5  Python: CPython 3.6.7
Borg server: PID: 18206  CWD: /home/${USER_BACKUP}
Borg server: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077', '--debug']
Borg server: SSH_ORIGINAL_COMMAND: None
Platform: Linux appEasylienceAlertDemo 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.7
PID: 22613  CWD: /home/${USER_BACKUP}
sys.argv: ['/usr/bin/borg', 'check', '${USER_BACKUP}@${TARGET_BACKUP}:/media/backup_storage/borg_backup/demo', '--debug', '--verify-data', '--repair']
SSH_ORIGINAL_COMMAND: None`

can i check something on the server side?

**Comment by ThomasWaldmann** [comment]
When it says "check repo config" it means the file `repo_directory/config`.

**Comment by gizmo15** [comment]
I haven't any config folder : 
`tree demo/
demo/
├── data
│   └── 0
│       ├── 23
│       ├── 25
│       ├── 27
│       ├── 29
│       ├── 31
│       ├── 32
│       └── 33
├── hints.33
├── index.33
├── integrity.33
└── nonce`

I don't know if it's relevant but : i have a script who use rsync to sync my backup folder who contain the borg folder. Can this impact the borg function?

Thanks!

**Comment by ThomasWaldmann** [comment]
Looks like you lost your `demo/config` file. Try to find out why.

Borg does quite a lot of effort to avoid losing or damaging the config file, so not sure why yours is gone and not even a `config.tmp` or something is left.

**Comment by gizmo15** [comment]
it's possible to recreate it without delete/recreate/init the folder?

the rsync can do this delete? if yes, do you have an advice/technical to sync this folder?

Thanks for your help!

**Comment by ThomasWaldmann** [comment]
As you used a `keyfile*` mode and assuming you did not tweak the config file somehow, you could create a new one (just run the same init command against a `demo2` folder and `cp demo2/config demo/config`.

But still: find out why you lost it, this is not normal.

About using rsync: there is a faq entry about that. rsync usually should not delete stuff from the source folder.

**Comment by ThomasWaldmann** [comment]
Hmm, one problem will be left after creating the new config: it will have a new repo ID, so borg likely won't find the encryption key. So you need to that in sync again by carefully editing either the key or the repo config.

**Comment by gizmo15** [comment]
okay, i will investigate on that disparition ^^

thanks again for the help ;)

**Comment by gizmo15** [comment]
it's on ext4.

thanks for the advice!

**Comment by ThomasWaldmann** [comment]
I just noticed this strange output:
```
Borg server: PID: 1370  CWD: /home/${USER_BACKUP}
```
The code generating this is:
```
    info.append('PID: %d  CWD: %s' % (os.getpid(), os.getcwd()))
```

So, your server OS really has that as cwd. This is broken, it should be `/home/username`.

**Comment by gizmo15** [comment]
i replace the name of the user ;)

**Comment by ThomasWaldmann** [comment]
You mean you edited the log output to anonymize it before posting it here?

**Comment by gizmo15** [comment]
Yes, i just change ${USER_BACKUP}@${TARGET_BACKUP} and ${USER_BACKUP}

**Comment by ThomasWaldmann** [comment]
any news?

**Comment by gizmo15** [comment]
Unfortunately, i haven't find anything :/ 

I suspect my secondary backup part but i can't reproduce in the time i have.

**Comment by gizmo15** [comment]
I have my answer : an old script who clean files older than 3 days ...
