### ISSUE TITLE
Feature Request: --list for delete command

### ISSUE THREAD

**Issue by demure** [borgbackup/borg#4359]
While cleaning up my repo to remove some misnamed archives (from a script snafu on my part) I had occasion to use the `delete` command. While using delete to remove some archives with a specific starting string, I found the command to be lacking a `--list` flag like the `prune` command has. I would suggest that it would be good UI for delete to have this too, so that Users can use the `--dry-run` flag and see what they will be matching.

The current STDOUT results of both `borg delete --dry-run -P "some_string"` (repo set by ENV VAR) and `borg delete -P "some_string"` is NULL currently.

**Comment by joey4** [comment]
If the issue is still available, I'll work on it.

**Comment by ThomasWaldmann** [comment]
@joey4 sure, go for it, make a PR. :)

**Comment by ThomasWaldmann** [comment]
@demure does `--info` (aka `-v`) already what you need?

Found this while reviewing #4382, see there for comments.

**Comment by ThomasWaldmann** [comment]
@joey4 can you do a backport to 1.1-maint also?

**Comment by joey4** [comment]
Sure, I did a PR.
