### ISSUE TITLE
borg list and borg extract are very slow, even for a single small file

### ISSUE THREAD

**Issue by russelldavis** [borgbackup/borg#4362]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue, unless it's expected to be this slow.

## System information. For client/server mode post info for both machines.
Client: macOS Mojave 10.14.3
Server: rsync.net

#### Your borg version (borg -V).
Client: 1.1.6
Server: 1.1.5

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg list ::2019-02-13T11:04:17 Users/russell/dev/project/.idea/vcs.xml
borg extract ::2019-02-13T11:04:17 Users/russell/dev/project/.idea/vcs.xml
```

#### Can you reproduce the problem? If so, describe how. If not, describe 
Yes, the commands above are consistently slow as described.

## Describe the problem you're observing.
The list command takes 130s to run. The extract command takes 280s to run. They're both dealing with a single file, specified by absolute path, whose contents are only a few hundred bytes. **Is it expected to be that slow?**

Here are stats from my latest backup:
```
                       Original size      Compressed size    Deduplicated size
This archive:                9.44 GB              6.65 GB             50.29 MB
All archives:              279.51 GB            156.11 GB             10.95 GB

                       Unique chunks         Total chunks
Chunk index:                  520298              5805751
```

Here are the CRUD benchmark results:
```
C-Z-BIG          45.59 MB/s (10 * 100.00 MB all-zero files: 21.93s)
R-Z-BIG           5.93 MB/s (10 * 100.00 MB all-zero files: 168.50s)
U-Z-BIG          83.37 MB/s (10 * 100.00 MB all-zero files: 11.99s)
D-Z-BIG         135.41 MB/s (10 * 100.00 MB all-zero files: 7.38s)
C-R-BIG           0.66 MB/s (10 * 100.00 MB random files: 1521.76s)
R-R-BIG           0.34 MB/s (10 * 100.00 MB random files: 2954.70s)
U-R-BIG          70.93 MB/s (10 * 100.00 MB random files: 14.10s)
D-R-BIG          43.95 MB/s (10 * 100.00 MB random files: 22.75s)
Remote: packet_write_wait: Connection to 69.43.165.8 port 22: Broken pipe
Connection closed by remote host
```

It got cut short because it was taking forever and eventually my laptop went to sleep, breaking the connection.

*Thanks for taking a look!*

**Comment by ThomasWaldmann** [comment]
Well, 0.34MB/s (R-R-BIG) isn't very fast. So that is one problem (your connection to rsync.net and/or their speed).

The other "problem" is that metadata access in an archive is linear, so the access time to access a single file is O(N), with N being the number of files in that archive.

borg has to read through the whole archive while searching for files matching what you specified on the commandline. Think "tar", just without the file contents being stored in the same file between the metadata. This is a design limitation of borg, not much we can do about that(*).

So, if you have many files in an archive and you extract a single small file, that's the worst case you get. So the good news is that if you extract more, it's much better.

What's bit curious here is that extract for a small file is taking much longer than list. Might be line speed or server speed fluctuation though.

(*) I did a quick try some time ago to add a search index to borg, but quickly noticed that the index is quite big and it costs a lot of time to have it updated, so I didn't continue on that route. An index could replicate metadata and thus save one from having to go through the archive sequentially.

Another approach would be to have a filesystem-like structure inside the repository (a hierarchy of directory objects), but that is nothing we have now or soon.

Closing as "works as designed" for the borg part.

Your internet connection's and rsync.net's latency/speed is nothing we (borg development) can influence.

**Comment by ThomasWaldmann** [comment]
borg is not a gui tool, so there is no browse. but we have the fuse fs, so you can browse with any file manager. you can't do much on the server side as all is encrypted.

**Comment by russelldavis** [comment]
> there is no browse. but we have the fuse fs, so you can browse with any file manager

Yeah, I meant browse in the broadest sense (via `borg list`, fuse fs, etc.). Mounting with fuse has the same problem, it's very slow with a remote server. Mounting the root path of one of my archives takes ~forever and causes Finder and my terminal to freeze. Mounting a the specific nested path I mentioned in this issue takes two minutes.

> you can't do much on the server side as all is encrypted.

Ah, right.

**Comment by carlosaguilarmelchor** [comment]
Hi, @ThomasWaldmann reopened an issue recently (to which I had just posted), so I am trying my luck again.

I think I have an approach that may help to make much quicker extracts. My setup is as follows:
  * two computers with a 44GB sync dir on which is my work-related stuff
  * when I work one day on a computer I start by pulling the archive with an extract and at the end of the day I push it with a create
The create push takes 10s, the extract pull takes 15 min.

Couldn't my computer on the morning start by doing a 10s fake push (create) to decide what are the chunks that change between the current archive and my computer and then do the reverse process much faster ? (identify where the sent chunks would be stored in the file index and retrieve the current chunks for these indices)

Best

**Comment by ThomasWaldmann** [comment]
@carlosaguilarmelchor it sounds like you need `extract` to operate like `update/sync` rather, which is currently not implemented - iirc there is another ticket about this and it doesn't really fit here in this ticket.

maybe `syncthing` or a similar tool would be a better match for your "keep in sync" use case.

**Comment by carlosaguilarmelchor** [comment]
Ok thx. `syncthing` does not support non trusted servers (e.g. remote encryption) which I need. There are tons of other options but for now borg is the fastest and most practical approach I know.

I have found another approach : `borg mount` and then `rsync` between the mounted dir and my computer dir. It takes around one second.

**Comment by infectormp** [comment]
@carlosaguilarmelchor synching support for file encryption (e.g. non-trusted servers) from version 1.16

**Comment by carlosaguilarmelchor** [comment]
Oh thx @infectormp. I will have another look at syncthing ! But I believe at then end I am going to stick to borg as:
  *  mounting+rsync gives a simple and fast way to sync
  * I love borg's simplicity, just like it was with a good old rsync on one sense or the other
  * I want manual pushes and pulls only, not automated things
  * Pushes are very fast with borg and I only pull once on the morning but I pull everytime I leave my computer or finish something important.

So even if you have not designed borg for this I think it is a wonderful "sync when you want" system :)

**Comment by martinvonwittich** [comment]
I have a similar issue - I have a rather large repository:

```
backupm1.iserv.eu /srv/iservbackup2/default/a5a2ec30-3b50-4a0f-8a34-02353a8631e7 # borg info .    
Repository ID: 52392b10f6cb75cd6567e88e1f1fadc73ac466452e6fe8522817f2be5a61a194
Location: /srv/iservbackup2/default/a5a2ec30-3b50-4a0f-8a34-02353a8631e7
Encrypted: No
Cache: /var/lib/iserv/remote-support/iserv-martin.von.wittich/.cache/borg/52392b10f6cb75cd6567e88e1f1fadc73ac466452e6fe8522817f2be5a61a194
Security dir: /var/lib/iserv/remote-support/iserv-martin.von.wittich/.config/borg/security/52392b10f6cb75cd6567e88e1f1fadc73ac466452e6fe8522817f2be5a61a194
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              113.51 TB             98.40 TB            909.04 GB

                       Unique chunks         Total chunks
Chunk index:                 2302157            233083560
```

Now I want to show the metadata of a single file in each archive. I haven't been able to figure out how to do this with `borg list` - I fiddled with `borg list -a '*' . usr/sbin/repodb`, but that doesn't do what I had hoped. Nonetheless, with a shell loop I can accomplish this easily (`head -n1` to limit it to a single archive for testing):

```
backupm1.iserv.eu /srv/iservbackup2/default/a5a2ec30-3b50-4a0f-8a34-02353a8631e7 # borg list --short . | head -n1 | while read archive; do borg list ".::$archive" usr/sbin/repodb; done
-rwxr-xr-x root   root       6407 Fri, 2023-06-16 17:04:33 usr/sbin/repodb
```

Unfortunately, while the `usr/sbin/repodb` line is printed very quickly (<1 sec), `borg` seems to continue to process the whole archive, which takes ~48 seconds. This increases the time to look up the file in all 44 archives from what I suppose could be ~44 seconds (44 archives * ~1 second) to ~35 minutes (44 archives * ~48 seconds).

Is there any way I can tell `borg` to stop processing the archive as soon as the specified PATH has been found?

**Comment by ThomasWaldmann** [comment]
@martinvonwittich guess I can't help you with the speed issue for same reasons as already discussed above, but the easiest way to show file metadata for some files along their history is to use borg mount's version view - you will get a view with folders instead of files and each folder contains all (different) revisions of the file that exist in all the archives loaded.

From borg mount docs:
```
# The "versions view" merges all archives in the repository
# and provides a versioned view on files.
$ borg mount -o versions /path/to/repo /tmp/mymountpoint
$ ls -l /tmp/mymountpoint/home/user/doc.txt/
total 24
-rw-rw-r-- 1 user group 12357 Aug 26 21:19 doc.cda00bc9.txt
-rw-rw-r-- 1 user group 12204 Aug 26 21:04 doc.fa760f28.txt
$ borg umount /tmp/mymountpoint
```

**Comment by martinvonwittich** [comment]
> @martinvonwittich guess I can't help you with the speed issue for same reasons as already discussed above, but the easiest way to show file metadata for some files along their history is to use borg mount's versions view 

Hm, I didn't know about `mount -o versions` yet, but unfortunately, it doesn't really work for me - when I tried it two weeks ago, it just hung for a long time, and then crashed with out of memory:

```
backupm1.iserv.eu /srv/iservbackup2/default/a5a2ec30-3b50-4a0f-8a34-02353a8631e7 # borg mount -o versions . /mnt/backup
zsh: killed     borg mount -o versions . /mnt/backup
```

```
[Di Dez  5 18:25:32 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/ssh.service,task=borg,pid=3030793,uid=0
[Di Dez  5 18:25:32 2023] Out of memory: Killed process 3030793 (borg) total-vm:19381712kB, anon-rss:15425876kB, file-rss:2396kB, shmem-rss:0kB, UID:0 pgtables:30296kB oom_score_adj:0
```

That's a notorious issue for us - accessing too many backups at the same time (e.g. when using mount) always leads to OOM, so we limit ourselves to accessing only a few backups at the same time.

> But borg mount also has options to only mount some archives and some files, which would save some time and memory.

Ah, yes, with `borg mount -a '2023-12*' -o versions . /mnt/backup` it does in fact work (though it still takes quite a long time and ~12 GB RAM^^). I'm keeping my fingers crossed that borg might get an index at some point to speed up operations like these - don't get me wrong, borg is *amazing*, but accessing backups is a constant pain for us.

**Comment by ThomasWaldmann** [comment]
You can reduce the memory needs (and also the runtime) by reducing the amount of archives and files in the `borgfs` filesystem borg creates in memory.

https://borgbackup.readthedocs.io/en/stable/usage/mount.html

Check:
- --prefix, --glob-archives, --first, --last - to reduce the number of archives mount will read
- `PATH` - to reduce the amount of files to the ones you are really interested in (check `borg list` to see how paths in the archive look like)

Maybe try this with a smaller repo / archive first to get used to it.

**Comment by martinvonwittich** [comment]
> You can reduce the memory needs (and also the runtime) by reducing the amount of archives and files in the borgfs filesystem borg creates in memory.

Thanks, I hadn't realized that. Just tested it with a repo and it works fine. It still takes a long time for the initial access per archive, but the reduced memory usage could greatly help when we have to iterate over a lot of archives.
