### ISSUE TITLE
How does borg handle being interrupted? (e.g. from a laptop going to sleep)

### ISSUE THREAD

**Issue by zhimsel** [borgbackup/borg#4366]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
N/A

#### Operating system (distribution) and version.
`<generic_linux>` client syncing to Debian 9 server (via SSH)

#### Hardware / network configuration, and filesystems used.
Various.

#### How much data is handled by borg?
Potentially hundreds of GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
N/A

----

I'm considering trying set up borg as a primary backup solution for a laptop. This laptop may be used intermittently and shut off or put to sleep at any time.

Let's say I shut down or sleep the laptop while a borg backup is in progress. What would happen? For sleeping, I imagine the process would resume on wake, but the connection would be dropped. How does it handle that interruption?

Thanks!

**Comment by ThomasWaldmann** [comment]
borg does checkpoints now and then (default: every 30mins, iirc).

so, if connection or something else breaks down, you lose 30mins max.

if you just start a new backup then, borg will notice that the repo has uncommitted objects and throw them away, going to last committed (valid) state and continuing from there.

just use a new archive name every time, like e.g. `laptop-home-{now}` (the last part will always be the current date/time).

**Comment by zhimsel** [comment]
Ok, cool. Assuming I can configure that 30-min checkpoint interval, that would keep the need for re-backing up to a minimum.

How does borg handle being interrupted on a process level? Any chances for backup corruption? Or is that mitigated by the checkpoint idea?

**Comment by ThomasWaldmann** [comment]
You can use a shorter `--checkpoint-interval`, but be aware that it gets less efficient the closer you get to 0 due to some constant commit overhead (e.g. for loading/saving index files).

Due to the transactional behaviour, you should never see corruption due to interruption. The post-commit stuff just gets removed next time borg uses the repo.

**Comment by zhimsel** [comment]
Good information. Thanks!
