### ISSUE TITLE
Bug/Request - Do not preserve global repo state across repo copies

### ISSUE THREAD

**Issue by DarrienG** [borgbackup/borg#4402]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes - possibly related to [this](https://github.com/borgbackup/borg/issues/3933)

## Is this a BUG / ISSUE report or a QUESTION?

Possible bug

## System information. For client/server mode post info for both machines.

1.1.8

#### Operating system (distribution) and version.

CentOS 7.X

#### Hardware / network configuration, and filesystems used.

8TB raided disk  / 10/40/100Gb / EXT4

#### How much data is handled by borg?

8GB to 300GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

See below. Two borg extracts in different locations from copies of repos.

## Describe the problem you're observing.

Borg remembers the state of the repo if a copy is made. State should be stored in the repo, not in some external data store (like git).

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

```
$ ls
some-borg-repo/
$ cp -r some-borg-repo/ copy-of-repo/
$ mkdir test-original test-copy
$ cd test-original
$ borg extract ../some-borg-repo::LATEST_BACKUP
Warning: The repository at location /mnt/some-borg-repo was previously at /mnt/some-other-location
Do you want to continue? [yN] y
# Extract repo...

$ cd test-copy
$ borg extract ../copy-of-repo::LATEST_BACKUP
Warning: The repository at location /mnt/copy-of-repo was previously at /mnt/test-original
Do you want to continue? [yN] y # <- **NOTE** and the above line
# Begin extracting huge repo...
```

#### Include any warning/errors/backtraces from the system logs
```
Warning: The repository at location /mnt/copy-of-repo was previously at /mnt/test-original
Do you want to continue? [yN] y # <- **NOTE** and the above line
```
It's important to note - that by extracting a repo. A copy of the same repo will be affected by side effects.

It's not a huge deal. Our services run in Kubernetes so we can get full isolation of services, but I feel like this should be contained in the repo, and not some global borg state.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location
