### ISSUE TITLE
1.2.0a2: Failing tests on OpenBSD current

### ISSUE THREAD

**Issue by bket** [borgbackup/borg#4403]
I started playing with 1.2.0a2 on OpenBSD current by running the testsuite. Result is that there are numerous failing tests some of which the root cause is easy to fix, others I do not understand. What I found so far:

- [x] `getxattr()` raises an `OSError` in [platform/base.py](https://github.com/borgbackup/borg/blob/master/src/borg/platform/base.py#L49) resulting in tests not even running
- [x] `acl_get()` should accept an `fd` in  [platform/base.py](https://github.com/borgbackup/borg/blob/master/src/borg/platform/base.py#L64)
- [x] `acl_set()` should accept an `fd` in  [platform/base.py](https://github.com/borgbackup/borg/blob/master/src/borg/platform/base.py#L72)
- [x] self test `test_*` (borg.testsuite.crypto.CryptoTestCase). Any idea how to address the issue below?
```
borgbackup version 1.2.0a2
self test test_AE (borg.testsuite.crypto.CryptoTestCase) FAILED:
Traceback (most recent call last):
  File "/tmp/ports/pobj/borgbackup-1.2.0a2/borgbackup-1.2.0a2/src/borg/testsuite/crypto.py", line 115, in test_AE
    hdr_mac_iv_cdata = cs.encrypt(data, header=header)
  File "src/borg/crypto/low_level.pyx", line 544, in borg.crypto.low_level._AEAD_BASE.encrypt
borg.crypto.low_level.CryptoError: EVP_EncryptInit_ex failed

self test test_AEAD (borg.testsuite.crypto.CryptoTestCase) FAILED:
Traceback (most recent call last):
  File "/tmp/ports/pobj/borgbackup-1.2.0a2/borgbackup-1.2.0a2/src/borg/testsuite/crypto.py", line 159, in test_AEAD
    hdr_mac_iv_cdata = cs.encrypt(data, header=header)
  File "src/borg/crypto/low_level.pyx", line 544, in borg.crypto.low_level._AEAD_BASE.encrypt
borg.crypto.low_level.CryptoError: EVP_EncryptInit_ex failed

self test failed
This is a bug either in Borg or in the package / distribution you use.
```
Latter issue has been fixed by #4407.

All tests run successfully on OpenBSD

**Comment by ThomasWaldmann** [comment]
about the openssl failure: your openssl version?

**Comment by ThomasWaldmann** [comment]
about the openssl related failure: i did not notice a malfunction on other platforms yet, but maybe it does not like the 3-step init (like needed for gcm/ocb) if it is not gcm/ocb. the examples in the openssl wiki show a 1-step init for these (giving cipher, iv, key at once).

**Comment by bket** [comment]
@ThomasWaldmann, issue is related to LibreSSL support.

Question: is there / will there be a specific requirement on a version of OpenSSL in the near future? If so, what are the requirements?

**Comment by ThomasWaldmann** [comment]
It currently works for both 1.0.x and 1.1.x. For some stuff, 1.1.x is required (because it is not present in 1.0), but the old stuff should also work with 1.0.x.

**Comment by ThomasWaldmann** [comment]
fixed, see PR links above.
