### ISSUE TITLE
`borg list` problem with filenames which contain 0x0A characters

### ISSUE THREAD

**Issue by Wikinaut** [borgbackup/borg#4421]
see https://github.com/borgbase/vorta/issues/217#issuecomment-469021231

using Vorta I found a problem for filenames which have ```0x0A``` characters in it.

When performing a list
```
borg list --info --log-json --format {size:8d}{TAB}{mtime}{TAB}{path}{NL} $REPO_PATH::$ARCHIVE_NAME > borg.lst
```

the output is broken - it is not on a single line - at these filenames.

The output for such files looks like (xxx, yyyy, tttt -> redacted content)

```
234973        Wed, 2015-11-04 17:03:22        home/xxx/yyy/tttttt tttttt ttttttttt
ttttttttttttttttt tttttttttttttttt
ttttt tttt ttttt
  tttt ttttt ttt.pdf
```

**Comment by ThomasWaldmann** [comment]
That a filename containing a linefeed causes a linefeed when output is not totally unexpected.

If you don't like that, don't have filenames with linefeeds.

**Comment by Wikinaut** [comment]
@ThomasWaldmann Such filenames break the borg list output, can have unexpected consequences for programs like Vorta which rely on the list output files (Du verstehst...). Currently I discuss this with @m3nu because Vorta shows issues with my backup. (Two issues have been already fixed by him.)

Please allow me to suggest 

#### Suggestion, not a workaround:
* during the ```borg create``` and ```borg create --dry-run``` command print a warning if filename/s contain/s problematic characters like ```0x0A```; and
* perhaps, list those files briefly. This could enable the user to rename such files.
