### ISSUE TITLE
early uncaught exceptions are reported by python as exit code 1 which borg defines as "warning".

### ISSUE THREAD

**Issue by textshell** [borgbackup/borg#4424]
If an exception happens before the try: blocks in archiver.py: main() python will terminate the process with exit code 1. But this exit code is defined as "warning" by borg, thus a hard error is misdetected as just an warning by software automating borg backups.

This mostly means all exceptions that are raised while importing code.

In our concrete case it was caused by a missing dependency on liblz4 (in our custom packaging), other kind of broken installations will have similar effects.

**Comment by ThomasWaldmann** [comment]
idea:
- import all critical stuff early in archiver.py
- try/except these imports
- in except block: output traceback, sys.exit(2)
