### ISSUE TITLE
optimize deduplication with netapp storage

### ISSUE THREAD

**Issue by tititototutu** [borgbackup/borg#4436]
Hi,

My config:
- server and client are debian 9
- borg version is 1.1.9
- netapp 9

Thanks a lot for your work and sorry for my poor english.

I am migrating my desktop and laptop backups from Backuppc to BorgBackup. The whole pool is 50Tera of datas. My server configuration is a vmware virtual machine debian and the backup storage is made with a nfs share on a netapp.

I do not want crypt and combine backups on a one repository. So all my backups have a personnal repos. but they are  sharing a lot of  same datas (approximately 10%).

My question is about optimize the deduplication:
- my borg config is the default one, chunker-params is a little confusioning to me.
- my netapp is also the the default one, so the chunks is 4096b

I can not modifiy the netapp configuration.

So do i need to change borg's chunks param to optimize my storage?

Regards.

**Comment by ThomasWaldmann** [comment]
"my netapp is also the the default one, so the chunks is 4096b" what do you mean precisely by that?

**Comment by tititototutu** [comment]
Hi,

thank you for your fast response!

i am a newbie with borg and not an expert on netapp system.., but if i understand it well, the netapp hardware subsystem deduplicate the storage with 4kb chunks (https://kb.netapp.com/app/answers/answer_view/a_id/1001012/~/faq---deduplication%2C-compression%2C-compaction-and-storage-efficiency-overview- )

it is not clear to me the role of CHUNK_MIN_EXP, CHUNK_MAX_EXP and HASH_WINDOW_SIZE between the max_segment_size.

My study case is:
 if i have 40 backups/repos (laptop + desktop made by a ssh connection to the depot) 
 with 500g-2To datas and +- 10% of same stuffs. 
 Every backups had a personnal arxiv and non uncrypted repository. 

What will be the best parameter of the "borg create" command to fit it well?

Regards,

**Comment by ThomasWaldmann** [comment]
there seems to be quite some overlap in functionality between what borg already does (dedup, compression) and what the storage (netapp) for your borg repo does.

if borg already deduped and compressed all the stuff, guess the attempt of the netapp to do this also/again will be futile.

**Comment by tititototutu** [comment]
ok thanks for your response but if i have multiple repos borg will not deduplicate the data between them, so the netapp dedup will still be useful.

have a nice day.

**Comment by ThomasWaldmann** [comment]
netapp dedup might not kick in between multiple borg repos due to different chunker seed (except for small files, which only have 1 chunk). same for encryption due to different encrypted result even for same data (due to different key, iv).

netapp compression will not be effective if borg already compressed the data (which might be still desirable due to the lower volume it has to transfer over the network).

**Comment by mikenye** [comment]
> "my netapp is also the the default one, so the chunks is 4096b" what do you mean precisely by that?

NetApp engineer here. He means the WAFL (NetApp's filesystem) block size is 4K.
