### ISSUE TITLE
RFE: Embed prune rules on the repository

### ISSUE THREAD

**Issue by robmv** [borgbackup/borg#4449]
Now that borg 1.2 will not do compaction by default, it would be great if prune rules could be added and stored on the repository, for example like:

```sh
borg set-auto-prune -d 7 -w 6 -m 6 -P $PREFIX $REPO
```

That way, when a server is configured to only allow appends, it could be configured with for example `--auto-prune`. As compaction is not run automatically, prunes should be fast enough to not extend the backup time too much.

Advantages of embedding  the prune rules on the repository:

1. The server has control of the prune rules and force that it should be run, the client has no control of it, if the server is configured for append only, the client will not be able to change these rules. On a network of multiple backed up clients this will help enforce prune rules, removing one more feature that require trusting the client.

2. If currently doing server side prune, there will be no need to have the encryption keys to do it, the server will only need to run compact at the preferred programmed interval, (release notes say compact doesn't need to decrypt data, only remove deleted segments). This will reduce the need for updating the cache every time because technically two clients were using the repository in this configuration.

**Comment by ThomasWaldmann** [comment]
Not doing compaction by default is not really related to pruning rules.

The usual assumption for borg is that the repo is encrypted and the repo server machine / repo storage is untrusted.

So, one can not execute prune on the server as that would need the key.

Also, as the server only has encrypted data, it does not know about archive names and should not know about archive name prefixes (as in pruning rules) either.

The server also has no means to check what the client is doing on a high level (e.g. what archives it is deleting / pruning or what prune rules it is executing), it only sees low-level object get/pul/del and commit.

What you could do:
- to-be-backed-up machines have ssh keys that enforce append-only on the repo server and also do pruning in append-only mode
- do compaction on the repo server, in non-append-only mode

That doesn't solve the fundamental problem of "i do not want to delete what i still might need" issue which is already covered in other tickets.

**Comment by robmv** [comment]
> So, one can not execute prune on the server as that would need the key.

Can't the server just provides the suggested prune rules to the client? or the client reading the prune rules. The server doesn't need to know the archive names, the prune rules could be stored by a client with the keys at hand. The idea is to centralize the rules storage.

Note: The server doesn't know the keys, but the sysadmins know them because they will need at some time restore files to another client. So these sysadmins could be able to change the rules using their borg client.

I just want to avoid these sysadmins needing to updates client scripts when prune rules need to change. Maybe the create command should have the --auto-prune command and then read the encrypted rules and use them.

>     * to-be-backed-up machines have ssh keys that enforce append-only on the repo server and also do pruning in append-only mode

Interesting that delete and prune works on append-only (the config name is a little confusing). The `transactions` file does not give much information about what was done by the client. I wonder if there is a way to query deleted archives when it is on append only mode (by the client itself).

**Comment by ThomasWaldmann** [comment]
Well, assuming the server provided the rules. Who says that the client follows them? It wouldn't help you against a malicious client.

About storing settings centrally: who except that client needs them? who would store it into the central storage? What about all the other settings / options a client uses?

I guess you currently have to either update the scripts on the clients or (if you rather want to have a config file, use borgmatic or something similar).

The transactions file can not give more info because the server does not really know what the client is doing on a high level.

No, the client can not query a deleted archive. It is logically deleted and this is all the client is seeing.
It only is recoverable if the repo is append-only and you remove the transactions starting from the one that did the delete in the repo storage, see the detailled description in the docs about that.

**Comment by robmv** [comment]
> Well, assuming the server provided the rules. Who says that the client follows them? It wouldn't help you against a malicious client.

There is no guarantee, that is why I talk about the client opting for it with some kind  of `--auto-prune` option. It is not about a malicious client, a hacked client could corrupt the repository without being easily noticed, I run the backup servers over LVM thin provisioning with snapshots to protect against miss configured or hacked clients. It is about simplifying the client configuration maintenance without the need of external tools.

> About storing settings centrally: who except that client needs them? who would store it into the central storage? What about all the other settings / options a client uses?

The sysadmins that configure the client could store them and update them later. If some client is using a borg server for backups, with advanced settings like append only mode, ssh keys, etc. It is highly probable it isn't done by a casual user, an advanced user is doing it, that maybe will not need of centralized configuration or is a network of clients managed by one or more sysdamins.

> About storing settings centrally: who except that client needs them? who would store it into the central storage? What about all the other settings / options a client uses?

Maybe centrally suggesting them to the client could help too, for example compression settings. I think that paths to backup could be suggested by the repository too. An option to allow the client to trust repository stored settings would be needed and be available only if the repository is encrypted (or allow the client to use it with no encryption but with a big warning requiring a YES confirmation prompt).

This RFE comes from some of the networks that use borg that I did the initial setup, some of them are medium sized, with a lot of them being mobile clients, so if borg could suggest this configuration to the clients, without the need to introduce things like ansible, puppet, chef or any other automation tool to the people that do the day to day support to that networks, it would be great.

**Comment by ThomasWaldmann** [comment]
I don't think this (currently?) fits well into the scope of what borg is doing.

borg gets its parameters via cmdline options (and some stuff via env var), there is not even a "config file".

there is also no central instance like a management server that controls borg clients (and making the borg repo into one neither feels right nor is in scope of development).

so this rather sounds like some tool on top of borg, not something to be built into borg.
