### ISSUE TITLE
Support for multiple target repositories in create command

### ISSUE THREAD

**Issue by xwst** [borgbackup/borg#4454]
According to the second FAQ entry
> Can I copy or synchronize my repo to another location?

the safest way of having a second backup is to invoke `borg create` with another repository. This means that I have to traverse the directories that are backed up twice (or even more for more backups).

I am not sure about the technical details of creating an archive, but allowing `borg create` to work with more than one repository at a time should speed up the process, at least as the file system is traversed only a single time. If I understand the `create` process correctly, this also means, that chunking and hashing needs to be performed only once.

If the repositories are supposed to be backups of one another, there might even be the chance to avoid reencrypting the data (given that the keys are identical). However I feel like this requires a lot of bookkeeping in order to avoid AES counter reuse.

**Comment by xwst** [comment]
> Yes, but traversal is rather quick.

Even if I have hundreds of thousands of files? I am just curious, because running e.g. hourly backups means that the files will probably not change too much between two backups but I still have to go over all files.

> No, it would need to chunk per repo as the chunker seed is different per repo (that means the chunks are cut differently).

If I have in mind to setup a backup repo, I'd probably be fine with identical chunker seeds, so I still can benefit from a single walk-through.

>And also no because of different AES keys, different MAC keys per repo.
> > ... given that the keys are identical

which is certainly achievable.
> But it would make the code more complex.

How much is "more"? I don't think that more complex code is necessarily bad. In particular if it increases overall performance.

**Comment by ThomasWaldmann** [comment]
recent python versions have `os.scandir` (plus borg doing 1 `os.stat` and a hashtable lookup per file), that's quite fast, just try it.

and i would suggest not doing premature and complex "optimizations", before someone(tm) has done profiling showing that it would be worth it.

maybe we can look at such stuff after the multithreading goal, which will require another code structure anyway (which i would suspect being better suited than now).

**Comment by xwst** [comment]
That sounds more than reasonable. If you keep the issue open I will come up with some profiling in the next months.

**Comment by ThomasWaldmann** [comment]
see also #2209.

**Comment by jdchristensen** [comment]
I doubt there's much speed to be gained here.  If you run a second backup shortly after the first, most information should be in the kernel's cache, so the scan will be fast.  Here's an example on 334 thousand files:

# time find . -ls | wc -l
333916

real	0m2.125s
user	0m1.070s
sys	0m1.132s

And I suspect that adding this would create a lot of additional complexity, reducing maintainability and increasing the risk of bugs.  All to save a couple of seconds...

**Comment by ThomasWaldmann** [comment]
Likely this feature (see top post) won't come, but borg 2 will have `borg transfer` (an efficient way to copy an archive from one repo to another).
