### ISSUE TITLE
turn off codecov emails

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#446]
i keep on seeing those messages in my pull requests:

https://github.com/borgbackup/borg/pull/445#issuecomment-159118010

it's pretty annoying because every time i think it's some human commenting on my code, whereas it's actually some odd bot i have no control over that is giving me information i don't really need. it's nice to see code coverage changes, but we already see those in the github checks at the bottom of the PR, and those do not generate emails.

if anything, i would be fine with getting an email when my PR makes tests fail. but telling me that "yay, 10 more lines covered by tests" is pretty useless to me.

**Comment by ThomasWaldmann** [comment]
I quickly checked, but I don't see a way to do that.

**Comment by RonnyPfannschmidt** [comment]
you could simply use a different service

**Comment by anarcat** [comment]
On 2015-11-24 11:18:30, Ronny Pfannschmidt wrote:
> you could simply use a different service

any suggestions?
-- 
We have no friends but the mountains.
                        - Kurdish saying

**Comment by ThomasWaldmann** [comment]
closing as there is no way to turn off.

**Comment by JasperCraeghs** [comment]
It is possible nowadays to disable (or tweak) the Codecov comments (but you can't disable the emails separately): https://docs.codecov.io/docs/pull-request-comments#section-disable-comment
