### ISSUE TITLE
Backup local fileserver with local sshfs mounted repo fails

### ISSUE THREAD

**Issue by holzwurminger** [borgbackup/borg#4462]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).
1.1.8

#### Operating system (distribution) and version.

4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.

VM on ESXI with ext4

#### How much data is handled by borg?

30 to 300 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

BACKUP_NAME="daten"
DESTINATION="/laufwerke/nasbind/$BACKUP_NAME/"
SOURCE_PATH="/laufwerke/$BACKUP_NAME/"

borg init --debug --info --encryption=keyfile $DESTINATION 2>> $LOG

borg create $RUN --debug --verbose --compression lzma $DESTINATION::$BACKUP_NAME $SOURCE_PATH 2>>$LOG

## Describe the problem you're observing.

The repo filesystem is mounted via sshfs on local system. borg inits the repo without error but when create(ing) the archive it wants ssh and a borg on the "other" side. where is the problem?

#### Include any warning/errors/backtraces from the system logs
````
Initializing repository at "/laufwerke/nasbind/daten"
Key in "/root/.config/borg/keys/laufwerke_nasbind_daten" created.
Keep this key safe. Your data will be inaccessible without it.
Synchronizing chunks cache...
Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
Done.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /laufwerke/nasbind/daten

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).

Vollsicherung wird ausgeführt
Im Modus --dry-run
Creating archive at "/laufwerke/nasbind/daten/::daten"
using builtin fallback logging configuration
35 self tests completed in 0.11 seconds
SSH command line: ['ssh', 'laufwerke', 'borg', 'serve', '--umask=077', '--debug']
Remote: ssh: Could not resolve hostname laufwerke: Temporary failure in name resolution^M
Connection closed by remote host. Is borg working on the server?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 132, in wrapper
    lock_wait=self.lock_wait, lock=lock, append_only=append_only, args=args)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 573, in __init__
    raise ConnectionClosedWithHint('Is borg working on the server?') from None
borg.remote.ConnectionClosedWithHint: Connection closed by remote host. Is borg working on the server?
````

**Comment by infectormp** [comment]
According to your logs:
> ssh: Could not resolve hostname laufwerke: Temporary failure in name resolution
> Connection closed by remote host

This is not a borg problem.

**Comment by holzwurminger** [comment]
Hallo, this is all? there is no ssh involved! there has no resolving to be done! because the repo is on the local system. ok, it is mounted via sshfs, but in your doku you make the same thing with the backup data. You say in the doku - run borg on the system with the backup data because traffic and time afford. I do. I have no chance to run borg on the other side (repo side) because it is only a store device and it musn´t be more. So I mount it secure via sshfs. I also tried via nfs, but it also not runs. Please help. Thank you

**Comment by Frzk** [comment]
Hi,

How are you mounting your SSHFS ?
What's in your $RUN var ?

I also think that you might be misunderstanding the repo / archive things. It should rather look something like this:

```bash
# Using the BORG_REPO environment var allows you to skip passing it on the command line
export BORG_REPO="/laufwerke/nasbind/my-repo"

# Then calling borg is just:
borg create --stats --exclude-caches --whatever-options-you-need ::{hostname}-{now} "${SOURCE_PATH}" 2>"${LOG}"

# {hostname} and {now} are placeholders borg understand and automatically sets for you.
# Here it means your backups will be stored in //laufwerke/nasbind/my-repo and they will be named after your hostname and current datetime.
#
# Available placeholders are (quoting the doc) : {now}, {utcnow}, {fqdn}, {hostname}, {user} and some others.
```

**Comment by ThomasWaldmann** [comment]
I am not sure this is a borg issue or a scripting issue.

Some hints:
- do not strip traceback output, esp. not the system info part
- do not use conflicting options, like giving `--debug --info` or `--debug --verbose` at once (--verbose -v --info all are the same and contradict --debug).
- reproduce your issue with a simpler script (or just on the commandline), no variables (this issue tracker is about borg, not about debugging your scripts)
- there is borg 1.1.9 (just saying, not necessarily related to your issue)
