### ISSUE TITLE
0.28.2 borg-linux* binaries miss FUSE support

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#447]
Related to #111 but somehow different case . Creating new issue cause I cant reopen the old one.

@ThomasWaldmann

on linux ubuntu 12.04 LTS (codename precise) the "borg mount" is impossible to be made to work.

error I get is :
Loading fuse support failed [ImportError: No module named 'llfuse']

I am using:
- the borg prebuilt 32 bit binary directly downloaded and installed in $PATH
- ubuntu 12.04
- I have succesfully run borg 0.28.2 ( latest release as of now ) and backed up OK

But I cant mount the backup to "see" its all there and/or test restore selectively only one folder/file.

What I tried:
- I tried installing distro packages for llfuse - for both python 2.7 and 3.2 - seems like although there ARE packages for both 2 and 3, they are the same package actually - by insepcting the real package version  in aptitude
- I tried seeing where the borg binary searches for llfuse when mounting - via ldd and "readelf -d borg" but llfuse is not listed there
- I tried setting  up python3 virtualenv and installing llfuse via its own venv pip, no luck - "borg mount" does not run from the venv NOR globally

So now I have to either find where to symlink the venv package in some /usr/local/python3.2/site-packages type of dir OR inspect the borg source to see how is llfuse loaded and why does it fail on my system.

PS. Can llfuse be bundled INTO the borg standalone binary executable as other libs are ?
PS2. Should I try compiling my own borg from the release/git master ? Will that fix it for me ?

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/28627351-0-28-2-borg-linux-binaries-miss-fuse-support)

**Comment by DrupaListo-com** [comment]
some debug info:
$ borg --version
borg 0.28.2

$ sha256sum /usr/local/bin/borg
74a98252177dc603ae7b8be26e3055d977fbca9beddaa50190f02c247dbb7ea5  /usr/local/bin/borg

**Comment by ThomasWaldmann** [comment]
The libraries (all python stuff and all compiled stuff except glibc) should be bundled into the binary already.
Could you try an older binary release?

**Comment by DrupaListo-com** [comment]
whoa, that answer was fast! @ThomasWaldmann what is your notification setup - emails ? Or sms ;)
I tried now with :
0.26.1
and 
0.27.0

To my surprise both of them worked!
I could borg init & borg create a test small repo with BOTH 0.26 and 0.27 by using direct paths to them like:

sudo borg-bins/0.26.1/borg-linux32 init /tmp/b
sudo borg-bins/0.26.1/borg-linux32 create /tmp/b::1 /tmp/data
sudo borg-bins/0.26.1/borg-linux32 create /tmp/b::2 /tmp/data

sudo borg-bins/0.26.1/borg-linux32 mount /tmp/b::1 /mnt/disk

THIS WORKS, files are there and can be listed / copied from /mnt/disk
ALSO works for 0.27.0

With 0.28.2 DOES NOT WORK.

So this gives me hope that its some regression introduced in 0.28 that can be easily traced thru git diffs to 1-2 .py files ...

Sth wrong with the compiler/bundler or the way we use it imho.

In what file is llfuse referenced ?
Searching thru the git source I find:

Vagrantfile:    # llfuse does not support netbsd
Vagrantfile:    pip install 'llfuse<0.41'  # 0.41 does not install due to UnicodeDecodeError
borg/fuse.py:import llfuse
borg/fuse.py:# Does this version of llfuse support ns precision?
borg/fuse.py:have_fuse_xtime_ns = hasattr(llfuse.EntryAttributes, 'st_mtime_ns')
borg/fuse.py:class FuseOperations(llfuse.Operations):


My understanding is that you use vagrant VM to build the borg binary. Maybe some vagrant related bug / unicode related prevents llfuse from installing and thus being packaged into the bin?

**Comment by ThomasWaldmann** [comment]
I can confirm / reproduce that the borg-linux32 has this issue on Ubuntu Precise 32bit.

**Comment by ThomasWaldmann** [comment]
Interesting: the centos6 binaries have libfuse.so.2 and llfuse.capi.cpython-35m...so in them, the normal ones do not.

**Comment by DrupaListo-com** [comment]
@ThomasWaldmann I have a #moneypledge: I am offering you 10eur to support your work on that bugfix - or anyone that is active here, sees that issue and solves it.
I see you use the bountysource platform.
I get the general idea of bountysource, but never sponsored anything there yet. 

What steps are necessary for me and you so I can fund you via bountysource?

Is there a more direct method than that ? Like direct paypal ?

PS. I tried finding PM messages in github - seems to me no such feature here.

**Comment by ThomasWaldmann** [comment]
See there: http://borgbackup.readthedocs.org/en/stable/support.html#bounties-and-fundraisers (and read the docs / faq of bountysource.com site).

**Comment by DrupaListo-com** [comment]
ok, here is the 11 usd bounty: https://www.bountysource.com/issues/28627351-0-28-2-borg-linux-binaries-miss-fuse-support

**Comment by ThomasWaldmann** [comment]
@DrupaListo-com thanks for the bounty. I linked it from the (top) ticket text and tagged it, as usual.

**Comment by ThomasWaldmann** [comment]
in 0.29.0 I made sure the fuse stuff works, sorry for the inconvenience.

**Comment by DrupaListo-com** [comment]
it works! Bounty released from my side. Use the funds wisely no matter how small ;) Buy urself a beer or two or just use it for other bounties on the project - up to you. Cheers.

**Comment by ThomasWaldmann** [comment]
Thanks! :-)

Just to tell how I usually deal with it:

If someone gives funds to borgbackup in general (not for a specific ticket), I use these funds to put bounties on tickets which I think are important, pressing, boring and/or difficult. Sometimes these bounties are rather meant as a start, not meant as the total amount that work should be awarded.

If a bounty is on a ticket and someone solves the ticket, the money goes to that person personally.

**Comment by DrupaListo-com** [comment]
mhm. Fair enough.
