### ISSUE TITLE
borg help should print <command> list in sorted order

### ISSUE THREAD

**Issue by fantasya-pbem** [borgbackup/borg#4471]
When calling "borg help", in section "required arguments: <command>" it lists the available commands unsorted. They should be sorted alphabetically.

@ThomasWaldmann: I'm not a Python programmer, but I looked into archiver.py and think I can fix that by myself. I consider this issue a good first one for me.

**Comment by ThomasWaldmann** [comment]
sounds good :) just make a pull request.
