### ISSUE TITLE
support request: borg cache dir: is it possible to move cache dir once it is created?

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#448]
1. is it possible to move cache dir once it is created?
2. Possible to use some --cache-dir-location type of switch? I saw its used in 'borg delete' - the "-c" switch and it works - deletes the cache in $HOME/.cache/borg

So should I symlink $HOME/.cache/borg to the real location I desire or it IS possible or easy to make it possible in future release to give the cache dir on 'borg init' or 'borg create'

Making sense ? @ThomasWaldmann This one should be relatively easy topic to think about - the location of the cache dir...

**Comment by ThomasWaldmann** [comment]
1. yes (including its content)
2. http://borgbackup.readthedocs.org/en/stable/usage.html#environment-variables or just use a symlink

**Comment by AnnoyingTechnology** [comment]
updated link https://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables
