### ISSUE TITLE
only do glibc checks on client?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4483]
Copying my reply to an issue posted on the mailing list to here:

```
     $ borg init --e none ./borgtest
     Remote: FATAL: this Python was compiled for a too old (g)libc and
     misses required functionality.
```
This is the code which triggers this exception / error message:

```
    required_funcs = {os.stat, os.utime, os.chown}
    if not os.supports_follow_symlinks.issuperset(required_funcs):
        raise PythonLibcTooOld
```

So, as you see, quite basic functionality like not following symlinks is not supported for all function where borg needs that.

So far for the bad news.

The good news are that these functions might be only required for using borg as a client, but not for "borg serve" (repo server part in client/server mode, if repo access is done via ssh:).

borg currently always does this check, but I guess it could be maybe omitted for the "borg serve" server part.

**Comment by ThomasWaldmann** [comment]
I had a look at the code and yes, as suspected, the `follow_symlinks = False` is only used clientside (for borg create and extract).

**Comment by ThomasWaldmann** [comment]
the code in #4487 needs practical testing. if you did, please post results here.

**Comment by ThomasWaldmann** [comment]
did someone test this?

**Comment by ThomasWaldmann** [comment]
With the code from the PR, this check is not executed for `borg serve`:
```
def check_python():
    if is_win32:
        required_funcs = {os.stat}
    else:
        required_funcs = {os.stat, os.utime, os.chown}
    if not os.supports_follow_symlinks.issuperset(required_funcs):
        raise PythonLibcTooOld
```

So what needs to be tested is:
- having a "borg server" system that is rather old, so running borg (master branch or 1.2.0a5) fails with an exception telling:
```
FATAL: this Python was compiled for a too old (g)libc and misses required functionality.
```
- then run master branch code with the PR code applies, the fatal error goes away, but one needs to check of borg is practically usable and runs well on such an old system (todo: run some backups, prune, repo check).

**Comment by shawnl** [comment]
There seems to be a problem with this change 

https://travis-ci.org/borgbackup/borg/jobs/525340780

**Comment by ThomasWaldmann** [comment]
@shawnl this is not caused by that change, it is a general problem that `test_extract_hardlinks` sometimes hangs - we have a ticket about it.

**Comment by FelixSchwarz** [comment]
> did someone test this?

Which version of glibc is too old? I would be interested in testing CentOS 7 if that would be helpful (glibc 2.17) but I want to be sure that my testing is meaningful. :-)

**Comment by ThomasWaldmann** [comment]
See there:
https://github.com/ContinuumIO/anaconda-issues/issues/1727#issuecomment-301661148

**Comment by ThomasWaldmann** [comment]
Looks like nobody tested this on a old enough ("stoneage") system.

I merged the change nevertheless because the change in borg is relatively simple and unlikely to directly cause harm. If an old system that now runs borg due to the disabled (serverside unnecessary) check fails to be good enough overall to support borg, it is at least not borg's fault, but the OS.

**Comment by mad-ady** [comment]
Alas, I have such a stone-age system in production :( An old RHEL4, where I wanted to use borg-backup to do periodic backups while the system is being overhauled to a newer OS...
The precompiled version doesn't work because glibc is too old (2.3.4). So, in an exercise of masochism I did the following: http://adrianpopagh.blogspot.com/2021/06/installing-borg-backup-on-old-fedora.html, with a few twists for RHEL4. Namely, using gcc-4.1.2 instead of gcc 3.4.6, and having to overwrite /usr/include/linux/fs.h with the one from FC8 so that borg would compile (otherwise it would say):
```
src/borg/platform/linux.c: In function '__pyx_pf_4borg_8platform_5linux_set_flags':
src/borg/platform/linux.c:2194: error: 'FS_IOC_SETFLAGS' undeclared (first use in this function)
src/borg/platform/linux.c:2194: error: (Each undeclared identifier is reported only once
src/borg/platform/linux.c:2194: error: for each function it appears in.)
src/borg/platform/linux.c: In function '__pyx_pf_4borg_8platform_5linux_2get_flags':
src/borg/platform/linux.c:2849: error: 'FS_IOC_GETFLAGS' undeclared (first use in this function)
src/borg/platform/linux.c: In function '__pyx_pymod_exec_linux':
src/borg/platform/linux.c:8095: error: 'FS_NODUMP_FL' undeclared (first use in this function)
src/borg/platform/linux.c:8113: error: 'FS_IMMUTABLE_FL' undeclared (first use in this function)
src/borg/platform/linux.c:8131: error: 'FS_APPEND_FL' undeclared (first use in this function)
src/borg/platform/linux.c:8149: error: 'FS_COMPR_FL' undeclared (first use in this function)
error: command '/opt/gcc-4.1.2/bin/gcc' failed with exit code 1
```

Anyway, borg is compiled and runs "just fine":
```
# LD_LIBRARY_PATH=/opt/openssl11/lib:$LD_LIBRARY_PATH /opt/python3/bin/borg -V
borg 1.1.16
```
But it complains when I try to init and talk to a remote repo:
```
# export BORG_REPO=ssh://old_server@backup-server:22/backup/old_server
# /usr/local/bin/borg init --encryption=none
FATAL: this Python was compiled for a too old (g)libc and misses required functionality.
```
I admit, that blinded by my insanity to trying to get the thing to work, I may be doing more damage than good. I've commented out the checks (in /opt/python3/lib/python3.9/site-packages/borgbackup-1.1.16-py3.9-linux-x86_64.egg/borg/helpers.py). Now init works. 

What could go wrong....?
I'll let you guys know!

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/c88a37eea430d7ec2e5da1ae503e43519ee90cb1/src/borg/helpers/checks.py#L12

as seen there, too old pythons / glibcs misses the option to not follow symlinks for these os calls.
