### ISSUE TITLE
3 ideas: borg razor ( = "borg diff" between archives + "borg delete-dir-from-repo" )

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#449]
The idea is simple and taken from real life:
Lets assume the following typical scenario:
- I take several backups of my /home or "/"
- from point ZERO I have taken the time to exclude some non-necessary folders like temp ones and lets say my /home/tmp folder which is my custom tmp folder ...

- BUT I've missed some other folders that I DONT want to backup ( most people miss even the obvious /home/tmp from last step )

SO... I want to retro-actively delete those folders from my backups - here comes :
borg delete-dir-from-repo - takes a dir path as arg1

Another idea is to make borg diff - comand that oitputs diffs between borg archives - helps u find in the diffs those dirs/files that have changed between last 2 archives and you can spot in the diffs that FOLDER1 is actually some useless for backup dir that u want DELETED from backups...

So my vision is that borg razor will use borg diff  + borg delete-dir-from-repo in sth like a wizard workflow on the cmdline that will allow the user to FIND + DELETE retro-actively those dirs that we backup by mistake...

Thoughts ? Maybe a separate tool in a separate github repo to not bloat borg?

PS. The proposed diff and delete retroactively tools can be done in a very slow and hdd space consuming way by restoring the full archives A and B on disk and doing diff on them... Or better eyt - by fuse mounting and diffing... So the diff can be done with borg mount + normal diff...

But the retroactive delete will need maybe restore=extract for real + delete folder from archive A + new backup=borg create ... which is painful...

Do we have read-write fuse mounts in borg?

Sorry for the long comment.

**Comment by RonnyPfannschmidt** [comment]
read-write mounts are unsustainable hard to get right,
so i doubt anyone wants to implement them just for fun 

its more at the level of a maters thesis or more

retrospective delete can also be done without  wasting much hd space, because its just creating a archive without the files, deleting the archive with files, then renaming

i strongly suspect that at most a megabyte of storage memory is needed in the backend, plus the archive indexes (which may be larger)

however the vacuum afterwards will be time-consuming

**Comment by DrupaListo-com** [comment]
1. "its just creating a archive without the files, deleting the archive with files, then renaming" - I saw a possibility to lie about archive's date ( to rewrite history ) via an cmdline option in the 'borg create" help.

2. "the vacuum afterwards will be time-consuming" - for me as a user saving several GB hdd space forever is worth the cpu time wasted.

**Comment by ThomasWaldmann** [comment]
The above seems duplicate to older tickets. Also, tickets should not cover multiple functions.

**Comment by DrupaListo-com** [comment]
oops. I dont normally do that. I assumed my use case is unique/rare, while in fact its quite the OPPOSITE I see:
#70 - Thoughts on "delete" for files/directories?

Quote:
"Definitely the number one missing feature for me as well."

This seems like sth I might create and fund a bounty for.

@ThomasWaldmann close this younger issue - I will migrate valuable ideas from it if any to the older #70
