### ISSUE TITLE
Can't init a repository as non root

### ISSUE THREAD

**Issue by Mace68** [borgbackup/borg#4491]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Possible issue

## System information. For client/server mode post info for both machines.

Operating System: KDE neon 5.15
KDE Plasma Version: 5.15.3
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.0
Kernel Version: 4.18.0-17-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-2600K CPU @ 3.40GHz
Memory: 31.4 GiB of RAM

#### Your borg version (borg -V).

borg 1.1.5

#### Operating system (distribution) and version.

KDE Neon 5.15

#### Hardware / network configuration, and filesystems used.

Wired 1000mbit, ext4

#### How much data is handled by borg?

single system

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg init --encryption=authenticated /media/backup/Linux`

## Describe the problem you're observing.

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 137, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 182, in __enter__
    self.create(self.path)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 269, in create
    self.save_config(path, config)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 290, in save_config
    config.write(fd)
  File "/usr/lib/python3/dist-packages/borg/platform/base.py", line 176, in __exit__
    os.replace(self.tmppath, self.path)
PermissionError: [Errno 13] Permission denied: '/media/backup/Linux/config.tmp' -> '/media/backup/Linux/config'

Platform: Linux 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64
Linux: neon 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.7
PID: 9406  CWD: /home/myuser
sys.argv: ['/usr/bin/borg', 'init', '--encryption=authenticated', '/media/backup/Linux']
SSH_ORIGINAL_COMMAND: None
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting 

retried with sudo and was successful, but want to be able to have a non-root repo. the repo directory is writable by myuser, the config.tmp file is readable/writable by myuser, and some files are written successfully to the repo dir, so i can't figure out why I'm getting the above error. These are the current file and directory permissions:

```
myuser@mymachine:~$ ls -l /media/backup/
total 29672204
drwxrwxr-x 3 myuser myuser        4096 Apr  3 19:47  Linux

myuser@mymachine:~$ ls -l /media/backup/Linux/
total 12
-rw------- 1 myuser myuser  209 Apr  3 19:47 config.tmp
drwxrwxr-x 2 myuser myuser 4096 Apr  3 19:47 data
-rwxrwxr-x 1 myuser myuser   73 Apr  3 19:47 README
```

**Comment by ThomasWaldmann** [comment]
This is not a bug, but likely a permission issue you caused by using same repo as different users (root and unprivileged user). Just always use same user to avoid this, see also the FAQ about how to do that.

To fix the permissions you need:
```
chown -R myuser.myuser /media/backup/Linux
```
And after that, always use the repo as `myuser`

**Comment by ThomasWaldmann** [comment]
btw, if you like you could get a more recent borg 1.1.x from the ppa (directly from same package maintainer).
