### ISSUE TITLE
Can't figure out how to setup exclude patterns

### ISSUE THREAD

**Issue by nspiller** [borgbackup/borg#4492]
Hi,

I have a question regarding the exclude patterns:

I'm using `borg` to backup my home directory to an external hard drive. My home contains a directory owned by root ( permissions: `drwx------` ) and I want to exclude that from the backup.

So I wanted to achieve this by using `--exclude`:

```
borg create                         \
    --verbose                       \
    --filter AME                    \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --exclude '/home/*/.cache/*'    \
    --exclude '/var/cache/*'        \
    --exclude '/var/tmp/*'          \
    --exclude '/home/myself/tmp/*' \
    --exclude '/home/myself/.dbus/' \
                                    \
    ::'{hostname}-{now}'            \
    /home/myself                           \
```

However, during the run I get
```
/home/myself/.dbus: scandir: [Errno 13] Permission denied: '/home/myself/.dbus'
```

I tried both `/home/myself/.dbus/` and `/home/myself/.dbus/*`.

I can't see why that should not be working. It's still doing the backup, but I would prefer an exit status of 0 :)

Borg is running in version  1.1.5 on Ubuntu 18.04

Thank you for your help :)

**Comment by mikenye** [comment]
Have you tried without the trailing slash? eg:
Change `--exclude '/home/myself/.dbus/'` to `--exclude '/home/myself/.dbus'` ?

**Comment by nspiller** [comment]
Hey mikenye,

no, apparently I hadn't tried that....
Works fine now! Thank you a lot :)
