### ISSUE TITLE
borg create --progress outputs CR instead of LF for new lines

### ISSUE THREAD

**Issue by paolobenve** [borgbackup/borg#4494]
When `borg create` is issued, summary lines are terminated with `LF`.

On the contrary, the extra lines produced when `borg create --progress` is issued, are terminated with `CR`.

I think the same terminator should be used.

A screenshot in geany with line terminators visibles:

![borg LF CR](https://user-images.githubusercontent.com/1417508/55548069-fa103d80-56d2-11e9-9dd0-8a6b792ee1b9.png)

The first half come from the `--progress` option, the second half is the create final summary.

The `--progress` option should use `LF` too.

**Comment by ThomasWaldmann** [comment]
This is on purpose (and intended for on-screen output, not logfile or `| less`).

Lines only ending with CR will reuse the same line and the next one will be printed over the previous one.

Lines ending with LF are normal screen output, new lines being used, scrolling...

**Comment by paolobenve** [comment]
ok, I understand, but log files are unreadable...

Trying to distinguish between interactive and batch execution...?

**Comment by ThomasWaldmann** [comment]
just do not use --progress if you write to a log file and not to screen.
