### ISSUE TITLE
Allow use of {hostname} keyword in --glob-archives

### ISSUE THREAD

**Issue by fbicknel** [borgbackup/borg#4495]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

(I would call it feature request, but that's not in my choices)

## System information. For client/server mode post info for both machines.
Ubuntu 18.04 4.15.0-46-generic #49-Ubuntu
#### Your borg version (borg -V).
borg 1.1.9

#### Operating system (distribution) and version.
um. Wasn't that "System information". If not... what was that?
#### Hardware / network configuration, and filesystems used.
AMD processor, local, single-machine backup, ZFS on the host, the target device is JFS.
#### How much data is handled by borg?
I *think* this is what you want?
```
bick-ubtu3 ~$ sudo -E borg info 
Repository ID: 50f08d75819b77b854c41d4f4e124806fc13835c0692a0a354bfdc44fde44a28
Location: /mnt/backup/borgbackup
Encrypted: Yes (repokey BLAKE2b)
Cache: /root/.cache/50f08d75819b77b854c41d4f4e124806fc13835c0692a0a354bfdc44fde44a28
Security dir: /root/.config/borg/security/50f08d75819b77b854c41d4f4e124806fc13835c0692a0a354bfdc44fde44a28
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:                3.24 TB              2.86 TB            391.18 GB

                       Unique chunks         Total chunks
Chunk index:                  371591              2704249
```
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
No problem here. Just a wish.

## Describe the problem you're observing.
So if you use `--prefix` with `borg prune`, you get access to some nice keywords, especially `{hostname}`. It would be nice to have those available for the `--glob-archives` option, as well.
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Again... not a problem.
#### Include any warning/errors/backtraces from the system logs
I'm feeling redundant.

**Comment by ThomasWaldmann** [comment]
Yup, good idea.
