### ISSUE TITLE
borg create does not handle space in the path

### ISSUE THREAD

**Issue by yavuzaydin** [borgbackup/borg#4504]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).

borg 1.1.9

#### Operating system (distribution) and version.

Cygwin 3.0.6(0.338/5/3)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

export BORG_PASSPHRASE='<PASSPHRASE>'
REPOSITORY='<borgbase REPO URL>'
DIRECTORIES='/d/New\ folder /d/Newfolder'

date=`date +%Y%m%d-%H%M`
borg create --error --compression auto,zlib,6 $REPOSITORY::$date $DIRECTORIES

I also tried with:
DIRECTORIES='/d/New\\ folder /d/Newfolder'
DIRECTORIES='/d/New\\\ folder /d/Newfolder'
DIRECTORIES="/d/'New folder' /d/Newfolder"
DIRECTORIES="'/d/New folder' /d/Newfolder"
DIRECTORIES="'/d/New\ folder /d/Newfolder'"
DIRECTORIES='"/d/New\ folder /d/Newfolder"'

And a couple more I'm forgetting.

## Describe the problem you're observing.

The backup doesn't contain /d/New\ folder, only /d/Newfolder.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, multiple servers have same issues.

**Comment by yavuzaydin** [comment]
Also tried with:
```
borg create --error --compression auto,zlib,6 xxxxxxxx@xxxxxxxx.repo.borgbase.com:repo::20191104-1413 /d/New\ folder/ /d/Newfolder/
```

Same result.

**Comment by DomoSokrat** [comment]
Quoting in bash can be fun.

Try
```
DIRECTORIES=("/d/New folder" /d/Newfolder) # creates an array
borg create … "${DIRECTORIES[@]}" # expand the array, quoting each element
```

The relevant information *can* be found in the bash man page, but it's not really easy to piece together, if you ask me.

**Comment by yavuzaydin** [comment]
Thank you very much, this works.
