### ISSUE TITLE
Encryption overhead and performance

### ISSUE THREAD

**Issue by eike-f** [borgbackup/borg#4509]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, sorry if I missed it

## Is this a BUG / ISSUE report or a QUESTION?

Question

Hello there! Thanks for maintaining this great piece of software!

To topic:

I'm syncing my repos to a cloud storage via rclone. To dodge the key reuse issue of stream ciphers I'm using the encryption provided by rclone.

My question is this: Is the encryption in borg in optimized in a way that makes it plausible that the borg encryption yields performance gains compared to encryption provided by an external program?
I'm just looking for a hunch, of course actual performance would have to be measured, I just don't have the time right now, but will get back to this depending on the answer here.
Also: Is there any other reason to not use external encryption?

**Comment by ThomasWaldmann** [comment]
I don't know how (fast/well/in detail) rclone is doing encryption (and authentication?).

borg uses openssl-based (and on many cpus hw-accelerated) AES encryption plus authentication using either hmac-sha256 or blake2b.

also not sure what "key reuse issue" you mean and what that has to do with using rclone.

are you using multiple borg clients to write to a single repo? there we have a (documented) counter reuse issue with malicious repos.

**Comment by eike-f** [comment]
Hm, from your answer I gather that I should not expect high performance gains by using borg's encryption itself. I'll try it this way and maybe make some measurements.

As to your other comments:
rclone uses [secretbox](https://godoc.org/golang.org/x/crypto/nacl/secretbox), which, as far as I can tell from the docs uses encrypt-then-mac.

> also not sure what "key reuse issue" you mean and what that has to do with using rclone.
I mean what you call "counter reuse issue". By using rclone encryption I mean to prevent an attacker from getting possibly two different repos encrypted with the same key.

> are you using multiple borg clients to write to a single repo? there we have a (documented) counter reuse issue with malicious repos.

No, I have different repos with different keys for every client.

**Comment by ThomasWaldmann** [comment]
secretbox seems to use good and fast encryption algos, but none of that is hw accelerated AFAIK.

if you use 1 client per repo and you init each repo just with `borg init`, you have 1 random key per repo and the counter state is remembered on repo side AND on client side, so that's safe.

**Comment by eike-f** [comment]
> if you use 1 client per repo and you init each repo just with `borg init`, you have 1 random key per repo and the counter state is remembered on repo side AND on client side, so that's safe.

Hm, I don't understand this: The docs say that syncing my repo is dangerous because of counter reuse, if I ever have different archives in the the local and remote versions.
I don't plan to treat them differently (apart from having changed the repo id so that borg knows they are different when I download the synced repo) but wanted to protect against it anyways.

**Comment by ThomasWaldmann** [comment]
I don't think the docs say that, maybe you misunderstood?

Otherwise please point me to the place in the docs (give a URL).

**Comment by eike-f** [comment]
I'm interpreting [this](https://borgbackup.readthedocs.io/en/stable/faq.html) (second question: Can I copy or synchronize my repo to another location?) in like it can result in counter reuse to sync a repo if I ever need to use the synced version, specifically:

>   - Encryption security issues if you would update repo and copy-of-repo independently, due to AES counter reuse.

> There is also a similar encryption security issue for the disaster case: If you lose repo and the borg client-side config/cache and you restore the repo from an older copy-of-repo, you also run into AES counter reuse.

**Comment by ThomasWaldmann** [comment]
If you start with identical original "A" and synced repo "B", stop updating A and continue using B as the borg target, you don't have a problem.

If you start from a B which is older than A and then try to write to B, I guess borg would warn you.
Restoring has no counter reuse issue, but continuing to use B to create archives in it has.

**Comment by eike-f** [comment]
My original question was summarily answered, so I close this issue, thank you!

Just so I understand, the problem is this:

Say I use local repo A and sync it to remote B, so I have a remote copy, incase my computer gets lost/broken/...
At some point in time I have archive 15 in A, which is not yet synced to B (B is still at archive 14) and then my computer is stolen.
Then I download B to my new computer to restore from backup and use it as a new local repo, creating archive 15' and sync it back to the remote. For the sake of argument lets say, archives 15 and 15' have the exact same on-disk size.
Then archive 15 and 15' are encrypted with the exact same key stream and

an attacker that has my stolen computer (and hence archive 15) and can access my remote repo has then access to (plaintext archive 15) XOR (archive 15').

Is this the only problem or is there even an attack, if my computer burned down and therefore I'm sure, noone has access to archive 15?

**Comment by ThomasWaldmann** [comment]
Yeah, the xor-scenario with same keys, same iv sequence and different data would be an issue.

If noone has access to 15, i guess there is no problem.
