### ISSUE TITLE
Compression can yield bigger size - should rather use none

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#4516]
This was already discussed in the past (#385 and elsewhere), but was not implemented.

When a file is already compressed, compressing it again may increase its size. For example using the default borg compressor, and standard (already compressed on my system) debian manpages:

```
mkdir /tmp/test
cd /usr/share/man/man1
cp *gz /tmp/test
cd /tmp/test
lz4 -v -m * > output.txt 2>&1
```

Have a look at the output.txt file:

```
*** LZ4 command line interface 64-bits v1.8.3, by Yann Collet ***
Compressed 1721 bytes into 1740 bytes ==> 101.10%                              
Compressed 563 bytes into 582 bytes ==> 103.37%                                
Compressed 592 bytes into 611 bytes ==> 103.21%                                
Compressed 5411 bytes into 5430 bytes ==> 100.35%                              
Compressed 2867 bytes into 2886 bytes ==> 100.66%                              
Compressed 2363 bytes into 2382 bytes ==> 100.80%                              
Compressed 2678 bytes into 2697 bytes ==> 100.71%                              
Compressed 3847 bytes into 3866 bytes ==> 100.49%                              
Compressed 1208 bytes into 1227 bytes ==> 101.57%                              
Compressed 577 bytes into 596 bytes ==> 103.29%
Compressed 1033 bytes into 1052 bytes ==> 101.84%
Compressed 7141 bytes into 7160 bytes ==> 100.27%
Compressed 154 bytes into 173 bytes ==> 112.34%
...
```
Most files are bigger then their original (actually by few bytes, but increasing to some KB whith bigger files). Actually they are all bigger than the original:
```
grep "1..\...%" output.txt|wc
grep -v "1..\...%" output.txt | grep % | wc
```
The last 2 commands give 2038 files with >= 100.02% size and 0 smaller than input files.

So it would be nice to have borg reverting to none compression when the compressed version is not smaller than the original. I know there is already auto compression, but while auto is mostly intended to avoid compressing with a slower algo this would still have 2 advantages even when not using auto:
- smaller repo (usually by a tiny fraction)
- faster file access (extract or mount) - this one is the most meaningful advantage!

**Comment by ThomasWaldmann** [comment]
Fixed by #4683.
