### ISSUE TITLE
[Question] create / prune / check parallel execution

### ISSUE THREAD

**Issue by jdorel** [borgbackup/borg#4517]
Is there any risks to running `borg create`, `borg prune` and/or `borg check` in parallel on the same repository ?

Would that ignore or consider the archive being currently created ?

Thanks

**Comment by ThomasWaldmann** [comment]
The repo is locked while borg does an operation in it.

The 2nd borg client trying to access it would wait for the lock wait time (default: a few secs) and then give up. You can use a longer lock wait time to let it wait longer, see `borg help` or the docs.
