### ISSUE TITLE
Feature request - pull remote borg repository with safe mode

### ISSUE THREAD

**Issue by alpha-and-omega** [borgbackup/borg#4519]
This is a feature request.

Why?
Assumptions:
1) Borgbackup creates backups of some local files to the local host repository. This is nice because one can use quick restore from local files and I use it everywhere.
2) But these backups are not safe and should be preserved at safe place and there are 3 options:
1.  push borg repository files to remote host (ssh, cloud storage, etc) - this is not safe, bacause compromised host can do anything to files
2.  pull remote borg repository files from the host to safe place using rsync - this is not safe too, because compromised repository files will overwrite the safe copy
3.  pull remote borg repository files using rdiff-backup or rsnapshot - this is safe! but requires additional utility and skill to setup

So, I would like to see an option to replace rsnapshot step with borgbackup to pull remote repository files to local repository with:
- integrity check of remote repository and if everything looks good:
- pull repository with already supported Append-only mode

**Comment by ThomasWaldmann** [comment]
Sorry, I'm confused after reading this. Can you just open a new ticket and just clearly describe what you actually want to do and leave away all references to what you don't want to do and also to other software?
