### ISSUE TITLE
borg compact -v could output some info

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#4522]
I tried `borg compact -v` in 1.2.0a6 and noticed it shows no output. I tried `borg compact --debug` and indeed it shows debug output.

`-v` usually shows some useful info/stats with other commands, it would be nice if borg compact could also output some basic stats (space freed or something else meaningful).

Also a couple tips related to compact (maybe I should open a new issue):
- the web page (https://borgbackup.readthedocs.io/en/latest/usage/compact.html) should details a bit more the description of --cleanup-commits , e.g. something like `"cleanup commit-only 17-byte segment files generated by borg 1.1. Use this one time after upgrading borg (server) to 1.2+"`, removing the same info from the Example;
- the docs should also clarify when it is useful to run compact, and also which commands may need it. I suppose it is only useful after a delete/prune. If I just run creates (and never delete/prune) is it still needed? BTW in 1.1 in which commands was executed?

**Comment by ThomasWaldmann** [comment]
good ideas, I'll see what can be done.

in < 1.2, compaction (IIRC) was always invoked when borg did write access to the repo.

but guess the only action creating holes that should be compacted is any kind of object deletion.

**Comment by ThomasWaldmann** [comment]
@FabioPedretti try `borg compact --progress` to see progress information.

Other than that, there isn't much to show for `borg compact --verbose` - just saying it started and it ended is a bit pointless and everything potentially taking a long time is covered by the progress indicator.

**Comment by ThomasWaldmann** [comment]
Side note: if one uses a storage quota, it will log the quota and the quota use (which has somehow similar information than logging how much space was freed by compact_segments).

**Comment by ThomasWaldmann** [comment]
see #4544.
