### ISSUE TITLE
buy stickers

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4527]
todo after #1902 is finished.

I'll privately buy some stickers to distribute to borg community (spread at conferences, mail to interested parties who also want some / want to spread some) and compensate that via a bountysource bounty.

https://www.bountysource.com/issues/73385627-buy-stickers

**Comment by ThomasWaldmann** [comment]
Seems like nobody wants to help / can free time to help with #1902.

I'll wait some days and in case nobody jumps in, I'll close this also and transfer the bounty money back to organization funds or other issues.

**Comment by dragetd** [comment]
I hope I correctly claimed this issue.

**Comment by ThomasWaldmann** [comment]
Hmm, bountysource seems to have some strange TLS error right now.

Let's wait until they are online again.

**Comment by dragetd** [comment]
Gee, I over-estimated the amount. Still have so many left, even tho I leave a bunch at every event. xD

I mentioned it before: If you are a hackerspace or similar thing and want a bunch to spread around, drop me a note and I can postage a pile over (sorry, not for personal requests, too much work / cost with the shipping =/ )

**Comment by ThomasWaldmann** [comment]
If somebody got a ticket for easterhegg 2020 in hamburg, some stickers could be spread there. I didn't get one, so guess GPN in karlsruhe is my next CCC event.

**Comment by ThomasWaldmann** [comment]
@dragetd can you claim (again)? I don't see your past claim on bountysource.

**Comment by ThomasWaldmann** [comment]
ehrm, I just noted this issue is open still, so it can't be claimed.

@dragetd try now. :-)
