### ISSUE TITLE
borg backup and btrfs 

### ISSUE THREAD

**Issue by manfredlotz** [borgbackup/borg#4532]
This is Fedora 30 Beta and borg is version 1.1.9

When I do a backup of a `btrfs` file system I first do a readonly snapshot, then back up the readonly snapshot.

Example
```
btrfs sub snap -r /home /.snapshots/home
borg create -v -stats /mnt/borg_repos::home.20190428 /.snapshots/home
btrfs sub del /.snapshots/home
```
The problem with this approach is that instead of paths starting with `/home` I have now `/.snapshots/home`.

Anything, I can do here.

**Comment by ThomasWaldmann** [comment]
```
cd /.snapshots
borg create -v -stats /mnt/borg_repos::home.20190428 home
```

alternatively: do it as before and strip away the `.snapshots` at extraction time, see `borg extract --help`.

**Comment by ThomasWaldmann** [comment]
TODO: check FAQ and docs whether this is already covered. if not, a PR for this is welcome!

**Comment by manfredlotz** [comment]
`cd /.snapshots` aso is a possible solution for `/home`.

But I have other mount points like for instance: `/data/images` where it doesn't fit nicely. Sure, I could workaround by naming the snapshot: `data.images`.

It would be great to have a mapping parameter in the `borg create` subcommand.

**Comment by manfredlotz** [comment]
I think I have to deal with it when doing the backup because otherwise the paths look too weird when mounting the repository.

**Comment by ThomasWaldmann** [comment]
IIRC you can also strip for `borg mount`.

**Comment by fantasya-pbem** [comment]
I take this ToDO and make a PR with a new FAQ, mentioning `extract` and `mount` PATH.
