### ISSUE TITLE
Exception results in "wrong" exit code (warning) instead of error

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#4537]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Of course.

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borgbackup-1.1.7-2.fc30

#### Operating system (distribution) and version.

Fedora 30

#### Hardware / network configuration, and filesystems used.

irrelevant

#### How much data is handled by borg?

ireelevant

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg -V` already or even `borg`

#### Include any warning/errors/backtraces from the system logs

```sh
$ borg -V
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (msgpack 0.6.1 (/usr/lib64/python3.7/site-packages), Requirement.parse('msgpack!=0.5.0,!=0.5.1,!=0.5.2,!=0.5.3,!=0.5.4,!=0.5.5,<=0.5.6,>=0.4.6'), {'borgbackup'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/borg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack!=0.5.0,!=0.5.1,!=0.5.2,!=0.5.3,!=0.5.4,!=0.5.5,<=0.5.6,>=0.4.6' distribution was not found and is required by borgbackup
$ echo $? # <-- this is important!
1
```

## What happens

The exception itself **is a known issue** (see [the Fedora bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1669083)), but **it's not what this bug report is about**(!).

What matters is the exit code! Borg seems to end with error code 1 when it encounters an exception. However, borg defines this as a "warning" only ([as per it's doc](https://borgbackup.readthedocs.io/en/stable/usage/general.html#return-codes)), i.e. no serious error…

## What should happen

IMHO, borg should in this case exit with error level `2` or higher.

Because this is certainly a fatal error… :smile: 

## Links

For wrapper projects or so, this can result in the wrong conclusions being drawn. 
See https://github.com/rugk/borg-cron-helper/issues/78 for the downstream issue of my wrapper scripts.

**Comment by ThomasWaldmann** [comment]
You are running an unsupported msgpack version, which is ... unsupported. ;-)

Also, the code erroring out with rc 1 is not even borg, but pkg_resources, there is nothing we can do about that.

And we never said you can just ignore warnings of borg (rc 1). A warning means you have to check the logs / the root cause and decide whether you can ignore it or not.

**Comment by rugk** [comment]
Yes, but this is not a warning, this is a huge program failure… So you really cannot catch that exception somehow and change the exit code?

**Comment by ThomasWaldmann** [comment]
This is the automatically generated `borg` script:
```
#!/home/user/w/borg-env/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'borgbackup','console_scripts','borg'
__requires__ = 'borgbackup'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('borgbackup', 'console_scripts', 'borg')()
    )
```
