### ISSUE TITLE
Warning: Using a pure-python msgpack! This will result in lower performance

### ISSUE THREAD

**Issue by DannyBen** [borgbackup/borg#4538]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. Found:

- [This unanswered question on python.org](https://mail.python.org/pipermail/borgbackup/2017q3/000747.html)
- [This GitHub issue - where they just say to install it differently](https://github.com/b3vis/docker-borgmatic/issues/6)

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

The borg alpine package at https://pkgs.alpinelinux.org/package/edge/community/x86/borgbackup

borg 1.1.7

#### Operating system (distribution) and version.

Alpine linux official image

```
# cat /etc/alpine-release
3.9.0
```

#### Hardware / network configuration, and filesystems used.

NA

#### How much data is handled by borg?

NA

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg init ./repo -e none`

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. Full reproduction steps:

```
$ docker pull alpine
$ docker run --rm -it alpine
$ apk --no-cache add borgbackup
$ borg init ./repo -e none
```

#### Include any warning/errors/backtraces from the system logs

Just this output:

`Using a pure-python msgpack! This will result in lower performance.`

**Comment by ThomasWaldmann** [comment]
As you use a "apk" package, I suspect this means a pre-packaged borg made by some alpine package maintainer and that this package depends on a pre-packaged (python-)msgpack package made by some (other?) alpine package maintainer.

The warning means that the latter (msgpack) is not packaged correctly (the C-based compiled code is missing and if falls back to the pure python code).

So, this is not a borgbackup, but a alpine packaging issue.

Also, there is borgbackup 1.1.9 (just saying).

**Comment by DannyBen** [comment]
Yeah, I figured as much - not sure where to reach the alpine package maintainer, and was hoping maybe he might be hanging out here.

**Comment by ThomasWaldmann** [comment]
Isn't there some packaging metadata or web site where you can find the contact?

**Comment by DannyBen** [comment]
> Isn't there some packaging metadata or web site where you can find the contact?

I'm on it. The place to report is in the [global alpine linux bug tracker](https://bugs.alpinelinux.org/projects/alpine/issues).

Waiting for my confirmation email, and will open an issue.

**Comment by ThomasWaldmann** [comment]
@DannyBen besides including the compiled stuff, see borg's setup.py, msgpack needs to satisfy the requirements given there - latest version won't work for borg 1.1.x.

**Comment by DannyBen** [comment]
I have opened issue [10401 on bugs.alpinelinux.org](https://bugs.alpinelinux.org/issues/10401)
