### ISSUE TITLE
[1.2.0a6] borg compact doesn't use BORG_REPO env variable

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#4541]
I get this:
`borg-1.2.0a6 compact: error: the following arguments are required: REPOSITORY`

borg list, for example, works fine.

**Comment by ThomasWaldmann** [comment]
Seems to affect more commands than just `compact`.

Also, the placeholders (like `REPO` or `REPO::ARCHIVE`) could be cleaned up.
