### ISSUE TITLE
[1.1 RFC] remove compaction after create, do it only after delete/prune

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#4546]
1.2 will have a dedicated command for compaction. However it was clarified that compaction should be really needed only after deleting archives, while it is also done also after create in 1.1.

In 1.1 I verified that when creating a small archive in a big repo, it takes over 5 minutes, while borg reports: `Duration: 1 minutes 46.29 seconds`. Part of the difference (over 3 minutes) is due to some other activities including compaction. This is very noticeable when doing create with many small archives.

So the proposal would be to disable compaction from create in 1.1, leaving it only when deleting archives, in the meantime that 1.2 will be ready.

Thanks.

**Comment by ThomasWaldmann** [comment]
IIRC, the additional time you see is taken by:
- compacting non-compact segments
- committing the repo (saving repo index etc.)
- committing the cache (saving chunks index, files cache)

As 1.1 runs compact_segments quite frequently, there isn't much to compact after `borg create`, so it doesn't take a lot of time. But, if it is a big repo (many chunks) and the usual backups done from the test machine have many (input data set) files, the indexes and caches are large and take some time to get written to disk.

So I'ld expect it not getting significantly faster.

Also, considering that 1.1 is the stable release, I'ld rather not do such changes there.

**Comment by ThomasWaldmann** [comment]
One of the scenarios where removing compaction significantly speeds things up is this:
- user does some custom selection of archives (manually or by some self-made prune policy script)
- for archive in archives: borg delete archive  (no compaction in borg 1.2)
- borg compact (just compact once, not N times)

**Comment by FabioPedretti** [comment]
If it can be useful, consecutively running borg-1.2.0a6 compact on my 1.1 production repo takes between 1:00 and 1:50 minutes (I remember that backupping a tiny archive on the same repo takes about 5 minutes).
But I agree with the other points.

(For reference running compact with --cleanup-commits is a lot faster, taking about 20-40 seconds, after the first execution, which removed tens thousand of 17 bytes files and took some hours.)

**Comment by ThomasWaldmann** [comment]
If borg compact runs for 1:00 to 1:50 minutes overall, that also includes the time to load/save repo index, so the pure compaction time is less than that.

Yeah, cleaning up the 17byte files **once** is useful.

**Comment by FabioPedretti** [comment]
Thanks for the clarifications and the time you put on this. Feel free to close the issue if there is nothing pending here.

**Comment by ThomasWaldmann** [comment]
Guess I rather work on finishing 1.2 than on 1.1 compaction changes.
