### ISSUE TITLE
encryption mode : mandatory or optional ?

### ISSUE THREAD

**Issue by guy-teube** [borgbackup/borg#4550]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
borg 1.1.5

#### Operating system (distribution) and version.
Ubuntu 18.04 LST 64 bits

#### Hardware / network configuration, and filesystems used.
ext4

## Describe the problem you're observing.

I run :
$ borg init path/to/dir
I get the error : 
borg init: error: the following arguments are required: -e/--encryption

So I run : 
$ borg init --help
Which says : 
optional arguments:
  -e MODE, --encryption MODE

The -e option seems to be mandatory, but in the man page, it's seems optional. What's the good status ?

**Comment by ThomasWaldmann** [comment]
Hmm, it used to be totally optional in borg 1.0, but as 1.1 added the blake2-based modes, there was no clear default any more and it became non-optional, so the user does a informed decision.

BTW, you are using a relatively old borg. If you'ld pull it from the ppa, you'ld get latest 1.1.x release.

borg 1.1.9 output:
```
optional arguments:
  -e MODE, --encryption MODE
                        select encryption key mode **(required)**
```
So, still a bit strange, but at least says "required" now.

**Comment by ThomasWaldmann** [comment]
from the code:
```
        subparser.add_argument('-e', '--encryption', metavar='MODE', dest='encryption', required=True,
                               choices=key_argument_names(),
                               help='select encryption key mode **(required)**')
```

**Comment by ThomasWaldmann** [comment]
Hmm, this might be terminology: `positional` vs. `optional` (optional meaning "like an option").

And usually options are optional (in the sense that you can give them or not), but for reasons give above, this is not the case here.

**Comment by ThomasWaldmann** [comment]
https://docs.python.org/3/library/argparse.html#required

**Comment by ThomasWaldmann** [comment]
So guess this is a cosmetic bug in the argparse help generation (or just a terminology issue).

Anyway, nothing we can easily fix in borg.

If we ever do a release doing everything new and incompatible, the encryption mode should not be an optional, but a required (positional) argument.

**Comment by jchook** [comment]
What if we made `none`, `authenticated`, or `authenticated-blake2` the default encryption mode?

1. The need to research / choose encryption modes poses a hurdle to getting started with borg
2. It seems reasonable that omitting the `--encryption` flag would generate an unencrypted repo.

**Comment by ThomasWaldmann** [comment]
"Security by default" - if you want to make it less secure, you need to configure it.

**Comment by ThomasWaldmann** [comment]
Guess we can't do anything here.
