### ISSUE TITLE
Support placeholders in archive comment

### ISSUE THREAD

**Issue by elho** [borgbackup/borg#4559]
It would be useful and more consistent, if the placeholders that can be used in archive names could also be used in archive comments.
Use case being to record information that could be useful to have at some point without making the archive name unnecessary long, e.g. `borg create --comment='Created using borg {borgversion} on {fqdn}' /path/to/repo::{hostname}-{now}`.

**Comment by ThomasWaldmann** [comment]
yup, good idea!
