### ISSUE TITLE
SSH port in repo url is not used when ssh:// is ommitted 

### ISSUE THREAD

**Issue by RlndVt** [borgbackup/borg#4565]
When trying to connect or initialise a repo over ssh, without adding ssh://, port 22 is used instead of the one specified in the url.

e.g. user@host:port/path/to/repo

When you add ssh:// the repo is initialised/added.

**Comment by ThomasWaldmann** [comment]
`port` is not part of the `user@host:path` syntax (see also `man scp`).

if you need to give a port, you must use `ssh://...`.

**Comment by ThomasWaldmann** [comment]
for scripting or shell usage, if you want to type less, consider setting the `BORG_REPO` environment variable. you don't need to give the long repo url in every borg command then.
