### ISSUE TITLE
BORG_PASSCOMMAND not working in script

### ISSUE THREAD

**Issue by aksh1618** [borgbackup/borg#4566]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug / Question

#### Your borg version (borg -V).

borg 1.1.8

#### Operating system (distribution) and version.

Arch Linux

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```bash
# Borg part of the backup script
sudo borg create                                                        \
    $BACKUP_LOCATION/borg_back::$(hostname)-$(date +%Y-%m-%d.%H-%M-%S)  \
    /                                                                   \
    --exclude pp:/dev                                                   \
    --exclude pp:/proc                                                  \
    --exclude pp:/sys                                                   \
    --exclude pp:/var/run                                               \
    --exclude pp:/var/cache                                             \
    --exclude pp:/run                                                   \
    --exclude pp:/mnt                                                   \
    --exclude pp:/tmp                                                   \
    --exclude pp:/lost+found                                            \
    --one-file-system                                                   \
    --verbose                                                           \
    --stats                                                             \
    --show-version                                                      \
    --show-rc                                                           \
    --progress                                                          \
    --compression zstd,10                                               \
    --exclude-caches                                                    \
    --list                                                              \
    --filter AME                                                        \
    2>> $BACKUP_LOCATION/logs/borg-$(date +%Y-%m-%d.%H-%M-%S)
```

## Describe the problem you're observing.

I'm using this at top of script:

```bash
export BORG_PASSCOMMAND='sudo cat /home/aksh/secure/borg_pass'
```

Where `borg_pass` contains password:

```bash
ls -la /home/aksh/secure/borg_pass
# -r-------- 1 root root 13 Apr 28 23:26 /home/aksh/secure/borg_pass
```

And executing the script as follows:

```bash
sudo --preserve-env ./backup.sh
```

But I still get prompted:

```bash
Enter passphrase for key /run/media/aksh/Aksh_HDD_1TB/borg_back: 
```

I tried owner and permissions of `borg_pass`, but nothing worked. Entering the password manually makes the backup proceed normally.

**Comment by ThomasWaldmann** [comment]
if you run your backup script as root, why do you have sudo in your BORG_PASSCOMMAND?

if you set BORG_PASSCOMMAND at the top of your backup script, why do you need --preserve-env when calling that script?

in general, i'ld advise doing simpler steps first and reducing everything to the bare minimum.

i tried to reproduce your problem (as a normal user, only doing the bare minimum to test BORG_PASSCOMMAND) and it worked fine for me.

important is to never forget that "export" in `export BORG_PASSCOMMAND=...`, otherwise it won't be in the shell environment and borg can only read it from there.

**Comment by aksh1618** [comment]
> if you run your backup script as root, why do you have sudo in your BORG_PASSCOMMAND?

Didn't have it initially, just added it there to see if that fixed the issue.

> if you set BORG_PASSCOMMAND at the top of your backup script, why do you need --preserve-env when calling that script?

Also an attempt to fix the issue

> i tried to reproduce your problem (as a normal user, only doing the bare minimum to test BORG_PASSCOMMAND) and it worked fine for me.

I need to run as sudo because I want to run `backup.sh` non-interactively and thus need not to have to enter sudo password for various steps.

**Comment by ThomasWaldmann** [comment]
AFAIK, BORG_PASSCOMMAND works, so might be some environment issue (not being in env, filtered from env, ...).
