### ISSUE TITLE
dedicted error message instead of stacktrace

### ISSUE THREAD

**Issue by Arlon1** [borgbackup/borg#4571]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

Issue.

#### Your borg version (borg -V).
borg 1.1.8
#### Operating system (distribution) and version.
Arch Linux.
#### How much data is handled by borg?
No Data.
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```borg init -e none patt/to/dir_without_read_permission```

## Describe the problem you're observing.
Borg prints a (rather verbose) stacktrace and system information.
IMHO a (possibly one-lined) error message would be more appropriate.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
```
mkdir /tmp/directory
chmod -r /tmp/directory
borg init -e none /tmp/directory
```

#### Include any warning/errors/backtraces from the system logs
```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 137, in wrapper
    with repository:
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 182, in __enter__
    self.create(self.path)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 251, in create
    self.check_can_create_repository(path)
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 234, in check_can_create_repository
    if not os.path.isdir(path) or os.listdir(path):
PermissionError: [Errno 13] Permission denied: '/tmp/directory'

Platform: Linux nz 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.3
PID: 24859  CWD: /home/fr
sys.argv: ['/usr/bin/borg', 'init', '-e', 'none', '/tmp/directory']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
There's the preference to rather give too much than too little information. This is not a bug, but intended.

In some cases (like yours), the traceback is not really needed. But you can ignore it.

But it would be worse if there is an error that is more complex / unclear and we have no traceback. Sometimes errors can not easily be reproduced, so it is important to have the traceback.
