### ISSUE TITLE
test failure with borgbackup 1.1.10

### ISSUE THREAD

**Issue by FelixSchwarz** [borgbackup/borg#4573]
(This is just early feedback - I need to investigate this a bit more but I wanted to give you a heads up)

    py.test-3 -x -vk "not test_non_ascii_acl and not test_fuse and not benchmark and not test_dash_open" $PYTHONPATH/borg/testsuite/*.py

    =================================== FAILURES ==============================
    __________________ ArchiverTestCase.test_corrupted_repository _____________

    self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_corrupted_repository>

        def test_corrupted_repository(self):
            self.cmd('init', '--encryption=repokey', self.repository_location)
            self.create_src_archive('test')
            self.cmd('extract', '--dry-run', self.repository_location + '::test')
            output = self.cmd('check', '--show-version', self.repository_location)
            self.assert_in('borgbackup version', output)  # implied output even without --info given
    >       self.assert_not_in('Starting repository check', output)  # --info not given for root logger
    E       AssertionError: 'Starting repository check' unexpectedly found in 'borgbackup version 1.1.10\nStarting repository check\nStarting repository index check\nCompleted repository check, no problems found.\n'

    build/lib.linux-x86_64-3.7/borg/testsuite/archiver.py:1523: AssertionError

The strange thing is that this failure did only show on Fedora 30 builders (not rawhide):
 - f30: https://koji.fedoraproject.org/koji/taskinfo?taskID=34880986
 - ~~rawhide: https://koji.fedoraproject.org/koji/taskinfo?taskID=34880896~~

I'm double checking a few things to ensure I did not mess up.

**Comment by FelixSchwarz** [comment]
This does not happen when running the tests on a F30 VM (not COPR/mock) - of course #4574 is visible. Need to check a bit more...

**Comment by ThomasWaldmann** [comment]
Hmm, the test code shown looks a bit strange, so I guess at least a comment why 'Starting repository check' should not show up there is missing.

**Comment by FelixSchwarz** [comment]
I have some more data to report:
- Test only fails in mock ("build container") not when run from the command line.
- It only happens for Fedora 30 (not F29, not rawhide).
- Running only this test alone makes the test pass (-> test ordering issue?, may [build-output.txt](https://github.com/borgbackup/borg/files/3187098/build-output.txt) helps)

For now I excluded the test when building Fedora's RPMs but I like to solve this properly (eventually, not necessarily right now).

I see that "test_corrupted_repository" passes multiple times until it fails:

    collecting ... collected 2714 items / 142 deselected
    ...
    ArchiverTestCase::test_corrupted_repository PASSED [  2%]
    ...
    ArchiverTestCaseBinary::test_corrupted_repository SKIPPED [  8%]
    ...
    RemoteArchiverTestCase::test_corrupted_repository PASSED [ 14%]
    ...
    ArchiverTestCase::test_corrupted_repository FAILED [ 50%]

Also I observed that sometimes pytest's progress reporting seems to be stuck at 50% before it finally passes. Maybe this is a pytest issue? Fedora 29 uses pytest 3.6.4, Fedora 30 uses 3.9.33 , rawhide has 4.4.1)

Anyway I'm looking for input:
- I think no test should be run twice, right?
- Is it possible that some previous tests modify the logger configuration without resetting it? When "cmd" is called it that always a subprocess? (making it unlikely that there are some leftovers in memory)
- any ideas how to debug that? (keep in mind this happens only inside the build container so gdb won't work easily)

**Comment by FelixSchwarz** [comment]
pytest - I hate you. I'm 90% convinced that this is a problem with pytest. If I force pytest 4.5.0 manually inside the F30 build, everything works.

**Comment by FelixSchwarz** [comment]
Ok, so for some (unknown) reason the test suite does not pass with pytest 3.7.x - 3.9.x (in mock). pytest 3.7 fails to even collect all tests. With pytest 3.8/3.9 I get the test failure mentioned in my first post. pytest 4.4/4.5 are fine.

A Fedora scratch build passed even for F30 so I'm currently building the real release for Fedora users.

@ThomasWaldmann: You added this issue to milestone "hydrogen-alpha7". Not sure if you still want to clarify the test conditions - otherwise feel free to close this issue.


#    pytest 3.7.x - 3.9.x fail to run the test suite.
#      Fedora 29 has pytest 3.6.4 (good), Fedora 30 uses 3.9.3 (as of 05/2019)
#    pytest versions 3.8.x/3.9.x cause test failure in ArchiverTestCase::test_corrupted_repository
#    (only when running the full suite).

**Comment by FelixSchwarz** [comment]
closing the issue as this is pytest related. Feel free to reopen if there is something left to be done for borgbackup.
