### ISSUE TITLE
[Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by mkirkland4874** [borgbackup/borg#4578]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

Client: v1.1.8
Server: v.1.1.8

#### Operating system (distribution) and version.

Client: Arch Linux kernel 4.19
Server: Alpine Linux kernel 4.14

#### Hardware / network configuration, and filesystems used.

Client: x86-64, BTRFS
Server: ARMv7, EXT4

#### How much data is handled by borg?

1-2TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Server (works): borg info /mnt/backup/borg/repo/root/
Client (does't work): borg info root@192.168.1.12:/mnt/backup/borg/repo/root/

## Describe the problem you're observing.

When using "borg info" over SSH from client to server, I get the following error. However, when I use "borg info" on the sever, it works.

*FileNotFoundError: [Errno 2] No such file or directory: ''*

#### Include any warning/errors/backtraces from the system logs

```
=== SERVER (WORKS) ===

odroid:/mnt/backup/borg# borg info /mnt/backup/borg/repo/root/
Using a pure-python msgpack! This will result in lower performance.
Repository ID: 12345
Location: /mnt/backup/borg/repo/root
Encrypted: No
Cache: /mnt/backup/borg/base/.cache/borg/12345
Security dir: /mnt/backup/borg/base/.config/borg/security/12345
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:               51.62 TB             45.62 TB              1.07 TB

                       Unique chunks         Total chunks
Chunk index:                  802916             35429716



=== CLIENT SSH (DOESN'T WORK) ===

[root@nas]# borg info root@192.168.1.12:/mnt/backup/borg/repo/root/
Remote: Using a pure-python msgpack! This will result in lower performance.
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4436, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4368, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 143, in wrapper
    assert_secure(repository, kwargs['manifest'], self.lock_wait)
  File "/usr/lib/python3.7/site-packages/borg/cache.py", line 205, in assert_secure
    sm = SecurityManager(repository)
  File "/usr/lib/python3.7/site-packages/borg/cache.py", line 64, in __init__
    self.cache_dir = cache_dir(repository)
  File "/usr/lib/python3.7/site-packages/borg/cache.py", line 226, in cache_dir
    return path or os.path.join(get_cache_dir(), repository.id_str)
  File "/usr/lib/python3.7/site-packages/borg/helpers.py", line 512, in get_cache_dir
    os.makedirs(cache_dir)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

Platform: Linux nas 4.19.31-1-lts #1 SMP Sun Mar 24 09:29:16 CET 2019 x86_64
Linux: arch  
Borg: 1.1.8  Python: CPython 3.7.2
PID: 1764  CWD: /root
sys.argv: ['/usr/bin/borg', 'info', 'root@192.168.1.12:/mnt/backup/borg/repo/root/']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
do you set `BORG_CACHE_DIR` to something?

**Comment by ThomasWaldmann** [comment]
btw, your msgpack-python is not correctly compiled, therefore you get that slowness warning.

use borg 1.1.10 to get a bundled and compiled msgpack with borg.

**Comment by mkirkland4874** [comment]
Thomas, you are correct. I had set BORG_CACHE_DIR to "" via
`export BORG_CACHE_DIR=""`
instead of 
`unset BORG_CACHE_DIR`

in order to clear it, which is incorrect. Unsetting the env var works now. Thanks for the heads up on the msgpack. Will plan to upgrade.

**Comment by fbicknel** [comment]
Just to help anyone else looking for this, the same applies to `BORG_CONFIG_DIR`. 

So be sure both `BORG_CACHE_DIR` and `BORG_CONFIG_DIR` are set to sane values or are unset!
