### ISSUE TITLE
ARM builds of 1.1.10 not downloadable

### ISSUE THREAD

**Issue by daPhipz** [borgbackup/borg#4579]
Since the release of 1.1.10 here on Github, I checked https://borg.bauerj.eu/ for builds to use on my Raspberry Pi. Until yesterday, the old version was downloadable.

Right now, when clicking on one of the Download buttons (ARMv7/ARMv6 in my case), it redirects to a page that says "The requested path was not found." The URL of this page is https://dl.bintray.com/borg-binary-builder/borg-binaries/borg--armv6

**Comment by ThomasWaldmann** [comment]
@bauerj ^^^

**Comment by bauerj** [comment]
Thanks, that should be fixed now.

**Comment by daPhipz** [comment]
Yes, it is fixed. Thanks!

**Comment by ThomasWaldmann** [comment]
@bauerj the new bundled msgpack stuff compiled / works as expected?
