### ISSUE TITLE
More discoverable link to Borgmatic in documentation

### ISSUE THREAD

**Issue by decentral1se** [borgbackup/borg#4581]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

Question.

---

Hi folks, I am wondering if we couldn't place a more discoverable link to https://torsion.org/borgmatic/ in the "Automating Backups" section over at https://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups. This tool is already mentioned in the related "software" section but I think it would be more useful to place it as a note for users who would prefer not to write a bash script (for whatever reason).

Thoughts?

**Comment by ThomasWaldmann** [comment]
I don't want to duplicate outside links in our docs, but what we could do is to link to the "related software" section from the "automating backups" section.

**Comment by decentral1se** [comment]
Agreed then! I'll submit a small PR.

**Comment by decentral1se** [comment]
Please see https://github.com/borgbackup/borg/pull/4586 :+1:
