### ISSUE TITLE
borg create got really slow from one day to the other

### ISSUE THREAD

**Issue by gilbrechbuhler** [borgbackup/borg#4582]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

1.1.9 (same on client and server)

#### Operating system (distribution) and version.

Client: Ubuntu 16.04.4
Server: Synology DSM 6.2.1-23824 Update **4** 

#### Hardware / network configuration, and filesystems used.

Client : LXC container running on a Proxmox host. ext4.
Server: Synology NAS RS815+

#### How much data is handled by borg?

Total size: 1.3 TB
Total compressezd size: 797.2 GB
Deduplicated size: 225.9 GB
Number of files : approximately 112000

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg create --filter AME --stats --json --exclude-caches`
BORG_REPO and BORG_PASSPHRASE environment variables defined.

We then prune with the following command :
`borg prune --list --prefix '{hostname}' --keep-last 2 --keep-daily 7 --keep-weekly 7 --keep-monthly 3`

## Describe the problem you're observing.

The backup for this client used to take 25 minutes on average. However, from one day to the other it suddenly started to take more than 2 hours. The only major change that happened on the container is that more space was dynamically added to its disk.

It is important to note that no change in backup time was noticed on the other LXC containers on the same Proxmox host. So I do not think it is a network issue, neither a server a issue.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The backup always takes more than 2 hours to execute now.

I know the backup has grown in size, but we have other backups that are bigger and take far less than 2 hours to run, using the same destination (but a different repository of course).

I suspected a cache issue, but being unsure and thinking that this issue might have happen to someone else, I figured I'd try to ask here. I did not find related issues though, but I may have miss them. Should I try a `check --repair` or to clean the cache ?

#### Include any warning/errors/backtraces from the system logs

This is the output for the borg backup before it got slow :
```
{
    "archive": {
        "command_line": [...],
        "duration": 425.794767,
        "end": "2019-05-06T03:36:01.000000",
        "id": "<id>",
        "limits": {
            "max_archive_size": 0.0003787524952341225
        },
        "name": "<name>",
        "start": "2019-05-06T03:28:55.000000",
        "stats": {
            "compressed_size": 35369800284,
            "deduplicated_size": 497206891,
            "nfiles": 111316,
            "original_size": 75774952381
        }
    },
    "cache": {
        "path": "<path>",
        "stats": {
            "total_chunks": 4486217,
            "total_csize": 850364833697,
            "total_size": 1265384698357,
            "total_unique_chunks": 238923,
            "unique_csize": 75523128102,
            "unique_size": 146188618853
        }
    },
    "encryption": {
        "mode": "repokey-blake2"
    },
    "repository": {
        "id": "<id>",
        "last_modified": "2019-05-06T03:36:03.000000",
        "location": "<location>"
    }
}
RESULT_0
```

Here are two outputs since the backup became really slow
```
{
    "archive": {
        "command_line": [...],
        "duration": 8017.04051,
        "end": "2019-05-19T05:59:17.000000",
        "id": "<id>",
        "limits": {
            "max_archive_size": 0.0003784663923798603
        },
        "name": "<name>",
        "start": "2019-05-19T03:45:40.000000",
        "stats": {
            "compressed_size": 37037649017,
            "deduplicated_size": 9451646249,
            "nfiles": 112004,
            "original_size": 79102269188
        }
    },
    "cache": {
        "path": "<path>",
        "stats": {
            "total_chunks": 3884451,
            "total_csize": 900801972288,
            "total_size": 1484416770142,
            "total_unique_chunks": 276383,
            "unique_csize": 165230100076,
            "unique_size": 254040860304
        }
    },
    "encryption": {
        "mode": "repokey-blake2"
    },
    "repository": {
        "id": "<id>",
        "last_modified": "2019-05-19T05:59:18.000000",
        "location": "<location>"
    }
}
```
```
{
    "archive": {
        "command_line": [...],
        "duration": 7906.424434,
        "end": "2019-05-20T05:53:13.000000",
        "id": "<id>",
        "limits": {
            "max_archive_size": 0.0003706939315057369
        },
        "name": "<name>",
        "start": "2019-05-20T03:41:27.000000",
        "stats": {
            "compressed_size": 37039591298,
            "deduplicated_size": 9454951988,
            "nfiles": 111993,
            "original_size": 79101346789
        }
    },
    "cache": {
        "path": "<path>",
        "stats": {
            "total_chunks": 3885060,
            "total_csize": 901620051912,
            "total_size": 1486720148451,
            "total_unique_chunks": 274786,
            "unique_csize": 164849176016,
            "unique_size": 252101246243
        }
    },
    "encryption": {
        "mode": "repokey-blake2"
    },
    "repository": {
        "id": "<id>",
        "last_modified": "2019-05-20T05:53:15.000000",
        "location": "<location>"
    }
}
```

Thanks a lot in advance for the help. Please tell me if you need anymore informations. I'll try to run benchmarks as soon as I can and put the informations here, but right now the machine is being used.

**Comment by infectormp** [comment]
You can try:
`--nobsdflags` https://borgbackup.readthedocs.io/en/stable/usage/notes.html#nobsdflags
BORG_FILES_CACHE_TTL https://borgbackup.readthedocs.io/en/stable/faq.html#it-always-chunks-all-my-files-even-unchanged-ones

similar issue: https://github.com/borgbackup/borg/issues/4229 https://github.com/borgbackup/borg/issues/2352 https://github.com/borgbackup/borg/issues/4192

**Comment by ThomasWaldmann** [comment]
It might be interesting to use `borg create --list` for the backups that are slow, so one can tell from the status characters which files borg considered as "potentially changed" - because a major slowdown likely means the files cache does not work as expected (or there really are a lot of unexpected changes) and borg has to chunk / hash / dedup a lot of files.

**Comment by gilbrechbuhler** [comment]
Hello,

Thanks a lot for your answers and sorry for the delayed response. So I ran multiple tests, with --nobsdflags the running time remained approximately the same. I ran tests with --list and the list of potentially chanegd files looked correct.

Then I noticed something, we have some hosted ERP running on this machine, and we export some of its internal data as multiple archive files that we inlude in the borg backup. These archive files are regenerated every night just before the borg backup (in place, so the new files replace the old ones on disk). The size of the archive files varies from 80MB to 6.9GB for a cumulative size of 10 GB approximately.
Here are my observations : if we do not regenerate the archives between two borg backups, the backup goes pretty fast, between 5 and 20 minutes depending on the load of the NAS receiving the backup. However, if we do generate new versions of the archives and run a borg backup again, the backup takes again more than 2 hours. Moreover, the timeline of the backup durations shows that the backups started being slow as soon as we activated the export of those archives.

Is it possible that borg has a hard time deduplicating and compressing those archive files ? I will look into it and try to find if someone encountered the same behaviour.

Thanks again a lot for your answers,
Have a nice day.

**Comment by ThomasWaldmann** [comment]
Yeah, you can see it at the dedup size: 497MB vs. 9.4GB.

So, it is just that your ERP archive files dedup rather badly. What format do they have?

**Comment by ThomasWaldmann** [comment]
Ping.

**Comment by gilbrechbuhler** [comment]
The archives are simple zip archives with a custom extension.

I ran the following test : 
- delete the archives before the backup
- recreate them but change their name to include the date

I wanted to see if this would prevent borg from deduplicating those files, but then I read the documentation again and understood why this would not work. Is there a way to tell borg to not deduplicate specific files ? Or to trick it into believing that they are new files ?

Thanks for your answer,
Have a nice day.

**Comment by ThomasWaldmann** [comment]
not sure about the default mode of "zip" if it is "rsyncable" or not. simple stream compressed data tends to not dedup at all, because a change at the beginning might change the whole remainder of the stream.

borg always dedups. but as it needs to chunk anyway, there is no problem with that even if the outcome is all new chunks (because they didn't dedup).

you could try if you can switch off compression or use a rsyncable compression mode for your db backups.

**Comment by ThomasWaldmann** [comment]
i'm closing this as it is not a borg issue.
