### ISSUE TITLE
Borg should read one line when reading password from stdin, not all input

### ISSUE THREAD

**Issue by fortran77** [borgbackup/borg#4584]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Some people might call it a bug, but maybe it's closer to a feature request

## System information. For client/server mode post info for both machines.

A variety of machines.

#### Your borg version (borg -V).

1.1.9

#### Operating system (distribution) and version.

Ubuntu 16.04, Ubuntu 18.04, CentOS 7.

#### Hardware / network configuration, and filesystems used.

A variety of machines, ext4 and xfs.

#### How much data is handled by borg?

Varies, between a few hundred kbytes and a few gigabytes.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

A variety of commands, the commonality is:

`export BORG_PASSPHRASE_FD=0`

## Describe the problem you're observing.

I am trying to do something that I thought would work, but it did not. When invoking borg from a Makefile, and having it read a password from stdin, and if we want the Makefile to do more than one borg command, suppose I try something like this:

` make abackup bbackup < password`

Here, 'make abackup' would cause a Borg backup to some remote archive A, and 'make bbackup' would cause a Borg backup to some remote archive B. So 'make abackup bbackup' simply runs both one by one.

But if Borg is reading the password from stdin, then the first invocation will eat up the password from stdin, leaving nothing for the second invocation.

The clever solution I came up with was to have the password twice in the password file. So the password file might contain:

`e8e928j4te57cm3f2u2k87k5`
`e8e928j4te57cm3f2u2k87k5`

My thinking was that the first invocation would read the first line, and the second would read the second line, and each would get the password.

But I then always get a password error.

There are two possible explanations. First, that Borg is reading all of stdin taking all of that as the password. Or second, Borg is doing buffered input, and the first invocation of Borg reads a block and consumes all of stdin, leaving nothing for the second one.

The first is more likely, because if I have the password twice in the password file, **both** invocations of Borg fail, not just the second one. The error as you might expect is:

`passphrase supplied in BORG_PASSPHRASE, by BORG_PASSCOMMAND or via BORG_PASSPHRASE_FD is incorrect.`

If my theory is correct, then my feature request is that Borg use unbuffered input (i.e., directly use the read() system call and read character by character until line feed is seen) and always read exactly one line from stdin and use that as the password. Then a strategy like mine should work.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The problem can be reproduced every time.

**Comment by ThomasWaldmann** [comment]
This is the relevant code:
```
    @classmethod
    def fd_passphrase(cls):
        try:
            fd = int(os.environ.get('BORG_PASSPHRASE_FD'))
        except (ValueError, TypeError):
            return None
        with os.fdopen(fd, mode='r') as f:
            passphrase = f.read()
        return cls(passphrase.rstrip('\n'))
```

So yes, your suspicion was right, it just reads all it can get.

Can you make a PR that fixes this and adds related tests?

**Comment by ThomasWaldmann** [comment]
Hmm, if users had more than one line readable from the FD, fixing this issue will break their passphrase / their setup.

**Comment by fortran77** [comment]
> Can you make a PR that fixes this and adds related tests?

Sure, can you folks please rewrite Borg in Perl?

Just kidding, I'll try to pick up enough Python to submit a PR. Thank-you for identifying the relevant code.

**Comment by ThomasWaldmann** [comment]
another idea: can't you just do it like:
```
make abackup < password
make bbackup < password
```

**Comment by fortran77** [comment]
Yes, I can always use separate commands, and I do. However, I was doing a couple of other things not so simple. E.g., the equivalent of:

```
LASTARCHIVE=`borg list --short somearchive | tail -1`
```

to get the last archive and then do another operation on $LASTARCHIVE. So this needs to be done with a single command. So a general solution opens up many possibilities.

I'm thinking an upward compatible solution might be to have Borg seek to position 0 in stdin before reading the password. This should work if stdin is a file (and if not should leave the seek position unchanged), and will not affect anybody using a multi-line password. I'll test it out to see if it will work.

**Comment by fortran77** [comment]
It turns out there is a simple solution, which won't actually work for me, but it works if your make command is reading from a file. In the Makefile:

`exec </dev/stdin ; borg command args ...`

In a bash in a Linux environment the phrase `exec </dev/stdin` reopens stdin from file descriptor 0, effectively seeking to position 0. So each Borg command preceded by `exec </dev/stdin` will read the password from the beginning.

It won't work for me because I am using ssh to invoke the make on a remote system, and feeding ssh the password file on stdin. So on the remote system the password is being read from a non-seekable pipe.

**Comment by fortran77** [comment]
My final solution is to save stdin into a temp file, then use Borg as many times as needed each time having it read from the file.

For better security I am saving stdin into a temp file, redirecting stdin to read from that file, then immediately removing the file. Now Borg can be repeatedly invoked, each time seeking back to 0 via the `exec </dev/stdin` strategy. This works well enough and with sufficient security, so I will close this issue.

Example Makefile lines are below.
```
mytarget:
        PASS=tmp.pass.$$$$; trap "rm -f $$PASS; exit" 0 1 2 3 15; \
        touch $$PASS; chmod 600 $$PASS; cat > $$PASS; exec 0<$$PASS; rm -f $$PASS; \
        export BORG_PASSPHRASE_FD=0; \
        exec 0</dev/stdin; first borg command ... ; \
        exec 0</dev/stdin; second borg command ... ; \
        ... ; \
        exec 0</dev/stdin; nth borg command ... ; \
        rm -f tmp.pass.*
```
