### ISSUE TITLE
Borg extract not keeping permissions from archive

### ISSUE THREAD

**Issue by Fabiosilvero** [borgbackup/borg#4589]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG
#### Your borg version (borg -V).
1.1.9
#### Operating system (distribution) and version.
LMDE 3 (based on Debian Stretch 9) amd64
#### How much data is handled by borg?
50Go 
#### Full borg commandline that lead to the problem (leave away excludes and passwords)

$ borg extract /path/to/repo::archive 

## Describe the problem you're observing.

Instead of keeping the UID/GID set in archive (visible with mounting borg archive), borg replaces with user executing it.

in archive mounted : 
-rw-r--r-- root root /etc/fstab

when copied /extracted  : 
-rw-r--r-- user user /etc/fstab

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I tried to : 
- mount archive, then cp -arv to destination : it failed to keep permissions
- mount archive, then rsync -av to destination : it failed to keep permissions
- extract archive : it failed to keep permissions

**Comment by ThomasWaldmann** [comment]
If you run borg as a normal user, borg does not have the permission to "chown/chgrp away from the current uid/gid" - you need to run borg as root for that.

That's expected and not a bug.
