### ISSUE TITLE
ability to unbundle xxhash?

### ISSUE THREAD

**Issue by FelixSchwarz** [borgbackup/borg#4592]
I noticed that borgbackup bundles (parts of) the xxHash library since commit 47894072ad5ed6d28375bdb7d6316b6bc8661284 (borgbackup 1.1.0). It seems as if you copied xxHash 0.6.2 and stripped all non 64-bit functionality.

Do you think it is possible to use a system-provided xxHash library? Is there a technical reason why the xxHash library is not suitable for borg?
I noticed a [comment in the original pull request](https://github.com/borgbackup/borg/pull/2580#issuecomment-305579398) by @enkore. He mentions performance benefits of not having additional function calls. Is there a place which is most likely affected by this?

This is a request mandated by [Fedora's packaging policy](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling):
> In addition to indicating bundling in this manner, packages whose upstreams have no mechanism to build against system libraries must be contacted publicly about a path to supporting system libraries. If upstream refuses, this must be recorded in the spec file, (...)

**Comment by ThomasWaldmann** [comment]
I didn't work with that code yet, just reviewed it back then.

I did a quick check about libxxhash: seems to be rather new in dists, for ubuntu one needs >= cosmic, for debian >= buster.

So, for borg 1.1.x I'ld prefer things staying as is for now, for master branch we could do it like we do for the other libs (see setup_xxx.py code).

**Comment by FelixSchwarz** [comment]
> So, for borg 1.1.x I'ld prefer things staying as is for now, for master branch we could do it like we do for the other libs (see setup_xxx.py code).

That is sensible. I'll see if I can take a stab at this.

**Comment by enkore** [comment]
IIRC it was new back then and no one of relevance had it packaged.

**Comment by FelixSchwarz** [comment]
Just a quick update: I have some code which unbundles xxhash which builds. There is some more work to do because just putting borg 1.2.0a6 in Fedora's spec file (+ unbundling patch) caused test failures. However that might be also a side-effect of the 1.2.0a6 upgrade (I never even tried to build the unmodified borg alpha version).

If someone is interested in working on that I'm happy to push my work in progress to a branch.

Btw: I noticed borgbackup right now ships *two* copies of xxhash already :-)

**Comment by ThomasWaldmann** [comment]
You could just open a "WIP: ..." PR.

About the 2 copies: I guess one is the directly bundled xxhash code, the other is indirect via some other code we bundle (like zstd).

The setup.py in master (1.2.0a6) is quite different from 1.1-maint branch.
Can you give a link to the test failures?

**Comment by FelixSchwarz** [comment]
> About the 2 copies: I guess one is the directly bundled xxhash code, the other is indirect via some other code we bundle (like zstd).

Yes.

> The setup.py in master (1.2.0a6) is quite different from 1.1-maint branch.

Right. That's why I'll only provide patches for master. Fedora can live with a bit of bundling for the time being.

>  Can you give a link to the test failures?

Will do when I'm working on this issue again. No hurries though.

**Comment by enkore** [comment]
zstd doesn't expose xxh though.

**Comment by FelixSchwarz** [comment]
It seems the main problem is this Cython code from checksums.pyx:

    cdef class StreamingXXH64:
        cdef XXH64_state_t state

        def __cinit__(self, seed=0):
            cdef unsigned long long _seed = seed
            if XXH64_reset(&self.state, _seed) != XXH_OK:

Upstream xxhash advises strongly against using XXH64_state_t with dynamic linking. If I understood the comments in xxhash.h correctly it should be fine to use a "XXH64_state_t *".

Right now this is no problem because the bundled code does not contains these ifdefs. My "test failures" were actually due to memory corruption as I messed up my pointers.

Next step to resolve this ticket would be to store only "XXH64_state_t *" in `StreamingXXH64`. Help would be appreciated (also hints if I misunderstood xxhash.h).

**Comment by FelixSchwarz** [comment]
Sorry for spamming but just after writing my last comment I think it "clicked" and I found `XXH64_createState()`/`XXH64_freeState()`. :-)

**Comment by ThomasWaldmann** [comment]
Fixed by #4602.
