### ISSUE TITLE
Can't mount repos

### ISSUE THREAD

**Issue by dudman** [borgbackup/borg#4595]
I've been having problems mounting my backups. I used to be able to mount all archives borg mount location:: mntpoint

the command completes, I can ls the mntpoint and see a list of archives, but as soon as I try and look further into the archives I get " Transport endpoint is not connected"

So I tried mounting a specific archive within a repo and get a Local Exception
```
Local Exception
Traceback (most recent call last):
  File "src/borg/archiver.py", line 4501, in main
  File "src/borg/archiver.py", line 4433, in run
  File "src/borg/archiver.py", line 1372, in do_mount
  File "src/borg/archiver.py", line 166, in wrapper
  File "src/borg/archiver.py", line 1382, in _do_mount
  File "src/borg/fuse.py", line 334, in mount
  File "src/borg/fuse.py", line 252, in _create_filesystem
  File "src/borg/fuse.py", line 391, in process_archive
  File "os.py", line 862, in fsencode
UnicodeEncodeError: 'ascii' codec can't encode character '\u0151' in position 175: ordinal not in range(128)

Platform: Linux alarm 5.1.1-1-ARCH #1 SMP PREEMPT Wed May 15 23:49:57 UTC 2019 armv7l
Linux: arch  
Borg: 1.1.10  Python: CPython 3.5.7 msgpack: 0.5.6
PID: 12470  CWD: /home/alarm/backintime/borg
sys.argv: ['borg', 'mount', '::root-2019-02-09', 'mnt']
SSH_ORIGINAL_COMMAND: None

[alarm@alarm borg]$ borg -V
borg 1.1.10

[alarm@alarm borg]$ more mount.sh 
export BORG_REPO=/home/alarm/backintime/borg/$1
#export BORG_REPO=/run/media/dudman/0cdbbfb5-6dc7-4e2e-9750-6e35c8e10c48/borg/$1

export BORG_PASSPHRASE='xxxxxxxxxx'

borg mount  ::root-2019-02-09  mnt
```

Even if I create a new repository I can list the contents but the results when mounting are the same.

Above it says msgpack 0.5.5, but pacman tells me I have 
```
pacman -Q|grep msgpack
python-msgpack 0.6.1-1
```

**Comment by ThomasWaldmann** [comment]
Note: I remove the passphrase from the script, I hope it was not your real one (if so, you might need a new one now).

msgpack: we bundled msgpack 0.5.6 into borg 1.1.10 so you have a supported version, even if your linux dist ships an unsupported version.

your problem is likely due to your locale and thus the fs encoding.

python thinks this is ascii and falls over some non-ascii filename in the archive(s) you mount.
so, set your locale to something with utf-8 and it'll work.

**Comment by dudman** [comment]
Many thanks, this is such a relief, I thought I'd lost it all, and the fix was so simple. :) of course the pasword was different, but I've changed it anyway.
Once again thanks for the great tool. If you havn't seen the GUI vorta its quite good.

**Comment by ThomasWaldmann** [comment]
I know vorta (and I did a lot of the translation code of it). Yeah, it's great for desktop user backups.
