### ISSUE TITLE
FAQ/doc updates: Provide info that deleted files are not handled on extract/restore

### ISSUE THREAD

**Issue by eharris** [borgbackup/borg#4598]
This is primarily a request for FAQ and documentation updates.

The FAQ should make it clear (probably under both the `Which file types, attributes, etc. are not preserved?` section, and `Are there other known limitations?`) that deleted files (files which did not exist in the backup being restored) are not removed if they exist in the `extract` destination.  So a restore/extract is not currently able to perform an exact "point-in-time" restore, UNLESS the destination location did not previously exist, which also requires enough spare disk space to hold an additional copy of the entire backup, and takes forever for large backups. (See #963, #1828, #1986, #2872)

A workaround for this missing functionality, which should probably be added as an additional FAQ item is:

1. Use `borg create` to create a new (temporary) archive of the current on-disk state
2. Use `borg diff` to compare the past archive with the one created in step 1
3. Parse the output from step 2 and delete any files that are listed as `removed`
4. Use `borg extract` to restore the rest of the backup
5. Use `borg delete` to remove the temporary archive created in step 1

A good comment about why this functionality isn't present yet is here: https://github.com/borgbackup/borg/issues/1986#issuecomment-335045767

**Comment by eharris** [comment]
This also helps explain (to unfamiliar users) why there is no `borg restore` verb.  It really is just `extract`ing, not restoring a prior state.

**Comment by ThomasWaldmann** [comment]
To make it even more clear:
- it **is** restoring to a prior state **if** you start from an empty directory.
- it is not transforming a directory with some arbitrary content to a prior state though.
