### ISSUE TITLE
msgpack is at supported version but borg reports an unsupported one

### ISSUE THREAD

**Issue by wsw70** [borgbackup/borg#4599]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG/ISSUE

#### Your borg version (borg -V).

local: `1.1.9`
remote: `1.1.9`

#### Operating system (distribution) and version.

Ubuntu 18.04.2 LTS

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
# /usr/bin/borg create --filter AME --list --stats ::srv-${INVOCATION_ID} /etc
Remote: You do not have a supported msgpack[-python] version installed. Terminating.
Remote: This should never happen as specific, supported versions are required by our setup.py.
Remote: Do not contact borgbackup support about this.
Connection closed by remote host. Is borg working on the server?
```

## Describe the problem you're observing.

The `msgpack` in `setup.py` which is supported is 

> ```
> install_requires = [
>     # we are rather picky about msgpack versions, because a good working msgpack is
>     # very important for borg, see: https://github.com/borgbackup/borg/issues/3753
>     'msgpack >=0.5.6, <=0.6.1',
>     # Please note:
>     # using any other version is not supported by borg development and
>     # any feedback related to issues caused by this will be ignored.
> ]
> ```
> 

On both machines (local and remote):

```
# pip install msgpack==0.5.6
Requirement already satisfied: msgpack==0.5.6 in /usr/lib/python3/dist-packages
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Both `borg` installations were done against the PPA. I am not sure if 

> This should never happen as specific, supported versions are required by our setup.py

is relevant as the installation is package-based

**Comment by ThomasWaldmann** [comment]
The 1.1.9 setup.py / the msgpack requirement looks like this:

https://github.com/borgbackup/borg/blob/1.1.9/setup.py#L42

Not sure what's wrong in your case, maybe you have installed different msgpack(-python) packages at different places (e.g. virtualenv and system wide).

But you could just use borg 1.1.10, which bundles a supported msgpack version and uses that.

**Comment by wsw70** [comment]
> Not sure what's wrong in your case, maybe you have installed different msgpack(-python) packages at different places (e.g. virtualenv and system wide).

I have only system-wide installations (no virtualenv)

> But you could just use borg 1.1.10, which bundles a supported msgpack version and uses that.

Thanks for the info. I will have to wait until the PPA catches up.

**Comment by ThomasWaldmann** [comment]
```
>>> import os
>>> os.__file__
'/home/user/.pyenv/versions/3.6.0/lib/python3.6/os.py'
```

You could try that for `msgpack` instead of `os` to see where your msgpack comes from.

(Use same user / environment / etc. as you use to invoke borg commands.)

**Comment by wsw70** [comment]
Ahhhh... My bad. On the remote

```
# pip install msgpack==0.5.6
Requirement already satisfied: msgpack==0.5.6 in /usr/local/lib/python2.7/dist-packages
# pip3 install msgpack==0.5.6
Collecting msgpack==0.5.6
  Downloading https://files.pythonhosted.org/packages/22/4e/dcf124fd97e5f5611123d6ad9f40ffd6eb979d1efdc1049e28a795672fcd/msgpack-0.5.6-cp36-cp36m-manylinux1_x86_64.whl (315kB)
    100% |████████████████████████████████| 317kB 3.9MB/s
Installing collected packages: msgpack
  Found existing installation: msgpack 0.6.0
    Uninstalling msgpack-0.6.0:
      Successfully uninstalled msgpack-0.6.0
Successfully installed msgpack-0.5.6
```

I missed the **python2.7** in `Requirement already satisfied: msgpack==0.5.6 in /usr/local/lib/python2.7/dist-packages` on the remote because `pip` is `pip3` on my local (where I double-checked).

Thanks for your help - everything works as expected now.
