### ISSUE TITLE
How do I terminate a backup?

### ISSUE THREAD

**Issue by chrissound** [borgbackup/borg#4611]
```
sudo borg create  --progress --stats --compression lz4  ~/mount/raidBackup::backup2 ~/mount/raid18t
^CKeyboard interrupt2.76 GB D 36443 N home/chris/mount/raid18t/chris/tmp/tmp/nix-shell-19886-0/.attr-0 
```
I initiated a control-C.

Do I just delete the lock file now?

```
 borg list ~/mount/raidBackup
...
borg.locking.LockFailed: Failed to create/acquire the lock /home/chris/mount/raidBackup/lock.exclusive ([Errno 13] Permission denied: '/home/chris/mount/raidBackup/lock.exclusive')
...
```

**Comment by ThomasWaldmann** [comment]
Before using `borg break-lock repo` you need to check whether a borg process is still running and accessing the repo. Only break the lock if no borg process is active any more (considering all users/machines that access this repo).

Usually a Ctrl-C should not leave a stale lock behind. What borg version is that?
