### ISSUE TITLE
Repo security_dir without location file

### ISSUE THREAD

**Issue by elho** [borgbackup/borg#4614]
I found that below `~/.config/borg/security/`, there is one directory that does not have a `location` file. It does contain these files: `key-type` `manifest-timestamp` `nonce` `tam_required`

I have no idea to which repository this may have belonged to, I was looking at all the `location` files wanting to clean up after doing countless tests with borg the last few weeks, creating and using many temporary repositories for that, most of which have been deleted since.

This is on Debian Buster, using its borgbackup 1.1.9-2 package.

**Comment by ThomasWaldmann** [comment]
The current code saves `key-type`, `location` and `manifest-timestamp` all in one go in `borg.cache.SecurityManager.save` method. So, it should be there.

But, a missing (or unreadable) `location` file does not trigger `save()` nor questions being asked about whether the location is ok. Guess this is a bug.

One can trigger rewriting all the files by removing `key-type` (just move the file somewhere else so you can compare whether contents are same after it got re-written).

**Comment by ThomasWaldmann** [comment]
@enkore ^^^ can you have a look please?

**Comment by ThomasWaldmann** [comment]
Hmm, should `known` method check for all the files created by `save` maybe?

**Comment by ThomasWaldmann** [comment]
See PR #4646.
