### ISSUE TITLE
Remove prebuild egg-info

### ISSUE THREAD

**Issue by bpereto** [borgbackup/borg#462]
Hi,

Please remove the prebuilt egg-info from the source tar.gz

borgbackup-0.28.2/borgbackup.egg-info
borgbackup-0.28.2/borgbackup.egg-info/*

**Comment by RonnyPfannschmidt** [comment]
thats a standard setuptools artifact and expected

**Comment by bpereto** [comment]
Sure, but after setup.py build is run and not already delivered in the release source tgz?

**Comment by RonnyPfannschmidt** [comment]
uhm nope, setuptools adds it to the sdist, its expected

**Comment by bpereto** [comment]
alright, removing it manually in the spec file (for packaging in rpm)
