### ISSUE TITLE
--exclude doesn't seem to exclude folders

### ISSUE THREAD

**Issue by matcharles** [borgbackup/borg#4627]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

v1.1.10

#### Operating system (distribution) and version.

Arch

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

    #!/bin/bash
    REPOSITORY=`hostname`-`date +%Y%m%d`

    # Backup of /home /var /data /etc /boot
    sudo borg create -v --stats --progress          \
	    /data/backups/hostname::$REPOSITORY    \
        /home                                       \
        /var	                                    \
        /data										\
        /etc										\
        /boot
        --exclude /home/*/.cache                  \
        --exclude /home/*/.local					\
        --exclude /data/backups				    \
        --exclude /data/vms					    

## Describe the problem you're observing.

I just realised that the exclude do not seem to exclude the files. I am seeing the backup run and I can see it processing files in the folders above. I have tried numerous ways of writing it

    '--exclude '/home/*/.cache' \'
    '--exclude 'home/*/.cache' \'
    '--exclude '/home/*/.cache/' \'
    '--exclude home/*/.cache \'

And none of them seem to change the behavior. I suspect I am using the 'exclude' switch wrong, but from what I have seen in the wiki that's the correct use?

**Comment by matcharles** [comment]
Disregard, forgot and escape backslash before the '--exclude' option :-1:

**Comment by ThomasWaldmann** [comment]
Your profile pic looks familiar. :D
