### ISSUE TITLE
Improve missing/broken "chunk" file handling

### ISSUE THREAD

**Issue by 0-wiz-0** [borgbackup/borg#4628]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.9
#### Operating system (distribution) and version.
NetBSD/8.99.42/amd64/pkgsrc
#### Hardware / network configuration, and filesystems used.
Not relevant.
#### How much data is handled by borg?
Not relevant.
#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create --stats $REPOSITORY::name-`date +%Y-%m-%d` some paths ---exclude some --exclude excludes

## Describe the problem you're observing.
A recent reset broke the "chunk" file. borg does not recover nicely from it.
I see:
````
Enter passphrase for key $REPOSITORY 
Killed stale lock localhost@207732466274344.9335-0.
Removed stale exclusive roster lock for host localhost@207732466274344 pid 9335 thread 0.
Removed stale exclusive roster lock for host localhost@207732466274344 pid 9335 thread 0.
File failed integrity check: /home/wiz/.cache/borg/some_hex/chunks
````
`borg check` was happy with the remote repository, just the local cache is broken.

Moving the "chunks" file away doesn't cause borg to recreate it:
````
Enter passphrase for key $REPOSITORY: 
Killed stale lock localhost@207732466274344.23341-0.
Removed stale exclusive roster lock for host localhost@207732466274344 pid 23341 thread 0.
Removed stale exclusive roster lock for host localhost@207732466274344 pid 23341 thread 0.
Local Exception
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.7/site-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/pkg/lib/python3.7/site-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/pkg/lib/python3.7/site-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/pkg/lib/python3.7/site-packages/borg/archiver.py", line 550, in do_create
    cache_mode=args.files_cache_mode, ignore_inode=args.ignore_inode) as cache:
  File "/usr/pkg/lib/python3.7/site-packages/borg/cache.py", line 380, in __new__
    return local()
  File "/usr/pkg/lib/python3.7/site-packages/borg/cache.py", line 374, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/pkg/lib/python3.7/site-packages/borg/cache.py", line 457, in __init__
    self.open()
  File "/usr/pkg/lib/python3.7/site-packages/borg/cache.py", line 505, in open
    self.rollback()
  File "/usr/pkg/lib/python3.7/site-packages/borg/cache.py", line 610, in rollback
    self._do_open()
  File "/usr/pkg/lib/python3.7/site-packages/borg/cache.py", line 494, in _do_open
    integrity_data=self.cache_config.integrity.get('chunks')) as fd:
  File "/usr/pkg/lib/python3.7/site-packages/borg/crypto/file_integrity.py", line 129, in __init__
    self.file_fd = override_fd or open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wiz/.cache/borg/some_hex/chunks'
````
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, happens every time with the currently broken "chunks" file.

I was told that `borg delete --cache-only $REPOSITORY` is a workaround, haven't tried that yet. It would be nice to indicate this in the error message, or make borg recreate the chunks file when it's missing.

**Comment by 0-wiz-0** [comment]
`borg delete --cache-only $REPOSITORY` did indeed fix the problem for me.

**Comment by ThomasWaldmann** [comment]
Hmm, guess I won't add an "automatic fixing" for this.

The above workaround works and so at least you'll notice that you lost a local file.
