### ISSUE TITLE
Documentation: script fails with "Invalid location format: "::{hostname}-{now}""

### ISSUE THREAD

**Issue by jans23** [borgbackup/borg#4629]
When using [this script](https://borgbackup.readthedocs.io/en/1.1-maint/quickstart.html#automating-backups) from the Borg documentation on Ubuntu Linux (bash shell) it fails with the following error:
`borg create: error: argument ARCHIVE: Invalid location format: "::{hostname}-{now}"`

**Comment by ThomasWaldmann** [comment]
We need the FULL command line you actually have run, the borg version, operation system, etc.

**Comment by jans23** [comment]
```
borg create                         \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    ::'$(hostname)-$(date --iso-8601)'            \
    '/home/me'                       \
```

Note: I changed `{hostname}-{now}` to `$(hostname)-$(date --iso-8601)` from the original script.

**Comment by jans23** [comment]
I solved the issue. It was caused by `BORG_REPO` lacking the SSH port.

**Comment by jans23** [comment]
Still I had to change the [script](https://borgbackup.readthedocs.io/en/1.1-maint/quickstart.html#automating-backups) from `'{hostname}-{now}'` to `"$(hostname)-$(date --iso-8601)"` (note the different quotations marks).

**Comment by ThomasWaldmann** [comment]
The original script (copied from 1.1.10 docs) does it like that:
```
export BORG_REPO=ssh://username@example.com:2022/~/backup/main

borg create                      \
    ... (some options) ...       \
    ::'{hostname}-{now}'         \
    /home
```

Note:
- there is no `$` before `{hostname}` because borg expands that value (we are **not** calling the `hostname` shell command). same for `{now}` (not calling the `date` shell command). see the placeholders help.
- if you let borg expand that and you don't try to call shell commands, the single quotes should be ok.
- if you want to rather call shell commands or expand shell variables, you must not use singles quotes, but you need double quotes to let that happen.

So, the script in the docs works differently that yours, but IMHO it is correct.

**Comment by ThomasWaldmann** [comment]
Also, the ssh port spec in the `BORG_REPO` env var can be left away and it would default to 22 then.

The example repo from the docs then would look like:
```
export BORG_REPO=ssh://username@example.com/~/backup/main
```

I removed `:2022`, so it uses the default 22 now.

**Comment by jans23** [comment]
Thanks for clarifying about` {hostname}` and `{now}`.

I used `ssh://username@example.com:/~/backup/main`. Note the `:` which I'm used to from the command line and which caused this issue with Borg.

**Comment by ThomasWaldmann** [comment]
Hmm, I think the `:` belongs to the port, so it is a bug to give it without a port.

OTOH, the parser could still default to 22 if there is a `:` without a port number after it. Makes the already complex url parsing a little bit more complex...

**Comment by jans23** [comment]
The funny thing is I just tried [Vorta](https://github.com/borgbase/vorta/) and it seems to demand a `:` in the repository URL even without port number.

**Comment by ThomasWaldmann** [comment]
@m3nu ^ i thought vorta just passes the repo url through to borg? can you confirm?

**Comment by m3nu** [comment]
> @m3nu ^ i thought vorta just passes the repo url through to borg? can you confirm?

For remote repos we check if there is a `:` anywhere (`ssh://`, `:repo`, etc). Otherwise Borg will treat it as local folder, which is not desired when "remote repo" is selected.

Apart from that it's just passed through, yes.
