### ISSUE TITLE
Feature request: Better tools to analyze disk space usage

### ISSUE THREAD

**Issue by aradis** [borgbackup/borg#4632]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature request

Currently, seeing what is using up disk space in a borg repository is difficult. I think this is fairly self-evident to anyone that has tried to do so, but I can provide examples if needed.

I believe `borg list` does provide all of the information necessary to analyze disk space usage, however in order to do so the user has to:

- Keep a local set of `borg list` output for each archive.
- Write fairly sophisticated scripts to analyze the data. For example, out of 100 archives there may be 3 consecutive archives that contain a large file that when deleted via `borg recreate` would free up significant space. The programming ability and effort required to write such analysis scripts is non-trivial.

Due to the variety of ways people use borg repositories, and how they may wish to analyze the data and find actionable ways to free up space, my suggestion would be for borg to facilitate keeping copies of complete `borg list` JSON data for each archive, e.g.

`borg create --keep-details`

would store the information in ~/.local/borg/details/ or \<repo\>/details/, and

`borg generate-details [archive criteria]`

would ensure each matching archive has an up-to-date and non-corrupt details file.

Then users could share their favorite scripts and one-liners for analyzing the data.

As for implementing this in borg, just a few thoughts:

- The details could be stored either in the repository itself or locally on the client. I think storing it in the repository would be more consistent with borg's repository-wide config but would make analysis of remote repositories slow. Maybe have a `sync-details` command that would download the data for faster local analysis?
- There could be an index file that stores the expected hash for each JSON file, to allow checking for corrupt files.
- Commands that modify archive contents such as `borg recreate` should check if a details file exists for the archive, and regenerate it if so.
- Commands that delete archives such as `borg delete` and `borg prune` should also delete the corresponding details file.
- Having this data could potentially speed up commands such as `borg diff`, although I think in most circumstances users would want to consult the archives directly to ensure the most accurate results.

**Comment by ThomasWaldmann** [comment]
I don't quite see the point of this.

In a borg repo, there is a per-archive metadata stream that has all the metadata which you then can output via borg list or use otherwise. So why should the same information be kept at an additional place, adding a lot of management overhead?

If someone would like to write code to do an analysis bases on that metadata, they can already do it and just make a pull request against borg.

**Comment by aradis** [comment]
1. Performance
2. Standardizes analysis scripts
3. Simplifies analysis scripts

For me, with 1.1.10 on a fast client with a local repo on SSD, `borg list` on a nominally 500GB archive takes 80s with the default `--format`. With a `--format` containing all of the keys, it takes.. well, over an hour so far and still running.

Even if `borg list` could be optimized to take only 10s or 5s or even 1s, that is still hours or days for a repository that has thousands of archives. And that's just to get the metadata for one analysis. If a user wants to take a look at a subset of archives or any other type of subsequent query, the script would need to fetch that metadata all over again.

At some point either borg or the analysis script will need to write local copies of the metadata. With local copies it may still take a while to read all of the metadata in, but that would be minutes and not hours or days.

Having borg write the local copies means all scripts will be able to access the files in a standard format in a known location.  If each script has to write the files itself that means extra development effort and incompatibility between scripts. Having the JSON files available also allows for simple types of analysis using `jq` or similar tools.

A simpler option would be a single `sync-metadata` command that dumps the metadata into local files. And analysis scripts could say "make sure to run `sync-metadata` before running the analysis". For efficiency, `borg create` could still have an option to dump the metadata after creating the archive. You'd still have the issue of metadata for deleted archives hanging around and outdated metadata that wasn't updated when doing a `borg recreate`, but that should be easy enough to check for as part of a `sync-metadata` run. While I still prefer the outline in my original comment, just having a single `sync-metadata` command fulfills the criteria of being able to make and share fast(ish) disk space analysis scripts.

**Comment by ThomasWaldmann** [comment]
Considering `borg list` with **all the keys** being slow: some stuff is computed on demand (and not just read from metadata) when you use the specific placeholder, so better only request what you really need.

Besides that, I still don't see the point. This feature request looks like a premature optimisation / preparation for a hypothetical analysis scripts that does not even exist yet.

So I'ld suggest first writing the analysis script and if it is interesting we can then look into making it faster.

**Comment by aradis** [comment]
I think my suggestion about the metadata cache derailed this feature request. I'll add a new issue that simply requests better disk space analysis tools without any suggestion about how to accomplish that.

I'll leave an example script below in case that might be useful to anyone that comes across this bug.

---

```
    rm -f /tmp/json

    for archive in `borg list my_repo | cut -d' ' -f1`
    do
        borg info my_repo::"$archive" >> /tmp/json
    done

    jq -r --tab '.archives[0].name + " " + (.archives[0].stats.original_size/1024/1024/1024|floor|tostring) + "GB " + (.archives[0].stats.compressed_size/1024/1024/1024|floor|tostring) + "GB " + (.archives[0].stats.deduplicated_size/1024/1024|floor|tostring) + "MB"' /tmp/json | column -t

    archive-2018-01-01  100GB  80GB   6MB
    archive-2018-01-02  101GB  80GB   15MB
    archive-2018-01-03  101GB  80GB   7MB
    archive-2018-01-04  101GB  80GB   3MB
    archive-2018-01-05  101GB  80GB   8MB
    archive-2018-01-06  101GB  80GB   13MB
```

That provides the total size, compressed size, and deduplicated size of each archive. Getting the data necessary for a more detailed analysis is currently slow.
