### ISSUE TITLE
"FUSE version too old" error when installing borg on macOS

### ISSUE THREAD

**Issue by russelldavis** [borgbackup/borg#4639]
On macOS, when installing borg via pip using `pip install borgbackup[fuse]`, or manually installing its requirements using `pip install -r requirements.d/fuse.txt`, installation fails with the following error:

```
error: FUSE version too old, 2.9.0 or newer required
```

I tracked this down -- it's caused by osxfuse's [compatibility layer](https://github.com/osxfuse/osxfuse/wiki/FAQ#13-what-is-the-macfuse-compatibility-layer-do-i-need-it) being installed (which adds a set of older, incompatible header files at `/usr/local/include/fuse` that take precedence over the newer ones at `/usr/local/include/osxfuse`).

The osxfuse installer does not install the compatibility layer by default, however the homebrew cask formula does. I've [opened a PR](https://github.com/Homebrew/homebrew-cask/pull/65213) to change that, but I figured it would also be helpful to have an issue here documenting the problem and the workaround.

So, if you are running into this problem: uninstall osxfuse, then reinstall it without the compatibility layer. ~~Until the PR above gets merged, that means installing outside of homebrew (or manually editing the formula).~~ **Update:** the PR has been merged, so you can now just run `brew cask reinstall osxfuse`.

Feel free to close this issue since I don't think there's anything to be done on borg's side. (You could potentially add a note about this to the docs at https://borgbackup.readthedocs.io/en/stable/installation.html, but this issue being discoverable may be good enough.)

**Comment by ThomasWaldmann** [comment]
Do we still need to document something?

If osxfuse is fixed now (in brew cask) and someone installs it now, there won't be a problem, right?

I also never had a problem with directly installing osxfuse (using their release downloads from github).

**Comment by russelldavis** [comment]
> If osxfuse is fixed now (in brew cask) and someone installs it now, there won't be a problem, right?

Yep, that's right. 

> I also never had a problem with directly installing osxfuse (using their release downloads from github).

Same. That installer does give you an option (off by default) to install the compatibility layer, so anyone enabling that option would still run into this problem.

Up to you on whether to update the docs for those folks, and anyone who installed via homebrew before today. (The homebrew fix and this issue being searchable now should go a long way.)

**Comment by ThomasWaldmann** [comment]
guess this can be closed.
