### ISSUE TITLE
How to get paths which was backuped

### ISSUE THREAD

**Issue by BulatSaif** [borgbackup/borg#4644]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## Describe the problem you're observing.

I wold like to delete or move existing folders before extract the backup. But I can not find the way how to get list of backuped paths. `borg list` prints files. 

For example, I created  backup:
```
borg create /path/to/repo::archive1 /opt/app1 /opt/app2 /opt/...  --exclude '*.tmp'
```
`/opt/app1 /opt/app2 /opt/...` - is dynamic and generated by script.

Is it possible to run `borg` command on existing archive  and get output like: `/opt/app1 /opt/app2 /opt/...`?

I can run `borg info /path/to/repo::archive1` and see the `Command line:` with all paths what was backup. And `borg list  /path/to/repo::archive1` - prints the files, but i need only the paths. 
How can I get the path from existing backup or only options is to parse the `Command line:`  from `borg info`?

**Comment by ThomasWaldmann** [comment]
There is only the `Command line:`, which you already found.

**Comment by BulatSaif** [comment]
@ThomasWaldmann , Thanks for the quick response, do you have any hints how to parse `Command line:`?  It can be very complicated.

**Comment by ThomasWaldmann** [comment]
Well, maybe the easiest way would be to remember the paths at borg create time.

You said you automatically create the list of paths and the give it to borg, you also could save them to a local file just before/after that.

borg parses the command give to it using python's `argparse` library (see `src/borg/archiver.py`) and yes, it can be rather complex.

**Comment by BulatSaif** [comment]
> Well, maybe the easiest way would be to remember the paths at borg create time.

Yes, it was my firs idea. And I start to save path in `comment` field  via `--comment` parameter 
and it  easy to extract:
```
COMMENT=$(borg info --json $ARCHIVE | python3 -c "import sys,json; print(json.load(sys.stdin)['archives'][0]['comment'])")
```

but I also wanted to test old backups, what do not have the comment field.
If anyone finds this issue, here my dirty way to parse the `Command line:` :
```bash
    ARCHIVE="/path/to/repo::archive1"

    # Get borg 'Command line:' from archive info
    cmd=$(borg info --json $ARCHIVE | python3 -c "import sys,json; print(json.load(sys.stdin)['archives'][0]['command_line'])")

    # find the index of  ARCHIVE +1 argument 
    INDEX=$(python3 -c "print([i for i, s in enumerate($cmd) if '$ARCHIVE' in s][0]+1)")

    # extrtact all argument between  $ARCHIVE and the next argument what starts with '-' (or unti the end)
    # it should be the paths
    DIRS=$(python3 -c "print('\n'.join($cmd[$INDEX:next((i for i in enumerate($cmd[$INDEX:]) if i[1].startswith('-')),[len($cmd[$INDEX:]),-1])[0]+$INDEX]))")

    # also parse all exclude
    EXCLUDE=$(python3 -c "print('\n'.join([v for k, v in zip($cmd,$cmd[1:]) if '--exclude' in k]))")

    # you can get `comment` from `$(borg info --json)['archives'][0]['comment']` or like this:
    COMMENT=$(python3 -c "print(''.join([v for k, v in zip($cmd,$cmd[1:]) if '--comment' in k][-1:]))")
```
