### ISSUE TITLE
Default Cron Script Fails: borg create: error: argument ARCHIVE: "operation": No archive specified

### ISSUE THREAD

**Issue by gaia** [borgbackup/borg#4649]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question (bug?)

## System information. For client/server mode post info for both machines.

borg-linux64 1.1.10

#### Operating system (distribution) and version.

Debian 9.9/Proxmox: 4.15.18-16-pve SMP PVE 4.15.18-41 x86_64

#### Hardware / network configuration, and filesystems used.

N/A

#### How much data is handled by borg?

<2GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

https://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups

## Describe the problem you're observing.

```
./borg.sh
borg create: error: argument ARCHIVE: "operation": No archive specified
terminating with success status, rc 0
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes

####

Borg binary from https://github.com/borgbackup/borg/releases.
Binary is root:root 0755 in a separate drive, symlinked as
`/usr/local/bin/borg -> /mnt/storage/backup-tools/borg-linux64`
`borg` by itself and `init` work fine.

Actual script:

```
#!/bin/sh

export BORG_REPO=/mnt/storage/backups/borg

export BORG_PASSPHRASE='xxxxxxx'

export BORG_PASSCOMMAND='pass show backup'

info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

borg create                         \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --exclude '/home/*/.cache/*'    \
    --exclude '/var/cache/*'        \
    --exclude '/var/tmp/*'          \
    --exclude '/mnt/storage/*'      \
    --exclude '/mnt/containers/*'   \
    --exclude '/mnt/usb/*'          \
    --exclude '/mnt/bindmounts/*'   \
    --exclude '/zfs_containers2/*   \
    --exclude '/dev/*'              \
    --exclude '/media/*'            \
    --exclude '/proc/*'             \
    --exclude '/sys/*'              \
    --exclude '/tmp/*'              \
    --exclude '/var/run/*'          \
    --exclude '/var/lock/*'         \
                                    \
    ::'{hostname}-{now}'            \
    /                               \

backup_exit=$?

info "Pruning repository"

borg prune                          \
    --list                          \
    --prefix '{hostname}-'          \
    --show-rc                       \
    --keep-daily    7               \
    --keep-weekly   2               \
    --keep-monthly  1               \

prune_exit=$?

global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))

if [ ${global_exit} -eq 0 ]; then
    info "Backup and Prune finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup and/or Prune finished with warnings"
else
    info "Backup and/or Prune finished with errors"
fi

exit ${global_exit}
```

**Comment by ThomasWaldmann** [comment]
I don't see an obvious error in the script, so just some comments what I noticed:

"Borg 2.5 binary" what do you mean by that? You stated it is 1.1.10.

```
export BORG_PASSPHRASE='xxxxxxx'
export BORG_PASSCOMMAND='pass show backup'
```
You only need one of them (and the latter one only if you use the `pass` password manager to manage your borg passphrase).

Is `/bin/sh` a `bash` shell for you? Can you try if `/bin/bash` works better?

Can you make sure there is no trailing whitespace at your line endings?

**Comment by gaia** [comment]
`/bin/bash`

updated to `export BORG_PASSCOMMAND='backup'`, still same error

PS: 2.5 is ReaR, sorry. updated the OP

**Comment by ThomasWaldmann** [comment]
Why is that correct?

**Comment by gaia** [comment]
sorry, I meant to say I corrected the OP, it is not v2.5 (that's the version of ReaR)

**Comment by ThomasWaldmann** [comment]
A single quote after zfs_containers is missing.

**Comment by ThomasWaldmann** [comment]
> updated to export BORG_PASSCOMMAND='backup', still same error

Why is that correct?

**Comment by gaia** [comment]
gotcha. `export BORG_PASSPHRASE='xxxxxxx'` is the only line i have now between those two.

and I apologize for wasting your time with the missing single quote. it works now!
