### ISSUE TITLE
borg upgrade for remote repositories missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#465]
Remote repo upgrade is missing still. Also the code needs to be refactored to not assume everything is local.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/28855643-borg-upgrade-call-for-remote-repositories)

**Comment by ThomasWaldmann** [comment]
TODO: document this limitation until it is solved.

**Comment by galets** [comment]
I might be missing something, but is there currently no way to upgrade attic repository without giving passphrase to remote server?

**Comment by enkore** [comment]
There is an updated description here, based on what the upgrader does: http://borgbackup.readthedocs.io/en/latest/faq.html#migrating-from-attic

**Comment by galets** [comment]
I'm not sure how to interpret this... What it says is: 

> Thus, to upgrade a “passphrase” attic repo to a “repokey” borg repo, 2 steps are needed, in this order
> 
> borg upgrade repo
> borg key migrate-to-repokey repo

There is no command "borg key migrate-to-repokey". I tried importing key I created for different repo, but naturally it didn't work. Is there an un-documented command?

**Comment by enkore** [comment]
Sorry, I sent you to the "latest" docs where that command has been moved. In 1.0 it's called "borg migrate-to-repokey".

**Comment by galets** [comment]
Yeah, my bad... I was reading the documentation at https://borgbackup.readthedocs.io/en/stable/usage.html# and there hasn't been a section on `borg migrate-to-repokey` command, but when I ran `borg --help` there was one. Also, the attic migration documentation mentions `borg key migrate-to-repokey`, which doesn't exist - that's what got me confused

**Comment by galets** [comment]
... perhaps if that section gets updated, you won't need to implement the feature after all. My issue was that I was under assumption that `borg upgrade` command had to be executed with a passphrase, which I didn't want to do on remote ssh server, cuz, you know, opsec. But since it doesn't need to happen, there shouldn't be an issue

**Comment by ThomasWaldmann** [comment]
Just to keep the idea (not sure if we really want to do it that way):
- if the repository code would do the upgrade, it would work for remote repos.
- `borg check` and / or `recover_segment()` could transform an attic segment file to a borg segment file.

But:
- would make repository code even more complex

**Comment by ThomasWaldmann** [comment]
closing due to #5230.

**Comment by ThomasWaldmann** [comment]
reopening, see #5230.
