### ISSUE TITLE
haskell port ?

### ISSUE THREAD

**Issue by simonmichael** [borgbackup/borg#4651]
Ok I'll be that person.. it doesn't hurt to ask.. I hope! @ThomasWaldmann, @jborg and other attic/borg devs: I'm loving this tool so far - thank you very much. By any chance, do you ever think about a version built in a more typesafe language, such as Haskell ? 

Here's a little more context:

> sm: I wish https://www.borgbackup.org was built in haskell.
> Rembane: Why?
> sm: although it's really good, it's really disconcerting to see random python tracebacks from normal usage
> sm: I'd have more faith in a haskell version
> Rembane: I haven't gotten any so far, but maybe you have a more interesting use case than I have.
> sm: currently I'm just trying to use borg recreate, and KeyError 'data' for no obvious reason
> sm: brings back my former life as a pythonista !
> Rembane: That sounds like a nerve wracking experience.
> sm: well I'll get over it :) But backups are already stressful, ideally the tool would be bulletproof

I'll report the recreate issue. [#4652]

**Comment by simonmichael** [comment]
PS: I know, rewrites almost never make sense. But maybe backup software is special.. and speaking as someone who maintained a python codebase for 10 years (@ThomasWaldmann: remember Zwiki ?) and then a haskell one for 11 years, happily..

**Comment by ThomasWaldmann** [comment]
About seeing tracebacks now and then:

I rather have a traceback with lots of useful info (for developers) than a nice pretty nothing-saying error message with too little info. This is especially true for stuff that might not be reproducible or taking hours to reproduce.

About porting to other languages: I like Python, so I don't have much interest in that.

The only things where I might be slightly interested in alternatives are the borg parts that currently use `C`, but only if the tooling / integration is less-or-equal painful / portable than what we have now. As these parts aren't too big and neither they are too complex, the need of having them ported is not very high.

As a hint for people who don't like their backup tool being in Python: there is `restic` and it is implemented in Go. Its working principles are quite similar to what borg does. It's a younger project, so it might be more modern in some places, but also more incomplete in others.

**Comment by domenkozar** [comment]
The irony is strong: https://github.com/borgbackup/borg/issues/4681
