### ISSUE TITLE
"Original size" of backup is twice that of the source folder

### ISSUE THREAD

**Issue by kaysond** [borgbackup/borg#4654]
## Summary
Doing a backup of a ~56GB folder yields an "Original Size" of 109GB, a "Compressed Size" of 96.99GB and a "Deduplicated Size" of 53GB. There is no other backup with this prefix, and all other backups from this source were deleted prior to the test.

It may just be a reporting error, but its still concerning that compressed size is significantly larger than the original, and deduplicated is only slightly smaller, especially given the zstd compression.

## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

## System information. For client/server mode post info for both machines.
Client: Custom AMD Desktop PC
Server: Raspberry Pi 3B

#### Your borg version (borg -V).
Client: 1.1.5
Server: 1.1.8

#### Operating system (distribution) and version.
Client: Ubuntu 18.04.2
Server: Raspbian 9.9

#### Hardware / network configuration, and filesystems used.
Sent over the internet via ssh (default ssh options)
Filesystem is ext4 on both ends

#### How much data is handled by borg?
500GB de-duped

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
See below

## Describe the problem you're observing.
The reported "Original size" of the archive after backup is nearly twice the size of the actual contents of the directory that was backed up

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
This consistently happens with all backups to varying degree

#### Include any warning/errors/backtraces from the system logs
```
administrator@fserver:/var/www/files/Backups/Aram$ du -sh /var/www/files/Backups/Aram/WindowsBackup
56G     /var/www/files/Backups/Aram/WindowsBackup
administrator@fserver:/var/www/files/Backups/Aram$ sudo -H offsite-backup create aramdesk /var/www/files/Backups/Aram/WindowsBackup/
administrator@fserver:/var/www/files/Backups/Aram$ sudo -H offsite-backup info -P aramdesk
Archive name: aramdesk-2019-06-28T14:12:11
Archive fingerprint: cb12b51e42d43e77b1e917dc640572372085eb25750ea6fa04b66adc20518ece
Comment:
Hostname: fserver
Username: root
Time (start): Fri, 2019-06-28 14:12:17
Time (end): Fri, 2019-06-28 21:45:22
Duration: 7 hours 33 minutes 4.65 seconds
Number of files: 11530
Command line: /usr/bin/borg create --verbose --compression zstd,10 '::aramdesk-{now}' /var/www/files/Backups/Aram/WindowsBackup/
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              109.00 GB             96.99 GB             53.75 GB
All archives:              566.50 GB            434.57 GB            356.77 GB

                       Unique chunks         Total chunks
Chunk index:                  996558              1152685
```
Note `offsite-backup` just sets envvars and calls `borg` with some added params

**Comment by ThomasWaldmann** [comment]
This is a cosmetic bug, search for the existing ticket (closing this as duplicate).

**Comment by kaysond** [comment]
@ThomasWaldmann you mean #3224?  I saw that but it appeared to have been patched in 2017 and 1.1.5 was released long after...

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/3522

https://github.com/borgbackup/borg/issues/3690

https://github.com/borgbackup/borg/issues/3736

**Comment by kaysond** [comment]
Thank you. Explains why searching for "original size" didn't come up with any results. In any case, upgrading to v1.1.10 on client and server resolved the issue.
