### ISSUE TITLE
Borg check on deleted archive does a lot of job only to discard it. 

### ISSUE THREAD

**Issue by Barafu** [borgbackup/borg#4657]
## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

1.1.10

#### Operating system (distribution) and version.

Arch, n/a

#### Hardware / network configuration, and filesystems used.

btrfs locally, NFS 3 for repo. 

#### How much data is handled by borg?

5Gb 

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
> borg delete /storage/data/Backups::testbooks2
> borg check /storage/data/Backups::testbooks2
Archive 'testbooks2' not found.
Archive consistency check complete, problems found.
```

## Describe the problem you're observing.

Running "check"  with deleted archive causes `borg` to do a check of everything,  then report that archive is missing. 
I think that "check" on a missing archive should fail immediately, rather then performing check on other archives. If a user wanted a whole repo check, he would say so.

**Comment by ThomasWaldmann** [comment]
Sounds weird, I'll have a look...

**Comment by Barafu** [comment]
I tested it again. Well, it does not check all repo, but certainly there is a huge delay before telling me that archive does not exist.

**Comment by ThomasWaldmann** [comment]
`-v` gives more info about this:
```
$ borg check -v repo::existing
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Enter passphrase for key borg/repo: 
Analyzing archive existing (1/1)
Orphaned objects check skipped (needs all archives checked).
Archive consistency check complete, no problems found.
```

Here it checked first the repo, then the existing archive, all ok, no problems.

```
$ borg check -v repo::notexisting
Starting repository check
Starting repository index check
Completed repository check, no problems found.
Starting archive consistency check...
Enter passphrase for key borg/repo: 
Archive '2' not found.
Orphaned objects check skipped (needs all archives checked).
Archive consistency check complete, problems found.
```
Here it also checked the repo first (ok), then didn't find the given archive (-> problem).

**Comment by ThomasWaldmann** [comment]
I don't think anything should be changed here.

The special problem with "check" is that we can't assume everything being fine when it is started, so we first need to do the low-level check (and repair, if `--repair` is given), then the higher-level archive check (and repair ...).

If you want to somehow rely on the repo being in a relatively good state, guess you could do a `borg check --archive-only repo::archive` - that would fail quicker as it does not do the low-level check first.
