### ISSUE TITLE
borg upgrade also upgrades the backup repo

### ISSUE THREAD

**Issue by jdchristensen** [borgbackup/borg#466]
It uses hardlinks to create a backup repo, but then updates the files in place,
which doesn't break the hardlinks.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/28861170-borg-upgrade-also-upgrades-the-backup-repo)

**Comment by anarcat** [comment]
are you sure? did you conclude this from reading the source or from running the upgrade directly?

there's a unit test that verifies that we operate on a copy of the hardlink here:

https://github.com/borgbackup/borg/blob/master/borg/testsuite/upgrader.py#L188

**Comment by jdchristensen** [comment]
I tested this with the released version of borg, and the hardlinks weren't broken.

**Comment by anarcat** [comment]
On 2015-12-04 14:40:48, Dan Christensen wrote:
> I tested this with the released version of borg, and the hardlinks weren't broken.

Can you provide a more obvious way to reproduce? Did you run with
--inplace?

Thanks

**Comment by jdchristensen** [comment]
$ attic init test2.attic
    Initializing repository at "test2.attic"
    Encryption NOT enabled.
    Use the "--encryption=passphrase|keyfile" to enable encryption.
    Initializing cache...
    
    $ attic create test2.attic::1 foo
    
    $ ./borg-linux64 upgrade test2.attic
    making a hardlink copy in /tmp/jdc/test2.attic.upgrade-2015-12-04-15:31:33
    opening attic repository with borg and converting
    no key file found for repository
    converting index index b'/tmp/jdc/test2.attic/index.2'
    copying attic cache file from /home/jdc/.cache/attic/1b8ffdb91a5cefae0af6b7ec4a3a9ebcd0ff22aa0e497a0705796a679ee2f95d/config to /home/jdc/.cache/borg/1b8ffdb91a5cefae0af6b7ec4a3a9ebcd0ff22aa0e497a0705796a679ee2f95d/config
    copying attic cache file from /home/jdc/.cache/attic/1b8ffdb91a5cefae0af6b7ec4a3a9ebcd0ff22aa0e497a0705796a679ee2f95d/files to /home/jdc/.cache/borg/1b8ffdb91a5cefae0af6b7ec4a3a9ebcd0ff22aa0e497a0705796a679ee2f95d/files
    copying attic cache file from /home/jdc/.cache/attic/1b8ffdb91a5cefae0af6b7ec4a3a9ebcd0ff22aa0e497a0705796a679ee2f95d/chunks to /home/jdc/.cache/borg/1b8ffdb91a5cefae0af6b7ec4a3a9ebcd0ff22aa0e497a0705796a679ee2f95d/chunks
    converting cache /home/jdc/.cache/borg/1b8ffdb91a5cefae0af6b7ec4a3a9ebcd0ff22aa0e497a0705796a679ee2f95d/chunks
    converting 1 segments...
    converting segment 1/1, 100.00% done (/tmp/jdc/test2.attic/data/0/2)
    
    $ ls -l test2.attic*/index.2
    -rw-rw---- 2 jdc jdc 40978 Dec  4 15:31 test2.attic/index.2
    -rw-rw---- 2 jdc jdc 40978 Dec  4 15:31 test2.attic.upgrade-2015-12-04-15:31:33/index.2
    
    $ ls -i test2.attic*/index.2
    6700175 test2.attic/index.2
    6700175 test2.attic.upgrade-2015-12-04-15:31:33/index.2

The two index.2 files have the same inode number.

Ah, but now I see that the data files are different, so in that case the hardlinks are broken.

**Comment by jdchristensen** [comment]
Here's an approach that would be safer, and still allow progress reporting.

When --inplace is given, do things the way they are currently done.

Without --inplace, require the user to specify the name of the new borg repo to be created.
Then, go through the attic repo one file at a time and write the converted file to the new borg repo.
Then there's no chance that the attic repo will get corrupted.  Moreover, it will work across 
filesystems, which might be a common situation for a large repo.

**Comment by anarcat** [comment]
On 2015-12-04 15:37:42, Dan Christensen wrote:
> The two index.2 files have the same inode number.

Okay, so only the index files are affected. That is a bug.

> Ah, but now I see that the data files are different, so in that case the hardlinks are broken.

Phew! At least those work. :)

On 2015-12-04 16:08:10, Dan Christensen wrote:
> Here's an approach that would be safer, and still allow progress reporting.
>
> When --inplace is given, do things the way they are currently done.
>
> Without --inplace, require the user to specify the name of the new borg repo to be created.
> Then, go through the attic repo one file at a time and write the converted file to the new borg repo.
> Then there's no chance that the attic repo will get corrupted.  Moreover, it will work across 
> filesystems, which might be a common situation for a large repo.

That  could work. I guess I got carried away with the hardlink
approach... I think the hardlink approach is still faster than copying
the whole file, especially with COW filesystems like ZFS or BTRFS,
because the file *won't* need to be completely copied from scratch...

But yeah, this would probably be safer and work across filesystems...

**Comment by ThomasWaldmann** [comment]
I upgraded a attic repo to borg, using `borg upgrade repo` (not in-place):
```
tw@tux:~/w/borg$ ls -li repo*
repo:
2267577 -rw-rw-r-- 2 tw tw   148 Dec  7 18:49 config
2330626 drwxrwxr-x 3 tw tw  4096 Dec  7 18:49 data
2267586 -rw-rw-r-- 2 tw tw    32 Dec  7 18:51 hints.2
2267587 -rw-rw-r-- 2 tw tw 40978 Dec  7 18:52 index.2
2267582 -rw------- 2 tw tw    31 Dec  7 18:52 lock.roster
2267576 -rw-rw-r-- 2 tw tw    28 Dec  7 18:49 README

repo.upgrade-2015-12-07-18:52:06:
2267577 -rw-rw-r-- 2 tw tw   148 Dec  7 18:49 config
2821173 drwxrwxr-x 3 tw tw  4096 Dec  7 18:49 data
2267586 -rw-rw-r-- 2 tw tw    32 Dec  7 18:51 hints.2
2267587 -rw-rw-r-- 2 tw tw 40978 Dec  7 18:52 index.2
2267582 -rw------- 2 tw tw    31 Dec  7 18:52 lock.roster
2267576 -rw-rw-r-- 2 tw tw    28 Dec  7 18:49 README
```
As one sees at the filenames and the inode numbers at the left, there are the following issues:
- a lock.roster file is created in the attic repo backup that was not there before (attic does not use that file). that's a minor issue, but a little unclean.
- the repo/README is still the same and says `This is an Attic repository` which is not true after the conversion.
- config, hints.2, index.2 are same inode.
- the segment files are (as it should be) different:
```
2267581 -rw------- 1 tw tw 1911341 Dec  7 18:52 repo/data/0/2
2267585 -rw-rw-r-- 1 tw tw 1911341 Dec  7 18:51 repo.upgrade-2015-12-07-18:52:06/data/0/2
```

**Comment by jdchristensen** [comment]
I just tested with 0.29, and see that the hints and config files are still hardlinked between the two repos.

Also, the borg repo has a lock.roster hanging around at the end.

**Comment by anarcat** [comment]
we really need to fix the unit test here... it should cover a complete upgrade command run...

**Comment by ThomasWaldmann** [comment]
@jdchristensen the issues caused by the original code were fixed. a hardlink is not an issue per se, the files do not need to have different content. also, a lock.roster file is normal in a borg repo. if you find anything of that an issue, please open a new ticket (and tell why you think it is an issue and how to reproduce a problem).

@anarcat please open a new issue for that (or a PR).

**Comment by jdchristensen** [comment]
I'm not sure whether hardlinking the hints file is a bug, so rather than open a new issue, I'll ask one more question here:  what if, at some point in the future, either attic or borg updates the hints file in place?  Then the other repo might stop functioning.

The hints file appears to be small, so I think it would be safer to have a separate copy than a hardlink.

All of the same comments apply to the config file.
