### ISSUE TITLE
Current docs (for 1.1.10) reference `borg compact` which doesn't exist yet

### ISSUE THREAD

**Issue by russelldavis** [borgbackup/borg#4660]
At https://borgbackup.readthedocs.io/en/stable/usage/notes.html, it has a reference to running `borg compact repo`. It looks like that command only exists in an unreleased version of borg.

**Comment by ThomasWaldmann** [comment]
Yeah, that somehow was overlooked... :-(

Instead of "compact", it could be "prune" (or any repo writing op) in 1.1.x.

**Comment by ThomasWaldmann** [comment]
fixed by #4714.
