### ISSUE TITLE
borg hangs with remote access, not with local (needs to inform user of break-lock)

### ISSUE THREAD

**Issue by krupan** [borgbackup/borg#4667]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug / ISSUE report

#### Your borg version (borg -V).

borg 1.1.5

#### Operating system (distribution) and version.

Ubuntu 18.04.2 LTS

#### Hardware / network configuration, and filesystems used.

ext4, LAN, ssh, laptop client, desktop server

#### How much data is handled by borg?

47 GB is the size of the directory being backed up.  Total data in the borg server repository is 8.7 GB (awesome dedup!)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg list ssh://backups/srv/backups-work

## Describe the problem you're observing.

Asks for passphrase and then hangs indefinitely when accessing repository over ssh.  Works fine when accessing repository locally from the server

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I'm not sure I can reproduce it now that I've fixed it.  To figure out why it was hanging I finally ran it under strace and saw this repeating:

```
select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
mkdir("/home/bmurdock/.cache/borg/815e0b467f0e11f62a821f7d4b1ea372550f87ede3b8606fcfe15d7271df73e4/lock.exclusive", 0777) = -1 EEXIST (File exists)
stat("/home/bmurdock/.cache/borg/815e0b467f0e11f62a821f7d4b1ea372550f87ede3b8606fcfe15d7271df73e4/lock.exclusive/bmurdock-laptop@198375883805174.3756-0", 0x7fff4232c5e0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/bmurdock/.cache/borg/815e0b467f0e11f62a821f7d4b1ea372550f87ede3b8606fcfe15d7271df73e4/lock.exclusive", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
getdents(3, /* 3 entries */, 32768)     = 112
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
```

I noticed that `lock.exclusive` directory and realized it must be a locking problem.  After running `borg break-lock ssh://backups/srv/backups-work` the problem went away.

Some kind of message about locks would have been very helpful here, instead of an eternal hang with no feedback.

**Comment by infectormp** [comment]
Your version of borg is outdated, can you reproduce problem with latest version?

**Comment by krupan** [comment]
Well, first time I tried running with the latest borg I got this message:
```

**Comment by ThomasWaldmann** [comment]
You did not reproduce it as your original problem was an infinite hang.

**Comment by ThomasWaldmann** [comment]
So, reopen if you can reproduce and post the commands needed for that.
