### ISSUE TITLE
gmane has wrong mailing list address

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#467]
http://dir.gmane.org/gmane.comp.sysutils.backup.borgbackup.general

still shows the outdated @librelist mail address.

the new address is borgbackup@python.org.

if whoever made this could please fix it, that would be appreciated.

**Comment by anarcat** [comment]
i asked in https://github.com/borgbackup/borg/issues/430#issuecomment-161866161

no response from the gmane people yet. maybe you'd like to ask yourself... see their FAQ, iirc.

**Comment by ThomasWaldmann** [comment]
I wrote another email to Lars (gmane admin).

**Comment by aklaver** [comment]
Probably because the Borg site:

https://borgbackup.readthedocs.org/en/stable/support.html

has the wrong address also.

**Comment by ThomasWaldmann** [comment]
@aklaver to read the latest stuff, you need "latest", not "stable".

**Comment by aklaver** [comment]
That is good to know, but when you search for Borg backup you get:
https://borgbackup.readthedocs.org/en/stable/

My point is, folks coming to the project are going to come in on stable and probably stick there, because it is stable. They then have to know facts not available to them in order to get to the mailing list. Also I think the version of the software should not relate to what mailing list is used.

**Comment by anarcat** [comment]
On 2015-12-11 17:24:23, Adrian Klaver wrote:
> That is good to know, but when you search for Borg backup you get:
> https://borgbackup.readthedocs.org/en/stable/
>
> My point is, folks coming to the project are going to come in on stable and probably stick there, because it is stable. They then have to know facts not available to them in order to get to the mailing list. Also I think the version of the software should not relate to what mailing list is used. 

You are right. This is a temporary condition that will be resolved as
soon as a new release is published, which will be real soon now.

**Comment by aklaver** [comment]
Thanks.

**Comment by ThomasWaldmann** [comment]
I tagged this as wontfix, because I can not fix it and contacting the admin there does not work.

I did not create the archive there, so I won't care any further ...
