### ISSUE TITLE
[Question] How can I log the output of --stats after a backup thats ran through cron?

### ISSUE THREAD

**Issue by lukeeexd** [borgbackup/borg#4671]
Hi,

Currently have `0 */1 * * * /path/to/script/backup.sh >> /path/to/log/borglog.log 2>&1` in cron

After it finished nothing is being sent to borglog.log. Am I doing it wrong? I have --stats in my borg command in backup.sh

**Comment by infectormp** [comment]
You need place this `>> /path/to//log/borglog.log 2>&1` inside `backup.sh`.

**Comment by lukeeexd** [comment]
I had tried that. after the borg command on the same line I had it, did nothing either

**Comment by infectormp** [comment]
Here is working example
```#!/bin/bash
BACKUP_PATH=/backup
REPO_NAME=www

export BORG_PASSPHRASE="xxx"
ARCHIVE_NAME="$REPO_NAME.`date +%d-%m-%Y_%H-%M-%S`"
LOG_NAME="$ARCHIVE_NAME.log"
LOG_PATH=/var/log/borg_backup
SOURCE_PATH=/var/www
COMMAND="borg create -v --info --list --show-rc -s --exclude '*.log' --exclude '*.txt' --keep-exclude-tags --exclude-caches -C auto,zstd --filter=AME"

echo Repository name: $REPO_NAME >> $LOG_PATH/$LOG_NAME 2>&1
echo Hostname: $HOSTNAME >> $LOG_PATH/$LOG_NAME 2>&1
echo Username: $LOGNAME >> $LOG_PATH/$LOG_NAME 2>&1
echo Command line: $COMMAND >> $LOG_PATH/$LOG_NAME 2>&1
borg -V >> $LOG_PATH/$LOG_NAME 2>&1
echo ------------------------------------------------------------------------------ >> $LOG_PATH/$LOG_NAME 2>&1
$COMMAND $BACKUP_PATH/$REPO_NAME::$ARCHIVE_NAME $SOURCE_PATH >> $LOG_PATH/$LOG_NAME 2>&1```

**Comment by lukeeexd** [comment]
`#!/bin/bash
export BORG_PASSPHRASE='REDACTED'
LOG_NAME="borglog.log"
LOG_PATH="/LOG/PATH"

screen -S reset -X stuff 'save-off\r'
screen -S reset -X stuff 'tellraw @a ["",{"text":"Backing up...","bold":false,"color":"red"}]\r'
borg create --exclude '/home/REDACTED/backup/survival/plugins/dynmap/web/' --exclude '/home/minecraft/backup/survival/plugins/CoreProtect/' REDACTED@REDACTED:/home/REDACTED/borg::survival-backup-{utcnow:%d-%m-%Y_%H:%M:%S} /home/REDACTED/backup
screen -S reset -X stuff 'tellraw @a ["",{"text":"Backup Complete!","bold":false,"color":"green"}]\r'
screen -S reset -X stuff 'save-on\r'

echo >> $LOG_PATH/$LOG_NAME 2>&1`

This is what I have, what am I missing cause wont work with this

**Comment by lukeeexd** [comment]
I just realised, that ofc that wont work. It seems the example you gave doesnt have --stats. I'm just trying to get the output of --stats to go into the log file after every time the cronjob runs

**Comment by infectormp** [comment]
`-s` is the same as `--stats`

**Comment by lukeeexd** [comment]
What part of the example is sending -s output to the logfile?

**Comment by infectormp** [comment]
You need `borg create --exclude ... >> $LOG_PATH/$LOG_NAME 2>&1` not `echo >> $LOG_PATH/$LOG_NAME 2>&1`

**Comment by infectormp** [comment]
This part `$COMMAND $BACKUP_PATH/$REPO_NAME::$ARCHIVE_NAME $SOURCE_PATH >> $LOG_PATH/$LOG_NAME 2>&1`

**Comment by lukeeexd** [comment]
`borg create --exclude '/home/REDACTED/backup/survival/plugins/dynmap/web/' --exclude '/home/REDACTED/backup/survival/plugins/CoreProtect/' REDACTED@REDACTED:/home/REDACTED/borg::survival-backup-{utcnow:%d-%m-%Y_%H:%M:%S} /home/REDACTED/backup >> $LOG_PATH/$LOG_NAME 2>&1` ?

**Comment by infectormp** [comment]
add `-s` or `--stats` to your command line

**Comment by lukeeexd** [comment]
wow i forgot I removed that when adding it for the cronjob. Thank you

**Comment by ThomasWaldmann** [comment]
So, this ticket can be closed?

**Comment by lukeeexd** [comment]
> So, this ticket can be closed?

Yes
