### ISSUE TITLE
Consider making `--no-atime` the default

### ISSUE THREAD

**Issue by russelldavis** [borgbackup/borg#4673]
The [docs already mention](https://borgbackup.readthedocs.io/en/stable/usage/notes.html#noatime-noctime) the problem that storing `atime` can create:

> it might also affect metadata stream deduplication: if only this timestamp changes between backups and is stored into the metadata stream, the metadata stream chunks won’t deduplicate just because of that.

What the docs don't mention is that on systems that don't support `O_NOATIME` (e.g. macOS), every single file will have a modified `atime` by virtue of borg scanning it. This means that the metadata stream will get almost no deduplication at all, resulting in large archive sizes even when ~no data has changed.

Additionally, the stored `atime` values won't really be useful, since they'll just reflect the time of the backup.

So, I think it makes sense for `--noatime` to be the default (with a `--atime` flag to opt-in), at least on systems where `O_NOATIME` is not available. (But I'd lean towards making it the default everywhere, since it's unclear that the value of storing it outweighs the downside for the average user.)

There of course could be suitable compatibility measures, like keeping the old default for existing repos.

**Comment by ThomasWaldmann** [comment]
I don't want to make the default of a setting dependent on presence of a system feature.
What borg does should be determined by the options given (if possible).

I agree that noatime behaviour is likely what many users want, so borg 1.2 might be a good time to change the default and add a new option. Opinions?

**Comment by russelldavis** [comment]
> I don't want to make the default of a setting dependent on presence of a system feature.
What borg does should be determined by the options given (if possible).

Agreed (I was mostly hedging in case there were reasons for not changing it everywhere).

> I agree that noatime behaviour is likely what many users want, so borg 1.2 might be a good time to change the default and add a new option

Yep, that'd be perfect.

**Comment by FabioPedretti** [comment]
Agree on --noatime being the default (I am already using it).
