### ISSUE TITLE
Allow option to control compacting threshold

### ISSUE THREAD

**Issue by russelldavis** [borgbackup/borg#4674]
Some other users have mentioned this would be useful:
- https://github.com/borgbackup/borg/issues/2985#issuecomment-375391451
- https://mail.python.org/pipermail/borgbackup/2016q4/000501.html

I would find it useful for the same reasons (to minimize churn when rcloning a Borg repo to S3).

**Comment by fantasya-pbem** [comment]
@ThomasWaldmann I could try to add an option. But what is expected? A new option for ``borg compact`` that has an effect when this command is run?

**Comment by ThomasWaldmann** [comment]
Yeah, guess it needs a new compact option.

Also, please note that `RemoteRepository.commit` also needs to be extended so it will also work for remote repos.

**Comment by fantasya-pbem** [comment]
Yeah, my first-ever Python programming experience merged!
