### ISSUE TITLE
Borg prune keep daily 6 is keeping one?

### ISSUE THREAD

**Issue by lukeeexd** [borgbackup/borg#4675]
I want to take a backup every hour. So 24 backups per day, then at the end of the day prune so only to keep the latest 6. I thought the below command would do it but seems it doesnt?

`borg prune -v --list --dry-run --keep-daily=6 /home/luke/borg`

`Keeping archive: survival-backup-03-07-2019_22:58:11  Wed, 2019-07-03 23:58:13 [becfff0d9465858a2f69ab23ba18433ff07083686aa129a47c6ed0dccf38b43c]
Would prune:     survival-backup-03-07-2019_22:00:01  Wed, 2019-07-03 23:00:03 [1ee81941fc1f19936777740db3c04152b3c7fd06d7145a9f32ae2ac9381dc4d2]
Would prune:     survival-backup-03-07-2019_21:00:01  Wed, 2019-07-03 22:00:03 [3291b69936d9b394f88ed85cb5b7386a69be76ed44f6469c4200a9c82055577d]
Would prune:     survival-backup-03-07-2019_20:00:02  Wed, 2019-07-03 21:00:03 [05a77fe464a018b423422e1b09daae8bfdef04591c2101a1f2cba7b6b79ae691]
Would prune:     survival-backup-03-07-2019_19:00:01  Wed, 2019-07-03 20:00:02 [91600be094af4b9be27231fd81e6bbb086ea8ecfe55bb370e69ea30e615530c0]
Would prune:     survival-backup-03-07-2019_18:00:02  Wed, 2019-07-03 19:00:03 [6fdcc2e544a69ec8dadda44731941ec6939a8fc79ce8cc37424284d39122d0b8]
Would prune:     survival-backup-03-07-2019_17:00:01  Wed, 2019-07-03 18:00:03 [7555a4792809eece3f154c0399e01a83ea8fe75ad83609108efb1287dea7c2f6]
Would prune:     survival-backup-03-07-2019_16:00:02  Wed, 2019-07-03 17:00:03 [c97e94c9e027b6479f6f894ada89940031afc3ef9b799830f3c9adde6b88d4c2]
Would prune:     survival-backup-03-07-2019_15:00:01  Wed, 2019-07-03 16:00:03 [c5417ae70b88875921b42e995986e5ce4c8696868ebb456f04f90820c5c2f78d]
Would prune:     survival-backup-03-07-2019_14:00:01  Wed, 2019-07-03 15:00:03 [dddfd6a1dda5c42739470245af9a12b0e5028d999bdea3c7133c3a2e0a39a133]
Would prune:     survival-backup-03-07-2019_13:00:01  Wed, 2019-07-03 14:00:03 [1eff080f7067e44371c2b5adc4fea454e4146d57b8b5f20f0f132c34d2ad1433]
Would prune:     survival-backup-03-07-2019_10:00:02  Wed, 2019-07-03 11:00:03 [bc2f4a6043764573186e4bdabd838d6bf6743e9adcd700d342783f6692132a4f]
Would prune:     survival-backup-03-07-2019_04:00:01  Wed, 2019-07-03 05:00:03 [12024a3045023c244e3e9714e4553a2744fba15be3a19dfd387a7676a564ff59]
Would prune:     survival-backup-03-07-2019_03:23:25  Wed, 2019-07-03 04:23:26 [75244c9d7ce32271712e9b8919ee1555cd4b77c791313a59a23fd80278fe93a1]`

edit: nvm seems i should be using --keep-hourly

**Comment by a-gn** [comment]
`--keep-daily 6` keeps the last archive of each day for 6 days. `--keep-hourly 6` keeps the last archive of each hour for 6 hours, it sounds more like what you want.

**Comment by ThomasWaldmann** [comment]
guess this is solved.
