### ISSUE TITLE
Add a --retry-when-failed option to borg extract

### ISSUE THREAD

**Issue by a-gn** [borgbackup/borg#4677]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

borg 1.1.5

#### Operating system (distribution) and version.

Ubuntu Ubuntu 18.04.2 on WSL on Windows 10 1903

#### Hardware / network configuration, and filesystems used.

SSH to rsync.net

#### How much data is handled by borg?

20GB+

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg extract --progress 'user@hostname:borg::archname' valid_path_in_archive`

## Describe the problem you're observing.

I suffer from #636 (long operations stop with "connection closed by remote"), but it also happens during long restores (`borg extract`). This is a huge problem: the solution for `borg create` was to restart the operation until it finishes, but this fails for restores since `borg extract` starts over every time. I've been trying to restore a large folder for some hours and always get the same error.

Since this is probably a problem with my connection (specialized ISP for student accommodations), borg can't prevent this error, but it would help greatly to have the option to make borg re-open the connection and continue the extraction from the file it failed on. Maybe with a retry count to avoid an infinite loop.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

This happens every time I do a long operation with borg over SSH.

I tried re-starting the extraction and got the same error at some point. I can't prevent this from happening or mitigate it, since borg has no way (that I know of) of continuing the extraction from where it left off.

#### Include any warning/errors/backtraces from the system logs

`Connection closed by remote host`

**Comment by ThomasWaldmann** [comment]
Did you try the ssh configuration change suggested in #636?

**Comment by a-gn** [comment]
> Did you try the ssh configuration change suggested in #636?

I will try later. But reading the thread and the new doc, it seems to let borg exit gracefully, and not actually fix the connection problem?

**Comment by ThomasWaldmann** [comment]
If you use (Server|Client)Alive, they will send a packet over the ssh channel to see whether the other side is still alive (and answers with a reply to that packet). That might help keeping the ssh connection connected in situations when there is no other traffic.

**Comment by ThomasWaldmann** [comment]
Also, you might want to read the changelog since 1.1.5. There were quite some releases after that with misc. fixes. An up-to-date Ubuntu package is available from the maintainer's ppa.

**Comment by a-gn** [comment]
I just added these settings and restored 30GB without error on the same connection as yesterday, but just realized I messed up the settings and actually changed nothing. I guess this can be closed, it was probably just my connection. Thanks for your help.
