### ISSUE TITLE
Crash when checking/backing up to existing repo

### ISSUE THREAD

**Issue by kaisengit** [borgbackup/borg#4678]
## Have you checked borgbackup docs, FAQ, and open Github issues?

I did

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg 1.1.10

#### Operating system (distribution) and version.
Linux 5.1.15-1-MANJARO

#### Hardware / network configuration, and filesystems used.
A borg repo on an external ntfs hard drive mounted via cifs.

#### How much data is handled by borg?
~ 20 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg check /mnt/mixplatte/borg/yoga`

## Describe the problem you're observing.
Any command connected to this specific repo leads to the crash pasted below. A few weeks ago this repo worked fine. Note that I can still create new repos and add files to them on the same file system. The error is specific to this existing repo.

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 892, in check
    transaction_id = self.get_transaction_id()
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 376, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 357, in check_transaction
    segments_transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1217, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1252, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.7/site-packages/borg/archiver.py", line 327, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 896, in check
    transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1217, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3.7/site-packages/borg/repository.py", line 1252, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

Platform: Linux yoga 5.1.15-1-MANJARO #1 SMP PREEMPT Wed Jun 26 23:48:19 UTC 2019 x86_64
Linux: arch Manjaro Linux
Borg: 1.1.10  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 1575  CWD: /opt/scripts
sys.argv: ['/bin/borg', 'check', '/mnt/mixplatte/borg/yoga']
SSH_ORIGINAL_COMMAND: None

```

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/4211

**Comment by kaisengit** [comment]
I don't think these issues are related. My error message is a different one and using the mount options provided in #4211 does not fix my problem or affect my error message. Also I am still able to create new repos and write to them on the same drive. It's just the existing repo which suddenly acted up.

**Comment by ThomasWaldmann** [comment]
`OSError: [Errno 5] Input/output error` this is a problem below borg:
- disk medium
- filesystem (ntfs)
- network / network filesystem (cifs)

**Comment by kaisengit** [comment]
It is still strange since only this one repo acts up. I am actually backing up several different machines via this cifs setup and they work all fine. Later I will mount the drive locally and see whether it makes a difference.

**Comment by kaisengit** [comment]
Update: I did attach the drive locally. All SMART values are good as is overall drive health. When running any borg command on the repo though the above error appears. I have now created a new repo on the same drive (which worked fine) and I have my fingers crossed that it doesn't get borked up this time. IMO it is/was not a filesystem or hardware problem

**Comment by infectormp** [comment]
So this is network (cifs) problem

**Comment by kaisengit** [comment]
Why would it be? As I said the same error appeared when I attached the drive locally. I now made a new repo on the same drive, using the same backup command and the backup works again. Both locally and remotely via cifs. For some reason this repo got nuked; I now have my fingers crossed it does not happen again.

**Comment by infectormp** [comment]
Sorry I misunderstood you. Did you check FS for errors or you check only SMART values?

**Comment by ThomasWaldmann** [comment]
You could do `smartctl -t long DEVICE` and then check smart values again.

**Comment by kaisengit** [comment]
It was a file system issue after all. I attached the disk to a Windows computer and ran chkdsk /f. It found a few errors and corrected them. Afterwards the original repo worked fine again! Very sorry to have wasted your time!
