### ISSUE TITLE
borg mount: error: argument REPOSITORY_OR_ARCHIVE: Invalid location format

### ISSUE THREAD

**Issue by axelhuizinga** [borgbackup/borg#4684]
Hi,
I can't figure out how to correctly use borg mount
mounting as cifs share works:
mount.cifs --verbose -o user=u199016,pass=xxx //u199016.your-storagebox.de/backup /opt/backup/u199016.your-storagebox.de
but 
borg mount  //u199016.your-storagebox.de/backup /opt/backup/u199016.your-storagebox.de
returns the error message:
borg mount: error: argument REPOSITORY_OR_ARCHIVE: Invalid location format: "//u199016.your-storagebox.de/backup"
how is the correct location format in this context?

**Comment by infectormp** [comment]
`borg mount /opt/backup/u199016.your-storagebox.de`

**Comment by axelhuizinga** [comment]
that doesn't work since /opt/backup doesn't exist on the repo
after a lot of try and error this works:
borg mount ssh://u199016@u199016.your-storagebox.de:23/home/backup /opt/backup/u199016.your-storagebox.de
Enter passphrase for key ssh://u199016@u199016.your-storagebox.de:23/home/backup:
...

**Comment by infectormp** [comment]
` /opt/backup` will work after you mount if over cifs
