### ISSUE TITLE
Add options to decompress before backing up.

### ISSUE THREAD

**Issue by BloodBlight** [borgbackup/borg#4688]
It would be nice if there was an option to have borg do an inline extract of some archive types before backing up the file.

For example, I have a folder full of “snapshots” made from an application (that I don’t have control over).  Each of these are 90%+ the same, but they are tar.gz’ed.  So when they go into borg there is effectively no deduplication.

I am not sure how you would restore these.  I guess you could create a folder of files, or a tar rather than a tar.gz, or I suppose you could even offer to re-compress them, but…  Anything is better than nothing, and any difficulties during restores I think would be outweighed by the advantages.

Today we handle this with several scripts, but it is a bit kludgy and we have to do a create for every file from a standard input (without burning a ton of IO).  I think this would be great for targeting large and diverse file servers.  Maybe even some ZIP support?

I was thinking this could even be a fuse overlay of some sort rather than a direct borg feature?  Something that remaps any supported archive to a folder (like archive mount, but invisible)?  IDK…  Just thinking.

Thanks!

**Comment by ThomasWaldmann** [comment]
We had an issue about a quite similar idea, but close it, because it might be troublesome to recreate a binary-identical file at restore time.
