### ISSUE TITLE
Slow create invocation for 1TB of files?

### ISSUE THREAD

**Issue by pkeir** [borgbackup/borg#4689]
I would like to periodically backup our family photos and videos. I have two external 5TB USB3 drives. I would like to use the first of these as the source - updated ad-hoc by family members. Our files are currently 1TB in size. Periodically I would then back this up to the second USB drive.

I am using 64-bit Ubuntu 19.04 Desktop which has borg backup version 1.1.9; the desktop machine I am using for this has an AMD A10-7850K. I read through the documentation of borg backup, and after an hour or so of small tests, I began with the following two commands: 

```
borg init -e none /media/john/usb-two/borg-family-archive
borg create --stats --progress /media/john/usb-two/borg-family-archive::{user}-{now} /media/john/usb-one/
```

The last (create) step takes a very long time. After 24 hours it seemed to be halfway through. I cancelled the process as I felt this was taking too long. Does this seem like a long time? I guess before I invest in this as a standard procedure, I'd like to be sure I've chosen the right tool, and am following the correct approach. Assuming it did finish after 48 hours, could I expect further `create` invocations (say for 100 new photos) to run much quicker? In minutes or still hours? I noticed that compression is on by default, so I also then tried with no compression on a 2.5GB test, but this took almost the same time with or without.

**Comment by ThomasWaldmann** [comment]
The default compression (lz4) does not cause speed issues, it is low compression, but high speed.

The first backup usually takes long, how long depends on a lot of factors. Borg is single-threaded, so it will only use 1 core. Future backups will take time corresponding to the amount of changed/added files.

**Comment by ThomasWaldmann** [comment]
If you just aborted (e.g. using ctrl-c) and did not delete the target repo, you can just start the backup again and it will do the remaining work (it won't transfer data again which is already in the repo).

**Comment by pkeir** [comment]
I tried again, from scratch, and it completed in less than 24 hours. I then called the same `borg create` command again (i.e. no changes), and it took 5 minutes. I think I can work with this. Thanks.

**Comment by Zapeth** [comment]
I'm currently also looking for a long-term backup solution for all of my data (~3TB) and I'm curious about some stats of your backed up data (if you don't mind sharing):

1) what is the size difference of your archived data vs the original?
2) how much time does a `borg check --verify-data` take on the archived data?
3) how much time does it take to extract something from the archived data (might be more interesting to measure for small, medium and big sizes too, like ~1MB, 100MB+, 1GB+)
4) specs of the USB drive where the archived data is stored and the measurements were performed

**Comment by pkeir** [comment]
1. The original is 933GB and the backup is 843GB.
2. I didn't take the exact time. My notes only warn me: "hours".
3. I don't have that information.
4. The discs are 2x Seagate 5 TB Backup Plus USB 3.0 Portable 2.5 Inch External Hard Drive.

I may get back to you on point 3, but not for some months; when I make my next backup.

**Comment by ThomasWaldmann** [comment]
@pkeir In case the hours long initial backup is demotivating you to make more frequent backups than every few months: all non-initial backups are way quicker than the initial one.

**Comment by pkeir** [comment]
@ThomasWaldmann Thanks. Every few months is just the rate I naturally back up my photos. I was happy enough that the "no change" test I mentioned completed in 5 minutes. I'll try to remember then and update with my first real benchmark.

**Comment by ThomasWaldmann** [comment]
Guess we can close this. Backing up a lot of data for the first time with borg takes time. How much depends on a lot of factors.

**Comment by Zapeth** [comment]
@pkeir Thank you for the information. I was hoping for a somewhat more accurate time range regarding 2) since I'm also planning to do data verification checks from time to time, but I understand if its a hassle for you (especially if it takes up a good portion of a day).
