### ISSUE TITLE
diff command returns other values than documented

### ISSUE THREAD

**Issue by anhofmann** [borgbackup/borg#4693]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

borg 1.1.10

## Describe the problem you're observing.

If a file is changed only slightly (e.g. one byte), borg diff will display a much larger change (e.g. 8.8 MB) than actually changed in the file.  Borg diff displays the number of bytes of the chunk in which the file has been changed instead of the number of bytes that have changed in the file. 

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

```
$ borg init -e=none testrepo
$ dd if=/dev/urandom bs=10M count=5 of=./file
$ borg create testrepo::1 ./file
<flip a byte with xxd or whatever editor>
$ borg create testrepo::2 ./file
$ borg diff ../testrepo::1 2
output:   +8.8 MB   -8.8 MB file
```

**Comment by ThomasWaldmann** [comment]
That's how it is intended to work, no at bug - it displays the size of the chunks added / removed.

I am just wondering a bit that it is >8MB, the default target chunk size is 2MB, so **that** might be something to investigate.

You could help analyzing this by repeating your experiment (with some new random input files, with a  all-zero file, with 1byte changes at misc places).

**Comment by ThomasWaldmann** [comment]
If the docs say anything else, link specifically to the bad docs or make a pull request, if you like.
