### ISSUE TITLE
[1.2.0a6] Should benchmark crud perform a implicit compact?

### ISSUE THREAD

**Issue by ntova** [borgbackup/borg#4694]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.

Arch Linux Arm on Raspberry Pi 4

#### Your borg version (borg -V).

borg 1.2.0a6

#### How much data is handled by borg?

~800MB (test repository)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg benchmark crud :: /tmp

## Describe the problem you're observing.

Running a benchmark in the new alpha does not compact the repository afterwards and uses about 2GB of space (in may case). A manual compact restores that space.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

`du -sh $BORG_REPO` -> ~800MB
`borg benchmark crud :: /tmp`
`du -sh $BORG_REPO` -> ~2.8GB
`borg compact ::`
`du -sh $BORG_REPO` -> ~800MB

I see two options:
* do a implicit compact after a benchmark
* document that a benchmark uses space until the next run of `compact`

**Comment by ThomasWaldmann** [comment]
It is already documented that space is not recovered after deletion until you run compact.

https://borgbackup.readthedocs.io/en/master/usage/compact.html#description

https://borgbackup.readthedocs.io/en/master/usage/delete.html#description

Guess that "Important:" line from delete command description could be reused / slightly modified for the crud command description.

Can you make a PR for that?
