### ISSUE TITLE
Borg prints out "Repository XXX does not exist" if the read/write permissions are not granted

### ISSUE THREAD

**Issue by Forceu** [borgbackup/borg#4695]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

## System information. For client/server mode post info for both machines.
Linux x64

#### Your borg version (borg -V).
1.1.9

#### Operating system (distribution) and version.
Ubuntu 18.04LTS

#### Hardware / network configuration, and filesystems used.
Ext4 / Cryptsetup

#### How much data is handled by borg?
8TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
All borg commands

## Describe the problem you're observing.
I attached my harddrive including the Borg repository to a different server with more perfomance. Apparently the folder settings were set incorrectly, therefore Borg was unable to create a new archive. It always gave the error "Repository XXXXX does not exist.", it would be a lot better however if it put out some thing that tells the user that the permissions were denied. I tried finding out why it thinks that the repository doesn't exist for almost an hour, until I saw that the permissions were set incorrectly.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps 

Chown the folder with the repository to a different user, so borg cannot access it.

#### Include any warning/errors/backtraces from the system logs
Repository XXXXX does not exist.

**Comment by ThomasWaldmann** [comment]
I can't reproduce:

```
$ ls -ld noperms
drwxrwx--- 2 root root 4096 Jul 28 14:59 noperms/

$ borg -V
borg 1.1.9

$ borg init -e none noperms/repo
Local Exception
Traceback (most recent call last):
  File "/home/user/w/borg/src/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/home/user/w/borg/src/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/home/user/w/borg/src/borg/archiver.py", line 139, in wrapper
    with repository:
  File "/home/user/w/borg/src/borg/repository.py", line 187, in __enter__
    self.create(self.path)
  File "/home/user/w/borg/src/borg/repository.py", line 262, in create
    os.mkdir(path)
PermissionError: [Errno 13] Permission denied: '/home/user/w/borg/noperms/repo'

Platform: Linux development 4.14.119-2.pvops.qubes.x86_64 #1 SMP Wed May 15 06:43:11 UTC 2019 x86_64
Linux: debian 9.6 
Borg: 1.1.9  Python: CPython 3.5.6
PID: 2924  CWD: /home/user/w/borg
sys.argv: ['/home/user/w/borg-env/bin/borg', 'init', '-e', 'none', 'noperms/repo']
SSH_ORIGINAL_COMMAND: None
```

It clearly says "permission denied".

**Comment by Forceu** [comment]
No I was writing in regards to creating a new archive, not repo.

```
borg init -e none noperm/repo
sudo chown root:root noperm
sudo chmod 700 noperm
borg -v create noperm/repo::Test /tmp

$ Repository /home/force/noperm/repo does not exist.
```

**Comment by ThomasWaldmann** [comment]
Confirmed.

The problem here is that it uses `os.path.isdir(path)` and that just returns False if it has no permissions, thus borg told that the repo does not exist.

I will change this to:
- use `st = os.stat(path)` and catch `FileNotFoundError` -> repo does not exist.
- do not catch other exceptions, so it will just blow up on permission and other errors (like lots of other places).
- check for path being a directory with `stat.S_ISDIR(st.st_mode)`, if not -> invalid repository.

**Comment by ThomasWaldmann** [comment]
See #4698.
