### ISSUE TITLE
Does borg benchmark have [options] ?

### ISSUE THREAD

**Issue by adatum** [borgbackup/borg#4707]
## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

The [documentation](https://borgbackup.readthedocs.io/en/stable/usage/benchmark.html) specifies `[options]` for the command, but does not explain what they are, if any. Either the documentation seems incomplete or there are no options. If the latter, I would suggest removing the mention because it is confusing.

`borg [common options] benchmark crud [options] REPO PATH`

Further down, there is a description of borg benchmark's output, but it uses `==` which I confused for possible syntax (possibly for [options]). 

eg. 

> C- == borg create (1st archive creation, no compression, do not use files cache)
>     C-Z- == all-zero files. full dedup, this is primarily measuring reader/chunker/hasher. C-R- == random files. no dedup, measuring throughput through all processing stages.

I would suggest not using `==` as it has programmatic meaning, and instead using code blocks for pre-formatted text like `C-`, `C-Z-`, or using quotations "C-", "C-Z-", or even nothing at all "C- in output means...".

#### Your borg version (borg -V).
borg 1.1.10

**Comment by ThomasWaldmann** [comment]
Can you make a PR with this (and test wether html docs, man page and commandline help still all look ok)?

**Comment by adatum** [comment]
Is `[options]` real, a planned improvement, or an oversight?

**Comment by ThomasWaldmann** [comment]
The docs are created automatically from the python code, so I guess `[options]` is always there.

In fact, some options are always evaluated, e.g. if you give `-v`.

Whether an option actually makes a difference, depends on the subcommand implementation (e.g. `-v` won't make a different, if a command does not emit anything with < WARNING level).

**Comment by adatum** [comment]
Doesn't `-v` fall under `[common options]` as described in the [documentation](https://borgbackup.readthedocs.io/en/stable/usage/general.html#common-options)? My understanding is that `[options]` would be flags that are specific to the `borg benchmark crud` command, aside from the common options.

Contrast with any other command, for example, [borg init](https://borgbackup.readthedocs.io/en/stable/usage/init.html) which specifies

`borg [common options] init [options] [REPOSITORY]`

and lists `[options]` specific to borg init, and then also has a link to the documentation of the common options.

**Comment by ThomasWaldmann** [comment]
yes, -v is a common option. guess the options placeholder is also always there, no matter how many options there are for a command. if there arent't listed any, there are none...
