### ISSUE TITLE
Seg fault backing up locked file from Samba mount.

### ISSUE THREAD

**Issue by BloodBlight** [borgbackup/borg#4709]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yep

## Is this a BUG / ISSUE report or a QUESTION?
BUG

## System information. For client/server mode post info for both machines.
A "local" backup of a mounted samba share.

#### Your borg version (borg -V).
borg-linux64 1.1.10

#### Operating system (distribution) and version.
Ubuntu 18.04.2 LTS

#### How much data is handled by borg?
Under 1TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
#Target is Windows Server 2016
```
mount.cifs #PRIVATE#/Share /mnt/Temp -o domain=#PRIVATE#,username=#PRIVATE#,vers=2.0,rw,nounix,iocharset=utf8,file_mode=0666,dir_mode=0777
~/borg-linux64 create --compression zstd,11 --stats --progress #PRIVATE#::Initial /mnt/Temp/
```

## Describe the problem you're observing.
We have a job that is trying to backup a windows share that is being mounted to a local temp location.  When it hits a file that is locked, rather than erroring ans skipping it, borg seg faults.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Happend every time on this lock file.  I think it is being made by the windows version of elastisearsh.

#### Include any warning/errors/backtraces from the system logs
```
Fatal Python error: Segmentation fault4 N mnt/Temp/...#PRIVATE#.../write.lock                                            

Current thread 0x00007fe55f77e740 (most recent call first):
  File "borg/archive.py", line 182 in backup_io_iter
  File "borg/archive.py", line 990 in chunk_file
  File "borg/archive.py", line 1063 in process_file
  File "borg/archiver.py", line 624 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 536 in create_inner
  File "borg/archiver.py", line 573 in do_create
  File "borg/archiver.py", line 166 in wrapper
  File "borg/archiver.py", line 4433 in run
  File "borg/archiver.py", line 4501 in main
  File "borg/__main__.py", line 2 in <module>
Segmentation fault (core dumped)
```
Note sure where the core dump is, but I probably can't share it...

**Comment by ThomasWaldmann** [comment]
```
class BackupIO:
    op = ''
                                                         # this empty line is line 182
    def __call__(self, op=''):
        self.op = op
        return self

    def __enter__(self):
        pass

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type and issubclass(exc_type, OSError):
            raise BackupOSError(self.op, exc_val) from exc_val


backup_io = BackupIO()
```

**Comment by ThomasWaldmann** [comment]
```
cdef class Chunker:
    cdef _Chunker *chunker

    def __cinit__(self, int seed, int chunk_min_exp, int chunk_max_exp, int hash_mask_bits, int hash_window_size):
        min_size = 1 << chunk_min_exp
        max_size = 1 << chunk_max_exp
        # see chunker_process, first while loop condition, first term must be able to get True:
        assert hash_window_size + min_size + 1 <= max_size, "too small max_size"
        hash_mask = (1 << hash_mask_bits) - 1
        self.chunker = chunker_init(hash_window_size, hash_mask, min_size, max_size, seed & 0xffffffff)

    def chunkify(self, fd, fh=-1):
        """
        Cut a file into chunks.

        :param fd: Python file object
        :param fh: OS-level file handle (if available),
                   defaults to -1 which means not to use OS-level fd.
        """
        chunker_set_fd(self.chunker, fd, fh)
        return self

    def __dealloc__(self):
        if self.chunker:
            chunker_free(self.chunker)

    def __iter__(self):
        return self

    def __next__(self):
        return chunker_process(self.chunker)          # <- iterator
```

So it looks like `chunker_process` (one of the few parts of borg that is in C) has an issue.

Can you run borg with a debugger (e.g. gdb) and then reproduce the issue?

**Comment by BloodBlight** [comment]
Should be able to.  Doing some googling, do you have a ready procedure?

**Comment by BloodBlight** [comment]
Installed, poking at it now (only used it once before).

**Comment by BloodBlight** [comment]
Source files loaded, I am left here:
```
Fatal Python error: Segmentation #PRIVATE#

Current thread 0x00007ffff7fe9740 (most recent call first):
  File "borg/archive.py", line 182 in backup_io_iter
  File "borg/archive.py", line 990 in chunk_file
  File "borg/archive.py", line 1063 in process_file
  File "borg/archiver.py", line 624 in _process
  File "borg/archiver.py", line 650 in _process
  File "borg/archiver.py", line 536 in create_inner
  File "borg/archiver.py", line 573 in do_create
  File "borg/archiver.py", line 166 in wrapper
  File "borg/archiver.py", line 4433 in run
  File "borg/archiver.py", line 4501 in main
  File "borg/__main__.py", line 2 in <module>

Program received signal SIGSEGV, Segmentation fault.
__GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
51	}
(gdb) 
```

Not sure what to do next.

**Comment by BloodBlight** [comment]
File: sysdeps/unix/sysv/linux/raise.c
```
 26 int
 27 raise (int sig)
 28 {
 29   /* rt_sigprocmask may fail if:
 30 
 31      1. sigsetsize != sizeof (sigset_t) (EINVAL)
 32      2. a failure in copy from/to user space (EFAULT)
 33      3. an invalid 'how' operation (EINVAL)
 34 
 35      The first case is already handle in glibc syscall call by using the arch
 36      defined _NSIG.  Second case is handled by using a stack allocated mask.
 37      The last one should be handled by the block/unblock functions.  */
 38 
 39   sigset_t set;
 40   __libc_signal_block_app (&set);
 41 
 42   INTERNAL_SYSCALL_DECL (err);
 43   pid_t pid = INTERNAL_SYSCALL (getpid, err, 0);
 44   pid_t tid = INTERNAL_SYSCALL (gettid, err, 0);
 45 
 46   int ret = INLINE_SYSCALL (tgkill, 3, pid, tid, sig);
 47 
 48   __libc_signal_restore_set (&set);
 49 
 50   return ret;
 51 }
 52 libc_hidden_def (raise)
 53 weak_alias (raise, gsignal)
```

**Comment by ThomasWaldmann** [comment]
not sure either. the line below the segfault is not in borg, but `linux/raise.c` (not sure what that is).

guess one needs to go a step back (up?) somehow, so one sees the last steps in borg code.

**Comment by ThomasWaldmann** [comment]
show the C callstack somehow?

**Comment by BloodBlight** [comment]
Not sure how, searching..  But check this out:
```
cp /mnt/#PRIVATE#/write.lock /tmp/
cp: error writing '/tmp/write.lock': Bad address
```
So, ya, probably NOT a borg issue.  The source is part of glibc so I might have to go fishing.

**Comment by ThomasWaldmann** [comment]
Oh, yeah, that looks strange. Maybe the cifs code doing something badly?

**Comment by ThomasWaldmann** [comment]
From Elladan on IRC:
```
ThomasWaldmann, next step is "bt" for backtrace
"bt full"
"thread apply all bt full"
"info locals", "info args" don't hurt.
The CIFS code could conceivably be sending a fatal signal
as a half-assed way of implementing mandatory locks.
```

**Comment by BloodBlight** [comment]
It looks like rsync can copy the files just fine, including the clocked files.

It looks like I need additional symobls,

**Comment by BloodBlight** [comment]
I have a test environment where I can use experimental code if that helps.

**Comment by ThomasWaldmann** [comment]
Well, I did not see a bug in borg yet and considering what you've found with `cp`, it does not even look like a borg bug.

**Comment by nafetsreuab** [comment]
Still an issue with latest borg version (1.1.13)

`/input/allplan/2019/Prj/n0001300.lck: stat: [Errno 2] No such file or directory: '/input/allplan/2019/Prj/n0001300.lck'                                                             /input/allplan/2019/Prj/n0001596.lck: open: [Errno 16] Device or resource busy: '/input/allplan/2019/Prj/n0001596.lck'                                                              /input/allplan/2019/Prj/n0002010.lck: open: [Errno 16] Device or resource busy: '/input/allplan/2019/Prj/n0002010.lck'                                                              /input/allplan/2019/Prj/n0001875.lck: open: [Errno 16] Device or resource busy: '/input/allplan/2019/Prj/n0001875.lck'                                                              /input/allplan/2019/Prj/n0001744.lck: open: [Errno 16] Device or resource busy: '/input/allplan/2019/Prj/n0001744.lck'                                                              /input/allplan/2019/Prj/n0001910.lck: open: [Errno 16] Device or resource busy: '/input/allplan/2019/Prj/n0001910.lck'                                                              Fatal Python error: Segmentation fault                                                                                                                                                                                                                                                                                                                                  Current thread 0x00007fd49f12b700 (most recent call first):                                                                                                                           File "borg/archive.py", line 183 in backup_io_iter                                                                                                                                  File "borg/archive.py", line 998 in chunk_file                                                                                                                                      File "borg/archive.py", line 1071 in process_file                                                                                                                                   File "borg/archiver.py", line 635 in _process                                                                                                                                       File "borg/archiver.py", line 661 in _process                                                                                                                                       File "borg/archiver.py", line 661 in _process                                                                                                                                       File "borg/archiver.py", line 661 in _process                                                                                                                                       File "borg/archiver.py", line 547 in create_inner                                                                                                                                   File "borg/archiver.py", line 584 in do_create                                                                                                                                      File "borg/archiver.py", line 176 in wrapper                                                                                                                                        File "borg/archiver.py", line 4497 in run                                                                                                                                           File "borg/archiver.py", line 4565 in main                                                                                                                                          File "borg/__main__.py", line 2 in <module>                                                                                                                                       Segmentation fault      `

mounted with: type cifs (ro,relatime,vers=default,cache=strict,username=backup,domain=,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.1.2,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)

Reported files are:

# file n0001596.lck
n0001596.lck: empty

  File: n0001596.lck
  Size: 0         	Blocks: 0          IO Block: 16384  regular empty file
Device: 33h/51d	Inode: 844424930437110  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-06-25 12:43:13.212525800 +0200
Modify: 2020-06-25 12:43:13.212525800 +0200
Change: 2020-06-25 12:43:13.212525800 +0200
 Birth: -

Indeed, not only borg can not access the file:

# cp n0001596.lck /tmp/
cp: cannot open 'n0001596.lck' for reading: Device or resource busy


Still giving it a try with --read-special and will report back.

**Comment by nafetsreuab** [comment]
Just follow up, with --read-special in place, borg just logged "Device or resource busy" but did not segfault this time.
Will provide follow up, after whole backup is done. But looks promising ;)

**Comment by ThomasWaldmann** [comment]
@nafetsreuab read the comments above, this is not a borg issue, but likely in CIFS.

**Comment by bauerstefan** [comment]
As borg logs, that Device or resource is busy, it detects, that it can not read from filehandle. Shouldn't that be a case, that borg could detect and just skip forward to next file?

Local 'cp' just detects it and skips file. Or as stated before by @BloodBlight - rsync has no problem copying this files at all.

I dont see the cifs code influencing borgs behavior - i see that borg is just hitting a 'case' that it does not know yet how to handle it appropriate. But maybe I'm just seeing it from too far away. no offence. thank you for your time and effort! Just wanted to provide a different angle to the problem.

**Comment by nafetsreuab** [comment]
After excluding reported and locked files, borg still segfaults without reporting specific files anymore. So I'm not sure, if a specific file is the reason at all.

**Comment by ThomasWaldmann** [comment]
This is not a borg issue, but an issue in CIFS code.
