### ISSUE TITLE
Stuck on "Remote: Replaying segments 0%"

### ISSUE THREAD

**Issue by tonke90** [borgbackup/borg#4726]
### Your borg version (borg -V).
borg 1.1.10 (server & client)

#### Operating system (distribution) and version.
client: Arch Linux
server: Arch Linux ARM

#### Hardware / network configuration, and filesystems used.
server: Raspberry PI 2
HDD: USB 3 TB
filesystem: btrfs

#### How much data is handled by borg?
~650 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
date=$(date +"%Y-%m-%d" )
cd "/data"
borg create --progress --verbose ssh://backup/media/data/backups/pictures::$date Pictures
```

## Describe the problem you're observing.

I’m running a offsite backup to a Raspberry Pi 2 with a USB HDD attached to it running borg.

On my first incremental backup to this repository (the initial one wasn’t done remotely) borg gets stuck on the status:
```
Remote: Replaying segments 0%
```
I had the same status for my other repositories, but there it progressed.

First, I can observe the borg process doing CPU (~60%) and I/O (~28 M/s) load on the server:
```
/usr/bin/python /usr/bin/borg serve --umask=077 --info
```
But after several minutes the the process vanishes without anything happening on the client side.

It might be relevant that beforehand, I received and Input/output error from the kernel (without anything observable in smart monitor) for the USB HDD containing the backups. I then restarted the server and it was gone, so I think it could have been something kernel update related. I don’t think it is a problem anymore, but it might have lead up to it. Does the replaying of the segments happens all the time, or is it because he couldn’t read the  backup before? I read in the docs that it happens when the index is outdated?

Is it because the whole setup is to slow for the repository size (so far I though the upload is the bottleneck)? I’m just unsure because there is no more load on the server and no error message on the client side. And I couldn’t find a log on the server.

#### Edit:
I just noticed that the Replaying segments also happens when I do a borg check on the server and there I can use debug log level. I will update the issue if I have new results.

**Comment by ThomasWaldmann** [comment]
Replaying segments is not normal, it happens when the local cache contents (chunks index) is behind the committed repo state. Can happen if client crashes after committing the repo, before committing the local cache.

I am wondering: if you've seen an I/O error from the kernel, didn't that terminate borg also (with and `IOError / OSError` traceback?

I suspect you have some hardware or "below borg" software issue.

**Comment by tonke90** [comment]
Thanks for letting me know it is not normal behavior, Thomas. So it seems it was triggered by the I/O error before. I just ran a `borg check` over the night directly on the server and he finished the replaying segments part successful and I could do the backup without problems afterwards. So the problem is resolved for me. I’m just wondering if I wasn’t patient enough when it was triggered by the backup, or if it really got stuck (the missing CPU & I/O load was leading me to interrupt it and don’t wait longer).

The I/O error indeed produced a traceback in borg, but since it was resolved by a restart I didn’t save it, sorry.

I hope it wasn’t a hardware error. I actually don’t think so, since all the smart values look fine and it was resolved by the restart. It might be (the only thing I don’t like about Arch Linux) that he updated the kernel of the running system or something similar, without me restarting. But I will keep an eye on it.

```
smartctl 7.0 2018-12-30 r4883 [armv7l-linux-4.19.66-1-ARCH] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x002f   200   200   051    Pre-fail  Always       -       0
  3 Spin_Up_Time            0x0027   195   179   021    Pre-fail  Always       -       7241
  4 Start_Stop_Count        0x0032   100   100   000    Old_age   Always       -       82
  5 Reallocated_Sector_Ct   0x0033   200   200   140    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x002e   200   200   000    Old_age   Always       -       0
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       498
 10 Spin_Retry_Count        0x0032   100   253   000    Old_age   Always       -       0
 11 Calibration_Retry_Count 0x0032   100   253   000    Old_age   Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       41
192 Power-Off_Retract_Count 0x0032   200   200   000    Old_age   Always       -       26
193 Load_Cycle_Count        0x0032   200   200   000    Old_age   Always       -       405
194 Temperature_Celsius     0x0022   118   103   000    Old_age   Always       -       34
196 Reallocated_Event_Count 0x0032   200   200   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0032   200   200   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0030   100   253   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x0032   200   200   000    Old_age   Always       -       0
200 Multi_Zone_Error_Rate   0x0008   100   253   000    Old_age   Offline      -       0
```
