### ISSUE TITLE
windows: accept absolute paths as repo without explicit file protocol

### ISSUE THREAD

**Issue by jrast** [borgbackup/borg#4732]
On windows the repo path must be relative or the protocol (`file://`) must be explicitly specified. A standard (windows) absolute path, like `D:\Projects\` should also work.

This issue becomes relevant if #4696 is merged, some points where also discussed in the following comment / discussion: https://github.com/borgbackup/borg/pull/4696#discussion_r312008674

**Comment by ThomasWaldmann** [comment]
Fixed by #4862.
