### ISSUE TITLE
Show rsync like diff [feature request]

### ISSUE THREAD

**Issue by littlesandra88** [borgbackup/borg#4739]
With rsync one can do
```
rsync -avn --stats --delete-before --log-format='%i %12l %f' ...
```
and get a diff of the changes that would be made if the backup were done now. it would like the files that are deleted on the source, new files and modified files.

This would be a very useful feature so one can review the changes before doing a backup. In particular catch is files have been deleted from the source that were not suppose to be deleted.

**Comment by ThomasWaldmann** [comment]
rsync works differently than borg, it has access to both original and modified file (and also directories) and thus can rather easily show what's changed.

borg only sees the current file (and directory).

Additionally it has a "files cache" with a hash map `file-path --> file-metadata` (or more precisely, it is `H(file-path) --> file-metadata`).

It does not know about old directory contents, thus showing deleted files is not possible with what we have.

**Comment by littlesandra88** [comment]
Interesting.

Would it be difficult to make e.g. `--diff` or perhaps `--simulate-backup` which would access the destination and give an exact diff of new/modified/deleted files and directories?

**Comment by RonnyPfannschmidt** [comment]
i'd like to note that a "backup changes diff" doesnt apply in the context of borg as each backup itself is a full backup

and rsync style output for diff might make sense, a simulate option not

**Comment by ThomasWaldmann** [comment]
There is a trick (in some other ticket, not sure if already in the docs/faq) involving tar to show the diff between a borg archive and the fs.

Also, there is `borg diff`, but it can only show the diff between 2 borg archives.
