### ISSUE TITLE
Borg Cache Grows Linearly with Number of Backups

### ISSUE THREAD

**Issue by davidbartonau** [borgbackup/borg#4740]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, the docs and FAQ as well as #1766 and  #235.

## Is this a BUG / ISSUE report or a QUESTION?
I think it's a bug, but maybe I am using it wrong ;-)

#### Your borg version (borg -V).
Both: 1.1.10

#### Operating system (distribution) and version.
Client: 14.04
Server: 18.04

#### Hardware / network configuration, and filesystems used.
Xen Virtual Machine with one IP address.  2 filesystems ext3

#### How much data is handled by borg?
180G is the working data size
144G is the server repository size in ~560 backup snapshots
Each backup has ~8M files in it, they are 99% identical.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg create --debug --stats --progress --rsh "ssh -i /root/.ssh/id_rsa_backup" ssh://root@SERVER:22/mnt/borg-backups/vms/prod-imap-02/::root_$(date +%Y-%m-%d_%H:%M) /`

With excludes:
`borg create --debug --stats --progress --rsh "ssh -i /root/.ssh/id_rsa_backup" --exclude "/root/backups/zbackup*" --exclude "/var/lib/postgresql/*/main/" --exclude /dev --exclude /proc --exclude /sys --exclude /tmp --exclude /run --exclude "*/log/*" --exclude "*/logs/*" ssh://root@SERVER:22/mnt/borg-backups/vms/prod-imap-02/::root_$(date +%Y-%m-%d_%H:%M) /`

## Describe the problem you're observing.
I am switching from zbackup to borg, and have been running full disk remote backup (excluding special file systems).

Recently I had a multi-disk failure and had to restore from backup.  Restoring worked well, and I was able to get the server up and running again.

Now when I try to resume the backups, I get the following problems:

1. Previously, there was no /root/.cache/borg but this time borg tries to create a local cache.  This should not be a big deal, but because of 2, it is a showstopper
2. Every single snapshot causes borg to pull ~250- 300M in a chunk file 

At this rate, my chunk cache will exceed my backup size :-(

```
using builtin fallback logging configuration
35 self tests completed in 0.23 seconds
SSH command line: ['ssh', '-i', '/root/.ssh/id_rsa_backup', '-p', '22', 'root@[snip]', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.31 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/mnt/borg-backups/vms/prod-imap-02'
Remote: Resolved repository path to '/mnt/borg-backups/vms/prod-imap-02'
Remote: Verified integrity of /mnt/borg-backups/vms/prod-imap-02/index.5336
TAM-verified manifest
security: read previous location 'ssh://root@[snip]:22/mnt/borg-backups/vms/prod-imap-02'
security: read manifest timestamp '2019-08-27T05:11:13.398068'
security: determined newest manifest timestamp as 2019-08-27T05:11:13.398068
security: repository checks ok, allowing access
Creating archive at "ssh://root@[snip]:22/mnt/borg-backups/vms/prod-imap-02/::root_2019-08-30_08:06"
Reading files cache ...
security: read previous location 'ssh://root@[snip]:22/mnt/borg-backups/vms/prod-imap-02'
security: read manifest timestamp '2019-08-27T05:11:13.398068'
security: determined newest manifest timestamp as 2019-08-27T05:11:13.398068
security: repository checks ok, allowing access
Synchronizing chunks cache...                                                                                                                                                                               
Archives: 563, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 563.
Fetching and building archive index for root_2019-08-04_18:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-06-05_18:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-08-16_03:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-06-14_00:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-08-22_12:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-08-27_12:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-08-26_00:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-08-16_00:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-08-27_06:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-07-31_18:29 ...29                                                                                                                                         
Merging into master chunks index ...
Fetching and building archive index for root_2019-07-25_06:29 ...29                                                                                                                                         
Merging into master chunks index ...
etc.
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Running the borg command above reproduces it

A possible workaround is to prune the repository to reduce the number of snapshots.  I might give that a go and post my results.

**Comment by davidbartonau** [comment]
I am trying to prune the cache on the server itself
```
borg prune --dry-run --list --debug --keep-last 12 --keep-daily 7 --keep-weekly 4 --keep-monthly -1 /mnt/borg-backups/vms/prod-imap-02/
```
For some reason it needs to build a local cache for the local repo.  I ran out of disk space.  I've moved the cache dir and will try again.

**Comment by davidbartonau** [comment]
It's taking about 1 - 2 mins to download the cache for each archive index.  This means it will take half a day to rebuild the chunk index.

Is this expected behaviour?  A key advantage of borg over zbackup was the fact that borg includes tarlike functionality.  However large file counts seem to make this feature problematic when you try to operate on it.

**Comment by ThomasWaldmann** [comment]
The docs have a workaround for situations one does not like the chunks.archive.d cache storage needs.

What you experience is just the usual space vs. time optimization conflict, often it is not possible to have low space and fast speed, so you need to choose.

The chunks.archive.d is needed as a way to locally (and relatively quickly, because there is not much "fetching stuff from remote") build a matching master chunks index from a set of cached per-archive partial indexes.

The alternative is not having that cache (see workaround) and always fetching the per-archive chunks information from remote - that is always slow, not only once.

(Re-)building that master chunks index is only needed if the repo is out of sync with the current local index - this only happens if you work in same repo from multiple machines. Thus, not doing that is another way to optimize.

Another way is to reduce your archive count. It might be not very likely that you really need that many, so adjusting `borg prune` parameters to cut down the archive count would also cut down the effort needed to deal with them.

**Comment by ThomasWaldmann** [comment]
And no, that is not a bug, but expected behaviour.

**Comment by davidbartonau** [comment]
`borg prune --dry-run` just finished after 9h.  The cache is 155G vs 144G for the repository.

@ThomasWaldmann I am _trying_ to prune the archive, but as you can see it is building the cache.  It seems really odd to have a cache that is a) bigger than the source file and b) on the same machine. c) increases linearly with the number of backups even _if they are storing the same thing_ 

I might have a go to see what the performance implications of having the index are vs not having it.  Not having an index sounds scary, but my server was backing up for months without it and it seemed fine.

Right now I am trying to prune the archive and expect that to take a day.  Would you be willing to include some space / time benchmarks so that people can see what the overhead of various backup strategies are?

**Comment by andir** [comment]
I have a similar case where I backup a server very frequently in append-only mode. As soon as I prune it on the target server the cache on the backup source explodes and causes out of disk space issues. The cache is also larger than the actual borg archive size. My current workaround is to not prune individual borg archives but to rotate them, wait N days, delete the old archive.

**Comment by ThomasWaldmann** [comment]
@andir see https://github.com/borgbackup/borg/issues/4740#issuecomment-526551592

**Comment by davidbartonau** [comment]
@andir that sounds painful.  You could tar the files and feed them into borg, and that might fix the problem.

In the end, I've reverted back to zbackup as the cache issue was unworkable.  Although that seems unmaintained recently, it's worked for me for 8+ years and I'd rather use something that works and hopefully a better solution comes along.

**Comment by ThomasWaldmann** [comment]
Looks like it is too hard to find this in the docs, so here is a direct link.

https://borgbackup.readthedocs.io/en/stable/faq.html#the-borg-cache-eats-way-too-much-disk-space-what-can-i-do

Creating a directory to avoid unwanted caching is no way "unworkable", but very easy to do.
