### ISSUE TITLE
Many files marked as modified for no apparent reason

### ISSUE THREAD

**Issue by rolandu** [borgbackup/borg#4747]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. My issue is similar to "It always chunks all my files, even unchanged ones!", but I only backup exactly one location using exactly the same settings. So the answer in the FAQ did not really help me.

## Is this a BUG / ISSUE report or a QUESTION?

Question / support request

#### Your borg version (borg -V).

- borg 1.1.5

#### Operating system (distribution) and version.

- Linux Mint 19.1 on Linux 4.15.0-58-generic x86_64

#### Hardware / network configuration, and filesystems used.

- source: local files (ext4)
- target: fuse.sshfs (server is Debian 9 (stretch) / Linux 4.9.0-9-amd64 x86_64 / ext4)

#### How much data is handled by borg?

```
------------------------------------------------------------------------------
Archive name: L3-2019-09-02T20:50:14
Archive fingerprint: xxx
Time (start): Mon, 2019-09-02 20:50:19
Time (end):   Mon, 2019-09-02 21:16:50
Duration: 26 minutes 30.85 seconds
Number of files: 502149
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              275.10 GB            253.88 GB            124.84 MB
All archives:                2.27 TB              2.10 TB            249.88 GB

                       Unique chunks         Total chunks
Chunk index:                  611475              5398895
------------------------------------------------------------------------------
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
export BORG_SOURCES='/etc /home /root /var'

borg create                      \
--stats                          \
--compression lz4                \
--exclude-caches                 \
--exclude-from $BORG_EXCLUDEFILE \
--list                           \
--filter=AME                     \
--noatime                        \
::'{hostname}-{now}'             \
$BORG_SOURCES
```

## Describe the problem you're observing.

The "list" option allows me to see that borg considers almost every file in /home as modified (shown as "M <filename>"), even though nothing has changed and even if executing backups directly one after another.

Expected behavior: Only a handful of files in home should be modified within those few minutes.

I added the "--noatime" option recently because I believed that automatic processes might access all the files regularly in the background. However, this did not lead to any changes in the behavior.

The total deduplicated size of the backup is still only 100MB, so it seems that only a lot of metadata gets stored.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, happens every time.

#### Include any warning/errors/backtraces from the system logs

No errors.

**Comment by ThomasWaldmann** [comment]
For the files shown as modified, check the ctime, inode number and size for changes.

Also, you could try a more recent borg release, you can get it from the debian backports repository.

**Comment by rolandu** [comment]
I believe ctime is the issue here. I just learned what this is right now. I have a cron script that resets permissions on the home directories every half hour... it seems that even if nothing is changed, the ctime is updated on all the files. I am testing this now.

Question: if I use "--noctime" will borg still backup changed permissions or is ctime needed for it to work properly?

**Comment by infectormp** [comment]
@rolandu btw, newer version of borg is available

**Comment by rolandu** [comment]
I would prefer to stay with the version my distro provides unless there are serious issues.

Test complete. cdate was the issue. Backup is much faster now. I will either use --noctime or disable/modify my permissions script.

**Comment by ThomasWaldmann** [comment]
@rolandu a cron-script resetting permissions sounds unusual and might be a indication that you are doing something wrong maybe.

Ignoring `ctime` (removing it from `--files-cache`) is maybe no good idea either.

I'ld try to get rid of that cron script and solving the root cause of your issue otherwise.

If that is not possible, you could use find to only change the files that actually need changing (not touching all files).

Or using mtime instead of ctime for `--files-cache` (borg 1.0 used mtime, but that is not the default any more since borg 1.1 because it is less safe as a change detection than ctime).

**Comment by rolandu** [comment]
> @rolandu a cron-script resetting permissions sounds unusual and might be a indication that you are doing something wrong maybe.

@ThomasWaldmann Maybe I am doing something wrong. I observed that many desktop programs add group/other permissions to files by default. Therefore I wrote a script that basically does `chown -R myuser:myuser /home/myuser && chmod -R o-rwx /home/*` - do you think it is a bad idea?

**Comment by ThomasWaldmann** [comment]
A normal desktop program runs as your normal user/group and will create files with your uid and gid, so regarding that, all should be fine. Considering the permissions, these are influenced by the umask set and that is usually set to a sane default also (depends on how groups are managed, but usually it at least takes away all permissions from "others", maybe also some or all from "group").

What easily can go wrong, is if there is some habit to do a lot of stuff as "root" (maybe in some cases without a real need) - of course if you create files as root, you'll have troubles using them as your normal user.
