### ISSUE TITLE
Borg mount empty for old attic archive

### ISSUE THREAD

**Issue by aljungberg** [borgbackup/borg#4748]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

Borg: 1.1.10
Python: CPython 3.7.4 
msgpack: 0.5.6

#### Operating system (distribution) and version.

macos 10.14.6

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg mount -f repo::"20161222_RESJ" /tmp/jic

## Describe the problem you're observing.

Mounted archives are empty.

For certain archives, borg shows no files in the mount point. But `borg extract` on the same archive works fine.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I don't know how to reproduce this, I got this archive by upgrading from attic to borg. But I can offer a theory of what's wrong. Please bear with me, I might have absolutely no idea what I'm talking about, I'm not familiar with the code base. 

This is the structure of my archive:

```
borg list repo::"20161222_RESJ"|head
drwxr-xr-x root   wheel         0 Tue, 2016-12-20 11:01:43 .
-rw-rw-r-- root   admin     12292 Wed, 2019-08-14 13:19:00 ./.DS_Store
d--x--x--x root   wheel         0 Thu, 2019-08-15 09:32:28 ./.DocumentRevisions-V100
drwx------ root   wheel         0 Wed, 2017-06-21 22:20:43 ./.DocumentRevisions-V100/.cs
drwxr-xr-x root   wheel         0 Thu, 2015-07-16 01:46:17 ./.DocumentRevisions-V100/.cs/ChunkStorage
drwxr-xr-x root   wheel         0 Thu, 2015-07-16 01:46:17 ./.DocumentRevisions-V100/.cs/ChunkStorage/0
drwxr-xr-x root   wheel         0 Thu, 2015-07-16 01:46:17 ./.DocumentRevisions-V100/.cs/ChunkStorage/0/0
drwx------ root   wheel         0 Tue, 2017-07-11 14:16:03 ./.DocumentRevisions-V100/.cs/ChunkStorage/0/0/0
-rw-r--r-- root   wheel   7520256 Tue, 2017-07-11 14:26:25 ./.DocumentRevisions-V100/.cs/ChunkStoreDatabase
-rw-r--r-- root   wheel         0 Tue, 2017-07-11 14:26:25 ./.DocumentRevisions-V100/.cs/ChunkStoreDatabase-wal
```

Note that everything in the archive is under `./`.

Now in borg's `fuse.py` we've got this:

```python
    def readdir(self, fh, off):
        entries = [(b'.', fh), (b'..', self.parent[fh])]
        entries.extend(self.contents[fh].items())
```

`.` always links to itself (which makes sense). 

But when mounting these archives and doing readdir on the root folder, `self.contents[fh].items()` ALSO contains `.`. This looks strange to me. This is what `entries` looks like after the above code:

```python
[(b'.', 1), (b'..', 1), (b'.', 1000032)]
```

So we have `.` linking back to the root inode, 1. But then there's also a folder named `.` that links somewhere else. Two folders with the same name. I think this is what breaks the mount, and even if it doesn't break it directly, the content of this "extra" `.` is inaccessible.

A workaround is to use `--strip-components 1` to get rid of the leading `./` when mounting.

**Comment by ThomasWaldmann** [comment]
Hmm, yeah, sounds like a bug - I'll have a look.

Thanks for finding / initial analysis!

**Comment by ThomasWaldmann** [comment]
Can you upload a small attic repo (as .tgz or .zip) that reproduces the problem?

**Comment by aljungberg** [comment]
It only happened with my (not at all small) attic repo and when I tried to reproduce it by creating a new archive the same way as the old one it didn't happen. For all I know this could be an old bug in attic -- I've been using it for quite a while.

**Comment by ThomasWaldmann** [comment]
OK, I'll try fixing it without.

**Comment by ThomasWaldmann** [comment]
I just made a backup with borg and tried to get paths into the archive which start with `./`, couldn't do that. As you also could not do that with the "latest" attic, I guess it is a bug in path processing for some old attic version.

It could be avoided by adding some code to the loop in `process_archive` in fuse.py, but that would make it a bit slower for everybody.

Considering that you found that workaround that also solves the problem, I guess I rather not make it slower just to handle that case.
```
A workaround is to use --strip-components 1 to get rid of the leading ./ when mounting.
```

**Comment by ThomasWaldmann** [comment]
guess this can be closed.
