### ISSUE TITLE
master: python setup.py build_man is broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4752]
somehow it doesn't process `borgfs` correctly:

```
$ python setup.py build_man
Detected OpenSSL [via pkg-config]
Using bundled BLAKE2
Detected and preferring liblz4 [via pkg-config]
Using bundled ZSTD
Using bundled xxhash
running build_man
building man pages (in docs/man)
building man page borg-benchmark(1)
building man page borg-benchmark-crud(1)
building man page borgfs(1)
building man page borg-borgfs-benchmark(1)
building man page borg-borgfs-benchmark-crud(1)
error: [Errno 2] No such file or directory: 'docs/usage/borgfs_benchmark_crud.rst'
```

**Comment by ThomasWaldmann** [comment]
Because of that, the related man pages will be missing in 1.2.0a7.

**Comment by Gu1nness** [comment]
Hum,
I'm interested by this one.
However I'm not sure if it is just a matter of creating the good files for the borgfs commands, or some python code in the setup_docs.py file (which reads the files) in order to create them automatically.

**Comment by ThomasWaldmann** [comment]
The goal is to fix `python setup.py build_man` (or the `argparse` related code in `borg.archiver`?), so that build_man works without an issue.

`borg` is the usual cli command to invoke borgbackup, `borgfs` is a special cli command using by `fstab` / `mount` only in context of mounting a borg repo / archive.

`borg benchmark crud` exists as a command, but stuff like `borgfs benchmark crud` doesn't make sense nor does it need docs to be generated.

**Comment by Gu1nness** [comment]
Ok right,
I'll have a look at it then!
Thanks for your answer!

**Comment by ThomasWaldmann** [comment]
BTW, this is likely a regression compared to older borg releases - I only noticed this brokenness recently.
So maybe checking older releases whether they work ok and comparing new to older code could give hints about what is broken.

**Comment by Gu1nness** [comment]
Sure!
I'll have a look at the former releases!

**Comment by Gu1nness** [comment]
As I said in the commit message, the issue #4471 generated way more problems than what was reported here.
It actually created all the commands that existed for borg but for borgfs, creating a duplicate command of borg.
This might be something you want to release soon in order to have everything patched ASAP.
