### ISSUE TITLE
Feature request: borg server with restrict to archive

### ISSUE THREAD

**Issue by stevekerrison** [borgbackup/borg#4757]
I am looking at the feasibility of having multiple clients backup to the same repository, to benefit from deduplication, but without the ability of each client to interact with any other's archives.

This would be similar to how [`borg serve --restrict-to-repository`](https://borgbackup.readthedocs.io/en/stable/deployment/hosting-repositories.html) works, but at the archive level.

After a brief dip into the code, it looks like the work would go mostly into the `Archiver`. For example:

* Add a `--restrict-to-archive` argument to to `serve`, add a new `restrict_to_archives` list, update blacklists etc.
* Consume this list of paths in the relevant `do_*` functions, for example `do_create` and `do_delete` or `_delete_archives`
* Write tests to ensure that introducing this option, and any restrictions passed via it, don't adversely affect other operations on the repo, and behave as expected.

In addition, there's the following performance and security considerations:

* The repository still needs a lock, so clients must wait their turn
  * Fine, that's a pre-existing constraint
* All clients share the same repository key, which potentially increases the attack surface for the repository key
  * Each client may protect the key with its own passphrase or other method, for example the key could be GPG distributed (an out-of-band activity from Borg).
  * Clients don't have access to the remote repository as a whole, only via `borg serve`, therefore a compromised key is not *immediately* exposing the repo.
  * The repository location should have additional at-rest encryption for the data, and mitigation against direct access to the repository.
  * The key could be periodically changed but that would require privileged access and re-generating the whole repo (I think?), and only provides some protection is there's a lag between key compromise and gaining access to the repository data.
* One would need to ensure a client cannot break out of the archive restriction
  * Sticking to simple archive prefixes may be a good start.
* A malicious client may, with some effort, be able to learn something about data other clients are storing in the repo, by the impact of their archive updates on the repo size and deduplication factor.
  * It's assumed that clients are collaborate, but want to benefit from some sort of privacy. Therefore they're not unknown to each other, and have other reasons not to be malicious towards each other. However, this potential risk may be a no-go for other use cases.

I may have a go at implementing this, but before embarking on such a thing, wanted to field it to see if there's any gotcha I've *not* considered.

Thanks.

**Comment by ThomasWaldmann** [comment]
the borg serve side of a client/server borg is assumed to only see encrypted data.

so it can not see archives, so your feature request is not possible within that design.

**Comment by ThomasWaldmann** [comment]
also, if 2 parties access the same repo, it is currently required that the parties trust each other.

there is only one encryption key, each client could delete every chunk they want.

so, you must use different repos if there is no trust.

**Comment by stevekerrison** [comment]
I realised after poking around a bit more that archives were only understood client side, so what you say matches up with that, thanks.

It doesn't seem like it would be feasible to introduce this feature, as it goes against the way the server & chunks work. So, into the bucket of good but useless ideas is goes...

Thanks for your input!
