### ISSUE TITLE
Feature request: Mark archive as don't-prune

### ISSUE THREAD

**Issue by Catscrash** [borgbackup/borg#4758]
Hi,

it would be great, if we could mark one specific backup as not-pruneable, so that - even if it would be deleted by the given --keep-... settings, it will not be pruned. 

Use case is to keep a backup of a specific date, but keep the rest of the prune-settings intact.

best regards

**Comment by infectormp** [comment]
same https://github.com/borgbackup/borg/issues/4754?

**Comment by Catscrash** [comment]
Hi @infectormp. Thanks for your answer.

Partly... The given answer regarding the prefix does help a bit, I can of course change my prune-scripts to have --prefix in there and then rename the backup I want to keep to be different... still an option to somehow flag the backup of today and prune will just not touch it would be nicer and easier in my opinion

**Comment by infectormp** [comment]
So you want mark archive inside of repo as immutable?

**Comment by Catscrash** [comment]
Yep. Not as a security feature, just as a protection against pruning, as I might want to keep exactly this archive longer than pruning would usually allow

**Comment by infectormp** [comment]
Then I would suggest change "backup" to "archive" in issue summary to deal with Borg terminology

**Comment by Catscrash** [comment]
Good idea, thanks, done

**Comment by ThomasWaldmann** [comment]
If you use --prefix for prune, you can just rename an archive to a non-matching name, so it won't prune it.

**Comment by grinapo** [comment]
Could this be included in the documentation/FAQ please? 
This seems to be a fairly common desire: "I have to keep the yesterday's backup because it contains The Things The Disaster Deleted Today".

**Comment by ThomasWaldmann** [comment]
borg2: see #953.
