### ISSUE TITLE
progress-indication auto-enable conflicts with --verbose

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#476]
the progress indicator for create needs to be able to output on the same line repeatedly (using the \r trick to overwrite the line again and again).

but --verbose causes scrolling. that's not a problem per se as the user could decide between the two, but if a console user gives `borg create -v`, we automatically enable progress indication also because we always do that when a tty is connected.

i suggest to remove the automatic progress indication enabling. too much magic.

**Comment by DrupaListo-com** [comment]
+1 for removing the magic behaviour.
As for the --progress / --no-progress question: you ARE on the right track namely:
1. when --progress given - show progress
2. dont even have a --no-progress option
3. when nothing given ( NO --progress given), logically = no progress indicatior

So yeah, people who need --progress will just call it as a swtich and all is happy.
People who want changed files listings, will dont give --progress swtich at all and just use --verbose.
( I use 
--verbose
--filter AM

so I can see only the relevant to me changes.
)

**Comment by ThomasWaldmann** [comment]
please always include the E status in filters, it is used for errors which you likely don't want to miss.

**Comment by DrupaListo-com** [comment]
noted. Updated my wrapper conf.

**Comment by witten** [comment]
Even with the progress disabled by default by now, it's a little unexpected that when a user combines `--progress` with `--list`, they get garbled output due to the `\r` trick. Is it worth filing this as a separate ticket, or is the solution "just don't do that"? Thanks.

Context: https://projects.torsion.org/witten/borgmatic/issues/257

**Comment by ThomasWaldmann** [comment]
It's "just don't do that".

**Comment by witten** [comment]
Thanks. I'll work around it then!
