### ISSUE TITLE
data loss: borg prune -P-- affects all archives

### ISSUE THREAD

**Issue by horazont** [borgbackup/borg#4769]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

borg 1.1.10

#### Operating system (distribution) and version.

Debian testing, Debian stable (both)

#### Hardware / network configuration, and filesystems used.

ext4, tmpfs

#### How much data is handled by borg?

several TB, a few MB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ borg prune -d7 --stats -P-- io
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes:

```
$ borg init -e none test
$ borg create "test::test-$(date --iso-8601=seconds)" icons
$ borg create "test::--$(date --iso-8601=seconds)" icons
$ borg create "test::test-$(date --iso-8601=seconds)" icons
$ borg create "test::--$(date --iso-8601=seconds)" icons
$ borg prune -n --list --keep-hourly 1 -Ptest- test
Keeping archive: test-2019-09-29T18:11:06+02:00       Sun, 2019-09-29 18:11:06 [9d1c048374200473d4c2155488e24e8e6ea37c1b257e2bd684dff0c49f1f73cf]
Would prune:     test-2019-09-29T18:10:57+02:00       Sun, 2019-09-29 18:10:57 [f2d53c6752713f68d7e1409784ee22cdb2e8ca7094286e0199bbf919c5548c86]
$ borg prune -n --list --keep-hourly 1 -P-- test
Keeping archive: --2019-09-29T18:11:09+02:00          Sun, 2019-09-29 18:11:09 [6f59a4b2575626a2a8fa748be6e44abd6bb4db17ee1db0dfe67ab10b095ea71e]
Would prune:     test-2019-09-29T18:11:06+02:00       Sun, 2019-09-29 18:11:06 [9d1c048374200473d4c2155488e24e8e6ea37c1b257e2bd684dff0c49f1f73cf]
Would prune:     --2019-09-29T18:11:02+02:00          Sun, 2019-09-29 18:11:03 [795d5c84deb4d646135ae7fcf853a2f7537418b81f91aefba74a8e9bc097e5bb]
Would prune:     test-2019-09-29T18:10:57+02:00       Sun, 2019-09-29 18:10:57 [f2d53c6752713f68d7e1409784ee22cdb2e8ca7094286e0199bbf919c5548c86]
```

As you can see, ``borg prune`` will prune *all* archives when invoked with ``-P--``. This does not happen with ``-P-`` or ``-P---``. It also happens with  ``--prefix=--``, but not with ``'-a--*'``.

I would expect borg to either:

- Complain about a malformed argument if it can’t deal with ``--`` for whatever reason, or
- Operate correctly only pruning archives starting with ``--``

Instead, it pruned away many my backups because I assumed this would work :/ and did not do another ``--dry-run``.

**Comment by ThomasWaldmann** [comment]
Uuh, that is a strange bug.

I suspect you somehow confused python's `argparse` command line argument parsing, so that it thought `--` is another option and not the value for `--prefix` / `-P` and used an empty string there.

I'm sorry it pruned all your old backups.

Yeah, doing another `prune --dry-run` could have avoided it (or not using strange prefixes that can be confused with options).

**Comment by ThomasWaldmann** [comment]
As this might be a python argparse bug, can you please give the python version used by the borg client?

Did you use the borgbackup package from debian or the fat binary downloaded from us from github releases page?

**Comment by ThomasWaldmann** [comment]
BTW, you maybe don't need the `$(date ...)` call, have a look at borg's `{now}` placeholder.

**Comment by horazont** [comment]
Python: Python 3.7.4+. I use the debian package.

```
borgbackup:
  Installed: 1.1.10-2
  Candidate: 1.1.10-2
  Version table:
 *** 1.1.10-2 990
        990 http://ftp.de.debian.org/debian testing/main amd64 Packages
        500 http://ftp.de.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ThomasWaldmann** [comment]
So you use py 3.7.3? (first sentence contradicts output below)

**Comment by horazont** [comment]
This is indeed an argparse issue:

##### foo.py
```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-P", "--prefix")
parser.add_argument("foo")
parser.add_argument("bar")

print(parser.parse_args())
```

```console
$ python3 foo.py -P xyz foo bar
Namespace(bar='bar', foo='foo', prefix='xyz')
$ python3 foo.py -P'-- foo' foo bar
Namespace(bar='bar', foo='foo', prefix='-- foo')
$ python3 foo.py -P'--' foo bar
Namespace(bar='bar', foo='foo', prefix=[])
```

This is super creepy. As a first measure, I suggest that borg rejects ``-P`` if it’s an empty list. As a second measure, we should figure out if this is intended behaviour.

**Comment by ThomasWaldmann** [comment]
Also noticeable: see how the prefix value changes from a str to an empty list when `--` is encountered.

**Comment by horazont** [comment]
> So you use py 3.7.3? (first sentence contradicts output below)

Huh, indeed.

```console
$ python3 --version
Python 3.7.4+
$ apt policy python3
python3:
  Installed: 3.7.3-1
  Candidate: 3.7.3-1
  Version table:
     3.7.5-1 500
        500 http://ftp.de.debian.org/debian unstable/main amd64 Packages
 *** 3.7.3-1 990
        990 http://ftp.de.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
```

Not sure what to make of that.

> Also noticeable: see how the prefix value changes from a str to an empty list when ``--`` is encountered.

Yes, this is very concerning. Maybe as a first-aid measure, borg could detect that ``prefix`` is an empty list (as opposed to an empty string or None) and error out in that case. I think this is a terrible hack, but silently deleting all the archives is worse :/.

**Comment by ThomasWaldmann** [comment]
See #4774.

I did not like to forbid giving an empty value for `--prefix` as when some code computes the value, the empty value might well be a desired, valid value.

But I changed the code so that it internally differentiates whether --prefix has been given on the commandline (or not) and also that for any case it has been given, processing is the same (== compute glob_archives value from `args.prefix + '*'`). As this is only a valid operation for `str`, it will crash with a TypeError when argparse misbehaved and gave a `[]` value (instead of the str `--`).

**Comment by ThomasWaldmann** [comment]
@horazont did you already file an issue in the Python issue tracker?

**Comment by horazont** [comment]
@ThomasWaldmann I just searched for one and found this: https://bugs.python.org/issue14364

So it’s already reported.

**Comment by ThomasWaldmann** [comment]
Oh, open since 7.5y!

**Comment by horazont** [comment]
FTR, I left a comment confirming that the patches in the issue *do* work: https://bugs.python.org/issue14364?#msg353865
