### ISSUE TITLE
Different chunker params for a directory?

### ISSUE THREAD

**Issue by ss-17** [borgbackup/borg#4775]
Hi.

Its not really a issue. Just a query. While creating an archive, Is it possible to have different chunker params for a particular directory and apply default to the rest?

Thanks.

**Comment by RonnyPfannschmidt** [comment]
currently im not aware of a mechanism that supports that

**Comment by ss-17** [comment]
Thanks :)

**Comment by ThomasWaldmann** [comment]
You can use different borg create commands or even separate repos if you have a really good reason to do so. You could do some "benchmarks" to check whether it's really worth it.

Be aware of small chunk size producing a lot more chunks, needing a lot more memory - that can be a problem if your repo size vs. ram size is somehow unbalanced.

**Comment by szpak** [comment]
Related to #1005.

**Comment by ThomasWaldmann** [comment]
Guess having #1005 open for this is enough.
