### ISSUE TITLE
Feature request: Borgbackup in pull data mode

### ISSUE THREAD

**Issue by ledufakademy** [borgbackup/borg#4780]
I know that this is not an issue BUT ... push data to a repository can be, in certain circumstance, a very big security issue.
So is it possible to implement a features in order to backup a remote file system and store it in a local (or distant why not) borgbackup repository.
i already do that with sshFS ..so technically it's fully doingable.

Thank you for reading me.

**Comment by ThomasWaldmann** [comment]
IIRC there are already other tickets talking about pull mode ideas, so closing this one as duplicate.
