### ISSUE TITLE
Do you want to continue? [yN]

### ISSUE THREAD

**Issue by raph431** [borgbackup/borg#4786]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg 1.1.5
#### Operating system (distribution) and version.
Ubuntu 18.04.1 LTS
#### Hardware / network configuration, and filesystems used.
GB-BXBT-2807 ext3
#### How much data is handled by borg?
30GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg check ...

## Describe the problem you're observing.
Warning: The repository at location ssh://... was previously located at ssh://...
Do you want to continue? [yN] 

This is really annoying if you move your backup and cannot schedule your backup automatically because of this warning. Please include some --force option, that will say "yes" to this question.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes. I even had to reproduce the problem, because my ssh connection breaks down if I just wait for this prompt. So I have to press return every few minutes to even get this prompt.

**Comment by infectormp** [comment]
@raph431 please read the docs https://borgbackup.readthedocs.io/en/stable/usage/general.html

**Comment by fantasya-pbem** [comment]
> @raph431 please read the docs https://borgbackup.readthedocs.io/en/stable/usage/general.html
BORG_RELOCATED_REPO_ACCESS_IS_OK

**Comment by raph431** [comment]
I'm sorry for bothering you. I have overlooked those environment variables. Thank you very much for your help and your great backup solution.
