### ISSUE TITLE
error handling of deleted file

### ISSUE THREAD

**Issue by DanielDent** [borgbackup/borg#479]
borg was used to back up directory "/x". When the backup was started, "/x" contained "/x/foo", as well as "/x/bar".

"/x/foo" took a long time to process. By the time borg got to "/x/bar", "/x/bar" didn't exist - it had been deleted.

/x/bar: [Errno 2] No such file or directory: '/x/bar'
Command '('borg', 'create', 'backupsetname::here, ''/x', '--compression', 'none')' returned non-zero exit status 1

**Comment by ThomasWaldmann** [comment]
There is already an error handler: it just emits the warning msg, then skips that file and proceeds with backing up subsequent files (if any).

The rc 1 you are seeing is a warning (in that case: that it did not backup all files), but not an error (that would be rc 2, at least in recent borgbackup versions).

If you do not want to see warnings, you can try excluding places without important files, but with expected issues, like `/tmp/*`.

**Comment by anarcat** [comment]
you can also create a filesystem snapshot on which borg can then operate.  see also #325.

**Comment by ThomasWaldmann** [comment]
closing this, no bug.
