### ISSUE TITLE
Corrupted segment reference count when using rclone mount

### ISSUE THREAD

**Issue by Cubox** [borgbackup/borg#4795]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue (I think)

#### Your borg version (borg -V).

1.1.10

#### Operating system (distribution) and version.

FreeBSD 12.0-STABLE

#### Hardware / network configuration, and filesystems used.

amd64.
local filesystem is zfs, trying to backup into rclone fuse mounted Gdrive

#### How much data is handled by borg?
20G approx

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create -p -e /root/.cache -C zlib,6 -v /gdrive::Onyx-2019-10-19T23:13 /usr/home /etc /root /www/cubox /www/fbh /usr/local/etc

## Describe the problem you're observing.

Corrupted segment reference count - corrupted index or hints when trying to use borg onto rclone's mounted filesystem.
They are using fusefs.

I am well aware this might be an issue with rclone only, that borg might be doing everything good.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes.
Mount target filesystem like this:
`rclone -v --config /home/cubox/.rclone.conf --vfs-cache-mode full --cache-dir /tmp/rclone mount Gdrive:Onyx/Borg /gdrive`
Init borg repo using this:
`borg init /gdrive -e repokey-blake2`

```Failed to securely erase old repository config file (hardlinks not supported>). Old repokey data, if any, might persist on physical storage.

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam /gdrive

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).
```

Then try to backup with `borg create -p -e /root/.cache -C zlib,6 -v /gdrive::Onyx-2019-10-19T23:13 /usr/home /etc /root /www/cubox /www/fbh /usr/local/etc`

Watch in horror the following error message:
```Creating archive at "/gdrive::Onyx-2019-10-19T23:13"
Local Exceptionents   0%
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 573, in do_create
    create_inner(archive, cache)
  File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 538, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/local/lib/python3.7/site-packages/borg/archive.py", line 515, in save
    self.repository.commit()
  File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 442, in commit
    self.compact_segments()
  File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 789, in compact_segments
    assert segments[segment] == 0, 'Corrupted segment reference count - corrupted index or hints'
AssertionError: Corrupted segment reference count - corrupted index or hints

Platform: FreeBSD Onyx 12.0-STABLE FreeBSD 12.0-STABLE r347964 GENERIC amd64
Borg: 1.1.10  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 65451  CWD: /root
sys.argv: ['/usr/local/bin/borg', 'create', '-p', '-e', '/root/.cache', '-C', 'zlib,6', '-v', '/gdrive::Onyx-2019-10-19T23:13', '/usr/home', '/etc', '/root', '/www/cubox', '/www/
fbh', '/usr/local/etc']
SSH_ORIGINAL_COMMAND: None
```

#### Include any warning/errors/backtraces from the system logs

Here is the output from rclone

```2019/10/19 23:11:24 INFO  : Cleaned the cache: objects 0 (was 0), total size 0 (was 0)
2019/10/19 23:11:51 INFO  : README: Copied (new)
2019/10/19 23:11:53 INFO  : config.tmp: Copied (new)
2019/10/19 23:11:54 INFO  : config.tmp: Moved (server side)
2019/10/19 23:11:57 INFO  : lock.exclusive/Onyx@14038007751194.65290-0: Copied (new)
2019/10/19 23:11:58 INFO  : lock.roster: Copied (new)
2019/10/19 23:11:59 INFO  : config: Copied (new)
2019/10/19 23:12:01 INFO  : config.tmp: Copied (new)
2019/10/19 23:12:02 INFO  : config: Deleted
2019/10/19 23:12:02 INFO  : config.tmp: Moved (server side)
2019/10/19 23:12:04 INFO  : nonce.tmp: Copied (new)
2019/10/19 23:12:05 INFO  : nonce.tmp: Moved (server side)
2019/10/19 23:12:09 INFO  : data/0/0: Copied (new)
2019/10/19 23:12:10 INFO  : data/0/1: Copied (new)
2019/10/19 23:12:12 INFO  : hints.1.tmp: Copied (new)
2019/10/19 23:12:14 INFO  : index.1.tmp: Copied (new)
2019/10/19 23:12:15 INFO  : integrity.1.tmp: Copied (new)
2019/10/19 23:12:16 INFO  : integrity.1.tmp: Moved (server side)
2019/10/19 23:12:17 INFO  : hints.1.tmp: Moved (server side)
2019/10/19 23:12:17 INFO  : index.1.tmp: Moved (server side)
2019/10/19 23:12:18 INFO  : integrity.1: Copied (new)
2019/10/19 23:12:18 INFO  : index.1: Copied (new)
2019/10/19 23:12:20 INFO  : lock.roster: Copied (replaced existing)
2019/10/19 23:12:20 INFO  : lock.roster: Removed from cache
2019/10/19 23:12:20 INFO  : lock.exclusive/Onyx@14038007751194.65290-0: Removed from cache
2019/10/19 23:12:24 INFO  : Cleaned the cache: objects 16 (was 17), total size 82.771k (was 0)
2019/10/19 23:13:21 INFO  : lock.exclusive/Onyx@14038007751194.65451-0: Copied (new)
2019/10/19 23:13:22 INFO  : lock.roster: Copied (new)
2019/10/19 23:13:23 INFO  : config: Copied (replaced existing)
2019/10/19 23:13:24 INFO  : nonce: Copied (new)
2019/10/19 23:13:24 INFO  : Cleaned the cache: objects 19 (was 19), total size 83.572k (was 82.771k)
2019/10/19 23:13:25 INFO  : nonce.tmp: Copied (new)
2019/10/19 23:13:26 INFO  : nonce: Deleted
2019/10/19 23:13:27 INFO  : nonce.tmp: Moved (server side)
2019/10/19 23:13:27 INFO  : hints.1: Copied (new)
2019/10/19 23:14:24 INFO  : Cleaned the cache: objects 21 (was 21), total size 455.111M (was 83.572k)
2019/10/19 23:15:24 INFO  : Cleaned the cache: objects 21 (was 21), total size 500.093M (was 455.111M)
2019/10/19 23:15:24 INFO  : Cleaned the cache: objects 21 (was 21), total size 500.093M (was 455.111M)
2019/10/19 23:15:29 INFO  : data/0/2: Copied (new)
2019/10/19 23:16:24 INFO  : Cleaned the cache: objects 22 (was 22), total size 947.837M (was 500.093M)
2019/10/19 23:17:24 INFO  : Cleaned the cache: objects 22 (was 22), total size 1000.961M (was 947.837M)
2019/10/19 23:17:34 INFO  : data/0/3: Copied (new)
2019/10/19 23:18:24 INFO  : Cleaned the cache: objects 23 (was 23), total size 1.174G (was 1000.961M)
2019/10/19 23:19:24 INFO  : Cleaned the cache: objects 23 (was 23), total size 1.466G (was 1.174G)
2019/10/19 23:20:06 INFO  : data/0/4: Copied (new)
2019/10/19 23:20:24 INFO  : Cleaned the cache: objects 24 (was 24), total size 1.634G (was 1.466G)
2019/10/19 23:21:24 INFO  : Cleaned the cache: objects 24 (was 24), total size 1.960G (was 1.634G)
2019/10/19 23:21:52 INFO  : data/0/5: Copied (new)
2019/10/19 23:22:24 INFO  : Cleaned the cache: objects 25 (was 25), total size 2.448G (was 1.960G)
2019/10/19 23:23:16 INFO  : data/0/6: Copied (new)
2019/10/19 23:23:24 INFO  : Cleaned the cache: objects 26 (was 26), total size 2.599G (was 2.448G)
2019/10/19 23:24:24 INFO  : Cleaned the cache: objects 26 (was 26), total size 2.937G (was 2.599G)
2019/10/19 23:25:16 INFO  : data/0/7: Copied (new)
2019/10/19 23:25:24 INFO  : Cleaned the cache: objects 27 (was 27), total size 3.425G (was 2.937G)
2019/10/19 23:26:19 INFO  : data/0/8: Copied (new)
2019/10/19 23:26:20 INFO  : data/0/9: Copied (new)
2019/10/19 23:26:21 INFO  : data/0/10: Copied (new)
2019/10/19 23:26:24 INFO  : Cleaned the cache: objects 30 (was 30), total size 3.500G (was 3.425G)
2019/10/19 23:26:31 INFO  : data/0/11: Copied (new)
2019/10/19 23:26:49 INFO  : data/0/9: Copied (replaced existing)
2019/10/19 23:26:50 INFO  : lock.roster: Copied (replaced existing)
2019/10/19 23:26:51 INFO  : lock.roster: Removed from cache
2019/10/19 23:26:52 INFO  : lock.exclusive/Onyx@14038007751194.65451-0: Removed from cache
2019/10/19 23:27:24 INFO  : Cleaned the cache: objects 29 (was 30), total size 3.500G (was 3.500G)
2019/10/19 23:28:24 INFO  : Cleaned the cache: objects 29 (was 29), total size 3.500G (was 3.500G)```

Issue opened with rclone https://github.com/rclone/rclone/issues/3641

**Comment by ThomasWaldmann** [comment]
Some fuse cloud fs have consistency problems (and do not behave like a real fs), maybe this is such a case.

**Comment by ncw** [comment]
Rclone author here: this is probably an rclone problem, or maybe an eventual consistentcy problem.

However I'd really appreciate an explanation of exactly what the error message means so I can dig in a bit further - thanks.

**Comment by ThomasWaldmann** [comment]
hi @ncw, thanks for joining us here!

the code with the failing assertion is this: https://github.com/borgbackup/borg/blob/1.1.10/src/borg/repository.py#L675

The assertion failing is making sure that a segment file (file in `borgrepo/data/...`) is really unused before we delete it. borg maintains a usage count for each segment in the `hints` file (and in `self.segments` in the code).

At that place, it should be unused as the code just transferred all segment entries of the non-compact old segment file to a new (compact) segment file.

**Comment by ncw** [comment]
Thanks for your explanation @ThomasWaldmann 

What does being "unused" mean for a segment file? Or in file system terms what is rclone returning to say the segment file isn't unused?

How do you think borg's view of the world and rclone's have got out of sync?

**Comment by ThomasWaldmann** [comment]
Borg is using a log-like on-disk data structure to implement a key/value store for its repository.

A segment file has internally a sequence of entries (e.g. a PUT entry is adding data to the key/value store). If an entry is later deleted (by a subsequent DEL entry for the same key), it creates a logical hole in the segment file as the corresponding PUT is superseded by the DEL. The data is still there in that segment file, but not used any more.

To get rid of the logical holes and free up unneeded disk space, compact_segments is reading all entries from a non-compact segment with holes and writes them to a new compact segment file.

If all entries have been transferred to the new segment file (and the index has been updated accordingly), the old segment file is **unused** (has 0 used entries in it, that is what the assertion is checking).

I am not sure how it gets out of sync. One way would be that borg writes new data to a file and a subsequent read of that file does not return the new data, but some older content of the file.

**Comment by Cubox-** [comment]
From what @ivandeex said in https://github.com/rclone/rclone/issues/3641, could this issue be caused by mkdir being non-atomic with rclone's filesystem?

**Comment by ThomasWaldmann** [comment]
We use atomicity of mkdir in our repository locking code. But that would only matter if multiple borg clients are run against the same repo (and try to acquire the lock at very much the same instant).

@Cubox- did you have that situation?

**Comment by Cubox-** [comment]
@ThomasWaldmann no
The rclone fs was mounted on /gdrive (empty directory), and the borg client (running borg create) was on the same machine, with "/gdrive" as argument for path.

**Comment by ThomasWaldmann** [comment]
Is there any update on this?

**Comment by ncw** [comment]
It would be worth testing this again against rclone 1.53.1 or later as the VFS layer was re-written for that version and lots of little corner case bugs were winkled out.

**Comment by strugee** [comment]
So, I finally bit the bullet and built rclone from source, using https://github.com/rclone/rclone/commit/0ad38dd6fa28e841501a4c7bb3ec82c646ac1531 (I literally _just_ realized that I meant to build from a stable release and instead built from git master... oh well, too late now). rclone-related corruption is now magically "fixed" (????).

I had previously used my Borg repository over google-drive-ocamlfuse. I tried rclone in Debian buster because the OCaml implementation has terrible performance, and that worked for a bit before I hit corruption. `borg check`, even using the known-working google-drive-ocamlfuse instead of `rclone mount`, crashed. I can't remember exactly what the error was - something about `__del__` I think? However, since trying my newly-built copy of rclone (which reports its version as `v1.55.0-DEV`) the crash seems to have magically disappeared. `borg check` on the Borg repository completes without error, although I didn't run it with full data verification turned on. I'm running `borg create` right now and it seems to be working okay.

It's unclear to me if I'm hitting the same bug other folks in this thread are, and if my problem is _really_ fixed... it's kind of suspicious that it just magically went away.

**Comment by ncw** [comment]
> It's unclear to me if I'm hitting the same bug other folks in this thread are, and if my problem is _really_ fixed... it's kind of suspicious that it just magically went away.

I don't think it is magic, I think it the 100s of fixes the VFS layer in rclone has received which has polished it up like the bright star it really is ;-)

**Comment by strugee** [comment]
@ncw oh, for sure :P

I'm mostly just suspicious that there isn't any persistent corruption detected anymore. I would have expected using the version of rclone in Debian stable to have corrupted the on-disk repository data, such that reading it from a newer rclone would still cause crashes (since IIRC I got those crashes even switching back to the much slower but working google-drive-ocamlfuse)? I dunno. I can't remember exactly what I tried when at this point, and it seems to be working now ;)

**Comment by Jeff-rgb2** [comment]
I’m about to deploy an Ubuntu, Rclone mount (VFS cache mode full) and borg backup solution.

How have you find the combination of Rclone mount + borg backup?

Any tips, recommendations ?

**Comment by hrv231** [comment]
> How have you find the combination of Rclone mount + borg backup?
> 
> Any tips, recommendations ?

I'm doing that, I have on my unraid rclone running with mount to Google Drive, I use this rclone mount for my borg backup repository.
I found this thread looking for other people's config.
In my case, it is working perfectly, no problems so far, I have rclone mount with this config:
`rclone mount --cache-dir /mnt/disks/ud1/RClone_Caching_Folder/ --vfs-cache-mode full --max-read-ahead 1024k --allow-other encrypted: /mnt/disks/secure &`
and then I point my borg repository inside the _/mnt/disks/secure_ folder, so far running borg create works with no issues.
This is what I run if it helps
`borg create --compression none --one-file-system --read-special --files-cache mtime,size --debug --show-rc --progress /ua_nvme1/testrepo::testrepo-{now} /mnt/user/repo1`

rclone v1.55.0
borg 1.1.15

On the [rclone ticket](https://github.com/rclone/rclone/issues/3641) the user @dragetd explains that it is possible to reduce the segment size of borgbackup, that way the download from the cloud (in this case with rclone mount) would not take so long, that's a great idea that I still need to test, because that's exactly what it is happening to me, and I'm backing up about 500GB.

The work from Borg developers and RClone developers is amazing, I definitely need to donate something to those guys!

Great work!!

**Comment by Jeff-rgb2** [comment]
Thanks for your detailed response.

In your Rclone command, what does this mean, 

--allow-other encrypted: /mnt/disks/secure &

And in your borg command, what does this mean,
/ua_nvme1/testrepo::testrepo-{now} /mnt/user/repo1

I’ll likely use Vorta to mount borg as I’ve heard good things

**Comment by hrv231** [comment]
The --allow-other is something related to security, technically I'm allowing other users to play with the rclone mount, you can read more about it [here](https://forum.rclone.org/t/what-does-allow-other-do/12366)
The _encrypted_ is my google drive folder that I use to upload files, but it is encrypted using rclone crypt, you will need to read more about, but if you are not interested in encryption, you can place there your normal rclone cloud, example:
`--allow-other name_of_your_rclone_cloud: /mnt/disks/secure`
The /mnt/disks/secure is just an empty folder I created to mount my rclone cloud there.

Yes, use Vorta, it is good.

Good luck!

**Comment by ThomasWaldmann** [comment]
Guess this is solved.
