### ISSUE TITLE
Message that key needs to be backuped is misleading.

### ISSUE THREAD

**Issue by Apromixately** [borgbackup/borg#4803]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

UI Issue

## System information. For client/server mode post info for both machines.
Virtualbox VM

#### Your borg version (borg -V).
borg 1.0.9

#### Operating system (distribution) and version.
Vanilla Ubuntu 19.04

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
$ ./borg-linux64 init -e keyfile local
Enter new passphrase:
Enter same passphrase again:
Do you want your passphrase to be displayed for verification? [yN]:

By default repositories initialized with this version will produce security
errors if written to with an older version (up to and including Borg 1.0.8).

If you want to use these older versions, you can disable the check by running:
borg upgrade --disable-tam local

See https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-0-9-manifest-spoofing-vulnerability for details about the security implications.

IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).
```

## Describe the problem you're observing.
I don't think the displayed warning is correct. 
**IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s).**
Restoring the backup only requires the passphrase since the key is included in the backup.

**Comment by ThomasWaldmann** [comment]
The message is correct.

Just imagine that the config file in the repo (that's where the key is stored) gets lost or corrupted.

Then you'll need your key backup. If you have none, you have lost all access to the repo.

**Comment by Apromixately** [comment]
@ThomasWaldmann Okay, now I am even more confused. Isn't that config file part of the repo? So why would I lose the config file and not the rest of the repo? Or is this specifically to avoid partial corruption to affect the entire repo?

**Comment by ThomasWaldmann** [comment]
because "shit happens".

it could be a software bug in borg damaging the config (in the repo), a filesystem issue or just a defective sector just affecting your config file while all else is still ok.

it would be really a sad situation if you lose your repo config (including the key) and all else is still there, but you can't access it any more because you don't have the key / the key backup.

**Comment by Apromixately** [comment]
Hm...okay...that seems a bit too special a case for my needs. Thanks for the explanation, @ThomasWaldmann ! Much appreciated!

**Comment by ThomasWaldmann** [comment]
Software bugs, fs issues, defective disk sectors are not special, they happen all the time.

**Comment by Apromixately** [comment]
@ThomasWaldmann That's true but if the key got corrupted it would be noticed immediately when trying to create the next backup, right?

**Comment by ThomasWaldmann** [comment]
Yes. That would not help you if you have no backup, though.

But at least (assuming you regularly use the repo) it would not be a desaster-recovery time bad surprise.
