### ISSUE TITLE
Module 'os' has no attribute 'set_blocking'

### ISSUE THREAD

**Issue by henfri** [borgbackup/borg#4806]
Hello,

I am testing the current build of borg. Both, when doing an init or a create, I get:
```
c:\Program Files\Borg>borg init --encryption=repokey borg@homeserver:/media/22cd0c22-c75b-432a-b92b-73229607a8bd/Backups/borg/Windows

borg@homeserver's password:
Exception ignored in: <function RemoteRepository.__del__ at 0x000002132EAD1288>
Traceback (most recent call last):
  File "borg\remote.py", line 616, in __del__
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "borg\archiver.py", line 4434, in main
  File "borg\archiver.py", line 4366, in run
  File "borg\archiver.py", line 147, in wrapper
  File "borg\remote.py", line 558, in __init__
AttributeError: module 'os' has no attribute 'set_blocking'

Borg: 1.2.0a7.dev96+gd31afcb2  Python: CPython 3.7.4 msgpack: 0.6.1
PID: 12996  CWD: c:\Program Files\Borg
sys.argv: ['borg', 'init', '--encryption=repokey', 'borg@homeserver:/media/22cd0c22-c75b-432a-b92b-73229607a8bd/Backups/borg/Windows']
SSH_ORIGINAL_COMMAND: None
```

Edit: if someone can tell me how to add a the os:windows label...
this https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests does not work; I think it works only for the owner of the repo. I do not have the mentioned checkbox.

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
I just clicked on "Labels" on the right side of the page and selected "os: windows".

**Comment by henfri** [comment]
You are owner ;-)
For me, this is grey.

**Comment by ThomasWaldmann** [comment]
BTW, after "fixing" (not using the non-existing method), of course one needs to check whether a remote repo still works.

**Comment by henfri** [comment]
@Anakonda: Why did this work in the Windows Tree?
https://github.com/borgbackup/borg/blob/3c68040c5053e0b9d829e344a4d06359c93bfb27/src/borg/remote.py#L213

**Comment by Anakonda** [comment]
On my phone right now so not entirely sure.
Firstly vss have nothing to do with the error, your links were about communicating with remote, vss is about disk snapshots.
Secondly you dont have to set stdin blocking, it already is.

**Comment by henfri** [comment]
Hello,

sorry, I was under the impression that the remote module got the datastream via stdin; But that was pure speculation, and thinking about it, probably without much sense.

Regarding not having to make stdin blocking: 
Then 
https://github.com/borgbackup/borg/commit/3c68040c5053e0b9d829e344a4d06359c93bfb27
is not needed and we can just remove 
https://github.com/borgbackup/borg/blob/2209f56cd53dcb47e8056c20e25968f1e402fa94/src/borg/remote.py#L558

What's your view on this @TW?

And what about stdout and stderr?


Regards,
Hendrik

**Comment by ThomasWaldmann** [comment]
I have no idea about blocking/non-blocking streams on windows.

Try it - if it doesn't work I guess you'll notice it quickly if you pump bigger amounts of data.

**Comment by Anakonda** [comment]
Just to check, is your client or server or both Windows?

**Comment by henfri** [comment]
The Client

**Comment by henfri** [comment]
Hello,

> have no idea about blocking/non-blocking streams on windows.

I was *not* refering to Windows. @Anakonda mentioned that streams were blocking anyway and I interpreted that as a general comment, not limited to Windows.


> Try it - if it doesn't work I guess you'll notice it quickly if you pump bigger amounts of data.

How will I notice?

**Comment by Anakonda** [comment]
Make a backup and try to extract it. Compare the original files and the files extracted.

**Comment by henfri** [comment]
OK.
Can I also run from uncompiled cide? I think dir Debugging, that would bei preferable.
Otherwise @jrast would you create a Test build?

**Comment by jrast** [comment]
Note that remote repositories (using ssh) is curently not working for
Windows. So please try it with a local repo.

What do you mean with a test build?

I will update the information in README_WINDOWS with some more items on the
"whats working"/"whats not working" list. I will also add more detailed
instructions on how to build borg. But basically the dependencies are
already listed. If they are available, running "python setup.py build_ext"
should build the extension. Or install the package in editable mode: pip
install -e .



henfri <notifications@github.com> schrieb am Sa., 26. Okt. 2019, 22:44:

**Comment by henfri** [comment]
Hello,

> Note that remote repositories (using ssh) is curently not working for
> Windows. So please try it with a local repo.

I was not aware, but can confirm ;-)

> What do you mean with a test build?

Well, @Anakonda  suggested that set_blocking() calls are not needed under windows. That is why under the old Windows branch they were conditional and not executed under windows.

Now, I am willing to test that, but I cannot, as I only have a borg.exe.
Thus, I need a way to test it.
a) by running 'from source'
b) by getting a build from you that has the changes
c) by building myself (but for that my free time currently is too limited, I fear)

I would prefer a) (and that's probably what you mean by installing the package in editable mode)
 
Which repository and branch should I use?
Is this the right syntax?
`pip install -e git+https://github.com/jrast/borg@/win10-cibuild `
or
`pip install -e git+https://github.com/borgbackup/borg`

Regards,
Hendrik

**Comment by jrast** [comment]
You can use the win10-cibuild branch. I rebased the branch today, so the latest changes of the master branch are also in this branch.

This are roughly the steps required to build & run Borg on Windows (Windows 10 / Python 3.7):

- Get a VC 14.0 Compiler
- Checkout the repo
- Download OpenSSL, you can use `scripts/win-download-openssl.ps1` for this step.
- Install borg with `pip install -e .`, I highly recommend to do this in a virtual environment

Note that you need a compiler in order to work on the code! I don't know if it would be possible to provide only the DLL`s in order to simplify the developement setup for people who only want to work on the python code.

**Comment by henfri** [comment]
Thanks.
It surely Sounds easy enough. But the Devil is in the Details...
I surely would prefer not needing the compiler. What dlls is it compiling?

**Comment by jrast** [comment]
There are multiple cython / c extensions which are part of borg: chunker, compress, hashindex, item, checksum,  low level crypto and a platform specific library. You can see the compiled modules if you open the wheel file (for example the one from the latest build: https://ci.appveyor.com/api/buildjobs/mixsrf32pwnn1lsi/artifacts/dist%2Fborgbackup-1.2.0a7.dev135%2Bg53b4ba7f-cp37-cp37m-win_amd64.whl) with a zip tool / 7-Zip.

**Comment by henfri** [comment]
Hello,

I understand.
What I just tried: I installed the above whl.
It installs the scripts to
C:\Users\henfri\AppData\Roaming\Python\Python37\site-packages\borg\
and the executable to
C:\Users\henfri\AppData\Roaming\Python\Python37\Scripts

I can change the scripts and the changes have effect.

So I can develop without a compiler.

Greetings,
Hendrik

**Comment by jrast** [comment]
This issue got quite off-topic... I think the key points from this issue are:

- SSH is not yet supported on windows --> Should be handled in a separate Issue
- On windows path with a drive letter, eg. `C:\MyFiles\`,  are only supported if given with the file protocol and forward slashes: `file://C:/MyFiles/`. See #4732 

@henfri / @ThomasWaldmann can you close this issue?

**Comment by henfri** [comment]
Hello,

you are right, in that this topic got totally off topic. 
But we cannot close this, as we the problem still exists, right?

Greetings,
Hendrik

**Comment by jrast** [comment]
I created #4820 for the SSH support.

**Comment by henfri** [comment]
Thanks, that would be very important. Local backups somehow defat the purpose ;-)
