### ISSUE TITLE
borg delete --dry-run option not recognized and not working

### ISSUE THREAD

**Issue by fnx2k** [borgbackup/borg#4807]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Bug

#### Your borg version (borg -V).
borg 1.1.5

#### Operating system (distribution) and version.
Linux Ubuntu 18.04.3 LTS

#### Hardware / network configuration, and filesystems used.
Usb external disk - ext3

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg delete --dry-run  -s --save-space /path_to_repo::20YYMMDD
borg delete -n /path_to_repo::20YYMMDD

## Describe the problem you're observing.
When using the borg delete command the option --dry-run or -n is not recognized.

borg: error: unrecognized arguments: -n

This option is however shown in the manual:
https://borgbackup.readthedocs.io/en/stable/usage/delete.html

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
always

#### Include any warning/errors/backtraces from the system logs
```borg: error: unrecognized arguments: --dry-run```
```borg: error: unrecognized arguments: -n```

**Comment by ThomasWaldmann** [comment]
Are you reading the 1.1.5 docs or latest 1.1 or master?

See the version selector on the lower right there: https://borgbackup.readthedocs.io/en/1.1.5/

**Comment by fnx2k** [comment]
Understood.
Thank you for this precision.
