### ISSUE TITLE
Save 'prune' configuration in the repository

### ISSUE THREAD

**Issue by Flowdalic** [borgbackup/borg#4809]
It would be great if the 'prune' configuration could be stored within the repository. This would decouple the periodic invocation of the 'prune' command from the retention configuration.

# Example

Assume I have `N` borg repositories borg1 - borgN, each may have a different retention policy. Assume the is a `prune-borg-repositories` script, which periodically gets invoked using cron / systemd-timerd.

## Current status

Right now the script roughly looks like this

```bash
retention_policy[borg1] = "-keep-hourly 36 ----keep-weekly 4"
for repo in reposotories; do
   retention_policy_args = retention_policy[$repo]
   borg prune $retention_policy_args $repo
done
```

## Desired status

Assume now that there is a `borg prune --save` command, which specifies the retention policy (or policies) for a repository.

The user responsible for borg2 could simply

```bash
$ borg prune --save --keep-hourly 36 --keep-weekly 4 borg2
```

and now the `prune-borg-repositories` script simply becomes

```bash
for repo in repositories; do
  borg prune $repo
done
```

Ideally there would also be a `borg prune --list` command, to list the current retention policy (or policies). Note that I assume that there could be multiple policies for a single repository, with different archive filters. I am not sure if this is possible nor sensible, or if this leads to a good UX.

**Comment by ThomasWaldmann** [comment]
borg's threat model is that the server is rather untrusted (think of a backup server that you just rented at some hosting company or some other guy offering you some space on a remote machine).

putting the prune (or create) config into the repo would not fit that model: by modifying the prune configuration one could easily kill a lot of backups. similar for create.

besides that, we do not have any server side backup or prune configuration yet.

also, the backup is usually maintained clientside (what archives are created with specific content/excludes, archive name prefixes, etc.) and the prune config needs to match that (esp. archive name prefixes and also retention requirements depending on the contents), so it is easier to have a consistent config if all is managed clientside (at the same place).

**Comment by Flowdalic** [comment]
Thanks for your reply.

I have to admit that I do not quite follow your argumentation. For unencrypted repositories, the server (operator) can already delete(/kill/prune) backups at his will. For encrypted repositories, he can probably not delete indiviual backups, but obviously delete the whole repository. I do not see how any of this changes when you store the retention policy as part of the repository.

> also, the backup is usually maintained clientside (what archives are created with specific content/excludes, archive name prefixes, etc.) and the prune config needs to match that (esp. archive name prefixes and also retention requirements depending on the contents), so it is easier to have a consistent config if all is managed clientside (at the same place).

I guess my point here is, while the backup is created clientside, I may want to run `borg prune` directly on the server via a periodic job<sup>1</sup>. And then, I'd argue, it leads to a better UX if the retention policy stored in the repository, because it can be modified client side, without touching the periodic prune job configuration.

1: I note that is only sensible for unencrypted repositories.

**Comment by ThomasWaldmann** [comment]
We always assume encrypted repos as this matches our threat model - and we don't want to encourage users to work with unsafe configurations (unencrypted repos or encrypted repos plus putting the unlocked key onto the repo server) just because some specific functionality would only work that way.

It's correct that an attacker with repo server access could delete the whole repo (or corrupt it by deleting segment files). But these are rather obvious attacks, just pruning a bit much might be not that obvious and might be not recognized as an attack for a long time, which is more problematic.
