### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by henfri** [borgbackup/borg#4810]
Hello,

@jrast  I installed the whl from here:
https://ci.appveyor.com/api/buildjobs/mixsrf32pwnn1lsi/artifacts/dist%2Fborgbackup-1.2.0a7.dev135%2Bg53b4ba7f-cp37-cp37m-win_amd64.whl

With that, I try to init a new repo:

```
C:\Users\henfrik\AppData\Roaming\Python\Python37\Scripts>borg init --encryption=repokey "C:\Users\henfrik\Desktop\temp\Borg\"
Traceback (most recent call last):
  File "C:\Users\henfrik\AppData\Roaming\Python\Python37\site-packages\borg\archiver.py", line 37, in <module>
    from . import helpers
  File "C:\Users\henfrik\AppData\Roaming\Python\Python37\site-packages\borg\helpers\__init__.py", line 9, in <module>
    from .checks import *  # NOQA
  File "C:\Users\henfrik\AppData\Roaming\Python\Python37\site-packages\borg\helpers\checks.py", line 4, in <module>
    from .errors import Error
  File "C:\Users\henfrik\AppData\Roaming\Python\Python37\site-packages\borg\helpers\errors.py", line 3, in <module>
    import borg.crypto.low_level
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

I did install openssl with /scripts/openssl.ps1

This can be solved by copying the dlls that are installed to 
`external\cpython-bin-deps-openssl-bin-1.1.1c\amd64` 
after running the script next to the borg.exe.
In my case that is
`C:\Users\henfrik\AppData\Roaming\Python\Python37\Scripts`

Probably it would also work to copy the dlls into the PATH.

Greetings,
Hendrik

**Comment by jrast** [comment]
Can you provide some more information about your installation?

- Windows Version?
- Official Package as provided by the Python Foundation? Or something else like Anaconda, WinPython, ...?
- Is there a `DLLs` folder in the main folder where python is installed. Eg. `C:\Python37-x64` is the main folder, and in this folder is a subfolder named `DLLs`?
- If the above folder exists: Is there a file named `libcrypto-1_1.dll` in the `DLLs` folder?

**Comment by henfri** [comment]
Sure:
Windows 10
Anaconda (installed to C:\ProgramData\Anaconda3)
There is a DLLs folder in it, but no libcrypto-1_1.dll in that folder.

**Comment by jrast** [comment]
OK, so Anaconda does not provide the `libcrypto` DLL in a standard setup while the standard python distribution does. The wheel does not ship a copy of the DLL as it's expected to be present. If you search for anything named `libcrypt*` in your installation folder, do you get any hits?

**Comment by jrast** [comment]
On conda openssl is available through a custom package: https://anaconda.org/anaconda/openssl

**Comment by henfri** [comment]
Hello,

thanks. After installing that package, there are several libcrypto*.dlls.

Greetings,
Hendrik

**Comment by henfri** [comment]
Hello,

I have created a PR:
https://github.com/borgbackup/borg/compare/master...henfri:patch-1

We can close this now.

Greetings,
Hendrik
