### ISSUE TITLE
Support SSH on windows

### ISSUE THREAD

**Issue by jrast** [borgbackup/borg#4820]
Currently SSH is not supported on Windows. Since Windows 10 SSH is easy to install, so it might be possible to support ssh on windows too.

**Comment by henfri** [comment]
I just tried out the key exchange with my linux server to ensure the pasword-less access via ssh. 
Easy!

1. ssh-keygen --> do not enter a passphrase
2. copy the content of C:\Users\[username]\.ssh\id_rsa.pub to /home/borg/.ssh/authorized_keys of your server

Now your ssh borg@server will work without password.

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
Superseded by #7261.
