### ISSUE TITLE
Plaintext error with --json reporting

### ISSUE THREAD

**Issue by wsw70** [borgbackup/borg#4828]
## Is this a BUG / ISSUE report or a QUESTION?

ISSUE, maybe BUG (or at least functionality issue)

#### Your borg version (borg -V).

`borg 1.1.10`

#### Operating system (distribution) and version.

Ubuntu 18.04

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

    borg info /tmp/borgtest --last 1 --json

## Describe the problem you're observing.

This command works fine, except in the case where a backup is running. In such a situation, the following message is reported:

     Failed to create/acquire the lock /tmp/borgtest/lock.exclusive (timeout).

- Technically this reply is correct, the lock is owned by the backup process.
- Conceptually I do not think this is a proper answer because I am looking for information about the status of my backups no matter if the backup is running or not
- Programatically I think it is a mistake to send back plain text when the request was specifically for JSON

## Describe what you would have expected (I added that one :))

Ideally a JSON reply with the status of the existing backups (including the "latest" - the one which was successful), possibly with the information that there is a next one coming because the backup is ongoing

Or at least something like

```
{
  "ok": false,
  "error": "Failed to create/acquire the lock /tmp/borgtest/lock.exclusive (timeout).",
  "reason": "backup ongoing"
}
```

Another thing is that the message is stating that a lock could not be acquired, which may or may not be a problem - and does not tell the reason (a running backup). It makes it particularly difficult to reliably monitor the backups execution.

**Comment by ThomasWaldmann** [comment]
If the repository is locked, borg can not access it. This has been discussed in other tickets already, see there.

About the non-json error message: maybe first check the return code of the borg command. If that is not 0, there was a warning or an error. In that case you maybe should not expect the returned text to be json. Unsure about the warning case, but I am quite sure that there can be a lot of error conditions leading to non-json.

**Comment by wsw70** [comment]
> If the repository is locked, borg can not access it. This has been discussed in other tickets already, see there.

Yes, I saw other tickets and mentioned that in my first bullet ("Technically ..."). 

Is the reason for the lock available somehow? (notably when the lock is a real/current one like in the case of a backup (as opposed to a stale one))

> About the non-json error message: maybe first check the return code of the borg command. If that is not 0, there was a warning or an error. In that case you maybe should not expect the returned text to be json. Unsure about the warning case, but I am quite sure that there can be a lot of error conditions leading to non-json.

I already do a check on the deserialization but then I just know that there is a string reported. I can further confirm that if it includes some keywords the reason is a lock. But then (as mentioned above) I am stuck with a generic message.

If you prefer I can open another issue for that, since the answer to the problem in the title is that only when a response is successful a JSON will be available (if I got it right).
