### ISSUE TITLE
JSON timestamp is incorrect

### ISSUE THREAD

**Issue by wsw70** [borgbackup/borg#4832]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, there are several places where people raise isses with incorrect timestamps, some have workarounds. Here it is a bug without a workaround.

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

`borg 1.1.10`

#### Operating system (distribution) and version.

Ubuntu 18.04

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

    borg info /services/backup/borg --last 1 --json

## Describe the problem you're observing.

The output of 

```
{
    "archives": [
        {
  (...)
            "end": "2019-11-09T08:00:22.000000",
```

is incorrect.

The backup ended at 08:00:22 **local time**. The timestamp does not have a timezone indication and in other bug reports the general answer is that the timestamps will be UTC.

This is not the case here and the timestamp is not easily fixable in a place where daylight saving is applied (France for instance). Beside doing gymnastics with the current date and checking whether DST is applied at that date there is not way to reliably use that timestamp. Specifically, adding a `Z` at the end is not a solution (the time in the timestamp is local). For those using Python to analyze the timestamp, using `arrow` and adding `.replace(tzinfo='local')` to the `get()` solves the issue.

**The solution (which also fixes other bug reports) is to use a standardized format: ISO-8601 (https://fr.wikipedia.org/wiki/ISO_8601)**

**Comment by ThomasWaldmann** [comment]
I just played around a bit and looked at the start and end timestamps:
- borg create --stats outputs localtime timestamps
- same with --json
- borg info on the created archive outputs localtime also
- same with --json

So, the timestamps are correct and consistent.

It's just not what you expected and yes, the timezone is not specified.

**Comment by wsw70** [comment]
"localtime" is a concept which does not exist with dates.

If I need to check on a server that a backup completed in the last hour and I know that the end time is 8:20 and my time is 15:45, has it completed?

It is not a matter of preferences, it is just that the timestamp is simply incorrect. It is not UTC either, as it was suggested in another bug report. 

To be frank, forcefully closing this bug report is just hiding the issue. The software is really great, tandis a lot for it, it is just that some decisions do not scale (this one, or the ability to check for backups status when a backup is running, for instance)

**Comment by ThomasWaldmann** [comment]
You can not know the end time before it has ended anyway.

Nor can you access the repo while a backup is running, it will be locked.

**Comment by wsw70** [comment]
> You can not know the end time before it has ended anyway.

That's not the point I am trying to make. I get an ending time (typically when monitoring the backup) and I do not know when it has ended because this is a time I cannot compare with "now" without knowing the location of the server. If it was an epoch timestamp or a ISO-formatted date then it would have been easy.

> Nor can you access the repo while a backup is running, it will be locked.

This was another example of a design decision which does not take into account automated reporting (monitoring for instance). The fact that the backup is running should not block me from checking the status of the backup (again, typically in a monitoring context).
