### ISSUE TITLE
1.1-maint: upgrade Vagrantfile to python 3.5.9

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4834]
There was just a new python 3.5.9 release.

Upgrade the 1.1-maint Vagrantfile to this as soon as py-env supports it so that we use it for the binary builds.

**Comment by Gu1nness** [comment]
It seems that pyenv supports 3.5.9 : https://github.com/pyenv/pyenv/pull/1448 .
I will update all occurences of 3.5.3 to 3.5.9

**Comment by ThomasWaldmann** [comment]
IIRC the current version is 3.5.7 or .8.

**Comment by ThomasWaldmann** [comment]
Fixed by #4842.
