### ISSUE TITLE
docs issue with date format strings?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4837]
From #4836:

It appears that when using archive placeholder "{now}" and want to apply format to it, the format string has to be in quotes i.e. '%Y-%m-%d'.

That's not how it's written in the docs and examples.

**Comment by Gu1nness** [comment]
Do you think it is better to update the documentation or the code to be in accordance with the documentation?
I would go for the documentation for retro-compatibility.

**Comment by ThomasWaldmann** [comment]
If the documented version works, this is good enough.

Guess that was false alarm (or a difference how the shell handles the commandline).
