### ISSUE TITLE
--progress argument missing on borg create usage page

### ISSUE THREAD

**Issue by kosli** [borgbackup/borg#4838]
On https://borgbackup.readthedocs.io/en/stable/usage/create.html
the --progress argument is mentioned only in the text, but missing in the optional arguments listing.

**Comment by ThomasWaldmann** [comment]
oops? that's interesting, especially because the listing is automatically generated.

**Comment by kosli** [comment]
@ThomasWaldmann `borg create --help` doesn't show it either ;-)

**Comment by fantasya-pbem** [comment]
--progress is a common option shared by all borg commands.

**Comment by kosli** [comment]
@fantasya-pbem thanks for mentioning. I wouldn't have looked for a "progress" option at the bottom of the general information page at https://borgbackup.readthedocs.io/en/stable/usage/general.html#common-options  ... I think it would still be beneficial to have it listed with every command that provides any output with the --progress argument. e.g. I don't think the mount option provides any "progress"... or at least not yet.

**Comment by ThomasWaldmann** [comment]
@kosli i see your point, but we can not easily automate that. common options are just options that can always be given. whether they have an effect depends on whether the code checks the program internal flags.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/general.html#common-options

referred to by this: `borg [common options] create [options] ARCHIVE [PATH...]`

so guess there is nothing to do here.
