### ISSUE TITLE
Feature proposal: Add a possibility to run the borg check in small pieces

### ISSUE THREAD

**Issue by jk-1** [borgbackup/borg#4840]
Problem: If an repository is big enough, the borg check will take very long time. In my case the repo is just about 1 TB in a USB3 disk and borg check --verify-data takes more than 10 hours. This is a serious problem if I need to take a new backup e.g. after 2 hours. Ofcourse I can interrupt the check, take the backup and after the backup restart the check from beginning, but then the 2 hours checking work is wasted.

Proposal: Add a possibility to run the borg check in small pieces.

Possibility 1: User can send a specified signal e.g. SIGUSR1 or SIGUSR2 to borg during the check operation. This signal causes borg to store progression point/current check position into a file and exit. Restarted borg check would then search the file and if it exists, then continue the check from the correct position. From the user point of view this might be the most flexible solution.

Possibility 2: Give a max runtime as a parameter to borg. If the max runtime is exceeded before check is finished, borg will exit and store the progression/current check position into a separate file. When borg check is restarted, it will search the progression file and if found then continues the check operation from the current check postition.

Example: 

`borg check blaa-blaa --max-runtime 2h`

Possibility 3: Same as above in possibility 2 but instead of runtime, a max percentage of the total work is given.

Example: 

`borg check blaa-blaa --percentage 5`

The interrupted borg check exit value might be different from normal OK value to indicate that execution was interrupted.

Other issues: 
- Restarted borg check should be able to continue check even if the stored position is deleted from the repo because of a prune operation.
- Restarted borg check should be able to continue check even if there are new archives added after interruption.
- The file containing the progression point/current check position should be human readable/text.

Problems with the current solution --first N --last N archives: With these options user cannot check the whole repository in pieces. Also in case you could give a range of archives to check (not currently possible) you would do lot of duplicate checking if different archives contained same data.

**Comment by infectormp** [comment]
This will be implemented in future version see https://github.com/borgbackup/borg/issues/4473

**Comment by ThomasWaldmann** [comment]
@jk-1 I'll close this as it is already implemented in master branch (and in 1.2 alpha versions).

If you want to help, you could carefully test it.

Read there:

https://github.com/borgbackup/borg/releases/tag/1.2.0a7
