### ISSUE TITLE
ModuleNotFoundError: No module named 'borg.crypto.low_level'

### ISSUE THREAD

**Issue by ot3** [borgbackup/borg#4844]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

borg 1.1.5 on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-70-generic x86_64)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
pi@eon:[~]: borg
Traceback (most recent call last):
  File "/usr/bin/borg", line 11, in <module>
    load_entry_point('borgbackup==1.1.5', 'console_scripts', 'borg')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 36, in <module>
    from . import helpers
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 40, in <module>
    import borg.crypto.low_level
ModuleNotFoundError: No module named 'borg.crypto.low_level'
pi@eon:[~]:
```

I had a fully operational borg installation until a few days ago when I upgraded Python from 3.6 to 3.8. This broke a dependency with some other package and I decided to install Python 3.7.3. From then on, borg refuses to start, resulting in the error message above and I can no longer make backups

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I have tried uninstalling borg, reinstalling using apt-get, reinstalling using pip3, searching from root downwards for 'borg.crypto.low_level', updating the OS and many online searches, all to no avail. Any help will be appreciated very much.

**Comment by ThomasWaldmann** [comment]
So, how did you "upgrade from python 3.6 to 3.8"? AFAIK there is no ubuntu 18.04 package for that.

**Comment by ot3** [comment]
I have searched both my bash and browser histories but it seems that I can't find how I did this. I do know that in the end I installed the latest supported version (3.7.3) as well as python-dev. Running python3 shows this:
```
pi@eon:[~]: python3
Python 3.7.3 (default, Apr  3 2019, 19:16:38)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

All my own python code runs normally, as well as InfluxDB, , Grafana, Pandas and Numpy. Only borg fails to start due to the apparent lack of the 'borg.crypto.low_level' module.

**Comment by ThomasWaldmann** [comment]
If you overwrote the system's `/usr/bin/python` (e.g. by running `make install`, which is wrong and should be `make altinstall` when installing from source), then quite a lot might be broken now.

The stuff that comes with ubuntu usually is made for the python that comes with ubuntu, not for other versions.

You maybe can repair that by reinstalling the python3 from ubuntu.

**Comment by ThomasWaldmann** [comment]
If you need other python versions than the ones you get from ubuntu (e.g. for development purposes), have a look at `pyenv`.

**Comment by ot3** [comment]
I have solved the problem by installing a completely separate Python3 version using the --user flag after all attempts to remove, reinstall, install or otherwise repair the current installation failed.

The following commands were instrumental in getting things back on track:
```
sudo update-alternatives --remove-all python
sudo update-alternatives --remove-all python3
sudo ln -sf /usr/bin/python2.7 /usr/bin/python
sudo ln -sf /usr/bin/python3.6 /usr/bin/python3
python3 -m pip install --user --upgrade pip
```
Borg is working once more.
