### ISSUE TITLE
Parallel downloading/uploading

### ISSUE THREAD

**Issue by BirkhoffLee** [borgbackup/borg#4850]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## Question

I found that borg is using only one thread to upload the data, and I wonder if there's any way to do parallel upload/downloads to the remote server, for example using rsync?

Apologies if this question doesn't make sense, since I'm not too familiar with Borg's technical implementation.

**Comment by ThomasWaldmann** [comment]
Yes, borg is currently single threaded.

There is already an open github issue and a bounty about adding multithreading, see there.

**Comment by ThomasWaldmann** [comment]
Congrats to a 10GE internet connection! ;-)
