### ISSUE TITLE
Huge memory usage usage by borg-linux64 serve under CentOS8

### ISSUE THREAD

**Issue by Self-Perfection** [borgbackup/borg#4852]
I observe high RAM usage by `borg serve`, up to 500+ MB. Actually I could not perform first full backup, `borg serve` got OOMed
* 64 bit versions of borg 1.1.10 (either packaged in EPEL, or [pyinstaller release](https://github.com/borgbackup/borg/releases/download/1.1.10/borg-linux64)) 
* Server spec: CentOS 8 in KVM, ext4
* Data amount: ~6GB, ~1800 files

Memory usage raises with amount of data transferred during current `borg serve` invocation, so storing newer archives with small amount of new data does not cause `borg serve` to consume more than reasonable ~70-80MB of RAM.

Interestingly, that on the other host (Ubuntu 16.04 in OpenVZ) with the same borg standalone binary and the same data `borg serve` during initial backup does not eats lots of RAM and stays within reasonable 70-80MB of RSS.

Also [32 bit release](https://github.com/borgbackup/borg/releases/download/1.1.10/borg-linux32) is not affected, so I have a workaround. This difference between 64bit and 32bit versions seems especially strange.

To reproduce it is enough to run:
```
borg init --encryption=repokey-blake2
borg create ::{hostname}_photos_{now:%F_%T} $DATADIR ssh://CentOShost/borgdir
```

This seems similar to #3573 . But as far as I can tell, `borg-linux64 serve` does not use python fallback of msgpack implementation, at least C implementation is loaded:
```
lsof -c borg-linux64|grep msg   
borg-linu 8497 borg  mem    REG  253,1    476850  6815787 /tmp/_MEIKFymD3/borg.algorithms.msgpack._unpacker.so
borg-linu 8497 borg  mem    REG  253,1    425650  6815786 /tmp/_MEIKFymD3/borg.algorithms.msgpack._packer.so
```

**Comment by ThomasWaldmann** [comment]
If you can not reproduce with same borg binary on the other system, it might be rather an issue of the environment/system than of borg maybe?

**Comment by Self-Perfection** [comment]
It might be! On the other hand I don't see any issues with other software running on problematic host, that suggests the problem is within borg. For now it looks like 50%/50% chances of server environment issue vs borg issue.

I ran a few more measurements. Here is RAM (max RSS) consumption in megabyte of running on these two servers, `borg serve` during init / `borg serve` during archive create

|| Ubuntu 16.04, OpenVZ | CentOS 8, KVM |
| --- | --- | --- |
| 64 bit release, 1.0.13 | 16 / 48 | 20 / 100 |
| 32 bit release, 1.0.13 | | 14.5 / 39 |
| 64 bit release, 1.1.x | 71 / 71 | 74-75 / 400-600  |
| 32 bit release, 1.1.x |  | 58 / 58 |

Summary of tests:
* 1.0.x series were much more in RAM consumption
* On problematic host `borg serve` tends to gobble up RAM since 1.0.x series

Any advice how I can debug memory usage by borg?

**Comment by ThomasWaldmann** [comment]
I can't follow your "summary" - did you confuse 1.0 and 1.1?

Please edit your above post to make your point / the facts clear.

**Comment by Self-Perfection** [comment]
Oooops, I missed the word "thrifty".

1.0.x version were much more thrifty, economical in RAM usage.

**Comment by ThomasWaldmann** [comment]
"On problematic host borg serve tends to gobble up RAM since 1.0.x series"

I don't see that in your numbers either.

**Comment by Self-Perfection** [comment]
That was indeed confusingly worded indeed, I've updated that line too:
> On problematic host x86_64 `borg serve` during create of initial archive for sample 6GB of data tends to gobble up RAM since 1.0.x series (uses 5-8 times more RAM during `borg serve` for `borg create` than for `borg init`) For comparison 32 bit versions and 64 bit versions on "normal" host do not differ that much in memory usage of `borg serve` during init vs create, 3 times maximum.

**Comment by ThomasWaldmann** [comment]
I still don't understand why you write "since 1.0.x" because your table only shows an increase since 1.1.x (and you didn't show any pre-1.0 data).

Also, comparing `borg init` to `borg create` is maybe not that useful because init only deals with rather empty data structures while create is filling them with lots of data (esp. the in-memory files and chunks cache on the client side and the repo index on the server side).

**Comment by cghtompkins** [comment]
I have a similar issue with `borg serve` under Debian 10 x64, KVM, ext4 while running `borg create`. Borg consumes ~350MB before OOMing.

Version: `1.1.13` `borg-linux64` from the release page on both sides

Command:
`borg create USER@DOMAIN:PATH::initial_backup LOCAL_PATH`

Backup size: 4.2GB

**Comment by ThomasWaldmann** [comment]
@cghtompkins if 350MB means OOM you should use a host with more memory.

**Comment by cghtompkins** [comment]
Of course I could use another host with more memory, but since the memory consumption increases continuously with time I am affraid it will eventually end up running out of memory as well with larger backups.

That being said, is that the expected behaviour? Do you have a rough estimate of the memory consumption vs size of the backup?

**Comment by ThomasWaldmann** [comment]
I didn't measure that recently, but borg in general needs quite some memory:
- borg serve: for loading the repository index, index size ~ amount of chunks in repo
- borg client: for loading chunks index and files cache, see formula in the docs
- borg single process (not client+server): sum of client + server

Growth along these lines is expected, abnormal growth way beyond that could be a bug.

**Comment by ThomasWaldmann** [comment]
Without more information, guess we can't do anything here.

Borg needs quite some memory (depending on amount of data), that is expected.
