### ISSUE TITLE
Borg/Vorta backup stopped working

### ISSUE THREAD

**Issue by xboydavey** [borgbackup/borg#4865]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
1.1.9

#### Operating system (distribution) and version.
PCLinuxOS 4.9.190-pclos1

#### Hardware / network configuration, and filesystems used.
Intel Core i7 in Dell XPS 64GB
borg repo on attached Western Digitial 10TB USB backup drive with ext4 filesystem
backup process backs up ext4, xfs, jfs volumes
 
#### How much data is handled by borg?

~4TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

standard Vorta backup command line
repo created with this command line:
sudo borg init -e repokey /media/backup/borg/ -v

## Describe the problem you're observing.

been using borg backup since 3/2019. Since updating gnome to version that uses new gnome keyring, been getting the following error when attempting to peform daily scheduled backup:

ERROR: passphrase supplied in BORG_PASSPHRASE, by BORG_PASSCOMMAND or via BORG_PASSPHRASE_FD is incorrect.

at one point a keyring dialog was popping up when Vorta would start the backup. If I cancelled the dialog, the backup would not start. I finally just clicked 'Ok' with no username nor password specified, and the dialog no longer appears. However when Vorta attempts the scheduled backup, the above referenced error occurs.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

In Vorta, click the 'Start Backup' button

#### Include any warning/errors/backtraces from the system logs

````
/var/log/vorta:
$ cat vorta
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
````

**Comment by ThomasWaldmann** [comment]
Sounds like a keyring issue, so maybe rather something for the vorta issue tracker?

Can you still access your backups with borg cli command?

**Comment by xboydavey** [comment]
$ borg mount /media/backup/borg /mnt/bak/
Enter passphrase for key /backup/borg: 

Now I'm being prompted for a passphrase?

**Comment by xboydavey** [comment]
Ok, I just found out that I do have a passphrase; I tested some phrases and found one that worked. How do I completely remove the passphrase so that there is no login/passphrase required for the backup? Can I just run this command:
$ borg key change-passphrase /media/backup/borg, and when prompted specify a -0- length / empty passphrase?

**Comment by xboydavey** [comment]
Problem solved. Used BORG_PASSPHRASE, BORG_NEW_PASSPHRASE env vars to change password. Unlinked repository in Vorta, then relinked and entered password. Backup runs now.

Thank you for your advice.
