### ISSUE TITLE
borgbackup take too long for diff of 137GB

### ISSUE THREAD

**Issue by ledufakademy** [borgbackup/borg#4871]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue / question

## System information. For client/server mode post info for both machines.
qemu/kvm vm with 4 core (core i5 3470), 8 GB, hdd mdam raid5 below (7200rpm/mn)

#### Your borg version (borg -V).
Debian buster package so 1.1.9-2

#### Operating system (distribution) and version.
Debian Buster

#### Hardware / network configuration, and filesystems used.
1GB link between borgbackup pull server and proxmox lxc (nextcloud data) to be backup

#### How much data is handled by borg?
137.65GB

## Describe the problem you're observing.
diff size is only 169MB it's take 1h28mn ...
we use sshFS, mount remote fs on borgbackup server(pull) then backup.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes every night 😎

#### Include any warning/errors/backtraces from the system logs

no error .

If this complaint relates to borg performance, please include CRUD benchmark
results and any steps you took to troubleshoot.
How to run benchmark: http://borgbackup.readthedocs.io/en/stable/usage/benchmark.html

**Comment by ThomasWaldmann** [comment]
did you read the docs / FAQ?

iirc it is documented there that this might be a problem of unstable inode numbers (because you use sshfs) making the default --files-cache=ctime,inode,size not work as expected.

So, try with --files-cache=ctime,size (you need to do 2 backups after that to see an effect).

**Comment by ledufakademy** [comment]
Thank you thomas, i will give it a try tonight.

**Comment by ledufakademy** [comment]
i try with only 3GB of data ... with this option --files-cache=ctime,size

Creating archive at "/Sauvegardes/Prod/web2::web2-{now:%d_%m_%Y:%M}"
------------------------------------------------------------------------------
Archive name: web2-10_12_2019:23
Archive fingerprint: cd71225621d150808c6262464ea2a1d93164034bfdf4231ae2e65ea34b2561d7
Time (start): Tue, 2019-12-10 21:23:25
Time (end):   Tue, 2019-12-10 21:25:26
Duration: 2 minutes 0.92 seconds
Number of files: 126217
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                3.20 GB              3.09 GB              6.82 MB
All archives:               74.19 GB             73.66 GB              5.38 GB

                       Unique chunks         Total chunks
Chunk index:                   56403              2955073
------------------------------------------------------------------------------

**Comment by ThomasWaldmann** [comment]
`--list` option might be also useful, so you see the status for each file.

**Comment by ledufakademy** [comment]
thank you for your advices thomas borg  is a great tool.

**Comment by ledufakademy** [comment]
--list ... HUGE mail !!! (i send report by mail !)

**Comment by ledufakademy** [comment]
Ok , the --files-cache do GREATLY the job : thank you again Thomas.

==> 3mn

Archive name: web3-11_12_2019:45
Archive fingerprint: 1118f99bf3c90fa37bcde9fb1c7ab90dd4da16762c3e88257b0270774416c5bf
Time (start): Wed, 2019-12-11 09:45:05
Time (end):   Wed, 2019-12-11 09:48:47
Duration: 3 minutes 41.90 seconds
Number of files: 216685
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              137.64 GB            137.24 GB             42.15 MB
All archives:                3.44 TB              3.43 TB            144.74 GB

                       Unique chunks         Total chunks
Chunk index:                  163973              6692140

**Comment by ledufakademy** [comment]
--files-cache=ctime,size (in borg create option)
solve my issue.
