### ISSUE TITLE
Borg for Mac OS backs up multiple mount points even with -x

### ISSUE THREAD

**Issue by jbrepogmailcom** [borgbackup/borg#4876]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Seems to be a bug

#### Your borg version (borg -V).
1.1.9
#### Operating system (distribution) and version.
Mac OS Catalina
#### How much data is handled by borg?
80GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create -x --stats --noatime --progress --compression auto,zstd,22 server:/......./OSX-Direct-System-Borg::$(date "+%FT%H-%M-%S") /

## Describe the problem you're observing.
In Catalina, system is readonly partition mounted at / and data is read-write partition mounted at /System/Volumes/Data. When I create backup with -x, all data in /System/Volumes/Data and other mounted partitions are backed as well, but they should not be. Seems like identification of mounted volume at Mac OS Catalina is problematic.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Use the command line above

**Comment by ThomasWaldmann** [comment]
iirc, borg checks if the device number changes before recursing.

is that problem new on catalina and it worked on older versions?

**Comment by ThomasWaldmann** [comment]
any feedback?

btw, there was a recent docs addition that explains better how -x works and the issues related to that (esp. btrfs).

**Comment by ThomasWaldmann** [comment]
```
(borg-env) tw@mba2020 borg % df
Filesystem                       512-blocks      Used Available Capacity iused      ifree %iused  Mounted on
/dev/disk3s1s1                    965595304  17726104 332893536     6%  356091 1664467680    0%   /
...
/dev/disk3s5                      965595304 601693400 332893536    65% 1498063 1664467680    0%   /System/Volumes/Data
...
```

```
(borg-env) tw@mba2020 borg % python3
>>> import os
>>> os.stat("/")
os.stat_result(st_mode=16877, st_ino=2, st_dev=16777234, st_nlink=20, st_uid=0, st_gid=0, st_size=640, st_atime=1679114076, st_mtime=1679114076, st_ctime=1679114076)
>>> os.stat("/System/Volumes/Data/")
os.stat_result(st_mode=16877, st_ino=1152921500311879682, st_dev=16777234, st_nlink=21, st_uid=0, st_gid=0, st_size=672, st_atime=1680323674, st_mtime=1679954672, st_ctime=1679954672)
>>> os.stat("/System/Volumes/Data/usr")
os.stat_result(st_mode=16877, st_ino=115177768, st_dev=16777234, st_nlink=5, st_uid=0, st_gid=0, st_size=160, st_atime=1679114076, st_mtime=1679114076, st_ctime=1679954639)
```

Note how `st_dev` is the same value for both directories, although they are in different mounts.
That's why borg thinks it is the same filesystem.

**Comment by ThomasWaldmann** [comment]
Also notable:
```
>>> os.path.ismount("/")
True
>>> os.path.ismount("/System")
False
>>> os.path.ismount("/System/Volumes")
False
>>> os.path.ismount("/System/Volumes/Data")
False
>>> os.path.ismount("/System/Volumes/Data/usr")
False
```

**Comment by ThomasWaldmann** [comment]
It doesn't look like we can "fix" this easily, so I'll add a note about apfs/macOS to the docs of `-x`.
