### ISSUE TITLE
Is a borg repo efficiently "rsync-able"?

### ISSUE THREAD

**Issue by kaysond** [borgbackup/borg#4879]
My current backup solution is to run rsnapshot to an external drive, then borg to an offsite network location. The performance is somewhat slow because of my bad upload bandwidth, and I need to use compression so it uses a lot of CPU. I'm wondering if it would be better to skip rsnapshot altogether, run borg to a local network drive, then have the network drive host just rsync to an offsite location.

Is the borg repo suitable for rsync? Meaning, do files and their names stay the same between backups?  Except when new chunks are added, for example.

**Comment by infectormp** [comment]
You can rsync borg repo to other location. Please reed FAQ https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

**Comment by ThomasWaldmann** [comment]
if you want to have 2 independent borg repos, the best way is to just init and do backups into 2 separate borg repos.

**Comment by kaysond** [comment]
Thanks guys. I saw that in the docs. 

It doesn't really answer my question with regards to the **efficiency** of using something like rsync, though. I'm hoping to have a backup system where only my network is the bottleneck rather than CPU/memory/disk, which is the case with borg as its scanning chunks.

I already have the issue of something going wrong in my local backup propagating to the offsite one since I run rsnapshot then borg on the latest snapshot (which I have to do to get a consistent filesystem state).

**Comment by ThomasWaldmann** [comment]
If you run a repo in append-only mode, the rsync operation would be rather efficient as only new segment files are appended "at the end".

If you do not use append-only and maybe also prune now and then, it will also first append new stuff at the end, but then also compact the logical holes to really free up disk space (and it does that by shuffling the still used data (but not the holes) from old segment files to new segment files). Due to the compaction, the rsync operation gets less efficient.

But as you have read meanwhile in the FAQ: rsyncing is not recommended anyway, for multiple reasons.

**Comment by kaysond** [comment]
@ThomasWaldmann thanks for the explanation.

Do you have any plans to add something like a `clone` feature? What I would really like to do is run local borg backups to a raspberry pi, then have the raspberry pi take care of the sync to an offsite location. It doesn't sound like that really works with two `borg init`s, though, hence the question about using rsync...

**Comment by kaysond** [comment]
Maybe what I need to do is rsnapshot to the raspberry pi, then borg offsite... But the rpi compression speed will be bad...

**Comment by ThomasWaldmann** [comment]
The crypto is not done server side, so the way to go is to init and use 2 different repos **from the client**.

A server-side clone operation like you envision can not solve the crypto issue (AES CTR reuse)

**Comment by muchcharles** [comment]
> if you want to have 2 independent borg repos, the best way is to just init and do backups into 2 separate borg repos.

How does this work if you periodically connect an external drive and want to sync all the intermediate backups?

**Comment by ThomasWaldmann** [comment]
@muchcharles If you want all backups on all external drives, guess you would need to have the borg repo on some always-connected drive and then rsync that to the external drives as a redundant external copy (that is not used by borg directly).

But personally, I guess I rather would not do that, but just have a part of the backups on each external drive and directly write to them.

E.g. if you have 5 drives, 1 per weekday, the monday drive would just have all the monday borg backups. And each drive would be separately initialized once with "borg init". That way, most drives are offline most of the time and even if some drive gets defect or has some fs issue, you still have multiple other good drives.
