### ISSUE TITLE
No .checkpoint archives in my backups.

### ISSUE THREAD

**Issue by Fibroblasto** [borgbackup/borg#4881]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).

borg 1.1.9
borg-linux64 1.1.10

#### Operating system (distribution) and version.

Linux Debian Stable (Buster 10.2)

#### Hardware / network configuration, and filesystems used.

ext4 source and destination. Local backup.
Remote backup. Source: ext4. Destination: cloud Backblaze B2 mounted as FUSE with rclone.

#### How much data is handled by borg?

In the tests in the local backup, three files of 3.8 GB, 3.9 GB and 4.1 GB; total, 11.8 GB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create --checkpoint-interval 60 /tmp/borg-test::{hostname}-{now:%d-%m-%Y_%H:%M:%S} 'bigfile-1' 'bigfile-2' 'bigfile-3'

## Describe the problem you're observing.

During the backup and after it has finished, no .checkpoint files can be found.
After the backup, the command "borg list /tmp/borg-test" does not show any .checkpoint.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, it can be reproduced with the above mentioned commands. I never get .checkpoint files.

#### Include any warning/errors/backtraces from the system logs

No lines that include the word "borg" in /var/log/syslog

**Comment by ThomasWaldmann** [comment]
There are no .checkpoint files, but .checkpoint archives.

You only will see them if you abort after one is made and before the `borg create` finishes.

**Comment by ThomasWaldmann** [comment]
and please reproduce the problem (if there is any) on a known-good filesystem, like ext4.

**Comment by Fibroblasto** [comment]
As I wrote above, 

> and please reproduce the problem (if there is any) on a known-good filesystem, like ext4.

As I wrote above:

> Hardware / network configuration, and filesystems used.
ext4 source and destination. Local backup.

I will check aborting the backup and will report whatever I get. With "--checkpoint-interval 60" I should have several of them. Thanks.

**Comment by ThomasWaldmann** [comment]
Sorry, I only read the "remote backup" target filesystem being "cloud Backblaze B2 mounted as FUSE with rclone".

If that does not matter as you also see the same issue with local ext4, rather do not report such complex setups.

**Comment by ThomasWaldmann** [comment]
Guess this can be closed.
