### ISSUE TITLE
Docs: suggest users to always exclude Borg key files from backups

### ISSUE THREAD

**Issue by kroki** [borgbackup/borg#4887]
Minor documentation improvement suggestion: current [docs](https://borgbackup.readthedocs.io/en/latest/quickstart.html#repository-encryption) say:

> Make a backup copy of the key file (keyfile mode) or repo config file (repokey mode) and keep it at a safe place, so you still have the key in case it gets corrupted or lost. Also keep your passphrase at a safe place.
> ...
> A backup inside of the backup that is encrypted with that key/passphrase won’t help you with that, of course.

These statements are somewhat cryptic, as Borg itself is supposed to be a safe place for backups.  It should be explicitly advised (especially since as-of-now Borg's security is somewhat fragile) that the user should exclude said Borg key files from every backup, as backing them up inside Borg makes no point and is actually risky (quote from memory):

> Encryption is like putting you data in a safe.  Publishing encrypted result is like leaving your safe on a street for anyone to try to wrench it open.

If Nonce is compromised, an attacker may access _some_ data (Nonce overlap segment).  If there happens to be the key file, the attacker is invited to go further and try to break the passphrase, thus potentially accessing _all_ data.

WRT to key files language that avoids "backup" word is preferable ("_Store/Keep_ a copy...").

**Comment by ThomasWaldmann** [comment]
In repokey mode, the key is store in the repo anyway, at a well-known place, so this does not apply for repokey mode.

In keyfile mode, the worst that could happen is that security downgrades to that of repokey mode IF your CTR reuse attack is successful AND the keyfile happens to be in the decryptable data. It is still encrypted with the passphrase, so same situation as with repokey, just harder to achieve.

**Comment by kroki** [comment]
> so same situation as with repokey,

Agree, but this is exactly the point: users choose keyfile mode precisely because they believe that they will communicate with external world only with the strong random key, thus tend to reuse weak passphrase for local keyfiles.  They however may backup such files assuming that they will be protected with said strong random key, thus disabling attack on weak passphrase.

> just harder to achieve.

Well, agree, it's all about chances.  However with current fragile use of CTR in multi-client case the attacker just have to make a copy of the repo after `borg init`, and then provide each client doing first `borg create` with a fresh copy, thus obtaining substantial Nonce overlap.  There will be some problems for attacker to solve still (either guessing some client plaintext, or decoupling XOR of two client plaintexts (with Nonce reused for same key `cihpertext1 XOR ciphertext2 == plaintext1 XOR plaintext2` for CTR), but this is practically achievable).

I think somewhere deep inside all of us cherish the belief,

>  "oh c'mon, no one will run a _deliberate_ attack against _me_, I need encryption only to _obfuscate_ my data so that it won't surface somewhere in plain _accidently_"

and this is true for most of us.  However documentation should perhaps communicate such assumptions in a cleaner way.

Still everything is rooted in CTR misuse, so closing as semantic duplicate.
