### ISSUE TITLE
Migrate from CTR encryption mode to CBC

### ISSUE THREAD

**Issue by kroki** [borgbackup/borg#4889]
There are some [upcoming encryption changes](https://github.com/borgbackup/borg/wiki/Borg-Helium#development-goals) (with a promising "**Note:** This page could be outdated.").  The page _seems_ to suggest migration from CTR to something else (which almost always means [CBC](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Block_Chaining_(CBC))).  However the page uses obscure terminology and doesn't reveal any details, so its worth to clarify things.

### CTR encryption mode is widely adopted all over the Internet, so why Borg should not use it?

On the Internet, secure communications are established like this:
1. Client requests from server it's _asymmetric public_ (enables only encryption) key.
2. If such public key is signed with the trusted certificate then the signature is checked, if there is no signature or check fails then client aborts or proceeds depending on user choice.
3. Client generates _random_ (relatively short-lived) _symmetric_ (enables both encryption and decryption) key.  This key is called "session key".
4. Client encrypts "session key" with server's public key and sends it to server.
5. Server decrypts "session key" with its _asymmetric private_ (enables only decryption) key of the used public/private pair.
6. Now client and server share random symmetric "session key", which they use from now on _for this connection only_.  This way it's easy to maintain [Nonce](https://en.wikipedia.org/wiki/Cryptographic_nonce) constraint of being used only once _in the scope of a particular symmetric key_.  Other connections use _different_ random key, so reuse of Nonce there is not a problem.

OTOH, to make restoration from backup possible Borg uses single create-once-live-forever symmetric key, hence the requirement of globally (both in space (multi-client) and time) unique Nonce values.

The problem is that Borg can't provide globally unique Nonces.

### Why the issue should be acted upon as soon as possible, before any other "next cool feature yay!"

As-of-now Borg uses CTR with an ad hoc scheme to ensure that Nonce is not reused.  Borg developers are aware that this scheme doesn't scale to multi-client case, and has issues even in single-client setups.  For multi-case the flaw is even documented inside [_Internals_](https://borgbackup.readthedocs.io/en/latest/internals/security.html#attack-model) section.  However, official [FAQ](https://borgbackup.readthedocs.io/en/latest/faq.html?highlight=sparse#can-i-backup-from-multiple-servers-into-a-single-repository) in the very first question boldly claimed the opposite without mentioning security issues, single-client potential risks weren't mentioned in the docs at all (I use past tense in the hope that this will be fixed soon, see #4883).

As many users don't read docs past FAQ, where may be lots of setups that have wrong impression about their security level ("everything is encrypted, right?" - not enough), and even ones already compromised.  Security issues should be fixed ASAP.

### What to do?

Nonce reuse problem is inherent to CTR encryption mode, so the only solution is to use another encryption mode.  For persistent data widely accepted choice is to use CBC (while CTR is designed for communicate-and-forget scenario, CBC is designed to persistanse).  Unlike CTR, which requires Nonce, CBC requires [Initialization Vector (IV)](https://en.wikipedia.org/wiki/Initialization_vector), a non-secret value with the property of being (pseudo)random in a sense that future values can't be predicted a priori, and that value collisions are virtually non-existent.  Last requirement sounds muck like Nonce's "never reuse", but actually isn't: if two IVs collide, then the only information the attacker would get is that two plain-texts were the same if their cipher-texts are the same, different otherwise. Unlike with Nonce attacker won't be able to actually decrypt anything.  **Note: last two claims should be reviewed by security expert.**

### How to do?

**Note: claims/proposals in this section should be reviewed by security expert.**

If true (as opposed to pseudo) random number source is available (for instance with Intel's `RDRAND` instruction) then use it for IV generation (note: Linux /dev/random is subject to entropy draining and can't be used for large number of random numbers).

If only pseudorandom number generator (PRNG) is available, seed it with a true random number (one per Borg run is enough), if no true random numbers are available at all, seed it with current time with highest precision available.  Let's call pseudorandom number generated by PRNG on some iteration `PRN`.

We can't use `PRN` as IV directly, because attacker could lookup `PRN` sequnce prefix in a dictionary to guess seed value, and thus compute all future `PRN` values.  Also if _seed_ values collide, then the whole sequence of pseudorandom numbers will repeat producing lots of collisions that are better avoided if possible.  Hence the proposal is to compute `PRN xor MAC(plain-text)`.  Since attacker can't compute `MAC(plain-text)` he can't restore original `PRN`, so both issues are addressed (if seed collides `PRN xor MAC(plain-text)` will still repeat for _same_ plain-text, but the scope of repetition is limited to the chunk length; normally Borg even won't send same chunks due to deduplication, but the attacker may trick it to do so with "repo copy attack").

However, some people believe that `MAC(plain-text)` may reveal some information about plain-text and that `xor` "encryption" is not enough, so the final proposal is: `IV = ENCRYPT(PRN xor MAC(plain-text))`, which under CBC encryption mode is equivalent to `IV = 0; ENCRYPT((PRN xor MAC(plain-text)) || plain-text)` (double bars are concatenation operator, i.e. prepend plain-text with `PRN xor MAC(plain-text)` block, then encrypt the whole message using zero IV; on decrypt use first block as IV).

### What about compatibility?

Almost nothing.  Borg should leave the code to decrypt CTR chunks, but all new chunks should be encrypted in CBC mode.  Even compaction will work: Borg won't have to round-trip data to client for re-encryption, simply mix CTR chunks into CBC stream (I believe each chunk has cipher tag, if not then try both ciphers and see if `MAC(plain-text)` matches).  As long as you do not perform new CTR _encryption_ old repos are either safe or _have already been compromised_.  In latter case new data encrypted in CBC mode won't be compromised, but deduplicated parts will refer to old CTR chunks, so if you believe in a threat described in #4887, then users are advised to create a new repo _with a new passphrase_ and never update an old one.

**Comment by kroki** [comment]
Perhaps it's also worth mentioning that when you create, say, 256-bit pseudorandom number having only 64-bit PRNG, do not concatenate 4 sequential `PRN`s from single PRNG into a wider word - this doesn't increase entropy.  Instead use 4 PRNG instances with 4 independent seeds, concatenate results.  Truncation of `PRN` is also a bad idea.

**Comment by kroki** [comment]
Just took a look at [Restic docs](https://restic.readthedocs.io/en/latest/100_references.html#keys-encryption-and-mac): they too use CTR, but with pseudorandom Nonce.  Well, if one truly believes that low collision probability is equivalent to "it will never happen", then this may be a way to go for Borg as well.

There's one good reason to strive to stay with CTR: [GCM](https://en.wikipedia.org/wiki/Galois/Counter_Mode) encryption mode (despite Wikipedia, it _does_ support 256-bit encryption too).  It is similar to CTR, uses Nonce too, but computes `ENCRYPT(plain-text)` and `MAC(cipher-text)` in one pass and is accelerated in hardware (about 30-40% faster than computing them in separate passes).  I don't understand why Borg or Restic use two-pass approach instead.

Since Borg takes its chances in other matters (#4884), it may choose to do opportunistic encryption as well.  My personal opinion is that security comes before performance, but there are niche markets for opposite solutions too.

**Comment by ThomasWaldmann** [comment]
I'm not a cryptographer, but IIRC CBC mode has its own issues.

We already have a ticket discussing GCM and OCB, see that there.

**Comment by ThomasWaldmann** [comment]
BTW, the crypto interface in master is a bit different than in 1.1-maint, it was refactored to AEAD style, to potentially support modes like GCM and OCB by providing a more usable interface for that.

**Comment by kroki** [comment]
> CBC mode has its own issues.

True. CBC is [malleable](https://en.wikipedia.org/wiki/Malleability_(cryptography)) and susceptible to [padding oracle attack](https://en.wikipedia.org/wiki/Padding_oracle_attack).  You will also google a lot of "GCM is more secure than CBC", which is also true due to concept substitution.  However CBC+MAC is as strong as GCM (which are CTR+MAC), while reusing IV is not as catastrophic as reusing Nonce.

However I changed my mind overnight, and now think that probabilistic approach is indeed suits Borg better.  So closing this report in favor of #3814.  Once this is implemented (should be quite easy to code and will play well with already used sequential Nonces) #4883 could be closed too saving the embarrassment of acknowledging that multi-client is not supported.
