### ISSUE TITLE
use mock with autospec

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#489]
after requiring python 3.4.0 (or -.1?):

there is some pain related to some mock versions documented there:
https://github.com/borgbackup/borg/blob/4c668a85b63955ccd41b8f7b1c151373da1a4924/borg/testsuite/mock.py

after finding that, I talked to some people and they all advised to use mock in a non-default, but better way: to avoid the pain caused by succeeding "non-existing" methods by using autospec=True.

So, the calls have to be changed to autospec=True (and whatever else is needed to make that work).

**Comment by enkore** [comment]
?

**Comment by ThomasWaldmann** [comment]
Well, there is one Mock() left in testsuite/archive.py.
