### ISSUE TITLE
Borg native S3 storage compatibility without mount

### ISSUE THREAD

**Issue by LucaBernstein** [borgbackup/borg#4890]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## Describe the issue you're having.

I want to establish a fail-safe backup strategy with `borg`.
For that it would be awesome to be able to backup to an S3 storage without mounting it (#102 ).
That's because if I mount it I am vulnerable to a ransomware attack and if the borg backup on the storage is encrypted I have no more data left (with the local backup also being encrypted as it is mounted I have no backups left).

What possibility is there that borg supports native S3 storage API in the near future?

I hope I conveyed my issues and if anyone has suggestions to build a nice backup concept please feel free to raise that so maybe we can work around this. ;)

**Comment by ThomasWaldmann** [comment]
The is no "cloud storage" support in borg and at least for the foreseeable future, there won't be.
IIRC, this has already been discussed in other tickets before, please look it up there.
One usual workaround is to have a local borg repo and use rclone to have a copy in the cloud.

If attacker code gets control over your machine, storage does not need to be mounted to be affected, the attacker could also use borg to delete your backups or maybe intercept s3-related credentials and use them to delete all your s3 stuff.

**Comment by MPW1412** [comment]
There is a logic flaw in @LucaBernstein's request: If borg can write to the S3 storage, the credentials must be held locally, and so the ransomware could erase the data, if it was coded to search for them.

**Comment by yuvadm** [comment]
I believe it should be possible to configure AWS IAM keys that can only append data to S3, not modify or delete.

**Comment by lapineige** [comment]
Hello,

> The is no "cloud storage" support in borg and at least for the foreseeable future, there won't be.*

Is that still valid ?

Thanks

**Comment by infectormp** [comment]
> Hello,
> 
> > The is no "cloud storage" support in borg and at least for the foreseeable future, there won't be.*
> 
> Is that still valid ?
> 
> Thanks

yes

**Comment by ThomasWaldmann** [comment]
I plan to do some rather fundamental, experimental and big change (which also relates to the backends) in master branch ("borg2") soon, but the outcome of that has to be seen.

IF that comes out as successful, a future with other than filesystem backends in borg might be possible.

**Comment by lapineige** [comment]
Thank you for the feedback :)
Good luck implementing it if you end up doing so :)

**Comment by toby1984** [comment]
> I plan to do some rather fundamental, experimental and big change (which also relates to the backends) in master branch ("borg2") soon, but the outcome of that has to be seen.
> 
> IF that comes out as successful, a future with other than filesystem backends in borg might be possible.

Just came across this issue as I was looking into using Backblaze (S3 compatible) with Borg ... I take it that the experimental changes did not work out ?
