### ISSUE TITLE
More borg-placeholders - {last} {newest} {first} {oldest}

### ISSUE THREAD

**Issue by Tunoac** [borgbackup/borg#4892]
borg-placeholders covers useful shortcuts, like {hostname} {now}.

I'm missing some for reading/accessing the repository, e.g. like {last} {newest} {first} {oldest}

Use case:
last=$(borg  list --last 1 | awk '{print $1}')
borg mount ::${last} /d/d1/@t/borg/m

Could be faster and easier:
borg mount ::{last} /mountpoint/xyz

Thanks for your comments on this idea!

**Comment by ThomasWaldmann** [comment]
There can be multiple backup sequences in the same repo, so it is not sufficient if one just would give `{last}` (or any of the others you mentioned) - that is why it does not exist and you should use:

```
borg --list --short --prefix <prefix> --last 1 repo
```
