### ISSUE TITLE
strip-components and hardlink_masters in 1.1.10

### ISSUE THREAD

**Issue by favonia** [borgbackup/borg#4893]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Possibly a regression BUG

#### Your borg version (borg -V).

1.1.10

#### Operating system (distribution) and version.

Arch Linux

#### Hardware / network configuration, and filesystems used.

1. backup system: external USB hard drive using btrfs
2. main systems: using ext4

The USB connection and the filesystems have been checked.

#### How much data is handled by borg?

```
                       Original size      Compressed size    Deduplicated size
All archives:                1.49 TB              1.29 TB            176.28 GB

                       Unique chunks         Total chunks
Chunk index:                  684439              4486059
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
sudo borg extract --progress --debug --strip-components 2 /mnt/backup::2019.12.19
```

## Describe the problem you're observing.

The problem seems to go away without `--strip-components 2`. I suspect that there is a regression bug about the component stripper and/or the hardlink mapping.

```
using builtin fallback logging configuration
35 self tests completed in 0.08 seconds
Verified integrity of /mnt/backup/index.370
Enter passphrase for key /mnt/backup: 
TAM-verified manifest
security: read previous location '/mnt/backup'
security: read manifest timestamp '2019-12-20T06:16:18.569254'
security: determined newest manifest timestamp as 2019-12-20T06:16:18.569254
security: repository checks ok, allowing access
Local Exceptionng: .rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/parser-2.4.0.0/lib/parser/lexer.rb                                     
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 179, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 759, in do_extract
    for item in archive.iter_items(filter, partial_extract=partial_extract,
  File "/usr/lib/python3.8/site-packages/borg/archive.py", line 465, in iter_items
    for item in self.pipeline.unpack_many(self.metadata.items, partial_extract=partial_extract,
  File "/usr/lib/python3.8/site-packages/borg/archive.py", line 236, in unpack_many
    chunks, _ = hardlink_masters[source]
KeyError: 'path/to/some/file/in/the/archive'
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I downgraded borg to 1.1.8 (by rebuilding the package from the older official PKGBUILD) and everything worked again. These archives are a bit large and I am not sure where to start to create a smaller example. I am happy to try different things if there are concrete suggestions.

#### Include any warning/errors/backtraces from the system logs

Nothing caught by journald.

**Comment by ThomasWaldmann** [comment]
Hmm, I remember fixing something like that (not sure if it was exactly that, though).

Did you search the closed tickets also?

Can you reproduce with current 1.1-maint branch?

I want to make a 1.1.11 release soon, but didn't get to it yet.

**Comment by favonia** [comment]
@ThomasWaldmann I tried to search GitHub issues a bit. The closest one I found is https://github.com/borgbackup/borg/issues/761, but that could not explain why 1.1.8 worked.

**Comment by ThomasWaldmann** [comment]
Duplicate of #4607 ?

**Comment by favonia** [comment]
I did not finish the full testing, but it went beyond the usual percentage where 1.1.10 failed. Thank you for your work!

**Comment by ThomasWaldmann** [comment]
@favonia did you use 1.1-maint branch current code for that test?

**Comment by favonia** [comment]
@ThomasWaldmann Yes.
