### ISSUE TITLE
How much of a cryptographic vulnerability would a leaked cache pose?

### ISSUE THREAD

**Issue by finefoot** [borgbackup/borg#4899]
There is a short exchange about this on the mailing list: https://mail.python.org/pipermail/borgbackup/2019q1/001267.html

The question was if it's okay to put the (unencrypted) cache with the (encrypted) repository. While it has been answered to "not do this" due to the cache containing metadata information, there is no deeper explanation.

Assuming one doesn't care about metadata and puts the cache with the repo anyway or in case the cache has inadvertently been leaked: How much of a cryptographic vulnerability would one be facing?

(I'm not planning to leak the cache on purpose, like putting it with the encrypted repository - I'm just wondering about how much I should worry about keeping the cache secure.)

**Comment by ThomasWaldmann** [comment]
Fixed by #4900, backport to 1.1-maint still required.

**Comment by finefoot** [comment]
@ThomasWaldmann 

> Fixed by #4900

It is? My understanding is, that the changes introduced by #4900 clarify that it's of importance to put the cache at a secure location as well as the related essential steps to help prevent leaking of the cache.

However, this issue poses the question about cryptographic vulnerability of the borg repo/archive *in case the cache has already been leaked*.

**Comment by finefoot** [comment]
I mean, maybe the answer is simply: There is no cryptographic vulnerability from a leaked cache. You'll only expose unencrypted metadata information.

Is that what you mean?

**Comment by ThomasWaldmann** [comment]
The cache is not encrypted, thus even the title of this issue is unclear.

You are not supposed to "leak" the cache and the default location is considered to be secure.

The files cache contents are H(filepath) -> (size, timestamp, inode number, chunkid list).
The chunks cache contents are chunkid -> (size, csize, refcount).

So, yes, it is metadata. Whether it is "only" metadata (in the sense that metadata does not matter that much) pretty much depends on your threat model.

**Comment by finefoot** [comment]
@ThomasWaldmann 

> The cache is not encrypted, thus even the title of this issue is unclear.

See my previous comment: "this issue poses the question about cryptographic vulnerability of the borg repo/archive in case the cache has already been leaked". Take the following scenario for example:

- My drive, and therefore my home folder, is fully encrypted.
- However, I forgot to lock my laptop and an attacker was able to copy my `.cache/borg` folder.
- My borg repo/archive is of course still encrypted with a password.
- Will the copy of the cache, which is now in the possession of the attacker, help with attacking the borg repo?
- Or is the only use of that copy the gained information about metadata?

> Whether it is "only" metadata (in the sense that metadata does not matter that much) pretty much depends on your threat model.

That's true indeed.

**Comment by ThomasWaldmann** [comment]
If you forgot to lock your laptop, the attacker has access to all your files on it anyway.

He maybe could also find and read your backup script with the key password and maybe also the key.

Not sure why one would need to do complicated attacks considering the above, but here is one:

In the files cache, one can see the sizes of all files. So an attacker could make good guesses whether you possess and backed up a collection of files that is known to the attacker.

**Comment by finefoot** [comment]
> If you forgot to lock your laptop, the attacker has access to all your files on it anyway.

Like I explained in a different issue, a possible scenario would be that one is backing up from external media like an external hard drive. By default, the cache would still be in my home folder, though. So cache and data are not in the same location. The external hard drive is encrypted and contains both data and backup script and keys.

> In the files cache, one can see the sizes of all files. So an attacker could make good guesses whether you possess and backed up a collection of files that is known to the attacker.

True. In some cases that might be valuable information to the attacker.

How do you feel about the above mentioned scenario or regarding the cache security assumption in general? While I agree that in the overwhelming number of use cases for borg, the assumption proves true, I also think that it's still a pretty strong assumption. Do you think it would be beneficial to display a warning, if backup source and cache don't belong to the same file system? Again, the overwhelming number of use cases would never see this warning. It would only be shown to those who don't keep their cache with the backup source data.

**Comment by ThomasWaldmann** [comment]
I don't think that "not the same filesystem" is the criteria. A lot of people have / and /home on different FSes and still they are always mounted together in the same way and always present.

Sounds rather like whether removable media (that is actually removed sometimes) is used or not is the criteria - but that is hard to detect, esp. if it is always there when it is backed up...

**Comment by ThomasWaldmann** [comment]
Maybe the docs should tell not to store the cache on a lower security level storage than the original files.

**Comment by finefoot** [comment]
> A lot of people have / and /home on different FSes and still they are always mounted together in the same way and always present.

But "always mounted together" doesn't mean that they share the same security level: one could mount an encrypted partition with backup data while having unencrypted /home and therefore unencrypted cache. That's why I thought it's only safe to assume same security level for same file system. Right?

I think, ideally, Borg should display such a warning too often rather than too rarely, as it's a matter of data security: Basically, a user might not be aware of the cache at all and inadvertently expose the metadata information. In the end, it comes down to the question which experience is being expected from borg users. If you don't want to assume layman-users/newbies, then showing a warning would be overkill since people are obviously *supposed* to know about the cache by reading the docs.

> Sounds rather like whether removable media (that is actually removed sometimes) is used or not is the criteria - but that is hard to detect, esp. if it is always there when it is backed up...

Had a quick look around but couldn't find anything useful... I'll try to keep looking.

> Maybe the docs should tell not to store the cache on a lower security level storage than the original files.

:+1: Agreed, it can't hurt. Like for #4894, I'd just wait for #4919 to get merged, first.

**Comment by finefoot** [comment]
@ThomasWaldmann 

> Maybe the docs should tell not to store the cache on a lower security level storage than the original files.

Like I said, I agree with this. It can't hurt to add this to the docs. However, it's possible that this is not enough:

> I think, ideally, Borg should display such a warning too often rather than too rarely, as it's a matter of data security: Basically, a user might not be aware of the cache at all and inadvertently expose the metadata information

Currently, it's assumed that the average borg user knows that a cache with unencrypted metadata information is being generated.

**Comment by finefoot** [comment]
I just noticed #4941 which kind of touches the same subject.

**Comment by finefoot** [comment]
I feel like the original question is sufficiently answered with

> In the files cache, one can see the sizes of all files. So an attacker could make good guesses whether you possess and backed up a collection of files that is known to the attacker.

and

> So, yes, it is metadata. Whether it is "only" metadata (in the sense that metadata does not matter that much) pretty much depends on your threat model.

Thanks for the explanations. :)

Therefore, regarding the discussion on borg's assumptions on cache security, I'll open a new issue.
