### ISSUE TITLE
borg init results in "IndexError: list index out of range"

### ISSUE THREAD

**Issue by ArthurClemens** [borgbackup/borg#4907]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue report

#### Your borg version (borg -V).

`borg 1.1.10`

#### Operating system (distribution) and version.

MacOS Mojave

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ borg init arthur@myDomain.com:/mnt/privateBackups/MacBookProArthur -e repokey --debug
using builtin fallback logging configuration
35 self tests completed in 0.10 seconds
SSH command line: ['ssh', 'arthur@myDomain.com', 'borg', 'serve', '--umask=077', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.15 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/mnt/privateBackups/MacBookProArthur'
Remote: Resolved repository path to '/mnt/privateBackups/MacBookProArthur'
Initializing repository at "ssh://arthur@myDomain.com/mnt/privateBackups/MacBookProArthur"
RemoteRepository: 178 B bytes sent, 886 B bytes received, 3 messages sent
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4501, in main
  File "borg/archiver.py", line 4433, in run
  File "borg/archiver.py", line 166, in wrapper
  File "borg/archiver.py", line 280, in do_init
  File "borg/crypto/key.py", line 110, in key_creator
  File "borg/crypto/key.py", line 684, in create
  File "borg/crypto/key.py", line 507, in new
  File "borg/crypto/key.py", line 435, in env_passphrase
  File "borg/crypto/key.py", line 449, in env_passcommand
  File "subprocess.py", line 316, in check_output
  File "subprocess.py", line 383, in run
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1181, in _execute_child
IndexError: list index out of range

Platform: Darwin MacBookProArthur.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
Borg: 1.1.10  Python: CPython 3.5.7 msgpack: 0.5.6
PID: 48059  CWD: /Users/arthur
sys.argv: ['borg', 'init', 'arthur@myDomain.com:/mnt/privateBackups/MacBookProArthur', '-e', 'repokey', '--debug']
SSH_ORIGINAL_COMMAND: None
```

## Describe the problem you're observing.

Suddenly I cannot create a new backup repo anymore. I have issued this command before in the past days, and this error has appeared only now.

The repo has been created, but when using `borg check` it doesn't have a manifest.

Deletion and re-initing as mentioned in #4252 doesn't solve the issue.

**Comment by ArthurClemens** [comment]
Weird, after a restart it works again.

**Comment by ThomasWaldmann** [comment]
looks like it is related to BORG_PASSCOMMAND.

On January 3, 2020 4:23:42 PM GMT+01:00, Arthur Clemens <notifications@github.com> wrote:
>## Have you checked borgbackup docs, FAQ, and open Github issues?
>
>Yes
>
>## Is this a BUG / ISSUE report or a QUESTION?
>
>Issue report
>
>## System information. For client/server mode post info for both
>machines.
>
>#### Your borg version (borg -V).
>
>`borg 1.1.10`
>
>#### Operating system (distribution) and version.
>
>MacOS Mojave
>
>#### Full borg commandline that lead to the problem (leave away
>excludes and passwords)
>
>```
>$ borg init arthur@myDomain.com:/mnt/privateBackups/MacBookProArthur -e
>repokey --debug
>using builtin fallback logging configuration
>35 self tests completed in 0.10 seconds
>SSH command line: ['ssh', 'arthur@myDomain.com', 'borg', 'serve',
>'--umask=077', '--debug']
>Remote: using builtin fallback logging configuration
>Remote: 35 self tests completed in 0.15 seconds
>Remote: using builtin fallback logging configuration
>Remote: Initialized logging system for JSON-based protocol
>Remote: Resolving repository path
>b'/mnt/privateBackups/MacBookProArthur'
>Remote: Resolved repository path to
>'/mnt/privateBackups/MacBookProArthur'
>Initializing repository at
>"ssh://arthur@myDomain.com/mnt/privateBackups/MacBookProArthur"
>RemoteRepository: 178 B bytes sent, 886 B bytes received, 3 messages
>sent
>Local Exception
>Traceback (most recent call last):
>  File "borg/archiver.py", line 4501, in main
>  File "borg/archiver.py", line 4433, in run
>  File "borg/archiver.py", line 166, in wrapper
>  File "borg/archiver.py", line 280, in do_init
>  File "borg/crypto/key.py", line 110, in key_creator
>  File "borg/crypto/key.py", line 684, in create
>  File "borg/crypto/key.py", line 507, in new
>  File "borg/crypto/key.py", line 435, in env_passphrase
>  File "borg/crypto/key.py", line 449, in env_passcommand
>  File "subprocess.py", line 316, in check_output
>  File "subprocess.py", line 383, in run
>  File "subprocess.py", line 676, in __init__
>  File "subprocess.py", line 1181, in _execute_child
>IndexError: list index out of range
>
>Platform: Darwin MacBookProArthur.local 19.2.0 Darwin Kernel Version
>19.2.0: Sat Nov  9 03:47:04 PST 2019;
>root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
>Borg: 1.1.10  Python: CPython 3.5.7 msgpack: 0.5.6
>PID: 48059  CWD: /Users/arthur
>sys.argv: ['borg', 'init',
>'arthur@myDomain.com:/mnt/privateBackups/MacBookProArthur', '-e',
>'repokey', '--debug']
>SSH_ORIGINAL_COMMAND: None
>```
>
>## Describe the problem you're observing.
>
>Suddenly I cannot create a new backup repo anymore. I have issued this
>command before in the past days, and this error has appeared only now.
>
>The repo has been created, but when using `borg check` it doesn't have
>a manifest.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/4907

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
