### ISSUE TITLE
Cache, or information obtained from the security directory is newer than repository -- without attack (I think!)

### ISSUE THREAD

**Issue by horazont** [borgbackup/borg#4908]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes-ish (actually, I was directed here from IRC, so I assume this is OK)

## Is this a BUG / ISSUE report or a QUESTION?

A bug probably.

## System information. For client/server mode post info for both machines.

Borg version: 1.1.9 (Debian buster: 1.1.9-2) (client and server)

### Client setup

- Debian buster
- borg metadata (cache etc.): ext4 storage on LUKS encrypted spinning rust
- source data: ext4 storage on a LUKS encrypted raid1 (mdraid) on spinning rust

### Server setup

- Debian buster VM (with KVM); I can get details about the hypervisor if necessary
- repository: ext4 on a virtual block device. The virtual block device is in a raw image on a zfs filesystem with snapshots enabled.

#### How much data is handled by borg?

- Repository size is 302 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Any. Initially triggered with:

```
borg create -s '::archivename-{now:%Y-%m-%dT%H:%M:%S}' /path/to/data
```

## Describe the problem you're observing.

I currently run manual daily backups against the backup server. On 2020-01-03, the backup failed to start with:

```
Cache, or information obtained from the security directory is newer than repository - this is either an attack or unsafe (multiple repos with same ID)
```

The backup from the day before succeeded without errors.

In IRC, textshell and me debugged around the issue. We obtained the following information:

* manifest timestamps: 2020-01-02T18:06:01.742927 (server; via ``borg debug dump-manifest`` from the client with a temporary ~/.config), 2020-01-03T16:32:10.033869 (client)
* nonces: 0000001037c5aee8 (server), 0000001037c5aee8 (client)

Timeline of events:

- Backup on 2020-01-02 which succeeded. The timestamp matches nicely with the timestamp currently found on the server side.
- Backup on 2020-01-03 which succeeded. The timestamp is found in the client manifest info and matches with the timestamp on the emails I get on backups.
- Backup on 2020-01-04 failed to start with the aforementioned error message.

#### Can you reproduce the problem?

I can reproduce the error message, but I can not figure out how to make it happen in the first place.

#### Include any warning/errors/backtraces from the system logs

I can not find anything relevant in the syslog on either server or client. It appears that the SSH session from the client was closed cleanly:

```
Jan  2 18:06:10 gluon sshd[30335]: Received disconnect from 2001:16b8:[…]:fe42:2911 port 37242:11: disconnected by user
Jan  2 18:06:10 gluon sshd[30335]: Disconnected from 2001:16b8:[…]:fe42:2911 port 37242
Jan  2 18:06:10 gluon sshd[30326]: pam_unix(sshd:session): session closed for user luna-backup
Jan  2 18:06:10 gluon systemd-logind[400]: Removed session 2211.
Jan  2 18:06:10 gluon systemd: pam_unix(systemd-user:session): session closed for user luna-backup
[…]
Jan  3 16:32:17 gluon sshd[1531]: Received disconnect from 2001:16b8:55e4:8700:1e87:2cff:fe42:2911 port 37442:11: disconnected by user
Jan  3 16:32:17 gluon sshd[1531]: Disconnected from 2001:16b8:55e4:8700:1e87:2cff:fe42:2911 port 37442
Jan  3 16:32:17 gluon sshd[1522]: pam_unix(sshd:session): session closed for user luna-backup
Jan  3 16:32:17 gluon systemd-logind[400]: Removed session 2497.
Jan  3 16:32:17 gluon systemd: pam_unix(systemd-user:session): session closed for user luna-backup
```

**Comment by horazont** [comment]
Before obtaining the manifest info with dump-manifest, a borg check --repository-only completed and found this:

```
Index object count mismatch.
committed index: 746283 objects
rebuilt index:   746286 objects
ID                                                               rebuilt index    committed index
0000000000000000000000000000000000000000000000000000000000000000 (53506, 60341)   (53494, 1707908)
2fcbcbc3c3282b1d5a1f1b554e1c55aaed62b7e4d3ac81606675e106ca9b7662 (53506, 8)       <not found>
646a7122ff881d40bb08cfa1e1436be6238a5d1883744d4e2fa10f91872503b6 (53506, 5157)    <not found>
78f1e428c7812af10e25a3bccf5a7973204a1c9d5dbcf2b493c809c72ba19399 (53506, 6325)    <not found>
Completed repository check, errors found.

```

**Comment by horazont** [comment]
Timestamps of files in the repository:

```
drwx------ 3 luna-backup luna-backup     4096 Jan  5 14:51 .
drwxr-xr-x 7 luna-backup luna-backup     4096 Jan  5 14:48 ..
-rw------- 1 luna-backup luna-backup      635 Nov 25  2016 config
drwx------ 8 luna-backup luna-backup     4096 Jan 25  2019 data
-rw------- 1 luna-backup luna-backup   195378 Jan  4 12:29 hints.53507
-rw------- 1 luna-backup luna-backup 51516698 Jan  4 12:29 index.53507
-rw------- 1 luna-backup luna-backup      190 Jan  4 12:29 integrity.53507
-rw------- 1 luna-backup luna-backup       16 Jan  3 16:32 nonce
-rw------- 1 luna-backup luna-backup       26 Nov 25  2016 README
```

The most recent data segments:

```
-rw------- 1 luna-backup luna-backup       17 Jan  2 18:06 53493
-rw------- 1 luna-backup luna-backup  1717600 Jan  2 18:06 53494
-rw------- 1 luna-backup luna-backup       17 Jan  2 18:06 53495
-rw------- 1 luna-backup luna-backup       17 Jan  3 16:29 53497
-rw------- 1 luna-backup luna-backup       17 Jan  3 16:29 53499
-rw------- 1 luna-backup luna-backup       17 Jan  3 16:29 53501
-rw------- 1 luna-backup luna-backup       17 Jan  3 16:29 53503
-rw------- 1 luna-backup luna-backup       17 Jan  3 16:32 53505
-rw------- 1 luna-backup luna-backup    70185 Jan  3 16:32 53506
-rw------- 1 luna-backup luna-backup       17 Jan  3 16:32 53507
```

**Comment by textshell** [comment]
(from irc)
The chunk ids reported by check as exactly the same chunk ids that have a put in segment 53506. So the problem seems to be that there is some way for borg to write an index with a transaction id without actually updating the index content to that transaction.

**Comment by horazont** [comment]
I was able to obtain snapshots from the morning of the 3rd an 4th of January. The timestamps in the snapshots look like this:

##### 2020-01-03 00:00:01 (after successful backup with properly committed data)

```
Nov 25  2016 config
Jan 25  2019 data
Jan  2 18:06 hints.53495
Jan  2 18:06 index.53495
Jan  2 18:06 integrity.53495
Jan  2 18:03 nonce
Nov 25  2016 README
```

##### 2020-01-04 00:00:01 (after last successful backup without properly committed data)

```
Nov 25  2016 config
Jan 25  2019 data
Jan  3 16:32 hints.53507
Jan  3 16:32 index.53507
Jan  3 16:32 integrity.53507
Jan  3 16:32 nonce
Nov 25  2016 README
```

**Comment by horazont** [comment]
It has been confirmed that the storage stack used causes silent ext4 filesystem corruption. Feel free to close this, unless you want to provide better diagnostics or handling of such situations.

**Comment by ThomasWaldmann** [comment]
@horazont can you add more details about what exactly is causing ext4 fs corruption? guess that might be interesting for people with similar setups.

As far as borg is concerned, I guess we can close this. We need to rely on the fs working correctly, otherwise we are pretty much lost. @textshell what do you think about this?

**Comment by ThomasWaldmann** [comment]
ping.

**Comment by horazont** [comment]
@ThomasWaldmann Oh wow, this scrolled out of my inbox *far*. Thanks for pinging me.

So this was a VM. The storage was fed directly to Qemu via iscsi. We do not know the exact cause, but we observed *very* strange things going on, in the order of magnitude of RAM content(!) appearing in the file cache(!!) of the guest system(!!!) (Ever gotten Permission denied when SSH-ing into a system, only to find the ~/.ssh/authorized_keys mangled to contain a page of a running libuuid.so (instead of your public keys), which disappears when you drop fs caches?). This strongly correlated with heavy I/O (e.g. borg) on the iscsi volumes.

When the storage was switched back to NFS backed volumes, all of the odd behaviour disappeared.

A few months later, some memory corruption vulnerabilities in the iscsi subsystem of qemu were published. I have no idea if that’s related. We’ve been running without issues on NFS since then.

So with the cache corruption in the guest system (visible through any syscall operating on files), it is conceivable that this has caused confusion to borg and/or ext4 itself which broke things.

**Comment by ThomasWaldmann** [comment]
Thanks for updating!

Adding such information is still useful, as people can find it when searching all issues filed here.

So I'm closing this as it was likely caused by an issue below borg.

**Comment by poelzi** [comment]
We had a bad corruption on ceph filesystem on which I put my backups. One techniuqe could be to create par files together with the archive. That way, single file corruption could be repaired.
