### ISSUE TITLE
always segfault when backing up a debian server

### ISSUE THREAD

**Issue by teecee1** [borgbackup/borg#4909]
On a debian buster machine hosted at hetzner
installed not much, but docker for some apps

running
borg create -p -v --stats --show-version --exclude-from /root/borg/excludes ssh://xxxxxxx@xxxxxxx.your-backup.de:23/./.borg_repos/xxxxxxxx::2020-01-05--21-42  /

stops running in the middle of the job with 
./borg_backup: line 67: 11838 Segmentation fault      borg create $progress $opts $REPOSITORY::"${backup_dir}" /

it crashes EVERY run. tried different parameters.
it crashes at diferent positions, but always in the middle of a GMV directory which is a google mail mackup with about 100.000 small files

it is possible to put all these files together into a tar archive. so no prob to read te files. but borg has probs with it ... ??

when I try to exclude the GMV directory: "create" runs without probs.

#### Your borg version (borg -V).
1.1.9

#### Operating system (distribution) and version.
debian 10 buster

#### Hardware / network configuration, and filesystems used.
256GB SSD ; 2TB HD Raid excluded from Backup

#### How much data is handled by borg?
about 50GB in 1Mio files

**Comment by ThomasWaldmann** [comment]
Usually python code does not segfault, so this is either an issue in our C code or a hw / environment issue.

Can you run borg with gdb to get more infos about the segfault?

Is it the borg debian package from buster?

**Comment by teecee1** [comment]
(1) gdb:
my first try with gdb (as a former programmer in other environments):
`(gdb) file borg
"/usr/bin/borg": not in executable format: file format not recognized`

(2) yes from hetzner-mirror for buster

**Comment by teecee1** [comment]
Ok, I got some info from an old borg-issue with gdb. And this is what I got:

'''
root # gdb --args /usr/bin/python3 `which borg` create -v --stats --show-version -x --exclude-from /root/borg/excludes ssh://uuu@uuu.your-backup.de:23/./.borg_repos/xxx::2020-01-06--11-57 /
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3...Reading symbols from /usr/lib/debug/.build-id/66/44f05b3a3ab9727ecee55c58681bc43b94d92e.debug...done.
done.
(gdb) run
Starting program: /usr/bin/python3 /usr/bin/borg create -v --stats --show-version -x --exclude-from /root/borg/excludes ssh://uuu@uuu.your-backup.de:23/./.borg_repos/xxx::2020-01-06--11-57 /
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 23223]
borgbackup version 1.1.9
[Detaching after fork from child process 23224]
Enter passphrase for key ssh://uuu@uuu.your-backup.de:23/./.borg_repos/xxx: 
Killed stale lock teecee.teecee.de@119170001108763.17082-0.
Removed stale exclusive roster lock for host teecee.teecee.de@119170001108763 pid 17082 thread 0.
Removed stale exclusive roster lock for host teecee.teecee.de@119170001108763 pid 17082 thread 0.
Creating archive at "ssh://u182550@u182550.your-backup.de:23/./.borg_repos/80db6dd3bf05431a88f0cac9b5144da1::2020-01-06--11-57"

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb)
'''

Any chance to get more info from gdb?

**Comment by ThomasWaldmann** [comment]
See there for some gdb usage (esp. `bt`):

https://github.com/borgbackup/borg/issues/4709

**Comment by teecee1** [comment]
> See there for some gdb usage (esp. `bt`):
> 
> #4709

Does not work after "The program no longer exists."

**Comment by teecee1** [comment]
I played with excluded.
By accident I got this result:

```
borg create -v --stats --show-version -x --exclude-from /root/borg/excludes ssh://uuu@uuu.your-backup.de:23/./.borg_repos/xxx::2020-01-06--23-23 /
borgbackup version 1.1.9
Killed stale lock teecee.teecee.de@119170001108763.22583-0.
Removed stale exclusive roster lock for host teecee.teecee.de@119170001108763 pid 22583 thread 0.
Removed stale exclusive roster lock for host teecee.teecee.de@119170001108763 pid 22583 thread 0.
Creating archive at "ssh://uuu@uuu.your-backup.de:23/./.borg_repos/xxx::2020-01-06--23-23"
Fatal Python error: Segmentation fault

Current thread 0x00007f701c797740 (most recent call first):
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 949 in file_known_and_unchanged
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1006 in process_file
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 608 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 634 in _process
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 520 in create_inner
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 557 in do_create
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154 in wrapper
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387 in run
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455 in main
  File "/usr/bin/borg", line 11 in <module>
./borg_backup: line 67: 24083 Segmentation fault      borg create $progress $opts $REPOSITORY::"${backup_dir}" /
```

**Comment by ThomasWaldmann** [comment]
OK, so it crashed in there (or in code called from there):
```
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 949 in file_known_and_unchanged
```
https://github.com/borgbackup/borg/blob/1.1.9/src/borg/cache.py#L949

**Comment by ThomasWaldmann** [comment]
`self.files` is a python dictionary data structure (and tends to be rather large depending on the count of files you back up).

So it could be a bug on `python` itself, but considering that `dict` is used all over the place in python, that is rather unlikely and I would rather expect that your machine has some hardware or OS issues.

Can you run `memtest86+` for some hours (at least 1 full pass, better more).

**Comment by teecee1** [comment]
OK, some hardware probs. Cannot locate exactly yet.
Hetzner found an incompatibilty beween kernel and acpi. 
Probably also an filessystem inconsistency.

**Comment by TDannhauer** [comment]
Hi @teecee1 : what was the Details reason? It seemsnI have the Same issue, but Inhabers gdb‘ed the issue yet.

at Bootup, Kernel Logs ACPI issues, it is listed after adding usb during Boot process .

Can you give me Details about Hetzners analysis Results and the way to fixes ? in your Case?

thanks,
Torben
