### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by daviehh** [borgbackup/borg#4910]
Looks like the signing GPG key "6D5B EF9A DD20 7580 5747 B70F 9F88 FB52 FAF7 B393" expired on 12/23/2019? This can result in 
`gpg --recv-keys "6D5B EF9A DD20 7580 5747 B70F 9F88 FB52 FAF7 B393"`

returning
`gpg: key 9F88FB52FAF7B393: no user ID`

https://borgbackup.readthedocs.io/en/stable/support.html#verifying-signed-releases
may need to be updated. Thanks!

**Comment by ThomasWaldmann** [comment]
I've edited my key, extended the expiry and uploaded it to a keyserver.

Not sure how long it takes until all keyservers have that.

Thanks for the reminder.

**Comment by daviehh** [comment]
Thanks!
