### ISSUE TITLE
Running `borg recreate --exclude-caches` on a specific archive raises a KeyError

### ISSUE THREAD

**Issue by intelfx** [borgbackup/borg#4911]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

```
$ borg -V
borg 1.2.0a8.dev61+gfc96fc4b
```

#### Operating system (distribution) and version.

Arch Linux

#### Hardware / network configuration, and filesystems used.

- borg host: btrfs RAID5 on HDD
- borg client: btrfs on SSD
- `borg create` over SSH, `borg recreate` locally on host

#### How much data is handled by borg?

```
$ du -hs /mnt/data/Backups/Hosts/able/borg
609G    /mnt/data/Backups/Hosts/able/borg
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ export BORG_PASSCOMMAND="pass misc/borg"
$ export BORG_REPO="/mnt/data/Backups/Hosts/able/borg"
$ borg recreate --exclude-caches --keep-exclude-tags --progress --stats ::able-2019-08-21
```

## Describe the problem you're observing.

Using `borg recreate --exclude-caches` on a single specific archive in my repository raises a KeyError.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The problem can be reproduced on this specific archive 100% of the time.

#### Include any warning/errors/backtraces from the system logs

```
$ export BORG_PASSCOMMAND="pass misc/borg"
$ export BORG_REPO="/mnt/data/Backups/Hosts/able/borg"
$ borg recreate --exclude-caches --keep-exclude-tags --progress --stats ::able-2019-08-21
recreate is an experimental feature.
Type 'YES' if you understand this and want to continue: YES
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4476, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 4407, in run
    return set_ec(func(args))
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 165, in wrapper
    return method(self, args, repository=repository, cache=cache_, **kwargs)
  File "/usr/lib/python3.8/site-packages/borg/archiver.py", line 1570, in do_recreate
    if not recreater.recreate(name, args.comment, args.target):
  File "/usr/lib/python3.8/site-packages/borg/archive.py", line 1887, in recreate
    self.matcher_add_tagged_dirs(archive)
  File "/usr/lib/python3.8/site-packages/borg/archive.py", line 2042, in matcher_add_tagged_dirs
    file = open_item(archive, cachedir_masters[item.source])
KeyError: 'arch/var/lib/flatpak/repo/objects/50/7741d5f44a0b8c6d81e907afb1160bb7f3aba3e44779d2bcb0b04a556a70f7.file'

Platform: Linux stratofortress.nexus.i.intelfx.name 5.4.7-arch1-1 #1 SMP PREEMPT Tue, 31 Dec 2019 17:20:16 +0000 x86_64
Linux: Unknown Linux
Borg: 1.2.0a8.dev61+gfc96fc4b  Python: CPython 3.8.1 msgpack: 0.6.2
PID: 2148059  CWD: /mnt/data/Backups/Hosts/able/borg
sys.argv: ['/usr/bin/borg', 'recreate', '--exclude-caches', '--keep-exclude-tags', '--progress', '--stats', '::able-2019-08-21']
SSH_ORIGINAL_COMMAND: None
```

## Additional notes:

Mounting the problematic archive reveals that `arch/var/lib/flatpak/repo/objects/50/7741d5f44a0b8c6d81e907afb1160bb7f3aba3e44779d2bcb0b04a556a70f7.file` contains valid cachedir tag contents, and adding a `print()` to the crash site reveals that this file is a hardlink destination for a properly named cachedir tag:

```
$ borg recreate --exclude-caches --keep-exclude-tags --progress --stats ::able-2019-08-21
recreate is an experimental feature.                                                                               
Type 'YES' if you understand this and want to continue: YES                                                        
XXX: going to crash:
        item.path=arch/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/365d62760000772f8cf401cfb6389252a2c1e2a0ebb39d99302fb730abfd8b74/files/cache/fontconfig/CACHEDIR.TAG
        item.source=arch/var/lib/flatpak/repo/objects/50/7741d5f44a0b8c6d81e907afb1160bb7f3aba3e44779d2bcb0b04a556a70f7.file
Local Exception
<...>
```

As I understand the situation, the crash occurs when a `CACHEDIR.TAG` is a hardlink to another file that is _not_ named `CACHEDIR.TAG` (which can and will happen with deduplicating content-addressable stores such as flatpak, ostree etc).

I have worked around this issue locally by simply skipping tag content verification when the hardlink cannot be resolved, but I don't see a good way to fix this properly without either loading the whole archive contents into the hashmap or making `matcher_add_tagged_dirs()` quadratic.

Any ideas?

**Comment by ThomasWaldmann** [comment]
I could reproduce the issue and added a test to check if it happens.
Now trying to fix it.

See #5227.

**Comment by ThomasWaldmann** [comment]
@intelfx thanks for reporting this!

the code was half prepared for such issues, but only considered all files named `CACHEDIR.TAG` and not that the first archived "master" hardlink (which actually contains the content) could have a different name.

**Comment by ThomasWaldmann** [comment]
This also affects borg 1.1.x.
