### ISSUE TITLE
Error: Failed to create/acquire the lock [Errno 13] Permission denied: '.../lock.exclusive

### ISSUE THREAD

**Issue by vrishaligiri** [borgbackup/borg#4913]
Background:
- Failure happening only in prod (other environments are all ok)
- Using Airflow along with docker containers to run borg backup process. It's a python multithreading process. On average 5 threads out of 15 threads fail with lock create/acquire issue. Data being processed varies from 5 to 10 GB.
- It's not time out issue, so worried about using `borg break-lock`
- Our docker container runs with "sudo" permission. Doesn't look like permission issue. (Also given that 10 out of 15 threads are successful, so permissions are good)

## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Issue

#### Your borg version (borg -V). 
1.1.6

#### Operating system (distribution) and version. 
Linux e090132a34ae 3.10.0-1062.4.1.el7.x86_64
Linux: debian 9.6

#### How much data is handled by borg? 
5 to 10 GB

#### Full borg command line that lead to the problem (leave away excludes and passwords)
borg create --stats /backup_dest/db_name::db_name-20200107044358 /backup_source/db_name

## Describe the problem you're observing.
The backup process fails to create/acquire the lock during `borg create` process.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting
Trigger Airflow dag (docker operator task) to backup multiple databases (using python multithreading)

#### Include any warning/errors/backtraces from the system logs
Traceback:
```
ERROR: Command line: ['/borg', 'create', '--stats', '/backup_dest/db_name::db_name-20200107044358', '/backup_source/db_name']

INFO - Exit code: 2
INFO - Stderr:  | Failed to create/acquire the lock /backup_dest/db_name/lock.exclusive ([Errno 13] Permission denied: '/backup_dest/db_name/lock.exclusive').
INFO - | Traceback (most recent call last):
INFO - |   File "borg/archiver.py", line 4312, in main
INFO - |   File "borg/archiver.py", line 4244, in run
INFO - |   File "borg/archiver.py", line 137, in wrapper
INFO - |   File "borg/repository.py", line 184, in __enter__
INFO - |   File "borg/repository.py", line 381, in open
INFO - |   File "borg/locking.py", line 346, in acquire
INFO - |   File "borg/locking.py", line 359, in _wait_for_readers_finishing
INFO - |   File "borg/locking.py", line 137, in acquire
INFO - | borg.locking.LockFailed: Failed to create/acquire the lock /backup_dest/db_name/lock.exclusive ([Errno 13] Permission denied: '/backup_dest/db_name/lock.exclusive').
INFO - |
INFO - | Platform: Linux e090132a34ae 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64
INFO - | Linux: debian 9.6
INFO - | Borg: 1.1.6  Python: CPython 3.5.5
INFO - | PID: 219  CWD: /borg
INFO - | sys.argv: ['/borg', 'create', '--stats', '/backup_dest/db_name::db_name-20200107044358', '/backup_source/db_name']
INFO - | SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
You use outdated version of borg. Can you update borg and reproduce this issue?

**Comment by ThomasWaldmann** [comment]
Hmm, I read your comment about "permission denied", but that kind of error message usually comes from the kernel and should usually be correct.

So please check fs permissions (user, group, mode, acls, ...), whether the borg really runs as root and whether docker might interfere with that.

Also, I do not know "Airflow" and how you use it. borg is a single threaded **process** so there is no multi-threading at borg level. you can create multiple borg processes, of course, but if borg works with a repo, it locks that repo, so you can't work with multiple borg in the same repo at the same time.

If you just want multiple borg waiting until they can access the same repo one after each other, you only need `--lock-wait=xxxx` with a long timeout.

So, there is no "python multithreading" as far as borg is concerned. You can have N borg processes with 1 thread each.

**Comment by vrishaligiri** [comment]
@infectormp I updated borg to 1.1.10 and the issue still persists. (logs are below)

@ThomasWaldmann Sure, I'll have FS permissions check once again. Also, to add more details to my multiprocessing explanation - I use python package `import multiprocessing` and launch borg for every database at the same time (8 threads max). And every thread will run through my function of borg commands for their respective database -> init repo, backup, check and prune.

```Command line: ['/usr/local/bin/borg', '--lock-wait', '600', 'create', '--stats', '/backup_dest/db_name::db_name-20200108205451', '/backup_src/db_name']
Exit code: 2
Stderr:  | Failed to create/acquire the lock /backup_dest/db_name/lock.exclusive ([Errno 13] Permission denied: '/backup_dest/db_name/lock.exclusive').
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
|     exit_code = archiver.run(args)
|   File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
|     return set_ec(func(args))
|   File "/usr/local/lib/python3.7/site-packages/borg/archiver.py", line 151, in wrapper
|     with repository:
|   File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 189, in __enter__
|     self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
|   File "/usr/local/lib/python3.7/site-packages/borg/repository.py", line 392, in open
|     self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
|   File "/usr/local/lib/python3.7/site-packages/borg/locking.py", line 350, in acquire
|     self._wait_for_readers_finishing(remove, sleep)
|   File "/usr/local/lib/python3.7/site-packages/borg/locking.py", line 363, in _wait_for_readers_finishing
|     self._lock.acquire()
|   File "/usr/local/lib/python3.7/site-packages/borg/locking.py", line 138, in acquire
|     raise LockFailed(self.path, str(err)) from None
| borg.locking.LockFailed: Failed to create/acquire the lock /backup_dest/db_name/lock.exclusive ([Errno 13] Permission denied: '/backup_dest/db_name/lock.exclusive').
|
| Platform: Linux df8a3e007c1e 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64
| Linux: debian 9.6
| Borg: 1.1.10  Python: CPython 3.7.1 msgpack: 0.5.6
| PID: 212  CWD: /borg
| sys.argv: ['/usr/local/bin/borg', '--lock-wait', '600', 'create', '--stats', '/backup_dest/db_name::db_name-20200108205451', '/backup_src/db_name']
| SSH_ORIGINAL_COMMAND: None```

**Comment by ThomasWaldmann** [comment]
Show your code that invokes borg, please.

**Comment by vrishaligiri** [comment]
@ThomasWaldmann For official reasons, I won't be able to share the exact code. But below is a gist of the same -

```
import multiprocessing as mp

with mp.Pool(cpu_count) as mpp:
     result_list = mpp.map(execute_borg_func, (input for input in borg_input_list))

# Borg functions
def execute_borg_func(input_values):
     borg_init_repo()
     borg_create_backup() <-- fails with create/acquire lock issue
     borg_check_backup()
```

**Comment by ThomasWaldmann** [comment]
Well, as I still do not know what you are doing, I can't help you and thus I am closing this.

**Comment by vrishaligiri** [comment]
@ThomasWaldmann Here's what we found out, if helps updating the borg.

If a backup process fails while creating backup, it leaves lock.exclusive and lock.roster. In such case, if we restart the process, it couldn't delete the lock and fails with the error mentioned in subject line.

Currently we are implementing the manual process the check the lock files, if created longer than ~20 hrs, delete files - and run the backup process.

I hope it helps improve Borg. Thanks!
