### ISSUE TITLE
Understanding prune options

### ISSUE THREAD

**Issue by vonHabsi** [borgbackup/borg#4914]
When reading the documentation on prune I see that keeping a monthly backup uses the `-1` option in `borg prune -v --list --keep-daily=7 --keep-weekly=4 --keep-monthly=-1 /path/to/repo`.

Is that because using `-1` is a special option to keep monthly backups for ever regardless of how old they are so long as there is space for them?

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/prune.html#description

search for "negative" there.

**Comment by ThomasWaldmann** [comment]
It does not consider whether there is space - you have to make sure there is enough space by other means.
