### ISSUE TITLE
Borg mounted folder invisible from website

### ISSUE THREAD

**Issue by Ultome** [borgbackup/borg#4916]
I have used Borg Backup for a while now and haven't found any issue until now.
I'm trying to make accessible a mounted archive on my website, and it turned out that it didn't work no matter what I tried: the folder simply doesn't show up!
To be clear, my mounted archive is in mywebsite/path/to/mounted/archive on my server, and I can access it all right from the terminal when on my server, but from the web it just doesn't appear on the index of /path/to/mounted/archive!
What should I do?
I have tried a lot of things related to permissions but no luck there.
Any help would be appreciated!

**Comment by infectormp** [comment]
Did you try set owner for mounted folder = www-user?

**Comment by ThomasWaldmann** [comment]
Read `man fuse` and fuse documentation about fuse configuration, esp. `user_allow_other`.

Also think about unwanted security issues it might have if you expose your backups via the web server.

**Comment by Ultome** [comment]
What do you mean www-user ? Actually "www-user" or the user who owns the folder the website is in on the server? I did ensure the second proposition, but didn't try the first (should I?)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by infectormp** [comment]
I mean user who run web server i.e. apache or nginx. But this problem is windows specific i guess, so maybe this related to fuse.

**Comment by Ultome** [comment]
I have tried setting the ownership to the user maintaining the website on nginx without success, and I am on Ubuntu

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Ultome** [comment]
What would be the syntax for allow_other within my borg mount? I can't seem to find out an example on the web :/

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by infectormp** [comment]
http://manpages.ubuntu.com/manpages/bionic/en/man8/mount.fuse.8.html#configuration
add `user_allow_other` to `/etc/fuse.conf`
then 
`borg mount -o allow_other ...`

**Comment by Ultome** [comment]
INCREDIBLE! It works like a charm with this! Thank you so much for your help and your time!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
