### ISSUE TITLE
create new archive while the repo is offline or incomplete

### ISSUE THREAD

**Issue by mo-han** [borgbackup/borg#4917]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

question / feature request

This idea comes from another bakcup tool, "DAR backup", which can generate an isolated catalogue file as a reference file for future incremental backup without the existance of old backups. You can check it here http://dar.linux.free.fr/doc/Features.html, at the "ISOLATION" section.

I know these two tools work totally differently. So here is only a consultation - is it possible?

The circumstance is really not very rare - say there is folder with a lot of data, which is already fully "borged" and the repo is already burned into a blu-ray disc. then, sometime later, it need to be taken a incremental backup, but it's too slow to pull out that disc and copy the whole repo out into local disk, then do a borg backup towards the repo and finally, pick out the new created segments and updated files and burn them into a second blu-ray disc...

**Comment by RonnyPfannschmidt** [comment]
this one is a interesting idea, i do have a few ideas for a different segment handling which could enable that kind of backup

however it should be noted that that one is lingering at the back of my head since years and wont materialize any-time soon (i'm not even a regular contributor)

**Comment by ThomasWaldmann** [comment]
borg does not do "full+incremental" backups, borg always does "full" backups (so e.g. there is no difference in logical structure or use scenario between a first and a second backup). This is what pruning / deleting archives makes a lot simpler, btw.

borg just does not store the same chunks of data multiple times, this is why your 2nd+ backup "feels" incremental, speed-wise.

These "chunks" are file content data, but also pieces of the stream of files' metadata, so both are deduplicated.

Also, I'ld personally not recommend using something like BD as backup media. Compared to HDDs they are relatively slow, capacity is rather limited. Just use 2.5" USB3 HDDs, they are relatively cheap and store up to 5TB currently (and if that is not enough, there are slightly less comfortable, but higher capacity 3.5" USB3 HDDs).

BTW, iirc we already have a "multiple volumes" ticket, so maybe rather extend that.

**Comment by mo-han** [comment]
@ThomasWaldmann 
thanks for your suggestion. but why would think this feature request is only about optical-disc-burning-backup scenario? what if the repo is on a storage already full and the user has no extra space to hold the repo and the data to be added? I just use Blu-ray disc as an example.

I know about that Borg always do full backup as well as the segments being stream data. that's why I said "I know this two tools work totally differently".

btw, HDD is not as reliable as Blu-ray, since an HDD is a whole complicated device constructed of many small parts, which could lost all data as any part went wrong. especially nowadays those consumer grade cheap but high capacity HDDs are all short-lived fragile storage medium, compared to which, optical-burned disc are way too more reliable, as long as kept in proper environment.

**Comment by ThomasWaldmann** [comment]
I didn't say it is only about optical-disc scenarios, just pointed out I do not recommend such media (because you mentioned it). I also (for borg) do not recommend tapes (or any sequential or slow-random-access media), too small HDDs, too small / too cheap USB sticks or anything else that is too small or too unreliable.

About long term reliability: If your BD drive dies in some years, I could imagine the scenario that they just don't produce them any more. Then you have a lot of media and can't read them.

A USB HDD is a standalone device and just needs a USB port to work. If it dies after years long service, you buy a new bigger capacity one.

If you are ok with removing the media discussion from this ticket, I'll do so.

**Comment by mo-han** [comment]
No need to talk about something that might happen "in some years". Let's focus on the recent years and the near future. I used to have a WD My Passport portable USB HDD, which is a good product but only  worked for 4 years, and all the data on it were gone. Meanwhile, my 7 years old BD-R discs (a big pile of discs) are still readable, with a few bytes corrupted, but almost all files are in good state, right now.
You just have no idea about how fragile these HDDs are. Plate broken, data gone; motor broken, data gone; magnet head broken, data gone; circuit broken, data gone...
What if the BD readers are not produced anymore? Just transfer all the data to some kind of new-age storage medium. When would that happen? The next 10 years, or may 20 years later. Totally acceptable. So what? You thought HDD are gonna last to the end of the world? How many computers nowadays have an interface for those decades-ago storage device?
You have to transfer your precious data to new popular medium, no matter what kind of device you rely on right now.
Right now, these consumer grade HDDs are only guaranteed to work 3 to 5 years, mostly die not long after that. If you think that is long enough, talk to my discs burned 7 years ago.

And now you "friendly" ask me to stop argue on medium. Interesting, I wonder who did you think is the one to start this?
This is your project, you are the one who take decisions, but don't ever think the other users have to beg you. If this tool can't fullfil my requirements, I just use other one. So stop selling you fragile-HDD-is-a-better-backup-medium-than-optical-disc stuff.

**Comment by mo-han** [comment]
Oh, btw, Blu-ray disc and tapes are hot choice when big companies need to backup tons of cold data.
I know you know it, I'm not here to be your teacher. I'm also aware that you just don't recommend using borg "with" them. Well maybe I should do as those companies, if BD or tapes, then no borg-backup.

**Comment by ThomasWaldmann** [comment]
Yeah, do whatever you like.
