### ISSUE TITLE
proposal: a new borg wrapper/extras/helper scripts repo

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#492]
It is time to centralize all our borg wrapper scripts efforts.

Anyone interested please drop a +1 or similar.

I am sure everyone using borg and knowing a little or a lot bash scripting is writing his/her own borg wrappers. Re-inventing the wheel maybe, if too lazy to use sth like backup ninja.

Most people have 80/90% same needs and 5/10/20% different needs for the features out of a wrapper.

I propose we host a git repo under the borg organisation :
- a repo for borg wrapper / borg extras - where we write a general purpose wrapper that can: 
  - backup your mysql/pgsql/... databases before borg create to a configurable folder
  - do some lvm/btrfs/hcp/... snapshotting before borg create
  - check if the backup destination is mounted or online before borg create
  - do a post borg create borg prune
  - etc...

- same thing as above but without re-discovering the wheel - and using backup ninja for example

- or maybe we have 2-3-4 folders in the repo: one for our borg specific community wrapper , another for borg-backup-ninja, and another for some random wrappers that are unofficial and provided as is by some borg users - like cooking recipies where they always have the name of the recipe owner...

The end goal is to configure your borg routine ONCE and then use just sth like "borg-backup" or "borg-runner".

I personally have made such a wrapper that uses a conf file to set the src/dest and excludes folders, also the options I give to borg. So I am living the good life by backking up everytime with simply 'borg-backup' - manually or via cron.

My wrapper backs up mysql , does a FS snapshot, backs up with borg create, prunes and logs errors/changed files to a timestamped log file. And makes coffee.

PS. I know of the existence of this wrapper: https://github.com/witten/atticmatic

But it lacks support for custom pre hooks and post hooks - like for lvm snapshotting and mysql backup... Or I am wrong and its possible ?

**Comment by ThomasWaldmann** [comment]
well, you've already noticed that requirements are different and that one existing wrapper (atticmatic/borgmatic) does not match your needs, so you want to write your own matching-your-needs wrapper.

so the questions are:
- will that wrapper be universal enough so it is really reusable?
- or will it just have different features (and bugs, and reinvent the wheel just slightly differently)?
- is it easier to just write a custom backup script directly invoking whatever commands that are needed or having a very complex wrapper with own configuration (and own learning curve) that tries to foresee all use cases and tries to somehow support you with them (with always some risk of not being flexible enough for some use case)?

i can't tell much about atticmatic, i've had a quick look, but i don't use it myself. if you just miss a few features there, maybe talk to the author whether they could be added.

in general, adding some repo is ofc possible, we just should get clear about the goals:
- just a collection of scripts of some users (you could always publish them on your own gh account btw.)?
- a new wrapper project? (why?)

btw, I am no fan of complex shell scripts. up to a specific complexity, i am fine with them, but the longer and more complex they get, i rather want a real programming language (python).

**Comment by DrupaListo-com** [comment]
I wish there was a backup GUI that could handle any backup program backend.
Much like backup ninja is a generic wrapper, a generic backup GUI would do much of the same as backup ninja does in its text mode.

The need for a higher level borg wrapper is there for sure. It would give better UX, which is good even for the tech crowd/early adopters.

Here is what will happen now:

- we can try finding a good generic FOSS backup wrapper/GUI. Base 1 is just a text-based wrapper. Awesome if we find a GUI/grapphic backup manager too.

- if we dont find anything decent, I will begin working on my own bash based backup wrapper, generic enough for many backup programs , borg being primary the target. Secondary ones: duplicity and rdiff-backup, rsnapshot.
The design principles for my bash wrapper would be
- very simple code structure:
  - one bash file borg-backup, that handles the logic
  - one conf.sh file that holds the configuration, sane defaults and good comments there with examples ready to uncomment
  - pre-backup.d/ and post-backup.d/ to hold pre/post hooks, with names like 01-run-mysqldump.sh , 95-borg-prune.sh, so they are ordered easily with a file rename
- easy to use from end users: possibly first run wizard written in ncurses or just using bash "dialog"
- at some point even a GUI can be built to just use this wrapper and borg as backend

I need thoughts if anyone knows sth better than backupninja.
Or is it good enough ?

**Comment by ThomasWaldmann** [comment]
maybe the gui issue should be discussed in another issue, this one is about a wrapper/extras/helper scripts repo.

i thought a while about the repo and i rather think we should have a link list and everybody who feels like publishes scripts / helpers in an own (personal) repo.

mixing this stuff together will just create a maintenance problem and also a wrong impression that stuff in that repo is more than a collection of some people's scripts.

**Comment by anarcat** [comment]
for GUIs, there is #314 and https://github.com/borgbackup/borgweb

as for the general idea, +1 - i have my own set of requirements that could be implemented, detailed in #326.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/community there it is.

**Comment by witten** [comment]
> PS. I know of the existence of this wrapper: https://github.com/witten/atticmatic

> But it lacks support for custom pre hooks and post hooks - like for lvm snapshotting and mysql backup... Or I am wrong and its possible ?

Note that borgmatic (formerly atticmatic) now supports pre and post hooks. So it may meet your needs for this now.
