### ISSUE TITLE
Sorting has no effect, documented but not implemented?

### ISSUE THREAD

**Issue by ygoe** [borgbackup/borg#4920]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes (5 pages of open/closed issues looking for "sort-by"; judging by the title, none of them have to do with "sort-by")

## Is this a BUG / ISSUE report or a QUESTION?

Bug

## System information. For client/server mode post info for both machines.

Client: Ubuntu Server 18.04
Server: unknown, provided by hetzner.de

#### Your borg version (borg -V).

1.1.10

#### Operating system (distribution) and version.

Ubuntu Server 18.04

#### Hardware / network configuration, and filesystems used.

LAN, ext3/4, LVM snapshot for creating the backup

#### How much data is handled by borg?

39 GB (entire "/" ext4 filesystem + "/boot" ext3 filesystem)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

REPOSITORY="ssh://${BACKUP_USER}@${BACKUP_USER}.your-storagebox.de:23/./backup"
borg list **--sort-by name** $REPOSITORY::$archive

## Describe the problem you're observing.

The output is unsorted. Directories and file names appear in a random (seemingly deterministic, for one archive) order.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Happens every time.

#### Include any warning/errors/backtraces from the system logs

None

**Comment by ThomasWaldmann** [comment]
borg list --help (on master branch):
```
...
Archive filters:
  Archive filters can be applied to repository targets.     <----------------- !!!

...
  --sort-by KEYS        Comma-separated list of sorting keys; valid keys are:
                        timestamp, name, id; default is: timestamp
```

So, guess you misunderstood the docs.

You can only use `--sort-by` for **repository** targets, not for archive targets.
