### ISSUE TITLE
Prune with keep-last doen't work with remote repository? 

### ISSUE THREAD

**Issue by Fr3d-P** [borgbackup/borg#4925]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
1.1.9

#### Operating system (distribution) and version.
Raspbian
#### Hardware / network configuration, and filesystems used.
raspberry pi
#### How much data is handled by borg?
lots
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg prune -v --list --stats --dry-run --keep-last=5 --keep-daily=7 --keep-weekly=26 --keep-yearly=-1 ssh://pi@192.168.1.21/media/piRaidDrive/Borg/octoPi

## Describe the problem you're observing.
Message :
usage: borg [-h] [-V] <command> ...
borg: error: unrecognized arguments: --keep-last=5

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes I can reproduce the problem with keep-last, keep-secondly and keep-minutely. It begins to work with keep-hourly.

The same command, launched locally on the server
borg prune -v --list --stats --dry-run --keep-last=5 --keep-daily=7 --keep-weekly=26 --keep-yearly=-1 /media/piRaidDrive/Borg/octoPi
works .
The server and the client have the same borg version

#### Include any warning/errors/backtraces from the system logs

None

**Comment by ThomasWaldmann** [comment]
delete and prune are high-level operations implemented by the borg client, so they don't care whether your repo is local or remote.

--stats does not work with --dry-run (more recent / future borg versions warn about this).

I tested your command (removed `--stats`, with 1.1.9, with my local repo), it worked.

I suspect you have an older version of borg which you use when it does not work, so better check the exact same scenario with `borg -V`.

**Comment by Fr3d-P** [comment]
I'm confused, the version on the client was 1.0.9, not 1.1.9!
The version number was close, and in addition, `sudo apt install borgbackup` replied with
borgbackup is already the newest version  on both machines....
The system on the client's pi was Stretch, it seems that 1.0.9 was the latest version of Borg for it!

You're right, with version 1.1.9 on both sides it worked, thanks!
