### ISSUE TITLE
How to commit transaction log?

### ISSUE THREAD

**Issue by doits** [borgbackup/borg#4926]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.10

## Question

I have a client that backups to a remote location (server) in append only mode (`borg serve` is run with append only flag). This means prunes do not actually free disk space, everything is fine.

Now on the server I can access that repository, too, and see the transaction log. How can I apply the transaction log so files are actually deleted, disk space is freed etc.? Is there a command for this? Something like "everything what the client requested in append only mode is fine, let's commit it now"?

**Comment by ThomasWaldmann** [comment]
you just need to run some repo-writing operation (e.g. borg prune) with append-only mode switched off.

if you use authorized_keys method, you can just use a different ssh key for an entry without append-only.

**Comment by doits** [comment]
Thanks for the info. That is a good idea to run pruning with a separate key (and from another trusted machine).

Thinking more about it: Is there a way to have one key do append-only changes but *ignore/prevent* non append-only changes like pruning, so that they are not even written to the transaction log for later playback?

That meant I could be sure the untrusted key can never add something to the transaction log that will be played out later when the trusted key does a non append-only repo-writing operation (like pruning old backups). Otherwise there might be malicious entries in the transaction log from the untrusted key that will be played back when the trusted key writes to the repo.

Something like `borg serve --only backup` that means only the `backup` command can be run. Not sure if this is possible to implement or if there is an already a solution for what I am thinking?

**Comment by ThomasWaldmann** [comment]
BTW, you need to upgrade your borg version (1.1.10 -> 1.1.13), see the changelog of more recent versions and esp. the advisory at top of the changelog.

**Comment by ThomasWaldmann** [comment]
There is no way of letting borg do just specific high-level operations. In fact, the repo side (borg serve) does only see low-level operations (get, put, delete chunk) and does not even know to which high-level operation (create, extract, delete, prune) they belong.

So, append-only is the only thing there is.

Technical detail:

In fact, borg 1.1.x works by only appending for (the first phase of) all repo-writing operations it does.

In 1.1.x, the first phase is followed by a second phase doing compact_segments() which is not just appending.
append-only mode basically disables the 2nd phase, so all historic states are preserved in the repo.

In borg 1.2, there is no 2nd phase, but a separate `borg compact` command.
