### ISSUE TITLE
Configure Borg to store cache inside repository

### ISSUE THREAD

**Issue by Feuermurmel** [borgbackup/borg#4929]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question/Feature request

#### Your borg version (borg -V).

```
$ borg --version
borg 1.1.9
```

#### Operating system (distribution) and version.

Debian stretch.

#### Hardware / network configuration, and filesystems used.

Local directory on ZFS.

#### How much data is handled by borg?

2 to 2.5 TiB.

## Describe the problem you're observing.

I'm have a repository containing about 700 archives, each referencing about 2 TB of data. In the past 3 months I've hit a few issues with the chunk cache and Borg hat to rebuild the cache twice, which took almost a week both times. `~/.cache/borg` is on the root ext4 filesystem with limited space while the borg repository is on a separate, local ZFS filesystem with (almost) unlimited space. The whole ZFS pool has hourly snapshots which are kept for a week, as kind of a filesystem-level undo. I haven't investigated the exact causes for the cache becoming invalid but I think it was related to the root filesystem temporarily filling up and terminating the `borg create` process ungracefully.

In any case, those instances where the cache had to be rebuilt seem utterly unnecessary. In both cases, when Borg noticed that it fricked up its cache data structures, and assuming that those caches were also stored in the same ZFS filesystem, I could have just rolled back that filesystem to before Borg was terminated and all should be in a consistent state again.

Now my question is, is there an intended way to configure Borg either globally or per-repository to store its caches inside or alongside the repository? I've seen the `BORG_CACHE_DIR` environment variable but that seems to have two issues: (A) Doesn't work with multiple repositories (I would have to set it manually on the command line each time I invoke Borg, which is error prone) and (B) If I ever forget to set it when running Borg, the cache will become out of date and has to be rebuilt (which I'm trying to avoid in the first place).

I think a sensible way would be to provide a global or repository-level setting which can be used to enable such a feature.

**Comment by ThomasWaldmann** [comment]
The cache is not encrypted and expected to be at a secure place.
The threat model of borg assumes that the repo is not at a (totally) secure place.
So we can not store the cache "inside" the repository.
