### ISSUE TITLE
list: sort by size

### ISSUE THREAD

**Issue by blueyed** [borgbackup/borg#4932]
It would be nice if `borg list --sort-by size` would work.

This can be useful to inspect archives for large files that could/should be
excluded maybe.

Currently only the following keys are supported:
```
  --sort-by KEYS        Comma-separated list of sorting keys; valid keys are:
                        timestamp, name, id; default is: timestamp
```

#### Your borg version (borg -V).

borg 1.2.0a8.dev62+g61b82347.d20200127

**Comment by ThomasWaldmann** [comment]
Sorting is only for the archive listing (== repo contents), not for the files listing (== archive contents).

**Comment by blueyed** [comment]
Oh, I see.
Would it be possible to have the latter in general?

And apart from that the help/doc should be clarified maybe?

**Comment by jdchristensen** [comment]
I use the follow to sort the output of `borg list <archive>` by size, largest first:

```
sort -n -r -k 4
```

**Comment by ThomasWaldmann** [comment]
It is already documented, see headline:

"Archive filters — Archive filters can be applied to **repository targets**.".

**Comment by ThomasWaldmann** [comment]
In general I don't think it makes much sense to implement this inside borg - it would have to buffer all the output (which is potentially huge for files listing) and then sort it afterwards. You can have the same by using `sort` as @jdchristensen pointed out.
