### ISSUE TITLE
Release key expired

### ISSUE THREAD

**Issue by Demosthenexx** [borgbackup/borg#4933]
The release key has expired. The builds look updated as the releases are signed, but the key isn't published in the documentation.

```
~/software/borg                                                                        
% gpg --recv-keys 9F88FB52FAF7B393                                                     
gpg: key 9F88FB52FAF7B393: 283 signatures not checked due to missing keys              
gpg: key 9F88FB52FAF7B393: public key "Thomas Waldmann <tw@waldmann-edv.de>" imported  
gpg: marginals needed: 3  completes needed: 1  trust model: pgp                        
gpg: depth: 0  valid:   4  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 4u                  
gpg: next trustdb check due at 2025-10-17                                              
gpg: Total number processed: 1                                                         
gpg:               imported: 1                                                         

~/software/borg                                                             
% gpgv borg-linux64.asc borg-linux64                                        
gpgv: Signature made Thu 16 May 2019 05:18:18 AM CEST                       
gpgv:                using RSA key 2F81AFFBAB04E11FE8EE65D4243ACFA951F78E01 
gpgv:                issuer "tw@waldmann-edv.de"                            
gpgv: Can't check signature: No public key                                                                                                                         

~/software/borg                                                        
% gpg --list-keys    6D5BEF9ADD2075805747B70F9F88FB52FAF7B393          
pub   rsa4096 2009-12-25 [SC] [expired: 2019-12-24]                    
      6D5BEF9ADD2075805747B70F9F88FB52FAF7B393                         
uid           [ expired] Thomas Waldmann <tw@waldmann-edv.de>          
uid           [ expired] Thomas Waldmann <tw-public@gmx.de>            
uid           [ expired] Thomas Waldmann <twaldmann@thinkmo.de>        
uid           [ expired] Thomas Waldmann <thomas.j.waldmann@gmail.com> 
```

https://borgbackup.readthedocs.io/en/stable/support.html#security-contact

This document shows the old key that expired.

**Comment by ThomasWaldmann** [comment]
Hmm, i have uploaded same key with later expiry date a few weeks ago to some keyserver.

From which keyserver did you get the old key?

**Comment by Demosthenexx** [comment]
I'm using pgp.mit.edu. It allowed me to successfully download the old key listed in the documentation.

In the example above, the released code was signed with a new key ending in 8E01. All of the Borg documentation points to your old key ending in B393.

Given that the B393 key expired at end of 2019, I assume you've created a new key for signing releases. I think the docs just need to be updated with that key information.

**Comment by intdel** [comment]
Same problem here:

`root@borgbase:/tmp# gpg --recv-keys --keyserver hkps://keyserver.ubuntu.com "6D5B EF9A DD20 7580 5747 B70F 9F88 FB52 FAF
7 B393"
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 9F88FB52FAF7B393: public key "Thomas Waldmann <tw@waldmann-edv.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1
root@borgbase:/tmp# gpg --verify borg-linux64.asc
gpg: assuming signed data in 'borg-linux64'
gpg: Signature made Thu 16 May 2019 05:18:18 AM CEST
gpg:                using RSA key 2F81AFFBAB04E11FE8EE65D4243ACFA951F78E01
gpg:                issuer "tw@waldmann-edv.de"
gpg: Good signature from "Thomas Waldmann <tw@waldmann-edv.de>" [expired]
gpg:                 aka "Thomas Waldmann <thomas.j.waldmann@gmail.com>" [expired]
gpg:                 aka "Thomas Waldmann <twaldmann@thinkmo.de>" [expired]
gpg:                 aka "Thomas Waldmann <tw-public@gmx.de>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 6D5B EF9A DD20 7580 5747  B70F 9F88 FB52 FAF7 B393
     Subkey fingerprint: 2F81 AFFB AB04 E11F E8EE  65D4 243A CFA9 51F7 8E01`

**Comment by Demosthenexx** [comment]
Note there is a difference in the output between gpgv and 'gpg --verify':

'''                                                        
% gpgv -v borg-linux64.asc borg-linux64                                                 
gpgv: Signature made Thu 16 May 2019 05:18:18 AM CEST                                   
gpgv:                using RSA key 2F81AFFBAB04E11FE8EE65D4243ACFA951F78E01             
gpgv:                issuer "tw@waldmann-edv.de"                                        
gpgv: Can't check signature: No public key                                              
                                                                                                                                 
% gpg --verify borg-linux64.asc                                                         
gpg: assuming signed data in 'borg-linux64'                                             
gpg: Signature made Thu 16 May 2019 05:18:18 AM CEST                                    
gpg:                using RSA key 2F81AFFBAB04E11FE8EE65D4243ACFA951F78E01              
gpg:                issuer "tw@waldmann-edv.de"                                         
gpg: Good signature from "Thomas Waldmann <tw@waldmann-edv.de>" [expired]               
gpg:                 aka "Thomas Waldmann <tw-public@gmx.de>" [expired]                 
gpg:                 aka "Thomas Waldmann <twaldmann@thinkmo.de>" [expired]             
gpg:                 aka "Thomas Waldmann <thomas.j.waldmann@gmail.com>" [expired]      
gpg: Note: This key has expired!                                                        
Primary key fingerprint: 6D5B EF9A DD20 7580 5747  B70F 9F88 FB52 FAF7 B393             
     Subkey fingerprint: 2F81 AFFB AB04 E11F E8EE  65D4 243A CFA9 51F7 8E01             
                                                                                        
'''

Perhaps gpgv doesn't respect an expired key by default?

**Comment by ThomasWaldmann** [comment]
I uploaded it again to keyservers, pgp.mit.edu and sks-keyservers.

I also attached my pubkey to this comment.
[gpg-tw2020-pub.txt](https://github.com/borgbackup/borg/files/4141319/gpg-tw2020-pub.txt)

**Comment by Demosthenexx** [comment]
Can you update the expiration on an already published key? I thought you had to issue a new one?

**Comment by ThomasWaldmann** [comment]
Yes, you can extend the expiry date by "editing" the key with gpg.

And I do not know any reason why one shouldn't do that, except if you think your key got somehow less secure (e.g. because someone has copied your private key, because the key strength is not adequate any more, etc.).
