### ISSUE TITLE
borg extract --strip-components --list has confusing output

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#4934]
The list output gives the original paths, without --strip-components applied. So if you are looking to extract files, the list output actually does not represent the paths Borg is or would be (--dry-run) writing.

**Comment by Gu1nness** [comment]
Can I take this one?

**Comment by ThomasWaldmann** [comment]
@Gu1nness sure (all tickets are free to take as long as nobody is assigned / told that they are working on it in a comment).

**Comment by ThomasWaldmann** [comment]
Fixed in master, Backport to 1.1-maint still to do.

**Comment by ThomasWaldmann** [comment]
Fixed in 1.1-maint by #4973.
