### ISSUE TITLE
Interactive mode for the prune command

### ISSUE THREAD

**Issue by dachev** [borgbackup/borg#4936]
It would be nice to have the option to prompt the user for confirmation before archive deletion. Users that rely heavily on their shell history instead of typing commands from scratch are less thoughtful of the effects of their actions.

It would be nice to have a CLI option that will require an interactive confirmation before deleting an archive. Perhaps it would be even better to also show a list of archives that will be kept. This will help people develop intuition and will be a great learning tool.

**Comment by ThomasWaldmann** [comment]
isn't there borg prune --dry-run so you can have a look first?

**Comment by dachev** [comment]
The idea is to prevent unexpected outcomes without active participation from the user. It will probably be even wiser to require interactive confirmation by default and allow passing a `-y` parameter for non-interactive execution. This is not without a precedent and standard behavior in Debian's `apt` utilities or example.

**Comment by ThomasWaldmann** [comment]
A lot of setups do `borg prune` via cron-job or sth similar.

So we can't just change the default behaviour to be interactive or it will break (hang) everybody's cron jobs.

**Comment by dachev** [comment]
I see. We definitely don't want to break existing installations. Perhaps something to consider if one day you happen to refactor the commands and/or go to version 2.
