### ISSUE TITLE
Feature Request: borg export-tar: Archive filters

### ISSUE THREAD

**Issue by 90er** [borgbackup/borg#4937]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Most of

## Is this a BUG / ISSUE report or a QUESTION?

Feature Request

#### Your borg version (borg -V).
1.1.10

#### Operating system (distribution) and version.
Debian 9

#### Hardware / network configuration, and filesystems used.
Not important

#### How much data is handled by borg?
~200 MB unique files per Repository

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg export-tar (--last 1)

## Describe the problem you're observing.
i want to only export the latest archive of an Repository using borg export-tar. As I red the manpage, the filter for the e.g. last 1 archive is only available for borg list but not for borg export-tar.

```
Archive filters:
  Archive filters can be applied to repository targets.

  -P PREFIX, --prefix PREFIX
                        only consider archive names starting with this prefix.
  -a GLOB, --glob-archives GLOB
                        only consider archive names matching the glob. sh:
                        rules apply, see "borg help patterns". ``--prefix``
                        and ``--glob-archives`` are mutually exclusive.
  --sort-by KEYS        Comma-separated list of sorting keys; valid keys are:
                        timestamp, name, id; default is: timestamp
  --first N             consider first N archives after other filters were
                        applied
  --last N              consider last N archives after other filters were
                        applied
```

Right now I use a workaround to iterate trough all Repositorys and get the latest archive per Repository using borg list --last 1 and export them.

```
for i in $(ls $FOLDER)
do
	BORGLIST=$(borg list --last 1 ${FOLDER}/${i}/)
	borg export-tar --tar-filter=gzip ${FOLDER}/${i}::${ARCHIVE} ${HOME}/${i}.tar.gz
done
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
See above

**Comment by ThomasWaldmann** [comment]
well, that "workaround" is the intended way to do this currently.

**Comment by ThomasWaldmann** [comment]
I am closing this, due to:
- there is a working way to solve and it is rather obvious scripting
- the archive filters, in the general case, select N archives (N being 0 ... <all archives>), but `borg export-tar` only works correctly / makes sense for N == 1.
