### ISSUE TITLE
borg binary: Exception when trying to find/load libc

### ISSUE THREAD

**Issue by TheVillux** [borgbackup/borg#494]
I was reticent to mention this, since it's a very specific situation, but somebody in IRC suggested opening a bug. Anyhow, I'm attempting to use Borg via a bootable ISO based off of CentOS 6 using the Relax and Recover disaster recovery system.

When attempting to run either 0.28.2 or 0.29.0 from inside of the bootable recovery system I get the Traceback mentioned in the title. I ran a stack trace to see if I was missing a library, but I didn't see anything amiss off-hand. Also running ldd against borg doesn't seem to turn up any missing items.

I don't know much about Python, so I'm not sure what you need in order to assist, but here's the last couple of lines from the Traceback:
```
File "<string>", line 121, in __init__
File "/home/vagrant/.pyenv/versions/3.5.1/lib/python3.5/posixpath.py", line 139, in basename
AttributeError: 'NoneType' object has no attribute 'rfind'
__main__ returned -1
```
More Traceback info can be found here:
[borg_0.29.0_traceback.txt](https://github.com/borgbackup/borg/files/63456/borg_0.29.0_traceback.txt)

Before I found Borg, I was using this setup with Attic and that binary seemed to work okay.

**Comment by ThomasWaldmann** [comment]
The xattr.py line 31 that causes the fail is:
```
libc = CDLL(find_library('c'), use_errno=True)
```
So it seems it has trouble finding your (g)libc.

**Comment by ThomasWaldmann** [comment]
Also try on that machine (using python 2.5/6/7 or 3.2/3/4/5):
```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> CDLL('libc.so.6')
<CDLL 'libc.so.6', handle 7f5292511a88 at 7f529239cc90>

>>> from ctypes.util import find_library
>>> find_library('c')
'libc.so.6'
```

**Comment by TheVillux** [comment]
This is a minimal bootable system for Disaster Recovery, based off of a full CentOS 6 system, so there's no python, cc, gcc, ldconfig or objdump installed on it.

I apologize for the dropbox links, I'll attach the traceback to my original post.

```
ldd /usr/local/bin/borg
    linux-vdso.so.1 =>  (0x00007ffd6b060000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f45d6b17000)
    libz.so.1 => /lib64/libz.so.1 (0x00007f45d6901000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f45d656c000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f45d6d1e000)
```

**Comment by ThomasWaldmann** [comment]
My suspicion is that it might be a bit too minimal then to be generally useful for running stuff.
As /sbin/ldconfig isn't big, maybe it should be just included.

Maybe first try to copy it onto that system manually and check if borg works then. If so, file a ticket at "rear" project.

**Comment by TheVillux** [comment]
I can easily include anything else I need to, I just need a little hand holding to figure out what that might be. I thought when I ran "ldd" against borg it would just show me the missing library, but that doesn't seem to be the case.

**Comment by ThomasWaldmann** [comment]
The binary uses some bootstrap loader to get things going, what ldd shows you is likely what the loader needs. The loader then unpacks all the stuff to /tmp/_ME* (a directory including all needed python and binary library files) and then invokes the borg main program there. Then, python imports stuff and python's "ctypes" fails to find your libc.

**Comment by TheVillux** [comment]
Okay, that makes sense, let me see if I can use pmap or something to figure out what all the requirements are.

**Comment by TheVillux** [comment]
I believe I've found the culprit (which you already mentioned), it was simply a matter of **/sbin/ldconfig** missing. In order to figure this out, I used **strace -f -e trace=process borg** The **-f** was key, in order to capture child process info, which may not have dawned on me without your input above.

**Comment by ThomasWaldmann** [comment]
Well, we maybe can do a "last resort" trick for that case:

I bet the function that usually finds the library name returns None in such a case.
But if we can do a good guess about the library name (like "libc.so.6" for linux) we could just try that in case we got None and in case we are on Linux.

**Comment by TheVillux** [comment]
Whatever you think is appropriate. I just updated my build script to include */sbin/ldconfig* in the recovery ISO and all seems well now for my use case.

**Comment by ThomasWaldmann** [comment]
OS X: libc.dylib (works without abs. path)
netbsd / freebsd: libc.so
openbsd: does not work, no symlinks
linux: libc.so.6
