### ISSUE TITLE
How important is $HOME/.config/borg?

### ISSUE THREAD

**Issue by remyabel** [borgbackup/borg#4941]
I've been reading the docs and issues over and over and it isn't clear to me how important the `$HOME/.config/borg` folder is. I'm getting the impression that analogous to duplicacy's per-repo `config` file, that the `$HOME/.config/borg` folder needs to be backed up independently as it contains stateful information. Which leads me to the following questions and I apologize if this has already been answered elsewhere:

- Should I back this folder up independently? i.e, if it gets corrupted what do I lose in terms of the ability to do with my repos?

- Is it a security risk if someone gains access to this folder? Meaning can I back it up in plaintext or do I need to encrypt it (file permissions aside)?

- Furthermore what happens if you delete `$HOME/.config/borg/cache`. Considering it's called the "cache" folder one would think it could be deleted safely, but it appears that if you delete it you need to use environment variables to silence warnings about unknown/untrusted repositories. Is this permanent or can the cache be regenerated?

**Comment by fantasya-pbem** [comment]
I am currently working on this.

**Comment by fantasya-pbem** [comment]
Please review the new FAQ entry. Is this answering your question / clarifying the matter?
