### ISSUE TITLE
How does borg handle a repository which uses the same archive name everytime?

### ISSUE THREAD

**Issue by vonHabsi** [borgbackup/borg#4942]
The documentation gives an example where a backup is created with the name `{hostname}-{now}` meaning that the repository will have backups distinguished by the time.

What happens if the `borg-create` command always uses `{hostname}` only, without the `{now}`?

Will it still be possible to retrieve by date range earlier versions of files create with the same archive name, or prune them if they still exist?

Do subsequent borg-create commands overwrite the files of the earlier backups?

Does deduplication still occur?

**Comment by ThomasWaldmann** [comment]
I will reject duplicate-name archive creation.

**Comment by vonHabsi** [comment]
Do you mean "I**t** will reject duplicate-name archive creation"?

It looks like you missed the **t** in the **It**

**Comment by ThomasWaldmann** [comment]
Oh, oops, yes "it". :-)

**Comment by vonHabsi** [comment]
I wanted to be sure that you didn't mean it was a feature you had no intention of supporting. Thanks

**Comment by ThomasWaldmann** [comment]
Well, as the archive name is used as a key into the list of archives, there actually is no intention to allow duplicate keys (because that would just not work).
