### ISSUE TITLE
[QUESTION] Backing up Windows partition / files from Windows partition

### ISSUE THREAD

**Issue by Gladuin** [borgbackup/borg#4944]
Hello,

I have no problem using Linux to back up my files, but I also want to be able to backup the files from my Windows partition. Would simply mounting my partition using ntfs-3g be sufficient?

I apologize if this has been asked before and I hope someone can answer this.

**Comment by infectormp** [comment]
There is no problem to do backup files from Windows partition using ntfs-3g. 

Fell free to open new issue if you will have any problems.

**Comment by Gladuin** [comment]
> 
> 
> There is no problem to do backup files from Windows partition using ntfs-3g.
> 
> Fell free to open new issue if you will have any problems.

That'll backup everything right (ie. hidden files, system files, etc.)

**Comment by infectormp** [comment]
> That'll backup everything right (eg. hidden files, system files, etc.)
Have no idea, but I not see any reason why borg must not do that

**Comment by Gladuin** [comment]
> 
> 
> > That'll backup everything right (eg. hidden files, system files, etc.)
> 
> Have no idea, but I not see any reason why borg shouldn't do that

Alright, thank you for clarifying!
