### ISSUE TITLE
Windows attributes dont get backed up

### ISSUE THREAD

**Issue by Gladuin** [borgbackup/borg#4945]
Hi,

I am testing borg out before actually using it and found out that borg doesn't back up windows attributes (read-only, system file, hidden, etc.).

I am using borg v1.1.9 on WSL, but I can (and probably will) use it on Linux if I'm going to make a full backup of my partition.

Thanks for helping me in advance.

**Comment by infectormp** [comment]
See https://borgbackup.readthedocs.io/en/stable/usage/general.html#platforms

**Comment by ThomasWaldmann** [comment]
All kinds of windows support are pretty much experimental still.

cygwin and WSL might work to some degree, native windows is rather broken.
