### ISSUE TITLE
--umask not honored in ssh authorized_keys forced command

### ISSUE THREAD

**Issue by atfrase** [borgbackup/borg#4947]
I'm setting up a remote borg server (v1.1.10 on both sides), and I tried setting the `--umask` option in the `authorized_keys` file like so:

```restrict,command="borg serve --umask 007" ssh-ed25519 AAAA....```

Unfortunately, repositories and archives created using this ssh key nonetheless use the default 077 umask. Specifying `--umask 007` explicitly on the client side with each operation (init, create, ...) results in the correct permissions on the server, but the whole idea of the ssh forced command approach is for the server to be able to enforce (or at least set a default for) some options without the client having to worry about it every time.

There is another open issue (#346) for repo-level default values which would also meet my need, but I'm filing this as a technically separate issue.

There is also a closed issue (#1168) for supporting `borg serve --append-only` which might be a good template for adding similar support for `borg serve --umask`?

**Comment by ThomasWaldmann** [comment]
If somebody has some time to independently reproduce the issue, that would be welcome!

**Comment by ThomasWaldmann** [comment]
The problem is that server-side authorized_keys-forced-command umask would be honoured **IF** it was not overridden by the client, but the client always overrides it because it always puts `--umask=NNN` into the commandline when invoking the server-side borg.

**Comment by ThomasWaldmann** [comment]
We could change that behaviour so that it only transmits the client-side umask to the server-side IF the umask is manually set on the client-side. This needs a change in argparsing so that is uses a None default so we can detect whether it was manually set or not.

**Comment by ThomasWaldmann** [comment]
The problem is that "umask" is on the whitelist, so it is currently allowed to be specified by the client and it can not be overridden server-side:

https://github.com/borgbackup/borg/blob/1.1.10/src/borg/archiver.py#L4332

So, guess we would need to remove it from the whitelist to enable server-side enforcement, but then the client loses control over umask. Guess that needs to wait until borg 1.2?

**Comment by knutov** [comment]
@ThomasWaldmann (sorry for the offtopic) It's been a long time from the last stable release. When do you plan to release next 1.1.* stable version and stable 1.2?

**Comment by ThomasWaldmann** [comment]
see milestones.

1.1.11 asap.
1.2 will get a new alpha at some time, final release will take longer.

**Comment by ThomasWaldmann** [comment]
@knutov 1.2.0a8 released (and I will delete the unrelated posts from this ticket now, including this one).

**Comment by ThomasWaldmann** [comment]
this needs an update of usage.rst also, search for `--umask`.
