### ISSUE TITLE
Receiving Data integrity error on backup

### ISSUE THREAD

**Issue by struthio** [borgbackup/borg#4952]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg 1.1.10
#### Operating system (distribution) and version.
UBUNTU 18.04
#### Hardware / network configuration, and filesystems used.
ODroid-H2 (running borg backup) + WD MyCloud EX2 as backup filesystem connected to ODroid by SSHFS
#### How much data is handled by borg?
800GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create			\
	--verbose		\
	--stats			\
	--noatime		\
	--noctime		\
	--compression lzma,9	\
	/mnt/borg/photos_catalog::'{now}-{hostname}' ./photos 2> ${TEMP_FILENAME}

## Describe the problem you're observing.
I wanted to create initial backup with BORG.
After running for about a week I run borg check command and received some integrity errors (Data integrity error: Segment entry data short read). I thought something went wrong and decided to rerun initial backup this time by adding to backed up folder 100GB and running command above (8 runs in total). 

After I running borg create for last time i executed borg check and... again i have messages like:
Data integrity error: Segment entry data short read [segment 1282, offset 69905865]: expected 2206587, got 119342 bytes

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, see description above.

#### Include any warning/errors/backtraces from the system logs
No issues in logs found

**Comment by ThomasWaldmann** [comment]
Well, it didn't get all the data it wanted when reading from the segment file.

2 potential causes:
- segment files got truncated somehow (fs problem?)
- length information got corrupted (RAM not working OK)

So, maybe do a fsck and a memtest86+ run first.

Maybe also test the disk (smartctl -t long and after that has completed, look at smartctl -a).

BTW: lzma,9 doesn't make sense (except if you want to generate heat), see the docs about that.

**Comment by jurgenhaas** [comment]
My setup is very similar to the one posted above, just the error message is slightly different:

```
Data integrity error: Segment entry checksum mismatch [segment 51, offset 516914654]
Starting repository index check
Index object count mismatch.
committed index: 109158 objects
rebuilt index:   108953 objects
ID: ca70a09027938c6c1bd2975c89e92ca9738315a26a7d66cf507976fd4cad6d44 rebuilt index: <not found>      committed index: (51, 393146103)
ID: fd109c0f6583099352d7493fa06100bf43714c2e848f3b7f97f192c2168a851b rebuilt index: <not found>      committed index: (51, 306857794)
ID: 34a95cda4ea99c78f1e7ca4aa9f08533c9e2c69366ec90fbb08b76fe9fd2afa5 rebuilt index: <not found>      committed index: (51, 131355525)
ID: c184f8a2ecb3bbe30c1e643b0d0669d37cc249015c6f677a8fb7b2ec71673014 rebuilt index: <not found>      committed index: (51, 173289506)
...
...
```

What's confusing, when running the check again with the same command `borg check --prefix {hostname}- --info /var/backups/borg/nextcloud_paragon`, it runs through and reports no errors. I've seen this twice and wonder, if the system is self-healing or what else could be the reason for this.

**Comment by ThomasWaldmann** [comment]
Both of you should upgrade to borg 1.1.11 and read the changelog (esp. the data corruption advisory at the top):

https://github.com/borgbackup/borg/blob/1.1-maint/docs/changes.rst#pre-1111-potential-index-corruption--data-loss-issue

**Comment by ThomasWaldmann** [comment]
And please file a new bug if you still have issues with borg 1.1.11 (after following the procedure in the advisory).

**Comment by struthio** [comment]
For my issue problem was (I guess) with LZMA. When I switched to LZ4 compression everything worked without issue. I was able to backup 1TB of photos and then run check on it without any issues.

**Comment by ThomasWaldmann** [comment]
"correlation is not causation".

As of now, I don't see how the compressor could be related to that, but if you can consistently reproduce multiple times so there is some indication of a causation, please open a separate issue about that.

**Comment by ThomasWaldmann** [comment]
And don't do anything else before you have followed the advisory.

**Comment by jurgenhaas** [comment]
@ThomasWaldmann thanks for your advice, this seems to have resolved my issue.
