### ISSUE TITLE
stats no longer shows day of week

### ISSUE THREAD

**Issue by aklaver** [borgbackup/borg#496]
borg 0.29.0

When using create --stats  the output no longer shows the day of the week.

0.28.2 output:
Keeping archive: panda-121415_1835                    Mon Dec 14 18:35:50 2015
Keeping archive: panda-121415_0925                    Mon Dec 14 09:26:27 2015
Keeping archive: panda-121315_1835                    Sun Dec 13 18:36:03 2015
....
0.29.0 output:
Keeping archive: panda-121515_1537                    2015-12-15 15:37:50
Keeping archive: panda-121515_0654                    2015-12-15 06:55:36
Keeping archive: panda-121415_1835                    2015-12-14 18:35:50
Keeping archive: panda-121315_1835                    2015-12-13 18:36:03
....

**Comment by ThomasWaldmann** [comment]
Yes, we use a iso-8601 like format without weekday now. Is that a problem?

**Comment by aklaver** [comment]
The day of the week helped provide context to the date.  It is useful in seeing the prune schedule at work. Generally I see loss of information as a negative and therefore something that should be left to the end user to decide.

**Comment by ThomasWaldmann** [comment]
So, which shall it be?:

a) Sun, 2015-12-20 23:59:59
b) 2015-12-20 23:59:59 (Sun)

**Comment by aklaver** [comment]
My preference would be a), but as long as the day of the week is present I will be happy. Thanks for taking a look at this.

**Comment by jungle-boogie** [comment]
I'm happy to see the iso standard for the date. Thank you for your efforts to have this in v29.

I'd also prefer option a.

**Comment by level323** [comment]
I don't want to throw this discussion off track,  but I've been following
the thread and was wondering if "X days ago" kind of reporting might not be
more generally informative? Although the OP seems to have a particular
desire to know the name of the day of the week that an archive was
constructed, perhaps even more users would find value in output which
stated the days/hours sine the present when the archive was made?

**Comment by ThomasWaldmann** [comment]
BTW, I hate "x TIMEUNIT ago" (in general).

I want to have precise timestamps without having to do clock/calendar calculations (and then still not having a precise value).

**Comment by tconstans** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Why not formatting date according to current locale ?
- --
Thomas Constans
Opendoor
+33 6 23 37 87 85

Sent from mobile phone.
Envoyé de mon téléphone, excusez la brièveté.

Le 18 décembre 2015 22:35:58 UTC+01:00, level323 <notifications@github.com> a écrit :
>I don't want to throw this discussion off track,  but I've been
>following
>the thread and was wondering if "X days ago" kind of reporting might
>not be
>more generally informative? Although the OP seems to have a particular
>desire to know the name of the day of the week that an archive was
>constructed, perhaps even more users would find value in output which
>stated the days/hours sine the present when the archive was made?
>On 19 Dec 2015 2:34 am, "jungle-boogie" <notifications@github.com>
>wrote:
>
>> I'm happy to see the iso standard for the date. Thank you for your
>efforts
>> to have this in v29.
>>
>> I'd also prefer option a.
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/borgbackup/borg/issues/496#issuecomment-165807518>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/496#issuecomment-165902766
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFJBAEBCgAzBQJWdJJlLBxUaG9tYXMgQ29uc3RhbnMgKG5vbmUpIDx0aG9tYXNA
b3BlbmRvb3IuZnI+AAoJELoZdF+AQQVBFiEH/2o/oDuLjQIQsPGbijSCkOM7zx1Q
KEgrIQSdLm4y+IDD63EF+vDAPVqfemKmGXHAu25h92zmLBn7KVjOLQ/qEHZEGz2L
p+X4uAm5o/NwutPyT2HepB0bslhhPBy5VmmwgZuFZlqeDFZhpFPRnvZqEIQf3Wvo
EY2Gb4czZcTrCAiXSTGDfkHexF80ZDOcD+dKVFO9skambza6721TKsfK4pn/EHUO
SJ9dJl+TGEB40sn7bsRuMauv5VJHjZwrXDr7ZuE1C6F/b5pPNP6e+zTxqowlyTBD
znf116QAnQgDzDoGxVYzhrk561hU8+HF7r/ClJIMkPMQv7r+OpVIHzz8y4E=
=K8AS
-----END PGP SIGNATURE-----

**Comment by jungle-boogie** [comment]
> Why not formatting date according to current locale ?

Not in favor of that. iso 8601 is good.

**Comment by aklaver** [comment]
I think using current locale is not a bad idea, as it is the point of the i18n/L10n sequence. The issue with regards to Borg is that,  as far as I understand, there is no global config file to hold user preferences.

**Comment by aklaver** [comment]
#TW I agree,  TIME ago tends to make me more confused then enlightened.

**Comment by ThomasWaldmann** [comment]
@tconstans there is currently no l10n/i18n in borg. English is used because it is the de-facto international language (and esp. system administration language) and iso 8601 is used now as the standardized international date/time format (rather than using the confused/confusing british/american way of writing date and time).

The iso 8601 way of date/time formatting has a logical order from big to small units (left to right) and (because of that) it also sorts correctly without further effort.
