### ISSUE TITLE
test of / upgrade to pyinstaller 3.6 / 4.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#4963]
pyinstaller 3.6 was recently released.

first try in master branch, then decide about backport to 1.1-maint.

**Comment by Gu1nness** [comment]
Ok, I'll have a look at it then in order to solve #5019

**Comment by ThomasWaldmann** [comment]
Pyinstaller 4.0 was released a while ago, we can test that also.

**Comment by ThomasWaldmann** [comment]
master branch and 1.1-maint branch will now use latest pyinstaller.
