### ISSUE TITLE
Parity check/recover considered?

### ISSUE THREAD

**Issue by brenthuisman** [borgbackup/borg#498]
Is the addition of parity or Parchive like features considered? In my opinion a secure backup tool is the perfect candidate for the inclusion of this kind of feature in the fight against bitrot. Seeing that attic/borg already checksums data, why not go a step further and allow us to recover bytes that were corrupted during storage.

**Comment by ThomasWaldmann** [comment]
There is already a ticket to discuss that stuff:

https://github.com/borgbackup/borg/issues/225

Maybe you can add "Parchive" (with link) there please?
