### ISSUE TITLE
needs exec /tmp

### ISSUE THREAD

**Issue by dieeasy** [borgbackup/borg#499]
Trying to execute borg (0.29.0, standalone binary) on a system where /tmp is mounted noexec
```
$ mount |grep 'on /tmp'
/dev/mapper/vg-tmp on /tmp type ext4 (rw,noexec,nosuid,nodev,noatime,user_xattr)
```
fails with the following error: 
```
borg: error while loading shared libraries: libz.so.1: failed to map segment from shared object: Operation not permitted
```
Enabling exec (```$ sudo mount -o remount,exec /tmp```) allows borg to run normally.
Borg should be able to run on systems where /tmp is monted noexec, in my opinion.

**Comment by ThomasWaldmann** [comment]
Yes, that's a known property of pyinstaller single-file binaries, they unpack to TEMP and then execute the binary from the unpacked directory.

You can try:
- setting TEMP environment variable and point to a directory with exec permissions. use a place with lots of space because borg uses TEMP otherwise also.
- grabbing the /tmp/_ME* directory while borg is running and copy it elsewhere - later start borg directly from that directory.

I'll keep this issue open as a reminder to add some FAQ / docs section about this.

**Comment by dieeasy** [comment]
Thanks for the quick reply!
How much free space are we talking about? /tmp might not be very big (<1GB) on many some systems I work on so it could be a good idea to point TEMP to somewhere bigger anyway.

**Comment by ThomasWaldmann** [comment]
Depends on repo size (archive and chunk count), but can be multiple GBs.
Same thing applies for ~/.cache/borg btw.

**Comment by dieeasy** [comment]
Currently my target is three main archives with roughly the following data sets:
* 6423 MB total in 112730 files with 58 KB avg size
* 431776 MB total in 433 files with 1021105 KB avg size
* 1679565 MB total in 3952547 files with 435 KB avg size

There are some huge files and many small files in the mix so probably a hard set to choose sizes for.
At the moment I am using ```--chunker-params=19,23,21,4095``` as suggested for large datasets (bumping min to 512k and avg to 2m, if I got it).

**Comment by ThomasWaldmann** [comment]
There's a formula in the "internals" docs to compute the index sizes.
For .cache it is about archive_count * chunk index size.
For temp it is a bit hard to estimate as that is a dynamically built cache.

**Comment by dieeasy** [comment]
I can confirm setting TEMP to some path mounted exec yields a working borg.

**Comment by dieeasy** [comment]
Just an idea.

Assuming the binary (borg-linux64 in this example) can be found in $PATH (e.g. /usr/local/bin), one possible solution is to install a helper script called "borg" like:
```
#!/bin/sh
echo TEMP="`dirname $0`" borg-linux64 $@
```
so you can put that in a writable executable location with enough space available and TEMP will be set to the same path (where the helper script resides, not necessarily the same as the borg binary).

I should be "standard" enough to suggest it to users in the same documentation mentioning this issue.

**Comment by ThomasWaldmann** [comment]
@dieeasy usually binary locations are not writable (for security reasons, except for root), so that doesn't help much.

**Comment by dieeasy** [comment]
@ThomasWaldmann I may be overlooking something but the borg binary need not be in a writable location, the helper script does ($0 refers to the path the helper has been called with), and it may or may not be in $PATH, depending on how the user wants to call it (even ./borg from a backup user's home dir).

An alternate solution for shell scripts might be to define a function and call that instead of the binary directly, e.g.:
```
borg()
{
    TEMP="`dirname $0`" borg-linux64 $@
}

borg help
```
Moreover, one can always use something else than ``` `dirname $0` ```, like /var/tmp, /opt/borg/tmp or whatever.

**Comment by ThomasWaldmann** [comment]
@dieeasy ah, right, I was assuming all is in same location.
