### ISSUE TITLE
What Microsoft did with 'hotspot' chunks

### ISSUE THREAD

**Issue by jumper444** [borgbackup/borg#50]
As Attic / Borg grow and look at new ideas I wanted to mention something Microsoft did with their take on deduplication:
https://technet.microsoft.com/en-us/library/hh831434.aspx

Essentially they made the unique step (from what I've seen) of deciding that any data chunk which is referenced over 100 times (by being found in multiple files or multiple versions of files) will be stored more than once in the filesystem/repository/whatever.

I've seen other backup programs (bup?) which, instead, will use PAR as an add-on command/utility to accomplish something similar...meaning that if you have a deduping backup you need to made sure (and DARN sure when it's a 'hotspot') that you don't lose any bits at anytime in history.

Common responses are "use a file system like XFS" to maintain integrity of the repository, etc.  Choice of OS or device or system is often restricted or not open as a solution.  I also think microsoft often manages (polar criticisms aside) to at times take a new look at something and find an improvement or new angle.

So...It might be interesting to consider taking 'hotspot' chunks whose loss would clearly destroy a large amount of backed up data and keep multiple records of them.  "attic check" would check these.  Perhaps a check would also happen during extraction.

**Comment by jumper444** [comment]
I'd point out that mathmatically the count for referenced chunks would be an exponential type curve. Most data chunks have just a few references, but a few out on the tail end of the curve having hundreds or thousands.  If such a redundancy feature were implemented it could either be a) as a fixed value like "100+ references" is duplicated; b) the reference count threshold could be a variable for a new repository; c) instead a user could specify "10%" or such which would mean increase the repository size by 10% by duplicating the highest count 'hotspot' chunks (working down the exponential curve distribution) until the repository is now 10% (or whatever) larger.

**Comment by ThomasWaldmann** [comment]
borg (and also attic) does not cover providing redundancy and it is also not planned for near future, you have to solve it in some other way (like RAID disks or special filesystem) if you need that.

using the chunk refcount as an indicator for importance might do something good or not. it could be just a bunch of zeros that occurs very often - that doesn't make these zeros more important than other chunks, they are just more frequently occurring. also it does not say that the files that have these chunks are more important than others.

so, I am closing this for now as out-of-scope.
