### ISSUE TITLE
add rendering docs to release todo

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5000]
avoids markup issues, e.g. in changelog / bug advisories.

**Comment by milkey-mouse** [comment]
Happy 5000th issue!

**Comment by milkey-mouse** [comment]
On a more serious note, isn't this already in the release checklist?

https://github.com/borgbackup/borg/blame/master/docs/development.rst#L322-L323

**Comment by ThomasWaldmann** [comment]
that's not what i meant.

what i mean is rendering changes.rst to html (sphinx: make html) and looking at it, to avoid markup errors like in 1.1.11 release (in the security advisory part at the top of the file).

**Comment by fantasya-pbem** [comment]
So you want to add something like "render changes.rst to html and check for markup errors" here: https://borgbackup.readthedocs.io/en/stable/development.html#creating-a-new-release
Did I understand correctly? Or do you want "render documentation with sphinx and check", which would be quite a lot to do.
