### ISSUE TITLE
Idea: use borg for storing "btrfs send" FS dump files

### ISSUE THREAD

**Issue by DrupaListo-com** [borgbackup/borg#501]
@all, Is it a good idea to use borg to store/dedup the "btrfs send" dumps ?

The borg-Btrfs workflow would be:
1. run btrfs snapshot to make the latest snapshot
2. dump the btrfs send output to a file thus capturing all changed FS blocks between current and last snapshot
3. store that file into the borg repo

Usual borg way:
- relying on the borg cache and full FS read everytime, resulting in a backup time of about 10-20-30 mins for a normal root FS backup

Pros of the borg-btrfs way:
- snapshotting feature out of the box thanks to btrfs thus consistent backup on the FS level
- the snapshot + send should be way faster than the 10-30 mins borg needs to do a full FS scan

Possible cons:
- not clear how efficient would a borg dedup be on a btrfs send dump file
- each backup is not a full FS plain files/dirs copy but a 'btrfs send' dump, thus to restore some point in time you need to go all the way to point 0 , restore all dumps in order and do a "btrfs receive" on some new FS you are building... maybe there is a better way for this?

Anyone with expirience with backup schemes using btrfs send/receive / ideas?

**Comment by RonnyPfannschmidt** [comment]
that sounds completely out of scope

**Comment by rumpelsepp** [comment]
You can solve the "consistent backup on the FS level" thing by a simple shell script wrapper, which first creates a BTRFS/ZFS snapshot, second backups that snapshot with borg and last but not least cleans that crap up.

I have sth like this in mind:

```bash
#!/usr/bin/env bash

BORG_REPO=
BORG_ARCHIVE=
BTRFS_SRC=
BTRFS_SNAPSHOT=/backup-$(date +%Y%m%d)

btrfs snapshot create $BTRFS_SRC $BTRFS_SNAPSHOT
borg create $BORG_REPO::$BORG_ARCHIVE $BTRFS_SNAPSHOT
btrfs snapshot delete $BTRFS_SNAPSHOT
```

**Comment by RonnyPfannschmidt** [comment]
but in the end it would create a situation where you no longer can use a single tool for restore,

imho borg should never handle that

**Comment by ThomasWaldmann** [comment]
@DrupaListo-com guess there are too many cons. You can't even extract a single file from that kind of backup without rebuilding the whole filesystem step by step (and having enough space somewhere to do that). Also, you can't list what files you have in a specific snapshot.

besides that, how one does snapshotting (with btrfs, with lvm, with whatever) is outside the scope of borgbackup, so I'm closing this.

BTW, if you either use the binary (includes python 3.5.1) or your own installation of python 3.5.x, the fs scan should be quite fast (faster than with <=3.4.x) - it just does a directory traversal and nothing more if the files were not touched (it just compares against the "files" cache).
