### ISSUE TITLE
freebsd64 vagrant machine broken on master

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5019]
```
    freebsd64: Message from python27-2.7.17_1:
    freebsd64: 
    freebsd64: --
    freebsd64: ===>   NOTICE:
    freebsd64: 
    freebsd64: This port is deprecated; you may wish to reconsider installing it:
    freebsd64: 
    freebsd64: EOLed upstream.
    freebsd64: 
    freebsd64: It is scheduled to be removed on or after 2020-12-31.
==> freebsd64: Running provisioner: build env (shell)...
    freebsd64: Running: inline script
    freebsd64: /tmp/vagrant-shell: virtualenv: not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by Gu1nness** [comment]
I can take this one as well, but I guess you need to send me the box file as well ?

**Comment by ThomasWaldmann** [comment]
@Gu1nness sure, let's meet on irc?

**Comment by Gu1nness** [comment]
Ok, so it seems that py36 was partially dropped on FreeBSD (see https://www.freshports.org/devel/py3-virtualenv/ )
> No installation instructions: this port has been deleted.
> The package name of this deleted port was:
> PKGNAME: py36-virtualenv

I think the easiest way is to update python to python3.7 for FreeBSD ?

**Comment by Gu1nness** [comment]
There is another problem which has appeared recently with pyinstaller and setuptools : https://github.com/pypa/setuptools/issues/1963 .
This has been fixed in recent versions of pyinstaller, or by adding a cli argument to pyinstaller to remove some warning.
What do you think ?

**Comment by ThomasWaldmann** [comment]
If a more recent pyinstaller helps, see #4963.

**Comment by Gu1nness** [comment]
We need to wait for 3.7 to have it fixed.
Meanwhile, the workaround seems to be to add `--hidden-import="pkg_resources.py2_warn"` to the pyinstaller command.
We can keep this until the next release of PyInstaller maybe?

**Comment by ThomasWaldmann** [comment]
waiting for pyinstaller can take rather long... - so yes, pin setuptools as needed.

**Comment by Gu1nness** [comment]
Ok.
Then I'll fix the box and pin setuptools for a while.

**Comment by ThomasWaldmann** [comment]
ok, the new freebsd121-64.box works!

**Comment by ThomasWaldmann** [comment]
BTW, pyinstaller 4.0 was released a while ago.
