### ISSUE TITLE
openindiana vagrant VM broken on master

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5020]
```
    openindiana64: ===== 1133 passed, 247 skipped, 2 xfailed, 4 warnings in 375.55s (0:06:15) =====
    openindiana64: Coverage.py warning: No data was collected. (no-data-collected)
    openindiana64: py36 create: /export/home/vagrant/borg/borg/.tox/py36
    openindiana64: SKIPPED: InterpreterNotFound: python3.6
    openindiana64: py37 create: /export/home/vagrant/borg/borg/.tox/py37
    openindiana64: SKIPPED: InterpreterNotFound: python3.7
    openindiana64: py38 create: /export/home/vagrant/borg/borg/.tox/py38
    openindiana64: SKIPPED: InterpreterNotFound: python3.8
    openindiana64: flake8 create: /export/home/vagrant/borg/borg/.tox/flake8
    openindiana64: flake8 installdeps: flake8, pkgconfig
    openindiana64: flake8 inst: /export/home/vagrant/borg/borg/.tox/.tmp/package/1/borgbackup-1.2.0a8.dev108+g425f0919.d20200310.zip
    openindiana64: ERROR: invocation failed (exit code 1), logfile: /export/home/vagrant/borg/borg/.tox/flake8/log/flake8-2.log
    openindiana64: ================================== log start ===================================
    openindiana64: Processing ./.tox/.tmp/package/1/borgbackup-1.2.0a8.dev108+g425f0919.d20200310.zip
    openindiana64:     ERROR: Command errored out with exit status 1:
    openindiana64:      command: /export/home/vagrant/borg/borg/.tox/flake8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dsyo6kfe/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dsyo6kfe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-dsyo6kfe/pip-egg-info
    openindiana64:          cwd: /tmp/pip-req-build-dsyo6kfe/
    openindiana64:     Complete output (5 lines):
    openindiana64:     Traceback (most recent call last):
    openindiana64:       File "<string>", line 1, in <module>
    openindiana64:       File "/tmp/pip-req-build-dsyo6kfe/setup.py", line 131, in <module>
    openindiana64:         raise ImportError('The GIT version of Borg needs Cython. Install Cython or use a released version.')
    openindiana64:     ImportError: The GIT version of Borg needs Cython. Install Cython or use a released version.
    openindiana64:     ----------------------------------------
    openindiana64: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    openindiana64: =================================== log end ====================================
    openindiana64: ___________________________________ summary ____________________________________
    openindiana64:   py35: commands succeeded
    openindiana64: SKIPPED:  py36: InterpreterNotFound: python3.6
    openindiana64: SKIPPED:  py37: InterpreterNotFound: python3.7
    openindiana64: SKIPPED:  py38: InterpreterNotFound: python3.8
    openindiana64: ERROR:   flake8: InvocationError for command /export/home/vagrant/borg/borg/.tox/flake8/bin/python -m pip install --exists-action w .tox/.tmp/package/1/borgbackup-1.2.0a8.dev108+g425f0919.d20200310.zip (exited with code 1)
```

**Comment by Gu1nness** [comment]
Okay, I'll take this one.
FIrst of all, the VagrantFile seems to be broken for the creation of the VM : the vagrant box is called [openindiana/hipster](https://app.vagrantup.com/openindiana/boxes/hipster) and not `openindiana`.
Then, just the time for me to setup the vagrant VM (updates, install, all that jazz).
And then I guess it's mostly installing cython once and for all.
I'll see what is happening

**Comment by Gu1nness** [comment]
I have seen what I guess is a typo : https://github.com/borgbackup/borg/blob/master/Vagrantfile#L117 .
It should be `python3` instead of `pyton3` no ?

**Comment by Gu1nness** [comment]
Gosh the image on [vagrant](https://app.vagrantup.com/openindiana/boxes/hipster/versions/20181023) is too old to install packages, so I guess I'm stuck.
Maybe we should ask for a new version of openindiana on the vagrant repo ?

**Comment by Gu1nness** [comment]
There is an open issue at openindiana here : https://www.illumos.org/issues/12398
So I guess we'll wait until they update the box? Meanwhile I'm testing with the box given as an example in the issue.

**Comment by Gu1nness** [comment]
(Now, I have all working as it should with the box from Toasterson and a few fixes (clang updated to 8.0 for example and cython in the list of packages to install the first time the VM is set and the symbolic link required).

**Comment by ThomasWaldmann** [comment]
Hmm, looks like the email replies i sent to this ticket here didn't make it to here...

So:

sure, that's a typo, good catch!

I started with the official vagrant box, but it got broken somehow.
Then installed an own, local box, this is what I used recently.

**Comment by Gu1nness** [comment]
So do you want to go on with your own local box ?
If so, can we find a way so I can have it to run my tests ?

**Comment by ThomasWaldmann** [comment]
Can you install magic wormhole to transfer it?

**Comment by Gu1nness** [comment]
I have the fiber at home.
I have installed magic wormhole, even though I have never used it.
Maybe a query on IRC would be better to do this ?

**Comment by ThomasWaldmann** [comment]
yes, irc. currently i am busy otherwise, but grab me on #borgbackup later.

**Comment by ThomasWaldmann** [comment]
ok, i am ready now, had a bit of time.

**Comment by Gu1nness** [comment]
I have narrowed down the problem.
sys.path is not conserved when launching tox.
For example on the VM : 
```
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-sunos5', '/usr/lib/python3.5/lib-dynload', '/export/home/vagrant/borg/borg/.tox/flake8/lib/python3.5/site-packages']
```
And on my laptop (debian sid):
```
['/home/neha/src/borg/borg', '/home/neha/src/borg/borg/venv-3.8/lib/python38.zip', '/home/neha/src/borg/borg/venv-3.8/lib/python3.8', '/home/neha/src/borg/borg/venv-3.8/lib/python3.8/lib-dynload', '/home/neha/.pyenv/versions/3.8.0/lib/python3.8', '/home/neha/src/borg/borg/venv-3.8/lib/python3.8/site-packages']
```

Now I need to find how to read tox documentation to find how to fix this.

**Comment by Gu1nness** [comment]
The other solution would obviously be to add Cython to the deps for flake8 but I don't find it satisfying.

**Comment by Gu1nness** [comment]
It seems that it works more by accident than anything on our systems, since it finds Cython in the path that is given to tox.
So maybe adding Cython to the deps for flake8 would be the solution, not extremely costly.
@ThomasWaldmann What do you think ?

**Comment by ThomasWaldmann** [comment]
Another approach would be to drop flake8 testing from the vagrant VMs.

We do it all the time on travis-ci, so could skip it on the vagrant VMs, which are primarily for platform testing.

**Comment by Gu1nness** [comment]
That's a good idea indeed.

**Comment by ThomasWaldmann** [comment]
tox --skip-missing-interpreters -e py35,py36,py37,py38

**Comment by Gu1nness** [comment]
Sorry I thought I had committed and pushed everything already...
