### ISSUE TITLE
QUESTION about prune and S3 Intelligent Storage tiers

### ISSUE THREAD

**Issue by lorenzoridolfi** [borgbackup/borg#5022]
Hi,
Today I use borgbackup with backblaze and I'm planning to move to AWS S3. Recently I had to recover my files from backblaze and wasn't a good experience. 
AWS S3 offers an interesting option of storage tiers where you pay half of the price for files you don't access often. You have the option to attribute a specific tier to each file and this process can be automatic based on the file age. For instance, you can move a file to the "less frequent access" if the file is not changed for more than X days. It's important to notice that you'll only have the discount if the file really doesn't change and you also pay for changing the tier of the file. So, it's important to setup borg to prune the files in a compatible way. 
My original plan is to keep the files in the normal storage tier for 60 days and after that, migrate the files to the "less frequent access" tier. Normally I don't change old files, so the pruning of files older than 60 days won't make too much difference in storage space.
I keep a local copy of all borg files and I use rclone to sync the files to the remote storage.
My questions are:
- If I configure the borg prune to only prune files up to 60 days, the old files won't be touched? 
- Besides pruning, does borg modifies the old files for any other reason?

**Comment by ThomasWaldmann** [comment]
Maybe using a provider who actually supports borg (see our homepage) would be the best solution.

borg never modifies old segment files "in place". but, when they contain holes, it may compact the data by reading them and writing the still needed objects to new segment files.

the only way to completely avoid that is to run the repo in "append-only" mode, which means it will grow forever.
