### ISSUE TITLE
Python 3.8 problem: borgbackup-1.1.10 requires python(abi) = 3.7, but this requirement cannot be provided

### ISSUE THREAD

**Issue by quicktrick** [borgbackup/borg#5028]
openSUSE Tumbleweed

I'm trying to upgrade the system and all the installed packages. It's going to upgrade `python3-3.7.3` to  `python3-3.8.2` but there are problems with `borgbackup-1.1.10`:

```
Problem: borgbackup-1.1.10-2.2.x86_64 requires python(abi) = 3.7, but this requirement cannot be provided
```

Is it going to be solved in the near future?

Edit:
Oh, I'm sorry, I haven't seen Release 1.1.11.  It isn't in openSUSE repository yet.  Does it support Python 3.8?

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/github/borgbackup/borg/builds/659677993

So it looks like this is a problem the SuSE package maintainer has to solve.

**Comment by ThomasWaldmann** [comment]
If you need a working borg before that is solved, try the linux64 binary package from our github releases page.
