### ISSUE TITLE
BORG_RSH and --rsh is not used for borg list

### ISSUE THREAD

**Issue by mattelacchiato** [borgbackup/borg#5031]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
`borg 1.1.9`
#### Operating system (distribution) and version.
Raspbian Buster (10.3)
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```BORG_RSH="sudo -u <user> ssh" sudo borg list ssh://<repository>::<archive>```

## Describe the problem you're observing.
I've created the archive with 
```BORG_RSH="sudo -u <user> ssh" borg create ssh://<repository>::<archive>```

When I run the list command, I receive this error message:
```Connection closed by remote host. Is borg working on the server?```

Even adding `-v` to the ssh command, doesn't print any verbose output. Also, switching form environment varialbe `BORG_RSH` to command argument `--rsh` does not work.

This leads me to the conclusion, that `BORG_RSH` and `--rsh` is not used in `borg list`.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes, with the steps described above.

**Comment by fantasya-pbem** [comment]
After setting BORG_RSH (as your login user) you run sudo, which runs the borg command as root. So your BORG_RSH setting is not used. Can you log in as root and try it again?

**Comment by mattelacchiato** [comment]
Like I said: even using `--rsh` option does not work
And: It worked when I've created the archive.

**Comment by fantasya-pbem** [comment]
You wrote you created it with ``BORG_RSH="sudo -u <user> ssh" borg create ssh://<repository>::<archive>``. This is not the same as BORG_RSH=... **sudo** borg list ... As I tried to explain: The BORG_RSH variable is set in your user's environment. But the ``sudo borg`` command is run as root, where no BORG_RSH is set in the environment (because you set it as non-root user).

**Comment by ThomasWaldmann** [comment]
Guess this is an environment issue, as @fantasya-pbem pointed out.
