### ISSUE TITLE
msgpack from PPA breaks borg 1.1.11 on Ubuntu 18.04

### ISSUE THREAD

**Issue by rusitschka** [borgbackup/borg#5037]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
BUG

#### Your borg version (borg -V).
1.1.11

#### Operating system (distribution) and version.
Ubuntu 18.04

## Describe the problem you're observing.
Using the Ubuntu PPA 18.04 the msgpack version in the PPA 0.6.2-1~ubuntu18.04.1~ppa1 gives the following error:

```
Remote: You do not have a supported msgpack[-python] version installed. Terminating.
Remote: This should never happen as specific, supported versions are required by our setup.py.
Remote: Do not contact borgbackup support about this.
Connection closed by remote host. Is borg working on the server?
```

Downgrading to msgpack 0.5.6-1 from the official Ubuntu repo fixes this.

**Comment by infectormp** [comment]
This is normal behavior. msgpack 0.6.2 is not supported by borg.

**Comment by rusitschka** [comment]
The why is it in the PPA? https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg ^^^

BTW, since a while, we have a bundled known-good msgpack inside borg.

**Comment by haslinger** [comment]
A few hours ago, a new borgbackup 1.1.11-5 was made available, that resolves the issue for.
So try to update and rerun borg.

**Comment by rusitschka** [comment]
I can confirm that it's working again. Thanks!

**Comment by LocutusOfBorg** [comment]
yep, fixed and updated!
