### ISSUE TITLE
Help me understand the output of --progress and --stats

### ISSUE THREAD

**Issue by jmdesprez** [borgbackup/borg#5038]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

Hello, 
I've some difficulties to understand what the `--progress` option output.

From the documentation : The --progress option shows (from left to right) Original, Compressed and Deduplicated (O, C and D, respectively), then the Number of files (N) processed so far, followed by the currently processed path.

But the documentation also indicate : Compression is applied after deduplication ([Internals documentations about compression](https://borgbackup.readthedocs.io/en/stable/internals/data-structures.html#compression)).

Here is an example of what I see during a `borg create --progress ....` : `28.53 GB O 20.76 GB C 7.87 GB D`
As the compression is applied after the deduplication, how the Compressed size can be larger than the Deduplicated size?

Same question for the `--stats` as the summary display something like this : 
```
                       Original size      Compressed size    Deduplicated size
This archive:               33.00 GB             23.82 GB              9.21 GB
```
The compressed size is also larger than the deduplicated size.

This sentence from the documentation : "“This Archive” deduplicated size there is most interesting as that is how much your repository will grow" make me think that "Deduplicated size" is the size of deduplicated chunk *after* compression, is it correct?

Can someone help me understand these outputs?

Thanks :)

**Comment by infectormp** [comment]
Original size = Compressed size + Deduplicated size

**Comment by infectormp** [comment]
Original size = size of data that was backup by borg. i.e. size of source directory
Compressed size = size of backup after compression.
Deduplicated size = size of backup after deduplication. This is size of your repository on a file system.

**Comment by jmdesprez** [comment]
Hello,

Thanks to your comment and some test I've done using different `--compression` I now understand more clearly :)

Thanks a lot !

**Comment by ThomasWaldmann** [comment]
The `C)ompressed` value is a somehow synthetic value.

Borg first deduplicates and only compresses if the data is not duplicate.

So what it shows after `C` is the size ALL input data in the backup set would have IF it were just compressed, but not deduplicated.
