### ISSUE TITLE
How to show the progress during borg prune

### ISSUE THREAD

**Issue by finefoot** [borgbackup/borg#5040]
`borg prune` might take some time and as far as I know, there is no status indicator to show that borg is still working. It would be nice to have `--progress` show some information during processing. Couldn't find a previous issue on this, hope I didn't overlook something.

**Comment by ThomasWaldmann** [comment]
Likely a lot of the time borg 1.1.x needs for prune is due to compact_segments being called after archive deletion. This will change in 1.2 / master branch.

**Comment by finefoot** [comment]
So you're saying there won't be a need for `--progress` with `borg prune` in the future anyway?

**Comment by ThomasWaldmann** [comment]
How much time the first phase of prune (multi-delete) takes likely depends on machine speed, archive size, chunk size and how many archives prune will delete.

The second phase (in 1.1.x) is compact_segments and way more I/O intensive on the repo side.

**Comment by ThomasWaldmann** [comment]
Note that since borg 1.2:
- borg prune only does the multi-delete
- borg compact is needed to do the compact_segments

**Comment by ThomasWaldmann** [comment]
Looks like  borg 1.2.x now has `borg prune --progress`, so one at least gets a progress indication for the multi-delete phase.
