### ISSUE TITLE
Prune question :(

### ISSUE THREAD

**Issue by wesmannmsu** [borgbackup/borg#5047]
Sorry, I know asking questions sucks. BUT I have read all that I can find and I am still unclear. if I use this your example at:

https://borgbackup.readthedocs.io/en/stable/usage/prune.html

And my very first backup was 1 Jan 2015 of 6TB and nothing was ever deleted, only added to.  does the June 30m repository contain all of the information that was in the 1 Jan 2015 backup? and all the data that was added up to June 30?

I assume this is yes since, on June 30th, all the files in the FS on that date still existed? Is everything that still existed on June 30th all put into that same monthly? even though, it's only been incrementally adding files for the last 6 months since the first full backup?

However, if I accidentally deleted 1TB of data on 1 March, all that data (1TB) is now not in the 30th of June repository?

**Comment by wesmannmsu** [comment]
Again, sorry for asking, thanks for all the hard work! going to run over and donate ASAP!

**Comment by infectormp** [comment]
In borg context we use terminology: repository and archive. I assume is answer to your question is here https://borgbackup.readthedocs.io/en/stable/quickstart.html#archives-and-repositories. 

If we talk about data deletions from the drive then your repository still contain deleted data (in archive from 1 Jan 2015). `borg prune` deletes archives from repository according to your prune policy and it doesn't delete data by size.

**Comment by wesmannmsu** [comment]
Thank you for the response, I did read that page as well, I just re-read it just to make sure I didn't miss something. Its this line on that page that is confusing me. 

_**After the backup this script also uses the borg prune subcommand to keep only a certain number of old archives and deletes the others in order to preserve disk space.**_

I feel like its saying, if my initial archive was created on 1 Jan 2015 (using your prune page example), by the time I reach the end of the year. That first archive has been pruned, along with all the data associated with it. 

However, it could also mean, that since the "30th of June (monthly)", it is referencing that data still, it's kept. is that what's happening?

for example, if I had two files that I back up in the very first Archive 1 Jan 2015.. 
abc.txt.  and cde.txt, then deleted the cde.txt the very next day. 

using **borg prune --keep-daily 14 --keep-monthly 6**

At the end of the year, abc.txt will still be in all of the monthly repositories? but cde.txt would have been lost forever sometime around the 15th daily? 

Again, super sorry for my confusion.

**Comment by ThomasWaldmann** [comment]
borg archives contain file metadata (inside the archive stream) and references to file content data chunks.

The file content chunks are stored as outside the archive stream, so that multiple archives can reference to the same content chunks.

Of course, content chunks are only deleted if no reference to them exists any more (== if you have deleted all archives referencing them).

So, logically an archive contains all files that you have backed up at that archive's creation time and you do not need to care about deduplication, borg handles that automatically and you do not need to consider it when deleting archives.

This is different from tools that do full+incremental backups, borg always does full backups.

**Comment by ThomasWaldmann** [comment]
I guess we can close this now.

If there is some specific part of the docs that is wrong or should be improved, please point to it and suggest an improvement.

**Comment by wesmannmsu** [comment]
Thank you for your explanation. it does explain the prune function perfectly. I didn't see that info on the prune page, which lead to my confusion. I may have not understood it if it was there.  I might suggest adding this bit to the prune page, just to help clarify. 

**borg archives contain file metadata (inside the archive stream) and references to file content data chunks.

The file content chunks are stored outside the archive stream, so that multiple archives can reference to the same content chunks.

Of course, content chunks are only deleted if no reference to them exists anymore (== if you have deleted all archives referencing them).**
