### ISSUE TITLE
FUSE mount is slow for linear reads of big files

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5067]
As discovered and fixed by @lexa-a in #5032, linearly reading a big file from a borg fuse mount is slower than it needs to be.

From the PR comment:

This patch is a quick fix for an inefficient seek algorithm used in read() function:
- On each read call chunk list for given file is regenerated.
- Finding needed chunk takes a lot of time for large offsets.

For 64 GB files read speed drops to 16 MB/s, for 128 GB - to 8 MB/s, and so on.

After applying this patch read speed becomes 270 MB/s, and does not depend on read position inside file.

**Comment by ThomasWaldmann** [comment]
Note: "big" relates to the amount of chunks of the file.

If you use a smaller target chunk size than usual, the issue will also apply to smaller files.

**Comment by ThomasWaldmann** [comment]
Update from #5032:
```
Thanks for fix, now it works well:

Deduplicated size=31.62 GB, Unique chunks=367413

(48 GB) copied, 131.732 s, 367 MB/s  (small chunk size)

For standard chunk size speed is 380 MB/s.

borg mount vs extract md5sum does also match.
```

**Comment by enkore** [comment]
Went quite a long way in terms of throughput considering Borg 1.0 bottlenecks at a few MB/s on decrypting the same chunk over and over for typical read sizes. Good work! :)
