### ISSUE TITLE
Backup after renaming source directory

### ISSUE THREAD

**Issue by srett** [borgbackup/borg#5071]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Docs, google, issues

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

1.1.11, Linux

I'm backing up about 2TB of data over a slow connection, but that's fine since the data is only growing slowly. Now I had to reorganize the directory structure of the data that gets backed up. On the next call to "borg create ...", it seems that borg is transferring all the files to the remote server again (progress slow according to --verbose, connection is saturated).
So, is de-duplication generally only happening client-side if the path matches something already in the repo? Is there anything I can do to force borg to look for matching chunks in the repo by hash, before sending actual file contents? Am I just doing something wrong here? I basically just changed my borg-call from ```borg --verbose create "::$name" /mnt/old/location``` to ```borg --verbose create "::$name" /mnt/new/location``` (repo/passphrase via environemt vars).

I tried finding anything about this online, but you only get results for questions related to moving/renaming the repository, not the source data... It would be really great if I could speed this up, estimated duration for the full 2TB is almost 4 days... :-/

**Comment by ThomasWaldmann** [comment]
If you rename directories in the backup input files set, the files cache will not match the files that have differences in their absolute path. Thus, there will be no quick processing of unchanged files.

So, chunking at the clientside is expected (will read, chunk, hash these files completely).

But if the local lookup whether we already have the chunk in the repo is positive, the chunk won't be transmitted to the repo.

`create --list` might give some more details.

**Comment by srett** [comment]
OK thanks; so it should work, but chew through all the files on the client again. Currently I solved it with a bind-mount from "old" to "new", so the absolute path looks the same again. All the files get marked as modified (because different FS/inode?) in the verbose output, but not transferred again. That seems to match the read/chunk/hash pattern. After that run, I will try without the bind-mount again. Hopefully that works and I can chalk it up to having made a dumb mistake because tired/overworked/going nuts staying inside.

**Comment by ThomasWaldmann** [comment]
Absolute path, inode number, file size and ctime must match for a files cache hit.

There are some ways to use `--files-cache`, but the default of it is the safest one.

**Comment by srett** [comment]
I played around with it some more and it seems to be working as you said now. So no idea what I was observing initially really.
