### ISSUE TITLE
Standalone build on Centos

### ISSUE THREAD

**Issue by davobo** [borgbackup/borg#5077]
Hi

trying to build standalone borg binary on Centos 7, but getting Cython.Plex module missing.

All required libs and python dependencies are installed. I'm able to build and install borg from source code but standalone binary just won't cooperate. Currently suspecting on some Cython path misconfiguration but "python setup.py install" successfully installs it.

Using:
    python 3.6.8
    borg source code 1.1.11
    Cython 0.29.16
    kernel: 3.10.0-693.el7.x86_64

Error:
> File "setup.py", line 109, in <module>
  File "/home/test/Downloads/python3-virtualenv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Cython/Compiler/Main.py", line 28, in <module>
  File "Cython/Compiler/Scanning.py", line 1, in init Cython.Compiler.Scanning
ModuleNotFoundError: No module named 'Cython.Plex'

Similar to 
[pip3 install from github on CentOS 6 issues #132](https://github.com/borgbackup/borg/issues/132) #

**Comment by ThomasWaldmann** [comment]
Does the borg-linux64 binary we offer not work for you?

**Comment by davobo** [comment]
I'm actually trying to build the binary for VMware ESXi, since provided borg-linux64 binary doesn't work. When I try to run it i get following error:

> Failed to write all bytes for _codecs_cn.so

**Comment by ThomasWaldmann** [comment]
Well, maybe have a look at the Vagrantfile in the repo:

https://github.com/borgbackup/borg/blob/1.1-maint/Vagrantfile#L296

**Comment by davobo** [comment]
Thanks for the info. 
libpython3.5m.so.rh-python35-1.0 librarly nedded linkade under different name and one import error popped up ("ImportError: No module named 'win32com'"), but it didn't affect the build. Pyinstaller successfully build the binary but unfortunately same issue persists when running it. 

> File "setup.py", line 109, in <module>
  File "/home/root/borg-env/lib64/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "Cython/Compiler/Main.py", line 28, in <module>
  File "/home/root/borg-env/lib64/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
  File "Cython/Compiler/Scanning.py", line 1, in init Cython.Compiler.Scanning
ImportError: No module named 'Cython.Plex'

Environment setup:

>python==3.5.1
 apipkg==1.5
appdirs==1.4.3
attrs==19.3.0
bleach==3.1.4
certifi==2019.11.28
chardet==3.0.4
coverage==5.0.4
Cython==0.29.16
distlib==0.3.0
docutils==0.16
execnet==1.7.1
filelock==3.0.12
idna==2.9
importlib-metadata==1.6.0
importlib-resources==1.4.0
more-itertools==8.2.0
packaging==20.3
pathlib2==2.3.5
pkginfo==1.5.0.1
pluggy==0.13.1
py==1.8.1
py-cpuinfo==5.0.0
Pygments==2.6.1
PyInstaller==3.2.1
pyparsing==2.4.6
pytest==5.4.1
pytest-benchmark==3.2.3
pytest-cov==2.8.1
pytest-forked==1.1.3
pytest-xdist==1.31.0
readme-renderer==25.0
requests==2.23.0
requests-toolbelt==0.9.1
setuptools-scm==3.5.0
six==1.14.0
toml==0.10.0
tox==3.14.6
tqdm==4.45.0
twine==1.15.0
urllib3==1.25.8
virtualenv==20.0.16
wcwidth==0.1.9
webencodings==0.5.1
zipp==1.2.0

**Comment by ThomasWaldmann** [comment]
The win32com message seems normal under linux, not harmful.

No idea about the Cython Plex issue. Maybe talk to the PyInstaller developers?

**Comment by davobo** [comment]
Ok. Will try there and will get back if I manage to resolve it

**Comment by ThomasWaldmann** [comment]
If somebody got this working, it maybe would be a good idea to change our `Vagrantfile` to do that
