### ISSUE TITLE
FR - support quoted BORG_PASSPHRASE

### ISSUE THREAD

**Issue by yatesco** [borgbackup/borg#508]
Hi,

I have a passphrase which includes characters interpreted by the shell (e.g. '&'). If I issue an `export BORG_PASSPHRASE=abc&def` then the shell does the wrong thing.

It would be great if I could put the value in single quotes to turn into a string, e.g. `BORG_PASSPHRASE='abc&def'` but this doesn't currently work.

Thanks!

**Comment by ThomasWaldmann** [comment]
```
$ export BORG_PASSPHRASE='abc&def'
$ echo $BORG_PASSPHRASE
abc&def
```

Looks like it should work without doing anything special except using single quotes.

**Comment by yatesco** [comment]
The actual passphrase I was using was much more complex, but I didn’t write it down. I may well have done something numptyish - it wasn’t defining the passphrase that was the problem it was the fact that it wasn’t picked up and I was prompted for the passphrase.

Let me close this then with a ‘doh, I wish I had written down the actual passphrase in question’.

close #508
