### ISSUE TITLE
Suggestion to add pip dependencies in the documentation and elsewhere

### ISSUE THREAD

**Issue by Wikinaut** [borgbackup/borg#5090]
On https://borgbackup.readthedocs.io/en/stable/installation.html#using-pip I suggest to add:

* pip install setuptools
* pip install cython

as these are essential for performing

* pip install borgbackup

then.

[moved from https://github.com/borgbackup/borgbackup.github.io/issues/54 to here]

**Comment by ThomasWaldmann** [comment]
if you use pip, you install a release version of borg which does not need Cython.

Why do you think these are needed?

**Comment by Wikinaut** [comment]
Thomas, I respectfully disagree. There came immediately an error which explains that a cython is needed - now I can't reproduce it, because my boxes are currently running backups. Please "believe" me!

**Comment by ThomasWaldmann** [comment]
Can't reproduce.

**Comment by Wikinaut** [comment]
try a fresh installation of 
1. OpenMediaVault 4.1.35-1 Arrakis
2. LinuxMint 19.3

Then try to install borgbackup via pip. I had the problem twice in the last few weeks.

**Comment by ThomasWaldmann** [comment]
I tried on a fresh debian installation and it worked (and I just did `pip3 install borgbackup` to install 1.1.11, after installing the required header files / libs as documented).

So if there is a problem, it is likely not in borg, but in the environment.

**Comment by Wikinaut** [comment]
Tho, I was wrong! I checked the ```history | grep cython``` and found that apparently python3-dev or something like that was misleading me: I saw after removing cython, I simply installed all headers...

**Comment by Wikinaut** [comment]
@ThomasWaldmann update!

What had to be added as dependencies (for the pip installation on LinuxMint 19.3) was:

* pip3 install **setuptools**
* pip3 install **wheel**

Then
* pip3 install borgbackup

![grafik](https://user-images.githubusercontent.com/1151915/79162712-0a76f000-7dde-11ea-8eba-6ef8118b6ab5.png)

**Comment by fantasya-pbem** [comment]
@ThomasWaldmann You added this to 1.1.12 milestone, does that mean there is already a commit adding something to the docs? If not - what needs to be added? The lines of WIkinaut's last comment? Just for LinuxMint / Ubuntu?

**Comment by ThomasWaldmann** [comment]
Well, as I said, I could not reproduce the issue.
But the screenshot shows that there can be an issue and I suspect it is some buggy or outdated setuptools or not installed wheel package.

I think, for the pip installation method, there could be something like:

```
pip install -U pip setuptools wheel  # might be required if your tools are outdated
```

**Comment by Wikinaut** [comment]
As I explained:
setuptool were missing, and wheel.
