### ISSUE TITLE
attrs: [Errno 1] Operation not permitted: '<FD 7>'

### ISSUE THREAD

**Issue by Peitemoukiemena** [borgbackup/borg#5092]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).
borg 1.1.9 on the server being backed up
borg 1.1.7 on the server with the remote repository

#### Operating system (distribution) and version.
centos 7 on the server being backed up
Linux synology on the server with the remote repository

#### Hardware / network configuration, and filesystems used.
ext4 on both

#### How much data is handled by borg?
16 GB original size

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg extract /path/to/repo::my-files home/USERNAME/src`

## Describe the problem you're observing.
I run the above command to extract some files from a certain path and I get the error
```
attrs: [Errno 1] Operation not permitted: '<FD 7>'
```
Even though I see the error when extracting, I check the file afterwards and it has been extracted and the size is normal. Then why do I see this error? Could it mean that the file is corrupted?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I run `borg create` on the centos server. The repository is remote on the synology. The backup run succesfully. Then when I am extracting on synology, I see the error.

#### Include any warning/errors/backtraces from the system logs
No logs on synology.

**Comment by ThomasWaldmann** [comment]
try to reproduce with a current borg version (to which you want to upgrade anyway, see changelog).

also try as root.

**Comment by ambis** [comment]
I got this too. Running 1.1.11 everywhere and backup to Borgbase.

Backup is created on a Centos 7 with SELinux set to enforcing.

I tested by running a borg docker image on my docker-for-mac (also 1.1.11) and against the same borgbase remote.

When I ran the same restore command on the Centos 7 host, no errors were given. File was always extracted OK, regardles of the env/error.

**Comment by ambis** [comment]
> "attrs" means that it happens when trying to set xattrs (or ACLs or selinux stuff). That needs to be supported by your filesystem to work.

Oh. Could it be possible to detect this in Borg code and maybe tell the user that some attrs couldn't be restored, and the usual culprit being that current fs not supporting some attrs.

It also threw me off for a while, I tought the extract command had errored, especially when it says Errno 1 and not warning. Error means non-recoverable usually.

**Comment by Peitemoukiemena** [comment]
True, I restored a backup and even though each and every file had this Error, the restored backup was complete.

**Comment by ThomasWaldmann** [comment]
a general thing to check/improve here: it refers to an FD number, does it also show the filename? if not, we should find some way to do that. this is especially an issue in master branch, where a lot of stuff happens based on the FD (and not the filename).

**Comment by Peitemoukiemena** [comment]
Indeed it shows the full path and filename before the `[Errno 1] Operation not permitted: '<FD num>'`

**Comment by ThomasWaldmann** [comment]
I just noted that the bigger problem related to this is that other xattrs and bsdflags got skipped by the bad exception handling.

**Comment by ThomasWaldmann** [comment]
@Peitemoukiemena @ambis can you check the patch in #5583, like:

- reproduce the issue without patch
- try patched code in same circumstances

**Comment by ThomasWaldmann** [comment]
now merged into 1.1-maint branch and tagged for forward porting to master.

**Comment by Peitemoukiemena** [comment]
> @Peitemoukiemena @ambis can you check the patch in #5583, like:
> 
> * reproduce the issue without patch
> * try patched code in same circumstances

Would I need to update Borg to the latest version to try patched code?

**Comment by ThomasWaldmann** [comment]
@Peitemoukiemena you need to use 1.1.15. if there are no packages from your favourite dist yet, you can either use the fat binary from github releases or install via pip or git (from source).

**Comment by mnpenner** [comment]
Thanks  for the pointers about the attrs not being supported. I found there's a few [options](https://borgbackup.readthedocs.io/en/stable/usage/extract.html) to simply ignore these.

I'm extracting my backup to Windows now like this:

```sh
borg extract --progress --noacls --noxattrs --nobsdflags ::Desktop-C-Drive-2021-04
```

No errors yet.
