### ISSUE TITLE
Regression in borg mount permissions

### ISSUE THREAD

**Issue by Timmmm** [borgbackup/borg#5093]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

1.1.11

#### Operating system (distribution) and version.

Ubuntu 16.04

#### Hardware / network configuration, and filesystems used.

x86_64... ?

#### How much data is handled by borg?

Couple of GB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

    borg mount backup.borg backup_mount

## Describe the problem you're observing.

Some of the directories in the mount have very strange owners and groups. If I `cd` into them I cannot `ls` - I get a permission denied error. If I mount the same backup with Borg 1.0.11 the owners/groups are still wrong, but I don't get an error with `ls`.

More details in [these comments](https://github.com/borgbackup/borg/issues/1017#issuecomment-611563604).

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. I create a backup on Mac with this command: 

```
borg create --progress --stats \
	--exclude "*/target" \
	--exclude "*/node_modules" \
	--exclude "*/.dart_tool" \
	timh@sw01:backup.borg::main-`date +%Y-%m-%d_%H%M` \
	~/workspace \
	~/bin/backup \
	~/.bash_profile
```

Then mount it on `sw01` using the above command. Then `cd workspace; ls`.

#### Include any warning/errors/backtraces from the system logs

None.

**Comment by ThomasWaldmann** [comment]
If you have different systems, a mismatch between UIDs and GIDs is expected, this is not a bug.

You can use root to get access nevertheless.

**Comment by Timmmm** [comment]
> this is not a bug.

Yes it is. It used to work fine, also the various options that claim to ignore permissions have no effect so there is literally no way to access the data with the current version of Borg. If that isn't a bug I don't know what is.

> You can use root to get access nevertheless.

No I can't. I can't remember the exact error but even root cannot `cd` into the mounted directory. Yes really.

**Comment by ThomasWaldmann** [comment]
Read this about allow_root and allow_other:

http://manpages.ubuntu.com/manpages/precise/man8/mount.fuse.8.html
