### ISSUE TITLE
borg create returns error 1 on success

### ISSUE THREAD

**Issue by UglyBob79** [borgbackup/borg#5095]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
1.1.7
#### Operating system (distribution) and version.
4.18.10-arch1-1-ARCH
#### Hardware / network configuration, and filesystems used.
Backing up from a Intel i3 ext4 over sshfs to another remote Synology NAS
#### How much data is handled by borg?
~2TB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create -v --debug --stats --compression lz4         \
        --list --filter=d                                \
    /mnt/backupbob/borg::'{hostname}-{now}'              \
        /usr/local/scripts                               \
        /etc                                             \
        /srv/git                                         \
        /srv/http                                        \
        /mnt/pictures                                    \
        /mnt/backup                                      \
        /home/mattias 

## Describe the problem you're observing.

I have a script that will break if any of the steps does not return OK(0) and it has been running fine for probably a year. But now (I think after an upgrade) I get notifications every backup that borg create has failed with error code 1. I have tried running it manually with debug and there is nothing weird in the output, but the command definitely returns error 1.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Right now I can reproduce it every time.

#### Include any warning/errors/backtraces from the system logs

End of my log with --debug option from borg create:
```
...
Cleaned up 0 uncommitted segment files (== everything after segment 14290).
Verified integrity of /mnt/backupbob/borg/hints.14290
check_free_space: required bytes 895636178, free bytes 1934456655872
security: saving state for 3ccb85e6a0d1bbcf04243e6f1091119e4f3cfec8c4abecab98a043310fdc1f24 to /root/.config/borg/security/3ccb85e6a0d1bbcf04243e6f1091119e4f3cfec8c4abecab98a043310fdc1f24
security: current location   /mnt/backupbob/borg
security: key type           5
security: manifest timestamp 2020-04-10T13:27:08.653133
------------------------------------------------------------------------------
Archive name: spongebob-2020-04-10T15:23:11
Archive fingerprint: c89756428515ed0e48f9c23cda637729260cb5920f0e6363a2dbf33c8e77a42b
Time (start): Fri, 2020-04-10 15:23:58
Time (end):   Fri, 2020-04-10 15:27:08
Duration: 3 minutes 9.71 seconds
Number of files: 91697
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               52.39 GB             46.35 GB            319.50 kB
All archives:               38.65 TB             36.42 TB              2.00 TB

                       Unique chunks         Total chunks
Chunk index:                 1061452             19762843
------------------------------------------------------------------------------
[root@spongebob backup]# echo $?
1
```

**Comment by UglyBob79** [comment]
Can also add that the archive seem to be created as well (i can see it if I list), so I'm not sure if this is a completely false error.

**Comment by ThomasWaldmann** [comment]
1 is warning, 2 is error, see the docs.

if you look into the output, you also should see the warning message.
maybe NOT using --debug, but rather --info or --warning helps here.

**Comment by UglyBob79** [comment]
Ah, you are right! After enabling --warning I see now one of my backup folders get a warning:
/mnt/pictures: [Errno 116] Stale file handle: '/mnt/pictures'

**Comment by UglyBob79** [comment]
Not a bug, it was a valid warning.
