### ISSUE TITLE
QUESTION: run Check on small chunks

### ISSUE THREAD

**Issue by kitwo** [borgbackup/borg#5104]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

1.1.9

#### Operating system (distribution) and version.

Raspbian Buster

#### Hardware / network configuration, and filesystems used.

Raspberry pi 4b 4GB

#### How much data is handled by borg?

2.7 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg check

borg check --repository-only

## Describe the problem you're observing.

Coming from using Restic, it had an option to "verify/check -dataset" which allowed a section of the repository to be verified/checked.

In my scenario, my repository is stored on a remote PC (another raspberry pi 3b, located in a different geographic location), and this pc is online from 6am > 8pm, and doing a check would require several days of continuous running to complete. 

As such, I'd like to know if there is a function in Borg to only check a selection of chunks. So that I can check say 10 chunks out of 52 each week.

I can see the option to check first N archives, but I don't see how useful this would be as my first full backup is 2.7 tb.

Is there anything that could be suggested to verify a batch of chunks rather than archives at a time, or does the check restart from the last point it stopped?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

N/A

**Comment by fantasya-pbem** [comment]
In Borg 1.2.0 (not released yet) we have ``borg check --max-duration``, see https://borgbackup.readthedocs.io/en/master/usage/check.html.

**Comment by kitwo** [comment]
Thank you, that could be a solution to this, how could that be used that I'm not checking the same section of my repository each time? 




I'm wondering if I'd use this to check the "first N" of my repository? 




Would you have a better suggestion?




Many thanks,




Kit




Get Outlook for Android







On Sat, Apr 11, 2020 at 5:38 PM +0100, "Thalian" <notifications@github.com> wrote:















In Borg 1.2.0 (not released yet) we have borg check --max-duration, see https://borgbackup.readthedocs.io/en/master/usage/check.html.

**Comment by ThomasWaldmann** [comment]
It remembers the position where it got to in the config file (when finishing) and starts from there at the next run.

**Comment by kitwo** [comment]
That'll do the trick then, any idea when it will released?




Get Outlook for Android







On Sat, Apr 11, 2020 at 6:40 PM +0100, "TW" <notifications@github.com> wrote:















It remembers the position where it got to in the config file (when finishing) and starts from there at the next run.

**Comment by ThomasWaldmann** [comment]
When it is ready. :)
