### ISSUE TITLE
readonly tests malfunctioning

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5111]
tried to locally run the tests like `tox -e py35` on my laptop and all the new readonly tests were failing.

i ran the tests as a regular user, not root:

```
chattr: Operation not permitted while setting flags on /tmp/tmp7obixgmm/repository
```

As root `chattr +i` works, but the tests should work as non-root also.

ext4 filesystem (also on /tmp).

**Comment by ThomasWaldmann** [comment]
Also the test run behaved rather strangely, hanging at the end.

**Comment by ThomasWaldmann** [comment]
@finefoot ^

**Comment by finefoot** [comment]
> but the tests should work as non-root also

I wasn't aware of that. I thought everything on Travis and Vagrant etc. runs as root. I'll take a look.

**Comment by finefoot** [comment]
I guess the problem is with `chattr` only (because that's the command that requires root privileges) and `chflags uchg` still works? (Assuming you run OS X tests locally, too?)

**Comment by ThomasWaldmann** [comment]
My laptop is linux-based, so I run the linux tests there (as normal user).

When doing release / platform testing, I use the Vagrantfile and vagrant VMs for testing.

In general, we have 3 kinds of "users" running the tests: non-root, real root, and fakeroot.

**Comment by finefoot** [comment]
How about just adding an additional `chmod -R ugo-w repo` for non-root users and letting `chattr` silently fail?

**Comment by finefoot** [comment]
```python
    @contextmanager
    def read_only(self, path):
        """Some paths need to be made read-only for testing

        To simulate operations on read-only repositories, writing
        permissions are simply being withdrawn. However, if the tests
        are being run with root privileges, this is not enough and
        the folder has to be rendered immutable, additionally.
        """
        if sys.platform.startswith('linux'):
            cmd_immutable = 'chattr +i "%s"' % path
            cmd_mutable = 'chattr -i "%s"' % path
        elif sys.platform.startswith(('darwin', 'freebsd', 'netbsd', 'openbsd')):
            cmd_immutable = 'chflags uchg "%s"' % path
            cmd_mutable = 'chflags nouchg "%s"' % path
        elif sys.platform.startswith('sunos'):  # openindiana
            cmd_immutable = 'chmod S+vimmutable "%s"' % path
            cmd_mutable = 'chmod S-vimmutable "%s"' % path
        else:
            message = 'Testing read-only repos is not supported on platform %s' % sys.platform
            self.skipTest(message)
        try:
            os.system('chmod -R ugo-w "%s"' % path)
            os.system(cmd_immutable)
            yield
        finally:
            # Restore permissions to ensure clean-up doesn't fail
            os.system(cmd_mutable)
            os.system('chmod -R ugo+w "%s"' % path)
```

**Comment by finefoot** [comment]
Cannot test it locally myself, unfortunately. But I'll just open a pull request to see if Travis has an issue with it.

**Comment by finefoot** [comment]
#5112

**Comment by finefoot** [comment]
Yup, seems like this works. Travis CI checks are still passing and I just ran `tox -e py37` locally inside a Docker container with a non-root user, which currently fails with `1.1-maint` but passes after adding the patch from #5112. I'll wait for your feedback regarding other platforms.

**Comment by ThomasWaldmann** [comment]
Works now, thanks!
