### ISSUE TITLE
python3-msgpack version 0.5.1 does not exist on Xenial

### ISSUE THREAD

**Issue by SamK** [borgbackup/borg#5114]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.

Ubuntu 16.04 with ppa

#### Your borg version (borg -V).
N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
add-apt-repository ppa:costamagnagianfranco/borgbackup
apt-get update
apt-get install borgbackup
```

## Describe the problem you're observing.

```
# apt-get install borgbackup
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 borgbackup : Depends: python3-msgpack (>= 0.5.1) but 0.4.6-1build1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

This might be related to #4959 but I'm not sure.

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg ^^^

Notable:
- There is currently no python3-msgpack offered by the ppa.
- We (borg developers) bundle a known-good msgpack into borg, so that could just be used and the ubuntu package dependency by removed.

**Comment by ThomasWaldmann** [comment]
@SamK if you need a working borg until that is fixed, you could:
- install the fat borg-linux64 from github releases page
- upgrade to ubuntu bionic (maybe a good idea anyway, considering that 16.04 will run out of support in 1y)
- upgrade to ubuntu focal for the very latest stuff

**Comment by ThomasWaldmann** [comment]
@samk the current borgbackup xenial package in the ppa should work - can you just try again (apt update, apt install ...)?

**Comment by SamK** [comment]
Hi @ThomasWaldmann thank you very much for your feedback.
We are currently stuck with Ubuntu Xenial for the moment.

I tried reinstalling borgbackup using apt-get but the issue is not solved.

Aren't we expecting to find python3-msgpack in the [pool folder](http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu/pool/main/p/
)?

**Comment by skerit** [comment]
I'm also still on Ubuntu 16.04, and I get the same error.
I also tried to install via pip3, but I guess this ubuntu version is just too old for that because I get several errors when doing that.

I actually plan on upgrading to 20.04 once it comes out in a few days, but want to create a backup first :)

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/releases/tag/1.1.11 there is a binary, which should "just work" on most linux / freebsd / macOS installations.

**Comment by SamK** [comment]
Good enough, I will use the binary as a workaround and close the issue.

Thank you for providing the best backup software in the world.

PS: Please note that the original problem I raised is still not solved: using the [ppa with Xenial](http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu/dists/xenial/) as advertised still does not work. In order to avoid future confusion, I think you should either make it work, rollback to a working version or in the worst case remove this repository.

**Comment by bwesen** [comment]
Hi, why was this closed? I just tried to install Borg on Xenial using the PPA and it doesn't work (exact same bug as the OP here). So please keep this open.

**Comment by ThomasWaldmann** [comment]
Well, it's no borgbackup upstream issue (for this issue tracker) but rather a packaging / distribution issue. But we can keep it open for a while so that people search for suggestions can more easily find it.

It has to be fixed by @LocutusOfBorg though, guess he'll have a look as soon as he finds some time.

**Comment by ThomasWaldmann** [comment]
Besides that, it is upgrade time for xenial users anyway, it will run out of support soon (4/2021) and the upgrade target (focal usually) is already available.

I recently upgraded from xenial -> bionic -> focal without an issue.

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg did you fix this already?

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg See link directly above ^^^.

Also there: https://travis-ci.org/github/borgbackup/borg-import/jobs/604430790 (our master branch broken now)

So guess this either needs a fix or a "wontfix" (considering the age of xenial, only having 7 months of remaining LTS support, this would be an option also).

**Comment by ThomasWaldmann** [comment]
See https://github.com/borgbackup/borg/pull/5404#issuecomment-706541761 - try again now?

**Comment by LocutusOfBorg** [comment]
We can close this issue! sorry for the delay!

**Comment by LocutusOfBorg** [comment]
we now use bundled msgpack
