### ISSUE TITLE
Inconsistent switch to display changes during 'dry-run' operation

### ISSUE THREAD

**Issue by jumper444** [borgbackup/borg#5116]
There are two operations I use, so far, to destructively modify a repository:
_delete_ and _recreate_

They allow wildcards, patterns, etc.  Obviously this is a dangerous operation and therefore the '--dry-run' switch exists for both to check your work before execution.

I have found an inconsistency in the method of displaying the proposed (dry-run) changes in order to review them however.

When I use _recreate_, the switches are "--dry-run --list" which will output what is going to happen.

However when using _delete_  the same process of "--dry-run --list" results in error:
_borg: error: unrecognized arguments: --list_

When using _delete_ , instead (through trial and error) I found out that instead I have to use:
"--dry-run --verbose"

My issues are:
1) this is not consistent switch usage for the listing of changes among operations that are relatively similar/destructive/deleting/changing; I think '--list' should function for both; (addendum: '--list' is also used with _create_ to likewise show added files and directories)

2) '--verbose' is generally viewed in a debugging light and should not be used in this context to display the desired output of a '--dry-run'; (It can still do that, but I think the 'what will change with this command' should be primarily on the '--list' command. verbose might include other info as well);

3) if '--verbose' is kept as the command to review results of a _delete_ dry-run it is not listed on the documentation page, (whereas the _recreate_ documentation page has '--list' right next to the '--dry-run' switch so a user can immediately grasp what to do.)  I suggest adding it under --dry-run switch to clarify how to see proposed deletions:
"_--verbose_      output list of items deleted (or to delete with --dry-run)"

**Comment by jumper444** [comment]
There may be other operations that have --dry-run options.  I would suggest (asserting that nobody does a --dry-run without wanting to see what will happen) that '--list' is available in all such circumstances.

**Comment by jumper444** [comment]
I'm using 1.1.11

**Comment by ThomasWaldmann** [comment]
maybe one should do a global review about consistency relating to this.

**Comment by realityexists** [comment]
Also worth noting that https://borgbackup.readthedocs.io/en/stable/usage/delete.html makes no mention of `--verbose` or `-v` and without those options `borg delete --dry-run` produces no output whatsoever, which probably makes it rather useless to the average user who has not searched the GitHub issues.

**Comment by ThomasWaldmann** [comment]
`-v` or `--info` sets the log level to `INFO` and is a global borg option.

By default, the level is `WARNING` and you won't see info-level output.

So guess the global log level stuff is only explained at some other place in the docs, but maybe we could at least add an example showing correct usage of `--dry-run` with `-v` or `--info`.

**Comment by jumper444** [comment]
Is there *any* situation where a person does a --dry-run but does not want to see the output?

**Comment by ThomasWaldmann** [comment]
Unlikely. :-) But the point is that borg needs to behave consistently and not do too much magic.

So, if you want to investigate, look at how similar use cases work (if their behaviour differs and is better).
Or, what else all needs to change IF we need a new mechanism for this and want consistent behaviour.

**Comment by Gu1nness** [comment]
I think that:
 * It is necessary to add the --list switch to _delete_
 * Update the documentation

This way we have a consistent way of listing files in all commands.
I can work on this one.

**Comment by ThomasWaldmann** [comment]
"update docs" likely means to just update `archiver.py` strings, the docs are auto-generated from that.

except the examples, they need to be edited in the respective rst files.
