### ISSUE TITLE
re-evaluate mmaped hashindex

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#513]
long ago, attic tried to work with a mmaped hashindex file, but removed it because of bad performance and started just loading the complete hashindex into memory, working with it and saving it back at the end. this consumes quite a lot of memory and can't work if you do not have that amount.

mmap seems a good idea in general though as it enables working with less memory than hashindex file size.

quite a while after that, i added "fadvise dontneed" calls to not blow up the fs / blocks cache for all the file data it reads once while backing up these files.

maybe this solves the mmap performance issues? i suspect that with the lower memory pressure now (due to fadvise), mmap could work better, so we could just try using it again.

**Comment by bdb** [comment]
Wouldn't using SQLite for the index and the caches be the best option? It should reduce mem usage quite a bit and still offer great performance. It's already been optimized to handled all of the dirty work of a persistent key-value store.

**Comment by enkore** [comment]
There are other options as well, although I don't really see the need(?) to entirely replace it. I don't claim to have extensively analysed performance of borg, but from the comparisons and profiles are made so far I'd say the bottlenecks are somewhere else (so for example file listing or extraction of small parts isn't limited by anything in the code, it's limited by the structure, cf. #32). Similarly archive creation is limited either by CPU (hashing, chunking, _compressing_, _encrypting_) or IO (in the former case multi-threading would help, in the latter multi-threading might enhance performance by a couple percent, or even decrease it: I/O is picky).

If we are talking about getting rid of code that is implemented in some other place already, then the BTrees package (developed mainly for ZODB) should be considered. Their implementation is efficient and has been shown to scale beyond *dozens* of GB per tree.

**Comment by ThomasWaldmann** [comment]
One could take an existing repo chunk index and:
- build / query another one from it (using same hashindex code)
- build / query a sqlite index
- ...
And then compare performance numbers.

**Comment by bdb** [comment]
Well, I was thinking more of memory use. I created a 900GB uncompressed, unencrypted archive with "--chunker-params 12,23,16,4095" and its pretty slow and uses a huge amount of memory (2GB+ easily). SQLIte should considerably reduce that memory usage since it will page in only whats needed to get the results for a query instead of loading the whole database into memory.

**Comment by ThomasWaldmann** [comment]
Yes, that's why the chunker params default to bigger chunks now. Reducing memory needs is a good goal, not just for small systems, but also for "many TB" scenarios. But we have to avoid performance issues. attic has been using mmapped index file and performance was bad. So, guess somebody has to try, maybe first the simple benchmark I suggested above.

**Comment by enkore** [comment]
I think we can scratch SQLite from the candidate list. I tried it today for the files cache, which has (much) bigger objects than the chunks cache:

- On disk: 250+ % space usage
      files cache: 215 MB for 2436610 entries (88 byte / entry) with
                   2535818 chunk IDs (i.e. sum(chunks) for all entries)
      sqlite3 db:  570 MB (exact same data set)
- Less memory usage
- But way slower (storing per-row-lists in a relational database doesn't work very well in general, I tried both separate table & BLOB msgpack. For the msgpack as a BLOB it needs less space (but still much more) and is slightly faster than with an extra table, but still slower than the current solution. I indexed both table on the path_hash.)
- I still have another idea how the files cache memory usage could be lowered with little performance impact, but that'll take a while.

Seems very very unlikely that SQLite would perform anywhere near HashIndex, which is used with even less per-node data (46 bytes) than the files cache, which has comparatively large nodes.

**Comment by ThomasWaldmann** [comment]
Hard to beat a in-memory hashtable (except maybe by a better in-memory hashtable).

That said, we also have to consider what we really need: for big files, we have 1 chunkid lookup per chunk and the chunk is about 2MB big - so if we pump 100MB/s big files, we have about 50 lookups per second.

For small files, it is very different of course as they might be just e.g. 1kB big - but then likely the reader would not yield 100MB/s anyway due to fs overhead / access time.

**Comment by enkore** [comment]
So I looked into this.

A minor hurdle is that the buckets aren't aligned to a page, but that's no big problem, just extend the map as needed and do some pointer math:

```c
static long page_mask;

/* mmap tools */
static void
_page_mask(void)
{
    if(!page_mask) {
        page_mask = sysconf(_SC_PAGESIZE) - 1;
        assert(page_mask != -2);
    }
}

static long
_round_to_page(long length)
{
    return (length + page_mask) & ~page_mask;
}

static void *
arbitrary_anon_mmap(long length)
{
    int mmap_flags = MAP_PRIVATE;
#ifdef MAP_ANONYMOUS
    mmap_flags |= MAP_ANONYMOUS;
#endif
#ifdef MAP_ANON
    mmap_flags |= MAP_ANON;
#endif
#ifdef MAP_HUGETLB
    mmap_flags |= MAP_HUGETLB;
#endif

    _page_mask();

    long real_length = _round_to_page(length);
    void *mapping = mmap(NULL, real_length, PROT_READ|PROT_WRITE, mmap_flags, -1, 0);
    if(mapping == MAP_FAILED) {
#ifdef MAP_HUGETLB
        if(errno == ENOMEM) {
            /* MAP_HUGETLB fails for small mappings (smaller than one huge page)
             * Strangely it does so with ENOMEM instead of EINVAL. */
            mmap_flags &= ~MAP_HUGETLB;
            mapping = mmap(NULL, real_length, PROT_READ|PROT_WRITE, mmap_flags, -1, 0);
            if(mapping != MAP_FAILED) {
                return mapping;
            }
        }
#endif
        EPRINTF("mmap()ing %ld bytes failed", real_length);
        return NULL;
    }

    return mapping;
}

static void *
arbitrary_file_map(int fd, long length, long offset)
{
    int mmap_flags = MAP_PRIVATE;
#ifdef MAP_HUGETLB
    mmap_flags |= MAP_HUGETLB;
#endif

    long real_length = _round_to_page(length);
    /* round the offset down to a page boundary */
    long real_offset = offset & ~page_mask;
    long addr_offset = offset - real_offset;
    assert(addr_offset >= 0);

    void *mapping = mmap(NULL, real_length, PROT_READ|PROT_WRITE, mmap_flags, fd, real_offset);
    if(mapping == MAP_FAILED) {
#ifdef MAP_HUGETLB
        if(errno == ENOMEM) {
            /* MAP_HUGETLB fails for small mappings (smaller than one huge page)
             * Strangely it does so with ENOMEM instead of EINVAL. */
            mmap_flags &= ~MAP_HUGETLB;
            mapping = mmap(NULL, real_length, PROT_READ|PROT_WRITE, mmap_flags, fd, real_offset);
            if(mapping != MAP_FAILED) {
                return mapping + addr_offset;
            }
        }
#endif
        EPRINTF("mmap()ing %ld bytes (offset %ld) from fd %d failed", real_length, real_offset, fd);
        return NULL;
    }

    /* add the difference between page-aligned offset and "wished" offset back to the mapping address */
    return mapping  + addr_offset;
}

static void
arbitrary_unmap(void *addr, long length)
{
    /* round incoming address down to a page boundary -
     * this is the inverse of what arbitrary_file_map may have done */
    void *real_addr = (void*)((long)addr & ~page_mask);
    long real_length = _round_to_page(length);
    if(munmap(real_addr, real_length) != 0) {
        EPRINTF("munmap()ing %ld bytes at %p failed", real_length, real_addr);
        assert(0); /* STONITH */
    }
}
```

Then just map on open:

```c
    if(!(index = malloc(sizeof(HashIndex)))) {
        EPRINTF_PATH(path, "malloc header failed");
        goto fail;
    }
    index->buckets = arbitrary_file_map(fileno(fd), buckets_length, ftell(fd));
    if(!index->buckets) {
        EPRINTF_MSG("note: fd %d is backed by %s", fileno(fd), path);
        free(index);
        index = NULL;
        goto fail;
    }
```

Okay, here's the first problem. We can't have PROT_WRITE on a mapping backed by a read-only fd, not possible. So we have to open in mode a+b, which moves us further away from working with read-only repos (**-1**).

This also means that any page we write to is copied first to a new page.

_init

```c
    index->buckets = arbitrary_anon_mmap(index->num_buckets * index->bucket_size);
    if(!index->buckets) {
        EPRINTF("mmap()ing buckets failed");
        free(index);
        return NULL;
    }
```

Simple enough.

---

At this point it makes sense to review why we want(ed?) this. For pure ro ops it's easier on the memory, since we don't copy by read(2) from the page cache. For writing it's the same. Note that, since we never mlock anything (we may consider doing that for passwords/keys), all the pages of the process are swappable.

The "have to open for writing" thing is kinda dealbreaker, working around it is also not trivial.

**Comment by enkore** [comment]
This is pretty much completely pointless now due to the effective load factor fix reading the entire table upon loading it.

**Comment by ThomasWaldmann** [comment]
Note: the ht scan done to count the empty buckets is now gone as of borg 2.0.0b3 (num_empty is simply saved to the header).
