### ISSUE TITLE
Remote: OpenSSL version mismatch

### ISSUE THREAD

**Issue by niieani** [borgbackup/borg#514]
I'm using the binaries from the GitHub release page on the repository server:
sha256: 5d8362f545aedf71be1893bd0fab30ecd79d40c89671323c804376b53f8886af
https://github.com/borgbackup/borg/releases/download/0.29.0/borg-linux64
Note: borg-linux64 binary built with openssl 1.0.1e (debian wheezy)

Initially, on the client, the same binary was used.

But when running Borg I get:

```
Remote: OpenSSL version mismatch. Built against 1000204f, you have 1000105f
Connection closed by remote host. Is borg working on the server?
```

Does that mean I need to recompile borg? If so, where, on the repository-side or locally?

On the remote repo server, there is openssl 1.0.2d-0ubuntu1.2 installed.

Note: "Remote:" does not always mean that the message to the right of it really came from the remote system. It is just stuff emitted on stderr on our side of the ssh tunnel. It can come from remote stderr, go through the tunnel and appear on our stderr. But it could be also emitted by our ssh client on stderr.

**Comment by niieani** [comment]
I've compiled borg locally (using `pip`) and the error went away, the repository-side works fine with the GitHub release binary.
There was another problem however, I'm on Ubuntu 15.10 and needed to `apt-get install python3.5-dev` otherwise `borg` would not compile. This package is not mentioned in the documentation.

**Comment by ThomasWaldmann** [comment]
Please update your first posts with the borg versions and how you made / installed them - for both the local client as well as the remote server.

The binary made with pyinstaller is expected to contain all libraries it needs, so it should not emit a openssl version mismatch.

Strange is that you say that a change on the client fixed the error msg from the server, I can't make sense from that.

**Comment by niieani** [comment]
Updated, basically I'm just using 0.29.0 both for the binary on the client and for the sources for the `pip` compilation. It indeed seemed weird for me too, since the error stated `Remote: OpenSSL version mismatch`.

**Comment by ThomasWaldmann** [comment]
please give the sha256sum for the binary you used on the server.

**Comment by niieani** [comment]
`5d8362f545aedf71be1893bd0fab30ecd79d40c89671323c804376b53f8886af`
which should be the same as: https://github.com/borgbackup/borg/releases/download/0.29.0/borg-linux64

**Comment by ThomasWaldmann** [comment]
also, please give the version number of the openssl package installed on the repo server.

**Comment by niieani** [comment]
```bash
$ apt-cache policy openssl
openssl:
  Installed: 1.0.2d-0ubuntu1.2
```

**Comment by ThomasWaldmann** [comment]
Please also give the openssl version installed as linux dist package on the client.

**Comment by ThomasWaldmann** [comment]
ping. see last comment. it's important as the version on the server somehow does not make sense with the error msg.

**Comment by ThomasWaldmann** [comment]
Ah, I think I can now make sense from the error message:
It comes from the client's ssh binary (/usr/bin/ssh) and is emitted on stderr.
We can't differentiate that from stderr stuff coming from remote via the tunnel, thus the "Remote:" prefix, which is wrong here.

"built against" is the version /usr/bin/ssh was built against.
"you have" is the openssl library bundled into the pyinstaller binary (intended to be used by borg, but seems that ssh loads it also).

**Comment by ThomasWaldmann** [comment]
hmm, do we need to unset LD_LIBRARY_PATH when forking ssh?
