### ISSUE TITLE
Return code 1 although permission of folder to be backed up denied

### ISSUE THREAD

**Issue by mokasin** [borgbackup/borg#5144]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.11

#### Operating system (distribution) and version.
Ubuntu 19.10

#### Hardware / network configuration, and filesystems used.
Backup user gains permission to the folder via ACL.

#### How much data is handled by borg?
One archive ca 100 GB
All Archives ca 2.21 TB

before compression and deduplication.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
Essentially the script from the documentation:
```
#!/bin/sh

# Setting this, so the repo does not need to be given on the commandline:
export BORG_REPO=/media/BackupUSB/borghome

# Setting this, so you won't be asked for your repository passphrase:
export BORG_PASSPHRASE=''

export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

# Backup the most important directories into an archive named after
# the machine this script is currently running on:

borg create                                \
    --filter AME                           \
    --list                                 \
    --stats                                \
    --show-rc                              \
    --compression lz4                      \
    --exclude-caches                       \
                                            \
    ::'{hostname}-{now:%Y-%m-%d}'          \
    /home/user1                             \

backup_exit=$?

info "Pruning repository"

# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
# archives of THIS machine. The '{hostname}-' prefix is very important to
# limit prune's operation to this machine's archives and not apply to
# other machines' archives also:


borg prune                          \
    --list                          \
    --show-rc                       \
    --prefix '{hostname}-'          \
    --keep-daily    7               \
    --keep-weekly   4               \
    --keep-monthly  24              \

prune_exit=$?


# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))

if [ ${global_exit} -eq 0 ]; then
    info "Backup and Prune finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup and/or Prune finished with warnings"
else
    info "Backup and/or Prune finished with errors"
fi

exit ${global_exit}
```

## Describe the problem you're observing.

Although the backup script completely fails, because it cannot gain permissions to the files it is supposed to backup, the return code is 1, a warning. I would expect an return code larger than 1, because this is an error!

Unfortunately, because the pruning did not check for the return code that means 0 bytes are written to disk and the following pruning deletes old backups that had the files. So basically good backups are replaced by empty ones one after the other!

Before pruning the return code of `borg create` should definitely checked (this should be changed in the documentation!), but an rc 1 code does not point to something as awful as that.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I am not sure, why the permission was denied in the first place. At the moment I cannot reproduce in vivo. Perhaps it can be reproduced by artificially denying access to the directory to be backed up.

#### Include any warning/errors/backtraces from the system logs

Output of my systemd-service running the script
```
Do 2. Apr 18:32:35 CEST 2020 Starting backup
/home/user1: scandir: [Errno 13] Permission denied: '/home/user1'
E /home/user1
------------------------------------------------------------------------------
Archive name: myhostname-2020-04-02
Archive fingerprint: ed12905b8dd0871db65267097a104a14ff5ca5fed65e6a013ef726bc95f769c7
Time (start): Thu, 2020-04-02 18:32:37
Time (end):   Thu, 2020-04-02 18:32:38
Duration: 1.13 seconds
Number of files: 0
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  915 B                741 B                741 B
All archives:                2.10 TB              1.71 TB             81.25 GB
                       Unique chunks         Total chunks
Chunk index:                  281604              6554786
------------------------------------------------------------------------------
terminating with warning status, rc 1
```

**Comment by ThomasWaldmann** [comment]
These are not bugs and a rc 1 means that you have to check the logs.

If pruning in such a case as yours means bad things happening, you have set the count of archives to be retained too low.

**Comment by mokasin** [comment]
Thx for the response. I would classify: I cannot make a backup because I cannot access the files, as an error. I am arguing that creating an empty backup instead is a bug indeed. I would expect that borg create fails in that case. Wouldn't you agree?

Just retaining more archives as a solution does not really make sense to me, because then I just have potentially a lot of empty archives.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/general.html#return-codes this is how the return codes are defined.

skipping of filesystem objects due to permission or other issues is rather frequent, so borg can not decide whether that fs object was important to you or not - you need to do that yourself by reading the logs if rc > 0.

if you end up with a lot of empty archives, it means you never read your logs, even if rc was > 0.

--stats output and checking how long the backup took are additional indicators that might be useful.

**Comment by mokasin** [comment]
Okay, fair enough. I do not have an issue if some file system objects are skipped. But it is strange to me, if none can be accessed it even creates an archive. But I guess it makes sense to you :wink:.

> if you end up with a lot of empty archives, it means you never read your logs, even if rc was > 0.

I am trying to find a backup solution for somebody not so tech savy who does not know how to use the command line or knows where to look for logs. So I tried to automate as much as possible and I myself only checked after months. In other words, I am looking for something idiot proof. My solution doesn't seem to fit the bill.

**Comment by ThomasWaldmann** [comment]
I guess it makes sense to you also if you think of the generalized cases:
- if it backs up 999 files and skips 1 due to some error, it is rc 1
- if it backs up 1 file and skips 999 files due to errors, it is rc 1
- why should it not be rc 1 if it skips 1 file as in your case but still reaches the end of the recursion without crashing (a crash would be rc 2)

One could argue now that skipping a toplevel file is serious. But skipping an important lower-level file could also be serious.

So, there is nothing helping you if you do not check the logs and decide yourself whether it was serious.

And there can't be a fully automated idiot proof solution without checking. A lot can go wrong and a lot of that can not be decided automatically.
