### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by elnappo** [borgbackup/borg#515]
don't use `~/.borg` use e.g. `~/.config/borg/` or `~/.local/share/borg/` (not sure which fits best) as described in the XDG Base Directory Specification.

* https://live.gnome.org/GnomeGoals/XDGConfigFolders
* http://standards.freedesktop.org/basedir-spec/latest/

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/29483339-follow-xdg-base-directory-specification)

**Comment by rumpelsepp** [comment]
I guess `~/.cache/borg` is important as well. But IIRC that directory it is already in use, isn't it?

**Comment by ThomasWaldmann** [comment]
Yes, I think moving the directory is useful. It would be nice if we could make "borg upgrade" do that and to change this at 1.0 release.

**Comment by htgoebel** [comment]
:+1:
You can find resp. code for all platforms in PyInstaller, see https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/configure.py#L58.

**Comment by anarcat** [comment]
the spec says:

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
> 
> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

since we use this mostly for key storage, it seems that `.local/share` is the place this should be, even if i find this freaking ugly. `$XDG_DATA_DIRS` should also be respected, which reverts to `/usr/local/share:/usr/share`, which seems wrong - shouldn't keys be in `/etc`? In this case it would be `$XDG_CONFIG_HOME`, but then that defaults to `/etc/xdg` which seems also ugly.

other ideas?

regarding the pyinstaller code, it doesn't actually respect the standard: it's missing the DIRS search path.

**Comment by ThomasWaldmann** [comment]
@anarcat: /etc needs root. using borg to make backups does not necessarily require root, any non-admin user of a multi-user system should be able to make a backup of his/her own stuff without having to ask the admin to change /etc.

**Comment by anarcat** [comment]
On 2016-01-24 12:09:57, TW wrote:
> @anarcat: /etc needs root. using borg to make backups does not necessarily require root, any non-admin user of a multi-user system should be able to make a backup of his/her own stuff without having to ask the admin to change /etc.

that is only a default fallback.

a.
-- 
They say that time changes things, but you actually have to change
them yourself.           - Andy Warhol

**Comment by htgoebel** [comment]
The spec says: "$XDG_DATA_DIRS [...] directories to *search* for data files". 

BTW PyInstaller is using $XDG_*CACHE*_DIR.

**Comment by anarcat** [comment]
i am pretty sure we don't want our crypto keys in a `cache` directory, which implies it can be deleted and then recreated freely.

that said, i think it makes sense to allow keys to be stored in `/etc/borg/keys` for system-wide backups (as opposed to `/root/...`), no?

**Comment by ThomasWaldmann** [comment]
Well, having keys at one specific place (like ~/...) is good, so you don't have to search them. :)
Also, that directory is always usable by the current user, /etc is not.
