### ISSUE TITLE
Release README says "Debian 9 Buster"

### ISSUE THREAD

**Issue by fantasya-pbem** [borgbackup/borg#5157]
## Is this a BUG / ISSUE report or a QUESTION?

(very minor) issue

## Describe the problem you're observing.

Release README.txt in the assets of https://github.com/borgbackup/borg/releases/tag/1.2.0a8 contains "built on Debian 9 Buster" which should be "Debian 10 Buster".

**Comment by ThomasWaldmann** [comment]
Fixed! Thanks for reporting!
