### ISSUE TITLE
Feature request: specific return code for locked repo

### ISSUE THREAD

**Issue by ettom** [borgbackup/borg#5158]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

Hi, this is a feature request for borg to exit with a specific return code in case the operation failed because of a locked repository. This would make scripting easier. My current solution is to run `borg with-lock $repo /bin/true` to check for a locked repository beforehand, but having a separate return code (3?) for this case would be nice. Perhaps other groups of errors could also have their own exit codes.

**Comment by ThomasWaldmann** [comment]
Assuming there was a specific return code for "repo is locked", what exactly would you do with it?

IIRC there is an older ticket for more specific return codes in general, but it has not been implemented (yet?) - maybe you can find it for more details.

**Comment by ettom** [comment]
I'd check the return code and notify the user/administrator. I could of course capture the output of the borg command and grep it for "locked repo", but thats a pretty ugly hack.

Also, the `with-lock` behaviour is not ideal at the moment. It's impossible to know if rc 2 was caused by the repo being locked, or the user command returning 2. This of course cannot really be fixed, but having a less common, specific error code for locked repos would help.

I did find the older ticket : https://github.com/borgbackup/borg/issues/61

**Comment by ThomasWaldmann** [comment]
Would `--lock-wait=XXX` be useful for you?

**Comment by ettom** [comment]
Yes, I'm already using that. It doesn't really solve the problem though, just postpones it.

**Comment by fantasya-pbem** [comment]
One could turn JSON logging on, and parse the msgid for LockError. See: https://borgbackup.readthedocs.io/en/stable/internals/frontends.html

**Comment by ettom** [comment]
I think this is even hackier than parsing the output directly. The way I see it, it would be nice if all of the msgids would have their own return code. Sadly I currently don't have enough time to start implementing this myself. I understand if there is a lack of interest from maintainers as this is more of a quality of life improvement.

**Comment by ThomasWaldmann** [comment]
todo:
- check what it is returning now (I assume it is rc=2 for error)
- pick a good value for "repo is locked" rc
- document it
- implement it

**Comment by rsyring** [comment]
FWIW, the use case for me is that I'm using a python script to help with automation of common borg functionality.  A general error code is raised all the way through the scripts b/c I don't know what it is.  If I had an error code just for locked repo, I could catch that, delay, and try again if applicable.

**Comment by ThomasWaldmann** [comment]
@rsyring but if you want to catch locked-error, delay and try again, you could also just give borg a quite high `--lock-wait=XXX` time and borg would do that loop internally.

**Comment by rsyring** [comment]
Agreed.  In my case, there is some other work that my app can go do while waiting to try again.  So in my case specifically, a blocking call using a high lock wait value is counter productive.  Quickly knowing we have failed to acquire a lock is desired, but easing the ability to know for sure it was a lock acquire failure situation, by looking at the return code, would be preferable.

**Comment by ThomasWaldmann** [comment]
see #6756
