### ISSUE TITLE
Borg config --list does not show last_segment_checked

### ISSUE THREAD

**Issue by fantasya-pbem** [borgbackup/borg#5159]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

## System information. For client/server mode post info for both machines.

1.2.0a8 / also master

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg config --list /path/to/repo`

## Describe the problem you're observing.

If a partial check has started and has been stopped due to timeout, the config file contains the `last_segment_checked` key with an int value.
You can verify that with `borg config /path/to/repo last_segment_checked`, which prints the segment number.

Now try `borg config --list /path/to/repo`: The last_segment_checked is missing.

Reason: In source code of archiver.py `last_segment_checked` is not read when the list subcommand is executed.

I will create a PR for this.

**Comment by fantasya-pbem** [comment]
Backporting to 1.1 is not needed because this config key is created by `borg check --max-duration` which is 1.2+ only.

**Comment by ThomasWaldmann** [comment]
So, why does one need to read this value?

**Comment by fantasya-pbem** [comment]
One could also try to read if this value exists, to see if a partial check has been started and has timed out. Even better, one can write this value to reset a partial check! ;-)
I consider it at least a missing feature, an inconsistency, if an entry in the config cannot be (at least) read by a command that exists to read config entries. Why does the config command exist at all?
