### ISSUE TITLE
recreate: drop the "experimental feature" warning?

### ISSUE THREAD

**Issue by martinvonwittich** [borgbackup/borg#5164]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

More of a feature request, really :)

#### Your borg version (borg -V).

```
backup ~ # borg -V
borg 1.1.9
```

#### Operating system (distribution) and version.

```
backup ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
backup ~ # cat /etc/debian_version
10.3
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg recreate --dry-run --verbose --list -e 'pp:home/some.user' '::archive...'
```

## Describe the problem you're observing.

`borg recreate` currently prints a warning indicating that the `recreate` feature is still experimental:

```
recreate is an experimental feature.
Type 'YES' if you understand this and want to continue:
```

[This warning has been in the code for 4 years](https://github.com/borgbackup/borg/blame/08a12cc40523b58bdfe92be9e9d937179287e805/src/borg/archiver.py#L1569) (which was the point where `recreate` was originally implemented). As far as I can tell from the currently open bug reports, there are currently no serious issues regarding `recreate`, and looking at the closed pull requests, most of the work on it happened back in 2017.

Is this warning still relevant today, or can it safely be removed?

**Comment by ThomasWaldmann** [comment]
You're right, it is not new nor there is ongoing work on it currently.

But we had users who erased lots of data by wrongly using it.

We already have documented that problem, but I guess we need to replace the "experimental" warning with a "potentially dangerous" warning. Same applies to `borg check` btw.

**Comment by enkore** [comment]
Afaik the "erased lots of data" problems were issues related to how Borg handles patterns (absolute-relative conversion and all that) leading to unintentionally not matching any files (much like `borg extract ... /home/foo`), I feel like there is an opportunity to improve this in general. For example, borg could detect the use of absolute paths when referring to archive contents and reject or possibly patch them with a warning.
