### ISSUE TITLE
recreate: --list: point user to "Item Flags" in borg help create

### ISSUE THREAD

**Issue by martinvonwittich** [borgbackup/borg#5165]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature request (documentation improvement)

#### Your borg version (borg -V).

```
backup ~ # borg -V
borg 1.1.9
```

#### Operating system (distribution) and version.

```
backup ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
backup ~ # cat /etc/debian_version
10.3
```

## Describe the problem you're observing.

The `recreate` documentation (`borg help recreate` and `man borg-recreate`) recommends to use the options `--dry-run --verbose --list` to test a `recreate` before actually doing it:

```
USE WITH CAUTION.
Depending on the PATHs and patterns given, recreate can be used to permanently
delete files from archives.
When in doubt, use --dry-run --verbose --list to see how patterns/PATHS are
interpreted.
```

Unfortunately it doesn't really explain how to interpret the output. From fiddling around with it I quickly figured out that filenames seem to be prefixed with either `-` or `x`, but I had a hard time finding the documentation that explains these characters (neither `-`, `x` nor `list` are easy to google^^). Guessing is pretty much a no-go here (`-` could as much be a simple list indicator like in it works Markdown, but also very well indicate subtraction, ie. "this file is going to be removed from the archive").

I finally found it in `borg help create`, in the section `Item flags`:

```
- '-' = dry run, item was not backed up
- 'x' = excluded, item was not backed up
```

The `borg help recreate` docs should point the user there so that this is easier to figure out :)

**Comment by ThomasWaldmann** [comment]
todo: add some links to docs.

**Comment by fantasya-pbem** [comment]
I'll have a look into it, maybe we can restructure the docs a bit and put "Item flags" in a more central section, referencing to it from the individual commands.
