### ISSUE TITLE
environment variables for borg list formats

### ISSUE THREAD

**Issue by ddribin** [borgbackup/borg#5166]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue (Enhancement Request)

#### Your borg version (borg -V).

`borg 1.1.11`

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg list --format '{archive:40} {time} [{id}]{NL}'`

## Describe the problem you're observing.

My archive names are a bit long, so in order to make `bog list` output prettier I use the `--format` option to expand the `archive` column to 40 characters, instead the default 36 . There are two issues with this:

1. It's annoying to have to type this in every time.
2. I only want this format for archive lists, not file lists, so I can't really alias `borg list`.

It would be really nice to have these two environment variables:

- `BORG_LIST_ARCHIVE_FORMAT`
- `BORG_LIST_FILE_FORMAT`

**Comment by ThomasWaldmann** [comment]
For borg2, that would be:
```
BORG_RLIST_FORMAT  # "repo list -> archives"
BORG_LIST_FORMAT  # "archive list -> files"
BORG_XXXX_FORMAT
```

**Comment by ddribin** [comment]
Nice! Thank you!
