### ISSUE TITLE
SSH mount: Backups mount on CloudLinux 

### ISSUE THREAD

**Issue by Moodesstas** [borgbackup/borg#5168]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?
Question
#### Your borg version (borg -V).
1.1.10
#### Operating system (distribution) and version.
`3.10.0-962.3.2.lve1.5.27.el7.x86_64 #1 SMP Sat Nov 30 02:18:52 EST 2019 x86_64 x86_64 x86_64 GNU/Linux`
`3.10.0-962.3.2.lve1.5.25.6.el7.x86_64 #1 SMP Thu Apr 18 06:40:26 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux`

## Describe the problem you're observing.
We have several servers with cloudlinux and borg backups installed. Backup mount performed with root permissions and specifying “allow_other” option. After the supposedly successful mount the files via ssh are only accessible to the root user and to the standard user backup folder is seen as empty.

The backups mount performed as follows:
Creating directory on user side and then mount backups
`/usr/bin/borg --lock-wait 180 mount -o allow_other -P files- ssh://usr@server.tld/backup/user1/borg '/user1/backups' `
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
/etc/mtab  has right information `“borgfs on /user1/backups/ type fuse (ro,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)”.` Tried option “ignore_permissions'' and nothing has changed. Tried “--debug” and no errors noticed. Checked and this option "allow_other" seems to be working, because users can access files via ftp.

**Comment by ThomasWaldmann** [comment]
"to the standard user backup folder is seen as empty" - did you try `cd mountpoint ; ls -l`?

**Comment by ThomasWaldmann** [comment]
also please check:
- uid/gid username/groupname mode of files in archive
- uid/gid username/groupname of the user you use to access the mounted files

**Comment by ThomasWaldmann** [comment]
Also, that a user can access the files via ftp but you do not see files locally as same user sounds rather strange.

**Comment by Moodesstas** [comment]
https://github.com/borgbackup/borg/issues/5168#issuecomment-621753243
Yes, strange situation, if I connect with users logins via port 21, the files are accessible, but if I connect via 22, whether it is sftp or ssh files not available, just empty directory and seems like not mounted at all.

Can you please detail what i need to check here on backup server
https://github.com/borgbackup/borg/issues/5168#issuecomment-621750920
![image](https://user-images.githubusercontent.com/39772853/80836877-57403080-8bfe-11ea-8c0e-4b86e091b8e7.png)

**Comment by ThomasWaldmann** [comment]
I didn't mean the files in the repository directory, but the files stored in the borg archive you are mounting.

**Comment by ThomasWaldmann** [comment]
@Moodesstas so, what was the solution?

**Comment by Moodesstas** [comment]
No, Still investigating this issue. But seems internal issue somehow related with ssh port because mounted backups accessible through port 21. I will update if i find something.
