### ISSUE TITLE
Borg check -- ask for passphrase immediately

### ISSUE THREAD

**Issue by kdmurray91** [borgbackup/borg#5170]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, apologies if I missed something though

## Is this a BUG / ISSUE report or a QUESTION?

Question/enhancement/feature request

#### Your borg version (borg -V).

`borg 1.1.9` from the debian sid package

#### Operating system (distribution) and version.

Debian sid

#### Hardware / network configuration, and filesystems used.

xfs on a raid 6 array

#### How much data is handled by borg?

~1.5TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
export BORG_REPO='/local/path/to/images.repo'
export BORG_PASSCOMMAND='pass borg/imagerepo'
borg check --prefix images --last 3 --progress
```

## Describe the problem you're observing.

`borg check` first does a repo scan which doesn't require a passphrase, and later asks for a passphrase when it starts checking the archives.

This causes some inconvenience, as i'll often run a backup and then leave `borg check` to run overnight. As this repo is quite large, the repo check will take a couple of hours, which means the archive check hangs until i can put the password in the next morning. If `borg check` asked for the passphrase immediately (via borg_passcommand, which in this case is [password-store](https://www.passwordstore.org/)), the scan over archives could complete overnight too. 

Taking a quick look at the code, perhaps the [`ArchiveChecker` instance](https://github.com/borgbackup/borg/blob/9019b48fd5982802af44a510b9decc05fa672c33/src/borg/archiver.py#L335) could be instantiated before the [`repository.check()` call](https://github.com/borgbackup/borg/blob/9019b48fd5982802af44a510b9decc05fa672c33/src/borg/archiver.py#L331) (only if `not args.repo_only`), and `ArchiveChecker`'s `__init__()` be changed to unlock the repo on instantitation? I assume `self.key = self.identify_key(repository)` is what gets the key? It seems that would require a bit of a rejig of `ArchiveChecker` to split initialisation code out from the `ArchiveChecker.check()` method. Are there places where an `ArchiveChecker` instance is used to check more than one repo, and therefore can't be one instance for one repo? If this logic seems sensible, i can code up a PR later.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

N/A, see above comandline.

#### Include any warning/errors/backtraces from the system logs

All commands successful, and logs are normal.

**Comment by ThomasWaldmann** [comment]
IIRC we already have an open issue about this, so this here might be a duplicate.
