### ISSUE TITLE
[Question] How to improve speed and reduce data transmission over the line.

### ISSUE THREAD

**Issue by Pecadis** [borgbackup/borg#5172]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
borg 1.1.11

#### Operating system (distribution) and version.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
4.19.0-8-amd64

#### Hardware / network configuration, and filesystems used.
amd64
32 Gb Ram
Zfs
Network to first Borg backup is locally and the second one over the Internet to an Offsite Location

#### How much data is handled by borg?
This archive:                 11.38 TB              9.40 TB             21.96 GB
All archives:              683.08 TB            564.69 TB             10.73 TB
                            Unique chunks         Total chunks
Chunk index:                 7642638            325556591

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create \
-s -C zstd,4 --exclude-caches \
--exclude '/poolone/01/01/*'    \
--exclude '/poolone/01/02/*' \
--exclude '/poolone/01/03/*'    \
--exclude '/poolone/01/04/*' \
--exclude '/poolone/01/05/*' \
--exclude '/poolone/01/06/*'     \
--exclude '/poolone/01/07/*'        \
--exclude '/poolone/01/08/*'        \
--exclude '/poolone/02/*'        \
--exclude '/poolone/03/*'        \
$BORG_REPO::$(date '+%Y-%m-%d_%H-%M-%S') $B_SENDER >> $b_logfile 2>&1

## Describe the problem you're observing.
I have run borgbackup since at least a year and have seen the average backup time to be about 1 hour. However it's now taking about three to four times as long as before. And also sends about 25 gb of data over the line.

I also followed the Docs, especially with the setup of borg serve on the receiving end.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Unfortunately, i can't really tell you how to reproduce it on your own System, it's more of a question on how to improve the Backup speeds and Data sent.

So: How could i speed up the Backup time and reduce the Amount of Data which will be sent over the line?

#### Include any warning/errors/backtraces from the system logs
Here are the outputs of the CRUD Operation with the command:
borg benchmark crud $BORG_REPO /poolone
```
C-Z-BIG          33.10 MB/s (10 * 100.00 MB all-zero files: 30.22s)
R-Z-BIG         247.05 MB/s (10 * 100.00 MB all-zero files: 4.05s)
U-Z-BIG          48.08 MB/s (10 * 100.00 MB all-zero files: 20.80s)
D-Z-BIG          69.21 MB/s (10 * 100.00 MB all-zero files: 14.45s)
C-R-BIG          39.78 MB/s (10 * 100.00 MB random files: 25.14s)
R-R-BIG          89.46 MB/s (10 * 100.00 MB random files: 11.18s)
U-R-BIG          46.89 MB/s (10 * 100.00 MB random files: 21.33s)
D-R-BIG          63.86 MB/s (10 * 100.00 MB random files: 15.66s)
C-Z-MEDIUM       55.76 MB/s (1000 * 1.00 MB all-zero files: 17.94s)
R-Z-MEDIUM      102.37 MB/s (1000 * 1.00 MB all-zero files: 9.77s)
U-Z-MEDIUM       48.25 MB/s (1000 * 1.00 MB all-zero files: 20.72s)
D-Z-MEDIUM       65.99 MB/s (1000 * 1.00 MB all-zero files: 15.15s)
C-R-MEDIUM       44.26 MB/s (1000 * 1.00 MB random files: 22.59s)
R-R-MEDIUM      100.03 MB/s (1000 * 1.00 MB random files: 10.00s)
U-R-MEDIUM       48.54 MB/s (1000 * 1.00 MB random files: 20.60s)
D-R-MEDIUM       61.93 MB/s (1000 * 1.00 MB random files: 16.15s)
C-Z-SMALL         5.64 MB/s (10000 * 10.00 kB all-zero files: 17.73s)
R-Z-SMALL        52.65 MB/s (10000 * 10.00 kB all-zero files: 1.90s)
U-Z-SMALL         4.64 MB/s (10000 * 10.00 kB all-zero files: 21.57s)
D-Z-SMALL         6.43 MB/s (10000 * 10.00 kB all-zero files: 15.55s)
C-R-SMALL         4.78 MB/s (10000 * 10.00 kB random files: 20.92s)
R-R-SMALL        53.10 MB/s (10000 * 10.00 kB random files: 1.88s)
U-R-SMALL         4.42 MB/s (10000 * 10.00 kB random files: 22.64s)
D-R-SMALL         4.89 MB/s (10000 * 10.00 kB random files: 20.46s)
```

**Comment by ThomasWaldmann** [comment]
Well, as you see at **This archive**, borg has put ~22GB new data into the repository.

The easiest explanation is that you have 22GB of new/changed data since the previous backup to that repo. That can be either content data or metadata.

**Comment by Pecadis** [comment]
Hi Thomas,
thank you for pointing out this fact i have overlooked. Is there generally a way to reduce that/ make it even more efficient (besides reducing the amount of raw new data)?

**Comment by ThomasWaldmann** [comment]
## metadata

Maybe check if you have something touching metadata, like:
- atime (also check in mount options for atime / noatime / relatime)
- uid/gid or mode (someone using `chown/chmod -R`?)
- xattrs or acls
- other metadata

Also check if you actually need to back up `atime` information.

Metadata is usually not much (compared to data), but e.g. if you back up `atime` timestamps and they are changing all the time, the whole stream of metadata will not or only badly deduplicate. If you have a huge amount of files, that might make a big difference already.

## data

If there is really a lot of change in the content data, you can check:
- whether you really need it in your backup (esp. caches and tmp can often be excluded)
- whether you can optimize chunker params for better deduplication (this is rather for new repos, for already existing ones you could make it worse)

Using `borg create --list --filter AME --stats ...` and keeping the output log is maybe useful here.

**Comment by Pecadis** [comment]
Thank you. I will try those points.

**Comment by Pecadis** [comment]
After fiddeling around, i finally found the issue.
i have done a Backup of my Monitoring system (influxdb) in that there was a "tag" which has been blown up tremendously which internally caused the data to be changed in a lot of places.

After cleaning up this part, it went back to a healthy 3,5 gb/day.
