### ISSUE TITLE
[Question] How to: patterns-from format?

### ISSUE THREAD

**Issue by nitwhiz** [borgbackup/borg#5175]
How do I specify files in the patterns-from file?

I've got
```
+ /home
+ /srv

+ /srv/gitlab/data/backups

- /home/andy/backup
- /home/andy/mk_wedding

- /srv/gitlab/data
- /srv/gitlab/logs

- **/.git/**
- **/.cache/**
- **/.composer/**
- **/.docker/**
- **/.gdrive/**
- **/.java/**
- **/.local/**
- **/.node-gyp/**
- **/.npm/**
- **/.yarn/**
- **/node_modules/**
```
in my `/config/include`, and am running borg like this:

```
borg create \
  --verbose \
  --list \
  --stats \
  --compression lz4 \
  --exclude-caches \
  --patterns-from /config/include \
  "::${BORG_ARCHIVE}" /home /srv
```

First off, order seems to matter? I have to put includes before excludes, `/srv/gitlab/data/backups` wouldn't be included else.

Those `**/.../**` don't work. Stuff like `/home/andy/.cache/yarn/v2/npm-nan-2.11.0...` is included.

Could you give me some hints on how these patterns work exactly?

**Comment by nitwhiz** [comment]
I think I found the secret. The definitions need to become less specific towards the end. Meaning, the deeper the path, the further up the definition needs to be. Imo this is a process which should be blackboxed away, but as always, Python is the reason we can't have nice things.

Working example:

```
+ /srv/gitlab/data/backups
- /srv/gitlab/data

- /srv/gitlab/logs

- /home/andy/backup
- /home/andy/mk_wedding

- **/.git/**
- **/.cache/**
- **/.composer/**
- **/.docker/**
- **/.gdrive/**
- **/.java/**
- **/.local/**
- **/.node-gyp/**
- **/.npm/**
- **/.yarn/**
- **/node_modules/**

+ /home
+ /srv
```

I like the rest of borg, keep up the good work! Ditch snek as soon as you can.

**Comment by Timvrakas** [comment]
This was _very_ hard for me to figure out. I think this behavior should be fixed, or at the very least the documentation improved.

**Comment by fantasya-pbem** [comment]
The docs say: _„The first matching pattern is used so if an include pattern matches before an exclude pattern, the file is backed up.“_

**Comment by nitwhiz** [comment]
@fantasya-pbem good point - this should be found [in here](https://borgbackup.readthedocs.io/en/stable/usage/create.html), not in "misc help" though.

still, i think a behaviour like `.gitignore` uses would make way more sense and is widely known.

**Comment by ThomasWaldmann** [comment]
At that place, it says 2 times "see borg help patterns" or so, but without using a link in the web based docs.

We should try to have a link in the web based docs, but the man page should also still look ok (no link possibility in there).
