### ISSUE TITLE
borg list patterns doc / example

### ISSUE THREAD

**Issue by akvadrako** [borgbackup/borg#5176]
I was trying to use `borg list` with path patterns but the documentation was lacking. I didn't see how to do it until I found a email thread with an example. The docs only say:

>   | PATH | paths to list; patterns are supported

My understanding is that unlike with `--exclude`, patterns are not recognized by default, but require a prefix like `re:`. It would be nice to have at least one example and maybe a line that says something like:

> if `path` starts with a pattern prefix, it will be treated like a pattern. Otherwise it must be an exact match."

**Comment by flolilo** [comment]
If I understand you correctly, this site might be what you were looking for:
https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-patterns

IMHO, this could be a little easier to find in the docs - I think I found it when looking through all search results of "exclude" in the RTD-search.

**Comment by akvadrako** [comment]
Not quite. It’s easy to find the documentation for patterns, and the exclude options are fairly clear.

It’s not clear that paths are only patterns if they are prefixed. Or maybe more clearly, the default prefix for path is “pp”.

**Comment by vjkr** [comment]
As it is labelled recently. I will give a try, Thanks Thomas

**Comment by remyabel** [comment]
I created a PR that clarifies that the pattern in command paths is distinct from `--exclude` and `--pattern` and is path prefix by default like akvadrako said. Let me know if that's sufficient.
