### ISSUE TITLE
Working with path

### ISSUE THREAD

**Issue by velgi** [borgbackup/borg#5177]
Hi!

Sorry if my question so simple, but I don't understand (after checking docs and issues), how i can work with path in my backups.
For example:

`borg create -s user@host:/backup/test_bk::test_wordpress /test/wordpress`   

after that I see:   
```
borg list user@host:/backup/test_bk::test_wordpress   
drwxr-xr-x root   root          0 Sat, 2020-05-02 02:00:03 test/wordpress   
-rw-r--r-- root   root      47874 Mon, 2020-02-10 06:50:05 test/wordpress/wp-login.php   
-rw-r--r-- root   root       3940 Thu, 2020-02-06 09:33:11 test/wordpress/wp-cron.php   
-rw-r--r-- root   root       3133 Thu, 2020-02-06 09:33:11 test/wordpress/xmlrpc.php   
-rw-r--r-- root   root       3300 Thu, 2020-02-06 09:33:11 test/wordpress/wp-load.php   
....
```   

And when I extract my backup like that:
`borg extract user@host:/backup/test_bk::test_wordpress test`   
There are no problems, backup restoring in current directory, in directory with name test.

But initially i want put in backup only directory "wordpress" , without directory tets. I want write   
 `borg create -s user@host:/backup/test_bk::test_wordpress /test/wordpress`   
 and in backup might be only wordpress. Maybe there are some options for that?

Also, i don't understand, why i can't restore backup in directory that i needed.
When i typing 
`borg extract user@host:/backup/test_bk::test_wordpress /root/test`
I see error:
`Include pattern '/root/test' never matched.`
I tried use `--strip-components` and try to changed command like that
`borg extract --strip-components 1 user@host:/backup/test_bk::test_wordpress wordpress`    
but without result    
`Include pattern 'wordpress' never matched`
How i can working with paths like i need?

**Comment by ThomasWaldmann** [comment]
borg create works with the path you give to it. so if you want it to be just "wordpress":
- cd /test
- borg create ... wordpress

borg extract always extracts into cwd. just go to where ever you want to be first.

**Comment by velgi** [comment]
Sorry to hear it. 
For me it too uncomfortable and illogical to use it for backups of many users, many sites etc.
