### ISSUE TITLE
Chunk ID XXXXXX missing from chunks index, corrupted chunks index - aborting transaction.

### ISSUE THREAD

**Issue by Oxemis** [borgbackup/borg#5178]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. Issue is kind of similar to https://github.com/borgbackup/borg/issues/1675. 

But my backup was not moved. 
It was created by this version of borg on this server and was working well since 2020-04-15. 
The backup is a local backup.

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).

borg 1.0.12 (1.0.12-0ubuntu1.16.04.1)

#### Operating system (distribution) and version.

Ubuntu 16.04

#### Hardware / network configuration, and filesystems used.

ext3

#### How much data is handled by borg?

Only a backup of /etc run each hour.

```
                       Original size      Compressed size    Deduplicated size
This archive:               11.32 MB              4.64 MB            131.21 kB
All archives:              475.81 MB            194.79 MB             18.00 MB

                       Unique chunks         Total chunks
Chunk index:                    3057               114649
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg prune --stats --list --keep-within 1d --keep-daily 15 --keep-weekly 5 --keep-monthly 18 /my/repo`

## Describe the problem you're observing.

Pruning does not work. The command return and exit code of 2.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, by running the command again.

#### Include any warning/errors/backtraces from the system logs

```
Chunk ID 8ff847_XXXXXX_37d462 missing from chunks index, corrupted chunks index - aborting transaction.
```

The command `borg check /my/repo` works fine and the return code is 0.

What can I do to recover from this state ?

**Comment by ThomasWaldmann** [comment]
See #4829 - in short: use a fixed borg version, e.g. 1.1.11 and read/follow the advisory in the changelog.

On xenial, you can try @LocutusOfBorg's ppa to get 1.1.11 or (in case that does not work) use the fat binary from there: https://github.com/borgbackup/borg/releases/tag/1.1.11

**Comment by ThomasWaldmann** [comment]
In case someone wants to patch borg 1.0.x, see #4968 .

**Comment by LocutusOfBorg** [comment]
my ppa is up to date!
