### ISSUE TITLE
Attempt to automate "borg" in script fails with "Connection closed by remote host."

### ISSUE THREAD

**Issue by yguel** [borgbackup/borg#5179]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
Client: Borg: 1.1.5  Python: CPython 3.6.9
Remote: on rsync.net Borg: 0.29.0 Python: CPython 3.4.3

#### Operating system (distribution) and version.
Client: Linux: Ubuntu 18.04 bionic
Remote: FreeBSD 11.1

#### Hardware / network configuration, and filesystems used.
Not relevant

#### How much data is handled by borg?
Not relevant 

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg init --debug --encryption=repokey-blake2 user@server:~/borg_bckp_tests
```

I get the same problem with 
```
borg create --progress --stats user@server:~/borg_bckp::test-00 /tmp/things_to_bckp
```

## Describe the problem you're observing.
When running from the shell the commands (init or create or any other) executes fine.

When running inside a python script with subprocess or os.system all the command fail with the error 
"Connection closed by remote host. Is borg working on the server?"

I would like to understand what prevents borg to be launched from a script especially if this is related to a ssh problem.

I know there is borgomatic that does something similar but I want to understand what happens here before switching to an other super tool.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes I can reproduce the problem.
I provided the following environment variables:
"BORG_RSH" tried it as "ssh -i ~/.ssh/id_rsa"  and as "ssh -oBatchMode=yes -i ~/.ssh/id_rsa"
"BORG_REMOTE_PATH" is set
"BORG_PASSPHRASE" is set
"BORG_NEW_PASSPHRASE" is also set

I tried to also set "SSH_ORIGINAL_COMMAND" with the same values than BORG_RSH but it did not change anything.
I tried that because the --debug option gave me:
"SSH_ORIGINAL_COMMAND: None"

#### Include any warning/errors/backtraces from the system logs
```
35 self tests completed in 0.09 seconds
SSH command line: ['ssh', '-oBatchMode=yes', '-i', '~/.ssh/id_rsa', 'user@server', '~/borg_bckp_tests', 'serve', '--umask=077', '--debug']
Connection closed by remote host. Is borg working on the server?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4253, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4185, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 132, in wrapper
    lock_wait=self.lock_wait, lock=lock, append_only=append_only, args=args)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 573, in __init__
    raise ConnectionClosedWithHint('Is borg working on the server?') from None
borg.remote.ConnectionClosedWithHint: Connection closed by remote host. Is borg working on the server?

Platform: Linux next 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.5  Python: CPython 3.6.9
PID: 12749  CWD: /tmp/backup_borg_tests
sys.argv: ['/usr/bin/borg', 'init', '--debug', '--encryption=repokey-blake2', 'user@server:~/borg_bckp_tests']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
rsync.net has a "borg1" binary that you should rather use than the outdated 0.29 one.

**Comment by ThomasWaldmann** [comment]
also, you should update your local borg to 1.1.11, see the changelog about why / what to do after upgrade.

**Comment by jdchristensen** [comment]
> SSH command line: ['ssh', '-oBatchMode=yes', '-i', '~/.ssh/id_rsa', 'user@server', '~/borg_bckp_tests', 'serve', '--umask=077', '--debug']

Doesn't this look suspicious?  It looks to me like it is trying to run "~/borg_bckp_tests" on the server instead of borg itself.

**Comment by yguel** [comment]
What is very strange to me, is that I run exactly the same command from the python subprocess and the shell and the results are completely different.
Indeed from the command line, the SSH command line is: ['ssh', '-i', '~/.ssh/id_rsa', 'user@server', 'borg', 'serve', '--umask=077', '--debug']

**Comment by yguel** [comment]
@jdchristensen You nailed it, I misused the BORG_REMOTE_PATH and interpreted it as the remote directory for backup and not the path for the borg command.

@ThomasWaldmann I will try to use borg1, and in that case set BORG_REMOTE_PATH to /usr/local/bin/borg1/borg1.

Thanks a lot to all for your help, everything is way clearer like that.
