### ISSUE TITLE
[Question] borg create from stdin and caching

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#5180]
I was not able to found clarification or any description of this scenarion in documentation:

How metadata caching is working in case of creating snapshot from stdin pipe? Example:

`mysqldump ... | borg create $REPOSITORY::mysql-$now -`

Is there any sense to add option `--files-cache=ctime,size` in this case? It's not file, so may be better to add `--no-cache-sync` or `--no-files-cache`? Will deduplication be working in this case?

btw, does `--files-cache=ctime,size` doing the same as `--ignore-inode` ?

**Comment by ThomasWaldmann** [comment]
as stdin is only a stream of data, there is no such metadata associated with it.

so, the files cache should not be used at all.

iirc, --ignore-inode is deprecated (do you see a warning?) and just removes `inode` from the `--files-cache` default of `ctime,size,inode`.

**Comment by knutov** [comment]
> cache should not be used for stdin at all

According to the documentation, "in order for the deduplication used by Borg to work, it needs to keep a local cache containing checksums of all file chunks already stored in the repository".

As I see by stats after `borg create` (and from repo size) - deduplication is working for backups from stdin.

Example for my random MySQL db (`mysqlump ... | borg create ... -`):

```
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               96.43 MB             11.32 MB            605.73 kB
```

So, how it is working then?

**Comment by ThomasWaldmann** [comment]
In my previous comment, I meant the `files cache`, not the `chunks cache`.

**Comment by knutov** [comment]
So, chunk cache is used, files cache is not used, it's ok to set `--no-files-cache` (or do not specify at all), but not good idea to set `--no-cache-sync`, am I correct?

**Comment by ThomasWaldmann** [comment]
Guess it should not do harm to use --no-files-cache, but maybe that is not even needed because borg does not load the files cache anyway when just processing stdin. Did not check the code yet about that though.

Don't use --no-cache-sync without good reason.

**Comment by ThomasWaldmann** [comment]
I checked the code:

`LocalCache._do_open` first reads the chunks cache and then the files cache (except if it is **disabled**).
So, one could save a bit of loading time by disabling the files cache for doing stdin-only archiving.

If the files cache is loaded, it is also saved back to disk at the end. You can see that by giving --progress.

**Comment by knutov** [comment]
Thanks!

**Comment by ThomasWaldmann** [comment]
Maybe adding this to the docs would be useful, PRs welcome.

**Comment by fantasya-pbem** [comment]
I'll do a PR for the docs.
