### ISSUE TITLE
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry size

### ISSUE THREAD

**Issue by JustPieceOfMeat** [borgbackup/borg#5181]
Hello, Tryed to make backup with `sudo borg create --verbose --compression lz4 /mnt::"05-08-2020" /home/public`, but got
```
Data integrity error: Invalid segment entry size 292495875 - too big [segment 341, offset 20489762]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1574, in do_prune
    with Cache(repository, key, manifest, lock_wait=self.lock_wait) as cache:
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 380, in __new__
    return local()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 374, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 467, in __init__
    self.sync()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 851, in sync
    self.chunks = create_master_idx(self.chunks)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 805, in create_master_idx
    fetch_and_build_idx(archive_id, decrypted_repository, archive_chunk_idx)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 710, in fetch_and_build_idx
    for item_id, (csize, data) in zip(archive.items, decrypted_repository.get_many(archive.items)):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 1084, in get_many
    for key, data in zip(keys, self.repository.get_many(keys)):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1079, in get_many
    yield self.get(id_)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1073, in get
    return self.io.read(segment, offset, id)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1415, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1439, in _read
    size, segment, offset))
borg.helpers.IntegrityError: Data integrity error: Invalid segment entry size 292495875 - too big [segment 341, offset 20489762]

Platform: Linux buhprofi-server 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64
Linux: debian 10.3
Borg: 1.1.9  Python: CPython 3.7.3
PID: 19200  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'prune', '--keep-daily', '7', '--keep-weekly', '4', '--keep-monthly', '3', '/mnt']
SSH_ORIGINAL_COMMAND: None
```
Tryed e2fsck, `borg check --repair /mnt`, that didn't help. 
I have 2 HDDs, one for system and data (2 parts) and one for backups. `lsblk` output:
```
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 931.5G  0 disk
├─sda1   8:1    0  14.9G  0 part /
└─sda2   8:2    0 916.6G  0 part /home/public
sdb      8:16   0 931.5G  0 disk
└─sdb1   8:17   0 931.5G  0 part /mnt
```
And I have enough space on backup partition. `df` output:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        15G  5.5G  8.4G  40% /
/dev/sda2       902G  175G  681G  21% /home/public
/dev/sdb1       917G   65G  806G   8% /mnt
```
So, I got the same error when tried `sudo borg prune --keep-daily 7 --keep-weekly 4 --keep-monthly 3 /mnt`

What should I do with it?

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#i-get-an-integrityerror-or-similar-what-now

**Comment by infectormp** [comment]
and update borg to latest version

**Comment by ThomasWaldmann** [comment]
... and follow the advisory at the top of the changelog.

**Comment by JustPieceOfMeat** [comment]
> https://borgbackup.readthedocs.io/en/stable/faq.html#i-get-an-integrityerror-or-similar-what-now

Tried to check disk, can't run memtest, because have only ssh access.



> and update borg to latest version

I have latest version from debian repos

**Comment by ThomasWaldmann** [comment]
Borg does not create such (292MB) big objects in the repo. So there is something severly wrong there:
- either that "size" is not really a size (some offset error)
- or it is a corrupted size, otherwise it could not be that big

So, did you follow the advisory about the pre-1.1.11 hashindex corruption issue?

**Comment by ThomasWaldmann** [comment]
@JustPieceOfMeat ^^^

**Comment by JustPieceOfMeat** [comment]
Updated borg from binary to 1.1.13 and tried:
```
$ sudo borg check --repair /mnt
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Exception ignored in: <bound method Repository.__del__ of <Repository /mnt>>
Traceback (most recent call last):
  File "borg/repository.py", line 179, in __del__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 274, in modify
  File "borg/locking.py", line 233, in load
OSError: [Errno 5] Input/output error: '/mnt/lock.roster'
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 176, in wrapper
  File "borg/archiver.py", line 338, in do_check
  File "borg/repository.py", line 971, in check
  File "borg/repository.py", line 1422, in iter_objects
  File "borg/repository.py", line 1514, in _read
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 4565, in main
  File "borg/archiver.py", line 4497, in run
  File "borg/archiver.py", line 176, in wrapper
  File "borg/repository.py", line 204, in __exit__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 274, in modify
  File "borg/locking.py", line 233, in load
OSError: [Errno 5] Input/output error: '/mnt/lock.roster'

Platform: Linux buhprofi-server 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
Linux: debian 10.4 
Borg: 1.1.13  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 2105  CWD: /home/user
sys.argv: ['borg', 'check', '--repair', '/mnt']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Input/Output error is usually an error below borg, like a malfunctioning disk, adaptor, filesystem or OS.

What exactly is mounted on /mnt and how?

**Comment by JustPieceOfMeat** [comment]
```
$ mount | grep /mnt
/dev/sdb1 on /mnt type ext2 (rw,relatime)
```
/dev/sdb is 1TB HDD just for backups. 
```
$ sudo df -h /mnt 
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1       917G   65G  806G   8% /mnt
```
when its just started I tried fsck, but it didn't help.

**Comment by ThomasWaldmann** [comment]
Seems to be a rather old disk, if `ext2` was a thing back then.

So, check the disk, use `smartctl -t long /dev/sdX` and (if it is still ok and) if you can, reformat it to `ext4`.

**Comment by JustPieceOfMeat** [comment]
smartlctl didn't work, I don't remember why. I converted ext2 to ext4 and it didn't work. I have physical access now, I'll check disks, RAM, wipe all and reinstall.

**Comment by hozza** [comment]
I may be able to shed some light on this.

I managed to get this same error when creating an archive in a repo. In my case the separate non-OS disk partition filled up during the "borg create" command (hardware is fine, as well as RAM and other hardware, EXT4, NVME).

I received many (maybe hundreds?) of more human readable errors saying that individual files could not be **read** due to lack of disk space (doesn't make much sense to me!) then at the end I got this:

```
borg.helpers.errors.IntegrityError: Data integrity error: Invalid segment entry size 2372513599 - too big [segment 406, offset 244176389
```

I've ran a `borg check repo::archive` and got some errors:

```
Data integrity error: Segment entry checksum mismatch [segment 406, offset 237011732]
```

I then ran a `borg check --repair repo::archive`. After I agreed to the terrifying messages, it said it fixed the issue and so I ran the create again (not sure if that's needed?) but it said the archive already existed... Not sure if the backup has worked tbh.

Edit: I ran another create afterwards with a tweaked timestamp and name. It completed almost instantly, with some sensible looking stats so I guess the previous one did work.

**Comment by ThomasWaldmann** [comment]
@hozza Hmm, if a repository disk/fs is 100% full, I would expect borg 1.x to crash due to that and not finish the repository transaction. When more space is available again and the next backup is tried, I would expect that borg rolls back the transaction to the pre-backup state and be fine again.

"archive already exists" is because each archive must have a unique name in borg 1.x.

**Comment by hozza** [comment]
I don't have any concrete evidence that it was the full disk. It could just be a coincidence I guess?

**Comment by ThomasWaldmann** [comment]
Yes, could be coincidence. If that was the first check since a while, there maybe was a undetected corruption issue until you ran it for other reasons.
