### ISSUE TITLE
borg stumbles over "Segment entry checksum mismatch" in archives check

### ISSUE THREAD

**Issue by shelvacu** [borgbackup/borg#5182]
## Have you checked borgbackup docs, FAQ, and open Github issues?

I've checked the docs and FAQ. There are too many issues to look over every single one, but I was not able to find a similar issue when searching through issues marked "question" or those mentioning borg check.

## Is this a BUG / ISSUE report or a QUESTION?

Question, perhaps a feature request.

#### Your borg version (borg -V).

`borg 1.1.11`

#### Operating system (distribution) and version.

Debian 10 buster, x86_64

#### Hardware / network configuration, and filesystems used.

An overlay FS combining an external hard drive and a FUSE google drive mount. I realize this may be the source of the problem, however I'd still like to know if I can fix it without recreating the repo from the beginning.

#### How much data is handled by borg?

Repo is currently 4.4TiB, eventually it needs to store ~13TiB of data.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg-env/bin/borg -v -p check --repair /root/borg-overlay`

## Describe the problem you're observing.

Borg check --repair failed to repair. I'm wondering what the best way would be to keep the progress so that I don't have to copy over the 4.4TB again

To be clear, I *don't* care about data loss in the borg repo for now. I only care about keeping my *progress* towards a complete, working borg archive. If I could somehow delete `emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt-6.checkpoint.3` while still keeping all the deduplicated segments of data that would seem to be ideal, but I don't know enough about the internals of borg to even say that would make sense.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Any attempt to `borg create` reliably fails with a similar error message, I'm sorry I don't have the exact message. The `borg check` command takes multiple days to run, and so I have not run it again.

However, since it says `Completed repository check, no problems found.`, I suspect that if I could skip to the archive consistency check, it could quite quickly reproduce the problem.

#### Additional info

I believe the corruption happened when the drive used for borg's cache filled up completely, and writes failed. This was a simple PEBKAC, and the cache is configured to write elsewhere now.

The archive is encrypted using `repokey-blake2`.

#### Include any warning/errors/backtraces from the system logs

```text
Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade (1/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade2.checkpoint (2/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt3 (3/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt4 (4/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt5 (5/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt6.checkpoint (6/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt-6.checkpoint (7/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt-6.checkpoint.1 (8/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt-6.checkpoint.2 (9/12)
Analyzing archive emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt-6.checkpoint.3 (10/12)
Data integrity error: Segment entry checksum mismatch [segment 2710, offset 4293464]
Traceback (most recent call last):
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 335, in do_check
    verify_data=args.verify_data, save_space=args.save_space):
  File "/root/borg-env/lib/python3.7/site-packages/borg/archive.py", line 1233, in check
    self.rebuild_refcounts(archive=archive, first=first, last=last, sort_by=sort_by, glob=glob)
  File "/root/borg-env/lib/python3.7/site-packages/borg/archive.py", line 1620, in rebuild_refcounts
    for item in robust_iterator(archive):
  File "/root/borg-env/lib/python3.7/site-packages/borg/archive.py", line 1562, in robust_iterator
    for chunk_id, cdata in zip(items, repository.get_many(items)):
  File "/root/borg-env/lib/python3.7/site-packages/borg/remote.py", line 1083, in get_many
    for key, data in zip(keys, self.repository.get_many(keys)):
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1109, in get_many
    yield self.get(id_)
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1103, in get
    return self.io.read(segment, offset, id)
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1470, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1506, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 2710, offset 4293464]

Platform: Linux 2esrever 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64
Linux: debian 10.3
Borg: 1.1.11  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 24284  CWD: /root
sys.argv: ['borg-env/bin/borg', '-v', '-p', 'check', '--repair', '/root/borg-overlay']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
you could try to delete the checkpoint with the corrupt segment.

**Comment by shelvacu** [comment]
Just tried that, unfortunately it's the same error:

```text
# borg-env/bin/borg delete /root/borg-overlay 'emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt-6.checkpoint.3'
Data integrity error: Segment entry checksum mismatch [segment 2710, offset 4293464]
Traceback (most recent call last):
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 1265, in do_delete
    return self._delete_archives(args, repository)
  File "/root/borg-env/lib/python3.7/site-packages/borg/archiver.py", line 1309, in _delete_archives
    with Cache(repository, key, manifest, progress=args.progress, lock_wait=self.lock_wait) as cache:
  File "/root/borg-env/lib/python3.7/site-packages/borg/cache.py", line 380, in __new__
    return local()
  File "/root/borg-env/lib/python3.7/site-packages/borg/cache.py", line 374, in local
    lock_wait=lock_wait, cache_mode=cache_mode)
  File "/root/borg-env/lib/python3.7/site-packages/borg/cache.py", line 467, in __init__
    self.sync()
  File "/root/borg-env/lib/python3.7/site-packages/borg/cache.py", line 851, in sync
    self.chunks = create_master_idx(self.chunks)
  File "/root/borg-env/lib/python3.7/site-packages/borg/cache.py", line 805, in create_master_idx
    fetch_and_build_idx(archive_id, decrypted_repository, archive_chunk_idx)
  File "/root/borg-env/lib/python3.7/site-packages/borg/cache.py", line 710, in fetch_and_build_idx
    for item_id, (csize, data) in zip(archive.items, decrypted_repository.get_many(archive.items)):
  File "/root/borg-env/lib/python3.7/site-packages/borg/remote.py", line 1083, in get_many
    for key, data in zip(keys, self.repository.get_many(keys)):
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1109, in get_many
    yield self.get(id_)
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1103, in get
    return self.io.read(segment, offset, id)
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1470, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/root/borg-env/lib/python3.7/site-packages/borg/repository.py", line 1506, in _read
    segment, offset))
borg.helpers.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 2710, offset 4293464]

Platform: Linux 2esrever 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64
Linux: debian 10.4 
Borg: 1.1.11  Python: CPython 3.7.3 msgpack: 0.5.6
PID: 29074  CWD: /root
sys.argv: ['borg-env/bin/borg', 'delete', '/root/borg-overlay', 'emanlooc@2020-03-31-before-stretch-buster-upgrade-attempt-6.checkpoint.3']
SSH_ORIGINAL_COMMAND: None
```

**Comment by shelvacu** [comment]
I was able to fix this by doing this in the python REPL: (actually did a lot more trial and error, but if I needed to do it again this should be all that's needed)

```python
from borg.logger import setup_logging
from borg.repository import LoggedIO
setup_logging()
lo = LoggedIO("/root/borg-overlay", 524288000, 1000)
lo.recover_segment(2710, lo.segment_filename(2710))
```

Where `/root/borg-overlay` is the repo, `524288000` is the `max_segment_size` from the `config` file, `1000` is the `segments_per_dir` config, and `2710` is the segment that it was complaining about.

`borg check --archives-only /root/borg-overlay` then reported no problems found.

----

I write this in the hopes that it might help other people who have the same problem, but I don't think this solves the issue. Shouldn't `borg check --repair` have run `recover_segment`?

**Comment by ThomasWaldmann** [comment]
Did you ever change the segments_per_dir value after already having some contents in the repo?

**Comment by ThomasWaldmann** [comment]
What strange here:
- the commandline and output in your first log / traceback shows that you ran a full borg check --repair (including repository and archives checks)
- the repository check reads all objects stored in the segment files and checks the crc32 - if there is an issue, it should internally get an IntegrityError there and it should (in --repair mode) call `recover_segment` for the problematic segment, outputting "attempting to recover <segment_filename>"
- but you do not have that in the repository check part, only later in the archives check part

**Comment by shelvacu** [comment]
> Did you ever change the segments_per_dir value after already having some contents in the repo?

No, definitely didn't change that. I'm not sure why it was having such strange behaviour.

**Comment by shelvacu** [comment]
Just had this happen a few days ago with a separate borg repo with a very similar setup. The one thing I noticed in common in every case was that it was preceded by a full disk on the system running borg, causing borg to fail (as expected).

**Comment by ThomasWaldmann** [comment]
Can you reproduce it? If so, open a new ticket with reproduction steps, preferably a script working with relative, local paths.

**Comment by starcraft66** [comment]
I had to use @shelvacu's REPL solution to fix one of my own backup repos borg 1.1.15 couldn't fix using `borg check --repair`. After running the python code, `borg check --repair` was able to succeed and zero out a couple of files.

**Comment by ThomasWaldmann** [comment]
Guess I'ld need to do debugging on a system where this is happening.

**Comment by ThomasWaldmann** [comment]
I've looked at the 1.1.11 code: do we have an issue with intermediate commits (like done for checkpoints)?

They are written to **same** segment as previous data and followed by following data (in same segment file).
A non-intermediate "final" commit is written to a separate segment file as its only content (in recent borg versions, older borg wrote the commit to the end of the segment file, after all previous data in that file).

`is_committed_segment` only returns True if a segment **ends** with a commit tag (which is usually not the case for an intermediate commit) and there is no `IntegrityError` encountered in the entries before the commit tag.

`is_committed_segment` is used by `get_segments_transaction` to find the segments transaction id.

With intermediate commits not being considered, they also won't be found for the segments transaction id, but only the last final commit. OTOH, the index transaction id corresponds to the last index update and the index is also updated for checkpoint/intermediate commits.

**Comment by ThomasWaldmann** [comment]
@shelvacu I read the 1.1.11 `Repository.check` code and could not find an issue how it could not find a crc32 mismatch in a segment file when doing a `borg check`. For all segment files and all entries in there, it reads header and data and computes / checks the crc32.

So flaky hardware behaviour could be the easiest explanation.

Any additional data from your side?

**Comment by shelvacu** [comment]
> Any additional data from your side?

Unfortunately I dont have the borg repo any more, and what I've written here is much more than my memory.

**Comment by ThomasWaldmann** [comment]
Guess we can't do anything more for this.

**Comment by boelle** [comment]
i also have this issue

2 backups in the repro

```
root@omvnovatech:~# borg list  /srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA
Enter passphrase for key /srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA:
21102023_10:06:36-Backup-Bo-OMV_NOVA Sat, 2023-10-21 09:06:54 [94b2ebe64ccc1273c37087bb1b10fe65c6c8ddf5baf4f910a2b118c2ad69cd4f]
21102023_10:46:52-Backup-Bo-OMV_NOVA Sat, 2023-10-21 09:46:58 [cb77345706dccb60d68d290a0f35400c857fbbb3befb289c0196fc4a141b7c0a]
```

i would have tried to delete the archive with the fault but the problem comes during the checking segments part of the check and it does not give a clue as there where and most important why (so i can avoid it in the future)

![image](https://github.com/borgbackup/borg/assets/3832239/6d2dbfb8-cbd2-47f3-bd63-1cdf1a498fa9)


2 machines in the UK that sends backup to me in DK, they also backup to each other for good messure
i send backup to both the machines in the UK

only one out of 6 backups have this error 

```
hecking segments 23.5%
Checking segments 23.6%
Data integrity error: Segment entry checksum mismatch [segment 1383, offset 194962596]
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1039, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1512, in iter_objects
    size, tag, key, data = self._read(fd, self.header_fmt, header, segment, offset,
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1611, in _read
    raise IntegrityError('Segment entry checksum mismatch [segment {}, offset {}]'.format(
borg.helpers.errors.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 1383, offset 194962596]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 343, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space, max_duration=args.max_duration):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1044, in check
    self.io.recover_segment(segment, filename)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1542, in recover_segment
    with mmap.mmap(src_fd.fileno(), 0, access=mmap.ACCESS_READ) as mm:
OSError: [Errno 19] No such device

Platform: Linux omvnovatech 6.1.0-0.deb11.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4~bpo11+1 (2023-08-08) x86_64
Linux: Unknown Linux  
Borg: 1.2.3  Python: CPython 3.9.2 msgpack: 1.0.0 fuse: llfuse 1.3.8 [pyfuse3,llfuse]
PID: 1790337  CWD: /
sys.argv: ['/usr/bin/borg', 'check', '--progress', '--repair', '/srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA']
SSH_ORIGINAL_COMMAND: None
```

Q is now, do i submit another backup and try to check again or do i submit the backup and just delete the other 2?

**Comment by ThomasWaldmann** [comment]
@boelle can you please move this to a new issue? The main issue in your case seems to be in line 1542, so that's different.

**Comment by boelle** [comment]
yes, give me a few....
