### ISSUE TITLE
[QUESTION] Add shared lock to CLI

### ISSUE THREAD

**Issue by scolby33** [borgbackup/borg#5183]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
1.1.11

#### Operating system (distribution) and version.
Debian 9

#### Hardware / network configuration, and filesystems used.
x64-64, local, ext4

#### How much data is handled by borg?
About 300GB deduplicated

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg with-lock ...`

## Describe the problem you're observing.
I would like to create a shared reader lock on the repository. My workflow is
- use `borg` to back up my workstation to a server
- use `rclone` to copy the borg repository on the server to cloud storage

Currently, I use `borg with-lock ... rclone ...` to hold a lock on the repository while uploading the borg repo to the cloud. I am switching cloud providers and will, for a time, be uploading to multiple places. I would like to allow these two uploads to proceed in parallel while still preventing writes to the repository.

A flag like `borg with-lock --shared` would work nicely.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
N/a

#### Include any warning/errors/backtraces from the system logs
N/a

**Comment by scolby33** [comment]
I am willing to work on a PR for this if the functionality would meet the approval of the maintainer.

**Comment by ThomasWaldmann** [comment]
borg currently always does exclusive locks.

**Comment by scolby33** [comment]
I see that `@with_repository` has an `exclusive` argument. Would a value of `False` there not actually make a lock or is this just not currently exposed to the CLI? https://github.com/borgbackup/borg/blob/master/src/borg/archiver.py#L109-L111

**Comment by ntova** [comment]
I use a similar approach. The easiest solution would be to call a script in `borg with-lock` and in this script call the two rclone commands in parallel using your shell, something like this:
```bash
#!/bin/bash 
rclone 1 &
rclone 2 &
wait
```

**Comment by ThomasWaldmann** [comment]
Using exclusive locks only was implemented due to the deadlocks the older method with "upgrading" from shared to exclusive gave us.

As we don't use shared locks right now, I am closing this.
