### ISSUE TITLE
SIGTERM handling

### ISSUE THREAD

**Issue by leonardopl** [borgbackup/borg#519]
`borg` doesn't catch **SIGTERM** signals and clean up as it does with **SIGINT** signals (CTRL+C), it just plainly exit, what makes continuing the backup later a little harder, since I can't even do a `borg check` into the repo (the process just keep running without doing nothing).

I had to manually delete the *lock.exclusive* folder for it to do a check, but even so I couldn't get it to continue the backup with `borg create`, after issuing the command it just keeps running without doing anything, as said above. (perhaps fixed in the version 0.29)

Since I was doing the initial backup it wasn't a problem for me, but it would be nice if borg could handle such cases (exiting without cleaning up).

I hit this **SIGTERM** issue today when using `borg` inside a script called by a `systemd` unit and had to stop the unit before `borg` could complete the backup. To stop the unit `systemd` by default sends a **SIGTERM** to the processes. But the issue can also be reproduced with a simple `kill`.

**Obs.:** I'm using borg version 0.28.2 shipped by *archlinux* in their [community] repo. I have looked into the changelog of version 0.29 before posting and didn't find any mention of the **SIGTERM** issue, though the lock up one could have been fixed, but I need to upgrade first before confirming.

**Comment by ThomasWaldmann** [comment]
If you kill it, it can be that it leaves a stale repo lock AND a stale cache lock. Since recently, there is a break-lock subcommand to get rid of them more comfortably in such conditions.

I'll have a look if lock cleanup can be improved for SIGTERM.

**Comment by ThomasWaldmann** [comment]
I looked at KeyboardInterrupt handling: there is nothing special there that cleans up locks. It just emits a log msg and sets exit code.

So I think what you ran into is the same as in #285 and we can close this one as duplicate.

**Comment by leonardopl** [comment]
Well, that issue is more specifically about when KeyboardInterrupt is called after a SIGINT (ctrl+c) signal and can't clear the lock.

But the problem is that after a SIGTERM the KeyboardInterrupt handling ins't called at all, `borg` just forcefully exit without printing anything and bash just print 'Terminated'.

For example when creating a archive and sending a **SIGINT** (ctrl+c):

```
 leonardo ~ $ borg create -s -C zlib repo::files files
^CKeyboard interrupt.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1261, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 1215, in run
    return args.func(args)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 183, in do_create
    read_special=args.read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 247, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib/python3.5/site-packages/borg/archiver.py", line 221, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib/python3.5/site-packages/borg/archive.py", line 535, in process_file
    chunks.append(cache.add_chunk(self.key.id_hash(chunk), chunk, self.stats))
  File "/usr/lib/python3.5/site-packages/borg/cache.py", line 356, in add_chunk
    data = self.key.encrypt(data)
  File "/usr/lib/python3.5/site-packages/borg/key.py", line 103, in encrypt
    return b''.join([self.TYPE_STR, self.compressor.compress(data)])
KeyboardInterrupt

Platform: Linux arch 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 
Linux: arch    LibC: glibc 2.3.4
Python: CPython 3.5.1
```

Now, with the same command, when sending a **SIGTERM** (`kill PID`):

```
leonardo ~ $ borg create -s -C zlib repo::files files
Terminated
```

In the first case the locks are removed, but in the second they aren't:

```
leonardo ~ $ borg create -s -C zlib repo::files files
Terminated
leonardo ~ $ borg create -s -C zlib repo::files files
Failed to create/acquire the lock /home/leonardo/repo/lock.exclusive (timeout).
```

Note that **SIGTERM** is different from **SIGKILL** (`kill -9`), as a **SIGTERM** can be caught by the process to allow it to do some cleaning before exiting, or it can even be ignored. If the process don't handle the **SIGTERM** signal it is forcibly terminated, as what happen with a **SIGKILL**.

**Comment by ThomasWaldmann** [comment]
@leonardopl look at the KeyboardInterrupt handler: there is nothing that removes locks.

So what you see is likely just that SIGINT (Ctrl-C) hit at a place of the code where no lock was set and SIGTERM hit at a place where a lock was set. Handling this is the topic of #285.

**Comment by leonardopl** [comment]
Sorry, I hadn't yet looked at the code, nor have I any experience with Python, but it seems, looking at the code (archiver.py), that it's just as you say, `borg` just catches the KeyboardInterrupt exception and exits. (I didn't know KeyboardInterrupt was a built-in exception generated by a SIGINT).

Feel free to close this issue, as long as a signal handler for **SIGTERM** can be implemented I don't see a problem.

Although, since the execution is being interrupted by a exception, I don't understand how the locks are being removed at all. I think the `__del__` method of Repository ensures that the locks are removed before or when the program exits. That why the locks are removed with a **SIGINT** and not with a **SIGTERM**, as the latter doesn't even give a chance for the program to exit properly (`sys.exit(exit_code)`) and thus Python interpreter can't delete the references and `Repository.__del__()` doesn't get called (but as the [Python reference states](https://docs.python.org/3.5/reference/datamodel.html?highlight=__exit__#object.__del__): "It is not guaranteed that `__del__()` methods are called for objects that still exist when the interpreter exits").

**Comment by ThomasWaldmann** [comment]
Yes, using `__del__` is a bad way to deal with such stuff. I really should be a context manager, see #285.

I am not sure if SIGINT and SIGTERM trigger a different behaviour concerning whether `__del__` is executed or not, but this can also be taken to #285.

**Comment by qknight** [comment]
i'm also affected by two lock scenarios:

i see two types of locks:
* lock
* lock.roster

both block new backups. why can't borg not check if the PID is still there and if not, remove the obsolete lock-file?

**Comment by enkore** [comment]
It can, it just doesn't do it ATM. #562 #1246
