### ISSUE TITLE
[Question] borg api for project integration

### ISSUE THREAD

**Issue by deajan** [borgbackup/borg#5191]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

Hello,

I am currently seeking a solution for KVM standalone hypervisor backups, and came to the conclusion that I should make local snapshots, and dedup/compress them to a remote repository.

For the remote backend, I consider the following projects: borg backup, bup, restic and burp.
So far, borg backup is my favorite in terms of dedup algorithm and performance.

The KVM snapshotting code being python, I'd like to know if borg backup has some sort of API, which would allow me to call borg functionnality without having to open an error prone subprocess to borg cli interface, ie facilitate borg assimilation in my project ;)

Best regards, Ozy.

**Comment by ThomasWaldmann** [comment]
There is no python api and as long there are bigger restructurings planned (see multithreading), having one might just break stuff in the future.

The usual way to use borg from higher level tools is to give commandline params (and maybe addtl. files, like pattern files) to it, create a subprocess and read its progress output in json format (see --json and --log-json).

One can also see subprocess as a feature (isolation, clear boundary, clear outer api) than as a problem.

**Comment by deajan** [comment]
Fair enough, having a `--json` output option for CLI is less error prone than having to parse some exotic output.
Thanks for your reply, and more generally thanks for the borg project.
