### ISSUE TITLE
Wishlist/suggestion: external source of change information

### ISSUE THREAD

**Issue by lheckemann** [borgbackup/borg#5194]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Question

#### Your borg version (borg -V).
borg 1.1.11
#### Operating system (distribution) and version.
NixOS 20.03
#### Hardware / network configuration, and filesystems used.
(not really relevant I guess?) 
#### How much data is handled by borg?
(irrelevant)
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
N/A

Some people use borg to create backups from zfs snapshots. This could be a lot more efficient than it currently is, particularly for large data sets — zfs's copy-on-write functionality allows the filesystem to determine exactly what changed between two snapshots more reliably and more quickly than by scanning the metadata as borg does, and doesn't need a cache for this purpose. Btrfs and other CoW filesystems could support this functionality as well.

I can see how this is nontrivial and exposes a lot of potential unsafety if introduced as a general-purpose command-line flag like `--assume-paths-unchanged`; but I would appreciate some feedback to find out what other people think about this — maybe it would be best implemented by a separate tool using borg as a library?

cc @grahamc @flokli @cole-h

**Comment by ThomasWaldmann** [comment]
Borg always does full backups, thus finding out which files have changed is only useful for not reading the **contents** of unchanged files. Borg will still read some **metadata* for **all** files (because these are not present in the files cache).

The result is always an archive that has entries for **all** files in the input data set.

**Comment by lheckemann** [comment]
Right, I think I was confusing two concepts:
- avoiding copying file contents by using the borg cache
- avoiding reading metadata
Makes sense that the latter is probably not feasible, but couldn't the need for the files cache still be avoided completely with a "sufficiently advanced filesystem", saving space and time?

**Comment by ThomasWaldmann** [comment]
The files cache has cmtime/inode/size and the chunks id list for all known ("seen") files.

So, if we detect "no content change" (by any means, including comparing cached cmtime/inode/size to the filesystem), we create the archive item like:
- read metadata (user/group/mode, ACLs, xattrs, ...) from filesystem and put into into the archived item
- use the cached chunks id list and put it into the archived item
- we do **not** need to read file contents, we know it did not change

The metadata disk access could only be avoided by caching more metadata, which would make the files cache even more huge than it already is.

**Comment by lheckemann** [comment]
Alright, seems there are too many things I don't know about for this to make sense. Thanks for the quick responses!

**Comment by ThomasWaldmann** [comment]
Yeah, it's quite clever (design from attic author).

I caught myself thinking about inotify etc. until noticing that it does not make sense because we need metadata from all the files.
