### ISSUE TITLE
borgbackup 1.1.11 fails to build with Python 3.9b1 (Fedora rawhide)

### ISSUE THREAD

**Issue by FelixSchwarz** [borgbackup/borg#5195]
I'm not yet sure if this is a borg problem - it might be as well Fedora setup but I figured this ticket might help coordination in case somebody else experiences the same problem.

Downstream bug with build logs and additional information: https://bugzilla.redhat.com/show_bug.cgi?id=1838161

Test output:

    __________ RemoteArchiverTestCase.test_compression_auto_compressible ___________

    self = <borg.testsuite.archiver.RemoteArchiverTestCase testMethod=test_compression_auto_compressible>

        def test_compression_auto_compressible(self):
            size, csize = self._get_sizes('auto,zlib', compressible=True)
    >       assert csize < size * 0.1
    E       AssertionError: assert 0 < (0 * 0.1)

    build/lib.linux-x86_64-3.9/borg/testsuite/archiver.py:2094: AssertionError

This test worked fine with Python 3.9 a6 but started to fail with 3.9b1.

The test checks the output of

    list --format "{size} {csize} {path}{NL}" "__testsuite__:/tmp/tmpwxjt208t/repository::test"

Good test output (with Python 3.8) is

    0 0 input
    10000 35 input/file

The test fails in Python 3.9:
    
    Remote: <frozen importlib._bootstrap>:228: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 872 from C header, got 880 from PyObject
    0 0 input
    10000 35 input/file

In the Fedora build ([spec file](https://src.fedoraproject.org/rpms/borgbackup/blob/master/f/borgbackup.spec)) we do not use pre-built Cython sources but recreate these from `.pyx`.

The strange thing is that I can not reproduce the issue when running the test suite in a VM (with the same packages as the Fedora process, no pip-installed packages). Together with the `RuntimeWarning` I suspect that we have a bad package somewhere.

I'll debug this further after the Fedora Python 3.9 mass rebuild (currently in progress). I hope that I can debug this much better once the mass rebuild is done and will update this issue.

**Comment by hroncok** [comment]
This was a problem on my side with python3-llfuse package rebuilt with Python 3.9.0a6. Sorry about that.

**Comment by The-Compiler** [comment]
Just stumbled upon this because of a similar issue in my own project - for future reference, you can launch Python with `-Werror` (or export `PYTHONWARNINGS=error`) to get a stacktrace to see where warnings like those are coming from.
