### ISSUE TITLE
No backups after pruning possible (Errno 13; Permission Denied)

### ISSUE THREAD

**Issue by hyWse** [borgbackup/borg#5200]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE / QUESTION

#### Your borg version (borg -V).

borg 1.0.9 (both, remote and client)

#### Operating system (distribution) and version.

Debian GNU/Linux 9.11 (stretch)

#### How much data is handled by borg?

around **8.5 TB** *before pruning*, **1.6 TB** *after pruning*

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

` borg prune -v --list --keep-within=10d --keep-weekly=4 --keep-monthly=-1 node10-repo/`

## Describe the problem you're observing.

After pruning a repository with the command above, I can no longer create backups. 
The last "version" in the repository under data/ is 120, but the client, which should be backed up, tries to read/write to data/174

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The problem occurred on all servers where I pruned using the command.

#### Include any warning/errors/backtraces from the system logs

```
borg check ssh://user@host//mnt/md0/borg/node07-repo
Remote: Borg 1.0.9: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 432, in check
Remote:     transaction_id = self.get_transaction_id()
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 150, in get_transaction_id
Remote:     segments_transaction_id = self.io.get_segments_transaction_id()
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 611, in get_segments_transaction_id
Remote:     for segment, filename in self.segment_iterator(reverse=True):
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 597, in segment_iterator
Remote:     filenames = os.listdir(os.path.join(data_path, dir))
Remote: PermissionError: [Errno 13] Permission denied: '/mnt/md0/borg/node07-repo/data/174'
Remote:
Remote: During handling of the above exception, another exception occurred:
Remote:
Remote: Traceback (most recent call last):
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 113, in serve
Remote:     res = f(*args)
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 435, in check
Remote:     transaction_id = self.io.get_segments_transaction_id()
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 611, in get_segments_transaction_id
Remote:     for segment, filename in self.segment_iterator(reverse=True):
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 597, in segment_iterator
Remote:     filenames = os.listdir(os.path.join(data_path, dir))
Remote: PermissionError: [Errno 13] Permission denied: '/mnt/md0/borg/node07-repo/data/174'
Remote: Platform: Linux ns3143987 4.19-ovh-xxxx-std-ipv6-64 #972509 SMP Thu Nov 7 08:31:48 UTC 2019 x86_64
Remote: Linux: debian 9.11
Remote: Borg: 1.0.9  Python: CPython 3.5.3
Remote: PID: 3059  CWD: /home/md0user
Remote: sys.argv: ['/usr/bin/borg', 'serve', '--umask=077']
Remote: SSH_ORIGINAL_COMMAND: None
Remote:
('Remote Exception (see remote log for the traceback)', 'PermissionError')
Platform: Linux ns3084809 4.9.150-xxxx-std-ipv6-64 #544830 SMP Mon Jan 14 08:31:26 UTC 2019 x86_64
Linux: debian 9.6
Borg: 1.0.9  Python: CPython 3.5.3
PID: 16145  CWD: /home
sys.argv: ['/usr/bin/borg', 'check', 'ssh://user@host//mnt/md0/borg/node07-repo']
SSH_ORIGINAL_COMMAND: None
```

Thanks for your help

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/4898

**Comment by hyWse** [comment]
Oh, my God, I feel stupid right now.

I gave the user with chown rights, but only for the data/ folder.
I have now given rights to the complete Borg folder again, now it works.

I should have tested it before I created an issue, I'm sorry, but i works now.
Thank you @infectormp
