### ISSUE TITLE
Building borg for RHEL/Centos 6.

### ISSUE THREAD

**Issue by mphilipps** [borgbackup/borg#5218]
hi,
With the latest release (1.1.12/1.1.13) the linux binaries are build on debian jessie and expect a higher glibc version.  This means it fails to run on RHEL/Centos 6, which still uses 2.12.

I figured I would be able to just built my binary, but even when following the pip/virtualenv tutorial I run into `raise RuntimeError("Python 3.5 or later is required")`. 
According to https://borgbackup.readthedocs.io/en/stable/installation.html I should only need 3.4, is this a mistake in the documentation or in the build process?

Steps to reproduce:
install epel6.
 ```
yum install -y python34 python34-devel python34-pip python-virtualenv openssl openssl-devel
libacl libacl-devel redhat-rpm-config
virtualenv --python=python3 borg-env
source borg-env/bin/activate
pip install -U pip setuptools wheel
pip install borgbackup
```

**Comment by ThomasWaldmann** [comment]
Yes, the wheezy boxes stopped working as Debian moved the apt sources to the archive servers.

As wheezy is way outdated anyway, I didn't feel like fixing them and switched to jessie (which soon will also run out of longterm support, but maybe the archive stays at the production servers for a while).

What you posted above is **not** building a fat binary, you need pyinstaller for that, see the `Vagrantfile` for the steps I used (a bit is also in the docs, but the Vagrantfile is more detailled).

Borg 1.1.x should work with 3.4, but as 3.4 is also pretty dead I used 3.5.latest to make the binaries (and the binaries bundle the python into the binary, so you don't need to have it on the system).

I can't help much with RHEL/Centos, I rather dislike it due to all sorts of strange issue I had with it.

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/github/borgbackup/borg/builds/695429949 you can see there that 1.1.3 works on py34.

**Comment by mphilipps** [comment]
> What you posted above is **not** building a fat binary, you need pyinstaller for that, see the `Vagrantfile` for the steps I used (a bit is also in the docs, but the Vagrantfile is more detailled).

I will give that a try.

> Borg 1.1.x should work with 3.4, but as 3.4 is also pretty dead I used 3.5.latest to make the binaries (and the binaries bundle the python into the binary, so you don't need to have it on the system).
> 
> I can't help much with old RHEL/Centos, I rather dislike it due to all sorts of strange issue I had with it.

Can't blame you for that, it is not like I am running Centos 6 because I enjoy it. It is just that some software is incompatible with anything that isn't at least 10 years out-of-date.

> https://travis-ci.org/github/borgbackup/borg/builds/695429949 you can see there that 1.1.3 works on py34.
Thank you for the link, lets hope this is still the case for 1.1.13

**Comment by ThomasWaldmann** [comment]
The travis log you see was testing the 1.1.3 code on python 3.4.6.

**Comment by mphilipps** [comment]
It seems like pip is a pretty stupid package manager. Doing `pip install -U pip` installs a pip version that is incompatible with the installed python version. Have to do `pip install -U pip==18.1`.

**Comment by mphilipps** [comment]
I think I almost got it. Pyinstaller succeeds and builds a binary, but a few files/modules appear to be missing.
```

./borg.exe --version
Traceback (most recent call last):
  File "borg/__main__.py", line 14, in <module>
  File "/root/borg-env/lib/python3.4/site-packages/PyInstaller-3.5+gf11e387-py3.4.egg/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "borg/__init__.py", line 5, in <module>
ImportError: No module named 'borg._version'
[1107] Failed to execute script __main__
```
It also appears to read from the borg-env. I would have assumed that with the pyinstaller the borg-env isn't required anymore.


What I am doing:
```
yum install -y python34 python34-devel python34-pip python-virtualenv openssl openssl-devel libacl libacl-devel redhat-rpm-config
virtualenv --python=python3 borg-env
source borg-env/bin/activate

pip install -U pip==18.1
pip install -U setuptools wheel

git clone https://github.com/thomaswaldmann/pyinstaller.git
pushd pyinstaller/
git checkout v3.5-maint
python setup.py install
popd

git clone https://github.com/borgbackup/borg.git
pushd borg
# edit basepath in scripts/borg.exe.spec
pyinstaller --clean --distpath=/root/b scripts/borg.exe.spec
popd
```

**Comment by ThomasWaldmann** [comment]
You need to proceed in the same way as in the Vagrantfile concerning installing borg.

The `_version` file missing is usually generated by `setuptools-scm` when you install (or sdist) borg.

If you want to generate a borg that says it is `1.1.13`, make sure not to edit any git controlled borg files.

**Comment by ThomasWaldmann** [comment]
Would #5220 help you?

**Comment by mphilipps** [comment]
> The _version file missing is usually generated by setuptools-scm when you install (or sdist) borg.

I will investigate.

> Would #5220 help you?

Of course it would, although it might be easier to get Centos 6 image for building? Unlike wheezy or jessie soon, Centos 6 is technically still supported.

**Comment by mphilipps** [comment]
Success, managed to build me some binaries for centos 6. If anyone else is trying to do the same, this is what I did.

```
yum install -y python34 python34-devel python34-pip python-virtualenv openssl openssl-devel libacl libacl-devel redhat-rpm-config
virtualenv --python=python3 borg-env
source borg-env/bin/activate

pip install -U pip==19.0.3
pip install -U setuptools wheel

git clone https://github.com/thomaswaldmann/pyinstaller.git
pushd pyinstaller/
git checkout v3.5-maint
python setup.py install
popd

pip download borgbackup==1.1.13
tar -xvf borgbackup-1.1.13.tar.gz
pushd borgbackup-1.1.13
sed -i 's/vagrant\/borg\/borg/root\/borgbackup-1.1.13/' scripts/borg.exe.spec
pip install -r requirements.d/development.lock.txt
pip install -e .
pyinstaller --clean --distpath=/root/b scripts/borg.exe.spec
popd
```

may have to adjust some paths.

**Comment by zapme** [comment]
Thanks for this, worked for RHEL6, binary portable to other RHEL boxes

**Comment by aiso-net** [comment]
Here is how to do it on CentOS 7 for anyone that wants to know:
yum install -y centos-release-scl epel-release
yum install -y rh-python38 rh-python38-python-devel rh-python38-python-pip rh-python38-python-virtualenv gcc gcc-c++ lz4-devel libzstd-devel xxhash-libs openssl openssl-devel libacl libacl-devel redhat-rpm-config wget fuse3 fuse3-devel libacl zlib-devel
scl enable rh-python38 bash
python3 -m pip install --user virtualenv
python3 -m virtualenv --python=python3 borg-env
source borg-env/bin/activate
pip install -U pip setuptools wheel
pip install pkgconfig
pip install pyfuse3
pip install borgbackup

**Comment by aiso-net** [comment]
For CentOS7/RHEL7:

yum install -y centos-release-scl epel-release
yum install -y rh-python38 rh-python38-python-devel rh-python38-python-pip rh-python38-python-virtualenv git gcc gcc-c++ lz4-devel libzstd-devel xxhash-libs openssl openssl-devel libacl libacl-devel redhat-rpm-config wget fuse3 fuse3-devel libacl zlib-devel
scl enable rh-python38 bash
python3 -m pip install --user virtualenv
python3 -m virtualenv --python=python3 borg-env
source borg-env/bin/activate
pip install -U pip setuptools wheel
git clone https://github.com/thomaswaldmann/pyinstaller.git
pushd pyinstaller/
git checkout v4.7-maint
python3 setup.py install
popd
pip install pyfuse3
pip download borgbackup==1.1.17
tar -xvf borgbackup-1.1.17.tar.gz
pushd borgbackup-1.1.17
sed -i 's/vagrant\/borg\/borg/root\/borgbackup-1.1.17/' scripts/borg.exe.spec
pip install -r requirements.d/development.lock.txt
pip install -e .
pyinstaller --clean --distpath=/root/b scripts/borg.exe.spec
popd

file is in /root/b/borg.exe

**Comment by IngoMeyer441** [comment]
Thanks @aiso-net for providing your steps for CentOS 7. I customized your script a bit to use the older `llfuse` instead of `pyfuse3`, otherwise `borg mount` would not work for me. This is my altered script for CentOS 7:

```bash
#!/bin/bash

BORG_VERSION="1.1.17"

cleanup () {
    if [[ -n "${SCRIPT_TMP_DIR}" ]]; then
        rm -rf "${SCRIPT_TMP_DIR}"
    fi
}
trap cleanup EXIT

SCRIPT_TMP_DIR="$(mktemp -d)" || exit

yum install -y \
    centos-release-scl \
    epel-release && \
yum install -y \
    fuse-devel \
    gcc \
    gcc-c++ \
    git \
    libacl-devel \
    libzstd-devel \
    lz4-devel \
    openssl-devel \
    redhat-rpm-config \
    rh-python38 \
    rh-python38-python-devel \
    rh-python38-python-pip \
    rh-python38-python-virtualenv \
    xxhash-devel \
    zlib-devel && \
pushd "${SCRIPT_TMP_DIR}" &>/dev/null && \
source /opt/rh/rh-python38/enable && \
python3 -m pip install --user virtualenv && \
python3 -m venv borg-env && \
source borg-env/bin/activate && \
pip install -U pip setuptools wheel && \
git clone https://github.com/thomaswaldmann/pyinstaller.git && \
pushd pyinstaller/ &>/dev/null && \
git checkout v4.7-maint && \
python3 setup.py install && \
popd &>/dev/null && \
pip download "borgbackup==${BORG_VERSION}" && \
tar -xvf "borgbackup-${BORG_VERSION}".tar.gz && \
pushd "borgbackup-${BORG_VERSION}" &>/dev/null && \
pip install -r requirements.d/development.lock.txt && \
pip install -e '.[fuse]' && \
pyinstaller --clean --distpath=../dist scripts/borg.exe.spec && \
popd &>/dev/null && \
popd &>/dev/null && \
cp -v "${SCRIPT_TMP_DIR}/dist/borg.exe" ./borg
```

Temporary files are cleaned up, the resulting executable is copied to the current working directory.

**Comment by aiso-net** [comment]
> pyfuse3
Thanks, what about the same script for pyfuse3, can you make a script for that? I would rather use a script that I can run each time a borg update comes out to get the compiled update.
