### ISSUE TITLE
Borg 1.1.13 binary: "Using a pure-python msgpack! This will result in lower performance."

### ISSUE THREAD

**Issue by Alex131089** [borgbackup/borg#5219]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).
1.1.13

#### Operating system (distribution) and version.
CentOS 7

#### Hardware / network configuration, and filesystems used.
Not relevant

#### How much data is handled by borg?
Not relevant

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
Not relevant

## Describe the problem you're observing.

Borg 1.1.13 downloaded from https://github.com/borgbackup/borg/releases/download/1.1.13/borg-linux64 doesn't seem to include the non-pure-python msgpack. When running operation on a repo, the following message appears:
```
# borg delete --cache-only -v
Using a pure-python msgpack! This will result in lower performance.
Cache deleted.
```
(was affected by bug 4829 twice without knowing it was a borg bug, thanks for the fix :) )

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

```
[vagrant@vagrant-centos-docker ~]$ curl -JOL https://github.com/borgbackup/borg/releases/download/1.1.13/borg-linux64
[vagrant@vagrant-centos-docker ~]$ ./borg-linux64 debug info
Using a pure-python msgpack! This will result in lower performance.
Platform: Linux vagrant-centos-docker 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64
Linux: CentOS Linux 7.6.1810 Core
Borg: 1.1.13  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 24890  CWD: /data/centreon
sys.argv: ['./borg-linux64', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('vagrant-centos-docker@90520739839718', 24890, 0)
```

**Comment by ThomasWaldmann** [comment]
I get this:
```
$ ./borg-linux64 debug info
Platform: Linux development 4.19.107-1.pvops.qubes.x86_64 #1 SMP Sat Feb 29 16:04:42 UTC 2020 x86_64
Linux: debian 9.12 
Borg: 1.1.13  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 18219  CWD: /home/user/w/borg-dist/1.1.13
sys.argv: ['./borg-linux64', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('localhost@95535655936', 18219, 0)
```

**Comment by Alex131089** [comment]
Hu, I did it again just to be sure: 

```
[vagrant@vagrant-centos-docker ~]$ cd /tmp

[vagrant@vagrant-centos-docker tmp]$ curl -JOL https://github.com/borgbackup/borg/releases/download/1.1.13/borg-linux64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623  100   623    0     0   1136      0 --:--:-- --:--:-- --:--:--  1138
100 14.5M  100 14.5M    0     0   444k      0  0:00:33  0:00:33 --:--:--  643k
curl: Saved to filename 'borg-linux64'

[vagrant@vagrant-centos-docker tmp]$ ls -lah borg-linux64
-rw-rw-r--. 1 vagrant vagrant 15M Jun  8 14:03 borg-linux64

[vagrant@vagrant-centos-docker tmp]$ chmod +x borg-linux64

[vagrant@vagrant-centos-docker tmp]$ ./borg-linux64 debug info
Using a pure-python msgpack! This will result in lower performance.
Platform: Linux vagrant-centos-docker 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64
Linux: CentOS Linux 7.6.1810 Core
Borg: 1.1.13  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 13973  CWD: /tmp
sys.argv: ['./borg-linux64', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('vagrant-centos-docker@90520739839718', 13973, 0)
```

What can I do to get more informations about what's wrong?

**Comment by Alex131089** [comment]
Unless I'm not understanding something and this is expected / expected is some situations?

**Comment by Alex131089** [comment]
It seems to have been introduced in borg 1.1.12:

1.1.10:
```
[vagrant@vagrant-centos-docker ~]$ rm borg-linux64; curl -JOL https://github.com/borgbackup/borg/releases/download/1.1.10/borg-linux64; chmod +x borg-linux64; ./borg-linux64 debug info
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623  100   623    0     0   1993      0 --:--:-- --:--:-- --:--:--  1990
100 14.3M  100 14.3M    0     0   465k      0  0:00:31  0:00:31 --:--:--  549k
curl: Saved to filename 'borg-linux64'
Platform: Linux vagrant-centos-docker 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64
Linux: CentOS Linux 7.6.1810 Core
Borg: 1.1.10  Python: CPython 3.5.7 msgpack: 0.5.6
PID: 20109  CWD: /home/vagrant
sys.argv: ['./borg-linux64', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('vagrant-centos-docker@90520739839718', 20109, 0)
```

1.1.11:
```
[vagrant@vagrant-centos-docker ~]$ rm borg-linux64; curl -JOL https://github.com/borgbackup/borg/releases/download/1.1.11/borg-linux64; chmod +x borg-linux64; ./borg-linux64 debug info
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623  100   623    0     0   1038      0 --:--:-- --:--:-- --:--:--  1038
100 14.6M  100 14.6M    0     0   468k      0  0:00:32  0:00:32 --:--:--  468k
curl: Saved to filename 'borg-linux64'
Platform: Linux vagrant-centos-docker 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64
Linux: CentOS Linux 7.6.1810 Core
Borg: 1.1.11  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 20394  CWD: /home/vagrant
sys.argv: ['./borg-linux64', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('vagrant-centos-docker@90520739839718', 20394, 0)
```

1.1.12:
```
[vagrant@vagrant-centos-docker ~]$ rm borg-linux64; curl -JOL https://github.com/borgbackup/borg/releases/download/1.1.12/borg-linux64; chmod +x borg-linux64; ./borg-linux64 debug info
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   623  100   623    0     0    895      0 --:--:-- --:--:-- --:--:--   895
100 14.5M  100 14.5M    0     0   445k      0  0:00:33  0:00:33 --:--:--  496k
curl: Saved to filename 'borg-linux64'
Using a pure-python msgpack! This will result in lower performance.
Platform: Linux vagrant-centos-docker 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64
Linux: CentOS Linux 7.6.1810 Core
Borg: 1.1.12  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 20678  CWD: /home/vagrant
sys.argv: ['./borg-linux64', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('vagrant-centos-docker@90520739839718', 20678, 0)
```

**Comment by brucegivens** [comment]
FWIW, I've also got this output on 1.1.13:
```
# ./borg debug info
Using a pure-python msgpack! This will result in lower performance.
Platform: Linux host.domain.com 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64
Linux: CentOS Linux 7.8.2003 Core
Borg: 1.1.13  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 18499  CWD: /usr/local/bin
sys.argv: ['./borg', 'debug', 'info']
SSH_ORIGINAL_COMMAND: None

CRC implementation: crc32_clmul
Process ID: ('host.domain.com@345052724999', 18499, 0)
```

**Comment by Alex131089** [comment]
```
[vagrant@vagrant-centos-docker ~]$ rpm -q glibc
glibc-2.17-260.el7_6.6.x86_64
```

Could it be related to https://github.com/borgbackup/borg/commit/0ceade3027420be9683a9b131c7f0e9a08670dc6 ?

**Comment by ThomasWaldmann** [comment]
The binary was built on a system with glibc 2.19 (documented in the README.txt, btw).

So maybe the compiled msgpack requires that now, fails to import on older systems and then falls back to the pure-python implementation.

**Comment by ThomasWaldmann** [comment]
See #5218, maybe you can work together to build a binary for aged RHEL/Centos systems.

**Comment by ThomasWaldmann** [comment]
Another approach would be #5220.

**Comment by Alex131089** [comment]
While I don't have issue with lower performances (seems equivalent so far), I just noticed it seems to break the remote feature:
```
Got unexpected RPC data format from server:
$LOG WARNING pyimod03_importers Remote: Using a pure-python msgpack! This will result in lower performance.
```
Am I doing something wrong, or this is a real bug and should have it's own issue?

**Comment by ThomasWaldmann** [comment]
@Alex131089 not sure I understand.

The root problem is the newer glibc requirement, right? This is known and not a bug, we just could think about #5220.

The slow msgpack error message caused by that disturbing the RPC communication is another issue though - and **that** might be caused by the "socat hack".

So, guess nothing to do here.

**Comment by devZer0** [comment]
i'm still getting this message with recent borg binary release and latest centos7

what performance implication will this have on borg runtime? i want to decide if it's worth putting effort intor resolving this problem.

**Comment by ThomasWaldmann** [comment]
I didn't measure yet how much slower the pure python msgpack is compared to the compiled one.

**Comment by devZer0** [comment]
ouch - apparently it makes a BIG difference !

i wished i had done performance comparison i little bit earlier, i did not expect that it's such a big difference. 

```
# time /backup/bin/borg check /backup-borg-repos/rproxy2
Using a pure-python msgpack! This will result in lower performance.

real	5m27.357s
user	5m21.804s
sys	0m1.008s

[root@backupvm2 ~]# time borg check /backup-borg-repos/rproxy2

real	1m3.628s
user	1m0.609s
sys	0m0.796s

**Comment by aiso-net** [comment]
I get this on CentOS 7 as well and would like to know how to fix it.

**Comment by ThomasWaldmann** [comment]
@aiso-net this ticket is closed, did you read the posts above?

**Comment by aiso-net** [comment]
Ya, just did, looks like its because an older glibc running on CentOS 7. I tried the yum version and your binary and both do it. So I think I might have to compile myself using modified instructions for CentOS 7 based on https://github.com/borgbackup/borg/issues/5218#issuecomment-641223235, correct?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/releases/tag/1.1.11 check this release if you want to deploy to old systems, it was the last one still built for an older glibc.

**Comment by aiso-net** [comment]
Thanks, feature/update wise, is it best to use the 1.1.11 generic binary or just compile each newer version manually and run on own compiled against CentOS7 ?

**Comment by ThomasWaldmann** [comment]
Of course if you can use the latest release, you will get better code quality (bug and performance fixes, maybe some new features), so if you can easily do that, go for it.

If building it yourself is a pain point, 1.1.11 binary is still good enough to use (not older than that, though).
If you run client / server, for the repo server side borg is often less important to have the latest and greatest as only runs a small part of the overall code on the server side. Most code parts run client side.

**Comment by aiso-net** [comment]
Thanks, until we get around to building our own, when running the 1.1.11, do we run that on the server (borg storage server where the backups are stored) to fix the issue or the client (the server getting backed up) to fix the issue?

**Comment by ThomasWaldmann** [comment]
@aiso-net usually you should use the latest release code (e.g. 1.1.17). but if you have an old linux installation and your glibc isn't fully compatible and you get that slow msgpack warning, you need to use the 1.1.11 binary because that was built on an older linux thant the 1.1.12+ binaries.

Alternatively, do not use the binaries and do a local installation, e.g. via pip, then you can use more recent borg versions (as long as the requirements are fulfilled.
