### ISSUE TITLE
Borg backup cannot read older backups made on non-UTF-8 systems

### ISSUE THREAD

**Issue by MrJohz** [borgbackup/borg#5222]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes - relevant FAQ [here](https://borgbackup.readthedocs.io/en/stable/faq.html#if-it-crashes-with-a-unicodeerror-what-can-i-do), relevant issues include #3202

## Is this a BUG / ISSUE report or a QUESTION?

I think more a QUESTION

#### Your borg version (borg -V).

borg 1.1.11

#### Operating system (distribution) and version.

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

#### Hardware / network configuration, and filesystems used.

External hard drive connected via USB

#### How much data is handled by borg?

A couple of backups from a previous laptop

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg list /media/<me>/<device_name>

## Describe the problem you're observing.

UTF-8 decoding problem - Borg cannot read the repository because it is (I think?) not correctly encoded.  My guess is that I created the original backup on a non-UTF-8 filesystem at some point in the past, and now I can't read it out again because Borg (reasonably) refuses to read non-UTF-8-encoded files.

My question is what I can now do in order to extract the files.  My guess would be that if I can install a version of Borg that's old enough, and guess the system encoding of my old laptop, this would work - do you know if there's a specific version of Borg that started failing on non-UTF-8 issues?

Alternatively, is there some other reason that this error can occur, or some other way that I can force Borg to try and read this repository?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, running the above command

#### Include any warning/errors/backtraces from the system logs

```
Exception ignored in: <function Repository.__del__ at 0x7f8e57ad7160>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 180, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 151, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 413, in open
    self.config.read_file(fd)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 3: invalid start byte

Platform: Linux jfrere 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64
Linux: Unknown Linux  
Borg: 1.1.11  Python: CPython 3.8.2 msgpack: 0.5.6
PID: 5282  CWD: /home/jfrere
sys.argv: ['/usr/bin/borg', 'list', '/media/jfrere/b197deea-0bd4-4199-9349-82aaddd7c71a']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
Read FAQ, please https://borgbackup.readthedocs.io/en/stable/faq.html#if-it-crashes-with-a-unicodeerror-what-can-i-do

**Comment by MrJohz** [comment]
Ah yes, I wanted to clarify that but I forgot - my current system encoding is in UTF-8 - that's not the issue.  My working theory is that it was the hard drive backup that was not created in UTF-8, and I can't change the system encoding to match the encoding that I was using then, because otherwise then I won't be using UTF-8 any more, and Borg complains.

**Comment by infectormp** [comment]
Can you print `locale` output here?

**Comment by MrJohz** [comment]
```
$ locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=

$ localectl status 
   System Locale: LANG=en_GB.UTF-8
       VC Keymap: uk
      X11 Layout: gb,de
     X11 Variant: ,
```

**Comment by infectormp** [comment]
Can you set locale to en_US.UTF-8 and check again to be sure?

**Comment by MrJohz** [comment]
```
$ LOCALE=en_US.UTF-8 borg list /media/jfrere/b197deea-0bd4-4199-9349-82aaddd7c71a/
Exception ignored in: <function Repository.__del__ at 0x7f3b8d9c5160>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 180, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4529, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4461, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 151, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 413, in open
    self.config.read_file(fd)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 3: invalid start byte

Platform: Linux jfrere 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64
Linux: Unknown Linux  
Borg: 1.1.11  Python: CPython 3.8.2 msgpack: 0.5.6
PID: 8518  CWD: /home/jfrere
sys.argv: ['/usr/bin/borg', 'list', '/media/jfrere/b197deea-0bd4-4199-9349-82aaddd7c71a/']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
borg is not a charset conversion tool.

but iirc it stores the byte sequence of the pathes, so if you backed up from a latin1 filesystem, just restore to a latin1 filesystem encoding and it should work.

**Comment by ThomasWaldmann** [comment]
problems related to this one:
- encoding of archived paths must be **known** - not sure if we store it into an archive, maybe not
- quite frequently encoded filenames encountered on old samba servers is a real mess. there is not **one** encoding, but a whole mess if historical encoding and even total invalid crap.
- going from non-unicode known and valid encoding to some unicode encoding (like utf-8) is no problem, but the opposite **can be** and information being lost from filenames.
- not sure about xattrs, ACLs etc. - likely there are also lurking encoding issues.

**Comment by hubx** [comment]
I encountered something related while borg extract an ext4/Linux archive on apfs/macos

`ph?nomen 093.jpg: open: [Errno 92] Illegal byte sequence: '<PATH>ph\udce4nomen 093.jpg'`

similar errors occur for paths containing \udce1

While investigating I found this [source ](https://books.google.de/books?id=f7wGeA71_eUC&lpg=PA162&ots=Xkg009j-Ir&dq=The%20reason%20it%20crashes%20is%20that%20the%20character%20%5Cudce4%20is%20technically%20invalid%20Unicode&hl=de&pg=PA162#v=onepage&q=The%20reason%20it%20crashes%20is%20that%20the%20character%20%5Cudce4%20is%20technically%20invalid%20Unicode&f=false) claiming that \udce4 is a surrgate pair, which is utf-16. I am not sure if the filename was valid on the original system.

and this thread https://news.ycombinator.com/item?id=13954240 talks about differences in encoding. there is a mention that there is a workaround for rsync (`--iconv=UTF-8-MAC,UTF-8`)

Happy to create a sepreate issues if this is another issue or specific to macos

**Comment by ThomasWaldmann** [comment]
@hubx is that all you got or could you also provide a full traceback?

If that happens with `borg extract`, you could also try `borg mount` and use the shell or misc. file managers to copy/rename such files.
