### ISSUE TITLE
Feature suggestion - improve reporting of progress for "check --repair"

### ISSUE THREAD

**Issue by kellytrinh** [borgbackup/borg#5229]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature Request/Suggestion

## System information. For client/server mode post info for both machines.

N/A

#### Your borg version (borg -V).

borg 1.1.13

#### Operating system (distribution) and version.

N/A
#### How much data is handled by borg?

450Gb

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg check --verbose --repair /mnt/Backups/Borg

## Describe the problem you're observing.

**1) Review Experimental Warning**

I get the following when running above command.

``` 'check --repair' is an experimental feature that might result in data loss.```

In the light of issue #5164 suggest to also review warning  

**Suggestion 2:**

Need to better communicate what is going on; note already using --verbose option.

After 4 hours I have 

```'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
Starting repository check
```

That's it.  Disk activity seems to indicate something is being done but no clue how far along it is.   Its been 4 hours and don't know if going to be done soon or another 4, 14, 24, or more! (the full backup would be around 24 hr so if much much more then I would just rather cancel the repair)

**Comment by ThomasWaldmann** [comment]
Huh?

So you are saying you immediately get
```
 'check --repair' is an experimental feature that might result in data loss.
```

... then 4 hours no output and then you get

```
Type 'YES' if you understand this and want to continue: YES
Starting repository check
```

?

**Comment by ThomasWaldmann** [comment]
Also try `--progress` option, please.

**Comment by kellytrinh** [comment]
For first - The query was immediate.  I posted this after four hours.

I waited 12 hours (a normal backup takes about 8 hours from zero...) and then killed the process

I fixed the repo with another method so can't experiment or reproduce anymore.

**Comment by ThomasWaldmann** [comment]
it is expected that a full borg check (which checks all segments in the repo AND all archives in the repo) takes longer than creating 1 initial archive.

the are some options to speed this up if one only wants a partial check.
