### ISSUE TITLE
Example path for --exclude-from

### ISSUE THREAD

**Issue by tuxick** [borgbackup/borg#5236]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## Describe the problem you're observing.

I found it quite hard to find out how to use/allow spaces in --exclude-from file, one extra example in manual/help might help a lot:

# No need to escape spaces 
/mnt/c/System Volume Information

(not having to escape spaces is quite counterintuitive :)

**Comment by ThomasWaldmann** [comment]
Well, if you consider that parsing of arguments and splitting at spaces is a feature of your shell (and quoting is for working around that feature), it is quite intuitive.

The contents of --exclude-from or --patterns-from files are not processed by your shell, but directly read by borg.

OTOH, when entering `borg ... <arguments>` on the command line or in a shell script, the arguments *are* processed by the shell.

**Comment by Gu1nness** [comment]
Taking this one, documenting both patterns files and exclude files.
From what I understand (and from my tests) adding a space is not a problem since everything is handled by borg which reads one entry per line.
