### ISSUE TITLE
Document renaming repository

### ISSUE THREAD

**Issue by tuxick** [borgbackup/borg#5240]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Request for documentation

## Describe the problem you're observing.

Could not find how to rename a repository, what i found is that all it takes is:

**rename the repository on the server
change path in ~/.cache/borg/*/config**

**Comment by ThomasWaldmann** [comment]
if you just rename the directory (or move the whole thing to a different ssh location), borg will warn you next time when you talk to the repo at the new location that the repo has moved. if you confirm, you should be done.

please try that. not sure if we need to document something if you can just do it, confirm and you're done!?

**Comment by tuxick** [comment]
The fact I ended up messing about kinda suggests it's worth documenting. It seems sensible to not just try renaming directories without first checking how it's supposed to be done.
Figured out a useful thing is trying a borg list after renaming, to get prompted and have the rename checked as well, without interfering with the (cron schedule).
I also forgot about BORG_RELOCATED_REPO_ACCESS_IS_OK.

**Comment by eamanu** [comment]
Hello!, I would like to work on this issue today on the EuroPython sprint.

**Comment by ThomasWaldmann** [comment]
sure, just do it! :-)

**Comment by ThomasWaldmann** [comment]
note:

that env variable is good when doing a mass rename or when needing automation. if you do not set that env var, borg will just interactively ask whether it is ok.

about generation of docs you have to know that some part is auto-generated from text in archiver.py and some other parts are taken from the docs/ directory.
