### ISSUE TITLE
Tamper resistance when attacker has keys?

### ISSUE THREAD

**Issue by gcoimbra** [borgbackup/borg#5245]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

The newest...

#### Operating system (distribution) and version.

Irrelevant. I think.

#### How much data is handled by borg?

Irrelevant.

## Describe the problem you're observing.

I've read that encypted repo of Borg is tamper resistant when attacker does not have keys. But when it does, can I just record the  
archive fingerprint somewhere else, and if I think the repo or the archive maybe tampered alredy I just check the fingerprint against the one I've recorded? If not, anyway of doing this?

**Comment by ThomasWaldmann** [comment]
You always can tamper data if you have access to it.

But I guess what you mean by tamper resistant is that tampering does not go undetected. That is reached by using a MAC over the stored data (and to compute the MAC, you need key material which is stored encrypted inside borg's key).

So, having the borg key is not enough, you also need to be able to decrypt it (== have the passphrase that protects it).

If you have key and passphrase, you can decrypt repo data as well as compute valid MACs over new data (which you could add to the repo). Also, you could chunk files in the same way as that borg is usually doing it for that repo.

As the archive id is a MAC over the archive metadata, I guess you could detect somebody tampering with the archives if a known id of a known archive suddenly changes without your actions being the reason for that (e.g. borg recreate).

But before relying on that, better review the code that deals with this.

**Comment by enkore** [comment]
> But when it does, can I just record the
archive fingerprint somewhere else, and if I think the repo or the archive maybe tampered alredy I just check the fingerprint against the one I've recorded?

Yes, but keep in mind that checking the "borg list" output isn't enough, since that doesn't verify the merkle tree all the way down. A "borg extract --dry-run" would do that, for example.
