### ISSUE TITLE
Move borg repository to another server

### ISSUE THREAD

**Issue by antiuser** [borgbackup/borg#5249]
Hi there! I want to know how can i move borg repo to another machine?
I want to upgrade my backup server and install another hard drives, i need to format this array with borg backup.
I want keep only empty repository (archives not important for this operations).
What can i do with that?
Thank you!

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

**Comment by antiuser** [comment]
> https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

Yep, i already read this manual, but i want to change server machine (and use hostname from old server backup). So if i create a new repo than my clients may be have a problem to copy to this repo (think, there will be a question - Borg backup location change, are you shure to copy?). And in this situation i need to change script on each machine

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables
**BORG_RELOCATED_REPO_ACCESS_IS_OK=no (or =yes)**
    For “Warning: The repository at location … was previously located at …”

**Comment by antiuser** [comment]
> https://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables
> **BORG_RELOCATED_REPO_ACCESS_IS_OK=no (or =yes)**
> For “Warning: The repository at location … was previously located at …”

Yes, i know this, but it will be difficult to add this line to one hundred machines.
Is there way to copy some directories from old borg backup to new borg backup?

**Comment by ThomasWaldmann** [comment]
if you're managing 100 machines, you should have (or think about) a way to automate managing them, e.g. using ansible.

you could add this env var to `.bashrc` (if using bash) of the user used to run borg. or you could change your backup script.

another method is to completely put the repo you are currently using at the same logical location (which you give as repo in the `borg create` command). if the server name stays same, path stays same and the same repo is there, borg won't see any difference.

**Comment by antiuser** [comment]
@ThomasWaldmann yes, we are thinking about ansible. All paths and location will be the same.
I want to know how to transfer repos without archives only?

**Comment by infectormp** [comment]
Repos without archives - empty repos. Just create a new one with same name and password.

**Comment by antiuser** [comment]
> Repos without archives - empty repos. Just create a new one with same name and password.

oh, thats a way. Im probe this, thanks a lot!

**Comment by ThomasWaldmann** [comment]
I think when you create a new repo, borg will notice that this is a different one and will ask.

**Comment by antiuser** [comment]
@ThomasWaldmann it will be a problem :(

**Comment by ThomasWaldmann** [comment]
if it is an option, you could delete all/most archives from original repo and then transfer that repo to new storage (same logical place).

**Comment by ThomasWaldmann** [comment]
BTW, issue title is a bit misleading.

This seems to be **not** about moving a repo "as is" to another (logical) location (repo url), but rather about creating a new empty repo at the same logical location and avoiding borg asking about whether that repo is ok.

As borg does not fully trust the server, this is problematic.

Just imagine some evil guy having access to your backup server and replacing your repo with an empty repo without you even noticing...

**Comment by antiuser** [comment]
> BTW, issue title is a bit misleading.
> 
> This seems to be **not** about moving a repo "as is" to another (logical) location (repo url), but rather about creating a new empty repo at the same logical location and avoiding borg asking about whether that repo is ok.
> 
> As borg does not fully trust the server, this is problematic.
> 
> Just imagine some evil guy having access to your backup server and replacing your repo with an empty repo without you even noticing...

for security reasons we are using SSH keys and borg without passwords and encryption

**Comment by antiuser** [comment]
Amazing! Im create one hundred repos such as borg -enone borg1.srv:/borg/instance{1..100}, shutdown old server and trying to borg create from each local servers - and its working without any notice :) Thank you so much!

**Comment by antiuser** [comment]
Another problem that we have on some nodes this is borg notify:
```
Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue? [yN] y

```

**Comment by ThomasWaldmann** [comment]
if you don't use encryption, some checks might be a bit more relaxed.

but if all clients talk to same new unencrypted repo, you should see the same "previously unknown unencrypted repository" query on all of them.
