### ISSUE TITLE
List new files of an archive?

### ISSUE THREAD

**Issue by georgjaehnig** [borgbackup/borg#5250]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## Describe the problem you're observing.

I often create a new archive that is "surprisingly" big – because I've left somewhere some temporary files that should not be in there.

My current workflow is to delete the last archive, then create it again and closely watch with files have been added.

Instead, I would like to have a simple option to just list the new files of an archive. That way I could delete the unnecessary ones, and recreate the archive – without needing to stare at the command line for a few minutes.

Is there such a command to list the new files of an archive?

**Comment by ThomasWaldmann** [comment]
Try `borg create --list --filter=AME ...`.

If you're not interested in modified files, you can drop the `M` (modified). But I'ld always keep the `E`, so you see errors.

`A` status is for added files.

**Comment by georgjaehnig** [comment]
OK, thanks! I see this is the command line option for creating an archive. But what if already created one and now what to see the new files added?
It seems `borg list` doesn't have a `--filter` option or something similar, does it?

**Comment by ThomasWaldmann** [comment]
As borg is always creating **full** archives (not *incremental/differential* archives), there is no "new file tracking" except in the moment when they are backed up (this has to do with the files cache primarily).

So, just always use the suggested `borg create` command and keep the logs in case you need them later.

There is also `borg diff`, but that is way more expensive.

**Comment by georgjaehnig** [comment]
OK, thanks!
