### ISSUE TITLE
Cannot view/set config: Repository must be local

### ISSUE THREAD

**Issue by ygoe** [borgbackup/borg#5252]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. Total 2 results in Google: An unrelated issue in this project, and your source code.

## Is this a BUG / ISSUE report or a QUESTION?

Bug/error

#### Your borg version (borg -V).

borg 1.1.11

#### Operating system (distribution) and version.

Ubuntu 18.04

#### Hardware / network configuration, and filesystems used.

* Local: ext4
* Remote: SSH/SFTP

#### How much data is handled by borg?

Nothing for this task

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg config -l "ssh://u000000@u000000.your-storagebox.de:23"
borg config -- "ssh://u000000@u000000.your-storagebox.de:23/./backup" additional_free_space
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, happens every time

#### Include any warning/errors/backtraces from the system logs

This is the output of the program:

```
usage: borg config [-h] [--critical] [--error] [--warning] [--info] [--debug]
                   [--debug-topic TOPIC] [-p] [--log-json]
                   [--lock-wait SECONDS] [--show-version] [--show-rc]
                   [--umask M] [--remote-path PATH] [--remote-ratelimit RATE]
                   [--consider-part-files] [--debug-profile FILE] [--rsh RSH]
                   [-c] [-d | -l]
                   [REPOSITORY] [NAME] [VALUE]
borg config: error: argument REPOSITORY: "ssh://u000000@u000000.your-storagebox.de:23/./backup": Repository must be local
```

I'm not sure what must be "local" here. The repository is really remote. And the backup works fine (at least it did before the remote file system was completely filled up, I'm working on this with the remote server operator).

**Comment by ThomasWaldmann** [comment]
"must be local" means that the repo must be a locally mounted directory (so `ssh:` repos won't work).

if you have your repo on a remote server accessible via ssh, just run the borg command there.
