### ISSUE TITLE
How likely is it that the option --ignore-inode would result in changes not being detected? 

### ISSUE THREAD

**Issue by steffres** [borgbackup/borg#5259]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg-linux64 1.1.10

#### Operating system (distribution) and version.

UbuntuServer 20.04 on both pull backup server and production server

#### Hardware / network configuration, and filesystems used.

backup server pulls lvm snapshot data from production server via sshfs on lan.

#### How much data is handled by borg?

160 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
/opt/borg_1.1.10/borg-linux64 \
        create --compression lz4 \
        /media/backup_user/HugeDisk/BACKUPS/BORG_1.1.10/BACKUP_MediathekServer::$(date +'%Y%m%d_%H%M')$1 \
        /media/backup_user/MediathekServer/mnt/ubuntu-lv-snap \
        /media/backup_user/MediathekServer/mnt/data-lv-snap \

```

## Describe the problem you're observing.

Due to slow performance (13 hours) I am considering experimenting with the `--ignore-inode` option. However before that, I would like to know if it is possible that changed data might not be detected and hence not being backed up. As said in the [doc](https://www.systutorials.com/docs/linux/man/1-borg/) and [here in this issue](https://github.com/borgbackup/borg/issues/2800), change detection might not work reliably. So this means that it's possible that such data would not be backed up at all? How likely would this be? And if there is a chance, perhaps it would be better in the case of using sshfs to use fuse's [`noforget` option](https://www.fsl.cs.stonybrook.edu/docs/fuse/fuse-article-appendices.html) to have stable inodes via sshfs? 

And thanks for your most awesome backup solution, it really provides some killer features.

Cheers,
Stefan

**Comment by ThomasWaldmann** [comment]
Well, usually the `ctime` is changing if file contents or file metadata has changed, so that should trigger the backup of a change quite reliably.

`size` is of course not reliable, because a file can change without changing its size. but **if** size changes, you can be pretty sure that it in fact has changed.

`inode` change is an indication of a file (a specific filename) having been replaced by another one, like `mv new original`.
so if the inode changes, there might be a content change or not. some filesystems do not have stable inode numbers, in that case you can not use inode as a trigger, because it triggers too often without meaning a real change.

**Comment by steffres** [comment]
Thank you Thomas for your clarifications.

With this it seems safe to assume then that changes will be detected reliably.

However, just to entertain the thought: So the change of a file would be not detected if 1. size stays the same 2. modification date for whatever reason is not updated at file change or reverted? (3. And even with an inode remaining unchanged)

**Comment by ThomasWaldmann** [comment]
`ctime`(which we use by default, kernel controlled, no userspace control) is much safer than `mtime` (modification time, kernel+userspace controlled).

older borg versions used mtime by default and other tools also do, but that's dangerous if some other tool does changes to a file and afterwards resets the mtime to the previous value.

**Comment by steffres** [comment]
Alright. I will use `--files-cache ctime,size` then with my sshfs mount. 

Thank you very much Thomas!
