### ISSUE TITLE
Tar export on Ubuntu 20.04 outputs @paxheader files

### ISSUE THREAD

**Issue by AntonyXSI** [borgbackup/borg#5274]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
ISSUE

## System information. For client/server mode post info for both machines.
borg 1.1.13
Ubuntu 20.04.1 LTS

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg export-tar --tar-filter="gzip -3" --strip-components 6 /var/borg/$App::$DownloadName $DownloadName.tar.gz

## Describe the problem you're observing.
Gzip/tar file contains lots of @PaxHeader files and missing file extensions.

Is there a way to force GNU export over POSIX from tar in borg? Tar is set to GNU by default on the system but I haven't found how to change this within the borg files, there seems to be something overriding this. I have borg installed and exporting ok on older Ubuntu LTS versions, and can only replicate this issue on 20.04

**Comment by ThomasWaldmann** [comment]
Sorry, I don't get what the problem is...

**Comment by AntonyXSI** [comment]
I'm still researching this myself. The export-tar command through borg appears to be using the posix format instead of gnu which is adding thousands of additional @paxheader files to the gzip file along with incomplete file extensions on some files, which makes the gzip file unusable.

I have been able to replicate this by using the --format=posix option on a tar request eg:
tar -czvf archive.tar.gz test-folder/ --format=posix

Using --format=gnu with tar should fix the above issue but I'm unable to add that option to the export-tar command, nor can I pinpoint why tar is using that format through borg. Perhaps I can create a work around with piping the extract command to gzip in the meantime.

**Comment by enkore** [comment]
It's Python's fault. Borg uses the default format of the tarfile module, which changed defaults in 3.8:

> Changed in version 3.8: The default format for new archives was changed to PAX_FORMAT from GNU_FORMAT.
