### ISSUE TITLE
Relocate repository

### ISSUE THREAD

**Issue by xor-gate** [borgbackup/borg#528]
Currently there is not option to rewrite the location of the repository and we need always to use the `BORG_RELOCATED_REPO_ACCESS_IS_OK`. I don't know if this is even possible with the current architecture of borg. But a use case would be a storage server has two different dns entries. From outside the LAN and inside the LAN. The `BORG_RELOCATED_REPO_ACCESS_IS_OK` works as expected and only it will not look pretty in the output.

**Comment by ThomasWaldmann** [comment]
I assume that you can't access the outside fqdn from the LAN. A hack could be to just resolve that fqdn to the intranet IP inside your LAN.

**Comment by xor-gate** [comment]
Yes but for example:

* LAN: <hostname>.local (using mDNS hostname)
* WAN: <hostname>.domain

LAN would be used to don't stress the router and let NAT back the packets.

**Comment by ThomasWaldmann** [comment]
If you resolve the .domain name to the .local IP inside your LAN, it will not go over your router.

**Comment by xor-gate** [comment]
You are right about that, but then borg will still be annoying the message :-)

**Comment by ThomasWaldmann** [comment]
If you always use the same fqdn, i don't think it will complain.

**Comment by xor-gate** [comment]
You are right, maybe when roaming with a client which does backups to different FQDNs there is something wrong anyway. As borg is not a clustered synchronisation tool like Syncthing.
