### ISSUE TITLE
borg mount - data included in backup but not accessible from mount when folder symlink used to include it

### ISSUE THREAD

**Issue by jonathan-molyneux** [borgbackup/borg#5282]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.1.13

#### Operating system (distribution) and version.

debian 10.5

#### Hardware / network configuration, and filesystems used.

ext4

#### How much data is handled by borg?

reproducible in demo data set

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg mount repo::backup /tmp/borg-mount/

## Describe the problem you're observing.

When creating a backup using the one file system flag, data can be included into the backup that shows up in the borg create and with borg list repo::backup but will not be accessible from borg mount repo::backup as it's parent is a link instead of a folder.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

1) create a new blank repo

2) create a folder that will be backed up e.g /tmp/borg-bug/backup

3) in /tmp/borg-bug/backup create a demo folder and file for backup e.g. /tmp/borg-bug/backup/folder/valid (copy of cpuinfo from proc but could be anything).

3) in /tmp/borg-bug/backup folder create a link to another filesystem e.g. /tmp/borg-bug/backup/other -> /tmp/borg-bug/other/
Note: The /tmp/borg-bug/other/ needs to be another filesystem (was using a loopfs ext4 for testing).

4) in the other filesystem create another folder and file for backup e.g. /tmp/borg-bug/other/folder/missing

5) create a backup including the two folders directly, but using the link for the second one, for example:
borg create --verbose --filter AME --list --stats --show-rc --one-file-system repo::backup /tmp/borg-bug/backup/ /tmp/borg-bug/backup/other/folder/
the second path is valid but it's using the link "other" which points to the "other" filesystem mount.
the backup will complete and show two files added to the archive:
Creating archive at "repo::backup"
A /tmp/borg-bug/backup/folder/valid
A /tmp/borg-bug/backup/other/folder/missing

6) you can list the backup archive using borg list repo::backup
drwxr-xr-x root   root          0 Tue, 2020-08-04 21:54:39 tmp/borg-bug/backup
lrwxrwxrwx root   root         20 Tue, 2020-08-04 21:29:59 tmp/borg-bug/backup/other -> /tmp/borg-bug/other/
drwxr-xr-x root   root          0 Tue, 2020-08-04 21:55:29 tmp/borg-bug/backup/folder
-r--r--r-- root   root      10136 Tue, 2020-08-04 19:00:05 tmp/borg-bug/backup/folder/valid
drwxr-xr-x root   root          0 Tue, 2020-08-04 19:17:44 tmp/borg-bug/backup/other/folder
-rw-r--r-- root   root   104857600 Tue, 2020-08-04 19:01:04 tmp/borg-bug/backup/other/folder/missing

7) when the backup is mounted using borg mount, your unable to access the data stored in other/folder
borg mount repo::backup /tmp/borg-mount/
find /tmp/borg-mount/      
/tmp/borg-mount/
/tmp/borg-mount/tmp
/tmp/borg-mount/tmp/borg-bug
/tmp/borg-mount/tmp/borg-bug/backup
/tmp/borg-mount/tmp/borg-bug/backup/folder
/tmp/borg-mount/tmp/borg-bug/backup/folder/valid
/tmp/borg-mount/tmp/borg-bug/backup/other
the other folder has correctly been included as a link, but due to this the data stored in other/folder isn't accessible.

8) the data can be extracted manually by bypassing the link and requesting the folder itself e.g.
borg extract repo::backup tmp/borg-bug/backup/other/folder

#### Include any warning/errors/backtraces from the system logs

No errors.

## Bounty

https://www.bountysource.com/issues/92233949-borg-mount-data-included-in-backup-but-not-accessible-from-mount-when-folder-symlink-used-to-include-it

Steps:
- reproduce (write a script only using relative pathes)
- explain
- fix

**Comment by ThomasWaldmann** [comment]
I had time to have a look at this. This at first look like a bug in how the FUSE filesystem is created, but while writing a reproducer script, I noticed that it "works as designed".

The problem is that you did not backup all filesystem objects needed.

You backed up the symlink fs object `/tmp/borg-bug/backup/other` (because it is contained in /tmp/borg-bug/backup/, which is the first of the recursion roots you have given to `borg create`).

But you did **not** backup the real directory object that this symlink is pointing to:  `/tmp/borg-bug/other` (because that is not contained in any recursion roots you have given). The fact that you have backed up some files below this not-backed-up directory does not help with that the directory object itself did not get backed up.

There is one notable difference here in how borg extract and borg mount (the FUSE fs) work:
- if you `borg extract` files and borg encounters missing parent directories, it just "makes them up" from nothing else than their name (with the consequence of potentially wrong directory metadata, like owner/group/permissions etc.).
- the FUSE fs really only contains objects that are in the archive. the symlink is broken because the symlink target is not in the archive.

**Comment by ThomasWaldmann** [comment]
Here is the (unfinished/untested) reproducer script I wrote:
```
mkdir -p testdata/borg-bug/backup/folder
touch testdata/borg-bug/backup/folder/valid
# "other" folder needs to be on different filesystem than "testdata"
mkdir -p /tmp/borg-bug/other/folder
touch /tmp/borg-bug/other/folder/missing
ln -s /tmp/borg-bug/other testdata/borg-bug/backup/other

borg init -e none repo
borg create -v --filter AME --list --stats --one-file-system repo::backup testdata/borg-bug/backup/ testdata/borg-bug/backup/other/folder/
borg list repo::backup
# here, all files SEEM to be there.

# when the backup is mounted using borg mount, your unable to access the data stored in other/folder
mkdir -p mnt
borg mount repo::backup mnt
find mnt
# here, the file "missing" is missing
```

I didn't finish/try it, because I found the explanation for the behaviour while writing it.

**Comment by ThomasWaldmann** [comment]
BTW, I think for the fuse fs, there could be even more issues (like the symlink target path not matching the target fs object path if they did not happen to be under a common base path).

**Comment by ThomasWaldmann** [comment]
OK, considering the above, guess there is nothing to fix here.

Maybe one advice about how to avoid "missing" important stuff:

If one give thes root directory (`/`) as the recursion root and just excludes all unwanted stuff, it is less likely that such problems occur. One can also use another "relatively high" in the hierarchy recursion root, as long as all important parts (all data, symlinks **and** symlink targets) are contained in that recursion root.

In general, starting from including all and only excluding known-irrelevant stuff is easier and less error-prone than only including all the relevant stuff.

**Comment by ThomasWaldmann** [comment]
Somehow related: #5680
