### ISSUE TITLE
QUESTION: Backup a debian-server to my home pc behind a router

### ISSUE THREAD

**Issue by incoggnito** [borgbackup/borg#5286]
Hiya!,

is there any easy way to use borg-backup through a reverse ssh-pipe?

     me@arch$ ssh -R 2000:localhost:22 user@remoteserver

I could reconnect to my workstation: 

     user@remoteserver$ ssh -p2000 me@localhost

Or is there any other easy way to use borg to backup a server to my local machine?

**Comment by ThomasWaldmann** [comment]
See the docs.
