### ISSUE TITLE
Excluding protected macOS directories

### ISSUE THREAD

**Issue by abendy** [borgbackup/borg#5291]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
1.1.13

#### Operating system (distribution) and version.
macOS Catalina, 10.15.6

#### Hardware / network configuration, and filesystems used.
APFS (Encrypted) -> rsync.net w/ ssh

#### How much data is handled by borg?
~20G

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
  borg create                                                   \
    --compression zlib,6                                        \
    --exclude-caches                                            \
    --exclude-from $BORG_EXCLUDES                               \
    --exclude-if-present .noborg                                \
    --filter AME                                                \
    --list                                                      \
    --one-file-system                                           \
    --patterns-from $BORG_INCLUDES                              \
    --remote-path=borg1                                         \
    --show-rc                                                   \
    --stats                                                     \
    --verbose                                                   \
    ::${BORG_BACKUP_NAME}                                       \
    2>> $BORG_LOG_FILE
```

BORG_INCLUDES:

```
R /Users/foo
- /Users/foo/Library/Autosave Information
```

## Describe the problem you're observing.

Excluding protected system files. Borg appears to be error'ing on those directories producing a non-zero exit even though I'm excluding specific directories that are protected by macOS or that I don't need to backup. I found many threads about Full Disk Access and signing binaries, I'm interested in ignoring those directories entirely.

#### Include any warning/errors/backtraces from the system logs

```
/Users/foo/Library/Autosave Information: scandir: [Errno 1] Operation not permitted: '/Users/foo/Library/Autosave Information'
E /Users/foo/Library/Autosave Information
```

**Comment by ThomasWaldmann** [comment]
Guess you want to use `!`, not `-` (see the docs for details).

Tell me if it helped or not.

**Comment by abendy** [comment]
It did, thanks. I neglected to see that in the docs. Planning to review this section again
