### ISSUE TITLE
matching files based on other attributes than filename

### ISSUE THREAD

**Issue by ReimarBauer** [borgbackup/borg#5294]
Hi there 
this is a feature request. 
I discussed this 2020-08-12 on irc with viq_ and Horrorcat and ThomasWaldmann

I have a situation where I want to delete files based on UID. A user can request deleting files because of GDPR. I can do this easily on disk.  But there are backups. In backups I can delete a directory by its name and do a recreate. 
If I know what I want to delete I could delete it by name. A deletion by UID or other attributes would be a way better to solve this.

I am also refactoring my backup workflow. However because files can always be on places not expected an easy way to remove all on some attribute is a great feature.

**Comment by ThomasWaldmann** [comment]
Adding my IRC post:

guess borg list with some output formatting option could create a list "<uid> <path>" for an archive.
that list could be used to create a patterns file, which could be used for borg recreate.
so, a bit of tweaking required, but guess that would work.

borg has a special "full match" pattern that is very efficient and should scales up to lots of patterns.

**Comment by ThomasWaldmann** [comment]
Note:
- DSGVO (de) -> GDPR (en)
- also changing issue title because removing is just an application of pattern matching.

**Comment by ThomasWaldmann** [comment]
related to #4102 (stat result has uid, so this ticket is just a special case of that one).

**Comment by ThomasWaldmann** [comment]
closing as duplicate.
