### ISSUE TITLE
Detect bit rot on the source filesystem?

### ISSUE THREAD

**Issue by tarruda** [borgbackup/borg#5296]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION / SUGGESTION / RFC

## Describe the problem you're observing.

Recently I've been reading about how zfs/btrfs deal with bit rot when reading data by reporting errors if the checksum is not matched. AFAICT it is not possible to have this kind of high-level automatic detection without using these filesystems, but I still prefer to keep using ext4 since there's a visible performance degradation when using zfs/btrfs, not to mention increased complexity when setting up new systems. I wonder however, if it is possible to achieve something similar on other filesystems by simply using borg as a backup solution.

Note that I'm aware borg already has support for detecting repository data corruption with `borg check` and even has some repair capability with `borg check --repair` (#1300, as long as the data becomes available again when creating new archives). Here I mean something different: Detect data corruption on the source of the backup, before it is written on the repository. This is best explained by describing an example (my own use case):

I currently use ext4 as the main filesystem of my laptop's SSD, and have a few remote borg repositories (independent from each other) which receive hourly backups of my important data.

If one my important files get corrupt due to SSD bit rot, it will be written to the borg repo on next backup, silently overwriting the good version on newer archives. Clearly I still have access to the good copy if I have a good archive retention policy, but if I don't notice this corruption until a couple of years later, then the bad version will overwrite the good version on all archives. I could prevent this by using zfs/btrfs as my main filesystem (borg create would fail when trying to read the corrupt file), but as I mentioned earlier, I prefer to keep using ext4 due to simplicity and performance reasons.

While this out of borg's responsibility, there might be a simple solution to the problem: Borg could look at the file modification timestamp in addition to checksum when adding it to new archives. If the file checksum differs, but the file modification timestamp is still the same, then borg can report to the user that something is wrong with the source file and refuse to create the archive, which would allow the user to restore the file from one of borg backups.

I'd be willing to get familiar with the code and implement it myself if the maintainers think this is worth having and confirm that it is possible to integrate in borg's current architecture. If a similar protection mechanism already exists in borg, then please disregard/close this issue (thanks for this great piece of software BTW).

**Comment by ThomasWaldmann** [comment]
You have to be aware that this would make borg quite slow, because it would have to always rechunk / rehash all the files (this is similar to switching off the files-cache performance-wise). So there would be a lot of IO and CPU load due to this.

If one is willing to pay that price, it would be possible to implement. But you'ld need to rather use the ctime (or configurable ctime/mtime) because mtime is too unreliable (which is why borg is using ctime for the files-cache by default since 1.1).

**Comment by tarruda** [comment]
> You have to be aware that this would make borg quite slow, because it would have to always rechunk / rehash all the files (this is similar to switching off the files-cache performance-wise). So there would be a lot of IO and CPU load due to this.

Personally I would be ok to pay the price, as I only use borg to backup important data (In my case a full initial backup only takes a couple of minutes anyway). It makes sense to hide this extra check under an optional command line switch so that it becomes an opt-in feature.

**Comment by tarruda** [comment]
@ThomasWaldmann please correct me if I'm wrong: This check only needs to be done when rebuilding the cache, no? If borg already looks at ctime and stores it in a cache, I assume that only files files that have ctime changed are read again and recomputed.

If so my scenario would not happen as long as the original cache is still present (even if the file gets corrupted, it would not be included since ctime would not change).

**Comment by ThomasWaldmann** [comment]
it would work like this:

while recursing over all files, a specific path is encountered (let's assume it is a regular file).

that path is looked up in the files cache:

cache miss:

we don't know anything about this file. it might be totally new or maybe has changed path. read / chunk / hash it and store all chunks we do not already have into the repo, update the files cache.

cache hit:

normal operation: compare timestamp, inode number, size fs vs. files cache entry.
if all still matches, we assume file is unchanged and create an archive item from current metadata (read from fs) and chunks list from the files cache. if there is a mismatch, we proceed like for a cache miss.

bitrot detect operation: compare timestamp, inode number, size as above to establish our expectation about whether the file has legitimately changed or not. in any case, we read/chunk/hash the file. then we check whether our expectation about change holds true by comparing the computed chunks id list vs. the stored chunks id list from the files cache. if expectation does not match reality, we have detected bitrot.

in case of bitrot, i would log a warning, but continue to back up all other files and then terminate with rc=1.
let's not do a fatal error and abort (rc=2) - having a current backup of all other files without bitrot might be still very useful and expected. when borg exits with warning rc, an admin has to check and evalutate the logs.

**Comment by ThomasWaldmann** [comment]
in general, without the fs supporting checksums and without ecc memory (and all data pathes somehow protected by checksums), it's a bit of a guessing game. it's not just the flash or magnetic bit (permanently) flipping, it could be also some memory bit in RAM or a bit flipping while travelling over some problematic hardware. also, we can't be sure that if we detect bitrot, the problem is in the content data. it could be also the checksum that has been corrupted and therefore does not match the data any more.

so, we can notice that we have a problem, but we can not for sure say what's corrrect and what not.

**Comment by tarruda** [comment]
> bitrot detect operation: compare timestamp, inode number, size as above to establish our expectation about whether the file has legitimately changed or not. in any case, we read/chunk/hash the file

It seems like you don't need to do anything during a "bitrot detect operation" when the cache hits, because that file is not going to be sent to the repository anyway. So it doesn't matter if it is bit rot, as long as we have a good copy in our repository we can always restore it later if the bit rot is detected.

As far as I can see, the only situation that needs to be handled is when there's a cache miss, which could happen if the borg cache is deleted. I assume that borg doesn't store the inode numbers in the repository, so you would compare only the newly computed file hash and timestamp with the same file path on a previous archive, and warn the user about it. TBH it seems reasonable to just backup the new file like normal, but leave a warning to the user so they can inspect and fix from a previous archive.

> so, we can notice that we have a problem, but we can not for sure say what's corrrect and what not.

Sure, the goal would be to inform the users that something might have happened.

**Comment by tarruda** [comment]
Here's an idea:

```
borg create --bitrot-detect=mydata-{hostname}- ::mydata-{hostname}-{now:%Y-%m-%d-%H%M} dir1 dir2...
```

What borg would do when creating `mydata-{hostname}-{now:%Y-%m-%d-%H%M}` is search for the most recent `mydata-{hostname}` archive that has each new file that had a cache miss, and report a possible error if the checksums changed but timestamp and size are still the same

**Comment by ThomasWaldmann** [comment]
I'ld rather use the files cache only and not read an old archive.

**Comment by tarruda** [comment]
> I'ld rather use the files cache only and not read an old archive.

If we use only files cache, then nothing needs to be done. As I mentioned, if borg assumes the file is unchanged, the bit rotted version will never be included in the repository.

**Comment by ThomasWaldmann** [comment]
I thought your intention was to detect bitrot early. You don't have that now.

Also, **if** you have a bitrotted file and then a legitimate change is made to it, the bitrot **and** the legitimate change will be backed up in the next borg run.

**Comment by tarruda** [comment]
> I thought your intention was to detect bitrot early. You don't have that now.

My goal was to prevent a bad/corrupted file from being written silently in the repository. If the bad file is never written and I still have in one of my backups, I can always restore it later when I detect the problem.

> Also, if you have a bitrotted file and then a legitimate change is made to it, the bitrot and the legitimate change will be backed up in the next borg run. 

True, though this would be more useful for files that are rarely accessed, such as old objects in a git repository.

Another idea came to mind: Can I have borg report the changed files when creating an archive? If there's a list of changed files after `borg create`, then I can iterate and do the check from a wrapper script.

**Comment by ThomasWaldmann** [comment]
You can use `borg create --list --filter AME ...`.

**Comment by tarruda** [comment]
I've found other solutions that use similar ideas:

- https://github.com/rfjakob/cshatag
- https://github.com/ambv/bitrot

Closing as it is become clear to me that this is better to handle outside borg. In any case, thanks for considering @ThomasWaldmann .
