### ISSUE TITLE
What is the difference of pattern types pf and pp

### ISSUE THREAD

**Issue by mstilkerich** [borgbackup/borg#5300]
Hello,

  from reading borg-patterns(1), it is not clear to me what the difference is between the pattern types pp and pf.

Sticking with the example - say I wanted to exclude root/somedir. Both pp:root/somedir and pf:root/somedir seem to have exactly the same effect, the directory and all its contents are not part of the backup.

What is the difference?

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-patterns

**Comment by mstilkerich** [comment]
I read the manpage, but I don't get the difference.

**Comment by infectormp** [comment]
In case of excluding directories, the effect is the same regardless of the selected pattern.

**Comment by mstilkerich** [comment]
So what is the difference when excluding a file? I tried that as well, both pp and pf cause the file to be excluded from backup.

**Comment by ThomasWaldmann** [comment]
The path prefix match pattern `pp:foo` will match `foobar`.

The path full match pattern `pf:foo` will not match `foobar`.

**Comment by mstilkerich** [comment]
Ok thanks, that's indeed quite a difference. It makes sense from the name "path prefix", but the description and chosen example IMO does not make it clear.

**Comment by ThomasWaldmann** [comment]
Yeah, that's right. We need a better docs here.

**Comment by lorsanta** [comment]
I was trying to solve this issue and I did some testing.  In PathPrefixPattern at the end of pattern a trailing slash is added.
https://github.com/borgbackup/borg/blob/49ce3aff64357a1995637767c7965349d6ec457b/src/borg/patterns.py#L240
So if we want to exclude root/somedir or root/somefile there is really no difference between pp and pf.
 I was thinking to solve this adding a note in the docs that states that in some cases pp and pf may have the same behaviour.

**Comment by Gu1nness** [comment]
Working on this one on the documentation part.

**Comment by remyabel** [comment]
> The path prefix match pattern pp:foo will match foobar.

Cannot reproduce this. This is the results I get from testing.

```
[test@toolbox borg]$ mkdir ~/test-backup
[test@toolbox borg]$ borg init ~/test-backup -e none
[test@toolbox borg]$ borg create ~/test-backup::test ~/borg
[test@toolbox borg]$ borg extract ~/test-backup::test -e 'pp:foo' -n --list
var/home/test/borg
var/home/test/borg/a
var/home/test/borg/b
var/home/test/borg/c
var/home/test/borg/d
var/home/test/borg/foobar
var/home/test/borg/foobar/somedir
var/home/test/borg/foobar/somedir/a
var/home/test/borg/bar
var/home/test/borg/barfoo
[test@toolbox borg]$ borg extract ~/test-backup::test -e 'pp:var/home/test/borg/foo' -n --list
var/home/test/borg
var/home/test/borg/a
var/home/test/borg/b
var/home/test/borg/c
var/home/test/borg/d
var/home/test/borg/foobar
var/home/test/borg/foobar/somedir
var/home/test/borg/foobar/somedir/a
var/home/test/borg/bar
var/home/test/borg/barfoo
[test@toolbox borg]$ borg extract ~/test-backup::test -e 'pp:var/home/test/borg/foobar' -n --list
var/home/test/borg
var/home/test/borg/a
var/home/test/borg/b
var/home/test/borg/c
var/home/test/borg/d
var/home/test/borg/bar
var/home/test/borg/barfoo
[test@toolbox borg]$ borg extract ~/test-backup::test -e 'pf:var/home/test/borg/foobar' -n --list
var/home/test/borg
var/home/test/borg/a
var/home/test/borg/b
var/home/test/borg/c
var/home/test/borg/d
var/home/test/borg/foobar/somedir
var/home/test/borg/foobar/somedir/a
var/home/test/borg/bar
var/home/test/borg/barfoo
```

So as documented the path prefix pattern will match `foobar` and its subdirectories while the path full match pattern only matches `foobar`. But I'm not sure how to get `pp:foo` to match `pp:foobar`? Feels like I'm missing something obvious.
