### ISSUE TITLE
add exception handler for "Data integrity error: More than allowed put data"

### ISSUE THREAD

**Issue by howlym** [borgbackup/borg#5307]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

## System information. For client/server mode post info for both machines.
CentOS 7.6.1810
#### Your borg version (borg -V).
borg 1.1.13
#### How much data is handled by borg?
87TB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)

sys.argv: ['/usr/bin/borg', 'create', '/backups6/roarchive::20200818092212', '/vnas00/data/roarchive', '-v', '--stats', '--one-file-system', '--show-rc', '--exclude-caches', '-e', '*.delme', '-e', '**/.cache', '--files-cache', 'ctime,size', '--numeric-owner', '--checkpoint-interval', '300']

## Describe the problem you're observing.
I was trying to backup 87TB of data, it always gets stuck around 56TB mark, then thows the error message.

```
Data integrity error: More than allowed put data [20996131 > 20971479]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 584, in do_create
    create_inner(archive, cache)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 547, in create_inner
    read_special=args.read_special, dry_run=dry_run, st=st)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 661, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 661, in _process
    read_special=read_special, dry_run=dry_run)
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 661, in _process
    read_special=read_special, dry_run=dry_run)
  [Previous line repeated 6 more times]
  File "/usr/lib64/python3.6/site-packages/borg/archiver.py", line 635, in _process
    status = archive.process_file(path, st, cache)
  File "/usr/lib64/python3.6/site-packages/borg/archive.py", line 1071, in process_file
    self.chunk_file(item, cache, self.stats, backup_io_iter(self.chunker.chunkify(fd, fh)))
  File "/usr/lib64/python3.6/site-packages/borg/archive.py", line 1003, in chunk_file
    from_chunk, part_number = self.write_part_file(item, from_chunk, part_number)
  File "/usr/lib64/python3.6/site-packages/borg/archive.py", line 981, in write_part_file
    self.write_checkpoint()
  File "/usr/lib64/python3.6/site-packages/borg/archive.py", line 478, in write_checkpoint
    self.save(self.checkpoint_name)
  File "/usr/lib64/python3.6/site-packages/borg/archive.py", line 512, in save
    self.cache.add_chunk(self.id, data, self.stats)
  File "/usr/lib64/python3.6/site-packages/borg/cache.py", line 899, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 1145, in put
    segment, offset = self.io.write_put(id, data)
  File "/usr/lib64/python3.6/site-packages/borg/repository.py", line 1545, in write_put
    raise IntegrityError('More than allowed put data [{} > {}]'.format(data_size, MAX_DATA_SIZE))
borg.helpers.IntegrityError: Data integrity error: More than allowed put data [20996131 > 20971479]

Platform: Linux vnasbak02.int.voleon.net 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64
Linux: CentOS Linux 7.6.1810 Core
Borg: 1.1.13  Python: CPython 3.6.8 msgpack: 0.5.6
PID: 15443  CWD: /usr/local/sbin
sys.argv: ['/usr/bin/borg', 'create', '/backups6/roarchive::20200818092212', '/vnas00/data/roarchive', '-v', '--stats', '--one-file-system', '--show-rc', '--exclude-caches', '-e', '*.delme', '-e', '**/.cache', '--files-cache', 'ctime,size', '--numeric-owner', '--checkpoint-interval', '300']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes
#### Include any warning/errors/backtraces from the system logs
No system logs with regard to this issue.

**Comment by ThomasWaldmann** [comment]
uhoh. that's an interesting failure, borg should never produce that big chunks.

is there anything special with your data? it seems you are the first finding this issue.

also please note that checkpoint-interval 300s is a rather bad idea if you are dealing with bigger data sets, that might add a huge overhead. if you have a rather stable connection to your repo, maybe rather use the default or an even longer interval.

**Comment by howlym** [comment]
Thanks for your advice. I'll change the interval back to default. Nothing special with my data, it just has a lot of small files and some hard links.

**Comment by ThomasWaldmann** [comment]
Is that your first borg backup of that data set?

borg maintains a "percent of max archive size used" value and displays it in `borg create --stats` and `borg info` output, iirc.

my first suspicion is that you maybe have gone beyond the limits (maybe due to the lots of little files), so the toplevel archive chunk got too big. if that is the case, borg currently can not do that, there is an open issue about this.

You could try excluding some files so the total amount of files per archive gets much lower (like 50% maybe) and have an eye on that "percentage of max. archive size used" value while you exclude less and less stuff.

**Comment by ThomasWaldmann** [comment]
see also: https://borgbackup.readthedocs.io/en/stable/internals/data-structures.html#archives for more details.

**Comment by ThomasWaldmann** [comment]
Tagged as duplicate because this is a known and documented design limitation and we already have an open issue about it.

For the same reason, it's not a bug.

**Comment by howlym** [comment]
You are right, it's been 100% utilized. 

`borg info .::20200818092212.checkpoint
Archive name: 20200818092212.checkpoint
Archive fingerprint: 25dcb5b0ad6013975778554c7c66721508a3058f5ec92847e57c359d9b088086
Comment:
Hostname: vnasbak02
Username: root
Time (start): Tue, 2020-08-18 09:22:16
Time (end): Thu, 2020-08-20 04:36:30
Duration: 1 days 19 hours 14 minutes 13.68 seconds
Number of files: 57080703
Command line: /usr/bin/borg create /backups6/roarchive::20200818092212 /vnas00/data/roarchive -v --stats --one-file-system --show-rc --exclude-caches -e '*.delme' -e '**/.cache' --files-cache ctime,size --numeric-owner --checkpoint-interval 300
Utilization of maximum supported archive size: 100%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               72.79 TB             67.99 TB             11.07 GB
All archives:              220.96 TB            205.67 TB             61.05 TB

                       Unique chunks         Total chunks
Chunk index:                70224481            235687551
`

**Comment by ThomasWaldmann** [comment]
Thanks for the confirmation!

Wow, > 57 Million files, that's quite a lot.

**Comment by jdchristensen** [comment]
Borg should handle this situation more gracefully, giving a clear error message instead of a backtrace.

**Comment by ThomasWaldmann** [comment]
Guess we could add an exception handler in `save`.

**Comment by ThomasWaldmann** [comment]
See PR #5330 - this just prints a 1 line error message and exit with rc = 2 (ERROR).
