### ISSUE TITLE
How to back up only certain files (e.g. *.jpg)

### ISSUE THREAD

**Issue by jim-collier** [borgbackup/borg#5310]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.13

#### Operating system (distribution) and version.

Ubuntu 18.04.4

#### Hardware / network configuration, and filesystems used.

Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz
16 GB RAM
ZFS 5 x 3-way mirrors, 22 TiB usable

#### How much data is handled by borg?

15 TiB

## Question

Is this possible? I can't find a reference to a command-line flag that will do this, or related FAQ, doc, or issue.

The reason I'm doing this, is to back up my most important files first, which I can get most optimally "close enough" with wildcard matching.

I understand I can generate a separate "includes" file but if there's a way to keep it native, that would be better for my use case.

Many thanks.

Update: I realize there actually is no `--files-from` flag or similar functionality (and `--patterns-from` is marked experiments - and seems a little dicey to include millions of files).

**Comment by ThomasWaldmann** [comment]
borg help patterns

**Comment by jim-collier** [comment]
Sadly, as mentioned, I'm not comfortable with the "experimental" status particularly on production data, but thanks for the suggestion.

**Comment by ThomasWaldmann** [comment]
Maybe really read borg help patterns before assuming things?

I'ld like to fix anything unclear there, but would expect the discussion starting from what is already documented.

**Comment by jim-collier** [comment]
@ThomasWaldmann Seems like we're miscommunicating. Maybe my previous reply was too long.

But I wrote at length, the shortcomings, as I see them, *specifically* of the output of `borg help patterns`. Literally, "starting from what is already documented".

Rather than saying I'm "assuming things", maybe try to understand the shortcomings that I saw as an average user, and why - which I went to some effort to think through clearly, tried to present logically - specifically from the output of `borg help patterns, Which, in fact, does not seem to be elaborated on in any other documentations, e.g. [Borg Documentation](https://borgbackup.readthedocs.io/en/stable/).

You may understand perfectly well the specific syntax and grammar expected by `--patterns-from`, as very lightly hinted at in the output in `borg help patterns`. But without that syntax and grammar being documented for users anywhere that I've been able to find, that output is opaque and not very useful. Just because I don't understand the syntax & grammar, doesn't mean I'm "assuming things".

**Comment by ThomasWaldmann** [comment]
It clearly says "full path" at quite some places and also explains what that means.

It nowhere says that the R recursion root specification makes patterns defined below it relative. Or that R means relative.

**Comment by ThomasWaldmann** [comment]
But I agree, there are some shortcomings in that part of the docs:
- usage of leading / in patterns - bug in docs or ignored by the code?
- ability of using a pattern type prefix directly in a pattern line
- scope of a P definition line
- explicitly saying that R means recursion root (starting point of recursion)
- extend the example pattern file to cover more of this

**Comment by ThomasWaldmann** [comment]
borg 1.2 can also read paths from stdin (e.g. like `find ... | borg ...`).
