### ISSUE TITLE
Remote repositories and free space

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#5313]
If I understanding correctly, repos usually should have set an `additional_free_space` in the configuration. However, I can neither set nor control this option in my GUI for remote repositories.

Then I thought, maybe I can ensure the free space from the GUI. Borg tells me how much space it already needs during a backup. But there is no feature in borg to check the free space of a repo.

Right now there are two features coming to my mind:

1. Add an option to `borg init` similar to `--append-only` that – at least for new repos – the GUI can set an `additional_free_space`. However, I would be really happy if I wouldn't have to come up with a number and just tell borg to ensure that the backup is not running out of space to prune + compact [v1.2] old stuff.

2. In general it would be nice to be able to tell the user how much space is left. So far I have seen people doing an extra sftp connection for that. But that option is not always working and seems unnecessarily complicated.

**Comment by ThomasWaldmann** [comment]
additional_free_space: did you check / try `borg config`?

free space via rpc: not sure this is in scope of borg.

free disk space is just one of many resources that one could monitor (there are also cpu load, available memory, ...).
also, it is a bit system / environment dependent, e.g. quotas could be active.

**Comment by sophie-h** [comment]
> additional_free_space: did you check / try `borg config`?

Yes. See "I can neither set nor control this option in my GUI for remote repositories." Because I can't use `borg config` on remote repos. I'm not sure that it's a good solution to do it via ssh connections.

> free space via rpc: not sure this is in scope of borg.

I totally see that this feature doesn't fit with all the other infos that borg outputs, because currently they are all about borg. However, I have seen backup scripts that only use sftp for this single information and got everything else from borg. I think this can be seen as a strong sign that this feature fits into borg.

> free disk space is just one of many resources that one could monitor (there are also cpu load, available memory, ...).

I think it's very reasonable to only care about the free space on a backup server :) I really see a problem if users suddenly run out of backup space. Maybe they want to purge old backups, maybe they want to rent more space, maybe they don't know yet. But often, it will be problematic to suddenly deal with the situation that they cannot do a backup. Therefore, having access to this information in the GUI is crucial to me.

> also, it is a bit system / environment dependent, e.g. quotas could be active.

Phew! Absolutely! I have no ideas how quotas etc. are handled. My experience is that storage hosting solutions reports the correct numbers via `df`. But I have no ideas what surprises other environments will show.

**Comment by ThomasWaldmann** [comment]
Oh, yeah, sorry, forgot about borg config only being local.

Running out of hdd space (or running out of RAM) will be discovered (late) by monitoring your borg logs for errors.
Running out of RAM can mean that your backups don't work and may affect other apps on the same system.
You could also maybe overhead some badly cooled CPU due to lzma usage.

(you see, I don't want to mutate borg into a systems monitoring tool)

I think the only question here is whether something really bad happens in the "(almost) full fs" case:
- for the borg repo, like becoming corrupted or unable to free space later (borg tries hard to avoid this)
- for the OS and other apps, like not being able to work any more due to a full fs (additional_free_space can be used for this)

**Comment by ThomasWaldmann** [comment]
See #6288.
