### ISSUE TITLE
Memory aid for passwords?

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#5314]
I don't know how much this helps users to remember their passwords, but it's a common option is to provide a free text field to store a memory aid. Would it be an option to store this in borg alongside the key, at least for repokeys?

**Comment by ThomasWaldmann** [comment]
Not sure if that is needed in borg:

If you have few passwords and a password hint would help you selecting the right one, then you likely reuse passwords for different purposes. that's a bad idea with potential to catastrophic failure.

If you don't do that, you'll likely have a password manager (or something equivalent) and then you don't need to "remember" such passwords anyway, nor do you need a hint.

Besides that, if you use borg withing a script backing up your stuff, you could of course put that password hint into the script.
