### ISSUE TITLE
Garbled output with --list and --progress

### ISSUE THREAD

**Issue by Aran-Fey** [borgbackup/borg#5316]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

1.1.13

#### Operating system (distribution) and version.

Manjaro linux 5.7.9-1

#### Hardware / network configuration, and filesystems used.

Uhh, what?

#### How much data is handled by borg?

Around 130 GB maybe? Why does that matter?

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create                              \
    --verbose                            \
    --filter AME                         \
    --list                               \
    --stats                              \
    --show-rc                            \
    --progress                           \
    --checkpoint-interval 600            \
    --compression lz4                    \
    --files-cache=mtime,size             \
                                         \
    ::'auto-{now}'                       \
    'Desktop'
```

## Describe the problem you're observing.

When the `--list` flag is combined with `--progress`, borg fills the terminal with messed-up half-overwritten lines of output. What's happening is that `--progress` prints a line like

```
70 GB O   69 GB C   50 GB D  12345 N Desktop/folder/file.txt
``` 

And when that is complete, `--list` prints

```
A Desktop/folder/file.txt
```

on top of that, leading to:

```
A Desktop/folder/file.txt D  12345 N Desktop/folder/file.txt
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Didn't you literally just make me include the command line that reproduces the problem?

#### Include any warning/errors/backtraces from the system logs

**Comment by ThomasWaldmann** [comment]
list and progress are not supposed to be used together.

**Comment by Aran-Fey** [comment]
Why not, though? `list` gives me a rough idea of which files have already been backed up, and `progress` lets me see how quickly (or slowly) large files are being uploaded. Besides, surely it can't be terribly difficult to clear or overwrite the output from `process`?

**Comment by ThomasWaldmann** [comment]
Borg only uses very simple screen control:
- it's mostly just stream-like output
- progress display is the only special thing, using just a CR (not LF or CRLF) to overwrite the same line again, so it does not scroll

So, there is no "(n)curses-like" full-screen output.

**Comment by jedie** [comment]
borg has these "checkpoint" stuff... What's about to print a block of lines with status information after every checkpoint? Informations like "--stats" one...?

**Comment by ThomasWaldmann** [comment]
@jedie how is this related to this issue?

--list outputs a (scrolling) list of filenames, --progress outputs a (stationary) display of amount/count/filename.

as long as the list option is active, everything else will quickly scroll away.

**Comment by LaurentBonnaud** [comment]
> list and progress are not supposed to be used together.

I also got caught by this.  How about outputting a warning when those options are used together?

**Comment by ThomasWaldmann** [comment]
This is already fixed. From master branch:
```
        if args.progress and getattr(args, "output_list", False) and not args.log_json:
            parser.error("Options --progress and --list do not play nicely together.")
```
