### ISSUE TITLE
Borg opens files even though it doesn't need to

### ISSUE THREAD

**Issue by kalumkalac** [borgbackup/borg#5317]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

More like a QUESTION

## Describe the problem you're observing.

I read on the doc about the way Borg detects changes on file, wether it require rechunk or not, and how we can modify that behaviour (using the `--files-cache` parameter).

However, by running `strace`, I noticed that Borg is opening every file even though it does not require a re-chunk (file is not modified). For example:

```
lstat("stack/docker-compose.yml", {st_mode=S_IFREG|0644, st_size=1644, ...}) = 0
llistxattr("stack/docker-compose.yml", "", 4096) = 0
openat(AT_FDCWD, "stack/docker-compose.yml", O_RDONLY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC) = 5
getxattr("stack/docker-compose.yml", "system.posix_acl_access", NULL, 0) = -1 ENODATA (No data available)
getxattr("stack/docker-compose.yml", "system.posix_acl_default", NULL, 0) = -1 ENODATA (No data available)
```

In comparison, `rsync` does not open the file, it just read the metadata:

```
lstat("docker-compose.yml", {st_mode=S_IFREG|0644, st_size=1644, ...}) = 0
```

Why does borg need to open the file each time ? It does not make sense since it should only read the meta-data of the file, not the file itself. This can cause a performance issue, especially for remote filesystem.

If you wonder why I bother, this is because I wanted to use Borg on a AWS Elastic File System partition. EFS has a feature which cause non recently accessed files to be moved to an infrequent access storage class, which save big $$. Borg runs daily on my server, if it opens every file even if it doesn't need to, this will cause the file to stay in the standard storage classe and EFS price will be far too high for me to use.

Could anyone explain why this open file is needed and if/how it could be avoided ? Thanks a lot.

**Comment by infectormp** [comment]
Can you put here `strace` output of `borg` with `--nobsdflags` ?

**Comment by ThomasWaldmann** [comment]
@kalumkalac what borg version do you use? 1.1.x and master branch (1.2 alpha) behave rather different in that respect.

**Comment by kalumkalac** [comment]
Hello, I just tested with the master version and even though the strace gave differents results, it still ends up opening the file.

Running with the `--nobsdflags` switch have the same results:

```
$ /home/damien/tmp/borg-env/bin/borg --version
borg 1.2.0a9.dev70+g1860a331
```

```
$ strace /home/damien/tmp/borg-env/bin/borg create --nobsdflags borg/repo/::test8 stack 2> strace_output.log
$ grep docker-compose strace_output.log
newfstatat(6, "docker-compose.yml", {st_mode=S_IFREG|0644, st_size=1645, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(6, "docker-compose.yml", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_NOATIME|O_CLOEXEC) = 7
```

```
$ strace /home/damien/tmp/borg-env/bin/borg create borg/repo/::test9 stack 2> strace_output.log
$ grep docker-compose strace_output.log
newfstatat(6, "docker-compose.yml", {st_mode=S_IFREG|0644, st_size=1645, ...}, AT_SYMLINK_NOFOLLOW) = 0
openat(6, "docker-compose.yml", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_NOATIME|O_CLOEXEC) = 7
```

**Comment by ThomasWaldmann** [comment]
master branch is expected to open files, because it tries to do as much as possible based on the file descriptor (to avoid race conditions).

if you want to analyze some perceived problem, you should look at what is done with the fd returned by open(). then it usually gets clear why the file is opened.

**Comment by ThomasWaldmann** [comment]
hmm, just re-read top post and i think we can shorten this:

if opening files is too expensive ($$$), filesystem and borg are not suited for each other.

considering the borg will be even more based on opening files in the future, this is a "wontfix".
