### ISSUE TITLE
 Connection closed by remote host

### ISSUE THREAD

**Issue by akvadrako** [borgbackup/borg#5318]
Today I have been trying to extract an archive from borgbase and haven't been able to.

## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).
1.1.13
#### Operating system (distribution) and version.
Ubuntu 20.04
#### Hardware / network configuration, and filesystems used.
Thinkpad, WiFi, ext4
#### How much data is handled by borg?
1.4GiB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg extract --verbose --debug n95rtrz9@n95rtrz9.repo.borgbase.com:repo::bf5ee96960ad-2020-09-01T16:20:16.499470

## Describe the problem you're observing.
After some time I the extract aborts with a "Connection closed by remote host" message.
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, it happens every time.
#### Include any warning/errors/backtraces from the system logs
```
data/srv/bare/devin/objects/pack/pack-1cb856ffb0ea06f3214f2b81b24fc92466b2c154.idx: attrs: [Errno 1] Operation not permitted: '<FD 3>'
RemoteRepository: 1.40 MB bytes sent, 1.41 GB bytes received, 26345 messages sent
still 16 cached responses left in RemoteRepository
Connection closed by remote host
Traceback (most recent call last):
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archiver.py", line 189, in wrapper
    return method(self, args, repository=repository, manifest=manifest, key=key, archive=archive, **kwargs)
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archiver.py", line 800, in do_extract
    archive.extract_item(item, stdout=stdout, sparse=sparse, hardlink_masters=hardlink_masters,
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archive.py", line 645, in extract_item
    for data in self.pipeline.fetch_many(ids, is_preloaded=True):
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archive.py", line 251, in fetch_many
    for id_, data in zip(ids, self.repository.get_many(ids, is_preloaded=is_preloaded)):
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/remote.py", line 937, in get_many
    for resp in self.call_many('get', [{'id': id} for id in ids], is_preloaded=is_preloaded):
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/remote.py", line 814, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archiver.py", line 4565, in main
    exit_code = archiver.run(args)
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archiver.py", line 4497, in run
    return set_ec(func(args))
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/archiver.py", line 176, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/remote.py", line 634, in __exit__
    self.rollback()
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/remote.py", line 477, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/remote.py", line 712, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/home/dev/devin/py3env/lib/python3.8/site-packages/borg/remote.py", line 814, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

Platform: Linux orac 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
Linux: Unknown Linux
Borg: 1.1.13  Python: CPython 3.8.2 msgpack: 0.5.6
PID: 963347  CWD: /home/dev/data
sys.argv: ['/home/dev/devin/py3env/bin/borg', 'extract', '--verbose', '--debug', 'n95rtrz9@n95rtrz9.repo.borgbase.com:repo::bf5ee96960ad-2020-09-01T16:20:16.499470']
SSH_ORIGINAL_COMMAND: None
```

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#why-do-i-get-connection-closed-by-remote-after-a-while

**Comment by akvadrako** [comment]
Interesting - the last message in the linked issue #636 is actually from me about a year ago.

It still seems like it could be that borgbase.com is misconfigured.

**Comment by akvadrako** [comment]
@m3nu Could you clarify if borgbase.com has the recommended SSH settings from the docs as you indicated about a year ago?

If it does it looks like this is a bug.

**Comment by jdchristensen** [comment]
The first line of the error output mentions an operation not permitted error.  Could that be the issue causing the server to crash?

**Comment by akvadrako** [comment]
I don't think so; there are thousands of those lines before and they seem to be because I'm not extracting as root.

**Comment by m3nu** [comment]
> @m3nu Could you clarify if borgbase.com has the recommended SSH settings from the docs as you indicated about a year ago?

Yes, we apply those settings on all storage servers, as I commented [here](https://github.com/borgbackup/borg/issues/636#issuecomment-520105765). There is also a more in-depth discussion in the docs: https://docs.borgbase.com/faq/#my-ssh-connection-breaks-after-a-long-backup-or-prune-operation

This is the actual Ansible part doing the change:

```
- name: Update SSH ClientAliveInterval
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ClientAliveInterval
    line: ClientAliveInterval 10
  notify: Restart sshd

- name: Update SSH ClientAliveCountMax
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ClientAliveCountMax
    line: ClientAliveCountMax 30
  notify: Restart sshd
```

Let me know if any other change would be needed to address this in the SSH configs or the docs.

**Comment by akvadrako** [comment]
Okay, I have done some more testing. It seems like it's something to do with my ISP, since I stop getting replies from the server at random times. And it works from another location.

**Comment by ThomasWaldmann** [comment]
@akvadrako besides your ISP, also consider it could be your router.
