### ISSUE TITLE
[QUESTION] exclude folder, but include one subfolder

### ISSUE THREAD

**Issue by Nono-m0le** [borgbackup/borg#5320]
Hi there,

I'm using borg 1.1.5 on Ubuntu 18.05, I would like to exclude a folder, but include only one subfolder.
On the example below: 
```
backup_test/
├── share
│   ├── all
│   ├── test1
│   ├── test2
├── otherdir
│   └── otherfile1
└── otherdir2
    └── otherfile2
```
I would like here to backup the whole content of "backup_test", but only the subfolder "share/all" into the folder "share" (aka exclude backup_test/share/test1 & backup_test/share/test2).
My idea (not working) was to use : 
borg create --exclude 'backup_test/share/*' BORG_REPO::'test' backup_test/share/all/ backup_test/

but the exclude take over the "backup_test/share/all/" directory.

Using other tools (like duplicity), allow the usage of : 
```
--include 'backup_test/share/all' 
--exclude 'backup_test/share/*' 
backup_test/
```

My question is : Is there a way to exclude all subfolder or a folder, except one ?

**Comment by Nono-m0le** [comment]
Actually, during my trials, I use --pattern, with "/" at the end. This works very well : 
`borg create --pattern=+backup_test/share/all --pattern=-backup_test/share BORG_REPO::'test' backup_test/`

**Comment by ThomasWaldmann** [comment]
@Nono-m0le you should urgently upgrade your borg to a recent version.

There might be a ppa for 18.04 with a newer version, or upgrade your whole ubuntu to a newer release (that also has a newer borg).

See the advisory in the changelog (right at the top of the file) about how to proceed after having a new borg installed.
