### ISSUE TITLE
Mounted archives not showing in macOS finder's sidebar

### ISSUE THREAD

**Issue by sunknudsen** [borgbackup/borg#5321]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Possible BUG, probable ISSUE

#### Your borg version (borg -V).

borg 1.1.13

#### Operating system (distribution) and version.

macOS Catalina 10.15.6

#### Hardware / network configuration, and filesystems used.

MacBook Pro / APFS

#### How much data is handled by borg?

Very little

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```shell
borg mount -o  /Volumes/Backup/borg /tmp/borg
```

## Describe the problem you're observing.

When I mount VeraCrypt encrypted volume, it appears on macOS’s sidebar.

This isn’t the case for Borg, why? Is there a mounting option to enable that feature?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, see above command.

**Comment by ThomasWaldmann** [comment]
Do you run `borg mount` as root? Or as the same user who uses the GUI / sidebar?

Does `ls -l /tmp/borg` work for the same user who uses the GUI / sidebar?

**Comment by sunknudsen** [comment]
@ThomasWaldmann Same user as GUI. `ls -l /tmp/borg` lists archives as expected.

**Comment by ThomasWaldmann** [comment]
I vaguely remember we already had such an issue (which is not a borg issue, but likely a macOS / fuse issue).

Can you search this issue tracker for it? Maybe it was not about sidebar, but about finder or so.

**Comment by sunknudsen** [comment]
@ThomasWaldmann Spent over an hour searching before submitting this issue, but will search some more. Thanks for your help! Perhaps this is by design... do you know if mounted archives should show up on the macOS sidebar?

**Comment by ThomasWaldmann** [comment]
I am not a macOS user, so I can't answer this.

**Comment by ThomasWaldmann** [comment]
What I meant was issue #1126 (but it says "fixed in 1.0-maint", so hopefully it is fixed for newer versions also).

But there are some other things you could try.

**Comment by ThomasWaldmann** [comment]
<img width="1591" alt="Screenshot 2023-04-02 at 15 42 09" src="https://user-images.githubusercontent.com/356103/229356668-df5b8ad8-d1f4-4d68-a2e9-235fe2ca1e5c.png">

Notable:
- it shows a smb server mount in the sidebar ("10.10.10.20") and in the main part of the window ("tw", that is the share name)
- the borg mount is not visible in the side bar, but in the main part of the window ("macFUSE Volume 0")
- the borg mount is shown as size: **zero bytes** there - is that maybe the reason why finder does not find it side-bar-worthy?

**Comment by ThomasWaldmann** [comment]
https://github.com/osxfuse/osxfuse/wiki/Mount-options#local

Read the above first and use this on your own risk:
```
borg mount -olocal REPO MOUNTPOINT
```

Then the mount shows in the sidebar of the finder.
