### ISSUE TITLE
Aborting check --repair in recover_segment() may leave segment partially recovered

### ISSUE THREAD

**Issue by elho** [borgbackup/borg#5325]
I have not tested this, so may be missing something, but looking at the code:

[`recover_segment`](https://github.com/borgbackup/borg/blob/85e6c0afd82f52182c56bfcc0b795aef33adc037/src/borg/repository.py#L1485) does rename a segment adding the [`.beforerecover`](https://github.com/borgbackup/borg/blob/85e6c0afd82f52182c56bfcc0b795aef33adc037/src/borg/repository.py#L1489) extension and then creates a new file with the original name, [**slowly**](https://github.com/borgbackup/borg/issues/4243#issuecomment-451702272) iterates over the renamed original segment, copying any parts with correct CRC over.

This code is the only occurrence of the string `beforerecover` within the source, so I conclude, that such a renamed original segment is never considered for repair again.

Thus, when a long running `borg check --repair` is interrupted for some reason and that interruption happens within above process, the original (renamed to `.beforerecover`) segment as well as the new segment, which however only has parts of the original data recovered yet, are left behind and a new run of `borg check --repair` would check than new segment only and skip on to the next, if its fine in itself (or if not (or is the new partial one always self-consistent?), maybe even overwrite the original by again renaming the partial new one to `.beforerecover`?).

Either way, with no new errors showing up, the user will assume the `borg check --repair` to have resumed just fine, when it eventually skipped over what worst case could be a large part of a segment containing data that could have been recovered.

[This comment](https://github.com/borgbackup/borg/issues/4243#issuecomment-451702455) seems to have observed that happening in practice, but seems to have went unnoticed within that question.

**Comment by elho** [comment]
Possible steps to improveme:
1. Rename the `.beforerecover` to something like `.afterecover` or `.recovered` (adding numbered extensions when that already exists to avoid ever overwriting a original segment) within `recover_segment` as soon as it is iterated over.
2. In the check code, do look for left behind `.beforerecover` files, warn/error about their existence in al cases.
3. Restart `recover_segment` on a left behind `.beforerecover` file in case of check repair.

To not overcomplicate things, 3 could be skipped (with an according warning) if nonsense/unsafe combinations of files exist, like e.g. both a `.beforerecover` and `.recovered`.

**Comment by ThomasWaldmann** [comment]
Uh, good catch. I didn't check the source yet, but guess you're right.

Another idea would be to re-use the existing pattern/code, where we have a context manager that helps with reading the original file, writing to a temp file and only if successful, atomically renaming the temp file over the original file.

Or copy instead of rename, in case we want to keep the original.

**Comment by ThomasWaldmann** [comment]
Just tweeted/tooted a PSA about "avoid interrupting borg check --repair" pointing to that PR / this issue.

To clarify: interupting only leads to a problem if `borg check --repair` happens to be in `recover_segment` part of the code (which is executed IF a segment file contains entries with bad CRC32).
