### ISSUE TITLE
Request: add size, total files, duration in borg list repository archives

### ISSUE THREAD

**Issue by biji** [borgbackup/borg#5328]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.13

#### Operating system (distribution) and version.

compile

## Describe the problem you're observing.

Please add add `size`, `Number of files`, and `duration` while listing repository archives, to quickly show overview if backup success or not. Currently we have to call `borg list` then `borg info` for each backups to check those details

Thanks

**Comment by pgerber** [comment]
There are some workarounds you might be interested in.

You can show the info for all archives (can be very slow):

```
$ borg info --glob '*'
```
Or the N last archives:

```
$ borg info --last 5
```

You can also use `--json` in combination with `jq` to make the output a bit more readable:

```
$ borg info --json --last 3 | jq '.archives[]|{"name": .name, "files": .stats.nfiles, "size": (.stats.original_size/1024/1024|floor|tostring + " MiB"), "duration": (.duration|floor|tostring + " seconds")}'
{
  "name": "main-2020-09-25T13:59:11Z",
  "files": 288115,
  "size": "8339 MiB",
  "duration": "144 seconds"
}
{
  "name": "main-2020-09-25T15:56:11Z",
  "files": 288115,
  "size": "8339 MiB",
  "duration": "142 seconds"
}
{
  "name": "main-2020-09-26T07:52:12Z",
  "files": 288135,
  "size": "8339 MiB",
  "duration": "89 seconds"
}
```

**Comment by zhum** [comment]
I prefer to get some stats from borg just after backup and pruning. I try to import borg stats into DB and visualize it via Grafana and now it is like a hell...
Here are my suggestions for format (just all from standard output, but **formatted right**):
{
  "duration": 125,
  "start": "2021-11-03 03:35:06",
  "end": "2021-11-03 03:37:11",
  "files": 812661,
  "name": "my-arch-monday",
  "fingerprint": "123abcd",
  "original size mb": 123444,
  "compressed size mb": 90123,
  "deduplicated size mb": 5999,
  "all size mb": 888123,
  "all compressed size mb": 901123,
  "all deduplicated size mb": 51999,
  "status": 0,
  "errors": []
}
for pruning:
{
  "start": "2021-11-03 04:35:06",
  "end": "2021-11-03 04:45:06",
  "kept": 9,
  "pruned": 1,
  "kept list": ["my-arch-02", ...],
  "pruned list": ["my-arch-01"]
  "status": 0,
  "errors": []
}

**Comment by ThomasWaldmann** [comment]
in master branch (borg2), I recently added placeholders `size` and `nfiles`, so `borg rlist --format=...` can use them.

not sure about the duration (but you shouldn't use that to differentiate between success and failure anyway, that's what the `borg create` rc and log is for).
