### ISSUE TITLE
The meaning of "statistical medium".

### ISSUE THREAD

**Issue by j77h** [borgbackup/borg#5336]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

A request for clarification of a term in the documentation.

## Details

This appears at a few places in the documentation:
"HASH_MASK_BITS = 21 (**statistical medium** chunk size ~= 2^21 B = 2 MiB)"

At first I thought that by 'medi **_um_**' it meant 'medi **_an_**', but in another place it says
"producing chunks of 2^HASH_MASK_BITS Bytes on **_average_**",
and average usually means 'arithmetic mean'.

Can you say which measure of '[central tendency](https://en.wikipedia.org/wiki/Central_tendency)' is the intended/correct meaning of 'statistical medium'?

When I know which it means, will I be able to choose my chunker params any better? Not sure about that ... ;)

**Comment by ThomasWaldmann** [comment]
I guess saying "on average" would be the easiest.

I am not totally sure about the distribution of chunk sizes coming out of the chunker though.

**Comment by Gu1nness** [comment]
So the sentence `HASH_MASK_BITS = 21 (statistical medium chunk size ~= 2^21 B = 2 MiB)`
would become `HASH_MASK_BITS = 21 (average chunk size ~= 2^21 B = 2 MiB)`?

If so I can provide a patch soon.

**Comment by hashbackup** [comment]
A good chunker will generate a consistent average chunk size, but having a minimum and maximum chunk size skews things.  For example, min/avg/max = 2/2/2 will have an average chunk size of 2 (fixed chunk size), 2/2/4 will have an average chunk size > 2, and 1/2/2 will have an average chunk size < 2.  Intuitively it seems if the min and max are symmetric, like 4/8/12, the mean would be 8, but I don't know that is true.

I barely passed probability in engineering school, but for those who did, here's an article: https://en.wikipedia.org/wiki/Truncated_distribution

**Comment by ThomasWaldmann** [comment]
Maybe we could just talk about a "target chunk size". That is less likely to be mathematically wrong.

**Comment by Gu1nness** [comment]
Sure
Patch incoming tonight.

**Comment by Gu1nness** [comment]
(Sorry, emergency yesterday night, and not available before monday I guess, except in some edge cases)
