### ISSUE TITLE
Different passwords for backup and restore

### ISSUE THREAD

**Issue by edgimar** [borgbackup/borg#5337]
I would like to have a way for multiple computers to backup to a single remote repository (all using the same 'backup' password, and thus allowing for deduplication across machines), but that none of those computers would be able to restore from the repository without a 'restore' password.  The reason for this is to permit automated backups without any concern that one compromised backed-up computer will result in the data from all of the backed-up computers being accessible.  If the 'restore' password is separate from the backup password, and if this restore password is kept safe and not on any of the computers that are being backed up, then all of the data of these computers will be at least less easy to compromise.

Is this already achievable somehow?  I didn't notice anything in the documentation / FAQ that was relevant.

## Is this a BUG / ISSUE report or a QUESTION?

Question

**Comment by ThomasWaldmann** [comment]
the password is for unlocking (decrypting) the key material borg is using.

after unlocking, it has the AES key (symmetric: same key for encrypting and decrypting), the MAC key (for authenticating data) and the chunker seed (random).

you see, it is symmetric, so being able to backup (encrypt) means also being able to decrypt (and thus, restore).

if you share a repo between clients, it means full trust between those.
there are also some other issues with sharing a repo, see the FAQ.

if any of these are a problem, just do not share a repo. you will still get a lot of historical and within-host dedup.

as this is a quite fundamental thing, this is a "wontfix" for now.

**Comment by ThomasWaldmann** [comment]
News in master branch: `BORG_REPO_PERMISSIONS` feature now allows `write-only` repositories. 

Using `.ssh/authorized_keys`, this can be enabled for normal backup operations using some ssh "backup keys". For restoring and also for repository maintenance, there need to be addtl. entries using e.g. `read-only` or `all` permissions.
