### ISSUE TITLE
Mounting Snapshots and incremental backups

### ISSUE THREAD

**Issue by 8FordPrefect8** [borgbackup/borg#5353]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question
#### Your borg version (borg -V).
1.1.9
#### Operating system (distribution) and version.
Debian stable
#### Hardware / network configuration, and filesystems used.
ZFS
#### How much data is handled by borg?
~5TB
## Describe the problem you're observing.

I started this year with my first home build server. It runs debian stable and I use zfs for my files. After checking different solutions I went with borg and played around with some test repos. So far I only implemented a script for USB-Backups but I have plans to expend this to a backup server and remote backups, when I find time and when I solved my current Issue with USB-Backups.

Since the amount of data is big and I am afraid I might change something while later automated backups are running I had the idea of following process for my backup script. When started a zfs-snapshot is created. The snapshot is then mounted and a backup of the mounted snapshot is created. After the backup is done and a check is performed, the snapshot is unmounted and deleted. I tested everything and did some weeks ago an initial Backup.
Recently I performed a second backup with only some documents of some MB added.  It took 6 hours to do this backup via USB. This would make daily backups over the internet impossible. So I wondered if I have some problem and found this.
https://github.com/borgbackup/borg/issues/3067

Is borg recognizing my files as new because of the process of creating snapshots and mounting them? If so, what can I do to improve the situation?
Here you can see my script and a recent report:
https://pastebin.com/Nk7ZcV6g

https://pastebin.com/Pc1hSM7u

**Comment by 8FordPrefect8** [comment]
I am ultra sorry about the messed up post. But apparently I am to stupid to work out how to do it and the system is not accepting my created text files.

**Comment by ThomasWaldmann** [comment]
There is a help and a preview when editing a post on github.

BTW, your borg is too old, you should use >= 1.1.11, see changelog, esp. the advisory at the top of the changelog.

**Comment by 8FordPrefect8** [comment]
But there seems to be nothing like a code box or something that just displays text unformatted.

Hmm I checked my Server and run apt update and upgrade. 1.1.9 is the newest version in the official debian repos.

**Comment by ThomasWaldmann** [comment]
You can use `borg create --list --filter=AME ...` to find out which files it considers modified.

If that are unexpectedly many and unchanged files appear as M)odified, then the files cache is not working as it should for you. See the description of the `--files-cache` option and use `stat` to find out what triggers the cache miss.

https://borgbackup.readthedocs.io/en/stable/faq.html#i-am-seeing-a-added-status-for-an-unchanged-file

https://borgbackup.readthedocs.io/en/stable/faq.html#it-always-chunks-all-my-files-even-unchanged-ones

https://borgbackup.readthedocs.io/en/stable/usage/create.html?highlight=files%20cache

**Comment by ThomasWaldmann** [comment]
There is a newer borg in debian backport and you can also use the latest "fat binary" from us, see github releases.

**Comment by 8FordPrefect8** [comment]
Thanks I will have a look at it and get the newer version. I will also have a look at the links posted.
But from your response I get that in principle the idea of creating and mounting snapshots for the backup shouldn't confuse the borg cache, correct?

**Comment by 8FordPrefect8** [comment]
So I read a bit over your links. I saw one thing that might be a problem.
It's said the cache of a file determines whether it's regarded as new. And that varying snapshot names or mount points might be an issue.
In my case the name of the snapshot is varying. But the name of the mount point not. So if a cache of the file is created. Will it differ because of the snapshot name, although the mount point and file path is all the same?
Since the snapshot is destroyed even if a backup fails there is no need to have the timestamp in it and I could change that if that's the issue.

**Comment by ThomasWaldmann** [comment]
borg is only interested in full pathes, ctime, inode number and size and they need to stay stable if the file did not change.

**Comment by 8FordPrefect8** [comment]
Currently I am running my skript again, as I wanted to check if it's taking again so much time. It seems it is. I checked the inode number of files and folders in one folder on the mounted snapshot and in the pool and they are identical. So I think it's the same for the previous snapshots too. The same for the timing with ls -lc. Size is of course also the same.
With the full path I am not sure. Does borg see that the file path of the mounted snapshot is not the "real" filepath, when cache is calculated?

Once it's done and I mounted my USB-HDD manually again. Can I use the comment with the --list option as a dry run to make it maybe faster?

**Comment by ThomasWaldmann** [comment]
If you always mount your snapshot to e.g. `/mnt/snapshot`, so that the full path is e.g. `/mnt/snapshot/etc/passwd`, changing pathes should not be an issue.

**Comment by ThomasWaldmann** [comment]
Not sure whether dry-run is helpful. It will show what files it considers for backup, but it does not attempt to really back them up, so guess it will not do a files cache lookup nor log the result.

**Comment by ThomasWaldmann** [comment]
But you can just use a small subset of your data to do your experiments more quickly.

**Comment by 8FordPrefect8** [comment]
Ah ok. So far I head only the intention to do always full backups, because thats the logical thing for me to do.
But if I want to see whats happening, I could create an archive with maybe just one folder for fast testing. So that means I could use the very same repo and create a different chain of archives for e.g. the server os filestructure.
So instead of my:
borg --show-version -v create --stats --compression lz4 $BorgRepo::$BackupName $MountDir
I could run
borg --show-version -v create --stats --compression lz4 $BorgRepo::$BackupName $MountDir/folder/subfolder/...

That will speed up things a lot.

BTW: I really appreciate your work. So far it seems really cool to me. I only had experience with Synology-Backuptools so far.

**Comment by 8FordPrefect8** [comment]
I read about the --files-cache option. So I could define a different way to do this and see whether it has some effect. But how should the --stats option help me? I already have the --stats option in my script.

**Comment by 8FordPrefect8** [comment]
Oh man, I am such a retard!

I did a closer look again on the timestamps of my backup report that I linked in the paste.bin in the modified starting post.
I only looked at the complete time of the script and overlooked that I do several things with it. The actual backup time is even written down explicitly and it was like 21 seconds. Which is amazing considering the huge dataset. What lasted 6 hours was the check on the repository.

Thanks a lot for your help and enlightment. Maybe a closing question. I am planning on having a smaller subset of around 1-2TB on an online server and wanna do daily backups. Is there an easy way to do an estimate on how long a check will take with respect to bandwidth? I guess it would be good to avoid conflicts because a backup might not be possible if the check is running and vice versa.

**Comment by ThomasWaldmann** [comment]
Ah, that explains it. :-)

You don't need to run check after every backup (assuming that your hardware behaves rather stable), maybe rather once a week or once a month. Also, you could limit the archives check to the last few archives if you only want to test the recently added stuff. Testing all now and then is a good idea though.

**Comment by 8FordPrefect8** [comment]
For the USB I decided to do this every time as I tend o do this randomly. For automated network I already have a test in my skript to chek for a specific week day :). Tanks for the hint with latest archives.
