### ISSUE TITLE
Borg mount - mounted dir has only question marks for permissions/ownership

### ISSUE THREAD

**Issue by james-cook** [borgbackup/borg#5354]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.
Client server are the same machine, local borg to local drive, all ext4.

#### Your borg version (borg -V).
1.1.11

#### Operating system (distribution) and version.
Raspian buster lite, kernel 5.4.51,
Openmediavault 5 is installed on the machine
 
#### Hardware / network configuration, and filesystems used.
Raspberry pi 4, 4gb ram
Borg etc is all local.
Raspi4 directory is shared via smb to W10 machine on local closed network.

#### How much data is handled by borg?
1.2TB deduped to 723GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
sudo borg mount /localpath/repo::archive.name /mount/directory 

## Describe the problem you're observing.
Prior to command,ls of /mount/directory shows
drwxrwsrwx pi users directory 

After mount cmd
d?????????? ? ? directory 
cd directory gives permission denied
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I added a+w and a+x to the ORIGINAL directory
This did not change anything
I tried doing the same to the mounted directory
sudo chmod a+w directory 
This gives: read-only file system, and nothing is changed

sudo ls -alR directory does show the contents expected. 

#### Include any warning/errors/backtraces from the system logs

I am probably just missing something simple

**Comment by ThomasWaldmann** [comment]
Do you use the same user for `borg mount` and `ls`?

fuse is a bit special with permissions, see the fuse docs / man page, search for `allow_other`.

BTW, the fuse fs built by borg mount is read-only, so you can not change stuff there, including the mountpoint path while it is mounted.

**Comment by james-cook** [comment]
> Do you use the same user for borg mount and ls?
That was my blind spot!
Thanks.

sudo borg mount -o allow_other ... (as above)

works fine.

Thanks for your superfast tips
