### ISSUE TITLE
"terminating with warning status, rc 1

### ISSUE THREAD

**Issue by Gooberpatrol66** [borgbackup/borg#5360]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
.borg-real 1.1.13

#### Operating system (distribution) and version.
guix

#### Hardware / network configuration, and filesystems used.
ssh, btrfs

#### How much data is handled by borg?
4gb

## Describe the problem you're observing.
I ran this script https://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups, and it said there were warnings, but a ctrl+f for WARNING in the output returned nothing

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Seemed to only happen during the first run?

**Comment by ThomasWaldmann** [comment]
Guess the logger might not be configured to also output the log level, so maybe just read the output?

**Comment by ThomasWaldmann** [comment]
That said, the logger **is configurable**, if you prefer having ERROR, WARNING, INFO, DEBUG in every log message (also timestamps are possible), see the docs.
