### ISSUE TITLE
prune: keeping last X number of backups

### ISSUE THREAD

**Issue by shartge** [borgbackup/borg#537]
`prune` currently allows one to specify to keep all backups created inside a time interval via `--keep-within` or a more complex regime via `-H -d -w -m -y`. But what is missing (and what I need right now) is the possibility to keep the last X number of backups disregarding any time interval: `--keep-last N`

**Comment by jdchristensen** [comment]
If you don't back up more than once an hour, then -H N would be equivalent.  (Hours without backups don't count towards the total.)

**Comment by shartge** [comment]
In this case I use borg to backup several VMs. Sometimes I backup multiple times an hour, sometimes I don't backup for several days. I just want to keep the last 30 (or so) backups around without accidentally deleting one (which then later turns out to be the important one) because it was the first of two backups during one hour.

**Comment by ThomasWaldmann** [comment]
well, assuming you backed up 30 times in a single hour, would you just want to keep these 30 backups and delete the one from the hour before and from yesterday?

**Comment by shartge** [comment]
In this case: yes. I always want to keep the last X backups.

I see that this option conflicts with `--keep-within` and the other time-based pruning options, which can be combined.

**Comment by vjay82** [comment]
I would like this too.
I want to backup to a local server which then transmits the backups to an offsite location. The offsite location has only limited space available so I'd like to write a script that checks the folder size and calls prune with a decremented count until it fits. If you like to add a --keep-within XX MB size option, that would be nice too but would rather raise other questions for what to throw.

**Comment by frispete** [comment]
I think, that while the prune options are very sophisticated, this scheme misses the most simple cases.
In my use case, it's a bunch of VMs, that are used on a **very irregular** base. Any time based prune policy will fail sooner or later, given, the backup task is: "just keep a certain number of revisions, no matter how old they are".

Also, I would like to note, that the documentation for pruning shows: it is complex to explain and to use. As time limited, as most of us are, it's hard to swallow in a short time, when getting started with borg. A simple --keep # option would help to satisfy the simple needs here, and leave the complex scheme for later (when it's really needed).

So, what do you think, would adding a --keep # option be acceptable, given, I would take care of the initial implementation?

**Comment by ThomasWaldmann** [comment]
From the comments above, one could conclude that --keep N is equivalent to --keep-<small_timeunit> N (e.g. we could just add minutes and seconds to existing theme). So it could be done by same mechanism and also would not cause any problem if mixed. Needs checking.

I agree that for some simple cases this is useful. It doesn't help with grasping the more complex scheme though and you will need the more complex scheme in many cases (as just keeping last N is often a bad option).

**Comment by ThomasWaldmann** [comment]
See PR #941.
