### ISSUE TITLE
check python 3.9

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5372]
python 3.9.0 is soon to be released.

check if borg works on py39, try manually and also run our tests.

add it to tox.ini, travis-ci, vagrant boxes, setup.py (metadata).

**Comment by ernestoarbitrio** [comment]
I did it in here https://github.com/borgbackup/borg/pull/5373 but travis fails on python 3.9 job cause of `llfuse` installation fails. I even add `SKIPFUSE=true` on the related job but no way, same failure.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/master/.travis/install.sh#L66 guess there is a bug.

first it checks SKIPFUSE and strips the requirements file that only has llfuse.
But a few lines below, it does pip install -e .[fuse] which installs borg with the fuse extra.

So, guess if SKIPFUSE then it should just do `pip install -e .`.

**Comment by ThomasWaldmann** [comment]
Looks like llfuse pypi package has a pre-cythonized llfuse.c from 2019 inside, which is not python 3.9 compatible. :-(

Also, llfuse is not maintained any more.

**Comment by ThomasWaldmann** [comment]
https://github.com/python-llfuse/python-llfuse/issues/24 llfuse issue.

**Comment by infectormp** [comment]
python 3.9.0 was released yesterday

**Comment by ThomasWaldmann** [comment]
@infectormp I already added it to master branch testing and there is a backport PR for 1.1-maint pending.

llfuse caused a bit more work than expected...

**Comment by ThomasWaldmann** [comment]
fixed by #5373 and #5389.
