### ISSUE TITLE
Demo asciinema videos are truncated at the right using firefox

### ISSUE THREAD

**Issue by marcwittke** [borgbackup/borg#5386]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

issue with documentation

## Describe the problem you're observing.

![image](https://user-images.githubusercontent.com/4075651/95029672-42216f00-0680-11eb-9340-a90b764ce1e2.png)

I fiddled half an hour around with the shell commands and finally installed chromium to see that I need to separate the backup set from the repo by two colons. Well, not that kind of an issue, and I knew that I was missing something important and also knew how to mitigate the issue, but for a newcomer this is a really sad experience, when not even the very first howto video can be reproduced

**Comment by ThomasWaldmann** [comment]
I just tried the basic usage demo with firefox 78.3.0esr and it worked for me, nothing truncated / cut.

**Comment by ThomasWaldmann** [comment]
Can somebody try to reproduce this with a current firefox and report their results?

**Comment by ThomasWaldmann** [comment]
The important line in the screenshot in the top post should look like that:
```
$ # So now, let's create our first (compressed) backup.
$ borg create --stats --progress --compression lz4 /media/backup/borgdemo::backup1 Wallpaper   
```

**Comment by ThomasWaldmann** [comment]
I also tried to reproduce with a current firefox (80/81), it worked for me.
