### ISSUE TITLE
pruning output folder size is different from actual folder size

### ISSUE THREAD

**Issue by alfredonodo** [borgbackup/borg#5387]
Hi,
I have a problem/question with borg 1.1.5 on ubuntu server 18.04. I already checked the documentation without finding a similar issue. Moreover, I have other machines where borg works without any issue with the same commands.
In few words, borg output after daily pruning is different than actual folder size.
I'm using the following command:
```
borg init --encryption=repokey-blake2 repository_path
borg create -v --list --filter=AME --progress --stats --exclude-caches --compression lzma,9 destination_folder source_folder
borg prune -v --list --save-space --stats --force --keep-daily=3 --prefix='{hostname}-' repository_path
```
There are not any error, borg does not delete the old files even if the output show it.

**Comment by ThomasWaldmann** [comment]
Please reproduce with a current borg version, like 1.1.13.

Also, please be more precise, you did not show the actual "difference".

**Comment by pachainti** [comment]
Hi,
the latest version on ubuntu 18.04 is 1.1.5 while the latest version available by adding [this PPA](https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup) is 1.1.11. So I installed it, but the result is the same.

------------------------------------------------------------------------------                                                                                                                                     
```
Archive name: server-root-2020-10-05-14:29:01
Number of files: 37365
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               12.61 GB             10.37 GB              6.41 MB
All archives:               60.04 GB             49.25 GB             18.06 GB

                       Unique chunks         Total chunks
Chunk index:                   42061               157101
------------------------------------------------------------------------------
Borg pruning old backup
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:              -15.03 GB            -12.75 GB            -53.40 MB
All archives:               45.02 GB             36.50 GB             18.00 GB

                       Unique chunks         Total chunks
Chunk index:                   41925               119055
------------------------------------------------------------------------------
```
The actual size should be 36.5 GB non 45.02 GB.

**Comment by alfredonodo** [comment]
Hi,
the latest version on ubuntu 18.04 is 1.1.5 while the latest version available by adding [this PPA](https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup) is 1.1.11. So I installed it, but the result is the same.

------------------------------------------------------------------------------                                                                                                                                     
```
Archive name: server-root-2020-10-05-14:29:01
Number of files: 37365
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               12.61 GB             10.37 GB              6.41 MB
All archives:               60.04 GB             49.25 GB             18.06 GB

                       Unique chunks         Total chunks
Chunk index:                   42061               157101
------------------------------------------------------------------------------
```

Borg pruning old backup
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:              -15.03 GB            -12.75 GB            -53.40 MB
All archives:               45.02 GB             36.50 GB             18.00 GB

                       Unique chunks         Total chunks
Chunk index:                   41925               119055
------------------------------------------------------------------------------
```

The actual size should be 36.5 GB non 45.02 GB.

**Comment by ThomasWaldmann** [comment]
I still don't get what you mean / what the issue is. Looks pretty consistent to me.

**Comment by ThomasWaldmann** [comment]
You talk about "folders" - do you mean "archives"?

**Comment by alfredonodo** [comment]
My question is: why is the archive/folder size displayed by borg different from the archive/folder size displayed by the operating system?

**Comment by ThomasWaldmann** [comment]
The `repository/data/` directory size should be approximately what you see for "all archives" under "deduplicated size" (plus filesystem overhead).

The `repository/` directory size is a bit bigger, because there is the repo index and some other files in there also.

**Comment by alfredonodo** [comment]
As you can see this is almost 3 times the deduplicated size.
```
du -sh borg_folder
52G	borg_folder
```
I have other machines where the size of the borg_folder is more or less the same of that of deduplicated.
For this reason I'm reporting this as a possible bug.

**Comment by infectormp** [comment]
Show us `du -sh borg_folder/data`

**Comment by ThomasWaldmann** [comment]
Also check if the repo is `append-only`.

**Comment by alfredonodo** [comment]
```
du -sh borg_folder/data
52G	borg_folder/data
```
The repository is configured as follow: 
`borg init --encryption=repokey-blake2 repository_path`
and this is the only difference with the other machines:
`borg init --encryption=repokey repository_path`

**Comment by ThomasWaldmann** [comment]
`-blake2` just changes how the MAC is computed. Rather unlikely that this influence space usage or related bugs.

**Comment by alfredonodo** [comment]
Right, but it is the only difference. Any idea about what to check?

**Comment by ThomasWaldmann** [comment]
What does `borg check [--repair]` say?

**Comment by ThomasWaldmann** [comment]
You can also manually look into the directory, if you find something strange there.

**Comment by alfredonodo** [comment]
`borg check --repair borg_backup`
It worked :)

```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               14.80 GB             12.53 GB              2.22 GB
All archives:               55.34 GB             46.29 GB             20.23 GB

                       Unique chunks         Total chunks
Chunk index:                   44280               155775
------------------------------------------------------------------------------
```

Borg listing backup
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:              -12.63 GB            -10.37 GB            -10.00 MB
All archives:               42.71 GB             35.91 GB             20.22 GB

                       Unique chunks         Total chunks
Chunk index:                   44197               117796
------------------------------------------------------------------------------
```
Is it safe to use check --repair? Or I can loose my data?

```
'check --repair' is an experimental feature that might result in data loss.
Type 'YES' if you understand this and want to continue: YES
```

**Comment by ThomasWaldmann** [comment]
What do you mean by "it worked"? is the borg stats now corresponding to `du` output?

**Comment by alfredonodo** [comment]
> What do you mean by "it worked"? is the borg stats now corresponding to `du` output?

Yes

**Comment by ThomasWaldmann** [comment]
looks like solved.

**Comment by alfredonodo** [comment]
Right, just a question: is it common to have to repair the repository in order to have the right folder size? Or is an exception?

**Comment by ThomasWaldmann** [comment]
No, guess that is not common.

**Comment by alfredonodo** [comment]
Hi,
I created again two repositories with the same parameters except for encryption:
```
borg init --encryption=repokey-blake2 repository_path
borg init --encryption=repokey repository_path
```

```
borg create -v --list --filter=AME --progress --stats --exclude-caches --compression lzma,9 destination_folder source_folder
borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repository_path
```

Now I have again the same problem as before for both the repository.

After pruning
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:              -14.16 GB            -11.80 GB             -2.44 GB
All archives:               14.19 GB             11.83 GB             11.77 GB

                       Unique chunks         Total chunks
Chunk index:                   49391                53800
------------------------------------------------------------------------------
```

```
du -sh borg_folder1/data
69G	borg_folder1/data
```

After pruning

```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:              -14.19 GB            -11.83 GB            -10.21 MB
All archives:               14.19 GB             11.83 GB             11.78 GB

                       Unique chunks         Total chunks
Chunk index:                   49164                53544
------------------------------------------------------------------------------
```

```
du -sh borg_folder2/data
40G	borg_folder2/data
```

Do I have to repair both repository again?
`borg 1.1.14`

**Comment by ThomasWaldmann** [comment]
Side note:

Do not use lzma,9 - it makes no sense (does not compress better) and just consumes a lot of cpu.

The maximum for lzma is lzma,6 due to the size of the borg chunks (usual target size is ~2MiB).

**Comment by ThomasWaldmann** [comment]
Another side note:

`--keep-daily=1` as only prune "keep" option is a bit unusual.

usually people keep more than 1 archive (esp. considering that does not cost a lot of space due to deduplication). also, usually also the other `--keep-X` (X=weekly, montly, yearly) are used to not only have the latest stuff.

But, theoretically, this of course should not cause any issue in the borg repo. You just have few backups / short history...

**Comment by ThomasWaldmann** [comment]
The easiest explanation for you disk usage issue would be that the borg repo is operated in `append-only` mode.

Check:
- `repo/config` file whether it has append_only = 1 (or so) in there
- if you run client/server via ssh, check if the ssh forced command on the borg serve side enforces append-only (usually configured in `.ssh/authorized_keys`)

**Comment by ThomasWaldmann** [comment]
Another explanation could be the `borg prune` command not running up to its normal end, but getting interrupted somehow before it internally calls `compact_segments()`.

**Comment by alfredonodo** [comment]
Thank you for your suggestions. I do not mind about CPU, since each backup is executed two times a day. I mind about space, what is the [best compression option](https://manpages.debian.org/testing/borgbackup/borg-compression.1.en.html) in terms of space usage?
I usually specify --keep-daily=7 --keep-weekly=4 --keep-monthly=6, but since borg consumes all my space, I removed the multiple archives.
For both repositories: 
```
cat config 
[repository]
version = 1
segments_per_dir = 1000
max_segment_size = 524288000
append_only = 0
storage_quota = 0
additional_free_space = 0
```
Borg prune runs well and the previous outputs come from it.
The output of borg is synchronized with a cloud backup, but I do not think that it could be a problem. I have many other borg repository synchronized with the same cloud and all works well.

**Comment by ThomasWaldmann** [comment]
What's the best compression for you potentially depends on your data, so you have to find out yourself.

In general, zstd is a very modern algorithm (much newer than lzma) and covers a wide range of compression levels.

But if you stay with lzma, go down to level 6, for borg it will compress as good as 9 and consume less time and power.

So, do I understand correctly, that the borg repo is local (not via ssh)?

**Comment by alfredonodo** [comment]
The repository is on remote server to which I can connect via ssh or via remote desktop. The repository is then synchronized to a common cloud.

**Comment by ThomasWaldmann** [comment]
if you run client/server via ssh, check if the ssh forced command on the borg serve side enforces append-only (usually configured in .ssh/authorized_keys).

did you check that?

**Comment by alfredonodo** [comment]
Hi,
on my authorized_keys there are just keys without any configuration parameters:
```
ssh-dss key user@hostname
ssh-rsa key user@hostname
```
The backup is executed via a script with cron: `crontab -e` (root user)
```
00 02 * * * /path/borg_script1.sh
00 14 * * * /path/borg_script2.sh
```
It could be something related to a different user (manual logged user and cron root user) that creates the backup? I do not think so, I created again two repositories and I have just one backup.
```
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath1
Keeping archive: server-username-2020-11-29-02:01:37
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               14.49 GB             12.11 GB             12.06 GB

                       Unique chunks         Total chunks
Chunk index:                   42123                43711
------------------------------------------------------------------------------
du -sh repositoryPath1/data
24G	repositoryPath1/data
```

```
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath2
Keeping archive: server-username-2020-11-28-14:01:34
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               14.48 GB             12.10 GB             12.03 GB

                       Unique chunks         Total chunks
Chunk index:                   41572                42886
------------------------------------------------------------------------------

du -sh repositoryPath1/data
31G	repositoryPath1/data
```

**Comment by ThomasWaldmann** [comment]
I've no idea about what that could be.

So, one approach to proceed would be that you create a script that reproduces the issue in the most simple way possible:
- preferably only using relative pathes
- preferably with a most simple borg invocation
- preferably with a local repo

This is so anybody can easily reproduce without much effort.

**Comment by someone-somenet-org** [comment]
Just came across this too on almost all of my repos. This happens even with new repos created this month.
It seems like ``borg prune --umask 0077 --list --stats --save-space --keep-last 1 -d14 -w16 -m48 . `` keeps some dangling files.

Backups of /root and /etc seem to get the most cruft data while /var dont.
Unfortunately I did not manage to reproduce this. But the compaction effect of ``borg check --repair .`` is real.

I am considering running this against the multi-TB backups of /srv - maybe this is a good way to test, if the offsite backups work, if it is actually check --repair that is broken and just randomly deletes data.

`` # du -sch root``
```
57M     root
57M     total
```

``# borg info root``
```
[...]
Encrypted: No
[...]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              234.49 MB            132.19 MB             40.92 MB

                       Unique chunks         Total chunks
Chunk index:                   16285               110842
```

``# borg check --repair root``
``# du -sch root``
```
42M     root
42M     total
```

**Comment by someone-somenet-org** [comment]
Some more testing on another machine... It seems these 17 byte "empty" files are removed by ``borg check --repair .``, but are left over when only using ``borg prune`` or ``borg delete``.

`` # du -scm etc``
```
16      etc
16      total
```
``# borg info etc``
```
Encrypted: No
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              350.41 MB            119.76 MB             12.64 MB

                       Unique chunks         Total chunks
Chunk index:                    1971                48122
```
``# find etc -type f -size 17c | wc``
```
    777     777   11877
```
``# borg check --verbose --repair etc``
``# du -scm etc``
```
13      etc
13      total
```
``# find etc -type f -size 17c | wc``
```
      3       3      48
```

**Comment by someone-somenet-org** [comment]
Is there a way to re-create a repository?
as in:
+ copy over only all data that is actually used.
+ make sure these are correct and in the current on-disk-format.
+ make it look like there never was anything in this repository that was deleted.
  + reset counters (those on index.XXX; hints.XXX)

**Comment by alfredonodo** [comment]
> I've no idea about what that could be.
> 
> So, one approach to proceed would be that you create a script that reproduces the issue in the most simple way possible:
> 
>     * preferably only using relative pathes
> 
>     * preferably with a most simple borg invocation
> 
>     * preferably with a local repo
> 
> 
> This is so anybody can easily reproduce without much effort.

Hi,
I made further tests and I think I found the culprit. The problems appears when I use borg together with mega.nz. So we can exclude a problem related to permissions, borg itself and cron task.
I think I can exclude a problem of mega.nz itself too, since in other machines I have the same script, but they use GUI official [cloud sync software](https://help.mega.nz/megasync/general.html).
This machine uses command line [megatools sync software](https://megatools.megous.com/).
I'm going to use GUI official cloud sync software in order to confirm that is a problem of megatools.
Do you have any hint? Is the first time that something similar happen?
Thank you
```

Borg + cron + mega1
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath1
Keeping archive: server-root-2020-12-30-02:15:14 Wed, 2020-12-30 02:15:16 [72a930d711c0bd481583f9754f66d87cde2f28f67da731c831843f44eda1f03c]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               15.67 GB             13.23 GB             13.18 GB

                       Unique chunks         Total chunks
Chunk index:                   42747                44357
------------------------------------------------------------------------------
sudo du -sh repositoryPath1/data
72G	repositoryPath1/data

Borg + cron + mega2
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath2
Keeping archive: server-root-2020-12-29-14:01:28 Tue, 2020-12-29 14:01:29 [d2b621830d2b3a499f088ad2a418753c66314b950184545e7c2b79260c663729]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               18.99 GB             16.54 GB             16.47 GB

                       Unique chunks         Total chunks
Chunk index:                   43324                44890
------------------------------------------------------------------------------
du -sh repositoryPath2/data
46G	repositoryPath2/data

Borg + cron
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath3
Keeping archive: server-root-2020-12-29-17:48:10 Tue, 2020-12-29 17:48:11 [777ee9eb5e01ba2c406a1dd477a2f660adaca4e5ff491b2bf96dede9abba3a5b]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               19.15 GB             16.70 GB             16.50 GB

                       Unique chunks         Total chunks
Chunk index:                   43696                45335
------------------------------------------------------------------------------
du -sh repositoryPath3/data
16G	repositoryPath3/data

Borg manual
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath4
Keeping archive: server-root-2020-12-30-02:15:14 Wed, 2020-12-30 02:15:16 [d9b0e0bdd55eb83b283dcd81eb99a44c0f9e935e154d47513de72c077a1c6953]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               15.67 GB             13.23 GB             13.17 GB

                       Unique chunks         Total chunks
Chunk index:                   42752                44356
------------------------------------------------------------------------------
du -sh repositoryPath4/data
13G	repositoryPath4/data
```

**Comment by ThomasWaldmann** [comment]
well, if you only see that on mega, but not locally, likely the mega filesystem you use has some flaws and does not (always) behave like a normal filesystem.

**Comment by alfredonodo** [comment]
In order to be 100% sure, I created again the same repositories. I will let you know and then, if confirmed, I would close the issue.

**Comment by alfredonodo** [comment]
I can confirm that there is an issue with megacmd.
```
Borg + cron + megacmd
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath1/data
Keeping archive: server-root-2021-01-25-02:01:47 Mon, 2021-01-25 02:01:48 [71833468ca08d55cd39226891d052f9d3f13ca2295a381077492cdedcfcfd215]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               16.03 GB             13.55 GB             13.47 GB

                       Unique chunks         Total chunks
Chunk index:                   47299                50904
------------------------------------------------------------------------------
du -sh repositoryPath1/data
73G	repositoryPath1/data

Borg + cron + megacmd
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath2/data
Keeping archive: server-root-2021-01-25-14:01:39 Mon, 2021-01-25 14:01:39 [d3c538cbcda77366cf7eb8c9f49fb1dbc59e6f3dd80737b625559d658c7359cb]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               19.25 GB             16.74 GB             16.64 GB

                       Unique chunks         Total chunks
Chunk index:                   48126                51822
------------------------------------------------------------------------------
du -sh repositoryPath2/data
47G	repositoryPath2/data

Borg + cron + megasync
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath3/data
Enter passphrase for key /home/master/Desktop/backup3/moodleBackup/BorgBackupCloud3: 
Keeping archive: server-root-2021-01-25-03:01:52 Mon, 2021-01-25 03:01:53 [265383b015da0a3e654381a84754f1e7213e5ba0b2d6520eafaf93244831f8ec]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               16.04 GB             13.54 GB             13.45 GB

                       Unique chunks         Total chunks
Chunk index:                   47247                50859
------------------------------------------------------------------------------
du -sh repositoryPath3/data
13G	repositoryPath3/data

Borg + borg
sudo borg prune -v --list --save-space --stats --force --keep-daily=1 --prefix='{hostname}-' repositoryPath4/data
Keeping archive: server-root-2021-01-25-04:03:54 Mon, 2021-01-25 04:03:55 [e1319679e059ead558758a03fd0e9fea141d393c8306f57be953aea9ddf2193b]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               19.26 GB             16.75 GB             16.66 GB

                       Unique chunks         Total chunks
Chunk index:                   48293                51894
------------------------------------------------------------------------------
du -sh repositoryPath4/data
17G	repositoryPath4/data 
```

**Comment by arcstur** [comment]
I had the same problem, of borg size not matching `du` size. Doing a `borg check --repair` didn't work, but `borg compact` did!

**Comment by arcstur** [comment]
Actually, `borg compact` only worked AFTER a `borg check --repair`!

When I tried doing it on a copy of the repo without checking and repairing first it didn't worked.

But, anyway, the documentation clearly says on [borg prune](https://borgbackup.readthedocs.io/en/stable/usage/prune.html):
> Important: Repository disk space is **not** freed until you run borg compact.

**Comment by ThomasWaldmann** [comment]
Usually it is not required to run `borg check --repair` before `borg compact`.
But maybe that repo was in a somehow weird state and actually needed fixing first.

**Comment by alfredonodo** [comment]
> Actually, `borg compact` only worked AFTER a `borg check --repair`!
> 
> When I tried doing it on a copy of the repo without checking and repairing first it didn't worked.
> 
> But, anyway, the documentation clearly says on [borg prune](https://borgbackup.readthedocs.io/en/stable/usage/prune.html):
> 
> > Important: Repository disk space is **not** freed until you run borg compact.

Thank you for your message. I will investigate further, however, according to my research, it is a bug in megacmd as it works flawlessly both offline and with megasync.

**Comment by alfredonodo** [comment]
Hi,
I am still having the previous issue that has not been solved from mega side. Has anyone experiencing something similar? Now I am on ubuntu server 24.04, borg 1.2.8, megacmd 2.6.0 and megasync 6.5.1. Who knows if the next borg 2.0 will solve the problem.
