### ISSUE TITLE
Best way to set up development for documentation

### ISSUE THREAD

**Issue by eike-fokken** [borgbackup/borg#5399]
I'm working on a pull request that entails only documentation.
In that work I found that the documentation lacks on some hands-on advice for someone like me.

Maybe you can help me getting around some problems I had (I will apply what I learn here to include it in the docs on development).

Most of the docs are created from the source files, generating some rst.inc files.
Therefore to view the newly created docs, one has to "build" the borg exectutable and use it to run
```python setup.py build_usage```

I need help with two things:
1. Can I tell setup.py to use a specific borg executable? I got around this by adding `borgrepo/.tox/py38/bin` to my path and exporting it, but this felt cumbersome to me and may interfere with my backup
2. What is the command for tox to just build the binary and not run any tests in order to save time?

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/development.html#documentation there is the general process to build the docs, reading the upper part of that page and the developer / source based install docs might be also helpful.

Usually one works from an active virtual environment and then it will use the python that venv was built for (e.g. with `virtualenv`).

If one needs some python not present on the system, one can use pyenv to install it.

I build the binaries inside vagrant/virtualbox VMs, see `Vagrantfile` for the commands used there, search for pyinstaller or binary.

`tox` is just a wrapper around pytest/flake8 to test for all python version + style check.

**Comment by ThomasWaldmann** [comment]
BTW, for borg <= 1.1.14 a relatively old pyinstaller, python 3.5.x and debian jessie was used.

Right now, I am updating this to build with pyinstaller 4.0, python 3.7.x and debian stretch.

**Comment by eike-fokken** [comment]
I got it to work, thanks. The issue was with me trying to combine python from conda and a system python.
After getting rid of conda and reinstalling virtualenv with
```sudo pip install virtualenv```
it now works as described in the docs. I'll think about whether I still find that the docs could be changed in that regard (guess my exact problem was rather peculiar) and if so will file a pull request.
