### ISSUE TITLE
borg stalls forever after interrupted first backup

### ISSUE THREAD

**Issue by varac** [borgbackup/borg#54]
hi, i made a remote (encrypted) backup, which got interrupted by a jammed uplink (borg stalled even after the uplink was ok again, and i needed to cancel the backup. should i open a seperate issue that borg doesn't recover from a temporar jammed uplink ?)
Now, when i do `borg list -v  ssh://xxx@SERVER/var/backup/borg`, i seem to stall forever without output.
What can i do to provide more details, afaik, there's no --debug flag to borg ?

**Comment by varac** [comment]
oh, client is `Borg 0.16+217.g98a0157-py3.4-linux-x86_64.egg` and server is `Borg 0.23.0`

**Comment by ThomasWaldmann** [comment]
@varac thanks for the feedback. I'll have a look and see if I can reproduce.

**Comment by varac** [comment]
i figured out what's the problem here.
if you start a backup with `borg create`, and interrupt it, the server proc is still running and waiting for input. Any additional `borg create` or `borg list` stalls, untless you kill the borg proc on the server.

**Comment by ThomasWaldmann** [comment]
Hmm, it might be waiting for the exclusive lock.

**Comment by ThomasWaldmann** [comment]
I am closing this as we have other tickets about showing the wait for a lock / dealing with locks.

**Comment by covermind** [comment]
Ok I move openssh server on backup server to 23 tcp port - same issue not working. Stalled.
Next I Install dropbear ssh server and bind it to 23 tcp port - Working!!!
How?

But I do not understand WTF. Only one server with borg backup have this trouble. Other servers backups work OK.

Backup tasks working over internet not inside LAN network.
