### ISSUE TITLE
implement borg mount with pyfuse3

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5407]
`llfuse` is (more or less) unmaintained, we need to support `pyfuse3` in future (master branch only) to implement `borg mount`.

llfuse support must not get removed yet, as some platforms can not yet run pyfuse3 (e.g. macOS and FreeBSD). so we must have both implementations in parallel in the codebase.

as pyfuse3 started as a fork of llfuse, the api might be similar - so we could check if some borg code could be used for both of the `borg mount` implementations.

pyfuse3-based implementation must include automated tests, same or similar as we have now for the llfuse-based implementation.

bounty: https://www.bountysource.com/issues/93368903-implement-borg-mount-with-pyfuse3

**Comment by ThomasWaldmann** [comment]
I intend to put a bounty on this, but bountysource currently has technical issues...

**Comment by selurvedu** [comment]
I've got an impression that Bountysource got broken months ago.

**Comment by ThomasWaldmann** [comment]
Got a reply from BS support, but still not working.

**Comment by ThomasWaldmann** [comment]
Note: check #4948 - does it behave the same with `pyfuse3` and can we find out **why**?

**Comment by ThomasWaldmann** [comment]
could transfer 50 USD from another (not wanted any more) bounty via my personal account, but still can't access organization funds.

anybody interested in this can help by increasing the bounty.

**Comment by Gu1nness** [comment]
I'm taking this one !

**Comment by ThomasWaldmann** [comment]
@Gu1nness I started implementing it when I assigned the issue to myself. Maybe should have better left a comment also.

**Comment by Gu1nness** [comment]
Ah I didn't see you assigned it to yourself!
For now I'm working on the imports and all the places where llfuse is used, but it took only ten minutes for me for what I did.
So I guess I'll leave it to you and will work on the next one :)

**Comment by ThomasWaldmann** [comment]
@Gu1nness if you like, review #5430.
