### ISSUE TITLE
Security of ssh forced commands

### ISSUE THREAD

**Issue by eike-fokken** [borgbackup/borg#5410]
## Have you checked borgbackup docs, FAQ, and open Github issues?
 
Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Operating system (distribution) and version.

Debian testing

## The Question

Various threads here lament the absence of a pull-style backup in borg because of security concerns.

My question is therefore: How far is the problem of a malicious client deleting old backups mitigated by using ssh forced commands a explained in the borg serve documentation.
My impression is that the only drawback of this is the reliance on an external security measure, namely ssh. Is this impression wrong?

**Comment by ThomasWaldmann** [comment]
There are 2 aspects:
- forced command for a specific key means the client can't issue any other command than that (e.g. another command than `borg` or `borg` with other options). So it is enforcing command and some options.
- `append-only` mode - if this is enforced server side, a client can not modify/remove any past repo state.

Relying on ssh for security measures should be quite OK as this is a very widespread and well-maintained, secure piece of software.

**Comment by ThomasWaldmann** [comment]
BTW, some pull style methods are meanwhile documented.

**Comment by eike-fokken** [comment]
concerning the first aspect, I think this is not different from pull style backups, as in that case no command whatsoever can be done from the client regarding the backup.
For the second aspect I sympathize with a lot of commenters that append-only mode is difficult to use in practice because I usually want to prune my backups from time to time. But I admit that it may be useful for people having much space and very high security needs.

> Relying on ssh for security measures should be quite OK as this is a very widespread and well-maintained, secure piece of software.
I'm definitely ok with that.

I must say that I dislike the pull style backups in the docs because they cannot deduplicate on the client side and hence have to transmit the whole data over the wire, if I understand it correctly. But your comments make me believe that there is no real difference in security between pull and push backup if I make sure that clients can never access the backup server except with the ssh key that has a forced command.

**Comment by ThomasWaldmann** [comment]
Yeah, it is difficult to know what you can safely delete (== NOT need later).

But there is nothing borg or any other tool can do about that.

Hmm? At least the latest doc additions invokes a borg on the client-side from the server, so that should work as normal.

**Comment by eike-fokken** [comment]
Oh, I see now. I only read about the sshfs-way.
Thanks for clearing that up!
