### ISSUE TITLE
borg create --list: when to show a path/filename

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5417]
borg 1.1.x prints the path/filename after completing the back up of that file.

for rather big files, this might take rather long and the user only sees the previous filenames, not the filename of the big file.

thus, the user might think, borg is hanging / not doing anything. Example: https://github.com/borgbackup/borg/issues/4762#issuecomment-538785655

also, if some file-reading related error or warning is output, it might be unclear to which file the error message refers.

this ticket is about changing this behaviour, to print the path/filename before starting to back up the respective file.

Bounty: https://www.bountysource.com/issues/93406062-borg-create-list-when-to-show-a-path-filename

**Comment by ThomasWaldmann** [comment]
There is an issue with showing filename first:

We also show the status and while reading the file, the status might change to E)rror.

**Comment by ThomasWaldmann** [comment]
Idea: before borg decides to call `chunk_file` (which reads, chunks, hashes, ... the file's content) we could emit the latest status (usually A or M for regular files) plus filename and signal via status = None (usually the return value of the file item handler) that no additional output is wanted after completion (needs some other code changes, status None is currently treated as invalid state).

**Comment by ThomasWaldmann** [comment]
Does anybody see an issue with this slight behaviour change?

**Comment by fantasya-pbem** [comment]
So the file with error will have double output (M somefile, E somefile)?

**Comment by ThomasWaldmann** [comment]
Yes, in case of an error.

**Comment by Gu1nness** [comment]
Wouldn't it be possible in this specific case to rewrite the line using \r?
This way, we avoid deduplication, and make it easier to check the number of back-upped files?

**Comment by ThomasWaldmann** [comment]
Hmm, not sure if that is possible, have to check how that output is generated.

**Comment by Gu1nness** [comment]
@ThomasWaldmann Can you point me to the place where chunk_file is called ? I cannot find it in the source only in the builds :/
Then I can write the patch with the two lines, or the \r if possible

**Comment by ThomasWaldmann** [comment]
This change should be delayed until after PR #5492 (+ potential backport).

**Comment by Gu1nness** [comment]
Sure, I'll wait then!

**Comment by Gu1nness** [comment]
I have started working on this one, still WIP but close to an end

**Comment by ThomasWaldmann** [comment]
@Gu1nness i've just changed the milestone for this, we first want to have that in master for a bit.

Later we can maybe backport to 1.1-maint.

**Comment by ThomasWaldmann** [comment]
@Gu1nness please open a PR as soon as you have something, to get early feedback.

**Comment by Gu1nness** [comment]
Sure, I'll do this.

**Comment by ThomasWaldmann** [comment]
@Gu1nness are you still working on this?

**Comment by Gu1nness** [comment]
Yes, I just was offline for quite a few days.
Patch incoming soon

**Comment by ThomasWaldmann** [comment]
@Gu1nness told me that this will take a while and can be taken by someone else.

**Comment by ThomasWaldmann** [comment]
Will work on this now.
