### ISSUE TITLE
cygwin issue with bundled msgpack in borg 1.1.x

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5419]
current borg 1.1.x:

the usual developer setup with virtualenv, requirements.d/development.txt and finally `pip install -e .` does not work on cygwin.

it breaks when trying to compile the bundled msgpack due to not finding `pack.h`, which is in same directory as the file including it.

adding `.` to include path does not help either.

maybe somebody actually using borg on cygwin could debug / fix this. :-)

Bounty: https://www.bountysource.com/issues/93406061-cygwin-issue-with-bundled-msgpack-in-borg-1-1-x

**Comment by fadedreamz** [comment]
I want to give it a shot. Kindly assign me for this issue.

**Comment by fadedreamz** [comment]
Using master - I can't reproduce the issue. It seems it is able to build the msgpack.

```
Collecting msgpack<=1.0.0,>=0.5.6
  Downloading msgpack-1.0.0.tar.gz (232 kB)
     |████████████████████████████████| 232 kB 1.1 MB/s
Building wheels for collected packages: msgpack
  Building wheel for msgpack (setup.py) ... done
  Created wheel for msgpack: filename=msgpack-1.0.0-cp38-cp38-cygwin_3_1_7_x86_64.whl size=15880 sha256=c126307075965bdf7690e38ab972ef0d24441d9f35f872d505ef323fd73c2f3e
  Stored in directory: /home/WDAGUtilityAccount/.cache/pip/wheels/0b/b8/26/147bd5396c0983181d6a9fb93fa1cdcdf457795f824c7bcf1c
Successfully built msgpack
Installing collected packages: msgpack, borgbackup
  Running setup.py develop for borgbackup
Successfully installed borgbackup msgpack-1.0.0
```
How to check the version of the currently building borg?

**Comment by ThomasWaldmann** [comment]
The first line of this ticket says **current borg 1.1.x**, so you need to `git checkout 1.1-maint`, not master.

**Comment by ThomasWaldmann** [comment]
The setup code in 1.1-maint and master differs quite a bit, guess this difference is causing this. If we can make 1.1-maint work with a small fix that would be very much preferred compared to backporting all the setup*.py code from master.

**Comment by fadedreamz** [comment]
I still got success with 1.1-maint, I am following the instructions from `docs/installation.rst`. Tried with python3.6 and python3.8 in both cases it was able to successfully do `pip install -e .`. Can you provide me the reproducible steps?

**Comment by ThomasWaldmann** [comment]
When trying to create a new virtual env using `virtualenv` command, I got some tracebacks. That led my to checking what python3-related packages are installed. There was some older py36 stuff and some py38 (3.8.3) stuff. I decided to purge all py3 related cygwin packages, then installed all with py38-only from scratch.

Then used `python3 -m venv borg-env` to create the venv instead of the `virtualenv` command.

`pip install -r requirements... ; pip install -e .` then worked. `borg -V` gave `1.1.15`, so that worked.

**Comment by ThomasWaldmann** [comment]
Then I commented the line with `llfuse` in `requirements.d/fuse.txt` and ran `tox -e py38` to invoke the unit tests. FUSE is not working on cygwin AFAIK, so no need to try that.

That is crashing with `No module named setup_lz4` although the file is present in cwd.

**Comment by fadedreamz** [comment]
Equally strange on my side! I followed your steps and got `borg -V` to get `borg 1.1.16.dev1+g9b376667.d20210120`. And from there was able to execute the `tox -e py38` to get following output.

```
============================= test session starts ==============================
platform cygwin -- Python 3.8.3, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38/.pytest_cache
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Tests enabled: root, symlinks, hardlinks, atime/mtime, modes
Tests disabled: BSD flags, fuse
rootdir: /home/faded/borg, configfile: setup.cfg
plugins: benchmark-3.2.3, cov-2.11.0, forked-1.3.0, xdist-2.2.0
gw0 [1384] / gw1 [1384] / gw2 [1384] / gw3 [1384]
...................................s.................................... [  5%]
...........s.....ss.s.....s....s.....s..........s..F.sss.s.............s [ 10%]
..ssssssssssssssssssssssssssssssssssssFs.s..........ssssssssssssssssssss [ 15%]
ssssssssssssssss......F.ssssssssssssssssssssssssssssssssssssssssssssssss [ 20%]
ss........................s.........s.........s.ss.......F....ssssssssss [ 26%]
ssssssssssssssssssssssssss......ss...................................... [ 31%]
...........sssssssssssssssss....ssssssssssssssssssssssssssssssss........ [ 36%]
.............s.......................................................... [ 41%]
........................................................................ [ 46%]
......................................................ss................ [ 52%]
...................................................................s.... [ 57%]
.........................s..s..........................s..s............. [ 62%]
...........ss.F.s........................s.............................. [ 67%]
....................................................................ssss [ 72%]
ss...ss................................................................. [ 78%]
...........................F............................................ [ 83%]
.....................................s.................................. [ 88%]
........................................................................ [ 93%]
...sssss.........sss..............................................s..... [ 98%]
................                                                         [100%]
=================================== FAILURES ===================================
```

The only difference I can see is the `borg -V` version number. If I use `pip install -r requirements.d/development.txt` I get `1.1.16` and if I use `pip install -r requirements.d/development.lock.txt` I get the above version. I am running Win10 VM + cygwin.

Do you have the commit hash which gives the `1.1.15` version?

**Comment by fadedreamz** [comment]
At this point, I am suspecting the packages (read package versions) you have in the cygwin may be causing the breakage.

**Comment by ThomasWaldmann** [comment]
I did a `git checkout 1.1.15` to have a well-known, easily reproducible state of the code.

**Comment by ThomasWaldmann** [comment]
I run into same issues with current 1.1-maint checkout.

**Comment by ThomasWaldmann** [comment]
Note: just running `pytest` (without using tox, after tweaking PYTHONPATH and `pip -e .`) **works**.

**Comment by fadedreamz** [comment]
I used gcc-10, and 1.1-maint branch, I will try with 1.1.15 tag build.
Also, just to be sure, I tried with a fresh win10 vm, it was able to run the tox (albait having test failures) with out the missing header file message.

**Comment by fadedreamz** [comment]
@ThomasWaldmann 
Using Win10 (19042.631), I can't reproduce the issue.
I am using following packages from cygwin
```
python3=3.8.3-1
python3-devel=3.8.3-1
python38-setuptools=51.1.1-1
libcrypt-devel=4.4.4-1
libssl-devel=1.1.1f-1
binutils=2.34+1git
git=2.30.0-1
make=4.3-1
openssh=8.4p 1-2
gcc=10.2.0-1
```
Here are my steps (inside a cygwin term)
1. `git clone git@github.com:borgbackup/borg.git`
2. `cd brog`
3. `python3 -m venv borg-env`
4. `source borg-env/bin/active`
5. `git checkout 1.1.15 -b 1.1.15`
6. `pip install -r requirements.d/development.txt`
7. `pip install -e .`
8. `borg -V` this now gives 1.1.15
9. comment out `lfuse` from `requirements.d/fuse.txt`
10. `tox -e py38`

At this point I see the test is running.
Can you try with a fresh vm with same packages as mine?

**Comment by ThomasWaldmann** [comment]
I have the same packages as you. Used the same commands, still does not work.

Can you do a `pip freeze` with your borg-env activated?

**Comment by fadedreamz** [comment]
Output of `pip freeze` 
```
apipkg==1.5
appdirs==1.4.4
attrs==20.3.0
bleach==3.2.1
-e git+https://github.com/borgbackup/borg.git@6916d1b3bc8d25d9e6f6254459abd3e21f4dc1e3#egg=borgbackup
certifi==2020.12.5
chardet==4.0.0
colorama==0.4.4
coverage==5.3.1
Cython==0.29.21
distlib==0.3.1
docutils==0.16
execnet==1.7.1
filelock==3.0.12
idna==2.10
iniconfig==1.1.1
keyring==21.8.0
packaging==20.8
pkginfo==1.7.0
pluggy==0.13.1
py==1.10.0
py-cpuinfo==7.0.0
Pygments==2.7.4
pyparsing==2.4.7
pytest==6.2.1
pytest-benchmark==3.2.3
pytest-cov==2.11.1
pytest-forked==1.3.0
pytest-xdist==2.2.0
readme-renderer==28.0
requests==2.25.1
requests-toolbelt==0.9.1
rfc3986==1.4.0
setuptools-scm==5.0.1
six==1.15.0
toml==0.10.2
tox==3.21.2
tqdm==4.56.0
twine==3.3.0
urllib3==1.26.2
virtualenv==20.4.0
webencodings==0.5.1
```

**Comment by ThomasWaldmann** [comment]
About the same here, nothing suspicious.

Did another experiment by removing the `*wheel*` and `*virtualenv*` cygwin packages, but it didn't change the issues.

I'll make a final try using a completely fresh windows user profile. I don't feel like completely reinstalling windows.

**Comment by ThomasWaldmann** [comment]
Switching to a new user profile made it work. I still don't know, what is causing this, but at least I can run the tests again on cygwin.

@fadedreamz if you like, you can collect the bounty for helping here.

**Comment by fadedreamz** [comment]
@ThomasWaldmann Glad I was able to help.
