### ISSUE TITLE
Is it reliable to use Borg for system backups (root directory)

### ISSUE THREAD

**Issue by tifDev** [borgbackup/borg#5424]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

# My question

Does Borg preserves:
- symbolic links, file permissions, user & group ownerships and timestamps
- ACLs
- extended attributes
?

In case the System is not properly working well (f.e. we remove a system folder from our root directory) or even in a case where the OS doesn't even boots, how would this tool be able to solve the problem in both cases? 

And is it possible to then restore for example just home directory?

Thanks in advance.

**OS:** Linux

**Comment by ThomasWaldmann** [comment]
Read the docs, please.

You can boot from any live system (e.g. from USB or CD), then download the fat binary from github releases and then do your restore. You can restore a subset, of course.

**Comment by enkore** [comment]
Close this? It seems to me like Borg has shown in practice that it can absolutely do this and the docs answer all of these questions.

**Comment by yash-fn** [comment]
Well one other thing I was not able to find an answer for: while backing up a live system, what happens if a file that is being backed up changes during said backup? Is an inconsistent state possible with borg? Is it safe for live systems?

**Comment by yash-fn** [comment]
From the Docs "Backing up live VMs can (and will) result in corrupted or inconsistent backup contents: a VM image is just a regular file to Borg with the same issues as regular files when it comes to concurrent reading and writing from the same file."

so I guess that means no to live systems. :-(

**Comment by ThomasWaldmann** [comment]
@yash-fn this is a problem outside of borg scope. in general, you should back up a state that is helpful for when you need to recover. if you backup crap, it is useless for restoring.

whether you can achieve a useful (and frozen/snapshotted, for consistency) state for a live VM depends very much on the virtualisation software - some might be able to quiesce the filesystem inside, then take a snapshot of the VM block device state so you can back up that.

**Comment by yash-fn** [comment]
Yeah I've done more research and looks like I didn't understand what a snapshot was. Borg and other tools are a backup manager whereas snapshots are a low level file system tool to ensure file states of what the backup manager reads are read only preventing inconsistent state. I conflated the two and now understand the difference. Thanks for the explanation.
