### ISSUE TITLE
tox.ini is outdated compared to setup.py

### ISSUE THREAD

**Issue by Gu1nness** [borgbackup/borg#5426]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

master branch

## Problem : 

The [setup file](https://github.com/borgbackup/borg/blob/master/setup.py#L297) 
specifies that the python version should be >=3.6 but the tox.ini still lists py35 as a possible test version.
py35 should be removed from tox.ini.

I can do this if you're OK with it.

**Comment by ThomasWaldmann** [comment]
Yeah, that should be fixed. Thanks for a PR.

**Comment by Gu1nness** [comment]
Here you are :)
