### ISSUE TITLE
borg init PermissionError with s3 compatible digitalocean spaces mounted with s3fs

### ISSUE THREAD

**Issue by Jerome-thinking** [borgbackup/borg#5431]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

## System information. For client/server mode post info for both machines.
alpine:3.12 as a docker container

#### Your borg version (borg -V).
(borg-env) bash-5.0$ borg -V
borg 1.1.14

#### Operating system (distribution) and version.
Linux e9a2072141cd 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 Linux

#### Hardware / network configuration, and filesystems used.
borg runs in a container that is spawned as a job in a kubernetes cluster.
The back up repository is intended to be created on a digital ocean spaces bucket (s3 compatible). This is mounted via s3fs. Once it is mounted we do not see any problems accessing the storage. Copy/Remove via the shell works.

sudo s3fs ${SPACE_NAME} ${SPACE_MOUNT_POINT} -o url=${SPACE_URL} -o use_cache=/tmp -o use_path_request_style -o allow_other -o uid=10001 -o gid=20001 -o nocopyapi

The nocopyapi option was a desperate attempt to find the cause for the issue, it did not change anything.

#### How much data is handled by borg?
Nothing yet because it fails at the init command

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg init --debug --encryption=repokey --make-parent-dirs ${BORG_REPO}

## Describe the problem you're observing.
When run as a part of the digitalocean kubernetes infrastructure borg fails with PermissionErrors.
Sometimes it fails creating the README (I assume this is the first file created), sometimes it fails when copying the config.tmp to config

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. Happens every time.
Together with the digitalocean support we attempted several approaches to narrow down the cause.
We could rule out
- it was the digitalocean spaces access rates limit (as it was temporarily raised by them)
- it was the user being root (as the behavior is exactly the same, using root or another user)
- it is a pure container based problem (as we are successfully using the container from our local dev machine to create backups)
- it is directly related to https://github.com/borgbackup/borg/issues/2499 (as we never mixed any users, the repo is created in the same run as the permission errors occur)
- using the s3fs option nocopyapi seems to change the behavior as this was doing the trick to make it work from our local dev machines, but it does not change anything from within the k8s cluster, also there seems to be no hint anywhere about space api not supporting copy/put

#### Include any warning/errors/backtraces from the system logs
Exception thrown in the command line:
```
[borg-backup-1603127400-vxttl borg-backup] Local Exception
[borg-backup-1603127400-vxttl borg-backup] Traceback (most recent call last):
[borg-backup-1603127400-vxttl borg-backup]   File "/home/redacted/setup/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 4591, in main
[borg-backup-1603127400-vxttl borg-backup]     exit_code = archiver.run(args)
[borg-backup-1603127400-vxttl borg-backup]   File "/home/redacted/setup/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 4523, in run
[borg-backup-1603127400-vxttl borg-backup]     return set_ec(func(args))
[borg-backup-1603127400-vxttl borg-backup]   File "/home/redacted/setup/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 161, in wrapper
[borg-backup-1603127400-vxttl borg-backup]     with repository:
[borg-backup-1603127400-vxttl borg-backup]   File "/home/redacted/setup/borg-env/lib/python3.8/site-packages/borg/repository.py", line 188, in __enter__
[borg-backup-1603127400-vxttl borg-backup]     self.create(self.path)
[borg-backup-1603127400-vxttl borg-backup]   File "/home/redacted/setup/borg-env/lib/python3.8/site-packages/borg/repository.py", line 287, in create
[borg-backup-1603127400-vxttl borg-backup]     self.save_config(path, config)
[borg-backup-1603127400-vxttl borg-backup]   File "/home/redacted/setup/borg-env/lib/python3.8/site-packages/borg/repository.py", line 313, in save_config
[borg-backup-1603127400-vxttl borg-backup]     config.write(fd)
[borg-backup-1603127400-vxttl borg-backup]   File "/home/redacted/setup/borg-env/lib/python3.8/site-packages/borg/platform/base.py", line 176, in __exit__
[borg-backup-1603127400-vxttl borg-backup]     os.replace(self.tmppath, self.path)
[borg-backup-1603127400-vxttl borg-backup] PermissionError: [Errno 1] Operation not permitted: '/spaces/redacted/config.tmp' -> '/spaces/redacted/config'
[borg-backup-1603127400-vxttl borg-backup] 
[borg-backup-1603127400-vxttl borg-backup] Platform: Linux borg-backup-1603127400-vxttl 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64
[borg-backup-1603127400-vxttl borg-backup] Linux: Unknown Linux  
[borg-backup-1603127400-vxttl borg-backup] Borg: 1.1.14  Python: CPython 3.8.5 msgpack: 0.5.6
[borg-backup-1603127400-vxttl borg-backup] PID: 21  CWD: /home/redacted/setup
[borg-backup-1603127400-vxttl borg-backup] sys.argv: ['/home/redacted/setup/borg-env/bin/borg', 'init', '--debug', '--encryption=repokey', '--make-parent-dirs', '/spaces/test']
[borg-backup-1603127400-vxttl borg-backup] SSH_ORIGINAL_COMMAND: None
[borg-backup-1603127400-vxttl borg-backup] 
```

**Comment by ThomasWaldmann** [comment]
I'm pretty sure this is a permissions issue (check permissions in your repo directory) or an issue with your filesystem (s3fs).

What borg does there is simply renaming config.tmp over config, which is a valid fs operation (and which should be atomic).

**Comment by ThomasWaldmann** [comment]
https://github.com/python-llfuse/python-llfuse/commit/6810c8f91e745ae76858f94236a51fdb84c506a5 related maybe?

**Comment by ThomasWaldmann** [comment]
https://docs.python.org/3/library/os.html#os.replace

note: borg has no exception handling there, because under normal circumstances, this does not fail.
