### ISSUE TITLE
Store a GPG-encrypted copy of the keyfile in the repository

### ISSUE THREAD

**Issue by satwell** [borgbackup/borg#5432]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature Request

#### Your borg version (borg -V).

1.1.14

#### Operating system (distribution) and version.

Linux, Debian Buster and Bullseye
MacOS, Catalina

## Describe the problem you're observing.

I'd like to have a way to keep a GPG-encrypted copy of the repository keyfile in the repository so that a repository can be restored if all I have is the GPG secret key.

Note that this is not the same as other feature requests that would like to use public key encryption for the repository.  This is about using the exact same encryption key, but storing that key using GPG public key encryption.

Why?  My GPG key is already well-secured and backed up.  If I can use that to secure the repository keyfile, then I don't need to keep additional backups of the repository keyfile or passphrase.  This is particularly valuable with multiple repositories.

I can currently export the keyfile, GPG encrypt it, and store it alongside the repository.  But it would be harder to make a mistake, e.g., accidentally delete the encrypted keyfile, if it was actually part of the repository.

This could be implemented as new "borg key" subcommands that store and retrieve the GPG-encrypted key from `config` in the repo.

I can also think of a couple less-ideal alternative implementations.

One possibility would be to have an unencrypted multi-line field in the repository, called "comment" or "password hint" that could be read without the key/passphrase and that the user could manually store GPG ASCII-encoded data in.  Would work, but kind of kludgy.

Another possibility would be to add an alternative to keyfile and repokey, called something like gpgkey.  Similar to repokey, it could use GPG encryption to protect the keyfile instead of a passphrase.  Potentially interesting, but GPG is not great for programmatic use, and I think this might be too brittle.

**Comment by ThomasWaldmann** [comment]
How about just using gpg and scp within a custom script?

Not sure if it counts as a "key backup" if you store the gpg-encrypted key right besides the repokey, especially if one would put it into the repo config.

Also, I don't think I want to integrate gpg for anything into borg. gpg would just add a lot of complexity for users and developers.

**Comment by satwell** [comment]
Yes, definitely I can get what I want by writing my own tools for this.  I started down that route and realized that, for me at least, the ideal place to store a GPG-encrypted keyfile would be in the repository itself.  That way it could be written and read through `borg serve`, and I could easily extend my existing client-side monitoring to verify that the repository contains a GPG-encrypted keyfile.  But certainly I have other options if this isn't a reasonable feature to add to borg.
