### ISSUE TITLE
How to suppress 'remote' output of borg create

### ISSUE THREAD

**Issue by justchris1** [borgbackup/borg#5434]
First of all - thanks for the great tool!  I am finding it quite capable.  Also, thanks for allowing questions to be asked in this forum.

## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## System information. For client/server mode post info for both machines.
VM's with VMWare.  Each has 2 CPUs, 8GB RAM.

#### Your borg version (borg -V).
1.1.13

#### Operating system (distribution) and version.
Centos 8 (client and server)

#### Hardware / network configuration, and filesystems used.
Two VMs, on the same host machine.  Each has EXT4 filesystems local.

#### How much data is handled by borg?
<10MB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
(I am using a slightly customized script of the example located at https://borgbackup.readthedocs.io/en/stable/quickstart.html, 'Automating backups')
borg create   --warning  --show-rc  --compression lz4  --exclude-caches  --lock-wait 600   ::'{hostname}-{now}'   /home/justme1

## Describe the problem you're observing.
As you can see, I am trying to narrow down the output from the borg create command.  I am logging the output (of stderr) to a log file for later review, if needed.  However, I am getting spewed this on every invocation:
```
Remote: \S
Remote: Kernel \r on an \m
Remote: 
```
I am uncertain if the underlying SSH connection or borg is putting this out.  I have configured the ssh config on the borg serve side to command="borg serve --restrict-to-path /path/to/repo",restrict ssh-rsa AAAAB3[...] as suggested on the borg serve page.

Is there a command or environment variable to set for this to not be printed out, or printed out only on error?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Every time the above command is run.

#### Include any warning/errors/backtraces from the system logs
```
Remote: \S
Remote: Kernel \r on an \m
Remote: 
```

**Comment by ThomasWaldmann** [comment]
I don't think this comes from borg. Maybe from ssh?

BTW, "Remote:" here only means that borg received this on the pipe that is connected to the local ssh client.
Usually, this is stuff coming from the remote side, but it could also be something that the local ssh client has output.

**Comment by justchris1** [comment]
Thanks for the quick thoughts.  I had also suspected it might be originating from SSH.  Is there a way of controlling what Borg does with the output from the SSH client, or at what verbosity level it would be reported to the output pipe?

**Comment by enkore** [comment]
Sounds like /etc/issue.

**Comment by justchris1** [comment]
Thanks for the excellent help!  It might be helpful to potentially control what borg create does with the output of the pipe from the remote, or at least assign it to a debug level (such as --verbose or --info).  However, I will leave it up the project to decide if that is desirable from their perspective.  For others who are affected by the same issue searching in the future, I was able to control the specific user's banner by following the following post: https://unix.stackexchange.com/questions/474752/disable-ssh-motd-banner-for-a-specific-user.
