### ISSUE TITLE
automatic reconnection by ISP kills pipe and borg create

### ISSUE THREAD

**Issue by 8FordPrefect8** [borgbackup/borg#5435]
I tried Yesterday to perform my first off site backup with borg. This morning I checked my mails and saw already to my surprise the backup report I create in my script.
The connection was lost due to a broken pipe. I had directly an idea about the resaon and checked my router. At the very same time the nightly ISP reconnect occured.

I couldn't find anything in the docs how to overcome this issue. I guess I maybe have to limited borg and ssh knowledge and maybe and hopefully the solution is easy. Because restarting every day and trie to break the lock will be annoying.

A short question related to this. When I managed to break the lock, should I try to run the very same create command with the same archive name or can I just use my script again, which would create a new archive?

Edit: Although I think it's not really of help for this rather general issue, here is some additional information.
On my Debian server I use the backported version of borg so it's 1.1.14-2.
The repository resides on a Hetzner Storage box. Hetzner doesn't state what subversion they are using. It's 1.1.x. From the documentation I cant see to what the --show-version refers. In my log that resulted in 1.1.14, but if it refers to the client, it is just redundant. I use a ssh key to connect to it without being prompted for password.
The comment I run for create is in principle:
borg --show-version -v create --stats --compression lz4 ssh://bla@bla.your-storagebox.de:23/./backups/repo::$BackupName $MountDir

The error message I get is:
Remote: packet_write_wait: Connection to <IP> port 23: Broken pipe
Connection closed by remote host

The later on prune comment in my script resulted in report of lock:
Failed to create/acquire the lock /home/backups/repo/lock.exclusive (timeout).

I contacted Hetzner and asked them about some sshd.conf settings related to robustness of ssh conncetions.
They wrote they have the following settings:
ClientAliveInterval 30
ClientAliveCountMax 10
TCPKeepAlive yes

But they said this wouldn't help when I get a new IP and that with a new IP I need to reestablish a new connection.

So is there any trick that borg will reconnect to the server within the create command?

**Comment by ThomasWaldmann** [comment]
You can just keep trying, using your same script. borg creates checkpoints (by default every 30 mins), so at some time, it will have transferred all chunks to the server and then the daily backup will be quite fast.

The only case where this does not apply, is when your daily changes are more than you can transfer before it disconnects you, then you should backup more often or get a better connection.

**Comment by ThomasWaldmann** [comment]
And no, borg does neither handle the connection (ssh does) nor does it do automatic reconnects.

In case your repo is locked, make sure that not borg is currently running first and only then use `borg break-lock`.

**Comment by 8FordPrefect8** [comment]
Ah, I didn't check if borg was running before i broke the log. It shouldn't though.
But what could happen if it was running? Anything I should check now or once the initial archive is done?

Thx for your help with some of the noobish questions.

My connection is quite good. I don't know if it's an international thing, but I guess you are german like me. So here it is quite common that as normal customer you don't have a static IP and therefore have a forced reconnect every night and getting a new IP. I would highly wonder if I am the only one with that problem.

Of course since I only load the most important stuff online and my upload is 40Mbit/s. I am done within two days I guess. so it means 2-3 times to break the lock and afterwards I should be fine.

But anyway is there some existing solution even on ssh level? I got from Hetzner that with new IP on my home I need to create a new ssh conncetion. In principle that shouldn't be an issue as I don't need manual interaction for that purpose. But I don't understand how I could help borg create to reconnect instead of dropping the job.

My understanding of the process is the following, please correct me if I am wrong.
1. I have the Hetzner server in my known_hosts for root, because I established a connection once.
2. A connection is  now possible without passphrase for root, as I have my public key on the Hetzner server.
3. Usually there is no open ssh connection to the Hetzner server.
4. If I am issuing for example the borg create command with the repo being specified over ssh, an ssh tunnel is started.
5. If I get a new IP the tunnel collapses and the data stream brakes down.
6. Borg on my client will discover the connection loss and will close with a fail.

How can I maybe configure ssh or maybe borg. That after a loss the repo is just connected to again?

**Comment by ThomasWaldmann** [comment]
If 2 borg write to same repo, I guess it could leads to inconsistencies or damage of the repo in the worst case.
The lock is there to avoid that, so don't break it if you did not make sure no borg is running.
Usually, even in case of exceptions, borg should remove the lock when terminating.

The connection breaks down due to your provider shutting down your internet connection for a short time. After that you might get a new IP or not. The shutdown of the IP connection is what also terminates the ssh connection.

I don't know a good workaround, but as I said, it is not a problem anyway.

**Comment by tacerus** [comment]
I would try spawning your backup jobs inside a Mosh tunnel (https://github.com/carltonf/mosh-via-tunnel), however I just started using Borg and am not sure about the caveats of this idea.
