### ISSUE TITLE
Race condition with get_cache_dir()

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#5439]
My integration tests for borg bindings fail from time to time because there is a race condition here

```py
def get_cache_dir():
…
    # Create path if it doesn't exist yet
    if not os.path.exists(cache_dir):
        os.makedirs(cache_dir)
```

**Comment by ThomasWaldmann** [comment]
What does "fail" mean precisely? Do you get a traceback and if you, can you add it here please?

**Comment by enkore** [comment]
I suppose we could just add exist_ok=True there, after reviewing that nothing around that snippet assumes exclusive access (shouldn't be the case, we got explicit locks for that).

**Comment by sophie-h** [comment]
I thought the race condition was obvious from the code above:

> File \"/app/lib/python3.8/site-packages/borg/cache.py\", line 226, in cache_dir\n    return path or os.path.join(get_cache_dir(), repository.id_str)\n  File \"/app/lib/python3.8/site-packages/borg/helpers.py\", line 561, in get_cache_dir\n    os.makedirs(cache_dir)\n  File \"/usr/lib/python3.8/os.py\", line 223, in makedirs\n    mkdir(name, mode)\nFileExistsError: [Errno 17] File exists: \'/build/.cache/borg\'\n\nPlatform: Linux runner-6yewjmgw-project-11121-concurrent-0 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64\nLinux: Unknown Linux  \nBorg: 1.1.14  Python: CPython 3.8.5 msgpack: 0.5.6\nPID: 7348  CWD: /run/build/pika-backup\nsys.argv: [\'/app/bin/borg\', \'init\', \'--rsh\', \'ssh -o BatchMode=yes\', \'--encryption=repokey\', \'--log-json\', \'--\', \'/tmp/0ddbaa5d-8179-40dc-a71f-b1a5b3cdf048\']

It also happens for config

> File \"/app/lib/python3.8/site-packages/borg/helpers.py\", line 584, in get_config_dir\n    os.makedirs(config_dir)\n  File \"/usr/lib/python3.8/os.py\", line 223, in makedirs\n    mkdir(name, mode)\nFileExistsError: [Errno 17] File exists: \'/build/.config/borg\'\n\nPlatform: Linux runner-6yewjmgw-project-11121-concurrent-0 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64\nLinux: Unknown Linux  \nBorg: 1.1.14  Python: CPython 3.8.5 msgpack: 0.5.6\nPID: 7322  CWD: /run/build/pika-backup\nsys.argv: [\'/app/bin/borg\', \'init\', \'--rsh\', \'ssh -o BatchMode=yes\', \'--encryption=repokey\', \'--log-json\', \'--\', \'/tmp/975fb159-11ec-4447-849b-5e795fd990eb\']

**Comment by ThomasWaldmann** [comment]
Can you post it in a readable format?

**Comment by enkore** [comment]
Yeah, both of these functions should just use exist_ok, because they're creating the top-level directories, not even the specific cache/config dirs for a repo.

**Comment by ThomasWaldmann** [comment]
Note: #5216 is working on same code and intention is to fix this at the same time.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/5216#issuecomment-707852957 describes to remove the race condition, thus I am closing this as a duplicate.
