### ISSUE TITLE
deal better with options passed from client to server

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#544]
https://github.com/borgbackup/borg/pull/529#discussion_r49457475 see that thread.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/29821167-deal-better-with-options-passed-from-client-to-server)

**Comment by xor-gate** [comment]
As a summary:

* `borg serve` could automatically detect it runs under SSH by checking environment variable `SSH_ORIGINAL_COMMAND` and cleans up/restricts the parameters given by the client.
* possibly borg could be configured to allow/restrict certain parameters as a comma separated list `--exclude-args=restrict-path,umask`.

**Comment by anarcat** [comment]
do i understand this correctly that `borg serve` should check if `SSH_ORIGINAL_COMMAND` exists and then have a whitelist of commandline arguments provided? other than `--restrict-path`, what else should be allowed (`--verbose`) was mentionned, but then there was an objection there as well...

there was a discussion there as well to change directory to what is specified in `--restrict-path` to allow easier relative paths for archives... but then i wonder if it wouldn't be simpler to leave that to a wrapper script as well - if you're going to have a `command` in your `authorized_keys` file (right?), might as well change the path there as well... 

i am not sure this is a necessary change or what is necessary here.

**Comment by ThomasWaldmann** [comment]
@anarcat the problem is that the server process should be in sync with the client concerning mode of operation. Otherwise stuff done on the server side does not behave as expected when looking at the cli parameters given to the client.

E.g. if you give `borg create --umask 0007 ...` on the client side and the server side uses a hardcoded borg command that does not include that umask, it won't behave as expected from the cli params.
Same for logging level (server might stay at WARNING, although -v/--info was given at client cli).
Some more to check are mention in the original ticket, see first post.

Hard coding this into authorized key is not really a solution, as it does not adapt to changing cli options given by the user.

**Comment by xor-gate** [comment]
I think the "easiest fix" would to just not allow overwriting `restrict-path` when already set, then the commandline args from the client could be directly parsed into the server process by reading SSH_ORIGINAL_COMMAND.

**Comment by xor-gate** [comment]
@ThomasWaldmann you patch looks great, this also removes the need for a half-working wrapper script. I think we should document this new behaviour ?

**Comment by ThomasWaldmann** [comment]
right. reopened to add some docs.

**Comment by xor-gate** [comment]
@ThomasWaldmann :+1:
