### ISSUE TITLE
Backup to Synology stop with borg.remote.ConnectionClosed

### ISSUE THREAD

**Issue by Nono-m0le** [borgbackup/borg#5457]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V). 
Client; 1.1.14 / Server: 1.1.13

#### Operating system (distribution) and version. 
Debian 10

#### Hardware / network configuration, and filesystems used. 
Dedicated server / remote connection (over ssh) / ext4

#### How much data is handled by borg?
less than 1GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg create                             \
        --verbose                       \
        --debug                         \
        --filter AME                    \
        --list                          \
        --stats                         \
        --show-rc                       \
        --compression lz4               \
        ::'{hostname}-{now:%Y-%m-%d_%H:%M:%S}' \
        /home                    \
```

## Describe the problem you're observing.
At some point (not always the same folder/files/moment, the backup stop with:
```
RemoteRepository: 52.47 MB bytes sent, 19.74 kB bytes received, 1830 messages sent
Connection closed by remote host
Traceback (most recent call last):
  File "borg/archiver.py", line 176, in wrapper
  File "borg/archiver.py", line 586, in do_create
  File "borg/archiver.py", line 549, in create_inner
  File "borg/archiver.py", line 663, in _process
  File "borg/archiver.py", line 663, in _process
  File "borg/archiver.py", line 663, in _process
  File "borg/archiver.py", line 663, in _process
  File "borg/archiver.py", line 637, in _process
  File "borg/archive.py", line 1084, in process_file
  File "borg/archive.py", line 1007, in chunk_file
  File "borg/archive.py", line 995, in chunk_processor
  File "borg/cache.py", line 899, in add_chunk
  File "borg/remote.py", line 477, in do_rpc
  File "borg/remote.py", line 712, in call
  File "borg/remote.py", line 814, in call_many
borg.remote.ConnectionClosed: Connection closed by remote host
During handling of the above exception, another exception occurred: 
Traceback (most recent call last): 
File "borg/archiver.py", line 4591, in main
File "borg/archiver.py", line 4523, in run
File "borg/archiver.py", line 176, in wrapper
File "borg/remote.py", line 634, in __exit__
File "borg/remote.py", line 477, in do_rpc
File "borg/remote.py", line 712, in call
File "borg/remote.py", line 814, in call_many
borg.remote.ConnectionClosed: Connection closed by remote host 
Platform: Linux WEB2 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
Linux: debian 10.5
Borg: 1.1.14  Python: CPython 3.5.10 msgpack: 0.5.6
PID: 5935  CWD: /home
sys.argv: ['borg', 'create', '--verbose', '--debug', '--filter', 'AME', '--list', '--stats', '--show-rc', 
'--compression', 'lz4', '--exclude-caches', '--exclude', '/home/*/.cache/*', '--exclude', '/var/cache/*', 
'--exclude', '/var/tmp/*', '::{hostname}-{now:%Y-%m-%d_%H:%M:%S}', '/home']           
SSH_ORIGINAL_COMMAND: None 
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
It happens when one VM hosted on the server. almost every other VM (same configuration/Version/cmdline) works without issue. To the very same NAS Synology

#### Include any warning/errors/backtraces from the system logs
see above, with --debug output

**Comment by ThomasWaldmann** [comment]
Did you check these issues?

https://github.com/borgbackup/borg/issues?q=is%3Aissue+is%3Aopen+Connection+closed+by+remote+host

**Comment by Nono-m0le** [comment]
Hi @ThomasWaldmann ,

Yup, and I consider all of them (including result from my research engine) none of them fit my issue.
On my case, backup works from the same source (dedicated server using XEN) to the same destination.
I suceed, backup BEFORE this one, AFTER this one, and each are longer/bigger than this one, and really nothing obvious explain why it failed like this, and almost never for the same files.

**Comment by Nono-m0le** [comment]
@ThomasWaldmann Is there any log or info I could bring in, in order to figure out what's going on for the backup ?

**Comment by ThomasWaldmann** [comment]
It's likely an ssh issue. If it was a borg issue, you would see a traceback or something.

But it just says "connection closed by remote host".

**Comment by Nono-m0le** [comment]
@ThomasWaldmann at your knowledge, is there any way to debug the ssh when using borg ?
I'm finding strange that this may happens only from time to time, on different VM, all from the same server. (Because, finally, the "faulty VM" finally suceed to backup once or twice, over 2 weeks).

**Comment by ThomasWaldmann** [comment]
Closing. Rather old, likely ssh or network issue.
