### ISSUE TITLE
move from travis-ci to github workflows/actions

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5467]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

about borg's usage of travis-ci:
- the linux based test runs take rather long
- the macOS based test runs take even longer and are problematic #5370 #5405
- due to sudo, we need VMs
- we need to test on different python versions, on different OSes (linux and mac) and in master branch with llfuse or pyfuse3.

we did **not** overuse by testing the full matrix of this, but only tested a small subset with good coverage.

bounty: https://www.bountysource.com/issues/93837766-travis-ci-bad-news-for-foss-projects

the bounty is for moving the remaining borgbackup/* projects that are currently on travis-ci to github workflows / actions (see the last comments below).

**Comment by ThomasWaldmann** [comment]
Only a few builds after the migration to .com, travis tells me that the `borgbackup` organization has use 1590 of the 10000 monthly credits already.

So, it's easy to see that the free credits won't be enough.

As the macOS test jobs are especially expensive, I guess I'll switch them off unless somebody is sponsoring them.

**Comment by ThomasWaldmann** [comment]
Now it is 6980 used already. These 10000 credits do not suffice even for 1 day of dev activity. :-(

**Comment by ThomasWaldmann** [comment]
Now used 12000 credits already. Out of credits, game over for now. :-(

These were only a few, even trivial pull requests and only a few hours on that new tariff of travis-ci...

**Comment by ThomasWaldmann** [comment]
I had a look at the paid plans (prices are per month):
- USD 69 for 1 concurrent job (== wait for 1h at least)
- USD 129 for 2 concurrent jobs (== wait for 0.5h at least)
- USD 249 for 5 concurrent jobs (== wait for 0.2h at least)

So, they sell the same amount of usage time for a almost linearly going up price depending on how long one wants to wait.

Doesn't look like that will work for us.

**Comment by jurgenhaas** [comment]
Thats why i switched all projects to GitLab, even to a self-hosted instance. Pipelines are great, scalable and free. I'm happy to help, get in touch to share ideas.

**Comment by ThomasWaldmann** [comment]
I'm checking out github workflows/actions right now.

**Comment by Gu1nness** [comment]
Bad news indeed, maybe the code could be mirrored on a gitlab instance with CI and tested there?
Or use the Github CI workflow can also work but we don't know if they will change it the same way soon…

**Comment by ThomasWaldmann** [comment]
Got a mail from travis today, in which they layed out their requirements for using travis for free with credits from FOSS pool.

One of them was that the project must not get sponsored by commercial companies.

I find it not appropriate to basically block FOSS projects from sponsorings, so we'll just move away from travis ci for borgbackup.

**Comment by ThomasWaldmann** [comment]
TODO:
- add github workflows for the other repos (already done here)
- remove travis permissions for borgbackup org
- remove `.travis` and `.travis.yml`

**Comment by ThomasWaldmann** [comment]
github actions done, thanks to @samuel-w! closing this to enable bounty claim.

rest is tracked in #5528 ...
