### ISSUE TITLE
FAQ points to closed issue for pull backups

### ISSUE THREAD

**Issue by anarcat** [borgbackup/borg#5480]
https://borgbackup.readthedocs.io/en/latest/faq.html#how-can-i-protect-against-a-hacked-backup-client says:

> # How can I protect against a hacked backup client?
> 
> Assume you backup your backup client machine C to the backup server S and C gets hacked. In a simple push setup, the attacker could then use borg on C to delete all backups residing on S.
> 
> These are your options to protect against that:
> 
> - Do not allow to permanently delete data from the repo, see Append-only mode (forbid compaction).
> - Use a pull-mode setup using ssh -R, see #900.
> - Mount C’s filesystem on another machine and then create a backup of it.
> - Do not give C filesystem-level access to S.

That's great except #900 is a kind of long issue that was closed because BountySource and chaos. Maybe it would be best to point to some other documentation for pull-mode? Maybe something about #5288 which I believe made https://borgbackup.readthedocs.io/en/latest/deployment/pull-backup.html possible?

**Comment by Gu1nness** [comment]
@anarcat So you'd like to see https://borgbackup.readthedocs.io/en/latest/faq.html#how-can-i-protect-against-a-hacked-backup-client point to https://borgbackup.readthedocs.io/en/latest/deployment/pull-backup.html instead of #900 ?
If yes I'll do the change

**Comment by ThomasWaldmann** [comment]
There is also one strange item in that list:
```
Do not give C filesystem-level access to S.
```

If one wants to protect S from attackers on C, one **of course** does not do that.
But, to delete all archives on S, it is not **required** to have that (one can just use the borg client).

Not sure what to do about this one. Either add "Of course, ..." or remove it from the list?

**Comment by ThomasWaldmann** [comment]
Note: it already points to the right chapter via "See Hosting repositories for a detailed protection guide."

So maybe just continue that sentence with ", especially [point to pull backup subsection]"?

**Comment by anarcat** [comment]
>  If yes I'll do the change

pretty much yeah.

> Do not give C filesystem-level access to S.

Yeah, that struck me as odd as well: i'm not sure why it's there for.

> Note: it already points to the right chapter via "See Hosting repositories for a detailed protection guide."

I think the pull-mode should be an explicit item in the list.
