### ISSUE TITLE
Adding brotli as a new compression algorithm

### ISSUE THREAD

**Issue by Gu1nness** [borgbackup/borg#5486]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## QUESTION

I'm willing to add brotli as a new compression algorithm. It is supported in Linux and BSD systems, I need to check on other platforms such as OSx and Windows.

Worst case, I can still use brotlipy which uses the brolilib from Google.

If borgbackup could back me up with a bountysource on this one, it would be awesome!

**Comment by ThomasWaldmann** [comment]
Find and read the ticket about adding new compression algos, please.

**Comment by meineerde** [comment]
That would be #1633.

**Comment by Gu1nness** [comment]
Yes I looked and commented this issue #1633 because I wanted to add it in the documentation.
I think brotli (@ThomasWaldmann you mentioned it in 2016) can be a good idea, I will implement it and see the performances of this compression compared with zstd, lzma and zlib to see if there is a use for this.

**Comment by ThomasWaldmann** [comment]
https://community.centminmod.com/threads/round-3-compression-comparison-benchmarks-zstd-vs-brotli-vs-pigz-vs-bzip2-vs-xz-etc.17259/#post-73060

See how the zstd is always to the left (== faster at same compression) of brotli?

If you have time you can do of course own borg based measurement, but that graph doesn't look like brotli is a worthwhile addition - see the criteria in #1633, top post.

**Comment by Gu1nness** [comment]
Yeah indeed, I guessed brotli was better than that.
Closing this issue since it is now irrelevant.
