### ISSUE TITLE
pip install borg breaks borgbackup installation in debian

### ISSUE THREAD

**Issue by Report404** [borgbackup/borg#5487]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Did not find a discussion of my problem in either of that.

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION / BURG

#### Your borg version (borg -V).
Package: borgbackup
Version: 1.1.9-2+deb10u1

#### Operating system (distribution) and version.
Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
All borg commands do not work anymore after executing 
$ pip install borg
and
$ pip3 install borg

(I wanted to use the libaries for a python script)

## Describe the problem you're observing.
$ which borg
/usr/bin/borg

So, the symlink still exists

no borg commands like "create" "info" "list" work anymore

#### Can you reproduce the problem?

Yes, no borg commands like "create" "info" "list" work anymore.

#### Include any warning/errors/backtraces from the system logs

No condorscript.py file was detected in directory

#### Notes

I think the execution of "pip" broke my borg installation. This can't be intended by the developers. Is this a debian problem with symlink handling? How could I work around this? What code is beeing executed now? What did change? I would like to understand. I like the software borg very much. Thank you in advance.

**Comment by ThomasWaldmann** [comment]
the package name is `borgbackup`, not `borg`.
