### ISSUE TITLE
Travis speedup by using container based infrastructure

### ISSUE THREAD

**Issue by xor-gate** [borgbackup/borg#549]
I just saw travis was having issues with their (slow) non-container based infrastructure.
Currently the `.travis.yml` file needs sudo which could be removed by adding the 
apt packages directly:
https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages

And for OSX it could also be added into the travis file instead of the `.travis/install` file:
https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-OSX

**Comment by ThomasWaldmann** [comment]
I had a look, but it is a bit confusing:

liblz4 is on the package whitelist, but the gezakovacs ppa is not.
I searched for lz4 packages on the web, but only found gezakovacs' for trusty.

Maybe we delay this change a bit. From experience, it is always a pain to change travis configuration, with a lot of trial and error. So we maybe better do that after 1.0.

**Comment by ThomasWaldmann** [comment]
Helps with this would be appreciated (create your own travis account for testing/developing this).

I guess this will likely need some trial and error changesets, so collapsing the changesets into some few clean ones at the end would be good.

**Comment by xor-gate** [comment]
Yeah, "pre-configured" continues integration platforms like travis are not always as handy as it could be. That is why some opensource projects run their own continues integration platform with Jenkins or Buildbot. It is always a pain to have the correct dependencies. I would like to help and try but for the upcoming weeks it wont happen yet.

**Comment by Ranlvor** [comment]
I looked into this one. Travis runs Ubuntu 12.04 per default, which does not yet have lz4 in apt. You could request adding the gezakovacs-PPA to the whitelist but the repository for the whitelist has a huge backlog of things waiting to be approved, so them accepting gezakovacs seems to be improbable. Travis does offer running Builds on Ubuntu 14.04, but only for sudo-enabled builds and with even worse performance than the current setup.

Other possibilitys: 
 * Try https://circleci.com/
   Disadvantage: Does not seem to have support for building against multible python-versions at once.
 * Setup Jenkins/Buildbot somewhere
   Disadvantage: Someone has to sponsor some Hardware/VM and someone has to maintain it.

**Comment by enkore** [comment]
Sponsored HW/VMs would be really nice for *BSD-testing (which afaik no cloud CI offers). I run/maintain a Jenkins for some stuff of mine, but the hardware would is inept for a project like Borg (a single, non-virtualized build takes ~45 minutes).

**Comment by xor-gate** [comment]
[DigitalOcean](https://digitalocean.com) supports FreeBSD, and [RootBSD](https://www.rootbsd.net) supports most common BSDs.

**Comment by enkore** [comment]
DigitalOcean is a charged service, so someone would need to sponsor it.

Appveyor has free CI for Windows.

Bottom line: testing on the other unix-y platforms will need a sponsor one way or another (money / hardware / VMs).

**Comment by ThomasWaldmann** [comment]
tagged "later" - we need to wait until travis offer trusty-based containers, which have lz4.

**Comment by ThomasWaldmann** [comment]
we don't use travis any more.
