### ISSUE TITLE
--stats output should include repo location

### ISSUE THREAD

**Issue by laur89** [borgbackup/borg#5491]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Y

## Is this a BUG / ISSUE report or a QUESTION?

Feature request

#### Your borg version (borg -V).

borg 1.1.14 (from apk community repos)

#### Operating system (distribution) and version.

alpine linux

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create **--stats**

## Describe the problem you're observing.

I'd like `--stats` output also to include the repository location. This is to make it easier to discern different --stats outputs from a logfile. I have a script that's backing up in parallel to remote & local borg repos; It'd be nice for --stats output head to look like

    ------------------------------------------------------------------------------
    Repository: 12345@ch-s011.rsync.net:/repo/path   # for remote repo
    Repository: /path/to/local/repo                                # for local repo
    Archive name: gitea-downtime-2020-11-08-054300
    Archive fingerprint: 27992ecef61844cb5ee377d447f2984bd9fc4e62134dcf5d81706914fg97pqfe
    Time (start): Sun, 2020-11-08 05:43:08

**Comment by ThomasWaldmann** [comment]
Would you like to make a PR for that against master branch?

**Comment by laur89** [comment]
Not familiar with the codebase. I'll try to get around to it, but no promises.

**Comment by Gu1nness** [comment]
@laur89 If you have some difficulties, I can have a look at it and point you to the right places :)

**Comment by Gu1nness** [comment]
@laur89 Any news, do you need some help?

**Comment by laur89** [comment]
@Gu1nness local dev env setup turned out to be trickier than expected. Hoping to revisit coming weekend.

**Comment by Gu1nness** [comment]
Ok nice, don't hesitate to ping me if necessary.

**Comment by Gu1nness** [comment]
Okay @laur89 I'll patch it if you don't mind.
