### ISSUE TITLE
What is the data utilization for borg mount?

### ISSUE THREAD

**Issue by auanasgheps** [borgbackup/borg#5494]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V): 
1.1.14 and 1.1.13 

#### Operating system (distribution) and version:
Debian 10 (client - backup source), Synology DSM (server - backup destination)

#### Hardware / network configuration, and filesystems used.
**Client - Backup Source**
Debian 10 - borg 1.1.14 + borgmatic
FTTH connection, 1Gbit down, 200 Mbps upload
ext4
**Server - Backup Destination**
Synology DSM 6.2.3 - borg 1.1.13
VDSL connection, 70 Mbps download, 20 upload
ext4

#### How much data is handled by borg?
It's going to be 6TB at least. The first full fat backup will be done locally, then about 15-20GB over Internet/SSH every week.

## Describe the problem you're observing.
Hi,
I am setting up a borg environment to backup all of my personal data from my current server to my old Synology NAS in another city. 
I am new to borg and I apologize if this is a noob question.

My question is regarding the actual network usage needed to restore one or a little number of files. 
If I need a full restore I will **obviously** do it locally, but what happens when I want to restore one or some files? My backup server has a peasant 20 Mbit upload which _can_ be challenging.

As far as I understood, `borg extract` will restore a full backup, so I'm not going to use that remotely, but what about `borg mount`?
Does it only use metadata or similar to display files, or it still needs to extract all archives from a backup?

Additionally, where these "temp" files/archives are stored?

**Comment by ThomasWaldmann** [comment]
I think you should be fine with 20Mbit/s.

You can also do a partial extraction with `borg extract`, see the docs.

Similarly, you can do a partial mount with `borg mount`. Like:
- only 1 archive
- only a specific directory

borg mount keeps the filesystem structure in memory (the essential metadata), but fetches data on-access only.

**Comment by auanasgheps** [comment]
> borg mount keeps the filesystem structure in memory (the essential metadata), but fetches data on-access only.

That's great, that's what I wanted to know (and I hoped). It's a very useful info, which I could not find in the docs. 

I will also try the specific directory mount, since is the one I'm likely going to use.

**Comment by auanasgheps** [comment]
I've managed to test this scenario with a "small" test backup of 10GB and it is behaving as you described:
- Mount is quick (bunch of seconds) with minimal network transfer
- Files are being transferred only when copied or opened

I am shocked how easy and swift `borg mount` works.
@ThomasWaldmann it definitely needs to be advertised, why this is not on the homepage and in docs?

I will donate to this project as soon as I can :)
My questions are over, this can be closed unless you want to keep it as a TODO for the docs.

**Comment by ThomasWaldmann** [comment]
Notes:

How quick it is depends on the archive size and many other factors.

"Mountable backups with FUSE." is on the homepage.

Thanks for donations. Generic funds donations via bountysource will get put on tickets and whoever works on the tickets (== works on borg) will get the bounty.
