### ISSUE TITLE
borg prune suddenly slow for one execution

### ISSUE THREAD

**Issue by laur89** [borgbackup/borg#5495]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

1.1.14

#### Operating system (distribution) and version.

Host is an unraid OS, borg running from a docker container running alpine linux.

#### Hardware / network configuration, and filesystems used.

Local repo is written on a btrfs FS.

#### How much data is handled by borg?

Some `create` stats:

	------------------------------------------------------------------------------
						Original size      Compressed size    Deduplicated size
	This archive:                2.67 GB              1.05 GB              5.30 MB
	All archives:              284.06 GB            246.18 GB             47.23 GB

						Unique chunks         Total chunks
	Chunk index:                  118384              1580947
	------------------------------------------------------------------------------

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

**Create:**

    borg create --stats --show-rc --lock-wait 600 --compression zlib,5 [some --excludes] "$repo::unraid-unraid-{now:%Y-%m-%d-%H%M%S}"  4_directories.../

**Prune:**

    borg prune --show-rc "$repo" --prefix "unraid-unraid-" --keep-daily=7 --keep-weekly=4 --keep-monthly=3 --keep-within=3d

## Describe the problem you're observing.

This backup job has been running nightly for months, backing up both locally & remotely. The runtimes are always in the same ballpark:
For remote, both create & prune are mostly sub-200 sec, but vary a lot; prune is sometimes as low as 8 sec, but have seen as high as 269 sec;
For local, create is mostly sub-60sec, prune up to 2 sec.

Previous night following times were witnessed:
**Remote:**
create completed in 120s (nominal)
prune completed in **13853s** (that's just under 4 hours)

**Local:**
create completed in 43s (nominal)
prune completed in **457s**

What might've caused this hiccup?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Just ran the same backup again (with added `--list` & `--stats` options to prune), but it's no longer happening - times are back to previously seen values.

**Comment by ThomasWaldmann** [comment]
Not sure that even is a "hiccup". It might be just doing more work, thus taking more time.

E.g. if prune decides to delete a yearly archive, the differences to all other archives might be rather big (the yearly archive might hold the last reference to a lot of chunks). When deleting that, it will poke a lot of logical holes into segment files and at the end `compact_segments()` might shuffle around a lot of data to remove these holes.

**Comment by laur89** [comment]
Was considering that, but never experienced this long of a prune.
Would it maybe make sense to separate different upload jobs into their own repositories as opposed to run all jobs against the same repo?

**Comment by ThomasWaldmann** [comment]
One vs. multiple repos has pros and cons, see the FAQ.

BTW, it does of course not need to be a yearly archive, it could just be any archive holding a lot of unique chunk references. So if you had a lot of unique data on the system at one day (that was not present the day before and neither the day after), removing that day's archive will also take its time...

**Comment by laur89** [comment]
Right, sounds like this is by design so all's good.
Thanks!
