### ISSUE TITLE
[scripting] run command while borg lock is acquired by borg itself

### ISSUE THREAD

**Issue by laur89** [borgbackup/borg#5498]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## Describe the problem you're observing.

A backup script has to run some business logic just before running `borg create` (eg stopping docker containers).
Doing it simply prior to running `create` is dangerous, as another backup might be running, holding the lock possibly until `--lock-wait` expires. **How could we run our business logic while subsequent `borg create` is guaranteed to get the lock?**

Imagine following crontab contents that run said backup script:

    10 05 * * *   /backup.sh
    20 05 * * *   /backup.sh
    30 05 * * *   /backup.sh

Say the `05:10` job is running and will take some hours to complete; this means two following scripts also will start in the meantime, while waiting for `--lock-wait` time. Is there some built-in way to manage this?

**Comment by ThomasWaldmann** [comment]
Well, guess the only way would be this:

```
borg --lock-wait XXXX with-lock backup.sh
```

backup.sh:
```
# your stuff here
borg create --bypass-lock ...
# your stuff here, too
```

Not feeling too good with this though, consider --bypass-lock was only intended for rather special use cases and `borg create` is definitely not one of them. If somebody would directly call backup.sh, it could corrupt your repository.

So consider that unsupported usage, in case you decide to do that.

**Comment by ThomasWaldmann** [comment]
Also, maybe try this first on a fresh, experimental repo, I never tried this...

**Comment by ThomasWaldmann** [comment]
A cleaner way would be to implement your own lock for the whole process, outside of borg.

**Comment by laur89** [comment]
> borg --lock-wait XXXX with-lock backup.sh

That's clever! Your notes on the safety are valid; wonder if we could detect from within `backup.sh` that it's being invoked by `borg with-lock`, that way dangers of direct execution could be avoided.


> A cleaner way would be to implement your own lock for the whole process, outside of borg.

Wouldn't cover multiple hosts working against common remote repo, unless we implement our own distributed locking.

**Comment by ThomasWaldmann** [comment]
As a general note: be careful with using `BORG_...` as env var name, rather consider these to be reserved by borg.

**Comment by laur89** [comment]
Would it be non-trivial to add support for locking `n` repos `with-lock` command?

**Comment by ThomasWaldmann** [comment]
Each repo has 1 exclusive lock (for own/internal purposes).

**Comment by laur89** [comment]
Correct, but if `with-lock` supported grabbing locks of multiple repositories, then it'd make additional scripting simpler.

    borg --lock-wait XXXX with-lock "$repo1" "$repo2" "$repoN" cmd

**Comment by ThomasWaldmann** [comment]
There is not one borg operation that deals with multiple repos. Sounds like "out of scope".

**Comment by laur89** [comment]
Thanks. Sounds like this problem is better solved outside of borg then.
