### ISSUE TITLE
make a release that can get in before debian-next freeze

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5499]
https://release.debian.org/bullseye/freeze_policy.html

@LocutusOfBorg is 2020-12-24 early enough for you?

See the 1.1.15 milestone:

https://github.com/borgbackup/borg/milestone/72

**Comment by LocutusOfBorg** [comment]
sure just ping me on irc please :D

**Comment by Gu1nness** [comment]
Working hard to have the release ready :)

**Comment by ThomasWaldmann** [comment]
ok, guess we have all the code changes in 1.1-maint. so just some docs updating and the usual release work to do.

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg @FelixSchwarz 1.1.15 is out.

**Comment by FelixSchwarz** [comment]
@ThomasWaldmann already on its way to testing (https://bodhi.fedoraproject.org/updates/FEDORA-2020-4906e07692). We use [release-monitoring.org](https://release-monitoring.org/project/10446/) so I usually get the notification before the announce mail is sent :-) However I appreciate your pings about important bugs.

**Comment by LocutusOfBorg** [comment]
It's now in sid
