### ISSUE TITLE
Build failing on forks

### ISSUE THREAD

**Issue by Gu1nness** [borgbackup/borg#5502]
When committing to a fork on a branch, the travis tests fail due to
```
 borg.remote.RemoteRepository.RPCServerOutdated: Borg server is too old for open make_parent_dirs=True. Required version 1.1.9
```
which is pretty annoying.
Am I the only one who has this problem ?

**Comment by ThomasWaldmann** [comment]
Never seen that yet.

But at least for the borgbackup organization, the idea was to go away from travis anyway, see #5467 .

**Comment by ThomasWaldmann** [comment]
as we removed travis-ci, guess we can close this?
