### ISSUE TITLE
Contradicting statements about use of hardlinks in documentation

### ISSUE THREAD

**Issue by puenka** [borgbackup/borg#5518]
In the documentation (stable and master) under Usage/General/File Systems, it is stated that
> Hardlinks are needed for `borg upgrade --inplace`

However, in the borg-upgrade documentation it says that
> Unless `--inplace` is specified, the upgrade process first creates a backup copy of the repository, in REPOSITORY.before-upgrade-DATETIME, using hardlinks.

which contradicts the above. From my experience when trying to use a WebDAV mount, using `borg upgrade` without `--inplace` fails due to the lack of hard linking capability.

Except for the mentioned issue of the repository not being recoverable in case of an error during a new snapshot process, is it generally safe to perform a (secondary of course) borg backup on a file system that does not support hard links (e.g. a WebDAV mount) by always using the `--inplace` option? Does this even work with create? On my mount it fails.

**Comment by ThomasWaldmann** [comment]
Need to have a look at the code for this.

In general, you should only use `borg upgrade` if the docs / changelog tell you to do so.

**Comment by ThomasWaldmann** [comment]
Where exactly is the contradiction? Did you see the **Unless**?

**Comment by puenka** [comment]
First just from a linguistical level:
The first statement says that hardlinks are needed **if** the inplace option is specified.
The second statement says that hardlinks are needed **except if** (i.e. unless) the inplace option is specified (thus any operation mode needs hardlinks?).

Also interpreting the content, it makes sense to me that the explanation of how hardlinks are being used in the second statement refers to the case **without** inplace, because the creation of a backup copy is omitted when using the option.

**Comment by ThomasWaldmann** [comment]
Ah, right, so first needs to be rephrased to:

"Hardlinks are needed for borg upgrade (if --inplace is not given)."

**Comment by puenka** [comment]
Yes, that's what I thought (but I don't have the code insight to actually argue about it)!
However I do think that I once had an error with a non-hardlinking file system already at init or at create, but that needs further investigation because this might not have been the exact reason why it failed...but that's just anecdotal anyways and doesn't really bother me at the moment.
