### ISSUE TITLE
No key file for repository <REPO> found in ~/.config/borg/keys 

### ISSUE THREAD

**Issue by asadkhan34** [borgbackup/borg#5521]
Hello , 

I just ran into a problem , whenever i am running the command borg list its giving me error which says No key file exists but key file already exists at the required path so why it is saying that No key file exist ?

Following are the steps to reproduce the problem . 

1 ) I am using LXC containers and first time i ran borg init command to initialize borg repo using encryption mode = keyfile
2)  After initializing the repo , i took the snapshot of my container and when i restore the snapshot of my container the borg repo is there as well as the key also exist there at path ( /root/.config/borg/keys/) , but when i ran borg list then it says No key file for repository . 
 
FYI borg version = 1.0.9

Please assist .

**Comment by infectormp** [comment]
Your version is outdated, I strongly recommend you to update it and try to reproduce this error again.
When you post a problem, please put the command line you used.

**Comment by asadkhan34** [comment]
@infectormp  Thanks for responding 

Following commands which i ran  

To initialize borg repo 
borg init --encryption=keyfile /mnt/backups/dev-abbottberg/

To list backups ran following command 
borg list /mnt/backups/dev-abbottberg/

command gives the following error 
**No key file for repository /mnt/backups/dev-abbottberg found in /root/.config/borg/keys**

**Comment by asadkhan34** [comment]
![image](https://user-images.githubusercontent.com/75013154/100225194-a43f7780-2f3f-11eb-8329-af2d99071a5e.png)

@infectormp  hey you can see i just updated the borg version its now 1.1.14 and still the same issue please see attached screen shot

**Comment by ThomasWaldmann** [comment]
Find out the id of that repo:
```
borg config REPO id
```

Check for the key:
```
ls -lR ~/.config/borg/THATID
```

**Comment by asadkhan34** [comment]
![image](https://user-images.githubusercontent.com/75013154/100234520-0783d680-2f4d-11eb-8a33-10e4f7dc9ea4.png)
 Please find the attached image i ran both of the commands you mentioned , and i dont have others users than root on this container .

**Comment by ThomasWaldmann** [comment]
look again at the cmds, had to fix them.

On 25 November 2020 14:37:58 CET, asadkhan34 <notifications@github.com> wrote:
>![image](https://user-images.githubusercontent.com/75013154/100234520-0783d680-2f4d-11eb-8a33-10e4f7dc9ea4.png)
>Please find the attached image i ran both of the commands you mentioned
>, and i dont have others users than root on this container . 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/5521#issuecomment-733711203

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by asadkhan34** [comment]
Sorry @ThomasWaldmann  i didn't get what you said . 

What should I need to check again ?

**Comment by asadkhan34** [comment]
@ThomasWaldmann  brother waiting for your reply .

**Comment by ThomasWaldmann** [comment]
I sent a reply via email, but it seems that it did not make it up to here.

Just execute the commands again as you see them now in my post above.

**Comment by ThomasWaldmann** [comment]
About your post there: https://github.com/borgbackup/borg/issues/5521#issuecomment-733711203

Please do not post images, but copy & paste text, if possible.

Also, why does it say `cannot access`? You are root, you should be able to access.

It seems that you have some strange issue there, which is not a borg issue though.

I still need the `ls -l` for the keys directory.

**Comment by asadkhan34** [comment]
it doest not have any issue with permissions , i ran wrong command just find the commands below i ran again 
root@dev-abbottberg:/mnt/backups/dev-abbottberg# ls -l ~/.config/borg/keys
total 2

**Comment by asadkhan34** [comment]
root@dev-abbottberg:~/.config/borg/keys# ls
mnt_backups_dev_abbottberg

here you can see the key exists there at path

**Comment by ThomasWaldmann** [comment]
Please show the first, second and last line from the output of:
```
cat ~/.config/borg/keys/mnt_backups_dev_abbottberg
```

**Comment by ThomasWaldmann** [comment]
Also you did not show yet correct ls -l output... (that would include owner/group/permissions).

**Comment by asadkhan34** [comment]
cat ~/.config/borg/keys/mnt_backups_dev_abbottberg

first, second and last line from the output of above command 

BORG_KEY ca98029680750a8980ec08eef2c1720976fe4af68466ac29b1fdd1afda64e3db
hqppdGVyYXRpb25zzgABhqCpYWxnb3JpdGhtpnNoYTI1Nqd2ZXJzaW9uAaRzYWx02gAgPN
4SEDb+w5c1xmlyKpAheUkmAuzYdE3kC8XhzwrjYRI+MJv3xZ3ng=

**Comment by asadkhan34** [comment]
ls -l output
drwx------ 2 root root   3 Nov 25 08:09 .
drwx------ 4 root root   4 Nov 25 08:09 ..
-rwx------ 1 root root 553 Nov 25 08:09 mnt_backups_dev_abbottberg

**Comment by ThomasWaldmann** [comment]
The file format of the key looks correct, but the repo id there (see the value directly after BORG_KEY) does not match your repo id.

So, this is not the correct key / not the repo for that key.

**Comment by ThomasWaldmann** [comment]
So, check if you have a key elsewhere, the repo id must match.

You can also have a look at `repo_dir/config`, if there is a key in there (but usually that one is found without an issue).
