### ISSUE TITLE
kill config and permissions for travis-ci?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5528]
considering that travis-ci is not needed any more (we have github actions now), remove the configuration for it?

affected repos: borg, borg-import, borgbackup.github.io

also: remove travis permissions to borgbackup repos / organization.

**Comment by Gu1nness** [comment]
I'll remove the travis configuration, but I'm not sure I can remove the travis permissions for borgbackup repos / organization

**Comment by ThomasWaldmann** [comment]
I wanted to collect some feedback first.

As both github and travis-ci are companies, we might run into similar issues with both, so keeping the travis config might be an idea.

OTOH, maintaining the travis config just for the case and running into out of credits issues regularly might be also too much pain.

**Comment by Gu1nness** [comment]
The only idea I could see to be sure to avoid this kind of problem would be to mirror it on a gitlab instance with gitlab runners.
I can provide it for borg if necessary, I have the processing power of my dedicated server.

**Comment by ThomasWaldmann** [comment]
Well, I also have servers, but I rather want to avoid the single server / single admin issues.

Maybe some day codeberg could be an alternative.

But you're right, we can fetch it from git history if needed.

**Comment by ThomasWaldmann** [comment]
https://github.com/organizations/borgbackup/settings/oauth_application_policy
access to private infos now denied there for travis / travis open-source

https://github.com/organizations/borgbackup/settings/installations
travis github app uninstalled from there

travis ci now says "could not find borgbackup organization".

so guess this is mostly done.

todo: update references to travis in docs -> "github workflow" or "github action".
