### ISSUE TITLE
After back up and read error fat32 partition becomes read only

### ISSUE THREAD

**Issue by OneArb** [borgbackup/borg#5530]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.14

#### Operating system (distribution) and version.

Manjaro

#### How much data is handled by borg?

400 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```/usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 ```

## Describe the problem you're observing.

After a successful backup, fat32 partition becomes read only, a lock icon displays besides each file and I get a "read only file system" when trying to write to files.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes

I ran ```borg break-lock``` on the archive.

I deleted the file creating the read error which solved the issue.

Is it expected behavior the volume remains in read only mode upon read error?

#### Include any warning/errors/backtraces from the system logs

vorta.borg.borg_thread - WARNING - [some file name] read: [Errno 5] Input/output error

**Comment by ThomasWaldmann** [comment]
guess you never want to hide "E" (error), so it should be `--filter=AME`.

if a file system suddenly becomes read-only, it might be because of a hardware issue. if an error happens, the fs might "remount-ro" (see mount options, see defaults). you need to umount, fix the issue, re-mount then.

input/output error aka IOError usually point to an issue below borg, e.g. hardware, kernel, fs.

**Comment by ThomasWaldmann** [comment]
ehrm, is that commandline (and esp. the --filter value) automatically created by vorta?

**Comment by OneArb** [comment]
Yes, I don't think options can be modified from the GUI.

Got it, only the repository can get locked rather than the volume.
