### ISSUE TITLE
TZ issues within automated tests

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5535]
commet by @amikula from https://github.com/borgbackup/borg/pull/5332#issuecomment-708529283 : 

One thing I don't like about the tests is that they're somewhat **dependent on the developer's time zone**, because command line timestamps are in UTC but prune interprets the timestamps in local time.

I've compensated for that by getting the current timezone and offsetting from UTC accordingly in the tests. Also note that **DST changes are not accounted for**. I've put the test timestamps at midday so there won't be problems with this, but it's a kludge that may bite someone later on down the road.

The alternative of calculating the correct local offset for a particular day doesn't seem to be handled by Python core libraries, so I think the tests would need to **bring in a new library to handle localtime correctly for dates in the past**. Even then, the offset for the tests will be different depending on the environment's timezone, so it's probably best to **bring in a testing library** (eg. freezegun) to **make the tests independent of the test environment's timezone**.

**Comment by FelixSchwarz** [comment]
Just wanted to mention that [freezegun](https://github.com/spulec/freezegun/) did work very well for me (in other projects) so +1 for that.

**Comment by ThomasWaldmann** [comment]
Likely fixed by #7282 in master branch.
