### ISSUE TITLE
archlinux box is broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5543]
virtualenv in the archlinux vagrant box is broken (master branch).

guess it has something to do with that line in the Vagrantfile:
```
pacman --sync --noconfirm --refresh python-virtualenv python-pip
```

This seems to do a partial upgrade and afterwards it doesn't work any more.

`virtualenv` is not on the base system - how do I get it without upgrading a ton of stuff and without introducing inconsistencies?

**Comment by samuel-w** [comment]
I think it can be replaced with 
`pacman --sync --upgrade --noconfirm --refresh python-virtualenv python-pip`

**Comment by ThomasWaldmann** [comment]
arch64: error: only one operation may be used at a time

**Comment by samuel-w** [comment]
`pacman -Syu --noconfirm python-virtualenv python-pip`
This is the shorthand, before `pacman --sync --refresh` was running, which is equivalent to 'pacman -Sy', which is a bad thing apparently. https://bbs.archlinux.org/viewtopic.php?id=89328

**Comment by samuel-w** [comment]
If you want to avoid upgrades maybe `pacman -Su --noconfirm python-virtualenv python-pip`? I assume the vagrant VM is updated  every month.

**Comment by ThomasWaldmann** [comment]
pacman -Su --noconfirm python-virtualenv python-pip just gives a ton of 404...

**Comment by samuel-w** [comment]
Oh yeah, its because the mirrors delete old packages. Use `pacman -Syu --noconfirm python-virtualenv python-pip`.

**Comment by samuel-w** [comment]
Are the VMs persistent? If so, then upgrading on every run is fine.

**Comment by ThomasWaldmann** [comment]
No, i usually destroy the vm after testing.

**Comment by samuel-w** [comment]
I guess it will have to upgrade every time, or keep the VM persistent.

**Comment by ThomasWaldmann** [comment]
that pulls 400MB+ although i justed updated the vagrant box to the latest available one...

**Comment by samuel-w** [comment]
If you keep updating the vagrant box, it _might_ be fine to run  `pacman -S --noconfirm python-virtualenv python-pip`. It will break when the package mirrors update `python-virtualenv' or `python-pip`.

**Comment by ThomasWaldmann** [comment]
and installs kernel, firmware, builds dkms stuff.......................

but at least it seems to work now, thanks!

**Comment by samuel-w** [comment]
Another solution would be to use the Arch Linux Archive, but it defeats the point of testing on rolling release. https://archive.archlinux.org/repos/
