### ISSUE TITLE
vagrant: archlinux box misses fuse kernel module

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5547]
```
    arch64: ERROR:   py39-fuse2: commands failed
    arch64: ERROR:   py39-fuse3: commands failed

$ sudo modprobe fuse
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.9.10-arch1-1

$ uname -a
Linux arch.band.it 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux
```

**Comment by samuel-w** [comment]
Add `fuse2` to `pacman -Syu --noconfirm python-virtualenv python-pip`, making it `pacman -Syu --noconfirm python-virtualenv python-pip fuse2`

**Comment by samuel-w** [comment]
Although python-llfuse uses only fuse2 on Arch.

**Comment by ThomasWaldmann** [comment]
i added it to the pacman line to install fuse2/fuse3, plus a modprobe fuse directly after that.
does not work, doesn't find the fuse module.

if i reboot the vm, modprobe fuse works, but i can't do that for the vagrant test run.

**Comment by ThomasWaldmann** [comment]
it seems to have a fuse kernel module only for the new kernel (also installed by that pacman invocation), but not for the running kernel.

**Comment by ThomasWaldmann** [comment]
I'll remove the arch linux box for now.

If somebody would like to re-add it: feel welcome to fix the issues and make a PR.
