### ISSUE TITLE
vagrant brew cask

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5557]
When installing `osxfuse`:

```
    darwin64: Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.                                                                                                                 
```

**Comment by samuel-w** [comment]
Seems the solution is replacing
`        brew install homebrew/cask/osxfuse || brew upgrade homebrew/cask/osxfuse  # Required for Python llfuse module`
with
`        brew install --cask osxfuse || brew upgrade --cask osxfuse  # Required for Python llfuse module`
