### ISSUE TITLE
borg always rechunks new files after cache deletion

### ISSUE THREAD

**Issue by schuellerstefan** [borgbackup/borg#5564]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.1.14

#### Operating system (distribution) and version.

arch x64 latest

#### Hardware / network configuration, and filesystems used.

btrfs

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

1. Create borg repository
2. Add a file (e.g. 10 GB) called "a" into a directory to archive
3. Remove associated cache dir in ~/.cache/borg/
4. Add another file (e.g. 10 GB) called "b" into the same directory as "a" was stored
5. Create a new archive. "a" and "b" are rechunked since they are not in the cache
6. Create a new archive again. "a" and "b" should be taken from the cache, but only "a" is taken. "b" is rechunked again

**Comment by ThomasWaldmann** [comment]
see the faq.

On 13 December 2020 12:54:38 CET, schuellerstefan <notifications@github.com> wrote:
>
>
>## Have you checked borgbackup docs, FAQ, and open Github issues?
>
>Yes
>
>## Is this a BUG / ISSUE report or a QUESTION?
>
>Bug
>
>## System information. For client/server mode post info for both
>machines.
>
>#### Your borg version (borg -V).
>
>borg 1.1.14
>
>#### Operating system (distribution) and version.
>
>arch x64 latest
>
>#### Hardware / network configuration, and filesystems used.
>
>btrfs
>
>## Describe the problem you're observing.
>
>#### Can you reproduce the problem? If so, describe how. If not,
>describe troubleshooting steps you took before opening the issue.
>
>1. Create borg repository
>2. Add a file (e.g. 10 GB) called "a" into a directory to archive
>3. Remove associated cache dir in ~/.cache/borg/
>4. Add another file (e.g. 10 GB) called "b" into the same directory as
>"a" was stored
>5. Create a new archive. "a" and "b" are rechunked since they are not
>in the cache
>6. Create a new archive again. "a" and "b" should be taken from the
>cache, but only "a" is taken. "b" is rechunked again
>
>#### Include any warning/errors/backtraces from the system logs
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/5564

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by schuellerstefan** [comment]
Hi Thomas,

thanks for pointing that out. This is a over simplified example of my problem.
I've already read that but thought I wouldn't be affected.
In my scenarion it was rechunking several TBs over and over again.

The reason for that is that I put a big bunch of files into my backup folder by mv'ing them into it, thus causing them to get all the same ctime timestamp.

Is there a paritcular reason why ctime instead of mtime is used?

**Comment by ThomasWaldmann** [comment]
ctime instead of mtime: because it is more reliable (only under kernel control, no userspace code can change it in weird ways).

if you want to avoid the issue described in the faq, just do a `touch backupdata/somefile` before starting `borg create` - so somefile will have the most recent timestamp and not one of your huge files.

**Comment by ThomasWaldmann** [comment]
btw, borg uses a (theoretically) nanosecond resolution timestamp, so even a `mv` should not create a lot of identical timestamps.

**Comment by schuellerstefan** [comment]
I just wrote that code snippet

```
import os
import sys
import collections

ctimes = {}

for dirpath, dnames, fnames in os.walk(sys.argv[1]):
	for f in fnames:
		abs_path = dirpath + os.sep + f
		if not os.path.isfile(abs_path):
			continue

		stat = os.stat(abs_path)
		if stat.st_ctime_ns in ctimes:
			ctimes[stat.st_ctime_ns] = ctimes[stat.st_ctime_ns] + 1
		else:
			ctimes[stat.st_ctime_ns] = 1


sort = {}
unique = 0
non_unique = 0

for time, count in ctimes.items():
	if count == 1:
		unique = unique + 1
		continue
	non_unique = non_unique + count
	if not count in sort:
		sort[count] = []
	sort[count].append(time)
for key in sorted(sort.keys()):
	print('duplicate timestamps for {} count: {}'.format(sort[key], key))

print('unique entries: {} duplicates: {}'.format(unique, non_unique))
```
and it prints:

```
duplicate timestamps for [1607726597982137305] count: 17
duplicate timestamps for [1606253943186263804] count: 25
duplicate timestamps for [1607848023975570760] count: 33
duplicate timestamps for [1607726465511110353] count: 162
duplicate timestamps for [1607726465521110431] count: 287
duplicate timestamps for [1607726465514443713] count: 289
duplicate timestamps for [1607726465517777072] count: 290
unique entries: 859 duplicates: 12520
```
So the timestamp (at least on btrfs) is quite unprecise. Which in my case caused a lot of rechunking what made me thought the cache was broken because it were so many files.

Thank you for clarification, Thomas

**Comment by ThomasWaldmann** [comment]
Interesting, would have expected more different timestamps.

But anyway, you know how to solve it now.
