### ISSUE TITLE
borg repo filesystems

### ISSUE THREAD

**Issue by manfredlotz** [borgbackup/borg#5567]
Note: this question is about pcloud filesystem, but the answer applies to all filesystems in general.

This is borg 1.1.14 running on Fedora 33 Linux. I am trying to find out if it is possible to backup into a borg repository residing on a mounted pCloud drive.

It is important to note that pCloud doesn't support hardlinks.

When doing a `borg init` I get
```
Failed to securely erase old repository config file (hardlinks not supported>).
Old repokey data, if any, might persist on physical storage.
```
Questions:

What is the impact of having no hardlink support available on pCloud?

Is borg usable to backup to a borg repository on pCloud or should I better not do this? 

Thanks a lot.

**Comment by ThomasWaldmann** [comment]
I don't know pcloud, but the most important requirement for a fs for a borg repo is mainly stability / reliability.

We try to optimize some stuff (for security or performance) using hardlinks, but usually you can also work without.

In the docs we have some more words about the requirements, but in general, it is not much.

Of course, if your fs would not behave like a normal filesystem, had bugs, was not behaving consistently, was slow, that would rather speak against using it.

**Comment by manfredlotz** [comment]
Thanks for your quick reply.

I did more testing and it seems things working fine. So, if hardlinks are not really important then I am not so much concerned.
