### ISSUE TITLE
Clarification on the (--one-file-system) option and FILES SPECIALS with regulars files in repo

### ISSUE THREAD

**Issue by vincenzogianfelice** [borgbackup/borg#5573]
Hi. I ran into a backup of the whole system with borg and couldn't help but notice a little headache. Since some _folders_ in UNIX are dynamically generated on each boot (like `sys`, `proc`, `dev`, ...) if I use the **--one-file-system** option, rightly so, it doesn't copy them. 
But (which happened to me) the presence of these folders is essential for the correct system startup. In fact, i happened to access via linux live again and manually create the folders in question (`proc`, `sys`, `run`, `dev`). The question is: **_is there a way to_** (while using the option in question) **_copy ONLY  the folders_** (while preserving their permissions)?

(I am using version **1.0.9** ... this is the one of the system I currently use)
Thanks and sorry for my english

**Comment by vincenzogianfelice** [comment]
> Hi. I ran into a backup of the whole system with borg and couldn't help but notice a little headache. Since some _folders_ in UNIX are dynamically generated on each boot (like `sys`, `proc`, `dev`, ...) if I use the **--one-file-system** option, rightly so, it doesn't copy them. But (which happened to me) these folders (at least their presence) is essential. In fact, I happened to access live again and manually create the folders in question (`proc`, `sys`, `run`, `dev`). The question is: is there a way to (while using the option in question) copy _ONLY_ the _folders_ (while _**preserving**_ their **_permissions_**)?
> 
> Thanks and sorry for my english

**Comment by ThomasWaldmann** [comment]
```
mkdir /rootfs
mount --bind / /rootfs
borg create repo::archive /rootfs
```

And borg 1.0.9 is outdated and unsupported, you should use 1.1.latest (e.g. download some binary from github releases if your distribution does not offer it, check glibc in borg's readme).

**Comment by vincenzogianfelice** [comment]
> And borg 1.0.9 is outdated and unsupported, you should use 1.1.latest (e.g. download some binary from github releases if your distribution does not offer it, check glibc in borg's readme).

Yes, I'll be upgrading soon.

As for the "solution" ... I didn't quite understand what you did ... you mounted **/** in a new folder ... and what changes compared to using **/**?

**Comment by vincenzogianfelice** [comment]
> E borg 1.0.9 è obsoleto e non supportato, dovresti usare 1.1.latest (ad esempio, scarica alcuni binari dalle versioni di github se la tua distribuzione non lo offre, controlla glibc nel readme di borg).

Sì, aggiornerò presto.

Per quanto riguarda la "soluzione" ... I solved the classic way, that is (once the backup has been restored) manually create the various directories. It would be nice though if there was an option to at least copy the "root" directories (with the --one-file-system option).

Thanks anyway.

**Comment by ThomasWaldmann** [comment]
You can not access the directories where another filesystem is mounted, because there is the other fs mounted there, hiding the underlying directory.

With the bind-mount method I showed, only the underlying fs is mounted to another places and thus makes these directories accessible. Often they are empty, but in case of `/dev` there is usually a set of basic files in there.

**Comment by ThomasWaldmann** [comment]
guess this is solved.
