### ISSUE TITLE
pytest deprecation warning about yield_fixture

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5575]
pytest 6.2.1:
```
/vagrant/borg/borg/.tox/py36-none/lib/python3.6/site-packages/borg/testsuite/remote.py:73:
    PytestDeprecationWarning: @pytest.yield_fixture is deprecated.                                                                        
Use @pytest.fixture instead; they are the same.
Docs: https://docs.pytest.org/en/stable/warnings.html  
```

This should be fixed globally.

**Comment by ThomasWaldmann** [comment]
I've seen this in master branch, but guess it also applies to 1.1-maint.

**Comment by FelixSchwarz** [comment]
Just wanted to note that this makes it harder to ship borgbackup in EPEL 7 as we have pytest 2.9.2 there. Not a big deal to create a patch for this issue but I hope we can keep using pytest 2.9 for some time.

**Comment by ThomasWaldmann** [comment]
OK, so we need to revert #5577 and:
- suppress the deprecation warning
- or, use a pytest version that does not emit the warning

**Comment by FelixSchwarz** [comment]
I already added a revert manually: https://src.fedoraproject.org/rpms/borgbackup/tree/epel7

Also I don't think you have to revert this patch upstream. This is a patch with a straight-forward revert which I can carry for EPEL7. Of course official support for pytest 2.9 would be a bit easier but I don't want to place an unreasonable burden on upstream development.

**Comment by ThomasWaldmann** [comment]
OK, so we'll keep it as is. Thanks for patching.
