### ISSUE TITLE
Borg backups entire /home directory even though I specified to backup /home/[username].

### ISSUE THREAD

**Issue by LiterallyJohnny** [borgbackup/borg#5588]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

Bug.

#### Your borg version (borg -V).

borg 1.1.14

#### Operating system (distribution) and version.

Arch Linux, rolling release.

#### Hardware / network configuration, and filesystems used.

Connected to home wifi, attempting to backup my user's home directory to an external drive.

#### How much data is handled by borg?
About 20GB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Initialize repo:
```
borg init --encryption=repokey mountpoints/backups/
```
Create first backup:
```
borg create --stats --progress -v -e ~/.cache -e ~/mountpoints ~/mountpoints/backups/::{hostname}_{now} /home/johnny/
```

## Describe the problem you're observing.

I am trying to backup my user's home directory (/home/johnny) but whenever I run run the backup and restore it into a test folder, it backups the entire directory (/home). I am not trying to backup the entire directory, which includes the directories for the other users on my computer. I am trying to backup JUST /home/johnny.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Follow the user guide. Initialize the repo, create a backup for /home/[username], and then restore it.

**Comment by ThomasWaldmann** [comment]
Please simplify the borg command to the minimum you need to reproduce your issue.

**Comment by LiterallyJohnny** [comment]
It said to use the full command that lead to my problem. That's what I did.

**Comment by ThomasWaldmann** [comment]
Yup, it is useful to not give less than needed to reproduce, so the full command is kind of safe.

But it is also useful to determine the minimum command needed to reproduce, just to have less code running / a less special case.

**Comment by ThomasWaldmann** [comment]
Can't reproduce, it only backed up 1 file for me that was in the given directory.
```
$ borg create --stats --progress -v -e ~/.cache -e ~/mountpoints ~/w/borg/repo/::{hostname}_{now} /home/foo/
Creating archive at "/home/user/w/borg/repo/::{hostname}_{now}"
------------------------------------------------------------------------------                                                                                                                                                          
Archive name: development_2020-12-24T21:23:59
Archive fingerprint: 586ff093a7e129c32014b1310c6a95dc271c51839beeddc9046049b463e8026d
Time (start): Thu, 2020-12-24 21:23:59
Time (end):   Thu, 2020-12-24 21:23:59
Duration: 0.01 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  913 B                711 B                711 B
All archives:               25.52 MB             10.41 MB             10.40 MB

                       Unique chunks         Total chunks
Chunk index:                     485                  488
------------------------------------------------------------------------------
```

**Comment by ThomasWaldmann** [comment]
```
(borg-env) user@development:~/w/borg$ ls -lR /home/foo
/home/foo:
total 4
drwxrwxr-x 2 user root 4096 Dec 24 21:23 bar

/home/foo/bar:
total 0
-rw-r--r-- 1 user user 0 Dec 24 21:23 baz
```

**Comment by LiterallyJohnny** [comment]
Hmm. I'm a bit confused as to what this means, but I might just be a little slow, lol.

**Comment by ThomasWaldmann** [comment]
See that:
```
Number of files: 1
```
So it just backed up the one file inside /home/foo, as expected - not all inside /home.

**Comment by LiterallyJohnny** [comment]
Hmm. I am so confused now. I believe I did the same thing, but it gives me the entire /home directory when I restore it.

**Comment by ThomasWaldmann** [comment]
If you back up `/home/user`, it will back up:
- the directory object `home`
- the directory object `user`
- everything inside directory `user` (except if you exclude it)

And if you extract that, it will extract:
- home
- user
- all inside user

**Comment by LiterallyJohnny** [comment]
How would I go about making it where it ignores `/home` and backup `/user`?

**Comment by LiterallyJohnny** [comment]
Dammit, didn't mean to close it.

**Comment by ThomasWaldmann** [comment]
```
cd /home
borg create repo::archive user
```

or, just do it as you have it now and strip the directory levels at extract time.

**Comment by LiterallyJohnny** [comment]
Is there not like a flag or option I could use to do this? I would rather not strip the directory levels at extraction, and I'm trying to make a script for this.

**Comment by ThomasWaldmann** [comment]
there is no strip at create time because it can be done like i posted.

**Comment by ThomasWaldmann** [comment]
guess this is cleared. not a bug, just expectations vs. reality. :-)
