### ISSUE TITLE
remove travis references from docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5589]
s/travis ci/CI system/g

except if it is rather specific, then "github actions" / "github actions CI".

**Comment by samuel-w** [comment]
They seem to be gone
https://github.com/borgbackup/borg/search?q=travis

**Comment by ThomasWaldmann** [comment]
Not sure how good the gh search function is. Also: check both master and 1.1-maint branch.

**Comment by samuel-w** [comment]
Both have no references in the docs, can't do a github search on non-master 
https://borgbackup.readthedocs.io/en/master/search.html?q=travis&check_keywords=yes&area=default
https://borgbackup.readthedocs.io/en/stable/search.html?q=travis&check_keywords=yes&area=default

**Comment by ThomasWaldmann** [comment]
Strange, I can't find it any more either. So let's close this, thanks!
