### ISSUE TITLE
1.1.15 xxh64 bundled-> xxHash library new dependency?

### ISSUE THREAD

**Issue by kubedzero** [borgbackup/borg#5591]
I just tried using the new version 1.1.15 to print out the version `borg --version` and received an error `libxxhash.so.0: cannot open shared object file: No such file or directory`.

I see in the changelog https://borgbackup.readthedocs.io/en/stable/changes.html?highlight=libxxhash `enable using libxxhash instead of bundled xxh64 code` which seems to suggest a dependency change not mentioned in the "Compatibility notes" section of the changelog.

Is there an expectation that `xxHash` needs to be independently installed (the latest version I see for my Slackware OS is [0.8.0](http://slackware.cs.utah.edu/pub/slackware/slackware64-current/slackware64/l/xxHash-0.8.0-x86_64-1.txz)) prior to installing BorgBackup, or is there a way to still use the bundled `xxh64` code for a reduced dependency tree? 

For reference, Installing `xxHash` separately allows me to run `borg --version` as expected on version 1.1.15

**Comment by ThomasWaldmann** [comment]
How did you install borg before running into this issue?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.1.15/setup.py#L217 that is the place where it detects the libxxhash system location. if it finds it AND prefer_system_libxxhash is True (default), then it uses libxxhash, otherwise it should fall back to the bundled code.

**Comment by kubedzero** [comment]
Got it, thanks! Looks to be that I compiled BorgBackup on a system that had xxHash installed and then ported the compiled package over to a system that did not have it installed, thus the issue. 

Let me experiment a bit and I'll update this issue.

**Comment by kubedzero** [comment]
That explanation really helped, thanks so much! I [updated](https://github.com/kubedzero/unRAID-NerdPack/blob/master/source/SlackBuild/borgbackup/borgbackup.SlackBuild#L77) my SlackBuild to turn the `prefer_system_libxxhash` to `False`, recompiled, copied the package over to the `xxHash`-less OS, and confirmed it worked as expected.
