### ISSUE TITLE
BORG_FILES_CACHE_SUFFIX: a couple of followups

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#5602]
BORG_FILES_CACHE_SUFFIX (included in 1.1.15+ #5511 and 1.2.0b1+ #5433) is a much better way to deal with the multiple backup sets on the same repo than the old BORG_FILES_CACHE_TTL way. A couple suggestions as a followup:

1. please consider updating this section: https://borgbackup.readthedocs.io/en/stable/faq.html#always-chunking to use BORG_FILES_CACHE_SUFFIX rather than BORG_FILES_CACHE_TTL.
2. maybe also consider reducing default value of BORG_FILES_CACHE_TTL, so to encourage using BORG_FILES_CACHE_SUFFIX with multiple sets.

**Comment by ThomasWaldmann** [comment]
Well, both methods exist in parallel and do different things, so one can even combine both to reduce memory needs.

**Comment by FabioPedretti** [comment]
One of the two examples linked at https://borgbackup.readthedocs.io/en/stable/faq.html#always-chunking talks about the "different data sets" use-case on the same machine:
`So, for example, if you do daily backups of 26 different data sets A, B, C, …, Z on one machine...`
I think this is the really perfect use case for suggesting BORG_FILES_CACHE_SUFFIX rather than the currently proposed increasing of BORG_FILES_CACHE_TTL. Not only you'll have the cache for every set, but you'll also only load the useful cache, avoiding the useless ones.

Hoping it can help someone else, with my use-case, using it I decrease my backup time from over 4h:30m to less than 3h:00m. 
My use case is 18 sets, most very small, a couple big. Initially I had a huge "files" cache file, now the bigger files.X is ~380MB, another files.Y ~101MB, and many other < 1 MB files.Z.
Specifically, the backup time for the many smaller sets went from 4m:30s to 1m:20s each (so, most of the time of smaller sets was previously spent loading useless caches).

For some more information here is also the actual server CPU usage:
![borg](https://user-images.githubusercontent.com/3390837/107122298-3d233500-6897-11eb-916f-707b31182da3.png)
- The first 3 peaks are before using BORG_FILES_CACHE_SUFFIX.
- (Ignore the following 2 peaks)
- The last 2 peaks are after using BORG_FILES_CACHE_SUFFIX.

Not only the backup completes a lot faster, but max/average CPU usage is also lower (from 2,5/2GHz to about 1,5/1,5GHz).

**Comment by ThomasWaldmann** [comment]
Yes, if one has a lot of stuff, one can nicely tweak it.

OTOH, if one doesn't, one can also go for ease-of-use and just use 1 files cache.

**Comment by ThomasWaldmann** [comment]
@FabioPedretti see #6659.
