### ISSUE TITLE
Append-only mode in authorized_keys only keeps last transaction's files (hints, index, integrity)

### ISSUE THREAD

**Issue by ju-kreber** [borgbackup/borg#5605]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Both? Maybe I'm doing something wrong, maybe there is a bug

#### Your borg version (borg -V).
Server: `borg 1.1.14`
Client: `borg 1.1.15`

#### Operating system (distribution) and version.
Server: Linux 3.4 armv5 (QNAP NAS)
Client: Linux Mint 18 (Linux 4.15 x86_64)

#### Hardware / network configuration, and filesystems used.
Server: QNAP NAS with borgbackup from Entware (opkg), regular ext4 filesystem
Client: Ordinary linux computer with ext4 / ntfs

#### How much data is handled by borg?
toy examples

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
various simple `borg create` or `borg delete`

## Describe the problem you're observing.

Backup is done over ssh. For the user that owns the borg repository on the server, there exist two distinct ssh keys: One plain key that is used for automated backup from the client machine and another encrypted one for occasionally logging in and managing the repo. Both keys are in the `authorized_keys` for that user and most importantly, the "backup"-key is prefixed with
```
command="borg serve --restrict-to-path /share/Backup/borg_repos --append-only",restrict ssh-rsa abcd....
```
as shown in the docs. The goal is to prevent corrupted backups should the client be compromised. Note that the repository itself is *not* in append-only mode since I want to manage it from time to time, removing old backups once I'm sure the newer ones are okay. If I understood the docs correctly, it is intended to be done just like this.

Now I would expect all operations emitted by the client (with the "backup" key) to create a new transaction in the repo dir. Indeed, each command generates a new line in the `transactions` file. However, the other three files (hints, index, integrity) only exist for the most recent transaction, e.g. `ls` gives

```
README        config        data/         hints.18      index.18      integrity.18  nonce         transactions
```

This looks like I'm not able to revert certain transactions, which is bad. So I'd like to ask if I understood something wrong about how to use borg or if there actually could be a bug somewhere.

Regards

**Comment by ThomasWaldmann** [comment]
We have some docs about how to use append-only mode, please read them.

Keeping hints/index/integrity is not needed.

**Comment by ju-kreber** [comment]
Well, seems like I indeed went through the docs too quickly, sorry for that!

For anyone else stumbling across the same thing as me: `hints`, `index` and `integrity` really only exist for the last transaction; the files that have to be removed for all transaction you want to revert are in the `data` directory.
