### ISSUE TITLE
Open github discussion?!?

### ISSUE THREAD

**Issue by jedie** [borgbackup/borg#5616]
What's about to activate github discussion functionality?

I take a look into borg backup. Maybe i will close development on my https://github.com/jedie/PyHardLinkBackup and use borg.

For "easy" install i created https://github.com/jedie/borgbackup-install ... This is something i would start a discussion ;)

**Comment by ThomasWaldmann** [comment]
https://mail.python.org/mailman/listinfo/borgbackup

there is this mailing list, so not sure what we'll win by using github discussions.
there would be more vendor lock-in for sure, though.

**Comment by ThomasWaldmann** [comment]
Thanks for considering borg - maybe have a look into the source, contributions and feedback is welcome!

**Comment by ThomasWaldmann** [comment]
btw, i never used gh discussions yet. so if i am missing something, just tell.

**Comment by RonnyPfannschmidt** [comment]
for pytest it was nice to have a conversation barrier be removed for user questions

IMHO mailing lists are icky, i consider them a broken nuisance, its just that we have no sane replacements :/

**Comment by jedie** [comment]
Yes it's another vendor lock-in ... That's sad. I hope that github alternatives are get into federation with shared user profiles etc.

But yes, it's just another easy to use way to discuss, instead of create issues like this ;)

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/discussions is open!
