### ISSUE TITLE
borg is taking 8-15 seconds to startup on macOS Catalina

### ISSUE THREAD

**Issue by Mehuge** [borgbackup/borg#5617]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

borg-macosx64 1.1.15

#### Operating system (distribution) and version.

macOS Catalina (10.15.7)

#### Hardware / network configuration, and filesystems used.

NA

#### How much data is handled by borg?

NA

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`./borg-macosx64 -V`

## Describe the problem you're observing.

Borg takes ages to start up.
Binary from: https://github.com/borgbackup/borg/releases/download/1.1.15/borg-macosx64

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

```
$ time ./borg-macosx64 -V
borg-macosx64 1.1.15

real	0m10.783s
user	0m0.521s
sys	0m0.324s
```

#### Include any warning/errors/backtraces from the system logs

NA

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/releases/download/1.1.15/borg-macosx64.tgz use that one (directory-based), not the single-file one.

That'll save you some startup time for the 2nd+ startup.

**Comment by ThomasWaldmann** [comment]
Also, this is a problem caused by your OS.

**Comment by Mehuge** [comment]
I could not for the life of me get the directory based version working. After getting past OSX refusing to run the exe, I got an error about not being able to run Python, due to system policy. Not able to find instructions on how to get the dir version to work on macos, so gave up.

The installation instructions (https://borgbackup.readthedocs.io/en/stable/installation.html) do not specifically mention using brew to install borgbackup, its kind of eluded to if the reader spots it and makes the connection, but no explicit instruction.

I notice now that installation.rtp does mention it:-

`brew cask install borgbackup`
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
`brew install --cask borgbackup`
Error: Cask 'borgbackup' is unavailable: No Cask with this name exists.
`brew install borgbackup`
success!

I then spotted from one of your issues `borgbackup/tap/borgbackup-fuse`

`brew install borgbackup`
`brew install borgbackup/tap/borgbackup-fuse`

borg initially took a few seconds to launch, subsequently launches instantaneously.

**Comment by ThomasWaldmann** [comment]
sure, if you can use the brew tap, that's better in any case.

**Comment by ThomasWaldmann** [comment]
About that:

"I could not for the life of me get the directory based version working. After getting past OSX refusing to run the exe, I got an error about not being able to run Python, due to system policy."

Can you open a separate issue for this? When I set up the directory build, I tested it and it worked for me.
