### ISSUE TITLE
"--one-file-system" and "see the docs" ?!?

### ISSUE THREAD

**Issue by jedie** [borgbackup/borg#5618]
https://borgbackup.readthedocs.io/en/stable/usage/create.html contains this:

![grafik](https://user-images.githubusercontent.com/71315/103924382-38dbee80-5116-11eb-893b-3bdb761cc3a7.png)

Where are the docs with more information about this?

search with `one-file-system` brings no more information: https://borgbackup.readthedocs.io/en/stable/search.html?q=one-file-system

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/create.html#description

see the last paragraph there.

**Comment by jedie** [comment]
Ah! Great. Than is should be renamed to "see below" ?

**Comment by ThomasWaldmann** [comment]
Yeah, could be changed to "see below".

If one invokes `borg create --help`, it is also "below".
