### ISSUE TITLE
better locking

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#562]
misc ideas to improve locking.

**Comment by enkore** [comment]
Regarding *locking with context managers to avoid stale locks on forgotten .close calls etc.*

An implementation idea would be to stack a decorator on top of a context manager: Practically all do_XYZ() methods of Archiver open a repo, use it all the time, and close (or don't) it at all of the exit points. If we use a context manager, we'll have an additional indent for all these methods over their entire spawn: not pretty. If we wrap the CM in a decorator we avoid that, and can deduplicate some code at the same time.

```
class Archiver:
    def do_blah(self, args):
        repository = self.open_repository(args, exclusive=True)
        manifest, key = Manifest.load(repository)
        # do stuff

    # With a context manager:

    def do_blah(self, args):
        with self.open_repository(args, exclusive=True) as repository:
            manifest, key = Manifest.load(repository)
            # do stuff

    # Now let's get a decorator in the spirit of open_repository (pseudo code)

    def open_repository(function):
        @wraps
        def wrapper(args, **kwargs):
            with (do stuff from open_repository) as repository:
                function(args, repository=repository, **kwargs)
        return wrapper

    @open_repository
    @load_manifest
    def do_blah(self, args, repository, manifest, key):
        # do stuff
```

This kind of decorator stacks (as I tried to express with `@load_manifest`), so even more code dedup.

**Comment by enkore** [comment]
#1049 is another bit for this.

I think the only thing missing now is a repo config item "i_the_user_promise_that_i_wont_access_this_repo_over_sshfs_nfs_or_whatever" that allows removing locks via a PID check on the roster. Off by default.

**Comment by ThomasWaldmann** [comment]
and then another admin of same server moves the repo on nfs...

**Comment by dr4Ke** [comment]
If I understand right, the lock is specified as a couple (hostname, pid). Can't we just check the pid only if this is the local computer. It would solve at least two use cases: local usage, and remote "borg serve" usage. The other ones (access through a remote FS) would leave a lock as (remote_host:remote_pid) and we can also check this pid if the remote_host is the same as the one where is the current user. So the only case where we can't check the pid is if the user is running borg on a remote FS from another machine. Is this correct?

Possible check:
- local use on local FS
- remote use via SSH (`borg serve`)
- local use via remote FS (same hostname as the existing locks)

Impossible check:
- foreign use via remote FS (different hostname than the existing locks)
- local use on local FS with remote lock
- remote use via SSH with foreigh lock (locked through a remote FS)

Possible false positives if two machines have the same hostname (should not happen often).

**Comment by enkore** [comment]
> Possible false positives if two machines have the same hostname (should not happen often).

This happens quite often with not-so-experienced VM admins.

That's why I said above that any such check should be safeguarded and opt-in.

**Comment by verygreen** [comment]
I guess having this feature as opt-in makes sense in some way too.
But in order to have truly unattended backup solution this is one of important prerequisites

**Comment by textshell** [comment]
On modern systems (e.g. debian jessie and newer, much rearlier for fedoras) there is the machine id that is supposed to be unique: https://www.freedesktop.org/software/systemd/man/machine-id.html
I’m sure there are systems that do get this wrong too, but only when cloned from the same image somewhere.

**Comment by PlasmaPower** [comment]
Looks like that's unique to systemd based systems, which I think we'd want to avoid. Might work well with a fallback though.

**Comment by ThomasWaldmann** [comment]
About part b) of #502: i guess this might be solved by the recent locking fixes in 1.0.7rc - as we now immediately get an exclusive write lock, I guess it won't run into that wanting to lock-upgrade over and over problem. Need to try this out before release.

**Comment by ThomasWaldmann** [comment]
Yes, it just tells LockTimeout once now.

**Comment by ThomasWaldmann** [comment]
I am closing this now, everybody who added stuff not relating to top post please move it to some other ticket (if it is not done yet and needs to be preserved).

**Comment by mr-tl** [comment]
I would just like to add that the correct shell variable is `BORG_HOSTNAME_IS_UNIQUE=yes|no` from looking in the current `borg` source.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/general.html?highlight=BORG_HOSTNAME#environment-variables
