### ISSUE TITLE
borg-macosx64.tgz errors with code signature in (Python) not valid for use in process using Library Validation: library load disallowed by system policy

### ISSUE THREAD

**Issue by Mehuge** [borgbackup/borg#5622]
macOS Catalina 10.15.7

Downloaded https://github.com/borgbackup/borg/releases/download/1.1.15/borg-macosx64.tgz and extracted, which creates `borg-dir`. 

The first issue, is a typical and expected one.

In terminal, tried to run borg.exe and get the expected **borg.exe cannot be opened because the developer cannot be verified** message. So, using finder, navigated into borg-dir, found borg.exe and right clicked borg.exe and clicked open while holding CMD to get the alternative dialog **macOs cannot verify the developer of "borg.exe" are you sure you want to open it?** and click the Open button.

Having clicked open, because I use Parallels VM to run a windows machine, parallels tries to open borg.exe in the VM which ofc fails with **This app cannot run on your PC**. Again, not unexpected. So I renamed `borg.exe` to `borg-exe` (for want of a better name) to avoid this.

Running `./borg-exe` from the command line now gives a new dialog **"Python" cannot be opened because the developer cannot be verified**, with the following output in the terminal
```
[9278] Error loading Python lib '/Users/adf/Downloads/borg-dir/Python': dlopen: dlopen(/Users/adf/Downloads/borg-dir/Python, 10): no suitable image found.  Did find:
	/Users/adf/Downloads/borg-dir/Python: code signature in (/Users/adf/Downloads/borg-dir/Python) not valid for use in process using Library Validation: library load disallowed by system policy
```
This was the point I gave up because I had since discovered `brew install borgbackup/tap/borgbackup-fuse`.

However, as I am running through the process again to write the issue, I continued

In Finder, going back into `borg-dir`, right click Python and click open while holding CMD and select open. Get the are you sure dialog and click open. This opens a terminal window which immediately finishes (need to manually close).

Back in terminal window, I again try `./borg-exe -v` and am presented with

![image](https://user-images.githubusercontent.com/99895/103999143-78e1b680-5194-11eb-858d-50f989a0329c.png)

Clicking cancel (my options are move to bin, or cancel) I get two subsequent similar dialogs for other things its trying to load, the output in the terminal is
```
9278] Error loading Python lib '/Users/adf/Downloads/borg-dir/Python': dlopen: dlopen(/Users/adf/Downloads/borg-dir/Python, 10): no suitable image found.  Did find:
	/Users/adf/Downloads/borg-dir/Python: code signature in (/Users/adf/Downloads/borg-dir/Python) not valid for use in process using Library Validation: library load disallowed by system policy
Austins-MacBook-Pro:borg-dir adf$ ./borg.exe -v
[9340] mod is NULL - structTraceback (most recent call last):
  File "/Users/vagrant/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/struct.py", line 13, in <module>
ImportError: dlopen(/Users/adf/Downloads/borg-dir/_struct.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
	/Users/adf/Downloads/borg-dir/_struct.cpython-37m-darwin.so: code signature in (/Users/adf/Downloads/borg-dir/_struct.cpython-37m-darwin.so) not valid for use in process using Library Validation: library load disallowed by system policy
[9340] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "/Users/vagrant/.pyenv/versions/3.7.9/envs/borg-env/lib/python3.7/site-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod02_archive.py", line 30, in <module>
ModuleNotFoundError: No module named 'struct'
[9340] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "/Users/vagrant/.pyenv/versions/3.7.9/envs/borg-env/lib/python3.7/site-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod03_importers.py", line 26, in <module>
ModuleNotFoundError: No module named 'pyimod02_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[9340] Failed to execute script pyiboot01_bootstrap
```

**Comment by Mehuge** [comment]
I just tried something different, get a slightly different result.

I moved borg-macosx64.tgz to /Applications then extracted it there. So I now have `/Applications/borg-dir`.

Right click then CMD+Open to get the security dialog and click Open. Similar issue with parallels trying to run it ofc.

From terminal, running borg doesn't complain about Python this time, but it does still complain about loading the libraries.
```
$ cd /Applications/borg-dir
$ ./borg.exe -v
[9423] mod is NULL - structTraceback (most recent call last):
  File "/Users/vagrant/.pyenv/versions/3.7.9/Python.framework/Versions/3.7/lib/python3.7/struct.py", line 13, in <module>
ImportError: dlopen(/Applications/borg-dir/_struct.cpython-37m-darwin.so, 2): no suitable image found.  Did find:
	/Applications/borg-dir/_struct.cpython-37m-darwin.so: code signature in (/Applications/borg-dir/_struct.cpython-37m-darwin.so) not valid for use in process using Library Validation: library load disallowed by system policy
[9423] mod is NULL - pyimod02_archiveTraceback (most recent call last):
  File "/Users/vagrant/.pyenv/versions/3.7.9/envs/borg-env/lib/python3.7/site-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod02_archive.py", line 30, in <module>
ModuleNotFoundError: No module named 'struct'
[9423] mod is NULL - pyimod03_importersTraceback (most recent call last):
  File "/Users/vagrant/.pyenv/versions/3.7.9/envs/borg-env/lib/python3.7/site-packages/pyinstaller-4.0-py3.7.egg/PyInstaller/loader/pyimod03_importers.py", line 26, in <module>
ModuleNotFoundError: No module named 'pyimod02_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[9423] Failed to execute script pyiboot01_bootstrap
```

**Comment by ThomasWaldmann** [comment]
This needs to be solved/commented by a mac user (== not me).

**Comment by Frzk** [comment]
That's GateKeeper. You're trying to execute some files that are not signed with a "valid" certificate.
As you can see, you can add exceptions, but you would need to do this for all files being loaded.

FWIW, I'm running the compiled binary flawlessly (allow it once, and then allow access to `~/Documents`, `~/Desktop`, ... when it prompts for it)

**Comment by Mehuge** [comment]
Tried using `spctl` to approve these files, and its not playing:

```
# runs, but cant launch borg.exe
sudo spctl --add ~/Downloads/borg-dir 

# can launch borg.exe from command line, but complains about libintl
# It didn't complain about Python, perhaps remembering previous attempts
sudo spctl --add ~/Downloads/borg-dir/borg.exe  

# runs, but still is rejected with libintl.8.dylib cannot be opened because developer cannot be verified
sudo spctl --add ~/Downloads/borg-dir/libintl.8.dylib

# bundle format unrecognised, invalid, or unsuitable
sudo spctl --assess ~/Downloads/borg-dir
```

Disabling Gatekeeper would presumably work, and someone mentioned in another bug that adding terminal as a developer tool, also works.

```
sudo spctl developer-mode enable-terminal
```

Reorganising borg-dir to be a bundle might allow `spctl` to be used to approve it.

I am using `brew install borgbackup/tap/borgbackup-fuse` so its not an issue for me.

**Comment by m3nu** [comment]
I added the dir-style binary to overcome the issues you guys are describing here. It worked without extra steps when I added it at first. We also use the .tgz release to bundle it with Vorta. To run it on the latest Big Sur, I'm aware of those options:

### Option 1: Remove quarantine attribute from files
```
 $ tar xvf borg-macosx64.tgz
...

$ xattr -dr com.apple.quarantine borg-dir/*

$ time ./borg-dir/borg.exe --version
borg.exe 1.2.0b2.dev102+g0ed75ca0
./borg-dir/borg.exe --version  0.34s user 0.07s system 5% cpu 7.192 total

$ time ./borg-dir/borg.exe --version
borg.exe 1.2.0b2.dev102+g0ed75ca0
./borg-dir/borg.exe --version  0.34s user 0.05s system 95% cpu 0.410 total
```

As can be seen this avoids all "Can't verify" errors and macOS will verify all libs when they first run. All subsequent runs are fast, since the files are already known.

### Option 2: Sign all executable files
This requires a Apple Dev account ($99/year) and certificate. It's how we sign Borg for Vorta releases. 

```
find ./borg-dir \
    -type f \( -name \*.so -or -name \*.dylib -or -name borg.exe -or -name Python \) \
    -exec codesign --verbose --force --timestamp --deep --sign "${CERTIFICATE_NAME}" \
    --entitlements ../package/entitlements.plist  --options runtime {} \;
```

### Option 3: Allow exception in Preferences
After a file gets blocked, you can also allow it in *Preferences > Security and Privacy*. Sadly it will ask for each lib individually, so it's not a very practical approach.

<img src="https://user-images.githubusercontent.com/3916435/107139273-f0059880-6954-11eb-83cb-ca8fb50e4b7c.jpg" width=300 />

I guess we should add option 1 to the docs, @ThomasWaldmann ? Option 2 is also possible, but maybe not practical to add it to Vagrant.

**Comment by ThomasWaldmann** [comment]
Option 0 is kind of "step 1", while option 1/2/3 are alternatives for "step 2"?

**Comment by Mehuge** [comment]
Can confirm option 0 works.

**Comment by m3nu** [comment]
> Can confirm option 0 works.

Great. In case people download via Safari, I also put option 1 to remove the attribute in the updated macOS docs. #5677 

> Option 0 is kind of "step 1", while option 1/2/3 are alternatives for "step 2"?

Yeah, something like that:

- Option 1: download with wget/curl and all is good.
- Option 2: download with a browser and decide how to get rid of the quarantine attribute. (xattr, codesign, Prefs)

**Comment by ThomasWaldmann** [comment]
Ah, so I misunderstood. I thought using option 0 still requires one of 1, 2 or 3.

**Comment by ThomasWaldmann** [comment]
Hmm. #5677 does not include the above.

**Comment by ThomasWaldmann** [comment]
so the logical structure should be maybe like that?

- alternative 1: wget
- alternative 2: use browser and one of 2a, 2b or 2c
- 2a xattr removal
- 2b code signing
- 2c exception in prefs

**Comment by m3nu** [comment]
> Hmm. #5677 does not include the above.

I gave all the options here for completeness. I don't think they are needed for the install instructions:

- alternative 1 doesn't cause any issues, so no need to mention it.
- alternative 2: I included 2a because it's the simplest. 2b and 2c aren't practical

**Comment by ThomasWaldmann** [comment]
If 1 is not causing any issues at all and using 1 means not having to do 2a/2b/2c, maybe that should be recommended in the docs.

**Comment by m3nu** [comment]
Can do. How about [this wording](https://github.com/borgbackup/borg/pull/5682/files)?

> To avoid signing issues download the file from the Terminal app or remove the `quarantine` attribute after downloading: `$ xattr -dr com.apple.quarantine borg-macosx64.tgz`

I would still keep the `xattr` note, since users may not expect to get a different file when downloading from a browser.

Or should we recommend using the CLI only? 

> To avoid signing issues download the file from the Terminal app using `curl` or `wget`.

**Comment by ThomasWaldmann** [comment]
Sounds fine. Maybe emphasize the **or**.

**Comment by m3nu** [comment]
Updated.

![Screen Shot 2021-02-11 at 13 46 29](https://user-images.githubusercontent.com/3916435/107605993-b0e68880-6c6f-11eb-8ecf-c184960a0317.jpg)

Slightly reworded to "download via command line" to include all kinds of terminals.

**Comment by ThomasWaldmann** [comment]
ok, documented now, closing.
