### ISSUE TITLE
Sample batch file contains error (compact command not found)

### ISSUE THREAD

**Issue by fourofspades** [borgbackup/borg#5624]
The sample script on the borg homepage contains errors about compact command not being found.

Confidence in backup solutions are easily dented by errors in documentation like this.  Does the code contain similar errors?

**Comment by ThomasWaldmann** [comment]
you're likely looking at docs that do not match the borg version you use.

see the version selector at the bottom right.

**Comment by ThomasWaldmann** [comment]
no response, but i am pretty sure my comment solves this issue.
