### ISSUE TITLE
borg create seems to read all already backuped files

### ISSUE THREAD

**Issue by PhieF** [borgbackup/borg#5626]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.11

#### Operating system (distribution) and version.

Ubuntu 20.04

#### Hardware / network configuration, and filesystems used.

see below

#### How much data is handled by borg?

103gB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create -v -p --files-cache=mtime,size --stats dest::"${DATE}" from-path --compression=lz4

or

borg create -v -p --files-cache=ctime,size --stats dest::"${DATE}" from-path --compression=lz4

## Describe the problem you're observing.

I have a question about this part 
--files-cache=mtime,size

I'm trying to use borg as my main backup system, 
to backup server A to server B

when backup A to B it seems to need to read a lot of data from A to detect file change
I'd like borg to only rely on modification time and size, or even ctime

In fact is this particular case, A is using s3ql as file system. Which means that reading data from A is slow and costs money (S3 like has a cost per gB downloaded). S3QL caches files metadata which why with rsync I don't have this issue. Rsync only uses modification time and size to detect changes

so with rsync:

First sync, slow and cost because reading everything (which is normal)
second sync : really fast since needed metadata are kept by s3ql

with borgbackup:
First sync, slow and cost because reading everything (which is normal)
second sync: also slow since it seems to read files again, at least part on them, so it cost money as I pay for each gB read on server A

Any ideas to get it working this way ? Am I doing something wrong ?

And really, thanks for this wonderful project and you work, borg is a great software

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#what-s-the-expected-backup-performance read some sections starting from there.

**Comment by ThomasWaldmann** [comment]
```
borg create -v -p --files-cache=ctime,size --stats dest::"${DATE}" from-path --compression=lz4
```

- `lz4` compression is the default
- `ctime,inode,size` is the default for the files cache and you should only change that if you notice that your filesystem does not correctly support that. network fs often do not support stable inode numbers. using `mtime` instead of `ctime` is less safe because mtime can be modified from userspace tools (e.g. keeping mtime same although file was modified).
- `"${DATE}"` - borg can do that itself using the `{now}` placeholder (with optional custom timestamp format)

**Comment by PhieF** [comment]
Thanks

So, I guess I have at least one issue I didn't see

```
Another possible reason is that files don’t always have the same path, for example if you mount a filesystem without stable mount points for each backup or if you are running the backup from a filesystem snapshot whose name is not stable. If the directory where you mount a filesystem is different every time, Borg assumes they are different files. This is true even if you backup these files with relative pathnames - borg uses full pathnames in files cache regardless.

```

I'm using a different backup mount point each time, so, this might explain why I have this issue

but


```
it first looks whether the file has changed (compared to the values stored in the files cache).
```
What does it use to detect that change, because if it needs to read the file, compare it to the cache, then my issue remains since I don't want it to be read from the source file system again

Thanks for your help !

**Comment by PhieF** [comment]
For testing:

--files-cache=disabled

will take the exact same time, as if it wasn't using any cache

**Comment by ThomasWaldmann** [comment]
The speedup for unmodified files is based on metadata, it does not even read the file contents if it knows the file is not modified.

So, if it finds the file in the files cache and ctime,inode,size match, it just grabs the chunk ids from the files cache entry and creates a new archive item with these - it will only read some metadata from the fs in this case (like user/group/mode, xattrs, acls, bsdflags).

**Comment by ThomasWaldmann** [comment]
But if detects the file to be new or modified, it will read and chunk the whole file (which is relatively slower).

**Comment by ThomasWaldmann** [comment]
From the FAQ: You can use the `stat` command on files to manually look at fs metadata to debug if there is any unexpected change triggering the M status.

E.g.:

```
user@development:~/w/borg$ stat setup.py
  File: setup.py
  Size: 36972     	Blocks: 80         IO Block: 4096   regular file
Device: ca10h/51728d	Inode: 1180915     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    user)   Gid: ( 1000/    user)
Access: 2021-01-10 14:15:15.557000000 +0100
Modify: 2021-01-10 14:15:02.969000000 +0100
Change: 2021-01-10 14:15:02.969000000 +0100
 Birth: -
```

So, you have size, inode, ctime (change time) all there, you just need to find out what changes unexpectedly between your backups (between mounts?). I suspect it is the inode number, but better check yourself.

**Comment by ThomasWaldmann** [comment]
And you rather should use `--list` than `--progress`, so you get the status chars at the beginning of the output lines.

`A` (added) and `M` (modified) is slow (reading/chunking), `U` (unchanged) is fast.

**Comment by ThomasWaldmann** [comment]
Also keep in mind that each time you switch caching mode, it will need one run to build that cache and the cache will then be useful only in the next run **after** that.

**Comment by PhieF** [comment]
OK then 

Each time I'm  running it when trying to save a directory called   testql-no I get

```
d testql-no/lost+foundtestql-no                                                                                                                                                                            
A testql-no/6b43a28c-86ee-4681-8ab9-787ac140afc0-1080.mp41-8ab9-787ac140afc0-1080.mp4                                                                                                                      
d testql-no
```
each time I run the exact same command


and the stat is

```
root@ovh3:/mnt# stat testql-no/6b43a28c-86ee-4681-8ab9-787ac140afc0-1080.mp4 
  Fichier : testql-no/6b43a28c-86ee-4681-8ab9-787ac140afc0-1080.mp4
   Taille : 1168159554  Blocs : 2281576    Blocs d'E/S : 4096   fichier
Périphérique : 901h/2305d       Inœud : 2752517     Liens : 1
Accès : (0644/-rw-r--r--)  UID : (    0/    root)   GID : (    0/    root)
Accès : 2021-01-11 14:27:53.742055386 +0000
Modif. : 2021-01-11 14:27:54.774040257 +0000
Changt : 2021-01-11 14:27:54.774040257 +0000
  Créé : -
```

**Comment by PhieF** [comment]
So to sum up

My first issue was the changing mounting point (I don't know why I didn't see it in the doc at first...)

my second was that I was testing with only one file.

So, thanks very much for both your help and your great software, I will close this issue !
