### ISSUE TITLE
Original Size is bigger than expected and backup doesn't end

### ISSUE THREAD

**Issue by auanasgheps** [borgbackup/borg#5627]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue.

#### Your borg version (borg -V)
borg 1.1.13

#### Operating system (distribution) and version.
Synology DSM 6.2.3
#### Hardware / network configuration, and filesystems used.
Synology DS215j. The source backup is NTFS, destination is EXT4.

#### How much data is handled by borg?
3.67 TiB = 4.03 TB
I am aware Borg shows **TB** whilst most OSes actyually show **TiB**

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
Please note I am using borgmatic. The command I see in logs is:

borg create --exclude-from /tmp/tmp_j7essc5 --compression zstd --remote-path /usr/local/bin/borg --info USERNAME@MYSERVER:backup::{hostname}-{now:%Y-%m-%dT%H:%M:%S} /srv/dev-disk-by-uuid-0204C10404C0FC23/nvme-dati /srv/dev-disk-by-uuid-0204C10404C0FC23/raidunion

## Describe the problem you're observing.
I am backing up all of my data on a Synology DS215j, a very slow NAS, running borg 1.1.13, from an external USB drive to the internal NAS drive.
The backup is taking forever but it is expected because this NAS is slow as a rock. I've been running the backup 12hrs per day and writing down the numbers at the end of each day.

On the 9th of January the total size was already above what I expected. Something weird happened on the 10th, then the numbers went up again.

**09/01/21**
Original Size | Compressed Size | Deduplicated Size
------------ | ------------- | ------------- |
4.28 TB | 4.09 TB | 1.87 TB

**10/01/21**
Original Size | Compressed Size | Deduplicated Size
------------ | ------------- | ------------- |
2.27 TB | 2.18 TB | 1.98 TB

Yes, I've doublechecked these numbers.

**11/01/21**
Earlier today

Original Size | Compressed Size | Deduplicated Size
------------ | ------------- | ------------- |
4.63 TB | 4.44 TB | 2.05 TB

I've temporary moved the configuration to a VM on my PC, running the same backup (but obviously remote) hoping for a speed improvement. The borg version here is 1.1.15.

```
root@omv-test:~# borgmatic --info
USERNAME@MYSERVER:backup: Displaying summary info for archives
Repository ID: 83460e483b76ea768e95dbc[redacted]
Location: ssh://USERNAME@MYSERVER/./backup
Encrypted: Yes (repokey)
Cache: /root/.cache/borg/83460e483b76ea768e95dbc64[redacted]
Security dir: /root/.config/borg/security/83460e483b76ea[redacted]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:                4.79 TB              4.59 TB              2.05 TB
                       Unique chunks         Total chunks
Chunk index:                 1541426              4583880
```

Aside from the original and compressed size fall which is pretty _funny_, why my backup is still running?

I've never used deduplication but I'm not sure if is **that** efficient: I have at least 3 TB of video files. Can they really be deduplicated?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
This is my only backup.

#### Include any warning/errors/backtraces from the system logs
I've configured borgmatic to write logs, and all I can see is that the backup is being started every single time and never ends.

[2021-01-11 22:56:36,709] INFO: USERNAME@MYSERVER:backup: Pruning archives
[2021-01-11 22:56:43,142] INFO: USERNAME@MYSERVER:backup: Creating archive
[2021-01-11 22:56:47,955] INFO: Creating archive at "sUSERNAME@MYSERVER:backup:backup::{hostname}-{now:%Y-%m-%dT%H:%M:%S}"

EDIT: Kept it running on the VM which is way more faster, for about two hous. Original size has increased a lot, unique Chunks and Deduplicated Size has barely changed. What the heck is going on here?
```
srv.milano@192.168.178.25:backup: Displaying summary info for archives
Repository ID: 83460e483b76ea768e95dbc[redacted]
Location: ssh://USERNAME@MYSERVER/./backup
Encrypted: Yes (repokey)
Cache: /root/.cache/borg/83460e483b76ea768e95dbc64[redacted]
Security dir: /root/.config/borg/security/83460e483b76ea768e95dbc64[redacted]
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:                5.41 TB              5.15 TB              2.05 TB
                       Unique chunks         Total chunks
Chunk index:                 1542322              5402829
```

**Comment by ThomasWaldmann** [comment]
If you have interrrupted one of these backups, there might be a checkpoint archive in the repo that references the data that was transferred until then.

If you start another backup with that checkpoint being present, it will dedup against that, leading to a relatively low deduped size in the current backup run, because it already has some of the data in the checkpoint archive.

**Comment by auanasgheps** [comment]
> If you have interrupted one of these backups, there might be a checkpoint archive in the repo that references the data that was transferred until then.

Yes I do interrupt backups each day because I don't want the backup drive to be spinning all the time, but at that point backups have been going for hours.  

This morning I restarted the backup on the VM and there's no mention of the checkpoint:

```
[2021-01-12 09:27:50,258] INFO: /etc/borgmatic/config.yaml: Pinging Healthchecks start
[2021-01-12 09:27:50,461] INFO: USERNAME@MYSERVER:backup: Pruning archives
[2021-01-12 09:28:14,413] INFO: USERNAME@MYSERVER:backup: Creating archive
[2021-01-12 09:28:20,942] INFO: Creating archive at "USERNAME@MYSERVER:backup::{hostname}-{now:%Y-%m-%dT%H:%M:%S}"
```

**Comment by ThomasWaldmann** [comment]
borg never "mentions" any present / previous backup archives.

please note that borg also never "resumes" a backup run. it always does a fresh, full backup.

in some cases, it just happens that some of the content data chunks are already in the repository, which is normal deduplication behaviour.

**Comment by auanasgheps** [comment]
> please note that borg also never "resumes" a backup run. it always does a fresh, full backup.

Thanks for clarifying, I wasn't aware of this. This would explain original size being higher than expected.

So what is the role of the checkpoint archive? To avoid copying data already in the repository from the previous partial backup?

**Comment by ThomasWaldmann** [comment]
A checkpoint is a valid, finished transaction. So everything up to that is in a good, known state, the backup is just not complete.

All after the checkpoint are uncomitted segment files and they will be rolled back next time you write to the repo to get the repo into a valid, consistent state.

The checkpoint archive is valid archive, it is just not complete. It holds all the references to the content data up to the checkpoint.

One does not need to deal with the checkpoint archive, but could in case of emergency. One usually just starts a fresh backup and that will finish quicker, because some of the data is already in the repo. Later, prune will get rid of checkpoint archives.

**Comment by auanasgheps** [comment]
Thank you. The behaviour is now clear to me and numbers make more sense.
