### ISSUE TITLE
why does borg read/chunk the same file(s) again and again? (FAQ)

### ISSUE THREAD

**Issue by manfredlotz** [borgbackup/borg#5628]
My system is a Fedora 33 Linux, borg is 1.1.15. 

I did a simple test to backup a directory containing a single file

- from my laptop where the directory is in a btrfs subvolume
- to an external USB hard disk where the borg repository is also residing in a btrfs subvolume

The test is like this:

```
  export BORG_REPO=/run/media/manfred/BACKUP2/borg.test
  rm -rf $BORG_REPO
  borg init -e none
  
  borg create --files-cache="ctime,size"  --stats ::test1 /data/images/test

 # now immediately a new backup done without any change to the source.
  borg create --files-cache="ctime,size"  --stats ::test2 /data/images/test
```
When `/data/images/test` contains

```
-rw-r--r--. 2 manfred manfred 3097952256 May 27  2020 d1.iso
file d1.iso 
d1.iso: UDF filesystem data (version 1.5) 'SOMETRAINING_FINAL4'
```

then the second run of borg shows

```
Time (start): Tue, 2021-01-12 10:28:53
Time (end):   Tue, 2021-01-12 10:28:53
Duration: 0.01 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                3.10 GB              3.06 GB                547 B
All archives:              122.00 GB            118.91 GB             21.37 GB

                       Unique chunks         Total chunks
Chunk index:                    8533                47204
------------------------------------------------------------------------------
```
This is fine, of course.

If I have a different iso image in that directory, for example

```
file d3.iso 
d3.iso: UDF filesystem data (version 1.5) 'DVD_PAL'
```
then the second run of borg shows this:

```
Time (start): Tue, 2021-01-12 09:07:18
Time (end):   Tue, 2021-01-12 09:07:21
Duration: 3.82 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                3.95 GB              3.90 GB                570 B
All archives:              118.90 GB            116.51 GB             21.48 GB

                       Unique chunks         Total chunks
Chunk index:                    8532                46012
------------------------------------------------------------------------------
```

Why does it take 3.82 seconds to find out that there is nothing to backup?

**Comment by ThomasWaldmann** [comment]
3 seconds could be due to a lot of reasons. please reproduce the issue showing a much bigger difference.

**Comment by ThomasWaldmann** [comment]
Also, please use `--list` to get more information about what borg is doing and read the FAQ about some special cases.

**Comment by manfredlotz** [comment]
I made an even simpler test and the file gets added each time I run borg
```
borg init -e none repos
```
First backup 

```
 borg create --list  --stats repos::zipfile source
A source/x.zip
d source
------------------------------------------------------------------------------
Archive name: zipfile
Archive fingerprint: c73435f7a12966a84d0bc7a61fa98a64219dc484abd4b917a40e02aa2cb1024e
Time (start): Wed, 2021-01-13 06:27:16
Time (end):   Wed, 2021-01-13 06:27:17
Duration: 1.33 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              214.42 MB            215.26 MB            215.26 MB
All archives:              214.42 MB            215.26 MB            215.26 MB

                       Unique chunks         Total chunks
Chunk index:                      98                   98
------------------------------------------------------------------------------
```

Subsequent backups have an A all of the time.

```
borg create --list  --stats repos::zipfile1 source
A source/x.zip
d source
------------------------------------------------------------------------------
Archive name: zipfile1
Archive fingerprint: 441979fa078329b5adca4026068f7342e8009bca6dbb4bf8fdd862daec84b924
Time (start): Wed, 2021-01-13 06:27:25
Time (end):   Wed, 2021-01-13 06:27:26
Duration: 1.06 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              214.42 MB            215.26 MB                429 B
All archives:              428.85 MB            430.51 MB            215.26 MB

                       Unique chunks         Total chunks
Chunk index:                      99                  196
------------------------------------------------------------------------------
```

**Comment by manfredlotz** [comment]
As said previously, this is happening on a btrfs subvolume. Now transferred my test to a different system where I have an ext4 filesystem. There things are working ok, i.e. I get

```
U source/x.zip
d source
```
Does it mean that borg doesn't support btrfs file systems properly?

**Comment by manfredlotz** [comment]
Additional remark. When I run borg like this
```
 borg create --list --files-cache='ctime,size' --verbose --progress --stats repos::z7 source
```
I get

```
Creating archive at "repos::z7"
A source/x.zip3.32 MB C 0 B D 0 N source/x.zip                                                                            
d source
```

**Comment by manfredlotz** [comment]
I am still investigating and being unable to find the cause of all of this.

Another test on a 3rd system where I backup `/home` (which is btrfs) to an external HD which is also btrfs.
Here the second backup has `U` for 99.x % of all files and takes 23.88 seconds for 21836 files. Perfect.

Both systems with btrfs are Fedora 33 and same software level. I am lost having no idea why on one system things work fine and on the other system there is no `U` when doing another backup.

**Comment by manfredlotz** [comment]
I am aware that it looks as if I am a bit crazy but anyway here the next observations.

The system were things are fine despite using btrfs runs SELinux in enforcing mode. The system where things are slow because each time I do a new backup all files get added again runs in permissive mode (for some reasons I cannot switch to enforcing at this point in time).

Nevertheless, I changed to enforcing and changed back to permissive and for whatever reason borg now works fine. Unchanged files do not get added again.

So, this is pretty confusing to me.

**Comment by ThomasWaldmann** [comment]
- **please read the FAQ in the docs, all of it**
- do not mix --list and --progress
- test with more than 1 file and with a volume that reproduces a clearly visible issue

**Comment by manfredlotz** [comment]
I have read the FAQ, which doesn't mean I have understood it all. 

For example, I don't understand how unchanged files can be added again when I do a new backup minutes after having done the last one. File stats haven't changed.

My last test was with a partition having around a million files where it worked fine after having switched SELinux to enforcing and back to permissive. Which is at least confusing for me. Perhaps it was accidentally, don't know.

**Comment by manfredlotz** [comment]
There is some stuff in the FAQ regarding `A` aso. I don't understand. Which is the right place to discuss this?

**Comment by ThomasWaldmann** [comment]
You can discuss it here, just point to the docs and specifically ask what you do not understand, so we can clarify the docs maybe.

**Comment by manfredlotz** [comment]
Thank you. 

My understanding is that a file already backed up is skipped from a future backup when that file has not changed in any way. In this case I would define not changed that the output of `stat somefile` is the same as before in terms of ctime. mtime, size and inode. Ok, `--files-cache` could be used to specify what will be compared.

So, let's start with my questions.

In `I am seeing ‘A’ (added) status for an unchanged file!?` it is said 

```
The files cache is used to determine whether Borg already “knows” / has backed up a file and if so, to skip the file from chunking. It does intentionally not contain files that have a timestamp same as the newest timestamp in the created archive.
```

I understand this paragraph in a way that my understanding is correct. 

The next sentence: 

`So, if you see an ‘A’ status for unchanged file(s), they are likely the files with the most recent timestamp in that archive.`

I don't simply understand. If the timestamp of a file to backup, most recent or not, is the same in the cache resp. backup then it is skipped according to the first paragraph above. ???

**Comment by jdchristensen** [comment]
The key part is the sentence:
```
It does intentionally not contain files that have a timestamp same as the newest timestamp in the created archive.
```
(This is grammatically incorrect and should be rephrased to "It intentionally does not contain ..." or, better, "It intentionally excludes files that have a timestamp that matches the newest timestamp in the created archive".)

The point is that files whose timestamp is exactly the same as the last file backed up are not recorded in the cache, so such files appear as new files the next time the backup is run.  This is just in case they changed during that same instant recorded in the timestamp.

This issue confuses a lot of people.  Is there a way borg could avoid doing this, and still be safe?

**Comment by manfredlotz** [comment]
Thanks for this. I never had understood it this way. But I have to admit I have read your reply more than one time.

Let's see if I understood correctly: Let us assume I have exactly one file `f1` in my `source/` directory which never changes but nevertheless I do backup `source/` multiple times.

1st backup shows:  `A source/f1` and `f1`s metadata is in the cache

2nd backup shows: `U source/f1` and now `f1`s metadata is deleted in cache

3rd backup shows: `A source/f1` and `f1`s metadata is again in the cache

4rd backup like 2nd backup. 

This is how I understood your explanation but it does not match my observation when using borg.

**Comment by jdchristensen** [comment]
No, files whose timestamp matches the latest timestamp will always be marked `A` in the next backup.  As the FAQ says.

**Comment by manfredlotz** [comment]
Then I am lost. It seems to mean that a file which never changes will always be marked `A` and thus chunkend every time. So `U` should never happen. More confused than before.

**Comment by jdchristensen** [comment]
When you do a backup of multiple files, typically they will all have different ctimes.  Only the one with the most recent ctime will be chunked again in the next backup.  Try making a directory and touching two files in it.  In the first backup, both will be marked with `A`.  If nothing changes, then for each subsequent backup, just the newer file gets marked `A`.  When you are backing up thousands of files, it's not such a big deal if one of them gets rechunked.  And if you want to avoid it, you can always touch an empty file in the backup set right before starting the backup, so only that empty file will get rechunked.

**Comment by manfredlotz** [comment]
Thank you so much. This explanation helped a lot and matches my observation I made earlier with two files in a directory. And it helped me to get a starting point in understanding `It always chunks all my files, even unchanged ones!`. 

Assume I don't have two files in my source/ directory tree but 1 million. It is the same behavior? In other words only the newest file gets rechunked? Which reminds me that I didn't understand ` BORG_FILES_CACHE_TTL` really. Perhaps it has an impact, not sure.

**Comment by ThomasWaldmann** [comment]
@manfredlotz ok, now that you understood it, can you specifically point at the wording in the docs that made you not understand it initially? I'ld like to improve that, if possible.

**Comment by ThomasWaldmann** [comment]
@manfredlotz The number of files do not matter. But if the newest file has a timestamp T, all files with that timestamp T (be it 1 or a million) will be dropped from files cache.

Practically, it is usually one or a few, but there can be special cases with a lot of such files. 

You can influence this by just creating that "newest" file yourself, e.g. a empty file.

**Comment by manfredlotz** [comment]
At this point in time I don't understand enough yet to make suggestions to improve the FAQ. 

Yesterday, I changed my script to create an empty `.borg` file in the top level directory of the subvolume which gets backuped. I tried it with a single subvolume and things worked fine.

There is `BORG_FILES_CACHE_TTL` mentioned in `It always chunks all my files, even unchanged ones!`.  It seems it does also influence re-chunking. In the meantime I got an idea what `data set` could mean. My interpretation is that a `data set` denotes an archive which was created by running a `borg create`. 

Then it is said that the default for `BORG_FILES_CACHE_TTL` is 10. Does this mean that after having run 10 backups a re-chunk take place no matter if files had changed in the meantime or not? If yes does this happen only when the next set of backup happens the next day?

**Comment by ThomasWaldmann** [comment]
Well, if `data set` would mean `archive`, it would say `archive`. :-)

`data set` refers to all input / source files you give to borg create. They will end up being archived in the archive that results from that run, but the archive is the destination and the (input) data set is the source.

No, it does not mean that after 10 backups it will rechunk everything. It only means that if you have more than 10 **different** data sets, then you will need to increase that value (or run into a rechunking issue).

**Comment by manfredlotz** [comment]
Aaa, ok. So, two data sets are different if their source is not equal.

Data set 1 with source:   `/data` and `/tmp`
Data set 2 with source: `/data`
Data set 3 with source: `/tmp`

All data sets are different. Correct?

**Comment by ThomasWaldmann** [comment]
Well, they are partly different, partly overlapping. So it might only rechunk a part of your files.

But usually one has data sets with no overlap and that case is easier to discuss.

**Comment by manfredlotz** [comment]
The case with more than a single source directory in a `borg create...` is interesting. 

I did a test with a scheme similar like above:
Source 1: `/s1`
Source 2: `/s2`
Source 3: `/s3`
Source 4: `/s2` and `/s3`

`export BORG_FILES_CACHE_TTL=4`

There was no re-chunking which indicates that `borg` just differentiates between different source directories. Which mean that in above case for `borg` there are exactly 3 different sources.

**Comment by jdchristensen** [comment]
You are misunderstanding `BORG_FILES_CACHE_TTL`.  Borg doesn't keep track of how many sources you have.  It simply removes a file from the files cache if it hasn't seen it in X backups, where X is the value of the `BORG_FILES_CACHE_TTL` variable.  So if you have two source trees `/s1` and `/s2` and you backup `/s2` four times (with that variable set to 4), then when you next backup `/s1`, the files will be re-chunked.  So you have to make the `TTL` value large enough that that doesn't happen with your backup pattern.

The FAQ explains this pretty clearly I think:

> Every time you do a backup (on the same machine, using the same user), the cache entries’ ttl values of files that were not “seen” are incremented by 1 and if they reach BORG_FILES_CACHE_TTL, the entry is removed from the cache.

I'm pretty sure that when a file *is* seen, the ttl value is set to 0 (or maybe 1).  If this is correct, the FAQ should mention it as well.

**Comment by manfredlotz** [comment]
Thanks for your explanation. I guess I have now (at least better as before) understood this part.
