### ISSUE TITLE
[doc] typo / inaccuracy on 'borg benchmark' usage page

### ISSUE THREAD

**Issue by fenugrec** [borgbackup/borg#5630]
[EDIT - originally I misunderstood the docs. They are correct but could benefit from maybe adding an example command ? ]

When using wrong arguments or with permission issues, `borg benchmark crud` can exit without deleting the `borg-test-data/` it created, leading to some head scratching. It would be a nice addition to cleanup that folder systematically on exit (clean or error), unless there's some use case for the current bheavior ?

**Comment by ThomasWaldmann** [comment]
Maybe we can use some `try / finally` or so in the code to make sure the cleanup happens.

**Comment by brunobehnken** [comment]
@ThomasWaldmann can I be assigned to this issue?

**Comment by ThomasWaldmann** [comment]
@brunobehnken sure! :-)
