### ISSUE TITLE
Client talking to a newer version of borg on the server, is it ok?

### ISSUE THREAD

**Issue by daloic** [borgbackup/borg#5631]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

- new server: borg-linux64 1.1.15
- client: borg 1.0.10

#### Operating system (distribution) and version.

- new server: Ubuntu 20.04
- client: Ubuntu 14.04.5 LTS

## The question

The current backup server we have needs an upgrade. The new server is configured with borg 1.1.15.
As we have old clients which are stable, able to nicely backup against the current backup server with borg 1.0.10, I wonder if it is possible to keep them using borg 1.0.10 but just changing the target backup server with the target backup server running borg 1.1.15?

I understand that the files on disk are compatible, but I am not sure if the communication between two borg versions, here 1.1.15 on the server and 1.0.10 on the client are possible. 

And yes, it means that for the past 6 years, we have had clients creating a daily backup with borg, nicely, no corruptions, just a nice backup and peace of mind. Big thank you!

**Comment by ThomasWaldmann** [comment]
IIRC, it should work.

OTOH, you could maybe also use the borg binary from github releases, to get a more recent borg onto these systems.

1.0.10 is rather old, not even the last 1.0.x version (and 1.0.x in general is out of support).

**Comment by daloic** [comment]
Thank you Thomas for this very fast answer. I will test if a new version can run on these old Ubuntu clients (the libc may be an issue) and if not I will try to find the newest working version and use it against the new server. I will report my tests here within the next 7 days.

**Comment by daloic** [comment]
As the old clients have glibc 2.19, I was able to upgrade borg both on the server and the clients. The test backups went smoothly. I am now running `borg check --repository-only` on the repositories on the server. 

Thank you for your help and again, thank you for this very nice borg. The kind of software I like, robust, doing its job days after days without the need to babysit it all the time (repository checks, test restore sometimes, df, that's it).

I am closing the issue because I don't foresee more issues.
