### ISSUE TITLE
borg on cygwin test failures

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5640]
borg 1.1.15:

I can't c&p from my windows VM, thus just brief:

- `test_create_stdin` fails due to a uid lookup issue: the user2uid(user) lookup returns None, leading to a failure. user == group == None. this is caused by the default of `stdin_user=uid2user(0)`. On Posix systems, this is usually `root` and `root` maps back to uid 0. But not on cygwin...

- `test_recreate_basic` falls over a `PermissionError` in `create_regular_file('dir2/file3')`. this is because `create_test_files` takes away write permissions on dir2. it does not do that on linux, except when running as root (because mknod fails on linux, but not on cygwin). so, when using cygwin as normal user, it runs into that issue that it can not create a new file in dir2 due to dir permissions.

- `test_atime` fails: looks like borg extract does not set the atime of the extracted file. in borg 1.1.x, we archive/extract atime by default. in master branch / borg 1.2, we do **not** archive atime by default. unclear where the problem in 1.1.15 is...

**Comment by ThomasWaldmann** [comment]
The first 2 are diagnosed and should be easy to fix.

The test_atime is a bit tougher: I could not find out yet, what's going wrong.

Stuff I tried:
- disable virus scanner (in case it touches atime directly after borg extract)
- do not do other stuff (acls, xattrs) after setting atime
- set attrs based on path of closed file, not on open file handle
- disable birthtime-setting code path (seems we **do have** birthtime in archived item on cygwin!)

**Comment by DeeNewcum** [comment]
I'm interested in tackling the first two issues. One question though -- it looks like fakeroot is required to run the tests, but some quick Googling didn't reveal how to install fakeroot on cygwin. Any advice?

**Comment by ThomasWaldmann** [comment]
A lot of tests also work without fakeroot:
- either as a normal user (because they do not require root)
- or by running as normal root (if possible, e.g. on some CI hosts that create one-time usage VMs)

Guess this is only relevant for the 2nd issue. And the 2nd one is due to some strange arrangement, maybe it can be solved in other ways?

**Comment by DeeNewcum** [comment]
Someone else can work on this bug; my Cygwin installation is misbehaving.

**Comment by ThomasWaldmann** [comment]
See #7218.
