### ISSUE TITLE
"Building the docs with sphinx" instructions does not work for vagrant environments

### ISSUE THREAD

**Issue by rpolley** [borgbackup/borg#5641]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).
development version

#### Operating system (distribution) and version.
ubuntu/bionic64

#### Hardware / network configuration, and filesystems used.
vagrant/virtualbox

## Describe the problem you're observing.
The instructions for setting up the development environment to be able to build documentation are incomplete. Currently it tells you:
```
The documentation (in reStructuredText format, .rst) is in docs/.

To build the html version of it, you need to have Sphinx installed (in your Borg virtualenv with Python 3):

pip install -r requirements.d/docs.txt

Now run:

cd docs/
make html
```
However, the `make html` step fails because it can't run sphinx-build.
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

- Spin up a fresh bionic64 dev box using vagrant
- On the vagrant box follow the steps for building documentation

**Comment by ThomasWaldmann** [comment]
I just tried to reproduce in a qubes debian10-dvm and it works for me.
- first get the normal borg dev environment working (also described in the docs)
- then pip install -r requirements.d/docs.txt
- cd docs ; make html
- works

**Comment by ThomasWaldmann** [comment]
```
(borg-env) user@disp2549:~/borg/docs$ which sphinx-build 
/home/user/borg-env/bin/sphinx-build
```
So, `sphinx-build` was obviously installed to the venv.

**Comment by rpolley** [comment]
Can you point me towards the instructions for setting up the virtual environment? I can't seem to find it anywhere in the documentation.

**Comment by rpolley** [comment]
Never mind it was in the installation section

**Comment by rpolley** [comment]
Followed the installation instructions and it worked. Closing.
