### ISSUE TITLE
Troubleshooting CIFS Source "Modified" Files

### ISSUE THREAD

**Issue by DrBrynzo** [borgbackup/borg#5646]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. I've also followed suggested actions from the FAQ and other similar issues. 

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION (Minor ISSUE, maybe more of an annoyance admittedly)

#### Your borg version (borg -V).
borg 1.1.9
#### Operating system (distribution) and version.
Debian 10.7
#### Hardware / network configuration, and filesystems used.
KVM based VM
Source: CIFS-mounted share from Synology NAS (BTRFS)
Destination: SSH target on Linux BTRFS
#### How much data is handled by borg?
~780 GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
create --verbose --filter AME --list --stats --show-rc --compression auto,lzma  /data/<various paths - several jobs>

## Describe the problem you're observing.
On every backup run, all the files are showing as "M" modified and the backup takes a very long time processing all the files.

Even having read the FAQ and knowing about network/non-standard filesystems, I'm trying to figure out where else I can troubleshoot this as this behavior did not used to happen and the configuration has been unchanged for well over a year.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, can reproduce, simply by running the backup again even moments later (typically runs once per day).

I've run "stat" on various samples of files between days, even rebooting the source server (Synology NAS) and the client (system running borg). The output of stat is the same:

Jan 21
  File: /data/media/bryn/video/DPB10/2018-02/2018_0202_164823_001.MOV
  Size: 123949883 	Blocks: 242096     IO Block: 16384  regular file
Device: 2fh/47d	Inode: 1179593     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1028/    bryn)   Gid: (  100/   users)
Access: 2019-12-20 04:57:26.975849300 -0800
Modify: 2018-02-02 16:49:38.000000000 -0800
Change: 2018-02-02 16:49:38.000000000 -0800
 Birth: -

Jan 22 (post reboot, next day)
  File: /data/media/bryn/video/DPB10/2018-02/2018_0202_164823_001.MOV
  Size: 123949883 	Blocks: 242096     IO Block: 16384  regular file
Device: 2fh/47d	Inode: 1179593     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1028/    bryn)   Gid: (  100/   users)
Access: 2019-12-20 04:57:26.975849300 -0800
Modify: 2018-02-02 16:49:38.000000000 -0800
Change: 2018-02-02 16:49:38.000000000 -0800
 Birth: -

I've tried MD5 checksums, binary file comparisons (using Beyond Compare) and diff. The files are unchanged.

I ran an rsync against a subset of the files between both dates and rsync detected no changes. This last piece if information is interesting to me because it means borg is "seeing" something that rsync is not, maybe?

I also have another backup of the same data using Duplicacy and Duplicacy did not detect any changes as well.

Synology Hyper Backup also shows no changes to the file set, though it is only dealing with the local BTRFS filesystem, not over the CIFS share so it's just an verification of the state of the files being unchanged.

I'm really just looking for some guidance on why borg would be the "odd man out" here. This set of files is almost never modified other than having new data added to it occasionally. Just a couple of months ago borg backups were quick and detected no changes so something changed and I've been unable to figure out what that would be. Just looking for help trying to narrow it down.

**Comment by ThomasWaldmann** [comment]
As you've already checked timestamps and inode number, the files cache TTL not being high enough for your amount of different backup jobs would be the easiest explanation (see FAQ).

**Comment by DrBrynzo** [comment]
I read the section on TTLs previously, but had the impression that the TTL is only important if the file is not "seen" (27 times in the example). Almost no files are ever being deleted from the source and should be present in perpetuity. While a small portion of the jobs in question cover documents that change, the pathnames don't and should be "seen" consistently.

Example from FAQ: "Every time you do a backup (on the same machine, using the same user), the cache entries’ ttl values of files that were not “seen” are incremented by 1 and if they reach BORG_FILES_CACHE_TTL, the entry is removed from the cache."

To me, that read the file would somehow need to not be present (seen) to affect or be affected by the TTL.

**Comment by DrBrynzo** [comment]
I also want to clarify what you mean by "jobs" (and "sets" in the docs) so I'm not making incorrect assumptions.

"So, for example, if you do daily backups of 26 different data sets A, B, C, …, Z on one machine (using the default TTL), the files from A will be already forgotten when you repeat the same backups on the next day and it will be slow because it would chunk all the files each time."

Is it assumed above that the different sets are from a single client to a single borg repository?

Example: If I back up /my/photos in one scripts to BORG_REPO=/backups/photos and /my/music to BORG_REPO=/backups/music are those separate with their own TTLs as they have their own config and cache directories? 

How does TTL come into play in that scenario versus, say, if I backup both /my/photos and /my/music to /backups/allmystuff? (Multiple data sets, single repo.)

I had made an assumption that if it has a completely different repo and also key in the repo "config" file (and cache/config directory) that there is no relation or shared state between those backups - they are completely "siloed" from each other. I just want to make sure I didn't make a bad assumption about that.

**Comment by ThomasWaldmann** [comment]
Being seen requires being looked at. If a file is not looked at in a backup run because it is not in the input data set, it is "not seen".

**Comment by DrBrynzo** [comment]
Thank you for the concise answers on those points. 

I apologize as I may have unintentionally led us down an alley of euphemistic terms like "seen" and "looked at". In trying to be plain and simple I may have actually done the opposite.

In more specific terms, one example data set breaks down like this: 

Total disk usage: 185.9 GiB  
Apparent size: 185.9 GiB  
Items: 27436

I'm still trying to figure out what would cause the behavior I'm seeing. Given those numbers is there a change I should be making to the TTL setting? My worry is that I'm completely misunderstanding the TTL information in the FAQ and here.

The details are from one self-contained source from one backup client to one self-contained backup repo (not shared). The content is just raw photo and video files exported from SD cards and digital cameras. It is the "source" library that I copy things out of to build other projects or libraries out of. The files generally don't change or get deleted as they are meant to be the reference/immutable source versions. Files do get added on a regular basis.

The mount is always present on the backup client VM. The first thing my backup script does is check for a flag file in the mount. If the flag file is not present, the script exits immediately. There shouldn't be a state where the backup starts and the mount and it's files aren't present. In fact, if I fire up the backup again right after it finishes with no other operations between, I still see all the files showing up as "M".

After some thought, I'm actually not as concerned about this. I now kind of like the idea that all the source files are being fully chunked/compared. Now, if I see the resulting backup stats and see more than a few KB in deduplicated size I'll know something is wrong. This whole thing came out of the thought that maybe I had been hit by some file encryption malware after seeing all the "M"'s in the first place. It would still be nice to solve as the backups are taking hours when they used to take a couple minutes.

Thank you for your patience.

**Comment by ThomasWaldmann** [comment]
To answer whether it is the ttl or not, i need all the borg create commands (complete command) that run against the repo that shows the issue (until the commands repeat).

**Comment by jdchristensen** [comment]
If nothing else is being backed up to the repo in between the commands that result in M status, then TTL won't be the culprit.  Can you reproduce on a subset of, say, 5 files, to make it faster for you to do tests?  As TW said, give the full sequence of commands and actions that lead to the problem, with the output.

**Comment by DrBrynzo** [comment]
I'm mystified now. I can no longer reproduce the behavior. I carefully went back through my backup script logs and this issue only manifested from January 17 to January 22. Since January 23, backups have returned to normal and only new and actually modified files are being backed up again.

The systems were both rebooted between Jan. 21-22 and the problem survived the reboot so I opened this request. I ran the backup manually several times on Jan. 22 and still observed all the files with "M" status, so I'm very confused about what the cause could have been as the systems have been in a steady state with no modifications since opening the request.

I think the only thing I hate more than crashes, errors and problems are phantom issues like this that suddenly clear themselves. I hate that I'm probably going to be watching my backup logs like a hawk for the foreseeable future but I have to say I guess there's nothing to see here and move along... Equal parts relieving and frustrating as it is.

Thanks for your time and insights.

**Comment by ThomasWaldmann** [comment]
Strange. Did you remove some backup job?

**Comment by DrBrynzo** [comment]
No. This configuration is among my most stable. I set it up in May of 2019 and it has very strict "do not touch" designs in place including permissions, configuration tracking using checksums and git, and regularly performed test restores with binary comparisons. It solely exists to be my main disaster recovery source and is designed to be very static. I do lots of DR design/planning as part of my career so I like to think I take it pretty seriously even with my personal stuff.

**Comment by DrBrynzo** [comment]
I don't know if this is interesting still or not (or if it was to begin with), but it happened again last night with a couple of the backup sets. A "set" in this case is a single backup on single client to a single, unshared repo. I haven't touched/changed any of the configuration and no files were added, removed, or modified in the source.

I think this might be related to something Synology is doing now, but whatever it might be doing isn't actually changing files (no modification times or change in MD5 signature) or even the "stat" output of the files.

Command (BORG_PREFIX is defined as "moments" earlier in the script):

borg create \
    --verbose \
    --filter AME \
    --list \
    --stats \
    --show-rc \
    --compression auto,lzma \
    --exclude-caches \
    --exclude '*.DS_Store' \
    --exclude '*._*' \
    --exclude '*Thumbs.db' \
    ::$BORG_PREFIX-'{now}' \
    /data/homes/bryn/Drive/Moments \
    /data/media/bryn/pictures

Archive name: bryn_moments-2021-01-28T00:32:25
Archive fingerprint: eb3867b89d3d4e7733b782f24abdc21e5a8c12d7a059ed15e0939bed1712fddf
Time (start): Thu, 2021-01-28 00:32:29
Time (end):   Thu, 2021-01-28 03:08:41
Duration: 2 hours 36 minutes 12.10 seconds
Number of files: 54957
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              433.22 GB            428.58 GB             32.95 MB
All archives:               46.32 TB             45.82 TB            215.82 GB

                       Unique chunks         Total chunks
Chunk index:                  112361             22559811
------------------------------------------------------------------------------
terminating with success status, rc 0


Almost all of the "M" files were in the "Moments" folder, which is maintained by the Synology Moments application and backed by Synology Drive. The only files that showed up from the "pictures" folder were four files (status "A") that were added a few days ago with the same time stamp and are the most recently added files, which is an expected borg behavior.

Another backup of a document folder (text files and scripts and such) showed the same "M" behavior again but it also is stored under the umbrella of Synology Drive. Again, no changes to files, time stamps, "stat" output. 

Other backup scripts/jobs from last night of sources from the NAS that are NOT managed by Synology Drive look "normal".

For lack of a better explanation, I'm leaning toward the idea that Synology Drive is doing *something* that is triggering borg to "see" modifications where other applications (rsync, Duplicacy, Synology Hyper Backup) are not but it's not daily/consistent or seemingly detectable using any of the utilities or tools I've tried to troubleshoot with.

So, while this is looking like it's NOT really a borg problem in any way, it would still be great to figure out WHY it's happening to surface potential mitigation options so backups that should take under 10 minutes are not taking hours and blocking other maintenance tasks. Perhaps I could even run a flag up the pole at Synology had I some causality.

**Comment by ThomasWaldmann** [comment]
Do you have non-ascii chars in the path/filenames of these files?

**Comment by DrBrynzo** [comment]
Shouldn't be anything non-alpha, just folders of JPEGs and a few movie files, a quick snippet (can provide the whole list/output privately if needed):

M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00448_n_11acpbv88t0428_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00449_n_11acpbv88t0429_z.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00450_n_11acpbv88t0430_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00451_n_11acpbv88t0431_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00452_n_11acpbv88t0432_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00453_n_11acpbv88t0433_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00454_n_11acpbv88t0434_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00455_n_11acpbv88t0435_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00456_n_11acpbv88t0436.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00457_n_11acpbv88t0437.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00459_n_11acpbv88t0439.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00460_n_11acpbv88t0440_g.jpg
M /data/homes/bryn/Drive/Moments/Pictures/Photos/2002/2002-05/00461_n_11acpbv88t0441_g.jpg

**Comment by ehannes** [comment]
@DrBrynzo did you solve this issue? It appears as if I have the same problem, or at least a similar one. All my files are listed as modified. In my case, I have two borg repositories connected to the same set of files - I backup the files to two different locations. It might have something to do with the problem. I use borg on several other machines and I don't see the problem with modified files there.

**Comment by DrBrynzo** [comment]
It's not really "solved" so much as "side-stepped". I did a little more testing by setting up another backup of the same data that was instead copied locally to the machine initiating the backup using rsync, i.e.:

rsync -a NAS:/volume1/files/to/back/up /local/files/to/back/up

I discovered that Synology will use a .ssh/authorized_keys file with rsync so I'm avoiding the SMB share for backups. Whatever file-tickling Synology is doing that was causing the issue over SMB doesn't seem to affect rsync copies. This means that (at the cost of local disk space on the backup server) I'm seeing expected behavior now and don't have the original problem of Borg "seeing" changed files. I've chosen to view the "lost" disk space on my backup server as an investment in having another live copy of my data for quick recovery and change reference, so it works out.

I know I could run BorgBackup on the Synology (there is even a SynoCommunity package) but I like to avoid modifications outside of Synology's native tools as much as possible. Their systems are not designed to be general computing devices even though lots of people seem to want to die on that hill with smoking craters where their data used to be. This rsync setup worked without any modifications other than enabling rsync and uploading a public key so it should survive changes/upgrades to DSM and not mess with anything under the hood.

**Comment by ThomasWaldmann** [comment]
Not sure it helps, but just FYI:
- rsync uses mtime, size (IIRC)
- borg uses ctime, size, inode number (by default, see `--files-cache` option)

**Comment by ehannes** [comment]
Found my problem. It was completely unrelated to borg. Thanks @ThomasWaldmann for pointing out `ctime` (and for a splendid backup solution, I love it :heart:), that was the problem in my case. I take backup of files mounted inside a Docker container, and the `ctime` changes when I start/stop the container and thus mount the volume inside the container.
