### ISSUE TITLE
check whether we can remove some bundled code

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5648]
only for master branch.

e.g.:
- lz4
- zstd
- xxh64
- crc32

preferably, such stuff is used via a library, but to unbundle, we need the library to be widely available.

that also applies to the systems we use to build the fat binary releases with pyinstaller:
- debian stretch / buster
- macOS / brew
- FreeBSD

**Comment by ThomasWaldmann** [comment]
@enkore borg.algorithms has a docstring like:

Ideally these would be sourced from existing libraries,
but:

- are available but in poor form (crc32), or
- don't really make sense as a library (xxHash).

Do you remember what was poor about crc32 libs and why xxHash doesn't make sense as a library?

**Comment by m3nu** [comment]
You mean the three libs referenced [here](https://github.com/borgbackup/borg/blob/940768ef2a718a9e5d36f794332aedefc93a8ff5/setup.py#L50) in `setup.py:50` and below?

For macOS they are all (lz4, zstd, xxhash) available and Borg finds them during installation without issues. We also install them in the [Vagrant file](https://github.com/borgbackup/borg/blob/5d46395ed0768c24621c77e621f4ccaccf43f509/Vagrantfile#L99), [Fuse-Homebrew formula](https://github.com/borgbackup/homebrew-tap/blob/c94af611623ab0209bc64dd17663b160cb80dc67/Formula/borgbackup-fuse.rb#L41) and [official Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/72ca6364fe412b68e90ced8c3ccfe79885c2e22f/Formula/borgbackup.rb#L26).

Noticed that xxHash had a bug and didn't add a version number to their pkgconfig file. So Borg didn't find it by itself. This should be [fixed](https://github.com/Cyan4973/xxHash/commit/b4dbf5fefc37b8a5f80b3bbc6b8ff639cf5f0ec2) in the next release 0.8.1. After that we could add xxHash to the Vagrant file and our internal Homebrew formula.

For libb2, you already removed the bundled version from what I see. So this is a hard dependency starting from 1.2? If so I'll be sure to update Vagrant and Homebrew for it.

**Comment by ThomasWaldmann** [comment]
Yes + also some other stuff below `src/borg/algorithms`.

Ah, good that xxHash got its pkgconfig fixed.

**Comment by enkore** [comment]
I'd guess I wrote that comment ("don't really make sense as a library (xxHash).") from the PoV of hashing small data, which is one of the design objectives of xxHash. In that case, it is something that should be linked and preferably LTO'd into one binary instead of being in a shared object. This isn't relevant to Borg. It seems many distributions picked it up though in the last ~two-ish years. So that's good news :)

Re. CRC32 IIRC there just wasn't a library–as an actual project–with a state-of-the-art implementation at the time. Don't know if that changed.

**Comment by ThomasWaldmann** [comment]
superseded by #6316.
