### ISSUE TITLE
How to suppress prompt output if they are skipped via environmental variable?

### ISSUE THREAD

**Issue by AlphaJack** [borgbackup/borg#5653]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

`borg 1.1.14`

#### Operating system (distribution) and version.

Not relevant

#### Hardware / network configuration, and filesystems used.

Not relevant

#### How much data is handled by borg?

Not relevant

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg list --last 1 "$unknownRepo" | awk '{print $1}' 2>> "logfile"`
`borg extract --list --info "$unknownRepo::lastArchive" &>> "logfile"`

## Describe the problem you're observing.

My script output gets polluted by Borg prompts even if I am redirecting both STDERR and STDOUT to a separate log file.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Running the command above, with the proper environmental variable set, returns the following:

```
===> Extracting Borg archives                                                                                                       
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
[OK] Extracted Borg archive BS210122T1732 for repo a                                                                         
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
[OK] Extracted Borg archive BS210122T1729 for repo b                                                                
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
[OK] Extracted Borg archive BS210122T1728 for repo c                                                                           
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
[OK] Extracted Borg archive BS210123T0321 for repo d                                                                        
```

My expected output should look like this:

```
===> Extracting Borg archives                                                                                                                                                    
[OK] Extracted Borg archive BS210122T1732 for repo a                                                                                                                  
[OK] Extracted Borg archive BS210122T1729 for repo b                                                                                                            
[OK] Extracted Borg archive BS210122T1728 for repo c                                                                                                                       
[OK] Extracted Borg archive BS210122T1726 for repo d                                                                        
```

A workaround is putting `borg extract --list --info "$unknownRepo::lastArchive" &>> "logfile"` inside a variable, but I would like to know if there are better ways to do suppress the prompt.

#### Include any warning/errors/backtraces from the system logs

Not relevant

**Comment by ThomasWaldmann** [comment]
I doubt you redirect both output channels. There is no other output channel than stdout and stderr for something to come out of borg.

**Comment by jdchristensen** [comment]
The list command shown does not have stderr redirected.

**Comment by AlphaJack** [comment]
> The list command shown does not have stderr redirected.

I mistyped the first one, I've added `2>` because I need stdout from that output, but I can still see stderr (even if I point to /dev/null) 
Why it shouldn't work? I use `&>` to redirect both stdout and stderr in all of my scripts. An example is `systemctl enable service &>/dev/null`, which doesn't print anythig compared to `systemctl enable service >/dev/null` (in this case systemd uses stderr).

Output comparison:  
`borg list --last 1 "/path/to/repo" | awk '{print $1}'` (show everything)
```
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
BS210122T1728
```

` borg list --last 1 "/path/to/repo" | awk '{print $1}' 2>/dev/null` (hide stderr)
```
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
BS210122T1728
```

`borg list --last 1 "/path/to/repo" | awk '{print $1}' >/dev/null` (hide stdout like "1>")
```
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
```

`borg list --last 1 "/path/to/repo" | awk '{print $1}' &>/dev/null` (hide both)
```
Warning: Attempting to access a previously unknown unencrypted repository!                                                         
Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)                                                
```

**Comment by jdchristensen** [comment]
You are only redirecting stderr of the second process in the pipeline (awk) not the first.  The pipe only sends stdout of borg to awk, not stderr.  This is clearly a scripting issue and not a borg issue.

**Comment by AlphaJack** [comment]
You are right, I had to put `2>/dev/null` before the pipe. Many thanks!

**Comment by SR-G** [comment]
On my side, i have roughly the same need (and i don't see any elegant solution) : 
1. I also would like to NOT see all the messages like `Do you want to continue? [yN] yes (from BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK)` (dumped on stderr)  
2. But on the other hand to still be able to see the other messages that are also dumped on stderr, like : `Archive volume-netdata-config_2022-11-01 already exists`

(of course if i redirect stderr to null, i hide first use kind of messages but then i'm also hiding second kind of messages ...)

Any ideas ?

**Comment by ThomasWaldmann** [comment]
You only should see the "unknown unencrypted repo" warning once. After you accepted to use it (manually "y" or by using the env var), it is not unknown any more and thus should not warn any more.

**Comment by SR-G** [comment]
Do you mean that the fact that one answer has been entered once is persisted somewhere by borg ? (like in ~/.<something>)

Right now my use case is to mount (volatile) docker container with only the borg backup binary inside it (in order to automatically backup the content of several data volumes on several different nodes), so it's a fresh blank start each time = hence, for now, i'm seeing that message constantly in aggregated logs.

But maybe i can try to add the "something being persisted" inside the container, i'll try to find what it may be

**Comment by ThomasWaldmann** [comment]
Yes, either in .cache/borg or .config/borg, just have a look.
