### ISSUE TITLE
macOS: test borg mount with macFUSE 4.x

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5660]
macFUSE 4.x is the successor of OSXfuse 3.x - does it work as expected?

**Comment by m3nu** [comment]
Works fine with `llfuse`, but not `pyfuse3`, since macFUSE only supports fuse v2 API, not v3:

> pyfuse3 requires a libfuse 3.x compatible API. OSXFUSE only supports the libfuse 2.9 API. (from [here](https://github.com/libfuse/pyfuse3/issues/32))

Steps done to test:

1. Install macFUSE
2. Restart
3. `$ BORG_OPENSSL_PREFIX=/usr/local/Cellar/openssl@1.1/1.1.1i pip install '.[llfuse]'`
4. `$ borg mount /Users/manu/Downloads/test-repo::1 ~/Downloads/mnt`
5. Archive is mounted as expected

**Comment by m3nu** [comment]
So this is also a docs issue to mention that Borg on macOS only works with `llfuse`?

**Comment by ThomasWaldmann** [comment]
Well, yes, but we need to be careful because that could change over time, when macFUSE switches to fuse3 some day.

**Comment by m3nu** [comment]
So anything left to do here? Is it worth adding a note on using `llfuse` only in the docs here: https://borgbackup.readthedocs.io/en/master/installation.html#macos ?

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/master/installation.html#dependencies guess we should just tell there what fuse versions llfuse and pyfuse3 needs, this will apply to all operating systems.

**Comment by ThomasWaldmann** [comment]
About BORG_OPENSSL_PREFIX - isn't openssl discovered via pkg-config in master branch?
Did you:
- brew install pkg-config
- pip install pkgconfig
- then pip install borgbackup[llfuse]
?

**Comment by m3nu** [comment]
No. By default the Homebrew openssl formula is NOT linked. Adding it to pkg-config is mentioned as optional step.

```
$ brew info openssl
openssl@1.1: stable 1.1.1i (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
...
openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

Worth documenting [here](https://borgbackup.readthedocs.io/en/stable/installation.html#mac-os-x)? I think the error is already quite clear. Else we could add:

> To make sure the Homebrew-provided `openssl` library is found, set `BORG_OPENSSL_PREFIX=/usr/local/Cellar/openssl` or `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` before running `pip install`

**Comment by ThomasWaldmann** [comment]
OK, guess that is to support 1.0 and 1.1 (and maybe future other versions) in parallel.

**Comment by m3nu** [comment]
And also to avoid conflicts with the macOS-shipped LibreSSL:

> openssl@1.1 is keg-only, which means it was not symlinked into /usr/local, because macOS provides LibreSSL.

Anyways, should I add a short note to the macOS "install from source" docs [here](https://borgbackup.readthedocs.io/en/stable/installation.html#mac-os-x)?

**Comment by ThomasWaldmann** [comment]
@m3nu Yeah, looks like that needs an update.

**Comment by m3nu** [comment]
Added two notes on the openssl thing and the compatible Python-FUSE library under the macOS section.

**Comment by m3nu** [comment]
I snuck another change into my PR to use `macFUSE` instead of `osxfuse`. The former is needed for Apple M1 chips, [according](https://github.com/osxfuse/osxfuse/issues/754#issuecomment-756014190) to the developer.

The formulas are almost the same and I already [updated](https://github.com/borgbackup/homebrew-tap/issues/6) Borg's own formula to use macFUSE.

**Comment by m3nu** [comment]
Thanks for merging!

One more thing: On macOS with an Apple M1 chip, the [Homebrew prefix](https://github.com/borgbackup/homebrew-tap/issues/6#issuecomment-781393275) is different and not in the [current list](https://github.com/borgbackup/borg/blob/1.1-maint/setup.py#L170). OK to add it in `1.1-maint`?

**Comment by ThomasWaldmann** [comment]
Merged the PR. ^^^

So, all done here? Close?

**Comment by m3nu** [comment]
Yeah. Hope the new setup works for a while. Let's close.
