### ISSUE TITLE
"not a valid repository. Check repo config."

### ISSUE THREAD

**Issue by paulmcclellan** [borgbackup/borg#5663]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg 1.1.15

#### Operating system (distribution) and version.
Unraid Version: 6.8.3

#### Hardware / network configuration, and filesystems used.
i5-6440, 16GB RAM, 5 x 3TB disks, plus 2 SSDs for cache.  

#### How much data is handled by borg?
4 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create -s -p /mnt/disks/easystore::$(date +%F)-UnraidBackup  /mnt/user/Unraid

## Describe the problem you're observing.
I have been backing up to an external disk for a while.  I switched to a bigger disk and continued backups without issue.  However once I removed the original external disk, Borg no longer "sees" the repository, so won't allow any operations.  I receive this error:

"/mnt/disks/easystore is not a valid repository. Check repo config."

I tried "borg recreate easystore /mnt/disks/easystore", which took over 24 hours.  It had a warning: "Warning: Attempting to access a previously unknown unencrypted repository!  Do you want to continue?"  I entered "y".  It seemed to process each backup (e.g.: Processing 2021-01-24-UnraidBackup), and it returned no errors.   
However I still can't connect to the repository, and receive the same "not a valid repository.  Check repo config" error.

Is it possible to repair?  If not, can I simply delete the repository, and start over?

TIA

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes.  Can repro with any Borg command

#### Include any warning/errors/backtraces from the system logs
I haven't found any yet.

**Comment by ThomasWaldmann** [comment]
"/mnt/disks/easystore is not a valid repository. Check repo config."

Can you give the output of `cat /mnt/disks/easystore/config`? In case there is an encryption key in it, please remove/shorten it.

**Comment by ThomasWaldmann** [comment]
That looks like a valid config. Is there some permissions or fs issue triggering borg saying it is not valid?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.1.15/src/borg/repository.py#L418

- the given repo path is not a directory
- the given repo path does not contain a `config` file
- the config files does not have a `[repository]` section with `version = 1`

**Comment by paulmcclellan** [comment]
/mnt/disks/easystore is a directory.  

Now borg create -s -p /mnt/disks/easystore/easystore::$(date +%F)-UnraidBackup /mnt/user/Unraid

returns:

Exception ignored in: <function Repository.__del__ at 0x1524478ca280>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/borg/repository.py", line 180, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/usr/lib64/python3.9/site-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib64/python3.9/site-packages/borg/repository.py", line 446, in open
    self.id = unhexlify(self.config.get('repository', 'id').strip())
binascii.Error: Odd-length string

Platform: Linux Tower 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020 x86_64
Linux: Unknown Linux  
Borg: 1.1.15  Python: CPython 3.9.0 msgpack: 0.5.6
PID: 25627  CWD: /mnt/disks/easystore
sys.argv: ['/usr/bin/borg', 'create', '-s', '-p', '/mnt/disks/easystore::2021-01-29-UnraidBackup', '/mnt/user/Unraid']
SSH_ORIGINAL_COMMAND: None

This seems to be from repository.py line 177:
   def __del__(self):
        if self.lock:
            self.close()
            assert False, "cleanup happened in Repository.__del__"

**Comment by ThomasWaldmann** [comment]
Use a valid repo id.

On 30 January 2021 00:20:20 CET, paulmcclellan <notifications@github.com> wrote:
>/mnt/disks/easystore is a directory.  
>
>Now borg create -s -p /mnt/disks/easystore/easystore::$(date
>+%F)-UnraidBackup /mnt/user/Unraid
>
>returns:
>
>Exception ignored in: <function Repository.__del__ at 0x1524478ca280>
>Traceback (most recent call last):
>File "/usr/lib64/python3.9/site-packages/borg/repository.py", line 180,
>in __del__
>    assert False, "cleanup happened in Repository.__del__"
>AssertionError: cleanup happened in Repository.__del__
>Local Exception
>Traceback (most recent call last):
>File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4621,
>in main
>    exit_code = archiver.run(args)
>File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 4553,
>in run
>    return set_ec(func(args))
>File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 162,
>in wrapper
>    with repository:
>File "/usr/lib64/python3.9/site-packages/borg/repository.py", line 190,
>in __enter__
>self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait,
>lock=self.do_lock)
>File "/usr/lib64/python3.9/site-packages/borg/repository.py", line 446,
>in open
>    self.id = unhexlify(self.config.get('repository', 'id').strip())
>binascii.Error: Odd-length string
>
>Platform: Linux Tower 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST
>2020 x86_64
>Linux: Unknown Linux  
>Borg: 1.1.15  Python: CPython 3.9.0 msgpack: 0.5.6
>PID: 25627  CWD: /mnt/disks/easystore
>sys.argv: ['/usr/bin/borg', 'create', '-s', '-p',
>'/mnt/disks/easystore::2021-01-29-UnraidBackup', '/mnt/user/Unraid']
>SSH_ORIGINAL_COMMAND: None
>
>This seems to be from repository.py line 177:
>   def __del__(self):
>        if self.lock:
>            self.close()
>            assert False, "cleanup happened in Repository.__del__"
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbackup/borg/issues/5663#issuecomment-770100874

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paulmcclellan** [comment]
Thanks Thomas!  That was it.  Working fine again!
