### ISSUE TITLE
add a freebsd 32bit build machine to the Vagrantfile

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#567]
and before, try whether pyinstaller works on 32bit freebsd.

**Comment by ThomasWaldmann** [comment]
seems there is no ready-to-use 32bit freebsd vagrant box.

**Comment by breyer** [comment]
I setup a vagrant FreeBSD 10.2 i386 box for testing. Never done this before, so if something is not working, give me a chance to fix it. You can download the box from https://www.breyer.eu/vagrant/FreeBSD-10.2-i386.box

**Comment by breyer** [comment]
My progress currently stops while i try to compile borg on my freebsd32 test machine.
This is line 201 in the Vagrantfile > pip install 'llfuse<0.41'.

Any ideas?

```
(borg-env) [vagrant@FreeBSD-10 /vagrant/borg/borg]$ pip install 'llfuse<0.41'
Collecting llfuse<0.41
  Using cached llfuse-0.40.tar.bz2
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/vagrant/borg/borg-env/lib/python3.5/site-packages/pip/req/req_install.py", line 375, in setup_py
    import setuptools  # noqa
  File "/vagrant/borg/borg-env/lib/python3.5/site-packages/setuptools/__init__.py", line 14, in <module>
    from setuptools.extension import Extension
  File "/vagrant/borg/borg-env/lib/python3.5/site-packages/setuptools/extension.py", line 10, in <module>
    from .dist import _get_unpatched
  File "/vagrant/borg/borg-env/lib/python3.5/site-packages/setuptools/dist.py", line 21, in <module>
    from setuptools import windows_support
  File "/vagrant/borg/borg-env/lib/python3.5/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/home/vagrant/.pyenv/versions/3.5.1/lib/python3.5/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named '_ctypes'
```

**Comment by ThomasWaldmann** [comment]
try again with 'llfuse<0.42'. if it also fails, file a bug in the llfuse issue tracker.

**Comment by ThomasWaldmann** [comment]
but that's a bit strange, when i made the 1.0 rc1 for freebsd 64bit, llfuse worked (iirc).

**Comment by jungle-boogie** [comment]
HI @breyer,

What version of python is pip linked against?

**Comment by breyer** [comment]
@ThomasWaldmann 
right, 1.0 rc1 worked for me also on 64bit. will try from beginning tomorrow.

@jungle-boogie 
3.5.1

**Comment by jungle-boogie** [comment]
I'm able to install both llfuse<0.42 and llfuse<0.41 on real 32bit hardware with freeBSD 10.2

**Comment by breyer** [comment]
I setup a fresh freebsd 32bit and 64bit build machine. Works fine for me. Hope i`ve done everything right, it`s my second commit on github.

**Comment by ThomasWaldmann** [comment]
thanks for the effort. i just did never get to adopt freebsd 32 to my platform testing VMs.

and now (for borg 1.2), I guess I rather think about dropping 32bit platforms than adding new ones.
