### ISSUE TITLE
Is --verify-data required for checking in append-only mode

### ISSUE THREAD

**Issue by ianw** [borgbackup/borg#5681]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

The documentation on append-only mode says

> 
> Even if an archive appears to be available, it is possible an attacker could delete just a few chunks from an archive and silently corrupt its data. While in append-only mode, this is reversible, but borg check should be run before a writing/pruning operation on an append-only repository to catch accidental or malicious corruption:
> 
> run without append-only mode
> borg check --verify-data repo

It is unclear to me if the threat discussed means it is necessary to run with ``--verify-data`` to find the corruption; or will ``--repository-only`` or ``--archives-only`` find similar corruption?

**Comment by ThomasWaldmann** [comment]
If you want to verify all the file contents, then you need to use `--verify-data`. Of course, it will read all archived file contents then and be quite slower.

**Comment by ianw** [comment]
Thanks, I'm specifically wondering if the attack mentioned

> it is possible an attacker could delete just a few chunks from an archive 

would be found with just an archive check?  It sounds like yes (the chunk is gone, which is noticed)?

I have full verifications happening in the background weekly.  I'm just wondering what the minimum should be done before issuing a prune command.

**Comment by ThomasWaldmann** [comment]
Deleting is maybe relatively obvious. More evil would be to replace the original data by crap data.

**Comment by enkore** [comment]
... and for that you need --verify-data.
