### ISSUE TITLE
Doesn't work when invoked via a symlink

### ISSUE THREAD

**Issue by cherio** [borgbackup/borg#5688]
This looks like a regression in 1.1.15 as it used to work with 1.1.14.

I extract `borg` versions from `borg-linux64.tgz` into version specific directories e.g.
`/home/user/opt/.versions/borg-1.1.14`
`/home/user/opt/.versions/borg-1.1.15`

Then I symlink it into the user bin directory, e.g.
`ln -sf /home/user/opt/.versions/borg-1.1.14/borg.exe /home/user/bin/borg`

This works when invoked from anywhere by the user `user` e.g.
`borg --help`

The same no longer works if I symlink to 1.1.15
`ln -sf /home/user/opt/.versions/borg-1.1.15/borg.exe /home/user/bin/borg`
`borg --help`
produces this error
`[1576546] Error loading Python lib '/home/user/bin/libpython3.7m.so.1.0': dlopen: /home/user/bin/libpython3.7m.so.1.0: cannot open shared object file: No such file or directory`

**Comment by ThomasWaldmann** [comment]
borg 1.1.15 was the first version built with pyinstaller 4.0 (1.1.14 used 3.2.1), so this could be a regression in pyinstaller.

**Comment by ThomasWaldmann** [comment]
https://github.com/pyinstaller/pyinstaller/issues/4674

https://github.com/pyinstaller/pyinstaller/pull/5232 fixed this in pyinstaller 4.2.

**Comment by ThomasWaldmann** [comment]
@cherio i upgraded pyinstaller in #5689, so this should be fixed in next release.

while testing the new bootloader, I also tested symlinking:

```
ln -s borg-dir/borg.exe b
./b help  #  <--- worked
```
