### ISSUE TITLE
Command options --config-dir and --cache-dir

### ISSUE THREAD

**Issue by NixNotCastey** [borgbackup/borg#5692]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature request

#### Your borg version (borg -V).
borg 1.1.15

## Describe the problem you're observing.

It would be nice to have option to change cache dir and config dir from default ~/.cache and ~/.config.
I usually have small partition for /root on servers and bigger separately mounted directories based on current needs and role of server. Ability to change cache (and optionally config) directory would be nice. Currently, I have settled workaround for this by mounting separate share to /root/.cache

Another advantage of this option would be the possibility to store cache on a faster tier of storage.

Alternative solutions have this option available.

**Comment by ThomasWaldmann** [comment]
See the borg docs about environment variables.

**Comment by NixNotCastey** [comment]
Sorry, I used search on docs on readthedocs and issues here on github and doesn't find options for this.
I searched a "cache dir" and "cache" phrases and "Environment Variables" wasn't suggested, witch is weird because on Environment Variables word "cache" is used.

Thanks for pointing out docs.
