### ISSUE TITLE
Have pretty error msgs without losing debug capability

### ISSUE THREAD

**Issue by rumpelsepp** [borgbackup/borg#57]
When I try to push to an existing archive an exception is raised. A nice error message would be better.

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 857, in main
    exit_code = archiver.run(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 813, in run
    return args.func(args)
  File "/usr/lib/python3.4/site-packages/borg/archiver.py", line 107, in do_create
    numeric_owner=args.numeric_owner, progress=args.progress)
  File "/usr/lib/python3.4/site-packages/borg/archive.py", line 148, in __init__
    raise self.AlreadyExists(name)
borg.archive.AlreadyExists: laptop-2015-06-17
borg: Error: Archive laptop-2015-06-17 already exists
```

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/22342961-have-pretty-error-msgs-without-losing-debug-capability)

**Comment by ThomasWaldmann** [comment]
yes, you are right. attic tries to have less tracebacks and more pretty error msgs, but sometimes it also hides useful information due to that.

In borg, I switched that to have more tracebacks and less prettyness, to be able to find issues using the tracebacks.

**Comment by anarcat** [comment]
how about this being a function of `-v` ? or maybe a `--debug` flag specifically for tracebacks or hooking in a debugger?

see also #74.

**Comment by ThomasWaldmann** [comment]
@anarcat no, I don't think that is an option. You can not always know in advance that a traceback will happen, it might happen only once or only rarely and we need those tracebacks to fix any such issue.

But we need to differently handle such exceptions than rather "normal" error conditions, like an already existing archive name. In the latter case, the user should see a normal error message, not a traceback.

**Comment by anarcat** [comment]
true. then we could have two classes of exceptions: warnings and errors, maybe? the latter being the only one triggering an exception...

**Comment by ThomasWaldmann** [comment]
I almost changed the Error class to be able to return different exit_codes (or having a Warning class also).
But then I found that if such an exception reaches the toplevel error handler (and exits with that error code), it is always an error in the sense of abrupt termination, not reaching the normal operation end.
