### ISSUE TITLE
"File name too long" when running borgbackup on OSX via pwsh

### ISSUE THREAD

**Issue by futuralogic** [borgbackup/borg#5709]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

`borg 1.1.11`

#### Operating system (distribution) and version.

OSX Mojave 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64

#### Hardware / network configuration, and filesystems used.

Macbook Pro (Retina, 15-inch, Mid 2014)
2.5 Ghz Intel Core i7
RAM 16GB
File system: Apple APFS main system drive

Mounting borg repo to /Volumes/Backups via CIFS from a Synology NAS (with external USB drive on the Synology hosting the repo, formatted NTFS, thus only shareable via CIFS on Synology)

#### How much data is handled by borg?

1.9 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```powershell
# Set my repo access key as an env variable which is used by borg to decrypt the archives. String is 1,368 characters
$Env:BORG_PASSCOMMAND=$(security find-generic-password -a $Env:USER -s borg-passphrase -w)
# Repo path
$REPO="/Volumes/Backups/nas"
# List archives in the repo
borg list $REPO
```

### Expected behavior

A list of repos

```none
# Borg output when it lists repos:
archive1-2018-02-26-19-57            Mon, 2018-02-26 19:57:53 [5c2b...]
archive1-2018-03-27-18-06            Tue, 2018-03-27 18:06:12 [cbda...]
archive1-2018-10-07-22-57            Sun, 2018-10-07 23:08:16 [7871...]
...
```

## Describe the problem you're observing.

```none
> borg list $REPO
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4529, in main
  File "borg/archiver.py", line 4461, in run
  File "borg/archiver.py", line 153, in wrapper
  File "borg/helpers.py", line 375, in load
  File "borg/crypto/key.py", line 134, in key_factory
  File "borg/crypto/key.py", line 594, in detect
  File "borg/crypto/key.py", line 435, in env_passphrase
  File "borg/crypto/key.py", line 449, in env_passcommand
  File "subprocess.py", line 316, in check_output
  File "subprocess.py", line 383, in run
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1289, in _execute_child
OSError: [Errno 63] File name too long

Platform: Darwin nameless.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64
Borg: 1.1.11  Python: CPython 3.5.9 msgpack: 0.5.6
PID: 55531  CWD: /Users/nameless
sys.argv: ['/usr/local/bin/borg', 'list', '/Volumes/Backups/nas']
SSH_ORIGINAL_COMMAND: None
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The issue happens reliably under pwsh core, but works fine in bash.

#### Console (OSX log app - Errors & Faults) shows:

`error	16:51:37.793204 -0600	pwsh	nw_path_close_fd Failed to close guarded necp fd 117 [9: Bad file descriptor]`

(Consequently, I notice this same error being logged from Visual Studio Code - perhaps because I use pwsh as my embedded terminal shell?) 

I am running these commands from pwsh inside vs code.  However, running pwsh via iterm2 results in the same issues.

For reference:
`error	16:58:45.133980 -0600	Code Helper (Renderer)	nw_path_close_fd Failed to close guarded necp fd 41 [9: Bad file descriptor]`

Opened this issue with the powershell team but they were unable to repro.
Issue: Powershell/Powershell#14833

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by infectormp** [comment]
You use outdated borg version. Can you reproduce this error with the latest version?

**Comment by ThomasWaldmann** [comment]
```
$Env:BORG_PASSCOMMAND=$(security find-generic-password -a $Env:USER -s borg-passphrase -w)
```

I don't know the shell you are using, but doesn't that mean that the "security find-generic-password ..." command will be executed and the resuling passphrase will be assigned to the env variable?

That would be useful for `BORG_PASSPHRASE` env var, but is **not** what you need for `BORG_PASSCOMMAND` - for the latter you just have the command (not the result of the command) as contents.

That would also explain the "filename too long" error message: your super long passphrase is given to borg as passcommand and borg tries to **execute that "command"** and then something complains about the super long filename of the "command".

**Comment by futuralogic** [comment]
This issue can be closed. @ThomasWaldmann's comment about the BORG_PASSCOMMAND vs. BORG_PASSPHRASE was the factor in this case.

I had occasion to reattempt utilizing powershell as my shell for backups and refactored the code to accommodate these suggestions and it worked successfully.

Fix:

`$Env:BORG_PASSCOMMAND = "security find-generic-password -a $Env:USER -s borg-passphrase -w"`
