### ISSUE TITLE
option to prevent multi-client use that can lead to confidentiality loss

### ISSUE THREAD

**Issue by aa755** [borgbackup/borg#5711]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

Question and/or feature request

## Describe the problem you're observing.

As a newcomer to borg, I am finding it hard to understand the conditions under which borg guarantees confidentiality, especially regarding multi-client use. The manual says "Borg is built upon a defined Attack model that cannot provide its guarantees for multiple clients using the same repository." It is not clear what exactly constitutes multi-client use. If my computer dies and I set up the same repo on a different computer, would that be multi-client use? (Probably not). It would be nice if I didn't have to worry about the subtleties of what constitutes multi-client use and also be protected from accidentally violating the no-multi-client-use requirement. Does/Can borg provide a setting where I declaratively tell it to prevent me from doing any multi-client-use that could violate confidentiality (assuming malicious borg host)?

**Comment by ThomasWaldmann** [comment]
IIRC, the docs strongly suggest to use 1 repo per client, so just do that?

**Comment by ThomasWaldmann** [comment]
The encryption issue is AES counter reuse. The counter needs to always increase, never repeat.

borg remembers highest counter value on client side (usually in `~/.config/borg/...`) and on repo side. but you maybe do not want to have too much trust in a remote repo on some machine not owned / controlled only by yourself.

one problem is that if you completely lose the client side, you lose your own "safe" counter value, then you have these options:
- trust the repo side counter (hoping that noone is attacking you)
- not continuing to make backups into that repo (== avoiding potential counter reuse), but init a fresh repo.

**Comment by ozppupbg** [comment]
With the new encryption schema seeming to pick up pace (e.g. https://github.com/borgbackup/borg/issues/3814), it might be worth to look into this again.

I've been thinking about multi-client (server) setups myself for some time.
With the counter issue resolved by new encryption, there is only one major question remaining in my opinion:

**How can multiple clients use the same repo manifest safely?**

For this I came up with two possible solutions:
- Use some sort of locking mechanism and a special "merge" operation between the local and remote archive manifest entries
- Give each new client a separate blank manifest to start from. This would only require the server to store separate all-zero-id manifest entries for each client.

I would prefer the second option, as it requries no changes on the client side and also improves security and reliability, as different clients cannot access or mess-up data/archives from other clients (as this would require guessing either the content of a file or a 256bit id-hash).

So as long, as no malicious client colludes with a compromized server, all security properties should hold in this scenario.

**Comment by ThomasWaldmann** [comment]
@ozppupbg hmm, you seem to talk about quite something different than borg is doing right now.

if the potential nonce reuse issues will be fixed, there are no "confidentiality issues" (see topic) left (AFAIK).

currently, borg locks the repo, so only one client can work in the repo at the same time.

one multi-client issue left (but not security related) is the cache coherency issue with the clientside chunks index.

for the far future, one could also think about concurrent lockless operation, but i do not think we should discuss all that in a single ticket.

**Comment by ThomasWaldmann** [comment]
fixed in borg2: as it derives a new encryption key per session (per borg invocation), it does not need to manage the counter any more, but can just starting to count from 0 in each session.
