### ISSUE TITLE
Feature to not exclude path even if parent was excluded, similar to what rsync does

### ISSUE THREAD

**Issue by power833** [borgbackup/borg#5716]
From what I could see, Borg doesn't have a feature similar to rsync's:

--include=PATTERN       don't exclude files matching PATTERN

which ensures PATTERN will always be included even if the parent folder might have been excluded for example. Could this be added?

**Comment by m3nu** [comment]
Already available as “Patterns”? Is this what you need? Be sure to check out the docs [here](https://borgbackup.readthedocs.io/en/stable/usage/help.html?highlight=patterns#borg-help-patterns). Or maybe you have a concrete example?

```
# backup pics, but not the ones from 2018, except the good ones:
# note: using = is essential to avoid cmdline argument parsing issues.
borg create --pattern=+pics/2018/good --pattern=-pics/2018 repo::arch pics
```

**Comment by power833** [comment]
Yes, it looks like this can accomplish exactly the same things as rsync's include.
