### ISSUE TITLE
I want to backup a file on a different server with ssh connection using Borg

### ISSUE THREAD

**Issue by BayramGrbz45** [borgbackup/borg#5717]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.15

#### Operating system (distribution) and version.

Ubuntu 18 server

#### Hardware / network configuration, and filesystems used.

static ip, ext 4

#### How much data is handled by borg?

10 gb

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create ssh://user@ip:port/./backup/test::2020-01-03 ssh://root@ip:/backup/testdata -vvv -s

#### Include any warning/errors/backtraces from the system logs

I want to backup a file on a different server with ssh connection using Borg

**Comment by m3nu** [comment]
This can be achieved by running Borg remotely, as suggested by Thomas some time ago: https://github.com/borgbase/vorta/discussions/841

Your command becomes: (not tested)

`ssh root@ip borg create ssh://user@ip:port/./backup/test::2020-01-03 /backup/testdata`

**Comment by ThomasWaldmann** [comment]
Yeah, as @m3nu said.

Just wanted to add that this is way more efficient because borg then has local access to the backup input files, can quickly skip unchanged files and even for changed ones it only needs to transfer new chunks it does not already have in the repo yet.

**Comment by BayramGrbz45** [comment]
The Borg backup server I have installed. I want to perform backup operations without installing borg to other servers via.


`borg create ssh://user@ip-1:port/./backup/test::2020-01-03 ssh://root@ip-2:/backup/testdata -vvv -s
`

**Comment by ThomasWaldmann** [comment]
You need borg on the machines. If you can't get a nice borg package from your dist, you can also just put the `borg` fat binary into `/usr/local/bin/` - see github release page for the binaries. The fat binaries have no external dependencies except a recent enough glibc.

For Ubuntu, there is also the borg package maintainer's PPA, where you can get fresh borg releases.

**Comment by jirib** [comment]
> The Borg backup server I have installed. I want to perform backup operations without installing borg to other servers via.
> 
> backup server : ip 1
> borg server: ip-3
> server: ip-2
> 
> `borg create ssh://user@ip-1:port/./backup/test::2020-01-03 ssh://root@ip-2:/backup/testdata -vvv -s `
> 
> _I have a server with a management center. I manage other servers with this server. I have uploaded a borg backup to this server. I want to do my backups without uploading borg to other servers._

SSHFS?
