### ISSUE TITLE
change --numeric-owner to --numeric-ids

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5724]
borg used to use `--numeric-owner` as option to trigger processing of numeric ids.

this is a bit unpretty as it does not only affect the **user**name / uid, but also the **group**name / gid.

rsync uses `--numeric-ids` to trigger similar behaviour, so let's use that.

Implementation note:
- deprecate old option name, but keep it for now
- change code to support new option name and use `numeric_ids` as attribute name.

**Comment by ThomasWaldmann** [comment]
note: after PR #5725 is merged.

**Comment by rlkenny98** [comment]
Hi I'd like to work on this. First time contributor here

**Comment by ThomasWaldmann** [comment]
Cool, just make a PR!

To get an idea about how to handle deprecation, just look at some other option that got deprecated already (see change log).

**Comment by rlkenny98** [comment]
@ThomasWaldmann Hey just created a PR for my changes! Did not address any code changes to support numeric_ids as an attribute name, but I went through and marked any mention of --numeric-owner/ numeric_owner as deprecated.

**Comment by ThomasWaldmann** [comment]
@rlkenny98 thanks for the effort, but this is not the way to do that.

borg users usually won't read the comments you put there and if you do not change the code in the same way as it was done for past deprecations of other options, most users of borg would not even notice that something was deprecated and have a hard time later when the option finally goes away and their backup scripts break.

so the approach for deprecation is to still accept the deprecated option and behave as usual, but to **emit a warning** so users will notice the deprecation (in their logs or on their screen) when using borg with that option. after noticing they will need to change their scripts so that the new option is used. that way, nobody will run into an issue when the deprecated option is remove later (except those who ignored all the warnings, but that is not our fault).

we already have such code, you simply need to extend that.

**Comment by ThomasWaldmann** [comment]
@rlkenny98 Are you still working on this?

**Comment by rlkenny98** [comment]
Hey sorry for the lack of responses, I am no longer working on this. Sorry for any inconveniences
!

**Comment by ThomasWaldmann** [comment]
OK, thanks for your effort!

**Comment by ThomasWaldmann** [comment]
@rlkenny98 i worked on this, see PR #5765:
- https://github.com/borgbackup/borg/pull/5765/commits/251ce11fd844f267c4a0e5ddef69706232d86c9b that is the rather manual part of solving this.
- https://github.com/borgbackup/borg/pull/5765/commits/6f9b9e5a53c3e1a19405aac1cc903af6da15b003 that is the search-and-replace-all cleanup part for the source code, so the internal variable names correspond to the new option name.
