### ISSUE TITLE
get rid of distutils

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5729]
some python 3.10 alpha version we use for testing now breaks all our testing (not only on 3.10, but also cancelling the other test runs) because of the `distutils` deprecation.

we use distutils:
- in setup.py to subclass and extend the `clean` command (to remove generated files by cython)
- for `LooseVersion` at 2 other places

The setuptools migration docs are rather unhelpful for this, subclassing is undocumented, could not find `clean` in setuptools and I also could not find a direct replacement for `LooseVersion`. Importing from `setuptools._distutils` runs into the same issues.

For borg 1.1.x there is also the requirement that we avoid adding new dependencies (while we still want to support python 3.10 for future 1.1.x releases), so using the `packaging` pypi package for some `Version` class is no solution.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt can you help, please?

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann the version from pkg_resources as first idea as it's intensely commonly part of the ecosystem as a starting point, for more, please hit me up tommorow, I'm a bit preoccupied with something and it will slip me

**Comment by RonnyPfannschmidt** [comment]
@jaraco perhaps has a better idea tho

**Comment by ThomasWaldmann** [comment]
`pkg_resources.parse_version()`

**Comment by RonnyPfannschmidt** [comment]
the idea for a starting point is pkg_resources as that one tends to be all time included monster (aka no new deps)
packaging wold be a new dep for sure

**Comment by jaraco** [comment]
I would try to avoid assumptions that `pkg_resources` is present. I'm actively working to discourage use of it at all, but definitely discouraging assuming it's present. I make sure not to install setuptools in my local environments and uninstall it if it gets installed. I'd recommend `packaging` even if it's an additional dependency.

**Comment by ThomasWaldmann** [comment]
In master, this was fixed by #5786, but if we want 1.1.x on py310, we still need a fix for 1.1-maint branch.

@LocutusOfBorg would adding `packaging` as addtl. python dependency be a problem for your 1.1.x packaging / backports?

**Comment by bket** [comment]
Concerning OpenBSD:
- No issues foreseen for packaging on current.
- Backporting should be OK as well, unless there is a dependency on a specific version of `packaging`. #5786 seems to suggest that this is not the case.

**Comment by m3nu** [comment]
Regarding macOS (formula [with](https://github.com/borgbackup/homebrew-tap) / [without](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/borgbackup.rb) FUSE support):

- Also no issues to expect.
- Currently the formula is pinned to Python 3.9

**Comment by FelixSchwarz** [comment]
Fedora has python packaging `20.4` / `20.9` in current releases so no problem here. Fedora 35 just had its big Python 3.10 rebuild so I'd be very interested to get  borgbackup compatible with Python 3.10 soon-ish.

EPEL 7 + 8 ship `16.8`. EPEL 8 has python-packaging in a special repo which is not enabled by default (but can be enabled easily). Judging from past experience with certbot I guess we'll get some bug reports about this but I can deal with these. Also I will probably not update borgbackup in EPEL 7/8 if this requires a repo upgrade or any kind of manual intervention.

So I'd say packaging is not a problem for Fedora+EPEL.

**Comment by bsiegert** [comment]
pkgsrc has https://pkgsrc.se/devel/py-packaging, so I do not foresee any problems.

More generally, if distutils stops working, a huge number of _other_ Python packages are probably going to break with Python 3.10 🙍‍♂️

**Comment by FelixSchwarz** [comment]
Btw: The test suite passed just fine in Fedora's 3.10 rebuild (using borgbackup 1.1.16) so unless I'm missing something I guess there is no need for immediate action. (Though I did not yet try to run borgbackup on a rawhide machine.)

Fedora build logs:
https://kojipkgs.fedoraproject.org//packages/borgbackup/1.1.16/2.fc35/data/logs/x86_64/build.log

@bsiegert I don't think distutils will stop working with 3.10.  The deprecation message is:
> The distutils package is deprecated and slated for removal in Python 3.12.

@ThomasWaldmann Python 3.10 alphas were a bit buggy. I vaguely remember that Cython triggered some bugs which were reported and/or fixed by Fedora's Python wranglers. But these should be gone for good. If you are interested I can ping you when borgbackup's test suite fails in Fedora's early rebuilds. For example Miro triggered test builds of Python software against Python 3.10 in December and Fedora maintainers do get early bug reports about these.

**Comment by LocutusOfBorg** [comment]
Debian/Ubuntu have recent enough packaging versions (>=16.6 and up to 20.9). No issues on our side I would say

**Comment by ThomasWaldmann** [comment]
Fixed: master: #5786, 1.1-maint: #5847
