### ISSUE TITLE
Question about setup of shell completion

### ISSUE THREAD

**Issue by thomas-mc-work** [borgbackup/borg#5742]
How is `scripts/shell_completions/bash/borg` being processed during setup? I couldn't find any reference of it in the `setup.py`. Also the path doesn't seem to follow any convention.

Thanks in advance!

**Comment by ThomasWaldmann** [comment]
Guess the answer is "not at all".

We just provide these files so you have them in case you want to use them.
If you want completions, you need to follow the docs of your shell completion mechanism about how to install such files.

Also, a borg dist package maintainer could pick those files and put them into correct place (or make separate packages of these, if preferred).

**Comment by thomas-mc-work** [comment]
Thank you for your reply! You're right: I just saw that I've installed it from an deb package and not via pip.
