### ISSUE TITLE
[Issue/Improvement] "Borg list" or "borg info" without write permission rights

### ISSUE THREAD

**Issue by 99rgosse** [borgbackup/borg#5746]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE/IMPROVEMENT

#### Your borg version (borg -V).
borg 1.1.15

#### Operating system (distribution) and version.
ubuntu 18.04.5 LTS

#### Hardware / network configuration, and filesystems used.
2 local servers on EXT4 + shared CIFS

#### How much data is handled by borg?
2 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg list --short /mnt/backup/lastbackup

## Describe the problem you're observing.
I want to ensure that my backup made from server1 and written on my share /mnt/backup/lastbackup are accessible from server 2.
Only Server1 can backup, Server2 can only check the backups (no write permission, only read)
My goal is not to give permissions for server2 (avoiding mistakes) but just ensuring everything is right.
some other commands shouldn't need write permission too:
borg list
borg info
borg extract (provided you don't try to extract where the repository is)
borg mount/unmount (same than extract)

#### Include any warning/errors/backtraces from the system logs

Failed to create/acquire the lock /mnt/backup/lastbackup/lock.exclusive ([Errno 30] Read-only file system: '/mnt/backup/lastbackup/lock.exclusive').
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 162, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 421, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait, kill_stale_locks=hostname_is_unique()).acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 353, in acquire
    with self._lock:
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 114, in __enter__
    return self.acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 138, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /mnt/backup/lastbackup/lock.exclusive ([Errno 30] Read-only file system: '/mnt/backup/lastbackup/lock.exclusive').

Platform: Linux ch03testrdteam 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:46:27 UTC 2021 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.15  Python: CPython 3.6.9 msgpack: 0.5.6
PID: 6471  CWD: /home/ch03deploysys.argv: ['/usr/bin/borg', 'list', '--short', '/mnt/backup/lastbackup']
SSH_ORIGINAL_COMMAND: None

**Comment by 99rgosse** [comment]
If someone think this is relevant, I can try to make this work without write permission...

**Comment by ThomasWaldmann** [comment]
Some releases ago, a feature was added to operate on read-only media to do operations without lock.

Check the change log, please.

**Comment by 99rgosse** [comment]
> Some releases ago, a feature was added to operate on read-only media to do operations without lock.
> 
> Check the change log, please.

Ooooh cool, thank you, that was **"--bypass-lock"** ... and this was even in the docs 🤦 (well, I was sure to read them... maybe on old version...) Sorry for disturbing !
