### ISSUE TITLE
"Completely healed previously damaged file!" message doesn't go away. Should I be concerned?

### ISSUE THREAD

**Issue by chaghi** [borgbackup/borg#5747]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Server:

* Borg version: `borg 1.1.16`
* OS: `OSMC 2020.11-1 (4.19.122-2-osmc #1 SMP PREEMPT Sat Jul 4 02:39:56 UTC 2020 armv7l GNU/Linux)`
* Hardware / filesystem: `Raspberry Pi 3 Model B Rev 1.2` / `ext4`

#### Client: 

* Borg version: `borg 1.1.16`
* OS: `Ubuntu 20.10 (5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 GNU/Linux)`
* Hardware / filesystem: `Lenovo ThinkPad T470s` / `ext4`

#### How much data is handled by borg?

```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               12.95 GB              9.70 GB             77.00 MB
All archives:              251.98 GB            188.20 GB             11.33 GB

                       Unique chunks         Total chunks
Chunk index:                  115332              1860796
------------------------------------------------------------------------------
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg check -v raspi:/media/Elements/Backup/borg-repos/laptop`

## Describe the problem you're observing.

I've been doing a local backup of my laptop to a USB pendrive using borg for several years now, without problems. A few months ago, the pendrive broke, and several of the backups got corrupted with missing chunks.

Fortunately, the corruption was on non-critical data, and on a file which was easily recovered (a DLL from a Wine distribution I haven't been using in ages anyway). I was able to recover the missing chunks with a `borg check --repair`. I also moved the borg repository to a proper disk attached to a Raspberry Pi.

The  thing is, ever since this happened, every time I do a `borg check`, I always get a couple of messages on each affected snapshot:

* "Healed previously missing file chunk! (Byte 1788429-6225942)"
* "Completely healed previously damaged file!"

(see below)

Is this normal? Why if borg was able to recover the missing file chunk, I still get the message/warning every time? Should I be worried? If this is normal, is there anything I can do to permanently discard those messages? I find them confusing, as they seem to imply there's something wrong, when apparently there isn't.

I'll greatly appreciate any thoughts about this particular scenario.

```
Remote: Starting repository check
Remote: Starting repository index check
Remote: Index object count match.
Remote: Completed repository check, no problems found.
Starting archive consistency check...
Analyzing archive laptop-guest-2017-11-28T19:52:34 (1/19)
laptop-guest-2017-11-28T19:52:34: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Healed previously missing file chunk! (Byte 1788429-6225942).
laptop-guest-2017-11-28T19:52:34: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Completely healed previously damaged file!
Analyzing archive laptop-guest-2018-12-22T19:17:49 (2/19)
laptop-guest-2018-12-22T19:17:49: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Healed previously missing file chunk! (Byte 1788429-6225942).
laptop-guest-2018-12-22T19:17:49: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Completely healed previously damaged file!
Analyzing archive laptop-guest-2019-11-02T10:59:38 (3/19)
laptop-guest-2019-11-02T10:59:38: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Healed previously missing file chunk! (Byte 1788429-6225942).
laptop-guest-2019-11-02T10:59:38: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Completely healed previously damaged file!
Analyzing archive laptop-guest-2020-01-04T11:40:50 (4/19)
laptop-guest-2020-01-04T11:40:50: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Healed previously missing file chunk! (Byte 1788429-6225942).
laptop-guest-2020-01-04T11:40:50: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Completely healed previously damaged file!
Analyzing archive laptop-guest-2020-03-11T19:58:31 (5/19)
laptop-guest-2020-03-11T19:58:31: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Healed previously missing file chunk! (Byte 1788429-6225942).
laptop-guest-2020-03-11T19:58:31: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Completely healed previously damaged file!
Analyzing archive laptop-guest-2020-08-04T20:22:31 (6/19)
laptop-guest-2020-08-04T20:22:31: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Healed previously missing file chunk! (Byte 1788429-6225942).
laptop-guest-2020-08-04T20:22:31: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Completely healed previously damaged file!
Analyzing archive laptop-guest-2020-11-08T18:54:16 (7/19)
laptop-guest-2020-11-08T18:54:16: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Healed previously missing file chunk! (Byte 1788429-6225942).
laptop-guest-2020-11-08T18:54:16: home/guest/.wine-pipelight/drive_c/Program Files/Silverlight/5.1.30214.0/mscorlib.ni.dll: Completely healed previously damaged file!
Analyzing archive laptop-guest-2020-12-30T14:59:03 (8/19)
Analyzing archive laptop-guest-2021-01-23T10:09:02 (9/19)
Analyzing archive laptop-guest-2021-01-31T18:47:36 (10/19)
Analyzing archive laptop-guest-2021-02-05T20:15:23 (11/19)
Analyzing archive laptop-guest-2021-02-11T21:06:12 (12/19)
Analyzing archive laptop-guest-2021-02-17T22:59:24 (13/19)
Analyzing archive laptop-guest-2021-02-21T20:51:58 (14/19)
Analyzing archive laptop-guest-2021-02-28T22:07:07 (15/19)
Analyzing archive laptop-guest-2021-03-06T10:44:02 (16/19)
Analyzing archive laptop-guest-2021-03-13T09:35:34 (17/19)
Analyzing archive laptop-guest-2021-03-21T21:14:07 (18/19)
Analyzing archive laptop-guest-2021-03-27T11:59:16 (19/19)
Archive consistency check complete, no problems found.
```

**Comment by ThomasWaldmann** [comment]
If one wants `borg check` to not only check, but also repair, one has to invoke `borg check --repair`.

**Comment by chaghi** [comment]
I understand that, and I did a `borg check --repair` when I discovered the corruption. Does this mean that the first repair wasn't enough, and I should run it or or more times until no further problems are found?

I'll try that, but I still think the output is confusing, as it is telling that it has fixed something (and it hasn't, it's just checking), and `borg check` finishes with an "Archive consistency check complete, no problems found." when there are indeed a number of unresolved corruptions.

**Comment by ThomasWaldmann** [comment]
the first repair might have discovered that some chunks are missing and replaced missing chunks with all-zero chunks.
also it made sure that chunks / repo index are valid.
so, basically the first repair produced files that are **known** to be "in need of repair".

the next `borg create` after that likely uploaded missing chunks to the repo, because the same file was still in the input data set and produced the same chunk that got lost in the repo. that is the case if you're lucky.

the next `borg check --repair`` then will notice that a file that currently has all-zero replacement chunks can be repaired, because the missing chunk is present in the repo now. that's the **healing**.

**Comment by chaghi** [comment]
Thank you very much for the explanation Thomas! It makes sense... although I stand by my comment that the output of `borg check` (whithout `--repair`) could be less ambiguous, somehow.

I run a `borg check --repair` again after your first comment, and I've just finished running a regular `borg check -v` without warnings. So the second `--reapair` did the trick.

Thanks for your help!
