### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by pkol** [borgbackup/borg#5749]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

1.1.16

#### Operating system (distribution) and version.

Ubuntu 20.04.1 LTS

#### Hardware / network configuration, and filesystems used.

intel cpu, ext4

#### How much data is handled by borg?

500G

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg check /mnt/pkj2/lew2.borg/ --info

## Describe the problem you're observing.

It crash with following message:

Starting repository check
Local Exception
Traceback (most recent call last):
  File "/home/backup_lew/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 4690, in main
    exit_code = archiver.run(args)
  File "/home/backup_lew/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 4622, in run
    return set_ec(func(args))
  File "/home/backup_lew/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/backup_lew/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 343, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/home/backup_lew/borg-env/lib/python3.8/site-packages/borg/repository.py", line 979, in check
    objects = list(self.io.iter_objects(segment))
  File "/home/backup_lew/borg-env/lib/python3.8/site-packages/borg/repository.py", line 1435, in iter_objects
    size, tag, key, data = self._read(fd, self.header_fmt, header, segment, offset,
  File "/home/backup_lew/borg-env/lib/python3.8/site-packages/borg/repository.py", line 1527, in _read
    data = fd.read(length)
OSError: [Errno 5] Input/output error

Platform: Linux puszczyk 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64
Linux: Unknown Linux
Borg: 1.1.16  Python: CPython 3.8.5 msgpack: 0.5.6.+borg1
PID: 3049452  CWD: /home/backup_lew
sys.argv: ['/home/backup_lew/borg-env/bin/borg', 'check', '/mnt/pkj2/lew2.borg/', '--info']
SSH_ORIGINAL_COMMAND: None

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

It happens every time for this repo.

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/issues/4087#issuecomment-424372781

**Comment by pkol** [comment]
fsck.ext4 shows no issues with this filesystem. Whole HDD is used only for borg repo. 

Is it possible to print filename which id problematic for borg?

**Comment by infectormp** [comment]
Try to check [SMART](https://borgbackup.readthedocs.io/en/stable/faq.html#i-get-an-integrityerror-or-similar-what-now)

**Comment by ThomasWaldmann** [comment]
`borg check --debug ...` will output the segment file name.

as @infectormp already pointed out, this is an issue below borg. hardware, kernel / filesystem, something is broken there.

**Comment by ThomasWaldmann** [comment]
Guess this is solved.
