### ISSUE TITLE
Add option to skip if running on battery

### ISSUE THREAD

**Issue by cd2357** [borgbackup/borg#5750]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question / feature request

## Describe the problem you're observing.

Please add an optional flag like `--skipIfRunnnigOnBattery=true` or similar.

The goal behind it is to tell `borg` to skip backup runs if the machine currently runs on battery power, because this can be very taxing on the battery.

This option is especially useful for people who setup a `borg` cron job on their laptops.

**Comment by ThomasWaldmann** [comment]
This is something that is very specific to the operating system and usually not portable, so it is better suited to be solved inside your script that just calls borg. Or in your OS, that calls the script (or not).
