### ISSUE TITLE
--adedupe to delete older archives with same content

### ISSUE THREAD

**Issue by Connor22** [borgbackup/borg#5757]
# What?

A flag to the `borg create` command that would delete backups that contain exactly the same data. Pattern/regex can be passed to the flag to narrow the search.

# Why?

Keep the list of archives in a repo cleaner, especially when dealing with automated backups.

# How?

Simple example would be to have `borg diff` run against each archive (that matches the pattern/regex if passed), and delete any which do not output diff'd files.

# Example Usage

```sh
#!/bin/bash
# # # # 
# Backs up every directory in the current directory into its own archive
# # # #

REPO='/mnt/borg'

for FILE in $(ls)
do 
    if [[ -d $FILE ]]
    then
        NAME=${basename "$FILE"}
        borg create --compression auto,zstd,3 --adedupe "$NAME-.\*" "$REPO"::$NAME-{now:%Y-%m-%d}
    fi
done
```

Which would delete any previous archives matching `$NAME-.*` that have absolutely no changes compared to the created archive.

**Comment by ThomasWaldmann** [comment]
This would make `borg create` a lot more complex in what it does and likely also a lot slower.

Effects:
- less archives (only have what is actually different)
- less archive-count related storage needs (esp. client-side `chunks.archives.d/` cache)
- but: basically **no** space saving in repo (mostly duplicate archives don't need much space)

The lower archive count (and its effects) is usually achieved by just having an appropriate `prune` policy:
- keep many recent archives
- keep medium amount of medium aged archives
- keep few old archives
