### ISSUE TITLE
replacing Hashindex with memory mapped TrieOfhash

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [borgbackup/borg#5758]
followup to #5756 with a "better" plan

this is a unstructured write-down to capture the idea for later implementation

A Trie is a prefix tree,
typically used for membership testsof different lenght,

however in borg we can use them for fixed depth with a different layout

```c

struct TrieHeader {
   union {
       uint32 parent_idx;
       uint32 next_free_idx; // used for a free list, item 0 has  the free list and 
    };

Struct FreeListEntry {
  
  TrieHeader hdr;
  uint32 size;
}

struct ChunkEntry {
  uint32 age; uint32 size; uint32 csize;
}

struct LookupTrie {
  TrieHeader hdr;
  uint32 next_items[16];
};

Struct ChunkMetadataTie {
 # allocates 3 blocks
  # in lining those may be bad, out of band mechanism is possible
   TrieHeader hdr;
   Chunkentry entries[16]:

struct FileCacheTrie {
  # either dynamic allocation or a better trick, needs to be determined
   FileData
   uint32 chunkindexes[...] # indexes of the chunk entries in the chunk trie
}

```

 all 32 bit integers will be network byteorder

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt It's a bit unclear to me whether this would have any advantages compared to what I implemented in borghash and borg master branch recently:

- chunk index: master uses a small wrapper around `borghash.HashTableNT` (which efficiently stores a mapping from chunkid256 to (flags32, size32). it's in cython and uses a key/value array that stores the keys/values serialized as bytes without any overhead (except that it does not free space of deleted entries in the kv array to guarantee stable indexes).
- files cache: master has a `compress` / `uncompress` method, which does NOT use a conventional compression algorithm, but:
  - for the entry's chunks list, it replaces the (chunkid256, size32) tuples by a index32 into the ChunkIndex key/value array, where the chunkid and size is stored.
  - msgpacks the whole files cache entry to reduce it to a single bytes object

**Comment by RonnyPfannschmidt** [comment]
I need to familiarize with the new structures first 


At the time of writing, this was targeting to be a enhancements over the storages from back then 

The new stuff is rather different, and I need to reevaluate

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borghash

https://github.com/borgbackup/borg/blob/master/src/borg/hashindex.pyx

https://github.com/borgbackup/borg/blob/master/src/borg/cache.py#L386

**Comment by ThomasWaldmann** [comment]
Closing this for now, reopen if needed.
