### ISSUE TITLE
BORG_SECURITY_DIR should be in XDG_HOME_DATA, not XDG_HOME_CONFIG

### ISSUE THREAD

**Issue by jdorel** [borgbackup/borg#5760]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

borg 1.1.16

#### Operating system (distribution) and version.

Linux 5.11.13-arch1-1

## Describe the problem you're observing.

Currently, BORG_SECURITY_DIR defaults to BORG_CONFIG_DIR/security. However, this is data that often changes, and not related to borg configuration made by the user. It should be moved to XDG_DATA_HOME so that versionning and backup of $XDG_CONFIG_HOME isn't cluttered by those changes ?

**Comment by ThomasWaldmann** [comment]
Guess the idea of the current behaviour was like:
- we have CACHE and people should be able to kill that without losing anything important
- everything important that shouldn't get lost is in CONFIG

**Comment by ThomasWaldmann** [comment]
borg2 release would be a good opportunity to change this, but this gets complicated by borg2 needing to be able to read borg 1.x repos (for `borg transfer`).

**Comment by ThomasWaldmann** [comment]
Hmm, we also have the borg keys directory inside the config dir - but guess that's not a problem because the keys don't change frequently.

**Comment by ThomasWaldmann** [comment]
@jdorel have a look. what do you think about the keys location?
