### ISSUE TITLE
Borg CRITICAL [Errno 2] No such file or directory: 'borg': 'borg'

### ISSUE THREAD

**Issue by Naweap** [borgbackup/borg#5779]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V) :
borg 1.1.16

#### Operating system (distribution) and version :
Linux raspberrypi4 5.10.17-v7l+ 

#### How much data is handled by borg?
Around 300 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords) :
/home/borg/.local/bin/borgmatic -c /etc/borgmatic/gitea_primary.config.yaml

## Describe the problem you're observing.

Hi guys, I'm running borg and it works well.

It's only been a few days since I'm facing an issue. I'm not sure if it's related to borg, borgmatic or something else but I will try to explain.

I'm using a systemd service in order to run backups. The service file looks like the following :

```
[Unit]
Description=Borgmatic gitea primary
After=network.target
Wants=network-online.target
[Service]
Restart=no
Type=exec
ExecStart=/home/borg/.local/bin/borgmatic -c /etc/borgmatic/gitea_primary.config.yaml
User=borg
Group=borg
Environment='BORG_PASSCOMMAND=cat /home/borg/.borg-passphrase'
[Install]
```

As you can see I'm running the ExecStart command with a user named borg. When I run this service, I get the following error :

```
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL /etc/borgmatic/gitea_primary.config.yaml: Error running configuration file
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL summary:
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL /etc/borgmatic/gitea_primary.config.yaml: Error running configuration file
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL /mnt/gitea_primary/backups: Error running actions for repository
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL [Errno 2] No such file or directory: 'borg': 'borg'
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL
avr 21 01:00:14 raspberrypi4 borgmatic[29905]: CRITICAL Need some help? https://torsion.org/borgmatic/#issues

```

But when I'm logging manually with the borg user and running the command placed in the ExecStart, the backup runs successfully.

I don't know where this error could come from. I found similar issues already but no one is related with mine.

Does someone has an idea of where the issue could come from ?

Thanks in advance.

**Comment by infectormp** [comment]
I think you need to submit issue to [borgmatic](https://projects.torsion.org/witten/borgmatic/issues) tracker. This is bot a borg issue.

**Comment by ThomasWaldmann** [comment]
The error msg comes from borgmatic and the issue seems to be that it can't find borg.

So maybe the PATH of that process does not contain the directory where `borg` is located.

**Comment by Naweap** [comment]
Answered at : [](https://projects.torsion.org/witten/borgmatic/issues/412#issuecomment-3391)
