### ISSUE TITLE
Cannot allocate memory on borg create

### ISSUE THREAD

**Issue by danielfomin96** [borgbackup/borg#5784]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg 1.1.16
#### Operating system (distribution) and version.
Ubuntu 20.04
#### Hardware / network configuration, and filesystems used.
IntelNuc Server with 2x 8GB RAM. Backup stored on SMB filesystem connected over powerline. Filesystem is ext4.
#### How much data is handled by borg?
Archives range from 40GB to 800GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg create \
      --compression auto,lzma \
      -v \
      --exclude-caches                \
      -x \
      --stats                                  \
        --one-file-system \
    ::`date --iso-8601=hours` \
    /
```

## Describe the problem you're observing.
I get a cannot allocate memory message when creating a backup of my filesystem.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
The problem occurs regularly but without me knowing what the cause is. The problem happens about every two days with my four backup scripts.
`htop`/ `sar`/ `vmstat` analysis while error occurs shows no problems with memory.

#### Include any warning/errors/backtraces from the system logs
```
Local Exception
Traceback (most recent call last):
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 4690, in main
    exit_code = archiver.run(args)
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 4622, in run
    return set_ec(func(args))
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 595, in do_create
    create_inner(archive, cache)
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/archiver.py", line 560, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/archive.py", line 530, in save
    self.repository.commit()
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/repository.py", line 475, in commit
    self.compact_segments()
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/repository.py", line 839, in compact_segments
    complete_xfer(intermediate=False)
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/repository.py", line 728, in complete_xfer
    segment = self.io.write_commit(intermediate=intermediate)
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/repository.py", line 1583, in write_commit
    self.close_segment()
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/repository.py", line 1391, in close_segment
    fd.close()
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/platform/base.py", line 136, in close
    self.sync()
  File "/home/daniel/borg-env/lib/python3.8/site-packages/borg/platform/base.py", line 125, in sync
    platform.fdatasync(self.fileno)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by ThomasWaldmann** [comment]
Can you check with `atop`? That's quite nice and stuff will show in red if there is a suspected problem.

Also, can you try to reproduce without smbfs / cifs, so we can see whether it is a borg issue or a smbfs/cifs issue?

BTW:
- `-x` and `--one-file-system` are the same functionality, so better remove the `-x`
- lzma is rather heavy one the cpu, maybe you want to try zstd instead?
- try the `{now}` placeholder, then you do not need to call `date`

**Comment by ThomasWaldmann** [comment]
Also, what's your local fs?

**Comment by danielfomin96** [comment]
I have added ext4 to my first post

**Comment by danielfomin96** [comment]
[https://imgur.com/mX2L8LI](https://imgur.com/mX2L8LI) has the atop output where at the 8 sec mark the command failed with the mentioned error

**Comment by danielfomin96** [comment]
I have 16GB swap and it is never used more than 4-5GB. `vm.overcommit_memory` is set to 0 which should maximally reduce such problems, as I understand it (I had it set to 1 for some days not knowing what it does but changed it back when debugging this problem, without it fixing anything)

**Comment by ThomasWaldmann** [comment]
You should get `vmcom < vmlim`.

**Comment by danielfomin96** [comment]
I have now while running `borg create` commands those values: `vmcom  30.4G | vmlim  23.8G`. Just to make sure, when I increase my swap by 10GB, my problem will probably be gone?

**Comment by danielfomin96** [comment]
Even increasing the swap size did not help

**Comment by ThomasWaldmann** [comment]
Did you see your vmcom staying below vmlim after that?

**Comment by danielfomin96** [comment]
I have it now set up in a way that I have multiple GB more vmlim than vmcom even when running `borg`. I am also in the process of testing `borg` without cifs but with a HDD. Until now I had no errors. Maybe cifs is the problem. But this would be strange to me, as it worked for some years now with the same setup

**Comment by danielfomin96** [comment]
After some tests using a HDD as backup destination as well as using ssh instead of SMB/CIFS, I assume that the error occurred because of SMB as I could not replicate the error otherwise.

Thank you for your help
