### ISSUE TITLE
Better log files

### ISSUE THREAD

**Issue by pguth** [borgbackup/borg#58]
Determine success state and have it in the log file for easy readout (see borgbackup/borgweb/issues/35).

**Comment by ThomasWaldmann** [comment]
See also: https://github.com/jborg/attic/issues/50

**Comment by ThomasWaldmann** [comment]
It's a pity, but because this is a rather global change and there is a lot of unmerged code in experimental branch, I think we have to do that later.

**Comment by ThomasWaldmann** [comment]
improved a little by: https://github.com/borgbackup/borg/commit/89db9b8b9ec77b3e8e73e2aa2df88edeb223a65c

now, if something bad happens (Exception, Error, Ctrl-C), always says "borg: Error: ..." on stderr and terminates with rc=1.
for success (rc=0), it currently does not output a text to follow "be quiet on success", especially NOT on stderr.

not sure if there should be a rc=0 message. and if so, where it should be.

**Comment by anarcat** [comment]
is this related to #302 and #314? or should this be simply another LoggingHandler?

i'm unclear as to what is necessary here...

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/58#issuecomment-113759160 maybe just that.

Log message could be like: INFO borg terminated %s with rc N

N=0 -> "successfully"
N=1 -> "normally, but with warnings"
N=2 -> "due to an error"
