### ISSUE TITLE
[1.2.0b3] borg info very slow

### ISSUE THREAD

**Issue by FabioPedretti** [borgbackup/borg#5804]
#### Your borg version (borg -V).
```
# ./borg-1.1.16 -V
borg-1.1.16 1.1.16

# ./borg-1.2.0b3 -V
borg-1.2.0b3 1.2.0b3
```

#### Operating system (distribution) and version.
Updated Debian 10.

#### Hardware / network configuration, and filesystems used.
VM with ext4 main FS, repo on remote sshfs.

#### How much data is handled by borg?
See output of borg info below.

## Describe the problem you're observing.
borg info with 1.2.0b3 is very slow (cannot finish after some minutes). 1.1.16 completes in 3seconds.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

No problem with 1.1.16:
```
# time ./borg-1.1.16 info /mnt/sshfs/borg-repo/
Repository ID: a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Location: /mnt/sshfs/borg-repo
Encrypted: Yes (repokey BLAKE2b)
Cache: /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Security dir: /root/.config/borg/security/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              591.28 TB            450.30 TB              2.30 TB

                       Unique chunks         Total chunks
Chunk index:                 5152794           1143984208

real	0m3,366s
user	0m1,828s
sys	0m0,742s
```

With 1.2.0b3 (I killed it after over 2 minutes):
```
# time ./borg-1.2.0b3 info /mnt/sshfs/borg-repo/
Repository ID: a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Location: /mnt/sshfs/borg-repo
Encrypted: Yes (repokey BLAKE2b)
Cache: /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Security dir: /root/.config/borg/security/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
^C^CKeyboard interrupt

real	2m36,123s
user	0m31,764s
sys	0m3,745s
```

While running the borg 1.2.0b3 info command, "top" output shows borg CPU usage, as well as ssh/sshfs CPU usage (the repo is on sshfs).
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                           
17608 root      20   0  971804 937936  12504 S  20,6  11,5   0:19.73 borg-1.2.0b3                                      
15527 root      20   0   19828  10240   5672 S   8,3   0,1  11:40.80 ssh                                               
15529 root      20   0  522012   6224    776 S   5,6   0,1  10:47.79 sshfs   
```                   
(issue splitted from #5673)

**Comment by ThomasWaldmann** [comment]
Can you do same without sshfs?

**Comment by FabioPedretti** [comment]
Do you mean copying the repo elsewhere?
Unfortunately no, my sshfs repo is over 2TB and the borg VM FS is tiny, just 16GB.

**Comment by FabioPedretti** [comment]
Output with --info and --debug.

1.1.16:
```
# time ./borg-1.1.16 info --info --debug /mnt/sshfs/borg-repo/
using builtin fallback logging configuration
35 self tests completed in 0.17 seconds
Verified integrity of /mnt/sshfs/borg-repo/index.111970
TAM-verified manifest
security: read previous location '/mnt/sshfs/borg-repo'
security: read manifest timestamp '2021-05-12T04:56:14.929514'
security: determined newest manifest timestamp as 2021-05-12T04:56:14.929514
security: repository checks ok, allowing access
Verified integrity of /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811/chunks
security: read previous location '/mnt/sshfs/borg-repo'
security: read manifest timestamp '2021-05-12T04:56:14.929514'
security: determined newest manifest timestamp as 2021-05-12T04:56:14.929514
security: repository checks ok, allowing access
Repository ID: a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Location: /mnt/sshfs/borg-repo
Encrypted: Yes (repokey BLAKE2b)
Cache: /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Security dir: /root/.config/borg/security/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              591.28 TB            450.30 TB              2.30 TB

                       Unique chunks         Total chunks
Chunk index:                 5152794           1143984208

real	0m3,847s
user	0m1,803s
sys	0m0,837s
```

1.2.0b3:
```
# time ./borg-1.2.0b3 info --info --debug /mnt/sshfs/borg-repo/
using builtin fallback logging configuration
38 self tests completed in 0.15 seconds
Verified integrity of /mnt/sshfs/borg-repo/index.111970
TAM-verified manifest
security: read previous location '/mnt/sshfs/borg-repo'
security: read manifest timestamp '2021-05-12T04:56:14.929514'
security: determined newest manifest timestamp as 2021-05-12T04:56:14.929514
security: repository checks ok, allowing access
Verified integrity of /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811/chunks
security: read previous location '/mnt/sshfs/borg-repo'
security: read manifest timestamp '2021-05-12T04:56:14.929514'
security: determined newest manifest timestamp as 2021-05-12T04:56:14.929514
security: repository checks ok, allowing access
Repository ID: a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Location: /mnt/sshfs/borg-repo
Encrypted: Yes (repokey BLAKE2b)
Cache: /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Security dir: /root/.config/borg/security/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
^C^C^CKeyboard interrupt
Traceback (most recent call last):
  File "borg/archiver.py", line 4839, in main
  File "borg/archiver.py", line 4770, in run
  File "borg/archiver.py", line 180, in wrapper
  File "borg/archiver.py", line 1432, in do_info
  File "borg/archiver.py", line 1514, in _info_repository
  File "borg/cache.py", line 412, in __str__
  File "borg/cache.py", line 439, in format_tuple
  File "borg/cache.py", line 431, in stats
  File "borg/archive.py", line 641, in calc_stats
  File "borg/repository.py", line 1179, in get_many
  File "borg/repository.py", line 1173, in get
  File "borg/repository.py", line 1544, in read
  File "borg/helpers/process.py", line 180, in handler
KeyboardInterrupt

Platform: Linux borg 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
Linux: Unknown Linux  
Borg: 1.2.0b3  Python: CPython 3.9.5 msgpack: 1.0.2 fuse: llfuse 1.4.1 [pyfuse3,llfuse]
PID: 17644  CWD: /root/binaries
sys.argv: ['./borg-1.2.0b3', 'info', '--info', '--debug', '/mnt/sshfs/borg-repo/']
SSH_ORIGINAL_COMMAND: None


real	0m58,418s
user	0m11,175s
sys	0m1,644s
```

**Comment by ThomasWaldmann** [comment]
One vague suspicion:

The way 1.1.x does statistics had some issues (sometimes showing unexpected values), so there were bigger changes in master branch (1.2). I remember adding some values to the archive header in master branch, so that the overall file count / size-sum etc. can be easily read from there. BUT, older borg did not put that info there, so in that case it has to fall back to a slower method.

Maybe try info on a single old (1.1) and new (1.2) archive.

**Comment by FabioPedretti** [comment]
I tried creating a new archive (350MB compressed, 700 files) with 1.1 and another one with 1.2, still on a sshfs FS.
Every borg info with either version on either repo takes a small and similar time (2,5s). Probably too small to see any eventual difference, but I cannot tests with bigger repo at the moment.

**Comment by FabioPedretti** [comment]
This issue was also later reported in #6259 and addressed by #6296: thanks for the fix!
Indeed, after having a first borg-1.2.0 running some hours, the file cache was created and the next runs are faster.
There are two remaining differences however, I don't know if they are expected. Feel free to close this issue, in this case:
- it is still over 3x slower that 1.1;
- the reported sizes are slightly different (likely the 1.1 is wrong?).

See the output below.

With 1.1.17:
```
# time ./borg-1.1.17 info
Repository ID: a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Location: /mnt/sshfs/borg-repo
Encrypted: Yes (repokey BLAKE2b)
Cache: /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Security dir: /root/.config/borg/security/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              662.60 TB            502.50 TB              2.46 TB

                       Unique chunks         Total chunks
Chunk index:                 5255499           1183178793

real	0m26,835s
user	0m2,231s
sys	0m1,492s
```
With 1.2.0:
```
# time ./borg-1.2.0 info
Repository ID: a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Location: /mnt/sshfs/borg-repo
Encrypted: Yes (repokey BLAKE2b)
Cache: /mnt/sshfs/borg-cache/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
Security dir: /root/.config/borg/security/a0a213e2d7c13a3d80933520b7298d9ddf27ac25c0fbbd9c55c62acce94f8811
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:              661.12 TB            502.36 TB              2.46 TB

                       Unique chunks         Total chunks
Chunk index:                 5255499           1183178793

real	1m43,685s
user	0m6,663s
sys	0m2,491s
```

**Comment by ThomasWaldmann** [comment]
Yes, the difference is likely due to the `--consider-part-files` related computations not being correct in 1.1.x.

How many archives are in that repo?

**Comment by FabioPedretti** [comment]
> Yes, the difference is likely due to the `--consider-part-files` related computations not being correct in 1.1.x.
> 
> How many archives are in that repo?

3088.

**Comment by ThomasWaldmann** [comment]
IIRC:
- old code: doing the "all archives" stats based on the local chunks index
- new code: doing "all archives" stats like `sum(size_from(archive) for archive in repo)` (similar to doing the "this archive" stats like `size_from(archive)`)

Obviously the 2nd method is slower if you have a lot or archives and/or a remote repo. Users with less-than-thousands of archives will notice a smaller effect than you did.

But the problem with the 1st method was just that it could give very wrong results if the part files made a big difference (== there were some checkpoints within big files, producing big .part files) and also there was no way to implement --consider-part-files.

**Comment by ThomasWaldmann** [comment]
BTW, one thing I had considered before adding the cache was to drop the "all archives" stats from some places:
- `borg create --stats repo::archive`
- `borg info repo::archive`

Both currently give the "all archives" stats although noone really asked for it.

What we could do is to only compute that, if someone is really specifically asking for it, like with:
- `borg info repo`

**Comment by ThomasWaldmann** [comment]
Does this still happen?

**Comment by FabioPedretti** [comment]
> Does this still happen?

The status is still the same of what I detailed in the later comment https://github.com/borgbackup/borg/issues/5804#issuecomment-1059935562: the first post issue is fixed, but 1.2.0 is still slower than 1.1.17.

**Comment by ThomasWaldmann** [comment]
OK, thanks for the info.

I'll close this, 3000 archives is quite a lot and thus some slowness is expected.

What we can do is to drop the "all archives" stats no one is asking for (when doing "borg info repo::archive"), that will save quite a bit. New ticket for that.

**Comment by FabioPedretti** [comment]
> OK, thanks for the info.
> 
> I'll close this, 3000 archives is quite a lot and thus some slowness is expected.
> 
> What we can do is to drop the "all archives" stats no one is asking for (when doing "borg info repo::archive"), that will save quite a bit. New ticket for that.

OK, for the record: #6638.
