### ISSUE TITLE
borg check --verify-data crashing

### ISSUE THREAD

**Issue by rsyring** [borgbackup/borg#5806]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.  Possibly related to #3225

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).

borg 1.1.16

#### Operating system (distribution) and version.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

#### Hardware / network configuration, and filesystems used.

WD Elements external drive, USB 3 connection

#### How much data is handled by borg?

The repo in question is 95G on disk according to `du`

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg check --verify-data /mnt/extborg2/nanex/borg-system`

## Describe the problem you're observing.

I can run a repository check without issue:

```
root@nanex:~# borg check /mnt/extborg2/nanex/borg-system
Enter passphrase for key /mnt/extborg2/nanex/borg-system: 
root@nanex:~#
```

But when checking with verify data, I get an exception after it runs for some time (10s of minutes):

```
root@nanex:~# borg check --verify-data /mnt/extborg2/nanex/borg-system
Enter passphrase for key /mnt/extborg2/nanex/borg-system: 
Exception ignored in: <function Repository.__del__ at 0x7fcb6f68d0e0>
Traceback (most recent call last):
  File "borg/repository.py", line 179, in __del__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 282, in modify
KeyError: (('nanex@79871138881880', 3701717, 0),)
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 177, in wrapper
  File "borg/archiver.py", line 350, in do_check
  File "borg/archive.py", line 1249, in check
  File "borg/archive.py", line 1639, in rebuild_refcounts
  File "borg/archive.py", line 268, in add
  File "borg/archive.py", line 285, in flush
  File "borg/archive.py", line 1440, in add_callback
  File "borg/crypto/key.py", line 370, in encrypt
  File "borg/crypto/nonces.py", line 72, in ensure_reservation
  File "borg/crypto/nonces.py", line 39, in get_repo_free_nonce
  File "borg/repository.py", line 336, in get_free_nonce
AssertionError: bug in code, exclusive lock should exist here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 4690, in main
  File "borg/archiver.py", line 4622, in run
  File "borg/archiver.py", line 177, in wrapper
  File "borg/repository.py", line 204, in __exit__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 282, in modify
KeyError: ('nanex@79871138881880', 3701717, 0)

Platform: Linux nanex 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
Linux: debian bullseye/sid 
Borg: 1.1.16  Python: CPython 3.7.9 msgpack: 0.5.6.+borg1
PID: 3701717  CWD: /root
sys.argv: ['borg', 'check', '--verify-data', '/mnt/extborg2/nanex/borg-system']
SSH_ORIGINAL_COMMAND: None
```
I might also get a different exception, same command:

```
root@nanex:~# borg check --verify-data /mnt/extborg2/nanex/borg-system
Exception ignored in: <function Repository.__del__ at 0x7f270a22f0e0>
Traceback (most recent call last):
  File "borg/repository.py", line 179, in __del__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 282, in modify
KeyError: (('nanex@79871138881880', 1281064, 0),)
Local Exception
Traceback (most recent call last):
  File "borg/repository.py", line 1376, in get_fd
  File "borg/lrucache.py", line 21, in __getitem__
KeyError: 14788

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 177, in wrapper
  File "borg/archiver.py", line 343, in do_check
  File "borg/repository.py", line 979, in check
  File "borg/repository.py", line 1424, in iter_objects
  File "borg/repository.py", line 1378, in get_fd
  File "borg/repository.py", line 1359, in open_fd
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/extborg2/nanex/borg-system/data/14/14788'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 4690, in main
  File "borg/archiver.py", line 4622, in run
  File "borg/archiver.py", line 177, in wrapper
  File "borg/repository.py", line 204, in __exit__
  File "borg/repository.py", line 460, in close
  File "borg/locking.py", line 383, in release
  File "borg/locking.py", line 282, in modify
KeyError: ('nanex@79871138881880', 1281064, 0)

Platform: Linux nanex 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
Linux: debian bullseye/sid 
Borg: 1.1.16  Python: CPython 3.7.9 msgpack: 0.5.6.+borg1
PID: 1281064  CWD: /root
sys.argv: ['borg', 'check', '--verify-data', '/mnt/extborg2/nanex/borg-system']
SSH_ORIGINAL_COMMAND: None
```

That directory is missing:

```
ls /mnt/extborg2/nanex/borg-system/data/14/1478*
/mnt/extborg2/nanex/borg-system/data/14/14780  /mnt/extborg2/nanex/borg-system/data/14/14783  /mnt/extborg2/nanex/borg-system/data/14/14789
/mnt/extborg2/nanex/borg-system/data/14/14781  /mnt/extborg2/nanex/borg-system/data/14/14785
/mnt/extborg2/nanex/borg-system/data/14/14782  /mnt/extborg2/nanex/borg-system/data/14/14787
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes.  Just run the command again.

I did run e2fsck on the unmounted file system.  No errors detected and didn't fix the problem.

#### Include any warning/errors/backtraces from the system logs

Included above.

**Comment by infectormp** [comment]
@rsyring try to check memory for errors

**Comment by ThomasWaldmann** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/extborg2/nanex/borg-system/data/14/14788'
```

That is the interesting line. Can you check - is the file really missing?

**Comment by ThomasWaldmann** [comment]
Can you try:
```
# borg check --repair --verify-data /mnt/extborg2/nanex/borg-system
```

**Comment by rsyring** [comment]
> @rsyring try to check memory for errors

I ran memtest on it and all is good.  Also, FWIW, I have been able to successfully verify other repos.

> As the directory is missing, the remaining question is just why borg check is crashing, it should not.

You may already know the answer to this question, but I also find it interesting that with the directory gone, sometimes that is part of the exception message and sometimes it is not.

> Can you try: `borg check --repair --verify-data /mnt/extborg2/nanex/borg-system`

Yes, I will and will report back.

Thanks to both of you for suggestions.

**Comment by ThomasWaldmann** [comment]
@rsyring did the `borg check --repair` already complete? Did it work?

**Comment by rsyring** [comment]
Sorry about not getting back to you all.  So, I ran the check with verify data (without repair) about four more times.  One of those runs resulted in similar exceptions.  But the others all ran successfully and since I wasn't able to reproduce anymore, there was no reason to run the repair.

I was using rsync to copy the repo to an external drive.  I've read the docs about why that's not a good idea, but I have some reasons why I wanted to do it that way.  I wasn't using `with-lock` initially before that copy operation, so it's possible rsync picked up the repo in an inconsistent state.  Not sure if that would affect things?  I did implement that now and maybe that fixed the repo?

I was never able to reproduce the error from this issue on the rsync source repo.  I ended up switching to a different external drive just in case it was a rare hardware issue.  I run repo checks once a month so here in a week or so I'll run everything again.

You are welcome to close this issue.  I don't think I'm going to have anything else helpful to report.  But I really appreciate your willingness to help.

**Comment by ThomasWaldmann** [comment]
guess rsync not having completely synced a consistent state could explain this.
so, sure, using with-lock is much safer. it also avoids multiple such rsyncs running at the same time.

ok, so guess you solved your specific issue with this.

otoh, there is still the issue that `borg check` should not crash, but make the best of whatever state a repo is in, so guess i keep this open until someone has looked at that.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/5806#issuecomment-841358643 < about that:

i had a look at the code:
- open_fd computes a filename based on the segment number
- the segment number is computed by the outer loop by io.segment_iterator() based on directories and files found **on disk**.

so, under normal circumstances, this exception never happens. guess rsync was running and not completed yet, maybe it renames dirs to a temp name while trying to sync them, causing a race condition in borg's code.

guess aborting is the best we can do in such a case.
