### ISSUE TITLE
Ui suggestion

### ISSUE THREAD

**Issue by bastiencyr** [borgbackup/borg#5807]
Hello, 
I checked the mainWindow ui file because I wanted to optimize the space at the bottom (on my screen, the window is to big the first time). There is a status bar and and it seems that noboy use it so I have removed it. I have also moved the cancel and backup buttons to a toolBar. 
This is the result :
![image](https://user-images.githubusercontent.com/63359575/118247637-b12b3580-b4a3-11eb-9c90-9a51e88b43a6.png)

It's just a suggestion but I think a toolBar is a good idea. It is more compact and beautiful (with icons). 
My "Backup" button on toolBar starts a backup and it works.

I have others suggestions like adding the misc tab in a setting action in toolBar (all ui is made for one profile, one backup but misc tab is about all profiles and backups,  its global settings), maybe move the profile menu elsewhere...

**Comment by RonnyPfannschmidt** [comment]
The vorta ui is a different project

**Comment by bastiencyr** [comment]
Oh really sorry I got the wrong git, I close the comment for vorta repo.
