### ISSUE TITLE
Change versioning schema

### ISSUE THREAD

**Issue by NotANormalNerd** [borgbackup/borg#581]
This article explains it very well and Bord especially should follow the version schema.
This way people and programs always know what happens and borg can move forwards.

https://medium.com/javascript-scene/software-versions-are-broken-3d2dc0da0783#.fta8yeoud

**Comment by ThomasWaldmann** [comment]
We already do semantic versioning. But perception of what "breaking" means differs.

**Comment by RonnyPfannschmidt** [comment]
actually this is the reason borg is in the `0.x.y` series :)
