### ISSUE TITLE
How to install binaries on Antix 17.4?

### ISSUE THREAD

**Issue by seanspotatobusiness** [borgbackup/borg#5812]
I have an old air-gapped machine with Antix 17.4 (which is based on Debian) installed. I would like to use BorgBackup but I can't find instructions on how to install anything that I can download and transfer on a USB drive.

The readme file that came inside the download does not include any instructions on how to install the program so that it is usable from the terminal.

Some places on the Internet say that in general binaries should be put in the /usr/local/bin folder, others the /opt folder. I tried following the instructions here https://asciinema.org/a/28691?autoplay=1&speed=2 and created a folder in my home directory called bin and put a folder in that called borg. I had to add a -r flag to the cp command or the system refused to copy the folders. After making the borg folder executable, I type "borg" at the terminal and get back "command not found". Are those instructions even compatible with what I downloaded? I tried the same instructions in the /opt folder but this also does not get the terminal to recognise the command "borg".

```
sean@antix1:~/Desktop/borgbackup-1.1.16/src
$ sudo mv ~/Desktop/borgbackup-1.1.16 /usr/local/bin/
[sudo] password for sean: 
sean@antix1:~/Desktop/borgbackup-1.1.16/src
$ borg
bash: borg: command not found
sean@antix1:~/Desktop/borgbackup-1.1.16/src
$ sudo mv /usr/local/bin/borgbackup-1.1.16 /opt
sean@antix1:~/Desktop/borgbackup-1.1.16/src
$ borg
bash: borg: command not found
sean@antix1:~/Desktop/borgbackup-1.1.16/src
$ cd /opt
sean@antix1:/opt
$ ls
borgbackup-1.1.16
sean@antix1:/opt
$ cp /opt/borgbackup-1.1.16 ~/bin/borg
cp: -r not specified; omitting directory '/opt/borgbackup-1.1.16'
sean@antix1:/opt
$ chmod +x ~/bin/borg
chmod: cannot access '/home/sean/bin/borg': No such file or directory
sean@antix1:/opt
$ cp -r /opt/borgbackup-1.1.16 ~/bin/borg
cp: cannot create directory '/home/sean/bin/borg': No such file or directory
sean@antix1:/opt
$ sudo cp -r /opt/borgbackup-1.1.16 ~/bin/borg
[sudo] password for sean: 
cp: cannot create directory '/home/sean/bin/borg': No such file or directory
sean@antix1:/opt
$ sudo cp /opt/borgbackup-1.1.16 /opt/borg
cp: -r not specified; omitting directory '/opt/borgbackup-1.1.16'
sean@antix1:/opt
$ sudo cp -r /opt/borgbackup-1.1.16 /opt/borg
sean@antix1:/opt
$ chmod +x /opt/borg
chmod: changing permissions of '/opt/borg': Operation not permitted
sean@antix1:/opt
$ sudo chmod +x /opt/borg
sean@antix1:/opt
$ borg
bash: borg: command not found
sean@antix1:/opt
$ mkdir ~/bin/borg
mkdir: cannot create directory ‘/home/sean/bin/borg’: No such file or directory
sean@antix1:/opt
$ mkdir ~/bin
sean@antix1:/opt
$ mkdir ~/bin/borg
sean@antix1:/opt
$ cp -r /opt/borgbackup-1.1.16 ~/bin/borg
sean@antix1:/opt
$ chmod +x ~/bin/borg
sean@antix1:/opt
$ borg
bash: borg: command not found
sean@antix1:/opt
$ borg init repo
bash: borg: command not found
sean@antix1:/opt
$ 
```

**Comment by ThomasWaldmann** [comment]
On Linux (and other posix OS), you can start command by giving a full absolute or relative path, even if the directory is not in the PATH search path, e.g.:
```
/root/bin/borg
./borg
```

So, in that case it doesn't matter where you put it.

More comfortable is when you put it into a directory that is in PATH env variable (see `echo $PATH` output).
Usually, for custom local stuff, one uses `/usr/local/bin`.

Also, you need to make the download executable, like `chmod +x borg`.

**Comment by ThomasWaldmann** [comment]
Also, it looks like you are trying to use the src, not a borg binary.

I guess in your case it would be easier to install a binary and just use that, the source code based install is more effort (and described in the docs).

See there for linux 64bit binaries: https://github.com/borgbackup/borg/releases

**Comment by ThomasWaldmann** [comment]
Guess that should solve this.
