### ISSUE TITLE
Check if archives were marked for deletion in append-only mode

### ISSUE THREAD

**Issue by niklassc7** [borgbackup/borg#5813]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

1.1.9

#### Operating system (distribution) and version.

Debian

## Question
When I use a repository in append-only mode, is there an easy way of checking if there are pending delete operations that were made in append-only mode before I run a write-command in non-append-only mode, so that I don't accidentally delete data?

## Describe the problem you're observing.

I created a repo in append-only mode

    borg init --append-only -e none myrepo
    borg create myrepo::archive0 somedata
    borg create myrepo::archive1 somedata # content of somedata-directory was changed before this command

And deleted a repository in append-only mode

     borg delete myrepo::archive1

I deactivated append-only mode and tried checking the integrity of the repo

     borg config myrepo append_only 0
     borg check --verify-data myrepo

Which finished without error or warning, however in `borg list`  the repository `archive1` was missing and how I understood it, the files would actually be deleted if I now ran any `prune` , `create` or `delete` command.
I was able to restore the archive by following https://borgbackup.readthedocs.io/en/stable/usage/notes.html#id3

I understand that as the `borg check --verify-data` is only to check if the repository was corrupted (some single files where deleted) and not if whole archives were marked for deletion in append-only mode.

Is there a way to check if archives were marked for deletion in append-only mode before I run a write-operation in non-append-only mode?

**Comment by ThomasWaldmann** [comment]
You can just list the repo, so you see what archives are still there.

If archives were deleted, you do not see them any more in the list.

There is no other easy way to see what was deleted. But if you see what is still there, you should be able to tell whether that is all you need.

**Comment by niklassc7** [comment]
Thanks for the quick answer!
