### ISSUE TITLE
irc channel: freenode -> libera

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5817]
### irc
seems like there was kind of a hostile takeover of freenode and everybody is moving to libera.chat now.

i personally did not investigate this much, but there are some details: https://anarc.at/blog/2021-05-24-leaving-freenode/

so i'ld suggest we just also move to libera.

### matrix
switching to a matrix channel would be also a good option, but would require a switch of clients, too.

i personally run `irssi` on a `screen`/`tmux` on a server (so the client is permanently connected to the chat network), is there something similar for matrix?

**Comment by ThomasWaldmann** [comment]
looks like quite some of us have been already on #borgbackup on libera.chat, hehe - and now i am, too.

i'll try to register the channel now, so we officially have it.

**Comment by RonnyPfannschmidt** [comment]
@ThomasWaldmann personally i use matrix with a irc bridge already, matrix has persistent history so an own always on client is not required, i just use a desktop and a mobile client

i'd love to see borg set up as bridged channel sometime in future, but as far as i can tell you are the major doer, so you get to pick what works best for you :)

**Comment by l29ah** [comment]
I don't like the Matrix option, as the XMPP gateway for it lacks history fetching, unlike biboumi (a gateway for IRC) that works as a bouncer.

**Comment by ThomasWaldmann** [comment]
thanks for the hints!

i sent the registration email now, let's see when it gets processed. guess they have a lot of work right now.

**Comment by elho** [comment]
IRC is one thing, Matrix some other. Just like there's the mailing list and that github Discussions thing. None is a substitute for the other, they are different types of communication with different culture associated to them.
The IRC side of things (which I, personally will stick to) has a need to officially (updating pointers in the docs) move to something free right now.

**Comment by elho** [comment]
> i'd love to see borg set up as bridged channel sometime in future, but as far as i can tell you are the major doer, so you get to pick what works best for you :)

I'd assume that to automatically happen once Libera gets a Matrix bridge.  OFTC for instance does have one, so projects that moved there instead already have a bunch of Matrix users in their channels.

**Comment by d7415** [comment]
> > i'd love to see borg set up as bridged channel sometime in future, but as far as i can tell you are the major doer, so you get to pick what works best for you :)
> 
> I'd assume that to automatically happen once Libera gets a Matrix bridge. OFTC for instance does have one, so projects that moved there instead already have a bunch of Matrix users in their channels.

It's in progress matrix-org/matrix-appservice-irc#1324

**Comment by ThomasWaldmann** [comment]
as far as irc is concerned, guess we are done here. see you on libera chat!
