### ISSUE TITLE
borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']

### ISSUE THREAD

**Issue by marozsas** [borgbackup/borg#5819]
The title says all.
I am running openSuse Tumbleweed and looks like llfuse is obsolete/unmainted.
I hope someone can fix somehow, as the mount feature is great to browse the backups and picking a specific file.

`kimera:~ # rpm -qa | grep -iE "fuse|borg"

python39-fuse-1.0.0-1.4.x86_64
kio-fuse-5.0.1-1.2.x86_64
libfuse3-3-3.10.3-1.1.x86_64
enblend-enfuse-4.2-6.1.x86_64
fuse3-3.10.3-1.1.x86_64
borgbackup-1.1.16-2.1.x86_64
borgbackup-doc-1.1.16-2.1.x86_64
libfuse2-2.9.9-4.3.x86_64
python38-fuse-1.0.0-1.4.x86_64
fuse-2.9.9-4.3.x86_64
borgmatic-1.5.13-1.1.noarch
python39-pyfuse3-3.2.0-2.1.x86_64
python38-defusedxml-0.7.1-2.1.noarch
borgbackup-bash-completion-1.1.16-2.1.noarch
gvfs-fuse-1.48.1-1.1.x86_64
python38-pyfuse3-3.2.0-2.1.x86_64
`

**Comment by ThomasWaldmann** [comment]
This needs to be fixed by SuSE package maintainer. For borg 1.1.x, `borg mount` requires `llfuse`.

**Comment by marozsas** [comment]
borgbackup-1.2.4-1.1.x86_64 and python310-pyfuse3-3.2.2-1.3.x86_64 was release already  and borg mount it is working again on TW 20230331.
Thank you.
