### ISSUE TITLE
Filter list action

### ISSUE THREAD

**Issue by LeonB** [borgbackup/borg#582]
It would be nice if `borg list` with an archive as positional parameter would also support some kind filtering support. Maybe something like #361 but for the list action.

My use case: I have some kind of webbased dashboard checking if the borg backups includes a mysql dump located in /var/backups/mysql/. I now do `borg list /media/backups/borg/myserver::2016-01-19 | grep "var/backups/mysql"` but it takes a while to run that command.

**Comment by ThomasWaldmann** [comment]
The --filter only filters the status char borg create emits.

For borg list, there is no status char, so you maybe rather need to pipe through grep to search for filenames.
