### ISSUE TITLE
Question:  What determines number of ssh connections and how can I adjust this ?

### ISSUE THREAD

**Issue by buforded** [borgbackup/borg#5824]
When I use borg backup to back up a SOURCE dataset to an ssh endpoint, a certain number of ssh connections are initiated.

Unlike rsync, which (if uninterrupted) can backup the entire SOURCE dataset with one, single ssh connection, borg creates multiple connections, one after another.  The larger the SOURCE dataset, the more ssh connections are created.

I have three questions:

- what is the default number of ssh connections created and is it a function of size or number of files or ... ?
- How can I adjust this (my goal is to REDUCE the number of connections made) ?
- If I have an EXISTING remote repository, can I make this adjustment (to REDUCE number of connections made) on the source (client) without re-uploading my dataset ?  Or do I need to re-upload the repository when this adjustment is made ?

Thank you very much.

**Comment by ThomasWaldmann** [comment]
Hmm, I would assume there is one ssh connection per borg command.

Precisely what borg commands did you execute and how many ssh connections did you see for each command?

**Comment by buforded** [comment]
Thank you very much.

So you are saying that borg is like rsync - you specify a source path and a single ssh connection is created to transfer that entire source regardless of how many files or how many gigabytes in size it is, etc. 

Correct ?

**Comment by RonnyPfannschmidt** [comment]
correct
