### ISSUE TITLE
Msg "creating archive at ..." does not expand placeholders in archive name

### ISSUE THREAD

**Issue by heapxor** [borgbackup/borg#5826]
hi,
running bananian OS (debian) i downloaded https://borg.bauerj.eu/bin/borg-1.1.16-armv6

executing backup using #!/bin/bash script 
...

 $REPOSITORY::'{hostname}'-'{now:%Y-%m-%d_%T}'                  \

...

Creating archive at "heap@10.0.1.1:/x/banana-repo::{hostname}-{now:%Y-%m-%d_%T}"

The hostname and time is not "resolved" and replaced accordingly.

Any idea why?

Python 2.7.9 (default, Sep 16 2019, 12:56:14)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 >>> import socket
 >>> socket.gethostname()
'bananapi'

file /usr/bin/borg: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3,
              for GNU/Linux 3.2.0, BuildID[sha1]=584855b7096ef005ebbc274ffd8b61b126a2d202, stripped

**Comment by heapxor** [comment]
once the script finished all looks fine: borg list
bananapi-2021-06-07_18:48:08

**Comment by ThomasWaldmann** [comment]
It's a cosmetic / usability bug.

While looking at it, I also found that if one uses the BORG_REPO env var, placeholders in the repo part do not get expanded at all.

In the code, there is also a bad naming issue: quite a lot of places use location.orig (which was meant to be the location as given by the user). But rather they should use the expanded version.

**Comment by ThomasWaldmann** [comment]
Fixed in 1.1-maint.
