### ISSUE TITLE
Can I wildcard multiple repos into a single borg command for efficiency ?

### ISSUE THREAD

**Issue by rsyncnet** [borgbackup/borg#5832]
I may have done something dumb ...

I had a big directory of subdirs and I iterated through them creating an individual borg repo, on the remote destination, for every single one.

It works just fine but a "single" backup spawns thousands of individual borg processes.

HOWEVER, every single repo has the same key and settings.

So, is there any way that I can run a single borg command for something like 'a*' and 'b*' so that I only run 26 total borg commands instead of 2000 ?

If they all had different keys and settings, of course that would not work - but since the command I run, and the options, and the keys are the same, is there a way to run a single borg command that groups some of them together ?

I just need to somehow run *far* fewer borg commands and I would love to not re-upload all of my data ...

EDIT - just to clarify:

If I am doing something like this:

borg aa ... dest ...
borg ab ... dest ...
borg ac ... dest ...
borg ad ... dest ...

... and they all use the same key and options individually ... then what will happen if I do this:

borg a* ... dest ...

Will borg run through a* one by one and upload each to the exact same destination as before, but with one command instead of four ?

Thank you.

**Comment by ThomasWaldmann** [comment]
borg always works with a single repo, so if you used some wrapper to initialize all these repos, you need to use a similar wrapper to backup to them / restore from them.

if you did N `borg init` calls to create all these N repos, they do **not** use the same key, but N different keys.

if you used the same passphrase for all of them, the different keys will be protected by same passphrase though (but it is possible to change the passphrase).

about running multiple borg in parallel: you can do this as long as you have enough resources (CPU, RAM, I/O).

it is hard to say where the optimum concurrency for optimum speed would be without running out of resources, but some ideas would be:
- if C is your cpu core count, run about C .. 2*C borg processes
- be careful with memory consumption
- if you have hard disks, try to not cause more random accesses than needed (hdds are fast if read sequentially, but super slow with a lot of random rw head jumping around)
