### ISSUE TITLE
pip 8.x breaks python 3.2 compatibility

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#585]
as travis installs the latest pip into test envs, this currently breaks py32 test envs.

https://travis-ci.org/borgbackup/borg/jobs/103865631#L321

**Comment by ThomasWaldmann** [comment]
Still does not work after this:

https://github.com/borgbackup/borg/commit/69c8edc4e36195f3805c149fa576326ba525cbe5

https://travis-ci.org/borgbackup/borg/jobs/104184293

**Comment by BanzaiMan** [comment]
Something else is installing virutalenv 14.0.1. https://travis-ci.org/borgbackup/borg/jobs/104184293#L346

**Comment by ThomasWaldmann** [comment]
Ah, tox is the culprit. :)

OK, I added `virtualenv<14.0` to the requirements, let's see.

**Comment by ThomasWaldmann** [comment]
OK, this has solved it. Thanks @BanzaiMan!

It still errors, but that seems to be a problem on the OS X platform.
