### ISSUE TITLE
leading slash required for include/exclude matching of full paths

### ISSUE THREAD

**Issue by Alexander-Shukaev** [borgbackup/borg#5857]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

```
borg 1.1.16
```

#### Operating system (distribution) and version.

Arch Linux

#### Hardware / network configuration, and filesystems used.

EXT4

## Describe the problem you're observing.

I tried

```
sh:home/*/Projects/**/*.log
```

and it appears that this pattern does not match.  I suspect that it's because double asterisk (star) is only supported in the beginning of the pattern.  Is that true?  Is there any technical limitation that prevents them from being present anywhere?

**Comment by Alexander-Shukaev** [comment]
I figured this out.  It's an issue with documentation, maybe amend it whenever you have time.  Run

```bash
borg help patterns
```

and review this part:

```bash
Examples:

    # Exclude '/home/user/file.o' but not '/home/user/file.odt':
    $ borg create -e '*.o' backup /

    # Exclude '/home/user/junk' and '/home/user/subdir/junk' but
    # not '/home/user/importantjunk' or '/etc/junk':
    $ borg create -e '/home/*/junk' backup /

    # Exclude the contents of '/home/user/cache' but not the directory itself:
    $ borg create -e /home/user/cache/ backup /

    # The file '/home/user/cache/important' is *not* backed up:
    $ borg create -e /home/user/cache/ backup / /home/user/cache/important

    # The contents of directories in '/home' are not backed up when their name
    # ends in '.tmp'
    $ borg create --exclude 're:^/home/[^/]+\.tmp/' backup /

    # Load exclusions from file
    $ cat >exclude.txt <<EOF
    # Comment line
    /home/*/junk
    *.tmp
    fm:aa:something/*
    re:^home/[^/]\.tmp/
    sh:home/*/.thumbnails
     # Example with spaces, no need to escape as it is processed by borg
    some file with spaces.txt
    EOF
    $ borg create --exclude-from exclude.txt backup /
```

namely it should be (missing characters are highlighted with `^`):

```bash
    re:^/home/[^/]+\.tmp/
        ^         ^
    sh:/home/*/.thumbnails
       ^
```

**Comment by ThomasWaldmann** [comment]
Hmm, yeah guess that's wrong.

All the paths inside an archive have the leading `/` removed, but guess the matcher still sees it in the fs path.
