### ISSUE TITLE
Q: nonce file has been deleted by accident, are there any impacts ?

### ISSUE THREAD

**Issue by momiji** [borgbackup/borg#5858]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

$ borg -V
borg 1.1.11

#### Operating system (distribution) and version.

RHEL 7.9

## Describe the problem you're observing.

A nonce file in the borg backup folder has been deleted by accident, and I was wondering wether this can have impact on the backup already performed, or on the process of restoring the backup content.
If so, is there any solution apart from dropping all existant backup and start from scratch again?

I was not able to find anything about this file in the documentation, hence the question here in the issues.

Any help will be appreciated.

Regards,
momiji

**Comment by ThomasWaldmann** [comment]
can you give the full path of the file you deleted?

**Comment by momiji** [comment]
Hello,

The path of the nonce file is at the root of the backup folder. In the same folder I can see those files/folders:
- config
- data/
- hints.XXX
- index.XXX
- integrity.XXX
- README

Does it help ?

Regards,
momiji

**Comment by ThomasWaldmann** [comment]
> A nonce file in the borg backup folder has been deleted by accident, and I was wondering whether
> this can have impact on the backup already performed,

No.

> or on the process of restoring the backup content.

AFAIK no, but you should just try that. Testing your backups is always a good idea.

> If so, is there any solution apart from dropping all existant backup and start from scratch again?

The `nonce` file in the repo is the repo-side memory of the latest used (or reserved) nonce.
There is also a client-side memory of the nonce, in the security directory.

As long as either repo or client has a correct memory of the nonce, there should be no problem.

If you lose both, I guess you would run into the usual nonce-reuse security issue, which would make breaking the AES-CTR encryption possible.

If you just do another backup, does the nonce-file re-appear in the repo?
