### ISSUE TITLE
find_library() needs shell

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5870]
borg users are patching away the find_library call so that they don't need a shell in the chroot they use.

there should be a way to do this without patching borg source code.

maybe via a BORG_LIBC env variable?

**Comment by ThomasWaldmann** [comment]
related question about the fallback values:

What is the correct name of the libc on
- current freebsd? are older, still widely used freebsds different?
- current netbsd? are older, still widely used netbsds different?
- current macOS? are older, still widely used macOS different?
- on linux, it is libc.so.6 - always?

Current code: https://github.com/borgbackup/borg/blob/1.1.16/src/borg/xattr.py#L70

**Comment by bsiegert** [comment]
Whatever -lc selects is the libc. On OpenBSD for instance, it may be called libc.so.21.2 or similar. There is no one file name on BSD.

**Comment by ThomasWaldmann** [comment]
When trying to forward port this to master, I noticed that libc stuff there is handled by Cython, so we don't need the libc_name there.

So, fixed in 1.1-maint and not applicable in master, closing.
