### ISSUE TITLE
reduce startup time

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5871]
borg backup space providers may want to reduce startup time / cpu / I/O because they run a lot of borg processes in parallel.

`borg.selftest` runs some unit-tests to make sure some fundamental stuff is working ok.
at bigger sites, this could be just done at install / testing time and skipped in production.

skipping should be possible without modifying the borg source, maybe via a BORG_SKIP_SELFTESTS env variable.

**Comment by m3nu** [comment]
Never thought about this, but could be useful. Since many connections I see are very short-lived.
