### ISSUE TITLE
Concept Question

### ISSUE THREAD

**Issue by dcbo** [borgbackup/borg#5879]
# This a QUESTION

## My Setup
Currently I am Backing Up my SMB-Share and some RaspberryPi with an self written Shell-Script.
This is done in Pull-Mode, as I can trust my Backup Server. 
The Server is switched on once a day, the Backups are carried out and the Server shuts down.
The Server hat full read access to my SMB and the right to run rsync as root on all raspberrys.

### My Threat Modell
In my opinion the major threat (beside Hard-Drive defect) is an crypto trojan.

### My Current Solution
My Backup script does incremental Backups and in case of a Crypto Trojan it would backup more Data than usual.
After the Backup my script reports the successful Backup to my (Nagios) Monitoring-Server 
If a threshold of changed Files/Data is exceeded I will be informed.

## My Question
Is it possible to monitor Borg-Backup to detect a crypto Trojan:

### Pull Mode
The Backup-Server should read the Statistics of the Last Backup 
- Number of Files Changed since last backup, 
- Bytes transferred during Backup Job, 
- Size the incremental Backup is consuming on Server

and report them to a Monitoring System (or vial email)

### Push Mode
The Backup-Server (as this is the only machine i trust) should read the statistics of the last Backup 
and report them to a Monitoring System

**Comment by ThomasWaldmann** [comment]
You could use `borg create --stats` and maybe also try the json-related options.

`borg info repo::LASTARCHIVE` is maybe also useful, but only if you run it after each backup, so the deduped size will show if there is a sudden major increment of new data.

So borg offers the data you need for monitoring, but you need to do the monitoring yourself.

**Comment by dcbo** [comment]
Thanks

**Comment by ThomasWaldmann** [comment]
If you want to run the borg client somewhere else, you will need the key and the passphrase.

They key part is easy if you use `repokey` mode, otherwise you'll need to copy the key.

In general, if you let multiple borg clients access the same repo, some repo operations might get the other clients out of sync (and needing a resync when they do the next operation).
