### ISSUE TITLE
Wishlist: FUSE driver to mount repositories in a snapshot-like fashion

### ISSUE THREAD

**Issue by andreas-h** [borgbackup/borg#588]
The one feature I love about older backup software like rsnapshot is that they provide actual filesystem folders representing the state of the backup source at the point of backup.

Wouldn't it be possible to implement this for borg as a FUSE driver?  Then one could `borg mount $REPOSITORY $MOUNTPOINT` and would have a read-only version of the backup repository. At its root, there could be one folder per backup, like this:

    $MOUNTPOINT/2016-01-01T00:00:00
    $MOUNTPOINT/2016-01-02T01:23:45
    [...]

The user could then use regular filesystem tools / the toolchain she is used to to investigate changes between backups and so on.

What do you think?  Is there interest in such a feature?

**Comment by ThomasWaldmann** [comment]
hint: there is borg mount already. :)
