### ISSUE TITLE
borg check does not detect defects caused by bad sectors

### ISSUE THREAD

**Issue by saddy001** [borgbackup/borg#5916]
This borg 1.1.15 on Ubuntu 18.04, ext4 (client) and borg 1.1.9 on Raspbian 10, ext4 external usb HDD (server).

While doing `borg extract --list ::reponame-time` when remotely restoring a failed system I got an IOError from borg. Looking at dmesg I found the reason, the HDD containing the backup repo has defect sectors and borg tried to read from it:
```
I/O error, dev sda, sector 10016080
USB disconnect, device number 9: rejecting I/O to dead device
```
I could restore the system by using excludes to circumvent these sectors and so far everything is fine with borg. Then I wanted to improve my backup strategy by automating `borg check` to avoid that situation in the future. However neither `borg check  <REPO-PATH>` nor `borg check --verify-data <REPO-PATH>` see any problems with the archive. Is this intended?

**Comment by ThomasWaldmann** [comment]
Well, borg check does not cryptographically verify the content data of files. borg check --verify-data does that though.
So I'ld say the latter should read/verify all data from the repo.

Maybe that I/O error is not happening always, but only sometimes?
Is sda really your usb HDD?
**If you posted the full traceback, we could better see where borg is failing.**

As a general note, it might be a bad idea to run borg check --repair if your hardware is defective.
I'ld rather first transfer the repo to a working storage device and then try borg check there.

**Comment by saddy001** [comment]
I did another `borg extract --dry-run` and that went fine. My current working hypothesis is that the sector got reallocated and was repaired at the same time. This is consistent with smartctl Reallocated_Sector_Ct being 2 while Offline_Uncorrectable is 0. 
So I guess it's not a borg problem.
