### ISSUE TITLE
update docs $30 bounty (48)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5928]
there are quite some docs issues: https://github.com/borgbackup/borg/labels/documentation

grab some doc update issues, create a PR against master (and, after discussion, also to 1.1-maint, if applicable, see here, also linked from PR submission template)

the bounty is for fixing 2 small issues or 1 bigger issue.
docs issues that already have a bounty on them do not qualify.

---

:moneybag: [there is a bounty for this]()

**Comment by remyabel** [comment]
Two small issues fixed: https://github.com/borgbackup/borg/pull/5931, https://github.com/borgbackup/borg/pull/5930

Github also did not seem to close the original issues automatically for some reason.

**Comment by ThomasWaldmann** [comment]
not auto-closing is because this was not merged into master (but 1.1-maint). i closed manually.

so all done here!
