### ISSUE TITLE
Original size of All archives

### ISSUE THREAD

**Issue by izyk** [borgbackup/borg#5933]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION or maybe BUG/ISSUE/FEATURE

#### Your borg version (borg -V).
borg 1.1.16

#### Operating system (distribution) and version.
CentOS Linux release 7.9.2009 (Core)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg info /path/to/archive::archivename

## Describe the problem you're observing.
Hello.
Why is the original size ("Original size" column) in the row describing all archives not equal to the sum of all archives added to the repository? Why does it show a different size that exceeds the sum of the original sizes of all archives?  What does this size show? 
Thank you.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                2.27 TB            467.83 GB             12.09 GB
All archives:               16.74 TB              3.16 TB            393.70 GB

```
Sum of all my archives is 2.27*5=11,35 TB

**Comment by khmarbaise** [comment]
I would say this belongs into the the discussion are here: https://github.com/borgbackup/borg/discussions

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/discussions/5935 moved to there, closing here.
