### ISSUE TITLE
add documentation for command in authorized_keys

### ISSUE THREAD

**Issue by tomaszduda23** [borgbackup/borg#5938]
Documentation should explain bellow. It seems to be present only in source code.

`                whitelist = {`
`                    'debug_topics',`
`                    'lock_wait',`
`                    'log_level',`
`                    'umask',`
`                }`

`# note: it is not possible to specify a whitelisted option via a forced command,`
`# it always gets overridden by the value specified (or defaulted to) by the client commmand.`

**Comment by hexagonrecursion** [comment]
Note: since c53190176389dcbd711060a8a9f4326e66d1d533 umask is in the denylist instead of allowlist
