### ISSUE TITLE
borg delete --force should kill repo without passphrase

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5941]
There should be a way to cleanly remove a repo even if the passphrase was lost.

`borg delete REPO` wants to know the passphrase (and if given, it will list all archives in the repo and ask "are you sure?").
to list the archives, the key is needed, so it asks for the passphrase.

But if the user is really sure anyway, we could offer a non-default less safe way with `borg delete --force REPO` and just kill the repo, no questions asked.

Workaround until this is implemented:
```
borg config REPO id     # gives id for manual clean up
rm -rf REPO
rm -rf ~/.cache/borg/THATID
rm -rf ~/.config/borg/security/THATID
```

Of course, this will **not** delete an append-only mode repository.

**Comment by remyabel** [comment]
From what I tell, there doesn't seem to be an existing test case for deleting an append only repo in `src/borg/testsuite/archiver.py`. I have something like this:

```python
def test_delete_force_repo_append_only(self):
        os.environ['BORG_PASSPHRASE'] = 'passphrase'
        self.cmd('init', '--encryption=repokey', '--append-only', self.repository_location)
        self.cmd('create', self.repository_location + '::test', 'input')
        # Should not delete an append-only repository
        os.environ['BORG_DELETE_I_KNOW_WHAT_I_AM_DOING'] = 'no'
        os.environ['BORG_PASSPHRASE'] = ''
        with self.assert_raises(ValueError):
            output = self.cmd('delete', '--force', self.repository_location, exit_code=EXIT_ERROR)
            assert os.path.exists(self.repository_path)
            self.assert_not_in('request', output)
```

It fails with an RPCError when the test suite passes it a `RemoteRepository`. How do you think I should handle this?

**Comment by ThomasWaldmann** [comment]
@remyabel please move that to a new ticket.

**Comment by remyabel** [comment]
Sorry if I wasn't clear. It's relevant because after adding the functionality, I also wanted to test this part:

> Of course, this will not delete an append-only mode repository.

I will open a new issue.

**Comment by Spokaren** [comment]
Hi I like to know how i can contribute to this issue

**Comment by remyabel** [comment]
Sure, spokaren can take over. I'll work on something else.

**Comment by ThomasWaldmann** [comment]
@Spokaren you have it. a good start is to look at `borg.archiver.do_delete`.

**Comment by ThomasWaldmann** [comment]
BTW, there is a test that `repository.destroy()` does not destroy an append-only repo (and that is the call used internally by `borg delete repo`):

https://github.com/borgbackup/borg/blob/1.1.17/src/borg/testsuite/repository.py#L409

**Comment by ThomasWaldmann** [comment]
@CoolCold hmm, i guess i inserted that workaround with `rm` later into that post and then it seemed the last phrase referred to that workaround and not to the stuff I wrote above it.

but as you said, append-only of course won't stop `rm`, so i moved that phrase to above the workaround.
