### ISSUE TITLE
 Fatal Python error: Bus error

### ISSUE THREAD

**Issue by seancork** [borgbackup/borg#5947]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

i'm using raspberry pi 4, (dietpi) with 64 bit = 1 on config.txt file.

#### Your borg version (borg -V).

borg 1.1.17

#### Operating system (distribution) and version.

https://dietpi.com/docs/releases/ 
lastest version

#### Hardware / network configuration, and filesystems used.

Raspberry Pi 4, 4 GB, external hard drive also

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borgmatic create

## Describe the problem you're observing.

```
Mon Aug  2 00:34:12 BST 2021 - Starting backup
changedname@changedname.repo.borgbase.com:repo: Error running actions for repository
Command 'borg create --exclude-from /tmp/tmpmzid8q_w --exclude-if-present .nobackup --compression auto,zstd --one-file-system changedname@changedname.repo.borgbase.com:repo::{hostname}-{now:%Y-%m-%d-%H%M%S} configs' died with <Signals.SIGBUS: 7>.
/etc/borgmatic/config.yaml: Error running configuration file

summary:
/etc/borgmatic/config.yaml: Error running configuration file
changedname@changedname.repo.borgbase.com:repo: Error running actions for repository
Killed stale lock DietPi@242606376069719.2757-0.
Removed stale exclusive roster lock for host DietPi@242606376069719 pid 2757 thread 0.
Removed stale exclusive roster lock for host DietPi@242606376069719 pid 2757 thread 0.
Fatal Python error: Bus error
Current thread 0xf788f010 (most recent call first):
  File "borg/crypto/key.py", line 369 in encrypt
  File "borg/cache.py", line 916 in add_chunk
  File "borg/archive.py", line 301 in write_chunk
  File "borg/archive.py", line 285 in flush
  File "borg/archive.py", line 491 in save
  File "borg/archiver.py", line 563 in create_inner
  File "borg/archiver.py", line 598 in do_create
  File "borg/archiver.py", line 177 in wrapper
  File "borg/archiver.py", line 4635 in run
  File "borg/archiver.py", line 4703 in main
  File "borg/__main__.py", line 2 in <module>
Command 'borg create --exclude-from /tmp/tmpmzid8q_w --exclude-if-present .nobackup --compression auto,zstd --one-file-system changedname@changednam:repo::{hostname}-{now:%Y-%m-%d-%H%M%S} configs' died with <Signals.SIGBUS: 7>.

```

Need some help? https://torsion.org/borgmatic/#issues

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

yes , I seen this https://github.com/borgbackup/borg/issues/4891 but nothing there has helped me

**Comment by ThomasWaldmann** [comment]
#4891 has been fixed already, but the general way to debug this and find the root cause is similar as seen there.

The python traceback is not precise enough to really find the problem, so this need the code location on the C level including line number.

**Comment by ThomasWaldmann** [comment]
borg.crypto.key:369 calls the compressor, so the issue is likely related to some lower-level (Cython or C or external lib) compression code.

**Comment by ThomasWaldmann** [comment]
In general, 64bit on raspi has been a bit painful. While the 32bit kernel supports unaligned accesses, it seems like the 64bit one does not, see #4891.

**Comment by seancork** [comment]
A yes ok ,For now I took out auto,zstd as I do not need compression and it works as needed for me.

**Comment by ThomasWaldmann** [comment]
If you do not specify "--compression none" or so, it will default to `lz4`.

IF that works, it likely means an issue in `zstd`.

Then you could find out whether the code you use uses the bundled zstd code or the libzstd from the linux distribution. Also you could try zstd outside of borg.

**Comment by ThomasWaldmann** [comment]
Well, without more precise infos, we can't do anything about this.

If this still happens and you can provide more infos, please reopen.

**Comment by berlincount** [comment]
I'm running into the same issue.

**Comment by berlincount** [comment]
```
Remote: Current thread 0xf789c900 (most recent call first):
Remote:   File "/usr/lib/python3/dist-packages/borg/crypto/file_integrity.py", line 75 in write
Remote:   File "/usr/lib/python3/dist-packages/borg/crypto/file_integrity.py", line 29 in write
Remote:   File "/usr/lib/python3/dist-packages/msgpack/__init__.py", line 38 in pack
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 580 in write_index
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 814 in replay_segments
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 373 in check_transaction
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 376 in get_transaction_id
Remote:   File "/usr/lib/python3/dist-packages/borg/repository.py", line 1070 in get
Remote:   File "/usr/lib/python3/dist-packages/borg/remote.py", line 248 in serve
```

with `compression: none` configured.
