### ISSUE TITLE
Confusing "Permission Denied" error message when ~/.config/borg is unreadable

### ISSUE THREAD

**Issue by rsyring** [borgbackup/borg#5952]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes to the latter, no to the prior two b/c even if it's in the docs/FAQ, I think an improvement can be made

## Is this a BUG / ISSUE report or a QUESTION?

Feature Request

#### Your borg version (borg -V).

1.1.17

#### Operating system (distribution) and version.

Ubuntu 20.04

#### Hardware / network configuration, and filesystems used.

Local disk

#### How much data is handled by borg?

N/A

## Describe the problem you're observing.

When borg encounters a configuration directory that is not readable, it errors with a "Permission denied" message.  However, it's not clear what path has permission problems.  The first/obvious, but wrong, assumption is that it's something with the repo directory.  But when you look at that directory, it appears that borg has created a repo (or part of it).

It would be a lot more helpful if the permission denied message included the problematic path that can't be accessed.

```
$ borg init --encryption repokey-blake2 ~/tmp/borg-bar
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: n
Error: Permission denied

$ ls -lh ~/.config/borg/
ls: cannot open directory '/home/rsyring/.config/borg/': Permission denied

$ rm -rf ~/.config/borg/
rm: cannot remove '/home/rsyring/.config/borg/': Permission denied

$ sudo rm -rf ~/.config/borg/

$ borg init --encryption repokey-blake2 ~/tmp/borg-bar
A repository already exists at /home/rsyring/tmp/borg-bar.

$ rm -rf ~/tmp/borg-bar/

$ borg init --encryption repokey-blake2 ~/tmp/borg-bar
(...snip... output as expected for successful command)
$
```

**Comment by ThomasWaldmann** [comment]
I see the issue, not enough information in the error message (which is already a "pretty" error message, not a python traceback).

BTW, to avoid such issues, always run borg as the same user.

If you run borg client/server, always use same user on client, always use same user on server, then you won't run into permission issues.

**Comment by gks** [comment]
Ran into this issue myself. I concur, this would be a great quality of life improvement.

**Comment by ThomasWaldmann** [comment]
I'll have a look. The path missing in that borg error msg is not helpful.

**Comment by gks** [comment]
> I'll have a look. The path missing in that borg error msg is not helpful.

Just wanted to say thank you for fixing this up. Much appreciated!
