### ISSUE TITLE
nothing provides python3.6dist(packaging) error on CentOS 8

### ISSUE THREAD

**Issue by jaymefSO** [borgbackup/borg#5953]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

1.1.16

#### Operating system (distribution) and version.

CentOS 8.4 / RHEL 8.4

#### Hardware / network configuration, and filesystems used.

N/A

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

N/A

## Describe the problem you're observing.

When using yum/dnf to update borgbackup RPM package from 1.1.16 to 1.1.17 the following error is observed on multiple hosts running CentOS/RHEL 8.4:

```
# yum update borgbackup
Last metadata expiration check: 2:41:14 ago on Tue 10 Aug 2021 08:58:19 AM ADT.
Error:
 Problem: cannot install the best update candidate for package borgbackup-1.1.16-1.el8.x86_64
  - nothing provides python3.6dist(packaging) needed by borgbackup-1.1.17-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes

#### Include any warning/errors/backtraces from the system logs

N/A

**Comment by ThomasWaldmann** [comment]
this is a packaging issue, better filed in centos/rhel issue tracker. @FelixSchwarz

**Comment by jaymefSO** [comment]
I was able to resolve the problem on both CentOS 8 and RHEL 8 systems by doing the following:

CentOS 8: `yum config-manager --set-enabled powertools`
RHEL 8: `subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms`

This allowed borgbackup package to install the `python3-packaging` dependency it was looking for.

**Comment by FelixSchwarz** [comment]
@jaymefSO: yes, that is what you need to do (though the canonical form for CentOS 8 is `dnf config-manager ...`)

Basically EPEL requires you to enable the powertools/coderead-builder... repos as mentioned on the [Fedora EPEL page](https://fedoraproject.org/wiki/EPEL#Quickstart) (section "Quickstart"). Unfortunately this is a bit annoying but not much I can do about. IIRC one (both) of the alternative RHEL rebuilds Rocky/Alma did enable powertools by default.
