### ISSUE TITLE
Repository has no manifest. error

### ISSUE THREAD

**Issue by enesdogan00** [borgbackup/borg#5955]
I was using borg to take backup of my servers and when I tried to access one of my backups I got the error of  "Repository has no manifest." Is there a way to fix it? It's very important for me.
```
$ sudo borg list openvpn
Repository has no manifest.
```

**Comment by ThomasWaldmann** [comment]
Well, it looks like your repository has lost some data - check whether the filesystem and disk you use is ok and working reliably.

After that, you can run `borg check --repair`- it will take quite a while depending on size of repo, but it can regenerate the manifest from archive data.

**Comment by ThomasWaldmann** [comment]
BTW, what borg version do you use? Do you use rsync.net hosting?

**Comment by enes4949** [comment]
> Well, it looks like your repository has lost some data - check whether the filesystem and disk you use is ok and working reliably.
> 
> After that, you can run `borg check --repair`- it will take quite a while depending on size of repo, but it can regenerate the manifest from archive data.
It gives the error:
```
Type 'YES' if you understand this and want to continue: YES
Repository contains no apparent data at all, cannot continue
check/repair.
```

And my version is: `borg 1.1.17`

**Comment by ThomasWaldmann** [comment]
Hmm, that sounds bad. Do a `ls -lR repodir`.

**Comment by enes4949** [comment]
```
.:
total 64
-rw------- 1 archie wheel   209 Jul 26 19:15 config
drwx------ 3 archie wheel  4096 Jul 27 23:15 data
-rw------- 1 root   root     48 Aug 13 16:27 hints.2
-rw------- 1 root   root  41258 Aug 13 16:27 index.2
-rw------- 1 root   root    190 Aug 13 16:27 integrity.2
-rw------- 1 archie wheel    73 Jul 26 19:15 README

./data:
total 4
drwx------ 2 archie wheel 4096 Aug 13 16:27 0

./data/0:
total 4
-rw------- 1 root root 17 Aug 13 16:27 2

```

**Comment by ThomasWaldmann** [comment]
Well, there is a repo, but there is no data of yours in there (just sum up all files below data, 17 bytes is just a borg commit tag).

Are you sure you are accessing the correct repo?

Also: permissions mixup in there - always use same user to access the repo.

**Comment by ThomasWaldmann** [comment]
Any news?
