### ISSUE TITLE
How to backup the backup?

### ISSUE THREAD

**Issue by niwla23** [borgbackup/borg#5961]
I make my backups to a raspberry pi with an SSD connected over ssh. Now I also want to backup the data to a NAS with SMB access.
I am thinking about just letting it rsync the backup files to the NAS every day but I was wondering if there is a better way or if there may be any conflicts / corruption using rsync to sync my backup to an SMB NAS.

**Comment by ThomasWaldmann** [comment]
See the FAQ section in the docs, please.

**Comment by jameysharp** [comment]
I'm not affiliated with this community, but since I have a similar question I'll mention that I assume the FAQ section Thomas is referring to is https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

**Comment by niwla23** [comment]
sorry didnt see that section in the FAQ.
