### ISSUE TITLE
debug log all cache / index full paths

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5963]
Considering issues like #5954 are bad to solve / debug without this information, borg should debug log full paths of all caches / indexes it uses.

**Comment by ritvikagrawal1** [comment]
i'd like to try and pick it up @ThomasWaldmann

**Comment by ThomasWaldmann** [comment]
@ritvikagrawal1 sure, just take it! :-)

**Comment by Rsakhuja** [comment]
Can I work on this issue if it's still open?

**Comment by ThomasWaldmann** [comment]
@Rsakhuja sure, just take it! :-)

**Comment by sumeetdeveloper** [comment]
@Rsakhuja are you still working upon this issue

**Comment by ThomasWaldmann** [comment]
@sumeetdeveloper if there is no response, i think we can just assume they are not working on this.

**Comment by sumeetdeveloper** [comment]
Shall I start working upon this issue then? if it is open?

**Comment by ThomasWaldmann** [comment]
Guess so, it's been a while since October.

**Comment by sumeetdeveloper** [comment]
@ThomasWaldmann can you help me to reproduce this issue or point any documentation or stuff

**Comment by ThomasWaldmann** [comment]
@sumeetdeveloper Sure.

To start, just do a global search for cache_dir in the source.

**Comment by diivi** [comment]
How would you like this to be implemented? Should there be another command that logs the cache dir by using the `get_cache_dir()` function in `fs.py`? I need a little more context, thanks!

**Comment by ThomasWaldmann** [comment]
@diivi read how the ticket linked from top post ended.

quite some work there could have been avoided if it were clear that it used a different cache dir than the user thought it did. maybe the user would have found the issue themselves, if --debug had output the full cache file path.
