### ISSUE TITLE
Error 5 Input/Output Error on Raspi 4

### ISSUE THREAD

**Issue by Oberlurch3000** [borgbackup/borg#5966]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. There are related topics but nothing helped me solving the problem.

## Is this a BUG / ISSUE report or a QUESTION?

It's a question. I'm not sure if it's a borg issue but maybe the repository damaged. Otherwhise the harddrive could be broken.

## System information. For client/server mode post info for both machines.
```
Platform: Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l
Linux: debian 10.10
```

Borg is used to backup a nextcloud server with about 2 TB of data.

NC server on 2.5'' HDD (ext4)

BACKUP server on HDD (NTFS):

```
=== START OF INFORMATION SECTION ===
Vendor:               WD
Product:              Elements 25A3
Revision:             1030
Compliance:           SPC-4
User Capacity:        8,001,529,315,328 bytes [8.00 TB]
Logical block size:   512 bytes
Physical block size:  4096 bytes
LU is fully provisioned
Rotation Rate:        5400 rpm
Serial number:        1EHUT74N
Device type:          disk
Local Time is:        Wed Aug 25 18:17:16 2021 BST
SMART support is:     Unavailable - device lacks SMART capability.

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported
```

#### Your borg version (borg -V).

Borg: 1.1.9  Python: CPython 3.7.3

#### Operating system (distribution) and version.

Platform: Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l
Linux: debian 10.10

#### Hardware / network configuration, and filesystems used.

Both harddrives are connected via USB v3 to the raspi 4.

#### How much data is handled by borg?

Approximately 2 TB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

This is how the backup log looks right now every morning.

```
###### Start des Backups: 25.08.2021 - 02:00:01 ######

Daten werden zusammengestellt
Maintenance mode enabled
apache2 wird gestoppt
Datenbanksicherung wird erstellt

Backup mit borgbackup
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 141, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 330, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1070, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 376, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 357, in check_transaction
    segments_transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1216, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1251, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

Platform: Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l
Linux: debian 10.10 
Borg: 1.1.9  Python: CPython 3.7.3
PID: 31599  CWD: /root
sys.argv: ['/usr/bin/borg', 'create', '--exclude', '/media/backup/', '--stats', '/media/backup//daten::20210825_020001', '/media/backup/temp', '/etc/', '/media/myCloudDrive/ncdatabase/', '/media/myCloudDrive/ncdata/', '/root/', '/var/www/nextcloud/', '/media/backup/temp/']
SSH_ORIGINAL_COMMAND: None


apache2 wird gestartet
Maintenance mode disabled
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 141, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib/python3/dist-packages/borg/helpers.py", line 330, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1070, in get
    self.index = self.open_index(self.get_transaction_id())
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 376, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 357, in check_transaction
    segments_transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1216, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1251, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

Platform: Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l
Linux: debian 10.10 
Borg: 1.1.9  Python: CPython 3.7.3
PID: 31642  CWD: /root
sys.argv: ['/usr/bin/borg', 'prune', '--progress', '--stats', '/media/backup//daten', '--keep-within=7d', '--keep-weekly=4', '--keep-monthly=6']
SSH_ORIGINAL_COMMAND: None


###### Ende des Backups: 25.08.2021 - 02:00:20 (00 Stunden 00 Minuten 19 Sekunden) ######
```

Plattenbelegung:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1       7.3T  1.3T  6.0T  18% /media/backup
```

This is how the backup log should look like before:

```
###### Start des Backups: 26.07.2021 - 02:00:01 ######

Daten werden zusammengestellt
Maintenance mode enabled
apache2 wird gestoppt
Datenbanksicherung wird erstellt

Backup mit borgbackup
------------------------------------------------------------------------------
Archive name: 20210726_020001
Archive fingerprint: b291f072bda3e6bad0d6fda8d80d8395408343c6a96a8786d3d59b57c93704df
Time (start): Mon, 2021-07-26 02:03:01
Time (end):   Mon, 2021-07-26 03:37:56
Duration: 1 hours 34 minutes 55.81 seconds Number of files: 481730 Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                1.90 TB              1.90 TB              7.07 GB
All archives:               33.76 TB             33.61 TB              1.41 TB

                       Unique chunks         Total chunks
Chunk index:                  850669             21123618
------------------------------------------------------------------------------

apache2 wird gestartet
Maintenance mode disabled
Pruning archives   0%
Initializing cache transaction: Reading config Initializing cache transaction: Reading chunks Initializing cache transaction: Reading files


Compacting segments   0%
Compacting segments   1%
Compacting segments   2%
Compacting segments   3%
Compacting segments   4%
Compacting segments   5%
Compacting segments   6%
Compacting segments   7%
Compacting segments   8%
Compacting segments   9%
Compacting segments  10%
Compacting segments  11%
Compacting segments  12%
Compacting segments  13%
Compacting segments  14%
Compacting segments  15%
Compacting segments  16%
Compacting segments  17%
Compacting segments  18%
Compacting segments  19%
Compacting segments  20%
Compacting segments  21%
Compacting segments  22%
Compacting segments  23%
Compacting segments  24%
Compacting segments  25%
Compacting segments  26%
Compacting segments  27%
Compacting segments  28%
Compacting segments  29%
Compacting segments  30%
Compacting segments  31%
Compacting segments  32%
Compacting segments  33%
Compacting segments  34%
Compacting segments  35%
Compacting segments  36%
Compacting segments  37%
Compacting segments  38%
Compacting segments  39%
Compacting segments  40%
Compacting segments  41%
Compacting segments  42%
Compacting segments  43%
Compacting segments  44%
Compacting segments  45%
Compacting segments  46%
Compacting segments  47%
Compacting segments  48%
Compacting segments  49%
Compacting segments  50%
Compacting segments  51%
Compacting segments  52%
Compacting segments  53%
Compacting segments  54%
Compacting segments  55%
Compacting segments  56%
Compacting segments  57%
Compacting segments  58%
Compacting segments  59%
Compacting segments  60%
Compacting segments  61%
Compacting segments  62%
Compacting segments  63%
Compacting segments  64%
Compacting segments  65%
Compacting segments  66%
Compacting segments  67%
Compacting segments  68%
Compacting segments  69%
Compacting segments  70%
Compacting segments  71%
Compacting segments  72%
Compacting segments  73%
Compacting segments  74%
Compacting segments  75%
Compacting segments  76%
Compacting segments  77%
Compacting segments  78%
Compacting segments  79%
Compacting segments  80%
Compacting segments  81%
Compacting segments  82%
Compacting segments  83%
Compacting segments  84%
Compacting segments  85%
Compacting segments  86%
Compacting segments  87%
Compacting segments  88%
Compacting segments  89%
Compacting segments  90%
Compacting segments  91%
Compacting segments  92%
Compacting segments  93%
Compacting segments  94%
Compacting segments  95%
Compacting segments  96%
Compacting segments  97%
Compacting segments  98%
Compacting segments  99%

Saving chunks cache
Saving cache config

------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:               -1.90 TB             -1.89 TB           -100.26 MB
All archives:               31.86 TB             31.73 TB              1.41 TB

                       Unique chunks         Total chunks
Chunk index:                  850301             19926656
------------------------------------------------------------------------------

###### Ende des Backups: 26.07.2021 - 03:42:49 (01 Stunden 42 Minuten 48 Sekunden) ######
```

Plattenbelegung:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1       7.3T  1.3T  6.0T  18% /media/backup
```

This shows up if I do "borg check":

```
root@raspberrypi:/home/pi# borg check /media/backup/daten/
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 892, in check
    transaction_id = self.get_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 376, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 357, in check_transaction
    segments_transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1216, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1251, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 315, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 896, in check
    transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1216, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1251, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

Platform: Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l
Linux: debian 10.10
Borg: 1.1.9  Python: CPython 3.7.3
PID: 25369  CWD: /home/pi
sys.argv: ['/usr/bin/borg', 'check', '/media/backup/daten/']
SSH_ORIGINAL_COMMAND: None
```

## Describe the problem you're observing.

I use borg backup about one year now to backup my cloud.
Since a few weeks the backup runs into an error every night.
There were no bigger changes to the system during this time. Maybe a Nextcloud update or so.
No changes to the core system or borg or the backup script.
The amount of data handeled by borg increased very slowly.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. The error occurs every time I run the backup no matter if manually or by cronjob.
I already tried a different raspi 4 changed the USB ports or rebooted everything. But same result.

**Comment by Oberlurch3000** [comment]
So after some trying around I got the right command for testing the harddrive:
'''
root@raspberrypi:/media/backup/backup_logs# smartctl --all --device sat /dev/sdb1
smartctl 6.6 2017-11-05 r4594 [armv7l-linux-5.10.52-v7l+] (local build)
Copyright (C) 2002-17, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     WDC WD80EMAZ-00WJTA0
Serial Number:    1EHUT74N
LU WWN Device Id: 5 000cca 27ed9cfbd
Firmware Version: 83.H0A83
User Capacity:    8,001,563,222,016 bytes [8.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      3.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Sun Aug 29 20:39:02 2021 BST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x80) Offline data collection activity
                                        was never started.
                                        Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever
                                        been run.
Total time to complete Offline
data collection:                (   93) seconds.
Offline data collection
capabilities:                    (0x5b) SMART execute Offline immediate.
                                        Auto Offline data collection on/off support.
                                        Suspend Offline collection upon new
                                        command.
                                        Offline surface scan supported.
                                        Self-test supported.
                                        No Conveyance Self-test supported.
                                        Selective Self-test supported.
SMART capabilities:            (0x0003) Saves SMART data before entering
                                        power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine
recommended polling time:        (   2) minutes.
Extended self-test routine
recommended polling time:        (1066) minutes.
SCT capabilities:              (0x003d) SCT Status supported.
                                        SCT Error Recovery Control supported.
                                        SCT Feature Control supported.
                                        SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0004   128   128   054    Old_age   Offline      -       116
  3 Spin_Up_Time            0x0007   169   169   024    Pre-fail  Always       -       335 (Average 442)
  4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       474
  5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000a   100   100   067    Old_age   Always       -       0
  8 Seek_Time_Performance   0x0004   128   128   020    Old_age   Offline      -       18
  9 Power_On_Hours          0x0012   100   100   000    Old_age   Always       -       900
 10 Spin_Retry_Count        0x0012   100   100   060    Old_age   Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       474
 22 Unknown_Attribute       0x0023   100   100   025    Pre-fail  Always       -       100
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       498
193 Load_Cycle_Count        0x0012   100   100   000    Old_age   Always       -       498
194 Temperature_Celsius     0x0002   151   151   000    Old_age   Always       -       43 (Min/Max 20/48)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Completed without error       00%       831         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
'''

I think everything looks OK in my opinion.
Further I created a second repository on my raspis SD card just to see if everything works. => That works fine
If i try to create a 2nd repo an the HDD, borg tells me there's already one existing. So I can't test that...
BTW it's possible to access files directly from the harddrive.

So the problem is borg not being able to access the repository on the HDD. So maybe the repo is damaged?
Is there any other way to check if the repo is broken beside "borg check" since this commad runs into Errno 5 too.

If that's the case it would be ok, since I got an other backup and the server is still running. I'd only like to know what could went wrong and save some time if possible. Creating a new repo takes some time when backing up 2TB of data for the first time :/.

**Comment by ThomasWaldmann** [comment]
The SMART log and test results look fine.

The other issues you added in your last post are unclear. We need precise commands here and their output.

There is no fundamental reason why borg would work on your sdcard and not on your hdd. Something is wrong there.

**Comment by Oberlurch3000** [comment]
So this is the output if I try "borg check":
```
root@raspberrypi:/home/pi# borg check /media/backup/daten
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 892, in check
    transaction_id = self.get_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 376, in get_transaction_id
    self.check_transaction()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 357, in check_transaction
    segments_transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1216, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1251, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 315, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 896, in check
    transaction_id = self.io.get_segments_transaction_id()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1216, in get_segments_transaction_id
    if self.is_committed_segment(segment):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1251, in is_committed_segment
    if fd.read(self.header_fmt.size) != self.COMMIT:
OSError: [Errno 5] Input/output error

Platform: Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l
Linux: debian 10.10
Borg: 1.1.9  Python: CPython 3.7.3
PID: 792  CWD: /home/pi
sys.argv: ['/usr/bin/borg', 'check', '/media/backup/daten']
SSH_ORIGINAL_COMMAND: None
```
Same problem like the backup script itselve.

Second I tried to create a repo beside "/media/backup/daten" in "/media/backup/daten2" just to see if it works to create a new repo on the same harddrive. I can create a second repo an backup into it.
```
root@raspberrypi:/home/pi# bash /root/scripts/testbackup.sh

###### Start des Backups: 30.08.2021 - 18:40:30 ######

Daten werden zusammengestellt
Maintenance mode enabled
apache2 wird gestoppt
Datenbanksicherung wird erstellt

Backup mit borgbackup
------------------------------------------------------------------------------
Archive name: 20210830_184030
Archive fingerprint: 0fdbe4581bd7e0575fd88834b10e1e63a579e99cc170a12883299badaa071adb
Time (start): Mon, 2021-08-30 18:40:46
Time (end):   Mon, 2021-08-30 18:40:47
Duration: 0.24 seconds
Number of files: 30
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               36.62 kB             18.51 kB             18.42 kB
All archives:               36.62 kB             18.51 kB             18.42 kB

                       Unique chunks         Total chunks
Chunk index:                      27                   29
------------------------------------------------------------------------------

apache2 wird gestartet
Maintenance mode disabled
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:               36.62 kB             18.51 kB             18.42 kB

                       Unique chunks         Total chunks
Chunk index:                      27                   29
------------------------------------------------------------------------------

###### Ende des Backups: 30.08.2021 - 18:40:50 (00 Stunden 00 Minuten 20 Sekunden) ######

Plattenbelegung:

Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1       7.3T  1.3T  6.0T  18% /media/backup
root@raspberrypi:/home/pi# borg list /media/backup/daten2
Enter passphrase for key /media/backup/daten2:
20210830_184030                      Mon, 2021-08-30 18:40:46 [0fdbe4581bd7e0575fd88834b10e1e63a579e99cc170a12883299badaa071adb]
```
The backup gets saved like it should:
```
root@raspberrypi:/home/pi# borg list /media/backup/daten2
Enter passphrase for key /media/backup/daten2:
20210830_184030                      Mon, 2021-08-30 18:40:46 [0fdbe4581bd7e0575fd88834b10e1e63a579e99cc170a12883299badaa071adb]
```
When performing "borg check" with the new repo it seems to work I guess? There is no output.
```
root@raspberrypi:/home/pi# borg check /media/backup/daten2
Enter passphrase for key /media/backup/daten2:
```
So the problems appear exclusivly at the existing "old" repo I guess. That's why I think the repo got damaged somehow.

**Comment by ThomasWaldmann** [comment]
Try to copy the problematic repo to a new location, e.g. daten -> daten-copy.

`cp -a`or `rsync -a`should do it. Check if the cp or rsync works without emitting any error messages. If you get any error message (like I/O error), you will see that the problem has nothing to do with borg. If you don't get any error, it might be just random luck and an intermittent error.

Then run `borg check` on the new repo directory.

**Comment by Oberlurch3000** [comment]
Ok.. so this was the error output after copying all the backup data. Is it possible to delete this file "7777" so the backup could work again?
```
root@raspberrypi:/media/backup# rsync -a --info=progress2 --info=name0 /media/backup/daten /media/backup/daten-copy
1,424,351,336,113 100%   16.40MB/s   23:00:04 (xfr#5658, to-chk=0/5668)
rsync: read errors mapping "/media/backup/daten/data/7/7777": Input/output error (5)
1,424,444,282,545 100%   16.40MB/s   23:00:13 (xfr#5659, to-chk=0/5668)
rsync: read errors mapping "/media/backup/daten/data/7/7777": Input/output error (5)
ERROR: daten/data/7/7777 failed verification -- update discarded.
1,424,444,282,545 100%   16.40MB/s   23:00:13 (xfr#5659, to-chk=0/5668)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
You have new mail in /var/mail/root
```

**Comment by ThomasWaldmann** [comment]
You should first get your hardware / kernel / filesystem working reliably before trying to `borg check --repair` this repo.

As you see with rsync failing also, there is some problem below borg and rsync.

As the HDD SMART test looked ok, maybe try a `fsck` next?

**Comment by Oberlurch3000** [comment]
I think for my NTFS drive "ntfsfix" is the right command, since fsck gives no output.
But it looks good so far.
```
root@raspberrypi:/home/pi# ntfsfix /dev/sdb1
Mounting volume... OK
Processing of $MFT and $MFTMirr completed successfully.
Checking the alternate boot sector... OK
NTFS volume version is 3.1.
NTFS partition /dev/sdb1 was processed successfully.
```

**Comment by ThomasWaldmann** [comment]
Not sure if you should continue backups on that hardware, it seems broken. I guess the issue will reappear later...

You can interrupt a borg backup by just killing the borg process (= SIGTERM, SIGINT). If you do that after it has made checkpoint[s] (usually every 30 mins), it will make progress over time.

**Comment by Oberlurch3000** [comment]
Yeah, you are right. It's a bit risky to do so. But since it is my private cloud and I got a second backup I want to give it a try ;). Some kind of snapshot is worth thinking of.

Right now I use ```timeout``` to stop the process after 4 hours and 5 minutes.

Thank you for your advice and help! I'll close this thread now.

**Comment by Oberlurch3000** [comment]
SOLVED:
Just to complete this thread.
Finally I found the issue. In my backup directories I had just a "/" beside the cloud's data and database folder. By removing it the backup runs like it should.

So in conclusion: No hardware or filesystem error. Just users fault ;).

**Comment by ThomasWaldmann** [comment]
```
['/usr/bin/borg', 'create', ..., '/media/backup//daten::20210825_020001', ...]
```

Right, that looks erroneous.

Still wondering why that produces this traceback though...
