### ISSUE TITLE
tar options possible?

### ISSUE THREAD

**Issue by yash-fn** [borgbackup/borg#5972]
Basically same issue as #5177 but am wondering if you an option may be added similar to tar flag "-C" which changes directory prior to extracting or archiving. 

I envision something like 
`borg extract -C /path/extractdir repo::backup`

which will then change to /path/extractdir dir and extract contents into that folder. 
This will enable it to function similar to tar which would be
`tar xf archive.tar -C /path/extractdir`

Is this possibility? My use case is using within docker container and as such working directory cannot be easily changed by me without rebuilding application each time. syntactic sugar. Many thanks for your efforts!

**Comment by yash-fn** [comment]
Also found something with pipelines which appears to work:

`borg export-tar repo::backup - | tar xf - -C extractdir`

Seems to work fine? Is this same as what I mentioned above?

**Comment by Gu1nness** [comment]
Seems a good idea to me.
@ThomasWaldmann what do you think?
Or we keep it simple and add something to the documentation ?

**Comment by ThomasWaldmann** [comment]
Usually -C can be easily replaced by just first changing into that directory via a shell command.

**Comment by yash-fn** [comment]
Would just be a nice syntactic sugar in situations where two commands can be inconvenient like in pipeline. It couldn't hurt to add it right? Still learning python, but if I were to try to implement feature which file in project structure would be best place to add it?

**Comment by ThomasWaldmann** [comment]
It all starts in src/borg/archiver.py search for e.g. do_extract there.

**Comment by yash-fn** [comment]
I think all I need to implement this feature is to basically prepend the -C arg to all path args for create command and then strip the -C arg from the path prior to the path being stored into the repo. And then for extract I would need to only prepend the -C arg to any paths that it writes out from the repo.
So to that effect, where is the path argument parsed? Don't know where argument parsing begins. Could someone please give me just a rough framework of how the argument parsing is handled and/or where?

**Comment by yash-fn** [comment]
Oh sweet. I found some strip-components option that is pretty similar to what I want to do. I'm gonna try and mimic that first for export.
