### ISSUE TITLE
require py38 (master branch /  borg 1.2)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5975]
considering that there is widespread support for 3.8+ meanwhile and creating the next release (1.2) is still todo, i guess we could also drop support for py37 and require py38 as the minimum for borg >= 1.2.

anyone seeing a problem with this?

everybody who is still on <=py37 seems to prefer older / stable stuff, so can as well just use borg 1.1.x.

**Comment by ThomasWaldmann** [comment]
I checked all the stuff used by our vagrant testing boxes:
```
boxes using pyenv install 3.9.5 for the binary build and do not use the
system python for testing, but other pythons installed via pyenv.

ubuntu focal: 3.8.2
debian bullseye: 3.9.2
debian buster: pyenv
debian stretch: pyenv
freebsd 12.1: pyenv
openbsd 6.9: 3.8.x
netbsd 9.2: 3.8.x
macos-sierra: pyenv
openindiana 2021.04: 3.9.4 (currently upgrading that box)
```

**Comment by ThomasWaldmann** [comment]
Seems like noone has anything against this, so I'll do that now...

**Comment by FelixSchwarz** [comment]
I'm a bit late to the party but I wanted to mention that we only have Python 3.6 in CentOS 7 + CentOS 8 (with all the required dependencies). From a RHEL perspective Python 3.6 is the "forever Python" which will be present+supported for the next 8+ years (similar to Python 2.7 currently).
