### ISSUE TITLE
sshd: message authentication code incorrect

### ISSUE THREAD

**Issue by ruffson** [borgbackup/borg#5984]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
server: borg 1.1.9
client: Vorta 0.7.8 and borg 1.1.17

#### Operating system (distribution) and version.
server: Raspberry Pi OS (Debian 10 buster)
client: Fedora 34

#### Hardware / network configuration, and filesystems used.
server: Raspberry Pi 4B/ 8GB connected via ethernet to router
BTRFS file systems but same problem on former ext4
local network

#### How much data is handled by borg?
~ 2-3 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
I usually use Vorta but could reproduce with following simple test:
`borg create pi@192.168.1.234:/mnt/data/backup::Friday ~/ `

## Describe the problem you're observing.

When I try to backup via ssh I get "Connection closed by remote host" after months of it working correctly.
I checked #636 and other issues but none of the mitigations helped me.
The connection drops seconds after it was initiated.
See the logs below.

Things I tried:
- Adding the 3 lines mentioned in [this](https://github.com/borgbackup/borg/issues/636#issuecomment-183423240) comment
- Changing ClientAliveInterval and ClientAliveCountMax to varies numbers (10, 0 and 30, 3 respectively)
- Adding --lock-wait 600 to my borg command
- Switching out hardware: tried 3 different raspberry pies
- Moving the server from wifi to ethernet
- Adding a brand new backup drive (using btrfs whereas before I used ext4)
- Setting up a new borg repo

I want to stress that this worked for months flawlessly and that I did not change anything about the server. Now everything is newly setup (several times) and it does not even start a backup because it fails after a few seconds.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Running the above mentioned command.

#### Include any warning/errors/backtraces from the system logs

Logs from the server:

The `journalctl` at connection start looks like this:

```
Sep 10 09:09:10 homepi sshd[1094]: Accepted publickey for pi from 192.168.1.189 port 59228 ssh2: ED25519 ...
Sep 10 09:09:10 homepi sshd[1094]: pam_unix(sshd:session): session opened for user pi by (uid=0)
Sep 10 09:09:10 homepi systemd-logind[395]: New session 4 of user pi.
Sep 10 09:09:10 homepi systemd[1]: Started Session 4 of user pi.
```
And after a few seconds it always closes with this:

```
Sep 10 09:09:43 homepi sshd[1100]: ssh_dispatch_run_fatal:
   Connection from user pi 192.168.1.189 port 59228: message authentication code incorrect
Sep 10 09:09:43 homepi sshd[1094]: pam_unix(sshd:session): session closed for user pi
Sep 10 09:09:43 homepi systemd-logind[395]: Session 4 logged out. Waiting for processes to exit.
Sep 10 09:09:43 homepi systemd[1]: session-4.scope: Succeeded.
Sep 10 09:09:43 homepi systemd-logind[395]: Removed session 4.
```

**Comment by ThomasWaldmann** [comment]
If sshd says "message authentication code incorrect" (== MAC incorrect), I guess this means a corrupted network packet payload.

ssh uses authenticated encryption, that means when sending data it first encrypts (e.g. AES) and then authenticates (computes a MAC). When receiving data, it first authenticates (checks the MAC) before decrypting. The MAC check fails for you, so that means the payload has been corrupted and it does not even try to decrypt it.

I am regularly seeing that sort of crap on a buggy network infrastructure "protected" by a S*ph*s firewall / DPI.

**Comment by ThomasWaldmann** [comment]
I tagged this as "won't fix" because it is not a borg issue. It might be a hardware issue, not sure.

**Comment by ruffson** [comment]
@ThomasWaldmann  Thank you for that thorough explanation. I doubt that this is a hardware issue since I also experience the same problem with a different notebook as client and 3 different pis as server. So maybe it is more a (suddently) misconfigured ssh config. Although I can connect to and keep a solid connection with ssh otherwise.

Still probably not an issue with borg and I will keep looking or (more likely) give up on it.

**Comment by ThomasWaldmann** [comment]
I doubt that you could misconfigure ssh in a way leading to this issue.

But there could be a bug in ssh(d), a bug in other software between NIC and sshd.
