### ISSUE TITLE
Issues with non-accessible folder

### ISSUE THREAD

**Issue by fury182** [borgbackup/borg#5991]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

1.1.17

#### Operating system (distribution) and version.

Ubuntu 20.04

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create --progress hostname:repo::2021-09-25-03-00-00 '/home/parent/' --pattern=-'/home/parent/inaccessible/' --exclude /home/parent/inaccessible/

## Describe the problem you're observing.

Even though I exclude the "inaccessible" folder (even twice because I tried everything I could to get it to work) that is not accessible by the user running the command, borg still displays:

/home/parent/inaccessible: stat: [Errno 13] Permission denied: '/home/parent/inaccessible'

during backup, and most annoyingly finishes the execution with an error code (so my parent script launching the backup thinks something went really wrong).

**Comment by jdchristensen** [comment]
Try excluding the trailing slash:  `--exclude /home/parent/inaccessible`
If that doesn't work, can you give the exact commands to reproduce it, including how you create the inaccessible directory?

**Comment by fury182** [comment]
@jdchristensen No luck, there's no difference in behavior when removing the trailing slash. The inaccessible folders are fuse mounted folders created by Tresorit. I'm running my backup as root and the mounted folders belong to a regular user.

Thanks

**Comment by ThomasWaldmann** [comment]
If nothing else helps, did you try reading the docs? :-)

https://borgbackup.readthedocs.io/en/stable/usage/help.html#miscellaneous-help

especially the parts about "exclude-norecurse" and "full path" might be useful, also the different pattern styles.

**Comment by jdchristensen** [comment]
I haven't been able to reproduce the issue using a folder that I remove permissions on.  If @fury182 can give a standalone way to reproduce the problem, that would help.  I guess the difference might be that even when I remove permissions from a directory, I am still allowed to stat it.  Maybe there's no way to make borg avoid doing a stat on a folder within a folder that is backed up?  Hmm, in my case, strace doesn't show a stat, but there is a call to getdents64 that might be an issue?  Not sure.  @fury182 could try running `strace -f -v -o /tmp/borg.strace <borg command>` to see what happens there.

**Comment by fury182** [comment]
To answer @ThomasWaldmann I tried using --pattern=!'/home/parent/inaccessible/' but I got the same error.

**Comment by fury182** [comment]
@jdchristensen I think the issue should be reproducible by mounting a fuse directory as a regular user (such that root does not have permissions to it) and then running the backup as root. I don't think Tresorit is doing anything non-standard for this directory.

Details for the directory appear as below (ls -la):
drwx------ 1 myuser root 0 Jan  1  1970 /home/parent/inaccessible/

If you still can't reproduce I'll look into it some more.

Thanks!

**Comment by jdchristensen** [comment]
I tested with a fuse filesystem, but still can't reproduce this.  Please provide a precise recipe to reproduce it.

```
# mount | tail -2
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
# cd /run/user/1000
# ls -d doc
ls: cannot access 'doc': Permission denied
# stat doc
stat: cannot stat 'doc': Permission denied
# ls -d gvfs
ls: cannot access 'gvfs': Permission denied
# stat gvfs
stat: cannot stat 'gvfs': Permission denied
# mkdir /tmp/borgtest.repo
# borg init -e none /tmp/borgtest.repo
# borg create --exclude /run/user/1000/gvfs --exclude /run/user/1000/doc /tmp/borgtest.repo::test /run/user/1000
# borg --version
borg 1.1.17
```

**Comment by codethief** [comment]
I'm having the same issue with borgbackup v1.2.1: In my case it's the (rootless) Docker volumes and overlays that cause trouble:

```
/home/user/.local/share/docker/volumes/d863a5929ca407637509e8d07ec21fbf1446f4f14673f5eb7d7d6e0ce2930a8c/_data/fastcgi_temp: dir_open: [Errno 13] Permission denied: 'fastcgi_temp'
/home/user/.local/share/docker/volumes/d863a5929ca407637509e8d07ec21fbf1446f4f14673f5eb7d7d6e0ce2930a8c/_data/uwsgi_temp: dir_open: [Errno 13] Permission denied: 'uwsgi_temp'
```

where 

```
$ sudo ls -l /home/user/.local/share/docker/volumes/d863a5929ca407637509e8d07ec21fbf1446f4f14673f5eb7d7d6e0ce2930a8c/_data/
drwx------ 2 100999 100999 4096 Apr 14 14:53 client_temp
drwx------ 2 100999 100999 4096 Apr 14 14:53 fastcgi_temp
drwx------ 2 100999 100999 4096 Apr 14 14:53 proxy_temp_path
drwx------ 2 100999 100999 4096 Apr 14 14:53 scgi_temp
drwx------ 2 100999 100999 4096 Apr 14 14:53 uwsgi_temp
```

I backup more or less my entire `/home` directory but specify exceptions, like so:

```bash
borg create                                 \
    --compression lz4                       \
    --exclude-caches                        \
    --filter AME                            \
    --list                                  \
    --patterns-from directories.txt \
    --progress                              \
    --show-rc                               \
    --stats                                 \
    --verbose                               \
                                            \
    ::"{hostname}-$ARCHIVE_NAME-{utcnow}"
```

where directories.txt contains

```
# Pattern style
P sh

# Root directory, i.e. where recursion / backup starts
R /home/user

##### INCLUDES
# Since we're excluding all dotfiles below, explicitly include the following
# directories (i.e. override the exclusion rule in the following cases):
+ /home/*/.config
+ /home/*/.ssh
+ /home/*/.mozilla/firefox
# …

##### EXCLUDES
# Exclude cache directories and the like:
- /home/*/**/node_modules
- /home/*/tmp
# …

# Exclude all (other) dotfiles:
- /home/*/.*
```

Now I tried adding `- /home/*/.local/share/docker/**/*` (and variations of this exclusion patterns) to that file but in every single case I still get the permission warnings and borgbackup, at the end of the day, exits with code 1 (`terminating with warning status, rc 1`).

**Comment by ThomasWaldmann** [comment]
The error happens with `dir_open` (so borg want to recurse into that directory). If that is denied, you get this error.

To avoid this, you need for forbid borg recursing into these directories (`!` instead of `-`), see the patterns docs.

**Comment by codethief** [comment]
Thank you, I wasn't aware of `exclude-norecurse`!
