### ISSUE TITLE
Borg saying my directory is not a writable one, but it is!

### ISSUE THREAD

**Issue by aldaronT3** [borgbackup/borg#5993]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes
## Is this a BUG / ISSUE report or a QUESTION?

BUG

## System information. For client/server mode post info for both machines.

x64

#### Your borg version (borg -V).

1.1.16

#### Operating system (distribution) and version.

Debian 11

#### Hardware / network configuration, and filesystems used.

ext4

#### How much data is handled by borg?

Aroud 1To

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg mount /media/me/me-backup-3T::2021-09-26 01:09:11 /home/me/0-BORG/

## Describe the problem you're observing.

I use chmod to make 0-BORG/ directory writable.

```
me@me-laptop:~/0-BORG$ ls -lha
total 8,0K
drwxrwxr-x  2 me me 4,0K 27 sept. 21:35 .
drwxrwxr-x 27 me me 4,0K 27 sept. 22:02 ..
-rw-rw-rw-  1 me me    0 27 sept. 21:35 test
me@me-laptop:~/0-BORG$ chmod -R 777 .
me@me-laptop:~/0-BORG$ ls -lha
total 8,0K
drwxrwxrwx  2 me me 4,0K 27 sept. 21:35 .
drwxrwxr-x 27 me me 4,0K 27 sept. 22:02 ..
-rwxrwxrwx  1 me me    0 27 sept. 21:35 test
```

But Borg tells me my directory is not writable. Why ? 
```
me@me-laptop:~/0-BORG$ borg mount /media/me/me-backup-3T::2021-09-26 01:09:11 /home/me/0-BORG/
01:09:11: Mountpoint must be a writable directory
me@me-laptop:~/0-BORG$ ls -lha
total 8,0K
drwxrwxrwx  2 me me 4,0K 27 sept. 21:35 .
drwxrwxr-x 27 me me 4,0K 27 sept. 22:02 ..
-rwxrwxrwx  1 me me    0 27 sept. 21:35 test
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

No, I have no material for.

**Comment by ThomasWaldmann** [comment]
not a bug: borgfs is readonly, that includes the topmost directory that overlays the mountpoint directory.

**Comment by aldaronT3** [comment]
> not a bug: borgfs is readonly, that includes the topmost directory that overlays the mountpoint directory.
I do not understand sorry: borgfs is readonly, but the mountpoint directory has to be writable. Did I miss something?

**Comment by jdchristensen** [comment]
@aldaronT3 You need to quote the space character in your archive name.  Borg is trying to mount on the non-existent directory `01:09:11`:
```
01:09:11: Mountpoint must be a writable directory
```

**Comment by ThomasWaldmann** [comment]
@jdchristensen hah, good catch!

@aldaronT3 yeah, iirc that message comes from the FUSE code, not from borg. so just accept the "writable" part.

It is a bit overspecific for your case though, because there is no such directory (and thus also no such writable directory).
