### ISSUE TITLE
Remote repository seems to get corrupted easily, and then borg check --repair hangs indefinitely

### ISSUE THREAD

**Issue by SeanDS** [borgbackup/borg#5995]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug / issue report

#### Your borg version (borg -V).

Server: borg 1.1.15
Client: borg 1.1.17

#### Operating system (distribution) and version.

Server: Ubuntu 20.04.3 LTS
Client: Ubuntu 20.04.3 LTS

#### Hardware / network configuration, and filesystems used.

Backup over SSH using [borgmatic](https://torsion.org/borgmatic/). Runs as root on the client.

Client uses ext4 on top of an LVM, server uses just ext4.

#### How much data is handled by borg?

Roughly 200 GB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Error on already-corrupt repository triggered by `borg create --exclude-from /etc/borgmatic/excludes --exclude-caches --compression zstd --remote-ratelimit 500 --info user@server:/path/to/backup/::{hostname}-{now:%Y-%m-%dT%H:%M:%S.%f} /data/media /etc /home /srv /var` on client.

Hang while trying to repair triggered by `borg check --repair --progress --debug /path/to/backup` on server.

## Describe the problem you're observing.

I have a nightly backup scheduled between client and server over SSH. On at least three occasions, after the initial 200 GB backup is made, after a period of days, weeks, or months of successful incremental backups, the remote repository will develop what appears to be corruption, with subsequent backups reporting the error:

```
Data integrity error: Segment entry checksum mismatch [segment 2321, offset 483648553]
```

On each occasion, after some temporary fixes (see below) have stopped working, I have nuked the repository and started again with a full backup, but eventually the corruption returns (days, weeks or months later).

After this error starts to appear, running a `borg check --repair` on the server sometimes fixes the issue for a few days before it returns. However, eventually `borg check --repair` seems to enter a state where it hangs indefinitely after printing something like:

```
using builtin fallback logging configuration
35 self tests completed in 0.14 seconds
This is a potentially dangerous function.
check --repair might lead to data loss (for kinds of corruption it is not
capable of dealing with). BE VERY CAREFUL!

Type 'YES' if you understand this and want to continue: YES
Starting repository check
Verified integrity of /path/to/backup/index.3017
Read committed index of transaction 3017
Cleaned up 0 uncommitted segment files (== everything after segment 3017).
Segment transaction is    3017
Determined transaction is 3017
Found 2229 segments
Data integrity error: Segment entry checksum mismatch [segment 848, offset 30772150]                                               
attempting to recover /path/to/backup/data/0/848
```

(technically the above was from a `borg check --repair --progress --debug /path/to/backup`)

I have left the server running the repair command for hours and up to a day or two before without it finishing. The CPU activity starts at about 25% while the repair says "Checking segments XY.Z%" but goes to 100% eventually once it says "attempting to recover /path/to/backup/data/X/Y" and stays there until the process is killed.

It should be pointed out that the connection between client and server is somewhat unstable, with the client's modem resetting every morning, dropping open external connections in the process, and thus causing the initial backup transfer service to halt with non-zero exit code if it is still running. This usually only affects the initial 200 GB backup, with the service needing to be restarted every morning for the first few weeks until fully synced. Incremental backups after the initial backup are usually long since finished by the time in the morning when the router resets so the interruption doesn't affect the process. Even though this daily interruption doesn't seem to directly cause corruption, the point I'd like to make here is that, while the backed-up data on the remote server is all "there", and, according to borg, uncorrupted, in the process of "getting there" it is however interrupted dozens of times. I don't know if this might introduce some corruption that borg cannot identify and handle.

I think this is a bug in borg: it somehow can't handle this situation, and also hangs while trying to repair. I'd also however like assistance in fixing my currently corrupt repository too though, if possible.

Related to #4243?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I have been able to reproduce the problem by trial and error. I simply have to delete the repository, start again, and wait long enough for the corruption to come back.

#### Include any warning/errors/backtraces from the system logs

See above.

**Comment by ThomasWaldmann** [comment]
Are there log lines missing after "attempting to recover"?

It seems you have 2 problems:

1. your unstable connection. that is annoying, but does not corrupt the repo.
2. your repo server does not work correctly, likely there is some hw issue which corrupts your data.

Check memory (memtest86+), disk (smartctl -t long, smartctl -a after it finished)  and filesystem (fsck).

Additionally, there might be an efficiency problem fixing that kind of corruption. if the crc32 does not match the data in the segment file, borg tries to resync (and computes a lot of crc32 checksums for offsets incrementing byte-wise). If there is a lot of corruption and the cpu is slow, maybe that is what you see with the high cpu load.

**Comment by ThomasWaldmann** [comment]
Maybe #5327 would improve performance, not merged yet.

**Comment by SeanDS** [comment]
> Are there log lines missing after "attempting to recover"?

No, it hangs there at 100% CPU.

> Check memory (memtest86+), disk (smartctl -t long, smartctl -a after it finished) and filesystem (fsck).

Ok, I've started those checks and will report back if I find anything.

> Additionally, there might be an efficiency problem fixing that kind of corruption. if the crc32 does not match the data in the segment file, borg tries to resync (and computes a lot of crc32 checksums for offsets incrementing byte-wise). If there is a lot of corruption and the cpu is slow, maybe that is what you see with the high cpu load.

I see the person in #4243 reported waiting 10 days... about the same as just starting the full backup again. Is there a way to nuke those corrupt segments and any backups that use them, and perform a fresh backup that uses the rest of the (not corrupt) segments to avoid resyncing the entirety of the data?

**Comment by ThomasWaldmann** [comment]
borg check --repair tries to **keep all valid** (crc32 ok) segment file entries (so it does of course not kill any valid data).

The problem is that if it encounters an entry with invalid crc32, it can not rely on anything in that entry - that includes the entry length information (which is usually used to find the start of the next entry). This is why it advances byte-by-byte to find the next offset that looks like an entry with correct crc32.

If there is only one invalid entry, this should succeed usually after ~2MiB (max. 8MiB).
But if there is lots of crap (all entries in that one segment file or even all entries in all segment files after there), it could be more data to process and take much longer (but that would also indicate major hw / fs / kernel issues on that machine).

What CPU does the borg repo server have? ECC memory?

**Comment by SeanDS** [comment]
I've done the tests you listed, and all came back without errors.

> What CPU does the borg repo server have? ECC memory?

Details below. I believe the total width shown for the memory report implies it's ECC.

```
$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           26
Model name:                      Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
Stepping:                        5
Frequency boost:                 enabled
CPU MHz:                         2666.850
CPU max MHz:                     2667.0000
CPU min MHz:                     1600.0000
BogoMIPS:                        5333.70
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr 
                                 sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology
                                  nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 ss
                                 e4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flus
                                 h_l1d

$ dmidecode -t memory
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.6 present.

-- some unrelated memory info removed --

Handle 0x0013, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x000D
        Error Information Handle: Not Provided
        Total Width: 72 bits
        Data Width: 64 bits
        Size: 4096 MB
        Form Factor: DIMM
        Set: None
        Locator: DIMM2A
        Bank Locator: BANK2
        Type: Other
        Type Detail: Other
        Speed: 1333 MT/s
        Manufacturer: Manufacturer02
        Serial Number: 00000000
        Asset Tag: AssetTagNum2
        Part Number:                   
        Rank: Unknown

Handle 0x0015, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x000D
        Error Information Handle: Not Provided
        Total Width: 72 bits
        Data Width: 64 bits
        Size: 4096 MB
        Form Factor: DIMM
        Set: None
        Locator: DIMM2B
        Bank Locator: BANK3
        Type: Other
        Type Detail: Other
        Speed: 1333 MT/s
        Manufacturer: Manufacturer03
        Serial Number: 00000000
        Asset Tag: AssetTagNum3
        Part Number:                   
        Rank: Unknown

Handle 0x0017, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x000D
        Error Information Handle: Not Provided
        Total Width: 72 bits
        Data Width: 64 bits
        Size: 4096 MB
        Form Factor: DIMM
        Set: None
        Locator: DIMM3A
        Bank Locator: BANK4
        Type: Other
        Type Detail: Other
        Speed: 1333 MT/s
        Manufacturer: Manufacturer04
        Serial Number: 00000000
        Asset Tag: AssetTagNum4
        Part Number:                   
        Rank: Unknown

Handle 0x0019, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x000D
        Error Information Handle: Not Provided
        Total Width: 72 bits
        Data Width: 64 bits
        Size: 4096 MB
        Form Factor: DIMM
        Set: None
        Locator: DIMM3B
        Bank Locator: BANK5
        Type: Other
        Type Detail: Other
        Speed: 1333 MT/s
        Manufacturer: Manufacturer05
        Serial Number: 00000000
        Asset Tag: AssetTagNum5
        Part Number:                   
        Rank: Unknown
```

**Comment by ThomasWaldmann** [comment]
According to Intel's ARK, this CPU does not support ECC:

https://ark.intel.com/content/www/us/en/ark/products/37147/intel-core-i7-920-processor-8m-cache-2-66-ghz-4-80-gt-s-intel-qpi.html

But those 72bits width in dmidecode output look suspicious, strange.

So, the memtest86+ ran for at least one full pass without errors? what was the `smartctl -a` output like?

**Comment by SeanDS** [comment]
It's a cheap Kimsufi (OVH) server, so I wouldn't be sure about EEC. And the 72 bit width thing is just what I read [here](https://serverfault.com/a/810459) about interpreting the output of `dmidecode`.

I am not sure if the memory test I performed was `memtest86+` exactly. It was whatever memory test is included in the OVH rescue partition they call [`rescue64-pro`](https://docs.ovh.com/gb/en/dedicated/ovh-rescue/#using-the-rescue-mode-web-interface-rescue64-pro-only_1). It took about 30 mins to run.

The `smartctl -a` output looked all normal (at least to me):

```
$ smartctl -a /dev/sda
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-88-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Hitachi/HGST Ultrastar 7K4000
Device Model:     HGST HUS724020ALA640
Serial Number:    PN2138P2GNRJ7J
LU WWN Device Id: 5 000cca 24bc96bf9
Firmware Version: MF6OABY0
User Capacity:    2,000,398,934,016 bytes [2.00 TB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 3.0 Gb/s)
Local Time is:    Mon Oct  4 18:23:21 2021 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x80) Offline data collection activity
                                        was never started.
                                        Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever 
                                        been run.
Total time to complete Offline 
data collection:                (   24) seconds.
Offline data collection
capabilities:                    (0x5b) SMART execute Offline immediate.
                                        Auto Offline data collection on/off support.
                                        Suspend Offline collection upon new
                                        command.
                                        Offline surface scan supported.
                                        Self-test supported.
                                        No Conveyance Self-test supported.
                                        Selective Self-test supported.
SMART capabilities:            (0x0003) Saves SMART data before entering
                                        power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine 
recommended polling time:        (   1) minutes.
Extended self-test routine
recommended polling time:        ( 315) minutes.
SCT capabilities:              (0x003d) SCT Status supported.
                                        SCT Error Recovery Control supported.
                                        SCT Feature Control supported.
                                        SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0005   137   137   054    Pre-fail  Offline      -       77
  3 Spin_Up_Time            0x0007   146   146   024    Pre-fail  Always       -       475 (Average 378)
  4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       109
  5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0
  8 Seek_Time_Performance   0x0005   145   145   020    Pre-fail  Offline      -       24
  9 Power_On_Hours          0x0012   093   093   000    Old_age   Always       -       49613
 10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       109
192 Power-Off_Retract_Count 0x0032   099   099   000    Old_age   Always       -       1960
193 Load_Cycle_Count        0x0012   099   099   000    Old_age   Always       -       1960
194 Temperature_Celsius     0x0002   146   146   000    Old_age   Always       -       41 (Min/Max 16/46)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Completed without error       00%     49597         -
# 2  Short offline       Completed without error       00%     39022         -
# 3  Short offline       Completed without error       00%     39014         -
# 4  Short offline       Completed without error       00%     39014         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```

**Comment by ThomasWaldmann** [comment]
SMART looks good.

I guess you can't easily run memtest86+ without physical access or a IP KVM console, so you could boot into memtest86+ and see its vga output (no OS running at that time, just memtest86+).

Maybe you could point their support to this ticket, so they can run it.

Having repeatedly such issues quite often points to hw problems.

**Comment by SeanDS** [comment]
I doubt OVH would do such a thing for a Kimsufi line server. It's their super cheap, no-human-support offering.

What I've managed to do is run `memtester` on 14GB out of 16GB. It all passed (good for me, bad for figuring out the bug).

```
$ free
              total        used        free      shared  buff/cache   available
Mem:       16386776      611392    14899096        4928      876288    15434408
Swap:        523260           0      523260
$ memtester 14000 1
memtester version 4.3.0 (64-bit)
Copyright (C) 2001-2012 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 4096
pagesizemask is 0xfffffffffffff000
want 14000MB (14680064000 bytes)
got  14000MB (14680064000 bytes), trying mlock ...locked.
Loop 1/1:
  Stuck Address       : ok         
  Random Value        : ok
  Compare XOR         : ok
  Compare SUB         : ok
  Compare MUL         : ok
  Compare DIV         : ok
  Compare OR          : ok
  Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok         
  Block Sequential    : ok         
  Checkerboard        : ok         
  Bit Spread          : ok         
  Bit Flip            : ok         
  Walking Ones        : ok         
  Walking Zeroes      : ok         
  8-bit Writes        : ok
  16-bit Writes       : ok

Done.
```

Is there absolutely zero chance a bad connection can cause corruption? Are there any recommended SSH settings on client and server?

And is there any way to nuke backups that use the corrupted segments? I know you said that's not what `borg check --repair` does but is there any other command that might help here?

**Comment by ThomasWaldmann** [comment]
The (weak, low-level, non-cryptographic) crc32 checksums are computed in the repository code part, which runs on the borg serve side. This is what "segment entry checksum" refers to.

The (strong, high-level, cryptographic) MACs are computed at the borg client side.

**Comment by ThomasWaldmann** [comment]
Guess this is not a borg issue.
