### ISSUE TITLE
'restrict' needs to come first in authorized_keys (documentation issue)

### ISSUE THREAD

**Issue by Aicho3oi** [borgbackup/borg#5997]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue (documentation)

#### Your borg version (borg -V).
1.1.15 (client), 1.1.17 (server).

#### Operating system (distribution) and version.
Linux Mint 20.2 (client), DSM 7.0-41890 (server)

#### Hardware / network configuration, and filesystems used.
N/A (probably?)

#### How much data is handled by borg?
N/A (probably?)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
command="borg serve --restrict-to-repository /home/user/repository",restrict key type key key host

## Describe the problem you're observing.

Hi team

Well done on creating some amazing software!

I noticed a small issue that I thought should be brought to your attention. 

The documentation at https://borgbackup.readthedocs.io/en/1.1.17/deployment/hosting-repositories.html recommends this change to the ~user/.ssh/authorized_keys file as the most important piece for a correct deployment:

command="borg serve --restrict-to-repository /home/user/repository",restrict key type key key host

But it doesn't work. 

What I found is that the restrict has to come first, like this: 

restrict,command="borg serve --restrict-to-repository /home/user/repository" key type key key host

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes. I've tried moving 'restrict':

- to the front (works as expected), 
- moving it back where the documentation specifies (doesn't work, seems to cause the whole SSH key to be disregarded, such that the server requires a password to sign in, and once signed in access is not restricted in terms of commands or repositories), and 
- to the front again (works as expected again). 

I am not sure why that would make any difference; but it does. Perhaps this is a Synology quirk... Anyway I should let you know in case my experience helps others.

**Comment by ThomasWaldmann** [comment]
What's the precise sshd on your borg server? openssh? version?

**Comment by ThomasWaldmann** [comment]
https://manpages.debian.org/buster/openssh-server/authorized_keys.5.en.html#restrict

"restrict" option is there since openssh 7.2 (and is an abbreviation for a set of single-capability ssh restrictions, so that one can be more brief). I am not aware of any order requirements for the options.

Note that this has nothing to do with borg restrictions (like restrict to a specific path or repo - that has to be done within the borg serve command).

**Comment by Aicho3oi** [comment]
"sshd -V
unknown option -- V
OpenSSH_8.2p1, OpenSSL 1.1.1k  25 Mar 2021"

Yes, likewise, I wouldn't have anticipated an order requirement. Yet, apparently there is, at least in my case. Maybe it's a quirk with my system.

**Comment by ralferoo** [comment]
> #### Full borg commandline that lead to the problem (leave away excludes and passwords)
> command="borg serve --restrict-to-repository /home/user/repository",restrict key type key key host

It might not have been your problem, but I was initially tripped up because I had a space between the comma and restrict. It's possible this was your issue, as it just causes ssh to silently ignore the key...

**Comment by Aicho3oi** [comment]
Thanks for your time Thomas and Ralferoo!

It is working now. 

The order doesn't matter. 

I'm not sure what went wrong above. But, after losing a lot of hair trying to figure it out, I suspect it probably came down to permissions. 

[More detail - It was 2 months ago, so I'm a bit fuzzy, but my best guess as to what I had done - I had created a number of versions of the authorized_keys file, along my path to finding something that worked. Somewhere along the way I must have done "chmod 600 ~/.ssh/authorized_keys" on the version that finally worked (where the 'restrict' came first). But I probably hadn't done it on version where the 'restrict' came after; and so the key in that version got silently ignored. In other words I think I incorrectly attributed failure to the placement of the 'restrict' option: whereas in fact the failure was probably due to incorrect permissions].

Apologies for the muppetry!

I've made a general contribution on Bountysource. Well done again on creating some amazing software.

**Comment by ralferoo** [comment]
There's an options called StrictModes in sshd which turns off this check, but normally if any of your home directory, your .ssh directory or the authorized_keys file are world-writable then sshd ignores the file because somebody could have added additional keys into it.

**Comment by Aicho3oi** [comment]
Ahhh, that helps to explain why it's set up that way - it makes good sense. Thank you!
