### ISSUE TITLE
terminates when a non-existing directory is specified

### ISSUE THREAD

**Issue by bpereto** [borgbackup/borg#600]
`borg create` terminates when an inexisting directory to backup is specified with.

Expected:
eventually log an error and continues.

Example:
`/data` does not exist.
excludes does not contain any reference for /data.

`borg create /mnt/test.borg::Test_no_dir /boot /data --exclude-from /tmp/excludes --compression lzma,4`

Result:
`/data: [Errno 2] No such file or directory: '/data'`
echo $?
1

**Comment by ThomasWaldmann** [comment]
so, are you saying it did not backup /boot? did you check?

**Comment by bpereto** [comment]
Ok, nevermind.
Tested with additional source dirs and it exits with 1, and backup the rest of the given valid locations.

**Comment by ThomasWaldmann** [comment]
In case you wondered because of the "1": that means warning, not a total failure. See the docs about error levels.

About the output: the default log level is warning, so you only see warnings and errors.
If you want to see a list of all files/dirs, use borg create -v --list ... (0.30).
