### ISSUE TITLE
Exclude hidden files and folders, except those permitted

### ISSUE THREAD

**Issue by Firesphere** [borgbackup/borg#6000]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.15

#### Operating system (distribution) and version.

Platform: Linux ghidra 5.4.0-87-generic #98~18.04.1-Ubuntu SMP Wed Sep 22 10:45:04 UTC 2021 x86_64
Linux: Ubuntu 18.04 bionic
Borg: 1.1.15  Python: CPython 3.6.9 msgpack: 0.5.6

#### Hardware / network configuration, and filesystems used.

CIFS mount, wired network 1GBit

CIFS mount:
`cifs rw,credentials=/root/.smbcredentials,noserverino,_netdev,nofail`

#### How much data is handled by borg?

About 100G

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create /path/to/repo::{now } ~ --exclude-from exclude_patterns.txt --exclude-caches -p -v

Exclude patterns file:
```
+ /home/firesphere/.ssh
+ /home/firesphere/.gnupg
- /home/firesphere/.*
- /home/firesphere/stack/
- /home/firesphere/Vaults/
```
## Describe the problem you're observing.

I can not exclude hidden files/folders (starting with a `.`)

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Run the same command, same thing happens, dot-prefixed files are included

#### Include any warning/errors/backtraces from the system logs

Not applicable

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/help.html

please read the docs about the difference between the older `--exclude` mechanism and the newer `--patterns` mechanism, syntax is different. See also the examples.
