### ISSUE TITLE
[Web UI] Borg Backup Server

### ISSUE THREAD

**Issue by Pheggas** [borgbackup/borg#6007]
Hello. According to this site (http://www.borgbackupserver.com/) you're developing some sort of Web UI for BorgBackup. But the latest update was written in December 2019, right? 

Is it a dead project or what? Didn't find any update on it after that date.

**Comment by yash-fn** [comment]
I believe that is a separate project with a separate team actually.

**Comment by ThomasWaldmann** [comment]
@yash-fn is correct, you have to ask them / there.
