### ISSUE TITLE
process stopped with org.crypto.file_integrity.FileIntegrityError: File failed integrity check: /root/.cache/borg/

### ISSUE THREAD

**Issue by andrewufrank** [borgbackup/borg#6010]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

bug

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create -ps siam2::brugg_20211014stFolder /stFolder

## Describe the problem you're observing.
process stops with error 
org.crypto.file_integrity.FileIntegrityError: File failed integrity check: /root/.cache/borg/

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes. 
it occurs everytime till the /root/.cache/borg directory is emptied.
i assume that the action to delete the cache should be automatic in this case, because I believe that the 
error occured because moved the backup device between cpus (i.e. I assume that : worked on a, worked on b, worked again on a -> error with cache state. )

thank you for a wonderful tool!

**Comment by andrewufrank** [comment]
there was a file name, which i have not copied. 
i will run the checks once the backup is completed.  - you did realize I run this on a raspi 4 with a debian 64 bit OS, perhaps this has contributed to the problem. 
why would it not be a good idea to delete the cache in such cases automatically? It was not a difficult issue for me but I guess some newbies might be confused and not know what to do. I like borg and my interest is only to make it as easy to use as possible.
thank you for all the good work!

**Comment by ThomasWaldmann** [comment]
Hmm, ok, i take the memtest86+ back, guess than won't run on a raspi. So you need to find a working memory tester for that.

**Comment by andrewufrank** [comment]
thank you for your help - smartctl seems not to work either. this box usually runs without fault, thus I take it is a fluke. if it recurring, i will go to the pain to make memtest86 and smartctl to check. today I do not have the time. 
i understand your argument and side with it - if one can be certain of the cause of the problem; i had the suspicion that the cause was the sequence of switching the backup device between computers. you seem to indicate, that this is not the cause - and you understand the internal workings of borg, which I do not. I appreciate the information.
