### ISSUE TITLE
binascii.Error: Non-hexadecimal digit found when running borg since today

### ISSUE THREAD

**Issue by NielsH** [borgbackup/borg#6031]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.17
#### Operating system (distribution) and version.
Client: Debian 9  
Server: Debian 10

#### Hardware / network configuration, and filesystems used.
N/A
#### How much data is handled by borg?
3TB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg check --last 1

## Describe the problem you're observing.

Hi,

Since yesterday the backups of one of our systems are failing, after being working for months correctly. We are using borgmatic and we see it does a borg prune commands which fails. We tried the command manually as well, and it also fails. We can also see the error when we run: `borg check --last 1`

The error output is:
```
Enter passphrase for key ssh://borg@<snip>:22/./bbe199ea-7247-4aa4-986e-9e37317d0521:
Local Exception
Traceback (most recent call last):
  File "borg/archiver.py", line 4703, in main
  File "borg/archiver.py", line 4635, in run
  File "borg/archiver.py", line 177, in wrapper
  File "borg/archiver.py", line 351, in do_check
  File "borg/archive.py", line 1249, in check
  File "borg/archive.py", line 1642, in rebuild_refcounts
  File "borg/archive.py", line 268, in add
  File "borg/archive.py", line 285, in flush
  File "borg/archive.py", line 1440, in add_callback
  File "borg/crypto/key.py", line 370, in encrypt
  File "borg/crypto/nonces.py", line 73, in ensure_reservation
  File "borg/crypto/nonces.py", line 27, in get_local_free_nonce
binascii.Error: Non-hexadecimal digit found

Platform: Linux storage01 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64
Linux: debian 9.13
Borg: 1.1.17  Python: CPython 3.7.11 msgpack: 0.5.6.+borg1
PID: 26682  CWD: /home/niels
sys.argv: ['borg', 'check', '--last', '1']
SSH_ORIGINAL_COMMAND: None
```

Is there a way for us to resolve this? Or do we nee to re-initialize the backup repo and start fresh?

**Comment by ThomasWaldmann** [comment]
There is a file `.config/security/REPOID/nonce` on the machine that runs the borg client and it seems this file is corrupted on your machine (this should be an ASCII text file with a hex number in it).

As long as your repo is in a trusted good state, I'ld guess you could just delete the client side file and it will trust the nonce it gets from the repo.

**Comment by ThomasWaldmann** [comment]
Maybe also try to find out why this file is corrupted.

**Comment by NielsH** [comment]
Thanks. Afte removing the file backup succeeded again!
A few hours after my post the raid controller reported a disk failure. Probably something happened there that caused the corruption.

**Comment by ThomasWaldmann** [comment]
Yeah. OTOH, if you have redundant disks and one of them is failing, that should not cause corruption as long as the other disk(s) still have the data. So this is still weird. Maybe check RAM (memtest86+) and raid controller also.
