### ISSUE TITLE
Sending mail from automated borgbackup bash script 

### ISSUE THREAD

**Issue by elhananjair** [borgbackup/borg#6033]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION 

#### Your borg version (borg -V).
1.1.17
#### Operating system (distribution) and version.
Fedora Server 33
#### Hardware / network configuration, and filesystems used.
FS: BTRFS 
#### How much data is handled by borg?
More than 100GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
#!/bin/sh

#borg automated backup ENV variable check

export BORG_REPO=*************

# Password for repo
export BORG_PASSPHRASE='************'

#Error handling 
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap "echo $( date ) Backup interrupted >&2; exit 2" INT TERM

info "Starting Backup"

#borg create
borg create --verbose --filter AME --list --stats --show-rc --compression lz4 ::'{hostname}-{now}' /var/www/html/nextcloud/
backup_exit=$?

info "Pruning repository"

borg prune --list --prefix '{hostname}-' --show-rc --keep-within=1d
prune_exit=$?

global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
if [ ${global_exit} -eq 0 ]; then 
info "Backup and Prune finished successfully"
**echo "Backup and Prune finished successfully" | mail -s "Backup Log" myemail@gmail.com**
elif [ ${global_exit} -eq 1 ]; then
**echo "Back and/or Prune finished with warrings" | mail -s "Backup Log" myemail@gmail.com**
info "Backup and/or Prune finished with warrings"
else
**echo "Backup and/or Prune finished with errors" | mail -s "Backuo Log" myemail@gmail.com**
info "Backup and/or Prune finished with errors"
fi

exit ${global_exit}


```

## Describe the problem you're observing.
I am using sendmail package to send an email from script and I am not receiving an email after this script executed.
#### Include any warning/errors/backtraces from the system logs
No warning, a service executing this script doesn't raise any warnings

**Comment by ThomasWaldmann** [comment]
Well, guess this is not a borg problem, but a problem in your mail configuration.

I usually use cron to execute backup scripts and it is a standard feature of cron to send stdout of cronjobs to the cronjob owner (default) or to a configured MAILTO address. For that to work, one usually has a local mail server running that sends mail via an internet smarthost (which usually requires some configuration for authentication and TLS).

**Comment by elhananjair** [comment]
> Well, guess this is not a borg problem, but a problem in your mail configuration.
> 
> I usually use cron to execute backup scripts and it is a standard feature of cron to send stdout of cronjobs to the cronjob owner (default) or to a configured MAILTO address. For that to work, one usually has a local mail server running that sends mail via an internet smarthost (which usually requires some configuration for authentication and TLS).

I have already configured my server to send mail from CLI (by installing these packages in fedora: sendmail sendmail-cf mailx s-nail). I have tried that from CLI and it worked fine I got an email sent from CLI. Now I wanted the same command to work in bash script that am executing using **systemd timer** daily. 
So @ThomasWaldmann I was expecting this command embedded in automated borgbackup bash script to be executed the same way when I it run directly from CLI. Thanks

**Comment by ThomasWaldmann** [comment]
Well, borg does not do anything with email, so you for sure do not have a borg problem.

I'll keep this open for a while, in case somebody can help you with systemd, but not for too long as this issue tracker is not for generic email or systemd configuration help.

**Comment by elhananjair** [comment]
> Well, borg does not do anything with email, so you for sure do not have a borg problem.
> 
> I'll keep this open for a while, in case somebody can help you with systemd, but not for too long as this issue tracker is not for generic email or systemd configuration help.

yes its not borg problem, I just wanted to raise this question in case someone help me with that. Thanks @ThomasWaldmann.

**Comment by elhananjair** [comment]
> Well, borg does not do anything with email, so you for sure do not have a borg problem.
> 
> I'll keep this open for a while, in case somebody can help you with systemd, but not for too long as this issue tracker is not for generic email or systemd configuration help.

Thanks @ThomasWaldmann I fixed it already and forgot to close this issue, am sorry.
