### ISSUE TITLE
Missing progress output for repository checks via borg serve

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#6038]
I'm getting progress info for archives but not for repository checks.

**Comment by sophie-h** [comment]
```
$ borg --version
borg 1.1.17
```

Tried it with `--debug` but now also

```
$ borg check --info --progress --log-json <repo>
```

It works for local repos, just not via borg serve.

**Comment by sophie-h** [comment]
Also, what has the `--info` part to do with this?

**Comment by infectormp** [comment]
@sophie-h RTFM https://borgbackup.readthedocs.io/en/stable/usage/general.html#logging

**Comment by sophie-h** [comment]
I hope it's okay that I have just blocked @infectormp

**Comment by sophie-h** [comment]
TLDR; of Hetzner support answer: Some logging output is currently suppressed by Hetzner. The problem should be solved within some weeks.

Closing because not a borg problem.
