### ISSUE TITLE
check --max-duration: remember position more frequently

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#6039]
Does the ` --max-duration` option for checks also support continuation after connection loss or should I just run successive ` --max-duration` checks to cover potential connection loss or other interruptions?

**Comment by ThomasWaldmann** [comment]
When max_duration time is reached while doing the repo check, it will save how far it got to the repo config and stop.
It will **not** save progress before that.

So, if only sometimes a partial check is interrupted it would still progress (by the ones which did not get interrupted).
If all checks would get interrupted before they reach max_duration, it would never complete.

**Comment by sophie-h** [comment]
I would probably emulate something similar to snapshots for `create`. Just run consecutive checks with `--max-duration` of 30 minutes to cover connection losses etc. If that's out of the scope for borg this issue can be closed.

**Comment by ThomasWaldmann** [comment]
Well, borg it could just write the current position to the config file more often (like it does at the end).

**Comment by sophie-h** [comment]
Yes, I think having 'automatic' continuation support for more features would be great. While I have quite a fast and reliable internet connection, interruptions still happen. I think it would make peoples lives much easier :)

**Comment by ThomasWaldmann** [comment]
@sophie-h for ` borg create` there are checkpoints, but borg is not "continuing" in that case, it is just avoiding uploading committed stuff again (and rolling back anything not committed). So even for unstable connections, it should be possible to finish a backup when doing multiple tries.

**Comment by sophie-h** [comment]
> for ` borg create` there are checkpoints, but borg is not "continuing" in that case

Sure, but I added automatic retries on disconnect for remote backups to Pika Backup a while ago. Together with checkpoints, this seems to work quite well.
