### ISSUE TITLE
not understanding the numbers #897846...

### ISSUE THREAD

**Issue by blueray453** [borgbackup/borg#6041]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

**Not sure how to do it.**

#### Your borg version (borg -V).

borg 1.1.17

#### Operating system (distribution) and version.

Linux Mint 20.2

#### Hardware / network configuration, and filesystems used.

EXT4

#### How much data is handled by borg?

4TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
% borg --info --progress create --exclude='lost+found' --exclude='.Trash-1000' --list --stats /media/blueray/WDPurple8TB/borg-backup-red::{hostname}-{now:%Y-%m-%d_%H:%M:%S} /media/blueray/WDRed
Creating archive at "/media/blueray/WDPurple8TB/borg-backup-red::{hostname}-{now:%Y-%m-%d_%H:%M:%S}"
A /media/blueray/WDRed/lost+found/#89784625/blueray/WDRed/lost+found/#89784625
A /media/blueray/WDRed/lost+found/#89784626/blueray/WDRed/lost+found/#89784626
A /media/blueray/WDRed/lost+found/#89784627/blueray/WDRed/lost+found/#89784627
A /media/blueray/WDRed/lost+found/#89784628/blueray/WDRed/lost+found/#89784628
A /media/blueray/WDRed/lost+found/#89784629dia/blueray/WDRed/lost+found/#89784629
A /media/blueray/WDRed/lost+found/#89784630dia/blueray/WDRed/lost+found/#89784630
A /media/blueray/WDRed/lost+found/#89784632dia/blueray/WDRed/lost+found/#89784632
A /media/blueray/WDRed/lost+found/#89784633
A /media/blueray/WDRed/lost+found/#89784634dia/blueray/WDRed/lost+found/#89784634
A /media/blueray/WDRed/lost+found/#89784635dia/blueray/WDRed/lost+found/#89784635
A /media/blueray/WDRed/lost+found/#89784636edia/blueray/WDRed/lost+found/#89784636
A /media/blueray/WDRed/lost+found/#89784637edia/blueray/WDRed/lost+found/#89784637
A /media/blueray/WDRed/lost+found/#89784638edia/blueray/WDRed/lost+found/#89784638
A /media/blueray/WDRed/lost+found/#89784639edia/blueray/WDRed/lost+found/#89784639
A /media/blueray/WDRed/lost+found/#89784640edia/blueray/WDRed/lost+found/#89784640
A /media/blueray/WDRed/lost+found/#89784641edia/blueray/WDRed/lost+found/#89784641
A /media/blueray/WDRed/lost+found/#89784642edia/blueray/WDRed/lost+found/#89784642
A /media/blueray/WDRed/lost+found/#89784643edia/blueray/WDRed/lost+found/#89784643
A /media/blueray/WDRed/lost+found/#89784644edia/blueray/WDRed/lost+found/#89784644
A /media/blueray/WDRed/lost+found/#89784645
A /media/blueray/WDRed/lost+found/#89784646edia/blueray/WDRed/lost+found/#89784646
A /media/blueray/WDRed/lost+found/#89784647edia/blueray/WDRed/lost+found/#89784647
A /media/blueray/WDRed/lost+found/#89784648edia/blueray/WDRed/lost+found/#89784648
A /media/blueray/WDRed/lost+found/#89784649edia/blueray/WDRed/lost+found/#89784649
A /media/blueray/WDRed/lost+found/#89784650edia/blueray/WDRed/lost+found/#89784650
A /media/blueray/WDRed/lost+found/#89784651
A /media/blueray/WDRed/lost+found/#89784652edia/blueray/WDRed/lost+found/#89784652
A /media/blueray/WDRed/lost+found/#89784653ia/blueray/WDRed/lost+found/#89784653
A /media/blueray/WDRed/lost+found/#89784669
A /media/blueray/WDRed/lost+found/#89784671smail/WDRed/lost+found/#89784671
A /media/blueray/WDRed/lost+found/#89784672
A /media/blueray/WDRed/lost+found/#89784677smail/WDRed/lost+found/#89784677
d /media/ismail/WDRed/lost+found/#89784695
```

## Describe the problem you're observing.

I am trying to backup from one HDD to another in my Machine.

What I am trying to do is exclude `/media/blueray/WDRed/lost+found` and `/media/blueray/WDRed/.Trash-1000`

I am not understanding whether the command has excluded `.Trash-1000` & `lost+found` or it is doing something else.

What does `A` mean? What does `d` mean? What are the numbers `#89784..`?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Used command `% borg --info --progress create --exclude='lost+found' --exclude='.Trash-1000' --list --stats /media/blueray/WDPurple8TB/borg-backup-red::{hostname}-{now:%Y-%m-%d_%H:%M:%S} /media/blueray/WDRed` in my machine.

#### Include any warning/errors/backtraces from the system logs

**Not sure how to do it.**

**Comment by blueray453** [comment]
I found most of the issues in https://borgbackup.readthedocs.io/en/stable/usage/create.html#item-flags

However, not still understanding the numbers `#897846...`

**Comment by ThomasWaldmann** [comment]
Do not mix --list and --progress.

**Comment by ThomasWaldmann** [comment]
About excludes, please read the docs. If you correctly match, it'll work.

**Comment by blueray453** [comment]
Thank you very much.
