### ISSUE TITLE
How to show `borg create --list` output to terminal but save any WARNING , ERROR , CRITICAL log to file.

### ISSUE THREAD

**Issue by blueray453** [borgbackup/borg#6042]
I am using `borg 1.1.17`.

How to show `borg create --list` output to terminal but save any WARNING , ERROR , CRITICAL log to file.

I have tried `borg --warning create --list --exclude='lost+found' --exclude='.Trash-1000' /media/blueray/WDPurple8TB/borg-backup-purple::{hostname}-{now:%Y-%m-%d_%H:%M:%S} /media/blueray/WDPurple 2>> /media/blueray/WDPurple8TB/borg-backup-purple.log` , but it is sending everything to the `borg-backup-purple.log` file (keeping the terminal empty).

**Comment by ThomasWaldmann** [comment]
You can configure borg's logging (see docs), but by default, it only emits log output on stderr.

**Comment by blueray453** [comment]
What should the config file look like if I want to redirect `borg create --list` to stdout and `borg --warning` output to stderr?

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/general.html?highlight=logging#logging

I thought we had a link there to the python docs about the logging configuration file format...

Ah, it is a bit below that section in the docs: there, "INI" is a link, click it - or look at the example:
```
BORG_LOGGING_CONF
When set, use the given filename as INI-style logging configuration. A basic example conf can be found at docs/misc/logging.conf.
```

**Comment by blueray453** [comment]
Thank you very much.

**Comment by blueray453** [comment]
The config file in `/home/blueray/.config/borg/logging.conf` looks like:

```
[loggers]
keys=root

[handlers]
keys=logfile

[formatters]
keys=logfile

[logger_root]
level=NOTSET
handlers=logfile

[handler_logfile]
class=FileHandler
level=INFO
formatter=logfile
args=('/home/blueray/Desktop/borg.log', 'w')

[formatter_logfile]
format=%(asctime)s %(levelname)s %(message)s
datefmt=
class=logging.Formatter

```
I ran:
```
$ BORG_LOGGING_CONF=/home/blueray/.config/borg/logging.conf
$ borg --warning --progress --show-rc create --show-version --stats --exclude='/media/blueray/WDPurple/lost+found' --exclude='/media/blueray/WDPurple/.Trash-1000' /media/blueray/WDPurple8TB/borg-backup-purple::{hostname}-{now:%Y-%m-%d_%H:%M:%S} /media/blueray/WDPurple
```

The information is from 
https://mail.python.org/pipermail/borgbackup/2016q1/000166.html 
https://mail.python.org/pipermail/borgbackup/2016q2/000223.html

It does not create a log file in `/home/blueray/Desktop/borg.log`.

What might be the issue here?

**P.S.** I created the repository using `borg init --encryption=none /media/blueray/WDPurple8TB/borg-backup-purple`. So, I am not using any password. I am just saying this in case I need to make any change to the `logging.conf` file or use any more environment variables.

**Comment by jdchristensen** [comment]
I'm guessing you have to `export` the environment variable.
