### ISSUE TITLE
Borg version 1.1.15 outdated and can't Install version 1.1.17 on Ubuntu 18.04 and 20.04

### ISSUE THREAD

**Issue by ali-yahyaoui** [borgbackup/borg#6043]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
1.1.15
#### Operating system (distribution) and version.
Ubuntu 18.04 and Ubuntu 20.04
## Describe the problem you're observing.
Failed to create/acquire the lock /var/borg/repo/lock.exclusive (timeout).
#### Can you reproduce the issue? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
When doing a backup on many servers with the same version, I had received the error described below, I had tried to break-lock as mentioned in here in issue [#3191](https://github.com/borgbackup/borg/issues/3191#issuecomment-338160680) and the same issue. I notice that the borg version (1.1.15) is outdated as mentioned in these [docs ](https://repology.org/project/borgbackup/versions), the issue is can't upgrade the borg version to the latest 1.1.17

**Comment by ThomasWaldmann** [comment]
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup/+packages?field.name_filter=&field.status_filter=published&field.series_filter=focal

you can get a more recent borg from the maintainer's ppa.
