### ISSUE TITLE
borg failed to create/acquire the lock.exclusive

### ISSUE THREAD

**Issue by ali-yahyaoui** [borgbackup/borg#6047]
When running a backup script through a scheduled Jenkins job on many servers, I receive the following error on `borg create` command:

    Failed to create/acquire the lock /path/to/repo/lock.exclusive (timeout).
    terminating with error status, rc 2

OS : Ubuntu 18.04 Bionic and Ubuntu 20.04 Focal
Borg version: 1.1.15
PS: I had tried some solution like `borg break-lock`, and upgrade borg to the latest version 1.1.17 and same problem.

**Comment by ThomasWaldmann** [comment]
If you access the same repo from multiple clients at the same time, the first one will succeed and the second+ one will encounter a lock.

The default waiting time for the repo maybe getting unlocked is rather short (iirc 2 seconds or so), but if you like you can make it wait for longer (e.g. `--max-lock-wait 3600`).

`break-lock` is only for manual and very careful usage, see the docs.

**Comment by dusanmsk** [comment]
Hi, I have similar problem, but my situation is different.

I have 2 separate repos (original and clone made by 'btrfs snap create') - but still can't do things in parallel on both repos - Failed to create/acquire the lock /root/.cache/borg/8d02c6736b2bdfb47c2fcd04b440fc1215601d15acb53b5122ddd4859fcad8eb/lock.exclusive (timeout).

I understand that it is safer to lock by archive id than archive path, especially in network environment, but this is annoying when I want to test something on the copy and in the same time work on 'production' archive in parallel.

**Comment by ThomasWaldmann** [comment]
@dusanmsk you can only do 1 operation in a repo at the same time. a repo is identified by its unique repoid (which is also used to make up paths to have a unique cache per repo). if you make a copy or a snapshot of a repo, you have the same id in the copy/snapshot, so it is not unique any more.

So either don't do that or (hack!) modify the id in the copy, so it is unique again.

**Comment by seaniedan-flwls** [comment]
`--lock-wait 360`
in borg 1.2.4, to wait 360/60= 6 minutes.
