### ISSUE TITLE
Clarify if positional arguments are allowed in-between since Python 3.7+

### ISSUE THREAD

**Issue by savchenko** [borgbackup/borg#6054]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

Borg 1.1.16

#### Operating system (distribution) and version.

Debian 11, Python 3.9.2

#### Hardware / network configuration, and filesystems used.

N/A

#### How much data is handled by borg?

N/A

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

N/A

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

`man borg`, NOTES section states:

> Borg  only  supports taking options (-s and --progress in the example) to the left or right of
       all positional arguments (repo::archive and path in the example), but not in between them
   [...]
   This is due to a problem in the argparse module: https://bugs.python.org/issue15112

Bug #15112 references [ArgumentParser.parse_intermixed_args()](https://docs.python.org/3/library/argparse.html#intermixed-parsing) as the proposed fix. 

#### Question
Is the original warning still applicable for Borg v1.1.16 running on Python 3.9?

**Comment by ThomasWaldmann** [comment]
Well, just try it out?

I don't think I want to make the docs more complicated by making them python version specific.

**Comment by ThomasWaldmann** [comment]
Quote from the parse_intermixed_args docs: """These parsers do not support all the argparse features, and will raise exceptions if unsupported features are used. In particular, subparsers, argparse.REMAINDER, and mutually exclusive groups that include both optionals and positionals are not supported."""

Not sure how to parse these docs, but borg uses:
- subparsers (all over the place)
- argparse.REMAINDER (`borg with-lock ...`)

**Comment by ThomasWaldmann** [comment]
Guess we can't use that.
