### ISSUE TITLE
Show SSH output if the connection is closed

### ISSUE THREAD

**Issue by Timmmm** [borgbackup/borg#6059]
In certain situations (e.g. if you try to backup over SSH to a host that doesn't have `borg` on its PATH) you get this not very helpful error message:

    Connection closed by remote host. Is borg working on the server?

Even with `--verbose` it doesn't print any additional detail. If I go to `--debug` it shows the command it is running at least:

```
using builtin fallback logging configuration
35 self tests completed in 0.10 seconds
SSH command line: ['ssh', 'tim@sw01', 'borg', 'serve', '--umask=077', '--debug']
Connection closed by remote host. Is borg working on the server?
```

But still no actual error message. If I actually run the command the issue is obvious:

```
 ~ ssh tim@sw01 borg serve --umask=077 --debug
bash: borg: command not found
```

In this case `borg` was added to `.bashrc` but it's not in the global `PATH`.

It would be nice if Borg would print the output from SSH if it fails to connect to the remote Borg process.

**Comment by ThomasWaldmann** [comment]
Hmm, just tried to reproduce, but I got this:
```
(borg-env) tw@mba2020 borg % borg -V
borg 1.1.18.dev93+g5ccbd199.d20220130

(borg-env) tw@mba2020 borg % borg info tw@localhost:foobar
(tw@localhost) Password:
Remote: zsh:1: command not found: borg
Connection closed by remote host. Is borg working on the server?
```

**Comment by Timmmm** [comment]
Hmm weird. Well I'll close it and reopen if it happens again.

**Comment by jen-w** [comment]
For posterity, I faced this issue and fixed it by specifying exact path of borg on my remote machine using `--remote-path` command line option.

**Comment by ThomasWaldmann** [comment]
@jen-w That can be avoided by putting `borg` in some directory listed in `$PATH`. If it is no system package, `/usr/local/bin` is a good place.
