### ISSUE TITLE
trailing slash oddities

### ISSUE THREAD

**Issue by Pyrohh** [borgbackup/borg#606]
system info:
```
Platform: OpenBSD orchid.home 5.9 GENERIC.MP#1854 amd64 amd64
Borg: 0.30.0 Python: CPython 3.4.4
```

Trailing slashes in the path passed to `borg init` seem to matter later when running `borg create`. This should help illustrate the problem:

```
$ mkdir /tmp/backup
$ borg init /tmp/backup/
$ borg create /tmp/backup::test ~/src
Warning: The repository at location /tmp/backup was previously located at /tmp/backup/
Do you want to continue? [yN]
```

Note how `/tmp/backup/` was specified in `borg init`, but `/tmp/backup` (no trailing slash) was used in borg create. The problem is avoided if the pathname passed verbatim to `borg init` is used instead:
```
$ borg create /tmp/backup/::test ~/src
```

---

I'm not sure if this is by design, but I certainly found it surprising given that trailing slashes generally have no importance in Bourne-shell derivatives and the programs run within them.

**Comment by ThomasWaldmann** [comment]
yes, it's not too clever yet with that check.
but as long as you are consistent (always give same repo path), it is no problem.

**Comment by ThomasWaldmann** [comment]
see also: https://github.com/jborg/attic/issues/297

**Comment by ThomasWaldmann** [comment]
When fixing this, also check behaviour of relative pathes and pathes containing `.` and `..`.

**Comment by Pyrohh** [comment]
> When fixing this, also check behaviour of relative pathes and pathes containing . and ...

Maybe we could pass the path argument through [`os.path.normpath()`](https://docs.python.org/2/library/os.path.html#os.path.abspath)?

**Comment by ThomasWaldmann** [comment]
@Pyrohh good idea, i am just implementing that.

it won't fix all strange effects (like using absolute vs. relative pathes), but that can't be done easily as the path could be remote also, so os.path.abspath() does not help here.
