### ISSUE TITLE
borg list --format: improve docs, extend placeholders

### ISSUE THREAD

**Issue by xeruf** [borgbackup/borg#6061]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.

borg version 1.1.17

## Describe the problem you're observing.

The format for `borg-list --format` is barely documented:
There are keys, and from the example I can see that adding `:N` will right-pad the key to length `N`. But what about trimming or left-padding or...? Currently I can't even know what is supported.

Furthermore, the default given applies only to file listings. The default for repo listing should be given as well, which might prevent confusion such as in #3399.

Finally, I would like some extra keys for repo listing:
- size of the archive files (compress/uncompressed) - ignore deduplication for this
- number of files in the archive

**Comment by ThomasWaldmann** [comment]
Docs: https://borgbackup.readthedocs.io/en/stable/usage/list.html

Default: as there is only one borg list command that covers repos as well as archives, the help string in the argparser needs to mention both defaults.

Default formats (1.1-maint):
```
archive: "{mode} {user:6} {group:6} {size:8} {mtime} {path}{extra}{NL}"
repo: "{archive:<36} {time} [{id}]{NL}"
```

Formatting options / syntax: guess this is standard python f-string formatting.

Additional keys for repo listing:
- 1.1-maint: not available, neither from manifest nor from archive metadata
- master has size, csize, nfiles, size_parts, csize_parts,nfiles_parts in archive metadata

**Comment by ThomasWaldmann** [comment]
Working on this needs 2 PRs:
- one for the help string and docs fix, needed for master and later as backport for 1.1-maint
- one for adding placeholders for master only

**Comment by kaushik853** [comment]
Hey,
can i take up this issue?

**Comment by ThomasWaldmann** [comment]
@kaushik853 sure! in general, all open issue can be taken.

**Comment by xeruf** [comment]
This is my cli workaround for displaying archives with their size in the meantime, but it is abysmally slow :/
```sh
sizesum() {
    borg list ::$1 "--format={${2}size}{NL}" |
		paste -s -d'+' | bc | numfmt --to=iec
}
sizes() {
    p=$1
    echo $p: all $(sizesum $p) compressed $(sizesum $p "c") deduplicated $(sizesum $p "dc")
}
borg list --format="{name}{NL}" |
	while read p
	do sizes $p
	done
```
