### ISSUE TITLE
globally review string formatting

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6069]
see #6063 and #6064.

it could be that such issues are more widespread than just at that single place, search and fix all of them (if any).

**Comment by hexagonrecursion** [comment]
This sounds like a job for [semgrep](https://semgrep.dev). I'll give this one a try

**Comment by hexagonrecursion** [comment]
Sorry. Life. Busy. I don't know when I will be able to work on this.

**Comment by ThomasWaldmann** [comment]
Did manual review and didn't find any other problems.
