### ISSUE TITLE
Strange code in test_unknown_mandatory_feature_in_cache

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6070]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
latest master (e8ff51b0f90b994b3931722a4aaca2c57130126d)

## Describe the problem you're observing.

path_prefix is a str, but it is only used in a boolean context in this test. If it is supposed to be a bool, then it has a strange type and a confusing name.

**If the type is correct, the intention is probably to pass it to the code under test, but this does not happen.**

https://github.com/borgbackup/borg/blob/e8ff51b0f90b994b3931722a4aaca2c57130126d/src/borg/testsuite/archiver.py#L1848-L1887

**Comment by ThomasWaldmann** [comment]
It is a string. In Python, strings are truthy if they are not empty.

**Comment by ThomasWaldmann** [comment]
Yeah, the code was strange, fixing it...
