### ISSUE TITLE
disk space usage of repository

### ISSUE THREAD

**Issue by vot4anto** [borgbackup/borg#6077]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg -V
borg 1.1.17

#### Operating system (distribution) and version.
Ubuntu 18.04

## Describe the problem you're observing.

If I check the disk space usage of the repository using the command: borg info  The Deduplicated size is nearly the disk space of the filesystem:

```
# borg info gitlabgem/repo

------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:               29.53 TB             21.84 TB            599.72 GB

                       Unique chunks         Total chunks
Chunk index:                  280220             10134931

# du -sh gitlabgem/repo
574G    gitlabgem/

```

So by now no problem, but If I check the deduplicated size of each archive of the repository and after sum this deduplicated_size the total space is not the same of the the Deduplicated size of the repository.

```
for f in $(borg list gitlabgem/repo | cut -f 1  -d " ") ; do borg info --json gitlabgem/repo::$f| grep deduplicated_size ; done
                "deduplicated_size": 2663,
                "deduplicated_size": 29811695480,
                "deduplicated_size": 646,
                "deduplicated_size": 6112373360,
                "deduplicated_size": 646,
                "deduplicated_size": 9562128899,
                "deduplicated_size": 2647,
                "deduplicated_size": 19130911976,
                "deduplicated_size": 646,
                "deduplicated_size": 2167681228,
                "deduplicated_size": 647,
                "deduplicated_size": 2629459135,
                "deduplicated_size": 646,
                "deduplicated_size": 3440143335,
                "deduplicated_size": 647,
                "deduplicated_size": 3109414718,
                "deduplicated_size": 647,
                "deduplicated_size": 13686167279,
                "deduplicated_size": 646,
                "deduplicated_size": 4028028036,
                "deduplicated_size": 647,
                "deduplicated_size": 1728565594,
                "deduplicated_size": 647,
                "deduplicated_size": 3067417398,
                "deduplicated_size": 646,
                "deduplicated_size": 3622871495,
                "deduplicated_size": 647,
                "deduplicated_size": 5573163121,
                "deduplicated_size": 647,
                "deduplicated_size": 3842082410,
                "deduplicated_size": 2664,
                "deduplicated_size": 5082016870,
                "deduplicated_size": 647,
                "deduplicated_size": 3625429879,
                "deduplicated_size": 649,
                "deduplicated_size": 2113671042,
                "deduplicated_size": 647,
                "deduplicated_size": 2366604358,
                "deduplicated_size": 646,
                "deduplicated_size": 1699523224,
                "deduplicated_size": 649,
                "deduplicated_size": 1834928068,
                "deduplicated_size": 647,
                "deduplicated_size": 2754468459,
                "deduplicated_size": 646,
                "deduplicated_size": 2063147157,
                "deduplicated_size": 646,
                "deduplicated_size": 2535972550,
                "deduplicated_size": 647,
                "deduplicated_size": 6967653531,

```
The sum is 142555540805

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, I check on more than one repository

**Comment by enkore** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/info.html?

> Please note that the deduplicated sizes of the individual archives do not add up to the deduplicated size of the repository (“all archives”), because the two are meaning different things:

> This archive / deduplicated size = amount of data stored ONLY for this archive = unique chunks of this archive. All archives / deduplicated size = amount of data stored in the repo = all chunks in the repository.

**Comment by vot4anto** [comment]
So also if I delete one o more archive the total size of the repo can be the same? And also if i do the recreate operation?

**Comment by enkore** [comment]
If you delete a single archive you'd expect the size of the repo to go down by the deduplicated size of that particular archive, yes.

What happens after invoking recreate depends greatly on the options used.

**Comment by vot4anto** [comment]
I use recreate to delete large files from archive that don't be to backup but the total size of repo was not affected.
I see there is a default size for the chunks, can I adjust this size in case of lots small files and on other case of few bigger files to backup?

**Comment by ThomasWaldmann** [comment]
@vot4anto If the unwanted files you remove via recreate happen to be contained in multiple archives (and thus the content chunks are referenced by multiple archives), the space will be freed when the last reference is removed (== you have removed the unwanted files from **all** archives that contain them).

**Comment by vot4anto** [comment]
Ok, I undestand, thanks for the support
