### ISSUE TITLE
Warning: Attempting to access a previously unknown unencrypted repository!

### ISSUE THREAD

**Issue by rikvdh** [borgbackup/borg#608]
Hi,

We are trying to automate borg deployment and addition of backup nodes via Ansible. The borg repository is created by the borg-server, and when the borg-client connects (via SSH) to borg for the first time Borg gets stuck at `Warning: Attempting to access a previously unknown unencrypted repository!`, and requires interaction from the user.

But in our case, the backups are ran from cron and no user interaction is possible, therefore Borg will be stuck forever.

Is there a command line option to override this warning? The documentation doesn't say anything on this.

Thanks,

Rik

**Comment by ThomasWaldmann** [comment]
See there:

http://borgbackup.readthedocs.org/en/stable/usage.html#environment-variables

Use these carefully. Especially if you use encryption, overriding this warning creates a security risk.

**Comment by claudissimus** [comment]
Hi,

I have the same issue on a local machine - when trying to backup to a repository via cron I get the message `Warning: Attempting to access a previously unknown unencrypted repository`. When I call the script manually, it works fine. 
Where does borg store the info whether a repository is known or unknown ? 

Thank you.

**Comment by enkore** [comment]
> Where does borg store the info whether a repository is known or unknown ? 

In the cache ($HOME/.cache/borg)

**Comment by claudissimus** [comment]
Cron runs in a different context indeed. 
Can I safely just copy the borg cache dir to the other user's home or is there another recommended way to make a repository known to borg (besides forcing auto-yes via environment as suggested above - a solution I would like to circumvent) ? 
Thanks again.

**Comment by enkore** [comment]
- Can copy the cache dir (specifically: ~/.cache/borg/[repo id]/ ; the repo id is in the "config" file in the repository)
- Could run the script once with su/sudo to get things started
- Run once with the yes-env-var

**Comment by bjorkegeek** [comment]
Borg uses the environment variable $HOME to find the home directory. This is not set in the cron shell environment. Try adding the line
`export HOME=/root`
to your backup script, before running borg.

**Comment by nizedk** [comment]
Running my script, now with $HOME env set, did not work as intended. I had to login as the user, run the script, confirm, and log out again - then it worked using cron.

**Comment by ThomasWaldmann** [comment]
@nizedk what is `not as intended` precisely?

**Comment by dgasaway** [comment]
Personal experience: init and initial backups run from root shell, more backups from vixie-cron job (as root), failure when I switched to fcron (still running job as root).  Problem went away when I put `export HOME=/root` in the backup script as @bjorkegeek suggested.  Thanks!

**Comment by azzamsa** [comment]
Had the same issue today. Adding `export HOME=/root` doesn't work for me. But `export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes` as mentoned by Thomas [here](https://github.com/borgbackup/borg/issues/2947#issuecomment-338507297) works like a charm.

I use anacron that run in [non-root mode](http://akeil.net/posts/user-controlled-anacron.html). So I dont need `sudo borg` except backup for `/` directory.

Thanks lot for borg.
