### ISSUE TITLE
Borg-list: Add archive size as placeholder

### ISSUE THREAD

**Issue by xeruf** [borgbackup/borg#6086]
Followup to #6061 

## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.

borg version 1.1.17

## Describe the problem you're observing.

I would like some extra keys for repo listing:
- size of the archive files (compress/uncompressed) - ignore deduplication for this
- number of files in the archive

**Comment by ThomasWaldmann** [comment]
Guess you'll need some metadata for this which is (only?) available in master branch created archives since a while.

**Comment by xeruf** [comment]
So the feature already exists but isn't published in a release yet?

**Comment by ThomasWaldmann** [comment]
I remember adding some metadata to master branch ("borg 1.2") archives a while ago.

Not sure though whether there are already placeholders that use that data, so please check.

Target branch of this ticket is only master branch (where the new metadata is present), iirc it is not in 1.1-maint.

**Comment by ThomasWaldmann** [comment]
PR #7506 will fix this (in master / borg2).

**Comment by xeruf** [comment]
that sounds perfect, thank you :)
