### ISSUE TITLE
Borg seems to be doing full backup on an existing repo after reinstalling the OS

### ISSUE THREAD

**Issue by blueray453** [borgbackup/borg#6089]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.17

#### Operating system (distribution) and version.

Linux Mint 20.2

#### How much data is handled by borg?

6TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg init --encryption=none /media/ismail/WDPurple8TB/6tbpurple
borg --warning --progress --show-rc create --show-version --stats --exclude='/media/ismail/WDPurple6TB/lost+found' --exclude='/media/ismail/WDPurple6TB/.Trash-1000' /media/ismail/WDPurple8TB/6tbpurple::{hostname}-{now:%Y-%m-%d_%H:%M:%S} /media/ismail/WDPurple6TB
```

## Describe the problem you're observing.

When I ran `borg --warning --progress --show-rc create --show-version --stats --exclude='/media/ismail/WDPurple6TB/lost+found' --exclude='/media/ismail/WDPurple6TB/.Trash-1000' /media/ismail/WDPurple8TB/6tbpurple::{hostname}-{now:%Y-%m-%d_%H:%M:%S} /media/ismail/WDPurple6TB` for the first time it took a long time obviously. From than on it took little time everytime I ran the command (as it is doing incremental backup).

Then I ran `borg prune -v --list --keep-last=3 /media/ismail/WDPurple8TB/6tbpurple` . The size of the repo became ~5TB, earlier it was ~5.5TB.

Then `borg list --short .` output looked like
```
ismail-i5-2021-12-08_13:00:40
ismail-i5-2021-12-08_13:30:38
ismail-i5-2021-12-08_13:32:06
```
Then I reinstalled the OS. And installed borg again. Now when I ran the command for the first time it seems to be doing full backup. Just to be clear I neither touched WDPurple6TB nor WDPurple8TB when reinstalling the OS.

I mounted `ismail-i5-2021-12-08_13:32:06` using `borg mount /media/ismail/WDPurple8TB/6tbpurple::ismail-i5-2021-12-08_13:32:06 /tmp/mymountpoint`. The contents seems ok. 

So, why it is doing full backup instead of incremental backup when I am running `borg --warning --progress --show-rc create --show-version --stats --exclude='/media/ismail/WDPurple6TB/lost+found' --exclude='/media/ismail/WDPurple6TB/.Trash-1000' /media/ismail/WDPurple8TB/6tbpurple::{hostname}-{now:%Y-%m-%d_%H:%M:%S} /media/ismail/WDPurple6TB` ?

#### Include any warning/errors/backtraces from the system logs
When I ran the command for the first time after reinstalling the OS it said 

> Warning: Attempting to access a previously unknown unencrypted repository

I said yes. I also know about `export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes`

**Comment by RonnyPfannschmidt** [comment]
Borg always does full backus however it's typically able to deduplicate pretty smartly and avoid unnecessary work

An operation system reinstall commonly means the caches borg does use for that are gone, so it has to run full operation

This will still deduplicate, its just that without the information on what work to avoid the complete content will have to be considered instead of just the changes

Aka borg will deliver the advantages of full backup and the advantages of incremental backups by being smart about what work to do on repeat backups

**Comment by ThomasWaldmann** [comment]
What @RonnyPfannschmidt said!

Typically, when you run borg as root user, it's cache is in ~root/.cache/borg/... - if you lost that by your OS reinstall, it has to rebuild the cache and also read all input data set files completely.

**Comment by blueray453** [comment]
@ThomasWaldmann what if the username is suppose `blueray`. In that case, what is the location of the cache directory. 

Is there any way I can keep the cache near the repo.

For example, if the backup is in `/media/blueray/WDPurple8TB` , I want to keep the cache in ` /media/blueray/WDPurple8TB/borg-cache` . How can I do that?

**Comment by snsmac** [comment]
@blueray453 
If you want a custom directory for the cache you can set it with the environment variable [`BORG_CACHE_DIR `](https://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables)
The data in this folder [is not encrypted](https://borgbackup.readthedocs.io/en/stable/faq.html#cache-security), so you need to be careful with it

**Comment by ThomasWaldmann** [comment]
See the docs about BORG_CACHE_DIR's default.

And yeah, what @snsmac said: storing the cache dir near the repo is dangerous (except if you do not use repo encryption at all anyway, guess then it does not matter).

**Comment by blueray453** [comment]
Thank you very much all.
