### ISSUE TITLE
QUESTION and WISHLIST:  better borg diffs or Changes and how to find them ?  ( and list them as side by side diffs )

### ISSUE THREAD

**Issue by placidchat** [borgbackup/borg#6091]
I'd like to find out if files have changed on disk vs the backups or between different snapshots of backups. At the same time, i'd like to be able to do a side by side diff between these files.

So an invocation like `borg diff --full <archive snapshot> <file directory>` to display an sdiff between files that have changed would be immensely helpful. 

Is there a way this can be done now?

**Comment by ThomasWaldmann** [comment]
We for sure will not implement a files content diff.

If you need that, just mount the borg repo and run your diff tool on whatever archives you want.

Also, a diff between filesystem and borg archive is currently not implemented, iirc.

**Comment by theChaosCoder** [comment]
You can make a backup and compare against that ...

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#how-can-i-compare-contents-of-an-archive-to-my-local-filesystem
