### ISSUE TITLE
Confusing CLI message "output file to export key to expected"

### ISSUE THREAD

**Issue by canadaduane** [borgbackup/borg#6092]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

borg 1.1.17

#### Operating system (distribution) and version.

Pop!_OS 21.10

#### Hardware / network configuration, and filesystems used.

None yet.

#### How much data is handled by borg?

None yet.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg key export /media/duane/JOHNSONVID2/backup.borg`

## Describe the problem you're observing.

The error message is confusing:
`output file to export key to expected`

Something like this would have been clearer to me:
`please specify the destination file where you'd like the key to be exported`

(Nice to have): In addition, it would be nice if the absence of a file just dumped the key to stdout.

**Comment by ThomasWaldmann** [comment]
Yeah, sounds like a good suggestion - do you want to make a PR for that?
