### ISSUE TITLE
Stale Locks Remain Stale Until you Manually Unlock Them (not good for automation)

### ISSUE THREAD

**Issue by Lonniebiz** [borgbackup/borg#6094]
I find it ironic that this issue is "locked" (given that it pertains to stale "locks"). The issue is marked as resolved, but it doesn't seem to be in resolved in borg 1.1.16:
https://github.com/borgbackup/borg/issues/3191

A power outage is what caused my stale lock. I can unlock it, but what concerns me is Borg's inability to auto-notice that a lock is stale. I ultimately intend to automate these borg backups, and if it cannot recover from a stale lock, I can see potential for recurring failures going unnoticed. I will certainly take great care in my scripting to be notified of such failures, because I read [here](https://github.com/borgbackup/borg/issues/3191) of a person who went 3 months without noticing that a stale lock was preventing all his automated backups!

Rather than just complaining about this, maybe I can suggest some solutions. Hmm.

Certainly borg logs activity on a repo with timestamps, no? If so, it seems that a stale lock rejection should trigger a log evaluation to occur, if there's been no log activity in the last 10 minutes (for example), then instead of continuing to cry about a lock, maybe borg should simply make a checkpoint out of the abandoned session and auto-unlock the repo. That's the first thing that comes to my mind; hopefully someone else can top it.

**Comment by ThomasWaldmann** [comment]
borg tries to kill locks, if it can for sure tell that they are stale:

https://github.com/borgbackup/borg/blob/1.1.17/src/borg/locking.py#L158
