### ISSUE TITLE
duplicate faq entry

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6098]
- 1.1 (also check master) "How can I switch append-only mode on and off?"

**Comment by sarfarazahmad89** [comment]
Hello there, I was trying to raise a PR to fix this, however, when I built the documentation from source (the master branch) with 

```bash
$ pwd
/tmp/borg/docs
$ make html
```
The build documentation did land under `_build` but I don't see duplicate references to "How can I switch append-only mode on and off?" in there.

**Comment by sarfarazahmad89** [comment]
Was fixed here: https://github.com/borgbackup/borg/pull/5931/commits/928347bd89bc7b454d6de70d018a3c69267b8f56

**Comment by ThomasWaldmann** [comment]
yeah, it was fixed short after 1.1.17 release. Thus not in released docs yet, but already fixed in 1.1-maint and master branch.

thanks for checking!
