### ISSUE TITLE
Older versions?

### ISSUE THREAD

**Issue by Quantlyx** [borgbackup/borg#6103]
If I automatically run a backup every day. And than I want to extract the version of 5 days ago. Can I even do that? In other worlds: Does it have kind of a version control?

EDIT: Sry I didn't add QUESTION label. Kinda new to GitHub...

**Comment by Quantlyx** [comment]
CLOSING BECAUSE WRONG FORMAT SRY. WILL POST AGAIN IN RIGHT FORMAT!

**Comment by infectormp** [comment]
Yes, you can. Please read the docs https://borgbackup.readthedocs.io/en/stable/quickstart.html#archives-and-repositories

**Comment by Quantlyx** [comment]
> Yes, you can. Please read the docs https://borgbackup.readthedocs.io/en/stable/quickstart.html#archives-and-repositories
> 
> 

Thank you so much.
I actually tried to find something like this in the docs.
Sry I didn't.
Thanks and happy new year!
