### ISSUE TITLE
directory size limit

### ISSUE THREAD

**Issue by Quantlyx** [borgbackup/borg#6104]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, I thought I found something earlier but I'm not able to recall/find it again.

## Is this a BUG / ISSUE report or a QUESTION?

Question

**Comment by ThomasWaldmann** [comment]
There is no specific limit on directory size for borg, but there is a (quite high) limit on the overall archive size:

https://borgbackup.readthedocs.io/en/stable/faq.html#are-there-other-known-limitations

**Comment by Quantlyx** [comment]
I found a Chapter which suggests that 1000 files is the limit in a directory.
https://borgbackup.readthedocs.io/en/1.1-maint/usage/general.html#file-systems
Did I understand something wrong?

**Comment by Quantlyx** [comment]
> There is no specific limit on directory size for borg, but there is a (quite high) limit on the overall archive size:
> 
> https://borgbackup.readthedocs.io/en/stable/faq.html#are-there-other-known-limitations

I found a Chapter which suggests that 1000 files is the limit in a directory.
https://borgbackup.readthedocs.io/en/1.1-maint/usage/general.html#file-systems
Did I understand something wrong?

**Comment by infectormp** [comment]
This is requirements for the file system where you will put Borg repository.

**Comment by Quantlyx** [comment]
> This is requirements for the file system where you will put Borg repository.

Thaks!
Sry I am so stupid right now but I can't seem to find the option to only make a archive of a specified path. I saw it in the DOCS eralier but now I'm unable to find it.
Could you point me in the right direction?

**Comment by infectormp** [comment]
> Could you point me in the right direction?
https://borgbackup.readthedocs.io/en/1.1-maint/usage/create.html
https://borgbackup.readthedocs.io/en/1.1-maint/usage/create.html#examples

**Comment by Quantlyx** [comment]
I litterly was looking over this page rn!
Thx so much!
