### ISSUE TITLE
Incomplete FAQ item about keys

### ISSUE THREAD

**Issue by jurgenhaas** [borgbackup/borg#6107]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, and that's why I'm opening this issue.

## Is this a BUG / ISSUE report or a QUESTION?

It's a documentation issue, combinded with a question.

## Describe the problem you're observing.

The FAQ at [How important is the $HOME/.config/borg directory?](https://borgbackup.readthedocs.io/en/master/faq.html#how-important-is-the-home-config-borg-directory) state about the `$HOME/.config/borg/keys` directory, that the keys in there are essential and cannot be recovered. Losing them means losing access to the repository.

We do not have that directory on any of our hosts and that's confusing in relation to this FAQ statement. We are using SSH private keys to access the repositories and those are stored in `$HOME/.ssh` which works just fine. I guess, it's those keys you're referring to, right?

If that's correct, then the FAQ should probably be updated.

And also, if we lost that SSH key on a host but still had access to the UI of the repository over https://www.borgbase.com, we could still assign a new SSH key to an existing repository and recover access to it that way.

Is that true too? If so, that would be nice to be added to the FAQ too.

**Comment by ThomasWaldmann** [comment]
The information missing in that FAQ entry is that only keys for `keyfile` modes are stored there. For `repokey` modes the keys are stored inside the repo.

This is **not** about ssh keys, but about borg's keys (encryption, signing, chunking of repo contents).

We do not cover borgbase usage in borg's docs, you need to check their docs.

**Comment by jurgenhaas** [comment]
Thanks @ThomasWaldmann for the explanation. I indeed missed the encryption mode `repokey` being used. Clarifying that in the FAQ would make it clear, when others come across that same scenario.

**Comment by EugeneMakita** [comment]
Hi @ThomasWaldmann can i take this ?

**Comment by ThomasWaldmann** [comment]
Sure, every open ticket can be taken. Thanks!
