### ISSUE TITLE
ModuleNotFoundError: No module named 'msgpack'

### ISSUE THREAD

**Issue by JBlond** [borgbackup/borg#6109]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.

Windows 10 Version 1809 LTSC

#### Your borg version (borg -V).

last build <https://ci.appveyor.com/project/borgbackup/borg/build/artifacts>

Commit [dee70c0f](https://github.com/sophie-h/borg/commit/dee70c0f4d957244db473abe0200b09dcb59ae2e)

#### Operating system (distribution) and version.

Windows 10 Version 1809 LTSC

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg.exe  

## Describe the problem you're observing.

```shell
Traceback (most recent call last):
  File "borg\archiver.py", line 38, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "borg\helpers\__init__.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "borg\helpers\misc.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "borg\helpers\msgpack.py", line 19, in <module>
ModuleNotFoundError: No module named 'msgpack'
````

**Comment by ThomasWaldmann** [comment]
Looks like `msgpack` is missing, which is required to run borg.

Not familiar with the windows .exe build, but if one installs borg from source, msgpack get's pulled via setup.py.

**Comment by JBlond** [comment]
Hi Thomas,
I see your point. I thought that the download was an all-in-binary since there is only borg.exe and no installer.

The Powershell scripts will do the trick.

**Comment by JBlond** [comment]
Install python 3
install Microsoft Visual C++ 14 Build tools https://visualstudio.microsoft.com/de/visual-cpp-build-tools/


git clone https://github.com/borgbackup/borg.git
Open Powershell
cd to borg folder

pip install Cython
pip install wheel
pip install pyinstaller
.\scripts\win-download-openssl.ps1
.\scripts\win-build.ps1
