### ISSUE TITLE
borg list --short for extracting archive names

### ISSUE THREAD

**Issue by abclution** [borgbackup/borg#611]
Please implement borg list --short for extracting archive names, one per line for scripting.

The current output requires some parsing to extract archive names for scripting. This would be useful for implementing mounting scripts of backups.

**Comment by abclution** [comment]
Current --short option lists as such:

`pm1-2016-01-17T20:43:04.287972.checkpoint Sun, 2016-01-17 21:26:22
pm1-2016-01-18T11:20:09.140282.checkpoint Mon, 2016-01-18 17:37:26
pm1-2016-01-19T14:22:01.970764       Tue, 2016-01-19 14:27:15
`
Useful to have only the archive name. This problem has also been solved below.

**Comment by abclution** [comment]
Bash one liner example solving this problem (and much more) courtesy of Manwe on irc.
`
 while IFS=$'\t' read -r NAME DATE ; do UNIXTIME=$(date -d "$DATE" +%s); REFTIME=$( date +"%s" -d "40 days ago") ; if [ $UNIXTIME -gt $REFTIME ] ; then echo $NAME ; echo $DATE; echo DoMountingHere; fi ; done < <(borg list /repo/Path |awk '{print $1"\t"$2" "$3" "$4}')`

**Comment by ThomasWaldmann** [comment]
@abclution likely the current `borg list --short` only works for archives (where it just outputs filenames), but not for repos (where it should output just the archive names).
