### ISSUE TITLE
borg info: No output for empty repo with --last or --first supplied

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#6120]
```
$ borg --version
borg 1.1.17
```

`borg info` or `borg info --json` do not give any output if `--last=1` or `--first=1` is supplied and there are no archives yet.

**Comment by ThomasWaldmann** [comment]
I'ld assume that if you give last/first=N that then **up to** N items are output (that is less than N if fewer than N archives exist). If 0 archives exist, 0 items are output.

So guess that is correct / consistent behaviour?

**Comment by sophie-h** [comment]
`borg info --json` without the `--last=1` gives the following

```json
{
    "cache": {
        "path": "...",
        "stats": {
            "total_chunks": 0,
            "total_csize": 0,
            "total_size": 0,
            "total_unique_chunks": 0,
            "unique_csize": 0,
            "unique_size": 0
        }
    },
    "encryption": {
        "mode": "repokey"
    },
    "repository": {
        "id": "...",
        "last_modified": "2021-10-12T00:03:37.000000",
        "location": "..."
    },
    "security_dir": "..."
}
```

With `--last=1` it returns nothing. Instead I would expect the same output but with `"archives": []` added.

**Comment by ThomasWaldmann** [comment]
Oh, ok, that makes sense.

**Comment by ThomasWaldmann** [comment]
also applies to master branch.

**Comment by ThomasWaldmann** [comment]
The cause of this is that if you invoke do_info for archive(s) (either giving an archive name, last/first or prefix), it calls `_info_archives` while it calls `_info_repository` when only giving the repository.

**Comment by hexagonrecursion** [comment]
@sophie-h JSON info has been fixed: it now prints `"archives": []`, but without --json the output is still empty. Has this bug been fully resolved? Your first comment made it sound like you did not expect this behavior.

**Comment by ThomasWaldmann** [comment]
the code specifically checks for `--json` and only includes that info if that is given.
