### ISSUE TITLE
borg 1.1-maint fails to compile with Clang & ld.lld as the linker

### ISSUE THREAD

**Issue by telans** [borgbackup/borg#6131]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

## System information. For client/server mode post info for both machines.

n/a

#### Your borg version (borg -V).

1.1.17,
1.1-maint

#### Operating system (distribution) and version.

```
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.8"
```

#### Hardware / network configuration, and filesystems used.

amd64, n/a

#### How much data is handled by borg?

n/a

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

n/a

## Describe the problem you're observing.

Borg fails to compile with Clang + ld.lld as the linker when using releases or HEAD from the 1.1-maint branch. There is no issue on master.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Always:
`python setup.py build -j16`

Multiple messages stating the following:
```
ld.lld: error: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../lib64/crti.o is incompatible with elf32-i386
ld.lld: error: /usr/lib/llvm/13/bin/../../../../lib/clang/13.0.1/lib/linux/clang_rt.crtbegin-x86_64.o is incompatible with elf32-i386
ld.lld: error: build/temp.linux-x86_64-3.10/src/borg/algorithms/msgpack/_packer.o is incompatible with elf32-i386
ld.lld: error: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so is incompatible with elf32-i386
```

There are no issues using ld.bfd, or compiling with ld.lld from master.

#### Include any warning/errors/backtraces from the system logs

Full build log from HEAD of branch `1.1-maint`: https://dpaste.com/AT7LK6AWV

**Comment by ThomasWaldmann** [comment]
I've no idea about this toolchain and related issues, sorry.

That `elf32-i386` seen in these error msgs, is that correct / expected? Seems weird as it also has `x86_64` there.

**Comment by telans** [comment]
> That `elf32-i386` seen in these error msgs, is that correct / expected? Seems weird as it also has `x86_64` there.

It's not expected, I'm not cross-compiling or anything just building on my main amd64 system. It seems to me like some library borg is creating is created as `elf32-i386` and so lld refuses to link my 64-bit libraries with it, but I'm not sure. Though it is odd that ld.bfd seems to not have any problems.

**Comment by ThomasWaldmann** [comment]
Can this still be reproduced with current toolchain, borg 1.2-maint or master?
