### ISSUE TITLE
Missing Docs: Please help me understand the output of --list --verbose (characters "M", "A", etc.)

### ISSUE THREAD

**Issue by Sieboldianus** [borgbackup/borg#6133]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. More specifically, I checked [usage/general.html](https://borgbackup.readthedocs.io/en/stable/usage/general.html)

## Is this a BUG / ISSUE report or a QUESTION?

Issue: Missing Documentation

## Infos

Borg version: `borg 1.1.9`
Operating system (distribution) and version: In unprivileged LXC (Debian 10), on Proxmox
Hardware / network configuration, and filesystems used: ZFS mount (Raidz2)
How much data is handled by borg? `90GB`
Full borg commandline that lead to the problem (leave away excludes and passwords):

```
borgmatic --verbosity 1
borg create --verbose --list
```

## Describe the problem you're observing.

In the report progress, I see characters in front of files that I cannot explain (`M`, `A`).

```output
M /nc_data/user1/filea.md
M /nc_data/user1/fileb.md
M /nc_data/user2/filex.md
A /nc_data/user1/filec.md
A /nc_data/user1/filed.md
A /nc_data/user2/filey.md
```

- I have checked [borg/helpers/progress.py](https://github.com/borgbackup/borg/blob/master/src/borg/helpers/progress.py), but those characters are not explained there.
- there is [#5038](https://github.com/borgbackup/borg/issues/5038), but it doesn't speak about these character codes
- there is also [pipermail/borgbackup/2016q1/000115.html](https://mail.python.org/pipermail/borgbackup/2016q1/000115.html) with a discussion, but it only answers what "N", "C" and "D" could mean, not "A" and "M"

I could guess that A means "Archive" and "M" means "Move", but it does not really make sense in my context, or I am misinterpreting what happened in my case (I saw a lot of "M"s and a few "A"s, after migrating from Raid1 to ZFS in my underlying storage).

**Comment by infectormp** [comment]
This is explained in FAQ https://borgbackup.readthedocs.io/en/stable/usage/create.html#item-flags

**Comment by Sieboldianus** [comment]
Wow, incredible hpw I could not find this. Thank you very much.
