### ISSUE TITLE
update web site for 1.2.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6137]
see there: https://www.borgbackup.org/releases/

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borgbackup.github.io/pull/75 see there.

**Comment by enkore** [comment]
Is there a "policy" for 1.1 support and EOL? I can't recall if we wrote one down for 1.0 when we released 1.1.

**Comment by ThomasWaldmann** [comment]
No policy, but I think we will update 1.1.x for a while even after 1.2.0 is released.
Maybe not for new features, but definitely for severe bugs and security.

**Comment by ThomasWaldmann** [comment]
if a native english speaker (and borg user) could proofread that PR, that would be very welcome.

**Comment by ThomasWaldmann** [comment]
Website is updated. Rather early, but people will notice the reference to 2022-02-22. :-)
