### ISSUE TITLE
vagrant: use libvirt (kvm) rather than virtualbox

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6146]
use libvirt/kvm for borg platform testing (see Vagrantfile in our repo).

kvm seems to be way faster. also likely more portable (virtualbox is amd/intel x64 only).

quite some work though to migrate this on my testing workstation as I've quite some virtualbox boxes...

**Comment by ThomasWaldmann** [comment]
hmm, no macos boxes for libvirt?

**Comment by dragetd** [comment]
Some info:
MacOS is a bit more difficult since it relies in some apple specific settings (properties) of the VM. There is a bash based project for setting up qemu for MacOS (and other popular images): https://github.com/quickemu-project/quickemu

**Comment by m3nu** [comment]
Just started using "Lima" for my more complex testing, that needs more than a Docker container:

https://github.com/lima-vm/lima

It's still under heavy development, but performance, config files, etc are all very promising. Concepts are not too different from Vagrant. I just haven't seen a macOS or BSD guest yet.

**Comment by ThomasWaldmann** [comment]
Note: i recently tried vagrant and kvm/libvirt:
- quite some strange issues not seen before with virtualbox
- some boxes not available for kvm
