### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by ghost** [borgbackup/borg#6190]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
Client: borg 1.1.17
Client OS: Manjaro Xfce, stable, 5.10 kernel

#### Operating system (distribution) and version.
SFTP server: WSL Ubuntu LTS 20.04.3 on Windows 10 Pro
Kernel: 4.4.0-19041-Microsoft
server borg version 1.1.15

#### How much data is handled by borg?
Approx. 260GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg check --verify-data --repair  ssh://user1@192.168.35.10:23023/mnt/r/Users/user1

## Describe the problem you're observing.
I initially observed repo error using Vorta backup.
Afterwards running above-mentioned command line also showed error.

Error displayed on client side:
Remote: client_loop: send disconnect: Broken pipe
Connection closed by remote host

On server side, sshd_config already contains following:
ClientAliveInterval 15
ClientAliveCountMax 30

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
After initial error in Vorta I ran the cmd line on client and it showed the same error as mentioned above.

**Comment by ThomasWaldmann** [comment]
Hmm, yeah, looks like your ssh server closed the connection.

BTW, `--verify-data`is a rather time and I/O expensive option, consider if you really need that.

Can you try adding `--verbose --progress` or so?

**Comment by Maula-Jatt** [comment]
The reason to use `--verify-data ` was the I was informed by **Vorta** backup to check repo.  Is there a safer method to "_fix_" repo issues?

I will try again with `--verbose --progress ` and revert back. Thanks.

**Comment by ThomasWaldmann** [comment]
A normal repo check is `borg check` (plus `--repair` if you want borg to actually fix stuff and not just check).
If you invoke that it will do a low-level crc32 check of all chunks plus a consistency check archives metadata vs. chunks actually present in the index (it will NOT do a cryptographic check of all file content chunks though - if you want that additionally and you are willing to wait longer, then add the `--verify-data`).

**Comment by Maula-Jatt** [comment]
Here's the latest output from Borg:

```
borg check --verify-data --progress --verbose  ssh://***************
Remote: Starting repository check
Remote: Checking segments 10.9%
Remote: Starting repository index check
Remote: Index object count match.
Remote: Completed repository check, no problems found.
Starting archive consistency check...
Enter passphrase for key ssh://***************: 
Starting cryptographic data integrity verification...
**Remote: client_loop: send disconnect: Broken pipe                               
Connection closed by remote host**
```
( _certain confidental info has been redacted to protect the innocent_)

Any suggestion to fix Borg or the SSH config to return to previous glory?

**Comment by infectormp** [comment]
@Maula-Jatt did you already check FAQ https://borgbackup.readthedocs.io/en/stable/faq.html#common-issues?

**Comment by Maula-Jatt** [comment]
> @Maula-Jatt did you already check FAQ https://borgbackup.readthedocs.io/en/stable/faq.html#common-issues?

Yes, I did go through the documentation, including the link above. I have the timeout configured properly on both client and the server side. Please note that this is a new phenomena as I was able to run the checks, in past, without any disruptions.

**Comment by ThomasWaldmann** [comment]
The borg client<->server connection - is that WAN or LAN?

Did try power-cycling network equipment in the client<->server path already?

**Comment by Maula-Jatt** [comment]
It is a WAN connection. Server is in a different country.

Server has been restarted couple of times. I will also do network equipment power-cycling.

**Comment by Maula-Jatt** [comment]
As of now here is my configuration:

```
**On server side:**
    TCPKeepAlive yes
    ClientAliveInterval 300
    ClientAliveCountMax 30
    DebianBanner no
    Protocol 2

**On client side:**
    Host *
      ServerAliveInterval 300
      ServerAliveCountMax 4
      ServerAliveInterval 900
```

On both ends the available Internet throughput is 500Mb/sec. No QoS implemented on router. Network equipments restarted on both ends.

Still getting broken pipe error.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/faq.html#why-does-borg-extract-hang-after-some-time

The intervals there are way lower. In case some network equipment (like your internet router) thinks "this is not needed any more" because there is a minute of no traffic, i guess keeping this relatively low help.

Also, you have a duplicate entry on the client side.

**Comment by Maula-Jatt** [comment]
> https://borgbackup.readthedocs.io/en/stable/faq.html#why-does-borg-extract-hang-after-some-time
> 
> The intervals there are way lower. In case some network equipment (like your internet router) thinks "this is not needed any more" because there is a minute of no traffic, i guess keeping this relatively low help.
> 
> Also, you have a duplicate entry on the client side.
> 
> I checked one of my personal borg WAN connections and I don't have these entries (not on client, not on server) and it works for me.

Which particular entry are you referring to?
Also what do you suggest the value should be for my case?

**Comment by Maula-Jatt** [comment]
Archive consistency check runs successfully but cryptographic data integrity verification takes a _very_ long time to run and ends up with broken pipe message after 5% or so. At this point I am clueless as to where to look for a solution. I can either continue to dump more data in my Borg repo without fixing the problem (if any) or I may have to look for alternative backup solution.

Just in case anyone missed the initially provided details: the SFTP/SSH server is a crusty but reliable, hardware-wise, Windows 10 Pro box running Ubuntu LTS 20.04.3 on WSL. It is running reliably well in someone else garage. It was all great and dandy for last 2 years or so. Never hand any issue running verification scan.

Also I am able to transfer large number of files (GBs) to/from the _server_ using FileZilla without any problem at all. I am assuming since during SFTP file transfer the network remains active and there's no idle state so there's no disconnection.

**Comment by ThomasWaldmann** [comment]
@Maula-Jatt use the values suggested in the linked docs section.

if the normal check works and just the --verify-data one does not, it sounds like a timing / threshold issue on the ssh or router level. some NAT routers kick NAT entries if there has been no traffic for a while, so keep the connection busy.

**Comment by Maula-Jatt** [comment]
This might be out of my league but is it worth exploring for borg to maintain a steady connection since SSH is the key element of the ecosystem. i.e. Borg will send constant _ping_ to client or server so that SSH itself does not kill the session.

**Comment by ThomasWaldmann** [comment]
Well, guess that "constant ping" is what tcp and ssh(d) level keepalives are good for.
