### ISSUE TITLE
detect file changes only based on checksum

### ISSUE THREAD

**Issue by shartge** [borgbackup/borg#620]
I'd like a mode where borgbackup always hashes every file to detect changes and does not rely on the mod-time of a file, like --checksum does for rsync.

Rationale: using borgbackup on devices where the local time is not trustable, like on an RasPi without RTC.

Of course this checksum-only mode will be (much) slower because it needs to completely read every file but on the other hand one can be sure that every change is detected and saved, even if the locale time always starts at 01.01.1970 00:00 on every boot.

**Comment by ThomasWaldmann** [comment]
did you see borg create --no-file-cache?

**Comment by shartge** [comment]
I did (I checked the man page twice to see if there was already an option doing what I wanted) but I guess I did not understand what it does.

**Comment by shartge** [comment]
OK, after testing --no-files-cache: this does not what I  imagined. It reads all files and hashes them but it also creates new chunks for all files.

What I meant with "--checksum-only" is for borgbackup to not skip files based on the timestamp, but rehash every file and then do its normal thing, deduplicating identical chunks, etc. Just as if every file has been touched since the last backup.

**Comment by ThomasWaldmann** [comment]
Are you saying it did NOT deduplicate the stuff in the storage?

Or are you saying it did transfer all new chunks into the repo although they already were in the repo and later removed the (identical) old chunks during compaction phase?
The latter is a somehow known issue and there is a separate ticket about that.

**Comment by shartge** [comment]
To be honest: I did not wait for the process to finish, as it would take another 2 hours on the system I tested it and after seeing it transfer all chunks over to the server I guessed that the deduplication did not happen and aborted the run.

**Comment by ThomasWaldmann** [comment]
That's the other issue: https://github.com/borgbackup/borg/issues/460
