### ISSUE TITLE
Wishlist: moving some archives to a different repo

### ISSUE THREAD

**Issue by callegar** [borgbackup/borg#6212]
Hi, I wonder if there is some means to move an archive to a new repository.

My usage case is the following. In the past I have backed up multiple machines to the same repo, to take maximum advantage of the deduplication abilities of borg, given that the machines happen to frequently have common subsets of files.

Unfortunately, I have recently realized that this way of doing things has too many disadvantages. It is discouraged from a security perspective and it causes a too large overhead on the machines being backed up, either in terms of storage (if you use a chunk cache) or in terms of sync time (if you don't).

I am thus considering the option to switch to an arrangement where each machine is backed up to its own repo.  Clearly I can do that *from now on*, but when doing so it would be nice to *port* the past history to these new repos. As an example: suppose that my repo contains:

- current repo
  - archive with backup from machine A date A1
  - archive with backup from machine B date B1
  - archive with backup from machine C date C1
  - archive with backup from machine A date A2
  - archive with backup from machine A date A3
  - archive with backup from machine A date A4
  - archive with backup from machine B date B2

What would be the best way to disentangle it into

- repo for machine A
  - archive with backup from machine A date A1
  - archive with backup from machine A date A2
  - archive with backup from machine A date A3
  - archive with backup from machine A date A4
- repo for machine B
  - archive with backup from machine B date B1
  - archive with backup from machine B date B2
- repo for machine C
  - archive with backup from machine C date C1 

I wonder if some of the following could be possible:

- Duplicate the current repo multiple times, and then prune away from each copy what is not needed
  - Would it be enough to copy the repos with rsync and then change the keys?
- Create new repos and *move* there what is needed with some export/import trick? How? 
- Something else?

**Comment by ThomasWaldmann** [comment]
can you check whether we already have a ticket for this?

**Comment by ThomasWaldmann** [comment]
Quick answer about "duplicating repos" with rsync and use them all:
- they would have the same repo ID afterwards, leading to misc. severe issues if just used like that
- they would use the same crypto key (and you can't change that), leading to crypto issues if you update them independently

**Comment by callegar** [comment]
@ThomasWaldmann 

> can you check whether we already have a ticket for this?

I have looked around, but may have missed something, will recheck.

> they would have the same repo ID

Maybe duplicate and recreate?

**Comment by ThomasWaldmann** [comment]
@callegar usually the repo id never changes. one can manually edit the repo/config file, but one needs to do that after creating the copy and before ever using the copy with borg. also, if one uses keyfile keys, one needs to copy/edit the key also (the repo id is in there, too).

but, be aware that if you have 2 repos with the same AES key and you update them independently, the crypto can be broken (AES counter/nonce reuse), so this is not recommended.

**Comment by callegar** [comment]
> One can manually edit the repo/config file, but one needs to do that after creating the copy and before ever using the copy with borg

OK. Is there any rule for the generation of a valid ID? Is it just a random HEX string with 64 digits?

> also, if one uses keyfile keys, one needs to copy/edit the key

This is less clear to me... is that the key in the config file? How do you copy/edit it?

> if you have 2 repos with the same AES key and you update them independently, the crypto can be broken (AES counter/nonce reuse)

If I understand correctly, there is no way to change the AES key, is this the case?

From the above exchanges, it seems to me that a non-lossy export/import format would be rather beneficial, solving many problems at once.  It would enable one to use one instance of borg to export an archive piping the output into another instance of borg importing it into another repo, so enabling one to move archives and to effectively duplicating repos into ones with new IDs and crypto. The latter seems particularly valuable in case a key is compromised.  In principle if other backup solutions pick up support for the same export/import format, that would also make it easy to migrate backups from one solution to another one.

Unfortunately `tar`, for which there is already an `export` command, is lossy. Would `pax` be a better choice? I think it was originally conceived as an interchange format also for this sort of things. Or would something ad hoc be needed?

**Comment by ThomasWaldmann** [comment]
repo id: it is just random hex and must be unique. you can edit it with a text editor.

About non-lossy transfer: iirc we have a ticket about this. could be either a special borg-pax-tar-based format or just some borg specific new serialization/deserialization.

**Comment by callegar** [comment]
> About non-lossy transfer: iirc we have a ticket about this.

Excellent hint! Thanks.

So, the question in the current issue would actually be answered by #4337, possibly together with #5830 and is rather similar to #3867, #895,  #3249 and in some sense #1697, #1421.

Consider closing given the number of partially or fully overlapping issues.

**Comment by ThomasWaldmann** [comment]
Hah, that many tickets already.

**Comment by callegar** [comment]
Many tickets, but I understand that some work on (lossless) export/import is on the way. Tar import is already merged, right?
