### ISSUE TITLE
Borg via Rclone encryption (additionally)

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#6221]
It seems to me that Borg works very well by Rclone and many people praise the combination of these two great applications.
Does anyone use the encryption function built into Rclone to enter an additional encryption layer?
https://rclone.org/crypt/
For extremely important data or for paranoids ;)

**Comment by juliandddd** [comment]
Bump - curious about the same

**Comment by ThomasWaldmann** [comment]
"[File content](https://rclone.org/crypt/#file-encryption) encryption is performed using [NaCl SecretBox](https://godoc.org/golang.org/x/crypto/nacl/secretbox), based on XSalsa20 cipher and Poly1305 for integrity."

**Comment by ThomasWaldmann** [comment]
My 5 cent about this (I am not a cryptographer, but know a bit about it):

Considering that borg and rclone use different algorithms for encryption and authentication, it might really be useful for the case that one of them is broken somehow.

OTOH, you'll use more code by using this, creating a more complex system, so there is also the risk of more bugs.
