### ISSUE TITLE
What is the Windows counterpart of ~/.config/borg ?

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6225]
The documentation sometimes refers to locations like `~/.config/borg` and `$HOME/.config/borg`. This, obviously, does not apply to Windows. The docs should be updated to include the Windows counterpart too.

Examples:
* https://borgbackup.readthedocs.io/en/master/usage/init.html
  > keyfile: stores the (encrypted) key into ~/.config/borg/keys/
* https://borgbackup.readthedocs.io/en/master/faq.html?highlight=home#how-important-is-the-home-config-borg-directory

Related: https://github.com/borgbackup/borg/pull/6184#discussion_r795244523

**Comment by thinkrapido** [comment]
we can use the same structure here.
$HOME gets exchanged with %USERPROFILE%.

**Comment by thinkrapido** [comment]
from pathlib import Path
print(Path.home())

**Comment by ThomasWaldmann** [comment]
Note: We now use `platformdirs` package to query config and cache directory locations. (master branch, borg2)

**Comment by ThomasWaldmann** [comment]
merging this into #7332.
