### ISSUE TITLE
How to know if a file was deleted and not moved?

### ISSUE THREAD

**Issue by blueray453** [borgbackup/borg#6228]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.17

#### Operating system (distribution) and version.

Linux Mint 20.3

#### How much data is handled by borg?

~5TB

How to know if a file was deleted and not moved?

Reading https://github.com/borgbackup/borg/issues/2395#issuecomment-293013096 , my guess is there is no straightforward solution. But is there any hack?

For example:
I can get the added and deleted files using:

```
borg diff .::start_deleting ismail-i5-2022-02-02_04:16:04 | grep "^added" | sd "^added.*media/ismail/WDPurple6TB/" "" > /home/ismail/Desktop/added-files.txt
borg diff .::start_deleting ismail-i5-2022-02-02_04:16:04 | grep "^removed" | sd "^removed.*media/ismail/WDPurple6TB/" "" > /home/ismail/Desktop/deleted-files.txt
```
The output looks like

```
_SystemAdminLinux/_Linux/_docs
_SystemAdminLinux/_Linux/_docs/_Administration
_SystemAdminLinux/_Linux/_docs/_Administration/Enterprise Linux System Admin
_SystemAdminLinux/_Linux/_docs/_Administration/Enterprise Linux System Admin/a- Cover + Table of Contents.pdf
_SystemAdminLinux/_Linux/_docs/_Administration/Enterprise Linux System Admin/Chapter 1.pdf
_SystemAdminLinux/_Linux/_docs/_Administration/Enterprise Linux System Admin/Chapter 10.pdf
_SystemAdminLinux/_Linux/_docs/_Administration/Enterprise Linux System Admin/Chapter 11.pdf
_SystemAdminLinux/_Linux/_docs/_Administration/Enterprise Linux System Admin/Chapter 12.pdf
_SystemAdminLinux/_Linux/_docs/_Administration/Enterprise Linux System Admin/Chapter 13.pdf
```
If I could add the hash with the file names in diff output , I could remove lines from `deleted-files.txt` which has duplicate hash in `added-files.txt`.

So, the question actually is: How can I add the hash of files in diff output.

**Comment by ThomasWaldmann** [comment]
For borg, a moved file is the same as a deleted file at one place (filename1) and a new file appearing at another place (filename2).

So I guess you can't find moved files with borg diff.

The only way to detect a move of an unmodified file would be to track a full-file hash and notice that the new file has same hash as the deleted file.
