### ISSUE TITLE
Crypto is broken -> update docs

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#6229]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes
## Is this a BUG / ISSUE report or a QUESTION?
Question + update Docs

##

Hi

After reading this, I'm a little worried about the safety of my backups:

- https://github.com/borgbackup/borg/issues/3499#issuecomment-356074809
- https://github.com/borgbackup/borg/issues/5254
- https://borgbackup.readthedocs.io/en/stable/faq.html#isn-t-borgbackup-s-aes-ctr-crypto-broken

**Assumption: I use one client for repo, but the server owner is a bad guy.**
Questions:
1. What's in practice means "Crypto is broken"?
Does this mean that the bad server owner (for example Borgbase.com or Rsync.net) can manipulate the counter and receive my backups decrypted in a plain text?
2. Is Borg notifying the problem with the counter when creating backup?
3. Maybe it would be worth adding information [here](https://borgbackup.readthedocs.io/en/stable/faq.html#isn-t-borgbackup-s-aes-ctr-crypto-broken), which means "Crypto is broken". Means simply "decrypted files"?

**Comment by ThomasWaldmann** [comment]
borg keeps the AES counter value clientside also (not only in the repo). So as long as you use 1 client per repo and you do not lose the clientside counter while somebody is attacking you on the server, you don't have a problem (borg will emit a warning then if the repo counter behaves strangely and will use the higher counter value from the clientside).

**Comment by git70** [comment]
> borg will emit a warning then if the repo counter behaves strangely

It looks like it is a very important alert

So the backup is safe if I fully meet the conditions:
1. I have only one client for repo
2. I do not ignore the AES counter warnings
3. I will not continue to write to repo in the case of:
a) Receiving a counter error warnings
b) Loss of the clientside counter (disk explosion)

I understand well?

**Comment by ThomasWaldmann** [comment]
iirc, borg does not let you "ignore" that problem and just continue automatically.

**Comment by git70** [comment]
Can a bad server owner using BorgServe to fool BorgClient and give him a false counter?

**Comment by ThomasWaldmann** [comment]
the borg client compares to its local copy of the counter and rejects to continue if remote < local.

**Comment by git70** [comment]
I meant hacking (malicious borg modification).
Since I don't know how borg serve communicates with borg client (is it bi-directional? Can client accept any commands from serve?), Is it possible for borg client to be tricked by borg serve? (got from a borg serve counter, thinking it was a local counter)

**Comment by ThomasWaldmann** [comment]
The communication the client doing RPC via ssh on the server (not vice versa, not bidi).
So I don't think there is a way to trick the client here.

**Comment by git70** [comment]
Thank you very much for your time and patience :)

I have one more thought:

Encryption = Privacy of files
Authentication = File integrity (File modification detection for example)

The problem of the AES-CTR counter = violated privacy = spoiled points 3. and 4. [here](https://borgbackup.readthedocs.io/en/stable/internals/security.html#attack-model)
But authentication (file integrity) is still ensured? (i.e. points 1. and 2. in the Attack Model)

I think well?

**Comment by ThomasWaldmann** [comment]
Yes, that sounds correct. The authenticity is checked clientside via hmac-sha256 or blake2b using the clientside (secret) MAC key.

**Comment by ThomasWaldmann** [comment]
In master (1.2) I added a borg-internal "crypto api", mainly to clean up the code and map the crypto usage of borg to a AEAD-style api rather than having it at misc. places in the code.

Other than that, there are **no** crypto changes, no new algorithms are used, AES-CTR is still used.

Doing crypto changes is in the next milestone "helium" (== master branch after borg 1.2 release).

**Comment by git70** [comment]
I suggested the entry "crypto: new AES-OCB, CHACHA20-POLY1305" [here](https://github.com/borgbackup/borg/blob/master/docs/changes.rst#version-120a2-and-earlier-2019-02-24) :(

Is there a known date for the introduction of new algorithms? Although the indicative plan ...?

**Comment by ThomasWaldmann** [comment]
@git70 see there: https://github.com/borgbackup/borg/blob/1.2.0rc1/src/borg/crypto/low_level.pyx#L654

so, borg's internal crypto api has OCB and chacha, but it is not used yet by other borg code.
that's why it is under "refactorings / internal" and not under "new features".

how long it'll take to really make use of that depends a lot on how many people contribute to that, i don't think i can predict that.

**Comment by git70** [comment]
It seems to me (although I am not a professional from crypto) that OCB and ChaCha20 are a good choice for security. I also saw other threads, where you talked about it :)

Somewhere I saw your confirmation (I can not find now) that after release Borg 1.2, crypto's case will have a priority (and then multithreaded).
Is it true?

I would like to help you, but I'm not a programmer :(
I can only help through subsidies and testing ...

**Comment by ThomasWaldmann** [comment]
@git70 see there about post-1.2 goals: https://github.com/borgbackup/borg/milestone/17 (subject to change, maybe too much in there, considering how long 1.2 took we maybe should have smaller milestones)

Other contributions than coding are also always welcome!

**Comment by ThomasWaldmann** [comment]
@git70 have a look at the pull requests (master branch, so borg 1.3+).

**Comment by ThomasWaldmann** [comment]
I removed all the docs about potential issues related to aes-ctr and counter/nonce management from the borg2 branch. We will not use aes-ctr mode for future repos.
