### ISSUE TITLE
relate patterns to the source path(s)

### ISSUE THREAD

**Issue by funkyfuture** [borgbackup/borg#623]
i came across this when i migrated a backup script from using `rsync` to `borg` and reused a files with exclusion patterns.

if i observed correctly and did understand the code correctly, `borg` evaluates patterns starting with a `/` to the filesystem's root. in opposite `rsync` considers an initial `/` as the specified source path.

i propose to adapt that behavior, because:
- it doesn't make much sense to evaluate against a context that isn't considered anyway
- patterns are shorter
- patterns files are reusable in different / changed contexts

e.g. with `borg create --exclude-from excludes <repo>::<name> /home/user` i would currently specify in the `excludes` file:

    /home/user/.cache

this would simply become:

    /.cache

if there's an agreement (how) to change this aspect, i'm willing to implement the changes.

**Comment by ThomasWaldmann** [comment]
Borg supports multiple source base directories, so it would be unclear to which of them the exclude patterns are relative.

**Comment by funkyfuture** [comment]
to all of 'em i'd say.

**Comment by ThomasWaldmann** [comment]
sounds weird.

**Comment by funkyfuture** [comment]
> it would be somehow weird
i somehow like that. ;-)

the current design can also be considered weird:

    borg create --exclude /dev /media/backup::archive /var/www

this is valid, but it makes no sense. so, qualifies as weird. but weird as category will not help us.

i see the point that with `borg`'s archiving of full paths and the possibility to archive several paths at a time, the current design is straight-forward and unambiguous.

however, i'm not a fan of repeating the same strings, eg:
```
/home/user/bin/lost+found
/home/user/.cache
/home/user/.davfs2/cache
/home/user/.dbus
/home/user/DEADJOE
/home/user/.fontconfig
/home/user/.local/share/Trash
/home/user/.thumbnails
/home/user/big_folder
/home/user/another_big_folder
/home/user/irrelevant_folder
...
```

what about a magic word that defines a prefix for the following lines in a pattern file?

```
^/home/user
/bin/lost+found
/.cache
/.davfs2/cache
/.dbus
/DEADJOE
/.fontconfig
/.local/share/Trash
/.thumbnails
/big_folder
/another_big_folder
/irrelevant_folder
...
```

the caret is just an example. with the possibility to include other files (like `rsync` does) this would also make pattern sets reusable in different contexts.

**Comment by ThomasWaldmann** [comment]
I don't care much that people could write scripts that make no sense, they always can do that. ;)

What's critical though is if some mechanism can not be made doing what is required (like when applying an exclusion relatively to **all** base paths, as I pointed out above).

I understand that repetition is somehow a bit awkward, but otoh, the current mechanism is at least simple.
In a shell script, you could even use $HOME or $H to abbreviate that.

Your last suggestion makes the system more complex and it also creates a strange mix of pathes beginning with slash that are absolute (as usual) and pathes beginning with slash that are meant relative (which is very unusual).

**Comment by ThomasWaldmann** [comment]
Guess I'll close this soon, unless somebody comes up with a new idea.

**Comment by mahikeulbody** [comment]
> you could even use $HOME

I fail to use $HOME in a "--patterns-from" config.
Is it possible ?

**Comment by ThomasWaldmann** [comment]
No, there is no environment variable expansion for the patterns file.

**Comment by mahikeulbody** [comment]
Ok, thanks for the answer. It could be a future feature ?

By the way, what is the recommended channel for general support (ie non-issue related) ?

**Comment by dimejo** [comment]
> By the way, what is the recommended channel for general support (ie non-issue related) ?

https://mail.python.org/mailman/listinfo/borgbackup
