### ISSUE TITLE
borg help does not show help for sub-sub-commands (eg. borg key export)

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6232]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

borg 1.2.0b5.dev34+g91cfa823

#### Operating system (distribution) and version.

Fedora release 34 (Thirty Four)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```sh
borg help key export
usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug]
            [--debug-topic TOPIC] [-p] [--iec] [--log-json]
            [--lock-wait SECONDS] [--bypass-lock] [--show-version] [--show-rc]
            [--umask M] [--remote-path PATH] [--remote-ratelimit RATE]
            [--upload-ratelimit RATE] [--remote-buffer UPLOAD_BUFFER]
            [--upload-buffer UPLOAD_BUFFER] [--consider-part-files]
            [--debug-profile FILE] [--rsh RSH]
            <command> ...
borg: error: unrecognized arguments: export
```

## Describe the problem you're observing.

`borg help` appears to have no support for sub-sub-commands such as `borg key export`

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Run `borg help key export`

## A workaround

This works:
```sh
borg key export --help
```

**Comment by ThomasWaldmann** [comment]
Yeah, just document workaround (if not already there).
