### ISSUE TITLE
RHEL 8 EPEL Repo "python3.6dist" Dependency Issue

### ISSUE THREAD

**Issue by BloodBlight** [borgbackup/borg#6234]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yep, not 100% sure if this is an issue with Borgs deployment, or something that should get reported to RHEL.  So please let me know if I should open a case with them.

## Is this a BUG / ISSUE report or a QUESTION?
Repository Dependency  Issue

## System information. For client/server mode post info for both machines.
This is a fresh deployment. 
I deploy brogbackup in out standard kickstart and as part of upgrading from RHEL 7 to RHEL 8 I noticed this issue.

#### Your borg version (borg -V).
borgbackup-1.1.17-1.el8.x86_64

#### Operating system (distribution) and version.
RHEL 8

## Describe the problem you're observing.
On a clean install, and after enabling the EPEL, borg fails to install:
```
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
dnf config-manager --set-enabled epel


dnf install --nobest borgbackup
Updating Subscription Management repositories.
Extra Packages for Enterprise Linux 8 - x86_64                                                          13 kB/s |  18 kB     00:01
Error:
 Problem: conflicting requests
  - nothing provides python3.6dist(packaging) needed by borgbackup-1.1.17-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

dnf search python3
....
python36.x86_64 : Interpreter of the Python programming language
python36-debug.x86_64 : Debug version of the Python runtime
python36-devel.x86_64 : Libraries and header files needed for Python development
python36-rpm-macros.noarch : RPM macros for building RPMs with Python 3.6
...
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yep.  Tried a few times.

**Comment by ThomasWaldmann** [comment]
Guess that looks like a packaging issue. @FelixSchwarz can you have a look?

**Comment by FelixSchwarz** [comment]
Unfortunately you need to enable the "powertools"/"code-ready-builder-..." repo: https://docs.fedoraproject.org/en-US/epel/#_el8

This is an unfortunate gotcha but only Red Hat can do something about it (I think Rocky+Alma Linux enable the repo by default).

**Comment by ThomasWaldmann** [comment]
Hmm, I remember new you having said that already in the past (but I forgot, sorry).

Sounds like we should have that in our docs?

**Comment by BloodBlight** [comment]
That worked, ish...
On RHEL (rather than CentOS), this will be the "CodeReady" repo:
```sudo subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms```

I am working now!  Should we close this or leave open for a documentation update(s)?

**Comment by ThomasWaldmann** [comment]
Leave it open until documented.

**Comment by ThomasWaldmann** [comment]
Does this also affect borg 1.2 and python >= 3.8?

**Comment by FelixSchwarz** [comment]
> Does this also affect borg 1.2 and python >= 3.8?

EPEL 8 does not have Python 3.8 and I'm not aware of plans to add it which means EPEL won't ship borg 1.2.

**Comment by ThomasWaldmann** [comment]
OK, so guess we either need a docs PR for 1.1-maint while that is still supported or it will resolve automatically when it is not any more.

**Comment by ThomasWaldmann** [comment]
Closing this, py36 is not supported any more. Also there is no future release planned for borg 1.1 branch.

**Comment by ThomasWaldmann** [comment]
Note:
- In RHEL 9, Python 3.9 is the default Python implementation. Since RHEL 9.2, Python 3.11 is available as the python3.11 package suite.
- in EPEL9, there is borg 1.2.
