### ISSUE TITLE
speed of borg create --stats / borg info

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6259]
master branch / borg 1.2: stats can be slower than before.

https://github.com/borgbackup/borg/discussions/6166#discussioncomment-2040866

**Comment by ThomasWaldmann** [comment]
Also check `borg info` (maybe same thing).

**Comment by ThomasWaldmann** [comment]
could be related to some fallback code that is used if borg 1.2 archive metadata is not present.

**Comment by fantasya-pbem** [comment]
Hey @ThomasWaldmann 
do you need more input for investigation? I could copy the description of my tests here and add more info if needed.

**Comment by ThomasWaldmann** [comment]
Wow, just tried `borg info REPO::ARCHIVE` with borg 1.2 on a borg 1.1 archive. That was slow!

**Comment by ThomasWaldmann** [comment]
Found the culprit:

`Archive.calc_stats()` is fast for borg 1.2 archives (gets summed up stats values from archive metadata), but expensive for borg 1.1 archives (has to read all archived items' metadata to sum up the desired stats values).

For a single archive, this is slower, but still tolerable.

But the real killer comes via "All archives": to correctly compute the total_size and total_csize values, it iterates over all archives in the manifest and calls `calc_stats()` for each of them (see `CacheStatsMixin.stats`). And that can get arbitrarily slow, depending on how many 1.1 archives exist in the repo.

**Comment by ThomasWaldmann** [comment]
@m3nu ^

**Comment by ThomasWaldmann** [comment]
Dropping the "All archives:" line from `borg info repo::arch` output would make that one OK, but `borg info repo` would be still very slow.

**Comment by ThomasWaldmann** [comment]
Guess we just could cache this locally. It's only very little information missing from the borg 1.1 archives, but expensive to compute.

**Comment by jdchristensen** [comment]
Does borg 1.2 show more info/stats than borg 1.1?  I'm asking because `borg info repo` seems fast with borg 1.1, so I'm curious why 1.2 would make this slower.  If it is because 1.2 shows extra info, then maybe the fallback should be to simply not display the extra info for 1.1 archives, but to continue to show what borg 1.1 shows.

**Comment by ThomasWaldmann** [comment]
@jdchristensen It's slow because it is correct, not because it shows more info.

borg < 1.2 had some issues due to how part files work, so the stats sometimes showed weird, more or less incorrect values.

**Comment by ThomasWaldmann** [comment]
btw, i shortly wondered why this affects borg create --stats (because if you use borg 1.2, this will have the new metadata in the archive header). But it also shows "All Archives:" line there and that's why it got painfully slow.

**Comment by m3nu** [comment]
Awesome! Will try this right away. 💃
