### ISSUE TITLE
Is it possible to have a stable name for hints/index files?

### ISSUE THREAD

**Issue by adept** [borgbackup/borg#626]
Hi,

I have daily backup of a fileset which changes infrequently. Fileset is rather large, and index.xxx file is more than 600 Mb large. 

Repository is s3sync-ed to amazon S3 for off-site storage. I do not do this every day, but when I do this, even if there were no new files added to the backup, I see that (big) old index file is removed and (equally big) new index file is uploaded to replace it. I understand that block counts are updated for all files, but there is a bunch of old-ish archives that reference blocks that do not correspond to live files anymore, and there's bound to be some data similarity between old and new index file. If index file had a stable name, s3sync would try to utilize this similarity to reduce amount of data transferred, but when names change, this is impossible.

Do you think that there is a way to give index.xxx file a stable name or inherent reason why this cant be done?

**Comment by ThomasWaldmann** [comment]
IIRC, the .xxx extension has to do with the transaction processing, so maybe not easy to change that in a safe way (and to be sure about it).

**Comment by ThomasWaldmann** [comment]
BTW, if your s3 offsite backup is just for the bigger desasters and for the smaller ones you always use your local repo, you could also just exclude index and hints - they can be rebuilt by borg check --repair.

BTW, only run s3sync while no borg backup is in progress.

**Comment by adept** [comment]
Ah, you are correct - I completely forgot about rebuilding! Thank you for
the reminder. This fixes the problem for me

On Fri, Feb 5, 2016 at 4:09 PM, TW <notifications@github.com> wrote:

> BTW, if your s3 offsite backup is just for the bigger desasters and for
> the smaller ones you always use your local repo, you could also just
> exclude index and hints - they can be rebuilt by borg check --repair.
>
> BTW, only run s3sync while no borg backup is in progress.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borgbackup/borg/issues/626#issuecomment-180421403>.
>



-- 
Dmitry Astapov
