### ISSUE TITLE
scandir: [Errno 60] Operation timed out

### ISSUE THREAD

**Issue by iron-udjin** [borgbackup/borg#6267]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.1.17

#### Operating system (distribution) and version.

FreeBSD 13-RELEASE

#### Hardware / network configuration, and filesystems used.

s3 bucket mounted by "rclone mount"

#### How much data is handled by borg?

1T

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create -s --compression auto,lz4 $REPOSITORY::${PREFIX}-`date +%Y-%m-%d` $BACKUP_PATH

## Describe the problem you're observing.

I need to backup s3 bucket of self hosted s3 (minio) which is mounted by "rclone mount" via FUSE. Sometimes backup process interrupts with error:
`scandir: [Errno 60] Operation timed out: '/mnt/shared/system/MediaPhoto/images/000'`
...because sometimes s3 answers slowly.

How can I increase borg I/O operations timeout?

Thank you!

**Comment by ThomasWaldmann** [comment]
That's a problem of the layers below borg and borg itself would wait forever I guess.

**Comment by iron-udjin** [comment]
In case of FUSE timeout it would complan in system log. But system log has no errors. It most likely timeout of python open() and scandir() calls.

`open: [Errno 60] Operation timed out: '/mnt/shared/system/Article/og_images/002/324/260/original/678a17e099c6ba0931968767697955b4.jpg'`

Is there way to increase the timeouts?

**Comment by iron-udjin** [comment]
When I run:
`# find /mnt/shared -type d -exec ls {} \;`
...before `borg create ...` backup creates fine.
It would be great to have configurable I/O timeout and number of retries.

**Comment by ThomasWaldmann** [comment]
this is the python `os.scandir` api. as you see, there is no timeout parameter.

https://docs.python.org/3.10/library/os.html?highlight=scandir#os.scandir

so, as i already said: this is a problem below borg and we can't do anything about it.
