### ISSUE TITLE
Interrupted borg delete / prune

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6284]
### Discussed in https://github.com/borgbackup/borg/discussions/6283

<div type='discussions-op-text'>

<sup>Originally posted by **sophie-h** February 11, 2022</sup>
It does look like borg prune has to start all over again if it is canceled while running in 1.1. Is that correct?

I'm currently trying to prune hundreds of archives but there does not seem to be an easy way to complete this.</div>

**Comment by ThomasWaldmann** [comment]
Guess we need something like `borg create --checkpoint-interval` also for `borg prune`.

It could just do commits every time the interval has passed. If one ctrl-c's after such a commit, it would have less to delete the next time it is invoked.

Also need to check that the updated manifest is written back / committed at that time.

**Comment by ThomasWaldmann** [comment]
Besides solving the above, there is of course also `compact_segments()` that can take rather long.
Needs to be checked how that does / could do intermediate commits.

**Comment by sophie-h** [comment]
Related issues terms of "continue, where it left off" #6039

**Comment by noplanman** [comment]
How do I go about pruning a large repository effectively?

I'm doing an hourly backup and hadn't set up pruning from the very start, which has me a repo with over 1000 archives now.
When I run the prune, each archive takes a few minutes to prune.

So basically, unless I let the prune finish completely in one run (taking hours and hours, in effect blocking any new backup due to the lock), I can never get the prune to finish?

**Comment by ThomasWaldmann** [comment]
@noplanman prune should be a bit faster in 1.2 as it only does the first part of the work (compared to < 1.2), but does not compact until you also invoke `borg compact`.

If you have a lot of archives to prune (e.g. because no prune ran until now), I'ld try pruning less, then compact, then prune some more, compact, etc. - one can do that by adjusting the timing (`--keep-*`) parameters carefully.

So don't prune 10000 archives at once, but rather 10 or 50 or 100. And prune regularly in future, then it is usually only very few archives it needs to delete.

**Comment by noplanman** [comment]
Thanks for your reply @ThomasWaldmann, that's what I was thinking too.

But I'm not sure how to actually make that happen, if my end goal is to keep archives with these rules:
`-H 24 -d 7 -w 4 -m 12`

I would have to manually calculate from all archives, which ones would fit in the "gaps" and have those removed in chunks.

Maybe what puzzles me the most, is why after an archive is pruned, it isn't actually pruned :thinking: 
What happens during this process that "goes lost" after cancelling the process?
```
...
Pruning archive (35/1047): 20220716-0318 Sat, 2022-07-16 05:18:47 [1967eba4fa5c79bc97a802b964caee49cb53435f914ecd19851aed0559a0129d]
Pruning archive (36/1047): 20220716-0218 Sat, 2022-07-16 04:18:52 [9cf96945989c54990e026508f471f42a1d7f33dc9b191a3d38ea70a2d01008d2]
Pruning archive (37/1047): 20220716-0118 Sat, 2022-07-16 03:18:54 [162fbaa1e3f787398f23e0e37fb5e45381b9dd8d6555626fad070719c2a594d3]
...
```

**Comment by ThomasWaldmann** [comment]
> Maybe what puzzles me the most, is why after an archive is pruned, it isn't actually pruned 🤔 What happens during this process that "goes lost" after cancelling the process?

It appends DEL tags to the repo for all chunks with refcount going to 0 and a COMMIT at the end.
If you cancel it in between, stuff won't be committed and thus considered invalid and rolled back.

borg compact will then really free up space by processing these DELs and removing the corresponding PUTs.

**Comment by ThomasWaldmann** [comment]
Note: guess we need to have this in borg 1.2.x - in the not so far future, a lot of people might decide to first prune many archives before `borg transfer`ring the rest to their new borg2 repo.

**Comment by jdchristensen** [comment]
@noplanman `--keep-within 1d` excludes all archives from the last day from pruning.  Then it ignores those, and continues with the usual processing of the other options to decide what to prune and keep.  So if you have also specified `-m 12`, then 12 additional archives would be excluded from pruning.

**Comment by ThomasWaldmann** [comment]
borg 1.2 prune now also explains why it kept the archives it kept (try -v --list --dry-run or so).

**Comment by noplanman** [comment]
Ok, I'd thought it might not be. Will continue to prune drop-wise with `--keep-within`, thanks!

**Comment by ThomasWaldmann** [comment]
moved the part about compaction to #6899.
