### ISSUE TITLE
Symlinks hide backup content in borg mount

### ISSUE THREAD

**Issue by henfri** [borgbackup/borg#6287]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

## System information. For client/server mode post info for both machines.
linux 5.13.9

#### Your borg version (borg -V).
borg 1.1.11

#### Operating system (distribution) and version.
Debian Buster

#### Hardware / network configuration, and filesystems used.
btrfs

#### How much data is handled by borg?
few bytes in the test-script

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
mkdir -p testdata/borg-bug/backup/folder
touch testdata/borg-bug/backup/folder/valid
ln -s testdata/borg-bug test
ln -s /etc etc

borg init -e none repo
borg create -v repo::backup test/backup/ ./test ./etc

echo "----------- borg list ------"
borg list repo::backup
# here, all files SEEM to be there.

echo "----------- Now via borg mount -----------"
# when the backup is mounted using borg mount, your unable to access the data stored in backup/folder
mkdir -p mnt
borg mount repo::backup mnt
find mnt/
find mnt/ -exec ls -l {} \;
echo "the contents of "backup" is missing here."
ls -l ./etc/ | head
echo "furthermore etc points to the files outside of the backup, which is a bit misleading"
umount mnt
rm -r repo testdata mnt etc
rm test
```
## Describe the problem you're observing.
1) the symlink to "test" points to "nothing" in the fuse mount. But for that reason test/testdata/* is not shown in the borg mount
2) symlinks in borg mount can point outside the backup, which is misleading and can be dangerous. I tried to copy data from my backup, but in fact I copied it from my harddrive (which had the partially erroneous data). Having confidence that I restored my files, I deleted the partially erroneous data and overwrote it with what I thought was my backup - which in the end was the same data...

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
see script above

#### Include any warning/errors/backtraces from the system logs
none

Best regards,
Hendrik

**Comment by ThomasWaldmann** [comment]
I think this is an invalid issue:
- `test`: borg backs up a symlink as a symlink (and does not follow it, does not back up the target fs object), this is expected behaviour.
- `borg-bug`: you did not backup this directory item, thus that directory is missing in the archive. that directory is the symlink target (thus the symlink is broken) and it is also the parent directory of `backup` (thus these files are unreachable).
