### ISSUE TITLE
How to make Borg aware of a new RSA key?

### ISSUE THREAD

**Issue by brannerchinese** [borgbackup/borg#6294]
My repository was initialized with `--encryption=repokey-blake2`, and all operations have gone very smoothly for some months. I'm using v. 1.1.17.

After generating a new local RSA key, I find that any Borg interactions with the host server now require me to enter my password. I assume there is a connection between the two events, but if there is a way to make Borg aware of the new RSA key, I don't see it described in the documentation on ReadTheDocs. Can you help?

**Comment by ThomasWaldmann** [comment]
This is not a borg problem, but something in your ssh setup.

The only thing notable here for borg usage is that is a good idea to make the first ssh connection manually (not via borg), in case ssh wants a one time "do you really want to connect to this unknown host" answer.

**Comment by brannerchinese** [comment]
Right you are — thank you very much. I had failed to copy the revised public key to `.ssh/authorized_keys`.
