### ISSUE TITLE
change compression, recompress existing chunks in repo

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#630]
create an archive with different compression as used in previous archives and do not consider chunks we already have (with old compression), but store all chunks again (using the new compression).

hmm, is this already done by `--no-files-cache`? if it doesn't quickly skip the files, it will chunk them and store them again into the repo (using the new compression).

if that works, we should document that. if it works, it would ofc only change the chunks that are referenced by the new archive. chunks only referenced by old archives would not get recompressed.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/30541836-change-compression-recompress-existing-chunks-in-repo)

**Comment by ThomasWaldmann** [comment]
maybe a bit cleaner is to iterate over all chunks in the repo, read (decrypt,decompress) the data and write it back (compress, encrypt) again.

when doing that, similar considerations as for deleting a lot of archives have to be done:
when rewriting the chunks, they are written to new segment files (needing space, potentially lots of space) and the old chunks in the old segment files are not needed any more. try to not double space requirements, but keep it down to ~ 1 segment file size.

**Comment by enkore** [comment]
"borg recreate" (#812) is now merged into master and allows this as well (among other things).

Skipping chunks already compressed with the specified compression is not implemented yet, but will likely come with a future PR.
