### ISSUE TITLE
I want to drive the windows port from release 1.2.0 on

### ISSUE THREAD

**Issue by thinkrapido** [borgbackup/borg#6302]
Hi all,

I want to drive the windows port development and need reviewers for this deed.
You can also help accomplish tasks.

If you are willing to do so, just add your request to this thread, with a comment of what you want to do.
In the first place, because there is no one else at the moment for the windows port, I need reviewers.

I've just started and want to get the first commits merged in the major branch of the 1.2.0 release from February, 22th 2022 on.

Thank you in advance.

Cheers,
Romeo

**Comment by FelixSchwarz** [comment]
Even though I'm not using Windows (much) I'd love to see borgbackup working as good as possible on Windows. Maybe you could use this issue as tracking bug and link new pull requests, layout short-term plans and mention required tasks so others could join in if they feel they can help out?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/projects < there's also this for project planning (and some older tickets).

**Comment by MatejKovacic** [comment]
I am also not using Windows, but windows is everywhere and it would be nice to have Borg running on it natively.

**Comment by OscarBeiro** [comment]
Hi, 
I have very limited time for this but I can help with some testing.
Currently using WSL and cygwin for this. I think having a native windows port would be a huge leap for this great tool.
Cheers,

**Comment by thinkrapido** [comment]
Thank you very much for your offers!
Currently, I have problems to get appveyor to work.
It does just use the wrong directory, I think, and that's all. Locally, I can get an borg.exe out of pyinstaller.
Here is my code https://github.com/borgbackup/borg/pull/6308, if you like to investigate.
I made several trial-and-error micro-commits. After several attempts appveyor kicked me and I don't know hat to start an appveyor test locally. It's to complicated to set it up and the documentation is not of help.

**Comment by thinkrapido** [comment]
> Hi, I have very limited time available, but I can help with some testing. I'm currently using WSL and Cygwin to backup two Windows machines; however, it is not usable in many environments. Having a native windows port would be a giant leap for this great tool. Cheers,

I switched to scoop and msys2, because I can get a very good support for openssl with this setup. See https://github.com/borgbackup/borg/pull/6308

**Comment by henfri** [comment]
Hi Romeo / thinkrapido,

great to hear that. 
I had looked at the Windows-Port previously, but my python skills are insufficient, I fear. 

Is there a binary already, that I can test?

Best regards,
Hendrik

**Comment by thinkrapido** [comment]
Hi Hendrik,

currently, there is only a pyinstaller build on my machine, because I can't get appveyor working.
This build is in no way optimized to handle windows specific stuff. So, there can only be the default help of borg.exe properly shown as it would be with the normal linux installation.
I'm afraid, you need to still wait for a testable borg.exe.

**Comment by henfri** [comment]
Will wait patiently :-)

**Comment by mmacura311** [comment]
Hi, I have several windows 10 machines available (all 64bit pro versions + one 64bit home), so I can do some tests once there is build available.

**Comment by thinkrapido** [comment]
@mmacura311 , you're welcome.
I have currently problems getting appveyor to run.
My setup in this commit https://github.com/borgbackup/borg/pull/6308 can't be joined, therefore.
The setup works if you follow the documentation details for windows.
It's pretty easy now and you get a pyinstaller exe out ouf it.
If you find any issues describe them in an approprieate issue file.

**Comment by thinkrapido** [comment]
@mmacura311 if you can help me appveyor to get working I'll be glad.

**Comment by santiagobiali** [comment]
I've been using borg on windows using cygwin for around 3 years and it's really fast (cygwin needs some tweeaks, but it's set and forget).
I run those in 4 windows servers and a debian machine as destination (cross-platform).

Looking forward to a better port to windows, tho.

**Comment by AnneTheAgile** [comment]
I could help with testing on win10 and tba a purism linux.
It seems like this is a good project and I'd really like to have my backups in good shape.
@santiagobiali what tweaks did you need to get it all to start? I don't have cygwin on my machine yet.

**Comment by santiagobiali** [comment]
@AnneTheAgile Here is the script I'm using to install cygwin and borg:
https://github.com/santiagobiali/borg-cygwin/blob/main/borg_install.ps1

If a new version of borg is released and no new dependencies are added, just run the script again to update borg.

Oh, feel free to remove some packages like "email", I added that to fit my needs.

**Comment by ThomasWaldmann** [comment]
I think we can close this ticket as there is no current activity.

Current state:
- cygwin and WSL more or less work.
- there is currently some ongoing work in master branch (borg2) to make the tests work on native win32 (but it still needs more work).

If somebody wants to help: just pick one of the "os: windows" labelled tickets and try to solve it.
