### ISSUE TITLE
require python >= 3.9

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6315]
borg 1.2 requires python >= 3.8.

so, for helium milestone (borg 1.3?), we can increase requirements considering the development will take a while and stable dists will have catched up by whenever it will get released and accepted into stable dists.

https://docs.python.org/3/whatsnew/3.9.html

**Comment by FelixSchwarz** [comment]
Just wanted to mention that the upcoming RHEL 9 will have Python 3.9 so please keep in mind that by dropping 3.9 you'll cut off RHEL 9 (unless users use the pyinstaller-based binaries).

**Comment by ThomasWaldmann** [comment]
The plan here is to support everything >= 3.9, so if RHEL9 has 3.9, that's fine.

**Comment by ThomasWaldmann** [comment]
Note: Ubuntu 22.04 LTS also has py39.

**Comment by braewoods** [comment]
Ubuntu 20.04 will likely not work as it only has python 3.8 for the general system. 3.9 is available but I suspect it won't have everything Borg needs.

**Comment by ThomasWaldmann** [comment]
There will soon be ubuntu 22.04 officially released (in contrary to borg master branch, which will take quite some time until it will see a release in form of borg 1.3.0). So I expect 20.04 users will either stay on 1.1.x or get 1.2.x via backports maybe. Noone will use master branch on ubuntu-oldstable after 2022-04.

If there are **developers** who prefer to run systems with older default python, there is always pyenv which can easily be used to get any addtl. python version one wants.
