### ISSUE TITLE
get rid of most bundled 3rd party code

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6316]
considering that our version requirements aren't that high, i guess we can remove the bundled code and require that respective libs / headers are present on the system.

see `src/borg/algorithms`
- lz4
- zstd
- xxhash
- not sure about the crc32 stuff there, can we get it from somewhere and not bundle it?

this will also enable us to simplify `setup*.py` significantly.

**Comment by FelixSchwarz** [comment]
just wanted to mention that Fedora probably needs a way to bundle msgpack. In Fedora packages often get minor version updates even within a stable release and borg is pretty picky about usable msgpack versions.

If the situation arise again (like the one we had with msgpack 1.0 vs 0.5.6) we might have to resort to bundling msgpack again. Of course we can carry the patches ourself but it would be helpful if the code structure to do so would be left in place. (yes, I know that borgbackup 1.2/master never bundled msgpack)

**Comment by ThomasWaldmann** [comment]
As we have `borg.helpers.msgpack` now in borg 1.2 as a wrapper around msgpack, we are a bit more flexible and can adapt to some degree to msgpack changes (as long as it is not totally broken).

The msgpack-bundling we have in 1.1-maint is not present in 1.2 and I would prefer to keep it like that.

Of course, if nothing else helped, we could bundle it again, but guess that would be the last option.

It would be nice if distributions would not "upgrade" to broken msgpack versions and cause unnecessary issues.
Maybe check borg testsuite before upgrading msgpack? :-)

**Comment by FelixSchwarz** [comment]
> The msgpack-bundling we have in 1.1-maint is not present in 1.2 and I would prefer to keep it like that.

me too.

> It would be nice if distributions would not "upgrade" to broken msgpack versions and cause unnecessary issues. Maybe check borg testsuite before upgrading msgpack? :-)

Currently maintenance of the msgpack package done by other packagers who were not as cooperative as I'd wished (though that was also before I was main packager for borgbackup and the previous borg packager was unresponsive). However I should probably talk to the current maintainers, maybe I can stay in the loop for msgpack updates in Fedora :-)

**Comment by ThomasWaldmann** [comment]
crc32 stuff:
- libcrcutil - hw accelerated and fast sw crc32/crc64 implementations
- python3-crc32c - also has hw accelerated and pure sw implementations

**Comment by FelixSchwarz** [comment]
`libcrcutil` (https://code.google.com/archive/p/crcutil/ ?) seems to be a copylib with a dead upstream so not the ideal candidate to package in Fedora.

**Comment by ThomasWaldmann** [comment]
Uh, google code archive, creepy.

**Comment by ThomasWaldmann** [comment]
all done, except the crc32 stuff: #6372

**Comment by ThomasWaldmann** [comment]
I searched around a bit, but didn't find something that could replace the crc32 code we have now as an external library:
- slice-by-8 algorithm
- CLMUL based algorithm

See there: https://github.com/borgbackup/borg/tree/1.2.0/src/borg/algorithms

Any ideas (besides just keeping it)?

**Comment by braewoods** [comment]
Perhaps we could look at the forks of Zlib that have accelerated CRC32 implementations use ARM and x86_64 SIMD code. It appears to still work even if the runtime host does not support it as it can fallback to slower generic code. This is what is in Chromium's bundled Zlib code so I'm guessing it works well if they're using it.

**Comment by ThomasWaldmann** [comment]
@braewoods well, we already have bundled code, so that would be only little progress (except maybe if we can use code that many people bundle and that gets better maintenance elsewhere).

Is there also a popular small library that contains that code? That would be progress as we could then unbundle that stuff.

**Comment by braewoods** [comment]
I highly doubt it as crc32 is usually only bundled with libraries or code that actually needs it. It's rarely standalone as a library. We'll probably still have to bundle something. Perhaps we could use GIT submodules?

**Comment by braewoods** [comment]
I'll look and see if any zlib alternatives have an accelerated CRC32 exposed.

**Comment by braewoods** [comment]
libdeflate looks like a contender and appears to already be packaged on several distributions. It appears to use accelerated CRC32 and there's a CRC32 algorithm exposed. Is there a way to benchmark this vs the existing code?

**Comment by ThomasWaldmann** [comment]
https://github.com/ebiggers/libdeflate had a quick look - looks nice and is packaged for misc. dists. not sure about netbsd / openbsd / openindiana availability.

**Comment by braewoods** [comment]
Perhaps we could introduce it as a submodule and statically link it if the target does not already have it as a separate package or system library?

**Comment by ThomasWaldmann** [comment]
https://github.com/dcwatson/deflate or we add a `crc32()` api there.

**Comment by braewoods** [comment]
Yea, we'd have to? It has no crc32 exposed to the python API.

**Comment by ThomasWaldmann** [comment]
yup. but guess that would be a one time effort and the least pain long term (hopefully). and as we would do that for borg 1.3, the dists not having libdeflate and deflate python package yet would have quite some time to package that.

@enkore what do you think about that?

**Comment by braewoods** [comment]
I could probably write a wrapper for it. I've written manual C python extensions before.

**Comment by ThomasWaldmann** [comment]
Let's see what @dcwatson and @enkore say.

**Comment by braewoods** [comment]
I finished a crc32 wrapper. We'll see if it gets accepted.

**Comment by ThomasWaldmann** [comment]
https://github.com/zlib-ng/zlib-ng/ that might be also an option.

**Comment by ThomasWaldmann** [comment]
this can be removed, we do not use our own blake2b code any more (but python hashlib) since a while): 

https://github.com/borgbackup/borg/blob/master/scripts/py36-blake2.py

**Comment by enkore** [comment]
>@enkore what do you think about that?

Sounds good to me. There's probably no rush to push 1.3 out so as you say there's a lot of time for distros, and there's always the possibility of building a small library as part of the borg package on their part. Getting rid of all this vendored stuff is very nice.

**Comment by ThomasWaldmann** [comment]
crc32 stuff fixed by #6387.

so, nothing left here to do.

except maybe to test `borg benchmark cpu` on misc platforms and check whether they have `libdeflate`.
