### ISSUE TITLE
FileNotFoundError thrown on borg create: hints-file missing

### ISSUE THREAD

**Issue by maximilian-walter** [borgbackup/borg#6331]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE / QUESTION

#### Your borg version (borg -V).

borg 1.1.16

#### Operating system (distribution) and version.

Debian 11.2 "Bullseye"

#### Hardware / network configuration, and filesystems used.

Asus PN41 Mini-PC with a Samsung 970 EVO Plus 2TB, local backup, no network involved
ext4 with LVM (encrypted)

#### How much data is handled by borg?

300GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
/usr/bin/borg create --compression zstd --exclude-caches --exclude '*/.Trash-*' '/var/borg/local::{hostname}-{now:%Y-%m-%d-%H%M%S}' '/var/nas' '/var/www'
```

## Describe the problem you're observing.

I use borg to create hourly backups on my NAS-server. Some times `borg create` throws an Exception, because a hints-file (like hints.2763.tmp) was not found inside the repository. On the next run, I get some warnings that segments are not found, but listed in compaction data (see logs below). The following runs never return any errors.

The data on the NAS rarly changes and the backuped files and the repository are stored on the same fast NVMe (in case you are wondering: I use the backup to be able to undo changes, e.g. files overwritten by mistake). The `borg create` command runs only for seconds, but it is possible that files are changed while the backup runs.

Are these Exceptions critical? What can I do to avoid them?

The same server also uses borg to backup the data to an external cloud-storage. This backup only runs once a day and never returns any errors.

Thanks for your advice!

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

No, the Exception occurs only sporadic.

I run `borg check --verify-data` on the repository and it did not found any errors. I can also mount the repository and restore data from it.

#### Include any warning/errors/backtraces from the system logs

Run with error:

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4690, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4622, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 595, in do_create
    create_inner(archive, cache)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 560, in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 530, in save
    self.repository.commit()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 476, in commit
    self.write_index()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 637, in write_index
    rename_tmp(hints_file)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 587, in rename_tmp
    os.rename(file + '.tmp', file)
FileNotFoundError: [Errno 2] No such file or directory: '/var/borg/local/hints.2763.tmp' -> '/var/borg/local/hints.2763'

Platform: Linux server 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64
Linux: Unknown Linux  
Borg: 1.1.16  Python: CPython 3.9.2 msgpack: 0.5.6.+borg1
PID: 519872  CWD: /root
sys.argv: ['/usr/bin/borg', 'create', '--compression', 'zstd', '--exclude-caches', '--exclude', '*/.Trash-*', '/var/borg/local::{hostname}-{now:%Y-%m-%d-%H%M%S}', '/var/nas', '/var/www']
SSH_ORIGINAL_COMMAND: None
```

The following run:

```
segment 2758 not found, but listed in compaction data
segment 2760 not found, but listed in compaction data
```

**Comment by ThomasWaldmann** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/borg/local/hints.2763.tmp' -> '/var/borg/local/hints.2763'
```
That looks like the filesystem / storage device used for `/var/local/borg` is losing files.

The .tmp file should be there, borg created it when the backup started.

That's a serious error and you should find its root cause:
- run a memory tester like memtest86+, just to make sure RAM is ok before proceeding
- check if the nvme device is running properly (maybe `smartctl`, do a full read using `dd`, check kernel messages)
- run fsck on the local filesystems

**Comment by maximilian-walter** [comment]
Hello @ThomasWaldmann, thank you for your fast response!

I tried the following:

- Memtest86
- The extended self-test of the SSD (started in the UEFI)
- Get SMART status via `smartctl -a`
- fsck
- mprime for stress-testing (used Large FFTs and the blend-test)
- Checked logs (dmesg, /var/log/syslog)

All tests did not return any errors, also no suspicious log-messages were found.

Now I'm litte baffled. The server does run absolutely flawless, and I did not have any problems using my data in the last months. Only the erratic errors from the borg backup are alarming.

**Comment by ThomasWaldmann** [comment]
Do you have some other process running there that removes `*.tmp` maybe?

**Comment by ThomasWaldmann** [comment]
Also, can you check uptime and whether the machine maybe crashes or reboots suddenly while or short after borg is running.

**Comment by maximilian-walter** [comment]
Hello @ThomasWaldmann ,

> Do you have some other process running there that removes *.tmp maybe?

No, but a cronjob could delete files inside the backed up directories. These files are not important, so I changed the exclude-paths to remove them from the backup.

But in this case (a file which should be backed up gets deleted while the backup is running) the error message should include the path of the missing file (like `/var/www/vhosts/example/tmp/my-now-deleted-session-file`)?! Not the path to a hints-file.

> Also, can you check uptime and whether the machine maybe crashes or reboots suddenly while or short after borg is running.

The server did not crash/restart. I looked at the monitoring and there are no anomalies like increased system load or a reseted uptime visible. The server is also not able to restart unnoticed: Because of the disk-encryption it needs an passphrase to boot.

**But the monitoring could indeed be a problem:** I wrote a plugin for Munin to check the repository-size (using `borg info`) and age of the last backup (using `borg list`). Both are called every five minutes. They use the `--bypass-lock` argument to not interfere with the regular backups. Could this be a problem?

But then I would not undertstand why the error occurs only some times: The backup runs 24 times a day, but there are often many days between these exceptions.

**Comment by ThomasWaldmann** [comment]
I only meant `*.tmp` file deletions inside the repo dir. The error msg is correct.

`--bypass-lock` could well be a problem, not sure.

this option was added primarily to support repos on r/o filesystems. but as locks are there to avoid issues with parallel usage of a repo and you did exactly that by bypassing the locks, it could be the root cause of your problem. that it doesn't happen more frequently could be the result of some race condition. so i'ld say don't do that and you'll see if the problem goes away.

**Comment by ThomasWaldmann** [comment]
From the `--bypass-lock` docs:

Warning

If you do use --bypass-lock, you are responsible to ensure that no other borg instances have write access to the repository. Otherwise, you might experience errors and read broken data if changes to that repository are being made at the same time.

**Comment by maximilian-walter** [comment]
I removed the Munin-plugin, so no parallel usage can occur anymore. I used the flag only because in my understand the list and info commands are read-only, so it should be safe. Maybe this was an false assumption and I should have looked at the code first. :-)

I will see if this fixes my problem. Thanks for your exceptionell support!

**Comment by ThomasWaldmann** [comment]
TODO if someone has some time to spare:

Analyse what exactly happened here (and whether it still happens using the latest code).

Maybe this could be useful in case we can easily improve that or in case we'll ever want to achieve lock-free operations.

**Comment by ThomasWaldmann** [comment]
Couldn't resist and did some analysis:
- `Repository.write_index` (called by `.commit`, `.replay_segments` and `.check`) is not made for concurrency (and with locks, there is also no need for concurrency there)
- see how it deals with misc. `*.tmp` files (renaming them, deleting them)
