### ISSUE TITLE
_hashindex.c compiler warnings

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6333]
mostly harmless, but still annoying.

check if we can get rid of these by adding some casts.

**Comment by braewoods** [comment]
I was looking through the _hashindex.c file and I was surprised to see that the C code uses unsigned char as the pointer type for the value. Given how it appears to be intended to be a general purpose data structure, why wasn't void used? This is the typical way to silence warnings due to harmless pointer mismatches.

**Comment by ThomasWaldmann** [comment]
Guess the problem with `void *` is that there is no standardized pointer arithmetic with them, while `unsigned char *` is pointing to bytes and does arithmetic byte-wise.

**Comment by braewoods** [comment]
Fair enough. I've seen that issue compensated for by reassigning it to a local pointer of the correct type.

**Comment by braewoods** [comment]
e.g.
```
void foo(const void* arg1) {
const char* arg = arg1;
}
```

**Comment by braewoods** [comment]
I ask because we can either fix it in the hashindex functions or where it is called. The void pointer approach is more future proof though.

**Comment by ThomasWaldmann** [comment]
Do it as you proposed, guess this is the best way.

When dealing with bytes / byte-wise pointer arithmetic, guess the local pointer needs to be `unsigned char *`.

**Comment by braewoods** [comment]
I don't think it's needed anywhere but one function after reviewing it. The key argument is generally only one type from what I've seen. It's the value argument that really benefits.

**Comment by braewoods** [comment]
Indeed but I believe that normally triggers a warning if it occurs because it's a bad practice.

**Comment by braewoods** [comment]
Interesting. It's available but not enabled by default. `-Wpointer-arith` does warn about it.

**Comment by ThomasWaldmann** [comment]
yeah, let's wait a bit, i am doing big changes in setup right now.
