### ISSUE TITLE
Borg backup no output when >>tofile

### ISSUE THREAD

**Issue by kirys** [borgbackup/borg#6342]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

Rocky linux 8.5 

#### Your borg version (borg -V).

1.1.17

#### Operating system (distribution) and version.

Rocky linux 8.5 

## Describe the problem you're observing.

Borg create give no output when redirected to file, other commands works as expeced.

Output is produced if the output goes to the terminal

                borg create --stats -v --compression auto,zstd,6 \
                --exclude-from "/etc/backup/filelists/full-exclude.files" \
                --exclude-caches \
                /mnt/bck/loc/::{hostname}-{now:%Y-%m-%d-%H:%M} \
                                /path/list\
                                --show-version >>/var/log/backup.log

I'm doing something wrong?
Thank You
K.

**Comment by RonnyPfannschmidt** [comment]
borg outputs to the terminal by default, if you rediret you use that, the tool tee is commonly used in combination with nomal output

```
  borg create --stats -v --compression auto,zstd,6 \
            --exclude-from "/etc/backup/filelists/full-exclude.files" \
            --exclude-caches \
            /mnt/bck/loc/::{hostname}-{now:%Y-%m-%d-%H:%M} \
                            /path/list\
                            --show-version |tee /var/log/backup.log
```

**Comment by ThomasWaldmann** [comment]
borg usually outputs log on `stderr` because in needs `stdout` for data with some commands.

**Comment by ThomasWaldmann** [comment]
@kirys can you edit the issue title? "Boige" is not an english word AFAIK.

**Comment by kirys** [comment]
currently borg is called by a script and the whole script is run by cron
/usr/scripts/doBackup.sh nightly 2>&1 >>/var/log/backup.log

so both stdout and stderr should go to the log.
borg info works, while create gave no output.
I didn't think that "tee" had a different behavior other than tee write to both file and stdout.
I'll make a check and let you know
Bye
K.

**Comment by kirys** [comment]
> @kirys can you edit the issue title? "Boige" is not an english word AFAIK.

sorry a typo

**Comment by jdchristensen** [comment]
> /usr/scripts/doBackup.sh nightly 2>&1 >>/var/log/backup.log

If your intention is that stdout and stderr both go to backup.log, then you've got the order wrong in your redirections.  The above makes stderr to go wherever stdout is going, and then separately changes where stdout is going.  Compare:

```
$ ls fdshj 2>&1 >/dev/null
ls: cannot access 'fdshj': No such file or directory
$ ls fdshj >/dev/null 2>&1
```
You need to put `2>&1` after the redirection of stdout.

**Comment by kirys** [comment]
thank you!

**Comment by ThomasWaldmann** [comment]
Guess we can close this, rather a shell scripting issue than a borg issue.
