### ISSUE TITLE
Upgrading to Borg 1.2.0 on Ubuntu 21.10 not possible

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [borgbackup/borg#6349]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes 

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).
borg 1.1.17

#### Operating system (distribution) and version.
OS: Ubuntu 21.10 x86_64
Kernel: 5.14.10-051410-generic

#### Hardware / network configuration, and filesystems used.
Btrfs

#### How much data is handled by borg?
Irrelevant

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`pip install borgbackup --upgrade`

## Describe the problem you're observing.
    Collecting borgbackup
      Using cached borgbackup-1.2.0.tar.gz (4.0 MB)
      Preparing metadata (setup.py) ... error
      error: subprocess-exited-with-error

      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [9 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/tmp/pip-install-l7txgtcl/borgbackup_e56a8cb4300146e9832f7646f46de9f5/setup.py", line 185, in <module>
              setup_crypto.crypto_ext_kwargs(pc, system_prefix_openssl),
            File "/tmp/pip-install-l7txgtcl/borgbackup_e56a8cb4300146e9832f7646f46de9f5/setup_crypto.py", line 32, in crypto_ext_kwargs
              raise Exception('Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX')
          Exception: Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX
          Warning: can not import pkgconfig python package.
          [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Reproduce by `pip install borgbackup --upgrade`

**Comment by ThomasWaldmann** [comment]
If nothing else helps, read the docs? :-)

**Comment by FabioPedretti** [comment]
For the record there is also this Ubuntu PPA: https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup
But since it doesn't provide packages for impish / 21.10, I backported borgbackup 1.2.0 in my test PPA:
https://launchpad.net/~oibaf/+archive/ubuntu/test/+packages?field.name_filter=borg&field.status_filter=published

**Comment by wkordalski** [comment]
I had the same issue on ArchLinux.

```sh
mkvirtualenv test
# We are inside test venv from now
pip install borgbackup
# Cannot find OpenSSL error here
```

I had OpenSSL installed.
It turned out that specifying the `BORG_OPENSSL_PREFIX` is enough.

```sh
BORG_OPENSSL_PREFIX='/usr' pip install borgbackup
```

**Comment by ThomasWaldmann** [comment]
Sure, the docs say very clearly that you must install pkgconfig first and then `pip install borgbackup`.

pkgconfig is a way to automatically locate libs and header files IF the library supports getting found by pkg(-)config (which a lot do).

**Comment by braewoods** [comment]
@ThomasWaldmann Does it also document how you need to install python3-pkgconfig? I had to do that for system python on Ubuntu systems.

**Comment by braewoods** [comment]
On closer inspection, it appears Borg doesn't even have the python pkgconfig module listed as a dependency. Is this an oversight? It might explain why they're having issues with PIP.

**Comment by ThomasWaldmann** [comment]
This is a documented dependency, see our docs. We can't solve this within `setup.py` because `pkgconfig` is already required at import time of `setup.py`.

**Comment by braewoods** [comment]
So it's not possible to do without rework of setup.py. Understood.

**Comment by Unrepentant-Atheist** [comment]
I dum dum...

Missed `pip install pkgconfig`

**Comment by Unrepentant-Atheist** [comment]
Having missed `pip install pkgconfig` and installed it then doing `pip install -U borgbackup` results in: https://pastebin.com/9Yxy5LVY

**Comment by ThomasWaldmann** [comment]
You still do not have all requirements installed, please just read our install docs.
```
      src/borg/platform/linux.c:699:10: fatal error: sys/acl.h: No such file or directory
```

**Comment by Unrepentant-Atheist** [comment]
Yeah, yeah, okay, my bad... can't read for shite...

    sudo apt-get install python3 python3-dev python3-pip python3-virtualenv \
    libacl1-dev libacl1 \
    libssl-dev \
    liblz4-dev libzstd-dev libxxhash-dev \
    build-essential \
    pkg-config python3-pkgconfig

Well, okay, now it work. However, question:

When I create the virtualenv, it doesn't take the fuse installation into it. Thus, whenever I try `pip install borgbackup[pyfuse3]` inside a virtualenv, it doesn't work, because not fuse is installed in the virtualenv. Outside of it, it exists.

**Comment by ThomasWaldmann** [comment]
Just read on in our docs:
```
sudo apt-get install libfuse-dev fuse    # needed for llfuse
sudo apt-get install libfuse3-dev fuse3  # needed for pyfuse3
```

```
pip install borgbackup[llfuse]  # to use llfuse
pip install borgbackup[pyfuse3]  # to use pyfuse3
```

You need to choose either `llfuse` or `pyfuse3` depending on which libfuse you have.

**Comment by Unrepentant-Atheist** [comment]
Yes, I get that, but that's for apt , when I create a virtualenv the fuse pip packages are not there. They are in the normal environment.

**Comment by ThomasWaldmann** [comment]
You need to install the python stuff (like llfuse or pyfuse3) into the virtual env you have active.
Libraries and headers can be installed normally on the system level (like sudo apt install libfuse3-dev).
