### ISSUE TITLE
windows: AppVeyor support needed

### ISSUE THREAD

**Issue by thinkrapido** [borgbackup/borg#6376]
AppVeyor leaves me out to analyze the code, because I bombarded appveyor with too many commits.

I just want to get https://github.com/borgbackup/borg/pull/6308 working.

It seems that there is a conflict with the two directories /c/projects/borg and /appveyor. I don't know how to resolve this.

**Comment by ThomasWaldmann** [comment]
We migrated from appveyor to github action.
