### ISSUE TITLE
Repo redundancy as an afterthought

### ISSUE THREAD

**Issue by cristianrz** [borgbackup/borg#6389]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

N/A

## Describe the problem you're observing.

I have a borg repo and I wanted to have an extra repo for redundancy just in case something happens to the first repo or the drive where that repo is located. Not sure if there's any way at all to do this without losing all my history of archives.

If I just rsync and try to `borg repo1` and `borg repo2` then borg will complain about having two repos with the same ID, and if I change the ID, I am guessing because of encryption, borg will complain with

```
Data integrity error: Invalid segment entry header [segment 2, offset 418360678]: unpack requires a buffer of 41 bytes"
```

Reading the documentation the only way I can find to do this is just rsync to the second drive periodically but I am quite reluctant to do that since any errors on the first repo will just duplicate.

**Comment by ThomasWaldmann** [comment]
I you want a disk with a 2nd repo, you just run `borg init` to create a fresh repo there and fill it with `borg create`.

**Comment by cristianrz** [comment]
One of the main points of my question was how to do this without losing the historic backups on my 2nd drive. I've got around 2 years of backups of the 1st repo which, if I just start a second repo from scratch would not be "protected". Maybe there's something trivial that I'm not seeing.

**Comment by ThomasWaldmann** [comment]
There is no "perfect and fast" way to do that (and this is due to how borg tries to work in a very secure way).

Options:
- borg list --short, loop over archive names and call borg extract and borg create (slow, needs disk space)
- borg list --short, loop over archive names and call borg export-tar | borg import-tar (lossy, see related tickets)
- borg mount old repo, loops over archive directories and run borg create with each (lossy, FUSE does not support all file metadata e.g. ACLs)

**Comment by cristianrz** [comment]
Ok, that helps. When you say lossy do you mean permissions/attributes?

My backups are mainly office stuff (documents, pictures, videos, etc) so I don't really care about permissions (I think), what approach would you recommend?

**Comment by ThomasWaldmann** [comment]
I mean metadata (like ACLs, xattrs, flags). Basic metadata (like user, group, mode) is preserved (be careful, better check).

Some people have tried the mount-based method, which is rather easy to use, but maybe not very efficient.

The export-tar / import-tar method is a bit newer, but maybe a bit more efficient than the mount-based one.

In any case, make sure that the newly made repo actually contains what you need.

**Comment by santiagobiali** [comment]
You can duplicate the repository, it's very easy actually.

1. Rsync the repo to another disk/location
2. On the repository (new disk) open "newPathNewDiskRepo/config" and change the "id" to a new id (you can only change the last digit, let's say its "id = 59[...]e6", change it to ""id = 59[...]e7" and save.
3. In the cache (not the new disk, on the server running borg create) duplicate the folder ".cache/borg/59[...]e6" and change it's name to "59[...]e7" (the same as in step 2)
4. In ".cache/borg/59[...]e7/config" (the duplicated one) change:
    repository = 59[...]e7
    previous_location = newPathNewDiskRepo
5. In ".config/borg/keys" find the key to the repo, duplicate the file, open it and change the first line with the new id "59[...]e7"
6. In  ".config/borg/security" duplicate the folder "59[...]e6" and rename it to "59[...]e7"
7. In ".config/borg/security/59[...]e7/location" change the path to the new one "newPathNewDiskRepo"

8. Test it: run borg list && borg info on the new repo.

Now just duplicate your backup script, change the destination path to the new repo and run both scripts (old and new) to get redundancy.

**Comment by ThomasWaldmann** [comment]
@santiagobiali if you afterwards use both repos independently (e.g. by creating new backup archives), you make the repos cryptographically insecure (an attacker could break the encryption) due to AES-CTR mode nonce reuse. See the borg docs for more details.
