### ISSUE TITLE
1.2.0 fails with GLIBC_2.28 not found on ReadyNAS

### ISSUE THREAD

**Issue by jonknapp** [borgbackup/borg#6391]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue - not sure I'd label it as a bug as I'm unsure if ReadyNAS is supported though it has historically worked.

#### Your borg version (borg -V).

version 1.1.17 works fine with `borg-linux64-1.1.17`. Version 1.2.0 does not work.

#### Operating system (distribution) and version.

```
[~] # cat /etc/os-release 
NAME="QTS"
VERSION="4.3.6 (20220103)"
ID=qts
PRETTY_NAME="QTS 4.3.6 (20220103)"
VERSION_ID="4.3.6"

[~] # cat /proc/version
Linux version 4.2.8 (root@U16BuildServer46) (gcc version 4.9.2 (toolchain config: [gcc-4.9.2 binutils-2.25 glibc-2.21]) ) #1 SMP Mon Jan 3 01:03:51 CST 2022
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Running borg throws the error immediately.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yep. Here's the script I use to download the latest version from Github releases, create a small wrapper script for environment setup, and symlink it for use on the ReadyNAS.

```sh
BORG_VERSION=1.2.0

curl --location "https://github.com/borgbackup/borg/releases/download/$BORG_VERSION/borg-linux64" --output "borg-linux64-$BORG_VERSION"
chmod +x "borg-linux64-$BORG_VERSION"
rm borg.sh
touch borg.sh
echo "export BORG_CACHE_DIR=/share/CE_CACHEDEV1_DATA" >> borg.sh
echo "/root/borg-linux64-$BORG_VERSION \"\$@\"" >> borg.sh
chmod +x borg.sh
ln -fs "/root/borg.sh" /usr/bin/borg
```
The full error I receive is:

```
[3024] Error loading Python lib '/tmp/_MEIMBjpPB/libpython3.9.so.1.0': dlopen: /lib/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIMBjpPB/libpython3.9.so.1.0)
```

**Comment by ThomasWaldmann** [comment]
your linux is rather old, so try the `borg-linuxold64` from there:

https://github.com/borgbackup/borg/releases/tag/1.2.0

**Comment by jonknapp** [comment]
Works perfectly! Thank you very much.

**Comment by miguno** [comment]
> your linux is rather old, so try the `borg-linuxold64` from there:
> 
> https://github.com/borgbackup/borg/releases/tag/1.2.0

Thanks, this helped me, too. Synology NAS with a deprecated DSM 6.x version.
