### ISSUE TITLE
simplify libs setup

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6392]
in master branch, we recently got rid of most of the code in `setup_*.py`.

guess we now could put all the remaining code into a `setup_libs.py` or maybe after a little refactoring and deduplication of code maybe even directly into `setup.py`.

**Comment by m3nu** [comment]
Can I work on this? Already doing some packaging, which is related.

Would also suggest to move some meta-data type stuff to `setup.cfg` and only keep actual code in `setup.py`. E.g. the classifiers: https://github.com/borgbackup/borg/blob/master/setup.py#L250

**Comment by ThomasWaldmann** [comment]
This would currently conflict with the already started crc32 work (see my PR, which is blocked by the `deflate` package release, which is still todo).

But after that is merged, sure!

**Comment by m3nu** [comment]
Ok, will keep an eye on this.

**Comment by ThomasWaldmann** [comment]
I'm finished with the crc32 / libdeflate stuff.
