### ISSUE TITLE
Windows Port ToDo List

### ISSUE THREAD

**Issue by thinkrapido** [borgbackup/borg#6402]
**This here will be the summary of all ToDo's for the windows port.**

What's this all about: https://github.com/borgbackup/borg/issues/6302

**Tasks in descending priority:**

- [ ] https://github.com/borgbackup/borg/pull/6308

**Done Tasks:**

- tbd

**Comment by thinkrapido** [comment]
@ThomasWaldmann , please look into the history of open windows feature requests and pm me to fill this new list. Afterwards, close the open issues which aren't relevant any more.

**Comment by ThomasWaldmann** [comment]
I don't think it is a good idea trying to put all the issues into a single one. I'ld suggest using a project (see at the right side) as "the list" and keeping the issues separate. that also helps focussing on a small task and enables closing such issues when done while a "monster issue" with everything windows inside can likely never get closed.

**Comment by ThomasWaldmann** [comment]
see there https://github.com/borgbackup/borg/projects/6

**Comment by ThomasWaldmann** [comment]
There are also some tickets labelled with "os: windows".

Just pick whatever you like from there and add it to the project's columns: https://github.com/borgbackup/borg/labels/os%3A%20windows
