### ISSUE TITLE
borg create fails with Local Exception, borg.remote.ConnectionClosed: Connection closed by remote host and BrokenPipeError: [Errno 32] Broken pipe.

### ISSUE THREAD

**Issue by dataprolet** [borgbackup/borg#6442]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Issue

## System information. For client/server mode post info for both machines.
Client is my desktop computer, here's a [full output](https://pastebin.com/YBSNh0pS) of `inxi -Fazi`.
Server is a [Hetzner Storagebox BX11](https://www.hetzner.com/storage/storage-box/bx11).

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
Arch Linux, Kernel 5.16.14-zen1-1-zen.

#### Hardware / network configuration, and filesystems used.
AMD Ryzen 5 3600, MS-7C02
Ethernet connection from PC to switch to router.
Using ufw limit ssh (port 22) and Pi-hole in case, that's somewhat relevant.
Filesystem is ext4 on LVM on LUKS.

#### How much data is handled by borg?
I'm currently backing up multiple directories containing around 670 GB in total, from which I successfully transferred 280 GB in between errors already.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
#!/usr/bin/env bash
export BORG_PASSPHRASE="xxx"
LOG="/home/user/folder/borg.log"
BACKUP_USER="user"
REPOSITORY="ssh://${BACKUP_USER}@${BACKUP_USER}.domain-tld:23/./folder/repo/"
exec >> >(tee -i ${LOG})
exec 2>&1
echo "Started: $(date)"
sudo borg create -v --stats -C auto,zstd        \
        $REPOSITORY::'{now:%Y-%m-%d_%H:%M}'     \
        /home/user/folder/subfolder1                 \
        /home/user/folder/subfolder2                \
        /home/user/folder/subfolder3              \
        /home/user/folder/subfolder4                 \
        /home/user/folder/subfolder5                   \
echo "Finished: $(date)"
```

## Describe the problem you're observing.
Borg appears to randomly fail to transfer data and returns the same error, even though I'm using the exact same commands. Some days I transfer hundreds of gigabyte without a problem, sometimes the command fails after some time without transferring any data and sometimes a few gigabytes are transferred before failing. That's why I managed to transfer roughly 280 GB already.
Borg always asks for the passphrase of the repository and after I enter it I can see an increase in CPU usage and sometimes also network usage (upload, obviously), so it is in fact doing something before failing.

I already contacted the online storage provider and they replied that there is no problem with my online storage. They also told my to use `mtr` to check the connection and it only showed packet loss on [the 7th hop](https://docs.hetzner.com/robot/dedicated-server/troubleshooting/network-diagnosis-and-report-to-hetzner/#1-packet-loss-that-disappears-until-the-target-hop), but no packet loss on the host.

While typing this a tried to start Borg over and over again, sometimes failing right away, one time failing after transferring around 2 GB and now running for another 2-3 GB. But I just see the upload speed dropping and assume it's gonna fail again in a couple of minutes.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I can somewhat reproduce it, because whereas Borg returns the error most of the time, sometimes it doesn't and I don't know why.

Also I already asked on the Borg subreddit [for help](https://www.reddit.com/r/BorgBackup/comments/ta50m7/encrypted_backup_over_ssh_fails_with_local/) and added `ServerAliveInterval 10` to my clients SSH config and `ClientAliveInterval 60` to the hosts SSH config.

#### Include any warning/errors/backtraces from the system logs
```
Started: Sa 12. Mär 15:45:37 CET 2022
[sudo] password for user: 
Enter passphrase for key ssh://user@domain.tld:23/./folder/repo: 
Creating archive at "ssh://user@domain.tld:23/./folder/repo/::2022-03-12_15:45"
Remote: client_loop: send disconnect: Broken pipe
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 668, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 605, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 813, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 813, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 813, in _rec_walk
    self._rec_walk(
  [Previous line repeated 8 more times]
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 779, in _rec_walk
    status = self._process_any(path=path, parent_fd=parent_fd, name=name, st=st, fso=fso, cache=cache,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 681, in _process_any
    return fso.process_file(path=path, parent_fd=parent_fd, name=name, st=st, cache=cache)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1407, in process_file
    self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1234, in process_file_chunks
    item.chunks.append(chunk_processor(chunk))
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 1222, in chunk_processor
    chunk_entry = cache.add_chunk(chunk_id, data, stats, wait=False)
  File "/usr/lib/python3.10/site-packages/borg/cache.py", line 947, in add_chunk
    self.repository.put(id, data, wait=wait)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 709, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 826, in call_many
    raise ConnectionClosed()
borg.remote.ConnectionClosed: Connection closed by remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 634, in __exit__
    self.rollback()
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 476, in do_rpc
    return self.call(f.__name__, named, **extra)
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 709, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 779, in call_many
    send_buffer()  # Try to send data, as some cases (async_response) will never try to send data otherwise.
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 719, in send_buffer
    written = self.ratelimit.write(self.stdin_fd, self.to_send.peek_front())
  File "/usr/lib/python3.10/site-packages/borg/remote.py", line 417, in write
    written = os.write(fd, to_send)
BrokenPipeError: [Errno 32] Broken pipe

Platform: Linux Desktop 5.16.14-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 11 Mar 2022 17:40:33 +0000 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.10.2 msgpack: 1.0.3 fuse: None [pyfuse3,llfuse]
PID: 14787  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'create', '-v', '--stats', '-C', 'auto,zstd', 'ssh://user@domain.tld:23/./folder/repo/::{now:%Y-%m-%d_%H:%M}', '/home/user/folder/subfolder1', '/home/user/folder/subfolder2', '/home/user/folder/subfolder3', '/home/user/folder/subfolder4', '/home/user/folder/subfolder5']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
Not a borg issue, but a ssh connection issue.

There's quite some stuff about that already in the docs / FAQ and also in other tickets here in the issue tracker.
