### ISSUE TITLE
Not able to install via pip

### ISSUE THREAD

**Issue by schulzalbrecht** [borgbackup/borg#6444]
## Have you checked borgbackup docs, FAQ, and open Github issues?
yes, normally the issue was solved by upgrading setuptools. this is not my case, I have the latest version of setuptools.

## Is this a BUG / ISSUE report or a QUESTION?
BUG

## System information. For client/server mode post info for both machines.
MacOS, zsh 5.8, python 3.10.2, pip 22.0.4

#### Your borg version (borg -V).
Trying to install version 1.2.0

#### Operating system (distribution) and version.
macOS Monterey 12.2.1

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`pip install pkgconfig ; pip install "borgbackup==1.2.0"`

## Describe the problem you're observing.
borg Installation doesn't complete due to an error likely in borg and not in pip.

#### Include any warning/errors/backtraces from the system logs

Output of the above command.
```zsh
Requirement already satisfied: pkgconfig in /Users/user/.local/share/virtualenvs/borg-backup-5gWH0AFw/lib/python3.10/site-packages (1.5.5)
Collecting borgbackup==1.2.0
  Using cached borgbackup-1.2.0.tar.gz (4.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zb/b9l803ps75n5fqqgrb_nzm_c0000gn/T/pip-install-7h1rkd6p/borgbackup_aca14694baa546e4ac25344728db8273/setup.py", line 185, in <module>
          setup_crypto.crypto_ext_kwargs(pc, system_prefix_openssl),
        File "/private/var/folders/zb/b9l803ps75n5fqqgrb_nzm_c0000gn/T/pip-install-7h1rkd6p/borgbackup_aca14694baa546e4ac25344728db8273/setup_crypto.py", line 32, in crypto_ext_kwargs
          raise Exception('Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX')
      Exception: Could not find OpenSSL lib/headers, please set BORG_OPENSSL_PREFIX
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by infectormp** [comment]
Why no one uses search? https://github.com/borgbackup/borg/issues/6390

**Comment by ThomasWaldmann** [comment]
closing as duplicate
