### ISSUE TITLE
Duplicated File List

### ISSUE THREAD

**Issue by zecKiLL** [borgbackup/borg#6447]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## Describe the problem you're observing.

Given the built-in deduplication functionality provided by Borg and the metadata stored in the file cache, would it be feasible to add a feature to Borg which could list the duplicated files (binary identical files, regardless of filenames or dates) in the backup tree, solely by utilizing the data in the file cache, essentially turning Borg into a super-fast duplicated file search engine?

Thank you very much in advance,
zK

**Comment by ThomasWaldmann** [comment]
the files cache only has `H(filename) -> (timestamp, inode, size, chunkids_list)`.

so, you don't have a readable filename, just the hash of it and also no overall hash of the contents (but a list of chunk hashes).

**Comment by zecKiLL** [comment]
Hi Thomas,

Thank you for your quick reply.

Understood about the filenames are missing... 

On the other hand, matching chunkids_list from different entries should indicate files with binary identical contents?

Thanks again,
zK

**Comment by ThomasWaldmann** [comment]
Yes, if the list is identical, the contents of the file are identical (but not necessarily the metadata).

**Comment by felipesanches** [comment]
I believe this issue should be reopened with its original question being converted into a feature request.

**Comment by ThomasWaldmann** [comment]
As I said above, the files cache does not contain filenames (paths), but only the hashes of each filename.

Also, the lookup is by H(filename), so you can quickly find an entry for a given path.

But you can't quickly find a duplicate OTHER file, that would require iterating over all cached entries and comparing their chunk list to the current chunk list. And even after you have found an entry with the same chunk list, you still would not know its filename.

Thus, this can't be implemented using the files cache.
