### ISSUE TITLE
test new crc32 implementation on misc platforms

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6448]
master branch

we now require `libdeflate` there and currently use it on all platforms except macOS (where `zlib.crc32` is much faster).

TODO:
- check libdeflate availability on misc. dists (this is mainly a task for distribution package maintainers who want to support borg 1.3 later)
- check whether `libdeflate` can be auto-discovered via `pkg-config`
- run `borg benchmark cpu` and check whether the faster crc32 implementation is used

**Comment by Begasus** [comment]
From the 1.2-maint branch: related #4117
```
/boot/system/non-packaged/bin> borg -V
resolve symbol "static_assert" returned: -2147478780
Traceback (most recent call last):
   File "/packages/python38_x86-3.8.12-1/.self/non-packaged/lib/python3.8/site-packages/borgbackup-1.2.1.dev65+gb5443da6-py3.8-haiku-1-BePC.egg/borg/archiver.py", line 39, in <module>
      from .algorithms.checksums import crc32
ImportError: Symbol not found
```
Only needed an export for the openssl headers, didn't mention libdeflate (from what I saw in the build)

**Comment by ThomasWaldmann** [comment]
this ticket is only about master branch.

on 1.2-maint, the crc32 stuff gets imported from the code we bundle, see `src/borg/algorithms`.

**Comment by ThomasWaldmann** [comment]
You seem to have a build issue on 1.2-maint - if it persists and you need help, please open a new issue for that.

**Comment by ThomasWaldmann** [comment]
- ubuntu jammy: libdeflate used and faster
- debian bullseye: libdeflate used and ???
- darwin: zlib used and ???
- freebsd: libdeflate used and ???
- openbsd: libdeflate used and faster
- netbsd: libdeflate not yet available (soon)
- openindiana: no libdeflate yet

**Comment by ThomasWaldmann** [comment]
maybe that darwin effect was due to older cpu or virtualisation.

overall, it seems to work as expected.
