### ISSUE TITLE
Reduce the chance of "file changed" warnings

### ISSUE THREAD

**Issue by dseomn** [borgbackup/borg#6457]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature request, so I guess closer to issue?

#### Your borg version (borg -V).

Client: `borg 1.2.0`
Server: `borg 1.1.16`

#### Operating system (distribution) and version.

Client: `Debian GNU/Linux bookworm/sid`
Server: `Debian GNU/Linux 11 (bullseye)`

#### Hardware / network configuration, and filesystems used.

Client and server: amd64, mixed SSD and HDD, ssh over wireguard, ext4

#### How much data is handled by borg?

2.3TiB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create --exclude-from /opt/make-backup-borg/files.exclude --exclude-from /opt/make-backup-borg/files.local.exclude ::auto-{fqdn}-{user}-{utcnow:%Y-%m-%dT%H:%M:%SZ} /
```

## Describe the problem you're observing.

I'm getting `file changed while we backed it up` warnings, similar to https://github.com/borgbackup/borg/issues/6379. Unlike in that issue though, I do care about consistency of the files and I'm glad to have the warnings when there's an issue. What I'd like is for borg to try to avoid the issue in the first place, when possible. Some options I can think of, which could potentially be combined:

1. Retry individual files that change during backup, and only issue the warning if the issue persists after a specified number of retries.
2. Read small (for a configurable definition of "small") files into RAM before trying to back them up into the borg repo. The files that I'm having this issue with are all small enough to fit easily into RAM, and stored on SSD so reading into RAM would be fast. However, I only have about 800KiB/s of bandwidth from the borg client to the server. For a roughly constant file size and roughly constant rate of file changes, I think the chances of a file change happening at the same time as reading into RAM would be much lower than the chances of a file change happening during a slow read.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Run `borg create` over a slow link with files that change periodically.

**Comment by ThomasWaldmann** [comment]
I see what you mean, but I don't think we should do that:

- it makes the code more complex
- neither the number of retries nor the "small files" can be chosen in a safe way (== solving the problem for sure) and making it configurable just delegates the unsolvable problem to the user
- so in the end it's all potentially futile attempts and doesn't really solve the problem

So, how about just making a snapshot to get rid of the fundamental inconsistency issue if you don't want borg to warn about inconsistent files?

**Comment by dseomn** [comment]
ext4 is pretty common on desktops, and I don't think it supports snapshots itself. LVM does, but normal LVM snapshots are kinda weird (bad write performance and they require a fixed space allocation, if I remember correctly) and I don't think LVM thin volumes (which support much better snapshots) are at all common in desktops. So I agree that snapshots are the best option in theory, but I don't think they're a practical answer for most linux desktops, yet.

> it makes the code more complex

Agreed. Hopefully neither option is very complex, but I'm not familiar with the code. Any sense of how common the "file changed" issue is in cases when snapshots are impractical?

> chosen in a safe way (== solving the problem for sure)

Why reject an 80/90/95/99% solution just because it can't guarantee that it solves the problem 100% of the time, when the 100% solution (snapshots) is currently impractical for a common use case (desktops)?

Just to throw numbers out, here are some things that I think might be reasonable defaults to solve the problem most (but not all) of the time: 3 retries, 8 times the maximum chunk size (so 64MiB, I think). (I think 10% of free RAM would be a better default, but I don't see an easy way to get that number in python without bringing in additional dependencies.)

**Comment by ThomasWaldmann** [comment]
How "common" it is depends on what you do on your desktop and when you run your backups.

It might also depend on that how good your proposed counter-measures will work.

You can try to do a PR implementing your proposal and try to find a way to prove it really works in usual cases.

**Comment by ThomasWaldmann** [comment]
Can we close this in favour of #7346?

**Comment by dseomn** [comment]
That covers retrying, but not reading files into RAM. Maybe retrying will be enough though? I don't know.

**Comment by ThomasWaldmann** [comment]
Superseded by #7346.

**Comment by ThomasWaldmann** [comment]
@dseomn There is a ~8MB buffer that already reads files into memory.

Of course there can be files bigger than that, but we can not support very large buffers.

Also, even when reading a file as quickly as possible into memory, there would be still a chance of it changing while we read it.
