### ISSUE TITLE
borg info gives wrong info about encryption for "authenticated" mode

### ISSUE THREAD

**Issue by antipiot** [borgbackup/borg#6462]
## Have you checked borgbackup docs, FAQ, and open Github issues?  
Yes  

## Is this a BUG / ISSUE report or a QUESTION?  
BUG

#### Your borg version (borg -V).  
borg 1.1.15

#### Full borg commandline that lead to the problem (leave away excludes and passwords)  
```
borg init --encryption=authenticated /path/to/repository
borg info /path/to/repository
```

## Describe the problem you're observing.
The [documentation here](https://borgbackup.readthedocs.io/en/stable/usage/init.html) state "If you do not want to encrypt the contents of your backups, but still want to detect malicious tampering use --encryption authenticated."

But `borg info` reports that:
```
Encrypted: Yes (authenticated)
```

What is the real status about that? All informations welcome!

EDIT: following [this link](https://github.com/borgbackup/borg/issues/4042) it looks to not be encrypted.

**Comment by ThomasWaldmann** [comment]
`authenticated` is not encrypted. That's a bug in `borg info` due to a bad check for unencrypted (only `plaintext` is considered not encrypted, `authenticated` missing there).

Also, guess we could better use `KEYCLASS.logically_encrypted` which also considers the case that an empty passphrase repokey should be considered as logically not encrypted.

**Comment by bybwang** [comment]
I'd like to work on this issue!

**Comment by ThomasWaldmann** [comment]
@bybwang Thanks! Just open a PR against master branch with your changes.

**Comment by ThomasWaldmann** [comment]
@bybwang do you need help?

**Comment by cmcgee0308** [comment]
Hi there! I'm a novice at Python and I was wondering if this would be a good open source for me to contribute to at my skill level? :)

**Comment by ThomasWaldmann** [comment]
@cmcgee0308 It depends. Some parts are easy, some parts are hard.

Maybe check the issues for tag "easy" or "good first issue".

**Comment by cmcgee0308** [comment]
This issue had those tags so I was hoping it would be right up my alley. 😁

**Comment by bybwang** [comment]
@ThomasWaldmann I'm ok thanks for asking! Sorry I had some stuff come up but I will be taking a look soon

**Comment by ThomasWaldmann** [comment]
i want to release 1.1.18 soon, can we speed up a bit?

**Comment by ThomasWaldmann** [comment]
I'll fix this myself.
