### ISSUE TITLE
borg diff contains path only entry

### ISSUE THREAD

**Issue by herrwusel** [borgbackup/borg#6483]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

1.2.0

#### Operating system (distribution) and version.

Arch linux

#### Hardware / network configuration, and filesystems used.

Backups are copied to an HDD via ssh.

#### How much data is handled by borg?

50G

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I'm using Vorta and discovered something odd: when I `borg diff` some lines are just paths without the change type and size:
```
                    home/jakob/Zotero/pipes/1647851804595
```
According to https://github.com/borgbase/vorta/issues/1228 this is not intended behaviour. Is this correct?

**Comment by ThomasWaldmann** [comment]
We should at least have the borg commandline that leads to this issue.

**Comment by herrwusel** [comment]
```
borg diff --info user@ip:/mnt/backup/b1/::c940-arch-2022-03-19-185905 c940-arch-2022-03-21-172543
``` 
is the command. I don't want to paste the entire output

**Comment by real-yfprojects** [comment]
Is a change in the result of `borg diff` without a change type a valid behaviour of borg? @ThomasWaldmann 
I couldn't find anything about such changes in the docs.

**Comment by ThomasWaldmann** [comment]
`home/jakob/Zotero/pipes/1647851804595` can you give me the `stat` output for that file?

is that a regular file? or a FIFO (fs pipe)?

**Comment by herrwusel** [comment]
It is a FIFO. The files comes from Zotero - a program to manage references. While the program is running there is a file in `pipes`. When closed the directory is empty.
```
$ stat Zotero/pipes/1650188949339
 Datei: Zotero/pipes/1650188949339
 Größe: 0               Blöcke: 0          EA Block: 4096   FIFO
Device: 254,2   Inode: 1611751691  Links: 1
Zugriff: (0600/prw-------)  Uid: ( 1000/   jakob)   Gid: (  998/   wheel)
Zugriff: 2022-04-17 11:49:10.187720668 +0200
Modifiziert: 2022-04-17 11:49:10.187720668 +0200
Geändert: 2022-04-17 11:49:10.187720668 +0200
Geburt: 2022-04-17 11:49:10.187720668 +0200
```

**Comment by ThomasWaldmann** [comment]
OK, so there is no content to diff. We have to check `borg diff` what to do best in such a case.

**Comment by ThomasWaldmann** [comment]
presence change ("added" / "removed") for fifos, blk and chr devs was not yet supported by borg diff.

**Comment by ThomasWaldmann** [comment]
@herrwusel can you test #6615 ?

**Comment by m3nu** [comment]
Thanks for the pointer. We'll extend it. There is some refactoring happening in this feature anyways.

**Comment by m3nu** [comment]
Actually @real-yfprojects was faster and already took care: https://github.com/borgbase/vorta/pull/1265 👏

**Comment by real-yfprojects** [comment]
@ThomasWaldmann Is this an issue with `borg list` as well? Does listing archive contents support the file types FIFO and co?

**Comment by ThomasWaldmann** [comment]
Don't think so, but just try. :-)
