### ISSUE TITLE
freebsd fuse for mount

### ISSUE THREAD

**Issue by jungle-boogie** [borgbackup/borg#649]
Hello,

Trying to mount a backup:
`borg mount pulsebackup::pulse.net-2016-02-06-01-15 gg`
`Loading fuse support failed [ImportError: No module named 'llfuse']`

I manually loaded the kernel module with
`sudo kldload fuse`
and see this is dmesg:
`fuse-freebsd: version 0.4.4, FUSE ABI 7.8`

Fuse was imported into base with this commit from 3 years and 3 months ago:
https://svnweb.freebsd.org/base?view=revision&revision=241519

Any chance of getting `mount` working on freebsd? I tested this on 10.2-release.

**Comment by ThomasWaldmann** [comment]
you need python-llfuse.

**Comment by jungle-boogie** [comment]
> you need python-llfuse.

And that's installed with pip? 

```
% pip3 -V
pip 8.0.2 from /usr/local/lib/python3.4/site-packages (python 3.4)
```

```
% sudo pip3 install llfuse
Collecting llfuse
  Downloading llfuse-0.42.1.tar.bz2 (320kB)
    100% |████████████████████████████████| 323kB 952kB/s
No files/directories in /tmp/pip-build-8wuzxna5/llfuse/pip-egg-info (from PKG-INFO)
```

And yet, I don't see llfuse:

```
% pip3 list
borgbackup (1.0.0rc1)
decorator (4.0.4)
ipython (4.0.0)
ipython-genutils (0.1.0)
msgpack-python (0.4.7)
ngrid (0.1.0)
numpy (1.10.1)
pandas (0.17.0)
pandashells (0.1.5)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (8.0.2)
ptyprocess (0.5)
python-dateutil (2.4.2)
pytz (2015.7)
setuptools (18.5)
simplegeneric (0.8.1)
six (1.10.0)
termsql (0.3)
traitlets (4.0.0)
virtualenv (13.1.2)
wheel (0.26.0)
````

**Comment by ThomasWaldmann** [comment]
0.42.1 does not work due to incompatible changes in llfuse, see my updated first comment.

**Comment by ThomasWaldmann** [comment]
There is also the possibility now to do "pip install borgbackup[fuse]" that will automatically install the correct llfuse version. I updated the docs already about that.

**Comment by jungle-boogie** [comment]
Hello,
I do see the docs were updated:
http://borgbackup.readthedocs.org/en/latest/installation.html#using-pip

```
% sudo pip3 install --upgrade 'borgbackup[fuse]==1.0.0rc1'
Requirement already up-to-date: borgbackup[fuse]==1.0.0rc1 in /usr/local/lib/python3.4/site-packages
  borgbackup 1.0.0rc1 does not provide the extra 'fuse'
Requirement already up-to-date: msgpack-python>=0.4.6 in /usr/local/lib/python3.4/site-packages (from borgbackup[fuse]==1.0.0rc1)
```

Are you planning on updating borg 1.0.0rc01 with fuse?

**Comment by jungle-boogie** [comment]
I needed to install `fusefs-libs` from freeBSD package, then install llfuse<0.42 with pip.

Finally, loading the kernel module is still necessary:
`sudo kldload fuse`

**Comment by ThomasWaldmann** [comment]
That stuff is even to be seen in our Vagrantfile. Maybe not much yet for freebsd in the main docs, though.

**Comment by jungle-boogie** [comment]
Hi @ThomasWaldmann,

I can look into updating the docs as this is specific to freeBSD. 

re-opening to work on docs.

**Comment by ThomasWaldmann** [comment]
Are you still working on that / your PR?

**Comment by skorokithakis** [comment]
This is still happening for me:

~~~
14:04:33 $ pip install -U borgbackup[fuse]
Requirement already up-to-date: borgbackup[fuse] in /home/stavros/.virtualenvs/generic3/lib/python3.4/site-packages
Requirement already up-to-date: msgpack-python>=0.4.6 in /home/stavros/.virtualenvs/generic3/lib/python3.4/site-packages (from borgbackup[fuse])
Collecting llfuse<2.0 (from borgbackup[fuse])
  Using cached llfuse-1.1.tar.bz2
No files/directories in /tmp/pip-build-v2sj8sz3/llfuse/pip-egg-info (from PKG-INFO)
~~~

**Comment by ThomasWaldmann** [comment]
@skorokithakis the procedure as shown in the Vagrantfile is used by me on every borgbackup release and the fuse stuff works for me in the FreeBSD VM:

https://github.com/borgbackup/borg/blob/master/Vagrantfile#L73
https://github.com/borgbackup/borg/blob/master/Vagrantfile#L193

Is maybe your /tmp too small or otherwise special?
Also, maybe kill that cached llfuse-1.1.tar.bz2 file, so pip fetches a fresh copy.

**Comment by ThomasWaldmann** [comment]
If that doesn't help, please open a new ticket.

**Comment by skorokithakis** [comment]
On Ubuntu, I needed to install `libfuse-dev` to get `llfuse` to install. It works now.

**Comment by ThomasWaldmann** [comment]
That's even documented:
http://borgbackup.readthedocs.io/en/stable/installation.html#debian-ubuntu

**Comment by skorokithakis** [comment]
Ah, bleh, I missed that last line, thank you.
