### ISSUE TITLE
remove legacy crypto modes for new repos

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6490]
#6463 added shiny nice AEAD crypto modes and also the usage of session keys, which solves the potential issues with the legacy AES-CTR based crypto (mainly about nonce management to avoid nonce reuse).

To get rid of the old stuff quickly, I think we should remove the legacy crypto modes for new repos with 2.0 and remove the legacy code completely in N+1 release.

**Comment by ThomasWaldmann** [comment]
Maybe we could also deprecate the `pbkdf2` based borg keys (they use encrypt-and-MAC and the `AES` class is only used by them).

**Comment by Charles-Auer** [comment]
Based on the docs, this looks like it would affect both regular keys and blake2b keys. Is that correct?

**Comment by ThomasWaldmann** [comment]
yes, it affects all pre-1.3 modes, they are all based on AES-CTR mode and need the related counter management, which can be problematic in some situations.

**Comment by ThomasWaldmann** [comment]
fixed in borg2 branch.
