### ISSUE TITLE
borg create: add formatting options to archive name

### ISSUE THREAD

**Issue by manwegit** [borgbackup/borg#650]
I've noticed that quite many new users (me included) don't notice uniqueness requirement for archive name before running the backup second time. 

Examples show using `date +%Y%m%d` etc to add uniqueness to archive name. I'm personally fine with this as is most likely majority of experienced linux users. For home users this might be an issue.

I propose that borg could use pythons uuid package or some other method to add postfix to archive name. ( --add-automatic-postfix here in this example.. yeah.. I'm bad with coming up with param names)

`borg create --add-automatic-postfix /mnt/backup::my-documents ~/Documents`

Would be similar if you'd write this with current create:
`borg create /mnt/backup::my-documents_$(uuid | cut -f 1 -d-)  ~/Documents`

This would also make usage examples for new users more friendly.

Or if we are ok with possible collision although relatively small window, then $(date +%s) = unix timestamp, could be used without adding python uuid library tote the mix.   

`borg create /mnt/backup::my-documents_$(date +%s)  ~/Documents`

I'm willing to write a patch for this if needed.

**Comment by RonnyPfannschmidt** [comment]
i would like to propose the ability to use a python format string template having availiable the variables `now`, `pid`,  `user` and `uid`

so an archive name could be `::documents-{now:%y-%m%d}-{user}`

**Comment by manwegit** [comment]
My take on this is that it would be non-configurable and meant for basic home backup. 
Anything more complex can be and should be handled by the user like:
`documents-$(date +"%Y-%m%d-${USER}-$$")`
`$$` = current PID

**Comment by manwegit** [comment]
Just tried it, four new lines to archiver.py do_create (add timestamp if param active) and 3 for the 
option: --generate-archive-postfix
    Add options --generate-archive-postfix for easier backups of the same location.
    Use: with --generate-archive-postfix it's possible to repeat same backup cmd
    without sorting to shell veriables like:
    borg create --generate-archive-postfix /backup/repo::MyDocuments ~/MyDocuments
    this will generate archive names like:
     /backup/repo::MyDocuments_1454926244
     /backup/repo::MyDocuments_1454926325

[@see diff on my borg feature branch](https://github.com/borgbackup/borg/compare/master...manwegit:feature/create-autotimestamp)

Comment, should a pull request be made with this (and if any of you have better name for option please contribute)

**Comment by ThomasWaldmann** [comment]
I am not convinced this is helpful.

The problem you describe is that a user is unaware that archive names must be unique. That might be the case until he tries his 2nd backup, but then he'll learn it, even if he does not read the docs.

Adding another option (that must be learned about first also) does not help such users.

Aside from that fundamental problem:

- I don't think we should just add random numbers to the archive names.
- Ronny's suggestion is a bit more flexible and avoids that we have to add another option. OTOH, repo/archive names are already rather complex and get even more complex by this.

**Comment by ThomasWaldmann** [comment]
if we would go ronny's way, `{hostname}` (short) and `fqdn` (long) would also be useful placeholders.

**Comment by manwegit** [comment]
AAa.. Now I get Ronnys comment, I misread it. Yeah adding formatting to archivename would be preferable and after --list-format pull merge, we already have a helper function for that could be used/extended with filter option. (e.g. make archive name filter obey filename restrictions)

**Comment by manwegit** [comment]
Made formatting like @RonnyPfannschmidt asked and added fqdn + hostname (like @ThomasWaldmann commented).

[see diff on my borg feature branch](https://github.com/borgbackup/borg/compare/master...manwegit:feature/format_archive)

Any interest for this feature? Pull request?

**Comment by ThomasWaldmann** [comment]
Yes, PR that one after we have your first one merged.

**Comment by ThomasWaldmann** [comment]
first one is merged.

**Comment by ThomasWaldmann** [comment]
merged https://github.com/borgbackup/borg/pull/692
