### ISSUE TITLE
QUESTION - Split backup using regexp pattern

### ISSUE THREAD

**Issue by sarwanjassi** [borgbackup/borg#6502]
Hello,

Is there any way to Split backup using regexp pattern. Lets say i have username from A to Z and i need to take backup of users staring with A to F , G-P and Q-Z in 3 different repository.

So i will need to copy data directories with names

Please advise

**Comment by ThomasWaldmann** [comment]
Well, guess you could use the shell to help you, like:
```
borg create repo1::archive /home/[a-f]*
```

**Comment by ThomasWaldmann** [comment]
Guess this is solved.

**Comment by sarwanjassi** [comment]
Kindly remove my email

**Comment by ThomasWaldmann** [comment]
Kindly just read the email you got from github, it contains instructions for you how to do that.
