### ISSUE TITLE
`borg compact` command does not exist

### ISSUE THREAD

**Issue by mhillebrand** [borgbackup/borg#6505]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes, and I'm astonished by my inability to find anything.

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.1.15

#### Operating system (distribution) and version.

Linux Mint 20.3 Una

#### Hardware / network configuration, and filesystems used.

Client: Linux RAID-0 ext4
Borg Repo: Synology RAID-1 NAS (Samba share, mounted automatically on boot)

#### How much data is handled by borg?

Less than 1TB

## Describe the problem you're observing.

In the documentation for the `borg prune` command, it says:

> Important: Repository disk space is not freed until you run `borg compact`.

However, the `borg compact` command doesn't exist for me. Is it only for the borg server setup? More importantly, should I do something other than just `borg prune` from the client side if I want to free up deleted/pruned space on disk?

#### Include any warning/errors/backtraces from the system logs

`$ borg compact`
```
usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug] [--debug-topic TOPIC] [-p]
            [--log-json] [--lock-wait SECONDS] [--bypass-lock] [--show-version] [--show-rc] [--umask M]
            [--remote-path PATH] [--remote-ratelimit RATE] [--consider-part-files]
            [--debug-profile FILE] [--rsh RSH]
            <command> ...
borg: error: argument <command>: invalid choice: 'compact' (choose from 'mount', 'serve', 'init', 'check', 'key', 'change-passphrase', 'create', 'extract', 'export-tar', 'diff', 'rename', 'delete', 'list', 'umount', 'info', 'break-lock', 'prune', 'upgrade', 'recreate', 'with-lock', 'config', 'help', 'debug', 'benchmark')
```

**Comment by mhillebrand** [comment]
Oh, never mind. I found this:

https://borgbackup.readthedocs.io/en/1.1.5/usage/prune.html

**Comment by ThomasWaldmann** [comment]
You are reading docs for the wrong versions (first 1.2.0, now 1.1.5).

Guess you wanted https://borgbackup.readthedocs.io/en/1.1.15/usage/prune.html .

There's a version selector at the lower right of these docs.

**Comment by mhillebrand** [comment]
Yeah, that's why I closed the issue with this comment. 😉

> Oh, never mind. I found this:
> 
> https://borgbackup.readthedocs.io/en/1.1.5/usage/prune.html

I thought that upgrading Linux Mint to the latest version would let me install v1.2.0 via `apt`. Boy, was I wrong. I successfully installed it using `pip`, and everything is fine now. Really impressed with Borg, by the way!!
