### ISSUE TITLE
start/end times in UTC

### ISSUE THREAD

**Issue by jungle-boogie** [borgbackup/borg#651]
Hello,

I'm now using `borg 1.0.0rc1`

My timezone is America/Los_Angeles:
```
% date
Mon Feb  8 08:45:54 PST 2016
```

When a backup is generated, the start and end times are in UTC:
```
Start time: Mon Feb  8 16:46:44 2016
End time: Mon Feb  8 16:46:45 2016
Duration: 1.25 seconds
Number of files: 168
```

However I save the file with my time and date: 2016-02-08-08-46

I believe this is a new behavior for Borg but is it intended? My cron jobs will now report 7 - 8 hours ahead of when they started/ended. I can use the time I received the mail to know when it completed.

**Comment by ThomasWaldmann** [comment]
Please give the commandline you used.
