### ISSUE TITLE
borg prune wipe quite everything from my backups.

### ISSUE THREAD

**Issue by dominix** [borgbackup/borg#6513]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

a bug issue

#### Your borg version (borg -V).

1.2.0

#### Operating system (distribution) and version.

Synology DSM 7.
uname : Linux  4.4.59+ #25556 SMP Sat Aug 28 02:14:27 CST 2021 x86_64 GNU/Linux synology_v1000_rs1221rp+

#### Hardware / network configuration, and filesystems used.

synology / I Gb ethernet / Btrfs (24 To)

#### How much data is handled by borg?

less than 1To (approx 300 G a this time)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg prune --keep-daily 6 --keep-weekly 4 --keep-monthly 2 --stats

## Describe the problem you're observing.

I have a dozen of sub-directories (or folder).
I backup them as  borg create ::${DIRECTORY}_$DATE  /volume1/${DIRECTORY}
DATE is export DATE=$(date +%Y%m%d)
if I borg list --short I can see everythings may be twice or more (after few days)
if I prune => borg prune --keep-daily 6 --keep-weekly 4 --keep-monthly 2 --stats
quite every get wiped out
Deleted data:             -651.67 GB           -588.21 GB           -241.63 GB
All archives:                    3.51 GB              3.26 GB              2.78 GB

however there should be no data to wipe (too soon)

NB: there is  a link in openvpn between the source and the target. link is approx 100Mbit /s, used very efficently. (10 ~ 11 MB/s when backing up)

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

every time I do "borg prune --keep-daily 6 --keep-weekly 4 --keep-monthly 2 --stats" it wipes (quite) everything
only one folder persist (one of the smaller)

#### Include any warning/errors/backtraces from the system log

I can see no relevant logs

**Comment by ThomasWaldmann** [comment]
if you read the docs, you'll find `--prefix` (solves your issue, which is not a bug) and `--dry-run` (avoid accidental damage by bad parameters).
 
With borg 1.2.0 there is `-v` or `--list` telling you the **rule** that keeps archives.

**Comment by dominix** [comment]
ok "borg prune --keep-within ${BORG_KEEP_DAILY}d   --keep-daily $BORG_KEEP_DAILY "  fix my situation

but it sound weird that a just released backup will be pruned with a --keep-daily 7. my backup script was working fine with 1.1.15.

**Comment by ThomasWaldmann** [comment]
If you still think there is a bug and you did not just forget to use `--prefix` correctly, please provide a script that reproduces your issue and shows different behaviour on 1.1.x and 1.2.0.

**Comment by kosli** [comment]
@dominix  How have you installed borg on the Synology NAS, as I have problems to get the 1.2.x release running on the Synology NAS. See #7091

**Comment by kosli** [comment]
Thanks @dominix Hmm, it looks like the package from SynoCommunity installs python too:
https://github.com/SynoCommunity/spksrc/blob/0f1353c96030bf21e830166a082d3925b5377051/spk/borgbackup/Makefile#L9
So that explains why it "works" :-)
(Where I got now 1.2.2 running by using the "linuxold64" release at https://github.com/borgbackup/borg/releases/download/1.2.2/borg-linuxold64)
