### ISSUE TITLE
multi-core blockchain and AI support

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6517]
borg finally needs to unleash the revolutionary power of the block chain, providing a new back-end architecture to store your data in there.

Also, we should use AI (artifical intelligence!) to recognise what the user really wanted and automatically determine how to chunk, compress and encrypt stuff in a military grade way. Of course, one core is not enough for this, so you will need an Apple M1 Ultra or an AMD Threadripper for that.

Some unused cores could be used for crypto mining while you back up (coins conveniently and automatically being transmitted to us), so that would automatically pay for your future software / AI upgrades.

**Comment by RonnyPfannschmidt** [comment]
finally the backup tools do their part in financing the backup storage

AI powered DWIM is going to b e a great help to in finally getting the people to run that `yes|rm -rif /` in a more streamlined manner
