### ISSUE TITLE
Simple que

### ISSUE THREAD

**Issue by leothewolf** [borgbackup/borg#6525]
Hey I just wish to know if the data I store on repo as in an image is it accessible so that it can be used to serve images on my site? Or is it just for storage purpose?

**Comment by ThomasWaldmann** [comment]
Can you please rephrase your question, I do not understand what you want to know precisely.

**Comment by leothewolf** [comment]
I mean if I store the data on borg site in the repo is it accessible as the github content is? As in if I store image here it can be accessed using rawgithubuser content link of it

**Comment by ThomasWaldmann** [comment]
No, you can only access stuff in a borg repo via borg (the closes to direct access is `borg mount`, which makes the repo content accessible as a FUSE filesystem).
