### ISSUE TITLE
RecursionError after updating to 1.2.0

### ISSUE THREAD

**Issue by noctuid** [borgbackup/borg#6542]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes. Possibly related to #380, but I have not seen this issue before now.

## Is this a BUG / ISSUE report or a QUESTION?

Looks like a new bug. Maybe a question (if the problem is something on my end).

#### Your borg version (borg -V).

borg 1.2.0

#### Operating system (distribution) and version.

Arch

#### Hardware / network configuration, and filesystems used.

ext4 source, backing up to exfat on a usb

#### How much data is handled by borg?

<2GB in this case

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Run in my home directory:
sys.argv: ['/usr/bin/borg', 'create', '--debug', '--stats', '--progress', '--patterns-from=.zsh/borg_minimal.txt', '/media/Samsung USB/minimal_backup::{hostname}-{user}-{now:%Y-%m-%dT%H:%M:%S}', './']

[Here](https://github.com/noctuid/dotfiles/blob/master/terminal/.zsh/borg_minimal.txt) is the pattern file if needed.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

After updating to 1.2, my backups to existing repos fail with the RecursionError shown below. I have two usb drives I backup to and also use borgbase and get the same error in all cases every time.

I am not 100% sure this is related to updating to 1.2, but I only started seeing this issue after I updated the other day (previously had not updated borg in probably >4 months). I don't think I have any deeply nested directories where this should be an issues. Is there any way for me to see *where* this is happening so I can check to make sure there isn't some issue with my directory structure?

Also, I've always (prior to 1.2 also) gotten a bunch of `dir_open` errors like `.cache/paru/clone/klfc/pkg: dir_open: [Errno 13] Permission denied: 'pkg'` even though I am not backing up `.cache`. Does this have to do with my pattern file? This may be completely unrelated, but is it possible borg is recursing into some deeply nested directory structure that is not in one of the directories I am backing up?

#### Include any warning/errors/backtraces from the system logs

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 668, in do_create
    create_inner(archive, cache, fso)
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 605, in create_inner
    self._rec_walk(path=path, parent_fd=parent_fd, name=name,
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 813, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 813, in _rec_walk
    self._rec_walk(
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 813, in _rec_walk
    self._rec_walk(
  [Previous line repeated 985 more times]
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 782, in _rec_walk
    with OsOpen(path=path, parent_fd=parent_fd, name=name, flags=flags_dir,
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/site-packages/borg/archive.py", line 264, in OsOpen
    fd = os_open(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=noatime)
  File "/usr/lib/python3.10/site-packages/borg/helpers/fs.py", line 287, in os_open
    _flags_noatime = _flags_normal | O_('NOATIME')
  File "/usr/lib/python3.10/site-packages/borg/helpers/fs.py", line 250, in O_
    result |= getattr(os, 'O_' + flag, 0)
RecursionError: maximum recursion depth exceeded while calling a Python object

Platform: Linux bahamut 5.17.1-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 28 Mar 2022 21:56:46 +0000 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.10.4 msgpack: 1.0.3 fuse: llfuse 1.4.1 [pyfuse3,llfuse]
PID: 926490  CWD: /home/noctuid
sys.argv: ['/usr/bin/borg', 'create', '--debug', '--stats', '--progress', '--patterns-from=.zsh/borg_minimal.txt', '/media/Samsung USB/minimal_backup::{hostname}-{user}-{now:%Y-%m-%dT%H:%M:%S}', './']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
```
  File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 813, in _rec_walk
    self._rec_walk(
  [Previous line repeated 985 more times]
```
See the last line: recursion was close to 1000 deep when it gave up.

That's either a really deep directory or maybe a defect filesystem that has an endless cycle somewhere.

**Comment by ThomasWaldmann** [comment]
You could add this before line 813:
```
print(normpath)
```
And then run it again to see what it prints before it dies.

**Comment by noctuid** [comment]
> That's either a really deep directory or maybe a defect filesystem that has an endless cycle somewhere.

There was a directory that seems to have an endless cycle. Nothing should show up as `/home..` because I was using `./` as the root path, but the printed paths started looking something like this:
```
move/foo/a

/home
move/foo/a
/home/noctuid
move/foo/a
/home/noctuid/move/foo
move/foo/a

/home/noctuid/move/foo/b

move/foo/a
/home/noctuid/move/foo/b
/home
move/foo/a
/home/noctuid/move/foo/b
/home/noctuid
move/foo/a
...

```

I saw basically a duplicate directory with an endless nested structure in the file manager. Deleting it fixed the issue

Is this a filesystem corruption issue, or how does this happen?.

**Comment by ThomasWaldmann** [comment]
I have troubles to interpret that output. But what you describe sounds like a fs corruption.
