### ISSUE TITLE
initialise a borg repo reusing existing key material

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6554]
with the new AEAD session key based modes, we do not have counter management issues / nonce reuse issues any more.

at the start of a backup (or other) session, the session key is derived from a random sessionid and the master key material (from borg key). no problem if 2 or more repos use the same master key material in parallel.

one reason to actually use that is replication of archives/chunks from one repo into another (or in general, if one might want to copy or move an archive from one to the other) - that can be done very efficiently, keeping the encrypted chunks "as is", if both repos share the same master key material (including the id key and chunker secret).

so, what we need now is something like:
```
borg init --key-from existing_repo new_repo
```

Keep the same passphrase. If desired, it can be changed afterwards via `borg key change-passphrase`.

Bounty: https://app.bountysource.com/issues/106877923-initialise-a-borg-repo-reusing-existing-key-material (a bit less than usual, but no more funds available)

**Comment by ThomasWaldmann** [comment]
another "reuse key material" use case (from #6608) is copying existing chunks (and also wanting to cut the same chunks for future backups to not destroy deduplication).

For that, we need to keep the chunker secret and the id mac secret (and also the chunker algorithm, the chunker params and the id mac algorithm).

**Comment by elho** [comment]
> Does it make sense to have a different passphrase? In the end, it is protecting the same key material.

Users may want that, but those can use `borg key change-passphrase` on the new repo right after having initialised it, thus I see no need to provide yet another way of doing that.


> For that, we need to keep the chunker secret and the id mac secret (and also the chunker algorithm, the chunker params and the id mac algorithm).

Another use case for that would be benchmarking, ie. one is able to create multiple repos with e.g. different compression algorithms and settings and not hav ethe results influenced by differently cut chunks.
