### ISSUE TITLE
Archive is created even when path is wrong

### ISSUE THREAD

**Issue by DoTheEvo** [borgbackup/borg#656]
Hi

I passed non existing path to `borg create` and got error, when I noticed the path is wrong and fixed it I could not create the archive of the name I had in mind, since it already existed from the failed attempt.

Is this intentional behavior?

Also `borg delete` in the [documentation](http://borgbackup.readthedocs.org/en/stable/usage.html#borg-delete) lacks examples.

**Comment by ThomasWaldmann** [comment]
Well, this is a edge case of `borg create repo::archive path1 path2 ... pathn`.

If one of these pathes does not exist, borg continues (and backups all correct n-1 pathes) and just emits a warning, that one path did not result in any matches.

If course, if n == 1 and that one path is not correct, that results is that warning and an empty archive.

So, while it might feel a bit strange, it is the same mechanism, working correctly.

**Comment by ThomasWaldmann** [comment]
Keeping this open as a reminder to add 2 examples for `borg delete`: archive and repo deletion.
