### ISSUE TITLE
[1.1] and [1.2] Key algorithm forward compatibility

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6561]
borg 1.3 Introduces a change to the format of our keys (#747). 1.3 will happily work with either format and even allow the user to switch back and forth between the two, but 1.1 and 1.2 will produce an unhelpful error when they encounter the new format:
```
borg info /path/to/repo/
/path/to/repo is not a valid repository. Check repo config.
```

We should make a new release in the 1.1 and 1.2 branches that would implement a more helpful error

**Comment by ThomasWaldmann** [comment]
1.1-maint about a 1.3 repo:
```
/Users/tw/w/borg/repo13 does not have a valid configuration. Check repo config [repository version 2 is not supported by this borg version].
```

**Comment by ThomasWaldmann** [comment]
fixed.
