### ISSUE TITLE
[doc] [1.1] [1.2] backport "Add a troubleshooting note to the FAQ"

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6562]
borg 1.3 Introduces a change to the format of our keys (https://github.com/borgbackup/borg/issues/747). 1.3 will happily work with either format and even allow the user to switch back and forth between the two, but 1.1 and 1.2 will produce an unhelpful error when they encounter the new format:
```
borg info /path/to/repo/
/path/to/repo is not a valid repository. Check repo config.
```
#6561 will cover future releases of 1.1 and 1.2, but we can not go back in time and implement better forward compatibility into the copies of borg that are installed today. We should backport 749c156ecdb4708014db371bda33e170a097e6b2

**Comment by ThomasWaldmann** [comment]
The problem with that is that docs releases are bound to the code releases and their git tags, we can't change the docs for a releases after that release.

But users are often not careful and read the wrong docs anyway: they read the latest stable docs (will be 1.2.1 docs soon), so if we fix it there, users will read it (even if they wanted to read the docs for their older borg version).

We can also still fix the 1.1-maint docs so it will go into 1.1.18 docs (but noone will read these by accident as it is oldstable now).

**Comment by ThomasWaldmann** [comment]
@hexagonrecursion maybe for #6398 ?

**Comment by ThomasWaldmann** [comment]
done.
