### ISSUE TITLE
invalid repository

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6566]
if an old borg detects a repo version > 1 it just says "invalid repository".

it could be a bit more helpful and e.g. tell "you need a new borg release to support repo version X".

**Comment by ThomasWaldmann** [comment]
fix this in 1.1-maint and also 1.2-maint.

**Comment by ThomasWaldmann** [comment]
@hexagonrecursion yet another such place. ^^^

**Comment by ThomasWaldmann** [comment]
Maybe could rather use `InvalidRepositoryConfig` exception.

**Comment by hexagonrecursion** [comment]
For people (like me) wishing to know what "repo version > 1" means: https://github.com/borgbackup/borg/issues/1704
