### ISSUE TITLE
repo: to upgrade or not to upgrade...

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6569]
borg helium milestone (current master branch) will be reached quicker than expected and there will be some major changes:

- new kdf (argon2) to improve key security - key upgrade for existing keys is available (but the AES encryption key will stay the same, of course, for existing repos)
- new crypto (AEAD, session keys, faster, safer and easier, no counter management issues any more) - as it is now, this will only be available for new repos.
- new repository v2 format (safer and faster, see also #6512) - as it is now, borg master branch does not work with v1 repos and creates v2 repos. 

the new crypto and the new repo format have some major advantages (and the old code / old repos have some major disadvantages), so it would be good to get everything to the new stuff and also get rid of the old stuff ASAP.

the question is how we get there, considering:
- users having big repos and possibly tight free space
- borg developer resources being limited

**Comment by ThomasWaldmann** [comment]
Options:

- do a breaking change (borg 2.0 would not read or upgrade old repos):

  - least development effort (no need to write a complicated upgrader)
  - we could use developer time to maybe do some more breaking changes while we are at it (e.g. a repo index with csize, leading to additional speed improvements and cleanups)
  - users could use export-tar/import-tar with borg-pax to copy archives into new repos (would need a borg-pax backport to 1.2.x, but that effort is not much)

- stay compatible

  - keep quite some legacy code for now, so borg is able to at least read old repos.
  - more complex code, when would we get rid of the legacy code?
  - there is no in-place crypto-upgrader yet
  - there is no in-place repo v1 -> v2 upgrader yet
  - any in-place upgrader has a management issue, because upgrades can be interrupted, leaving a half-converted repo behind. tracking what's converted and what not can use a lot of RAM.

**Comment by FabioPedretti** [comment]
I'd vote for the "breaking change" approach.
If one still need to manage an old repo he can easily keep using 1.1/1.2.

**Comment by bill-myers** [comment]
Any solution that requires twice the disk space because the repository data file format changes and restartable in-place migration is not support is obviously completely unacceptable (since there may not be enough disk space to do the migration).

So if you want a new repository format you need to either support having data files in the current format forever, or provide proper upgrade code that can convert file by file and can handle repositories in a partially upgraded states.

**Comment by ThomasWaldmann** [comment]
@bill-myers see #6663 for the current approach.

That supports migration, but you'll need a new repo for it (and the space for the new repo).

Everybody not having the space (yet) can also just continue using the old borg version until the space situation at the current repo location improves or until stuff is moved to another location.

An in-place migration likely won't happen due to the complexity of the changes.

**Comment by BillKen** [comment]
Can anything be done to easily make borg1.x and borg2 coexist? (namespacing?)  I realise skilled admins will probably be able to install both in different paths but having builtin support will make distro packaging for users who need both during transition easier.
BillK

**Comment by ThomasWaldmann** [comment]
@BillKen this is being discussed in #6602.

**Comment by ThomasWaldmann** [comment]
guess we can close this one and continue there.
