### ISSUE TITLE
Failing to open file with noatime

### ISSUE THREAD

**Issue by chebee7i** [borgbackup/borg#657]
I have a mount point with `noatime` set. In this situation, the logic in `Archive._open_rb` is roughly:

1. Attempt to open the with noatime flags. 
2. If step 1 fails, try with normal flags and on success, assume step 1 failed because noatime was tried on a file we didn't have ownership on.  

The result is that files will be opened noatime only if we are the owner and are opened normal otherwise.

In my situation, the file fails to open with noatime even though I am the owner.  It seems like the code should check this scenario in the except clause. That is, rather than assume that opening noatime will work when I am the file owner, it should check that this is true. If not, then it should open normally.

I'm not sure why the file can't be opened noatime, even though I am the owner.  FWIW, the mount point is a Mac OS Extended filesystem that is made available to Linux using Parallels.

**Comment by chebee7i** [comment]
The following got me going:

```
diff --git a/borg/archive.py b/borg/archive.py
index 99c9206..4b0cbd7 100644
--- a/borg/archive.py
+++ b/borg/archive.py
@@ -596,7 +596,12 @@ Number of files: {0.stats.nfiles}'''.format(
                 euid = os.geteuid()
                 # So in future, let's check whether the file is owned by us
                 # before attempting to use O_NOATIME.
-                Archive._open_rb = open_noatime_if_owner
+                if euid == 0 or s.st_uid == euid:
+                    # Then failure was not an ownership issue.
+                    Archive._open_rb = open_simple
+                else:
+                    # Assume failure was an ownership issue.
+                    Archive._open_rb = open_noatime_if_owner
             return fd
```

**Comment by ThomasWaldmann** [comment]
Interesting. One remaining problem might be that this seems to behave differently depending on the filesystem that is currently processed, so this one-time decision might not be correct for the rest of the run, when borg create recurses into different filesystems with different behaviour.

**Comment by chebee7i** [comment]
Right. Is the noatime check strictly for optimization? Perhaps it would be better not to guess and have the user explicitly request that files be opened with noatime. Otherwise, it seems like you might have to do this check on each file...which is probably slower than just opening in normal mode for every file?

**Comment by ThomasWaldmann** [comment]
It tries to use the not-atime-touching open() to not modify the file metadata for files it backs up in any way. In some cases (fs not mounted with noatime option), it is also better for performance.

Yes, i think for now doing the check for each file would be simplest. If it really slows down, it could be later optimized to only check when entering a new filesystem.

**Comment by ThomasWaldmann** [comment]
"In my situation, the file fails to open with noatime even though I am the owner."

Can you give the traceback for the original failure please?

**Comment by ThomasWaldmann** [comment]
currently trying this:
```
    def _open_rb(path):
        try:
            # if we have O_NOATIME, this likely will succeed if we are root or owner of file:
            return os.open(path, flags_noatime)
        except PermissionError:
            if flags_noatime == flags_normal:
                # we do not have O_NOATIME, no need to try again:
                raise
            # Was this EPERM due to the O_NOATIME flag? Try again without it:
            return os.open(path, flags_normal)
```

**Comment by ThomasWaldmann** [comment]
See my PR - if you could try the code (before or after I merge it), that would be great.

**Comment by ThomasWaldmann** [comment]
I merged the PR into github master branch code now, so it can be tested from there (or later from 1.0.0 rc2 or release).

**Comment by chebee7i** [comment]
Confirmed that #657 fixes this issue.

**Comment by ThomasWaldmann** [comment]
Great, thanks for testing! :)
