### ISSUE TITLE
make compression a little more flexible

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#66]
borg currently has hardcoded zlib level 6 compression (same as attic).

this is a throughput bottleneck if your I/O is rather fast (and you do not use encryption or your encryption is also fast, e.g. due to AES-NI or fast cpu).

i already made compression very flexible (offerings different and better algorithms, different compression levels, very high speed for some), but it requires bigger code and format changes and thus lives in experimental branch currently.

but there could be a rather simple change for 0.x.x releases, that doesn't change any storage format:
just making it possible to adjust the zlib compression level (but ALWAYS use zlib, even for 0 compression).
one could even read these repos with older borg versions as uncompress works on any zlib compressed data, not matter what the compression level was.

```
compression of a 100MB text file
================================

algo  time ratio compress/uncompressed
--------------------------------------
zlib0  0.64 1.000
zlib1  2.18 0.505
zlib2  2.41 0.498
zlib3  3.02 0.491
zlib4  3.52 0.470
zlib5  4.79 0.457
zlib6  6.81 0.456 (borg / attic hardcoded default)
zlib7  8.23 0.456
zlib8 23.49 0.456
zlib9 30.91 0.456
```

I think especially level 0 and 1 would be interesting if one wants more speed (and either does not care for backup size [-> level 0] or can also live with slightly less compression than level 6 [-> level 1]).

I'ld just add a compression level argument to borg create, so one can adjust the compression level on a per-backup basis.

**Comment by ThomasWaldmann** [comment]
we could also consider to switch the default to zlib1 or zlib0.

for my experimental branch changes, i even used "no compression" as default, so the user has to think about and say what he wants, IF he wants compression. there are a lot of compression options there and only 1 "no compression" option, so that makes it a natural default somehow.

for stable branch, zlib0 would be the closest thing we can get to "no compression" without bigger changes, but it still adds zlib protocol overhead, so it even outputs a little more data than it gets as input.

**Comment by anarcat** [comment]
what's the "zero time" here? no compression with zlib is `0.64`, but what about just piping the bytes around?

**Comment by ThomasWaldmann** [comment]
it's the time to pipe the data through zlib.compress(data, level=0). the output will be zlib format and we need that because at uncompress time, we'll just do zlib.uncompress(cdata). only if we do it that way, no other changes will be needed.

**Comment by anarcat** [comment]
yes, i understand the idea and applaud it. :) what i'm curious about is the overhead of `zlib.compress(data, level=0)` versus just passing a buffer around.

**Comment by ThomasWaldmann** [comment]
@anarcat:

the overhead in time is 0.64s per 100MB input data.
the overhead in space is below 0.1% otherwise it would have shown up in the table above.

**Comment by anarcat** [comment]
i see, okay.. it was just unclear to me what the numbers were - i see they are relative to "not calling zlib at all"...

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/67

**Comment by ThomasWaldmann** [comment]
implemented by https://github.com/borgbackup/borg/commit/6964799d13e28077fec6e9310e2c43f596af125d
