### ISSUE TITLE
quota output is strange

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6603]
borg 1.1.x

quota output (only done when quotas are enforced) is done when saving an archive - which does not only happen at the very end of a backup, but also when doing checkpoints (so, every 30mins by default).

especially when using it in combination with `--progress`, the quota output disturbs the progress output:

**Comment by jernejs** [comment]
I'll upload the image here, because I use that URL for any image that I only need temporarily:
![Image1](https://user-images.githubusercontent.com/1800143/163665959-95f1a4d8-8e8b-485b-b398-0c7fbd02bb35.png)

**Comment by ThomasWaldmann** [comment]
hmm, guess this is hard to fix with the current repository code.

the quota output is logged at info level when a transaction is started and when it is committed.

the problem is that due to checkpointing this happens again and again when the backup time is (much) longer than the checkpoint interval.

guess we could fix this if the quota logging was explicitly triggered by the client (not the server-side repository code), so maybe we can fix it together with #2870.

**Comment by ThomasWaldmann** [comment]
the quota log output will be removed as part of #7121 .
