### ISSUE TITLE
PPA install gives 404 error on Ubuntu 21.10

### ISSUE THREAD

**Issue by femto-code** [borgbackup/borg#6605]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Operating system (distribution) and version.
Kubuntu 21.10 impish

## Describe the problem you're observing.

When adding PPA (https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup) as descriped in installation manual (https://borgbackup.readthedocs.io/en/stable/installation.html) the installation fails with 404 error.

#### Include any warning/errors/backtraces from the system logs
```
Err:15 http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu impish Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg ^

**Comment by ThomasWaldmann** [comment]
@femto-code can you try https instead of http?

**Comment by femto-code** [comment]
Now with `https://` in apt sources I get:
```
W: Failed to fetch https://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu/dists/impish/InRelease  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 91.189.95.85 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

To me, it seems like there is something wrong with the UBUNTU version being `impish`

![Screenshot_20220416_150031](https://user-images.githubusercontent.com/59444046/163675959-309b1ec2-410e-4cae-910a-b9a5661a0e53.png)

The dropdown does not offer impish nor 21.x - maybe that is the problem?

**Comment by ThomasWaldmann** [comment]
Ah, right, it seems there is nothing for impish. Jammy is around the corner anyway, guess you could just use that (now or soon).

**Comment by femto-code** [comment]
Okay, thanks for the clarification @ThomasWaldmann !

Two more questions out of curiosity/interest:

1. What is the reason why this PPA is not usable on 21 impish?

2. Would you recommend upgrading to 1.2? Does the packed binaries have any dependencies? Everything needed to get it to run just as the apt-installed one?

**Comment by ThomasWaldmann** [comment]
@femto-code this ppa is made by @LocutusOfBorg (who maintains borg for debian and ubuntu).

I don't know the reasons why not for impish, but I would suspect lack of developer resources. It takes some time for porting / testing and a lot of people rather use the LTS versions and not that many use the versions in between.

1.2.0 is rather fresh still and there were some bugs discovered even though we did a long alpha / beta / rc testing phase. Have a look at the 1.2.1 milestone to see what will be addressed by that upcoming release.

The fat pyinstaller-made binaries have no dependencies except glibc and related stuff (libcrypto), all other stuff is bundled into them, so just try it.

**Comment by FabioPedretti** [comment]
You can try my unofficial PPA: https://launchpad.net/~oibaf/+archive/ubuntu/test/+packages

**Comment by femto-code** [comment]
Okay, thanks @ThomasWaldmann for the in-depth explanation and @FabioPedretti for the PPA hint!

I think I will switch to 22.04 soon however, when borg 1.2 can be considered as widely bug-free.

Closing this now - please keep up your work at this awesome project!

**Comment by LocutusOfBorg** [comment]
Hello, no big reason, except that impish is going EOL in 2022-07-14
