### ISSUE TITLE
Replace id_key, enc_key and enc_hmac_key with a single field

### ISSUE THREAD

**Issue by hexagonrecursion** [borgbackup/borg#6611]
If we choose to break with the past #6602, I propose we simplify our key format. Our keys currently store 800 secret bits split into 4 fields: id_key (256 bits), enc_key (256 bits), enc_hmac_key (256 bits) and chunk_seed (32 bits). The fields were once created each for a specific purpose, but some were later repurposed:
1. We needed a new key to authenticate the manifest. We currently derive it via a key derivation function from a concatenation of id_key, enc_key and enc_hmac_key.
2. In #6463 we needed a session key. We currently derive it via a key derivation function from a concatenation of enc_key and enc_hmac_key.

I propose we future-proof our key format by having a single secret field - a seed. We can then derive any number of keys we need from it via a cryptographically secure pseudorandom number generator.

P.S. I myself do not currently have an opinion on whether breaking with the past (#6602) is a good idea or not.
P.P.S. We might want to future-proof the format by generating a bigger seed than we need and truncating it to the length a given PRNG wants. We can then upgrade to a PRNG with a bigger seed without changing the format

**Comment by ThomasWaldmann** [comment]
idea:
- have a new attr `crypt_key` that contains 512 bits
- while we need it, have a property `enc_key` that returns first half of `crypt_key`
- while we need it, have a property `enc_hmac_key` that returns second half of `crypt_key`
- load: deal with old and new keys, but feed into crypt_key attr
- save: only save new keys

**Comment by ThomasWaldmann** [comment]
hmm, not that easy. `enc_hmac_key` and `id_key` for the blake2b-based modes are 1024bits long.

**Comment by ThomasWaldmann** [comment]
Old borg can not read/process the new keys that have `crypt_key` instead of `enc_key` and `enc_hmac_key`, thus increasing the key `version` to `2`.
