### ISSUE TITLE
remove "all archives" stats when no one asked for it

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6638]
quite some operations output the "all archives" stats line.

it's usually fine and fast, if you just have a few archives (like 50).
but it can be slower, if you have a lot of archives (like thousands).

also there's the "no one asked for this" issue for some of the commands.

these commands deal with just 1 archive, but they output "all archives" stats:
```
borg create --stats
borg info repo::archive
(maybe some more)
```

i guess "all archives" should be removed from everywhere except:
```
borg info repo
```

**Comment by DrBrynzo** [comment]
I actually like to see this output from --stats when I'm reviewing backup logs. It helps maintain an awareness of overall time deltas and overall deduplication. Occasionally, I also do several restores and run recursive diffs to look for (un)expected changes. Checking the most recent --stats output gives me a quick mental map of "worst case" storage needs for these operations. Of course I could just get used to running "info" before doing so.

Would it be feasible to have a --stats-all argument (or similar)?

Definitely file under "nice to have" and not "deal breaker".

**Comment by deathtrip** [comment]
Removing  "all archives" will make the --stats argument nearly useless. As right now it gives a good idea of the size of the current archive within the repo.
No one might have asked for this option, but it's been there for a long time, people got used to it and nobody asked for it to be removed.
Also i don't think it's a good idea to make design decisions based on a corner case (over 3000 archives with over billion total chunks on sshfs).

**Comment by ThomasWaldmann** [comment]
Well, with --stats it would still show the "this archive" line, just not the "all archives" line.

The problem is that due to the way which is necessary to correctly compute the "all archives" info, it scales with O(N) at best (for N archives) in borg 1.2. It's even worse for borg 1.2 with borg 1.1 archives and only bearable due to the metadata cache i added to work around this (thus it is only slow the first time).

borg 1.1 computed this a bit differently (and thus quicker), but in some cases incorrect, which often led to confusion.

the general idea about externalising this into "borg info repo" is to make it controllable: you can get the info by using that command, but you're not forced to wait for it just because you wanted the "this archive" stats.

a similar change has been done for compact_segments: it was always done implicitly in borg < 1.2 (slowing things down) and now users have better control via "borg compact".

**Comment by FabioPedretti** [comment]
> Would it be feasible to have a --stats-all argument (or similar)?

Not really sure if we want yet another option, but I agree that --stats-all or --stats-full with all info may eventually be a nice compromise for who want avoid doing an additional borg info.

**Comment by fantasya-pbem** [comment]
I am ok with removing "all archives" from `--stats` if we add `--stats-all` that mimics the old `--stats` behaviour.

**Comment by ThomasWaldmann** [comment]
In borg2, stats stuff changed considerably anyway, so I also implemented this.

repo ops now give some repo stats, archive ops give archive stats.

see the borg 2.0.0a2 alpha release.

in general, it has less stats due to the csize removal. but csize had to go, it was always in the way and was one of the things blocking some nice features, like efficient repo-level recompression.

maybe some stuff can come back later, it just needs to be implemented differently.
