### ISSUE TITLE
max_duration=3600 not supported?

### ISSUE THREAD

**Issue by TheBekker** [borgbackup/borg#6647]
I have had a borg backup setup running for a while now and i try to add --max-duration to my repo check, but i'm getting an error about my borger server being old, and it requiring 1.2.0a4.
I am running 1.2.0, and from what i see in changelog, 1.2.0.a4 is older than 1.2.0, or am i missing something?

```
/ # borg check --max-duration=3600 --repository-only 'ssh://XXXX'
Borg server is too old for check max_duration=3600. Required version 1.2.0a4
/ # borg --version
borg 1.2.0 
```

**Comment by infectormp** [comment]
1.2.0.a4 is alpha
1.2.0 is stable one

**Comment by TheBekker** [comment]
> 

Yes, but 1.2.0a4 is older than 1.2.0 right? (at least according to the changelogs)

So is --max-duration only supported in that specific alpha and the removed from the stable?
Or is version check for that argument bugged?

**Comment by infectormp** [comment]
No, 1.2.0 is older. --max-duration supported by stable version too.

**Comment by infectormp** [comment]
Borg **server** is too old

Check borg version on remote server

**Comment by TheBekker** [comment]
> No, 1.2.0 is older. --max-duration supported by stable version too.
Are you sure? 
According to releases here and on the changelog, 1.2.0a4 is from 2019 and 1.2.0 is from 2022.


> Borg **server** is too old
> 
> Check borg version on remote server

Do you mean on my repository?
I do run the repository on a remote server, how would i check the version of that?

I tried running upgrade, but seems like `upgrade` doesn't play nice with remote repo?
Seems to think its a local repo.

````
/ # borg upgrade 'ssh://XXXX@XXXXX:23/backups/thebeast'
Repository /backups/thebeast does not exist.
````

**Comment by infectormp** [comment]
a mean 1.2.0 is newer. You should not use alpha version.

**Comment by TheBekker** [comment]
> a mean 1.2.0 is newer. You should not use alpha version.

Yes and i am not.
I'm running 1.2.0, as shown in my example running `borg --version`, it returns `1.2.0`.

That is why i am confused by the error about running an old version.

**Comment by ThomasWaldmann** [comment]
You need to check the borg version on the borg host you use in `ssh://borghost`.

**Comment by TheBekker** [comment]
> 

How would i do that?
I'm just hosting a remote storage, where i pointed my repository to be created at. (hetzner storagebox to be exact)
Or am i misunderstanding how it works?

**Comment by ThomasWaldmann** [comment]
Try sshing into there manually, you will get some error that includes the borg version.

**Comment by TheBekker** [comment]
> Try sshing into there manually, you will get some error that includes the borg version.

Doesn't seem like i get the borg version back from them. 

````
~#@❯ ssh uXXXXX@uXXXXX.your-storagebox.de                                                                      ❮  
uXXXXX@uXXXXX.your-storagebox.de's password:
PTY allocation request failed on channel 0
shell request failed on channel 0
````

I've just sent them an email asking about versions and if it's possible to upgrade.
Sorry, I wasn't aware that the repo was actually running a borg instance as well.
Thought it was just running on my end, and then just dumping data vis SCP/SSH.

**Comment by ThomasWaldmann** [comment]
Hmm, guess that is due to hetzner's special logging configuration again, normally one can see the version.

But IIRC they wanted to wait for 1.2.1 before switching.

**Comment by TheBekker** [comment]
> 

Ahh i see, i guess might have to wait a while before i can get some new fancy features.

Well, thanks for clearing stuff up :)
