### ISSUE TITLE
Screencast:  Uses --stats without adding -v

### ISSUE THREAD

**Issue by dannyedel** [borgbackup/borg#665]
This was reported as debian bug [814853][], but I do not believe it is specific to the debian version. I can reproduce this with the precompiled `borg-linux64` binary, so I am forwarding it here.

The screencast linked on the startpage shows the usage of `--stats` parameter, but omits `-v`.
Typing the same commands on a fresh installation will produce no output, which will confuse users a lot.

This is not a bug, since the manpage clearly states without `-v` parameter or a logging configuration we will not see the stats.

I just think the screencast should be updated to use `--stats -v` to not depend on any set environment variables, and make the output reproducible.

----

Also, since borgbackup gets included into more and more distributions (see #105) it might make sense to provide different two screencasts for installation, and for usage, since more and more users will be able to use their native package manager for installation and just want to see the usage part.

[814853]: https://bugs.debian.org/814853

**Comment by glandium** [comment]
I'd argue this: what is the point of an option that does nothing unless another option is given?

**Comment by ThomasWaldmann** [comment]
The screencast was made with an older borg version.

@dannyedel Splitting up the screencast into 2+ makes sense: installation (binary), usage (simple).

Later, usage (advanced) could be added as another screencast.

@glandium it's not that it is doing nothing, it sets the internal log level (see also the documentation).

**Comment by glandium** [comment]
@ThomasWaldmann it might not be doing nothing technically, but as far as a user is concerned, it is. Also, few people will read manpages, and --help doesn't say anything about this "feature".

**Comment by glandium** [comment]
Also, using -v enables *other* messages.

**Comment by ThomasWaldmann** [comment]
@glandium here it does:
```
$ borg create --help
...
  -v, --verbose, --info
                        enable informative (verbose) output, work on log level
                        INFO
  --debug               enable debug output, work on log level DEBUG
...
```

**Comment by glandium** [comment]
No it doesn't:
```
  -s, --stats           print statistics for the created archive
```

**Comment by glandium** [comment]
My point is, if you do `borg create --stats`, you don't get stats. If you do `borg create -v --stats`, now you get stats, but you also get other messages.

**Comment by ThomasWaldmann** [comment]
Come on, please read the help completely. If it's  not clear enough from there, read the docs, they explicitely tell that you have to lower the log level to see informative output. and stats are not warnings, so you don't see them on warning log level.

**Comment by glandium** [comment]
Come on, do you expect everyone to go read the full documentation when `--help` has plenty of info already? Plus, the documentation doesn't tell me how to display the stats *and only* the stats. Oh, wait, right, it's just not possible.

**Comment by ThomasWaldmann** [comment]
If you have a better idea than the current implementation of output and logging, feel free to open a ticket about the whole new plan. You'll have to consider all the circumstances and scenarios where it needs to work (which are even shortly documented) in your plan, though.

**Comment by glandium** [comment]
Why should I, totally not familiar with the code (as in, I never even remotely looked at it), make a "whole new plan" to fix something that, as the screencast shows, was not a problem in the past? You should be able to tell why it worked before and why it doesn't now. Or don't you even acknowledge that there is a usability problem?

**Comment by ThomasWaldmann** [comment]
EOD.
