### ISSUE TITLE
Cannot backup network filesystems

### ISSUE THREAD

**Issue by pigmy31** [borgbackup/borg#6650]
Hi,

## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

This an ISSUE report.

OS: Ubuntu 22.04
BorgBackup: 1.2
Vorta version: 0.8.3
Installed from: packages from Ubuntu repository

## Describe the problem you're observing.
Since my upgrade to Vorta 0.8.3/BorgBackup 1.2, network filesystem backups fail with error code 1: vorta.borg.borg_job - WARNING - /media/nas/donnees: file inode changed (race condition), skipping file

I tested with the option: --files-change=ctime,size (parameter added to the last line of the planning tab), but the error still occurs.

Is this behavior already identified? Is it a bug or a misuse on my part?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes

Regards

**Comment by ThomasWaldmann** [comment]
You could use the `stat` command on that file (or any file on that network fs).

Does the inode change for each `stat` you do?

BTW, you have a typo in there, it is `cache`not `change`.

`--files-cache=ctime,size` would fix the files cache behaviour for unstable inodes, but what you see here is the check for race conditions (file is changing while borg tries to back it up), that is something else.

**Comment by ThomasWaldmann** [comment]
Also: rc 1 means warning (== you have to check whether the reported problem is of relevance to you, likely all files except the ones with warnings/errors were backed up, just not the problematic ones).

**Comment by pigmy31** [comment]
Ok, I saw my mistake in the description. I did write "--files-cache" in Vorta. Thanks for your attention.

I used the `stat` command on my three network file systems (FYI, they are self-mounted) and the values shown are strictly identical. These file systems, and the files they contain, do not change that often and never when a backup is run (this last comment for your last explanation I did not understand from reading the documentation).

This behavior appeared when I upgraded my computer (OS version from which the Borg and Vorta upgrades came). Before that, I had never had this kind of error.

**Comment by ThomasWaldmann** [comment]
borg 1.1 and 1.2 work a bit differently: fd-based (1.2) rather than name-based (1.1).

also, it checks the stat there:
```


def stat_update_check(st_old, st_curr):
    """
    this checks for some race conditions between the first filename-based stat()
    we did before dispatching to the (hopefully correct) file type backup handler
    and the (hopefully) fd-based fstat() we did in the handler.

    if there is a problematic difference (e.g. file type changed), we rather
    skip the file than being tricked into a security problem.

    such races should only happen if:
    - we are backing up a live filesystem (no snapshot, not inactive)
    - if files change due to normal fs activity at an unfortunate time
    - if somebody is doing an attack against us
    """
    # assuming that a file type change implicates a different inode change AND that inode numbers
    # are not duplicate in a short timeframe, this check is redundant and solved by the ino check:
    if stat.S_IFMT(st_old.st_mode) != stat.S_IFMT(st_curr.st_mode):
        # in this case, we dispatched to wrong handler - abort
        raise BackupError('file type changed (race condition), skipping file')
    if st_old.st_ino != st_curr.st_ino:
        # in this case, the hardlinks-related code in create_helper has the wrong inode - abort!
        raise BackupError('file inode changed (race condition), skipping file')
    # looks ok, we are still dealing with the same thing - return current stat:
    return st_curr
```

**Comment by ThomasWaldmann** [comment]
So, do you see that error often? Is it always the same file? Is there something special about that file?

**Comment by pigmy31** [comment]
Hi,

@benurb :
     my network filesystems, based on NFS, don't use hidden files.
@ThomasWaldmann : 
     This error occurs with every backup.
     These are always the same file systems (the error occurs every time for /media/nas/films and /media/nas/photos, and 4 times out of 5 for /media/nas/data) and therefore no files, contained under these mount points, are backed up.
     No particular files (avi, jpg, mkv, ods, pdf, and so on), these are file systems used by two computers for personal use.

Regards

**Comment by ThomasWaldmann** [comment]
@pigmy31 so the "special" thing is that all these files are in fact **directories** and also **mountpoints**?

is the mounting already done when you start borg or do you use some automounter or something similar?

**Comment by pigmy31** [comment]
Hi Thomas,
Network file systems are handled by the automounter. I will test by forcing them to be mounted before borg backs them up in three weeks. I'll be out of town during that time.
I'll let you know when I get back.
Regards

**Comment by ThomasWaldmann** [comment]
So, does it work if you normally mount before invoking borg?

**Comment by pigmy31** [comment]
Hi Thomas,
I am back after three weeks away from home and one week to test your solution.
You were right. I did a "while true" loop, to keep my automounted filesystems during the backup, and everything was correctly saved.
I close this problem and it is solved for me.
Thanks for your help.
Greetings
Michel

**Comment by ThomasWaldmann** [comment]
@pigmy31 ok, thanks for the feedback.

**Comment by Revan335** [comment]
> Hi Thomas, I am back after three weeks away from home and one week to test your solution. You were right. I did a "while true" loop, to keep my automounted filesystems during the backup, and everything was correctly saved. I close this problem and it is solved for me. Thanks for your help. Greetings Michel

What is the solution?
Maybe i'm blind to see her.

**Comment by ThomasWaldmann** [comment]
@Revan335 I think the problem was some sort of "automounter" that mounted some filesystem into the mountpoint directory on first access (by borg). This triggered a change of the inode, which triggered the race condition warning in borg (and also borg skipping to process that directory).

If the stuff is just mounted before the borg backup run (and stays mounted as long as the backup is running), there is no such problem.

**Comment by Revan335** [comment]
> @Revan335 I think the problem was some sort of "automounter" that mounted some filesystem into the mountpoint directory on first access (by borg). This triggered a change of the inode, which triggered the race condition warning in borg (and also borg skipping to process that directory).
> 
> If the stuff is just mounted before the borg backup run (and stays mounted as long as the backup is running), there is no such problem.

Thanks!
OK, but we can trigger the mount and umount before and after the backup in borg/vorta to bypass? the automounter?
This the automounter that are used: https://forum.endeavouros.com/t/root-mounting-any-device-using-systemd-mount-and-automount/7696 https://root.nix.dk/en/notes-and-bookmarks/systemd-sample-mount-units

**Comment by ThomasWaldmann** [comment]
Well, the simplest thing would be to not use an automounter.
If you use one, you could just access the mountpoints before borg runs, so they are (and stay) mounted.

**Comment by Revan335** [comment]
Can i automated this with borg/vorta? Access and stay the mountpoints before and exit the mountpoints after the backup.

**Comment by ThomasWaldmann** [comment]
borg has no option for that and I suspect neither has vorta.
but you can just add that to your borg script / pre-backup commands.
