### ISSUE TITLE
borg check --repair using a lot of CPU but no I/O?

### ISSUE THREAD

**Issue by Daniel15** [borgbackup/borg#6669]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
1.1.16 installed via Debian package

#### Operating system (distribution) and version.
Debian bullseye

#### Hardware / network configuration, and filesystems used.
Borgbackup server is a VPS with 10TB space, 2GB RAM, 2 CPU cores
Server being backed up is a dedicated server, 8 cores, 16GB RAM, 1TB disk space but not much of it is backed up
Both are using ext4.

#### How much data is handled by borg?
~95GB for this particular backup

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg check --verbose --repair --verify-data ssh://backup-lv02@xxxxx:22/data/backup/lv02
```

## Describe the problem you're observing.

I;'m trying to recover from data corruption on the server hosting the backups for a particular server.

I got this output:
```
$ borg check --verbose --repair --verify-data ssh://backup-lv02@xxxxxxxxx:22/data/backup/lv02
This is a potentially dangerous function.
check --repair might lead to data loss (for kinds of corruption it is not
capable of dealing with). BE VERY CAREFUL!

Type 'YES' if you understand this and want to continue: YES
Remote: Starting repository check
Remote: Data integrity error: Segment entry checksum mismatch [segment 169, offset 131220]
Remote: attempting to recover /data/backup/lv02/data/0/169
```

It's been sitting like this for a while, with CPU usage at 100% of one core (the backup server has two cores):
![](https://d.sb/2022/05/firefox_06-17.42.47.png)

However, the disk is mostly idle?
![](https://d.sb/2022/05/firefox_06-17.40.44.png)

What is it doing?

I killed it because I think it's just going to be quicker to restore the Borgbackup repo from a mirror.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes

#### Include any warning/errors/backtraces from the system logs
Can't see any relevant logs

**Comment by ThomasWaldmann** [comment]
It's going over the corrupted segments byte-by-byte and trying to find and rescue all entries that are ok still.

This was optimized to work faster recently, btw. - by using some additional checks, a lot of crc32 computations can be skipped. IIRC, it is in 1.2.0, but sure about 1.1.x, check the change log.

**Comment by Daniel15** [comment]
> It's going over the corrupted segments byte-by-byte

But there's no disk I/O happening, and it definitely can't cache that much data in only 2GB of RAM. 🤔

> IIRC, it is in 1.2.0

Unfortunately Debian don't ship 1.2 in stable and don't have a backport for it.

**Comment by ThomasWaldmann** [comment]
A segment is usually 500MiB and will get mmapped for that purpose. Going over that byte-by-byte will take a while.

If you only have 2GB of RAM, it could be also that your system is paging?

**Comment by Daniel15** [comment]
Thanks @ThomasWaldmann  - makes sense. 😃

**Comment by ThomasWaldmann** [comment]
The root cause of that more-or-less inefficient process was also recently fixed in master: the repo format of attic and also current borg has a **CRC32** over header **and** data.

There are 2 problems with that:
- one can't quickly compute whether only a header is correct (including vital information like length == where next header starts), because it extends over all header+data.
- crc32 implementations have quite varying speed, depending on how well they are tuned to your CPUs capabilities (1:10 speed differences have been seen) - this was also recently addressed by chosing the quicker of 2 libs depending on platform.

**Comment by ThomasWaldmann** [comment]
BTW, `--verify-data` is also quite expensive.

**Comment by jdchristensen** [comment]
> Unfortunately Debian don't ship 1.2 in stable and don't have a backport for it.

You can just use the pre-compiled fat binary.  That's what I use on all of my systems, which makes it easy to keep up-to-date with borg, independent of the OS version.

**Comment by Daniel15** [comment]
I'm going to close this issue since my questions were answered. Thank you!

> > Unfortunately Debian don't ship 1.2 in stable and don't have a backport for it.
> 
> You can just use the pre-compiled fat binary. That's what I use on all of my systems, which makes it easy to keep up-to-date with borg, independent of the OS version.

I prefer using Debian packages since `unattended-upgrades` keeps everything up-to-date in terms of security patches, but maybe I'll take your idea and just deploy the static binary to all my systems. I've already got Ansible playbooks for some other things so I can just add it to those.
