### ISSUE TITLE
update the screencast

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#669]
it was made with a old version of borg, also it deals with both installation (binary) and usage (simple examples).

the new screencasts need to be separate and deal with:
- installation (binary)
- usage (simple)
- usage (advanced)

New screencasts must be made with 1.0.0rc2 or later.

**Comment by ThomasWaldmann** [comment]
at the beginning of the screencast, a comment could be included like:
`this teaser screencast was made with borg version x.x.x - older or newer borgs may behave differently.`

**Comment by rugk** [comment]
Is it okay to do this with borg v1.0.9?

**Comment by enkore** [comment]
I think perhaps use 1.1.0b6, since that includes some nice quality of life improvements over 1.0 (like --stats without --verbose).

**Comment by ThomasWaldmann** [comment]
Yeah, using 1.1 beta and (only) linking it from master would be good. Maybe mention in your screencast that you are using 1.1.

**Comment by rugk** [comment]
* Install: https://asciinema.org/a/UKPQ8A1RVapVy2yGaSJFTpsxQ

**Comment by enkore** [comment]
Nice. I edited it a bit (shortened the long download and removed some non-visible stuff, /FedRocks etc.): https://asciinema.org/a/auUuafZKRJ24RmalxcxV7CtDB

**Comment by rugk** [comment]
added basic usage…

**Comment by rugk** [comment]
I've updated [the scripts for the advanced screencast](https://gist.github.com/rugk/4176a6c46031c6ae2a9b51b83035dce9). I'll do the screencast tomorrow, so if you have anything, which you don't like at the script or something is missing, complain now and I can still change it. :smiley:

**Comment by ThomasWaldmann** [comment]
@rugk I'll have a look after the sprints. For review it would be easier if it was in a pull request, so one can add comments/feedback.

**Comment by rugk** [comment]
But you do not want to have these into your repo…
BTW which sprints?

Also note that the commands at the end, will still get some comments. I'll have to try them out, first, however.

**Comment by ThomasWaldmann** [comment]
@rugk sprints at europython, today and tomorrow. random borg stuff, nothing specific.

**Comment by rugk** [comment]
In any case I'll try to finish the screencast today.

**Comment by rugk** [comment]
Okay, I've changed my opinion: I'll finish this tomorrow…

Also: Would you like to upload the asciinemas to your account or can I just use my account there?
Of course, I'll provide the snippets, thumbnail (seconds) and so on…

**Comment by ThomasWaldmann** [comment]
If you just do a PR with all the files AND upload a easy reviewable demo to your account, review is easy.

Later I can update the screencast on the current account.
