### ISSUE TITLE
compression type bytes: include compression level / preset

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6698]
when using `borg recreate`, there is the `--recompress if-different` option, that only recompresses if the data it is not already compressed with the desired algorithm.

this is useful to e.g. change from zlib to zstd, but not for changing zstd,1 to zstd,6.  because we do not store the level yet, borg can only see "this is zstd compress", but has no idea about the level.

we store 2 bytes for the compression and currently only 1 of them is really used (only exception: the zlib type bytes hack we needed for the attic to borg transition). this hack is going away within PR #6663.

so we could store the level / preset into the 2nd byte to support `borg recreate` working efficiently when staying within the same algorithm and just changing the level.

for the import of compressed data (like with `borg transfer`), we do not know the compression level, so guess we need to reserve `0xff` to mean `unknown level`) and patch that into the compression header at `borg transfer` time.

**Comment by ThomasWaldmann** [comment]
Note: the obfuscation "compressor" handling needs checking first.

**Comment by ThomasWaldmann** [comment]
some compressors like `NONE` and `LZ4` do not use compression levels.
as we do not know yet whether we might use a level somehow later, the level is set to 0xFF for now.

**Comment by FabioPedretti** [comment]
Just a note that a compression level may change between different compressor version.
E.g. zstd 1.5.2 may have a compression level of 12 having similar performance (compressed ratio) of zstd 1.4 level 10 or 1.3 level 8.
So it should be intended mostly as a reference.

**Comment by ThomasWaldmann** [comment]
Thanks for the hint. But I don't think there is much we can do about this.
We just put into that byte what was give to the compressor at the time of compression.

Also, we have to hope noone will need level >= 255. :-)

**Comment by FabioPedretti** [comment]
Also note that zstd may use levels < 0.

**Comment by ThomasWaldmann** [comment]
Oh. We do not support these yet in borg, but I guess I'll put a range check in there.

**Comment by ThomasWaldmann** [comment]
fixed, see above.
