### ISSUE TITLE
borg-create: non-existing top level paths should be explicitly logged

### ISSUE THREAD

**Issue by azrdev** [borgbackup/borg#6708]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
* client 1.1.17
* server 1.1.16

#### Operating system (distribution) and version.
* client Fedora 35
* server Debian 11

#### Hardware / network configuration, and filesystems used.
irrelevant, I think

#### How much data is handled by borg?
irrelevant, I think

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
~~~sh
me@client$ borg create --stats --verbose --show-rc --compression auto,zstd,9 \
        ssh://server/~/borg02::client.{utcnow} \
        /etc \
        /home/me/directory-does-not-exist
~~~

## Describe the problem you're observing.
When passing a PATH to `borg create` that does not exist (among others that do), it returns 1 indicating "warning  (operation  reached  its normal end, but there were warnings -- you should check the log, logged as WARNING)" but there is nothing logged to stdout/err, even with `--verbose`. In other words: borg states something failed, and I should see why above, but I don't.

Adding `--list --filter='E?'` reveals that the top-level PATH was not found (in my case a typo, which excluded the meant directory from backups).

In such a case, I'd expect the missing top-level PATH to be printed (at least on --verbose).

#### Include any warning/errors/backtraces from the system logs

none

**Comment by ThomasWaldmann** [comment]
I just tried to reproduce with borg 1.2-maint branch:
```
(borg-env) tw@mba2020 borg % borg create repo12::archive src/ foobar/ docs/
Enter passphrase for key /Users/tw/w/borg/repo12: 
foobar: [Errno 2] No such file or directory: 'foobar'
```

So I guess this was either fixed at some time or you just overlooked the output.
