### ISSUE TITLE
Offer binary wheels for borg?

### ISSUE THREAD

**Issue by modem7** [borgbackup/borg#6721]
Heya, 

I'm working with @grantbevis on https://github.com/borgmatic-collective/docker-borgmatic

During development and testing of multi-arch versions of Borgmatic, we install Borg as standard. 

Due to borgbackup only having a Source Distribution, it takes quite some time to build for multiple architectures, which can slow down testing time (takes approx an hour to build for amd64 and arm64 from source).

Would it be possible to ask for a wheel/built distribution to be created and added to pypi as part of the release (much like [borgmatic](https://pypi.org/project/borgmatic/#files) has) to make build times far quicker?

This should also decrease install time for those who wish to install via pip instead of a repo.

**Comment by infectormp** [comment]
borg has fat binary also. You can find it @ https://github.com/borgbackup/borg/releases

**Comment by ThomasWaldmann** [comment]
Not sure I want to get into wheel building.

I don't really trust "cloud based" building. In case someone would own that infrastructure, they would also own all machines running those wheels.

Not sure about locals ways to build a lot of wheels, what are the options? I don't like to run docker either, btw.

**Comment by modem7** [comment]
> Not sure I want to get into wheel building.
> 
> I don't really trust "cloud based" building. In case someone would own that infrastructure, they would also own all machines running those wheels.
> 
> Not sure about locals ways to build a lot of wheels, what are the options? I don't like to run docker either, btw.

Unfortunately my knowledge on Python is borderline non-existent. 

What I did find was: https://github.com/borgmatic-collective/borgmatic/blob/master/scripts/release - but not quite sure if this would work. 

My (very poor) understanding from the Borgmatic release is that they use a [universal wheel](https://realpython.com/python-wheels/#specifying-a-universal-wheel) rather than a distribution wheel, which should allow it to be used on any distro/arch.

I could be very wrong though!

**Comment by ThomasWaldmann** [comment]
Universal wheels can't be made from borg, because borg is not pure python, but also needs C and Cython stuff to be compiled and the resulting shared objects to be included into the wheel.

So we would need to build wheels for all python versions, for linux, macos, bsd, maybe windows later.

**Comment by ThomasWaldmann** [comment]
BTW, why does your build take an hour? Is non-native qemu involved here?

**Comment by modem7** [comment]
> BTW, why does your build take an hour? Is non-native qemu involved here?

Unfortunately so.

Buildx (qemu emulation) cross compiling for multiple architectures on an x86_64 system, outputting a single manifest which has the multiple arches together in a single file/tag.

Worse yet, it's using docker-in-docker to do it. Great for CI, but there's obviously going to be performance degredation.

**Comment by ThomasWaldmann** [comment]
Maybe an idea would be to have a cache for the borg wheels it builds locally from the sdist and persist that between runs.

**Comment by ThomasWaldmann** [comment]
BTW, borg also likes to have a non-stoneage glibc to use some features not present in older ones. So, IF we would build wheels, guess it would not be `manylinux1` wheels, but something more recent.

**Comment by modem7** [comment]
> borg has fat binary also. You can find it @ https://github.com/borgbackup/borg/releases

The problem with the fat binaries, is that for arm, it'd require a separate tag, rather than a multi-arch manifest (unless you significantly edit the build method).

**Comment by modem7** [comment]
> BTW, borg also likes to have a non-stoneage glibc to use some features not present in older ones. So, IF we would build wheels, guess it would not be `manylinux1` wheels, but something more recent.

Given my lack of knowledge of Python, I'd be more than happy to test any manual method (with some guidance) to see if there's a good automated method to do this.

**Comment by ThomasWaldmann** [comment]
Yeah, guess the cibuildwheel would be a low-effort way to solve.

I just have bad feelings about the security of running the "produced in the cloud" binary wheels as root on production systems.

Am I too paranoid? :-) Would like to hear some opinions.

**Comment by modem7** [comment]
> Am I too paranoid? :-) Would like to hear some opinions.

IMO, yes.......and no. 

My opinion is: Your views are completely valid and sensible, but there are also additional protections you can utilise to limit potential bad actors. 

GPG signing, 2fa with hardware keys for example, and/or......Utilise a locally hosted CI/CD system like self hosted Github runners, or GitLab etc to build. 

Maybe make sure there are multiple reviewers and authorisers for runs etc.

But that's my personal view. I have had issues in the past with bad actors, my codebase wasn't breached, but resources were utilised. So your views above are absolutely not without merit.

**Comment by grantbevis** [comment]
I'm also 50/50 in that cloud building is super convenient but at what cost? 

@modem7 and I have discussed using the default Alpine repository version of borg for our image but there may be some lag when a new version is released.

It's not the end of the world that it takes so long to compile due to the frequency at which we release. Perhaps @modem7 we should have another image where we build the pypi version of borg in to a python:alpine container and then we base borgmatic's container from that image. Meaning when we need to build a later borgmatic version and borg's version hasn't changed our image builds should be in minutes not hours.

Something to consider, @ThomasWaldmann - Is there an official borgbackup docker image? If not would you be open to us providing the image code?

**Comment by modem7** [comment]
> Perhaps @modem7 we should have another image where we build the pypi version of borg in to a python:alpine container and then we base borgmatic's container from that image. 

That not a bad shout tbf, especially if they're tagged, and borgmatic already had wheels built anyway.

It's certainly an avenue to investigate, the other would be to build our own wheel and copy it in during build time, both should give us what we require, and as a bonus, we could also build for more architectures as it'd take less time build to build.

**Comment by ThomasWaldmann** [comment]
@grantbevis there has been some activity about borg and docker in the past, but the main issue is that i personally don't use docker, so I don't want to maintain that. Also, I can't review docker stuff due to lack of experience with it.

So maybe it is best to have that in a community repository and everybody who wants to use it can fetch it from there.

**Comment by modem7** [comment]
Hey guys,

Whilst not automated (yet), I've done this so far:

https://github.com/modem7/docker-borgmatic

Dual arch builds down from ~1 hour to ~6 minutes.

I build the wheels manually atm with Docker, emulating whatever arch I require, but subsequent builds are substantially faster throughout.

For now, this method is keeping in line with KISS, but automation will eventually be the end goal.

**Comment by modem7** [comment]
I've made my own version of a pypi index (https://github.com/modem7/PyPI) which works quite well.

There are scripts with comments in there for building the wheels in multiarch using docker too.

**Comment by modem7** [comment]
Closing with resolution of https://github.com/borgmatic-collective/pypi
