### ISSUE TITLE
borg create stat: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by aoblet** [borgbackup/borg#6725]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question. Can we force borg create to continue if a file is not accessible ?

It can happens in case of filesystem error. It represents a very small portion of files (a few).

I would like borg to ignore these errors and backup the rest of the files.

#### Your borg version (borg -V).
borg 1.1.9

#### Operating system (distribution) and version.
Debian GNU/Linux 10 (buster)

#### Hardware / network configuration, and filesystems used.
ZFS

#### How much data is handled by borg?
20 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create --show-rc '/tmp/test::test-{utcnow}' /mnt/test

## Describe the problem you're observing.
```bash
/path/to/folder: stat: [Errno 5] Input/output error: '/path/to/folder'
terminating with warning status, rc 1
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes.

**Comment by ThomasWaldmann** [comment]
> Question. Can we force borg create to continue if a file is not accessible ?

That is the default behaviour. Since quite a while.

You could get a more recent version via debian backports apt source btw.

**Comment by aoblet** [comment]
Updated. Thanks for the quick answer.
