### ISSUE TITLE
Missing development dependencies

### ISSUE THREAD

**Issue by qua-bla** [borgbackup/borg#673]
I tried to follow <http://borgbackup.readthedocs.org/en/stable/installation.html#git-installation> and noted `liblz4-dev` and `libacl1-dev` as unmentioned dependencies. A vague hint to the distro packages that are required would come in handy.

**Comment by ThomasWaldmann** [comment]
See there: http://borgbackup.readthedocs.org/en/stable/installation.html#dependencies

**Comment by ThomasWaldmann** [comment]
the -dev is maybe really missing, just the non-header packages are mentioned.

**Comment by qua-bla** [comment]
Sorry, I definitely overlooked the distro specifics. With the new hint, maybe even I will find them in the future ;)

**Comment by ThomasWaldmann** [comment]
Guess they should be mentioned in the general section.
If you don't run any of the specifically covered distros, you won't read their doc section.
