### ISSUE TITLE
borg compact --cleanup-commits documentation doesn't match experience

### ISSUE THREAD

**Issue by griffrawk** [borgbackup/borg#6732]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).
1.2.0

#### Operating system (distribution) and version.
Arch Linux 

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg --verbose compact --cleanup-commits /media/Backup/caddy-borg`

## Describe the problem you're observing.
When I first tried to do the cleanup-commits action after 1.2.0 upgrade, borg threw an error for the above command line despite it appearing to fulfil the requirement:
`borg: error: unrecognized arguments: -–cleanup-commits`

```
% borg help compact

usage: borg compact [-h] [--critical] [--error] [--warning] [--info] [--debug] [--debug-topic TOPIC] [-p] [--iec] [--log-json]
                    [--lock-wait SECONDS] [--bypass-lock] [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
                    [--remote-ratelimit RATE] [--upload-ratelimit RATE] [--remote-buffer UPLOAD_BUFFER]
                    [--upload-buffer UPLOAD_BUFFER] [--consider-part-files] [--debug-profile FILE] [--rsh RSH] [--cleanup-commits]
                    [--threshold PERCENT]
                    [REPOSITORY]
```
... gives the options as preceding the repo, but I could only make it work by appending `--cleanup-commits` *after* specifying the repo:
`borg --verbose compact  /media/Backup/caddy-borg --cleanup-commits`

This doesn't match the docs, the inbuilt help, or any of the other established conventions of the other commands...

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes. 
To troubleshoot, reformat command as above.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/general.html#positional-arguments-and-options-order-matters

Guess this is yet another variation of that documented argparse limitation?

**Comment by ThomasWaldmann** [comment]
Guess it would also work if you moved the `--verbose` to the right of `compact` (as the usage docs you quoted show it).

**Comment by griffrawk** [comment]
Ah, I'd forgotten about that. Thanks for the reminder. Seeing as there's already a mitigation in that doc, I'll close this. 

Ty
