### ISSUE TITLE
Question - nonce file / Backup Borg Repo to WORM / object lock storage

### ISSUE THREAD

**Issue by Catscrash** [borgbackup/borg#6733]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

1.1.9

#### Operating system (distribution) and version.

Debian 9

#### Hardware / network configuration, and filesystems used.

45TB Raid 5, 10G Network, Ext4

#### How much data is handled by borg?

27TB in 400 Repos

## Describe the problem you're observing.

I want to backup the borg repositories securely to a Cloud Provider including ransomware protection / protection from a hacker controlling the borg server. That's why I want to use Backblaze with Object Lock as a sync target. 

With object lock, I can make sure that files that got added once can only be deleted after X days.

My issue is with the nonce file, since that changes after every action, but if I write it on day 1, I can't update it on day 2 when it changed if I have an object lock set on it.

Is this file strictly necessary for restoring from the repository, or can I somehow recreate it, if it got lost? If so, I could exclude it from the object lock and if someone were to delete it, that would be fine? In a short test I was able to access the repository after the file got deleted, but maybe I'm missing something important?

Or is there some way to switch that file to a versioned file like "hints.xxx" or "integrity.xxx"?

**Comment by ThomasWaldmann** [comment]
The `nonce` file is to keep the highest reserved counter value (for AES-CTR encryption) on the server side.

You do not need it for restores, but rather for secure (considering the encryption, one must never repeat the same counter values) creation of backups, especially if there are multiple clients backing up to same repo or if backups get interrupted and restarted or if clients completely use their local memory of the counter.

Make sure you can reproduce the exact state of at least the files in `repo_dir/data/` (that is where you backed up data is) and the `config` file, the misc. `*.nnnnn` files can be rebuilt.

**Comment by Catscrash** [comment]
Perfect, thank you very much
