### ISSUE TITLE
`--patterns-from` still requires `PATH` argument, contradicting documentation

### ISSUE THREAD

**Issue by wilbowma** [borgbackup/borg#6757]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?
Bug

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
macOS 10.15.7

#### How much data is handled by borg?
30GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg create --dry-run --patterns-from ~/.config/borg/include.generic borg-server:backups::'{hostname}+test'
```

## Describe the problem you're observing.
According to the borg-patterns documentation (https://manpages.debian.org/testing/borgbackup/borg-patterns.1.en.html, e.g.), using a `--patterns-from` file should not require a `PATH` on the command line:
> borg create --patterns-from patternfile.lst repo::arch

However, my above command reports:
```
> borg create --dry-run --patterns-from ~/.config/borg/include.generic borg-server:backups::'{hostname}+test'
usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug] [--debug-topic TOPIC] [-p] [--iec] [--log-json] [--lock-wait SECONDS] [--bypass-lock] [--show-version]
            [--show-rc] [--umask M] [--remote-path PATH] [--remote-ratelimit RATE] [--upload-ratelimit RATE] [--remote-buffer UPLOAD_BUFFER] [--upload-buffer UPLOAD_BUFFER]
            [--consider-part-files] [--debug-profile FILE] [--rsh RSH]
            <command> ...
borg: error: Need at least one PATH argument.
```

My `include.generic` is:
```
+ ~/
```

**Comment by ThomasWaldmann** [comment]
You need at least a `R some_recursion_root_path` entry then. borg needs to know where to start.

**Comment by ThomasWaldmann** [comment]
Also be careful with stuff that is normally expanded by the shell (like `~`), this does not happen in the patterns file.

**Comment by wilbowma** [comment]
Ah, right. If I expand ~/ and change it to `R /home/user` it works; my mistake!
