### ISSUE TITLE
Donations page seems outdated

### ISSUE THREAD

**Issue by WilliamDEdwards** [borgbackup/borg#6758]
The [donations page](https://www.borgbackup.org/support/fund.html) mentions three options for donating:

- Liberapay for regular donations
- BountySource, not sure what for
- BountySource Salt for regular donations/bounties

The BountySource text says:

> You can use the above, if you do not have some specific bounty (see below).

I'm not sure what 'above' refers to.

The BountySource link leads to https://app.bountysource.com/teams/borgbackup, which has a 'Support borgbackup' button. This leads to BountySource Salt. That seems redundant, as BountySource Salt is already mentioned as another option.

The BountySource Salt website says:

> We are sorry to inform you that the SALT platform has been temporary closed for technical reasons. Please apologize for any inconvenience.

What is the best option for a one-time donation (no bounty)?

**Comment by ThomasWaldmann** [comment]
Did you try ignoring the banner about salt and donating xx USD "just one time"?

**Comment by ThomasWaldmann** [comment]
BTW, they announce to soon have a better web interface, so we can have some hope. :-)

**Comment by ThomasWaldmann** [comment]
@WilliamDEdwards did you try again?

**Comment by WilliamDEdwards** [comment]
> @WilliamDEdwards did you try again?

I just tried on Bountysource Salt. When clicking "Support borgbackup", the following information is shown:

> Important Billing Details
> [...]
> We accept PayPal and Credit Cards (VISA, MC, AMEX, and more)

However, at checkout it is only possible to use PayPal:

<img width="468" alt="Schermafbeelding 2022-06-15 om 19 47 21" src="https://user-images.githubusercontent.com/12184311/173892097-fe08ce7c-4945-49c1-9787-6d631ec0f67b.png">

I thought maybe I have to enter credit card details in my account details, but the buttons are not visible:

<img width="254" alt="Schermafbeelding 2022-06-15 om 19 46 21" src="https://user-images.githubusercontent.com/12184311/173892174-0333ca5b-aeb7-4c05-ac47-462dee4d7da6.png">
 
Anyway, the only buttons there are for logout and to the 'Supoprt Levels' page, so it doesn't matter anyway.

I found [this comment](https://github.com/bountysource/core/issues/486#issuecomment-643821155) which implies that Bountysource Salt supported credit cards at some point.

The only alternative payment method I can find is on the 'Settings' page under the 'Account' tab:

> You haven't added an ETH address yet.
> Add your ETH address so you can keep track of your crypto contributions!

Not sure how to proceed.

**Comment by ThomasWaldmann** [comment]
Note: I also add paypal to the donations page now as an easy / better usable option.

**Comment by baioc** [comment]
Not to hijack the thread, but adding an OpenCollective link to the donations page may also be a good idea, since it supports wire transfers (no PayPal or credit card needed, unlike the current options).
That is assuming OC is working as expected for the Borg collective (#5674 is still open, so I'm not 100% sure).

**Comment by ThomasWaldmann** [comment]
OC added, bountysource removed.

**Comment by WilliamDEdwards** [comment]
I saw that GitHub Sponsors is now set up, so I donated that way.

**Comment by ThomasWaldmann** [comment]
@WilliamDEdwards thanks for your donation.

yes, gh sponsors is set up (and also goes into our OpenCollective account).
