### ISSUE TITLE
Shell syntax error in documentation (Installation -> Using git)

### ISSUE THREAD

**Issue by taladar** [borgbackup/borg#6761]
In https://borgbackup.readthedocs.io/en/stable/installation.html#using-git

```
virtualenv --python=${which python3} borg-env
```
should be
```
virtualenv --python=$(which python3) borg-env
```

**Comment by ThomasWaldmann** [comment]
Can you make a PR with a fix?

**Comment by targhs** [comment]
I hope that works. Contributing for the first time in Borg. Do we have bounty for this issue?

**Comment by ThomasWaldmann** [comment]
Not specifically, but there might be generic bounties like "update docs" or "do backports".

Currently a bit low on organisation funds for new bounties though ... :-(

**Comment by targhs** [comment]
> Not specifically, but there might be generic bounties like "update docs" or "do backports".
> 
> Currently a bit low on organisation funds for new bounties though ... :-(

Oh...i thought bounties would some kinda badges. No worries

**Comment by ThomasWaldmann** [comment]
With bounties, you can get some $$ for solving issues. See bountysource.com.
