### ISSUE TITLE
Archive stats differ between create and info commands

### ISSUE THREAD

**Issue by m1bcodes** [borgbackup/borg#6776]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Cound be a bug.

#### Your borg version (borg -V).
borg 1.2.1

#### Operating system (distribution) and version.
Cygwin:
$ uname -r
3.3.5-341.x86_64

#### Hardware / network configuration, and filesystems used.
Unknown

#### How much data is handled by borg?
< 10 kb

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create -p --log-json --stats --json "<repo-path>"::"Archive1" "<folder to back up>"
borg info --json --log-json "<repo-path>"::"Archive1"

```

## Describe the problem you're observing.

The stats section in the json output for both commands differ for the same archive. This is a behaviour, which must have been occured between borg version 1.1.7 and 1.2.1.

Here are the stats for some test files under 1.1.7, they are the same for the create and info commands:

```
            "stats": {
                "compressed_size": 1446,
                "deduplicated_size": 1446,
                "nfiles": 4,
                "original_size": 2699
            },
```
If I do the same thing with the same files under borg 1.2.1, I get the following stats for the create:

```
        "stats": {
            "compressed_size": 849,
            "deduplicated_size": 849,
            "nfiles": 4,
            "original_size": 765
        }
```
and this is the result of the info command:
```
            "stats": {
                "compressed_size": 192,
                "deduplicated_size": 1462,
                "nfiles": 4,
                "original_size": 20
            },

```

The total bytes of all files stored in the archive is indeed 20 bytes.
So how can the difference between 1.1.7 and 1.2.1 interpreted. And why are the sizes different for the create and info commands?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. Just create an archive and get the info for it.

**Comment by ThomasWaldmann** [comment]
It could be related to how borg computes some of these statistics, there have been quite some fixes and changes between these versions:
- in borg 1.1.x, some stats had fundamental issues if `.part` files were present (like created by in-file checkpointing)
- borg 1.2 writes new metadata to archives, like size and amount of files (and .part files)

In general, the compressed/encrypted/authenticated format has some overhead, which is noticeable esp. for small/uncompressible files.

**Comment by ThomasWaldmann** [comment]
BTW, if you really used 1.1.7, please read this:

https://borgbackup.readthedocs.io/en/stable/changes.html#pre-1-1-11-potential-index-corruption-data-loss-issue

**Comment by m1bcodes** [comment]
Thanks for the insight and the hint to the pre 1-1-11 issue.
