### ISSUE TITLE
Archive deduplicated size not summing up to "All archives" size

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [borgbackup/borg#6777]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG/QUESTION -- I suspect this is a user-error and not a borg-bug but not sure.

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
Arch Linux (rolling)

#### Hardware / network configuration, and filesystems used.
ThinkPad X1 Carbon, Ethernet with 500 Mbit/s down, 50 Mbit/s up, ext4

#### How much data is handled by borg?
Ca. 650 GB

_When I initially created the first the backup, I ran out of storage after 400 GB and had to upgrade my borgbase plan. After running the create command again with the same name, it continue from there. So I suspect this is messing up my stats but not sure how to fix it._

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`BORG_PASSPHRASE=$(cat secrets/borgbase/BORG_PASSPHRASE) borg info ...[edited].repo.borgbase.com:repo::smc_home_2022-06-03T14:03:22+01:00`

## Describe the problem you're observing.
The individual archive dedup sizes reported by `borg info` (<10GB) do not sum up to the all archives number (489.95 GB).
```
                       Original size      Compressed size    Deduplicated size
This archive:              632.47 GB            549.46 GB            350.25 MB
This archive:              633.67 GB            550.60 GB            469.99 MB
This archive:                1.98 GB              1.83 GB              3.36 MB
This archive:              642.65 GB            558.34 GB              8.19 GB
All archives:                1.91 TB              1.66 TB            489.95 GB

```
These numbers come from 4 archives (`borg list`):
```
smc_home_2022-06-03T14:03:22+01:00   Fri, 2022-06-03 17:29:30 [fingerprint removed]
smc_home_2022-06-05T13:12:50+01:00   Sun, 2022-06-05 13:12:52 [fingerprint removed]
smc_camHPC_2022-06-06T11:23:21+01:00 Mon, 2022-06-06 11:23:32 [fingerprint removed]
smc_home_2022-06-11T17:27:44+01:00   Sat, 2022-06-11 17:27:45 [fingerprint removed]
```
Using outputs of `borg info` for each of them
```
Archive name: smc_home_2022-06-03T14:03:22+01:00
Archive fingerprint: [fingerprint removed]
Comment: 
Hostname: smc
Username: stefan
Time (start): Fri, 2022-06-03 17:29:30
Time (end): Fri, 2022-06-03 18:18:52
Duration: 49 minutes 21.30 seconds
Number of files: 704964
Command line: /usr/bin/borg create [edited].repo.borgbase.com:repo::smc_home_2022-06-03T14:03:22+01:00 /home --progress --stats
Utilization of maximum supported archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:              632.47 GB            549.46 GB            350.25 MB
All archives:                1.91 TB              1.66 TB            489.95 GB

                       Unique chunks         Total chunks
Chunk index:                  786142              2839058
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I ran `borg check -v` before this, with no effects:
```
Remote: Starting repository check
Remote: finished segment check at segment 1082
Remote: Starting repository index check
Remote: Index object count match.
Remote: Finished full repository check, no problems found.
Starting archive consistency check...
Analyzing archive smc_home_2022-06-03T14:03:22+01:00 (1/4)
Analyzing archive smc_home_2022-06-05T13:12:50+01:00 (2/4)
Analyzing archive smc_camHPC_2022-06-06T11:23:21+01:00 (3/4)
Analyzing archive smc_home_2022-06-11T17:27:44+01:00 (4/4)
Archive consistency check complete, no problems found.
```

I also tried `borg prune --list --keep-daily 100 --prefix smc  --dry-run` and found there were *5* repositories, one named `smc_home_2022-06-03T14:03:22+01:00.snapshot` containing ~400 GB dedup size. I ran the prune operation without `--dry-run` to delete that one, but this has not affected the problem above.

**Comment by ThomasWaldmann** [comment]
That's normal.

An archives "deduplicated size" is the size of all unique chunks **only** referenced by this single archive.
This is the amount you would free by deleting this single archive only.

A lot of data is referenced by multiple archives, that is the amount you are missing by just summing up the deduped sizes.

**Comment by Stefan-Heimersheim** [comment]
Oh, I see! Is there a built-in way to see "how much data referenced by this archive" (without the only), or is this more complicated?

**Comment by ThomasWaldmann** [comment]
That's the column with the "compressed size".

**Comment by Stefan-Heimersheim** [comment]
That doesn't count deduplication of data within this archive though, does it?

**Comment by ThomasWaldmann** [comment]
IIRC we do not have a "how much space would deleting this set of archives free" yet. Not sure if that would be very practical though except if you already know when some unwanted files made your repo grow.

**Comment by ThomasWaldmann** [comment]
guess this is resolved.
