### ISSUE TITLE
Clam detects borg as possible virus / false positive as of 1.2.0

### ISSUE THREAD

**Issue by mzurborg-iquadrat** [borgbackup/borg#6783]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
1.2.1

#### Operating system (distribution) and version.
Ubuntu 20.04.4 LTS

#### Hardware / network configuration, and filesystems used.
AMD EPYC 8 Core 16 Threads

#### How much data is handled by borg?
60GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
clamscan /usr/local/bin/borg

## Describe the problem you're observing.

/usr/local/bin/borg: Unix.Dropper.Python-9950644-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 8619408
Engine version: 0.103.6
Scanned directories: 0
Scanned files: 1
Infected files: 1
Data scanned: 23.29 MB
Data read: 21.86 MB (ratio 1.07:1)
Time: 27.765 sec (0 m 27 s)
Start Date: 2022:06:21 13:37:26
End Date:   2022:06:21 13:37:53

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, eversince 1.2.0

## Temporary solution
echo -e "ExcludePath ^/usr/local/bin/borg" | sudo tee -a /etc/clamav/clamd.conf

**Comment by enkore** [comment]
Clamav has a form for reporting false positives here: http://www.clamav.net/reports/fp

**Comment by ThomasWaldmann** [comment]
@mzurborg-iquadrat that file, is that the pyinstaller-made fat borg binary you downloaded from github releases?

**Comment by ThomasWaldmann** [comment]
@mzurborg-iquadrat did you report to clamav? was the issue resolved?

**Comment by ThomasWaldmann** [comment]
Guess this was resolved.
