### ISSUE TITLE
macOS intel: borg benchmark cpu results wanted

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6801]
could someone with a intel mac please use borg 2.0.0a2 and the latest libdeflate from brew and run:
```
borg benchmark cpu
```

I need the crc32 results to decide whether we keep libdeflate for borg2.

**Comment by ThomasWaldmann** [comment]
For M1 mac and libdeflate 1.12:
```
Non-cryptographic checksums / hashes ===========================
crc32 (zlib, used)       1GB        0.034s
crc32 (libdeflate)       1GB        0.018s
xxh64                    1GB        0.071s
```

**Comment by ThomasWaldmann** [comment]
The point is:
- we only want to have external requirements / dependencies if there is a good reason for it.
- borg <= 1.2 does a ton of crc32 computation (repository code, crc32 computed over all data)
- but borg 2.0 has the new PUT2 format and only does crc32 computation over a few header bytes (per segment) and uses xxh64 for the vast amount of body data.
- borg 2.0's `borg transfer` is the last time a lot of crc32 needs to get computed (when reading from the old repo), but this is a one-time effort we could just ignore.

**Comment by ThomasWaldmann** [comment]
libdeflate 1.12 got some tuning for M1. but in general and especially for stable linux dists we can not assume to always have the latest and greatest version of a lib.

**Comment by accolon** [comment]
I ran the benchmark on a MacBook Pro (16 Zoll, 2019) with 2,6 GHz 6-Core Intel Core i7, using libdeflate 1.12 from Home-brew with borg 2.0.0a2.

No other applications were running. I executed the benchmark five times at got some the following values:

Non-cryptographic checksums / hashes ===========================
crc32 (zlib, used)  1GB  0.065s
crc32 (libdeflate)  1GB  0.050s
xxh64  1GB  0.085s

Non-cryptographic checksums / hashes ===========================
crc32 (zlib, used)  1GB  0.051s
crc32 (libdeflate)  1GB  0.044s
xxh64  1GB  0.074s

Non-cryptographic checksums / hashes ===========================
crc32 (zlib, used)  1GB  0.065s
crc32 (libdeflate)  1GB  0.055s
xxh64  1GB  0.076s

Non-cryptographic checksums / hashes ===========================
crc32 (zlib, used)  1GB  0.064s
crc32 (libdeflate)  1GB  0.052s
xxh64  1GB  0.081s

Non-cryptographic checksums / hashes ===========================
crc32 (zlib, used)  1GB  0.064s
crc32 (libdeflate)  1GB  0.048s
xxh64  1GB  0.088s

libdeflate is always faster, but compared to your M1 benchmark the difference is not that large on Intel.

**Comment by ThomasWaldmann** [comment]
OK, considering that borg2 will not compute crc32 over big amounts of data any more with its new repo format, I decided to remove `libdeflate` requirement and just always use `zlib.crc32`.

It's not `libdeflate`'s fault, the practical speed advantage of having it vs. the maintenance burden of having one more dependency is just not big enough any more (this was very different in the old repo format, but not any more).
