### ISSUE TITLE
Try to make borg 1.2.1 for unraid, but is not working.

### ISSUE THREAD

**Issue by GHTGXL** [borgbackup/borg#6812]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

 ISSUE

## System information. For client/server mode post info for both machines.
version 5.15.46-Unraid (6.10.3)

#### Your borg version (borg -V).
Can't show, make error
#### Operating system (distribution) and version.
version 5.15.46-Unraid (6.10.3)
#### Hardware / network configuration, and filesystems used.
XFS Array to XFS Unassigned Devices
#### How much data is handled by borg?
104GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
upgradepkg borgbackup-1.2.1-x86_64-1_SBo.txz

## Describe the problem you're observing.
Because borg in unraid nerdpack is 1.1.5, and I need 1.2.1 for borg compact, I try to follow https://github.com/dmacias72/unRAID-NerdPack/issues/66 to make myself, after some try, I make the 1.2.1 upgrade pack, try to install and use, and have this problem, I notice the pack size is much smaller that 1.1.5 from nerdpack, don't sure where is the problem.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Just install 1.2.1 pack by upgradepkg.
#### Include any warning/errors/backtraces from the system logs
```
 borg -v
Traceback (most recent call last):
  File "/usr/local/bin/borg", line 33, in <module>
    sys.exit(load_entry_point('borgbackup==1.2.1', 'console_scripts', 'borg')())
  File "/usr/local/bin/borg", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib64/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib64/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: borgbackup
```

[borgbackup 1.1.5 and 1.2.1.zip](https://github.com/borgbackup/borg/files/9011674/borgbackup.1.1.5.and.1.2.1.zip)

**Comment by SmartPhoneLover** [comment]
I'm also in unRAID (6.11.5). Just use the Borgmatic container. You can interact with borg directly if wanted, that's what I do from inside the container.
