### ISSUE TITLE
Clone and Update Repository

### ISSUE THREAD

**Issue by htho** [borgbackup/borg#683]
Is there a way to clone and update/sync a repository, since there is no [redundancy](http://borgbackup.readthedocs.org/en/stable/faq.html#can-project-name-add-redundancy-to-the-backup-data-to-deal-with-hardware-malfunction)?

My scenario: I create daily backups of my machine to a repository on another disk. Every once in a while, I want to copy this repository to yet another disk. Deleting the old copy and creating a new one on each backup-of-the-backup is a waste of time. It would be nice to have a clone/update function, that simply updates an existing clone of a repository.

**Comment by jungle-boogie** [comment]
So you would want borg to update an existing backup instead of using prune to delete it?

**Comment by htho** [comment]
No. I am not talking about copying single backups, but about copying a whole repository containing a set of previous backups. I want to copy the whole repository to another disk.

There must be something more efficient than:

```bash
$ rm -rf /mnt/backup_disk_fallback/backup_repo
$ cp -a /mnt/backup_disk/backup_repo /mnt/backup_disk_fallback/backup_repo
```
I thought about using rsync, but I am not sure if this is efficient since I don't know how much the blocks and names change.
```bash
$ rsync --archive --delete /mnt/backup_disk/backup_repo /mnt/backup_disk_fallback/backup_repo
```

**Comment by ThomasWaldmann** [comment]
See there:

http://borgbackup.readthedocs.org/en/latest/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

**Comment by htho** [comment]
I missed that one. I'm sorry for bothering you with this frequently asked question.

**Comment by ThomasWaldmann** [comment]
No problem, it is a relatively new entry and might be not visible in the stable docs you read.
