### ISSUE TITLE
--files-cache by path for faster import

### ISSUE THREAD

**Issue by rrueger** [borgbackup/borg#6835]
**Have you checked borgbackup docs, FAQ, and open Github issues?** Yes. 

**Is this a BUG / ISSUE report or a QUESTION?** Question

**borg version (borg -V):** borg 1.2.1

**Operating system (distribution) and version.** ArchLinux

## Describe the problem you're observing.

When importing snapshots from another application (btrfs, non-hardlinked rsync, ...), a lot of identical files need to be re-chunked.

Would it be possible to cache files based on (relative) path? That is, suppose we have existing snapshots

    snapshot01/file1
    snapshot01/file2
    snapshot01/...
    snapshot02/file1
    snapshot02/file3
    snapshot02/...

and we execute borg with

     cd <path to>/snapshot01 && borg create <options> --files-cache path . && cd -
     cd <path to>/snapshot02 && borg create <options> --files-cache path . && cd -

then borg would consider the file `snapshot02/file1` to be cached, since the `mtime, size, path` are equal (because the relative path of `snapshot01/file` and `snapshot02/file` is `./file1` in both archives).

In this use-case, I believe it is reasonable that if all three conditions are met, that the files really are identical.

My explicit example is: I have ~1000 btrfs snapshots of my home directory and I would like to import them. I think caching by path would make a lot of sense. 

Perhaps this is more appropriate for `borg-import`?

Conversely, I am not sure how many false-positive collisions one would get by just using `mtime, size`, but I thought that a cache-by-path might be a better-be-safe-than-sorry alternative to inode-caching especially when importing.

**Comment by ThomasWaldmann** [comment]
Yes, borg-import could be used / extended to be usable for this.

Also, if you just always mount your stuff so it ends up having an identical absolute path, the existing files cache mechanism would just work.

**Comment by rrueger** [comment]
> Also, if you just always mount your stuff so it ends up having an identical absolute path, the existing files cache mechanism would just work.

Of course!

For `btrfs` I can do this with `mount -o subvol=<SUBVOLUME NAME> <BTRFS ROOT> /mnt`.
For generic directories, [one can use](https://unix.stackexchange.com/a/198591) `mount --bind <SOURCE DIR>/<SNAPSHOT N> /mnt`.

In both cases, one would need to use

    cd /mnt && borg create <OPTIONS> --files-cache ctime,size <BORG ROOT>::<BORG SNAPSHOT NAME> .

Of course it already says this in the docs, I didn't see it. Leaving it here for anyone else.

> The mount points of filesystems or filesystem snapshots should be the same for every creation of a new archive to ensure fast operation. This is because the file cache that is used to determine changed files quickly uses absolute filenames. If this is not possible, consider creating a bind mount to a stable location.

This also highlights that the aforementioned "cache by path" is already done by borg.

Thank you
