### ISSUE TITLE
The compability disclaimer.

### ISSUE THREAD

**Issue by htho** [borgbackup/borg#684]
In a [section about the differences between attic and borg](http://borgbackup.readthedocs.org/en/stable/index.html#differences-between-attic-and-borg), there is this disclaimer-like text:

> BORG IS NOT COMPATIBLE WITH ORIGINAL ATTIC (but there is a one-way conversion).
> 
> EXPECT THAT WE WILL BREAK COMPATIBILITY REPEATEDLY WHEN MAJOR RELEASE NUMBER CHANGES (like when going from 0.x.y to 1.0.0).
> 
> NOT RELEASED DEVELOPMENT VERSIONS HAVE UNKNOWN COMPATIBILITY PROPERTIES.
> 
> THIS IS SOFTWARE IN DEVELOPMENT, DECIDE YOURSELF WHETHER IT FITS YOUR NEEDS.

Since I am not a native speaker, I wonder if the second sentence (or is it a paragraph) applies to the compatibility to attic or, to older borg versions. In other words: Do I have to worry, that using future releases, I won't be able to extract backups from repositories I create today?

Best Regards
htho

**Comment by jungle-boogie** [comment]
I'm sure you're a native speaker, just not a native English speaker. ;)

That is how I read the sentence, too. 

Also read this:
https://github.com/borgbackup/borg/blob/1.0.0rc1/docs/changes.rst

**Comment by ThomasWaldmann** [comment]
While we try to stay compatible or provide a converter for your repo, there is no guarantee on that.
If bigger, incompatible changes are required to improve the software, we will do them.

You can always keep an old version, in source code and/or as binary, so there is no real problem with that.
