### ISSUE TITLE
Can I selectively delete within old archives?

### ISSUE THREAD

**Issue by georgjaehnig** [borgbackup/borg#686]
Hi,

I've heard about Borg Backup via the 32C3 Lightning Talk which got me pretty interested. I'm still thinking if I want to use it, and there is one specific use case where I wonder if it's possible with Borg Backup.

(I hope this is the right place for the question, if not, simply tell me where to ask.)

So let's say I have the following data which I have already backupped with Borg Backup:

	/my_wedding_photos
	/my_drunk_photos

A day later, I decide that:

- I don't want `/my_wedding_photos` on my working disk anymore (as they take too much space) – **but I still want them in my backup**.
- I don't want `/my_drunk_photos` on my working disk anymore – **and I also don't want them in my backups** (they shall be completely forgotten).

Is there any workflow with Borg Backup that allows me to achieve this?

(I know about `prune` for instance but I still can't imagine an according workflow with it: `prune` does delete based on archive time, not based on content.)

The only "solution" that comes up for me is: Constantly keeping all the files I want in my backups also on my working disk all the time. But maybe there is more?

Cheers!

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/31079745-can-i-selectively-delete-within-old-archives)

**Comment by ThomasWaldmann** [comment]
There is no function yet to remove some specific files or dirs from all your backup archives, but this is already the topic of another issue.

About having stuff in your backup, but not on your working disk: you can do that, but of course you must be careful not to delete/prune the backup then. Also you risk losing the stuff in case you have it only on 1 backup disk and the backup disk dies.

Having the stuff that is important to you on your working disk and creating a good backup of this is definitely the easiest approach of managing your data. If you do it more complicated, I'ld say have stuff at least on 2 different media and check them regularly.

**Comment by jdchristensen** [comment]
If you are backing up data sets that you think might have different pruning strategies in the future, I would recommend putting each set of data into a different archive or even a different repository.  For example, I back up /home into one repo, all system files into another, and photos into a third.  I more aggressively prune the system repo.

**Comment by tgharold** [comment]
As you mentioned, an alternate work-around uses the ```--prefix``` operator along with an archive naming scheme to keep track of which category or user a particular backup belongs to and prune them out at different rates.

(The downside of doing multiple users to the same repository in a borg "push" system is that all users with read access to the repo can read all the files, no matter who they belong to.  But for a single-user system or family, without that concern it can work well.)

The way to leverage the --prefix is to be consistent when naming your archives.  So backups of system files might get a 'system' prefix, backups of photos might get a 'photos' prefix, backups of the home directory might get a 'home' prefix.  That will give you the ability to prune photo backups differently then system file backups.

My current user-level borg backup wrapper (called "borg-snapshots") looks like the following, it either defaults the prefix to ```snapshot-${USER}-(date/time)``` or will take a single command-line argument which then results in a prefix that looks like (```ManualPrefixLabel-${USER}-(date/time)```).  In the crontab table, I call it as ```borg-snapshots daily``` for the daily automated backup which makes the archive name for daily backups look like ```daily-${USER}-(date/time)```.  I could also setup a crontab entry that does hourly backups with ```hourly-${USER}-(date/time)```.

It's a toss-up whether you do "label-${USER}" or "${USER}-label".  The former makes it possible to prune by category across multiple users, the latter only lets you prune within a specific user's categories.

So I can also use that script argument to do one-time backups of files that I might not want to keep around long-term (example ```borg-snapshots ManualBackupOfClientXFiles```).  And easily get rid of it later with ```borg prune --prefix ManualBackupOfClientXFiles --keep-within 1d <path-to-repo>```, as long as that prefix is unique and doesn't clash with other backup archives that I want to keep.

It's really nice that ```borg list``` now supports the --prefix argument, so you can see which archives in the repo match.  Plus there's the --dry-run argument for test drives.

```bash
#!/bin/bash

# exit immediately on errors
set -e
# error out if uninitialized variable is used
set -u

# borg init --encryption none file:///mnt/path/to/backups/USERNAME/borg

REPOPATH=file:///mnt/path/to/backups/${USER}/borg
PREFIXNAME=snapshot-${USER}
if [ $# -ge 1 ]; then
  PREFIXNAME=${1}-${USER}
fi
ARCHIVENAME=${PREFIXNAME}
ARCHIVENAME+="-"$(date +'%Y%m%d-%H%M')

echo "Creating: ${REPOPATH}::${ARCHIVENAME}"
borg create --progress --stats --compression lzma \
  -e /home/${USER}/.cache \
  -e /home/${USER}/Downloads \
  -e /home/${USER}/Videos \
  ${REPOPATH}::${ARCHIVENAME} \
  /home/${USER}

borg check --archives-only --prefix ${PREFIXNAME} --last 5 ${REPOPATH}
```

Notes: 

- This script writes out to a different borg repo based on the ${USER} variable.  
- I don't do encryption when initializing the repo (I use LUKS encryption).
- It doesn't check the return code of "borg create" (uses "set -e" instead).
- LZMA compression is really slow, use lzr (fast) or zlib (medium speed) if that's a concern.
- There might be bugs or other oddities.

**Comment by DrupaListo-com** [comment]
borg rewrite! Wow! Backing this one with 10$. Way to go Enkore!

**Comment by enkore** [comment]
"borg recreate" (#812) is now merged into master and allows this (among other things).

**Comment by DrupaListo-com** [comment]
1. How exactly can I remove /home/user/tmp123 from all borg-backup archives in a repo located under /media/disk/repo22 ? @enkore Give me an example. Thanks a ton.
2. When will recreate be available in borg? In which version?

**Comment by enkore** [comment]
It's in master, the next release from master will be 1.1.

The docs give a few examples: http://borgbackup.readthedocs.org/en/latest/usage.html#borg-recreate

Your use case is included there:

``` console
# Remove unwanted files from all archives in a repository
$ borg recreate /mnt/backup -e /home/icke/Pictures/drunk_photos
```

**Comment by DrupaListo-com** [comment]
thanks!

**Comment by DrupaListo-com** [comment]
Who else thinks that it would be a lot more intuitive to have a dedicated borg command for retroactive delete of files/folders - sth like delete-retroactively, rewrite-history, delete-wrongly-added ?

It just seems wrong to me to have a command called "recreate" for deleting unwanted data, especially when the syntax is :
$ borg recreate /mnt/backup -e /home/icke/Pictures/drunk_photos

where the folder drunk_photos is actually given as arg to the --exclude options...

Opinions for pros/cons of adding some syntactic sugar to borg via a separate command for this sub-case of recreate?

We can't afford to bloat borg with lots of synt. sugar, but I strongly suppose that this feature of delete-from-all-backups / delete-retro / delete-retroactively WILL be used very frequently...

PS. If we decide no such command will be added - can we AT LEAST add a prominent FAQ entry about : "How do I delete unwanted files/folders from backups?" - where we give that recreate example one more appearance in the answer.

PS 2: There is also the https://github.com/borgbackup/community - where we might put such synt. sugar helpers that have no place in borg. I have and use a home-grown unreleased wrapper package for borg that has lots of such shortcuts and someday soon will release to borg-community...

**Comment by tgharold** [comment]
Well, the new recreate command allows borg to do a lot more things then just delete unwanted data in an archive.  It also allows changing chunker/compression settings.  So it was a very good addition to the borg commands.

But I'm not completely opposed to having a syntactic sugar command for delete.  Your community script would just silently change "recreate" to "delete" and then add in "-e" before any paths after the archive name.  Even then, I'm not sure I'd do more then make "delete" an alias for "recreate".  The syntax would then read:

```bash
$ borg delete /mnt/backup -e /home/icke/Pictures/drunk_photos
```

Which to me reads fairly cleanly already.

FAQ/help page updates would probably help more then the syntactic sugar.

**Comment by ThomasWaldmann** [comment]
There's a semantic/logical problem with this: -e is usually exclude. And if you exclude something from "delete", it would mean it is not deleted.

**Comment by DrupaListo-com** [comment]
I forgot to mention that borg delete and borg prune ARE ALREADY TAKEN and cant be used for my proposal above.

delete - Delete an existing repository or archive - this deletes whole repo/archive
prune - Prune repository archives according to specified rules - this is for deleting old archives that are too old for us to keep

Maybe "recreate REPO_OR_ARCHIVE -e DIR" can be added as an option to "delete"?
Sth like:
borg delete --delete-from-backups DIR REPO_OR_ARCHIVE

which will be a shortcut to: 
recreate REPO_OR_ARCHIVE -e DIR

??

I think most people will try looking for retroactive deleting of files under borg delete's docs ... and in the FAQ and/or feature list.

**Comment by DrupaListo-com** [comment]
"There's a semantic/logical problem with this: -e is usually exclude. And if you exclude something from "delete", it would mean it is not deleted."
^this. The very reason I am proposing sth easier to remember and harder to get lost with than "recreate -e DIR" ...

**Comment by enkore** [comment]
I don't really see the need (deleting stuff retroactively should be *rare*, but sometimes necessary), but the only semantically valid shortcut I see would be

   borg delete repo::archive [path…]

**Comment by DrupaListo-com** [comment]
so its +1 from @enkore for using borg delete with a switch-option  like --delete-everywhere-in-backup or ---delete-dir-from-all-archives

OR

just enkore's: 
borg delete repo::archive [path…]

which I like very much.

**Comment by Ape** [comment]
I think it would be better to leave `borg delete` alone and use some other command for this feature.

**Comment by enkore** [comment]
> so its +1 from @enkore for using borg delete with a switch-option like --delete-everywhere-in-backup or ---delete-dir-from-all-archives

No, I have no particular opinion whether this should be added or not -- with a slight bias to "no", because this should be an unusual operation that should be done "consciously". What I wrote above is that *if* a shortcut *should* be added, how it should look like.

**Comment by DrupaListo-com** [comment]
As long as there IS some way to do it + has good docs/examples/FAQ-section / easily findable via google - it's fine!

Any ideas when will 1.1 be released?

**Comment by enkore** [comment]
When it's done, mature and stable.

**Comment by fullofcaffeine** [comment]
Is `recreate` stable at the moment? I'm considering using it to delete some big files from a 500GB archive. Also, as a related question: does anyone know if this would work over s3fs (I don't currently have this repo locally).
