### ISSUE TITLE
Why installing from source doesn't build the last version?

### ISSUE THREAD

**Issue by Stopi** [borgbackup/borg#6873]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

It's more of a QUESTION

#### Your borg version (borg -V).
borg 1.1.18

#### Operating system (distribution) and version.
AlmaLinux - 8.6 (Sky Tiger) / up to date.

#### Hardware / network configuration, and filesystems used.
XFS

#### How much data is handled by borg?
None yet.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg -V

## Describe the problem you're observing.
I just installed borg from source (with pip) following the documentation (https://borgbackup.readthedocs.io/en/stable/installation.html#from-source).
I end up with a borg version 1.1.18 but I expected v1.2.1 (aka the last version).

This is a redhat-like distro so I've followed intructions for fedora:
```
dnf install python3 python3-devel python3-pip python3-virtualenv libacl-devel libacl openssl-devel lz4-devel libzstd-devel xxhash-devel pkgconf python3-pkgconfig fuse3-devel fuse3
dnf install gcc gcc-c++ redhat-rpm-config

virtualenv --python=python3 borg-env
source borg-env/bin/activate

pip install -U pip setuptools wheel
pip install pkgconfig
pip install borgbackup[pyfuse3]
```
The last command ended up pretty fast, without error.
I now have a borg binary but it's not at last version.

I build from source because the distro package manager only offers v1.1.17.
This is a server but I intend to use it as a client for backups to another server using debian.

Last week I configured 2 other machines (a server and a client) both on debian using pretty much the same commands:
```
apt install python3-pip python3-virtualenv pkg-config libssl-dev liblz4-dev libzstd-dev libxxhash-dev libfuse3-dev fuse3 libacl1-dev

virtualenv --python=python3 borg-env
source borg-env/bin/activate

pip install -U pip setuptools wheel
pip install pkgconfig
pip install borgbackup[pyfuse3]
```
This gave me a borg binary in version 1.2.1 which is the correct version I'm expecting.

What am I missing here?

Could this be related to the kernel version?
On Almalinux, I got 4.18.0-372.16.1.el8_6.x86_64.
On Debian it's 5.10.0-15-marvell.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I think I've said it all.

#### Include any warning/errors/backtraces from the system logs
WARNING: borgbackup 1.1.18 does not provide the extra 'pyfuse3'

**Comment by Stopi** [comment]
Well, upgrading the kernel to version 5.18.12-1.el8.elrepo.x86_64 did not solve the issue.

**Comment by ThomasWaldmann** [comment]
pip tells you what it installed, just read its output. you can also try `pip install -U borgbackup`.

another issue might be the `PATH`. using `which borg` you can find the absolute path of what it will execute and check whether that is the expected/desired path or whether you need to adjust `PATH`.

**Comment by Stopi** [comment]
Thanks for your answer.
I still don't see where is the problem nor how the pip output can help me here.

Please, find here a the full output for the commands I've run:
```
 /opt/borgbackup $ virtualenv --python=python3 borg-env
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /opt/borgbackup/borg-env/bin/python3
Also creating executable in /opt/borgbackup/borg-env/bin/python
Installing setuptools, pip, wheel...done.

 /opt/borgbackup $ source borg-env/bin/activate

(borg-env)  /opt/borgbackup $ pip install -U pip setuptools wheel
Requirement already satisfied: pip in ./borg-env/lib/python3.6/site-packages (21.3.1)
Requirement already satisfied: setuptools in ./borg-env/lib/python3.6/site-packages (59.6.0)
Requirement already satisfied: wheel in ./borg-env/lib/python3.6/site-packages (0.37.1)

(borg-env)  /opt/borgbackup $ pip install pkgconfig
Collecting pkgconfig
  Using cached pkgconfig-1.5.5-py3-none-any.whl (6.7 kB)
Installing collected packages: pkgconfig
Successfully installed pkgconfig-1.5.5

(borg-env)  /opt/borgbackup $ pip install borgbackup[pyfuse3]
Collecting borgbackup[pyfuse3]
  Using cached borgbackup-1.1.18-cp36-cp36m-linux_x86_64.whl
WARNING: borgbackup 1.1.18 does not provide the extra 'pyfuse3'
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Installing collected packages: pyparsing, packaging, borgbackup
Successfully installed borgbackup-1.1.18 packaging-21.3 pyparsing-3.0.9
```
Also:
```
(borg-env)  /opt/borgbackup $ pip install -U borgbackup
Requirement already satisfied: borgbackup in ./borg-env/lib/python3.6/site-packages (1.1.18)
Requirement already satisfied: packaging in ./borg-env/lib/python3.6/site-packages (from borgbackup) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./borg-env/lib/python3.6/site-packages (from packaging->borgbackup) (3.0.9)
```

**Comment by Stopi** [comment]
And:
```
(borg-env)  /opt/borgbackup $ which borg
/opt/borgbackup/borg-env/bin/borg
```

**Comment by Stopi** [comment]
I just found more info in the github release page (https://github.com/borgbackup/borg/releases/tag/1.2.1).
I'm told to use:
```
pip install pkgconfig ; pip install "borgbackup==1.2.1"
```
But when I try, here is the output:
```
(borg-env)  /opt/borgbackup $ pip install "borgbackup[pyfuse3]==1.2.1"
ERROR: Could not find a version that satisfies the requirement borgbackup[pyfuse3]==1.2.1 (from versions: 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.26.1, 0.27.0, 0.28.0, 0.28.1, 0.28.2, 0.29.0, 0.30.0, 0.30.1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6rc1, 1.0.6, 1.0.7rc1, 1.0.7rc2, 1.0.7, 1.0.8rc1, 1.0.8, 1.0.9rc1, 1.0.9, 1.0.10rc1, 1.0.10, 1.0.11rc1, 1.0.11, 1.0.12, 1.0.13, 1.1.0b1, 1.1.0b2, 1.1.0b3, 1.1.0b4, 1.1.0b5, 1.1.0b6, 1.1.0rc1, 1.1.0rc2, 1.1.0rc3, 1.1.0rc4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.2.0a2, 1.2.0a3, 1.2.0a4, 1.2.0a5, 1.2.0a6, 1.2.0a7, 1.2.0a8, 1.2.0a9, 1.2.0b1, 1.2.0b2, 1.2.0b3)
ERROR: No matching distribution found for borgbackup[pyfuse3]==1.2.1
```

**Comment by ThomasWaldmann** [comment]
use pip uninstall first and the retry install with -U.

**Comment by Stopi** [comment]
I'm sorry but the syntax I've tried is the only one that doesn't produce an error.
```
(borg-env)  /opt/borgbackup $ pip install "borgbackup==1.2.1[pyfuse3]"
ERROR: Extras after version '==1.2.1[pyfuse3]'.
```
Anyway, I have the exact same result even using only:
```
pip install "borgbackup==1.2.1"
```

i've also tried your recommendation:
```
(borg-env)  /opt/borgbackup $ pip uninstall borgbackup
Found existing installation: borgbackup 1.1.18
Uninstalling borgbackup-1.1.18:
  Would remove:
    /opt/borgbackup/borg-env/bin/borg
    /opt/borgbackup/borg-env/bin/borgfs
    /opt/borgbackup/borg-env/lib/python3.6/site-packages/borg/*
    /opt/borgbackup/borg-env/lib/python3.6/site-packages/borgbackup-1.1.18.dist-info/*
Proceed (Y/n)? 
  Successfully uninstalled borgbackup-1.1.18

(borg-env)  /opt/borgbackup $ pip install -U borgbackup[pyfuse3]
Collecting borgbackup[pyfuse3]
  Using cached borgbackup-1.1.18-cp36-cp36m-linux_x86_64.whl
WARNING: borgbackup 1.1.18 does not provide the extra 'pyfuse3'
Requirement already satisfied: packaging in ./borg-env/lib/python3.6/site-packages (from borgbackup[pyfuse3]) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./borg-env/lib/python3.6/site-packages (from packaging->borgbackup[pyfuse3]) (3.0.9)
Installing collected packages: borgbackup
Successfully installed borgbackup-1.1.18
```
I think this will not work because for some reason version 1.2.1 is not in the list I get from the error message:
```
ERROR: Could not find a version that satisfies the requirement borgbackup==1.2.1 (from versions: 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.26.1, 0.27.0, 0.28.0, 0.28.1, 0.28.2, 0.29.0, 0.30.0, 0.30.1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6rc1, 1.0.6, 1.0.7rc1, 1.0.7rc2, 1.0.7, 1.0.8rc1, 1.0.8, 1.0.9rc1, 1.0.9, 1.0.10rc1, 1.0.10, 1.0.11rc1, 1.0.11, 1.0.12, 1.0.13, 1.1.0b1, 1.1.0b2, 1.1.0b3, 1.1.0b4, 1.1.0b5, 1.1.0b6, 1.1.0rc1, 1.1.0rc2, 1.1.0rc3, 1.1.0rc4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18, 1.2.0a2, 1.2.0a3, 1.2.0a4, 1.2.0a5, 1.2.0a6, 1.2.0a7, 1.2.0a8, 1.2.0a9, 1.2.0b1, 1.2.0b2, 1.2.0b3)
```

**Comment by Stopi** [comment]
I'm not a python dev, so I'm not sure exactly where pip goes to find the list of available versions and how it knows which one is stable.
If you know how, can you have a look there?

**Comment by ThomasWaldmann** [comment]
https://pypi.org/project/borgbackup/

https://pypi.org/project/borgbackup/#history

maybe you use some other index / a cache / a proxy?

**Comment by ThomasWaldmann** [comment]
ehrm, no, it is likely your python version. if you use python 3.6, borg 1.1.18 is the latest version supporting that.

for 1.2.x you need at least python 3.8.

**Comment by ThomasWaldmann** [comment]
(but if your system is that old, nothing speaks against just using the very stable 1.1.18 on it)

**Comment by Stopi** [comment]
OK, thank you for your help, so the issue would be the python version.
```
(borg-env)  /opt/borgbackup $ python --version
Python 3.6.8
```
Indeed I'm using v3.6.

The system isn't old, it's the very last version of AlmaLinux which is fairly recent.
I will try to see if I can upgrade my python version.

Any how I will report here the result.

Thanks again for your quick and helpful answers.

**Comment by ThomasWaldmann** [comment]
if you upgrade, use python 3.9 or 3.10 or 3.8, in that order.

**Comment by Stopi** [comment]
```
virtualenv --python=python3.9 borg-env
```
solved the version issue, now pip tries to install borgbackup-1.2.1, thanks.
