### ISSUE TITLE
_version.py format change

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6875]
there seems to be a problem in debian or ubuntu because the file format changed slightly between setuptools_scm 6.4.2 (what I used) and 7.x (what they use), so a file changes unexpectedly.

guess i'll just release borg 1.2.2 using the 7.x version.

**Comment by LocutusOfBorg** [comment]
TEMPLATES is the way to go?

**Comment by ThomasWaldmann** [comment]
Fixed, see PRs above.
