### ISSUE TITLE
borg treats all files in davfs2 as modified

### ISSUE THREAD

**Issue by GrayXu** [borgbackup/borg#6883]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG, but maybe outside of borg

## System information. For client/server mode post info for both machines.

borg 1.2.0  
Ubuntu 21
davfs2 + [haiwen/seafdav](https://github.com/haiwen/seafdav) for seafile

```
borg create                         \
        --verbose                       \
        --filter AME                    \
        --list                          \
        --stats                         \
        --show-rc                       \
        --compression lzma               \
        --exclude-caches                \
       /path/...
```

## Describe the problem you're observing.

I tried to use borg to backup files from a davfs2(webdav) mounted filesystem.  
Most of files are unchanged (time and size), but borg keep telling me that all files are modified (`M /path/...`).  
As a result, it is causing more time than expected.

Is there any way to avoid this? Thanks!

**Comment by ThomasWaldmann** [comment]
Try giving `--files-cache=ctime,size`. Only if that doesn't work either, give `--files-cache=mtime,size`.

You need to run **two** backups and look at the output of the 2nd one to confirm whether it is working.

**Comment by GrayXu** [comment]
thanks!

**Comment by GrayXu** [comment]
update: I'm sure the problem is caused by the webdav servers
