### ISSUE TITLE
Documentation: "Edit on GitHub" link broken

### ISSUE THREAD

**Issue by dannyedel** [borgbackup/borg#689]
In the online documentation, the "Edit on GitHub" (top right corner) link appears to be broken.

Example link:

https://borgbackup.readthedocs.org/en/stable/installation.html refers to https://github.com/borgbackup/borg/blob/ec547402300e53728fb53bc20732049e63ef29c3/docs/installation.rst which is 404.

On my local clone, this is the sha *of the gpg-signed tag object*, not of the underlying commit, which is cd6044e85ca45929b02a080f7982841187367e4f.

The `latest` branch does not have this issue (it hardcodes "master" into the pathname).

**Possible fix**: If I use the tag's name instead of the sha, the link works as intended:

https://github.com/borgbackup/borg/blob/0.30.1/docs/installation.rst

If it's not possible to change the link target, then maybe disable the link on release builds, a 404 helps nobody to contribute.

**Comment by ThomasWaldmann** [comment]
The problem is known, but IIRC this is part of the readthedocs theme, not of our content/code.

IIRC, we already have (had?) a ticket about it here, but it should be rather filed against readthedocs project.
