### ISSUE TITLE
How exclude file types (jpg, gz and etc) from compression ? Is it possible ?

### ISSUE THREAD

**Issue by yiiness** [borgbackup/borg#6898]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
1.1.16 or other(if it feature presents)
#### Operating system (distribution) and version.
(debian 11.2(x64) - borgbackup from standart repo)
#### How much data is handled by borg?
2TB

**Comment by ThomasWaldmann** [comment]
No, there is not.

But:
- some compression algorithms might do better some worse when trying to compress already compressed data, just try it
- there is `--compression=auto,...` which first invokes lz4 to test compressibility and only if it is compressible, invokes the more expensive compression algorithm given by `...`.
