### ISSUE TITLE
precompiled borg binaries on qnap NAS

### ISSUE THREAD

**Issue by copart** [borgbackup/borg#690]
Hi,

I have a qnap NAS (x86_64 arch) that I am trying to get borg working with.  At this point I am unable to get multiple python packages to compile (the device uses a toolset from the openwrt project for customer stuff).  Hence, trying to precompiled option.

Anyway, I have Attic v0.14 working on the qnap using a precompiled binary.  This works perfectly.  I attempted to use borg-linux64 and the executable segfaults on run.  Should it work?  

Anybody else get Python3, numpy, and other packages working on a qnap using Entware-ng for gcc and qpkg for Python 3?

**Comment by ThomasWaldmann** [comment]
Please check what glibc version you have on the NAS device.

If it is much older than the one used to build the binary, the crash is likely due to that (see the docs / binary README).

**Comment by copart** [comment]
Thanks for replying.  It appears the the Qnap has a recent glibc, at 2.22.  Same as my fedora install.

# LD_LIBRARY_PATH=/opt/lib ./getglibcver 
2.22
# ldd --version | grep ldd
ldd (GNU libc) 2.22
# LD_LIBRARY_PATH=/opt/lib ./borg-linux64
Segmentation fault
# LD_LIBRARY_PATH=/opt/lib TEMP=/share/dir ./borg-linux64
Segmentation fault

I tried to move where it extracted as another try.

**Comment by ThomasWaldmann** [comment]
Why are you tweaking LD_LIBRARY_PATH?

pyinstaller does also tweak LD_LIBRARY_PATH, so all the bundled libs get loaded from the directory where the stuff gets unpacked.

**Comment by copart** [comment]
hi, the Qnap has its own built in libraries that I believe conflict if you do not tweak LD_LIBRARY_PATH.  If I do not export LD_LIBRARY_PATH or set on cmdline, it loads the built in and not the ones in the /opt directories.

For example:

# TEMP=/share/dir ./borg-linux64
./borg-linux64: error while loading shared libraries: libdl.so.2: wrong ELF class: ELFCLASS32

Just to confirm that 32 bit does not work either as the above kind of hints at architecture mismatch
# TEMP=/share/dir ./borg-linux32
Error loading Python lib '/share/dir/_MEIWLgWaV/libpython3.5m.so.1.0': /lib/libc.so.6: version `GLIBC_2.7' not found (required by /share/dir/_MEIWLgWaV/libpython3.5m.so.1.0)

**Comment by manwegit** [comment]
I'd also like to get borg working on Qnap, but atm I'm running stuff with nfs mounts from Qnap.
Default libs are old and most likely will not be updated for the foreseeable future. Let me know if you can get it to work.

**Comment by manwegit** [comment]
@copart Progessing on Qnap build, but I'm missing some dev headers and libs. I'll try to get some progress on this next week. 
BUT I'm not sure, will I create standalone bin. Steps to build on Qnap borg is my first priority.

**Comment by copart** [comment]
I wish I could figure out how to install Python3 libraries that require compilation.  They all seem to fail even with the headers available from Entware-ng downloaded and proper env setup.

**Comment by nepet** [comment]
Hi there,
have you made any progress on the issue by now?

**Comment by copart** [comment]
@nepet 
Not yet, however. have not tried in the last week.  Please let us know if you find out.

**Comment by manwegit** [comment]
Sorry, busy. looks like I'll be busy this week also, so nothing new (most likely) this week from me.

**Comment by Saw-Head** [comment]
Hey heros,
I love BorgBackup and I am using it on one of my Linux servers (Debian). Absolutely great!
Now I would like to use it on my (old) QNAP NAS TS-210 too.

I tried the original precompiled binaries, but I didn't succeed (cannot execute binary file), guess this is because of the ARM based hardware/software.
I googled a lot but I couldn't find a package that comes without the need of compilation.

Has anyone of you found a solution for this or can someone give me a hint how I could do this?

Cheers,
Saw

**Comment by copart** [comment]
I got it to work, however, I have a QNAP with an ATOM cpu, so YMMV with ARM.  I had to BUILD my own Python since the Python3 offered in qpkg is Python i686 which added complexity with regards to CPYTHON.

1.  Install Entware-ng, I forget all the packages I installed, but you obviously need gcc and more
2.  Download headers, set environment
https://github.com/Entware-ng/Entware-ng/wiki/Using-gcc-%28native-compilation%29,
3. Download and install lz4.  Make sure headers are in /opt/include and library is in /opt/lib.  Get from https://github.com/Cyan4973/lz4
4.  Download and BUILD Python, in order for some of the default modules to install I needed to do
ln -s /opt/lib/libgdbm.so.4.0.0 /opt/lib/libgdbm.so
ln -s /opt/lib/libssl.so.1.0.0 /opt/lib/libssl.so
ln -s /opt/lib/libsqlite3.so.0.8.6 /opt/lib/libsqlite3.so
ln -s /opt/lib/libbz2.so.1.0.6 /opt/lib/libbz2.so
5.  /opt/bin/pip3.5 install borgbackup
6.  BACKUP

Footnote: I did make some changes to Modules/Setup, however, I think that can be avoided as long as you do the ln -s in step 4.

**Comment by copart** [comment]
for completeness, I updated my borg install to 1.0.6.  I had to do the following:

export BORG_LZ4_PREFIX=/opt
export BORG_OPENSSL_PREFIX=/opt/include

**Comment by ThomasWaldmann** [comment]
@copart you are sure about /opt/include? what is the full path of openssl/evp.h?

**Comment by copart** [comment]
@ThomasWaldmann 

[~] # ls -la /opt/include/openssl/evp.h 
-rw-r--r--    1 admin    administ     67798 Jun 17 19:55 /opt/include/openssl/evp.h

**Comment by ThomasWaldmann** [comment]
I'ld say the openssl prefix is /opt then.

**Comment by ThomasWaldmann** [comment]
no reply, closing.

**Comment by azazel75** [comment]
i think i'll try borg inside a debian/ubuntu docker container... my qnap can run them, it seems much simpler

**Comment by demure** [comment]
For future people that try to do this on QNAP, the app "Container Station" is the effective solution, using an OS of your choice. You may however face issues with the port forwarding, and have to dive into the QNAP filesystem to manually fix. [QNAP Forum post on fix](https://forum.qnap.com/viewtopic.php?t=115258#p596749) 

I will edit this with a link to my blog post when I'm finished writing it, in case the QNAP forum has issues.

**Comment by quicktrick** [comment]
Hello!  A lot of thanks to @copart  and  @ThomasWaldmann !  I was able to install `borgbackup` on Qnap TS-459 Pro (`Linux TS-459 3.4.6 #1 SMP Fri Dec 8 01:32:36 CST 2017 x86_64 GNU/Linux`).  I installed `Entware-3x`, followed the steps in @copart 's instruction except I installed `python3` from Entware's repository.  But I wasn't able to install FUSE support.  Here are my logs:

    root@TS-459:/share/MD0_DATA/.qpkg/Entware-3x# pip3.6 install borgbackup
    Collecting borgbackup
      Using cached borgbackup-1.1.4.tar.gz
    Requirement already satisfied: msgpack-python>=0.4.6 in ./lib/python3.6/site-packages (from borgbackup)
    Building wheels for collected packages: borgbackup
      Running setup.py bdist_wheel for borgbackup ... done
      Stored in directory: /opt/root/.cache/pip/wheels/9d/85/82/0b24ab0df228e284a03eb02986cc407de283cd175172175cae
    Successfully built borgbackup
    Installing collected packages: borgbackup
    Successfully installed borgbackup-1.1.4
    
    root@TS-459:/share/MD0_DATA/.qpkg/Entware-3x# pip3.6 install borgbackup[fuse]
    Requirement already satisfied: borgbackup[fuse] in ./lib/python3.6/site-packages
    Requirement already satisfied: msgpack-python>=0.4.6 in ./lib/python3.6/site-packages (from borgbackup[fuse])
    Collecting llfuse<2.0; extra == "fuse" (from borgbackup[fuse])
      Using cached llfuse-1.3.2.tar.bz2
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/share/MD0_DATA/.qpkg/Entware-3x/tmp/pip-build-n4dfhnoy/llfuse/setup.py", line 283, in <module>
            main()
          File "/share/MD0_DATA/.qpkg/Entware-3x/tmp/pip-build-n4dfhnoy/llfuse/setup.py", line 76, in main
            compile_args = pkg_config('fuse', cflags=True, ldflags=False, min_ver='2.8.0')
          File "/share/MD0_DATA/.qpkg/Entware-3x/tmp/pip-build-n4dfhnoy/llfuse/setup.py", line 175, in pkg_config
            if subprocess.call(cmd) != 0:
          File "/subprocess.py", line 267, in call
          File "/subprocess.py", line 707, in __init__
          File "/subprocess.py", line 1333, in _execute_child
        FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /share/MD0_DATA/.qpkg/Entware-3x/tmp/pip-build-n4dfhnoy/llfuse/

What may be the problem with Fuse?

BTW, I was not able to install `borg-env` too:

    root@TS-459:/share/MD0_DATA/.qpkg/Entware-3x# virtualenv --python=python3 borg-env
    Running virtualenv with interpreter /opt/bin/python3
    Using base prefix '/opt'
    New python executable in /share/MD0_DATA/.qpkg/Entware-3x/borg-env/bin/python3
    Also creating executable in /share/MD0_DATA/.qpkg/Entware-3x/borg-env/bin/python
    Installing setuptools, pip, wheel...
      Complete output from command /share/MD0_DATA/.qpk...borg-env/bin/python3 - setuptools pip wheel:
      Traceback (most recent call last):
      File "<stdin>", line 7, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/opt/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 26, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/opt/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/utils/__init__.py", line 23, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/opt/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/locations.py", line 9, in <module>
      File "/share/MD0_DATA/.qpkg/Entware-3x/borg-env/lib/python3.6/distutils/__init__.py", line 17, in <module>
        real_distutils = imp.load_module("_virtualenv_distutils", None, distutils_path, ('', '', imp.PKG_DIRECTORY))
      File "/imp.py", line 244, in load_module
      File "/imp.py", line 210, in load_package
    ValueError: '/opt/lib/python3.6/distutils/__init__.py/__init__.pyc' is not a package
    ----------------------------------------
    ...Installing setuptools, pip, wheel...done.
    Traceback (most recent call last):
      File "/opt/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
        main()
      File "/opt/lib/python3.6/site-packages/virtualenv.py", line 713, in main
        symlink=options.symlink)
      File "/opt/lib/python3.6/site-packages/virtualenv.py", line 945, in create_environment
        download=download,
      File "/opt/lib/python3.6/site-packages/virtualenv.py", line 901, in install_wheel
        call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
      File "/opt/lib/python3.6/site-packages/virtualenv.py", line 797, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /share/MD0_DATA/.qpk...borg-env/bin/python3 - setuptools pip wheel failed with error code 1

Anyway, `Borg` itself is working fine, many-many thanks for that!  Though Fuse is very desirable to get working too.

**Comment by ThomasWaldmann** [comment]
llfuse install: it wants the pkg-config tool. see our install docs for some required packages hints.

not sure about the virtualenv issue, it just looks broken (but that is unrelated to borg).

**Comment by quicktrick** [comment]
Thank you, Thomas!  Unfortunately that didn't work too.  I tried it on the same and on another Qnap NAS. I tried to install it from the source code too, but got the following output:

    pip3.6 install -r requirements.d/fuse.txt
    Collecting llfuse<2.0 (from -r requirements.d/fuse.txt (line 3))
      Downloading llfuse-1.3.2.tar.bz2 (348kB)
        100% | 348kB 196kB/s
    No files/directories in /share/MD0_DATA/.qpkg/Entware-ng/tmp/pip-build-m1ebksv0/llfuse/pip-egg-info (from PKG-INFO)

And I didn't find some required packages in Entware's repository too.

It's not a big deal though. Borg itself works fine and that's the thing.

**Comment by ThomasWaldmann** [comment]
@quicktrick that looks like building llfuse did not work. Maybe `-v` helps?

And, as I already said, we've documented all requirements for borg (and deps) in the install docs.

**Comment by noplanman** [comment]
@copart You may want to try building the binary using my docker building project here:
https://git.feneas.org/noplanman/borg-binary-builder

After installing docker and checking out the project `./build qemux86-64 1.1.7` will create an image with a built binary, and `./extract qemux86-64 borg` will then extract it so that you can use it directly.

I'd encourage you to read the readme first though!

**Comment by quicktrick** [comment]
I've just successfully upgraded from 1.1.4 to 1.1.8 on my old Qnap TS-239 Pro II+ Turbo (x86_32) `Linux QNAP 3.4.6 #1 SMP Fri Dec 8 10:21:53 CST 2017 i686 GNU/Linux`.

    [admin@QNAP src]# pip3.6 install --upgrade pip
    [admin@QNAP src]# curl -O -L https://github.com/borgbackup/borg/releases/download/1.1.8/borgbackup-1.1.8.tar.gz
    [admin@QNAP src]# tar -xzf borgbackup-1.1.8.tar.gz
    [admin@QNAP borgbackup-1.1.8]# TMPDIR=/opt/tmp pip3.6 install -v -r requirements.d/development.txt
    [admin@QNAP borgbackup-1.1.8]# TMPDIR=/opt/tmp pip3.6 install -v -r requirements.d/docs.txt
    [admin@QNAP borgbackup-1.1.8]# TMPDIR=/opt/tmp pip3.6 install -e .
    [admin@QNAP borgbackup-1.1.8]# borg -V
    borg 1.1.8

First I installed the github master branch version `borgbackup-1.2.0.dev745+g2bcff382`, and it seemed to work, but when I tried to backup I got errors, so I moved to 1.1.8.  It works fine!

**Comment by ngondard** [comment]
Thanks to @ThomasWaldmann, @copart, @quicktrick and everyone else involved in this thread, I got me `borgbackup-1.1.8` on an outdated armv5 `Buffalo Linkstation`!
For information sake, I took the `Entware` route as @copart explained (first installing `python3` + `python3-pip` and downloading Entware headers into `/opt/include`). Then I had trouble with `openssl`. I compiled it from source with Entware packages (namely `perl`, `perlbase-base`, `perlbase-cpan`, `gcc`, `make`).
Backuping just fine right now!

**Comment by noplanman** [comment]
@ngondard Out of curiosity, did you try out the binary at https://borg.bauerj.eu?

**Comment by ngondard** [comment]
@noplanman it would have spared me quite some time indeed! However, I am currently building `borgbackup` on another antique (a powerpc-based `Mybooklive`). Therefore I wanted to learn (besides, I am an IT guy after all).

**Comment by noplanman** [comment]
Ok! Just checking to see if it worked, to assure that the builds play nicely on different systems :+1:

**Comment by danielczestki** [comment]
> Has anyone of you found a solution for this ARM or can someone give me a hint how I could do this?
> 
> Cheers,
> Saw

hello. I am looking ARM based borg binaries. Do you have them ?

**Comment by noplanman** [comment]
@danielczestki Check here: https://borg.bauerj.eu/

**Comment by danielczestki** [comment]
I found: https://borg.bauerj.eu/

**Comment by Hurricos** [comment]
> @noplanman it would have spared me quite some time indeed! However, I am currently building `borgbackup` on another antique (a powerpc-based `Mybooklive`). Therefore I wanted to learn (besides, I am an IT guy after all).

How did things work out on your MyBook? Those have the same processor (APM82181) as the Meraki MX60W - 1G flash, 512MB RAM, run OpenWrt fine, have headers for a SATA and if you add some capacitors the miniPCIe slot is also an mSATA slot (tested by adding said capacitors and the SATA interface to the .dts).

**Comment by jchhenderson** [comment]
> I found: https://borg.bauerj.eu/

Hi all,

So for an Intel based QNAP (TS-453Bmini), is the best method via Container Station or is there an up-to-date binary?

I did find the below, but it is v1.1.7
https://www.qnapclub.eu/en/qpkg/488

**Comment by ThomasWaldmann** [comment]
Give the maintainer a wakeup call, there were important fixes in 1.1.11 and also in 1.1.14.

**Comment by jchhenderson** [comment]
Hi, thanks.  I'll do that, but it no longer loads since the latest QTS update as it hasn't got a valid signature.

**Comment by noplanman** [comment]
@jchhenderson You may be able to simply overwrite the borg binary in the system, even if there is no "official" QNAP package.
I do the same on my Synology boxes.

**Comment by jchhenderson** [comment]
@noplanman nice.  What would the co and be to do that?

**Comment by noplanman** [comment]
@jchhenderson Can you log in to your QNAP with SSH?
If yes, you can execute `uname -m` to find out what architecture your NAS has and then download the correct borg binary from the [releases page](https://github.com/borgbackup/borg/releases/) directly to your NAS (probably `borg-linux32`). Then you can make it executable and try to execute it to make sure that it works:
```
$ chmod +x borg-linux32
$ ./borg-linux32 -V
```
If the correct version is displayed, it works!

Then you can see where your packaged borg binary is located with: `$ which borg`
Lastly, you can rename / back up the original file and then move the one you downloaded into the place of the old one.

Hope that makes sense, otherwise just ask again!

**Comment by jchhenderson** [comment]
Hi,

Please be patient with me.

I have SSH'd in and `uname` -m results with `x86_64` so I downloaded `borg-linux64`

```
$ chmod +x borg-linux64
$ ./borg-linux64 -V
```
resulted in `borg-linux64 1.1.14` - fantastic

`$ which borg` resulted in `/usr/bin/borg`
I went here but it was an alias that pointed to the real location - which is where I copied it.

Thanks for your help!

**Comment by copart** [comment]
Howdy all... So, I have not tried updating borg in too long on my QNap. Unfortunately my qnap is end of life and does not support containers/dockers, which is definitely the best way.

```
[~] # pip3.6 install borgbackup
Collecting borgbackup
  Using cached borgbackup-1.1.14.tar.gz (3.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/share/MD0_DATA/.qpkg/Entware-ng/tmp/pip-install-pz_ha5y7/borgbackup/setup.py'"'"'; __file__='"'"'/share/MD0_DATA/.qpkg/Entware-ng/tmp/pip-install-pz_ha5y7/borgbackup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /share/MD0_DATA/.qpkg/Entware-ng/tmp/pip-pip-egg-info-0yj_qz4c
         cwd: /share/MD0_DATA/.qpkg/Entware-ng/tmp/pip-install-pz_ha5y7/borgbackup/
    Complete output (87 lines):
    /opt/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'entry_points'
    Traceback (most recent call last):
      File "/dist.py", line 528, in _parse_command_opts
      File "/dist.py", line 482, in get_command_class
      File "/dist.py", line 832, in get_command_class
    distutils.errors.DistutilsModuleError: invalid command 'bdist_egg'
```

python3-distutils is installed. Oddly I cannot even install older versions via pip anymore.

Any guess how to get around the bdist_egg issue?

**Comment by noplanman** [comment]
@copart How about using the pre-built binaries from the [Releases](https://github.com/borgbackup/borg/releases/) page?

@jchhenderson Well done! 💪

**Comment by copart** [comment]
the prebuild have never worked due to QNap having very old libraries

```
./borg: error while loading shared libraries: libdl.so.2: wrong ELF class: ELFCLASS32
```

**Comment by quicktrick** [comment]
Hi @copart !

Last time I installed borgbackup (1.1.10) on Qnap TS-459 Pro (on 2019-12-16), I did it the following way:

```
Linux TS-459 3.4.6 #1 SMP Tue Apr 21 10:44:30 CST 2020 x86_64 GNU/Linux
```

```
root@TS-459:/# opkg install gcc
root@TS-459:/# opkg install make gawk
root@TS-459:/# opkg install pkg-config
root@TS-459:/# opkg install patch diffutils coreutils-install
root@TS-459:/# wget -qO- http://pkg.entware.net/binaries/x86-64/include/include.tar.gz | tar xvz -C /opt/include
root@TS-459:/# source /opt/bin/gcc_env.sh
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src# curl -O -L https://github.com/lz4/lz4/archive/v1.9.2.tar.gz
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src# tar -xzf v1.9.2.tar.gz
root@TS-459:/# export prefix=/opt
root@TS-459:/# export CC=gcc
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src/lz4-1.9.2# make
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src/lz4-1.9.2# make install
root@TS-459:/# lz4 -V
*** LZ4 command line interface 64-bits v1.9.2, by Yann Collet ***
root@TS-459:/# opkg install python3
root@TS-459:/# opkg install python3-dev
root@TS-459:/# opkg install libev
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src# python3 get-pip.py
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src# pip -V
pip 19.3.1 from /opt/lib/python3.7/site-packages/pip (python 3.7)
root@TS-459:/share/MD0_DATA/.qpkg/Entware/lib# chmod 755 libcrypto.so.1.1
root@TS-459:/share/MD0_DATA/.qpkg/Entware/lib# ln -s libcrypto.so.1.1 libcrypto.so
root@TS-459:/share/MD0_DATA/.qpkg/Entware/bin# ln -s python3 python
```

Then I tried to install borgbackup from the source

```
root@TS-459:/# export PREFIX=/opt
root@TS-459:/# export BORG_LZ4_PREFIX=/opt
root@TS-459:/# export BORG_OPENSSL_PREFIX=/opt

root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src# curl -O -L https://github.com/borgbackup/borg/archive/1.1.10.tar.gz
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src# tar -xzf 1.1.10.tar.gz
root@TS-459:/share/MD0_DATA/.qpkg/Entware/usr/src/borg-1.1.10# pip install -r requirements.d/development.txt
.....
    /opt/bin/ld: cannot find -lffi
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-openwrt-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/share/MD0_DATA/.qpkg/Entware/tmp/pip-install-xst9o0ak/cffi/setup.py'"'"'; __file__='"'"'/share/MD0_DATA/.qpkg/Entware/tmp/pip-install-xst9o0ak/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /share/MD0_DATA/.qpkg/Entware/tmp/pip-record-c_opb4bt/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

After that I tried another way:

```
root@TS-459:/share/MD0_DATA/.qpkg/Entware# TMPDIR=/opt/tmp pip install "borgbackup==1.1.10"
Collecting borgbackup==1.1.10
  Downloading https://files.pythonhosted.org/packages/24/13/77cd0bed77fa80cf79e18d1fb1806641e895878bda389771ea63f30560de/borgbackup-1.1.10.tar.gz (3.6MB)
     |████████████████████████████████| 3.6MB 380kB/s
Building wheels for collected packages: borgbackup
  Building wheel for borgbackup (setup.py) ... done
  Created wheel for borgbackup: filename=borgbackup-1.1.10-cp37-cp37-linux_x86_64.whl size=1034301 sha256=f02d858d1bfb1c9c9d068e031611140f8c56af13bed019e65f346ea27ad14362
  Stored in directory: /opt/root/.cache/pip/wheels/51/4f/71/1e3136f4d5481e2089ea3eb28a47be4ea97d3ff08c4eb91acc
Successfully built borgbackup
Installing collected packages: borgbackup
Successfully installed borgbackup-1.1.10
```

```
root@TS-459:/# borg -V
borg 1.1.10
```

I haven't updated it since then yet.

**Comment by copart** [comment]
hi @quicktrick. I think I would have to remove my customizations and restart fresh. Your awesome came up with same error. Thank you so much for responding.

Any chance you can share the compiled binary for 1.1.10? Maybe it will work.

**Comment by copart** [comment]
I got it!
I had to move from Entware-ng to Entware. Upgraded to python3.

Downloaded source for 1.1.14.

And:
python3 ./setup.py install

Wow

**Comment by quicktrick** [comment]
Congratulations!   Is it working now?

**Comment by jchhenderson** [comment]
ugh - my QNAP's OS keep killing Borg because it has an "Invalid Digital Signature" (I think from the original 1.1.7 package that I installed first before updating 1.1.14 over it).

**Comment by noplanman** [comment]
@jchhenderson Maybe instead of overwriting the original 1.1.7 binary, you can try to simply replace the alias and move the 1.1.14 binary directly to `/usr/bin/borg`.
There might be some cronjob or something checking signatures that needs to be disabled, I don't know QNAP, sorry 😕

**Comment by jchhenderson** [comment]
@noplanman - thanks, will try that.
No apologies necessary, I appreciate the friendly help 👍

**Comment by copart** [comment]
@quicktrick 
Only fixed ssh (opkg messed it up) just now. Still has same issue where a backup is disconnecting before completing. 

The following is same issue I had with previous version, which is why I wanted to upgrade
```
Executing...
borg create --stats --compress zlib,6 --list -v --filter=AME --exclude-caches --exclude-from ./all.filter bu:all.borg::all-2020-10-19 /media /web

Creating archive at "bu:all.borg::all-2020-10-19"
Connection closed by remote host
```
The "Connection closed by remote host" is happening before the backup finishes, notice we are not seeing that stats (--stats). 

Running a check now, hopefully this fixes it. This is a repo that has existed and appended to almost daily since 2016. Every so often doing a prune.

**Comment by noplanman** [comment]
@copart Do you run into the same disconnect problem with a fresh repo?

**Comment by jchhenderson** [comment]
> @jchhenderson Maybe instead of overwriting the original 1.1.7 binary, you can try to simply replace the alias and move the 1.1.14 binary directly to `/usr/bin/borg`.
> There might be some cronjob or something checking signatures that needs to be disabled, I don't know QNAP, sorry 😕

Uninstalling the 1.1.7 .qpkg and moving the 1.1.14 binary to /usr/bin/borg (and making executable) worked perfectly

Thanks you so much!
