### ISSUE TITLE
Repository does not exist

### ISSUE THREAD

**Issue by jake147-s** [borgbackup/borg#6924]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
1.1.15

#### Operating system (distribution) and version.
linux mint 20.3

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg extract media/jk/iomega320hd/archivebb::2022-08-01T12:59:28
```

## Describe the problem you're observing.

when i list the archive with 
```
borg list media/jk/iomega320hd/archivebb
```

i see the following archive with the timestamp and hash
```
2022-08-01T12:59:28
```
so the path is correct

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes

**Comment by jake147-s** [comment]
borg version 1.1.15

**Comment by ThomasWaldmann** [comment]
Guess the easiest explanation is that the repo path is incorrect. Considering it is a relative path (see missing `/` at the left), it depends on the current working directory (which could be even different between your tries and looks like it only would work if cwd == `/`).

So just use absolute repo paths for such a use case.
