### ISSUE TITLE
convert .vsd to .odg

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6928]
we have some diagrams made with visio in the docs, the should be transformed to an open format, like libreoffice draw.

**Comment by ThomasWaldmann** [comment]
note: i tried loading the stuff into libreoffice on macOS, but it looked rather weird / incorrect.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
It's opening quite well for me with libreoffice on Linux. Do you want to recreate near-exact copies or can we be lenient regarding the look ?

**Comment by ThomasWaldmann** [comment]
We can be lenient. It should look ok and transport the same information.
