### ISSUE TITLE
Command sequence for redundant backups

### ISSUE THREAD

**Issue by necker123** [borgbackup/borg#6978]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

1.2.1

#### Operating system (distribution) and version.

macOS 12.5

#### How much data is handled by borg?

~20 GB

## Describe the problem you're observing.

The docs article at https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location says that you need the following commands to backup to two different repos:

`borg init repo1`
`borg init repo2`

`borg create repo1`
`borg create repo2`

Is this the same as doing the following or is there any difference?

`borg init repo1`
`borg create repo1`

`borg init repo2`
`borg create repo2`

This might be important for people who already created one backup and want to add a second one to a different location.

If it is the same, would it be possible to add it to the docs?

**Comment by ThomasWaldmann** [comment]
That doesn't matter / doesn't make a difference, because the 2 repositories are independent of each other.

And of course you'll need something like `borg create repoX::archivename ...`.
