### ISSUE TITLE
check xattr namespace behaviour

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#6997]
there was a strange issue in #6988 and the root cause was a strange xattr named `user.security.selinux` (the correct name would be `security.selinux`).

the processing (or rather ignoring) of such invalid stuff was solved by #6990.

but the open question is still: where did that invalid xattr initially come from?

we should make sure it did not come from borg.

**Comment by ThomasWaldmann** [comment]
Note:
- tests in `borg.testsuite.xattr` work ok on macOS (I also added some with `security.` namespace and didn't spot anything unusual)

**Comment by ThomasWaldmann** [comment]
@rudd-o do you use freebsd? if so, did you restore a linux backup on a freebsd machine?

**Comment by ThomasWaldmann** [comment]
It looks like the `borg.platform.freebsd.setxattr` code is problematic when used cross-platform:
- when backing up on freebsd, borg only queries the xattrs from the EXTATTR_NAMESPACE_USER (and writes them with a `user.` prefix into the archive) - **check if we also need to back up other namespaces**.
- so when restoring such an archive on freebsd, only `user.*` xattrs are expected and processed correctly (as far as i could see)
- but, if an archive has `security.*` xattrs, `borg.platform.freebsd.setxattr` is misbehaved:
  - it does not find the usual `user.` prefix (and thus does not strip it)
  - it does not expect a `security.` prefix (and thus does not strip it)
  - but it still calls the freebsd api with EXTATTR_NAMESPACE_USER, so the result could be something like `user.security.*`. :-(

**Comment by Rudd-O** [comment]
Only Linux.  No FreeBSD.  The attributes must have been set by either Syncthing or some other tool.  Right now all I want is those attributes gone.  `user.security.selinux` is ridiculous and meaningless.

**Comment by ThomasWaldmann** [comment]
I am not familiar with xattr usage on freebsd, so guess this needs somebody with knowledge about this, see my previous comment.

**Comment by oikumene** [comment]
FreeBSD manual of [extattr(3)](https://man.freebsd.org/cgi/man.cgi?query=extattr&sektion=3&apropos=0&manpath=FreeBSD+13.1-RELEASE+and+Ports) says 

> Although a file system may implement arbitrary 
> namespaces, these functions only support the EXTATTR_NAMESPACE_USER
> ("user") and EXTATTR_NAMESPACE_SYSTEM ("system") namespaces, which	are
> defined in	[extattr(9)](https://man.freebsd.org/cgi/man.cgi?query=extattr&sektion=9&apropos=0&manpath=FreeBSD+13.1-RELEASE+and+Ports).

does this help?

**Comment by ThomasWaldmann** [comment]
@oikumene for what are xattrs typically used for under freebsd? Is there some list of the "usual stuff" (keys)?

**Comment by ThomasWaldmann** [comment]
@oikumene can you review #7435?

**Comment by oikumene** [comment]
> for what are xattrs typically used for under freebsd? Is there some list of the "usual stuff" (keys)?

I do not know well, but I think there are no "usual stuff" for xattr in FreeBSD. I have never encountered one.
For Mandatory Access Control (MAC) (which is similar to SELinux), they use maclabel which seems different from xattr (as far as reading manpages.)

**Comment by ThomasWaldmann** [comment]
^ fixed in 1.2-maint branch, hopefully.
