### ISSUE TITLE
Allow manual checkpoints creation, via e.g. UNIX, signals during the backup process

### ISSUE THREAD

**Issue by Flowdalic** [borgbackup/borg#7005]
It would be great if users could trigger the creation of checkpoints while the backup process is running. My use case for this is to trigger a checkpoint if I am about to terminate or suspend the backup process, e.g., because I am about to shut the lid of my laptop.

Please conisder extending borg so, that a manual checkpoint can be triggered, e.g., by sending a UNIX signal to the process.

Additionally, or alternatively, couldn't borg create a ceckpoint when it receives SIGTERM?

**Comment by infectormp** [comment]
Did you read FAQ about checkpoints? https://borgbackup.readthedocs.io/en/stable/faq.html#if-a-backup-stops-mid-way-does-the-already-backed-up-data-stay-there

**Comment by infectormp** [comment]
You can change checkpoint internal using the `--checkpoint-interval` command to more suitable time interval

**Comment by Flowdalic** [comment]
Thanks, I see that borg now always creates a checkpoint on SIGINT. This can hence be closed.
