### ISSUE TITLE
Drop makedirs for cache and keys on the remote side

### ISSUE THREAD

**Issue by manwegit** [borgbackup/borg#701]
Running borg against remote target where home directory is not writeable, borg will exit with
`Remote: PermissionError: [Errno 13] Permission denied: '/home/backup/.borg/keys' `
And same for .borg/cache or .cache/borg/ (depending on version)

Fix with something like:
`        if args.func != self.do_serve:`
to arhiver.py line 1418 (and indents etc) 

Workaround is to pre create said directories or using ` --remote-path=` with wrapper script

**Comment by ThomasWaldmann** [comment]
does it actually use these directories at all on the "server" side?

**Comment by manwegit** [comment]
As far I could test, no:
tried extract, mount, create, check and init

As long as keys and cache dir exist (even when not writable) borg create worked fine.

I did not go through source with a fine comp and this was just running binary test against server.

**Comment by ThomasWaldmann** [comment]
as encryption is done client-side, keys are not expected to ever be on a remote server (or used by remote server).

also, the cache is primarily to accelerate access to remote data, that could be only accessible over a slow connection, so that also is only expected on the client.

**Comment by ThomasWaldmann** [comment]
fixed by:
https://github.com/borgbackup/borg/commit/9c9ac2fd58d3217ae431db96a5dd1196d09be99a

thanks!
