### ISSUE TITLE
Question - how to run borg in low-RAM environment?

### ISSUE THREAD

**Issue by jbrepogmailcom** [borgbackup/borg#7023]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

1.1.9

#### Operating system (distribution) and version.

Raspbian

#### Hardware / network configuration, and filesystems used.

512MB RAM

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

sudo borg prune --keep-within=3m -v -p /RAID3T/BACKUPS/Borg/T4-Ubuntu-Borg

## Describe the problem you're observing.

Borg is crashin on oom-killer - Out of RAM

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes

#### Include any warning/errors/backtraces from the system logs

Is there any possibility to reduce RAM usage while prune? Backups itself run well, but not prune.

**Comment by ThomasWaldmann** [comment]
There is a formula in the docs for the memory consumption, maybe you can use it to reduce the memory requirements.

https://borgbackup.readthedocs.io/en/1.1.18/internals/data-structures.html#indexes-caches-memory-usage

The more chunks you have in the repo, the more memory the chunks index and the repo index will need.

The files cache (used for `borg create`) will have a memory consumption proportional to the files count and also the TTL will influence it.

In general, it is not recommended to run borg on low-memory systems, especially not if you are at the same time dealing with big amounts of data (what makes the whole system quite "unbalanced").

**Comment by ThomasWaldmann** [comment]
http://archive.raspbian.org/raspbian/pool/main/b/borgbackup/

btw, there seem to be more recent packages there, can you use them?

1.1.9 is rather old meanwhile (and only acceptable if it is patched for the critical bug that was fixed in 1.1.11, which usually is the case in debian and ubuntu).

**Comment by jbrepogmailcom** [comment]
Thanks for the quick answer. However, I am running borg prune, which works on already created chunks, not borg create.

It seems that if I run borg remotely over ssh, the borg daemon on low-RAM computer uses less RAM.

**Comment by ThomasWaldmann** [comment]
borg prune and borg delete also will need the chunks (to decrement the refcounts) and the repo index.

If you run borg client/server (== with a ssh: repository), the repo index is loaded in the borg serve process and the chunks index is loaded into the borg client process.

**Comment by ThomasWaldmann** [comment]
Maybe the OOM is triggered by a hashtable resize (either growing or shrinking the HT), which temporarily has both old and new hashtables in memory (IIRC).

**Comment by jbrepogmailcom** [comment]
Sorry I am user not expert, I do not understand last message at all :-)
Nevermind - I tried to run apt upgrade and I am not offered any borg version above the one I have, 1.1.9. I run Raspian 10 (buster) and I do not intend to upgrade the distro as everything is running well. Is there any special repository I need to install to get higher version for Raspbian 10?

**Comment by ThomasWaldmann** [comment]
for the normal debian, there is debian backports with newer stuff, not sure how it is handled for raspbian.

https://borg.bauerj.eu you can also check there for a more recent version (but guess that will not fundamentally change the memory situation).

**Comment by jbrepogmailcom** [comment]
I finally fixed it by extending swap memory from 100MB to 1GB. About third of that was used and it ran for 6 hours
