### ISSUE TITLE
migrate-to-repokey endless passphrase loop on repokey repo

### ISSUE THREAD

**Issue by manwegit** [borgbackup/borg#703]
borg migrate-to-repokey on a repokey repo created endless loop for asking passphrase

Expected behaviour is to indicate repokey mode active after first passphrase query if repo is not passphrase repo.

**Comment by manwegit** [comment]
Should manifest key type change when migrating repo key?
AFAICT Manifest does not change on migrate. 

Quick fix for this problem would be to add test for keytype on migrate.
archiver.py
132:        if manifest_data[0] == PassphraseKey.TYPE:

With that change migrate will not stay in endless loop, but already migrated passphrase things rechange repokey.

I don't know enough about manifest manipulation in borg, so I'm not comfortable touching that part of the code.

**Comment by ThomasWaldmann** [comment]
No, keytype byte does not change. As the support for passphrase-only was removed, its type byte was just re-assigned to be repokey now. The type byte is in every chunk stored into the repo, not just the manifest. So, checking for the type byte does not help here, but checking for key location would.

**Comment by manwegit** [comment]
Another quickfix would be to change while True to a counter + error

borg/key.py
234:        while True:

**Comment by manwegit** [comment]
This is not an issue for me, but migrating to 1.0.0 from old passphrase system or other people unsure about this command might be confused and some clean exit would be nice (like three tries).
