### ISSUE TITLE
Syncing Remote Repos

### ISSUE THREAD

**Issue by christopher-besch** [borgbackup/borg#7033]
Hello smart people!
I have a Borg repo on two machines. One repo (called server repo from here on) gets populated with new daily archives and the second one syncs it's repo (called client repo) with the former.

The current way of syncing I came up with:
1. Check what archives are missing on the client repo.
2. Extract those archives into a temporary directory on the client using SSH.
3. Create a new archive in the client repo from the temporary dir.
4. Remove any repos in the client that don't exist on the server anymore.

My problem with this solution is that it always pulls an entire new archive (not just the chunks that differ) over the network. This is very slow and I'm looking for a way to speed this process up. Is there some kind of `borg sync` command that syncs two repos?

Thanks for your help!
Chris

**Comment by ThomasWaldmann** [comment]
There's no such functionality yet, but it will come with borg 2:

https://borgbackup.readthedocs.io/en/master/usage/transfer.html
