### ISSUE TITLE
Running `borg check` causes `local variable 'segment' referenced before assignment`

### ISSUE THREAD

**Issue by WilliamDEdwards** [borgbackup/borg#7034]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

Bug report.

#### Your borg version (borg -V).

1.2.0

#### Operating system (distribution) and version.

macOS 12.5.1

#### Hardware / network configuration, and filesystems used.

APFS

#### How much data is handled by borg?

Repository is empty.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

    BORG_PASSCOMMAND=test borg check koffer

## Describe the problem you're observing.

When a repository is corrupt, and `borg check` is run, the following error is written to stderr:

    UnboundLocalError: local variable 'segment' referenced before assignment

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

- Create repository
- Corrupt it, e.g. by moving away files in `data/`
- Run `borg check`

#### Include any warning/errors/backtraces from the system logs

```
Local Exception
Traceback (most recent call last):
  File "/usr/local/Cellar/borgbackup/1.2.0/libexec/lib/python3.10/site-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
  File "/usr/local/Cellar/borgbackup/1.2.0/libexec/lib/python3.10/site-packages/borg/archiver.py", line 5020, in run
    return set_ec(func(args))
  File "/usr/local/Cellar/borgbackup/1.2.0/libexec/lib/python3.10/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/local/Cellar/borgbackup/1.2.0/libexec/lib/python3.10/site-packages/borg/archiver.py", line 342, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space, max_duration=args.max_duration):
  File "/usr/local/Cellar/borgbackup/1.2.0/libexec/lib/python3.10/site-packages/borg/repository.py", line 1040, in check
    logger.info('finished segment check at segment %d', segment)
UnboundLocalError: local variable 'segment' referenced before assignment
```

**Comment by ThomasWaldmann** [comment]
Good catch, you found a bug! I could reproduce it with 1.2-maint code. :-)

**Comment by ThomasWaldmann** [comment]
Fixed that specific issue.

In case of an empty repo it runs into another traceback-causing issue though. but in that case, it is not due to a problem in the code, but because it can not find a segments transaction id if there are no segment files and correctly notes that this is likely beyond repair.
