### ISSUE TITLE
Repository init fails in keyfile mode when keyfile dir is not writeable

### ISSUE THREAD

**Issue by manwegit** [borgbackup/borg#704]
Repository is created, but unusable because keyfile is not stored on the disk.

Steps to reproduce:
```
mkdir /tmp/keysdir
export BORG_KEYS_DIR=/tmp/keysdir
chmod a-w "$BORG_KEYS_DIR"
borg init -e keyfile /tmp/testrepo
```
result:
```
Enter new passphrase:
Enter same passphrase again:
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1466, in main
  File "borg/archiver.py", line 1420, in run
  File "borg/archiver.py", line 93, in do_init
  File "borg/key.py", line 35, in key_creator
  File "borg/key.py", line 340, in create
  File "borg/key.py", line 386, in save
PermissionError: [Errno 13] Permission denied: '/tmp/keysdir/tmp_testrepo'
```

Solutions:

1. If key cannot be written then print it out with the error.
1. Abort repo creation and remove also created repo.
1. Test write permissions before repo creation to keyfile dir when -e keyfile is used.

**Comment by ThomasWaldmann** [comment]
Guess solution 3 is the best / easiest.

**Comment by ThomasWaldmann** [comment]
Hmm, after thinking about it: we create that keyfile dir with correct permissions in borg if it does not exist.

Why should we care if somebody else creates it with wrong permissions or modifies it to have wrong permissions?

**Comment by manwegit** [comment]
If we want to be nice, then we could print keyfile info to stdout (or err) so that the key could be manually inserted later. ( sol 1)
Although this only affects newly created repos so  there is no data loss, confusion at the most.

**Comment by ThomasWaldmann** [comment]
I am closing this. The "permission denied" error msg is clear enough and borg is not responsible for catching any possible bad permissions in the filesystem.

As an admin, one always needs to be aware about ownership and permissions. If the uid/gid used by a process can't access the data it needs to access / can't create files it needs to create, the only thing that can be expected is a reasonable error message. That's a general thing and does not just apply to the keys dir, but basically any file/directory in use.
