### ISSUE TITLE
options --list doesn't work with delete --dry-run

### ISSUE THREAD

**Issue by Nono-m0le** [borgbackup/borg#7060]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG (imo)

#### Your borg version (borg -V). 
borg 1.1.15
#### Operating system (distribution) and version.
Ubuntu 18 LTS
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg delete --list --dry-run --glob-archives 'name-*' ssh://user@host:port/./borg_backup/`
or
`borg delete --list --dry-run -a 'name-*' ssh://user@host:port/./borg_backup/`

## Describe the problem you're observing.
both above commands gives me :
`borg: error: unrecognized arguments: --list`

I look in the documentation (here https://borgbackup.readthedocs.io/en/stable/usage/delete.html ) for the command above: 
```
$ borg delete --list --dry-run -a '*-May-*' /path/to/repo
$ borg delete --glob-archives '*-2012-*' /path/to/repo
```

**Comment by ThomasWaldmann** [comment]
These are the docs for 1.1.15: https://borgbackup.readthedocs.io/en/1.1.15/usage/delete.html

No `--list` there. The stable docs you read are for the latest stable release, which is currently 1.2.2.

Guess you could use that via the borgbackup ppa, maybe first upgrade to ubuntu 20.04 at least.
