### ISSUE TITLE
master: switch binary building to python 3.10.8+

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7068]
master branch:

currently binaries still use 3.9.x, but guess the pyinstaller 5.x we have now is expected to work ok with 3.10 and 3.10 in general should be stable enough meanwhile.

**Comment by ThomasWaldmann** [comment]
note: tests and building the binary worked with 3.10.7.

**Comment by firewavemtl** [comment]
What about 3.11 ? :)

**Comment by ThomasWaldmann** [comment]
@firewavemtl we do automated tests on 3.11, but for building the binary we want something less fresh / bleeding edge than 3.11 is currently.

master branch is currently in beta, so we primarily want to focus on finding bugs in borg (and maybe avoid bugs somewhere else).

But I don't rule it out for later.

Maybe at a later borg beta or rc, maybe at python 3.11.1 or .2 and also when pyinstaller got some more community testing with 3.11.x.

**Comment by ThomasWaldmann** [comment]
Fixed by #7104.
