### ISSUE TITLE
2.0.0b3: 'tuple' object has no attribute 'segment'

### ISSUE THREAD

**Issue by pgerber** [borgbackup/borg#7073]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

bug

#### Your borg version (borg -V).

```
user@tmp-borg:~$ borg --version
borg 2.0.0b3
```

#### Operating system (distribution) and version.

Debian 11

#### How much data is handled by borg?

Seen on two test repositories. Sizes: ~ 1MiB and 100 GiB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ tar -C /etc -c fstab | borg -r test import-tar test-4 -
Local Exception
Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 594, in main
  File "borg/archiver/__init__.py", line 522, in run
  File "borg/archiver/_common.py", line 155, in wrapper
  File "borg/archiver/tar_cmds.py", line 253, in do_import_tar
  File "borg/archiver/tar_cmds.py", line 327, in _import_tar
  File "borg/archive.py", line 681, in save
  File "borg/manifest.py", line 287, in write
  File "borg/repository.py", line 1311, in put
AttributeError: 'tuple' object has no attribute 'segment'

Platform: Linux tmp-borg 5.19.9-1.fc32.qubes.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 16 14:54:56 CEST 2022 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b3  Python: CPython 3.9.14 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 120594  CWD: /home/user
sys.argv: ['borg', '-r', 'test', 'import-tar', 'test-4', '-']
SSH_ORIGINAL_COMMAND: None
```
## Describe the problem you're observing.

The above crash happens rather arbitrarily. Affected is one almost empty repository (trace above). I also get the same error trying to copy a repository using export-tar / import-tar for a repository where this worked just fine with 2.0.0b2.

**Comment by ThomasWaldmann** [comment]
Should not happen for new repos. Did you work with an old (borg 1) repo here?

**Comment by ThomasWaldmann** [comment]
Note: `NSIndex.__get__` returns `NSIndexEntry` named 3-tuples, `NSIndex1.__get__` returns normal 2-tuples.

`NSIndex1` is only used for reading old repos (like in `borg transfer`).

**Comment by pgerber** [comment]
> Should not happen for new repos. Did you work with an old (borg 1) repo here?

This seems unlikely. Borg 2 appears to refuse to touch any Borg 1 repository. I was testing a few things and copying some repositories. Could be that I corrupted the repository in some way in the process.

**Comment by ThomasWaldmann** [comment]
That's strange then. You did not maybe edit the version number in the repo config? :-)

**Comment by pgerber** [comment]
> You did not maybe edit the version number in the repo config? :-)

I'm pretty sure I'd remember that :-)

>  Or use not uptodate compiled Cython/C code?

It's the all-in-one binary published on GitHub.

**Comment by ThomasWaldmann** [comment]
Just tried it with the 2.0.0b3 code:
```
>>> n=NSIndex()
>>> n[b'0'*32] = (1,2,3)

>>> n[b'0'*32]
NSIndexEntry(segment=1, offset=2, size=3)

>>>n[b'1'*32]
Traceback (most recent call last):
  File "src/borg/hashindex.pyx", line 219, in borg.hashindex.NSIndex.__getitem__
    raise KeyError(key)
KeyError: b'11111111111111111111111111111111'
```

**Comment by ThomasWaldmann** [comment]
I can't reproduce:
```
(borg-env) tw@mba2020 borg % export BORG_REPO=/tmp/b20_repo                                    
(borg-env) tw@mba2020 borg % export BORG_PASSPHRASE=secret                                     
(borg-env) tw@mba2020 borg % borg rcreate -e repokey-aes-ocb
(borg-env) tw@mba2020 borg % borg import-tar arch1 *.tar                                       
(borg-env) tw@mba2020 borg % borg import-tar arch2 *.tar
(borg-env) tw@mba2020 borg % borg list arch1
-rw-r--r-- tw     staff   8391488 Sat, 2022-04-23 01:01:25  zeros.bin
(borg-env) tw@mba2020 borg % borg list arch2
-rw-r--r-- tw     staff   8391488 Sat, 2022-04-23 01:01:25  zeros.bin
(borg-env) tw@mba2020 borg % borg -V
borg 2.0.0b3
```

**Comment by ThomasWaldmann** [comment]
@pgerber can you please add the sha256sum of the binary you use to the top post?

**Comment by pgerber** [comment]
> @pgerber can you please add the sha256sum of the binary you use to the top post?

@ThomasWaldmann, certainly.

```
user@tmp-borg:~$ sha256sum "$(type -p borg)"
4cd2d2134ecff52373ba7df032154058cd343885ca5523e18aaa5c66dc9799bf  /home/user/bin/borg
```

> I can't reproduce

Unfortunately, I don't appear to have the affected repositories any longer and I appear to be unable to reproduce this with a new repository.

**Comment by ThomasWaldmann** [comment]
Ah, I guess I have an explanation:

Maybe your affected repo was made with a borg 2 version that still used the old repo index format (like borg 1.x).

The current borg2 code expects repos to have indexes in the new format and only can deal with old repos / old indexes for `--other-repo` (e.g. of `borg create` and `borg transfer`), but not for `--repo`.

So guess this just an inter-beta incompatibility (which is expected).
