### ISSUE TITLE
borg diff not recognizing identical chunk params when diffing v1.1 with v1.2 archive

### ISSUE THREAD

**Issue by pgerber** [borgbackup/borg#7079]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

```
$ borg -V
borg 1.2.2
```

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ borg diff ::main-2022-09-30T13:41:46Z main-2022-10-03T07:50:40Z
--chunker-params might be different between archives, diff will be slow.
If you know for certain that they are the same, pass --same-chunker-params to override this check.
…
```

## Describe the problem you're observing.

The former archive in the above command was created by Borg v1.1:

```
$ borg debug dump-archive ::main-2022-09-30T13:41:46Z -
{
    …
    "_meta":
    {
        "chunker_params": [
            19,
            23,
            21,
            4095
        ],
…
```

And the latter by Borg v1.2:

```
$ borg debug dump-archive ::main-2022-10-03T07:50:40Z -
{
    …
    "_meta":
    {
        "chunker_params": [
            "buzhash",
            19,
            23,
            21,
            4095
        ],

```

As can be seen, in Borg v1.2 the name for the chunker was added to the params. I suspect this leads to this issue.

I'd consider the following changes to improve the situation:

- [x] Correct comparison between v1.1 and v1.2 chunk params in v1.2.x.
- [x] Convert the chunk params to the newer format during the `borg transfer` required to upgrade to v2.0. As of Borg 2.0.0b3 the chunk params are kept as is but this would probably be a good time to normalize them and drop the code to handle the old format.

**Comment by ThomasWaldmann** [comment]
Very good analysis / suggestions, thanks!
