### ISSUE TITLE
file changed warning: Add message id and path

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#7080]
Why not another issue about "`<path>`: file changed while we backed it up" :upside_down_face: 

I don't think any of the existing issues #6622 #6989 #6379 propose a global solution that can avoid this message.

However, I want to treat those warnings differently in Pika Backup. For this, I would like to have a `msgid` and the file's path. AFAIK there are no warnings with `msgid` yet but, I don't think that is a problem. Not sure if just adding a `path` key to the message would be okay?

It would probably be good to do the same thing for 'deleted during backup' or whatever the message is.

Application:

- Pika supports hourly backups. Files like SQLite of chat apps, or an ongoing Download can cause those warnings quite frequently. Instead of users ignoring all those warnings completely or turning backups off, I'm not alerting the user if there is no warning about the same file an hour later again. It's not 100% secure but much more realistic in practice.
- Just filter those messages completely if you know what you are doing #6379

**Comment by ThomasWaldmann** [comment]
will be fixed as part of #7976.

**Comment by ThomasWaldmann** [comment]
borg 1.4 fixed by #7976 - please test!
