### ISSUE TITLE
make no encryption default for new repository

### ISSUE THREAD

**Issue by brainchild0** [borgbackup/borg#7084]
The `init` command fails if not accompanied by an `-e`/`--encryption` switch, listed in the manual under *optional arguments*, and also marked as *required*, the latter appearing to be accurate. 

The manual section for initializing a new repository first mentions the possibility of the `none` value, for creating an unencrypted repository, halfway through the length of the section, after a detailed description of the security model.

Encryption is extremely useful where needed, but much data is still stored unencrypted, by choice. Unencrypted data storage remains most common and the default for most storage systems. Many data important to a specific individual has no particular value to anyone else. 

If the user has not specified a particular encryption scheme when attempting to create a repository, I suggest that the application should apply the value `none` as the default.

**Comment by brainchild0** [comment]
I am  sorry, but I feel I should take the last opportunity to emphasize the weight of my objections to this choice, and the reasons for them.

The requirement is not aligned to widespread patterns and practices related to generating targets for file storage. Whether making a file system or building an archive, the default is almost always without encryption.

Many user data is kept unencrypted, and not important enough to others for its owner to bother about protection. Photographs of a niece's birthday  party when she was three years old may be an important keepsake, but is a not a practical  idea is that it is unsafe to keep unencrypted copies in a removable storage device kept in a desk drawer in one's home. Indeed, using encryption may be more dangerous to the user than not, due to the possibility of losing the key, and the choice to use encryption should generally be a conscious one born of an understanding of the problems associated with theft or sabotage weighed against the inconvenience and risk.


Unfortunately, the  characterization of a choice to forego encryption as "informed consent" and not the default lacks any notable precedent in historical or practical  context, and the resulting policy is draconian and paternalistic.

**Comment by ThomasWaldmann** [comment]
There is not default for `--encryption` in borg. So you can choose whatever you like, that includes "none" in your case.
