### ISSUE TITLE
support for synchronizing two repositories

### ISSUE THREAD

**Issue by brainchild0** [borgbackup/borg#7085]
Presently, support appears unavailable for copying an archive from one repository to another. Such a feature might be useful to facilitate storing the same backup in multiple locations. Making multiple backups from the same original source is not necessarily an acceptable solution, due to the inability to ensure an exactly equivalent capture, which is especially important for deduplication and incremental use cases. 

Suggested is a feature, following the familiar analogy of Git repositories, to move the minimal   dependencies from one repository to another, considering which data the target may already have acquired, in order copy the data of a given archive.

Unlike Git, Borg does not capture the concept of  a current repository (as Git processes the working directory), so rather than the semantics of *push* and *pull*, a better choice may be a _synchronize_ command, to which may be passed a source and target repository and archive name.

**Comment by infectormp** [comment]
This future can be found in 2.0 version with is beta now https://borgbackup.readthedocs.io/en/2.0.0b3/usage/transfer.html
For current borg version you can use method described in FAQ https://borgbackup.readthedocs.io/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location

**Comment by ThomasWaldmann** [comment]
1. yup, `borg transfer` will be the way in future.
2. that's not quite what @brainchild0 was asking for. for current borg (< 2.0), there is no `borg transfer` yet.

**Comment by brainchild0** [comment]
Thank you for the information and references. I am glad that a *transfer* command is identified as an objective for future  development.

I read the parts of the FAQ, which I had not yet seen, as referenced in the earlier comment. Doing so, I noticed a variety of issues that give me hesitation about whether the current design of Borg is stable and robust enough to  rely on it as for recovery after loss.

The FAQ lists many limitations concerning the importance of only interacting with a given repository from the same system and user account, and the numerous ways that cache or other data incoherence may lead to failure.

I have also read in the documentation that the storage model is not safe for writing to file systems not supporting journaling,  a limitation that precludes many natural backup targets, such as a flash card. In my view the objectives and general use cases of the application ought to support a model by which the logic of the application is robust enough to protect against particular limitations of the underlying file store, whether it be limitations in file naming rules or lack of support for journaling.  While journaling for  a system mount is invaluable for safe operation of a modern operating system, it is not required for data transfer and storage applications.  Transactions may be managed in application logic without any  dependence on file system features.

Returning to the matter of synchronizing repositories, I would suggest that the design of the Borg repository should be akin to that of a Git repository. In any persisted state of a repository as left by the last transaction, or attempted transaction, the data as it had been committed before the transaction  should be possible safely and securely to extract by  any user of any system, the only foreseeable limitation being   the versions of the tools being too far out of date.

**Comment by brainchild0** [comment]
> borg needs a repo storage fs that WORKS. sounds easy, but not all filesystems qualify for that.

I am sorry but I  must dispute that claim that a journaled file system is required for transactional safety at the application level. 


> if you think the git model is so great for backups, i suggest you just try using git for backups and you'll see.

It was never a premise of my reasoning that Git is a suitable tool for backups. I'm sorry you made such an inference.

**Comment by ThomasWaldmann** [comment]
you can also extract a borg repo later without strong requirements of the environment.
