### ISSUE TITLE
support for file systems without journaling

### ISSUE THREAD

**Issue by brainchild0** [borgbackup/borg#7086]
Quoting from [earlier comments](https://github.com/borgbackup/borg/issues/7085#issuecomment-1275974101) for a discussion on a different topic...

> I have also read in the documentation that the storage model is not safe for writing to file systems not supporting journaling, a limitation that precludes many natural backup targets, such as a flash card. In my view the objectives and general use cases of the application ought to support a model by which the logic of the application is robust enough to protect against particular limitations of the underlying file store, whether limitations in file naming rules, or, as in the present case, lack of support for journaling. While journaling for a system mount is invaluable for safe operation of a modern operating system, it is not required for transfer and storage scenarios emphasizing redundancy and archival. Transactions may be managed in application logic without any dependence on file system features.

Continuing...

> In any persisted state of a repository as left by the last transaction, or attempted transaction, the data as it had been committed before the transaction should be possible to extract safely and securely by any user of any system, with the only foreseeable limitation of the versions of the tools being too far out of date.

**Comment by ThomasWaldmann** [comment]
borg works like a log and always appends data at the end.

if you had a valid transaction committed before, that won't be affected by the current transaction being interrupted or failing otherwise and the next time you open the repo, borg will roll back uncommitted stuff to the last valid commit.

**Comment by brainchild0** [comment]
That's good. Why is a problem then if the file system is not journaled?

**Comment by ThomasWaldmann** [comment]
Well, non-journalled fs can corrupt easily in crash events. Then you'll need some sort of fsck trying to get things into a good state again (not always successful).

Maybe it also is better with well-behaved syncing and write-ordering, not sure.

**Comment by brainchild0** [comment]
Yes, the file system may corrupt, but as long as the corruption is detected by the application, then the lack of journaling in the file system is just an inherit limitation for the file system, and not a problem for use in the application.

If a system failure occurs during a backup operation, the normal case is that the user will attempt to resume or to repeat the backup operation.

Is Borg able to detect whether any files are missing or truncated, and is the check efficient enough to be performed at the beginning of each session? (This check should not require reading the full payload of each file.)

**Comment by ThomasWaldmann** [comment]
You can run `borg check` or even `borg check --verify-data` to make sure everything is fine from borg's perspective, but that is an expensive operation and takes quite some time (esp. the latter). 

But guess it can not be much less than this because borg can not know how a fs might be corrupted. There could be files missing, data not having made it onto disk / all-zero files contents, truncation, etc.

**Comment by ThomasWaldmann** [comment]
At startup, borg does some checks to find the last valid transaction:
- checks the checksum/hash of the repo index contents
- check the transaction number from repo index filename `index.NNN`
- checks for a commit at the end of segment file NNN

If that is all fine, borg will consider the transaction to have completed successfully.

**Comment by brainchild0** [comment]
Truncation and deletion should be quick to detect, if the storage format is designed robustly.

Zeroing is more tricky, but if application  detects an incomplete transaction,  its  suggests that the repository should be scanned for loss. 

One way to handle   the case of an incomplete transaction is to abort the current command, and  then to issue a choice, of whether to perform a full scan, or to skip the scan (and simply roll back the transaction).

I think this design is a good solution.

I think the warning against using file systems that are not journaled is not necessary. If feels alarmist and not relevant the the application limitations. It is to me the same as a warning not to store a portable hard disk inside a  hot car. It's true, but off topic.

**Comment by ThomasWaldmann** [comment]
No, what matters is how it really works and if there is a chance one does not know all the details of fs implementations (I don't), one rather plays on the safe side.

**Comment by ThomasWaldmann** [comment]
@enkore I suspect you have written that paragraph, maybe you could contribute your PoV.

**Comment by brainchild0** [comment]
> No, what matters is how it really works

I was just suggesting that if no one knows the origin of the passage,  then it is reasonable to consider revising it based on a current consensus.
