### ISSUE TITLE
Borg 1.2.2 binary on Synology NAS: Error loading Python lib '/opt/tmp/_MEIDZ0axt/libpython3.9.so.1.0'

### ISSUE THREAD

**Issue by kosli** [borgbackup/borg#7091]
I have run into a similar error when upgrading borg from 1.1.18 to 1.2.2 on a synology NAS as in #6339 

Would I need to install python or some python libraries in addition on the synology NAS?

**Comment by ThomasWaldmann** [comment]
Where did you get the binary from and what is its sha256 checksum?

**Comment by kosli** [comment]
> Where did you get the binary from and what is its sha256 checksum?

https://github.com/borgbackup/borg/releases/download/1.2.2/borg-linux64
29f68bd4f8b524f0c2c530d5679ea1a7fcce6bb6ffe16dbe7d07b19dbebf794a  borg-linux64

**Comment by kosli** [comment]
fyi, same result with 1.2.0 and 1.2.1

**Comment by ThomasWaldmann** [comment]
You do not need to install python separately, it is contained in the binary.

You can try the old/new binary also, you can try using the directory mode binary (*.tgz), which does not need to unpack itself into the temp dir.

**Comment by ThomasWaldmann** [comment]
You can also try the 1.1.11 borg-linuxold64 in can you need something compatible with a very old glibc (see also the README right besides the binaries).

**Comment by kosli** [comment]
@ThomasWaldmann  Thanks. I didn't see the linuxold/new binaries before. The borg-linuxold64 (https://github.com/borgbackup/borg/releases/download/1.2.2/borg-linuxold64) works fine. 
What exactly is the difference on the linux64, linuxold64 and linuxnew64 binaries?

**Comment by ThomasWaldmann** [comment]
That's documented in the `00_README.txt` file available with the binaries.
