### ISSUE TITLE
borg extract very slow

### ISSUE THREAD

**Issue by TheCherry** [borgbackup/borg#7092]
Borg 1.2.2

Here is a very slow example, that should work faster.

Create a file with truncate:
`truncate -s 10GB testfile.dat`

Upload it to a Repo, after that you see that the deduplication and compressed size is very very small:
```
                       Original size      Compressed size    Deduplicated size
All archives:               10.00 GB             39.28 MB             37.05 kB

                       Unique chunks         Total chunks
Chunk index:                       4                 1195
```

But then you extract that file it needs a very long time to do this. Its delete even the original file (that is unchanged) and extract then the testfile. I think a checksum makes here sense? And if the deduplicated size is that small, in theory, it should be much much faster to extract the file?

--- EDIT
OK `--sparse` helps here out. But that helps only for null chunks ...

So I created a new test file (its a 7.5G file with only a unique 256 patern) : 
```python
data = "".join([chr(item) for item in range(0,255)])

target = int((5 * 1024 * 1024 * 1024) / len(data))
to_write = (data*target).encode()

with open("testfile.dat", "wb+") as f:
    f.write(to_write)
```

Now the info tells me that:
```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:               18.04 GB             71.24 MB              6.44 MB

                       Unique chunks         Total chunks
Chunk index:                     198                 2156
```

And then `--sparse` don't help again.
And that a check with a checksum is missing is realy strange, that he delete just the file even if there is no differences.

**Comment by ThomasWaldmann** [comment]
Sure, `--sparse` only helps for files that contain longer ranges of all-zero which can be optimized by writing sparse file ranges (== not really writing data to disk, just seeking), no surprise here.

So, what's left here to do? What do you mean by "a checksum is missing"?

**Comment by TheCherry** [comment]
I mean, then the file in the archive and on harddisk is exactly the same `extract` still delete the file on the harddisk and overwrite it that is just not necessary. Like `rsync -c` do it.

**Comment by ThomasWaldmann** [comment]
The state borg extract is made to work with is an empty target directory. That's what we have in the code.

It has some minimal code to get existing files out of the way if it wants to extract something to the same place, but that's it. We already have an existing ticket to optimize extract for non-empty targets, so I am closing this.

**Comment by ThomasWaldmann** [comment]
IIRC some people have "optimized" this a bit by using `borg mount` and then rsync from the mount to the target.
