### ISSUE TITLE
restoring data, when the HDD had unreadable (pending, uncorrectable) sectors 

### ISSUE THREAD

**Issue by Golddouble** [borgbackup/borg#7100]
My HDD still works, but is no longer in the best of health.
It has some unreadable (pending, uncorrectable) sectors and it's possible, I already lost some data.

But I have made backups with borgbackup (-> Vorta) all few days.
Borgbackup version: 1.1.15-3

**So here is my question:**

**Scenario:**
-Given: I have a borgbackup snapshot from 2022-08-20
-Given: I have a borgbackup snapshot from 2022-10-23
-Given: There were **no unreadable (pending, uncorrectable) sectors** when I made the snapshot on  2022-08-20
-Given: But there were **unreadable (pending, uncorrectable) sectors** when I made the snapshot on  2022-10-23
-Given: All data in the currently affected sectors were already present on 2022-08-20 and are still present 2022-10-23 (but now affected). This means, that there are no new data, that lies in the affected sectors that were not also present in the snapshot from 2022-08-20.

**Question:** 
What happens, if I restore via Vorta the snapshot from 2022-10-23 ?

Which answer is right?
A) You will have the data from the affected sectors back, because Vorta is able to automatically fetch the unaffected data from the earlier snapshot. -> So the data is saved.
B) When you restore the snapshot from 2022-10-23, then your restored data will be affected. If you want to get back your data from the affected sectors, then you must restore the snapshot from 2022-08-20 .

Would appreciate some answer. Very interested in this. Thank you.

**Comment by ThomasWaldmann** [comment]
X. If the affected files were not changed (like: different ctime or inode number or size, see `--files-cache`) between these snapshots, borg will just reference the content chunks already present in the repo (from some earlier snapshot) and will not read their contents from disk at backup time. It will read some metadata from disk, like stat, xattrs, acls, flags.

Y. If a file has changed (or is new) and gives I/O errors when borg reads it at backup time, borg will log an ERROR and skip to the next file.

So, if X is true, your answer A will be true.

If Y is true you could have noticed it if you monitor borg's log output. In this case, some files might be missing in the newer snapshot.

**Comment by ThomasWaldmann** [comment]
Guess this is answered.
