### ISSUE TITLE
running a borg client with little free disk space

### ISSUE THREAD

**Issue by tobwen** [borgbackup/borg#7107]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
QUESTION

## Your borg version (borg -V).
borg 1.2.2

## Questions
- At which line of the code has a segment been fully written to a local repository in the CREATE process?
- Can I access the segment's filename from this function?

**Comment by pgerber** [comment]
This seems a rather odd thing to do. May I ask for what purpose you need the filename. Perhaps, there is a better solution to your problem that doesn't involve some dirty hack.

**Comment by tobwen** [comment]
## stupid situation
Actually, I wanted to keep that small since that's not an issue of Borg Backup, but let me get into details: One of my virtual machines only has 1.5 GiB free disk space left (no way to change this) and the only allowed place to upload the backup is _Microsoft OneDrive_ (contractual reasons that are unavoidable). 

## possibilities
a) use _rclone_ to mount _OneDrive_ and set clone to remove the segments as soon as they got uploaded or
b) use _rclone_ with inotify to upload the single segments and remove them as soon they got uploaded.

## problems
_rclone_ is creating the segments way too quick. So the disk is full within some seconds

## workarounds
a) setting an insanely high compression rate to get the segments created more slowly
b) use SSH with ratelimiting: `borg create --upload-ratelimit=20000 ssh://root@localhost:22/mnt/onedrive/myrepository`

## hints
The upload of the server is 20 to 40 MiB/s to _OneDrive_. A ratelimit of 200k was tested to work best here.
I don't care about overhead, which is created by high compression or the "SSH loop".

## better solutions
I wanted to add an upload function to _rclone_ in my own fork only, but I wasn't able to figure out, when a segment got finally completed.

**Comment by pgerber** [comment]
Now I'm almost sorry I asked.

> b) use rclone with inotify to upload the single segments and remove them as soon they got uploaded.

One possibility could be to use inotify to wait for a segment to be closed and then just stop Borg (i.e kill -SIGSTOP $PID), upload and remove the file and then continue Borg (kill -SIGCONT $PID). I don't think this works for reading though. If I remember correctly, Borg caches file descriptors (=keeps files open).

> a) use rclone to mount OneDrive and set clone to remove the segments as soon as they got uploaded or

I'm not at all familiar with rclone. Have you had a look at some of the option like `--vfs-cache-mode` or `--vfs-cache-max-age`.

> I wanted to add an upload function to rclone in my own fork only, but I wasn't able to figure out, when a segment got finally completed.

I believe this happens in [repository.py:1554](https://github.com/borgbackup/borg/blob/c29d4a096bba4018e14208b54fe24bdc886f4f3d/src/borg/repository.py#L1554) but I haven't thoroughly checked.

There is also a [max_segment_size](https://borgbackup.readthedocs.io/en/stable/internals/data-structures.html?highlight=max_segment_size#config-file) you could lower. Perhaps it would help. The value must be adjusted on a fresh repo, before creating any archives.

I do wonder, though, if Borg is the right choice here. It might be easier to just upload some simply archive directly to OneDrive.

**Comment by tobwen** [comment]
> Now I'm almost sorry I asked.

Yeah, that's why I tried to keep the question simple. I don't want to consume your time helping me with that silly problem.

> One possibility could be to use inotify to wait for a segment to be closed and then just stop Borg

But _Borg_ writes multiple segments, not only one. This might work updates, but not for the initial upload, since there are many big segments.

> I'm not at all familiar with rclone. 

Thanks, I'm already those vfs-settings. `rclone mount` works fine so far, but I wanted to make it more stable using `rclone move`.

> I believe this happens in [repository.py:1554](https://github.com/borgbackup/borg/blob/c29d4a096bba4018e14208b54fe24bdc886f4f3d/src/borg/repository.py#L1554) but I haven't thoroughly checked.

I've been there already, but it doesn't seem like this is called on each segment (even when it should). I've written DEBUG messages in this function, but I only got rare output. That is what made me ask the question in here :)

> I do wonder, though, if Borg is the right choice here. It might be easier to just upload some simply archive directly to OneDrive.

Actually, _Borg_ in combination with _rclone_ works fine here. I can even mount the repository and restore files from it. Sure copying the files directly to _OneDrive_ might work better, but I'm losing all the deduplication and compression features, _Borg_ offers.

**Comment by tobwen** [comment]
On IRC, someone came up with an idea, how to eliminate the SSH overhead:
```
BORG_RSH='sh -c "borg serve"' borg create --upload-ratelimit=20000 ssh://localhost/mnt/onedrive/myrepository::1
```

**Comment by ThomasWaldmann** [comment]
A machine that is short before running out of disk space is not a suitable place to use borg (neither as client nor as repo server).

About the ctrl-c issue please open a separate ticket and describe how sh differs from ssh in that respect, how to reproduce etc.

**Comment by tobwen** [comment]
> A machine that is short before running out of disk space is not a suitable place to use borg (neither as client nor as repo server).

It works perfectly. I've backed up 1.5 TB from this server within one night. From another machine, I've tested the segments, all are fine. Since the OneDrive account has 25 TB of storage, it's a nice second backup target :)

I didn't want to start a discussion about how bad the solution is or discuss, how to backup from a client on little free disk space! I really just wanted to know, where a segment gets closed. I'm therefore really irritated that you change the title.

> About the ctrl-c issue please open a separate ticket and describe how sh differs from ssh in that respect, how to reproduce etc.

Are you sure? I think it's abuse and not an issue. But you can have a look at it, of course.

**Comment by ThomasWaldmann** [comment]
It works until it needs a little more disk space for some cache or index (or until something else has filled up the disk a little more) and then it will stop working.

I short while ago, I improved ctrl-c handling so it should not kill the subprocesses (like ssh, tar, ...) too early. Maybe I have missed something?

**Comment by dagelf** [comment]
Just a note of caution... SIGSTOP and SIGCONT can cause `borg` to become defunct. I haven't dug too deep, but I imagine it can happen if the whole system suspends and resumes inbetween, and `borg` resuming before the relevant drives have woken up - or perhaps there are still some other race conditions present in the Linux kernel.  Maybe it can also happen if the underlying filesystems get remounted - I doubt `borg` will try to reopen the path on a read error. Perhaps we can implement a response to SIGINT so as to be used instead of SIGSTOP. I will open a separate discussion for that after examining the source and doing some tests...
