### ISSUE TITLE
Fix the Quick Start regarding --prefix

### ISSUE THREAD

**Issue by Matthias80** [borgbackup/borg#7109]
--prefix was deprecated (#6806) but the quickstart-guide still uses the --prefix -option (https://borgbackup.readthedocs.io/en/stable/quickstart.html)

**Comment by protocolog** [comment]
I am student of BITS Pilani, India. Please, assign me this issue.

**Comment by ThomasWaldmann** [comment]
@protocolog thanks for helping!

**Comment by protocolog** [comment]
Hi, First of all thanks for assigning me and I am new in web handling but I have little experience in Django and flask. Can you tell me how can I run the quickstart.html on my local machine to check my updates? I have gone through quickstart.rst I understand the issue.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/development.html#documentation did you read this already?

**Comment by protocolog** [comment]
Hi, I am trying to build html version using sphinx, But I am getting error in make command. I have installed the sphinx properly and still it is giving me borg._version module error. Please help me here.
@ThomasWaldmann

**Comment by ThomasWaldmann** [comment]
you need to install sphinx and also borg. usually, as a developer, one installs both into the active venv, see our install and development docs.

**Comment by protocolog** [comment]
In src/borg __init__.py you have imported _version but you don't have that file in the directory, Which is why getting error while making the HTML file. Please help me here. I have created the VEnv in pycharm(Linux). I tried to update the module but still giving error. I have gone through documentation and installed requirements.
@ThomasWaldmann

**Comment by ThomasWaldmann** [comment]
as i said, you need to **install** borg (the `_version` module will then be auto-created by `setuptools_scm`), like `pip install -e .` .

**Comment by protocolog** [comment]
Can you provide community channel link on slack?

**Comment by ThomasWaldmann** [comment]
I don't use slack for borgbackup, but you can use the issue tracker and discussions on github, the mailing list or the irc channel, see our homepage / docs for details.

**Comment by ThomasWaldmann** [comment]
Any progress here?

**Comment by ThomasWaldmann** [comment]
Fixed by #7223.

No fix needed for master, because --prefix was removed there completely.
