### ISSUE TITLE
Borg pretty slow while extracting (with encryption)

### ISSUE THREAD

**Issue by janwego** [borgbackup/borg#7110]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

Debian Bullseye (server AND client)

#### Your borg version (borg -V).

1.1.16 on both machines

#### Hardware / network configuration, and filesystems used.

ext4 filesystem / 250 mbit network. 
Storing was pretty fast (see below). Extracting it was about just 700 kbit / 7 mbit.

#### How much data is handled by borg?
```
Archive name: vzborg-108-2022_10_31-16_46_50.vma
Archive fingerprint: 0c42a72fe09b002ea9367504121ab3d62798e5b48d14fb9e866d882e067b24d8
Time (start): Mon, 2022-10-31 16:46:53
Time (end):   Mon, 2022-10-31 16:52:12
Duration: 5 minutes 19.38 seconds
Number of files: 1
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               13.35 GB              6.44 GB              3.58 GB
All archives:               13.35 GB              6.44 GB              3.58 GB

                       Unique chunks         Total chunks
Chunk index:                 1279572              2757600
```
It's one big VMA file. 

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg extract ssh://user@server:port/path/to/Backup::THE_FILE.vma

## Describe the problem you're observing.

as given above, storing on the remote server is at 250 mbit, extracting at 7 mbit.
Or maybe the remote host I/O is just bad? It's with encryption enabled.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

yes

#### Include any warning/errors/backtraces from the system logs

```
C-Z-BIG          89.61 MB/s (10 * 100.00 MB all-zero files: 11.16s)
R-Z-BIG          21.97 MB/s (10 * 100.00 MB all-zero files: 45.52s)
U-Z-BIG         209.31 MB/s (10 * 100.00 MB all-zero files: 4.78s)
D-Z-BIG         248.52 MB/s (10 * 100.00 MB all-zero files: 4.02s)
C-R-BIG          21.17 MB/s (10 * 100.00 MB random files: 47.23s)
R-R-BIG          22.78 MB/s (10 * 100.00 MB random files: 43.91s)
U-R-BIG         225.14 MB/s (10 * 100.00 MB random files: 4.44s)
D-R-BIG          98.50 MB/s (10 * 100.00 MB random files: 10.15s)
C-Z-MEDIUM      102.67 MB/s (1000 * 1.00 MB all-zero files: 9.74s)
R-Z-MEDIUM       22.12 MB/s (1000 * 1.00 MB all-zero files: 45.21s)
U-Z-MEDIUM      247.87 MB/s (1000 * 1.00 MB all-zero files: 4.03s)
D-Z-MEDIUM      259.16 MB/s (1000 * 1.00 MB all-zero files: 3.86s)
C-R-MEDIUM       19.93 MB/s (1000 * 1.00 MB random files: 50.17s)
R-R-MEDIUM       23.22 MB/s (1000 * 1.00 MB random files: 43.06s)
U-R-MEDIUM      247.56 MB/s (1000 * 1.00 MB random files: 4.04s)
D-R-MEDIUM      119.10 MB/s (1000 * 1.00 MB random files: 8.40s)
C-Z-SMALL        14.42 MB/s (10000 * 10.00 kB all-zero files: 6.93s)
R-Z-SMALL        13.15 MB/s (10000 * 10.00 kB all-zero files: 7.60s)
U-Z-SMALL        19.28 MB/s (10000 * 10.00 kB all-zero files: 5.19s)
D-Z-SMALL        22.78 MB/s (10000 * 10.00 kB all-zero files: 4.39s)
C-R-SMALL        10.02 MB/s (10000 * 10.00 kB random files: 9.98s)
R-R-SMALL        12.67 MB/s (10000 * 10.00 kB random files: 7.90s)
U-R-SMALL        15.98 MB/s (10000 * 10.00 kB random files: 6.26s)
D-R-SMALL        17.76 MB/s (10000 * 10.00 kB random files: 5.63s)
```

**Comment by infectormp** [comment]
You are using pretty old version of borg. Please update to latest version and try to reproduce the problem.

**Comment by janwego** [comment]
Hi infectormp.
thanks for your reply - updating to 1.2.2 sadly didn't help, same behaviour as before, not getting over 700-800 kbit while extracting. CRUD-values are even worse than before, maybe this is because of the evening-times.

Best regards,

Jan

**Comment by infectormp** [comment]
In the case of remote extraction, we have several factors that can affect the speed:
1.Networl load/Bandwidth capacity
2.I/O on remote HDD
2.CPU load on remote host in case of using encrypted HDD

So, this issue is out of borg I think.

**Comment by ThomasWaldmann** [comment]
It might be that archive extraction is not yet as optimised as archive creation (simply because it is used less often). Maybe some more experiments are needed here to specifically find where the problem is located precisely / what influences the extraction rate.

**Comment by janwego** [comment]
Hi Thomas,
thanks for pointing that out - I'm playing a bit with the compression right now because adding and extracting a 1 GB Testfile works like a charm. 
Best wishes,

Jan

**Comment by ThomasWaldmann** [comment]
Just some hints about probabilities of some potential causes for slowness:
- encryption: unlikely (assuming that you have a decent CPU including hw accelerated AES)
- authentication/hashing: unlikely (assuming a decently fast CPU)
- disk I/O: should be ruled out by using a fast SSD without much other load
- compression: you should use lz4 compression (default) within the scope of this issue (of course an expensive compression will be slower, but that is expected)
- outside of borg reasons: like machine load, connection congestion, connection throughput issues - these should be ruled out as borg can do nothing about these.
- connection latency: this would be interesting to look at, what influence does it have on overall throughput?
- connection related overheads: maybe interesting for lots of small files/chunks
- borg bugs / scalability issues: maybe interesting

**Comment by ThomasWaldmann** [comment]
@janwego did you find out something?
