### ISSUE TITLE
Repo size on disk up to 56 times larger than "all archives deduplicated size"

### ISSUE THREAD

**Issue by eta-orionis** [borgbackup/borg#7126]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question, possibly bug

#### Your borg version (borg -V).
borg 1.2.0 on Synology (armada CPU)

#### Operating system (distribution) and version.
DSM 6.24 

#### Hardware / network configuration, and filesystems used.
Synology DS218j, ext4 on LVM RAID

#### How much data is handled by borg?
500GB in several repos

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg info

## Describe the problem you're observing.
For all of my repos, the repo size on disk is from 1.2 to 56 times larger than the "all archives deduplicated size"

I have read the docs on borg info and, if I understood correctly, the "all archives deduplicated size" is more or less the size on disk. What can explain the discrepancy, especially since the difference is not a constant factor?

Here an example:

```
$ du -d 1 -h repo-name
8.8G    scm

$ borg info repo-name
Using a pure-python msgpack! This will result in lower performance.
<...redacted...>
Encrypted: No
<...redacted>
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:               11.97 GB              5.07 GB            157.27 MB

                       Unique chunks         Total chunks
Chunk index:                    2858               140353
```

And here's a summary for the other repos:

|Repo |Deduplicated size  | Size on disk |
| ----|------------------ | -------------|
| 1 | 157.27M	| 8.8G	|
| 2 | 26.69M	| 172M	|
| 3 | 38.92G	| 129G	|
| 4 | 16.38G	| 31G	|
| 5 | 15.76G	| 69G	|
| 6 | 92.56G	| 118G	|

**Comment by ThomasWaldmann** [comment]
If you `du` the repo dir, it also includes e.g. the repo index - that might explain some (minor) difference. The chunks are in `repo_dir/data`.

Do you have your repos in **append-only** mode (see `repo_dir/config` and also `authorized_keys` file where this also can be enforced)?

Since switching to borg 1.2 (assuming you started with < 1.2), did you ever run `borg compact`? That is required for borg >= 1.2 to actually free disk space, see docs / changelog.

**Comment by ThomasWaldmann** [comment]
There's also a problem with your `python-msgpack`. It is slower, because the C implementation of msgpack was not compiled and thus it uses the slower Python implementation of that code.

**Comment by ThomasWaldmann** [comment]
Also, there is borg 1.2.2 - if it is not available as package yet, maybe bump some maintainer.

**Comment by eta-orionis** [comment]
Thank you! The repos were not in append-only mode, but I did enforce append-only in the `authorized_keys` file and had not read the new behavior from borg 1.2 that needs compacting after deletes. I'm compacting now and space is being freed.
(Can't do much for the `python-msgpack` message unfortunately, there's no better library for my NAS)
