### ISSUE TITLE
PPA for UBUNTU and homebrew for Linux

### ISSUE THREAD

**Issue by lamyergeier** [borgbackup/borg#7132]
The PPA mentioned in the official docs is: [[borgbackup backports : Gianfranco Costamagna](https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup)](https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/borgbackup)

I wanted to know if this is an official PPA or not?

Currently the homebrew installation on Linux also does not support fuse `brew install borgbackup`.
Borg complains as follows:

![image](https://user-images.githubusercontent.com/42092626/200175838-750ffa62-5aa8-4566-9ea4-22cc1d6e7f68.png)

I know that on MAC-OS the macfuse was removed, but can the homebrew on linux install it completely with the FUSE support?

I am using the homebrew as I am not sure if PPA is official, but it would be nice to use homebrew version.

**Comment by infectormp** [comment]
Official docs here https://borgbackup.readthedocs.io/en/stable/installation.html. Also here you can find macOS section.

**Comment by ThomasWaldmann** [comment]
Interesting, I didn't know homebrew is on Linux, too (only knew it is a thing on macOS).

**Comment by lamyergeier** [comment]
> Official docs here https://borgbackup.readthedocs.io/en/stable/installation.html. Also here you can find macOS section.

@infectormp  I am not interested in macOS. I want to install latest borgbackup on Linux and since homebrew installation works quite fine on linux, I just wanted it to add fuse functionality for Linux.

**Comment by lamyergeier** [comment]
> Interesting, I didn't know homebrew is on Linux, too (only knew it is a thing on macOS).

@ThomasWaldmann  Please install it using brew, its super easy on Linux. And has the advantage of staying up to date and not depending on untrusted builds.

**Comment by infectormp** [comment]
@lamyergeier Why don't you use the official package manager provided by the OS you are using? You can find the status of borg packages in repositories on the page I mentioned earlier and use package manager provided by the OS to install it. 
Have you tried the installation method provided for macOS? It uses brew.

**Comment by lamyergeier** [comment]
Ubuntu apt package is not updated anymore for the LTS version.

Yes, i know about macos. But i am using homebrew on Linux.

**Comment by ThomasWaldmann** [comment]
@lamyergeier it is ubuntu (and debian) policy that for a stable ubuntu release, the packaged software versions are usually not upgraded, but only patched if there is a security or other major issue.

but the ppa you found is from the same maintainer and provides more recent borg versions.

**Comment by lamyergeier** [comment]
Thanks. Will it be possible to include fuse for homebrew for Linux users.

**Comment by ThomasWaldmann** [comment]
@lamyergeier we have a homebrew formula there for macOS, including FUSE.

https://github.com/borgbackup/homebrew-tap/blob/master/Formula/borgbackup-fuse.rb

Note sure who maintains the Linux homebrew formula? I am not familiar with homebrew packaging...

@m3nu do you know?

**Comment by ThomasWaldmann** [comment]
There is the default homebrew formula: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/borgbackup.rb

**Comment by lamyergeier** [comment]
Hopefully the maintainer of the formula can enable fuse for linux. Unfortunately, I don't have any experience with this.

**Comment by m3nu** [comment]
The official Homebrew formula is maintained somewhat "collectively". I've seen many people edit it. Do consider that they don't want FUSE support for macOS due to licensing. But you're probably welcome to adjust it for Linux.
