### ISSUE TITLE
Control file size of output files

### ISSUE THREAD

**Issue by jankap** [borgbackup/borg#7137]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

v1.2.0

#### Operating system (distribution) and version.

WSL, Ubuntu 22.04

#### How much data is handled by borg?

300 MB

## Describe the problem you're observing.

I'm working on a file system that has quotas per file, i.e. a file must not be > 100 MB. Is it possible to automatically split the files under `data/0/...` to a pre-defined size? `--chunker-options` seem not to help and quotas are repository-wide.

Any workarounds?

Thank you so much!

**Comment by ThomasWaldmann** [comment]
Just have a look into `repo_dir/config` after `borg init`.

**Comment by jankap** [comment]
> Just have a look into `repo_dir/config` after `borg init`.
> 
> For local repos, you can set values using `borg config`.

Awesome, found it.

![image](https://user-images.githubusercontent.com/12893844/200350805-d09894b1-9da8-489c-9743-152e2352ba14.png)

With the right keyword `max_segment_size`, there's much information that can be found. Without it was difficult.

Thanks!
