### ISSUE TITLE
How to convert to a repokey?

### ISSUE THREAD

**Issue by rustyrussell** [borgbackup/borg#7143]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

Ubuntu 22.10, both ends.

#### Your borg version (borg -V).

borg 1.2.0

#### Operating system (distribution) and version.

Ubuntu

## Describe the problem you're observing.

I went to restore to a new laptop, only to discover I needed the local key in .config.  Fortunately, not a real emergency, but I obv created the server repo without a repokey.

I could not find anything on how to convert an existing repository to a repokey?  Meanwhile I used "key export" to keep a copy on my server, but that seems awkward.

Thanks in advance!

**Comment by ThomasWaldmann** [comment]
What you likely need is `borg key change-location` , but that is not yet available in a released borg version (will likely come in borg 2.0).

https://borgbackup.readthedocs.io/en/2.0.0b1/usage/key.html

**Comment by ThomasWaldmann** [comment]
Also, when switching to borg 2, you will need to create new repos anyway, so you can also choose the right key location at that time. And then, if you like, you can `borg transfer` archives from your old repo to the new repo.

**Comment by rustyrussell** [comment]
Thanks, this has been very helpful!
