### ISSUE TITLE
Being able to backup files from SFTP to a repository

### ISSUE THREAD

**Issue by Ethorbit** [borgbackup/borg#7153]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Feature request

#### Your borg version (borg -V).
borg 1.2.2

#### Operating system (distribution) and version.
Arch Linux 
kernel 5.15.79-1-lts

#### Hardware / network configuration, and filesystems used.
Not relevant

#### How much data is handled by borg?
Not relevant

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
Not relevant

## Describe the problem you're observing.
Borg doesn't seem to have any built-in functionality for backing up files from SFTP to a repository. 

While we COULD use a thirdparty tool to create an SFTP mountpoint; SSHFS is buggy, slow and is no longer being developed, and Rclone mounts don't preserve permissions and symlinks. I don't see any good way of doing this.

While we COULD sync a directory from SFTP to a local directory and then back that up with Borg, all files would be stored twice which would be bad for both storage and speed.

It just makes more sense if Borg could do this itself.

**Comment by ThomasWaldmann** [comment]
borg needs filesystem access to the files it should back up.
developing and integrating an sftp filesystem / sftp client into borg is out of scope of borg.

what you can do to solve your problem:
- run borg on the system that has the files, so you do not need sftp
- try to support the development / maintenance of sshfs (or whatever you used until now)

**Comment by someone-somenet-org** [comment]
sshfs works pretty well tho.

**Comment by Ethorbit** [comment]
> sshfs works pretty well tho.

sshfs is ridiculously slow compared to rsync. 
I've switched to rsnapshot and it has been working a lot better.

* With Borg and sshfs, archive took an hour
* With rsnapshot, archive took 15 minutes.
