### ISSUE TITLE
Unusuable repo after full disk

### ISSUE THREAD

**Issue by mw-cyrano** [borgbackup/borg#7158]
Hello,

a full disk incident broke a repository here.

```
$ /usr/local/bin/borg --version
borg 1.2.2
$ /usr/local/bin/borg check --repair /mnt/<path removed>
Exception ignored in: <function Repository.__del__ at 0x7fbf6c115040>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/borg/repository.py", line 190, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/borg/archiver.py", line 5159, in main
    exit_code = archiver.run(args)
  File "/usr/local/lib/python3.8/dist-packages/borg/archiver.py", line 5090, in run
    return set_ec(func(args))
  File "/usr/local/lib/python3.8/dist-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/local/lib/python3.8/dist-packages/borg/repository.py", line 200, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/local/lib/python3.8/dist-packages/borg/repository.py", line 438, in open
    self.config.read_file(fd)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 0: invalid continuation byte

Platform: Linux dav-backup 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64
Linux: Unknown Linux  #it actually is Ubuntu 20.04
Borg: 1.2.2  Python: CPython 3.8.10 msgpack: 1.0.4 fuse: llfuse 1.3.6 [pyfuse3,llfuse]
PID: 30487  CWD: /mnt/<path removed>
sys.argv: ['/usr/local/bin/borg', 'check', '--repair', '/mnt/<path removed>']
SSH_ORIGINAL_COMMAND: None

```

The repo can't be appended to or be pruned.

Any ideas?

It's not critial. We have another copy of the backup on another server. I'm only reporting this to potentially improve borg.

Best,
Matthias

**Comment by ThomasWaldmann** [comment]
Your config file seems to be not utf-8, have a look what's in there (repo_dir/config).

**Comment by ThomasWaldmann** [comment]
In general, it is know and documented that having a full filesystem is problematic and should be avoided by all means.

In the repo config, you can either set quota or set a specific space borg should leave free.

**Comment by mw-cyrano** [comment]
Thanks for the hint. The file is complete garbage.

Can it be rebuild? I have the key elsewhere. The other parameters seem trivial. I just wouldn't know where to find the ID?

**Comment by ThomasWaldmann** [comment]
You could just create a temporary new repo to get a repo config (it will have a new random id, so borg would rebuild the cache clientside).

If you used keyfile mode, you can find the correct id in the key file.

If you used repokey mode, you'll have to put the backupped key back into the repo config.

Also check if that system works correctly otherwise - borg has quite some precautions to never damage files like the repo config, not even when updating them and something goes wrong. Maybe check the repo dir if there is a temporary copy of the repo config with correct contents.

**Comment by ThomasWaldmann** [comment]
Guess this is solved?

**Comment by safinaskar** [comment]
@ThomasWaldmann , as well as I understand, this incident shows that lack of space can damage borg repo permanently. I. e. if disk fills and then the user adds more space (for example, by moving repo to another disk), the repo still remains damaged. Please, document this. This section https://borgbackup.readthedocs.io/en/2.0.0b5/quickstart.html#important-note-about-free-space does not state this clearly. Yes, it says that in case of full disk one possibly will be unable to remove old snapshots. But it doesn't say that the repo itself can be damaged

**Comment by ThomasWaldmann** [comment]
There is no clear evidence beyond what's described in that note yet. Also, what's described in that note should be sufficient to avoid out-of-space conditions by all means, right?

borg does quite some effort when updating config files to do that in the safest possible way, like:
- not damaging config files (like only partially writing them)
- always having a valid config either old or new, but nothing "in between"
- securely erasing the old config file, if possible

So, not sure how the garbage got into that config file, might be a fs issue.

As I've described above, it should be repairable manually.

**Comment by ThomasWaldmann** [comment]
when borg opens a repository, it checks whether it is in a committed (transaction completed) state. if it is not (e.g. a backup was interrupted / not completed), it rolls back to the last committed state.

that should also work for out-of-space issues after space is freed on the repo filesystem.

of course it is better to avoid out-of-space situations, e.g. by repository quota (max repo size) or keeping some space always free (min free space). See the repo config / docs.

**Comment by safinaskar** [comment]
@ThomasWaldmann , thanks for answer! So, it seems the guarantee exists. Please, write this to docs. You essentially said that after out-of-disk condition the repo is _trusted_. This is very important property. Please, write this to docs.

And what about `~/.cache/borg` filesystem? Does it have same guarantee?
