### ISSUE TITLE
vagrant: openbsd testing machine broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#716]
Somehow testing on openbsd doesn't work right now. It worked in the past and it is unclear what's the problem right now.

Issues:
- /etc/resolv.conf has non-working 127.0.1.1 entry (but manually setting it to a working nameserver also does not help)
- "vagrant up" does not install rsync automatically
- even when adding rsync manually with pkg_add rsync, "vagrant rsync openbsd64" does not synchronize the borg directory
- when running vagrant provision, llfuse installation fails with "unable to determine system"

It would be great if some openbsd user could have a look, as I can't test on openbsd until this is fixed.

**Comment by ThomasWaldmann** [comment]
I've added it to a milestone to give it more visibility. We still need somebody caring about this!

**Comment by bket** [comment]
- /etc/resolv.conf has non-working 127.0.1.1 entry (but manually setting it to a working nameserver also does not help)

What is the problem you are trying to solve? Please note that here is standard no DNS server running on 127.0.0.1.

- "vagrant up" does not install rsync automatically
- even when adding rsync manually with pkg_add rsync, "vagrant rsync openbsd64" does not synchronize the borg directory

#1698 

- when running vagrant provision, llfuse installation fails with "unable to determine system"

llfuse does not support OpenBSD. Also, #1699
