### ISSUE TITLE
have latest OS / distribution (security) fixes installed on build systems

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#717]
when building the binaries, we bundle some libraries into the single-file binary using pyinstaller.

to have all the available bug and security fixes, the OS / distribution should be up-to-date when doing the binary build.

we do binary build on linux (debian wheezy), freebsd and darwin, so these systems need to be updated first, before pyinstaller and tests run.

**Comment by jungle-boogie** [comment]
for freebsd, run these to install base system updates:
> sudo freebsd-update fetch

if there's anything to installl:
> sudo freebsd-update install

for pkgs like python, lz4, etc:
> sudo pkg update
> sudo pkg upgrade

**Comment by ThomasWaldmann** [comment]
this is what i have currently for freebsd;
```
freebsd-update --not-running-from-cron fetch install
(install some pkgs here)
pkg update
yes | pkg upgrade
```

**Comment by jungle-boogie** [comment]
I wrote some messages on irc. Yes, update the base & packages. these are two separate things on *BSD systems.
