### ISSUE TITLE
Reading mounted archive very slow initially (~2min wait)

### ISSUE THREAD

**Issue by jensb** [borgbackup/borg#7173]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug - or rather, performance issue.

#### Your borg version (borg -V), OS version, distribution, Hardware and filesystem

- 1.2.0, 
- Ubuntu 22.04 LTS jessy
- Intel i5-4570 "Haswell" from 2013, 16GB RAM (Client)
- ext4
- Synology diskstation, Borg archive mounted using SMB (Server) from ext4 fs and processed locally

#### How much data is handled by borg?

About a year of backups.
```
    ------------------------------------------------------------------------------
                           Original size      Compressed size    Deduplicated size
    All archives:               12.80 TB             12.33 TB            711.39 GB
                           Unique chunks         Total chunks
    Chunk index:                 2088988             24736320
    ------------------------------------------------------------------------------
```
#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`$ borgfs $BORG_REPO /media/jens/borgbackup`

## Describe the problem you're observing.

Mounting is fast.
`ls -l /media/jens/borgbackup` is fast.
But `ls -l /media/jens/borgbackup/any-subdirectory`
- will cause borgfs to consume a complete CPU core for minutes,
- with no noticeable network traffic (so it's not reading the whole backup or something like that),
- with no noticeable local disk traffic either.

This seems to be inside `_process_archive` (see below).

So borg seems to be stuck somewhere. 2 Minutes of CPU time is a lot and I can't imagine what this is being used for.

This happens for every first-evel subdirectory in the mountpoint which is accessed. If I use "--debug --progress -o versions", borgfs walks through all these subdirectories one by one, and logs it:

```
$ borgfs $BORG_REPO /media/jens/borgbackup/ --debug --foreground --progress -o versions
using builtin fallback logging configuration
38 self tests completed in 0.07 seconds
Verified integrity of /media/jens/Home/Backups/Linuxkiste_18.04_Borg/index.14246
TAM-verified manifest
security: read previous location '/media/jens/Home/Backups/Linuxkiste_18.04_Borg'
security: read manifest timestamp '2022-11-26T19:28:03.260417'
security: determined newest manifest timestamp as 2022-11-26T19:28:03.260417
security: repository checks ok, allowing access
mount data cache capacity: 4 chunks
Mounting filesystem
fuse: _process_archive completed in 0.0 s for archive schweizerkaese.fritz.box-2019-01-18T13:32:10
fuse: _process_archive completed in 37.7 s for archive schweizerkaese.fritz.box-2019-01-19T19:24:42
fuse: _process_archive completed in 32.0 s for archive schweizerkaese.fritz.box-2019-01-20T22:02:22
fuse: _process_archive completed in 115.3 s for archive linuxkiste-2022-03-31T22:35:02
fuse: _process_archive completed in 121.2 s for archive linuxkiste-2022-04-30T22:35:02
fuse: _process_archive completed in 112.9 s for archive linuxkiste-2022-05-31T22:35:03
... etc ...
```

#### Can you reproduce the problem? If so, describe how.

Yes, every time, using the same commands as above.

**Comment by ThomasWaldmann** [comment]
borg is on-demand loading the archive metadata as soon as you enter an archive subdirectory.

How fast it is to load an archive and build the borgfs fs structure in memory depend on archive size, speed of the machine, how fast repo access is, etc.

Some delay here is very much expected. It can be a little for small archives and fast machines or quite significant for big archives and slow machines.

**Comment by ThomasWaldmann** [comment]
If one wants to wait less, these are the options:
- do not enter archive dirs if not needed (avoid on-demand loading)
- only mount a specific archive, not the complete repo
- only mount specific paths in a specific archive, not the complete archive

**Comment by ThomasWaldmann** [comment]
Using `-o versions` will read **all** archives by default to create the version view, but you can limit this by giving options that limit the archive, like `--last 3` or `-a 'onlythese*'`.

**Comment by jensb** [comment]
Thank you for explaining. Just mounting subdirectories of an archive helps if I already know which parts of an archive I know.
Still, 2 minutes per archive for a normal desktop backup (~100GB of data) seems quite a bit of time for me.
Can you point me to the responsible code? I'm curious.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/1.2.2/src/borg/archiver.py#L1336

https://github.com/borgbackup/borg/blob/1.2.2/src/borg/fuse.py

**Comment by jensb** [comment]
Thanks! I'll have a look at this.

**Comment by ThomasWaldmann** [comment]
TODO: check if my tuning tips are already documented.
