### ISSUE TITLE
Feature Request - borg standalone working with /tmp/ noexec

### ISSUE THREAD

**Issue by SoftBrok** [borgbackup/borg#718]
I was looking to setup borg today, but I hit a brick wall due to /tmp/ being setup as noexec for security.

The standalone borg binary should definitely be allowed to work without /tmp/ being set to exec. For many servers, it is simply not an option to change this. Webhosting servers based on control panels can't be changed so easily.

**Comment by manwegit** [comment]
Have you tried:
`export TMPDIR=/some/other/dir`
Run Borg standalone

**Comment by dragetd** [comment]
We have added a note regarding this to the installation section of the docs: http://borgbackup.readthedocs.org/en/stable/installation.html?highlight=standalone#standalone-binary

You can set TMPDIR and use some temporary folder with executable permissions! :-)

**Comment by ThomasWaldmann** [comment]
Another way to avoid using the temp directory is to copy the extraction result from the binary from there (while it is running). It is a directory called `_ME*` and everything you need is in there and can be started from the copy without needing extraction to temp dir again.

**Comment by ThomasWaldmann** [comment]
BTW, requiring exec on the TEMP dir (which is not required to be /tmp) is a requirement of pyinstaller single-file binaries, it just needs a place to unpack and run the stuff.

**Comment by dynek** [comment]
Any clever way to set `TMPDIR` for the remote host as well when doing remote backup using `ssh` ?
