### ISSUE TITLE
Borg2 borg create --progress option is not documented

### ISSUE THREAD

**Issue by maurizio-emmex** [borgbackup/borg#7180]
## Have you checked borgbackup docs, FAQ, and open Github issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
borg2 -V
borg2 2.0.0b4
Note: I have symlinked borg V 2 as borg2, I can use borg V1 and V2 on the same machine.
#### Operating system (distribution) and version.
uname -a
FreeBSD clover-nas4.local 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64
#### How much data is handled by borg?
437.25 GiB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
REPO2="ssh://root@clover-nas2/zusb/borgbackup2/clover-nas4/vbox"
EXCLUDEFILE="/root/.config/my_config/borg/exclude_empty.txt"
BORG2_CREATE_OPT="--remote-path borg2 --iec -sp --show-rc -C zstd --exclude-caches --exclude-from"
borg2 create -r $REPO2 $BORG2_CREATE_OPT "$EXCLUDEFILE" "{now:%Y-%m-%dH%H}" "."

## Describe the problem you're observing.
In borg2 create the --progress option shows:
```
5.46 GiB O 5.42 GiB U 82 N VirtualBox VMs/win10_maurizio/win10_maurizio-disk1.vdi
```
not as specified in the 'borg2 help create' command:
```
The --progress option shows (from left to right) Original, Compressed and Deduplicated
(O, C and D, respectively), then the Number of files (N) processed so far, followed by
the currently processed path.
```

**Comment by ThomasWaldmann** [comment]
Yeah, the docs need an update there, they still tell the borg1 state of affairs.

borg2 does not manage the `csize` (compressed size of a chunk) at some place any more, thus some commands lost that part of the output.

O = original (uncompressed) size
U = uncompressed and deduplicated size
N = files count

**Comment by maurizio-emmex** [comment]
Thank you.

**Comment by ThomasWaldmann** [comment]
we'll keep this open until the docs are fixed.
