### ISSUE TITLE
`file changed while we backed it up` Message a bit broken

### ISSUE THREAD

**Issue by theAkito** [borgbackup/borg#7183]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes!

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.2.2

#### Operating system (distribution) and version.
Several.
Debian, Arch, NixOS..........

#### Hardware / network configuration, and filesystems used.
Various

#### How much data is handled by borg?
Various

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg --progress --verbose create --comment ... -e ... -e ... -e ... -e ... -e ... -e ... -e ... -e ... -e ... --stats ssh:/... /
```

## Describe the problem you're observing.
When a file changes during it being backed up, there is a message shown about it.
The message is _always_, on various systems, output in a bit broken way.
Example follows.

```
/wal/0000000000000005-00000000000619e2.wal: file changed while we backed it up.wal
```

Notice how the `.wal` is appended. It's the last four characters of the actual file, which changed during the backup process.

When this happened the first time, I thought this was some quirk or a fluke.
However, I have since then experienced it on multiple systems, with multiple operating systems, with multiple, completely different, hardware setups.

This **always** happens. On every single file, that changed while it was backed up. The message always appends the last few characters of the file that changed.

Most tries happened in Bash.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Change a file while it is backed up by Borg & check what borg is saying.

## Somewhat a bit related to the following issues
* https://github.com/borgbackup/borg/issues/7080
* https://github.com/borgbackup/borg/issues/6622
* https://github.com/borgbackup/borg/issues/6989
* https://github.com/borgbackup/borg/issues/6379

**Comment by ThomasWaldmann** [comment]
That might be a general issue with how misc. other output interferes with the `--progress` output, usually it doesn't end up pretty.

**Comment by ThomasWaldmann** [comment]
borg2 will disallow using `--progress` together with `--list` if not in json mode. thus, no screen or log file mess up any more.
