### ISSUE TITLE
borg2 list command produce a different output than borg V1

### ISSUE THREAD

**Issue by maurizio-emmex** [borgbackup/borg#7185]
## Have you checked borgbackup docs, FAQ, and open Github issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

small issue

#### Your borg version (borg -V).
borg2 -V
borg2 2.0.0b4

#### Operating system (distribution) and version.
uname -a
FreeBSD clover-nas4.local 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64
#### Hardware / network configuration, and filesystems used.
ZFS
#### How much data is handled by borg?
397 GiB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
echo $REPO2
ssh://root@clover-nas2/zusb/borgbackup2/clover-nas4/vbox
borg2 list -r $REPO2 --remote-path borg2 2022-12-05H16
## Describe the problem you're observing.
A line in the list has an additional space compared with the borg V1 list line eg.
```
-rw------- vboxusers vboxusers      183 Thu, 2021-04-29 17:08:33  .ICEauthority
-rw------- vboxusers vboxusers      183 Thu, 2021-04-29 17:08:33 .ICEauthority
```
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, use the borg2 list command.

**Comment by ThomasWaldmann** [comment]
"%a, %Y-%m-%d %H:%M:%S %z" this format without timezone (so %z will be replaced by empty string) is causing the "additional" space in the observed borg list output.

Considering borg2 shall work better with timezones and actually output a timezone there, this will be resolved automatically as soon as that change is merged (I am currently working on it).

**Comment by ThomasWaldmann** [comment]
This is how it looks with the code in that PR:
```
-rw-r--r-- tw     staff    106465 Sat, 2022-12-10 11:42:18 +0000 src/borg/archive.py
```
So the timestamp is given as utc time including the utc tzoffset of +0000. One space to the left of the tzoffset, one space to the right.
