### ISSUE TITLE
usage --paths-from-stdin backup result does not meet expectations. No file exists

### ISSUE THREAD

**Issue by zran-20** [borgbackup/borg#7190]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes 

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.2.2

#### Operating system (distribution) and version.
Ubuntu 18.04.3 LTS

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
find /data -maxdepth 1 -ctime 1 | borg create --stats --list /storage::save_find_result_1 --paths-from-stdin
```
## Describe the problem you're observing.
I want to find some directories that meet the requirements and use borg for backup, but I find that the byte of the backup directory is 0. Why. Does it only support file backup? Can I back up the directory recursively

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
```
root@master:/storage# find /data -maxdepth 1 -ctime 1  -exec ls -l {} \; | head -10
total 10240000
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_1
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_10
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_100
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_1000
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_101
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_102
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_103
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_104
-rw-r--r-- 1 root root 10485760 12月  7 10:00 mock_data_1_105
find: ‘ls’ terminated by signal 13
root@master:/storage# find /data -maxdepth 1 -ctime 1 | borg create --stats --list /storage::save_find_result_1 --paths-from-stdin
d /data/dir1
------------------------------------------------------------------------------
Repository: /storage
Archive name: save_find_result_1
Archive fingerprint: 32622313834dbaefd79b0d9d8a2a6773aa7718ff788d75339303588cf6bf4316
Time (start): Thu, 2022-12-08 15:50:13
Time (end):   Thu, 2022-12-08 15:50:13
Duration: 0.00 seconds
Number of files: 0
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:                  553 B                510 B                510 B
All archives:                    0 B                  0 B                591 B

                       Unique chunks         Total chunks
Chunk index:                       2                    2
------------------------------------------------------------------------------
root@master:/storage#
root@master:/storage# borg list  /storage::save_find_result_1
drwxr-xr-x root   root          0 Wed, 2022-12-07 10:01:21 data/dir1
```
![image](https://user-images.githubusercontent.com/16559017/206390633-9ccc9e1f-d255-4d50-be74-3e0411c1a3df.png)

**Comment by ThomasWaldmann** [comment]
```
d /data/dir1
```

It looks like you only gave the path of that **one** directory to borg, but not the paths of all files you wanted to back up.
So, better check the output of your find command before giving that to borg.

If you use borg with `--paths-from-stdin` borg does not recurse into directories, you have full control via stdin about what borg shall back up - but that also means that you are fully responsible for really giving all the paths of all files you want in your backup.

**Comment by ThomasWaldmann** [comment]
Could you resolve your issue?

**Comment by e64462** [comment]
> ```
> d /data/dir1
> ```
> 
> It looks like you only gave the path of that **one** directory to borg, but not the paths of all files you wanted to back up. So, better check the output of your find command before giving that to borg.
> 
> If you use borg with `--paths-from-stdin` borg does not recurse into directories, you have full control via stdin about what borg shall back up - but that also means that you are fully responsible for really giving all the paths of all files you want in your backup.

A mention of this modified behavior (from the expected default) with --paths-from-stdin would be a welcome addition to the docs.

**Comment by ThomasWaldmann** [comment]
@e64462 what do you see as "modified behaviour" and where does your "expected default" expectation come from?

IIRC, `--paths-from-stdin` (and also `--paths-from-command`) did not see any changes since it was added to borg.

This is from the borg 1.2.3 docs:
```
--paths-from-stdin   read DELIM-separated list of paths to backup from stdin. Will not recurse into directories.
```

**Comment by e64462** [comment]
somehow i missed that, i guess... or just failed to consider the consequences of it in my own deployment. You're spot on though, decidedly not a developer. Thanks anyway

**Comment by ThomasWaldmann** [comment]
There was some recent change to the docs of `--paths-from-stdin`:

read DELIM-separated list of paths to backup from stdin. 
***All control is external: it will back up all files given - no more, no less.***

Guess that is clear enough now.
