### ISSUE TITLE
borg --comment does not work with curly braces

### ISSUE THREAD

**Issue by Shchegolyaev** [borgbackup/borg#7207]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG 

## System information. For client/server mode post info for both machines.

Ubuntu 22.04.1 LTC // Debian GNU/Linux 11 (bullseye)

#### Your borg version (borg -V).

1.2.0 // 1.1.16

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
comment=exa{mp}le
borg create --comment "$comment" $backups_path::$backup_name /  --exclude=/home/sergey/PycharmProjects
Invalid placeholder "mp" in string: exa{mp}le
```

The problem was not observed in version 1.1.9. I noticed it by updating to 1.1.16

**Comment by ThomasWaldmann** [comment]
That's a feature, not a bug. You can use placeholders like `{hostname}` in comments.
