### ISSUE TITLE
GLIBC_2.28 not found 

### ISSUE THREAD

**Issue by devZer0** [borgbackup/borg#7208]
on centos 7 , i'm getting

```
# ./borg-1.2.2
[22647] Error loading Python lib '/tmp/_MEIonDdbY/libpython3.9.so.1.0': dlopen: /lib64/libc.so.6: 
version `GLIBC_2.28' not found (required by /tmp/_MEIonDdbY/libpython3.9.so.1.0)
```
for borg 1.2.2 from releases download at https://github.com/borgbackup/borg/releases/tag/1.2.2

**Comment by infectormp** [comment]
look like you have glibc lower then 2.28

**Comment by devZer0** [comment]
yes i do. centos7 has such old one

**Comment by devZer0** [comment]
that's what i did. the 1.1.18 fat binary works fine

**Comment by infectormp** [comment]
did you try borg-linux64 or borg-linuxnew64?

**Comment by devZer0** [comment]
i tried borg-linux64, but thanks for the pointer, i tried borg-linuxold64 and that works. didn't notice that it should have been the one to use. just got to used too always downloading borg-linux64

**Comment by realrobgit** [comment]
Dear all, 
I installed the package BorgBackup_1.2.2.1_arm-x19.qpkg from https://www.myqnap.org/product/borg-backup/ on my QNAP TS 421 Firmware 4.3.3.2211 
Installation works. BUT when I SSH to the machine and try to execute borg it brings:  [admin@NASDSTF ~]# borg
[27163] Error loading Python lib '/tmp/_MEI85VzZV/libpython3.8.so.1.0': dlopen: /lib/libc.so.6: version `GLIBC_2.10' not found (required by /tmp/_MEI85VzZV/libpython3.8.so.1.0)

I then checked the ldd version: 

[admin@NASDSTF ~]# ldd --version
ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

Any idea how I can bring Borg to work? Thx in advance!

**Comment by infectormp** [comment]
@devZer0 try to download `borg-linuxold64` from there https://github.com/borgbackup/borg/releases

**Comment by ThomasWaldmann** [comment]
@infectormp They have a ARM based machine, the x64 binaries from borgbackup's github releases won't work.

**Comment by ThomasWaldmann** [comment]
@realrobgit You can try this if you do not find a better qnap (ARM) borg package:

https://borg.bauerj.eu

**Comment by realrobgit** [comment]
Hi Thomas, 
Thats a good guess!Thx - I´´ll try that in the evening! Best yours!

**Comment by realrobgit** [comment]
Thx again but still dont workin with none of the installation. hmm another idea?

**Comment by ThomasWaldmann** [comment]
@realrobgit well, of course you could ask whoever built that qnap package you tried, but which didn't work.

The problem with such NAS systems is they rather often use somehow proprietary and/or rather old/limited operating systems.

How much RAM does your qnap NAS have? If it is rather little, maybe you could rather use a cifs or nfs share exported by the NAS and just run borg only on the clients.
