### ISSUE TITLE
check compatibility with llfuse 1.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#722]
from the changelog, it does not look like 1.0 causes problems for borg, but better check.

if it works, adapt requirements file and setup.py.

**Comment by LocutusOfBorg** [comment]
with llfuse 1.0 in Debian this might become a problem :)

**Comment by dannyedel** [comment]
Borg seems™ to work correctly with `python3-llfuse 1.0+dfsg-1` from Debian sid.
I tried interactive usage and also a crude [automated fuse session][1] I use to verify basic mount/readfile works.

[1]: https://anonscm.debian.org/cgit/collab-maint/borgbackup.git/tree/debian/tests/simplesession

**Comment by ThomasWaldmann** [comment]
Fixed by PR #726.
