### ISSUE TITLE
Can't backup anymore after big prune action on the repo, backup ends with `MemoryError`

### ISSUE THREAD

**Issue by christophehenry** [borgbackup/borg#7226]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

1.2.0, Vorta 0.8.9 installed with Flatpak

#### Operating system (distribution) and version.

Linux Fedora 36

#### Hardware / network configuration, and filesystems used.

Backing up on a Synology hosted on local network. Borg is installed on Synology using the Syno community package. Now version 1.2.1 but at some point during last week was 1.2.2 [to test the update pull request](https://github.com/SynoCommunity/spksrc/pull/5500/files). The problem appeared after several days of using 1.2.2 from the PR and has persisted since then.

#### How much data is handled by borg?

~1.5To

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
app/bin/borg create --remote-path=/usr/local/bin/borg --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmpwqyoo_zw ssh://<path_to_backup_on_remote_::<backup_name> <home>
```

## Describe the problem you're observing.

I've been using Borg to bakcup my home directory for several months on my Synology NAS. on the 9th of december I updated borgbackup and borgmatic on the NAS [using this code](https://github.com/SynoCommunity/spksrc/pull/5500/files). On the 21 of december I performed a big prune on the repo after fixing incorrect prune settings that led to keep far too many backups (~20). After this prune, only 10 archive remained. Since then, every backup end with a `MemoryError`.

At first other commands were failing too. Like mounting an archive (using Vorta) didn't fail with an error but hang for a long time then indicated was mounted but trying to navigate the files with Dolphin made my system to freeze. I first tried to remove borg from the NAS and reinstall the stable version. This fixed mounting archives for backing up with `borg create` still ends with a `MemoryError` after a long exectution time.

I also tried `borg compact` directly on the NAS. This reduces `borg create` execution time but it still ends with a `MemoryError`. At that point, I can mount previous archives so I suppose I can restore from existing archives but I can't make new backups.

#### Include any warning/errors/backtraces from the system logs

Stacktrace from Vorta's logs:

```
Traceback (most recent call last):

  File "<path_to_borg_install_on_NAS>/env/lib/python3.10/site-packages/borg/remote.py", line 240, in serve
    res = f(**args)

  File "<path_to_borg_install_on_NAS>/env/lib/python3.10/site-packages/borg/repository.py", line 1241, in delete
    self.prepare_txn(self.get_transaction_id())

  File "<path_to_borg_install_on_NAS>/env/lib/python3.10/site-packages/borg/repository.py", line 558, in prepare_txn
    self.index = self.open_index(transaction_id, auto_recover=False)

  File "<path_to_borg_install_on_NAS>/env/lib/python3.10/site-packages/borg/repository.py", line 526, in open_index
    return NSIndex.read(fd)

  File "src/borg/hashindex.pyx", line 114, in borg.hashindex.IndexBase.read

  File "src/borg/hashindex.pyx", line 99, in borg.hashindex.IndexBase.__cinit__

  File "<path_to_borg_install_on_NAS>/env/lib/python3.10/site-packages/borg/crypto/file_integrity.py", line 32, in read
    return self.fd.read(n)

  File "<path_to_borg_install_on_NAS>/env/lib/python3.10/site-packages/borg/crypto/file_integrity.py", line 82, in read
    data = super().read(n)

  File "<path_to_borg_install_on_NAS>/env/lib/python3.10/site-packages/borg/crypto/file_integrity.py", line 32, in read
    return self.fd.read(n)

MemoryError
```

**Comment by ThomasWaldmann** [comment]
MemoryError means that borg (python) can't allocate enough memory.

The traceback shows it happens while loading the repository index.

How much RAM / swap do you have? Can you increase it?

**Comment by ThomasWaldmann** [comment]
I don't think this has anything to do with the PR code you mentioned or the fact you switched between misc borg 1.2.x versions.

It's like just that you have been close to the limits and at some time, you have gone beyond your machine's limit (or something else is now using more memory, so it is not available for borg any more).

**Comment by christophehenry** [comment]
What memory limits? Are we talking about RAM or HDD? If the latter, I have plenty of memory available. If we're talking about RAM, then nothing should've changed in the environment: it's just a NAS there's not much processes running to eat uo the memory. Why is it always failing now? And what can I do to remedy?

**Comment by ThomasWaldmann** [comment]
RAM. borg needs to be able to load misc. hash tables (repo index [on the borg repo server side], chunks index and files cache [on the borg client side]) into memory.

As your repo grows (has increasing amount of chunks), the repo index and the chunks index grow accordingly.
Also, if the count of input files grows, the memory needs of the files cache grows also.
There's a formula in the docs.

What you can try is to increase swap. It will be very slow, but it might work again.

The real solution is to use a machine that has enough real RAM. Or to create smaller repos.

So, how much RAM does you NAS have?

Output of that command?:
```
ls -lh repo_directory/index*
```

**Comment by christophehenry** [comment]
> As your repo grows (has increasing amount of chunks), the repo index and the chunks index grow accordingly.
Also, if the count of input files grows, the memory needs of the files cache grows also.

But shouldn't have this be solved by the sucessful `borg compact`?

>Output of that command?:
> `ls -lh repo_directory/index*`

```
-rwxrwxrwx+ 1 **** **** 629M Dec 25 18:31 repo_directory/index.11095
```

**Comment by ThomasWaldmann** [comment]
I don't think `borg compact` changes the repo index size (it rather frees space of segments that are not in the index any more already).

So your index size is 629MB and your RAM is 512MB (parts of which is used by other processes and the kernel), there you have the problem.

Together with the 2G of swap it might work, but you're rather close to the limit, so it can happen again (e.g. if more chunks come into the index and it has to resize the hashtable).

If the memory is upgradable, I'ld suggest putting in 8 or 16GB.

**Comment by christophehenry** [comment]
Meh… Ok, thank you for the help.

**Comment by ThomasWaldmann** [comment]
If the memory is not upgradable, you could run borg completely client-side and have the repo inside a NFS or cifs share exported by the NAS. Then borg won't need RAM on the NAS side.

**Comment by ThomasWaldmann** [comment]
OK, i think this issue can be closed. borg needs enough RAM to be able to work.

**Comment by christophehenry** [comment]
Thank you for your help.
