### ISSUE TITLE
Linux: When there are multiple borg backups in bash script, the script is cancelled after completion of first command

### ISSUE THREAD

**Issue by jbrepogmailcom** [borgbackup/borg#7244]
## Have you checked borgbackup docs, FAQ, and open Github issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

## System information. For client/server mode post info for both machines.

Linux / Ubuntu 22.04

#### Your borg version (borg -V).

1.2.0

#### Operating system (distribution) and version.

Ubuntu 64 bit 22.04

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

sudo borg create --exclude /*cache*/ --exclude /*Cache*/ --stats --progress --compression auto,zstd,22 --exclude /home/janbenes/.steam/debian-installation --exclude /home/janbenes/Downloads --exclude /home/janbenes/.recoll --exclude /home/janbenes/.snapshots --exclude /.snapshots --exclude /home/janbenes/.cache --exclude /home/.ecryptfs pi@raspiserver4.local:/RAID3T/BACKUPS/Borg/T4-Ubuntu-Borg::$(date "+%FT%H-%M-%S")-home /home/janbenes

## Describe the problem you're observing.

There are multiple borg backup commands in backup.sh script. Until some time ago, all borg commands performed one after another. Since some months ago, only first borg backup is performed and then bash scripts ends to command line, quite like it has ran to the end.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Always

**Comment by ThomasWaldmann** [comment]
This is not a borg bug, but bad borg result code handling.

rc = 0 means OK, 1 means WARNING, 2 means ERROR.

Likely your script terminates for rc = 1, which it should not in this case.

**Comment by ThomasWaldmann** [comment]
BTW, if you'ld use the borg PPA, you could get a more recent borg for ubuntu (from same package maintainer).

**Comment by ThomasWaldmann** [comment]
Guess this is solved.

**Comment by ThomasWaldmann** [comment]
@KavkaTSR likely the same solution, see https://github.com/borgbackup/borg/issues/7244#issuecomment-1374869355 - you shouldn't terminate the script if borg returns rc 1.

**Comment by KavkaTSR** [comment]
> @KavkaTSR likely the same solution, see [#7244 (comment)](https://github.com/borgbackup/borg/issues/7244#issuecomment-1374869355) - you shouldn't terminate the script if borg returns rc 1.
I checked it first - rc is zero.
Prety strange situation. May be it is not borgbackup issue because involved two more programs, plus scripts.
Decided to leave comment here, may be it will help someone.
