### ISSUE TITLE
Backup speed limited by borg on fast disk and ramdisk

### ISSUE THREAD

**Issue by oernii** [borgbackup/borg#7253]
## Have you checked borgbackup docs, FAQ, and open Github issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
QUESTION

## System information. For client/server mode post info for both machines.
server E5-2470 v2 , 128GB RAM,
source: 2x10g NVMe storage multipath
repo: tmpfs

#### Your borg version (borg -V).
borg 1.2.3
borg 2alpha

#### Operating system (distribution) and version.
RockyLinux9

#### How much data is handled by borg?
souce 20GB disk NVMe iscsi disk
repo 50GB RAMdisk

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
- trying to backup a big disk image
dd if=/dev/remote/nvmedisk bs=16M |  borg-linuxnew64 create -v --stats --repo /mnt/tmpfs/ -C none TestCreate1 - 

## Describe the problem you're observing.
overall borg backup speed does not exceed 130MB/s, while the source and repo are capable of 1400MB/s. No compression
Enabling zstd compression lowers the performance to 115MB/s.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes

#### Include any warning/errors/backtraces from the system logs
CRUD benchmark:
C-Z-BIG         449.42 MB/s (10 * 100.00 MB all-zero files: 2.23s)
R-Z-BIG         220.55 MB/s (10 * 100.00 MB all-zero files: 4.53s)
U-Z-BIG        1915.50 MB/s (10 * 100.00 MB all-zero files: 0.52s)
D-Z-BIG        3006.81 MB/s (10 * 100.00 MB all-zero files: 0.33s)
C-R-BIG         142.45 MB/s (10 * 100.00 MB random files: 7.02s)
R-R-BIG         226.23 MB/s (10 * 100.00 MB random files: 4.42s)
U-R-BIG        1200.11 MB/s (10 * 100.00 MB random files: 0.83s)
D-R-BIG        2885.55 MB/s (10 * 100.00 MB random files: 0.35s)
C-Z-MEDIUM      643.17 MB/s (1000 * 1.00 MB all-zero files: 1.55s)
R-Z-MEDIUM      232.27 MB/s (1000 * 1.00 MB all-zero files: 4.31s)
U-Z-MEDIUM     1903.72 MB/s (1000 * 1.00 MB all-zero files: 0.53s)
D-Z-MEDIUM     2950.74 MB/s (1000 * 1.00 MB all-zero files: 0.34s)
C-R-MEDIUM      155.90 MB/s (1000 * 1.00 MB random files: 6.41s)
R-R-MEDIUM      224.78 MB/s (1000 * 1.00 MB random files: 4.45s)
U-R-MEDIUM     1874.15 MB/s (1000 * 1.00 MB random files: 0.53s)
D-R-MEDIUM     2656.56 MB/s (1000 * 1.00 MB random files: 0.38s)
C-Z-SMALL        35.59 MB/s (10000 * 10.00 kB all-zero files: 2.81s)
R-Z-SMALL        61.93 MB/s (10000 * 10.00 kB all-zero files: 1.61s)
U-Z-SMALL        36.58 MB/s (10000 * 10.00 kB all-zero files: 2.73s)
D-Z-SMALL       186.79 MB/s (10000 * 10.00 kB all-zero files: 0.54s)
C-R-SMALL        25.54 MB/s (10000 * 10.00 kB random files: 3.92s)
R-R-SMALL        63.14 MB/s (10000 * 10.00 kB random files: 1.58s)
U-R-SMALL        37.49 MB/s (10000 * 10.00 kB random files: 2.67s)
D-R-SMALL       155.44 MB/s (10000 * 10.00 kB random files: 0.64s)

DD from source->repo goes at a rate of 1263 MB/s

**Comment by infectormp** [comment]
DD shows just IO speed without any overheads, but borg doing a lot of operation: `borg create: does chunking, hashing, compression, crypto (high CPU usage)` and also borg doesn't support multithreading yet.

**Comment by ThomasWaldmann** [comment]
What you see in practice somehow corresponds to the C-R-BIG 142.45 MB/s benchmark.

Some optimisation hints:
- use lz4 compression, it usually has a positive impact
- use the `fixed` chunker with 1..8MiB block size (this consumes less cpu than the default `buzhash` chunker)
- if you use encryption in the repo, make sure AES is hw accelerated, esp. if you use a VM
- check whether blake2b or hmac-sha256 is faster on your machine (see `borg init`)

borg will never get as fast data transfer as dd or rsync, because it does much more.

but in practice it is still often very fast, because it deduplicates and does not process data again which it already has in the repo.

You can also try the latest borg2 beta for performance testing.

**Comment by ThomasWaldmann** [comment]
Guess this is as good as it gets for the current codebase. At some time in the future we may add multithreading, which might bump up speeds more, but don't hold your breath. :-)

The main point of borg is to avoid unnecessary data processing, like skipping of unchanged files, like not compressing/encrypting/authenticating/writing chunks it already has in the repo.
This gives a away bigger speed advantage for many users than the pure throughput optimisation. But you do not get these optimisations when processing piped data.

**Comment by ThomasWaldmann** [comment]
OK, guess there's nothing to do here for now. We already have another open ticket for multithreading.
