### ISSUE TITLE
Chunk cache is rebuilt after borg recreate (aka clone)

### ISSUE THREAD

**Issue by henrus** [borgbackup/borg#7274]
I am cloning an archive by recreating with an non-matching exclude

borg recreate REPO::old --exclude NIX --target new

However, it seems as if the the chunk cache is not updated and rebuild in the next. I am not sure whether this is something specific to recreate or the way I use it (clone operation).

## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes, nothing seemed to match

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE (cache is rebuilt unnecessarily)

## System information. For client/server mode post info for both machines.

Test were run locally. Problem exists on client/server set up, too.

#### Your borg version (borg -V).

1.2.3

#### Operating system (distribution) and version.

Ubuntu 20.04

#### How much data is handled by borg?

The problem can be reproduced in a sandbox (local directories)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create REPO::old someDir
borg recreate -v --debug REPO::old --exclude NIX --target new
borg recreate -v --debug REPO::old --exclude NIX --target new2

## Describe the problem you're observing.

The chunk cache is rebuild

```
...
Archives: 17, w/ cached Idx: 16, w/ outdated Idx: 0, w/o cached Idx: 1.
Reading cached archive chunk index for test ...
Verified integrity of /home/henrus/.cache/borg/ae7e8a6a07e3cbdc843b97e57881d569e7bb5f0fd3aa80101b9a4c1688b83ced/chunks.archive.d/f34c49d643432f02cb5214a421e4117cfe0c3f5e2a307e6a4670e5f2f12ee435.compact
Merging into master chunks index ...
...
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

This can be reproduced and repeated.

**Comment by ThomasWaldmann** [comment]
This is very very likely the same issue as the more general / less special #7278.

It is just that for any locally created new archive, borg does not immediately write something to `chunks.archives.d/`.
