### ISSUE TITLE
borg2: use platformdirs python package?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7281]
@RayyanAnsari suggested to use the `platformdirs` python lib ( https://github.com/platformdirs/platformdirs ) and I had a closer look now:

- the code quality seems decent, from an experienced developer
- the amount of code is not much, but also not trivial. it might be also interesting for us that it supports android also (but not sure it is relevant for termux users).
- some dists have it already packaged, some do not (looked at debian,ubuntu,fedora), so there might be some work for packagers.
- there is 1 open ticket in their tracker with some discussion whether they use some (macOS) directory correctly or not. https://github.com/platformdirs/platformdirs/issues/98
- so, i guess we could add it as a python dependency for borg if we can get rid of some of the corresponding code we have.
- we would need to be careful, so we do not break "borg transfer" when it reads borg1 archives/repos (config/cache access the borg1 way).
- for borg2 config/cache, we could be incompatible as that would be all-new anyway.
- it seems to not yet autocreate not-yet existing directories, but guess the maintainer there is open for a PR with that. https://github.com/platformdirs/platformdirs/issues/120

**Comment by RonnyPfannschmidt** [comment]
I highly recommend the library

**Comment by ThomasWaldmann** [comment]
@RayyanAnsari are you working on using platformdirs for borg?

**Comment by RayyanAnsari** [comment]
I have, see IRC.

**Comment by ThomasWaldmann** [comment]
Note: not having XDG_*_HOME with platformdirs on macOS caused a bit of a pain (and might also cause upgrade issues).
