### ISSUE TITLE
To UTC or not to UTC...

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7283]
#7282 fixed the issue that our tests fail when they are run in some timezones (e.g. `TZ=UTC+12`) by changing the timezone in which borg prunes to UTC. Update: #7284 reverts #7282 and fixes the tests differently.

This corresponds to borg2 currently using UTC for about everything (only exception is when giving `--timestamp=...` on the commandline **without** specifying a tz offset like `+01:00`, then it will use local time).

Some IRC conversation related to this:
```
18:32  ThomasWaldmann$ guess this might give slightly different behaviour from user expectations, but it is more consistent with borg2 having utc archive timestamps.
18:33  ThomasWaldmann$ also, our unit tests failed when running them in some timezones like utc+12 and with that change, they now work in any TZ.
18:35  ThomasWaldmann$ borg2 list now outputs archive listing like:
18:35  ThomasWaldmann$ arch                                 Wed, 2023-01-18 17:34:40 +0000  [592...0d12c]
18:35  ThomasWaldmann$ so that is also utc
18:36  tao$ is it always UTC? or is that just because you set the TZ to UTC
18:36  ThomasWaldmann$ for local users maybe needs a bit getting used to it. for internationally dispersed users with common repos it might be simpler now.
18:36  tao$ hmmm. i'd not like that. i'd rather see local time in every time stamp
18:36  ThomasWaldmann$ no, the archive list is always utc.
18:37  ThomasWaldmann$ yeah, that's what i mean with "getting used to it". :-)
18:38  ThomasWaldmann$ but just imagine you have that international context. having people in different TZs making backups and later looking at them.
18:38  ThomasWaldmann$ then you'ld have all sorts of hard-to-compare timestamps.
18:38  tao$ i don't want to get used to that though. if i make a backup at 19:00 and list the archives i want to see one that says 19:00. setting it to UTC is fine, but should be some way of setting it to localtime too surely?
18:39  ThomasWaldmann$ the ts in the archive is in utc. when running borg list, borg could recompute that to local time.
18:40  tao$ yes. i only mean when i display the list using rlist. internally in the repo metadata i don't care about
18:40  ThomasWaldmann$ but then, if your friend in london made a backup at 18:00 local time there, you'ld get it displayed as being from 19:00 (in germany)
18:41  ThomasWaldmann$ which refers to the same point in time, but might make discussion about it a bit confusing.
18:42  tao$ way i would see it working would be to internally store the timestamp in UTC and then when i do borg rlist it uses the local TZ setting to display it in the local timezone, for UK, Germany, USA whatever
18:42  ThomasWaldmann$ like e.g. if he says "restore the backup of 18:00"
18:43  ThomasWaldmann$ then you might restore the wrong one.
18:43  ThomasWaldmann$ (assuming there is one per hour, for example)
18:43  tao$ i might be wrong about this, but most users i would expect only have one person using that repo in one single timezone. multiple users in multiple timezones seems less likely
18:44  ThomasWaldmann$ that might be, yes. but there is a lot of remote work and there are international companies and organisations.
18:45  tao$ could it be a switch/environment variable at least so you can choose UTC or localtime in operations? or is that too complicated
18:46  ThomasWaldmann$ that's something we could think about and someone would need to write the code.
18:46  ThomasWaldmann$ what i am changing above (url) is not the list behaviour btw (that was done quite a while ago), but how prune looks at dates/times.
18:46  tao$ it's feeling a bit like the --iec thing where iB stats are the only thing that makes sense to me but it's not the default :)
18:47  ThomasWaldmann$ yeah. ISO vs. IEC.
18:47  ThomasWaldmann$ HDD manufacturer like ISO better (because then their HDDs are "bigger")
18:49  ThomasWaldmann$ at least borg2 will be much more precise no matter what ones chooses, as it is always giving the tz offset (like +00:00 for utc tz)
18:50  ThomasWaldmann$ in some contexts (e.g. when looking at log files) that can be quite important
18:51  ThomasWaldmann$ you don't want to get into prison just because somebody confused the datetime when determining who had the IP address in question 
                       at a specific time.
18:53  tao$ yes. i absolutely agree when it's got international use. just for the use case of a one person personal backup, UTC seems wrong
18:54  tao$ it's not so bad for me because i'm in the UK so UTC == GMT, but it will still be an hour out during DST. will be really weird though for people in USA, Japan etc
18:59  ThomasWaldmann$ besides the display issue, there would be also the "pruning behaviour" issue.
```

**Comment by ThomasWaldmann** [comment]
When discussing this, we have to differentiate:
- what borg is internally doing (borg2 uses UTC timezone everywhere)
- what borg is displaying to the user
- how borg is behaving (e.g. `borg prune` rules keeping/deleting archives based on their timestamp)

**Comment by jdchristensen** [comment]
I think borg should by default display local time.  There could be a --utc switch to get it to display UTC instead (or the `TZ=UTC` trick could be documented.  Most programs and websites display local time.  I agree that including the offset is important to make this unambiguous.

For pruning, I also think most users will be less confused if "day" is defined using local time.  First, that's long been the borg 1.x default, and is documented.  Second, we already get lots of issues raised by misunderstanding pruning, and I think it would be worse if the last backup on (local) Tuesday was deleted because in UTC that backup was the first on Wednesday.  That all said, I'm ok with changing this if it is well-documented and clearly announced.  I don't really care which backups get pruned, as long as they get gradually thinned out.

**Comment by jdchristensen** [comment]
I don't think the test failures should be a factor in this decision.  One could just use the local timezone to adjust things in the tests to make them work.

**Comment by ThomasWaldmann** [comment]
@jdchristensen I could fix the tests by using the local timezone when giving the testing timestamps.

It's a bit different than normal borg operations because a borg manifest or borg archive uses timestamps in UTC timezone, but this is not relevant for testing the correctness of `prune_split`.

**Comment by ThomasWaldmann** [comment]
TODO: fix normal output of borg to give timestamps in local time, including the tzoffset to make clear it is in that specific timezone.

**Comment by ThomasWaldmann** [comment]
Yet another aspect of timestamp usage is keeping or losing timezone (tzoffset) information.

## Archives

When users run `borg create`, they create an archive running this command on a machine located in (or rather: configured to be in) some specific timezone (let's just assume CET here). Currently, borg normalizes the timestamp it stores into archive metadata (and also into manifest) to UTC, so it loses the information about the original timezone.

## Files

When creating an archive, borg does `os.stat` to get the unix timestamps (mtime, ctime, atime, birthtime) of each file. This is just a timestamp in nanoseconds (by convention defined as "ns since 1.1.1970 in UTC"). Due to the convention, borg does not archive timezone information with that.

So, as it is now (always storing UTC timestamps, for archives as well as for files), we have consistent behaviour, but we lose the tzoffset of the original environment.

**Comment by ThomasWaldmann** [comment]
Discuss: is timestamp behaviour now fine (as seen in 2.0.0b5) or do we need to change something (see also previous comment)?

**Comment by ThomasWaldmann** [comment]
Guess all is fine.
