### ISSUE TITLE
borg.locking.LockFailed: Failed to create/acquire the lock ... 

### ISSUE THREAD

**Issue by gtenrreiro** [borgbackup/borg#7292]
#### Your borg version (borg -V).
1.2.3
#### Operating system (distribution) and version.
MacOS Ventura 13.1
#### Hardware / network configuration, and filesystems used.
APFS
#### How much data is handled by borg?
5GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
#!/bin/bash

# Setting this, so the repo does not need to be given on the commandline:
export BORG_REPO=/Volumes/GusData/gusBackup

# See the section "Passphrase notes" for more infos.
export BORG_PASSPHRASE=''

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

# Backup the most important directories into an archive named after
# the machine this script is currently running on:
export PATH=$PATH:/opt/homebrew/bin

borg create                         \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --exclude '/Users/gt/Library'   \
    --exclude '/Users/gt/.Trash'    \
                                    \
    ::$(date +"%Y_%m_%d_%I_%M_%p")  \                      \
    /Users/gt                       
```

## Describe the problem you're observing.
The command above, ran from a script, from the command line works fine, however if I call the same command from crontab, then it fails saying "borg.locking.LockFailed: Failed to create/acquire the lock"

To test, I even changed the permissions on "gusBackup" to 777 recursive, but still nothing. 
I checked and the script runs as my user, same user that runs it when I do it by hand from the command line interactively.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, 
#### Include any warning/errors/backtraces from the system logs

Fri Jan 20 21:01:00 CST 2023 Starting backup

Failed to create/acquire the lock /Volumes/GusData/gusBackup/lock.exclusive ([Errno 1] Operation not permitted: '/Volumes/GusData/gusBackup/lock.exclusive.oc181fq3.tmp').
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/repository.py", line 200, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/repository.py", line 432, in open
    self.lock = Lock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/locking.py", line 384, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/locking.py", line 397, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/opt/homebrew/Cellar/borgbackup/1.2.3/libexec/lib/python3.11/site-packages/borg/locking.py", line 137, in acquire
    raise LockFailed(self.path, str(err)) from None
borg.locking.LockFailed: Failed to create/acquire the lock /Volumes/GusData/gusBackup/lock.exclusive ([Errno 1] Operation not permitted: '/Volumes/GusData/gusBackup/lock.exclusive.oc181fq3.tmp').

Platform: Darwin M-H43H1HH623 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
Borg: 1.2.3  Python: CPython 3.11.1 msgpack: 1.0.4 fuse: None [pyfuse3,llfuse]
PID: 32705  CWD: /Users/gt
sys.argv: ['/opt/homebrew/bin/borg', 'create', '--verbose', '--filter', 'AME', '--list', '--stats', '--show-rc', '--compression', 'lz4', '--exclude-caches', '--exclude', '/Users/gt/Library', '--exclude', '/Users/gt/.Trash', '::2023_01_20_09_01_PM', ' ', '/Users/gt']
SSH_ORIGINAL_COMMAND: None

terminating with error status, rc 2

**Comment by infectormp** [comment]
It says `[Errno 1] Operation not permitted`, so this is not the borg problem. This error message came from OS level.

**Comment by gtenrreiro** [comment]
Figured it out. On MacOs, my backup drive was an external mounted drive, and cron had to be given "Full Disk Access" from the System Settings, otherwise it can't do much on that drive. Thanks
