### ISSUE TITLE
borg v1.2.3 xattrs error on CIFS mount

### ISSUE THREAD

**Issue by rsuna** [borgbackup/borg#7293]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

## System information. For client/server mode post info for both machines.
Mode: pull
Server: linux
mounted Windos 10 NTFS volume (C), as CIFS on the linux host

#### Your borg version (borg -V).
borg 1.2.3
#### Operating system (distribution) and version.
Debian 11.6
Windows 10  Pro  Version  21H2
#### Hardware / network configuration, and filesystems used.
linux amd64, filesystem btrfs and mounted CIFS
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg create  --stats --list --filter 'E?' --show-rc --compression zstd --exclude-caches  --files-cache ctime,size  /local_disk/backup/borg::spanishdancer'-{now}' /cifs/spanishdancer/C

## Describe the problem you're observing.
Direct after start the command the following message appears:

> /cifs/spanishdancer/C: extended stat (xattrs): [Errno 13] Permission denied: '<FD 6>'
> E /cifs/spanishdancer/C

This failure didn't happen with the borg version 1.1.16.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

The /cifs/spanishdancer/C is a CIFS mount, which was created manually by following command:

> mount -t cifs -o cred=/etc/creds/spanishdancer,serverino //spanishdancer/C /cifs/spanishdancer/C

The resulting mount is (output of the mount cmd):

> //spanishdancer/C on /cifs/spanishdancer/C type cifs (rw,relatime,vers=3.1.1,cache=strict,username=borgbackup,domain=SPANISHDANCER,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.0.9,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,closetimeo=5)

Maybe that the option _nounix_ is the issue, but its enabled automatically. I didn't find a way to not enable this mount option.
There seems to be no possibility to disable this kind of xattrs check in borg 1.2.3.

**Comment by ThomasWaldmann** [comment]
As this is a "Permission denied" OS Error, it happens below borg.

I've no idea how/whether cifs / ntfs deals with xattrs, but maybe check first whether there is some simple issue with permissions.

In case you do not need extended attributes anyway, you can run `borg create --noxattrs --noacls ...`.

**Comment by ThomasWaldmann** [comment]
BTW, also check your `--files-cache=ctime,size` setting. ctime on linux is "inode change time", is kernel controlled and reacts to any change on a file. but on windows, this might be something like "create time" and might never change - if that is the case, you should rather use mtime.

**Comment by rsuna** [comment]
The hint with `borg create --noxattrs `... solves the issue.
I also changed the `--files-cache=ctime,size` to `--files-cache=mtime,size`.
Thanks for you help.
