### ISSUE TITLE
fix --newer/older/newest/oldest options / support code

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7296]
master branch only:

as `define_archive_filters_group` defaults to adding these options, **all** commands calling this now suddenly "support" these options, according to their help.

but they do not really support these options, because the appropriate code is not there:
- `list_considering` does not yet support them
- check other places

**Comment by ThomasWaldmann** [comment]
@Michael-Girma ^ found this issue after merging.

**Comment by Michael-Girma** [comment]
I did make changes to ```list_considering``` should those be removed?

**Comment by ThomasWaldmann** [comment]
I think you only changed `.list`, but not `.list_considering`.

**Comment by ThomasWaldmann** [comment]
btw, update your local master branch first from borg master.
