### ISSUE TITLE
"--umask" option doesn't set proper permissions to "nonce" and "config" files

### ISSUE THREAD

**Issue by jeremyfritzen** [borgbackup/borg#7297]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Question (because I think I might not use it properly ; but maybe it will end up being an issue)

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
Ubuntu 22.04.1 LTS

#### Hardware / network configuration, and filesystems used.
1vCPU (3.092GHz) / 2GB RAM (Lab VM)
ext4 filesystem

#### How much data is handled by borg?
Very few (/bin content, ~200MB)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg init -e repokey --umask 0022 test-borg`
`borg create --umask 0022 test-borg/::test1 /bin`
`ls -lh test-borg/` gives the following:

> drwxr-xr-x  3 user1 group1  4096 Jan 23 13:43 ./
> drwxr-x--- 12 user1 group1  4096 Jan 23 13:38 ../
> -rw-r--r--  1 user1 group1    73 Jan 23 13:38 README
> -rw-------  1 user1 group1   700 Jan 23 13:38 config
> drwxr-xr-x  3 user1 group1  4096 Jan 23 13:38 data/
> -rw-r--r--  1 user1 group1   118 Jan 23 13:43 hints.13
> -rw-r--r--  1 user1 group1 41258 Jan 23 13:43 index.13
> -rw-r--r--  1 user1 group1   190 Jan 23 13:43 integrity.13
> -rw-------  1 user1 group1    16 Jan 23 13:43 nonce

## Describe the problem you're observing.
`nonce` and "config" files don't have the expected permissions.
I would expect them to have `rw- r-- r--` permissions since I used `--umask 0022` option when creating the archive.

I can fix the issue for config file by manually changing the permissions via chmod.
But since nonce is recreated/updated each time you add an archive, new permissions will be set to `rw- --- ---`.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Follow commandline instructions above.

I saw this ticket [#4375](https://github.com/borgbackup/borg/issues/4375) but the resolution didn't help me.

#### Include any warning/errors/backtraces from the system logs
None

**Comment by ThomasWaldmann** [comment]
Can you reproduce with borg 1.2.3? You can get it via the PPA for borgbackup.

**Comment by jeremyfritzen** [comment]
It works :)
Thanks a lot!
