### ISSUE TITLE
"Borg help patterns" missing or hard to find

### ISSUE THREAD

**Issue by jumper444** [borgbackup/borg#73]
The documentation usage page:
https://borgbackup.github.io/borgbackup/usage.html
has multiple instances of the following sentence:
"See “borg help patterns” for more help on exclude patterns."

The phrase/term itself has no hyperlink (which would be the best solution) and searching the page or the left table of contents shows no result or way to get to this documentation.  Maybe it is right in front of me and I'm missing it somehow?

**Comment by ThomasWaldmann** [comment]
borg help patterns is a command you enter on the shell. I clarify the message...

**Comment by ovizii** [comment]
*switching over from duply I used to use this type of patters in its exclude file:*

**/tmp
**/cache

*would borg's equivalent simply be:*
*/cache
*/tmp

**meaning any folders called cache and tmp are excluded including their content? **

*Can I simply put those two lines into an exclude file and use --exclude-from EXCLUDEFILE to load it?*

**Comment by ThomasWaldmann** [comment]
Well, we only support the patterns as seen in "borg help patterns".
And yes, one usually opens a new ticket if the topic does not match.
