### ISSUE TITLE
add more info to archive log 

### ISSUE THREAD

**Issue by infectormp** [borgbackup/borg#730]
Hello, please add repository name to log. Currently we can identify repository in log only if add repository name to archive name at backup stage, but this not right way.

**Comment by infectormp** [comment]
Would be useful also add this info too
Hostname: 
Username: 
Command line:

**Comment by ThomasWaldmann** [comment]
Well, assuming you have a different log file for different repos, you can also see it from there.

"repository name" -> "repository url"

**Comment by infectormp** [comment]
@ThomasWaldmann you right. We have different log file for different repos.

> "repository name" -> "repository url"
yes, but in log we not have "repository url".

this can be look like ```reading files cache from /backup/etc.repo``` or can be added to summarize info at bottom

**Comment by ThomasWaldmann** [comment]
the additional stuff you want is emitted by borg info repo::archive (except the repo url).

**Comment by infectormp** [comment]
i know

**Comment by infectormp** [comment]
ok. look like i will use borg info to get needed info to log.
