### ISSUE TITLE
pip: has inconsistent version: expected '1.2.3', but metadata has '0.0.0'

### ISSUE THREAD

**Issue by sophie-h** [borgbackup/borg#7302]
I have been hitting this problem for a while. The way borg is installed is generated via flatpak-builder-tools

The message is

> borgbackup-1.2.3.tar.gz has inconsistent version: expected '1.2.3', but metadata has '0.0.0'

And I ran into it today again

https://buildbot.flathub.org/#/builders/37/builds/2462

The workaround is to use `--use-deprecated=legacy-resolver` but that doesn't sound quite right.

The build command is

```
pip3 install --verbose --exists-action=i --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} \"borgbackup\" --no-build-isolation
```

**Comment by ThomasWaldmann** [comment]
that .tar.gz is the download from pypi.org?

**Comment by ThomasWaldmann** [comment]
```
  /usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'use_scm_version'
```
Hmm, the pyproject.toml says borg requires setuptools_scm, but here it complains about the config dict for that.

**Comment by sophie-h** [comment]
It is https://files.pythonhosted.org/packages/e6/a5/69a9ddce8ae769e1bf4d1f1e93459238f473bad770d4dddba108db91971c/borgbackup-1.2.3.tar.gz

I don't think it's a bug in the resolver if the metadata contains '0.0.0'. The expected '1.2.3' comes from the filename afaik

**Comment by ThomasWaldmann** [comment]
Something unrelated i noticed: it says "using bundled xxhash". So you do not have libxxhash-dev installed there?

**Comment by sophie-h** [comment]
> Something unrelated i noticed: it says "using bundled xxhash". So you do not have libxxhash-dev installed there?

You can't really install packages in Flatpak, instead you usually build things. Is the bundled version bad?

**Comment by ThomasWaldmann** [comment]
xxhash: No, I just noticed it discovered all from libs via pkg-config, just not that.

**Comment by ThomasWaldmann** [comment]
I had a look into the .tar.gz: `PKG-INFO` says 1.2.3 and also `borg/_version.py` says 1.2.3.

Maybe setuptools_scm malfunctioning somehow?

**Comment by sophie-h** [comment]
Unfortunately python packaging is just weird magic to me

**Comment by asiunov** [comment]
@sophie-h I think this is happening because you use this option `--no-build-isolation`, in which case you have to install all build dependencies manually. In this case, you are missing `setuptools-scm` which is used for borg versioning. Try `pip install setuptools-scm`

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/7302#issuecomment-1407755293 I also have seen this while tweaking setup in borg 1.4-maint branch, but then resolved it after I moved most stuff to `pyproject.tom` and using only `pip install` and `python -m build`.

Guess it is worth retrying this with 1.4-maint (or some 1.4 alpha/beta release soon).

**Comment by sophie-h** [comment]
Someone explained to me that I manually need to installl `setuptools-scm` because whatever is provided in the Flatpak Sdk is not enough to resolve the version properly. Sorry for the fuzz. For people working with python that's probably obvious.

**Comment by sophie-h** [comment]
> In this case, you are missing setuptools-scm which is used for borg versioning. Try pip install setuptools-scm

Ah, also here, thanks!
