### ISSUE TITLE
questioning the "part files" feature

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7304]
While working on #6709 I noticed that part files and getting statistics right are kind of a pain.

# concept of checkpoints

- we want checkpointing (creation of valid, but incomplete archives, e.g. every 30mins).
- user can also press Ctrl-C / send SIGINT to invoke checkpointing
- checkpointing is easy when processing small files, we just save a checkpoint archive in between files. done.
- but if we process really big files (like disk images), this is not good enough, because this can take way longer than our checkpoint interval (and also would not react in a timely manner to SIGINT). in the worst case, we would have 1 super big file and that would have to be done without any checkpoint.

# concept of part files

To solve the issue with big files, part file support was added quite a while ago (borg 1.1, IIRC):

- when checkpointing and we are in the middle of a file, create a part(ial) file item that references the range of chunks we were processing since start of the file or since last checkpoint.
- at the end of the file, also create a normal item for the full file
- in the end (when nothing gets fatally interrupted), we have part1 ... partN **and** the full file
- concatenate part1 + part2 + ... + partN == full file

# pain points with part files
- stats: we have more files now. to not confuse users, we have to differentiate between files_count and part_files_count.
- stats: we have chunks referenced by the full file, but we reference the same chunks again from the part files. to not confuse users, we have to differentiate between overall files_size and of part_files_size.
- we needed `--consider-part-files` option to support showing stats with/without the part files
- as we usually do not create a part file (only when checkpointing happens), chunks are at first accounted as non-part chunks (and they might be unique or not). when we then decide to checkpoint (based on time or SIGINT received), we have to re-account the chunks correctly for the part file (as only that will be in the checkpoint archive), considering uniqueness (which would require extra tracking we do not have yet).
- when doing `borg recreate`, we might get **part files** as input, then we would get parts-of-parts when checkpointing...
- the code to support all this is way more complicated than it would be without this.
- the related code likely has bugs, statistics have been off in the past.

**Comment by RonnyPfannschmidt** [comment]
would it be possible to have checkpointing work in a manner where a checkpoint indeed has a single part file, however the next checkpoint would instead of adding a extra part file just be a archive with a larger part file 

(similar to how a download with firefox has a slowly increasing part file that will eventualy replace a standin)

that way the checkpoints would be very regular archives, and part files would no longer be part of fonal archives

the cost would be that a checkpoint has to synthesize a archive thats slightly different than the work in progress to keep the differentiable tail in check

**Comment by ThomasWaldmann** [comment]
How could this be done in a simpler way, without any part files?

# Option "not saving the current incomplete item"

- if we do a checkpoint and just save the archive (the current file item not yet added), we would have a valid archive (containing all files we have processed yet, just not the current unfinished one).
- we also would have added content chunks for the unfinished file and as they are not referenced yet by the not yet written file item for the unfinished file, chunk reference counts might be too high for old chunks and we might have  some orphan new chunks that are not used by any archive.
- too high refcounts and orphan chunks could be fixed by `borg check --repair`. This is harmless, but it might make users worry if they see related warnings.

# Option "saving the incomplete current item"

- if we do a checkpoint (adding the current, still incomplete item to the checkpoint archive) and then save the archive, the archive would then contain all files we processed, the last file might be incomplete/truncated.
- all chunks we have added would be referenced, refcounts would be correct.
- the archive name would be "somename.checkpoint.X", so the user would see that this is not a complete archive, but just a checkpoint and could expect that the last file in there might be incomplete.
- if we like, we could still have the item.part attribute indicating this is a partial/truncated file. maybe not even needed, see next point:
- item.size could be different from sum(chunk sizes) also indicating potential truncation of the last file.

# What we would win.
- correct per-archive stats (files count, overall size)
- no --consider-part-files needed any more.
- way simpler code
- fixing #6709 might get a bit easier.

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt guess what you suggest sounds like B? I have to think more about the archive metadata stream...

**Comment by ThomasWaldmann** [comment]
IIRC, there is only one archive metadata stream created and referenced by the archives in its different growth stages:
- first checkpoint archive: m1m2m3
- 2nd checkpoint archive: m1m2m3m4m5
- final archive archive: m1m2m3m4m5m6m7

So, guess B does not work and would make the stats issue even worse.

**Comment by ThomasWaldmann** [comment]
# Option C: "save checkpoint archive without current item" plus "save auxiliary archive with incomplete item"
- checkpoint archive is fully valid, all files are complete and its metadata stream is a prefix of all other checkpoints and the final archive
- auxiliary archive is only to have correct refcounts and to have the incomplete item NOT in the checkpoint archive (and also not in the final archive).

**Comment by ThomasWaldmann** [comment]
`borg transfer` could get rid of "part files" when transferring from borg 1.2 to 2.0 repos.

**Comment by RonnyPfannschmidt** [comment]
interesting points, now im torn between B and C

it reads likea complexity gradient where D has the current mess but separated in a archive to destroy later, C has the "tail management managed externally and C is the magical goldilock that has correct singular part files for the last item while the archive grows

if size vs stored data size can be managed correctly, then checkpoints can be treated like partial tar files (and the .part extension would be "mood"

**Comment by ThomasWaldmann** [comment]
"moot"? you mention C twice, did you mean B once?

**Comment by ThomasWaldmann** [comment]
PR for option B is in #7309.

**Comment by ThomasWaldmann** [comment]
Merged.
