### ISSUE TITLE
add more info to prune log

### ISSUE THREAD

**Issue by infectormp** [borgbackup/borg#731]
Please add flowing info to prune log

1. Archive fingerprint (In case of archive rename we can't automatically handle pruned archive)
2. Repository name

**Comment by ThomasWaldmann** [comment]
So, what do you want to do with the archive fingerprint from the log?

"repository name" -> "repository URL"

**Comment by infectormp** [comment]
We are store info from borg logs to mysql, after prune we check prune log and look for pruned archive and set what archive was pruned. But in case of archive rename we can't automatically handle pruned archive. 

We currently develop (php+mysql) webapp to manage\analyze borg logs and we need a bit more info from logs for this. After app will finished i push it to github.

**Comment by ThomasWaldmann** [comment]
i currently have:
<name (26 chars)> <datetime> [<id>]

it's bit less pretty now due to the long hex id, but of course the id is more stable than the name.

**Comment by infectormp** [comment]
:+1:
