### ISSUE TITLE
borg list --dry-run status chars, shall we change them?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7321]
Current output (borg <= 2.0):
```
- /some/file              # "-" means "not backed up" (due to dry-run)
x /some/other/file        # "x" means excluded
```
pstn on IRC found it confusing that they are not related to the exclusion chars (+, -, !).

So, we could actually do that, for borg >= 2.0:
```
+ /some/file              # included (but "not backed up" due to dry-run)
- /some/other/file        # excluded
! /some/other/file        # excluded no-recurse
```

**Comment by cyb3rz3us** [comment]
Seems like a good move given that it would align the symbols between their use in creating patterns & what is presented when testing those same patterns.  Makes much more sense this way.

**Comment by ThomasWaldmann** [comment]
Hmm, thinking about it: guess we do not track which rule triggered inclusion/exclusion, we only know the result. So, and easy change could likely only do + and - status char (and - status could be either - or ! in the rules).

**Comment by cyb3rz3us** [comment]
> do not track which rule triggered inclusion/exclusion, we only know the result

I think this is fine, correct?  Don't we only care about the results during a dry-run?

**Comment by ThomasWaldmann** [comment]
When running borg on non-dry-run mode, "x" status char is currently also used there to signal "excluded".

So, guess if we change "x" to "-" in dry-run mode, we also need to do the same in non-dry-run mode.

**Comment by ThomasWaldmann** [comment]
Will be in borg2!
