### ISSUE TITLE
[Question] Weekly copy from repo to external server

### ISSUE THREAD

**Issue by CrysK** [borgbackup/borg#7326]
Hello all,

I am using Borg (v1.2.3) on Ubuntu 22.04 LTS headless server. Backup is done successfully on the same server, daily. It keeps: daily, weekly, monthly.

The question:
I want to upload a (copy of the) backup to an external server every week. I want to keep the CPU time and especially the data upload low. 
The compressed data is currently about 6TB (original 6,4TB), the daily backup takes about 0:30h to 2:00h, the internet connection has unfortunately only 25MBit/s upload.
How can I copy a backup weekly to the external server? So that only the most necessary data is transferred.

Thank you very much!

**Comment by ThomasWaldmann** [comment]
If you can install borg on the external server and just make an additional backup, that might be the best solution as it avoids error propagation.

Otherwise:
- check segment file size in the repo config, maybe you want to use less than 500MB, e.g. 50MB
- do not run `borg compact` too frequently, it shuffles stuff around in the segment files
- make sure borg does not use the repo when you sync it to the server, see `borg with-lock ...`.

**Comment by CrysK** [comment]
Thank you very much!

> If you can install borg on the external server and just make an additional backup, that might be the best solution as it avoids error propagation.

But then the external server would have to compare all of the data, which would take about 22 days at >6TB and 25MBit/s!?



> Otherwise:

That would mean:
- 6 days a week run normal `borg create`
- on the 7th day `borg create`, then `borg with-lock` with `rsync` to copy to the external server

But if I run a `borg compact` only once, then I have to replace the complete repo!?

If I run `borg compact` on the 7th day on both servers, the repos are probably not identical!?

**Comment by ThomasWaldmann** [comment]
Into a fresh borg repo, the initial backup usually takes rather long. But you can do it in multiple attempts and interrupt at any time, it will converge against a good/complete state. After that, borg will be very fast and only add changes. I backed up a long time over a even much slower DSL upstream (not as much as data as you have though, but after first backup only daily changes matter).

No, `borg compact`will not change all segment files nor you have to replace the whole repo.

As long as you do NOT run compact, rsync will be super efficient as new stuff is in new files and all old files stay exactly the same (no matter whether you added archives, deleted archives, pruned, ...).

When you run compact, it will make segment files compact. If you had deleted some archives, this usually means some old non-compact segment files will have vanished and new compact segment files (with all the non-deleted data) will have been created, so there will be a bit more traffic.

**Comment by RonnyPfannschmidt** [comment]
would borg transfer from borg2 be able to ease with the trouble?

also in case of large dataset with small changes set, would a  initial offline transfer help (aka take encrypted bulk data via a harddisk to the target location)

**Comment by ThomasWaldmann** [comment]
1. yes
2. independently updating 2 repos with the same key with borg < 2 creates security issues, like nonce reuse.

**Comment by ThomasWaldmann** [comment]
Guess this is solved.

**Comment by ThomasWaldmann** [comment]
Ideally, you could `borg check` the repo first and only rsync it if that returns 0. That would avoid at least some error propagation.

Why do you call `borg break-lock $LOCAL_PATH`?
