### ISSUE TITLE
undef NDEBUG?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7329]
@jdchristensen just found out that we compile the C stuff with `NDEBUG` set, so all the `assert()` calls we have in the C code are removed or deactivated.

It's a setup.py default as it seems, but we could change it:

https://stackoverflow.com/questions/50740518/remove-a-default-compiler-option-when-building-with-setup-py

Guess we want to have the asserts active.

Anything bad we would get by undefining `NDEBUG`?

**Comment by jdchristensen** [comment]
I think we should try enabling the assertions.  We could check that some benchmarks don't slow down appreciably.  It looks like there are around 30 uses of assert in C code.

**Comment by ThomasWaldmann** [comment]
I am not worried much about the `assert(condition)`, I was just asking myself **what else** will change by this?

Found this:

https://stackoverflow.com/questions/5473556/what-is-the-ndebug-preprocessor-macro-used-for-on-different-platforms

So guess we'll be fine by just undefining it for now in master branch.

**Comment by ThomasWaldmann** [comment]
done, see #7331.
