### ISSUE TITLE
borg recreate --exclude triggers rechunking

### ISSUE THREAD

**Issue by mischaelschill** [borgbackup/borg#7336]
I have a rather large, remote backup repository (4TB), and wanted to remove directories from old archives to free up some space.

I ran borg recreate -e "directory/to/remove/*" and a dry run seemed to do what I want after a few minutes. Now when I run the actual command, it didn't return for hours. nethogs shows that a lot of data is downloaded, so I assume that for some reason, the whole archive is downloaded. I assumed, since I only remove some files, the actual contents of the archive is not needed locally.

I didn't specify --recompress, and neither did I add --chunker-params. However, I do have different chunker params than the borg default when I create archives, but I assumed from the manpage that recreate is not re-chunking if no chunker params are specified.

I use borg 1.2.3.

**Comment by ThomasWaldmann** [comment]
Please give the complete borg command you used (you can edit paths if they are private, but keep semantics the same).

Indeed, I'ld also expect that not to download a lot of data. Can you reproduce this?

**Comment by ThomasWaldmann** [comment]
Oh, guess I need to check WHAT chunker params this will default to if one does not explicitly give them. Maybe it defaults to same value as `borg create` and thus would trigger rechunking in your case although you did not intend to do that.

**Comment by mischaelschill** [comment]
This is the command

borg recreate ssh://my.server/home/my.borg::myarchive -pse */var/lib/libvirt/* --comment novm --lock-wait 5

The manpage states that adding chunker params will cause re-chunking, that is why I didn't: --chunker-params will re-chunk all files in the archive

**Comment by ThomasWaldmann** [comment]
Maybe the help text / man page text is only true if one usually uses the default chunker params.

**Comment by ThomasWaldmann** [comment]
Guess this is a bug, I added a test for it and it fails, see #7337.

**Comment by mischaelschill** [comment]
If I add --chunker-params buzhash,16,23,21,4095 (the params I used for the archive) to the command, it works as expected.

**Comment by ThomasWaldmann** [comment]
A bug. The default value for parsing the `--chunker-params` option must be `None` (not `CHUNKER_PARAMS`).
