### ISSUE TITLE
[documentation] Where can I get the official borgbackup pgp public key

### ISSUE THREAD

**Issue by JavaScriptDude** [borgbackup/borg#734]
I would like to verify your files on the download for borg using the .asc files but I cannot find your sites public key.

If this is not documented, can you add this to your docs for others as well?

**Comment by ThomasWaldmann** [comment]
The key fingerprint is in the readme on github releases page.
Also, the fingerprint is in the footer of all my mails on the mailing list.

**Comment by JavaScriptDude** [comment]
Excellent. Thanks for the prompt reply.
