### ISSUE TITLE
backup not the complete path

### ISSUE THREAD

**Issue by Mitch187** [borgbackup/borg#7341]
Hi,

is it possible to make an archive with borg backup like this:

borg create --numeric-ids ssh://test@test.de:23/./backup::2023_02_10_initial /volume1/servers/test

But without the complete path with: Delete /volume1/servers/test from the path, but with the files and folders within.

When i extract it, it shows only the files in /volume1/servers/test

Best Regards,
Mitch

**Comment by ThomasWaldmann** [comment]
Guess you would need #6461, but it is not implemented yet.

You could `cd /volume1/servers/test` and `borg create REPO::ARCHIVE .`.

**Comment by ThomasWaldmann** [comment]
Duplicate, closing.
