### ISSUE TITLE
virtualbox 7 with Intel PRO/1000: Repository index missing or corrupted

### ISSUE THREAD

**Issue by lod911** [borgbackup/borg#7342]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
1.1.16 (Debian-Repo) & 1.2.3 (manual Installation)

#### Operating system (distribution) and version.
xxx@pc:~$ uname -a
Linux pc 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.
Virtualbox 7.0 VM
Bridged Networking
**NIC: Intel PRO/1000 MT Desktop (82540EM)**
Borg Repository is on an DS920 Synology NAS -> SMB Share

#### How much data is handled by borg?
Issue occures while init, check, create, etc.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
sudo borg init --debug --verbose --encryption repokey /mnt/ds920_backup/aaa

## Describe the problem you're observing.
Since i upgraded Virtualbox from 6.1 to 7.0, Borg crashes with "Repository index missing or corrupted" while any borg action with the respository.

I'm not sure, if this is a borg or virtualbox issue. But I think, it should be interessting for borg too and maybe analyse some checks or at least a more detailed errormessage.
Or maybe some information, that maybe helps oracle, to make some changes on there side?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, almost every time i run borg with any action verb. See backtraces below.
For testing, i created a fresh VM with Debian (Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux) and installed borg from the official debian repo (1.1.16). 
For further testing, i installed\copy the 1.2.3 Version with the same effect.

#### Include any warning/errors/backtraces from the system logs
```
xxx@pc:/mnt$ sudo borg init --debug --verbose --encryption repokey /mnt/ds920_backup/aaa
Initializing repository at "/mnt/ds920_backup/aaa"
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]: y
Your passphrase (between double-quotes): "123"
Make sure the passphrase displayed above is exactly what you wanted.
Remember your passphrase. Your data will be inaccessible without it.
Key in "<Repository /mnt/ds920_backup/aaa>" created.
Keep this key safe. Your data will be inaccessible without it.
Synchronizing chunks cache...
Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
Repository index missing or corrupted, trying to recover from: File failed integrity check: /mnt/ds920_backup/aaa/index.1
Repository index missing or corrupted, trying to recover from: File failed integrity check: /mnt/ds920_backup/aaa/index.2
Repository index missing or corrupted, trying to recover from: File failed integrity check: /mnt/ds920_backup/aaa/index.2
Checking repository transaction due to previous error: File failed integrity check: /mnt/ds920_backup/aaa/index.2
Repository index missing or corrupted, trying to recover from: File failed integrity check: /mnt/ds920_backup/aaa/index.2
File failed integrity check: /mnt/ds920_backup/aaa/index.2
Traceback (most recent call last):
  File "borg/repository.py", line 526, in open_index
  File "borg/crypto/file_integrity.py", line 195, in __exit__
  File "borg/crypto/file_integrity.py", line 189, in hash_part
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /mnt/ds920_backup/aaa/index.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/repository.py", line 526, in open_index
  File "borg/crypto/file_integrity.py", line 195, in __exit__
  File "borg/crypto/file_integrity.py", line 189, in hash_part
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /mnt/ds920_backup/aaa/index.2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/repository.py", line 558, in prepare_txn
  File "borg/repository.py", line 526, in open_index
  File "borg/crypto/file_integrity.py", line 195, in __exit__
  File "borg/crypto/file_integrity.py", line 189, in hash_part
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /mnt/ds920_backup/aaa/index.2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/archiver.py", line 5168, in main
  File "borg/archiver.py", line 5099, in run
  File "borg/archiver.py", line 183, in wrapper
  File "borg/archiver.py", line 290, in do_init
  File "borg/cache.py", line 387, in __new__
  File "borg/cache.py", line 378, in local
  File "borg/cache.py", line 497, in __init__
  File "borg/cache.py", line 903, in sync
  File "borg/cache.py", line 838, in create_master_idx
  File "borg/repository.py", line 1140, in __len__
  File "borg/repository.py", line 535, in open_index
  File "borg/repository.py", line 532, in open_index
  File "borg/repository.py", line 562, in prepare_txn
  File "borg/repository.py", line 526, in open_index
  File "borg/crypto/file_integrity.py", line 195, in __exit__
  File "borg/crypto/file_integrity.py", line 189, in hash_part
borg.crypto.file_integrity.FileIntegrityError: File failed integrity check: /mnt/ds920_backup/aaa/index.2

Platform: Linux pc 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Linux: Unknown Linux  
Borg: 1.2.3  Python: CPython 3.9.16 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 570  CWD: /mnt
sys.argv: ['borg', 'init', '--debug', '--verbose', '--encryption', 'repokey', '/mnt/ds920_backup/aaa']
SSH_ORIGINAL_COMMAND: None

```
#### LogFile from the NAS:
```
Protokoll,Uhrzeit,IP-Adresse,Benutzer,Ereignis,Datei/Ordner,Dateigröße,Dateiname
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Löschen,Ordner,NA,/pc_backup/aaa/lock.exclusive
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Löschen,Datei,0 Bytes,/pc_backup/aaa/lock.exclusive/pc.xxx.net@8796755360620.602-0
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Löschen,Datei,17 Bytes,/pc_backup/aaa/lock.roster
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,17 Bytes,/pc_backup/aaa/lock.roster
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,17 Bytes,/pc_backup/aaa/lock.roster
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,17 Bytes,/pc_backup/aaa/lock.roster
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,58 Bytes,/pc_backup/aaa/lock.roster
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Löschen,Datei,40.29 KB,/pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,40.29 KB,/pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,190 Bytes,/pc_backup/aaa/integrity.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,40.29 KB,/pc_backup/aaa/index.1.tmp -> /pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,70 Bytes,/pc_backup/aaa/hints.1.tmp -> /pc_backup/aaa/hints.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,190 Bytes,/pc_backup/aaa/integrity.1.tmp -> /pc_backup/aaa/integrity.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,190 Bytes,/pc_backup/aaa/integrity.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/integrity.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,40.29 KB,/pc_backup/aaa/index.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/index.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,70 Bytes,/pc_backup/aaa/hints.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/hints.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Löschen,Datei,40.29 KB,/pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,40.29 KB,/pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,190 Bytes,/pc_backup/aaa/integrity.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,40.29 KB,/pc_backup/aaa/index.1.tmp -> /pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,70 Bytes,/pc_backup/aaa/hints.1.tmp -> /pc_backup/aaa/hints.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,190 Bytes,/pc_backup/aaa/integrity.1.tmp -> /pc_backup/aaa/integrity.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,190 Bytes,/pc_backup/aaa/integrity.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/integrity.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,40.29 KB,/pc_backup/aaa/index.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/index.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,70 Bytes,/pc_backup/aaa/hints.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/hints.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,530 Bytes,/pc_backup/aaa/data/0/0
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Löschen,Datei,40.29 KB,/pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,40.29 KB,/pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,190 Bytes,/pc_backup/aaa/integrity.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,40.29 KB,/pc_backup/aaa/index.1.tmp -> /pc_backup/aaa/index.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,70 Bytes,/pc_backup/aaa/hints.1.tmp -> /pc_backup/aaa/hints.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,190 Bytes,/pc_backup/aaa/integrity.1.tmp -> /pc_backup/aaa/integrity.1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,190 Bytes,/pc_backup/aaa/integrity.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/integrity.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,40.29 KB,/pc_backup/aaa/index.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/index.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,70 Bytes,/pc_backup/aaa/hints.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/hints.1.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,17 Bytes,/pc_backup/aaa/data/0/1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Lesen,Datei,17 Bytes,/pc_backup/aaa/data/0/1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,17 Bytes,/pc_backup/aaa/data/0/1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/data/0/1
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,530 Bytes,/pc_backup/aaa/data/0/0
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/data/0/0
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Ordner,NA,/pc_backup/0
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,16 Bytes,/pc_backup/aaa/nonce-oo_7btec.tmp -> /pc_backup/aaa/nonce
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,16 Bytes,/pc_backup/aaa/nonce-oo_7btec.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/nonce-oo_7btec.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Löschen,Datei,209 Bytes,/pc_backup/aaa/config.old
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,209 Bytes,/pc_backup/aaa/config.old
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Umbenennen,Datei,209 Bytes,/pc_backup/aaa/config-wnpw1a_f.tmp -> /pc_backup/aaa/config
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Schreiben,Datei,700 Bytes,/pc_backup/aaa/config-wnpw1a_f.tmp
SMB,2023/02/11 08:20:30,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/config-wnpw1a_f.tmp
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Lesen,Datei,209 Bytes,/pc_backup/aaa/config
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Schreiben,Datei,58 Bytes,/pc_backup/aaa/lock.roster
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/lock.roster
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Umbenennen,Ordner,NA,/pc_backup/aaa/lock.exclusive.uyusjqd1.tmp -> /pc_backup/aaa/lock.exclusive
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/lock.exclusive.uyusjqd1.tmp/pc.xxx.net@8796755360620.602-0
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Erstellen,Ordner,NA,/pc_backup/lock.exclusive.uyusjqd1.tmp
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Umbenennen,Datei,209 Bytes,/pc_backup/aaa/config-o153yysn.tmp -> /pc_backup/aaa/config
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Schreiben,Datei,209 Bytes,/pc_backup/aaa/config-o153yysn.tmp
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/config-o153yysn.tmp
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Erstellen,Ordner,NA,/pc_backup/data
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Schreiben,Datei,73 Bytes,/pc_backup/aaa/README
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Erstellen,Datei,0 Bytes,/pc_backup/aaa/README
SMB,2023/02/11 08:20:25,x.x.x.x,pc,Erstellen,Ordner,NA,/pc_backup/aaa
```

# Workaround
Some Tests:
|NIC|OK - NOK|
|---|----|
|AMD PCNet PCI II (Am79C970A)|OK|
|AMD PCNet FAST III (Am79C973)|OK|
|Intel PRO/1000 MT Desktop (82540EM)|NOK|
|Intel PRO/1000 T Server (82543GC)|OK|
|Intel PRO/1000 MT Server (82545EM)|NOK|
|Paravirtualized network adapter (virtio-net)|OK|

Borg works with Version 1.1.16 & 1.2.3

Changed to AMD PCNet FAST III (Am79C973)
https://www.virtualbox.org/manual/ch06.html

**Comment by infectormp** [comment]
If workaround helps you then this is not the borg issue. You need to fill bug to Virtualbox

**Comment by lod911** [comment]
Could be, but what does the error-message from borg exactly mean? What happens and when does it happen, that borg fails? What can i tell oracle, that they can investigate? Does a file change after creation without any action of borg? Or what does the error mean?

At the moment, only borg has problems with this NIC. I run diverse VMs and no one has problems, except borg. Why?

**Comment by infectormp** [comment]
Do I understand it correctly, this corruption happens on `borg init`?

borg think that repo is corrupted somehow. To ensure that the problem in the VM you need try to do the same operations without VM.  
Also check repo for corruption using `borg check` https://borgbackup.readthedocs.io/en/stable/usage/check.html

**Comment by infectormp** [comment]
How much RAM and swap do you have in the VM?

**Comment by lod911** [comment]
Yes, on `borg init`.

There ist no problem without VM. The failure occurs only in VM guests.

`xxx@pc:~$ free -m
              gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
Speicher:       7957          75        7778           0         103        7698
Swap:            974           0         974`

**Comment by ThomasWaldmann** [comment]
From your description, it looks like the PRO/1000 NIC is corrupting data.

You can try again switching back and forth between PRO/1000 and virtio NIC and if the problem comes and goes accordingly, you can be quite sure it is that NIC.

That's a pretty serious error as basically everybody who is not using the virtio NIC uses the PRO/1000 instead, so definitely notify the virtualbox devs.

**Comment by ThomasWaldmann** [comment]
Tag "hardware issue" here refers to the virtual PRO/1000 NIC "hardware".

**Comment by ThomasWaldmann** [comment]
@lod911 Please add the precise virtualbox version number to your top post (and also where you got the virtualbox package from - is it from the virtualbox.org apt source or from debian apt source?).

**Comment by lod911** [comment]
Yes, when I switch de NICs, the problem comes and goes.

`VirtualBox Version 7.0.6 r155176 (Qt5.15.2)`

Source: 
`deb [arch=i386,amd64] http://download.virtualbox.org/virtualbox/debian bullseye contrib`

I'm currious, I am the only one with this problem? I think there should be more user with VirtualBox 7. The "Intel PRO/1000 MT Desktop (82540EM)" is the standard when you generate a new guest.

**Comment by infectormp** [comment]
You are the first who has raised this issue.

**Comment by lod911** [comment]
Some Tests:
|NIC|OK - NOK|
|---|----|
|AMD PCNet PCI II (Am79C970A)|OK|
|AMD PCNet FAST III (Am79C973)|OK|
|Intel PRO/1000 MT Desktop (82540EM)|NOK|
|Intel PRO/1000 T Server (82543GC)|OK|
|Intel PRO/1000 MT Server (82545EM)|NOK|
|Paravirtualized network adapter (virtio-net)|OK|

Unfortunatly, I have no clue from phyton. Is there maybe some easy code who is doing that, what borg does during "init"? So Oracle can maybe use this for doing some tests by them self?

**Comment by infectormp** [comment]
> what borg does during "init"?

This command initializes an empty repository.

**Comment by infectormp** [comment]
What NIC do you have on bare HW?

**Comment by lod911** [comment]
root@xxx:/home/xxx# lshw -C Network
  *-network
       description: Ethernet interface
       product: Ethernet Connection I217-LM
       vendor: Intel Corporation
       physical id: 19
       bus info: pci@0000:00:19.0
       logical name: eth0
       version: 05
       serial: 90:1b:0e:51:20:33
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=5.10.0-21-amd64 duplex=full firmware=0.13-4 ip=x.x.x.x latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:31 memory:fb100000-fb11ffff memory:fb139000-fb139fff ioport:f020(size=32)

**Comment by ThomasWaldmann** [comment]
@lod911 can you still reproduce this with the current virtualbox release? did you file a bug at virtualbox?

this doesn't look like a borg issue, so I'm tending to closing this here.

**Comment by lod911** [comment]
@ThomasWaldmann 
In the meantime I went back to virtualbox 6.1. There where to many (other) issues. I didnt file a bug at virtualbox.

I will close this bug. I thought, maybe its interessting for you. I also don't see this as bug of borg. 

Mybe at the end of this year I give virtualbox 7 a new try :)
