### ISSUE TITLE
extend Statistics class for "file changed while reading"

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7354]
Statistics class tracks some stats about the files borg backed up.

The "C" status is not yet considered there (not yet printed in `--stats` output) - borg uses it if a file has changed while we read it.

**Comment by shalearkane** [comment]
Can I work on this issue if it is not assigned or should I wait till the current issue at hand is resolved?

**Comment by infectormp** [comment]
@shalearkane all open and unassigned stuff can be taken.

**Comment by ThomasWaldmann** [comment]
@shalearkane it's easiest if you just make a PR, so we can discuss your code there.

**Comment by ThomasWaldmann** [comment]
@shalearkane you are working on this?

**Comment by shalearkane** [comment]
Yes, I am working on this. I am just caught up in my university mid-semester exams. I am intending post my PR on the 24th Feb. However, if this issue needs to be tackled fast, you can assign this to someone else.
