### ISSUE TITLE
fix Statistics.__add__

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7355]
because the file_stats defaultdict can contain different keys, it must iterate over `union(self.keys(), other.keys())` when adding up stats values.

**Comment by vhadzhiev** [comment]
Hi, can it be done by setting `stats.files_stats = self.files_stats` and then iterate the keys of `other.files_stats` and check if key is in `stats.files_stats`? If key is not present in the dictionary, create it. And finally `stats.files_stats[key] += other.files_stats[key]`.

**Comment by ThomasWaldmann** [comment]
@vhadzhiev something like that might work, but is too much effort and also a bit an asymmetric approach.

Just iterating over the union set of all keys is the symmetric approach and easier.

**Comment by vhadzhiev** [comment]
A very long one-liner here :)
`stats.files_stats = {key: (self.files_stats[key] + other.files_stats[key]) for key in self.files_stats.keys() | other.files_stats.keys()}`

I don't have much experience with defaultdicts, but as I read the docs, I really like it. The one-liner above will create normal dictionary. I also tested with another one-liner if the new dictionary can be initiated as defaultdict and it worked. 

`stats.files_stats = defaultdict(int, {key: (self.files_stats[key] + other.files_stats[key]) for key in self.files_stats.keys() | other.files_stats.keys()})`

Which one should be used if they are OK? Is it needed the new dictionary also to have the functionality of the defaultdict?

**Comment by ThomasWaldmann** [comment]
We need the lower one.

Could be a bit shorter via first doing:
```
st1, st2 = self.files_stats, other.files_stats
```

**Comment by vhadzhiev** [comment]
OK, 10x. I'll fix it it tomorrow and will create pull request.
