### ISSUE TITLE
Update Docs for setting up Development Environment?

### ISSUE THREAD

**Issue by shalearkane** [borgbackup/borg#7356]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?
Question

I have looked into https://borgbackup.readthedocs.io/en/stable/development.html#building-a-development-environment however, I had to install several packages related to compression algorithms libs. It would be nice for new contributors if these packages were mentioned so that the command `pip install -r requirements.d/development.txt` would run without issues on the first try on Linux.

**Comment by ThomasWaldmann** [comment]
Well, development actually requires the same setup as install borg from source (which is documented in the install section), so if we do not mention that already, that pointer could be added.

**Comment by abebeos** [comment]
Fixed in 

small docs update: https://github.com/borgbackup/borg/pull/7423 + small docs update https://github.com/borgbackup/borg/pull/7429
