### ISSUE TITLE
Fedora URL in docs/installation.rst seems to be outdated

### ISSUE THREAD

**Issue by voegelas** [borgbackup/borg#7357]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Minor issue

## System information. For client/server mode post info for both machines.

Not relevant

## Describe the problem you're observing.

The file [docs/installation.rst](https://github.com/borgbackup/borg/blob/8ada680c876e36d8c3222138415d922c137bd9d6/docs/installation.rst#distribution-package) points to https://apps.fedoraproject.org/packages/borgbackup, which doesn't redirect to the package description and gives me a "404 Not Found" error.

```rst
.. _Fedora official repository: https://apps.fedoraproject.org/packages/borgbackup
```

The address https://packages.fedoraproject.org/pkgs/borgbackup/borgbackup/ works for me.

**Comment by ThomasWaldmann** [comment]
@voegelas thanks for finding this, can you create a PR with a fix?

**Comment by FelixSchwarz** [comment]
Thanks Thomas, I did miss that you had additional commits on 1.1-maint. I cherry-picked some commits which seem relevant but the build still fails:
```
_____________ ArchiverTestCase.test_compression_auto_compressible ______________
self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_compression_auto_compressible>
    def test_compression_auto_compressible(self):
        size, csize = self._get_sizes('auto,zlib', compressible=True)
        assert csize < size * 0.1
>       assert csize == 35  # same as compression 'zlib'
E       AssertionError: assert 53 == 35
build/lib.linux-s390x-3.6/borg/testsuite/archiver.py:2255: AssertionError
```

Anyway, thank you for maintaining borg the way you do (long branch maintenance, using system libraries, ...) - it really makes distro packaging much easier even though it is a lot of extra work for you.

**Comment by ThomasWaldmann** [comment]
Note: I copied that #7363.
