### ISSUE TITLE
chunkid == id_hash(plaintext) - better always check?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7362]
Just a brain dump, so I don't forget, needs checking in the source.

## borg < 2.0

After reading a chunk from the repo, it calls `assert_id` to check whether `wanted_chunkid == H(plaintext_content_we_got_from_repo)`.

This is rather expensive on the CPU as all data is going through hmac-sha256 or blake2b, but back then this was the only way to make sure we really got the right data for the chunkid we wanted. Without doing that check, the repo could cheat and just give us data for another chunk (which would be also encrypted and authenticated, but the client would not know that it is the data for another chunkid).

## borg2 (master branch)

Currently omits the calls to `assert_id` because it does the crypto a bit differently (AEAD):
- when the client writes data to the repo, it puts the chunkid into the "AD" (additional data) part of AEAD. That part is not encrypted, but it is authenticated ("signed").
- When reading a chunk from the repo, the AEAD crypto will authenticate all data (including the chunkid) and if successful, will decrypt the encrypted part also. So, if we can successfully aead-auth-decrypt, we know that the chunkid is exactly as it was written by the client and that the data is also as written by the client. 
- if we assume the client was **well-behaved**, we do not need to call `assert_id`, because we can just check if the chunkid in the AD part is the same as the chunkid we wanted. This is good for performance.
- the repo can not cheat on the client by just returning a different chunk: it would be very obvious as it would have a different chunkid in the AD part.
- but, if we can not rely on that a well-behaved client has written the data correctly, I guess we still would need to call `assert_id`. E.g. there could be malware on the client at backup time that uses modified, evil borg code that writes a wrong chunkid into the AD part when writing data to the repo (to the same, wrong chunkid key). In that case, the AEAD would work as usual, but it would sign chunkid and data without `chunkid == H(plaintext)` being true.
- a well-behaved borg client could detect such a evil borg chunk when calling `assert_id`. but that requires that a well-behaved borg client is used (and not the same "evil borg" that made the bad chunks).

Discuss: how do we deal with that in borg2?

- always call `assert_id` and spend the additional cycles?
- only do it in some *paranoid mode* and otherwise omit it?

**Comment by horazont** [comment]
Sounds like something for borg check, not for regular operations.

**Comment by taqiohr** [comment]
> Sounds like something for borg check, not for regular operations.

This only applies when you have access to the plaintext - so decryption happens anyway - and then you can omit the additional hash by putting the chunk ID in the AAD. So, it is a performance win for borg check but also other operations which decrypt like restoring.

**Comment by horazont** [comment]
Ah I see, I wasn't aware that the archive check may read chunks multiple times.

**Comment by awgcooper** [comment]
As a non-coder, I am always going to prize data integrity over a speed. An evil borg client is probably not a very likely scenario (although more so nowadays) but I'd still prefer whatever protection is available. As a general UX point, I've never found speed an issue so not having a potential AEAD-related speed-up in borg2 doesn't strike me as a loss. If you hived off `assert_id` into a paranoid mode, I'd use paranoid mode.

**Comment by ThomasWaldmann** [comment]
#7367 makes this play safe for now.

Not sure if we really need a less safe, faster mode and take risks.
