### ISSUE TITLE
Unable to use borg with gcsfuse (failed to acquire lock)

### ISSUE THREAD

**Issue by mcaceresb** [borgbackup/borg#7366]
`borg` runs successfully both with external physical media (via USB), over ssh, and in local folders. However, I also have a backup in google cloud that I mount via `gcsfuse`. Sometime last year this stopped working.

## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes.

#### Your borg version (borg -V).

borg 1.2.3

#### Operating system (distribution) and version.

Arch Linux (6.1.11-arch1-1)

#### Hardware / network configuration, and filesystems used.

I am mounting a google cloud bucket via [`gcsfuse`](https://github.com/GoogleCloudPlatform/gcsfuse).

#### How much data is handled by borg?

0

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg init --encryption=repokey test
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. I encounter the issue even just trying to initialize a repo.

```
gcsfuse home-backup /home/mauricio/home-backup
cd /home/mauricio/home-backup
borg init --encryption=repokey test
```

I later tried adding `--foreground --debug_gcs` options to `gcsfuse` to look for any clues; I saw that the log kept saying `test/lock.exclusive` not found. However, it said this for seemingly every file it tried to create, even though it successfully created them (I could see at least some files being created and deleted as the command ran, and in the end I was left with a `config` file, a `README`, and an empty `data` folder inside of `test`, which previously did not exist).

#### Include any warning/errors/backtraces from the system logs

From the `borg` command:

```
Failed to create/acquire the lock /home/mauricio/home-backup/test/lock.exclusive (timeout).
```

**Comment by ThomasWaldmann** [comment]
Looks like you found an issue in gcsfuse, please file a bug there.

**Comment by RonnyPfannschmidt** [comment]
it seems gcs is never able to provide posix semantics

**Comment by mcaceresb** [comment]
Fixed following the advice [here](https://github.com/GoogleCloudPlatform/gcsfuse/issues/942#issuecomment-1436296284).
