### ISSUE TITLE
Suggestion: faster --repair after check

### ISSUE THREAD

**Issue by mischaelschill** [borgbackup/borg#7369]
This is a suggestion/feature request.

I have a rather large remote repository, around 3TB. Running a borg check takes hours to complete, which is manageable. But if it finds an error I want to correct with --repair, it (seems to) start from scratch. Would it be possible to somehow store the result from a borg check to make the subsequent --repair faster?

**Comment by ThomasWaldmann** [comment]
IIRC we already have another ticket with the idea that `borg check` could work like `borg check --repair` and interactively ask whether to commit any repairs at the end.

**Comment by ThomasWaldmann** [comment]
Closing in favour of #2398.
