### ISSUE TITLE
Is there any disadvantage in speed/reposize using "borg create --content-from-command -- tar -c $PATH" instead direct "borg create $PATH"

### ISSUE THREAD

**Issue by qupfer** [borgbackup/borg#7376]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

##

Hi,
I'm trying to create an script, which backup my lxd container/vms to borg. 
Basicly, It just create a new snapshot and send it to borg. 

I can just use the snapshot dir as PATH for borg create. Very easy, best way for "just store" I think. 
However, for a restore, I have to extract all and make a tar archive with some small modifications (rename a folder and add a yaml).
That means I need ~ 2x container size as temporary disk storage.

The other way I can do: Runing tar over the snapshot dir, doing the "tar modifications" directly and use it as stdin input for borg create. 
For restore, I just need to extract the - ready-to-use - stdin-archiv. More elegant for this usecase, but "feels" more slowly.

But I'm not sure, if its just a "feeling" or if there a (big) differences, speacily in repo-size.  Of course, the tar process itself needs a bit time. But as it is uncompressed, I think it should not be noticeably. 

Can someone with deeper borg knowledge give me same information about the expected disadvantages using a pre-tar command instead running borg directly?

**Comment by ThomasWaldmann** [comment]
Borg's **files cache** uses file metadata (e.g. ctime, size, inode number) to quickly determine unchanged files. It can create a backup of a unchanged file very quickly, without reading its contents.

That of course only works with a filesystem, not if you feed a tar stream into borg.

Also, if you feed a tar stream, there won't be visible boundaries between the content of the files, which influences how borg cuts chunks (a file end usually is a chunk end also).

So assuming you do backups way more often than restores, maybe backup as is (fs) and post-process at restore time, if needed.
