### ISSUE TITLE
update docs (46)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7398]
there are quite some docs issues: https://github.com/borgbackup/borg/labels/documentation

grab some doc update issues, create a PR against master (and, after discussion, also to 1.2-maint, if applicable, see here, also linked from PR submission template)

the bounty is for fixing 2 small issues or 1 bigger issue.
docs issues that already have a bounty on them do not qualify.

---

:moneybag: [there is a bounty for this](https://app.bountysource.com/issues/117547819-update-docs-46)

**Comment by abebeos** [comment]
@ThomasWaldmann , Bountysource is usually "one entry per issue", what is the bounty process here?

> the bounty is for fixing 2 small issues or 1 bigger issue.

The issues should have a marker "small", so things are clear and transparent right from start.

**Comment by abebeos** [comment]
> This is just to keep management overhead down.

I assume for you. Because for me, it is more overhead (starting with asking "what is the process?").

What is the process?

**Comment by ThomasWaldmann** [comment]
Update some docs, make a PR.

If you only fix a little, it will only be half of the bounty ticket.

**Comment by abebeos** [comment]
>>Most importantly: Is the amount in escrow, and how/when is it payed?
> You can read more at bountysource.com.

No, I can't, as you don't stick to the bountysource process.

**Comment by ThomasWaldmann** [comment]
Strangely, noone yet had a problem with that. So either try or fix issues elsewhere. :-)

**Comment by abebeos** [comment]
> Strangely, noone yet had a problem with that. 

code-monkeys vs. process-thinker

> So either try or fix issues elsewhere. :-)

I extract: you refuse to clarify what your modified (bountysource-) process is.

**Comment by abebeos** [comment]
> There is no modified process.

Correct. Your process is your (very personal) process.

What is relevant however:

you refuse to clarify what your modified (bountysource-) process is.

=> modified (bountysource-) process

Anyways, backing off here, enough played.

**Comment by abebeos** [comment]
small docs update: https://github.com/borgbackup/borg/pull/7423 + small docs update https://github.com/borgbackup/borg/pull/7429

**Comment by abebeos** [comment]
@ThomasWaldmann , ty for the payment!
