### ISSUE TITLE
add debug commands for repoobj id_hash/parse/format

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7406]
#7405 fixed `borg debug put-obj / get-obj`:
```
borg debug get-obj id file  # read object id from repo, write it to file
borg debug put-obj id file  # read file, write it to object id in the repo
```

Sometimes, IDs are mentioned in error messages, so `get-obj` can be used to read an object with the known id from the repo and write it to some file. But in borg2, the file format is non-trivial: encrypted/msgpacked chunk metadata plus encrypted/compressed chunk data.

But, `put-obj` alone is not very useful yet in general, because the id must be given, but is usually non-trivial to compute.

Also, to parse or format the repo object format, we need debug wrappers
```
borg debug id-hash file  # read plaintext file, compute the object id from it
borg debug parse-obj objfile  # read object file, parse the object into meta dict and data (decrypting, decompressing)
borg debug format-obj file  # read plaintext file, format it into a compressed, encrypted object with a meta header
```

These functions can all be found in `repoobj.py`.

**Comment by shalearkane** [comment]
I am working on this, issue. I am trying to understand how the id_hash can be calculated. Here's what I understand. 

- id-hash is calculated by the function (which must be implemented by the derived `Key` classes): https://github.com/borgbackup/borg/blob/611e391da907e420631ffbd5dca2c931e54ad619/src/borg/crypto/key.py#L195-L197
- In `1.2maint` you registered a new command, https://github.com/borgbackup/borg/blob/cef5b446acf66cdcdd1d545ecb99ea28e62608c3/src/borg/archiver.py#L3745-L3758
- and you implemented this function https://github.com/borgbackup/borg/blob/cef5b446acf66cdcdd1d545ecb99ea28e62608c3/src/borg/archiver.py#L2210-L2217
- In the above function, the decorator https://github.com/borgbackup/borg/blob/cef5b446acf66cdcdd1d545ecb99ea28e62608c3/src/borg/archiver.py#L2210 returns the derived Key class by parsing the repository.

However in `master` branch, the `with_repository` decorator https://github.com/borgbackup/borg/blob/611e391da907e420631ffbd5dca2c931e54ad619/src/borg/archiver/_common.py#L74-L160 does not pass the `key` in its `kwargs`.

So implementing the same thing in borg2 requires me to implement detecting and passing `key` in `kwargs` in `with_repository`, right?

**Comment by ThomasWaldmann** [comment]
You'll usually just use `manifest.repo_objs` (see also `repoopj.py`).

**Comment by shalearkane** [comment]
Where should the output of the id-hash go? To stdout/stderr or to a file?

**Comment by ThomasWaldmann** [comment]
guess stdout would be good.

**Comment by shalearkane** [comment]
Also, how do I get the object id for the objfile to be parsed in parse-obj? The `parse` function requires both `id` and `cdata`. I read the [docs](https://borgbackup.readthedocs.io/en/stable/internals/data-structures.html) but I am unable to understand how to get objectid from objectdata.

**Comment by ThomasWaldmann** [comment]
The user would start from knowing some interesting ID, then:
- `borg debug get-obj ID PATH`
- `borg debug parse-obj ID PATH ...`

**Comment by shalearkane** [comment]
The implementation in nearly complete. I have got two issues regarding i/o,
- The `parse()` function returns `tuple[dict,bytes]` (or a `tuple` of `meta` and `uncompressed data`. Outputting to `stdout` may not make sense, so I suggest outputting as a pickle file.
- The `format()` function takes in `id: bytes`, `meta: dict` and `data: bytes`. Taking in `meta: dict` might be awkward to take in through `stdin`. I suggest taking the input as a pickle file.

Should I implement as described above or should I take a different approach?

**Comment by ThomasWaldmann** [comment]
parse: while a pickle is fine for python, not all borg users are pythonistas. So guess we should write a json file and a binary data file.

format: same, meta from json, data from binary file.
