### ISSUE TITLE
msgpack 1.0.5 out

### ISSUE THREAD

**Issue by 0-wiz-0** [borgbackup/borg#7417]
borg is quite restrictive in msgpack versions it accepts. This is sometimes a problem for packaging systems that only provide the latest version.
[1.0.5 is out](https://github.com/msgpack/msgpack-python/blob/main/ChangeLog.rst#105), is it fine to use this with borg?

**Comment by ThomasWaldmann** [comment]
> borg is quite restrictive in msgpack versions it accepts.

That's intended. There have been broken releases and you don't want bad 
backups just because msgpack wasn't tested enough.

> 1.0.5 is out 
> <https://github.com/msgpack/msgpack-python/blob/main/ChangeLog.rst#105>, 
> is it fine to use this with borg?

I will run the platform tests with that ASAP and we'll know afterwards.

**Comment by ThomasWaldmann** [comment]
#7419 for 1.2-maint branch

Platform tests still todo. The msgpack changelog looked rather harmless.

**Comment by ThomasWaldmann** [comment]
I plan doing a 1.2.4 release soon, see the milestones.

**Comment by ThomasWaldmann** [comment]
considering that both branches are updated, I'll close this now.

the platform testing will happen anyway as part of the release process, maybe also in a test run before.
can't do it right now because my in-house wifi bridge just died. :-(

**Comment by ThomasWaldmann** [comment]
borg 1.2.4 was just released and accepts msgpack 1.0.5 also.
