### ISSUE TITLE
Borg asking for key file when upgrading unencrypted repository

### ISSUE THREAD

**Issue by ple0x** [borgbackup/borg#7418]
Evening,

So i have an unencrypted borg backup repository which im trying to upgrade. The problem is, when running the borg backup command borg replies with "no key file found for repository".

I'm a bit confused about this situation since the repository in question is unencrypted therefore theres no key for it.

**Comment by infectormp** [comment]
@ple0x what borg version do you use?

**Comment by ThomasWaldmann** [comment]
also please give the borg commands you tried.

**Comment by ThomasWaldmann** [comment]
Just a guess: if you have corrruption in your repo files and the type byte in the repo manifest changed from "unencrypted" to "encrypted", that could lead to that behaviour.

**Comment by ThomasWaldmann** [comment]
No reply, closing.
