### ISSUE TITLE
Borg suddenly fails to create archive in server machine over ssh, throws OSError: [Errno 5]

### ISSUE THREAD

**Issue by rikrdo89** [borgbackup/borg#7426]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
client: Ubuntu 20.04 
server: Ubuntu 20.04 

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

borg create  --stats --progress --compression auto,zstd,3 ssh://user@xxx.xx.xx.xx:xx/myrepo/::archive myfiles

## Describe the problem you're observing.
When creating an archive, borg seems to be  `syncing chunks cache` for up to 80%, and then suddenly stops and throws the following error: 
```
Traceback (most recent call last):ing archive xxxxx

  File "/usr/lib/python3/dist-packages/borg/remote.py", line 247, in serve
    res = f(**args)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1117, in get
    return self.io.read(segment, offset, id)

  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1481, in read
    header = fd.read(self.put_header_fmt.size)

OSError: [Errno 5] Input/output error
```
I can however  access the archive over ssh and even list the archives with borg remotely `borg list ssh://user@xxx.xx.xx.xxx:xx/myrepo`, so there is no Input/output issues. Even more, If I can log into server that host the repo, I can create a local archive to the repo without issues.

**Comment by infectormp** [comment]
This is an issue below borg. hardware, kernel / filesystem, something is broken there.
https://github.com/borgbackup/borg/issues/4087
https://github.com/borgbackup/borg/issues/5749

**Comment by rikrdo89** [comment]
Even though I can access the remote drive that is used to store the borg repo, and I am still able to create a borg archive to that same repo within the host server? Also fsck.ext4 shows no issues with the filesystem. It seems like the issue is coming from the client running borg...

any way to begin troubleshooting this?  Some of the post suggest clearing cache... how can I do that in the client machine?

**Comment by infectormp** [comment]
If you can create a local archive to the repo perhaps the problem is not on the remote host. Check hdd\fs on a client side.

**Comment by rikrdo89** [comment]
The client doesn't seem to have any issues (SSD). Does it help that borg running in the client machine always stop when it reaches 86% of `syncing chunks cache`  ? Could this be a cache issue? anyway to rebuild cache from the client side?

**Comment by infectormp** [comment]
Did you have enough space?

**Comment by rikrdo89** [comment]
mmm... the client where I am trying to start the backup has only 10GB of storage left, would that be an issue when borg is reading the repo? (The remote server where the repo is hosted has several TBs)

**Comment by rikrdo89** [comment]
To clarify, the client has 10GB left for the OS, but borg and its cache files are in a partition with several 100sGB of SSD. 
Looking at the cache, I see that within the repo ID, there is `/chunks.archive.d` and also `/txn.active`. I don't think I have seen that last file before.

**Comment by ThomasWaldmann** [comment]
If the repository code throws an I/O error, this is for sure an issue inside the repository (and if the repo is remote: an issue on the remote server side, not on the borg client side).

**Comment by rikrdo89** [comment]
When I am in the remote, I can create an archive in the repo without any issues.  I just run it with and it outputs the stats without errors 

```
[myserver] $ borg create  --stats --error --compression auto,zstd,3 /myrepo/::myarchive /myfiles
Enter passphrase for key /myrepo:
------------------------------------------------------------------------------
Archive name: myarchive
Archive fingerprint: xxxxxxxx
Time (start): Fri, 2023-03-10 12:42:44
Time (end):   Fri, 2023-03-10 12:42:47
Duration: 2.63 seconds
Number of files: 52
Utilization of max. archive size: 0%
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
This archive:               14.80 MB             11.53 MB              3.83 kB
All archives:              133.15 TB            121.00 TB              4.34 TB

                       Unique chunks         Total chunks
Chunk index:                 2392456             61409524
------------------------------------------------------------------------------
```

**Comment by ThomasWaldmann** [comment]
@rikrdo89 that might be, but that is not relevant.

**Comment by rikrdo89** [comment]
Could you please explain what you mean? I thought you said this looks like an issue on the remote server side, but the remote server can create archives into the repo without issues. I am failing to see how that is possible.

**Comment by ThomasWaldmann** [comment]
So, better check that hardware, filesystem, RAM and **only after fixing that** try `borg check`.

If you want a thorough check (that reads all content data), you'll need `borg check --verify-data`.

**Comment by ThomasWaldmann** [comment]
Creating a new archive does not read content data that is already contained in the repo.

So if there is e.g. some bad sector in some segment file, that will not be discovered.

**Comment by rikrdo89** [comment]
Wouldn't that be the same when creating a new archive from the client? You don't think this is a cache issue at all? It is just it stops when it is `syncing chunks cache` ...

**Comment by ThomasWaldmann** [comment]
If you use a `ssh://...` repo with borg, the `repository.py` code is executed on the server side.

In the traceback you have posted, you see it is crashing there because the OS gave an I/O error to borg instead of the data it wanted to read from some repo segment file.

If the chunks index/cache gets out of sync because you use one repo from multiple places, borg will need to resync that. It then reads infos from ALL archives, either from the local chunks.archives.d/  directory or from the remote repo.

BTW, just as a side note: if you access the repo, always use the same user to not mess up permissions for the repo files (e.g. by sometimes using "borg" and other times using "root").

**Comment by rikrdo89** [comment]
I see... I just try creating an archive from another client that also backs-up to the same remote repo and It is throwing the same error. So if all this indicate that there is a bad sector in a segment file.... is there a way I can fix this to continue backing up to my repo? (I don't mind losing the last archives as long as I haven't lost all the archives) Could you point me in the right direction to solve this? thanks!

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/7426#issuecomment-1464157052 that is the recommeded procedure.

if you do not fix the hw / fs issue first, you might make it worse by running `borg check --repair`.

**Comment by rikrdo89** [comment]
OK, I jsut run `sudo fsck.ext4 -y /path/to/BorgDrive` and there seems to have been some issues in the drive. A second check did not find any remaining issues.  I am running `borg check` but it looks like it will take some hours to complete... I'll report back if I get this sorted out or if I am left without a backup  :(

**Comment by rikrdo89** [comment]
The `borg check` also threw an I/O error after a few hours.  However, since I can mount archives from the server machine, I was able to figure out that there is an archive in the repo that is throwing the I/O error. How do you recommend removing that archive ?

```
$ borg check /path/to/repo
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 341, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 971, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1415, in iter_objects
    if fd.read(MAGIC_LEN) != MAGIC:
OSError: [Errno 5] Input/output error
```

**Comment by rikrdo89** [comment]
running `borg check -v --archives-only path/to/repo` also throws an I/O error when arriving to the same (possibly corrupted) archive (archive n42):
```
$ borg check -v --archives-only /path/to/repo
Starting archive consistency check...
Enter passphrase for key /path/to/repo:
Analyzing archive XXX_2022-06-23_00h45m (1/46)
...
Analyzing archive XXX_2023-03-02_01h00m (42/46)
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 345, in do_check
    if not args.repo_only and not ArchiveChecker().check(
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1244, in check
    self.rebuild_refcounts(archive=archive, first=first, last=last, sort_by=sort_by, glob=glob)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1631, in rebuild_refcounts
    for item in robust_iterator(archive):
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 1573, in robust_iterator
    for chunk_id, cdata in zip(items, repository.get_many(items)):
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 1083, in get_many
    for key, data in zip(keys, self.repository.get_many(keys)):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1123, in get_many
    yield self.get(id_)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1117, in get
    return self.io.read(segment, offset, id)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1481, in read
    header = fd.read(self.put_header_fmt.size)
OSError: [Errno 5] Input/output error
```

idk what is the best way to proceed. As a note, I am still able to create and mount archives to this repo from the server side (except for archive n42 )

**Comment by ThomasWaldmann** [comment]
As I said, first fix your hardware. If that disk is having errors, copy your repo to a working disk before you proceed.

**Comment by rikrdo89** [comment]
I thought I fixed the fs errors by running `sudo fsck.ext4 -y /dev/partition` ... or do you mean something else by fixing the hw? So at this point, is there anything else to do since the `borg check` throws the input/output error?

**Comment by rikrdo89** [comment]
Here is the output of my checks:

```
$ sudo fsck.ext4 -y /dev/sdd2
e2fsck 1.45.5 (07-Jan-2020)
bak_10TB: clean, 8893/305176576 files, 1091994383/2441406208 blocks

$ sudo smartctl -a /dev/sdd2
...
SMART Health Status: OK.
....

```

**Comment by ThomasWaldmann** [comment]
The overall "SMART health status" is known to switch rather late to "FAILING" (suspicion: HDD manufacturers don't like you to return stuff while it is in warranty).

If you like, post the complete output of `smartctl -a /dev/sdd` (note the absence of the partition number) so we can have a look.

**Comment by rikrdo89** [comment]
ok thanks. I started the smart long test on the whole HDD.... it looks like it will take ~24hrs.

So if I understand correctly, there is a bad sector in the HDD that seems to be affecting one of the archives (number 42 out of 46) and that's why borg is receiving an input/output error when it gets to that archive. Did I get this right? and if this is the case,  is there a good way that I could "rescue" or "copy" archives 1 to 41 with borg?

I guess I could manually load each archive and rsync the contents, to another drive, and then create an archive one by one... but this would take weeks.... Please I would appreciate any suggestions you might have. Thanks

**Comment by rikrdo89** [comment]
fyi... I tried `borg delete -v --force /path/to/repo::archive42` but  also failed with the same I/O error...

**Comment by ThomasWaldmann** [comment]
Not sure why you are continuing to work with borg on that defective disk after I advised you should copy the repo to a new disk and continue there. You can just try to cp, rsync or a file manager to transfer the repo directory to a new disk.

If it can not read all the files, then just copy as much as still readable.

After that is finished, run `borg check --repair` on the repo **on the new disk**.

**Comment by rikrdo89** [comment]
Sorry I didn't understand your prev recommendation. I'll copy as much as i can and do a check repair in the new drive. When copying the repo with rsync, do you recommend to keeping the hardlinks as in `rsync -aH` ?

**Comment by ThomasWaldmann** [comment]
`rsync -avH src/ dst/` is what I usually use. Maybe also `--numeric-ids`, depending on the use case.

IIRC, borg doesn't use hardlinks inside the repo except for secure erasing the old version of the repo config after it has written an updated one. So using `-H` is maybe not really required, but also does no harm.

**Comment by rikrdo89** [comment]
I was able to copy my repo to a brand-new drive, and I proceeded to run the borg checks (repo + archives), but this time it is raising an different error (file or directory no found) before the checks are over. I suspect that the missing file is prob from my archive number 42, so I tried to force `borg delete` that archive, but still it raises the same error. Should I manually delete the path in the archive? I appreciate your help with this issue.

here is the error:

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1361, in get_fd
    ts, fd = self.fds[segment]
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
KeyError: 8971

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4621, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4553, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 177, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1283, in do_delete
    return self._delete_archives(args, repository)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1340, in _delete_archives
    archive.delete(stats, progress=args.progress, forced=args.forced)
  File "/usr/lib/python3/dist-packages/borg/archive.py", line 846, in delete
    for (i, (items_id, data)) in enumerate(zip(items_ids, self.repository.get_many(items_ids))):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1123, in get_many
    yield self.get(id_)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1117, in get
    return self.io.read(segment, offset, id)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1479, in read
    fd = self.get_fd(segment)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1363, in get_fd
    fd = open_fd()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1344, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/repo/data/8/8971'

```

**Comment by rikrdo89** [comment]
Hey @ThomasWaldmann , thanks a lot for all your help. I think it is almost fixed.  After running  `borg check --repair ` on the repo and on the archives (and waiting patiently for hours), the missing chucks have been replaced with zeros. Looking at the repair logs, I think the issue could have resulted in part from a file that was being accessed while the automatic borg backup was running... which could have caused a hiccup on the HDD (or the HDD is ready for the trash). In any case, After the repairs, all the repo and archive checks are completed and no problems are found!!! (albeit from the missing chunks that are now zeros).

So my last questio: at this point that all the checks are ok, what should be the best sequence of next steps to deal with missing chunks? A --> B--> C?
A) Clear local cache with ` $ borg delete --cache-only $REPO`
B) Delete corrupted repo(s) from oldest to news  `$ borg delete --force REPO::CORRUPT_ARCHIVE`
C) Create a new archive and hope the missing chucks are recreated with `$ borg create`

**Comment by rikrdo89** [comment]
It's all fixed now, no more empty or missing chunks. After `borg check --repair` , I deleted the corrupted archive and the newer ones after that (I don't know if this was necessary, but it worked in my case).  I have created archives from different client machines and it all has completed successfully. Doing a `borg check` no longer throws any errors. Also FYI, I didn't need to delete any caches.

Thank's for all the help!

**Comment by ThomasWaldmann** [comment]
Usually there is no problem with parallel (read) access to files on linux, so I guess your HDD might be defective. And you shouldn't have multiple things writing to your borg repo in parallel (borg uses locks and nothing else than borg should write into there anyway).

 If you post `smartctl -a /dev/sdx` output, we can have a look (if one looks at the detailled stats, it usually becomes rather clear - just ignore that overall health value).
