### ISSUE TITLE
import-tar for multiple or concatenated tar files

### ISSUE THREAD

**Issue by dotdoom** [borgbackup/borg#7432]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.2.3

#### How much data is handled by borg?

400-500 GB

#### Description

tl;dr: could `borg import-tar` support multiple tar archives, or a file made by simply `cat`-entating several tar files?

Use case / situation: a few hundred GB of exported data is split into multiple tar files by size (50 GB each) rather than content.

Solution A: use `tar --catenate` to combine those into a single tar, then use `borg import-tar`.  Unfortunately GNU tar has a bug that prevents it from concatenating more than one archive at a time, and concatenating one by one is too expensive due to implementation (see https://superuser.com/a/1098273).

Solution B: use `cat 1.tar 2.tar ...` and feed that into `borg import-tar`.  Simply catenating tar archives doesn't produce a completely valid combined archive due to zero-padding.  That padding can be ignored during extraction with `--ignore-zeros` flag of `tar` (https://www.gnu.org/software/tar/manual/html_node/concatenate.html) but that isn't currently supported by `borg import-tar` as far as I can tell from experimenting.  Perhaps this could be implemented similar to libarchive (https://github.com/libarchive/libarchive/issues/457).

What would work is either `borg import-tar` supporting multiple files in a command line, or `--ignore-zeros` inspired option.  I have a preference for the latter for simplicity.

Note the issue is similar to #6807 by title, but that question is about having a directory per tar archive, which is unpreferred in this case.

**Comment by ThomasWaldmann** [comment]
I don't know, you could just try. borg uses python stdlib's `tarfile` module.

Considering that we can't easily change what is supported by that module, this is not a borg issue. Maybe newer python versions (== with newer `tarfile` versions) have more features / less bugs, but we can't implement that inside borg.

Another solution is to just match the separation you had with the tarfiles into equivalent archives inside a borg repo (you could maybe even take the .tar filename as archive name for borg).

**Comment by ThomasWaldmann** [comment]
Supporting multiple tar files: does not exist as a feature yet, but maybe someone wants to implement.

**Comment by dotdoom** [comment]
> you could just try

I did.  See the problem described in solution B.  This doesn't work today.

> separation you had with the tarfiles

This won't work so well, since files are split by size rather then content (see first post).

> Supporting multiple tar files

I guess that's the only option then.

**Comment by dotdoom** [comment]
Actually tarfile.TarFile has `ignore_zeros` parameter.  Could borg use it?

**Comment by ThomasWaldmann** [comment]
Yes, borg could use that.

The question then is whether borg could just always set that to True or whether that would break normal operation somehow (and it would need a borg cli option to enable this).

**Comment by dotdoom** [comment]
Certainly shouldn't be the default when reading from a tape (or other unstructured media), as tar doesn't have another stop marker and if the tape is any longer than the archive (which it should), tar will read garbage.  Although I'm not sure how popular tapes are these days among borg users.

GNU tar doc hints that there are some implementations that could write garbage after the zeros block: https://www.gnu.org/software/tar/manual/html_node/Ignore-Zeros.html -- can't comment on that, never looked that close at my archives.

Is it expensive to get a borg cli option?

**Comment by ThomasWaldmann** [comment]
I don't think many people still use tapes. But OTOH, we don't want to hold people back from migrating from tapes to borg.

So, if that "zero block" acts as end-of-file / end-of-archive marker in case of tapes, I guess we'll need that option.

If you'ld like to implement this, have a look at borg master branch, `src/borg/archiver/tar_cmds.py` (or so) and make a PR.

**Comment by ThomasWaldmann** [comment]
Hmm, if we use that additional option and the default is like current behaviour, guess this is harmless enough to get added to 1.2-maint even.

**Comment by dotdoom** [comment]
I'll dust off my Python skills and give it a try.  In the meantime, a fast solution I found is to use `bsdtar`, which doesn't have the same bug as GNU tar when concatenating, and also allows to merge archives to stdout instead of back to disk first:

```shell
$ find /raw/archives/dir/ -type f -name '*.tgz' -print0 | \
    xargs -0 -- printf '@%s\0' | \
    xargs -0 -- bsdtar -cf - | \
    borg import-tar ...
```

**Comment by ThomasWaldmann** [comment]
@dotdoom are you working on this?

asking because i'll release 1.2.4 soon and this is one of the last issues that could be fixed for that release.

**Comment by dotdoom** [comment]
@ThomasWaldmann let me take a stab at it tomorrow, I’ll draft a PR and ping it to you, then we decide if I’m capable of finishing it. Thanks for the reminder!

**Comment by dotdoom** [comment]
@ThomasWaldmann went with #7460.  I'll hold the backport to maintenance branch to keep it in sync with feedback on master branch PR.
