### ISSUE TITLE
Error running borg-freebsd64 on freenas 9.3

### ISSUE THREAD

**Issue by dyu** [borgbackup/borg#744]
I get:
```
/tmp/_MEI0ddP11/libthr.so.3: Undefined symbol "__set_error_selector"
```

**Comment by dyu** [comment]
Version 1.0.0 downloaded from your release page.

**Comment by enkore** [comment]
I'd say your FreeNAS 9.3 libc is too old for the prebuild binary.

__set_error_selector was added here: https://lists.freebsd.org/pipermail/svn-src-head/2015-January/066488.html in r276681

Maybe try updating it?

**Comment by dyu** [comment]
Well, not sure what side effects are caused by upgrading to that libc.
I'm assuming you built that binary on a freebsd 10.
Building that binary on a freebsd 9.x would work, though would be extra work on your end :-)
I can do that myself if you can share your build scripts for freebsd.

**Comment by ThomasWaldmann** [comment]
See the Vagrantfile in the repo about how to build on freebsd.
The precise build platforms are also described there (plus documented in the readme of the binaries).

@dyu side effects by installing a bad or incompatible (g)libc can be major, either do not try or at least be very careful there.

**Comment by ThomasWaldmann** [comment]
If FreeBSD 9 is still popular, something to consider would be whether binaries built on FreeBSD 9 also work on FreeBSD 10. If so, we could maybe just build on FreeBSD 9?

How about security updates? Is FreeBSD 9 still getting them?

**Comment by bbqsrc** [comment]
FreeBSD 9 is still a supported distribution of FreeBSD.

FreeBSD 9 and 10 have significantly differing toolchains (9 uses gcc, 10 uses clang) so they need different binaries.

**Comment by ThomasWaldmann** [comment]
@bbqsrc thanks for the info. so, how widespread is freebsd 9 - should we build binaries for it (if possible)?

**Comment by bbqsrc** [comment]
I haven't got exact numbers, but I am a package maintainer for FreeBSD, and when I build something that is only compatible with FreeBSD 10 and above, I *always* get emails about it asking where FreeBSD 9 support is, so there's quite a few people still using 9. If it's not too hard to do, it'd be worth adding support.

**Comment by jungle-boogie** [comment]
FreeBSD 9.3 will be EOL 31 December, 2016: https://www.freebsd.org/security/security.html#sup

**Comment by ThomasWaldmann** [comment]
Note: the 1.0.0 binary was built on FreeBSD 10.2.

**Comment by ThomasWaldmann** [comment]
From current FreeNAS release notes: "The base OS version for FreeNAS 9.10 is now FreeBSD 10.3-RC3, ...".

So, guess this issue could be resolved by using a FreeNAS version that uses FreeBSD 10.2 or newer. I am not totally sure about binary compatibility with newer OS, but it obviously does not work on older OS.
