### ISSUE TITLE
Usage of environment variables causes crash

### ISSUE THREAD

**Issue by jimboolio** [borgbackup/borg#7444]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

borg 1.2.3

#### Operating system (distribution) and version.

AlmaLinux 9.1 (Lime Lynx)

#### Hardware / network configuration, and filesystems used.

Local only
XFS + LUKS

#### How much data is handled by borg?

At this point zero bytes

## Describe the problem you're observing.

```
REPOPASSWD="helloworld"

CONFIG_DIR="$(echo "$HOME")/.config/borg/"
export BORG_KEY_FILE="test.key"
export BORG_KEYS_DIR="${CONFIG_DIR}keys/"

export BORG_PASSPHRASE=$REPOPASSWD

export BORG_NEW_PASSPHRASE=$REPOPASSWD

# The following command generates the key file to $(pwd) instead of BORG_KEYS_DIR with a name of BORG_KEY_FILE
# I can work around this by using pushd and popd to exec it in BORG_KEYS_DIR
borg init --encryption keyfile /home/jimbo/backup/test

BACKUPNAME="$(date +"%Y-%d-%m-%s")-test"
DIRECTORIES_TO_BACKUP="$(echo "$HOME")/Documents"

# Next command will fail since it looks for the key from working directory instead of BORG_KEYS_DIR
borg create /home/jimbo/backup/test::$BACKUPNAME $DIRECTORIES_TO_BACKUP
```

If I unset the `BORG_KEYS_DIR` it will create it into working directory instead of `~/.config/borg/keys/`

I'm going to sync the repo to (non standard) external service while keeping local copy, so I cannot keep the keys in repo. Additionally my use requires that the key names are predictable and do not conflict if I init multiple repos. I could pushd and popd to the key directory whenever I run init and create commands but restoring files would involve copying the repokey file to the restore directory and removing it afterwards if the environment variables do not work. I'd be happy to hear about some workarounds or it might be that I have just misunderstood this page https://borgbackup.readthedocs.io/en/stable/usage/general.html

#### Include any warning/errors/backtraces from the system logs

Run the previous script above, the key will appear in wrong place. Move the key manually to the proper directory, comment out the init section and run only backup generation and it will spit something like this

```
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 170, in wrapper
    kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
  File "/usr/lib64/python3.9/site-packages/borg/helpers/manifest.py", line 187, in load
    key = key_factory(repository, cdata)
  File "/usr/lib64/python3.9/site-packages/borg/crypto/key.py", line 134, in key_factory
    return identify_key(manifest_data).detect(repository, manifest_data)
  File "/usr/lib64/python3.9/site-packages/borg/crypto/key.py", line 585, in detect
    target = key.find_key()
  File "/usr/lib64/python3.9/site-packages/borg/crypto/key.py", line 719, in find_key
    return self.sanity_check(keyfile, self.repository.id)
  File "/usr/lib64/python3.9/site-packages/borg/crypto/key.py", line 707, in sanity_check
    with open(filename, 'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jimbo/Work/misc/borg-scripts/test.key'

Platform: Linux localhost.localdomain 5.14.0-162.12.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan 23 14:51:52 EST 2023 x86_64
Linux: Unknown Linux  
Borg: 1.2.3  Python: CPython 3.9.14 msgpack: 1.0.3 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 77861  CWD: /home/jimbo/Work/misc/borg-scripts
sys.argv: ['/usr/bin/borg', 'create', '/home/jimbo/backup/test::2023-14-03-1678815344-test', '/home/jimbo/Documents']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
i didn't research it yet, but guess BORG_KEYS_FILE (if used) should have the full path and filename (and overrides other settings). it is only for rather special use cases.

also BORG_NEW_PASSPHRASE is only for changing the passphrase, IIRC.

**Comment by ThomasWaldmann** [comment]
btw, it is not a problem per-se to have the borg key in the repo, because the key is encrypted with your passphrase.

so as long as your passphrase is secure and AES is secure, your repokey should be also safe, even if it is on a remote server.

**Comment by jimboolio** [comment]
I thought I tried using full path as `BORG_KEYS_FILE`, but apparently I didn't test far enough, since the init fails when full path is used but `borg create ...` works fine

So this doesn't work:
```
#!/bin/bash

REPOPASSWD="helloworld"

CONFIG_DIR="$(echo "$HOME")/.config/borg/"
export BORG_KEY_FILE="${CONFIG_DIR}keys/test.key"
#export BORG_KEYS_DIR="${CONFIG_DIR}keys/"

export BORG_PASSPHRASE=$REPOPASSWD

export BORG_NEW_PASSPHRASE=$REPOPASSWD

# The following command generates the key file to $(pwd) instead of BORG_KEYS_DIR with a name of BORG_KEY_FILE
# I can work around this by using pushd and popd to exec it in BORG_KEYS_DIR
borg init --encryption keyfile /home/jimbo/backup/test
```

Results in this:
```
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib64/python3.9/site-packages/borg/archiver.py", line 282, in do_init
    key = key_creator(repository, args)
  File "/usr/lib64/python3.9/site-packages/borg/crypto/key.py", line 110, in key_creator
    return key.create(repository, args)
  File "/usr/lib64/python3.9/site-packages/borg/crypto/key.py", line 684, in create
    key.save(target, passphrase, create=True)
  File "/usr/lib64/python3.9/site-packages/borg/crypto/key.py", line 779, in save
    with SaveFile(target) as fd:
  File "/usr/lib64/python3.9/site-packages/borg/platform/base.py", line 230, in __enter__
    self.tmp_fd, self.tmp_fname = mkstemp_mode(prefix=self.tmp_prefix, suffix='.tmp', dir=self.dir, mode=0o666)
  File "/usr/lib64/python3.9/site-packages/borg/helpers/fs.py", line 409, in mkstemp_mode
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type, mode)
  File "/usr/lib64/python3.9/site-packages/borg/helpers/fs.py", line 365, in _mkstemp_inner
    fd = _os.open(file, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/jimbo/.config/borg/keys/test.key-083iblx9.tmp'

Platform: Linux localhost.localdomain 5.14.0-162.12.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan 23 14:51:52 EST 2023 x86_64
Linux: Unknown Linux  
Borg: 1.2.3  Python: CPython 3.9.14 msgpack: 1.0.3 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 9438  CWD: /home/jimbo/Work/misc/borg-scripts
sys.argv: ['/usr/bin/borg', 'init', '--encryption', 'keyfile', '/home/jimbo/backup/test']
SSH_ORIGINAL_COMMAND: None
```

And this does work after the repo has been initialized:
```
REPOPASSWD="helloworld"

CONFIG_DIR="$(echo "$HOME")/.config/borg/"
export BORG_KEY_FILE="${CONFIG_DIR}keys/test.key"
#export BORG_KEYS_DIR="${CONFIG_DIR}keys/"

export BORG_PASSPHRASE=$REPOPASSWD

export BORG_NEW_PASSPHRASE=$REPOPASSWD

# The following command generates the key file to $(pwd) instead of BORG_KEYS_DIR with a name of BORG_KEY_FILE
# I can work around this by using pushd and popd to exec it in BORG_KEYS_DIR
#borg init --encryption keyfile /home/jimbo/backup/test

BACKUPNAME="$(date +"%Y-%d-%m-%s")-test"
DIRECTORIES_TO_BACKUP="$(echo "$HOME")/Documents"

# Next command will fail since it looks for the key from working directory instead of BORG_KEYS_DIR if
# the key file is actually at BORG_KEYS_DIR
borg create /home/jimbo/backup/test::$BACKUPNAME $DIRECTORIES_TO_BACKUP
```

As a summary if someone encounters this issue, the easiest workaround is probably to only use `--encryption repokey` option but with stronger passwords. 

And if one insists on using `--encryption keyfile` (like me since my backup destination is so affordable that it is untrusted) it probably works by doing pushd to `borg/keys` when running `borg init` if `BORG_KEYS_FILE` is set up only as the file name. Then popd and overwrite `BORG_KEYS_FILE` with full path+filename and use that for `borg create`. 

Additionally I noticed that if `BORG_KEYS_FILE` is unset and I run `borg list`, borg will use some key, probably randomly from the keys directory. If it is set and the key file is missing, that'll cause an unhandled crash. But if `BORG_KEYS_FILE` is set and file exists borg works as expected and even backup extraction works.

But anyways, thanks for the quick response, I think I gathered enough information to work around these surprises

**Comment by ThomasWaldmann** [comment]
> BORG_KEY_FILE="${CONFIG_DIR}keys/test.key"

borg will create that key file, but the parent directory ("keys") must 
already exist before invoking borg.

> Additionally I noticed that if |BORG_KEYS_FILE| is unset and I run |borg 
> list|, borg will use some key, probably randomly from the keys 
> directory. If it is set and the key file is missing, that'll cause an 
> unhandled crash. But if |BORG_KEYS_FILE| is set and file exists borg 
> works as expected and even backup extraction works.

That sounds strange, can you file a bug report on github?

**Comment by Michael-Girma** [comment]
@ThomasWaldmann, I can confirm that this is indeed the case. 

1. If repo key is in keys directory (BORG_KEYS_DIR if set or CONFIG_DIR/keys if unset), borg will automatically use that.
2. If BORG_KEYS_DIR is specified (CONFIG_DIR/keys will be used instead if not) and key does not exist, borg displays a message along the lines of ```No key file for repository /Users/michael/Documents/test/repo found in /Users/michael/.config/borg/keys.```
3. If BORG_KEY_FILE is set while it does not exist, borg raises an unhandled exception noting that the file does not exist.

This test was for 1.2-maint. Is there a bug report and can I pick that up?

**Comment by ThomasWaldmann** [comment]
Guess we keep the scope of this ticket to the top post (please file other tickets for other stuff discovered):

The docs about BORG_KEY_FILE can be misunderstood easily and need to get improved (that was the root cause of these problems):
- stating that a full, absolute path to the key file is needed
- stating that all directories in that path must exist
- stating that this is only for rather special applications, forces borg to always use that given path (no matter what repository it is accessing), requiring appropriate external management of that path (like dealing with multiple unique paths for multiple repos)

**Comment by ThomasWaldmann** [comment]
@jimboolio https://github.com/borgbackup/borg/pull/7463/files - would that have avoided your issues?
