### ISSUE TITLE
wrong cache directories

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7445]
From a discussion post:

> I noticed that with borg 2 the cache directories do *not* contain the 
> name borg which is a bit annoying and i would prefer the old behaviour.
> 
> Borg 1.2 
> /home/dietmar/.cache/borg/0a2cb8f22adaa78a1863b028f3d1629393ef0fdd99b3b61c11d871de9eaaee8b/README
> 
> Borg 2.0.0b5 
> /home/dietmar/.cache/fa673b73240ed3b75ba947fd98787fdf8ecd17204323e4a10c2754cdcc5fd547/README

this is likely due to us switching to `platformdirs` library and the related api change.

config directories need also checking, there might be the same issue.

**Comment by nain-F49FF806** [comment]
Hi. I would like to look into this. First step for me I guess would be replicating it on my device. (and looking at the relevant code)

Could you mention the email thread subject so I can read more?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/discussions/7392#discussioncomment-5316914 see there.

**Comment by nain-F49FF806** [comment]
I suppose #7300 (mentioned earlier) , #7332 are related to this. Am going afk now.
Will check again tomorrow. (if it's still open :)

**Comment by nain-F49FF806** [comment]
I think this might be the offending line https://github.com/borgbackup/borg/blob/270b705248a6a23a2842697b114aec446f6b99fd/src/borg/helpers/fs.py#L146

`join_base_dir(".config", legacy=legacy)` should instead be `join_base_dir(".config", "borg", legacy=legacy)`

**Comment by nain-F49FF806** [comment]
Will try the exact release.

**Comment by nain-F49FF806** [comment]
> Yes, I think you maybe discovered an issue there (but that is only for the case when BORG_BASE_DIR is used, which is not the default use case).

I think that line is being used for all three cases. 
It tries to get `"BORG_CONFIG_DIR"`, from environment, if it doesn't find it then the default value `join_base_dir(".config", legacy=legacy) or platformdirs.user_config_dir("borg")` is used.

The first part (left hand) of the `or` should return "None" in most cases (unless legacy=True, or `BORG_BASE_DIR` is set) so the second hand will be choosed in regular scenario. 

And I just checked running that (`platformdirs.user_config_dir("borg")`) with platformdirs version 3.1.0 on Ubuntu 20.04, and it gives the expected "/home/user/.config/borg" value. 

So, one way I see it happening is if the user has set `BORG_BASE_DIR`. Then the value given by `join_base_dir` will be used.

**Comment by nain-F49FF806** [comment]
Just ran manual testing on 1.2.3 vs 2.0.0b5, both with the BORG_BASE_DIR set. Can confirm the difference in behavior. 
The later version looses borg subdir

```
(borg-env):/tmp$ tree -a -L 2 borg1.2.3/
borg1.2.3/
|-- .cache
|   `-- borg
`-- .config
    `-- borg
```

```
(borg-env):/tmp$ tree -a -L 2 borg2/    
borg2/
|-- .cache
|   |-- CACHEDIR.TAG
|   `-- df4e4ae7737b68eeb241f01fc1bffee4f5fdda570a238815d05a2f2f1b756eaa
`-- .config
    `-- security

```

Seems like that is the issue here.

**Comment by nain-F49FF806** [comment]
Will look into the tests.

**Comment by nain-F49FF806** [comment]
Submitted a commit fixing the issue for `config` dir.  Should the same fix be applied for the `cache` dir?

Or is `cache` dir compatibility when using `BORG_BASE_DIR` not necessary?
I can imagine `BORG_BASE_DIR` would generally be borg specific and exclusive, so adding a sub-directory `borg` under `cache` there feels redundant. 

But it would make sense to do it for consistency, seeing as config's location perhaps _should_ remain compatible between versions.

**Comment by ThomasWaldmann** [comment]
I think we should have config and cache dir work as compatible to previously ("legacy") as possible.
There are some expected changes (like on macOS), but we shouldn't have unexpected ones.

**Comment by nain-F49FF806** [comment]
Acknowledged. Have submitted commits for both. Open to feedback if some changes are required.
