### ISSUE TITLE
borg crashes with exception when cache files are missing, should handle this gracefully

### ISSUE THREAD

**Issue by agrommek** [borgbackup/borg#7450]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug / Enhancement

#### Your borg version (borg -V).

borg-2.0.0b5

#### Operating system (distribution) and version.

Arch Linux, Ubuntu Server 22.04

#### Hardware / network configuration, and filesystems used.

Local repositories for testing, ext4

#### How much data is handled by borg?

a few GB, for testing

## Describe the problem you're observing.

I messed a bit around in the cache directory in an effort to save some space as this is rather big in my production setup (several GB) and noticed the following behavior: When the whole cache directory is deleted, borg re-sycns the cache from the repository and/or rebuilds the files cache an other data. However, when only part of the cache directory is deleted (only files cache, only chunks cache, only config file, ...), borg exits with an exception:

```
$ borg-2.0.0b5-linuxnew64 create downloads-{utcnow} /home/me/Downloads/ --repo /path/to/testrepo1  --progress --verbose --stats
Enter passphrase for key /path/to/testrepo1: 
Creating archive at "/path/to/testrepo1"
Local Exception
Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 595, in main
  File "borg/archiver/__init__.py", line 523, in run
  File "borg/archiver/_common.py", line 156, in wrapper
  File "borg/archiver/create_cmd.py", line 221, in do_create
  File "borg/cache.py", line 426, in __new__
  File "borg/cache.py", line 411, in local
  File "borg/cache.py", line 525, in __init__
  File "borg/cache.py", line 575, in open
  File "borg/cache.py", line 698, in rollback
  File "borg/cache.py", line 560, in _do_open
  File "borg/crypto/file_integrity.py", line 133, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/me/.cache/borg/74188eaf53161b51a9a6f23140ea342099a0a4d3e84c1d09ff125aca9a0ae1b6/chunks'

Platform: Linux tomateX 6.2.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:08 +0000 x86_64
Linux: Unknown Linux  
Borg: 2.0.0b5  Python: CPython 3.11.2 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 4102  CWD: /home/me/.cache/borg/74188eaf53161b51a9a6f23140ea342099a0a4d3e84c1d09ff125aca9a0ae1b6
sys.argv: ['/home/me/Downloads/borg-2.0.0b5-linuxnew64', 'create', 'downloads-{utcnow}', '/home/me/Downloads/', '--repo', '/path/to/testrepo1', '--progress', '--verbose', '--stats']
SSH_ORIGINAL_COMMAND: None
```
Borg should / could handle this situation more gracefully by doing one of those:

- Exit gracefully and inform the user that something is wrong with their cache directory and that they should go delete it completely.
- Offer / provide a switch, maybe `--repair-cache` or `--rebuild-cache` or so, to make repairing the cache an explicit user action.
- Log a warning, delete the cache directory and start rebuilding it.

Maybe there are other things borg could do. In any case, users should not need to interpret python stack traces when something goes wrong. One could reply that users also shouldn't muck around in the cache directory, but some will do (as I did... ;-) )

**Comment by ThomasWaldmann** [comment]
Yes, maybe it could automatically deal with such situations.

OTOH: usually such files do not just vanish and maybe you would like to know in case they do (if you did not delete them yourself like you did).

**Comment by Michael-Girma** [comment]
@ThomasWaldmann maybe do both. Notify the user that borg will have to rebuild caches due to the fact that there are missing cache files and carry on with the process.

**Comment by Michael-Girma** [comment]
@ThomasWaldmann we should be able to just wipe the cache if file, chunk, config, or chunks.archive.d are missing, right? That would force a cache rebuild.

**Comment by ThomasWaldmann** [comment]
Guess borg has different requirements depending on the cache:
- chunks cache is required for borg create
- files cache is not required for borg create (it will be just slower) and will be recreated by borg create anyway
- chunks.archives.d/ is only checked if chunks cache is out of sync and needs to be re-synced. that directory can even be replaced by a file if one wants to disable the archive and rather save some disk space.

**Comment by Michael-Girma** [comment]
@ThomasWaldmann Then just check for config and chunks, I suppose.

**Comment by ThomasWaldmann** [comment]
This was recently fixed - if there is an exception due to a missing or corrupted cache file, it'll rebuild it now.
