### ISSUE TITLE
Running borg create with sudo returns invalid location format error

### ISSUE THREAD

**Issue by that-one-arab** [borgbackup/borg#7451]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.1.15

#### Operating system (distribution) and version.
Ubuntu 20.04

#### Hardware / network configuration, and filesystems used.
Borg installed both locally and remotely, backups are stored in the remote server, ext4

#### How much data is handled by borg?
10GB+

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```bash
export BORG_REPO="root@${VPS_IP}:/root/borg/backups"
export BORG_PASSPHRASE=$BORG_PASSWORD
export BORG_RSH="ssh -i ${VPS_PPK}"

sudo borg create                    \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
                                    
    ::'{now:%Y-%m-%d}-borg-ver-{borgversion}' \
    /etc                            \
    /home                           \
    /root                           \
    /var                            \
```

## Describe the problem you're observing.
Running the above command as root using `sudo` returns an error
This issue only occurs when running the command as sudo. Removing `sudo` from the commandline makes everything work normally

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, use the above borg commandline

#### Include any warning/errors/backtraces from the system logs
 `error: argument ARCHIVE: Invalid location format: "::{now:%Y-%m-%d}-borg-ver-{borgversion}"`

**Comment by ThomasWaldmann** [comment]
Likely due to sudo usage, check its documentation about how it deals with env vars.

**Comment by that-one-arab** [comment]
It is just like you said, running the backup script with sudo solved the issue!

I experienced 2 more errors after that:
- **1st error** is an error related to my remote server's ssh private key not being read, this happens if

**Comment by that-one-arab** [comment]
It is just like you said, running the script with `sudo` solved the issue!

I did get one more error, this error is related to my remote server's borg repository key not being read (if we initialize borg repo with `keyfile` encryption)
This error was solved by using the `BORG_KEY_FILE` environment variable and specifying the path to the key

Thank you!

**Comment by ThomasWaldmann** [comment]
You shouldn't use BORG_KEY_FILE in normal setups. As long as that is set, it will use that filename, no matter what you do.

So rather find out what's the root cause of your issue, maybe it's a permission problem or accessing the wrong HOME dir...

**Comment by that-one-arab** [comment]
@ThomasWaldmann The root cause was that running with `sudo` replaced the default file path from `/home/USER/.config/borg/keys` to `/home/root/.config/borg/keys` which made borg unable to find the key file, hence why I needed to re-specify it. Also I am exporting this environment variable from the script itself, meaning that the environment variable is not a permanent one and only restricted to the session.

Is there a better way for me to go on doing this?

**Comment by ThomasWaldmann** [comment]
You always should use borg as the same user to avoid such trouble (and also a permission mess in the repo).
If you need root for borg, always run it as root (and also have the key file there).

**Comment by that-one-arab** [comment]
@ThomasWaldmann Got it. Will change my setup accordingly. Thank you
