### ISSUE TITLE
Cache/file-change detection is not working

### ISSUE THREAD

**Issue by detoxhby** [borgbackup/borg#7458]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.2.3 (stable)

#### Operating system (distribution) and version.

Ubuntu 20.04 (latest / up-to-date) with kernel 5.15

#### Hardware / network configuration, and filesystems used.

**btrfs** (mount options: `subvol=data,noatime,ssd,space_cache=v2,acl`)

#### How much data is handled by borg?

6 TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```bash
# create readonly btrfs snapshot,
# cd into the snapshot directory, then...
borg create                         \
    --filter AME                    \
    --stats                         \
    --verbose                       \
    --list                          \
    --show-rc                       \
    --compression auto,zstd,5       \
    --exclude-caches                \
    --noflags                       \
    --noacls                        \
    --noxattrs                      \
    --numeric-ids                   \
    --files-cache mtime,size        \
                                    \
    ::'{now}'                       \
    .                               \
    2>&1
```

## Describe the problem you're observing.

Using latest stable borg on a btrfs snapshot **results in full read of source files** (**"A"** is shown for every single file in the output). The content is not recreated (no writes to the backup disk 99% of the time), nor rehashed (the cache content (files/chunks) remains almost the same size, small change only).

The most concerning thing is that executing borg create **with --dry-run it shows every single file as not changed** (with --filter AME it shows nothing due to this fact). Modifications are not detected this way.

We've tried:
* including/excluding the following flags: --noflags, --noacls, --noxattrs, --numeric-ids
* every sane combination of files-cache:
  * default
  * mtime,size,inode
  * ctime,size
  * mtime,size
* ran multiple consecutive backups to make sure the cache could be effective

We suspected inode and/or ctime change due to snapshots but after trying out all cache variant we ran out of options, seems like a bug mostly because of --dry-run's strange behavior (should detected changes but not).

Any help or workaround is appreciated as huge amount of data (~million files) requires half-day to complete which is problematic on a daily backup (and also max out the storage with high usage).

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

yes, always

#### Include any warning/errors/backtraces from the system logs

no errors/warnings/extra logs

**Comment by infectormp** [comment]
Do you mount btrfs snapshot every time to the same mount point?

https://borgbackup.readthedocs.io/en/stable/faq.html#i-am-seeing-a-added-status-for-an-unchanged-file
> Furthermore, pathnames recorded in files cache are always absolute, even if you specify source directories with relative pathname. If relative pathnames are stable, but absolute are not (for example if you mount a filesystem without stable mount points for each backup or if you are running the backup from a filesystem snapshot whose name is not stable), borg will assume that files are different and will report them as ‘added’, even though no new chunks will be actually recorded for them. To avoid this, you could bind mount your source directory in a directory with the stable path.

**Comment by ThomasWaldmann** [comment]
a dry run will just output "x" for excluded files or "-" for not excluded files, it does not do any "file changed" detection. dry run is mostly useful for checking include/exclude behaviour.

is what you describe a btrfs specific problem or can you reproduce on another fs type?

if a file is detected as "A" (added), it means it was not found in the files cache and it will be chunked/hashed.

**Comment by ThomasWaldmann** [comment]
@detoxhby you can not have relative paths in the files-cache, it always uses abs paths.

But maybe you can bind-mount your snapshot path to a fixed path and backup that.

**Comment by detoxhby** [comment]
Thanks, changed the backup script to use fix snapshot path with extra check on existing snapshot directory (to avoid conflicts).

Gonna report back in 2 days after the backups are done (and close the issue accordingly).

**Comment by detoxhby** [comment]
It was solved by using fixed snapshot path, thank you again!
