### ISSUE TITLE
Do back/forward ports (98)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7468]
https://github.com/borgbackup/borg/issues?q=label%3Aforwardport%2Fmaster%2Cbackport%2F1.1-maint%2Cbackport%2F1.2-maint

do 2 simple/small or 1 mid-sized/mid-complex forward/backport from there.

---

:moneybag: [there is a bounty for this](https://app.bountysource.com/issues/118370201-do-back-forward-ports-98)

**Comment by abebeos** [comment]
looks like no issues available.

**Comment by ThomasWaldmann** [comment]
@abebeos true right now, but theoretically this can change any time (and this is why i will delete your and my comment in a while - people have to use the search link in the top post).

**Comment by sashadev-sky** [comment]
backport #7477: #7547
backport #7489: #7548

**Comment by ThomasWaldmann** [comment]
All done, thanks!
