### ISSUE TITLE
Do back/forward ports (99)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7469]
https://github.com/borgbackup/borg/issues?q=label%3Aforwardport%2Fmaster%2Cbackport%2F1.1-maint%2Cbackport%2F1.2-maint

do 2 simple/small or 1 mid-sized/mid-complex forward/backport from there.

---

:moneybag: [there is a bounty for this](https://app.bountysource.com/issues/118370192-do-back-forward-ports-99)

**Comment by abebeos** [comment]
looks like no issues available.

**Comment by ThomasWaldmann** [comment]
@abebeos true right now, but theoretically this can change any time (and this is why i will delete your and my comment in a while - people have to use the search link in the top post).

**Comment by sashadev-sky** [comment]
Backport #7492: #7549
Backport #7521: #7550

**Comment by ThomasWaldmann** [comment]
Sure. :)
