### ISSUE TITLE
Install pre-commit to avoid un-linted/unformatted code from being committed

### ISSUE THREAD

**Issue by Michael-Girma** [borgbackup/borg#7476]
## Is this a BUG / ISSUE report or a QUESTION?

Enhancement

## Describe the problem you're observing.

As a contributor, I've passed in several commits that haven't been linted/formatted after forgetting to run ```black``` and ```flake8```. This could be avoided by running pre-commit hooks to analyze the code before the commit is made thus circumventing unformatted code from being committed.

**Comment by ThomasWaldmann** [comment]
black must use the same version as on our github ci and as in our requirements file:

https://github.com/borgbackup/borg/blob/master/requirements.d/codestyle.txt

**Comment by Michael-Girma** [comment]
@ThomasWaldmann Well, pre-commit hooks are not recommended if the pre-commit scripts take a long time. However, since we're only running formatting scripts, I think we should be fine. Even though, it is thought of as a guardrail, pre-commit hooks can be bypassed by using a flag so we won't be blocking commits in scenarios where it's unnecessary to run them.

**Comment by ThomasWaldmann** [comment]
Note: this is only for master, no backport to 1.2-maint.
