### ISSUE TITLE
Question about:  mount an archive stored on an external drive (using root) and "Mountpoint must be a writable directory"

### ISSUE THREAD

**Issue by lamyergeier** [borgbackup/borg#7496]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```bash
sudo borg  -r /media/lamy/f0b9ad2c-58b6-43d7-82d8-3ab5e54bce13/LaptopSSD mount -a lamy-2023-03-31T12:24:53.483170 /mnt/BackupMount
```

## Describe the problem you're observing.

I am able to list all archives in a repository:

```bash
$ sudo borg  -r /media/lamy/f0b9ad2c-58b6-43d7-82d8-3ab5e54bce13/LaptopSSD rlist
lamy-2023-03-29T09:58:03.891829      Wed, 2023-03-29 09:58:03 +0200 [04585a816699dd0c5dab9d5f1790e4e74a1a720bf6ade635d0f7a7fd006d6cfb]
lamy-2023-03-31T12:24:53.483170      Fri, 2023-03-31 12:24:54 +0200 [ad5a218456d1f2ec9f2acdd5c883bf555e34b34add2997bb507d7af0a55053d4]
lamy-2023-04-03T14:41:50.049101      Mon, 2023-04-03 14:41:50 +0200 [56e9c0553d1694fb1229b82c55c3fc57c3a753d70aa0b16942941dea07470bb5]
```

I am also able to list contents of a particular archive that I want to see:

```bash
sudo borg  -r /media/lamy/f0b9ad2c-58b6-43d7-82d8-3ab5e54bce13/LaptopSSD list lamy-2023-03-31T12:24:53.483170
```

But when I mount it the location becomes inaccessible in the file browser:

```bash
 sudo borg  -r /media/lamy/f0b9ad2c-58b6-43d7-82d8-3ab5e54bce13/LaptopSSD mount -a lamy-2023-03-31T12:24:53.483170 /mnt/BackupMount
```

- Note the file permissions for the folder `BackupMount` becomes `????` 

```
$ ls -la /mnt
ls: cannot access '/mnt/BackupMount': Permission denied
total 28K
drwxr-xr-x  8 root 4.0K Apr  3 13:58 ./
drwxr-xr-x 20 root 4.0K Apr  3 02:12 ../
d?????????  ? ?       ?            ? BackupMount/
```

- But when I become a  root user (using su),  it shows as follows

```bash
root@lamy:/mnt# ls -la
total 28
drwxr-xr-x  8 root root 4096 Apr  3 13:58 .
drwxr-xr-x 20 root root 4096 Apr  3 02:12 ..
drwxr-xr-x  1 root root    0 Apr  3 18:17 BackupMount
```

Note that the size of BackupMount folder is shown as 0 instead of 4096. What could be causing this?
Infact all child folders show 0 size! 

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Described above

**Comment by ThomasWaldmann** [comment]
Do the mount again, but additionally use `-f` (foreground) option to see if there is any error msg or traceback.

Then, switch to another terminal and access the mountpoint.

**Comment by lamyergeier** [comment]
@ThomasWaldmann I created mounting with foreground in one window, where it shows no error and does not exits after mounting. In another window I try to access the mountpoint, you can see all directory have 0 size and `????`  as file permission when accessing it as non root user 

- In one window

```bash
$ sudo borg  -r /media/lamy/f0b9ad2c-58b6-43d7-82d8-3ab5e54bce13/LaptopSSD mount -f -a lamy-2023-03-31T12:24:53.483170 /mnt/BackupMount
```

- In another window:

```
$ cd /mnt
/mnt
$ la
ls: cannot access 'BackupMount': Permission denied
total 20K
755 drwxr-xr-x 3 lamy lamy 4.0K 2022-11-27 17:42 BackupLocal
d????????? ? ?    ?       ?                ? BackupMount
755 drwxr-xr-x 4 lamy lamy 4.0K 2022-12-12 00:01 ContainerDocuments
755 drwxr-xr-x 2 lamy lamy 4.0K 2023-01-13 12:10 DataFixed
755 drwxr-xr-x 2 lamy lamy 4.0K 2022-12-11 16:58 TempMount
755 drwxr-xr-x 2 lamy lamy 4.0K 2022-12-20 20:07 VirtualMachine
$ su
Password: 
root@lamy:/mnt# ls -la
total 28
drwxr-xr-x  8 root root 4096 Apr  3 19:09 .
drwxr-xr-x 20 root root 4096 Apr  3 02:12 ..
drwxr-xr-x  3 lamy lamy 4096 Nov 27 17:42 BackupLocal
drwxr-xr-x  1 root root    0 Apr  3 19:09 BackupMount
drwxr-xr-x  4 lamy lamy 4096 Dec 12 00:01 ContainerDocuments
drwxr-xr-x  2 lamy lamy 4096 Jan 13 12:10 DataFixed
drwxr-xr-x  2 lamy lamy 4096 Dec 11 16:58 TempMount
drwxr-xr-x  2 lamy lamy 4096 Dec 20 20:07 VirtualMachine
root@lamy:/mnt# cd BackupMount/
root@lamy:/mnt/BackupMount# ls -la
total 4
drwxr-xr-x 1 root root    0 Apr  3 19:09 .
drwxr-xr-x 8 root root 4096 Apr  3 19:09 ..
drwxr-xr-x 1 root root    0 Mar 31 12:24 lamy-2023-03-31T12:24:53.483170
root@lamy:/mnt/BackupMount# 
```

**Comment by ThomasWaldmann** [comment]
Ah, guess it's just fuse and permission handling.

You always should use the same user. For borg and for accessing the fuse mount.

**Comment by lamyergeier** [comment]
So, I created the backup as root as I have to also save files owned by the root.

You can see above that when I have changed to root user. All directories (and subdirectories) of the mount point  are showing as size 0. Is this expected?

**Comment by ThomasWaldmann** [comment]
Not sure about the directories.

Maybe rather check whether you have the expected files in there and whether they have the correct contents.

**Comment by lamyergeier** [comment]
I am getting another error now (with and without `-f` with borg mount):

```
$ cd /mnt; ls -la
total 24K
755 drwxr-xr-x 2 root root 4.0K 2023-04-03 22:31 BackupMount

$ sudo borg  -r /media/lamy/f0b9ad2c-58b6-43d7-82d8-3ab5e54bce13/LaptopSSD mount -f lamy-2023-03-31T12:24:53.483170 /mnt/BackupMount
lamy-2023-03-31T12:24:53.483170: Mountpoint must be a writable directory

$ sudo borg  -r /media/lamy/f0b9ad2c-58b6-43d7-82d8-3ab5e54bce13/LaptopSSD mount lamy-2023-03-31T12:24:53.483170 /mnt/BackupMount
lamy-2023-03-31T12:24:53.483170: Mountpoint must be a writable directory
```

**Comment by ThomasWaldmann** [comment]
**Mountpoint must be a writable directory** <- sure!

**Comment by lamyergeier** [comment]
@ThomasWaldmann the file permission of the mount point directory can be seen above. As per what I understand it should be writable. What do you think?

**Comment by jdchristensen** [comment]
Looks like you forgot the `-a`, so it is trying to mount it on the non-existent directory `lamy-2023-03-31T12:24:53.483170`, as the error message says.

**Comment by ThomasWaldmann** [comment]
I'll improve the error message.

**Comment by lamyergeier** [comment]
@ThomasWaldmann Yes
