### ISSUE TITLE
display passphrase for verification

### ISSUE THREAD

**Issue by infectormp** [borgbackup/borg#750]
Would be nice do not ask for display passphrase for verification if passphrase was empty.

**Comment by enkore** [comment]
I'd ask for the opposite (always display a message if it's empty).

**Comment by infectormp** [comment]
@enkore and why i need press here **N** or **Y** if i not enter passphrase?

Maybe better warn user about repo will be not encrypted?

**Comment by enkore** [comment]
The repo will always be encrypted if -e is repokey/keyfile: these modes generate a few keys internally and store them encrypted by kdf(your_passphrase). If the repokey/keyfile hasn't been stolen you can change the passphrase later.

I guess from your other comments that this is about automating borg? If so, you probably want to use `BORG_DISPLAY_PASSPHRASE=n`.

**Comment by infectormp** [comment]
No. When i init repo with ```borg init /backup/test.repo``` i get asked for passphrase. I not enter passphrase (just press **Enter** two times) and get message ```Do you want your passphrase to be displayed for verification? [yN]:```. 

Do we need this message if passphrase was not entered? May be here we need warn user about repo will be not encrypted?

**Comment by enkore** [comment]
Technically the repo is encrypted, it's just the keys for the data that is encrypted with a *very* weak passphrase (`""`).

I think we are actually thinking the same thing. What I meant in the first comment above could look something like this:

    $ borg init …
    Enter new passphrase: 
    Enter same passphrase again:
    Warning: Empty passphrase does not provide protection.

And only ask to display it if there was a passphrase given.

**Comment by infectormp** [comment]
@enkore yes, your are right :100:

**Comment by ThomasWaldmann** [comment]
I don't think we need this feature, it might be even harmful if we added it.

The feature is to give people the opportunity to verify their passphrase and that applies to all passphrases, even empty ones.

Also: if you don't want to have it display, you just need to hit Enter as the default is N.

**Comment by infectormp** [comment]
It was just a question, so i satisfied with any decision.
