### ISSUE TITLE
highlander options "special effects"

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7500]
borg has some cli options with `action=Highlander`, which raises an error if there is more than one (see also #6269).

E.g. it does not make sense to give `--umask` more than once (especially not with different values).

But, this error is not raised, if the first of these options happens to use the same value as the default value of the option.

E.g.:
```
borg --umask 077 --umask 007 rlist --repo ...  # no error (0o077 is the default)
borg --umask 007 --umask 077 rlist --repo ...  # error "there can be only one"
borg --umask 777 --umask 007 rlist --repo ...  # error "there can be only one"
borg --umask 007 --umask 777 rlist --repo ...  # error "there can be only one"
```

**Comment by snsmac** [comment]
I'm working on this
