### ISSUE TITLE
FreeBSD export BORG_PASSPHRASE doesn't seem to work properly

### ISSUE THREAD

**Issue by jogood** [borgbackup/borg#7502]
I have used the remote example in borg documentation. Works when I launch it, but it prompt for password. So it doesn't from cron, says permission denied. I have `export BORG_PASSPHRASE='pass'`. There's no encryption and I also added `REPO_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes`.

The export command works. The setenv command doesn't work.

Is there something I'm doing wrong?

**Comment by ThomasWaldmann** [comment]
The env var code (in borg) is the same everywhere (and works), so I am pretty sure the error is outside of borg.

How you set an env var might depend on your shell, using `sudo` or using multiple scripts or ... might add some complexity outside of borg.

**Comment by ThomasWaldmann** [comment]
BTW, if you are a freebsd user: check if you can debug / fix #6871!

**Comment by jogood** [comment]
> 

I can't help, I'm quite new to FreeBSD.

As for the FreeBSD example, I run this script from `sudo crontab -e`. 

```
export BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK=yes

export BORG_REPO=ssh://user@url.backup:22/path/backup/

export BORG_PASSPHRASE='pass'
export BORG_PASSCOMMAND='pass'
# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

# Backup the most important directories into an archive named after
# the machine this script is currently running on:

/usr/local/bin/borg create                         \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --exclude-caches                \
    --exclude 'home/*/.cache/*'     \
    --exclude 'var/tmp/*'           \
    --compression none              \
    -e none                         \
    ::'{hostname}-{now}'            \
    /etc                            \
    /home                           \
    /root                           \
    /usr/local 

backup_exit=$?

info "Pruning repository"

/usr/local/bin/borg prune                          \
    --list                          \
    --glob-archives '{hostname}-*'  \
    --show-rc                       \
    --keep-daily    1               \
    --keep-weekly   1               \
    --keep-monthly  1

prune_exit=$?

# actually free repo disk space by compacting segments

info "Compacting repository"

/usr/local/bin/borg compact

compact_exit=$?

# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
global_exit=$(( compact_exit > global_exit ? compact_exit : global_exit ))

if [ ${global_exit} -eq 0 ]; then
    info "Backup, Prune, and Compact finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup, Prune, and/or Compact finished with warnings"
else
    info "Backup, Prune, and/or Compact finished with errors"
fi

```

Result (same message 3 time):

```
Remote: Permission denied, please try again.
Remote: Permission denied, please try again.
Remote: user@url.backup: Permission denied (publickey,password).
Connection closed by remote host. Is borg working on the server?
terminating with error status, rc 2
```

If I run this same script  myself from root user, I get a password prompt which I assume is the problem. Unless for some reason, launching this script from cron would not ask prompt and error would be something else.

**Comment by ThomasWaldmann** [comment]
Remove the line with `BORG_PASSCOMMAND`.

**Comment by jogood** [comment]
Doesn't work either.

**Comment by ThomasWaldmann** [comment]
Remote: user@url.backup: Permission denied (publickey,password).

Your ssh setup is not working. You should have the ssh pubkey in `~/.ssh/authorized_keys` on the repo server.

**Comment by ThomasWaldmann** [comment]
BTW, `--compression none` is often worse than the default (lz4 compression), except if you back up only precompressed or pre-encrypted data.

**Comment by jogood** [comment]
Ok going to check that.

As for compression, I have zfs compression. Same zfs compression on remote. I suppose it is decompressed, sent through ssh then recompressed even though it is the same compression? Or is zfs that great that it will receive it encrypted as well? I tried lz4, it was very slow, but I haven't tried without compression, might be as slow but I doubt.

**Comment by ThomasWaldmann** [comment]
```
    -e none                         \
```

That looks suspect also.

**Comment by jogood** [comment]
It's no encryption. It is a simple example

**Comment by ThomasWaldmann** [comment]
lz4 is one of the fastest compression algorithms existing and usually faster than uncompressed (because it has to transfer / write less data.

You can only set encryption with `borg init -e ...` per repo. You can't change encryption on a per archive basis (with borg create).

**Comment by jogood** [comment]
> ```
> Remote: user@url.backup: Permission denied (publickey,password).
> ```
> 
> Your ssh setup is not working. You should have the ssh pubkey in `~/.ssh/authorized_keys` on the repo server.

Ok, its likely working. Still add a prompt but that's because I didn't add port in my init command I think. Will try again with cron later. Thanks a lot!

**Comment by jogood** [comment]
It's working!

As of lz4, is it possible that for some old hardware it is just not fast? I haven't tried lz4 on zfs (except maybe it was the default on FreeBSD installation), but zstd didn't slow down anything (possibly faster, I don't know). I think I have tried tar with lz4 encryption and it was much slower than not encrypted (on this same device). xz was super slow.

Anyway, I will try lz4 after that and see how long it takes.

**Comment by ThomasWaldmann** [comment]
Usually (e.g. on amd64 / x86-64 platform) lz4 should be faster than zstd,1.

**Comment by jogood** [comment]
Ok. I can say that no compression isn't faster. Now my question is, is there advantage to add borg compression if zfs source and destination are already using zstd compression? The bottleneck is the lan and CPU usage.

**Comment by ThomasWaldmann** [comment]
If you use an encrypted repo, the filesystem below the repo files can't compress anything.

The compression in the filesystem of the source files is irrelevant, because it will be transparently uncompressed when borg reads the files.

**Comment by jogood** [comment]
Good point! Thanks a lot again
