### ISSUE TITLE
backup from  FTP to Borgrepository --> read: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by pcace** [borgbackup/borg#7516]
Hi There, 

i am trying to backup an FTP share (yes i know its kind of weird but the medium is only available via FTP :/ ) to a Borgbackup repository. 
the problem is, that i always run into some i/o errors like this: read: [Errno 5] Input/output error

as a repository a use a storagebox from hetzner.de and the backupping device is a raspberry pi with borgbackup 1.2.4

the failing files are totally fine if checked directly. 

if you have any idea what i can do here, please let me know!

**Comment by ThomasWaldmann** [comment]
I/O errors are below borg, usually a disk / ssd or fs problem.

Check what exactly the error msg is saying, so you can locate the issue and fix the problem before doing anything else.

**Comment by Jamie-Landeg-Jones** [comment]
I don't know what OS you are running, but certain sdcards don't play well with the raspberry pi, and can produce random input/output errors on large filesystem access.

In fact, one of my old pi2's I use as a proxy relay at my mums house running freebsd often crashes out completely if you just do a "find / ..." -- my temporary solution was to add a USB stick, and move all but the root filesystem to that.. It's been stable since!

**Comment by ThomasWaldmann** [comment]
An SSD connected to a USB-SATA adaptor might be even more reliable and performant.

**Comment by pcace** [comment]
Hi, thank you so much for all the comments. tbh its kind of hard to imagine that it has something to do with the filesystem on the raspberry pi since i am mounting the FTP (also tried with a SMB share) to the raspberry and then backup it to a remote location. Does it cache files and the cache is too slow or so? how would i find the exact problem, because when i manually copy the file for example form the FTP to the raspberry pi it totally works.
If anyone has an idea what i could do please let me know!! Thanks a lot!

**Comment by ThomasWaldmann** [comment]
@pcace if you post the full traceback including the full error message and also the precise command you used, we maybe can help you locating the problem.

**Comment by Jamie-Landeg-Jones** [comment]
@pcace Also, which OS are you running?

As an aside, I'd never heard of Hetzner storage box until I read your post.... But anyway, I'm now the proud owner of my own Hetzner storage box (to be used as a backup to my borg-backup server), so thanks for that!! :-)

**Comment by pcace** [comment]
Hi, i have solved it by not using FTP. I found that the share also supports SMB. 
Sorry for not beeing able to share more information about the issue :/ but it probably wasnt a borg problem anyways...
cheers
