### ISSUE TITLE
Borg prints out "Repository XXX does not exist" if ssh access is denied

### ISSUE THREAD

**Issue by Forceu** [borgbackup/borg#7525]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

Server: 1.2.0
Client : 1.2.4

#### Operating system (distribution) and version.

Ubuntu 22.04

#### Hardware / network configuration, and filesystems used.

SSH over wireguard

#### How much data is handled by borg?

~ 6TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
REPOSITORY="server-wg-borg:/backup/folder/"
export BORG_PASSPHRASE=password
borg list $REPOSITORY
```

SSH config:

```
Host server-wg-borg
  Hostname server-wg (resolves to valid IP)
  User borgbackup
  IdentityFile /home/user/.ssh/id_rsa
```

The same happens with the `create` command

## Describe the problem you're observing.

If SSH access is denied, borg simply reports, that the folder does not exist instead of reporting that SSH access was not granted.

#### Can you reproduce the problem? 

- Deny SSH access
- Create new backup

**Comment by ThomasWaldmann** [comment]
please use ssh:// url syntax to avoid parsing ambiguities.
Am 16. Apr. 2023, 11:55 +0200 schrieb Marc Ole Bulling ***@***.***>:

**Comment by ThomasWaldmann** [comment]
Guess this will solve it, reopen in case it doesn't.
