### ISSUE TITLE
Why is Borg stating "Archive doesn't exist"?

### ISSUE THREAD

**Issue by richardskumat** [borgbackup/borg#753]
Hello,

I'm having issues with Borgbackup on debian testing, version: https://packages.debian.org/stretch/borgbackup, borg 1.0.0.

Archive is not password protected or encrypted. It's simply sitting on an external usb drive.

Here's the output of borg list /path/to/archive:

```
user@debian:~/tmp/borg$ borg list /path/to/archive
::Sunday                             Sun, 2016-03-13 15:01:49
::Monday                             Mon, 2016-03-14 09:00:08
::Tuesday                            Tue, 2016-03-15 19:09:18
```

I've tried to extract Sunday's archives, but it's saying it doesn't exist.

Command I've tried to extract it to current directory(.):

```
borg extract /path/to/archive::Sunday .

Archive Sunday does not exist
```

Borg info on the archive has the same result:

```
user@debian:~/tmp/borg$ borg info /path/to/archive::Monday
Archive Monday does not exist
user@debian:~/tmp/borg$ borg info /path/to/archive::Tuesday
Archive Tuesday does not exist
user@debian:~/tmp/borg$ borg info /path/to/archive::Sunday
Archive Sunday does not exist
```

Archives are created daily with borg create -v --stats /path/to/archive::Sunday and so on.

What am I doing wrong? I've tried to query the archive with lower case(sunday) word, but get the same result.

**Comment by enkore** [comment]
user@debian:~/tmp/borg$ borg list /path/to/archive
    ::Sunday                             Sun, 2016-03-13 15:01:49

The `::` doesn't belong to the archive name, and when listing archives Borg does not include it. So your archive names somehow end up with an extra pair of `::`.

In any case, this will work:

    borg info /path/to/archive::::Monday
    borg extract /path/to/archive::::Sunday .

**Comment by richardskumat** [comment]
That was indeed the case.

The script I have does the following:

Relevant snippet:

```
var1="/path/to/archive"
d7="Sunday"
borg create -v --stats $var1::${d7}
```
This was my first script with borg and thought ```::``` will be needed for it to work.

Thank you very much.

**Comment by enkore** [comment]
The snippet wouldn't cause a double `::`, maybe $var1 includes a `::` at the end? (Or $d7 at the beginning)?

**Comment by richardskumat** [comment]
I've included it manually. var1 is just a path to the repo and d1..7 are just short vars for each day, 1 starting with Monday to 7 ending with Sunday. I'll remove the ```::``` part and see if it works.

**Comment by richardskumat** [comment]
I was wrong, the path variables indeed had ```::``` after the path.
