### ISSUE TITLE
Control Borg process from another program?

### ISSUE THREAD

**Issue by Daniel-Nashed** [borgbackup/borg#7531]
Hi,

my use case is that I have an application, which puts databases into backup mode one by one, but all the database files should be stored in one `borg create` operation.

This wasn't possible earlier, but with `--paths-from-stdin` I almost have what I need.
What is missing in my approach is a trigger/status when the file is backup-ed and I can get the database file back into normal operations.

One idea was to use the `--list` option. But my tests show, that the file is listed already when Borg starts taking the backup.
I would need a trigger, after the file backup was completed.

My idea would be to hook the input and output of the borg command and control it that way.

If there is an easier way, to get the same use case covered, I am very open for ideas.

From my application view a kind of request model would be best -- like a small API to talk to a running borg operation.

But I think the  `--paths-from-stdin` should be already a good way, if I get any kind of feedback, that the file is done.

Maybe there is an easier way? Maybe having a log option after the file is backed up would be useful also for other requirements?  

In some cases it might be useful to know what is being processed. in other cases (like my case) it would be helpful to see what has been already processed.

Thanks for any tip!

**Comment by Daniel-Nashed** [comment]
Just revisited my request after I discovered a new feature in BorgBackup.

```
borg import-tar --ignore-zeros
```

allows to pipe data into the running backup operation. 

Wrote a prototype in C which does the following:

With popen() start this type of command to write to it:

```
borg import-tar --ignore-zeros 'backup-archiv' -
```

Then use a trigger file which contains the file name to backup and read the data via popen() read from a command like this:

```
tar -cPf - 'myfile' 
```

The data I am reading from one file handle, is written directly into the borg write file handle.
The data has the tar format information for the files. I first thought I would need to write code to write in tar format.
But tar does that for me and just sends me the data stream. 

Once done I remove the trigger file and let me calling program continue with the next file.

I could also find a better communication way, by having the same binary use a two way pipe communication to let it wait until the data was streamed to BorgBackup via tar format.

each file will be in a separate tar file and this will work with the new option ´--ignore-zeros`.

Does this sound like a plan? Or is there an easier way someone could think of?

The C program is already working. I might want to change the communication. The key here is to wait until the file is processed.

-- Daniel

**Comment by ThomasWaldmann** [comment]
@Daniel-Nashed sounds like a plan. And your code then can notice when tar finishes, then also borg is done with that file and you can continue to the next one).
