### ISSUE TITLE
Lock files in multiple directories

### ISSUE THREAD

**Issue by storcium** [borgbackup/borg#755]
Hello, I noticed that lock.roster and lock.exclusive directory appear in two places - ~/.cache/borg and the repo itself.  Is there a relationship between the two and any order to these, i.e. if the repo lock is deleted (for example with a stale/crashed process), should the ~/.cache lock files be deleted too?

Thank you,
Alex

**Comment by RonnyPfannschmidt** [comment]
the locks are independent, the repo ones protect the repo, the cache ones protect the cache

a repo is potentially remote while the cache is local

**Comment by ThomasWaldmann** [comment]
"borg break-lock repo" should destroy both locks.

But be careful when using it, there must be no active borg running in that repo.

**Comment by storcium** [comment]
Thank you very much, this makes sense.

--
Alex Gorbachev
Storcium

**Comment by ThomasWaldmann** [comment]
There is also a open ticket to improve lock-cleanup, so if there is a crash or interruption occurs, locks get removed. Until that's done, use break-lock.
