### ISSUE TITLE
Excludes somehow ignored, worked before

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [borgbackup/borg#7552]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).
borg 1.2.4

#### Operating system (distribution) and version.
Arch linux with kernel 6.3.1-arch1-1; updated today

#### Hardware / network configuration, and filesystems used.
ext4

#### How much data is handled by borg?
~500GB (original, not the backup repo)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

This command was used for  a long time without issues before.

Excludes are needed here!

```
borg create -v -s -p --list --progress \
       	-e re:__pycache__ \
	-e re:.*\.pid$ \
	-e re:/node-modules/ \
	-e re:.*Cache.* \
        -e re:.*cache.* \
	-e re:\.pyc$ \
	-e re:^/dev \
	-e re:^/media \
	-e re:^/mnt \
	-e re:.*\.so$ \
	-e re:.*\.iso$ \
	-e re:^/proc \
	-e re:^/run \
	-e re:^/sys \
	-e re:^/usr/portage \
	-e re:^/usr/share/linux \
	-e re:^/var/cache \
	-e re:^/var/lock \
	-e re:^/var/run \
	-e re:^/var/tmp \
	-e re:^/var/log \
	-e re:.m2 \
        -e re:.gradle \
        -e re:node_modules \
        -e re:tmp \
        -e re:.dvdcss \
        --exclude-caches \
	-C lzma,5 \
        /run/media/jo/4c09d91b-4a57-4cd1-a152-8155c6b915c6/arch-tower::{now:%Y-%m-%d} /
```

## Describe the problem you're observing.

/proc is not ignored, despite being in the exclude list, see above.

```
...
/proc/1379/task/1414/personality: read: [Errno 1] Operation not permitted
E /proc/1379/task/1414/personality
U /proc/1379/task/1414/limits
U /proc/1379/task/1414/sched
U /proc/1379/task/1414/comm
A /proc/1379/task/1414/syscall
/proc/1379/task/1414/syscall: read: [Errno 1] Operation not permitted
E /proc/1379/task/1414/syscall
U /proc/1379/task/1414/cmdline
U /proc/1379/task/1414/stat
U /proc/1379/task/1414/statm
U /proc/1379/task/1414/maps
U /proc/1379/task/1414/children
U /proc/1379/task/1414/numa_maps
...
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, run the command above

#### Include any warning/errors/backtraces from the system logs

Nothing of interest

**Comment by ThomasWaldmann** [comment]
From the docs:

Starting with Borg 1.2, discovered fs paths are normalised, have leading slashes removed and then are matched against your patterns. Note: You need to review your include / exclude patterns and make sure they do not expect leading slashes. Borg can only deal with this for some very simple patterns by removing leading slashes there also.

https://borgbackup.readthedocs.io/en/1.2.4/usage/help.html#borg-help-patterns

So: remove the leading slashes from your patterns and try again.

**Comment by TheCataliasTNT2k** [comment]
Thank you, works.
I might have overlooked that one, but I do not know why.
Have a good one 😉
