### ISSUE TITLE
file changed while we backed it up

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7558]
https://github.com/borgbackup/borg/blob/1.2.4/src/borg/archive.py#L1460

Currently borg 1.2.x compares the **ctime** before backing up the file contents with the ctime directly after that and if they differ, it says "file changed while we backed it up".

On UNIX, ctime is the "inode change time" and it changes for:
- metadata changes (like owner, group, mode, ...)
- file content changes

Guess borg could be a bit more specific:
- before/after backing up the content chunks, it could compare **mtime** instead or additionally to ctime. mtime specifically indicates a **file content change** which can be a major data consistency issue (a slight problem is that mtime is under userspace control, so software can modify it arbitrarily - but that rather can be an issue if it is fake identical, not if it is different).
- borg could also look at the file size before / after and maybe include that in the log message. some files (like log files) are used in an append-only way which is usually not a problem even if the file changes while we read it.

borg master branch is a bit different already: it retries to back up the file if it detects a "change while reading".

**Comment by ams-tschoening** [comment]
> On UNIX, ctime is the "inode change time" and it changes for:

Does it change for last access time as well? In that case, depending on how file systems are mounted, Borg itself might be the reason to unnecessarily repeat backup attempts?

**Comment by ThomasWaldmann** [comment]
No, ctime doesn't change by just reading the file, only atime does that.

**Comment by ams-tschoening** [comment]
My question was if atime changes trigger ctime changes at some point because atimes are written metadata as well in the end. But that doesn't seem to be the case and atime really handled specially: https://askubuntu.com/a/748902/512299

**Comment by ThomasWaldmann** [comment]
Hmm, guess this is problematic for the same reason borg by default does not use mtime for the files-cache "is this file still the same" detection:

mtime is unreliable as it can be controlled from user space and there are tools that reset mtime after modifying a file.

So we sadly can not conclude `same mtime -> file contents did not change`. If there is a change in ctime, we must assume there could have been a content modification also.
