### ISSUE TITLE
does the fixed chunker avoid having to obfuscate

### ISSUE THREAD

**Issue by elandorr** [borgbackup/borg#7560]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## Describe the problem you're observing.

Do multiple files fit in one chunk in borg? If so, then using fixed chunks avoids having to bloat files for plausible deniability, right? Nobody would know, if that's 1 file, or 1000.

'Duplicati' creates roughly(?) equal blocks and does not leak any info about the files contained, if I remember correctly. Maybe borg's idea works different.

The only downside of the fixed chunker, if that's the case, would be that you always have to transfer at least one full chunk, even, if the file changed is 1KiB. Right?

**Comment by ThomasWaldmann** [comment]
1 file -> at least 1 chunk (borg does not put data from multiple files into one chunk).

for small files (below chunk size), the chunk size will be something like file_size + overhead, so fingerprinting is possible here.

in case of the fixed chunker: it cuts pieces of the specified size as long as it has enough data to fill them. The last piece will be smaller.

borg creates segment files of, by default, ~500MiB. so you do not directly "see" chunk sizes in the file system.
but, the repo index contains segments/offsets, so chunk sizes are visible there.

**Comment by elandorr** [comment]
Thank you for the explanation. I reckon the fixed chunker is only useful for full block device backups, then, like the docs mention. Otherwise it's a guess for which chunker settings may be best for index performance.

more chunks = better dedup
fewer chunks = more scalability

**Comment by ThomasWaldmann** [comment]
BTW, both chunkers will produce at least one new chunk for any content change in a file.
Also, the chunksize of that is determined by the chunking algorithm and there is no effort done to minimise the chunk sizes to **only** contain the changed data.

**Comment by elandorr** [comment]
Really interesting program. 5 seconds to get something done, but a lot of complexity to dive into. Thanks for your help.
