### ISSUE TITLE
--one-file-system pointless when --paths-from-stdin

### ISSUE THREAD

**Issue by elandorr** [borgbackup/borg#7566]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG/peculiarity

#### Your borg version (borg -V).
1.2.4
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg create \
  --verbose \
  --progress \
  --show-version \
  --show-rc \
  --stats \
  --list \
  --filter=AMCE \
  --compression obfuscate,115,zstd,9 \
  --exclude-caches \
  --one-file-system \
  --paths-from-stdin \
  ::"barfoo_{now}" \
```

## Describe the problem you're observing.

Because there's no input equivalent for `--exclude-from`, I built something that feeds paths to borg. (I don't want to have to deal with possible CLI limits, so I built it to forget. Some say max is 4K which might be too little at some point.)

I think this is, because I generate the includes using `find`. I have to, as `--paths-from-stdin` doesn't recurse. Because borg gets a path to a file inside that folder, it doesn't see a device mismatch.

Not sure what to do about it, but now you know.

Possibilities:

- add a note about this to the docs
- add a flag for accepting includes from a file
- add a flag to toggle recursion
- set base path from starting pwd and exclude mismatches based on that (maybe also as a flag)

I just used `find`'s `--one-file-system` equivalent, but that may not apply to every scenario.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes see above

**Comment by ThomasWaldmann** [comment]
If you use paths from stdin, borg just does what you say and backups all the given files.

Guess we could make the docs more clear about that.

**Comment by elandorr** [comment]
I might add that, if you confirm I got the doc process right.

An option to read paths from a file and let borg do the recursion would be useful either way. Less chance to make a mess.

**Comment by ThomasWaldmann** [comment]
Read just the "paths" (guess you mean the recursion roots) from a file: you can already have that, either by:
- a little shell scripting, paths end up being `borg create` cli arguments (only for few paths), or
- a patterns file, give the paths as `R` lines

I guess I would rather not like to implement mixed control. Either borg has control and does the recursion, include/exclude, etc. or the control is external and just feeds a final list of files into borg. Mixing both modes makes it much more complicated to implement and to understand.

**Comment by elandorr** [comment]
I see your point. I think that's a misunderstanding. We both want the same thing, only that it also take a file instead of just args:

- Borg accepts a file/pattern list for incl. and excl., recursion and filtering are neatly in py.
- Borg opens stdin and the user feeds it a pre-computed list that's taken verbatim.

> (only for few paths),

I just finished making this infinitely scalable: I read my plaintext list, pipe it to find, results end up in borg. In the middle a grep eats an exclude pattern file, and filters.

My goal was:

- 'unlimited' potential includes without worrying about any CLI limits
- filter via excludes

That works now (includes are read live, excludes are read into memory once), but I feel this could be way more elegant in py directly than my bash madness. 

_Oh my God._ While typing, I read the same page again, and noticed:

![image](https://github.com/borgbackup/borg/assets/56206745/51304933-2996-47ce-861e-b1217651f12c)
My mind read '**exclusion** options' and stopped looking for 'include'.

![image](https://github.com/borgbackup/borg/assets/56206745/8e737424-c2a9-47ef-9d69-8388f4b14fcb)
But it's also for includes.

I kept looking for 'incl' in here: 
![image](https://github.com/borgbackup/borg/assets/56206745/593aae07-ea84-46ec-931e-264105e7cb4d)

Well. It was an exercise in bash, then. :)

> the paths as R lines

Searched for 'recursion', didn't spot anything, read many other pages 5 times, but that one. I should've read the page in full instead of '/'-ing around.

I hope borg is the final backup tool, because now I know too many BorgFacts™. The only thing still a bit worrying is speed. A small first run took 9 minutes; I can now understand at least a little whoever here had to do a PB and got a bit edgy. But this still seems faster than the (opensource) alternatives. And who could trust a corporation with backups? Since Snowden we know all the big stuff is backdoored.

The dedup is glorious! We can have it backup every single day without bothering about space. (Well, no experience with the cache, yet.)

I might add a note to --paths-from-stdin to make it clear it's exclusive. Maybe we could rename 'exclusion options' to 'include/exclude options', but I understand, if you think that sounds worse.

Thanks for your help and cheers

**Comment by ThomasWaldmann** [comment]
Yeah, the headline could be "include/exclude options", that would be better.

Indeed, borg is a bit slow for the first backup, but after you have that (and your daily changes are just small to medium size, like for most people), it'll be pretty fast for most 2nd+ backups.

**Comment by elandorr** [comment]
Looking forward to seeing it in action.

It's better to keep datasets small, anyway. The prevalent dogma of infinite growth is killing us. But a few TB are unfortunately already common. I'll start with a small box.

I'm interested in scalability out of curiosity. Usually the answer to 'how do they do it' is just 'they throw money at it'. But I always imagine some crazy genius algo. The draw to dedup/inc is viability on low-end to me. Most people/orgs don't have res to throw around, but still quite a bit of storage to handle. Those with $ just dump everything 1:1 live anyway. If you can afford such servers as mentioned here sometimes, you can afford to pay a guy to move a physical drive from a RAID and skip the whole shenanigans.

Is it possible to allow integrity verification on the remote? (without pass) Would save a lot of traffic. I suppose doing a full one once a week/month is advisable. Pushing it from the client would be helpful too, in case of servers where one doesn't have direct access. Though the other admin might not want to allow that, or people could push the button too often.

**Comment by ThomasWaldmann** [comment]
There was some recent change to the docs of `--paths-from-stdin`:

read DELIM-separated list of paths to backup from stdin. 
***All control is external: it will back up all files given - no more, no less.***

Guess that is clear enough now.
