### ISSUE TITLE
Improved output format for 'borg diff'

### ISSUE THREAD

**Issue by Ape** [borgbackup/borg#757]
I'd like to thank @enkore and @ThomasWaldmann for implementing ```borg diff``` command. It is really useful for me and it works surprisingly fast. See #177 and #740.

I'd like to have a slightly modified output format for the command. I will present one draft that I think would be very good, but please tell your opinions about the format. We might want to support multiple formats if so desired.

In the current version, each change will take two lines of output. The most important change I'd like to propose is to have only one line per change. In addition, the file paths may be long so anything on the line after the path may be hard to see; especially since the path length typically varies a lot between lines. The format should be also terse and quick to read.

It could look like this:
```
+ path/to/added
- path/to/deleted
[content: +202 B, -215 B] path/to/contents_changed
[user: root -> ape] path/to/user_changed
[mode: -rw-rw-rw- -> -rw-r----] path/to/permissions_changed
[mode: drwxr-xr-x -> lrwxrwxrwx] path/to/folder_to_symlink
[content: +42 kB, -532 kB] [user: ape -> root] [group: users -> root] [mode: -rw-r---- -> -rw-rw-rw] path/to/everything_changed (should be quite rare case)
...
```

**Comment by enkore** [comment]
#751 gives us a flexible `ItemFormatter` that is extensible as well, that can be used for this (e.g. two formatters which are output one after the other with the "old" and "new" item --- whether that results in two output lines is up to the format used).

**Comment by Ape** [comment]
Maybe we could also use terminal colors and bold font. For example deleted files could be red lines, and new files could be green. I'd like to make examining long change lists as easy as possible.

**Comment by enkore** [comment]
Hmm, terminal color handling is quite complicated. If this should be implemented (i have no particular opinion), then it would have to use a soft-dependency, implementing it ourselves is way too much effort. A soft-dependency might be justifiable in this case, since it is no loss of essential functionality if on some systems no colors are printed.

---

Your proposed format looks good to me.

**Comment by ThomasWaldmann** [comment]
no terminal colours for now.

i still have to play with the code and practically try it, but proposal sounds good.

**Comment by Ape** [comment]
I was thinking about this a bit more and realized that the paths should be aligned as possible. Rare cases, like lots of changed metadata, can be an exception to this. So here is something along these ideas:

```
added       path/to/added
removed     path/to/deleted
+842B -215B path/to/contents_changed
+12M  -111K path/to/contents_changed2
[u:root -> u:ape] path/to/user_changed
[g-w o-rw]  path/to/permissions_changed
[drwxr-xr-x -> lrwxrwxrwx] path/to/folder_to_symlink
+42K  -532K [u:ape -> u:root] [g:users -> g:root] [g+w o+rw] path/to/everything_changed
...
```
