### ISSUE TITLE
Is borg prune filtering not handling `sh:` prefixes ?

### ISSUE THREAD

**Issue by rafariossaa** [borgbackup/borg#7570]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
client (ubuntu 23.04): borg 1.2.4
server (debian 11): borg 1.1.16

Vorta (ubuntu 23.04): Vorta 0.8.10

#### Operating system (distribution) and version.
client (ubuntu 23.04)
server (debian 11)

#### How much data is handled by borg?
Less that 2 GB, this is a small toy environment

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
$ borg prune --list --info --log-json --keep-hourly 2 --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 2 -a sh:rafa-laptop* --keep-within 1H backup_user@backup-server.net:/home/backup_user/backup_vault/trabajo
```
## Describe the problem you're observing.

The above command does not return the list of archives to delete, however, if I remove the prefix `sh:` it works. I tested several bash regular expression and they worked, but when they are prefixed by `sh:`, for example:

```
$ borg prune --dry-run --list  --keep-hourly 2 --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 2 -a 'sh:{hostname}*' --keep-within 1H backup_user@backup-server.net:/home/backup_user/backup_vault/trabajo

or

$ borg prune --dry-run --list  --keep-hourly 2 --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 2 -a 'sh:rafa-laptop*' --keep-within 1H backup_user@backup-server.net:/home/backup_user/backup_vault/trabajo
```

The `borg prune` line is generated by vorta, and as far as I can tell by reading the docs it should work, but maybe I am just missing something. 

The archives looks like this:
```
$ borg prune --dry-run --list  --keep-hourly 2 \
  --keep-daily 7 \
  --keep-weekly 4 \
  --keep-monthly 6 \
  --keep-yearly 2 \ 
  -a '{hostname}*' \
  --keep-within 1H \
  backup_user@backup-server.net:/home/backup_user/backup_vault/trabajo


Keeping archive (rule: within #1):       rafa-laptop-2023-05-15-210824        Mon, 2023-05-15 21:08:25 [c3dfae3bd7bce6b369b65324a363825ef798075b1dbdbf0468532a275dd32bbb]
Keeping archive (rule: hourly #1):       rafa-laptop-2023-05-15-173403        Mon, 2023-05-15 17:34:04 [2f8dd30e009a5907b1c8b443e48eb82bb68aef7768a789306fe83845f7310440]
Would prune:                             rafa-laptop-2023-05-15-172400        Mon, 2023-05-15 17:24:01 [d1374c8f187f379fb559871e68bb7b5dd457b522d10a0a44cfb1ebd6000556d3]
Would prune:                             rafa-laptop-2023-05-15-171357        Mon, 2023-05-15 17:13:58 [e58f863dce5c9a6ee489018dcaf8d4dad4bb9e8de183e7e662b115b59329f617]
Would prune:                             rafa-laptop-2023-05-15-170354        Mon, 2023-05-15 17:03:55 [10ff3cd3124dbedd46e0ba2abdbd5c60285a1b0403c6b91c7f7789ed7f52d520]
...
```

**Comment by ThomasWaldmann** [comment]
borg 1.2.4 docs: https://borgbackup.readthedocs.io/en/1.2.4/usage/prune.html

`-a` aka `--glob-archives` expects sh-style globbing patterns in borg 1.2.

But, as it **only** can process that style of patterns in borg 1.2, it did not expect a `sh:` prefix there.

Support for other styles was added for borg2 (and also the `-a` long name was renamed to `--match-archives` to reflect that it is not just globbing any more).

borg2 docs: https://borgbackup.readthedocs.io/en/master/usage/prune.html (guess needs some fixes, still talks about --glob-archives at some places)

**Comment by ThomasWaldmann** [comment]
@m3nu ^

**Comment by m3nu** [comment]
I recall making some adjustments for different versions for this. So should be good for Vorta.

**Comment by ThomasWaldmann** [comment]
@rafariossaa can you edit the top post and add the vorta version that generated that prune command?

**Comment by m3nu** [comment]
Related change in Vorta: https://github.com/borgbase/vorta/pull/1565/files

**Comment by rafariossaa** [comment]
@m3nu The vorta vresion I am using (0.8.10), use this code:
```
            if borg_compat.check('V122'):
                pruning_opts += ['-a', 'sh:' + formatted_prune_prefix + '*']
            else:
                pruning_opts += ['--prefix', formatted_prune_prefix]

```
So it is not handling well the version as in the PR you indicated.

I will updated my versions and provide feedback.

Thanks.

**Comment by rafariossaa** [comment]
I upgraded vorta to `0.8.12` and it worked perfectly.

This issue could be closed.

Thanks you all.

**Comment by m3nu** [comment]
Awesome! Good we verified the fix works correctly.

**Comment by ocroquette** [comment]
I just got hit by this bug. I guess I am not the last one, since Ubuntu 23.04 (Lunar Lobster) is still using Vorta 0.8.10 at this time. 

See also https://packages.ubuntu.com/search?keywords=vorta

As a workaround, I patched ```/usr/lib/python3/dist-packages/vorta/borg/prune.py``` manually.

Thanks for the information and the fix.
