### ISSUE TITLE
borg disobeys backup pattern

### ISSUE THREAD

**Issue by willrabbermann** [borgbackup/borg#7572]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug/Issue

## System information. For client/server mode post info for both machines.

GNU/Linux

#### Your borg version (borg -V).
borg 1.2.4

#### Operating system (distribution) and version.
gentoo

#### Hardware / network configuration, and filesystems used.
ext4 nfs wireguard

#### How much data is handled by borg?
Was ~30 GB now is 56 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

bkp-patterns
```
R /

- /mnt/*/
- /export/*/

- /media/
- /dev/
! /proc/
- /sys/

- /tmp/
+ /var/cache/binpkgs/
+ /var/lib/portage/
- /var/cache/
- /var/tmp/

- /home/*/.cache/
- /var/db/repos/
+ pf:/usr/src/linux
- /usr/src/

- /var/lib/libvirt/images/
- /swapfile
- /home/*/.local/share/Steam/
- /home/*/Downloads/
```

```
borg create -sv --progress --exclude-caches --patterns-from $bkp-patterns $osbackups::{hostname}-root-{now} /
```

## Describe the problem you're observing.

My $osbackups repository was usually ~30 GB now it is 56 GB.
I was working on large data in ```/mnt/mmc``` where my sd cards were mounted for a few weeks and I was working on various cards. It seems to have backed up everything in /mnt/mmc even after deleting the old backups, its huge. I have run borg compact on my repo.

I've reverted to an old version of my repo since.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
I checked my bkp-patterns files but 
```- /mnt/*/```
seemed to be working before. It seems to have still backed up /mnt/mmc and made my laptop run out of space (damn)

#### Include any warning/errors/backtraces from the system logs
N/A

**Comment by willrabbermann** [comment]
```
Cache, or information obtained from the security directory is newer than repository - this is either an attack or unsafe (multiple repos with same ID)
```
gotta delete .cache...

**Comment by willrabbermann** [comment]
would like to add a feature request for borg-list command.
would be nice if we could ```borg list --format '{name} {size} {NL}' repo``` but I know then you would want to do original/compressed/deduplicated variants of ```size``` for consistency. uhhh maybe I could commit this

**Comment by ThomasWaldmann** [comment]
@willrabbermann Please read the borg 1.2.x docs about leading slashes. `borg help patterns`

**Comment by willrabbermann** [comment]
@ThomasWaldmann

> Starting with Borg 1.2, discovered fs paths are normalised, have leading slashes removed and then are matched against your patterns.  Note: You need to review your include / exclude patterns and make sure they do not expect leading slashes. Borg can only deal with this for some very simple patterns by removing leading slashes there also.

I see, I should remove leading slashes from the patterns.
I still like to include the ending slash, therefore the directory itself but none of its contents.

```
R /

- mnt/*/
- export/*/

- media/
- dev/
! proc/
- sys/

- tmp/
+ var/cache/binpkgs/
+ var/lib/portage/
- var/cache/
- var/tmp/

- home/*/.cache/
- var/db/repos/
+ pf:usr/src/linux
- usr/src/

- var/lib/libvirt/images/
- swapfile
- home/*/.local/share/Steam/
- home/*/Downloads/
```
How would I test my patterns before running ```borg create``` with a live repo?
Answer:

> To test your exclusion patterns without performing an actual backup you can run borg create --list --dry-run ....

This is very good documentation. Thank you for the help sir!

**Comment by willrabbermann** [comment]
By the way the reason it backed up mmc because ``` I did this ``` I have two backup patterns because I was lazy. Dont be lazy. it should work perfectly now

**Comment by willrabbermann** [comment]
is there a way to to this:
```
R /

- mnt/*/
+ mnt/samsung750evo/*/
- mnt/samsung750evo/*/
```
it still includes mnt/samsung750evo/*/'s contents

**Comment by willrabbermann** [comment]
@ThomasWaldmann lmk if it's possible or a more concise way to do the above, I exclude everything in mnt/ but some directories have structures I'd like saved in the archive.

**Comment by ThomasWaldmann** [comment]
```
+ mnt/samsung750evo/*/
- mnt/samsung750evo/*/
```
That doesn't make sense as it is "first match" (which is always the include) and it will never match the exclude.

So not sure what you want to achieve with that.

**Comment by willrabbermann** [comment]
This order seems to work exactly as I want:
```
R /

- mnt/samsung750evo/*/
+ mnt/samsung750evo/

- mnt/*/
```

>  it is "first match" (which is always the include) and it will never match the exclude.
So first it matches ```- mnt/samsung750evo/*/``` but wouldn't backup anything until I include
```+ mnt/samsung750evo/```
