### ISSUE TITLE
fix stretch vagrant box

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7579]
we use the `debian/stretch64` box (currently 9.12.0) and it is broken since the apt source was moved to archive server.

we use the box to intentionally build a old borg binary that works on stretch and similarly old linux systems.

Changes needed to the box, todo for box maintainer:

- apt sources.list: the `security.` and `deb.` server do not work any more, use `archive.`!
- apt update
- apt dist-upgrade -y
- apt install rsync  # pre-install rsync so vagrant does not have to install it when booting the box
- re-package and upload to app.vagrantup.com

https://app.vagrantup.com/debian/boxes/stretch64

Note: because `vagrant up` already breaks at trying to install `rsync`, this can not be fixed easily by box users.

**Comment by ThomasWaldmann** [comment]
@jk4949 https://app.vagrantup.com/debian there are some infos about how to file an issue / contact them.

**Comment by jk4949** [comment]
@ThomasWaldmann  Thank you! I have already read it... I will try to contact them...

**Comment by ThomasWaldmann** [comment]
@jk4949 did you communicate with the maintainer?

**Comment by jk4949** [comment]
@ThomasWaldmann I still have not received any feedback .

 Is the support for the outdated system absolutely necessary or could it be replaced with a current LTS version for example?

The vagrant box of Debian/Stretch seems to be no longer maintained.

**Comment by ThomasWaldmann** [comment]
A borg binary built with an old glibc (so it can run on old Linux) depends on that.

**Comment by ThomasWaldmann** [comment]
Moved this to rc1 milestone. If the box is not fixed until then, there will be no binary built on stretch / built with a glibc as old as found on debian stretch.

**Comment by ThomasWaldmann** [comment]
todo: try https://app.vagrantup.com/generic/boxes/debian9

**Comment by ThomasWaldmann** [comment]
Due to OpenSSL 1.1.1 being EOL now, guess we won't keep the stretch box alive for borg2.

If the box gets fixed until 1.2.7, it might live on for borg 1.2.x releases, we'll see.

**Comment by trendymail** [comment]
Please, do not drop support of "fat" binary "borg-linuxold64" (stretch) for Borg 1.2.X.

OpenVZ/Virtuozzo 7 provides "OpenSSL 1.0.2k-fips  26 Jan 2017"

I know this is absolutely outdated but OpenVZ/Virtuozzo 9 is not ready at all (beta almost unusable).

In the meantime, I will check how to build Borg from sources (I am not a dev...)

**Comment by ThomasWaldmann** [comment]
fixed in 1.2-maint by #7857.
