### ISSUE TITLE
sh: style patterns: support {alt1,alt2} shell-style alternatives

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7602]
See the TODO comment in `borg.helpers.shellpattern`.

**Comment by DavidRambo** [comment]
Hello, thank you for using the "good first issue" label : )

I'm working on this (along with corresponding tests) and intend to have a pull request soon. My next step is to translate the "stuff" constituting the alternative groups as well as to handle nested groups.
