### ISSUE TITLE
Extracting archive with hard-linked files and --strip-components fails

### ISSUE THREAD

**Issue by nprncbl** [borgbackup/borg#761]
I use borg to backup dovecot maildirs. Dovecot uses hard-links for copied mail to avoid storing messages multiple times if users copy them.

When you restore an archive with a backup of a Dovecot maildir and that maildir contains hard-links, the restore works just fine. Look at this example of a restored mail message that has been copied by the user from the inbox to some other folder:

`root@node4:/tmp# ls -l /tmp/large/vmail/somedomain.com/someuser/.Newsletter.Logistics\ Viewpoints/cur/1457623913.M965480P3612*`

`-rw-r--r-- 2 vmail vmail 59K Mar 10 15:31 /tmp/large/vmail/somedomain/someuser/.Newsletter.Logistics Viewpoints/cur/1457623913.M965480P3612.node4,S=59664,W=60637:2,Sab`

Notice the two links to this file.

The same message can be found in the restored inbox of this user, and it is hard-linked to the same file on disk. Perfect!

Now, let's use borg's great --strip-components feature, as we really do not care for all that prefixed stuff and only want to restore the somedomain part of the archive:

`root@node4:/tmp# time borg extract --verbose --sparse --strip-components 2 /path-to-borg-repo/vmail.borg::vmail.2016-03-17.05-00 large/vmail/somedomain`

The extraction works fine in general, but it complains about missing directories or files when trying to make the hard-links contained in the archive:

`large/vmail/somedomain/someuser/cur/1457623913.M965480P3612.node4,S=59664,W=60637:2,STac: [Errno 2] No such file or directory: '/tmp/large/vmail/somedomain/someuser/.Newsletter.Logistics Viewpoints/cur/1457623913.M965480P3612.node4,S=59664,W=60637:2,Sab' -> '/tmp/somedomain/someuser/cur/1457623913.M965480P3612.node4,S=59664,W=60637:2,STac'`

To me, it seems that the --strip-components option is not taken into account when computing the source and destination for hard-linking files.

Please let me know if you need any more information or clarification.

Thanks for working on borg - it is an awesome piece of backup software!

**Comment by enkore** [comment]
Interesting find.

For symlinks it's probably best to not change anything, they should be stored as absolute paths anyway.

For hardlinks the file should extracted like a regular file if the source lies outside the --strip-components subtree.

**Comment by enkore** [comment]
be51b91 contains a failing test case demonstrating the issue.

Hm, not so easy to solve. I think to do this properly we'll need to essentially rebuild the hard_links dictionary used at creation time, which creates a chain of items linked by b'source' (by remembering the last seen path of any hard link, and pointing b'source' at that path for a new hard link) - only the first item in this chain has the chunks, but no b'source'. So how do we know when extracting that we need to remember an item, we haven't seen yet if it's b'path' occurs in any future b'source'...

**Comment by enkore** [comment]
In b7f8165 I added an additional failing test, that triggers this behaviour by specifying a path to extract and not using the somewhat obscure --strip-components.

I think this: 

> Or we store a mapping path => chunk_ids (we don't need more for a hard link), of all items (which could be hundreds of MB for large archives). The "chain building algorithm" used by create and described above guarantees that this gives the correct results.

Might be the only way to correctly extract hard links when extracting any subset of a archive: even --exclude will trigger this.

**Comment by enkore** [comment]
Patch PR in #763
