### ISSUE TITLE
first line of create log is mixed with another line

### ISSUE THREAD

**Issue by elandorr** [borgbackup/borg#7612]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
yes

## Is this a BUG / ISSUE report or a QUESTION?

bug

#### Your borg version (borg -V).
124
#### Operating system (distribution) and version.
deb stable
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
 `borg create --verbose --progress --iec --stats --list --filter=AMCE --paths-from-stdin --paths-delimiter '\0'`

## Describe the problem you're observing.
the first line is mixed up in the following way:

```
Creating archive at "ssh://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXborg::main_2023-05-28T19:44:38"
M /XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/XXXXXXXXAAAAAAAAAAAAAAAAAA 
```

I left it as is, only blackened out chars. In case it's related to length you know exactly. The first part however consists of more than just one folder.
Near the end it suddenly mixes with another file. The rest of the log seems to be normal.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, seems to happen every time. Only now looked closely enough at the stream of files flying by to notice it.

**Comment by ThomasWaldmann** [comment]
`--list` and `--progress` shouldn't be used together as that will mix up their output.

IIRC we added already a warning for that recently.

**Comment by elandorr** [comment]
I see. Thanks!
