### ISSUE TITLE
Ignore --filters with --dry-run

### ISSUE THREAD

**Issue by infectormp** [borgbackup/borg#762]
Currently when we run ```borg create --dry-run``` we always get to log status **-** and if we use ```--dry-run``` with ```--filters``` we will always have 1 line in log ```terminating with success status, rc 0```.

Maybe we need ignore ```--filters``` if ```--dry-run``` used?

**Comment by ThomasWaldmann** [comment]
yeah, sounds good.

**Comment by ThomasWaldmann** [comment]
alternatively, we could use the same letters as normally instead of "-" log status.

i did not want to do that when implementing it so that nobody thinks the files / dirs / etc. were processed, but it is obvious that they were not (thus "-").

**Comment by infectormp** [comment]
well this was my first idea show normal status instead of "-". Show normal status with --dry-run will help completely simulate backup process.

**Comment by infectormp** [comment]
and i vote to show normal status

**Comment by infectormp** [comment]
i was confused when run  --dry-run with --filters and get empty log :)

**Comment by ThomasWaldmann** [comment]
Hmm, there is the issue that (IIRC) regular file status (the different uppercase status chars) can not be determined correctly in a dry-run.

**Comment by ThomasWaldmann** [comment]
I am closing this as we would not be able to reproduce same output as without dry-run, so it is maybe better to keep the "-" status. If you want to see it using the filter, just add "-" to the filter.
