### ISSUE TITLE
Borg mount is not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by edwinclement08** [borgbackup/borg#7632]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
borg 1.2.4
#### Operating system (distribution) and version.
Ubuntu 20.04.6 LTS

#### Hardware / network configuration, and filesystems used.
2 vCPU 2GB VPS
ext4 SSD 40GB

#### How much data is handled by borg
1 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg --debug mount .::server01-2023-06-08T18:20:12.589988 /mnt/second/

## Describe the problem you're observing.
Unable to mount archive. Have tried the binary release as well as the borg PPA.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
```
$ lsmod | grep fuse
fuse                    4242  -2
```
$ modprobe fuse 
```
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.4.0
```
Tried installing fuse3, libfuse3 and fuse, libfuse. Nothing did any changes to the error.

#### Include any warning/errors/backtraces from the system logs
```
using builtin fallback logging configuration
33 self tests completed in 0.13 seconds
Verified integrity of /home/app/borg_backup/personal/index.36
TAM-verified manifest
security: read previous location '/home/app/borg_backup/personal'
security: read manifest timestamp '2023-06-08T19:52:25.695654'
security: determined newest manifest timestamp as 2023-06-08T19:52:25.695654
security: repository checks ok, allowing access
mount data cache capacity: 2 chunks
Mounting filesystem
fuse: _process_archive completed in 0.7 s for archive server01-2023-06-08T18:20:12.589988
Initializing pyfuse3
Calling fuse_session_new
Calling fuse_session_mount
fuse: device not found, try 'modprobe fuse' first
```

**Comment by ThomasWaldmann** [comment]
Hmm, usually it works like that.

Maybe check our `Vagrantfile`, it has all the steps to provision misc. VMs from standard boxes.

**Comment by edwinclement08** [comment]
Hey @ThomasWaldmann , sorry for not being clear, but this is a hosted VPS. Hostinger.in is the provider.

**Comment by qupfer** [comment]
If its a VPS, is it a "full" vm with its own kernel or just a "container", which use the hosts kernel?

**Comment by edwinclement08** [comment]
Is there a way to check that from the shell? I do run docker inside the VM for some webservices, so I guess it cannot be a container. Also all changes persist a reboot and I use apt to install packages.

**Comment by qupfer** [comment]
> so I guess it cannot be a container. 

As you can run docker-in-docker, the  guess is not right. :-D 

>  Also all changes persist a reboot and I use apt to install packages.

Yes, thats clear. There are other types of containers, which are used for VPS (like OpenVZ/virtuozzo or lxc)

However, you can try the following to get more "information"

`uname -a` and post the output. 

try:
`systemd-detect-virt`

And you can check, if these files exist and look at its content:
`sudo cat /proc/vz/veinfo`
`sudo cat /proc/vz/version`
`sudo cat /proc/sys/xen`

**Comment by edwinclement08** [comment]
Hey, thanks for telling me the likely issue. Regardless, here are the logs that I see
```
app@server01:~$ uname -a
Linux server01.edwinclement08.com 5.4.0 #1 SMP Thu Dec 15 20:31:06 MSK 2022 x86_64 x86_64 x86_64 GNU/Linux
app@server01:~$  systemd-detect-virt
openvz
root@server01:~#  sudo cat /proc/vz/info
f6060665-dd2a-4727-b237-026d88bfe4f3     0   456                2a02:4780:f:7f2a:0:0:0:1   141.136.42.51
```

so, it looks like it uses openvz. Does that imply that the mount mechanism won't work? Is there some alternative mechanism that can be used that does not need kernel support?

**Comment by qupfer** [comment]
Simply said: Yes, this means you can't use fuse on your system. You can ask your hoster, if he can activate fuse for your vserver, but I would not relay on that chance.

**Comment by edwinclement08** [comment]
Thanks for the help, will reach out to support

**Comment by ThomasWaldmann** [comment]
BTW, I just had the same issue when using `borg mount` inside a LXC container under Proxmox VE.

Solution:
```
Proxmox container settings -> Options -> Features -> [X] FUSE
```
