### ISSUE TITLE
*bsd get_runtime_dir()

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7638]
from `platformdirs` we get `/run/user/1001/pytest`, then we call `os.makedirs(d, mode=511, exist_ok=True)` and that fails on `os.mkdir("/run", mode=511)` due to permission denied.

**Comment by ThomasWaldmann** [comment]
Root cause: there is no `/run` dir on freebsd, so `platformdirs` is giving us a invalid directory.

Can someone manage filing a bug there? Thanks!

**Comment by ThomasWaldmann** [comment]
`export BORG_RUNTIME_DIR=/whatever` can be used as a workaround until this is fixed.

**Comment by RayyanAnsari** [comment]
does installing pam_xdg help?

**Comment by ThomasWaldmann** [comment]
didn't try that. is that something usually found on bsd systems?

**Comment by RayyanAnsari** [comment]
it's a package in freebsd, not sure about the other ones.
freshports says it has no dependent packages, so I'm guessing it's not installed by default?

**Comment by RayyanAnsari** [comment]
i was busy for a bit, but it looks like someone contributed a fix in the meantime https://github.com/platformdirs/platformdirs/pull/194

does that fix this?

**Comment by ThomasWaldmann** [comment]
Left a comment there. Guess it at least does not return a completely invalid path any more.

OTOH, not sure if it always works as expected, see there.

**Comment by ThomasWaldmann** [comment]
TODO: retry with current platformdirs release.

**Comment by RayyanAnsari** [comment]
note: platformdirs can also create the directory itself, using the `ensure_exists` arg.

**Comment by RayyanAnsari** [comment]
is this now fixed?

**Comment by ThomasWaldmann** [comment]
Not sure. They merged a change that I guess should work for non-root logged-in users, but not sure about root or when running stuff as a system service.

**Comment by ThomasWaldmann** [comment]
Current code / packages on freebsd:

```
>>> from borg.helpers.fs import get_runtime_dir
>>> get_runtime_dir()
'/tmp/runtime-1001/borg'
>>> from platformdirs import *
>>> user_runtime_dir()
'/tmp/runtime-1001'
```

So guess this is fixed now.

**Comment by ThomasWaldmann** [comment]
https://github.com/platformdirs/platformdirs/pull/201
