### ISSUE TITLE
append-only : a way to prune from the server or a promoted client

### ISSUE THREAD

**Issue by eoli3n** [borgbackup/borg#7645]
By design, if a client can mark backups as ones to remove, then ``borg compact`` can't be automated server-side, because it would destroy any backups deleted client-side.

From the documentation: https://borgbackup.readthedocs.io/en/stable/usage/notes.html?highlight=append-only#id3

> Suppose an attacker remotely deleted all backups, but your repository was in append-only mode. A transaction log in this situation might look like this:
> [...]
> From your security logs you conclude the attacker gained access at 15:54:00 and all the backups where deleted or replaced by compromised backups.

I don't need borg to make security audit. ``--append-only`` miss its aim : block an attacker to delete data.
I need ``--append-only`` to protect me from an attacker, and I also need to be able to continue to prune my backups and free space on the server. The solution is to be able to do this from another place than the client itself.
``borg compact`` works without encryption key, it doesn't know what is in the repository, so this isn't the way.

I would prefer to be able to automate ``borg prune`` server side, or from another client which can access to the repository without ``--append-only``.

To protect backups server-side, I would give a way to borg to natively work with secrets.
```
$ borg set-secret BORG_PASSPHRASE="myStrongPassphrase"
```

**Comment by ThomasWaldmann** [comment]
Please read the docs about borg's threat model and also the already existing tickets and ideas about this. In case you have new ideas that bring us closer to a solution, add them there.

Closing this as a duplicate.

**Comment by ThomasWaldmann** [comment]
#2251 #1772 and maybe some others...
