### ISSUE TITLE
scripts: remove gpg signature upload for pypi

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7649]
from pypi:

What?

During your recent upload of borgbackup to PyPI, we noticed you uploaded a GPG signature. However, support for GPG signatures has been removed from PyPI.
What should I do?

While uploads will continue to work, any signatures uploaded to PyPI will be discarded. It is recommended to no longer upload signatures to PyPI.

**Comment by FelixSchwarz** [comment]
Unfortunately pypi removed GPG support: https://lwn.net/Articles/932721/
