### ISSUE TITLE
`borg --serve` logging on weird providers like Hetzner StorageBox

### ISSUE THREAD

**Issue by debuglevel** [borgbackup/borg#7659]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

borg 1.2 

#### Operating system (distribution) and version.

Hetzner StorageBox

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`.ssh/authorized_keys`

```
command="export BORG_LOGGING_CONF=/home/logging.ini; borg serve --append-only --restrict-to-repository ./BorgBackup/bbb4.avm-konferenz.de",restrict ...
command="borg serve --append-only --restrict-to-repository ./BorgBackup/bbb4.avm-konferenz.de --debug >> /home/borg.log",restrict ...
```

## Describe the problem you're observing.

On some crippled endpoints like Hetzners StorageBox, the restricted SSH commands above do not work. StorageBox does not offer a bash but some weird shell which disallows about everything. Therefore, setting an ENV as well as redirecting stdout/stderr does not work. I guess there is no chance for logging with `borg --serve` for now.

It might work however, if `borg --serve` would offer some `--log-file /home/borg.log` option.
But I absolutely understand if you do not want to add such an option only because of a weird provider with a weird shell.

**Comment by ThomasWaldmann** [comment]
can you try:

BORG_LOGGING_CONF=/home/logging.ini borg serve …
Am 19. Juni 2023, 17:26 +0200 schrieb Marc Kohaupt ***@***.***>:

**Comment by debuglevel** [comment]
> BORG_LOGGING_CONF=/home/logging.ini borg serve …

Just in case anybody else using StorageBox found this issue: Nah, does not work either ;-).

> BTW, the good news here is that I recently refactored how the client/server logging system works.
Sounds nice :) Looking forward to borg2.

I guess I'm closing this, as for borg1.2 there will probably no more changes regarding logging and borg2 seems to include them already.

**Comment by ThomasWaldmann** [comment]
Yeah, no huge changes in 1.2 (and the changes in master related to that were huge and breaking).
