### ISSUE TITLE
borg 2.0.0b6: borg check -p progress printing

### ISSUE THREAD

**Issue by daviehh** [borgbackup/borg#7662]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

## System information. For client/server mode post info for both machines.

client: macos, apple silicon
server: synology, borg2 in docker

#### Your borg version (borg -V).
borg2 2.0.0b6

#### Operating system (distribution) and version.
uname -a:
client: Darwin MacbookPro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
server: Linux nas 4.4.302+ #64570 SMP Sat Jun 3 00:00:25 CST 2023 x86_64 GNU/Linux

#### Hardware / network configuration, and filesystems used.

Local network, mac on APFS, server on btrfs

#### How much data is handled by borg?
~30 GiB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`borg check -v -p`
or
`borg check -p`

## Describe the problem you're observing.

With borg 1.2.4, `borg check -p` shows live percentage progress,
however, with borg 2.0.0b6, `borg check -p` prints nothing until check is done, at which point the progress are printed at once:

borg 2 (nothing printed until check is done):

<img width="325" alt="Screenshot 2023-06-21 at 10 21 33 PM" src="https://github.com/borgbackup/borg/assets/25255906/1c29a8c5-9bc5-49f8-971a-2fcd991b4035">

compare with borg 1.2.4, in progress:
<img width="279" alt="Screenshot 2023-06-21 at 10 17 37 PM" src="https://github.com/borgbackup/borg/assets/25255906/f0d01a00-f790-47c5-974b-18876b1b8522">

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes

#### Include any warning/errors/backtraces from the system logs

N/A

**Comment by ThomasWaldmann** [comment]
The remote logging system (and also how progress messages are handled) in master branch / borg2 now works fundamentally different than before.

I'll check if it can be improved.
