### ISSUE TITLE
after `borg delete ::archive` repo remains same size on file system

### ISSUE THREAD

**Issue by SpiritInAShell** [borgbackup/borg#7671]
This thing is a user error! **I read man borg-delete** but I did NOT NOTICE the warning! I should have! My fault. Very sorry.

## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Couldn't find reference to this isue

## Is this a BUG / ISSUE report or a QUESTION?

Bug? (Hopefully it is something that I do wrong)

#### Your borg version (borg -V).

```
borg 1.2.4
```

#### Operating system (distribution) and version.

Linux Mint 20.3 64 Bit

#### How much data is handled by borg?

Seems independent (I checked with repo A about 120GiB, and repo B about 1.2GiB)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
borg init --encryption=repokey benchmark4.borg
borg create --verbose --progress --stats --compression=none benchmark4.borg::(myDateTimeStamp) <path to backup>
borg delete --debug --list --stats benchmark4.borg::2023-06-24_05-06-40
borg info --verbose benchmark4.borg
borg list --short --verbose --consider-checkpoints benchmark4.borg
```
## Describe the problem you're observing.

(how I discovered this: I wanted to benchmark borg depending `--compression=algo` on a subset of real data I wanted to backup at a later point. I chose a directory with 80GiB data. I wrote a shell script iterating over `none lz4 lzma zlib`. After each iteration I deleted the previously created archive with `borg delete --debug --list --stats --last 1`. After returning to the machine, I noticed that borg reported "no disk space" even after deleting each archive.)

**What I expected:** (What am I expecting falsely?)

- size of repo on filesystem being near 0 after deleting all archives.
- If adding the same file(s), I expect deduplication to happen as data is still remaining in segment files in the repo directory
- `borg check` to recognize segment files on filesystem to be without reference and report/delete them

**What I did:** (a benchmark situation I created)

1. I create a repo
2. I add any file(s) using `borg create`
3. I look at the repo size on filesystem
4. I delete the archive (or, for testing, all archives) using either the archive name or `--last 1`
5. I look at the repo size on filesystem which remains the same!
6. `borg info` and `borg list` show an empty archive
7. `borg check` 
8. After deleting all archives and adding the exact same files, repo size in filesystem grows, the segment files on harddrive are not used to deduplicate the added data
9. redo, and repo size on filesystem grows continuously even if repo contains no archives

```
$ borg init --encryption=repokey benchmark4.borg
$ borg create --verbose --progress --stats --compression=none benchmark4.borg::(myDateTimeStamp) <path to backup>
$ du -ms benchmark4.borg/
1304	benchmark4.borg/
$ borg delete --debug --list --stats --last 1 benchmark4.borg
$ du -ms benchmark4.borg/
1304	benchmark4.borg/
$borg list --short --verbose --consider-checkpoints benchmark4.borg
#nothing
$ borg info --verbose benchmark4.borg
Repository ID: f4114bd37cae9a86121f7c967cf7cdf3dc2d88681367790ea091b16e31880d6a
Location: /media/user1/storage01/benchmark4.borg
Encrypted: Yes (repokey)
Cache: /home/user1/.cache/borg/f4114bd37cae9a86121f7c967cf7cdf3dc2d88681367790ea091b16e31880d6a
Security dir: /home/user1/.config/borg/security/f4114bd37cae9a86121f7c967cf7cdf3dc2d88681367790ea091b16e31880d6a
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:                    0 B                  0 B                  0 B

                       Unique chunks         Total chunks
Chunk index:                       0                    0
$ borg check benchmark4.borg --debug
using builtin fallback logging configuration
33 self tests completed in 0.08 seconds
Starting repository check
Verified integrity of /media/user1/storage01/benchmark4.borg/index.69
Read committed index of transaction 69
Segment transaction is    69
Determined transaction is 69
Found 70 segments
checking segment file /media/user1/storage01/benchmark4.borg/data/0/0...

# skipping lines

checking segment file /media/user1/storage01/benchmark4.borg/data/0/69...
finished segment check at segment 69
Starting repository index check
Index object count match.
Finished full repository check, no problems found.
Starting archive consistency check...
Verified integrity of /media/user1/storage01/benchmark4.borg/index.69
TAM-verified manifest
Archive consistency check complete, no problems found.
```
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Reproducable with 4 newly created repos with any data I threw at borg. (1st run 80GiB to backup, later only a few 100MiB to test)

**Comment by infectormp** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/delete.html#description

> Important: When deleting archives, repository disk space is not freed until you run borg compact.

**Comment by SpiritInAShell** [comment]
> https://borgbackup.readthedocs.io/en/stable/usage/delete.html#description
> 
> > Important: When deleting archives, repository disk space is not freed until you run borg compact.

This thing is a user error! **I read man borg-delete** but I did NOT NOTICE the warning! I should have! My fault. Very sorry.
