### ISSUE TITLE
Unusual use of --exclude

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#7675]
Hi

I know that I can back up the entire disk in RAW mode in two ways:
`borg create --read-special repo::hostname /dev/sda`
or
`dd if=/dev/sda bs=10M | borg create /path/to/repo::hostname`

My use case:
The disk contains two partitions, one of which is encrypted with LUKS. 
The LUKS header is at the beginning of the sda2 partition and the data segment is offset by 16777216 bytes (as seen from luksDump).
Is it possible to use the `--exclude` option to make Borg skip the header bytes?
Or another way to achieve this behavior?

Firstly, this would be ideal for keeping my data safe in the repository, because as encrypted data without header is pure random noise with no brute force capability (I will keep the header separate).
Secondly, I can then even opt out of Borg encryption and reduce CPU load.

**Comment by ThomasWaldmann** [comment]
Not sure why you would like to exclude the LUKS header. How would you restore that in case /dev/sda gets defective?

You can't use `--exclude` to exclude byte ranges of a stream, its only usage is to exclude some files based on their path names when doing a file based backup.

`dd` has some options to seek / skip, maybe that is useful if you really want that.

With dd, you need something like:
```
dd if=/dev/sda bs=10M | borg create /path/to/repo::hostname -
```
