### ISSUE TITLE
need a CVE for borg

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7677]
I recently discovered a security issue in borg and I am currently working on fixing it and related docs.

Can somebody please assist in getting one CVE assigned for that?

@LocutusOfBorg or @FelixSchwarz maybe?

Note: the last CVEs 2016/2017 were assigned by MITRE, but not sure if this is still the way to go.

**Comment by TimWolla** [comment]
> Can somebody please assist in getting one CVE assigned for that?

If you use GitHub's security advisory feature, you should be able to request a CVE from GitHub:

https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/creating-a-repository-security-advisory

**Comment by ThomasWaldmann** [comment]
@TimWolla oh, right, completely forgot about that.

@FelixSchwarz shall I get it via github or are you already in progress with the security team of fedora?

**Comment by FelixSchwarz** [comment]
I thought that @q5sys already reached out to you but if there was some mishap in the communication why not try GitHub? I'd be interested in how smooth that process goes (also in case I need a CVE in the future for my own stuff).

**Comment by ThomasWaldmann** [comment]
@q5sys Thanks for the infos. Guess I'll try github and in case that doesn't work, fall back to MITRE.

**Comment by ThomasWaldmann** [comment]
Update: started working on a security advisory, requested a CVE from github.

**Comment by q5sys** [comment]
Glad to know the process was effective and efficient!
