### ISSUE TITLE
Unable to build borgbackup on Gentoo.

### ISSUE THREAD

**Issue by slashbeast** [borgbackup/borg#769]
Hello,

I am trying to package borgbackup for Gentoo, however I am not able to build it due to sandbox violation during 'python3 setup.py build'.

    setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('/var/tmp/portage/portage/app-backup/borgbackup-1.0.0/work/borgbackup-1.0.0-python3_4/setuptools_scm.egg-info', 511) {}

**Comment by ThomasWaldmann** [comment]
Guess that is rather Python-on-Gentoo specific and hasn't much to do with borgbackup itself, so you better ask some gentoo users / packagers. BTW, IIRC there is already a package for gentoo, see issue #105.

**Comment by RonnyPfannschmidt** [comment]
FYI - you needto have the build time dependency of setuptools_scm ready to build borg from source in a sandbox

**Comment by slashbeast** [comment]
Thx, solved by setuptools_scm dependency.
