### ISSUE TITLE
recover data from a repo in 'authenticated' mode without the key/passphrase?

### ISSUE THREAD

**Issue by DrBanana419** [borgbackup/borg#7700]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

## Describe the problem you're observing.
So I have this borg archive that was created with --encryption=authenticated (or authenticated-blake2, I can't remember) and I have accessed it before, using the passphrase. But since then I've forgotten it. Now I know the data isn't actually encrypted, so how can I get to it? There's only a post on stackexchange asking this question although it did not have any answers.

**Comment by ThomasWaldmann** [comment]
Well, `borg init` tells everybody to have a backup of passphrase **and** key, so it is bad that you did not follow that.

Theoretically, the data could be recovered (as it is not encrypted), but it can not be authenticated any more (and borg would want to do that, as the repo and the chunks in it are of that type) - so guess we have no code yet to actually do that.

**Comment by ThomasWaldmann** [comment]
How important is the data in the repo?

**Comment by DrBanana419** [comment]
> How important is the data in the repo?

Actually, I _did_ remember the passphrase half an hour after making this issue, but I would still appreciate it if there were a mechanism to recover data in situations like this. If not, then it should be clearly indicated in the documentation that even when using authenticated mode, you will need to remember your passphrase to access the data. At present, the documentation is somewhat misleading.

**Comment by ThomasWaldmann** [comment]
Well, if it uses a key and asks you for the passphrase each time you use the repo, then one shouldn't assume that it also works without the passphrase (or without the key).

I read the `borg create` docs and yes, it could additionally say that you will always need key and passphrase to work with the repo, just to make that totally clear.

`borg init -e authenticated ...` already outputs **IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!** after creating a new repo.

I don't think anything is **misleading** there though, like stating something that is not true. If you think it is, can you specifically point to the place you mean?

**Comment by ThomasWaldmann** [comment]
I made some code to help in such cases, see PR #7702.

**Comment by DrBanana419** [comment]
> Well, if it uses a key and asks you for the passphrase each time you use the repo, then one shouldn't assume that it also works without the passphrase (or without the key).
> 
> I read the `borg create` docs and yes, it could additionally say that you will always need key and passphrase for encrypted as well as for authenticated repos to work with the repo, just to make that totally clear.
> 
> I don't think anything is **misleading** in the docs though, like stating something that is not true. If you think it is, can you specifically point to the place you mean?
> 
> `borg init -e authenticated ...` already outputs **IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!** after creating a new repo.

Maybe I used 'misleading' for the lack of a better word. I think the offender is 

> If you do not want to encrypt the contents of your backups, but still want to detect malicious tampering use --encryption authenticated.


Specifically the 'no encryption' part. Having no encryption means that there should be nothing to decrypt (nothing is 'locked'), so that implies that you should be able to access your data without a passphrase. Although technically English isn't my first language so maybe I'm just misunderstanding.

**Comment by ThomasWaldmann** [comment]
@DrBanana419 https://github.com/borgbackup/borg/pull/7702/files see there!

**Comment by ThomasWaldmann** [comment]
Fixed in 1.2-maint, will be in 1.2.5.
