### ISSUE TITLE
Self-hosted client-server communication results in UnexpectedRPCDataFormatFromServer error.

### ISSUE THREAD

**Issue by plundration** [borgbackup/borg#7726]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

This is a bug/issue

## System information. For client/server mode post info for both machines.

Client: 
Fedora 37, Gnome 43, Borg 1.2.4
Linux -------- 6.3.8-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 01:51:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Server: 
Fedora Server 38, Borg 1.2.4
Linux -------- 6.2.13-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 27 01:33:30 UTC 2023 x86_64 GNU/Linux

#### Your borg version (borg -V).

1.2.4

#### Operating system (distribution) and version.

Fedora 37

#### Hardware / network configuration, and filesystems used.

Local FS is btrfs and remote is ext4.

#### How much data is handled by borg?

Not important

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
❯ borg init --encryption=none ssh://user@192.168.1.108/media/backups/desktop-fedora --debug
using builtin fallback logging configuration
33 self tests completed in 0.08 seconds
SSH command line: ['ssh', 'user@192.168.1.108', 'borg', 'serve', '--debug']
Got unexpected RPC data format from server:


Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/borg/archiver.py", line 5213, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/borg/archiver.py", line 5144, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/borg/archiver.py", line 161, in wrapper
    repository = RemoteRepository(location.omit_archive(), create=create, exclusive=argument(args, exclusive),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/borg/remote.py", line 574, in __init__
    version = self.call('negotiate', {'client_data': {
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/borg/remote.py", line 711, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib64/python3.11/site-packages/borg/remote.py", line 843, in call_many
    raise UnexpectedRPCDataFormatFromServer(data)
borg.remote.UnexpectedRPCDataFormatFromServer: Got unexpected RPC data format from server:



Platform: Linux --------.-- 6.3.8-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 01:51:54 UTC 2023 x86_64
Linux: Unknown Linux  
Borg: 1.2.4  Python: CPython 3.11.4 msgpack: 1.0.4 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 38226  CWD: /home/user
sys.argv: ['/usr/bin/borg', 'init', '--encryption=none', 'ssh://user@192.168.1.108/media/backups/desktop-fedora', '--debug']
SSH_ORIGINAL_COMMAND: None

```

The data if printed is `b'\n'`.

## Describe the problem you're observing.

When I try to init a repo or backup to an existing one on my server, it doesn't work and says `Got unexpected RPC data from server: `

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I looked online and only found 5 posts about `RPC data format` errors, none of them were the same as mine. I tried `init` `create` `info`, and they all result in the same error.

I don't have another server to try this on, but I did uninstall and reinstall multiple times.

#### Include any warning/errors/backtraces from the system logs

-/-

**Comment by ThomasWaldmann** [comment]
What happens if you manually ssh to that server? Use the same user.

**Comment by plundration** [comment]
If I do it manually, it works

**Comment by plundration** [comment]
Accidentally closed this issue

**Comment by plundration** [comment]
If I do it manually, it works

**Comment by ThomasWaldmann** [comment]
I meant:
```
ssh user@192.168.1.108 borg serve
```

**Comment by plundration** [comment]
The same error

```
❯ ssh plunder@192.168.1.108 borg serve


$LOG ERROR borg.archiver Remote: Borg 1.2.4: Got unexpected RPC data format from client.
```

**Comment by plundration** [comment]
Ok I have fixed the issue, it seems to have been something to do with the ZSH P10K shell which takes time to load. The solution is to create a separate user for borg, that uses the basic bash shell.

**Comment by ThomasWaldmann** [comment]
If you manually ssh to "borg serve", that error is expected, because your input is not borg rpc format. But getting that error (and also the borg version) proves that borg serve is working on the server side.

Never had a timeout issue with that though.
