### ISSUE TITLE
borg client waiting forever to acquire the lock

### ISSUE THREAD

**Issue by jperville** [borgbackup/borg#773]
I have been experimenting with borg 1.0.0 and I am wondering how locking is supposed to work.

I have 2 computers being backed up to the same shared repository over SSH (eg. 192.168.0.1:/var/tmp/mybackup').

Each client is run like this: `borg create --lock-wait=10000 [lots of --excludes] 192.168.0.1:/var/tmp/mybackup::$(hostname)-$(date '+%Y-%m-%d_%H:%M:%S' ) /`

When I start backup at the same time on all clients, only 1 client can start the backup and the others are waiting on the lock. So far so good. But when the first client finishes its backup then I expect the next client to acquire the lock yet all stay stuck waiting on the lock!

Here is what `ps aux | grep borg` displays on the backup server:
```sh
root@backupserver:/etc# ps aux | grep borg
root     19833  0.0  0.0  93012 27412 ?        Ss   15:46   0:00 /usr/bin/python3 /usr/local/bin/borg serve --umask=077 --info
```

I have to CTRL-C the waiting clients then restart them manually; then again only the first to acquire the lock can complete, all other clients stay stuck.

Worse, the 'borg serve' processes on the server keep running, even after I CTRL-C out of the clients.

Am I doing anything wrong?

**Comment by ThomasWaldmann** [comment]
I suspect there is something else going wrong here. Try to reproduce this locally.

**Comment by jperville** [comment]
Hello @ThomasWaldmann , thanks for quickly picking up my issue.
I have reproduced locally in a fresh ubuntu 14.04 amd64 VM (without using SSH, only local filesystem).

I installed borg using the ubuntu package at `ppa:costamagnagianfranco/borgbackup`.
Version is:
```sh
root@backends-vm:~# dpkg -l | grep borgbackup
ii  borgbackup                               1.0.0-3~ubuntu14.04.1~ppa1       amd64        deduplicating and compressing backup program
```

To reproduce, I made a wrapper script with the following content:

```sh
root@backends-vm:~# cat /usr/local/bin/main-backup
#!/bin/sh

exec /usr/bin/borg create --stats --verbose --compression=lz4 --exclude-caches --lock-wait=10800 --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/var/cache --exclude=/run --exclude=/var/run --exclude=/mnt\* --exclude=/cdrom --exclude=/media --exclude=\*/tmp --exclude=/srv/ceph-osd.0 --exclude=/srv/ceph-osd.2 --exclude=/srv/ceph-osd.1 --exclude=/var/lib/docker --exclude=/ceph --exclude=/var/lib/owlim --exclude=/var/lib/mongodb --exclude=/var/lib/redis --exclude=/var/lib/rabbitmq --exclude=/vagrant /var/backups/borg::$( date '+vagrant-c19ea810-Main_%Y-%m-%d_%H:%M:%S' ) /
```

The repository at /var/backups/borg has been manually created earlier with the following command-line: `borg create --encryption=none /var/backups/borg`.

Then I start a "screen" session and run the backup of the whole system using my wrapper script.
Then detach the screen (or use another terminal) and run the wrapper script again before the first copy is finished.

At some point the first copy finishes successfully but the second copy never starts.

If I look at the processes running after the first execution has completed successfully:

```
root@backends-vm:~# ps aux | grep borg
root     21765  0.0  0.7 100940 28540 pts/6    S+   19:11   0:00 /usr/bin/python3 /usr/bin/borg create --stats --verbose --compression=lz4 --exclude-caches --lock-wait=10800 --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/var/cache --exclude=/run --exclude=/var/run --exclude=/mnt* --exclude=/cdrom --exclude=/media --exclude=*/tmp --exclude=/srv/ceph-osd.0 --exclude=/srv/ceph-osd.2 --exclude=/srv/ceph-osd.1 --exclude=/var/lib/docker --exclude=/ceph --exclude=/var/lib/owlim --exclude=/var/lib/mongodb --exclude=/var/lib/redis --exclude=/var/lib/rabbitmq --exclude=/vagrant /var/backups/borg::vagrant-c19ea810-Main_2016-03-19_19:11:22 /
```

If I look at the internal data of borg repository:
```sh
root@backends-vm:~# ls -l /var/backups/borg/
total 5144
-rw------- 1 root root     148 Mar 18 14:57 config
drwx------ 3 root root    4096 Mar 18 14:57 data
-rw------- 1 root root     912 Mar 19 19:13 hints.278
-rw------- 1 root root 5244058 Mar 19 19:13 index.278
-rw------- 1 root root      31 Mar 19 19:13 lock.roster
-rw------- 1 root root      26 Mar 18 14:57 README
```

No trace of a lock left.

I can also mount the borg repository using fuse, and it won't complain about the repository being locked. Meanwhile my second instance is still trying to acquire the lock...

**Comment by jperville** [comment]
When I ctrl-c the second instance (the one waiting forever for lock) I have the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 133, in acquire
    os.mkdir(self.path)
FileExistsError: [Errno 17] File exists: '/var/backups/borg/lock.exclusive'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1466, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1420, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 207, in do_create
    repository = self.open_repository(args, exclusive=True)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 67, in open_repository
    repository = Repository(location.path, create=create, exclusive=exclusive, lock_wait=self.lock_wait, lock=lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 64, in __init__
    self.open(self.path, exclusive, lock_wait=lock_wait, lock=lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 142, in open
    self.lock = UpgradableLock(os.path.join(path, 'lock'), exclusive, timeout=lock_wait).acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 257, in acquire
    self._wait_for_readers_finishing(remove, sleep)
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 270, in _wait_for_readers_finishing
    self._lock.acquire()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 137, in acquire
    if timer.timed_out_or_sleep():
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 72, in timed_out_or_sleep
    self.sleep()
  File "/usr/lib/python3/dist-packages/borg/locking.py", line 63, in sleep
    time.sleep(self.sleep_interval)
KeyboardInterrupt

Platform: Linux backends-vm 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64
Linux: Ubuntu 14.04 trusty  LibC: glibc 2.9
Borg: 1.0.0  Python: CPython 3.4.0
PID: 21765  CWD: /usr/local/bin
sys.argv: ['/usr/bin/borg', 'create', '--stats', '--verbose', '--compression=lz4', '--exclude-caches', '--lock-wait=10800', '--exclude=/proc', '--exclude=/sys', '--exclude=/dev', '--exclude=/var/cache', '--exclude=/run', '--exclude=/var/run', '--exclude=/mnt*', '--exclude=/cdrom', '--exclude=/media', '--exclude=*/tmp', '--exclude=/srv/ceph-osd.0', '--exclude=/srv/ceph-osd.2', '--exclude=/srv/ceph-osd.1', '--exclude=/var/lib/docker', '--exclude=/ceph', '--exclude=/var/lib/owlim', '--exclude=/var/lib/mongodb', '--exclude=/var/lib/redis', '--exclude=/var/lib/rabbitmq', '--exclude=/vagrant', '/var/backups/borg::vagrant-c19ea810-Main_2016-03-19_19:11:22', '/']
SSH_ORIGINAL_COMMAND: None

^C
```

The lock file from the stacktrace does not actually exist:

```sh
root@backends-vm:/usr/local/bin# ls -l /var/backups/borg/lock.exclusive
ls: cannot access /var/backups/borg/lock.exclusive: No such file or directory
```

**Comment by ThomasWaldmann** [comment]
Guess the stacktrace is misleading. At the time when the FileExistsError occurred, the lock dir really existed. In the exception handler (for file exists == lock dir exists), there is a sleep - which you interrupted with Ctrl-C (when the lock dir was already gone).

From the code:
```
 sleep = timeout / 10.0
```

Likely that was not the best idea in general.
For your timeout time of 10.000 s, this means a sleep time of 1000s.

So, likely it is not stuck, you'ld just need to observe it for ~1000s.

**Comment by jperville** [comment]
Hi @ThomasWaldmann , actually I just found that myself and tried with a lock-wait of 300 (which means checking every 30 seconds) and indeed it worked.

Would it be possible to add a command-line option to specify the sleep interval, because I plan to have like a dozen clients backup to the same repository and at the start the backup may take a while, and I would like every clients to get their chance without some waiting for hours then giving up because they have exhausted their 10 tries.

**Comment by ThomasWaldmann** [comment]
I guess I rather change the code, so it'll use 10%, but not longer than a minute.

**Comment by jperville** [comment]
That would be even better, or if something like libnotify is available we could be immediately notified when the lock is released on the filesystem.

**Comment by jperville** [comment]
Cheers :)
