### ISSUE TITLE
Which file permissions are necessary to use borg as non privileged user?

### ISSUE THREAD

**Issue by pcuinty** [borgbackup/borg#774]
Since I only want to backup files from my home directory, I'd like to set up a repository and back up files as a non privileged user. As a novice: Which file permissions do I need to set up?

Right now, I get the following error when trying to `borg init repo`

    PermissionError: [Errno 13] Permission denied: '/home/user/.cache/borg/4c9fc8bb...'

Thanks for your help

**Comment by enkore** [comment]
None.

This looks like .cache or .cache/borg became somehow not writeable for you. Did you create either directory as root?

**Comment by pcuinty** [comment]
surprisingly this is really the case, `.cache/borg` has root as owner. I installed borg via ppa (ppa:costamagnagianfranco/borgbackup)  on ubuntu 15.10 (via `sudo apt-get`). Maybe changing default ownership in the future?

Anyway, now it works like charm, thank you so much.

**Comment by ThomasWaldmann** [comment]
$HOME/.cache/borg is created when you first run borg.

likely you ran borg once under uid root, but HOME was still pointing to your home dir.
