### ISSUE TITLE
tests missing for FreeBSD acl code

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7745]
borg has some platform specific code for ACLs on FreeBSD, but looks like there are no tests for that code (we only have ACL tests for Linux and macOS (darwin)).

**Comment by bigtedde** [comment]
Dummy file created for these tests. Find [here](https://github.com/borgbackup/borg/pull/7748).

**Comment by ThomasWaldmann** [comment]
the freebsd64 vagrant machines needs "acls" option in /etc/fstab.
