### ISSUE TITLE
does borg really not support incremental backups to existing repo ?

### ISSUE THREAD

**Issue by commandline-be** [borgbackup/borg#7747]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## System information. For client/server mode post info for both machines.

any OS

#### Your borg version (borg -V).

1.1.18

#### Operating system (distribution) and version.

Linux 5.14

## Describe the problem you're observing.

I fail to understand how to update the backup for a host make to a dedicated repo and only update changed files.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

YES, running borg create on an existing repo

#### Include any warning/errors/backtraces from the system logs

Archive mybackup already exists

**Comment by RonnyPfannschmidt** [comment]
Dedup has the same space saving effects without the chain catastrophic effects

It's fair to say that effective dedup makes incremental unnecessary

**Comment by infectormp** [comment]
> I fail to understand how to update the backup for a host make to a dedicated repo and only update changed files.
Just run borg again

**Comment by ThomasWaldmann** [comment]
@commandline-be just as a general hint: you may want to append the timestamp to the backup name (because backup names need to be unique), see the docs.

**Comment by ThomasWaldmann** [comment]
guess this is answered.
