### ISSUE TITLE
--exclude does not work if path have more than single slash separating dirs

### ISSUE THREAD

**Issue by slashbeast** [borgbackup/borg#775]
Hello,

It seems that '-e //usr/share/doc' for backing up /usr/share won't work, it won't excude this dir. Replacing '//usr/share/doc' with '/./usr/share/doc' gets the job done.

When writting simple shell scripts which utilize borg it's rather easy to concatenate two variables, which may result in having multiple slashes instead of one and one could expect that it won't be a problem.

**Comment by ThomasWaldmann** [comment]
your pathes look broken. if your script does not produce correct pathes, fix your script.

**Comment by slashbeast** [comment]
The paths are *correct*.

I had a script to backup rootfs (the /) and then a list of excludes like:

    ${path_to_backup}/tmp
    ${path_to_backup}/var/tmp

And so on. In case of 'path_to_backup="/"' it won't work. As a workaround I used '${path_to_backup/./tmp' and it worked.

The "//". "/./" and "/" are supposed to work the same and works in everything else, beside borgbackup.

**Comment by enkore** [comment]
He has a point, normally any number of consecutive slashes just collapse into one, and most applications handle that as expected. When building patterns it would be a good idea to use os.path.normpath to handle these cases imho.

**Comment by enkore** [comment]
This wouldn't help in your case, though. I didn't notice that your path started with //, and @ThomasWaldmann is absolutely right that specifically those are broken (implementation defined).

```
>>> import os.path
>>> os.path.normpath("//asdf")
'//asdf'
>>> os.path.normpath("///asdf")
'/asdf'
```
