### ISSUE TITLE
How to get rid of "Using a pure-python msgpack!"

### ISSUE THREAD

**Issue by trendymail** [borgbackup/borg#7760]
Hello from France!

First, I just want to say "Thank you!". :)

I discovered Borg 10/15 days ago, ran some tests and results were just so impressive.

1) Thanks for the documation: very clear, useful and compact.

2) Thanks for the Github repository: I do not understand Python source code but it allows me to browse the code to find an error message.

3) Thanks for maintaning Github issues: I really have searched before submiting this question.

So, if my question is a duplicate, feel free to delete it.

## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes, but I could have missed some useful infos.

## Is this a BUG / ISSUE report or a QUESTION?

Just a question.

#### Your borg version (borg -V).

borg-linuxold64 1.2.4 (big fat binary)

#### Operating system (distribution) and version.

OpenVZ 7 (aka: Virtuozzo 7)

# ldd --version
ldd (GNU libc) 2.17

AFAIK, this version of OpenVZ 7 will remain the same for many years.

#### Hardware / network configuration, and filesystems used.

Dedicated servers, default network, EXT4.

## Describe the problem you're observing.

Borg (bit fat binaries) do not use latest "pure-python msgpack".

I really do not know if this is possible to statically link latest Python version within these binaries.

However, if these "fat binaries" would take more than 10 seconds to run (with Python inside), I really do not care.

Borg is so "competitive" that this extra delay is not (at all) a problem.

Have a great day!

**Comment by RonnyPfannschmidt** [comment]
The question is not quite clear

Borg picks specific msgpack versions with c speedups to ensure backup performance and consistency

The fat binaries do create some delay but for a typical backup run that is irrelevant as it buy's ease of deployment for user convenience 

I vaguely recall the unpacking can be cached 

In cases where it actually matters classical installation would resolve that

**Comment by ThomasWaldmann** [comment]
From the issue title, I suspect the problem is that borg emits that "Using pure-python msgpack!" warning in that setup (so it is operating slower than it normally would).

**Comment by trendymail** [comment]
Hello!

@RonnyPfannschmidt: sorry, I agree with you, my question was not very clear (I am new to Borg... ^^).

@ThomasWaldmann: thanks for your detailed answer, it is now way more clearer to me (libc dependency).

Here is the "upgraded" question:

Using git repo (v1.2.4), is it possible to compile Borg and statically link the C library ? (ex: Debian 11/12 => glibc 2.31/2.36)

I have read that it could have various side effects.

https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged

If Borg does not use dlopen(3) to load NSS or iConv, it should be fine.

Please, tell me if statically linking glic is acceptable to you or if it just the most direct path to disaster... ^^

I do not care (yet) if Borg could randomly crash with solution: current tests are still in progress.

Have a great day! :)

**Comment by trendymail** [comment]
Understood!

So, last question: how long do you will provide "fat" binaries builded with Debian 9 "Strech"?

I am impatient to use Borg 2! ^^

Please, feel free to close this issue. :)

**Comment by ThomasWaldmann** [comment]
Until someone fixes #7579, there won't be stretch-built binaries.
