### ISSUE TITLE
using borg with sudo

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#7761]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug / Queststion (?)

## System information. For client/server mode post info for both machines.
LMDE 5 (Linux Mint Debian Edition = Debian 11)

#### Your borg version (borg -V).
1.2.4 (binary downloaded from github to /usr/local/bin/ because there is only 1.2.3 in the Bullseye repository)

## Describe the problem you're observing.

Sorry if this isn't a Borg bug, just a lack of my skills....

I added two environment variables to ~/.bashrc (I also tried in /etc/environment):
```
export BORG_BASE_DIR='/home/mint/Desktop/test-borg-config'
export BORG_PASSCOMMAND='cat /home/mint/Desktop/test-borg-config/test-borg-pass'
```
They are correctly detected:
```
mint@mint:~$ export
declare -x BORG_BASE_DIR="/home/mint/Desktop/test-borg-config"
declare -x BORG_PASSCOMMAND="cat /home/mint/Desktop/test-borg-config/test-borg-pass"
```
I initialized the repository correctly:
```
mint@mint:~$ borg init --encryption=keyfile-blake2 --show-version --progress --debug -v /home/mint/Desktop/test-borg-repo
```
I created the archive correctly:
```
mint@mint:~$ borg create --list --stats --progress -v --show-version --compression zstd /home/mint/Desktop/test-borg-repo::test-{now} /home/mint/Desktop/test-borg-example-data
```
But if I execute the command as `sudo` I get an error: `No key file for repository /home/mint/Desktop/test-borg-repo found in /root/.config/borg/keys`
(I need `sudo` to be able to backup the /dev/sda block device along with `--read-special`)

```
mint@mint:~$ sudo borg create --list --stats --progress -v --debug --show-version --compression zstd /home/mint/Desktop/test-borg-repo::test-{now} /home/mint/Desktop/test-borg-example-data
using builtin fallback logging configuration
borgbackup version 1.2.4
33 self tests completed in 0.11 seconds
Verified integrity of /home/mint/Desktop/test-borg-repo/index.9
No key file for repository /home/mint/Desktop/test-borg-repo found in /root/.config/borg/keys.
Traceback (most recent call last):
  File "borg/archiver.py", line 5213, in main
  File "borg/archiver.py", line 5144, in run
  File "borg/archiver.py", line 170, in wrapper
  File "borg/helpers/manifest.py", line 187, in load
  File "borg/crypto/key.py", line 134, in key_factory
  File "borg/crypto/key.py", line 585, in detect
  File "borg/crypto/key.py", line 723, in find_key
borg.crypto.key.KeyfileNotFoundError: No key file for repository /home/mint/Desktop/test-borg-repo found in /root/.config/borg/keys.

Platform: Linux mint 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64
Linux: Unknown Linux  
Borg: 1.2.4  Python: CPython 3.9.16 msgpack: 1.0.5 fuse: llfuse 1.4.2 [pyfuse3,llfuse]
PID: 3682  CWD: /home/mint
sys.argv: ['borg', 'create', '--list', '--stats', '--progress', '-v', '--debug', '--show-version', '--compression', 'zstd', '/home/mint/Desktop/test-borg-repo::test-{now}', '/home/mint/Desktop/test-borg-example-data']
SSH_ORIGINAL_COMMAND: None
```
However, if I add these variables to the command line it works fine:
```
mint@mint:~$ sudo BORG_BASE_DIR='/home/mint/Desktop/test-borg-config' BORG_PASSCOMMAND='cat /home/mint/Desktop/test-borg-config/test-borg-pass' borg create --list --stats --progress -v --show-version --compression zstd /home/mint/Desktop/test-borg-repo::test-{now} /home/mint/Desktop/test-borg-example-data
```
Could this be a Borg bug? Or am I the stupid one?

**Comment by ThomasWaldmann** [comment]
It's because `sudo` does not just "pass through" the environment variables, check its docs.

**Comment by ThomasWaldmann** [comment]
1. no, as it is done by sudo.
2. idk
3. idk

I usually always run borg as the same user:
- either as normal user (e.g. to backup just the files of that user)
- or as root (**not** using sudo) to backup files of all users and/or system files

**Comment by jdchristensen** [comment]
I don't think you should use `sudo -E`, as it may pass through things you don't expect.  Instead, set the variables *as the root user, either using `sudo VAR1=value VAR2=value command`, or by putting the variables and command(s) in a script, and running the whole script with `sudo`.

BTW, you should also be able to get a root shell with `sudo -i`.

**Comment by RonnyPfannschmidt** [comment]
I'm under the impression this issue Will have to be closed as "borg won't recommend insecure/error prone"practices
