### ISSUE TITLE
Could borg be used for windows system drive image backup?

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [borgbackup/borg#7762]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Operating system (distribution) and version.

windows 11

#### How much data is handled by borg?

100GB

## Describe the problem you're observing.

Looking for windows system hot backup solution

**Comment by RonnyPfannschmidt** [comment]
It's not clear what you mean by hot backup in your particular Case

**Comment by LakeishaKowalczyk** [comment]
> It's not clear what you mean by hot backup in your particular Case

Backup the C:\ into an image file (e.g. `.wim` ) while windows is running
So I can use it to restore windows when the system is corrupted (e.g. via a PE system on a USB flash drive)

**Comment by RonnyPfannschmidt** [comment]
Borg does not deal with creating disk Images itself,your backup strategy is still unclear

**Comment by ThomasWaldmann** [comment]
For what you want, there is software like macrium reflect.

With borg, you can backup files (and anything assuring consistency, like snapshotting) needs to be done externally.

**Comment by LakeishaKowalczyk** [comment]
> For what you want, there is software like macrium reflect.
> 
> With borg, you can backup files (and anything assuring consistency, like snapshotting) needs to be done externally.

Thank you, I prefer to use programs that is open source and preferably portable.
Do you have any recommendations?

**Comment by infectormp** [comment]
Look at UrBackup

**Comment by ThomasWaldmann** [comment]
Guess this is solved.
