### ISSUE TITLE
Emergency recovery

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#7763]
## Is this a BUG / ISSUE report or a QUESTION?
Question

I use keyfile mode and I have a copy of the keyfile + SSH key in a safe separate place outside the computer.

Let's assume an extreme case of data loss - laptop theft, fire, etc...

Is it enough to have a keyfile + SSH key + password to recover a backup from the repository to a new computer (which I have on a separate medium that I haven't lost)?
So without all Borg configuration files (cache, nonces, etc)....
Should I have anything else in a separate location?

**Comment by ThomasWaldmann** [comment]
Sounds good (I assume you mean the borg key passphrase with "password").
Of course you might need the passphrase for the ssh key also.

Instead of copying the borg key, you can also use `borg key export` - it has some output formats that might be better if you want to keep something on paper.
