### ISSUE TITLE
Question about --stdout and --content-from-command

### ISSUE THREAD

**Issue by git70** [borgbackup/borg#7764]
## Is this a BUG / ISSUE report or a QUESTION?
Question

I use according to the documentation [here](https://borgbackup.readthedocs.io/en/stable/usage/create.html?highlight=raw#examples) and [here](https://borgbackup.readthedocs.io/en/stable/usage/extract.html?highlight=raw#examples):
`borg create --read-special --chunker-params fixed,4194304 /path/to/repo::my-sdx /dev/sdX`
and
`borg extract --stdout /path/to/repo::my-sdx | dd of=/dev/sdx bs=10M`

But [here](https://borgbackup.readthedocs.io/en/stable/usage/create.html#reading-from-stdin) he writes about command pipelining issues

Questions:
1. Does the problem with the potential pipe failure from Borg to dd also apply to the `borg extract` operation (i.e. dd will not notice the Borg failure and will continue)?
2. Does the `--content-from-command` option also apply to the `borg extract` operation and can it help?

**Comment by ThomasWaldmann** [comment]
1. i think so, yes.
2. no, in the extract case, `dd` (not: `borg`) would have to offer such an option to notice that its input is incorrect (usually too short) due to an error in borg.

But besides that, there likely would be also some error msgs on stderr.

**Comment by ThomasWaldmann** [comment]
Yes, if something goes wrong at `borg extract`, you'll get an error msg on stderr and borg will terminate with rc != 0.
