### ISSUE TITLE
Failed to create/acquire the lock: question

### ISSUE THREAD

**Issue by jacob-issac** [borgbackup/borg#7786]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes.

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
Linux Mint Cinamon

#### How much data is handled by borg?
12 GB

## Describe the problem you're observing.
- Something happened with my mount location, it had to do with FAT, so i reformated by USB to exFAT and copied the borg backup repo
- Now I see this 

```
Failed to create/acquire the lock /mnt/pb/bb/mv/lock.exclusive ([Errno 13] Permission denied: '/mnt/pb/bb/mv/lock.exclusive.lnntxi44.tmp').
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5089, in main
    exit_code = archiver.run(args)
```

- I tried borg break-lock path/to/repo
- I tried `rm -rf /home/j/.cache/borg/`
- still the same problem

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes. Just creating backups.

**Comment by ThomasWaldmann** [comment]
```
[Errno 13] Permission denied: '/mnt/pb/bb/mv/lock.exclusive.lnntxi44.tmp'
```

Can you check the permissions there?

Is there a special reason why you want to use FAT / exFAT? These are likely the worst filesystems out there.

**Comment by jacob-issac** [comment]
I don't know better. Which filesystem do you recommend?

And when I run `ls -ld /mnt/pb/bb/mv`

I get `drwxr-xr-x 3 root root 32768 Aug 28 11:00 /mnt/pb/bb/mv`

**Comment by ThomasWaldmann** [comment]
The usual fs for linux external disks is ext4.

**Comment by jacob-issac** [comment]
Thank you! Changing fs to ext4 fixed the problem.
