### ISSUE TITLE
is CACHEDIR.TAG file case sensitive ?

### ISSUE THREAD

**Issue by andreagrax** [borgbackup/borg#7799]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

question

#### Your borg version (borg -V).
borg 1.2.2
#### Operating system (distribution) and version.
ubuntu 22.04

#### Hardware / network configuration, and filesystems used.
i7 laptop, ext4 + LVM fs
#### How much data is handled by borg?
about 10 GB
## Describe the problem you're observing.

CAHCEDIR.TAG filename is case sensitive ? I did't find anything in the docs

**Comment by ThomasWaldmann** [comment]
If you use a case-sensitive filesystem (like usual on linux), yes, it must be precisely "CACHEDIR.TAG".

If the file is located on a case-insensitive fs (like fat or ntfs), I guess it would be also found with other casing.
