### ISSUE TITLE
EuroPython 2016 Sprint and LT

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#780]
Sprints on borg are at Saturday and Sunday (Room Axular at the sprints site).

Useful Links:
- development docs: http://borgbackup.readthedocs.io/en/latest/development.html
- if something is missing in the docs: ask Thomas Waldmann, contribute a docs pull request
- easy tickets: https://github.com/borgbackup/borg/labels/easy
- wiki page on EP wiki: https://wiki.python.org/moin/EuroPython2016/Sprints

There was a Lightning Talk about borg at EuroPython (see conference recordings, after they are available).

**Comment by blueyed** [comment]
I'm interested in borg and the sprint in general.  I am not using it currently, but would like to try it instead of / besides bup.

**Comment by ThomasWaldmann** [comment]
@blueyed thanks for considering joining the sprints. While I of course could show borg to you there, I guess it is more productive if you try it beforehands and maybe have some looks into the code also, so we can concentrate on coding (or coding related questions) in the sprint rather than usage of borg.

**Comment by ThomasWaldmann** [comment]
Other borg users at europython who would like to join the borg sprint?

**Comment by ThomasWaldmann** [comment]
Note: we have some issues tagged "easy" - maybe use them if you are a new contributor. Also, please read the docs, they answer all your questions about installing borg and also many development related questions. 

If something is missing in the docs: find out and contribute that.

**Comment by ThomasWaldmann** [comment]
https://youtu.be/LJ2zRHociVw?t=25m30s borgbackup lightning talk
