### ISSUE TITLE
`borg list --format` breaks with `Invalid placeholder` if spaces are in the string

### ISSUE THREAD

**Issue by olifre** [borgbackup/borg#7815]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).
`borg 1.2.6`

#### Operating system (distribution) and version.
Gentoo Linux

#### Hardware / network configuration, and filesystems used.
BTRFS at backup source, EXT4 at backup target, GBit/s network

#### How much data is handled by borg?
~500 GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
BORG_WORKAROUNDS=ignore_invalid_archive_tam borg list --format='{name} {time} tam:{tam}{NL}' backup-target-host:backup-target-dir/backup-repo-name
```
(i.e. the command from the upgrade guidelines)

## Describe the problem you're observing.
```
Invalid placeholder "time" in string: {time}
```
Dropping `{time}` reveals;
```
Invalid placeholder "tam" in string: tam:{tam}{NL}
```
Replacing all spaces with underscores in the strings makes things work, i.e. I have to use:
```
--format='{name}_{time}_tam:{tam}{NL}'
```

I am not sure whether this is just a documentation issue (i.e. the documentation should use something which is not a space there) or an actual bug. 
In any case, the error message "Invalid placeholder" also seems quite misleading, since the placeholder is actually well-supported.

**Comment by ThomasWaldmann** [comment]
I tested all the commands from the upgrade docs by copy&pasting them from the raw text file to a shell (IIRC zsh on macOS), so they should work "as is".

Maybe there is some problem with your shell? Or did you copy and paste from rendered html and we have some different quotes there leading to malfunction?

**Comment by olifre** [comment]
You are correct, this is my bad: The shell is not (directly) at fault, and neither is the environment. 

However, I've been using a `borgwrapper` shell script, which sets my `BORG_PASSPHRASE` and finally calls:
```
/usr/bin/borg $@
```
Silly me forgot the quotes, i.e.:
```
/usr/bin/borg "$@"
```
This led to the actual `/usr/bin/borg` seeing these arguments separately, and caused the error. 

Sorry for the noise — I hope this explanation may help others doing a similar beginner mistake :wink:. 
And thanks for maintaining this brilliant and reliable tool!
