### ISSUE TITLE
Check borg --version on remote 

### ISSUE THREAD

**Issue by goebbe** [borgbackup/borg#7829]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
YES - I hope I didn't miss the relevant information.

## Is this a BUG / ISSUE report or a QUESTION?
Question

## System information. For client/server mode, post info for both machines.
client: Linux Mint 21.2
server: synology NAS

#### Your borg version (borg -V).
client: 1.2.4
server: 1.2.6 

## Describe the problem you're observing.
Using a shell script to run daily backup, I thought that providing the borg --version for client and remote could be useful information for my logs. 

To get the version of the client, the following command did the job:
`borg --version  `

Now, I (wrongly?) tried the following to get the version of the remote backup server:  
`borg --version --remote-path='/usr/local/bin/borg' ssh://admin@192.168.0.5 \   `

I expected to get the borg version on the remote computer, here. 
However, this did not work, instead, somewhat unexpected (to me :-) )  the version of the client is reported, again.

In order to get the remote borg version, instead, I used the following command:
`ssh admin@192.168.0.5 /usr/local/bin/borg --version`
i.e. ssh into the server and execute borg --version there. 

Here is my question: 
Is there a way to get the remote borg-version, using the borg syntax? Did I miss something? 

I believe it would be convenient, to get the remote borg version, when a remote server (ssh://...) is provided at the same time.

**Comment by ThomasWaldmann** [comment]
Good idea, that is not implemented yet.

Internally, borg client and server exchange some version information, but there is no special borg command to display the remote borg version.

**Comment by ThomasWaldmann** [comment]
I implemented an additional `borg version <REPO>` command, that displays borg client and server version.

**Comment by ThomasWaldmann** [comment]
Fixed in 1.4-maint.
