### ISSUE TITLE
Unbelievable Deduplication

### ISSUE THREAD

**Issue by stevesbrain** [borgbackup/borg#7833]
Hi all,

I've got a repository that I keep some of my most personal stuff in. I back this repository up regularly, and on one of the days I added some content to it, I noted that the size of the repository changed less than 1MB, despite adding ~100MB of new files which were all pictures/videos that had never existed until that day.

I struggle to believe that, on a repository of predominantly images + videos, there would be enough blocks already in the repository to de duplicate any of these files, let alone all of them on the same day. 

I have done a diff and info on these repositories, to show you what I mean (trimmed list of files, but gives you an idea):

### Diff showing that files were added
```
root@Borg:~ # borg diff ssh://user@host/./borg-backup::Borg-2023-09-15T05:00:13.038821 Borg-2023-09-16T00:00:01.864817
added     204.77 kB path/to/files/IMG_3748.JPG
added      19.34 MB path/to/files/NjI2MUI5OEItMDYzMi00RUU1LUE1QTQtMDVBMjQxQzZGM0M1.MOV
added     270.57 kB path/to/files/IMG_3749.JPG
added     315.56 kB path/to/files/IMG_3740.JPG                 
added       2.94 MB path/to/files/RjM4Mzk2MTItQTZBRC00NTJELTg0NDQtMjJDQzY5OTNCRTI1.MOV
added       4.11 MB path/to/files/RDBGNzhDMzUtNENDNi00QjY0LThGRUEtQ0M3RUIyQjZGNDc4.MOV
added       5.75 MB path/to/files/OTA5MDc2NjMtREQ4OC00NzU1LTk5RjMtOTk0Q0MyNDk0RDlD.MOV
added     288.10 kB path/to/files/IMG_3760.JPG
added     435.21 kB path/to/files/IMG_3758.JPG
added     582.69 kB path/to/files/IMG_3764.JPG
added     407.99 kB path/to/files/IMG_3765.JPG
added     363.10 kB path/to/files/IMG_3759.JPG
added     126.70 kB path/to/files/IMG_3738.JPG
added      43.14 MB path/to/files/RUY3QjVBNjAtNzQ1NS00MjZDLTgwMDEtQ0QzNENFMTgyOUEz.MOV
```

### Archive Info showing that files were also added, but that size was deduped 
```
Archive name: Borg-2023-09-15T05:00:13.038821                                                                      [40/1957]
Archive fingerprint: FINGERPRINT                                       
Comment:                                                                                                                    
Hostname: Borg                                                                                                              
Username: root                                                                                                              
Time (start): Fri, 2023-09-15 05:00:24
Time (end): Fri, 2023-09-15 05:11:03
Duration: 10 minutes 38.63 seconds    
Number of files: *486695*                                       
Command line: /usr/local/bin/borg create —exclude-if-present .nobackup ‘ssh://user@host/./borg-backup::{ho
stname}-{now:%Y-%m-%dT%H:%M:%S.%f}’ /path/to/files —info
Utilization of maximum supported archive size: 0%                                                                           
——————————————————————————                                          
                       Original size      Compressed size    Deduplicated size
This archive:              633.51 GB            624.59 GB             45.81 kB
All archives:               24.82 TB             24.44 TB            632.62 GB
                                                                                                                            
                       Unique chunks         Total chunks                                                                   
Chunk index:                  670847             27879490
```

```                                                           
Archive name: Borg-2023-09-16T00:00:01.864817            
Archive fingerprint: FINGERPRINT
Comment:                 
Hostname: Borg                                                                                                              
Username: root
Time (start): Sat, 2023-09-16 00:00:11
Time (end): Sat, 2023-09-16 00:14:44
Duration: 14 minutes 33.60 seconds    
Number of files: *486748*                                       
Command line: /usr/local/bin/borg create —exclude-if-present .nobackup ‘ssh://user@host/./borg-backup::{ho
stname}-{now:%Y-%m-%dT%H:%M:%S.%f}’ /path/to/files —info
Utilization of maximum supported archive size: 0%                                                                           
——————————————————————————
                       Original size      Compressed size    Deduplicated size
This archive:              633.60 GB            624.68 GB             45.70 kB
All archives:               24.82 TB             24.44 TB            632.62 GB
                                                                                                                            
                       Unique chunks         Total chunks                                                                   
Chunk index:                  670847             27879490
```

I've verified of course that the files do indeed exist in the backup, and can be restored. Is there any other sort of weirdness going on here that you think I should verify, or, do you think this is just an extremely unlikely scenario where unique files that have previously existed are, somehow, deduplicated? Thanks

**Comment by ThomasWaldmann** [comment]
Hmm, if these pictures/movies did not exist in the repo before (like e.g. because they were newly created right before), that's indeed strange.

Can you check whether there is another backup between these 2, that also has these files? That would be the easiest explanation.

**Comment by stevesbrain** [comment]
Thanks for the response - and yeah they did not exist in the repo before, or in fact even in "the world" as such (pictures/videos that were taken that day so should be unique in every sense of the word). 

I have double checked, and these are indeed snapshots that are one after the other, so there is no backup between these two (and the diff should help support that, as well) :)

**Comment by ThomasWaldmann** [comment]
Is there a backup **after** the 2nd shown one that also has these files?

**Comment by stevesbrain** [comment]
Yeah, they are maintained/still in the repo after the next backup

**Comment by ThomasWaldmann** [comment]
OK, if you already have multiple backups of the new files, that explains what you see.

The deduplicated size shown for an archive is always the size of the unique chunks **only** in that single archive.

If you add a set of new and unique files of size S at time T, borg info of that archive will show approx. S as deduplicated size. But if you do another backup at time T+x that also has these files, they will not be unique any more when doing borg info, because they now have 2 references.

**Comment by stevesbrain** [comment]
Okay awesome, thanks for explaining that! I have a separate issue I'll have to sort out then - why they didn't show up in the backup in the first place despite being on disk, then subsequently did in a following backup (which is what lead me to diff'ing the snapshots in the first place. But at least that means this one can be closed for now - appreciate it, thanks :)
