### ISSUE TITLE
ValueError when calling borg

### ISSUE THREAD

**Issue by jersonal-com** [borgbackup/borg#7838]
After working for quite some time without any issues yesterday borg stopped working on a raspberry pi server. 

When logging on the server directly it doesn't even show the version of borg but stops with an error.  I did neither run a backup nor installed and kind of new software over the course of the last weeks before the error happened. 

## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE

#### Your borg version (borg -V).

borgbackup/testing,now 1.2.4-1 armhf [installed]

borg -V throws an error - see above

Version is from:
deb http://raspbian.raspberrypi.org/raspbian/ testing main contrib non-free rpi

#### Operating system (distribution) and version.

Raspbian GNU/Linux 11 (bullseye)

#### Hardware / network configuration, and filesystems used.

Filesystem on USB; ext4; error raises without accessing the file system

#### How much data is handled by borg?

2.3TB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`borg -V`

or

`borg --help`

## Describe the problem you're observing.

The above command leads to the following output:

```
$ borg -V
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 12, in <module>
    import inspect
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
```

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Happens every time when entering any kind of borg command. 

#### Include any warning/errors/backtraces from the system logs

No errors in the system log.

**Comment by RonnyPfannschmidt** [comment]
This looks like a broken python installation

**Comment by ThomasWaldmann** [comment]
Somehow it tries to compile py -> pyc, but fails to do so.

**Comment by ThomasWaldmann** [comment]
So maybe try:
- removing and reinstalling borg (usually it also compiles bytescode then)
- if that also fails, try reinstalling python.

Maybe also check, if the storage your OS is installed on works correctly, sometimes SDcards die...

**Comment by jersonal-com** [comment]
I removed and re-installed borg:

``` $ sudo apt purge borgbackup
$ sudo apt -t testing install borgbackup
$ borg -V
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 12, in <module>
    import inspect
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
```
Would it make sense to remove the compiled bytecode manually? If so - where are these files located?

**Comment by ThomasWaldmann** [comment]
The `inspect` module it tries to import (and fails) is part of your python installation.

I'ld try something like:
```
sudo apt-get install --reinstall python3.9  # check your python version first
```

**Comment by jersonal-com** [comment]
I reinstalled python and also tried to remove the cache with 
```
$ sudo mv /usr/lib/python3/dist-packages/__pycache__ /usr/lib/python3/dist-packages/__pycache__.old
```
A check for badblocks on the SD card showed no issue there:

```
$ sudo badblocks -sv /dev/mmcblk0p2 
Checking blocks 0 to 14893055
Checking for bad blocks (read-only test):   0.00% done, 0:00 elapsed. (0/0/0 errors)
done                                                 
Pass completed, 0 bad blocks found. (0/0/0 errors)
```
I would appreciate any other ideas on how to fix this...

**Comment by jersonal-com** [comment]
It seems that 

```
$ sudo rm /usr/lib/python3.11/__pycache__/*.pyc
```

did the trick. Thanks a lot for your help!
