### ISSUE TITLE
List all Borg repos from a remote server (without SSH access)

### ISSUE THREAD

**Issue by trendymail** [borgbackup/borg#7849]
Hello! 

## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes. Documentation is incredible!

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.2.6

#### Operating system (distribution) and version.

OpenVZ aka Virtuozzo 7 (using binary "borg-linuxold64")

#### Hardware / network configuration, and filesystems used.

Dedicated servers, 1 Gbits, EXT4.

#### How much data is handled by borg?

About ~2 To.

## Describe the problem you're observing.

I am using Borg to backup OpenVZ 7 disk images (root.hds).

Results are awesome. ^^

Still, I have an "issue": it does not seem possible to "ask" a remote Borg Server to "list" all repositories available/active/created.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Not a problem but a "missing" feature.

Let me explain:

I have 3 three containers: A, B and C.

Day 1 : A, B and C disk images are saved to borg SSH repos A, B and C.

Day 2 : container A is destroyed (no need to use it anymore)

Day 3 : how to prune, compact and eventually destroy repo A if container A is "missing"?

Thanks for your help! :)

**Comment by ThomasWaldmann** [comment]
borg does only know about the one repo you give on the command line, so it can't list other repos.

it's also not currently planned to add any management feature above this level.

**Comment by trendymail** [comment]
Many thanks for your answer!

So, a "solution" would be to grep "location" files inside "BORG_SECURITY_DIR" to find all used repos.

Is there any recommendation against this "raw" approach?

**Comment by ThomasWaldmann** [comment]
@trendymail guess that might work. but of course: you are accessing borg internals, so this might change (e.g. with borg2).

**Comment by trendymail** [comment]
Sorry for the late answer.

Understood!  (borg2)
 
Feel free to close this topic.

Have a great day. :)
