### ISSUE TITLE
Documentation about 'borg diff' usage

### ISSUE THREAD

**Issue by Ape** [borgbackup/borg#786]
```borg diff``` needs documentation on the [Usage page](https://borgbackup.readthedocs.org/en/stable/usage.html). I can write that after #783 is merged.

**Comment by enkore** [comment]
It already [has](http://borgbackup.readthedocs.org/en/latest/usage.html#borg-diff). The default version at RTD is stable (= last release), not latest (= HEAD of master).

**Comment by Ape** [comment]
Thanks, I will update the docs as part of #783.
