### ISSUE TITLE
Impact of compression setting on backup speed.

### ISSUE THREAD

**Issue by johannesCmayer** [borgbackup/borg#7861]
I have a question, not sure if this is the right place for it. I did not spot this with a quick glance at the FAQ.

How does the compression setting affect the backup speed? E.g. if I use LZ4 will the creation of a backup be faster (let's consider the case where we have already generated the client cache and where we need to regenerate the client cache), compared to using zstd-22?

**Comment by ThomasWaldmann** [comment]
If one just looks at compression speed, for sure lz4 is much faster than zstd,22.

But when creating a backup, borg has to do lots of other stuff besides compression (like e.g. local and network I/O, chunking, hashing, encryption), so the impact of that speedup might be not as big as in a compression algorithm benchmark.

Also, borg only needs to compress (and encrypt, authenticate, store) data which it not already has in the repository, so the performance impact of compression will also depend on how much new data is present.

Also keep in mind that ultra-high compression needs a lot of energy (and time) for diminishing returns in space usage. Especially lzma at high levels is known to be very "expensive".

**Comment by johannesCmayer** [comment]
What about the use case where you have a giant repository, and you append to it from a machine that has not generated a local cache yet? Can the compression used slow down the generation of the local cache? After the cache has been generated I would guess that the compression used would not matter anymore in terms of how long it takes to append to the repo. But I am not even quite sure what information is stored in the local cache so my guess might be wrong.

**Comment by ThomasWaldmann** [comment]
Re-syncing the (overall) chunks index reads metadata of all archives from the repo, which do not yet have a local single-archive chunks index. In this case, decompression is used, which is usually pretty fast, so likely other stuff determines the time that takes.

Whether compression for adding new data matters depends on the volume of the new data.
