### ISSUE TITLE
macOS Sonoma: “python3.11” would like to access data from other apps

### ISSUE THREAD

**Issue by sebastianhaberey** [borgbackup/borg#7869]
#### Is this a BUG / ISSUE report or a QUESTION?

Not entirely sure.

#### Your borg version (borg -V).

1.2.6

#### Operating system (distribution) and version.

macOS Sonora 14.0

## Description

I am running borg on macOS using a combination of cron and borgmatic. This has worked fine for months, but since the macOS update to Sonoma a couple days ago this keeps popping up:

<img width="372" alt="Screenshot 2023-10-11 at 18 14 05" src="https://github.com/borgbackup/borg/assets/4152849/44fbe9ce-b0da-44d8-b6b0-e2e5161f7d13">

When I click it, it just appears again (and again and again). It won't go away.

I am sure this is some kind of security problem that is macOS-related rather than a bug in borg, but I'd really appreciate some hints on how to solve this, if anybody has come across it.

**Comment by ThomasWaldmann** [comment]
Guess you could give "full disk" permissions to the terminal you start borg from.

**Comment by sebastianhaberey** [comment]
I've been able to work around this by going to System Settings -> Privacy & Security and giving "Full Disk Access" to "python3".

This doesn't seem right though, I'd like to give full disk access to borg, but not to the python binary in general.

> Guess you could give "full disk" permissions to the terminal you start borg from.

In my case borg is started by cron:

```
-+= 00001 root /sbin/launchd
 \-+= 00540 root /usr/sbin/cron
   \-+- 04508 root /usr/sbin/cron
     \-+= 04509 user /bin/sh -c /Users/user/Projects/borgbackup/borgbackup.sh >> /Users/user/Projects/borgbackup/logs/borgbackup.log 2>&1
       \-+- 04510 user bash /Users/user/Projects/borgbackup/borgbackup.sh
        \-+- 08594 user /opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python /opt/homebrew/bin/borgmatic [...]
```

 My cron already had full disk access, but apparently that's not enough.

**Comment by sebastianhaberey** [comment]
Closing this since I have a workaround and it's a macOS issue. If somebody has a more precise solution than mine ("Full Disk Access" for python3) maybe they can still post it here.
