### ISSUE TITLE
borg-linuxold64 list: error: argument --sort-by: Invalid sort key: archive

### ISSUE THREAD

**Issue by trendymail** [borgbackup/borg#7873]
Hello!

## Is this a BUG / ISSUE report or a QUESTION?

Might be a BUG

#### Your borg version (borg -V).

Borg v1.2.6 

#### Can you reproduce the problem?

Using '--sort-by="archive"' with borg list is rejected (syntax error).

Using '--sort-by="name"' with borg list works fine

---

borg list help says:

> Keys available only when listing archives in a repository:
>- archive: archive name interpreted as text (might be missing non-text characters, see barchive)
>- name: alias of "archive"

Because "name" is an alias or "archive", '--sort-by="archive"' should be accepted.

---

But, what is the official/recommended way to display/filter/glob archive name?

"name" or "archive"?

Have a great evening. :)

**Comment by ThomasWaldmann** [comment]
The code used for `--sort-by` in `Archives.list` currently only supports the `ArchiveInfo` attribute names:

name, id, ts

There is no support for aliases there.

**Comment by ThomasWaldmann** [comment]
`parseformat.SortBySpec` does a bit of preprocessing, so one can give timestamp instead of ts.

Could be extended to support the `archive` as alias of `name`.

**Comment by trendymail** [comment]
> There is no support for aliases there.

Understood.

Doc is right (as always) but it may seem legit to expect "alias" to work with "borg list".

Thank you for your answer!

**Comment by ThomasWaldmann** [comment]
Maybe someone searching for an easy contribution can make a PR for this, see my hints above.

**Comment by ThomasWaldmann** [comment]
Fixed in 1.2-maint branch.
