### ISSUE TITLE
borg check questions (borg release 1.2.3)

### ISSUE THREAD

**Issue by boelle** [borgbackup/borg#7874]
i did a check on a repro and it said problems found but no further info

are there an hidden option that can tell what archive the problem is within?

i do hourly backup but rarely change data i could remove the archive that have the issue (if its not the last one)

so yes a little more info than "problems found" would be nice

**Comment by boelle** [comment]
would the options -v -p be enough?

ie borg check --progress --verify-data -v -p  /repro

**Comment by infectormp** [comment]
There's a lot of information here about what you need to do next https://borgbackup.readthedocs.io/en/stable/usage/check.html

**Comment by boelle** [comment]
i read that one... nowhere it says how to get the info i want

**Comment by ThomasWaldmann** [comment]
Yes, usually `-v / --info` will get you informative log output, the default is only warnings and errors.

`--progress` is good for some long running stuff, like check on bigger repos.

The `--verify-data` will read and cryptographically check all file content data chunks, so that will take quite a bit longer than without that option.

**Comment by boelle** [comment]
> @boelle can you add the borg version in the top post?

added to subject

yep, i do not mind that it takes some time, i plan to do this automatic from within openmedia vault and send the output to email so i get a warning and can take action

i have ruled out hardware so it must be the connection to the offsite location that breaks or causes corruption in some of the archives

thinking of doing it once a month

**Comment by boelle** [comment]
well so far no issue

![image](https://github.com/borgbackup/borg/assets/3832239/80e66859-4237-41dd-b95e-62fe1b469f8b)

**Comment by boelle** [comment]
hmm... seems that i have no errors, will do another run just to be sure

side Q.... i can use the keep-last to keep last backup

but are there a way to say keep first and last?

**Comment by ThomasWaldmann** [comment]
No, `borg prune` is implemented in a way you can only use `--last` or `--first`.

I would recommend to rather use the timing based options though.

**Comment by boelle** [comment]
never thought of that.. ie rename them
thanks for the help so far

**Comment by ThomasWaldmann** [comment]
BTW, if you can upgrade to `borg 1.2.6` maybe do that first.

If not, be careful later when upgrading, read the upgrade hints at top of the changelog.

borg < 1.2.6 has a bug (it does not correctly regenerate the archive TAM when using `rename` or ` recreate` - and for borg versions >= 1.2.6 such archives would be considered invalid - thus the upgrade steps are required).
