### ISSUE TITLE
Multiple repos?

### ISSUE THREAD

**Issue by clickwir** [borgbackup/borg#788]
Is it ok and working to have multiple repos? I made a script to look for a repo and if it's not there, create it and then start doing backups. One local and one over SSH. But it seems whichever gets made second, doesn't work.

**Comment by enkore** [comment]
> But it seems whichever gets made second, doesn't work.

Error message?

**Comment by ThomasWaldmann** [comment]
Maybe you do not want to automate repo creation and rather let a backup script fail than automatically create a new repo if it is not there.

Just imagine your repo vanishing - wouldn't you want to know?

**Comment by ThomasWaldmann** [comment]
No response, closing.
