### ISSUE TITLE
borg stumbles over "Segment entry checksum mismatch" in archives check

### ISSUE THREAD

**Issue by boelle** [borgbackup/borg#7880]
like in #5182 i have the same issue

i also have this issue

2 backups in the repro

```
root@omvnovatech:~# borg list  /srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA
Enter passphrase for key /srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA:
21102023_10:06:36-Backup-Bo-OMV_NOVA Sat, 2023-10-21 09:06:54 [94b2ebe64ccc1273c37087bb1b10fe65c6c8ddf5baf4f910a2b118c2ad69cd4f]
21102023_10:46:52-Backup-Bo-OMV_NOVA Sat, 2023-10-21 09:46:58 [cb77345706dccb60d68d290a0f35400c857fbbb3befb289c0196fc4a141b7c0a]
```

i would have tried to delete the archive with the fault but the problem comes during the checking segments part of the check and it does not give a clue as there where and most important why (so i can avoid it in the future)

![image](https://github.com/borgbackup/borg/assets/3832239/6d2dbfb8-cbd2-47f3-bd63-1cdf1a498fa9)

2 machines in the UK that sends backup to me in DK, they also backup to each other for good messure
i send backup to both the machines in the UK

only one out of 6 backups have this error 

```
hecking segments 23.5%
Checking segments 23.6%
Data integrity error: Segment entry checksum mismatch [segment 1383, offset 194962596]
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1039, in check
    objects = list(self.io.iter_objects(segment))
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1512, in iter_objects
    size, tag, key, data = self._read(fd, self.header_fmt, header, segment, offset,
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1611, in _read
    raise IntegrityError('Segment entry checksum mismatch [segment {}, offset {}]'.format(
borg.helpers.errors.IntegrityError: Data integrity error: Segment entry checksum mismatch [segment 1383, offset 194962596]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 343, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space, max_duration=args.max_duration):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1044, in check
    self.io.recover_segment(segment, filename)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1542, in recover_segment
    with mmap.mmap(src_fd.fileno(), 0, access=mmap.ACCESS_READ) as mm:
OSError: [Errno 19] No such device

Platform: Linux omvnovatech 6.1.0-0.deb11.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4~bpo11+1 (2023-08-08) x86_64
Linux: Unknown Linux  
Borg: 1.2.3  Python: CPython 3.9.2 msgpack: 1.0.0 fuse: llfuse 1.3.8 [pyfuse3,llfuse]
PID: 1790337  CWD: /
sys.argv: ['/usr/bin/borg', 'check', '--progress', '--repair', '/srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA']
SSH_ORIGINAL_COMMAND: None
```

Q is now, do i submit another backup and try to check again or do i submit the backup and just delete the other 2?

**Comment by boelle** [comment]
so what other info is needed? borg version is mentioned

i use it via the omv plugin, ie its installed as part of the borgbackup plugin for omv, everything is updated to latest versions

**Comment by ThomasWaldmann** [comment]
So there are 2 issues here:

A) One is that you seem to have a corrupted segment file entry. The crc32 check failed for the entry in segment 1383 at offset 194962596.

This could be due to a hardware (usually RAM or storage medium) or kernel / filesystem error and is not related to borg.

**In case of a hw or fs issue, it is important to fix these first before trying to repair (or moving around a lot of data could cause more corruption).**

B) But, borg check has code to at least rescue the non-corrupt entries in a segment file
```
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1044, in check
    self.io.recover_segment(segment, filename)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1542, in recover_segment
    with mmap.mmap(src_fd.fileno(), 0, access=mmap.ACCESS_READ) as mm:
OSError: [Errno 19] No such device
```

Not sure what operation says "no such device" here, could be the `src_fd.fileno()` or the `mmap.mmap` or maybe the `__enter__` of that conext manager opening.

But usually, that should work, so guess there is something malfunctioning below borg - maybe the mergerfs?

**Comment by boelle** [comment]
```This could be due to a hardware (usually RAM or storage medium) or kernel / filesystem error and is not related to borg.```

ram has passed memcheck and is also of the ecc kind, hdd is spinning type and has also been checked for bad sectors with a pass (they are checked on every boot - not that i do that often)

it could be mergerfs, but i have no clue on how to figure out the cause

what makes me wonder why it stops checking the rest?

**Comment by ThomasWaldmann** [comment]
> `This could be due to a hardware (usually RAM or storage medium) or kernel / filesystem error and is not related to borg.`
> 
> ram has passed memcheck and is also of the ecc kind, hdd is spinning type and has also been checked for bad sectors with a pass (they are checked on every boot - not that i do that often)

OK, that sounds good.

> it could be mergerfs, but i have no clue on how to figure out the cause

Do you run that kernel since longer or was there a recent bigger upgrade?

> what makes me wonder why it stops checking the rest?

Because the line with mmap(...) failing is unexpected and fatal.

**Comment by boelle** [comment]
```Because the line with mmap(...) failing is unexpected and fatal.```

so checking again and again will and the fail happen at the same % progress does not prove or help anything?

```Do you run that kernel since longer or was there a recent bigger upgrade?``


Stupid enough i just use the update function in OMV and do not think much about it, maybe a lesson for me here is to not just update without a reason

thinking on now to progress....

**Comment by boelle** [comment]
adding another backup did not help, the check fails at the same place

trying to prune all but the last backup did fail too

```
root@omvnovatech:~# borg prune --dry-run --keep-last=1 /srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA
Enter passphrase for key /srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA:
Data integrity error: Invalid segment entry header [segment 552, offset 42891059]: unpack requires a buffer of 41 bytes
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5099, in run
    return set_ec(func(args))
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 183, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 1579, in do_prune
    with Cache(repository, key, manifest, lock_wait=self.lock_wait, iec=args.iec) as cache:
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 387, in __new__
    return local()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 378, in local
    return LocalCache(repository=repository, key=key, manifest=manifest, path=path, sync=sync,
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 497, in __init__
    self.sync()
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 903, in sync
    self.chunks = create_master_idx(self.chunks)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 857, in create_master_idx
    fetch_and_build_idx(archive_id, decrypted_repository, archive_chunk_idx)
  File "/usr/lib/python3/dist-packages/borg/cache.py", line 756, in fetch_and_build_idx
    csize, data = decrypted_repository.get(archive_id)
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 1088, in get
    return next(self.get_many([key], cache=False))
  File "/usr/lib/python3/dist-packages/borg/remote.py", line 1091, in get_many
    for key, data in zip(keys, self.repository.get_many(keys)):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1210, in get_many
    yield self.get(id_)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1204, in get
    return self.io.read(segment, offset, id)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1572, in read
    size, tag, key, data = self._read(fd, self.put_header_fmt, header, segment, offset, (TAG_PUT, ), read_data)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1587, in _read
    raise IntegrityError('Invalid segment entry header [segment {}, offset {}]: {}'.format(
borg.helpers.errors.IntegrityError: Data integrity error: Invalid segment entry header [segment 552, offset 42891059]: unpack requires a buffer of 41 bytes

Platform: Linux omvnovatech 6.1.0-0.deb11.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4~bpo11+1 (2023-08-08) x86_64
Linux: Unknown Linux
Borg: 1.2.3  Python: CPython 3.9.2 msgpack: 1.0.0 fuse: llfuse 1.3.8 [pyfuse3,llfuse]
PID: 1808016  CWD: /root
sys.argv: ['/usr/bin/borg', 'prune', '--dry-run', '--keep-last=1', '/srv/mergerfs/Data/homedir/bo/Borgbackup/Backup-Bo-OMV_NOVA']
SSH_ORIGINAL_COMMAND: None
```

**Comment by boelle** [comment]
side q.... since i have 1 working backup at my friend in the uk, can we just copy that repro to the other machine if we use the same passphrase? or are there some crypto keys that will prevent this?

**Comment by boelle** [comment]
i guess other causes of this could be an interrupted network connection, but again, i dont know which backup is the problem, both or just one... and if both would adding another backup not help?

**Comment by boelle** [comment]
hmm... just a random thought, does borg have something build in that verifies what is transfered during a backup? juat a would one in my head that maybe could prevent corruption in the first place

or if not would it be hard to implement? i know a verify during backup would slow it down, but if not many files change it would be a "small" cost

**Comment by ThomasWaldmann** [comment]
Usually `borg check --repair` can fix such issues (if it is just one or a few corrupted entries), but something in the stack **below borg** is malfunctioning here, maybe the fs or kernel.

The crc32 is computed and also checked by the repository code of borg, its main purpose is to detect corruption of the stored data / in the segment files used by borg.

Your repo URL does not look like borg is doing network stuff (no ssh:// repo), but you use some network fs and mergerfs. Thus, borg has nothing to do with the network transfer of the data and thus can't verify anything there.

Maybe you could try a `borg check --repair --repository-only` of that repository using a simpler / more direct way. If invoked that way, it does not need the encryption key and could directly run on the server that has the repo storage.

**Comment by ThomasWaldmann** [comment]
> side q.... since i have 1 working backup at my friend in the uk, can we just copy that repro to the other machine if we use the same passphrase? or are there some crypto keys that will prevent this?

You can move a repo to another place, but you must use a specific repo only at one place, of course.

Also, better do the first action with the new location interactively, borg might ask you whether the location change is ok.

**Comment by boelle** [comment]
```Your repo URL does not look like borg is doing network stuff``` 

i do the backup over internet, but the check was done where the repro is as to rule out network hickups (ie it was done on the machine storing the repro

```Maybe you could try a borg check --repair --repository-only ```

will try tomorrow when i have got some sleep

**Comment by ThomasWaldmann** [comment]
Hmm, guess then you need to modify the stack below borg on the repo server machine:
- try without that mergerfs layer (and any other non-essential layers)
- if that still does not work, try an older (or newer) kernel.
- check recent updates of your OMV installation, any kernel or fs related changes?

**Comment by boelle** [comment]
mergerfs will be hard, iuse it to pool my drives as a single one cant hold the data 

but yeah... its about the only thing left we can point fingers at

i will let the repro check run over night and save the output to file, might be lucky

**Comment by ThomasWaldmann** [comment]
Usually, if a borg create runs into a fatal error, it aborts the transaction. Next time borg is invoked, the incomplete transaction is rolled back to the last good state. But, as the docs point out, a disk full condition should be avoided by all means, because doing anything without any free disk space can be problematic.

**Comment by boelle** [comment]
> because doing anything without any free disk space can be problematic.

there was plenty free, its just mergerfs that do not skip to the next disc with free space, 
but in yeah in any case its not borg

**Comment by ThomasWaldmann** [comment]
@boelle so you identified a "mergerfs full disk" issue to be the root cause of the corruption and of the mmap issue you described above? i can somehow see that for the corruption part (guess if a segment entry does not fully fit on disk any more and it is only partially present), but the mmap issue seems to be another thing.

**Comment by boelle** [comment]
> so you identified a "mergerfs full disk" issue to be the root cause

its the only thing i can think of

> mmap issue

sorry for asking stupid, but do you mean the fast that i store my backup at a remote server?

**Comment by ThomasWaldmann** [comment]
In the traceback you posted, there is a line with mmap failing (this is the code from recover_segment, which is used to rescue as much as possible from a partly corrupted segment file). That code usually works, but did not for you.

**Comment by boelle** [comment]
One thought.... is not correct that the default max chunk size is about 500 mb? Can I reduce this? Want to do some eksperiments if lower size would reduce the risk

**Comment by ThomasWaldmann** [comment]
Yes, you can reduce it for future created segment files.

But I think you need to solve the fundamental issues on that system.

**Comment by boelle** [comment]
btw... do borgbackup say what filesize is going to be when it creates a chunk? or does it just stop when it reaches the limit in the repo config?

**Comment by ThomasWaldmann** [comment]
If it would exceed the limit, it will just write the chunk into a new segment file.

**Comment by boelle** [comment]
so it does not say "i want to create a 500mb file" before each chunk?

**Comment by ThomasWaldmann** [comment]
The chunks are usually smaller, default target size is about 2MiB, but how big the actual chunk will be depends on the contents of the file (when using the buzhash chunker) and is not known in advance.
