### ISSUE TITLE
create --list doesn't always use proper line-feeds, leading to garbled output

### ISSUE THREAD

**Issue by paddylandau** [borgbackup/borg#7888]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG report

## System information. For client/server mode post info for both machines.

Linux Ubuntu 22.04 (locally-created backup)

#### Your borg version (borg -V).

borg 1.2.6

#### Operating system (distribution) and version.

Linux Ubuntu 22.04

#### Hardware / network configuration, and filesystems used.

- Network: not applicable.
- Hardware: Dell desktop.
- File system: ext4

#### How much data is handled by borg?

Test directory, less than 1 MB.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
borg create --stats --verbose --one-file-system --progress --exclude-caches \
      --compression=zstd,22 --list --filter=AMCE --compression=zstd,22 -- \
      ${BUROOT}/zonk::'{now:%Y-%m-%dT%H-%M-%S}' \
      ${BUROOT}/bloo
```

## Describe the problem you're observing.

Terminal out from `create --list` is missing lines or shows garbled lines.

On redirecting the output to a file, I see that the problem is that some lines (not all lines) are terminated with hex `0D` (i.e. `^M`, carriage-return) instead of hex `0A` (line-feed).

On output to a terminal, this results in lines being overwritten.

One example of my output looks like this…

```
A /home/paddy/NoBackup/bloo/addy/NoBackup/bloo
```

… when it really should look like this…

```
0 B O 0 B C 0 B D 0 N home/paddy/NoBackup/bloo
A /home/paddy/NoBackup/bloo/a
```

This is because between the two lines is hex `0D` instead of hex `0A`, causing the second line to overwrite the beginning of the first line.

I don't know how to attach a file to this bug report, so you can find [my output file](https://www.dropbox.com/scl/fi/a7dwzsgfbdg3dev49jh8p/borg_create.list?rlkey=7n1v3fzumkicdqg7iap9mgtdc&dl=0) in Dropbox.

If you view it with something like `vi`, `nano` or `batcat`, you'll see the `^M` characters. If you display it to the terminal with `cat`, you'll see how the lines overwrite each other leading to missing or garbled lines.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, it's reproducible each time.

As a side note, the output goes to `stderr` instead of to `stdout`, which is really strange. `stderr` should be for errors, not normal output. No output at all goes to `stdout`.

#### Include any warning/errors/backtraces from the system logs

No errors or warnings.

**Comment by ThomasWaldmann** [comment]
That's not a bug, but the effect of mixing `--list` and `--progress`.

borg emits all log output on stderr, because stdout is used for data sometimes.

**Comment by paddylandau** [comment]
> That's not a bug, but the effect of mixing `--list` and `--progress`.

Oh. OK, thanks, I'll be sure not to use the two at the same time.

> borg emits all log output on stderr, because stdout is used for data sometimes.

Does this mean that I should suppress stdout on my terminal output?

**Comment by ThomasWaldmann** [comment]
No, you don't have to do anything special about stdout. If you use such functionality (e.g. for piping), you'll know it.
