### ISSUE TITLE
[Question] how to choose the yearly kept archive when pruning

### ISSUE THREAD

**Issue by hugotrip** [borgbackup/borg#7898]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes, probably related to #6293

## Is this a BUG / ISSUE report or a QUESTION?

Question 

## System information. 
borg 1.2.6

## Describe the problem you're observing.

As a teacher, I'd like that the yearly archive I keep match the school year, that is to tell borg to consider a year ends on 31st of july I think.

I've seen  the --keep-stdio option from issue #6293 should allow to customize pruning, but I really don't know how to use it to fit my usecase.

**Comment by ThomasWaldmann** [comment]
#6293 was not merged, so it is not available in borg.

As the normal prune won't match your needs (as it uses the normal start/end of the year), what you could do is:
- use `borg list REPO` to create a list of archives and their timestamps, you could also
  - sort by name or timestamp
  - use --format or --json to influence output format
  - restrict to a subset of all archives using --glob-archives
- read and parse the output from that using an own tool
- the own tool then could invoke `borg delete REPO::arch1 arch2 arch3 ...` to delete all given borg archives you don't want to keep.

**Comment by ThomasWaldmann** [comment]
Another option would be to rename the "yearly archive" you want to keep to a name that does not match the `--glob-archives` pattern used by your `borg prune` call.

If it does not match, borg prune will not touch it and so it will be kept.

**Comment by hugotrip** [comment]
Thanks for your replies.

If I understand correctly, your first proposal would mean that I don't use at all `borg prune` and replace it by a homemade script. If so, it will give me a lot of scratching and testing, as I'm no programmer...

The second one seems to be more accessible to me : it seems all it would require to automate this would be to set a systemd timer (I'm on linux) on the 31st of july to rename the last backup, isn't it ?

**Comment by ThomasWaldmann** [comment]
> The second one seems to be more accessible to me : it seems all it would require to automate this would be to set a systemd timer (I'm on linux) on the 31st of july to rename the last backup, isn't it ?

Yeah, that would work - just make sure the rename happens *after* the backup is done.
