### ISSUE TITLE
borg create --read-device repo /dev/vg0/*-snapshot

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#79]
this feature would read all given (device)files and save their content (not the device file node).

**Comment by tgharold** [comment]
Not sure where you're going with this feature.  Can you expand on the use case?  Maybe it's better to deal with LVM issues in a wrapper like borgmatic, then to try and expand borg to grok LVM?  Maybe keep borg more focused on "here's an already mounted file system, back it up".

**Comment by ThomasWaldmann** [comment]
The only change intended here is to read from a device file (not save the file as device file).
the archive could then be named repo::somehost-date and contain:
/dev/vg0/root-snapshot
/dev/vg0/home-snapshot
...

This is similar to using `dd if=/dev/vg0/xxx-snapshot | borg create repo:xxx` - except that we can do multiple snapshots at once and the snapshot device names are reflected in the repo.

**Comment by neutrinus** [comment]
+1
This is the last thing that blocks us from using Borg - no nice support for lvm images. We use xen and kvm, this would simplify our solution a lot.

 I will send a bag of Polish candy (krówka) for the one who will develop this :)

**Comment by ThomasWaldmann** [comment]
@neutrinus we are also on https://www.bountysource.com/. :)

reading a device is already possible using dd and stdin "-" mode, but this ticket is meant to really have the lv names in the archive.

**Comment by neutrinus** [comment]
I know, I can use stdin, but doesn't look clean for us :) 

Bounty created, no candies.

**Comment by ThomasWaldmann** [comment]
thanks for creating a bounty. guess I need to make bountysource a bit more visible here also.

**Comment by ThomasWaldmann** [comment]
I just found that this maybe makes sense to be more generic than --read-device (in the sense of a block device). How about just opening and reading (backing up) any given filename as if it were a regular file? Block devices, char devices(?), symlinks, FIFOs, sockets(?). Directories would be the only exception (and just recursed, as usual).

**Comment by ThomasWaldmann** [comment]
@neutrinus ^^^ have a look :)

**Comment by neutrinus** [comment]
Looks like it's what we have been looking for. I'm not sure if backing the content of symlink is a good idea, don't see any use case for it, but ok.

Thanks!

**Comment by ThomasWaldmann** [comment]
@neutrinus it's just treating all "special files" (except directories) the same way as regular files (and leaves the decision about what makes sense to the user for now). if we find some stuff later that never makes sense and that we do not want to "support", we could still change the code. 

about symlinks: it is useful, e.g. /dev/vg0/lvname-snapshot is a symlink to the dm target.

**Comment by sergiocallegari** [comment]
Hi,

From the previous discussion, it is unclear to me what is going to happen with symlinks.

Are symlinks going to be /dereferenced/ ?
(namely is the content pointed to by the symlink going to be backed up)

Or are symlinks going to be still stored as they are?
(namely is the location pointed to by the symlink going to be backed up)

Note that circular symlinks may be rather troublesome in the first case.

Also, it is unclear to me what happens when one backs up a device file with the new strategy. More specifically, what happens during restore?  Is the device file recreated with the same major/minor or does one get a 'real' file with the content instead?

In this case, some device files may be rather troublesome since they have infinite content.

Would it be a good idea to have slightly more extended documentation on the points above (possibly with warnings) ?

**Comment by ThomasWaldmann** [comment]
First, let me note that --read-special is not intended for normal, filesystem-level (full or partly-recursive) backups, you only give that option if you want to do something rather ... special - and if you have hand-picked some files that you want to treat that way.

It is just opening all files you give on the commandline without doing any special treatment according to the file type (the only exception here are directories: they will be recursed into). Guess same thing would happen if you just do `cat filename`.

So, symlinks will be dereferenced. Block device content will be read. Named pipes / UNIX domain sockets will be read.

I don't care about pathologic cases for the inputs. If you have circular symlinks AND you chose to give them using --read-special, well, then the old UNIX rule "you have the permission to shoot yourself into the foot" applies. Same thing can happen if you choose to give anything else that behaves troublesome when opened and read (never-ending /dev/zero, some stuff in /proc or devices that block come to mind).

About restore:

At backup time, the given files' metadata is saved as it would be saved without --read-special - but additionally, also the content read from it will be saved for it.

Restoring such a file directly (like creating a device node for the /dev/sda you saved and writing all saved content into it) would be a bit inflexible (and also dangerous maybe in case the device name changed or you did not really want to overwrite your current /dev/sda).
Thus, restoring such files' content is currently only supported one at a time via --stdout option (and you have to redirect stdout to whereever it shall go, maybe directly into an existing device file of your choice or via dd).

I added 2 examples for this in usage.rst back then already (see create/extract), but I'll add some more soon.

**Comment by sergiocallegari** [comment]
Once more, thanks for the explanation. Sorry I ask so many, but treating backup I want to be 100% sure that I understand how things work and possible corner cases before making them work.
