### ISSUE TITLE
How to check correctness of passphrase in a script?

### ISSUE THREAD

**Issue by mb706** [borgbackup/borg#791]
I'm working on a shellscript that is run interactively which asks for the repo passphrase and then invokes borg multiple times. Is there a simple way to check in a script that the passphrase is correct?

My idea at first was to set `BORG_PASSPHRASE` and then run a simple command (`borg list`) and check the exit code, but unfortunately borg queries the tty for a passphrase if the one in the environment does not match. Right now I'm using _expect_ to get around this, but this is quite hackish -- is there a simpler method?

**Comment by ThomasWaldmann** [comment]
A command "borg get-passphrase" might be useful.

It would ask for the passphrase, try it, repeat until valid and then ... echo it on stdout?

**Comment by mb706** [comment]
If borg list doesn't prompt for the passphrase and just fails (as in 94b61ea apparently, haven't run it yet) that is sufficient for my use case, thanks.

Maybe a quick check command that only checks the repo exists and the passphrase works (maybe also: the temp dir and the cache dir exist and are writeable, other assumptions borg makes...), would be generally useful in different kinds of scripts. I'm not sure having borg ask for the passphrase itself and then echo it would save the people who write scripts enough work to justify the additional complexity.

Thanks for the quick reaction btw, I love the project!

**Comment by enkore** [comment]
Fixed in 1.0-maint by #839; scheduled for 1.0.1. Will be merged back into master
