### ISSUE TITLE
Is it possible to exclude folders relative to "recursive root"?

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [borgbackup/borg#7918]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes, for hours.

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).

borg 1.2.6

## Describe the problem you're observing.

I do not understand whether exclude patterns can be specified in relative paths.

If the file *my_excludes* is:
```
Downloads
Repositories
```
and I do `borg create --exclude-from my_excludes /path/to/repo::bla /home/user` I expect */home/user/Downloads* to be excluded but this only works if *my_excludes* looks like

```
home/user/Downloads
home/user/Repositories
```

Isn't the whole point of relative paths to not have to repeat yourself and to be able to add to the file all the paths relative to `/home/user` and thus e.g. make this exclude file reusable for other users? The [docs](https://borgbackup.readthedocs.io/en/stable/usage/help.html) only contain examples where the recursion root is `/`. Therefore, no examples with actual relative paths exist AFAICS.

Am I doing something wrong? This seems like the most basic exclude use case. What is the reason that this does not "just work"?

**Comment by PanCakeConnaisseur** [comment]
I realized now that when giving multiple paths (recursion roots) to backup the relative paths in this version
```
Downloads
Repositories
```
would be ambiguous because borg wouldn't know relative to which of the backup paths (recursive roots) they are. Is this the reason this is not allowed? I also tried

```
R home/user
Downloads
Repositories
```
to no avail.

It seems to me that disallowing relative paths "just" to be able to specify multiple recursion roots is sacrificing something very common for something uncommon, but maybe my usecase is the exception.

Anyway, can you please

* confirm my suspicion
*  and help me find the most minimal/elegant config to exclude folders without hardcoding the user name in the exclude file?

**Comment by ThomasWaldmann** [comment]
Yes, you can't give exclusion paths (patterns) relative to the roots.

That one can give multiple roots is one reason.
Another reason is that the roots and also the patterns can be given on the command line as well as in a file and one can even mix the 2 approaches, so it would be unclear what pattern belongs to which root.

**Comment by PanCakeConnaisseur** [comment]
> The root paths should usually be given as absolute paths.

You mean
```
R /home/user
Downloads
Repositories
```
?

**Comment by ThomasWaldmann** [comment]
Exclude file (--exclude-from):
```
home/user/Downloads
home/user/Repositories
```

Patterns file (--patterns-from):
```
R /home/user
- home/user/Downloads
- home/user/Repositories
```

**Comment by PanCakeConnaisseur** [comment]
But does `R /home/user` in the second example even have an effect if the subsequent lines have to specify the path anyway? Or is it only useful for things like `sh:**/.[Tt]humbnails` which would match only folders inside `/home/user`?

**Comment by ThomasWaldmann** [comment]
The root path has no influence on / is not used for the patterns, it just gives a recursion root (a path in the filesystem where a recursion searching for files to back up starts).

It's the same as giving that path on the `borg create` command line.

**Comment by PanCakeConnaisseur** [comment]
I see. Thank you for your help.
