### ISSUE TITLE
borg create -read: [Errno 112] Host is down

### ISSUE THREAD

**Issue by e-ferrari** [borgbackup/borg#7920]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
1.2.4
#### Operating system (distribution) and version.
SLES 15 SP5
#### Hardware / network configuration, and filesystems used.
files to backup reside on a SAN with OCFS2. backup itself is stored on a CIFS share
#### How much data is handled by borg?
currently 3TB.
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
/usr/bin/python3.11 /usr/bin/borg create --list --stats ::{now} /mnt/domains/reflinks
```
## Describe the problem you're observing.
This is my first backup with borg. The files to be backuped reside on a OCFS2 volume on a FC SAN.
The backup itself resides on a CIFS share (NetApp). The files to be backuped are image files of virtual machines. i create reflinks (snapshots) on the OCFS2 volume so the image files are consistent and don't change during the backup.

#### Include any warning/errors/backtraces from the system logs
```
A /mnt/domains/reflinks/vm_amok.raw
/mnt/domains/reflinks/vm_amok.raw: read: [Errno 112] Host is down
E /mnt/domains/reflinks/vm_amok.raw
```
Which host is down ? The SAN or the CIFS share ?
What does borg do when this error occurs ?
Start the backup for this file again ? Or is the backup of this file corrupt ?
What does the 'E' mean ?

Thanks.

Bernd

**Comment by e-ferrari** [comment]
I found the meaning of the 'E' flag by myself:
- 'E' = regular file, an error happened while accessing/reading this file
Does that mean the backup of this file is corrupt ? Is there anything i can do to circumvent this ?
Is there maybe something similar to dd_rescue ? Which means borg create tries several times to read the clusters ?

**Comment by ThomasWaldmann** [comment]
Well, there was a read error on that file, so yes the backup of that file will be incomplete (or even skipped).

Retries were implemented a while ago in master branch (not sure though if they cover this case), but not in 1.2-maint branch (1.2.x releases) - that was a quite big change and not trivial due to the way borg works internally.

Guess you could avoid it by having a more reliable filesystem. The error was when reading the source file, so it was the OCFS2 that was having a hickup.

**Comment by e-ferrari** [comment]
Hi Thomas,
thanks for your answer. In which version was it implemented ? Maybe i will upgrade.
Thanks.
Bernd
