### ISSUE TITLE
Archive <name>  does not exist

### ISSUE THREAD

**Issue by hivefi** [borgbackup/borg#7923]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

## System information. For client/server mode post info for both machines.

desktop

#### Your borg version (borg -V).

1.2.4

#### Operating system (distribution) and version.

Debian 12 (6.1.55-1)

#### Hardware / network configuration, and filesystems used.

ext4

#### How much data is handled by borg?

?

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

sudo borg mount -o allow_other  /media/abc/123/borg2::zyxe  /media/e1234/

## Describe the problem you're observing.

Error 'Archive zyxe  does not exist'

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

I tried opening another backup. Also, I have tried to put the backup name in quotes. 

#### Include any warning/errors/backtraces from the system logs
N/A

**Comment by ThomasWaldmann** [comment]
Use `borg list` to show the archives in that repo.

In case of doubt, you can also use `borg check` to check the repository.

**Comment by hivefi** [comment]
I used `borg list` to view the backups in my repo. I enter the name of a backup included in the list. But it still gives the error when I try to mount one of the backups listed. 
I ran  'borg check' on the repo. No Output

**Comment by hivefi** [comment]
When I try to mount the repo with  I get "Repository /media/abc/123/borg2/  does not exist."
All my backups are have simple short names. I checked `borg list --format='*{archive}*{NL}' /media/abc/123/borg2
`

**Comment by ThomasWaldmann** [comment]
Huh? So you are saying `borg list repopath` works for you, but `borg mount repopath mountpoint` with same repopath does not?

If that is the case, guess I need the full terminal log with all the commands and the full output.

**Comment by hivefi** [comment]
I just tried again. It works now. Maybe after rebooting. I don't know.
