### ISSUE TITLE
take borgbackup stickers to the 37c3 (CCC event)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7927]
Event info: https://events.ccc.de/congress/2023/infos/index.html

I won't be there in person, but if someone from borg community visits there, they could get some borg stickers from me to distribute there.

In the past, there used to be sticker boxes at some places at congress, I assume this will be the case this year also.

So the task would be to put the stickers into these 37c3 sticker boxes so any interested visitor can pick up some from there.

Requirements:
- you need to have a congress ticket to get in there
- you need to request stickers from me (providing your postal address via e-mail) before 2023-12-12 to make sure you get the stickers before your travel to 37c3.

If you are interested, drop a comment below. Thanks!

**Comment by ThomasWaldmann** [comment]
Looks like today was the last 37c3 tickets sale.

**Comment by ThomasWaldmann** [comment]
Too late, no stickers for 37c3.

**Comment by dragetd** [comment]
Update: I have a lot of stickers and will drop them at sticker-collection points, the FOSS-AG Assembly and can be reached via @draget:matrix.org on Matrix if you need some for your table! :)
