### ISSUE TITLE
borg2: invalid chars detected matching

### ISSUE THREAD

**Issue by wbiehl** [borgbackup/borg#7938]
Why am I getting the "invalid chars detected matching" error?

When running "borg extract /mnt/backup/Borg::box-2023-11-15T01:57:01 /mnt/volume/mail/tm.com" I get the error "argument NAME: Invalid archive name: "/mnt/ backup/Borg::box-2023-11-15T01:57:01" [invalid chars detected matching "/\"<|>?*"]"

**System information**
Ubuntu Linux 22.04.3
borg 2.0.0b8.dev71+g8ebeb3cc

**Comment by ThomasWaldmann** [comment]
Looks like you use borg master branch (borg2), but the command syntax you use is like for borg1.

borg2 is not for production yet, but if you want to experiment with it, the syntax would be rather like:
```
borg extract -r /mnt/backup/Borg box-2023-11-15T01:57:01 mnt/volume/mail/tm.com
```

See the upgrade notes in the changelog about borg2 syntax changes.

**Comment by wbiehl** [comment]
> borg extract -r /mnt/backup/Borg box-2023-11-15T01:57:01 mnt/volume/mail/tm.com

It worked for me, Thank you very much!
