### ISSUE TITLE
`--exclude-caches` is not working

### ISSUE THREAD

**Issue by mamekoro** [borgbackup/borg#7945]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
Yes
(Searched `"--exclude-caches"` and `exclude caches`)

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).
borg 1.2.6

#### Operating system (distribution) and version.
Ubuntu 22.04

#### Hardware / network configuration, and filesystems used.
- Local (offline) repository
- Reproduced on Btrfs and tmpfs

#### How much data is handled by borg?
Small amount. (Tested with a directory with empty files.)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```bash
#!/usr/bin/env bash

mkdir /tmp/test-borg
cd /tmp/test-borg

borg init --encryption none repo

mkdir ignored
touch ignored/{CACHEDIR.TAG,hello}

set -x
borg create --exclude-caches --list repo::archive .
borg list repo::archive
set +x
```

## Describe the problem you're observing.
I expected the `./ignored` directory to be excluded, but was included.

The `ignored` directory has `CACHEDIR.TAG`, and the arguments for `borg create` has `--exclude-caches`, so I thought borg would exclude that directory, but it didn't work as expected. Am I missing something?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. See the shell script above.

#### Include any warning/errors/backtraces from the system logs
Here is the log obtained from the shell script above.

```
+ borg create --exclude-caches --list repo::archive .
A ignored/CACHEDIR.TAG
A ignored/hello
d ignored
d .
+ borg list repo::archive
drwx------ user group        0 Wed, 2023-11-22 00:36:34 .
drwx------ user group        0 Wed, 2023-11-22 00:36:34 ignored
-rw------- user group        0 Wed, 2023-11-22 00:36:34 ignored/CACHEDIR.TAG
-rw------- user group        0 Wed, 2023-11-22 00:36:34 ignored/hello
+ set +x
```

**Comment by mamekoro** [comment]
Sorry. This was my mistake, I forgot to write the following data to `CACHEDIR.TAG`.

`Signature: 8a477f597d28d172789f06886806bc55`

**Comment by jdchristensen** [comment]
Should `borg` be added to the list of backup software that supports CACHEDIR.TAG?  See https://bford.info/cachedir/

**Comment by mamekoro** [comment]
I have no particular opinion. I think it is up to the owner of bford.info.

**Comment by ThomasWaldmann** [comment]
@jdchristensen yes, could be added.

But I guess it's not super important - or does somebody choose the backup software by cachedir.tag support?
