### ISSUE TITLE
request a release

### ISSUE THREAD

**Issue by chenrui333** [borgbackup/borg#7948]
👋 not sure what would be the timeline for the new release, just raise an issue in here to ask. Thanks!

**Comment by chenrui333** [comment]
or can we do a maint release for 1.2-maint branch (msgpack needs some updates)

**Comment by ThomasWaldmann** [comment]
There is currently some testing being done about #6687, but other than that, there is nothing left in 1.2.7 milestone, so a release can come soon after positive feedback from testers.

**Comment by ThomasWaldmann** [comment]
Working on 1.2.7, will be out soon...
