### ISSUE TITLE
Split commands to their own code files from archiver.py

### ISSUE THREAD

**Issue by Ape** [borgbackup/borg#795]
This is just a minor refactoring ticket. I think `archiver.py` to too long. It would be a lot easier to navigate on the code if each command would have their own file along with their implementation (`do_x` function) and subparser.

This also applies to `testsuite/archiver.py`.

**Comment by ThomasWaldmann** [comment]
I see what you mean, but I think we first should do some simpler changes (like moving all into src/ ).

Also, a change like that likely causes a lot of troubles for the other branches "multithreading" and "experimental", so I'ld rather like to do that later.

**Comment by enkore** [comment]
Another nit-pick I have with archiver.py is that all the do_XYZ stuff and the argument definitions for them are far apart (and all the arg defs are clumped together; I navigate that only with Ctrl-F 'do_whatiwannaknow'). There are approaches to declarative argument definition for command line interfaces (e.g. click), but dependency issues and compatibility with scripts has to be evaluated carefully for such a change (if any).

**Comment by ThomasWaldmann** [comment]
see #6323.
