### ISSUE TITLE
fsync(2) the nonce file after it has been written for better resilience

### ISSUE THREAD

**Issue by mnalis** [borgbackup/borg#7969]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

ISSUE (enhancement request)

#### Your borg version (borg -V).
borg 1.2.4

#### Operating system (distribution) and version.
Debian Bookworm GNU/Linux

#### Hardware / network configuration, and filesystems used.
Dell i5 laptop with 16GB RAM, source NVMEs, with external 3.5TB USB HDD. Ext4 on both the source data and destination borg repository.

#### How much data is handled by borg?
about 1 TB in external HDD repository.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
`sudo borg create --stats --progress --noflags --noacls --noxattrs --compression zstd --exclude-caches --exclude-from /etc/exclude.txt  /media/ladica/backup/borg::{hostname}-{now}`

## Describe the problem you're observing.

It seems that `nonce` can get corrupted. While there are many ways it can happen (including software bugs and hardware issues), if the borg made sure the nonce file is safely on disk before continuing, that should reduce the chance of it getting corrupted.

This suggestion is being split from https://github.com/borgbackup/borg/issues/7967#issuecomment-1860645648, as it might need taking a deeper look separately from the problem mentioned there. This are some of possible alternatives (copied from that comment):

---

That got me wondering how just that `nonce` file could get corrupted, with the rest of the disk and repository apparently in good condition?  I've looked at `commit_nonce_reservation` which I think is responsible for saving `nonce` file (note that I'm completely new to borg codebase and not an python expert; my background is more in C) :

https://github.com/borgbackup/borg/blob/4c131059bc9e90753160c07bf26165278aeab69a/src/borg/repository.py#L365-L369

and it seems that it relies on `SaveFile` to make sure that the data is safely on disk before continuing there.

However if I'm reading that correctly, `SaveFile` seems to only do `close(2)`, which does not guarantee that data is safely on disk? i.e.

https://github.com/borgbackup/borg/blob/1432f547fe4fe13386b245dcc0d9c2a0880ddfe6/src/borg/platform/base.py#L239-L244

Would it make sense to either:

- explicitly `fsync(2)` file data before `close(2)` in `SaveFile` `__exit__`?
- explicitly `fsync(2)` file data in `commit_nonce_reservation` after `write(2)` (if above would be performance killer in other cases where it is unneeded - `nonce` is not being written all that frequently if I understand correctly, so it should be OK to do it just there?)
- I notice that there is also `class SyncFile` which perhaps might be used for `nonce` file (the function descriptions do not seem to explain when one is supposed to use one or the other)?

**Comment by ThomasWaldmann** [comment]
Note: SaveFile uses SyncFile internally.

**Comment by mnalis** [comment]
You are correct, I have missed that part. Verifying with `strace(1)` indicates it is indeed doing `fdatasync(2)` on `nonce` file upon writing it (which should be good enough for this case, as full `fsync(2)` shouldn't be needed unless we particularly care about timestamps there?):

```
 openat(AT_FDCWD, "/tmp/s/b/nonce-_mvpr2pa.tmp", O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC, 0666) = 5
 newfstatat(5, "", {st_mode=S_IFREG|0600, st_size=0, ...}, AT_EMPTY_PATH) = 0
 ioctl(5, TCGETS, 0x7ffebfb8c440) = -1 ENOTTY (Inappropriate ioctl for device)
 lseek(5, 0, SEEK_CUR) = 0
 lseek(5, 0, SEEK_CUR) = 0
 write(5, "000000006000006d", 16) = 16
 fdatasync(5)      = 0
 fadvise64(5, 0, 0, POSIX_FADV_DONTNEED) = 0
 close(5)          = 0
 openat(AT_FDCWD, "/tmp/s/b", O_RDONLY|O_CLOEXEC) = 5
 fsync(5)          = 0
 close(5)          = 0
 rename("/tmp/s/b/nonce-_mvpr2pa.tmp", "/tmp/s/b/nonce") = 0
 openat(AT_FDCWD, "/tmp/s/b", O_RDONLY|O_CLOEXEC) = 5
 fsync(5)          = 0
 close(5)          = 0
```

Closing this issue as it seems to be red herring (regarding repo corruption issues)
