### ISSUE TITLE
How new is my Linux?

### ISSUE THREAD

**Issue by Faerbit** [borgbackup/borg#7973]
For Linux you provide the following binaries:
* `borg-linuxold64`
* `borg-linux64`
* `borg-linuxnew64`
* `borg-linuxnewer64`

What the hell are those? How do I know if my Linux is old, ɛ, new, or newer?

If I missed some really obvious place where this is documented: I'm sorry, but I really can't find any information about this.

P.S. Using more descript names, would circumvent this problem somewhat.

**Comment by ThomasWaldmann** [comment]
Please read the 00_README.txt that sits right besides the other files.

**Comment by Faerbit** [comment]
Thank you :)

> For borg2, will use filenames that contain the glibc version

That sounds like a great idea!

**Comment by jdchristensen** [comment]
When I search for "borg download" I always find https://github.com/borgbackup/borg/releases and I often wonder which version to download.  Can that page be set-up to have a link to the 00_README.txt file?

**Comment by ThomasWaldmann** [comment]
@jdchristensen Yes, I opened a ticket about that.
