### ISSUE TITLE
Capitalization is not consistent

### ISSUE THREAD

**Issue by rumpelsepp** [borgbackup/borg#798]
This is just a nitpicking issue, but borg does not have a consistent usage of capitalized words in log messages. Also ellipsis (...) are not used consistently; sometimes there are some, sometimes there are none.

```
Archives: 1, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 1.
Fetching and building archive index for tatooine-2016-03-25-150454-CET ...
Merging into master chunks index ...
Done.
reading files cache
processing files
```

**Comment by ThomasWaldmann** [comment]
Yeah, you're right.

These need to get capitalized and ...ed.

Also, I guess it makes sense to emit them at DEBUG level, not at INFO level.
