### ISSUE TITLE
Borg "create" using a "--timestamp" far in the past: will borg "delete" or "prune" fail? (or will they behave as normal?)

### ISSUE THREAD

**Issue by trendymail** [borgbackup/borg#7985]
Hello !

## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yep! Doc is incredible, FAQ is awesome and issues are "delicious"... ^^

However, I did not read (yet) [Internals](https://borgbackup.readthedocs.io/en/stable/internals.html).

## Is this a BUG / ISSUE report or a QUESTION?

Question

## System information. For client/server mode post info for both machines.

OpenVZ 7 container: Debian 10 (buster) and soon Debian 12 (bookworm).

#### Your borg version (borg -V).

borg-linux64 1.2.7 using "fat" binaries (Debian 10 => borg-linux64, Debian 12 => borg-linuxnew64)

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Ex : `borg create --timestamp "2020-01-01 CET 00:00:00" REPO::files_2020-01-01 <files to save>`

## Long story short

I would like to use Borg to chunk/deduplicate/compress mails actually stored in uncompressed backup folders.

Every day; each mail received or send is copied in a separate backup folder with a date (oldest mail is about 5 years ago):

- `/home/backup/mails/<email_address>/<date:>/<recv|sent>/<files>` (each file is a raw mail)

After scanning these folders by date, I would like to create a unique borg archive for each day, ex:

- `borg create --timestamp "2018-05-16 CET 00:00:00" REPO::<email address>_recv_2018-05-16 ./<email address>/2018-05-16/recv/`
- `borg create --timestamp "2018-05-16 CET 00:00:00" REPO::<email address>_sent_2018-05-16 ./<email address>/2018-05-16/sent/`

## Question

Can I expect borg "prune" to behave normally when deleting (and then "compacting") archives older than 3 years?

- `borg prune --keep-within "3y" --glob-archives "<email address>_recv_*" REPO`
- `borg prune --keep-within "3y" --glob-archives "<email address>_sent_*" REPO`

Have great day/night (?) and thanks for Borg!

**Comment by ThomasWaldmann** [comment]
If you use `borg create --timestamp ...` then the created archive will look like it has been created at the given timestamp. `borg prune` will then use that timestamp for that archive when it considers its deletion (or keeping).

You can just try this yourself - if you use `borg prune --dry-run --verbose ...` you can first check whether it behaves as you wanted.

BTW, check the timestamp format, you need to use it as documented:

https://borgbackup.readthedocs.io/en/stable/usage/create.html
```
--timestamp TIMESTAMP | manually specify the archive creation date/time
                        (UTC, yyyy-mm-ddThh:mm:ss format).
                        Alternatively, give a reference file/directory.
```

`T` is just the letter T, not "CET". And you need to give UTC timestamp.

**Comment by trendymail** [comment]
> you need to give UTC timestamp.

Understood and sorry for the confusion: "CET" (date +%Z) is used internally to get UTC time (sent to borg "create").

Many thanks for your answer: I will try and test soon (a week or two).

Before that, I really must understand (and test) how "chunker-params" (unlike fixed chunker) handles and chunks data.

Again, thank you for your time. :)

**Comment by trendymail** [comment]
### Long story short

It turns out that:
- default "chunker-params" (buzhash,19,23,21,4095) 
- with custom "compression" (auto,zstd,3)
- yields very good results when creating backups of websites (~450 GiB).

So it should be the same (good) results when "backuping" mail files (~350 GiB) containing attached files.

**But, honestly, I did not try to "tune" chunker-params (so your mileage may vary).**

Lack of time and also because existing issues/questions/suggestions reported (from my point of view) limited benefits compared to the amount of time needed to test each case.

Closing this question resolved! :)
