### ISSUE TITLE
point to 00_README.txt from web page

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#7990]
From @jdchristensen:

When I search for "borg download" I always find https://github.com/borgbackup/borg/releases and I often wonder which version to download. Can that page be set-up to have a link to the 00_README.txt file?

**Comment by ThomasWaldmann** [comment]
Hmm, that page has the list of all assets on it and the `00_README.txt` is the first asset in that list.

@jdchristensen So you meant having a link in the text right above the asset list to the file in the asset list?

Or did you mean a link from another web page?

**Comment by jdchristensen** [comment]
@ThomasWaldmann Sorry, I missed the `00_README.txt` being at the top of the list.  What I think would help is some text saying something like "See the `00_README.txt` file in the assets list below for a description of the available downloads."

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/releases/tag/1.2.7 done there (I usually copy the text to next release and update it).

**Comment by jdchristensen** [comment]
Thanks, that makes sense.  The two sentences at the end seem to essentially say the same thing, though, so maybe one of them should be removed?

**Comment by ThomasWaldmann** [comment]
Sure, forgot to remove one, done!
