### ISSUE TITLE
Disable checkpoints, even on interrupted backups

### ISSUE THREAD

**Issue by Hawk777** [borgbackup/borg#8013]
Checkpoints are a great idea for unreliable links: in any situation where Borg might not be able to finish a backup, having a checkpoint means being able to resume faster later. However, even over the Internet, for my particular use case, I simply don’t run into that problem. However, I do often run into a different problem: Borg is running happily, creating an archive, and as I watch it, I notice that it’s backing up an *enormous* file that I really don’t want backed up—something newly arrived in the source directory, that isn’t in my exclude list yet because it didn’t exist before. At that point, I kill Borg, either delete the file or add it to an exclude pattern as appropriate, and then start it up again. However, in this case, checkpoint logic is counterproductive:
* Borg wants to create a checkpoint when I press Ctrl+C. I don’t *want* the file it’s in the middle of backing up, and would really rather it *didn’t* do that. So I have to wait for it to create a checkpoint that I don’t even want, which can take quite a few minutes.
* Once it’s finally finished running, creating the checkpoint I don’t even want, I just have to go and delete it and compact afterwards, which is an annoying extra step (especially since deletion requires a passphrase, which I effectively have to type twice since I have to also run `list` to find out what the checkpoint is named—just having to compact alone wouldn’t be so bad since it doesn’t need a passphrase).
* I could probably kill Borg harder, but it’s not obvious that doing so is safe or ergonomic (e.g. will it leave behind stale locks which I have to do just as much manual work to clean up?).

I’m not even certain whether “disabling checkpoints” is actually the feature I’m asking for, but it seems like it would probably do the job for me.

**Comment by ThomasWaldmann** [comment]
- Did you try hitting Ctrl-C **twice**?
- For the timed checkpoints, you could use a rather long `--checkpoint-interval=99999999` (default is 1800 IIRC).

borg2 might do this differently.

**Comment by Hawk777** [comment]
I haven’t tried double Ctrl+C. If a “harder” kill is safe (which I guess it must be—surely Borg is crash-consistent), then that would probably do the job well. This can probably be closed if that’s expected to work, thanks!

**Comment by ThomasWaldmann** [comment]
First please try if the double-Ctrl-C works for you.

If you use something like `kill -9` you have to expect some minor issues, like e.g. a locked repo (but no major damage).
