### ISSUE TITLE
Porting unit tests to py.test

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#802]
Currently we use pytest features in some tests, but most of the test-suite still runs on unittest.TestCase. A lot of useful pytest features just doesn't work for those, e.g. fixtures, which have to be emulated by hand, if necessary.

Maybe we should get rid of the legacy unittest stuff altogether and make the switch to pytest? It would make things like parametrized tests certainly much easier...

**Comment by ThomasWaldmann** [comment]
See #28. I'm ok with refactoring it, just be careful to not introduce regressions and maybe try to do it in multiple, simple steps rather than a huge / complicated change.

Closing this as duplicate.

**Comment by enkore** [comment]
Ok, thanks
