### ISSUE TITLE
failing hashindex tests on netbsd

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#804]
I've bisected the issue and this is the changeset breaking the tests: https://github.com/borgbackup/borg/commit/f63be633470128a84a2640cd3202d28c62223e21

@pyhalov can you fix it in a way so it does not break netbsd (64bit)?

`py.test -k hashindex` shows the failing tests.

I think the issue is that you check for _BIG_ENDIAN or _LITTLE_ENDIAN being defined. They are both defined on netbsd (and have a 4321, 1234 value).

http://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/sys/endian.h

**Comment by pyhalov** [comment]
I can do something like this https://github.com/pyhalov/borg/commit/6965f7d4383b7e2fa263afff3d8f74f4e63dbc0d

**Comment by ThomasWaldmann** [comment]
Yes, that does not fail on netbsd, please commit/PR and append ", fixes #804" to your commit comment.
