### ISSUE TITLE
`**/` exclude pattern excludes only from subdirs, not from main backed-up dir

### ISSUE THREAD

**Issue by mooreye** [borgbackup/borg#8042]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.2.7

#### Operating system (distribution) and version.
Fedora 39

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
cd ~
borg create --exclude-from "$borg_exclude_file" "$repo_dir::$snapshot_timestamp" .
```

## Describe the problem you're observing.

I want to exclude all LibreOffice's lock files from backup, so I put this in exclude file:

`**/.~lock.*#`

However, it only excludes from subdirectories and not from the main level of backed-up dir. This:

`.~lock.*#`

in turn excludes only from main level and not from subdirs. I have to include both patterns to exclude all of them.

Manual states that `**/` corresponds to *zero or more* levels so from what I understand the first solution should exclude both from main and subdirs. What am I doing wrong?

```
        Shell-style patterns, selector `sh:`
            This is the default style for ``--pattern`` and ``--patterns-from``.
            Like fnmatch patterns these are similar to shell patterns. The difference
            is that the pattern may include `**/` for matching zero or more directory
            levels, `*` for matching zero or more arbitrary characters with the
            exception of any path separator. A leading path separator is always removed.
```

**Comment by ThomasWaldmann** [comment]
Guess the problem might be that only the `**` is the wildcard, but you have `**/` there and that needs that additional slash to match.

**Comment by mooreye** [comment]
> Guess the problem might be that only the `**` is the wildcard, but you have `**/` there and that needs that additional slash to match.

It seems you're right, when I tried with:
`**.~lock.*#`
it works for both cases.

However this was not obvious to me since manual has this example:
```
# Exclude all iso files in any directory
- **/*.iso
```

"Any" seems to be both main and subdir to me.

**Comment by ThomasWaldmann** [comment]
Need to check how the code does the matching, maybe code and/or docs needs fixing.

**Comment by ThomasWaldmann** [comment]
I fixed the top post, must be `**/` (not `**`).

**Comment by ThomasWaldmann** [comment]
I just added this to the tests and it **succeeds**!
```
def test_patterns2_shell():
    pattern = "**/.~lock.*#"
    files = [".~lock.#", "docs1/.~lock.1#", "docs1/docs2/.~lock.12#", "something", "docs1/something"]
    expected = [".~lock.#", "docs1/.~lock.1#", "docs1/docs2/.~lock.12#"]
    check_patterns(files, ShellPattern(pattern), expected)
```

Is that the kind of filenames and the usecase you had in mind?

**Comment by ThomasWaldmann** [comment]
I think the problem might be that you use `fm:` pattern style (default for --exclude-from), not `sh:` style:

https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns

**Comment by ThomasWaldmann** [comment]
So, if you want to continue with `--exclude-from`, try:
```
sh:**/.~lock.*#
```

**Comment by mooreye** [comment]
So it was my fault after all 🤦‍♂️
`sh:` works fine. Closing this then.
