### ISSUE TITLE
Issues with creating a repo

### ISSUE THREAD

**Issue by Yukinooooooo** [borgbackup/borg#8056]
I'm using Fedora 39 KDE, Kernel Version : 6.6.11, Wayland, borg version : 1.2.7 (Official by Fedora)

I installed borg with `sudo dnf install borgbackup`, everything is ok. When I try to create a repo without encryption with `borg init -e none /backup/borg` (I created a "backup" folder then "borg" folder from backup in cd `$HOME/Documents` before running `borg init -e none /backup/ borg`) First I type `cd $HOME/Documents` then `borg init -e none /backup/borg`, once typed, I got an error message :

```
[username@fedora Documents] $ borg init -e none /backup/borg
Local Exception
Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/borg/archiver.py", line 5343, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/borg/archiver.py", line 5263, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/borg/archiver.py", line 174, in wrapper
    with repository:
  File "/usr/lib64/python3.12/site-packages/borg/repository.py", line 201, in __enter__
    self.create(self.path)
  File "/usr/lib64/python3.12/site-packages/borg/repository.py", line 276, in create
    self.check_can_create_repository(path)
  File "/usr/lib64/python3.12/site-packages/borg/repository.py", line 258, in check_can_create_repository
    if not stat.S_ISDIR(st.st_mode) or os.listdir(path):
                                       ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/backup/borg'

Platform: Linux fedora 6.6.11-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 10 19:25:59 UTC 2024 x86_64
Linux: Unknown Linux  
Borg: 1.2.7  Python: CPython 3.12.1 msgpack: 1.0.5 fuse: llfuse 1.5.0 [pyfuse3,llfuse]
PID: 29967  CWD: /home/bpklxi/Documents
sys.argv: ['/usr/bin/borg', 'init', '-e', 'none', '/backup/borg']
SSH_ORIGINAL_COMMAND: None
```

When I typed sudo borg init -e none /backup/borg it says : "`A repository already exists at /backup/borg`, while my `/backup/borg` is empty, no files or anything else

**Comment by infectormp** [comment]
You need fix this problem -> **PermissionError: [Errno 13] Permission denied: '/backup/borg**
This error raised by OS not by borg

**Comment by ThomasWaldmann** [comment]
As a side note: borg >= 1.4.0b1 will emit just an error msg for that case (no traceback).

**Comment by ThomasWaldmann** [comment]
Guess this is solved?
