### ISSUE TITLE
Cache corruption

### ISSUE THREAD

**Issue by HusseinKabbout** [borgbackup/borg#8058]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).

```
> borg -V
borg 1.2.7
```

#### Operating system (distribution) and version.

```
> cat /etc/fedora-release
Fedora release 39 (Thirty Nine)
```

#### Hardware / network configuration, and filesystems used.

No special hardware or network share is used. I am using a normal BTRFS setup, that also contains my OS.

#### How much data is handled by borg?

Not relevant here.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

```
mkdir backup/ data/
borg init backup/ -e repokey
echo "Test" > data/some_data.txt
borg create --list backup::test1 data/some_data.txt
borg create --list backup::test1 data/some_data.txt
borg create --list backup::test2 data/some_data.txt
```

## Describe the problem you're observing.

By running the commands described above, the borg cache seems to get corrupted and all files are always treated as new files when backing up. It seems that the `~/.cache/borg/..../files` file does not get written into anymore.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

See `Full borg commandline that lead to the problem (leave away excludes and passwords)`

#### Include any warning/errors/backtraces from the system logs

Not relevant here.

**Comment by ThomasWaldmann** [comment]
Please see the FAQ about the files cache behaviour.

https://borgbackup.readthedocs.io/en/stable/faq.html#i-am-seeing-a-added-status-for-an-unchanged-file
