### ISSUE TITLE
borg delete is not using environment-variable "BORG_REPO"

### ISSUE THREAD

**Issue by bigboss74** [borgbackup/borg#8059]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug

#### Your borg version (borg -V).
borg 1.2.7

#### Operating system (distribution) and version.
ubuntu 22.04.

#### Hardware / network configuration, and filesystems used.
os: ext4
repo: zfs

#### How much data is handled by borg?
compressed testrepo is 25G

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
export BORG_REPO=/my/path/testrepo
export BORG_PASSPHRASE=mysecret
borg list
borg delete testarchive

## Describe the problem you're observing.
"borg list" works perfect and shows "testarchive"
"borg delete" is not using the environment "BORG_REPO"

Errormessage: "Repository testarchive does not exist."

Workaround is:
borg delete /my/path/testrepo testarchive

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes.
Create Archive and Delete it. Both with using the Environment-Variable "BORG_REPO".

**Comment by ThomasWaldmann** [comment]
The syntax you use does not do what you think. The way you gave it, it will try to delete a whole repo at path "testarchive".

What you need for your use case is:
```
borg delete ::testarchive
```
(if the repo spec (left side of ::) is empty, it will try to get it from BORG_REPO)
