### ISSUE TITLE
Recovery Dilemma: Lost Passphrase but BORG_KEY Access

### ISSUE THREAD

**Issue by juriSacchetta** [borgbackup/borg#8063]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?
Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Your borg version (borg -V).
borg 1.2.7

#### Operating system (distribution) and version.
Alpine

#### How much data is handled by borg?
200 GB

## Describe the problem you're observing.

Good morning,

I'm reaching out for guidance regarding a recent decision to reinstall without securing backup data from the Vorta tool. I'm attempting to regain access to my backup repository. I still have the BORG_KEY file but am unsure how to recover it.

I believe the repository type is Repokey-black2 with the repokey stored within the repository. When I initially created the repo, I backed up the Borg file in my Bitwarden but have since lost the passphrase. Is there any chance of recovering my backups?

**Comment by ThomasWaldmann** [comment]
You need both the key (either as keyfile or in the repo config or as a backup of one of these) **and** the passphrase.
