### ISSUE TITLE
borg info returns size values larger then the original

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#808]
I'm doing some benchmarking, using borg v1.0.0 (linux 64bit, Ubuntu 15.10 64bit) to backup a single .tar file to a local repository on the same machine.

The size of the .tar file is: 159869280 kilobytes (152.46GB) or 163706112000 bytes (also 152.46GB)

```borg info``` of the resulting backup consistently misreports the original size (across multiple compression methods):

```
                       Original size      Compressed size    Deduplicated size
This archive:              163.71 GB             93.75 GB             88.35 GB
All archives:              163.71 GB             93.75 GB             88.35 GB

                       Unique chunks         Total chunks
Chunk index:                   54778                59771
```

Even the final deduplicated size is a bit off as the "du -cks" size of the resulting borg directory was only 86310392 kilobytes (82.31GB), but the ```borg info``` reports the deduplicated size as 88.35GB.

**Comment by ThomasWaldmann** [comment]
1GB = 1 * 10^9 B, 1 GiB = 1 * 2^30 B.

So, for the original size: 163706112000 bytes == 163.71 GB.

**Comment by ThomasWaldmann** [comment]
For the deduplicated size, it is 86.31 GB (du) vs. 88.35GB (borg).
Maybe this is due to the snapshots it has taken every 5 minutes, but deleted again when it made the final archive. How long did this backup take?

**Comment by tgharold** [comment]
Anywhere from 60 minutes to 400 minutes (depending on the compression level).

**Comment by enkore** [comment]
`du` also considers the size of directories (how much their inode and directory entries take, as reported by the FS), while Borg will only consider the data actually stored in the repository.
