### ISSUE TITLE
purge "looks" different after upgrading from 0.3.x to 1.0RC1

### ISSUE THREAD

**Issue by ovizii** [borgbackup/borg#811]
I am using a script run by cron which in turn emails me the results, containing this:

```
/usr/local/sbin/borg prune $REPOSITORY -v --prefix `hostname`- \
    --keep-daily=7 --keep-weekly=4 --keep-monthly=6 --keep-yearly=1
```

Not sure if its me but the older versions delivered an output like this:

Keeping archive: james-2016-03-29                     Tue, 2016-03-29 04:59:38
Keeping archive: james-2016-03-28                     Mon, 2016-03-28 04:59:38
Keeping archive: james-2016-03-27                     Sun, 2016-03-27 04:59:40
Keeping archive: james-2016-03-26                     Sat, 2016-03-26 04:59:39
Keeping archive: james-2016-03-25                     Fri, 2016-03-25 04:59:38
Keeping archive: james-2016-03-24                     Thu, 2016-03-24 04:59:38
Keeping archive: james-2016-03-23                     Wed, 2016-03-23 04:59:37
Keeping archive: james-2016-03-20                     Sun, 2016-03-20 04:59:39
Keeping archive: james-2016-03-13                     Sun, 2016-03-13 04:59:39
Keeping archive: james-2016-03-06                     Sun, 2016-03-06 04:59:38
Keeping archive: james-2016-02-29                     Mon, 2016-02-29 04:59:38
Keeping archive: james-2016-02-28                     Sun, 2016-02-28 04:59:38
Keeping archive: james-2016-01-31                     Sun, 2016-01-31 04:59:39
Keeping archive: james-2015-12-31                     Thu, 2015-12-31 04:59:39
Pruning archive: james-2016-03-22                     Tue, 2016-03-22 04:59:39

while the new one shows nothing when running the prune command.

**Comment by enkore** [comment]
Try --stats or --list (see #658)

**Comment by ovizii** [comment]
Thanks!
