### ISSUE TITLE
BORG_EXIT_CODES=modern as DEFAULT in borg2?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#8110]
borg 1.4 defaults to "legacy".

We could change that for borg2 to "modern", so borg by default gives a lot of specific error and warning exit codes.

Opinions about that?

**Comment by ThomasWaldmann** [comment]
@m3nu @witten @sophie-h

**Comment by m3nu** [comment]
Vorta doesn't use them extensively right now. We could add better error messages after this is the default. Right now we only say "Some files couldn't be read, see logs for details" for example.

**Comment by ThomasWaldmann** [comment]
@m3nu Thanks for the feedback!

Just as a general note: support for these error/warning codes could be added at any time IF the wrapper checks/sets BORG_EXIT_CODES and reacts accordingly. This would be good, considering that borg >= 1.4 will already optionally support this (and that will be released soon).

**Comment by witten** [comment]
Recent versions of borgmatic set `BORG_EXIT_CODES=modern` unconditionally, so this proposed change to Borg 2 would be fine from borgmatic's perspective.

**Comment by ThomasWaldmann** [comment]
@witten Thanks for the feedback.

Just be careful: setting that will only change behaviour for borg >= 1.4.

**Comment by witten** [comment]
Understood!

**Comment by sophie-h** [comment]
> Opinions about that?

For 2.0 that's totally fine.
