### ISSUE TITLE
what is EBUSY?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#8123]
In #126, there was a mention of EBUSY.

Not familiar with this, when exactly can a file be "busy"?

Is this a platform specific thing?

How to deal with this for backup source files?

**Comment by infectormp** [comment]
EBUSY  Device or resource busy (POSIX.1-2001)
https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_03

> [EBUSY]
> Resource busy. An attempt was made to make use of a system resource that is not currently available, as it is being used by another process in a manner that would have conflicted with the request being made by this process.

**Comment by infectormp** [comment]
https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html
> Macro: int EBUSY
> “Device or resource busy.” A system resource that can’t be shared is already in use. For example, if you try to delete a file that is the root of a currently mounted filesystem,  you get this error.

**Comment by infectormp** [comment]
https://linux.die.net/HOWTO/SCSI-Generic-HOWTO/open.html

**Comment by ThomasWaldmann** [comment]
#8127

**Comment by ThomasWaldmann** [comment]
#8127 #8128
