### ISSUE TITLE
Cannot get the permission to restore

### ISSUE THREAD

**Issue by sebbi08** [borgbackup/borg#8138]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.2.0

#### Operating system (distribution) and version.
Ubuntu

#### Hardware / network configuration, and filesystems used.

ext4 filesystem

#### How much data is handled by borg?

some MB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

on one machine
sudo borg create --list -x --compression lz4 --patterns-from /home/sebastian/patternfile.lst /mnt/fritz/Extreme_SSD/test::test

on the other machine
cd /
borg extract --list /mnt/fritz/Extreme_SSD/test::test1

## Describe the problem you're observing.

I create a backup one machine and tested the restoration on another by using a network storage.

But somehow I cannot get the permissions to be extracted correctly.
I have the same users on both machines with the same id's

But somehow on mashin2 where I extract, all the permission are set to the executing user.

I also tried the `--numeric-ids` option on both sides but it did not help.

The thing is when i do a `borg list --json-lines /mnt/fritz/Extreme_SSD/test::test1 > /home/sebastian/test.json`

i get 

```
{"type": "d", "mode": "drwxrwxr-x", "user": "sebastian", "group": "sebastian", "uid": 1000, "gid": 1000, "path": "home/sebastian/docker/changedetection", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2024-02-01T16:30:09.279711", "size": 0}
{"type": "-", "mode": "-rw-rw-r--", "user": "sebastian", "group": "sebastian", "uid": 1000, "gid": 1000, "path": "home/sebastian/docker/changedetection/docker-compose.yml", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2024-02-19T15:32:51.923985", "size": 1552}
{"type": "d", "mode": "drwxr-xr-x", "user": "root", "group": "root", "uid": 0, "gid": 0, "path": "home/sebastian/docker/changedetection/data", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2024-03-08T14:27:47.892573", "size": 0}
{"type": "-", "mode": "-rw-r--r--", "user": "root", "group": "root", "uid": 0, "gid": 0, "path": "home/sebastian/docker/changedetection/data/secret.txt", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2024-02-01T16:30:11.799725", "size": 64}
{"type": "-", "mode": "-rw-r--r--", "user": "root", "group": "root", "uid": 0, "gid": 0, "path": "home/sebastian/docker/changedetection/data/url-watches.json", "healthy": true, "source": "", "linktarget": "", "flags": null, "mtime": "2024-03-08T14:27:47.892573", "size": 3168}
```

But the permissions for the root folder/files are somehow dropped when extracting.

I already saw that there is an issue with partial extraction thats why i tested it with this "small" archive

anything i could have done wrong here?

**Comment by sebbi08** [comment]
I just tried to extract the archive on the same server i created it and there i also have the same problem

**Comment by ThomasWaldmann** [comment]
Only root can chown/chgrp the user/group of a file away from the current user.

So, for a "perfect" restore with all metadata, you need to run `borg extract` as root.

**Comment by sebbi08** [comment]
I already tried `sudo borg extract ...` but then everything will be assigned to root

**Comment by ThomasWaldmann** [comment]
That would be a bug - and I doubt that.

If you think there is a bug, write a simple, small reproducer script that demonstrates the problem.

**Comment by sebbi08** [comment]
ok, I found the problem when I run following as my user

```
sudo borg extract ... all will be set to root:root
borg extract .... all will be my user
```

But when I run it as root user, everything is fine.

```
sudo -s
borg extract ...

```
don't know if that is a bug or intended

**Comment by ThomasWaldmann** [comment]
Strange.

What borg extract does after extracting file contents is to chown/chgrp the file to the user/group stored in the archive.

If there are no permissions to do that (not running as root), it will silently ignore this (so the file will keep the current user / current user's group).

But if there are permissions, there shouldn't be an issue.

**Comment by goebbe** [comment]
@sebbi08 Could you provide more details/ information about your system? OS? 

On my synology NAS `sudo -su` is a bit differently from `sudo -su` on my LinuxMint laptop.  
Also sudo su uses a different environment (/root)  than sudo (/home/username).  Not sure if this could explain differences in the ownership when extracting.

**Comment by sebbi08** [comment]
It is a standard Ubuntu 22.04.4.

So I fixed it by doing `sudo -su` and then running the command.

Actually I did a small test run today with only sudo and that worked as expected :/ 

Maybe it was also just a "0 that got into a fight with another 1" don't know.
