### ISSUE TITLE
No easy way to tell what's excluded

### ISSUE THREAD

**Issue by edgewood** [borgbackup/borg#814]
It's easy to look over --list output to see that files being included are desired, but hard to see if I'm accidentally leaving something out with an overzealous regex, etc.   To do that I have to run a dry-run backup without the exclude options, do another run with the exclude options in place, then diff the file list output for the two runs.  Pretty annoying for initial setup, and very inefficient for ongoing monitoring of whether new files are being wrongly excluded.

I've changed the code locally to output excluded paths (with a 'x ' prefix) and updated the doc.  I can't decide whether it should be on by default, or controlled by a --show-excluded option, so I decided to ask before creating a test and opening a PR.

**Comment by enkore** [comment]
Sounds like a useful feature to me (especially since there are now multiple kind of patterns). An extra option is probably not needed (there is already --filter which works on status characters).

**Comment by ThomasWaldmann** [comment]
Yeah, sounds useful.

IIRC the dry-run mode uses "-" to signal that a file has not been backed up, maybe if it is not backed up due to exclude, it could use the same status char.

**Comment by enkore** [comment]
Sounds like a useful feature to me (especially since there are now multiple kinds of patterns). An extra option is probably not needed (there is already --filter which works on status characters).

(Somehow I managed to delete this comment before)

**Comment by edgewood** [comment]
I considered using '-'.  That works fine for regular create runs, but not in dry-run mode, since there's no information about why the path was excluded.  Dry-run is where I do initial testing of exclude changes.

I'm open to using a different code than 'x', but would prefer something distinct from '-'.

I'll create the test case and submit a PR.

-- 
Ed Blackman

**Comment by ThomasWaldmann** [comment]
OK, use x.

**Comment by edgewood** [comment]
Resolved by PR #815
