### ISSUE TITLE
Running command in hook on behalf of another user?

### ISSUE THREAD

**Issue by ostasevych** [borgbackup/borg#8147]
Hi! I use borgmatic for backing up certain apps, which I need to stop on behalf of the `www-data` user before and start after running the backup.

I've added a couple of hooks:
```
before_backup:
  - echo "`date` - Starting backup"`
  - apprise -c /etc/apprise.yaml -t "⚙ PREPARING" --tag=test
  - sudo - u www-data php /var/www/mycloud/myapp config:system:set maintenance --value=true

after_backup:
  - echo "`date` - Finished backup"`
  - apprise -c /etc/apprise.yaml -t "✅ DONE" --tag=test
  - sudo -u www-data php /var/www/mycloud/myapp config:system:set maintenance --value=false
```

When executed borgmatic reports that:
```
Mar 05 07:22:59 my.local borgmatic[1105519]: CRITICAL sudo: no valid sudoers sources found, quitting
Mar 05 07:22:59 my.local borgmatic[1105519]: CRITICAL sudo: error initializing audit plugin sudoers_audit
Mar 05 07:22:59 my.local borgmatic[1105519]: CRITICAL Command 'sudo -u www-data php /var/www/mycloud/myapp config:system:set maintenance --value=false' returned non-zero exit status 1.
```
Is it possible to use sudo in hooks somehow or what to use?

UPD:

The only workaround, which I've found is to replace the string variable manually:
```
before_backup:
    - /usr/local/bin/app-maint-on
```
where app-maint-on:
```
#!/bin/bash
# Enable maintenance mode in app
printf "1,$ s/'maintenance' => false/'maintenance' => true/g\nw! /var/www/mycloud/config/config.php\nq!" | ex - /var//www/nextcloud/config/config.php
```
But that is like a workaround, which doesn't allow me to process the exit code from the execution of the app command.

**Comment by infectormp** [comment]
The right place for this question is here https://projects.torsion.org/borgmatic-collective/borgmatic/issues

**Comment by ostasevych** [comment]
> The right place for this question is here https://projects.torsion.org/borgmatic-collective/borgmatic/issues

It is almost not possible to submit issues there :(
![image](https://github.com/borgbackup/borg/assets/5199030/a0680784-1322-4186-a848-6b202368bcf5)

**Comment by infectormp** [comment]
Are you experiencing an issue with borgmatic? Or do you have an idea for a feature enhancement? Head on over to our [issue tracker](https://projects.torsion.org/borgmatic-collective/borgmatic/issues). In order to create a new issue or add a comment, you'll need to [register](https://projects.torsion.org/user/sign_up?invite_code=borgmatic) first. If you prefer to use an existing GitHub account, you can skip account creation and [login directly](https://projects.torsion.org/user/login).
