### ISSUE TITLE
borg serve read-only mode

### ISSUE THREAD

**Issue by knutov** [borgbackup/borg#8158]
It seems now borg does not have "read-only mode" for `borg serve`.

There are cases like disaster recovery, limited access for 3rd parties, like security scans, ability to extract data by some superuser where any ability to add something to the repo is strictly unwanted.

Is it possible/ease to add this feature?

Is there way to achieve the same functionality via external tools, may be some wrappers?

**Comment by debuglevel** [comment]
Yes, that would be great :)

However, duplicates #4756
