### ISSUE TITLE
Static binary for OpenBSD/NetBSD missing

### ISSUE THREAD

**Issue by skarekrow** [borgbackup/borg#8190]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue. Either with the README or the builds.

## Describe the problem you're observing.
As shown [here](https://github.com/borgbackup/borg/blob/1.4-maint/README.rst?plain=1#L91), the 1.4.x releases should have a single binary available for these OS's. Possibly for 1.2.x as well? 

Thanks for the great project over the years!

**Comment by ThomasWaldmann** [comment]
Ehrm, that looks like a bug in the docs.

IIRC:
- we never offered a pyinstaller-made binary for anything else than linux, freebsd, macOS.
- pyinstaller does not support other platforms.

**Comment by ThomasWaldmann** [comment]
One needs to read precisely: it says `(no binaries yet)` there.

**Comment by skarekrow** [comment]
Well that gets a big l o l from me. My brain completely didn't parse that. Sorry for the noise!
