### ISSUE TITLE
[1.2.7] borg check -repair lacks a summarizing information at the end when it actually repaired something(s)

### ISSUE THREAD

**Issue by Wikinaut** [borgbackup/borg#8192]
borg 1.2.7 

The `borg check -repair` function ends in my case with:
```
1 orphaned objects found!
Archive consistency check complete, problems found.
```

Here I suggest in cases like mine - when check `borg check -repair` actually repaired something - to add saying "**and 1 problem/s repaired** (or $n problems repaired).

```
1 orphaned objects found.
Archive consistency check complete, problems found and 1 problem/s repaired.
```

**Comment by ThomasWaldmann** [comment]
duplicate of #2397.
