### ISSUE TITLE
Backup to Hetzner Storage Share no longer working

### ISSUE THREAD

**Issue by dipstick1987** [borgbackup/borg#8194]
I didn't create this thread but this is another person with the issue:
https://old.reddit.com/r/BorgBackup/comments/1c7f8on/borgbackup_no_activity/

Basically I have a BorgBackup setup via BorgMatic which was working fine for a few months and then I decided to cancel the Hetzner Storage Box. A few weeks later I set it up again with the same config but just a slightly different repo location. This seems to never finish. Healthchecks reports each morning that there is a lock file present so the scheduled backup couldn't work.

The directory on the box I am backing up is 1.1TB and the Hetzner box reports the same space used for the backup but the backup just never seems to end. If I reboot the box and delete the lock file the backup starts but once again never completes.

I am pretty new to BorgBackup so I don't know how to troubleshoot this and where some logs might be.
I'll see what I can do about finding a log file etc.

## Is this a BUG / ISSUE report or a QUESTION?
Issue

#### Your borg version (borg -V).
1.2.4

#### Operating system (distribution) and version.
Debian 12

#### Hardware / network configuration, and filesystems used.
Proxmox Backup Server, ZFS storage

#### How much data is handled by borg?
1TB-ish

**Comment by ThomasWaldmann** [comment]
Could be borg noticing the different, previously unknown repo location and asking you interactively whether you are sure that you want to use that repo.

I suggest you directly invoke borg commands (without any wrapper like borgmatic) to better see its output, like e.g. `borg list`. After that works, try again with borgmatic.
