### ISSUE TITLE
borg2: Creating archive fails at specific archive name

### ISSUE THREAD

**Issue by hermann4** [borgbackup/borg#8198]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE

#### Your borg version (borg -V).

borg2 2.0.0b5

#### Operating system (distribution) and version.

Debian Bookworkm

#### Hardware / network configuration, and filesystems used.

Local Filesystem: Ext4, Archived to a locally mounted webdav directory

#### How much data is handled by borg?
50GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

sys.argv: ['/usr/bin/borg2', 'create', '-r', '/home/johndoe/backup/webdav/bu/backup/', '29-04-24-07:04:01', '/home/johndoe/backup/onedrive/']

## Describe the problem you're observing.

When execeuting the backup at times with uneven hours (as seen above, or 09:00...) it crashes with the following error: 
`ValueError: unknown hashindex magic: b''`

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Problem can be reproduced, if I either change the time to an even value the backup works, also if the ":" are replaced with "-" in the archive name the backup works even with uneven times

#### Include any warning/errors/backtraces from the system logs

**Comment by infectormp** [comment]
could you please post the full stack trace here?

**Comment by hermann4** [comment]
Cannot reproduce the behaviour i had yesterday as it is working now. Creating an archive with the name is possible today, so maybe a problem with the mount as you mentioned
