### ISSUE TITLE
Please add a way to keep backups independently of pruning retention policy

### ISSUE THREAD

**Issue by LaurentBonnaud** [borgbackup/borg#8205]
Hi,
I am using `borg prune` to reduce the disk space used by my backups.
I would like to be able to mark some backups as "not prunable" so that they are excluded from the daily/weekly/monthly retention policy that I defined.
My use case for this new feature is to keep a last backup of my system before a major OS upgrade.  Those upgrades are done at a point in time that is unrelated to weeks and months.
Thank you for considering this suggested addition!

**Comment by LaurentBonnaud** [comment]
This feature request is related to issue #846, but is more limited in scope and should be easier to implement.

**Comment by ThomasWaldmann** [comment]
borg2: see #953.

**Comment by LaurentBonnaud** [comment]
Thanks for the suggestion!
And thanks for borg2, that will be awesome!

**Comment by LaurentBonnaud** [comment]
Thanks for the fix!
