### ISSUE TITLE
`borgfs` in Standalone Binary Installation Docs

### ISSUE THREAD

**Issue by gitspeaks** [borgbackup/borg#8207]
I noticed a potential issue in the [Standalone Binary installation section](https://borgbackup.readthedocs.io/en/1.2-maint/installation.html#standalone-binary) of the documentation where it suggests creating a symlink to make `borgfs` an alias for `borg mount`

Quote:

> Optionally you can create a symlink to have borgfs available, which is an alias for borg mount:
> 
> ```bash
> ln -s /usr/local/bin/borg /usr/local/bin/borgfs
> ```

A symlink to `borg` will just replicate the `borg` command under a new name, `borgfs`, but does not restrict or modify its behavior to only execute `borg mount`.

The documentation might consider suggesting the use of a shell alias or a wrapper script instead. 

For example:

```bash
alias borgfs='borg mount'
```

**Comment by ThomasWaldmann** [comment]
Usually that works, borg internally detects the name by which it was invoked and then behaves differently.

Try:
- the single file fat binary
- the directory based fat binary
- the normal borg package (e.g. via pip install borg or linux dist package)

If one or more of these does not behave like "borg mount" when invoked as `borgfs`, please add which of these exactly to your original bug report.

**Comment by gitspeaks** [comment]
Thanks for the clarification! I've tested it and you're right, it works as expected. I suggest adding a note to the documentation explaining that Borg internally detects the name by which it was invoked and adjusts its behavior accordingly. This isn't immediately apparent, and such a note would help clarify why creating a symlink serves as a functional alias.
