### ISSUE TITLE
Remote backup support.

### ISSUE THREAD

**Issue by renard** [borgbackup/borg#822]
I just discovered borg and it seems to be a good backup system.

I actually use duplicity for large binary files and borg can be an alternative for it.

The good point of duplicity is the large amount of remote backup support such as:

* Azure
* B2
* Cloud Files (Rackspace)
* Copy cloud storage
* Dropbox
* Local file path
* FISH (Files transferred over Shell protocol) over ssh
* FTP
* Google Docs
* Google Cloud Storage
* HSI
* hubiC
* IMAP email storage
* Mega cloud storage
* OneDrive Backend
* Par2 Wrapper Backend
* Rsync via daemon
* Rsync over ssh (only key auth)
* S3 storage (Amazon)
* SCP/SFTP access
* Swift (Openstack)
* Tahoe-LAFS
* WebDAV
* pydrive

(see http://duplicity.nongnu.org/duplicity.1.html)

It there a plan to support such remote storages in borg?

Thanks.

**Comment by ThomasWaldmann** [comment]
There is already a amazon S3 related ticket, see there for some background: #102

In short words: not any time soon.

**Comment by infectormp** [comment]
* Local file path - already supported
* FISH (Files transferred over Shell protocol) over ssh -  - already supported via sshfs

**Comment by enkore** [comment]
For many of these there are FUSE file systems. But please do realize that some of these services and file systems don't work like a normal file system and have much weaker guarantees for consistency and other things. Which means that e.g. locking might not work as expected, or is sometimes unreliable -- not good when running concurrent jobs.

Some people report that it works for them.

btw. rsync.net offers a deeeep discount for Borg users (0.03 $/GB/mo) and just works™.

**Comment by ThomasWaldmann** [comment]
"locking" for borg is not "file locking" (like posix file locking), but just a (supposed to be atomic) mkdir call. either succeeds (we got the lock) or fails (someone else has the lock).

**Comment by ThomasWaldmann** [comment]
@renard can you maybe group them by "using proprietary protocol" (and being the only provider offering it) vs. "using standard protocol".

**Comment by renard** [comment]
@infectormp sure, I was just listing all remote supported by duplicity.

@enkore FUSE like solution are not portable thus not reliable on every system as you said. Even at $0.03/mo/GB this is more expensive than HubiC (50€/y for 10Tb)

@ThomasWaldmann All protocols here are available using python modules (I didn't dig deep enough for the internals) thus can be considered as standard protocols.

**Comment by ThomasWaldmann** [comment]
I don't consider it as a standard if only implemented by 1 provider.

**Comment by enkore** [comment]
> @enkore FUSE like solution are not portable thus not reliable on every system as you said. Even at $0.03/mo/GB this is more expensive than HubiC (50€/y for 10Tb)

A user here reported he uses FUSE on HubiC, and that it's throttled to 1 MB/s. I.e. you would spend half that year constantly uploading to fill those 10 TB. As I said above... ;)

> btw2. services which offer "unlimited XYZ" for free or at a very low price are usually soft-limited, e.g. very low bandwidth. ymmv.

**Comment by renard** [comment]
Ok fair enough.
Was looking if borg could be a reliable solution, I guess it won't for me
Good luck guys.
