### ISSUE TITLE
add --progress switch to borg check

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#824]
people run borg check from cron script and do not want the "Checking segments ..." output in the log (from borgbackup ML).

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/32498620-add-progress-switch-to-borg-check)

**Comment by ThomasWaldmann** [comment]
Problem: for remote repositories, passing progress=True/False to repo.check() would need a rpc change.

**Comment by enkore** [comment]
faheem (IRC) sparked the idea (kind of) that we could just push the ProgressIndicatorPercent over the normal logging infrastructure and have it use --info level or below. Would not break RPC.

**Comment by ThomasWaldmann** [comment]
@edgewood is this fixed?

**Comment by edgewood** [comment]
Fixed by #865.  The reference must have gotten lost in the squash.

**Comment by rom1v** [comment]
Could it be possible to enable `--progress` by default for `borg check` (and maybe other commands)?

Executing `borg check --verify-data` and getting absolutely no feedback is very confusing. (does it work? is it frozen?)

**Comment by ThomasWaldmann** [comment]
Please no discussions in issues that were closed 5y ago. If you want to file an issue, file a new one.
