### ISSUE TITLE
`import-tar` doc actually explains `export-tar`

### ISSUE THREAD

**Issue by rakoo** [borgbackup/borg#8252]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Documentation issue

---
Hey there,

The documentation for the `import-tar` command (https://borgbackup.readthedocs.io/en/stable/usage/tar.html) actually contains description, example and everything from `export-tar`:

"This command creates a backup archive from a tarball."

(It's probably because both actually have the same url ?)

**Comment by ThomasWaldmann** [comment]
The page contains the descriptions for both `import-tar` and `export-tar`, each under an own headline.

**Comment by felixschndr** [comment]
> The page contains the descriptions for both `import-tar` and `export-tar`, each under an own headline.

Same as with `borg key`: https://borgbackup.readthedocs.io/en/stable/usage/key.html

**Comment by rakoo** [comment]
Oh shoot I should have drank my coffee. Sorry !
