### ISSUE TITLE
Borg 1.4.0 FreeBSD fat binary on FreeBSD 13.2

### ISSUE THREAD

**Issue by Nikoos** [borgbackup/borg#8266]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

## System information. For client/server mode post info for both machines.
FreeBSD 13.2 in jail

#### Your borg version (borg -V).
`borg 1.2.8`

#### Operating system (distribution) and version.
TrueNAS 13.0 with FreeBSD 13.2 jail

#### Hardware / network configuration, and filesystems used.
Not relevant in this case

#### How much data is handled by borg?
Not relevant in this case

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
Not relevant in this case

## Describe the problem you're observing.
I download the Borg 1.4.0 FreeBSD binary on my jail and try to run, unfortunately, the following message appeared : 

```
root@borg-backup:/tmp # ./borg-freebsd
ld-elf.so.1: /tmp/borg-freebsd: Undefined symbol "__libc_start1@FBSD_1.7"
```

(I kept the previous version), After checking info on this binary, file command confirmed me that this binary is built for FreeBSD14 : 

```
root@borg-backup:/tmp # file borg-freebsd
borg-freebsd: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 14.0 (1400097), FreeBSD-style, stripped
```

If I perform the same operation on a previous version : 

```
root@borg-backup:/tmp # file borg-freebsd64
borg-freebsd64: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 13.2, FreeBSD-style, stripped
```

I was not able to found in the documentation if FreeBSD 13 is out of support for Borg, would you confirm me if FreeBSD 13.2 is out of support ?

Thanks for your support

Best regards,

**Comment by ThomasWaldmann** [comment]
I switched the build system to freebsd 14 for borg 1.4, see also the 00_README.txt that comes with the binaries.

I am not very familiar with fbsd - do you think a lot of users are still on 13?

**Comment by Nikoos** [comment]
Thanks for the inputs.

To be honest, it's a difficult question that I am not able to answer. In my personal case, I am limited to my main TrueNas os version (built on top of FreeBSD 13.0 and the upcoming beta will be built on top of FreeBSD 13.3 if I am correct).

**Comment by ThomasWaldmann** [comment]
OK, so it seems there are at least all the TrueNAS users.

Guess I'll add a fbsd13 build box.

**Comment by Nikoos** [comment]
Thanks @ThomasWaldmann for your help

**Comment by ThomasWaldmann** [comment]
Hmm, it's not as easy as I thought.

The code does not compile on freebsd 13 due to using `acl_extended_link_np` to determine whether a file has ACLs beyond what the normal user/group/mode bits can express.

I am closing this issue and opening a special one about that.

**Comment by mikae1** [comment]
> I am closing this issue and opening a special one about that.

Is there a new issue for this? Can't see a link for it. Sadly I'm also unable to use borg with TrueNAS now that the build is for FreeBSD 14 only.

**Comment by ThomasWaldmann** [comment]
@mikae1 See #8269.

**Comment by mikae1** [comment]
> @mikae1 See #8269.

Thanks!
