### ISSUE TITLE
Large size of segments lead to significantly larger transfer size

### ISSUE THREAD

**Issue by woodholly** [borgbackup/borg#8271]
Borg segment size is 500M. Any change (even 1 bit) in data leads to 500M changes/writes to borg backup files, if encryption used. This significantly increases time of backup, degrade SSD disks and leads to larger transfer times, when copying backup over the network to other host.
The solution is to decrease segment size to a reasonable value, is it possible ?
For example, incremental backup of 6Gb in size leads to 20Gb network transfers (and writes to disk), 3x.

**Comment by RonnyPfannschmidt** [comment]
I presume this was written without actual understanding of how borg uses segments 


They're only appended to when creating new backups 

Compaction and removal don't rewrite but discard file parts

**Comment by ThomasWaldmann** [comment]
@woodholly The 500MB segment size was optimised for local storage. For remote repos it can have advantages in some cases to decrease the max. segment size, but not quite how you think it would.

> Any change (even 1 bit) in data leads to 500M changes/writes to borg backup files, if encryption used.

No, not true. As ronny already remarked, data is appended.

> The solution is to decrease segment size to a reasonable value, is it possible?

Sure, see the repo config. You could try 10MB .. 50MB and do some benchmarks.

> For example, incremental backup of 6Gb in size leads to 20Gb network transfers (and writes to disk), 3x.

Did you measure that or where do the numbers come from? Is that a ssh:// remote repo or a network file system like nfs or samba or ...?


@RonnyPfannschmidt Compactions reads the old segment file and writes a new one only with the not-deleted entries, leaving out the deleted entries.

In general, I guess the biggest effect reducing max segment size would have is on compaction (when it copies used entries from old to new segments). But that compaction is done on the **repo server side**, so it's not network traffic, but server-local storage I/O. Also, there is a threshold, to avoid compacting segments if there isn't much space to save.

**Comment by woodholly** [comment]
If it just appends new data, then I don't understand why this increase in network transfer happens, can you explain that ?
>Did you measure that or where do the numbers come from? Is that a ssh:// remote repo or a network file system like nfs or samba or ...?

Yes that is how I found this. One of incremental backups info:
```
Original size      Compressed size    Deduplicated size
This archive:              105.17 GB             67.26 GB              10.75 GB
```
I rsync borg files daily to other server using rsync. This is data from rsync for that day:
```
sent 19,487,563,866 bytes  received 1,186 bytes  9,640,150.90 bytes/sec
```
So 10.75Gb of deduplicated data turned into 19Gb data transfer. Rsync only transfers changes, so borg has written all this new data to disk.

**Comment by infectormp** [comment]
Could you measure (using linux tools) the archive size before and after the backup, and then check how much data was transferred using rsync? 

It would also be good if you post your rsync command here.

**Comment by woodholly** [comment]
@infectormp today size of borg files: 326G, we will see tomorrow

**Comment by woodholly** [comment]
I use borg compact each run, so compact modifies segment 500M files entirely ?

**Comment by ThomasWaldmann** [comment]
@woodholly borg never modifies segment files after they were initially written and closed.

But, as I said above, borg compact reads old non-compact segment files (that have unused, deleted entries in an amount beyond the compaction threshold) and rewrites them to new segment files that are compact.

**Comment by woodholly** [comment]
Now I see why this happens. My solution is to decrease segment size to 4M and compaction threshold to 100% (never rewrite to new segment, just delete unused). Is it possible ?

**Comment by ThomasWaldmann** [comment]
As I already said, first thing to try is to run `borg compact` less often.

Only if that does not solve your problem already, then reduce max segment size to 10MB..50MB and play with the threshold (and don't use insane values for the threshold or will likely never compact anything).

**Comment by jdchristensen** [comment]
@woodholly Also, if it's possible for you, then you should have borg connect directly to the repo on the remote host, rather than working on a local repo and then copying it with rsync.  Then tasks like compacting the repo would happen on the server, and wouldn't require data transfer over the network.

**Comment by woodholly** [comment]
Thanks guys, reading https://borgbackup.readthedocs.io/en/stable/internals/data-structures.html helped me to understand that this is can't be fixed by design.
