### ISSUE TITLE
FreeBSD porting: question about llfuse < 1.0 requirement

### ISSUE THREAD

**Issue by jjuanino** [borgbackup/borg#828]
Hi,

I am trying to port this great software to FreeBSD, and have a question about llfuse dependency. 

According to setup.py:

```
extras_require = {
    # llfuse 0.40 (tested, proven, ok), needs FUSE version >= 2.8.0
    # llfuse 0.41 (tested shortly, looks ok), needs FUSE version >= 2.8.0
    # llfuse 0.42 (tested shortly, looks ok), needs FUSE version >= 2.8.0
    # llfuse 1.0 will break API
    'fuse': ['llfuse<1.0', ],
}
```

Currently, the FreeBSD port system provides llfuse=1.0 version. I have tested borg with 1.0 version of llfuse and works well. Is llfuse<1.0 a real requiremente or it could be avoided? 

Congratulations for develop this great software!

Regards

**Comment by ThomasWaldmann** [comment]
The comments you quoted are already different in latest code, see github master or 1.0-maint branch.
