### ISSUE TITLE
Disable cache with environment variable/CLI option

### ISSUE THREAD

**Issue by tomchiverton** [borgbackup/borg#8280]
This would be easier than the workaround listed in the FAQ till #474 is done.

**Comment by ThomasWaldmann** [comment]
What @tomchiverton means is the chunks.archives.d/ cache, which can use quite a lot of disk space for some repos (with many archives).

That cache is used to speed up the resync (rebuild) of the master chunks index, but is not required (if it is not used, borg fetches all infos from the repo if a chunks index resync is needed).
