### ISSUE TITLE
can we make the RPC interface more flexible?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#829]
RPC interface changes are currently problematic as users might run different versions of borg on client and server.

Adding a parameter to a remote procedure call currently needs changing server as well as client.

Maybe the RPC mechanism could be done in a way so that minor differences are just ignored.
- if client passes more parameters than server wants: just ignore them
- if server wants more parameters than client gives: use defaults

If we implement such a change, it might be by itself a RPC change and not compatible to previous RPC interface, but at least it would make it easier in future.

---

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/32543024-can-we-make-the-rpc-interface-more-flexible)

**Comment by ThomasWaldmann** [comment]
Example: #824 (would be easy to fix without this rpc issue)

**Comment by enkore** [comment]
We could also consider using one of the available RPC libraries, some of which handle details like these. Our requirement of communicating over a pipe, instead of a socket, probably eliminates many candidates, though.

**Comment by ThomasWaldmann** [comment]
Well, that's the point: I don't want to multiply protocol code.

**Comment by FelixSchwarz** [comment]
I'm a bit sceptical if ignoring parameters will be always harmless. Could cause nasty surprises (e.g. "--exclude" dropped). IMHO the right(tm) way to do it is that the client+server first exchange their supported protocol versions to agree on the version to use (usually the client would select the best protocol). However I guess you're much better qualified to choose the "best" approach for borg.

Btw I really appreciate your attempt to support different versions for client+server. This is a super annoying thing with bacula for example.

**Comment by Ape** [comment]
Could the client be very thin, i.e. only proxy all commands to the server and let the server to everything, including argument parsing? That way it would be enough to upgrade the server to a new version with some new command options and the thin client would be able to use them automatically (without upgrading the client).

**Comment by textshell** [comment]
As it is hard to speculate how much work a suggestion in some complex unfamiliar code is i just tried what a more flexible RPC based on named parameters but still sharing almost everything else with the old RPC would look like.
Result in #1419

**Comment by ThomasWaldmann** [comment]
Fixed by #1419. Claim the bounty. :)
