### ISSUE TITLE
borg2 commands: use repo-*, not r*

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#8292]
https://github.com/borgbackup/borg/discussions/7647 as discussed / voted there (voting is / will be open until this ticket is close, so in case you missed it, you can still vote there).

Current state of repo-level commands:
```
borg rcreate
borg rlist
borg rinfo
borg rdelete
...
```

Change to:
```
borg repocreate
borg repolist
borg repoinfo
borg repodelete
...
```

**Comment by ThomasWaldmann** [comment]
@m3nu @sophie-h @witten See above, guess b10 would be a good time for that change.

As we only want to change that once and then keep it for borg2 for a long time, just wanted to ask if we are all fine with `repo-*` instead of the `r*` commands or would you prefer `repo*` without the dash?

**Comment by m3nu** [comment]
`repoxxx` looks good to me.

**Comment by witten** [comment]
Either repo* or repo-* will be the same amount of work (a fair amount, actually!) from borgmatic's perspective. Looking at it as a user though, I might have a slight preference for repo*. (Easier to type.)

**Comment by RonnyPfannschmidt** [comment]
I strongly recommend dashes as readability is so much better with a little visual clue

**Comment by ThomasWaldmann** [comment]
@RonnyPfannschmidt same here (and also that editors like pycharm see words like repocreate as mis-spelled and underline them in red, but are fine with repo-create).

**Comment by ThomasWaldmann** [comment]
OK, we'll go with `repo-*`.

It's a bit more to type (but repo-level commands are a bit less frequent than archive level), but reads better.
