### ISSUE TITLE
Cold Archive Backup

### ISSUE THREAD

**Issue by Mezalor** [borgbackup/borg#8296]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).

borg 1.4

#### Operating system (distribution) and version.

Linux

## Describe the problem you're observing.

I would like to use Borg to regularly back up my data to a cold archive service. The problem is that I cannot quickly access my archived data. Is there a way to save just the metadata (hashes?) locally to enable calculating the data to be incremented in the next backup?

**Comment by ThomasWaldmann** [comment]
borg directly supports only backing up into a directory (on a locally mounted filesystem) or via ssh onto a remote server that has borg installed.

What some people do is to use some other tool to upload their borg repository to somewhere else. For that, you need to upload all the repository contents **while the repo is not used by borg** (e.g. by using `borg with-lock your-upload-tool ...`).

There is no support for separating borg metadata and data.

**Comment by Mezalor** [comment]
Ok I understand that it is better to keep a copy of the backup locally before pushing it to a Cold Storage.
Thanks for the answer
