### ISSUE TITLE
[Feature Request] Disable the YES prompt when BORG_CHECK_I_KNOW_WHAT_I_AM_DOING is enabled

### ISSUE THREAD

**Issue by dertuxmalwieder** [borgbackup/borg#8297]
My current Borg setup includes a cronjob that executes `prune` and `compact` once a day. With 2.0.0 b9 the necessity of `borg check` was introduced for this. Now `borg check` has the *disadvantage* that a separate query is made as to whether I ‘really want this’, which is of course impractical in a cronjob. Deactivating this query via `BORG_CHECK_I_KNOW_WHAT_I_AM_DOING=YES` does not make the query disappear, however, so that I receive an e-mail with several confirmed queries every day. In my opinion, this makes no sense.

My current workaround is to append `> /dev/null 2>&1` to the cronjob, but this is inelegant. A more elegant solution would be good.

**Comment by ThomasWaldmann** [comment]
Hmm, guess this is solved. borg2 now just needs the usual prune + compact, no borg check requirement anymore.
