### ISSUE TITLE
cython / c / ctypes mix

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#83]
Feedback by waldi - can / should we simplify?

Notes: the only ctypes stuff is in module xattr (everything else is Python/Cython/C).

See also #113 and #142.

**Comment by RonnyPfannschmidt** [comment]
shouldn't going for stdlib xattr fix the ctypes problem?

**Comment by ThomasWaldmann** [comment]
yes, added a pointer to #142.

**Comment by ThomasWaldmann** [comment]
As there is no pressing need to change this (like removing ctypes usage) and also this is not causing any issues, I tend to close this as wontfix except if somebody brings up any further information.

**Comment by ThomasWaldmann** [comment]
see above.
