### ISSUE TITLE
--dry-run would be useful for 'borg compact'

### ISSUE THREAD

**Issue by yrro** [borgbackup/borg#8300]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature request

## Describe the problem you're observing.

`--dry-run` isn't available for `borg compact`.

My wrapper script has to handle this by skipping the execution of `borg compact` when in dry run mode, rather than adding `--dry-run` to the borg command line. No big deal, but it would be nice if this option was present for `compact` as it is with `create`/`prune`.

**Comment by ThomasWaldmann** [comment]
Interesting idea for making scripting a bit easier.

I have to check whether a `borg compact --dry-run` can be doing anything useful (like e.g. saying how much it would compact/free) with actually doing it.
