### ISSUE TITLE
"Completely healed previously damaged file!" does not go away

### ISSUE THREAD

**Issue by sshaikh** [borgbackup/borg#8302]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes. Relevant issue found here: https://github.com/borgbackup/borg/issues/5747

## Is this a BUG / ISSUE report or a QUESTION?

A bug, assuming I have understood correctly.

#### Your borg version (borg -V).

```
$ borg -V
borg 1.4.0
```

#### Operating system (distribution) and version.

```
$ uname -a
Linux nas 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
```

#### Hardware / network configuration, and filesystems used.

Local repo on ext4. The same backup is performed against a remote repo, but that doesn't show these messages.

#### How much data is handled by borg?

Around 200GB in the backup.

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

`$ sudo borg check -v -p --repair  <repo>`

## Describe the problem you're observing.

I see the following for a single file, across some (but not all) archives.

```
Analyzing archive 2024-07-11T23:00:02.853989 (99/115)
nas-2024-07-11T23:00:02.853989: 5823.MP4: Healed previously missing file chunk! (Byte 61750682-63655426, Chunk d2bbcdf512be74b6416afdd4e5949145204a112ec4c3cbcd8a562e0f419ae908).
nas-2024-07-11T23:00:02.853989: 5823.MP4: Completely healed previously damaged file!
Analyzing archive 2024-07-12T23:00:03.401070 (100/115)
nas-2024-07-12T23:00:03.401070: 5823.MP4: Healed previously missing file chunk! (Byte 61750682-63655426, Chunk d2bbcdf512be74b6416afdd4e5949145204a112ec4c3cbcd8a562e0f419ae908).
nas-2024-07-12T23:00:03.401070: 5823.MP4: Completely healed previously damaged file!
Analyzing archive 2024-07-13T23:00:02.822753 (101/115)
nas-2024-07-13T23:00:02.822753: 5823.MP4: Healed previously missing file chunk! (Byte 61750682-63655426, Chunk d2bbcdf512be74b6416afdd4e5949145204a112ec4c3cbcd8a562e0f419ae908).
nas-2024-07-13T23:00:02.822753: 5823.MP4: Completely healed previously damaged file!
...
Archive consistency check complete, no problems found.
```

My understanding is that subsequent repairs should eventually leave these messages behind.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, this occurs each time I run the `check` command.

**Comment by ThomasWaldmann** [comment]
Weird, just to clarify:

So you run `borg check --repair` **multiple times on the same repo** and it is always the same chunk id, the same archive names and file name?

Are there other commands in between the check commands that access the repo?

Does the `borg check --repair` command finish successfully or could it be that it abnormally terminates after it emitted these log messages? Any tracebacks?

Did you create the repo freshly for borg 1.4 or did you upgrade from 1.2.x?

If you upgraded, did you follow the CVE-related upgrade steps at the top of the changelog? Did the repo show strange messages while you used it with borg 1.2.x?

**Comment by sshaikh** [comment]
I just ran it for the fourth time and it seems to now be completing okay, without the messages. Previously "healed" messages would have been printed for the same file across checks, although I cannot say if the chunks and archives were the same.

The checks always ended successfully.

I have been running the checks sequentially, but over time. The only thing I can think of is that between previous `check` runs, a backup might have been run by another process.

I did upgrade, and I did follow the upgrade steps. That said, my repo was in an apparently bad state before upgrade (and required repair).

I do not get any other messages apart from the healing ones. Some superseded chunks were deleted.

Once this check ends, I'll run a backup and check again.

I'll

**Comment by ThomasWaldmann** [comment]
One suspicion that came into my mind that could explain what you were seeing:

If your hardware has issues (esp. RAM issues), it could corrupt the chunk ids in memory and thus not find chunks anymore which it already had, repeatedly.

So, I'ld run memtest86+ on that client machine at least.

**Comment by ThomasWaldmann** [comment]
I checked our tests: we actually have a test that checks the "healing" borg can do.

I just extended that test a bit to check for the symptoms you had encountered: it works correctly for me.

**Comment by sshaikh** [comment]
Thanks for the attention. It seems to have passed the checks twice now after backing up, so happy to put this down to user error. I'll reopen if I see this again.
