### ISSUE TITLE
Borg on windows (ssh) crashes with FD exception error

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [borgbackup/borg#8305]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Bug /issue

## System information. For client/server mode post info for both machines.

Windows

#### Your borg version (borg -V).
borg 1.0.11
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes, install borg on windows, and try a simular command to mine where you attempt to use SSH
`borg create spiderunderurbed@authentik.spidershomelab.xyz:/hdds/Seagate/backups/windows::FIRST C:\Users\SpiderUnderUrBed.DaSpiderCave\Downloads`

#### Include any warning/errors/backtraces from the system logs
`PS C:\Users\SpiderUnderUrBed.DaSpiderCave> borg create spiderunderurbed@authentik.spidershomelab.xyz:/hdds/Seagate/backups/windows::FIRST C:\Users\SpiderUnderUrBed.DaSpiderCave\Downloads
Local Exception.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 2168, in main
    exit_code = archiver.run(args)
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 2104, in run
    return set_ec(func(args))
  File "/usr/lib/python3.6/site-packages/borg/archiver.py", line 94, in wrapper
    lock_wait=self.lock_wait, lock=lock, append_only=append_only, args=args)
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 234, in __init__
    version = self.call('negotiate', RPC_PROTOCOL_VERSION)
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 322, in call
    for resp in self.call_many(cmd, [args], **kw):
  File "/usr/lib/python3.6/site-packages/borg/remote.py", line 374, in call_many
    raise Exception('FD exception occurred')
Exception: FD exception occurred

Platform: CYGWIN_NT-10.0 DaSpiderCave 2.8.2(0.313/5/3) 2017-07-12 10:58 x86_64
Borg: 1.0.11  Python: CPython 3.6.1
PID: 28180  CWD: /c/Users/SpiderUnderUrBed.DaSpiderCave
sys.argv: ['/bin/borg', 'create', 'spiderunderurbed@(censored):/hdds/Seagate/backups/windows::FIRST', 'C:UsersSpiderUnderUrBed.DaSpiderCaveDownloads']
SSH_ORIGINAL_COMMAND: None`
<!--

If this complaint relates to borg performance, please include CRUD benchmark
results and any steps you took to troubleshoot.
How to run benchmark: http://borgbackup.readthedocs.io/en/stable/usage/benchmark.html

*IMPORTANT* - Please mark logs and text output from terminal commands 
or else GitHub will not display them correctly. 

Additional info:
Python 3.12.4 

FD exceptions occurred before when using ssh that was mentioned in #947 although this seems somewhat diffrent, I was wondering if there is any fix for me

**Comment by infectormp** [comment]
Wow. Your borg version is rather old. Please update and try to reproduce this issue.

**Comment by ThomasWaldmann** [comment]
Yup, my thoughts. 🤣

Before you update borg, also update your python, so you have a python version that is supported by the borg release. E.g. borg 1.2.8 needs python >=3.8.

**Comment by SpiderUnderUrBed** [comment]
Is there any exe or instructions from source compilation I can follow to get borg working on windows. I followed the instructions from a really old port of borg. I don't fancy using WSL or docker.

**Comment by ThomasWaldmann** [comment]
The borg docs are there: https://borgbackup.org/ and the install docs have sections for Linux (should be also good for WSL) and Cygwin.

**Comment by SpiderUnderUrBed** [comment]
Ok, I am aware of the docs and how you can run it via cygwin or WSL, I guess I will reconsider if I want to use it on windows via these methods, but WSL and Cygwin has some overhead, so I wanted to ask about how the native port was going? I thought the issue and all relevant PR's were closed but it hasn't been merged into the master branch. 

I assumed the windows branch worked however but I couldn't find instructions on how to compile the windows branch. But given its unmaintained I guess the WSL and Cygwin is the way to go. 
(I will close this issue shortly)
