### ISSUE TITLE
[ feature request ] Single binary. No depenencies. Migrate to Rust or Go.

### ISSUE THREAD

**Issue by yonas** [borgbackup/borg#8309]
Granted, I'm trying to install the latest dev (2.0.0b9) and not a stable version. But even so, the install experience is horrible:

```sh
$ apk add py3-pip
$ python3 -m venv .
$ . ./bin/activate
() / $ pip install borgbackup==2.0.0b9
Collecting borgbackup==2.0.0b9
  Downloading borgbackup-2.0.0b9.tar.gz (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 17.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-dj24qfbw/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 91, in _wrapper
          return func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dj24qfbw/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 125, in exists
          return call(cmd) == 0
                 ^^^^^^^^^
        File "/usr/lib/python3.12/subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "//lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "//lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "//lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dj24qfbw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dj24qfbw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dj24qfbw/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 145, in <module>
        File "<string>", line 127, in lib_ext_kwargs
        File "/tmp/pip-build-env-dj24qfbw/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 198, in installed
          if not exists(package):
                 ^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-dj24qfbw/overlay/lib/python3.12/site-packages/pkgconfig/pkgconfig.py", line 93, in _wrapper
          raise EnvironmentError("pkg-config probably not installed: %r" % e)
      OSError: pkg-config probably not installed: FileNotFoundError(2, 'No such file or directory')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I had to install many dev packages to proceed:

- acl-dev [ auto-installed via [crates](https://crates.io/crates/posix-acl) ]
- gcc [ auto-installed via the cargo package ]
- libacl [ auto-installed via [crates](https://crates.io/crates/posix-acl) ]
- libxxhash [ auto-installed via [crates](https://lib.rs/crates/xxhash-rust) ]
- linux-headers [ obsoleted ]
- lz4-dev [ auto-installed via [crates](https://lib.rs/crates/xxhash-rust) ]
- musl-dev [ auto-installed via the cargo package ]
- openssl-dev [ replaced by rustls ]
- pkgconf [ obsoleted ]
- py3-pip [ replaced by cargo ]
- python3-dev [ replaced by cargo ]
- xxhash-dev [ auto-installed via [crates](https://lib.rs/crates/xxhash-rust) ]
- zstd-dev [ auto-installed via the cargo package ]

Borg should migrate to Rust or Go. Compiling should be as simple as `apk add cargo ; cargo build --release`.

### Additional benefits
- much faster
- memory safe

**Comment by infectormp** [comment]
It's normal to install dev packages if you build it from the source. I you need a single binary you can get it here https://github.com/borgbackup/borg/releases under assets section.

**Comment by yonas** [comment]
> It's normal to install dev packages if you build it from the source. 

In the C, C++, and Python programming environment, yes. Not in Rust, and somewhat not in Go either.

> If you need a single binary you can get it here https://github.com/borgbackup/borg/releases under assets section.

Thanks, but what if github.com is down? What if I have the source code and no Internet connection?

**Comment by infectormp** [comment]
> Thanks, but what if github.com is down? What if I have the source code and no Internet connection?

О! In that case, you need to implement BCM (Business continuity management) process in your work. 
First, conduct a BIA (Business Impact Analysis) to assess the criticality of your business processes, and then develop mitigation measures for processes and systems that depend on internet or github availability.

**Comment by ThomasWaldmann** [comment]
@yonas This is a Python project, we won't switch everything to Rust or Go.

But if you'ld rather like to use something implemented in Go, you could use `restic`.

About installing borg / install experience:

- the most convenient way is to use a (linux or other) dist package - then all requirements are pulled in automatically by the package manager tool (e.g. apt or rpm) and updates (e.g. security or severe bugs) are usually also automatic or easy.
- if you are using the bleeding edge stuff (like you did with doing a pip install of the latest beta), reading the docs and some python tools experience is required.
- there's also the fat binary, as @infectormp already pointed out with all requirements included. you still should read the changelog though.

BTW, I agree that such a traceback as in top post is **not pretty**. A simple error msg, like "pkg-config not found" would be prettier.

But OTOH, such a traceback **contains a lot more information** than a simple error msg that can be very useful for developers and advanced users.

**Comment by ThomasWaldmann** [comment]
Closing this as `wontfix`. I opened #8313 as a different approach to this.
