### ISSUE TITLE
document TIMESPAN

### ISSUE THREAD

**Issue by dtugend** [borgbackup/borg#8310]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

missing documentation

## Describe the problem you're observing.

Please consider to document TIMESPAN that is used in various places e.g. here:
https://borgbackup.readthedocs.io/en/master/usage/general.html#date-and-time

I checked the actual code (thankfully that's possible ❤️), to be sure if 12m means 12 months (which it does) or if it means 12 minutes (which it does not).

I could try to make a pull request with changes in .rst format, if it helps more than it hurts, but I don't understand the "man" format enough yet.

**Comment by ThomasWaldmann** [comment]
Yup. If you invoke it with --help it refers to "7d or 12m" as an example in the option's help.

Thought that would be clear enough to mean 7 days and 12 months, but of course we can add it to the docs to clarify it.

**Comment by ThomasWaldmann** [comment]
Only the .rst or .py needs updating, everything else is generated from that.
