### ISSUE TITLE
Restore after new OS installation

### ISSUE THREAD

**Issue by iomari** [borgbackup/borg#8311]
Greetings,
I've been using borg/borgmatic for quite some time now with no issues what so sever. I have about 7 previous backups. Last week I did a fresh install of Kubuntu 24.04 which went smoothly then I connected my borg backup drive so I could restore some folders.
My previous home folder was already in place so my borg config files were in tact. I installed borgbackup and borgmatic. I mistakenly forgot to take note of the version of borg I was sing but I believe it was 2b8. So I ran the mount command:

```
sudo borg --repo /mnt/5t/backups/borg/complete mount /mnt/borg
[sudo] password for iomari:
```

and I'm getting the error:
`Runtime Error: borg mount not available: no FUSE support, BORG_FUSE_IMPL=pyfuse3,llfuse.`

I have both pyfuse3 and llfuse installed so I don't know what the problem is.

**Comment by ThomasWaldmann** [comment]
Check the borg install docs, it lists the ubuntu system packages required for borg, including the fuse/fuse3 packages.

**Comment by ThomasWaldmann** [comment]
In case you use a virtual env to install borg 2.0.0b8 via pip, you likely need to recreate the venv after upgrading the OS (and the OS python3). It's also in the docs...

**Comment by ThomasWaldmann** [comment]
No feedback, guess it was solved somehow.
