### ISSUE TITLE
Full backup space in Hetzner Storage Box

### ISSUE THREAD

**Issue by barnybla** [borgbackup/borg#8329]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

yes

## Is this a BUG / ISSUE report or a QUESTION?

QUESTION

#### Your borg version (borg -V).
borg 1.2.4
#### Operating system (distribution) and version.
Proxmox 8.2.4, Ubuntu 22.04.4 LTS, Synology DSM 7.2.1-69057 Update 5, 
#### Hardware / network configuration, and filesystems used.
Hetzner Storage Box
#### How much data is handled by borg?
10 T
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg break-lock ssh://u123456@u123456.your-storagebox.de:23/./backups/mail2

## Describe the problem you're observing.
borg.locking.LockFailed: Failed to create/acquire the lock /home/backups/nas2.example.local/lock.exclusive ([Errno 69] Disc quota exceeded: '/home/backups/nas2.example.local/lock.exclusive.u6e__251.tmp').

I made a big mistake, before my vacation to the USA, I started a new borg backup job, with a new repository.  I have forgotten to set any quota, so the box was running full. Now I have no chance to do annyting on the box. I was looking in the issues section for an answer, but there was no way working for me. Is there an easy way or is the only way to delete an repository?

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
yes, at all 5 repositorys

**Comment by ThomasWaldmann** [comment]
You need to:
- make some space, borg can't work with full fs
- check if you forgot to add `borg compact` to your backup script when upgrading to >= 1.2, see the change log

Making space can be difficult, but you could delete some of the segment files with the highest number under `repo_dir/data/...`. That will likely corrupt some backup archive(s), but borg check might be able to bring the repo back into a consistent state without these archives.

To avoid such situation in future, have a look at the repo config, you can give some additional reserved space there.

**Comment by barnybla** [comment]
Thanks Thomas,
deleting some segment files (2) was the right way, so I could remove the lock and "prune" to get enough space for the backups. After that I locked 2 G on each repository.
Regards
Bernd

**Comment by ThomasWaldmann** [comment]
@barnybla Don't forget `borg check --repair ...` - deleting segment files does some (limited) damage to the repo that needs repairing.

**Comment by trueshanti** [comment]
@barnybla 

> #### Full borg commandline that lead to the problem (leave away excludes and passwords)
> borg break-lock ssh://[u123456@u123456.your-storagebox.de](mailto:u123456@u123456.your-storagebox.de):23/./backups/mail2

> borg.locking.LockFailed: Failed to create/acquire the lock /home/backups/nas2.example.local/lock.exclusive ([Errno 69] Disc quota exceeded: '/home/backups/nas2.example.local/lock.exclusive.u6e__251.tmp').

what i think is fascinating here .. is that the dot "." leading the path on the STOBOX gets translated into "home" preaking the path (404) 

never had an issue with that ?

**Comment by ThomasWaldmann** [comment]
@barnybla @trueshanti A leading `/.` in such a ssh borg repo url expands to the full abs path of the current directory on the server side - which is usually the user's home directory, but could also be elsewhere depending on the server configuration.

But I guess the problem is elsewhere, `backups/mail2` in the command does not match the `backups/nas2.example.local` in the error output, so I suspect a copy&paste or log editing mistake.

**Comment by ThomasWaldmann** [comment]
This issue is about "full backup space" and also it is closed.

You are wrong, "/." is not getting replaced by $HOME, but by full abs path of the cwd and your cwd seems to be "/home". borg 1.x also has "/~" which would get replaced by $HOME.
