### ISSUE TITLE
Full, incremental or differential?

### ISSUE THREAD

**Issue by JoeMurray** [borgbackup/borg#8375]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Question

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

tl;dr Does borg do full, incremental or differential backups from perspective of files in the repo needed to do a restore?

I see in some places that Borg always does full backups and smartly deduplicates data. But reading the docs suggests that if previous files in the repo are corrupted or deleted then borg cannot restore. 

I'm confused by this. I'm interested in understanding which files in the backup repo are needed to do a restore, and the risks to a restore from one or more of these files not be available for restore. 

If I understand the documentation correctly, it seems that restore requires all of the files in the series going back to the most recent full backup in order to restore the most recently backed up data. So each backup file is not a full backup as I understand it. In fact, from the perspective of files needed for restore, this is an incremental backup approach.

Looking at https://www.unitrends.com/blog/types-of-backup-full-incremental-differential they explain an incremental backup only backups changes since most recent backup while differential backs up each time all of the changes since the most recent full backup. This means all backup files between now and full backup are required for restore in case of incremental backups, but only most recent backup file and original full backup file for a differential backup. Is one of these statements true of Borg's backup files?

Sorry for being long winded.

**Comment by infectormp** [comment]
See answer about backup here https://github.com/borgbackup/borg/issues/7917#issuecomment-1798333272

**Comment by JoeMurray** [comment]
Here's a place where issue response says borg always does full backup: https://github.com/borgbackup/borg/issues/6089#issuecomment-991520726

The part where I became worried about the storage system being susceptible to problems if files were corrupted was "If some data hasn’t changed from one backup to another, Borg can simply reference an already uploaded data chunk (deduplication)" from https://borgbackup.readthedocs.io/en/stable/quickstart.html#archives-and-repositories

Reading it carefully, it seems that ability to restore later backups depends on ability to restore earlier backups.

**Comment by RonnyPfannschmidt** [comment]
Each single backup is a full backup 

Borg used deduplication of chunks instead of incremental diffs 
 
I believe it's save to say that Borg provides the upsides of incremental backups without the downside

**Comment by RonnyPfannschmidt** [comment]
To elaborate further, if a new backup shares chunks with an old backup, Borg will keep all chunks needed by the new backup even when the old one is deleted

**Comment by JoeMurray** [comment]
Thanks. So there may be issues with bit rot/file corruption in the repo, but functionally each backup is a full backup that can be restored. I'm not so worried about performance times for restores, which is its own can of worms trying to measure it accurately and fairly. Though if you had any comparisons to hand that would be nice.

**Comment by ThomasWaldmann** [comment]
borg check can detect any sort of issue (like stuff missing or stuff being corrupted) in the repository, so there won't be surprises if you run it now and then.

of course if you fully deduplicate data and metadata, you have each specific piece of information only once (that's the definition of deduplication) and if you lose that, it's lost.

you can avoid getting into such trouble by choosing a reliable backup storage and by having multiple independent backup repositories.

**Comment by JoeMurray** [comment]
We use raid 1 for disk problems. Thanks for your rapid and helpful responses.
