### ISSUE TITLE
--files-from option for borg create

### ISSUE THREAD

**Issue by whiteatom** [borgbackup/borg#8424]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Feature Request

## System information. For client/server mode post info for both machines.

borg 1.2.7

Unraid 6.12.10

Backing up about 3.5tb

## Describe the problem you're observing.

could a --files-from option like rsync be added to borg create? It's a very useful option in my use case and has made my Borg transition a little clumsy.

see: https://linux.die.net/man/1/rsync
--files-from=FILE       read list of source-file names from FILE

Many thanks for all the work on this fantastic tool.

**Comment by ThomasWaldmann** [comment]
We already have that, check the docs.

**Comment by ThomasWaldmann** [comment]
https://borgbackup.readthedocs.io/en/stable/usage/create.html

- --paths-from-stdin
- --paths-from-command
- --paths-delimiter DELIM

**Comment by whiteatom** [comment]
Hmm.. ok - none of those are from a file like rsync. But I guess I can make this work... I suppose --paths-from-comment "cat file.txt" would essentially give me the same behaviour?

**Comment by ThomasWaldmann** [comment]
Yeah, it looks like there is no `--paths-from` yet, so it's either stdin or command.
