### ISSUE TITLE
borg repair: deal with corrupt hints file

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#843]
see: https://github.com/jborg/attic/issues/375

todo:
- reproduce (do we get same traceback still?)
- can borg repair fix that?

**Comment by enkore** [comment]
The segment index / hints files are automatically regenerated (no check needed) if missing. So, just wrap the reading part in a try..except, log & delete & regenerate them?

**Comment by enkore** [comment]
Fixed, further protections discussed in #1101
