### ISSUE TITLE
test_non_ascii_acl fails for 1.0.0

### ISSUE THREAD

**Issue by frispete** [borgbackup/borg#849]
While I see this test as being rather esoteric, it nags me nevertheless, since it forces me to ignore the testing result for the builds.

Example here:
https://build.opensuse.org/package/live_build_log/home:frispete:python3/python3-borgbackup/openSUSE_Leap_42.1/x86_64 @ [  241s] (timestamp is not stable due to rebuilds)

It happens on pretty all systems, I build for.

Is it related to libacl or is there a patch available?

**Comment by enkore** [comment]
I think that one will always fail outside a fakeroot.

**Comment by ThomasWaldmann** [comment]
Yes, the test is weird. But it tests a real failure some user has seen in practice. If someone has a better idea how to test this, feel free to fix it.

**Comment by frispete** [comment]
@enkore: well, the reason, it's not failing inside a faked root, is that the test is skipped inside of fakeroot...

**Comment by frispete** [comment]
Well, this test contains the following note:
# TODO: can this be tested without having an existing system user übel with uid 666 gid 666?

After studying the semantics of ACLs as being used within Linux distributions today, I cannot see, how this test can ever succeed without having added the user beforehand. While the man pages of setfacl and acl are pretty sparse on if numeric and literal user and group ids are being expected to exist, tests with setfacl show, that unknown numeric ids _are_ excepted, while unknown literal ids are _not_. At least on a XFS filesystem.

This is further complicated by the fact, that neither useradd nor groupadd allow non ascii ids.
I'm not sure, how this could ever be tested successfully.

**Comment by ThomasWaldmann** [comment]
@frispete on my local system, i just manually added such a user and the test works there.

**Comment by frispete** [comment]
@ThomasWaldmann I see, debian can do this. Good to know.

I disabled this single test, but build will fail now, if any other tests fail.
