### ISSUE TITLE
borg2 transfer attribute size not found

### ISSUE THREAD

**Issue by kuyagic** [borgbackup/borg#8491]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

YES

## Is this a BUG / ISSUE report or a QUESTION?

BUG

#### Your borg version (borg -V).
2.0.0b12
#### Operating system (distribution) and version.
Debian 12
#### How much data is handled by borg?
around 2GB
#### Full borg commandline that lead to the problem (leave away excludes and passwords)
```
root@home:~# borg2 -V
borg2 2.0.0b12
root@home:~# borg2 -r rclone://kfr:/rclone/borg2 transfer --other-repo /srv/borg/ --from-borg1
Local Exception

Error:

AttributeError: attribute size not found

If reporting bugs, please include the following:

Traceback (most recent call last):
  File "borg/archiver/__init__.py", line 633, in main
  File "borg/archiver/__init__.py", line 527, in run
  File "borg/archiver/_common.py", line 247, in wrapper
  File "borg/archiver/_common.py", line 174, in wrapper
  File "borg/archiver/transfer_cmd.py", line 36, in do_transfer
  File "borg/manifest.py", line 391, in list_considering
  File "borg/manifest.py", line 366, in list
  File "borg/manifest.py", line 176, in _matching_info_tuples
  File "borg/manifest.py", line 165, in _info_tuples
  File "borg/manifest.py", line 162, in _infos
  File "borg/manifest.py", line 152, in _get_archive_meta
  File "src/borg/item.pyx", line 221, in borg.item.PropDictProperty.__get__
AttributeError: attribute size not found

Platform: Linux crunchbits 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64
Linux: Unknown Linux
Borg: 2.0.0b12  Python: CPython 3.12.6 msgpack: 1.1.0 fuse: llfuse 1.5.1 [pyfuse3,llfuse]
PID: 3211124  CWD: /root
sys.argv: ['borg2', '-r', 'rclone://kfr:/rclone/borg2', 'transfer', '--other-repo', '/srv/borg/', '--from-borg1']
SSH_ORIGINAL_COMMAND: None
```

## Describe the problem you're observing.
use local file system as repo is the same.
borg1 repo is created and add snapshots with borg 1.4.0

**Comment by ThomasWaldmann** [comment]
Thanks for the bug report. It is a bit strange in 2 ways:
- I thought borg >= 1.2 always creates a pre-computed `size` within an archived item (e.g. a file). could it be that you have archives in that repo created by older borg clients?
- IIRC, `borg2 transfer` should deal with it, even if there is no pre-computed `size`

**Comment by ThomasWaldmann** [comment]
Relevant:
- e569595974da46cead38099274d286df9288e06f
- 2e83d18d35c40a4ebf4ac35f092c364d327f2ba8 #7072

**Comment by ThomasWaldmann** [comment]
@kuyagic Please check:
- do you have archives created with borg < 1.2.3 in that repo?
- are checkpoint archives in the repository? `borg1 list --consider-checkpoints ...`
- are archives imported by `borg import-tar`?

**Comment by ThomasWaldmann** [comment]
This should avoid the crash:
```
diff --git a/src/borg/manifest.py b/src/borg/manifest.py
index 2bcb6e49..9586b589 100644
--- a/src/borg/manifest.py
+++ b/src/borg/manifest.py
@@ -149,8 +149,8 @@ def _get_archive_meta(self, id: bytes) -> dict:
                 exists=True,  # repo has a valid archive item
                 username=archive_item.username,
                 hostname=archive_item.hostname,
-                size=archive_item.size,
-                nfiles=archive_item.nfiles,
+                size=archive_item.get("size", 0),
+                nfiles=archive_item.get("nfiles", 0),
                 comment=archive_item.comment,  # not always present?
                 tags=tuple(sorted(getattr(archive_item, "tags", []))),  # must be hashable
             )
```

**Comment by kuyagic** [comment]
> @kuyagic Please check:
> 
> * do you have archives created with borg < 1.2.3 in that repo?
> * are checkpoint archives in the repository? `borg1 list --consider-checkpoints ...`
> * are archives imported by `borg import-tar`?

My archives is from 2019 to 2024 , so it may be created with borg < 1.2.3
the first archive info in my repo
```
borg info /srv/borg::jd_2019-06-23_17_03_10
Archive name: jd_2019-06-23_17_03_10
Archive fingerprint: d15c3928e8b3d40459e3d418b0bd9113c94e9776411aa4808afcca5abcf4fa95
Comment:
Hostname: zmbox
Username: root
Time (start): Sun, 2019-06-23 17:03:20
Time (end): Sun, 2019-06-23 17:15:29
Duration: 12 minutes 8.72 seconds
Number of files: 26
```

no checkpoint archive

not imported by `borg import-tar`

**Comment by ThomasWaldmann** [comment]
OK, so guess you have old archives without size/nfiles information.

borg transfer should be able to transfer these, but already fell over the missing metadata while listing the archives in the old repo. That is fixed by ...

Note: when the archives are transferred, a new archive is created and save by the borg2 code, so they will have size/nfiles attributes after the transfer.

**Comment by ThomasWaldmann** [comment]
@kuyagic if you like, try the patch to confirm it works.
