### ISSUE TITLE
Create repo a bit later

### ISSUE THREAD

**Issue by infectormp** [borgbackup/borg#850]
Currently if ```init``` was interrupted, borg leave repo folder and some files inside repo. So we need delete repo folder manually. Maybe possible create repo at end of repo init process?

**Comment by ThomasWaldmann** [comment]
Well, creating and populating the repo folder is the main thing what init does.
So I'ld suggest not to interrupt it and just use borg delete repo afterwards if you change your mind.

**Comment by infectormp** [comment]
```borg delete``` not work for incomplete repo

Object with key b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' not found in repository /backup/opt.repo.
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1466, in main
    exit_code = archiver.run(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 1420, in run
    return args.func(args)
  File "/usr/lib64/python3.4/site-packages/borg/archiver.py", line 371, in do_delete
    manifest, key = Manifest.load(repository)
  File "/usr/lib64/python3.4/site-packages/borg/helpers.py", line 93, in load
    cdata = repository.get(cls.MANIFEST_ID)
  File "/usr/lib64/python3.4/site-packages/borg/repository.py", line 421, in get
    raise self.ObjectNotFound(id_, self.path) from None
borg.repository.ObjectNotFound: (b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', '/backup/opt.repo')

**Comment by infectormp** [comment]
You can create and populate the repo folder after ```Do you want your passphrase to be displayed for verification? [yN]:```

**Comment by Ape** [comment]
Certainly the process could be modified to first ask and verify the passphrase before doing anything else.

**Comment by enkore** [comment]
Ah, now it makes sense to me. I read this and wondered: *what's the use case for interrupting borg*. Typo in the passphrase, or wrong encryption options, that makes sense.

> Certainly the process could be modified to first ask and verify the passphrase before doing anything else.

Sounds good.
