### ISSUE TITLE
Accessing a remote repo not on port 22

### ISSUE THREAD

**Issue by module0x90** [borgbackup/borg#851]
Hi,

I had a quick go at this and this is really awesome. I was planning to use this for my server (on the internet), but then realized that it only supports "push" and not a "pull". But it supports remote repositories, ok.
As I want to backup to my workstation at home, initiated by the server, I realized that's gonna be a bit difficult - I don't want to setup any crazy port forwarding or something.
SSH tunnels came to mind... setting up quickly a local port forward on my workstation to my server, so that port 9000 on my server is hitting my workstation:

ssh -R 9000:localhost:22 user@server

Creating the repo then

./borg-linux64 init ssh://local@localhost:9000//mnt/storage/serverborgbackup

worked alright.
But then trying to create a backup with

./borg-linux64 create local@localhost:9000//mnt/storage/serverborgbackup:Wednesday /directory

I get 

borg-linux64 create: error: argument ARCHIVE: Invalid location format: "local@localhost:9000:serverborgbackup::Wednesday"

I tried various incarnations, full path, but I always get the same error.
I just thought I nearly got it:

./borg-linux64 create -v --debug local@localhost:9000//mnt/storage/serverborgbackup::Wednesday /directory

But this seems to disregard the port 9000. When I try 

ssh -p 9000 user@localhost

on my server I end up on my workstation.

Am I doing something wrong? Or is a different SSH port for remote repositories not supported?

Cheers

Thomas

**Comment by Ape** [comment]
This should work:
```
ssh://local@localhost:9000/mnt/storage/serverborgbackup
```

**Comment by enkore** [comment]
> I was planning to use this for my server (on the internet), but then realized that it only supports "push" and not a "pull".

It does pull backups over e.g. sshfs.

**Comment by module0x90** [comment]
I tried those, yes.
I am using the statically compiled version, borg-linux64 1.0.0, could that be an issue?

**Comment by module0x90** [comment]
@enkore I was thinking, in regards to setup, that the repo what's pushed to should be beyond the SSH tunnel, not the other way round. I am thinking just because that it doesn't *always* read all the files through the tunnel to find out it hasn't changed. If the repo is beyond the tunnel it has already read the file and just compares meta data - or only pushes the delta down the tunnel.

Is my asumption wrong?

**Comment by enkore** [comment]
Works for me, borg 1.0.0

``` sh
$ strace -fe trace=clone,execve borg list ssh://localhost:220/~/testrepo
...
[pid 22245] execve("/usr/bin/ssh", ["ssh", "-p", "220", "localhost", "borg", "serve", "--umask=077"], [/* 53 vars */]) = 0
...
```

**Comment by enkore** [comment]
> I am thinking just because that it doesn't always read all the files through the tunnel to find out it hasn't changed. If the repo is beyond the tunnel it has already read the file and just compares meta data - or only pushes the delta down the tunnel.

Yes'n'no. Borg 1.0.0 will do what you describe. Later releases will include `--ignore-inode`, so it still only looks at files that have changed.

**Comment by module0x90** [comment]
Coolio. Awesome guys. Works for me now when I prefix it with ssh://

./borg-linux64 create ssh://local@localhost:9000/mnt/storage/borgbackupmyserver::Wednesday /directory

Just running ... :-) 
Is this now a "reverse push" or a "reverse pull" backup? I guess the latter, as it is initiated internally.

**Comment by rsmck** [comment]
Sorry to open an old issue but I seem to have an interesting anomaly when using this;

```
root@treefrog:/data/scripts# borg init 'ssh://borg@10.40.23.214:7756:~/treefrog'
Remote: ssh: connect to host 10.40.23.214 port 775: Connection refused
```

It looks like it truncates the last digit of the port number... amusingly if I just put in an extra dummy digit it works;

```
root@treefrog:/data/scripts# borg init 'ssh://borg@10.40.23.214:77566:~/treefrog'
The authenticity of host '[10.40.23.214]:7756 ([10.40.23.214]:7756)' can't be established.
```

Running borg 1.0.9 (debian 8, installed from apt)

**Comment by ThomasWaldmann** [comment]
That's because your syntax is wrong. There should be a slash after the port and before the tilde.

We're working on having a better regex that rejects such stuff.

**Comment by rsmck** [comment]
That makes sense, didn't think of that as it was quoted.  Thanks for the quick response :)

--
Sent from my mobile device. 
Please excuse brevity.

**Comment by rs-development** [comment]
Is there an option to use an alternative port and a relative path? I could not find a syntax example

**Comment by fantasya-pbem** [comment]
Yes, see here: https://borgbackup.readthedocs.io/en/stable/usage/general.html

``ssh://user@host:port/path/to/repo`` - alternative syntax, port can be given
