### ISSUE TITLE
When running "$ borg init" on a pre-existing directory, permissions are not properly set.

### ISSUE THREAD

**Issue by sudoman** [borgbackup/borg#853]
If I create a backup using a pre-existing directory:

    $ mkdir backup-x
    $ ls -lhd backup-x
    drwxrwxr-x. 2 andrew andrew 4.0K Apr  6 20:19 backup-x
    $ borg init backup-x
    $ ls -lhd backup-x
    drwxrwxr-x. 3 andrew andrew 4.0K Apr  6 20:19 backup-x

... then the permissions of `backup-x` are incorrect. When `borg init` creates a new directory, they are correct:

    $ borg init backup-x
    $ ls -lhd backup-x
    drwx------. 3 andrew andrew 4.0K Apr  6 20:20 backup-x

**Comment by Ape** [comment]
It could be argued that the current behavior is correct. When you create the directory, it is your responsibility to set the permissions. It's not any fundamental requirement to have `drwx------` permissions, although it is usually recommended.

**Comment by enkore** [comment]
Borg uses the normal "umask" semantics, which only affects new files/directories.

**Comment by ThomasWaldmann** [comment]
I agree with ape - you create it, you are responsible. If borg creates it, it is correct.
