### ISSUE TITLE
Strip in the middle of a path slashdot hack

### ISSUE THREAD

**Issue by witten** [borgbackup/borg#8537]
My use case: I'm looking at implementing [ZFS filesystem integration](https://projects.torsion.org/borgmatic-collective/borgmatic/issues/261) as part of [borgmatic](https://torsion.org/borgmatic/) so that ZFS users can take advantage of consistent snapshots when storing their files into a Borg archive. (I believe that non-borgmatic Borg/ZFS users also have similar needs.)

That integration would work something like the following when creating a backup archive:

 * Before running Borg, make read-only ZFS snapshots of all configured ZFS filesystems. The way ZFS works is that such snapshots show up (mounted) in an invisible directory. So for instance `/my/zfs/mountpoint`'s snapshot might show up at `/my/zfs/mountpoint/.zfs/snapshots/borgmatic-1234`.
 * Run a `create` with Borg, passing in the snapshot paths.
 * As cleanup, remove the snapshots.

The problem with this plan is that the snapshot directory ends up in the Borg archive, e.g. `/my/zfs/mountpoint/.zfs/snapshots/borgmatic-1234`. However, ideally the snapshotting is completely transparent to the user, and the files instead get stored in the Borg archive to *appear* as if they came from their original ZFS filesystem mountpoints, e.g. just `/my/zfs/mountpoint`.

One way to support this ask would be to implement a feature that was already discussed (but not implemented) here: https://github.com/borgbackup/borg/issues/4685#issuecomment-1927895793 ... specifically the "SM" option. The idea is that borgmatic or the user would pass the following to Borg create: `/my/zfs/mountpoint/./.zfs/snapshots/borgmatic-1234/./`.

In this case, everything between the `/./`s would get stripped, leaving just `/my/zfs/mountpoint/` as the path stored in the Borg archive for these snapshotted files.  (In the general case, there could also be path components after the second `/./` that would be kept, but in this particular example that's not needed.)

The end result for this use case is that snapshot files appear at their "original" locations and can easily be extracted back to them should that be necessary.

In terms of ways this could go wrong: The interaction with the existing single slashdot hack should be considered. I think the way that could work is for Borg to search for two `/./`s in a path. If found, do the new "SM" behavior. But if there's only a single `/./`, run the existing "SP" logic.

Additionally, if a user unintentionally  includes `/./` twice in their path not intending to use this feature, then they could inadvertently get part of their path stripped out. That same downside applies to the existing "SP" logic.

Why not the "RP" logic? It just seems more complicated, and it doesn't have the nice property of normalizing to a standard (existent) path like the other approaches do.

**Comment by SpiritInAShell** [comment]
Sorry, this is not about the subject of paths, but just a thought on the scenario of @witten: what bothers me with the idea of creating archives from `zfs` or `btrfs` snapshots is, that - IIRC - `borg` uses absolute paths for caching (which files will not be read until BORG_FILES_CACHE_TTL is hit). So from my understanding, if you use timestamp based snapshot directories,  in your scenario, @witten, _you might also_ experience slow archive creation due to no files recognized by cache and always re-read from disk. Enabling such path replacements might lead to this user experience (if `borg` indeed handles as I remember.)

**Comment by witten** [comment]
Thanks for point this out. I can't speak to `btrfs`, but with `zfs` borgmatic *could* use a consistent snapshot name without encoding a timestamp in it. In the example above, I wasn't even thinking about using timestamps, but more like PID or something to prevent collisions. But in theory borgmatic or a non-borgmatic user could avoid even that when making filesystem snapshots if it interfered with Borg's caching.

**Comment by SpiritInAShell** [comment]
Another idea would be: _to me it feels as if_ `borg create` _on snapshot directories may become a more common thing_, and "spoofing the same directory" for files cache to work may become weird, the problem could be considered differently by a flag changing borgs behaviour:

`borg create --treat-sourcepath-as="/my/zfs/mountpoint/" /my/zfs/mountpoint/.zfs/snapshots/borgmatic-1234`

That flag would:
- rewrite the recorded paths in the archive to `--treat-sourcepath-as`
- treat all files cache actions read by `borg create` as if they were that specified directory.

You might solve that way a (very special) path rewrite problem and enable borg to more efficiently handle snapshots by `btrfs`,`zfs`,`rsync` etc, like I guess https://github.com/borgbackup/borg-import appears to address (only read about it)

**Comment by SpiritInAShell** [comment]
Alternative to the path rewrite problem:

Let `borg recreate` also rewrite path elements (strip, add, replace).
- Disadvantage: an additional, maybe very timely and dangerous action needed in the use case of this issue.
- but would enable the user to address _a very broad issue in a way most useful to his needs_
- no change in the source path behaviour of `borg create` which might cause errors due to ambiguousity

**Comment by jdchristensen** [comment]
I haven't followed everything in this issue, but borg can use relative paths, so you can do
```
cd /long/path/you/want/to/hide
borg create repo::archive .
```
and it will backup `/long/path/you/want/to/hide` but store paths relative to the that directory.  E.g. the file `/long/path/you/want/to/hide/subdir/example` will be stored as `subdir/example`.  So this is a way to strip leading path names.

I'm not in favour of the double-dot-slash hack.  I'd prefer a general `--rewrite-path` argument, but if it gets fancy, it might be complicated to document and use.

**Comment by witten** [comment]
The problem with either a command-line flag like `--treat-sourcepath-as`/`--rewrite-path` or the use of relative paths along with an initial `cd` is that it only works if you've got a single path to backup. As soon as you want to ask Borg to backup multiple paths with potentially differing prefixes (or the same prefix that you want rewritten differently for each path), either of these approaches break down. That's the benefit, IMO, of encoding the prefix that's to be stripped in the path itself; you can vary the prefix for each path as necessary.

Having said that, there may be other / better ways of encoding that information. (Maybe there's an approach with repeated uses of the same command-line flag?) But I do think at least my use case requires the ability for different paths to get different transformations, because a lot more can go into a backup than a single snapshot. And I imagine that applies to other use cases as well.

The `borg recreate` idea is interesting, but that might just be pushing the same design considerations downstream. You still need some way to specify which paths get which transformations IMO.

**Comment by jdchristensen** [comment]
I was imagining allowing multiple uses of `--rewrite-path`, so I think that covers your objection.  Moreover, instead of only allowing deletion, it allows replacement with a different path, which I expect would be a common case.

But more importantly, encoding transformations within the path itself seems too fragile.  For example, `/./` can occur in paths generated by other programs.

**Comment by witten** [comment]
What would the syntax of `--rewrite-path` look like? I'm wondering how you'd specify either individual paths or multiple paths to transform. And also how that transformation would be given.

> But more importantly, encoding transformations within the path itself seems too fragile. For example, /./ can occur in paths generated by other programs.

That ship has already flown, given that the single `/./` hack is already supported in Borg 1.4 and 2.0. But I could maybe see an argument against doubling down on that approach if you didn't like it to begin with. :smile:

**Comment by jdchristensen** [comment]
> What would the syntax of --rewrite-path look like?

`--rewrite-path replace/this with/that`
`--rewrite-path get/rid/of/this/ ''`

Give it multiple times to do multiple replacements.  It would be a purely string-based replacement process.

**Comment by witten** [comment]
Cool, I think that would work for my use case and I imagine other use cases as well. You'd just have to be careful that you're not matching more source paths than you intend to match. To that end, I can imagine needing the ability to match against the start of a path vs. the middle of a path vs. the end of a path... which would suggest regular expression support (e.g. `^` and `$`)... which would complicate things. (Incidentally, I feel like this general approach was discussed on another Borg ticket a while back, but I can't find it right now.)

@ThomasWaldmann, thoughts on the various approaches proposed? `--rewrite-path` vs. "SM"?

**Comment by witten** [comment]
Thanks for weighing in. My understanding with ZFS is that the snapshot gets auto-mounted at, say, `/my/zfs/mountpoint/.zfs/snapshots/borgmatic-1234`. But it's possible I can implement what you suggest by first unmounting that auto-mounted snapshot and then re-mounting it at `/somewhere/my/zfs/mountpoint`, passing `/somewhere/./my/zfs/mountpoint` to Borg to employ the slashdot hack.

The `cd` trick won't work here because there can be other non-snapshot, relative directories passed to Borg at the same time. And I've also looked at bind mounts, which are certainly possible but more complex, especially given the variance across operating systems.

Anyway, I'll give this a shot!

**Comment by witten** [comment]
This general approach appears to work. Turns out I didn't need to unmount the auto-mounted snapshot; I can just mount the snapshot in a second location. I'll close this ticket for now, but of course feel free to reopen it if someone else has a need for any of the other features discussed here.

**Comment by ThomasWaldmann** [comment]
Coming late to the party, was busy with other borg stuff.

Just wanted to add that the files cache key was changed:
- in borg 1.x it is H(full absolute path)
- in borg 2 (master branch) it is H(archived path)

The change was done so borg is able to rebuild the files cache also from an archive in the repo.
