### ISSUE TITLE
take borgbackup stickers to 38c3

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#8551]
Event info: https://events.ccc.de/congress/2024/infos/index.html

I won't be there in person, but if someone from borg community visits there, they could get some borg stickers from me to distribute there.

In the past, there used to be sticker boxes at some places at congress, I assume this will be the case this year also.

So the task would be to put the stickers into these sticker boxes so any interested visitor can pick up some from there.

Requirements:
- you need to have a congress ticket to get in there
- you need to request stickers from me (providing your postal address via e-mail) before 2024-12-12 to make sure you get the stickers before your travel to the chaos communication congress.

If you are interested, drop a comment below. Thanks!

**Comment by ThomasWaldmann** [comment]
@dragetd did you distribute all of your stickers last year or do you also have "stock" left?

**Comment by JustACasual** [comment]
Would be happy to do that :) I'm going!

**Comment by MarioTro** [comment]
I will be there too. Let me know if you need help.

**Comment by ThomasWaldmann** [comment]
Just send me an email with your postal address, thanks for helping!

**Comment by mcfly** [comment]
Nice. We at milliways are BorgBackup users and have an assembly. We proudly would put them in our sticker box.

**Comment by ThomasWaldmann** [comment]
I have prepared 2 packages (<2kg each) with stickers going to @MarioTro and @JustACasual if they confirm my email. I've also included a few 25x25mm plastic PC stickers for your personal use.

@mcfly I noticed shipping to the netherlands costs 3x as much, so I'ld like to send you just some 25x25mm plastic PC stickers if you confirm going - for your personal use and **for borg fans asking for them** at milliways assembly.

@MarioTro and @JustACasual maybe you can drop some paper stickers at milliways assembly, so they have these also.

Lots of paper stickers, but only few of these plastic stickers (sorry, don't have more).

**Comment by MarioTro** [comment]
I'll happily drop off some stickers at milliways assembly. See you there!

**Comment by ThomasWaldmann** [comment]
In the 2 packages I sent out recently, there are 2x ~2kg stickers.

**Comment by ThomasWaldmann** [comment]
Hope you all had a nice 38c3! I was following it remotely (mastodon and media.ccc.de), but still have a lot of talks to watch. :-)

**Comment by dragetd** [comment]
I put some stickers on the tables, but could not really drop a lot. So… still got more… still will bring them to all larger events I am at. :)
