### ISSUE TITLE
Deduplicate constants repeated in the code

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#856]
- [X] Replace [these](https://github.com/borgbackup/borg/blob/master/borg/archive.py#L186) tuples with a constant (e.g. ARCHIVE_TEXT_KEYS)
- [X] This key tuple: https://github.com/borgbackup/borg/blob/master/borg/archive.py#L61 (e.g. ITEM_TEXT_KEYS)
- [X] ITEM_KEYS (all item metadata, for validation / robust unpacker)
- [X] chunker params
- [X] repo seg size, segs / dir
- [X] CACHEDIR.TAG filename / content
- [X] default umask
- [ ] find other instances

**Comment by ThomasWaldmann** [comment]
How about creating a module `borg.constants` to put all such stuff there (so it can easily imported everywhere without creating an import cycle).

**Comment by ThomasWaldmann** [comment]
404

**Comment by enkore** [comment]
fixd

**Comment by enkore** [comment]
fixed

**Comment by ThomasWaldmann** [comment]
constants.FOOBAR is a bit long, how about:
```
from . import constants as c
x = c.FOOBAR
```

**Comment by ThomasWaldmann** [comment]
fixed by: https://github.com/borgbackup/borg/pull/927
