### ISSUE TITLE
No dry-run flags when using borg extract 

### ISSUE THREAD

**Issue by goebbe** [borgbackup/borg#8564]
Using borg 1.4, I checked the use of "flags" when doing a dry-run for different borg commands. 

The command `borg extract --dry-run --list` does not print the flags (that are used with e.g. borg create / borg recreate
Instead, `borg extract` prints only the list of items that would be included in the extract without the --dry-run. 

This was the command, I used: 
`borg extract REPO::ARCHIVE /home/user/test Admin -e 'home/user/test/*.bak'  --dry-run --verbose --list `

In the name of consistency, dry-run flags could be added to borg extract.

**Comment by ThomasWaldmann** [comment]
Good idea. It's just questionable if we shall do that for 1.4 or rather put it into 2.0 breaking release.

Not sure if somebody is parsing that output with some automation which would break if we change the format.

**Comment by goebbe** [comment]
I just reported this for borg 1.4, since I found this inconsistency using this version. 
From a user's point of view, this is not a big issue - I would rather leave borg 1.4. as it is now and focus on borg 2.0 as suggested.

**Comment by goebbe** [comment]
I shortly looked into this - but unfortunately fixing this is beyond my skills and knowledge. I could not even find the relevant places in the source code. :-D   Hopefully somebody more proficient will take this up.

**Comment by ThomasWaldmann** [comment]
The starting point for changing how some command works is its implementation in `src/borg/archiver/*_cmd.py` - and then follow the code from there.

**Comment by alighazi288** [comment]
Hi! First time contributor here. Could you please give me some advice on getting started? I would like to start with this as my first problem!

**Comment by ThomasWaldmann** [comment]
@alighazi288 Thanks for helping! Did you read the previous comment, where I pointed to the `*_cmd.py` files. This is where the commands are implemented.

About general borg installation, development setup, etc. please see our docs.

If you have more specific questions, just ask!

**Comment by alighazi288** [comment]
Thank you so much! I'll try working on a fix for the problem!

**Comment by goebbe** [comment]
@alighazi288  `borg create` and `borg recreate` both print the dry-run flags for items (folders / files), perhaps it is helpful to look at theses, as examples. 

When testing `borg extract --dry-run --list`, it **took quite a long time**, especially with large files. 
This was different from the `--dry-run` when testing `borg create` which went really fast. 
I had the impression that `borg create --dry-run --list` just checks what would happen if the sources / includes/ excludes are applied, whereas in the case of `borg extract --dry-run` additional computations are done. 

@ThomasWaldmann Is there a conceptional difference in what --dry-run should/ could achieve, here? Or should dry-run always just provide feedback on sources/ includes/ excludes?

**Comment by ThomasWaldmann** [comment]
There is a massive difference in create and extract dry-run:
- create --dry-run only recurses into the filesystem, applies include/exclude filtering and logs what was excluded/included. It does not process the files any further (does not read file content, not compress/encrypt/authenticate content data, not write to repo).
- extract --dry-run does all what a normal extract run would do, except writing the extracted data to the fs. so it reads all data from the repo, authenticates, decrypts, decompresses it.
