### ISSUE TITLE
Another Traceback from permission error, different from 8 year old #854

### ISSUE THREAD

**Issue by AlSimons** [borgbackup/borg#8569]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG/ISSUE

#### Your borg version (borg -V).
1.2.4

#### Operating system (distribution) and version.
Raspberry PI OS Debian 12 fully patched

#### Hardware / network configuration, and filesystems used.
Raspberry Pi 4, simple home lan, but not a network backup, ext4 for both the source tree and the repo (but different filesystems)

#### How much data is handled by borg?
About 10GB

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
borg list /backups/ext4/borg_repo

Note: Adding sudo fixes the problem

Given that a similar problem with a different traceback (#854) is about 8 years old, I thought it warranted a new Issue report. Apologies if not.

## Describe the problem you're observing.
I know that this is a permission problem, but the traceback is showing a key error as well as in a nexted exception an ENOPERM.
 
#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes, Create a repository owned by root, and attempt to do borg list without sudo.

#### Include any warning/errors/backtraces from the system logs

```
$ borg list /backups/ext4/borg_repo/
Exception ignored in: <function Repository.__del__ at 0x7f9e235940>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 190, in __del__
    assert False, "cleanup happened in Repository.__del__"
AssertionError: cleanup happened in Repository.__del__
Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1453, in get_fd
    ts, fd = self.fds[segment]
             ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/lrucache.py", line 21, in __getitem__
    value = self._cache[key]  # raise KeyError if not found
            ~~~~~~~~~~~^^^^^
KeyError: 20

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5213, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5144, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 168, in wrapper
    with repository:
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 200, in __enter__
    self.open(self.path, bool(self.exclusive), lock_wait=self.lock_wait, lock=self.do_lock)
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 469, in open
    if segment is not None and self.io.get_segment_magic(segment) == ATTIC_MAGIC:
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1488, in get_segment_magic
    fd = self.get_fd(segment)
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1455, in get_fd
    fd = open_fd()
         ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1436, in open_fd
    fd = open(self.segment_filename(segment), 'rb')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/backups/ext4/borg_repo/data/0/20'

Platform: Linux raspberrypi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64
Linux: Unknown Linux  
Borg: 1.2.4  Python: CPython 3.11.2 msgpack: 1.0.3 fuse: pyfuse3 3.2.1 [pyfuse3,llfuse]
PID: 61407  CWD: /home/simons
sys.argv: ['/usr/bin/borg', 'list', '/backups/ext4/borg_repo/']
SSH_ORIGINAL_COMMAND: None
```

**Comment by ThomasWaldmann** [comment]
The key error is a cache miss, you can ignore that part.

The permission problem is because you do not always use the same user to access your repo or because the user you use does not have permissions. That's not a borg problem.
