### ISSUE TITLE
File changed during backup warning although they never change.

### ISSUE THREAD

**Issue by hparlak** [borgbackup/borg#8573]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

If there is an explanation for how this might occur, this is a question.
Otherwise it's an Issue.

#### Your borg version (borg -V).
1.4.0

#### Operating system (distribution) and version.
Fedora Linux 41

#### Hardware / network configuration, and filesystems used.
Pulling files from a Windows share via sftp. Windows drive is ntfs

#### Full borg commandline that lead to the problem (leave away excludes and passwords)
I'm using Vorta. Commandline from the log is:
borg create --list --progress --info --log-json --json --filter=AM -C zstd,8 --exclude-from /tmp/tmpav0a__3j /home/yoga/ipc_backup::leyo-2024-11-29-081502 /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Desktop /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Documents /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Pictures /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Favorites /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/AppData/Roaming/Thunderbird/Profiles/4638tmg4.default/ImapMail /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/AppData/Roaming/Thunderbird/Profiles/4638tmg4.default/Mail /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/AppData/Local/Google/Chrome/User Data/Default/Bookmarks /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/AppData/Local/Google/Chrome/User Data/Default/Login Data /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/AppData/Local/Google/Chrome/User Data/Default/Preferences

## Describe the problem you're observing.
Some files cause the warning "file changed while we backed it up" every time I backup. The files surely never change.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.
Yes. This happens every time I backup.

**Comment by ThomasWaldmann** [comment]
borg does a `stat` call before and after backing up a file. if it says "changed", something (not necessarily the file content, could be also some metadata) has changed.

browser and mail client files often change while these programs are running.

**Comment by ThomasWaldmann** [comment]
@hparlak did you find out why your files are considered changed? You can check the timestamps yourself using the `stat` shell command.

**Comment by hparlak** [comment]
No I didn't find out. The issue continues, although it's just a nuisance. The files reside on an old Windows 7 PC. They're old .TIF and .xls files not touched for years. The stat commands output for an example file is as follows:

```
stat '/run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Desktop/Eski Masaüstü/9006957-420-16.01.2014-1240/9095753.TIF' 
  File: /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Desktop/Eski Masaüstü/9006957-420-16.01.2014-1240/9095753.TIF
  Size: 1165985   	Blocks: 2278       IO Block: 4096   regular file
Device: 0,88	Inode: 43          Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/    yoga)   Gid: ( 1000/    yoga)
Context: system_u:object_r:fusefs_t:s0
Access: 2016-04-02 10:25:23.000000000 +0300
Modify: 2012-12-10 15:39:52.000000000 +0200
Change: 2012-12-10 15:39:52.000000000 +0200
 Birth: -

```

**Comment by ThomasWaldmann** [comment]
The timestamps look ok (and old). Check if the inode is changing.

**Comment by hparlak** [comment]
Yes, inode is changed

```
stat '/run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Desktop/Eski Masaüstü/9006957-420-16.01.2014-1240/9095753.TIF'
  File: /run/user/1000/gvfs/sftp:host=192.168.1.201/C:/Users/ileri/Desktop/Eski Masaüstü/9006957-420-16.01.2014-1240/9095753.TIF
  Size: 1165985   	Blocks: 2278       IO Block: 4096   regular file
Device: 0,88	Inode: 9           Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/    yoga)   Gid: ( 1000/    yoga)
Context: system_u:object_r:fusefs_t:s0
Access: 2016-04-02 10:25:23.000000000 +0300
Modify: 2012-12-10 15:39:52.000000000 +0200
Change: 2012-12-10 15:39:52.000000000 +0200
 Birth: -
```

**Comment by infectormp** [comment]
> Yes, inode is changed
That is the answer.

https://borgbackup.readthedocs.io/en/stable/usage/create.html#description
`--files-cache ctime,size` will solve the problem

**Comment by hparlak** [comment]
Sorry but it doesn't solve the problem. (I tried it again after your reply, just in case)

Please let me remind you that the problem is not only detecting unchanged files as changed, but its warning about files being changed DURING backing up. Therefore borg probably thinks those files were not properly backed up and need to be backed up again next time, because the files (borg thinks) were changed DURING the last backup.

**Comment by ThomasWaldmann** [comment]
@hparlak is there anything common between the files borg warns about? Is it always the same files or is it somehow random?

**Comment by ThomasWaldmann** [comment]
This is the (slightly simplified) code that does the file-change-while-backup check. Note that it only looks at the ctime, not at the inode number:
```
with OsOpen(path=path, parent_fd=parent_fd, name=name, flags=flags, noatime=True) as fd:
    st = stat_update_check(st, os.fstat(fd))
    item.update(self.metadata_collector.stat_simple_attrs(st))
    with backup_io('read'):
        self.process_file_chunks(item, cache, self.stats, self.show_progress, backup_io_iter(self.chunker.chunkify(None, fd)))
    with backup_io('fstat2'):
        st2 = os.fstat(fd)
    changed_while_backup = st.st_ctime_ns != st2.st_ctime_ns
    if changed_while_backup:
        status = 'C'  # regular file changed while we backed it up, might be inconsistent/corrupt!
```

**Comment by hparlak** [comment]
I just filtered out all the problematic files from the log and moved them somewhere else where they wouldn't be backed up all the errors went away. So, it seems, this was specific to those files. But I don't understand why, because they're all document files that were all stored untouched for ages. I guess the buggy gvfs theory may be plausible. I will try to further investigate if suddenly an error comes up again for another file in the following days. 

By the way, there actually are some files (like mailboxes) that do change during backup, despite not causing these errors.

**Comment by ThomasWaldmann** [comment]
borg only emits this warning if a file changes WHILE borg is processing it.

**Comment by hparlak** [comment]
The email inbox file is 3gb. It takes a couple of minutes to back it up (over the network). It most likely changes during that time. I checked, although the file is modified, ctime does seem to not change while the file is in use by the email client, which i think explains the no warning based on your code sample.

**Comment by ThomasWaldmann** [comment]
If ctime does not change although the file is changed, your fs is broken and borg can't help you with that. So, please report an issue to gvfs.
