### ISSUE TITLE
Any attempt to access a repository results in a crash with "Input/Output Error: Input/output error: '<repository>/index.4503.tmp'" after "Replaying Segments"

### ISSUE THREAD

**Issue by maximumsomething** [borgbackup/borg#8579]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

Issue

#### Your borg version (borg -V).

borg 1.4.0

#### Operating system (distribution) and version.

Debian Testing (trixie)

#### Hardware / network configuration, and filesystems used.

A laptop backing up to a NTFS-formatted external hard disk

#### How much data is handled by borg?

The repository currently fills most of the 2TB drive

#### Full borg commandline that lead to the problem (leave away excludes and passwords)

Many commands do, but one example is `borg check --repair --progress <repository>/Vorta

#### The Issue

My computer crashed while borg was running, and ever since then, borg crashes whenever it tries to access the repository. Any action, including `borg create`, `borg check`, `borg mount`, results in several hours of "Replaying Segments", during which borg reads the whole ~2TB repository, then this error:

```Local Exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5391, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 5309, in run
    rc = func(args)
         ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 191, in wrapper
    return method(self, args, repository=repository, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/archiver.py", line 365, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space, max_duration=args.max_duration):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 1125, in check
    self.write_index()
  File "/usr/lib/python3/dist-packages/borg/repository.py", line 683, in write_index
    with IntegrityCheckedFile(index_file + '.tmp', filename=index_name, write=True) as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/borg/crypto/file_integrity.py", line 130, in __init__
    self.file_fd = override_fd or open(path, mode)
                                  ^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error: '<repository>/index.4503.tmp'
```

**Comment by infectormp** [comment]
It is a hardware error. Try to search similar issues.
https://borgbackup.readthedocs.io/en/stable/faq.html#i-get-an-integrityerror-or-similar-what-now

**Comment by maximumsomething** [comment]
It's not a hardware error. SMART reports the drive status as good. It was triggered by an unclean unmount. That means some sort of data corruption.

**Comment by infectormp** [comment]
> OSError: [Errno 5] Input/output error

This issue came from OS level. So, it might be the fs problem also. You need to resolve this issue first and then use `borg check`.

**Comment by maximumsomething** [comment]
As it turns out, it was a filesystem issue! Trying to manually create a file named 'index.4503.tmp' also returned an error. Running chkdsk on Windows fixed that.

I'll close this issue, but it does strike me as bad design that borg needs to write a file in order to read anything in the repository. What if the drive *was* actually failing?

**Comment by ThomasWaldmann** [comment]
borg is rather complex code.

For example, it locks the repo before accessing it. The lock is inside the repo dir, so it needs to write to the repo and if only for the lock.

Depending on the state of the repo, it might also do a rollback or other operations.

**Comment by ThomasWaldmann** [comment]
BTW, as you use linux, it would be better if you used ext4 for your borg repo disk rather than ntfs, for better reliability.
