### ISSUE TITLE
Document what packages are needed under Cygwin64

### ISSUE THREAD

**Issue by tgharold** [borgbackup/borg#86]
Initial testing indicates that the following Cygwin packages have to be installed prior to installing "pip" and "borgbackup".  I'm not sure whether binutils or libuuid-devel are required.

```
binutils (not sure)
gcc-g++
libuuid-devel (not sure)
openssl-devel
python3
python3-setuputils
wget (used to get the pip install)
```

The "pip" command install process looks like:

```bash
$ cd ~/
$ mkdir -p ~/downloads/python
$ cd ~/downloads/python
$ wget https://bootstrap.pypa.io/get-pip.py
$ python3 get-pip.py
$ pip3 --version
```

The "borgbackup" install is then

```bash
$ pip3 install borgbackup
```

Note: I will have to do testing later this week (actually running backups) under Cygwin64.

**Comment by ThomasWaldmann** [comment]
See https://github.com/borgbackup/borg/issues/53 for a binary wheel for cygwin/64.
You won't need the development stuff then.
I didn't use get-pip btw., IIRC I used easy_install pip (or so).

**Comment by ThomasWaldmann** [comment]
@tgharold I compared what you have installed and what I have installed:

python3
python3-setuptools
binutils
gcc-core (no gcc-g++ needed!)
openssl-devel (+libopenssl)

not strictly required, but maybe useful for some scenarios:
openssh
git
make
python3-cython (required to build non-releases / from git)

note sure about:
libattr1 (we use that on linux - on cygwin???)

**Comment by ThomasWaldmann** [comment]
Fixed, see https://github.com/borgbackup/borg/commit/f330b4bd2afae73fdc4cf18c10bb1ff005e66c3a .
