### ISSUE TITLE
freebsd test slowness

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#863]
somehow running the tests on freebsd 10.2 (vagrant machine) is much slower than on linux - why?

**Comment by jungle-boogie** [comment]
What is slow? When you're doing your testing for linux, are the tests also virtual machines? If so, does one have more RAM then the other? Are you using different versions of any tools? What tests?

**Comment by ThomasWaldmann** [comment]
On FreeBSD (vagrant) it is taking ~3000s on my machine to run the test.
On Linux (vagrant), it is much less (don't have exact numbers, but maybe 300..600s).
Every 64bit vagrant machine has 768MB RAM and a minimal installation of the OS (no GUI).
It is the time for a complete test run like "vagrant up" does automatically.

**Comment by jungle-boogie** [comment]
hmmm, that's a long time, but I'm still a bit unclear of the test you're running. Is it 'vagrant up' as the test?

**Comment by ThomasWaldmann** [comment]
The test is running all the unit tests for a specific python version. fakeroot -u tox -e py34 (or py35).

**Comment by enkore** [comment]
Running without fakeroot - ~402 s

Running with fakeroot - 2800 s

**Comment by jungle-boogie** [comment]
How's it compare on linux?

**Comment by enkore** [comment]
Essentially no difference.

**Comment by ThomasWaldmann** [comment]
@enkore your last post is ambiguous.

**Comment by enkore** [comment]
Clarification: there is essentially no difference in run-time between the test suite on Linux vs. FreeBSD without fakeroot.

**Comment by ThomasWaldmann** [comment]
I am closing this because fakeroot was removed for the freebsd because it also caused other issues.
