### ISSUE TITLE
consider pytest-xdist

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#864]
can be used to speed up by using parallel testing.
some tests may need fixing.

in general, this might make sense _after_ refactoring the unittest-based tests to py.test.

**Comment by ThomasWaldmann** [comment]
the fuse mount tests will need fixing for this, they don't work well when running in parallel.

**Comment by enkore** [comment]
I often run the entire test suite with xdist (`-n 20`), and if they pass it's fine -- but failures are often false negatives, with sometimes very strange errors. It seems that even though xdist runs in separate processes that unittest doesn't really like it.

**Comment by enkore** [comment]
xdist tests are iirc currently broken due to  test_invalid_msgpacked_item et al

**Comment by enkore** [comment]
Fixed by #1991
