### ISSUE TITLE
borg create --one-file-system traverses into other filesystems

### ISSUE THREAD

**Issue by bket** [borgbackup/borg#873]
Running borg 1.0.1 on OpenBSD 5.9 with --one-file-system traverses excluded mount points.

Expected behaviour of 'borg create --one-file-system /' is that all mounts excluding '/' are ignored. On OpenBSD this is not the case and all mount points are traversed and back-upped. Workaround is to use --exclude /mountpoint1 --exclude /mountpoint2.

**Comment by ThomasWaldmann** [comment]
@bket thanks for finding the issue and fixing it. @nachtgeist thanks for spotting the bug.

**Comment by ThomasWaldmann** [comment]
fixed in 1.0-maint by https://github.com/borgbackup/borg/commit/8dbbc35b714c62ec49c5e37fae9c4cb2069f24ed - soon to be merged into master also.

**Comment by ThomasWaldmann** [comment]
hmm, maybe I keep this open until after next bugfix release or until the changelog for 1.0.2 was updated.

**Comment by ThomasWaldmann** [comment]
also happens on netbsd. and everywhere where the device number is 0.

**Comment by ThomasWaldmann** [comment]
an easy workaround is available via --exclude /mountpoint1 --exclude /mountpoint2 ...

**Comment by ThomasWaldmann** [comment]
changelog for 1.0.2 updated, closing this.
