### ISSUE TITLE
remove experimental status from borg check --repair?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#876]
this feature is there since a while - can we be confident enough to remove the warning?

**Comment by pepa65** [comment]
I tried using the --repair option but cancelled when I encountered the warning... What are the actual abilities of repair, and what are the chances of making things worse? (Worse than unusable..?)

**Comment by ThomasWaldmann** [comment]
I think the warning is there because while there are no known bugs, there might be unknown bugs or repository states so that repair does not repair or might even make things worse.

So maybe there should be a different warning text?

**Comment by ThomasWaldmann** [comment]
there is another ticket now about documenting why it issues that warning.
