### ISSUE TITLE
borg info show incorrect deduplicated size for non last archive

### ISSUE THREAD

**Issue by infectormp** [borgbackup/borg#883]
**borg info** show incorrect deduplicated size for non last archive. Is this correct? 

**borg info** for 1 archive (initial):
Fingerprint: **2e5c71cdca3320ebfe4ef6c4f9216bc57a55e79090d47ec8d57872618a7bf9d3**
                       Original size      Compressed size    Deduplicated size
This archive:               34.48 MB             34.56 MB             **31.66 MB**
All archives:               34.48 MB             34.56 MB             31.66 MB

**borg info** for 2 archive:
Archive fingerprint: 6e57a82c1c4fea30d9e75eca18e2f3f049f10b950ce7fcbf1d90faa0e9305881
                       Original size      Compressed size    Deduplicated size
This archive:               34.48 MB             34.56 MB             **88.51 kB**
All archives:               68.95 MB             69.13 MB             31.75 MB

**borg info** for 1 archive after 2 archive was made:
Fingerprint: **2e5c71cdca3320ebfe4ef6c4f9216bc57a55e79090d47ec8d57872618a7bf9d3**
                       Original size      Compressed size    Deduplicated size
This archive:               34.48 MB             34.56 MB             **87.42 kB**
All archives:               68.95 MB             69.13 MB             31.75 MB

**Comment by enkore** [comment]
This is correct.

**Comment by infectormp** [comment]
Thank you, now it's more clear.

**Comment by ThomasWaldmann** [comment]
Check if the info docs need clarification regarding this.

**Comment by Ape** [comment]
Maybe it's easier to think as "How much space would I save if I were to delete this archive now?".

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/922
