### ISSUE TITLE
malfunction on big-endian archs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#889]
some refcount computations might go very wrong due to byte-order issues on big-endian architectures (like ppc, mips, s390, sparc, m68k, ...) - often denoted as "BE" or "*eb".

**do not use borg on these architectures for now until these issues have been fixed, repository corruption and data loss is not unlikely.** if you already have begun using borg on big-endian arch, never delete or prune anything from the existing repository and stop using it until a fix is available.

this issue **does not affect the widespread little-endian archs like x86, x64 / amd64 and it also does not affect bi-endian archs when run in little-endian mode (like often the case for ARM and also for mipsel).** These are usually denoted as "LE" or "*el".

we didn't encounter these issues before (in unit tests, in practical testing) as big-endian machines are rather rare nowadays (and even bi-endian archs are mostly run in little-endian mode). borg tried to support different endianness, but it didn't do it at all required places.

@verygreen can you check hashindex merge on ppc64? just create some remote archives, remove the local cache and let it rebuild it. maybe you find more things going very wrong.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/32843802-malfunction-on-big-endian-archs)

**Comment by verygreen** [comment]
so what is it exactly I need to run besides removing local .cache?
just borg info enough? try to create another archive?

BTW, I also tried borg check (on 1.0.0 still) earlier today with nothing to write home about.
```
[root@powermac ~]# borg check backup@backup:/backups/borg/powermac::2016-04-11
Orphaned objects check skipped (needs all archives checked).
```

I also tried to extract some files from the archives on x86 box and that did work as expected.

**Comment by enkore** [comment]
PR for this would be #890

As we noticed in IRC the differences between adding LE numbers in BE can range from "the same result" to "totally different thing". It might work for refcounts < 2**8 and some cases above that. It might also lead to data loss if a lower refcount is calculated than should be.

**Comment by ThomasWaldmann** [comment]
yes, another borg create would trigger chunkindex rebuild (if there is no chunkindex or when it is out of sync because you push from 2 machines into 1 repo).

**Comment by verygreen** [comment]
no problems with removed .cache/borg and creating a new archive here.

I also tried borg check on the whole repo as opposed a single archive and also got not isible problems other than a missed \n in the output:
```
[root@powermac ~]# borg check backup@backup:/backups/borg/powermac
[root@powermac ~]# gments 99.9%

```

**Comment by ThomasWaldmann** [comment]
fix: https://github.com/borgbackup/borg/commit/dd95d0ebe84b05bfd409561a2cacf00af8013a0e
