### ISSUE TITLE
--checkpoint-interval default too small

### ISSUE THREAD

**Issue by martin21** [borgbackup/borg#896]
borgbackup writes local chunk cache every 5 minutes, causing burst writes of more than 1 GiB each time.

I just saw this again, vmstat 1 output:

procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 1  3 2438352 130788    132 10609920  136   20 10316 126072 6832 28580 13 24 50 13  0
 1  3 2438400 154100    132 10558816    0   48   428 472396 3306 18648  4 14 35 47  0
 0  3 2438400 168484    132 10560680    0    0   452 452384 2268 2732  2  3 39 56  0
 0  2 2438400 183004    132 10561820    0    0   280 403788 2639 4671  5  5 38 53  0
 0  2 2438400 196108    132 10564468    0    0  1448 193200 2537 4000  6  7 43 45  0
 2  1 2438400 187444    132 10574308    0    0 12156 11252 4628 12536 14  7 65 15  0

the cache is:

merkaba:~> du -sh .cache/borg 
2,6G    .cache/borg

If I add the values of vmstat block out I get already 1,6 GiB of data written. Thats more than half of the cache. If it does that every 5 minutes its quite an amount of writes. Does borgbackup fully rewrite the cache every 5 minutes or does it just write changes to the cache?

(That said good SSDs can take a lot of writes, but still, this seems excessive to me.)

**Comment by martin21** [comment]
Okay, to be fair, it is still an BTRFS RAID 1, so divide that 1,6 GiB by two, as BTRFS wrote the same data to each of the SSDs. Still if this would be harddisks writing about 800 MiB would cause a considerable delay. Does borgbackup need to write local caches on every checkpoint on the remote repo? Can´t it rebuild the local cache in case it is not current?

(I know I can disable local cache completely and consider doing just this as I have a fast network connection here.)

**Comment by infectormp** [comment]
You can change checkpoint-interval ```--checkpoint-interval SECONDS```

**Comment by martin21** [comment]
Thanks, I adapted my script. I briefly looked for something like this, but overlooked it in the manpage. Its documented. So… closing.

**Comment by ThomasWaldmann** [comment]
reopening it so we change the default to a bigger value, e.g. 30min.

**Comment by martin21** [comment]
Thank you.
