### ISSUE TITLE
Failed trying to upgrade borg from 0.30 to 1.0

### ISSUE THREAD

**Issue by ovizii** [borgbackup/borg#904]
I tried this once before with a similar messy result. Any ideas what this means? I am using the precompiled binary from your downloads.

`root@alfred:~# borg -V
borg 1.0.1
root@alfred:~# borg upgrade /mnt/backup/alfred

/bin/sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1497, in main
  File "borg/archiver.py", line 1451, in run
  File "borg/archiver.py", line 621, in do_upgrade
  File "borg/upgrader.py", line 39, in upgrade
  File "shutil.py", line 353, in copytree
shutil.Error: [('/mnt/backup/alfred/data/0', '/mnt/backup/alfred.upgrade-2016-04-14-14:35:17/data/0', "[Errno 5] Input/output error: '/mnt/backup/alfred.upgrade-2016-04-14-14:35:17/data/0'"), ('/mnt/backup/alfred/data', '/mnt/backup/alfred.upgrade-2016-04-14-14:35:17/data', "[Errno 5] Input/output error: '/mnt/backup/alfred.upgrade-2016-04-14-14:35:17/data'"), ('/mnt/backup/alfred', '/mnt/backup/alfred.upgrade-2016-04-14-14:35:17', "[Errno 5] Input/output error: '/mnt/backup/alfred.upgrade-2016-04-14-14:35:17'")]

Platform: Linux alfred 4.2.8-1-pve #1 SMP Sat Mar 19 10:44:29 CET 2016 x86_64
Linux: debian 8.4
Borg: 1.0.1  Python: CPython 3.5.1
PID: 28066  CWD: /root
sys.argv: ['borg', 'upgrade', '/mnt/backup/alfred']
SSH_ORIGINAL_COMMAND: None

root@alfred:~#
`

**Comment by ThomasWaldmann** [comment]
There seems to be some library issue with ncurses.
Besides that, there is an I/O Error on your filesystem mounted at /mnt/backup - disk defect?

**Comment by ovizii** [comment]
any idea what to do about the ncurses issue? 

I mounted an NFS share where borg 0.30 used to do its backups daily: 
`/bin/mount -t nfs ftpback-xxx-xxx.ovh.net:/export/ftpbackup/xxx.ipxxx.eu /mnt/backup`

**Comment by enkore** [comment]
> any idea what to do about the ncurses issue?

The error message gives the impression that the linkage error is in /bin/sh, but that seems kinda unlikely to me. But if it were in the "borg" binary, then it wouldn't run; symbol lookup errors should be fatal...?

--

Since it's NFS an EIO on your end might not be caused by an EIO on the server.

**Comment by ovizii** [comment]
if it helps, this is the binary I am using: https://github.com/borgbackup/borg/releases/download/1.0.1/borg-linux64

> Since it's NFS an EIO on your end might not be caused by an EIO on the server; in any case this looks like a filesystem level error.
Any idea what to do? Worst case I'd delete the "upgrade-try-folder" alfred.upgrade-2016-04-14-14:35:17 - backup the original REPO and start fresh, without upgrading anything... but this seems kinda frustrating as it messed up just like the other machine: https://github.com/borgbackup/borg/issues/706

**Comment by enkore** [comment]
Borg gets an EIO when it tries to (basically) "cp -al" on the paths mentioned in the exception. Do you get the same/similar result when you try that on the console?

**Comment by ovizii** [comment]
nope, worked just fine:
`root@alfred:~# cp -al /mnt/backup/alfred /mnt/backup/alfred-test
root@alfred:~#
`

**Comment by enkore** [comment]
Can you try upgrade (and/or cp -al) again? If cp -al works then the copytree shouldn't fail either. If the FS is "flaky" in this regard both should be affected.

**Comment by ovizii** [comment]
I did it another 3 times with a few minutes in-between and always getting the same results :-( 

`root@alfred:~# borg upgrade /mnt/backup/alfred
/bin/sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 1497, in main
  File "borg/archiver.py", line 1451, in run
  File "borg/archiver.py", line 621, in do_upgrade
  File "borg/upgrader.py", line 39, in upgrade
  File "shutil.py", line 353, in copytree
shutil.Error: [('/mnt/backup/alfred/data/0', '/mnt/backup/alfred.upgrade-2016-04-14-15:39:08/data/0', "[Errno 5] Input/output error: '/mnt/backup/alfred.upgrade-2016-04-14-15:39:08/data/0'"), ('/mnt/backup/alfred/data', '/mnt/backup/alfred.upgrade-2016-04-14-15:39:08/data', "[Errno 5] Input/output error: '/mnt/backup/alfred.upgrade-2016-04-14-15:39:08/data'"), ('/mnt/backup/alfred', '/mnt/backup/alfred.upgrade-2016-04-14-15:39:08', "[Errno 5] Input/output error: '/mnt/backup/alfred.upgrade-2016-04-14-15:39:08'")]

Platform: Linux alfred 4.2.8-1-pve #1 SMP Sat Mar 19 10:44:29 CET 2016 x86_64
Linux: debian 8.4
Borg: 1.0.1  Python: CPython 3.5.1
PID: 15572  CWD: /root
sys.argv: ['borg', 'upgrade', '/mnt/backup/alfred']
SSH_ORIGINAL_COMMAND: None

root@alfred:~#
`

regarding paths: 
`root@alfred:~# ls -al /mnt/backup/alfred.upgrade-2016-04-14-14\:35\:17/
total 50450
drwxr-xr-x  3 postfix users        8 Apr 14 05:36 .
drwxr-xr-x 11 postfix users       14 Apr 14 15:39 ..
-rw-------  5 postfix users      148 Dec 12 12:34 config
drwx------  3 postfix users        3 Dec 12 12:34 data
-rw-------  5 postfix users     9217 Apr 14 05:31 hints.5284
-rw-------  5 postfix users 51516698 Apr 14 05:31 index.5284
-rw-------  5 postfix users       50 Apr 14 05:36 lock.roster
-rw-------  5 postfix users       26 Dec 12 12:34 README
`
`root@alfred:~# ls -al /mnt/backup/alfred.upgrade-2016-04-14-14\:35\:17/data/
total 46
drwx------ 3 postfix users    3 Dec 12 12:34 .
drwxr-xr-x 3 postfix users    8 Apr 14 05:36 ..
drwx------ 2 postfix users 1966 Apr 14 05:31 0
`
Please don't ask why its all owned by postfix, I have been executing all these upgrade commands as root.

Checked again with -n 
`root@alfred:~# ls -aln /mnt/backup/alfred.upgrade-2016-04-14-14\:35\:17/
total 50450
drwxr-xr-x  3 100 100        8 Apr 14 05:36 .
drwxr-xr-x 11 100 100       14 Apr 14 15:39 ..
-rw-------  5 100 100      148 Dec 12 12:34 config
drwx------  3 100 100        3 Dec 12 12:34 data
-rw-------  5 100 100     9217 Apr 14 05:31 hints.5284
-rw-------  5 100 100 51516698 Apr 14 05:31 index.5284
-rw-------  5 100 100       50 Apr 14 05:36 lock.roster
-rw-------  5 100 100       26 Dec 12 12:34 README
root@alfred:~#
`
indeed inside /etc/passwd I see
`postfix:x:100:104::/var/spool/postfix:/bin/false`

and yet, whoami yields: root

**Not sure if this is the problem somehow? Should I risk a chown -R root:root /mnt/backup/alfred ?**

**Comment by ThomasWaldmann** [comment]
hmm, maybe related to (no_)root_squash? strange user names might show up if user ids on both systems do not match. otoh, root always is 0.

**Comment by ovizii** [comment]
So to sum it up: 

- delete the "upgrade-try-folders" alfred.upgrade-2016-04-* 
- backup the original REPO 
- start fresh, without upgrading anything
