### ISSUE TITLE
fadvise DONTNEED needs to be page aligned

### ISSUE THREAD

**Issue by verygreen** [borgbackup/borg#907]
Looking at the kernel code, we can see that if we don't align the advise, some of it is disregarded:

```
        case POSIX_FADV_DONTNEED:
                if (!inode_write_congested(mapping->host))
                        __filemap_fdatawrite_range(mapping, offset, endbyte,
                                                   WB_SYNC_NONE);

                /*
                 * First and last FULL page! Partial pages are deliberately
                 * preserved on the expectation that it is better to preserve
                 * needed memory than to discard unneeded memory.
                 */
                start_index = (offset+(PAGE_SIZE-1)) >> PAGE_SHIFT;
                end_index = (endbyte >> PAGE_SHIFT);
```
I guess if you deal with a lot of small files, that might cause unnecessary cache pollution.

**Comment by ThomasWaldmann** [comment]
Small files (<512K) will likely end up as 1 chunk (1 read, 1 fadvise call), so we don't have a problem there, right?

**Comment by verygreen** [comment]
I mean, imagine a file that's less than 4k, or the size is not 4k aligned (page aligned on arches that have pages bigger than 4k).
When you do fadvise from 0 to end of such file the first (or the only) page is not dropped and stays in cache. If you have many files like that, you fill the cache with such pages potentially displacing some pages that were actually needed.

Also I just realized the other problem here is after you run full backup like that, it would invalidate entire pagecache for chunks that were read (so everything on first run, changed parts for the rest of it) even if they are frequently accessed. Though I guess that's fine and stuff would be re-read back pretty soon if it's really frequently used.

**Comment by ThomasWaldmann** [comment]
well, if the kernel does not free it, even if we fadvise start-to-end, we can't do much about it, can we?

the one-time invalidation is a known effect and considered harmless. a few guys deemed it bad like "it invalidates my super-big super-important super-heavy-load database files" - but the rebuttal of course is that one does not backup live db files as that would never be consistent anyway (and, as you noticed, it would be quickly reloaded into the cache again anyway).

**Comment by verygreen** [comment]
Just page-align the ending offset and the kernel would throw it away.

**Comment by ThomasWaldmann** [comment]
even if ending offset is beyond file end?

**Comment by verygreen** [comment]
Yes, why would that be a problem?

```
        /* Careful about overflows. Len == 0 means "as much as possible" */
        endbyte = offset + len;
        if (!len || endbyte < len)
                endbyte = -1;
        else
                endbyte--;              /* inclusive */

```

**Comment by verygreen** [comment]
hm, actually I guess I should read more code and less comments.
It's only first page that is affected, last page would be truncated entirely even if we only asked to truncate a single byte there based on the code I quoted in the ticket?

**Comment by ThomasWaldmann** [comment]
yeah, so it doesn't look like a problem at all (when reading the last 2 C code lines from OP).

**Comment by verygreen** [comment]
ok. then I am closing this.

**Comment by verygreen** [comment]
I am reopening this since the problem is actually still there, it's just a bit different one.

Problem 1: according to the code from mm/fadvise.c - the first partial page is not going to be truncated. I thought this is all fine because reads are going to be nicely page-aligned but alas, actually both read offsets and lengths are pretty much random so lots of partial page reads. That's lots of pages not thrown away from the cache that we no longer need.
Problem 2: The last page of the read is going to be truncated entirely, including the portion that we have not read yet (but plan to read next). This will make next read slower as we'll need to reread the page again.

I performed a simple test on borg 1.0.1 with and without the patch (below) and  on a rotating disk I see a consistent 10% read speed improvement with the patch.
The test was to add a 3664773120 bytes long file (generated from /dev/urandom) into a tmpfs archive.

repository was deleted and recreated for every run. /mnt was unmounted and mounted back between runs.
Borg 1.0.1 vanilla:
```
[root@intelbox2 ~]# time borg create /tmp/test-backup2::Initial /mnt/test
real	1m36.973s
user	0m40.927s
sys	0m4.793s
...
[root@intelbox2 ~]# time borg create /tmp/test-backup2::Initial /mnt/test

real	1m36.626s
user	0m40.686s
sys	0m4.889s
```

Borg 1.0.1 + the patch to page-align posix_advise calls:
```
[root@intelbox2 ~]# time ~green/bk/borg/.tox/py34/bin/borg create /tmp/test-backup2::Initial /mnt/test

real	1m25.212s
user	0m40.501s
sys	0m4.822s
...
[root@intelbox2 ~]# time ~green/bk/borg/.tox/py34/bin/borg create /tmp/test-backup2::Initial /mnt/test

real	1m25.380s
user	0m40.746s
sys	0m4.790s
```

the patch:
```
diff --git a/borg/_chunker.c b/borg/_chunker.c
index 5a1ecfa..3cc47a6 100644
--- a/borg/_chunker.c
+++ b/borg/_chunker.c
@@ -163,7 +163,9 @@ chunker_fill(Chunker *c)
         // size limit) kick out data from the cache that might be still useful
         // for the OS or other processes.
         if (length > 0) {
-            posix_fadvise(c->fh, offset, length, POSIX_FADV_DONTNEED);
+           int overshoot = (offset + length) & 4095;
+
+            posix_fadvise(c->fh, offset & ~4095ULL, length - overshoot, POSIX_FADV_DONTNEED);
         }
         #endif
     }

```

**Comment by ThomasWaldmann** [comment]
Like that, it means:
- we optimize for some undocumented behaviour (that could be ok, if we still follow the documented semantics somehow)
- we never fadvise-dontneed the overshot (not even in next round, not for last piece)

**Comment by verygreen** [comment]
re "undocumented behavior" (from fadvise64 manpage):

>        Requests  to  discard  partial  pages are ignored.  It is preferable to
>        preserve needed data than discard unneeded data.   If  the  application
>        requires  that  data  be  considered for discarding then offset and len
>        must be page-aligned.

so they do mention the pages and stuff.
Also kernel has a bug where it discards an ending partial page and we can consider this to be a workaround for a known bug. I'll work on a kernel patch, but how long will it take to propagate to distros is eveybody's guess.

About your second point - We do discard the later portion in the next read, actually (when we rollback the offset). But indeed the regression here is we never discard the last page of a non-page-aligned-sized file, so we need to detect if we are at EOF and don't adjust the size then, I guess.

**Comment by enkore** [comment]
Stupid question, but wouldn't be POSIX_FADV_SEQUENTIAL|POSIX_FADV_NOREUSE sufficient / simpler for this?

**Comment by verygreen** [comment]
No. The problem is, you can only have one advise per syscall.

Here's the linux kernel code:
```
        switch (advice) {
        case POSIX_FADV_SEQUENTIAL:
                f.file->f_ra.ra_pages = bdi->ra_pages * 2;
                spin_lock(&f.file->f_lock);
                f.file->f_mode &= ~FMODE_RANDOM;
                spin_unlock(&f.file->f_lock);
                break;
...
        case POSIX_FADV_NOREUSE:
                break;
```

So it's not a bad idea to do POSIX_FADV_SEQUENTIAL as it would open up a readahead window some, but POSIX_FADV_NOREUSE is a noop.

**Comment by ThomasWaldmann** [comment]
The advice we need most is "DONTNEED", so the cache does not fill with data we never need again.

**Comment by verygreen** [comment]
I am closing this again with the patch from #914 merged

**Comment by ThomasWaldmann** [comment]
patch is in 1.0-maint, will soon get merged into master also.

**Comment by ThomasWaldmann** [comment]
Note: the fixed blocksize chunker does not have this workaround yet, see PR #4238.
