### ISSUE TITLE
OS X based dev wanted for regular testing and binary builds

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#913]
virtualbox killed the capability to run OS X on non-Apple hardware, thus we need some developer with Apple hardware who:
- regularly runs the test suite
- regularly (best) or at least after releases builds standalone binaries, tests, gpg signs and releases them

The procedure is currently somehow documented in the Vagrantfile, see "darwin64", but due to above, will be removed from there.

**Comment by ThomasWaldmann** [comment]
See also #933 for a fix the vagrant machine needs to build a binary WITH lzma support.

**Comment by ThomasWaldmann** [comment]
Some hints about what is to do:
- you need to deal with git, so you can keep up-to-date with development, check out release tags, etc.
- I used vagrant and the darwin64 part of our Vagrantfile to run tests on OS X and at same time build the binary (the tests also run with the built binary).
- OS X version for building might be important, the binary should be as flexible regards to the required OS X version as possible (like: not just work on 1 OS X version).
- you need to gpg sign the built binary to avoid tampering and to enable users to check whether the binary is really from you and still is like you built it.

**Comment by ThomasWaldmann** [comment]
a current testing job would be to test latest osxfuse with borg.

**Comment by zyradyl** [comment]
By latest, do you want the beta or do you want straight from their VCS?

**Comment by ThomasWaldmann** [comment]
I meant the latest (pre)release.

The latest borg 1.1.0b2 was built with 3.5.2.
The latest borg 1.0.7 was built with 3.4.1.

So, useful tests are testing the borg branches (1.0-maint for 1.0.x, master for 1.1) with newer osxfuse releases than these.

**Comment by zyradyl** [comment]
On it!

**Comment by zyradyl** [comment]
Hey hey. So I spent the past little bit setting up a system through VMWare Fusion (I don't know much about Vagrant, but I'll work on learning it after I get something set up.)

Right now there are 3 images, One is the primary machine that has all the steps ran up to `pyenv-build-venv` ran on it, and the next two are linked clones, one with OSXFuse 3.5, and another with the latest OSXFuse Beta (Both through `brew cask`). Each VM has images set up for APFS, HFS+, HFSX, JHFS+, and JHFSX. I'm working on a bash script to run through and automate building the different borg versions and running the Unit Tests, then posting the resultant things to Pastebin.

Again, I don't know a lot of Python but I figure the least I can do is contribute Unit Tests and CPU cycles.

What I'm thinking about doing is running a borg repo on each filesystem with an amount of data you suggest for testing, and going from there.

So I'm really just looking for guidance. I don't mind doing testing, but I'm not sure what all you need.

- Is the above system Overkill? If so, what do you consider important to test, and what is less important?
- Would you prefer I focus on the latest versions of `brew cask`s OSXFuse Betas only, or continue doing release and beta?
- How much data is a good test set? I have a 127GB repository that is 2.28TB fully expanded, but I simply don't have the room to mess with that whole set. Would 5-10GB work? What about less?
- What practical operations do you want tested? I've never used Borgs Fuse component.

Sorry to post so many questions, just trying to figure out how to best help.

**Comment by ThomasWaldmann** [comment]
For the osxfuse tests, I think it is important to test new osxfuse releases, esp. if bigger version number steps occur (like changed x or y in x.y.z). Not sure if we need to test osxfuse betas.

I don't think the dataset needs to be large for the generic borg tests, more interesting is having all sorts of metadata that might come up on a OS X system and a sparse file.

**Comment by ThomasWaldmann** [comment]
solved by vagrant vm.
