### ISSUE TITLE
Should borg store writes be always purged from memory?

### ISSUE THREAD

**Issue by verygreen** [borgbackup/borg#915]
While on the surface it looks like borg writes are write-once, read-never so it's not worth to pollute the cache with those, this totally ignores things outside of the backup process.

For a dedicated backup server whose whole purpose is just serving backups, it makes total sense to not discard write cache as that speeds up subsequent check/info/etc operations.

@ThomasWaldmann thinks there's a risk in the form of
> if your backup is big, it will flood the  backup dest server's cache in same way as read cache 
> would flood backup src server

Though in reality I guess in many cases influx of data will be slower than the writeout rate.

Overall the most flexible thing to do seems to be to create an extra option that would control whenever writeout data is dropped from cache.
This setting would be enabled by default, unless started as borg server in which case it would be disabled. But people would be able to override this behavior if desired for whatever reason.

**Comment by ThomasWaldmann** [comment]
But maybe the check is better if it really has to read the stuff from disk, so you check what is on disk (and not what is in the cache).

Of course, normally this should be the same, but if one assumes everything is working ok, why check at all? :)

**Comment by verygreen** [comment]
But during check the data  might be cached for other reasons (i.e. somebod just did borg info/list).
If you insist on check always going straight to disk - use direct IO or flush the caches before reading (After opening). Might make sense to mke this an option too if you want, I guess.

**Comment by enkore** [comment]
> (i.e. somebod just did borg info/list).

Which do integrity checks on everything they read

**Comment by ThomasWaldmann** [comment]
@enkore why did you close?

**Comment by enkore** [comment]
imho this is resolved from the discussion above - writes are removed from the cache to ensure that a borg-check or similar run after a create actually reads what has been written to the disk.
