### ISSUE TITLE
default path to repo (nit-picky)

### ISSUE THREAD

**Issue by kloetzl** [borgbackup/borg#917]
Running borg v1.0.1 on Arch I get the following error:

```
path/to/repo$ borg list
usage: borg list [-h] [--critical] [--error] [--warning] [--info] [--debug]
                 [--lock-wait N] [--show-rc] [--no-files-cache] [--umask M]
                 [--remote-path PATH] [--short] [--list-format LISTFORMAT]
                 [-P PREFIX]
                 [REPOSITORY_OR_ARCHIVE]
borg list: error: argument REPOSITORY_OR_ARCHIVE: Invalid location format: ""
```

Technically, the argument `REPOSITORY_OR_ARCHIVE` is in brackets, thus considered *optional*  and should default to `.`. Same issue with `borg check`. Call me nit-picky, but I think you should either default to `.` or remove the brackets. ☺

**Comment by Ape** [comment]
It's optional when you have `BORG_REPO` env variable set. Otherwise it should be mandatory. I'm not sure what is the best way to reflect this with the usage line.

**Comment by kloetzl** [comment]
What is the reasoning behind not defaulting to `.`?

**Comment by enkore** [comment]
For some commands it doesn't make sense (`borg extract` comes to mind); making this consistent is more important imho than not having to type a few characters for *some* commands. If you want "." as the default, you can put `export BORG_REPO=.` in your `.*shrc`... ;)

**Comment by ThomasWaldmann** [comment]
@kloetzl if find it a bit unusual to have the current workdir inside the repo (so the repo is ".").

usually the repo is used from the outside and the only people going into there are developers or curious users.

if you have one standard repo per machine, setting the abs. path / url of that as BORG_REPO avoids a lot of typing (both for borg or for cd), so I think that is a good solution. Or set it to "." if you like, as @enkore suggested.

**Comment by kloetzl** [comment]
It was just a suggestion. Anyways, thanks for making such a great tool! :+1:
