### ISSUE TITLE
repository wide verification

### ISSUE THREAD

**Issue by fmitha** [borgbackup/borg#924]
If I want to do repository wide verification, there is currently no efficient way to do it.

I can run `borg extract -n` on individual archives. I could loop this over all archives in a repository, but this is very inefficient, and runs contrary to the deduplicating principle. All chunks should be verified only once.

So some repository wide verification which checks all the chunks would be useful.

***

:moneybag: [there is a bounty for this](https://www.bountysource.com/issues/33028034-repository-wide-verification)

**Comment by ThomasWaldmann** [comment]
There is also `borg check`.

**Comment by enkore** [comment]
Yeah but that only does CRC32 verification. At the chunk length probably still okay for bit rot detection, but not good enough for tamper detection.

Btw. check "kind of" does this if there is no manifest in the repo. It'll iterate over all chunks and decrypt them, which then also verifies their integrity.

I'd propose something like `borg check --full/thorough/paranoid` for this.

**Comment by ThomasWaldmann** [comment]
We can do that, but it won't be cheap. Lots of CPU for decrypt/decompress/hash and for remote repos also lots of traffic.

**Comment by fmitha** [comment]
For remote repositories, would it be possible to run such verifications directly on the remote site?

**Comment by ThomasWaldmann** [comment]
borg check (repo only, simple crc32 check): yes

for encrypted repos, real verification needs verifying the hmac and thus needs the hmac key - only the client has that key, thus: no

**Comment by fmitha** [comment]
Ok. How about for non-encrypted repositories?

Also, I was wondering, you earlier wrote:

> for remote repos also lots of traffic.

But if you are throwing the information away (all you need to know is that that the verification succeeded), why does there need to be lots of traffic coming back to local? If that is what you meant (and I assume you did), then all you need to know is that the verification succeeded. And if it didn't, you need to get the error. But that shouldn't take much traffic either.

**Comment by enkore** [comment]
> Ok. How about for non-encrypted repositories?

If you trust the remote anyway, just run the check command on the server?

**Comment by Ape** [comment]
Why is the hash calculated after compression and encryption?

**Comment by enkore** [comment]
There are two different HMACs with two different keys used for two different purposes:

- One is for the chunk ID and is over the uncompressed, unencrypted data as an identity function of the data. This is an identity MAC and can be used to detect exchanged data.
- One is the authentication HMAC. This is an encrypt-then-MAC scheme which is often recommended over other schemes, because (synposis) it's hard to fuck up.

**Comment by enkore** [comment]
> EDIT: And also isn't it unnecessary to require the key for hash verification. It would be enough to have just regular hashes for the chunks and then sign the chunk hashes on archive or repository level.

No, this would make fingerprinting attacks very easy.

**Comment by enkore** [comment]
Scheduled for 1.1

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/commit/0bceaf0736d503c7b5718275e340d2f0ab36185f
