### ISSUE TITLE
easier item metadata access (source)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#926]
all these item keys are usually used like item[b'foo'] which is unpretty and also unsafe against typos.

an idea to solve that is to use some special object, not just a dict, and access such stuff as item.foo.

if we stay away from a dynamic implementation, we could just define properties for all needed and use tab completion in future.

item.get(key, default) could be reimplemented accordingly.

**Comment by enkore** [comment]
The only dynamic access I found (with `ag 'item\[[^b]' borg`) is in platform_freebsd.pyx in acl_get / _get_acl. That wouldn't be caught by a simple `sed`, but needs to be written with setattr.

**Comment by ThomasWaldmann** [comment]
note: we should first merge (or reject / close) all PRs, this change is going to be a total merge spoiler.

**Comment by enkore** [comment]
Also stuff like `b'chunks' in item` is quite common. Continuing to use `in`, but then accessing stuff with attributes is unclean and unexpected, while regularly doing hasattr() is convoluted. Maybe add a convenience `has` method?

**Comment by Ape** [comment]
What about something like this:

```python
if item.chunks:
    process_chunks(item.chunks)
```

**Comment by enkore** [comment]
Writing it that way invites errors for falseish values. The example would need to be

```py
if item.chunks is not None:  # or some other sentinel value
   process_chunk(item.chunks)
```

It also means that all items would always carry (in-memory when reading but also when writing) all possible attributes around. For reading existing repositories code needs to be added that fills in missing attributes with their correct sentinel values.

**Comment by Ape** [comment]
I agree. `None` as the sentinel value is better than the syntax I proposed. Well my syntax is fine when you actually want to say:

```python
item.chunks is not None and item.chunks != []
```

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/981
