### ISSUE TITLE
Is there a way to completely ignore timestamp ?

### ISSUE THREAD

**Issue by shmox** [borgbackup/borg#930]
I would like to completely ignore timestamps in backup process.
What i need is to don't store timestamps in backup process, and to detect changes based only on files contant changes.

Here is my problem:

I have an angular js web application directory, that i offten compile with grunt build command, but it generates changes in timestamps in many files, but their content changes only in few files.
When i backup with --stats, the generated backup is about 170kb, for me this is too much because the files content changes are just about bites.

Sorry for my bad english :(

**Comment by Ape** [comment]
Perhaps you should exclude the build directory from the backups if it is a problem.

**Comment by ThomasWaldmann** [comment]
the mtime is only a indicator for borg to know which files may have content changes.
it will then chunk the file and only store new chunks to the repo.
the chunk size is at least min(filesize, 512KB), so for small files, it will just backup the whole file (or not, if unchanged content).

the minimum (and also statistically medium) chunk size used to be smaller in attic and early borg versions, but then you quickly run into memory issues because the chunk index grows way too big.

**Comment by shmox** [comment]
@Ape , no i need it because some files (only 2) have content changed.
@ThomasWaldmann, Many thanks for your reply now it's clear :) can you tell me please why all files metadata need to be backed up ? does borgbackup work like that or if in the future updates suppose you add a function like --ignore-metadata, and check only checksums can it work ?
If this addition can be added it will be awesome :)

PS: I am on windows 10 and using cygwin, Borgbackup is just awesome, i would like to thanks all contributors. if borgbackup can do volum shadow copy on windows it will be a must have for sysadmins on windows

**Comment by ThomasWaldmann** [comment]
@shmox every borg backup is a full backup (logically, doesn't mean it is big as it just references already-there-in-repo chunks that did not change). thus it needs to know all files that were there on your source disk at time of the backup. as it deduplicates the files metadata also, it's quite small.

If you use it with cygwin, be careful, that is rarely tested and (AFAIK) we do not have a windows-based developer yet. See also the issue tracker about some known cygwin/borg issues.
The VSS stuff is something that needs a windows-based developer who writes just a wrapper around borg that first snapshots, then calls borg, then releases the snapshot.

So, I don't see anything to do here in this ticket, close?

**Comment by shmox** [comment]
Okay thank you, close :+1:
