### ISSUE TITLE
investigate lvm thin provisioning

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#949]
lvcreate -T / man lvmthin

check if they support SEEK_HOLE, SEEK_DATA api on the lv device device file, so our future sparse file support would kick in.

**Comment by infectormp** [comment]
The [SEEK_HOLE and SEEK_DATA](http://man7.org/linux/man-pages/man2/lseek.2.html) operations are supported for the
       following filesystems:
       *  Btrfs (since Linux 3.1)
       *  OCFS (since Linux 3.2)
       *  XFS (since Linux 3.5)
       *  ext4 (since Linux 3.8)
       *  tmpfs (since Linux 3.8)
       *  NFS (since Linux 3.18)
       *  FUSE (since Linux 4.5)

**Comment by ThomasWaldmann** [comment]
I have the impression that SEEK_HOLE is generally **not** supported for **block devices**, only for files residing a supporting filesystem.

For block devices, sometimes another API is supported:
- nbd: BLOCK_STATUS, see e.g.: https://github.com/xapi-project/vhd-tool/blob/master/scripts/get_nbd_extents.py

**Comment by ThomasWaldmann** [comment]
related to #14

**Comment by ThomasWaldmann** [comment]
Superseded by #5609.
