### ISSUE TITLE
add a comments field in the entries of the manifest

### ISSUE THREAD

**Issue by frankpolte** [borgbackup/borg#951]
This would allow the user to add a list of tags or any further information (owner, user group, departement, customer id, backup source, ...) about an archive in the manifest. 

It could be saved as a dict or as a string. I would prefer the implementation as a dict, so that the user is more free in the usage and the pattern matcher for the "borg list"-command is more easy to be extended for giving better results. 

The comand line usage should be like the "extra-vars" option in ansible e.g. : --comment="uid=10253 customerid=23651 ..." or it take a JSON-string. 

With the naming "comments" I am not really happy, because I think it is more likely what a "commit message" of git used to be. [ansible doc](https://docs.ansible.com/ansible/playbooks_variables.html#passing-variables-on-the-command-line)

**Comment by infectormp** [comment]
https://github.com/borgbackup/borg/pull/847

**Comment by enkore** [comment]
This is scheduled for 1.1, see #847 and [latest docs](http://borgbackup.readthedocs.org/en/latest/usage.html#borg-create).

**Comment by frankpolte** [comment]
but implementing it as a dict would be more useful than just a string

**Comment by enkore** [comment]
That really depends on the use case. You can put structured data, e.g. XML, JSON, YAML, ... in there with little trouble (-- although reading the comment from fd/file/stdin might be more useful for larger 'comments'), as well as simple, free-form text comments.

**Comment by ThomasWaldmann** [comment]
close?
