### ISSUE TITLE
making the borg mount command non locking

### ISSUE THREAD

**Issue by frankpolte** [borgbackup/borg#952]
what would it take to make the mounting non locking?

**Comment by infectormp** [comment]
see also https://github.com/borgbackup/borg/issues/768, https://github.com/borgbackup/borg/issues/420

**Comment by enkore** [comment]
Duplicate of #768

**Comment by frankpolte** [comment]
I just wanted to discuss it with my issue [#953](https://github.com/borgbackup/borg/issues/953) and [#954](https://github.com/borgbackup/borg/issues/954)
