### ISSUE TITLE
add a "protected" flag for archives

### ISSUE THREAD

**Issue by frankpolte** [borgbackup/borg#953]
e.g. as a field in the entries of the manifest like the timestamp.

The use case would be an archive that represents a publication- or a "certification approved"-state. The delete function only needs to check the flag and that return without deleting it. This affects the pruning as well of course.

Maybe it could be further implemented that way, that all the chunks of all the protected archives are not written by borg, so that a bug in borg could not harm the protected backup states.
Further this would lead to the possible implementation of a non-locking borg mount feature. [#952](https://github.com/borgbackup/borg/issues/951)

**Comment by ThomasWaldmann** [comment]
We have tags now, so the question is now how to use them.

Let users do it via archive matching (-a) and `borg tag` command:
- --match-archives (-a) currently supports being given multiple times, so AND(tag1, tag2, ...) is possible.
- but: there is no "NOT" yet.

Or hardcode the matching into borg delete / borg prune, but use a tag that users can set with borg tag.

Or hardcode it into borg and use some extra tags / flags and some new command.

-

**Comment by ThomasWaldmann** [comment]
B) sounds the easiest:
- have a tag "PROT", users can set/add/remove via `borg tag`
- do not let users delete archives with PROT
- remove PROT archives from the archives list before prune does its keep/delete computation (so they do not influence that computation and also never get delete)

**Comment by ThomasWaldmann** [comment]
Or, more flexible: add a prune option `--keep-tag` where one can give the tag of archives that should be always kept.

**Comment by ThomasWaldmann** [comment]
New idea: have a subclass of tags that are also used by borg internally:

- prefix them somehow to make these tags **special**, e.g. `@PROT`.
- do not prune, delete or recreate any archive with tag `@PROT` (exception: borg check --repair is allowed to delete the archive if it is defective)
- allow adding/removing the protective tag via `borg tag --set/--remove`
- disallow erasing any **special tag** accidentally by `borg tag --set=SOME,THING,ELSE`
