### ISSUE TITLE
Additional ideas for the protected state of issue [#953]

### ISSUE THREAD

**Issue by frankpolte** [borgbackup/borg#954]
[#953](https://github.com/borgbackup/borg/issues/953)

Maybe it could be further implemented that way, that all the chunks of all the protected archives are not written by borg, so that a bug in borg could not harm the protected backup states.
Further this would lead to the possible implementation of a non-locking borg mount feature. [#952](https://github.com/borgbackup/borg/issues/952)
the counter argument would be a worse deduplication/compression ratio of  borg and a more complicated create-algorithm. this could even lead to the need of a compactify option in the check command.
but maybe others would like to have such a feature as well this is a trade-off.

**Comment by ThomasWaldmann** [comment]
Protection on a per chunk-level against borg bugs is likely too much effort and rarely needed.

There can be other things happening to your chunks also (like disk errors, datacenters burning down), so having multiple repos at different places is a good way to deal with that.

**Comment by ThomasWaldmann** [comment]
side note: borg2 can now mount a repo or archive using a shared lock.
