### ISSUE TITLE
Please sign tags properly

### ISSUE THREAD

**Issue by rumpelsepp** [borgbackup/borg#959]
I just saw, that some borg git tags are not signed.

unsigned: 
- 1.0.1
- 1.0.0rc2

I am not sure if it makes sense to sign them afterwards; but please be careful to not forget to sign the release tags in the future. :)

**Comment by ThomasWaldmann** [comment]
IIRC i did sign them locally, but somehow could not push the signed tag. Maybe it has something to do with the tag used by (created by) when using github releases.

**Comment by enkore** [comment]
push --tags would not overwrite existing tags unless --force is applied

**Comment by ThomasWaldmann** [comment]
```
$ git push --dry-run --tags --force borg 1.0.0rc2
To git@github.com:borgbackup/borg.git
 + 46059f0...5a1424a 1.0.0rc1 -> 1.0.0rc1 (forced update)
 ```
wat?

**Comment by Ape** [comment]
`--tags` tells it to push all changed tags.

**Comment by enkore** [comment]
I see that 1.0.1 is still unsigned / reopening

**Comment by ThomasWaldmann** [comment]
It is currently unclear what the best way and the precise git commands are to fix this.

The procedure must not have a negative impact on the git repo, esp. not on more recent history.

Re-uploading some files / comment text to the 1.0.1 github release would be acceptable, but it must not show up as latest release (see also: http://stackoverflow.com/questions/22822586/swap-latest-release-on-github ).

**Comment by rugk** [comment]
Here are some good resources on git signing:

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

In any case have you considered signing git commits?

**Comment by enkore** [comment]
Some ppl do it some amount of the time. Whether it's meaningful is debatable.

**Comment by ThomasWaldmann** [comment]
I usually sign all releases.
