### ISSUE TITLE
add a BORG_KEYFILE environment variable

### ISSUE THREAD

**Issue by legrostdg** [borgbackup/borg#962]
It would be great to have a BORG_KEYFILE environment variable, to be able to automate encrypted backups (init, create, extract, ...) with external tools (which would of course call borg). My final goal is to write borg properties for [Propellor](https://propellor.branchable.com/).

**Comment by enkore** [comment]
`BORG_KEYS_DIR`? Keyfile names are the basename of the repository directory; duplicate names get a `.N`, Borg just tries them all.

**Comment by legrostdg** [comment]
No, I really mean "BORG_KEYFILE" (or BORG_KEY_FILE), not the DIR where are stored the keys.
Example of what could be difficult: on a freshly installed host, restore a keyfile-encrypted backup. What file borg should take (the keyfile could have been created on another host)? I can store an encrypted file in the Propellor system, but I have to know where it is going to be located (the complete filename).

**Comment by legrostdg** [comment]
> Keyfile names are the basename of the repository directory; duplicate names get a .N, Borg just tries them all.

Is that specified somewhere? If I rely on that, I guess I'm hacking, hoping for the keyfile names code no changing in the future. With "BORG_KEYFILE=/etc/borgkeys/myrepo.key" I would be sure this filename will not change.

**Comment by enkore** [comment]
I see your point (it wasn't clear to me from the ticket text). No, the key file name generation isn't specified, and the names don't matter to Borg. I think what might be easiest / best for your use case until such a feature might be added is to

1. Point BORG_KEYS_DIR to a temporary directory
2. borg init
3. Copy sole file from tempdir -- but maybe also check that "head -n 1 keyfile | grep -q repoid" has exit code 0
4. When extracting, create temporary dir, copy the associated keyfile from $wherever into that dir and point BORG_KEYS_DIR there

**Comment by legrostdg** [comment]
@enkore thanks for your help :-)

Unfortunately it will not work with the way Propellor is implemented. The whole point is having the entire config (with private files and everything) on your laptop, and then deploying it to your hosts. It's not possible to run a command on the server (where I would like to do my backup), getting the result, and storing it back to your Propellor state.

**Comment by ThomasWaldmann** [comment]
fixed by merging https://github.com/borgbackup/borg/pull/1001
