### ISSUE TITLE
Lock Priority

### ISSUE THREAD

**Issue by STRML** [borgbackup/borg#979]
It would be great if there were a way (or a workaround) for the following workflow:

1. App/DB servers backup to a backup server at intervals.
2. That backup server performs its own repository and archive checks at intervals.

The issue is that a long archives check can keep the repository locked, causing backups to fail.

Could it be possible for the lock to indicate priority, and for, say `borg create` to have priority over `borg check`?

If I'm barking up the wrong tree here, please let me know.

Thanks for all your great work on Borg.

**Comment by ThomasWaldmann** [comment]
The backup server can only perform repository check (check the crc32 of the chunks) as it does not have the encryption key. Archive checks must be done clientside as they require decryption and only the client has the key.

interrupting a check for a backup sounds like a problematic idea.

Potential workarounds for you:
- use cron to schedule backups and repo checks so they do not overlap (maybe check at weekend, backup workdays?)
- use separate repos (per app/db server or per small groups of them) so total backup time per repo doesn't take too much of the available backup server time and you can schedule checks in between backups.
- only check last archive(s), not all archives

**Comment by STRML** [comment]
Thanks @ThomasWaldmann. We're 24hrs and already separated, so out of those three #3 sounds the most reasonable. I wasn't aware you could check only a single archive. I'll look into doing that most of the time, and a full archive check at much longer intervals. Given our arch that makes sense.

Much appreciated.
