### ISSUE TITLE
continue working on experimental branch

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#98]
there's still quite some stuff there that is not yet in master (and maybe can't get into master now).

but at least master should be merged into experimental, so that they don't diverge too much.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/pull/129 is compression stuff done a bit differently (and better) than in experimental branch.

better:
- different compression per backup (create --compression cmdline option)
- compression type is stored with the chunk data, so could be different per chunk even
- compatible with zlib chunks made with previous borg versions

**Comment by anarcat** [comment]
is there stuff left in the experimental branch that's worth looking at? i am a little confused by all the merges on the top of the branch. :)

it would be better to have those ideas split into different branches...

**Comment by ThomasWaldmann** [comment]
iirc, it is mostly the new ciphers/hmacs/hashes and the more flexible metadata.

https://github.com/borgbackup/borg/blob/experimental/CHANGES-experimental.txt

**Comment by rumpelsepp** [comment]
> it would be better to have those ideas split into different branches...

yeah; and then rebase these branches on master, when they differ too much.

**Comment by ThomasWaldmann** [comment]
aead-style api was recently merged into master.
guess we won't use anything else from experimental.
