### ISSUE TITLE
borg diff --help should be more specific

### ISSUE THREAD

**Issue by theChaosCoder** [borgbackup/borg#980]
Borg diff shows this: (tested with windows build)

```
bin>borg diff
usage: borg diff [-h] [--critical] [--error] [--warning] [--info] [--debug]
                 [--lock-wait N] [--show-version] [--show-rc]
                 [--no-files-cache] [--umask M] [--remote-path PATH]
                 [-e PATTERN] [--exclude-from EXCLUDEFILE] [--numeric-owner]
                 [--same-chunker-params] [--sort]
                ARCHIVE1 ARCHIVE2 [PATH [PATH ...]]
borg diff: error: the following arguments are required: ARCHIVE1, ARCHIVE2, PATH
```
So I assumed the syntax would be **archive1 archive2 path** 
In my case `borg diff MyData1 MyData2 \\WDMYCLOUD\Backups\PC\Dateien-Borg`

But the right syntax is **path::archive1 archive2** or
`borg diff  \\WDMYCLOUD\Backups\PC\Dateien-Borg::MyData1 MyData2`

**Comment by ThomasWaldmann** [comment]
PATH is a (optional) path inside the archive, it is not the repository's path.

If you see REPO or REPOSITORY as placeholder, that is the repo path (or url).
If you see ARCHIVE, it usually means REPO::ARCHIVE.

Not for ARCHIVE2 here obviously (which might be confusing) as that must be in same repo.
