### ISSUE TITLE
borg lock / unlock cli command

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#989]
some people like to rsync their borg repo to another place (although there is a faq entry describing the potential issues with that: http://borgbackup.readthedocs.org/en/stable/faq.html#can-i-copy-or-synchronize-my-repo-to-another-location ).

if one wants to use rsync or other "copy the repo" mechanism, one should acquire a lock, so the repo is not changing while the copy is running. to script that, we need cli commands.

one also could do it like that:
- lock repo
- snapshot LV or filesystem
- unlock repo
- copy the snapshot

**Comment by edgewood** [comment]
borg with-lock COMMAND ?
-- 
Ed Blackman
Sent from my OnePlus One. Please excuse my brevity.


-------- Original Message --------

**Comment by ThomasWaldmann** [comment]
@edgewood good idea - that way we could automatically unlock when the child process terminates (and borg would return the rc from the child).

**Comment by ThomasWaldmann** [comment]
Hmm, holding a lock while copying the repo has the side effect that the copy will have the lock.
Not a big problem, one can use break-lock if one needs to use that repo, just wanted to note.

**Comment by ThomasWaldmann** [comment]
see PR #990.
