### ISSUE TITLE
Remove dependency of setuptools

### ISSUE THREAD

**Issue by bpereto** [borgbackup/borg#993]
Borg can not be used without setuptools installed. For packaging reasons it would be good to have as less deps as possible.

As far as I understand, setuptools is after install of borg only used for the main script and entry point.
We could drop that.

borg without setuptools installed:
```
Traceback (most recent call last):
  File "/bin/borg", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

What about a simple script to remove the need of setuptools:
```
from borg.archiver import main

if __name__ == "__main__":
	main()
```

**Comment by RonnyPfannschmidt** [comment]
thats a artifact of easy_install/setuptools installation

install with modern pip to go via wheel and setuptools free installation

**Comment by ThomasWaldmann** [comment]
yes, that script is generated.

if you use a wheel and a recent pip to install the wheel, this script is generated:
```
# -*- coding: utf-8 -*-
import re
import sys

from borg.archiver import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by ThomasWaldmann** [comment]
guess there is nothing todo here, closing.
