### ISSUE TITLE
prune - remove old checkpoints

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#998]
#997 is the minimal fix to avoid data loss with prune and checkpoint archives.

but we maybe also don't want to keep a lot of checkpoints, so (always considering `--prefix` of course):

- keep the latest checkpoint
- remove all older checkpoints
- then prune based on timing rules

another thought is that even a checkpoint is a (partial) backup and contains data maybe not contained in another backup. just assume most of the archives are checkpoints and few are finished, then you invoke prune. ofc, we could decide not to care (if you do not monitor your backups and fix the issue why a lot of them get interrupted AND you use prune and kill too much, that is not borgbackup's fault).

**Comment by jdchristensen** [comment]
If many clients backup into the same repo, then saving just the most recent checkpoint might not be enough.

Maybe do this if an option like --prune-old-checkpoints is specified?

**Comment by ThomasWaldmann** [comment]
If you backup more than 1 client to a repo, you must use --prefix in any case to restrict the prune call to only deal with the backups of the client issuing the prune call. This would be same for dealing with checkpoints.

**Comment by dragetd** [comment]
From a usage point of view, a failed backup is an unsuccessful backup. One must monitor the logs.
Of course it is nice to have partial data of older failed backups, but that is not really an 'expected behaviour', even if it might be 'good' in some cases.

I would also prefer if old checkpoints were just pruned automatically.

**Comment by enkore** [comment]
I think that by default keeping checkpoints is the sane policy. --throw-all-these-checkpoints-away could be a valid use case, not sure if it's important enough. Duplicating all the prune options for checkpoints seems bloated and unnecessary to me.

**Comment by ThomasWaldmann** [comment]
sure, no duplicated pruning policy just for checkpoints.

--delete-checkpoints could delete them all except if the latest on is not superceded by a even later finished backup, then it would keep the latest one so that resuming works.

**Comment by kinafu** [comment]
I've found one solution for deleting every .checkpoint-archive from a repository:
`borg list "$BORG_REPO" | grep ".checkpoint" | cut -d' ' -f1 | parallel --jobs 1 borg --dry-run delete "$BORG_REPO"::{}`
source: [https://www.solved.tips/clear-checkpoints-borg-repo](url)
(note the switch _--dry-run_)

**Comment by ThomasWaldmann** [comment]
@kinafu `borg list --short` ... | grep "\.checkpoint$" | parallel ...
